### ISSUE TITLE
MIN_IE_VERSION version confusion

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#10002]
With recent changes there is now MIN_{platform}_VERSION settings available.
The IE one is a little odd, with the default being set to -1.
https://github.com/emscripten-core/emscripten/blob/31309a8c12aaf142ec483dbe3edc0aa195c1bbca/src/settings.js#L1523
I imagine that this is intended to mean that IE isn't supported by default, however there are checks that check if MIN_IE_VERSION is less than a number, ie:
https://github.com/emscripten-core/emscripten/blob/31309a8c12aaf142ec483dbe3edc0aa195c1bbca/src/library.js#L4064-L4069

So shouldn't MIN_IE_VERSION be `MAX_INT` (or maybe `12`, as 11 is the current release), not `-1`?

**Comment by juj** [comment]
Err, very sharp eye!

Of course I botched that one up. `-1` means "not supported" only if passed on the command line as `-s MIN_IE_VERSION=-1`. Fix in #10005.
