### ISSUE TITLE
How to pass to image buffer to wasm

### ISSUE THREAD

**Issue by chhaunkar96** [emscripten-core/emscripten#10009]
I'm trying to pass array buffer to wasm OpenCV but some times It throws an exception or some time blank array when using imdecode function.
**Simple HTML:**
`<input type='file' id accept='image/*' onchange='openFile(event)'>`

**Javascript code**

```
 var openFile = function (e) {
            const fileReader = new FileReader();
            fileReader.onload = (event) => {
                const uint8Arr = new Uint8Array(event.target.result);
                passToWasm(uint8Arr);
            };
            fileReader.readAsArrayBuffer(e.target.files[0]);
        };

   function passToWasm(uint8ArrData) {
            // copying the uint8ArrData to the heap
            const numBytes = uint8ArrData.length * uint8ArrData.BYTES_PER_ELEMENT;
            const dataPtr = Module._malloc(numBytes);
            const dataOnHeap = new Uint8Array(Module.HEAPU8.buffer, dataPtr, numBytes);
            dataOnHeap.set(uint8ArrData);
            // calling the Wasm function
            const res = Module._image_input(dataOnHeap.byteOffset, uint8ArrData.length);
        }
```

**C++ code:** 
```
extern "C"
{
   int image_input(uint8_t* buffer, size_t nSize) //query image input
    {
        Mat raw_data = cv::Mat(1, nSize, CV_8UC1, buffer);
        img_object = cv::imdecode(raw_data, cv::IMREAD_UNCHANGED);
        cout << img_object << endl;
        return 1
    }
}
```

**Compiling with the following command:**
`sudo /home/xxx/emsdk/upstream/emscripten/em++ -Wall -std=c++11  ./test_wasm.cpp -lm -s WASM=1 -I/usr/local/include/opencv4 -L/home/kaushal/Documents/opencv/build_wasm2/lib  -llibopencv_core -llibopencv_calib3d  -llibopencv_imgproc -llibopencv_photo -llibopencv_flann -llibopencv_features2d -llibopencv_imgcodecs  -o test_wasm/test_wasm.html -s EXPORTED_FUNCTIONS='["_image_input"]' -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']"  -s DISABLE_EXCEPTION_CATCHING=2 -s USE_ZLIB=1 -s ALLOW_MEMORY_GROWTH=1`

Please help me I have spent many days to solve this problem.

**Comment by brion** [comment]
Your wrapper code looks ok to me, so this may be a problem with memory growth not updating the heap views correctly. It doesn't look like you're using pthreads so that ought to work though... To check, what emscripten version are you building with?

**Comment by chhaunkar96** [comment]
> Your wrapper code looks ok to me, so this may be a problem with memory growth not updating the heap views correctly. It doesn't look like you're using pthreads so that ought to work though... To check, what emscripten version are you building with?

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.3
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project cb47b8783017a76c5f2e4b974cfd6b22c9f1d5ff)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/kaushal/Documents/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

**Comment by chhaunkar96** [comment]
`Mat raw_data = cv::Mat(1, nSize, CV_8UC1, buffer);`

I'm getting 1-D array in `raw_data` but `imdecode` is not working with that array.

**Comment by brion** [comment]
Looks like you're going to have to instrument your code; add some debug `console.log()`s or step through in the debugger to make sure you know what's going on:
* is the input array of the expected length?
* does malloc return a valid pointer?
* does the creation of a new Uint8Array around the heap buffer throw an exception? If so, what exactly is the exception error message? Check that the size of Module.HEAPU8 is what you expected as well, and that all the data is in range.
* if anything looks out of whack, step through in the debugging to see what it looks like

**Comment by brion** [comment]
And of course:
* what's in the array? is it the expected data or something else?

**Comment by chhaunkar96** [comment]
[shared.zip](https://github.com/emscripten-core/emscripten/files/3957553/shared.zip)
I have attached what I'm getting in `raw_data`  variable. There are all things like array buffer, image and array length.

**Comment by brion** [comment]
Looks like it contains the JPEG file as expected yeah -- can you check also what the `dataOnHeap` array looks like? It should be the same length and contain the same data... if it does contain the expected data too but the Wasm code sees only zeroes, then I definitely suspect a problem with memory growth not updating the views. But if you're not using pthreads, the code _looks_ like it should work.

Is it possible to share the entire wasm & js/html output to test? It might take some fiddling around in the debugger to find what's going wrong. :)

**Comment by chhaunkar96** [comment]
[shared2.zip](https://github.com/emscripten-core/emscripten/files/3963940/shared2.zip)
Thank you @brion  for continuously supporting me.
I have attached everything related to this project.

**Comment by besttangent** [comment]
> [shared2.zip](https://github.com/emscripten-core/emscripten/files/3963940/shared2.zip)
> Thank you @brion for continuously support me.
> I have attached everything related to this project.

Hi, did you solve this problem? I faced the same problem now.

**Comment by chhaunkar96** [comment]
No. I didn't solve it.

**Comment by besttangent** [comment]
thanks for your reply.

在 2020年7月9日星期四，Kaushal chhaunkar <notifications@github.com> 写道：
