### ISSUE TITLE
Checking snprintf and vsnprintf failed

### ISSUE THREAD

**Issue by a-reisberg** [emscripten-core/emscripten#10016]
I'm trying to build texlive 2019 to emscripten following the script here https://github.com/latexjs/latexjs/blob/master/latexjs/Dockerfile, which seems to be a standard configure/make procedure.  However, configure fails (for the emscripten build) at the step "checking for snprintf and vsnprintf" which returns "no".

Being completely new to emscripten, I'm not sure which part of the log file is relevant. There are multiple log files and the whole thing is a couple of thousand lines. But I'm happy to provide more information!

Thanks!

**Comment by kripken** [comment]
Usually the last part of `config.log` is the relevant part, in most configure scripts. You should be able to find a program that it ran, and the output it got that it didn't expect, around there.

You can also read the configure script itself to see what it tried right after printing that "checking" message.

**Comment by a-reisberg** [comment]
Thanks! I finally figured it out. It seems like those errors are false negative. I commented those checks out and it works.
