### ISSUE TITLE
Passing a function pointer to JavaScript with a float argument breaks on fastcomp asm.js

### ISSUE THREAD

**Issue by xprogram** [emscripten-core/emscripten#10039]
Say we have `callback.c` like so:
```
#include <emscripten.h>
#include <stdio.h>

extern void testFloatCallback(void(*func)(float));

void callback(float a){
  printf("callback: %f\n", a);
}

int main(int argc, char** argv){
  testFloatCallback(&callback);
}
```
And `callback.js` defined as:
```
mergeInto(LibraryManager.library, {
  testFloatCallback__sig: 'vi',
  testFloatCallback: function(funcPtr){
    var callbackWrap = getFuncWrapper(funcPtr, 'vf');
    callbackWrap(5.6);
  }
});
```
Compiled like so:
```
emcc callback.c -s WASM=0 --js-library callback.js -o test.html
```
The following error message is printed to the console at runtime:
```
Assertion failed: bad function pointer type - no table for sig 'vf'
```
The error happens only on the fastcomp backend when targeting asm.js. Tested on latest emscripten (1.39.4), but might go further back than that. Chrome 79.0.3945.79 and Firefox 71.0 both display the error message.

Also, should I be using something other than `getFuncWrapper` if I wanted to pass an arbitrary C function pointer to JavaScript? It seems like an internal API. I couldn't find a proper solution in the docs though.

**Comment by juj** [comment]
Try `callback.js`:

```js
mergeInto(LibraryManager.library, {
  testFloatCallback: function(funcPtr){
  	{{{ makeDynCall('vf') }}}(funcPtr, 5.6);
  }
});
```

**Comment by xprogram** [comment]
Sadly, that doesn't work either. I get instead an error in the dev console:
```
Uncaught ReferenceError: dynCall_vf is not defined
    at _testFloatCallback (test.js:1813)
    at _main (test.js:2033)
    at asm._main (test.js:8460)
    at callMain (test.js:8715)
    at doRun (test.js:8774)
    at test.js:8785
```

**Comment by kripken** [comment]
Sounds like this works with upstream with `WASM=0`? Our development is focused on upstream now, is there a reason not to use that in this case?

**Comment by xprogram** [comment]
I guess not.. I was trying to make my code work with the fastcomp and upstream backends as much as possible, but seeing as how fastcomp is going to be deprecated I’ll focus my efforts on upstream only. Closing this now.
