### ISSUE TITLE
Emit asm2wasmImports only when needed?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#10034]
Currently each generated wasm program gets
```js
var asm2wasmImports = {
 "f64-rem": function(x, y) {
  return x % y;
 },
 "debugger": function() {debugger;}
};
 var info = {
  "env": asmLibraryArg,
  "wasi_snapshot_preview1": asmLibraryArg,
  "global": {
   "NaN": NaN,
   Infinity: Infinity
  },
  "global.Math": Math,
  "asm2wasm": asm2wasmImports
 };
```
It would make me really happy if `debugger` and `f64-rem` were emitted only when needed. Also, could they be emitted flat, i.e.
```js
 var info = {
  "env": asmLibraryArg,
  "wasi_snapshot_preview1": asmLibraryArg,
  "global": {
   "NaN": NaN,
   Infinity: Infinity
  },
  "global.Math": Math,
  "f64-rem": function(x, y) {
     return x % y;
  },
   "debugger": function() {debugger;}
 };
```
so that the whole `asm2wasmImports` object could vanish for smaller code size? (that is because it is very likely that optimized builds of real world applications never need to emit debugger, but do need to emit f64-rem?, so having to add a "asm2wasm" object for just "f64-rem" in it would be a bit silly)

**Comment by kripken** [comment]
I think this could be done - I'd recommend upgrading to upstream though :wink: as the code size wins there are even larger than stuff like this - but doing it might look like one of:

 * Move those two imports to `env`, so they aren't special any more. Maybe `asm2wasm$f64_rem` etc. At that point, I think metadce would just clear them out when they aren't needed, automatically. To avoid CI issues, an initial emscripten PR could provide those imports on both the old and new ways, then the binaryen change can land (which will not break CI thanks to the emscripten one), then an emscripten change can land that removes the old way.
 * Make asm2wasm emit some metadata, `usedF64Rem, usedDebugger`, and read that on the emscripten side. However we run asm2wasm late, so the JS is already emitted - we would need to post-process it to remove those things, which is kind of hackish (i.e., we can't use an ifdef in the JS compiler code for this, as it runs too early; so the first route seems better).

**Comment by juj** [comment]
> I'd recommend upgrading to upstream though

I think I checked this also against upstream before reporting, and upstream also has this? Or perhaps I mis-checked..

**Comment by kripken** [comment]
In upstream it wouldn't be used, as asm2wasm isn't run which is what creates those imports in the wasm. We also don't send it from JS. However, I see we are missing an ifdef on `var asm2wasmImports`, so that is created - it would be removed in -O2 and above automatically, but might be nice to ifdef it.

**Comment by juj** [comment]
Gotcha. Misinterpreted it to be also relevant to wasm backend since I saw it there in a quick test build. Posted a PR to gate it out there to not cause confusion.
