### ISSUE TITLE
"Looks like you are rendering without using requestAnimationFrame for the main loop"

### ISSUE THREAD

**Issue by cwoffenden** [emscripten-core/emscripten#10051]
Could we make the reporting of this optional, or at least not an error? I don't mind doing the PR.

https://github.com/emscripten-core/emscripten/blob/ff229dc6a296cea250308ae4f415592a365bf1bc/src/library_browser.js#L1258

My use case is: depending on the browser, when running using RAF the main loop doesn't get called _at all_ when the tab is in the background. For drawing this is preferable, but there are cases where we'd still like updates. Our workaround is on a visibility change switch from `EM_TIMING_RAF` to `EM_TIMING_SETTIMEOUT`, which will get called once per second. This works great, only the console gets the "Looks like you are rendering without using requestAnimationFrame for the main loop" on every switch.
```
static EM_BOOL visibilityChange(int, const EmscriptenVisibilityChangeEvent* e, void*) {
    if (e->hidden) {
        emscripten_set_main_loop_timing(EM_TIMING_SETTIMEOUT, 60);
    } else {
        emscripten_set_main_loop_timing(EM_TIMING_RAF,         1);
    }
    return EM_TRUE;
}
```
Wouldn't `warnOnce()` be enough, or at least only giving the error when `ASSERTIONS` are enabled?

**EDIT: the idea of hooking into the visibility event to toggle between RAF and timeout is flawed (see post further down).**

**Comment by sbc100** [comment]
That fact that you are not actually rendering, but this warning still occurs seems like the problem.  I wonder if we can fix the "you are rendering" detection to be more accurate.

**Comment by cwoffenden** [comment]
Adding a simple `!document.hidden` stops the error when not drawing, deferring until the document is shown again.

**Comment by juj** [comment]
Instead of continuously toggling the timing mode, how about

```c
double lastRenderTime = 0;

void renderFromBackground(void*) {
  if (emscripten_get_now() - lastRenderTime > 900) {
    render();
  }
}

void render() {
  lastRenderTime = emscripten_get_now();
}

int main() {
   emscripten_set_main_loop(render, 0, 0);
   emscripten_set_interval(renderFromBackground, 1000, 0);
}
```
That way there is no need for registering to a visibilitychange event callback, and the approach is "stateless", so there is no danger of the main loop timing mode getting out of date, or event callback handling falling through.

**Comment by cwoffenden** [comment]
That'll work around it for sure.

I still think the PR is worthwhile since it doesn't error unnecessarily, then will once the page is visible again.

**Comment by juj** [comment]
I think a better fix is to change the warning to be more precise about what it is warning against. Posted PR #10062 that does that.

**Comment by cwoffenden** [comment]
The idea that prompted the post, switching between RAF and timeout for the main loop, is flawed, since browsers that don't complete the RAF until the tab is foregrounded again won't ever switch to running with a timeout (e.g. Chrome). The proposal a few comments up, [running a watchdog timeout](#issuecomment-566232729), is a better solution.

That said, even if the use case is flawed I still think it worthwhile only running the test with `ASSERTIONS` and using `warnOnce()`. See #10090.
