### ISSUE TITLE
Fix predictable name mangling in wasm backend?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#10054]
In wasm backend, it looks like there is currently no predictable C name mangling in effect, but all function names are exported unmangled, and an arbitrary selection
```
def treat_as_user_function(name):
  library_functions_in_module = ('setTempRet0', 'getTempRet0', 'stackAlloc',
                                 'stackSave', 'stackRestore',
                                 'establishStackSpace', '__growWasmMemory',
                                 '__heap_base', '__data_end')
  if name.startswith('dynCall_'):
    return False
  if name in library_functions_in_module:
    return False
  return True
```
is being used to distinguish which functions should get a `x -> '_' + x` treatment.

Could this be fixed so that all symbols are exported already properly mangled (or not) in the Wasm module, like it used to be?

This is important because it enables using a linker option `-s DECLARE_ASM_MODULE_EXPORTS=0`, which replaces

```js
var _main,___errno_location,_fflush,stackSave,stackAlloc,stackRestore,__growWasmMemory;
WebAssembly.instantiate(Module['wasm'], imports).then(function(output) {
  var asm = output.instance.exports;
  ___wasm_call_ctors = asm["__wasm_call_ctors"];
  _main = asm["main"];
  ___errno_location = asm["__errno_location"];
  _fflush = asm["fflush"];
  stackSave = asm["stackSave"];
  stackAlloc = asm["stackAlloc"];
  stackRestore = asm["stackRestore"];
  __growWasmMemory = asm["__growWasmMemory"];
  initRuntime(asm);
  ready();
})
```
with
```js
WebAssembly.instantiate(Module['wasm'], imports).then(function(output) {
  var asm = output.instance.exports;
  for(var i in asm) this[i] = Module[i] = asm[i];
  initRuntime(asm);
  ready();
 }
```
which saves a lot of space in builds when each exported symbol does not need to be copied to the global scope one by one.

Now I end up writing the following runtime framework:

```js
#if WASM_BACKEND
  // Keep in sync with emscripten.py function treat_as_user_function(name).
  function asmjs_mangle(x) {
    var unmangledSymbols = ['setTempRet0', 'getTempRet0', 'stackAlloc', 'stackSave', 'stackRestore', 'establishStackSpace', '__growWasmMemory', '__heap_base', '__data_end'];
    return x.indexOf('dynCall_') == 0 || unmangledSymbols.indexOf(x) != -1 ? x : '_' + x;
  }
  for(var i in asm) this[asmjs_mangle(i)] = asm[i];
#else
  for(var i in asm) this[i] = asm[i];
#endif
```
which is quite clunky, and adds an extra point of maintenance.

**Comment by sbc100** [comment]
I think the original plan was to remove all the underscore prefixing stuff once fastcomp goes away.

However I'm open to other options.  One option is that we go the other direction and simply add underscores to all symbols in binaryen.   

I wasn't aware of the specific issue with DECLARE_ASM_MODULE_EXPORTS but I do agree this is a pain for many reasons.
