### ISSUE TITLE
Docs missing for coercing "val" to c++ values like a "int" or "double"

### ISSUE THREAD

**Issue by For-thewin** [emscripten-core/emscripten#10050]
Using val, i can get the number from JS code. For example:
     
//c++ code
     #include <emscripten/val.h>
     using namespace emscripten;
     int main()
     {
             val testNumber= val::global("testNumber");
     }
    // testNumer is a Number type in JS and its value is 1.0;
     
Now i want to get the value "1.0" and use it in c++. I have tried some methods like :
parseFloat(testNumber)  or double(testNumber). They don't work; 

So how can i convet the val to double/int?

**Comment by cwoffenden** [comment]
You can do: `testNumber.as<double>()` or `testNumber.as<int>()`. It's missing from the docs but it works just fine.

**Comment by For-thewin** [comment]
OK, That works. Thank you very much.

**Comment by kripken** [comment]
Perhaps we should reopen this for the docs issue mentioned here? Sounds serious that we're missing docs on this.

**Comment by sbc100** [comment]
Given that this is an embind issue, and embind is basically maintained it seems like the least of its worries.    But of course patches welcome.    Feel free to re-open as a "please add docs" issue.

**Comment by kripken** [comment]
Reopening for docs.

**Comment by cwoffenden** [comment]
I added some bare minimum docs for this.

**Comment by kripken** [comment]
Great, thanks for the reminder @cwoffenden !
