### ISSUE TITLE
Switch main branch from "incoming" to "master"

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10067]
We used to have a purpose for the distinction but we have not used it a very long time and `master` is essentially unused today with everyone working directly on `incoming`.

I propose the following phases for the transition:

1.  [x] Announce the plan on the mailing list
2.  [x] Begin keeping `master` in sync with `incoming`.  This will allow non-committer and things like builders to start using `master`.
3.  [x] Convert emscripten-releases and other builders to point to `master`.
4.  [x] Verify that github CI works on master (without actually committing there).
5.  [x] Block commits for `incoming` and open `master` for commits.
6.  [x] Docs on the website and likely the readmes of the emscripten and emsdk repos.
7.  [x] emsdk has support for building incoming-64bit etc., that should be switched to master.
8.  [x] Keep incoming in sync with master for certain period (the inverse of 2)
9.  [x] Delete (or at least rename) the `incoming` branch

**Comment by kripken** [comment]
This will be great!

More things that need to be done:

 * Docs on the website and likely the readmes of the emscripten and emsdk repos.
 * emsdk has support for building `incoming-64bit` etc., that should be switched to master.

**Comment by sbc100** [comment]
emscripten-release change: https://skia-review.googlesource.com/c/buildbot/+/263526

**Comment by sbc100** [comment]
incoming is now renamed to `old_incoming`
