### ISSUE TITLE
ERRNO_CODES not available when using emcc -O1, -O2, or -O3

### ISSUE THREAD

**Issue by a-reisberg** [emscripten-core/emscripten#10061]
I have a simple C program, which opens a file and and writes some text into it.  In my `pre.js`, I initialize the file system using `BrowserFS`. The relevant line is
```
var BFS = new BrowserFS.EmscriptenFS(FS, PATH, ERRNO_CODES);
```
which depends on `FS`, `PATH`, and `ERRNO_CODES` to be available at runtime.

Everything works when I compile with
```
emcc -s INVOKE_RUN=0 -s MODULARIZE=1 -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["FS"]' --pre-js pre.js hello.c -o hello.js
```
However, when I use `-Ox` when `x` is 1, 2, or 3, I get the following error
```
ERRNO_CODES is not defined
```

Is there anyway to make sure that `ERRNO_CODES` doesn't get optimized away?

Thanks!

**Comment by kripken** [comment]
I think you can add `$ERRNO_CODES` to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`, to force it to be included. Otherwise, it isn't included automatically (it may have been in the past, as more things depended on it - we removed some of those for code size reasons).

**Comment by a-reisberg** [comment]
That works!  Great, thanks!
