### ISSUE TITLE
Can't link -fno-exception compiled files with -fexception compiled .lib

### ISSUE THREAD

**Issue by gabrielcuvillier** [emscripten-core/emscripten#10060]
Following the discussion on #9947, here is how to reproduce the problem on a very simple testcase, yet with a subtle step in the way things are compiled:

// main.cpp
```
// Very basic: we just call an externally defined function
#include <iostream>
size_t function_with_stl();
int main() {
    std::cout << function_with_stl() << std::endl;
}
```

// stl.cpp
```
#include <vector>

// Actual implementation of the called function
size_t function_with_stl() {
    std::vector<int> dummy_vector;
    dummy_vector.push_back(1);
    return dummy_vector.size();
}
```

Now, first compile stl.cpp normally (with implicit -fexceptions), **and create a .lib** out of it (this is the subtility that triggers the issue later on)
```
emcc -c stl.cpp -o stl.o
emar ru stl.lib stl.o
```

And then compile main.cpp **without exceptions**, while linking to the previous exception enabled library:
```
emcc -fno-exceptions main.cpp -o main.html stl.lib
```

The following linker errors appears:

> error: DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), which means no C++ exception throwing support code is linked in, but such support is required by symbol __cxa_a
> llocate_exception. Either do not set DISABLE_EXCEPTION_THROWING (if you do want exception throwing) or compile all source files with -fno-except (so that no exceptions support code is re
> quired); also make sure DISABLE_EXCEPTION_CATCHING is set to the right value - if you want exceptions, it should be off, and vice versa.

The issue is that the .lib defines __cxa_ symbols as it uses STL containers and have been compiled with exception support. This is exactly what happens in #9947, and to me, this is probably normal behavior (but hard to understand first).

Note that everything would work if you either:
- add -fno-exceptions to the compilation of stl.cpp   (solution for the Regal port, explaining the two different variants)
- remove -fno-exceptions to the compilation of main.cpp   (... might be not suitable for some projects)
- don't use a .lib at all, and compile everything together   (can't use this for a port)

**Comment by juj** [comment]
> Can't link -fno-exception compiled files with -fexception compiled .lib

Does that work on any native compiler? If a code file has been compiled with `-fexception`, then it already has try-catch-throw opcodes in it + dependencies to C++ exception runtime. Stripping those out at a later stage may not be possible, I wonder if any compiler tries to do that..

**Comment by gabrielcuvillier** [comment]
@juj 
For some reason, it works with both gcc and clang !
Just replace emcc by gcc or clang in the above example

Not that to link, -lstdc++ need to be added to the command line. Maybe that's the trick (?)
But I think it is more that the -fno-exceptions flag is simply ignored for the purpose of the standard library: in all cases, there is some _cxa symbols in the various .o/.lib/elf binaries... !

**Comment by gabrielcuvillier** [comment]
According to https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_exceptions.html
it looks like all/most exceptions-related symbols are defined even with -fno-exceptions, but they simply have some dummy implementation (abort)

**Comment by sbc100** [comment]
I'm curious, if you compile you main.cpp wih `-fno-exceptions` but use -c produce an object file, then you like them together with without `-fno-exceptions` it should work.

i.e. The problem doesn't relate the flags used to compile `main.cpp` at all, but just to the flag used to link the final program, right?

**Comment by sbc100** [comment]
I suppose we could look at reducing that error to warning perhaps?  The document you link to also says: `If you might have some code that throws, you shouldn't use -fno-exceptions. If you have some code that uses try or catch, you shouldn't use -fno-exceptions.`

**Comment by gabrielcuvillier** [comment]
or maybe leave this as an error (because I think it is a normal behavior), but add a "check if some code using the standard C++ libraries (vector, string) have been eventually compiled with -fexceptions"
