### ISSUE TITLE
malloc results are not aligned to alignof(max_align_t)

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#10072]
It looks like `malloc`ed pointers are aligned to 8 bytes, but `alignof(max_align_t)` returns 16. This is a violation of the C standard; [`max_align_t` is supposed to reflect the minimum malloc alignment.](https://en.cppreference.com/w/c/types/max_align_t)

This has caused me a great deal of debugging confusion today...

**Comment by sbc100** [comment]
Yes, this is due to dlmalloc:
https://github.com/emscripten-core/emscripten/blob/incoming/system/lib/dlmalloc.c#L79
https://github.com/emscripten-core/emscripten/blob/748c80ca18219bdbf3baa9bfde4010e324d43b52/system/lib/dlmalloc.c#L284

I default to 2 * sizeof(ptr) here:
https://github.com/emscripten-core/emscripten/blob/748c80ca18219bdbf3baa9bfde4010e324d43b52/system/lib/dlmalloc.c#L661

We should probably update it to use max_align_t.  To be fair when dlmalloc was written that type did not exist :).   There will be some cost in memory usage / fragmentation, but perhaps its worth it?

Out of interest what how was this issue manifesting?  Are you using v128 types?

**Comment by Akaricchi** [comment]
The case is not very interesting and it's kind of stupid really. In short, my code can actually work with 8-byte alignment just fine. It just has lots of pointer casts, compiles with `-Wcast-align`, and contains paranoid amounts of `__builtin_assume_aligned` and alignment assertions (abstracted away with macros). Lots of pointers are cast between a "base" struct and derived types (this is C, not C++), and for simplicity the base struct has a forced alignment requirement of `max_align_t`. Everything just happens to work fine with `NDEBUG`, but otherwise the assertions are failing.

> Are you using v128 types?

`max_align_t` actually only needs to be just strict enough for the primitive types. It's expected and fine that SIMD stuff typically needs to be over-aligned. The only primitive type that's actually 16-byte aligned right now is `long double`, which does not exist in wasm natively. I'm not sure about this, but I suspect that it doesn't actually *need* that 16-byte alignment. So fixing that and lowering `max_align_t` to 8 may be a better option.

**Comment by sbc100** [comment]
The fact that `long double` is 16 bytes in webassembly is a very long running source of contention.  This is just one of the many annoying side effect of that choice.  Unfortunately I think that ship has sailed.

**Comment by Akaricchi** [comment]
Interesting. What was the reasoning behind that choice, and what's the main difficulty with reverting it? Maybe there's some previous discussion of this that I can read up on?

**Comment by Akaricchi** [comment]
To be clear, my point is that `long double` could still be 16 bytes in size, but 8-byte aligned, unless I'm missing something here.

**Comment by sbc100** [comment]
I didn't know that, are there existing types in llvm where _Alignof(x) < sizeof(x)? 

Regarding the old debate about `sizeof(long double)` I don't have links to discussions to hand but I doubt this issue will be significant enough to warrant change the ABI.  I think we can just change dlmalloc without incurring too much cost (am I wrong?)

**Comment by Akaricchi** [comment]
> I didn't know that, are there existing types in llvm where _Alignof(x) < sizeof(x)?

All the `_Complex` types, though I'm not sure how exactly llvm handles these. They are defined to be value pairs by the C standard (i.e. layout of `_Complex double` is equivalent to `double[2]`, where the real part comes first). So they typically have the same alignment as the base type, but double the size.

On x86_64 with `-malign-double`, clang makes `long double` 8-byte aligned but still 16 bytes in size: https://godbolt.org/z/m66mUR
Interestingly, the behavior of that switch seems to contradict the GCC description of it.

On x86_32, 4 is the natural alignment of both `double` and `long double`, and `sizeof(long double)` is 12: https://godbolt.org/z/xFhDyW

**Comment by sbc100** [comment]
Well, how about we fix dlmalloc to honor `max_align_t` in emscripten then we will continue to do the right thing whichever way that discussion might go?  There is no reason this issue needs to blocked on changinng wasms ABI.

**Comment by Akaricchi** [comment]
Oh sure, I wasn't implying it should be blocked. Fixing dlmalloc is fine and I don't think it'll cost too much.

Though I do hope for a future ABI change. `long double` is not used very often, and an alignment requirement relaxation doesn't seem too invasive to me.

**Comment by juj** [comment]
> Oh sure, I wasn't implying it should be blocked. Fixing dlmalloc is fine and I don't think it'll cost too much.
> 
> Though I do hope for a future ABI change. `long double` is not used very often, and an alignment requirement relaxation doesn't seem too invasive to me.

This is an odd reasoning. Switching dlmalloc alignment from 8 to 16 bytes is fine and does not cost too much, but `long double` being 16 byte aligned is too invasive and would like to be 8 bytes instead?

Way way more applications use dlmalloc compared to `long double`s, so not quite sure how/why worsening dlmalloc alignment is then perceived ok, but that same alignment on `long double` is invasive?

**Comment by Akaricchi** [comment]
> Switching dlmalloc alignment from 8 to 16 bytes is fine and does not cost too much, but long double being 16 byte aligned is too invasive and would like to be 8 bytes instead?

That is not what I said. I did not say that "long double being 16 byte aligned is too invasive", I said that changing the alignment of `long double` would probably not be too invasive of a change...

> so not quite sure how/why worsening dlmalloc alignment is then perceived ok

What do you mean by "worsening" the alignment? Is 16-byte alignment "worse" because it increases memory usage/fragmentation, or is it "better" because it actually satisfies the alignment requirements of every primitive type, as it's supposed to?

To be clear: I think *ideally*, `long double` and `max_align_t` should have been 8-byte aligned, and in that case, there would be no problem with a 8-byte aligned `malloc`. But as long as `long double` (and therefore `max_align_t`) remains 16-byte aligned, `malloc` must be as well.

**Comment by sbc100** [comment]
@juj what is your feeling about increasing malloc alignment to 16 (max_align_t)?  Do you think it will have noticeable effects on real world code?   Would you be ok with that change?

**Comment by sbc100** [comment]
Oh crap has it been a whole year.   We really should fix this.

**Comment by kripken** [comment]
This has been fixed by LLVM lowering the alignment of long double to 8, and now we also have assertions that verify `max_align_t` has the proper alignment etc.

**Comment by yu-re-ka** [comment]
Someone in https://github.com/NixOS/nixpkgs/pull/133217 reported this being triggered when building on x86_64-darwin with emscripten 2.0.26 and LLVM 12.x. So what can we do about it when this assertion triggers?

```
error: static_assert failed due to requirement '(__alignof(max_align_t)) == 8' "max_align_t must be 8"
_Static_assert(MALLOC_ALIGNMENT == 8, "max_align_t must be 8");
^              ~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by sbc100** [comment]
emscripten depends on tip-of-tree llvm.  It is not generally compatible with any old/stable releases of llvm.

There is some discussion of trying to support stable releases of llvm here: https://github.com/emscripten-core/emscripten/issues/11362, but not progress has been made so far.

**Comment by kripken** [comment]
The packaging docs may be helpful here:

https://github.com/emscripten-core/emscripten/blob/main/docs/packaging.md

**Comment by matthewp** [comment]
I've started getting this error when using the Homebrew version of emcc (latest). Is this expected?

**Comment by matthewp** [comment]
My issue turned out to be an old `~/.emscripten` that I didn't realize I had. Removing that caused it to create a new one in `/usr/local/Cellar/...`. I did have to set `LLVM_ROOT` and `BINARYEN_ROOT` manually, but after that it worked.
