### ISSUE TITLE
 LinkError: WebAssembly Instantiation: Import #0 module="env" function="sbrk" error: function import requires a callable

### ISSUE THREAD

**Issue by skandonkumar** [emscripten-core/emscripten#10074]
An outline of what I'm trying to do -
Converted a C library to WASM using EMScripten and wrote wrapper code to develop SDK. Used WebPack to bundle the whole thing by using "wasm-loader" which converts the WASM file into 8 bit integer array. The output is a single JS file but when we try to make API calls through this JS to the C library, I get the above mentioned error. 
Am I supposed to add the function "sbrk" in the env in the Emscripten generated JS file before using WebPack?
Any help would be greatly appreciated :)

The emscripten command I use is 
`emcc -s "EXTRA_EXPORTED_RUNTIME_METHODS=['cwrap', 'ccall', 'getValue', 'setValue', 'addFunction', 'removeFunction']" -s  EXPORTED_FUNCTIONS='[/*exported functions*/]' -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE=1`

**Comment by sbc100** [comment]
Which version of emscripten / emsdk are you using?  Specifically do yo know if you are using the llvm backend?

`sbrk` it self is defined in `libdlmalloc.a` (or what even version of malloc you are using).  You should see this included in the linker command line if you run the above command with either `-v` (for minimal verbosity) or EMCC_DEBUG=1 for full verbosity.

**Comment by skandonkumar** [comment]
@sbc100 , I am currently using emcc version 1.38.42. And I didn't realize that I had to use LLVM. I was just using the basic EMScripten JavaScript Compiler using the command I mentioned above. I was able to make the API calls to the WASM file with the help of EMScripten generated JS wrapper. I encountered this error while trying to bundle the whole project with WebPack. Do you suggest me to use LLVM upstream backend instead of emsdk for my application? Thanks again for your guidance.

**Comment by sbc100** [comment]
It sounds like your problem is with WebPack then.   if you binary needs sbrk and the emscripten js can load it.. but then WebPack can't then there is some issue with what WebPack is doing.  

This sounds unrelated to whether you use the llvm backenv, but yes you should use the llvm backend.  To use the llvm backend simply install with `./emsdk install latest` as opposed to the `./emsdk latest-fastcomp` (which is the old backend).

**Comment by skandonkumar** [comment]
Thanks @sbc100 . I will try EMScripten LLVM upstream backend to convert my C library and try WebPack to see if it still gives the error. If the error persists, I will try Rollup instead of WebPack. Thanks for the guidance.
