### ISSUE TITLE
python pointer cast errors.

### ISSUE THREAD

**Issue by tecan** [emscripten-core/emscripten#10073]
i got the EmCPython compile working but when i add
-s EMULATE_FUNCTION_POINTER_CASTS=1 to irrlicht compile it says

FuncCastEmulation::NUM_PARAMS needs to be at least FuncCastEmulation::NUM_PARAMS needs to be at least 1717

https://github.com/tecan/emscripten-projects  also for those interested

**Comment by sbc100** [comment]
1717 parameters!  really?  There is function pointer with 1717 arguments!

**Comment by tecan** [comment]
after looking again, the latest irrlicht compiles nice with it. no more issues.
