### ISSUE TITLE
EXPORT_NAME does not affect generated html

### ISSUE THREAD

**Issue by cwmos** [emscripten-core/emscripten#10086]
If you specify an EXPORT_NAME when you compile, the generated html creates a variable named "Module" rather than a variable with the name specified in EXPORT_NAME. This means that the generated js file will use an empty module rather than the one in the generated html file.

This confused me a lot.

A warning at compile time would be almost as useful to me as a fix.

**Comment by kripken** [comment]
Thanks @cwmos !

Good question. I opened #10105 to error on this for now, but I'm not sure if we should do anything else. On the one hand, emitting html means we control the entire page, so this isn't a case where modular output is the focus. On the other, it may be nice to let people customize it even then, if they load other things.

Might be worth experimenting to see how easy it is to change that. I suspect it's just editing `src/shell*.html` to replace `Module` with `{{{ EXPORT_NAME }}}`, as I think we already preprocess those files.

**Comment by embeddedt** [comment]
>  I think we already preprocess those files.

That seems to be case, as there is a [`{{{ SCRIPT }}}`](https://github.com/emscripten-core/emscripten/blob/8d692d5f9609e360d2ac9241dfcdef89a6d3cbc5/src/shell.html#L1296) directive at the bottom of the file.

**Comment by EPNW** [comment]
Is there a option to simply ignore this error?
I need to use the modular approach:
>On the other, it may be nice to let people customize it even then, if they load other things.

Editing the html afterwards seems easy enough, so a warning instead of a error would be sufficient...

**Comment by pshdevio** [comment]
> Is there a option to simply ignore this error? I need to use the modular approach:
> 
> > On the other, it may be nice to let people customize it even then, if they load other things.
> 
> Editing the html afterwards seems easy enough, so a warning instead of a error would be sufficient...

But when I run e.g. `emcc calculate_primes.cpp -O1 -std=c++14 -pthread -s MODULARIZE=1 -s EXPORT_NAME=XModule -s PTHREAD_POOL_SIZE=4 -o pthreads.html` all files EXCEPT the html file are generated. How can I get it to generate the html file too, so I can edit it ? I tried looking at one of the original .html files outputted when I don't use MODULARIZE and EXPORT_NAME, but nothing I try seems to work.

**Comment by birkskyum** [comment]
I hit this error:

```sh
em++: error: Customizing EXPORT_NAME requires that the HTML be customized to use that name (see https://github.com/emscripten-core/emscripten/issues/10086)
```

How can `the HTML be customized` in order to resolve this?

**Comment by sbc100** [comment]
> I hit this error:
> 
> ```shell
> em++: error: Customizing EXPORT_NAME requires that the HTML be customized to use that name (see https://github.com/emscripten-core/emscripten/issues/10086)
> ```
> 
> How can `the HTML be customized` in order to resolve this? As far as I'm aware, I don't even set the EXPORT_NAME explicitly - can I unset it somehow?

Can you see your full link command you are using?  I think that error can only show up if `-sEXPORT_NAME` is on the command line somewhere.

**Comment by pchilds** [comment]
Please reopen.
This is clearly a bug that has not been fixed nor workarounds documented.
`emcc ... -s MODULARIZE=1 -s EXPORT_NAME="mymodule" ... -o output.html ... `
Errors out before generating the html that needs to be customised in order for it not to error out.
The documentation for the error points to this webpage in which no solution is offered

**Comment by sbc100** [comment]
In order to customize the html output you use `--shell-file=myshell.html`.. or just output a `.js` file and write your own custom html to load it.  I will update the error message.

**Comment by pchilds** [comment]
--shell-file requires it to exist before hand.
Why not just add in a sed command? Mind you having a default of Module is just asking for trouble with collisions

**Comment by sbc100** [comment]
Currently we don't support custom `EXPORT_NAME` with the default shell so you need to create your own shell html file for this case.

**Comment by sbc100** [comment]
If you would like add support for `EXPORT_NAME` to the existing `index.html` we can re-open this a feature request.

Generarlly the html output of emscripten is really only designed as a starting point to get new users going.  Once you get going with emscripten that idea is that you would embed the generated JS in your own html framework and would not be asking emscripten to generate the html.

**Comment by pchilds** [comment]
Ok. Thanks for the clarification.

**Comment by CaglaNurYuva** [comment]
Is there any progress related to this issue? I am also stuck in the same problem. 

When I use -s MODULARIZE=1 -s EXPORT_NAME=createModule  --pre-js ${CMAKE_SOURCE_DIR}/main.js  flags, I get the error given below:

`em++: error: customizing EXPORT_NAME requires that the HTML be customized to use that name`

How should I modify shell.html file such that it is capable of working according to given EXPORT_NAME ?

**Comment by orange4glace** [comment]
It makes me so confused. Why is the build args is so complex?
