### ISSUE TITLE
need api to operate on websocket frame [feature request]

### ISSUE THREAD

**Issue by linuxaged** [emscripten-core/emscripten#10106]
there's no api in [websocket.h](https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/websocket.h) can be used to deal with websocket frame currently. We need something like [binaryFrameReceived](https://doc.qt.io/qt-5/qwebsocket.html#binaryFrameReceived), [textFrameReceived](https://doc.qt.io/qt-5/qwebsocket.html#textFrameReceived)

**Comment by juj** [comment]
When a WebSocket message is received, the [onmessage callback](https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/websocket.h#L46) is fired, which carries a [EmscriptenWebSocketMessageEvent](https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/websocket.h#L38) structure, that has the data, and a boolean that tells if the data is binary or text.

I wonder if you missed this, or are you looking for something different?

**Comment by linuxaged** [comment]
> I wonder if you missed this, or are you looking for something different?
websocket(TCP) will seperate big package into small frames, `onMessage` only triggered when all frames are received i think. Can i get the receiving progress with `onMessage`?

**Comment by juj** [comment]
Unless I am mistaken, it is not possible to get partial message fragments from a WebSocket message. https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onmessage will always receive the whole assembled message.
