### ISSUE TITLE
Unable to set the position of mouse in Emscripten with SDL/JS APIs

### ISSUE THREAD

**Issue by AbdelmalekIhdene** [emscripten-core/emscripten#10109]
Hey,
I am currently trying to set up a lock of the mouse position with SDL. I have tried many things, including `SDL_SetRelativeMouseMode` that gives me an exception and `SDL_WarpMouse*` which simply doesn't work. With that in mind, I was wondering. Is there a way to set the position of the mouse directly with emscripten?

Thank you for reading!

**Comment by kripken** [comment]
I believe Web APIs don't let you move the mouse around normally, but in [mouse capture mode](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) that might be possible. The user needs to click and allow the mouse to be captured first, though.

I'm not sure how well the SDL APIs integrate with that, though - it's possible they require more than even the capture APIs allow.
