### ISSUE TITLE
Why thread_local doesn't work under fastcomp backend?

### ISSUE THREAD

**Issue by jianliang79** [emscripten-core/emscripten#10134]
I have a simple program:
    
```
static thread_local int g_num = -1;

static void * thread(void *data)
{
    printf("thread begin to run!\n");
    g_num = 250;
    return 0;
}

int main()
{
    g_num = 100;

    printf("Starting thread.\n");
    pthread_attr_t attr;
    pthread_attr_init(&attr);

    pthread_t handle;
    pthread_create(&handle, &attr, thread, 0);
    void *ret = 0;
    pthread_join(handle, &ret);
    printf("thread exited.\n");

    printf("num is %d\n", g_num);
    return 0;
}
```
    I build this program with the following command:

> em++ -s WASM=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -std=gnu++11 thread.cpp -o  thread.html

    If I build this program with 1.38.45 or 1.39.x-fastcomp, When I run this program the console will show the following message:

> num is 250

    If I build this program with 1.39.x-upstream, the console will show:

> num is 100
    
    If seems that when I build this program with fastcomp backend, thread_local keywork will not take effect. How can I fix this?

**Comment by tlively** [comment]
Fastcomp simply did not support thread-local variables. Fastcomp only ever supported MVP WebAssembly features, but thread-local variables require the `bulk-memory` feature, so they are only supported with the upstream backend.

**Comment by jianliang79** [comment]
Thank you.
