### ISSUE TITLE
EVAL_CTORS seems to be enabled automatically on 'Oz' builds => bigger binaries ?

### ISSUE THREAD

**Issue by gabrielcuvillier** [emscripten-core/emscripten#10130]
According to this code in 'shared.py'
```
    def apply_opt_level(cls, opt_level, shrink_level=0, noisy=False):
      if opt_level >= 1:
        cls.attrs['ASM_JS'] = 1
        cls.attrs['ASSERTIONS'] = 0
        cls.attrs['ALIASING_FUNCTION_POINTERS'] = 1
      if shrink_level >= 2:
        cls.attrs['EVAL_CTORS'] = 1
```
It looks like EVAL_CTORS is enabled on Oz builds (because shrink_level == 2 in that case). 

Don't EVAL_CTORS would increase the final size of the binary (which is not the purpose of 'Oz') ? Just curious, I might be wrong. 

But this could explain a very weird case I have where using 'Oz' gives me with a significant bigger binary size than with an 'O3' build, something like +30% (is this even possible ?)

**Comment by tlively** [comment]
I think the idea of evaluating constructors during build time is that it will often save space by removing the constructor code. However, if a constructor uses just a small amount of code to generate a lot of new data, the size of the new data could easily surpass the code size savings. I suppose a good fix would be to change the constructor evaluator so that it only changes the binary if evaluating the constructors is beneficial for code size.

**Comment by gabrielcuvillier** [comment]
Ah, ok. I see the point. 

In my case, after further investigations, the "bigger binary size in Oz" issue does not seem to come from EVAL_CTOR, as building with -Os instead of -Oz (so w/out EVAL_CTOR) still creates a bigger binary than with -O2/3.

That's a really strange thing, as I don't have the same behavior when doing a native build (using Clang) => Os is smaller than O2/3 in that case

**Comment by gabrielcuvillier** [comment]
After comparing the binaries with 

> wasm-objdump -h

Oz
```
Type start=0x0000000b end=0x0000105b (size=0x00001050) count: 366
Import start=0x0000105e end=0x00001e69 (size=0x00000e0b) count: 397
Function start=0x00001e6c end=0x00004733 (size=0x000028c7) count: 9978
Global start=0x00004735 end=0x0000473e (size=0x00000009) count: 1
Export start=0x00004741 end=0x00004838 (size=0x000000f7) count: 41
Start start=0x0000483a end=0x0000483c (size=0x00000002) start: 10371
Elem start=0x0000483f end=0x00006d41 (size=0x00002502) count: 1
DataCount start=0x00006d43 end=0x00006d44 (size=0x00000001) count: 3
Code start=0x00006d49 end=0x003f0f7b (size=0x003ea232) count: 9978
Data start=0x003f0f7f end=0x0041e900 (size=0x0002d981) count: 3
```

O3:
```
Type start=0x0000000b end=0x00000be1 (size=0x00000bd6) count: 278
Import start=0x00000be4 end=0x00001a28 (size=0x00000e44) count: 397
Function start=0x00001a2b end=0x0000347f (size=0x00001a54) count: 6577
Global start=0x00003481 end=0x0000348a (size=0x00000009) count: 1
Export start=0x0000348d end=0x00003584 (size=0x000000f7) count: 41
Start start=0x00003586 end=0x00003588 (size=0x00000002) start: 6970
Elem start=0x0000358b end=0x000058ba (size=0x0000232f) count: 1
DataCount start=0x000058bc end=0x000058bd (size=0x00000001) count: 3
Code start=0x000058c2 end=0x0032cf7c (size=0x003276ba) count: 6577
Data start=0x0032cf80 end=0x0035bac9 (size=0x0002eb49) count: 3
```

So I notice some sections are bigger in Oz than with O3 (either in terms of "size" or "count"). Could it be a hint that the dead code elimination pass might not work as expected ??

**Comment by kripken** [comment]
Is that on fastcomp? On upstream I think eval-ctors is disabled (it needs some work to handle malloc properly there).

I agree we should probably not apply the transform if code size increases and we are optimizing for size. We can either open a new issue for that, or repurpose this one if there's nothing else actionable?

**Comment by gabrielcuvillier** [comment]
No, this is on upstream. So that's definitively Eval-ctors that is the issue there. I'll open another issue for the problem of Oz/s being bigger than O3/2.
I just need to isolate the case, as the project is quite big
