### ISSUE TITLE
upstream backend and pthread break old chrome browser

### ISSUE THREAD

**Issue by jianliang79** [emscripten-core/emscripten#10131]
I have an extremely simple sample program which is to test pthread of wasm, I build the program with the following command:
    emcc -s WASM=1 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -s thread.c -o thread.html
    If I build the program with 1.39.5(upstream backend) and run it in chrome 70, it will fail to compile the wasm module with the following message:
    CompileError: AsyncCompile: Wasm decoding failed: unexpected section: Code @+2522
    If I run the program with chrome 79 it works well and if build the program without pthread all chrome run the program well.
    If I build this program with 1.39.5-fastcomp, it works well even in chrome 70.
    It looks like upstream backend with pthread break compilation of the wasm module in old chrome browser. So what is wrong with my build instructions? How can I use upstream backend if I also want to support chrome 70? Thanks.

**Comment by tlively** [comment]
Chrome 70 only supported threads in an origin trial, and threads were turned on by default in Chrome 74 for desktop. If you want to support older versions of Chrome, you should not use threads.

**Comment by jianliang79** [comment]
Thank you for the reply.
    As a workaround, if I enable #enable-webassembly-threads explicitly in chrome 70-73, threaded webassembly app built with fastcomp work well.
