### ISSUE TITLE
Latest emsdk emcc -c not generate LLVM IR bitcode

### ISSUE THREAD

**Issue by jishuo1213** [emscripten-core/emscripten#10142]
I update my emsdk from version 1.38.41 to 1.39.5, I found that the new version emsdk can not build source code to LLVM IR bitcode.
I use emsdk to build openssl,because my emsdk version is update,I need rebuild openssl, I found that the new version emcc not generate LLVM IR bitcode but WebAssembly (wasm) binary module
file,the following two picture shows what happend.

emcc-1.39.5:
`emcc  -I. -Icrypto/include -Iinclude -fPIC -mx32 -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/home/fan/Tools/TASSL-1.1.1b/emcc-build-v4/ssl\"" -DENGINESDIR="\"/home/fan//Tools/TASSL-1.1.1b/emcc-build-v4/lib/engines-1.1\"" -DNDEBUG   -c -o crypto/aes/aes_cfb.o crypto/aes/aes_cfb.c`
![emcc-1 39 5](https://user-images.githubusercontent.com/9456146/71732719-f0468100-2e82-11ea-9fbb-4d8a8ca46d70.png)

emcc-1.38.41:
`emcc  -I. -Icrypto/include -Iinclude -fPIC -mx32 -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/home/fan/Tools/TASSL-1.1.1b/emcc-build-v3/ssl\"" -DENGINESDIR="\"/home/fan//Tools/TASSL-1.1.1b/emcc-build-v3/lib/engines-1.1\"" -DNDEBUG   -c -o crypto/aes/aes_ecb.o crypto/aes/aes_ecb.c`
![emcc-1 38 41](https://user-images.githubusercontent.com/9456146/71732720-f0df1780-2e82-11ea-9e5c-4d2e41e1132f.png)
The finally .so file is also not LLVM IR bitcode,I can not use the library.

**Comment by tlively** [comment]
This is an expected change because the default backend changed from
Fastcomp to upstream LLVM and we now produce proper WebAssembly object
files. It sounds like your build is breaking because some libraries are
built with the old backend and some are built with the new backend.
Clearing your build system's cache and rebuilding your dependencies should
fix that.

**Comment by sbc100** [comment]
The default is now to generate object files.   If you want to generate LLVM IR object files you can build with `-flto` or `-s WASM_OBJECT_FILES=0`.

Can I ask why you can't use the resulting library?   wasm object files should work fine.

BTW, the recommend way to build a library is to use the `.a` format.  Emscripten doesn't support `.so` files in the way one would expect.

**Comment by jishuo1213** [comment]
@sbc100 
Thank you for replay.
When i use fastcomp,i use the result `.so` (LLVM IR bitcode format) library in my project.With cmake link the .so library,and use cmake `SET(CMAKE_EXECUTABLE_SUFFIX ".html")` finally I got a wasm file about 600KB+ , a js file and a test html file.I can test my code use `emrun`,my main function will run.the js file and wasm file can use in the production environment.

When i use upstream,when i build my library without `-s WASM_OBJECT_FILES=0`,i use the result `.so` file(wasm binary module about 2.5M) in my project like fastcomp,the `CMakeLists.txt` file is same as before,finally I got only one .html file about 25KB,but the file is binary format(wasm binary module).no ohter file,does it mean i need load the library(2.5M) and the result file(25KB) in my production environment? I change the `CMAKE_EXECUTABLE_SUFFIX` to js,but the result is same.

When i build my library  whth `-s WASM_OBJECT_FILES=0` the library is `.so` (LLVM IR bitcode format),the finally result is also one binary file,but the size is about 2.5M.Upstream result is bigger than fastcomp.

My cmakeList is:

```
cmake_minimum_required(VERSION 3.0.0)
project(TASM2 VERSION 0.1.0)

aux_source_directory(src DIR_SRCS)
include_directories("include/")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/dist-new2)

set(TASSL_ROOT "/home/fan/Tools/TASSL-1.1.1b/emcc-build-v4")

include_directories("${TASSL_ROOT}/include" )
link_directories("${TASSL_ROOT}/lib")

set(CMAKE_C_FLAGS "-Oz --pre-js ../pre.js -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='[\"cwrap\",\"getValue\",\"setValue\"]'")

SET(CMAKE_EXECUTABLE_SUFFIX ".html")

add_executable(TASM2 ${DIR_SRCS})
target_link_libraries(TASM2 crypto)


set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
```
I think fastcomp is more convenience,it can generate js glue code,I can test my code,because i am not familer with javascript language.And the result file is smaller.

**Comment by sbc100** [comment]
There seems to be multiple things going on here.  First of all both fastcomp and the llvm back should both produce 3 files when the output ends in .html:  a .html file, a .js file and a .wasm file.     if you are seeing an html file that doesn't contain html, then we should first try to figure out why that is happening.   

Secondly, I would advise switching from using the .so file to .a file for libcypto.     Trying to use the fake .so file support in emscripten seems be complicating things and there is no benefit from doing this.

Once we have fixed those two issues, we can look at code size.  In general upstream llvm should probably comparable sized output (often smaller output) so something strange much be going on there.
