### ISSUE TITLE
Distribution of Liberation Sans Bold without source

### ISSUE THREAD

**Issue by JohnScott623** [emscripten-core/emscripten#10146]
Hello,

See the [report by the Debian Fonts Team downstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851109). LiberationSansBold.ttf is kept in tests/freetype/. This is version 1.06, which is licensed under the GPL and needs to be distributed with its source code.

**Comment by juj** [comment]
Looks like this came from an ancient commit at https://github.com/emscripten-core/emscripten/commit/82baf498bf205cd79bc054b1592d66d899fbc5d9.

Probably simplest to just replace the font file with something permissive, as the actual font used for the test does not matter the slightest.

**Comment by VirtualTim** [comment]
It looks like the freetype code is kept under [/tests/freetype/](https://github.com/emscripten-core/emscripten/tree/incoming/tests/freetype).
Am I missing something?

**Comment by juj** [comment]
They are referring to the source code of the font, not source code of freetype.

That being said, I now notice the link is ancient from 2017, and the URLs it link to are old or dead.

It looks like liberationfonts lives now in https://github.com/liberationfonts/liberation-fonts and is not under GPL license, but under another license "SIL Open Font License, Version 1.1.".

**Comment by JohnScott623** [comment]
On January 6, 2020 5:32:38 AM EST, juj <notifications@github.com> wrote:
>They are referring to the source code of the font, not source code of freetype.
>
>That being said, I now notice the link is ancient from 2017, and the URLs it link to are old or dead.
>
>It looks like liberationfonts lives now in https://github.com/liberationfonts/liberation-fonts and is not under GPL license, but under another license "SIL Open Font License, Version 1.1.".
>

The new 2.0 version is not under the GPL, but you're shipping the 1.x GPL version.

**Comment by kripken** [comment]
Thanks for the bug report @JohnScott623 !

I looked for the old source but couldn't find it, so as suggested above I propose upgrading to 2.00.5 in #10153.
