### ISSUE TITLE
Error when using glCompileShader: 'GL_OES_EGL_image_external' : extension is not supported"

### ISSUE THREAD

**Issue by yylittlefish** [emscripten-core/emscripten#10144]
Hi， 
I tried to use shader of GL_OES_EGL_image_external extension, 
the code could be compiled successfully and generated wasm file, but when I run the code, I get error log:
[INFO:CONSOLE(1)] "ERROR::glCompileShader ERROR: 0:1: 'GL_OES_EGL_image_external' : extension is not supported", source: file:///appWASM.js (1)
[INFO:CONSOLE(1)] "ERROR: 0:4: 'GL_OES_EGL_image_external' : extension is not supported", source: file:///appWASM.js (1)

I tried glBindTexture(GL_TEXTURE_EXTERNAL_OES, textureID), 
there's no error, I think empscripten supportes oes extension,
I dont know why the compileShader shows not support? 

this is my code:
void Context::CreateExternalOESProgramOnce() {
  if (shader_external_oes_.program)
    return;
  static const char kFragmentShaderExternal[] =
      "#extension GL_OES_EGL_image_external : require\n"
      "precision mediump float;            \n"
      "varying vec2 v_texCoord;            \n"
      "uniform samplerExternalOES s_texture; \n"
      "void main()                         \n"
      "{"
      "    gl_FragColor = texture2D(s_texture, v_texCoord); \n"
      "}";
  shader_external_oes_ = CreateProgram(kVertexShader, kFragmentShaderExternal);
}

Shader Context::CreateProgram(
    const char* vertex_shader,
    const char* fragment_shader) {
  Shader shader;

  // Create shader program.
  shader.program = glCreateProgram();
  CreateShader(shader.program, GL_VERTEX_SHADER, vertex_shader, strlen(vertex_shader));
  CreateShader(shader.program, GL_FRAGMENT_SHADER,fragment_shader, strlen(fragment_shader));
  ...
}

void Context::CreateShader(GLuint program,
                              GLenum type,
                              const char* source,
                              int size) {
  GLuint shader = glCreateShader(type);
  glShaderSource(shader, 1, &source, &size);
  glCompileShader(shader);

  GLint success;
  GLchar infoLog[512];
  glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
  if (!success)
  {
      glGetShaderInfoLog(shader, 512, NULL, infoLog);
      printf("ERROR::glCompileShader %s\n",infoLog);
  }
  ...
}

Thank you!

**Comment by yylittlefish** [comment]
do I need to add some flag in build command?
currently I use this:
 emcc -o  appWASM.js ./dev/cpp/emscripten.cpp -O3 -s ALLOW_MEMORY_GROWTH=1 -s USE_WEBGL2=1 -s FULL_ES3=1 -s WASM=1 -s NO_EXIT_RUNTIME=1  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -std=c++1z

**Comment by juj** [comment]
The problem here is that GL_OES_EGL_image_external extension is not supported in WebGL.

Try removing the use of that extension in the program. (samplerExternalOES is not supported).

**Comment by yylittlefish** [comment]
> The problem here is that GL_OES_EGL_image_external extension is not supported in WebGL.
> 
> Try removing the use of that extension in the program. (samplerExternalOES is not supported).

Hi, I doubt that my emscripten does not support GL_OES_EGL_image_external,
I use this to check and "[WASM]GL_OES_EGL_image_external not supported" is printted.
    context = emscripten_webgl_create_context(id, &attrs);
    bool ret = emscripten_webgl_enable_extension(context, "GL_OES_EGL_image_external");
    if(ret)
    {
    	printf("[WASM]GL_OES_EGL_image_external is supported\n");
    }
    else
    {
      	printf("[WASM]GL_OES_EGL_image_external not supported\n");
    }
do you know what should I do to make emscripten support it?

**Comment by yylittlefish** [comment]
I found the reason of this issue.
when I build, I should not use "USE_WEBGL2=1 ", cause webgl2 not supports oes extension.
