### ISSUE TITLE
errno is not set properly on failure

### ISSUE THREAD

**Issue by TuckWa** [emscripten-core/emscripten#10157]
We've noticed this when switching to using the llvm-wasm backend. (currently using emscripten 1.39.4)

Here's a small testcase:
```
#include <stdio.h>
#include <errno.h>
#include <fcntl.h>

int main()
{
    int fd = 0;
    printf("errno is %d\n", errno);
    fd = open("doesnotexist.txt", O_RDONLY);
    printf("fd is %d, errno is %d\n", fd, errno);
    return 0;
}
```

When compiled with gcc, I get the expected "no such file":
**errno is 0
fd is -1, errno is 2**

When using emcc and running in a browser, I keep seeing errno being set to 44 "Channel number out of range"
(compiled with emcc testopen.c -o testopen.html)
**errno is 0
fd is -1, errno is 44**

I'm not sure if this is indicative of some other problem, but it's obviously causing some issues for us since moving off of fastcomp.

**Comment by sbc100** [comment]
errno values can differ from system to system.  Emscripen's errno values are based on WASI which uses 44 got ENOENT.   

You program should never rely on the absolute value to errno.  Try using `strerror` to print the string form of the error if you are debugging.

**Comment by TuckWa** [comment]
Good point; this was in one very old section of code and it's the first time we've been bitten by different literal values. Thanks.
