### ISSUE TITLE
RangeError: start offset of Int32Array should be a multiple of 4

### ISSUE THREAD

**Issue by matanui159** [emscripten-core/emscripten#10179]
Given the test files:
```c
#include <emscripten.h>

int main() {
    EM_ASM({
        GROWABLE_HEAP_VIEW_I32(4, 8);
    });
    return 0;
}
```
and:
```html
<html>
    <head>
        <script src='a.out.js'></script>
    </head>
</html>
```

I get the error `RangeError: start offset of Int32Array should be a multiple of 4`.

By the looks of it, `TypedArray` view offsets and lengths are byte values, so the shifting in the `GROWABLE_HEAP_VIEW_*` functions need to be removed.

**Comment by kripken** [comment]
Thanks @matanui159 ! Fix in #10189 

I think those are not used, after @brion recently refactored that code, which is why this wasn't noticed.
