### ISSUE TITLE
"-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1" breaks SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT

### ISSUE THREAD

**Issue by kyavi** [emscripten-core/emscripten#10180]
With `-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0`, you could previously set a custom input receiver: e.g. `SDL_SetHint(SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT, "custom_receiver");` , where the web page contains a text input element with the ID "custom_receiver".

The new behaviour fails to use this value correctly and throws an error.

```
exception thrown: TypeError: eventHandler.target is null,registerOrRemoveHandler@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:7984:11
__registerMouseEventCallback@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:10354:7
_emscripten_set_mousemove_callback_on_thread@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:10375:7
wasm-function[2080]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:972190:1
wasm-function[2103]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:976771:1
wasm-function[2004]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:940992:1
wasm-function[304]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:32388:1
wasm-function[326]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:60796:1
wasm-function[337]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:66602:1
wasm-function[3108]@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:1133472:1
Module.dynCall_vi@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:11544:10
browserIterationFunc@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:4782:11
runIter@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:4905:13
Browser_mainLoop_runner@blob:https://my.domain/ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:4842:9
  ec2c687a-c85a-4d13-a2bc-b3a9bed0e53d:4910:58
TypeError: eventHandler.target is null[Learn More]
```

SDL only expects a prefixed hash selector for four specific elements, and asks for it to be omitted for custom IDs. This seems fundamentally incompatible the new use of document.querySelector without Emscripten prefixing the hash itself somewhere in the middle.

At the very least, _explicitly_ setting `-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0` should not create console log message, to allow for use of the previous behaviour without an erroneous warning.

Also whether intentional or not, I think the old behaviour was to default back to the window capturing input if the hinted element couldn't be found, which I liked and would prefer over any hard errors :)

**Comment by kripken** [comment]
cc @juj
