### ISSUE TITLE
emcc commandline wildcards issue

### ISSUE THREAD

**Issue by blitzcoder** [emscripten-core/emscripten#10197]
Hi, just curious why I am getting this command line error..

https://github.com/jarikomppa/soloud/issues/243

**Comment by sbc100** [comment]
This means that you don't have files that match `../piano/*.cpp`.  These types of arguments are expected to be expanded by the shell.   If its gets as far as emcc then either no such files exist, or you are not running from a shell ?

**Comment by sbc100** [comment]
e.g. :

```
$ gcc *.cpp
gcc: error: *.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
```

**Comment by blitzcoder** [comment]
Thanks, actually everything is in place. I also tried it via `emcmdprompt.`

When I run it without wildcard, it works.. `emcc ../piano/main.cpp`

I am using emsdk v1.37 on Win7 64

**Comment by blitzcoder** [comment]
If I use a shell like GitBash, it throws an error like this:

https://github.com/emscripten-core/emscripten/issues/763

**Comment by sbc100** [comment]
Does the `../piano/*.cpp` wildcard work in general from your windows command prompt?

Can you do, for example, `dir ../piano/*.cpp` ?   Perhaps windows command prompt requires backslash as path separator?

**Comment by sbc100** [comment]
Oh .. actually windows doesn't do any wildcard expansion the shell.   I had forgot this fact.   Its up to each individual tool to do this on windows I believe.

**Comment by blitzcoder** [comment]
Yes, I see that now. closing.. Thanks!

**Comment by Peter0x44** [comment]
Note that gcc will expand wildcards on windows if it's configured with `--enable-mingw-wildcard`
it does this by setting a global varable _dowildcard to 1.
https://www.msys2.org/docs/c/

So it's not unheard of for compiler drivers to expand wildcards on their own.
Note that you can use shells like busybox-w32 etc which expand wildcards for you.

**Comment by sbc100** [comment]
We try to stay as close to upstream llvm/clang, unless there is a good reason to differ.
