### ISSUE TITLE
LLVM backend emits a lot of "no symbols" error message to stderr

### ISSUE THREAD

**Issue by weitjong** [emscripten-core/emscripten#10191]
It seems like many people are getting this but no one yet has reported the issue. The "no sysmbols" error message seems harmless based on the result of my own Web build with EMCC 1.39.5. All my build artifacts run correctly. I would like to know why do I get these "no symbols" and how do I suppress or prevent them. It is a low priority issue but I have no other issue with LLVM backend to report for now (A big thanks to everyone!).

The "no symbols" bothers me because they are spamming my build log. This is the latest build log from my CI: https://travis-ci.org/weitjong/Urho3D/jobs/635851170. The build artifacts are uploaded here: https://urho3d.github.io/samples/ and as I said earlier they are tested to be working fine so far aside from a few samples have rendering artifact due to limitation of WebGL. I cannot just redirect stderr to `/dev/null` because I think that would also redirect the genuine Clang diagnostics in the build log. I would appreciate if something could be done about it. Thanks again.

**Comment by sbc100** [comment]
Almost certainly this relates to #9758.  I wonder if you can link with EMCC_DEBUG=1 to see what files are reporting this.    I suppose it could simply be empty object files.

**Comment by weitjong** [comment]
Thanks for the prompt response. With the `EMCC_DEBUG=1` all I can see is that the "no symbols" error message were emitted when the linker using the static library `libUrho3D.a`. The archive is the collection of all the objects from the Urho3D game engine. Since Urho3D is a cross-platform project I believe some of the object files in the archive may be empty for certain platform. And if so, it would be difficult for me to change my build process just to exclude those empty object files when preparing the archive. OK, now I know why I get them, but is there a way for me to suppress them without changing my build script?

**Comment by weitjong** [comment]
Thanks! You guys are great.
