### ISSUE TITLE
DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR  new constants are undocumented, old behaviour with null is undocumented

### ISSUE THREAD

**Issue by bhelyer** [emscripten-core/emscripten#10194]
Apologies if this is the wrong place for this, it's more of a documentation issue.

I'm updating to a recent version of Emscripten and I ran into the new default for DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR -- we have some code that uses 0 as a parameter to the resize callback, and a bunch that uses "canvas" (not "#canvas").

I can set DISABLE_... to 0 to make our code work for now, but I'm looking to update it and I have discovered that all of this seems to be entirely undocumented:

https://emscripten.org/docs/api_reference/html5.h.html#registration-functions

No mention of the EMSCRIPTEN_EVENT_TARGET_BLAH constants (which ones are available?). No documentation of the "reasonable defaults" that were chosen for 0 being passed as the first parameter (which I need to know to replace it with one of the aforementioned constants). Is the old string behaviour for strings not starting with # maintained?

**Comment by kripken** [comment]
Sorry about this, we should definitely have better docs here. I was hoping @juj could help out since he knows this by far the best. But I opened #10659 now which fixes a bunch of these docs.

I'm not sure about some of those questions, like the reasonable defaults stuff - @juj can you please clarify?

**Comment by juj** [comment]
>  No documentation of the "reasonable defaults" that were chosen for 0 being passed as the first parameter

The vagueness of what `0` meant was one of the reasons for the removal of the old mechanism. There was an email on the mailing list about how to migrate, explaining which events had which defaults, i.e. what the `0` meant for each function. Alternatively that can be discovered by looking at library_html5.js on the old code.

**Comment by bhelyer** [comment]
That was one of the *points* of this issue; the mechanism was removed, but no migration information was surfaced. "Your code is now broken, the way to fix it is in an email on a list somewhere, or read the old source code' is not ideal -- if links to the material was added to the documentation, it would aid in moving people from the old busted method. As it is, the code breaks and people will naturally to just enable the deprecation disabling flag as it's the path of least resistance.
