### ISSUE TITLE
Question About EM_JS()

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#10193]
I want to use the `EM_JS` function macro in C++ to use the `fetch` function.  Would it be a good idea to use `std::promise` as the first argument to `EM_JS`?  And if so, then given the fact that it's a template, what should I put as the template argument?  

What I want to do is make a request to an external API.  If I can't easily make a CORS request with `fetch` even in a Wasm app, I may have to use `XMLHttpRequest` instead.  In that case, please help me out with that in C++ with Emscripten.  Thanks.

**Comment by DragonOsman** [comment]
I found [this](https://emscripten.org/docs/api_reference/fetch.html).  Can it be used to make a request to an API, even if I don't want to store a file via IndexedDB with it?

**Comment by VirtualTim** [comment]
Yep.
You set up attributes something like:
```
emscripten_fetch_attr_t attr;
emscripten_fetch_attr_init(&attr);
attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | /*any other attributes*/;
```
If you don't use the `EMSCRIPTEN_FETCH_PERSIST_FILE` flag then file won't be stored in IndexedDB.

**Comment by DragonOsman** [comment]
Okay, thanks.  What other attributes can I use here?

**Comment by VirtualTim** [comment]
I think the wiki page you linked is pretty good, but for more details take a look at the header too: https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/fetch.h.

**Comment by DragonOsman** [comment]
Okay, got it.  

If I want to query OpenWeatherMap for weather data using this, would it be advised to store the data in memory only or would it be better to also keep it in IndexedDB?

**Comment by VirtualTim** [comment]
IndexedDB is good for when you want the data to be persisted between browser sessions, but I'm assuming that if you want weather data you want it to be up to date, so you probably just want it downloaded to memory.

**Comment by DragonOsman** [comment]
The site I want to query, openweathermap.org, has a per-second request limit of (no more than) 60 in their free plan, so I may have to find a way to keep the requests cached for about 10 seconds (if this number of seconds is a good idea) or so and then make a new one when the time is up.  I don't know if that's possible with localStorage or IndexedDB or not, though.

**Comment by VirtualTim** [comment]
In that case you're probably better off just caching in memory.
I'd do something like create a "WeatherDownloader" class that contains things like the downloaded data, response headers, etc, and a static timestamp for the last download time. Then when you perform a new download you can compare the current time with the timestamp and determine whether you want to download the data or not.
