### ISSUE TITLE
acorn-optimizer.js fails with SDL_Init() if O3 optimization is set

### ISSUE THREAD

**Issue by vmk1802** [emscripten-core/emscripten#10205]
**build environment is** 
>>------------------------------------------
./emsdk activate latest-upstream
Writing .emscripten configuration file to user home directory /home/mk/
Backing up old Emscripten configuration file in /home/mk/.emscripten.old
The Emscripten configuration file /home/mk/.emscripten has been rewritten with the following contents:

LLVM_ROOT = '/home/mk/git/emsdk/upstream/bin'
BINARYEN_ROOT = '/home/mk/git/emsdk/upstream'
EMSCRIPTEN_ROOT = '/home/mk/git/emsdk/upstream/emscripten'
NODE_JS = '/home/mk/git/emsdk/node/12.9.1_64bit/bin/node'
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

   /home/mk/git/emsdk:/home/mk/git/emsdk/upstream/emscripten:/home/mk/git/emsdk/node/12.9.1_64bit/bin

Set the following tools as active:
   releases-upstream-8bb7b0bbbca74cc58741416cc955011f22ff5ccb-64bit
   node-12.9.1-64bit
<<------------------------------------------------------------

**source code** 
>>----------------------------------------------------------- *.c
  if (SDL_Init(SDL_INIT_AUDIO) < 0)
  {
    //SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Coud not init audio sub system : %s", SDL_GetError());
    return FAIL;
  }
<<-----------------------------------------------------------------

**build command**
>>-------------------------------------------------------------------
emcc -O3 ./source.c -o ./output.wasm -s USE_SDL=2
<<-------------------------------------------------------------------

**Error**
>>-------------------------------------------------------------------
/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:697
          infos[reached].root = true; // in global scope, root it
                              ^

TypeError: Cannot set property 'root' of undefined
    at addReach (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:697:31)
    at visitNode (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:701:9)
    at /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:718:5
    at fullWalk (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:78:3)
    at /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:76:5
    at maybeChild (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:45:7)
    at visitChildren (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:53:10)
    at fullWalk (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:75:3)
    at /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:76:5
    at maybeChild (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:45:7)
shared:ERROR: '/home/mk/git/emsdk/node/12.9.1_64bit/bin/node /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmpckGOPM.js emitDCEGraph noPrint' failed (1)
<<-------------------------------------------------------------------

Please check

**Comment by kripken** [comment]
This doesn't sound like a known issue. Can you attach the source code so we can reproduce the error? Or, if not, adding some debug logging right before the line it errors on might help understand this.

**Comment by vmk1802** [comment]
**Source code needed to generate the error is below**

```
//source.c
#include <emscripten.h>
#include <SDL2/SDL.h>


int main(int argc, char *argv[])
{
  if (SDL_Init(SDL_INIT_AUDIO) < 0)
  {
    SDL_LogError(SDL_LOG_CATEGORY_APPLICATION, "Coud not init audio sub system : %s", SDL_GetError());
    return 1;
  }
  return 0;
}
```

**Build command**

> emcc -O3 ./source.c -o ./generated.wasm -s USE_SDL=2

**Complete error log**

```
/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:697
          infos[reached].root = true; // in global scope, root it
                              ^

TypeError: Cannot set property 'root' of undefined
    at addReach (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:697:31)
    at visitNode (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:701:9)
    at /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:718:5
    at fullWalk (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:78:3)
    at /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:76:5
    at maybeChild (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:45:7)
    at visitChildren (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:53:10)
    at fullWalk (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:75:3)
    at /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:76:5
    at maybeChild (/home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js:45:7)
shared:ERROR: '/home/mk/git/emsdk/node/12.9.1_64bit/bin/node /home/mk/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/tmp9B2mK9.js emitDCEGraph noPrint' failed (1)
```

I am using the latest-upstream, but I see that this is reproducible even with the older versions.

**Comment by kripken** [comment]
Thanks @vmk1802 ! Fix in https://github.com/emscripten-core/emscripten/pull/10273 The issue is the combination of SDL2 code that assumes JS support code, with standalone mode which does not depend on JS support code.

I made it not crash there, but note that this still won't work if you actually use the JS, which typically you don't in standalone mode. We could however try to support it there, using Table calls instead, if there's a need - what's your use case?

**Comment by vmk1802** [comment]
Thank you @kripken for fixing it quickly. Sorry, I was little busy to respond in time. Yes, as you pointed my intention is to use it in standalone mode, basically with chrome wasm engine(libwee8). I could build the wasm successfully but have not tried to run the wasm yet. This is more of prove of concept for a project we are working on. I will keep you updated about the status as I come across new findings.
