### ISSUE TITLE
val.h: any problems when i use like this???????

### ISSUE THREAD

**Issue by ToTheEnd0314** [emscripten-core/emscripten#10203]
### main.cpp
```
#include <emscripten.h>
#include <emscripten/bind.h>

using namespace emscripten;

class MyClass
{
public:
    MyClass(val f);
    val func;
    
    init cppFunc()
    {
         return 1;
    }
}

MyClass::MyClass(val f):func(f)
{
    f.call<val>("run", val(&MyClass::cppFunc));
}

EMSCRIPTEN_BINDS(test_module)
{
    class_<MyClass>("MyClass")
        .constructor<val>()
}
```

### html script
```
<script src="test.js"></script>
<script>
    Module.onRuntimeInitialized = function() {
        let MyClass = Module.MyClass;

        new MyClass({
            name: "test",
            run: (cppFunc) => {
                console.log("Cpp Func Log = ", cppFunc());
            }
        });
    }
</script>
```

#### Problems
I want to log **Cpp Func Log = 1** in web browser console, But I got below Error: <br>

```
(index):1 Uncaught (in promise) 
BindingError {name: "BindingError", message: "_emval_take_value has unknown type M3ByyFiN10emscripten3valEE", stack: "BindingError: _emval_take_value has unknown type M…nction[98]:0x37d8↵    at wasm-function[54]:0x2750"}
name: "BindingError"
message: "_emval_take_value has unknown type M3ByyFiN10emscripten3valEE"
stack: "BindingError: _emval_take_value has unknown type M3ByyFiN10emscripten3valEE↵    at BindingError.<anonymous> (http://localhost:8080/test.js:1:12869)↵    at new BindingError (eval at createNamedFu...
```

##### How can i make this functionality come true, or any error within my code, Thank You!!!

**Comment by ToTheEnd0314** [comment]
> ### main.cpp
> ```
> #include <emscripten.h>
> #include <emscripten/bind.h>
> 
> using namespace emscripten;
> 
> class MyClass
> {
> public:
>     MyClass(val f);
>     val func;
>     
>     init cppFunc()
>     {
>          return 1;
>     }
> }
> 
> MyClass::MyClass(val f):func(f)
> {
>     f.call<val>("run", val(&MyClass::cppFunc));
> }
> 
> EMSCRIPTEN_BINDS(test_module)
> {
>     class_<MyClass>("MyClass")
>         .constructor<val>()
> }
> ```
> 
> ### html script
> ```
> <script src="test.js"></script>
> <script>
>     Module.onRuntimeInitialized = function() {
>         let MyClass = Module.MyClass;
> 
>         new MyClass({
>             name: "test",
>             run: (cppFunc) => {
>                 console.log("Cpp Func Log = ", cppFunc());
>             }
>         });
>     }
> </script>
> ```
> 
> #### Problems
> I want to log **Cpp Func Log = 1** in web browser console, But I got below Error:
> 
> ```
> (index):1 Uncaught (in promise) 
> BindingError {name: "BindingError", message: "_emval_take_value has unknown type M3ByyFiN10emscripten3valEE", stack: "BindingError: _emval_take_value has unknown type M…nction[98]:0x37d8↵    at wasm-function[54]:0x2750"}
> name: "BindingError"
> message: "_emval_take_value has unknown type M3ByyFiN10emscripten3valEE"
> stack: "BindingError: _emval_take_value has unknown type M3ByyFiN10emscripten3valEE↵    at BindingError.<anonymous> (http://localhost:8080/test.js:1:12869)↵    at new BindingError (eval at createNamedFu...
> ```
> 
> ##### How can i make this functionality come true, or any error within my code, Thank You!!!

type maybe not ** M3ByyFiN10emscripten3valEE **

**Comment by ToTheEnd0314** [comment]
type maybe not ** M3ByyFiN10emscripten3valEE **

**Comment by jdoubleu** [comment]
FWIW, Embind should properly handle `emscripten::val` bindings. However, I'm not sure if it's allowed to pass them by value. Try taking an `const emscripten::val&` instead.
