### ISSUE TITLE
Move documentation from emscripten-site/gh-pages to master branch of this repo

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10228]
Apparently we can use the docs/ subdir to publish the emscripten site so we can move away from kripken/emscripten-site.

This should make the docs update process a lot smoother and obvious.

**Comment by sbc100** [comment]
Also, can you remind me again why we couldn't move emscripten-site to this org?  Was there some other reason?

**Comment by kripken** [comment]
It might break URLs to move that repo to this org, was the worry. After we moved to using emscripten.org on the site maybe that risk is gone.

How would the docs/ subdir work? It would contain the output of sphinx etc., in the master branch directly, and not gh-pages? That seems awkward somehow...

**Comment by kripken** [comment]
I see, interesting. That part sounds good.

Another issue is that there are a lot of files in the website, and a lot of them change each update (each tagged version, all the titles change, for example). It would add a lot of diffs to emscripten which is already not a small repo. I kind of like having the production website on the side.

**Comment by sbc100** [comment]
I'll do some investigation.   At the very least we should move it to the same org if possible.
