### ISSUE TITLE
Reverting to previous emsdk version

### ISSUE THREAD

**Issue by wini3d** [emscripten-core/emscripten#10220]
I tried updating to the latest version but the 1.35 prompt is throwing download errors so I decided to just start from scratch.

So I renamed my old installation and installed the new one on the same path c:/emscripten. Everything works well but I need to check back on my old installation, I renamed it back and now I am getting LLVM errors that I have tested from the latest version is showing up on my old 1.35 which did not exist when before updating to latest.

renamed back the .emscripten-old in my home folder that was set during my latest installation and still throwing the latest version errors.

**Comment by wini3d** [comment]
running my old 1.35 `emcc -v` it is showing clang 1.37, but in my 1.35 environment it is 1.35 or e1.35.0_64bit?


```
import os
JAVA='C:/emscripten/java/7.45_64bit/bin/java.exe'
SPIDERMONKEY_ENGINE='C:/emscripten/spidermonkey/37.0.1_64bit/js.exe'
CRUNCH='C:/emscripten/crunch/1.03/crunch.exe'
LLVM_ROOT='C:/emscripten/clang/e1.35.0_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='C:/emscripten/clang/e1.35.0_64bit/optimizer.exe'
NODE_JS='C:/emscripten/node/4.1.1_64bit/bin/node'
PYTHON='C:/emscripten/python/2.7.5.3_64bit/python.exe'
EMSCRIPTEN_ROOT='C:/emscripten/emscripten/1.35.0'
```

**Comment by sbc100** [comment]
Can you should the actual errors you are seeing.  Also can you show the download error?

Does `emcc --clear-cache` after you rename fix the issue?

**Comment by wini3d** [comment]
Thanks actually I think it is normal as the 1.35 came from an offline installer.

I am concerned about getting back my previous installation and just think about switching back and forth later.

It seems my llvm/clang or other tools has been updated when I installed the latest 1.39.

Even when I reinstalled the offline 1.35 installer, I noticed longer compile times and a lot of warnings that did not show before like these:

```
WARNING:root:generating system library: libcxx_noexcept.a...
WARNING:root:                                               ok
WARNING:root:generating system library: libcxxabi.bc...
WARNING:root:                                          ok
WARNING:root:generating system library: libc.bc...
```
```
WARNING:root:                                     ok
WARNING:root:generating system library: dlmalloc.bc...
WARNING:root:     
```

so how can I revert back to my previous emscripten 1.35 build tools?

**Comment by sbc100** [comment]
Those warning about generating system libraries should only occur the first time you use emscripten, or whenever you switch versions.  They are normal and expected.

**Comment by wini3d** [comment]
Thanks for the info. I figured the older version was garbled anyway and can't reproduce how it was working that way. Anyway, better to move forward with the latest emsdk version.

thanks again.
