### ISSUE TITLE
SDL2_MIXER cannot be used yet.

### ISSUE THREAD

**Issue by mrj0721** [emscripten-core/emscripten#10237]
The error when including <SDL2 / SDL_mixer.h> has definitely disappeared.
However, using the function of <SDL2 / SDL_mixer.h> results in an error.

<pre>
wasm-ld: warning: function signature mismatch: SDL_SetError
defined as (i32, i32) -> void in C:\Users\Ryu\.emscripten_cache\wasm-obj\libSDL2_mixer.a(mixer_8d0e20b3.c.o)
defined as (i32, i32) -> i32 in C:\Users\Ryu\.emscripten_cache\wasm-obj\libSDL2.a(SDL_error_000ca977.c.o)

wasm-ld: warning: function signature mismatch: SDL_Error
defined as (i32) -> void in C:\Users\Ryu\.emscripten_cache\wasm-obj\libSDL2_mixer.a(music_ogg_47d59e18.c.o)
defined as (i32) -> i32 in C:\Users\Ryu\.emscripten_cache\wasm-obj\libSDL2.a(SDL_error_000ca977.c.o)
</pre>

Are you testing until execution?

Can you give me a sample to play sound on Windows?

**Comment by sbc100** [comment]
I found the issue.  It looks like sdl2_mixer was being built against the SDL1 headers which have different signatures for those functions.

**Comment by sbc100** [comment]
We have two tests for sdl2_mixer.  One is part of the `other` test suite which only tests compilation.   The other is part of the browser test suite but is disabled in CI because we don't currently run any audio tests in the CI.  I imagine this is due to limitations of the CI browser environments.
