### ISSUE TITLE
Any plan to upgrade emscripten 1.39.x for Mac brew?

### ISSUE THREAD

**Issue by linux-china** [emscripten-core/emscripten#10236]
emscripten on brew is out of date for long time, and still 1.38.44 
 https://formulae.brew.sh/formula/emscripten
Any plan to upgrade to last version?

**Comment by Akaricchi** [comment]
The homebrew formula is not maintained by emscripten developers. You can actually submit an update yourself: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md
