### ISSUE TITLE
browser.test_sdl2_ttf test is flakey

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10233]
It seems to fail fairly regularly under both chrome and firefox:

https://app.circleci.com/jobs/github/emscripten-core/emscripten/231216

```
test_sdl2_ttf (test_browser.browser) ... [test error (see below), automatically retrying]
Expected to have '/report_result?0' == '/report_result?155', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+/report_result?155
```

**Comment by kripken** [comment]
One step to handling issues like this might be to somehow save the image when it isn't correct, so we can view it in the log somehow.
