### ISSUE TITLE
load-time error with js/wasm

### ISSUE THREAD

**Issue by CRasterImage** [emscripten-core/emscripten#10248]
I get this error in the browser console when trying to load a simple js / wasm:
```
BindingError {name: "BindingError", message: "No dynCall invoker for signature: ii", stack: "BindingError: No dynCall invoker for signature: ii…meCallbacks (http://localhost:8000/foo.js:1:7729)"}
name: "BindingError"
message: "No dynCall invoker for signature: ii"
stack: "BindingError: No dynCall invoker for signature: ii↵
    at BindingError.<anonymous> (http://localhost:8000/foo.js:1:12836)↵
    at new BindingError (eval at createNamedFunction (http://localhost:8000/foo.js:1:12545), <anonymous>:4:34)↵
    at throwBindingError (http://localhost:8000/foo.js:1:13277)↵
    at embind__requireFunction (http://localhost:8000/foo.js:1:29330)↵
    at __embind_register_class (http://localhost:8000/foo.js:1:30314)↵
    at wasm-function[45]:0x2715↵
    at wasm-function[88]:0x36a8↵
    at Module.___wasm_call_ctors (http://localhost:8000/foo.js:1:46999)↵
    at func (http://localhost:8000/foo.js:1:11692)↵
    at callRuntimeCallbacks (http://localhost:8000/foo.js:1:7729)"
```

the C++ code I am compiling is:
```
#include <math.h>
#include <emscripten.h>
#include <emscripten/bind.h>
#include <emscripten/html5.h>

using namespace emscripten;

class FOOWASMInterface
{
public:
   FOOWASMInterface() { }

   float bar(float value, bool up)
   {
      if(up)
         return ceil(value);
      else
         return floor(value);
   }
};

EMSCRIPTEN_BINDINGS(FOOModule) {
   class_<FOOWASMInterface>("FOOWASMInterface")
      .constructor<>()
      .function("bar", &FOOWASMInterface::bar)
      ;
}
```

and my compile instruction is:
`em++ -O3 -std=c++14 -s ERROR_ON_UNDEFINED_SYMBOLS=0 foo_bindings.cpp --bind -s WASM=1 -o foo.js`

and my javascript is:
```
Module = {
   onRuntimeInitialized: function () {
      var FOOLib = new Module.FOOWASMInterface();

      var value = FOOLib.bar(5.4, true);
      console.log('5.4 ceil' + value);
      value = FOOLib.bar(5.4, false);
      console.log('5.4 floor' + value);
   }
};
```

Is this a bug?  Or am I making a mistake somewhere?

**Comment by jgravelle-google** [comment]
I wasn't able to reproduce this. What version of Emscripten are you using?

**Comment by CRasterImage** [comment]
em++ --version reports
1.39.0

**Comment by jgravelle-google** [comment]
I don't know of anything that's changed since then. Did you install via emsdk?

Another thing I noticed was that I can simplify your command down to `em++ -O3 foo_bindings.cpp --bind -o foo.js`. None of the flags change the behavior on my end. In particular: why do you have `-s ERROR_ON_UNDEFINED_SYMBOLS=0`? That will tend to hide problems from earlier. What output do you get if you omit that?

The last thing that comes to mind is, which LLVM are you using? It may be possible that you're using the older fastcomp backend, which may have different behavior. Your `~/.emscripten` should have an LLVM_ROOT set which should point at the LLVM that emscripten is using.

**Comment by CRasterImage** [comment]
This is a windows 10 machine.  my .emcripten file told me where LLVM could be found.  The directory has a dozen .exe files.  Which exe should ask for version info?  Would I use"--version" to ask it?

**Comment by CRasterImage** [comment]
I did --version on llc.exe just to test and it reports:
LLVM version 10.0.0svn
DEBUG build with assertions.
Default target: x86_64-pc-windows-msvc
Host CPU: skylake
and some other stuff

**Comment by CRasterImage** [comment]
Also, the "A quick example" embind code example:
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#embind

gives me console binding errors.

**Comment by CRasterImage** [comment]
Oh, I found the problem.  In the html, I was listing the foo.js file ahead of the code that loads the module.  Apparently it doesn't like that.  It wants foo.js listed after.
