### ISSUE TITLE
nearbyintf doesn't obey rounding mode

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#10241]
Here is a quick test:

```c
#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include <fenv.h>

int main(void) {
  float x = -369.61;
  int32_t y;

  fesetround(FE_TOWARDZERO);

  y = (int32_t) nearbyintf(x);

  printf("%d %f\n", y, nearbyintf(x));

  return 0;
}
```

`nearbyintf` should be returning -369.0f, not -370.0f.

**Comment by kripken** [comment]
Wasm doesn't support rounding modes, so in practice we just use the normal wasm rounding (emulating the modes in software would probably be too slow to be useful for many things). This can cause differences with other platforms, sadly. Perhaps we should document this better if it isn't already.

**Comment by nemequ** [comment]
That makes sense.

Maybe a compile time warning on `fesetround` would help?

**Comment by kripken** [comment]
Hmm, only the linker knows when it's included, and it isn't obvious to me how to run a check like that there.

**Comment by nemequ** [comment]
I guess `__attribute__((availability(wasm,unavailable)))` would be the right thing to do, though I'm not sure if wasm (or emscripten) is supported as a platform.

If not, maybe `__attribute__((diagnose_if(rounding_mode != X, "WASM does not support rounding modes")))` (I'm not sure what the X should be… does WASM specify it?) would work.  That does have the benefit of being able to warn only if the rounding mode is not what WASM supports, but the major disadvantage of being ignored if the rounding mode isn't known at compile time (I can't remember if it requires a constant expression or just `__builtin_constant_p`).

There is also the deprecated attribute.  I "deprecated" isn't exactly the right word, but I think it would at least get the point across.

**Comment by kripken** [comment]
I think those would happen at compile time - which is when libc is compiled. That may not happen on the user's machine as we ship precompiled libc.

**Comment by nemequ** [comment]
Obviously you're the expert on emscripten internals (I really don't know anything about them), so maybe I'm missing something, but…

They happen at compile time, but they are all triggered when coding *calling* them is compiled, not when the code implementing them is compiled.  I think that when libc is compiled is largely irrelevant here.

At least diagnose_if and deprecated work this way.  TBH I've never actually used availability since AFAICT it's currently macOS-specific, but if it can be extended to emscripten it seems like the only down-side would be that you can't even allow what would basically be a no-op like `fesetround(fegetround())`.

**Comment by kripken** [comment]
Oh, right, if it's on the header then that sounds like it could work. Sorry, I'm not that familiar with those intrinsics. They should work the same as native, though, so if you know how to make them work, a PR would be great!

Concretely, it sounds like we should warn on any usage of `fesetround` etc. (I don't think we should warn on nearbyintf itself, IIUC).

**Comment by nemequ** [comment]
Any opinion on whether it should be a warning or an error?  If the latter

```diff
diff --git a/system/include/libc/fenv.h b/system/include/libc/fenv.h
index 05de990c0..ee1f879c0 100644
--- a/system/include/libc/fenv.h
+++ b/system/include/libc/fenv.h
@@ -14,7 +14,7 @@ int fesetexceptflag(const fexcept_t *, int);
 int fetestexcept(int);
 
 int fegetround(void);
-int fesetround(int);
+int fesetround(int) __attribute__((__unavailable__));
 
 int fegetenv(fenv_t *);
 int feholdexcept(fenv_t *);
@@ -25,4 +25,3 @@ int feupdateenv(const fenv_t *);
 }
 #endif
 #endif
-
```

Will do the trick nicely:

```
nemequ@peltast:~/t$ emcc -o round.js round.c
round.c:10:3: error: 'fesetround' is unavailable
  fesetround(FE_TOWARDZERO);
  ^
/opt/emscripten/upstream/emscripten/system/include/libc/fenv.h:17:5: note: 'fesetround' has been explicitly marked unavailable here
int fesetround(int) __attribute__((__unavailable__));
    ^
1 error generated.
```

For a warning I guess the best option would be the deprecated attribute:

```diff
diff --git a/system/include/libc/fenv.h b/system/include/libc/fenv.h
index 05de990c0..fce22f3ad 100644
--- a/system/include/libc/fenv.h
+++ b/system/include/libc/fenv.h
@@ -14,7 +14,7 @@ int fesetexceptflag(const fexcept_t *, int);
 int fetestexcept(int);
 
 int fegetround(void);
-int fesetround(int);
+int fesetround(int) __attribute__((__deprecated__("WASM does not support rounding modes")));
 
 int fegetenv(fenv_t *);
 int feholdexcept(fenv_t *);
@@ -25,4 +25,3 @@ int feupdateenv(const fenv_t *);
 }
 #endif
 #endif
-
```

```
nemequ@peltast:~/t$ emcc -o round.js round.c
round.c:10:3: warning: 'fesetround' is deprecated: WASM does not support rounding modes [-Wdeprecated-declarations]
  fesetround(FE_TOWARDZERO);
  ^
/opt/emscripten/upstream/emscripten/system/include/libc/fenv.h:17:36: note: 'fesetround' has been explicitly marked deprecated here
int fesetround(int) __attribute__((__deprecated__("WASM does not support rounding modes")));
                                   ^
1 warning generated.
```

**Comment by kripken** [comment]
I think a warning would be more appropriate, myself. A PR with that would be great!
