### ISSUE TITLE
Problem with minimal OpenAL capture

### ISSUE THREAD

**Issue by hosackm** [emscripten-core/emscripten#10247]
I'm new to Emscripten and OpenAL and I'm trying to get a minimal audio capture example working.  For now, all I want to do is display the number of frames (ALC_CAPTURE_SAMPLES) that are available before I start accessing the audio data.  I've read through the documentation that mentions that the number of frames will be 0 until the user clicks 'allow' when prompted for an audio device.  Even after I click 'allow' this number stays at 0 frames.

Here's what I have so far:

```
#include <stdio.h>
#include <emscripten.h>
#include <AL/al.h>
#include <AL/alc.h>

void mycallback(void *arg)
{
    ALCint nframes;
    ALCdevice *dev = (ALCdevice*)arg;

    alcGetIntegerv(dev, ALC_CAPTURE_SAMPLES, 1, &nframes);
    printf("Opened '%s'\n", alcGetString(dev, ALC_CAPTURE_DEVICE_SPECIFIER));
    printf("Num Frames: %d\n", nframes);
}

int main(int argc, char *argv[])
{
    ALCdevice *dev = NULL;

    dev = alcCaptureOpenDevice(NULL, 48000, AL_FORMAT_MONO16, 1024);
    alcCaptureStart(dev);
    emscripten_set_main_loop_arg(mycallback, dev, -1, 1);

    return 0;
}
```

Do you know why the audio device never seems to have incoming audio samples?

**Comment by hosackm** [comment]
It looks like the real problem was that Chrome wouldn't allow recording until the user interacted with the page.  I added a <button> element to page that starts the audio capture and it works now.

**Comment by popomen** [comment]
> It looks like the real problem was that Chrome wouldn't allow recording until the user interacted with the page. I added a element to page that starts the audio capture and it works now.

How does your example work? Now my nframe is always 0.

**Comment by hosackm** [comment]
Hey popomen,

The user has to interact with the page so what I did was add a <button> to start the processing. This way the user has to click it to start the processing. That was enough for me to get it to work.
