### ISSUE TITLE
Update pthread and memory-growth docs

### ISSUE THREAD

**Issue by matanui159** [emscripten-core/emscripten#10250]
The docs currently say:
> Pthreads + memory growth (ALLOW_MEMORY_GROWTH) is especially tricky, see wasm design issue #1271. This currently causes JS accessing the wasm memory to be slow - but this will likely only be noticeable if the JS does large amounts of memory reads and writes (wasm runs at full speed, so moving work over can fix this). This also requires that your JS be aware that the HEAP* views may need to be updated - use the GROWABLE_HEAP_* helper functions which automatically handle that for you.

However, from my understanding from looking through the code and in particular PR #9970 this isn't necessary anymore since this is done automatically during the build step by converting `HEAP*` accesses. The documentation should probably be updated to match this (but still point this out just in case someone gets confused by the conversion).

**Comment by brion** [comment]
Whoops, that should've gotten updated with the original patch... lemme try & fix. :)

**Comment by brion** [comment]
I think there's two different cases here which behave differently:
* JS code in the emscripten core and user-added libraries -- `HEAPU8` etc gets transformed automatically to use `GROWABLE_HEAP_U8()` etc. Nothing needs to be done, just keep using `HEAP*`.
* JS code outside the module that accesses `Module.HEAPU8` etc to get at linear memory -- these do not get transformed, and may turn up with a too-small view after allocation. These don't have a reliable 'by default' method of access, as neither `wasmMemory` nor the helper functions are  exported on the `Module` var.

The latter is more likely for library-like use cases where wrapper code providing higher-level interfaces for string and binary data might or might not be part of the emscripten module.

**Comment by matanui159** [comment]
Ty!
