### ISSUE TITLE
llvm compile error "inlinable function call"

### ISSUE THREAD

**Issue by acthp** [emscripten-core/emscripten#10268]
```
inlinable function call in a function with debug info must have a !dbg location
  tail call void @free(i8* %32)
```
Compile fails with llvm backend, but not fastcomp.

steps to reproduce

 ```
CHECK_RELEASE=0.13.0
CHECK_TGZ=check-${CHECK_RELEASE}.tar.gz
wget https://github.com/libcheck/check/releases/download/${CHECK_RELEASE}/${CHECK_TGZ}
tar zxf ${CHECK_TGZ}
mkdir -p check-build
cd check-build
emconfigure ../check-${CHECK_RELEASE}/configure
make
```

Maybe related to https://bugs.llvm.org/show_bug.cgi?id=31029

**Comment by kripken** [comment]
Which version is that with? The `make` command finishes without error for me (on latest tip of tree build).

**Comment by acthp** [comment]
Tested with emsdk 1.39.5 and 1.39.6

**Comment by kripken** [comment]
Perhaps it's been fixed since then, can try the `tot` build instead of `latest` or `1.39.6`. But less likely.

Perhaps it's OS dependent, hopefully other people can test this too.

**Comment by MSNexploder** [comment]
Just tested it using emsdk `1.39.6` and `tot`. Both error out with the same message.

I'm running on MacOS 10.15.2 (aka darwin19.2.0).

**Comment by kripken** [comment]
I tested on linux (where it worked).
