### ISSUE TITLE
[Feature Request, RFC] API for calling C++ command line program from Javascript with arguments and files.

### ISSUE THREAD

**Issue by marciot** [emscripten-core/emscripten#10277]
I've used Emscripten for several projects and one issue I run into often is that it is very difficult to interact with command line programs from an HTML web app. I feel the capability is there somehow if you manage to make the correct bindings, but this is far from trivial and there isn't an easy API for doing so. With this in mind, I would propose a set of requirements and get some feedback from devs on how feasible it would be make an API like this. Here are the requirements for the API:

- Allow a command-line program to be started using one or more command line arguments.
- Allow virtual "files" to be loaded from Javascript (i.e. they could be passed on as an array of bytes) prior to starting such program. 
- Either run the program on the current thread, or have it in a separate thread (maybe a web worker?)
- Have the ability to capture stdout and stderr and act on the output (possibly at real-time via a callback).
- Have the ability to load data into stdin (possibly in response to stdout).
- Have a means of detecting when the program has finished and get the status code.
- Allow multiple command line utilities to be packaged as one and executed individually.

If such an API existed, here is a hypothetical webpage that compressed a text string using the command-line "gzip" utility:

```
<html>
   <head>
      <script src="gzip.wasm.js">
      <script src="emscripten.js">
      <script>
           proc = new EmscriptenProcess("gzip");

           function doIt() {
               proc.addArgument("-c");
               proc.stdin = getElementById("in").text
               proc.onCommandExecuted = doneIt;
               proc.startAsWorker();
           }

           function doneIt() {
               if (proc.status == 0) {
                  getElementById("out").text = proc.stdout;
               } else {
                   alert("Error:" + proc.stderr);
               }
           }
      </script>
   </head>
   <body>
       Uncompressed Text: <textarea id="in">Hello world!</textarea>
       Compressed Text: <textarea id="out"></textarea>
       <button onClick="doIt();">Compress It</button>
   </body>
</html>
```

Anyhow, this is a pie in the sky idea. I know very little about how Emscripten works internally, so I do not know how difficult or whether it would be possible to do something like this at all. That said, from a user perspective, however, it would be fantastic; if something like this existed, I think it would make Emscripten a lot more approachable by a lot of people who simply wanted to run existing command line tools in their web pages without having to modify the original source.

**Comment by marciot** [comment]
Closing and reposting to emsdk.

**Comment by marciot** [comment]
Reopening as it is unclear whether this functionality would be part of the SDK or the core.

**Comment by marciot** [comment]
Unclear whether this belongs in emsdk or emscripten. So this has been duplicated as [#428](https://github.com/emscripten-core/emsdk/issues/428). I can close down one or the other once I learn where it belongs.

**Comment by kripken** [comment]
I think this makes more sense in this repo, as it's core emscripten functionality.

I like the idea! While we do have options to do many of the things you mention, many of those APIs grew organically over time, and are not all handled in a simple and central way. I'd be happy if someone were interested to design and implement a nicer JS API.

Specifically for

> Allow virtual "files" to be loaded from Javascript (i.e. they could be passed on as an array of bytes) prior to starting such program.

There is the FS API, stuff like createPreloadedFile, https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.createPreloadedFile

**Comment by marciot** [comment]
Thanks for the feedback. I have more or less been able to do what I want by setting 'Module.noInitialRun' to false and then call 'callMain' with my command line arguments. None of this was particularly easy to figure out. I only came across 'callMain' after having run the generated js file, which is quite illegible, though a pretty-printer so I could read it.

**Comment by kripken** [comment]
If you have ideas for documentation improvements, that would be appreciated - since you just noticed what was missing you can see better than us probably what should be better. Please open a PR if you can (if not, some concrete suggestions would be useful too).
