### ISSUE TITLE
GL

### ISSUE THREAD

**Issue by zvanow** [emscripten-core/emscripten#10286]
When compiling:
emcc tests \ sourc_s_gh.cpp -s USE_SDL = 2 -s FULL_ES2 = 1 --preload-file tests \ glbook -o index.html -O3 -s ALLOW_MEMORY_GROWTH = 1 -s USE_SDL_IMAGE = 2 -s USE_SDL_TTF = 2 -s SDL2IMAGE "['png']"
I get errors:
SDL_error.h: 57: 5: error: redefinition of enumerator 'SDL_ENOMEM'
SDL_error.h: 58: 5: error: redefinition of enumerator 'SDL_EFREAD'
SDL / SDL_error.h: 42: 30: error: functions that differ only in their return type cannot be overloaded

and other. What does it mean? Thanks.

**Comment by kripken** [comment]
I'm not sure which file you mean by `tests \ sourc_s_gh.cpp` but an error like this might be caused by mixing SDL1 and SDL2 includes. The flags imply you are using SDL2, so be careful of includes to `"SDL/"` (there should only be `"SDL2/"`).

**Comment by zvanow** [comment]
Thanks. I compiled the code from:
https://gist.github.com/derofim/c00a8ce4c7233862ecdd

Next I tweaked this:
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_ttf.h>
 #include <SDL/SDL_mixer.h>

And SDL_mixer.h left as it was. And because of him, I get the same errors again:
In file included from tests\sourc_s_gh.cpp:8:
In file included from F:\em\emsdk\upstream\emscripten\system\include\SDL/SDL_mixer.h:27:
In file included from F:\em\emsdk\upstream\emscripten\system\include\SDL/SDL_types.h:29:
F:\em\emsdk\upstream\emscripten\system\include\SDL/SDL_stdinc.h:117:5: error: redefinition of enumerator 'SDL_FALSE'
    SDL_FALSE = 0,
    ^
C:\Users\123\.emscripten_cache\wasm-obj\include\SDL2/SDL_stdinc.h:163:5: note: previous definition is here
    SDL_FALSE = 0,
    ^
In file included from tests\sourc_s_gh.cpp:8:
In file included from F:\em\emsdk\upstream\emscripten\system\include\SDL/SDL_mixer.h:27:
In file included from F:\em\emsdk\upstream\emscripten\system\include\SDL/SDL_types.h:29:
F:\em\emsdk\upstream\emscripten\system\include\SDL/SDL_stdinc.h:118:5: error: redefinition of enumerator 'SDL_TRUE'
    SDL_TRUE = 1
    ^
C:\Users\123\.emscripten_cache\wasm-obj\include\SDL2/SDL_stdinc.h:164:5: note: previous definition is here
    SDL_TRUE = 1

**Comment by kripken** [comment]
Makes sense, yeah. Using SDL2_mixer should work.

**Comment by zvanow** [comment]
I do not have such a file:  SDL2_mixer.h
There is only: SDL_mixer.h

**Comment by sbc100** [comment]
I think it should be `SDL2/SDL_mixer.h`.   Basically, you shouldn't mix headers from `SDL` and `SDL2`

**Comment by kripken** [comment]
SDL2_mixer is like SDL2_image. In your command you already have `-s USE_SDL_IMAGE=2`, I think you need to add `-s USE_SDL_MIXER=2`.

**Comment by zvanow** [comment]
Thanks, it worked. Interestingly, at the beginning of the file <SDL2 / SDL_mixer.h> was not. And then it appeared. Apparently it downloaded -). I had not expected.
