### ISSUE TITLE
can't install--broken repository?

### ISSUE THREAD

**Issue by adam-a-smith** [emscripten-core/emscripten#10297]
(Apologies if this isn't an appropriate place to post this. But I can't find an e-mail, and this appears to be the only way to contact you.)

Getting the following when I try to install:

adam@cheshire:/tmp/emsdk$ ./emsdk install latest
Installing SDK 'sdk-releases-upstream-967836071d96d9b7894e492382f5fcb96423fc07-64bit'..
Installing tool 'node-12.9.1-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.9.1-linux-x64.tar.xz': <urlopen error [Errno 104] Connection reset by peer>
Installation failed!

Absolutely no idea what to do after that. Apparently some repository or other is offline?

(Also--please consider making a Linux package that can be downloaded via Synaptic, that's more recent than 1.22.1? GitHub is utterly confusing for those who are not enmeshed in it.)

**Comment by sbc100** [comment]
That URL is to google cloud storage which is probably among the most reliable hosts on the internet.  Most likely you are seeing some kind of temporary issue with your internet connection or routing.   Does this happen consistently for you?

If you want a more recent package for your distribution that is a job for the downstream maintainer.   We are trying to increase our support for such maintainers but its still up to them to update either packages.  Which distro are you using?

**Comment by adam-a-smith** [comment]
Thanks for replying.

When I try to open https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.9.1-linux-x64.tar.xz with a browser, I get:

Secure Connection Failed
An error occurred during a connection to storage.googleapis.com. PR_CONNECT_RESET_ERROR

Yes, this is consistent. (I've also seen this recently with a totally unrelated project.)

Using Mint 19.3

**Comment by sbc100** [comment]
I'm afraid it looks like the problem is at your end.  That URL works fine from here.   

You can probably debug using tools such as `tcpdump`, `curl -v`, `wireshark`, etc.   I surprised that it only effecting `storage.googleapis.com`, if that URL doesn't work I would expect your internet connection in general to be broken too.

**Comment by adam-a-smith** [comment]
Crap.

I'm closing this issue. Thank you for your help--I really do appreciate the attention. I'm going to go yell at my IT Department now, and maybe try to access the files from home.
