### ISSUE TITLE
Exception::what() contains little information

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#10292]
Example code:
```
#include <exception>
#include <stdexcept>
#include <cstdio>
#include <string>

int main(int argc, char** argv) {
  try {
    std::string().at(1);
  } catch (const std::out_of_range &e) {
    printf("(1) e.what is: %s\n", e.what());
  } catch (const std::exception &e) {
    printf("(2) e.what is: %s\n", e.what());
  }
}
```
Compiled like (emscripten:1.39.4): `emcc test.cpp -fexceptions -std=c++11 -s DISABLE_EXCEPTION_CATCHING=0 -o test.html`

Running the above code produces an `e.what()` that is just `basic_string`, which is next to useless. This seems to happen with all the stdlib generated exceptions that I can think of.
Is this a limitation of WASI? Does `-fexceptions` need to be passed down to libc++?

**Comment by VirtualTim** [comment]
Running the same code in GCC produces an e.what() of `basic_string::at: __n (which is 1) >= this->size() (which is 0)`.
[see here.](http://cpp.sh/93d2g)

**Comment by juj** [comment]
Hmm, I wonder if that might be just a bug of `std::string().at(1);` error? What if you explicitly throw a `new std::runtime_error("This is an error!");`? Does that give you the print?

**Comment by VirtualTim** [comment]
Throwing errors manually (exactly like you describe) returns the correct `what()`. I tried a couple of other things to get it to throw, and those also just returned `basic_string`.

**Comment by kripken** [comment]
> Does -fexceptions need to be passed down to libc++?

libc++ is built with that flag when exceptions are enabled, so that part should be ok.

It's possible this is just what libc++ does for what(). To verify, can build libc++ natively and see what happens there with g++ (that would compare the same stdlib++ with only the compiler changing).

**Comment by VirtualTim** [comment]
Huh, so turns out that [libc++ just returns "basic_string" for a handful of errors.](https://github.com/llvm-mirror/libcxx/blob/da6e915c73f231074dc88f8a952a8273da0ca06b/include/string#L609-L616) This is different form libstdc++ which actually returns meaningful information.

So this is entirely on libc++.
