### ISSUE TITLE
"npm install" step has suggestions

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10291]
Installing the tot now, I saw

```
$ ./emsdk install tot
Installing SDK 'sdk-releases-upstream-856799fec303eff03345476ca987adadeb09dd40-64bit'..
[..]
Done installing tool 'releases-upstream-856799fec303eff03345476ca987adadeb09dd40-64bit'.
up to date in 0.054s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.10.2 → 6.13.6       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.6   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Done installing SDK 'sdk-releases-upstream-856799fec303eff03345476ca987adadeb09dd40-64bit'.
```

Could we hide all npm output? Or is that too dangerous?

cc @juj @sbc100

**Comment by juj** [comment]
I wonder if that goes to stdout? I suppose npm should operate as usual, and print progress to stdout and errors to stderr? In that case we could just mute stdout in the subprocess spawn and let stderr items come through.

Another way might be to pipe both streams in and grep for the output contents of stdout and stderr, and print them if process return code was nonzero, or some special keywords were found in the output?

**Comment by kripken** [comment]
Another option might be to add `running npm install...` in our output, and `npm install succeeded` after, so it's clear what's going on?

**Comment by sbc100** [comment]
Interesting.. i can't repro this.  Does it happen when you run `npm install` again in the emscripten repo?

**Comment by kripken** [comment]
I don't see that message in the emscripten repo when I try now. Odd.


(Anyhow, I think the issue of either hiding of giving context for npm output is pretty general here.)
