### ISSUE TITLE
emscripten_pthread_attr_settransferredcanvases canvas name

### ISSUE THREAD

**Issue by malytomas** [emscripten-core/emscripten#10308]
Function `emscripten_webgl_create_context` takes the canvas name with `#` eg. `ctx = emscripten_webgl_create_context("#display", &attr);`.

Function `emscripten_set_mousedown_callback` and all other events take the name of the element with the `#` too.

This build option `-s OFFSCREENCANVASES_TO_PTHREAD='#display'` as well.

The `emscripten_pthread_attr_settransferredcanvases` is the only function that takes the name without the `#`. Would it be possible to make this consistent? Thanks.

**Comment by juj** [comment]
I believe this was fixed in https://github.com/emscripten-core/emscripten/commit/13733d364bd8d5448b628d0066300c778b7afa1c#diff-db41bea94577c2dd9b0eef0308b06cf9R661.

**Comment by malytomas** [comment]
I dont know how to exactly verify what version am I at.

<details>
  <summary>emsdk list</summary>
  
  $ ./emsdk list
  
  The *recommended* precompiled SDK download is 1.39.7 (9a89fff28cc6f75e17976fce1904b280e4beb25d).
  
  To install/activate it, use one of:
           latest                  [default (llvm) backend]
           latest-fastcomp         [legacy (fastcomp) backend]
  
  Those are equivalent to installing/activating the following:
           1.39.7
           1.39.7-fastcomp
  
  All recent (non-legacy) installable versions are:
           1.39.7
           1.39.6
           1.39.5
           1.39.4
           1.39.3
           1.39.2
           1.39.1
           1.39.0
           1.38.48
           1.38.47
           1.38.46
           1.38.45
           1.38.44
           1.38.43
           1.38.42
           1.38.41
           1.38.40
           1.38.39
           1.38.38
           1.38.37
           1.38.36
           1.38.35
           1.38.34
           1.38.33
  
  The additional following precompiled SDKs are also available for download:
      *    sdk-releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit	INSTALLED
      *    sdk-releases-upstream-30ea217f8451d0fa45a918b12b997c0b870d541a-64bit	INSTALLED
           sdk-releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit
           sdk-releases-fastcomp-30ea217f8451d0fa45a918b12b997c0b870d541a-64bit
           sdk-fastcomp-1.38.30-64bit
           sdk-fastcomp-1.38.31-64bit
  
  The following SDKs can be compiled from source:
           sdk-upstream-master-64bit
           sdk-fastcomp-master-32bit
           sdk-fastcomp-master-64bit
           sdk-fastcomp-tag-1.38.30-64bit
           sdk-fastcomp-tag-1.38.31-64bit
  
  The following precompiled tool packages are available for download:
      (*)    releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit	INSTALLED
      (*)    releases-upstream-30ea217f8451d0fa45a918b12b997c0b870d541a-64bit	INSTALLED
             releases-fastcomp-3b8cff670e9233a6623563add831647e8689a86b-64bit
             releases-fastcomp-30ea217f8451d0fa45a918b12b997c0b870d541a-64bit
             fastcomp-clang-e1.38.30-64bit
             fastcomp-clang-e1.38.31-64bit
             node-4.1.1-64bit         
             node-8.9.1-64bit         
      (*)    node-12.9.1-64bit        	INSTALLED
             emscripten-1.38.30       
             emscripten-1.38.31       
  
  The following tools can be compiled from source:
             llvm-git-master-32bit    
             llvm-git-master-64bit    
             clang-tag-e1.38.30-32bit 
             clang-tag-e1.38.31-32bit 
             fastcomp-clang-tag-e1.38.30-64bit
             fastcomp-clang-tag-e1.38.31-64bit
             fastcomp-clang-master-32bit
             fastcomp-clang-master-64bit
             emscripten-tag-1.38.30-32bit
             emscripten-tag-1.38.31-32bit
             emscripten-tag-1.38.30-64bit
             emscripten-tag-1.38.31-64bit
             binaryen-tag-1.38.30-32bit
             binaryen-tag-1.38.31-32bit
             binaryen-tag-1.38.30-64bit
             binaryen-tag-1.38.31-64bit
             emscripten-master-32bit  
             emscripten-master-64bit  
             binaryen-master-32bit    
             binaryen-master-64bit    
  
  Items marked with * are activated for the current user.
  Items marked with (*) are selected for use, but your current shell environment is not configured to use them. Type "source ./emsdk_env.sh" to set up your current shell to use them.
  
  To access the historical archived versions, type 'emsdk list --old'
  
  Run "git pull" followed by "./emsdk update-tags" to pull in the latest list.
  
</details>

But with the current _latest_ I still get an exception that it cannot transfer the canvas.

<details>
  <summary>exception</summary>
  
  vts-browser-wasm-canvas.js:2736 2020-02-05 14:27:36 I3 [42(0)]: Create rendering thread {log.cpp:log():94}
  printChar @ vts-browser-wasm-canvas.js:2736
  _fd_write @ vts-browser-wasm-canvas.js:7695
  _emscripten_receive_on_main_thread_js @ vts-browser-wasm-canvas.js:6087
  _do_call
  emscripten_current_thread_process_queued_calls
  emscripten_main_thread_process_queued_calls
  Module._emscripten_main_thread_process_queued_calls @ vts-browser-wasm-canvas.js:9221
  worker.onmessage @ vts-browser-wasm-canvas.js:2268
  vts-browser-wasm-canvas.js:8011 pthread_create: transferredCanvasNames="#display"
  vts-browser-wasm-canvas.js:8011 pthread_create: transferredCanvasNames="#display"
  vts-browser-wasm-canvas.js:8039 pthread_create: cannot transfer canvas with ID "#display" to thread, since the current thread does not have control over it!
  _pthread_create @ vts-browser-wasm-canvas.js:8039
  _do_call
  emscripten_current_thread_process_queued_calls
  emscripten_main_thread_process_queued_calls
  Module._emscripten_main_thread_process_queued_calls @ vts-browser-wasm-canvas.js:9221
  worker.onmessage @ vts-browser-wasm-canvas.js:2268
  vts-browser-wasm-canvas.js:1624 Pthread aborting at Error
      at abort (http://tmw:6931/vts-browser-wasm-canvas.js:1624:69)
      at ___assert_fail (http://tmw:6931/vts-browser-wasm-canvas.js:2382:2)
      at dynCall_viiii (wasm-function[44082]:0x926e9e)
      at Module.dynCall_viiii (http://tmw:6931/vts-browser-wasm-canvas.js:9347:40)
      at invoke_viiii (http://tmw:6931/vts-browser-wasm-canvas.js:9958:3)
      at createRenderThread() (wasm-function[1253]:0x39604)
      at main (wasm-function[756]:0x24a24)
      at Module._main (http://tmw:6931/vts-browser-wasm-canvas.js:9119:31)
      at ___call_main (http://tmw:6931/vts-browser-wasm-canvas.js:2386:19)
      at __emscripten_thread_main (wasm-function[44061]:0x925e1c)
      at dynCall_ii (wasm-function[44103]:0x927020)
      at Object.Module.dynCall_ii (http://tmw:6931/vts-browser-wasm-canvas.js:9473:37)
      at onmessage (http://tmw:6931/vts-browser-wasm-canvas.worker.js:129:42)
  
</details>


Using ```emscripten_pthread_attr_settransferredcanvases(&attr, "display");``` instead works well.


Am I using an old version of emscripten or is the canvas transfer still broken?

Thanks

**Comment by juj** [comment]
Hmm, looks like there could still be a bug there indeed.

**Comment by kripken** [comment]
@malytomas to check what version you are on, do `emcc --version`

**Comment by malytomas** [comment]
> @malytomas to check what version you are on, do `emcc --version`

Thanks, I have updated my previous comment accordingly.

**Comment by TURIING** [comment]
I ran into the same problem, and after canvases using `#` in `emscripten_pthread_attr_settransferredases()`, "could not find canvas with id "#canvas" to transfer to thread!" will appear. When you remove it, it's normal
