### ISSUE TITLE
FS.mount, WORKERFS is undefined

### ISSUE THREAD

**Issue by tnikolai2** [emscripten-core/emscripten#10317]
v1.39.1: 10/30/2019
Only MEMFS is included by default, others (NODEFS, IDBFS, WORKERFS, PROXYFS) must be linked in explicitly, using -lnodefs.js, -lidbfs.js', -lworkerfs.js, -lproxyfs.js. See #9645

I use  -lworkerfs.js, all work. But if use optimization -O3 (without -g), FS.mount, WORKERFS is undefined.  I try -s EXTRA_EXPORTED_RUNTIME_METHODS, but not help.

**Comment by kripken** [comment]
Do you have a testcase showing the issue? I tried adding `-O3` to `browser.test_fs_workerfs_read` in our test suite, and it still passes, so it must be something more specific to your code.

**Comment by tnikolai2** [comment]
I found, this prroblem happens when I add --closure 1 . But it reduces resulting .js size from 99kb to 53kb.

To fix this I add --post-js file with:
```
Module['ensureString']=ensureString;
Module['WORKERFS']=WORKERFS;
FS['mount']=FS.mount
FS['unmount']=FS.unmount
```

**Comment by kripken** [comment]
Oh, that is expected, yes. With closure you must export things using a string name, or otherwise closure will minify them. Exporting them that way should work, it might also be possible to do it with EXPORTED_RUNTIME_METHODS but I'm not sure.

**Comment by tnikolai2** [comment]
EXPORTED_RUNTIME_METHODS not work with ensureString
but with stringToUTF8 work

**Comment by kripken** [comment]
Thanks @tnikolai2 , it does look like that's a bug. I opened #10368 to fix it now, if you can please check that resolves things for you.
