### ISSUE TITLE
Proxy ccall from javascript/DOM thread into the PROXY_TO_PTHREAD thread

### ISSUE THREAD

**Issue by malytomas** [emscripten-core/emscripten#10310]
I use PROXY_TO_PTHREAD which makes a separate thread in which my main function is called.

When I want to manipulate the DOM from this thread, I use a functions like these:
```c++
// this function is executed in the DOM thread
extern "C" void setHtmlImpl(const char *id, char *str)
{
    EM_ASM({
        document.getElementById(UTF8ToString($0)).innerHTML = UTF8ToString($1)
    }, id, str);
    std::free(str);
}

// this function is called in the PROXY_TO_PTHREAD thread
void setHtml(const char *id, const std::string &value)
{
    char *str = (char*)std::malloc(value.length() + 1);
    std::strcpy(str, value.c_str());
    emscripten_async_run_in_main_runtime_thread(
                EM_FUNC_SIG_VII, &setHtmlImpl, id, str);
}
```

It is slightly inconvenient (especially the memory management), but is doable.

However, I also want to do ccall from the JS/DOM thread into the PROXY_TO_PTHREAD thread.
I found `emscripten_async_queue_on_thread`, but I dont have access to the thread_id of the PROXY_TO_PTHREAD thread. I suggest to add a function `pthread_t emscripten_proxy_to_pthread_thread_id(void);` or similar.

Alternatively, have I missed some other/easier way to do these kind of things?

Thanks.

**Comment by juj** [comment]
Try [MAIN_THREAD_EM_ASM](https://emscripten.org/docs/api_reference/emscripten.h.html?highlight=main_thread_em_asm#c.MAIN_THREAD_EM_ASM0 instead of EM_ASM. Or better yet, a --js-library function with a `xxx__proxy: 'sync'` semantics applied to it.

**Comment by malytomas** [comment]
I forgot to mention these. Unfortunately, the MAIN_THREAD_EM_ASM is synchronous (blocking).
The asynchronous MAIN_THREAD_ASYNC_EM_ASM again requires manual management of memory. It would also require to ccall std::free from the javascript code.
Is there some other mechanism to free the memory after the function has ended in the main thread?

What about the other way? As of now I found a workaround, I call pthread_self() at the beginning of my main and store it in a global variable.
