### ISSUE TITLE
Debug flags (-g in particular) and DWARF with the upstream backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10325]
We've added a `-gforce_dwarf` flag for now, which makes us emit full DWARF in object files and preserve them during link. The reason we did this is that DWARF can be very large, and also binaryen changes would invalidate it so it wasn't correct anyhow. (For the size issue, we made `-g` only emit debug line info, which is then used for a source map.)

Recently Binaryen's DWARF support has improved and it should be updating it correctly in many cases - everything but certain optimizations that significantly change the structure of the code And browser devtools have DWARF support in progress, so we should start to plan for proper support, without `-gforce_dwarf`.

One possible approach is:

 * Make `-g` during compile emit full DWARF (instead of just debug line).
 * Make `-g` during link preserve DWARF through all binaryen operations and into the final output.
 * Make `-g` during link disable binaryen optimizations that are known to not yet handle DWARF properly. As we improve binaryen's DWARF support we can add more optimizations.

This would be a noticeable change for people using `-g` during compile, as it would add DWARF to those files and increase their size. If they link without `-g` the DWARF would be removed, but leaving an unnecessary `-g` at compile might lead to wasted work that way, and slower builds unless it is fixed. We should document this if we make this change.

This would be a noticeable change for people using the upstream backend and `-g` during link, as now the file would have DWARF, which can be large. For someone that doesn't want DWARF but does want a debug build - in the sense of an "emscripten debug build", so the JS isn't minified, function names are preserved, etc. - the `--profiling` option would probably be what they want anyhow, and that will still work (but we should document it clearly in the changelog).

Disabling some binaryen optimizations might also be noticeable, but hopefully not much: The source files can still be optimized by clang/llvm, so this wouldn't be a "debug build" - it could be an optimized build with debug info, just with fewer binaryen optimizations. Those typically reduce code size by 20% or so, so at worst we'd be losing that amount (but not be multiple times bigger like a build without any opts would be), and hopefully it would be much less than that 20% (as many opts do work fine, and we would not disable them). There may also be a slight slowdown here, but binaryen's speedup is smaller than the code size benefit usually, so that's even less of a concern.

Overall that seems ok to me for someone debugging locally - it will run at almost full speed and have almost the optimal size, but will also have DWARF and all the debugging capabilities they want. We may also want to think about people using DWARF for things like crash dumps from production builds, for which a 20% size increase is bad, and that's why as mentioned earlier I think we can add more optimizations over time and get most or all of that back.

In theory someone linking with `-O3 -g` and shipping that to production unintentionally - so the `-g` is a mistake - would get a larger build, as it contains DWARF + fewer binaryen opts. Hopefully a mistake like this is rare, but the mistake would get much costlier after this proposed change, so we should document it carefully.

An alternative to the above proposal is to not emit DWARF by default in `-g`, but do something like we did with source maps: only do it in `-g4` or some other special flag, so it's less likely to happen by mistake. The downside there is that `-g4` is nonstandard, and given how much closer the upstream backend is to normal compiler practices, I think it would be better to handle DWARF in the same way as native compilers do, or as close as we can.

Thoughts?

**Comment by sbc100** [comment]
I wouldn't worry about the compile time cost of `-g`.   Anyone passing that flag should expect such a cost, no?

As for dropping some optimizations with `-g` at link time, I think it sounds reasonable.  Is it common to pass `-g` at link time?  I don't think it does anything in a normal toolchain.   Normally `-g` is not supposed to effect code, so perhaps we would a warning of some kind if we do that?

**Comment by kripken** [comment]
> Normally -g is not supposed to effect code, so perhaps we would a warning of some kind if we do that?

Normally it has no effect, correct. In emscripten though it's affected the debuggability of the build, mostly in affecting JS generation, and whether source maps are emitted. I'm proposing here that it also control whether DWARF is emitted.

**Comment by sbc100** [comment]
Right but aren't you also proposing that it changes the optimizations that get run by binaryen?

**Comment by kripken** [comment]
Yes, that too. But I'm saying that in this proposal we shouldn't warn on `-g` because it's a valid flag (which I understood you to be suggesting before).

**Comment by sbc100** [comment]
I'm suggesting a warning such as:

`warning: since drawf support in binaryen is still a work in progress the `-g` flag can limit/change the optimization run on the final binary`

**Comment by kripken** [comment]
Oh, sorry, I wasn't clear before: DWARF is no longer a work in progress in this proposal :smile: After the last few days, we should be updating DWARF properly, and I'm not aware of any issues (but I'm sure bugs will be found and filed).
