### ISSUE TITLE
LLVM version appears incorrect (seeing "11.0", expected "10.0")

### ISSUE THREAD

**Issue by osen** [emscripten-core/emscripten#10326]
Please find attached a trivial patch that silences this warning:
[wasm_bump.txt](https://github.com/emscripten-core/emscripten/files/4135804/wasm_bump.txt)

I am assuming I needed to do this because I am using the very latest build of llvm/clang?
Attached is my entire automated build script to build an offline package (I am not a fan of the emsdk online-dependent approach).
[embuild.txt](https://github.com/emscripten-core/emscripten/files/4135815/embuild.txt)

**Comment by sbc100** [comment]
We recently switched from incoming to master as the active emscripten branch: https://github.com/emscripten-core/emscripten/issues/10067

So your build script should point at master rather than incoming.

As the final part of this change I'm planning on renaming the incoming branch so that this will become more obvious.

**Comment by sbc100** [comment]
BTW emsdk can produce a build completely from source using `./emsdk install sdk-upstream-master-64bit`.  This will checkout everything from git and build from source just like your script.

**Comment by osen** [comment]
Ah right, I missed that. Thank you. I will change my build script. I will also need to update my OpenBSD port Makefile (https://github.com/osen/openbsd_emscripten). This has gotten seriously out of date! ;)

>
> This will checkout everything from git and build from source just like your script
>

I could be wrong but where my script differs is that mine only grabs from online repos if source tarballs does not exist in the folder. So mine can build and deploy to multiple offline workstations.

Thanks for your info. I will close this issue.

**Comment by TJKoury** [comment]
Still seeing this error message using `master`.

**Comment by sbc100** [comment]
What version of emscripten do you have?   (What does emcc --version say).   It must be an older version if it expects llvm 10.

**Comment by TJKoury** [comment]
`emcc (Emscripten gcc/clang-like replacement) 1.39.7 (commit 7b2d3d0a3fc0d5238d5dee0371de7cc24d3542a7)`

**Comment by sbc100** [comment]
7b2d3d0a3fc0d5238d5dee0371de7cc24d3542a7 is basically ToT as of right now and it certainly expects llvm 11.

There must be some confusion here.   Can you post the fill failing command line with EMCC_DEBUG=1 set?   

Are you sure you not seeing the oposite error?  (expected 11 but saw 10?)  If so that you need to update you llvm version.

**Comment by TJKoury** [comment]
```
$ emcc
shared:WARNING: LLVM version appears incorrect (seeing "10.0", expected "11.0")
shared:INFO: (Emscripten: settings file has changed, clearing cache)
shared:INFO: (Emscripten: Running sanity checks)
emcc:WARNING: no input files

$ clang --version
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 890d5e2dd232f43842d8a9025e639027946d81f4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin```

**Comment by TJKoury** [comment]
So it does look like it expects LLVM 11, and I have LLVM installed in the correct location, and LLVM is the right version, but it does not see it that way.

**Comment by sbc100** [comment]
You need to configure emscripten to point to the correct clang version.   Normally this is don't by using `emsdk` or my editing `$HOME/.emscripten`.

**Comment by Carnaux** [comment]
I'm getting the same error 

```
stderr: shared:WARNING: LLVM version appears incorrect (seeing "11.0", expected "10.0")
shared:ERROR: '/usr/local/bin/wasm-emscripten-finalize --detect-features --global-base=1024 --check-stack-overflow /tmp/emscripten_temp_A06BOV/tmp339lQj.wasm -o /tmp/emscripten_temp_A06BOV/tmp339lQj.wasm.o.wasm' failed: [Errno 2] No such file or directory
FAIL: Compilation failed!
```

emcc --version:
emcc (Emscripten gcc/clang-like replacement) 1.39.6 (commit 6bfbe2a7da68e650054af2d272d2b79307a6ad72)

**Comment by sbc100** [comment]
The real error here is that `/usr/local/bin/wasm-emscripten-finalize` does not exist.

How are you installing emscripten / binaryen / llvm.  These three packages all need to be installed and kept in sync.

1.39.6 was that last release of emscripten that used LLVM 10.   1.39.7 expected LLVM 11.

I would recommend using emsdk to install to avoid all these issues.

**Comment by sbc100** [comment]
I misread the original issue by the way.   If you want to continue to use 1.39.7 you need to *downgrade* LLVM to version 10, or at least point emscripten at copy of LLVM 10.

**Comment by Carnaux** [comment]
> How are you installing emscripten / binaryen / llvm

I followed the documentation guide for the emscripten installation. And for some reason, cloning the git repo only installed 1.39.6.

**Comment by sbc100** [comment]
When did you clone?  1.39.6 is from back in January.   

 Are you sure you running the version you cloned?  What does `which emcc` say?

**Comment by Carnaux** [comment]
Sorry, my error, I'm running on WSL, and `which emcc` is pointing to the Windows installation, that's probably the issue.
