### ISSUE TITLE
-2147483648 incorrectly triggers literal too large warning

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#10336]
If you use `INT32_C(-2147483648)` in C++ it generates a warning:

```c++
#include <stdint.h>
#include <inttypes.h>
#include <limits.h>
#include <stdio.h>

static_assert(-2147483648LL == INT32_MIN, "INT32_MIN should be -2147483648");

int main(void) {
  const int32_t
    foo = INT32_C(-2147483648),
    bar = INT32_MIN, /* (-1-0x7fffffff) */
    baz = INT32_C(1) << 31;

  printf("%" PRId32 "\n", foo);
  printf("%" PRId32 "\n", bar);
  printf("%" PRId32 "\n", baz);

  return 0;
}
```

```
i32min.cc:10:20: warning: integer literal is too large to be represented in type 'long' and is subject to undefined behavior under C++98, interpreting as 'unsigned long'; this literal will have type 'long long' in C++11 onwards [-Wc++11-compat]
    foo = INT32_C(-2147483648),
                   ^
```

Off-by-one error on the warning, maybe?  It would be valid for -2147483649, and isn't triggered by -2147483647.  Note that if you remove the trailing LL in the static assertion that will generate a warning, too.

**Comment by sbc100** [comment]
I don't think this issue it emscripten specific.  I see warning from both g++ and clang++ if I also pass `-m32` to build in 32-bit mode like emscripten.

**Comment by sbc100** [comment]
I think this might be because the compiler evaluates 2147483648L first then negates it with the unary `-`.   

I see code in the llvm headers that leads me to think this is true:

```
#define INT40_MIN         (-INT40_C(549755813887)-1)                            
```

**Comment by nemequ** [comment]
> I don't think this issue it emscripten specific. I see warning from both g++ and clang++ if I also pass `-m32` to build in 32-bit mode like emscripten.

I don't.  Here it is on Compiler Explorer: https://godbolt.org/z/zJqmWs

clang gets a bit chatty with -Weverything, but not about `INT32_C(-2147483648)`.

**Comment by sbc100** [comment]
Sorry I think you also need to use a version of C++ pre-11.   The warnings all go away with `-std=c++11`  which I guess is the default in compiler explorer?

If you add `-std=c++03` (the emscripten default) you should should get the warnings from clang++ and g++.

**Comment by nemequ** [comment]
You're right, sorry for the noise :(

I had always thought the sign was part of the constant, but looking at the C17 spec §6.4.4.1, that's not so.

For some reason I hadn't made the connection to clang and gcc defaulting to newer versions of C++, so when I noticed that `INT32_MIN` was `(-1-0x7fffffff)` and had the same thought I just dismissed it.
