### ISSUE TITLE
Unable to build formerly working project -- not sourced? CXX compiler is c++ not emcc or em++

### ISSUE THREAD

**Issue by SergiusPaulus** [emscripten-core/emscripten#10332]
I had a fairly simple emscripten project working couple of months ago on OSX. Now I cannot get it to build.  In the Terminal I would build by simply:

mkdir build
cd build
cmake ..
make

For my main cpp file I am getting:

`fatal error: 'emscripten/bind.h' file not found
`
but when using make with VERBOSE=1 I noticed working the c++ compiler is used, and I am pretty sure it was either emcc or em++ before. When I run cmake .. part of the output is

```
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works

```
I *think* I have sourced my Terminal session properly.  I went into the emsdk directory and ran source emsdk_env.sh and it generated:

```
Adding directories to PATH:
PATH += /Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk
PATH += /Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk/node/12.9.1_64bit/bin

Setting environment variables:
EMSDK = /Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk
EM_CONFIG = /Users/cjohnson/.emscripten
EMSDK_NODE = /Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk/node/12.9.1_64bit/bin/node
```

but I don't recall doing that when I had this project going. Still, I discovered am supposed to source every new session so I did.

As mentioned, this all worked flawlessly earlier.

**Comment by SergiusPaulus** [comment]
... and echo $PATH yields

/Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk:/Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk/fastcomp/emscripten:/Users/cjohnson/Documents/OSX_Projects/AILBrowserDev/emscripten_project/emsdk/node/12.9.1_64bit/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by brion** [comment]
You should use the 'emconfigure' and 'emmake' tools to wrap the invocations of 'cmake' an 'make', something like this:

```
mkdir build
cd build
emconfigure cmake ..
emmake make -j4
```

This will set additional environment variables for CC, CXX etc appropriately to point at emcc and em++ and the linker etc tools for emscripten.

**Comment by SergiusPaulus** [comment]
@brion, thank you!  It now builds fine when I run exactly what you proposed.  Any idea why it worked before without using emconfigure and emmake?  Also, what is -j4 and is it necessary here?

**Comment by brion** [comment]
Most likely you either did use them before, or were manually setting a bunch of environment variables in some other way that didn't get documented in your build setup. There's pretty much no way it would have ever worked otherwise.

The `-j` option to `make` is for parallel builds. Usually you want some form of it because it uses your multiple CPU cores rather than letting them sit idle. :)

**Comment by SergiusPaulus** [comment]
Wowza! on the -j option.  Will keep using that.
