### ISSUE TITLE
DWARF: c/cpp source files are expected locally

### ISSUE THREAD

**Issue by TuckWa** [emscripten-core/emscripten#10344]
When building with -gforce_dwarf and attempting to debug in Chrome dev edition (81.0.4040.5), Chrome seems to think that my source files are local when in reality they are up on my server (emrun).

![image](https://user-images.githubusercontent.com/49871360/73664411-58000f80-466d-11ea-8a42-bf1ac37436ff.png)

Is this just not supported right now but will in future, or should I only be debugging locally?

**Comment by kripken** [comment]
I'm not entirely sure what the plan here is. cc @RReverser @dschuff  Meanwhile the `--source-map-base` option may help here, but I'm not sure if we plan to replace that with a more DWARF-specific flag later.

(I've only been testing with local files for now.)

**Comment by RReverser** [comment]
I don't think `--source-map-base` is going to help here. For now only local debugging is supported indeed, as absolute paths is what compilers assume and encode in debug info.

In the future we might add support for URLs produced by `-fdebug-prefix-map=...` in Clang or an equivalent option in a different compiler, but there are some challenges with correctly recognising URLs in places that normally expect paths, and for now that's not the highest priority feature on the list of things we want to improve or support in WebAssembly debugging.

**Comment by RReverser** [comment]
Yeah I think this can be closed as stale, as we have support for path overrides in the new DWARF extension.

**Comment by Heath123** [comment]
> Yeah I think this can be closed as stale, as we have support for path overrides in the new DWARF extension.

I can't find any info on this:
![image](https://user-images.githubusercontent.com/13787163/144286393-7db8e3f0-a873-43da-bfbe-bba55523b641.png)
How do I do this?

**Comment by RReverser** [comment]
Check out this section: https://developer.chrome.com/blog/wasm-debugging-2020/#path-mapping

**Comment by Heath123** [comment]
Thanks, I did see that, and it works, but that involves doing it for every URL and it would be nicer to embed it in the debug info if possible. I tried using a hex editor to change the path in the wasm file but it's still marked as a file URL so I end up with the browser trying to access `file://https://website.com/...`

**Comment by Heath123** [comment]
Oh, I messed this part
![image](https://user-images.githubusercontent.com/13787163/144309634-75cc7003-0380-43b3-8ef8-1891c203dc6a.png)
I'll try that

**Comment by RReverser** [comment]
> Thanks, I did see that, and it works, but that involves doing it for every URL

What do you mean? No, not every URL, only a prefix. As the example shows, you can remap e.g. `/mnt/c/src/my_project` to `C:\src\my_project` and it will remap all files under that folder.

**Comment by RReverser** [comment]
> and it would be nicer to embed it in the debug info if possible

That's possible too, via Clang's [`-fdebug-prefix-map`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fdebug-prefix-map).

Personally I'd avoid it though, because project recompilation is much slower than changing paths in an extension on the browser side.

**Comment by Heath123** [comment]
> > and it would be nicer to embed it in the debug info if possible
> 
> That's possible too, via Clang's [`-fdebug-prefix-map`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fdebug-prefix-map).
> 
> Personally I'd avoid it though, because project recompilation is much slower than changing paths in an extension on the browser side.

I tried `emcc -g main.c -fdebug-prefix-map=$PWD=https://emscripten-test.heathmitchell1.repl.co/ -o index.html` but I get `Could not load content for file://emscripten-test.heathmitchell1.repl.co/main.c (HTTP error: status code 404, net::ERR_INVALID_URL)`, just like when I hex edited the file.

![image](https://user-images.githubusercontent.com/13787163/144312811-057a1c3c-6d4c-4c29-ba92-3b36bbc842c3.png)

For context, I'm trying to make some sort of template for https://replit.com/, which creates a new URL for each project. So the URL will be known at compile time, but it would be a pain to go into the devtools settings every time you want to create a new project to test something quickly

**Comment by Heath123** [comment]
I found a workaround

**Comment by Heath123** [comment]
The workaround is: If I compile with `fdebug-prefix-map=$PWD=/https/emscripten-test.heathmitchell1.repl.co/`, then add an override like this:
![image](https://user-images.githubusercontent.com/13787163/144316400-7ee9b831-c75f-4cda-a60e-4947a53a6757.png)
then everything works fine and I should only have to set that one override for any URL
