### ISSUE TITLE
machine type must be wasm32

### ISSUE THREAD

**Issue by Y0QIN** [emscripten-core/emscripten#10342]
I update my emsdk to 1.39.6 on windows 64bit
and try to compile my code then occour following errors:
![企业微信截图_15807209926638](https://user-images.githubusercontent.com/20675936/73639788-00cb6080-46a8-11ea-8f20-5594515b6e94.png)

**Comment by sbc100** [comment]
I imagine you need to do a full clean build and that those object files were build with the old fastcomp backend.

**Comment by Y0QIN** [comment]
@sbc100 you mean that I should rebuild my .a files by version 1.39.6 ?

**Comment by sbc100** [comment]
Yes.    All your object files and all your libraries need to be rebuilt.

**Comment by Y0QIN** [comment]
thanks,I will try to rebuilt and then reply you

**Comment by Y0QIN** [comment]
@sbc100  I rebuilt and success,thanks

**Comment by sbc100** [comment]
Great!
