### ISSUE TITLE
machine type must be wasm32 

### ISSUE THREAD

**Issue by Y0QIN** [emscripten-core/emscripten#10341]
I update my emsdk to 1.39.6 on windows 64bit
and try to compile my code then occour following errors:
![企业微信截图_15807209926638](https://user-images.githubusercontent.com/20675936/73639788-00cb6080-46a8-11ea-8f20-5594515b6e94.png)

**Comment by VirtualTim** [comment]
Closing as a dupe of #10342.
@kripken it may be good just to delete this.
