### ISSUE TITLE
Compiling without exceptions is not possible on anymore on 1.38+

### ISSUE THREAD

**Issue by kunitoki** [emscripten-core/emscripten#10362]
Compiling my code without exceptions with these flags:
```
CMAKE_CXX_FLAGS:  -std=c++11 -s TOTAL_MEMORY=268435456 -s ALLOW_MEMORY_GROWTH=1 -s WASM=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s FORCE_FILESYSTEM=1 -s NODERAWFS=1 -fno-exceptions -s DISABLE_EXCEPTION_CATCHING=1
```

was working correctly (and passing the testsuite) on 1.37, but on 1.38 at the linking stage i get:

```
cache:INFO: generating system library: libc++-noexcept.a... (this will be cached in "/kunitoki/.emscripten_cache/asmjs/libc++-noexcept.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.bc... (this will be cached in "/kunitoki/.emscripten_cache/asmjs/libc++abi-noexcept.bc" for subsequent builds)
cache:INFO:  - ok
error: DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), which means no C++ exception throwing support code is linked in, but such support is required by symbol __cxa_allocate_exception. Either do not set DISABLE_EXCEPTION_THROWING (if you do want exception throwing) or compile all source files with -fno-except (so that no exceptions support code is required); also make sure DISABLE_EXCEPTION_CATCHING is set to the right value - if you want exceptions, it should be off, and vice versa.
Error: Aborting compilation due to previous errors
shared:ERROR: '/emsdk/node/12.9.1_64bit/bin/node /emsdk/fastcomp/emscripten/src/compiler.js /tmp/tmpyktIS5.txt /emsdk/fastcomp/emscripten/src/library_pthread_stub.js' failed (1)
```

any idea on how to past the issue ?

**Comment by sbc100** [comment]
It looks like some part of your program if referencing the `__cxa_allocate_exception` symbol.  Are you sure all your sources were built with `-fno-exceptions`? 

To find out where the reference if coming from you could try using `llvm-nm` of your object files or passing `-mllvm -debug-only=lld` to wasm-ld.   What I normally do is run with the EMCC_DEBUG=1 when copy and paste the linker command line and add the flags directly on the command line.

You could also try passing `--trace-symbol=__cxa_allocate_exception` to the linker.

if you have a smaller repro case for this I'm be interested to replicate it.

**Comment by kunitoki** [comment]
yeah true, it might be gtest / gmock which might override flags

thanks for the hints !

**Comment by kunitoki** [comment]
it was indeed that issue, made also gtest to compile without exceptions and now everything runs nicely !
