### ISSUE TITLE
emmalloc assertion error: region_is_in_use

### ISSUE THREAD

**Issue by kgdev** [emscripten-core/emscripten#10363]
Using the latest upstream of emsdk, I got this exception. It seems like a bug in the recent update of emmalloc? sbrk is also used by bdwgc.

![image](https://user-images.githubusercontent.com/6348456/73840848-209f8780-4854-11ea-9462-f8613add0ac4.png)

**Comment by kgdev** [comment]
@juj

**Comment by juj** [comment]
This can happen if there was memory overrun or underrun that occurred, or if there was an attempted double free.

You can try to debug with e.g.

```diff
diff --git a/system/lib/emmalloc.cpp b/system/lib/emmalloc.cpp
index 883b195cd..10aea64ff 100644
--- a/system/lib/emmalloc.cpp
+++ b/system/lib/emmalloc.cpp
@@ -905,6 +905,9 @@ void emmalloc_free(void *ptr)
   MALLOC_ACQUIRE();

   uint32_t size = region->size;
+#ifdef EMMALLOC_DEBUG_LOG
+  MAIN_THREAD_ASYNC_EM_ASM(console.log('regionSize:'+$0.toString(16)+', regionSizeAtCeiling:'+$1.toString(16)+')'), size, region_ceiling_size(region));
+#endif
   assert(size >= sizeof(Region));
   assert(region_is_in_use(region));
```

**Comment by kgdev** [comment]
Thanks, I will have a try.

**Comment by kgdev** [comment]
free(ptr=2ec9a48)
regionSize:2078, regionSizeAtCeiling:-b281) which is a nagative value?

**Comment by kgdev** [comment]
So that means it's potentially corrupted?

**Comment by kgdev** [comment]
![image](https://user-images.githubusercontent.com/6348456/73846372-644bbe80-485f-11ea-80c3-8e376b2f314d.png)

**Comment by kgdev** [comment]
Is it because sbrk is also used by others?

**Comment by juj** [comment]
> regionSize:2078, regionSizeAtCeiling:-b281) which is a nagative value?

This suggests a memory corruption somewhere.`regionSizeAtCeiling` is expected to be either 2078 if the region is in use, or -2079 if the region is free. Other values mean that either `regionSize` or `regionSizeAtCeiling` is corrupted.

Sbrk() should be safe to be used by others.

Can you post the full page with emmalloc debug log? And/or the full log?

**Comment by kgdev** [comment]
Thanks. I will try to dig more and then post something if needed.

**Comment by kgdev** [comment]
[10.86.98.112-1580920484807.log](https://github.com/emscripten-core/emscripten/files/4160782/10.86.98.112-1580920484807.log)

Please have a check

**Comment by kgdev** [comment]
[console-export-2020-2-6_0-40-15.txt](https://github.com/emscripten-core/emscripten/files/4160810/console-export-2020-2-6_0-40-15.txt)

This is in Firefox
