### ISSUE TITLE
BINARYEN_TRAP_MODE is not supported by the LLVM wasm backend

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#10365]
Is there a way to get the silent clamping behavior for trapping Wasm instructions to LLVM wasm backend? I.e. `-s BINARYEN_TRAP_MODE=clamp`?

**Comment by sbc100** [comment]
Hmm, I thought that the wasm backend only supports this mode and never traps.   What behaviour are you seeing?

**Comment by dschuff** [comment]
There's also `-mnontrapping-fptoint` which enables the nontrapping float->int conversion instructions. I know these are supported in Chrome and firefox, not sure about Safari.

**Comment by sbc100** [comment]
Right but IIRC the observable behavior is the same with and without `-mnontrapping-fptoint` right?  And the behavior should match fastcomp's `BINARYEN_TRAP_MODE=clamp`, right?

**Comment by juj** [comment]
Oh indeed, you are right. Wasm backend is always `-s BINARYEN_TRAP_MODE=clamp` (but does not allow one to specify `-s BINARYEN_TRAP_MODE=clamp`)

With fastcomp backend we generally have users choose between either `allow` and `clamp`. Typically for development builds people choose `allow` so that they can catch bugs, and for release builds, they choose `clamp` to get stable execution even in the face of unknown garbage data.

It would be great of LLVM wasm backend supported BINARYEN_TRAP_MODE with at least `clamp` and `allow` semantics like fastcomp used to.

I see that both backends generate the trapping instructions by default, which is great for compatibility and like we'd expect.

> There's also `-mnontrapping-fptoint` which enables the nontrapping float->int conversion instructions. I know these are supported in Chrome and firefox, not sure about Safari.

Now that we have the MIN_XXX_VERSION fields, it would be great to lean on those, and enable nontrapping instructions when the set of specified `MIN_XXX_VERSION` fields allows that. (but that is besides the request of this issue)

**Comment by juj** [comment]
> Right but IIRC the observable behavior is the same with and without `-mnontrapping-fptoint` right?

When you are actually executing, yeah, the behavior is the same. But the behavior is different with respect to browser compatibility.

> the behavior should match fastcomp's `BINARYEN_TRAP_MODE=clamp`

Yeah.

**Comment by sbc100** [comment]
I think adding a `BINARYEN_TRAP_MODE=allow` mode would probably involve a binaryen pass to remove checks the llvm inserts around trapping instructions.

I think this would be possible, bit I'm having trouble seeing why one would want that.  You say its to catch bugs but I'm not clear what kind of bugs you are talking about.  Are you talking about general floating point overflow bugs?  What are the mechanisms by which one would debug those in native toolchains, and why want to be different?   Is this something specifically related to JS and/or wasm2js doesn't apply to wasm-only builds maybe?

**Comment by juj** [comment]
> why one would want that.

It is to catch errors with undefined behavior in C&C++ standards.

>  What are the mechanisms by which one would debug those in native toolchains

In native toolchains one would use static analysis tools and/or Clang's udb sanitizer (https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)

**Comment by sbc100** [comment]
I would have thought we'd be better off investing in getting those ubsan working then, no?  Rather than trying to duplicate parts of it.  We do already have ubsan support in the llvm backend so maybe this is already covered?

**Comment by tlively** [comment]
Yes, UBSan already works with Emscripten.

**Comment by davlhd** [comment]
I am using 2.0.23 and I am getting this error: `Uncaught RuntimeError: float unrepresentable in integer range`. 

Shouldn't this be impossible when BINARYEN_TRAP_MODE=clamp is the default?

**Comment by kripken** [comment]
@davlhd That option no longer exists - you should get a warning from the compiler when you pass it. So it does not matter what value you provide it. But separate from that, yes, the LLVM wasm backend should always clamp, so that is strange. Can you provide a testcase, as it sounds like a possible bug?

**Comment by davlhd** [comment]
I am compiling zxing and I am scanning a scpecific barcode, thats when this is happening. 

Thats the report I am using: [https://github.com/nu-book/zxing-cpp](https://github.com/nu-book/zxing-cpp)
Is there any way I can debug this? Creating the examples repo would be very time consuming. 

I am trying to pass -mnontrapping-fptoint as this was mentioned as a fix but clang tells me this is an unknown flag: 
`clang-6.0: warning: argument unused during compilation: '-mnontrapping-fptoint'`

**Comment by sbc100** [comment]
The fact that you are seeing `clang-6.0` in the error message means you are probably using an ancient version of emscripten (perhaps fastcomp?).   I suggest upgrading if you can.

**Comment by davlhd** [comment]
Hello @sbc100 you are correct. I had the checkout of an older version hidden in my build script. I updated to the newest version and now its work. Thank you!
