### ISSUE TITLE
Setting clang -target x86_64-unknown-linux-gnu instead of  wasm32-unknown-emscripten

### ISSUE THREAD

**Issue by courteous** [emscripten-core/emscripten#10361]
I have a prepared a minimal Cmake "hello world" project 

[https://github.com/courteous/wasmELF.git](https://github.com/courteous/wasmELF.git)

I would like to cross compile this "hello world" to :

1) WebAssembly (wasm) binary module version 0x1 (MVP) 
2) ELF 64-bit LSB binary

for that reason i am trying to pass another "-target" to emscripten/clang i.e.
i.e.
`SET(TARGET x86_64-unknown-linux-gnu)`

the default one is "wasm32-unknown-emscripten" i.e.
`
emscripten/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten`

i do see that the included llc support the x86_64-unknown-linux-gnu target i.e. 

```
emscripten/emsdk/upstream/bin$ ./llc --version
LLVM (http://llvm.org/):
  LLVM version 11.0.0git
  Optimized build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64


```
What would be the right way to set this target so that emconfigure will understand that it i.e.

```
emconfigure cmake ../ -DCMAKE_BUILD_TYPE=Linux
make
```

will generate correct target flag ?

Here is the complete question on SO

[https://stackoverflow.com/questions/60060498/emscripten-clang-produce-elf-64-bit-executabel-and-wasm-binary-cross-compiler-ta](https://stackoverflow.com/questions/60060498/emscripten-clang-produce-elf-64-bit-executabel-and-wasm-binary-cross-compiler-ta)

**Comment by sbc100** [comment]
You can't use emcc or emmake with another target.  if you want to use x86_64-unknown-linux-gnu then you should probably just use your system compiler.   You may be able to use the version of clang that we include in emscripten for this purpose (because as you say we do include the x86 target there), but not via the emcc driver.

**Comment by courteous** [comment]
Hello Sam ,  many thanks for the clarification. The idea here was to not recompile the tree when i swtich from ELF to wasm tests and backwards.  i.e. once the LLVM bitcode is generated i wanted to generate a elf binary out of this. I will try to do that will another clang instance installed.I wanted to use the build in clang from emscripten since  i was afraid that installing another instance of clang will mess up some local variable.  Again thanks for the help.

**Comment by sbc100** [comment]
Sadly LLVM bitcode is not platform independent in that sense, so you can't produce as wasm file and and linux ELF file from the same bitcode file.   So you do need to fully re-compile I'm afraid.

**Comment by courteous** [comment]
Indeed that is not optimal, the problem is that most of the time people write test code,  in my case ( google test) and this code runs in ELF/DOS and then a compilation is made to wasm. However  to switch back and forth one needs to fully rebuild the tree and depending on the project that could really be painful. And do not get me wrong, I am grateful that we at least have this option, since webassembly brings  so much on the table. Maybe a feature request for the far future?

**Comment by sbc100** [comment]
Most build systems support multiple builds from the same source, so you should be able setup a different build directory for each target arch, then there is no need to clean the object files when switching.

**Comment by sbc100** [comment]
Making llvm bitcode compatible between architectures I'm afraid is outside the scope of emscripten or WebAssembly, it would be a (major) feature request for upstream llvm.
