### ISSUE TITLE
error: undefined symbol: __powisf2

### ISSUE THREAD

**Issue by diegocr** [emscripten-core/emscripten#10374]
Have just upgraded from 1.38.32 to latest 1.39.7 upstream[1] and facing the following compiler warnings/errors when compiling [ffmpeg.js](https://github.com/meganz/ffmpeg.js)

[1] 'sdk-releases-upstream-9a89fff28cc6f75e17976fce1904b280e4beb25d-64bit'

```
wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=72 expected=73
wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=73 expected=74
wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=73 expected=74
error: undefined symbol: __powisf2
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
shared:ERROR: 'C:/emsdk/node/12.9.1_64bit/bin/node.exe c:\emsdk\upstream\emscripten\src\compiler.js r:\temp\tmpjk2sjw.txt' failed (1)
make: *** [build/avcodec.js] Error 1
```

By using `-s ERROR_ON_UNDEFINED_SYMBOLS=0` it does compiles and the code seems to run fine** at first glance, so wondering what that's about and/or whether you guys may want to look into it.

(** runs fine provided the patch at https://github.com/emscripten-core/emscripten/pull/10373 is applied)

**Comment by sbc100** [comment]
The `__powisf2` issue looks like we need to update our copy of compiler-rt perhaps. 

The wasm-ld warnings are worth investigating too.  Another reason why we should really be building ffmpeg continuously somewhere I guess.

**Comment by sbc100** [comment]
I'm working on an update to compiler-rt.. after which I will look into adding any missing files. See #10380

**Comment by diegocr** [comment]
Awesome, thank you!
