### ISSUE TITLE
DISABLE_EXCEPTION_CATCHING=2 with EXCEPTION_CATCHING_WHITELIST seems not to be working in latest upstream backend

### ISSUE THREAD

**Issue by rohitsaini1995** [emscripten-core/emscripten#10371]
Hi All,

We made a update to 1.39.6 recently . Previously we were on 1.38.34 and using -s DISABLE_EXCEPTION_CATCHING=2 -s EXCEPTION_CATCHING_WHITELIST="@whitelist.txt", and it was working fine.
But in latest upstream it seems to be stopped working.

I wrote a small program to verify that, it is not working with this program as well.
```
#include <iostream>
#include "emscripten.h"
using namespace std;

extern "C"
void fun() {
   try {
      throw 10000;
   } catch(...) {
      cout<<"hello"<<endl;
   }
}
int main () {
   fun();
   return 0;
}
```

I run this command 
emcc test.cpp -s DISABLE_EXCEPTION_CATCHING=2 -s EXCEPTION_CATCHING_WHITELIST=["_fun"] -o test.html
with 1.38.34 it's working fine and printing hello, but with 1.39.6 function is not catching exception and "uncaught exception" is printing on console.

**Comment by rohitsaini1995** [comment]
changing _fun to fun works in this example, but not working in my actual code. I removed extra "_" from all the whitlisted functions still no luck. If this is a regression bug, is there any chance that something else other than just prefix causing this issue.

**Comment by rohitsaini1995** [comment]
More over I am passing this flag `DISABLE_EXCEPTION_CATCHING=2 with EXCEPTION_CATCHING_WHITELIST` during linking. With new backend Do I have to pass it during compile time as well.? If yes, how and what would be the flags exactly.

**Comment by kripken** [comment]
Oh, yes - you need the flag during compile as well, as code generation happens then, with the new backend. Literally passing the same flag should work.

**Comment by rohitsaini1995** [comment]
Actually I tried but it didn't work for me. Maybe I am passing the flag in wrong way. So just to make sure as I am compiling code using visual studio and I want to whitelist function named `eventHandler` passing `DISABLE_EXCEPTION_CATCHING=2 EXCEPTION_CATCHING_WHITELIST=['eventHandler']` to command line should work..?

**Comment by kripken** [comment]
Is `eventHandler` a C function? If it's C++ it might be name-mangled. Inspecting object file it is compiled into (say, running llvm-nm on that) will show the actual name the linker sees.

**Comment by aheejin** [comment]
Did you get this fixed? I think it can be a name mangling issue, unless you wrapped it with `extern "C"`. Or it might be an inlining issue (#10721), which means a function that had not been inlined before is now inlined with the latest version due to some changes in LLVM upstream or something. Does adding `-s INLINING_LIMIT=1` to your command line solve the issue? If so it's likely to be due to #10721.
