### ISSUE TITLE
asm.js source file twice the size?

### ISSUE THREAD

**Issue by slimbuck** [emscripten-core/emscripten#10386]
The basis asm.js file generated by compiler 1.39.7 (in order to get the Promise polyfill for IE) generates an asm.js source file that is twice as large compared to older compilers.

Any idea why the massive increase?

Is there anything we can do to bring the down? The flags I'm using are:

-s WASM=0
-s SINGLE_FILE=1
-s ALLOW_MEMORY_GROWTH=1
-Os
-s ASSERTIONS=0
-s MALLOC=emmalloc
-s MODULARIZE=1
-s EXPORT_NAME=BASIS

As always, thanks!

**Comment by kripken** [comment]
Is this a change between 1.38.x and 1.39.x? If so then it's likely the backend change, the non-wasm output is done using a completely different code path now. To confirm, build with `latest` vs `latest-fastcomp` (or `tot` vs `tot-fastcomp`).

The new path (wasm2js) is usually better, so perhaps you're hitting a bad case somehow that we are not aware of. Maybe you can provide builds with both backends, with `--profiling-funcs`, and I'll compare those?

**Comment by slimbuck** [comment]
Hi @kripken ,

Please find the two asm.js compiles attached.

They were both generated with compile flags:
"--profiling-funcs -s WASM=0 -s SINGLE_FILE=1 -s LEGACY_VM_SUPPORT=1"

The link flags use the above and add the following:
"--bind -s ALLOW_MEMORY_GROWTH=1 -O3 -s ASSERTIONS=0 -s MALLOC=emmalloc -s MODULARIZE=1 -s EXPORT_NAME=BASIS"

[basis.zip](https://github.com/emscripten-core/emscripten/files/4179961/basis.zip)

Thanks for your help!

**Comment by juj** [comment]
Breaking down where size is going: in old build: (856KB)
 - JS preamble: 13603 bytes
 - memory initializer: 540983 bytes
 - JS library functions: 49796 bytes
 - asm.js code: 266032 bytes
 - postamble: 5460 bytes

In new build: (1543KB (+80.25%)
 - JS preamble: 9618 bytes
 - Wasm2JS code: 304680 bytes + 6780 bytes
 - memory initializer: 536349 bytes
 - `wasmBinaryFile`: 672028 bytes
 - JS library functions + postamble: 50477 bytes

That `wasmBinaryFile` variable contains a base64 encoded copy of the Wasm2JS code, so in that build there is both a Wasm and a Wasm2JS version of the code present (by accident). If that size is removed, it leaves the new build down to 1543KB - 656KB = 908KB, which is quite close to the old size.

The remaining ~50KB size difference might be explained by Wasm2JS code size being 304680 bytes, whereas asm.js code was only 266032 bytes. Looking at the generated code for both, in the asm.js build variable names (e.g. "HEAP32") are mangled/minified, whereas in wasm2js version they are not. 
Wasm2js depends on Closure for variable name minification, so running the new build with `--closure 1` might give a better size for the Wasm2JS code block.

**Comment by slimbuck** [comment]
Thanks @juj!

So am I specifying a wrong set of flags thereby causing the duplicated module code or is this a bug in the toolchain?

**Comment by juj** [comment]
It is definitely a bug, redundant to have both versions embedded in the same output file.

Just checked - building with `-s MINIMAL_RUNTIME=1` flag does not generate the `wasmBinaryFile` output, though not sure if that would be a solution your case(?)

**Comment by slimbuck** [comment]
Hi @juj 

I managed to compile asm.js basis with MINIMAL_RUNTIME=1, but had to also specify EXPORTED_FUNCTIONS=["_free"].

Unfortunately the resulting module doesn't seem fine, it throws a runtime exception "No dynCall invoker for signature: vi" in callstack BASIS->then->...->initRuntime->...->embind_requireFunction.

**Comment by slimbuck** [comment]
Oh of course, it throws at runtime because it's looking to import free.

I was getting ##error: undefined symbol: free## so had tried specifying free in EXTRA_EXPORTED_RUNTIME_METHODS and DEFAULT_LIBRARY_FUNCS_TO_INCLUDE, but without success.

**Comment by juj** [comment]
Ah, yeah, looks like the issue here is using embind in conjunction with MINIMAL_RUNTIME. Authored PR https://github.com/emscripten-core/emscripten/pull/10417 to help with some of the issues there.

**Comment by slimbuck** [comment]
Thanks @juj. Any idea when that'll land on master?

**Comment by kripken** [comment]
A fix for the duplicate data is in #10438 - it was a bug in the combination of wasm2js + SINGLE_FILE. Thanks @slimbuck and @juj , without your help this might have gone unnoticed for longer!

**Comment by briancullinan** [comment]
I found this to happen with MODULARIZE. It has something to do with needing the memory space, but it fills my .wasm with a bunch of zeros. Is that right? I just read about this somewhere else, something to do with llvm. When I removed MODULARIZE it went from 70MB to 1.2MB

**Comment by kripken** [comment]
@briancullinan That doesn't sound like a known issue - modularize should have a very small impact on the generated code. It shouldn't affect LLVM, in particular. It's just a tiny change to the emitted JS.

Please file an issue with steps to reproduce (or two example builds to compare, something like that).

**Comment by slimbuck** [comment]
This is now fixed. Thanks team!
