### ISSUE TITLE
How to See C++ Mangled Names

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#10391]
Hi.

I want to see mangled C++ names produced by Emscripten so I can export them on the Module object with the mangled names.  So how do I see the mangled names?  

And if I export those functions with their mangled names and then minify the JS code with optimizations, would the mangled names get demangled?  I hope it doesn't cause problems if so. 

Edit to add: How well can the upstream Emscripten toolchain be expected to support C++20 features, especially modules?  Would we able to `import` the `emscripten.h` file as a module?  I'd like an answer to this in addition to the above stuff, if it's not too much trouble.  Thanks in advance.

**Comment by sbc100** [comment]
My understanding is the exporting prevents minification, so anything you export should not be minified.

To see the mangled names of you C++ symbols you can use `llvm-nm` on the resulting object file:

```
$ cat test.cc 
int foo(int x) {
  return 1;
}
$ emcc -c  test.cc
$ llvm-nm test.o 
00000001 T _Z3fooi
         U __stack_pointer
```

Here is you can see the `foo` got mangled to `_Z3fooi`. 

Make sure you use llvm-nm from emscripten, or some recent version of llvm-nm that supports wasm object files.

**Comment by sbc100** [comment]
As for C++20, emscripten uses the latest ToT clang so our support for C++20 features depends on llvm/clang's support.

As for the internals of emscripten such our own header files we currently have no support for C++ modules and no immediate plans to support them .  Feel free to open a feature request but and mark it as "Help Wanted" if you'd like to see that implemented.
