### ISSUE TITLE
Can Envoy interpret wasm or is wasm opaque to it?

### ISSUE THREAD

**Issue by Montana** [emscripten-core/emscripten#10407]
Can the proxy Envoy interpret wasm files? Like are the wasm files transparent to Envoy? I used a wasm filter which changes the http header with Envoy and did a cURL to capture the http header and its showing the interpreted version of wasm not the binary. So does this mean Envoy interprets wasm, just wanted to confirm. Not much on this, seen a similar question, but nothing concrete.

**Comment by sbc100** [comment]
You might be better off asking in the envoy issue tracker.  I don't know if anyone here knows about the envoy integration.

What do you mean by "its showing the interpreted version of wasm"?    Surely the way in which the wasm file is executed (interpreted vs JITed) should mostly unobservable (aside from perhaps perfrmance)?

**Comment by jplevyak** [comment]
I am not entirely sure how cURL would show how the wasm code was executed.  Envoy uses V8 which AFAIK doesn't have an interpreter for wasm.  There are two compilers, one fast and one optimizing.

**Comment by Montana** [comment]
Thank you so much @sbc100, I'll do that.
