### ISSUE TITLE
left shift in C-code zeros result

### ISSUE THREAD

**Issue by galmok** [emscripten-core/emscripten#10402]
I have this setup in my C-code:

"col" is some struct with red, green, and blue being unsigned short.
The values r, g, and b, will be between 0 and 255 inclusive.
The offset is correct.

buffer is:
unsigned int *buffer;

	int r=(col.red >> 8) & 0xff;
	int g=(col.green >> 8) & 0xff;
	int b=(col.blue >> 8) & 0xff;
	int offset = x + y*Used.MapWidth;
	buffer[offset] = r + g<<8 + b<<16 + 0xff000000;

Running the above result in only zeros getting written to buffer[offset]. Changing the last line to this:

	buffer[offset] = r + g*256 + b*65536 + 0xff000000;

solves the problem and the correct value is written. Seems left shift is malfunctioning or I have missed an important detail.

I am using emcc:
emcc (Emscripten gcc/clang-like replacement) 1.39.6 (commit ff44c97ffa3ace24792e3c9d785677050cfec6b2)

I build like this (powershell):
& emcc -s WASM=1 -s ALLOW_MEMORY_GROWTH -s EXPORTED_FUNCTIONS="['_main','_malloc','_getImageData']" -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap", "getValue", "setValue"]' $(ls *.c| % {$_.FullName}) $(ls Racer/*.c | % {$_.FullName}) -I. -ferror-limit=0 -o myrekrig.js

I don't know why I have to add _main and _malloc, but the code wouldn't run/be included otherwise. I started without EXPORTED_FUNCTIONS, but had to expose getImageData and then I also had to expose _main and _malloc. I can live with it, I just don't understand.

**Comment by brion** [comment]
I believe you need parentheses around those shifts, since shift doesn't bind as tightly as addition or multiplication in C.

**Comment by VirtualTim** [comment]
Like brion says, you need brackets around the shifts.
This should have given you compile warnings (Wparentheses).
With simple examples like this I find it handy to compare output using an online c++ shell. For example [cpp.sh](http://cpp.sh/3dprf), or [rextester.com](https://rextester.com/) (that one also does msvc, clang and gcc).

**Comment by brion** [comment]
Also on the EXPORTED_FUNCTIONS question -- _main and _malloc are included by default I believe, but if you set it yourself you're *overriding* the value rather than *adding* to it. The runtime support code needs access to _main to run it, and _malloc to do dynamic heap allocation.
