### ISSUE TITLE
emcc.py fails to read source files that are not valid UTF-8

### ISSUE THREAD

**Issue by attilaolah** [emscripten-core/emscripten#10405]
Some C files happen to not be valid UTF-8, for example this one here:

- https://github.com/lianhaidong/libpano13/blob/master/file.c#L299

While it is annoying that the file is not encoded correctly, `emcc` and `em++` don't seem to care. However, `emcc.py` fails to read the file due to this line:

- https://github.com/emscripten-core/emscripten/blob/master/emcc.py#L726

Changing that line from `open(arg).read()` to `open(arg, 'rb').read()` seems to fix the issue.

Would you be accepting a pull request for this, or should maintainers rather re-encode their source files as UTF-8 instead?

**Comment by sbc100** [comment]
Seems like a good change.  We might also want to just remove that code.
