### ISSUE TITLE
ERROR: BINARYEN_TRAP_MODE is not supported by the LLVM wasm backend 

### ISSUE THREAD

**Issue by abretaire** [emscripten-core/emscripten#10419]
Hello,

I followed the tutorial below and I would like to know why this error appears at the end and how to solve this problem?

![Capture2](https://user-images.githubusercontent.com/58423730/74240226-cb42fa80-4cd9-11ea-853f-0777bc2fbc26.PNG)

Here is the error message
![Capture](https://user-images.githubusercontent.com/58423730/74240010-5bcd0b00-4cd9-11ea-81b7-9d232305de93.PNG)

**Comment by sbc100** [comment]
I looks like you are specifying BINARYEN_TRAP_MODE in your link flags.  This flag doesn't mean anything for the wasm backend, so you should remove it.

**Comment by CraigZeng** [comment]
You could remove BINARYEN_TRAP_MODE=clamp in Samples/Emscripten/CMakeLists.txt. BINARYEN_TRAP_MODE  was removed in EMSctripten 1.39.0

**Comment by sbc100** [comment]
Assuming this answers you question can this issue now be closes?

**Comment by CraigZeng** [comment]
I think so. And it's better to move the issue in the ogre project.
