### ISSUE TITLE
How invoke Emscripten configure and compile to build a cmake project on Windows?

### ISSUE THREAD

**Issue by SergiusPaulus** [emscripten-core/emscripten#10412]
On Windows I can invoke emcc directly on a single cpp file to generate a wasm and js file.  But I have a larger project to build, so am trying to use cmake and then emconfigure and emmake. 
The following works to build without Emscripten:
```
mdir build
cd build
cmake ..
cmake --build .
```

What is the standard use to make this build with emscripten?  I can invoke `emconfigure cmake ..` and it seems to configure, but no invocations of emmake after that have worked and it does not seem to be invoking emcc, even though I begin my session with emcmdprompt.bat.

**Comment by sbc100** [comment]
You should use `emcmake cmake ...`  (emcmake is just a wrapper around emconfigure whish why running emconfigure also works).

You should be able to then run `cmake --build` to compile the project.   If thats not working can you post the output you are seeing?   I recommend using `-G ninja` (the ninja generator) as it will always show the full command line when a command fails.

**Comment by SergiusPaulus** [comment]
Thank you.  I could only get something to attempt a build by using `emconfigure cmake ..` and then `emmake cmake --build .` and it was because the configure step was building Microsoft Visual Studio project files.  But of course I need the emmake step to invoke the emcc compiler. I finally figured out that I have to send parameters in to emconfigure to specify what kind of makefiles are to be built.  I think that if that works, then `emmake make` will actually invoke the emcc or em++ compiler.  

However, I do not know if there is a linker for a non-Microsoft build.  Some say that you still need to link with Microsoft's linker.  I have no idea how to control that.  Maybe modify the makefiles by hand before running `emmake make`?  What is needed is a clear example for building on Windows.

**Comment by sbc100** [comment]
emcmake sets up all the environment variables you should need to set the CC, CXX and LD and more.

None of this should make any difference if you are using windows or not.

**Comment by SergiusPaulus** [comment]
emmake certainly worked differently for me on Windows than Mac. Here's part of what I mean.

`emconfigure -G "Unix Makefiles"
`
I didn't realize there was anything like that -G option, which seems to allow you to tell it to configure for Unix makefiles, whereas if I do not specify that option it was defaulting to Microsoft Visual Studio project files and the cl.exe compiler.  When I configured on Mac without using any -G option it set things up so that clang was used by default when I invoked emmake.

I've never used emcmake.  Is it the same as emmake?

**Comment by sbc100** [comment]
The `-G` option is an option to cmake.   emcmake is a wrapper around cmake that adds a few command line arguments for you.     

Once you've run `emcmake cmake -G make` or  `emcmake cmake -G ninja` all the options should be baked into the generated `build.ninja` or `Makefile` (or Visual Studio project I guess). 

`emcmake` is to` cmake` what `emconfigure` is to `configure`.   I recommand that you use emcmake for cmake projects and emconfigure for autoconf projects (as it happens they are implement by the same logic do you can they are today basically equivalent)..

**Comment by SergiusPaulus** [comment]
Ok, thanks.  Seems like I must use that -G option then.  Because if I do not on Windows what is produced is .vcxproj files, and the only command I've gotten to build them is `emmake --build .` but it does not invoke the emcc or em++ compiler, which is why I think my emconfigure is wrong.

I will post here what I am getting.

**Comment by SergiusPaulus** [comment]
Ok, starting with a new build folder, here are the results I got using the commands you suggested:

**C:\Users\vjohnson\Documents\QuickEmscriptenTest\build>emcmake cmake ..**

```
-- Building for: Visual Studio 16 2019
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/vjohnson/Documents/QuickEmscriptenTest/build
```

then

**C:\Users\vjohnson\Documents\QuickEmscriptenTest\build>cmake --build . --verbose**

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/11/2020 6:42:24 PM.
Project "C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\charl
esjohnson\Documents\QuickEmscriptenTest\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ZERO_CHECK.vcxproj" (default targets
).

Project "C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\charl
esjohnson\Documents\QuickEmscriptenTest\build\AILEMProcessor.vcxproj" (3) on node 1 (default targets).
InitializeBuildStatus:
  Touching "AILEMProcessor.dir\Debug\AILEMProcessor.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\link.exe /ER
  RORREPORT:QUEUE /OUT:"C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\Debug\AILEMProcessor.js" /INCREMENT
  AL /NOLOGO /MANIFEST:NO /PDB:"C:/Users/vjohnson/Documents/QuickEmscriptenTest/build/Debug/AILEMProcessor.pdb" /
  SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/vjohnson/Documents/QuickEmscriptenTest/buil
  d/Debug/" /MACHINE:X64  --default-obj-ext .obj AILEMProcessor.dir\Debug\AILEMProcessor.obj
LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Users\vjohnson\Documents\QuickEmscri
ptenTest\build\AILEMProcessor.vcxproj]
LINK : fatal error LNK1104: cannot open file '.obj' [C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\AILEMP
rocessor.vcxproj]
Done Building Project "C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\AILEMProcessor.vcxproj" (default tar
gets) -- FAILED.

Done Building Project "C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ALL_BUILD.vcxproj" (default targets)
 -- FAILED.


Build FAILED.

"C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\AILEMProcessor.vcxproj" (default target) (3) ->
(Link target) ->
  LINK : warning LNK4044: unrecognized option '/-default-obj-ext'; ignored [C:\Users\vjohnson\Documents\QuickEmsc
riptenTest\build\AILEMProcessor.vcxproj]


"C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\AILEMProcessor.vcxproj" (default target) (3) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file '.obj' [C:\Users\vjohnson\Documents\QuickEmscriptenTest\build\AILE
MProcessor.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.04
```

**Comment by SergiusPaulus** [comment]
Hmmm... that is new.  With your recommended commands I am getting further.  Just 1 error and it is because "Including <emscripten/bind.h> requires building with -std=c++11 or newer!"

But in my cmakelists.txt I am using `set(CMAKE_CXX_STANDARD 11)`

so that should be asking for c++11, right?

**Comment by sbc100** [comment]
Can you past the failing command line ?  Does it included a `-std=` directive at all?  It could be that the `set(CMAKE_CXX_STANDARD 11)` directive is somehow not being translated correctly into CFLAGS.

**Comment by SergiusPaulus** [comment]
Not sure what you mean. How can I get the "failing command line"?  What you see above is what I got on the command line using --verbose.  My cmakelists.txt is very small:

```
cmake_minimum_required (VERSION 3.16.4)

add_compile_options(-std=c++11)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

project (AILEMProcessor)

add_executable(AILEMProcessor ${PROJECT_SOURCE_DIR}/quick_test/AILEMProcessor.cpp)

target_include_directories(AILEMProcessor PUBLIC C:/Users/vjohnson/Documents/AILBrowserDev/emscripten_project/emsdk/fastcomp/emscripten/system/include)
```
But tell me how I can get the failing command line and I will post it here. I really need to know how to tell the compiler how to use c++11 since the codebase I need to build is a little old.

**Comment by sbc100** [comment]
For some reason the resulting visual studio is running cl.exe rather than emcc.   

Its strange to me that the correct compile would used with one generator but not with another.  cmake is supposed to ensure that the build is the same whichever build system you use.

I'm afraid I don't know enough about cmake backends to know how to debug this, but `emcc` *should* run rather than `cl.exe`.  If you are seeing `cl.exe` being run something is going wrong with the project generation.

**Comment by SergiusPaulus** [comment]
My understanding was that the configure step generated the makefiles and that emmake then used those to do the build/compilation.  If that's correct it makes sense then that MS project files are being produced by the configure step and then cl.exe is being used to build them.  I don't see how the emcc compiler would know what to do with them even if it was being called here.

My guess is that my first command (after creating the build folder and navigating into it) is wrong.  It surprised me btw that you suggested emcmake cmake .. as the first step as I thought emconfigure needed to be first.  On MacOS I build this fine with:

```
mkdir build
cd build
emconfigure cmake ..
emmake make
```

But on Windows it doesn't even know what "make" is, even though I have a make.exe.  Maybe not in path.  But I suppose my point is that the docs are unclear, unless you're familiar with all this, how things work on Windows.

**Comment by sbc100** [comment]
If you using a cmake project that we forgot all about `emconfigure`.   You should use `emcmake` in its place.   `emconfigure` is for autoconf-based projects.

Both cmake and autoconf bake in the custom compiler values into the projects that build.  So the resulting `Makefile`, `build.ninja`, or `vcproject` will have emcc as the compiler.   This means that if you use `emcmake` or `emconfigure` to build your makefile you *don't* need to run it under `emmake`.   `emmake` is for projects that don't use cmake or autoconf and instead have thier own makefile for which CC/CXX/LD/etc for overridaable.

In your case the above example works on OSX because the default there for cmake is `-G Unix Makefiles`.    For the final line you could also just run `make` on its own and it should still work.

If you are on windows and you want to have cmake use visual studio that should work, and the resulting project file should not use `cl.exe`.

If you don't need visual studio support you could use a different generator on windows such as `-G "NMake Makefiles` or `-G Ninja`:   See: https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html

I would advice using `-G Ninja` everywhere since its super fast and cross platform has good error reporting and is well tested with emscripten.

However, visual studio *should* work, so if you want to keep debugging it that could be useful to others who want to use it.

**Comment by SergiusPaulus** [comment]
Well, I took your advice and installed and started using Ninja, as follows:

```
emcmake cmake -G Ninja ..
cmake --build .
```

Everything is building fine now.  Thanks a lot.

**Comment by sbc100** [comment]
Woohoo!

**Comment by SergiusPaulus** [comment]
You rock.  But as you know Emscripten and WebAssembly rock too.  The web's been waiting for this technology.  All the best.

**Comment by prideout** [comment]
I found this thread helpful.  I have the same issue whereby `cl` is invoked rather than `emcc`, even though I had run the emsdk_env`.

Using a Ninja project instead of Visual Studio works great though.
