### ISSUE TITLE
unaligned access on atomic (wasm)

### ISSUE THREAD

**Issue by malytomas** [emscripten-core/emscripten#10418]
Hi,
I am porting a large c++ project to wasm and it started, without any actual change, throwing an exception ```captured an uncaught exception: RuntimeError: operation does not support unaligned accesses```. Stacktrace points to method _get_ in this code:
```c++
class thread_id {
public:
    static const std::string& get() {
        if (!holder_.get()) {
            holder_.reset(new std::string(boost::lexical_cast<std::string>
                                          (generator_++)));
        }
        return *holder_;
    }

    static void set(const std::string &value) {
        if (!holder_.get()) {
            holder_.reset(new std::string(value));
        } else {
            *holder_ = value;
        }
    }

private:
#ifdef __EMSCRIPTEN__
    static thread_local std::unique_ptr<std::string> holder_;
    alignas(32) static std::atomic_uint32_t generator_;
#else
    static boost::thread_specific_ptr<std::string> holder_;
    static std::atomic_uint_fast64_t generator_;
#endif
};
```

This is the second time I am dealing with this issue. The fix first time was to use the standard atomic instead of boost, as can be seen in the conditional compilation. Unfortunately, out of a sudden, the problem has resurfaced again. I tried to add the _alignas_ operator to no avail now.

When I print the address of the _generator__ variable, it is aligned at 4-byte boundary (address 0x89A4C). This is both with and without the _alignas_.

I use the same compiler (emcc (Emscripten gcc/clang-like replacement) 1.39.7), same browser (chrome Version 80.0.3987.87 (Official Build) (64-bit)), ubuntu bionic. And most curiously, SAME CODE. I have completely purged my build directory, removed emscripten cache and emscripten ports cache in home. But I cannot get rid of the exception.

These flags were used for the build:
```
-std=c++14 -stdlib=libc++ -Wno-conversion -Wno-missing-braces -Wno-unused-parameter -s OFFSCREENCANVAS_SUPPORT=1 -s PROXY_TO_PTHREAD=1 -s OFFSCREENCANVASES_TO_PTHREAD='#display' -s PTHREAD_POOL_SIZE=30 -s TOTAL_MEMORY=512MB -s ALLOW_MEMORY_GROWTH=1 -s WASM_MEM_MAX=1024MB -s EXTRA_EXPORTED_RUNTIME_METHODS='[cwrap,printErr]' -s WASM=1 -s USE_PTHREADS=1 -s FETCH=1 -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_FREETYPE=1 -s USE_HARFBUZZ=1 -s USE_WEBGL2=1 -s FULL_ES3=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s DISABLE_EXCEPTION_CATCHING=0 -s FILESYSTEM=0 -s STRICT=1 -O3 -DNDEBUG -O3 -DNDEBUG
```

Unfortunately, I am failing at reproducing the issue on simpler code.

I have run out of ideas and would very much appreciate any help. Any suggestions how to debug this.

Thanks

**Comment by kripken** [comment]
When you say the problem resurfaced, what changed? Did you upgrade the toolchain, or just rebuild, or change code in the project elsewhere, or something else?

If it's just when rebuilding, is it consistent on each build? Or is it random at runtime? Emscripten builds should be deterministic, so each build should be identical - so I'd guess it's some difference at runtime, some nondeterminism in the program?

If it happened when upgrading, bisecting to find the relevant change is usually fastest.

**Comment by VirtualTim** [comment]
At a glance my guess would be this line: `new std::string(boost::lexical_cast<std::string>(generator_++))`. 
Runtime alignment errors are tricky, since you might get lucky and the code might generate with the correct alignment, but you can change something unrelated and it will start to fail.

I'm compiling with `-Wcast-align` `-Wover-aligned`, and linking with `-s WARN_UNALIGNED=1`. I suggest you do the same, and see if these pick up anything.

**Comment by malytomas** [comment]
> When you say the problem resurfaced, what changed? Did you upgrade the toolchain, or just rebuild, or change code in the project elsewhere, or something else?

I was changing my code, hunting some other bug, and suddenly (after a build) this happened. After some attempts I completely discarded all my changes and did a clean rebuild, but the unaligned access remained. There were no other changes to toolchain, code or browser.
I suspect some other build cache somewhere. Are there any other apart from what I mentioned?
Should I try to completely remove the sdk/toolchain folder too?

> If it's just when rebuilding, is it consistent on each build? Or is it random at runtime? Emscripten builds should be deterministic, so each build should be identical - so I'd guess it's some difference at runtime, some nondeterminism in the program?

Once it started happening, it is consistent. It happens every page reload, and every rebuild.


> At a glance my guess would be this line: `new std::string(boost::lexical_cast<std::string>(generator_++))`.

Agreed.

> Runtime alignment errors are tricky, since you might get lucky and the code might generate with the correct alignment, but you can change something unrelated and it will start to fail.

The variable is static member, it should be placed in the init data section, honoring the alignment requirements.
Printing the address, it is 4-byte-aligned, which is enough for 4-byte-atomic, right?
Either way, the alignas(32) was completely ignored.

> I'm compiling with `-Wcast-align` `-Wover-aligned`, and linking with `-s WARN_UNALIGNED=1`. I suggest you do the same, and see if these pick up anything.

I get several warnings like:
```
/...../mesh.cpp:148:24: warning: cast from 'char *' to 'vts::vec3f *' (aka 'Matrix<float, 3, 1> *') increases required alignment from 1 to 4 [-Wcast-align]
            vec3f *o = (vec3f*)(spec.vertices.data()
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

However, this is unrelated code that would be run much later if there was no error.
I got no other warning and the same exception at runtime.


I really appreciate your help, I know this is difficult.
Would you have any other ideas?
Thanks

**Comment by makslevental** [comment]
@malytomas did you ever figure this out? having the same sort of issue...

**Comment by malytomas** [comment]
@makslevental Unfortunately no.
My solution was to completely remove the atomic (when building for emscripten), which was not a big deal as it was just an incremental index for naming threads for purpose of logging.

**Comment by makslevental** [comment]
:( @malytomas that's unfortunate. thanks anyway
