### ISSUE TITLE
LEGACY_VM_SUPPORT MIN_IE_VERSION Promise polyfill breaks Closure with wasm2js

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [emscripten-core/emscripten#10422]
At least with the 1.39.6 release, if IE support is enabled and Closure runs after linking, it will fail, complaining that
```
temp/path/name.wasm.o.js.pp.js.mem.js.jso.js:1: ERROR - Variable Promise declared more than once. First occurrence: externs.zip//es6.js
```
The `externs.zip` in question is part of Closure and lives inside its `.jar` file.

Running an equivalent build with closure disabled works as intended.

Doing the failing build with `EMCC_DEBUG` set reveals that the exact command that fails is
```
shared:DEBUG: executed C:/Clones/emsdk/java/8.152_64bit/bin/java.exe -Xmx1024m -jar C:\Clones\emsdk\upstream\emscripten\third_party\closure-compiler\compiler.jar --compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT5 --js C:\Clones\emsdk\upstream\emscripten\src\closure-annotations.js --js C:\Clones\emsdk\upstream\emscripten\src\closure-defined-fs-annotation.js --externs C:\Clones\emsdk\upstream\emscripten\src\closure-externs.js --externs C:\Clones\emsdk\upstream\emscripten\third_party\closure-compiler\browser-externs\fileapi_synchronous.js --js_output_file C:\Users\username\AppData\Local\Temp\emscripten_temp\modulename.wasm.o.js.pp.js.mem.js.jso.js.cc.js --js C:\Users\username\AppData\Local\Temp\emscripten_temp\modulename.wasm.o.js.pp.js.mem.js.jso.js
```

My understanding is that Closure uses `externs.zip/es6.js` to keep track of what the ECMAScript 6 built-ins are, and isn't detecting that the redefinition is actually a polyfill to use when the real version is absent. I'd assume there's an extra annotation that could be added somewhere to explain this to Closure (`@suppress {duplicate}` looks promising, but doesn't work when naively added to `emscripten/src/closure-annotations.js`).

**Comment by kripken** [comment]
@juj you know closure externs the best, please take a look.

**Comment by juj** [comment]
I have a branch in the queue that fixes this Closure issue and a hundred other Closure warnings that we are seeing at #10398 , but that is pending for https://github.com/emscripten-core/emscripten/pull/10393 to land first before it can progress.
