### ISSUE TITLE
[docs] tests/runner.py says "No tests found to run in set: ['asm*', 'binaryen*']" which are mentioned on docs page

### ISSUE THREAD

**Issue by haukex** [emscripten-core/emscripten#10420]
**Summary:** The command `python tests/runner.py asm* binaryen*` [from the documentation](https://emscripten.org/docs/getting_started/test-suite.html#important-tests) results in the error `No tests found to run in set: ['asm*', 'binaryen*']`. OTOH `python tests/runner.py wasm*` appears to work but doesn't appear to be documented, so I don't know what the correct way to run the core tests is.

Background: I just wanted to submit a fairly small pull request to `library.js` and wanted to make corresponding changes to the tests.

I followed the steps described in:

- <https://emscripten.org/docs/getting_started/downloads.html>
- <https://emscripten.org/docs/getting_started/test-suite.html>
- <https://emscripten.org/docs/contributing/developers_guide.html>

Specifically:

- set up a new Linux VM with Ubuntu 18.04 LTS with all the latest updates
- `sudo apt-get install build-essential git-core python cmake default-jre`
- `git clone https://github.com/emscripten-core/emsdk.git`
- `source ~/emsdk/emsdk_env.sh`
- `echo "source ~/emsdk/emsdk_env.sh" >>~/.profile`
- `emsdk update-tags`
- `emsdk install tot-upstream`
- `emsdk activate tot-upstream`
- `source ~/emsdk/emsdk_env.sh`
- `emsdk list | grep INSTALLED`
```
    *    sdk-releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit	INSTALLED
    *    sdk-releases-upstream-5acdc357a75ecba2935b2e752abf30140c7d9203-64bit	INSTALLED
     *     releases-upstream-3b8cff670e9233a6623563add831647e8689a86b-64bit	INSTALLED
     *     releases-upstream-5acdc357a75ecba2935b2e752abf30140c7d9203-64bit	INSTALLED
     *     node-12.9.1-64bit        	INSTALLED
```
- `cd ~/emsdk/upstream/emscripten`
- `python tests/runner.py test_loop` (this example from the docs seems to work)
```
tests/runner.py:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
WARNING: no 'numpy' module, HyBi protocol will be slower
Test suites:
['test_core']
Running test_core: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
test_loop (test_core.wasm0) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.552s

OK
```
- `python tests/runner.py asm* binaryen*` (this example from the docs *doesn't* work)
```
tests/runner.py:WARNING: use EMTEST_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
WARNING: no 'numpy' module, HyBi protocol will be slower
No tests found to run in set: ['asm*', 'binaryen*']
```

- However, `python tests/runner.py wasm*` at least seems to find tests and run them.

Could this be a documentation issue at <https://emscripten.org/docs/getting_started/test-suite.html#important-tests>, since it doesn't mention `wasm*` anywhere?

**Comment by sbc100** [comment]
I believe the documentation out of date yes.  You can see all the names of the test suites at the end of the test_core.py files.

**Comment by kripken** [comment]
Thanks for filing! We should definitely fix this, PR would be great.

**Comment by haukex** [comment]
Thanks! I took a look [here](https://github.com/emscripten-core/emscripten/blob/6f2637cf63278761c5cfa8d5a4a833181676b28b/tests/test_core.py#L8861) and [here](https://github.com/emscripten-core/emscripten/blob/6f2637cf63278761c5cfa8d5a4a833181676b28b/tests/runner.py#L239), and my understanding from those is that, instead of `asm* binaryen*`, the core tests are:

- `wasm*` appears to always be part of the core tests
- `if shared.Settings.WASM_BACKEND`, it's also `wasm*`, plus the non-core `asan`, `lsan`, and `asani`
- `if not shared.Settings.WASM_BACKEND`, it's `wasm* asm*` (?)
- `binaryen*` no longer exists?
- I see mentions of `simd2` and `bulkmem2`, but I'm not sure where those fit in

Since this is my first time looking at these, I would appreciate confirmation from someone who knows better, and I could create a pull request, yes.

**Comment by sbc100** [comment]
That looks about right yes.   I would recommend only mentioning "wasm0-N" in the docs and pointing the docs at test_core.py file for anything more detailed since these details tend to change slowly over time.

**Comment by haukex** [comment]
Thanks, I've submitted some suggestions as #10489.
