### ISSUE TITLE
Build time node dependency (TextDecoder not found)

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10429]
A little history of our node version dependency:

- Currently we depend on node version 4.1.1 to run compiler.js.  I think we do this because the vesion of node we use to use in old version of emsdk was 4.1.1.
- I tried to update this version in #9333, but reverted in  #9345
- As of emsdk#348 node we now use  12.9.1 in emsdk.

The reason I bring this up is that there is an issue where `MINIMAL_RUNTIME=1` +  `TEXTDECODER=2` generates a *build* time dependency on `TextDecoder`:

```
$ ./emcc -s MINIMAL_RUNTIME -s TEXTDECODER=2 ./tests/hello_world.c
error: failure to execute js library "library_strings.js": ReferenceError: TextDecoder is not defined,
error: use -s VERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "ReferenceError: TextDecoder is not defined" | ReferenceError: TextDecoder is not defined
    at eval (eval at load (eval at globalEval (/usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js:110:8)), <anonymous>:27:20)
    at Object.load (eval at globalEval (/usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js:110:8), <anonymous>:169:9)
    at JSify (eval at globalEval (/usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js:110:8), <anonymous>:71:20)
    at Object.<anonymous> (/usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js:226:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
shared:ERROR: '/usr/bin/nodejs /usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js /tmp/tmpE4x5Ma.txt' failed (1)
```

I think this breaks because without MINIMAL_RUNTIME the string functions in ` src/runtime_strings_extra.js` just go in the preamble and don't get processed by the jscompiler.   But with MINIMAL_RUNTIME=1 they go through the JS compiler?  Does that sounds right?

One of the ways to address this issue is to bump our build time JS dependency to 12.9.1... what do people think about doing that?

**Comment by sbc100** [comment]
I think it makes sense to match our build-time minimum node dependency with the version that emsdk installed.    This is currently 12.9.1, which is more recent that the node that ships with Ubuntu LTS.  However with emsdk and any number of other methods to install node I don't think thats a problem.   @kripken do you want to continue to support system node on ubuntu LTS?

**Comment by sbc100** [comment]
@juj since this relates to MINIMAL_RUNTIME and there might be an easy fix here that I'm not aware of.

**Comment by juj** [comment]
Oh, actually, this is highlighting how UTF-16 strings are just broken in `MINIMAL_RUNTIME=1` + `TEXTDECODER=2` mode. Global variables in library_x.js files do not end up in build output, so `UTF16Decoder` will not be included in code, just attempted to be parsed by the compiler at compile time. MINIMAL_RUNTIME should do
```js
mergeInto(LibraryManager.library, {
...
 #if TEXTDECODER == 2
 UTF16Decoder: '=new TextDecoder('utf-16le');',
#else // TEXTDECODER == 2
#if TEXTDECODER
  UTF16Decoder: '= typeof TextDecoder !== 'undefined' ? new TextDecoder('utf-16le') : undefined;',
#endif // TEXTDECODER
#endif // TEXTDECODER == 2
...
});
```
in library_strings.js to get the UTF16Decoder variable actually in the build output, and in this mode, the TextDecoder object will not be attempted to be instantiated at build time.

**Comment by juj** [comment]
I can submit a PR for this tomorrow'ish, or if you'd like to test it out, feel free to!

**Comment by sbc100** [comment]
Ah great so it looks like there is fix that doesn't involve requiring TextDecoder in the build-time node.  Happy for you to fix that :)

**Comment by sbc100** [comment]
I still propose we bump the minimum requirement since we don't test on the older versions and we don't want to get bug reports from users of the older versions.

**Comment by kripken** [comment]
sgtm to bump the minimum requirement.
