### ISSUE TITLE
Perf on short std::strings

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10433]
```cpp
#include <string>
#include <stdlib.h>

int xDoNotRemove = 0;

void string1000_test() {
  for (int x = 0; x < 1000; x++) {
    std::string s = "foobarfoobarfoobarfoobarfoobar";
    s += "barfoobarfoobarfoobarfoobarfoo";
    xDoNotRemove += s.size();
  }
}

int main(int argc, char** argv) {
  int n = argc > 1 ? atoi(argv[1]) : 0;
  for (int i = 0; i < n; i++) {
    string1000_test();
  }
}
```
The silly string's length there can be adjusted. Interesting, when I compare to native, on very short strings we are much slower,
```
string size - times slower than native
         30 - 1.17
         12 - 1.53
          9 - 1.18
          6 - 6.07
          3 - 2.50
```
Almost all the time is spent in memcpy. Our memcpy is pretty well-tuned, and I confirmed it isn't the time spent checking for different sizes that is an issue, almost all the time is in the simple
```
  while (d < d_end) {
    *d++ = *s++;
  }
```
Perhaps a native memcpy can be better than that? Alternatively, perhaps libc++ std::string is more tuned for long strings.

**Comment by kripken** [comment]
Investigating this, I compared emscripten and native using libc++, and verified we take the same internal code paths, so no extra calls to malloc or such. With the same `string` impl, some of the difference went away, but wasm was still over 2x slower.

The main factor left is the speed of `memcpy(.., 3)`. When I replace the system memcpy with the same one on both builds, the difference lessens. Investigating the difference there, the only real actionable thing is that in emscripten's memcpy we have an if for very large copies, as we have a special path for them in JS,

https://github.com/emscripten-core/emscripten/blob/ee81b17e37ab1fc51058c1ba84bc2fef20f058b0/system/lib/libc/emscripten_memcpy.c#L28

That special path is not useful in standalone wasm (no JS). Removing it (a single well-predicted branch) helps by 6-10% (depending on the VM), after which we are around 1.75-2x slower than native (again, depending on the VM).

This seems worth doing. It will require adding a variation to `libc_rt_wasm` for standalone/non-standalone mode. @sbc100 @jgravelle-google what are your thoughts on that?

**Comment by backes** [comment]
In V8 we also had to tune our own memcpy (FYI: [should disappear soon](https://crbug.com/v8/10209)) for small counts.
We do something similar to:
```
switch (count) {
  case 1: memcpy(dst, src, 1); break;
  case 2: memcpy(dst, src, 2); break;
  ...
  default: memcpy(dst, src, count); break;
}
```

See [original code](https://cs.chromium.org/chromium/src/v8/src/utils/memcopy.h?l=285&rcl=7b8038a34e1be102e5787c99591b189479b65881).

Clang generates a minimal number of move instructions per case, as expected (see [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlICsupVs1qhkAUgBMAISnTSAZ0ztkBPHUqZa6AMKpWAVwC2tQVvQAZPLUwA5YwCNMxEJNIAHVAsLraewyaCnt5qdFY29kZOLm5KKqG0DATMxAT%2BxqacisqYqr5JKQThdo7OrorJqemBWQqVRdYlUWWSAJSKqAbEyBwA5FIAzNbIhlgA1OIDOsh1xNbAk9jiAAwAgiurAG6oeOhjVMx1APpGmEbI7gCeENu7AFRj6HWkY2i0dWO36A8K3S/eAC9MEcCK9OvRWhMAOyyNZjMYKADuhGQCDGEDQBgh0Nhq3h8JYSjGyxAYwcxEwzAA1pNcfjXodMGNOKTTucrhAngR/n9ma1aWSKdTaRt6YSmZJWWcLtcuTzkC82gLyZSaQM6fjxWMBlL2bLngjeQN%2BerBaqRXDNYyxtxdTLOQbfgqbSbpGbherRVaiQBWO0cuWG50%2B13utUagnWgBs/v13KDLyjoZVHojDKJUNjDvjTpeUOTQvDXsjRIAHFnA7mxqWC%2BbPZb4VgDgZWAQK47eZiIcrCxa8dCACIbcRQge9dqsEC9H29UimXrLWeoKc6ORyBGdbpMwacWdthfj9oISlYFwQdpUkDcACcADofZIfdefT7OJwBgNONf30Ip9xZ/Oi6kMuvSzgoIDLKQ%2B6Lu0cCwEgaBGO4eDsGQFAYqgSEoWUIwiMAILEFiVKkFQKEEM44EQA4U5AQ41gpJcU67qQiGnPQADytCsIxB6kFgRh4ewNGzvgFJ5JsmDgbxmAAB65AY5FMbO1jkZOvGsHg5IMXoWBKVBcxGEp7Q0PQTBsBwPD8IIwiiCga4yEImngZA7SoO4CRSQAtOxAxjJ5dToJMA4SDIcg8H5yBgTkeQaBA5jVJkpDmMUkTREEXg%2BHQCXpSEvgpaULi1NFCQFFU%2BgZIIcS5CV9T5c0hUVIU2W1LVjSpWUnDtAom49FwE5TjOc7CcBU4yaWUaeVG3CvDZwDogQhG0FSkIQLghAkBMkifi8ehYahm2fpCq6hTIe7Ca0R4nmU56kJePrLLe3BQtwyzcNwpbjVGpbLONPq/r0/6kIZnDLJBgFLlOYEQVB539b0kgAcNIFnQeF2kBJxDeBo3BAA)).

Maybe Emscripten can do something similar?

**Comment by kripken** [comment]
Thanks @backes !

I did some tests now, and yes, this can help. When using a switch (confirmed lowered to a br_table) that leads to hardcoded loads/stores for size 3, this is 7.5% faster. The downside though is an increase in code size (e.g. 140 bytes for handling cases 1-4), so this is a tradeoff we'll need to think about.

**Comment by backes** [comment]
Wow, 140 bytes is a lot indeed for four cases. If we decide to add this, we would probably hard-code even more cases, maybe 16.

Just to be clear: This would be in the memcpy implementation, so all parts of the system would profit from this, right?

**Comment by kripken** [comment]
Yes, it would be the system memcpy, so it would help in general. But I'm not sure how common such small memcpys are - if it's a fixed-size memcpy then llvm already optimizes that very well statically, so this would only help dynamic ones.
