### ISSUE TITLE
empty string argument gets lost when going via response file

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#10441]
This is a followup to #10440 

If I pass an empty string as an EXPORTED_FUNCTION:

 `./emcc -s ~/test/hello.c -s EXPORTED_FUNCTIONS="['', '_foo']"`

I would expect to get the following linker argument:

`--export "" --export foo`

This works when passing args via python subprocess, but if passed via response file the linker ends up seeing: `--export --export foo` and reports `file not found: foo`

**Comment by sbc100** [comment]
@awtcode

**Comment by kripken** [comment]
Shouldn't we error on an empty string for a function name, anyhow?

**Comment by sbc100** [comment]
I can't seem to reproduce this issue anymore.
