### ISSUE TITLE
Reopening Issue: video file in opengl

### ISSUE THREAD

**Issue by Jonathhhan** [emscripten-core/emscripten#10487]
The solution from sortofsleepy sounds very interesting, sounds like it could be possible with Open Frameworks Emscripten too. I wanted to ask if there is a similar working example somewhere, because I could not find anything.

"whoa this is an old thread haha - I only just stumbled across this during research of a somewhat opposite path but in any case, figured I'd ought to leave a note for anyone else that might be looking to do the same thing in 2018. 

It is possible and I have a working sample. I can't quite release it yet though and it is tied to a framework but I can explain the basic concept. 

The simplest way is to blend use of Javascript and C++. You'll need to include `Embind`.

Basically the broad concepts are

1. create video element in Javascript. 
2. create texture in c++. 
3. in the global GL object, you'll be able to look up the texture you created in C++ within the textures key ie `GL.textures[<id for your c++ texture>]` so store a reference to that somehow in your Javascript. 
4. From there, all the control is on the Javascript side of things. I won't go into how to play the video as that should be pretty simple but to update your texture with the video content "

```javascript

  var gl = GLctx;
  gl.bindTexture( gl.TEXTURE_2D,texture );
 
   gl.texImage2D( gl.TEXTURE_2D,0,gl.RGBA,width,height,0,gl.RGBA,gl.UNSIGNED_BYTE,<video element> );
      gl.bindTexture (gl.TEXTURE_2D,null );

```

_Originally posted by @sortofsleepy in https://github.com/emscripten-core/emscripten/issues/1434#issuecomment-442215121_

**Comment by sortofsleepy** [comment]
@Jonathhhan is there something specific you were stuck on? Unfortunately I still can't quite release the sample but it's really straightforward.

**Comment by Jonathhhan** [comment]
@sortofsleepy thanks for your answer and your explanation. I will definitely give it a try. So far it looks like the best solution I have found for including external video files into Emscripten.
