### ISSUE TITLE
Preprocessor error with SEEK

### ISSUE THREAD

**Issue by Epse** [emscripten-core/emscripten#10483]
When compiling any code that uses `SEEK_SET`, `SEEK_CUR` or `SEEK_END` with a preprocessor conditional, the compiler will error.

I have included error output below. Please let me know if this should be asked upstream, I have searched the internet but could not find anything about this particular issue.

```
./Modules/_io/fileio.c:890:5: error: token is not a valid binary operator in a preprocessor subexpression
#if SEEK_SET != 0
    ^~~~~~~~
/home/e/install/emsdk/upstream/emscripten/system/include/libc/fcntl.h:80:18: note: expanded from macro 'SEEK_SET'
#define SEEK_SET __WASI_WHENCE_SET
                 ^~~~~~~~~~~~~~~~~
/home/e/install/emsdk/upstream/emscripten/system/include/wasi/api.h:693:45: note: expanded from macro '__WASI_WHENCE_SET'
#define __WASI_WHENCE_SET ((__wasi_whence_t)0)
                           ~~~~~~~~~~~~~~~~~^
./Modules/_io/fileio.c:893:5: error: token is not a valid binary operator in a preprocessor subexpression
#if SEEK_CUR != 1
    ^~~~~~~~
/home/e/install/emsdk/upstream/emscripten/system/include/libc/fcntl.h:81:18: note: expanded from macro 'SEEK_CUR'
#define SEEK_CUR __WASI_WHENCE_CUR
                 ^~~~~~~~~~~~~~~~~
/home/e/install/emsdk/upstream/emscripten/system/include/wasi/api.h:698:45: note: expanded from macro '__WASI_WHENCE_CUR'
#define __WASI_WHENCE_CUR ((__wasi_whence_t)1)
                           ~~~~~~~~~~~~~~~~~^
./Modules/_io/fileio.c:896:5: error: token is not a valid binary operator in a preprocessor subexpression
#if SEEK_END != 2
    ^~~~~~~~
/home/e/install/emsdk/upstream/emscripten/system/include/libc/fcntl.h:82:18: note: expanded from macro 'SEEK_END'
#define SEEK_END __WASI_WHENCE_END
                 ^~~~~~~~~~~~~~~~~
/home/e/install/emsdk/upstream/emscripten/system/include/wasi/api.h:703:45: note: expanded from macro '__WASI_WHENCE_END'
#define __WASI_WHENCE_END ((__wasi_whence_t)2)
```

**Comment by sbc100** [comment]
It looks to my like the upstream code might be trying to do something it shouldn't by assuming it can use SEEK_SET in the pre-processor in this way.    It probably is worth seeing if we can find out what the standard says about this.  Can you point me to the upstream code in question (is it open source)?

**Comment by Epse** [comment]
It's Cython, though a simple example like the following triggers as well.

```C
#include <stdio.h>

#if SEEK_SET != 0
#define didsomething
#endif

int main() {
    return 0;
}
```

**Comment by sbc100** [comment]
I'm just wondering if that standard says that constants like SEEK_SET have to be usable in pre-processor expressions like this?

**Comment by sbc100** [comment]
Oh.. I completely forgot.  We already fixed this upstream in wasi-libc: https://github.com/CraneStation/wasi-libc/pull/148.

We just need to update the wasi headers.

**Comment by Epse** [comment]
Any idea when this might happen or how I might do this for myself until the headers get updated?

**Comment by sbc100** [comment]
For a quick local fix you can probably just edit `api.h` and remove those cast operations from the macros.

**Comment by Epse** [comment]
Thank you very much, truly appreciate the help and all the work that's been put into emscripten
