### ISSUE TITLE
Erroneous glGetString call throws TypeError

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#10494]
```
WebGL: INVALID_ENUM: getParameter: invalid parameter name, WEBGL_debug_renderer_info not enabled
Uncaught TypeError: Cannot read property 'length' of null
    at lengthBytesUTF8 (taisei.js:formatted:5053)
    at stringToNewUTF8 (taisei.js:formatted:12107)
    at _glGetString (taisei.js:formatted:14009)
    at wasm-function[2316]:0x190c9d
```

A null value is passed to `stringToNewUTF8` here: https://github.com/emscripten-core/emscripten/blob/430c2911dbe0104beab264cd19a971a2a7c6b793/src/library_webgl.js#L1165

Would it be a good idea to make `stringToNewUTF8` return a null pointer if the argument is null? I think it at least warrants an assertion.

**Comment by kripken** [comment]
Good catch, that does look like a bug! I think we need to not call `stringToNewUTF8` on a null, and return a null pointer from the function. Would you like to open a PR?

**Comment by Akaricchi** [comment]
Sure. I was just wondering if you'd rather avoid passing null to `stringToNewUTF8` or have `stringToNewUTF8` handle such cases.
