### ISSUE TITLE
Can webassembly access an OpenGL context created outside?

### ISSUE THREAD

**Issue by AlexVestin** [emscripten-core/emscripten#10503]
Hello, awesome project!
I'm trying to use a a c++ library to draw both on the web and on node, but with extra computations on the node version. I am currently using node-addon bindings for node and webassembly bindings for the web, but it would do wonders if the same code could be re-used. 

Issue is in the node version I need to have access to the underlying context outside of the webassembly code for some other computation, is there any way to share/get a context created in wasm to node, or use an already existing gl context in webassembly?

**Comment by kripken** [comment]
I think this can be done, by setting the existing context on `Module.ctx`, as `createContext` begins with
```javascript
    createContext: function(canvas, useWebGL, setInModule, webGLContextAttributes) {
      if (useWebGL && Module.ctx && canvas == Module.canvas) return Module.ctx; // no need to recreate GL context if it's already been created for this canvas.
```
So if asked to create one, and one already exists there, it will use it.

**Comment by AlexVestin** [comment]
That (and setting GLctx) worked, thanks!
