### ISSUE TITLE
Question: is here a way to save application's settings?

### ISSUE THREAD

**Issue by Wohlstand** [emscripten-core/emscripten#10504]
For example, it's a game, and I need a way to save gamesave or keyboard setup done in options. Knowing the fact resources are read-only and they are always getting restored back into initial state on a restart. No, game is not uses network at all, I need to save setup locally. Is that possible? Last time when I have checked around documentation and googled around the world, I didn't found anything useful.

**Comment by Akaricchi** [comment]
You can use the [IndexedDB](https://emscripten.org/docs/api_reference/emscripten.h.html) APIs. I personally use the [IDBFS](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-idbfs) filesystem to store my persistent data in a config file just like the desktop version of the game does.

**Comment by Wohlstand** [comment]
Oh, thanks, I should try out this! I'll close this when I make this work at me. :fox_face:

**Comment by Wohlstand** [comment]
Okay, some days ago I did implemented that:
https://github.com/WohlSoft/PGE-Project/blob/b8f5fe7d594c230c149d18b4fc51f016c13a3613/Engine/common_features/app_path.cpp#L45-L87
So, thanks for a tip :fox_face:
