### ISSUE TITLE
JavaScript reference error in ASM_CONSTS

### ISSUE THREAD

**Issue by andypotato** [emscripten-core/emscripten#10514]
I'm using version **1.39.8** of emscripten and have successfully built the ARToolkit project as WASM module using the following command line:
```
emcc
-I/src/artoolkit5-js/lib/artoolkit5/include
-I/src/artoolkit5-js/src/artoolkit5/
-I/src/artoolkit5-js/lib/
-I/src/artoolkit5-js/lib/artoolkit5/lib/SRC/KPM/FreakMatcher
/src/artoolkit5-js/src/artoolkit5/libar.bc
/src/artoolkit5-js/lib/ARToolKitJS.cpp
/src/artoolkit5-js/lib/trackingMod.c
/src/artoolkit5-js/lib/trackingMod2d.c
-Oz -Wno-warn-absolute-paths
--memory-init-file 0 --bind
-D HAVE_NFT
-s TOTAL_MEMORY=268435456
-s USE_ZLIB=1
-s USE_LIBJPEG
-s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS']"
-s BINARYEN_TRAP_MODE=clamp
-s SINGLE_FILE=1
-s EXPORT_ES6=1
-s USE_ES6_IMPORT_META=0
-s MODULARIZE=1
-o /src/artoolkit5-js/src/artoolkit5/artoolkit_wasm.js
```

When using the module I will encounter the following error message:

```
Uncaught (in promise) ReferenceError: artoolkit is not defined
    at Array.ASM_CONSTS (artoolkit_wasm.js:5)
    at _emscripten_asm_const_iiiiiii (artoolkit_wasm.js:5)
    at :8080/wasm-function[923]:0x4ceb0
    at :8080/wasm-function[852]:0x4990f
    at :8080/wasm-function[1236]:0x6548b
    at Module.dynCall_iiiii (artoolkit_wasm.js:5)
    at dynCall_iiiii_6 (eval at makeDynCaller (artoolkit_wasm.js:NaN), <anonymous>:4:12)
    at ARToolkit.setup (eval at new_ (artoolkit_wasm.js:NaN), <anonymous>:10:10)
    at ARController._callee$ (ARController.js:106)
    at tryCatch (runtime.js:45)
```

Debugging this error I found the following code in the generated artoolkit_wasm.js:
```
var ASM_CONSTS = [function($0, $1, $2, $3, $4, $5) { if (!artoolkit["frameMalloc"]) { artoolkit["frameMalloc"] = ({}); } [...]
```
Inside `ASM_CONSTS` there is a reference to the `artoolkit` variable which was never initialized anywhere in the file. This is what causes the module to crash.

Is this a bug in emscripten or am I simply doing something wrong? If it's any help, the full source of the generated file [can be found here](https://github.com/andypotato/artoolkit5-js/blob/master/src/artoolkit5/artoolkit_wasm.js).

**Comment by sbc100** [comment]
Are you the author of the code?

It looks like the native code expects a JS global called `artoolkit` to exist.    From the README is looks like you need to something like `const artoolkit = new ARToolkit();`.

**Comment by sbc100** [comment]
The ASM_CONSTS come form the native code EM_ASM code embedded in the C++. e.g. https://github.com/andypotato/artoolkit5-js/blob/master/lib/ARToolKitJS.cpp#L154

You can see the code there depending on the `artoolkit` global var.

**Comment by andypotato** [comment]
I'm not the original author of the code you referenced. It's from the original **jsartoolkit5** project which has already successfully created an emscripten port of ARToolkit. What I'm trying to achieve is building an ES6 compatible module with WASM enabled based on their original work.

You gave me a very good pointer, thank you very much for that! So I guess this is not an issue with emscripten itself but merely with the original C++ code.
