### ISSUE TITLE
Asyncify: repeated yield fails

### ISSUE THREAD

**Issue by msorvig** [emscripten-core/emscripten#10515]
Hello!

I'm implementing a suspend() / resume() API, where suspend() yields to the event loop until resume() is called. (So far I've not found a C API in Emscripten which covers this use case - please point me in the right direction if there is one)

```
EM_JS(void, qt_suspend, (), {
  let sleepFn = function(wakeUp) { Module.qtWakeUp = wakeUp; };
  return Asyncify.handleSleep(sleepFn);
});

EM_JS(void, qt_resume, (), {
    Module.qtWakeUp();
});
```
This works fine once, however repeated calls to suspend does not: calls to resume() won't and will eventually fail with an "indirect call to null" error.

```
while (true) {
    puts("suspending")
    qt_suspend()
    puts("resumed")
}
// resume() is called from e.g. a button click event handler.
```

```
    RuntimeError: indirect call to null main.js line 1565 > WebAssembly.instantiate:20341:1
    dynCall_vi https://192.168.0.12:8005/OUT/main.js line 1565 > WebAssembly.instantiate:20341
    x https://192.168.0.12:8005/OUT/main.js:3597
    dynCall_vi https://192.168.0.12:8005/OUT/main.js:3818
    dynCall_vi_2 https://192.168.0.12:8005/OUT/main.js line 2196 > Function:4
    resume https://192.168.0.12:8005/OUT/main.js line 2007 > Function:7
    onclick https://192.168.0.12:8005/OUT/asyncify.html:1`
```

Bug in emscripten - or can suspend/resume be implemented differently?

**Comment by kripken** [comment]
Are you thinking of something like fibers or coroutines here, when talking about multiple suspends? (Otherwise I'm not sure what multiple suspends mean, as a suspended fiber/coroutine can't do anything, so it can't suspend again.)

There is a new Fibers API in emscripten that might be useful: https://emscripten.org/docs/api_reference/fiber.h.html cc @Akaricchi

**Comment by msorvig** [comment]
Hi, this is more about repeated suspends, rather than concurrent/recursive suspend.  Perhaps best explained via example, I've made a reproducer example available here: https://github.com/msorvig/qt-webassembly-examples/tree/master/emscripten_asyncify_%2310515

In that example, the main thread enters the "while(true) { suspend() }" loop on startup. A button  onclick event handler calls resume().

Expected behavior is that clicking the "resume" button will print "resumed" and then "suspending" on the console, for each button click.

Actual behavior is that this only works the first time the button is clicked, subsequent clicks either have no effect, or you get the "RuntimeError: indirect call to null" error shown above.

The fibers API looks interesting, thanks for the pointer! I will take a look and see if it can work for our use case.

**Comment by Akaricchi** [comment]
Sounds like @msorvig just wants to suspend and yield to the browser continuously in a loop, and only ever resume execution from a JS event handler. Fibers aren't useful in this case, they're mostly intended for intra-program asynchrony & cases where you might want multiple stacks/execution contexts with overlapping lifetimes. They're basically like threads, but cooperative rather than preemptive.

In theory this approach seems sound, but apparently something goes awry on the second iteration of the loop. Not quite sure what from just looking at the code. If I had to guess: maybe make sure you are not somehow calling the same `wakeUp` callback instance more than once?

**Comment by Akaricchi** [comment]
@msorvig I found your issue - the problem is that `qt_resume` directly calls the `wakeUp` function, which will continue executing the loop in the very same call stack, eventually calling into `qt_suspend` and `Asyncify.handleSleep`. If you build with assertions you should see a console error about `qt_resume` changing asyncify state even though it's missing from `ASYNCIFY_IMPORTS`.

Adding it to `ASYNCIFY_IMPORTS` won't fit it, however; `handleSleep` just can't deal with such recursion. The good news is that you can work around that by simply doing this instead of calling `Module.qtWakeUp` directly:

```js
setTimeout(Module.qtWakeUp);
```

**Comment by kripken** [comment]
I think there's a simpler way to do this, that avoids the `qt_resume` problem @Akaricchi identified:
```cpp
#include <stdio.h>
#include <emscripten.h>

extern "C" {

EM_JS(void, qt_suspend, (), {
    return Asyncify.handleSleep(function(wakeUp) {
        Module.resume = wakeUp;
    });
});

int main()
{
    while (true) {
        printf("suspending - press resume button to wake \n");
        qt_suspend();
        printf("resumed \n");
    }
    return 0;
}

}
```
```html
<html>
<head>
    <meta charset="utf-8"/>
</head>
<body onload>
    <div>
        asyncify suspend / resume (check console output)
    </div>
    <button onclick="Module.resume()">Resume</button>
    <script src="a.out.js"></script>
</body>
</html>
```
The wakeUp call is meant to be called from JS, not from other wasm code. So just calling it when the button is pressed will work, as that HTML does. With that I can press the button multiple times.

**Comment by msorvig** [comment]
@Akaricchi Thanks for the setTimeout suggestion. That works around the problem in the Qt implementation as well.

@kripken Looks like the example can indeed be simplified. The actual use case in Qt is however more complex and we need to support wakeups from wasm code.

**Comment by kripken** [comment]
I opened #10641 with a new assertion to catch this case, + docs that explain the issue + suggest the workaround @Akaricchi pointed out. Hopefully that helps avoid problems in the future.

**Comment by femski** [comment]
I am struggling with the same thing. It seems when you set

Module.resume= wakeUp;

in one thread - that variable/function pointer is in the local address space of that thread (Module).

If I call resume from another thread it does not see the Module.resume - so you can't wakeup one thread from another (even if you use you setTimeout(resume))

Is this correct ? How do I wakeup/resume one thread from another?

**Comment by kripken** [comment]
Do you mean a thread as in pthreads? I think that won't just work, as the JS runtime is not shared between workers, each worker has its own. We'd need to message between the workers somehow. There isn't support for asyncify changing threads like that yet.

**Comment by femski** [comment]
Yes, I mean two pthreads running in separate workers.  Most runloops are implements using pipes - which will requires filesystem work as you mentioned. So I guess I have to find a workaround for now.

**Comment by msorvig** [comment]
As a follow-up, would it be possible add API to Emscripten which covers this use-case? Something like 
```
bool emscripten_asyncify_suspend()
bool emscripten_asyncify_resume()
bool emscripten_asyncify_can_suspend()
```
The bool return value would indicate whether the suspend actually took place, or can take place.

**Comment by kripken** [comment]
@msorvig IIUC, suspend can be the same as written earlier,
```cpp
EM_JS(void, suspend, (), {
    return Asyncify.handleSleep(function(wakeUp) {
        Module.resume = wakeUp;
    });
});
```
and resuming would be done by JS calling `Module.resume()`. But I don't think we can do `resume` in C - that's the problem discussed earlier, you would have extra things on the stack when starting a rewind, which we just added an assertion to prevent confusion about. (Is there any benefit to resuming from C though? Seems like you want to resume from JS, so you call into C to do it - why not just call `Module.resume` directly?)

What would `can_suspend` check?

**Comment by msorvig** [comment]
The implementation of these primitives is indeed simple (once you know the setTimeout trick), so the main benefit is that you can stay in C emscripten_ API land and not have to write JavaScript code against the Asyncify API. For my use case I'm happy to not use JavaScript at all, when possible.

The resume() implementation can resume via setTimeout() (and should perhaps be named differently to indicate that the resume happens at some later point after it returns).

can_suspend would check some internal state (I maintain a bool in my implementation) and return false if a call to suspend() at that point would fail. It would also return false if the app was built without asyncify support.

The usefulness of the bool return values may be a bit limited. In the case of Qt we would use them  primarily to print better warnings for the application developer, and then exit().

**Comment by kripken** [comment]
> can_suspend would check some internal state (I maintain a bool in my implementation) and return false if a call to suspend() at that point would fail. 

What could cause it to fail? I'm missing something here.

**Comment by msorvig** [comment]
> > can_suspend would check some internal state (I maintain a bool in my implementation) and return false if a call to suspend() at that point would fail.
> 
> What could cause it to fail? I'm missing something here.

Yes, that was not completely clear. I'm thinking of the recursive case here, where suspend() (or emscripten_sleep() has been called, and a new call to suspend() is triggered by e.g. an event callback. (bug reported in https://github.com/emscripten-core/emscripten/issues/10375)

**Comment by kripken** [comment]
I see, thanks @msorvig 

After thinking on this, it seems like such new APIs can be implemented at the user level pretty easily:

```javascript
function doSleep(resume) {
  Module.resume = resume;
}
function canResume() {
  return !!Module.resume;
}
function doResume() {
  var resume = Module.resume;
  Module.resume = null;
  // Maybe also do a setTimeout(0) if this can be
  // called from compiled code, but that adds
  // unnecessary overhead to the normal case of
  // this being called from a JS callback.
  resume();
}
```

and these would be used from C as

```cpp
EM_JS(void, suspend, (), {
    return Asyncify.handleSleep(doSleep);
});

// ..

  suspend();
```

and to resume, the JS callback would call `doResume()`.

Is that right?

I'm unsure if it makes sense to add this to emscripten itself. It feels like a small but useful userspace library to me. Open to other opinions though.
