### ISSUE TITLE
Extending c++ class with a parameterized constructor using Embind

### ISSUE THREAD

**Issue by mgoulao** [emscripten-core/emscripten#10548]
I'm trying to extend a non-abstract method from a Class with a parameterized constructor using Embind. But I couldn't find any [example](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#non-abstract-virtual-methods) or [test](https://github.com/emscripten-core/emscripten/blob/5d5e2968b2f419fcd49ad767852020eb2f1e2c47/tests/embind/embind_test.cpp#L1281) where the Base class has a parameterized constructor. I have tried to find any useful information at the [bind.h API reference](https://emscripten.org/docs/api_reference/bind.h.html#classes) but I wasn't successful.

I don't know if this is currently possible, but here is a simple example of what I'm trying to achieve:

```#include <emscripten/bind.h>
#include <iostream>

using namespace emscripten;

class A {
  public:
    int _a;
    A(int a) {
	_a = a;
    }
    virtual ~A(){};
    virtual void invoke() {
      std::cout << "Hello from Base Class\n";
    }
};

class AWrapper : public wrapper<A> {
  public:
    EMSCRIPTEN_WRAPPER(AWrapper);
    AWrapper(int a) : A(a){};
    void invoke() {
        return call<void>("invoke");
    }
};

EMSCRIPTEN_BINDINGS(A) {
    class_<A>("A")
      .constructor<int>()
      .allow_subclass<AWrapper>("AWrapper")
      .function("invoke", optional_override([](A& self) {
                            return self.A::invoke();
                          })
      );
}
```
index.js

```
const Module = require("./wasm.js");

Module.onRuntimeInitialized = () => {
    const A = Module.A.extend("A", {
        invoke: () => {
            console.log("Hello from JS");
        }
    });

    const a = new A();
    a.invoke();
};
```

And this is the compilation error I receive:

``` error: type 'A' is not a direct or virtual base of 'AWrapper'
    AWrapper(int a) : A(a){};
                      ^
In file included from index.cpp:1:
/.../emscripten/bind.h:1087:15: error: no matching constructor for initialization of 'A'
            : T(std::forward<Args>(args)...)
```

**Comment by waywardmonkeys** [comment]
Where you have this:

```
      .allow_subclass<AWrapper>("AWrapper")
```

Try this:

```
      .allow_subclass<AWrapper>("AWrapper", constructor<int>())
```

**Comment by mgoulao** [comment]
It doesn't work. em++ gives the following error `type 'A' is not a direct or virtual base of 'AWrapper'`. Which makes sense, since I am inheriting the wrapper\<A\> and it has the following definition `class wrapper : public T, public internal::WrapperBase`
Using the version 1.39.8
