### ISSUE TITLE
Does emscripten support blocking on io?

### ISSUE THREAD

**Issue by anderspitman** [emscripten-core/emscripten#10545]
I originally asked this in a StackOverflow question [here](https://stackoverflow.com/q/60215750/943814), but haven't found a solution yet.

I'm running a C tool compiled to wasm using emscripten. The tool works on very large files (so obviously I have to run in a WebWorker for wasm). When running this tool normally on the CLI, often operations stream the results and terminate the program early once enough data has been returned. For example you might run:

./tool <input-file> | head -n 100

The tool would terminate after it detects stdout has been closed by head, effectively only reading a small portion of the input.

The problem is that stdout with emscripten appears to be asynchronous (by overriding Module.print), so the tool runs to completion every time. Is there a way to make it block on stdout so I can only read as much as I need and then terminate the tool?

I know this can be tricky because the browser is a very async environment. Ways I've seen similar things implemented before often involve something like a callback provided on the Module.print method, so you can inform the caller when you're ready for more data.

**Comment by sbc100** [comment]
Are you modelling both the communicating programs (tool, and head here as wasm modules? 
(If so you need them both to be able to block while the other runs)

Are they sharing memory?

Are you trying to run on the web or is node your target?

Emscripten does support "blocking" on the web via asyncify (its doesn't really block the allows the program to suspend and resume).    So you could compile both your programs with asyncify and have them communicate via some kind of fifo JS buffer between them.  However, emscripten doesn't really have any concept of multiple programs so you'd have glue them together your self.

Doing this in WebWorkers isn't necessarily the answer as WebWorkers also have limited ability to block (for example you still have to yield to event loop if you want PostMessage to work).
