### ISSUE TITLE
.js file complied by CMakeLists.txt doesn't work in html file

### ISSUE THREAD

**Issue by For-thewin** [emscripten-core/emscripten#10578]
Here is my demo .cpp.
```
#include <iostream>
#include <emscripten/bind.h>
using namespace emscripten;
void setDexel(int x, int y)
{
	std::cout<<x<<" "<<y<<std::endl;
}
EMSCRIPTEN_BINDINGS(my_module)
{
	function("setDexel", &setDexel);
}
```
When i use the command line "emcc --bind -o test.js test.cpp" to get test.js. and i call its funciton "setDexel", which works.
But i use the CMakeLists file to complier and get the test.js. The function "setDexel" doesn't work and the error is "Module.setDexel is not a function"

Here is my CmakeLists.txt

CMAKE_MINIMUM_REQUIRED(VERSION 2.8.0)
project(test)
add_definitions("-std=c++11")
add_executable (test test.cpp)
SET_TARGET_PROPERTIES(test PROPERTIES LINK_FLAGS "--bind -O3")

So is there something problem with my CmakeLists.txt? I can get the .js file and .wasm file. But i can't its function.

**Comment by sbc100** [comment]
Can you post the full link command that cmake produces (ninja -v / make VERBOSE=1)?   Do you get a link failure or a runtime failure?

**Comment by For-thewin** [comment]
> Can you post the full link command that cmake produces (ninja -v / make VERBOSE=1)? Do you get a link failure or a runtime failure?
Thanks a lot.
I use command line "emcmake cmake XXX" to get Makefile and continually use "mingw32-make" . I don't get a link failure and i can get .js file and a .wasm file. But they are smaller than them compiled by another way "emcc --bind -o test.js test.cpp ". I indeed get a runtime failure which is "Module.setDexel is not a function".

**Comment by sbc100** [comment]
What I mean is what is the link command produced when you run `make`?  I am looking for the full command line that should include the `--bind` etc on it.

**Comment by For-thewin** [comment]
Sorry. Here is the the link command produced when I run "mingw32-make" in my cmd.
[ 50%] Linking CXX executable TestArrayCmakeDemo.js
[100%] Built target TestArrayCmakeDemo

Well i add the "--bind" in my CmakeLists.txt 
SET_TARGET_PROPERTIES(TestArrayCmakeDemo PROPERTIES LINK_FLAGS "--bind -O3")
I am not sure does it work？ Is this a wrong way?
Thanks a lot.

**Comment by sbc100** [comment]
make is hiding the command line from you by default.   You can `VERBOSE=1` to see the actual link   (you will need to remove TestArrayCmakeDemo first so its forced to relink).

**Comment by For-thewin** [comment]
Thanks for your advice; Here is my whole procedure.

G:\yanershang\WebAssembly\test\test_array_cmake_demo>emcmake cmake VERBOSE=1 G:\
yanershang\WebAssembly\test\test_array_cmake_demo
-- Configuring done
-- Generating done
-- Build files have been written to: G:/yanershang/WebAssembly/test/test_array_c
make_demo

G:\yanershang\WebAssembly\test\test_array_cmake_demo>mingw32-make
Scanning dependencies of target TestArrayCmakeDemo
[ 50%] Building CXX object CMakeFiles/TestArrayCmakeDemo.dir/TestArrayCmakeDemo.
cpp.o
[100%] Linking CXX executable TestArrayCmakeDemo.js
[100%] Built target TestArrayCmakeDemo

Well, there seems no full command line?

**Comment by sbc100** [comment]
You need to add the `VERBOSE=1` to the make command (`mingw32-make`), not the `cmake` command.

There is also a cmake command to enable this by default: https://cmake.org/cmake/help/latest/variable/CMAKE_VERBOSE_MAKEFILE.html

**Comment by For-thewin** [comment]
Sorry, i am really a noob. So maybe here is the full command line.

G:\yanershang\WebAssembly\test\test_array_cmake_demo>mingw32-make VERBOSE=1

F:\cmake-3.13.0-win64-x64\bin\cmake.exe -SG:\yanershang\WebAssembly\test\test_ar
ray_cmake_demo -BG:\yanershang\WebAssembly\test\test_array_cmake_demo --check-bu
ild-system CMakeFiles\Makefile.cmake 0

F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_progress_start G:\yanershang\We
bAssembly\test\test_array_cmake_demo\CMakeFiles G:\yanershang\WebAssembly\test\t
est_array_cmake_demo\CMakeFiles\progress.marks

mingw32-make -f CMakeFiles\Makefile2 all

mingw32-make[1]: Entering directory 'G:/yanershang/WebAssembly/test/test_array_c
make_demo'

mingw32-make -f CMakeFiles\TestArrayCmakeDemo.dir\build.make CMakeFiles/TestArra
yCmakeDemo.dir/depend

mingw32-make[2]: Entering directory 'G:/yanershang/WebAssembly/test/test_array_c
make_demo'

F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_depends "MinGW Makefiles" G:\ya
nershang\WebAssembly\test\test_array_cmake_demo G:\yanershang\WebAssembly\test\t
est_array_cmake_demo G:\yanershang\WebAssembly\test\test_array_cmake_demo G:\yan
ershang\WebAssembly\test\test_array_cmake_demo G:\yanershang\WebAssembly\test\te
st_array_cmake_demo\CMakeFiles\TestArrayCmakeDemo.dir\DependInfo.cmake --color=
mingw32-make[2]: Leaving directory 'G:/yanershang/WebAssembly/test/test_array_cm
ake_demo'

mingw32-make -f CMakeFiles\TestArrayCmakeDemo.dir\build.make CMakeFiles/TestArra
yCmakeDemo.dir/build

mingw32-make[2]: Entering directory 'G:/yanershang/WebAssembly/test/test_array_c
make_demo'

mingw32-make[2]: Nothing to be done for 'CMakeFiles/TestArrayCmakeDemo.dir/build
'.

mingw32-make[2]: Leaving directory 'G:/yanershang/WebAssembly/test/test_array_cm
ake_demo'

[100%] Built target TestArrayCmakeDemo

mingw32-make[1]: Leaving directory 'G:/yanershang/WebAssembly/test/test_array_cm
ake_demo'

F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_progress_start G:\yanershang\We
bAssembly\test\test_array_cmake_demo\CMakeFiles 0

**Comment by sbc100** [comment]
I still don't see the actually command there that is building TestArrayCmakeDemo.   Maybe try the CMAKE_VERBOSE_MAKEFILE cmake option.

**Comment by For-thewin** [comment]
Thank you for your advice. I add SET( CMAKE_VERBOSE_MAKEFILE on ) in my CmakeLists.txt. and Here is the command line. And there exists "--bind".

G:\yanershang\WebAssembly\test\test_array_cmake_demo>mingw32-make
F:\cmake-3.13.0-win64-x64\bin\cmake.exe -SG:\yanershang\WebAssembly\test\test_ar
ray_cmake_demo -BG:\yanershang\WebAssembly\test\test_array_cmake_demo --check-bu
ild-system CMakeFiles\Makefile.cmake 0

F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_progress_start G:\yanershang\We
bAssembly\test\test_array_cmake_demo\CMakeFiles G:\yanershang\WebAssembly\test\t
est_array_cmake_demo\CMakeFiles\progress.marks
mingw32-make -f CMakeFiles\Makefile2 all

mingw32-make[1]: Entering directory 'G:/yanershang/WebAssembly/test/test_array_c
make_demo'
mingw32-make -f CMakeFiles\TestArrayCmakeDemo.dir\build.make CMakeFiles/TestArra
yCmakeDemo.dir/depend
mingw32-make[2]: Entering directory 'G:/yanershang/WebAssembly/test/test_array_c
make_demo'

F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_depends "MinGW Makefiles" G:\ya
nershang\WebAssembly\test\test_array_cmake_demo G:\yanershang\WebAssembly\test\t
est_array_cmake_demo G:\yanershang\WebAssembly\test\test_array_cmake_demo G:\yan
ershang\WebAssembly\test\test_array_cmake_demo G:\yanershang\WebAssembly\test\te
st_array_cmake_demo\CMakeFiles\TestArrayCmakeDemo.dir\DependInfo.cmake --color=
mingw32-make[2]: Leaving directory 'G:/yanershang/WebAssembly/test/test_array_cm
ake_demo'
mingw32-make -f CMakeFiles\TestArrayCmakeDemo.dir\build.make CMakeFiles/TestArra
yCmakeDemo.dir/build

mingw32-make[2]: Entering directory 'G:/yanershang/WebAssembly/test/test_array_c
make_demo'
[ 50%] Linking CXX executable TestArrayCmakeDemo.js
F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_link_script CMakeFiles\TestArra
yCmakeDemo.dir\link.txt --verbose=1

**G:\yanershang\WebAssembly\emsdk-master\upstream\emscripten\em++.bat  --bind -O
  @CMakeFiles\TestArrayCmakeDemo.dir\objects1.rsp  -o TestArrayCmakeDemo.js**

mingw32-make[2]: Leaving directory 'G:/yanershang/WebAssembly/test/test_array_cm
ake_demo'

[100%] Built target TestArrayCmakeDemo
mingw32-make[1]: Leaving directory 'G:/yanershang/WebAssembly/test/test_array_cm
ake_demo'
F:\cmake-3.13.0-win64-x64\bin\cmake.exe -E cmake_progress_start G:\yanershang\We
bAssembly\test\test_array_cmake_demo\CMakeFiles 0

**Comment by sbc100** [comment]
Ok so its not the compiler flags.   Are you sure the same program works when you build it directly from the command line?

**Comment by For-thewin** [comment]
Well it's weired. I am sure the .js file which i build directly from the command line works some times. But now there is the same error "TypeError: myMoudle.setDexel is not a function". Here is my program.

.cpp file
#include <iostream>
#include <emscripten/bind.h>
using namespace emscripten;

void setDexel(int x, int y)
{
	std::cout<<x<<" "<<y<<std::endl;
}

EMSCRIPTEN_BINDINGS(my_module)
{
	function("setDexel", &setDexel);
}

.html file (and i open it in firefox)
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <script src="TestArrayCmakeDemo.js"></script>
    <script>
        var myMoudle = Module;
        myMoudle.setDexel(1,2);
    </script>

</body>
</html>
