### ISSUE TITLE
Closure compiler tries to run x86-64 executable on ARM64 Linux

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#10582]
Testing with an `sdk-upstream-master-64bit` build from a couple days ago on Ubuntu 18.04 Aarch64 in Windows 10 WSL, I've found that the closure compiler is trying to run an x86-64 Linux executable which fails:

```
/home/brion/src/emsdk/emscripten/master/node_modules/google-closure-compiler-linux/compiler: 2: /home/brion/src/emsdk/emscripten/master/node_modules/google-closure-compiler-linux/compiler: Syntax error: "(" unexpected
/home/brion/src/emsdk/emscripten/master/node_modules/google-closure-compiler-linux/compiler: 1: /home/brion/src/emsdk/emscripten/master/node_modules/google-closure-compiler-linux/compiler: ELF: not found
shared:WARNING: Command '['/home/brion/src/emsdk/node/12.9.1_64bit/bin/node', '--max_old_space_size=8192', '/home/brion/src/emsdk/emscripten/master/node_modules/.bin/google-closure-compiler', '--version']' returned non-zero exit status 2 shared:ERROR: closure compiler ("['/home/brion/src/emsdk/node/12.9.1_64bit/bin/node', '--max_old_space_size=8192', '/home/brion/src/emsdk/emscripten/master/node_modules/.bin/google-closure-compiler'] --version") did not execute properly!

$ file  /home/brion/src/emsdk/emscripten/master/node_modules/google-closure-compiler-linux/compiler
/home/brion/src/emsdk/emscripten/master/node_modules/google-closure-compiler-linux/compiler: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=11e21f974f6ba9bcfe417548deb1bc36b2b4bcaa, with debug_info, not stripped
```

It should presumably be running the JS version here since there's no matching native build.

Installing a Java runtime (`apt-get install default-jre`) doesn't seem to have any effect (eg it doesn't switch to using the Java version automatically either).

**Comment by sbc100** [comment]
This sounds like this is upstream bug in the npm google-closure-compiler package: 
 https://www.npmjs.com/package/google-closure-compiler.  I imagine the authors never envisaged non-x86 envrionments.
 
Specifically regarding the java version, they have code in the npm module that attempts to use the native version on the demand and fall back to java and then JS.    In emscripten, we do try to put java on the path and set JAVA_HOME I think should be enough to have closure choose the java version.   If we are not going that correctly we may be able to fix that.

I think that the official stance here has to be that running the emscripten toolchain on non-amd64 architectures is not officially supported.    I imagine you are sole user of emsdk on arm-linux so I'm afraid it will probably be on you to maintain any support here.   As long it doesn't effect the mainline code too much I'm sure we would accept patches to keep it working if you want to contribute them.

**Comment by brion** [comment]
Yep, I know it's a niche use case and I'll probably have to fix it myself. :) I'll do some more testing and see if I can find a simple fix or workaround (upstream if necessary).
