### ISSUE TITLE
Users want to do their own -s parameters as well

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#10580]
In our own JS library code, we want to define custom JS library ifdefs, e.g. in our `library_x.js` files we have a need to add compile-time preprocessing directives that are different from Emscripten provided settings.

What do you think would be the best way to achieve this kind of support? The only way I can currently think of would be a new flag e.g. `-sx MY_CUSTOM_PARAMETER=1` that is identical to `-s`, but whatever is specified there would be added directly as-is as new options to the Settings registry?

**Comment by juj** [comment]
Or perhaps if we think of `-Dfoo=val` is for C/C++ code, perhaps `-jsDfoo=val` would define a value in JS library code?

**Comment by sbc100** [comment]
Hmm, I like the idea of passing `-D` defines to the JS preprocessor.

**Comment by sbc100** [comment]
Seems like a natural extension.   I also wonder if we should try to convert to actually using the C pre-processor, rather than a custom pre-processor.  Does our custom one do special things we rely on?

**Comment by juj** [comment]
I don't want to pass all `-D` defines to JS, not because JS code would break, but because random compiled C/C++ code might start to break once one adds defines that are meant for JS code only. That would be a time bomb just like the current `-l` directive was (and the current `-lGL` bug)

Also, JS defines can be complex JS things like arrays and strings and so on, which a C compiler would not necessarily parse?

**Comment by juj** [comment]
>  I also wonder if we should try to convert to actually using the C pre-processor

I have been a big big proponent of this, being able to do C macros in JS library files would be a huge thing for combining readability with code size optimizations. I did this work a couple of times in the past (there's a closed PR somewhere that fed all JS lib files to `clang -E`), but we did not come to a consensus unfortunately to land them.

**Comment by sbc100** [comment]
OK, I guess if we don't want them overlap then I'm ok with with `-jsDfoo=bar` I think.    JS macros a

I wonder if we should limit the effects of these macros to user JS code and keep our `-s` flags for controlling the system library behavior?  One good thing about the `-s` flags is that we have some control over their use and can warn users when they are using old/invalid settings.  A C-like macros system has no such protects.  For example we have no to report when a user mis-spells a `-D` macro... which I think is fine for user macro.  They are on their own with those.  But I wouldn't want that situation for flags that control the system libraries.

**Comment by VirtualTim** [comment]
I also really like this idea.
I've currently got 3 build configurations; UMD, ES6, and UMD+Node.js (plus debug/release/profiling options for each). I build by running a parameterised shell script which sets up some variables, does some some text replacement, then calls make. This ability would greatly simplify my build process.

**Comment by hujiajie** [comment]
Clang has flags like `-Xclang`, `-Xassembler`, `-Xlinker` to pass flags to the underlying compiler, assembler, linker, etc. Will it be more consistent by introducing `-Xjspreprocessor_or_whatever_else` and pass additional JS preprocessor flags via `-Xjspreprocessor_or_whatever_else -DFOOBAR=1`?

**Comment by briancullinan** [comment]
Why not just link the code using asm_js from a C file using the standard ifdef interface, why pass extra parameters to JS directly? I am thinking to convert some of my JS modules to .c files with the asm_js directive. I always liked that part about using assembly directly from C too. Sorry if this is off base, maybe I misunderstood.

**Comment by myzhan** [comment]
Still need this feature when I'm writing a js library.

**Comment by sbc100** [comment]
This was fixed in #10624.  In that PR the `-jsD` comment line flag was added.
