### ISSUE TITLE
Cannot catch exception after Asyncify.handleSleep()

### ISSUE THREAD

**Issue by woodser** [emscripten-core/emscripten#10584]
Hello,

I have an issue where JS calls a Module function which has a try...catch in C++.  Within the try, Asyncify.handleSleep() is called in EM_JS.  After returning to synchronous C++ execution, if an error is thrown in the proceeding C++, the catch block is not invoked, so the error is not handled, and the runtime shuts down.

How can errors be caught in C++ after using Asyncify, or can the runtime shutdown be detected or prevented?

In my case, it is acceptable that the original JS invocation blocks (i.e. no need to yield), because that thread is on a worker.

I am only using Asyncify to make network requests.  Perhaps there is a better way?

Thanks.

**Comment by kripken** [comment]
Good question! The way I think about asyncify is something like setjmp/longjmp, which is not aware of C++ exceptions, running destructors, and stuff like that. So I'm not sure offhand if the two should even be compatible, at least not with proper C++ destructors and so forth.

However, it's possible this is a specific separate bug, as it doesn't sound like you depend on destructors? If so then a small testcase might help investigate it.

**Comment by woodser** [comment]
I have created a [minimal example](https://github.com/woodser/wasm_fetch_example).

The error I want to recover from is [here](https://github.com/woodser/wasm_fetch_example/blob/15b8fc312f0e06a83509c20f50923c39a0fd60e2/src/main/cpp/wasm_bridge.cpp#L27):

```
void wasm_bridge::invoke_async_js_then_error(emscripten::val callback) {

  // call asynchronous js
  async_js();

  // suppose an error happens after
  try {
    throw runtime_error(string("Catch this!")); // <-- HOW TO CATCH OR RECOVER FROM THIS?
  } catch (...) {
    cout << "Error occurred!" << endl;
    callback(string("Callback payload after error"));
  }
}
```

The error above cannot be caught and recovered from (it shuts down the runtime) after `async_js()` is called which uses `Asyncify.handleSleep()`, whereas it is caught in JS if `async_js()` is not called.

**Comment by kripken** [comment]
Thanks for the testcase, but any chance you can reduce it some more? Looks like it has multiple files, uses embind - hard to get a quick picture of what's going on overall.

Taking the quoted part you posted here, I made this testcase:
```cpp
#include <emscripten.h>
#include <stdio.h>

int main() {
  emscripten_sleep(2);
  try {
    puts("throw");
    throw 5;
  } catch (...) {
    puts("caught");
  }
  puts("bye");
}
```
That works ok with `-s ASYNCIFY -fexceptions`, it pauses, then catches the exception, then exits. Perhaps you can extend that tiny testcase with stuff from yours, until it fails?

**Comment by kripken** [comment]
Oh, also - we recently fixed one or two things with asyncify - please try the latest release (1.39.9).

**Comment by woodser** [comment]
I was able to resolve this by passing `DISABLE_EXCEPTION_CATCHING` directly to the [cmake cxx flags](https://github.com/woodser/wasm_fetch_example/blob/4d74d50957039bc90acf9bba4f7092924f5e9976/CMakeLists.txt#L14).  Apparently the [target link property](https://github.com/woodser/wasm_fetch_example/blob/2349a18db02eb4557c62118920f19bc6ca781de2/CMakeLists.txt#L63) is not being used.

**Comment by kripken** [comment]
Oh, in that case this may be related to codegen happening at compile time rather than link, with the wasm backend. That does mean that exceptions flags need to be passed at both times. https://emscripten.org/docs/compiling/WebAssembly.html#backends
