### ISSUE TITLE
removeFunction does not work with the LLVM backend

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emscripten#10616]
I just realized that even though it isn't documented anywhere, [removeFunction is a noop](https://github.com/emscripten-core/emscripten/blob/93672a15ebd65a58b66c7528309325cca600b720/src/runtime_functions.js#L127) on the new LLVM backend, which makes it a no-go for [sql.js](https://github.com/kripken/sql.js) (we have had [issues](https://github.com/kripken/sql.js/pull/283) with this before).

In node, this issue is especially problematic, since it **kills the whole node process** when no more space is available.

<details>

```
<--- Last few GCs --->

[29681:0x476fa80]      910 ms: Mark-sweep 8.2 (11.1) -> 8.1 (11.4) MB, 6.6 / 0.2 ms  (average mu = 0.978, current mu = 0.088) memory pressure GC in old space requested
[29681:0x476fa80]      915 ms: Mark-sweep 8.1 (11.4) -> 7.9 (11.1) MB, 4.8 / 0.1 ms  (average mu = 0.962, current mu = 0.005) memory pressure GC in old space requested
[29681:0x476fa80]      920 ms: Mark-sweep 7.9 (11.1) -> 7.8 (10.9) MB, 4.8 / 0.1 ms  (average mu = 0.932, current mu = 0.015) memory pressure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2325ad8c0919 <JSObject>
    0: builtin exit frame: new constructor(aka Module)(this=0x316e6934ba71 <Object map = 0x20dd764a26e9>,0x316e6934b9d9 <Uint8Array map = 0xdeceb0824d9>,0x316e6934ba71 <Object map = 0x20dd764a26e9>)

    1: ConstructFrame [pc: 0x12c937a]
    2: StubFrame [pc: 0x13aa044]
    3: convertJsFunctionToWasm [0x24b07a92e6d9] [/home/ophir/Developpement/sql.js/dist/sql-wasm-debug.js:1468] [bytecode=0x335a...

FATAL ERROR: NewNativeModule Allocation failed - process out of memory
 1: 0x9bcac0 node::Abort() [node]
 2: 0x9bdc56 node::OnFatalError(char const*, char const*) [node]
 3: 0xb18eee v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb19269 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x10e0e03 v8::internal::wasm::WasmCodeManager::NewNativeModule(v8::internal::wasm::WasmEngine*, v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::shared_ptr<v8::internal::wasm::WasmModule const>) [node]
 6: 0x10eaba7 v8::internal::wasm::WasmEngine::NewNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, unsigned long, bool, std::shared_ptr<v8::internal::wasm::WasmModule const>) [node]
 7: 0x10c2033 v8::internal::wasm::CompileToNativeModule(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::ErrorThrower*, std::shared_ptr<v8::internal::wasm::WasmModule const>, v8::internal::wasm::ModuleWireBytes const&, v8::internal::Handle<v8::internal::FixedArray>*) [node]
 8: 0x10e6907 v8::internal::wasm::WasmEngine::SyncCompile(v8::internal::Isolate*, v8::internal::wasm::WasmFeatures const&, v8::internal::wasm::ErrorThrower*, v8::internal::wasm::ModuleWireBytes const&) [node]
 9: 0x1110da1  [node]
10: 0xb85415  [node]
11: 0xb85f32 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x134f199  [node]
Aborted (core dumped)
```

</details>

@kripken : Do you think removeFunction can be implemented soon ? Is it a lot of work ? I would be ready to work on a PR, but would probably need guidance.

**Comment by sbc100** [comment]
Looks related to https://github.com/emscripten-core/emscripten/issues/9903.

My advice once again would be try and avoid using addFunction/removeFunction at all if possible.

We could and should implement removeFunction, or at least assert there with the wasm backend.

However, I would recommend instead creating your own table of JS functions and managing that on the JS side.  On the native side you then have just one JS function that you would multiple all your callbacks through e.g. `callJSFunc(int it, ...)`.    I see several reasons for preferring this method.  One of which is that adding JS functions to a wasm table is currently fairly expensive.  

None of this is any excuse for the fact that we silently no-op in removeFunction.. we should do something about that for sure.

**Comment by lovasoa** [comment]
@sbc100: Why would that be required on the client side? If the technique you describe is more efficient than adding functions to a wasm table, than why doesn't emscripten use it by default in addFunction / removeFunction ?
I don't see any reason for this code to be on the library clients' side...

**Comment by sbc100** [comment]
emscripten itself doesn't use addFunction/removeFunction very much.  Its mostly used for dynamic code loading.  For example, where `dlsym` needs to return a function pointer.  I see it more as an emscripten internal detail rather than an API that user code is expected to be able to use.

In summary, we can and should fix removeFunction for you, but in the long run I was kind hoping find a way to hide this implementation detail.

**Comment by lovasoa** [comment]
Oh, this would be very bad news for sql.js ! The public interface of sql.js offers users to dynamically register javascript functions to use within the database and addFunction / removeFunction are at the core of this feature.

**Comment by sbc100** [comment]
I understand.  Don't worry,  we would not consider changing these or removing them unless there was a solution that worked for users such as sql.js.
