### ISSUE TITLE
em++ not respecting C++ std 

### ISSUE THREAD

**Issue by chhu** [emscripten-core/emscripten#10618]
Hi, I'm using a larger old C++ code that uses a global variable "rank" everywhere. Usually with g++ or clang I can simply add the std=c++98 or c++03 to avoid the conflict with std's rank. emcc does not respect this...

 em++ -std=c++98 test.cc

test.cc
````cpp
#include <iostream>
int rank = 0;

using namespace std;

int main() {
   return rank;
}
````

**Comment by sbc100** [comment]
This looks like an issue with libc++, the standard library from the llvm project that emscripten uses.

I see the same issue if I run the following command on my desktop to select libc++ rather than libstdc++:

```
$ clang -stdlib=libc++ -std=c++98 test.cc -c
test.cc:7:11: error: reference to 'rank' is ambiguous
   return rank;
          ^
test.cc:2:5: note: candidate found by name lookup is 'rank'
int rank = 0;
    ^
/usr/include/c++/v1/type_traits:1269:50: note: candidate found by name lookup is 'std::__1::rank'
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS rank
                                                 ^
1 error generated.
```

If there is a bug here it is with libc++, you might want to file a bug at https://bugs.llvm.org/

**Comment by chhu** [comment]
Hmm I compiled the code before with clang (not emscripten) without problems. Could it be that clang was using gnu's libc++ ?

**Comment by sbc100** [comment]
yes, clang will use the system default C++ library, so on most linux machines that means GNU stdc++.    On those systems you need to add `-stdlib=libc++` to get llvm's libc++.

**Comment by VirtualTim** [comment]
For future reference, I've had a lot of success with rextester for checking if a bug with the stdlib is emscripten specific.

[Compiling your code with `-std=c++98 -stdlib=libc++` gives the errors sb100 reported above.](https://rextester.com/FUAQZ66447)
