### ISSUE TITLE
Memory init file generation is ignored in wasm backend

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#10622]
```
emcc tests\hello_world.c --memory-init-file 1 -s USE_PTHREADS=1 -s WASM=1 -o a.html
```
generated a file `a.html.mem` in asm.js backend, but does not generate the memory initializer file in wasm backend, the directive `--memory-init-file 1` is getting silently ignored.

**Comment by kripken** [comment]
We should document this better, yeah. With wasm we never use a mem init file, as even with pthreads we have passive segments that let us embed them in the binary.

For wasm2js though we do obey that flag.

**Comment by tlively** [comment]
Maybe we should print a warning about the unused option?

**Comment by kripken** [comment]
Yes, docs + warning sounds good.
