### ISSUE TITLE
No way to get at popcnt

### ISSUE THREAD

**Issue by kg** [emscripten-core/emscripten#10634]
I'm trying to get access to the popcnt intrinsic and doing it via the x86 intrinsics header produces weird compile errors:

```
In file included from /home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/lib/clang/11.0.0/include/x86intrin.h:15:
In file included from /home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/lib/clang/11.0.0/include/immintrin.h:14:
/home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:50:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kate/Projects/mono-wasm/sdks/builds/toolchains/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:129:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
```

Emscripten refusing to support this would make sense, but the errors are strange and wasm is a 32-bit compile target with a popcnt instruction so it seems like there should be some way to get access to the intrinsic in a working build

**Comment by kripken** [comment]
I think clang has `__builtin_popcount` which works in wasm. Maybe the `mmintrin.h` header is missing some setup for that? cc @tlively

**Comment by tlively** [comment]
The problem with using `mmintrin.h` is that is uses a bunch of x86-specific builtin functions, like those in the error above. The best solution right now is to use `__builtin_popcount` directly.
