### ISSUE TITLE
I can't run HTML5Setup.sh successful

### ISSUE THREAD

**Issue by KGTyrael** [emscripten-core/emscripten#10636]
Under Windows 10 1909, when I run HTML5Setup.sh, it always show that`./emsdk: line 18: /c/Users/kyleh/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
`
I have already setup python3.8 and cmake. And I also add python to  the Path. I have tried to delete the emsdk folder, but it doesn't work.

I don't know what's wrong with it, Thanks for your help. 
![a1](https://user-images.githubusercontent.com/43983032/75816655-8f7aec80-5dd0-11ea-8aa1-48ae90220b8f.png)

**Comment by violacambie** [comment]
Hey @KGTyrael I had the same problem before. I solved it deleting the emsdk folder and running again the HTML5Setup.sh.
Toward the end looks like everything is successfully completed but an error apper:  Python PATH not found --skipping EPIC patches.
Did you find it?
