### ISSUE TITLE
EMScripten locateFile() not reading .WASM file after bundling with WebPack

### ISSUE THREAD

**Issue by skandonkumar** [emscripten-core/emscripten#10637]
I have converted my C library to WASM and wrapper JS using EMScripten. I also wrote my own JS library. I want to integrate both the libraries. I used Webpack to bundle my JS library including my Emscripten wrapper JS and added the WASM file using "file-loader" of WebPack. Initially, the Emscripten generated JS wrapper reads the WASM file using locateFile() method. But after bundling, the locate file is unable to locate the WASM file. Can someone please help me?

**Comment by brion** [comment]
I've had trouble with webpack's file-loader and .wasm files before; see comments on https://github.com/webpack/webpack/issues/6725 and related issues for some workarounds. I'm not sure what the most recommended way at present is.

**Comment by viroulep** [comment]
I struggled quite a bit having a working setup to import wasm compiled through Emscripten into a basic create react app (which uses webpack).
I managed to get it working by using the trick described in webpack/webpack#6725 (using `javascript/auto` in file-loader), but I also had to override the `locateFile` function used by the js file emitted by em++.
I gathered a MWE [here](https://github.com/viroulep/emscripten-webpack-cra) mainly for myself, but maybe it can help others having similar issues.

**Comment by spectras** [comment]
This comes from the generated loader not actually using `locateFile` from `Module` but its own internal `locateFile`, which is hard coded as `return scriptDirectory + path`.

**Comment by RReverser** [comment]
Now that both Webpack and we have support for `new URL(..., import.meta.url)` pattern, bundling with Webpack v5 should work out of the box, so closing this issue.

**Comment by noe** [comment]
The inconsistency between `Module.locateFile` and `new URL(..., import.meta.url)` is still there, isn't it?
