### ISSUE TITLE
Compiling with Boost requires manual download of headers

### ISSUE THREAD

**Issue by askuri** [emscripten-core/emscripten#10630]
I'm trying to compile a project that uses some boost libraries, such as phoenix and spirit. In prior versions of this project, these libs were not needed and the compilation went fine. I use cmake and added the `-s USE_BOOST_HEADERS=1` build option.

Now, the problem is that the boost libs are appearantly not found:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/martin/NetBeansProjects/emscripten_boost
make: ['make', 'emscripten_boost']
[ 50%] Building CXX object CMakeFiles/emscripten_boost.dir/wasm.cpp.o
/home/martin/NetBeansProjects/emscripten_boost/wasm.cpp:1:10: fatal error: 'boost/spirit/include/qi.hpp' file not found
#include <boost/spirit/include/qi.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
shared:ERROR: '/home/martin/Apps/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/martin/.emscripten_cache/wasm-obj/include -std=gnu++17 -c -DEMSCRIPTEN /home/martin/NetBeansProjects/emscripten_boost/wasm.cpp -Xclang -isystem/home/martin/Apps/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/emscripten_boost.dir/wasm.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
make[3]: *** [CMakeFiles/emscripten_boost.dir/build.make:63: CMakeFiles/emscripten_boost.dir/wasm.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/emscripten_boost.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/emscripten_boost.dir/rule] Error 2
make: *** [Makefile:118: emscripten_boost] Error 2
```

As suggested [here](https://stackoverflow.com/a/57082748/11836707), I copied/linked my system's boost libraries in `emsdk/upstream/emscripten/system/include/` and that made it work:
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/martin/NetBeansProjects/emscripten_boost
make: ['make', 'emscripten_boost']
[ 50%] Building CXX object CMakeFiles/emscripten_boost.dir/wasm.cpp.o
[100%] Linking CXX executable emscripten_boost.js
shared:INFO: (Emscripten: Running sanity checks)
system_libs:INFO: retrieving port: boost_headers from https://github.com/emscripten-ports/boost/releases/download/boost-1.70.0/boost-headers-1.70.0.zip                                                                     
system_libs:INFO: unpacking port: boost_headers
cache:INFO: generating port: libboost_headers.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libboost_headers.a" for subsequent builds)                                                              
root:INFO: building port: boost_headers
cache:INFO:  - ok
cache:INFO: generating system library: libc.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libc.a" for subsequent builds)                                                                            
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libcompiler_rt.a" for subsequent builds)                                                        
cache:INFO:  - ok
cache:INFO: generating system library: libc-wasm.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libc-wasm.a" for subsequent builds)                                                                  
cache:INFO:  - ok
cache:INFO: generating system library: libembind-rtti.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libembind-rtti.a" for subsequent builds)                                                        
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi-noexcept.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libc++abi-noexcept.a" for subsequent builds)                                                
cache:INFO:  - ok
cache:INFO: generating system library: libdlmalloc.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libdlmalloc.a" for subsequent builds)                                                              
cache:INFO:  - ok
cache:INFO: generating system library: libpthread_stub.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libpthread_stub.a" for subsequent builds)                                                      
cache:INFO:  - ok
cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libc_rt_wasm.a" for subsequent builds)                                                            
cache:INFO:  - ok
cache:INFO: generating system library: libsockets.a... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/libsockets.a" for subsequent builds)                                                                
cache:INFO:  - ok
 "/home/martin/Apps/emsdk/upstream/bin/wasm-ld" -o /tmp/emscripten_temp_8wTMVI/emscripten_boost.wasm --lto-O0 CMakeFiles/emscripten_boost.dir/wasm.cpp.o -L/home/martin/Apps/emsdk/upstream/emscripten/system/local/lib -L/home/martin/Apps/emsdk/upstream/emscripten/system/lib -L/home/martin/.emscripten_cache/wasm-obj /home/martin/.emscripten_cache/wasm-obj/libboost_headers.a /home/martin/.emscripten_cache/wasm-obj/libc.a /home/martin/.emscripten_cache/wasm-obj/libcompiler_rt.a /home/martin/.emscripten_cache/wasm-obj/libc-wasm.a --whole-archive /home/martin/.emscripten_cache/wasm-obj/libembind-rtti.a --no-whole-archive /home/martin/.emscripten_cache/wasm-obj/libc++abi-noexcept.a /home/martin/.emscripten_cache/wasm-obj/libdlmalloc.a /home/martin/.emscripten_cache/wasm-obj/libpthread_stub.a /home/martin/.emscripten_cache/wasm-obj/libc_rt_wasm.a /home/martin/.emscripten_cache/wasm-obj/libsockets.a --allow-undefined --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush -z stack-size=5242880 --initial-memory=524288000 --no-entry --max-memory=524288000 --global-base=1024
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/home/martin/.emscripten_cache/wasm-obj/generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
 "/home/martin/Apps/emsdk/upstream/bin/wasm-emscripten-finalize" --detect-features --global-base=1024 --check-stack-overflow /tmp/emscripten_temp_8wTMVI/emscripten_boost.wasm -o /tmp/emscripten_temp_8wTMVI/emscripten_boost.wasm.o.wasm
 "/home/martin/Apps/emsdk/upstream/bin/wasm-opt" --post-emscripten --inline-main --low-memory-unused --strip-debug --strip-producers --pass-arg=emscripten-sbrk-ptr@3952 emscripten_boost.wasm -o emscripten_boost.wasm --mvp-features
[100%] Built target emscripten_boost
```

Now, what makes me thinks this is a bug: appearantly, emscripten downloads the exact same libraries of boost and saves them in the cache, that i had just put into `emsdk/upstream/emscripten/system/include/`. So if emscripten has the ability to download the libs itself, why do I need to place them there manually? Am I missing something?

## Steps to reproduce
1. Download my sample code and extract it 
[emscripten_boost.zip](https://github.com/emscripten-core/emscripten/files/4277891/emscripten_boost.zip).
2. delete the user's .emscripten_cache and .emscripten_ports directories. On Ubuntu: `~/.emscripten_cache` and `~/.emscripten_ports`.
3. Make sure there is no boost libraries is `emsdk/upstream/emscripten/system/include` (there should not be one in the default installation I guess?)
4. run ./build_wasm.sh from a `source`d terminal. See the first error above.
5. To make it work, sym-link the boost libraries in `emsdk/upstream/emscripten/system/include/` as `boost`. Alternatively download it from here: https://www.boost.org/users/history/version_1_72_0.html and unpack the *boost* folder from the zip there.
6. re-run ./build_wasm.sh and see that it works.

## System information
Ubuntu 19.10
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.8
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 9dc84e9b02d1e402503906099d42fbae4da7d8d9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/martin/Apps/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by kripken** [comment]
cc @gabrielcuvillier

**Comment by askuri** [comment]
Found the problem. I was setting -s USE_BOOST_HEADERS=1 as a linker flag, but it also needs to be set as a compiler option when using the new backend. I guess that is the case for all ports. More information on when to set -s flags for the linker or the compiler are in the header of this file: https://github.com/emscripten-core/emscripten/blob/master/src/settings.js

I have changed my CMake file:
```
...
set_target_properties(prolog_bfs PROPERTIES COMPILE_FLAGS "-s USE_BOOST_HEADERS=1 -s DISABLE_EXCEPTION_CATCHING=0" LINK_FLAGS "--bind --emrun -s TOTAL_MEMORY=500MB -s USE_BOOST_HEADERS=1 -s DISABLE_EXCEPTION_CATCHING=0")
```

**Comment by twopelu** [comment]
Is there any solution when using emcc, not cmake?

**Comment by askuri** [comment]
I don't have experience using emcc directly. Just a blind guess: have you tried just adding `-s USE_BOOST_HEADERS=1` as an option of your emcc command?

Please let me know if that does the trick, then I'll update my answer on [StackOverflow](https://stackoverflow.com/questions/15724357/using-boost-with-emscripten/60550627#60550627) also.

**Comment by twopelu** [comment]
> I don't have experience using emcc directly. Just a blind guess: have you tried just adding `-s USE_BOOST_HEADERS=1` as an option of your emcc command?
> 
> Please let me know if that does the trick, then I'll update [my answer on StackOverflow](https://stackoverflow.com/questions/15724357/using-boost-with-emscripten/60550627#60550627) also.

Thanks for your reply! :-)

I have tried but it doest not work, I have opened and issue: 

https://github.com/emscripten-core/emscripten/issues/10630

**Comment by twopelu** [comment]
> Found the problem. I was setting -s USE_BOOST_HEADERS=1 as a linker flag, but it also needs to be set as a compiler option when using the new backend. I guess that is the case for all ports. More information on when to set -s flags for the linker or the compiler are in the header of this file: https://github.com/emscripten-core/emscripten/blob/master/src/settings.js
> 
> I have changed my CMake file:
> 
> ```
> ...
> set_target_properties(prolog_bfs PROPERTIES COMPILE_FLAGS "-s USE_BOOST_HEADERS=1 -s DISABLE_EXCEPTION_CATCHING=0" LINK_FLAGS "--bind --emrun -s TOTAL_MEMORY=500MB -s USE_BOOST_HEADERS=1 -s DISABLE_EXCEPTION_CATCHING=0")
> ```

I'm trying with CMake using your example and I can't make it work either. Could you share it again with the CMake file updated please? Thanks in advance!

**Comment by askuri** [comment]
Skip step 5. That step becomes unnecessary when setting `-s USE_BOOST_HEADERS=1 ` as a linker flag also, because then the required files will be downloaded automatically.

This is the Cmake file in its current version and it works like that: https://github.com/LhKipp/Prolog_BFS/blob/master/CMakeLists.txt.wasm

If it still doesn't work, I think it's best to post your problem on StackOverflow. Add your code and the error message.

**Comment by twopelu** [comment]
> Skip step 5. That step becomes unnecessary when setting `-s USE_BOOST_HEADERS=1 ` as a linker flag also, because then the required files will be downloaded automatically.
> 
> This is the Cmake file in its current version and it works like that: https://github.com/LhKipp/Prolog_BFS/blob/master/CMakeLists.txt.wasm
> 
> If it still doesn't work, I think it's best to post your problem on StackOverflow. Add your code and the error message.

Thanks again, I have found the problem is because I'm using the locale Boost library that is not headers-only and it would require to be compiled and then included. It does not work "out-of-the-box" like lambda, for instance.

I have updated my other issue in GitHub and StackOverflow question and will continue discussion there to avoid confusion ;-)
