### ISSUE TITLE
I cant avoid this error: "cannot --separate-asm when emitting wasm, since not emitting asm.js"

### ISSUE THREAD

**Issue by NikolayMakhonin** [emscripten-core/emscripten#10646]
**Environment:**
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.8
clang version 11.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 9dc84e9b02d1e402503906099d42fbae4da7d8d9)
Target: x86_64-pc-windows-msvc
Thread model: posix
```

**hello_world.c:**
```c
int main() {
  return 1234567890;
}
```
**Command:**
```
emcc tests/hello_world.c -o tests/hello_world.html -s WASM=0 --separate-asm
```

**Error:**
```
shared:ERROR: cannot --separate-asm when emitting wasm, since not emitting asm.js
```

How can I use the `--separate-asm` flag?

---
**Update:**
I commented these lines on `emcc.py`
```py
      # if options.separate_asm:
      #   exit_with_error('cannot --separate-asm when emitting wasm, since not emitting asm.js')
```
the command work without errors, but it still not generate `*.asm.js` file

**Comment by kripken** [comment]
We don't emit an `.asm.js` file with the wasm backend and wasm2js, since it isn't asm.js code. We could still emit it on the side with a different suffix, but that isn't supported atm.

I'm curious what your use case is for separating out that code? Back in the asm.js days it was useful to split the code out, since asm.js was compiled AOT and the split helped the main JS get started earlier. With wasm2js though it's not asm.js anymore, and parses as normal JS, which has nice fast startup anyhow.

**Comment by NikolayMakhonin** [comment]
> We don't emit an `.asm.js` file with the wasm backend and wasm2js, since it isn't asm.js code. We could still emit it on the side with a different suffix, but that isn't supported atm.

I'm tried to use `-s WASM_BACKEND`
```
emcc tests/test.c -o tests/test2.js -s WASM=0 --separate-asm -s WASM_BACKEND=0
```
and I got many many such errors (in `v 1.39.8`):
```
error: unknown target triple 'asmjs-unknown-emscripten', please use -triple or -arch
shared:ERROR: 'l:/Work/_GIT/GitHub/emscripten/upstream/bin\clang.exe -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\include\libcxx -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\lib\libcxxabi\include -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\include\compat -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\include -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\include\libc -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\lib\libc\musl\arch\emscripten -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\local\include -Xclang -isystemE:\Users\Mika.SEA\.emscripten_cache\asmjs\include -c -Werror -D_XOPEN_SOURCE=700 -Wno-unused-result -Os -fno-builtin -Wno-return-type -Wno-parentheses -Wno-ignored-attributes -Wno-shift-count-overflow -Wno-shift-negative-value -Wno-dangling-else -Wno-unknown-pragmas -Wno-shift-op-parentheses -Wno-string-plus-int -Wno-logical-op-parentheses -Wno-bitwise-op-parentheses -Wno-visibility -Wno-pointer-sign -Wno-absolute-value -Wno-empty-body -Il:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\lib\libc\musl\src\internal -Il:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\lib\libc\musl\arch\js -DEMSCRIPTEN -mllvm -disable-llvm-optzns l:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\lib\libc\musl\src\complex\cargl.c-fno-inline-functions -Xclang -disable-O0-optnone -Xclang -isysteml:\Work\_GIT\GitHub\emscripten\upstream\emscripten\system\include\SDL -c -o d:\Temp\AppData\Local\Temp\emscripten_temp_7uendq5_\cargl.c.o -emit-llvm' failed (1)
```

but it work in `v 1.38.46`

> I'm curious what your use case is for separating out that code? 

I need to convert a small library from `C` to `JS`. But emscripten generates huge unused boilerplate code.
Now I achieved what I wanted without separate into `* .asm.js`. I deleted the unused code manually and using [terser](https://xem.github.io/terser-online/).

> With wasm2js though it's not asm.js anymore, and parses as normal JS, which has nice fast startup anyhow.

I did not know about wasm2js. I will try it, thanks.

**Comment by kripken** [comment]
> error: unknown target triple 'asmjs-unknown-emscripten'

That means some of the input files were compiled with fastcomp, and not the wasm backend. You need to rebuild those with the new compiler (the default changed backend at 1.39.0, so upgrading past that version might hit this issue). If you have things like libraries prebuilt to bitcode, you need to rebuild those too, do `make clean`, etc.

> I need to convert a small library from C to JS. But emscripten generates huge unused boilerplate code.

The `MINIMAL_RUNTIME` option might help you - it emits very minimal runtime support code. With the wasm backend, something like `-s WASM=0 -s MINIMAL_RUNTIME -Os ` should get you a pretty small JS file.

**Comment by sbc100** [comment]
You can't use `-s WASM_BACKEND=0` to disable the wasm backend.   The way to do this is to pointer emscripten at the fastcomp compiler.    With emsdk this means installing something like `latest-fastcomp`.
