### ISSUE TITLE
Atomics are miscompiled in wasm backend

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#10654]
Switching from fastcomp backend to wasm backend, atomics begun to fail,
```c++
#include <emscripten/emscripten.h>
#include <emscripten/threading.h>
#include <stdint.h>
#include <stdio.h>
int main()
{
    uint8_t a = 1;
    uint8_t b = 2;
    uint8_t c = emscripten_atomic_exchange_u8(&a, b);
    printf("%d %d %d\n", a, b, c);
    return 0;
}
```

```
em++ a.cpp -pthread -s USE_PTHREADS=1 -std=c++14 -o a.html
```
Running a.html fails with
```
exception thrown: RuntimeError: unaligned memory access,@http://localhost:6931/a.wasm:wasm-function[100]:0x7194
@http://localhost:6931/a.wasm:wasm-function[27]:0xa18
@http://localhost:6931/a.wasm:wasm-function[28]:0xaa7
Module._main@http://localhost:6931/a.js:3415:32
callMain@http://localhost:6931/a.js:3881:28
doRun@http://localhost:6931/a.js:3943:31
run/<@http://localhost:6931/a.js:3954:7
a.html:1246:19
RuntimeError: unaligned memory access a.wasm:29076:1
```

Disassembling says that a `i32.atomic.rmw.cmpxchg`
```
   (i32.atomic.rmw.cmpxchg
    (i32.const 4544)
    (i32.const 0)
    (i32.const 1)
```
whereas it should have generated `i8.atomic.rmw.cmpxchg`? Did not try other atomics, I wonder if they might have similar issues?

**Comment by kripken** [comment]
Good find, that does look wrong... the code for these is
```cpp
uint8_t emscripten_atomic_exchange_u8(void /*uint8_t*/* addr, uint8_t newVal) {
  return __c11_atomic_exchange((_Atomic uintptr_t*)addr, newVal, __ATOMIC_SEQ_CST);
}
uint16_t emscripten_atomic_exchange_u16(void /*uint16_t*/* addr, uint16_t newVal) {
  return __c11_atomic_exchange((_Atomic uintptr_t*)addr, newVal, __ATOMIC_SEQ_CST);
}
```
And indeed it doesn't look like it says the underlying type.

It's hard to find docs on this - best I can see is https://releases.llvm.org/7.0.0/tools/clang/docs/LanguageExtensions.html - does anyone know how to do an atomic load of a certain size in c11? cc @tlively

**Comment by tlively** [comment]
The problem here is the cast of `addr` to `uintptr_t*`, since `uintptr_t` is an i32 and therefore is expected to be aligned to 4 bytes. Just get rid of that cast and everything should be good. Although there's no reason to take `addr` as a `void*` when it could be a `uint8_t*`, either.
