### ISSUE TITLE
Declaring Module in --pre-js doesn't work with WASM=0

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#10664]
I have a [custom HTML shell](https://github.com/taisei-project/taisei/blob/master/emscripten/shell.html) and a single [JavaScript file](https://github.com/taisei-project/taisei/blob/master/emscripten/preamble.js) that I embed with `--pre-js`. The Module object is declared in the `--pre-js` file; the shell is completely JS free. This works fine with WASM, but if I try to use wasm2js (WASM=0), something like the following code is emitted into the HTML:

```js
var memoryInitializer = "taisei.html.mem";
memoryInitializer = Module.locateFile ? Module.locateFile(memoryInitializer, "") : memoryInitializer,
Module.memoryInitializerRequestURL = memoryInitializer;
var meminitXHR = Module.memoryInitializerRequest = new XMLHttpRequest;
meminitXHR.open("GET", memoryInitializer, !0),
meminitXHR.responseType = "arraybuffer",
meminitXHR.send(null);
var script = document.createElement("script");
script.src = "taisei.js",
document.body.appendChild(script)
```

This breaks because Module is only created in `taisei.js`.

**Comment by kripken** [comment]
I believe that code is added for the mem init file. You can disable it with `--memory-init-file 0` (but then it's embedded in the js).

In general the html code we inject will assume Module exists. If you prefer to define Module in the JS, you can avoid using the HTML shell option, and build to JS (then the HTML file is completely under your control).
