### ISSUE TITLE
How to optimize the wasm file compiled from C++?

### ISSUE THREAD

**Issue by binwang-neu** [emscripten-core/emscripten#10667]
How can I get a simple wasm file that contains only C ++ source file information and not system library information?

**Comment by kripken** [comment]
The standard way to do this is make a shared library, `-s SIDE_MODULE`. That will add relocations though and other support for dynamic linking.

If you just want to view the wasm, and not run it, build with `-c` and it will emit a wasm object file, without linking anything into it.

A hackish way that is useful for testing is to set `EMCC_LEAVE_INPUTS_RAW=1` in the environment; that simply doesn't link in system libraries. But it leaves all system support to you.

**Comment by B-doublemint** [comment]
Thank you sir, it works when I build the source file with -c. 
But I have a problem, the output wasm file can not be converted to wat file, and I want to read the information in wasm.

**Comment by B-doublemint** [comment]
> The standard way to do this is make a shared library, `-s SIDE_MODULE`. That will add relocations though and other support for dynamic linking.
> 
> If you just want to view the wasm, and not run it, build with `-c` and it will emit a wasm object file, without linking anything into it.
> 
> A hackish way that is useful for testing is to set `EMCC_LEAVE_INPUTS_RAW=1` in the environment; that simply doesn't link in system libraries. But it leaves all system support to you.

**Comment by B-doublemint** [comment]
I tried your third method, it's effective. But sometime it gives an error, when the source file doesn't contain main function.
The error info: wasm-ld: error: entry symbol not defined (pass --no-entry to supress): _start

**Comment by kripken** [comment]
wabt's wasm2wat should work on wasm object files to convert them to wat format.

About the third option, yeah, it's just an internal hack for testing purposes. You can hack up shared.py to add that flag to work around that issue locally.

**Comment by B-doublemint** [comment]
Thank you sir.
