### ISSUE TITLE
Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by xiyuyizhi** [emscripten-core/emscripten#10674]
the js file generated by emcc  runtime  error: Cannot read property 'close' of undefined

ua: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3947.100 Safari/537.36

use fastcomp mode

and the emcc params:

```
-s ENVIRONMENT=worker \
-Os \
-s MODULARIZE=1 \
-s EXPORT_NAME=m \
-s ALLOW_MEMORY_GROWTH=1 \
-s TOTAL_MEMORY=16777216 \
-s EXPORTED_FUNCTIONS='xxxxx' \
-s EXTRA_EXPORTED_RUNTIME_METHODS="['addFunction']" \
-s RESERVED_FUNCTION_POINTERS=40 \
```

**Comment by kripken** [comment]
This isn't enough information for us to help you. Can you provide the build that shows that error?
