### ISSUE TITLE
compiling opencv with version X of emscripten doesn't work in version Y for point releases.

### ISSUE THREAD

**Issue by graph** [emscripten-core/emscripten#10683]
for example I have opencv compiled in `emcc --version`of 1.39.8, but when I use 1.39.10 with the precompiled opencv, I get link errors. Using the same version 1.39.8 works as expected. This issue has been around for a long time and hasn't been resolved. It's preventing my team from using newer version of emscripten. We were stuck on a very old version for more than a year and recently upgraded and see the problem still exists.

**Comment by brion** [comment]
Note that emscripten's internals move pretty fast; it's not recommended to link together files built with different versions of emscripten as that often doesn't work. You should compile all code with the same compiler.

**Comment by tlively** [comment]
Also note that Emscripten does not use semantic versioning, so it's not expected that the output from one version will be compatible with output from a subsequent version, even if it's only the minor version number that changed.

**Comment by graph** [comment]
Can plans be made for a more stable binary format for .a files? My team is going to be stuck on version 1.39.8 for more than a year.

**Comment by sbc100** [comment]
The format of the `.a` files themselves and the `.o` files within them, is relatively stable.   I don't think changes to the file formats will be a problem.

I think you are probably going to be more effected by changes to emscripten APIs, right?  e.g. you compile some code against emscripten header in one SDK and then expect the object files to work in another SDK.   I don't think it realistic for us try do that.  We have limited resources and testing old object code against new SDK version is not realistic.  The best I think we can do is (a) try to limit API churn and (b) document API changes when we make them.

In your specific example, if you are stuck on a particular SDK version you should be fine right?  During that whole year or more nothing needs to change.   If / when you upgrade you SDK you need to make sure you rebuild all your code.  Sounds like for you it will be a rare even so you will be less impacted than somebody who updates every week.

**Comment by sbc100** [comment]
Having said all that there are many emscripten releases that dont' change any APIs at all, so in many cases you will get lucky and the pre-compiled code *might* just work.  Also, if your code doesn't use many APIs it might not need re-compiling.   Luckily you should get linker errors to tell you when you need to re-compile in most cases.
