### ISSUE TITLE
Stack buffer overrun vulnerability in websocket_to_posix_proxy

### ISSUE THREAD

**Issue by ganterich** [emscripten-core/emscripten#10684]
https://github.com/emscripten-core/emscripten/blob/318c0e24fa6e3d0ac8acd8fead7cac923d58767f/tools/websocket_to_posix_proxy/src/main.cpp#L55

The size of the "key" buffer is not passed to GetHttpHeader.
Clients can overwrite the stack by sending a header value that is longer than 128 bytes in the header "Sec-WebSocket-Key" which is potentially dangerous.

**Comment by juj** [comment]
Great find! Fixed in above PR, even if somewhat late - this fell through since I don't scour the bug tracker daily anymore :/
