### ISSUE TITLE
undefined symbol: glTexStorage2D

### ISSUE THREAD

**Issue by bojosos** [emscripten-core/emscripten#10698]
The build command I am running is:
emcc -std=c++17 -s USE_FREETYPE=1 (INCLUDES AND FILES) -s TOTAL_MEMORY=512MB -DEC_WEB -DEC_DEBUG -DNDEBUG -DGLFW_INCLUDE_ES3 -s SAFE_HEAP=1 -s ASSERTIONS=1 -s FULL_ES3=1 -s USE_GLFW=3 --preload-file res --preload-file lua --memory-init-file 0 -O3 -o bin/Web/build.html

I can see the function in the GLES3 headers so I assume it should work. All other functions work except this one which is essential for textures so what should I do?

**Comment by Akaricchi** [comment]
Does adding `-lGL` to the link flags help?

**Comment by juj** [comment]
Try adding `-s MAX_WEBGL_VERSION=2` as well to the build, I think none of those flags are set to imply WebGL 2 automatically.

**Comment by Akaricchi** [comment]
>I think none of those flags are set to imply WebGL 2 automatically.

Indeed. Perhaps `FULL_ES3` should imply it, or at least warn if WebGL 2 is not enabled?

**Comment by bojosos** [comment]
`-s MAX_WEBGL_VERSION=2` did fix it but I have just realized that TEXTURE_SWIZZLE does not work in WebGL :(

**Comment by kripken** [comment]
Good point @Akaricchi , even the docs say that option enables WebGL2 features, so it seems like it should ensure WebGL2 is supported. I opened #10718 now to continue that discussion.
