### ISSUE TITLE
invalid section id

### ISSUE THREAD

**Issue by B-doublemint** [emscripten-core/emscripten#10692]
Why the section id is 0x0c? The official document  doesn't record 0x0c.

**Comment by tlively** [comment]
This is the data count section ID, introduced in the [https://github.com/WebAssembly/bulk-memory-operations](bulk memory proposal). It is emitted into all WebAssembly object files, but should not be present in your final binary unless you have bulk memory enabled. Bulk memory should be enabled only if you manually enabled it or if you build with pthreads.

**Comment by B-doublemint** [comment]
I compile the C++ source files with '-c', because I want to get a simple wasm file which only contains the source file informations, instead of system libraries informations. But the simple wasm file can not be parsed due to invaild section id. How to deal with it?

**Comment by tlively** [comment]
You cannot instantiate and use an object file without first linking it into a final binary. Even if your engine supports the data count section, there is a bunch of other missing information in unlinked object files. You must link your objects.
