### ISSUE TITLE
Duplicate function address of an exported function

### ISSUE THREAD

**Issue by spsaxena** [emscripten-core/emscripten#10693]
Since there are duplicate function address of an exported function, so function pointer comparison fails.
emscripten : 1.39.7

Example to demonstrate the same 
https://github.com/spsaxena/emsc_issues/tree/master/dupFnAddr
Output
![image](https://user-images.githubusercontent.com/12669021/76597219-df795200-653a-11ea-82ad-6fe921f1e303.png)
[](url)

**Comment by kripken** [comment]
Please test this on the latest release (1.39.10), although I don't think we've done significant work in that period on this topic. @sbc100 ?

**Comment by spsaxena** [comment]
thanks for you response, its same behavior as tested with -
 
emcc (Emscripten gcc/clang-like replacement) 1.39.10 (commit 1bd7d547598f3fc74699c172f6c9c59a1e8484f1)

**Comment by awtcode** [comment]
@sbc100 , any comments on this?

**Comment by kripken** [comment]
I tested this now with latest master (upstream), and it passed for me:
```
>in fnA> passed, 0x3, 0x3
>in fnB> passed, 0x4, 0x4
--
call fnB>in fnB> passed, 0x4, 0x4
call fnB>in fnB> passed, 0x4, 0x4
call fnA>in fnA> passed, 0x3, 0x3
call fnB>in fnB> passed, 0x4, 0x4
call fnA>in fnA> passed, 0x3, 0x3
```
I used this build file on linux:
```
~/Dev/emscripten/emcc \
 side.cpp \
 -O1 \
 -s WASM=1 \
 -s SIDE_MODULE=1 \
 -s ASSERTIONS=1 \
 -s DEMANGLE_SUPPORT=1 \
 -s DISABLE_EXCEPTION_CATCHING=0 \
 -s BINARYEN=1 \
 -s BINARYEN_METHOD='native-wasm' \
 -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
 -o side.wasm

~/Dev/emscripten/emcc \
 main.cpp \
 -O1 \
 --embed-file side.wasm@side.wasm \
 -s WASM=1 \
 -s MAIN_MODULE=2 \
 -s EXPORTED_FUNCTIONS=@exports.json \
 -o a.js \
```

But it does fail on fastcomp. Were you testing there perhaps?

(We very strongly suggest people upgrade to upstream, as all fixes are happening there now.)

**Comment by spsaxena** [comment]
Yes I am using fastcomp and I do see it passes if we build with llvm as backend.

**Comment by kripken** [comment]
The bug is probably in the static data initialization code in fastcomp. I'm not sure it's worth fixing that as it's pretty tricky code, and risky this late in fastcomp's lifecycle. The good news though is that there is a workaround in source code, which I verified works here:
```
int  main()
{
    cmdsArray[0].fnptr = fnA;
    cmdsArray[1].fnptr = fnB;
```
That is, do not rely on the static initialization in the declaration of global variables, and instead initialize them with code.

**Comment by kripken** [comment]
I think this was fixed by https://github.com/emscripten-core/emscripten/pull/10741
