### ISSUE TITLE
Move wasm_simd128.h into upstream LLVM

### ISSUE THREAD

**Issue by sunfishcode** [emscripten-core/emscripten#10714]
The header wasm_simd128.h would be useful to wasm32-wasi and wasm32-unknown-unknown users, so it would be useful to move to upstream LLVM.

I [requested this earlier](https://github.com/emscripten-core/emscripten/pull/8559#issuecomment-490655318), and the conclusion was that this makes sense to do, but later. Since then, the SIMD proposal has advanced to Stage 3 and much more of the spec, and this wasm_simd128.h header file, is now stable and tested. And now, we have more users interested in experimenting with SIMD.

@tlively As the primary author of this file, would you be willing to submit a PR to LLVM for this?

Thanks!

**Comment by tlively** [comment]
Yes, this sounds fine. I'll make that PR in the next couple days.

**Comment by tlively** [comment]
It was a few more than a couple days, but this change is up for review at https://reviews.llvm.org/D76959.
