### ISSUE TITLE
Error from wasm-ld: Section too large

### ISSUE THREAD

**Issue by jlongster** [emscripten-core/emscripten#10719]
I'm experiencing an error which seems really obscure - I can't find any other issues about it but I found the error in the LLVM source. Let me try to explain, and hopefully someone might be able to shed some light on it? I know you probably won't have an answer, but any help debugging this would be helpful.

I'm compiling this project: https://github.com/libofx/libofx. That project depends on OpenSP: http://openjade.sourceforge.net/doc/index.htm

Some context: I've successfully compiled all of this before. I've been using a WebAssembly version of libofx for about 2 years. Today I updated Emscripten to generate a fresh build and how hitting these problems (version 1.39.10, git hash 1bd7d547598f3fc74699c172f6c9c59a1e8484f1)

I can successfully compile OpenSP with the following hacks:

```
emconfigure ./configure --disable-doc-build
sed -i -e 's/\/\* \#undef HAVE_NAMESPACE_STD \*\//\#define HAVE_NAMESPACE_STD/g' OpenSP-1.5.2/config.h
sed -i -e 's/\/\* \#undef HAVE_MEMMOVE \*\//\#define HAVE_MEMMOVE 1/g' OpenSP-1.5.2/config.h
sed -i -e 's/\#define ptrdiff_t long/\/*\#define ptrdiff_t  long\*\//g' OpenSP-1.5.2/config.h
cd OpenSP-1.5.2 && emmake make
```

Honestly, I came up with those hacks a long time ago and can't remember why they are needed, but it successfully compiles.

Then I try to run `./configure` in libofx but it fails. Here is my call to it:

```
emconfigure ./configure --without-iconv --with-opensp-includes=/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/generic --with-opensp-libs=/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs
```

I'm specifying where exactly OpenSP is. It fails with this error:

```
checking for libosp... no
configure: error: unable to link a test program, is OpenSP installed?
```

If I look in `config.log` I can see what's actually failing:

```
configure:17105: checking for libosp
configure:17140: /Users/james/tmp/emsdk/upstream/emscripten/em++ -o conftest -DIN_LIBOFX -g -O2 -I/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/generic   conftest.cpp -L/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs -losp  >&5
wasm-ld: error: ParserEventGeneratorKit.o: Section too large
```

If I dig down some more, I can find the direct call to `wasm-ld` that I can run to replicate the error:

```
$ /Users/james/tmp/emsdk/upstream/bin/wasm-ld  -o conftest /var/folders/kx/1gnshz117g378t2d7kwqg9_c0000gn/T/emscripten_temp/test_0.o -L/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs /Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs/libosp.a -L/Users/james/tmp/emsdk/upstream/emscripten/system/lib -L/Users/james/.emscripten_cache/wasm --allow-undefined --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024 --relocatable

wasm-ld: error: ParserEventGeneratorKit.o: Section too large
```
I tested ` ParserEventGeneratorKit.o` and it looks like a valid wasm module:

```
> let b = fs.readFileSync('./OpenSP-1.5.2/lib/.libs/ParserEventGeneratorKit.o')
undefined
> WebAssembly.validate(b)
true
```

This is the place in LLVM that generates the error: https://github.com/llvm/llvm-project/blob/bd4812776bc73ca27bf6c68629a20f03268cdd6e/llvm/lib/Object/WasmObjectFile.cpp#L221

I don't know what to infer from that code. It looks like it's an invalid wasm module, but why it is validating in node?

**Comment by tlively** [comment]
It would be helpful if you could find and share the call to emcc that
generates ParserEventGeneratorKit.o. It would also be useful if you could
share the preprocessed source of ParserEventGeneratorKit by adding -E to
that emcc call. That will let us reproduce and investigate the issue
locally. This sounds like something that shouldn't be too hard to fix once
we can reproduce it.

**Comment by jlongster** [comment]
Absolutely. I'm current rebuilding LLVM to debug it and I'm way out of my depth. I'm happy to provide whatever info needed to help fix! Working on that now.

**Comment by jlongster** [comment]
em++ call that generates it:

```
/Users/james/tmp/emsdk/upstream/emscripten/em++ -DHAVE_CONFIG_H -I. -I. -I.. -I../include -I../generic -g -O2 -MT ParserEventGeneratorKit.lo -MD -MP -MF .deps/ParserEventGeneratorKit.Tpo -c ParserEventGeneratorKit.cxx -o ParserEventGeneratorKit.o
```

Here is the preprocessed output: https://gist.github.com/jlongster/4b5a626a1ab4e540972ba9f214fa96f3

Do those look correct to you?

**Comment by tlively** [comment]
Yep, that looks reasonable, thanks! I'll take a look and see if I can reproduce the error in a bit. Perhaps @sbc100 would be interested in taking a look, too.

**Comment by sbc100** [comment]
Any chance you could attach the object file in question.  The error is coming from the object files reader in llvm

**Comment by jlongster** [comment]
Here is the object file: https://jlongster.com/s/ParserEventGeneratorKit.o

I'm happy to zip up all of the header and object files as well if that helps reproduce the error.

**Comment by sbc100** [comment]
My version of wasm-ld reads that object just fine:

```
$ wasm-ld ParserEventGeneratorKit.o -o foo.wasm --no-entry
$ 
```

Can you send me the library that contains it?

**Comment by jlongster** [comment]
I'm suspicious that this is a bug with the LLVM backend. I went back to an earlier version 1.38.2 because it added the ENVIRONMENT option and that's all I need. Looks like that version still defaults to the fastcomp backend. It compiled fine.

I have a working solution now at least, but let me know what else I can do to provide info for debugging this.

**Comment by sbc100** [comment]
If its a bug in the backend we would like to know about it and fix it because fastcomp is due to be removed soon.

**Comment by jlongster** [comment]
> Can you send me the library that contains it?

In which format? Want me to zip the entire thing up?

**Comment by sbc100** [comment]
I'm assuming ParserEventGeneratorKit.o is coming from a .a archive?   libosp.a?  Can you send me that file?

**Comment by jlongster** [comment]
I'm honestly not sure, I'm not too familiar with C/C++ toolchains. I thought .o were object files genereated from C/C++ files. For example:

```
OpenSP-1.5.2/lib(master)% ls ParserEventGeneratorKit.*
ParserEventGeneratorKit.cxx ParserEventGeneratorKit.lo  ParserEventGeneratorKit.o
```

And that .o file gets copied out into the `.libs` directory

**Comment by sbc100** [comment]
The failing command line that you posted:

```$ /Users/james/tmp/emsdk/upstream/bin/wasm-ld  -o conftest /var/folders/kx/1gnshz117g378t2d7kwqg9_c0000gn/T/emscripten_temp/test_0.o -L/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs /Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs/libosp.a -L/Users/james/tmp/emsdk/upstream/emscripten/system/lib -L/Users/james/.emscripten_cache/wasm --allow-undefined --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024 --relocatable
```

Doesn't contains any direct references to ParserEventGeneratorKit.o, so I'm assuming its within a library of object files.

**Comment by sbc100** [comment]
Can you send `/Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs /Users/james/projects/actual/packages/node-libofx/OpenSP-1.5.2/lib/.libs/libosp.a `

**Comment by jlongster** [comment]
Sure thing (had to recompile it): https://jlongster.com/s/libosp.a

**Comment by jlongster** [comment]
I'll just zip up the entire library. Here is OpenSP-1.5.2.zip: https://jlongster.com/s/OpenSP-1.5.2.zip

It contains all the compiled bits too. You should be able to unzip that, and copy this source code:

```
 /* confdefs.h */
 #define PACKAGE_NAME ""
 #define PACKAGE_TARNAME ""
 #define PACKAGE_VERSION ""
 #define PACKAGE_STRING ""
 #define PACKAGE_BUGREPORT ""
 #define PACKAGE_URL ""
 #define PACKAGE "libofx"
 #define VERSION "0.9.13"
 #define STDC_HEADERS 1
 #define HAVE_SYS_TYPES_H 1
 #define HAVE_SYS_STAT_H 1
 #define HAVE_STDLIB_H 1
 #define HAVE_STRING_H 1
 #define HAVE_MEMORY_H 1
 #define HAVE_STRINGS_H 1
 #define HAVE_INTTYPES_H 1
 #define HAVE_STDINT_H 1
 #define HAVE_UNISTD_H 1
 #define HAVE_DLFCN_H 1
 #define LT_OBJDIR ".libs/"
 #define STDC_HEADERS 1
 #define SP_MULTI_BYTE 1
 #define HAVE_PARSEREVENTGENERATORKIT_H 1
 #define HAVE_SGMLAPPLICATION_H 1
 #define HAVE_EVENTGENERATOR_H 1
 /* end confdefs.h.  */
 
 		#include "ParserEventGeneratorKit.h"
 		using namespace std;
 		class OutlineApplication : public SGMLApplication {
 		public:
 		  OutlineApplication() { }
 		  void startElement(const StartElementEvent &event) {
 		  }
 		  void endElement(const EndElementEvent &) { }
 
 		};
 		int main(int argc, char **argv)
 		{
 		  ParserEventGeneratorKit parserKit;
 		  EventGenerator *egp = parserKit.makeEventGenerator(argc - 1, argv + 1);
 		  OutlineApplication app;
 		}
```

And then run this command to reproduce it:

```
em++ -o conftest -DIN_LIBOFX -g -O2 -I./generic   ~/tmp/test.cpp -L./lib/.libs -losp
```

**Comment by jlongster** [comment]
If you want to compile that lib yourself, do this:

```
emconfigure ./configure --disable-doc-build
sed -i -e 's/\/\* \#undef HAVE_NAMESPACE_STD \*\//\#define HAVE_NAMESPACE_STD/g' OpenSP-1.5.2/config.h
sed -i -e 's/\/\* \#undef HAVE_MEMMOVE \*\//\#define HAVE_MEMMOVE 1/g' OpenSP-1.5.2/config.h
sed -i -e 's/\#define ptrdiff_t long/\/*\#define ptrdiff_t  long\*\//g' OpenSP-1.5.2/config.h
emmake make
```

Not sure if all those hacks are needed anymore but it works for me

**Comment by sbc100** [comment]
I get access denied on https://jlongster.com/s/OpenSP-1.5.2.zip (think you can just attach such things to the ticket if you like).

**Comment by jlongster** [comment]
Oops bad persmissions, should be fixed now! github doesn't support weird file extensions (like .o or .a) but looks like it does work with zip. already posted the link though, so you can use that

**Comment by sbc100** [comment]
Seems to be some kind of malformed archive file.    I think it might be due to the fact that it was created with the wrong version of `ar`  can you ensure you are building with `AR=/path/to/emar`?

**Comment by jlongster** [comment]
If I open the Makefile generated for the project I find:

AR = /Users/james/tmp/emsdk/fastcomp/emscripten/emar

Seems like a likely problem though. Is there a way to get output in the build process when using make/etc to see which ar is actually being invoked?

**Comment by sbc100** [comment]
Remove libosp.a and then rebuilding should show you the command used.

**Comment by jlongster** [comment]
Sorry, I was able to get it working with the fastcomp backend, so this isn't as big of a deal for me anymore. I don't know why, I removed `libosp.a` and rebuilding did nothing. Something must be wrong with this old build set up.

I rebuilt the whole thing though, and here's the log:

[log.txt](https://github.com/emscripten-core/emscripten/files/4396467/log.txt)

In the log I found this:

```
/Users/james/tmp/emsdk/upstream/emscripten/emar cru .libs/libosp.a ../intl/libintl.a  Allocator.o ArcEngine.o Attribute.o Big5CodingSystem.o CharsetDecl.o CharsetInfo.o CharsetRegistry.o CmdLineApp.o CodingSystem.o CodingSystemKit.o ConsoleOutput.o ContentState.o ContentToken.o DescriptorManager.o Dtd.o DtdDeclEventHandler.o EUCJPCodingSystem.o ElementType.o Entity.o EntityApp.o EntityCatalog.o EntityDecl.o EntityManager.o ErrnoMessageArg.o ErrorCountEventHandler.o Event.o EventGenerator.o ExtendEntityManager.o ExternalId.o Fixed2CodingSystem.o GenericEventHandler.o Group.o Hash.o IListBase.o Id.o IdentityCodingSystem.o InputSource.o InternalInputSource.o Link.o LinkProcess.o LiteralStorage.o Location.o Lpd.o Markup.o Message.o MessageArg.o MessageEventHandler.o MessageFormatter.o MessageReporter.o MessageTable.o ModeInfo.o Notation.o NotationStorage.o NumericCharRefOrigin.o OffsetOrderedList.o OpenElement.o OutputByteStream.o OutputCharStream.o OutputState.o Param.o Parser.o ParserApp.o ParserEventGeneratorKit.o ParserMessages.o ParserOptions.o ParserState.o Partition.o PosixStorage.o Recognizer.o RewindStorageObject.o SGMLApplication.o SJISCodingSystem.o SOEntityCatalog.o Sd.o SdText.o SearchResultMessageArg.o SgmlParser.o ShortReferenceMap.o StdioStorage.o StorageManager.o Syntax.o Text.o TokenMessageArg.o TranslateCodingSystem.o TrieBuilder.o TypeId.o URLStorage.o UTF8CodingSystem.o Undo.o UnicodeCodingSystem.o UnivCharsetDesc.o XMLCodingSystem.o assert.o parseAttribute.o parseCommon.o parseDecl.o parseInstance.o parseMode.o parseParam.o parseSd.o splib.o app_inst.o arc_inst.o entmgr_inst.o parser_inst.o xentmgr_inst.o SubstTable.o UTF16CodingSystem.o Fixed4CodingSystem.o memcmp.o memmove.o strerror.o ../intl/libintl.a
```

It appears to be calling the right version of emar
