### ISSUE TITLE
emsdk install latest or tot-upstream fails on aarch64

### ISSUE THREAD

**Issue by jlb6740** [emscripten-core/emscripten#10715]
Hi,

On Ubuntu/Aarch64 platform did the following steps:

git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk update-tags
./emsdk install latest

> Error: No tool or SDK found by name 'sdk-releases-upstream-65d33d604d3fa0ebe03548378b898fc6608e9cb8-64bit'.

I am able to install other targets such as "sdk-upstream-master-64bit"

I found various bugs ... notably one https://github.com/emscripten-core/emsdk/issues/312 that mentioned a platform check that didn't match but this was occurred on windows and has been patched. I don't see any flags for verbose output so not sure how to debug this but it does not occur when I try on an x86-64 platform.

**Comment by sbc100** [comment]
We don't have pre-built binaries for anything except amd64 so you can't install `latest`.

I believe @brion is the only user of emscripten on arm so may be able to help here.  At the very least it would be nice to show a better error maybe?

**Comment by brion** [comment]
Yeah, the error message isn't ideal. There should be a note on `./emsdk list` that says it's an unsupported platform and binaries aren't available, but I think it gets kinda buried.

Let's open an [issue on emsdk](https://github.com/emscripten-core/emsdk/issues) for this and I'll whip up a patch for a clearer message that better directs people to using the source installs.

**Comment by jlb6740** [comment]
Ok. Thanks guys! I see the warming at the top now. Is another issue really needed? I'll open and let you decide how to proceed.
