### ISSUE TITLE
EXCEPTION_CATCHING_WHITELIST fails with inlining and __original_main

### ISSUE THREAD

**Issue by aheejin** [emscripten-core/emscripten#10721]
- Function names specified in `EXCEPTION_CATCHING_WHITELIST` can be inlined and may not exist in the final output. We don't have a mechanism to prevent this now.
- When we specify `main` in `EXCEPTION_CATCHING_WHITELIST` and the contents of `main` is outlined to `__original_main`, exception catching may not work.

**Comment by kripken** [comment]
Looks like `test_exceptions_white_list_2` fails for this reason when we remove the (unused) arguments from main.

One option here is to add `__original_main` to the list if `main` is there. Asyncify imports and other things may benefit as well.

**Comment by sbc100** [comment]
I thought that __original_main always got inlined into main by binaryen.. or is that happening after the exception handling white-list application?

**Comment by kripken** [comment]
Yes, I think the backend does the exceptions stuff (including the list) while compiling to wasm, and then only later does binaryen inline.

**Comment by aheejin** [comment]
This is still a problem, even though it may not be something urgent. I'm working on a fix for the second thing now.

**Comment by aheejin** [comment]
https://github.com/emscripten-core/emscripten/commit/1cfce09e85a0b4e270da0dab1acdbb5af98dd202 only fixed the second part of the issue. Reopening.

**Comment by aheejin** [comment]
Fixed by #13726 and https://github.com/emscripten-core/emsdk#how-do-i-use-my-own-emscripten-github-fork-with-the-sdk.
