### ISSUE TITLE
Cannot run on Ubuntu 20.04 (devel) due to python2 interpreter rename

### ISSUE THREAD

**Issue by fcole90** [emscripten-core/emscripten#10726]
Starting with Ubuntu 20.04 the python 2 interpreter is no longer available as `python` but only as `python2` (I think this is to explicitly break compatibility with legacy python). So, if I run `./emcc -v` I get  `/usr/bin/env: ‘python’: No such file or directory`. 
I can however run it with `python2 emcc -v`. To properly workaround this, the script should be changed to use 
```
#!/usr/bin/env python2
# Not use this, read my next comment
```
A better fix would be of course to run it on python3: https://github.com/emscripten-core/emscripten/issues/7198

**Comment by fcole90** [comment]
Actually I just noticed that Python3 support is available, then I'd recommend to have the shebang point explicitly to python3
```
#!/usr/bin/env python3
```

Who needs python2 could still run it explicitly with `python2 emcc`.

**Comment by sbc100** [comment]
So what happened with ubuntu?    Is /use/bin/python no longer symlink to either version?  Is it simply missing now?  Do you have a link to the upstream change/discussion?

But yes we change the entry point scripts.  I was actually thinking of turning them back into shell scripts that then call the correct python version.

**Comment by fcole90** [comment]
Sorry, I could only find some articles like this [Phoronix - Ubuntu 20.04 LTS Moves Ahead With Python 2 Removal..](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Clear-Python2) which leads to this mailing list: [Python2 removal for focal ...](https://lists.ubuntu.com/archives/ubuntu-devel/2020-February/040918.html)

**Comment by sbc100** [comment]
The interesting thing to me is that python2 is still installable and functional, but the `python` package which contained the `/usr/bin/python` symlink is now completely gone.. which mean `python` is no longer a valid command.  

I'm working on a fix.
