### ISSUE TITLE
Various undefinied symbols on final link

### ISSUE THREAD

**Issue by Cascades** [emscripten-core/emscripten#10730]
Hi,

So I'm doing a big build with cmake.

The commands I have run, after looking through issue #2655, are as follows:
`emcmake cmake ../project_name/`
`cmake --build .`

The first command worked alright... the second one works fine until the final link to `project_name.js`:
```
error: undefined symbol: uv__fs_event_close
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: uv__hrtime
error: undefined symbol: uv__io_poll
error: undefined symbol: uv__platform_invalidate_fd
error: undefined symbol: uv__platform_loop_delete
error: undefined symbol: uv__platform_loop_init
error: undefined symbol: uv_fs_event_init
error: undefined symbol: uv_fs_event_start
error: undefined symbol: uv_fs_event_stop
Error: Aborting compilation due to previous errors
shared:ERROR: '/xxx/emsdk/node/12.9.1_64bit/bin/node /xxx/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpam8glV.txt' failed (1)
Source/CMakeFiles/cmake.dir/build.make:117: recipe for target 'bin/project_name.js' failed
make[2]: *** [bin/project_name.js] Error 1
CMakeFiles/Makefile2:2014: recipe for target 'Source/CMakeFiles/cmake.dir/all' failed
make[1]: *** [Source/CMakeFiles/cmake.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

I also previously had this in there:
```
error: undefined symbol: posix_spawn_file_actions_adddup2
error: undefined symbol: posix_spawn_file_actions_addopen
error: undefined symbol: posix_spawn_file_actions_destroy
error: undefined symbol: posix_spawn_file_actions_init
```

but after reading issue #6090 and adding `-DHAVE_POSIX_SPAWN=0 -DHAVE_PTHREAD_H=0 -DHAVE_LIBPTHREAD=0 -DPTHREAD_IN_LIBC=0 -DHAVE_POSIX_SPAWNP=0 ` to the end of `emcmake cmake ../project_name/` they have now gone away.

I did some testing a `cmake --build .`, `make` & `emmake make` are all the same... while `emcmake cmake --build .` complains about some CMake variables which I couldn't be bothered to try and fix.

Any help getting past all these undefined symbols? Thanks!

**Comment by sbc100** [comment]
You don't need to use `emmake` if you use `emcmake`.   `emmake` is designed for when you have an upstream Makefile.   The cmake-generated makefile should have everything baked in so you can just run it with `make` directly (or indirectly via `--build`).

**Comment by sbc100** [comment]
Regarding the undefined symbols starting with `uv_`.  They look like they come from a library (libuv?).  I'm don't think libuv currently works with emscripten so you might need to find some alternative.   I'm not sure how/why this doesn't an error at cmake time though...

**Comment by sbc100** [comment]
Do you have a HAVE_LIBUV control in your project that you can set to 0?

**Comment by Cascades** [comment]
Nope, unfortunately I'm actually trying to build CMake itself, and they made libuv a required module a couple of years back :/

Guess I'm stuffed?

**Comment by sbc100** [comment]
Thats is strange..  I can't imagine its part of the core functionality.  Maybe you can hack on it to make it optional?

**Comment by Cascades** [comment]
Yah, well, it used to only be for the server apparently and now they want to open more doors for themselves? [PR here](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1104)

I've posted something over on their gitlab, meanwhile I'll get hacking! Thanks
