### ISSUE TITLE
Can't use most of C++ when compiling standalone

### ISSUE THREAD

**Issue by KTRosenberg** [emscripten-core/emscripten#10733]
I am attempting to compile a small C++ example that uses the standard library into wasm for use with a basic javascript entrypoint (not generated glue code). Unfortunately, when loading the module, I receive the following error:

`TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function`

I have attempted building using wasisdk and standalone llvm previously, but had similar issues. There doesn't seem to be information about working around this rather cryptic error.

Firstly, before I go deeper, is it even possible to build C++ code that uses data structures from the standard library into standalone wasm? I am unsure of whether I should be able to get this working given that wasm is still in its early days, but I might be doing something incorrectly. In my experience, almost every built-in data structure and string causes issues, even if I overload `new` and `delete` to rule-out some memory allocation issues.

For more details, my system is MacOS 10.14, and I'm running Chrome 80. I am using the latest version of emsdk from the github to compile.

My apologies for the influx of code blocks, but I am unsure of a better example. I've reduced the examples to the minimum as well as I could.

This is my bash build script:

```bash
em++ source.cpp \
--std=c++17 \
-flto \
-fno-exceptions \
-Os \
-o output.wasm \
-s "EXPORTED_FUNCTIONS=['_animate']" \
-s ERROR_ON_UNDEFINED_SYMBOLS=0 \
```

C++: I get the error as soon as I use a data structure such as a standard unordered map.
```cpp
#ifdef __cplusplus
	#define extern_c_begin() extern "C" {
	#define extern_c_end() }
#else 
	#define extern_c_begin()
	#define extern_c_end()
#endif

#include <unordered_map>

std::unordered_map<int, int> map;

int use_map() {
        // if I use the map at all, I get the error
	map.insert({1, 2});
	return (int)map.size();
}

extern_c_begin()

// call into js
void hello_js(void);

int animate(long arg) {
	int size = use_map();
	hello_js();
	return size;
}

extern_c_end()
```

Finally, my javascript/index.html:
```js
<!DOCTYPE html><html><head></head><body>
    <script type="module">
        "use strict";
        (async () => {
          try {
            const wasmInfo = {
                instance   : null,
                memoryHeap : null,
                env        : {}
            };

            wasmInfo.env["hello_js"] = () => {
                console.log("in js, call from wasm");
            };
            
            // error on load
            const wasmLoadResult = await WebAssembly.instantiateStreaming(
              fetch("./output.wasm"),
              {env : wasmInfo.env}
            );
            wasmInfo.instance = wasmLoadResult.instance;

            function animate(t) {
                requestAnimationFrame(animate);
                try {
                    console.log(wasmInfo.instance.exports.animate(t));
                } catch (e) {
                    console.error(e);
                }
            }
            requestAnimationFrame(animate);

          } catch (err) {
            console.error(err);
          }
        })();
</script></body></html>
```
This seems to happen with practically every data structure. I even tried a third-party library called `robin_hood` to replace the map, but that has the same issue.

Is there a solution?
Thank you for your time.

**Comment by sbc100** [comment]
Depending on the code you compile you will end up depending on a certain number of external functions.   These are kind of the system calls of WebAssembly.  With emscripten they will either be under "env" or under "wasi_snapshot_preview1".     

You can use `wasm-objdump` to see what imports you module requires.    To solve the immediate issue you can simple add `wasi_snapshot_preview1` to the map you are passing to `instantiateStreaming`.  Once you do that you will get more precise errors about what is missing from `env` and from `wasi_snapshot_preview1` which will probably both needs to contain a few items at least.

**Comment by sbc100** [comment]
BTW you may want to build with `-s WASM_STANDALONE` if you want to minimise the amount of helper functions you have to write in JS.

**Comment by KTRosenberg** [comment]
How do I add "wasi_snapshot_preview1" to the map? If that's the key, then that is the value?

```js
wasmInfo.env["wasi_snapshot_preview1"] = ?
            const wasmLoadResult = await WebAssembly.instantiateStreaming(
              fetch("./output.wasm"),
              {env : wasmInfo.env}
            );
```

My apologies if this is a simple thing.

**Comment by sbc100** [comment]
I would do something like this.

```
wasmInfo.env["wasi_snapshot_preview1"] = ?
            const wasmLoadResult = await WebAssembly.instantiateStreaming(
              fetch("./output.wasm"),
              {
               env : wasmInfo.env, 
               wasi_snapshot_preview1 : wasmInfo.wasi_snapshot_preview1
              }
            );
```

Then add    `wasi_snapshot_preview1   : {}` to you wasmInfo.   

Then you will need to fill out those two empty objects `{}` with all of the imports required by your program.

What you are trying to do is fairly non-trival.  For example here is very-much-incomplete wasi implementation I wrote in JS:  https://github.com/WebAssembly/waterfall/blob/master/src/wasi.js.
There are various other ones out there too.

I'm not saying what you are doing is impossible, but it is hard.  Can you I ask why you are trying to o this without using the emscripten implementation of these functions?

**Comment by KTRosenberg** [comment]
First of all, that seemed to work for now.
Secondly, the missing procedure was called `proc_exit` I believe. (Strange, I guess this is a very low-level procedure).

I thought that by using emscripten in standalone mode I could use wasm modules within my larger existing js code-base. I don't really want to have the huge amount of glue code because that code-base is large and not necessarily devoted to running the one program. I also don't want the emscripten-window style presentation in the index.html.
Based on the documentation, I don't see a way to incorporate wasm cleanly without going standalone, but I had thought that emscripten would include all of those extra functions somehow. Clearly I was missing something.
If there's a way to combine this sort of minimal build format with "hey, here are all of the extra functions you need to avoid breakage" then that would be great.

**Comment by sbc100** [comment]
Regarding the html:  You don't need to use emscripten's html.    If you set your output file to be a `.js` file, emscripten will build a wasm file and a companion js that you can use as you please.

Regarding the generated js:  Emscripten has good DCE (dead-code-elimination) so that the resulting JS file should only contains the minimum number of functions needed to run you program.   It may still look overwhelming to try to read it (!), but it shouldn't be prohibitively large (especially when compiling with -Os).  You are free to integrate the generated JS with your existing JS however you like.   Almost all projects that use emscripten use the auto-generated .js code (e.g. unity games, google earth web, etc..).   

Yes emscripten provides a virtual filesystem if you want one.

**Comment by KTRosenberg** [comment]
Oh, I see. Yet if I want to add  my own js functions to be called with C, I still do the usual `extern proc();` declarations in C? From the JS side do I use the LibraryManager referenced in the documentation here? https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript

**Comment by sbc100** [comment]
The minimization of the JS occurs based on the opt level (and other options).

You can build with `-O0` or `-O1` it will be implicitly disabled, or you can disable it for an optimized build with `--minify=0`.

The easiest way to call out to JS is probably using EM_JS or EM_ASM.  Writing a JS library is another option that might make sense depending on your use case (e.g. if you have a lot of JS code at the boundary to maintain).

**Comment by KTRosenberg** [comment]
That makes sense. Looking at the generated js, it doesn't look like I can add my own functions before the module is instantiated though. hmm

In any case, thanks a lot for helping me figure-out my main oversight!

**Comment by sbc100** [comment]
No probs!   Glad you are up and running!

There are `--pre-js` and `--post-js` flags to inject your own code unconditionally.  There is also the library system which you can use via `--library-js`.

**Comment by KTRosenberg** [comment]
Okay. Last thing about the library. I'm looking at the example here:
https://github.com/emscripten-core/emscripten/blob/1.29.12/tests/test_core.py#L5043

I don't think the LibraryManager is made available in the js, unless I'm missing something. Where would I call mergeInto/how do I get access to those?

**Comment by kripken** [comment]
A note on this:

> but I had thought that emscripten would include all of those extra functions somehow [like proc_exit]

Things like `proc_exit` are what you should expect to see since they do things you can't do inside the wasm. Things like exiting with a return code, or printing to stdout, are the imports you will need to provide yourself. The wasm module itself can only do pure computation basically inside its own linear memory; any I/O or interaction with the outside world will require imports or exports.

**Comment by KTRosenberg** [comment]
@kripken Yes, that makes sense. Speaking of interacting with the outside world, I am looking forward to being able to do some sort of hot-reloading state trickery with wasm, which seems impossible for now. The idea would be the do all memory allocations in one module and pass that data to a second module that you could recompile over and over. I don't think you can currently do this.

Anyway, that's a tangent.

**Comment by kripken** [comment]
You can share the Memory between modules, and pass state that way. Also mutable globals and the Table allow that. But it depends what you mean by state, I guess, I can think of various use cases.

**Comment by KTRosenberg** [comment]
Hmm somehow I failed to export the table even if I passed the correct flags as far as I’m concerned. Would you direct me to an example?

By sharing state I mean, here is the ideal (whether it works or not)
let’s say I allocate memory in module A for a struct containing game state. I pass this data to module B as a pointer, and module B uses that data.

When module B requests memory, the memory comes from module A via some sort of wrapper. (Note there’s no direct path from modules that don’t go through js, so runtime memory requests have some extra overhead.) Finally, let’s say I want to iterate on my project rapidly without wiping out all the game state in the struct. So what I do is issue a command to a local compiler and generate a new module B updated with new code, but not new structs. Module A passes the magic state struct pointer back to module B, and it can continue running as if nothing changed.

Problem: Correct me if I’m wrong, but this is currently impossible. Module B doesn’t know how to access data from
Module A via a pointer to A’s data, right?  :(. I’d need to do a value copy instead of a pointer copy, which means I couldn’t store pointers in the struct, as recompiling wasm might change all the offsets.

Any thoughts? I’m still interested in getting table metadata, but nothing seems to work.

**Comment by kripken** [comment]
If you want different modules to have different memories, then yeah, accessing one memory from another module will require multi-memory support (which is in progress), or copies (which Interface Types is working on).

**Comment by KTRosenberg** [comment]
Where can I monitor the progress of the multi-memory support, and how far along is it? I imagine it'll take a while, but I'm hoping to see it in Chrome and iOS Safari sometime.

**Comment by kripken** [comment]
There's an entry on the status page, https://github.com/WebAssembly/proposals and a link from there to the main repo which you can watch. I'm not sure if there's a good way to directly see the VM implementation status though, but that's reflected in the status page (i.e. it won't reach later stages without such support).

**Comment by KTRosenberg** [comment]
Thanks. One more thing if I may ask— I’m trying to figure how to import memory into a standalone wasm module instead of exporting it, and I don’t think I need a side-module, but the import memory flag doesn’t seem to be exposed to the emscripten frontend. Is there a way to import memory that I haven’t found?

**Comment by sbc100** [comment]
@KTRosenberg its possible you can use "-Wl,--import-memory" on the command line.   Especially after this change lands:  #10747 

In general, for this kind of bespoke change, if emscripten doesn;t support exactly you what you need, you can use binaryen or wabt to convert your module to text format, modify it in-place and then convert it back to binary.    Or you can write a binaryen pass to do it.

**Comment by rambip** [comment]
I fanilly found documentation about these exported functions:
https://alexene.dev/2020/08/17/webassembly-without-the-browser-part-1.html

Could I  know exactly what these functions are ?
- fd_read
- fd_write
- proc_exit

And is there a lust somewhere of all these functions ?
I would like to ignore them at compile time, because I think they are not used in my webassembly

**Comment by kripken** [comment]
@rambip Those are syscalls to do I/O. You can find their implementations in `src/library_wasi.js`.

If they are not used, they should be removed in an optimized build. Inspecting the binary can show how they are being used.

**Comment by rambip** [comment]
@kripken 
What do you call an "optimized build" ?
I compiled the stb_image headers without including stdio, but it still imports these syscalls
I will loke at the expanded .wat

**Comment by kripken** [comment]
By "optimized build" I mean something like `-O3` or `-Os`.

**Comment by sbc100** [comment]
From my stackoverflow response:

Firstly I would recommend building with `-Oz` or at least`-O2` so that the toolchain tries is upmost to shrink the resulting binaryn.

I recommend building with `-Oz --profiling-funcs` and then using `wasm-objdump` or `wasm-decompile` to see why those imports and ultimately being used.

When I do this is clear that `proc_exit` is being used `assert_fail` .. indeed it looks like they are all due to the use of the assert macro and adding `-DNDEBUG` makes all those imports go away.

**Comment by sbc100** [comment]
Hopefully this issue can now be closed?

**Comment by rambip** [comment]
Yes thanks !!!
