### ISSUE TITLE
Question: how does __wasm_call_ctors get created

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#10742]
emcc --version 
```
1.39.7
```

I'm following https://medium.com/@MStrehovsky/building-a-self-contained-game-in-c-under-8-kilobytes-74c3cf60ea04?sk=334b06f72dad47f15d0ba0cc6a502487 and trying to do the Wasm equivalent.  I build a few bits with
```
emcc MiniRuntime.wasm.c -c -o MiniRuntime.bc -s WASM=1
```
and I use the CoreRT compiler to produce the LLVM bc for my program with
```
..\corert\bin\WebAssembly.wasm.Debug\tools\ilc --targetarch=wasm zerosnake.ilexe -o zerosnake.bc --systemmodule:zerosnake --Os -g
```
That's my bit of course I don't expect any help there.  There is no `main` and in the x64 world the linker handles this with `/entry:__managed__Main` as that is the entry point.  I link with
```
"E:\GitHub\emsdk\upstream\emscripten\emcc.bat" "zerosnake.bc" -o "zerosnake.html" -s WASM=1 --emrun MiniRuntime.bc
```
And at runtime I get 
```
TypeError: Module.asm.__wasm_call_ctors is undefined
```
in the console.  So I read some stuff and it seems that `__wasm_call_ctors` is related to the startup, but I'm wondering where emscripten would normally call `main` and what I should/can do as an equivalent to `link`s `/entry`?

**Comment by sbc100** [comment]
`__wasm_call_ctors` is a function that is generated by the linker: `wasm-ld`.    

It should then get automatically called by the js which is generated by emscripten.  Can you take a look at the generated JS?  Do you get a backtrace along with that error?

**Comment by yowl** [comment]
yes there is:
```
___wasm_call_ctors file:///E:/GitHub/SeeSharpSnake/zerosnake.js:2169
    func file:///E:/GitHub/SeeSharpSnake/zerosnake.js:1809
    callRuntimeCallbacks file:///E:/GitHub/SeeSharpSnake/zerosnake.js:1377
    initRuntime file:///E:/GitHub/SeeSharpSnake/zerosnake.js:1409
    doRun file:///E:/GitHub/SeeSharpSnake/zerosnake.js:2384
    run file:///E:/GitHub/SeeSharpSnake/zerosnake.js:2401
```

Also may be of interest: 
```
wasm-objdump.exe zerosnake.wasm -x
```
gives (cut)
```
Export[15]:
 - func[7] <__wasm_call_ctors> -> "__wasm_call_ctors"
 - func[17] <malloc> -> "malloc"
 - func[10] <__errno_location> -> "__errno_location"
 - func[21] <fflush> -> "fflush"
 - func[20] <setThrew> -> "setThrew"
 - func[18] <free> -> "free"
 - global[1] -> "__data_end"
 - func[23] <__set_stack_limit> -> "__set_stack_limit"
 - func[24] <stackSave> -> "stackSave"
 - func[25] <stackAlloc> -> "stackAlloc"
 - func[26] <stackRestore> -> "stackRestore"
 - func[27] <__growWasmMemory> -> "__growWasmMemory"
 - func[28] <dynCall_ii> -> "dynCall_ii"
 - func[29] <dynCall_iiii> -> "dynCall_iiii"
 - func[31] <dynCall_jiji> -> "dynCall_jiji"
Elem[1]:
```

**Comment by yowl** [comment]
I added 
```
    console.log(Module["asm"]);
```
 at line 2169 and
```
{}
​
<prototype>: {…}
​​__defineGetter__: function __defineGetter__()
​​__defineSetter__: function __defineSetter__()
​​__lookupGetter__: function __lookupGetter__()
​​__lookupSetter__: function __lookupSetter__()
​​__proto__: 
​​constructor: function Object()
​​hasOwnProperty: function hasOwnProperty()
​​isPrototypeOf: function isPrototypeOf()
​​propertyIsEnumerable: function propertyIsEnumerable()
​​toLocaleString: function toLocaleString()
​​toString: function toString()
​​valueOf: function valueOf()
​​<get __proto__()>: function __proto__()
​​<set __proto__()>: __proto__()
​​​zerosnake.js:2169:13
TypeError: Module.asm.__wasm_call_ctors is undefined zerosnake.js:2170:3
```
Perhaps the wasm didn't load ok?

**Comment by sbc100** [comment]
What is the contents of line 2169?

Can you run basic examples such as hello world?   They should all follow the same pattern.

**Comment by yowl** [comment]
2169 is 
```
 return Module["asm"]["__wasm_call_ctors"].apply(null, arguments)
```
Yes other stuff is fine, just this one where I'm doing different build steps.  It seems like some timing thing as if I add a `console.log` to the `receiveInstance` js function in `createWasm` then the problem goes away.

**Comment by yowl** [comment]
Should wasm-ld also add the `_start` symbol or will it only do that if it finds a `main` symbol ?

**Comment by sbc100** [comment]
No, emscripten doesn't use `_start`.  Instead, it builds with `--no-entry` and explicitly exports both `__wasm_call_ctors` and `main` which it then calls from JS.

I'm not sure how the error `TypeError: Module.asm.__wasm_call_ctors is undefined` comes from the line `return Module["asm"]["__wasm_call_ctors"].apply(null, arguments)`.   Maybe I don't understand JS error messages but I would have expected something like "undefined is not a function" if the key `"__wasm_call_ctors"` was missing from `Module["asm"]`.

**Comment by yowl** [comment]
I don't pretend to be able to explain Javascript design, its right up there with Basic in my opinion.  Anyway I added a `main` and add a `console.log` and that gets it running so I'll close this
