### ISSUE TITLE
[Feature request] Let -gseperate-dwarf take an optional argument to specifiy the filename

### ISSUE THREAD

**Issue by pfaffe** [emscripten-core/emscripten#10759]
Currently the path put into the custom_section is based on the file path argument, which could be an absolute or relative path, not just the file name. That path likely makes little sense to clients, but that can be fixed simply by letting me specify the correct path explicitly.

**Comment by kripken** [comment]
Sounds good. Any thoughts on the notation? Not sure if there's an existing convention for this we can follow.

If nothing else, maybe the path could be appended to the flag with an `=`, so `-gseparate-dwarf[=PATH]`?

**Comment by kripken** [comment]
cc @dschuff

**Comment by pfaffe** [comment]
I'm quite happy with `-gseparate-dwarf[=PATH]`!

**Comment by kripken** [comment]
Sounds good, I opened #10766 with that now.
