### ISSUE TITLE
modifying output of app.js when using --proxy-to-worker

### ISSUE THREAD

**Issue by esromneb** [emscripten-core/emscripten#10769]
I am hoping to use `--proxy-to-worker`.  In order to get `postCustomMessage()` working, I've edited `app.js` and added:
```javascript
Module["onCustomMessage"] = (x) => {
  console.log('worker got msg: ' + x);
}
```

However each time I re-compile my c++ code, these edits get wiped out.  What can I pass to emcc in order to get permanent changes?  I've found the `--shell-file` option for controlling the html output, is there something similar for the js output?

In general I feel like the documentation should contain a section about how to work with the outputs of the compiler in a permanent way.

**Comment by kripken** [comment]
`--pre-js` lets you prepend JS to the main JS file. (and `--post-js` appends)

However I think `--proxy-to-worker` also emits an extra JS file maybe (or maybe I'm confusing it with pthreads) - in that case there might not be a flag. But you could add something to your build system to prepend or append after calling emcc.

**Comment by esromneb** [comment]
Ok, that works!!

 I have a related question.  From the `--help` I see this text

```
"--pre-js <file>"
   Specify a file whose contents are added before the emitted code and
   optimized together with it. Note that this might not literally be
   the very first thing in the JS output, for example if "MODULARIZE"
   is used (see "src/settings.js"). If you want that, you can just
   prepend to the output from emscripten; the benefit of "--pre-js" is
   that it optimizes the code with the rest of the emscripten output,
   which allows better dead code elimination and minification, and it
   should only be used for that purpose. In particular, "--pre-js"
   code should not alter the main output from emscripten in ways that
   could confuse the optimizer, such as using "--pre-js" + "--post-js"
   to put all the output in an inner function scope (see "MODULARIZE"
   for that).

   *--pre-js* (but not *--post-js*) is also useful for specifying
   things on the "Module" object, as it appears before the JS looks at
   "Module" (for example, you can define "Module['print']" there).
```

I tried it and I am allowed to pass `--pre-js` as well as `--pre-jsa` and `--pre-jsb` etc.  What is the purpose of the wildcard allowing characters after `--pre-js` and is there an order?

**Comment by sbc100** [comment]
Hmm... I don't think wildcards should be accepted there.  I think the asterisk there comes from the author wanting those words in the help text to appear in bold.     The fact that we accept `--pre-jsa` is really a bug in emcc I think.. we should fix that:  https://github.com/emscripten-core/emscripten/blob/master/emcc.py#L2826
