### ISSUE TITLE
build notes filter

### ISSUE THREAD

**Issue by friesendrywall** [emscripten-core/emscripten#10768]
Is there some way to filter out build notes and specific warnings?  So far my search has come up dry in the docs.

**Comment by sbc100** [comment]
We've been moving more and more warning to be managed by the warning manager.

Do you have specific messages you'd like to control that are currently not controllable?

**Comment by friesendrywall** [comment]
I didn't realize that I needed to use -Wno clang style disabling.

However, I'd still like to disable macro expansion notes, like

`./HardwareProfile.h:163:28: note: expanded from macro 'Charge_OFF'
#define Charge_OFF      LATACLR = 1<<5`

and I don't really see any way.

**Comment by sbc100** [comment]
That looks like a clang note, no?   So controlling that would be bug/question for clang developers I think.
