### ISSUE TITLE
err is not a function

### ISSUE THREAD

**Issue by briancullinan** [emscripten-core/emscripten#10762]
This kind of usage
```
              if (e && typeof e === 'object' && e.stack) err('exception thrown: ' + [e, e.stack]);
```
Has scoping issues, I must be using the variable err in my code and it is overriding the emscripten definition.

**Comment by kripken** [comment]
Where does this happen? Do you have a testcase showing the issue?

**Comment by briancullinan** [comment]
Sorry to bother. I think it was my fault, I used `var err` and caused a leaky scope, the code above is from inside emscripten, probably support or something. Once I changed my code and stopped using the name err, it went away, if there is an err it works as expected. I might like to fix the module builder and make it more syntax aware, I read somewhere it is pretty "dumbed down" for lack of a better word.
