### ISSUE TITLE
Creating a webgl context in a webworker

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#10764]
Using version 1.39.11 and Firefox developer edition 75.0b8 (64-bit)

I'm trying to use WebGL and Offscreen rendering in a web worker. Flags for linking are:

```
 -s USE_GLFW=3
 -s FULL_ES3=1
 -s OFFSCREEN_FRAMEBUFFER=1
 -s OFFSCREENCANVAS_SUPPORT=1
 -s USE_WEBGL2=1
 -s ENVIRONMENT=worker
```

```
EmscriptenWebGLContextAttributes attrs;
emscripten_webgl_init_context_attributes(&attrs);
attrs.majorVersion = 3;
attrs.minorVersion = 3;
attrs.renderViaOffscreenBackBuffer = true;
int ctx = emscripten_webgl_create_context(0, &attrs);
```

The program gets stuck inside create context and I'm wondering what's the problem. As I understand the first parameter of `emscripten_webgl_create_context` is the name of the canvas - but since I use offscreen rendering I guess that is not needed?

**Comment by kripken** [comment]
IIRC the model is to create the context on the main thread, so it is connected to the place where rendering appears. Then it is transferred to a worker (which emscripten should do automatically with those flags).

Can see `browser.test_webgl_offscreen_canvas_only_in_pthread` as a test that should show that working.

**Comment by major-mayer** [comment]
Hmm so i tried as @kripken suggested and created a canvas on the main thread before and then handed the context over to the worker thread. 
It's now looking like this:
```cpp
// Create a context on the main thread first:
	EmscriptenWebGLContextAttributes webglAttr;
	emscripten_webgl_init_context_attributes(&webglAttr);
	emscripten_webgl_create_context("#canvas", &webglAttr);

	// Then create a pthread and transfer the canvas to the created thread
	// m_rcLoopThread = std::thread(&HAFDRendererOpenGLBased::ExecuteRenderContextLoop, this);
	pthread_attr_t attr;
	pthread_attr_init(&attr);
	emscripten_pthread_attr_settransferredcanvases(&attr, "#canvas");
	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
  	pthread_create(&m_rcLoopThread, &attr, [](void* myThis)-> void*{
		  reinterpret_cast<MyClass*>(myThis)->MyRenderFunction(); pthread_exit(0);

		  }, this);

```
Unfortunately tho this gives me a new error right when I create the thread:
`failed to transfer control of canvas "canvas" to OffscreenCanvas! Error: InvalidStateError: Failed to execute 'transferControlToOffscreen' on 'HTMLCanvasElement': Cannot transfer control from a canvas that has a rendering context`

So transfering the control of a canvas element that has an existing context, doesn't seem to be the right way...

**Comment by major-mayer** [comment]
Well, PROXY_TO_PTHREAD unfortunately isn't an option if you are using embind to create bindings for a CPP library, because there is no main function that you could proxy.
@kripken has described a workaround as pseudo-code [here](https://github.com/emscripten-core/emscripten/issues/15868#issuecomment-1006168330) but I can't get it to working code...
