### ISSUE TITLE
Issue with emsdk.py in Windows (due to fix_potentially_long_windows_pathname())

### ISSUE THREAD

**Issue by alimalkhalifa** [emscripten-core/emscripten#10773]
Hey! Just thought I would make you aware.

I had a failure on installation both on cmd.exe and ps using emsdk.bat install latest.  Dug into it and found that def fix_potentially_long_windows_pathname() returns a reference even if the path is not too long, and seems my OS is failing at accessing a reference path?

Not sure exactly, but this is the error received
```
Unzipping file 'C:/Users/amalk/Documents/Projects/emsdk/zips/node-v12.9.1-win-x64.zip' failed due to reason: [Error 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\C:\\Users\\amalk\\Documents\\Projects\\emsdk\\node\\unzip_temp\\node-v12.9.1-win-x64/'
```

Hacked/Solved it by making fix_potentially_long_windows_pathname() always return the pathname as such, in case someone is having a similar issue and needs a bandaid:

```python
def fix_potentially_long_windows_pathname(pathname):
  if true or not WINDOWS:
    return pathname
```

NB: This disables all protection for pathnames > 260 chars.  Please make sure you are not using long pathnames when you do this

**Comment by Jaifroid** [comment]
I got what may be a similar failure when updating emsdk to latest on Windows 10.

> Unzipping file 'C:/Users/xxxxx/Source/Repos/emsdk/zips/e13b86d4dbd9a986525ef27d4ad8157949b9bc3a-wasm-binaries.zip' failed due to reason: [Error 5] Access is denied: '\\\\?\\C:\\Users\\xxxxx\\Source\\Repos\\emsdk\\upstream\\emscripten\\third_party\\websockify\\tests\\include'
> Installation failed!

I'll try the hack, even though the error message is different.

**Comment by Jaifroid** [comment]
The hack didn't work because "global name 'true' is not defined". I don't know python, but I guess it should be 'True'..... Full message:

> Unzipping file 'C:/Users/xxxxx/Source/Repos/emsdk/zips/e13b86d4dbd9a986525ef27d4ad8157949b9bc3a-wasm-binaries.zip' failed due to reason: global name 'true' is not defined
Installation failed!

**Comment by Jaifroid** [comment]
It still fails when correcting the hack to 'True'. Error message:

> Unzipping file 'C:/Users/xxxxx/Source/Repos/emsdk/zips/e13b86d4dbd9a986525ef27d4ad8157949b9bc3a-wasm-binaries.zip' failed due to reason: [Error 5] Access is denied: 'C:/Users/xxxxx/Source/Repos/emsdk/upstream\\./emscripten/third_party/websockify/tests/include'
Installation failed!

It's a malformed path, but not due to long filename, due to inclusion of a rogue `./` I think, or else returning the Windows path is not what is required here. So, I'm a bit stumped now...

**Comment by woshiZS** [comment]
I met this problem again, and I searched this problem, and someone said this is due to an old python package.
The python path is hard coded in their running script, like this:
```shell
:: When using our bundled python we never want the users
:: PYTHONHOME or PYTHONPATH
:: https://github.com/emscripten-core/emsdk/issues/598
if exist "%~dp0python\3.9.2-1_64bit\python.exe" (
  set EMSDK_PY="%~dp0python\3.9.2-1_64bit\python.exe"
  set PYTHONHOME=
  set PYTHONPATH=
  goto end
)

if exist "%~dp0python\3.9.2-nuget_64bit\python.exe" (
  set EMSDK_PY="%~dp0python\3.9.2-nuget_64bit\python.exe"
  set PYTHONHOME=
  set PYTHONPATH=
  goto end
)

if exist "%~dp0python\3.7.4-pywin32_64bit\python.exe" (
  set EMSDK_PY="%~dp0python\3.7.4-pywin32_64bit\python.exe"
  set PYTHONHOME=
  set PYTHONPATH=
  goto end
)

if exist "%~dp0python\3.7.4_64bit\python.exe" (
  set EMSDK_PY="%~dp0python\3.7.4_64bit\python.exe"
  set PYTHONHOME=
  set PYTHONPATH=
  goto end
)

if exist "%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe" (
  set EMSDK_PY="%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe"
  set PYTHONHOME=
  set PYTHONPATH=
  goto end
)

:: As a last resort, access from PATH.
set EMSDK_PY=python

:end
call %EMSDK_PY% "%~dp0\emsdk.py" %*

endlocal

:: python is not able to set environment variables to the parent calling
:: process, so therefore have it craft a .bat file, which we invoke after
:: finishing python execution, to set up the environment variables
if exist "%~dp0\emsdk_set_env.bat" (
  call "%~dp0\emsdk_set_env.bat" > nul
  del /F /Q "%~dp0\emsdk_set_env.bat"
)
```
I check my python path, its default value is python2.7, so changed the word "python" to "python3", and it works!
```shell
set EMSDK_PY=python3
```
Hope this will help anyone who met the same problem.

**Comment by sbc100** [comment]
@woshiZS which build of python2.7 is failing for you?  Can you run `where python` and `python --version` to report the output?

**Comment by woshiZS** [comment]
@sbc100 It's python 2.7.2, and my OS is windows11.
![image](https://github.com/emscripten-core/emscripten/assets/38726708/ad57c0dc-d13b-46e0-9e9f-6ff04c05afd6)
