### ISSUE TITLE
Linker issues when building map

### ISSUE THREAD

**Issue by friesendrywall** [emscripten-core/emscripten#10778]
My application builds and runs, however I'd like to generate a source map, which won't, giving me a bunch of linker errors.  Is there some trick to using --generate-source-map ? My present options are

`-s ASYNCIFY=1 -s USE_PTHREADS -Wno-incompatible-pointer-types-discards-qualifiers -Wno-pointer-sign -Wno-incompatible-pointer-types -g4 --source-map-base http://emscripten.test/ -O0`

Here is what I presently get

`wasm-ld: error: C:\Users\Erik\.emscripten_cache\wasm\libc-mt.a(emscripten_pthread.c.o): undefined symbol: initPthreadsJS`

The full output is :

```
C:\msys\1.0\bin\make.exe -f Makefile CONF=Release
"/C/msys/1.0/bin/make.exe" -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
make.exe[1]: Entering directory `/c/AerCon Software/web_emulation/Monitor-2620'
"/C/msys/1.0/bin/make.exe"  -f nbproject/Makefile-Release.mk dist/Release/emscripten-Windows/monitor-2620.js.exe
make.exe[2]: Entering directory `/c/AerCon Software/web_emulation/Monitor-2620'
mkdir -p dist/Release/emscripten-Windows
emcc -s ASYNCIFY=1 -s USE_PTHREADS -Wno-incompatible-pointer-types-discards-qualifiers -Wno-pointer-sign -Wno-incompatible-pointer-types -g4 --source-map-base http://emscripten.test/ -O0    -o dist/Release/emscripten-Windows/monitor-2620.js build/Release/emscripten-Windows/ADC.o build/Release/emscripten-Windows/AerMain.o build/Release/emscripten-Windows/Aeration.o build/Release/emscripten-Windows/Alarms.o build/Release/emscripten-Windows/Alerts.o build/Release/emscripten-Windows/BitMapHeader.o build/Release/emscripten-Windows/Buoy.o build/Release/emscripten-Windows/CRC.o build/Release/emscripten-Windows/Combined.o build/Release/emscripten-Windows/Controlprocess.o build/Release/emscripten-Windows/KS_0108.o build/Release/emscripten-Windows/L37x29.o build/Release/emscripten-Windows/Logging.o build/Release/emscripten-Windows/Menu.o build/Release/emscripten-Windows/MyTimers.o build/Release/emscripten-Windows/Primitive.o build/Release/emscripten-Windows/Satisfiers.o build/Release/emscripten-Windows/SystemLog.o build/Release/emscripten-Windows/lc256.o build/Release/emscripten-Windows/qmatrix.o build/Release/emscripten-Windows/rtcc.o build/Release/emscripten-Windows/splash.o build/Release/emscripten-Windows/time.o build/Release/emscripten-Windows/web_main.o  -s LLD_REPORT_UNDEFINED
wasm-ld: error: C:\Users\Erik\.emscripten_cache\wasm\libc-mt.a(emscripten_pthread.c.o): undefined symbol: initPthreadsJS
shared:ERROR: 'C:/Software/emsdk/upstream/bin\wasm-ld.exe -o C:\Users\Erik\AppData\Local\Temp\emscripten_temp_etx1se_f\monitor-2620.wasm --lto-O0 build/Release/emscripten-Windows/ADC.o -LC:\Software\emsdk\upstream\emscripten\system\local\lib build/Release/emscripten-Windows/AerMain.o -LC:\Software\emsdk\upstream\emscripten\system\lib build/Release/emscripten-Windows/Aeration.o -LC:\Users\Erik\.emscripten_cache\wasm build/Release/emscripten-Windows/Alarms.o build/Release/emscripten-Windows/Alerts.o build/Release/emscripten-Windows/BitMapHeader.o build/Release/emscripten-Windows/Buoy.o build/Release/emscripten-Windows/CRC.o build/Release/emscripten-Windows/Combined.o build/Release/emscripten-Windows/Controlprocess.o build/Release/emscripten-Windows/KS_0108.o build/Release/emscripten-Windows/L37x29.o build/Release/emscripten-Windows/Logging.o build/Release/emscripten-Windows/Menu.o build/Release/emscripten-Windows/MyTimers.o build/Release/emscripten-Windows/Primitive.o build/Release/emscripten-Windows/Satisfiers.o build/Release/emscripten-Windows/SystemLog.o build/Release/emscripten-Windows/lc256.o build/Release/emscripten-Windows/qmatrix.o build/Release/emscripten-Windows/rtcc.o build/Release/emscripten-Windows/splash.o build/Release/emscripten-Windows/time.o build/Release/emscripten-Windows/web_main.o C:\Users\Erik\.emscripten_cache\wasm\libc-mt.a C:\Users\Erik\.emscripten_cache\wasm\libcompiler_rt.a C:\Users\Erik\.emscripten_cache\wasm\libc-wasm.a C:\Users\Erik\.emscripten_cache\wasm\libdlmalloc-mt-debug.a C:\Users\Erik\.emscripten_cache\wasm\libpthread-mt.a C:\Users\Erik\.emscripten_cache\wasm\libc_rt_wasm.a C:\Users\Erik\.emscripten_cache\wasm\libsockets-mt.a --allow-undefined-file=C:\Users\Erik\AppData\Local\Temp\tmpehcbusn1.undefined --import-memory --import-table --shared-memory -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export __errno_location --export fflush --export emscripten_get_global_libc --export __pthread_tsd_run_dtors --export __emscripten_pthread_data_constructor --export _get_tzname --export _get_daylight --export _get_timezone --export memcpy -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (1)
make.exe[2]: *** [dist/Release/emscripten-Windows/monitor-2620.js.exe] Error 1
make.exe[2]: Leaving directory `/c/AerCon Software/web_emulation/Monitor-2620'
make.exe[1]: *** [.build-conf] Error 2
make.exe[1]: Leaving directory `/c/AerCon Software/web_emulation/Monitor-2620'
make.exe": *** [.build-impl] Error 2
```

**Comment by sbc100** [comment]
I think maybe the `LLD_REPORT_UNDEFINED` is causing some false positives here.    I think I'm going to remove the advice pointing people to using it.   Does your problem still exist if you remove this flag?

**Comment by friesendrywall** [comment]
No, its still there.  Its somewhat of a nebulous issue.  --clear-cache makes it change, but now it moved to something in my program that exists, so I really don't know why I'm getting these undefined symbols.

Incidentally, the only clue I'm getting about this so far is that the first included file ADC.o is where the missing symbols are locations.

`emcc -s ASYNCIFY=1 -s USE_PTHREADS -Wno-incompatible-pointer-types-discards-qualifiers -Wno-pointer-sign -Wno-incompatible-pointer-types -O0 -g --source-map-base    -o dist/Release/emscripten-Windows/monitor-2620.js build/Release/emscripten-Windows/ADC.o build/Release/emscripten-Windows/AerMain.o build/Release/emscripten-Windows/Aeration.o build/Release/emscripten-Windows/Alarms.o build/Release/emscripten-Windows/Alerts.o build/Release/emscripten-Windows/BitMapHeader.o build/Release/emscripten-Windows/Buoy.o build/Release/emscripten-Windows/CRC.o build/Release/emscripten-Windows/Combined.o build/Release/emscripten-Windows/Controlprocess.o build/Release/emscripten-Windows/KS_0108.o build/Release/emscripten-Windows/L37x29.o build/Release/emscripten-Windows/Logging.o build/Release/emscripten-Windows/Menu.o build/Release/emscripten-Windows/MyTimers.o build/Release/emscripten-Windows/Primitive.o build/Release/emscripten-Windows/Satisfiers.o build/Release/emscripten-Windows/SystemLog.o build/Release/emscripten-Windows/lc256.o build/Release/emscripten-Windows/qmatrix.o build/Release/emscripten-Windows/rtcc.o build/Release/emscripten-Windows/splash.o build/Release/emscripten-Windows/time.o build/Release/emscripten-Windows/web_main.o 
`

**Comment by sbc100** [comment]
Can you show the output of the command?  (the failing one).  I assume the missing symbol is reported later on (once you removed `LLD_REPORT_UNDEFINED`).

**Comment by sbc100** [comment]
Also the description implies the the link succeeds when you don't pass ` --generate-source-map`?  Is that correct?

**Comment by friesendrywall** [comment]
It works now, not sure why, this could be closed.  The working build command is

`-s ASYNCIFY=1 -s USE_PTHREADS -Wno-incompatible-pointer-types-discards-qualifiers -Wno-pointer-sign -Wno-incompatible-pointer-types -g4 -O3 -s ASYNCIFY_STACK_SIZE=32767 --source-map-base http://emscripten.test --generate-source-map`
