### ISSUE TITLE
calledRun flag not reset at startup

### ISSUE THREAD

**Issue by alekzander2005** [emscripten-core/emscripten#10785]
If you run two wasm application subsequently on the same page, then second one wouldnt run, because calledRun flag will have earlier stored value about first application.

It can be fixed by changing
var calledRun;
to
var calledRun = false;
in src/postamble.js

**Comment by kripken** [comment]
How are the two compiled? If one's global variables collide with the other, I think a lot more problems would happen than `calledRun` (like `Module` itself would collide, and exports). So I don't think I understand the scenario you describe.

In general though, the intended solution for this is to use `MODULARIZE`. Then they don't all use the global scope, and won't collide.

**Comment by alekzander2005** [comment]
Hi! I will definitley try this MODULARIZE, thank you.
I dont think it's worth your time to dig into our scenario.
If this isnt a bug, then it' all right, sorry that i bothered you.

**Comment by kripken** [comment]
No problem, and let us know if you have any issues with MODULARIZE.
