### ISSUE TITLE
libdeh265 library porting issue with emscripten compiler 

### ISSUE THREAD

**Issue by kuldeepmore** [emscripten-core/emscripten#10784]
I am trying to build libde265 using emscripten compiler but I am getting following build error.
I am using following make files and source code to build libdeh265.
[https://github.com/strukturag/libde265]
I have done the right setup for emscripten compiler as mention in official document.Also I am able to build other libraries as well using current setup but not this one. 
I have attached the error logs and how I have setup the emscripten to this issue please check.
[buildissue.txt](https://github.com/emscripten-core/emscripten/files/4392759/buildissue.txt)

**Comment by sbc100** [comment]
The error seems to be coming from configparam code:

```
In file included from configparam.cc:23:
In file included from ./configparam.h:30:
In file included from /home/dell/Kuldeep/WebAssembly/emsdk/upstream/emscripten/system/include/libcxx/vector:274:
```

```
/home/dell/Kuldeep/WebAssembly/emsdk/upstream/emscripten/system/include/libcxx/memory:2147:9: error: cannot initialize a member subobject of type 'int *' with an rvalue of type 'long'
      : __value_(_VSTD::forward<_Up>(__u))
```

Perhaps there is some incompatibility between the code you are trying to build and the C++ library that emscripten provides? (libc++ : https://libcxx.llvm.org/).

One word of advice when using autoconf you almost certainly want to pass `--disable-shared` so that you get static library as emscripten doesn't support shared libraries in the normal sense of the word.

Are you using the `emconfigure` command to drive the autoconf?

**Comment by kuldeepmore** [comment]
I have used `--disabled-shared` but still getting same error.
Also I am using `emconfigure` to build the library.

**Comment by sbc100** [comment]
I think you are going to have to take a look at the code in `configparam.cc` and see why its not compiling.

**Comment by sbc100** [comment]
If you can't figure it out by inspecting the code you can try finding the failing command (the one that compiles `configparam.cc` for example) and running it with `-E` to generate a pre-processed output file and then attaching that file to this issue.    That way its possible for someone else to reproduce the issue locally and see what is wrong with that code.

**Comment by kuldeepmore** [comment]
I have checked the code of `configparam.cc` and it is giving error for including `vector` header file.
any input why it is not able to include the standard header file.

**Comment by sbc100** [comment]
This looks like a some kind of C++ template instantiation issue that you should be able to debug and fix at your end.    It could be an issue with libc++, but most likely the issue is in your code.

If you want us to help more with it we would need to see the source code.  The easiest way to attach the source code is to run the failing command with `-E` which will generate the pre-processed  output.

**Comment by kuldeepmore** [comment]
Thanks for quick response. I have tried to build same source code on on same machine with gcc/g++ compiler and it is able to build it successfully, So I don;t think so issue in source code.
Also if you want me to attache source code then please let me know where should I give option `-E` which will generate the pre-processed output.I have attached the build script to this thread now, please look at it. 
[build.zip]
(https://github.com/emscripten-core/emscripten/files/4727561/build.zip)
Also let me know where this pre-processed output generated(I mean location).
Also I already mentioned the source is there on git on following link.
[source](https://github.com/strukturag/libde265.js)

**Comment by kuldeepmore** [comment]
Now I am able to build the library successfully using emscripten emscripten-1.38.30 the issue is the source code I was using is very old and has some deprecated emcc/++ option.Now I have downloaded the latest source code and tried to build then it is able to build it successfully.

But when I upgraded my emscripten  to 1.39.11 then it is not able to build the latest code please check the attached error package which contain error log as well as diagnostic files.
[build_emscripten_1.39.zip](https://github.com/emscripten-core/emscripten/files/4727928/build_emscripten_1.39.zip)

**Comment by LeviPesin** [comment]
I have the same issue when building https://github.com/strukturag/libheif (it uses libde265) using https://github.com/strukturag/libheif/blob/master/build-emscripten.sh:
```
In file included from configparam.cc:23:
In file included from ./configparam.h:30:
In file included from /home/levi/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/vector:276:
In file included from /home/levi/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__bit_reference:15:
In file included from /home/levi/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/algorithm:653:
/home/levi/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/memory:1229:9: error: cannot initialize a member subobject of type 'int *' with an rvalue of type 'long'
      : __value_(_VSTD::forward<_Up>(__u))
        ^        ~~~~~~~~~~~~~~~~~~~~~~~~
```
Is there some way to fix it?

**Comment by LeviPesin** [comment]
It seems that issue is with libde265 1.0.2 and changing LIBDE265_VERSION from 1.0.2 to 1.0.8 in https://github.com/strukturag/libheif/blob/master/build-emscripten.sh fixes the issue.
