### ISSUE TITLE
Run emcc command from nodejs spawn : how to set stdin buffer and get stdout result.

### ISSUE THREAD

**Issue by pierreglibert** [emscripten-core/emscripten#10806]
Hi community :)
I tried use emcc command line from nodejs script without input & output arguments.
It looks like this : 

```
var emccProcess = childProcess.spawn(pathOfEmcc , args);

emccProcess.stdin.write("int main(int argc, char const *argv[]) {return 0;}");

emccProcess.stdin.pipe(gulp.dest(path.resolve(outputDirectory)));

emccProcess.stdout.on('data', (data) => {
     console.log("stdout" + data)
});
```

The compiler return an error and ask to specify the input & output files.
Is it possible to pass a buffer in stdin & get the result in stdout ?

Thanks for your help,
Pierre.

**Comment by sbc100** [comment]
Just like with clang and gcc, if you want compile from stdin you need to pass `-` as an input.

**Comment by pierreglibert** [comment]
hi @sbc100 :)
Thanks for your help. 
I have this : "shared:ERROR: -: Unknown file suffix when compiling to LLVM bitcode!"

my code : 

```
var emccProcess = childProcess.spawn('emcc', ['-'], {stdio : ['pipe', 'pipe', 'pipe'], shell : true});

var src = fs.createReadStream(this._inputFilePath).on('open', () => {
    console.log('open')
    src.pipe(emccProcess.stdin)
})

emccProcess.stdout.on('data', (data) => {
    console.log("stdin" + data)
});
emccProcess.stdin.on('data', (data) => {
    console.log("stdin" + data)
});

emccProcess.stderr.on('data', (data) => {

    console.log("stderr" + data)

    emccProcess.kill();

    if (onError) {
        onError(data);
    }

});

emccProcess.on('close', (code) => {
    if (onSuccess) {
        onSuccess();
    }
});

emccProcess.on('SIGINT', () => {
    emccProcess.kill();
});
```

**Comment by sbc100** [comment]
Normally when compiling from stdin you also need to specify that input language.    Does adding `-x c` or `-x c++` help?  Also what kind of output to you want?  emscripten currently (i'm trying to remove that) changes its behaviour based on the name of the output file (so adding `-o somefile.js` will give you js output for example.

**Comment by pierreglibert** [comment]
Hi @sbc100.
I try to pass the buffer content of the input file to stdin et catch the buffer result returned by emscripten. With nodejs stream classes, I can keep the buffer without write it in directory.

**Comment by sbc100** [comment]
I'm not sure clang supported wrinting it output to stdout.   Are you able to make this work with raw clang?  We aim to be command line compatible with clang as much as possible.  

You could try `-o /dev/stdout` but that would I guess be limited to only working on linux/unix?

**Comment by pierreglibert** [comment]
ok, I will come back soon after doing some tests. Thank you ;)
