### ISSUE TITLE
How to compile C ++ AMP project or OpenCL project with emcc

### ISSUE THREAD

**Issue by xmq1996** [emscripten-core/emscripten#10800]
1. I tried to compile with the OpenCL project. On the Windows side, because OpenCL provided by NVIDIA's CUDA is a lib file, it seems that emcc cannot recognize this type of file. Then I tried it again on the ubuntu side, and because emcc does not seem to support linking OpenCL.so files. I looked for a long time and couldn't find a solution.
2. I also tried to compile the C ++ AMP project, but the amp.h file could not be obtained. After I added a series of header file search paths, the vcruntime.h file reported more than 20 errors, and I saw some errors. It felt like there was no syntax error in that place.

**Comment by sbc100** [comment]
You can't use pre-compiled libraries for other platforms with emscripten.   You either need to compile OpenCL from source yourself, or you would need NVIDIA to provide an emscripten-built version of their  library.     Where are you expecting to be able to run the your OpenCL code? 

Please open a separate issue for the second problem and please include the full command you ran along with its full output.

**Comment by xmq1996** [comment]
My original intention was to use some parallel computing language in my C ++ project to optimize the project, and then run it on the front end through wasm compilation.So I tried C ++ AMP and OpenCL framework.
   1.For the OpenCL version provided by NVIDIA, I have not found the compiled version for the time being, so I cannot recompile to get the .a file.
    2.For the C ++ AMP project, I just included the amp.h file in vs2015, and vs2015 can execute correctly. But when compiling with wasm, it will report amp.h errors; then I found the location of amp.h myself, included the path with -I in the emcc code, and then reported that many files were not found It is the official C ++ library), and I also add the path to the emcc code, and the final error will be a series of errors about the header file vcruntime.h.
     My compile command is as follows:emcc   -I "D:\vs2015.com_chs\VC\atlmfc\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" -I "C:\Program Files (x86)\Windows Kits\8.1\Include\um" -I "C:\Program Files (x86)\Windows Kits\8.1\Include\shared"  -I "D:\vs2015.com_chs\VC\include"  main.cpp -s "EXPORTED_FUNCTIONS=['_getPoint']" -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" -s ERROR_ON_UNDEFINED_SYMBOLS=0  -o math.js
![image](https://user-images.githubusercontent.com/29848518/78004726-18a02780-736d-11ea-9241-d0185754c43a.png)
   I will post the Amp question separately later.

**Comment by xmq1996** [comment]
I found a copy of the AMP project code on the Internet, and it was confirmed that it can run normally in vs.
`#include <amp.h>
#include <iostream>
using namespace concurrency;

const int size = 5;

int main() {
	int aCPP[] = { 1, 2, 3, 4, 5 };
	int bCPP[] = { 6, 7, 8, 9, 10 };
	int sumCPP[size];
	// Create C++ AMP objects.
	array_view<const int, 1> a(size, aCPP);
	array_view<const int, 1> b(size, bCPP);
	array_view<int, 1> sum(size, sumCPP);
	sum.discard_data();
	parallel_for_each(
		// Define the compute domain, which is the set of threads that are created.
		sum.extent,
		// Define the code to run on each thread on the accelerator.
		[=](index<1> idx) restrict(amp)
	{
		sum[idx] = a[idx] + b[idx];
	}
	);
	// Print the results. The expected output is "7, 9, 11, 13, 15".
	for (int i = 0; i < size; i++) {
		std::cout << sum[i] << "\n";
	}
	system("pause");
	return 0;
}`

**Comment by engineer1109** [comment]
Emscripten is  a unix system. Use pthread.
