### ISSUE TITLE
how to use emcmake&emmake output .a file 

### ISSUE THREAD

**Issue by hxske** [emscripten-core/emscripten#10807]
I tried use emcmake to build an existing library project, and i got output .a file(ar archive), not a .js or .wasm file, how i use it in a js file. thank you
here is the files:

clib.c
```
EMSCRIPTEN_KEEPALIVE 
int myFunc(int a, int b)
{
	printf("hello wasm\n");
	return a + b;
}
```

```
CMakeLists:
cmake_minimum_required(VERSION 3.6)
PROJECT(CLIB)

set(SRC clib.c)
add_library(clib ${SRC})
```

command:
emcmake cmake ..
emmake make

**Comment by sbc100** [comment]
To create .js output you need to build and executable (i.e. `add_executable`)

**Comment by hxske** [comment]
> 
> 
> To create .js output you need to build an executable (i.e. `add_executable`)

got it and thanks
