### ISSUE TITLE
Javascript exceptions when calling some OpenGL functions with invalid shader ids

### ISSUE THREAD

**Issue by larsbohn** [emscripten-core/emscripten#10808]
Hi!

I'm using an older version of emscripten but by code reviewing latest I think this issue is still there.

As it seems there are several GL functions which give javascript exceptions when calling them with invalid params.

Concretely calling

```
glCompileShader(shaderId);
or
glShaderSource(shaderId, 1, &fragment_shader, NULL);

```
with **an invalid shaderId** gives a javascript exception:

```
my-app.js:7954 exception thrown: TypeError: Failed to execute 'compileShader' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.,TypeError: Failed to execute 'compileShader' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glCompileShader (http://localhost/root/my-app.js:9945:13)
```
Debugger says this comes from this line in emscripten:
```
 function _glCompileShader(shader) {
      GLctx.compileShader(GL.shaders[shader]);
    }
```
I suppose because the shader is completely missing in GL.shaders[].

There may be more of such issues, probably related to code also using GL objects as a param.

This is a bit of a problem because there is no way to react from C++ properly on programming errors, and I'm not sure what happens here in context lost scenarios (I can test that later if it helps you).

Do you think this could be fixed?

Regards,
Lars

**Comment by kripken** [comment]
It does look like the code is not robust against such programming errors. I think the idea is that you can build with `GL_ASSERTIONS` which will give you useful debug logging while developing, for such errors. Then in the release build you don't want that extra overhead.

If that's not enough, we could make `GL_ASSERTIONS` not just report the error but also behave like a native implementation would, that is, return without running JS code that crashes. Then you could run with `GL_ASSERTIONS` in release builds if you absolutely need that.

**Comment by larsbohn** [comment]
Thanks for the comment!

Our code base is developed in Visual Studio (mainly for good debugging and better test execution mechanisms, also we need to run in native environments), then recompiled with emscripten to be executed in browsers.

So we're relying quite heavily on having the same behaviour in native and browser environments.

For us it would be useful to have that same behaviour (so in the case of the glCompileShader it would do nothing, just set glError accordingly).

If that cannot be achieved at the very least it would be important to document all API's having different behaviour compared to desktop, else we're running blindly into issues in the field.

So having an assertion during development is less important I guess. Common practice with OpenGL is anyway to have glGetError after each gl call during development, and disable that in release builds (only keep it in critical places like tex allocations, which can run into out of memory issues).

Regards,
Lars

**Comment by kripken** [comment]
That makes sense, thanks. Seems reasonable to support this.

I'd prefer to not add a new option for this, but it looks like it fits under `GL_TRACK_ERRORS`, as that option enables more strict error handling. So I'd be happy with a PR that does the behavior you want, ifdefed with that flag. Perhaps you'd like to submit that?

**Comment by kripken** [comment]
I looked at this for a while, and I'm actually not sure what to do anymore. `GL_TRACK_ERRORS` is set to 1 by default, but just checks some errors, not all - docs say `GL errors that exist in GLES2 but do not exist in WebGL` which I am not sure I understand. But the direct problem is that if we add this to that option, we'd be increasing code size by default, which we don't want.

So perhaps we do need a new option?
