### ISSUE TITLE
TLS struct destructors not called when thread is not joined

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#10809]
With the following on Linux (or Windows Subsytem for Linux)/Ubuntu
```
#include <stdio.h>
#include <iostream>
#if EMSCRIPTEN
include <emscripten.h>
#else
#include <chrono>
#include <thread>
#endif

struct TlsDestructionMonitor
{
        public:
                  TlsDestructionMonitor() {
                          std::cout << "ctr " << std::uintptr_t(this);
                              printf("Constructor()\n");
                                }

        void Set()
        {
                printf("set\n");
        }

  ~TlsDestructionMonitor()
  {
    printf("dest\n");
  }
};

thread_local TlsDestructionMonitor tls_destructionMonitor;
void* doWork(void *arg)
{
        printf("thread doing work\n");
        tls_destructionMonitor.Set();
        return NULL;
}

int main()
{
        pthread_t thread;
        pthread_attr_t attr;
        void * retVal;

        printf("hello\n");
        int id = pthread_create(&thread, NULL, &doWork, NULL);
        if(!id)
        {
                printf("sleeping\n");
#if EMSCRIPTEN
                emscripten_sleep(1000);
#else
                std::this_thread::sleep_for(std::chrono::milliseconds(1000));
#endif
                printf("slept\n");
                //printf("joining\n");
                //                //pthread_join(thread, &retVal);
                //                                //printf("joined\n");
                                                                                                                        //                                        }
        }
        return(0);
}
```
Compile with
`g++ 1.cpp -lpthread -pthread`
and run
`./a.out`
and you get
```
hello
sleeping
thread doing work
ctr 140391460898558Constructor()
set
dest
slept
```
The `dest` is from the destructor of the struct.  Same code with
```
em++ t.cpp -s USE_PTHREADS=1 -o t.html --emrun -s PROXY_TO_PTHREAD=1 -s ASYNCIFY=1
```
And run it in New Edge (Chrome backend) and you get
```
hello
sleeping
thread doing work
ctr 5398504Constructor()
set
slept
```
The destructor is not called.  If you replace the main thread's sleep with a join it works the same on Linux and Emscripten.

Possibly related to https://github.com/emscripten-core/emscripten/issues/9251 although that's about `exit` and ending all threads.

**Comment by kripken** [comment]
cc @juj

**Comment by Akaricchi** [comment]
I'm fairly sure `EXIT_RUNTIME` is required to call C++ destructors after `main` or a thread returns. Did you try building with `-s EXIT_RUNTIME=1`?

**Comment by sbc100** [comment]
But these object are linked to the lifetime of the thread right?  They should get called when the thread exits, even while main is still running, as in this example.   If they are linked to `EXIT_RUNTIME` that would seem like bug too.

**Comment by Akaricchi** [comment]
Sorry, I'm not very familiar with how threads work in emscripten yet, so I'm mostly speculating. As far as I understand each thread runs in a worker and therefore has a separate JS "runtime", correct? With that in mind it *kind of* makes sense that it would depend on `EXIT_RUNTIME`, but I agree it's not desirable behavior. But if this isn't what's actually happening here then I'm sorry and please ignore me.

**Comment by juj** [comment]
The issue is that thread-local `cxa_thread_atexit` was incorrectly marked to be an alias of process-global `atexit`, hence the destructor was attempted to be run when the program quits (which in the default EXIT_RUNTIME=0 mode is never)

**Comment by yowl** [comment]
Thanks!
