### ISSUE TITLE
undefined symbol: __syscall3, __syscall5 and __syscall91

### ISSUE THREAD

**Issue by Robien** [emscripten-core/emscripten#10816]
Hello,

I use emsdk to build my C++ project to JS inside a docker image (debian buster) using the command:
`./emsdk install sdk-upstream-master-64bit` (I use master for browser compatibility issues) and it worked fine until yesterday, when I actually re-build my docker image.

Now, when I am compiling, I got:
```
/emsdk/emscripten/master/em++   -std=c++14 -O2 -g -Wall -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=10 -s EXIT_RUNTIME=1  -s PROXY_TO_PTHREAD=1 -s WEBSOCKET_DEBUG=1 -lwebsocket.js --emrun -s DISABLE_EXCEPTION_CATCHING=1 -s PTHREAD_POOL_SIZE=10 -s USE_PTHREADS=1 -s WASM=1 -s BINARYEN_METHOD='native-wasm' -s EXPORTED_FUNCTIONS='[_main]' -s EXIT_RUNTIME=1 @CMakeFiles/sc-browser.dir/objects1.rsp  -o sc-browser.html @CMakeFiles/sc-browser.dir/linklibs.rsp
error: undefined symbol: __syscall3
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: ___syscall3 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: __syscall5
warning: ___syscall5 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: __syscall91
warning: ___syscall91 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/emsdk/node/12.9.1_64bit/bin/node /emsdk/emscripten/master/src/compiler.js /tmp/tmp8u2ynhrs.txt' failed (1)

```
Native compilation works perfectly.

So I tried the EXPORTED_FUNCTIONS flag as suggested but it didn't change anything. I tried with -O0 -Os and -O2.

syscall 3 is 'read', syscall 5 is "open" and syscall 91 is mmap (map or unmap files or devices into memory). Since I am not using anything file related (except some std::cout << ) I tried the flags -s FORCE_FILESYSTEM=0 and -s FORCE_FILESYSTEM=1 without success.

Any ideas?

Thank you.

**Comment by sbc100** [comment]
Did you clear our any cached libraries?

This change renamed the syscall import from libc so thay now have meaning names: e,g `__sys_read`.   if you have an old libc it might still be referencing the wrong names.

**Comment by sbc100** [comment]
I'm working on a change that will allow you to see where the undefined symbols originate.  Its still has issues but you can try it out with `-s LLD_REPORT_UNDEFINED`

**Comment by Robien** [comment]
Thank you for the fast reply.
Yes, I had some cached library I totally forgot about it. I cleared it and it fixed the issue, thank you!

Unfortunately I can't test the command `-s LLD_REPORT_UNDEFINED` because I have already cleared the cache. If you are interested I can roll back to an older version and come back to master to reproduce the bug in order to test it.
