### ISSUE TITLE
compile error : /usr/include/features.h:367:12: fatal error: 'sys/cdefs.h' file not found

### ISSUE THREAD

**Issue by pans0ul** [emscripten-core/emscripten#10818]
I want to try compile [camera model] (https://github.com/heguixiang/Remove_ROS_VINS/tree/master/camera_model) using emcripten 

the command  _emconfigure cmake .. _  was passed  

but the error come from  _emmake make _ 
here is  output logs ：

![compile error](https://user-images.githubusercontent.com/35412241/78097911-2bb80380-7410-11ea-9fa7-d8a1addefe36.jpg)

same text :

`pans0ul@pans0ul:~/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/wbuild$ emconfigure cmake ..
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Found required Ceres dependency: glog
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, OpenMP, Multithreading]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pans0ul/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/wbuild
pans0ul@pans0ul:~/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/wbuild$ emmake make    make: ['make']
[  7%] Building CXX object CMakeFiles/camera_model.dir/src/chessboard/Chessboard.cc.o
In file included from /home/pans0ul/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/src/chessboard/Chessboard.cc:1:
In file included from /home/pans0ul/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/include/camodocal/chessboard/Chessboard.h:4:
In file included from /home/pans0ul/Library/boost_1_66_0/build_wasm/include/boost/shared_ptr.hpp:17:
In file included from /home/pans0ul/Library/boost_1_66_0/build_wasm/include/boost/smart_ptr/shared_ptr.hpp:17:
In file included from /home/pans0ul/Library/boost_1_66_0/build_wasm/include/boost/config.hpp:53:
In file included from /home/pans0ul/Library/boost_1_66_0/build_wasm/include/boost/config/detail/select_platform_config.hpp:104:
In file included from /home/pans0ul/Library/boost_1_66_0/build_wasm/include/boost/config/detail/posix_features.hpp:18:
In file included from /usr/include/unistd.h:25:
/usr/include/features.h:367:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^~~~~~~~~~~~~
1 error generated.
shared:ERROR: '/home/pans0ul/workSpace/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=8 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/home/pans0ul/.emscripten_cache/wasm-obj/include -I/home/pans0ul/Library/boost_1_66_0/build_wasm/include -I/usr/local/include -I/usr/include/eigen3 -I/usr/include -I/home/pans0ul/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/include -isystem /home/pans0ul/Library/opencv-3.2.0/build_wasm -isystem /home/pans0ul/Library/opencv-3.2.0/include -isystem /home/pans0ul/Library/opencv-3.2.0/include/opencv -isystem /home/pans0ul/Library/opencv-3.2.0/modules/core/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/flann/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/imgproc/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/ml/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/photo/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/video/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/viz/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/imgcodecs/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/shape/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/videoio/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/highgui/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/objdetect/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/superres/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/ts/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/features2d/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/calib3d/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/stitching/include -isystem /home/pans0ul/Library/opencv-3.2.0/modules/videostab/include -std=c++11 -O3 -fPIC -c -DEMSCRIPTEN /home/pans0ul/workSpace/VINS-withoutROS/VINSnonROS/Remove_ROS_VINS/camera_model/src/chessboard/Chessboard.cc -Xclang -isystem/home/pans0ul/workSpace/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/camera_model.dir/src/chessboard/Chessboard.cc.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
CMakeFiles/camera_model.dir/build.make:80: recipe for target 'CMakeFiles/camera_model.dir/src/chessboard/Chessboard.cc.o' failed
make[2]: *** [CMakeFiles/camera_model.dir/src/chessboard/Chessboard.cc.o] Error 1
CMakeFiles/Makefile2:92: recipe for target 'CMakeFiles/camera_model.dir/all' failed
make[1]: *** [CMakeFiles/camera_model.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by pans0ul** [comment]
**my cmakecache.txt :** 
[CMakeCache.txt](https://github.com/emscripten-core/emscripten/files/4412715/CMakeCache.txt)

**Comment by pans0ul** [comment]
I think something wrong ganna from the difference between webAssembly code running the VM machine and c++ running the local based system . So emscritpen can't find their own headfile for compiling . is it right ? 
and how can I do solve this issue ?
thanks you

**Comment by sbc100** [comment]
The primary problem is that shouldn't be using system include path such as -I/usr/include with emscripten.    This is because it is a cross compiler and it ships with its own headers and libraries.   The headers and libraries on your system are not compatible.

**Comment by pans0ul** [comment]
> The primary problem is that shouldn't be using system include path such as -I/usr/include with emscripten. This is because it is a cross compiler and it ships with its own headers and libraries. The headers and libraries on your system are not compatible.

so, what's right include path ? Im not familier with emscripten .  thank you

**Comment by sbc100** [comment]
The standard include paths should all be included by default, you don't need to add them.   You would only want to add a new include paths if you had new non-standard headers that you wanted to build against.

The stand headers live in various directories within `/emscripten/system/`.  You can see them added as system include paths at the beginning of your error message.

**Comment by pans0ul** [comment]
> The standard include paths should all be included by default, you don't need to add them. You would only want to add a new include paths if you had new non-standard headers that you wanted to build against.
> 
> The standard headers live in various directories within `/emscripten/system/`. You can see them added as system include paths at the beginning of your error message.

I didnt find  `sys/cdefs.h`  file in `/emscripten/system/`  . It seems that it's no existed.

I can only find one in `/usr/include`

![2020-04-01_222355](https://user-images.githubusercontent.com/35412241/78229709-ede7d780-7502-11ea-9fa2-4386c5853f76.jpg)

Eventually , I solve this issue by replacing staic glog library .

then ,turned out a new issue ..

![compile error -eigen 3](https://user-images.githubusercontent.com/35412241/78229936-3ef7cb80-7503-11ea-96be-7f3f6ed421cf.jpg)

It said that `fatal error: 'eigen3/Eigen/Dense' file not found`, but checked this path and file is right . what's the problem? is the emscripten can't identify no suffix headfile ?

**Comment by sbc100** [comment]
Great!  Can this issue be closed now?

**Comment by RReverser** [comment]
@sbc100 I stumbled upon this issue while debugging same error (missing `sys/cdefs.h`), and I'm not sure I understand the resolution here. Are you saying that users should include `sys/cdefs.h` from a system directory (`.../include/x86_64-linux-gnu`)? It seems counter-intuitive that it's not part of the `emscripten/system`, especially given that it contains platform-specific definitions.

**Comment by sbc100** [comment]
No.. the problem where was that the OP was adding a system include path (.e.g `-I/usr/include/xxx`) and the files included via that incorrect path themselves were looking for `sys/cdefs.h`.

As far as I know `sys/cdefs.h` is not part of musl or emscripten.   Do you have a project that wants to include this file directly?

**Comment by RReverser** [comment]
@sbc100 I did have one when asking the question, but when I tried to comment out that `#include`, it still works... so I guess not really necessary.
