### ISSUE TITLE
wasm-ld: warning: function signature mismatch when compiling with -flto=thin

### ISSUE THREAD

**Issue by amir-l** [emscripten-core/emscripten#10831]
Hi,
I'm trying to compile with IPO/LTO and I'm getting:
wasm-ld: warning: function signature mismatch: _ZN12wre_frontend12ModelFactory11createModelERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
>>> defined as () -> void in ModelFactory.cpp.o
>>> defined as (i32, i32, i32) -> void in lto.tmp

Without IPO/LTO there isn't any wasm-ld warning.

This maybe happen because the function implementation is defined in a different compilation unit from the EMSCRIPTEN_BINDINGS usage. This function isn't used except in the bindings:
emscripten::class_<wre_frontend::ModelFactory>(“ModelFactory”)
.constructor<>()
.function(“createModel”, &wre_frontend::ModelFactory::createModel);

Adding __attribute__((used)) to the function doesn't solve the issue.
I tried both with SDK 1.39.7 and 1.39.11.

The workaround: replace the function binding with a wrapper that exists in same compilation unit of the binding (implemented in the header file of the class). The wrapper calls the original function.

Related issue:
I would like to have linker warnings treated as errors.
Neither -Werror nor -Xlinker --fatal-warnings error out the function signature mismatch.
According to https://lld.llvm.org/WebAssembly.html - The --fatal-warnings flag can be used to disable generating stub functions and error out if mismatched are found.

**Comment by sbc100** [comment]
Regarding the linker flags, does `-Wl,--fatal-warnings` work for you?   I don't think we support `-Xlinker` but I think we should.

**Comment by amir-l** [comment]
Thanks, -Wl,--fatal-warnings solves the linker flags issue.
Note that target_link_options(${target_name} PRIVATE "LINKER:--fatal-warnings") produces -Xlinker

**Comment by amir-l** [comment]
Still happens with 1.39.17

**Comment by amir-l** [comment]
It is specific to thin LTO, regular/full works.
Since INTERPROCEDURAL_OPTIMIZATION produces -flto=thin, I think the toolchain (Emscripten.cmake) should change CMAKE_CXX_COMPILE_OPTIONS_IPO to full.

**Comment by sbc100** [comment]
Sounds reasonable, at least until we have more thin LTO coverage.  Would you be willing to create a PR?

**Comment by amir-l** [comment]
https://github.com/emscripten-core/emscripten/pull/11517

**Comment by ravisumit33** [comment]
I am facing this issue when I apply `-flto` at compile & link time. Otherwise no warnings come. I am using emscripten version 2.0.20. @sbc100 Is it planned to get fixed ?

**Comment by sbc100** [comment]
@ravisumit33 can you describe the issue you are seeing?  Is it just a warning?  Does the resulting program fail?   Can you share the full error message?

**Comment by ravisumit33** [comment]
> @ravisumit33 can you describe the issue you are seeing? Is it just a warning? Does the resulting program fail? Can you share the full error message?

At link time I m getting warnings (not errors) from wasm-ld like below. Build succeeds without any error.
<img width="1385" alt="Screenshot 2021-09-02 at 11 59 45 PM" src="https://user-images.githubusercontent.com/19284116/131897542-eaba4937-6b50-4667-ac05-28fcc5d41be4.png">

**Comment by sbc100** [comment]
And does the application work despite the warning?  (i.e. can you ignore it?)

Would you might copy and pasting the text of the message so that I can feed it into `c++filt` and find the demanded symbol name?  (including an imagine makes this a lot harder).

**Comment by andrewevstyukhin** [comment]
Hi @sbc100,
minimal repro is at [link](https://github.com/andrewevstyukhin/emscripten/commit/c3cf95577295099ae564c6b4b250ce21e6a76d21)

`bash ./test.sh`
> [100%] Linking CXX executable app.js
wasm-ld: warning: function signature mismatch: _ZN9Namespace8Delegate3OnEENSt3__28functionIFvNS0_6ResultEEEE
defined as () -> void in engine/libengine.a(Dispatcher.cpp.o)
defined as (i32, i32) -> void in lto.tmp

**Comment by andrewevstyukhin** [comment]
Breaking news about [reproduction](https://github.com/andrewevstyukhin/emscripten/tree/thinLtoProblem/_thinLtoProblem):

1. Problem exists if I use `target_link_libraries(app PUBLIC engine)` but disappears for `target_link_options(app PUBLIC ${LINK_FLAGS} engine/libengine.a)`

2. Order of objects matters:
broken: `em++.py CMakeFiles/app.dir/Main.cpp.o engine/libengine.a -o app.js`
working: `em++.py engine/libengine.a CMakeFiles/app.dir/Main.cpp.o -o app.js`

Broken order comes from `cmake version 3.22.1` and
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0 (3fd52e107187b8a169bb04a02b9f982c8a075205)`

**Comment by sbc100** [comment]
Is this still an issue with the latest version of emscripten?

**Comment by andrewevstyukhin** [comment]
For the latest emsdk installation (3.1.23) the issue is still relevant.
> _thinLtoProblem>bash test.sh
[100%] Linking CXX executable app.js
wasm-ld: warning: function signature mismatch: _ZN8Delegate3OnEENSt3__28functionIFvvEEE
 defined as () -> void in engine/libengine.a(Dispatcher.cpp.o)
 defined as (i32, i32) -> void in lto.tmp
[100%] Built target app

I can say these problems occur even for the `-flto` when libraries form diamond dependencies.

**Comment by asmundnordstoga** [comment]
It looks like the same issue is happening when linking with the proj library:
asm-ld: warning: function signature mismatch: _ZTv0_n32_NK5osgeo4proj9operation15SingleOperation11gridsNeededERKNSt3__210shared_ptrINS0_2io15DatabaseContextEEEb
>>> defined as () -> void in myLib/libproj.a(singleoperation.cpp.o)
>>> defined as (i32, i32, i32, i32) -> void in lto.tmp

**Comment by adam-ce** [comment]
also happens when trying to build Qt with lto: https://bugreports.qt.io/browse/QTBUG-129522?filter=-2

**Comment by xermicus** [comment]
What is the status of this issue?

**Comment by michaelharmonart** [comment]
https://github.com/llvm/llvm-project/pull/136197
is now merged, can anyone confirm if that fixes the issue?

**Comment by andrewevstyukhin** [comment]
I repeated [steps](https://github.com/emscripten-core/emscripten/issues/10831#issuecomment-1274111244) for the latest emsdk version `4.0.7` and expectedly got broken signatures:
> [100%] Linking CXX executable app.js
wasm-ld: warning: function signature mismatch: _ZN8Delegate3OnEENSt3__28functionIFvvEEE
 defined as () -> void in engine/libengine.a(Dispatcher.cpp.o)
 defined as (i32, i32) -> void in lto.tmp
[100%] Built target app

Then I compiled `llvm-project` with parameters `cmake -DLLVM_ENABLE_PROJECTS=lld -DLLVM_TARGETS_TO_BUILD=WebAssembly`, replaced `wasm-ld` and successfully passed the test:
> [100%] Linking CXX executable app.js
[100%] Built target app

**Comment by sbc100** [comment]
That sounds like this can be closed then, but llvm has not yet rolled into emsdk, so I'll wait until then before closing.

**Comment by andrewevstyukhin** [comment]
Hi,
emsdk release 4.0.8 still failed the test:
> [100%] Linking CXX executable app.js
wasm-ld: warning: function signature mismatch: _ZN8Delegate3OnEENSt3__28functionIFvvEEE
 defined as () -> void in engine/libengine.a(Dispatcher.cpp.o)
 defined as (i32, i32) -> void in lto.tmp
[100%] Built target app

**Comment by andrewevstyukhin** [comment]
I'm glad to write these words: emsdk 4.0.9 `passed` the test.
> [100%] Linking CXX executable app.js
[100%] Built target app
