### ISSUE TITLE
NODEFS: Unable to open file with O_NOFOLLOW

### ISSUE THREAD

**Issue by mpotthoff** [emscripten-core/emscripten#10839]
I'm trying to use sql.js together with NODEFS. Using the virtual filesystem everything works fine but as soon as I start using NODEFS I'm getting an `EINVAL` from the `open()` call.
Turns out that it is caused by the `O_NOFOLLOW` flag that is always used by sqlite on systems which have it defined.

The flag does seem to be handled in the `open()` function of `library_fs`:
https://github.com/emscripten-core/emscripten/blob/3369df9ffb5178f986d7ca9361df7cfbcd99c772/src/library_fs.js#L1022-L1024

But `flagsForNode()` in `library_nodefs` doesn't know about it and trows an `EINVAL`:
https://github.com/emscripten-core/emscripten/blob/3369df9ffb5178f986d7ca9361df7cfbcd99c772/src/library_nodefs.js#L85-L103

So I guess the flag should be unset like `O_EXCL` and `O_TRUNC`?
https://github.com/emscripten-core/emscripten/blob/3369df9ffb5178f986d7ca9361df7cfbcd99c772/src/library_fs.js#L1068-L1069

---

And one other thing I noticed: The current handling of `O_NOFOLLOW` in `library_fs` is a bit different than specified:
http://man7.org/linux/man-pages/man2/open.2.html
> If pathname is a symbolic link, then the open fails, with the error ELOOP.

Currently it behaves more like if `O_PATH` is set too:
> If pathname is a symbolic link and the O_NOFOLLOW flag is also specified, then the call returns a file descriptor referring to the symbolic link.

I'm not sure whether this should be changed too.

**Comment by kripken** [comment]
Thanks @mpotthoff , I think you might be right. PR would be welcome!

(I'm not sure about `NOFOLLOW`, we'd need to look into that more.)
