### ISSUE TITLE
Crashes when using invalid file for -s EXPORTED_FUNCTIONS=@filename

### ISSUE THREAD

**Issue by jtenner** [emscripten-core/emscripten#10841]
I accidentally pointed the compiler at the c file instead of a file with a list, and it output the following user unfriendly error:

```py
Traceback (most recent call last):
  File "/home/jtenner/emsdk/upstream/emscripten/emcc.py", line 3917, in <module>
    sys.exit(run(sys.argv))
  File "/home/jtenner/emsdk/upstream/emscripten/emcc.py", line 1392, in run
    shared.Settings.EXPORTED_FUNCTIONS += ['_malloc', '_free']
```

**Comment by sbc100** [comment]
Can you include that contents of @filename that causes the crash?  And also the full stackstrace (I don't see the actual python exception here.  I'm guessing its trying add a list of a non-list?

**Comment by jtenner** [comment]
I pointed it at `telnet.c`. It was a c file, not a file with a list.

**Comment by jtenner** [comment]
```
> libtelnet-ts@0.0.1 compile /home/jtenner/libtelnet
> emcc -O2 libtelnet.c -s EXPORTED_FUNCTIONS=@libtelnet.c -o build/libtelnet.js

Traceback (most recent call last):
  File "/home/jtenner/emsdk/upstream/emscripten/emcc.py", line 3917, in <module>
    sys.exit(run(sys.argv))
  File "/home/jtenner/emsdk/upstream/emscripten/emcc.py", line 1392, in run
    shared.Settings.EXPORTED_FUNCTIONS += ['_malloc', '_free']
TypeError: cannot concatenate 'str' and 'list' objects
```

Looks like it was trying to concatenate a str with a list.

The file is located here:

https://github.com/jtenner/libtelnet-ts/blob/master/libtelnet.c

**Comment by jtenner** [comment]
Okay. Obviously the real solution here is to use emscripten like it's supposed to be used. I just think it might be useful to type check that property.
