### ISSUE TITLE
undefined symbol: __powidf2 (-ffast-math)

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#10853]
Hi. I have project that works fine with `-ffast-math`. It compiles fine with this flag for native, but when I used this flag with emscripten I have this, error:
```
error: undefined symbol: __powidf2
```

setting `-s ERROR_ON_UNDEFINED_SYMBOLS=0` have no effect, if I set `-s LLD_REPORT_UNDEFINED`, then I have this error:

```
error: DISABLE_EXCEPTION_THROWING was set (likely due to -fno-exceptions), 
which means no C++ exception throwing support code is linked in, 
but such support is required by symbol __cxa_call_unexpected. 
Either do not set DISABLE_EXCEPTION_THROWING (if you do want exception throwing) 
or compile all source files with 
-fno-except (so that no exceptions support code is required); 
also make sure DISABLE_EXCEPTION_CATCHING is set to the right value -
 if you want exceptions, it should be off, and vice versa.
```

but project built with `-fno-exceptions` already. When I add `-fexceptions` then output is:
```
wasm-ld: error: symbol exported via --export not found: _get_environ
```

Without using `-ffast-math` project compiles and work fine.
emscripten 1.39.8 (commit a490cd1222830d860873bbfc38abcb0a25b28a68)

**Comment by kripken** [comment]
Is that with the upstream backend (default in 1.39.8. that is, if you didn't install the fastcomp version)? Check with `emcc -v` to make sure.

With upstream I see `powidf2.c` is in the files to be built, so it should work there. With fastcomp it's not there.

About exceptions, did you build all source files and link with `-fno-exceptions`? If you have a precompiled library or something like that, it needs to be rebuilt. You can run `llvm-nm` on files to see if they contain `call_unexpected` to verify.

Maybe you can provide the code to test?

**Comment by caiiiycuk** [comment]
Thanks for advise. I updated to 1.39.11 and now it works. So, I think it's not a problem anymore.
