### ISSUE TITLE
shared:ERROR: asm2wasm failed (-1073740791) 

### ISSUE THREAD

**Issue by woxinchangdanzou** [emscripten-core/emscripten#10859]
shared:ERROR: 'D:/TechnologyStudy/emsdk/fastcomp\bin\asm2wasm GsealApp.temp.asm.js --total-memory=16777216 --trap-mode=allow --mem-max=2097152000 --wasm-only --enable-threads -g -o GsealApp.wast -S --mvp-features --enable-threads' failed (-1073740791)

Environment:
emcc 1.38.41 fastcomp

**Comment by kripken** [comment]
Closing in favor of the duplicate bug filed at https://github.com/WebAssembly/binaryen/issues/2725

(Please don't open duplicate issues in separate repos - many of the same people are subscribed to both, so you're just sending them duplicate emails, and worse, there may end up parallel conversations in the separate places, which confuse people looking for a solution later.)
