### ISSUE TITLE
Test -flto=thin

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#10868]
As suggested by @sbc100 this should work, but we don't test it yet.

If it works we should update the docs on the benefits etc.

**Comment by aykejriw** [comment]
@kripken I would like to take this issue.

**Comment by kripken** [comment]
@aykejriw Sure, a PR would be great!

You might find https://emscripten.org/docs/getting_started/test-suite.html helpful to get started. And the relevant suite of tests is in `tests/test_other.py` which has a bunch of LTO tests already (like `test_wasm_backend_lto`). Let us know if you have any questions.

**Comment by sbc100** [comment]
We now run the core test suite in thinlto mode so I think we can close this out.
