### ISSUE TITLE
code size, 1.39.3 vs 1.39.7

### ISSUE THREAD

**Issue by JayceLai** [emscripten-core/emscripten#10873]
compile repository: [ammo.js](https://github.com/kripken/ammo.js)

| file\version | 1.39.3 | 1.39.7 |
| -- | -- | --|
| ammo.js| 1980KB|2560KB|

It seems the file not to being uglify, or some option default value is change?

The code size has grown a lot when using 1.39.7, does someone knew how to optimize? thanks.

**Comment by kripken** [comment]
What command did you use to build? Not using closure is one possible issue.

When I try `python make.py closure` on 1.39.12 I get 1845KB.

**Comment by JayceLai** [comment]
Thanks for your reply. 
I use the same command script `make.py`, but not sure exactly command what is.
The code size grow maybe it only happened on 1.39.7.

Now i using 1.39.3 version, switch version is terrible for me due to the network, it very slow.
Is there a way to save multiple versions at the same time without redownloading when switching?

**Comment by kripken** [comment]
The emsdk should not download unnecessary files anymore, we recently fixed that. Make sure you are using the very latest version from master.

**Comment by JayceLai** [comment]
glad to hear about that, many thanks.
