### ISSUE TITLE
glGetIntegerv return glError for some Object, such as WebGLBuffer etc.

### ISSUE THREAD

**Issue by rssqian** [emscripten-core/emscripten#10875]
The issue is as follows.

GLint ret;
//if current GL_PIXEL_UNPACK_BUFFER_BINDING is 0, webgl will return null.
//library_webgl.js:emscriptenWebGLGet assert null is wrong, and throw glError without set ret 0.
glGetIntegerv(GL_PIXEL_UNPACK_BUFFER_BINDING, &ret);

The related pull request:
https://github.com/emscripten-core/emscripten/pull/10874

**Comment by waywardmonkeys** [comment]
@kripken The PR was merged for this, so this can be closed.

**Comment by kripken** [comment]
Thanks!
