### ISSUE TITLE
Missing / no longer emitting "use asm" directives?

### ISSUE THREAD

**Issue by diegocr** [emscripten-core/emscripten#10882]
Hello,

I am recompiling [dcraw.js](https://github.com/meganz/dcraw.js) using upstream and i've noticed that "almost/use asm"-directives are no longer emitted for `ASM_JS` builds?

For that one i do want a single-file, hence i cannot use wasm due the `unsafe-eval` requirement, you know - and well, also because i would like to retain backward compatibility with older browsers or the synchronous initialization nature.

To make sure is not something specific to dcraw.c i've tried a hello world example, and it's the same, i.e.

```c
#include <stdio.h>
int main(int argc, char *argv[]) {
    printf("Doh %d!\n", argc);
}
```

and then compiling with `emcc -O3 -s WASM=0 -o test.js test.c` generates such a file without "use/almost asm" directives.

fwiw, i am using:

```bash
$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.39.11
```

Given wasm is the default backend nowadays, is emitting valid asm.js no longer possible?

**Comment by kripken** [comment]
asm.js is no longer supported, but JS definitely is! That includes support for old browsers without wasm, single file, etc. etc. It's basically the same as before, just without writing "almost asm" or "use asm".

asm.js is a weird "in-the-middle" mode between JS and wasm, that made sense at the time, but not now. See https://v8.dev/blog/emscripten-llvm-wasm#javascript-output for more.

**Comment by diegocr** [comment]
I see, thanks for the details / article, good reading 👍
