### ISSUE TITLE
Send OffscreenCanvas to worker with WorkerAPI

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#10888]
I need an OffscreenCanvas (OSC) in my worker and I'm using the WorkerAPI and from what I see I don't have a possibility to either create or send such a canvas to the worker.

I see two possibilities:

**Possibility 1:**

Create the OSC in the Mainthread, add it to Module['canvas'] and send it to the worker right after the worker has been created.

In the worker in onmessage check for this and assign it again to Module['canvas'].

main.js
```
function _emscripten_create_worker(url) {
      url = UTF8ToString(url);
      var id = Browser.workers.length;
      var info = {
        worker: new Worker(url),
        callbacks: [],
        awaited: 0,
        buffer: 0,
        bufferSize: 0
      };
      if (Module['canvas']) { // An offscreen canvas has been assigned in some JavaScript earlier
        canvasObj = {
          canvas: Module['canvas']
        }
        info.worker.postMessage(canvasObj, [canvasObj.canvas])
      }
      info.worker.onmessage = function info_worker_onmessage(msg) {
         ... <code continues as usual>
```

worker.js
```
 if (msg.data.canvas && !Module['canvas']) {
    Module['canvas'] = msg.data.canvas;
    } else { // this was originally not in an else body
      var func = Module['_' + msg.data['funcName']];
      if (!func) throw 'invalid worker function to call: ' + msg.data['funcName'];
     ... <code continues as usual>
```

**Possibility 2:**

Create OSC directly in the worker.

Can we get this supported?

**Comment by kripken** [comment]
I believe all the current OffscreenCanvas support is with the pthreads mode. It could perhaps be added to the worker API (and then the worker and the main program would be separate, and perhaps not use pthreads at all), but I'm not sure how much work that would be. If someone's interested to investigate though, that sounds good.
