### ISSUE TITLE
__errno_location being misused.

### ISSUE THREAD

**Issue by diegocr** [emscripten-core/emscripten#10883]
Hello,

I've stumbled upon what does seem an incorrect usage of `__errno_location` while building dcraw.js as pointed in #10882

Check out this example code:

```c
#include <errno.h>
#include <signal.h>

int main(int argc, char *argv[])
{
    errno = ENOSYS;
    kill(0, EPERM);
}
```
compiled using `emcc -Oz -g1 -s MINIMAL_RUNTIME=1 -s SINGLE_FILE=1 -o test.js test.c`

```bash
$ grep -B 1 -n errno_location test.js
207-function ___setErrNo(value) {
208: if (Module["___errno_location"]) HEAP32[Module["___errno_location"]() >> 2] = value;
--
234-
235:var _main, ___errno_location;
--
239- _main = asm["c"];
240: ___errno_location = asm["d"];
```

as you can see there, the `___setErrNo()` function does access `Module["___errno_location"]` which will never be truthy, it should be `if (___errno_location) { ... }` or rather that whole line should just be `HEAP32[___errno_location() >> 2] = value;`

or am i missing something? :-)

**Comment by sbc100** [comment]
Why do you say that `Module["___errno_location"]` will never be truthy?   `__errno_location` is a C function that returns the address of errno.   `Module["___errno_location"]`  will be a function if the __errno_location C function is exported (in EXPORTED_FUNCTIONS) and undefined if not.

`__setErrNo` is a JS utility function the settings the libc errno variable.   Its called only JS and depends on the `__errno_location` which is defined in native C code.

**Comment by diegocr** [comment]
It will never be truthy, i was implying this is an issue by using `MINIMAL_RUNTIME` :-)

If you do compile without that flag, then it will be like you said, i.e.

```bash
$ emcc -Oz -g1 -s SINGLE_FILE=1 -o test.js test.c

$ grep -B 1 -n errno_location test.js
693-function ___setErrNo(value) {
694: if (Module["___errno_location"]) HEAP32[Module["___errno_location"]() >> 2] = value;
--
792-
793:var ___errno_location = Module["___errno_location"] = function() {
794: return (___errno_location = Module["___errno_location"] = Module["asm"]["d"]).apply(null, arguments);
```

As you can see, only in normal builds `Module["___errno_location"]`  is defined.

**Comment by sbc100** [comment]
Ah, that makes more sense.  Perhaps a better title for this issue might be `setErrNo not working with MINIMAL_RUNTIME`.

I'm actually surprised this isn't already working since i would imagine its used in quite a few places.

@juj?
