### ISSUE TITLE
llvm crash when compiling libopus

### ISSUE THREAD

**Issue by whohoho** [emscripten-core/emscripten#10894]
Here is the crash reproducing files:

[pitch-0745d6.c.txt](https://github.com/emscripten-core/emscripten/files/4467501/pitch-0745d6.c.txt)
[pitch-0745d6.sh.txt](https://github.com/emscripten-core/emscripten/files/4467504/pitch-0745d6.sh.txt)

**Comment by kripken** [comment]
What version was this on, and what is the full error that you see?

Trying to run it locally on latest master, something looks wrong, I get
```
error: unknown argument: '-masm-verbose'
error: unknown argument: '-fmessage-length'
error: unknown argument: '-fdiagnostics-show-option'
```
Removing those, it compiles without error.

**Comment by whohoho** [comment]
Not sure what version that was on, issue was only on latest, not on latest-fastcomp so i used that.

Now i updated, and i don't seem to have the problem anymore.
