### ISSUE TITLE
emconfigure blocks drand48 detection

### ISSUE THREAD

**Issue by aduh95** [emscripten-core/emscripten#10896]
Trying to build [graphviz](http://graphviz.org) using Emscripten, I encountered the following error:

```
error: Linking globals named 'drand48': symbol multiply defined!
```

I noticed that `emconfigure` "blocks" drand48 detection somehow:

```
$ ./configure | grep drand48
checking for drand48... yes
^C
$ emconfigure ./configure | grep drand48 
configure: ./configure
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.11
clang version 6.0.1  (emscripten 1.39.11 : 1.39.11)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
shared:INFO: (Emscripten: Running sanity checks)
shared:ERROR: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.C', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
checking for drand48... no
```

I assume this is what is causing my problem. Is there a reason for `emconfigure` to change the behaviour of `./configure` for this lib? Is there a known workaround?

**Comment by sbc100** [comment]
It looks like you still using the fastcomp backend which is nearing end of life.  Can you try with the new llvm backend?

**Comment by aduh95** [comment]
@sbc100 same result:

```
$ emconfigure ./configure | grep drand48
configure: ./configure
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.12
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project eaa55590945a130131a47a4d2b89e3bbdfced79e)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Users/duhamean/Documents/emsdk/upstream/bin
shared:INFO: (Emscripten: Running sanity checks)
em++: error: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.C', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
checking for drand48... no
```

**Comment by sbc100** [comment]
can you attach the `config.log` or any other configure output files?

**Comment by aduh95** [comment]
Here you are: [config.log](https://github.com/emscripten-core/emscripten/files/4471051/config.log)

FWIW I tried to manually tweak the config to force define `HAVE_DRAND48`, but the build still fails:

```
error: static declaration of 'strcasecmp' follows non-static declaration
```

**Comment by sbc100** [comment]
The error in config.log is `wasm-ld: error: unknown argument: -headerpad_max_install_names`.  Do you know where that linker flag is coming from? 

It looks like somehow `-Wl,-headerpad_max_install_names` is being added to you LDFLAGS maybe?

**Comment by aduh95** [comment]
You're correct, removing it from `configure.ac` file solves the issue. Thanks for your support!

**Comment by meoyawn** [comment]
@aduh95 did you by any chance manage to compile graphviz to WASM without this hack?

**Comment by aduh95** [comment]
> @aduh95 did you by any chance manage to compile graphviz to WASM without this hack?

Yes, on Linux the hack is not necessary. On macOS, it's still needed, so I added the hack to my `Makefile`: https://github.com/aduh95/viz.js/blob/master/Makefile
