### ISSUE TITLE
Jslibrary issue

### ISSUE THREAD

**Issue by wurc** [emscripten-core/emscripten#10926]
I saw below note on **https://emcc.zcopy.site/docs/porting/connecting_cpp_and_javascript/interacting-with-code/**
If a JavaScript library depends on a compiled C library (like most of libc), you must edit src/deps_info.json. Search for “deps_info” in tools/system_libs.py.

**so my question is:**
How does JavaScript library depend on C library, js can call C function directly？Please share more explaination

**Comment by sbc100** [comment]
The JS library processing happens after the native code is linked.     The `deps_info` tells that native linker what symbols it needs to preserve when it finds a certain JS symbol is used.

For example there is an entry for `wgpuDeviceCreateBuffer`:

```
"wgpuDeviceCreateBuffer": ["malloc", "free"]
```

This says "if wgpuDeviceCreateBuffer is referenced, then also assume that malloc and free are referenced", without this malloc and free might not get included in the native link.

At least that is my understanding, but looking through the `deps_info` I now see a lot of keys that are not JS functions, which means means either I'm wrong or that file needs an update.
