### ISSUE TITLE
compiler-rt headers

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#10929]
The `compiler-rt` has a number of useful headers, such as those for controlling sanitizers:

https://github.com/llvm/llvm-project/tree/master/compiler-rt/include/sanitizer

Is there anything that I can do to help get these into emscripten?

**Comment by sbc100** [comment]
Seems like we should add them yes.

Take a look at `system/lib/update_compiler_rt.py` and `system/lib/compiler-rt/readme.txt`

And then look at `emsdk_cflags` in `tools/shared.py` get them added to default include path.

**Comment by sbc100** [comment]
Any time you change those system library you want to make sure you rebuild the relevant libraries.
You can force a rebuild of everything using `./emcc --clear-cache`.   Or you can rebuild specific libraries using `./embuilder build --force <library_name>`.

Then you would want to run the asan tests, e.g.: `./test/runner.py wasm2.test_asan*`

If you just want to add new headers and not update compiler-rt in general you can sync llvm to the revision mentioned in system/lib/compiler-rt/readme.txt.  That is the safest options and likely to result in the least amount for work.    It might also be nice to add the headers separately to doing the upgrade either way.
