### ISSUE TITLE
Emscripten.cmake bug

### ISSUE THREAD

**Issue by MoAlyousef** [emscripten-core/emscripten#10920]
Hi

I'm trying to compile a C++ project into wasm, namely fltk. The fltk repo uses CMake, which works nicely crossplatform. However trying to run emcmake cmake fails since fltk has a file VERSION in the repo root, which for some reason conficts with ```#include <version>``` in several libcxx headers. This doesn't occur when building normally with cmake and clang (using libcxx). So I've narrowed it down to Emscripten.cmake, however my CMake-fu falls short when trying to debug cmake scripts!

I've recreated a minimal reproducible example, create a folder with the following structure:
```
|
|_main.cpp
|
|_CMakeLists.txt
|
|_VERSION
```
Contents of CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.0)
project(main)
add_executable(main main.cpp)
target_include_directories(main PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
```
Contents of main.cpp
```c++
#include <cstddef>
int main() {}
```
Contenst of VERSION
```
1.4.0
```

Now build using emcmake cmake and emmake make.
Error:
```
$ emcmake cmake . && emmake make
configure: cmake . -DCMAKE_TOOLCHAIN_FILE=/path/to/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/path/to/node/12.9.1_64bit/bin/node"
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/dev/fl/temp/bin
make: make
Scanning dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
In file included from /mnt/d/dev/fl/temp/main.cpp:1:
In file included from /mnt/d/dev/emsdk/upstream/emscripten/system/include/libcxx/cstddef:37:
/mnt/d/dev/fl/temp/version:1:1: error: expected unqualified-id
1.4.0
^
em++: error: 'emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=12 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -
/* rest of build command...nothing to see */
CMakeFiles/main.dir/main.cpp.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
```

Everything works fine if the VERSION file is removed or the target_include_directories(main PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}) is removed. However since it's not my project, I think using emscripten should be less intrusive.

**Comment by sbc100** [comment]
The `/mnt/d/dev/` path in your error message looks like you are using windows here somehow?  Maybe WSL?    

I don't seem like this is an emscripten-specific issue.  Are you sure the same things doesn't happen when building without emscripten?

I did a quick experiment locally.  If you create a file with the same name as something in standard include path in your project it will choose you local file and the build will break.

In my experiment I created a file called `type_traints` and then used `#include <vector>`.    It failed when I included by directory with `-I`.

Its a shame that libc++ chose to use such as common name, but I doesn't seem releated to cmake or to emscripten.  I repro'd it using my desktop clang:

```
$ clang -c main.cpp -I..
# works
$ touch ../type_traits
$ clang -c main.cpp -I..
# fail
```

**Comment by sbc100** [comment]
Sadly it looks like libcxx includes <version> all over the place:

```
libcxx/include/algorithm:#include <version>
libcxx/include/any:#include <version>
libcxx/include/array:#include <version>
libcxx/include/atomic:#include <version>
libcxx/include/bit:#include <version>
libcxx/include/chrono:#include <version>
libcxx/include/cmath:#include <version>
libcxx/include/complex:#include <version>
libcxx/include/concepts:#include <version>
libcxx/include/cstddef:#include <version>
libcxx/include/deque:#include <version>
libcxx/include/exception:#include <version>
libcxx/include/filesystem:#include <version>
libcxx/include/forward_list:#include <version>
libcxx/include/functional:#include <version>
libcxx/include/iomanip:#include <version>
libcxx/include/istream:#include <version>
libcxx/include/iterator:#include <version>
libcxx/include/limits:#include <version>
libcxx/include/list:#include <version>
libcxx/include/locale:#include <version>
libcxx/include/map:#include <version>
libcxx/include/memory:#include <version>
libcxx/include/mutex:#include <version>
libcxx/include/new:#include <version>
libcxx/include/numeric:#include <version>
libcxx/include/optional:#include <version>
libcxx/include/ostream:#include <version>
libcxx/include/regex:#include <version>
libcxx/include/scoped_allocator:#include <version>
libcxx/include/set:#include <version>
libcxx/include/shared_mutex:#include <version>
libcxx/include/string:#include <version>
libcxx/include/string_view:#include <version>
libcxx/include/tuple:#include <version>
libcxx/include/type_traits:#include <version>
libcxx/include/unordered_map:#include <version>
libcxx/include/unordered_set:#include <version>
libcxx/include/utility:#include <version>
libcxx/include/variant:#include <version>
libcxx/include/vector:#include <version>
```

So I think your options are:

1) use a case sensitive filesystem
2) Avoid putting the project root where VERSION lives on the include path.
3) Rename VERSION to something else

**Comment by MoAlyousef** [comment]
You're right. Although WSL is case-sensitive, apparently running the distro clang disregards this. I'll see if a similar issue was reported on the clang side. Thank you!
