### ISSUE TITLE
emscripten.Building.configure causes error

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#10939]
Hi!
I am working on porting the OpenCascade CAD engine from C++ to WASM + JS. I am having an issue with the latest emscripten version 1.39.12. The error does not occur with emscripten 1.39.11.

My build system is largely based on Ammo.JS. I am using the following code to configure using cmake:
```python
    stage('Configure via CMake')
    emscripten.Building.configure([
      emscripten.PYTHON,
      os.path.join(EMSCRIPTEN_ROOT, 'emcmake'),
      'cmake',
      '../occt/',
      '-DCMAKE_BUILD_TYPE=Debug',
      '-D3RDPARTY_FREETYPE_DIR=/home/OCCT_WA/freetype-2.10.0',
      '-D3RDPARTY_FREETYPE_INCLUDE_DIR_freetype2=/home/OCCT_WA/freetype-2.10.0/include/freetype',
      '-D3RDPARTY_FREETYPE_INCLUDE_DIR_ft2build=/home/OCCT_WA/freetype-2.10.0/include',
      '-D3RDPARTY_FREETYPE_LIBRARY_DIR=/home/OCCT_WA/freetype-2.10.0/build',
      '-DBUILD_LIBRARY_TYPE=Static',
      '-DCMAKE_CXX_FLAGS="-DIGNORE_NO_ATOMICS=1 -frtti"',
      '-D3RDPARTY_INCLUDE_DIRS=/home/OCCT_WA/regal/src/apitrace/thirdparty/khronos/\;/home/OCCT_WA/fontconfig',
      '-DUSE_GLES2=ON',
      '-DBUILD_MODULE_Draw=OFF'
    ])
```

This gives me the following error message
```
File "/home/project/emsdk/upstream/emscripten/emcmake", line 9
    if [ -z $PYTHON ]; then
            ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "make.py", line 237, in <module>
    build()
  File "make.py", line 193, in build
    '-DBUILD_MODULE_Draw=OFF'
  File "/home/project/emsdk/upstream/emscripten/tools/shared.py", line 1595, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "/home/project/emsdk/upstream/emscripten/tools/shared.py", line 199, in run_process
    result.check_returncode()
  File "/home/project/emsdk/upstream/emscripten/tools/shared.py", line 172, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['/usr/bin/python2', '/home/project/emsdk/upstream/emscripten/emcmake', 'cmake', '../occt/', '-DCMAKE_BUILD_TYPE=Debug', '-D3RDPARTY_FREETYPE_DIR=/OCCT_WA/freetype-2.10.0', '-D3RDPARTY_FREETYPE_INCLUDE_DIR_freetype2=/OCCT_WA/freetype-2.10.0/include/freetype', '-D3RDPARTY_FREETYPE_INCLUDE_DIR_ft2build=/OCCT_WA/freetype-2.10.0/include', '-D3RDPARTY_FREETYPE_LIBRARY_DIR=/OCCT_WA/freetype-2.10.0/build', '-DBUILD_LIBRARY_TYPE=Static', '-DCMAKE_CXX_FLAGS="-DIGNORE_NO_ATOMICS=1 -frtti"', '-D3RDPARTY_INCLUDE_DIRS=/home/OCCT_WA/regal/src/apitrace/thirdparty/khronos/\\;/home/OCCT_WA/fontconfig', '-DUSE_GLES2=ON', '-DBUILD_MODULE_Draw=OFF']' returned non-zero exit status 1
```

I am pretty sure that the same problem would occurr in AmmoJS - although I didn't check that yet. I would greatly appreciate any help with this.

**Comment by sbc100** [comment]
This was caused by the the switch to using shell script to launch python: #10729 

We did expect some fallout from this, and luckily the solution is fairly simple:  You can either add the `.py` extension to `emcmake` or you can can drop the `emscripten.PYTHON` first argument and let the shell script find python.

If you take the latter choice you might also need to add ".bat" if you want the script to run on windows.

BTW, it looks like you are importing and using emscripten python code, which is not current assumed to be used outside emscripten itself (so will change and break you over time).  Can you point me to where this code lives so we/I can test a look at fixing it?

**Comment by donalffons** [comment]
Legend! :-) That was much easier than I thought.
Just removing the emscripten.PYTHON argument did the trick. Thanks a lot for your help.

The repository lives here: https://github.com/donalffons/opencascade.js

It downloads OpenCascade from their git repository, but currently depends on some other dependencies (freetype, regal, fontconfig) to be manually downloaded and copied to certain locations - automating this is on my to-do list.

Which python code is problematic, in your opinion?
Thanks again!

**Comment by donalffons** [comment]
(as a side note, I meanwhile also checked and verified that the issue is present in Ammo.JS. I would create a pull request there, but don't have a properly setup windows system to test it.)

**Comment by sbc100** [comment]
Thanks I'll open a bug on ammo js to stop doing this...
