### ISSUE TITLE
error: use of undeclared identifier 'bind_front'

### ISSUE THREAD

**Issue by louisabraham** [emscripten-core/emscripten#10933]
Tried with both -std=c++20 and -std=gnu++20.

https://en.cppreference.com/w/cpp/utility/functional/bind_front

The same code compiles with g++

**Comment by sbc100** [comment]
Looks like this is a library feature that is not yet supported by libc++: https://en.cppreference.com/w/cpp/compiler_support.

So maybe look for an upstream libc++ bug?  Once its added there we can update libc++ here in emscripten and it should work.

**Comment by louisabraham** [comment]
Ah my bad, didn't know about partial support. Closing this to unclutter.
