### ISSUE TITLE
uncaught C++ exceptions (std::stod() )

### ISSUE THREAD

**Issue by delleceste** [emscripten-core/emscripten#10936]
using std::stod to convert a string to double, if the string is not a number, the application crashes instead of entering the catch clause

```cpp
try {
                double dou = std::stod(da[name].toString().c_str());
        }
        catch(const std::invalid_argument& ) {
        }
        catch(const std::out_of_range &) {   
        }
```

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.47
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 6c7e775325067e33fa60611e619a8b987b6d0c35) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /archivi/devel/emsdk-1.38.47/fastcomp/fastcomp/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0

**Comment by kripken** [comment]
@delleceste - can you perhaps provide a full testcase? I realize it's probably not many more lines than what you provided already, but consider it from the developer's point of view - it's must faster to just copy-paste a full example than to start to figure out the right `#include`s and other boilerplate around the relevant code. Thanks!

**Comment by aheejin** [comment]
I tested with this program
```
#include <string>                                                                
#include <stdexcept>                                                             
                                                                                 
int main() {                                                                     
  try {                                                                          
    double dou = std::stod("hello");                                             
  } catch (const std::invalid_argument &) {                                      
  } catch (const std::out_of_range &) {                                          
  }                                                                              
  return 0;                                                                      
}
```

And compiled this with
```
emcc -s DISABLE_EXCEPTION_CATCHING=0 test.cpp
```

And I don't see any problem, meaning the exception is caught. You seem to be using fastcomp, so I tested with the exact version of fastcomp, fastcomp-clang, and emscripten you are using, and it still works fine.

Can you clarify with the program and the command line you used?
