### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.spawn'

### ISSUE THREAD

**Issue by jtenner** [emscripten-core/emscripten#10943]
Problem was experienced on Ubuntu WSL.

```
Traceback (most recent call last):
  File "/home/jtenner/emsdk/upstream/emscripten/emcc.py", line 42, in <module>
    import emscripten
  File "/home/jtenner/emsdk/upstream/emscripten/emscripten.py", line 25, in <module>
    from tools import shared
  File "/home/jtenner/emsdk/upstream/emscripten/tools/shared.py", line 8, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
```

The workaround is installing `python3-distutils`

**Comment by sbc100** [comment]
It interesting the debian/ubuntu decided to take this package and make it not part of the normal python3 installation.   On my ubuntu system I have so many code packages that all depend on `python3-distutils` that removing seems impossible.  But I guess if you have a really minimal install one might not have this package.

I wonder how they justify not shipping part of the python standard library.  I guess its kind of deprecated: https://docs.python.org/3.9/distutils/introduction.html

Anyway I guess that best thing is to stop depending on it.
