### ISSUE TITLE
emsdk 1.39 python PATH not found -- skipping EPIC pacthes here

### ISSUE THREAD

**Issue by violacambie** [emscripten-core/emscripten#10946]
I'm encountering this warning in the end of the HTML5Setup.sh: 
"**emsdk 1.39 python PATH not found -- skipping EPIC pacthes here**"

I have installed python 3.8.2.
But emsdk says: **set as active python-3.7.4-64bit**

Any idea?

**Comment by sbc100** [comment]
On windows emsdk installs a version of python for you, in case you don't have one and it will use that one by default.   The version of python that emsdk install is currently 3.7.4.  The version we used to install with older SDKs was 2.7.13.1. 

I don't know what `HTML5Setup.sh` is so perhaps some more context is needed. Sounds like that script might be hardcoding the path of the old version of python maybe?

**Comment by sbc100** [comment]
Ah, looks like script comes from UnrealEngine.  You might want to ask about this problem there.

**Comment by violacambie** [comment]
Yes correct. the script comes from UnrealEngine.
Many thanks I-ll try to ask them too!

**Comment by artur2024** [comment]
Anything known about this problem? I have the same problem with HTML5Setup.sh

**Comment by sbc100** [comment]
This sounds like an upstream bug in `HTML5Setup.sh` where they are assuming the path of python.  Please file a bug with UnrealEngine.

**Comment by jimmiil** [comment]
same problem with me...

**Comment by sbc100** [comment]
Did someone file a bug on the downstream `HTML5Setup.sh` yet?
