### ISSUE TITLE
How to locate the callee function in call_indirect? 

### ISSUE THREAD

**Issue by B-doublemint** [emscripten-core/emscripten#10947]
How to locate the callee function in call_indirect? 
For example:
(call_indirect (type $t9) $T0
       (local.tee $p0(i32.load offset=8(local.get $p0)))
       (i32.const 3108)
       (i32.load offset=12(i32.load(local.get $p0)))
)
In the table section, I didn't find the function which type is t9.

**Comment by sbc100** [comment]
The callee depends on the table slow that you pass to call_indirect and what is in that slot at runtime.

In general you can't know statically which function will be called. 

Its is also possible to write a program that contains call_indirect to a given signature without any function with that signature existing.

**Comment by B-doublemint** [comment]
Thank you sir.
