### ISSUE TITLE
Bug in page:Emscripten Tutorial 

### ISSUE THREAD

**Issue by Raffaello** [emscripten-core/emscripten#10955]
REPLACE THIS TEXT WITH BUG DESCRIPTION 
Unfortunately several browsers (including Chrome, Safari, and Internet Explorer) do not support file:// XHR requests, and can’t load extra files needed by the HTML (like a .wasm file, or packaged file data as mentioned lower down). For these browsers you’ll need to serve the files using a webserver. The easiest way to do this is to use the python SimpleHTTPServer (in the current directory do python -m SimpleHTTPServer 8080 and then open http://localhost:8080/hello.html).
URL: ../../docs/getting_started/Tutorial

----

at the present time the default python is `python3.7` roughly. and the command to run is:

```bash
python -m http.server 8080
```

It might be worth adding the default for the python 3 and a BC note for python2.7

**Comment by kripken** [comment]
Thanks @Raffaello , I opened https://github.com/emscripten-core/emscripten/pull/10963 now, please take a look.
