### ISSUE TITLE
How to import memory from JS?

### ISSUE THREAD

**Issue by GirkovArpa** [emscripten-core/emscripten#10957]
In `settings.js`:

```javascript
// STANDALONE_WASM indicates that we want to emit a wasm file that can run without
// JavaScript ... when this option is set we do not
// import the Memory
```

I'm using this flag but I want to import memory so I don't have to do it in the C++ I'm compiling.  But I can't find any way to do so.

**Comment by kripken** [comment]
Correct, there isn't an option for that. But you can disassemble the wasm into text, modify the memory to be impored, and write it back out (e.g. using wasm2wat/wat2wasm or wasm-dis/wasm-as).

**Comment by sbc100** [comment]
I don't understand the problem though.  How are you compiling your C++?  The wasm-ld linker normally takes care of exporting the memory for you so its not something you have to do yourself.

**Comment by GirkovArpa** [comment]
> emcc -Os -s STANDALONE_WASM -s INITIAL_MEMORY=1024mb -s TOTAL_MEMORY=1024mb -s TOTAL_STACK=512mb -s EXPORTED_FUNCTIONS="['_myFunction1,' '_myFunction2']" -Wl,--no-entry "filename.cpp" - o "filename.wasm"

I don't want to set memory with compilation flags.  I want to set the memory limits in JavaScript, like this:

```javascript
const b2p = function bytesToPages(bytes) { return Math.ceil(bytes / 64_000); }
new WebAssembly.Memory({ initial: b2p(1_000_000), maximum: b2p(10_000_000) });
```

This lets me debug my wasm memory errors without having to constantly recompile it with different flags.

At the moment I can see my ArrayBuffer (the memory shared between WASM and JS I believe) is enormous, but if I create a typed array in JS, pass the pointer (index of the first element in the typed array in the shared memory, I believe) to the wasm, the wasm gets a memory out of bounds error when trying to set the value of a certain index in that array even though the index is WELL within the limits of the ArrayBuffer.

And debugging this is a PAIN if I can't set the memory from JavaScript.

**Comment by sbc100** [comment]
Ok, I see, that makes sense.  If you are writing you own JS hardness to load the wasm file, than I think it might work to simply pass that `-Wl,--import-memory` at link time.

**Comment by sbc100** [comment]
You will need 1.39.12 or above to allow arbitrary link flags such as this to be passed though.

**Comment by GirkovArpa** [comment]
So it's that easy!  Thanks!

**Comment by npip99** [comment]
@sbc100 I followed those instructions, but when passing in `-Wl,--import-memory`, I get a 4.24 MB wasm file. Without --import-memory, it's only a 49 kb wasm file. Something seems wrong, is it supposed to increase the filesize 1000-fold?

**Comment by sbc100** [comment]
Yes please open a bug report, although passing `-Wl,--import-memory` is not really configuration we support officially.

I imagine the size difference is down the `.bss` data (zero initialized data)  but we could need to take a look at the two binaries to know for sure.   What does `wasm-objdump` tell do you?  Do you have a lot of uninitialized global data in your program?   Lets discuss on the new bug..
