### ISSUE TITLE
Can't install latest using './emsdk install latest'

### ISSUE THREAD

**Issue by ShehabAhmedSayem** [emscripten-core/emscripten#10958]
Hello there. I'm using linux and following the instruction given on the site. But I can't install the latest using './emsdk install latest' command. Giving the following error:
`Installing SDK 'sdk-releases-upstream-7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f-64bit'..
Skipped installing node-12.9.1-64bit, already installed.
Installing tool 'releases-upstream-7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f/wasm-binaries.tbz2': <urlopen error [Errno 104] Connection reset by peer>
Installation failed!`
I have node-12.9.1 installed. python version 3.7.5. Searched and found that it was due to some network issue. but I had my connection alright. Is the files in storage.googleapis missing or storage.googleapis is down?

**Comment by ShehabAhmedSayem** [comment]
After the first time if I run the command again Errno 0 is given instead of 104.
`Installing SDK 'sdk-releases-upstream-7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f-64bit'..
Skipped installing node-12.9.1-64bit, already installed.
Installing tool 'releases-upstream-7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f/wasm-binaries.tbz2': <urlopen error [Errno 0] Error>
Installation failed!
`

**Comment by sbc100** [comment]
Seems like a network connection issue.  Can you download that file to your machine using other methods?

Does `wget` or `curl` work with `https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f/wasm-binaries.tbz2`

**Comment by ShehabAhmedSayem** [comment]
Thanks @sbc100 for replying. I have tried with wget and curl both but couldn't connect to storage.googleapis.com. 
after wget this is showing in the terminal :
`--2020-04-21 15:40:52--  https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7b3cd38017f7c582cfa3ac24a9f12aa6a8dca51f/wasm-binaries.tbz2
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.31.208, 2404:6800:4007:809::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.31.208|:443... connected.
Unable to establish SSL connection.
` 
after curl this is showing in the terminal:
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 
`
I could download with google chrome using a vpn by copy pasting the link, but almost 20-25 times I need to resume the download of chrome download manager as the network keep failing. 
Now I have the files and I copy pasted the wasm-binaries.tbz2 inside the emsdk folder and tried to run install latest command but couldn't get it. Another information is that I have manually downloaded node 12.9.1 from official nodejs page link for linux as emsdk couldn't install them and keep that in emsdk folder. So now when I run isntall latest it finds node perfectly. but don't know where to keep the wasm-binaries.tbz2 folder.
Thanks in advance.

**Comment by sbc100** [comment]
If you can't reliably connect to and download from storage.googleapis.com:443, then you have bigger network issue, which I don't thing are released to emsdk.

There is no easy way that I know of to point emsdk that binaries you downloaded.   You could try extracting that archive, and renaming the directory to "upstream" within the emsdk folder and then try running `emsdk activate latest` to create the emscripten config, but I fear that may try to download the file over again.

**Comment by ShehabAhmedSayem** [comment]
Yeah, you are right. renaming the folder upstream doesn't work. But while trying to run the install latest command from time to time suddenly for one time the download started and didn't give me error. And now I'm able to work with it. After that time I again tried but was getting the previous error. Don't know why can't I connect with storage.googleapis.com though I can easily download from other sites using curl or wget. By the way, closing the issue as this is not related to emsdk. And again thank you very much for your time @sbc100 .

**Comment by shaunrd0** [comment]
Had this issue as well at a few different points during installation, running Kubuntu 20.04 in a virtualbox VM. I was able to manually wget the files returning 104's with no problems, though. After reading the previous comment, I just kept rerunning the command to install and eventually each error resolved itself. Errors I encountered are below 

First 104
```
Installing SDK 'sdk-releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'..
Installing tool 'node-12.18.1-64bit'..
Downloading: /home/kapper/mame-ems/emsdk/zips/node-v12.18.1-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-linux-x64.tar.xz, 14695604 Bytes
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-linux-x64.tar.xz': [Errno 104] Connection reset by peer
Installation failed!
```

So at this point, I try `wget` to grab the errored URL above
```
--2020-07-01 11:45:47--  https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-linux-x64.tar.xz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.4.208, 172.217.6.112, 172.217.1.48, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.4.208|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14695604 (14M) [application/x-tar]
Saving to: ‘node-v12.18.1-linux-x64.tar.xz’

node-v12.18.1-linux-x64.tar.xz      4%[=>                                                         ] 690.86K  3.53MB/s    in 0.2s    

2020-07-01 11:45:48 (3.53 MB/s) - Read error at byte 707444/14695604 (Connection reset by peer). Retrying.

--2020-07-01 11:45:49--  (try: 2)  https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-linux-x64.tar.xz
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.4.208|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 14695604 (14M), 13988160 (13M) remaining [application/x-tar]
Saving to: ‘node-v12.18.1-linux-x64.tar.xz’

node-v12.18.1-linux-x64.tar.xz    100%[++========================================================>]  14.01M  10.2MB/s    in 1.3s    

2020-07-01 11:45:50 (10.2 MB/s) - ‘node-v12.18.1-linux-x64.tar.xz’ saved [14695604/14695604]
```


Ran it again, and it completes below..
```
Installing SDK 'sdk-releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'..
Installing tool 'node-12.18.1-64bit'..
Downloading: /home/kapper/mame-ems/emsdk/zips/node-v12.18.1-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-linux-x64.tar.xz, 14695604 Bytes
Unpacking '/home/kapper/mame-ems/emsdk/zips/node-v12.18.1-linux-x64.tar.xz' to '/home/kapper/mame-ems/emsdk/node/12.18.1_64bit'
Done installing tool 'node-12.18.1-64bit'.
Installing tool 'releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'..
Downloading: /home/kapper/mame-ems/emsdk/zips/1914a1543f08cd8e41f44c2bb05f7a90d1920275-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/1914a1543f08cd8e41f44c2bb05f7a90d1920275/wasm-binaries.tbz2, 121734269 Bytes
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/1914a1543f08cd8e41f44c2bb05f7a90d1920275/wasm-binaries.tbz2': [Errno 104] Connection reset by peer
Installation failed!
```

Re-ran, Errno 104, ran again, and it completes below but npm has an integrity error?..
```
Installing SDK 'sdk-releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'..
Skipped installing node-12.18.1-64bit, already installed.
Installing tool 'releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'..
Downloading: /home/kapper/mame-ems/emsdk/zips/1914a1543f08cd8e41f44c2bb05f7a90d1920275-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/1914a1543f08cd8e41f44c2bb05f7a90d1920275/wasm-binaries.tbz2, 121734269 Bytes
Unpacking '/home/kapper/mame-ems/emsdk/zips/1914a1543f08cd8e41f44c2bb05f7a90d1920275-wasm-binaries.tbz2' to '/home/kapper/mame-ems/emsdk/upstream'
Done installing tool 'releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'.
Running post-install step: npm ci ...
Error running ['/home/kapper/mame-ems/emsdk/node/12.18.1_64bit/bin/npm', 'ci', '--production']:
npm WARN tarball tarball data for google-closure-compiler@20200224.0.0 (sha512-V81dRYygdHbZtOtU16VX26xAdJBB1UZyfSg3OTzdNl3l/xEIx1D/L7TYUqjeTXsxcy+JruJ/UfUlIJAOaMRTog==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for google-closure-compiler-js@20200224.0.0 (sha512-70VKN0kbnTRtu2dqxDjWZQGfEQIHj7b7oUUCsYPO5oEXCDfgxNc13oYUJXvrTONLRWlHCNl/I8FNrVOwZ3gY/g==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for google-closure-compiler-java@20200224.0.0 (sha512-palFcDoScauZjWIsGDzMK6h+IctcRb55I3wJX8Ko/DTSz72xwadRdKm0lGt8OoYL7SKEO+IjgD7s8XrAGpLnlQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for google-closure-compiler-windows@20200224.0.0 (sha512-l6w2D8r9+GC9CQTAYEMAuNI996Zb6YV5qG7+FR0gCoL6h6S3Mc7mi87bafgwaicsVcmmHE/9kCBuW4ZyTMs5Fg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for google-closure-compiler-osx@20200224.0.0 (sha512-WXVNW9nPUqjvCe38mUIlBGEPVPCTKLtdaXC+q+kQdonkJFHNrpdyYWa746Y8cNP/byQyDNpPsqcKseZTLh17sQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for google-closure-compiler-js@20200224.0.0 (sha512-70VKN0kbnTRtu2dqxDjWZQGfEQIHj7b7oUUCsYPO5oEXCDfgxNc13oYUJXvrTONLRWlHCNl/I8FNrVOwZ3gY/g==) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting google-closure-compiler-js@20200224.0.0:
npm ERR! Verification failed while extracting google-closure-compiler-js@20200224.0.0:
npm ERR! sha512-70VKN0kbnTRtu2dqxDjWZQGfEQIHj7b7oUUCsYPO5oEXCDfgxNc13oYUJXvrTONLRWlHCNl/I8FNrVOwZ3gY/g== integrity checksum failed when using sha512: wanted sha512-70VKN0kbnTRtu2dqxDjWZQGfEQIHj7b7oUUCsYPO5oEXCDfgxNc13oYUJXvrTONLRWlHCNl/I8FNrVOwZ3gY/g== but got sha512-kkaXeOSgbt9ACVn0Gk1PPZZFwuiC2jv31XjJqVoxCZ5MV1CIUzak2DxgSKP7kkKm2aUQOa93MTYaMGpJX7zisA==. (8864 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kapper/.npm/_logs/2020-07-01T15_47_42_550Z-debug.log
```

Ran one last time and it completes
```
Installing SDK 'sdk-releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'..
Skipped installing node-12.18.1-64bit, already installed.
Skipped installing releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit, already installed.
Running post-install step: npm ci ...
Done running: npm ci
Done installing SDK 'sdk-releases-upstream-1914a1543f08cd8e41f44c2bb05f7a90d1920275-64bit'.
```

Just posting in case someone runs into these, everything seems to be working now for me. Try, try again :)
