### ISSUE TITLE
I have a project using boost library, how to use wasm to compile

### ISSUE THREAD

**Issue by xmq1996** [emscripten-core/emscripten#10966]
I did the following:
1. Compile the boost source code through the steps explained by Scott Butler, the specific process is as follows: https://stackoverflow.com/questions/15724357/using-boost-with-emscripten
2. Then use the following command to compile my project:
`emcc test.cpp -I "/home/haseepc/BOOST/pre/include" -L "/home/haseepc/BOOST/pre/lib" -lboost_atomic -lboost_chrono -lboost_container -lboost_context -lboost_coroutine -lboost_date_time -lboost_exception -lboost_filesystem -lboost_graph -lboost_locale -lboost_log -lboost_log_setup -lboost_math_c99 -lboost_math_c99f -lboost_math_c99l -lboost_math_tr1 -lboost_math_tr1f -lboost_math_tr1l -lboost_prg_exec_monitor -lboost_program_options -lboost_random -lboost_regex -lboost_serialization -lboost_system -lboost_test_exec_monitor -lboost_thread -lboost_timer -lboost_type_erasure -lboost_unit_test_framework -lboost_wave -lboost_wserialization -s WASM=1 -o hello.html`
3.The error is reported as follows:wasm-ld: error: unknown file type: error_code.o
shared:ERROR: '/home/haseepc/wasm/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_JXVqL8/hello.wasm --lto-O0 /tmp/emscripten_temp_JXVqL8/test_0.o -L/home/haseepc/BOOST/pre/lib -L/home/haseepc/wasm/emsdk/upstream/emscripten/system/local/lib /home/haseepc/BOOST/pre/lib/libboost_atomic.a /home/haseepc/BOOST/pre/lib/libboost_chrono.a /home/haseepc/BOOST/pre/lib/libboost_container.a /home/haseepc/BOOST/pre/lib/libboost_context.a /home/haseepc/BOOST/pre/lib/libboost_coroutine.a /home/haseepc/BOOST/pre/lib/libboost_date_time.a /home/haseepc/BOOST/pre/lib/libboost_exception.a /home/haseepc/BOOST/pre/lib/libboost_filesystem.a /home/haseepc/BOOST/pre/lib/libboost_graph.a /home/haseepc/BOOST/pre/lib/libboost_locale.a /home/haseepc/BOOST/pre/lib/libboost_log.a /home/haseepc/BOOST/pre/lib/libboost_log_setup.a /home/haseepc/BOOST/pre/lib/libboost_math_c99.a /home/haseepc/BOOST/pre/lib/libboost_math_c99f.a /home/haseepc/BOOST/pre/lib/libboost_math_c99l.a /home/haseepc/BOOST/pre/lib/libboost_math_tr1.a /home/haseepc/BOOST/pre/lib/libboost_math_tr1f.a /home/haseepc/BOOST/pre/lib/libboost_math_tr1l.a /home/haseepc/BOOST/pre/lib/libboost_prg_exec_monitor.a /home/haseepc/BOOST/pre/lib/libboost_program_options.a /home/haseepc/BOOST/pre/lib/libboost_random.a /home/haseepc/BOOST/pre/lib/libboost_regex.a /home/haseepc/BOOST/pre/lib/libboost_serialization.a /home/haseepc/BOOST/pre/lib/libboost_system.a /home/haseepc/BOOST/pre/lib/libboost_test_exec_monitor.a /home/haseepc/BOOST/pre/lib/libboost_thread.a /home/haseepc/BOOST/pre/lib/libboost_timer.a /home/haseepc/BOOST/pre/lib/libboost_type_erasure.a /home/haseepc/BOOST/pre/lib/libboost_unit_test_framework.a /home/haseepc/BOOST/pre/lib/libboost_wave.a /home/haseepc/BOOST/pre/lib/libboost_wserialization.a /home/haseepc/.emscripten_cache/wasm/libc.a /home/haseepc/.emscripten_cache/wasm/libcompiler_rt.a /home/haseepc/.emscripten_cache/wasm/libc-wasm.a /home/haseepc/.emscripten_cache/wasm/libc++-noexcept.a /home/haseepc/.emscripten_cache/wasm/libc++abi-noexcept.a /home/haseepc/.emscripten_cache/wasm/libdlmalloc.a /home/haseepc/.emscripten_cache/wasm/libpthread_stub.a /home/haseepc/.emscripten_cache/wasm/libc_rt_wasm.a /home/haseepc/.emscripten_cache/wasm/libsockets.a --allow-undefined --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export __errno_location --export fflush --export setThrew --export _ZSt18uncaught_exceptionv --export __cxa_find_matching_catch --export memset --export __cxa_is_pointer_type --export __cxa_can_catch --export memalign --export _get_environ --export _get_tzname --export _get_daylight --export _get_timezone --export htonl --export htons --export ntohs --export emscripten_main_thread_process_queued_calls -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (1)

**Comment by xmq1996** [comment]
test.cpp is as follows:`#include <boost/thread.hpp>
#include <iostream>
using namespace std;
#ifdef __cplusplus
extern "C"
{
#endif
void Func(int nCount)

{

    for (int i = 0; i < nCount; i++)

    {

        cout <<  __FUNCTION__ << i << endl;

    }

}
int main() {
   boost::thread th(Func, 100);

    //等待线程结束

    th.join();
    return 0;
}
#ifdef __cplusplus
}
#endif`

**Comment by aheejin** [comment]
Not sure what's going on here, but the error message sounds like error_code.o is not a valid wasm object file or a bitcode file wasm-ld expects. What does
```
file error_code.o
```
print?

**Comment by xmq1996** [comment]
Sorry, aheejin, to come back to you so late.
The output is as follows:
error_code.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped

**Comment by aheejin** [comment]
Yes, that means error_code.o is not a wasm object file but a x86 object file. I have no idea how you generated that file, so if you give the commands you used to generate that file, it will be helpful to figure out the reason.

**Comment by besttangent** [comment]
> Yes, that means error_code.o is not a wasm object file but a x86 object file. I have no idea how you generated that file, so if you give the commands you used to generate that file, it will be helpful to figure out the reason.
Can I ask a question, please? I think your meaning is that If I were to use the llvm backend, I can not use .a file consisted of x64 object file? And how can I get an archieve file(.a) consisted of wasm object with cmake? I know I can use emcmake to do it but any other method? Or in other words, if I want to use static libs, how should I generate the libs?

**Comment by aheejin** [comment]
I'm not exactly sure what your question is. You can use .a file with emscripten but that should consist of wasm object files, not x64 object files. It looks [`emar`](https://github.com/emscripten-core/emscripten/blob/master/emar) can archive object files into an archive.

**Comment by besttangent** [comment]
I am very sorry to reply you so lately. I had solved this problem and thank
you again.

Heejin Ahn <notifications@github.com> 于2020年7月9日周四 上午11:10写道：

**Comment by alibagher** [comment]
Can you please let us know how you solved the issue?
