### ISSUE TITLE
Standalone assembly files (.s/.S)

### ISSUE THREAD

**Issue by Maratyszcza** [emscripten-core/emscripten#10972]
Emscripten wrapper doesn't accept standalone assembly files (.s/.S) as input even though Clang supports it. I get the following error:
```shared:ERROR: probe.s: Input file has an unknown suffix, don't know what to do with it!```

**Comment by kripken** [comment]
I think I remember @tlively experimenting with this (or maybe it was just with bare clang?)

**Comment by sbc100** [comment]
Yes, clang and llvm support this, we just need to allow it I think.
