### ISSUE TITLE
crash when compiling simple side module with debug symbols

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#10983]
Compiling a simple dynamic library with debug symbols currently fails on 1.39.13

side.cpp:
```c++
#include <emscripten.h>
EMSCRIPTEN_KEEPALIVE void side_module_func() {}
```

em++ side.cpp -s SIDE_MODULE=2 -s WASM=1 -Os -g --profiling -o side.wasm
fails with an assertion:
```
wasm-ld: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/lld/wasm/Symbols.cpp:287: uint32_t lld::wasm::GlobalSymbol::getGlobalIndex() const: Assertion 'globalIndex != INVALID_INDEX' failed.
```
Without debug symbols the compilation works.

**Comment by sbc100** [comment]
As mentioned in #14025 and I think we have fix in the form of https://reviews.llvm.org/D101399.  However I'm still working on writing a test...

**Comment by gl84** [comment]
Thank you.
