### ISSUE TITLE
Stdio streams are not flushed in standalone mode

### ISSUE THREAD

**Issue by mbovel** [emscripten-core/emscripten#10990]
To reproduce with the last version (`1.39.13`):

```
$ upstream/emscripten/emcc hello.c -s EXIT_RUNTIME=1 -o hello.wasm
$ wasmer hello.wasm
```

With `hello.c` containing:

```c
#include <stdio.h>
int main() { printf("Hello World"); return 0; }
```

---

In JS, this is handled by `flush_NO_FILESYSTEM`, which is in the `__ATEXIT__` array:

```js
function flush_NO_FILESYSTEM() {
    // flush anything remaining in the buffers during shutdown
    if (typeof _fflush !== 'undefined') _fflush(0);
    var buffers = SYSCALLS.buffers;
    if (buffers[1].length) SYSCALLS.printChar(1, 10);
    if (buffers[2].length) SYSCALLS.printChar(2, 10);
}
```

Would it be possible to generate something similar at the end of `_start` when `EXIT_RUNTIME` and `STANDALONE_WASM` are set?

**Comment by kripken** [comment]
Good question!

What happens in other vms like wasmtime and wavm? And how about native applications?

I think we added that flush in JS because `console.log` etc. can only write a full line. So we don't have any way to tell the OS "print a partial line here". But a wasm VM should be able to?

**Comment by sbc100** [comment]
It should certainly be possible to make this work, especially with the recent change to WASI which defines reactors:  https://github.com/WebAssembly/WASI/blob/master/design/application-abi.md

**Comment by sunfishcode** [comment]
Another option for people targeting non-Web VMs is to use [wasi-sdk](https://github.com/WebAssembly/wasi-sdk), which supports flushing stdio streams on exit.

**Comment by mbovel** [comment]
> What happens in other vms like wasmtime and wavm?

I tried with [GraalWasm](https://github.com/oracle/graal/tree/master/wasm), and nothing is printed their neither.

I'd expect it to happen in any interpreter as `fd_write` is not even called.

> And how about native applications?

The stream is correctly flushed in a native application: [*the C runtime will register `atexit()` handlers to flush standard buffers when `exit()` is called*](https://stackoverflow.com/questions/17230411/printf-flush-at-program-exit).

**Comment by kripken** [comment]
> I'd expect it to be the case in any interpreter as fd_write is not even called.

Oh right, thanks, this is still buffered at the libc level...

Ok, this is definitely a bug then, that we should fix. I opened https://github.com/emscripten-core/emscripten/pull/10995 now to get `atexit()` working which is necessary for that.

**Comment by kripken** [comment]
@mbovel ok, this should be fixed by that PR, and I also verified that the testcase here works as expected.

One remaining question perhaps is whether we should support `EXIT_RUNTIME=0` in standalone mode. Right now, we always flush the streams during exit, regardless of that flag. I suspect that's ok because there isn't much code size cost, and it's the more natural thing in a non-Web environment. But curious what people think.

**Comment by vadimkantorov** [comment]
@kripken How can I manually flush stderr?

For stdout, I manually do `putchar('\n'.charCodeAt(0))` and then fflush.

Can I do `Module.SYSCALLS.printChar(2, 10);`?

Or should I import `fputc` and call it as `fputc(2, 10)`? Should 2 work as `FILE*`? Or should I call it as `fputc(fopen('/dev/stderr'), 10)`?

**Comment by vadimkantorov** [comment]
For me exits are happening with exit() function, so maybe I could set an atexit handler in C

**Comment by kripken** [comment]
Another option might be to call from JS, if you export fflush, and then do `Module._fflush(2);` (0 is stdin, 1 is stdout, 2 is stderr)

**Comment by vadimkantorov** [comment]
fflush works well from javascript, but without a prior putchar, it doesn't work. something is buffered hard.

so need to do ftputc `\n` to stdout and stderr and only then flush...

**Comment by sbc100** [comment]
fflush() only flush the stdio streams to the kernel (in this case to JS).   It does not, flush the buffers that exist on the JS side as we are discussing over in #14457.

Lets continue that discussion in #14457.
