### ISSUE TITLE
Fail to compile the code of google protobuf with em++

### ISSUE THREAD

**Issue by tobegit3hub** [emscripten-core/emscripten#11002]
Now we try to use `em++` to compile C++ source code to wasm files. The project relies on google protobuf and can be built with `clang++` or `g++`. When we switch to `em++` in cmake and it throws compile error like this.

```
/Users/tobe/code/thirdparty/include/google/protobuf/stubs/once.h:125:30: error: cannot initialize a parameter of type 'const volatile google::protobuf::internal::Atomic32 *' (aka 'const volatile int *') with an lvalue of type 'google::protobuf::ProtobufOnceType *' (aka 'long *')
  if (internal::Acquire_Load(once) != ONCE_STATE_DONE) {
                             ^~~~
/Users/tobe/code/thirdparty/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h:97:55: note: passing argument to parameter 'ptr' here
inline Atomic32 Acquire_Load(volatile const Atomic32* ptr) {
                                                      ^
In file included from /Users/tobe/code/build/src/proto/type.pb.cc:5:
In file included from /Users/tobe/code/build/src/proto/type.pb.h:22:
In file included from /Users/tobe/code/thirdparty/include/google/protobuf/generated_message_util.h:44:
/Users/tobe/code/thirdparty/include/google/protobuf/stubs/once.h:134:30: error: cannot initialize a parameter of type 'const volatile google::protobuf::internal::Atomic32 *' (aka 'const volatile int *') with an lvalue of type 'google::protobuf::ProtobufOnceType *' (aka 'long *')
  if (internal::Acquire_Load(once) != ONCE_STATE_DONE) {
                             ^~~~
/Users/tobe/code/thirdparty/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h:97:55: note: passing argument to parameter 'ptr' here
inline Atomic32 Acquire_Load(volatile const Atomic32* ptr) {
                                                      ^
2 errors generated.
em++: error: '/Users/tobe/code/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/lib/libunwind/include -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/include -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/Users/tobe/.emscripten_cache/wasm/include -I/Users/tobe/code/thirdparty/include -I/Users/tobe/code/src -I/Users/tobe/code/build/src -std=c++14 -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -fPIC -g -Wall -std=c++14 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -c -DEMSCRIPTEN -fignore-exceptions /Users/tobe/code/build/src/proto/type.pb.cc -Xclang -isystem/Users/tobe/code/emsdk/upstream/emscripten/system/include/SDL -c -o CMakeFiles/fesql_proto.dir/type.pb.cc.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
```

We have set `-std=c++14` and the only different to cause the error is relacing `g++` to `em++`.

**Comment by aheejin** [comment]
I don't have much clue, but this is a clang error, so this is not something emscripten would change the behavior on. In your ~/.emscripten file, there should be a variable called `LLVM_ROOT`. What is the version of clang in that path? You can check it using `[YOUR_LLVM_ROOT]/clang --version`. What is the version of the vanilla clang, which you said worked? Is it possible that the two versions are very different?

**Comment by tobegit3hub** [comment]
Thanks @aheejin . We found that the version of `clang` from `emscripten`(version 11.0.0) is different from the one of system(version 11.0.3).

I will try to use the system one to compile and test again.

**Comment by tobegit3hub** [comment]
We will try re-compiling llvm with `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly` to test with the local llvm system.

**Comment by aheejin** [comment]
I doubt that small different (11.0.0 vs. 11.0.3) would cause some rule changes like that. Also I wonder what version 11.0.3 is? 10.0.0 is the latest release, and 11.0.0 is what the current trunk prints. How can your system clang print 11.0.3? Where did you compile or install it?

Also, from 9.0.0 or something, WebAssembly became the default target, so you don't need `-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD` to build wasm.

`-fignore-exceptions` was added in https://github.com/llvm/llvm-project/commit/55e2678fcd4d7eca3f9a602a919da499c1103041, which was in Feb. I'm still not sure which version of clang you are using, but if you are using the current trunk, it should be in there. If you use one or previous releases, it can be it's not in there, but it shouldn't print something like version 11.0.3 then. (Even if you are using the current trunk, I don't know what 11.0.3 is.)

**Comment by tobegit3hub** [comment]
Sorry for the typo. It is my fault and the versions are `10.0.0` vs `10.0.3`. 

`10.0.3` was installed in system by `brew install`.

**Comment by tobegit3hub** [comment]
Could be the problem of clang and we will check it out later and thanks for the support.

**Comment by arielm** [comment]
FWIW, I recently tried to build an old version of protobuf (circa 2015) for emscripten (ASM.js) and I received the same error.

The solution was to apply a patch to `protobuf/src/google/protobuf/stubs/atomicops.h`:
```
 // Use AtomicWord for a machine-sized pointer.  It will use the Atomic32 or
 // Atomic64 routines below, depending on your architecture.
+#if !defined(GOOGLE_PROTOBUF_ARCH_64_BIT)
+typedef Atomic32 AtomicWord;
+#else
 typedef intptr_t AtomicWord;
+#endif
```
Inspired by [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1192556#c13)
