### ISSUE TITLE
Syntax errors in em++ when Python is installed in a directory with spaces

### ISSUE THREAD

**Issue by yeputons** [emscripten-core/emscripten#11005]
Environment: Windows 7, using msys2 Bash, `which python` yields `/c/Program Files (x86)/Python38-32/python`. If I run `em++` in cmd, everything works, but it fails when ran from msys bash:

```
$ em++ a.cpp
/f/Soft/emsdk/upstream/emscripten/em++: line 16: [: too many arguments
/f/Soft/emsdk/upstream/emscripten/em++: line 20: [: too many arguments
/f/Soft/emsdk/upstream/emscripten/em++: line 24: [: too many arguments
/f/Soft/emsdk/upstream/emscripten/em++: line 29: /c/Program: No such file or directory
```

I suspect it broke in #10729 (released in 1.39.12): `tools/run_python.sh` lacks proper quoting of the `$PYTHON` variable.

**Comment by sbc100** [comment]
Yup, looks like we don't correctly support spaces in the python executable path.    Thanks for reporting.   If you have patch it would be welcome.
