### ISSUE TITLE
MEMFS.stream_ops.write broken on legacy browsers

### ISSUE THREAD

**Issue by JustAMan** [emscripten-core/emscripten#11008]
Hi!

I'm using emscripten to compile a C library to render subtitles on the fly, and during debugging why it won't work on older WebOS models I found that recent PR has introduced an incompatibility with legacy browsers. I'm speaking of https://github.com/emscripten-core/emscripten/pull/10347 - in older browsers I found that `Uint8Array` doesn't have `.slice()` member (at least in worker context, in some not-so-ancient it has `.slice()` in normal context but not within web worker).

**Comment by kripken** [comment]
Thanks @JustAMan !

I opened #11011 now to add automatic polyfilling there, can you please test it?
