### ISSUE TITLE
WebGPU header outdated

### ISSUE THREAD

**Issue by Tandaradei** [emscripten-core/emscripten#11007]
Comparing to the [specification](https://gpuweb.github.io/gpuweb/) and the [header at webgpu-native](https://github.com/webgpu-native/webgpu-headers/blob/master/webgpu.h), it seem's like webgpu.h is outdated in emscripten (last update was in january).
Apparently Chrome Canary and Firefox Nightly (the ones I've tested) are using the updated specification, so the emscripten generated code won't work there.
Are there any plans on updating webgpu.h (and probably also some emscripten related files)?
I'm not really experienced with emscripten beside using it, but if it's just renaming the properties in the header file and (I guess) in library_webgpu.js, I would be glad to help out.

@kainino0x just tagging you, because you did the last commit on webgpu.h

**Comment by kainino0x** [comment]
You're correct, we haven't updated Emscripten's implementation yet to match the latest spec. We are tracking this TODO, but a contribution would be welcome! FYI, if you need header match between Emscripten and Dawn, you can try using an older revision of Dawn.

**Comment by SachinVarghese** [comment]
Hi, I was also testing the webgpu on Firefox nightly so I am happy to help as well. Just wondering if there an easier way to refer to the `webgpu.h` file created with dawn to use in this repo? Also, are there any existing examples in this repo that use webgpu header files?

**Comment by kainino0x** [comment]
@SachinVarghese I'm not exactly sure of your question about `webgpu.h`. When building against Emscripten you don't need Dawn at all (except optionally for `webgpu_cpp`); `webgpu.h` is included in Emscripten, and can be included directly like in [this test](https://github.com/emscripten-core/emscripten/blob/028f73723214eff982aac2c919ce7b5ed826452f/tests/webgpu_dummy.cpp).
