### ISSUE TITLE
g++ compile failed  reason: typedef redefinition with different types ('struct _IO_FILE' vs 'struct __sFILE') typedef struct _IO_FILE FILE;

### ISSUE THREAD

**Issue by zhusjfaker** [emscripten-core/emscripten#11018]
In file included from /Users/zhushijie/Desktop/github/cplus-learn/count/index.cpp:3:
In file included from /Users/zhushijie/emsdk/emscripten/incoming/system/include/emscripten.h:1:
In file included from /Users/zhushijie/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:31:
In file included from /Users/zhushijie/emsdk/emscripten/incoming/system/include/SDL/SDL.h:75:
/Users/zhushijie/emsdk/emscripten/incoming/system/include/SDL/SDL_atomic.h:289:15: warning: 'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in macOS 10.12 - Use
      std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCASPtr(a, value, v));
              ^
/Users/zhushijie/emsdk/emscripten/incoming/system/include/SDL/SDL_atomic.h:167:45: note: expanded from macro 'SDL_AtomicCASPtr'
#define SDL_AtomicCASPtr(a, oldval, newval) OSAtomicCompareAndSwap64Barrier((int64_t)(oldval), (int64_t)(newval), (int64_t*)(a))
                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:645:9: note: 'OSAtomicCompareAndSwap64Barrier' has been
      explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t __oldValue, int64_t __newValue,
        ^
In file included from /Users/zhushijie/Desktop/github/cplus-learn/count/index.cpp:3:
In file included from /Users/zhushijie/emsdk/emscripten/incoming/system/include/emscripten.h:1:
/Users/zhushijie/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:234:25: error: typedef redefinition with different types ('struct _IO_FILE' vs 'struct __sFILE')
typedef struct _IO_FILE FILE;

**Comment by zhusjfaker** [comment]
vscode task.json

{
      "type": "shell",
      "label": "test",
      "command": "g++",
      "args": [
        "-std=c++11",
        "-I",
        "/Users/zhushijie/emsdk/emscripten/incoming/system/include",
        "-g",
        "-o",
        "${workspaceFolder}/index",
        "${file}"
      ],
      "options": {
        "cwd": "${workspaceFolder}"
      }
    },

**Comment by aheejin** [comment]
Not sure how you encountered this issue, but it seems that you are using g++? You should use emcc or em++ if you want to use emscripten.

**Comment by kinglezhuang** [comment]
@aheejin 

> Not sure how you encountered this issue, but it seems that you are using g++? You should use emcc or em++ if you want to use emscripten.

The same issue with llvm clang compiler.

Why we encounter such problem?
We want to develop a c++ library or program which include <emscripten/emscripten.h> & <emscripten/val.h> header files.
And we also want to  debug c++ library or program by using C++ development tools not just compile to js.

If we want to include fetch.h to get a resource or json from internet, how to verify it?
If some issues occur, we want to fix it on c++ layer then port to js.

How you implement c++ program & debug it?

**Comment by aheejin** [comment]
Sorry, you want to use emscripten compiler, or only emscripten header files?
And can you please provide us with a test case and a command line you ran to cause that error?

**Comment by kinglezhuang** [comment]
@aheejin 

I want to use Xcode/Clion/VSCode to write some c++ library and command line app by including emscripten header files & run the the command line app by using Xcode/Clion/VSCode.

**Comment by kinglezhuang** [comment]
Undefined symbols for architecture x86_64:
  "__emval_call_void_method", referenced from:
      emscripten::internal::MethodCaller<void, emscripten::val const&>::call(emscripten::internal::_EM_VAL*, char const*, emscripten::val const&) in main.o
  "__emval_decref", referenced from:
      emscripten::val::~val() in main.o
  "__emval_get_global", referenced from:
      emscripten::val::global(char const*) in main.o
  "__emval_get_method_caller", referenced from:
      emscripten::internal::Signature<void, emscripten::val const&>::init_method_caller() in main.o
  "__emval_incref", referenced from:
      emscripten::val::val(emscripten::val const&) in main.o
      emscripten::internal::BindingType<emscripten::val, void>::toWireType(emscripten::val const&) in main.o
  "__emval_new_array", referenced from:
      emscripten::val::array() in main.o
  "__emval_new_cstring", referenced from:
      emscripten::val::val(char const*) in main.o
  "__emval_set_property", referenced from:
      void emscripten::val::set<char [2]>(char const (&) [2], emscripten::val const&) in main.o
  "__emval_take_value", referenced from:
      emscripten::val::val<int>(int&&) in main.o
  "_emscripten_log", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by waywardmonkeys** [comment]
Pass `--bind` to `em++`.
