### ISSUE TITLE
Why is my Wasm injecting a useless value into a random location in memory?

### ISSUE THREAD

**Issue by GirkovArpa** [emscripten-core/emscripten#11012]
Compiling this:

```cpp
typedef long int i32;

extern "C" {
  i32 dot(i32 *vec1, i32 *vec2, i32 len) {
    i32 prod = 0;
    for (i32 i = 0; i < len; i++) {
      prod += (vec1[i] * vec2[i]);
    }
    return prod;
  }
}
```

```
emcc -O3 -Wl,--no-entry -s INITIAL_MEMORY=64kb -s MAXIMUM_MEMORY=6400kb -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=0kb -s STANDALONE_WASM -s EXPORTED_FUNCTIONS="['_dot']" "index.cpp" -o "index.wasm"
```
Produces a Wasm file ending with this:

```wat
 (data $d0 (i32.const 1536) "\a0\06"))
```
I don't want my memory to have a random value at a random location.  I want it to all be zeros.  So what is this for?

Using `wat2wasm` and `wasm2wat` I removed the line and it still works as intended.  A while back I had an RNG that was malfunctioning for some unknown reason.  It maintained state in linear memory, I assume it was this needless line putting a needless value in the memory that messed it up.

**Comment by sbc100** [comment]
Once this change lands in wasm-ld, the `-Map` linker flag will be the easiest way to answer this kind of question.

By running with `EMCC_DEBUG` and looking at the intermediate files I see that in this case wasm-ld is not generating any data segments at all so this must be added by some kind of binaryen pass.

**Comment by kripken** [comment]
I believe that is emscripten setting the sbrk location. There is an address in memory for the current sbrk, and we write to it at compile time.

This program doesn't use malloc, however, so we should be able to optimize this out. In fact we should be able to not include malloc/free by default in standalone mode, as it's just the JS glue that is the reason we include it by default. So we should be able to do this:
```diff
diff --git a/emcc.py b/emcc.py
index 14ea387dc..492fcb087 100755
--- a/emcc.py
+++ b/emcc.py
@@ -1400,7 +1400,7 @@ There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR P
     if shared.Settings.EMBIND:
       forced_stdlibs.append('libembind')
 
-    if not shared.Settings.MINIMAL_RUNTIME:
+    if not shared.Settings.MINIMAL_RUNTIME and not shared.Settings.STANDALONE_WASM:
       # Always need malloc and free to be kept alive and exported, for internal use and other
       # modules
       shared.Settings.EXPORTED_FUNCTIONS += ['_malloc', '_free']
```
But that doesn't work. @sbc100 I wonder if it's related to the other linking issues I am stuck on with atexit: like there, if I trace in lld malloc and free, I don't seem to get enough info to figure out why they are linked in:
```
.emscripten_cache/wasm/libdlmalloc.a: lazy definition of malloc
.emscripten_cache/wasm/libdlmalloc.a: lazy definition of free
```

**Comment by sbc100** [comment]
That change works for me, it gets rid of malloc and free in the wasm-ld output.

The problem is that that doesn't effect the emscripten-sbrk-ptr pass that binaryen uses to add that global pointer location, so it won't effect this memory segment.   I think the real solution is to declare sbrk_ptr as a C global so the linker can eliminate it.

**Comment by kripken** [comment]
Thanks @sbc100 , yeah, I was not measuring that correctly, you are right that your PR fixes the malloc issue.

If it's easy to make `sbrk_ptr` a C global that sounds good. Currently JS wants to be able to read and write that address, though, which is the complication.

Another option might be to see in the `--post-emscripten` pass whether `sbrk()` even exists. If it doesn't, then C won't need the pointer (but JS might). Not sure if that's simpler or not.

**Comment by sbc100** [comment]
I've been doing some experimenting moving `sbrk_ptr` into C and completely removing DYNAMICTOP_PTR and DYNAMIC_BASE!    I really think it would make sense, assuming we can make it work.

Especially because sbrk itself is always implemented in `system/lib/sbrk.c` these days.

**Comment by kripken** [comment]
@sbc100 that sounds great!
