### ISSUE TITLE
Incomplete return type in template argument for std::function fails to compile

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#11022]
If you compile the following:
```
#include <iostream>
#include <functional>
struct foo;
using fnc = std::function<foo(int)>;
struct bar {
    bar() {
        std::cout << "construct me" << std::endl;
    }
    fnc _f{nullptr};
};
int main(int argc, const char * argv[]) {
    // insert code here...
    std::cout << "Hello, World!\n";
    bar b{};
    return 0;
}
```
You get:
```
In file included from test.cc:1:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/iostream:37:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/ios:215:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/__locale:14:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/string:504:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/string_view:175:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/__string:56:
In file included from /Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/algorithm:644:
/Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/functional:2051:16: error: incomplete result type 'foo' in function definition
    static _Rp __call_empty(const __policy_storage*,
               ^
/Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/functional:2038:35: note: in instantiation of member function 'std::__2::__function::__policy_invoker<foo (int)>::__call_empty' requested here
    __policy_invoker() : __call_(&__call_empty) {}
                                  ^
/Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/functional:2090:5: note: in instantiation of member function 'std::__2::__function::__policy_invoker<foo (int)>::__policy_invoker' requested here
    __policy_func() : __policy_(__policy::__create_empty()) {}
    ^
/Users/dschuff/code/emr/emscripten-releases/emscripten/system/include/libcxx/functional:2276:5: note: in instantiation of member function 'std::__2::__function::__policy_func<foo (int)>::__policy_func' requested here
    function(nullptr_t) _NOEXCEPT {}
    ^
test.cc:9:11: note: in instantiation of member function 'std::__2::function<foo (int)>::function' requested here
    fnc _f{nullptr};
          ^
test.cc:3:8: note: forward declaration of 'foo'
struct foo;
       ^
1 error generated.
```
If you instead use a complete type:
`using fnc = std::function<void (int, foo&)>;`
then it will compile.
But it should be fine to have an incomplete return type for the template argument; it works on other platforms.

This seems likely to be a bug in libcxx that is either a regression (if we are close to tip-of-tree) or maybe something else related to our local changes?

**Comment by dschuff** [comment]
I might take a stab at updating libcxx again. @sbc100 did you run into any issues when you did that last time?

**Comment by sbc100** [comment]
Nope should be fairly straight forward.   See `system/lib/update_libcxx.py` and `system/lib/update_libcxxabi.py`.

I would recommend updating to the latest 10.x.x tag in llvm.  For a list of local patches see the readme for each library.

Thanks!

**Comment by dschuff** [comment]
#11038 didn't fix this, but I decided to land it anyway, since LLVM 10.x has been released.
For this issue, I discovered that it seems to be related to the fact that we're using libcxx ABI version 2. e.g. if I edit the lib builder in shared.py to use `-D_LIBCPP_ABI_VERSION=1` instead, then this bug goes away. That probably also explains why other major platforms that haven't wanted to break their ABI don't have that problem (since AFAIK ABIv2 hasn't been declared stable yet).

**Comment by sbc100** [comment]
Oh my, where did `_LIBCPP_ABI_VERSION=2` get added.   Can we remove it?

**Comment by sbc100** [comment]
Looks like it dates back to 3751c013cbbb03edfa4d9e36ab551941850b1228.  Still relevant?

**Comment by kripken** [comment]
cc @sunfishcode for last comment

**Comment by dschuff** [comment]
I don't know if we necessarily want to go all the way back to V1 There probably are things we might want from the v2 ABI, and the features all have individual defines, e.g. `_LIBCPP_ABI_ALTERNATE_STRING_LAYOUT`.
Eventually we will need to think about stabilizing the ABI (e.g. when we have stable dylibs), but we aren't necessarily there yet. 
I'll try to figure out which bit is actually causing this.

**Comment by dschuff** [comment]
well that was quick: it's [_LIBCPP_ABI_OPTIMIZED_FUNCTION](https://github.com/llvm/llvm-project/blob/master/libcxx/include/__config#L102). Haven't looked at why yet.

**Comment by dschuff** [comment]
I filed https://bugs.llvm.org/show_bug.cgi?id=46678 about this (and posted on libcxx-dev for more general advice about ABIv2)
