### ISSUE TITLE
emscripten_fetch calls onsuccess for url with non open port

### ISSUE THREAD

**Issue by lpotter** [emscripten-core/emscripten#11030]
When I try using emscripten_fetch and use a url that has a non functional port number, like http://google.com:81, it will return quickly in the onsuccess handler, with "None" as the data payload.

Using XMLHttpRequest javascript, it will simply timeout after a while and return in the onerror handler.

Using the fetch javascript API, it will also timeout and call the onerror handler.

I would expect it act like either the XMLHttpRequest or fetch javascript API's and call the onerror handler.

**Comment by PunitSalian** [comment]
I can take a look at this

**Comment by kripken** [comment]
That would be great @PunitSalian ! Let us know if you need anything.

**Comment by PunitSalian** [comment]
Reading the API docs will get back to you if any questions

**Comment by PunitSalian** [comment]
@lpotter  can you post the sample program used to reproduce this ?

**Comment by PietroMarchini94** [comment]
Hello there, I'm trying to replicate the issue with no luck.
Waiting for news from @lpotter  : @PunitSalian were you able to replicate it?
