### ISSUE TITLE
Failed to compile c++ files by include emscripten header files

### ISSUE THREAD

**Issue by kinglezhuang** [emscripten-core/emscripten#11032]
CompileC project/ems.build/Debug/ems.build/Objects-normal/x86_64/main.o main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/kingle.zhuang/Desktop/cmake_demo
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.15 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -index-store-path /Users/kingle.zhuang/Library/Developer/Xcode/DerivedData/ems-dordltcxoonnzcbbjdrefljlqrlb/Index/DataStore -I/Users/kingle.zhuang/Desktop/cmake_demo/project/Debug/include -I/usr/local/Cellar/emsdk/upstream/emscripten/system/include -I/usr/local/Cellar/emsdk/upstream/emscripten/system/lib -I/Users/kingle.zhuang/Desktop/cmake_demo/project/ems.build/Debug/ems.build/DerivedSources-normal/x86_64 -I/Users/kingle.zhuang/Desktop/cmake_demo/project/ems.build/Debug/ems.build/DerivedSources/x86_64 -I/Users/kingle.zhuang/Desktop/cmake_demo/project/ems.build/Debug/ems.build/DerivedSources -F/Users/kingle.zhuang/Desktop/cmake_demo/project/Debug -std=c++14 -MMD -MT dependencies -MF /Users/kingle.zhuang/Desktop/cmake_demo/project/ems.build/Debug/ems.build/Objects-normal/x86_64/main.d --serialize-diagnostics /Users/kingle.zhuang/Desktop/cmake_demo/project/ems.build/Debug/ems.build/Objects-normal/x86_64/main.dia -c /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp -o /Users/kingle.zhuang/Desktop/cmake_demo/project/ems.build/Debug/ems.build/Objects-normal/x86_64/main.o

In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:6:
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/val.h:193:9: error: static_assert failed due to requirement 'sizeof(emscripten::internal::GenericWireType) == 8' "GenericWireType must be 8 bytes"
        static_assert(sizeof(GenericWireType) == 8, "GenericWireType must be 8 bytes");
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:7:
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/bind.h:921:70: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
            static_assert(sizeof(FieldType) == sizeof(ElementType[N]));
                                                                     ^
                                                                     , ""
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:32:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:214:15: warning: 'OSAtomicCompareAndSwap32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCAS(a, value, v));
              ^
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:163:42: note: expanded from macro 'SDL_AtomicCAS'
#define SDL_AtomicCAS(a, oldval, newval) OSAtomicCompareAndSwap32Barrier((oldval), (newval), &(a)->value)
                                         ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:32:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:161:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libkern/OSAtomic.h:43:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libkern/OSAtomicDeprecated.h:518:9: note: 'OSAtomicCompareAndSwap32Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32Barrier( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:32:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:244:15: warning: 'OSAtomicCompareAndSwap32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCAS(a, value, (value + v)));
              ^
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:163:42: note: expanded from macro 'SDL_AtomicCAS'
#define SDL_AtomicCAS(a, oldval, newval) OSAtomicCompareAndSwap32Barrier((oldval), (newval), &(a)->value)
                                         ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:32:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:161:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libkern/OSAtomic.h:43:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libkern/OSAtomicDeprecated.h:518:9: note: 'OSAtomicCompareAndSwap32Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap32Barrier( int32_t __oldValue, int32_t __newValue, volatile int32_t *__theValue );
        ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:32:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:289:15: warning: 'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
    } while (!SDL_AtomicCASPtr(a, value, v));
              ^
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:167:45: note: expanded from macro 'SDL_AtomicCASPtr'
#define SDL_AtomicCASPtr(a, oldval, newval) OSAtomicCompareAndSwap64Barrier((int64_t)(oldval), (int64_t)(newval), (int64_t*)(a))
                                            ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:32:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:161:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libkern/OSAtomic.h:43:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libkern/OSAtomicDeprecated.h:645:9: note: 'OSAtomicCompareAndSwap64Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t __oldValue, int64_t __newValue,
        ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:9:
/usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/emscripten.h:233:25: error: typedef redefinition with different types ('struct _IO_FILE' vs 'struct __sFILE')
typedef struct _IO_FILE FILE;
                        ^
In file included from /Users/kingle.zhuang/Desktop/cmake_demo/main.cpp:6:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/val.h:15:
In file included from /usr/local/Cellar/emsdk/upstream/emscripten/system/include/emscripten/wire.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdio.h:108:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:157:3: note: previous definition is here
} FILE;
  ^
4 warnings and 2 errors generated.

Why we encounter such problem?
We want to develop a c++ library or program which include <emscripten/emscripten.h> & <emscripten/val.h> header files.
And we also want to debug c++ library or program by using C++ development tools not just compile to js.

If we want to include fetch.h to get a resource or json from internet, how to verify it?
If some issues occur, we want to fix it on c++ layer then port to js.

How you implement c++ program & debug it?

**Comment by sbc100** [comment]
I looks like system include paths somehow being adding to your emscripten
builds.

emscripten is cross compiler and is not compatible with your system
headers.  Include paths such as
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/`
should not be showing up in your emscripten build.  Perhaps you build
system is somehow adding this include paths by mistake?

cheers,
sam
