### ISSUE TITLE
WASM_ASYNC_COMPILATION=0 && ASSERTIONS=1

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#11045]
As discussed in #6092, when using sync loading with assertions enabled, you get an error due to the wrapper functions that are installed by `ASSERTIONS`:

```
asm["__wasm_call_ctors"] = function() {
                         ^

TypeError: Cannot assign to read only property '__wasm_call_ctors' of object '[object Object]'
    at /Users/bruce/.../embind_test.js:4697:26
```

The relevant code is from within the generated JS is:

```
var asm = createWasm();
var real____wasm_call_ctors = asm["__wasm_call_ctors"];
asm["__wasm_call_ctors"] = function() {
  assert(runtimeInitialized, 'you need to wait for the runtime to be ready (e.g. wait for main() to be called)');
  assert(!runtimeExited, 'the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)');
  return real____wasm_call_ctors.apply(null, arguments);
};
```

This happens because `WebAssembly.Instance.exports` is a read-only object as defined here (and in the spec): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Instance/exports

You can see that it gets `asm` by calling `createWasm`.

In `src/preamble.js`, the end of the `createWasm` function looks like:

```
#if WASM_ASYNC_COMPILATION
#if RUNTIME_LOGGING
  err('asynchronously preparing wasm');
#endif
  instantiateAsync();
#if LOAD_SOURCE_MAP
  getSourceMapPromise().then(receiveSourceMapJSON);
#endif
  return {}; // no exports yet; we'll fill them in later
#else
  instantiateSync();
  return Module['asm']; // exports were assigned here
#endif
}
```

So, in the async case, it just returns `{}`, while in the sync case, it is returning `Module[asm]`.

`Module[asm]` is set up in the start of `receiveInstance`:

```
  // Load the wasm module and create an instance of using native support in the JS engine.
  // handle a generated wasm instance, receiving its exports and
  // performing other necessary setup
  /** @param {WebAssembly.Module=} module*/
  function receiveInstance(instance, module) {
    var exports = instance.exports;
#if RELOCATABLE
    exports = relocateExports(exports, GLOBAL_BASE, 0);
#endif
#if WASM_BACKEND && ASYNCIFY
    exports = Asyncify.instrumentWasmExports(exports);
#endif
    Module['asm'] = exports;
```

So here, we can see that it is getting assigned the read-only value from `WebAssembly.Instance.exports`.

This does not require a browser to reproduce. I'm hitting it running some automated tests under Node, trying to see if I can enable `ASSERTIONS` for the tests. We use sync compilation for other reasons that will be difficult to address in the near term future.

**Comment by sbc100** [comment]
Indeed, it seems like the `you need to wait for the runtime to be ready` assertions don't make sense at all in `WASM_ASYNC_COMPILATION` since you never need to wait.

I'm a little confused as to why we are not seeing this in any of our testing though.  Presumably we have a bunch of test for `WASM_ASYNC_COMPILATION` mode and a lot of testing with assertions enabled.  Do you know why we don't see this in testing today?

**Comment by sbc100** [comment]
I'm unable to reproduce this, at the least using the version of node that we use for testing: node-v14.1.0-

**Comment by sbc100** [comment]
Sorry we don't use v14.1.0 for testing.. but I tested with v14.1.0 and I still can't reproduce it.

**Comment by sbc100** [comment]
Oh.. I see the problem.  From the spec: `This error happens only in strict mode code. In non-strict code, the assignment is silently ignored.`.

Still we should fix it.  And we should increase the use of strict in our test code.
