### ISSUE TITLE
Upstream wasm is 25% larger on mozjpeg_enc in Squoosh

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#11055]
See https://github.com/GoogleChromeLabs/squoosh/pull/750 where this was noticed.

[fastcomp_prof.wasm.gz](https://github.com/emscripten-core/emscripten/files/4565863/fastcomp_prof.wasm.gz)
[upstream_prof.wasm.gz](https://github.com/emscripten-core/emscripten/files/4565864/upstream_prof.wasm.gz)

The upstream wasm file is 25% bigger (8% after gzip). This doesn't seem related to code at all. It's all in the data section,
```
$ bloaty upstream_prof.wasm -d symbols -- fastcomp_prof.wasm
     VM SIZE                                FILE SIZE
 --------------                          --------------
  [ = ]       0 [section Data]           +72.5Ki   +92%
...
  [ = ]       0 TOTAL                    +66.6Ki   +25%
```

Almost every single function is smaller with upstream, and their total size is also smaller. But the huge data size increase of 72K wins.

Eyeballing the wasm files, it's not easy for me to see what's actually different in those data sections. Maybe someone can might notice something though? Also, do we have tools to debug a binary size change like this? (like diff data sections, see which part came from which source file)

**Comment by RReverser** [comment]
> Also, do we have tools to debug a binary size change like this? (like diff data sections, see which part came from which source file)

One thing I found helpful with wasm-ld is `--no-merge-data-segments` which allows to sort / diff them one-by-one. But I'm not sure if there's a counterpart for fastcomp to use for comparison?

**Comment by kripken** [comment]
There isn't, I don't think. Fastcomp's linker for data is extremely simple, it just reads the LLVM IR: https://github.com/emscripten-core/emscripten-fastcomp/blob/ede231d349e048cf2971d1efe4d73f62325ebfe2/lib/Target/JSBackend/JSBackend.cpp#L4284

**Comment by RReverser** [comment]
Looks like you should be able to at least add logging to print separate strings from the IR in that function? More tedious than if there was an existing tool, but could probably work.

**Comment by kripken** [comment]
Ah, no need, I figured this out. The difference vanishes if building with LTO. The wasm is then 2.5% smaller than fastcomp in fact.

Fastcomp runs `-globaldce` by default, and it must be doing quite a lot on this project. Upstream uses wasm object files by default, and so we don't have that.

Would be good to build that codec with `-flto` on all compile commands.

**Comment by RReverser** [comment]
Ah sounds good. I've actually tried `-flto` in past, but didn't see any improvement, so decided to leave builds without it.

Back then I didn't know that we're still using Fastcomp backend (it would probably be good to raise an issue on that Docker container's repo, as it's not very obvious), so that probably explains it all.

**Comment by RReverser** [comment]
Raised an issue and assigned it to myself on Squoosh side. Thanks for the investigation!

**Comment by kripken** [comment]
Yeah, I've already opened https://github.com/trzecieu/emscripten-docker/issues/66

**Comment by sbc100** [comment]
I'm curious why LTO helps so much the data section in this case.  Perhaps there is some kind data that repeats in each object file which is merged by the regular linker but not by wasm-ld.  

IIRC there are some things like SHF_MERGE and SHF_STRING in ELF that we don't yet have an equivalent of.

**Comment by RReverser** [comment]
> Yeah, I've already opened [trzecieu/emscripten-docker#66](https://github.com/trzecieu/emscripten-docker/issues/66)

Beat me to it :) Thanks!

**Comment by RReverser** [comment]
> Perhaps there is some kind data that repeats in each object file which is merged by the regular linker but not by wasm-ld.

@sbc100 Sounds plausible, especially if these are just some constants from `.h` headers that end up in each object file.
