### ISSUE TITLE
Incorrect instructions for starting SimpleHTTPServer on Windows

### ISSUE THREAD

**Issue by TheMostDiligent** [emscripten-core/emscripten#11068]
Hello!

[This section](https://emscripten.org/docs/getting_started/Tutorial.html#generating-html) suggests the following command to start SimpleHTTPServer:
```
python -m SimpleHTTPServer 8080
```
On Windows, this command generates the following error:
```
emsdk\python\3.7.4_64bit\python.exe: No module named SimpleHTTPServer
```
The correct format for the command is:
```
python -m http.server 8080
```

Also, take a look at this [SO question](https://stackoverflow.com/questions/7943751/what-is-the-python-3-equivalent-of-python-m-simplehttpserver)

**Comment by kripken** [comment]
Thanks @TheMostDiligent , I updated the docs now. I think the difference is python 2 vs 3 in those commands, https://emscripten.org/docs/getting_started/FAQ.html#why-does-my-program-stall-in-downloading-or-preparing
