### ISSUE TITLE
dynCall is not a function

### ISSUE THREAD

**Issue by fmod-mathew** [emscripten-core/emscripten#11074]
At runtime I am receiving the following message "dynCall is not a function" when executing a function that takes floats as arguments. 

For reference I'm building ASM.js with fastcomp using the latest SDK. However after some investigations I've nailed down the point where it broke to 1.39.9, more specifically #10417. There is a section of code removed in embind.js that handles resolving functions that take float arguments with receiving functions implemented as double. Adding this code back in resolve my issue.

The comments indicate this code is super ancient, which leads me to believe I'm not doing something right. Regardless, my code works fine in all previous versions, also works fine for fastcomp wasm, upstream JS and upstream wasm variants.

My current work around is enable PRECISE_F32 to force all the bindings to "f" not "d" however I'm slightly worried about the code bloat from the math.fround and any performance implications.

**Comment by kripken** [comment]
Sounds like we're missing tests for some case, sorry about that...

As this works in upstream JS, I'm curious why you're using fastcomp asm.js still?

**Comment by fmod-mathew** [comment]
We develop the audio middleware FMOD, so we have a variety of different compilation targets to satisfy our customer requests. We've just upgraded to latest and are rolling out upstream built versions but we are maintaining fastcomp for now also.

**Comment by kripken** [comment]
I see, thanks @fmod-mathew 

In that case I don't think this is important to prioritize, as it's a fastcomp-asm.js-only issue. We're mostly focused on issues with switching from fastcomp to upstream at this point. Please let us know if you have any problems there!

(leaving open since we also would accept a patch if someone is interested to fix this)
