### ISSUE TITLE
Official Docker images

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#11078]
Something that came up in discussion with @kripken: currently the semi-official way to use Emscripten from Dockers is by using images published by @trzecieu at https://github.com/trzecieu/emscripten-docker.

They're doing a great job at maintaining images to the best of their abilities, but it's understandable that with this approach versions are often lagging a bit behind official releases and don't reflect official defaults changes (like https://github.com/trzecieu/emscripten-docker/issues/66) and so on.

With this in mind and given the popularity of Docker as a way to use Emscripten, it would be useful to integrate build & publish process into the Emscripten CI release process.

@trzecieu is that something you would be interested in upstreaming?

**Comment by sbc100** [comment]
I think we were already working towards this a while ago, but I guess out efforts stalled.

The Dockerfile itself was moved the emsdk repo: https://github.com/emscripten-core/emsdk/commits/master/docker.  See https://github.com/emscripten-core/emsdk/pull/368.

It makes sense to live there because its really a docker image that contains not just emscripten but the whole emsdk.

We even have a home of dockerhub but its currently empty: https://hub.docker.com/r/emscripten/emsdk

I agree we should re-start these efforts.

**Comment by sbc100** [comment]
Even if we finish the existing outstanding transition though, you be bring up a good question: How and when should we automatically publish this? 

Currently the way we publish releases is to modify `emscripten-releases-tags.txt` in the emsdk repo, so I guess it makes sense to the emsdk actions on github master to trigger the publication whenever `emscripten-releases-tags.txt` changes?

**Comment by RReverser** [comment]
Ah yeah, makes perfect sense for this to live in emsdk. Let me transfer the issue over...

**Comment by trzecieu** [comment]
Hi @RReverser, yes this is something that I'm planning to re-boot in next couple of days. I apology for lack of activity.

**Comment by RReverser** [comment]
Linking a related issue in emsdk repo for reference: https://github.com/emscripten-core/emsdk/issues/372

**Comment by sbc100** [comment]
can be closed now?    #372 still has some minor cleanups such as adding the README and redirecting people from the older images.    But we are publishing images automatically now via github actions to https://hub.docker.com/r/emscripten/emsdk.

**Comment by RReverser** [comment]
I think it's useful to keep this as tracking issue for emscripten.org documentation still (since these are different repos).

**Comment by RReverser** [comment]
This can be closed now as docs were updated in https://github.com/emscripten-core/emscripten/issues/11772.
