### ISSUE TITLE
Which C++ statements are related to Webassembly's memory operations?

### ISSUE THREAD

**Issue by B-doublemint** [emscripten-core/emscripten#11089]
Which C++ statements are related to Webassembly's memory operations?  Such as i32.laod, i32.store, from which statement are these instructions compiled?

**Comment by sbc100** [comment]
Any reading or writing to global or local C/C++ variables could lower to these instructions.

**Comment by B-doublemint** [comment]
Thanks.

**Comment by sbc100** [comment]
Can we close this now?

**Comment by B-doublemint** [comment]
I'm sorry sir, another question. The type of target function in call_indirect instruction is not in table section. 
For example, 'call_indirect (type $t8) $T0' in one function, but I can't find a function with type t8 in table's elem '(elem $e0 (i32.const 1) $f78 $f71 $f65 $f60 $f51 $f44 $f22 $f35 $f77 $f76 $f75 $f54 $_start $f28 $f27 $f62 $f61 $f59 $f52 $f18 $f34 $f34 $f50 $f39 $f42 $f48 $f18 $f40 $f43 $f47 $f18 $f41 $f45 $f46)'.

**Comment by sbc100** [comment]
It is possible in C/C++ to create a program that contains a call_indirect to a function of type X but have a table with functions of type X.

In the most basic example you can create a program which contains no elems at all but still uses call_indirect:  All you need to is pass NULL where a function pointer is expected in you C/C++ program.

I'm not saying that is what is happening here, but its possible. 

How is your problem manifesting, are you getting a crash at runtime?   Can you build with `--profiling` and `-s ASSERTIONS` and get any more information. 

Also would you mind opening new issue for this?

**Comment by B-doublemint** [comment]
ok.
