### ISSUE TITLE
Consider properly supporting -Wl,--version

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#11092]
`emcc` currently requires a dummy file input in order to pass this flag to the linker. This does the job, but it also prints an ugly error and may trigger a rebuild of cached objects.

```
$ ./emcc -Wl,--version wtf.c
LLD 11.0.0 (https://github.com/llvm/llvm-project 68400a23083769244a6af07ec42ec61877a4bb12)
Failed opening '/tmp/emscripten_temp_m3xfln_n/a.out.wasm'
emcc: error: '/opt/binaryen/bin/wasm-emscripten-finalize --detect-features --global-base=1024 --check-stack-overflow /tmp/emscripten_temp_m3xfln_n/a.out.wasm -o /tmp/emscripten_temp_m3xfln_n/a.out.wasm.o.wasm' failed (1)
```

Related https://github.com/mesonbuild/meson/pull/7090

**Comment by sbc100** [comment]
Hmm .. that is somwhat odd thing to do but I guess we could support it.    By passing that flag you are basically asking the linker not to write any output, which obviously confused the later stages of the compilation.

I guess we can include special case handling for that flag since it seems to work with clang and gcc.

Regarding mesonbuild/meson#7090, I can think of two other possible approaches:

1. Derive the wasm-ld path in some other way and then run the linker with `--version`, like on other platforms.  For example it looks like if you run `emcc -v` will print the llvm install path:

```
$ ./emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.15
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 57d361bd2f3668eefa7028ad4a2d616317ed437c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/sbc/dev/wasm/emsdk/upstream/bin
```

Then you can join `InstalledDir` to `wasm-ld`.

2. Just report the emscripten version and don't try to dig down to find the actual version of wasm-ld.  The reason this might make more sense for emscripten than other toolchains is that wasm-ld is really just one part of the linking process.  There are many other parts too (such as wasm-emscripten-finalize, wasm-opt, compiler.js, and more).

**Comment by Akaricchi** [comment]
> Hmm .. that is somwhat odd thing to do but I guess we could support it. By passing that flag you are basically asking the linker not to write any output, which obviously confused the later stages of the compilation.

I don't think this is odd, it's pretty standard practice for determining the linker version.

> Derive the wasm-ld path in some other way and then run the linker with --version, like on other platforms. For example it looks like if you run emcc -v will print the llvm install path:

I suppose that could work, but what other platforms are you talking about? Build systems generally prefer not to invoke the linker directly with GNU-like toolchains. Meson (and probably other build systems) does the same thing for GCC, Clang, etc. Though not the case with Emscripten, sometimes the actual linker used depends on the compiler flags (`-fuse-ld=...`).

> Just report the emscripten version and don't try to dig down to find the actual version of wasm-ld. The reason this might make more sense for emscripten than other toolchains is that wasm-ld is really just one part of the linking process. There are many other parts too (such as wasm-emscripten-finalize, wasm-opt, compiler.js, and more).

I don't have a strong opinion here. Meson likes reporting the compiler and linker versions separately, and I found it was doing it correctly for Emscripten, so I fixed it. I'm just reporting an inconsistency with the gcc/clang behavior.

**Comment by Akaricchi** [comment]
Also, perhaps I wasn't clear enough. What I expect is for `emcc -Wl,--version` to work without any input; the dummy `wtf.c` file is just my workaround to make `emcc` call the linker at all, because otherwise it complains about the lack of input files and bails early. Though GCC and Clang also ignore any inputs if `-Wl,--version` is passed.

**Comment by sbc100** [comment]
> > Hmm .. that is somwhat odd thing to do but I guess we could support it. By passing that flag you are basically asking the linker not to write any output, which obviously confused the later stages of the compilation.
> 
> I don't think this is odd, it's pretty standard practice for determining the linker version.

Maybe odd was a bad choice of words.   I've just never seen the technique used to determine the linker version.  I guess you learn something new every day (I've been working on for 20 years and still learning).

**Comment by sbc100** [comment]
Interesting .. just running `gcc` or `clang` without any args will produce `no input files` and fail, but if you pass *any* linker flag at all they try to perform a link against nothing but the system libraries.

I guess we should do that same, and also somehow detect that `--version` flag and not perform any post-link steps.   Its an odd case where the linker returns `0` but doesn't create the output file.
