### ISSUE TITLE
How to track the target function of call_indirect instruction?

### ISSUE THREAD

**Issue by B-doublemint** [emscripten-core/emscripten#11104]
The type of target function in call_indirect instruction can not be found in table section. I want to parse wasm file to build control flow graph. How can I deal with it?

**Comment by sbc100** [comment]
IIUC target function of a call_indirect instruction not something that can be known statically.  @kripken , can you confirm?  My understanding is that building full control flow graph is not generally possible in the presence of `call_indirect`.

**Comment by B-doublemint** [comment]
I learnd all of the target functions in call_indirect instruction should be recorded in table section. Maybe I can't locate the target function statically, I hope to narrow search by function type. Is that feasible?

**Comment by kripken** [comment]
Both last comments are correct, yes - all you can know of an indirect call is what type it will have. So you can at least filter the table by that (as it will trap if the type is wrong). However, the table can change at runtime, so you must be sure the application doesn't actually do that.

**Comment by B-doublemint** [comment]
Thank you sir.
