### ISSUE TITLE
emcc missing npm dependencies.

### ISSUE THREAD

**Issue by kevzettler** [emscripten-core/emscripten#11117]
I installed emscripten through `homebrew` on Mac. `emcc` is failing with:

`emcc: error: html-minifier-terser was not found! Please run "npm install" in Emscripten root directory to set up npm dependencies!`

I have tried installing `html-minifier-terser` as a global npm module and it is still not detecting it

What path does `emcc` expect for the npm dependencies ?

**Comment by sbc100** [comment]
Its looks like it looking in the node_modules directory within the emscripten directory:
https://github.com/emscripten-core/emscripten/blob/423a77f9be2a26d5a86dd9e4aec4e095cd73fb70/emcc.py#L3724

If you run `npm install` in the emscripten directory it will ensure the correct version is installed.  I would worry that simply using the global module might mean we don't get the version we expect.

However I do suspect that we are probably using the wrong method to find the js entry point.  Suggestions for improvements welcome.

**Comment by kevzettler** [comment]
thanks @sbc100 wheres is the "emscripten directory" though? I have tried moving the node-modules folder adjacent to 

```
 kevs-mbp:flare-engine kevzettler$ which emcc
/usr/local/bin/emcc
kevs-mbp:flare-engine kevzettler$ ls -lash /usr/local/bin/emcc
0 lrwxr-xr-x  1 kevzettler  admin    37B May  8 15:51 /usr/local/bin/emcc -> ../Cellar/emscripten/1.39.15/bin/emcc
```

**Comment by sbc100** [comment]
It looks like you are using the homebrew package.  The package probably needs to be updated.  The solution is most likely to run `npm ci` (or better still `npm ci`) in the emscripten directory as part of the post-install step.   This way all the our dependencies that are specified in the `package.json` file will b installed in the `node_modules` directory under the emscripten directory.

The emscripten root is the place where you can find the emscripten source tree.  It will contain, for example, the `tools` directory and the `pacakge.json` file.   In the homebrew case I imagine it is probably something like `/usr/local/Cellar/emscripten/1.39.15/`.

**Comment by kevzettler** [comment]
>It looks like you are using the homebrew package. 

yes that is previously stated above https://github.com/emscripten-core/emscripten/issues/11117#issue-615064010
<img width="433" alt="Screenshot 2020-05-08 22 03 05" src="https://user-images.githubusercontent.com/126209/81464568-b6122680-9177-11ea-8a54-b31048289d02.png">

The emscripten executable I am working with has  source *no source tree directory* as you mention because it is installed post-compilation. the question here is... What path does this python line evaluate to, when precompiled?

```
[shared.path_from_root('node_modules', '.bin', 'html-minifier-terser' + ('.cmd' if WINDOWS else '')), filename, '-o', filename] + opts, env=shared.env_with_node_in_path()
```

**Comment by sbc100** [comment]
I'm not sure why you mean by "precompiled".  emscripten is made up of hundreds of files.  If you can find out where the homebrew package installed them all, that will be your root.   Specifically if you can find the file in question, `emcc.py` (with the .py extension), that file lives in the root.    

Once you have found that directory you run `npm install` and the package.json will tell npm what needs to be install.  (or course the real fix would be to update the homebrew package to do this).

**Comment by kevzettler** [comment]
Sorry I said "precompiled" didn't expect that to be a trigger word. The core question still remains...

What does this path evaluate to in the `emcc` executable?

`[shared.path_from_root('node_modules', '.bin', 'html-minifier-terser' + ('.cmd' if WINDOWS else '')), filename, '-o', filename] + opts, env=shared.env_with_node_in_path()
`

surely if I `mv` `cp` the `emcc` executable around it is still going to try to evaluate that path and it could differ from where the source `emcc.py` was.

So it is either a relative path to `emcc` or it is a absolute path and it is going to be what...?

**Comment by sbc100** [comment]
It looks like the homebrew package just copyies all the files from the git repo: https://github.com/Homebrew/homebrew-core/blob/master/Formula/emscripten.rb#L48.

Try `/usr/local/Cellar/emscripten/1.39.15/` that looks like the likely path, although I don't have a mac to verify.

I imagine the file are you looking at called emcc, is some kind of symbol link or script that points back to the emscripten root.   As far as I know there is no such thing as an `emcc` executable, it should just be a script.

**Comment by kevzettler** [comment]
thank you for your support @sbc100, much appreciated.

>I imagine the file are you looking at called emcc, is some kind of symbol link or script that points >back to the emscripten root. As far as I know there is no such thing as an emcc executable, it >should just be a script.

yes I have previously stated that and shown the symbol link paths above at:
https://github.com/emscripten-core/emscripten/issues/11117#issuecomment-626091350

The symbol link is:
```
/usr/local/bin/emcc -> ../Cellar/emscripten/1.39.15/bin/emcc
```

I have copied the `node_modules` directory to these places...

`/usr/local/Cellar/emscripten/1.39.15/`
```
kevs-mbp:bin kevzettler$ stat /usr/local/Cellar/emscripten/1.39.15/node_modules/
16777220 46069101 drwxr-xr-x 19 kevzettler staff 0 608 "May  8 22:56:11 2020" "May  8 22:44:11 2020" "May  8 22:44:11 2020" "May  8 22:44:11 2020" 4096 0 0 /usr/local/Cellar/emscripten/1.39.15/node_modules/
```

`/usr/local/Cellar/emscripten/1.39.15/bin/`
```
kevs-mbp:bin kevzettler$ stat /usr/local/Cellar/emscripten/1.39.15/bin/node_modules/
16777220 46047331 drwxr-xr-x 20
```

They are still not being referenced by `emcc` which leads me to believe that is looking for an absolute path. or a path relative to the filesystem it was compiled on.

**Comment by sbc100** [comment]
I think that `../Cellar/emscripten/1.39.15/bin/emcc` must also be symbol link or shell script that points back to the actual emscripten directory.  Can you take a look at that file and see where it is pointing?

I would advise against just copying some existing `node_modules`  directory.  The `node_modules` that you end up with should be the result of running `npm install` specifically in the correct directory where our `pacakge.json` lives.   That way you know you have the exact packages that emscripten needs.

**Comment by kevzettler** [comment]
`../Cellar/emscripten/1.39.15/bin/emcc` does appear to be a shell script... it looks like:

```
kevs-mbp:bin kevzettler$ cat /usr/local/Cellar/emscripten/1.39.15/bin/emcc
#!/bin/bash
PYTHON="/usr/local/opt/python@3.8/bin/python3" exec "/usr/local/Cellar/emscripten/1.39.15/libexec/emcc" "$@"
```

`/usr/local/Cellar/emscripten/1.39.15/libexec/` 
seems to be the missing piece and the "emscripten root"
 it has a `package.json` within.

I copied the `node_modules` directly from the other previous directories I tried and it worked because npm locks `node-modules` with the `package-lock.json`.

**Comment by kevzettler** [comment]
thanks @sbc100 much appreciated

**Comment by cschar** [comment]
I had installed emscripten via nix packages.... uninstalled then used the vanilla install instructions
https://emscripten.org/docs/getting_started/downloads.html#installation-instructions
problem went away
