### ISSUE TITLE
Protecting/obfuscating emscripten's virtual filesystem

### ISSUE THREAD

**Issue by szilardszaloki** [emscripten-core/emscripten#11129]
Hi there,

I'm wondering how the contents of emscripten's virtual filesystem (the .data file) could be protected.
In particular, I'm about to load 3D models and display them to the user, but I don't want the geometry, texture, etc. files to be publicly available, since they are not necessarily my property. AFAIK, the .data file either sits next to the generated HTML/JS/WASM files, or it's fetched via the URL returned by `Module`'s `locateFile` function. Either way, once the user has the .data file, it's quite straightforward to assemble the files making up the model. Is there a built-in obfuscation feature that could be applied to the virtual filesystem, or does there exist a general rule of thumb (besides encrypting all the files on server side and decrypting them runtime, which would be overkill)?

Thanks in advance!

Best,
Szilard

**Comment by juj** [comment]
For whatever non-encrypting solution you will use, I will as an attacker use the browser's Network Transfers tab and grab the file from there, no code modifications required. Whatever Emscripten has in `locateFile`, or `Module` or other structures does not play a role in such a grab-via-devtools attack.

If you would like to slow me down, the only thing you can do is to encrypt the file and decrypt inside wasm heap. Unfortunately that is not watertight either, as I can still disassemble the wasm code, but as an attacker I would certainly be doing some cost benefit analysis whether the extra time that it takes to disassemble would be worth it.

There are no built-in encryption routines in Emscripten.

If you think client-side decryption is an overkill obfuscation, you could also try e.g. a rot-13 conversion (or xor ^ -1u for binary data) for obfuscation, that would be very simple, and will still slow the attacker down equally likely.

**Comment by szilardszaloki** [comment]
Thanks for the quick response!
