### ISSUE TITLE
std::exception_ptr incorrectly deleted on worker thread completion

### ISSUE THREAD

**Issue by ptc-pmacer** [emscripten-core/emscripten#11127]
It appears that a std::exception_ptr created on a worker thread is deleted when the thread completes, even if a reference to it still exists on the main thread.

Sample code:
```C++
#include <iostream>
#include <thread>

class AsyncTask 
{
public:
	AsyncTask() {}
	~AsyncTask() { std::cout<<"AsyncTask Destructed"<<std::endl; }
	
	void SetTaskFailed(std::exception_ptr e) { m_exception_ptr = e; };
	
private:
	std::exception_ptr m_exception_ptr;
};

std::shared_ptr<AsyncTask> myJob;

void thread_function()
{
	auto e = std::make_shared<AsyncTask>();
	e->SetTaskFailed(std::make_exception_ptr(std::runtime_error { "Task Failed" }));
	myJob = e;
	e = nullptr;
	std::cout<<"Exit of Thread"<<std::endl;
}

int main()
{
	std::thread threadObj(thread_function);
	threadObj.join();
	std::cout<<"Removing myJob"<<std::endl;
	myJob = nullptr;
	std::cout<<"Exit of Main Function"<<std::endl;
	return 0;
}
````
Compilation command:
`emcc -g4 -O0 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=5 -s DISABLE_EXCEPTION_CATCHING=0 -fexceptions -o index.html main.cpp`

In the sample code above, we create an AsyncTask in a worker thread, which we then mark as failed, providing a std::exception_ptr to give the reason for the failure.  The AsyncTask is then referenced by a global variable.  However, when we subsequently de-reference this AsyncTask on the main thread (after the worker thread is completed) the following error occurs:

```
index.js:2536 Uncaught TypeError: Cannot read property 'refcount' of undefined
    at ___exception_decRef (index.js:2536)
    at ___cxa_decrement_exception_refcount (index.js:2550)
    at std::exception_ptr::~exception_ptr() (:8080/wasm-function[270]:0x8011)
    at AsyncTask::~AsyncTask() (:8080/wasm-function[189]:0x63e4)
    at std::__2::__shared_ptr_emplace<AsyncTask, std::__2::allocator<AsyncTask> >::__on_zero_shared() (:8080/wasm-function[188]:0x62c3)
    at std::__2::__shared_count::__release_shared() (:8080/wasm-function[157]:0x575c)
    at std::__2::__shared_weak_count::__release_shared() (:8080/wasm-function[79]:0x1f89)
    at std::__2::shared_ptr<AsyncTask>::~shared_ptr() (:8080/wasm-function[78]:0x1f27)
    at std::__2::shared_ptr<AsyncTask>::operator=(std::__2::shared_ptr<AsyncTask>&&) (:8080/wasm-function[88]:0x2758)
    at __original_main (:8080/wasm-function[110]:0x3a0d)
````

**Comment by kripken** [comment]
I didn't know this, but yes, the docs say that a `std::exception_ptr` should keep the underlying exception alive while there is any such reference to it. So it does seem like it should be kept alive here.

Not sure offhand if the problem is that in exceptions code we don't do that (cc @aheejin ) or if in pthreads code we run global destructors unnecessarily when a pthread exits. The last option should be easy to confirm or disprove with some logging.

**Comment by jpharvey** [comment]
Just a small follow up. I don't think this is the pthread exit handling. It is about the __exception_infos objects which appears to be unique to each thread.
If the code is modified as follows

```
#include <iostream>
#include <thread>

class AsyncTask 
{
public:
	AsyncTask() {}
	~AsyncTask() { std::cout<<"AsyncTask Destructed"<<std::endl;}
	
	void SetTaskFailed(std::exception_ptr e) { m_exception_ptr = e; };
	
private:
	std::exception_ptr m_exception_ptr;
};

std::shared_ptr<AsyncTask> myJob;
extern "C" void *__exception_deAdjust(void *);
void thread_function()
{
	auto e = std::make_shared<AsyncTask>();
	e->SetTaskFailed(std::make_exception_ptr(std::runtime_error { "Task Failed" }));
	myJob = e;
	e = nullptr;
	std::cout<<"Sleep"<<std::endl;
    std::this_thread::sleep_for (std::chrono::seconds(10));
	std::cout<<"Exit of Thread"<<std::endl;
}

int main()
{
	std::cout<<"main"<<std::endl;
    std::thread threadObj(thread_function);
	std::cout<<"started thread"<<std::endl;
    std::this_thread::sleep_for (std::chrono::seconds(5));
	std::cout<<"Removing myJob"<<std::endl;
	myJob = nullptr;
    std::cout<<"wait thread"<<std::endl;
	threadObj.join();
	std::cout<<"Exit of Main Function"<<std::endl;
	return 0;
}
```
The thread is still alive when the main thread tries to delete the exception_ptr. The __exceptions_infos is empty on the main thread at that time but in the other thread contains the address of the exception item to look up.  
Hope that helps a bit. I have no idea how to make that shared between the threads.

**Comment by ptc-pmacer** [comment]
Is it possible to get some help with this issue?  It is a major issue for us

**Comment by kripken** [comment]
If the problem is that the JS structures contain data set on one thread but needed on another, then that is a current limitation, see #11233 As mentioned there the new wasm exception handling support will fix this, and be fully thread-safe.

**Comment by arlebedev** [comment]
I have created #11503 with minimal example. Gonna fix it somehow.
