### ISSUE TITLE
Missed dead code elimination optimization opportunity on web apps that never quit (+7KB, ~5.4% overhead)

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#11136]
Here is something that's been on the back of my mind for a while now. STR:

```c++
#include <emscripten/html5.h>

class Foo
{
public:
	~Foo()
	{
		emscripten_console_log("Foo deleted!");
	}
};

Foo foo;

int main()
{
    return 0;
}
```
Build with
```bash
em++ a.cpp -o a.html -s EXIT_RUNTIME=0 -Oz -g3
```

The generated JS code will contain
```js
  function _emscripten_console_log(str) {
      console.log(UTF8ToString(str));
    }
...
var asmLibraryArg = { "emscripten_console_log": _emscripten_console_log, ... };
```
and the generated Wasm code will contain
```
   NAN%       0 emscripten_console_log       24   1.3%
   NAN%       0 Foo::~Foo()                  23   1.3%
```
wasm-dis also shows a
```
 (elem (i32.const 1) $__cxx_global_array_dtor)
 (func $__cxx_global_array_dtor (param $0 i32)
  (drop
   (call $Foo::~Foo\28\29
    (i32.const 1040)
   )
  )
 )
```

But because the application was built with `-s EXIT_RUNTIME=0`, is would be known at compilation time that none of that code will ever execute!

In practice we find that there is a lot of dead code that gets pulled in to our builds from this cause. In my toybox 2D game, this is currently the single biggest source of dead code (granted, the test game is a micro-sized test, but still a full game).

Would it be possible to optimize this in LLVM or Binaryen by making them aware of an app that will not quit with `-s EXIT_RUNTIME=0`, destructors for all global data can be omitted?

**Comment by juj** [comment]
(worth noting that `-s EXIT_RUNTIME=0` is currently our default build option already)

**Comment by kripken** [comment]
I think what's going on here is that we remove `atexit` calls if we know we won't exit. However, we do this pretty late, after LLVM is finished, in a binaryen pass - and at that point the called function is in the table. We can't remove it from there, so it sticks around.

Probably this should be done in LLVM somehow. Alternatively, if binaryen can tell what is a global dtor, it could remove it - looks like it's named `__cxx_global_array_dtor` in this output, but not sure we can rely on that. But, @tlively has been thinking about optimization metadata for wasm files, and maybe that could include info about being a global destructor? That would be enough.

**Comment by sbc100** [comment]
Sounds like this might need to be a codegen option?  So we can avoid registering the destructors in the first place?  

Also, does `EXIT_RUNTIME=0` mean that the runtime can never exit, or that it doesn't exit automatically when main returns?  We should probably specific because if its that later we could have users who depend on this.

**Comment by kripken** [comment]
The flag has always meant we never exit. It's basically the setting you want for a library/reactor. We defaulted to it in emscripten because it was the common use case + it's smaller.

**Comment by juj** [comment]
I now notice that what is likely keeping those functions alive is that they are all added by function pointer to the function table, e.g.

```
(elem (i32.const 1) $__cxx_global_array_dtor $__cxx_global_array_dtor.11 $__cxx_global_array_dtor.13 $__cxx_global_array_dtor.15 $__cxx_global_array_dtor.17 $__cxx_global_array_dtor.19 $__cxx_global_array_dtor.21 $__cxx_global_array_dtor.23 $__cxx_global_array_dtor.25 $__cxx_global_array_dtor.27 $__cxx_global_array_dtor.29 ...
```
(which would definitely be how they are made known to `atexit`)

> Also, does `EXIT_RUNTIME=0` mean that the runtime can never exit,

Yeah, if we build with `-s EXIT_RUNTIME=0`, we do not emit any code to quit the runtime, so it is not possible to even to manually quit.

**Comment by juj** [comment]
Oh wow, there does already exist a Clang flag `-fno-c++-static-destructors`, confirmed that it works to avoid emitting any of these `__cxx_global_array_dtor`s!

First thought was that we should make `-s NO_EXIT_RUNTIME=1`/`-s EXIT_RUNTIME=0` always imply `-fno-c++-static-destructors`, and add that to the Clang build line. However so far `-s NO_EXIT_RUNTIME=1` has been a link-time-only setting, and it is not something that one'd pass at object compile time.

Testing out, it looks like if I only pass `-fno-c++-static-destructors` to final link, and not to intermediate object compile steps, then it is too late, and the `__cxx_global_array_dtor`s will still be present. I have to pass `-fno-c++-static-destructors` to at least to the compile steps, then it works. (not sure if link time will need that, probably not).

Not sure how we could carry this optimization over. Change and document that `-s EXIT_RUNTIME=0` is now a compile+link flag, and have it imply `-fno-c++-static-destructors`?

**Comment by sbc100** [comment]
I see two options:

1. As you say, build everything we `-fno-c++-static-destructors`. 
    Pros: 
      Builds on standard clang feature that already does what we want. 
    Cons: 
      Requires passing flags to all C compiles.  
      Only works for C++, not `__attribute__((desctructor))` in C)?
      Possibly needing to maintaining an extra variant of libc++/libc++abi (do they have any static destructors in it?

2. Make the post-link optimizer tools (binaryen I guess) aware of __cxa_exit and how to eliminate any calls to it and cleanup DCE functions the were only included for that purpose.
    Pros:
       Doesn't require rebuilding any libraries of passing any extra compile flags
    Cons: 
       Could be pretty tricky.  How can we know its safe to remove the function address from the table?

**Comment by kripken** [comment]
> Change and document that -s EXIT_RUNTIME=0 is now a compile+link flag, and have it imply -fno-c++-static-destructors?

I think that's a good idea.

> Possibly needing to maintaining an extra variant of libc++/libc++abi (do they have any static destructors in it?

Sadly I think the iostream constructor does flushing in its destructor. But I guess if you use iostream, you expect overhead...
