### ISSUE TITLE
how can i fallback js when wasm not support

### ISSUE THREAD

**Issue by sanriqing** [emscripten-core/emscripten#11134]
There seems to be no compatible code when `wasm=2` . 
i find some issue 
1. [Run wasm2js if wasm fails #10621](https://github.com/emscripten-core/emscripten/pull/10621)
2. [JS fallback when Wasm is not supported #10118 ](https://github.com/emscripten-core/emscripten/pull/10118)

but all of them are not  master.

i want to know how to fallback js when   WebAssembly is no defined with master code

**Comment by kripken** [comment]
cc @juj for the status of the 1st PR there which is still open.

**Comment by juj** [comment]
Rebased the PR to latest, and dropped a comment. Would love to take the PR forward, but not quite sure how to do it cleanly without the page reload.
