### ISSUE TITLE
support C++17 std::optional in Embind

### ISSUE THREAD

**Issue by skonstant** [emscripten-core/emscripten#11139]
I would find it useful to allow class properties and method parameters to be optional, like in WebIDL.

I use std::optional a lot and that would seem like a natural thing do. As this is taken care of in WebIDL

something like this:

template<typename OptionalType>
struct OptionalAccess {
    static emscripten::val value(
            const OptionalType& v) {
        return emscripten::val(v.value());
    }

    static bool has_value(OptionalType& v) {
        return v.has_value();
    }
};

template<typename V>
emscripten::class_<std::optional<V>> register_optional(const char* name) {
    typedef std::optional<V> OptionalType;

    return emscripten::class_<std::optional<V>>(name)
            .function("value", &OptionalAccess<OptionalType>::value)
            .function("has_value", &OptionalAccess<OptionalType>::has_value);
}

but it's cumbersome to register a new optional type, can we not have something generic?

**Comment by skonstant** [comment]
Any progress on this?

I have done Typescript "bindings" for this now:

`export abstract class Optional<T> {
    has_value(): boolean;
    value(): T;
    delete();
  }`

and

`export class OptionalString extends Optional<string> {}`

But again it is pretty poor, it would be much better to have undefined or null or the value, this way we could use it as falsy.

**Comment by mrroohian** [comment]
For anyone still interested I've a workaround here: https://github.com/emscripten-core/emscripten/issues/20082#issuecomment-1686907931

**Comment by brendandahl** [comment]
Fixed by #21076
