### ISSUE TITLE
Single instruction intrinsic to cause a wasm trap?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#11141]
When an application should crash, we want to abort execution. Currently this can be done from within wasm e.g. with a

```c
emscripten_throw_string("abort!");
```

However for release builds it is desirable to optimize the code size of such aborts, which would otherwise be quite large. In some cases we just optimize away any aborting code and truck through, but it can be very hard to diagnose errors afterwards.

That leads me to ponder what is the shortest instruction sequence in wasm that would cause a trap? I tried creating something like the following

```
inline void __attribute__((optnone, always_inline)) emscripten_wasm_trap()
{
  0/0;
}
```
but that does not quite work, for some reason even in debug builds there are no warnings issued, and the compiler does not generate the division.

Would it be possible to add e.g. in binaryen a direct intrinsic that could be used to emit the shortest possible wasm opcode sequence that will cause a trap? Then release code could ifdef to `emscripten_wasm_trap();` to get that shortest possible "abort here" instruction generated?

Integer divide by zero seems like the shortest way to achieve that?

**Comment by kripken** [comment]
I think what you're looking for is `__builtin_trap()`? That compiles down to a single `unreachable` instruction (one byte).

**Comment by juj** [comment]
Hmm, I was eyeing that `unreachable` instruction, and was thinking that it is treated the same way as LLVM `__builtin_unreachable()`, which is used for reachability deduction and size optimization. That is, any linear/branchless path that will lead to an `unreachable` would also be understood to be unreachable, hence LLVM will all such code away, and immediately call `unreachable`?

If `__builtin_trap()` emits an unreachable, will it be guaranteed to emit that instruction so "late" that its semantics will be different? E.g. if I do

```c++
int main()
{
   emscripten_console_log("hello!");
   __builtin_trap();
}
```
will there be a strong guarantee that a call to console log will always be preserved under optimizations?

**Comment by kripken** [comment]
I'm not an expert on this, but I believe that is exactly the difference with `__builtin_unreachable`, see the gcc docs for example: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

I.e. trap aborts execution, unreachable marks as unreachable. Sadly wasm's trap is called "unreachable" which adds confusion, but it's a trap... not sure why we renamed it that way, honestly.
