### ISSUE TITLE
libcxxabi depends on printf formatting (+6KB, ~4.6% overhead)

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#11142]
Surprisingly, the following program depends on `printf`:

```c++
class Foo
{
public:
	Foo()
	:counter(5)
	{

	}

	int counter;
};

int testfunc()
{
	static Foo foo;
	return ++foo.counter;
}

int main()
{
	testfunc();
}
```

This is because static initialization of `static Foo foo` will inject dependencies to `cxa_guard_acquire()` and `cxa_guard_release()`, which will have dependencies to cxxabi `abort_message`, which is

```c++
_LIBCXXABI_HIDDEN _LIBCXXABI_NORETURN void
abort_message(const char *format, ...) __attribute__((format(printf, 1, 2)));
```

This will then in turn bring in the full dependency to printf, which is pretty large.

cxxabi has two aborts: `ABORT()` and this printf depending `ABORT_WITH_MESSAGE()`.

It would be great to turn these both in e.g. >= `-O2` and >= `-Os` release builds to instead emit the `emscripten_wasm_trap()` instruction instead (#11141) for minimal code size, and only in debug builds have all the large code size requiring calls.

**Comment by sbc100** [comment]
Hmm this sounds familiar.  I think in the past we've don't something to avoid bring thing, at least I remember messing with `ABORT_WITH_MESSAGE` in the past.

Definitely worth fixing.   If this turns out to be a regression we need to look at why our metasdce and other codesize tests didn't catch it.

**Comment by kripken** [comment]
I'm taking a look. I also remember we did something for something related, but yeah, looks like it doens't help here.

**Comment by kripken** [comment]
I think the related thing I was remembering was avoiding printing demangled stack traces (which is indeed unrelated). I don't see anything else in the log atm.
