### ISSUE TITLE
int64_t in C++ results in UnboundTypeError

### ISSUE THREAD

**Issue by skonstant** [emscripten-core/emscripten#11140]
If I pass a property to embind that has type int64_t, which seems to hit this in alltypes.h

#if defined(__NEED_int64_t) && !defined(__DEFINED_int64_t)
typedef _Int64          int64_t;

I get  an UnboundTypeError exception when trying to read it in Javascript.

This is particularly problematic for passing timestamps, I use std::chrono::system_clock::time_point everywhere and since we do not have binding for Javascript date <-> std::chrono::system_clock::time_point yet, I would like to pass milliseconds at least, so I wrote this:

`emscripten::val toJsDate(std::chrono::system_clock::time_point timePoint) {
    return emscripten::val(
            (std::chrono::duration_cast<std::chrono::milliseconds>(timePoint.time_since_epoch())).count());
}`

And

`  emscripten::class_<std::chrono::system_clock::time_point>("TimePoint")
            .function("ms", &toJsDate);`

I get an exception and if I cast to long, I get a truncated value. I can pass seconds but that massively loses precision.

**Comment by brion** [comment]
I don't believe there's currently a mapping for `int64_t` to JS in embind by default. (BigInt would work on browsers that support it, but not on those where it doesn't, and afaik this work hasn't been done yet on the embind side.)

Your best bet is probably to convert to a `double`, which maps directly to JavaScript `number`. This will pass through 53 bits of integer precision; if you need more bits you'll have to do some manual mapping by splitting it to multiple words or a string or something.

**Comment by skonstant** [comment]
Thank you brion, I can try double then.

**Comment by Chris00** [comment]
See [JavaScript BigInt to WebAssembly i64 integration](https://github.com/WebAssembly/proposals/issues/7).
