### ISSUE TITLE
Unused POSIXism leaks into compiled apps (+3KB, ~+2.3% overhead)

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#11148]
In an application that does not use any of POSIX environment code ([setenv, getenv, environ, etc.](https://www.gnu.org/software/libc/manual/html_node/Environment-Access.html)), and does not use the MEMFS filesystem or WASI, the following code creeps into the build:

Wasm side:
```wast
 (import "a" "Eb" (func $__wasi_environ_sizes_get (param i32 i32) (result i32)))
 (import "a" "Fb" (func $__wasi_environ_get (param i32 i32) (result i32)))

 (func $__wasm_call_ctors
  (call $initialize_malloc_heap\28\29)
  (call $__emscripten_environ_constructor)
  ...
)

 (func $__emscripten_environ_constructor
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (global.set $global$0
   (local.tee $0
    (i32.sub
     (global.get $global$0)
     (i32.const 16)
    )
   )
  )
  (block $label$1
   (br_if $label$1
    (call $__wasi_environ_sizes_get
     (i32.add
      (local.get $0)
      (i32.const 12)
     )
     (i32.add
      (local.get $0)
      (i32.const 8)
     )
    )
   )
   (i32.store
    (i32.const 282472)
    (local.tee $1
     (call $emmalloc_memalign
      (i32.add
       (i32.shl
        (i32.load offset=12
         (local.get $0)
        )
        (i32.const 2)
       )
       (i32.const 4)
      )
     )
    )
   )
   (br_if $label$1
    (i32.eqz
     (local.get $1)
    )
   )
   (block $label$2
    (if
     (local.tee $1
      (call $emmalloc_memalign
       (i32.load offset=8
        (local.get $0)
       )
      )
     )
     (br_if $label$2
      (local.tee $2
       (i32.load
        (i32.const 282472)
       )
      )
     )
    )
    (i32.store
     (i32.const 282472)
     (i32.const 0)
    )
    (br $label$1)
   )
   (i32.store
    (i32.add
     (local.get $2)
     (i32.shl
      (i32.load offset=12
       (local.get $0)
      )
      (i32.const 2)
     )
    )
    (i32.const 0)
   )
   (br_if $label$1
    (i32.eqz
     (call $__wasi_environ_get
      (i32.load
       (i32.const 282472)
      )
      (local.get $1)
     )
    )
   )
   (i32.store
    (i32.const 282472)
    (i32.const 0)
   )
  )
  (global.set $global$0
   (i32.add
    (local.get $0)
    (i32.const 16)
   )
  )
 )
```

JS side:

```js
var ENV = {};

function __getExecutableName() {
    return "./this.program"
}

function getEnvStrings() {
    if (!getEnvStrings.strings) {
        var env = {
            "USER": "web_user",
            "LOGNAME": "web_user",
            "PATH": "/",
            "PWD": "/",
            "HOME": "/home/web_user",
            "LANG": (typeof navigator === "object" && navigator.languages && navigator.languages[0] || "C").replace("-", "_") + ".UTF-8",
            "_": __getExecutableName()
        };
        for (var x in ENV) {
            env[x] = ENV[x]
        }
        var strings = [];
        for (var x in env) {
            strings.push(x + "=" + env[x])
        }
        getEnvStrings.strings = strings
    }
    return getEnvStrings.strings
}

function _environ_get(__environ, environ_buf) {
    var bufSize = 0;
    getEnvStrings().forEach(function(string, i) {
        var ptr = environ_buf + bufSize;
        HEAP32[__environ + i * 4 >> 2] = ptr;
        writeAsciiToMemory(string, ptr);
        bufSize += string.length + 1
    });
    return 0
}

function _environ_sizes_get(penviron_count, penviron_buf_size) {
    var strings = getEnvStrings();
    HEAP32[penviron_count >> 2] = strings.length;
    var bufSize = 0;
    strings.forEach(function(string) {
        bufSize += string.length + 1
    });
    HEAP32[penviron_buf_size >> 2] = bufSize;
    return 0
}
```

that comes from `__environ.c`:

```c
#ifdef __EMSCRIPTEN__
__attribute__((constructor(100))) // construct this before user code
void __emscripten_environ_constructor(void) {
    size_t environ_count;
    size_t environ_buf_size;
    __wasi_errno_t err = __wasi_environ_sizes_get(&environ_count,
                                                  &environ_buf_size);
    if (err != __WASI_ERRNO_SUCCESS) {
        return;
    }

    __environ = malloc(sizeof(char *) * (environ_count + 1));
    if (__environ == 0) {
        return;
    }
    char *environ_buf = malloc(sizeof(char) * environ_buf_size);
    if (__environ == 0 || environ_buf == 0) {
        __environ = 0;
        return;
    }

    // Ensure null termination.
    __environ[environ_count] = 0;

    err = __wasi_environ_get((uint8_t**)__environ, environ_buf);
    if (err != __WASI_ERRNO_SUCCESS) {
        __environ = 0;
    }
}
#endif
```
This constitutes ~3KB, or about +2.3% of the total application size.

I wonder what is the machinery that is pulling this in? Iiuc LLVM treats `constructor` functions as something un-DCEable (for a reason), and `system_libs.py` has this for `libc`:
```py
    if shared.Settings.WASM_BACKEND:
      # See libc_extras below
      # Include all the getenv stuff with the wasm backend. With fastcomp we
      # still use JS because libc is a .bc file and we don't want to have a
      # global constructor there for __environ, which would mean it is always
      # included.
      libc_files += files_in_path(
          path_components=['system', 'lib', 'libc', 'musl', 'src', 'env'],
          filenames=['__environ.c', 'getenv.c', 'putenv.c', 'setenv.c', 'unsetenv.c'])
```

That looks like whenever using a) Wasm backend, and b) any symbol that will link in libc, then the 3KB of environment and the related WASI code overhead will creep in(?)

Not sure what would be the best way to avoid this, except to add a `-s POSIX_ENVIRON_SUPPORT=0` linker flag?

**Comment by sbc100** [comment]
Could you include the input source and the command line you used to build the program? 

I wonder is this something that is occurring in STANDALONE_WASM mode?

**Comment by juj** [comment]
Unfortunately this happens in a larger application. But the application does not have any references to environment related code, i.e. it builds clean with this PR and `-s SUPPORT_POSIX_ENV=0`.

**Comment by juj** [comment]
The link flags that are being used are
```
-std=c++11 -fno-exceptions -fno-rtti -s DISABLE_EXCEPTION_CATCHING=1 -Wall -Wextra -Wno-long-long -Wno-variadic-macros -O3 -ffast-math -flto -s WARN_ON_UNDEFINED_SYMBOLS=1 -s MINIMAL_RUNTIME=2 -s ENVIRONMENT=web -s TEXTDECODER=1 -s ABORTING_MALLOC=1 -s SUPPORT_ERRNO=0 -s MALLOC=emmalloc -s SUPPORT_POSIX_ENV=0 -s GL_EMULATE_GLES_VERSION_STRING_FORMAT=0 -s GL_EXTENSIONS_IN_PREFIXED_FORMAT=0 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 -s GL_TRACK_ERRORS=0 -s GL_SUPPORT_EXPLICIT_SWAP_CONTROL=0 --output_eol linux -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 --profiling-funcs -s ASMFS=1 -s FETCH=1 -s FETCH_SUPPORT_INDEXEDDB=0 -s TOTAL_STACK=64KB -s TOTAL_MEMORY=16MB --emit-symbol-map -s NO_EXIT_RUNTIME=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s MAX_WEBGL_VERSION=2
```

**Comment by sbc100** [comment]
Can you figure out why the `__envrion.o` object is being included in your link?  It should only be included in demand.  Thats is how it is supposed to work anyway.
 
Maybe you can try using `-Wl,--trace-symbol=xxx` ,   perhaps  `-Wl,--trace-symbol=__environ` will help?    

The strange thing is that if your program really did depend on `__environ` then we could expect that adding SUPPORT_POSIX_ENV would cause a link error.

Maybe `-flto` might be a clue?  Does the envrion code still get included when you run without `-flto`?

**Comment by juj** [comment]
With `-Wl,--trace-symbol=__environ` I get:

```
/Users/clb/emsdk/emscripten/master/cache/wasm-lto/libc.a: lazy definition of __environ
/Users/clb/emsdk/emscripten/master/cache/wasm-lto/libc.a(getenv.o): reference to __environ
/Users/clb/emsdk/emscripten/master/cache/wasm-lto/libc.a(__environ.o): definition of __environ
```
If I drop `-flto`, I get
```
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a: lazy definition of __environ
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(getenv.o): reference to __environ
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(__environ.o): definition of __environ
```
and the environment stuff remains.

There are no references to any environment related code, `__environ`, or `getenv()` in the codebase, double-checked and triple-checked that it has no hits.

If I do `-Wl,--trace-symbol=getenv` I get

```
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a: lazy definition of getenv
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(locale_map.o): reference to getenv
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(getenv.o): definition of getenv
```

that suggests perhaps something in locale_map, but there no locale-specific code being used in the program either. (in particular, no `__get_locale`)

**Comment by sbc100** [comment]
Right .. it looks like `locale_map.o` is the problem here.

Still a mystery as to how you don't get undefined references to `getenv` when you build with `SUPPORT_POSIX_ENV`?     The only explanation is can think of is that some other version of getenv is being included when you set `SUPPORT_POSIX_ENV`.

What does `-Wl,--trace-symbol=getenv` show when `SUPPORT_POSIX_ENV` is enabled?

**Comment by juj** [comment]
> What does `-Wl,--trace-symbol=getenv` show when `SUPPORT_POSIX_ENV` is enabled?

It shows 

```
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a: lazy definition of getenv
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(locale_map.o): reference to getenv
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(getenv.o): definition of getenv
```
like shown above - that was built in master branch without SUPPORT_POSIX_ENV in the tree.

**Comment by sbc100** [comment]
Sorry I mean `SUPPORT_POSIX_ENV=0` where does locale_map end up getting its `getenv` from in that case?

**Comment by juj** [comment]
If I build with `-s SUPPORT_POSIX_ENV=0`, and add tracing for `getlocale`, `setlocale`, `__get_locale` and `__environ`, I get

```
[ 98%] Linking CXX executable bin/Cards/Cards.html
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/Cards.dir/link.txt --verbose=1
/Users/clb/emsdk/emscripten/master/em++   -DLOGGING_SUPPORT_DISABLED -std=c++11 -DGFXAPI_USE_WASM=1 -fno-exceptions -fno-rtti -s DISABLE_EXCEPTION_CATCHING=1 -Wall -Wextra -Wno-long-long -Wno-variadic-macros -DNDEBUG -O2 -DRELEASE -DNDEBUG -DOPTIMIZED_RELEASE -O3 -ffast-math -DMATH_ENABLE_INSECURE_OPTIMIZATIONS -DNDEBUG -DMATH_SILENT_ASSUME -DRELEASE -DOPTIMIZED_RELEASE   -s WARN_ON_UNDEFINED_SYMBOLS=1 -s MINIFY_HTML=0 -s WORKAROUND_IOS_9_RIGHT_SHIFT_BUG=1 -s MINIMAL_RUNTIME=2 -s ENVIRONMENT=web -s TEXTDECODER=1 -s ABORTING_MALLOC=1 -s SUPPORT_ERRNO=0 -s MALLOC=emmalloc -s SUPPORT_POSIX_ENV=0 -Wl,--trace-symbol=getlocale -Wl,--trace-symbol=setlocale -Wl,--trace-symbol=__get_locale -Wl,--trace-symbol=__environ -s GL_EMULATE_GLES_VERSION_STRING_FORMAT=0 -s GL_EXTENSIONS_IN_PREFIXED_FORMAT=0 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 -s GL_TRACK_ERRORS=0 -s GL_SUPPORT_EXPLICIT_SWAP_CONTROL=0 --output_eol linux -s ERROR_ON_UNDEFINED_SYMBOLS=1 -fno-exceptions -fno-rtti -s DISABLE_EXCEPTION_CATCHING=1 -O2 -O3 -ffast-math -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1  --profiling-funcs -s ASMFS=1 -s FETCH=1 -s FETCH_SUPPORT_INDEXEDDB=0 -s TOTAL_STACK=64KB -s TOTAL_MEMORY=16MB --emit-symbol-map -s NO_EXIT_RUNTIME=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s MAX_WEBGL_VERSION=2 -lwebgl.js --shell-file /Users/clb/code/emcc_cards/Cards_shell_template.html --js-library "/Users/clb/code/Samples/Cards/library_cards.js" @CMakeFiles/Cards.dir/objects1.rsp  -o bin/Cards/Cards.html @CMakeFiles/Cards.dir/linklibs.rsp
em++: warning: for wasm there is no need to set ELIMINATE_DUPLICATE_FUNCTIONS, the binaryen optimizer does it automatically [-Wemcc]
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a: lazy definition of setlocale
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a: lazy definition of __get_locale
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(newlocale.o): reference to __get_locale
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(locale_map.o): definition of __get_locale
/Users/clb/emsdk/emscripten/master/cache/wasm/libc++-noexcept.a(locale.o): reference to setlocale
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(setlocale.o): definition of setlocale
/Users/clb/emsdk/emscripten/master/cache/wasm/libc.a(setlocale.o): reference to __get_locale
[100%] Built target Cards
```

**Comment by juj** [comment]
In that case, it looks like no hits for `__environ` (as one would expect), hence calling `__get_locale` would error out on `__environ` being missing.. but `__get_locale` is not being used in the program either, so that should be ok.

**Comment by sbc100** [comment]
What about `getenv` which is needed by `__get_locale`.  Where is it getting that from? 

Is it coming from JS or some other native code object?


As an aside,  `__get_locale` does seem to be included in your program, otherwise I think you would not see the `definition of __get_locale`.. you would only see the lazy definition.   Lazy defintiion means part of a library.. once you see the actual definition in the object file, that means the linker decided it needed that object file.

**Comment by juj** [comment]
If I disassemble the generated wasm file, there are no references to `__get_locale`, `getlocale`, `setlocale`, `__environ`, `getenv`, `setenv`, or anything else related. These are all local definitions and chains of references inside libc, that are not referenced by the built program.

If I edit `system/lib/libc/musl/src/locale/locale_map.c` and delete `__get_locale`, then `emcc --clear-cache`, and then relink the program, the program builds just fine without any missing code.

**Comment by sbc100** [comment]
I'm still curious what `-Wl,--trace-symbol=getenv` says with `SUPPORT_POSIX_ENV=0`?    It seems like we would need someone to define this symbol.

Sorry for all this back and forth.  If we could find a repro case I'd love to be able to take a closer look.  What we are looking for a program that seemingly *doesn't* use environment variables, but *does* link in this constructor, right?   I'll see if I can repo this with a few simple programs.

**Comment by sbc100** [comment]
I'm also curious about what happens if you build with `LLD_REPORT_UNDEFINED=1` in the `SUPPORT_POSIX_ENV=0` case, is wasm-ld happy?

**Comment by juj** [comment]
Ops, posted in the wrong thread: the two comments in https://github.com/emscripten-core/emscripten/pull/11149#issuecomment-628261140 were supposed to be posted to this thread.

**Comment by juj** [comment]
In summary, it looks like something that uses STL, but gets optimized away, but optimizer is not able to reason about optimizing away the constructor.

**Comment by sbc100** [comment]
I don't think any of the post-link tools that we run can remove the static constructors (other than maybe eval-ctors, which that is kind of different).

I believe that the only way to not include the static constructor is for the linker to not include it.   If the linker decides its needed we are kind of stuck with it.  

We should try to build a test case so we can understand this better and try to find a solution.
