### ISSUE TITLE
How to output html using emcmake + emmake

### ISSUE THREAD

**Issue by GameOverture** [emscripten-core/emscripten#11154]
For my project using cmake I use the following:
```
emcmake cmake -DHYBUILD_Emscripten=ON ..
emmake make
```
Which outputs `NewGame.data NewGame.js NewGame.wasm`

However I'm trying to use the -o option to specify generating a html file. My CMakeLists.txt is the following. It properly does the `--preload-file ../data` part in the `set_target_properties(LINK_FLAGS)` command.

```
cmake_minimum_required(VERSION 3.10)
project(NewGame VERSION 1.0)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

option(HYBUILD_Emscripten "Build game for web browsers" OFF)

add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../HarmonyEngine/Engine" "Engine")

set(HY_SRCFILES
	"src/pch.h"
	"src/main.cpp"
	"src/NewGame.cpp"
	"src/NewGame.h"
	"NewGame.hyproj")

add_executable(NewGame ${HY_SRCFILES})
set_target_properties(NewGame PROPERTIES
	CXX_STANDARD 14
	CXX_STANDARD_REQUIRED YES
	CXX_EXTENSIONS NO)

target_include_directories(NewGame PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../HarmonyEngine/Engine/include")
target_include_directories(NewGame PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../HarmonyEngine/Engine/external/box2d/include")
target_include_directories(NewGame PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../HarmonyEngine/Engine/external/glad/include")
target_include_directories(NewGame PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../HarmonyEngine/Engine/external/soil2/include")

if(HYBUILD_Emscripten)
	target_compile_definitions(NewGame PRIVATE HY_CONFIG_EMSCRIPTEN)
	set_target_properties(NewGame PROPERTIES LINK_FLAGS "-o index.html --preload-file ../data")
else()
	target_include_directories(NewGame PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/../HarmonyEngine/Engine/external/glfw/include")
	target_precompile_headers(NewGame PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src/pch.h")
endif()

target_link_libraries(NewGame PUBLIC HyEngine)

if (MSVC)
	set_property(TARGET NewGame PROPERTY VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
	set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT NewGame)
endif()

```

**Comment by GameOverture** [comment]
@azakai on Discord helped me with the solution

Adding this to the CMakeLists.txt worked
`set(CMAKE_EXECUTABLE_SUFFIX ".html")`

**Comment by realExant** [comment]
Don't use set(CMAKE_EXECUTABLE_SUFFIX ".html")
Change 'add_executable' to 'qt_add_executable' in the CMakeLists.txt.

**Comment by sbc100** [comment]
@robtaylor

**Comment by starball5** [comment]
Note that if you don't want to modify a CMakeLists.txt, you can set `CMAKE_EXECUTABLE_SUFFIX` as a cache variable in the configuration command using [`-D`](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-D). But if the project _does_ set `CMAKE_EXECUTABLE_SUFFIX` without checking for it to already be set, and it doesn't also set it as a cache variable, then the project's definition will clobber the commandline one.

**Comment by gblikas** [comment]
Just chiming in here...  

Setting [`CMAKE_EXECUTABLE_SUFFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_EXECUTABLE_SUFFIX.html) works just fine, but we override the line the toolchain file, https://github.com/emscripten-core/emscripten/blob/ea35c8cde53d4691504436300493d60b49ff3744/cmake/Modules/Platform/Emscripten.cmake#L273

From my memory, CMake usually recommends end-users (not toolchain developers) not to mess with `CMAKE_*` variables, when possible. 

**A reason for adding .html**

@sbc100 In my CMakeLists.txt file and workflow, I'm building to WASM and I do use `set(CMAKE_EXECUTABLE_SUFFIX .html)`. This generates 3 files for me: `foo.html`, `foo.js` and `foo.wasm`. With this in mind, perhaps  https://github.com/emscripten-core/emscripten/blob/ea35c8cde53d4691504436300493d60b49ff3744/cmake/Modules/Platform/Emscripten.cmake#L273 could be made more generic by setting `CMAKE_EXECUTABLE_SUFFIX` to `.html` as well? 

At the tradeoff of an additional file (perhaps substantial build times), this would allow developers to easily test the barebones in browser, giving a good indication of runtime. 

**A reason against .html**

Perhaps leaving it as is is best. A program cross-compiling and then running in the browser via HTML is on a case-by-case basis; how would the Emscripten project know the program to be used, e.g. UI design?... It's nice that we have the ability to generate a testable `.html` file, but at the end of the day, we should probably be writing our own `.html` test scripts that apropriately load data and do the interactions of our `.js`.

**Comment by starball5** [comment]
> From my memory, CMake usually recommends end-users (not toolchain developers) not to mess with CMAKE_* variables, when possible.

@gblikas that's not true. There are even variables that are explicitly suggested to be left for the "user" to define instead of being set by projects.

Aside: semi-related: #18860

**Comment by sbc100** [comment]
> Just chiming in here...
> 
> Setting [`CMAKE_EXECUTABLE_SUFFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_EXECUTABLE_SUFFIX.html) works just fine, but we override the line the toolchain file,
> 
> https://github.com/emscripten-core/emscripten/blob/ea35c8cde53d4691504436300493d60b49ff3744/cmake/Modules/Platform/Emscripten.cmake#L273
> 
> From my memory, CMake usually recommends end-users (not toolchain developers) not to mess with `CMAKE_*` variables, when possible.

As @starball5 points out this is not true.   Think `CMAKE_CXX_FLAGS`, for example.

> 
> **A reason for adding .html**
> 
> @sbc100 In my CMakeLists.txt file and workflow, I'm building to WASM and I do use `set(CMAKE_EXECUTABLE_SUFFIX .html)`. This generates 3 files for me: `foo.html`, `foo.js` and `foo.wasm`. With this in mind, perhaps
> 
> https://github.com/emscripten-core/emscripten/blob/ea35c8cde53d4691504436300493d60b49ff3744/cmake/Modules/Platform/Emscripten.cmake#L273
> 
> could be made more generic by setting `CMAKE_EXECUTABLE_SUFFIX` to `.html` as well?
> At the tradeoff of an additional file (perhaps substantial build times), this would allow developers to easily test the barebones in browser, giving a good indication of runtime; this has been very very helpful to me (and I'm sure other developers).
> 
> **A reason against .html**
> 
> A program cross-compiling and then running in the browser via HTML is on a case-by-case basis; how would the Emscripten project know the program to be used, e.g. UI design?... It's nice that we have the ability to generate a testable `.html` file, but at the end of the day, we should probably be writing our own `.html` test scripts that apropriately load data and do the interactions of our `.js`.

I think the reasons against are stronger here.  Users can opt into html if they want to.

**Comment by sbc100** [comment]
I think we can close this since `CMAKE_EXECUTABLE_SUFFIX` seems like the right answer.

**Comment by starball5** [comment]
(and also the `SUFFIX` target property).

**Comment by gblikas** [comment]
> > From my memory, CMake usually recommends end-users (not toolchain developers) not to mess with CMAKE_* variables, when possible.
> 
> @gblikas that's not true. There are even variables that are explicitly suggested to be left for the "user" to define instead of being set by projects.
> 
> Aside: semi-related: #18860

@starball5  I believe `add_compile_options` is the preferred single-project solution.

**Comment by githubuser6000** [comment]
I just bumped into this today. The proposed solution did not work for me on cmake 3.30 and custom clang build. 

As mentioned before, per-target `SUFFIX` can be set ([cmake docs](https://cmake.org/cmake/help/latest/prop_tgt/SUFFIX.html)). This is much better than having to set this globally. 

```
add_executable(main ...)
set_target_properties(main PROPERTIES SUFFIX ".html")
```

I assume the "right" way is to author a html and js file to load the generated wasm file which makes sense for bigger projects, but having this available would really help out with getting started and testing.

**Comment by starball5** [comment]
At least for the issue at hand in this ticket, I'd suggest users to use the `SUFFIX` target property, unless in context of the user's CMake project, there's no fear of defaulting `SUFFIX` for anything unintended, or that's acceptable to set a default and set everything else specifically.
