### ISSUE TITLE
How to add EM_JS into importObject of WebAssembly.instantiate?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11168]
I complied C++ code this way ,

`emcc entry.cpp -s WASM=1 -o entry.wasm
`

Then imported it on Javascript as follows,

```
let importObject = {}

fetch(chrome.runtime.getURL("entry.wasm")).then(response =>
    response.arrayBuffer()
  ).then(bytes =>
    WebAssembly.instantiate(bytes, importObject)
  ).then(results => {
    // Do something with the results!
});
```

However, It's required to put arguments into importObject but I have no clue what should I put.  I've spent 4 hours Googling various resources but nowhere to find plain English definition other than bunch of hello world examples with memory import. 

I need to know what are the necessary arguments for this object in order to EM_JS function.

The code works fine if I compile with EMScripten to output HTML but I'm looking to use my WASM code in production. I don't want to display scary terminal (The one in EMScripten HTML) front of my users.

**Comment by gerald-dotcom** [comment]
I found an example here

https://codepen.io/Gee2Cee/pen/eaNewE

Which use that JS file generated by EM so it's obvious that this JS file used as a run-time or sort of

Now the question would be, how does one build multiple wasm modules and use this runtime? 

Does each module need it own isolated runtime?  or can they share each other? 

I don't know how the integration would looks like

**Comment by curiousdannii** [comment]
You should try the JS output first, just change `entry.wasm` to `entry.js`.

**Comment by gerald-dotcom** [comment]
I was able to use MODULARIZE=1 to export encapsulated code and yes my guesses are correct, each module are using it own run time and I should use JS run time. 

Now time to test this thing. I will update when it work !!

**Comment by gerald-dotcom** [comment]
The code in FAQ not working

await Module.then(m => {
  delete m['then'];
  resolve(m);
});

I'm getting error that Module.then is not a function

**Comment by gerald-dotcom** [comment]
MyCode().then(function(Module) {
  // this is reached when everything is ready, and you can call methods on Module
});

This one appear to be working.

**Comment by sbc100** [comment]
Great!  Can this issue be closed now?

**Comment by gerald-dotcom** [comment]
It appear the code is working but not logging errors. 

Fixed by adding **window.onerror**
```

window.onerror = function(event) {
    return false;
}
```

Issue can be closed now.
