### ISSUE TITLE
Module._malloc argument integer overflow?

### ISSUE THREAD

**Issue by serg06** [emscripten-core/emscripten#11160]
When I try to malloc 2GB at a time, everything works as expected:

```
> size = 2 * 1000 * 1000 * 1000;
2000000000
> Module._malloc(size)
5246680
> Module._malloc(size)
hello4.js:1850 Failed to grow the heap from 2005270528 bytes to 4005298176 bytes, not enough memory!
0
```

But when I try to malloc 40GB at a time, it only allocates 40GB mod 2^32 bytes = 1.34GB:

```
> size = 40 * 1000 * 1000 * 1000;
40000000000
> Module._malloc(size)
5246680
> Module._malloc(size)
hello4.js:1850 Failed to grow the heap from 1350565888 bytes to 2695888896 bytes, not enough memory!
```

And when I try to malloc 20GB at a time, it doesn't allocate anything because 20GB mod 2^32 bytes = 2.8GB which becomes negative since the integer is signed.

```
> size = 20 * 1000 * 1000 * 1000;
20000000000
> Module._malloc(size)
0
```

It seems to me like this is all caused by _malloc taking a 32-bit signed integer which can't hold such large numbers.

**Comment by sbc100** [comment]
As of today, WebAssembly can only operate o 32-bit memory.    There are plans to remove this restriction, but its not going to happen overnight.     What kind of workload to you have the requires such a large working set?

**Comment by sbc100** [comment]
Also, in practice, WebAssembly on the web does not yet allow memories larger than 2Gb .

**Comment by kripken** [comment]
The default limit of memory is 2GB. It's not that the integer is signed, but that you must explicitly opt in to getting more than that. (But only up to 4GB at best as @sbc100 said - memory is 32-bit)

See details here, including the flags to get more than 2GB: https://v8.dev/blog/4gb-wasm-memory
