### ISSUE TITLE
Emscripten not working on Windows

### ISSUE THREAD

**Issue by tripleslash** [emscripten-core/emscripten#11178]
I've installed emscripten as described on the website using the `emsdk install latest`, `emsdk activate latest` and `emsdk_env` commands. So far everything has seemed to work. However when I try to invoke any emscripten command, I'm getting the following errors:

```
> emcmake cmake .

configure: cmake . -DCMAKE_TOOLCHAIN_FILE=C:\Development\SDKs\emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="C:/Development/SDKs/emsdk/node/12.9.1_64bit/bin/node.exe"
Traceback (most recent call last):
  File "C:\Development\SDKs\emsdk\upstream\emscripten\\emcmake.py", line 34, in <module>
    sys.exit(run())
  File "C:\Development\SDKs\emsdk\upstream\emscripten\\emcmake.py", line 27, in run
    shared.Building.configure(sys.argv[1:])
  File "C:\Development\SDKs\emsdk\upstream\emscripten\tools\shared.py", line 1397, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "C:\Development\SDKs\emsdk\upstream\emscripten\tools\shared.py", line 189, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "C:\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by sbc100** [comment]
It looks like the system cannot find the cmake command.    Do you have cmake installed and in your path?

(I think the way to tell on windows is to run `where cmake`)

**Comment by tripleslash** [comment]
Hi @sbc100 thanks for the fast reply.

cmake is indeed installed:

```
cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.
```

**Comment by sbc100** [comment]
Strange.   `tools\shared.py` line 1397 should just running a subproccess with arg0 == 'cmake'.

Can you `print(cmd)` right before  `tools\shared.py` line 1397?

Also can you check cmake is runnable from python by running `python -c "import subprocess; subprocess.call(['cmake'])"`

**Comment by tripleslash** [comment]
I have figured out the problem. The issue was that I've ran the above command from an elevated command prompt. Because it was elevated it ran under the windows admin account and the user path wasn't taken into consideration.

Thanks for the help!

**Comment by ricardoboss** [comment]
I'm having the same problem, the same exact error message, but I'm not running in an elevated shell. It must be something else in my environment. Any ideas?

**Comment by tjaartvanderWalt** [comment]
I had the same issue. My issue was I was using the VSCode terminal. When I run the command in a regular terminal it works as expected.
