### ISSUE TITLE
CMake's target_precompile_headers causes build failures

### ISSUE THREAD

**Issue by gunstarpl** [emscripten-core/emscripten#11172]
Hey,

During porting of my code I've ran into a problem with precompiled headers defined in CMakelists.txt for my project, which causes compilation to fail with following errors for PCH header files generated by CMake:

> FAILED: Source/System/CMakeFiles/System.dir/Debug/cmake_pch.hxx.pch 
C:\Users\Doan\Desktop\emsdk\upstream\emscripten\em++.bat  -DCMAKE_INTDIR=\"Debug\" -IC:/Users/Doan/Desktop/GameEngine/Source/System/../../Include -IC:/Users/Doan/Desktop/GameEngine/Source/Core/../../Include -IC:/Users/Doan/Desktop/GameEngine/Source/Core/../../External/utfcpp-2.3.6/source -IC:/Users/Doan/Desktop/GameEngine/Source/Core/../../External/GLM-0.9.9.3 -IC:/Users/Doan/Desktop/GameEngine/Source/Common/../../Include -IC:/Users/Doan/Desktop/GameEngine/Source/Logger/../../Include -IC:/Users/Doan/Desktop/GameEngine/Source/Logger/../../External/fmt-6.1.2/include -IC:/Users/Doan/Desktop/GameEngine/External/fmt-6.1.2/include -IC:/Users/Doan/Desktop/GameEngine/Source/Event/../../Include -IC:/Users/Doan/Desktop/GameEngine/Source/Reflection/../../Include -IC:/Users/Doan/Desktop/GameEngine/External/glad-0.1.33/include -IC:/Users/Doan/Desktop/GameEngine/External/ImGui-1.62/. -IC:/Users/Doan/Desktop/GameEngine/External/ImGui-1.62/./examples -IC:/Users/Doan/Desktop/GameEngine/Source/Core/../../External/GLEW-2.1.0/include -g   -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_GLFW=3 -s FULL_ES3=1 -std=gnu++17 -Xclang -emit-pch -Xclang -include -Xclang C:/Users/Doan/Desktop/GameEngine-Web/Source/System/CMakeFiles/System.dir/Debug/cmake_pch.hxx -MD -MT Source/System/CMakeFiles/System.dir/Debug/cmake_pch.hxx.pch -MF Source\System\CMakeFiles\System.dir\Debug\cmake_pch.hxx.pch.d -o Source/System/CMakeFiles/System.dir/Debug/cmake_pch.hxx.pch -c Source/System/CMakeFiles/System.dir/cmake_pch.hxx.cxx
em++: error: cannot specify -o with -c/-S and multiple source files

Full example build output can be found here: https://gist.github.com/gunstarpl/3d0d07a3397416abb7268e17279fa9ae

I do not understand what could be wrong with specified arguments seen above. This seems to occur whenever target_precompile_headers() is used (it's a rather new functionality added in CMake 3.16). I have a workaround which involves globally disabling precompiled headers using following cache option, after which everything compiles smoothly (it's not ideal as compilation time takes a hit):
`set(CMAKE_DISABLE_PRECOMPILE_HEADERS ON CACHE BOOL "")`

It's also worth mentioning that I am using toolchain file "emsdk\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake" for cross compilation with Ninja generator and that's pretty much it. I also have CI running with MSVC, GCC 9, Clang 9 and they are not experiencing any similar issues. It's seems unlikely to be an issue with Ninja itself, but I haven't ruled it out completly yet.

If issue does not look like something obvious, I could come up with a minimal CMake example - just let me know!

Thank you for your time!

**Comment by sbc100** [comment]
Hi.  I added that warning but berhaps there is bug ehre.

I think it is generally true that you can't compile with `-c` and `-o` and have multiple input files. gcc and clang both fail in similar ways:

```
$ gcc foo.c bar.c -c -o out.o
gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or ‘-E’ with multiple files
compilation terminated.
```

```
$ clang foo.c bar.c -c -o out.o
clang-10: error: cannot specify -o when generating multiple output files
```

However in your command line I don't actually see multiple inputs so I think it must be false positive.   I will see if I can reproduce.

**Comment by sbc100** [comment]
It looks like we were not correctly recognizing the `-Xclang -include -Xclang foo.h` pattern that cmake seems to be using and mistaking `foo.h` for a file to be compiled (when actually its part of the preceding `-include`.

**Comment by gunstarpl** [comment]
I can confirm that your change does fix the errors for me. PCH files get generated and my build completes successfully with them.

Thank you @sbc100!
