### ISSUE TITLE
Bug in page:Embind - No documentation on selecting an overloaded constructor

### ISSUE THREAD

**Issue by MarkCallow** [emscripten-core/emscripten#11170]
The page says you can select overloaded constructors but *all* the examples are for selecting overloaded methods. Selecting an overloaded constructor is *very* different. It doesn't even use the select_overload keyword. I just wasted about 30 minutes figuring out how to do this, all for the sake of 1 missing line in the documentation.

URL: ../../../docs/porting/connecting_cpp_and_javascript/embind

**Comment by kripken** [comment]
Thanks @MarkCallow , I'd like to fix the docs. I don't know embind that well myself though. Since you've figured this out, can you tell me what the docs should be changed to, or open a PR yourself? Thanks!

**Comment by waywardmonkeys** [comment]
In `tests/embind/embind_test.cpp`, there are these blocks of code that demonstrate the feature:

```
    class_<MultipleCtors>("MultipleCtors")
        .constructor<int>()
        .constructor<int, int>()
        .constructor<int, int, int>()
        .function("WhichCtorCalled", &MultipleCtors::WhichCtorCalled)
        ;

    class_<MultipleSmartCtors>("MultipleSmartCtors")
        .smart_ptr<std::shared_ptr<MultipleSmartCtors>>("shared_ptr<MultipleSmartCtors>")
        .constructor(&std::make_shared<MultipleSmartCtors, int>)
        .constructor(&std::make_shared<MultipleSmartCtors, int, int>)
        .function("WhichCtorCalled", &MultipleSmartCtors::WhichCtorCalled)
        ;
```
