### ISSUE TITLE
Status & Roadblocks for a portable Emscripten

### ISSUE THREAD

**Issue by jeff-hykin** [emscripten-core/emscripten#11175]
## What this issue is about

I hope for this to be an ongoing collaboration/discussion for creating some form of Emscripten with fully bundled dependencies. Portable meaning a flashdrive inserted into an fresh install of any major OS, with no internet connection, could compile C++ to wasm, and wouldn't break with changes to global versions of system packages. Possibly some other people, along with myself, would like to work on this, but we could use help getting started. (A related discussion was here: https://github.com/emscripten-core/emscripten/issues/9313 , however I wanted this issue to include portability outside of a browser context)

In theory, the basic job of Emscripten is a purely functional operation; input of one language output to another language. So (very much in-theory) it is possible for that operation to be done in an OS-independent portable way, and even possibly in a browser using WASM. And to be clear "portable" doesn't mean practical or primary, this isn't about removing dependencies from emscripten-master. A 1 hour compile time requiring 32Gb of RAM for a `hello world.cpp` using an out-of-date emscripten would still count as an initial success despite being extremely less than ideal.

## Work Overview

The main dependencies as I understand them are python, LLVM with clang & wasmId, node.js, binaryen, and the emscripten code itself.

Portability
- [x] emscripten code itself (trivial: can be bundled in a zip)
- [x] node.js runtime can be bundled into an electron app
- [ ] Python; there are many not-quite-100% ports to node.js/browser such as [Pyoide](https://github.com/iodide-project/pyodide), [MicroPython](https://github.com/micropython/micropython/pull/3575), and [skulpt](https://github.com/skulpt/skulpt)
- [ ] LLVM has an alpha-implementation of a WASM version [here](https://github.com/binji/wasm-clang) 
- [ ] binaryen I'm assuming can be treated similar to emscripten, although I do not know for certain

## Questions

Did I misunderstand any of the dependencies: Is cmake optional for Mac/Linux even though they're in the OS pre-reqs? Are LLVM and binaryen downloaded to the local emsdk folder at installation time?

What obvious & non-obvious challenges are there for having emscripten use portable versions of Python and LLVM?

## Current rough plan

Create a `python` command that is actually using node.js and pyodide in order to be portable. Use decorators to catch python system calls and manually run them with the correct ENV variables and portable versions of the executables. Perform something similar for LLVM.

**Comment by sbc100** [comment]
Doesn't emsdk serve the purpose of providing emscripten fully bundled with all its dependencies?    Indeed that seems to be the sole purpose of emsdk.   We could do more (for example, I'll looking an bundling python3 with the macOS version in order to avoid users having to install it themselves).    

Admittedly, emsdk it only supported 3 operating systems.  Do you have specific other platforms you want to run the toolchain on?    Is sounds like you are defining portable as "runs in JavaScript", is that right?  (Not criticizing this definition, just trying to defined what we you asking for here).

We also the the emscripten docker image which packages up even more dependencies and has even fewer system dependencies:  https://hub.docker.com/r/trzeci/emscripten/.

**Comment by jeff-hykin** [comment]
The portable idea, which I probably should clarify, would mean you could put in on a flashdrive and plug & play with most Linux distros, MacOS, and Windows 10. Prebuilt binaries would work, but the eventual goal would be to have emscripten be executable on the client side of a website. Node has prebuilt binaries, and could be an intermediary to reach web-JavaScript, but ideally all dependencies would eventually be compiled to Wasm.

Emscripten, especially with docker, is perfectly easy to setup for most devs. My use case is needing WASM compilation in an app with a non-technical audience that wouldn't be comfortable installing, or even checking a version of python. Beyond that it would be desirable to have the global version of python be independent of the one used by emscripten.

**Comment by juj** [comment]
Emscripten SDK is designed to be portable for flashdrive plug&play use, but unfortunately not "all-in-one" for all OSes in one go. You could get around this by preparing a USB flash drive with different `emsdk_mac/`, `emsdk_win/` and emsdk_linux` directories.

On Windows Emsdk depends operates by bundling python 3, because Windows does not offer a system python installation. On Linux, a system python 3 installation is expected, and on macOS, a a system python 2 installation is expected.

**Comment by jeff-hykin** [comment]
@juj that would work, executables with the same name could be made to appear as a singular command and automatically select which folder to use. The python requirement is the main challenge of this issue. Windows 10 is a problem, Linux might not have python on docker builds, and MacOS won't inlcude python2 in the next update, although starting with Catalina it has Python 3.7.3. Ideally a portable python would be used instead of global installations, however I don't know of non-global python installation for windows. A standalone interpreter has be made for Linux by ScyllaDB, but there doesn't seem to be a windows 10 equivalent. The work they did might possibly be replicated for windows, although it wouldn't be trivial. The standalone interpreter would be much more reliable than the current python-to-javascript execution methods.


How would be best to target different OS's and create those three folders? Is there a way to perform the install command beforehand, and target each OS from a single OS?

**Comment by juj** [comment]
> Is there a way to perform the install command beforehand, and target each OS from a single OS.

Emsdk itself does not have a cross-compilation architecture. However if you build manually, you would be able to cross-compile to each OS, as long as you set up cross-compiler archs accordingly.

> If a standalone python executable was created

The python installation that emsdk ships for Windows is a portable/standalone python installation. You can look at the emsdk_manifest.json files on how it solves that, and reuse the same scheme for other OSes.

Instead of editing emsdk_manifest.json for those OSes, check how emsdk precreates the .emscripten config file and the env. vars for Windows, which locate the portable python installation. The same scheme can be used for the other OSes, it will work identically there.

**Comment by sbc100** [comment]
If you want to how we bundle the windows python in the emsdk I wrote this little script that generates it:

https://github.com/emscripten-core/emsdk/blob/master/scripts/update_python.py

**Comment by kripken** [comment]
@jeff-hykin 

I'd love to see this happen!

LLVM and Binaryen are the easy parts. There are ports of both to js+wasm (using node.js file access), although the LLVM side is less polished, but it could be. A week or so ago I helped an LLVM-using project port itself to wasm, it took only about a day, although we did add a bunch of hacks along the way.

If you're fine running node.js in Electron, that sounds fine. (I am personally also interested in a 100% Web solution, which means no Node, or limited functionality.)

The bigger issue is Python. There are ports of it, and they work, but really just the pure computation side. Emscripten uses python to do things like file access, network access, multiprocessing, etc. Those things are harder to port. I see 2 main routes here:

1. Do the hard work to port them. For example, find whatever system calls python ends up doing to get its multiprocess support (`popen` etc.?) and map those to Node.js APIs. This might not be easy, and not all APIs might be available in Node. But there can't be *that* many APIs here, so just trying might be the best thing.
2. Rewrite our python code to something else. Node.js was extremely new back when emscripten started, so we couldn't consider it, and python was the easy option. But node.js would be fine today. This would mean converting several thousand lines of code, but not all of it would be necessary immediately. Also I've wondered if some kind of script could automatically convert 90% of the syntax properly, and leave 10% to humans (luckily neither of the two languages declares types!).

I wish I had time for these myself, but I can help someone else get started and with any questions!

**Comment by jeff-hykin** [comment]
> The python installation that emsdk ships for Windows is a portable/standalone python installation.

@juj This is fantastic to hear, I had no idea emsdk was shipped with a portable python for windows.

> Instead of editing emsdk_manifest.json for those OSes, check how emsdk precreates the .emscripten config file and the env. vars for Windows, which locate the portable python installation. The same scheme can be used for the other OSes, it will work identically there.

Thanks for the info, this is definitely enough that I can get started with. And thanks @sbc100 that is also really helpful!

**Comment by jeff-hykin** [comment]
@kripken your news is also great to hear. Do you have any links to the LLVM repo you worked on? I reached out to the author of the clang-wasm demo, but the repo was still very alpha (the iostream header doesn't even work).

The python multiprocessing will certainly be very hard to port, I didn't realize that was part of the code base. I'll be exploring all the ways; portable python, auto-convert and fix bugs, or manual translation from python to node. For fun sometime I'll probably make a rough python-to-javascript syntax converter although it'll probably be more like 75% instead of 90% hands-free conversion. The multiprocessing code will be the real work in almost any case though.

**Comment by sbc100** [comment]
If I were you I would start with wask-sdk.  Its just one or two standalone binaries.  You will learn a long in the process and,  if you have successful in building a version that suites your needs then you might consider extending the project to emscripten which is strictly harder (by several orders of magnitude IMHO).

**Comment by kripken** [comment]
@jeff-hykin 

> Do you have any links to the LLVM repo you worked on? 

It's not my project, and I'm not sure they want it shared widely yet, sorry. (But there isn't much there that would help you - basically, the port was just: run emcmake cmake and then make, and add a few hacks to avoid missing features.)

> For fun sometime I'll probably make a rough python-to-javascript syntax converter

Btw, I did some searching meanwhile, and found [JavaScripthon](https://github.com/metapensiero/metapensiero.pj). It looks like a pretty serious effort at translating Python to JavaScript, so might be worth looking at!

**Comment by jeff-hykin** [comment]
After getting more familiar with the codebase, I should partially apologize as I should've done a better job reading the readme. I can see why my first few comments on portability were confusing; I was misunderstanding the dependencies of the SDK. You guys are really friendly for working with me despite me not making too much sense! (I also didn't notice that I created the issue on core instead of the sdk)

To my defense, I think there is a subtle issue on [emscripten.org](emscripten.org), which I was using instead of the readme. The [Download and Install](https://emscripten.org/docs/getting_started/downloads.html) page thats linked by Google has this:

> ## Installation instructions
> First check the [Platform-specific notes](https://emscripten.org/docs/getting_started/downloads.html#platform-specific-notes) below and install any prerequisites.


<br>

And following [that link](https://emscripten.org/docs/getting_started/downloads.html#platform-specific-notes) you reach:

> ### Windows
> 1. Install Python 2.7.12 or newer (older versions may not work due to a GitHub change with SSL).


<br>

Followed by

> ### macOS
> If you use MacOS 10.13.3 or later then you should have a new enough version of Python installed (older versions may not work due to a GitHub change with SSL). Otherwise you can manually install and use Python 2.7.12 or newer.

> These instructions explain how to install all the [required tools](https://emscripten.org/docs/building_from_source/toolchain_what_is_needed.html#toolchain-what-you-need). 

<br>

Following that "all the required tools" link ends up here:

> ### Emscripten tools and dependencies
> In general a complete Emscripten environment requires the following tools. First test to see if they are already installed using the instructions below.
> 
> - Node.js (0.8 or above; 0.10.17 or above to run websocket-using servers in node):
> - Python 2.7.12 or above, or Python 3.5 or above (Python 2.7.0 or newer may also work, but is known to have SSL related issues, https://github.com/emscripten-core/emscripten/issues/6275)
> - Java (1.6.0_31 or later). Java is optional. It is required to use the Closure Compiler (in order to minify your code).
> - Git client. Git is required if building tools from source.
> - LLVM (LLVM, including clang and wasm-ld)
> - Binaryen (Binaryen, including wasm-opt, wasm-emscripten-finalize, etc.)
> - The Emscripten code, from GitHub

Which seems like the normal requirements since there's explicit statements about building from source like "Git is required if building tools from source."  But upon closer inspection I see now that the whole list is under the building from source page.

Thats why I was really surprised @juj when you mentioned bundled python with windows (since [emscripten.org](emscripten.org) said to install python ≥ 2.7.12 on Windows).

**Comment by jeff-hykin** [comment]
So to revise the issue: 99% of my needs are met! (Even if it's still far away from a web implementation) I'm really impressed how you guys bundled everything so well, I can't remember the last time I've used a tool that didn't have global non-preinstalled dependencies. I've been getting started on the last 1%, which is to have a single folder corresponding to a specific version of emscripten where `./emsdk/**/emcc file.c` works without needing to run any setup commands, and have it where no `~/.emscripten` is created/needed.

I'm still interested in reducing the dependencies as much as possible, but it will be probably be awhile before I put significant work into converting the whole code base to node or compile the LLVM itself to WASM/WASI. @kripken JavaScripthon does look really cool, I might use that on other projects in the meantime.

**Comment by jeff-hykin** [comment]
@kripken thanks for sharing JavaScripthon I didn't see that in my search. I might use it on other projects as well.

> Node.js was extremely new back when emscripten started, so we couldn't consider it, and python was the easy option. But node.js would be fine today.

Is there any interest in slowly moving away from python? Either towards node, or towards something like Rust/C++ that can be compiled to WASM.

**Comment by kripken** [comment]
> Is there any interest in slowly moving away from python? Either towards node, or towards something like Rust/C++ that can be compiled to WASM.

Yes, I think that would be good to explore (I don't have a strong opinion between the various options, each has advantages). Would be great if someone experimented with this, something like getting "hello world" to work with an emcc.py replacement.

**Comment by jeff-hykin** [comment]
That's good to hear.

I've been working on something that coincidentally should help; a Node recreation of a library for scripting tasks. It seems like a decent chunk of the python is simple tasks like zip/unzip, or converting between windows/unix filepaths.

I found the mention of the "embedded" mode in the code and took advantage of that to create a `emsdk_windows`, and `emsdk_mac` folder. But I didn't see anything about the embedded mode in the documentation. I modified some of the code in `shared.py` to get it working without absolute paths in `.emscripten`. I tested the USB drive on a Mac with a different OS version and it worked! I'll have access to a separate windows machine for testing on Saturday. 

The only issue on the Mac test, was that it rebuilds the cache on the first run even though the cache was already built. It would be really nice to not have to rebuild it, but I'm not sure if that's worth forcing: is the cache dependent on OS-version/hardware architecture? I could probably force it to check the relative path, but it's not worth pursuing if it's going to result in a corrupt cache.

**Comment by sbc100** [comment]
If you install with "./emsdk --embedded" the resulting tree should be completely portable/movable.
It works by using relative paths in the config file (it does this by reading the EM_CONFIG environment variable).  I'm hoping to make the embedded options the default very soon.
 
If you install emscripten with "emsdk" the cache should these days come fully populated.

The cache should platform independent, although as it happens the emsdk builders for each OS build their own cache.  I would be interesting to figure out why the case is being cleared.  EMCC_DEBUG=1 might help you here.

**Comment by jeff-hykin** [comment]
@sbc100 Thanks for the info. I'm using emsdk so I'll figure out what's going on with that debugging tip. Thanks also for the brief explanation of the embedded option. I (of course) found the documentation immediately after reading your comment, so I'll be spending a lot more time reading.

**Comment by sbc100** [comment]
Embedded is not the default mode for emsdk as of a couple of days ago!

**Comment by jeff-hykin** [comment]
(did you mean now? Instead of not)

**Comment by sbc100** [comment]
Yes!  :)

**Comment by jeff-hykin** [comment]
whoop! 🎊  🚀

**Comment by npip99** [comment]
It would be nice to see emscripten as a complete .wasm file / a single executable, that can take C++ as input and output wasm. I would use [pkg](https://github.com/vercel/pkg#readme) as opposed to electron though. Electron is for porting the entire browser environment, pkg is for only nodejs apps.

**Comment by jeff-hykin** [comment]
Here's some related news 
https://www.reddit.com/r/WebAssembly/comments/qn9a5j/i_made_emception_emscripten_running_clientside_in/

**Comment by sbc100** [comment]
Wow!  That is very impressive indeed.

**Comment by kripken** [comment]
Thanks for mentioning that @jeff-hykin !

As mentioned in https://github.com/emscripten-core/emscripten/issues/6432#issuecomment-963407064 , I think we can close this now. See notes there about possible followup issues.
