### ISSUE TITLE
"Not a vector MVT!" clang error with -s SIMD=1 on tot

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#11176]
This may belong in llvm/clang, not here.  If so, sorry… just let me know and I'll file it there.

We use tot for [SIMDe](https://github.com/nemequ/simde/), and today our emscripten builds started failing.  Here is an example (including the output from clang with the backtrace): https://travis-ci.org/github/nemequ/simde/jobs/687742400

The problem occurs with `-O3 -s SIMD=1`.

I've attached the [test case from clang](https://github.com/emscripten-core/emscripten/files/4639371/emscripten-error.tar.gz).  It's rather large, sorry.  I'm running it through C-Reduce now, but it's going *very* slowly.  Once it's done I'll add it if it's any good.

**Comment by kripken** [comment]
cc @tlively

**Comment by tlively** [comment]
Thanks for the cc, will investigate.

**Comment by tlively** [comment]
Fixed in https://reviews.llvm.org/D80164

**Comment by nemequ** [comment]
Our CI is working again now.  Thanks @tlively!
