### ISSUE TITLE
How to pass Object key value pair as an argument to JavaScript Function with embind::val?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11197]
I haven't seen a single example of embind::val that pass Object Key Value Pair as an Argument to JavaScript Functions. 

Therefore, I decided to try by structuring JSON-style string with C++ and passing it as an argument to that specific function,

`'{' + std::string("brandId") + ':' + std::to_string(brandId) + '}'
`
However, the Javascript run time not recognize it as an valid Object instead it being parsed as a String literal. 

While I'm new to C++, I got slight memory about Struct data type and I decided to give it try, but even though I can pass Struct as an Argument, at run time, it trigger following error, 

`parameter 1 has unknown type Z9getCarBrandiNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEiE10brandStruct`

**Comment by gerald-dotcom** [comment]
I was able to do following,

```
    emscripten::val ExampleObject = emscripten::val::object();
    ExampleObjectset("key", value);
```

It is working, but is this correct way to create native Objects in emscripten?

**Comment by kripken** [comment]
@gerald-dotcom - I'd suggest not posting the same questions both here and to the mailing list. Many of the same people read them both, so you're just sending them duplicate emails. Worse, the discussions can get fragmented if a response appears in one but not the other, so it makes things harder for people searching in the future.

For questions like this, I think a github issue is more appropriate (but I don't feel strongly about that).

I understand it can be frustrating to not get an answer, and posting in more places does increase your chances. If you're really stuck, I'd suggest posting an issue, waiting a week or so, and then posting to the mailing list but only posting a brief "please see this issue, I could use help there" - that at least would avoid the fragmentation problem.

**Comment by gerald-dotcom** [comment]
@gerald-dotcom 

I'm trying to get the solution faster and I will make sure to post solution both in here and there. 

Already did for previous issue.  You have my word. 

For the next time, I will post issue in Google Groups and will wait.
