### ISSUE TITLE
Enable stdin for compilation

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#112]
For use with other builders it is faster and easier if compiling can be done via passing by stdin.

**Comment by trzecieu** [comment]
I think that might be closed, recent upstream compiled does support compilation from stdin:
```bash
/tmp 
➜ cat << EOF > main.cpp                                   
#include <iostream>
int main() { std::cout << "Hello EMCC" << std::endl; }
EOF

/tmp 
➜ cat main.cpp | em++ -x c++ -s WASM=2 -o main.js -   

/tmp took 2s 
➜ node main.js 
Hello EMCC

```

**Comment by kripken** [comment]
Yes, this was fixed at some point and seems we forgot to close the issue, thanks @trzecieu
