### ISSUE TITLE
libc++ etc. needed with emcc on a c file?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#11219]
When running `emcc a.c` I noticed it links in c++ libs,
```
system_libs:DEBUG: including crt1 (crt1.o)
system_libs:DEBUG: including libc (libc.a)
system_libs:DEBUG: including libcompiler_rt (libcompiler_rt.a)
system_libs:DEBUG: including libc-wasm (libc-wasm.a)
system_libs:DEBUG: including libc++ (libc++-noexcept.a)
system_libs:DEBUG: including libc++abi (libc++abi-noexcept.a)
system_libs:DEBUG: including libmalloc (libdlmalloc.a)
system_libs:DEBUG: including libpthread (libpthread_stub.a)
system_libs:DEBUG: including libstandalonewasm (libstandalonewasm.a)
system_libs:DEBUG: including libc_rt_wasm (libc_rt_wasm.a)
system_libs:DEBUG: including libsockets (libsockets.a)
```
Is that necessary? I guess there is likely no cost as the linker considers them and links in nothing from them. But after clearing the cache it means building a `.c` file leads to building `libc++` and `libc++abi` which surprised me.

cc @sbc100

**Comment by sbc100** [comment]
I'd would like to fix this, and stop having C++ libs included except if you run `em++` or there is a C++ file in the command line.  This is how other toolchains (gcc and clang) work.

The downside is that historically emscripten has always made libc++ available so it will break compatibility.

If we go ahead with the change the following cases will still work:

```emcc foo.cpp``
```em++ foo.o```

However the following case will stop working:

```emcc foo.o```

In this case the compiler driver being used if for C code and the driver can't see any C++ files in the input so the link will fail if `foo.o` contains C++ code.

I'm not sure it work the breakage though as you are right when you say that none of libc++ will be pulled in if its not referenced.   So there is basically no cost to keeping the status quo.

**Comment by sbc100** [comment]
This will be fixed once we resolve: https://github.com/emscripten-core/emscripten/issues/11121
