### ISSUE TITLE
IE 11 Support not working in 1.39.14

### ISSUE THREAD

**Issue by jofeux** [emscripten-core/emscripten#11217]
I'm porting my application from  emscpriten 1.37.0 to 1.39.14/1.29.16. Its supposed to continue to run in IE11.

When compiling with   `-s WASM=0 -s SINGLE_FILE=1  -s LEGACY_VM_SUPPORT=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['_malloc', 'writeArrayToMemory', 'ccall', 'getValue', 'setValue']"` I see an error in the console of IE11 `Property "apply" of undefined or null reference cannot be called`. This happens when calling Module._malloc(..) executes:
```
/** @type {function(...*):?} */
var _malloc = Module["_malloc"] = function() {
  return (_malloc = Module["_malloc"] = Module["asm"]["malloc"]).apply(null, arguments);
};
```
The property _malloc of Module exists, but it has a value of 'undefined'.

Am I missing a certain compiler/linker flag?

**Comment by sbc100** [comment]
I believe malloc is a native function and should be exported by adding it to `EXPORTED_FUNCTIONS`.   However based on that code snipped it looks like it is indeed being exported already.   

BTW, its `Module["asm"]["malloc"]` where the actual code is expected to live.   `Module["_malloc"]` is only an alias.

Does this work when you use `WASM=1`?  Can you run with EMCC_DEBUG=1 and see if malloc appears in the log anywhere?

**Comment by sbc100** [comment]
Also where is the call to malloc happening?  Is it perhaps coming before the module is loaded?

**Comment by jofeux** [comment]
@sbc100 Thanks for your help. The module was only partially loaded. Adding `-s BINARYEN_ASYNC_COMPILATION=0` solved my problem. By the way, in Chrome (83) and Firefox (76) the applications also runs without any problems.

WASM=1 did not help, since IE11 does not support WASM. On IE11 console: `WebAssembly not supported`.
I could not use EMCC_DEBUG=1: `emcc: error: Attempt to set a non-existent setting: 'EMCC_DEBUG'`

`Assertions=1` showed me the way.

**Comment by jofeux** [comment]
Problem solved, but one more question: What is the significance of the following wasm-ld warnings: 
` [exec] wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=0 expected=1
     [exec] wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=1 expected=2
     [exec] wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=2 expected=3
     [exec] wasm-ld: warning: unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=3 expected=4
`

**Comment by sbc100** [comment]
EMCC_DEBUG is an environment variables, rather than a `-s` setting.

**Comment by sbc100** [comment]
Those linker warning a not a problem in an off themselves but it more of a consistency check between the compiler and the linker.  You should not be seeing them though.  Why version of emscripten and llvm are you using (what does `emcc -v` say?) .    If you can figure what part of your program is causing those linker errors that would be usrful, or perhaps post some kind of instructions so we can reproduce?

**Comment by sbc100** [comment]
You probably don't want `BINARYEN_ASYNC_COMPILATION=0` because is severely limits the size of the WebAssembly module and is kind of an anti-pattern on the web (since it blocks that main thread).  Better to modify your JavaScript code to wait until the module is ready before using it.

**Comment by jofeux** [comment]
I will change to async compilation. Makes a lot of sense.

I found a small example for the `unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB` warning. The warning is given when _mid_istream_open_mem is being exported. Two points seem to lead to the warning: 1. Referencing mem_istream_close within mid_istream_open_mem and 2. Create the js output via creating a shared library.

I hope my little example helps to analyz the root cause.

Source file stream.c
`#include <stdlib.h>

typedef int (*MidIStreamCloseFunc) (void *ctx);
typedef struct _MidIStream MidIStream;

struct _MidIStream
{
  MidIStreamCloseFunc close;
  void *ctx;
};

int
mem_istream_close (void *ctx)
{
  return 99;
}

MidIStream *
mid_istream_open_mem (void *mem, size_t size, int autofree)
{
  MidIStream *stream;

  stream->close = mem_istream_close;

  return stream;
}
`
Bash script to create libstream.js
`#!/bin/bash

# Terminate script on error
set -e

# Set paths for emscripten SDK
source ../../emsdk/emsdk_env.sh

# Compile stream.c
emcc -DHAVE_CONFIG_H -I. -I. -I.. -I.. -O0 -MT stream.lo -MD -MP -c stream.c  -fPIC -DPIC -o stream.o

# Create library
emcc -r -shared stream.o -lm -lc -o libstream-0.1.so.0


# Link libstream to JavaScript module libtstream.js"
emcc libstream-0.1.so.0 \
     -o libstream.js \
     -s EXPORTED_FUNCTIONS="['_mid_istream_open_mem']"

`

**Comment by sbc100** [comment]
Thanks @jofeux , that will help a lot in tacking  that warning down.

**Comment by sbc100** [comment]
I'm investigating the warning now.  I seem to be related to you intermediate step of creating a shared library with `-shared -r`. 

Since emscripten doesn't really support shared libraries can you try just building your code as static libraries (with `ar`.. and without `-fPIC`)?    If you are using some kind of build tool such as autoconf can you somehow disable shared libraries?

**Comment by sbc100** [comment]
The warning you are seeing turned out to be harmless, and it has now been fixed in upstream llvm.

Please go ahead and close this bug if you think its been resolved.

**Comment by jofeux** [comment]
Thanks for your great support, thanks for the wonderful product.
