### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wurc** [emscripten-core/emscripten#11216]
emcc: error: ../src/x86/sysv.S: Input file has an unknown suffix, don't know what to do with it!

Input file has an unknown suffix, don't know what to do with it!

**Comment by sbc100** [comment]
Recent versions of emscripten should support the `.S` suffix for assembly code.

However in this case it looks like you trying to feed it X86 assembly, which will certainly not work.  You need to modify the build system to avoid compiling this source file.
