### ISSUE TITLE
Unable to catch BindingError even when -s DISABLE_EXCEPTION_CATCHING=0

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11222]
I have implemented try and catch logic directly in C++ and what I'm trying to do is to detect undefined variable of JavaScript. 

Here is code,

`      emscripten::val full = emscripten::val::global("fullValues");
	
        try {
		std::cout << full.as<std::string>() << "\n";
	}
	catch (const std::runtime_error& re)
	{
		// speciffic handling for runtime_error
		std::cerr << "Runtime error: " << re.what() << std::endl;
	}
	catch (const std::exception& ex)
	{
		// speciffic handling for all exceptions extending std::exception, except
		// std::runtime_error which is handled explicitly
		std::cerr << "Error occurred: " << ex.what() << std::endl;
	}
	catch (...)
	{
		// catch any other errors (that we have no information about)
		std::cerr << "Unknown failure occurred. Possible memory corruption" << std::endl;
	}
`

I complied the above code with -s DISABLE_EXCEPTION_CATCHING=0 but the browser console still print out the error when it shouldn't

`BindingError: Cannot pass non-string to std::string`

**Comment by sbc100** [comment]
I think BindingError is a JavaScript exception from embind.js.  AFAIK you can't catch JavaScript exceptions in C++ (I could be wrong but it seems unlikely).
