### ISSUE TITLE
confusing errors when same file is linked twice

### ISSUE THREAD

**Issue by jstimpfle** [emscripten-core/emscripten#11220]
I had a problem at the linking stage using emcc where I got a lot of errors like this:

```
wasm-ld: error: duplicate symbol: foo
>>> defined in data.o
>>> defined in data.o 
```

It took me some time to figure out that I had accidentally listed `data.o` twice on the linker command line. I figure it would be a quick fix to detect or handle that problem in a friendlier way? Does it ever make sense to link the same file twice?

**Comment by sbc100** [comment]
Linkers in general do not support this.  At least none of the one I've ever used.  I don't think it makes sense for emscripten to be different in this respect.

**Comment by sbc100** [comment]
That warning seems very clear indeed to me.. it appears to communicate precisely what is wrong no?

**Comment by jstimpfle** [comment]
It probably never happened to me when using other linkers. As to the message, sure, it prints the problem, but no help is offered in finding the cause.

I'm aware that even detecting that a file was given twice on the command line is hard to do correctly in general - when the path was typed in different ways. Some languages' standard libraries do it by looking at the inode for example. So that makes me doubt as well that there is a nice way to handle this.

**Comment by sbc100** [comment]
The error messages produced by gcc and clang are very similar:

```
clang -fuse-ld=lld foo.o foo.o
ld.lld: error: duplicate symbol: main
>>> defined at foo.c
>>>            foo.o:(main)
>>> defined at foo.c
>>>            foo.o:(.text+0x0)
```

```
$ gcc  foo.o foo.o
/usr/bin/ld: foo.o: in function `main':
foo.c:(.text+0x0): multiple definition of `main'; foo.o:foo.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

Personally I think these error are useful enough to diagnose the problem.   Its sounds like you are asking for a special error saying "You included the same file twice"?    I think the problem with doing that is there are some cases where this is a valid thing to do.  For example, if all the symbols in a given object file are weakly defined. 

If you would like to pursue this then its probably best in the upstream lld project where these errors are detected.  Maybe file a bug bugs.llvm.org and if its possible we could get this error added to all versions of lld, not just the WebAssembly one.
