### ISSUE TITLE
emsdk install latest_upstream requires npm

### ISSUE THREAD

**Issue by leemke** [emscripten-core/emscripten#11234]
running the latest "emsdk install latest_upstream" at the end invoke "npm".
That tool is not pre-installed in chrome os.

**Comment by sbc100** [comment]
emsdk installs its own copy of node.  It should not depend on the system version node. 

The code in question is here:

https://github.com/emscripten-core/emsdk/blob/5613488e753e05170967052fab74254eb9763d4f/emsdk.py#L1239

Could you add some debugging to see why this doesn't seem to be working for you?
