### ISSUE TITLE
Breaking change: fix GL context-specific attributes

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#11230]
Currently we have the following

```js
var GL = {
  counter: 1,
  buffers: [],
  mappedBuffers: {},
  programs: [],
  framebuffers: [],
  renderbuffers: [],
  textures: [],
  uniforms: [],
  shaders: [],
  vaos: [],
  contexts: [],
  currentContext: null,
  offscreenCanvases: {},
  timerQueriesEXT: [],
  queries: [],
  samplers: [],
  transformFeedbacks: [],
  syncs: [],
  programInfos: {},
  stringCache: {},
  stringiCache: {},
  unpackAlignment: 4,
```
This is troubling, because most of the state above is per-context, instead of global. When dealing with multiple contexts, one cannot distinguish between their respective data. If a context is lost or deleted, we cannot clean up its per-context textures/uniforms/etc, but they stick around as orphaned data.

There are mentions of issues (browser bugs?) where keeping around texture/buffers references from contexts would be preventing garbage collection (e.g. https://stackoverflow.com/questions/37072303/how-to-free-and-garbage-collect-a-webgl-context and https://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use), so it would be nice to be clean with this behavior.

Further, most of the keys are unique (because of GL spec). We never simultaneously have a GL.textures[x] and, say, a GL.buffers[x].

I would like to move all of the above data to be instead per-context, i.e. from `GL` to `GLctx`, similar to #11225. This way if a context is deleted, all of its state is deleted automatically too.

I would also like to change to a single `GLctx.objects` map that has all the abovementioned objects, instead of having a separate array for each object type. That will give smaller code size due to fewer arrays, but also less entropy for gzip to compress better.

However I do know there are some users who directly access the internal `GL.textures` and `GL.buffers` etc. fields from their JS code (although that data has not ever been considered as public API). This change would break those users. (We at Unity do that as well)

I'm pondering if I should approach this with a -s LEGACY_SINGLE_CONTEXT_GL_STATE = 0/1 setting, or just go ahead and do the change and let users break? If users are accessing `GL.textures[x]` from their code, they would get a noisy exception `GL.textures` is not an array, so the change should not cause silent failure at least.

Migrating to the new structure would mean changing all occurrences of `GL.textures[x]` / `GL.buffers[x]` etc. to `GLctx.objects[x]`.

If one wants to test if something is of type texture or a buffer (somewhat rare since code paths statically know what they are working on), instead of doing `GL.textures[x]` they'd either call `_glIsTexture(x)` or do `typeof GLctx.objects[x] === 'WebGLTexture'`. So overall migration should not be too complicated.

**Comment by kripken** [comment]
> Further, most of the keys are unique (because of GL spec).

Which are not?

Aside from that question this sounds good to me. As an internal API I think we can break it for these benefits. We should just mention it in the changelog while doing so.

**Comment by juj** [comment]
> > Further, most of the keys are unique (because of GL spec).
> 
> Which are not?

Err sorry, bad wording. All of the GL object names are unique. The `GL.contexts` and `GL.offscreenCanvases` e.g. are not, since they do not store WebGL objects.

**Comment by kripken** [comment]
I see, thanks. Sounds good!
