### ISSUE TITLE
Exception in destructor of emscripten::val when in a different thread

### ISSUE THREAD

**Issue by skonstant** [emscripten-core/emscripten#11248]
I have a class that contains an emscripten::val

```class JSInterface {

public:
    explicit JSInterface(emscripten::val callbacks) : myCallbacks(callbacks) {}

    emscripten::val myCallbacks;
};
```

This is overriden in JS like this for example:

```callback = new Module.JSGetReposCb({
                  on_error: function(error) {
                      console.error(error)
                  },
                  on_success: function(repos, user) {
                      FS.syncfs(function (err) {

                      });
                  }
              });
```

In the main browser thread, I do some work on a background thread, call the callback on the main thread and if the object gets freed in a background thread, I get a crash when the emscripten::val field gets cleared. (I use smart pointers, I do not delete myself).

I guess this is kind of expected as Javascript objects do not cross threads, it would be useful if this was caught however, because I cannot catch it and it crashes my thread.

**Comment by kripken** [comment]
(I think you need three backticks before and after to escape a block)

cc @jgravelle-google , yeah, it would be good to have better errors and checks for stuff like this.

**Comment by skonstant** [comment]
Updated, yes, it crashes the thread but it does not crash the browser tab strangely enough, on Chrome. The worker seems to stay there however.
