### ISSUE TITLE
RuntimeError: function signature mismatch,RuntimeError: function signature mismatch when set SAFE_HEAP=1 + llvm-backend

### ISSUE THREAD

**Issue by Praveer1981** [emscripten-core/emscripten#11242]
Hi,
Recently, we have upgraded our emscripten version and now point to upstream. 
The source code works well with the fastcomp. However, we encounter `segmentation fault` in the upstream.
Flags set:
 `FLAGS = -std=c++17 -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR
  LINK_FLAGS = -s EXIT_RUNTIME=1 -s SAFE_HEAP=1 -s ASSERTIONS=1 --profiling -s DISABLE_EXCEPTION_CATCHING=0 -s INLINING_LIMIT=1 -s FORCE_FILESYSTEM=1 --emit-symbol-map --profiling -s ASSERTIONS=2 -lnodefs.js  -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s WASM_OBJECT_FILES=0 -flto -fPIC -Oz`

below is the sample code.
**main.cpp**
```
#include <iostream>
#include <boost/filesystem/path.hpp>

#include<emscripten.h>

typedef  boost::filesystem::path path;
constexpr auto SETTINGS_NAME = L"Settings";
 constexpr auto FILE_NAME = L"temp.json";
const path& resDir()
{
    static path p = path(L"/test");
    assert(!p.empty());
    return p;
}

std::wstring
foo()
{
    static const auto& imagePath = resDir() / SETTINGS_NAME /FILE_NAME;
    return imagePath.wstring();
}

int main() {
    std::cout<<"Start Main"<<std::endl;
    {
        std::wstring path = foo();
        std::wcout<< __LINE__<<" "<<__FUNCTION__ <<" "<<__FILE__ <<" "<< path<<"\n";
    }
    std::cout<<"End Main"<<std::endl;
    return 0;
}
```
Attached the supporting files
[Rlated_files.zip](https://github.com/emscripten-core/emscripten/files/4680356/Rlated_files.zip)

**Comment by sbc100** [comment]
Do you mean a compiler crash?  Or a runtime crash?   I'm guessing a compiler crash (Since wasm doesn't have segmentation faults per say).  Can you include the full output of the crash?

**Comment by Praveer1981** [comment]
Its a run time crash. I have attached the full out put of the crash.
[localhost-1590450930743.log](https://github.com/emscripten-core/emscripten/files/4679216/localhost-1590450930743.log)

**Comment by sbc100** [comment]
Are you using the emscripten port of boost or your own version?

Does the problem reproduce without boost?   (it would be good to remove the dependency to simplify the repro case if possible, since boost adds a lot of complexity).

Also, I assume from the title of the bug that the program runs fine without SAFE_HEAP?

**Comment by kripken** [comment]
Worth trying this with asan (`-fsanitize=address` at both compile and link) as the code might have a real issue.

**Comment by Praveer1981** [comment]
@sbc100  I had added boost in my sample app because my actual code uses boost. I removed the boost dependency and ran it I got the same runtime error.
1. with upstream -> function signature mismatch.
2. with fastcomp -> there is no error.
3. I built and run using vs2019 -> there is no error.
Here is my updated codesnippet:
```
std::wstring
foo()
{
    static const std::wstring& imagePath(L"/TEST");
    return imagePath;
}

int main()
{
    std::cout << "Start Main" << std::endl;
    {
        std::wstring path = foo();
        std::wcout << __LINE__ << " " << __FUNCTION__ << " " << __FILE__ << " " << path << "\n";
    }
    std::cout << "End Main" << std::endl;
    return 0;
}
```

**Comment by kripken** [comment]
Thanks @Praveer1981 , adding `#include <iostream>` to that last testcase, it's enough to do `emcc a.cpp -std=c++17 -s EXIT_RUNTIME=1  -O3 --profiling` to see the error. What seems to be happening here is that an `atexit` is set up, and we assume the function signature is `void (int)` but the function is
```
$std::__2::basic_string<char\2c\20std::__2::char_traits<char>\2c\20std::__2::allocator<char>\20>::~basic_string\28\29 (param $0 i32) (result i32)
```
(this is an atexit for that static `wstring`).

The signature of such a function should indeed be `void (int)` according to libcxxabi,
```c++
extern _LIBCXXABI_FUNC_VIS int __cxa_atexit(void (*f)(void *), void *p,
```

Maybe this is undefined behavior in libc++?

**Comment by sbc100** [comment]
Oh, I think this is an issue that @sunfishcode bought up recently.  Dan do you have a bug somewhere regarding this?

TBH, if its that easy to re-produce why don't we see this all over the place and in our test suite?

**Comment by kripken** [comment]
I suspect we don't see this often because we default to not exiting the runtime, but here `EXIT_RUNTIME` was set.

**Comment by Praveer1981** [comment]
Thanks @sbc100 @kripken did you log this as bug? in which version we might expect the fix ?

**Comment by sbc100** [comment]
This issue is what we consider a bug. 

Are you able to run with `EXIT_RUNTIME=0` as a workaround for a while?   While we are keen to look into this its hard for us to give any concrete timelines on bugfixes I'm afraid.

It looks like the fix will most likely require an upstream llvm change.  I think this upstream bug looks like the same thing maybe: https://bugs.llvm.org/show_bug.cgi?id=45876.
