### ISSUE TITLE
FFplay port not terminating

### ISSUE THREAD

**Issue by adityasharma2000** [emscripten-core/emscripten#11247]
While porting ffplay using emscripten, the _main function call doesn't seem to terminate. ![ffplayerror](https://user-images.githubusercontent.com/40341018/82886683-7fece900-9f64-11ea-8592-8e95d4df7014.png)The following were configuration and build commands.

Emscripten Version:  latest-fastcomp

Configuration:
`emconfigure ./configure --disable-x86asm --disable-inline-asm --disable-doc --disable-stripping --nm="llvm-nm -g" --ar=emar --cc=emcc --cxx=em++ --objcc=emcc --dep-cc=emcc`

Compiled/built using:
`emcc -Llibavcodec -Llibavdevice -Llibavfilter -Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample  -Qunused-arguments -Oz -o FFplayJavascript/ffplay-script.html fftools/cmdutils.o fftools/ffplay.o  -lavdevice -lavfilter -lavformat -lavcodec -lswresample -lswscale -lavutil  -lm  -s EXPORTED_FUNCTIONS="[_main]" -s EXTRA_EXPORTED_RUNTIME_METHODS="[cwrap, FS, getValue, setValue]" -s USE_PTHREADS=1 -s USE_SDL=2 -s TOTAL_MEMORY=33554432`

Linking pthreads is essential because ffplay uses SDL_mutex. If not included, it complains:
`SDL_CreateMutex(): SDL not built with thread support`

I am unable to locate the reason for the port to not terminate. Is it related to pthread implementation in emscripten or some incorrect configuration/build options used?

**Comment by sbc100** [comment]
If you are trying to build a version of ffmpeg that runs on the main thread you want to build without `-s USE_PTHREADS=1`.

In this mode you should get stub pthread functions which will enable your program to link, but will fail at runtime if you try to use them.

Better still, find a way to remove the dependency of ffmpeg on `SDL_CreateMutex`.  Is there some configuration option to disable the threaded code?

The most likely cause of your immediate program is that pthread_create cannot synchronously start a web worker.. so programs that expect to be able to create threads and start talking to them without first yielding the event loop will block forever.   You can often work around this by setting PTHREAD_POOL_SIZE to some value great than zero which will cause the workers to be created before main runs.

**Comment by adityasharma2000** [comment]
Thanks @sbc100. I changed the build to include PTHREAD_POOL_SIZE and it did go forward.
I have 1 more problem though. I cannot make it render any videos or graphical content. I have a canvas with id="canvas", but then it should automatically do the rendering. I have checked a few links and resources, but none seem to help. If you could share relevant links regarding this problem, it  would be really helpful. Thanks.
![ffplayrender](https://user-images.githubusercontent.com/40341018/83024465-11835600-a04c-11ea-8fa1-6a0e49549b95.png)

**Comment by sbc100** [comment]
If you are trying to render from a background thread you probably need to investigate how the off-screen canvas stuff works.  Sadly I don't know much about it myself.
