### ISSUE TITLE
regression bug upstream 1.39.9+ some C++ io functions not working correctly

### ISSUE THREAD

**Issue by briangavin** [emscripten-core/emscripten#11255]
I have not yet fully narrowed this down, but I am buffer overrun and other errors when I upgrade from upstream 1.39.8 to 1.39.9+ when trying to use certain c++ io functions such as std::istream read_bytes.  Wasm program also works correctly with fastcomp all versions.

**Comment by sbc100** [comment]
If you can provide a test case it sounds like something we need to fix before the switch over.   

You can also try with `-sanitize=address` do see if you have certain classes in memory bugs in your own code (just in case the fastcomp build is working by chance).

**Comment by briangavin** [comment]
It appears the mistake is on my side sorry.   I used the sanitize tool and fixed the problem.
