### ISSUE TITLE
Browser compatibility issues for libde265 

### ISSUE THREAD

**Issue by gawadeavinash** [emscripten-core/emscripten#11263]
Libde265 is h265 decoder. Works well on chrome for stream having configuration 1080p , 10fps and 1MbPS bitrate but on Firefox latency and pauses occurs for same stream.

**Comment by kripken** [comment]
Please [file a bug for firefox directly](https://bugzilla.mozilla.org/home) so that they can fix it (they will need a testcase to be able to look at), and link to it here.
