### ISSUE TITLE
emscripten_websocket_send_binary is missing a __deps entry

### ISSUE THREAD

**Issue by bpaterson2000** [emscripten-core/emscripten#11268]
in library_websockets.js, WS is not recognized by emscripten_websocket_send_binary.  

Running emscripten code that simply calls getaddrinfo, issues this error in the browser console
>Uncaught ReferenceError: WS is not defined at _emscripten_websocket_send_binary

Im not sure if only _new and _send_binary should have a deps entry, i would assume more than just send_binary would also need the same treatment?

**Comment by sbc100** [comment]
Yes all those socket functions that use `WS` should have deps on it.

Please upload a PR if you are able.

**Comment by bpaterson2000** [comment]
I made a PR https://github.com/emscripten-core/emscripten/pull/11269 , i've never done a PR before - hopefully I didnt make a mess of it.
