### ISSUE TITLE
win10 Emscripten encountered a problem compiling C / C + + files

### ISSUE THREAD

**Issue by BrunaDeLafel** [emscripten-core/emscripten#11272]
### emcc Version：
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.15
clang version 11.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 57d361bd2f3668eefa7028ad4a2d616317ed437c)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:/emsdk/upstream/bin
  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
shared:INFO: (Emscripten: Running sanity checks)`

### Error message

PS C:\Users\bruna\Desktop\wasmDemo> **emcc test.c**
[cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "D:\emsdk\upstream\emscripten\cache\wasm\libcompiler_rt.a" for subsequent builds)](url)

`
D:/emsdk/upstream/bin\llvm-ar.exe: error: C:\\Users\\bruna\\AppData\\Local\\Temp\\emscripten_temp_5y41ue_4\\addtf3.o: There are no characters in the multibyte target code page that this Unicode character can map to.
`

**Comment by sbc100** [comment]
Is this related to #10802?

Does setting the PYTHONUTF8 environment variable help?

**Comment by BrunaDeLafel** [comment]
@sbc100 Sorry, after reading the previous issue, where should I add this PYTHONUTF8?

**Comment by sbc100** [comment]
In your environment.   I think on windows that mean `set PYTHONUTF8=1` , but I'm not windows user so I could be wrong.

**Comment by BrunaDeLafel** [comment]
@sbc100 Hello! I came to the company this morning and configured the environment variables related to windows. The original problem is gone. There is a new error.
### ERROR MESSAGE

`Traceback (most recent call last):`

`
  File "D:\emsdk\upstream\emscripten\\emcc.py", line 42, in <module>
    import emscripten
  File "D:\emsdk\upstream\emscripten\emscripten.py", line 25, in <module>
    from tools import shared
  File "D:\emsdk\upstream\emscripten\tools\shared.py", line 3409, in <module>
    parse_config_file()
  File "D:\emsdk\upstream\emscripten\tools\shared.py", line 264, in parse_config_file
    config_text = open(CONFIG_FILE, 'r').read() if CONFIG_FILE else EM_CONFIG
  File "D:\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
`

`
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 306: invalid continuation byte
`

**Comment by BrunaDeLafel** [comment]
@sbc100 I think it's just my computer's python that has some problems. My other windows computer, emscripten, is running properly. I'll check again

**Comment by BrunaDeLafel** [comment]
@sbc100 The problem is solved, ask a colleague of Alibaba, the last reason is because this windows10 does not set the global language support, the modification and restart will run successfully (I think I will not use this operating system anymore), thank you for taking the time Help me see the problem.
