### ISSUE TITLE
delete operator is missing - Embind

### ISSUE THREAD

**Issue by JomaCorpFX** [emscripten-core/emscripten#11286]
**New operator** easy to use
`val x = val::global("Promise").new_(JsManager::Bind(promiseCallback));`

I need to delete a property from object

The solution add a global function in JS 
```
window.DeleteProperty = function(obj, property)
{
  return delete object[property];
}
```
and call from C++
```
bool result = val::global("window").call<bool>("DeleteProperty", aValObject, val("aPropertyName"));
bool result = val::global("window").call<bool>("DeleteProperty", aValObject, aValPropertyName);
```

But I think it is more elegant to use the operator directly with embind.
```
aValObject.delete_("aPropertyName")
aValObject.delete_(aValPropertyName)
```

I found this
https://git.sprintf.io/emscripten-ports/emscripten/commit/15172564ef9f82c84f7267fa0fddf9a0dc54cc9f?lang=es-ES

**Comment by JomaCorpFX** [comment]
Checking the "**val.h**" file, I have noticed that the **delete_** method exists, but in Visual Studio Code it shows an error
"emscripten :: val" does not have any members "delete_"

but if we compile with "em ++" it does not generate any error.
In conclusion, the operator exists. It is an intellisense problem in VSCode.

![image](https://user-images.githubusercontent.com/18097869/83495808-d040db00-a47d-11ea-9b87-0d3f1abd2539.png)

**Comment by jeffRTC** [comment]
Dang it.

Ran to the same. VS code issue.

**Comment by Satancito** [comment]
@jeffRTC  you can solve this with following

**1.** open **"val.h"** file (control + click on delele_ method)

**2.** change this code
**from this**
```
#if __STRICT_ANSI__
        val typeof() const {
            return val(_emval_typeof(handle));
        }
#endif
```
![image](https://user-images.githubusercontent.com/18097869/103025634-32e3ec00-4520-11eb-8b00-31d186031ead.png)

**to this**
```
// #if __STRICT_ANSI__
//         val typeof() const {
//             return val(_emval_typeof(handle));
//         }
// #endif
```
![image](https://user-images.githubusercontent.com/18097869/103025709-5870f580-4520-11eb-8ec3-e04af722371e.png)

3. Enjoy.
