### ISSUE TITLE
Could you filter/check -s parameters?

### ISSUE THREAD

**Issue by igormcoelho** [emscripten-core/emscripten#11281]
Dear all, congratulations for this nice project!

In my brief experience using it, it has already happened many times that I passed wrong parameters via `-s` options.

One simple example:  `-s 'EXPORT_NAME="my-lib-name"'` 

The problem with this is that `my-lib-name` is not a valid name inside javascript, as this `-` will be treated as a `minus` somewhere in the code... and the huge problem is that the error generated by it will be completely cryptic, and many times, emscripten won't even generate an error for that.

I've done that many times on EXPORT_NAME, but also on other flags, like FUNCTION EXPORTS, etc (mistake some `"` with `\"`, for example). I know it's my mistake, but if you could do some basic check on valid identifiers (letters, numbers, underscore,...) passed for `-s` parameters, that would possibly avoid thousands of other crazy errors for users (an d maybe some less issues here, that would be perhaps hard to debug).

I hope that's not much extra work for you guys, if knew the project better I could try that myself, but for the moment I'll have to rely on your masterminds :)

**Comment by sbc100** [comment]
For `EXPORTED_FUNCTIONS` you might want to look at the options of using file to store your expored functions names.   You can use this with the `-s EXPORTED_FUNCTIONS=@filename` syntax.

For the EXPORT_NANE yes I guess we can and should check that its a valid JS identifier.. That should be easy enough.
