### ISSUE TITLE
Question about the LLVM backend and Emterpretify

### ISSUE THREAD

**Issue by sortofsleepy** [emscripten-core/emscripten#11297]
👋 

Coming back to a project after roughly a year(yea yea haha) and I've noticed some changes that seem to be causing problems now. 

Basically the issue at the moment is the use of `emscripten_wget_data` which is being used to load files within the same directory as the main application. 

Roughly a year ago this worked fine. 
``` bash
   set( CXX_FLAGS "${CXX_FLAGS} -s EMTERPRETIFY=1 -s EMTERPRETIFY_FILE=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/em.data.binary -s EMTERPRETIFY_ASYNC=1" )
```

Now when the EMTERPRETIFY flag is set, I get the error 
```bash
emcc: EMTERPRETIFY is not supported by the LLVM wasm backend.  
```

I have thus far not been able to find the necessary information to figure out what changes I need to make to my build setup. 

Any ideas?

I'm hoping that this is an easy fix; in the meantime I will continue to look. 

Thanks!

Info 
====
* Windows 10 using WSL
* Emscripten 1.39.16

**Comment by kripken** [comment]
The Emterpreter was removed, correct. The replacement is the [new Asyncify](https://emscripten.org/docs/porting/asyncify.html) (design issue: https://github.com/emscripten-core/emscripten/issues/8561). It should do basically the same things in terms of calling sync APIs.

**Comment by sortofsleepy** [comment]
> 
> 
> The Emterpreter was removed, correct. The replacement is the [new Asyncify](https://emscripten.org/docs/porting/asyncify.html) (design issue: #8561). It should do basically the same things in terms of calling sync APIs.

Thanks for the quick response! Alright, noted, I will look over the docs and that issue. Couple follow up questions before I close this 

* So are uses of things like `emscripten_wget_data` basically going to have to be re-written by the end user? Or is there a plan to convert the API over to be LLVM compatible? 

Basically the project is to get an existing OpenGL engine compatible with Emscripten; project leaders are pretty keen on keeping the api as close to the desktop one as possible and having built in functions is REALLY handy. 

Lastly 

* I assume the plan is to eventually force everyone to use LLVM? 

Thanks!

**Comment by kripken** [comment]
> So are uses of things like emscripten_wget_data basically going to have to be re-written by the end user? 

No! It should just work. Just replace `-s EMTERPRETIFY` with `-s ASYNCIFY`. Asyncify already has full support for it.

If it doesn't just work please let us know, that would be a bug!

**Comment by sortofsleepy** [comment]
Awesome! That wasn't exactly clear on the docs. 

I will give that a shot and open a new issue if it's still not working. 

Thanks!
