### ISSUE TITLE
[SDL2] SDL_CreateWindow reports "eventHandler.target is undefined"

### ISSUE THREAD

**Issue by embeddedt** [emscripten-core/emscripten#11295]
I hope this is the right place to be reporting this type of issue; if not, please let me know.

I am working on an existing Emscripten project and have recently started getting this error when calling `SDL_CreateWindow`.

```c
    SDL_Init(SDL_INIT_VIDEO);
    SDL_SetEventFilter(quit_filter, NULL);

    window = SDL_CreateWindow("TFT Simulator",
                              SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
                              MONITOR_HOR_RES * MONITOR_ZOOM, MONITOR_VER_RES * MONITOR_ZOOM, 0);
```

That gives me this error: 

```
TypeError: eventHandler.target is undefined lvgl_mp.js:411968:11
    registerOrRemoveHandler http://127.0.0.1:8080/lvgl_mp.js:411968
    __registerMouseEventCallback http://127.0.0.1:8080/lvgl_mp.js:414084
    _emscripten_set_mousemove_callback_on_thread http://127.0.0.1:8080/lvgl_mp.js:414101
```

Here are my flags for compiling:

```
-s USE_SDL=2 -s WASM=0 --source-map-base http://localhost:8000 --memory-init-file 0 --js-library library.js -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0  -m32 -O0 -g3 -Wall -Werror -std=gnu11  -fdata-sections -ffunction-sections
```

And for linking:

```
-m32 -Wl,--gc-sections -Wl,-Map=build/micropython.js.map,--cref -s USE_SDL=2 -s WASM=0 --source-map-base http://localhost:8000 --memory-init-file 0 --js-library library.js -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0
```

I've removed the `EXPORTED_FUNCTIONS` and `EXTRA_EXPORTED_RUNTIME_METHODS` arguments from my listings to save space; if you need those flags, or any other information, just ask!

It's not entirely clear to me why this value is `undefined`; my initial research/debugging has suggested that the canvas reference is not being passed to Emscripten properly, but I added debugging logic to my `Module['canvas']` function and it is returning a proper canvas element.

We do one special trick in our project which may be part of the problem: Emscripten runs in an `iframe` while the canvas element is located in the parent window. This has worked for months, but I'm wondering if a recent browser/toolchain update broke things?

Any suggestions would be greatly appreciated.

**Comment by kripken** [comment]
Doesn't sound like a known issue to me, but cc @Daft-Freak who might remember more.

Since it crashes on something basic like `SDL_CreateWindow` I'd suggest looking at the test suite examples using that method that are known to work (full-text search under `tests/` for that method, for example) . Narrowing down what's different in your case (different params, or different HTML setup) might be the fastest way to figure this out.

**Comment by kripken** [comment]
> This has worked for months, but I'm wondering if a recent browser/toolchain update broke things?

Or, if this is a regression, then bisection on emscripten releases/commits could be even faster.

For the browser side, checking a bunch of different browsers and versions could rule that out.

**Comment by Daft-Freak** [comment]
Probably related to the event target changes `-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR`. SDL2 doesn't use `Module['canvas']` and instead ends up looking for a canvas with an id of "canvas". Which happens to work on the default shell.

(GL support still uses `Module['canvas']`, but that's an entirely separate issue...)

**Comment by embeddedt** [comment]
I tried a combination of things and was able to resolve the problem:

* I switched to Emscripten 1.39.7 (I believe this uses the "upstream" compiler?).
* I moved the canvas element into the iframe and set `Module['canvas'] = document.getElementById("canvas")`.
* I set `DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR` to 1 in order to opt into the ID-searching behavior and be forwards-compatible. 

Thanks for the suggestions.

**Comment by embeddedt** [comment]
Update: I found an alternative workaround that works regardless of where the canvas element is.

It involves monkey-patching `document.querySelector` to return the canvas element.

```js
var prevQuery = document.querySelector;
document.querySelector = function(selector) {
	if(selector == "#canvas")
		return window.top.document.getElementById('canvas');
	else
		return prevQuery(selector);
}
```

Tested and confirmed to be working with 2.0.4.
