### ISSUE TITLE
dlsym for executable

### ISSUE THREAD

**Issue by kg** [emscripten-core/emscripten#11304]
In other native environments, you can use dlsym to get the address of a symbol from an executable (i.e. the currently running one). I can't see anything in the documentation about how this would be done for an emscripten-compiled binary, since it only talks about using dlopen to open a module from the filesystem.

For a .so in the filesystem I can dlopen it and dlsym it, but if I statically link it in, what's the equivalent operation to be able to dlsym its symbols out of my main executable?

**Comment by kripken** [comment]
I think `dlopen` with NULL opens the current executable. That works in emscripten too, here is a test: https://github.com/emscripten-core/emscripten/blob/master/tests/core/test_dlfcn_self.c#L19

**Comment by kg** [comment]
Aha, so the documentation is correct and just omitted this case - there's no need to do anything weird with the filesystem. Thanks.

**Comment by kripken** [comment]
Oh, which doc page did you see this mistake on? We should fix that.

**Comment by kg** [comment]
https://github.com/emscripten-core/emscripten/wiki/Linking#dlopen-dynamic-linking said "you must load the side module into the filesystem", which I interpreted as meaning that it *must* exist in the filesystem, but it makes perfect sense that dlopen(NULL) would still work and the documentation was just not referring to the case. Maybe still worthwhile to be explicit that in this scenario, it will also work.

**Comment by kripken** [comment]
Thanks, good idea. I updated that page now.

Closing as I think that's all we need to do here.
