### ISSUE TITLE
Cannot use EXPORT_ES6=1 and USE_PTHREADS=1 at the same time

### ISSUE THREAD

**Issue by protango** [emscripten-core/emscripten#11303]
If I try to invoke emcc using both the EXPORT_ES6 and USE_PTHREADS flags, I receive an error relating to the acorn optimizer:

**Command**
`emcc file.cpp -o bin/file.js --bind -s MODULARIZE=1 -s EXPORT_ES6=1 -O3 -s USE_PTHREADS=1`

**Output**
```
C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:2780
  throw err
  ^

SyntaxError: 'import' and 'export' may only appear at the top level (61:6)
      import(e.data.urlOrBlob).then(function(PhysicsModule) {
      ^

    at Parser.pp$4.raise (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:2778:13)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:831:16)
    at Parser.pp$1.parseBlock (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1145:23)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:825:34)
    at Parser.pp$1.parseIfStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:965:26)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:814:31)
    at Parser.pp$1.parseBlock (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1145:23)
    at Parser.pp$1.parseTryStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1041:21)
    at Parser.pp$1.parseStatement (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:818:32)
    at Parser.pp$1.parseBlock (C:\emsdk\upstream\emscripten\third_party\acorn\dist\acorn.js:1145:23) {
  pos: ?[33m2136?[39m,
  loc: Position { line: ?[33m61?[39m, column: ?[33m6?[39m },
  raisedAt: ?[33m2142?[39m
}
emcc: error: 'C:/emsdk/node/12.9.1_64bit/bin/node.exe C:\emsdk\upstream\emscripten\tools\acorn-optimizer.js C:\...\bin\physics.worker.js minifyWhitespace' failed (1)
```

Looks like it is complaining about this line in the outputted "bin/file.worker.js" file:
```
      import(e.data.urlOrBlob).then(function(Module) {
        return Module.default(Module);
      }).then(function(instance) {
        Module = instance;
        postMessage({ 'cmd': 'loaded' });
      });
```

**Comment by kripken** [comment]
This may be a bug in acorn, but more likely either our emitted code is wrong or we need to upgrade it.

**Comment by kuhlmannmarkus** [comment]
Same here...

**Comment by kripken** [comment]
https://github.com/emscripten-core/emscripten/pull/11435 upgraded acorn, and is in `emsdk install tot` so that might be worth trying.

If that doens't fix it, then as the tags say, we'd be happy to help someone that has time to look into this. Starting by reading the emitted code might be a good starting point. Let us know if you have emscripten-specific questions we can help with, if someone looks at it.

**Comment by kuhlmannmarkus** [comment]
#11435 unfortunately did not solve the issue.

**Comment by RReverser** [comment]
I'm running into this as well. Acorn has dynamic import support since 7.0.0, and Emscripten already uses 7.3.1, so on that side of things it's already progressed far enough since the issue was opened.

However, dynamic import is a feature of ES2020 and #11435 - the last update - only set `ecmaVersion` to `2018`. It will need to be bumped again for this to work.

Also note that in Acorn 8.0.0 we have added `ecmaVersion: "latest"` support for cases where caller just wants all the latest features and doesn't care about specific target. Not sure if Emscripten falls into this category of clients, but if it does, might be worth bumping to it instead.

**Comment by sbc100** [comment]
> Also note that in Acorn 8.0.0 we have added `ecmaVersion: "latest"` support for cases where caller just wants all the latest features and doesn't care about specific target. Not sure if Emscripten falls into this category of clients, but if it does, might be worth bumping to it instead.

I think we would want that that as long as acorn didn't introduce new language constructs.   As of today we still output ES5 and we wouldn't want anything more recent to sneak into the output.  Assuming acorn won't do this I think using "latest" here is fine.

**Comment by RReverser** [comment]
> I think we would want that that as long as acorn didn't introduce new language constructs. As of today we still output ES5 and we wouldn't want anything more recent to sneak into the output.

I'm not sure what you mean by that. Acorn is just a parser, so it can gain support for mew language constructs, but it can't output or generate anything.

**Comment by RReverser** [comment]
Btw, I saw this comment too when searching for `ecmaVersion`: https://github.com/emscripten-core/emscripten/blob/270f795c0492d681b55de89f9888cf577be9d4fc/tools/building.py#L1005-L1006

If we change Acorn to `latest`, then that one can similarly be set to `ECMASCRIPT_NEXT`.

**Comment by RReverser** [comment]
Re-opening, as apparently the ES version bump wasn't enough. Now there are problems with AST conversion to Terser:

```
C:\Users\me\Documents\emsdk\upstream\emscripten\third_party\terser\terser.js:8314
        var ret = node != null ? MOZ_TO_ME[node.type](node) : null;
                                                     ^

TypeError: MOZ_TO_ME[node.type] is not a function
    at from_moz (C:\Users\me\Documents\emsdk\upstream\emscripten\third_party\terser\terser.js:8314:54)
    at Object.MemberExpression (C:\Users\me\Documents\emsdk\upstream\emscripten\third_party\terser\terser.js:7595:30)
    at from_moz (C:\Users\me\Documents\emsdk\upstream\emscripten\third_party\terser\terser.js:8314:54)
    at Object.From_Moz_CallExpression [as CallExpression] (eval at map (C:\Users\me\Documents\emsdk\upstream\emscripten\third_party\terser\terser.js:8300:21), <anonymous>:5:13)
...
```

**Comment by RReverser** [comment]
But also, wait, why do we need both Terser *and* Closure? That seems a bit suboptimal?

**Comment by kripken** [comment]
> But also, wait, why do we need both Terser and Closure?

Do you mean in general?

We don't use terser for minification. In `tools/acorn_optimizer.js` it's used to convert an acorn AST to JS (so it's in support of the passes in that file, which are almost all not minification-related). Maybe there's a better way or simpler tool for that? I remember I couldn't find one at the time.

**Comment by RReverser** [comment]
@kripken Ah, that's what I thought after looking at the code. Yeah, there is https://github.com/estools/escodegen which, among other ESTree tools in that org, was created specifically as a simple AST-to-JS generator. It should be both simpler and much faster than going via all Terser's conversions.

**Comment by RReverser** [comment]
Raised a tracking issue: https://github.com/emscripten-core/emscripten/issues/12410
