### ISSUE TITLE
Touch events break on iOS 13.5

### ISSUE THREAD

**Issue by szilardszaloki** [emscripten-core/emscripten#11308]
A callback registered via e.g. `emscripten_set_touchstart_callback()` doesn't get called the second time when a double tap occurs. The default double tap zoom is triggered though (which seemingly cannot be suppressed).

**Browsers failed:**
- Safari
- Chrome (83.0.4103.88)
- Firefox (26.0)
- Opera touch (2.3.2)

**Browsers passed:**
- Edge (45.4.11)

On Edge, the callback is called, along with the default double tap zoom.

Minimal example:
```
#include <iostream>
#include <emscripten/html5.h>

EM_BOOL touch_callback(int, EmscriptenTouchEvent const*, void*) {
    static int i = 0;
    std::cout << ++i << std::endl;
    return EM_FALSE;
}

int main(int const, char const* const []) {
    emscripten_set_touchstart_callback("#canvas", nullptr, 1, touch_callback);
    return 0;
}
```
_em++ main.cpp -o touch_test.html
emrun --no_browser touch_test.html_

**Comment by szilardszaloki** [comment]
Actually the first tap blocks any gestures (pan, swipe, etc. and not just a second tap) on the canvas for ~500 ms.

**Comment by szilardszaloki** [comment]
Hi @kripken,
Calling `preventDefault()` on the touch event (`return EM_TRUE;`) fixes the issue. I doubt that this should be the universal solution though...

**Comment by ericoporto** [comment]
@szilardszaloki did you find a better fix?
