### ISSUE TITLE
Bug in page:Interacting with code - Example provided don't work. 

### ISSUE THREAD

**Issue by tiagoquin** [emscripten-core/emscripten#11314]
The example provided to work with CPP in Nodejs doesn't work.
By following the instruction you get:

`RuntimeError: abort(Assertion failed: you need to wait for the runtime to be ready (e.g. wait for main() to be called)) at Error`

For some reason explained in the FAQ (which, as a beginner I don't understand: by following it I could not figure out how to make it work)

and also:

`RuntimeError: abort('ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)) at Error`

For not having `-s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'`  in the build command I guess.

Maybe I'm totally missing something, in this case sorry, first time playing with it ^^'

URL: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-an-api-written-in-c-c-from-nodejs

**Comment by kripken** [comment]
Thanks @tiagoquin ! Yes, looks like that example is broken, sorry about that...

Fixes in #11335, please test it if you can.
