### ISSUE TITLE
SIMDe Integration

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#11311]
We would like to build on @juj's work with the SSE headers by distributing [SIMDe](https://github.com/nemequ/simde) with Emscripten and making parts of it automatically available to users when (and only when) they pass the appropriate compiler flags like `-msse`. There are a few things to figure out about how we can do that.

1. How should SIMDe be pulled into the Emscripten distribution? Git submodules? Source dump? The emscripten-releases rollers? How frequently should it be updated? On a related note, what kind of testing do we want to have in Emscripten? @kripken @sbc100 @dschuff it would be great to get your thoughts on this.

2. How should SIMDe be exposed to users? Our goals are slightly different from upstream SIMDe's goals because we want users to have to opt in to each set of intrinsics using compiler flags, we don't want to expose the `simde_` prefix, we don't want users to need to change their code at all, and we never want to expose scalar emulation paths. Having custom Emscripten headers that contain logic to wrap the SIMDe headers would be a reasonable way to do this, but other methods might be possible as well. I'll defer the details to @seanptmaher. cc @ngzhian.

This issue is a fork of the Emscripten-specific parts of the discussion at https://github.com/nemequ/simde/issues/86.

**Comment by sbc100** [comment]
I sounds have a lot any submodule use.. so I would say either just check-in a copy of the headers, or maybe use a port (tools/ports).

**Comment by tlively** [comment]
These questions have all been settled.
