### ISSUE TITLE
error while converting c++ , use of undeclared identifier in mmintrin.h

### ISSUE THREAD

**Issue by ankitcsr** [emscripten-core/emscripten#11321]
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:33:5: note: '__builtin_isless' declared here
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:50:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:67:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:129:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:159:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:189:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:216:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:239:19: error: use of undeclared identifier '__builtin_ia32_punpckhwd'
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:260:19: error: use of undeclared identifier '__builtin_ia32_punpckhdq'
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:287:19: error: use of undeclared identifier '__builtin_ia32_punpcklbw'
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:310:19: error: use of undeclared identifier '__builtin_ia32_punpcklwd'
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:331:19: error: use of undeclared identifier '__builtin_ia32_punpckldq'
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:352:19: error: use of undeclared identifier '__builtin_ia32_paddb'
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:373:19: error: use of undeclared identifier '__builtin_ia32_paddw'
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:394:19: error: use of undeclared identifier '__builtin_ia32_paddd'
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:416:19: error: use of undeclared identifier '__builtin_ia32_paddsb'
    return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:439:19: error: use of undeclared identifier '__builtin_ia32_paddsw'
    return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/Documents/emsdk/upstream/lib/clang/11.0.0/include/mmintrin.h:461:19: error: use of undeclared identifier '__builtin_ia32_paddusb'
    return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);

**Comment by sbc100** [comment]
mmintrin.h is a header for x86 intrinsics.      You probably don't want to be including it when building for emscripten. 

As it happens we are in the process of implementing a translation layer to wasm simd, but you probably don't what that right now either because that depends on simd in the runtime which is not yet available in browser by default.

Solution: find the source file that is including this header and have it do something else instread
