### ISSUE TITLE
Target feature 'atomics' used in hb-buffer.cc.o is disallowed

### ISSUE THREAD

**Issue by HellOInDec** [emscripten-core/emscripten#11326]
Hi, I'm trying to compile my project with USE_HARFBUZZ=1 and USE_PTHREADS=1, and thie issue happened when compilong harfbuzz:
![image](https://user-images.githubusercontent.com/1794321/83614874-5f520e00-a5b8-11ea-9ec5-e29b8309199b.png)
Is there anything I missed?

**Comment by kripken** [comment]
It sounds like `Particles.cpp` was compiled without pthreads support. Perhaps the `USE_PTHREADS` flag only reached some of the files being compiled? Verifying with `make VERBOSE=1` or such can help.
