### ISSUE TITLE
I would like to build telnet client.

### ISSUE THREAD

**Issue by kismp123** [emscripten-core/emscripten#11325]
As title I would like to build telnet client. 
It must run on browser like javascript. ( this is why I wrote here )
Is this possible with WebAssembly?

Thanks

**Comment by juj** [comment]
It is possible, but you will need to use some kind of WebSockets->native sockets translation, since browsers do not allow direct access to TCP sockets. Check out e.g. https://emscripten.org/docs/porting/networking.html#full-posix-sockets-over-websocket-proxy-server and https://github.com/emscripten-core/emscripten/tree/master/tools/websocket_to_posix_proxy

**Comment by kismp123** [comment]
thanks man
you made my future :)

**Comment by kismp123** [comment]
Can I ask you again how to build? 
I'm doing build you gave me
https://github.com/emscripten-core/emscripten/tree/master/tools/websocket_to_posix_proxy

but I have some problem.
First I tried.
```
>emcc main.cpp sha1.cpp socket_registry.cpp websocket_to_posix_proxy.cpp
In file included from main.cpp:12:
./socket_registry.h:10:55: error: unknown type name 'SOCKET_T'
void TrackSocketUsedByConnection(int proxyConnection, SOCKET_T usedSocket);
                                                      ^
```

I thought it needs header files 
```
>emcc -include *.h main.cpp sha1.cpp socket_registry.cpp websocket_to_posix_proxy.cpp
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: error: cannot specify -o when generating multiple output files
```

I thought again "should I use em++?"
```
>em++ -include *.h main.cpp sha1.cpp socket_registry.cpp websocket_to_posix_proxy.cpp
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++: error: cannot specify -o when generating multiple output files
```

so I found how to use cmake 
```
>emcmake cmake -DHYBUILD_Emscripten=ON ..
configure: cmake -DHYBUILD_Emscripten=ON .. -DCMAKE_TOOLCHAIN_FILE=C:\emsdk-master\upstream\emscripten\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="C:/emsdk-master/node/12.9.1_64bit/bin/node.exe"
-- Could NOT find Threads (missing: Threads_FOUND)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Desktop/webAssembly/src
```

However there is no any js or html file :(
Can I ask you how to build? 

Thank you.

**Comment by yylittlefish** [comment]
Hi, @kismp123 
have you fixed this issue? does your client running well?
I built websocket_to_posix_proxy and it could running well,
but when I calls  "emscripten_init_websocket_to_posix_socket_bridge" and "emscripten_websocket_get_ready_state" api to connect with it, it always not ready, could you help me, please?
