### ISSUE TITLE
WebGPU WGPUBlendDescriptor sampleMask causes assertion

### ISSUE THREAD

**Issue by cwoffenden** [emscripten-core/emscripten#11343]
Building as debug a simple WebGPU example now dies with:

```
Uncaught (in promise) TypeError: Failed to execute 'createRenderPipeline' on 'GPUDevice': Value is outside the 'unsigned long' value range.
```
On this line:

https://github.com/emscripten-core/emscripten/blob/d976153f66378598f127de6438baf0d26696462f/src/library_webgpu.js#L935

`sampleMask` is `-1` (and not the expected `0xFFFFFFFF`, which is currently the only accepted value in Chrome Canary). The `SAFE_HEAP_LOAD` is requesting an unsigned and does return the expected `4294967295`. The `|0` is resulting in a signed value (and removing it doesn't trigger the assert).

Offending line here in a simple example:

https://github.com/cwoffenden/hello-webgpu/blob/6729f858d0088b6a8df122d882066730d26f1234/src/main.cpp#L222

(But any code setting the `sampleMask` should trigger the same)

**Comment by kainino0x** [comment]
Thanks for the report; will look into it!

**Comment by cwoffenden** [comment]
To clarify, the debug build was with `ASSERTIONS=2`.

**Comment by kainino0x** [comment]
The `|0` is injected specifically by SAFE_HEAP=1. @kripken am I holding `makeGetValue` wrong? (`makeGetValue(struct, offset, 'i32', false, true)`)

**Comment by kripken** [comment]
@kainino0x Ah, that looks like a bug... quite old actually, but never noticed til now. Fix in #11748

**Comment by kainino0x** [comment]
Thanks! That should be all that's needed for this bug.

**Comment by cwoffenden** [comment]
Fixed!
