### ISSUE TITLE
install.py installs a lot of clutter

### ISSUE THREAD

**Issue by svenstaro** [emscripten-core/emscripten#11358]
I think `install.py` could be improved in that it currently installs a ton of stuff that could be considered clutter:

```
.circleci/
.circleci/config.yml
.clang-format
.editorconfig
.flake8
.gitattributes
.github/
.github/config.yml
.github/stale.yml
.github/workflows/
.github/workflows/archive.yml
.gitignore
```

And also arguably it shouldn't install .bat files on Linux.

**Comment by sbc100** [comment]
Thanks for the feedback.  Lets fix all those issue.   If you'd like to file a PR it would be most welcome, otherwise I'll try to get around to it.

And thanks for trying to out this new install method.

It sounds like we should probably skip all files that start with `.`?

**Comment by svenstaro** [comment]
Turns out that this is already kind of being handled in `install.py` but it seems buggy as it doesn't work. I suggest using [copytree](https://docs.python.org/3/library/shutil.html#shutil.copytree) as it has ignore functionality built-in. I don't have time to fix this myself, I'm afraid.
