### ISSUE TITLE
Should building with WASM=2 automatically fallback to JS when WebAssembly is undefined?

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#11357]
I read that in version 1.39.7

> - Added new linker option -s WASM=2 which produces a dual Wasm+JS build, which
  falls back to using a JavaScript version if WebAssembly is not supported in
  target browser/shell. (#10118)

Which is very interesting to us. When I build with this option (using 1.39.13) I get following output:

  * `{TARGET}.js`
  * `{TARGET}.wasm`
  * `{TARGET}.wasm.js`
  * `{TARGET}.js.mem`

Where I assume `{TARGET}.js` is the file I load and then should handle the fall back if needed. But looking at the source code of `{TARGET}.js` I can nowhere see this fallback mechanism and if I write
`WebAssembly = undefined` before loading `{TARGET}.js` I get a type error that

> TypeError: WebAssembly.Table is not a constructor 

For completeness here the other link options we use:
```
    "SHELL:-s ALLOW_MEMORY_GROWTH=1"
    "SHELL:-s DISABLE_EXCEPTION_CATCHING=0"
    "SHELL:-s ENVIRONMENT=worker"
    "SHELL:-s EXTRA_EXPORTED_RUNTIME_METHODS=\"['stringToUTF8']\""
    "SHELL:-s FETCH=1"
    "SHELL:-s FORCE_FILESYSTEM=1"
    "SHELL:-s LZ4=1"
    "SHELL:-s NO_EXIT_RUNTIME=1"
    "SHELL:-s WARN_ON_UNDEFINED_SYMBOLS=1"
    "SHELL:-s WASM=2"
    --bind
    --cache ${CMAKE_BINARY_DIR}/emscripten_cache
    --post-js ${output_native}
    --pre-js ${PROJECT_BINARY_DIR}/pre.js
    -lidbfs.js
```

**Comment by juj** [comment]
The fallback is implemented in the output a.html file:
```
          function loadMainJs() {

          var script = document.createElement('script');
          script.src = "a.js";
          document.body.appendChild(script);

          }
          if (!window.WebAssembly) {
            // Current browser does not support WebAssembly, load the .wasm.js JavaScript fallback
            // before the main JS runtime.
            var wasm2js = document.createElement('script');
            wasm2js.src = 'a.wasm.js';
            wasm2js.onload = loadMainJs;
            document.body.appendChild(wasm2js);
          } else {
            // Current browser supports Wasm, proceed with loading the main JS runtime.
            loadMainJs();
          }
```
If you are outputting to .js, then choosing the right JS file - a.js or a.wasm.js to load, will fall to user.
