### ISSUE TITLE
WebGPU js library error

### ISSUE THREAD

**Issue by manhnt9** [emscripten-core/emscripten#11359]
When inserting this code to my HTML:
```html
    <script async type="text/javascript" src="library_webgpu.js"></script>
```
I have this error on Browser console:
`Uncaught SyntaxError: expected property name, got '{'library_webgpu.js:176:14`

Browser info:
- Firefox nightly 79.0a1 (2020-06-03) (64-bit) (Ubuntu 20.04)
- WebGPU enabled (I can run WebGPU demos)

**Comment by manhnt9** [comment]
Without linking the `library_webgpu.js`, my build has error:
```javascript
Uncaught ReferenceError: WebGPU is not defined
    JS_wgpu_init http://localhost/bin/01_window.js:1930
    _main http://localhost/bin/01_window.js:5297
    callMain
```

**Comment by kainino0x** [comment]
library_webgpu.js is not actually a plain JavaScript file - it is not meant to be sourced from the browser. Instead, it's part of Emscripten's templates for JavaScript generation - if you have `-s USE_WEBGPU=1`, it automatically uses it to generate code included in your build's resulting `.js` file.

**Comment by manhnt9** [comment]
I'm still having `Uncaught ReferenceError: WebGPU is not defined` while using `-s USE_WEBGPU=1`. Could this be an Emscripten's bug? How do I investigate this further?

**Comment by manhnt9** [comment]
Thanks @kainino0x. I've successfully init WebGPU using your suggestions!
CC: @floooh.

**Comment by floooh** [comment]
@manhnt9 I'm doing the WebGPU device and swapchain setup with mixed Javascript and C code (all the async setup is done in a JS function called from C code, and at the end of the async-callback chain there's a C function "_sapp_emsc_wgpu_ready" called which communicates all the setup object handles back to the C side. The C checks each frame if the asynchronous Javascript setup has completed before advancing.

This is the JS setup function: https://github.com/floooh/sokol/blob/d3e1c1065bdf13c436d63eb885ffa77e8d091948/sokol_app.h#L2986-L3008)

And this is the "statemachine switch-case" in the frame callback which waits until the initialization on the Javascript side has completed:

https://github.com/floooh/sokol/blob/d3e1c1065bdf13c436d63eb885ffa77e8d091948/sokol_app.h#L3129-L3148

**Comment by manhnt9** [comment]
Yeah, Since Kai pointed out that WebGPU object should not be used directly, I tagged you for the notice.

**Comment by kainino0x** [comment]
Using the WebGPU object may be technically okay (although in theory you should not need it). I was concerned that it would break due to minification (maybe with closure compiler optimizations). However even if it does work, please avoid using it if possible as it is not considered to have a stable API (and will definitely break in the future).
