### ISSUE TITLE
How to determine a image bits per pixel?

### ISSUE THREAD

**Issue by ValSergey** [emscripten-core/emscripten#11373]
Hello.
I use sdl2. 
 SDL_Surface *s = loadsurface(file);
 s->format->BitsPerPixel == 32 //   IS ALWAYS ?!!!

**Comment by sbc100** [comment]
Haven't you answered you own question there?     isn't the bit per pixel given by that member variable?

Give that that the member exists, it seems like it must be possible to differ per `SDL_Surface` otherwise it would not be member at all.

Perhaps I'm misunderstanding your question?

**Comment by ValSergey** [comment]
Ok.
I have RGB texture (tex.png)
__
SDL_Surface *s = loadsurface(file);
---------------OpenGL ES 3.0----------------
int bpp = s->format->BitsPerPixel; // bpp == 24 (RGB)
--------------WebGL 2--------------------------------
int bpp = s->format->BitsPerPixel; // bpp == 32 (RGBA)

**Comment by ValSergey** [comment]
loadsurface is IMG_Load(fileName);

Can  /tools/file_packager.py change files?
---------------------------
when use --embed-file image/        s->format->BitsPerPixel;  work ok

**Comment by ValSergey** [comment]
With --use-preload-plugins, the files are decoded using the browser’s image decoder,  and he change internal format on RGBA
