### ISSUE TITLE
generated .bc file starts with  \0asm

### ISSUE THREAD

**Issue by reak998** [emscripten-core/emscripten#11388]
The doc* mentions that the .bc files should start with BC. However I see  \0asm when I open them.
I checked with make VERBOSE=1 and em++ is used to generate them.

To reproduce the problem:
```
git clone git@github.com:bulletphysics/bullet3.git;
cd bullet3; mkdir build; cd build
emcmake cmake .. -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1 -DEMSCRIPTEN_FASTCOMP=1
emmake make  VERBOSE=1 LinearMath 
hexdump -c ./src/LinearMath/libLinearMath.bc | head -n 1
```

* https://emscripten.org/docs/compiling/Building-Projects.html

**Comment by raysan5** [comment]
Just updated to emscripten 2.0.4 upstream and now when I try to generate `libraylib.bc` it automatically generates `libraylib.js` + `libraylib.wasm`. I use a `Makefile` for all platforms where I compile the different units and at the end I generate the library archive; I get the following warning:
```
emcc -O1 core.o shapes.o textures.o text.o utils.o models.o raudio.o -o libraylib.bc
emcc: warning: generating an executable with an object extension (.bc).  If you meant to build an object file please use `-c, `-r`, or `-shared` [-Wemcc]
```
I also tried generating `libraylib.a` as listed in [Building Projects](https://emscripten.org/docs/compiling/Building-Projects.html#emscripten-build-output-files), in that case I got no warning, but same result: `libraylib.js` + `libraylib.wasm`.

What is the new way to generate a wasm library for further "linkage" with the program?

**Comment by kripken** [comment]
I believe this is from @sbc100 's recent changes.

Does adding `-r` or `-shared` as the quoted warning suggests fix things? Those should make it generate a library file you can then statically link.

@sbc100 do we need to update the Building Projects docs perhaps?

**Comment by sbc100** [comment]
Hi @raysan5, sorry for the disruption.  I think the correct fix for you is going to be to use a `.a` archive.

To build and archive you use`emar` command.  See `https://man7.org/linux/man-pages/man1/ar.1.html`.   e.g. `emar rcs libfoo.a obj1.o obj2.o`

**Comment by raysan5** [comment]
@kripken @sbc100 thank you very much for the quick answer! I tested the `-r` and `-shared` options but don't work:
```
emcc -O2 core.o shapes.o textures.o text.o utils.o models.o raudio.o -shared libraylib.bc
emcc: error: libraylib.bc: No such file or directory ("libraylib.bc" was expected to be an input file, based on the commandline arguments provided)
```
Using `emar` to generate `libraylib.a` works perfectly.

**Comment by sbc100** [comment]
If you use `-shared` or `-r` you still need the `-o` before the output filename.

**Comment by raysan5** [comment]
@sbc100 Oh! Thank you very much! It worked:
```
emcc core.o shapes.o textures.o text.o utils.o models.o raudio.o -r -o libraylib.bc
```

**Comment by sbc100** [comment]
Using libraylib.a is still the recommended way.   Linking `-r` and/or `-shared` is somewhat unusual and should not be needed.

Also, you probably want to avoid the `.bc` suffix these days in favor of just `.o`.
