### ISSUE TITLE
Error while building in Arch Linux

### ISSUE THREAD

**Issue by Srinivasa314** [emscripten-core/emscripten#11387]
Even for a simple file containing empty main function, the following error is displayed
```
Fatal: Module::addExport: stackSave already exists
```

**Comment by Srinivasa314** [comment]
The issue is not there in the git version of binaryen

**Comment by svenstaro** [comment]
@sbc100 thanks for the hint but how do I get the particular version of binaryen that belongs to a specific emscripten release?

**Comment by sbc100** [comment]
I'm afraid that has always been true.  Emscripten releases are tested against specific revisions of llvm and binaryen, so just picking a major version can lead to incompatibilities.  

It can sometimes work to pick the nearest version but that is not how we expect people to do it and its not how emsdk works.

For llvm there are plans to possibly start maintaining compatibility with major versions: #10818 

Sadly this means its best not use normal package dependencies for these but build specific versions and embed those in the emscripten package.   I get that this is not very friendly to packaging and might be one of the reasons why we have had issues with packaging emscripten over time.

**Comment by Shachlan** [comment]
This also happens to me on MacOS.

**Comment by sbc100** [comment]
Same issue, binaryen version needs to match emscripten releases.

For now, I recommend using emsdk rather than homebrew to make sure your versions all match.

**Comment by Shachlan** [comment]
@sbc100 I want to run emscripten tests locally, to test a change to emscripten. Can that be done via emsdk? If not, how can I find the correct Binaryen version?

**Comment by sbc100** [comment]
The is an FAQ entry for that but it actually looks out of date: https://github.com/emscripten-core/emsdk#how-do-i-use-my-own-emscripten-github-fork-with-the-sdk

The easiest way is simply to install the latest emsdk and active it .. it should set EM_CONFIG in your environment to point to the emsdk config file.    Then you can just use you local copy of emcc and it will see the emsdk config and get the other tools from there.

If you run `./tests/runner.py` it will always use the local emcc that lives alongside the tests directory.

**Comment by svenstaro** [comment]
Let's close this.

**Comment by Shachlan** [comment]
Opened https://github.com/emscripten-core/emscripten/issues/11455 for my issue.

**Comment by svenstaro** [comment]
@sbc100 can you close this?
