### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'dst.entries')

### ISSUE THREAD

**Issue by Shyiy** [emscripten-core/emscripten#11395]
I've got dozens of reports from different users on multiple devices encountering this error. Interestingly enough, this seems to happen only on Mobile Safari (iOS) while all other browsers and operating systems work fine.

The error comes from https://github.com/emscripten-core/emscripten/blob/master/src/library_idbfs.js (reconcile() function) and is caused by `dst` being undefined when the line is evaluated.

I run an emscripten-compiled WebAssembly application in a (blob) WebWorker.

Is it possible that maybe there are some race conditions for accessing the database which are not yet correctly covered by the emscripten js code? It would be nice if this is handled and maybe retried if it happens. Looking around how the `reconcile()` function is used (`syncfs`, `getLocalSet` and `getRemoteSet`) it seems to me like in addition to checking if `err` is present, `src` and `dst` should be checked for presence as well in case something else went wrong but there's no error object?

**Comment by kripken** [comment]
Sounds worth trying, definitely.

One option might be to ship that to your users and see if it improves things. Another option is to open a PR here and we can discuss in more detail those possible changes.

**Comment by Shyiy** [comment]
I could come up with an easy modification to just check if `dst` is undefined and fail accordingly and I'm confident that would work, however ideally the full fix should ideally implement the previously mentioned retry as I believe it would be expected for synchronization to eventually succeed transparently if there's a temporary problem. Would you agree that this mechanism should be part of the emscripten code or is it something that should be handled externally as a consequence of a (with a smaller new fix, simply "correctly failing") FS.syncfs call? I currently don't feel too confident and knowledgeable around the whole FS and indexedDB system...

In the meantime I'll see if I can easily reproduce the issue and check if some form of retry can be expected to work.

**Comment by Shyiy** [comment]
Small update:

I previously reported that in my case in some scenarios there were possibly two instances running and thus accessing indexedDB and causing a race condition, but this is actually unrelated as this issue appeared already before that was possible (so, only when a single instance was running and no race condition). Note also that I have logic in place around my calls to `FS.syncfs` to ensure that only at maximum one operation is running at some point in time.
