### ISSUE TITLE
libwesocket issue

### ISSUE THREAD

**Issue by wurc** [emscripten-core/emscripten#11396]
when I try to build libwebsocket using emscripten
below error pop up,
wrc@wrc-OptiPlex-7010:~/wasm_study/AirPlay_Video_SDK/AirPlay_Video_SDK_2.3.1f1/AirPlayVideoSDK-2.3.1-f.1/libwebsockets/build$ emmake make
make: make
[  0%] Built target GENHDR
[ 45%] Built target websockets
[ 46%] Linking C shared library libwebsockets.so
****emcc: error: Assuming object file output in the absence of `-c`, based on output filename. Add with** `-c` or `-r` to avoid this warning [-Wemcc] [-Werror]**

**Comment by sbc100** [comment]
Can you build with VERBOSE=1 (or with ninja rather than make) so we can see the command that fails?

**Comment by wurc** [comment]
@sbc100

**Comment by wurc** [comment]
I have fixed this issue with below steps
1.git clone https://github.com/warmcat/libwebsockets.git
2.cd libwebsockets/
3.mkdir build
4.cd build
5.emmake cmake .. -DLWS_WITHOUT_EXTENSIONS=1 \
                             -DLWS_WITH_SSL=0 \
                             -DLWS_WITH_ZLIB=0 \
                             -DLWS_WITH_ZIP_FOPS=0 \
                             -DLWS_WITH_SERVER_STATUS=1 \
                             -DLWS_WITH_SHARED=0 \
                             -DLWS_WITHOUT_TESTAPPS=1 \
                             -DLWS_WITHOUT_TEST_SERVER=1 \
                             -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=1 \
                             -DLWS_WITHOUT_TEST_PING=1 \
                             -DLWS_WITHOUT_TEST_CLIENT=1
6.emmake make

**Comment by wurc** [comment]
I have fixed this issue with below steps
