### ISSUE TITLE
TTF_RenderText_Solid leaking memory

### ISSUE THREAD

**Issue by marc40000** [emscripten-core/emscripten#1139]
Hi !

In my main iteration function I call TTF_RenderText_Solid() to render text. Afterwards I call SDL_FreeSurface() to free it again. However, after a few hundred iterations, I get this:

Cannot enlarge memory arrays in asm.js. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value, or (2) set Module.TOTAL_MEMORY before the program runs.:
abort@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:495
enlargeMemory@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:743
Runtime.staticAlloc@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:477
_malloc@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:2725
SDL.makeSurface@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:1780
_TTF_RenderText_Solid@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:2608
aV@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:2777
a1@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:2777
Runtime.dynCall@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:402
Browser.mainLoop.runner@file:///C:/meinedat/projects/emscripten/testprojects/Game/Emscripten/Release/Game.html:2680

It runs fine if I comment out the text rendering. So I guess SDL_FreeSurface() doesn't undo everything that is done by TTF_RenderText_Solid(). However, according to the example in sdl docu here http://sdl.beuc.net/sdl.wiki/SDL_ttf_Functions_Render_TTF_RenderText_Solid it looks like it should be enough.

**Comment by sketchin2** [comment]
-o "C:\meinedat\projects\emscripten\testprojects\Game\Emscripten\Debug\Game.html" -
