### ISSUE TITLE
WGPU could not create attachment due to lack of resolveTarget

### ISSUE THREAD

**Issue by manhnt9** [emscripten-core/emscripten#11404]
I'm having an exception when running WebGPU.

![Screenshot_2020-06-12_16-40-26](https://user-images.githubusercontent.com/11463928/84489298-ab453700-accb-11ea-99f5-e85c31b482f3.png)

When clicking on `makeColorAttachment`, it leads me to the point where the assertion fails:

![Screenshot_2020-06-12_16-40-46](https://user-images.githubusercontent.com/11463928/84489340-c2842480-accb-11ea-8174-d080dd0324bc.png)

It indicates that resolveTarget member is not valid.

My parameters when creating attachment descriptor:
![Screenshot_2020-06-12_16-41-20](https://user-images.githubusercontent.com/11463928/84489372-d3cd3100-accb-11ea-8480-1cf1dc984863.png)

According to the [spec](https://gpuweb.github.io/gpuweb/#dom-gpurenderpasscolorattachmentdescriptor-resolvetarget):
```
resolveTarget, of type GPUTextureView

    A GPUTextureView describing the texture subresource that will receive the resolved output for this color attachment if attachment is multisampled.
```

In this case I don't enable MSAA texture sampling. I'm not sure why resolveTarget is required here.

In `library_webgpu.js` code template:
```javascript
  wgpuCommandEncoderBeginRenderPass: function(encoderId, descriptor) {
    {{{ gpu.makeCheck('descriptor') }}}

    function makeColorAttachment(caPtr) {
      var loadValue = WebGPU.LoadOp[
          {{{ gpu.makeGetU32('caPtr', C_STRUCTS.WGPURenderPassColorAttachmentDescriptor.loadOp) }}}];
      if (loadValue === 'clear') {
        loadValue = WebGPU.makeColor(caPtr + {{{ C_STRUCTS.WGPURenderPassColorAttachmentDescriptor.clearColor }}});
      }

      return {
        "attachment": WebGPU.mgrTextureView.get(
          {{{ gpu.makeGetU32('caPtr', C_STRUCTS.WGPURenderPassColorAttachmentDescriptor.attachment) }}}),
        "resolveTarget": WebGPU.mgrTextureView.get(
          {{{ gpu.makeGetU32('caPtr', C_STRUCTS.WGPURenderPassColorAttachmentDescriptor.resolveTarget) }}}),
        "storeOp": WebGPU.StoreOp[
          {{{ gpu.makeGetU32('caPtr', C_STRUCTS.WGPURenderPassColorAttachmentDescriptor.storeOp) }}}],
        "loadValue": loadValue,
      };
    }
```

`resolveTarget` is always being read when creating color attachment, which is not correct as far as I could understand.

I think the library implementation should check whether `resolveTarget` is being used in the attachment descriptor before accessing it via `WebGPU.mgrTextureView.get`.

This `get` call is causing an exception as the browser reports, when it tries to find the texture view to use but it's not meant to be used at all since MSAA isn't involed.

**Comment by manhnt9** [comment]
Hi @kainino0x. Can you take a look at this issue? I think it's an Emscripten's bug.

**Comment by kainino0x** [comment]
Will do, sorry I haven't had a chance to work on these bugs yet but I will soon.

**Comment by manhnt9** [comment]
Thanks, it's nice to hear. Meanwhile I'll learn more about WebGPU :+1:

**Comment by kainino0x** [comment]
@manhnt9 I'm just revisiting this bug. Sorry I didn't look at your code earlier. The issue is that in your code, `resolveTarget` contains uninitialized data. So you need to either default initialize `colorAttDesc` (`colorAttDesc{}` or `colorAttDesc = {}`) or specify `colorAttDesc.resolveTarget = nullptr` or `colorAttDesc.resolveTarget = {}`.

**Comment by manhnt9** [comment]
@kainino0x I've tried that before but forgot to mention. Specifying `resolveTarget` to null will crash the tab with no reports on console, refreshing it will even crash the whole browser.

**Comment by manhnt9** [comment]
I'm gonna try on Chrome soon.

**Comment by manhnt9** [comment]
I installed Chrome dev linux but can't enable webgpu flag, it said Unavailable on your platform. I think only Chrome Canary has WGPU support which doesn't distribute Linux build.

**Comment by kainino0x** [comment]
It's available on Canary and Dev Channel, but only on Windows and Mac. It's on my plate to try to get it enabled on Linux.

**Comment by manhnt9** [comment]
> It's available on Canary and Dev Channel, but only on Windows and Mac. It's on my plate to try to get it enabled on Linux.

Cool, waiting for it.

Please take some time to review this again too.

And has this repo worked yet? https://github.com/kainino0x/webgpu-cross-platform-demo/

I reference to it when coding my C++ WGPU code.

**Comment by kainino0x** [comment]
I'm in the middle of updating it :) https://github.com/kainino0x/webgpu-cross-platform-demo/pull/4

> @kainino0x I've tried that before but forgot to mention. Specifying `resolveTarget` to null will crash the tab with no reports on console, refreshing it will even crash the whole browser.

Setting it to null explicitly should allow the JS code to continue past it, which means your crash is probably triggered by some later code.

Any WebGPU code crashing the browser is a browser bug (unless it's an out-of-memory, which is possible if you create a resource of undefined size). @kvark fyi

**Comment by kainino0x** [comment]
You can see what's happening in a firefox crash by going to about:crashes and opening the crash report, which includes a crash stack.

**Comment by kvark** [comment]
We are fully aware that invalid use of WebGPU can cause our GPU process to crash atm. We are working on it. Sorry about the inconvenience!

**Comment by manhnt9** [comment]
@kainino0x I tried commenting out the code after that. It crashes when sending the descriptor to API call. I'm getting "Invalid URL" when accessing "about:crashes".

I think for now I'll wait for what you'd have with your demo repo.

@kvark Thanks for the info mate!
