### ISSUE TITLE
Add inline alternative to command line ASYNC IMPORTS

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11402]
Lot of my manual leg work goes to copy pasting into ASYNC IMPORTS array in CMD and it would be better have something like EMSCRIPTEN_KEEPALIVE for ASYNC IMPORTS.

**Comment by sbc100** [comment]
One feature that might be of use is that you can specify a filename containing your list of imports:

`-s ASYNCIFY_IMPORTS=@filename.txt`

**Comment by gerald-dotcom** [comment]
> One feature that might be of use is that you can specify a filename containing your list of imports:
> 
> `-s ASYNCIFY_IMPORTS=@filename.txt`

Thanks. Will use it for now
