### ISSUE TITLE
When using EM with new Shell, EM ignore system libraries in cache

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11408]
I have a .bat file which build wasm in turn; however, the build process is slower because EM keep generating system libraries even when libs in cache. 

My bat file looks like this,

`@echo off

call C:\Users\Administrator\emsdk\emsdk activate latest
call C:\Users\Administrator\emsdk\emsdk_env.bat

............................. 

`

**Comment by sbc100** [comment]
Interesting.. this certainly shouldn't happen.

Can you post the output with EMCC_DEBUG=1 in your environment?    Also take a look at your `.emsceipten_sanity` file .. this gets generated each time you run.

Finally there was a bug that existed for a little while in this area and was fixed in: #11348, and I don't think that bug ever got shipped in a release.

**Comment by gerald-dotcom** [comment]
@sbc100  Please see attached DEBUG Output.

[Mon.txt](https://github.com/emscripten-core/emscripten/files/4782085/Mon.txt)

**Comment by gerald-dotcom** [comment]
"**.emsceipten_sanity**"  - no such a file can be located either in working dir or the emsdk dir

**Comment by sbc100** [comment]
Sorry.. there was a typo there: `.emscripten_sanity`

**Comment by sbc100** [comment]
Which libs in particular are continually being rebuilt?  All of them?

For  example do you see `generating system library: libcompiler_rt` every single time you build any program?

Can you run `emcc hello_world.c` and attach the output of running that two times.  If I understand correctly you will see `generating system library: libcompiler_rt` both times right?

**Comment by gerald-dotcom** [comment]
cache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "C:\Users\Administrator\.emscripten_cache\is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libcompiler_rt.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libcompiler_rt.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc-wasm.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libc-wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libc++.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc++abi.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libc++abi.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libembind-rtti.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libembind-rtti.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libfetch.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libfetch.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libdlmalloc.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libdlmalloc.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libpthread_stub.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libpthread_stub.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libc_rt_wasm.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libc_rt_wasm.a" for subsequent builds)
cache:INFO:  - ok
cache:INFO: generating system library: libsockets.a... (this will be cached in "C:\Users\Administrator\.emscripten_cache\wasm\libsockets.a" for subsequent builds)
cache:INFO:  - ok

**Comment by sbc100** [comment]
Hmm... looks like `C:\Users\Administrator.emscripten_cache` is missing a slash between `Administrator` and `.emscripten_cache`.. not sure if that would cause this problem but certainly worth fixing.

With the latest version of emscripten the cache should live in the emscripten directory itself.  Can you try upgrading to 1.39.18?

**Comment by sbc100** [comment]
Can you run with `EMCC_DEBUG=1` in the environment.   Specifically I'd like to see if the message `Using home-directory for emscripten cache due to read-only root` appears in the output ?

**Comment by gerald-dotcom** [comment]
> Can you run with `EMCC_DEBUG=1` in the environment. Specifically I'd like to see if the message `Using home-directory for emscripten cache due to read-only root` appears in the output ?

Mon.txt contain output of EMCC DEBUG = 1

**Comment by gerald-dotcom** [comment]
Upgraded to latest version and it build the wasm without printing cache:INFO

25 seconds total took to build.

**Comment by gerald-dotcom** [comment]
I didn't feel much difference either between build time. Looks so close.

**Comment by sbc100** [comment]
If you don't see the `cache:INFO` its not rebuilding then libraries.   You can run `emcc -v` for more information on what is taking the time.

Are you compiling your sources and linking in a single command?    Or is the 25 seconds just the link time?

**Comment by gerald-dotcom** [comment]
> If you don't see the `cache:INFO` its not rebuilding then libraries. You can run `emcc -v` for more information on what is taking the time.
> 
> Are you compiling your sources and linking in a single command? Or is the 25 seconds just the link time?

I just compile main.cpp with em++ with 0z optimization

**Comment by sbc100** [comment]
Sounds like the original issue no longer a problem.   Go ahead a close this issue if you agree.

**Comment by gerald-dotcom** [comment]
I agree.
