### ISSUE TITLE
invalid suffix on literal; C++11 requires a space between literal and identifier

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11414]
I have EMJS function with large minified JS code block yields around 5000 lines and when I complies, EM++ return invalid suffix on literal; C++11 requires a space between literal and identifier

I'm sure no one tried such a large code block inside EM_JS.

**Comment by sbc100** [comment]
There is probably something in your code block that needs to be escaped.

However, If you have a lot of JS code then its probably better to use `--library-js` to inject it, and then call that code from the EM_JS code block instead.

**Comment by gerald-dotcom** [comment]
> There is probably something in your code block that needs to be escaped.
> 
> However, If you have a lot of JS code then its probably better to use `--library-js` to inject it, and then call that code from the EM_JS code block instead.

I put unminified code block and now compiler issue "unterminated function-like macro invocation" 

I will look into library-js
