### ISSUE TITLE
std::cout doesn't output in an exported C++ function

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11418]
Issue is quite similar to this one https://github.com/emscripten-core/emscripten/issues/5823

I have exported a function using EMSCRIPTEN_KEEPALIVE and that function will output a string via std::cout but I was not able to see the output in the JS console. 

Tried to build using  -s NO_EXIT_RUNTIME=1 and -s ASSERTIONS=1; however, no errors and no output .

The exported function trigger at random times while main() is running. main() too has a lot of std::cout's.

All of my std::cout has << "\n" so that's not the case.

**Comment by kripken** [comment]
Can you provide the full testcase, so we can debug it? That does sound like a bug.

**Comment by gerald-dotcom** [comment]
@kripken  Absolutely impossible to share source code. Also, I don't use test cases for EM. Everything by hand till I become comfortable.

**Comment by gerald-dotcom** [comment]
Just saw  you referred another issue on the thread. Would that mean this is fixed?

**Comment by gerald-dotcom** [comment]
or do I have to follow his footsteps to get minimal example?

**Comment by kripken** [comment]
Sorry about the reference to this issue - it was a typo (off by one in the issue number - and no way to undo it in github, on this side).

Without a testcase I don't think we can figure this out here - there isn't enough information to get started. However, maybe you can debug it on your side.
