### ISSUE TITLE
emcc doesn't output anything

### ISSUE THREAD

**Issue by nicklowkc** [emscripten-core/emscripten#11423]
I am currently following the "Download and Install" tutorial from emscripten official website.
First, I couldn't find the emcc exe file even I have done all the required steps.
After then, I tried to download the emscripten zip from release pages. I tried to use emcc to generate a html page with hello world example, but I got nothing generated from emcc. Not even any errors messages that I can track what's happening.
My current development environments:
python 3.8(32-bit)
nodejs v10.15.3

It seems like emscripten only need those two installed, am I right?

**Comment by sbc100** [comment]
Can you print the full command you ran, along with its output?

Additioanlly you could run with `-v` on the command line or EMCC_DEBUG=1 in the environment to see more info.

**Comment by sbc100** [comment]
What does `which emcc` say?    

How about `sh -x \`which emcc\``?

**Comment by nicklowkc** [comment]
> What does `which emcc` say?
> 
> How about `sh -x $(which emcc)`?

Sorry that I didn't state on my previous comments. I am currently develop in Windows 10 so I guess the commands are different. 
By the way, it works perfectly in my mac book so I have no idea why. I will try it tonight on my windows 10 pc..

**Comment by sbc100** [comment]
What does `where emcc` say?

What shell are you using?

Take a look at emcc.bat.. all it does its run `python /path/to/emcc.py` .. its hard to see show it might not show anything.

**Comment by nicklowkc** [comment]
> What does `where emcc` say?
> 
> What shell are you using?
> 
> Take a look at emcc.bat.. all it does its run `python /path/to/emcc.py` .. its hard to see show it might not show anything.

It shows the following:
C:\emscripten\emcc
C:\emscripten\emcc.bat

I am using windows command prompt. The emcc.bat shows nothing though..

**Comment by sbc100** [comment]
It seems very strange that emcc.bat isn't working.  Can you try running emcc.bat explicitly (with the .bat extension)?

Also can you try running `python C:\emscripten\emcc.py` ?

I imagine you will need to install emsdk in the long run.. unless you plan on compiling llvm yourself?  So yeah you probably should use emsdk, but I'm curious as to what is going on here...

**Comment by nicklowkc** [comment]
![emcc](https://user-images.githubusercontent.com/3983799/85092821-8e59b800-b225-11ea-9b94-dc6481ba2e09.PNG)
This is the ouput for the commands. As you can see, it doesn't output anything. I can see the output message on mac though.

**Comment by kripken** [comment]
To debug this, I would add a line to `emcc.bat` for example to print something. That should check whether something is not totally broken in the OS. If that prints, then you can then start to add more, to see why it doesn't get to actually do anything.

If that prints nothing at all, you can try to write a new `.py` or `.bat` file from scratch that has just one print. If that works, then you can start to remove differences between the two files.

(If that doesn't print anything either, then something very basic would be wrong in your OS or in that shell.)

**Comment by sbc100** [comment]
What don't `where python` say?  What does `python -v` say?   Can you run python on its own?

**Comment by nicklowkc** [comment]
> What don't `where python` say? What does `python -v` say? Can you run python on its own?

where python outputs following
C:\Users\{Username}\AppData\Local\Microsoft\WindowsApps\python.exe

However, python -v doesn't output anything. I think the problem might be python installation...

**Comment by nicklowkc** [comment]
It seems like there was a problem with my python installation. After re-installing python, it solves the problem. Thank you guys for helping. For those who has the same problem, you have to uninstall python and re-install again.
Closing this issue..

**Comment by nicklowkc** [comment]
It seems like there was a problem with my python installation. After re-installing python, it solves the problem. Thank you guys for helping. For those who has the same problem, you have to uninstall python and re-install again.

**Comment by msemtd** [comment]
I think I can add some insight here: the Windows 10 May update broke my existing python install by installing a fake Python executable in my path that is supposed to launch Windows Store. It's a horrible hack and has caused a huge headache for IT admins worldwide. See https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/

**Comment by sbc100** [comment]
Sounds like we got the bottom of it.    The good news is that emsdk users won't be effected since we bundle our own python there.

Can this be closed now?

**Comment by nicklowkc** [comment]
> Sounds like we got the bottom of it. The good news is that emsdk users won't be effected since we bundle our own python there.
> 
> Can this be closed now?

Yes. Sorry for latte reply. 
Thank you for you guys help!
Closing this issue.
