### ISSUE TITLE
MEMFS unmounting multiple times

### ISSUE THREAD

**Issue by b-katt** [emscripten-core/emscripten#11420]
I can't seem to unmount a MEMFS mount dir multiple times. If I call: mount(), unmount(), mount() and unmount() again I get an error message in the last unmount() when using MEMFS.

I see: error properties: null({ node: undefined, setErrno: Function, errno: 28, code: 'EINVAL', constructor: Function })

**Comment by TroyTae** [comment]
Hello, @b-katt!
Now I write test code like this to re-produce this issue:
https://github.com/TroyTae/emscripten/blob/c1e1523f531ffa6432bec4bfb18cde1602adaaac/tests/fs/test_mount.c#L20-L53
But test is passed in my local test.
So can you explain me more detail?? (About code, environment, etc..)

**Comment by TroyTae** [comment]
ADD: CI tests also passed https://github.com/emscripten-core/emscripten/pull/11562

**Comment by sbc100** [comment]
@b-katt can you respond to #11562?  Any idea why we are not seeing the same failure that you are reporting? Are we doing something differently?

**Comment by sbc100** [comment]
Turns out this was a bug in the calling code.
