### ISSUE TITLE
Remove local fork of acorn JS parser

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11439]
We currently have a local fork of acorn in-tree, but it would be more elegant to simply install it via npm.

Apparently there is a local patch that upstream don't want but a suggested workaround exists #11435

**Comment by TroyTae** [comment]
Hello, I think you wanna delete `acornjs` code in `third_party` directory and add to package.json.
Is it correct?

**Comment by sbc100** [comment]
Yes, but also we have a local patch which contains functionality which we would like to preserve.    I believe @RReverser has suggested some way to get the desired behaviour without the local patch.

Thanks for the offer of help!

**Comment by TroyTae** [comment]
Can I ask a question?
First, I saw the history of built file of acorn(https://github.com/emscripten-core/emscripten/commits/master/third_party/acorn/dist/acorn.js)
But there is no changes.
So I saw the PR and I guess @kripken wanna add some error print. (https://github.com/acornjs/acorn/pull/793)
If I write about this issue, I'll wrap this line(https://github.com/emscripten-core/emscripten/blob/master/tools/acorn-optimizer.js#L1302) with try~catch.
But now there is no code in this repository.
Where is the local patch code?
Am I misunderstood about this issue or miss something..? 🤔

**Comment by RReverser** [comment]
Yeah it's quite hard to find the source change of Acorn, but it appears the built file was modified here https://github.com/emscripten-core/emscripten/blob/8c75547f36abb79ba7147d38b1b0862b438b05ec/third_party/acorn/dist/acorn.js#L2770-L2771.

FWIW my suggestion was the following: as you can see, the errors raised by Acorn have `pos` and `loc` properties, so if someone wanted to, they could simply `try-catch` the error and use those properties to produce a message in an arbitrary format.

@TroyTae I think the easiest might be to just update Acorn code to latest upstream in Emscripten repo, and then look at the expected format vs retrieved one when running tests and wrap accordingly.

**Comment by kripken** [comment]
It's also possible we can just replace acorn and all tests would pass - I think we may have removed an overly-strict test for the error format. Worth opening a PR with just that, and seeing test results.

**Comment by TroyTae** [comment]
@RReverser Thank you! It seems history is lost after move directory 😅 
As you said, error object has `loc` and `pos`, so maybe I can handle this.

@kripken Now I'm try to do it. If we need some strict test, I'll write it :)
