### ISSUE TITLE
Performance regression with Wasm SIMD between 1.39.15 and 1.39.18

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#11449]
Using codecbench-simd.js from meshoptimizer repository (if you want to build this yourself, `make codecbench-simd.js` from https://github.com/zeux/meshoptimizer should do it, although for 1.39.18 removing the custom `wasm_v8x16_swizzle` from vertexcodec.cpp will be required to compile), I'm comparing performance between 1.39.15 and 1.39.18 of a set of SIMD algorithms. All of them run at around the same speed, except for one - which is this function: https://github.com/zeux/meshoptimizer/blob/master/src/vertexfilter.cpp#L491

In 1.39.15, this code runs at 2.6 GB/s
In 1.39.18, this code runs at 1.4 GB/s
Both timings are on the same version of v8 (8.4.272-node.8).

Attached are the binaries built with debug info to help reproduce this. Looking at this, the performance regression likely comes from 1.39.18 inserting extra bad shuffles:

Where 1.39.15 version has this code (corresponding to the end of the function where we shuffle and then extract 64-bit lanes from the result):

```
|     v8x16.shuffle 0x11100100 0x13120302 0x15140504 0x17160706
| 
|     local.tee 6
|     i64x2.extract_lane 1
|     local.get 7
|     i32x4.extract_lane 1
|     i64.extend_i32_u
|     i64.rotl
|     i64.store 3 8
```

1.39.18 version has an extra shuffle after the correct shuffle:

```
|     v8x16.shuffle 0x11100100 0x13120302 0x15140504 0x17160706
| 
|     local.tee 9
|     i64x2.extract_lane 0
|     local.tee 6
|     local.get 11
|     local.get 8
|     v8x16.shuffle 0x03020100 0x00000000 0x07060504 0x00000000
| 
|     local.tee 10
|     local.get 8
|     v128.and
|     local.tee 12
|     i64x2.extract_lane 0
|     i64.shl
|     i64x2.splat
|     local.get 9
|     i64x2.extract_lane 1
|     local.tee 7
|     local.get 12
|     i64x2.extract_lane 1
|     i64.shl
|     i64x2.replace_lane 1
|     local.get 6
|     local.get 10
|     i64x2.neg
|     local.get 8
|     v128.and
|     local.tee 8
```

In addition, 1.39.18 version doesn't seem to synthesize i64.rotl anymore for whatever reason, instead using shifts for this? Despite the fact that `__builtin_rotateleft64` is used here (wrapped in `rotateleft64` function).

cc @tlively - likely an LLVM issue...

[perf.zip](https://github.com/emscripten-core/emscripten/files/4805709/perf.zip)

**Comment by zeux** [comment]
P.S. Curiously, this seems to be different from the usual "shuffle optimization" problem - the original shuffles from the source seem in tact here, but extra shuffles seem to be inserted here for unclear reasons.

**Comment by zeux** [comment]
// pack x/y/z/w using 16-bit unpacks; we pack wxyz by default (for qc=0)
		volatile v128_t res_0 = wasmx_unpacklo_v16x8(wyr, xzr);
		volatile v128_t res_1 = wasmx_unpackhi_v16x8(wyr, xzr);

**Comment by zeux** [comment]
Similarly, adding volatile here:

```
		// compute component index shifted left by 4 (and moved into i32x4 slot)
		volatile v128_t cm = wasm_i32x4_shl(cf, 4);
```

Also works around the problem with insignificant performance loss. I'm going to use this workaround for now.

**Comment by tlively** [comment]
@zeux, yes I think this is an LLVM problem, and I suspect that it is an unanticipated side effect of the quick fix I did to prevent shuffle merging. I will investigate further.

**Comment by tlively** [comment]
Very interesting! I've bisected this regression to https://github.com/llvm/llvm-project/commit/8cc911fa5b06f055430d006d0640248fcac2a101, which was supposed to be a non-functional change! I'll dive in more and figure out what is actually going wrong after this commit.

**Comment by tlively** [comment]
Fix up for review at https://reviews.llvm.org/D85759. It turns out the problem had nothing to do with our switch to using an intrinsic for shuffles after all.
