### ISSUE TITLE
Regression when building a .wasm module: undefined exported function: "__start"

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#11446]
I have a wasm module that successfully built before with Emscripten 1.39.15. After trying to update 1.39.18, I get the following error (same command line that used to work):

```
$ emcc src/vertexcodec.cpp src/indexcodec.cpp src/vertexfilter.cpp -O3 -DNDEBUG -s EXPORTED_FUNCTIONS='["__start","_sbrk" ,"_meshopt_decodeVertexBuffer","_meshopt_decodeIndexBuffer","_meshopt_decodeIndexSequence" ,"_meshopt_decodeFilterOct","_meshopt_decodeFilterQuat","_meshopt_decodeFilterExp"]' -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=24576 -s TOTAL_MEMORY=65536 -o build/decoder_base.wasm
emcc: error: undefined exported function: "__start" [-Wundefined] [-Werror]
```

The reason why I need the symbol is that the binary has static constructors; so I used to run _start from .js after instantiating the module. Note that none of these .cpp files have `main()` - this used to be supported (with `_start` omitting the call to `main` when `main` was absent).

Apologies if this was already discussed here, I wasn't able to quickly find the same issue.

**Comment by zeux** [comment]
The workaround for my case seems to be to export `__wasm_call_ctors` and call that directly. I'm happy with that workaround, so if the removal of _start is intentional I'll happily switch to that.

**Comment by kripken** [comment]
Interesting question, I'm not sure if exporting `_start` manually should be supported or not.

I think `__wasm_call_ctors` should be automatically exported for you - is that not the case?

cc @sbc100 for both questions.

**Comment by zeux** [comment]
> I think __wasm_call_ctors should be automatically exported for you - is that not the case?

Yes, it is - I can switch to `__wasm_call_ctors` if that's preferable.

**Comment by zeux** [comment]
It looks like I used to use call_ctors, but switched to start because some previous Emscripten version stopped emitting that in some cases (https://github.com/emscripten-core/emscripten/issues/9767). But I guess now this is back.

I don't really mind using either one, but I'd like to use something that's stable across Emscripten versions and stable going forward. If the stable ABI is wasm_call_ctors I can switch to that and close this.

**Comment by sbc100** [comment]
Interesting....`_start` is used in standalone mode but I didn't realize we provided a `_start` function at all in normal mode.         So I'm not sure how this used to work in 1.39.15.

In fact, after try to reproduce this, I can't make it work with 1.39.15:

```
((1.39.15)) $ ./emcc ~/test/hello.c -s EXPORTED_FUNCTIONS="['__start']"
system_libs:WARNING: main() is in the input files, but "_main" is not in EXPORTED_FUNCTIONS, which means it may be eliminated as dead code. Export it if you want main() to run.
emcc: error: undefined exported function: "__start" [-Wundefined] [-Werror]
```

Are you sure you weren't using standalone mode?  Or do you define you own start function maybe?

**Comment by zeux** [comment]
> Are you sure you weren't using standalone mode? Or do you define you own start function maybe?

Standalone mode is defined by default (I believe) when the output is a .wasm file. I'm not using STANDALONE_WASM explicitly but I did try adding that and nothing changed.

**Comment by kripken** [comment]
Correct, when emitting just a wasm file we default to standalone mode.

**Comment by sbc100** [comment]
Of course, sorry.  

I think this is bug.. we currently assume you are building a reactor if you don't export `main`... we should probably check for `_start` too.   

However, if you are actually building a reactor (something with no main) then the current best practice is to call the `_initialize` export.   This will basically just call `__wasm_call_ctors`

**Comment by sbc100** [comment]
(_initialize will be exported automatically when building a reactor so you don't need to explicitly add it to EXPORTED_FUNCTIONS).

**Comment by zeux** [comment]
I'm happy to switch to `_initialize` - is that the API that should be stable long-term?

**Comment by sbc100** [comment]
Its something we inherit from WASI: https://github.com/WebAssembly/WASI/blob/master/design/application-abi.md

The whole concept it standalone mode is still evolving, as is WASI itself, and the extent to which emscripten does or doesn't following what WASI is doing..    So I wouldn't want to make any strong guarantees about this never changing.   But there is nothing more stable we can point you to.   We will of course try to maintain backwards compat and issue warnings when we can't.

**Comment by zeux** [comment]
Right - that sounds good to me. I'm going to switch to `_initialize` for now, since it does work in 1.39.18, and adjust if necessary in the future.
