### ISSUE TITLE
clang-tidy support

### ISSUE THREAD

**Issue by amir-l** [emscripten-core/emscripten#11447]
When running emcmake with clang-tidy enabled, it looks like the toolchain is ignored, although the output is:
configure: cmake ... -DCMAKE_TOOLCHAIN_FILE=/root/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/root/emsdk/node/12.9.1_64bit/bin/node"

The enabling of clang-tidy is done with: set_target_properties(${target_name} PROPERTIES CXX_CLANG_TIDY ${clang_tidy_cmd})

Issues:
1. clang-tidy can't expand response files.
Solution: set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0), which overwrite emscripten.cmake setting it to 1.
2. emscripten headers not found.
(workaround: add ~/emsdk/upstream/emscripten/system/include to the include directories)
3. __EMSCRIPTEN__ isn't defined.
(workaround: add -D__EMSCRIPTEN__)
4. /root/emsdk/upstream/emscripten/system/include/emscripten/val.h:193:9: error: static_assert failed due to requirement 'sizeof(emscripten::internal::GenericWireType) == 8' "GenericWireType must be 8 bytes"

**Comment by sbc100** [comment]
Regarding (1)... can we just remove CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES completely?    Any idea why we set that?

2. how does this work for other cross toolchains?   How does clang-tidy find the system include paths normally?

3. This normally comes from setting that `-target` correctly... It seems wrong to defined `__EMSCRIPTEN__` when setting the emscripten tripple?

4. again, how does this work on other cross-build platforms such as android that might have static assertions about the target?   Would adding `-target wasm32-unknown-emscripten` solve a lot of these issues?

**Comment by amir-l** [comment]
1. I think it is for Windows cmd line limit. 
Here is the commit - https://github.com/emscripten-core/emscripten/commit/9de7165f9157812a827f96a73c70dea1d909b763

2. There might be an issue with clang-tidy and cross compilation: https://gitlab.kitware.com/cmake/cmake/-/issues/20632

**Comment by bkotsopoulossc** [comment]
@sbc100 any idea if anyone has gotten clang-tidy builds to work for emscripten/wasm since? Looks like there was some activity on that cmake issue

**Comment by sbc100** [comment]
No idea I'm afraid.  If you would like to work on it, maybe add a test to verify that it works, that would be most welcome.

**Comment by bkotsopoulossc** [comment]
Sounds good, just checking. If we do figure this out I’ll be sure to share

**Comment by stevenwdv** [comment]
Dropping #24365 here for future reference
