### ISSUE TITLE
onAbort does not triggered when WebAssembly not support and compiled with -O3

### ISSUE THREAD

**Issue by sky0014** [emscripten-core/emscripten#11459]
I test wasm in Chrome49 which does not support WebAssembly.

When compile with -O1, onAbort callback can be triggered so that I can use it to handle error conditions.

But when compiled with -O3, It does not triggered, so I can't capture this error.

**Comment by kripken** [comment]
Do you have a testcase showing the issue? I'm not sure what could cause this just from that description.

**Comment by sky0014** [comment]
@kripken I analysed the code and found the reason, also make a pr #11475 , you can have a check.
