### ISSUE TITLE
【IDBFS】transaction.oncomplete does not wait for all onsuccess of entries

### ISSUE THREAD

**Issue by junyuecao** [emscripten-core/emscripten#11457]
When I use FS.readFile in the FS.syncfs callback  it throws an error with file not found.

I think the callback here does not wait for all onsuccess of entries.  
https://github.com/emscripten-core/emscripten/blob/master/src/library_idbfs.js#L271

I added some log and here is the output.
![image](https://user-images.githubusercontent.com/1000408/85227823-36cc6f80-b412-11ea-8d4a-a9e3795c04f7.png)

Maybe we should count the success callback in `done` and wait for all success calls?

**Comment by Mrcooder** [comment]
Yeah, i met the same problem too

**Comment by kripken** [comment]
A PR would be great if one of you can submit one. Let us know if you have questions about doing that.

**Comment by junyuecao** [comment]
It's not a bug. It's because of some code I modified. Just close.
