### ISSUE TITLE
MODULARIZE not trigger catch block on network errors

### ISSUE THREAD

**Issue by tri170391** [emscripten-core/emscripten#11451]
I have built a `MODULARIZED` module and it works great in the `then()` code path. But when I simulate potential failures client cases I see some strange behaviours. Here is how I set it up:

```
Module().then((wasmModule) => {
    console.log('Success!');
    useWasmModule(wasmModule);
}).catch((e) => {
    console.log('Failed!', e.stack);
    handleGracefullyLoadingFailure(e);
});
```

First I tried blocking the `.wasm` file using browser blocking mechanism. The `catch` block does not trigger but I got: `Uncaught (in promise) TypeError: Failed to fetch` in the chrome Dev console.

Secondly I tried removing the `.wasm` file so it 404 instead of being blocked, The `catch` block also des not trigger and I got: `RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.`

The expected behavior with `Promise` is to trigger catch block when the `Promise` is failed to fulfill so those cases should actually trigger it I think. Also this makes WASM initialization failure "hangs" the `Promise` since it is stuck in `<Pending>` state.

**Comment by kripken** [comment]
cc @lourd

**Comment by tri170391** [comment]
Any update on this one guys?

**Comment by lourd** [comment]
Thanks for the bug report @tri170391! Taking a look now

**Comment by tri170391** [comment]
Here's my setup for the test: https://gist.github.com/tri170391/d7d38f212ddebcc58dce516ed82e1798

**Comment by lourd** [comment]
Just opened #11615 with the fix, please take a look

**Comment by tri170391** [comment]
The changes looks good to me, thank guys!
