### ISSUE TITLE
higher resoure utilization vs. native code

### ISSUE THREAD

**Issue by popomen** [emscripten-core/emscripten#11462]
we find that the same code compiled by g++ and em++ occupies different cpu utilization.  
g++: ~1%
em++:~13%

It is very confused to us.

Demo code:

```
#include <unistd.h>
#include <iostream>
#include <thread>

#ifdef WASM
#include <emscripten.h>
#endif

int NUM_THREAD = 100;

void thread_task(int id) {
    while(1){
        std::cout << "thread " << id << "is running" << std::endl;
        #ifdef WASM
        emscripten_sleep(100);
        #else
        usleep(100000);
        #endif
    }
}

int main()
{
    std::thread threads[NUM_THREAD];
    for (int i = 0; i < NUM_THREAD; i++) {
        threads[i] = std::thread(thread_task, i);
    }

    #ifdef WASM
    emscripten_sleep(100000);
    #else
    usleep(100000000);
    #endif

    return 0;
}
```

g++ compile script:
`g++ mainThread.cc  -o ../out/mainThread -lpthread
`

em++ compilation script:
`em++ mainThread.cc -D WASM -o ../out/mainThread_em.html  -s USE_PTHREADS=1 -s ALLOW_MEMORY_GROWTH=1 -s ASYNCIFY=1`

**Comment by popomen** [comment]
@kripken @juj 

Thanks!

**Comment by kripken** [comment]
Looks like this is building without optimizations? First thing, I would try to add `-O3`.

Asyncify also adds 50% or so overhead usually, so that might be another factor.

**Comment by popomen** [comment]
I tried to add `-O3`, but there was no significant improvement.

**Comment by kripken** [comment]
It's possible asyncify is the cause then.

Another possible issue is that I see this does a lot of logging to the console. That might take a lot more resources in wasm/JS so removing that might help. When I remove the logging I see about 3% CPU used.
