### ISSUE TITLE
SIMD compilation issue 

### ISSUE THREAD

**Issue by AlexVestin** [emscripten-core/emscripten#11484]
I'm I'm trying to get SIMD to work with the x264 library, and I'm a bit out of my depth with this so sorry in advance 😅 . 

I'm building x264 into a static library with the flags;
`extra-cflags=-c -Wno-unknown-warning-option -msimd128 -msse -s ASSERTIONS=2`
and a bunch other options (disabling threads and asm).

But when I try to run the code with `emrun`, I get the following error:
```
wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Compiling function #32 failed: f32x4.splat[0] expected type f32, found i64.const of type i64 @+7989
```
Could this be related to x264 using  `x86 or any other native inline SIMD assembly` or is there something else aty play here

Edit: Using `tot-upstream` release

**Comment by kripken** [comment]
Which browser and version is that on?

To verify if the wasm is valid or not, you can try to load the file in wasm2wat (wabt) or wasm-dump (binaryen) for example.

But this may be a known issue - @tlively ?

**Comment by tlively** [comment]
Hmm, my guess is that you're using a slightly older engine from before some recent opcode changes we did. If I'm right, using Chrome's beta channel should work.

**Comment by AlexVestin** [comment]
@kripken It was  on Chrome 83.0.4103.116 64-bit for windows, with the `WebAssembly SIMD support` flag enabled. The wasm2wat seems to have worked, it outputed a large text representation at least

@tlively seems to be right, Chrome canary 85.0.4181.0 didn't have the issue

**Comment by AlexVestin** [comment]
Thanks for the help!

Semi-related, but will porting NASM/.asm SIMD be supported in the future?

**Comment by tlively** [comment]
We don't have any plans to investigate compiling native assembly to WebAssembly, although I can image that someone might write a tool to do that if they have a compelling business reason to translate a very large amount of assembly.
