### ISSUE TITLE
10-70x slow down with optimized vs unoptimized WASM code

### ISSUE THREAD

**Issue by griffin2000** [emscripten-core/emscripten#11486]
I've hit an issue with the attached code, running the compiled wasm is at least 10x slower when I enable optimisation, compared to the unoptimised version.  This is on windows running Firefox 77.0.1 (64-bit) (also tested on Chrome with similar results):

I compile with this command line (see src/em/build.bat for the full command line for each case).
`emcc    main.cpp  -o dc.O3.js -O3 -std=c++17 -DEMSCRIPTEN=1 -s MODULARIZE=1 -s EXPORT_NAME=DC -s EXPORTED_FUNCTIONS="['_malloc']" -s TOTAL_MEMORY=1048576000
`

The exact timing for each case are at follows, O2 is around 8x slower than O0, O1 is 70x slower!
emcc -O0 76ms 
emcc -O1 5188ms 
emcc -O2 543ms 
emcc -O3 661ms 
emcc -Os 1299ms 
emcc -Oz 1175ms 

The code itself is in \src\em\main.cpp, its executed with the webpage and js source including in /index.html and dist/index.js.  Compiled WASM and JS is included for all the optimisation levels.

https://drive.google.com/file/d/171xpeDUROr3OvnS-xkfAHju42hBTnneM/view?usp=sharing

**Comment by kripken** [comment]
This seems quite surprising. The first thing I'd check is to build with `--profiling` and run the browser profilers on this, to see how profiles differ between O0 and O1 for example. Something that big should be a huge difference that is easily identified.

**Comment by griffin2000** [comment]
So it seems like the unordered_map access is the issue.  Here is the O1 version:
![image](https://user-images.githubusercontent.com/1008962/85645090-c0747b00-b666-11ea-965e-add2cc173ded.png)

the O0 version that access does not appear at all:
![image](https://user-images.githubusercontent.com/1008962/85645261-311b9780-b667-11ea-8f01-66d3fb30e4fd.png)

This is the function in question: https://github.com/dominikwodniok/dualmc/blob/caa01599e29f5fc128facd0c1fdfd26d546a8109/include/dualmc.tpp#L193

**Comment by griffin2000** [comment]
The Chrome profile results:
[Profile-20200624T215329.zip](https://github.com/emscripten-core/emscripten/files/4828768/Profile-20200624T215329.zip)

**Comment by rahbari** [comment]
When I see this issue I decided to compiled ffmpeg with -O0 and yes, it's at least two time faster than -O3.

**Comment by kripken** [comment]
Could be something going very wrong with LLVM, perhaps...

To make it practical to debug this, can you make a minimal testcase for it? Optimally, a single file with just that function, and a main that calls it and runs a fixed workload, and that is easy to build and run.

**Comment by griffin2000** [comment]
Yeah its v easy to repro...  See this snippet (full file attached below), its clearly v broken optimisation-wise.  O0 is 0.036 seconds, O1 is 2.212 seconds.

Compiled like this:

```

emcc    ../main.cpp ../IsoSurface.cpp ./EM.cpp -O0  -std=c++17  -o test.O0.html -DEMSCRIPTEN=1 -s EXPORTED_FUNCTIONS="['_malloc','_main']" -s TOTAL_MEMORY=1048576000
emcc    ../main.cpp ../IsoSurface.cpp ./EM.cpp -O1  -std=c++17  -o test.O1.html -DEMSCRIPTEN=1 -s EXPORTED_FUNCTIONS="['_malloc','_main']" -s TOTAL_MEMORY=1048576000
```


This struct:
```

/// Dual point key structure for hashing of shared vertices
struct DualPointKey {
	// a dual point can be uniquely identified by ite linearized volume cell
	// id and point code
	int32_t linearizedCellID;
	int pointCode;
	/// Equal operator for unordered map
	bool operator==(DualPointKey const& other) const;
};

bool DualPointKey::operator==(DualPointKey const& other) const {
	return linearizedCellID == other.linearizedCellID && pointCode == other.pointCode;
}

/// Functor for dual point key hash generation
struct DualPointKeyHash {
	size_t operator()(DualPointKey const& k) const {
		return size_t(k.linearizedCellID) | (size_t(k.pointCode) << 32u);
	}
};
```

Added to an unordered set:
```
	std::srand(13);
	std::unordered_map<DualPointKey, QuadIndexType, DualPointKeyHash> pointToIndex;

	int nv = 0;
	for (int i = 0; i < n; i++) {
		DualPointKey key;
		key.linearizedCellID = rand() % 100000;
		key.pointCode= rand() % 5;
		auto iterator = pointToIndex.find(key);
		if (iterator == pointToIndex.end()) {
			// create new vertex and vertex id
			QuadIndexType newVertexId = nv++;
			pointToIndex[key] = newVertexId;
		}
	}

```

**Comment by griffin2000** [comment]
File and build script here:
[EM.zip](https://github.com/emscripten-core/emscripten/files/4834685/EM.zip)

**Comment by kripken** [comment]
Thanks for the info - sounds like this can be really narrowed down, then. Can you attach a disassembly of the relevant function with -O0 and -O1? (you may want to mark the hot function as `__attribute__((noinline))` and build with `--profiling` so it's easy to find. to disassembly, you can use wasm-dis in binaryen, which is bundled with the emsdk binaries, or wasm2wat in wabt).

**Comment by griffin2000** [comment]
Sure here is the O1 version (full disassembly included below):

```

 (func $slowFunc\28int\29 (param $0 i32) (result i32)
  (local $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  (global.set $global$0
   (local.tee $1
    (i32.sub
     (global.get $global$0)
     (i32.const 48)
    )
   )
  )
  (call $srand
   (i32.const 13)
  )
  (local.set $2
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::unordered_map\28\29
    (i32.add
     (local.get $1)
     (i32.const 24)
    )
   )
  )
  (if
   (i32.ge_s
    (local.get $0)
    (i32.const 1)
   )
   (block
    (local.set $4
     (i32.const 0)
    )
    (local.set $3
     (i32.const 0)
    )
    (loop $label$2
     (i32.store offset=16
      (local.get $1)
      (i32.rem_s
       (call $rand)
       (i32.const 100000)
      )
     )
     (i32.store offset=20
      (local.get $1)
      (i32.rem_s
       (call $rand)
       (i32.const 5)
      )
     )
     (i32.store offset=8
      (local.get $1)
      (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::find\28DualPointKey\20const&\29
       (local.get $2)
       (i32.add
        (local.get $1)
        (i32.const 16)
       )
      )
     )
     (i32.store
      (local.get $1)
      (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::end\28\29
       (local.get $2)
      )
     )
     (if
      (call $std::__2::operator==\28std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\2c\20std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\29
       (i32.add
        (local.get $1)
        (i32.const 8)
       )
       (local.get $1)
      )
      (block
       (i32.store
        (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::operator\5b\5d\28DualPointKey\20const&\29
         (local.get $2)
         (i32.add
          (local.get $1)
          (i32.const 16)
         )
        )
        (local.get $4)
       )
       (local.set $4
        (i32.add
         (local.get $4)
         (i32.const 1)
        )
       )
      )
     )
     (br_if $label$2
      (i32.ne
       (local.tee $3
        (i32.add
         (local.get $3)
         (i32.const 1)
        )
       )
       (local.get $0)
      )
     )
    )
   )
  )
  (i32.store offset=16
   (local.get $1)
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::begin\28\29
    (local.get $2)
   )
  )
  (i32.store offset=8
   (local.get $1)
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::end\28\29
    (local.get $2)
   )
  )
  (local.set $3
   (i32.const 0)
  )
  (if
   (call $std::__2::operator!=\28std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\2c\20std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\29
    (i32.add
     (local.get $1)
     (i32.const 16)
    )
    (i32.add
     (local.get $1)
     (i32.const 8)
    )
   )
   (loop $label$5
    (drop
     (call $std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>::operator->\28\29\20const
      (i32.add
       (local.get $1)
       (i32.const 16)
      )
     )
    )
    (drop
     (call $std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>::operator++\28int\29
      (i32.add
       (local.get $1)
       (i32.const 16)
      )
      (i32.const 0)
     )
    )
    (i32.store offset=8
     (local.get $1)
     (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::end\28\29
      (local.get $2)
     )
    )
    (local.set $3
     (i32.add
      (local.get $3)
      (i32.const 1)
     )
    )
    (br_if $label$5
     (call $std::__2::operator!=\28std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\2c\20std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\29
      (i32.add
       (local.get $1)
       (i32.const 16)
      )
      (i32.add
       (local.get $1)
       (i32.const 8)
      )
     )
    )
   )
  )
  (drop
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::~unordered_map\28\29
    (local.get $2)
   )
  )
  (global.set $global$0
   (i32.add
    (local.get $1)
    (i32.const 48)
   )
  )
  (local.get $3)
 )
```

**Comment by griffin2000** [comment]
And the O0```


 (func $slowFunc\28int\29 (param $0 i32) (result i32)
  (local $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  (local $5 i32)
  (local $6 i32)
  (local $7 i32)
  (local $8 i32)
  (local $9 i32)
  (local $10 i32)
  (local $11 i32)
  (local $12 i32)
  (local $13 i32)
  (local $14 i32)
  (local $15 i32)
  (local $16 i32)
  (local $17 i32)
  (local $18 i32)
  (local $19 i32)
  (local $20 i32)
  (local $21 i32)
  (local $22 i32)
  (local $23 i32)
  (local $24 i32)
  (local $25 i32)
  (local $26 i32)
  (local $27 i32)
  (local $28 i32)
  (local $29 i32)
  (local $30 i32)
  (local $31 i32)
  (local $32 i32)
  (local $33 i32)
  (local $34 i32)
  (local $35 i32)
  (local $36 i32)
  (local $37 i32)
  (local $38 i32)
  (local $39 i32)
  (local $40 i32)
  (local $41 i32)
  (local $42 i32)
  (local $43 i32)
  (local $44 i32)
  (local $45 i32)
  (local $46 i32)
  (local $47 i32)
  (local $48 i32)
  (local $49 i32)
  (local $50 i32)
  (local $51 i32)
  (local $52 i32)
  (local $53 i32)
  (local $54 i32)
  (local $55 i32)
  (local $56 i32)
  (local $57 i32)
  (local $58 i32)
  (local $59 i32)
  (local $60 i32)
  (local $61 i32)
  (local $62 i32)
  (local $63 i32)
  (local $64 i32)
  (local $65 i32)
  (local $66 i32)
  (local $67 i32)
  (local $68 i32)
  (local $69 i32)
  (local $70 i32)
  (local $71 i32)
  (local $72 i32)
  (local $73 i32)
  (local $74 i32)
  (local $75 i32)
  (local $76 i32)
  (local $77 i32)
  (local $78 i32)
  (local $79 i32)
  (local $80 i32)
  (local $81 i32)
  (local $82 i32)
  (local $83 i32)
  (local $84 i32)
  (local $85 i32)
  (local $86 i32)
  (local $87 i32)
  (local $88 i32)
  (local $89 i32)
  (local $90 i32)
  (local $91 i32)
  (local $92 i32)
  (local $93 i32)
  (local.set $1
   (global.get $global$0)
  )
  (local.set $2
   (i32.const 96)
  )
  (local.set $3
   (i32.sub
    (local.get $1)
    (local.get $2)
   )
  )
  (block $label$1
   (if
    (i32.lt_u
     (local.tee $92
      (local.get $3)
     )
     (global.get $global$2)
    )
    (call $__handle_stack_overflow)
   )
   (global.set $global$0
    (local.get $92)
   )
  )
  (local.set $4
   (i32.const 0)
  )
  (local.set $5
   (i32.const 72)
  )
  (local.set $6
   (i32.add
    (local.get $3)
    (local.get $5)
   )
  )
  (local.set $7
   (local.get $6)
  )
  (local.set $8
   (i32.const 13)
  )
  (i32.store offset=92
   (local.get $3)
   (local.get $0)
  )
  (call $srand
   (local.get $8)
  )
  (drop
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::unordered_map\28\29
    (local.get $7)
   )
  )
  (i32.store offset=68
   (local.get $3)
   (local.get $4)
  )
  (i32.store offset=64
   (local.get $3)
   (local.get $4)
  )
  (block $label$3
   (loop $label$4
    (local.set $9
     (i32.load offset=64
      (local.get $3)
     )
    )
    (local.set $10
     (i32.load offset=92
      (local.get $3)
     )
    )
    (local.set $11
     (local.get $9)
    )
    (local.set $12
     (local.get $10)
    )
    (local.set $13
     (i32.lt_s
      (local.get $11)
      (local.get $12)
     )
    )
    (local.set $14
     (i32.const 1)
    )
    (local.set $15
     (i32.and
      (local.get $13)
      (local.get $14)
     )
    )
    (br_if $label$3
     (i32.eqz
      (local.get $15)
     )
    )
    (local.set $16
     (i32.const 48)
    )
    (local.set $17
     (i32.add
      (local.get $3)
      (local.get $16)
     )
    )
    (local.set $18
     (local.get $17)
    )
    (local.set $19
     (i32.const 40)
    )
    (local.set $20
     (i32.add
      (local.get $3)
      (local.get $19)
     )
    )
    (local.set $21
     (local.get $20)
    )
    (local.set $22
     (i32.const 72)
    )
    (local.set $23
     (i32.add
      (local.get $3)
      (local.get $22)
     )
    )
    (local.set $24
     (local.get $23)
    )
    (local.set $25
     (i32.const 56)
    )
    (local.set $26
     (i32.add
      (local.get $3)
      (local.get $25)
     )
    )
    (local.set $27
     (local.get $26)
    )
    (local.set $28
     (call $rand)
    )
    (local.set $29
     (i32.const 100000)
    )
    (local.set $30
     (i32.rem_s
      (local.get $28)
      (local.get $29)
     )
    )
    (i32.store offset=56
     (local.get $3)
     (local.get $30)
    )
    (local.set $31
     (call $rand)
    )
    (local.set $32
     (i32.const 5)
    )
    (local.set $33
     (i32.rem_s
      (local.get $31)
      (local.get $32)
     )
    )
    (i32.store offset=60
     (local.get $3)
     (local.get $33)
    )
    (local.set $34
     (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::find\28DualPointKey\20const&\29
      (local.get $24)
      (local.get $27)
     )
    )
    (i32.store offset=48
     (local.get $3)
     (local.get $34)
    )
    (local.set $35
     (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::end\28\29
      (local.get $24)
     )
    )
    (i32.store offset=40
     (local.get $3)
     (local.get $35)
    )
    (local.set $36
     (call $std::__2::operator==\28std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\2c\20std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\29
      (local.get $18)
      (local.get $21)
     )
    )
    (local.set $37
     (i32.const 1)
    )
    (local.set $38
     (i32.and
      (local.get $36)
      (local.get $37)
     )
    )
    (block $label$5
     (br_if $label$5
      (i32.eqz
       (local.get $38)
      )
     )
     (local.set $39
      (i32.const 72)
     )
     (local.set $40
      (i32.add
       (local.get $3)
       (local.get $39)
      )
     )
     (local.set $41
      (local.get $40)
     )
     (local.set $42
      (i32.const 56)
     )
     (local.set $43
      (i32.add
       (local.get $3)
       (local.get $42)
      )
     )
     (local.set $44
      (local.get $43)
     )
     (local.set $45
      (i32.load offset=68
       (local.get $3)
      )
     )
     (local.set $46
      (i32.const 1)
     )
     (local.set $47
      (i32.add
       (local.get $45)
       (local.get $46)
      )
     )
     (i32.store offset=68
      (local.get $3)
      (local.get $47)
     )
     (i32.store offset=36
      (local.get $3)
      (local.get $45)
     )
     (local.set $48
      (i32.load offset=36
       (local.get $3)
      )
     )
     (local.set $49
      (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::operator\5b\5d\28DualPointKey\20const&\29
       (local.get $41)
       (local.get $44)
      )
     )
     (i32.store
      (local.get $49)
      (local.get $48)
     )
    )
    (local.set $50
     (i32.load offset=64
      (local.get $3)
     )
    )
    (local.set $51
     (i32.const 1)
    )
    (local.set $52
     (i32.add
      (local.get $50)
      (local.get $51)
     )
    )
    (i32.store offset=64
     (local.get $3)
     (local.get $52)
    )
    (br $label$4)
   )
  )
  (local.set $53
   (i32.const 72)
  )
  (local.set $54
   (i32.add
    (local.get $3)
    (local.get $53)
   )
  )
  (local.set $55
   (local.get $54)
  )
  (local.set $56
   (i32.const 0)
  )
  (i32.store offset=32
   (local.get $3)
   (local.get $56)
  )
  (i32.store offset=28
   (local.get $3)
   (local.get $56)
  )
  (local.set $57
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::begin\28\29
    (local.get $55)
   )
  )
  (i32.store offset=24
   (local.get $3)
   (local.get $57)
  )
  (block $label$6
   (loop $label$7
    (local.set $58
     (i32.const 24)
    )
    (local.set $59
     (i32.add
      (local.get $3)
      (local.get $58)
     )
    )
    (local.set $60
     (local.get $59)
    )
    (local.set $61
     (i32.const 16)
    )
    (local.set $62
     (i32.add
      (local.get $3)
      (local.get $61)
     )
    )
    (local.set $63
     (local.get $62)
    )
    (local.set $64
     (i32.const 72)
    )
    (local.set $65
     (i32.add
      (local.get $3)
      (local.get $64)
     )
    )
    (local.set $66
     (local.get $65)
    )
    (local.set $67
     (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::end\28\29
      (local.get $66)
     )
    )
    (i32.store offset=16
     (local.get $3)
     (local.get $67)
    )
    (local.set $68
     (call $std::__2::operator!=\28std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\2c\20std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>\20const&\29
      (local.get $60)
      (local.get $63)
     )
    )
    (local.set $69
     (i32.const 1)
    )
    (local.set $70
     (i32.and
      (local.get $68)
      (local.get $69)
     )
    )
    (br_if $label$6
     (i32.eqz
      (local.get $70)
     )
    )
    (local.set $71
     (i32.const 24)
    )
    (local.set $72
     (i32.add
      (local.get $3)
      (local.get $71)
     )
    )
    (local.set $73
     (local.get $72)
    )
    (local.set $74
     (call $std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>::operator->\28\29\20const
      (local.get $73)
     )
    )
    (local.set $75
     (i32.load offset=8
      (local.get $74)
     )
    )
    (local.set $76
     (i32.load offset=32
      (local.get $3)
     )
    )
    (local.set $77
     (i32.add
      (local.get $76)
      (local.get $75)
     )
    )
    (i32.store offset=32
     (local.get $3)
     (local.get $77)
    )
    (local.set $78
     (i32.load offset=28
      (local.get $3)
     )
    )
    (local.set $79
     (i32.const 1)
    )
    (local.set $80
     (i32.add
      (local.get $78)
      (local.get $79)
     )
    )
    (i32.store offset=28
     (local.get $3)
     (local.get $80)
    )
    (local.set $81
     (i32.const 24)
    )
    (local.set $82
     (i32.add
      (local.get $3)
      (local.get $81)
     )
    )
    (local.set $83
     (local.get $82)
    )
    (local.set $84
     (i32.const 0)
    )
    (local.set $85
     (call $std::__2::__hash_map_iterator<std::__2::__hash_iterator<std::__2::__hash_node<std::__2::__hash_value_type<DualPointKey\2c\20int>\2c\20void*>*>\20>::operator++\28int\29
      (local.get $83)
      (local.get $84)
     )
    )
    (i32.store offset=8
     (local.get $3)
     (local.get $85)
    )
    (br $label$7)
   )
  )
  (local.set $86
   (i32.const 72)
  )
  (local.set $87
   (i32.add
    (local.get $3)
    (local.get $86)
   )
  )
  (local.set $88
   (local.get $87)
  )
  (local.set $89
   (i32.load offset=28
    (local.get $3)
   )
  )
  (drop
   (call $std::__2::unordered_map<DualPointKey\2c\20int\2c\20DualPointKeyHash\2c\20std::__2::equal_to<DualPointKey>\2c\20std::__2::allocator<std::__2::pair<DualPointKey\20const\2c\20int>\20>\20>::~unordered_map\28\29
    (local.get $88)
   )
  )
  (local.set $90
   (i32.const 96)
  )
  (local.set $91
   (i32.add
    (local.get $3)
    (local.get $90)
   )
  )
  (block $label$8
   (if
    (i32.lt_u
     (local.tee $93
      (local.get $91)
     )
     (global.get $global$2)
    )
    (call $__handle_stack_overflow)
   )
   (global.set $global$0
    (local.get $93)
   )
  )
  (return
   (local.get $89)
  )
 )

```

**Comment by griffin2000** [comment]
[EM.zip](https://github.com/emscripten-core/emscripten/files/4838374/EM.zip)

**Comment by griffin2000** [comment]
Actually that was the wrong version.  Resending...

**Comment by griffin2000** [comment]
Here is the correct disassembly.  I notice actually its that hash function thats actually the issue:
[Dis.zip](https://github.com/emscripten-core/emscripten/files/4838407/Dis.zip)

**Comment by griffin2000** [comment]
So this version of the hash function will in 0.01s with O1 (about 3x faster than the unoptimized version as expected):
```

struct DualPointKeyHash {
	size_t operator()(DualPointKey const& k) const {
		uint64_t combinedIndex = uint64_t(k.linearizedCellID) | (uint64_t(k.pointCode) << 32u);
		return std::hash<uint64_t>{}(combinedIndex);
	}
};
```

The original version will run 100x slower:
```

struct DualPointKeyHash {
	size_t operator()(DualPointKey const& k) const {
		return size_t(k.linearizedCellID) | (size_t(k.pointCode) << 32u);
	}
};

```

**Comment by griffin2000** [comment]
Here is the disassembly from the new version:
`
[test.O1.wasm.fast.zip](https://github.com/emscripten-core/emscripten/files/4838541/test.O1.wasm.fast.zip)
`

**Comment by griffin2000** [comment]
[test.O1.wasm.fast.zip](https://github.com/emscripten-core/emscripten/files/4838544/test.O1.wasm.fast.zip)

**Comment by kripken** [comment]
Nothing seems strange in those slowFunc* files. Are you sure that's the slow function? But your later comments say it's the hash functions being called, so I'm confused.

I think it may be fastest if I compile and investigate this locally. Please make this simpler so that is possible: I downloaded the first link here, but I don't see clear instructions for building the two versions, and it has extra files I'm unsure if I need or not, and also it seems to only run in a browser. Optimally, please make a testcase that is a single cpp file + a command to build it, and it runs in node in the shell, and it's very easy to measure performance, for example, it runs a fixed workload (with no random numbers, preferably) and finished when that completes, so just doing `time node O0.js` versus `time nodeO1.js` shows the huge 10-70x difference.

**Comment by griffin2000** [comment]
Sure, here is a version that compiles to js for node.  It has two files the test code in EM.cpp, and a windows batch file to build and disassemble (build.bat).

[EMNode.zip](https://github.com/emscripten-core/emscripten/files/4840953/EMNode.zip)


```
C:\Users\garet\axum\data\WhatEmerges\src\em\EM
λ node test.O1.js
Filled:9899
2.72174 seconds

C:\Users\garet\axum\data\WhatEmerges\src\em\EM
λ node test.O0.js
Filled:9899
0.0444268 seconds

```


It uses rand but initializes with srand so will be deterministic.  Node on line 13 there is a ifdef (set to 0)  that enables faster version of the hash (though it must be an interaction between the hash function and the map, as just simply running the hash function doesn't show the issue)

**Comment by griffin2000** [comment]
[EMNode0.zip](https://github.com/emscripten-core/emscripten/files/4840981/EMNode0.zip)

**Comment by kripken** [comment]
Thanks for the testcase. Ok, when I build it I see
```cpp
./EM.cpp:33:60: warning: shift count >= width of type [-Wshift-count-overflow]
                return size_t(k.linearizedCellID) | (size_t(k.pointCode) << 32u);
                                                                         ^  ~~~
1 warning generated.
```
That warning is valid: `size_t` is 32 bits on wasm, so the shift is not doing something useful. It may even be undefined behavior, and cause the optimizer to do odd things, which could explain the difference between O0 and O1 (one of them may do nothing for the shift, or do a rotate, or something else).

Removing the warning, by changing the line to
```cpp
		return size_t(k.linearizedCellID);
```
fixes the issue, and optimized builds are faster as expected.
