### ISSUE TITLE
emcc: cannot find library "System.B"

### ISSUE THREAD

**Issue by GenieTim** [emscripten-core/emscripten#11498]
Dear maintainers

Thank you for this awesome tool.

When trying to emscripten the [supertuxcart](https://github.com/supertuxkart/stk-code) game, I get the error `emcc: cannot find library "System.B"` after the compilation (`emmake cmake --build .`) as well as when executing the link step manually: 
```
emcc \
  --emscripten-cxx \
  @CMakeFiles/supertuxkart.dir/objects1.rsp \
  @CMakeFiles/supertuxkart.dir/linklibs.rsp \
  @CMakeFiles/supertuxkart.dir/includes_CXX.rsp \
  -o bin/supertuxkart.html
```

The curious thing (and the reason I am requesting help here) is that there is no "System.B" anywhere to be found. A simple `grep -R "*System*" ..` does not lead to any results at all. What is "System.B"? Where does the "System.B" requirement come from? Why does emscripten believe it needs it?

<details>
 <summary>Details/Steps to reproduce</summary>
 
Computer: Apple, macOS Catalina 10.15.5

emcc -v:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.18
clang version 6.0.1  (emscripten 1.39.18 : 1.39.18)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
shared:INFO: (Emscripten: Running sanity checks)
```

Libraries: quite a lot (see Supertuxkart [installation instructions](https://github.com/supertuxkart/stk-code/blob/master/INSTALL.md) & errors when compiling), all installed via [Homebrew](https://formulae.brew.sh/)

Changes to the supertuxkart code: none

Actual commands for compilation (run from `cmake_build` directory):
```
# run cmake configure 
emcmake cmake .. \
  -DBLUEZ_INCLUDE_DIR=/usr/local/lib/bluez-5.54/include \
  -DBLUEZ_LIBRARY=/usr/local/lib/bluez-5.54/lib \
  -DCMAKE_C_STANDARD=11 \
  -DCMAKE_CXX_STANDARD=14 \
  -DUSE_CRYPTO_OPENSSL=0 \
  -DCURL_INCLUDE_DIR=/usr/local/opt/curl/include \
  -DCURL_LIBRARY=/usr/local/opt/curl/lib/libcurl.dylib \
  -DFREETYPE_INCLUDE_DIRS=/usr/local//Cellar/freetype/2.10.2/include/freetype2 \
  -DFREETYPE_LIBRARY=/usr/local/opt/freetype/lib/libfreetype.dylib \
  -DFREETYPE2_INCLUDE_DIRS=/usr/local/opt/freetype/include/freetype2/freetype \
  -DFREETYPE2_LIBRARY=/usr/local/opt/freetype/lib/libfreetype.dylib \
  -DFRIBIDI_INCLUDE_DIR=/usr/local/Cellar/fribidi/1.0.9/include \
  -DFRIBIDI_LIBRARY=/usr/local/Cellar/fribidi/1.0.9/lib/libfribidi.dylib \
  -DHARFBUZZ_INCLUDEDIR=/usr/local/Cellar/harfbuzz/2.6.8/include \
  -DHARFBUZZ_LIBRARY=/usr/local/Cellar/harfbuzz/2.6.8/lib/libharfbuzz.dylib \
  -DJPEG_INCLUDE_DIR=/usr/local/Cellar/jpeg/9d/include \
  -DJPEG_LIBRARY=/usr/local/Cellar/jpeg/9d/lib/libjpeg.dylib \
  -DLIBCURL_INCLUDE_DIR=/usr/local/opt/curl/include \
  -DNETTLE_INCLUDE_DIRS=/usr/local/Cellar/nettle/3.6/include \
  -DNETTLE_LIBRARY=/usr/local/Cellar/nettle/3.6/lib/libnettle.dylib \
  -DOGGVORBIS_OGG_INCLUDE_DIR=/usr/local/Cellar/libogg/1.3.4/include \
  -DOGGVORBIS_OGG_LIBRARY=/usr/local/Cellar/libogg/1.3.4/lib/libogg.dylib \
  -DOGGVORBIS_VORBIS_INCLUDE_DIR=/usr/local/Cellar/libvorbis/1.3.6/include \
  -DOGGVORBIS_VORBIS_LIBRARY=/usr/local/Cellar/libvorbis/1.3.6/lib/libvorbis.dylib \
  -DOGGVORBIS_VORBISFILE_LIBRARY=/usr/local/Cellar/libvorbis/1.3.6/lib/libvorbisfile.dylib \
  -DOGGVORBIS_VORBISENC_LIBRARY=/usr/local/Cellar/libvorbis/1.3.6/lib/libvorbisenc.dylib \
  -DLIBRESOLV_LIBRARY=/usr/lib/libresolv.dylib \
  -DPTHREAD_LIBRARY=/usr/lib/libpthread.dylib \
  -DOPENAL_INCLUDE_DIR=/usr/local/opt/openal-soft/include \
  -DOPENAL_LIBRARY=/usr/local/opt/openal-soft/lib/libopenal.dylib \
  -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.dylib \
  -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g/include \
  -DOPENSSL_INCLUDEDIR=/usr/local/Cellar/openssl@1.1/1.1.1g/include \
  -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ \
  -DPNG_LIBRARY=/usr/local/Cellar/libpng/1.6.37/lib/libpng.dylib \
  -DPNG_PNG_INCLUDE_DIR=/usr/local/Cellar/libpng/1.6.37/include \
  -DSDL2_INCLUDEDIR=/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2 \
  -DSDL2_LIBRARY=/usr/local/Cellar/sdl2/2.0.12_1/lib/libSDL2.dylib \
  -DUSE_SYSTEM_GLEW=1 \
  -DUSE_WIIUSE=0 \
  -DZLIB_INCLUDE_DIR=/usr/local/opt/zlib/include \
  -DZLIB_LIBRARY=/usr/local/opt/zlib/lib/libz.1.dylib \
  -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=1

# compile
emmake cmake --build .

# Compile the linked bitcode generated by make (project.bc) to JavaScript.
emcc \
  --emscripten-cxx \
  @CMakeFiles/supertuxkart.dir/objects1.rsp \
  @CMakeFiles/supertuxkart.dir/linklibs.rsp \
  @CMakeFiles/supertuxkart.dir/includes_CXX.rsp \
  -o bin/supertuxkart.html
```

Output:
```
(... compilation ...)
[100%] Linking CXX executable bin/supertuxkart.js
em++: warning: the fastomp compiler is deprecated.  Please switch to the upstream llvm backend as soon as possible and open issues if you have trouble doing so [-Wfastcomp]
em++: error: emcc: cannot find library "System.B"
make[2]: *** [bin/supertuxkart.js] Error 1
make[1]: *** [CMakeFiles/supertuxkart.dir/all] Error 2
make: *** [all] Error 2
emcc: warning: the fastomp compiler is deprecated.  Please switch to the upstream llvm backend as soon as possible and open issues if you have trouble doing so [-Wfastcomp]
emcc: error: emcc: cannot find library "System.B"
```
</details>

l am very sorry if this is not related to this tool or if I missed a simple typo. Thanks for any help!

**Comment by sbc100** [comment]
Sadly the Makefile's the cmake produces by default don't show the failing command line.

The first step to debugging this would be to get visibility into the failing command.   I recommend switching to `-G Ninja` which also gives you parallel builds by default.   Alternatively you can `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` which will cause the `--build` command to not hide the failing commands.

**Comment by sbc100** [comment]
Also I would advice switch away form using the old fastcomp compiler ASAP.   I'm not sure how to do this in homebrew but if you use `emsdk` and install `latest` you will get the new backend.

**Comment by GenieTim** [comment]
Thank you very much for the hints. I upgraded emsdk and added the flag `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`. The error did indeed change. It is similar though: once again a library that cannot be found ("`unable to find library -lnul`") (do I have to close or rename the issue now?) as well as a new one. The output after compilation is now:

```
[100%] Linking CXX executable bin/supertuxkart.js
wasm-ld: error: unknown file type: /usr/local/opt/curl/lib/libcurl.4.dylib
wasm-ld: error: unable to find library -lnul
wasm-ld: error: unknown file type: /usr/local/opt/zlib/lib/libz.1.2.11.dylib
wasm-ld: error: unable to find library -lnul
em++: error: '/Users/(...)/emsdk/upstream/bin/wasm-ld @/var/folders/gv/f7hxxz3n7gbg2vfvrj101gnw0000gn/T/emscripten_avf_k717.rsp' failed (1)
make[2]: *** [bin/supertuxkart.js] Error 1
make[1]: *** [CMakeFiles/supertuxkart.dir/all] Error 2
make: *** [all] Error 2
wasm-ld: error: unable to find library -lnul
wasm-ld: error: unable to find library -lnul
emcc: error: '/Users/(...)/emsdk/upstream/bin/wasm-ld @/var/folders/gv/f7hxxz3n7gbg2vfvrj101gnw0000gn/T/emscripten_mndzipnk.rsp' failed (1)
```

At least this ime, I can find `-lnul` in cmake_build/CMakeFiles/supertuxkart.dir/linklibs.txt – unfortunately only there, twice, and not e.g. in a CMakeLists.txt or in code. The "nul" reminds me a bit too much of "null".
Removing the `-lnul ` from cmake_build/CMakeFiles/supertuxkart.dir/linklibs.txt, the compilation fails due to various undefined symbols.

Output of `file /usr/local/opt/curl/lib/libcurl.dylib`: `/usr/local/opt/curl/lib/libcurl.dylib: Mach-O 64-bit dynamically linked shared library x86_64`

**Comment by sbc100** [comment]
You can't link macOS shared libraries into your webassembly build.

You need to look at how /usr/local/opt/curl/lib/libcurl.4.dylib and /usr/local/opt/zlib/lib/libz.1.2.11.dylib are being located by cmake.. it should not be looking in those locations at all.  

Then you need to build your own copy of any dependencies such a libz and libcurl.   For libz the simplest way is to use the copy the comes with emscripten via `-s USE_ZLIB`.    For libcurl, I doubt there dependecieswill be any easy way to port it since emscripten does support raw sockets (at least not with the websocket proxy).

**Comment by GenieTim** [comment]
Thank you for your assistance. 
It is apparent that I clearly misunderstood some things about some initial CMake errors (`library .... not found, specify ..._LIBRARIES` variables). For the record and anyone googling: Instead of actually specifying these paths (as seen in the detauls/steps to reproduce section in the initial issue comment), the emscripten ports have to be used, resp. the path to emscripten compiled libraries. 
I currently have still issues doing that dynamically in CMake (spoiler: ExternalProject seems not to be viable, as it does not compile to a library but a utility; workarounds are more complicated then just using a sumodule for the libraries together with add_subdirectory) and am also getting errors due to it not finding the headers of the libraries provided by emscripten. These are issues though quite unrelated to the original and also issues where I can find tons of other things to try out on Google. 
To conclude, I am at a very different position now, do not expect the initial unexplained error to return and will therefore close this issue for the moment.
