### ISSUE TITLE
Should I compile .so file using emcc to open it with dlopen()?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11493]
Hi, I'm trying to open a dynamic library file (`.so`) using `dlopen()`.
So I created `libhello.so` file in Linux using `gcc` and compiled the `main.c` file with `--preload-file libhello.so` option.
However, I got the following error in a browser:

> (index):29 To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking

Should I compile `.so` file using `emcc` instead of `gcc` in order to be used in a web browser?

Thank you so much in advance!

reference: https://emscripten.org/docs/porting/files/packaging_files.html#preloading-files

**Comment by sbc100** [comment]
Yes, you need to use emcc to compile all the code.  

When building a shared library you need to build with `-s SIDE_MODULE=1` (both at compile and link time).
