### ISSUE TITLE
times() from <sys/times.h> doesn't work in Emscripten

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11491]
Hi, I'm trying to use `times()` which is part of `sys/times.h`.
It seems to work fine when I compile and run natively but it doesn't seem to work when I compile using Emscripten and run it in a browser.

My Code:

    #include <stdio.h>
    #include <unistd.h>
    #include <sys/types.h>
    #include <sys/time.h>
    #include <sys/times.h>
    
    int main()
    {
        struct tms cputime;
        for (int i = 0; i < 1000000; i++) {
            times(&cputime);
        }
        printf("time: %lu\n", cputime.tms_utime);
    }

Result when running natively in macOS:

    time: 85

Result when running in a Chrome Browser:

    time: 0

Is there a way to use `times()` in Emscripten or is it simply not supported in Emscripten?

Thank you so much in advance!

**Comment by sbc100** [comment]
Yup, this is simply not implemented: https://github.com/emscripten-core/emscripten/blob/2aa8c55a6afea89aad040a967e7397b07dcb8a57/src/library.js#L2843

We should probably have a more uniform way to informing developers when they hit such functions, especially in debug builds.

**Comment by cuinjune** [comment]
Thank you so much for your answer!
