### ISSUE TITLE
Is it possible to build a module with -undefined,dynamic_lookup?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11494]
Hi, I'm trying to build my code as a module with `-s MODULARIZE=1` and I want it to be used as a dynamic shared library.

However, it seems like the `-undefined,dynamic_lookup` flag is not supported in Emscripten.

Without the flag, I'm getting many undefined symbol warnings when I build my code with Emscripten.

Is there any alternative way to build a module without these warnings?

**Comment by sbc100** [comment]
The only official way we support dynamic libraries in emscripten is via the MAIN_MODULE/SIDE_MODULE options.  Have you looked into those?

`-undefined,dynamic_lookup` looks like an apple specific linker flag which is don't support in wasm-ld or in emscripten.

Have you tried simply building with `WARN_ON_UNDEFINED_SYMBOLS=0`...   That will at least give you something that builds.    I'm not sure how you would then inject those symbols at runtime.   What you have any idea of how you would like that to look?   i.e.  How you like to provide the symbols at runtime?    Do you want to pull them from the Module object?  Or provide a single function such as `resolveSymbols(name)` that you could then implement?

**Comment by cuinjune** [comment]
@sbc100 Thank you for your answer. 
I'm already using `-s ERROR_ON_UNDEFINED_SYMBOLS=0` flag so I can at least build it. 

I would like to pull the symbols from the main module so the side module can use the functions/variables that are implemented in the main module. I don't know what you mean by providing a single function though.

**Comment by sbc100** [comment]
I would try just using the SIDE_MODULE/MAIN_MODULE approach.       In this approach the functions in one are available to the other.

**Comment by sbc100** [comment]
You also don't need ERROR_ON_UNDEFINED_SYMBOLS=0 if you use SIDE_MODULE/MAIN_MODULE

**Comment by cuinjune** [comment]
@sbc100 Thank you! Should I use `-s EXPORT_ALL=1` flag for both SIDE_MODULE and MAIN_MODULE?

**Comment by sbc100** [comment]
No, with MAIN_MODULE/SIDE_MODULE all symbols are exported by default so you shouldn't need EXPORT_ALL.

**Comment by cuinjune** [comment]
@sbc100 I'm trying to create a simple example using `MAIN_MODULE/SIDE_MODULE` based on https://github.com/emscripten-core/emscripten/wiki/Linking#general-dynamic-linking but cannot make it work.

Here's my code:

**main.c:**

```
#include <stdio.h>
 
int side(int a);
 
int main()
{
    printf("hello world %d\n", side(1));
}
```
**side.c:**
```
int side(int a)
{
    return a + 1;
}
```
**compile:**
```
emcc side.c -s SIDE_MODULE=1 -o side.wasm
emcc main.c -s MAIN_MODULE=1 -o main.html
```
**index.html**
```
<!DOCTYPE html>
<html>

<head>
</head>

<body>
  <script>
    var Module
      = {
      preRun: []
      , postRun: []
      , print: function (e) {
        1 < arguments.length && (e = Array.prototype.slice.call(arguments).join(" "));
        console.log(e);
      }
      , printErr: function (e) {
        1 < arguments.length && (e = Array.prototype.slice.call(arguments).join(" "));
        console.error(e)
      }
    };
    Module.dynamicLibraries = ['side.wasm'];
  </script>
  <script async src="main.js"></script>
</body>

</html>
```
If I run it with `python -m SimpleHTTPServer`, I get the following errors:

```
(index):19 Assertion failed: undefined
printErr @ (index):19
abort @ main.js:33157
assert @ main.js:1074
removeRunDependency @ main.js:1984
(anonymous) @ main.js:2274
Promise.then (async)
instantiateArrayBuffer @ main.js:2272
(anonymous) @ main.js:2301
Promise.then (async)
(anonymous) @ main.js:2296
Promise.then (async)
instantiateAsync @ main.js:2288
createWasm @ main.js:2321
Module.asm @ main.js:2344
(anonymous) @ main.js:31495
(index):19 failed to asynchronously prepare wasm: abort(Assertion failed: undefined) at Error
    at jsStackTrace (http://localhost:8000/main.js:1626:13)
    at stackTrace (http://localhost:8000/main.js:1643:12)
    at abort (http://localhost:8000/main.js:33163:44)
    at assert (http://localhost:8000/main.js:1074:5)
    at removeRunDependency (http://localhost:8000/main.js:1984:5)
    at http://localhost:8000/main.js:2274:7
```

Any advice or guidance would be greatly appreciated!
