### ISSUE TITLE
SIMD: f32x4.splat[0] expected type f32, found i64.const of type i64 @+26296

### ISSUE THREAD

**Issue by rahbari** [emscripten-core/emscripten#11495]
I've compiled ffmpeg with emscripten and used it successfully, after compiling just with -msimd128 I get this error in chrome:
**Compiling function #59 failed: f32x4.splat[0] expected type f32, found i64.const of type i64 @+26296)**
I'm not an expert about SIMD and as the code compiles succusfully, don't know if this feature is not implemented in Chrome or it's a bug with emscripten.
I'm using emcc 1.39.18 and chrome 83 with "WebAssembly SIMD support" flag on.

**Comment by rahbari** [comment]
I just tested with Chrome Canary and it works fine, but there there is no performance improvement.

**Comment by AlexVestin** [comment]
I had the same issue in #11484 , also it seems x264 has most (all?) of its SIMD in [assembly](https://github.com/mirror/x264/blob/master/configure#L950) which I don't think [emscripten supports](https://emscripten.org/docs/porting/simd.html), so most of the performance gains isn't accessible

**Comment by tlively** [comment]
@rahbari you can check that SIMD was actually emitted by using wasm-objdump from wabt or wasm-dis from binaryen and looking for v128 types. If you just used the autovectorizer by passing -msimd128, it's not very surprising that you wouldn't see a performance difference. If you have any particularly hot code that you think could benefit from SIMD, the best path forward would be to port it to use the WebAssembly SIMD intrinsics. Alternatively, you can use Emscripten's SSE instrinsics, but there is no way to automatically port assembly.

**Comment by rahbari** [comment]
I decompiled using wasm-objdump and there are almost 20k occurrence of v128. 

> If you just used the autovectorizer by passing -msimd128, it's not very surprising that you wouldn't see a performance difference

Reading the docs I thought auto vectorizer automatically uses SIMD for loops.

**Comment by tlively** [comment]
It does, but it's unlikely to be able to do anything useful except for very simple loops that only do very simple operations.
