### ISSUE TITLE
patch backup file incorrectly exists in source tree.

### ISSUE THREAD

**Issue by hussamT** [emscripten-core/emscripten#11504]
https://github.com/emscripten-core/emscripten/blob/master/system/include/SDL/SDL_revision.h.orig
This should be removed.

**Comment by sbc100** [comment]
What makes you think that its patch backup file... but it also doesn't look very useful.

**Comment by hussamT** [comment]
if there are offsets when patching, it creates a .orig file unless patch is told explicitly not to do so.
So what likely happened was that some change on importing that header was accidentally commited.
