### ISSUE TITLE
Feature proposition: console.log and console.error for c++.

### ISSUE THREAD

**Issue by matt-42** [emscripten-core/emscripten#11501]
Hi all,

I find the console.log a lot more easier to use and faster to type than the std::cout << syntax.
What do you think about replicating it in c++? Here is a proposition:
 
```c++
struct {

  inline void log() { std::cout << std::endl; }

  template <typename A, typename... T> inline void log(A &&a, T &&... args) {
    std::cout << a;
    this->log(std::forward<T>(args)...);
  }

  inline void error() { std::cerr << std::endl; }

  template <typename A, typename... T> inline void error(A &&a, T &&... args) {
    std::cerr << a;
    this->error(std::forward<T>(args)...);
  }

} console;

```

**Comment by sbc100** [comment]
I don't see anything emscripten-specific about this, why not just add it to all your C++ project ?  Then it will work on all platforms.

BTW, In care you interested in direct access to the JS's `console.log` we have `emscripten_log` which works without pulling in any C++ runtime.

**Comment by matt-42** [comment]
Ok I understand.  At least it's here so people can copy paste it in their project.
