### ISSUE TITLE
fullscreen/SDL2 broke

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#11515]
Hi,

852ca4eb34b316d69f9999b7602e69a249422e63 / #11228 broke fullscreen support in SDL2, see https://github.com/emscripten-ports/SDL2/issues/87

Reverting src/library_html5.js make it work again.

**Comment by kripken** [comment]
Ah, that commit should have had no noticeable effects, so sounds like we messed up...

Do you have a testcase that shows the issue?

**Comment by kripken** [comment]
I think #11519 should fix this, but we need to verify.

**Comment by kripken** [comment]
Ah, no need for a testcase, I see this broke `interactive.test_html5_fullscreen` and others - which are not automated and so not run on CI, and we didn't realize we need to run those manually locally for that PR, which is how we missed this :cry:

**Comment by Beuc** [comment]
OK!
I had put a testcase in the SDL2 issue (press "f"):
https://gist.github.com/Beuc/0ab96af2fde381dd40d818f6b13450c0

**Comment by kripken** [comment]
Thanks @Beuc , I verified that works too.
