### ISSUE TITLE
GLFW linking issues when compiling template OpenGL Project 

### ISSUE THREAD

**Issue by lustoykov** [emscripten-core/emscripten#11514]
hey everyone, I've forked a simple[ template OpenGL project](https://github.com/lustoykov/Glitter) that I'd like to compile to wasm. I'm using macOS.

The original project has linked glfw in the CMakeLists.txt, but[ I've commented those parts out](https://github.com/lustoykov/Glitter/blob/master/CMakeLists.txt) in an attempt to replace them with `-s USE_GLFW=3 for emcc` later. Search for "!!!!!!" to see uncommented parts.

In order to build the project, I've taken following steps:

Step 1/ `cd Build && emcmake cmake ..` (success)
**Step 2/ `emmake make` fails with** 

```
[ 82%] Linking CXX executable Glitter/Glitter.js
**error: undefined symbol: glfwCreateWindow (referenced by top-level compiled C/C++ code)**
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
```
Per my understanding, those errors point at non existing glfw linking, but they should be ignored and passed to emcc later when compiling the final output: `emcc -s USE_GLFW=3...` 

In order to ignore them, I ran

**`emmake make -s ERROR_ON_UNDEFINED_SYMBOLS=0` which fails with the same stacktrace as above.**

How do I compile this project into wasm? Thanks!

**Comment by kripken** [comment]
The `undefined symbol: glfwCreateWindow` error happens during the final link step. I think you need to tell CMake to add another link flag, `-s USE_GLFW=3` as you mentioned.

Something like `cmake [..] "-DCMAKE_EXE_LINKER_FLAGS=-s USE_GLFW=3"` may work, but there are probably better ways in the CMakeLists.txt itself.

**Comment by lustoykov** [comment]
Thanks @kripken, for future readers - the suggestion above has helped.

In Step 1/ running

`cd Build && emcmake cmake "-DCMAKE_EXE_LINKER_FLAGS=-s USE_GLFW=3"`

has resolved the issue. I've ran into other issues specific to my Makefile, but I'm taking alternative approaches now.
