### ISSUE TITLE
geseparate_dwarf, symbol files, and external_debug_info reference

### ISSUE THREAD

**Issue by pfaffe** [emscripten-core/emscripten#11516]
Compiling with -geseparate_dwarf=foo.wasm currently has the effect of generating a foo.wasm file containing all DWARF data, and will also insert an external_debug_info custom section into the code module containing a string 'foo.wasm'.

It would be great to increase flexibility here. For instance, what if I want to point to the symbol module by absolute URL? I'd propose supporting a mapping syntax such as for --embed-file: `-gseparate_dwarf=./foo.wasm@http://.../foo.wasm`

**Comment by kripken** [comment]
Sounds reasonable to me, and the syntax sounds ok too.

@dschuff what do you think?

**Comment by dschuff** [comment]
The idea seems reasonable to me too. So the idea is that the bit before the `@` would be the debuginfo output file in the local filesystem  and the bit after it would appear in the external debug info custom section?

**Comment by kripken** [comment]
Yes, I think that's the suggestion.

**Comment by dschuff** [comment]
Another thing it might be worthwhile to support might be something like a GNU build ID, which uniquely identifies a build. That way the debugger can use whatever means it wants to locate the debug info, and the build ID can go into the external debug info section.

**Comment by dschuff** [comment]
(this was actually suggested in https://github.com/WebAssembly/tool-conventions/issues/133)
