### ISSUE TITLE
wasm-ld: error: unable to find library -lstdc++fs

### ISSUE THREAD

**Issue by qxred** [emscripten-core/emscripten#11528]
I just want to check  if emskd support std::experimental::filesystem, so compile the example code using 

`em++ --bind -o quick_example.js quick_example.cpp -lstdc++fs
`

Then I got error:

`wasm-ld: error: unable to find library -lstdc++fs`

Wondering if there is any plan to support that.

**Comment by sbc100** [comment]
I think you can just use the C++ <filesystem> header without needing to reference that additional library.

At least we certainly compile those parts of libc++:

```
./system/lib/libcxx/filesystem
├── directory_iterator.cpp
├── filesystem_common.h
├── int128_builtins.cpp
└── operations.cpp
```

**Comment by sbc100** [comment]
just removing `-lstdc++fs` from the command line should work
