### ISSUE TITLE
USE_PTHREADS brokes linking

### ISSUE THREAD

**Issue by DronCode** [emscripten-core/emscripten#11525]
Hello. 

I have an issue with usage of `USE_PTHREADS=1` and `PTHREAD_POOL_SIZE=2` in cmake. 

When I'm trying to add pthread support into my project via
```
set_target_properties(
        plugin_core
        PROPERTIES LINK_FLAGS " \
            -s 'EXTRA_EXPORTED_RUNTIME_METHODS=[\"ccall\",\"cwrap\",\"UTF8ToString\"]' \
            -s 'ASSERTIONS=1' \
            -s 'ALLOW_MEMORY_GROWTH=1' \
            -s 'USE_ZLIB=1' \
            -s 'USE_SDL=2' \
            -s 'WASM=1' \
            -s USE_PTHREADS=1 \
            -s PTHREAD_POOL_SIZE=2 \
            -lwebsocket.js \
            -luuid.js \
            -O3 \
        ")
```

I'm getting a linker error:

```
root:WARNING: USE_PTHREADS + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271
wasm-ld: error: --shared-memory is disallowed by CMakeFiles/plugin_core.dir/source/Entry.cpp.o because it was not compiled with 'atomics' or 'bulk-memory' features.
```

Maybe somebody knows what is a reason for this and how to fix that?
Thanks.

**Comment by sbc100** [comment]
You need to make sure you build all the object files with `-s USE_PTHREADS` too.

**Comment by DronCode** [comment]
With same values or only with `-s USE_PTHREADS=1`?

**Comment by sbc100** [comment]
USE_PTHREADS is one of the few flags that is required at compile and link time.   I don't think you need to pass any of the others at compile time.

**Comment by DronCode** [comment]
So, I tried to do that and it links when I'm passing that flags via

```
target_link_options(
        plugin_core PUBLIC
        "-s USE_PTHREADS=1"
        "-s PTHREAD_POOL_SIZE=2"
        "-s PROXY_TO_PTHREAD=1"
)
```

and removed that flags from set_target_properties (If I stay that flag in two places linked will ignore target_link_options instruction). I'm interested of why it doesn't work with `set_target_properties` because all other flags like `-s USE_SDL=2` or `-s ASSERTIONS=1` work nicely.

But in runtime, calling of any pthread_* functions doesn't work. As I can see in the console there are just empty stubs like 

```
_pthread_detach() {}
_pthread_create() { return 6; }
```

They literally do nothing. What's wrong now?

```emcc --version

emcc (Emscripten gcc/clang-like replacement) 1.39.18 (a3beeb0d6c9825bd1757d03677e817d819949a77)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kripken** [comment]
I don't know enough about cmake, but you can build with `EMCC_DEBUG=1` in the env to see the actual emcc commands cmake ends up doing. You should see `-s USE_PTHREADS` both when compiling source files and when doing the final link.

If you do see that but still have the problem, I'd try building pthreads code from the test suite that is known to work, for example `./tests/runner.py  test_pthreads_create` will run a test that uses `pthread_create` which you can verify has the right contents.

**Comment by DronCode** [comment]
Hmm, I will check it tomorrow, thanks for the advice :)

**Comment by DronCode** [comment]
So, I fixed that via custom cmake function. 
Maybe this code will be useful for somebody

```
include(CMakeParseArguments)

function(register_module)
    set(OPTIONS)
    cmake_parse_arguments(
            register_module
            "" # No single option arguments
            "TARGET"
            "LINKER_FLAGS"
            ${ARGN}
    )

    if (NOT register_module_TARGET)
        message(FATAL_ERROR "TARGET is required!")
        return()
    endif()

    set(_targetLinkFlags "-s USE_PTHREADS=1")
    set(_targetCompilerFlags "-s USE_PTHREADS=1")

    if (register_module_LINKER_FLAGS)
        set(_targetLinkFlags "${_targetLinkFlags} ${register_module_LINKER_FLAGS}")
    endif()

    set_target_properties(${register_module_TARGET} PROPERTIES LINK_FLAGS ${_targetLinkFlags})
    set_target_properties(${register_module_TARGET} PROPERTIES COMPILE_FLAGS ${_targetCompilerFlags})

    message(STATUS " Registered module ${register_module_TARGET}")

    unset(_targetLinkFlags)
    unset(_targetCompilerFlags)
endfunction()
```

and usage of it

```
add_subdirectory(third_party/fmt)
register_module(TARGET fmt)
```

and `fmt` will be compiled with threading support. 

Thanks for everybody who helped :D
