### ISSUE TITLE
Error when loading wasm binary file

### ISSUE THREAD

**Issue by yylittlefish** [emscripten-core/emscripten#11523]
Hi, I wrote a service with airplay sdk code and compiled successfully to a airplay-service.js(the codes contains too many lines so I did not paste here)
But when I tried to run it with this commend:
 node --experimental-wasm-threads --experimental-wasm-bulk-memory airplay-service.js
I met this error:
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #8519 failed: invalid atomic opcode @+2344857
CompileError: WebAssembly.instantiate(): Compiling function #8519 failed: invalid atomic opcode @+2344857
CompileError: WebAssembly.instantiate(): Compiling function #8519 failed: invalid atomic opcode @+2344857
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #8519 failed: invalid atomic opcode @+2344857) at Error
    at jsStackTrace (/home/yuyang/Emscripten/airplay-service.js:2326:17)
    at stackTrace (/home/yuyang/Emscripten/airplay-service.js:2343:16)
    at abort (/home/yuyang/Emscripten/airplay-service.js:1750:44)
    at /home/yuyang/Emscripten/airplay-service.js:1904:7
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #8519 failed: invalid atomic opcode @+2344857) at Error
    at jsStackTrace (/home/yuyang/Emscripten/airplay-service.js:2326:17)
    at stackTrace (/home/yuyang/Emscripten/airplay-service.js:2343:16)
    at abort (/home/yuyang/Emscripten/airplay-service.js:1750:44)
    at /home/yuyang/Emscripten/airplay-service.js:1904:7
/home/yuyang/Emscripten/airplay-service.js:154
      throw ex;

my emscripten version is:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.17
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project cc2349e3cf0e1f492433941b359a03fc3f746410)
Target: x86_64-unknown-linux-gnu

and the node version is v12.9.1

Have anybody met this kind of issue? any reply will be appreciated :)

**Comment by yylittlefish** [comment]
> What version of node are you using? It could be that you need a more recent version?

my node version is 12.9.1, it is not very old. could it be the reason?

**Comment by kripken** [comment]
There are a few atomic opcodes not supported in node 12. For that reason we disable our node-pthreads tests with asan (since asan uses some of those opcodes).

To verify you can use `wasm-objdump` to inspect which opcode is at the offset it complains about. Or, trying node 14 might fix things.

**Comment by yylittlefish** [comment]
Yes, use node14 will fix this issue, thank you very much

**Comment by yylittlefish** [comment]
Hi, @kripten
sorry, I have one more question.
I need to run the js in tv. 
for some reason, 
TV only support node 12, 
so I hope to find out what kind of code generated the un-supported atomic opcodes. 
I installed wabt, but dont know how to use wasm-objdump to check the atomic opcodes...there seems no guide..
do you know what kind of API could generat the unsupported atomic opcodes? 
I could consider to remove the api calling or find alternative solution.
Thank you!

**Comment by kripken** [comment]
`wasm-objdump --help` will show the options. I think `-d FILENAME` will dump out a file. Then you can grep for stuff with "atomic" in the name.

In general, I'm not sure what code would generate those. I have noticed that unoptimized code does it more often though.
