### ISSUE TITLE
Cannot catch RuntimeError in web worker

### ISSUE THREAD

**Issue by rualark** [emscripten-core/emscripten#11531]
I run wasm in web worker. I cannot find a way to catch RuntimeError exception that is thrown on abort here:
https://github.com/rualark/AiHarmony/blob/c12ed5cb1fda399dbd215430ce4dd245cc05c696/js/analysis/modules/CA3.js#L1445
![image](https://user-images.githubusercontent.com/15198808/86457071-c08e0e00-bd2b-11ea-821e-3ad01541dac8.png)

I tried to wrap this function into try-catch block, but exception cannot be caught here:
https://github.com/rualark/AiHarmony/blob/c12ed5cb1fda399dbd215430ce4dd245cc05c696/js/analysis/worker.js#L43

I am able to detect abort with this callback, but `undefined` is passed as a parameter to this callback and I cannot get error to pass it to Sentry.io:
https://github.com/rualark/AiHarmony/blob/c12ed5cb1fda399dbd215430ce4dd245cc05c696/js/analysis/worker.js#L9

Could you please help me understand, how can I catch RuntimError?

**Comment by kripken** [comment]
I think you can just do `onerror = ..handler function..` in the global scope, to be notified about any error.

**Comment by rualark** [comment]
Hi! Thanks for your reply!

Do you mean worker global scope, module global scope or html global scope? I tried adding this code to all three with no success:

```
onerror = function() {
  console.log('on error');
}
```

**Comment by kripken** [comment]
Any of those should work. A worker error is propagated up (unless something catches it - look for other `onerror` or `addEventListener`s).

The safest thing, to avoid the risk of another onerror overriding yours, is to use `addEventListener` in the worker scope, as in this example:
```js
addEventListener('error', (x) => {
  console.log(x + ' was thrown, and noticed by our custom onerror');
});
throw WebAssembly.RuntimeError('foo');
```

**Comment by rualark** [comment]
Yes, I can catch WebAssembly.RuntimeError if I throw it myself, but not if it is thrown by emscripten-generated js. Maybe it is because I import it with `importScripts`? I do that because I have multiple emscripten modules and import them based on messages that worker gets from application.

https://github.com/rualark/AiHarmony/blob/c12ed5cb1fda399dbd215430ce4dd245cc05c696/js/analysis/worker.js#L34
