### ISSUE TITLE
Don't exit from __lsan::DoLeakCheck

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#11534]
[Debugging with Sanitizers](https://emscripten.org/docs/debugging/Sanitizers.html) page suggests that, in case Emscripten program doesn't exit, one can invoke leak checks manually by defining and calling `__lsan::DoLeakCheck()`.

In principle, this works great for libraries where you want to make sure that there are no leaks after a call into the compiled JS+Wasm, but right now, aside from printing leaks to the console, `DoLeakCheck` also forcibly executes or halts the program, making it unusable in library scenario.

**Comment by sbc100** [comment]
I'm not sure we should be suggesting that people use this internal lsan function.   I'm also not sure if makes sense to do leak checks at any time except for program exit.

I'd rather add a way for programs build with `EXIT_RUNTIME=0` to manually choose to exit at some later point after main returns.  IIUC the main purpose of `EXIT_RUNTIME=0 ` is to not exit the runtime automatically after main runs.   If we allow for exiting explicitly would that remove the need for documenting and using this internal thing?

(I think `EXIT_RUNTIME=0` also happens to GC out all the code for running descrutors, but we could re-enable that if LSAN is used, or if we have some other mode such as `EXIT_RUNTIME=not_automatically_but_when_say`).

**Comment by RReverser** [comment]
As I mentioned, the use-case here is not programs but libraries built to JS+Wasm, where there is no conceptual "program exit" from C++ side because it can be loaded on the page once, and then called into from various places.

**Comment by sbc100** [comment]
Yes, I'm just suggesting that when leak checking is enabled, such programs must perform some kind of runtime "exit" before the leak checker runs.     The only restriction would then be that the program must be restarted before it can be used again.

The would still not exit of their own accord. 

Does this seems like an unreasonable burden to put on the users of the leak checker?

**Comment by sbc100** [comment]
The problem I see is that today there is no way to force a runtime exit in programs built with EXIT_RUNTIME=0, but I'm suggesting we add one for this purpose.

**Comment by sbc100** [comment]
If we don't do this then I'm not sure what the leak checking would even mean, because there could be all kind of program state still active, how could you tell which memory was part of the active global program state, and which parts were leaks?

**Comment by RReverser** [comment]
A follow-up: I found the source code which has a neighbour function `DoRecoverableLeakCheckVoid` which looks and sounds like something we'd want to use in the library case (checking for leaks without shutting down). https://github.com/emscripten-core/emscripten/blob/2bee818f21ff1687f28a4186795c10509cea784c/system/lib/compiler-rt/lib/lsan/lsan_common.cc#L649-L664 

I'll have to try this out later.

**Comment by sbc100** [comment]
Ah!  Sounds like that should solve that part of the problem.   Good find.

**Comment by RReverser** [comment]
@kripken @sbc100 Is this something we could expose in a more official way from Emscripten headers perhaps? As far as I can tell, right now user needs to manually define

```cpp
namespace __lsan {
  void DoLeakCheck(); // or DoRecoverableLeakCheckVoid
}
```

in their code to be able to call it, and that doesn't seem particularly clean / scalable.

**Comment by tlively** [comment]
It looks like there is already a PR to document the more official interface, which also already exists https://github.com/emscripten-core/emscripten/pull/10938

**Comment by RReverser** [comment]
~~Ah nice, however that doesn't help with the "recoverable" leak checking, without exiting the program  :(~~

Actually, looking at the latest headers, I see that's part of the public interface as well: https://github.com/llvm/llvm-project/blob/master/compiler-rt/include/sanitizer/lsan_interface.h

**Comment by RReverser** [comment]
I'll close this issue in favour of that PR, which, indeed, would address it once merged.
