### ISSUE TITLE
Possibly useless wasi imports

### ISSUE THREAD

**Issue by pmatos** [emscripten-core/emscripten#11535]
This C example generates 3 wasi imports that I cannot understand if they are needed but were certainly unexpected:

```
#include <stdlib.h>
#include <emscripten.h>

void * EMSCRIPTEN_KEEPALIVE wasm_malloc (unsigned long s)
{
  return malloc(s);
}

void EMSCRIPTEN_KEEPALIVE wasm_free(void *ptr)
{
  free(ptr);
}
```

Compile with:
```
$ emcc -O3 -o malloc.wasm extract.c -s ALLOW_MEMORY_GROWTH=0
```

Generates three WASI imports on `emcc (Emscripten gcc/clang-like replacement) 1.39.18 (a3beeb0d6c9825bd1757d03677e817d819949a77)`:
```
  (import "wasi_snapshot_preview1" "proc_exit" (func (;0;) (type 0)))
  (import "wasi_snapshot_preview1" "args_get" (func (;1;) (type 2)))
  (import "wasi_snapshot_preview1" "args_sizes_get" (func (;2;) (type 2)))
```

**Comment by kripken** [comment]
I think what's going on here is that we create a `_start` function by default, which includes argc/argv handling as well as a proper exit. If you instead build this with `--no-entry`, which is more suitable for a library, then those imports are not present.

@sbc100 Perhaps we need to document `--no-entry` better? But also, it surprises me that a program without a main gets a full-featured `_start`. If `main` is not present, could `_start` be empty? If there is no obvious way to do that in `crt1` etc., we could do it as a binaryen optimization.

**Comment by sbc100** [comment]
I would expect this to be a link failure.  At least the plan is that it will be once we finish with the reactor/command stuff.
