### ISSUE TITLE
Build "Hello World" to HTML Not Works

### ISSUE THREAD

**Issue by tigercosmos** [emscripten-core/emscripten#11542]
By following the tutorial in the official website, I built the hello world example to HTMT but it not works.

as:

<img width="1437" alt="截圖 2020-07-05 上午1 04 30" src="https://user-images.githubusercontent.com/18013815/86517436-80c64400-be5b-11ea-85cc-96c47c0c3549.png">

hello.c
```c
#include <stdio.h>

int main() {
  printf("hello, world!\n");
  return 0;
}
```

Build the c code:
```sh
 $ emcc hello.c -o hello.html
```

Environment:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.18
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 613c4a87ba9bb39d1927402f4dd4c1ef1f9a02f7)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Users/tigercosmos/emsdk/upstream/bin
shared:INFO: (Emscripten: Running sanity checks)
```

Chrome 83.0.4103.116

Did I miss something? I expect it should work since it is so simple.

**Comment by kripken** [comment]
It's probably the `file://` URL - that only works in some browsers, see

https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing

Looks like there is a note in the tutorial section about this, https://emscripten.org/docs/getting_started/Tutorial.html#generating-html - was that not clear enough? Or were you reading another part of the tutorial (maybe we should improve something)?

**Comment by tigercosmos** [comment]
Thanks @kripken! I see. I don't read the note carefully: "Unfortunately several browsers (including Chrome, Safari, and Internet Explorer)"

BTW do you know why it prints:
```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```
<img width="1434" alt="截圖 2020-07-05 上午1 18 18" src="https://user-images.githubusercontent.com/18013815/86517682-6db47380-be5d-11ea-8501-aa93a57d4ab8.png">

**Comment by redblobgames** [comment]
The `Incorrect response MIME type` error is telling you what's wrong — your web server is giving the wrong mime type for wasm. See https://emscripten.org/docs/compiling/Deploying-Pages.html 

> All JavaScript files (precompressed or not) should be best served with the HTTP response header `Content-Type: application/javascript`, and all asset files (`.data`, `.mem`) should be served with the header `Content-Type: application/octet-stream`. WebAssembly `.wasm` files should be served with `Content-Type: application/wasm`.

If you are using nginx, then look in your config file and add `application/wasm wasm;` to the `types { … }` section. This might be the `/etc/nginx/mime.types` file but it varies by platform. If you are using Apache, add `AddType application/wasm wasm` to your config file. 

If you don't serve the correct mime type, Emscripten will use an alternate way to load the file, so *it will still work*, but it might load a little slower. I usually don't worry about it until I'm deploying on my production web server.

**Comment by tigercosmos** [comment]
@redblobgames thanks!

**Comment by r-pankevicius** [comment]
It would be worth to mention in documentation section https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing that one may get scary errors in browser console output:

`hello.html:1246 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`

Emsdk is bundled with Python 3.7.4 but the issue "Mimetype is set to application/octet-stream for .wasm files instead of the correct application/wasm." is fixed in Python 3.8 - https://bugs.python.org/issue34758.

Well, it scares a bit, but it works.

**Comment by r-pankevicius** [comment]
I've tried these simple servers:
```
python -m http.server
npx serve
npx http-server
```
but none of them worked.

I noticed that test runner serves wasm files with `Content-type: application/wasm` header and extracted a minimal portion that works the same from it.

This script **simple_http_server.py** works OK, serving wasm with `Content-type: application/wasm` header.

```python
from http.server import HTTPServer, SimpleHTTPRequestHandler

# allows streaming compilation to work
SimpleHTTPRequestHandler.extensions_map['.wasm'] = 'application/wasm'

port = 8080
httpd = HTTPServer(('localhost', port), SimpleHTTPRequestHandler)
print(f'Serving at http://localhost:{port}')
httpd.serve_forever()
```

**Comment by sbc100** [comment]
It also works if you use the `emrun` tool which is shipped with emscripten.

**Comment by r-pankevicius** [comment]
It seems that emrun can serve only a single file.

```
C:\~src\Emscripten\play1\benchmarks\with-syms>emrun --hostname localhost --port 666
emrun [emrun_options] filename.html -- [html_cmdline_options]

   where emrun_options specifies command line options for emrun itself, whereas
   html_cmdline_options specifies startup arguments to the program.

If you are seeing "unrecognized arguments" when trying to pass
arguments to your page, remember to add `--` between arguments
to emrun itself and arguments to your page.


Type emrun --help for a detailed list of available options.
```

**Comment by sbc100** [comment]
You can pass a directory name too I think.  i.e. "./emrun --no_browser <dirname>`

**Comment by r-pankevicius** [comment]
It seems I am forced to pass html file as an first positional argument "serve". OK, I passed any html file and used serve_root option to pass . (current directory), e.g.:

```
C:\~src\Emscripten\play1>emrun any.html --serve_root .
Starting browser: cmd /C start  http://localhost:6931/any.html
```

It works fine serving that any.html, yet it even displays directory listing if I change URL to root (http://localhost:6931/) but at some point if I try to open other html file, the server exits.

**Comment by sbc100** [comment]
Running `emrun --no_browser .`  should do what you want.

**Comment by sbc100** [comment]
Then just navigate to the URL like you would when running `python -m http.server`

**Comment by r-pankevicius** [comment]
So true! Thank you.

```
C:\~src\Emscripten\play1>emrun --no_browser .
Web server root directory: C:\~src\Emscripten\play1
Now listening at http://0.0.0.0:6931/
```

Browsing to http://localhost:6931/ will work fine.
