### ISSUE TITLE
wasm-ld: error: ldexp.o: attempt to add bitcode file after LTO

### ISSUE THREAD

**Issue by femski** [emscripten-core/emscripten#11545]
Ever since moving up from 1.39.8 to anything newer (currently using 1.39.18), I get this linker error.

`wasm-ld: error: ldexp.o: attempt to add bitcode file after LTO`

-flto basically does not work for me anymore.

I am compiling all code with -flto and linking with -flto.
Not sure something changed and what we need to do differently.

**Comment by sbc100** [comment]
This is known issue that occurs when a symbol is not present in the bitcode but is generated when the bitcode is compiled.   

In this case llvm seems to be generated a call to ldexp at compile time but the linker already decided it didn't need that symbol.

We are still working on a solution.  

In the mean time, as a workaround, you could tell the linker to that that symbol is needed.   I think either of these two options should work:

1. Add `ldexp` to `EXPORTED_FUNCTIONS`
2. Add `-Wl,-u,ldexp` to the linker flags.

**Comment by femski** [comment]
I tried 2nd option and it worked!
Thank you @sbc100
