### ISSUE TITLE
Allocate not defined with O2 and beyond

### ISSUE THREAD

**Issue by louisabraham** [emscripten-core/emscripten#11547]
Hi, I cannot access allocate (nor setValue or getValue) from preamble.js with the latest version (1.39.18-2).
Other functions (like UTF8ToString) are fine.

**Comment by louisabraham** [comment]
I tried replacing allocate. It looks like something is definitely wrong.

```
> ptr = _malloc(1000)
5265592
> stringToUTF8("abcd", ptr)
0
> UTF8ToString(ptr)
""
```

**Comment by louisabraham** [comment]
It looks like any optimization level beyond O1 causes this critical bug.

**Comment by kripken** [comment]
They may get optimized out at higher optimization levels if they are not exported. Perhaps the build system needs to add them to `EXPORTED_RUNTIME_METHODS`.

However, in general it's best to avoid allocate, getValue, and setValue, and use `malloc` and direct memory access using `HEAP32` etc.

**Comment by louisabraham** [comment]
I tried EXPORTED_RUNTIME_METHODS but it didn't work.

In general, breaking programs compiled with previous versions is a bad practice.

I replaced with malloc, it works now.

**Comment by emilydolson** [comment]
Just in case anyone else lands on this issue with a similar problem - adding `allocate` to `EXPORTED_RUNTIME_METHODS` did fix it for me
