### ISSUE TITLE
Suggestion:FAQ - Mention Modularization Factory Function Defaults Parameter

### ISSUE THREAD

**Issue by hostilefork** [emscripten-core/emscripten#11540]
URL: ../../docs/getting_started/FAQ

*(Small enough that setting myself up to make a pull request seems less convenient than just making the suggestion, as it would have to be reviewed anyway.)*

The top hit for modularizing is the FAQ, which doesn't mention that the factory function takes default module settings.  That means that if you've been going with the historical global Module with some defaults to specify things like `locateFile()`, you wonder about the chicken-and-egg problem of how to specify that.  I wondered for a while and didn't see any mention of parameterization, which puzzled me.

Eventually I found this information from the settings file:

    // The factory function accepts 1 parameter, an object with default values for
    // the module instance:
    //
    //   const module = await EXPORT_NAME({ option: value, ... });
    //
    // Note the parentheses - we are calling EXPORT_NAME in order to instantiate
    // the module. This allows you to create multiple instances of the module.
    //
    // Note that in MODULARIZE mode we do *not* look for a global `Module` object
    // for default values. Default values must be passed as a parameter to the
    // factory function.

I feel some subset of this information should be present in the FAQ.  Maybe that could just be pared down to:

> Note that in MODULARIZE mode we do *not* look for a global `Module` object for default values. Default values must be passed as a parameter to the factory function.  See src/settings.js (link) for details.

It would have saved me some time and puzzlement if it were there.

**Comment by kripken** [comment]
I think this is a good suggestion, thanks!

I do think overall it would still be best if you can open a PR, though - if one of us opens a PR it would still need to be reviewed, so the total work is the same, or actually more since you've been thinking about this and have a good idea of how to rephrase it. And as this is just a doc change, opening a PR doesn't require you creating a fork or anything, you can just do it in the github UI on the website here - click "edit this file" when viewing it. I've done this in other repos for fixing a typo etc. and it's pretty convenient!

**Comment by hostilefork** [comment]
> opening a PR doesn't require you creating a fork or anything, you can just do it in the github UI on the website here - click "edit this file" when viewing it.

I believe that works for you because you're a repo owner.  Others need a fork.  :-)

If you have a fork you can do it, -but- unfortunately GitHub eliminated the fast-forward option purely through the web interface.  So you always have to muck with a git clients on an installation *somewhere* to do PRs if you ever made a fork at any point in time, if you want to have the up-to-date state.  Not as easy as it would be ideal for it to be...

**Comment by kripken** [comment]
> I believe that works for you because you're a repo owner. Others need a fork. :-)

I don't think so - I've done this recently on the Lobster repo for example, which I definitely am not an owner of.

For example, on [this file in Lobster](https://github.com/aardappel/lobster/blob/master/dev/CMakeLists.txt) I see the little pencil icon (with tooltip "edit the file") next to "raw" "blame" etc. Do you not see it?

(It may be true that you need a fork, I think that clicking that button automatically created a fork for me - all in the website, no git.)
