### ISSUE TITLE
Firefox 78.0.1 + threads

### ISSUE THREAD

**Issue by higaski** [emscripten-core/emscripten#11546]
I'm having a hard time getting threads to work on Firefox 78.0.1. Here is the little snippet I'm trying to run
```cpp
#include <cstdio>
#include <thread>

int main(int argc, char* argv[]) {
  std::thread first([] { puts("foo\n"); });
  std::thread second([] { puts("bar\n"); });
  puts("threads started\n");
  first.join();
  second.join();
  puts("threads joined\n");
}
```

Compiled and linked with CMake with USE_PTHREADS enabled
```
target_compile_options(
  Emscripten PRIVATE -v "SHELL:-s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8")
target_link_options(
  Emscripten PRIVATE -v --emrun
  "SHELL:-s MINIFY_HTML=0 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8")
```

So far so good. Running the .js file produced with node shows that both threads get created and run
```
$ node --experimental-wasm-threads --experimental-wasm-bulk-memory Emscripten.js
threads started
foo
bar
threads joined
```

However if I fire up a web server with Python and open the corresponding .html file with Firefox all I get is an "Uncaught ReferenceError: SharedArrayBuffer is not defined" exception. I can't really figure out why though. I know that the Firefox option "javascript.options.shared_memory" must be enabled in order to support SharedArrayBuffer but upon checking I've noticed that in my 78.0.1 build (Arch repo) it's enabled by default. What else am I missing?

/edit
Ok, I just found #10014 and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes
This cleared things up a bit. So this means threads are basically not an option currently until more standardization work is finished?

**Comment by kripken** [comment]
I think that standardization work is almost done, and the next release of Firefox or so will allow this. But it will depend on the new COOP/COEP stuff. See our test suite where that is set up on the server: https://github.com/emscripten-core/emscripten/blob/2bee818f21ff1687f28a4186795c10509cea784c/tests/runner.py#L1345 (the setup there is constantly tested on CI, so it should always be green, you can run `./tests/runner.py  browser.test_pthread_atomics_normal` for an example pthreads test)

**Comment by danielknobe** [comment]
Fixed with Firefox 79:
https://hacks.mozilla.org/2020/07/firefox-79/
