### ISSUE TITLE
Proposal: Disable other.test_minimal_runtime_code_size on Chromium CI (but not here!)

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#11559]
Currently when LLVM improves or regresses codegen somehow, we sometimes end up with the roll breaking on that test, which notices a +-20 byte difference. We then need to disable the test, let it roll, then enable it, and then update the tests and/or figure out what to do.

This is kind of annoying, and I think we can simplify it - without losing any code coverage - by skipping the test on chromium CI. Then LLVM will always roll in. We **will** still get a test failure on those tests, but only here on github CI. This may be slightly annoying as well, as it will just start to show up. However, we will be able to quickly fix it with a single PR here, as opposed to three (1 PR to disable, 1 to enable, and 1 to fix) plus the time that the roll is broken, the time to wait for the roll to happen before being able to re-enable it, and hopefully not forgetting to do that.

This will still prevent regressions, but let us do all the investigation/fixing here in github, as opposed to LLVM's roll being affected.

**Comment by tlively** [comment]
This SGTM. Going even further, we could split this test out into its own test suite and have an informational CI job to run it that won't block PR merging if it fails.

**Comment by sbc100** [comment]
Sounds like a reasonable approach.    We could have an environment variable that basically skips that or other tests.  We already have several such EMTEST_XXX env vars.

**Comment by kripken** [comment]
Hmm I thought about `EMTEST_XXX` for a bit but couldn't think of a good term for it. This is kind of very specific to that particular test.

How about just using the `skip:` mechanism? https://chromium-review.googlesource.com/c/emscripten-releases/+/2284732
