### ISSUE TITLE
Running Binaryen's C->wasm compiler inside of CRI-O container. Using StorageOS to store the compiled source code

### ISSUE THREAD

**Issue by advancedwebdeveloper** [emscripten-core/emscripten#11553]
Nobody replied on Discord - so I decided to open an issue.

I am interested to package Docker images, for running the compiler (C->WebAssembly) inside a container.
I thought that it would be a good option to store the input files/source code using https://storageos.com/.

I wanted to work out some configurations (that could cover all required scenarios) for auto-generated Docker images. Assuming that I have my source code on Github.

Ivan

**Comment by sbc100** [comment]
We do publish a somewhat official docker image of the emsdk which includes emscripten and all its dependencies:

https://hub.docker.com/r/emscripten/emsdk

It is maintained here:

https://github.com/emscripten-core/emsdk/blob/master/docker/Dockerfile

**Comment by advancedwebdeveloper** [comment]
So do I have to autogenerate my own Dockerfile file, if I have to ensure that compiled set of source code files, in C, are compiled with the latest version of C->WebAssembly compiler? So it would be inclusive (assumes that I am combining both steps, for that)? Or that is a separate step of the DevOps pipeline, which triggers corresponding actions of the bleeding edge version of the Docker image (emscripten), if the check shows that it is not up-to-date?
What about the file system usage and how to migrate into StorageOS? Is that about modifying the Dockerfile?

**Comment by sbc100** [comment]
I'm not sure I understand the questions you are asking but I'll have a go at answering.

The docker image we maintain at https://hub.docker.com/r/emscripten/emsdk should always include the very latest version.

`What about the file system usage and how to migrate into StorageOS? `... I don't quite understand what you are asking here.

**Comment by advancedwebdeveloper** [comment]
@sbc100 , I was asking whether your Docker image would relate to https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ (that could run before my containers, which would execute before I would compile any source in C, to wet .wasm files).
Or you where assuming that I would take your Docker image as a basis for extending it with my custom project (k8s Volumes, PersistentVolumes would allow to mount external storage into directories (as the compiler process would see it), so both pre-compiled emscripten and the code [in C] would be accessible inside a running container).

> > What about the file system usage and how to migrate into StorageOS? ...
> 
>  I don't quite understand what you are asking here.
I was asking:

- which options did you configure for Volumes or PersistentVolumes, when you prepared that "official" Docker image file (
[Types of Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes)
;
[Types of Volumes](https://kubernetes.io/docs/concepts/storage/volumes/)
 );
- how do you suggest running Binaryen, in sense of file/directory structure, to ensure valid input of the compiler

Ivan

**Comment by sbc100** [comment]
I'm no docker expert but perhaps you can find answers to those question by looking at our Dockerfile and the documentation for it:

https://github.com/emscripten-core/emsdk/tree/master/docker

There is a fair bit of information there, including how to extend the image.

I don't think we do anything very unusual, we just install emsdk and thats about it.

@trzecieu wrote must of it so may have more specific answers for you.

**Comment by advancedwebdeveloper** [comment]
It look like your team assumed to manually specify the path for the compilation process - while I was assuming that there would be some auto-generated config.

`# compile with docker image
docker run \
  --rm \
  -v $(pwd):$(pwd) \
  -u $(id -u):$(id -g) \
  emscripten/emsdk \
  emcc helloworld.cpp -o helloworld.js`

I think I understood what should be an entry point, out here:
['docker run' options ](https://docs.docker.com/engine/reference/commandline/run/#options)
. I was confused on how 
> docker run command first creates a writeable container layer over the specified image
was done. Also your Dockerfile has nothing to do with configuring any specific volumes, which have to be done for any persistent I/O, for the containerized compiler (and, optionally, for saving the results of the compilation, unless those are pushed into an external resource/service).
Referenced options have --volume and --volume-... listed, to take care of this.

So OK, I will wait for @trzecieu joining this discussion.
Ivan

**Comment by trzecieu** [comment]
Hi @advancedwebdeveloper : I've noticed the invitation, but that was so random that I thought that this is new strategy of head hunters. No offence : ) 

As @sbc100 said we use docker more like an environment to compile C/C++ to WASM. Given examples in the manual, aren't mandatory path. You should be able to mount any arbitrary volume as input / output. 

One think in mind is that we don't specify entrypoint in the meaning of most other micro service containers,
That is, when you run `docker run emscripten/emsdk  --version` it will simply fail. (unlike other more micro-service oriented images `docker run node --version`)

At the moment there is no particular reason for that, it's just an inheritance from the previous version of docker image.

I might miss something as k8s is undiscovered territory for me, maybe if you describe what you would like to achieve and how you see that docker image being used it would be easier. 

Cheers,
Piotr
