### ISSUE TITLE
xx.worker.js still has node support code when use -s ENVIRONMENT=worker and -s USE_PTHREADS=1

### ISSUE THREAD

**Issue by sky0014** [emscripten-core/emscripten#11564]
It seems that `ENVIRONMENT_MAY_BE_NODE` didn't work when compile worker.js.

**Comment by kripken** [comment]
Thanks @sky0014 ! Fix in #11583, yes, looks like we only handled ENVIRONMENT in the main JS file, but not the worker.js.
