### ISSUE TITLE
Timezone returns wrong value during DST

### ISSUE THREAD

**Issue by DConmy** [emscripten-core/emscripten#11572]
In src/library.js

    // timezone is specified as seconds west of UTC ("The external variable
    // `timezone` shall be set to the difference, in seconds, between
    // Coordinated Universal Time (UTC) and **local standard time**."), the same
    // as returned by getTimezoneOffset().
    // See http://pubs.opengroup.org/onlinepubs/009695399/functions/tzset.html
    {{{ makeSetValue('__get_timezone()', '0', '(new Date()).getTimezoneOffset() * 60', 'i32') }}};

For the east cost, this returns 4 hours, not the expected 5 hours.

According to MDN, getTimezoneOffset will differ based on the date and DST
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

But timezone is expected to be a constant and specified based on standard time
https://pubs.opengroup.org/onlinepubs/007908799/xsh/timezone.html

**Comment by DConmy** [comment]
I wanted validation that my analysis was correct.   I'll take a stab at a fix then.   Thanks.

**Comment by kripken** [comment]
Sounds good @DConmy - I think your analysis is right. However I'm not an expert on this stuff. One thing to try is to compile a program with emcc or with the regular system compiler and see if the results differ.
