### ISSUE TITLE
version include in cstddef:37: throws error ../../version:1:1: error: expected unqualified-id

### ISSUE THREAD

**Issue by kevzettler** [emscripten-core/emscripten#11575]
```
In file included from callback.cpp:20:
In file included from /usr/local/Cellar/emscripten/1.39.18/libexec/system/include/libcxx/stdlib.h:100:
In file included from /usr/local/Cellar/emscripten/1.39.18/libexec/system/include/libcxx/math.h:312:
In file included from /usr/local/Cellar/emscripten/1.39.18/libexec/system/include/libcxx/limits:121:
../../version:1:1: error: expected unqualified-id
0.74
^
4 errors generated.
em++: error: '/usr/local/opt/emscripten/libexec/llvm/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=18 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/include/libcxx -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/lib/libcxxabi/include -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/lib/libunwind/include -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/include/compat -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/include -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/include/libc -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/lib/libc/musl/arch/emscripten -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/local/include -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/system/include/SSE -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/cache/asmjs/include -DEMSCRIPTEN -Xclang -disable-O0-optnone -DHAVE_CONFIG_H -I. -I../.. -I../../include -O3 -MT callback.o -MD -MP -MF .deps/callback.Tpo -c -mllvm -disable-llvm-optzns callback.cpp -Xclang -isystem/usr/local/Cellar/emscripten/1.39.18/libexec/cache/asmjs/include/SDL2 -c -o callback.o -emit-llvm' failed (1)
make[6]: *** [callback.o] Error 1
make[5]: *** [all-recursive] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by sbc100** [comment]
The problem is the libcxx has a file called `version` in `system/include/libcxx/version` but the compiler is finding you own `version` which lives in `../../version` because of the `-I../..` on the command line.

**Comment by kevzettler** [comment]
thanks @sbc100 how can I fix this? 

I see: this in the Makefile:
```
DEFAULT_INCLUDES = -I. -I$(top_builddir)
AM_CPPFLAGS = -I$(top_srcdir)/include
```

And looking at some paths:
kevs-mbp:bin kevzettler$ which emcc | xargs cat
#!/bin/bash
PYTHON="/usr/local/opt/python@3.8/bin/python3" exec "/usr/local/Cellar/emscripten/1.39.18/libexec/emcc" "$@"
kevs-mbp:bin kevzettler$ cd /usr/local/Cellar/emscripten/1.39.18/libexec/
kevs-mbp:libexec kevzettler$ find ../ -name "version"
..//libexec/system/include/libcxx/version
kevs-mbp:libexec kevzettler$ find ../.. -name "version"
../../1.39.18/libexec/system/include/libcxx/version

**Comment by kevzettler** [comment]
Oh i've found that the project i'm trying to compile creates its own `version.h` file from a python script that looks like:

```
version.stamp:
	python version.py ../include/version.h .. $(CXX)
```

```
/* Version info file automatically generated by version.py */
#define VERSION_TEXT "4526ed7fM built with UNKNOWN"
```

**Comment by sbc100** [comment]
Your project is likely also generating a file called just `version` .. `version.h` would not be a problem.

I think is basically makes the project incompatible with libc++.. in the same way it would if you had a header called `string`.

**Comment by sbc100** [comment]
Maybe you can find a way to not generate the `version` file (and use `version.h` instread?)

**Comment by sbc100** [comment]
Indeed it seems like `version` is an official C++ header:  https://en.cppreference.com/w/cpp/header/version

**Comment by kevzettler** [comment]
@sbc100 I am not seeing a plain `version` file generated by the project only the `.h` file by searching the projects directory:

```
$ find ./ -name "version*"
.//include/version.h
.//src/version.py
```

**Comment by kevzettler** [comment]
ok I have removed the `version.h` file generation from the project. I am still encountering this error so it is coming from some where outside of the project. I have emscripten installed through homebrew on OsX so chances of a path conflict from that any thoughts on what else to check @sbc100 thank you for your help!

**Comment by sbc100** [comment]
You have a file called `version` (no .h extension) on your system that is in the include path .. that file seems to contain just the string "0.74".  It looks like the file exists two level up from where callback.cpp lives.

**Comment by kevzettler** [comment]
oh I see there this now its the `VERSION` meta file of the repo. How did you notice that from this ouput? I would have over looked it without searching for the `0.74` you mentioned. Where did you see that?

**Comment by kevzettler** [comment]
oh I see the 0.74 output in the original error now. Thanks for the help @sbc100

**Comment by sbc100** [comment]
Sounds like that is window-only issue since `VERSION` and `version` would be different otherwise.

**Comment by kevzettler** [comment]
@sbc100 this is on MacOs though which is surprising to me as I'd expect case sensitivity

**Comment by sbc100** [comment]
I think the solution is to find out where in your include path have a file called `version` or `VERSION` and either remove the file, or remove the path from your include path (`-I` path)
