### ISSUE TITLE
Create version stamp file in the emscripten cache directory

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11597]
For docker image users, and possible other use cases, that `.emscripten`, and `.emscripten_sanity` file ship together a pre-loaded cache directory.    

However if a user overrides the cache directory using EM_CACHE, and SDK upgrade is possible without emscripten realizing that the cache needs to be cleared.

See https://github.com/emscripten-core/emsdk/issues/372

We should write the sanity file (or an second sanity file) inside the cache directory itself to avoid this.

**Comment by sbc100** [comment]
One could also imagine using two different copies of emscripten on the same system... but using the same EM_CACHE variable.  In this case one would expect that cache to get cleared every time you switch from one to the other.

(This is one reason the cache now lives inside the emscripten directory by default).

**Comment by kripken** [comment]
I think putting the sanity check files in the cache is a good idea. Then the use case in the second comment wouldn't need to clear the cache, you could switch between different caches without an issue.

**Comment by sbc100** [comment]
I don't know why we didn't think of this before to be honest..
