### ISSUE TITLE
EXPORTED_FUNCTIONS does not work with openGL

### ISSUE THREAD

**Issue by NPIPHI** [emscripten-core/emscripten#11603]
I'm writing a program that dynamically links several modules together, including one that requires glfw/openGL functions.

 I use the build command:

`emcc main.cpp -o main.html -s USE_WEBGL=2 -s USE_GLFW=3 -s MAIN_MODULE=2 -s EXPORTED_FUNCTIONS=['_glClear', '_glClearColor', etc... ]`

to have the main module export all the required functions of the side modules, but openGL functions do not appear in the generated java script or wasm. When side modules try to use the openGL functions I get a "Uncaught TypeError: resolveSymbol(...) is undefined" error.

Building with
`emcc main.cpp -o main.html -s USE_WEBGL=2 -s USE_GLFW=3 -s MAIN_MODULE=1`
fixes the error, but I it also compiles a huge amount of unnecessary functions.

**Comment by sbc100** [comment]
I think this is because those functions are implemented in JS as JS library functions.

You need to export them as e.g. `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['glClear']"`

We should really generates errors/warnings for exported functions that are not found in the native code :(

**Comment by sbc100** [comment]
You can also do `INCLUDE_FULL_LIBRARY` to export all JS library functions..

**Comment by NPIPHI** [comment]
This works, thanks
