### ISSUE TITLE
Keyboard Input Target

### ISSUE THREAD

**Issue by diegurrio** [emscripten-core/emscripten#11612]
Our code is not receiving keyboard inputs when we set "#canvas" as the target. We explicitly build **-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1** and set our canvas' ID to "canvas". It's worth mentioning that we setup our Mouse input in a similar way and is working fine. We also notice that emscripten is intercepting keyboard input even though the canvas is not on focus. 

Example Code:
```
    EM_BOOL keyDownCallback(int eventType, const EmscriptenKeyboardEvent *event, void* userData) {
        // This message is never printed.
        printf("keyDownCallback()");
        return EM_FALSE;
    }

    EM_BOOL keyUpCallback(int eventType, const EmscriptenKeyboardEvent *event, void* userData) {
        // This message is never printed.
        printf("keyUpCallback()");
        return EM_FALSE;
    }

...
        EMSCRIPTEN_RESULT ret = emscripten_set_keydown_callback("#canvas", this, false, keyDownCallback);
        if (ret < 0) {
            printf("Could not set Emscripten key down callback.");
        }

        ret = emscripten_set_keyup_callback("#canvas", this, false, keyUpCallback);
        if (ret < 0) {
            printf("Could not set Emscripten key up callback.");
        }
...
```

**Comment by kripken** [comment]
I don't have an idea offhand for what this could be, but as this area of the code usually doesn't have people quickly jumping in with solutions in my experience, the advice I can give is to look in the test suite for similar API calls. Those are guaranteed to work, so reading them might show what needs to be done, or if not, maybe it'll become clear that we're missing some test coverage, and a PR with a new failing test example would be useful.
