### ISSUE TITLE
Issue building with vector

### ISSUE THREAD

**Issue by smalls12** [emscripten-core/emscripten#11618]
Hello,

I'm attempting to build my C++ project with emscripten.

I'm stuck on the following error
```
/src/3rdparty/emsdk/upstream/emscripten/system/include/libcxx/typeinfo:221:16: error: reinterpret_cast from 'std::__type_info_implementations::__non_unique_arm_rtti_bit_impl::__type_name_t' (aka 'unsigned int') to 'size_t' (aka 'unsigned long') is not allowed
        return reinterpret_cast<size_t>(__v);
```

From my project, it backtraced to an `#include <vector>`.

Not sure where to look next.

Any help is appreciated.

Thanks.

**Comment by sbc100** [comment]
Can you provide a minimal repro so we can investigate?   We have many projects that build just fine with <vector> so there must be something specific to your project here.

**Comment by smalls12** [comment]
This is all it takes

```
#include <vector>

int main(int argc, const char **argv)
{
    (void)argc;
    (void)argv;

    return 0;
}
```

I'm using cmake and these are the commands I use
`emcmake cmake ..`
`emmake make VERBOSE=1`

**Comment by sbc100** [comment]
Can you include the full output of the make command?

That file compiles just fine on its own.

**Comment by sbc100** [comment]
```
$ cat test.cc
#include <vector>

int main(int argc, const char **argv)
{
    (void)argc;
    (void)argv;

    return 0;
}
$ ./em++ -c test.cc
$
```

**Comment by smalls12** [comment]
Found the problem.

My CMakeLists.txt had the following lines:
```
include_directories( ${CMAKE_STAGING_PREFIX}/usr/include )
link_directories( ${CMAKE_STAGING_PREFIX}/usr/lib )
```

I'm not sure how that would have caused the problem, but fixed now.

Sorry for the noise, appreciate you confirming for me.
