### ISSUE TITLE
pass an shared_ptr to javascript cause memory leak (embind)

### ISSUE THREAD

**Issue by cuipeng1976** [emscripten-core/emscripten#11628]
emsdk 1.38.31

（一）C++ side
（1）bind a C++ class

class_<Cards>("Cards")
	.smart_ptr_constructor("Cards", &std::make_shared<Cards>)

（2）bind a C++ function

function("do_something", &do_something);

（3）do_something implementation

void do_something ( emscripten::val js_func )
{
	std::shared_ptr<Cards> new_cards = std::make_shared<Cards>();
	//...
	
	js_func(new_cards);
	
	//new_cards destructor will be called when leave do_something scope 
}

（二）js side

let js_func = function ( cards )
{
	//...
	
	// cards.delete(); if this line not be added, memery leak will cause an error: abort("Cannot enlarge memory arrays to size 16781312 bytes (OOM)...
}

do_something ( js_func );

//call do_something many times will produce the crash

**Comment by kripken** [comment]
I don't know embind well enough to tell if that's enough detail for someone to figure out the issue. I'd recommend attaching a minimal testcase that can be easily run.

**Comment by cuipeng1976** [comment]
> I don't know embind well enough to tell if that's enough detail for someone to figure out the issue. I'd recommend attaching a minimal testcase that can be easily run.

ok, i will do this later.

and is this a feature of embind? or bug
