### ISSUE TITLE
Using pthreads in a C++ function

### ISSUE THREAD

**Issue by adepierre** [emscripten-core/emscripten#11620]
Hi!

I'm quite sure this is not a bug and rather a misunderstanding from me, but I prefer to ask to be sure.

So my case is that I have a C++ function called when a button is pressed on the HTML page. As this function takes quite some time, I've moved the WASM module into a web worker to keep the UI thread available. Here is a minimal example to reproduce this setup compiled with: ``emcc --bind Module.cpp -s WASM=1 -o MyModule.js``

``Module.cpp``
```cpp
#include <iostream>
#include <thread>
#include <chrono>

#include <emscripten/bind.h>

using namespace emscripten;

void Sleep(int seconds)
{
    std::this_thread::sleep_for(std::chrono::seconds(seconds));
}

void Foo()
{
    std::cout << "Starting long computation" << std::endl;
    Sleep(5);
    std::cout << "Computation done!" << std::endl;
}

int main(int argc, char* argv[])
{
    std::cout << "Module is loading..." << std::endl;
    return 0;
}

EMSCRIPTEN_BINDINGS(my_module)
{
    function("Foo", &Foo);
}
```
``index.html``
```html
<!DOCTYPE html>
<html>
  <title>TestMymodule</title>
  <body>
      <button id="go">Go!</button>
      <script> 
            var module_worker = new Worker("Worker.js")
            
            module_worker.onmessage = function(e)
            {
                console.log(e.data);
            };
            
            document.getElementById("go").addEventListener('click', function(e)
            {
                module_worker.postMessage("");
            });
      </script>
  </body>
</html>
```

``Worker.js``
```javascript
importScripts('MyModule.js');

onmessage = function(e)
{
    Module.Foo();
    self.postMessage("Work done");
};
```

This works and everything runs smoothly \o/ The next step for me was to use multithreading to speed-up the long computation thing. So I modified my Foo function to
```cpp
void Foo()
{
    std::cout << "Starting long computation" << std::endl;
    std::thread t1(Sleep, 3);
    std::thread t2(Sleep, 2);
    t1.join();
    t2.join();
    std::cout << "Computation done!" << std::endl;
}
``` 
And compiled it using ``emcc --bind Module.cpp -s WASM=1 -s USE_PTHREADS=1 -o MyModule.js ``. Of course this doesn't work and print a link to the part of the doc explaining that I can't [block on the main thread](https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread) (even if the main thread here is not really the main but a worker).

I tried replacing the unwanted ``join`` by a boolean:
```cpp
void Sleep(int seconds, bool* busy)
{
    std::this_thread::sleep_for(std::chrono::seconds(seconds));
    *busy = false;
}

void Foo()
{
    std::cout << "Starting long computation" << std::endl;
    bool t1_busy = true;
    bool t2_busy = true;
    std::thread t1(Sleep, 3, &t1_busy);
    std::thread t2(Sleep, 2, &t2_busy);
    t1.detach();
    t2.detach();
    while (t1_busy || t2_busy)
    {

    }
    std::cout << "Computation done!" << std::endl;
}
```
But of course that did not change anything and my browser was still "stuck" waiting forever the bools to become true. I also tried to add ``-s PTHREAD_POOL_SIZE=2`` to my build command line, hoping the threads would be created before entering the function but it didn't work either.

So am I missing something here? Is it possible to use multithreading inside a function?

Thank you for your help!

**Comment by sky0014** [comment]
I met the same problem, It seems that pthreads program will stuck when running in a webworker.

**Comment by kripken** [comment]
I didn't investigate this in depth, but two notes about this code:
```cpp
    bool t1_busy = true;
    bool t2_busy = true;
    std::thread t1(Sleep, 3, &t1_busy);
    std::thread t2(Sleep, 2, &t2_busy);
    t1.detach();
    t2.detach();
    while (t1_busy || t2_busy)
    {

    }
```

First, I think those bools should be `atomic<bool>`? Otherwise it may not work to update them in one thread and see the result in another.

Second, the infinite `while` loop *may* be an issue. I think it should be ok, but just to be safe, I'd try replacing that with something async like `emscripten_set_main_loop`, so that that thread doesn't block while it waits for the result.

**Comment by adepierre** [comment]
Yes in an clean code they should be atomic, but as it didn't change the result, I tried to keep the minimal example as minimal as possible.

I didn't know about the ``emscripten_set_main_loop`` I'll try reading about it and come back later if I find a solution using it. Thanks for the info !

**Comment by sky0014** [comment]
@adepierre You can try remove the `std::out` code, maybe should work.

@kripken I found the problem is that `_fd_write` stucked when the main program is loading from a worker.
```js
    function _fd_write(fd, iov, iovcnt, pnum) {
      // Here stucked
      if (ENVIRONMENT_IS_PTHREAD) return _emscripten_proxy_to_main_thread_js(8, 1, fd, iov, iovcnt, pnum);
```

**Comment by adepierre** [comment]
@sky0014 Just tested it, not working. The program is still waiting forever. If I understood everything correctly, the two threads can't be started until the worker thread is free, i.e. until the Foo function is completed. But the Foo function needs the results of the two threads results to complete so I'll have to do things differently I guess. Maybe with ``emscripten_set_main_loop`` as suggested above.

**Comment by kripken** [comment]
@sky0014 Oh, yes, that is a possible issue - see paragraph 2 in 

https://emscripten.org/docs/porting/pthreads.html#proxying

`fd_write` and other I/O operations are proxied to the main thread. That is synchronous (since `fd_write` has to wait for the result), so if something else waits on the main thread, this can be a deadlock. The only real solution for now is to avoid I/O as much as possible, preferably do it only on the main thread, or avoid all other blocking operations.

**Comment by adepierre** [comment]
All right, so I tried different things, here is an example *on the main UI thread* that works just as expected, the function is called in the main UI thread. I use ASYNCIFY and emscripten_sleep to keep the browser responsive so I don't have to ``join`` in the main thread (the result is that the ``Work done`` log is printed before the work is actually done but that's not a big deal). The only warning in the console is "pthread #id exited" but I guess it's normal.

``Module.cpp`` compiled with ``emcc --bind Module.cpp -s WASM=1 -s ASYNCIFY -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -o MyModule.js``

```cpp
#include <iostream>
#include <thread>
#include <chrono>

#include <emscripten/bind.h>
#include <emscripten.h>

using namespace emscripten;

void Sleep(int seconds, bool* busy)
{
    std::this_thread::sleep_for(std::chrono::seconds(seconds));
    *busy = false;
}

void Foo()
{
    std::cout << "Starting long computation" << std::endl;
    bool t1_busy = true;
    bool t2_busy = true;
    std::thread t1(Sleep, 3, &t1_busy);
    std::thread t2(Sleep, 2, &t2_busy);
    t1.detach();
    t2.detach();
    while (t1_busy || t2_busy)
    {
        emscripten_sleep(10);
    }
    std::cout << "Computation done!" << std::endl;
}

int main(int argc, char* argv[])
{
    std::cout << "Loading..." << std::endl;
    return 0;
}

EMSCRIPTEN_BINDINGS(my_module)
{
    function("Foo", &Foo);
}
```

``index.html``

```html
<!DOCTYPE html>
<html>
  <title>TestMymodule</title>
  <body>
      <button id="go">Go!</button>
      <script src="MyModule.js"></script>
      <script> 
            document.getElementById("go").addEventListener('click', function(e)
            {
                Module.Foo();
                console.log("Work done");
            });
      </script>
  </body>
</html>
```

However, calling the same function of the same compiled module *inside* a WebWorker doesn't work. It seems that the threads never call the ``Sleep`` function at all.

``index.html``
```html
<!DOCTYPE html>
<html>
  <title>TestMymodule</title>
  <body>
      <button id="go">Go!</button>
      <script> 
            var module_worker = new Worker("Worker.js")
            
            module_worker.onmessage = function(e)
            {
                console.log(e.data);
            };
            
            document.getElementById("go").addEventListener('click', function(e)
            {
                module_worker.postMessage("go");
            });
      </script>
  </body>
</html>
```

``Worker.js`` 
```javascript
importScripts('MyModule.js');

onmessage = function(e)
{
    if(e.data === "go")
    {
        Module.Foo();
        self.postMessage("Work done");
    }
};
```

**Comment by adepierre** [comment]
Ok found the problem: the ``onmessage`` function defined in ``Worker.js`` kind of "intercept" the message sent to the pthreads. So they never actually receive the order to start working. I'm not sure if this is intended behaviour or if there is a possible fix?
