### ISSUE TITLE
Is there a size limit in files loaded with --preload-file?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11626]
Hi, I'm using `--preload-file` flag to preload the files to use in my app.

But it seems if the file size gets bigger, it generates some unknown errors when running in the browser.

I think the size limit is somewhere between 9.5 M and 10 M as I tested.

If this is true, is it possible to fix this so I can load more files?

**Comment by kripken** [comment]
I'm not aware of such a limit, and it surprises me. Perhaps a problem with your webserver, or browser?

Doing a quick check in the test suite,
```diff
diff --git a/tests/test_browser.py b/tests/test_browser.py
index ffd2ce88c..a4817ed16 100644
--- a/tests/test_browser.py
+++ b/tests/test_browser.py
@@ -4681,7 +4681,7 @@ window.close = function() {
     self.run_browser('test.html', None, '/report_result?0')
 
   def test_access_file_after_heap_resize(self):
-    create_test_file('test.txt', 'hello from file')
+    create_test_file('test.txt', 'hello from file' + ('.' * 11 * 1024 * 1024))
     create_test_file('page.c', self.with_report_result(open(path_from_root('tests', 'access_file_after_heap_resize.c'), 'r').read()))
     self.compile_btest(['page.c', '-s', 'WASM=1', '-s', 'ALLOW_MEMORY_GROWTH=1', '--preload-file', 'test.txt', '-o', 'page.html'])
     self.run_browser('page.html', 'hello from file', '/report_result?15')
```
Running `./tests/runner.py  browser.test_access_file_after_heap_resize` seems to work - the test fails when it reports the file size is 11MB + 15 bytes instead of 15 which it expects. So looks like it loaded it ok.

**Comment by cuinjune** [comment]
Thank you for your answer.

I could fix the issue by adding the `-s ALLOW_MEMORY_GROWTH=1` flag.
