### ISSUE TITLE
Ways of using poppler ?

### ISSUE THREAD

**Issue by boulabiar** [emscripten-core/emscripten#11666]
According to the documention, poppler is mentioned but it links to a folder containing some pdfs
https://emscripten.org/docs/compiling/Building-Projects.html?highlight=poppler#examples-test-code

There is also a test 
python tests/runner.py test_poppler
but I don't know what it does exactly.

My goal is a simple example showing how to use poppler to read some information from pdf (headers, editor, number of pages etc.) and using pdftotext in a browser environment.

Is there a way to do that and update the documentation to reflect this?

**Comment by kripken** [comment]
The test code loads a PDF in poppler and renders a page or two from it, then verifies the output is correct. See `test_poppler` in `tests/test_core.py`. You can see the `preRun` there adds the input file to the FS, and the `postRun` prints out the result so the test runner can verify it.

The docs link should probably point there. A PR to fix that would be welcome!
