### ISSUE TITLE
shared:ERROR: Js/ExternPost_Compiled.js: Input file has an unknown suffix, don't know what to do with it!

### ISSUE THREAD

**Issue by Satancito** [emscripten-core/emscripten#11664]
**Compile.ps1**

```
em++.bat `
main.cpp `
Inse.bc `
-I ../CppInclude `
-I Include `
-o Libzz.js `
-std=c++17 `
--bind `
-s WASM=1 `
-s DISABLE_EXCEPTION_CATCHING=0 `
-s SINGLE_FILE=1 `
-s ASYNCIFY=1 `
-s VERBOSE=0 `
-O2 `
-s EXPORT_NAME=`'CreateModuleInstance`' `
-s MODULARIZE=1 `
-s ASYNCIFY_IMPORTS=[] `
-s EXPORTED_FUNCTIONS=[`'_main`'] `
-s EXTRA_EXPORTED_RUNTIME_METHODS=[`'ccall`',`'cwrap`',`'lengthBytesUTF8`',`'stringToUTF8`'] `
--pre-js "Js/Pre_Compiled.js" `
--post-js "Js/Post_Compiled.js" `
--extern-pre-js "Js/ExternPre_Compiled.js" `
--extern-post-js "Js/ExternPost_Compiled.js" `
```

When compile, it shows this error
![image](https://user-images.githubusercontent.com/18097869/87726391-8a697900-c784-11ea-8471-a404c59eed18.png)
`shared:ERROR: Js/ExternPre_Compiled.js: Input file has an unknown suffix, don't know what to do with it!`

**The problem**
The compiler options
--extern-post-js <file>
--extern-pre-js <file>
both have same error.

I changed js files to root directory of project. Same error. I change to lowercase filenames and without special chars, same error as:
![image](https://user-images.githubusercontent.com/18097869/87726391-8a697900-c784-11ea-8471-a404c59eed18.png)
![image](https://user-images.githubusercontent.com/18097869/87727399-8179a700-c786-11ea-9be5-a0783160b842.png)
![image](https://user-images.githubusercontent.com/18097869/87727602-e503d480-c786-11ea-9150-ee75f9c3684f.png)

I checked the filenames, they are existing.
![image](https://user-images.githubusercontent.com/18097869/87726734-3f039a80-c785-11ea-8dc2-f8452cf4119a.png)

**Comment by sbc100** [comment]
What version of emscripten are you using (`emcc --version`)

Most likely you are using a version older than 1.39.15 where these flags are not supported.

**Comment by Satancito** [comment]
```
PS C:\Users\Megam> em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.39.11
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sbc100** [comment]
Yup, you need 1.39.15 or above to use those flags

**Comment by Satancito** [comment]
Updating...

**Comment by Satancito** [comment]
No errors. Thanks a lot @sbc100.
