### ISSUE TITLE
why libcxx filesystem has different values of flie_tpe than recommended by isocpp

### ISSUE THREAD

**Issue by Praveer1981** [emscripten-core/emscripten#11676]
Hi ,
Just curious to know why the `file_tpye ` enum  has different values than the values recommended by isocpp ?

**Emscripten:**
https://github.com/emscripten-core/emscripten/blob/0e53ba6943cc54fad836cd9b9d9035d92fbd3893/system/include/libcxx/filesystem#L271

**https://isocpp.org/**
https://isocpp.org/files/papers/P0218r1.html#Enum-file_type

**https://en.cppreference.com/**
https://en.cppreference.com/w/cpp/filesystem/file_type

**https://docs.microsoft.com/**
https://docs.microsoft.com/en-us/cpp/standard-library/filesystem-enumerations?view=vs-2019

**Comment by sbc100** [comment]
The C++ headers we provide come directly from llvm's libcxx: https://github.com/llvm/llvm-project/blob/d41d952be9773ad79fe2563074c612c1f810b83c/libcxx/include/filesystem#L271

What differences are you referring to?  At first glance the looks the same to me.  I must be missing some detail, can you explain the discrepancy that you see?

**Comment by Praveer1981** [comment]
@sbc100 I sorry for the incontinence I was not suppose to post this here. different values are in boost.
