### ISSUE TITLE
Optimizations higher than -O2 causes errors in runtime.

### ISSUE THREAD

**Issue by Satancito** [emscripten-core/emscripten#11679]
Hello friends.

I have previous compiled lib in **.BC format**
**Libzz.bc**. It was compiled with **-O2** Flag. It uses Botan.a (Crypto lib) in linking step.

`em++ Main.cpp ../CppLib/Botan-2.13.0-Emscripten-llvm-Release/lib/libbotan-2.a -o Libzz.bc -O2 -s VERBOSE=1 -s DISABLE_EXCEPTION_CATCHING=0 -r`

All Ok. Compiled successfully. **Libzz.bc**
<hr />

My **Main module**'s command. It uses **Libzz.bc** for link. 
When use:
**-O2, or lower(O0, O1)** flag. Compile OK, when run encryption method execution is OK.
**-O3 or above.**. Compile OK, but when run encryption method throws error and stops execution.

```
em++.bat `
main.cpp `
Libzz.bc `
-I ../CppInclude `
-I Include `
-o Main.js `
-std=c++17 `
--bind `
-s WASM=1 `
-s DISABLE_EXCEPTION_CATCHING=0 `
-s SINGLE_FILE=0 `
-s ASYNCIFY=1 `
-s VERBOSE=0 `
-O2 `
-s EXPORT_NAME=`'CreateModuleInstance`' `
-s MODULARIZE=1 `
-s ASYNCIFY_IMPORTS=[] `
-s EXPORTED_FUNCTIONS=[`'_main`'] `
-s EXTRA_EXPORTED_RUNTIME_METHODS=[`'ccall`',`'cwrap`',`'lengthBytesUTF8`',`'stringToUTF8`'] `
--pre-js "Js/Pre_Compiled.js" `
--post-js "Js/Post_Compiled.js" `
--extern-post-js "Js/ExternPost_Compiled.js" `
--extern-pre-js "Js/ExternPre_Compiled.js" `
```

Is there a way to tell the compiler not to optimize the **Libzz.bc** library but optimize my module **Main.js/Main.wasm**. I assume that when linking with -O3 or higher, the resulting module is optimized in more detail, names/symbols that may be needed in the Botan.a library may be lost. For that reason these errors originate when using that type of optimization -O3+. I wish to optimize my module more, but this limitation keeps me from using -O2.

I have tried 
**Libzz.bc** with -O0 / **Main.js** with -O2 = **All OK**
**Libzz.bc** with -O1 / **Main.js** with -O2 = **All OK**
**Libzz.bc** with -O0 / **Main.js** with -O3 = **ERROR**
**Libzz.bc** with -O0 / **Main.js** with -Oz = **ERROR**
**Libzz.bc** with -O0 / **Main.js** with -Os = **ERROR**

**Libzz.bc** with -O2 / **Main.js** with -O2 = **All OK** The one chosen by me.

But need -O3.

Any help is welcome.

**Comment by kripken** [comment]
`-O3` does do additional optimizations, like metadce and import/export name minification. It's possible that some of your JS makes an invalid assumption for those optimizations, or it could be an unknown bug. To investigate this, finding the full error message with `-O3 --profiling` could help.
