### ISSUE TITLE
Ignore Output When Sourcing emsdk_env.fish

### ISSUE THREAD

**Issue by trisys3** [emscripten-core/emscripten#11677]
When sourcing the env file after installing/activating, I always get a bunch of garbage if I do it from `fish`. This is fine if I only need to source once. The docs don't really say it, but it seems like we need to source on every new terminal, so you'd put it in your `config.fish`.

I can't get rid of the output by appending `>/dev/null`, which removes `stdout`, or even by adding `^/dev/null`, which gets rid of `stderr`. The output must be piped to one of the tertiary file handles that no one uses unless you really, really want the output. I've seen "Password:" prompts be retained when I removed both stdout/stderr, for example.

I used "latest" when installing/activating. Once I cloned/pulled, I ran:

```
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.fish
```

Can we get rid of all this extra output when sourcing the fish env script? It get removed when sourcing in bash, why is it kept with fish?

OS: Ubuntu Focal Fossa
Shell: fish

If you need any more info on my system, please ask.

**Comment by sbc100** [comment]
What is the "garbage" that you are talking about exactly?

We don't have anyone of the team who actually uses the fish shell so if you have any recommendations that would be great.

**Comment by sbc100** [comment]
The messages that `emsdk construct_env` writes are bring written stderr.   But it seems that the `source` command in fish shell doesn't allow for stderr redirect (`2> /dev/null`).   At least from my experimentation.

If I run `emsdk construct_env 2> /dev/null` then it will redirect the stderr messages.   But this doesn't seem to apply when running the source command. 

This could be related: https://stackoverflow.com/questions/59311500/pipe-the-output-of-eval-source-in-fish-shell

We could add some kind of other way to disable the stderr message perhpas?  EMSDK_QUIET=1 maybe?

**Comment by trisys3** [comment]
The correct syntax to redirect to stderr in fish is "^/dev/null". It's one if the things fish did to distinguish itself from the (admittedly pretty old) POSIX standard. I'm not sure why it didn't keep the "2>/dev/null" syntax, or what that even does, but I think it's another file handle, perhaps the equivalent of `bash`'s "3>/dev/null".

I wasn't trying to be dismissive or accusatory. By "garbage", I simply meant that most people probably wouldn't care about the output after the first time, if even then, and that it should be able to be suppressed.

**Comment by sbc100** [comment]
Looks like `2> /dev/null` works too, and might be preferred these days:  https://github.com/fish-shell/fish-shell/issues/4394

In any case it looks like this doesn't work for `source` commands... unlike bash.  In bash I can do `source somescript.sh 2> /dev/null`, but the same thing doesn't work with fish.   So we need to find someway to silence the script.  I think maybe an environment variable is a reasonable way?

**Comment by trisys3** [comment]
Sure, I'm OK with using an environment variable. I'm a little surprised and disappointed this doesn't work properly.
