### ISSUE TITLE
Incorrect behavior of glGetShaderiv with GL_INFO_LOG_LENGTH in library_webgl

### ISSUE THREAD

**Issue by NPIPHI** [emscripten-core/emscripten#11673]
The implementation of glGetShaderiv(GL_INFO_LOG_LENGTH) is incorrect when there is no information log.

in library_webgl.js
`{{{ makeSetValue('p', '0', 'log.length + 1', 'i32') }}};`

returns 1 if log.length == 0, but should return 0 if log.length == 0 according to the opengl standard

**Comment by kripken** [comment]
Thanks @NPIPHI ! I think you're right, this is indeed a bug.

It seems like a simple fix. Do you want to open a PR with that perhaps? If you do and have any questions let us know.

**Comment by NPIPHI** [comment]
I will open a PR. Not familiar with how the js processor works, but I should be able to figure it out.
