### ISSUE TITLE
Should "Blocking on the main browser thread" be warnned when running in worker?

### ISSUE THREAD

**Issue by sky0014** [emscripten-core/emscripten#11680]
Should "Blocking on the main browser thread" be warnned when running in worker?

**Comment by kripken** [comment]
You're right, it shouldn't.

I think the current bug is we assume the main emscripten thread is the main browser thread. But I guess you are running the main emscripten output in a worker? If so we can fix that by checking `!ENVIRONMENT_IS_WORKER` around there, a PR would be welcome!

Or do you see this in another situation?

**Comment by sky0014** [comment]
Yes, that's the situation.
I'm glad to make a PR to fix this.
