### ISSUE TITLE
test_sanity is broken

### ISSUE THREAD

**Issue by tklajnscek** [emscripten-core/emscripten#11696]
test_sanity seems to be broken - CI is reporting failures for the outstanding PRs.

It looks like it broke after https://github.com/emscripten-core/emscripten/pull/11613 because the test expects `run_js` to return only the first line of the output (`full_output = False` by default) whereas it now always returns the whole thing in `run_generated_code` so the test condition needs to be fixed or the behavior of `run_generated_code` changed to match `run_js`

**Comment by sbc100** [comment]
I believe this is an issue with emsdk (which can change underneath us since we always pull it from master during CI).

I think I have a fix.

**Comment by sbc100** [comment]
Actually it looks like I included the fix in #11662.   Can you rebase and confirm?

**Comment by tklajnscek** [comment]
Running now...

**Comment by tklajnscek** [comment]
Yep, works fine now! Thanks @sbc100 :)
