### ISSUE TITLE
"cmake" works but "emcmake cmake" throws an error

### ISSUE THREAD

**Issue by divyanshusahu** [emscripten-core/emscripten#11697]
I hope this is a correct place to ask this question.
When I build my project using `cmake ..` it works just fine.

```bash
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/manjaro-kde/Downloads/shellz/trunk/build
```

But when I tries to build the same project with `emcmake cmake ..` it's giving me the following error.

```bash
CMake Error at src/shellz/CMakeLists.txt:20 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

Any help will be appreciated. Thanks.

**Comment by kripken** [comment]
The main difference between the two is that normal cmake looks in your system libraries for things. If it's looking for Qt and you have Qt installed, that will work. But emscripten is a cross-compiler and it can't use your system libraries which are compiled to x86 or ARM etc.

Probably best to ask this on the Qt side, though, as I assume you'll need to install Qt for emscripten, which they have support for.

**Comment by divyanshusahu** [comment]
Hey, @kripken Thanks for pointing out in the right direction. It works.

Those who will face this same issue in the future, these two links help me a lot.
[https://doc.qt.io/qt-5/wasm.html](https://doc.qt.io/qt-5/wasm.html)
[https://gist.github.com/cajus/689eca85be257997019065979799e2f6](https://gist.github.com/cajus/689eca85be257997019065979799e2f6)

I am closing this issue now.
