### ISSUE TITLE
What's the easiest way to implement a virtual filesystem in JS?

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#11709]
I'm not sure if this is feasible, but this is what I'm trying to accomplish:

I have a C++ application that is a command-line utility that opens and saves files (... doing complex processing of the content as well). Some of the paths are passed through the command-line, but many paths are either inferred from the source names or read from the source files.

This code can be compiled with Emscripten using NODERAWFS and works great.

I'd like to provide a library-like interface to this code, so that the command-line utility is just a thin wrapper that implements raw filesystem access. For this to work without changing the C++ implementation, I'd need to use a virtual filesystem, like MEMFS. However, MEMFS expects the files to already be there when C++ code requests them, so it's not possible to implement raw filesystem on top of that.

Ideally I'd like to use something like MEMFS but install callbacks that, given a path to the file, can, for example, open the real file from the file system and copy the contents to MEMFS (or return a file-like object that the Emscripten library can read directly from, or some combination thereof).

Is there any way to inject some sort of callback-based interface as a file system implementation? Preferably without reimplementing everything that the file system needs :) My alternative route would be to make sure C++ code only ever accesses files through something other than fopen/fread/etc. but I'm trying to figure out if there's an alternate path that uses existing Emscripten's file system interface and implementation.

**Comment by sbc100** [comment]
If the files are backed by the real filesystem then what its wrong with just continuing to use NODERAWFS?

If you have some file that don't live on the disk you could mount a MEMFS at a certain mountpoint and have NODERAWFS as the root fs?

I guess I'm not exactly sure what the purpose of having a MEMFS that is backed by the rawfs is?  How is that preferable to just using the rawfs?

**Comment by kripken** [comment]
I think you can do this with a custom FS. See for example IDBFS which builds on MEMFS, not sure if you can do it in the exact same way, but might be helpful,

https://github.com/emscripten-core/emscripten/blob/master/src/library_idbfs.js#L21

**Comment by zeux** [comment]
> I guess I'm not exactly sure what the purpose of having a MEMFS that is backed by the rawfs is? How is that preferable to just using the rawfs?

It doesn't have to be memfs, but the idea was to compile the code as a library (reactor?) using Emscripten once, and then have the JS code use that and provide rawfs functionality without maintaining two different binary builds.

**Comment by kevzettler** [comment]
BrowserFS https://github.com/jvilk/BrowserFS

The internet archive has a good example of using BrowserFS to simulate a file system that they use with an Emscripten port of DosBox. They are able to mount the BrowserFS filesystem so dosbox can read it:

http://ascii.textfiles.com/archives/4924


https://github.com/dreamlayers/em-dosbox
