### ISSUE TITLE
alcMakeContextCurrent incorrectly returns ALC_FALSE

### ISSUE THREAD

**Issue by xanather** [emscripten-core/emscripten#11708]
Using the provided emscripten OpenAL implementation:

After making any context current with alcCreateContext + alcMakeContextCurrent and then calling
alcMakeContextCurrent(nullptr) incorrectly returns ALC_FALSE.

Setting alcMakeContextCurrent to null is necessary before alcDestroyContext and alcCloseDevice.

**Comment by xanather** [comment]
Bump to avoid it being closed.
Definitely not correct functionality described in OpenAL 1.1 docs.

Its a rather minor inconvenience, I may look at digging into the source sometime in the future to sort it, otherwise someone else feel free for an easy bug to fix!

**Comment by sbc100** [comment]
Bump again.  @xanather how do you feel about putting together a PR for this?

**Comment by sbc100** [comment]
Actually I took care of it in: https://github.com/emscripten-core/emscripten/pull/17591
