### ISSUE TITLE
EXPORT_ES6 in the new version

### ISSUE THREAD

**Issue by Johnly1986** [emscripten-core/emscripten#11702]
WARNING:root:Assigning a non-existent settings attribute "EXPORT_ES6"
WARNING:root: - did you mean one of EXPORT_NAME, EXPORT_ALL, EXPORT_BINDINGS?
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
WARNING:root:Assigning a non-existent settings attribute "USE_ES6_IMPORT_META"
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
------------------------------------------------------------------------------------------------------------------------
Is this option canceled in the new version? What should be done?

**Comment by sbc100** [comment]
What version are you using?  It looks like maybe an old version.  That option works fine for me:`

What does `emcc --version` say?   it should say something like `1.39.19` or `1.39.20`

**Comment by Johnly1986** [comment]
1.35.0 ，This may be the latest installation.&nbsp;



---Original---

**Comment by sbc100** [comment]
1.35.0  is from 2015 and (I guess) does not include the EXPORT_ES6.  You should updated to a more recent version.   The latest version is 1.39.20.
