### ISSUE TITLE
Stuttering performance under very light load.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#1170]
Something that I've long observed, and now got around to making a test case of: https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/bin/Pong.html

The demo utilizes very simple rendering and only submits one GL clear() and one dynamically-built VBO draw call per frame.

On Windows 7, in Firefox 20 and Firefox nightly (built about a week ago), the resulting animation stutters continuously, as if it's missing vsync intervals. In Chrome 26, the animation is noticeably smoother, and only rarely stutters.

When run as a native .exe, the application also runs smoothly. When vsync is disabled, the native exe runs at about 1200fps.

Some properties:
- the app uses emscripten built-in emscripten_set_main_loop mechanism with emscripten_set_main_loop(EmscriptenRenderWindow, 0, 0);
- the game update is set to fixed timestep of 1/60 seconds.
- whenever the detected timestep is above 19 msecs (==16.66ms + a small arbitrary number), the screen is flashed red, and an error message is printed to console.

The stuttering is most noticeable in the movement of the ball. The weird part is that when stuttering occurs, the screen does not always flash red (so the game update loop does run at a good framerate), but visually observed, it looks as if presentation did not occur on proper vsync intervals.

Running at fullscreen (press the fullscreen button on the page) improves the situation a bit, but still does not make it as smooth as Chrome.

For reference, the application source code is available at https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/mainPong.cpp . Unfortunately the framework code itself is not available.

Looking at Firefox nightly with the SPS profiler looks like this:
https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/pong-stutter.png
https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/pong-stutter-2.png
which indicates that the browser is idle most of the time as well, and executing the game update and render loop takes only a minimal time.

The application was compiled with -O2 --minify 0 --closure 0.

Anyone able to reproduce, or is it just my eyes? :)

**Comment by robozo** [comment]
Just a note, stuttering issue still present in Chrome, though Firefox and Safari run OK.
This is not under "light load", though, I'm throwing 500,000 dots on the screen each frame.
https://virtyou.com/logistic          (zoom in with shift up arrow)
For some reason, when the stuttering occurs, it can sometimes be relieved by reloading a few times.

**Comment by kripken** [comment]
@robozo it looks equally smooth to me in firefox and chrome. But I'm just estimating that visually. I'd suggest adding a measurement to put a number on it, and file a bug on chromium if you see chrome does poorly.
