### ISSUE TITLE
Anyway to return back to Main from callback?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11706]
I know at least in Javascript, it's impossible to get out from Callbacks means I have to write all the rest code inside call back. 
Now, I don't know whether this is same with Emscripten. Can anybody confirm?

I would love to have a way to Jump back to the main() and continue the execution from there

**Comment by gerald-dotcom** [comment]
I mean this is really neat and can avoid callback hell.

**Comment by sbc100** [comment]
Yes we have something called ASYNCIFY which does pretty much what you describe.  It allows you to yield from a wasm function, run the main loop (callbacks etc) and then return to where you left off:

https://emscripten.org/docs/porting/asyncify.html

**Comment by gerald-dotcom** [comment]
> Yes we have something called ASYNCIFY which does pretty much what you describe. It allows you to yield from a wasm function, run the main loop (callbacks etc) and then return to where you left off:
> 
> https://emscripten.org/docs/porting/asyncify.html

I have used Asyncify before and totally forget that I could use it for Fetch.
