### ISSUE TITLE
Reading preloaded files gives incorrect results.

### ISSUE THREAD

**Issue by nxtexe** [emscripten-core/emscripten#11710]
I'm fairly new to emscripten but I've been working on a small graphics application for a bit now and I preloaded my shader files when compiling my code to wasm. On the development server everything works as expected, the shader files are read correctly and work fine. However when I upload my web app to pythonanywhere.com hosting for some reason when I try to read the file it gives me incorrect data.
![Screenshot_575](https://user-images.githubusercontent.com/50880261/88307572-b8dddb80-ccd1-11ea-92c0-dfdb9c62657c.png)
This is what the a.out.data file looks after compilation.
![Screenshot_576](https://user-images.githubusercontent.com/50880261/88307571-b8dddb80-ccd1-11ea-8e85-0d292e136f32.png)
This is how the a.out.data file looks in the network tab of the browser when the page is loaded.
![Screenshot_577](https://user-images.githubusercontent.com/50880261/88307568-b8454500-ccd1-11ea-8139-2616f72ba47c.png)
But this is what the shaders files look like when I read them from within the application and print them to the console.
As you can see this causes a nasty error. The Invalid UTF-8 leading byte 0x-7f error was particularly confusing to me.
Does anyone know what I'm missing?

**Comment by sbc100** [comment]
Are are you generating a.out.data?  Iouts it bring produced by emscripten or are you creating it?  How are you then loading it in your emscripten code?  How are you printing it to the console?

It looks like a null termination issue, like the string is not null terminated and so JS is trying to read past the end of the string and getting garbage?

**Comment by nxtexe** [comment]
> Are are you generating a.out.data? Iouts it bring produced by emscripten or are you creating it? How are you then loading it in your emscripten code? How are you printing it to the console?
> 
> It looks like a null termination issue, like the string is not null terminated and so JS is trying to read past the end of the string and getting garbage?

I'm generating a.out.data by passing the -preload-files option to emcc. I load it into emscripten as if I were reading any other file. Are you familiar with the preload-files flag? It doesn't seem like you are.

**Comment by sbc100** [comment]
I'm not very familiar with that option no.   

Its seems very strange that this would work in one server but not on another.  

Does the size of the file you are seeing on the emscripten differ (i.e. are there any extra bytes reported).

I would try adding some debugging to the code that is generated by the `file_package.py` which is supposed to load this.   You could see at what point the corruption/change occurs.  Look for `getPreloadedPackage` either in the final output JS or in `file_package.py` which generates it and try adding some debugging there maybe?

**Comment by nxtexe** [comment]
> I'm not very familiar with that option no.
> 
> Its seems very strange that this would work in one server but not on another.
> 
> Does the size of the file you are seeing on the emscripten differ (i.e. are there any extra bytes reported).
> 
> I would try adding some debugging to the code that is generated by the `file_package.py` which is supposed to load this. You could see at what point the corruption/change occurs. Look for `getPreloadedPackage` either in the final output JS or in `file_package.py` which generates it and try adding some debugging there maybe?

I seemed to have fixed the issue. The way I transfer the code for my webserver to my hosting platform is by github, for some reason github was modifying the code in some way, shape or form. I got around this and the reason I know this is by using the file editor functionality offered by my hosting platform, I simply copied the contents of the a.out.data file from my local drive to my hosted webserver online using this file editing tool, and it worked. I will further investigate why github had failed in this way. I will now close this issue.
