### ISSUE TITLE
Module.modulePromiseResolve is not a function

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11718]
I want to load a dynamic lib on the fly and found a code that can do it,

```
	let url = UTF8ToString(str);
	loadDynamicLibrary(url, {loadAsync: true, global: true, nodelete: true}).then(
	() => {
		Module.modulePromiseResolve() 
	});
```

I see that it made calls to URL when I open network tab but it fail at Module.modulePromiseResolve() stage

I have no idea what Module.modulePromiseResolve()  do

**Comment by sbc100** [comment]
modulePromiseResolve doesn't look like something that is part of emscripten.   Where is this code coming from?

**Comment by gerald-dotcom** [comment]
Actually from https://github.com/emscripten-core/emscripten/issues/8302 here

**Comment by gerald-dotcom** [comment]
@sbc100  Searching on Github led me to here,

https://github.com/fibbo/WebAssemblyTests/blob/88a477e33da8fb56940e3f3f4143f277de3c77d4/dynamic_linking_mwe/dyn_linking_mwe.html

But again, the code is hard to understand.

**Comment by gerald-dotcom** [comment]
Figured out clean way to do this. Closing ..
