### ISSUE TITLE
How would one import a method declared in a class to ASYNCIFY_IMPORTS?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11727]

**Comment by kripken** [comment]
I think just like any other function, by its name. For example, the test suite has this:
```
tests/test_core.py:    'onlylist_b': (['-s', 'ASYNCIFY_ONLY=["main","__original_main","foo(int, double)","baz()","c_baz","Structy::funcy()"]'], True),
```
I believe Structy is a class, and funcy a function in it. You can read the code in the test suite for more.
