### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11722]
I wanted try emscripten with C++ classes and ran into multiple issues, while many got solved, now a new error appeared and I can't find root cause for it. 

main.cpp
```
#include <iostream>
#include <vector>
#include <set>
#include <string>
#include <algorithm>
#include <iterator>
#include <dlfcn.h>
#include <emscripten.h>
#include <emscripten/val.h>
#include <emscripten/fetch.h>
#include <emscripten/bind.h>
#include <nlohmann/json.hpp>
#include "CoreModule.h"

int main() {
    CoreModule instance1;

    std::cout << instance1.getProcessorsCount() << "\n";
}
```

CoreModule.h
```
#include <iostream>
#include <vector>
#include <set>
#include <string>
#include <algorithm>
#include <iterator>
#include <emscripten.h>
#include <emscripten/val.h>
#include <emscripten/fetch.h>
#include <emscripten/bind.h>

class CoreModule  {
   public:
      int getProcessorsCount();
}
```

CoreModuleMethods.cpp
```
#include <iostream>
#include <vector>
#include <set>
#include <string>
#include <algorithm>
#include <iterator>
#include <emscripten.h>
#include <emscripten/val.h>
#include <emscripten/fetch.h>
#include <emscripten/bind.h>
#include "CoreModule.h"


int CoreModule::getProcessorsCount() {
    emscripten::val window = emscripten::val::global("window");

    processorCount = window["clientInformation"]["hardwareConcurrency"].as<int>();
    return processorCount;
}
```

I compile using `em++ Main.cpp -o Entry.js -Oz --bind -I C:\Project\CoreE -s MODULARIZE=1 -s MAIN_MODULE=1  -s EXPORT_ALL=1 -s "EXPORT_NAME='CEntry'" -s DISABLE_EXCEPTION_CATCHING=0 -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1
`

The same code work fine without classes. I am not sure why!

**Comment by sbc100** [comment]
Try building without `-0z` (i.e. `-O0`) which enables assertions which will often give you better error messages in cases like this.

**Comment by gerald-dotcom** [comment]
@sbc100 Now I see this,

external function '_ZN11CoreModule11getProcessorsCountEv' is missing. perhaps a side module was not linked in? if this function was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment

**Comment by gerald-dotcom** [comment]
Ok, I figured it out, I have to link CoreModuleMethods.cpp and it works..
