### ISSUE TITLE
JS cannot load in 1.39.19 ("function Object() { [native code] }")

### ISSUE THREAD

**Issue by JCash** [emscripten-core/emscripten#11740]
We just moved from 1.39.16 to 1.39.20, and this new version produces strange code that won't even load in the browser:

> ...213);E()}function Object() { [native code] }(a,b){var c=0,...

This is when compiled with O3.
With O1/O0 it doesn't produce this code.

Searching for this code snippet, it seems related to Node.js, which seems you have updated from 12.9.1(1.39.18) to 12.18.1 (1.39.19).

Attached is a built .js file and its symbols.
[emscripten_issue.zip](https://github.com/emscripten-core/emscripten/files/4987051/emscripten_issue.zip)

**Comment by kripken** [comment]
How about `-O2`?

It's hard to figure out from the final build files. Can you build with `EMCC_DEBUG=1` and provide the temp files from `/tmp/emscripten_temp/emcc-*`?

**Comment by JCash** [comment]
The O2 displays the same behavior as O1 and O3, with the "[native code]" part in it.

Here's an executable built with O2, and the requested `emcc-*` files:
[dmengine_O2.zip](https://github.com/emscripten-core/emscripten/files/5010008/dmengine_O2.zip)

**Comment by kripken** [comment]
Thanks, but after investigating for a while I'm stuck as these are minified. Can you provide the files when built with `--profiling`? (assuming that doesn't make the bug go away; if it does, then at least `-g1`) Also there should be a few more files in the temp dir, like `wasm2js-output.js` that is crucial to debug this.

**Comment by JCash** [comment]
[dmengine_o2_g1.zip](https://github.com/emscripten-core/emscripten/files/5011769/dmengine_o2_g1.zip)

The `--profiling` flag made the issue go away, so I added the `-g1` as you suggested.
I also attached the contents of the `emscripten_temp` folder.
