### ISSUE TITLE
Enable shared memory without explicit pthreads support

### ISSUE THREAD

**Issue by rnewman** [emscripten-core/emscripten#11750]
I use `emcc` to build some code with `STANDALONE_WASM` to run in restricted environments in which the complex environment code provided by a standard Emscripten build is not appropriate.

For example, I would like to be able to share memory and a `WebAssembly.Module` between a worklet and a worker in order to offload expensive operations.

This seems theoretically possible: if the WebAssembly module uses `(memory … shared)` to create its memory region, and `(memory.atomic*)` for access, then the embedding context can handle sharing the memory and creating the workers.

I am running into two snags:

* If I pass `-Wl,--shared-memory` in the build, I get `wasm-ld: error: 'atomics' feature must be used in order to use shared memory'` (and the same for `bulk-memory`). I can't find a way to enable atomics or bulk memory without setting `USE_PTHREADS=1`, but doing so hits `emcc: error: STANDALONE_WASM does not support pthreads yet`.
* I don't see any docs explaining how these atomic operations reflect into C without using the pthreads API. Is it `<stdatomic.h>`? If not, are there any docs on how to inline `wat` into C source or link it appropriately?

Advice from experts would be much appreciated.

**Comment by tlively** [comment]
Try passing -mbulk-memory and -matomics at compile time to enable those
respective target features without opting into anything else -pthread
entails. Note that hacking around Emscripten's pthread support like this is
entirely untested, so it's possible you will run into some other snag.

**Comment by sbc100** [comment]
I would recommend passing `-pthread` to the compiler and the linker.   Otherwise you won't get the correct version of libc and other standard libraries.

Then you will have to implement any resulting undefined symbols.  (.e.g pthread_create).. but really there is no way around doing this.  Its kind of the minimum bar.

**Comment by tlively** [comment]
Oh right, mixing the single-threaded standard library with atomics-enabled
user code will produce another linker error. Sam, using -pthread leads to
the "emcc: error: STANDALONE_WASM does not support pthreads yet" error. Is
that not supported just because all the pthreads library code is
implemented in JS?

**Comment by sbc100** [comment]
Looks like the next problem requires a binaryen side fix:

```
Fatal: cannot apply sbrk-val since memory is not flattenable
```

**Comment by Julio-Guerra** [comment]
Hello @rnewman, did you figure out a solution? I am also willing to compile with atomic operations and shared memory.

**Comment by rnewman** [comment]
I did not: no progress beyond explicit `SharedArrayBuffer` and copying.

As far as I can tell, only the common "cowpath" through Emscripten — the script-tag-in-a-page one — is paved, and the rest is pretty rocky. It took quite a lot of experimentation just to get `STANDALONE_WASM` to a place that worked for me, so now I'm mostly not touching it and hoping it never breaks!

**Comment by PoignardAzur** [comment]
> As far as I can tell, only the common "cowpath" through Emscripten — the script-tag-in-a-page one — is paved, and the rest is pretty rocky.

As someone working on porting a C lib to JS through wasm (and web-workers, for extra headaches), I definitely feel your pain.

**Comment by RReverser** [comment]
I wonder if this is now resolved via WASM_WORKERS. cc @juj (I haven't looked into them deeply though)

**Comment by sbc100** [comment]
Indeed we now have the `-sSHARED_MEMORY` flag for exactly that (IIUC).
