### ISSUE TITLE
wasm-ld: error: unknown argument: -force_load, -single_module

### ISSUE THREAD

**Issue by adminy** [emscripten-core/emscripten#11764]
during emconfigure step fails with:

`wasm-ld: error: unknown argument: -force_load`

also some other errors like: 
`wasm-ld: error: unknown argument: -single_module`
occur before that.

**Comment by sbc100** [comment]
We don't support either of those flags.

Those both looks like mac-only linker flags.

For `-force_load`, see https://stackoverflow.com/questions/25038974/force-load-linker-flag-for-other-platforms.

Are you run emconfigure on mac BTW?     Does the same error occur on linux?

**Comment by adminy** [comment]
Yeah, like you I tried libde265 with the latest emscripten on mac. No luck, so I tried it in docker container, both debian and ubuntu. still no luck.

**Comment by sbc100** [comment]
Is the project hardcoded to only build on mac?   If you look at the build system you can probably find the place there those mac-specific flags and modify them.  If there is a linux build then those flags should work with emscripten.

**Comment by fasiha** [comment]
I encountered `single_module` when building https://github.com/taku910/mecab (clone, `cd mecab/mecab; emconfigure ./configure; emmake make`), on macOS 10.15.6.

The `configure` script pointed out that this could be disabled by setting LT_MULTI_MODULE environment variable to non-empty. That did the trick, `emmake make` finished successfully. Thanks for the tip @sbc100!
