### ISSUE TITLE
Getting 'using stub malloc/ free' from sdl

### ISSUE THREAD

**Issue by innova-engineering** [emscripten-core/emscripten#11769]
Hi,

we try to compile an application and get the warning:
```
using stub malloc (reference it from C to have the real one included)
using stub free (reference it from C to have the real one included)
```
coming seemingly from `_emscripten_webgl_create_context` and `_SDL_FreeSurface`.
We are running into memory issues and end up with:
```
Cannot enlarge memory arrays to size 135946512 bytes (OOM). Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 134217728, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
```

But we should have a lot less memory in use.
We use malloc and free in our c/c++ code and this seems to work, At least we do not call the stub malloc and free functions.
Memory profiler shows about 90mb free memory befor the crash.

We compile with this flags:
``` 
-DNDEBUG -O2   -s USE_ZLIB=1 -s FORCE_FILESYSTEM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=FS -s ALLOW_MEMORY_GROWTH=0 -s TOTAL_MEMORY=128MB -s ASSERTIONS=2 -s LLD_REPORT_UNDEFINED -s EXPORTED_RUNTIME_METHODS=['ccall','cwrap','UTF8ToString'] -s EXPORTED_FUNCTIONS=['_main', **more exportedFunctions**] -O2 --use-preload-plugins --preload-file **filepath to file** --memoryprofiler -s USE_BULLET=1 -s FETCH=1
```

Its seems as if for example sdl use the dummy malloc, free functions. Any idea what is going wrong here? Did we miss something? We would be very glad for suggestions.

**Comment by kripken** [comment]
What version is that on? I think we removed those stubs, so this type of problem should no longer be possible, on recent releases.

**Comment by innova-engineering** [comment]
We are observing this on version 1.39.8. Can you give us some hint (e. g. changelog reference) on how or where to look for a possible fix?

**Comment by kripken** [comment]
Searching for that text in the git history, looks like they were removed in #10825 which was shipped in 1.39.12.

**Comment by innova-engineering** [comment]
Ok great, thanks.

**Comment by innova-engineering** [comment]
We've upgraded to 1.40.1 and this fixed the memory issues we observed.
Also we do not get the "stub malloc/free" related notifications any longer.

Thanks for pointing this change out, we did not find any hint for it in ChangeLog.md .
