### ISSUE TITLE
Remove static allocation from JS compiler

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11773]
We have a function in the JS compiler called `makeStaticAlloc` that can allocate static data *after* the linker has run.

This can be a useful feature but it comes with a lot of extra code complexity and downsides.

The biggest problem is that the linker traditionally assumes that it controls data layout, and knows the start and end of the data, stack, and heap regions.    With emscripten we have hacks to retroactively update the internal `__stack_pointer` and inject the stack limit in some cases.    It also confuses code that relies on linker-generated symbols such as `edata`.

The second problem is that any such allocations are not available in standalone mode.

The more of these allocations we can push into native code the fewer JS hacks we will need and the fewer magic binaryen step will be needed.  Giving the linker visibility of all these symbols also allows gives it a better chance to do DCE and results in a wasm binary with fewer imports.

For example `emscripten_stack_get_base` and `emscripten_stack_get_end` currently call out to JS which is bad for performance and code size and portability.

**Comment by sbc100** [comment]
I've tried to do this in the past of found some places where it was hard/impossible for me to replace `makeStaticAlloc`, but I'd like to try again :)

**Comment by sbc100** [comment]
Removing `makeStaticAlloc` would also remove `STATIC_BUMP` from the JS codebase, which would simplify a lot of code.

**Comment by gerald-dotcom** [comment]
Out of curiosity, Can this affect Asyncify?

**Comment by kripken** [comment]
@sbc100 sounds good - we should probably wait for fastcomp removal first though to avoid extra complexity and work.

I imagine this would require moving a bunch of things from JS into C or .s files, which should be a good improvement for them anyhow.

@gerald-dotcom I don't think asyncify does static allocations (it does dynamic allocations, but those are fine)

**Comment by kripken** [comment]
Was this intentionally closed? I think that PR might have closed the wrong issue @sbc100

**Comment by sbc100** [comment]
I think that PR referenced this issue, but I didn't mean to close it.
