### ISSUE TITLE
std::uncaught_exception() is true after the exception has been caught

### ISSUE THREAD

**Issue by ImplOfAnImpl** [emscripten-core/emscripten#11776]
In the following code `std::uncaught_exception()` returns true when it shouldn't:
```
// ems_test.cpp
#include <exception>
#include <iostream>

struct Base
{
    virtual ~Base() {}
};

struct Exception: public Base, public std::exception
{
};

int main()
{
    try
    {
        throw Exception();
    }
    catch (const std::exception&)
    {
    }

    if (std::uncaught_exception())
    {
        std::cout << "!!! Not OK" << std::endl;
    }
    else
    {
        std::cout << "OK" << std::endl;
    }
}
```
```
$ em++ -s DISABLE_EXCEPTION_CATCHING=0 -o ems_test.js ems_test.cpp && node ems_test.js
!!! Not OK
```
I've run the code in a debugger and noticed that  [`__cxa_begin_catch`](https://github.com/emscripten-core/emscripten/blob/master/src/library_exceptions.js#L173) receives the 'adjusted' version of the exception pointer, which is not among the keys in `exceptionInfos`. So probably it should first be de-adjusted with `exception_deAdjust` (it worked for me).

**Comment by kripken** [comment]
Thanks @ImplOfAnImpl , yes, a fix might be needed...

Trying it on CI, a few things fail, see https://github.com/emscripten-core/emscripten/commit/123907c0607ed7ee904d8fe943bdf3d20bd37783 so this needs more investigation if you have time.

**Comment by ImplOfAnImpl** [comment]
I'm not an expert on this, but [the Itanium ABI documentation](https://itanium-cxx-abi.github.io/cxx-abi/abi-eh.html#cxx-catch) says that `__cxa_begin_catch` should return the adjusted pointer.
I.e. with the following changes:
```
--- a/src/library_exceptions.js
+++ b/src/library_exceptions.js
@@ -171,17 +171,18 @@ var LibraryExceptions = {
 
   __cxa_begin_catch__deps: ['$exceptionInfos', '$exceptionCaught', '$exception_addRef', '$exception_deAdjust', '_ZSt18uncaught_exceptionv'],
   __cxa_begin_catch: function(ptr) {
-    var info = exceptionInfos[ptr];
+    var deAdjustedPtr = exception_deAdjust(ptr);
+    var info = exceptionInfos[deAdjustedPtr];
     if (info && !info.caught) {
       info.caught = true;
       __ZSt18uncaught_exceptionv.uncaught_exceptions--;
     }
     if (info) info.rethrown = false;
-    exceptionCaught.push(ptr);
+    exceptionCaught.push(deAdjustedPtr);
 #if EXCEPTION_DEBUG
     err('cxa_begin_catch ' + [ptr, 'stack', exceptionCaught]);
 #endif
-    exception_addRef(exception_deAdjust(ptr));
+    exception_addRef(deAdjustedPtr);
     return ptr;
   },
```
all the `test_exception*` tests pass for me.

**Comment by kripken** [comment]
Oh, yes, I think you're right @ImplOfAnImpl , good point!

That looks promising, but meanwhile I verified that #11518 fixes this issue as part of that refactoring - so I think we can just wait for that to land actually.
