### ISSUE TITLE
Document existence and usage of "official" emsdk docker images.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11772]
We should probably point ppl to them in the same way point them to the emsdk from the official emscripten docs.

**Comment by sbc100** [comment]
@trzecieu, @azakai , if either of you feel like grabbing this please do

**Comment by sbc100** [comment]
@RReverser

**Comment by RReverser** [comment]
Cross-posting suggestion from chat: I think the best place to document these would be on https://emscripten.org/docs/getting_started/downloads.html by adding a new "Usage from Docker" section and updating the Note which currently mentions Docker images only as an unofficial / unsupported 3rd-party thing.

**Comment by trzecieu** [comment]
So, I don't know what's the best way to redirect people. 
Definitely I don't want to break all builds by removing repo / pushing dummy image. 

At the moment I've added info to the header about deprecation: https://hub.docker.com/repository/docker/trzeci/emscripten
I was thinking to change `emcc` / `em++` to print some message while building. That would not break peoples' builds and will be pretty verbose at the same time. 

Do you have some ideas what can be done more?

**Comment by sbc100** [comment]
I think simply redirecting people in the README of the docker hub page is fine for now.

People using your latest images without looking that that page will eventually realized they are on an old version an go looking for the upgrade path.

**Comment by RReverser** [comment]
> At the moment I've added info to the header about deprecation: [hub.docker.com/repository/docker/trzeci/emscripten](https://hub.docker.com/repository/docker/trzeci/emscripten)

I think this notice looks pretty good and self-explanatory. Although I'm not sure about "IS TO BE DEPRECATED" wording - is it technically not deprecated yet?
