### ISSUE TITLE
emscripten_set_main_loop doesn't work

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11777]
I don't see anything get printed out. @kripken see below for test case,

```
#include <iostream>
#include <string>
#include <algorithm>
#include <iterator>
#include <emscripten.h>
#include <emscripten/val.h>

void mainLoop() {
   std::cout << "Hi from Whatever It's!" << "\n";
}

int main() {
   // Set up an Infinite Loop 
   emscripten_set_main_loop(mainLoop, 0, 0);

   return 0;
}
```

Build with, 

`em++ Engine.cpp -s MODULARIZE=1 -s EXPORT_ALL=1 -s DISABLE_EXCEPTION_CATCHING=0 -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s "EXPORT_NAME='CoreEngine'" -o Engine.js `

**Comment by kripken** [comment]
The testcase works fine with just `em++ file.cpp -o a.html`. So one of your flags must be wrong.

I think it's MODULARIZE - see the docs in settings.js, it just creates a factory function, you also need to create an instance.

**Comment by gerald-dotcom** [comment]
> The testcase works fine with just `em++ file.cpp -o a.html`. So one of your flags must be causing the issue.
> 
> I think it's MODULARIZE - see the docs in settings.js, it just creates a factory function, you also need to create an instance.

I already knew about creating an instance. I've already done it months ago, just started to use this loop thing for pulling some stuff. 

`em++ Engine.cpp -s MODULARIZE=1 -s WASM=1 -s "EXPORT_NAME='CoreEngine'" -o Engine.js
`
This didn't worked out either. I've removed all flags that I suspect of but it didn't work either.....
