### ISSUE TITLE
Multiple -s flags in CMake cause malformed make files

### ISSUE THREAD

**Issue by cmannett85** [emscripten-core/emscripten#11789]
Using em++ 1.39.19 (f45bea21f3a8f74a68ed4e3e3d7e290807ee2aff), and CMake 3.16.  Using a CMake file that contains this instruction:
```
target_compile_options(my_app
    PRIVATE --std=c++20 -Werror -Wall -Wextra -s USE_BOOST_HEADERS -s USE_PTHREADS
)
```
Executing `emcmake cmake ...` results in this entry in `flags.make`:
```
CXX_FLAGS = -DNDEBUG -O2   --std=c++20 -Werror -Wall -Wextra -s USE_BOOST_HEADERS USE_PTHREADS
```
As you can see the second `-s` flag (and indeed all subsequent ones too) is missing.  This understandably results in this compilation error:
```
em++: error: USE_PTHREADS: No such file or directory ("USE_PTHREADS" was expected to be an input file, based on the commandline arguments provided)
```
I've tried putting them inside another CMake variable, and using a new `PRIVATE` section per `-s` entry, nothing changed the generated Makefile.

**Comment by cmannett85** [comment]
Nevermind, it's a CMake thing.  Buried in the last paragraph of the [docs](https://cmake.org/cmake/help/v3.16/command/target_compile_options.html#arguments):

> One may specify a group of options using shell-like quoting along with a SHELL: prefix. The SHELL: prefix is dropped, and the rest of the option string is parsed using the separate_arguments() UNIX_COMMAND mode. For example, "SHELL:-D A" "SHELL:-D B" becomes -D A -D B.

So my CMake command should be:
```
target_compile_options(my_app
    PRIVATE --std=c++20 -Werror -Wall -Wextra "SHELL:-s USE_BOOST_HEADERS" "SHELL:-s USE_PTHREADS"
)
```

**Comment by sbc100** [comment]
The point of https://github.com/emscripten-core/emscripten/pull/11550 was to allow this to work without the need for the `SHELL` thing, but you also need to join your `-s` flags to the argument without a space between them.

e.g.:

```
target_compile_options(my_app
    PRIVATE --std=c++20 -Werror -Wall -Wextra -sUSE_BOOST_HEADERS -sUSE_PTHREADS
)
```
