### ISSUE TITLE
Document the need for SDL_RENDERER_PRESENTVSYNC in SDL2 (more optimal, and avoids emscripten_set_main_loop warning about using <= 0)

### ISSUE THREAD

**Issue by adam4235** [emscripten-core/emscripten#11788]
The emscripten_set_main_loop function takes a fps parameter for the frame rate.  There's a warning that appears in the Web Console which is saying that it's ideal to set that to be <= 0 ("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!").

However, I'm getting that warning even when I pass 0 or -1 to the fps parameter.  Is the warning mistaken?

I don't notice any difference in the rendering regardless of whether I use 0, -1, or 60 for that parameter.

**Comment by kripken** [comment]
That sounds like a bug, yes.

Do you have a small testcase? I don't see it locally when trying examples in the test suite.

**Comment by adam4235** [comment]
The warning appears for me with this minimal test case.  I found that when I remove the call to SDL_CreateRenderer, the warning no longer appears.  Compiled with:

`em++ fps_bug.cpp -s USE_SDL=2 -std=c++11 -o index.html`

```
#include <iostream>
#include <cassert>

#include <SDL.h>

#include <emscripten.h>

using namespace std;

namespace {
    /** The main SDL window */
    SDL_Window* window = NULL;
    /** The renderer used to render to the screen */
    SDL_Renderer* renderer = NULL;
    /** True if we need to create the window on the current iteration of the event loop */
    bool needCreateWindow = true;
}

void mainLoopFunction()
{
    if (needCreateWindow) {
        std::pair<int, int> windowSize;

        windowSize.first = 1024;
        windowSize.second = 768;

        window = SDL_CreateWindow("Window",
                SDL_WINDOWPOS_CENTERED_DISPLAY(0), SDL_WINDOWPOS_CENTERED_DISPLAY(0),
                windowSize.first, windowSize.second,
                (SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE));

        assert(window);
        renderer = SDL_CreateRenderer(window, -1, 0);
        assert(renderer);
        needCreateWindow = false;
    }
}

int main(int argc, char** args)
{
    if (0 != SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_TIMER | SDL_INIT_JOYSTICK | SDL_INIT_GAMECONTROLLER | SDL_INIT_EVENTS)) {
        printf("Error initializing SDL: %s", SDL_GetError());
        return 1;
    }

    emscripten_set_main_loop(mainLoopFunction, -1, 1);

    return 0;
}

```

**Comment by kripken** [comment]
Ah, in that case then it's likely coming from the SDL code. I see in `eglSwapInterval` that it may use setTimeout instead of requestAnimationFrame depending on how its called. Indeed it's called with an interval of 0, which leads to this:

```javascript
function eglSwapInterval(display, interval) {
   ...
   if (interval == 0) _emscripten_set_main_loop_timing(0/*EM_TIMING_SETTIMEOUT*/, 0);
```

so it uses `setTimeout`.

The EGL docs for `eglSwapInterval` say

> If interval is set to a value of 0, buffer swaps are not synchronized to a video frame, and the swap happens as soon as the render is complete.

I'm not sure why that is best implemented with `setTimeout`. Also not sure why SDL2 calls it with an interval of 0.

Perhaps @juj and @Daft-Freak have ideas?

**Comment by juj** [comment]
It should be noted that swap interval of 0 (vsync limit disabled, "render and present as fast as possible") is not supported by web browsers, meaning that if one does any kind of event loop that ticks faster than what the presentation rate of the browser/display is (typically 60Hz, but gaming monitors with 120Hz/144Hz can have rAFs ticking at that rate in the browser), then the "excess" rendered WebGL frames will replace their previous ones. In other words, even if one sets a loop to render 120 frames per second, then only 60 of those will actually show up on the display, as there will be two frames rendered per every browser composition events, and every second frame is just obsoleted by the next one that is produced.

That being said, rendering as fast as possible in the browser is still useful for local development/performance profiling and debugging purposes, even though most of those frames will never show up on screen.

> I'm not sure why that is best implemented with `setTimeout`.

There are three ways to implement "render as fast as possible without vsync" in a browser, all of which are something that browser vendors (except for `setImmediate` from Microsoft) have voiced that web pages should not be doing live. From best to worst:

1) Use the [setImmediate Web API](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate), which was exactly intended for this use. None of Mozilla, Google and Apple wanted to support that however, so it got deprecated (and now with Microsoft transition to Chromium, it is effectively dead even in the last supported browser)

2) Do a loop of postMessage()s to self. This will cause an unboundedly fast event processing loop in JS that can render WebGL content at up to ~10000 fps on desktop (for naive/simple rendering workloads)

3) Do a loop of setTimeout()s to self. This will be throttled by the browser to about 250fps, or 4ms intervals to save battery.

4) Do a loop of setInterval()s to self. This will be throttled by the browser to <250fps as well (last time I measured, it was just a hair bit slower than using setTimeout()).

If you do a emscripten_set_main_loop_timing() with EM_TIMING_SETIMMEDIATE, it will use a combination of 1) and 2) where available for the fastest vsync-free rendering. **It is not recommended to ship a production web page with that build mode, as most of the produced frames will not make it to the screen.** In general, for shipping a web page, always prefer to use requestAnimationFrame (EM_TIMING_RAF) instead.

**Comment by Daft-Freak** [comment]
SDL2 defaults to vsync off when using a renderer. You need the `SDL_RENDERER_PRESENTVSYNC` flag to enable it.

**Comment by adam4235** [comment]
Thanks, adding the SDL_RENDERER_PRESENTVSYNC made the warning go away.

**Comment by kripken** [comment]
Given the details from @juj, should we always set `SDL_RENDERER_PRESENTVSYNC` perhaps? It seems like that's what users would want as the default.

**Comment by Daft-Freak** [comment]
Hmm, that flag is part of the renderer code and passed by the user to `SDL_CreateRenderer`. I don't think it's something the backend can change.

**Comment by kripken** [comment]
I see, thanks @Daft-Freak 

We should probably document this then. I'll reopen the issue and rename for that.

**Comment by Daft-Freak** [comment]
Another point here is that if you're doing the typical:
```
SDL_CreateRenderer(...)
...
emscripten_set_main_loop(...)
```

Then you get this warning, but the lack of vsync has no effect since SDL tried to turn it off too early. (+ another about it having no effect (#7100))
