### ISSUE TITLE
Advisory lock on an open file using flock not working

### ISSUE THREAD

**Issue by kjpou1** [emscripten-core/emscripten#11797]
Using flock does not seem to work.

The API is implemented and it's used by some of emscripten internal tooling (https://github.com/emscripten-core/emscripten/blob/master/tools/filelock.py#L363).

In the tests there are tests for fnctl that reference struct flock:  https://github.com/emscripten-core/emscripten/blob/master/tests/fcntl/test_fcntl.c#L57

But there do not seem to be any tests that use flock.

**Comment by sbc100** [comment]
The python locking implemented in tools/filelock.py is part of the compiler driver and nothing to do with the runtime.

It looks like `flock` is linux/bsd and not part of POSIX, which is probably why we have not gotten around to implementing it yet.  I don't think anyone would object if somebody wanted to add it.   It looks like we have a stub right here that can be filled in:
https://github.com/emscripten-core/emscripten/blob/c5cc009856d7a9ff47b31b3acd078f5e1dbdc133/src/library.js#L112

**Comment by kjpou1** [comment]
@sbc100 thank you for the information.  

Are you saying that POSIX record locks (fcntl) is implemented and should work?

**Comment by sbc100** [comment]
I looks from the test you linked to at hat least the F_GETLK and F_SETLK fcntls return errno 0.  

It looks like they mostly stubbed out: https://github.com/emscripten-core/emscripten/blob/126fa660dd1a9383180e8734076671a6041d44a6/src/library_syscall.js#L1160

Remember that emscripten is not multi-process and the filesystem is basically local the running module, so the actually locking functionality I don't think make much sense.

What you are hoping to lock against in your application exactly?

**Comment by kjpou1** [comment]
@sbc100 thank you for the information.  We will need to discuss the locking and whether or not it makes sense as you have mentioned.
