### ISSUE TITLE
Error being overridden incorrectly on FS.Rename

### ISSUE THREAD

**Issue by kjpou1** [emscripten-core/emscripten#11804]
While renaming a file and if one of the parent paths do not exist the error code is being overwritten to EBUSY instead of reporting the actual error:

```
Error no 44 Error: ENOENT Message: No such file or directory 

```

https://github.com/emscripten-core/emscripten/blob/126fa660dd1a9383180e8734076671a6041d44a6/src/library_fs.js#L729

Suggested code that returns back the original error code is the following:

```
        // parents must exist
        var lookup, old_dir, new_dir;
        try {
          lookup = FS.lookupPath(old_path, { parent: true });
          old_dir = lookup.node;
          lookup = FS.lookupPath(new_path, { parent: true });
          new_dir = lookup.node;
        } catch (e) {
          // do not override failing error
          if (e instanceof FS.ErrnoError)
            throw e;
          throw new FS.ErrnoError(10);
        }
```

**Comment by kripken** [comment]
I think that makes sense @kjpou1 , would you like to open a PR?
