### ISSUE TITLE
GLES headers are missing some compressed texture extensions

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#11801]
The following GLES extensions are missing from the headers:

* [EXT_texture_compression_rgtc](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_rgtc.txt); WebGL equivalent: [EXT_texture_compression_rgtc](https://www.khronos.org/registry/webgl/extensions/EXT_texture_compression_rgtc/)
* [EXT_texture_compression_bptc](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_bptc.txt); WebGL equivalent: [EXT_texture_compression_bptc](https://www.khronos.org/registry/webgl/extensions/EXT_texture_compression_bptc/)
* [EXT_texture_compression_s3tc_srgb](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_s3tc_srgb.txt); WebGL equivalent: [WEBGL_compressed_texture_s3tc_srgb](https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_s3tc_srgb/)
* [EXT_texture_compression_astc_decode_mode](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_astc_decode_mode.txt); no WebGL equivalent.

There are probably more missing extensions. The first 3 are the ones I actually ran into a problem with in my codebase, and the ones that are most useful to expose, since they are usable in WebGL. All of these are in the official Khronos `GLES2/gl2ext.h` header.

**Comment by kripken** [comment]
cc @juj

**Comment by Akaricchi** [comment]
The headers are apparently unmodified, just very outdated. So I just updated them and made a PR here #11808
