### ISSUE TITLE
How do to get stackTrace on exception

### ISSUE THREAD

**Issue by MangeshKute** [emscripten-core/emscripten#11815]
1. Whenever exception occurs, how could we get stack trace in catch block ?
2. If exception is uncaught and passed to JS caller, how does we get call stack ?
3. How does emscripten print stacktrace in console.log ?

**Comment by kripken** [comment]
You can get a JS stack trace from js by doing `new Error().stack`. For example
```cpp
EM_ASM({
  console.log("Current stack trace:", new Error().stack);
});
```
