### ISSUE TITLE
How to set EXPORTED_FUNCTIONS with CMake

### ISSUE THREAD

**Issue by higaski** [emscripten-core/emscripten#11817]
What's the recommended way to set -s EXPORTED_FUNCTIONS'["_int_sqrt"]' with CMake?

I'm currently using a string to store all the flags I need to pass to Emscripten since using target_compile_options directly isn't really much of an option. It treats successive -s flags as duplicates and removes them...

So far this has been a reasonable workaround for me. But now I'd like to make use of the EXPORTED_FUNCTIONS option and I can't seem to find any CMake syntax which would allow me to pass single and doubles quotes within a string. I've tried escaping the double quotes like this:
`-s EXPORTED_FUNCTIONS='[\"_int_sqrt\"]'`

But the slash ends up in the actual command...
`/usr/lib/emscripten/em++  -DNDEBUG -O2 -s EXPORTED_FUNCTIONS=[\"_int_sqrt\"]`

**Comment by sbc100** [comment]
Yuck... this is not great.  I've been meaning to try to simplify the syntax for `EXPORTED_FUNCTIONS` for a while now so you can just do `EXPORTED_FUNCTIONS=foo,bar,baz`.. but I'm not managed to land it yet.

I imagine there is some way to get cmake to do the right quoting.. but the simplest way might be to use a file: `-s EXPORTED_FUNCTIONS=@exports.txt`.

**Comment by higaski** [comment]
There generally seems to be a lot of confusion around how to get the quoting right. E.g. I've found the following closely related questions:
https://stackoverflow.com/questions/62575726/how-to-export-c-function-in-emscripten-when-using-cmake
https://github.com/emscripten-core/emscripten/issues/6021
https://github.com/emscripten-core/emscripten/issues/9821

The accepted answer on stackoverflow even suggested using add_definitions which makes my skin crawl... and probably also adds a -D prefix, how could this even work?

Personally, I just got it working by simply dropping all double quotes. I've appended
`-s EXPORTED_FUNCTIONS=['_main','_malloc','_int_sqrt'] -s EXTRA_EXPORTED_RUNTIME_METHODS=['ccall','cwrap']`
to my single CMake string and it started to work. For some reason CMake also doesn't play along when there are any whitespaces in the list. It might be a good idea to remove those from the documentation as well so that people don't run into this issue when copy/pasting the flags?

**Comment by curiousdannii** [comment]
This works, no escaping needed.
```
target_link_options(target PRIVATE
        -sEXTRA_EXPORTED_RUNTIME_METHODS=['_main','_foo','_bar'])
```

**Comment by higaski** [comment]
Well, if skipping the whitespace after "-s" works this is of course the preferred solution!
I guess CMake then treats each -s*something as new flag instead of removing duplicate -s prefixes.
Then I'd suggest putting that in the documentation somewhere? Never would I have guessed that this works... ;)

**Comment by sbc100** [comment]
Yes the ability to use `-s` options without that the following space was just added for the benefit of cmake

**Comment by kripken** [comment]
We should probably add more docs for that. Maybe on the [FAQ](https://emscripten.org/docs/getting_started/FAQ.html) or on [Building-Projects](https://emscripten.org/docs/compiling/Building-Projects.html)?

**Comment by Liteb0t** [comment]
> This works, no escaping needed.
> 
> ```
> target_link_options(target PRIVATE
>         -sEXPORTED_FUNCTIONS=['_main','_foo','_bar'])
> ```

Does not work with clang
clang: **error: unknown argument: '-sEXPORTED_FUNCTIONS=['_foo','_bar']'**

**Comment by sbc100** [comment]
The `-sEXPORTED_FUNCTIONS` flag is not designed for clang but for emcc.   If you that flag is being passed to clang it won't work.

Also, remember to use the more modern simpler form: `-sEXPORTED_FUNCTIONS=_foo,_bar`

**Comment by Liteb0t** [comment]
Nevermind I just called `cmake --build` for the wrong directory, whoops!
