### ISSUE TITLE
WebGL version detection is not robust

### ISSUE THREAD

**Issue by yjbanov** [emscripten-core/emscripten#11819]
Emscripten uses the following method to check whether WebGL2 is available:

https://github.com/emscripten-core/emscripten/blob/eb0ede77ae02e961cf8a266d55bdb513b6f03c23/src/library_browser.js#L321

However, sometimes `WebGL2RenderingContext` is available but WebGL2 is disabled due to hardware-specific reasons. For example, Moto E5, which runs the latest Chrome (84 as of this writing) and has the `WebGL2RenderingContext` type, disables WebGL2 dynamically. This leads Emscripten to believe that WebGL2 is available, ultimately leading it to this line:

https://github.com/emscripten-core/emscripten/blob/eb0ede77ae02e961cf8a266d55bdb513b6f03c23/src/library_browser.js#L347

A more robust approach would be to attempt to get a WebGL2 context, and if that fails (by returning `null`), attempt to get a WebGL1 context, and only if that fails too return null.

I discovered this while debugging a Flutter app that runs on top of CanvasKit. It's not a blocking issue as we can implement our own WebGL version detection and pass `majorVersion` to Emscripten.

**Comment by kripken** [comment]
Interesting...

Are we sure this (WebGL2RenderingContext is defined, but not usable) is not a browser bug? cc @kenrussell

**Comment by kenrussell** [comment]
It's not a browser bug. Creating a WebGL context is an expensive operation, and browsers can't do it in order to determine visibility of the WebGL2RenderingContext interface itself - it would impact startup time of all web pages.

**Comment by kripken** [comment]
Thanks @kenrussell , makes sense. I'll open a PR.

**Comment by yjbanov** [comment]
FYI: this is my implementation in Flutter: https://github.com/flutter/engine/commit/4eaf651347b008c31c4c6916c788ad5897bf9d5a

**Comment by kripken** [comment]
@yjbanov thanks, that makes sense. I opened #11839 meanwhile to handle this here. Should do the same thing, but may be slightly more efficient by not creating contexts just to check for support.

**Comment by juj** [comment]
See the comment in https://github.com/emscripten-core/emscripten/pull/11839#issuecomment-670838259.

The problem looks like is in library_browser.js rather than in library_webgl.js.

I do not mind the code size of library_browser.js increasing, so perhaps the PR #11839 could refactor to fix the issue in library_browser.js layer rather than in library_webgl.js?

**Comment by kripken** [comment]
I think we can close this. Based on discussion here an in the PR #11839, we don't want to automatically try 2 and then fall back to 1, as that may surprise a user that requested 2. Instead the user can explicity try to create 2, and if that fails create 1 (see code snipped from @juj in the PR, which also has a test).
