### ISSUE TITLE
Possible missed optimization for modules that don't use table after metadce?

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11828]
While landing #11826 I noticed we have potential missed optimization 

1. Function `foo` in wasm-ld output is alive on by its presence in the table.
2. Module contains at least one call-indirect (which means table elems must be kept alive)
3. During metadce all the call-indirect instructions are removed from the table.
4. `foo` and all other table elements could in theory now be removed by RemoveUnusedModuleElements 

I'm not sure why (4) doesn't seem to be happening.  Perhaps we just don't run that pass again after metadce?

**Comment by kripken** [comment]
In general we import that Table from the outside, so we can't remove its contents even if no call_indirects remain.

We can consider changing that, but if we don't have the Table accessible on the outside, we can't call it directly, and are forced to keep around dynCalls for JS.

**Comment by sbc100** [comment]
Right, I guess that is why this issue showed up in WASM_STANDALONE mode only where the table is internal and there are no dynCalls (in the default mode anyway).

Not a big deal I think.  I this case the function in question is empty anyway.
