### ISSUE TITLE
log4javascript js is not defined in webassembly sub-thread

### ISSUE THREAD

**Issue by Youxu-Chen** [emscripten-core/emscripten#11824]
Hi, all:

I invoke js code in c++ file to save my log with different level  by EM_ASM macro with log4javascript js library. It works well in main thread, however, it does not work in sub-thread.  The error is that `log4javascript is not defined`.

Here the code:

`thread.cc`:
```
#include <iostream>
#include <thread>
#include <stdlib.h>

#include <emscripten.h>
#include <emscripten/bind.h>

using namespace std;


void t1()
{
        cout << "here is sub thread" << endl;
        for (int i = 0; i < 10; i++) {
                EM_ASM({
                        var logger = log4javascript.getLogger("test");
                        logger.info("I am thread");
                        console.log("123");
                });
                emscripten_sleep(1000);
        }
}

void go()
{

        cout << "here is main thread" << endl;

        EM_ASM(
                logger = log4javascript.getLogger("./test");
        logger.debug("Welcome to FusionAccess HTML5 Client :)");
    );


        thread th1(t1);

        th1.detach();
}

EMSCRIPTEN_BINDINGS(my_module)
{
        emscripten::function("_Go", &go);
}
```

and I compile this file into `thread.js` by `em++ thread.cc -o thread.js -s USE_PTHREADS=1 -pthread -s ASYNCIFY=1 --bind`.

Then include `thread.js` in `thread.html`:
```
<html>

<head>
<script type="text/javascript" src="log4javascript.js"></script>
</head>

<body>
<script type="text/javascript" src="thread.js"></script>
<script type="text/javascript">
Module['onRuntimeInitialized'] = onRuntimeInitialized;
function onRuntimeInitialized() {

        var logger;
        var appender;

        function initLog() {
                logger = log4javascript.getLogger("./test");
                appender = new log4javascript.PopUpAppender();
                logger.addAppender(appender);
                logger.debug("start test log console!");
        }

    initLog();

        Module._Go();

}
</script>

</body>

</html>

```

Or is there other resolutions to save log in webassembly?

Thanks

**Comment by Youxu-Chen** [comment]
@kripken @juj @sbc100 @waywardmonkeys

**Comment by sbc100** [comment]
JS code that you include your page will not be available in your worker.

You would need to somehow load log4javascript in the worker.

I'm not familiar with log4javascript or what you mean by "save a log", but emscripten has it own `emscripten_log` function could work?

**Comment by Youxu-Chen** [comment]
> JS code that you include your page will not be available in your worker.
> 
> You would need to somehow load log4javascript in the worker.
> 
> I'm not familiar with log4javascript or what you mean by "save a log", but emscripten has it own `emscripten_log` function could work?

Thanks @sbc100 , I have tried the `MAIN_THREAD_ASYNC_EM_ASM` macro to let the sub-thread prints the log in main browser thread. The log finally shows but the content is out of order due to concurrency. 

log4javascript can save the log completely, rather than the console in browser. If I open the console after my program, the log before will lose.

Thanks again.
