### ISSUE TITLE
Pthreads keeps increasing with WASM

### ISSUE THREAD

**Issue by lnxjnky** [emscripten-core/emscripten#11825]
Hi,

I am new to webassembly. I am porting some cross platform code to WebAssembly with WASM=0, USE_PTHREADS=1 and PTHREAD_POOL_SIZE=8.
While running the code in chrome as browser extension, I observe that in chrome task manager the number of dedicated worker keeps increasing and my extension crashes after consuming good amount of memory.  It seems all are detach pthreads. Is there a way to investigate what is going wrong.

I am using sdk-fastcomp-tag-1.38.30-64bit version of emsdk.

![image](https://user-images.githubusercontent.com/8235459/89549009-651cd780-d825-11ea-8c2d-250cb3e91040.png)

**Comment by kripken** [comment]
One way to investigate this could be to look for `new Worker` in the JS, which is where new workers are created. Then you can add some logging at those times, use the stack to see why they happen, etc. (based on those flags, emscripten should create 8 workers, and then stop, unless you create more using `pthread_create` etc.)

**Comment by lnxjnky** [comment]
Thanks for the guidance. In my native code there are threads getting created using `pthread_create`, on task completion they get detached calling `pthread_detach `and exit. I see that `PThread.threadExit(result);` is invoked on the worker JS side but the worker is not deleted from the list and shows up in chrome task manager. Am I missing something here due to which the cleanup doesn't happen?

**Comment by kripken** [comment]
Does calling `pthread_exit` instead of `pthread_detach` fix the issue?

If so then it's either a bug in `pthread_detach`, or the implementation is correct but `pthread_detach` does not guarantee thread cleanup (I'm not sure either way from reading the docs, but others here know more about pthreads and can answer that).

**Comment by lnxjnky** [comment]
I did try to call `pthread_exit` at the time of task completion it didn't help. I have not tried calling `pthread_exit` instead of `pthread_detach`, not sure if that would be really help. Also going through some [docs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_exit.html), it seems an implicit call to `pthread_exit()` is made when a thread completes (when a call to return routine happens). 

Also looking at the worker.js code comment below, the exit operation is started even if there is no explicit call to `pthread_exit() ` which is happening in my case.

```
// The thread might have finished without calling pthread_exit(). If so, then perform the exit operation ourselves.
// (This is a no-op if explicit pthread_exit() had been called prior.)
      if (!Module['noExitRuntime']) PThread.threadExit(result);
```

**Comment by kripken** [comment]
Interesting. Not sure what's going on then.

Note that Workers are not deleted immediately - only the next time the browser does a GC. So seeing a long list of workers may not be a bug. But seeing new workers created unnecessarily would indicate that emscripten is not reusing them, which would be a bug.

**Comment by lnxjnky** [comment]
Could you please guide me how should I proceed from here? Can I do something from my side to help? Or do I have to wait for the bug to be created and fixed?

**Comment by kripken** [comment]
I think the main options are for you to continue to debug it on your side (did my last comments not help?), or otherwise to create a small testcase you can share with us (without a testcase, there isn't enough information to investigate this).

**Comment by lnxjnky** [comment]
On further debugging the generated .js code,  I found that the the created thread when detached are not added back to `unusedWorkerPool`. I modified the generated .js code and did cleanup on thread exit (`exit `command) and it solved the problem for me.

JS code before: No handling for exit command
```
worker.onmessage = function (e) 
.
.
else if (d.cmd === "exit") {} else if (d.cmd === "exitProcess") {
```

Modified code: Cleanup on exit command

```
worker.onmessage = function (e) 
.
.
else if (d.cmd === "exit") { 
  PThread.freeThreadData(worker.pthread);
  worker.pthread = undefined;
  PThread.unusedWorkerPool.push(worker);
  PThread.runningWorkers.splice(PThread.runningWorkers.indexOf(worker.pthread), 1)
} else if (d.cmd === "exitProcess") {
```

I am not sure if this is the right change, but it seems workers not getting added to `unusedWorkerPool `when threads are detached is the problem here. Thoughts?
