### ISSUE TITLE
free memory after new 

### ISSUE THREAD

**Issue by jvail** [emscripten-core/emscripten#11833]
Sorry for this very basic question but I could not find an answer in the docs (hope I am not blind or maybe it is too obvious for everyone else):
Is calling `_free(Ptr)` sufficient if the data has been allocated with `new` in c++ like in the example below or do I need a `delete[] data` in c++?

```cpp
uint_8* fn()
{
    uint_8* data = new uint_8[100];
   // ... fill array
   return data;`
}
```

```js
const Ptr = fn();
const data = Module['HEAPU8'].buffer.slice(Ptr.ptr, Ptr.ptr + 100);
Module['_free'](Ptr);
```

Thank you
Jan

**Comment by sbc100** [comment]
If you want to use `free` to free the memory you should probably use `malloc` to allocate it.  C++ new and delete (especially array new) don't necessarily correspond exactly to `malloc` and `free`.

**Comment by sbc100** [comment]
See http://www.cplusplus.com/reference/new/operator%20new[]/

```
operator new[] can be called explicitly as a regular function, but in C++, new[] is an operator with a very specific behavior: An expression with the new operator on an array type, first calls function operator new (i.e., this function) with the size of its array type specifier as first argument (plus any array overhead storage to keep track of the size, if any), and if this is successful, it then automatically initializes or constructs every object in the array (if needed). Finally, the expression evaluates as a pointer to the appropriate type pointing to the first element of the array.
```

**Comment by jvail** [comment]
Ok, thank you for clarifying.
