### ISSUE TITLE
EM_JS: How to convert int argc, char **argv to a JS array of strings?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11847]
I'm trying to call JS function from C/C++ with an array of strings as an argument.

Here's my example code:

**main.c:**

    #include <stdio.h>
    #include <emscripten.h>
    
    EM_JS(void, call_myFunc, (int argc, char **argv), {
         
        var arr = [];
        for (let i = 0; i < argc; i++) {
          arr.push(UTF8ToString(argv[i]));
        }
        myFunc(arr);
    });
    
    int main()
    {
        int argc = 4;
        char *argv[5] = { "ab", "cd", "ef", "gh" };
        call_myFunc(argc, argv);
    }

**index.html:**

    <!DOCTYPE html>
    <html>
    
    <head>
    </head>
    
    <body>
      <script>
      function myFunc(args) {
        console.log(args);
      }
      </script>
      <script async src="main.js"></script>
    </body>
    
    </html>
**build:**

    emcc main.c -o main.html

**result I get:**

    ["", "", "", ""]

**result I want:**

    ["ab", "cd", "ef", "gh"]

How can I properly convert `char **argv` to a JS array of strings?

**Comment by Akaricchi** [comment]
Since `argv` is a pointer, it gets passed as a plain number to javascript. Try something like this (untested):

```c
EM_JS(void, call_myFunc, (int argc, char **argv), {
    var arr = [];
    for (let i = 0; i < argc; i++) {
      arr.push(UTF8ToString(HEAP32[(argv << 2) + i]));
    }
    myFunc(arr);
});
```

**Comment by cuinjune** [comment]
@Akaricchi Thank you but it still doesn't work with your code.
It prints: 
```
Array(4)
0: ""
1: ""
2: ""
3: ""
```

**Comment by Akaricchi** [comment]
Err, I got the wrong shift operator. `>>` instead of `<<`.

**Comment by cuinjune** [comment]
Thank you so much! That worked!
