### ISSUE TITLE
EXPORTED_FUNCTIONS in WASM_STANDALONE mode

### ISSUE THREAD

**Issue by mejedi** [emscripten-core/emscripten#11854]
I try to build llvm for WASI using Emscripten. (I want to share llvm with custom changes with interested parties, but asking people to compile it seems to be a burden and I'd rather not build packages for many architectures/OS-es.)

I'm using `WASM_STANDALONE=1`. It builds without issues but there are some imported symbols that WASI platform doesn't provide. My understanding is that WASI is not fully supported yet. This is fine; I am working at gradually reducing the number of unresolved symbols.

I'm stuck with `emscripten_stack_get_end`. As far as I can tell there is nothing in the program that uses it, but it is imported. Excerpts from the resulting wasm:

```
(import "env" "emscripten_stack_get_end" (func (;11;) (type 14)))
(func (;14500;) (type 14) (result i32)
    global.get 1
    i32.eqz
    if  ;; label = @1
      call 11
      global.set 1
    end
    global.get 0
    global.get 1
    i32.sub)
(export "emscripten_stack_get_free" (func 14500))
```

I'm not well versed in WASM, please confirm that if there's neither `call 11` nor `call 14500` nor `;11;` nor `;14500;` anywhere else, it is safe to assume that all users were identified?

If `emscripten_stack_get_end ` is only necessary to implement an exported function, I'd like to get rid of it. Apparently, there are many other superfluous exports (excerpt):
```
 (export "_ZdlPv" (func 70))
  (export "LLVMInitializeX86TargetInfo" (func 7660))
  (export "LLVMInitializeX86Target" (func 8457))
  (export "LLVMInitializeX86TargetMC" (func 7762))
  (export "LLVMInitializeX86AsmPrinter" (func 8160))
  (export "LLVMInitializeX86AsmParser" (func 6129))
  (export "_Znwm" (func 29))
  (export "malloc" (func 65))
  (export "_ZdaPv" (func 70))
  (export "__cxa_pure_virtual" (func 3965))
  (export "__cxa_guard_acquire" (func 117))
  (export "__cxa_guard_release" (func 116))
  (export "_Znam" (func 14578))
  (export "__errno_location" (func 14936))
  (export "_start" (func 14943))
  (export "emscripten_stack_get_current" (func 14501))
```

I've tried `EXPORTED_FUNCTIONS `, but it didn't quite work:
```
em++  ... -sSTANDALONE_WASM -s EXPORTED_FUNCTIONS='["init"]' -s EXPORTED_RUNTIME_METHODS='[""]'
```
It says that `main` could get eliminated, but builds just fine.  The resulting binary goes down to 16M from 19M, which is alarming.

Still, exports contain a lot of cruft, including `emscripten_stack_get_free`.

Any pointers are greatly appreciated!

**Comment by sbc100** [comment]
Firstly, if you want pure WASI version of clang you might be better off with wasi-sdk: https://github.com/WebAssembly/wasi-sdk.     

Otherwise if you use `EXPORTED_FUNCTIONS` you need to prefix the symbols with `_` .   So `main` would be listed as `_main` and `init` would be listed `_init`.

As for `emscripten_stack_get_free` that is probably a bug.    Can you try added `-Wl,--trace-symbol=emscripten_stack_get_free` to see where it is being referenced from?   It doesn't look like its being included for simple programs.   What other `-s` settings are you passing?   Are you settings `MAIN_MODULE` or `EXPORT_ALL` by any chance?

**Comment by mejedi** [comment]
@sbc100 Thanks for your help!

It turns out I had `-Wl,--export-dynamic` on the command line. Removing the flag fixed it, `emscripten_stack_get_end` gone and only `memory`, `malloc`, `__errno_location`, and `_start` listed as exports.

PS I've tried was-sdk first, but there were major compilation issues due to missing [atomics](https://github.com/WebAssembly/wasi-sdk/issues/22).
