### ISSUE TITLE
Missing "ntohs" in recv() and send()

### ISSUE THREAD

**Issue by truboxl** [emscripten-core/emscripten#11851]
Let `link_test.c` be
```
#include <sys/types.h>
#include <sys/socket.h>

int main (void){
    recv(0, 0, 0, 0);
    send(0, 0, 0, 0);
    return 0;
}
```
and compile using `emcc link_test.c`
```
error: undefined symbol: ntohs (referenced by _inet_pton6_raw__deps: ['htons','ntohs','$jstoi_q'], referenced by $DNS__deps: ['_inet_pton4_raw','_inet_pton6_raw'], referenced by __sys_socketcall__deps: ['$SOCKFS','$DNS','_read_sockaddr','_write_sockaddr','$SYSCALLS'], referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _ntohs may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/home/jylo/emsdk/node/12.18.1_64bit/bin/node /home/jylo/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpt2t7oymv.txt' failed (1)
```

So this issue comes in 2 parts:

1. Adding "ntohs" to https://github.com/emscripten-core/emscripten/blob/8fb545497fba690753adf70bca6f7e7a0c78b075/src/deps_info.json#L82-L83

    seems to fix it.

2. But I am not sure how to change https://github.com/emscripten-core/emscripten/blob/8fb545497fba690753adf70bca6f7e7a0c78b075/tests/test_other.py#L9103-L9115

    to make it fail with the undefined symbol error.

Note: This test is derived from `curl` build system. So once this is fix it can make `curl` exec.
But I am having other errors like `getaddrinfo()` and thread problem that probably should be in a new issue itself.
And yes `--with-ssl=` does work if you copy `openssl.wasm` (and maybe `openssl.worker.js`) over to your openssl prefix after following the proper build config and `make install_sw`.

**Comment by kripken** [comment]
@truboxl Probably to make that test fail we'd need a tiny testcase that only calls that one function, and nothing else. So maybe just a call to `recv` in a new test right after that one? A PR with this fix would be great!
