### ISSUE TITLE
Does EM_JS create a global JS function?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11850]
If I use `EM_JS` like the following:

```
EM_JS(void, foo, (), {
      console.log("foo called");
});
```

I just found out I can call this function directly from Javascript with `foo()`.

Is this how it supposed to work? I thought `EM_JS` is only for being called in C/C++ but I was wrong.
Isn't it bad to have global function names that can potentially clash with other JS function names?

Or is there a way to make an `EM_JS` function not global and make it exist within the `Module` object?

**Comment by sbc100** [comment]
Don't all your native exports also exist at the top level?  e.g. _main?  Or are you some method to avoid that?  (Does MODULARIZE avoid that?)

**Comment by kripken** [comment]
MODULARIZE is the general solution for this, yes - in general the emscripten main scope will contain the JS library functions, EM_JS functions, and so forth. Modularize mode puts it all into a module so it's not global.

**Comment by cuinjune** [comment]
Thank you so much. That works!
