### ISSUE TITLE
Is it possible to return char** from EM_JS function?

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11899]
I'm trying to figure out how to return an array of strings from `EM_JS` function.

Here's my code:

**main.c:**
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <emscripten.h>

EM_JS(char **, get_strings, (), {
  var jsStrings = ["hello", "world"];
  var lengthBytes = lengthBytesUTF8(jsStrings[0] + jsStrings[1]) + 2;
  var stringOnWasmHeap = _malloc(lengthBytes);
  stringToUTF8(jsStrings, stringOnWasmHeap, lengthBytes);
  return stringOnWasmHeap;
});

int main() {
    char **argv = get_strings();
    printf("first: %s\n", argv[0]);
    printf("second: %s\n", argv[1]);
    free((void *)argv);
}
```
**build:**
`emcc main.c -o main.html`

**result:**

> exception thrown: TypeError: str.charCodeAt is not a function,TypeError: str.charCodeAt is not a function
>     at stringToUTF8Array 

How can I make the `EM_JS` function return an array of strings?
Thanks in advance!

**Comment by sbc100** [comment]
You need to call stringToUTF8 once for each string in the array.    

If you really want to return an array of C string you need to allocate each string and also the array of points and return a `char**`

**Comment by RixInGithub** [comment]
Also I'm very new in C, so you may need to correct me.
