### ISSUE TITLE
basename is empty on paths with trailing `/` 

### ISSUE THREAD

**Issue by mdh1418** [emscripten-core/emscripten#11897]
For paths with a trailing `/` referring to directories, basename https://github.com/emscripten-core/emscripten/blob/7c3ced64d51be643f7a12bb34e8b875155d49dc7/src/library_path.js#L67 will evaluate to an empty string. This causes errors with `rmdir` and `rename`.

### Reproduction
**hello_world.c**
```
/*
 * Copyright 2011 The Emscripten Authors.  All rights reserved.
 * Emscripten is available under two separate licenses, the MIT license and the
 * University of Illinois/NCSA Open Source License.  Both these licenses can be
 * found in the LICENSE file.
 */

#include <emscripten.h>
#include <stdio.h>


extern int rmdir(char* path);
extern int mkdir(char* path, int mode);

EM_JS(void, call_alert, (int errorcode), {
  console.log(errorcode);
});

int main() {
  char* path = "/mitchtest/";  
  mkdir(path, 777);
  call_alert(rmdir(path));
  return 0;
}
```

Copy two files
https://github.com/emscripten-core/emscripten/blob/7c3ced64d51be643f7a12bb34e8b875155d49dc7/src/library_path.js https://github.com/emscripten-core/emscripten/blob/2bca083cbbd5a4133db61fbd74d04f7feecfa907/src/library_fs.js

`./emcc --js-library <path-to-library_path.js> --js-library <path-to-library_fs.js> hello_world.c`
`node a.out.js`

Expected `0`
Actual `-1`

**Comment by sbc100** [comment]
Yup looks like we just need to call PATH.normalize first

**Comment by mdh1418** [comment]
It looks like PATH.normalize retains the trailing slash here https://github.com/emscripten-core/emscripten/blob/7c3ced64d51be643f7a12bb34e8b875155d49dc7/src/library_path.js#L49.
