### ISSUE TITLE
How to suppress the generation of useless exports  in STANDALONE_WASM=1 mode

### ISSUE THREAD

**Issue by eustas** [emscripten-core/emscripten#11898]
Additionally to the functions requested with `EXPORTED_FUNCTIONS` the following exports are  emitted:

 * `memory` - useful
 * `_initialize` - useful
 * `__errno_location` - useless
 * `stackSave` - useless
 * `stackRestore` - useless
 * `stackAlloc` - useless
 * `__data_end` - useless
 * `__growWasmMemory` - useless

Given that app is really standalone (everything is done via exported API, no JS crutches required), how can I suppress emission of useless exports (and supporting functions)?

**Comment by sbc100** [comment]
As it happens I just wrote a patch that removes a lot of those. #11900

**Comment by eustas** [comment]
Nice, thanks! Perhaps it should be done conditionally i.e. for `STANDALONE_WASM=2`

**Comment by eustas** [comment]
Or via `UNEXPORTED_FUNCTIONS` for better configurability / easier future versions support.

**Comment by sbc100** [comment]
It looks like even after I land my change you will still want to pass `SUPPORT_ERRNO=0` and `SUPPORT_LONGJMP=0` gets rid of `__errno_location` and of `stack*`.

I'd really rather not add `UNEXPORTED_FUNCTIONS` or `STANDALONE_WASM=2`, at least not without some serious consideration.

In theory we should be able to remove all unused exports via metadce, but this requires us to output a .js file (I think perhaps we do this under the hood anyway).   In general metadce is the answer to cleaning up these extra exports I think... let me investigate some more.

**Comment by kripken** [comment]
Yes, in general metadce should avoid unnecessary things like that automatically. Maybe we could improve metadce for standalone mode. But probably we could only do that for standalone mode *without* JS being emitted, as when we emit standalone with JS we do need that JS to run.

Considering the cases separately adds a little complexity though, but not much: in metadce, when no JS is being emitted, just remove all JS references.

**Comment by eustas** [comment]
Oh, `wasm-metadce` does all I want! It is just... undiscoverable.
(one glitch with it is that it requires names for root nodes... but does not care if they are all the same)

**Comment by sgbeal** [comment]
This appears to still be an issue. i'm unable, via an emcc call, to get the resulting wasm file and its JS glue to stop emitting and exporting:

```
stackAlloc
stackRestore
stackSave
emscripten_stack_get_base
​emscripten_stack_get_end​
emscripten_stack_get_free​
emscripten_stack_init
```

the stackXXX functions are getting exported in Module.asm and in Module, but also get an unexportedRuntimeFunction() line in the generated postamble which is a no-op because of the prior export of Module.stackXXX: 

```
var stackSave = Module["stackSave"] = createExportWrapper("stackSave");
var stackRestore = Module["stackRestore"] = createExportWrapper("stackRestore");
var stackAlloc = Module["stackAlloc"] = createExportWrapper("stackAlloc");
...
unexportedRuntimeFunction('stackSave', false);
unexportedRuntimeFunction('stackRestore', false);
unexportedRuntimeFunction('stackAlloc', false);
```

Module.stackAlloc() and friends are still exposed and still work. My `EXPORTED_RUNTIME_METHODS` list is explicitly empty: `-sEXPORTED_RUNTIME_METHODS=`. i've tried `-sSTANDALONE_WASM` but that had no outward effect.

i'm able to get rid of `__errno_location` using `SUPPORT_ERRNO=0` and `SUPPORT_LONGJMP=0`, as noted in an earlier comment. Seemingly nothing gets rid of the stack-related exports, though.

**Comment by sgbeal** [comment]
Thank you! Indeed, `-Oz` does it :). i never build with -Oz because it takes sooooo long on my machine, so never would have figured that out.

i guess this can be closed as "not an issue" - one just has to know that it only happens in certain optimization levels.

**Comment by ijc8** [comment]
Hello, I'm currently running into this issue. I'm using `-Oz` along with `-sSUPPORT_ERRNO=0` and `-sSUPPORT_LONGJMP=0`, but nonetheless get a wasm binary with various unwanted exports such as `stack*`.

Minimal example:
```shell
$ touch minimal.c
$ emcc -o minimal.wasm -Oz minimal.c --no-entry -sSUPPORT_ERRNO=0 -sSUPPORT_LONGJMP=0
$ stat -c%s minimal.wasm 
198
$ wasm-dis minimal.wasm
```
<details>
<summary>wasm-dis output</summary>

```wat
(module
 (type $none_=>_none (func))
 (type $none_=>_i32 (func (result i32)))
 (type $i32_=>_none (func (param i32)))
 (type $i32_=>_i32 (func (param i32) (result i32)))
 (global $global$0 (mut i32) (i32.const 66560))
 (memory $0 256 256)
 (table $0 2 2 funcref)
 (elem (i32.const 1) $0)
 (export "memory" (memory $0))
 (export "_initialize" (func $0))
 (export "__indirect_function_table" (table $0))
 (export "stackSave" (func $1))
 (export "stackRestore" (func $2))
 (export "stackAlloc" (func $3))
 (func $0
  (nop)
 )
 (func $1 (result i32)
  (global.get $global$0)
 )
 (func $2 (param $0 i32)
  (global.set $global$0
   (local.get $0)
  )
 )
 (func $3 (param $0 i32) (result i32)
  (global.set $global$0
   (local.tee $0
    (i32.and
     (i32.sub
      (global.get $global$0)
      (local.get $0)
     )
     (i32.const -16)
    )
   )
  )
  (local.get $0)
 )
)
```
</details>

It looks like `stack*` are unconditionally added to `REQUIRED_EXPORTS` here:

https://github.com/emscripten-core/emscripten/blob/6e5469075b597701d52659150dfa7859e905121f/tools/link.py#L1282

Should this code check `SUPPORT_LONGJMP`, the same way the code for `__errno_location` checks `SUPPORT_ERRNO`?

https://github.com/emscripten-core/emscripten/blob/6e5469075b597701d52659150dfa7859e905121f/tools/link.py#L1307-L1309

If this seems right, I'm happy to submit a PR!

**Comment by sbc100** [comment]
I think we can probably make the export of 'stackSave', 'stackRestore', 'stackAlloc' conditional on not running in standalone mode.   Can you send a PR for that?

Regarding the export of `__errno_location`, I created PR to simply remove it: https://github.com/emscripten-core/emscripten/pull/21063

**Comment by sbc100** [comment]
The stack function should no longer be exported by default once https://github.com/emscripten-core/emscripten/pull/21075 lands.

**Comment by ijc8** [comment]
Awesome, thanks for the quick response!

**Comment by sbc100** [comment]
I think we can close this now.  Feel free to re-open if you notice any more unexpected exports
