### ISSUE TITLE
PACKAGE_NAME variable is set to an absolute path

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#11910]
I preload a folder with `--preload-file` flag when building my app.

But for some reason, it no longer detects the preloaded `.data` file after I changed my makefile.

And I figured out the  `PACKAGE_NAME` in `js` file is now set to an absolute path even though I preloaded the file using a relative path. (the folder is in the same directory as makefile)

Is it possible to somehow force setting the `PACKAGE_NAME` variable when building the app?

Thank you in advance!

**Comment by Akaricchi** [comment]
> And I figured out the PACKAGE_NAME in js file is now set to an absolute path even though I preloaded the file using a relative path. (the folder is in the same directory as makefile)

This sounds like a regression. Maybe change the issue title to highlight that? We definitely shouldn't put absolute paths in js.

Could you share the exact command and js output sample?

**Comment by cuinjune** [comment]
@Akaricchi I simplified my project and you basically need these 3 commands to test this issue:

```
touch main.c foo.txt
emcc -o $(pwd)/main.html main.c --preload-file foo.txt
grep -r 'var PACKAGE_NAME = ' main.js
```
You will see that `PACKAGE_NAME` is using the absolute path.

So it seems like emscripten sets the `PACKAGE_NAME` variable the same path as the output `html` file even when the path is absolute.

I think this could mislead some users and should be fixed.

**Comment by Akaricchi** [comment]
Definitely needs fixing, but I'm not sure what would be the best way right now.

Meanwhile, you can work around this by invoking the packager directly. This has some other benefits, such as being able to use multiple packages and letting your build system cache them.

```sh
emscripten/tools/file_packager.py my-package.data --preload foo.txt > my-package.js
emcc -o main.html main.c --pre-js my-package.js -s FORCE_FILESYSTEM
```

**Comment by cuinjune** [comment]
@Akaricchi Thank you so much for your suggestion! I think I will just rely on using a relative path for now.

**Comment by kripken** [comment]
I don't think we changed this recently, but maybe it is an unintended regression somehow? Would be good to bisect to find out where it regressed.
