### ISSUE TITLE
Can we output .wat while building Wasm with Emscripten as of now?

### ISSUE THREAD

**Issue by Becavalier** [emscripten-core/emscripten#11913]
As titled.

**Comment by sbc100** [comment]
The best way to get a wat file is run either `wasm2wat` or `wasmdis` on the output wasm.

I'm not sure there is much value in adding and additional flag to have emcc do this under the hood automatically.   But maybe I'm missing something?

**Comment by Becavalier** [comment]
@sbc100 Yes, I see something like this in the document but seems it doesn't work.

![image](https://user-images.githubusercontent.com/8282020/90324278-2adad500-df9f-11ea-8b03-9533ae2d0832.png)

**Comment by sbc100** [comment]
Thanks!  

I opened #11919 to get those docs updated.

**Comment by Becavalier** [comment]
Cool! Thanks for updating!
