### ISSUE TITLE
pthread_create doesnt fire when ENVIRONMENT_IS_WORKER

### ISSUE THREAD

**Issue by AlexVestin** [emscripten-core/emscripten#11914]
Hello,
Been trying to create a pthread pool with emscripten, but having issues with getting the threads started when calling it from a web worker.

A small example `pthread_test.c`:
```C
#include <pthread.h>
#include <stdio.h>
void* tTask(void* arg) {
  printf("hello \n");
  return NULL;
}

int run() {
  printf("Starting run\n");
  pthread_t pid;
  pthread_create(&pid, NULL, tTask, NULL);
  pthread_join(pid, NULL);
  printf("Done\n");
  return 0;
}
```
with a simple html file that creates the worker `worker.js`
```JavaScript
importScripts('Wasmpool.js');
const Module = {
  locateFile: file => file,
  onRuntimeInitialized: () => Module._run(),
  mainScriptUrlOrBlob: 'Wasmpool.js',
};
WasmPool(Module);
```

tTask is called when exported using html as output, renaming run to main and adding the flag `-s PROXY_TO_PTHREAD`, but not in a worker as above. 
I tried it with the `latest` & `tot` builds and `Chrome Version 84.0.4147.125 64bits` + `Chrome Version 86.0.4234.0 (Official Build) canary`.
Any ideas?

Edit: Looks like it gets stuck [here](https://github.com/emscripten-core/emscripten/blob/master/src/worker.js#L203) , but the signature seems correct

**Comment by SegmentationFaultError** [comment]
I am in your same situation. It seems you cannot even perform basic IO... See my post in https://groups.google.com/d/msg/emscripten-discuss/EO1q0lDKi6Y/EqvVb1_AAwAJ

**Comment by msabwat** [comment]
Hi @AlexVestin thanks for the report, 

I tested your sample with these options:
```
emcc main.c -s MODULARIZE=1 -s 'EXPORT_NAME="WasmPool"' -s "EXPORTED_FUNCTIONS=["_run"]" -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -o Wasmpool.js 
```
are they all right (compared to what you did?)

I think the issue is that [this message](https://github.com/emscripten-core/emscripten/blob/master/src/library_pthread.js#L533), does not get to the worker. I am not sure about the reason why for now. 

[it says here](https://github.com/emscripten-core/emscripten/blob/c65f5eb0bfb2e8b373c0dcf51fc8c5c343380e15/src/library_pthread.js#L481) that spawnThread() cannot be called outside the main_thread, so one would expect runPthread() to  run [here](https://github.com/emscripten-core/emscripten/blob/c65f5eb0bfb2e8b373c0dcf51fc8c5c343380e15/src/library_pthread.js#L320) but it is not.

I am looking at code [here](https://github.com/emscripten-core/emscripten/blob/8cadca88dd4f1752a6cac08d1d0c595f5b055fad/src/worker.js#L115), and I also noticed that createWasm() gets called twice, even though only one worker is spawned (as expected)

**Comment by AlexVestin** [comment]
Hello @msabwat,
I'm building with;
```	
emcc pthread_test.c \
		-s MODULARIZE=1\
		-s EXPORT_NAME="'WasmPool'"\
		-s INITIAL_MEMORY=100MB \
		-s USE_PTHREADS=1 \
		-s ENVIRONMENT=worker,web \
		-s EXPORTED_FUNCTIONS="['_run']" \
		-s ASSERTIONS=1 \
		-o Wasmpool.js 
```

which hangs. But changing `int run() {` to `int main() {` and compiling with 
```
	emcc pthread_test.c \
		-s PROXY_TO_PTHREAD \
		-s INITIAL_MEMORY=100MB \
		-s USE_PTHREADS=1 \
		-s ENVIRONMENT=worker,web \
		-s ASSERTIONS=1 \
		-o Wasmpool.html 
```
works.

**Comment by SegmentationFaultError** [comment]
I do get the thread spawned, and it seems to execute again my worker's JS code. At this point I realized that this was killing its own onmessage (substituted by mine). If you skip this, you get a running worker-thread from a webworker. Except that, the execution on the C++ thread gets locked once it reaches a printf, or a new thread spawn point, during execution inside this thread.

I guess this is hacky from the beginning, but what alternatives do we have if we want to run a function that is not _main_ (from a webworker)? Current alternative I see is: pack all the pipeline functions I have in _main_ and prepare all before hand + a new instance each execution.

**Comment by AlexVestin** [comment]
Think I found what is going wrong. 
The pthread_join gets inserted before the worker thread is spawned going into this [infinite loop](https://github.com/emscripten-core/emscripten/blob/master/src/library_pthread.js#L841), stopping the worker from being spawned and completing its work.

I tried adding a quick hack [here](https://github.com/emscripten-core/emscripten/blob/master/src/library_pthread.js#L859)
```JavaScript
  if (!blockFlag) { // global variable added at top of file as false
          blockFlag = true;
          setTimeout(() => __emscripten_do_pthread_join(thread, status, block), 0);
          return;
        }
```
which seems to fix the blocking issue, but there is probably a more bettwe way to do it

**Comment by AlexVestin** [comment]
Seems like the [pthread_join loop](https://github.com/emscripten-core/emscripten/blob/master/src/library_pthread.js#L841) is inserted before the worker has gotten a chance to load (guess that it's loaded async), making the loop infinite.

**Comment by kripken** [comment]
If the problem has been identified here, it would be good to open a PR with at least a test for it, even if you don't have a fix for it yet.

There are a lot of pthreads tests in `tests/test_browser.py`, finding and modifying one would be best as then the modification can show exactly what wasn't being tested before.

**Comment by adepierre** [comment]
I had a similar problem, I managed to find a solution by naming my worker and checking its name to avoir the overwritting of the onmessage function (see #11620 ). Could it help you to solve your issue?

**Comment by SegmentationFaultError** [comment]
> 
> 
> I had a similar problem, I managed to find a solution by naming my worker and checking its name to avoir the overwritting of the onmessage function (see #11620 ). Could it help you to solve your issue?

Yes! I arrived to the same conclusion (check if onmessage has a value). Any solution to use IO on threads? Besides this, I also get stuck execution when spawning threads from threads.

**Comment by AlexVestin** [comment]
> I had a similar problem, I managed to find a solution by naming my worker and checking its name to avoir the overwritting of the onmessage function (see #11620 ). Could it help you to solve your issue?

I don't have an onmessage in the worker, so I don't think that fixes it.

@kripken I added a test case in #12080
