### ISSUE TITLE
_main in EXPORTED_FUNCTIONS with STANDALONE_WASM causes an error

### ISSUE THREAD

**Issue by mbovel** [emscripten-core/emscripten#11939]
Given `test.c`:

```c
int main(int argc, char* argv[]) { return 0; }
```

Compiling with:

```bash
$ emcc -s STANDALONE_WASM -g2 -O3 -s 'EXPORTED_FUNCTIONS=["_main"]' test.c -o test.js
```

Works as expected with `1.39.14`, but fails with `1.39.20` with error:

```
emcc: error: undefined exported function: "_main" [-Wundefined] [-Werror]
```

Removing `_main` from exported functions yields the following warning:

```
system_libs:WARNING: main() is in the input files, but "_main" is not in EXPORTED_FUNCTIONS, which means it may be eliminated as dead code. Export it if you want main() to run.
```

**Comment by sbc100** [comment]
This doesn't look like it has anything to do with the main being an include file.  I reproduces with `main` defined in the C file too.

I guess we have a bug in our special handling of the entry point with STANDALONE_WASM.. we treat `_start` as the entry point for STANDALONE_WASM files, and not `_main`.   However I don't think we should disallow the exporting of main explicitly if somebody wants to do that.

**Comment by mbovel** [comment]
> This doesn't look like it has anything to do with the main being an include file. I reproduces with `main` defined in the C file too.

Oh, indeed. I updated the title and the description in accordance.

**Comment by sbc100** [comment]
I've got a fix which suppresses the warning.   

However, I hope its OK that what we actually export is the `_start` function (which is the wasi entry poiint). 
 not the `main` function.   Is that OK for you?

**Comment by mbovel** [comment]
Thank you very much for having a look so fast.

Still sounds a bit confusing to me.

To elaborate on my use-case, I actually don't need a `_main` entry-point at all; I just added it to avoid the warning `system_libs:WARNING: main() is in the input files, but "_main" is not in EXPORTED_FUNCTIONS, which means it may be eliminated as dead code. Export it if you want main() to run.`. I need other exports though (`-s 'EXPORTED_FUNCTIONS=["_benchmarkSetupEach", "_benchmarkTeardownEach", "_benchmarkRun", ...]'`), hence the usage of `EXPORTED_FUNCTIONS`. The reason is that I use the generated binary in two different contexts, once as a _reactor_ (calling the exported functions individually) and once as a _command_ (calling only the entry point).

Not sure I got everything, but the most logical to me would be:

- Having the ability to set `STANDALONE_WASM` along with `EXPORTED_FUNCTIONS` without `_start` nor `_main`, and not throw a warning (this is what I would use),
- Throwing an error if `_main` is in  `EXPORTED_FUNCTIONS`, as it will not be exported anyway (if I understood correctly),
- Maybe accepting `_start` in `EXPORTED_FUNCTIONS` in this case as it will indeed be exported.

**Comment by sbc100** [comment]
Ah... I see.

I suggest we go with some variant of option 1.   We could make the warning into a real diagnostic warning so you could do `-Wno-unused-main`?    Alternatively could you put the main function in its own object file or library and don't include that when building your reactor?   I think it should be enough to have in its own object file actually?    Is your input code in the form of object files or libraries?

**Comment by mbovel** [comment]
Great, looks like this fixed my problem, thanks! So this is solved as far as I am concerned, but I'll still answer the questions.

>  We could make the warning into a real diagnostic warning so you could do `-Wno-unused-main`?

Yes, but is this warning ever relevant with `STANDALONE_WASM`? `_main` might not be eliminated as dead code as the message suggests, because it is used by `_start`. Right?

> Is your input code in the form of object files or libraries?

For my use-case (benchmarks in GraalWasm), `_main` is just defined in a [header file](https://github.com/oracle/graal/blob/master/wasm/includes/bench/harness.h) included from [other source files](https://github.com/oracle/graal/blob/master/wasm/src/org.graalvm.wasm.benchcases/src/bench/c/micro/qsort.c). We typically compile with:

```
$ emcc -s STANDALONE_WASM -g2 -O3 -s 'EXPORTED_FUNCTIONS=["_benchmarkIterationsCount", "_benchmarkSetupOnce", "_benchmarkSetupEach", "_benchmarkTeardownEach", "_benchmarkRun", "_main"]' .../qsort.c -o .../qsort.js -I .../includes/bench
```

We then use `node qsort.js` directly to benchmark Node.js, and call the individual `_benchmark*` methods from `qsort.wasm` in a JMH benchmark to benchmark GraalWasm. It is done this way to ensure that the benchmarked code is _exactly_ the same from Node.js and GraalWasm. But I am not sure how relevant that is. Maybe should we generate different binaries for the two use-cases with different commands.

**Comment by sbc100** [comment]
> Great, looks like this fixed my problem, thanks! So this is solved as far as I am concerned, but I'll still answer the questions.
> 
> > We could make the warning into a real diagnostic warning so you could do `-Wno-unused-main`?
> 
> Yes, but is this warning ever relevant with `STANDALONE_WASM`? `_main` might not be eliminated as dead code as the message suggests, because it is used by `_start`. Right?

The warning is supposed to help people what do not explicitly export `main` or `_start` but who's codebase contains a main function.   We take this as a sign that they are trying to build a command and warm them: "hey did you mean to build an executable rather than a library?".   Perhaps this is unnecessary and we can just remove the warning.

> 
> > Is your input code in the form of object files or libraries?
> 
> For my use-case (benchmarks in GraalWasm), `_main` is just defined in a [header file](https://github.com/oracle/graal/blob/master/wasm/includes/bench/harness.h) included from [other source files](https://github.com/oracle/graal/blob/master/wasm/src/org.graalvm.wasm.benchcases/src/bench/c/micro/qsort.c). We typically compile with:
> 
> ```
> $ emcc -s STANDALONE_WASM -g2 -O3 -s 'EXPORTED_FUNCTIONS=["_benchmarkIterationsCount", "_benchmarkSetupOnce", "_benchmarkSetupEach", "_benchmarkTeardownEach", "_benchmarkRun", "_main"]' .../qsort.c -o .../qsort.js -I .../includes/bench
> ```
> 
> We then use `node qsort.js` directly to benchmark Node.js, and call the individual `_benchmark*` methods from `qsort.wasm` in a JMH benchmark to benchmark GraalWasm. It is done this way to ensure that the benchmarked code is _exactly_ the same from Node.js and GraalWasm. But I am not sure how relevant that is. Maybe should we generate different binaries for the two use-cases with different commands.

I mean you can use the same compiled wasm code in both cases, but can't use a fully linked wasm both as a command *and* a reactor.   At least not right now.  So you want to build qsort_exe.wasm and qsort_lib.wasm.   One will export `_start` (which run static constructors and then `main`.  The other will export `_initialize` (for running static constructors) afterwhich you can call any of the exports.

This is kind of like the difference between an executable ELF and a shared object (.so) ELF.   You don't get single binary that act as both (actually technically maybe you can but nobody does this in practice).

**Comment by sbc100** [comment]
As long as you link the same libsort.a into both binaries you will be running the exact same code because libsort.a contains fully compiled wasm code and the linker won't touch it (modulo relocations).

**Comment by mbovel** [comment]
Ok, we'll make two separated `qsort_exe.wasm` and `qsort_lib.wasm` then.

Thanks for the insights!
