### ISSUE TITLE
emscripten 2.0.0 build question

### ISSUE THREAD

**Issue by chenrui333** [emscripten-core/emscripten#11931]
👋  Just noticed that it looks like there is no 2.0.0 release tag for `emscripten-core/emscripten-fastcomp` and `emscripten-core/emscripten-fastcomp-clang`, not quite sure if that is intended. Thanks!

Kind of relates to https://github.com/Homebrew/homebrew-core/pull/59509

**Comment by sbc100** [comment]
As of 2.0.0 there is no more fastcomp support in emscripten!  Hurrah!

The official upstream llvm backend now the only compiler backend that we support.     This has been many years I planning now and we had thought there were no remaining fastcomp users.    Is there some problem with the homebrew formula and the upstream backend?

**Comment by sbc100** [comment]
The idea is that users who really need fastcomp can just pin to 1.40.1.. so homebrew can continue to pin to 1.40.1 for an interim period if needed.

**Comment by chenrui333** [comment]
yeah, I was trying to remove `fastcomp` in [this PR](https://github.com/Homebrew/homebrew-core/pull/59629), but runs into some issue. Somehow `emscripten 2.0.0` builds out fine with the pinned 1.40.1 `fastcomp`. Can you take a look at my PR? Thanks!

**Comment by sbc100** [comment]
Which PR would you like me to look at ?  https://github.com/Homebrew/homebrew-core/pull/59629 looks like its closed already.

**Comment by MaxGraey** [comment]
It will be great if homebrew's version also migrate to upstream for 2.0.0 without pinning `fastcomp`. It's pretty important also for binaryen development for mac users. Unfortunately I'm really bad at devops stuffs otherwise I would help with this

**Comment by chenrui333** [comment]
@sbc100 we are using this one at the moment, https://github.com/Homebrew/homebrew-core/pull/59509

**Comment by chenrui333** [comment]
@MaxGraey good to know.

**Comment by MaxGraey** [comment]
@chenrui333 this my attempt build formula from scratch for upstream: https://gist.github.com/MaxGraey/2967952d64980ef7acbbbb1bd8fdf953

**Comment by chenrui333** [comment]
> @chenrui333 this my attempt build formula from scratch for upstream: https://gist.github.com/MaxGraey/2967952d64980ef7acbbbb1bd8fdf953. But it's a mess. Also I'm totally unfamiliar with Ruby so it's really hard for me

Nice, I will try it out now.

**Comment by sbc100** [comment]
Sadly I don't think you can (yet) depend on the llvm homebrew formula.   This is because emscripten doesn't currently support running with the stable version of llvm, only the latest tpi of tree version.

I think you need to replace the current fastcomp checkout + build with https://github.com/llvm/llvm-project (you can use tip of tree or figure out the exact revision needed by looking at the emscripten-releases repository). 

The cmake command for fascomp will need to be a little adapted too.  Mostly the supported targets should be set to WebAssembly.
