### ISSUE TITLE
emscripten_idb_async_store doesn't work on page close

### ISSUE THREAD

**Issue by marukrap** [emscripten-core/emscripten#11932]
I'm trying to make persistent save system for my game.

The first thing I did was to use `IDBFS` with `FS` library. I made a simple save/load code and it worked. And I wanted to save on page close, I used `emscripten_set_beforeunload_callback`'s callback function to save data. But it didn't work well. It works when I refresh the page, but it doesn't work if I close the tab by clicking X. (Tested on Chrome)

Then I tried another API like `emscripten_idb_async_store`. It works better, but still sometimes it doesn't save anything on page close. The synchronous functions(`emscripten_idb_store`) were the same. Sometimes it works, but sometimes it doesn't.

My code and a demo are here.
https://github.com/marukrap/RoguelikeTutorial2020/blob/master/Sources/Part11/Main.cpp#L21
https://marukrap.github.io/RoguelikeTutorial2020/Demos/Part11.html

In my test, often `emscripten_idb_async_store`'s callback functions(both `onstore` and `onerror`) never called. I added blocking code to `beforeunload` and `unload` events in javascript and printed some test log.

Also in the documentation, it says if you use `emscripten_set_main_loop`, `SDL_QUIT` event will work when the page is shut, but it doesn't seem to work when I put some code in there. I tried to save something and print some log but nothing happened.

**Comment by kripken** [comment]
I think the `beforeunload` HTML event can help here, https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event (or `onunload`, but that's not cancelable).

**Comment by marukrap** [comment]
I think it seems `beforeunload`(or `unload`) event just closes the page before the asynchronous functions are finished. And AFAIK there's no way to cancel this event except you use a confimation dialog. Also `emscripten_idb_store`(synchronous one) works the same as asynchronous functions in this case.

So is there any way to wait these asynchronous functions in `beforeunload` event? or do I need to use thread or something?
