### ISSUE TITLE
How would one pass plain JS Objects to a exported C++ function?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#11943]

**Comment by sbc100** [comment]
I believe the way to do this would be to use embind and have the receiving function take a  `val`.  

Are you using embind already?   Have you tried receiving a `val`?   Have you seen: `https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#using-val-to-transliterate-javascript-to-c`

**Comment by gerald-dotcom** [comment]
> I believe the way to do this would be to use embind and have the receiving function take a `val`.
> 
> Are you using embind already? Have you tried receiving a `val`? Have you seen: `https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#using-val-to-transliterate-javascript-to-c`

I had the val idea but was uncertain. I will try, thanks!

**Comment by gerald-dotcom** [comment]
> > I believe the way to do this would be to use embind and have the receiving function take a `val`.
> > Are you using embind already? Have you tried receiving a `val`? Have you seen: `https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#using-val-to-transliterate-javascript-to-c`
> 
> I had the val idea but was uncertain. I will try, thanks!
> 
> Of course, I'm using embind already

It works. Closing..
