### ISSUE TITLE
I'd like a way to add handling to errors from a worker thread

### ISSUE THREAD

**Issue by rickg-hcl** [emscripten-core/emscripten#11941]
In this code:

https://github.com/emscripten-core/emscripten/blob/551a0af33539f11d04327023fcc3c7fe332f40cc/src/library_pthread.js#L358

I see that when a work thread has an error, we just use the err() function to log the error.

It would be great if an application could register a handler for that condition like:

Module["PThread"].addThreadErrorHandler;

so that we can more gracefully deal with error when it happens.

**Comment by sbc100** [comment]
These days errors from workers are raised as exceptions back on the main thread, so you should be able to use the same mechanism you do for handling errors on the main thread (i.e. using the `noerror` event listener).
