### ISSUE TITLE
swprintf doesn't work in case of characters outside of basic ascii range

### ISSUE THREAD

**Issue by kovacsv** [emscripten-core/emscripten#11947]
swprintf cuts down the string if a character is found outside the 0-125 range. The code below demonstrates the problem. If I write a string to the console without swprintf it seems working. If I copy it to another string with swprintf the string is trimmed.

```cpp
#include <iostream>
#include <locale>
#include <codecvt>

std::string WStringToString (const std::wstring& str)
{
	std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> convert;
	return std::string (convert.to_bytes (str));
}

int main (int, char**)
{
	std::cout << "BEGIN" << std::endl;
	
	std::wstring directString (L"Aa\xc1");
	std::cout << WStringToString (directString) << std::endl;
	
	wchar_t formattedStringBuf[32];
	swprintf (formattedStringBuf, 32, L"%ls", directString.c_str ());
	
	std::wstring formattedString (formattedStringBuf);
	std::cout << WStringToString (formattedString) << std::endl;

	std::cout << "END" << std::endl;
	return EXIT_SUCCESS;
}
```

Compile and run:
```
em++ main.cpp
node a.out.js
```

Output:
```
BEGIN
AaÁ
Aa
END
```

Expected output (no difference between the two methods):
```
BEGIN
AaÁ
AaÁ
END
```

**Comment by AlexanderVitiuk** [comment]
Encountered the same bug, any thoughts on when it will be fixed?

Code:
...
std::wstring w1 = L"Привет";
std::wstring w2 = L"Василий";
wchar_t s[500];
swprintf(s, 500, L"[%ls %ls]", w1.c_str(), w2.c_str());
std::wcout << std::wstring(s).length() << s;
...

Output expected: 16 [Привет Василий]
Output got : 1 [

**Comment by kripken** [comment]
If someone is interested to work on this, let me know if you have any questions about how to debug it. As a starting point, I'd compile the testcase and try to see if the problem happens in libc or in JS support code.

**Comment by faerot** [comment]
Is this a musl bug or emscripten's ?

**Comment by AlexanderVitiuk** [comment]
There are testcase: 

`#include <iostream>
#include <string>
using namespace std;

int main() {
  wstring w1, w2;
  wchar_t s[500];
  // 1. latin:
  w1 = L"Hi";
  w2 = L"there!";
  swprintf(s, 500, L"[%ls %ls]", w1.c_str(), w2.c_str());
  std::wcout << std::wstring(s).length() << s;
  std::wcout << L"\n";

  // cyrillic  
  w1 = L"Привет";
  w2 = L"Василий";
  swprintf(s, 500, L"[%ls %ls]", w1.c_str(), w2.c_str());
  std::wcout << std::wstring(s).length() << s;
  std::wcout << L"\n";
  return 0;
}
 `

To compile:
emcc swprintf.cpp -s EXIT_RUNTIME=1 -o swprintf.html

**Comment by kripken** [comment]
To see if this is musl's fault or emscripten, one way is to compile without emscripten but with the musl code (for example by compiling in the relevant musl `.c` files, or building all of musl if that's not easy). Can also try different musl versions to see if  that matters.

**Comment by kovacsv** [comment]
I'm happy to investigate the musl part, but I haven't find any information on compiling and debugging musl on Windows. If you could help me start maybe I can check if it's a musl error or not.

**Comment by sunfishcode** [comment]
It looks like a musl issue. This C testcase:
```c
#include <wchar.h>

int main() {
  wprintf(L"[hello world]\n");
  wprintf(L"[Привет Василий]\n");
  wprintf(L"[goodbye]\n");
  return 0;
}
```
on x86_64-linux-gnu prints:
```
[hello world]
[Privet Vasilij]
[goodbye]
```
and on x86_64-linux-musl prints:
```
[hello world]
[[goodbye]
```

**Comment by faerot** [comment]
I have found this explanation on musl site about locale limitations:
https://wiki.musl-libc.org/open-issues.html
Does it mean that they won't be fixing it at all?

**Comment by graywolf** [comment]
Since the program starts in C locale (as POSIX mandates), the musl's behaviour
seems correct, see https://www.openwall.com/lists/musl/2020/11/01/5.

I do not know enough about emscripten to say if setlocale will work or not, but
it is definitely worth trying :)

**Comment by kovacsv** [comment]
Thanks @graywolf, you were right. A `setlocale (LC_ALL, "");` call in the main function solved the issue for me!
