### ISSUE TITLE
Data cached to IndexedDB (--use-preload-cache): cache invalidated even if data did not change

### ISSUE THREAD

**Issue by colin-guyon** [emscripten-core/emscripten#11952]
In `file_packager.py` a uuid is generated, that changes at each run even if the packaged data is exactly the same (https://github.com/emscripten-core/emscripten/commit/87ce53bcc7a9385a71901f3750db9fd7a25de077).
Wouldn't it be even better to use a hash of the packaged data instead? (possibly concatenated with something like a DB-format version number to trigger cache invalidation on breaking changes).
Indeed especially when upgrading EMSDK and regenerating packaged data, it would be great to keep using the existing cache instead of dropping it and then re-downloading the exact same data, when possible. (I could try to make a PR when I have time)

(I know it is advised in https://emscripten.org/docs/compiling/Deploying-Pages.html?highlight=preload%20cache to implement a custom data invalidation mechanism if needed, but it would be good to improve the default behavior, if agreed and doable)
Thanks

**Comment by kripken** [comment]
How would this handle hash collisions?

**Comment by colin-guyon** [comment]
It would not, but choosing an appropriate hash algorithm would minimize the risk.
I guess the low probability of a hash collision could be acceptable for many people, but I might be wrong. I understand depending on the application the risk should not be taken.
(In my case I could double check the hash vs the previous one when I know the data changed, and handle the case afterwards if ever it occurs one day)
I was thinking of something like a `--preload-cache-use-hash` option to make such behavior activable, not necessarily the default.

Anyway it is also easy, especially when packaging using `--separate-metadata`, to have its own uuid-replacement (that's what I already do today). It's just that I would have been happy if a DB-Schema version number was present in the file packager sources ;)

**Comment by Akaricchi** [comment]
Just wanted to say that I also employ a similar hack in my project to replace the random UUIDs with sha256 hashes, and would like to see an official option for this.

> How would this handle hash collisions?

A random sha256 collision is so astronomically unlikely it's not even worth considering. But you can always make it even more  astronomically unlikely by appending the data size, if you're paranoid.

**Comment by colin-guyon** [comment]
I chose sha256 too (note: Git uses it internally, and historically uses sha1 too).
It is easy to replace the "uuid" in metadata yes, but I think we would still need a `CACHE_DB_SCHEMA_VERSION = <int to increment over changes>` variable in `file_packager.py` (or a `cache-db-schema-version.txt` file, as it currently exists a `emscripten-version.txt` file). This way generating `"<schema-version>-<hash>"` as uuid replacement would be reliable, and data cache could be invalidated as less often as possible, even when using new versions of EMSDK.
The advantage of a variable in `file_packager.py` could be that when doing modifications to `file_packager.py` there may be less chances to forget to increment the number (when relevant)... (but code reviews exist also to lower the chances to miss this kind of update). Having a dedicated `cache-db-schema-version.txt` file would be slightly easier to find/parse for external scripts. 
(having a hash of `file_packager.py` instead of what I'm suggesting would not be another solution, as obviously modifying the file does not mean the data cache should be invalidated, and in the future the code could also be split to multiple python modules/packages...)

Or maybe there is a smarter solution?

(I also have a concern about the "Key" of cached data stored in IndexedDB that depends on the URL on which data was served, like "metadata/some/path/foo.data" and "package/some/path/foo.data/0" : being allowed to choose an identifier (with a `--key` option) to replace this would be great. This way we could change the route(s) serving data without duplicating the cache. But this could be addressed in another issue/PR)

**Comment by connorjclark** [comment]
Here's how to the workaround @Akaricchi suggested above:

```sh
HASH=$(shasum -a 256 module.data | awk '{print $1}')
sed -i -e "s/\"package_uuid\":\"[^\"]*\"/\"package_uuid\":\"$HASH\"/" module.js
```

This results in the JS emscripten generates only refetching the .data file if some content inside has changed.
