### ISSUE TITLE
Problems using std::future, std::launch::async

### ISSUE THREAD

**Issue by zajo** [emscripten-core/emscripten#11959]
I'm trying to get this simple test to work (on Node) and it seems to deadlock:

```
int main()
{
    std::future<int> fut = std::async(std::launch::async, [] { return 42; });
    return fut.get();
}
```

Is this supported at all? I'm compiling/linking with the following options:

```
WASM=1
USE_PTHREADS=1
PROXY_TO_PTHREAD=1
DISABLE_EXCEPTION_CATCHING=0
```

**Comment by sbc100** [comment]
We have no tests for `std::async` so I guess its not surprising that its not working yet :(      If you would like work on this I think other would be excited to see it happen.

**Comment by kleisauke** [comment]
Try setting `-s PTHREAD_POOL_SIZE=2`, see: https://github.com/emscripten-core/emscripten/issues/8988.

**Comment by zajo** [comment]
Thanks for the suggestion but it did not help.

**Comment by kleisauke** [comment]
I tried this test:
```cpp
#include <future>
#include <iostream>

int main() {
    std::future<int> fut = std::async(std::launch::async, [] {
        return 42;
    });
    std::cout << fut.get() << std::endl;
    return 0;
}
```

I compiled it with:
```bash
emcc test.cpp -std=c++11 -s ASSERTIONS=0 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1 -o test.js
```
<sup>(note that I've set `PTHREAD_POOL_SIZE` to 1, which simply works, so perhaps #8988 is outdated)</sup>

And ran it with Node.js like this:
```bash
node --experimental-wasm-threads -e "require('./test.js')"
```

This prints the expected 42, although the runtime did not exits (I needed to hit <kbd>Ctrl</kbd> + <kbd>C</kbd>). Perhaps that's the problem?

**Comment by kleisauke** [comment]
... If that's the problem, try setting ` -s EXIT_RUNTIME=1` to allow the runtime to quit when `main()` is finished.

(Pressed the comment button too early)

**Comment by zajo** [comment]
Thanks, yes that was the problem. In fact, it didn't even need `PTHREAD_POOL_SIZE`. Is this due to `PROXY_TO_THREAD`?

**Comment by zajo** [comment]
Thanks for the help!
