### ISSUE TITLE
Using standalone modules, emscripten required functions and exporting entire libraries

### ISSUE THREAD

**Issue by Rochet2** [emscripten-core/emscripten#11954]
Oof. Seems that pressing enter directly submitted the issue.

Where should I look for a list of functions the runtime needs to implement in order to work with emscripten standalone modules?
There seems to be no clear documentation or place in code that I have seen yet that lists the emscripten specific functions needed to be defined.
Based on compiler output I would at least need to define the following functions as they are imported by the compiled modules:
- emscripten_stack_get_end
- emscripten_notify_memory_growth

Additionally, how can a module export all of `<string>` or `math.h` for other modules to use?
I have not yet found out a way to export things unless I specifically name them or use them in code.
I would simply want to export all functions of a standard library for example in order for a module to offer them to another.
For example, I would potentially imagine that a cpp file having only `#include <string>` would export the entire string library when using `-Wl,--export-all` or a similar flag.

In my use case I want to be able to use a non-web runtime and create the necessary functions in order to split an application to multiple modules and then link them at load-time and run-time.

**Comment by sbc100** [comment]
There is some ongoing work to make this better.    See #11898 and #11896 

These are mostly internal functions that there are no docs as such other than reading the code.

We hope to be able to reduce the number of extra imports/exports used by standalone modules where possible. 

If you want a truly standalone module today the you might want to look at using wasi-sdk instead, as this will always produce modules with only WASI syscall imports.

**Comment by kripken** [comment]
> emscripten_notify_memory_growth

That is called when memory grows. If you don't need to do anything at that time, it can be a no-op. (In general though, growth may invalidate old JS views, so recreating them at this time can make sense.)

> emscripten_stack_get_end

@sbc100 when would that be used - isn't it behind a flag?

**Comment by Rochet2** [comment]
@sbc100 I tried wasi-sdk previously, but to create the dynamic modules it still seems to require using emscripten as a target. And when doing so I found no way to create a wasi module. I settled for creating modules by targeting WASI for the main module and targeting emscripten for the side module. The compilation commands I used were
```bash
$CC example_main.c -o example_main.wasm -Wl,-no-entry,--allow-undefined,--import-table,--import-memory
$CC --target=wasm32-unknown-emscripten-wasm -fPIC -nostdlib example_side.c -o example_side.wasm -Wl,-shared,-no-entry,--allow-undefined
```
The generated shared module requires importing `__stack_pointer`, which isn't exported by the main module. From inspecting a module I can see that the stack pointer is a mutable global. Mutable globals don't seem to be exportable and a potential workaround could be to generate functions for reading and writing to it. A great help for this workaround would be the possibility to wrap the variable with functions in the main and side module and I noticed that there was a `--wrap` linker flag in wasm-ld, but couldn't get it to work in any way yet. I would imagine that unless mutable globals are supported, the stack pointer must be accessed with functions or it must be stored in the linear memory and the location of it could be exported as a variable - but seems compilers don't do this. Could also be that I don't understand something fundamental or cant find the relevant flags.

I found no good way to access the stack information and instead turned to emscripten as there is some kind of dynamic linking support available. A related conversation can be found here: https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/Obtaining.20stack_pointer.3F

@kripken for me it is imported when using the following. Removing the export-dynamic will remove the import:
```bash
emcc test.cpp -o test.wasm -s SIDE_MODULE=0 -Wl,--no-entry,--export-dynamic
```
```cpp
#include <iostream>
#include <stdexcept>
#include <string>

__attribute__((used))
int test() {
    std::cout << "moi" << std::endl;
    std::cin.get();
    throw std::runtime_error("foobar");
    return 0;
}
```

**Comment by sbc100** [comment]
You are correct.  If you really need dynamic module linking then you need to use emscripten (today anyway).

I would not try to linking modules build with wasi-sdk and emscripten together that is just asking for trouble.

Do you really need dyanmic linking though?  Often times people discover they can get by without it and simplify their program significantly in doing so.

**Comment by sbc100** [comment]
Also. if you are using standalone mode I'm not sure how you could hope to use dynamic linking.  Dynamic linking in emscripten is powered by a whole bunch of JS code.. so the dynamically linked modules are not at all standalone and won't run without a whole bunch of JS support code.

**Comment by Rochet2** [comment]
> Do you really need dyanmic linking though?

Yes and no. The required part is exactly having run-time linking. However, if no suitable ways to achieve that for my purposes can be feasibly achieved (even if it requires replicating that JS support code), then a shared-nothing linking case can be used where multiple independent modules communicate through the host environment. That is a lot more limited though as there is a lot of performance overhead in intermodule communication.

> the dynamically linked modules are not at all standalone and won't run without a whole bunch of JS support code.

So far I have dynamic linking implemented at least on a basic level, where the memory, table and linking between the functions of modules is handled. There might be some parts that are missing, but currently simple C code compiled to wasm can be linked together ok, with the occasional missing function imports that then need to be implemented, such as the 2 mentioned in the original post above.

**Comment by Rochet2** [comment]
Closing as the main question about if there is a listing of the required functions was answered.

> These are mostly internal functions that there are no docs as such other than reading the code.

It also seems that there is no single place in code that lists all of these functions.
