### ISSUE TITLE
ERROR about EXPORTED_FUNCTION

### ISSUE THREAD

**Issue by BKAUTO** [emscripten-core/emscripten#11963]
Hello,

I am using the latest [emscripten/emsdk:2.0.0](https://hub.docker.com/layers/emscripten/emsdk/2.0.0/images/sha256-1fe842e8a10b225df4a65e37c4364d7ad96183ea86df0b4aeb8c519a8858981c?context=explore) docker to compile the latest [skia/canvaskit](https://skia.org/user/modules/canvaskit). 

I have met an error about EXPORTED_FUNCTIONS:
`error: undefined symbol: emscripten_webgl_get_current_context (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _emscripten_webgl_get_current_context may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: emscripten_webgl_make_context_current (referenced by top-level compiled C/C++ code)
warning: _emscripten_webgl_make_context_current may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/emsdk/node/12.18.1_64bit/bin/node /emsdk/upstream/emscripten/src/compiler.js /tmp/tmpspldwdwf.txt' failed (1)`

The error could be avoided by removing the '-s STRICT=1' parameter from em++. And these two functions can work correctly on website. It seems like someone has run into a similar issue([#9965](https://github.com/emscripten-core/emscripten/issues/9965)) which resulted to a fix of symbols files.

**Comment by sbc100** [comment]
One of the effects of enabling `STRICT` mode is that js libraries are not included automatically.

You should be able to fix the link error by expictly linking againt the library that contains that function: library_html5_webgl.js.  You can include this library by adding `-lGL` to the link line.

**Comment by BKAUTO** [comment]
That would fix it. Thanks!
