### ISSUE TITLE
UTF8ToString made a text string garbled.

### ISSUE THREAD

**Issue by fintechee** [emscripten-core/emscripten#11960]
Hi,

I encountered a very strange issue.

UTF8ToString made a text string garbled.
Not every string.
I input "abc def", the function encoded perfect.
I input "macdsample", the function worked as well.
But, when I input "macd sample", I got a garbled string -- "ȕP". 

Please help me find the reason and the solution.
Many thanks.

**Comment by DConmy** [comment]
There is not enough to provide a definitive answer.   But perhaps you are hitting a threading issue.   Specifically, if you are using calls from pthreads to get onto the browser thread, and are providing a UTF8 string from the stack, or for memory that can't be guaranteed to still exist at execution time on the browser main thread, you would then be converting garbage.   If that were the case, sometimes you get lucky and the memory is still what it was at the time of the request, and other times the memory has been reused for something else which will look like garbage.

**Comment by fintechee** [comment]
Thank you for your answer.
But I don't think it's an coincident issue.
Because just this string -- "macd sample" led problem.
And every time the output is the same -- ȕP.

Please check our source codes:
EM_JS(int, jOrderSend, (int uid, string symbol, const char* cmd, double volume, double price, int slippage, double stoploss, double takeprofit, string comment, int magic, datetime expiration, int arrow_color), {
   return Asyncify.handleSleep(function (wakeUp) {
    try {
      var symbolName = UTF8ToString(symbol);
      const orderType = UTF8ToString(cmd);
      const cmmnt = UTF8ToString(comment);
      var obj = window.mqlEAsBuffer[uid + ""];
      if (symbolName == "") {
        symbolName = obj.symbolName;
      }
      obj.lock = true;
      document.addEventListener("customevent", function (e) {
        window.mqlEAsBuffer[uid + ""].lock = false;
        wakeUp(parseInt(e.detail));
			}, {once: true});
      sendOrder(obj.brokerName, obj.accountId, symbolName, orderType, price, slippage, volume, takeprofit, stoploss, cmmnt, magic, expiration);
    } catch (e) {
      printErrorMessage(e.message);
      var event = new CustomEvent("customevent", {detail: -1});
  		document.dispatchEvent(event);
    }
  });
});

**Comment by DConmy** [comment]
What C/WASM code is calling jOrderSend?
If symbol, cmd and or comment are stack local to another thread, the results will be indeterminate.  Given that handleSleep could pause thread execution, that could also contribute to inconsistent results if it is a threading issue.

**Comment by fintechee** [comment]
Thank you for your reply.
I use C++ calling jOrderSend.

And, I made a compact sample. Please compile it and reproduce the garbled string.

testUTF8.html
<html>
  <head>
	   <meta charset="utf-8">
  </head>
  <body>
    <div id="j">
    </div>
    <script defer>
      var module = null
      var setjPrint = null
      var jPrint = null
      var cTest = null

      function jTest (comment) {
        window.comment = comment
        console.log(comment)
        var event = new CustomEvent("customevent", {detail: 1});
    		document.dispatchEvent(event);
      }

      function loadJs () {
				var scriptPromise = new Promise(function (resolve, reject) {
				  var script = document.createElement("script")
				  document.body.appendChild(script)
				  script.onload = resolve
				  script.onerror = reject
				  script.async = true
				  script.src = "http://127.0.0.1:8082/testUTF8.js"
				})

				scriptPromise.then(function () {
          API().then(function (Module) {
            module = Module
            jPrint = Module.addFunction(function (s) {
              console.log(module.UTF8ToString(s))
            }, "vi")
            setjPrint = Module.cwrap('setjPrint', null, ['number'])
            setjPrint(jPrint)
            cTest = Module.cwrap('cTest', null, null)
            cTest()
          })
        })
      }

      loadJs()
    </script>
  </body>
</html>


testUFT8.cpp

#include <stdio.h>
#include <stdarg.h>
#include <string>
#include <sstream>
#include <iostream>
#include <map>
#include <vector>
#include <algorithm>
#include <climits>
#include <float.h>
#include <unistd.h>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <chrono>
#include <emscripten.h>
using namespace std;

void (*jPrint) (const char*);

EM_JS(int, test, (string comment), {
   return Asyncify.handleSleep(function (wakeUp) {
    try {
      const cmmnt = UTF8ToString(comment);
      document.addEventListener("customevent", function (e) {
        wakeUp(parseInt(e.detail));
			}, {once: true});

      jTest(cmmnt);
    } catch (e) {
      var event = new CustomEvent("customevent", {detail: -1});
  		document.dispatchEvent(event);
    }
  });
});

extern "C" {
  EMSCRIPTEN_KEEPALIVE
  void setjPrint (void (*f) (const char*)) {
    jPrint = f;
  }
}

template <class Type, class... Types>
void Print (const Type & arg, const Types &... args) {
  stringstream s;
  s << arg;
  ((s << args), ..., (s << endl));
  jPrint(s.str().c_str());
}

extern "C" {
  EMSCRIPTEN_KEEPALIVE
  void cTest () {
    test("abc efg");
    test("macdsample");
    test("macd sample");
  }
}

build command:
emcc testUTF8.cpp -o testUTF8.js -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap", "addFunction", "UTF8ToString"]' -s RESERVED_FUNCTION_POINTERS=100 -s MODULARIZE=1 -s 'EXPORT_NAME="API"' -s ENVIRONMENT=web -s ASYNCIFY -s 'ASYNCIFY_IMPORTS=["test"]' -O3

http server:
http-server -p 8082 --cors=Authorization

**Comment by fintechee** [comment]
@DConmy 
Hi, any update?
Thanks.

**Comment by sbc100** [comment]
I think the bug is in the EM_JS declaration: `EM_JS(int, test, (string comment)`.     The type of `comment` should be `const char*`.   EM_JS and EM_ASM functions cannot can only recieve basic types such as integers, floats and pointers.

**Comment by fintechee** [comment]
@sbc100
Thanks for your response.
Technically, we may have tested "const char*"...
But I forgot what the result was.
We will test it soon and get back to you.

**Comment by fintechee** [comment]
@sbc100
Exactly!
const char * works!
Thank you!
