### ISSUE TITLE
Can wasm files be cached by the browser?

### ISSUE THREAD

**Issue by realray808** [emscripten-core/emscripten#11971]
I have compiled my c++ project using emscripten. And I found that every time I visited in the browser, I would download the wasm file again. I am confused why the wasm file is not cached. This puts pressure on my web server.
Can you teach me how to cache wasm files? THX : )

**Comment by curiousdannii** [comment]
From the perspective of HTTP it should be just a file like any other. What HTTP headers is your server sending?
