### ISSUE TITLE
Build problem since 1.39.16

### ISSUE THREAD

**Issue by mdhsl** [emscripten-core/emscripten#11977]
Hi everybody,

I am using Emscripten for a while to build ffmpeg.js from FFMPeg original lib. For that, I am using docker image: https://hub.docker.com/r/trzeci/emscripten

I was working fine until the version 1.39.15. After that, I've got a wrong output file as emake output.

The problem concerns all version >= 1.39.16 (I have also tested the last 2.0.0 version).

Here the relevant compilation options:

```
 emconfigure ./configure \
    --nm="llvm-nm -g" \
    --cxx=em++ \
    --ar=emar \
    --ranlib="emranlib" \
    --cc=emcc \
    --objcc=emcc \
    --dep-cc=emcc \
    --enable-cross-compile \
    --target-os=none \
    --arch=i686 \
    --disable-runtime-cpudetect \
    --disable-asm \
    --disable-fast-unaligned \
    --disable-pthreads \
    --disable-w32threads \
    --disable-os2threads \
    --disable-debug \
    --disable-stripping \
    \
    --disable-all \
    --enable-ffmpeg \
    --enable-avcodec \
    --enable-avformat \
    --enable-avutil \
    --enable-swresample \
    --enable-swscale \
    --enable-avfilter \
    --disable-network \
    --disable-d3d11va \
    --disable-dxva2 \
    --disable-vaapi \
    --disable-vdpau \
    --enable-decoder=h264 \
    --enable-decoder=vp9 \
    --enable-decoder=vp8 \
    --enable-decoder=hevc \
    --enable-protocol=file \
    --disable-bzlib \
    --disable-iconv \
    --disable-libxcb \
    --disable-lzma \
    --disable-securetransport \
    --disable-xlib \
    --disable-zlib
```
and

```
emmake make -j32
```
Full script here:  [https://github.com/mdhsl/ffmpeg.js/blob/master/build-js.sh](url)

In the working version (1.39.15), the *emmake* produce some kind of binary file which can be used as *emcc* input.

For the version >= 1.39.16, the *emmake* produce a javascript file (and a .wasm), so it becomes an invalid input for *emcc*.

I don't understand why I am getting a javascript file for the version >= 1.39.16 without changing any line of code.

Output:
Version 1.39.15:
```
[...]
AR      libavcodec/libavcodec.a
LD      ffmpeg_g
emcc: warning: Assuming object file output in the absence of `-c`, based on output filename. Add with `-c` or `-r` to avoid this warning [-Wemcc]
emcc: warning: ignoring unsupported linker flag: `-rpath-link=:libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample` [-Wlinkflags]
CP      ffmpeg
STRIP   ffmpeg
skipping strip ffmpeg
Emscripting ffmpeg into js
-rwxrwxrwx 1 root root 4.6M Aug 20 15:56 build/FFmpeg/ffmpeg.bc
emcc:WARNING: --llvm-lto ignored when using llvm backend
system_libs:WARNING: main() is in the input files, but "_main" is not in EXPORTED_FUNCTIONS, which means it may be eliminated as dead code. Export it if you want main() to run.
```
All fine here.
Now, for >= 1.39.16
```
[...]
AR      libavutil/libavutil.a
3 warnings generated.
8 warnings generated.
7 warnings generated.
AR      libswscale/libswscale.a
3 warnings generated.
AR      libavcodec/libavcodec.a
LD      ffmpeg_g
emcc: warning: ignoring unsupported linker flag: `-rpath-link=:libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample` [-Wlinkflags]
CP      ffmpeg
STRIP   ffmpeg
skipping strip ffmpeg
Emscripting ffmpeg into js
-rw-rw-rw- 1 root root 258K Aug 20 16:12 build/FFmpeg/ffmpeg.bc
emcc:WARNING: --llvm-lto ignored when using llvm backend
emcc: warning: build/FFmpeg/ffmpeg.bc is not a valid input file [-Winvalid-input]
emcc: error: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.C', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.S', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.s', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
```

Thanks for your Help and for the amazin work your are making for this project!

**Comment by kripken** [comment]
Reading the changelog, one of the entries for that release is
```
- Compiling to a file with no suffix will now generate an executable (JS) rather
  than an object file.  This means simple cases like `emcc -o foo foo.c` do the
  expected thing and generate an executable.
```
Looks like that was added in #11108

**Comment by mdhsl** [comment]
Thanks for replying. 

The problem is happening before executing emcc. 
Here the following order of the commands:
- emconfigure ./configure [...]
- emmake make -j => Should produce an object file but getting a JS file instead
- emcc [...]

I don't know if the issue is causing by emconfigure or emmake

**Comment by sbc100** [comment]
Yes this is due to that recent change which does break compatibility for cases like this.   However in some ways it also increates comptability (with systems like autoconf) since in this case autoconf and make is indending to build and executable an not a library.

The problem is that ffmpeg that make it build is an execuable and as such you cannot use it as the input to another compile step (just like on native systems).

I guess my question is .. given that you already have an ffmpeg executable why are you trying to run emcc again?   Can you now just have `make` produce the final output for you?

Can you show me the full emcc command line?  Perhaps we can instead pass the right set of link flags and you can avoid the post-list-emcc command completely?

**Comment by mdhsl** [comment]
I set some options to create the final JS output that fit my requirements.

Here the full emcc command:

```
emcc build/FFmpeg/ffmpeg.bc \
    -o dist/ffmpeg-h264.js \
    -O3 \
    -s MODULARIZE=1 \
    --memory-init-file 0 \
    -s WASM=1 \
    --llvm-opts 3 \
    --llvm-lto 3 \
    -g0 \
    --closure 1 \
    -s SINGLE_FILE=1 \
    -s NO_EXIT_RUNTIME=1 \
    -s 'EXPORT_NAME="OSH"' \
    -s EXPORTED_FUNCTIONS='["_avcodec_register_all","_avcodec_find_decoder_by_name","_avcodec_alloc_context3","_avcodec_open2", "_av_init_packet", "_av_frame_alloc", "_av_packet_from_data", "_avcodec_decode_video2", "_avcodec_flush_buffers"]' \
    -s EXTRA_EXPORTED_RUNTIME_METHODS='["FS", "ccall", "getValue", "setValue", "writeArrayToMemory"]' \
    -s TOTAL_MEMORY=134217728
```

I am exporting only function that I need and provide some optimization options

**Comment by mdhsl** [comment]
'Can you show me the full emcc command line? Perhaps we can instead pass the right set of link flags and you can avoid the post-list-emcc command completely?'

I was thinking about a solution like that but I don't know how to do that :)

**Comment by sbc100** [comment]
So you probably just want to set all those linker flags when you run `./configure`

For information on how to do that see for example this stackoverflow answer: https://unix.stackexchange.com/questions/149359/what-is-the-correct-syntax-to-add-cflags-and-ldflags-to-configure/149361

However it looks like you are trying to build a library rather than an executable.   is that right?   So ideally you would not use the ffmpeg target as the target you ship, but you would instead create a new wasm library based on the on the ffmpeg libraries.   If that is the case then you actually do probably want to run your own link command but pass it libavcodec.a rather than ffmpeg.bc.   What happens if you keep your emcc command and replace ffmpeg.bc with as list of all the libraries (libavcodec.a libswscale.a libavutil.a etc...)

**Comment by sbc100** [comment]
Sorry, I confusingly made two different suggestions for solutions in my previous comment.

1. Add LDFLAGS to configure such that the ffmpeg binary build by make is already what you want
2. Modify your emcc command line to refer to actual libraries not the ffmpeg executable.

I actually think in this case option (2) more correct.   Can you try it (replace ffmpeg.bc with as list of all the libraries (libavcodec.a libswscale.a libavutil.a etc...)

**Comment by mdhsl** [comment]
I think the solution 2) would work since I am using only libav functions. I will give a try and let you know. Thanks!

**Comment by mdhsl** [comment]
After making the change you suggested, it works! 
I have changed this:
```
emcc  build/FFmpeg/ffmpeg.bc
```

by 
```
emcc  build/FFmpeg/libavutil/libavutil.a \
    build/FFmpeg/libswscale/libswscale.a \
    build/FFmpeg/libavcodec/libavcodec.a \
    build/FFmpeg/libavfilter/libavfilter.a \
    build/FFmpeg/libavformat/libavformat.a \
```

Thanks a lot for the help!  and for the amazing work you are doing on this project, keep going!
I can also close this issue
