### ISSUE TITLE
Allow ES6 in emscripten output

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#11984]
We have a lot JavaScript code that emscripten generates and currently we limit all of it ES5 in order to maximize the portability of the output code.

However, given that non-ES5 runtime as rare (citation needed?), and that there are tools such as babel for converting ES6 to ES5 it seems like the wrong tradeoff to ask all emscripten JavaScript code to avoid modern features for this reason.

I recently ran across this in #11979 where the use of an ES6 feature would save code size and (I think) performance for the vast majority of our users.  

Also see #11858 

I propose that we remove this restriction and allow all ES6 features in emscripten output.  The remained question is now we support user who need ES5 output.  Do we:

A. Do nothing.  Assume that our users who want to target older engine are well versed in running babel themselves and put the burden on them.
B. Add a compatibility option `-s MIN_ES_VERSION=5`?   Or just `-s ES5`?    This would most likely mean taking an internal dependency on babel and running it as part of the post-link process.

We could also do a hybrid approach where we poll our users and ask how many would want option B?  Or at least we cpi;d delay the implementation of option B until we know we there a non-zero number of such users?

Please excuse me if this is a duplicate issue.  I'm fairly sure I've seen similar a one but I couldn't find it in a search for ES6 or ES5.

**Comment by curiousdannii** [comment]
ES5 is pretty much only needed for IE now. Probably that means mostly only for enterprise intranet type situations? I'd support using ES6+ features in output and saying that anyone who needs it to be ES5 can transpile it themselves.

**Comment by kripken** [comment]
Here is caniuse: https://caniuse.com/#feat=es6

Looks like e.g. Edge 14 lacks full support, not sure when it was released though, wikipedia page is incomplete. Firefox and Chrome seem fine (2017 / 2016). For Safari we should check iOS too.

@brion I believe you support older versions - thoughts?

**Comment by curiousdannii** [comment]
There's also https://kangax.github.io/compat-table/es6/

Edge 14 was released Aug 2016 and has only 0.02% browser share.

iOS seems to have close to full support since version 11.

**Comment by jvail** [comment]
Just an observation from someone trying to decide which build flags to use (only slightly off-topic):
It is bit confusing that with EXPORT_ES6=1 em emits code with require(...) and __dirname in node which makes it effectively unusable as node module in node 14.

**Comment by curiousdannii** [comment]
@jvail  You can subscribe to #11792 to get notified when that eventually gets fixed.

**Comment by sbc100** [comment]
> Here is caniuse: https://caniuse.com/#feat=es6
> 
> Looks like e.g. Edge 14 lacks full support, not sure when it was released though, wikipedia page is incomplete. Firefox and Chrome seem fine (2017 / 2016). For Safari we should check iOS too.

Our min Edge version is 44.. which has full support according to that site.  So I can't see any MIN_XXX_VERSIONS in our settings that don't already default to a version that fully supports ES6.

> 
> @brion I believe you support older versions - thoughts?

**Comment by sbc100** [comment]
bump!

**Comment by curiousdannii** [comment]
What still needs to be done? EM_ASYNC_JS already outputs async functions and arrow functions.

**Comment by sbc100** [comment]
The next steps as I see them:

1. Verify that the current default minimum set of browser targets support ES6
2. If (1) is false then push to up the defaults.
3. Write some code that can go from (set_of_browser_versions -> ES version)
4. Force transplantation via closure if the developer setting don't allow for ES6
5. Start writing ES6 with impunity!

**Comment by curiousdannii** [comment]
> Or does `EM_ASYNC_JS` itself output an arrow function?

It does! Maybe the tests are marked as uses_es6?

TBH, including a ES5 transpiler in Emscripten/Emsdk seems like a poor effort to benefit exchange. People can easily run the output through Babel themselves.

(Also, ES6 itself is now quite limiting. Async functions are ES2017, and with any future changes to the Environments system I'd say we should make full use of them. Not that we should be immediately jumping to ES2022 either. But some things will be worth bumping the requirements.)

**Comment by sbc100** [comment]
I don't think we need to add anything new since already ship (and use) the closure compiler which I believe can transpile down to ES5.   All we would be doing is enabling closure by default for those who want older browser support.

**Comment by sbc100** [comment]
We could potentially bump the default browser versions to something higher than ES6 possibly.    There is some value to having the defaults set to something that is widely available, but with this mechanism in place we could go higher. 

I think the question we would ask is, what percentage of developers would then need opt into targeting non-default (older) browsers?  If the number is very small I think there is good argument for bumping higher.

**Comment by juj** [comment]
I vote against using Babel, but instead just rely on our own `#ifdefs` and `{{{ }}}` macros to target ES5 vs ES6 syntax. That way they can automatically hook into the `TARGET_XXX_VERSION` defines in a fine grained manner, and we won't have to treat it as a "does browser X support all of ES6 or not?" problem.

**Comment by sbc100** [comment]
I'm not suggesting we use Babel (at least that isn't the current plan).  I'm suggesting using closure, which we already have available.

Why *not* force closure it in these (hopefully rare) cases?    The idea is that we would not up the min feature set until the need for closure is rare, so it should only effect a small number of users.

For very new features that are more recent than the default version then I agree we can continue to use `#if` conditions. 

I'm suggesting a new baseline of features that are acceptable throughout the codebase *without* conditionals.  These features ( (e.g on every array-iterating loop and on ever variable declaration with `let` or arrow functions for every lambda) are very common and widespread and so wrapping all of them in conditional (and including the fallback versions!) seems impractical at best.

**Comment by sbc100** [comment]
Speaking of closure, we already have the issue that it requires an ES version when we run it, and we have current bug/issue where we don't really know what to pass here and so we pass `--language_in ECMASCRIPT_2020 --language_out NO_TRANSPILE`: https://github.com/emscripten-core/emscripten/issues/12628

https://github.com/emscripten-core/emscripten/blob/4e615780a01ca6d551098402ee91347dbb682c40/tools/building.py#L780-L784

To fix this issue we really need to know the correct language version to pass as `--language_out`.  So having a function to calculate the current language version is needed here regardless.

**Comment by bkotsopoulossc** [comment]
> I vote against using Babel, but instead just rely on our own `#ifdefs` and `{{{ }}}` macros to target ES5 vs ES6 syntax. That way they can automatically hook into the `TARGET_XXX_VERSION` defines in a fine grained manner, and we won't have to treat it as a "does browser X support all of ES6 or not?" problem.

Tools like babel do offer ways to very specifically say what versions of each browser you want to target, and they deal with understanding (a) what features are you using in your code, (b) determining if each of those features are supported for each of those browsers, and (b) polyfilling them or transpiling them out. https://github.com/browserslist/browserslist is a common tool used in babel projects. You'd get the same level of granularity that you get with these [fields](https://github.com/emscripten-core/emscripten/blob/main/src/settings.js#L1676-L1706), but without needing to hand maintain the rules at the JS level.

Do we know how often emscripten is used with closure vs without, in the ecosystem?

Not saying we should ship babel with emscripten/emsdk, but maybe just having instructions on how to setup projects to run emscripten-generated JS through it. I imagine a lot of projects are already doing this. It seems there is a lot of effort put into maintaining browser compatibility in the emscripten generated JS, when a lot of this effort can be handled automatically by existing industry standard build tools

**Comment by sbc100** [comment]
Folks can already use babel as a post-processing as far as I know, right?

But I don't think we want to depend on that.   Its an option, but its not required.   Users who want to use babel to get support for older browser can do that.. without informing emscripten.  

 For users who want emscripten to produce ES5 output directly from emscripten I think using closure seems like a reasonable solution and is simple for us to implement.

**Comment by juj** [comment]
I would be curious to know how big the compile time and code size impact is when transpiling? Does Closure introduce a lot of scaffolding or other runtime to implement transpiling? Or is the transpiling result "tight" as if an optimal human had written the older version of the code?

Also I think we should probably document somewhere easy to find what the mininum browser requirements are that will not cause transpiling to occur?

Do you know what is the state of destructuring assignments and the spread syntax? Can Closure manage transpiling those?

**Comment by juj** [comment]
Oh, and looks like awesome work btw! (though I'll reserve the right to change my mind if Closure turns out to be a headache like it has proven out to be in the past... :)

**Comment by sbc100** [comment]
Yes, I will document that... also I should add a ChangeLog entry.

I will take a look at how each feature get polyfiled.   Remember that if folks don't like the way closure polyfils they still have the option of running the code through something different such as babel..  and it seems likely the folks targeting older browser are likely already doing transpilation as part of their deployment. 

I would hope that even if the polyfils result in a slight regression for those targetting legacy browsers we should still consider moving forward with this feature (unless the overhead is very significant, which seem unlikely).

**Comment by sbc100** [comment]
We are currently blocked form using all ES6 features to https://github.com/google/closure-compiler/issues/2007.

One possible way forward, as suggested in https://github.com/google/closure-compiler/issues/1138 is to force SIMPLE_OPTIMIZATIONS, even in debug builds, when transpilation is triggered.

@RReverser @kripken WDYT?  I think that seems fairly reasonable.  Hopefully most folks aren't doing too much debugging in older browsers.

**Comment by RReverser** [comment]
Maybe, but not a huge fan...

Also cross-pasting from the chat:

Btw it might be interesting to look into something like [swc](https://swc.rs/) for transpilation. It's a Babel alternative built in Rust & available as Wasm-based package.

Should be much faster than using Closure compiler just for transpilation, although at the cost of extra dependency. It also has Babel/Buble inspired loose mode which should output smaller ES5 code for common usages as well, for example:

![image](https://github.com/emscripten-core/emscripten/assets/557590/9a03fb5f-3f95-4afd-ad7e-fa973d83bb2d)

vs

![image](https://github.com/emscripten-core/emscripten/assets/557590/84db6458-b986-4f75-9b5d-5f7e4f291a87)

IMO the smaller output produced faster is worth it, but I know Emscripten was historically trying to avoid adding new dependencies.

**Comment by sbc100** [comment]
That looks like a great option actually.  Sounds like this won't have the bable downside of blowing up the number of dependencies in our node modules.

Having said that I think we could do these in either order.. i.e. we could switch to swc if/when folks complain about the SIMPLE_OPTIMIZATIONS approach?

**Comment by RReverser** [comment]
> i.e. we could switch to swc if/when folks complain about the SIMPLE_OPTIMIZATIONS approach?

I guess you could yeah, if going with basic optimisations is not a deal breaker.

**Comment by RReverser** [comment]
> Sounds like this won't have the bable downside of blowing up the number of dependencies in our node modules.

Yup, looks `@swc/core` has only 2 dependencies, both are basically empty (one is TS types and another is completely empty, just used for counting npm downloads across various packages that use it 😅).

**Comment by RReverser** [comment]
> Hopefully most folks aren't doing too much debugging in older browsers.

Thinking about it more, this seems like a sensible assumption for a quick solution. I'd say go for it.

**Comment by kripken** [comment]
> One possible way forward, as suggested in https://github.com/google/closure-compiler/issues/1138 is to force SIMPLE_OPTIMIZATIONS, even in debug builds, when transpilation is triggered.

To make sure I follow: Does this mean to do simple optimizations instead of no optimizations, or simple optimizations instead of advanced optimizations? (the former makes more sense given "even in debug builds", but the latter makes more sense to me otherwise, so I'm confused)

**Comment by sbc100** [comment]
Yes, it means that user who want to transpile will be forced to also get at least SIMPLE_OPTIMIZATIONS

**Comment by sbc100** [comment]
So SIMPLE_OPTIMIZATIONS instead of none.

**Comment by kripken** [comment]
I see, thanks. That is kind of weird, but otoh transpiling does modify the source code substantially anyhow, so I doubt it would make debugging harder. And usually for debugging people can run in a modern browser and avoid transpiling. So this sounds like a reasonable workaround to me as well.

To be sure I follow, though, this would have no effect in a default build, since by default we don't transpile?

**Comment by RReverser** [comment]
> To be sure I follow, though, this would have no effect in a default build, since by default we don't transpile?

That's correct.

Semi-related question though: I also saw various places in the codebase that could benefit from nullish coalescing operator (`A && A.B && A.B.C` - >`A?.B?.C`).

It's supported in Chrome 80+, Firefox 72+, Safari 13.1+ and Node.js 14+.

Our min versions defaults haven't changed in a long time and are currently set to Chrome 75+, Firefox 68+ and the others are higher already.

Given that Chrome & Firefox are evergreen and it's been a while, I hope it's not a deal-breaker to bump those versions as well so that we could benefit from this operator w/o worrying about transpiling?

**Comment by curiousdannii** [comment]
https://github.com/privatenumber/minification-benchmarks

From these benchmarks, swc is always one of the smallest, and quite fast. But I don't think it would be comparing against GCC's property mangler, but that was always an excessive option IMO. (It would be better if that was supported at the language level rather than hinting it by whether properties are quoted in the right way.)

**Comment by kripken** [comment]
> Our min versions defaults haven't changed in a long time and are currently set to Chrome 75+, Firefox 68+ and the others are higher already. Given that Chrome & Firefox are evergreen and it's been a while, I hope it's not a deal-breaker to bump those versions as well so that we could benefit from this operator w/o worrying about transpiling?

Yes, that sgtm. Looks like we updated Firefox to 68 in April, and Chrome even earlier, so a few versions higher should be fine. Even Firefox ESR is 115 (recently updated it seems) so that seems ok.

**Comment by RReverser** [comment]
Hm yeah Chrome is very old. I'll bump just a few versions more to include nullish assignment too then (Chrome 85+, Firefox 79+, others already covered).

**Comment by tomayac** [comment]
For Googlers on this Issue thread, this [document](https://docs.google.com/document/d/1U6iJhWNUDvdhJEJoE0k4DjN0uEer9Fl4la1WTemewEM/edit?usp=sharing) (sorry, it's not accessible to external people) might be interesting in the context of this discussion.
