### ISSUE TITLE
linking SIDE_MODULEs with exports does not work

### ISSUE THREAD

**Issue by cnlohr** [emscripten-core/emscripten#12005]
When linking in side modules, the end module does not contain the exports from the input modules.

cfile.c
```
int add2( int a, int b )
{
	return a+b;
}
```

```
emcc -o cfile.wasm cfile.c -s EXPORT_ALL=1 -s SIDE_MODULE=1
```

cfile.wasm contains the symbol correctly.

main.c
```
int main() {
}
```

Executing
```
~/git/emsdk/upstream/emscripten/emcc -o c-test.wasm cfile.wasm main.c -s LLD_REPORT_UNDEFINED -s EXPORT_ALL=1
```

Produces `c-test.wasm` however, this file is missing the `add2` export.

Any idea what's going on here?  Is there a cleaner way of linking together multiple wasm files using emscripten?

EDIT: If I manually specify `_add2` for the export list, the final step cannot find that symbol.

```
~/git/emsdk/upstream/emscripten/emcc -o c-test.wasm cfile.wasm watfile.wasm main.c -s LLD_REPORT_UNDEFINED -s EXPORTED_FUNCTIONS='["_add2","_main"]'
wasm-ld: error: symbol exported via --export not found: add2
emcc: error: '/home/cnlohr/git/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_it61533c/c-test.wasm cfile.wasm -L/home/cnlohr/git/emsdk/upstream/emscripten/system/local/lib watfile.wasm -L/home/cnlohr/git/emsdk/upstream/emscripten/system/lib /tmp/emscripten_temp_it61533c/main_0.o -L/home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/crt1.o /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libc.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libcompiler_rt.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libc++-noexcept.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libc++abi-noexcept.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libdlmalloc.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libpthread_stub.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libstandalonewasm.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libc_rt_wasm.a /home/cnlohr/git/emsdk/upstream/emscripten/cache/wasm/libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpi0cxwh8y.undefined --strip-debug --export add2 --export stackSave --export stackRestore --export stackAlloc --export __data_end --export fflush --export __errno_location -z stack-size=5242880 --initial-memory=16777216 --max-memory=16777216 --global-base=1024' failed (1)
Makefile:39: recipe for target 'c-test.wasm' failed
```

**Comment by cnlohr** [comment]
This was mostly in an effort to see how I could mix wasm and C, i.e. compile some wasm files externally (relocatable modules) and link them in.  I just figured a good test would be with C, but that makes sense.  I was unaware you could link .a files together, that's very interesting.  Do you have any invocation examples?  I'm not sure what that would look like command-wise  I've tried going through .bc files but they also have similar issues to what I was running into.

The bigger point is the way in which the Asyncify front end does things is paradigmatically difficult to reconcile with what I'm seeking to do... I was hoping to kinda mix-and-match the backend with some custom code on the front end.  I figured a good way to do that would be mix in the wasm portion of this: https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html

(Also this is parallel to #12006 )

**Comment by sbc100** [comment]
`.a` files are just archives of object files (`.o) files.   This is no different to on a native (gcc/clang) build system.

You create object files by compiling C/C++ source:

`emcc -c foo.c -o foo.o`

You then combine your object files in libraries using `emar`:

`emar rcs libfoo.a foo1.o foo2.o foo3.o`

Then when you link your wasm file you can include your library on the command line:

`emcc main.o libfoo.a -o out.wasm`

I would ignore anything you read about creating `.bc` files. That was something that we did a lot back in the fastcomp days.

**Comment by cnlohr** [comment]
I think I'm still missing something...

cfile.c:
```
#include <emscripten.h>
int add2( int a, int b )
{
	return a+b;
}
```

main.c
```
#include <emscripten.h>
#include <stdio.h>

int add2( int a, int b );

int main()
{
	printf( "%d\n", add2( 5, 6 ) );
}
```


```
emcc -o cfile.o cfile.c -s EXPORTED_FUNCTIONS='["_add2"]'
emar rcs cfile.a cfile.o
emcc -o c-test.wasm cfile.a main.c -s LLD_REPORT_UNDEFINED -s EXPORTED_FUNCTIONS='["_add2","_main"]'
emcc: error: undefined exported function: "_main" [-Wundefined] [-Werror]
```

**Comment by curiousdannii** [comment]
I'd recommend using Make or CMake. Here's roughly how you'd do it in CMake:

```
add_library(c-lib STATIC)
target_sources(c-lib PRIVATE cfile.c)

add_executable(c-test)
target_link_libraries(c-test c-lib)
target_sources(c-test PRIVATE main.c)
target_link_options(c-test PRIVATE
    -sEXPORTED_FUNCTIONS=['_add2','_main']
    -sLLD_REPORT_UNDEFINED
)
```

**Comment by cnlohr** [comment]
My build system is make-based, can you just run that and copy-paste the output?  It's difficult to see what's actually going on under the hood with that syntax?

**Comment by cnlohr** [comment]
Also just clicked the link.  Woah.  Ok!  I think I can work from here by doing the cmake thing myself and `make -n`'ing.

**Comment by cnlohr** [comment]
OK!!!! I found the actual issue here, but still do not know how to resolve it. You are outputting a `.js` file, whereas I am outputting a straight `.wasm` file.  My infrastructure is set up only to ingest the `.wasm` file from emscripten, and this does not work with a `.wasm` output file.  Does anyone have any idea how you would make this work with the `.wasm` output instead of the `.js` output?

**Comment by curiousdannii** [comment]
There is a STANDALONE_WASM setting, but Emscripten isn't really designed around it, so there are lots of limitations. You might be better off building to .wasm from LLVM directly, or using Rust or something else.

**Comment by cnlohr** [comment]
Even in that arena there's not much help for how to link around... Though, I was really hoping to continue to use emscripten because of it's broad support and really nice features.

But maybe this isn't feasible.

**Comment by sbc100** [comment]
You don't need to use `STANDALONE_WASM` to output just a wasm file.  You can just set the output filename to something ending in `.wasm`.  e.g. `emcc -o out.wasm main.c`.  Or you can using `--oformat=wasm` to force the output format regardless of extension.
