### ISSUE TITLE
SIMD: wasm_v16x8_shuffle(...) reproducibly produces garbage when compiled with -O1, -O2 or -O3, is fine with -O0

### ISSUE THREAD

**Issue by sbalko** [emscripten-core/emscripten#12017]
I have come across an issue when producing a SIMD-enabled build and using certain combinations of `wasm_u16x8_load_8x8` (load 8 bytes from memory and upcast to a `__u16x8` vector) followed by a shuffle of the resulting `__u16x8` vector, selecting the second 4 elements of the vector. 

A test program is given here: https://gist.github.com/sbalko/dc7d070de5acb2cc22affac386f9af27

In order to reproduce, compile with the program with the latest emsdk (2.0.1 at the time of reporting) like so:
```
emcc shuffle_bug.c -O3 -msimd128  -g -s INITIAL_MEMORY=1gb -s MAXIMUM_MEMORY=2gb -s ALLOW_MEMORY_GROWTH=1 -o bug.html
```

The serve the resulting files with a local webserver and use Chrome 84+ (with WebAssembly SIMD flag enabled) to run the program. The output will be this:
```
in-memory data at offset 0: {0, 1, 2, 3, 4, 5, 6, 7}
in-memory data at offset 64: {64, 65, 66, 67, 68, 69, 70, 71}
shuffled, with first 4 elements from both vectors: {0, 1, 2, 3, 64, 65, 66, 67}
shuffled, with first and last 4 elements from first, second vector: {0, 1, 2, 3, 0, 0, 0, 0}
```

The last line ("shuffled, with first and last 4 elements from first, second vector") produces a `__u16x8` vector with the last four elements set to `0`. They should be `68, 69, 70, 71`. 

Not compile the same program with `-O0` (no optimisations). This time, the output is correct:
```
in-memory data at offset 0: {0, 1, 2, 3, 4, 5, 6, 7}
in-memory data at offset 64: {64, 65, 66, 67, 68, 69, 70, 71}
shuffled, with first 4 elements from both vectors: {0, 1, 2, 3, 64, 65, 66, 67}
shuffled, with first and last 4 elements from first, second vector: {0, 1, 2, 3, 68, 69, 70, 71}
```
I am unsure if this is a problem with the emsdk toolchain, a bug in Chrome itself (or even a misunderstanding on my part).  The issue is reproducible on different CPUs (in case this matters), I've reproducibly tested it on an Core i7-8550U and a Threadripper 1950X.

**Comment by tlively** [comment]
Thanks for the report! After some investigation, this appears to be a V8 bug. I reported it upstream as https://bugs.chromium.org/p/v8/issues/detail?id=10824.

**Comment by ngzhian** [comment]
Fixed upstream, closing.
