### ISSUE TITLE
Possible change in exception behaviour after #11518?

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#12025]
I create LLVM bitcode for the CoreRT compiler.  Using the same bitcode and emscripten commits before and after https://github.com/emscripten-core/emscripten/pull/11518 results in different behaviour, moreover after #11518 I don't seem to have the c++ exception in my LLVM landing pads anymore.  I see that the exception is wrapped in some meta data, do I need to change something to accomodate that in either cpp or in LLVM bitcode landing pads?

I throw exceptions from cpp like 
```
throw ManagedExceptionWrapper(pEx);
```
where `ManagedExceptionWrapper` is wrapper around the managed .Net exception:
```
class ManagedExceptionWrapper : exception
{
public:
    ManagedExceptionWrapper(void* pManagedException)
    {
        m_pManagedException = pManagedException;
    }

public:
    void* m_pManagedException;
};
```

For completeness the landing pad looks like
```
LandingPad1:                                      ; preds = %TryF, %Try819, %Try814, %Try8, %Block1
  %5 = landingpad { i8*, i32 }
          cleanup
          catch i8* null
  %ex = extractvalue { i8*, i32 } %5, 0
  %6 = bitcast i8* %ex to i32*
  %offset = getelementptr i32, i32* %6, i32 1
  %managedEx = load i32, i32* %offset
```
where `managedEx` is before this commit, the `pManagedException`.

**Comment by sbc100** [comment]
@vagran @kripken can you take a look?

**Comment by kripken** [comment]
There should not have been any noticeable change to that PR, but maybe @vagran has an idea from those code samples?

Getting a full standalone C++ testcase might also help here.

**Comment by yowl** [comment]
What I notice that now that I'm not handling the exception (and just resume-ing), that in js it reports
```
exception thrown: 7190512
```
Which is curious as this is 16 bytes below the exception received in the LLVM landing pad, 16 bytes I think being the size of the metadata.

**Comment by yowl** [comment]
And perhaps even stranger if I change the LLVM from
```
            var exPtr = landingPadBuilder.BuildExtractValue(pad, 0, "ex");
```
to
```
            var wrappedExPtr = landingPadBuilder.BuildExtractValue(pad, 0, "ex");
            var exPtr = landingPadBuilder.BuildGEP(wrappedExPtr, new LLVMValueRef[] { BuildConstInt32(-16) });
```
It fixes things for a while but after 20 or so exceptions it fails again as though the offset is not always constant

**Comment by yowl** [comment]
Another possibility is that perhaps I've been getting away with over simplistic EH .  In dotnet the exception handling is different to c++, so I handle it all through the LLVM landing pads and resumes, I don't have any calls to __cxa_free_exception/__cxa_begin_catch/__cxa_end_catch, could that be causing me problems?

**Comment by yowl** [comment]
Ok, I think I can close this, getting the exception from `__cxa_begin_catch` works which is what I should have been doing all along, just got away without it before somehow.
