### ISSUE TITLE
Undefined symbols from library.js

### ISSUE THREAD

**Issue by ansniko** [emscripten-core/emscripten#12029]
I'm getting linker errors during compilation, but aren't these functions automatically linked, since they're in `emscripten/src/library.js`?

error: undefined symbol: gai_strerror (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _gai_strerror may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: gethostbyname (referenced by top-level compiled C/C++ code)
warning: _gethostbyname may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: getprotobyname (referenced by top-level compiled C/C++ code)
warning: _getprotobyname may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors

**Comment by sbc100** [comment]
What `-s` flags are you passing?

It looks like `gai_strerror` in library.js is only compiled in if `PROXY_POSIX_SOCKETS == 0`?  Are you setting PROXY_POSIX_SOCKETS?

Any from looking at `system/lib/websocket/websocket_to_posix_socket.cpp` is looks like maybe `gai_strerror` is missing from this mode?

**Comment by ansniko** [comment]
`-s` flags are: 

`-s USE_BOOST_HEADERS=1 -s PROXY_POSIX_SOCKETS=1 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -s USE_ZLIB=2`

Is there another lib I could link in, or would I need to implement gai_strerror, etc?

**Comment by sbc100** [comment]
Looks like you would need to implement `gai_strerror` or find a way to avoid using it.   See `websocket_to_posix_socket.cpp`

**Comment by TheMaverickProgrammer** [comment]
I'm having this same exact issue. Is this the function we must implement? Seems pretty easy to me:

https://pubs.opengroup.org/onlinepubs/007904875/functions/gai_strerror.html

**Comment by sbc100** [comment]
It might be easy to add if one of you want to try to add it to `system/lib/websocket/websocket_to_posix_socket.cpp`.

**Comment by TheMaverickProgrammer** [comment]
I'm not an expert with emscripten, do I just write the implementation of the function in `websocket_to_posix_socket.cpp` and everything it linked correctly or are there more steps involved?

**Comment by sbc100** [comment]
That should do it.   You might want to use `emcc --clear-cache` in order to force all the libraries to get re-built (or just delete the one library that websocket_to_posix_socket.cpp is part of) each time to modify the file.

**Comment by sbc100** [comment]
The simpler approach might just be to remove the calls to `gai_strerror` from your application as a temporary work around.

**Comment by Nanoteck137** [comment]
Hello, I was thinking that this might be a good first issue for me. 
So I was wondering if I can help with this?

**Comment by sbc100** [comment]
Sure!  In general feel free to help out on any issue that nobody has claimed ownership.  There should be plenty :)

**Comment by Nanoteck137** [comment]
Oh ok, thanks for the tip :)
