### ISSUE TITLE
Why are parameters via POST and emscripten_fetch() not passed to server using c_str()?

### ISSUE THREAD

**Issue by PowerNow** [emscripten-core/emscripten#12036]
Hi, I want to pass parameters per POST and emscripten_fetch() to my server, but it doesn't work with string type. The $_POST['para1'] stays empty.

```
emscripten_fetch_attr_t attr;
emscripten_fetch_attr_init(&attr);
strcpy(attr.requestMethod, "POST");
attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
attr.onsuccess = &Ntw::statFinished;
attr.onerror = &Ntw::statFailed;

const char * headers[] = {"Content-Type", "application/x-www-form-urlencoded", 0};
attr.requestHeaders = headers;

string param = "para1=test1";
1. attr.requestData = &param[]; => not works
2. attr.requestData = param.c_str(); => not works

const char *param = "para1=test1";
3. attr.requestData = param; => works

4. attr.requestData = "para1=test1"; => works

attr.requestDataSize = strlen(attr.requestData);

emscripten_fetch(&attr, "http://domain.com/test.php");
```
I'm using emscripten 1.39.13.

**Comment by tmadden** [comment]
I'm seeing similar problems on 1.40.1 and 2.0.0. It looks like the request body is actually being corrupted somehow. Chrome reports that the request body it's sending looks like this:

`&Q&Qusername":"sdafasdf"}`

So the real data shows through, but some stuff at the beginning got corrupted. I confirmed that the string remains valid until after emscripten_fetch returns. I also tried copying the string into a buffer. It seems that if the buffer is allocated on the stack, then it fixes the problem, but if the buffer is on the heap, the problem remains. So maybe it's just a matter of the fetch code not being able to access the heap properly. Is this a known limitation?

**Comment by tmadden** [comment]
OK, I read the actual headers for the fetch interface, and recent versions actually require the request body data to persist for the duration of the operation, so that would explain this behavior. Ensuring that my strings persist long enough allows me to use `c_str()` to pass the data. It's funny that stack-allocated data seems to consistently work for me, but as far as the original issue goes, I think the observed behavior is consistent with what the headers say, so this could probably be closed.

**Comment by PowerNow** [comment]
Fallback!
```
string post = "teststring";
char postChar[post.size() + 1];
std::copy(post.begin(), post.end(), postChar);
postChar[post.size()] = '\0';
...
attr.requestData = postChar; 
```

**Comment by PowerNow** [comment]
So you mean that the param.c_str() must exists until attr.onsuccess is called?

**Comment by tmadden** [comment]
Yeah, see here:

https://github.com/emscripten-core/emscripten/blob/master/system/include/emscripten/fetch.h#L108-L111

Your workaround puts it on the stack, which also worked for me, but the comment explicitly says not to do that. There might be some coincidental reason why that works (for now, or in some cases), but the correct thing to do is to store it on the heap for the duration of the request and then free it when `onsuccess` or `onfailure` is called. You can use `userData` to help with that.

**Comment by PowerNow** [comment]
I see, thanks...
