### ISSUE TITLE
What are the changes of LLVM11?

### ISSUE THREAD

**Issue by popomen** [emscripten-core/emscripten#12045]
https://emscripten.org/docs/building_from_source/index.html
I refer to this article to deploy emsscripten through source code, but I find that only LLVM11 is available.
If I use LLVM10, the following message is displayed:
```
em++: warning: LLVM version apperars incorrect(seeing "10.0", expected "11.0")
```
Many undefined symbol errors occur during the connection.

```
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(opendir.o): undefined symbol: __wasi_fd_close 
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(readdir.o): undefined symbol: __syscall220    
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(opendir.o): undefined symbol: __wasi_fd_close 
wasm-ld: error: /root/emscripten-1.39.18/cache/wasm/libc-mt.a(fcntl.o): undefined symbol: __syscall221      
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)                
```

**Comment by sbc100** [comment]
The instructions on `https://emscripten.org/docs/building_from_source/index.html` say to build llvm from source you need to checkout the code from https://github.com/llvm/llvm-project and build it.

If you do that you will end up with llvm 12 today.

Are you trying to use emscripten-1.39.18 for some particular reason?   That version is fairly old now.  If you do want to use that version you will need to build llvm version 11, not the latest version.  

If you want to save time i recommend just using the `emsdk` to install emscripten which ensures you get a the correct pre-built version of llvm.
