### ISSUE TITLE
Calling glGenQueries throws exception. 

### ISSUE THREAD

**Issue by rjappy** [emscripten-core/emscripten#12072]
Trying out emscripten for first time. 

App is throwing exception when glGenQueries is called.

The pointer to function 'glGenQueries' was retreieved by using SDL_GL_GetProcAddress

exception thrown: TypeError: GLctx.disjointTimerQueryExt is null,_emscripten_glGenQueriesEXT@http://localhost:8000/engine.js:11002:21
@http://localhost:8000/engine.wasm:wasm-function[218]:0x0
@http://localhost:8000/engine.wasm:wasm-function[31036]:0x2455c3
@http://localhost:8000/engine.wasm:wasm-function[31034]:0x24558a
@http://localhost:8000/engine.wasm:wasm-function[31093]:0x246959
@http://localhost:8000/engine.wasm:wasm-function[31092]:0x246759
@http://localhost:8000/engine.wasm:wasm-function[32386]:0x25f3cd
@http://localhost:8000/engine.wasm:wasm-function[30210]:0x2356fd
@http://localhost:8000/engine.wasm:wasm-function[30206]:0x23509c
@http://localhost:8000/engine.wasm:wasm-function[30203]:0x235012
Module._main@http://localhost:8000/engine.js:14087:60
callMain@http://localhost:8000/engine.js:15015:28
doRun@http://localhost:8000/engine.js:15076:31
run/<@http://localhost:8000/engine.js:15087:7

**Comment by rjappy** [comment]
Additional info , tried running on chrome

-------------------------------

Browser : chrome Version 80.0.3987.149 (Official Build) (64-bit)

-------------------------------

version   : OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))
vendor    : WebKit
renderer  : WebKit WebGL
GLSL version     : OpenGL ES GLSL ES 3.00 (WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium))
extensions       : EXT_color_buffer_float EXT_disjoint_timer_query_webgl2 EXT_float_blend EXT_texture_filter_anisotropic
OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context GL_EXT_color_buffer_float
GL_EXT_disjoint_timer_query_webgl2 GL_EXT_float_blend GL_EXT_texture_filter_anisotropic
GL_OES_texture_float_linear GL_WEBGL_compressed_texture_s3tc GL_WEBGL_compressed_texture_s3tc_srgb
GL_WEBGL_debug_renderer_info GL_WEBGL_debug_shaders GL_WEBGL_lose_context

-------------------------------

engine.html:1 exception thrown: TypeError: Cannot read property 'createQueryEXT' of null,TypeError: Cannot read property 'createQueryEXT' of null
    at _emscripten_glGenQueriesEXT (http://localhost:8000/engine.js:11002:48)
    at wasm-function[31036]:0x2455e4
    at wasm-function[31034]:0x24558c
    at wasm-function[31095]:0x246c13
    at wasm-function[31094]:0x246a13
    at wasm-function[32388]:0x25f687
    at wasm-function[30210]:0x2356ff
    at wasm-function[30206]:0x23509e
    at wasm-function[30203]:0x235014
    
-------------------------------

**Comment by kripken** [comment]
That might mean the `EXT_disjoint_timer_query` extension is not supported on those browsers. Perhaps @kainino0x knows the status?

**Comment by kainino0x** [comment]
That's likely. This extension is not guaranteed to be available, and it is disabled on browsers without site isolation due to Spectre (as it can provide a high-precision timer to the page). For example, see https://crbug.com/870491 tracking re-enabling it on Chrome on Android.

**Comment by rjappy** [comment]
glGenQueries is also used for generating IDs for occlusion queries.

Even without EXT_disjoint_timer_query , that feature should still be available .

I will check again with a small test case.

**Comment by kainino0x** [comment]
Right, true. Are you creating a WebGL 2 context?

Please provide a test case once you've found one; that'll make this much easier to investigate. Thanks!

**Comment by rjappy** [comment]
Test  :
```

#include <iostream>
#include <stdio.h>
#include <SDL2/SDL.h>
#include <GL/gl.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

SDL_Window*					mWindow = 0;
SDL_GLContext				mContext = 0;

void one_iter(void) {
	static int frames = 0;
	frames++;
	if (frames == 120) {
		emscripten_cancel_main_loop();
		SDL_Quit();
		return;
	}
	
	float animate = frames/120.;
	
	glClearColor(1. - animate,animate,1. - animate,1);
	glClear(GL_COLOR_BUFFER_BIT);
	
	SDL_GL_SwapWindow(mWindow);
	
}

extern "C" int main(int argc, char** argv) {
	std::cout << "Starting!\n";
	
	// init SDL
	if (SDL_Init(SDL_INIT_VIDEO|SDL_INIT_NOPARACHUTE) != 0) {
		std::cout << "SDL_Init returned error: " << SDL_GetError() << "\n";
		return 0;
	}
	
	mWindow = SDL_CreateWindow("title",
							SDL_WINDOWPOS_UNDEFINED,SDL_WINDOWPOS_UNDEFINED,
							640,480,
							SDL_WINDOW_OPENGL);
	if (!mWindow) {
		std::cout << "SDL_CreateWindow() failed: '" << SDL_GetError() << "'" << "\n";
		return 0;
	}
	
	// set opengl attributes
	SDL_GL_ResetAttributes();
	SDL_GL_SetAttribute(SDL_GL_RED_SIZE			,8);
	SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE		,8);
	SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE		,8);
	SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE		,8);
	
	// opengl version
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION,3);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION,0);
	
	mContext = SDL_GL_CreateContext(mWindow);
	if (!mContext) {
		std::cout << "SDL_GL_CreateContext() failed: '" << SDL_GetError() << "'" << "\n";
		return 0;
	}

	int	attr[15] = {-1};

	SDL_GL_GetAttribute(SDL_GL_RED_SIZE			,&attr[0]);
	SDL_GL_GetAttribute(SDL_GL_GREEN_SIZE		,&attr[1]);
	SDL_GL_GetAttribute(SDL_GL_BLUE_SIZE		,&attr[2]);
	SDL_GL_GetAttribute(SDL_GL_ALPHA_SIZE		,&attr[3]);
	SDL_GL_GetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION,	&attr[11]);
	SDL_GL_GetAttribute(SDL_GL_CONTEXT_MINOR_VERSION,	&attr[12]);

	{ std::cout
				<<	"RED_SIZE                        : " << 8 << " Got " << attr[0] << "\n"
				<<	"GREEN_SIZE                      : " << 8 << " Got " << attr[1] << "\n"
				<<	"BLUE_SIZE                       : " << 8 << " Got " << attr[2] << "\n"
				<<	"ALPHA_SIZE                      : " << 8 << " Got " << attr[3] << "\n"
				<<	"CONTEXT_MAJOR_VERSION           : " << attr[11] << "\n"
				<<	"CONTEXT_MINOR_VERSION           : " << attr[12] << "\n"
		;
	}
	
	std::cout << "SDL_GL_GetProcAddress(\"glGenQueries\")\n";
	PFNGLGENQUERIESPROC glGenQueries = (PFNGLGENQUERIESPROC)SDL_GL_GetProcAddress("glGenQueries");
	
	GLuint query_objects;
	std::cout << "calling glGenQueries\n";
	glGenQueries(1,&query_objects);
	std::cout << "got query object\n";
	
	emscripten_set_main_loop(one_iter,0,false);
	
	return 0;
}


```
compiled with "emcc -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s USE_SDL=2 test.cpp -o ./index.html"

fails when calling 'glGenQueries'

exception thrown: TypeError: GLctx.disjointTimerQueryExt is null,_emscripten_glGenQueriesEXT@http://192.168.0.102/index.js:6922:21
@http://192.168.0.102/index.wasm:wasm-function[78]:0x0
@http://192.168.0.102/index.wasm:wasm-function[356]:0x4e10
createExportWrapper/<@http://192.168.0.102/index.js:1709:22
callMain@http://192.168.0.102/index.js:10100:28
doRun@http://192.168.0.102/index.js:10162:31
run/<@http://192.168.0.102/index.js:10173:7

em version:
emcc (Emscripten gcc/clang-like replacement) 1.39.19 (f45bea21f3a8f74a68ed4e3e3d7e290807ee2aff)

**Comment by kainino0x** [comment]
From inspecting the code I think I see the issue. In [library_webgl2](https://github.com/emscripten-core/emscripten/blob/master/src/library_webgl2.js#L171), glGenQueries maps to gl.genQuery, but I think glGenQueriesEXT falls back to [library_webgl](https://github.com/emscripten-core/emscripten/blob/master/src/library_webgl.js#L1842) which maps to EXT_disjoint_timer_query.genQueryEXT.

I think in library_webgl's glGenQueriesEXT there should be something along these lines:
```
  glGenQueriesEXT__deps: [
#if MAX_WEBGL_VERSION >= 2
    'glGenQueries',
#endif
  ],
  glGenQueriesEXT: function(n, ids) {
#if MAX_WEBGL_VERSION >= 2
    if (GL.currentContext.version >= 2) {
      glGenQueries(n, ids);
      return;
    }
#endif
    // current implementation
  },
```

though not sure if this exact code works (might need to call _glGenObject instead of calling out to library_webgl2?). @rjappy would you be willing to try this out and open a PR if it works?

**Comment by rjappy** [comment]
Looks like its an issue in browsers

both firefox and chrome advertise GL_EXT_disjoint_timer_query but is returning null in 
GLctx.getExtension("EXT_disjoint_timer_query");

in firefox 
setting webgl.enable-privileged-extensions = true  in about:config fixes it.

there should be a check in return GLctx.getExtension("EXT_disjoint_timer_query");
as its an extension and may not be available in any case.

**Comment by kainino0x** [comment]
That's correct, the WebGL extension EXT_disjoint_timer_query is not available in WebGL 2. This is because the old EXT_disjoint_timer_query defined its own concept of queries, while in WebGL 2 it reuses the core query objects.

Since you're using WebGL 2 queries, you don't want to use EXT_disjoint_timer_query or EXT_disjoint_timer_query_webgl2. The point is to make sure that if glGenQueriesEXT is used on a WebGL 2 context, it does exactly the same thing as glGenQueries (instead of trying to use the queries from the disjoint timer query extension).

**Comment by kainino0x** [comment]
If you have cases where getSupportedExtensions() returns an extension that can't be enabled, or where EXT_disjoint_timer_query appears on a WebGL 2 context, please file browser bug(s).

**Comment by rjappy** [comment]
Sorry , still a bit confused.

For my firefox browser 80.0.1 (64-bit) , the following are extensions available in webgl2 context

  | EXT_color_buffer_float
  | EXT_float_blend
  | EXT_texture_compression_bptc
  | EXT_texture_compression_rgtc
  | EXT_texture_filter_anisotropic
  | OES_texture_float_linear
  | OVR_multiview2
  | WEBGL_compressed_texture_etc
  | WEBGL_compressed_texture_s3tc
  | WEBGL_compressed_texture_s3tc_srgb
  | WEBGL_debug_renderer_info
  | WEBGL_debug_shaders
  | WEBGL_lose_context

There is no EXT_disjoint_timer_query or EXT_disjoint_timer_query_webgl2 extension available.

If i run the test code i get following error

exception thrown: TypeError: GLctx.disjointTimerQueryExt is null,_emscripten_glGenQueriesEXT@http://192.168.0.102/index.js:6932:21
@http://192.168.0.102/index.wasm:wasm-function[79]:0x0
@http://192.168.0.102/index.wasm:wasm-function[355]:0x4ac3
createExportWrapper/<@http://192.168.0.102/index.js:1625:22
callMain@http://192.168.0.102/index.js:10282:28
doRun@http://192.168.0.102/index.js:10344:31
run/<@http://192.168.0.102/index.js:10355:7
setTimeout handler*run@http://192.168.0.102/index.js:10351:15
runCaller@http://192.168.0.102/index.js:10258:19
removeRunDependency@http://192.168.0.102/index.js:1543:7
receiveInstance@http://192.168.0.102/index.js:1688:24
receiveInstantiatedSource@http://192.168.0.102/index.js:1705:20
promise callback*instantiateAsync/<@http://192.168.0.102/index.js:1730:23
promise callback*instantiateAsync@http://192.168.0.102/index.js:1728:61
createWasm@http://192.168.0.102/index.js:1755:3
@http://192.168.0.102/index.js:10002:11

Digging through the code i think that glGenQueries is been diverted to glGenQueriesEXT which in turn calls glGenQueriesEXT in library_webgl.js which calls  'var query = GLctx.disjointTimerQueryExt['createQueryEXT']();' where disjointTimerQueryExt is null.

**Comment by rjappy** [comment]
Sorry , still confused.

On latest firefox version.

i am still getting typeerror. when calling glGenQueries.

The issue seems to be that the browser is by default disabling EXT_disjoint_timer_query and EXT_disjoint_timer_query_webgl2.

According to spec as i understand it , extensions need not be always available.

Digging through the code. i think that glGenQueries look name is been changed to glGenQueriesEXT which then goes to glGenQueriesEXT in library_webgl.js which calls 'var query = GLctx.disjointTimerQueryExt['createQueryEXT']();' where disjointTimerQueryExt is null .

Error Stack trace:

exception thrown: TypeError: GLctx.disjointTimerQueryExt is null,_emscripten_glGenQueriesEXT@http://192.168.0.102/index.js:6932:21
@http://192.168.0.102/index.wasm:wasm-function[79]:0x0
@http://192.168.0.102/index.wasm:wasm-function[355]:0x4ac3
createExportWrapper/<@http://192.168.0.102/index.js:1625:22
callMain@http://192.168.0.102/index.js:10282:28
doRun@http://192.168.0.102/index.js:10344:31
run/<@http://192.168.0.102/index.js:10355:7
setTimeout handler*run@http://192.168.0.102/index.js:10351:15
runCaller@http://192.168.0.102/index.js:10258:19
removeRunDependency@http://192.168.0.102/index.js:1543:7
receiveInstance@http://192.168.0.102/index.js:1688:24
receiveInstantiatedSource@http://192.168.0.102/index.js:1705:20
promise callback*instantiateAsync/<@http://192.168.0.102/index.js:1730:23
promise callback*instantiateAsync@http://192.168.0.102/index.js:1728:61
createWasm@http://192.168.0.102/index.js:1755:3
@http://192.168.0.102/index.js:10002:11
