### ISSUE TITLE
Why I'm getting an error after SDL_GLContext using any gl...() functions?

### ISSUE THREAD

**Issue by PowerNow** [emscripten-core/emscripten#12078]
Hi, I'm getting the folllowing error with emscripten 2.0.1 on some newer iOS and older Chrome, Edge browsers. On Mozilla it works perfectly.

```
SDL_Init(SDL_INIT_VIDEO);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);

m_window = SDL_CreateWindow("test", 0, 0, m_pCtrl->m_width, m_pCtrl->m_height, SDL_WINDOW_OPENGL|SDL_WINDOW_RESIZABLE);
SDL_GLContext context = SDL_GL_CreateContext(m_window);

glDepthFunc(GL_LEQUAL); // => error occurs here
```
**This error occurs no matter what gl...() function I use.**

```
emsc.js:1 Uncaught TypeError: Cannot read property 'depthFunc' of undefined
at _glDepthFunc (emsc.js:1)
at /plugin1/emsc.wasm:wasm-function[1715]:0x9883d
at /plugin1/emsc.wasm:wasm-function[2004]:0xa8831
at Ig (/plugin1/emsc.wasm:wasm-function[1198]:0x42fcd)
at Module._startModel (emsc.js:1)
at ccall (emsc.js:1)
at emsc.js:1
at onReady (plugin.js:1170)
at checkSegment (plugin.js:1317)
at FileReader.onLoaded (plugin.js:1256)
```
Has anyone an idea what I'm doing wrong here?

**Comment by rjappy** [comment]
Are you checking return value of  'SDL_GL_CreateContext(m_window)'

**Comment by PowerNow** [comment]
The result of SDL_GL_CreateContext(m_window) = NULL. So I changed SDL_GL_CONTEXT_MAJOR_VERSION = 2 and now the Context is valid. The OpenGl Version is 3.1, but WebGL 2 is based on OpenGL ES 3.0, which is based on OpenGL 3.3. Maybe that's the reason.  I'm wondering why this works on Firefox and not on Edge or Chrome? If I want to use WebGL with OpenGL ES 2 I always get an error that glReadBuffer(GL_COLOR_ATTACHMENT1) is unknown, although glReadBuffer() exists since OpenGL ES 2. Is there maybe a way to use SDL 2 with WebGL 1 and WebGL 2 for different browsers?

**Comment by rjappy** [comment]
Try linking using  'MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 '

Also set SDL_GL_CONTEXT_MAJOR_VERSION to 3 like before and check SDL_GetError() ,

**Comment by PowerNow** [comment]
Unfortunately no change, exactly the same error. SDL_GetError() of SDL_GL_CreateContext provides "error context Could not create EGL context (call to eglCreateContext failed, reporting an error of EGL_BAD_MATCH)".

**Comment by rjappy** [comment]
Maybe you don't have webgl 2 hardware support .

Goto "chrome://gpu/" in chrome.

That should show if webgl2 is supported.

If its unavailable updating graphics drivers may fix it.

**Comment by PowerNow** [comment]
Exactly, that confirmes my assumption, that min. opengl 3.3 must be available. But on firefox it works, although it supports only webgl 1 too? And all modern macOS or iOS do only support webgl 2 in "experimental mode", which does also not work. Is regarding emscripten no way to use somehow webgl 2 on apple?
