### ISSUE TITLE
Why emmake generate wasm file directly?Without LLVM bitcode?

### ISSUE THREAD

**Issue by visla-mengzhihao** [emscripten-core/emscripten#12086]
I want to build a wasm ffmpeg.And I use commands as follows.
`emconfigure   ./configure --cc="emcc" --enable-cross-compile --target-os=none --arch=x86_64 --cpu=generic \
    --disable-ffplay --disable-ffprobe --disable-asm --disable-doc --disable-devices --disable-pthreads --disable-w32threads --disable-network \
    --disable-hwaccels --disable-parsers --disable-bsfs --disable-debug --disable-protocols --disable-indevs --disable-outdevs --enable-protocol=file  --disable-stripping --ranlib="emranlib" 
emmake make
`
And then I got two files:ffmpeg_g  and ffmpeg_g.wasm.Which is the js file and wasm file.But when use in html,it returns 
`Uncaught (in promise) WORKERFS is no longer included by default; build with -lworkerfs.js` in console . 

My problem is why emmake generate wasm file directly,without LLVM bitcode? So I can't add paras during build.

**Comment by sbc100** [comment]
The build system for ffmpeg is setup to produce an executable called ffmpeg_g so the behavior you are seeing I believe is working as indended.

If you want the library files then I believe you want to look for libavcodec.a and other libraries.  Like other platform these are not bitcode by default.  emscripten no longer produced bitcode by default.  If you want bitcode you can pass `-flto` or `-emit-llvm` during complication. 

What kind of params do you want to pass?   Do you really need bitcode output files or do you just want to pass parameters to the compiler?  Normally you can pass params to the compiler via CFLAGS and LDFLAGS when running configure.

**Comment by visla-mengzhihao** [comment]
But how can I set the parameters? For example ,the js file  tell me to build with -lworkerfs.js ?

**Comment by sbc100** [comment]
`-lworkerfs.js` is a linker flag.   You would need to add it to the link flags somehow.   If you are setting `-s` options somewhere you could add it there.   Are you already setting them in `LDFLAGS`, if not I think it would be `LDFLAGS=-lworkerfs.js`
