### ISSUE TITLE
Question: how to use emscripten to declare `memory` in .wasm as `shared`

### ISSUE THREAD

**Issue by tigercosmos** [emscripten-core/emscripten#12098]
when emcc compile pthread to js +wasm, the wasm has
```
  (import "env" "memory" (memory (;0;) 256 256 shared))
```
as we can see, the `memory` is declared as `shared`.

I want to compile a standalone wasm with shared memory, so I can use JS's shared `WebAssembly.Memory`:
```
new WebAssembly.Memory({initial: 1, maximum: 1, shared: true});
```

How can I compile a C code and declared its variable as `shared` and compile it to a standalone wasm?

**Comment by sbc100** [comment]
I think the only way to get a shared memory today is to compile with `USE_PTHREADS`, and this more is currently incompatible with `STANDALONE_WASM`.

The fix would be to make `STANDALONE_WASM` work with `USE_PTHREADS` but that could be fair amount of work.

**Comment by sbc100** [comment]
The simplest way to get what you want today is probably to build with `STANDALONE_WASM` and then use wasm2wat and edit the resulting `.wat` file to mark the memory as shared.

Bear in mind that if you use this method, your code will not compiled with thread support which means it won't contains any atomic accesses and you could end up with data races.

**Comment by tigercosmos** [comment]
I've tried using wasm2wat and just add "shared" behind, but it will cause error once using wat2wasm to compile. I guess it is not allowed to do this?

**Comment by tlively** [comment]
What error are you getting? You might need to add `--enable-threads`.

**Comment by tigercosmos** [comment]
@tlively  thanks! You are right!
@sbc100 thank you too!
