### ISSUE TITLE
Add ADVISE mode for ASYNCIFY

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#12107]
Emscripten's old Emterpreter mode had a setting `EMTERPRETIFY_ADVISE` that would output which functions it had identified needed to be converted for use with the Emterpreter. I've checked the docs and settings.js, but couldn't see anything like this for the new Asyncify mode.

**Comment by kripken** [comment]
I'm curious to hear more about how this would be useful, as Asyncify will automatically do that analysis and add those functions by itself.

If you want to get logging of that analysis, asyncify has an `asyncify-verbose` which you can use, with something like
```
-s BINARYEN_EXTRA_PASSES='--pass-arg=asyncify-verbose' --profiling
```
We could document that, as I think it's only mentioned on the Asyncify side atm in Binaryen.

Or is there another use case?

**Comment by curiousdannii** [comment]
Ah thanks, that's really helpful!

Use case is determining whether you have functions that should be added to `ASYNCIFY_REMOVE` or to determine whether `ASYNCIFY_IGNORE_INDIRECT` could help.

How would you feel about an extra setting that would enable those options?

**Comment by kripken** [comment]
> How would you feel about an extra setting that would enable those options?

That sounds reasonable. It is a little tricky to get the arg right, and that you need `--profiling` or such also tricky. PR would be great!

> What does "can change the state due to initial scan" mean?

It's anything before the "flow" analysis between functions. That is, things we notice during scanning of the function's body. That includes use of indirect calls, and a few other minor things I think. I'll look into improving the text of those on the binaryen side.
