### ISSUE TITLE
Browser unable to allocate memory when loading large file in VTK after compiling with Emscripten

### ISSUE THREAD

**Issue by ming-origen** [emscripten-core/emscripten#12109]
Hi,

I have compiled VTK via WebAssembly, and am trying to load a large (~600MB .vtp) file for visualization from the browser.
For the sake of testing, I have packaged the .vtp file using `--preload-file`.
However, when I'm trying to load the file, it complains (on Chrome):  
```
ReadPolyData.js:2270 ERROR: In /work/src/Common/Core/vtkGenericDataArray.txx, line 389
put_char @ ReadPolyData.js:2270
ReadPolyData.js:2270 vtkLongLongArray (0x58c728): Unable to allocate 155551200 elements of size 8 bytes. 
put_char @ ReadPolyData.js:2270
ReadPolyData.js:2270 
put_char @ ReadPolyData.js:2270
ReadPolyData.js:13325 exception thrown: 5819304
callMain @ ReadPolyData.js:13325
ReadPolyData.js:223 Uncaught 5819304
```

Is there a good way to know the amount of memory the browser is asking to allocate?  
From what I can tell, on Chrome it's trying to allocate `155551200 * 8 = 1244409600` (\~1.2GB) of memory.
Here is a snapshot of the current memory usage, which shows it's using ~1.5GB of memory:
![image](https://user-images.githubusercontent.com/62708948/92200149-132c9900-ee47-11ea-8280-d18b560f2c46.png)

Considering how Chrome now allows for 4GB of memory, I am a bit confused why this is causing the memory issue. What would be a good way to monitor memory allocation on browser? I have already set the maximum memory to 4GB:
```
set(emscripten_options)
list(APPEND emscripten_options
  ...
  "SHELL:-s MAXIMUM_MEMORY=4GB"
  "SHELL:-s ALLOW_MEMORY_GROWTH=1"
  ...
)
```

I have asked about this issue on the VTK repo [https://gitlab.kitware.com/vtk/vtk/-/issues/17997](https://gitlab.kitware.com/vtk/vtk/-/issues/17997), but feel this might be more relevant for Emscripten? Thanks!

I am also attaching my C++ code for your reference:
```
#include "vtkXMLPolyDataReader.h"
#include "vtkSmartPointer.h"
#include "vtkPolyDataMapper.h"
#include "vtkActor.h"
#include "vtkRenderer.h"
#include "vtkSDL2OpenGLRenderWindow.h"
#include "vtkSDL2RenderWindowInteractor.h"

int main ( int argc, char *argv[] )
{
  using namespace std;
  string filename = "./example.vtp";

  // Read all the data from the file
  vtkSmartPointer<vtkXMLPolyDataReader> reader =
    vtkSmartPointer<vtkXMLPolyDataReader>::New();
  reader->SetFileName(filename.c_str());
  reader->Update();
  
  // Visualize
  vtkSmartPointer<vtkPolyDataMapper> mapper =
    vtkSmartPointer<vtkPolyDataMapper>::New();
  mapper->SetInputConnection(reader->GetOutputPort());

  vtkSmartPointer<vtkActor> actor =
    vtkSmartPointer<vtkActor>::New();
  actor->SetMapper(mapper);

  vtkSmartPointer<vtkRenderer> renderer =
    vtkSmartPointer<vtkRenderer>::New();
  vtkSmartPointer<vtkSDL2OpenGLRenderWindow> renderWindow =
    vtkSmartPointer<vtkSDL2OpenGLRenderWindow>::New();
  renderWindow->AddRenderer(renderer);
  vtkSmartPointer<vtkSDL2RenderWindowInteractor> renderWindowInteractor =
    vtkSmartPointer<vtkSDL2RenderWindowInteractor>::New();
  renderWindowInteractor->SetRenderWindow(renderWindow);

  renderer->AddActor(actor);
  renderer->SetBackground(.3, .6, .3); // Background color green

  renderWindow->Render();
  renderWindowInteractor->Start();

  return EXIT_SUCCESS;
}
```

**Comment by kripken** [comment]
`emscripten_realloc_buffer` is where the program will grow the memory. In a build with `ASSERTIONS` enabled it should log errors,

https://github.com/emscripten-core/emscripten/blob/246938cbdb7c8c293cff5088db68d659df4859c7/src/library.js#L484-L486

so that could tell you how much is being requested.

See also `MEMORY_GROWTH_LINEAR_STEP` and related options as used in `emscripten_resize_heap` (which is where we decide how much to grow by).

**Comment by ming-origen** [comment]
Thanks @kripken! I'll check these.
