### ISSUE TITLE
wasm-sourcemap.py fails if parts of the code are on a different drive on Windows

### ISSUE THREAD

**Issue by GeorgRottensteiner** [emscripten-core/emscripten#12111]
I have common code on a different drive than the main project code.
Using -g on compiling and -g4 on linking has wasm-sourcemap.py fail on the linking part with errors like:

path is on mount 'p:', start on mount 'D:'

This is a common problem with os.relpath, the fix seems to be in wasm-sourcemap.py:

Replace line 782:

`file_name = os.path.relpath(os.path.abspath(file_name), base_path)`

with:

```
file_name = os.path.abspath(file_name)
try:
  file_name = os.path.relpath(file_name, base_path)
except Exception:
  pass     
```

**Comment by kripken** [comment]
I think that makes sense @GeorgRottensteiner - would you like to open a PR with that? (maybe plus a comment on the try to explain why it is needed) Thanks!

**Comment by GeorgRottensteiner** [comment]
I'll try, never created a PR before :)

**Comment by GeorgRottensteiner** [comment]
Seems I figured it out, I needed to fork the whole shebang and do the branch there.
