### ISSUE TITLE
Emscripten.cmake

### ISSUE THREAD

**Issue by lpotter** [emscripten-core/emscripten#12117]
It seems the Emscripten.cmake toolchain file might be out of date:

SET(CMAKE_EXECUTABLE_SUFFIX ".js")

Not sure of there are other areas where it could be updated

**Comment by Yongle-Fu** [comment]
emcmake cmake .. -DUSE_CUDA=0 -DUSE_OPENCV=0 -DUSE_OPENMP=0 -DUSE_CPP_PACKAGE=1
configure: cmake .. -DUSE_CUDA=0 -DUSE_OPENCV=0 -DUSE_OPENMP=0 -DUSE_CPP_PACKAGE=1 -DCMAKE_TOOLCHAIN_FILE=/path/to/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/path/to/emsdk/node/12.18.1_64bit/bin/node"
-- CMAKE_CROSSCOMPILING TRUE
-- CMAKE_HOST_SYSTEM_PROCESSOR x86_64
-- CMAKE_SYSTEM_PROCESSOR x86
-- CMAKE_SYSTEM_NAME Emscripten
-- CMake version '3.18.2' using generator 'Unix Makefiles'
-- Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_INTEL_LIBRARY MKL_INTEL_THREAD_LIBRARY MKL_CORE_LIBRARY IOMP_LIBRARY)
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
CMake Error at cmake/Modules/FindOpenBLAS.cmake:82 (MESSAGE):
  Could not find OpenBLAS
Call Stack (most recent call first):
  cmake/ChooseBlas.cmake:42 (find_package)
  CMakeLists.txt:303 (include)

-- Configuring incomplete, errors occurred!
See also "/path/to/mxnet/build_emsdk/CMakeFiles/CMakeOutput.log".

**Comment by Yongle-Fu** [comment]
emcmake failed.  -> emcmake cmake .. -DUSE_CUDA=0 -DUSE_OPENCV=0 -DUSE_OPENMP=0 -DUSE_CPP_PACKAGE=1
but without emcmake success. -> cmake .. -DUSE_CUDA=0 -DUSE_OPENCV=0 -DUSE_OPENMP=0 -DUSE_CPP_PACKAGE=1

**Comment by sbc100** [comment]
What is wrong with using `.js` as the output suffix for executables?     It seems pretty reasonable to me since `.wasm` files are not generally usable on their own, and most users probably don't want the `.html` boilerplate.

I guess one possible alternative would be to use the empty suffix (which would still produce JavaScript file)?
