### ISSUE TITLE
wasm-ld stage: unexpected existing value for R_WASM_MEMORY_ADDR_I32

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#12110]
I'm trying to narrow down what causes this message:

```
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=2148916452 expected=18446744071563500772
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=2148916460 expected=18446744071563500780
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=2148916468 expected=18446744071563500788
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=2148916476 expected=18446744071563500796
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=2148916484 expected=18446744071563500804
```
I get quite a few of these with these arguments to `wasm-ld` from emcc 2.0.1
```
-o e:\1.o E:\GitHub\corert\tests\src\Simple\HelloWasm\obj\Debug\wasm\native\HelloWasm.o 
E:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libbootstrappercpp.a 
-LE:\GitHub\emsdk\upstream\emscripten\system\local\lib  
-LE:\GitHub\emsdk\upstream\emscripten\system\lib 
-LE:\GitHub\emsdk\upstream\emscripten\cache\wasm 
-mllvm 
-combiner-global-alias-analysis=false 
-mllvm 
-enable-emscripten-cxx-exceptions 
-mllvm 
-enable-emscripten-sjlj 
-mllvm 
-disable-lsr 
--allow-undefined 
--import-memory 
--import-table -
-export main 
--export malloc 
--export free 
--export stackSave 
--export stackRestore 
--export stackAlloc 
--export __data_end 
--export __wasm_call_ctors 
--export fflush 
--export __errno_location 
--export __cxa_is_pointer_type 
--export __cxa_can_catch 
--export _ZSt18uncaught_exceptionv 
--export setThrew 
--export memalign 
--export memset 
--export emscripten_main_thread_process_queued_calls 
-z stack-size=5242880 
--initial-memory=167772160 
--no-entry 
--max-memory=167772160 
--global-base=1024 --verbose
```
I've got wasm-ld in the debugger to try to narrow down the problem as currently I only know it happens when combining the wasm object .o file built from LLVM IR, and the wasm .a archive built from c++ code with emcc.

In the debugger it happens after printing
```
wasm-ld: writing CUSTOM(.debug_ranges) size=265 chunks=1
wasm-ld: writing CUSTOM(.debug_pubtypes) size=250166 chunks=1
wasm-ld: writing CUSTOM(.debug_info) size=898780 chunks=2
wasm-ld: writing DATA size=1776661 body=1776657
wasm-ld: writing CODE
wasm-ld:  size=12127832
wasm-ld:  headersize=5
wasm-ld:  codeheadersize=3
wasm-ld: writing ELEM
wasm-ld: writing EXPORT
wasm-ld: writing GLOBAL
wasm-ld: writing FUNCTION
wasm-ld: writing IMPORT
wasm-ld: writing TYPE
```
![image](https://user-images.githubusercontent.com/2720041/92263828-e4dca700-eea2-11ea-94df-1208f67e55f6.png)

The bitcode from HelloWasm.o is large at 28MB, so I would like to get a smaller repro.  Is there anything I can see from debugging `wasm-ld` to help me identify where in the bitcode (as I think that's likely where the problem is) I should focus?

**Comment by yowl** [comment]
I can add that in 
```
uint64_t ObjFile::calcExpectedValue(const WasmRelocation &reloc) const
```
it goes through
```
    if (segment.Data.Offset.Opcode == WASM_OPCODE_I32_CONST)
      return segment.Data.Offset.Value.Int32 + sym.Info.DataRef.Offset +
             reloc.Addend;
```
Where `reloc.Addend is a 64 bit value and has a negative value e.g. `-2147483648` which looks like what causes the resulting large `expected` value

**Comment by sbc100** [comment]
There have been a couple of recent fix on the llvm side that might address this.

Could you try again with the `tot` emsdk release?

**Comment by sbc100** [comment]
If it still happens could you zip up the input files at attach to this ticket?

**Comment by yowl** [comment]
Seems to still have them with `tot`.  Extract the zip and run
[e.zip](https://github.com/emscripten-core/emscripten/files/5337175/e.zip)

"E:\GitHub\emsdk\upstream\emscripten\emcc.bat" "HelloWasm.o" -o "HelloWasm.html" -s ABORTING_MALLOC=0 -s 
ERROR_ON_UNDEFINED_SYMBOLS=0 -s DISABLE_EXCEPTION_CATCHING=0 --emrun "libPortableRuntime.a" "libbootstrappercpp.a" "libSystem.Private.CoreLib.Native.a"  -g3 -s INITIAL_MEMORY=268435456 --js-library dotnet_support.js --pre-js Microsoft.JSInterop.js --post-js HelloWasm.js -g -fsanitize=address

**Comment by sbc100** [comment]
Great.  I'll take a look.  

Where do `libSystem.Private.CoreLib.Native.a`, `libPortableRuntime.a` and `libSystem.Private.CoreLib.Native.a` come from by the way?  Specifically is everything here built from source using the same version of the SDK are you are trying to use object code or libraries built with an older version of llvm/emsdk?

**Comment by yowl** [comment]
I've rebuilt them to be sure, but yes they all come from the same version of emcc.  Those are built from cpp using emcc.  HelloWasm.o is built from LLVM using emcc -c.  THis is all the wasm backend of https://github.com/dotnet/corert
[Uploading e.zip…]()

**Comment by yowl** [comment]
[e.zip](https://github.com/emscripten-core/emscripten/files/5337390/e.zip)

**Comment by sbc100** [comment]
The `unexpected existing value for R_WASM_MEMORY_ADDR_I32` warnings I've seen before are when a slightly older version of llvm was used to produce the object files.    Is it possible that https://github.com/dotnet/corert is using a slightly different version of llvm? 

I think these offsets in question were changed in https://reviews.llvm.org/D79462 or https://reviews.llvm.org/D87407.     

Its is a little sad to have this ABI break, between LLVM versions.  I was kind of hoping it would not effect too many people.  However, I believe it should be safe to just ignore the warning.  Are you seeing in runtime issues?   The placeholder value that is being complained about should not matter because the linker overrides them anyway.

**Comment by yowl** [comment]
Runtime looks fine.  When LLVM11 is out, then hopefully we'll get a new version of LLVMSharp and hence a new version of LLVM.  It's always a problem for me when I want the latest emscripten, but have to chance it with an older LLVMSharp/libLLVM.  Go ahead and close if you like, if it is still present with LLVM11 I can reopen.

**Comment by sbc100** [comment]
Ok that makes sense  Good to know.   

I don't know if you are already tracking https://github.com/emscripten-core/emscripten/issues/11362 but it certainly seems like you could benefit.
