### ISSUE TITLE
emconfigure doesn't trigger native executable with unknown file extension anymore

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#12148]
Hi,

#11807 changes emconfigure's behavior a bit and breaks my ffmpeg compilation.

```
emconfigure emcc -o ffconf.fPJJgwvT test.o
```
used to produce test.qsdf as an executable, providing pseudo-native compilation (pre-2.0.0).
Since 2.0.0 it has the same behavior as without `emconfigure` so ffmpeg's `./configure` fails as it can't execute `ffconf.fPJJgwvT` (which is now an object file).

(The past behavior is maintained with no extension -- `emconfigure emcc -o ffconf test.o` .)

I believe this change wasn't intended.

**Comment by sbc100** [comment]
Sorry about that.  I do have change in works to default to outputting executables for all unknown suffixes:  https://github.com/emscripten-core/emscripten/pull/11799.  

I will try get that than landed.

**Comment by sbc100** [comment]
Fixed in #11799.
