### ISSUE TITLE
pthreads inside a worker?

### ISSUE THREAD

**Issue by Zelex** [emscripten-core/emscripten#12140]
I can't get pthreads to work if in a worker. So in my setup I have a worker, and this worker loads the emscripten wasm js file, this wasm js file then instantiates additional workers to do the pthread work. This worker inside worker setup seems to generally be pretty broken.

**Comment by kripken** [comment]
#12102 which just landed fixed an issue that sounds like this.

You can test with that PR, or wait until the next tip of tree build.
