### ISSUE TITLE
HTTP Error 401.3 - Unauthorized under IIS for emscripten compiler output files

### ISSUE THREAD

**Issue by r-pankevicius** [emscripten-core/emscripten#12161]
#### OS 
Windows 10

#### Emscripten version was latest 2 weeks ago or so...
C:\~src\IIS-crap\emcc-play\uhu>emcc --version
emcc (Emscripten gcc/clang-like replacement) 2.0.1 (4ee902fd6963233f6be8b818eebd529ae406221e)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

#### localhost/mycrap
I set up a most primitive web site "mycrap" under IIS (Microsoft Web Server just in case you've never heard about it) with directory listing allowed. It points to C:\~src\IIS-crap so I can go to http://localhost/crap and see all files there and make my experiments.

#### Let's write hello.c
Now I am in folder C:\~src\IIS-crap\emcc-play\emcc-play\uhu and created a hello.c file using (surprise - not vim!) notepad:
```c
#include <stdio.h>

int main() {
  printf("hello, world!\n");
  return 0;
}
```
When I open URL http://localhost/crap/emcc-play/uhu/hello.c, I see that program.
So far, so good.

#### Let's compile hello.c

```
C:\~src\IIS-crap\emcc-play\uhu>dir
 Volume in drive C has no label.
 Volume Serial Number is 663B-14EA

 Directory of C:\~src\IIS-crap\emcc-play\uhu

09/10/2020  10:21 PM    <DIR>          .
09/10/2020  10:21 PM    <DIR>          ..
08/30/2020  05:46 PM                80 hello.c
               1 File(s)             80 bytes
               2 Dir(s)  104,067,710,976 bytes free

C:\~src\IIS-crap\emcc-play\uhu>emcc hello.c -o name.html

C:\~src\IIS-crap\emcc-play\uhu>dir
 Volume in drive C has no label.
 Volume Serial Number is 663B-14EA

 Directory of C:\~src\IIS-crap\emcc-play\uhu

09/10/2020  10:22 PM    <DIR>          .
09/10/2020  10:22 PM    <DIR>          ..
08/30/2020  05:46 PM                80 hello.c
09/10/2020  10:22 PM           103,974 name.html
09/10/2020  10:22 PM           118,904 name.js
09/10/2020  10:22 PM            21,404 name.wasm
               4 File(s)        244,362 bytes
               2 Dir(s)  104,067,452,928 bytes free
```
#### Let's see it in browser (Houston, we have a problem)
Now it seems obvious that I can open http://localhost/crap/emcc-play/uhu/name.html to test what I have got. But I get a nice spin-forever page. DevTools (F12) show error in console:
name.js:1 Failed to load resource: the server responded with a status of 401 (Unauthorized).

If, in browser, I go to ~~any~~ js and wasm files generated by emscripten (~~name.html,~~ name.js, name.wasm) I get this back:
```
HTTP Error 401.3 - Unauthorized
You do not have permission to view this directory or page because of the access control list (ACL) configuration or encryption settings for this resource on the Web server.
```

**Comment by sbc100** [comment]
This doesn't seem to be related to emscripten it is?  Isn't just a web server configuration issue?   Maybe your server isn't configured to server certain file types?    Maybe check the web server logs?

**Comment by r-pankevicius** [comment]
Basically ICACLS command shows what is going on: while name.html output file has "expected permissions", name.js and name.wasm have elevated permissions.

```
C:\~src\IIS-crap\emcc-play\uhu>icacls *.*
hello.c BUILTIN\Administrators:(I)(F)
        NT AUTHORITY\SYSTEM:(I)(F)
        BUILTIN\Users:(I)(RX)
        NT AUTHORITY\Authenticated Users:(I)(M)

name.html BUILTIN\Administrators:(I)(F)
          NT AUTHORITY\SYSTEM:(I)(F)
          BUILTIN\Users:(I)(RX)
          NT AUTHORITY\Authenticated Users:(I)(M)

name.js NT AUTHORITY\SYSTEM:(F)
        BUILTIN\Administrators:(F)
        (MY-DOMAIN)\(MY-USER-NAME):(F)

name.wasm NT AUTHORITY\SYSTEM:(F)
          BUILTIN\Administrators:(F)
          (MY-DOMAIN)\(MY-USER-NAME):(F)

Successfully processed 4 files; Failed processing 0 files
```

**Comment by r-pankevicius** [comment]
@sbc100 : added more info.

**Comment by sbc100** [comment]
Those files are not created in any special way.  I think mostly likely just `open(<filename>, 'w')` in python.   I can't see how emcc could create files that have "elevated permissions".    Is emcc itself installed as admin or your local user?

Maybe someone who knows more about windows can see what is going on?

I don't think we've have any reports of issues like this on windows before.

**Comment by sbc100** [comment]
(as a workaround can you somehow change the permissions).

**Comment by r-pankevicius** [comment]
@sbc100 I'agree that "Those files should not created in any special way", but they are :( Html file is not created in any special way, but js and wasm are.

Workaround exists:
`icacls "C:\~src\IIS-crap\emcc-play\uhu" /q /c /t /grant Users:F`

**Comment by r-pankevicius** [comment]
@sbc100 "I don't think we've have any reports of issues like this on windows before."

I checked that there are no open issues where IIS is mentioned. Probably Windows+IIS issue...

**Comment by sammax** [comment]
@r-pankevicius your src folder is not within your user folder. Changing the permissions of the folder to resemble those of a folder within your user folder makes all the emscripten-generated files have the correct acls. I don't know why the html file is created differently though. I suspect that they are created by different tools which use different mechanisms for some reason.

**Comment by sammax** [comment]
Thinking about it a bit more, the permissions from your user folder might not actually be the ones you need for IIS, but either way you can change the permissions of the containing folder to make the files get the permissions that you need.

**Comment by r-pankevicius** [comment]
@sammax Just look that "default defaults to defaults". I can open windows file explorer, right click with the mouse (Mac users won't understand that), create new "Text Document.txt" and I will see it in browser...

Or from command line (Windows users won't understand that):
```
C:\~src\IIS-crap\emcc-play\uhu>echo UHU > uhu.txt

C:\~src\IIS-crap\emcc-play\uhu>icacls uhu.txt
uhu.txt BUILTIN\Administrators:(I)(F)
        NT AUTHORITY\SYSTEM:(I)(F)
        BUILTIN\Users:(I)(RX)
        NT AUTHORITY\Authenticated Users:(I)(M)

Successfully processed 1 files; Failed processing 0 files
```

**Comment by sammax** [comment]
Hm, it seems what I said earlier is not quite correct. The js and wasm files are created without any permissions except for SYSTEM, Administrators and the current user, even when additional permissions are added for the containing folder.

**Comment by r-pankevicius** [comment]
On Linux emcc generates output files without playing with permissions, just checked in Google Cloud Shell:

```
$ ls -l
total 248
-rw-r--r-- 1 r_pankevicius rvm               75 Sep 11 06:56 hello.c
-rw-r--r-- 1 r_pankevicius r_pankevicius 102674 Sep 11 06:57 name.html
-rw-r--r-- 1 r_pankevicius r_pankevicius 114838 Sep 11 06:57 name.js
-rw-r--r-- 1 r_pankevicius r_pankevicius  21343 Sep 11 06:57 name.wasm
```

**Comment by r-pankevicius** [comment]
@sbc100 Do you think it will solve the issue?

Sorry, I'm a bit late, but I didn't get a notification by e-mail...

**Comment by r-pankevicius** [comment]
@sbc100 A small improvement - now there are no issues to access wasm file, but generated js file is inaccessible - HTTP Error 401.3 - Unauthorized.

```
C:\~src\IIS-crap\emcc-play\check2>emcc --version
emcc (Emscripten gcc/clang-like replacement) 2.0.4 (3047b77ed244ea8f3cb3ee7b18c0f89079ae6554)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


C:\~src\IIS-crap\emcc-play\check2>emcc hello.c -o name.html

C:\~src\IIS-crap\emcc-play\check2>icacls *.*
hello.c BUILTIN\Administrators:(I)(F)
        NT AUTHORITY\SYSTEM:(I)(F)
        BUILTIN\Users:(I)(RX)
        NT AUTHORITY\Authenticated Users:(I)(M)

name.html BUILTIN\Administrators:(I)(F)
          NT AUTHORITY\SYSTEM:(I)(F)
          BUILTIN\Users:(I)(RX)
          NT AUTHORITY\Authenticated Users:(I)(M)

name.js NT AUTHORITY\SYSTEM:(F)
        BUILTIN\Administrators:(F)
        (MY-DOMAIN)\(MY-USER-NAME):(F)

name.wasm BUILTIN\Administrators:(I)(F)
          NT AUTHORITY\SYSTEM:(I)(F)
          BUILTIN\Users:(I)(RX)
          NT AUTHORITY\Authenticated Users:(I)(M)

Successfully processed 4 files; Failed processing 0 files
```

**Comment by sbc100** [comment]
Yes we think we understand the issue now.   The solution is to write the final JS file directly to the target location.   I'm not sure when I'll get around to the fix though.   Do you have a workaround for now?

**Comment by r-pankevicius** [comment]
Of course I have, I mentioned it above.
BTW it's probably a good time to add a better error handling in generated html before you fix it.
Because here is what I see forever trying to open generated name.html: [screenshot](https://imgur.com/a/sziL5BB)

**Comment by sbc100** [comment]
I guess that is the same thing that happens if the wasm file is not fetchable for any reason?  

I assume the errors show up in the JS console?    I think the JS console is where we report most warnings and errors to the developer so it seems ok to me.  Do you think there is specific reason why that is not good enough in this situation?

**Comment by r-pankevicius** [comment]
Yes, they show up as:
`name.js:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)`

Well, I agree with you: emsdk is not a product for end user, so developers will solve these issues before releasing products to the user.

**Comment by r-pankevicius** [comment]
Another observation: when (in sources folder) after first compilation I run a "grant all users access to all files in this folder" command once:
`icacls . /q /c /t /grant Users:F`
then consequent changes to the source file (hello.c) will keep permissions to output files the same as they were before.

So it is enough to apply this workaround once and forget about it for a long while. Because typically you are changing source files tens and hundreds times while the output files (wasm and "js interop") remain the same.
