### ISSUE TITLE
Documentation for HTML5 events and pthreads should reference usleep as a requirement  for dispatching

### ISSUE THREAD

**Issue by DConmy** [emscripten-core/emscripten#12175]
https://emscripten.org/docs/api_reference/html5.h.html#html5-h

For the html5 event dispatching, the events are enqueued to the originally registering pthread (if it exists) and if it does not, the callback will be called directly.

In the case that the target thread exists, the calling sequence is as follows...

registerMouseEventCallback/wheel/ui event/etc
  JSEvents.queueEventHandlerOnThread.  
      emscripten_call_on_thread.    (if there is a thread to target and not us/current thread) 

The enqueued events are dequeued by calling either usleep, or emscripten_current_thread_process_queued_calls (which is called by usleep).   The documentation does not refer to either function.

One could argue that it would be logical to usleep on the pthread when idle.   While that is a valid point, our pthreads block on sem_waits which should be similar, with the exception of this implementation detail.

**Comment by kripken** [comment]
I think a third possibility is to return control to the main event loop. But I'm not sure if that works - if not we should fix it.

Otherwise I think that's all correct @DConmy , would you like to open a PR? Thanks!

**Comment by DConmy** [comment]
I'm not following on the 3rd option regarding returning control to the main event loop.   
Could you please elaborate?   (Or you may mean my suggestion below)

There is an additional problem with the codepath that dispatches to another thread, the code can no longer prevent default event handling...

#if USE_PTHREADS
      **if (targetThread) JSEvents.queueEventHandlerOnThread_iiii(targetThread, callbackfunc, eventTypeId, keyEventData, userData);**
      else
#endif
      if ({{{ makeDynCall('iiii', 'callbackfunc') }}}(eventTypeId, keyEventData, userData)) **e.preventDefault()**;

For our use case, we can be called from the main browser thread.   And from reviewing the headers, could do so by calling the _on_thread variants of the calls...   (which avoids the preventDefault problem as well)

emscripten_set_keydown_callback_on_thread( ..., EM_CALLBACK_THREAD_CONTEXT_MAIN_BROWSER_THREAD)

I would be more than happy to submit updates to the documentation.
I reviewed https://emscripten.org/docs/site/about.html#writing-and-updating-articles  And the link referenced in Building the Site to GitHub is broken.   Could you please point me to the repo behind the site?

**Comment by kripken** [comment]
By "return control to the main event loop" I meant to use something like `emscripten_set_main_loop`, that is, to run an async event loop as opposed to an "infinite loop" that never exits. On the browser main thread you need to return to the main event loop constantly for events to happen.

Updates to the docs would be great! That one link does look broken, I'll fix it. But the repo for the site is just this repo - the website is under `site/`. You can build it with `make html` under `site/`
