### ISSUE TITLE
Cleanup the old v1 FS compatibility functions

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#12185]
At the bottom of library_fs.js are what are labelled the "old v1 compatibility functions". These are a bunch of functions that don't seem to be used by the core FS implementation (though some are used elsewhere in other library files), with the exception of `createDevice` which is used elsewhere in library_fs.js. Altogether these functions constitute about 6.7KB of a minimised JS output. Because they are properties of the FS object they all get included, rather only if they get used. Can they be cleaned up?

**Comment by sbc100** [comment]
Sounds like a great idea! 

I imagine those who really care about JS codesize probably aren't using the filesystem stuff which is perhaps why this has not been focused on?
