### ISSUE TITLE
Freetype port not performing subpixel rendering (FT_LOAD_TARGET_LCD doesn't work)

### ISSUE THREAD

**Issue by JacksonAllan** [emscripten-core/emscripten#12197]
Hello :)

The Freetype port doesn't seem to be allowing any subpixel rendering. Usually, such rendering can be enabled using the FT_LOAD_TARGET_LCD flag. In this mode, the rendered glyph bitmap should contain separate values for the red, green, and blue channels of each pixel rather than just one value per pixel. However, when compiled via Emscripten, the one value is duplicated across all three channels.

Here is an example program demonstrating the issue. The program renders the letter "I" with the Arial font.
```
//Freetype 2 subpixel rendering test. Replace arial.ttf with your chosen font.
//GCC build: gcc -o ftsubpixeltest main.c -lfreetype -lz
//Emscripten build: emcc main.c -s USE_FREETYPE=1 --preload-file arial.ttf -o ftsubpixeltest.html

//main.c
#include <stdio.h>
#include <ft2build.h>
#include FT_FREETYPE_H

int main()
{
	FT_Library library;
	FT_Face face;
	FT_Init_FreeType( &library );
	FT_New_Face( library, "arial.ttf", 0, &face );
	FT_Set_Pixel_Sizes( face, 0, 18 );
	FT_Load_Char( face, 'I', FT_LOAD_RENDER | FT_LOAD_TARGET_LCD );

	for( int y = 0; y < face->glyph->bitmap.rows; y++ )
	{
		for( int x = 0, cols = face->glyph->bitmap.width / 3; x < cols; x++ )
		{
			printf( "[R%03d G%03d B%03d] ",
				face->glyph->bitmap.buffer[ y * face->glyph->bitmap.pitch + x * 3 ],
				face->glyph->bitmap.buffer[ y * face->glyph->bitmap.pitch + x * 3 + 1 ],
				face->glyph->bitmap.buffer[ y * face->glyph->bitmap.pitch + x * 3 + 2 ]
			);
		}
		
		printf( "\n" );
	}

	FT_Done_Face( face );
	FT_Done_FreeType( library );

	return 0;
}
```

gcc output:
```
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
[R000 G084 B168] [R255 G255 B255] [R184 G100 B016]
```
Here, the RGB channels differ for the pixels on the edge of the glyph, as expected.

emcc output:
```
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
[R255 G255 B255] [R255 G255 B255] 
```
Here, the RGB channels for every pixel are the same. The change of bitmap size suggests that Freetype is performing a regular (non-subpixel, grayscale) render and simply duplicating the result three times in the glyph's bitmap buffer to account for the expected three channels when FT_LOAD_TARGET_LCD is used.

Is this behavior expected? If so, is there any way to fix it?

**Comment by JacksonAllan** [comment]
I solved this problem. The issue is that Emscripten's version of FreeType (version 2.6) is rather old, and only in later versions was access to subpixel rendering enabled by default. The solution was therefore to compile the newest version with Emscripten.

For reference (and my own records), I managed to do this on Windows using CMake and Mingw-w64 by opening a command prompt in the directory of the latest FreeType version and setting the PATH variable to include the Emscripten paths (see or use emcmdprompt.bat) and my MinGW\bin directory. Then I ran the following commands:
```
mkdir emscripten_build
cd emscripten_build
emcmake cmake -D CMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" ..
emake make
```
This produces a libfreetype.a file. That file can then be placed in the same directory as your project and included in your Emscripten build. So for the above program, that's:
`emcc main.c libfreetype.a -s USE_FREETYPE=1 --preload-file arial.ttf -o ftsubpixeltest.html`
Alternatively, I suppose you could replace the libfreetype.a in your Emscripten directories.

I've also  attached my version of libfreetype.a, compiled from FreeType 2.10.2, to this post in case it might help someone. It seems to work fine but hasn't been thoroughly tested.

Of course, getting FreeType to perform subpixel font rendering is only half the problem. The other issue - for anyone intending to use it with WebGL - is that WebGL does not support the dual source blending needed for such rendering. I think a workaround is to get the background color where the text will be rendered from the current render buffer using glReadPixels and then passing it into the shader and doing the blending manually there. This should work so long you're rendering text against a flat background, although I'm sure glReadPixels has an impact on performance.
[libfreetype.zip](https://github.com/emscripten-core/emscripten/files/5220395/libfreetype.zip)

**Comment by kripken** [comment]
It would be good to update the port too.

cc @anlambert who has been helping there. @JacksonAllan I can also add you to the repo if you have time to update it + `tools/ports/freetype.py`? Should be pretty easy.

**Comment by JacksonAllan** [comment]
I'd like to help, but unfortunately, I don't think I'm the right person for the job as I don't really know the behind-the-scenes workings of Emscripten nor Python.
