### ISSUE TITLE
Bug in page:CyberDWARF Debugging 

### ISSUE THREAD

**Issue by softwareCobbler** [emscripten-core/emscripten#12194]
maybe no longer valid as of 0c405fc5827449df9e1d0dda9b901e6c2d5e2ac2
(I am getting `em++: error: Attempt to set a non-existent setting: 'CYBERDWARF'`)
URL: ../../docs/debugging/CyberDWARF

**Comment by sbc100** [comment]
Ah, yes it looks like the docs need updating (removing).  Thanks for pointing that out.
