### ISSUE TITLE
emcc not support -fpermissive compile option

### ISSUE THREAD

**Issue by Xiangqian-Dong** [emscripten-core/emscripten#12199]
I compile some code in Win10, CLion2020.1.
Visual studio 2017 compiled ok, but emcc 1.39.10 compile error in Win10.
I try MinGW, GCC compile ok if add -fpermissive compile option.
I try emcc with -fpermissive compile option, but the code still compile error.
The code list below.
Does emcc support -fpermissive compile option?
Will emcc support -fpermissive compile option?
Thanks.

// main.cpp 
```C++

namespace Name {
    template <typename T> class A;
}
template <typename T>
class Name::A {
public:
    void Func1() {
        Func2();
    }
};

int main() {

    Name::A<int> aInt;
    return 0;
}
```

// c.cpp
```C++

namespace Name {
    void Func2();
}

void Name::Func2() {

}
```

**Comment by sbc100** [comment]
This is because emscripten is based on clang and not gcc.   It seems clang does not support use of undeclared identifiers even in  `-fpermissive` mode.

If you want feature added you would need to discuss it in the clang issue tracker.
