### ISSUE TITLE
does anybody knows that the way to reduce js size?

### ISSUE THREAD

**Issue by wudimeicom** [emscripten-core/emscripten#12205]
emcc output a large javascript ,which contain  lots of things that most of them i don't use.

maybe something like this:

const sn={imports:{func:function(a){console.log(a);}}};

function loada(p){
return fetch(p)
.then(h=>h.arrayBuffer())
.then(cj=>{
try{
let m=new WebAssembly.Module(cj);
let c=new WebAssembly.Instance(m,sn);
return c;
}catch(e){
alert(e);
}
});
}

**Comment by curiousdannii** [comment]
You can try `STANDALONE_WASM=1`, but that really does put a lot of restrictions on what your program can do. See [settings.js](https://github.com/emscripten-core/emscripten/blob/master/src/settings.js) for more information about that setting.

**Comment by sbc100** [comment]
Emscripten does do a lot of work to reduce the total JS size, especially when running with `-Oz` or `-Os`.  Have you tried those options.

If you want to go even further we have experimental MINIMAL_RUNTIME flag which should emit no redundant JS at all.

If you find JS present in the output of MINIMAL_RUNTIME that is not actually needed please file a bug.

**Comment by kripken** [comment]
The docs have a section on code size:

https://emscripten.org/docs/optimizing/Optimizing-Code.html#code-size

In particular see what it says about closure compiler.
