### ISSUE TITLE
Using getrusage results in "_memset is not defined"

### ISSUE THREAD

**Issue by wilkie** [emscripten-core/emscripten#12204]
Hello all,

I'm cross-compiling binutils, as one does. It used to work in much older emscripten, yet I haven't been able to bisect it using any version listed in emsdk, though. My intention is to run the `as`/`objdump`/etc commands in a worker so I'm using these flags:

```
emcc -v -O3 `find riscv-gnu-toolchain/riscv-binutils-js/intl -name \*.o` `find riscv-gnu-toolchain/riscv-binutils-js/zlib -name \*.o` `find riscv-gnu-toolchain/riscv-binutils-js/opcodes -name \*.o` `find riscv-gnu-toolchain/riscv-binutils-js/libiberty -name \*.o` `find riscv-gnu-toolchain/riscv-binutils-js/libctf -name \*.o` `find riscv-gnu-toolchain/riscv-binutils-js/bfd -name \*.o` `find riscv-gnu-toolchain/riscv-binutils-js/gas -name \*.o` -o assets/js/riscv64-unknown-elf-as-bare.js -s WASM=1 -s ASSERTIONS=1 -lworkerfs.js -lfs.js
```

So `-lworkerfs.js -lfs.js -s WASM=1` with `-O3` though I've permuted the optimization flags to no change.

It calls into `getrusage` which uses `_memset` with absolutely no reference to `_memset` elsewhere in the resulting `riscv64-unknown-elf-as-bare.js` file.

Interestingly, if I add `-s "EXPORTED_FUNCTIONS=['_memset']"` it does a whole lot of wrong stuff! It does not have a filesystem, nor workerfs, etc. I clearly do not understand how that mechanism works.

Thank you for your time!

**Comment by wilkie** [comment]
I workaround this issue by throwing in a naive little memset implementation. I know the only reference is the getrusage which calls it with a multiple of 4 for the length and 0 for v, so:

```javascript
function _memset(p,v,l) {
  for(let i=0;i<l/4;i++){HEAP32[(p+i*4)>>2]=v;}
}
```

**Comment by sbc100** [comment]
What most confuses me about this issue is that `-s "EXPORTED_FUNCTIONS=['_memset']"` seems to cause other problems.  I really can't see how that could be.

The dependency between `__sys_getrusage` and `memset` is documented in `src/deps_info.json` which means maybe there is an issue in the way these dependencies are being processed.

**Comment by sbc100** [comment]
I think I have the fix.

I'm also a little surprised that you managed to build any kind of real program without transitively depending on `memset` in the native code.

**Comment by wilkie** [comment]
It is indeed a real program... it is binutils, so to be fair, that's probably a bit of a magical thing. 😁

As for the export for memset, yeah, I have no clue. I add that and suddenly `FS.filesystems` is undefined and the emitted code doesn't even have the `getrusage` function (but it does have memset!) and it was unclear why that had changed. I certainly do not understand enough about how certain chunks are emitted and in what circumstances to navigate why this happened. I assume that I am the one doing something wrong.

**Comment by wilkie** [comment]
Thanks for that patch! That was quick work. Glad it was seemingly a simple issue.

**Comment by sbc100** [comment]
Oh!  You need to also export `_main` when you export `_memset` .. otherwise emscripten thinks that you *only* want memset :)

**Comment by wilkie** [comment]
That makes COMPLETE sense. haha. It's always the simple things.
