### ISSUE TITLE
Clang's -MJ option to generate compilation database doesn't work with emcc

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#12215]
I am trying to generate compile_commands.json for my project using clang's -MJ option. I tried this option on a sample hello_world program with command:

`em++ Hello.cpp -o Hello -MJ a.o.json`

Emscripten throws an error saying:
`shared:ERROR: a.o.json: No such file or directory ("a.o.json" was expected to be an input file, based on the commandline arguments provided)`

The JSON file should be output as in clang. When I add such json file manually, error changes to:
`shared:ERROR: a.o.json: Input file has an unknown suffix, don't know what to do with it!`

This I believe is happening because em++ is not passing this option to clang.

**Comment by rizsotto** [comment]
For anyone landing here who wants `compile_commands.json` for an Emscripten build without relying on `-MJ`: [Bear](https://github.com/rizsotto/Bear) takes a different route -- it intercepts the build and records the compiler invocations directly, so it does not depend on `em++` forwarding `-MJ` to clang. The upcoming Bear 4.1.6 recognizes `emcc`/`em++` (and the `.py` forms) out of the box, so `bear -- emmake make` (or `bear -- <your build>`) produces a database with the emcc commands as invoked. The recorded command is the emcc invocation itself; a language server that needs Emscripten's built-in include paths can point clangd's `--query-driver` at `emcc`.
