### ISSUE TITLE
Embed-file too slow/inflated compared to preload-file (not available on node)

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#12214]
I'm "preloading" a minimal TexLive distro (~6k small files), with LZ4 this results in 70Mb data file (+ 40Mb wasm file). This works reasonably fast in browser.

I'm trying to make a similar package for node and wish it also access the TexLive distro from some sort of archive (like a data file; in order to avoid distributing huge directories that are slow to unpack/copy/traverse, that's why I don't want to rely on nodefs for accessing the directory), but emscripten does not allow using a "preloaded" lz4 package in node enviroment. Embed-file option produces a 500Mb js file that OOMs node interpreter semingly while trying to set up the file system.

Are there ways to hack around that? I can think of having custom C code for imitating mounted file system via patching out fopen call. Would that work? Are there better ways?

**Comment by kripken** [comment]
I think supporting preloading in node is the best thing here. Looks like @sbc100 has a PR up already that looks mostly done, https://github.com/emscripten-core/emscripten/pull/11785

**Comment by vadimkantorov** [comment]
Closed by #11785 ?

**Comment by kripken** [comment]
Good point, thanks, looks like we can consider this closed.
