### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by qmz13579** [emscripten-core/emscripten#12221]
C:\Users\Administrator>emcc
Traceback (most recent call last):
  File "C:\Users\Administrator\emsdk\upstream\emscripten\\emcc.py", line 42, in <module>
    import emscripten
  File "C:\Users\Administrator\emsdk\upstream\emscripten\emscripten.py", line 22, in <module>
    from tools import building
  File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\building.py", line 23, in <module>
    from . import shared
  File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 1641, in <module>
    parse_config_file()
  File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 340, in parse_config_file
    config_text = open(CONFIG_FILE, 'r').read() if CONFIG_FILE else EM_CONFIG
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\emsdk\\upstream\\emscripten'

**Comment by sbc100** [comment]
Do you have EM_CONFIG set in your environment?

Are you running as admin?

Can you `set EMCC_DEBUG=1` and run again?

**Comment by sbc100** [comment]
Its not clear to be if `C:\Users\Administrator\emsdk\upstream\emscripten` (which is a directory) is trying to be opened as a file...  it certainly shouldn't be

**Comment by sbc100** [comment]
What version of emsdk are you using ?  Can you make sure emsdk itself is up-to-date and you have installed the latest sdk using `emsdk install latest` and `emsdk activate latest`?

**Comment by qmz13579** [comment]
> 您使用哪个版本的 emsdk？您能否确保 emsdk 本身是最新的，并且您已使用 和 安装了最新的 sdk。`emsdk install latest``emsdk activate latest`

C:\Users\Administrator\emsdk>emsdk activate latest
Setting the following tools as active:
   node-12.18.1-64bit
   python-3.7.4-pywin32-64bit
   java-8.152-64bit
   releases-upstream-7a7f38ca19da152d4cd6da4776921a0f1e3f3e3f-64bit

Adding directories to PATH:
PATH += C:\Users\Administrator\emsdk
PATH += C:\Users\Administrator\emsdk\node\12.18.1_64bit\bin
PATH += C:\Users\Administrator\emsdk\python\3.7.4-pywin32_64bit
PATH += C:\Users\Administrator\emsdk\java\8.152_64bit\bin

Setting environment variables:
EMSDK = C:/Users/Administrator/emsdk
EM_CONFIG = C:\Users\Administrator\emsdk\.emscripten
EMSDK_NODE = C:\Users\Administrator\emsdk\node\12.18.1_64bit\bin\node.exe
EMSDK_PYTHON = C:\Users\Administrator\emsdk\python\3.7.4-pywin32_64bit\python.exe
JAVA_HOME = C:\Users\Administrator\emsdk\java\8.152_64bit
EM_CACHE = C:/Users/Administrator/emsdk/upstream/emscripten\cache
The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to permanently register this environment globally to all users in Windows Registry, rerun this command with the option --global.



C:\Users\Administrator>set EMCC_DEBUG=1

C:\Users\Administrator>emcc
shared:DEBUG: EM_CONFIG is located in C:\Users\Administrator\emsdk\upstream\emscripten
Traceback (most recent call last):
  File "C:\Users\Administrator\emsdk\upstream\emscripten\\emcc.py", line 42, in <module>
    import emscripten
  File "C:\Users\Administrator\emsdk\upstream\emscripten\emscripten.py", line 22, in <module>
    from tools import building
  File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\building.py", line 23, in <module>
    from . import shared
  File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 1641, in <module>
    parse_config_file()
  File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 340, in parse_config_file
    config_text = open(CONFIG_FILE, 'r').read() if CONFIG_FILE else EM_CONFIG
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\emsdk\\upstream\\emscripten'

**Comment by qmz13579** [comment]
> > 您使用哪个版本的 emsdk？您能否确保 emsdk 本身是最新的，并且您已使用 和 安装了最新的 sdk。`` emsdk install latest``emsdk activate latest ``
> 
> C:\Users\Administrator\emsdk>emsdk activate latest
> Setting the following tools as active:
> node-12.18.1-64bit
> python-3.7.4-pywin32-64bit
> java-8.152-64bit
> releases-upstream-7a7f38ca19da152d4cd6da4776921a0f1e3f3e3f-64bit
> 
> Adding directories to PATH:
> PATH += C:\Users\Administrator\emsdk
> PATH += C:\Users\Administrator\emsdk\node\12.18.1_64bit\bin
> PATH += C:\Users\Administrator\emsdk\python\3.7.4-pywin32_64bit
> PATH += C:\Users\Administrator\emsdk\java\8.152_64bit\bin
> 
> Setting environment variables:
> EMSDK = C:/Users/Administrator/emsdk
> EM_CONFIG = C:\Users\Administrator\emsdk.emscripten
> EMSDK_NODE = C:\Users\Administrator\emsdk\node\12.18.1_64bit\bin\node.exe
> EMSDK_PYTHON = C:\Users\Administrator\emsdk\python\3.7.4-pywin32_64bit\python.exe
> JAVA_HOME = C:\Users\Administrator\emsdk\java\8.152_64bit
> EM_CACHE = C:/Users/Administrator/emsdk/upstream/emscripten\cache
> The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to permanently register this environment globally to all users in Windows Registry, rerun this command with the option --global.
> 
> C:\Users\Administrator>set EMCC_DEBUG=1
> 
> C:\Users\Administrator>emcc
> shared:DEBUG: EM_CONFIG is located in C:\Users\Administrator\emsdk\upstream\emscripten
> Traceback (most recent call last):
> File "C:\Users\Administrator\emsdk\upstream\emscripten\emcc.py", line 42, in
> import emscripten
> File "C:\Users\Administrator\emsdk\upstream\emscripten\emscripten.py", line 22, in
> from tools import building
> File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\building.py", line 23, in
> from . import shared
> File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 1641, in
> parse_config_file()
> File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 340, in parse_config_file
> config_text = open(CONFIG_FILE, 'r').read() if CONFIG_FILE else EM_CONFIG
> PermissionError: [Errno 13] Permission denied: 'C:\Users\Administrator\emsdk\upstream\emscripten'

I am completely confused, because I use it for the first time, which one has problems, please ask me

**Comment by qmz13579** [comment]
I am completely confused, because I use it for the first time, which one has problems, please ask me

**Comment by sbc100** [comment]
> > 您使用哪个版本的 emsdk？您能否确保 emsdk 本身是最新的，并且您已使用 和 安装了最新的 sdk。`` emsdk install latest``emsdk activate latest ``
> 
> C:\Users\Administrator\emsdk>emsdk activate latest
> Setting the following tools as active:
> node-12.18.1-64bit
> python-3.7.4-pywin32-64bit
> java-8.152-64bit
> releases-upstream-7a7f38ca19da152d4cd6da4776921a0f1e3f3e3f-64bit
> 
> Adding directories to PATH:
> PATH += C:\Users\Administrator\emsdk
> PATH += C:\Users\Administrator\emsdk\node\12.18.1_64bit\bin
> PATH += C:\Users\Administrator\emsdk\python\3.7.4-pywin32_64bit
> PATH += C:\Users\Administrator\emsdk\java\8.152_64bit\bin
> 
> Setting environment variables:
> EMSDK = C:/Users/Administrator/emsdk
> EM_CONFIG = C:\Users\Administrator\emsdk.emscripten

This one looks rather odd.. It should be "C:\Users\Administrator\emsdk\.emscripten".
However I'm not sure why this would cause emscripten to thing that the config was locating in "C:\Users\Administrator\emsdk\upstream\emscripten".



> EMSDK_NODE = C:\Users\Administrator\emsdk\node\12.18.1_64bit\bin\node.exe
> EMSDK_PYTHON = C:\Users\Administrator\emsdk\python\3.7.4-pywin32_64bit\python.exe
> JAVA_HOME = C:\Users\Administrator\emsdk\java\8.152_64bit
> EM_CACHE = C:/Users/Administrator/emsdk/upstream/emscripten\cache
> The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to permanently register this environment globally to all users in Windows Registry, rerun this command with the option --global.
> 
> C:\Users\Administrator>set EMCC_DEBUG=1
> 
> C:\Users\Administrator>emcc
> shared:DEBUG: EM_CONFIG is located in C:\Users\Administrator\emsdk\upstream\emscripten
> Traceback (most recent call last):
> File "C:\Users\Administrator\emsdk\upstream\emscripten\emcc.py", line 42, in
> import emscripten
> File "C:\Users\Administrator\emsdk\upstream\emscripten\emscripten.py", line 22, in
> from tools import building
> File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\building.py", line 23, in
> from . import shared
> File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 1641, in
> parse_config_file()
> File "C:\Users\Administrator\emsdk\upstream\emscripten\tools\shared.py", line 340, in parse_config_file
> config_text = open(CONFIG_FILE, 'r').read() if CONFIG_FILE else EM_CONFIG
> PermissionError: [Errno 13] Permission denied: 'C:\Users\Administrator\emsdk\upstream\emscripten'

**Comment by sbc100** [comment]
Can you run `echo %EM_CONFIG%` to confirm what is in your environment?

**Comment by qmz13579** [comment]
> 你能运行来确认您的环境中的是什么吗？`echo %EM_CONFIG%`

Finally, thank you
