### ISSUE TITLE
Do we still need EMIT_EMSCRIPTEN_METADATA?

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#12231]
When this was originally conceived it was necessary because the embedder required
access to information about the memory and table layout that was not otherwise
available.   Emscripten would extra this information during wasm-emscripten-finalize
but other tools couldn't do that.

Since then we have moved away from a model that required the embedder to know
the memory layout and sbrk() and malloc() are now always fully internal to the wasm
module.

For this reason I'm proposing the remove the memory layout information from the
metadata section (because actually we are moving to world emscripten doesn't know
this statically either), and possible the entire EMIT_EMSCRIPTEN_METADATA
option?

**Comment by sbc100** [comment]
@rianhunter what do you think?

**Comment by sbc100** [comment]
@AndrewScheidecker:  Apparently wavm is relying (or reportedly relying) on `emscripten_metadata`.  Can we work to remove this restriction?

Do you know of any remaining reasons why you still need the emscripten_metadata today?  I'm hoping modern emscripten-built standalone wasm modules don't need this to be executed.

**Comment by AndrewScheidecker** [comment]
I changed WAVM to not require `emscripten_metadata`. It didn't have a real need for it before, it was just using it to produce a user friendly error if STANDALONE_WASM wasn't used, or it had an unexpected ABI version.

**Comment by ERICXUCHI** [comment]
Now WAVM still needs -s EMIT_EMSCRIPTEN_METADATA=1 -s STANDALONE_WASM=1, it seems nothing changed.

**Comment by ERICXUCHI** [comment]
> In what sense does it still need this setting? Does it stop working you don't specify this setting? How exactly?

```
wavm version
WAVM version 0.0.0-prerelease
WAVM_ENABLE_RUNTIME:           true
WAVM_ENABLE_STATIC_LINKING:    false
WAVM_ENABLE_ASAN:              false
WAVM_ENABLE_UBSAN:             false
WAVM_ENABLE_TSAN:              false
WAVM_ENABLE_LIBFUZZER:         false
WAVM_ENABLE_RELEASE_ASSERTS:   false
WAVM_ENABLE_UNWIND:            true

```

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.31 (4fcbf0239ccca29771f9044c990b0d34fac6e2e7)
clang version 14.0.0 (https://github.com/llvm/llvm-project 8fa2394bad433558f3083cee158043e2fb66d781)
Target: wasm32-unknown-emscripten
Thread model: posix
```

We complie a `helloworld.c` by emscripten, then run the `a.out.wasm` by WAVM.
![image](https://user-images.githubusercontent.com/57583292/137255003-768fa1db-aa88-4042-801b-83298da0e70e.png)
Something wrong:
```
Module appears to be an Emscripten module, but does not have an 'emscripten_metadata' section. WAVM only supports Emscripten modules compiled with '-s EMIT_EMSCRIPTEN_METADATA=1'.
If this is not an Emscripten module, please use '--abi=<ABI>' on the WAVM command line to specify the correct ABI.
```
After I add `-s EMIT_EMSCRIPTEN_METADATA=1`, then WAVM reports `WAVM only supports Emscripten modules compiled with '-s STANDALONE_WASM=1'.`, after I add these two options, WAVM runs smoothly and print `Hello World` finally.

**Comment by sbc100** [comment]
Ah yes, it looks like wavm needs to have the check removed still. 

@AndrewScheidecker can you reply here when the check is removed and then I can go ahead and remove the metadata stuff from the emscripten side?
