### ISSUE TITLE
mktime does not modify std::tm input

### ISSUE THREAD

**Issue by jkae** [emscripten-core/emscripten#12241]
I think this is related to #2393

```
#include <ctime>
#include <iostream>
using namespace std;

int main() {
  tm t = { 0 };
  t.tm_sec = 212;
  t.tm_year = 119;
  t.tm_mday = 351;                     // January 351
  mktime(&t);
  printf("%.4d-%.2d-%.2dT%.2d:%.2d:%.2d Z\n", 1900 + t.tm_year, t.tm_mon + 1, t.tm_mday + 1, t.tm_hour, t.tm_min, t.tm_sec);
  return 0;
}

> 2019-01-352T00:00:212 Z
Expected output: 2019-12-18T00:03:32 Z
```
The above code functions in [g++.](https://tio.run/##bY/LTsMwEEX3/oqroqJUpGkcyqIN9ANYs0JIyHJMa1FPIj8WUdVvDzYghwVeXGmOZjxn5DCsj1JO040meQ6dwqP02qgDm4HunbdKmAMLTtMRJIxyg5AKznctY5o8jNBUrHBhgDfweMIFNa5tqitv3p2SkTW8yWRUwkbE@S4j04kxovsH3uK/t9ngWVAQdkw9ccp8Jtfi1q/SH4ONJh/FYlltu/Wyan7iJcU@B17faFGC7@oad7NJ@WvQU6S8/OMzl6c@5D5NZT7se7lVPlhC3bLrNH0B)
According to the C reference:
> If the conversion is successful, the time object is modified. All fields of time are updated to fit their proper ranges. time->tm_wday and time->tm_yday are recalculated using information available in other fields. 

This code works as expected in em++:
```
#include <ctime>
#include <iostream>
using namespace std;
int main() {
        tm t{0};
        t.tm_sec = 212;
        t.tm_mday = 351;
        t.tm_year = 119;

        time_t ms = mktime(&t);
        const tm lt = *localtime(&ms);
        printf("%.4d-%.2d-%.2dT%.2d:%.2d:%.2d Z\n",
                        1900 + lt.tm_year,
                        lt.tm_mon + 1,
                        lt.tm_mday + 1,
                        lt.tm_hour,
                        lt.tm_min,
                        lt.tm_sec);
        return 0;
}

> 2019-12-18T00:03:32 Z
```

Version `emcc (Emscripten gcc/clang-like replacement) 1.39.18 (a3beeb0d6c9825bd1757d03677e817d819949a77)`
(I don't know if this has been fixed recently, changelog has no entries for mktime)

**Comment by welchyd** [comment]
Nice job on providing a workaround ... looks like `mktime` and related functions `strpttime` `strftime` were changed at one point

```v1.35.18: 1/7/2016 - Fixed an issue with daylight saving time in mktime() (#4001)```

```v1.38.20: 11/20/2018 - Change `strptime()`'s handling of the "%c" to match that of `strftime()`.
   This is a breaking change for code which depends on the old definition of
   "%c".```

**Comment by welchyd** [comment]
I've had this issue as well

**Comment by kripken** [comment]
Sounds like `mktime` could call `localtime` right before returning, perhaps? That would be a simple fix in `src/library.js`, would one of you like to submit a PR @jkae @welchyd ?

**Comment by jkae** [comment]
I can do it. I've written and tested the fix, will just need to fork etc.

**Comment by kripken** [comment]
Sounds good, thanks @jkae !
