### ISSUE TITLE
List of functions emscripten imports/their purposes?

### ISSUE THREAD

**Issue by vedantroy** [emscripten-core/emscripten#12265]
I'm trying to create an alternate implementation of the emscripten JS runtime. Is there a list of functions that emscripten imports from the parent runtime?

I see some of the imports are WASI-imports, which I can find external documentation for. I'm more curious about things like:

- When is `__indirect_function_table` used?
- When is `setTempRet0` used?

Amongst other things. Is there any documentation on Emscripten's ABI?

**Comment by tlively** [comment]
In general Emscripten's interface with the wasm module is intentionally undocumented and unstable. We don't recommend assuming anything about it because it can change at any time (although in practice most of it doesn't change that frequently). So the short answer is that no, there is no documentation.

**Comment by kripken** [comment]
To add to that, things like `__indirect_function_table` and `__heap_base` are LLVM-isms (which might be documented there).

`setTempRet0` is used to store 32 bits of data on the side, for implementing 64-bit return values (the high 32 bits are stored on the side). But as @tlively said, this and other special JS calls are internal APIs for emscripten, and can change. The best docs for them are the source code, in `src/library*.js`.

You may want to use [standalone mode](https://v8.dev/blog/emscripten-standalone-wasm) which minimizes the amount of things used from JS.

**Comment by sbc100** [comment]
Yes, standalone mode is probably best way to go if trying to do this.

Others have attempted to do what you are doing although I'm not sure how much success they have had.

There was even an special metadata section called EMIT_EMSCRIPTEN_METADATA which was designed to give non-emscripen runtimes insight into the import/export ABI used by a given module: #7815.   However I'm currently trying to remove it now that we have STANDALONE_WASM mode: https://github.com/emscripten-core/emscripten/issues/12231
