### ISSUE TITLE
Is it better that pthread pool size can be set by javascript?

### ISSUE THREAD

**Issue by sky0014** [emscripten-core/emscripten#12266]
Now, it's set by compile arguments, once compiled, it can't be changed.

**Comment by sky0014** [comment]
We can use a `Module['pthreadPoolSize']` parameter to do that.

**Comment by kripken** [comment]
That is already possible, see `settings.js`:

https://github.com/emscripten-core/emscripten/blob/f9138f6ba1a72fe8ec7f6147cf1fe4d03462b181/src/settings.js#L1254-L1260

You can set that to `Module.something` or a global variable or some other thing.

**Comment by sky0014** [comment]
@kripken I got it, thanks!
