### ISSUE TITLE
ABORT_ON_WASM_EXCEPTIONS:  Crash stack is only one line on a crash on Chrome.

### ISSUE THREAD

**Issue by rickg-hcl** [emscripten-core/emscripten#12277]
I enabled the new ABORT_ON_WASM_EXCEPTIONS option in our build, and was happy that the Module['onAbort'] callback is called from worker threads.

The problem is that when handling the abort, the stack trace is only one line.
There's no real way to capture the full stack trace.

I suspect that it is due to the instrumentWasmExportsWithAbort() function calling abort with 

abort("unhandled exception: " + [ e, e.stack ]);

on Firefox, the whole stack is there, but on Chrome it is only one line.

**Comment by sbc100** [comment]
@tklajnscek ?

**Comment by tklajnscek** [comment]
Will check this in a bit...

**Comment by tklajnscek** [comment]
@rickg-hcl when I test this in Chrome with the following abort handler:
```
Module.onAbort = function(err) {
   console.log("ABORT - " + err);
}
```

I get this in debug:
```
ABORT - unhandled exception: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at testCrash (<anonymous>:wasm-function[5]:0x246)
    at wrapperCache.<computed> (http://localhost:8080/test2_dbg.js:1388:27)
    at Object.Module._testCrash (http://localhost:8080/test2_dbg.js:1697:75)
    at <anonymous>:1:8
```

So it looks like `err` is properly concatenated... can you paste the code you're using to log this and what exactly it logs?

Maybe it's only an issue in worker threads... I'll check that, but it's really late here today so it'll have to wait until Monday :)

**Comment by tklajnscek** [comment]
> can you paste the code you're using to log this and what exactly it logs?

@rickg-hcl?

**Comment by rickg-hcl** [comment]
I've been working on creating a standalone sample to reproduce this, but it's turning out to be more difficult than I expected.  If I can't get one soon, I'll close the issue.

**Comment by tklajnscek** [comment]
If you can't do a standalone sample it would be great if you could at least give me a bit more info:
- Compiler command line you use for the worker
- The raw console output when the abort happens

 Thanks!

**Comment by rickg-hcl** [comment]
After further research, I found that there was a code path that was truncating the string provided on Module['onAbort'] to 256 bytes.  Since we didn't get the whole stack before, it didn't matter but now it does..
The bottom line is that it was my problem and not yours..
Sorry for the trouble.

**Comment by tklajnscek** [comment]
No worries 😄
