### ISSUE TITLE
Collision of minified names

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#12271]
Note: I wasn't sure to create an issue in emscripten or binaryen. Please let me know if I should be creating this in binaryen.

I'm facing an issue now where the name of a function after minification collides with a name of an actual function.
The said minified name is "log".
Is there a way to avoid creating minified names that are real words? E.g. removing all vowels in minified names so that it has lesser chance of colliding with an actual function name?

**Comment by kripken** [comment]
Where is the collision? The main namespace, the Module object, something internal in wasm2js..?

In general collisions shouldn't be an issue in any of those, but there could be a bug. A testcase would be good.

**Comment by Mintyboi** [comment]
@kripken I have not gotten a reproducer from vanilla emscripten codebase. So it's a not a bug in emscripten per se.
We have some codes in our fork that contains a mapping of minified names to the actual functions and we do a reverse lookup on that map. That's where we see the collision.
But we got the minifications from binaryen.

**Comment by kripken** [comment]
Binaryen minified names shouldn't reach the global namespace, I don't think? Only the exports should, but those aren't minified? Sorry if I'm missing something obvious. Even without a reproducing testcase, more details could help understand what you mean @Mintyboi

**Comment by Mintyboi** [comment]
@kripken Nope, you're not missing anything.
It's what we did in an emscripten fork to minify even the exports so that we could reduce the size of the worker and wasm file. And we have a map from the minified names back to the mangled name so that we can reference back.

**Comment by kripken** [comment]
@Mintyboi Still not sure I follow...

Does what you do overlap with emscripten's own wasm import and export name minification? Or with what we run closure to do?

Maybe a little code sample could help me understand :smile:

**Comment by Mintyboi** [comment]
@kripken Yes, I think having some code will be best for us to be on the same page.
Please give me some time to get my changes into the latest master and I'll provide my branch and the output binaries.
Thank you for you patience thus far :)

**Comment by Mintyboi** [comment]
@kripken I manage to find out what I did that resulted in an error in the code.

Just some history in case you are wondering what I was trying to do.
Here are some code changes (non-functional) against v2.0.8: https://github.com/emscripten-core/emscripten/compare/2.0.8...Mintyboi:wip/mintyboi/sample-minification

Suppose if I have a JS function `ace` and a mapping file like this:
```
function _ace() {
 console.log("Just an ace function");
 return 1;
}

Module["mapping"] = {
 $: "free",
 A: "__cxa_free_exception",
 B: "__cxa_end_catch",
 C: "invoke_iiiiiiii",
 ............
 acd: "foo1",
 ace: "foo2",
 acf: "foo3",
 .............
};
```
My `ace` function happens to have a function pointer so a stub for it is created.
```
Module["_fp$ace$i"] = function() {
 var func = null;
 var minifiedName = getReverseMapping()["ace"]; /// Explanation1
 if (minifiedName) {
  // trying a function in the main module (fns in main module has been minified)
  func = Module["asm"][minifiedName];
 }
 // trying a function in the side module (fns in side module are NOT minified)
 if (!func) func = Module["asm"]["ace"];   /// Explanation2 !!! Collision happens here because we are calling function foo2
 if (!func) func = Module["_ace"];
 if (!func) func = Module["_ace"];
 if (!func) func = _ace;                   /// correct function that we are looking for
 var fp = addFunction(func, "i");
 Module["_fp$ace$i"] = function() {
  return fp;
 };
 return fp;
};
```

Explanation:
Explanation1 - Because the functions in the main module are minified, we have to do a reverse lookup of the map in case the function exists in the main module.
Explanation2 - ***Issue*** I should not calling this line here since all the functions in main module are minified. Removing this line should work.

**Comment by Mintyboi** [comment]
Just to take a step back as well.
Is what I'm trying to do (minifying imports and exports for main module) actually something that would work? Are there other parts that I'd have to take into considerations?

**Comment by sbc100** [comment]
Until your last two comments I had not realized your were refering to MAIN_MODULE/SIDE_MODULE builds here.

Are you using MAIN_MODULE=2?   If you are worried about the size of your MAIN_MODULE then switching to MAIN_MODULE=2 will be a much bigger win for you. 

If you are already using `MAIN_MODULE=2` and you want to save space by minifying the remaining names that is something we do not support right now at all.    The main reason is that it would require all the SIDE_MODULES and the MAIN_MODULE to agree on the mapping and currently that is not possible (since they SIDE_MODULES and the MAIN_MODULE are build separately, in theory they could even be built by different ppl).     If that is your goal perhaps we can open a seperate issue with a more specific name like `Enable import/export minification for dyanmic linking".

Note: The API for MAIN_MODULE and SIDE_MODULE exports recently changed BTW.  You might want to update to the latest emscripten version before proceeding.  These days we don't use `fp$` or `g$` accessors anymore but instead we use mutable global imports of the form `GOT.mem.YY` and `GOT.func.XX.

**Comment by Mintyboi** [comment]
Will be creating another issue, if required, for supporting import/export minification for dynamic linking
