### ISSUE TITLE
Feature request sysconf( _SC_PHYS_PAGES)

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#12287]
Would it be possible to implement `sysconf( _SC_PHYS_PAGES)` as either INITIAL_MEMORY / PAGE_SIZE, or if INITIAL_MEMORY not  specified, then MAXIMUM_MEMORY / PAGE_SIZE? If neither specified then return -1 as now.

**Comment by yowl** [comment]
Obviously for ALLOW_MEMORY_GROWTH, something extra would be required

**Comment by sbc100** [comment]
I guess we could use __builtin_wasm_memory_size to implement a kind of polyfill for this.  Patches welcome!
