### ISSUE TITLE
Asyncify not behaving synchronously starting with emscripten 2.0.3

### ISSUE THREAD

**Issue by woodser** [emscripten-core/emscripten#12295]
I have been [using Asyncify.handleSleep() in my project](https://github.com/monero-ecosystem/monero-javascript/blob/fefcae6c360cc8fedf3e5afa3678d755b4bf517d/src/main/cpp/http_client_wasm.cpp#L19) successfully for over a year.

Updating emscripten from **2.0.2** to **2.0.3** causes Asyncify to no longer behave synchronously.  Instead, the C++ main thread resumes as soon as an async instruction is executed in 2.0.3.

Linker flags:
`-- EMCC_LINKER_FLAGS_CORE -Wall -Werror -std=c++11 -Oz --bind -s MODULARIZE=1 -s 'EXPORT_NAME="monero_javascript"' -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ASSERTIONS=2 -s EXIT_RUNTIME=0 -s PRECISE_F32=1 -s EXCEPTION_DEBUG=0 -s DEMANGLE_SUPPORT=0 -s NO_DYNAMIC_EXECUTION=0 -s NODEJS_CATCH_EXIT=0 -s RESERVED_FUNCTION_POINTERS=5 -s EXTRA_EXPORTED_RUNTIME_METHODS='["UTF8ToString","stringToUTF8","lengthBytesUTF8","intArrayToString","makeBigInt","getTempRet0","addFunction"]' -s WASM=1 -s ALLOW_MEMORY_GROWTH=1  -s ASYNCIFY=1 -s 'ASYNCIFY_IMPORTS=["js_send_json_request","js_send_binary_request","emscripten_sleep"]'`
```

**Comment by sbc100** [comment]
Thanks for the report.  If you have time perhaps you bisect to find out which of these changes caused the failure:

https://github.com/emscripten-core/emscripten/compare/2.0.2...2.0.3

Also a full example of the failure would help whoever fixes this add a unittest to prevent such as failure recurring.

**Comment by woodser** [comment]
Sorry should have reported this in emsdk.  I'll bisect those commits and report back.

**Comment by woodser** [comment]
Comparing emsdk [2.0.2...2.0.3](https://github.com/emscripten-core/emsdk/compare/2.0.2...2.0.3), the issue is introduced with https://github.com/emscripten-core/emsdk/commit/def6e4903ab0c5592aeab018716b367f61123677.  Guessing that updates emscripten from 2.0.2 to 2.0.3?

**Comment by sbc100** [comment]
You would need to get emscripten from git and bisect the range there while keeping 2.0.2 emsdk installed.

Simply putting your git version of emscripten first in the PATH should be enough to have it get used over the emsdk version.

**Comment by woodser** [comment]
The issue first appears with commit https://github.com/emscripten-core/emscripten/commit/43fcfd2938b72c57373a910ece897b27aa298852.

**Comment by sbc100** [comment]
Ah!  It looks like that issue might already have been fixed in #12273.  You you try `emsdk update-tags && emsdk install tot`?

@kripken should we do a 2.0.5 release tomorrow to get this fix published?

**Comment by woodser** [comment]
> you try emsdk update-tags && emsdk install tot

@sbc100 I'm seeing the same behavior after`emsdk update-tags && emsdk install tot`.

**Comment by kleisauke** [comment]
Perhaps the tip-of-tree build needs to be activated as well? Try running `emsdk activate tot`.

**Comment by woodser** [comment]
Actually `emsdk update-tags` gives error `failed to find build of any recent emsdk revision` and `emsdk install tot` gives error `Tip-of-tree information was not found, run emsdk update-tags` using a clean clone of emsdk.

**Comment by woodser** [comment]
Ah yes it's working after installing and activating tot.
