### ISSUE TITLE
Document that PTHREAD_POOL_SIZE accepts JS expressions

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#12302]
`PTHREAD_POOL_SIZE` was made to accept arbitrary JS expressions back in https://github.com/emscripten-core/emscripten/pull/10263, but not documented.

I feel it's important to call out in docs that you can use `navigator.hardwareConcurrency` in that context as that's, arguably, one of the most useful values for multi-threaded apps.

**Comment by kleisauke** [comment]
Note that `navigator.hardwareConcurrency` is not available on Node. So perhaps it should be documented that one can use `_emscripten_num_logical_cores()`?
https://github.com/emscripten-core/emscripten/blob/5dac884e6c04803c1ac1effc441287f3ae3d9625/src/library_pthread.js#L561-L566

**Comment by RReverser** [comment]
Oh, good idea. Is it available from a global scope though / can you use it in that param?

**Comment by kleisauke** [comment]
It's available in the global scope, you only have to precede that function with `_`. I'm using it without problems [here](https://github.com/kleisauke/wasm-vips/blob/8f43b170602d1b026ff78a22d04159682ac82d5c/src/CMakeLists.txt#L105). However, I'm not sure how it behaves with the closure compiler (haven't tested that yet).

**Comment by RReverser** [comment]
Hmm I guess it would work but @kripken might know more.

**Comment by kripken** [comment]
Yes, that should be safe to do, good idea! You'd also need to export it though so it's included in the build, I think.

**Comment by RReverser** [comment]
Showed this to @bmeurer today and sounds like he would appreciate this too :) If nobody gets around, I'll document this myself after [undefined time spent on existing tasks].
