### ISSUE TITLE
Have wasm modules export their memory rather than import it.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#12315]
This was already done for the indirect function table (wasmTable) in #12296 and is a nice win for code size, portability and complexity.

The only reason we couldn't do this before was that JS used to be able to make static allocation and change the memory size and a layout *after* wasm-ld was run.   All that has now been removed the memory layout is now set at wasm-ld time which means that it should be able to create and export the memory to JS.

**Comment by sbc100** [comment]
The downside of this is that it means that supplying wasmMemory or INITIAL_MEMORY at runtime will no longer be supported.

**Comment by sbc100** [comment]
This seems like it could be controversial .. there could be folks out there relying on it.

For this reason I think I will start doing it for MINIMAL_RUNTIME mode, which already doesn't support runtime memory setting from the output.

**Comment by curiousdannii** [comment]
Would making importing memory be opt-in be a good option?

**Comment by sbc100** [comment]
I may be that we have to do that... but adding more options has a real const to emscripten maintainers so I'd really rather not do it unless we really need to.     One of my biggest ongoing goal with emscripten is to reduce the number of options .. and therefore increase test coverage of the options space.
