### ISSUE TITLE
RuntimeError: unreachable when calling imported function in standalone mode

### ISSUE THREAD

**Issue by vedantroy** [emscripten-core/emscripten#12322]
When importing a JS function from C & calling it in standalone mode, I get an unreachable error (WASM execution hit an "unreachable" statement).

Here's the reproduction:

```c
void import_from_js();

int main() {
    import_from_js();
    return 0;
}
```

```javascript
(async () => {
    const { instance } = await WebAssembly.instantiateStreaming(fetch("./sample.wasm"), {
        env: {
            import_from_js: () => {
                console.log("Hello World!")
            }
        },
        wasi_snapshot_preview1: {
            proc_exit: (code) => {
                console.log(code)
            }
        }
    })
    await instance.exports._start()
})()
```

The command: `emcc sample.c -o sample.wasm -s ERROR_ON_UNDEFINED_SYMBOLS=0`.

Emscripten version: emcc (Emscripten gcc/clang-like replacement) 2.0.4 (3047b77ed244ea8f3cb3ee7b18c0f89079ae6554)

**Comment by sbc100** [comment]
I think we figured this out on discord.   proc_exit is supposed to never return.  You need to `throw` or exit the process or something like that.

I think llvm inserts and `unreachable` instruction after a call to any C/C++ function marked `noreturn` which `__wasi_proc_exit` is: https://github.com/emscripten-core/emscripten/blob/001417595fcc5fb4825db8abf84fd0196255f2db/system/include/wasi/api.h#L2604
