### ISSUE TITLE
Unicode issues in file_packager.py if by mistake data file and js file are redirected to the same file

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#12326]
It then fails with:
```
  File "/mnt/c/Users/user/emsdk/upstream/emscripten//tools/file_packager.py", line 940, in <module>
    sys.exit(main())
  File "/mnt/c/Users/user/emsdk/upstream/emscripten//tools/file_packager.py", line 925, in main
    old = f.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte`
```

It could fail better or show a relevant error message.

**Comment by sbc100** [comment]
I wonder if this could somehow relate to the fact that it look like you using the windows version emsdk on a linux system?  I can't see why that would be but its certtainly and unusual setup and not known to work.

Can you try installing the linux version of emsdk rather than mounting the windows version on linux?

**Comment by sbc100** [comment]
Sorry ignore my previous comment.  Can you show what command line is needed to make this happen so we can write a test for it?

**Comment by vadimkantorov** [comment]
Yep, I'll do.

For now, it was just file_packager.py some_file.js --js-output=some_file.js (and some of my data files were not UTF-8 representable, but anyway that should be an error)

**Comment by sbc100** [comment]
Thanks.  Does this only happen when running file_packager.py directly, or did you notice it when file_packager was run internally from the compiler driver?

**Comment by vadimkantorov** [comment]
I ran it manually, hence made this mistake of passing js path twice. I think it cannot happen if run internally
