### ISSUE TITLE
CI failures on macOS related to using of native clang

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#12331]
Looks like the following two tests started failing in the last 24 hours due to some change outside of the repo:

- test_wasm2c_reactor
- test_cmake_compile_features

Both these changes try to use native clang to build a native binary so suspect something changes with the underlying xcode installation.

**Comment by sbc100** [comment]
I suggest we disable those two tests on macOS until we can get to the bottom of it.

**Comment by sbc100** [comment]
See https://app.circleci.com/pipelines/github/emscripten-core/emscripten/8247/workflows/d7085b0a-f78e-4720-94f4-aaccef522fed/jobs/360410

**Comment by kripken** [comment]
I'm not familiar with MacOS that much. Yeah, if no obvious quick fix, sgtm to disable for now.

**Comment by sbc100** [comment]
On further investigation it looks like an upstream llvm change that broke us. Tracking it down now.

**Comment by sbc100** [comment]
Hmm.. it looks like our bundled clang started exhibiting this bug, but the llvm revision is identical:

Broken clang from emscripten-release revision ee8d9b047084f5214aed9a06b8f5932a1a7eac6d
```
static:emsdk distiller$ upstream/bin/clang  -v
clang version 12.0.0 (/opt/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project af1d3e655991e5f0c86df372b8583a60d20268e0)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Users/distiller/emsdk/upstream/bin
```

Good clang from two revisions prior: d6f40a87182d556c70b1a1a9cf5e84d33ad08cac  (not that llvm did *not* roll in those two revisions):

```
static:emsdk distiller$ good/bin/clang  -v
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project af1d3e655991e5f0c86df372b8583a60d20268e0)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Users/distiller/emsdk/good/bin
````

See how the llvm version is identical...

**Comment by sbc100** [comment]
I tracked it down to llvm being built with a different definition of HOST_LINK_VERSION:  https://github.com/llvm/llvm-project/blob/e55410f8b260a2868d600ca99fe5ee80f9cd4fc5/clang/lib/Driver/Driver.cpp#L420

In the working release (2.0.4) this value seems to be 409.23 (because I see `-target-linker-version 409.12` in the clang -cc1` argument list). 

In the tot version it seems to be set to 609.

Now sure if its its worth investigating further...

**Comment by dschuff** [comment]
can we try to undef HOST_LINK_VERSION when we build clang?

**Comment by dschuff** [comment]
but agreed that this isn't worth investing too much time into, since it's really just a few of our tests that ever use this clang as a native builder. Arguably we should not even compile the x86 backend into LLVM, and our tests should arguably also just not do that.

**Comment by sbc100** [comment]
Yeah we should probably just assume system clang for those tests instead of using our bundled one.
