### ISSUE TITLE
Unclear linking error when building with -flto

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#12334]
Many TexLive dependencies compile and link well with `-flto`, but compiling TECkit gives this mysterious error (no error message). Without "-flto", everything succeeds.

```
/mnt/c/Users/user/emsdk/upstream/emscripten/em++ -Wreturn-type -Wno-write-strings -g -O2   -o teckit_compile TECkit-src/source/Sample-tools/TECkit_Compile.o libTECkit_Compiler.a /mnt/c/Users/user/busytex/build/wasm/texlive/libs/zlib/libz.a

em++: error: '/mnt/c/Users/user/emsdk/upstream/bin/wasm-emscripten-finalize --detect-features -g --global-base=1024 --dwarf /tmp/emscripten_temp_w4_0a8lj/teckit_compile.wasm -o /tmp/emscripten_temp_w4_0a8lj/teckit_compile.wasm.o.wasm' failed (-6)
```

**Comment by sbc100** [comment]
Thats not a linker error per-say, its crash in binaryen's wasm-emscripten-finalize.

Could you attach the input file that its crashing on?  (Use EMCC_DEBUG_SAVE=1 or EMCC_DEBUG=1 when linking to save the intermediate files).

**Comment by vadimkantorov** [comment]
For now attaching output of `strace -f ...`
[log.txt](https://github.com/emscripten-core/emscripten/files/5279447/log.txt)

Now running your suggestion

**Comment by vadimkantorov** [comment]
[emcc_debug.txt](https://github.com/emscripten-core/emscripten/files/5279458/emcc_debug.txt)

**Comment by sbc100** [comment]
What we need is the wasm input file (e.g.  /tmp/emscripten_temp_w4_0a8lj/teckit_compile.wasm from your original example).

**Comment by vadimkantorov** [comment]
EMCC_DEBUG_SAVE=1 seems to not create anything
```
vadimkantorov@DESKTOP-4UF8FID:/mnt/c/Users/user/busytex/build/wasm/texlive/libs/teckit$ EMCC_DEBUG_SAVE=1 /mnt/c/Users/user/emsdk/upstream/emscripten/em++ -Wreturn-type -Wno-write-strings -g -O2   -o teckit_compile TECkit-src/source/Sample-tools/TECkit_Compile.o libTECkit_Compiler.a /mnt/c/Users/user/busytex/build/wasm/texlive/libs/zlib/libz.a
em++: error: '/mnt/c/Users/user/emsdk/upstream/bin/wasm-emscripten-finalize --detect-features -g --global-base=1024 --dwarf /tmp/emscripten_temp_em3hfude/teckit_compile.wasm -o /tmp/emscripten_temp_em3hfude/teckit_compile.wasm.o.wasm' failed (-6)
not cleaning up temp files since in debug-save mode, see them in /tmp
not cleaning up temp files since in debug-save mode, see them in /tmp
not cleaning up temp files since in debug-save mode, see them in /tmp
not cleaning up temp files since in debug-save mode, see them in /tmp
vadimkantorov@DESKTOP-4UF8FID:/mnt/c/Users/user/busytex/build/wasm/texlive/libs/teckit$ ls /tmp
apt-dpkg-install-cXecsl  dotnet-installer  pip-bbaybj9i-unpack  tmp6bgqioor
vadimkantorov@DESKTOP-4UF8FID:/mnt/c/Users/user/busytex/build/wasm/texlive/libs/teckit$
```

**Comment by sbc100** [comment]
Yeah I think there are few different temp file handling systems in place.  EMCC_DEBUG should do that trick.  It should use the canonical temp directory `/tmp/emscripten_temp` rather than the random one.

**Comment by vadimkantorov** [comment]
[emscripten_temp.zip](https://github.com/emscripten-core/emscripten/files/5279491/emscripten_temp.zip)

**Comment by kripken** [comment]
Does the command fail for you on the provided file? I don't see a crash locally.

If this uses DWARF, it may be a DWARF crash bug that was recently fixed, #3158

If it still fails for you, maybe run it in a debugger or valgrind to get a stack trace?

**Comment by vadimkantorov** [comment]
Yes, em++ command fails for me. If bundling just the *.o and *.a files would do, I can upload them. But it's a good idea, I'm still running 2.0.0.

#3158 seems to be from 2015.

**Comment by vadimkantorov** [comment]
[Uploading teckit.zip…]()

**Comment by vadimkantorov** [comment]
For me this happens even on 2.0.4

**Comment by vadimkantorov** [comment]
dwarf seems to be used maybe, yes

**Comment by kripken** [comment]
Oops, it was in another repo, sorry - https://github.com/WebAssembly/binaryen/pull/3158

That's not in a release yet. You can test with `emsdk install tot` for a tip of tree build.

**Comment by vadimkantorov** [comment]
Will, try now. Yes, this crashes for me:
``` 
/mnt/c/Users/user/emsdk/upstream/bin/wasm-emscripten-finalize --detect-features --minimize-wasm-changes -g --dyncalls-i64 --global-base=1024 --dwarf /tmp/emscripten_temp/teckit_compile.wasm -o /tmp/emscripten_temp/teckit_compile.wasm.o.wasm
```

**Comment by kripken** [comment]
That's on the `tot` build?

Is there no other crash info? Please run it in valgrind or a debugger to get a stack trace.

**Comment by vadimkantorov** [comment]
`tot` fixed it!

**Comment by vadimkantorov** [comment]
I ran it on WSLv1, and it doesn't seem to be saving any crash dumps, but I can probably figure it out if needed. Please Let me know if I should still do that, or if `tot` can call the case closed

**Comment by kripken** [comment]
Oh good, thanks! If it works on `tot` then it's probably that issue I linked, and nothing more needs to be done.

**Comment by vadimkantorov** [comment]
The `tot` version now hangs indefinitely at some `checking whether the C compiler works...` checks

**Comment by sbc100** [comment]
Sounds like a different issue.
