### ISSUE TITLE
[USAGE] unknown file type

### ISSUE THREAD

**Issue by Genuifx** [emscripten-core/emscripten#12344]
`emcc -v `

```sh
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.2
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 77152a6b7ac07ce65568d7c69305653e7cad4bb0)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

when i run `emcc ffmpeg.bc -o ffmpeg.html` then get an error:

`wasm-ld: error: unknown file type: ffmpeg.bc`

**Comment by sbc100** [comment]
How did you build `ffmpeg.bc`?  What type if file is `ffmpeg.bc`?  (You can run `file ffmpeg.bc` to find out if you are on macOS or linux).

**Comment by Genuifx** [comment]
`ffmpeg.bc: ASCII text, with very long lines`

Have a see at https://github.com/Kagami/ffmpeg.js/blob/1eef77e5cfde211d4b8ac282a450f1ffe4fdba79/Makefile#L188

I run with 
```shell
emconfigure /path/to/FFmpeg/configure \
    --cc=emcc \
    --ar=emar \
    --ranlib=emranlib \
    --target-os=none \
    --enable-cross-compile \
    --disable-pthreads \
    --disable-w32threads \
    --disable-os2threads \
    --disable-doc \
    --enable-ffmpeg \
    --enable-avcodec \
    --enable-avformat \
    --disable-network \
	--disable-d3d11va \
	--disable-dxva2 \
	--disable-vaapi \
	--disable-vdpau \
    --disable-everything \
    --disable-bzlib \
	--disable-iconv \
	--disable-libxcb \
	--disable-lzma \
	--disable-sdl2 \
	--disable-securetransport \
	--disable-xlib \
    --disable-stripping \
    --disable-x86asm \
    --disable-inline-asm \
    --disable-asm \
    --disable-devices  \
    --disable-hwaccels --disable-parsers --disable-bsfs \
    --disable-debug --disable-protocols --disable-indevs --disable-outdevs --enable-protocol=file
```

then `cp ffmpeg ffmpeg.bc`.  @sbc100  `ffmpeg.bc` is generated here.

**Comment by jinzhuming** [comment]
I'm having the same problem.

```
cp ffmpeg ffmpeg.bc
emcc -s ASSERTIONS=1 -s VERBOSE=1 -s TOTAL_MEMORY=256mb -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -O2 -v ffmpeg.bc -o ./ffmpeg.js --pre-js ./ffmpeg_pre.js --post-js ./ffmpeg_post.js
```
![log](https://raw.githubusercontent.com/jinzhuming/oss/master/uPic/JI0Bsp.png)

**Comment by sbc100** [comment]
ffmpeg is an executable not a library, and emscripten generated JavaScript executables so `ffmpeg` is a JavaScript file and this cannot then be linked into another applications.

I assume you are trying to use ffmpeg as a library?  If so you probably want to instead link your program against libavcodec.a and other libraries that are part of ffmpeg.

**Comment by jinzhuming** [comment]
it is working:
[build_wasm](https://github.com/jordiwang/web-capture/blob/master/doc/build_wasm.sh)

`cp ffmpeg ffmpeg.bc` is an error operation, ffmpeg cannot be compiled. @Genuifx 

thank you, too  @sbc100

**Comment by Genuifx** [comment]
@sbc100 Noop, I not writing c++, I just wanna run FFmpeg at web platform. 

so, the only thing I need to do is load the generated `ffmpeg_g` and `ffmpeg_g.wasm` directly? 

btw. 
what the difference between `ffmpeg` and `ffmpeg_g`?  
why not rename `ffmpeg` to `ffmpeg.js`?

**Comment by sbc100** [comment]
Yes, renaming ffmpeg to ffmpeg.js would make sense to me.

I imagine the `_g` could be perhaps a debug build (since -g is the flag to include debug info), but I can't be sure, that is something specific the the ffmpeg build system.

**Comment by Genuifx** [comment]
awesome, thanks for your amazing work.
