### ISSUE TITLE
-lproxyfs.js doesn't include PROXYFS

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#12351]
I'd like to use PROXYFS within a WebWorker to skip re-init of file system and data package reloading.

Specifying `-lproxyfs.js` doesn't lead FS.filesystems to have PROXYFS
OTOH, specifying `-lworkerfs.js` does work, and indeed FS.filesystems has WORKERFS now

Specifying `-s EXPORTED_RUNTIME_METHODS=["PROXYFS"]` leads to `ReferenceError` at `Module["PROXYFS"]=PROXYFS;` at module initialization time

I'm not sure how https://github.com/emscripten-core/emscripten/blob/d021a984b8909b78b1cdd653c0fb302383a31306/tests/test_other.py#L2527 passes, I don't have any traces of PROXYFS when I use `-lproxyfs.js`. Do I need to specify some extra arguments in my compilation command?

**Comment by sbc100** [comment]
I does look like maybe proxyfs is missing here: https://github.com/emscripten-core/emscripten/blob/d021a984b8909b78b1cdd653c0fb302383a31306/src/library_fs.js#L1467

Perhaps there is a reason for this?  @kripken @juj ?

**Comment by vadimkantorov** [comment]
It's not added to Module.PROXYFS either. Seems even local PROXYFS object is not created, and hence it's not available anywhere

**Comment by vadimkantorov** [comment]
Is this test enabled?

**Comment by sbc100** [comment]
The test does currently pass due to other flags that is uses.    However I have a fix not that cleans that up and make it work as expected.

**Comment by vadimkantorov** [comment]
Cool. BTW, what other flags do make it work at the moment?

**Comment by vadimkantorov** [comment]
Oh, I see: `Remove EXPORT_ALL and MAIN_MODULE from test_proxyfs in favor
of being more precise in what we want to export.` :0

**Comment by vadimkantorov** [comment]
After this PR, it will appear on FS.filesystems, right?

**Comment by sbc100** [comment]
Yes, please don't copy the `MAIN_MODULE` + `EXPORT_ALL` hack.. that seems like missive overkill and misuse of `MAIN_MODULE` to boot.

**Comment by sbc100** [comment]
> After this PR, it will appear on FS.filesystems, right?

Yes

**Comment by vadimkantorov** [comment]
What is emscripten's process for CI? When is this commit landing in tip-of-tree? Is it nightly builds?

**Comment by sbc100** [comment]
We build releases continuously here: https://ci.chromium.org/p/emscripten-releases

You can install the latest release using `./emsdk upsdae-tags && ./emdk install tot`

**Comment by vadimkantorov** [comment]
@sbc100 Is there a way to enable tracing of FS calls?

After enabling proxying, I started to get `DVI: Invalid argument`:
```
xdvipdfmx | stderr: example.xdv -> example.pdf
xdvipdfmx | stderr: /bin/busytex: DVI: Invalid argument
```

This must be related to proxied file access.

E.g. I noticed that `FS.lookupPath('/some/directory').node.contents` breaks or returns null for proxied directory.

**Comment by vadimkantorov** [comment]
E.g. xdvidpfmx does absolute file seek. Is it supported by PROXYFS?

**Comment by vadimkantorov** [comment]
I think I identified the problem with PROXYFS+seek and created an issue: https://github.com/emscripten-core/emscripten/issues/12367

Otherwise, does emscripten support piping input to stdout? This would force dvipdfmx into not doing seek.
