### ISSUE TITLE
Avoid implicitly skipping tests when, for example, d8 is missing

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#12369]
We should have a way for users who don't want to install d8 to continue to run the test suite but we should not just implictly skip over the tests that depend on d8 (e.g. all the SIMD tests).

Instead we should have a envronment variable or command line option that such users can use. e.g. `EMTEST_NO_D8`.

**Comment by sbc100** [comment]
If anyone wants this please take it :)

**Comment by DhairyaBahl** [comment]
I would like to work on this issue. Kindly assign it to me.

Thanks

**Comment by DhairyaBahl** [comment]
@sbc100 Can you guide me a bit. I have installed emsdk from github to run emscripten in my local environment but I am having few difficulties. I am unable to run any command in emsdk. I have read contributing.md and readme file about emsdk but unable to solve errors. 

Thanks :)

**Comment by sbc100** [comment]
It looks like we already have a potential fix in #12392 .. sorry I didn't see that earlier.

**Comment by DhairyaBahl** [comment]
@sbc100 No probs  :)

**Comment by DhairyaBahl** [comment]
@sbc100 Kindly remove me from the assignee. I am not working on the issue. Thanks :)


> It looks like we already have a potential fix in #12392 .. sorry I didn't see that earlier.

**Comment by kainino0x** [comment]
This seems to have been fixed by #14381.
(stumbled on this issue trying to figure out how to make emtest pick up the d8 that I have installed)
