### ISSUE TITLE
Windows End of Line (CRLF) Confuses Linux

### ISSUE THREAD

**Issue by Albirair** [emscripten-core/emscripten#12379]
Linux assumes the **carriage return** at the end of the first line of any script part of the targeted shell name, thus it prints error messages stating "**bad interpreter** ".
The problem appeared from the start when trying to install _Emscripten_, to solve it I had to manually remove the carriage returns in the file _install.py_.

**Comment by sbc100** [comment]
What would your `install.py` have windows endings?  Did you do the checkout on windows?

**Comment by sbc100** [comment]
The fix is it to do you git checkout on linux if you are using linux... or to run install.py explicitly via `python install.py`
