### ISSUE TITLE
Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by flatmax** [emscripten-core/emscripten#12377]
The browser is having trouble with the "import.meta.url" line in the binded emscripten module :
```
var namedModule = (function() {
  var _scriptDir = import.meta.url;

```
I am importing my module like so :
```
    this.moduleName='namedModule';
    let script = document.createElement('script');
    script.src = this.moduleName+'.js';
    document.head.appendChild(script);

```
The error reported is :
`Uncaught SyntaxError: Cannot use 'import.meta' outside a module`

The binding command is :
	@emcc --bind --llvm-opts 1 --memory-init-file 0 --pre-js ./pre.js -s EXPORT_ES6=1 -s MODULARIZE=1 -s EXPORT_NAME="'namedModule'" -s SINGLE_FILE=1 -s "BINARYEN_METHOD='native-wasm'" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 $(AM_CXXFLAGS) .libs/namedModule.so $(GTKIOSTREAM_LIBS) -o .libs/namedModule.js

Any ideas on how to change the binding or loading mechanism to fix this problem ?

**Comment by curiousdannii** [comment]
Don't use EXPORT_ES6 if you don't intend to load it as an ES6 module. :)

**Comment by flatmax** [comment]
Yep - that works ! Thanks.
