### ISSUE TITLE
Don't install optional npm dependencies?

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#12406]
Following on from https://github.com/emscripten-core/emsdk/pull/625

The platform specific Closure Compiler packages are now huge - adding about 180MB to the compressed download size of emsdk.

But these platform specific packages are marked as optional, so it should be possible to exclude them.

They are present in the package-lock.json file - I don't know if that is being automatically or manually updated.

It's possible there are other optional dependencies which are actually required, so they may need to be manually listed as dependencies on.

**Comment by sbc100** [comment]
Is generated by `npm`.    I imagine this is an issue with upstream google-closure-compiler which grew is size in a way that seems like it must be bug.

If you think we are not managing the `package-lock.json` please advise, but its not manually edited no.

**Comment by sbc100** [comment]
interesting.. it looks like that command we use in emsdk (`npm ci`) does install optional deps, but the normal `npm install` does not.

I wonder what risks if any there would be in using `npm install` over `npm ci`?

**Comment by sbc100** [comment]
I just found `npm ci --no-optional`... certainly makes a huge differece:

```
$ npm ci
$ du -sm node_modules/
645	node_modules/
$ npm ci --no-optional
$ du -sm node_modules/
45	node_modules/
```

Wow... can that be real.

**Comment by sbc100** [comment]
Looks like that mode skips all the native closure compiler builds :(

Looks like just `npm install` does the right thing and just install the `linux` one.. kind a half way between the `npm ci` options:

```
$ npm install
du -sm node_modules/
333	node_modules/
```

**Comment by curiousdannii** [comment]
My understanding (rather limited) is that `npm ci` just looks at package-lock.json, whereas npm install looks at both it and package.json. I hadn't noticed that package-lock.json does say whether a package is optional or not, so that seems like a good option. And, these closure compiler packages are the only optional ones, so nothing else will break unexpectedly. :)

Will making a change to how emsdk installs the packages be tested in this repo's CI?

**Comment by sbc100** [comment]
Yes CI covers that.

**Comment by curiousdannii** [comment]
The Dockerfile only needs to cover linux right? What if it manually installed `google-closure-compiler-linux` after `npm ci --no-optional`? That would cut ~90MB from the compressed size.

**Comment by curiousdannii** [comment]
With my PR reverted we'll need another solution for this.

**Comment by sbc100** [comment]
Can you reland with the extra architecture check?  Should take care of it.

**Comment by curiousdannii** [comment]
Okay, that turned out to be not so difficult.
