### ISSUE TITLE
Update the documentation for the "allocate" function

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emscripten#12427]
In the documentation, `allocate` has the  signature `allocate(slab, types, allocator, ptr)`
 
> source: https://emscripten.org/docs/api_reference/advanced-apis.html?highlight=allocate#allocate

However, it looks like the `type` argument has been removed : 

https://github.com/emscripten-core/emscripten/blob/2.0.5/src/preamble.js#L205-L236

**Comment by lovasoa** [comment]
Thanks @kripken 👍

**Comment by kripken** [comment]
@nokotan did the work :smile: Thanks again!

And thanks for filing this issue so it got fixed @lovasoa !
