### ISSUE TITLE
Read a va_arg when there isn't one / fcntl reading from address 0

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#12433]
fcntl begins with
```c
int fcntl(int fd, int cmd, ...)
{
	unsigned long arg;
	va_list ap;
	va_start(ap, cmd);
	arg = va_arg(ap, unsigned long);
	va_end(ap);
```
It is valid to call `fcntl(x, y);` that is, without the third parameter. In that case, the wasm code receives a `0` for the last parameter that usually points to the varargs buffer. So this musl code ends up reading an `unsigned long` from address 0, which `SAFE_HEAP` marks as an error.

Other notes: This does not error in asan mode as asan ends up not instrumenting that load for some reason. This musl code is unchanged in upstream.

Is this a musl bug? Or is it a bug in wasm's codegen? Or is it somehow valid to emit this, and SAFE_HEAP must somehow know not to instrument it?

**Comment by sbc100** [comment]
Based on reading the man page for `fcntl` and for `va_arg` it looks like a bug to me:

fcntl:

```
fcntl() can take an optional third argument.  Whether or not this argument is required is  determined  by cmd.
```

It looks like fcntl should look at cmd first before deciding to try read any thing from va_list.

And va_arg:

```
If  there is no next argument, or if type is not compatible with the type of the actual next argument (as
promoted according to the default argument promotions), random errors will occur.
```

So it sounds like calling va_arg when there is nothing to read is undefined behaviour.

**Comment by sbc100** [comment]
Any idea why this error shows up with `SAFE_HEAP` but not with `asan`?  Is it because the load inside `va_arg` is invisible to asan somehow?

**Comment by kripken** [comment]
On a testcase both ASan and `SAFE_HEAP` error on a null pointer use:
```cpp
#include <stdarg.h>
#include <stdio.h>

void foo(int a, ...)
{
	int arg;
	va_list ap;
	va_start(ap, a);
	arg = va_arg(ap, int);
	va_end(ap);
	if (a) printf("%d : %d\n", a, arg);
	else printf("zero\n");
}

int main() {
  // Make some calls with an extra arg.
  foo(10, 100);
  foo(20, 200);

  // Make a call without.
  foo(0);
}
```
The same happens with actual fcntl. Perhaps we don't run ASan on all of libc? Or maybe I didn't measure properly back then. Anyhow, no difference now.

**Comment by kripken** [comment]
..but the difference remains in libc. fcntl in libc does *not* error with ASan. It just generates different code in that case. Very odd. Maybe it has a literal workaround for this issue that checks the function name? Anyhow, not sure it's worth the time to dig into ASan source code...

**Comment by sbc100** [comment]
Perhaps libc is compiled with flags that somehow avoid the asan failure..  either way I think we should land #14026
