### ISSUE TITLE
Document COOP / COEP in Pthreads support

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#12472]
Browsers have agreed to gate shared memory support on COOP/COEP headers. Firefox has already shipped this in stable version, Chrome for Android will do this in M88 and Chrome for Desktop (which currently supports SAB unconditionally) will do this in M91.

We should at least document this requirement at the top of [Pthreads support](https://emscripten.org/docs/porting/pthreads.html) page so that users are not confused when their pthreads code is not working in a deployed environment.

Additionally, we might think of adding a console warning, but I'm not yet sure how to do that nicely in a way that it would be shown only when user hasn't already opted into COOP/COEP, and not every single time they compile & run the app.

**Comment by DhairyaBahl** [comment]
I would like to work on this issue. Kindly assign it to me. 

Thanks :)

**Comment by RReverser** [comment]
@DhairyaBahl Done, looking forward to a PR! Thanks.

By the way, please link to https://web.dev/coop-coep/ from the added warning for users looking for the expanded explanation.

**Comment by DhairyaBahl** [comment]
@RReverser Okay. I will refer that documentation as well. 

Thanks :)

**Comment by DhairyaBahl** [comment]
Sorry I mistakenly closed it. I will create a new one  :)

**Comment by DhairyaBahl** [comment]
@RReverser @sbc100 
Kindly look at the PR #12478 . That PR will close this issue. Kindly tell me if i have to make improvements in that PR.

Thanks

**Comment by DhairyaBahl** [comment]
@kripken @sbc100 @RReverser I've made the required changes. Kindly look forward to my PR #12540 .

Thank you for cooperation :)

**Comment by DhairyaBahl** [comment]
@kripken @RReverser Kindly Close this Issue as my PR is merged and I am removing myself from the assignees. 

Thanks :+1:

**Comment by RReverser** [comment]
> and I am removing myself from the assignees

Just for the future - there is no need to remove yourself from assignees when work is complete.

**Comment by DhairyaBahl** [comment]
@RReverser I am extremely sorry.. I was not aware about this... 

Thanks :)

**Comment by RReverser** [comment]
No worries, it doesn't break anything, just a tip to reduce work for yourself :)
