### ISSUE TITLE
EM_JS : unable to free const char* in cpp 

### ISSUE THREAD

**Issue by gauravgola96** [emscripten-core/emscripten#12496]
```
EM_JS(const char*, get_todo_item, (const char *str), {
        return Asyncify.handleAsync(async() => {
            const text = UTF8ToString(str);
            out("text >> " + text);
            let response = await fetch("https://jsonplaceholder.typicode.com/todos/1");
            response = await response.json();
            var lengthBytes = lengthBytesUTF8(jstring)+1;
            var stringOnWasmHeap = _malloc(lengthBytes);
            stringToUTF8(jstring, stringOnWasmHeap, lengthBytes);
            return stringOnWasmHeap;
        });
    });

int main()
    {       
        const char*  response = get_todo_item("4455454545");
        std::free( response);
        return 0;
    }

```
Got compilation error : `cannot initialize a parameter of type 'void *' with an lvalue of type 'const char *'
        std::free( response);
`
Also tried: `std::free((char *)response)` successful compilation but memory is not freed when checking with cout.

Followed documentaion from : [https://emscripten.org/docs/api_reference/emscripten.h.html#c.EM_JS](url)

**Comment by kripken** [comment]
To debug this, maybe add some logging before the free, to see what the pointer's value is, and whether that matches the malloc.

**Comment by Akaricchi** [comment]
> Also tried: std::free((char *)response) successful compilation but memory is not freed when checking with cout.

What do you mean by that exactly? Did you `free` the string, then successfully print it out? If so then that is not a valid test. Dereferencing a `free`'d pointer is undefined behavior, and it's not surprising that the memory allocator wouldn't overwrite the `free`'d memory immediately.

Also consider simply returning `char*` rather than `const char*` from your `EM_JS` function, then you won't have to cast anything.

**Comment by mmarczell-graphisoft** [comment]
Could the documentation be wrong on this? It says return `const char*`, but that cannot be `free`-d the way the example code does, because of the const.
