### ISSUE TITLE
create_context(Webgl2.0) -> get_attributes: Webgl2.0 -> GL_VERSION: Webgl1.0

### ISSUE THREAD

**Issue by 100xCoder** [emscripten-core/emscripten#12490]
EmscriptenWebGLContextAttributes atrs,verify;
emscripten_webgl_init_context_attributes(&atrs);
atrs.majorVersion = 2;
atrs.minorVersion = 0;
emctx = emscripten_webgl_create_context(id, &atrs);
assert(0<emctx); // true
assert(emscripten_webgl_make_context_current(emctx) == EMSCRIPTEN_RESULT_SUCCESS); // true
assert(emscripten_webgl_get_context_attributes(emctx,&verify) == EMSCRIPTEN_RESULT_SUCCESS); // true
std::cout << "Tried to create WebGL" << atrs.majorVersion << "." << atrs.minorVersion << std::endl;
std::cout << "Got WebGL" << verify.majorVersion << "." << verify.minorVersion << std::endl;
std::cout << "GL_VERSION=" << glGetString(GL_VERSION) << std::endl;

Output:

Tried to create WebGL2.0
Got WebGL2.0
GL_VERSION=OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium))

This as well in Chrome as in Firefox. In both, JavaScript canvas.getContext('webgl2') succeeds and getParameter(ctx.VERSION) shows expected WebGL 2.0 is current.

Built with: -s USE_WEBGL2=1.
I tried -s {MIN|MAX}_WEBGL_... and FULL_ES3=1 and all flags I thought may be relevant. Compilation gives neither warnings nor errors. C++ language. I tried disabling optimization, with the same result. I think emscripten must be to blame, since it happens in both browsers for me. Either that, or I'm missing some information. I finally must add that the context is indeed a WebGL 1.0 one, because no features associated with a 2.0 context are operational.

**Comment by kripken** [comment]
I don't see anything offhand. I would look in the test suite for similar code, that would be guaranteed to work, and comparing to it may be helpful.

Or, making a full standalone testcase here, that is easy to run, can help too.

**Comment by 100xCoder** [comment]
I found out what the problem was. I had been building using a makefile, and turning .cpp files into .o files as usual. Then, in the link step, I omitted the necessary WEBGL2.0 flags. Apparently, it's mandatory to pass them in the link step as well. All is peachy again.

**Comment by kripken** [comment]
Great, glad you figured this out!

(Yes, flags affecting JS, like WebGL, are important at link time.)
