### ISSUE TITLE
run npm install in make install to pull in html-minifier-terser

### ISSUE THREAD

**Issue by andres-erbsen** [emscripten-core/emscripten#12519]
I am just trying out emscripten and when I use emcc -O2 -o a.html (as in [this example](https://emscripten.org/docs/porting/asyncify.html#returning-values)) I get the following error:

`emcc: error: html-minifier-terser was not found! Please run "npm install" in Emscripten root directory to set up npm dependencies`.

I have installed emscripten using the Arch Linux [package](https://github.com/archlinux/svntogit-community/blob/packages/emscripten/trunk/PKGBUILD#L97), and experience suggests that it would be unwise to run npm install there. I contacted the package maintainer and was recommended to report this issue upstream instead, as make install should definitely also take care of that step. So, could the necessary `npm install` be added to `make install`?

**Comment by sbc100** [comment]
I seem to remember this issue being dealt with in the downstream package.  @svenstaro is the maintainer I believe.

Does the `node_modules` directory exist at all inside the packaged emscripten directory?

**Comment by svenstaro** [comment]
It does but the Makefile doesn't use npm and I can't find anywhere that documents that. I think the Makefile should just run `npm install` and we're good.

**Comment by sbc100** [comment]
Ah I see ..   do you think it makes sense to bundle the `node_modules` in the emscripten tar ball?  I guess maybe?

Either that or we could document it somewhere.  Currently `npm ci` (or `npm install`) is an expects post-install step that all git users are expected to run and that `emsdk` runs.     Maybe better to keep the emscripten tar archive small and document this in `packaging.md`.  

I also see that you have `acorn` as dependency but that should also come from our own node_modules instead I think (to get a precise version match).

**Comment by svenstaro** [comment]
I think since you have a makefile with an install step, it should also take care of running npm to make sure all required not modules are in place.

**Comment by sbc100** [comment]
I kind of agree.  We also use this install script to publish the downloadable tar archive though... and I don't really want to bloat them with node_modules (which can also contain platform specific stuff).

What do you think?  Should our downloadable tar releases contains the `node_modules` directory?   I kind of think of npm install as being a post install step for a user of the tar archive.

**Comment by sbc100** [comment]
Maybe `make dist` can exclude node_modules even though `make install` creates it?

**Comment by andres-erbsen** [comment]
What would be needed to move forward with this? (The last proposal sounds reasonable to me.)

**Comment by sbc100** [comment]
I don't personally have time to look at this right now .. if anyone wants to propose a patch it would be welcome.
