### ISSUE TITLE
Getting "Too many locals" while trying to compile a 1 million LOCs with assertions enabled 

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#12539]
It complains that it can't do live analysis due to the size of codebase

**Comment by sbc100** [comment]
What tool exactly is complaining?

**Comment by gerald-dotcom** [comment]
> What tool exactly is complaining?

It's Emscripten

It just say too many local vars thus can't do live analysis

**Comment by sbc100** [comment]
Can you include that actual full error output?

**Comment by gerald-dotcom** [comment]
Here it's,

```
warning: too many locals (73919) to run liveness analysis in 1540
warning: too many locals (66415Assertion failed: canRun(func), file C:\b\s\w\ir\cache\builder\emscripten-releases\binaryen\src\cfg/liveness-traversal.h, line 193) to run liveness analysis in em++
```

and

`error: 'C:/Users/Administrator/emsdk/upstream\bin\wasm-opt --strip-dwarf --safe-heap --post-emscripten --inline-main --no-exit-runtime --low-memory-unused --strip-debug --strip-producers --asyncify --pass-arg=asyncify-asserts --pass-arg=asyncify-imports@env.invoke_*,env.emscripten_sleep,env.emscripten_wget,env.emscripten_wget_data,env.emscripten_idb_load,env.emscripten_idb_store,env.emscripten_idb_delete,env.emscripten_idb_exists,env.emscripten_idb_load_blob,env.emscripten_idb_store_blob,env.SDL_Delay,env.emscripten_scan_registers,env.emscripten_lazy_load_code,env.emscripten_fiber_swap,wasi_snapshot_preview1.fd_sync,env.__wasi_fd_sync,env._emval_await --pass-arg=stack-pointer@5292096 --pass-arg=emscripten-sbrk-ptr@49040 myMain.wasm -o myMain.wasm --mvp-features' failed (3221226505)`

**Comment by kripken** [comment]
Looks like it's the liveness analysis. That's just a warning, though. Does it otherwise finish ok? From the error it looks like maybe not, so could be a separate issue.

You can run with `EMCC_DEBUG=1 BINARYEN_PASS_DEBUG=1` to get more logging information.

**Comment by gerald-dotcom** [comment]
> Looks like it's the liveness analysis. That's just a warning, though. Does it otherwise finish ok? From the error it looks like maybe not, so could be a separate issue.
> 
> You can run with `EMCC_DEBUG=1 BINARYEN_PASS_DEBUG=1` in the environment to get more logging information.

The error goes away if I try with say -O2 other than that it still there and stop compiling.

I'm trying to debug alignment fault & segmentation fault without using -O option

**Comment by gerald-dotcom** [comment]
Well, I tried to compile with -O2 with specific memory flag and at runtime, it throws following error

`RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #1625 failed: local count too large @+2667236)`


I'm going to find sometime and post logging info

**Comment by kripken** [comment]
There are limitations on how many locals a wasm VM will accept. You may need to find a way to reduce the number at the source level, if binaryen can't optimize them away. For example, maybe you can generate multiple functions instead of one huge one, or prevent inlining, etc.

**Comment by gerald-dotcom** [comment]
> There are limitations on how many locals a wasm VM will accept. You may need to find a way to reduce the number at the source level, if binaryen can't optimize them away. For example, maybe you can generate multiple functions instead of one huge one, or prevent inlining, etc.

With-Oz locals error go away but in return it gives alignment fault & segmentation fault 

So it's impossible to debug if WASM VM has limit since debug mode need non-optimized version.

**Comment by gerald-dotcom** [comment]
I put` std::cout << "hello world << "\n"` on top of main function of this big program and all memory errors suddenly disappeared.

I've seen the same behavior on https://github.com/emscripten-core/emscripten/issues/11774

**Comment by gerald-dotcom** [comment]
Closing this. Tweaked some flags and it all magically started to work.
