### ISSUE TITLE
EMIT_EMSCRIPTEN_METADATA broken since 2.0.5

### ISSUE THREAD

**Issue by PiotrSikora** [emscripten-core/emscripten#12552]
```
$ ./emsdk install 2.0.5 && ./emsdk activate 2.0.5 && source emsdk_env.sh
$ emcc -s EMIT_EMSCRIPTEN_METADATA=1 upstream/emscripten/tests/hello_world.c -o hello_world.wasm
Traceback (most recent call last):
  File "/home/piotrsikora/Google/emsdk/upstream/emscripten/emcc.py", line 3241, in <module>
    sys.exit(run(sys.argv))
  File "/home/piotrsikora/Google/emsdk/upstream/emscripten/emcc.py", line 2220, in run
    do_binaryen(target, options, wasm_target)
  File "/home/piotrsikora/Google/emsdk/upstream/emscripten/emcc.py", line 2667, in do_binaryen
    webassembly.add_emscripten_metadata(wasm_target)
  File "/home/piotrsikora/Google/emsdk/upstream/emscripten/tools/webassembly.py", line 91, in add_emscripten_metadata
    toLEB(0) +
  File "/home/piotrsikora/Google/emsdk/upstream/emscripten/tools/webassembly.py", line 33, in toLEB
    assert x >= 0, 'TODO: signed'
AssertionError: TODO: signed
```
The same command works fine with 2.0.4 and older releases.

cc @sbc100

**Comment by kripken** [comment]
Very strange... our test in the test suite passes on CI, and it passes for me locally. Even stranger, from your stack trace @PiotrSikora , `toLEB` is called with `0`, so `x >= 0` as the assertion wants - so why is it failing?

I wonder if somehow the python code that is run differs from the python in the stack trace? Maybe add a `print('x is', x)` right before that assertion and see what it prints.

**Comment by sbc100** [comment]
I can repro this locally:

```
$ ./emcc -s EMIT_EMSCRIPTEN_METADATA=1 tests/hello_world.c -o hello_world.wasm
Traceback (most recent call last):
  File "./emcc.py", line 3268, in <module>
    sys.exit(run(sys.argv))
  File "./emcc.py", line 2253, in run
    do_binaryen(target, options, wasm_target)
  File "./emcc.py", line 2694, in do_binaryen
    webassembly.add_emscripten_metadata(wasm_target)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/webassembly.py", line 86, in add_emscripten_metadata
    toLEB(dynamic_base) +
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/webassembly.py", line 33, in toLEB
    assert x >= 0, 'TODO: signed'
AssertionError: TODO: signed
```

**Comment by sbc100** [comment]
Its because we are not generating JS at all here so that `apply_memory` functions in skipped over.

**Comment by sbc100** [comment]
@PiotrSikora we can and will fix this but can I ask if you really need EMIT_EMSCRIPTEN_METADATA and if so what for?

I'm hoping that here are no more valid reasons for it to exist and we can remove it soon.  See https://github.com/emscripten-core/emscripten/issues/12231.

**Comment by PiotrSikora** [comment]
@sbc100 that's a great question! It doesn't look like we need it anymore, so from my point of view it can be removed.

**Comment by sbc100** [comment]
Great!  I'll fix emscripten, if you remove the flag from your build :)

I'll probably send out a mail about possibly deprecating this soon.

**Comment by PiotrSikora** [comment]
> Great! I'll fix emscripten, if you remove the flag from your build :)

Deal! Consider it done.

btw: WAVM relies on the metadata if it detects non-WASI imports or if `--abi=emscripten` is specified:
```
Module appears to be an Emscripten module, but does not have an 'emscripten_metadata' section. WAVM only supports Emscripten modules compiled with '-s EMIT_EMSCRIPTEN_METADATA=1'.                                                                          
If this is not an Emscripten module, please use '--abi=<ABI>' on the WAVM command line to specify the correct ABI.
```

**Comment by sbc100** [comment]
Thanks for the heads up.  @AndrewScheidecker perhaps we can work to remove this restriction now.  Do you know of any remaining reasons why you need the `emscripten_metadata`.  I'm hoping modern emscripten-built standalone wasm modules don't need this to be executed.

**Comment by sbc100** [comment]
Actually lets move the discussion to #12231.
