### ISSUE TITLE
Undefined exported functions error despite of ERROR_ON_UNDEFINED_SYMBOLS=0

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#12558]
I am building c++ project as main module(-s MAIN_MODULE=2) with some exported functions given as `-s EXPORTED_FUNCTIONS=@funcs.txt` and `-s ERROR_ON_UNDEFINED_SYMBOLS=0`. I am still getting `undefined exported function:` error while linking. The same code was getting linked on version 1.38.28. Now, after upgrading to 2.0.6, these errors are coming.

**Comment by sbc100** [comment]
Yes this behaviour was changed in #11604.

The rational is that you really shouldn't be trying to export functions that don't exist.  Any reason why you have undefined functions in your @funcs.txt?   Any reason you can't remove them?

**Comment by ravisumit33** [comment]
Actually I am getting this error for many of the defined functions and many system library functions also such as `["_i64Subtract", "__ZTVNSt3__217bad_function_callE", "__ZTINSt3__219__shared_weak_countE", "__ZTVN10__cxxabiv121__vmi_class_type_infoE", ""__assert_fail", "__ZTVSt12length_error", etc.]`

I am linking with `EMCC_FORCE_STDLIBS=1` so this should not have been the case. Also using mangled names so mangling is also not the issue. I had given the exported functions list at compile time also.

Here are the steps I followed:
1.  Build object files(.o files) with `-c` flag
2. Combined .o files into .bc files using `-r` flag
3. Now linking all .bc files and compiling to .wasm

**Comment by sbc100** [comment]
Some of those symbol looks like they come from the C++ standard library.  Maybe you are linking with `emcc` rather than `em++`?  

Other such as `_i64Subtract` and `__assert_fail`.. look like symbols that are part of the JS function so I believe you would need to export those using `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` and they don't want to be mangled.

**Comment by sbc100** [comment]
Is there any particular reason you want to use combined object files here (`emcc -r`) rather than just normal `ar` libraries (created with `emar`)?   Also, I would avoid the `.bc` extension these days as the output `emcc -r` is actually a combined object files, not a bitcode file (unless you are using `-flto` everywhere).

**Comment by sbc100** [comment]
Also, FYI, EXPORTED_FUNCTIONS has no meaning at compile time.

**Comment by ravisumit33** [comment]
I am linking with em++ only. Looks like I have to add `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` option. 
I also tried your suggestion to use `ar` libraries but I am still getting same error. Most surprising thing is I am getting undefined exported function error for functions that I have defined and for C++ standard libraries.

**Comment by ravisumit33** [comment]
Is it possible that mangled names has changed between 1.38.28 and 2.0.6 versions?

**Comment by sbc100** [comment]
> Is it possible that mangled names has changed between 1.38.28 and 2.0.6 versions?
> C++ standard library functions like `__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcj` are not defined then what can be the possible causes?

I believe those symbols that live the C++ standard library can change over time yes.  Specifically when we update to new version libc++.  For example I don't see that symbol in particular in my libc++ today.  I do see two very similar symbols though:

```
$ ../llvm-build/bin/nm cache/wasm/libc++-noexcept.a | grep _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPK | grep " W"
cache/wasm/libc++-noexcept.a:typeinfo.o: no symbols
0000015b W _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm
000023c1 W _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcmm
```

So it looks like signature of the internal `allocator::__init` function changes from `(char const*, unsigned int)` to `(char const*, unsigned long)`.

**Comment by sbc100** [comment]
That particular change should have occurred when the llvm ABI for emscipten changes size_t from `int` to`long` (#5916), although it looks like that happened back in v1.38.10 so it would predate your last working version (v1.38.28).

**Comment by ravisumit33** [comment]
I see. Thanks for clarifying this. Is there a way to check for change in all the symbols like you checked for  libc++?  Like change in symbols for functions in my own code.

**Comment by sbc100** [comment]
The simplest way I can think of is running `llvm-nm` on the input object files.   

Normally you own symbols should not change since the name mangling of C++ symbols is stable (as long we don't change the ABI which should be extremely rare). 

The most common cause of symbol names changing is that modification of your input source code.. how do you handle that?  Do you maintain funcs.txt by hand somehow?

**Comment by ravisumit33** [comment]
For all the exported functions, we haven't changed the the source code. I checked for the symbols in my own code and looks like they have changed. For example:
`__ZN2t33pdf5store5ArrayINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEEC1ERKNS1_6ObjectIS5_EE`
changed to
`__ZN2t33pdf5store5ArrayINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEEC2ERKNS1_6ObjectIS5_EE`

We can see both are mangled names of the same functions just one letter is changed(1 --> 2).

**Comment by sbc100** [comment]
Interesting I don't know enough about name mangling to know the significance of that change..  if you are interesting if figuring out what llvm change caused the change it would be interesting to know.  Perhaps @dschuff has an idea?   


Sadly 1.38.28 -> 2.0.7 is quite a large range.

One question, when you were using 1.38.28 we you using fastcomp?   That might explain the difference.

**Comment by ravisumit33** [comment]
Yes, we were using fastcomp. One more thing I wanted to ask you. Why did you do `grep W` in the `nm` command above. I am asking this because one of the symbols for which I am getting undefined error has actually the same mangled name but its type is `t` instead of `W`. Is there a linkage issue here?

**Comment by sbc100** [comment]
Oh I was just looking for the those C++ symbols happen to be weakly defined which gives them "W" .... for more normal defined symbols you want "t".

I can imagine there could be differences bettwen fastcomp and llvm in terms of name mangling, mostly because the use such very different versions of llvm and clang.   @dschuff does this ring any bells.

In any case once you have fixed those names they should not change again any time soon.

**Comment by ravisumit33** [comment]
Some symbols such as `__ZTVN10__cxxabiv117__class_type_infoE` are present in libc++abi.a 
But still showing as undefined exported functions. 
<img width="1197" alt="Screenshot 2020-10-22 at 2 31 06 AM" src="https://user-images.githubusercontent.com/19284116/96786985-a6795800-140e-11eb-8912-dbe287144334.png">

<img width="905" alt="Screenshot 2020-10-22 at 2 33 01 AM" src="https://user-images.githubusercontent.com/19284116/96787153-e9d3c680-140e-11eb-9f88-5a303cdf4e47.png">

These are the librairies getting linked by em++:
C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libc.a 
C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libcompiler_rt.a C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libc++.a C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libc++abi.a C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libdlmalloc.a C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libpthread_stub.a C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libc_rt_wasm.a C:\Users\sumik\latest_emsdk\emsdk\upstream\emscripten\cache\wasm-lto-pic\libsockets.a

**Comment by ravisumit33** [comment]
Also can I get list of all undefined exported functions beforehand? Right now I am running em++ and then getting one and repeating this step.

**Comment by sbc100** [comment]
Ah yes, I forgot you can control this from the command line with `-Wno-error=undefined` to turn them into warnings so you should see all of them without exiting.  You can also use `-Wno-undefined` if you want to disable them completely.

**Comment by sbc100** [comment]
It looks like the problem with `_ZTVN10__cxxabiv117__class_type_infoE` is that its a data symbol rather than a function symbl.   Strangely enough EXPORT_FUNCTIONS can include data symbols.. but the error checker that is reported "undefined exported function" is not looking at the data exports.. so its given an erroneous error here.

**Comment by ravisumit33** [comment]
So, if side module needs these data symbols, what is the way to export them?

**Comment by sbc100** [comment]
They are being exported, the bug is the that error is being mis-reported for them.    You can suppress the error for a temporary workaround.   I'm working on an actual fix.  

We don't have many users of `MAIN_MODULE=2` or of exporting data symbols with `FUNCTION_EXPORTS` so it not surprising to me that things like this show up from time to time.

**Comment by dschuff** [comment]
I use `c++filt` to demangle symbol names (not that I had to remove the leading `_` to get it to work.

```
$ echo _ZN2t33pdf5store5ArrayINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEEC1ERKNS1_6ObjectIS5_EE | c++filt
t3::pdf::store::Array<t3::pdf::store::StoreObjTraits<t3::TetraphiliaAppTraits> >::Array(t3::pdf::store::Object<t3::pdf::store::StoreObjTraits<t3::TetraphiliaAppTraits> > const&)
$ echo _ZN2t33pdf5store5ArrayINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEEC2ERKNS1_6ObjectIS5_EE | c++filt
t3::pdf::store::Array<t3::pdf::store::StoreObjTraits<t3::TetraphiliaAppTraits> >::Array(t3::pdf::store::Object<t3::pdf::store::StoreObjTraits<t3::TetraphiliaAppTraits> > const&)
```

and the result is.... they have the same demangling? (at least, I can't see a difference)

So, according to https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling-special-ctor-dtor
the "C1" in the top version is a complete object constructor, whereas the "C2" in the bottom version is a base object constructor.

**Comment by ravisumit33** [comment]
Hi @sbc100 , 
Sorry for late reply
Thanks to you guys, I have resolved all undefined symbols while upgrading from 1.38.28 to 2.0.6.
Except one symbol `llvm_trap` which I have included in `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`.
I can clearly see it defined in `upstream/emscripten/src/library.js` but while linking I am getting following warning:
`warning: undefined symbol: llvm_trap (referenced by top-level compiled C/C++ code)`

Any idea why this happening?

**Comment by sbc100** [comment]
Interesting.. I just removed that symbol in #12015.    To our knowledge this symbol should not be needed anymore, at least it not needed by any of our test cases.

Can you add `-s LLD_REPORT_UNDEFINED` to see which object file the reference is coming from?

**Comment by sbc100** [comment]
Any news on this?  Where is the `llvm_trap` reference coming from?

**Comment by ravisumit33** [comment]
`llvm_trap` was there line `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` for `MAIN_MODULE`. I have checked for undefined symbols both in `MAIN_MODULE` and `SIDE_MODULE` but I can't find it. Perhaps it is not needed anymore.

**Comment by ravisumit33** [comment]
I think `LLD_REPORT_UNDEFINED` doesn't work if I want to have all undefined symbols for `SIDE_MODULE`. Is there a way to know this so that I can easily export them from `MAIN_MODULE` ?

**Comment by sbc100** [comment]
No, sadly there is no easy way to generate the list of symbols for `MAIN_MODULE=2`.. that is why `MAIN_MODULE=1` is the default because its so much easier to use.

Ideally we could write a tool to dump the imports of the SIDE_MODULE and convert that into a file that could be passed to `EXPORTED_FUNCTIONS=@<filename.txt>` when building the `MAIN_MODULE=2`?   Do you fancy writing such a tool?

**Comment by ravisumit33** [comment]
Currently, I use `llvm-nm` to find out all undefined symbols in my side module archive. One problem with this method is that we get duplicate undefined symbols as it shows same symbol multiple times for different object files. What do you think how should such a tool work to dump all undefined symbols?

**Comment by sbc100** [comment]
You should be able to get a more accurate undefined symbol list by looking that side module itself.   You can use wasm-dis (from binaryen) or wasm2wat or wasm-objdump (both from wabt) to inspect the contents of the side module itself and find all its imports.

**Comment by ravisumit33** [comment]
I used `wasm-dis` to disassemble side module wasm and I got imports like below:
```
(import "wasi_snapshot_preview1" "args_sizes_get" (func $fimport$0 (param i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "args_get" (func $fimport$1 (param i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "proc_exit" (func $fimport$2 (param i32)))
(import "env" "main" (func $fimport$3 (param i32 i32) (result i32)))
(import "env" "_ZNK2t33pdf5store10DictionaryINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEE10GetIntegerEPKci" (func $fimport$4 (param i32 i32 i32) (result i32)))
(import "env" "_ZN2t43pdf19get_page_dictionaryERNS0_8documentEN2t33pdf8document6PageIDE" (func $fimport$5 (param i32 i32 i32)))
(import "env" "_ZNK2t33pdf5store10DictionaryINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEE8GetArrayEPKc" (func $fimport$6 (param i32 i32 i32)))
(import "env" "_ZN2t33pdf5store11GetStoreKeyINS_20TetraphiliaAppTraitsEEERKNS1_8StoreKeyIT_EERKNS1_10DictionaryINS1_14StoreObjTraitsIS5_EEEE" (func $fimport$7 (param i32) (result i32)))
(import "env" "_ZNK2t33pdf5store10DictionaryINS1_14StoreObjTraitsINS_20TetraphiliaAppTraitsEEEE12GetReferenceEPKc" (func $fimport$8 (param i32 i32 i32)))
(import "env" "WaitForSingleObjectEx" (func $fimport$20 (param i32 i32 i32) (result i32)))
(import "env" "InterlockedCompareExchange" (func $fimport$21 (param i32 i32 i32) (result i32)))
(import "env" "CloseHandle" (func $fimport$22 (param i32) (result i32)))
(import "env" "_ZN5boost15throw_exceptionERKSt9exception" (func $fimport$23 (param i32)))
(import "env" "CreateEventA" (func $fimport$24 (param i32 i32 i32 i32) (result i32)))
 (import "env" "InterlockedExchangeAdd" (func $fimport$25 (param i32 i32) (result i32)))
```

This output can be parsed to find all imports. So, I believe symbols needed by side-module from main module are those containing `env`. Correct me if I am wrong?
And are we sure that all symbols with `env` are those that are required from main module?

**Comment by sbc100** [comment]
All imports will be needed, including the `wasi_snapshot_preview1` too.   Not just the `env`.

**Comment by ravisumit33** [comment]
Side modules can now be passed on command line while building main module to overcome this issue.
