### ISSUE TITLE
Emscripten glue code fails in strict mode with MAIN_MODULE

### ISSUE THREAD

**Issue by surma** [emscripten-core/emscripten#12568]
Here’s a [small repro case](https://gist.github.com/surma/3010d6ddce7435783821c87bc5409342) that you can just build with `make all`. 

If you comment out the [monkey-patched `setImmediate` global in `index.html`](https://gist.github.com/surma/3010d6ddce7435783821c87bc5409342#file-worker-js-L4), the code fails to run.

```
ReferenceError: setImmediate is not defined
    at main.js:formatted:29783
    at main ((index):7)
    at (index):14
```

**Comment by kripken** [comment]
Thanks @surma !

This should be fixed with #12581 as I see no references to `setImmediate` in the output with that.

@sbc100 we should probably do more strict mode testing... this testcase found another issue with `__stack_pointer` that I'll open a PR for in a sec.

**Comment by sbc100** [comment]
Yes, just like `-Werror` I think we should probably default to building the entire test suite with `-s STRICT_JS` enabled.

**Comment by Raumzeitkeks** [comment]
I ran into this problem as well. I have a slightly different [repro case](https://gist.github.com/Raumzeitkeks/b976df306870c5b01f552e21fe96c54b) that doesn't use `dlopen()`, but `Module['dynamicLibraries']`-style dynamic linking instead. I think the fix from #12581 should work here too, but progress on that pull request seems to have stalled.

**Comment by kripken** [comment]
It seems like there is a use for setImmediate, so I guess that PR should be closed.

Getting back to this issue, I thought removing setImmediate was a quick fix. But as it isn't, I'm unsure what is actually causing the problem here. What is different between setImmediate and setTimeout in strict mode? Is setImmediately specifically banned there or something like that?

**Comment by Raumzeitkeks** [comment]
I'm not certain, but I think setImmediate (and clearImmediate) are not really called in my case. Adding the polyfill is already sufficient to cause an error, since setImmediate and clearImmediate are being polyfilled unconditionally at module initialization. Why the polyfill is added in the first place is unclear to me though.

If I got that right, then removing setImmediate along with the polyfill should fix it.

**Comment by surma** [comment]
@kripken The specific problem here is that `setImmediate` is assigned without ever declaring the variable beforehand. That’s why this is throwing in strict mode. To fix this, you could do something like

```diff
- setImmediate = /* ... */
+ globalThis.setImmediate = /* ... */
```

That would fix this immediate issue. The other issue of polyfilling `setImmediate` with `setTimeout` is orthogonal.

**Comment by kripken** [comment]
I see, thanks. So it's the strict mode default, and that we write to a global place.

How about if when `STRICT` or `EXPORT_ES6` are enabled, we ifdef out the places that do things like this? That seems best to me but maybe there are cases not covered by those flags?

**Comment by hoodmane** [comment]
In Pyodide with Emscripten version 2.0.15, if we add:
```js
"use strict";
let setImmediate = globalThis.setImmediate;
let clearImmediate = globalThis.clearImmediate;
let baseName, fpcGOT, dyncallGOT, fpVal, dcVal;
```
then the output runs in strict mode. 

There are many other code paths that we are not hitting that will not work in strict mode. I think ideally it would be a good idea to make a PR that adds `"use strict";` to the output and then we can hunt down problems until all tests pass in strict mode.

For instance, I see many instances of `typeof some_thing!="undefined"`. This idiom is a runtime error in strict mode. If you did something like:
```
let globals;
if (typeof globalThis !== 'undefined' {
   globals = globalThis;
} else if (typeof self !== 'undefined') {
	globals = self;
} else if (typeof window !== 'undefined') {
	globals = window;
} else {
	globals = Function('return this')();
}
```
then you could feature detect functions like:
```js
if(globals.some_thing)
```
`globals` should get minified to a single letter so this will also be shorter than current generated code.

**Comment by kripken** [comment]
@hoodmane Help with fixing strict mode issues would be great!

About the PR you suggested, that sounds good. There is a `strict` test mode, which you can run locally with `./tests/runner.py strict`. A PR could add it for testing by adding it to `.circleci/config.yml` (alongside `wasm2` for example).
