### ISSUE TITLE
Can`USE_PTHREADS` and `MINIMAL_RUNTIME ` exist at the same time?

### ISSUE THREAD

**Issue by tigercosmos** [emscripten-core/emscripten#12578]
Can`USE_PTHREADS` and `MINIMAL_RUNTIME ` exist at the same time?

I have a simple pthread code `test.c`.

I run em with the following arguments:

```
emcc test.c \
		-s USE_PTHREADS=1 \
		-s PTHREAD_POOL_SIZE=4 \
		-s ENVIRONMENT=web,worker \
		-s MINIMAL_RUNTIME \
		-O3 \
		-o test.html
```

Then I got an error:
<details>
<img src="https://user-images.githubusercontent.com/18013815/96905642-4eecf200-14cb-11eb-8d00-5d57a2d52e9a.png">
</details>
The code works well when I don't set `MINIMAL_RUNTIME`.

I use version `2.0.7`.

`test.c` looks like:

<details>

```c
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

#define NUMTHRDS 4
#define MAGNIFICATION 1e9

typedef struct
{
    double *sum;
} Arg;

pthread_t callThd[NUMTHRDS];

void *count_pi(void *arg)
{

    Arg *data = (Arg *)arg;
    double *sum = data->sum;
    *sum += 1;

    printf("sum=%f\n", *sum);

    pthread_exit((void *)0);
}

int main(int argc, char *argv[])
{
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);

    double *sum = malloc(sizeof(*sum));
    *sum = 0;

    Arg arg[NUMTHRDS];
    for (int i = 0; i < NUMTHRDS; i++)
    {
        arg[i].sum = sum;
        pthread_create(&callThd[i], &attr, count_pi, (void *)&arg[i]);
    }

    pthread_attr_destroy(&attr);

    void *status;
    for (int i = 0; i < NUMTHRDS; i++)
    {
        pthread_join(callThd[i], &status);
    }

    printf("Final Sum =  %f \n", *sum);

    free(sum);
}
```

</details>

**Comment by tigercosmos** [comment]
I found the problem:

it's because there is inrelevant code not been deleted:

```
function _emscripten_futex_wait(addr, val, timeout) {
    if (addr <= 0 || addr > HEAP8.length || addr & 3 != 0) return -28;
    if (!ENVIRONMENT_IS_WEB) {
        var ret = Atomics.wait(HEAP32, addr >> 2, val, timeout);
        if (ret === "timed-out") return -73;
        if (ret === "not-equal") return -6;
        if (ret === "ok") return 0;
        throw "Atomics.wait returned an unexpected value " + ret
    } else {
```

**Comment by kripken** [comment]
cc @juj 

Yes, I think this is not done yet, and PRs would be great of course!

Is the issue that `ENVIRONMENT_IS_WEB` etc. are not defined? I'm not sure offhand how best to fix that. If it's a tiny ifdef maybe that's ok, but long-term we should be able to avoid all of this using https://github.com/emscripten-core/emscripten/issues/12203

**Comment by tigercosmos** [comment]
Yes, `ENVIRONMENT_IS_WEB` and `ENVIRONMENT_IS_NODE` are not defined in the output code, but they also should not exist at all.

I fix the issue by
```
	emcc test.c \
		-s USE_PTHREADS=1 \
		-s PTHREAD_POOL_SIZE=4 \
		-s ENVIRONMENT=web,worker \
		-s MINIMAL_RUNTIME \
		-O3 \
		-o test.html
	mv test.js tmp.js
	sed 's/ENVIRONMENT_IS_NODE/false/g' tmp.js | \
	sed 's/ENVIRONMENT_IS_WEB/true/g' > test.js
```

**Comment by tigercosmos** [comment]
@kripken I haven't checked this issue for a long time. Not sure if this issue still an issue.

**Comment by kripken** [comment]
I believe this should be fixed, as we have tests for it now.
