### ISSUE TITLE
Support -lSDL2_mixer and others

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#12589]
Background: https://github.com/emscripten-ports/SDL2_mixer/issues/2

Things like `-lSDL2` work because the internal library name matches the flag. But `SDL2_mixer` has a different internal name, with `_ogg` as a suffix, which prevents this.

The internal name is important as we build a different SDL2_mixer depending on the codecs. But it makes simple link flags not work.

It would be good to make such link flags just work, perhaps by mapping `-l` names to the internal ones. This would require some changes in `emcc.py` and related code's handling of link flag libraries, and maybe also the ports code itself like `tools/ports/sdl2_mixer.py`.

**Comment by sbc100** [comment]
One possiblity it so have many different version of `libSDL2_mixer.a` but have the directory name distinguish them.

So 

- `ogg/libSDL2_mixer.a`
- `ogg_mp3/libSDL2_mixer.a`

Then SDL2_MIXER_OGG would add `-L<path_to_system_libs>/ogg` to the library path?

Basically would move variant from the library name to the library path.

**Comment by Beuc** [comment]
I confirm this broke my pygame_sdl2 build.
`wasm-ld: error: unable to find library -lSDL2_mixer`

However I have troubles determining when that broke. My build worked in 2.0.2 but the related SDL2_mixer changes seem to predate.

**Comment by sbc100** [comment]
I believe it was when SDL_mixer to split into multiple different libraries with different names.  Maybe #11577?   But yes that would have been way back in 1.39.20.

You say it worked for you in 2.0.2, can you check 2.0.3?
