### ISSUE TITLE
[discussion] Exporting MEMFS JavaScript object by default

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#12599]
Since MEMFS is enabled by default, I propose to export it by default as Module.MEMFS and Module.filesystems.MEMFS variables. Currently:

```
Module.filesystems.MEMFS
VM224:1 Uncaught TypeError: Cannot read property 'MEMFS' of undefined

Module.MEMFS
ƒ () { abort("'MEMFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)") }
```

**Comment by sbc100** [comment]
Couldn't that argument be applied to any functions that are included by default?

I think the reason we don't do that is that there is cost to exporting things on the Module in general, at least in terms of code size.   I may not know all the history / details here though.

In there some particular reason why MEMFS is needed outside the module more than other objects/methods?

**Comment by vadimkantorov** [comment]
Yep, it could.

I guess, my question is that the memfs main code is included anyway, so exporting it is just `Module[key] = value`. But if these little lines add up to some big size, then you're right.

**Comment by sbc100** [comment]
I think one issue with code size is that the `Module[key]` stuff can't be minimized, unlike the rest of the JS internals, so t tends to add up yes.

**Comment by vadimkantorov** [comment]
I just found that MEMFS is available under "FS.filesystems.MEMFS" (even if it's not explicitly exported). It's just that I was using a wrong `filesystems` field (because it's not well-documented for now). So the code size reasoning and `FS.filesystems.MEMFS`, I retract this proposal :)
