### ISSUE TITLE
Multiple clang++ processes

### ISSUE THREAD

**Issue by bdenhollander** [emscripten-core/emscripten#12593]
On a relatively small project, time spent in "compile inputs" for a lists of .cpp files is dominating the total time. Would it be possible to parallelize this loop using `multiprocessing` or `joblib` to launch one instance of clang++ per core?

https://github.com/emscripten-core/emscripten/blob/56c5062c80b1962ffb1c23e0ba5fc3b6c9d19bc6/emcc.py#L2015-L2034

**Comment by sbc100** [comment]
The best way to compile in parallel is to use a build system that is capable of running multiple processes at once.

Normally you run the compiler once for each source input and the build system such as `make` or `ninja` is in charge of running them in parallel.

Passing multiple source inputs to the compiler directly is also limiting in other ways.  For example, it prevents you from choosing the location and name of the output files.

**Comment by bdenhollander** [comment]
Switching to `ninja` has significantly improved build performance.
