### ISSUE TITLE
please tag release 2.0.8 in git repository

### ISSUE THREAD

**Issue by jonassmedegaard** [emscripten-core/emscripten#12602]
Hi,

It seems from 7b87f0b and https://github.com/emscripten-core/emsdk/pull/643 that a release happened.

If that's correctly assumed, then please tag it as such - to avoid guessing, for those building emscripten from source.

**Comment by kripken** [comment]
Sorry about this @jonassmedegaard , looks like we forgot this time. I tagged emscripten and emsdk now with 2.0.8 now.
