### ISSUE TITLE
Environment Path entries lost

### ISSUE THREAD

**Issue by OAguinagalde** [emscripten-core/emscripten#12618]
I have a couple of scripts for building with emsc that run these 2 before building:
```psh
emsdk\emsdk activate latest;
emsdk\emsdk_env.bat;
```
I have never had problems until I updated my emscripten repo yesterday.
I've tracked down the issue to this exact commit  807e55c:

807e55c - Set user environment variables permanently by using `--permanent` + deprecate `--global` (#621)

The issues is that, after running the script, part of my path variables get lost.
Say I have 50 entries in my path variable. Before that commit, when using the script, I would get some new entries for emsdk without losing my previous entries, so 50 + emsdk path entries. After that commit, I would end up with only part of those 50, maybe just the last 10 (it's always the last X that are kept) + the new emsdk path entries.

It might not be a bug, since I can see that the commit touches something related, but I find it weird that only _some_ of the entries are lost and other ones are still there, so I'm guessing this is a bug. If not, please let me know how to use the emsdk scripts to not lose my previous path if possible. Thanks!

**Comment by OAguinagalde** [comment]
Ah, I think I just posted this on the wrong repo... I'll move this to the emsdk repo, my fault.

**Comment by sbc100** [comment]
This looks like a duplicate of https://github.com/emscripten-core/emsdk/issues/634

**Comment by OAguinagalde** [comment]
Yes it is, as I was going to move my issue there I saw that it was already being worked on
