### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '{' in generated .js file

### ISSUE THREAD

**Issue by fridenmf** [emscripten-core/emscripten#12621]
**Version:**
Emscripten 2.0.7

**Description:**
I have a working hello world project using WebGpu, but when added support for main/side-modules i started getting errors in the generated .js file:
Uncaught SyntaxError: Unexpected token '{'

I'm using the following target properties on the main module:
-O2 -s MAIN_MODULE=1 -s USE_WEBGPU=1  -s DISABLE_EXCEPTION_CATCHING=0 -s WASM=1 -s ASYNCIFY=1
and the following on the side module:
-O2 -s SIDE_MODULE=1 -s EXPORT_ALL=1 -s USE_WEBGPU=1 -s DISABLE_EXCEPTION_CATCHING=0 -s WASM=1 -s ASYNCIFY=1

I'm also using the compile options:
-Werror -Wfatal-errors -fPIC

The error occurs in the following lines in the generated .js file:
```
function _wgpuComputePassEncoderWriteTimestamp(encoderId, querySetId, queryIndex) {
      var pass = WebGPU.mgrComputePassEncoder.get(passId);
      var querySet = WebGPU.mgrQuerySet.get(querySetId);
      pass["writeTimestamp"](querySet, queryIndex);
    }
  Module["_wgpuComputePassEncoderWriteTimestamp"] = _wgpuComputePassEncoderWriteTimestamp;

  wgpuComputePipelineGetBindGroupLayout(pipelineId, groupIndex) {
      var pipeline = WebGPU.mgrComputePipeline.get(pipelineId);
      return WebGPU.mgrBindGroupLayout.create(pipeline["getBindGroupLayout"](groupIndex));
    }
  Module["_wgpuComputePipelineGetBindGroupLayout"] = _wgpuComputePipelineGetBindGroupLayout;

  function _wgpuComputePipelineReference(id) {
    WebGPU.mgrComputePipeline.reference(id);
  }
  Module["_wgpuComputePipelineReference"] = _wgpuComputePipelineReference;
```
, on the line declaring wgpuComputePipelineGetBindGroupLayout which is supposed to be function like _wgpuComputePassEncoderWriteTimestamp and _wgpuComputePipelineReference, but it's missing the function keyword. The name of the function is also missing an underscore prefix line the other ones.

The function wgpuRenderPipelineGetBindGroupLayout is also missing the function keyword and the underscore prefix.

If I manually add the function keyword and the underscore prefix to the wgpuComputePipelineGetBindGroupLayout and wgpuRenderPipelineGetBindGroupLayout functions the application runs like expected.

**Reproduction:**
The error can be reproduced using the target properties above, using the following code for the main module:
```
#ifdef __EMSCRIPTEN__
#include "webgpu/webgpu_cpp.h"
#include "emscripten.h"
#include "emscripten/html5.h"
#include "emscripten/html5_webgpu.h"
#endif
#include <stdio.h>

extern "C" int main(int argc, char** argv)
{
	printf("hello world\n");
	return 0;
}
```
, and the following code for the side module:
```
// side_module.h
int sideModule(int a);

// side_module.cpp
int sum(int a)
{
	return a + 1;
}
```

**Comment by sbc100** [comment]
Indeed it looks like both `wgpuComputePipelineGetBindGroupLayout` and `wgpuRenderPipelineGetBindGroupLayout` are declared in a stange way without the function keyword in `library_webgpu.js`... I have no idea how this is even possible, but it certainly doesn't seem to work.

@kainino, it looks like you added these in #11737?  Can you take a look?   Looks like we are missing some test coverage here.  (we could at at least compile and validate the resulting JS even if we don't run it in CI).

**Comment by curiousdannii** [comment]
They're called [method definitions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) and are part of ES2015 (ES6). These specific function definitions can be changed in the short term, but ideally this style of function definitions should be supported.

**Comment by sbc100** [comment]
Does that work in the global scope though?

The way library.js files work is that required elements are copied into the global scope... library.js files are kind of strange in various ways.

**Comment by curiousdannii** [comment]
No, only in object literals.

I don't know how the libraries stuff is handled. It clearly does some processing in JS because of the `mergeInto(LibraryManager.library, ...)` code. But I don't know what it does after that. It will probably need to be made aware of other types of function definitions.

**Comment by sbc100** [comment]
@kainino0x .. can you take a look at this (sorry I mistyped your handle earlier so you probably didn't see it until now)?  Should be easy easy fix

**Comment by kainino0x** [comment]
I'll take a look, thanks for forwarding!

**Comment by kainino0x** [comment]
Oops, this probably went unnoticed because this is valid syntax in some more recent versions of ES. Opened fix.

**Comment by sbc100** [comment]
No I think its invalid at the top level always so any program that actually includes these symbols won't parse (IIUC).

I mean that library is valid input, but it produces invalid output if used.

**Comment by kainino0x** [comment]
Got it, I think that makes sense. We definitely haven't tested this thoroughly yet.
