### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by smileorigin** [emscripten-core/emscripten#12620]
This is a part of my build script
```bash
-s WASM=1                   \
-s PROXY_TO_PTHREAD         \
-s USE_PTHREADS=1           \
-s ENVIRONMENT=web,worker   \
-s MODULARIZE=1             \
```

I import glue js from my js file, and all file is load done in browser.
But the worker is threw a error
![image](https://user-images.githubusercontent.com/18087843/97405600-e53d6f80-1932-11eb-8187-d79bf4f5b4fe.png)

**Comment by rteterin** [comment]
Hello @smileorigin.

Could you please tell how you solved this? I'm currently experiencing the same error.

**Comment by smileorigin** [comment]
> Hello @smileorigin.
> 
> Could you please tell how you solved this? I'm currently experiencing the same error.

I forgot the exact reason, but let me show you how I'm using it now.
> I'm not sure. It seems to be a problem with the EMCC version for me.  

Upgrade emcc to the latest version(**2.0.9**), and add `-s EXPORT_NAME=“ExampleModuleFactory"`
```javascript
window.ExampleModuleFactory(options).then((exampleModuleFactory) => {
    // onRuntimeInitialized
    // exampleModuleFactory is the wasm module instance
});
```
