### ISSUE TITLE
Dynamic EM_JS?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#12627]
I have a JS code that's hard to translate to EM_VAL therefore relaying on EM_JS but due to licencing issues I somehow need to construct EM_JS body dynamically so the JS code would be not known at compile time rather runtime.

**Comment by sbc100** [comment]
You can switch the using JS library and including your code via `--js-library` or you could switch to running your code via `emscripten_run_script` which takes string at runtime.
