### ISSUE TITLE
OES_fbo_render_mipmap not automatically initialized

### ISSUE THREAD

**Issue by goodartistscopy** [emscripten-core/emscripten#12638]
Hello,
Is there a specific reason why this WebGL extension is not in the list of [automatically enabled extensions](https://github.com/emscripten-core/emscripten/blob/16d018704df2f1cf29ff37c2c1f271ab0caed518/src/library_webgl.js#L1083) ? Is there a performance caveat in using it ?
thanks

**Comment by juj** [comment]
Hmm, I think it may have been ratified after the automatically enabled list was last updated. No known performance caveats. Marked down a note to post a PR to update this.

**Comment by goodartistscopy** [comment]
Thanks !
