### ISSUE TITLE
How to include Module._malloc and Module._free with the latest update?

### ISSUE THREAD

**Issue by josh83abc** [emscripten-core/emscripten#12644]
Hello guys,

I just upgraded to the latest version of emscripten and I can't make my project to work anymore. I didn't do any change, I just needed to recompile. 2 months ago it worked fine.

It looks like the new version doesn't include Module._malloc et Module._free anymore >[Stop including malloc/free by default #12213](https://github.com/emscripten-core/emscripten/pull/12213)

So now I got the error : Module._malloc is not a function

And by comparing with my old working compiled project, I can see that these lines are missing in the generated JS :
Object.getOwnPropertyDescriptor(a.ready,"_malloc") ...
Object.getOwnPropertyDescriptor(a.ready,"_free") ...

I tried to add the malloc and free manually : emcc .... -s EXPORTED_FUNCTIONS="['_malloc', '_free']"

But now I get this error : RuntimeError: abort(Assertion failed: exported native function malloc not found)

How to include Module._malloc and Module._free with the latest emscripten update?

Thanks for your help, I lost 3 hours on this :/

**Comment by sbc100** [comment]
` -s EXPORTED_FUNCTIONS="['_malloc', '_free']"` should absolutely work. 

For example can you run `emcc tests/hello_world.c -s EXPORTED_FUNCTIONS="['_main', '_malloc', '_free']"`.   This works fine for me.

Oh.. I see this is a runtime error which means as far as the compiler is concerned the functions do exist... but they are somehow not found in the wasm module at runtime.. could the wasm module being loaded be out-of-date?

Can you see using `wasm-objdump` if `malloc` is actually exported by the final module that you are shipping?

**Comment by josh83abc** [comment]
Ok I just got the idea to clear the cache (emcc --clear-cache) and I recompiled everything, with -s EXPORTED_FUNCTIONS="['_main', '_malloc', '_free']", and it works! I don't know what happened, I am pretty sure my previous wasm module was the most recent one. Anyway, always good to clear the cache :)
Thanks for the super fast reply!

**Comment by sbc100** [comment]
Actaully .. the cache should always be cleared when you update between emscripten versions so what you describe should not be possible.  Just FYI in case this comes up again it might be a sign of a different issue with stale cache.

**Comment by josh83abc** [comment]
When I clear the cache, emscripten generates a few files (liba...), but don't use to happen when I update to a new emscripten versions... Anyway, better to clear the clear twice to be sure ;) (I am using emscripten on linux)
