### ISSUE TITLE
How to create Virtual XHR Backed directory with many files and subdirecrories?

### ISSUE THREAD

**Issue by aveeday** [emscripten-core/emscripten#12652]
I am looking how to access files without need to declare all their name in preInit.

Is there a way to dynamically call FS.createLazyFile not in preInit function?

Or it will be good to be able create lazy dir like this:
```js
Module["preInit"] = function() {
     FS.createLazyDir('/', "bigdir", "http://localhost:11111/bigdir", true, false);
};
```

And then access any files from '/bigdir' like:
```sh
/bigdir/file1
/bigdir/anotherdir/file2
/bigdir/anotherdir/subdir/file3
```

**Comment by boardend** [comment]
I'm very interested in such a solution too. Had a look at the implementation of [`createLazyFile`](https://github.com/emscripten-core/emscripten/blob/a856e88ab85560b538d1b8d4f7e74ea0d1991c94/src/library_fs.js#L1676), but got scared by:

> This is a total hack, but I want to get this lazy file code out of the core of MEMFS. If we want to keep this lazy file concept I feel it should be its own thin LAZYFS proxying calls to MEMFS.

Is this something that could probably be implemented? Or are there other solutions emerging like the proposed LAZYFS?

**Comment by kripken** [comment]
WasmFS might be ready to add an XHR backend now, allowing lazy loading. (WasmFS is replacing the entire old FS, including createLazyFile etc.)

The tracking issue for that is https://github.com/emscripten-core/emscripten/issues/16032 so let's close this in favor of that one, as that is where new work will happen.
