### ISSUE TITLE
-o build/myobj.o generates build/myobj.wasm

### ISSUE THREAD

**Issue by aminya** [emscripten-core/emscripten#12663]
I have a codebase that uses both C (pcre library) and C++. I use `emcc` to generate an object file (build/pcre.o), and then use it as an argument to `em++`. However, instead of generating an object file, emcc generates a wasm and a js file.

I get this error why I do this:
```
emcc: warning: generating an executable with an object extension (.o).  If you meant to build an object file please use `-c, `-r`, or `-shared` [-Wemcc]
```

```bash
emcc                                         \
  -o build/pcre.o                            \
  -O3                                        \
  -I vendor/pcre/10.23/src                   \
  -I vendor/pcre/include                     \
  -D HAVE_CONFIG_H                           \
  -D PCRE2_CODE_UNIT_WIDTH=16                \
  vendor/pcre/pcre2_chartables.c             \
  vendor/pcre/10.23/src/pcre2_auto_possess.c \
  vendor/pcre/10.23/src/pcre2_compile.c      \
  vendor/pcre/10.23/src/pcre2_config.c       \
  vendor/pcre/10.23/src/pcre2_context.c      \
  vendor/pcre/10.23/src/pcre2_dfa_match.c    \
  vendor/pcre/10.23/src/pcre2_error.c        \
  vendor/pcre/10.23/src/pcre2_find_bracket.c \
  vendor/pcre/10.23/src/pcre2_jit_compile.c  \
  vendor/pcre/10.23/src/pcre2_maketables.c   \
  vendor/pcre/10.23/src/pcre2_match.c        \
  vendor/pcre/10.23/src/pcre2_match_data.c   \
  vendor/pcre/10.23/src/pcre2_newline.c      \
  vendor/pcre/10.23/src/pcre2_ord2utf.c      \
  vendor/pcre/10.23/src/pcre2_pattern_info.c \
  vendor/pcre/10.23/src/pcre2_serialize.c    \
  vendor/pcre/10.23/src/pcre2_string_utils.c \
  vendor/pcre/10.23/src/pcre2_study.c        \
  vendor/pcre/10.23/src/pcre2_substitute.c   \
  vendor/pcre/10.23/src/pcre2_substring.c    \
  vendor/pcre/10.23/src/pcre2_tables.c       \
  vendor/pcre/10.23/src/pcre2_ucd.c          \
  vendor/pcre/10.23/src/pcre2_valid_utf.c    \
  vendor/pcre/10.23/src/pcre2_xclass.c                                    
```

**Comment by sbc100** [comment]
If you want to build a library from a set of C files, the standard way to do it is to compile each file with the `-c` flag and then combine them into a library (an `ar` archive) using `emar rcs lib<foo>.a  obj1.o obj2.o ... etc`.

Normally one would use a Makefile or cmake file to along with a build tool like `make` or `ninja` which can build the object files in parallel.

As the message suggests we do still support combining many object into one using `-r` but its not the recommended path and it deviates from standard native compiler practice.

**Comment by aminya** [comment]
I tried the method you are suggesting. It seems to work. 

If generating an `o` file is not supported using `-o target.o`, then it should be removed from [the documentation](https://emscripten.org/docs/tools_reference/emcc.html?highlight=emcc).

**Comment by galoko** [comment]
I get this error while using vs-tool. Is there a way to fix this?

**Comment by sbc100** [comment]
@galoko perhaps you could give some more details.  Are you having trouble using `-c` to compile you object files?
