### ISSUE TITLE
Does void type EM_JS functions block execution?

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#12678]
I have a void type EM_JS function which I want to run without waiting it to be completed. I need to continue the rest program after calling the function without blocking execution.

**Comment by sbc100** [comment]
Can you use setTimeout or something like that the schedule the work on the event loop?

**Comment by gerald-dotcom** [comment]
Just to confirm, do you mean something like this??

```
EM_JS(void, start_timer, (), {
  Module.timer = false;
  setTimeout(function() {
    Module.timer = true;
  }, 500);
});

```

**Comment by gerald-dotcom** [comment]
Would it cause to continue the execution without blocking or EM-JS has some magic that even wait for setTimeouts?

**Comment by sbc100** [comment]
That is what I was thinking of yes.   You could just use setTimeout with 0 to have it happen ASAP.

Can you re-state the question?  I'm not sure exactly what you are asking.

**Comment by gerald-dotcom** [comment]
A picture is worth thousands words, see below code where I illustrated what need to be happen,
```
EM_JS(void, start_timer, (), {
  Module.timer = false;
  setTimeout(function() {
    Module.timer = true;
  }, 500);
});

int main() {
   start_timer(); /// Call EM_JS function and continue execution without waiting for EM_JS execution to be completed 
   std::cout << "This is some statement" << "\n"; // Execute this without waiting for start_timer()
   std::cout << "This is another statement" << "\n"; // Execute this too without waiting for start_timer()
}
```

**Comment by sbc100** [comment]
That will happen as you expect yes.   The timeout function will not run until after main is done and you have printed both those statements to stdout.   Even if you do setTimeout with 0 it won't run until you next yeild to the even loop which in this case will be when main returns.

**Comment by gerald-dotcom** [comment]
I need to run both main() and EM_JS simultaneously

**Comment by sbc100** [comment]
The JavaScript engine can only do one thing at time since its fundamentally single threaded and callback-based. 

All user code runs from and eventloop and there various ways you can interleave your native code with with JS code, but it normally involves splitting up your main function.  See https://emscripten.org/docs/porting/emscripten-runtime-environment.html#execution-lifecycle.

**Comment by gerald-dotcom** [comment]
Ok. How about pthreads? Would that bypass this limitation? 

But I'm not sure whether pThreads supports EM_JS out of box.  The other thing is EM_JS function does call a function in C++ side once a specific event observed and this C++ function set the value to a Global variable in C++.  I need this JS --> C++ call happen without waiting for main() to finish it's execution as the main() function pulls value of that global variable at certain stages.

**Comment by sbc100** [comment]
The best options for you are either to break up you main function into something that can yeild periodically to the event loop or use use ASYNCIFY to enable to to yield even without returning. 

You might be able to make a pthread-based solution work but that would be a lot of complexity to add, and your application would not run everywhere (pthread support is still fairly limited, especially on mobile).

Both pthreads and asyncify and fairly heavy weight solutions so if you can avoid them by re-structing your main function you might have have a better time.

**Comment by gerald-dotcom** [comment]
"use ASYNCIFY to enable to to yield even without returning"

How would that works? Any example? Do you mean the sleep function?

"your application would not run everywhere (pthread support is still fairly limited, especially on mobile)."

We target only desktop
