### ISSUE TITLE
undefined symbol: sigwait

### ISSUE THREAD

**Issue by liukangcc** [emscripten-core/emscripten#12687]
```
#define _GNU_SOURCE

#include <stdio.h>
#include <signal.h>

#if defined(__EMSCRIPTEN__) 
#include <emscripten.h>
#endif

int main(void)
{
    sigset_t sigmask;
    int sig;
    sigwait(&sigmask, &sig);
    printf("hello, world!\n");

    return 0;
}
```

>> emcc main.c -s LLD_REPORT_UNDEFINED -o main.html -v 

when i use emcc compile main.c file, i got the error message :  **wasm-ld: error: /tmp/emscripten_temp_b9h8rtoz/main_0.o: undefined symbol: sigwait**
how can i use signal in emcc, looking forward to a reply.

**Comment by sbc100** [comment]
emscripten doesn't currently implement signals.   Signals are form of control flow that doesn't match well with JS or WebAssembly so implementing them in useful way would be difficult.

We can add stubs for this that trap at runtime instead of compile time if you like?  But I suspect from your question you actually want them to work at runtime.

**Comment by thread-liu** [comment]
> emscripten doesn't currently implement signals. Signals are form of control flow that doesn't match well with JS or WebAssembly so implementing them in useful way would be difficult.
> 
> We can add stubs for this that trap at runtime instead of compile time if you like? But I suspect from your question you actually want them to work at runtime.

I wanted to run the RTOS (such as RT-Thread, FreeRTOS or some other RTOS) on the browser, So I need signal to control the communication between threads. 

How can i  add stubs for this that trap at runtime instead of compile time? 

Thank you for your reply.

**Comment by sbc100** [comment]
You can either just add sub version is you source code or you can add them to `src/library_signal.js`.
