### ISSUE TITLE
emsdk on RaspberryPI 4, 64bit

### ISSUE THREAD

**Issue by altineller** [emscripten-core/emscripten#12695]
Hello, 

What are my options for getting emsdk on a raspberry pi 4 host? I have been trying to compile it from source, but the process crashes the RPI4.

How can I pass -j2 instead of the default -j3 to cmake while compiling LLVM?

Best regards,
Can

**Comment by juj** [comment]
Try just editing the emsdk.py file directly to remove the `-j` directive, i.e. replace https://github.com/emscripten-core/emsdk/blob/40780130aa995872b777468c9ed60afe45af6601/emsdk.py#L980 with 

```py
make = ['cmake', '--build', '.']
```

for a singlethreaded build.

**Comment by juj** [comment]
Btw curious to hear how well RPi4 will work out, have been meaning to do a RPi4 setup at some point as well.

**Comment by altineller** [comment]
@juj it is going very slow. I now am compiling for 64bits, but I have succeeded to compile 32bits on RPI4 before. Thank you.

also, I have found out in the last minutes, passing -j2 as an argument also works. like ./emsdk install something -j2

**Comment by sbc100** [comment]
I think @brion is planning on adding pre-built binaries that might work for you: https://github.com/emscripten-core/emsdk/issues/547
