### ISSUE TITLE
emcc meddling with unrelated files on the filesystem

### ISSUE THREAD

**Issue by boris-kolpackov** [emscripten-core/emscripten#12709]
I've been trying to figure out this bizarre behavior where files change sporadically during build. After initially suspecting myself going insane I've eventually tracked it down to `emcc`:

```
$ touch test.o.ii
$ echo junk >test.d
$ echo good >test.o.d
$ cat test.o.d
good
$ em++ -o test.o -c -x c++ test.o.ii
$ cat test.o.d
junk
```

So it looks like `emcc` copied `test.d` to `test.o.d` for some reason. I suspect (but not sure) it has something to do with this code: https://github.com/emscripten-core/emscripten/blob/master/emcc.py#L2097. I am observing this behavior with Emscripten 2.0.8.

**Comment by sbc100** [comment]
Wow, that is a pretty subtle issue.   I think maybe it started showing up with recent changes to attempt to write directly to the output location where possible.  Investigating now.

**Comment by sbc100** [comment]
Thanks for this report, it motivated me to make this cleanup which is long overdue: https://github.com/emscripten-core/emscripten/pull/12710
