### ISSUE TITLE
LGPL-licensed freealut misrepresented as part of emscripten

### ISSUE THREAD

**Issue by jonassmedegaard** [emscripten-core/emscripten#12711]
Main code files below `tests/third_party/freealut` contain the standard emscripten copyright boilerplate referring to `LICENSE` file for licensing, despite a) file `tests/third_party/freealut/README` stating an LGPL license, and b) file `LICENSE` not covering LGPL.

The file `LICENSE`does at the end make a loose exception for for "The third_party/ subdirectory" which arguably also covers tests/third-party files, but then it does not make sense to add that standard boilerplate.

Please either clarify more explicitly the relationship between LGPL licensing and Emscripten copyright for freealut code files, or simply remove that boilerplate if it was applied in error.

**Comment by sbc100** [comment]
Thanks!  It looks like #7116 was look overzealous and didn't take into account third party code in the test directory.
