### ISSUE TITLE
Cannot port MLIR to WebAssembly

### ISSUE THREAD

**Issue by daquexian** [emscripten-core/emscripten#12722]
I'm trying to port MLIR to WebAssembly, but when I compile mlir-opt in release mode and run it, I got "Uncaught RuntimeError: memory access out of bounds", then I compile it in debug mode and run it again, I got the following error message:

<details>
<summary> Detailed error message </summary>

> $ cat ~/files/mbv2-160.mlir| node bin/mlir-opt.js
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Calling stub instead of sigaction()
> Assertion failed: (PtrWord & ~PointerBitMask) == 0 && "Pointer is not sufficiently aligned", at: /home/dev/files/repos/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h,179,updatePointer
> exception thrown: RuntimeError: abort(Assertion failed: (PtrWord & ~PointerBitMask) == 0 && "Pointer is not sufficiently aligned", at: /home/dev/files/repos/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h,179,updatePointer) at Error
>     at jsStackTrace (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1672:19)
>     at stackTrace (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1689:16)
>     at abort (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1402:44)
>     at ___assert_fail (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1695:7)
>     at llvm::PointerIntPairInfo<mlir::Attribute, 1u, llvm::PointerLikeTypeTraits<mlir::Attribute> >::updatePointer(long, mlir::Attribute) (wasm-function[36176]:0x626f6a)
>     at llvm::PointerIntPair<mlir::Attribute, 1u, bool, llvm::PointerLikeTypeTraits<mlir::Attribute>, llvm::PointerIntPairInfo<mlir::Attribute, 1u, llvm::PointerLikeTypeTraits<mlir::Attribute> > >::setPointer(mlir::Attribute) & (wasm-function[175193]:0x2302b3b)
>     at mlir::NamedAttrList::getDictionary(mlir::MLIRContext*) const (wasm-function[175191]:0x2302a04)
>     at mlir::detail::Parser::parseAttribute(mlir::Type) (wasm-function[147948]:0x1df94e8)
>     at mlir::detail::Parser::parseAttributeDict(mlir::NamedAttrList&)::$_1::operator()() const (wasm-function[148377]:0x1e10278)
>     at mlir::ParseResult llvm::function_ref<mlir::ParseResult ()>::callback_fn<mlir::detail::Parser::parseAttributeDict(mlir::NamedAttrList&)::$_1>(long) (wasm-function[147998]:0x1e01bcf),RuntimeError: abort(Assertion failed: (PtrWord & ~PointerBitMask) == 0 && "Pointer is not sufficiently aligned", at: /home/dev/files/repos/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h,179,updatePointer) at Error
>     at jsStackTrace (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1672:19)
>     at stackTrace (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1689:16)
>     at abort (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1402:44)
>     at ___assert_fail (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1695:7)
>     at llvm::PointerIntPairInfo<mlir::Attribute, 1u, llvm::PointerLikeTypeTraits<mlir::Attribute> >::updatePointer(long, mlir::Attribute) (wasm-function[36176]:0x626f6a)
>     at llvm::PointerIntPair<mlir::Attribute, 1u, bool, llvm::PointerLikeTypeTraits<mlir::Attribute>, llvm::PointerIntPairInfo<mlir::Attribute, 1u, llvm::PointerLikeTypeTraits<mlir::Attribute> > >::setPointer(mlir::Attribute) & (wasm-function[175193]:0x2302b3b)
>     at mlir::NamedAttrList::getDictionary(mlir::MLIRContext*) const (wasm-function[175191]:0x2302a04)
>     at mlir::detail::Parser::parseAttribute(mlir::Type) (wasm-function[147948]:0x1df94e8)
>     at mlir::detail::Parser::parseAttributeDict(mlir::NamedAttrList&)::$_1::operator()() const (wasm-function[148377]:0x1e10278)
>     at mlir::ParseResult llvm::function_ref<mlir::ParseResult ()>::callback_fn<mlir::detail::Parser::parseAttributeDict(mlir::NamedAttrList&)::$_1>(long) (wasm-function[147998]:0x1e01bcf)
>     at abort (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1408:11)
>     at ___assert_fail (/home/dev/files/repos/llvm-project/build-wasm-8d0fdd/bin/mlir-opt.js:1695:7)
>     at llvm::PointerIntPairInfo<mlir::Attribute, 1u, llvm::PointerLikeTypeTraits<mlir::Attribute> >::updatePointer(long, mlir::Attribute) (wasm-function[36176]:0x626f6a)
>     at llvm::PointerIntPair<mlir::Attribute, 1u, bool, llvm::PointerLikeTypeTraits<mlir::Attribute>, llvm::PointerIntPairInfo<mlir::Attribute, 1u, llvm::PointerLikeTypeTraits<mlir::Attribute> > >::setPointer(mlir::Attribute) & (wasm-function[175193]:0x2302b3b)
>     at mlir::NamedAttrList::getDictionary(mlir::MLIRContext*) const (wasm-function[175191]:0x2302a04)
>     at mlir::detail::Parser::parseAttribute(mlir::Type) (wasm-function[147948]:0x1df94e8)
>     at mlir::detail::Parser::parseAttributeDict(mlir::NamedAttrList&)::$_1::operator()() const (wasm-function[148377]:0x1e10278)
>     at mlir::ParseResult llvm::function_ref<mlir::ParseResult ()>::callback_fn<mlir::detail::Parser::parseAttributeDict(mlir::NamedAttrList&)::$_1>(long) (wasm-function[147998]:0x1e01bcf)
>     at llvm::function_ref<mlir::ParseResult ()>::operator()() const (wasm-function[148432]:0x1e13986)
>     at mlir::detail::Parser::parseCommaSeparatedList(llvm::function_ref<mlir::ParseResult ()>) (wasm-function[148431]:0x1e137de)
> </details>

Is there any possible reason? Thanks!

**Comment by kripken** [comment]
Hard to say from just that error - many possible things could be wrong. There are some compiler flags that can help,

https://emscripten.org/docs/porting/Debugging.html#compiler-settings

and also sanitizers,

https://emscripten.org/docs/debugging/Sanitizers.html

**Comment by daquexian** [comment]
@kripken thanks! It turns out to be an issue of mlir on 32-bit platforms. I submitted a patch to mlir: https://reviews.llvm.org/D91062
