### ISSUE TITLE
[Feature request] A way to remove unused WASI imports for standalone wasm without main function

### ISSUE THREAD

**Issue by djytw** [emscripten-core/emscripten#12725]
When building a *standalone* wasm library *without* main function, several imports from WASI will be included: `args_sizes_get`, `args_get`, and `proc_exit`. In most cases, we never call main function when using wasm in the browser, but the `_start` function with the above imports is still generated, so we have to polyfill these imports in order to load the wasm in the browser.

---

When compiling an *empty file* by `emcc test.c -Os -s STANDALONE_WASM -o test.wasm`, the following code will be generated, which I believe a main function like `int main(int , char**){}` is generated by emcc.

```wasm
...
  (import "wasi_snapshot_preview1" "args_sizes_get" (func $wasi_snapshot_preview1.args_sizes_get (type $t2)))
  (import "wasi_snapshot_preview1" "args_get" (func $wasi_snapshot_preview1.args_get (type $t2)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $wasi_snapshot_preview1.proc_exit (type $t4)))
  (import "env" "main" (func $env.main (type $t2)))
...
  (func $_start (type $t3)
    call $f6
    call $wasi_snapshot_preview1.proc_exit
    unreachable)
...
```

The first two imports can be removed, by creating a main function without parameter:

```c
int main() {}
```

then compile with the same command, this time a much simpler wasm generated:

```wasm
...
  (import "wasi_snapshot_preview1" "proc_exit" (func $wasi_snapshot_preview1.proc_exit (type $t2)))
...
  (func $_start (type $t1)
    i32.const 0
    call $wasi_snapshot_preview1.proc_exit
    unreachable)
...
```
But there is still a WASI import `proc_exit` that cannot be removed.

The last import can be removed by creating a forever loop, like
```c
int main() {
    while(1);
}
````
Then there will be no WASI imports. But this is really not an elegant way.

---

So the request is, a way to prevent generating these unnused WASI imports. For example, a way to overwrite the _start function, or a parameter to generate empty _start.

**Comment by sbc100** [comment]
If you want to create program without a main function you need to pass `--no-entry` to the linker.

The first command you posted should error with `undefined symbol: main` so there is obvious a bug there.     But `--no-entry` will solve your problem.

**Comment by sbc100** [comment]
I see, the problem is that undefined symbols are only reported when building to JS.   If you change your output filename to test.js then you can the error I was expecting:

```
$ emcc test.c -Os -s STANDALONE_WASM -o test.js 
error: undefined symbol: main (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _main may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
warning: To build in STANDALONE_WASM mode without a main(), use emcc --no-entry
Error: Aborting compilation due to previous errors
emcc: error: '/home/sbc/dev/wasm/emsdk/node/12.18.1_64bit/bin/node /home/sbc/dev/wasm/emscripten/src/compiler.js /tmp/tmpdqm8fn0c.txt' failed (1)
```

If even gives you the specific advice about adding `--no-entry`.

I am investigating that regression that stopping printing this error when outputting directly to wasm.

**Comment by djytw** [comment]
Thanks!
