### ISSUE TITLE
emscripten/wire.h:68:18: error: missing binary operator before token "("

### ISSUE THREAD

**Issue by ghdqh1515** [emscripten-core/emscripten#12724]
emscripten/wire.h:68:18: error: missing binary operator before token "("
 #if __has_feature(cxx_rtti)

I haven't edited the source Why is this error popping up?

Centos7 / GCC 4.8.5 / C++11

**Comment by curiousdannii** [comment]
You can't compile Emscripten projects with GCC. You need to use LLVM/Clang, and unless you know what you're doing, you shouldn't even use your OS's copy of LLVM, but should use the complete environment provided by emsdk.
