### ISSUE TITLE
Support -msse4 alias to -msse4.2

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#12746]
Just ran into this while porting a real project. On native x86 target Clang supports `-msse4` as an alias for `-msse4.2`, however Emscripten seems to ignore it and pass as-is to the underlying Clang (making it no-op). cc @juj @tlively @sbc100

**Comment by juj** [comment]
Supporting `-msse4` sounds good to me.

**Comment by giatorta** [comment]
Hi, I would like to take this issue as my "first bug", if it's ok I'd have two questions: 

- what does it mean "Emscripten ignore it and pass as-is to the underlying Clang (making it no-op)" ? 
wouldn't passing it to Clang make Clang process it correctly as an alias?

- I guess emcc is the program that is involved in calling Clang and that should be modified to fix the issue?

thank you for the advice!

**Comment by RReverser** [comment]
@giatorta Best way is to look at places in Emscripten codebase where "-msse4.2" occurs and see how to add "-msse4" there so that it would behave in the same way.

**Comment by giatorta** [comment]
@RReverser thanks for the hint, I think I now understand what I have to fix. Currently working on it in my fork of the repo...
