### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by nxtexe** [emscripten-core/emscripten#12750]
How do I target webgpu from emscripten? i.e. How do I write webgpu code in C/C++ to compile and run on the web using emscripten?

**Comment by kainino0x** [comment]
You can build with `-s USE_WEBGPU=1` and the WebGPU headers will be available.
In C: `#include <webgpu/webgpu.h>`
In C++: that, or `#include <webgpu/webgpu_cpp.h>`

There are a few other emscripten-specific functions. See here for example:
https://github.com/kainino0x/webgpu-cross-platform-demo/blob/e5c162a48db35de9eb7df73610f2e46d21ee6cd8/main.cpp
And most importantly note preinitializedWebGPUDevice must be set before initializing the module:
https://github.com/kainino0x/webgpu-cross-platform-demo/blob/e5c162a48db35de9eb7df73610f2e46d21ee6cd8/index.html#L227

**Comment by nxtexe** [comment]
> You can build with `-s USE_WEBGPU=1` and the WebGPU headers will be available.
> In C: `#include <webgpu/webgpu.h>`
> In C++: that, or `#include <webgpu/webgpu_cpp.h>`
> 
> There are a few other emscripten-specific functions. See here for example:
> https://github.com/kainino0x/webgpu-cross-platform-demo/blob/e5c162a48db35de9eb7df73610f2e46d21ee6cd8/main.cpp
> And most importantly note preinitializedWebGPUDevice must be set before initializing the module:
> https://github.com/kainino0x/webgpu-cross-platform-demo/blob/e5c162a48db35de9eb7df73610f2e46d21ee6cd8/index.html#L227

Thanks mate
