### ISSUE TITLE
warning: no output file specified, not emitting output (in "handle_final_wasm_symbols" context)

### ISSUE THREAD

**Issue by r-pankevicius** [emscripten-core/emscripten#12755]
I got this warning for no apparent reasons.

According to Sam Clegg: It looks like this message is coming from wasm-opt and is always printed when `--emit-symbol-map` is used.

I've ran into the issue on Windows 10 but later checked on Linux and it's there, too. I'll describe it from Windows perspective, but you'll be able to replay it on Linux (I've tried it on Google Cloud Console).

Steps to reproduce.
--------------------------
1. Copy two files benchmark_utf8.cpp and utf8_corpus.txt from Emscripten test suite to a separate new folder.
2. cd to that folder, run a command:
`emcc benchmark_utf8.cpp -s "EXTRA_EXPORTED_RUNTIME_METHODS=['UTF8ToString']" --emit-symbol-map  --source-map-base http://localhost:8080/whatever/ -o benchmark_utf8-wasm-with-semit-symbol-map.html --embed-file utf8_corpus.txt -g4
`

Expected: all fine.
Actual: a warning
`warning: no output file specified, not emitting output`

Add -v switch to the command line in step 2 and you'll see surroundings of the warning (handle_final_wasm_symbols):
building:DEBUG: handle_final_wasm_symbols
warning: no output file specified, not emitting output

I'm not sure if I miss something in arguments list or it is the issue.

**Comment by r-pankevicius** [comment]
Version for book keeping (November 10th is designated as International Accounting Day):
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 2.0.8 (d059fd603d0b45b584f634dc2365bc9e9a6ec1dd)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by r-pankevicius** [comment]
Started: https://groups.google.com/g/emscripten-discuss/c/cyL-iSbhE54

**Comment by sbc100** [comment]
Thanks!  I happened t have the fix already before you posed it.   Did we break the record for speed up bug closing there ? :)

**Comment by r-pankevicius** [comment]
No. You have a second record after https://youtu.be/u31OjOPF-ZI?t=245.

**Comment by r-pankevicius** [comment]
I confirm that warning is gone in version
emcc (Emscripten gcc/clang-like replacement) 2.0.8 (a14e861db1fccab540f7d29a2875a3a52e98abf6)
