### ISSUE TITLE
Linking OpenSSL library while building project

### ISSUE THREAD

**Issue by Juvojic** [emscripten-core/emscripten#12759]
I have written a file `secure-send.c` that includes parts of the OpenSSL library and calls its functions.
I tried to compile it with `emcc secure-send.c -o secure-send.wasm /usr/lib/x86_64-linux-gnu/libcrypto.a` which throws the error:
`wasm-ld: error: unknown file type: pem_all.o`.

I suppose this is a problem specific to the OpenSSL library but moreover, I am not familiar with the standard process of using libraries with emscripten. The documentation pages just say:
```
# Compile the library and code together to HTML
emcc project.o libstuff.a -o final.html
```
which I honestly tried to replicate exactly. 
I'm assuming that the predelivered libcrypto.a has been built correctly - I am able to use it without any issues with GCC.

**Comment by sbc100** [comment]
`/usr/lib/x86_64-linux-gnu/libcrypto.a` is a system library built for x86_64 linux.  You can't use that (or any other library from your system directory) with emscripten.

Any library that you use with emscripten needs to be specifically compiled with emscripten.

**Comment by Juvojic** [comment]
Thank you a lot for pointing me in the right direction! 
I actually did succeed to build the OpenSSL library with: 

1. cloning the OpenSSL repository
2. `emcmake ./Configure gcc -no-asm  //you may want to specify another compiler here` 
3. changing `CROSS_COMPILE = .../emsdk/upstream/emscripten/em` to `CROSS_COMPILE =` in the `Makefile`
4. `emmake make`

Thanks to https://asyncoder.com/2020/01/02/Mac%E4%B8%8A%E7%BC%96%E8%AF%91openSSL%E5%88%B0WebAssembly/ for providing an example and source code for `MACOS`.

**Comment by NefixEstrada** [comment]
For future reference, I ended up using:

```
emconfigure ./Configure \
  no-hw \
  no-shared \
  no-asm \
  no-threads \
  no-ssl3 \
  no-dtls \
  no-engine \
  no-dso \
  linux-x32 \
  -static
```

Without all this flags, it did compile and link, but OpenSSL wasn't behaving correctly. With this it works (at least for RSA) as expected!
