### ISSUE TITLE
Print warnings for scalarized SIMD intrinsics in verbose mode

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#12765]
When porting existing projects, I find it useful to understand which SSE instructions were "properly" translated to Wasm SIMD, and which fallback to a scalarized mode. I think this data would also help with prioritising particularly popular intrinsics.

Right now, the only way to find those is to manually grep for all `_mm_\w+` matches in the codebase, pass through sort & uniq, and manually check the tables at https://emscripten.org/docs/porting/simd.html, which is a bit cumbersome.

Could we print warnings for scalarised intrinsics during the build time instead (only once per each intrinsic and only in verbose build mode)?

**Comment by shatlyktma** [comment]
Intra code server

**Comment by RReverser** [comment]
I guess I'll close this as per https://github.com/emscripten-core/emscripten/issues/12871#issuecomment-839023306 since they appear to be duplicates and the newer issue is already referenced in a merged PR.

**Comment by tlively** [comment]
Thanks for filing this, though, @RReverser :)
