### ISSUE TITLE
Is gen_struct_info.py a user-facing tool?

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#12771]
It can clearly be useful for external users to want to extract struct information, but we don't document this tool anywhere.

Also, the only internal use of this tool is with `src/struct_info.json` as input, which means we currently don't have any testing the direct parsing of header files.   This is feature I did not even know it had.  

See #12758 

If gen_struct_info.py is designed for external use we should generate .bat/sh launcher for it and document its existence.

I think we should also consider dropping the c parser stuff and have it require json input.   That is unless we want to add some tests of the c parser.   (which currently requires a 3rd party python module).

**Comment by sbc100** [comment]
It looks like the C parsing feature goes way back to the original design of the tool in e0cd2c4078c5dbaecda881c9258f01d5069a1d02 but I'm not sure emscripten it self ever used this.

**Comment by sbc100** [comment]
@ngld

**Comment by ngld** [comment]
I originally wrote the C parsing logic hoping that I could run `gen_struct_info.py` directly against C headers to generate `struct_info.compiled.json`. However, that turned out to be impractical because `pycparser` isn't robust enough to parse most C headers. To solve that issue I added `struct_info.json` and used it instead. I honestly have no idea if that part still works.

I agree that `gen_struct_info.py` is useful for external users. Most of it should be documented in the file itself. As far as I know `gen_struct_info.py` is only used by Emscripten to generate the `struct_info.compiled.json` if it's not already cached.

**Comment by jkbbwr** [comment]
Is `libclang` a possibility? After doing some research it seemed like it might provide a simple way to leverage clangs internal AST for grabbing struct info

**Comment by sbc100** [comment]
I don't know if its something we need internally for emscripten... most of out struct usage seems OK with the current setup, and we are trying to move away from implementing libraries in JS as much as possible and towards native libraries.   There may be more external users, but #12758 is the first request I've seen.

**Comment by jkbbwr** [comment]
I assume you are moving towards embind?
I found it overly complicated to achieve what I was trying to do and that lead to managing lifetimes and resources hard. Plus C++ seemed to add a lot of complexity to a simple C project.

Its interesting getting your perspective on these things.

**Comment by sbc100** [comment]
No we don't use embind internally.  But where ever possible we are aiming to implement stuff in C in the system libraries.   If JS is doing a lot of struct manipulation than that seems like a sign that the code in question could be moved to C.   Not always but often.

**Comment by jkbbwr** [comment]
So one of the ways I was thinking of controlling lifetimes was via callbacks so the JS/Wasm land code looks like this

```js
createReader(..., (reader) => {
    console.log(reader.read_string(1));
});
```

The underlying C api looks something like this

```c
reader_t reader;
init_reader(&reader);
read_string(&reader, 1);
dispose_reader(&reader);
```

Do you think I could map the javascript callback to a function pointer and then move this C side? 
Hmmmmmmm
