### ISSUE TITLE
Output of  `em++ -dumpmachine` is inconsistent and breaks tooling

### ISSUE THREAD

**Issue by Klaim** [emscripten-core/emscripten#12770]
Note: To be clear, while this issue is minor, it makes tooling development a little bit more painful than it could be or is with other compilers.

Observed
----------

After a fresh install from sources of emscripten, the first invocation of `em++ -dumpmachine` will output first this line before the real output:
```
shared:INFO: (Emscripten: Running sanity checks)
```
Any future invocation will then never output this line.

When a tool relies on invoking `em++ -dumpmachine` they parse the output value directly. This will fail at the very first invocation after installation, but not afterwards, making working with `em++` looking midly inconsistent.

I'm hitting a concrete example using `build2` (https://build2.org): when initializing a configuration where we specified to use `em++` (or `emcc`) as compiler, `build2` will first invoke `em++ -dumpmachine` (with some other flags) to gather information about the target configuration. 

Note that this sanity check output line is not output with other info commands like `em++ --version`.

Expected
---------

Consistent output for the same command executed with the same input and environment.

How To Reproduce
-------------------

```
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
git pull
./emsdk install latest
./emsdk activate latest

source ./emsdk_env.sh
em++ --version  # Consistent: output will always be the same.
em++ -dumpmachine # Inconsistent: additional output "shared:INFO: (Emscripten: Running sanity checks)"
em++ -dumpmachine # Consistent from now on.

```

Proposition
------------

Either one of these would be fine to me (and probably to tool implementers):
- Do not output that line, except using a flag to explicitly do the sanity checks;
- Never run sanity checks without the user invoking a specific command to do that;
- Output that line by default, but have a flag to not output it, that can be used with all commands generated by tools;
- Do not do sanity checks for `-dumpmachine` command, in the same way `--version` does not do sanity checks.

Workaround
-------------

Invoke `em++ -dumpmachine` manually or via scripts before doing any work with the compiler. That works but looks like it could be avoided.

**Comment by sbc100** [comment]
I have fix which delays the sanity checks until after `-dumpmachine`.

However I did notice that `-dumpmachine` writes the machine info to stdout.. and the logging message go to stderr.   Perhaps that tool that its reading the output of `-dumpmachine` might be better of only reading stdout?   What tools are you specifically having issue with?

**Comment by sbc100** [comment]
Sorry I see you mention `build2`... can it be taught to only look at the stdout of `em++ -dumpmachine`?

**Comment by boris-kolpackov** [comment]
> Can it be taught to only look at the stdout of `em++ -dumpmachine`

It's complicated: the code is the same for GCC and Clang, which covers a wide range of versions as well as pseudo-GCC compilers (common in the embedded world). Merging `stderr` with `stdout` makes sure that we handle the result regardless of where it is written. There is also another aspect: some versions/pseudo-compilers do not support `-dumpmachine` in which case we fallback to something else. In other words, the failure of this test is not fatal, which means we need to suppress any diagnostics that might be issued during such failure.

Also, more generally, I wonder what is the motivation for printing such debug messages without the caller asking for them? Let's say we (as in, `build2`) didn't have to merge and let `stderr` go to the terminal. That would mean that now the user would see some confusing diagnostics that doesn't appear to be associated with any command being executed (the command for the above test is only displayed at a fairly high verbosity level).

**Comment by sbc100** [comment]
Its mostly historical.   I guess emscripten users/developers wanted to know when the sanity checks were run.

Anyway, by fix should make your use case happy.
