### ISSUE TITLE
For consideration: FS as member of Module

### ISSUE THREAD

**Issue by warpcoil** [emscripten-core/emscripten#12781]
Do you think it might be an idea to mount FS under the Module object for ease of access when using ES6

Like:

`var FS = Module.FS = {root:null,mounts:[]....`

instead of `var FS = {root:null,mounts:[].... etc`

Resulting in:

```
import('./bin/7za.js').then((exp) => {

  var Module = {}

  Module.preInit = () => {
      Module.FS.writeFile(`/${filename}`, new Uint8Array(buffer))
  }

  exp.default(Module)
}
```

Now I'm relatively new to ES6 and a little old skool

I can't seem to access FS methods (as they aren't exported)

**Comment by curiousdannii** [comment]
Compile with this option

```
-sEXTRA_EXPORTED_RUNTIME_METHODS=['FS']
```

**Comment by warpcoil** [comment]
Ah, there is it.  Now you have Module.FS . . .

Thank you
