### ISSUE TITLE
missing copyright and licensing for files derived from Sphinx

### ISSUE THREAD

**Issue by jonassmedegaard** [emscripten-core/emscripten#12794]
it seems the files below `site/source/_themes/emscripten_sphinx_rtd_theme` are derived from the Sphinx project, and most likely at least some of the original files were copyright protected, yet only two files contain copyright and licensing statements.

Furthermore, the licensing statement that is included references a missing `LICENSE` file:
> :copyright: Copyright 2007-2013 by the Sphinx team, see AUTHORS.
> :license: BSD, see LICENSE for details.

**Comment by jonassmedegaard** [comment]
The referenced `AUTHORS` file is missing as well.

**Comment by jonassmedegaard** [comment]
No, bot: this issue does not magically fix itself by applying time!

**Comment by lavender-agatha** [comment]
If there was an upvote option I would upvote this one.

It might not seem relevant, but it is.

**Comment by kripken** [comment]
Looks like @hamishwillee added those in 2014. Hamish, I think maybe we just forgot to copy the LICENSE file and add the headers at that time - does that sound right?

**Comment by hamishwillee** [comment]
@kripken That is the most likely scenario.

**Comment by kripken** [comment]
Thanks @hamishwillee !

I opened #20849 to add the missing license file. I also added a readme with a link to upstream.

I don't think anything more is needed, as skimming the upstream files, they do not have a license header in every single one. So AFAIK the only thing that was missing is the license file.
