### ISSUE TITLE
testsuite ignores LLVM_ADD_VERSION for llvm-dwarfdump

### ISSUE THREAD

**Issue by jonassmedegaard** [emscripten-core/emscripten#12799]
File `tests/test_core.py` resolves a local LLVM_DWARFDUMP instead of reusing config.LLVM_DWARFDUMP.

**Comment by sbc100** [comment]
Side note:  I would advise against using LLVM_ADD_VERSION if possible.  It normally implies that you are trying to use emscripten with a stable llvm version, and we don't generally support that.  See #11362.    Until we fix that we it would be dangerous to try to use emscripten with any llvm version except that one explicitly referenced in a given release.

**Comment by jonassmedegaard** [comment]
Quoting Sam Clegg (2020-11-17 19:54:37)
> Side note:  I would advise against using LLVM_ADD_VERSION if possible.  It normally implies that you are trying to use emscripten with a stable llvm version, and we don't generally support that.  See #11362.    Until we fix that we it would be dangerous to try to use emscripten with any llvm version except that one explicitly referenced in a given release. 

Thanks, I am aware that emscription project officially support only llvm which is not officically supported yet by llvm project itself.  For my use-case - packaging emscripten for Debian - it is not an option to chase latest and greatest tools continuously, not to use unmaintained historic snapshots as apparently is the "solution" for issue#11362.

Just to explain since you brought it up - I am interested in discussing that further but we should probably do that somewhere else than in this issue (and seems to me that issue#11362 is unsuitable as well, as I hinted above).

**Comment by sbc100** [comment]
It seem to me that #11362 is exactly right place to discuss that issue.. you want to support stable llvm versions, right?   that is *exactly* that bug is about.  I'm not sure what you mean by "unmaintained historic snapshots" but maybe you can bring that up on that issue?

**Comment by jonassmedegaard** [comment]
seems you did not want my input at #11362 after all, @sbc100 - I am puzzled why you encouraged me :-(

**Comment by sbc100** [comment]
Sorry, I didn't mean to shut you down,  I'm just trying to find a way for us to find a solution that works, given limited resources.    You all (debian) are one of the driving reasons for any work we do in #11362 so I think your input there is vital, even if we don't always agree on direction.   I think we are still exploring the solution space here.

**Comment by jonassmedegaard** [comment]
ok - I lost faith there for a moment. Thanks, you now restored my faith that we are indeed on the same track here... :-)
