### ISSUE TITLE
Support latest `ws` library on Node.js

### ISSUE THREAD

**Issue by Bannerets** [emscripten-core/emscripten#12813]
Hello,
In library_sockfs.js there are these lines:

```javascript
opts = ENVIRONMENT_IS_NODE ? {'protocol': subProtocols.toString()} : subProtocols;
// ...
ws = new WebSocketConstructor(url, opts);
// ...
peer.socket.on('message', function(data, flags) {
  if (!flags.binary) {
```

This doesn't work correctly with latest `ws@7`, the protocol option doesn't exist anymore (it should be passed in the second argument, like in the browsers), and the flags argument doesn't seem to be passed anymore.

Could the code be updated to support the latest ws?

I'm not sure if #10264 is related, I'm not talking about tests

**Comment by sbc100** [comment]
Oh, we list `ws` as a devDependency only.    I didn't realize it was also used in production I guess we should move that to a regular dependency in `package.json`.

In any case, it sounds like basically the same issue as #10264.   Feel free to try to do the upgrade and send a PR.
