### ISSUE TITLE
Imply -fno-inline when debug info is requested

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#12829]
Emscripten already disables some optimisations when compiling with `-g` to improve debugging experience (including Closure.

Right now, inlining doesn't work great with debugging breakpoints, so I suggest we auto-disable it too by passing `-fno-inline` to the underlying Clang when debug info is enabled to make the default experience a bit better until tools catch up and can support complex inlining scenarios. /cc @bmeurer

**Comment by sbc100** [comment]
I think the rule with `-g` is that it should not have any effect on code generation.    

(If emscripten is violating that rule we should probably fix that.)

**Comment by RReverser** [comment]
> is that it should not have any effect on code generation

At least, it already disables Closure for JS by default... why not disable some opts in Wasm too?

**Comment by sbc100** [comment]
I believe its a general rule that `-g` should not effect code generation.  I'm not sure where its written down but it came up a few times when I was working on wasm-ld.     The idea is that you explicitly set your opt level and your debug level separately in your different configuration.  Most debug builds would already disable this optimizations like this, right?

If your desire is actually to debug a release build.. (Is that your desire in this case?)  then we would be doing you disservice to turn off optimizations wouldn't we?  Because then you are not actually debugging your release build anymore, but something in-between.

**Comment by RReverser** [comment]
Yeah I can certainly see that point and agree with it in general.

I guess the difference I see about this particular case is, if you can't debug inlined functions (which you can't right now), would it be a bigger harm to keep such functions inlined but undebuggable, or debuggable but not inlined / less optimised.

I'm slightly leaning towards the "not inlined" preference, but I can see how it can be a problem if someone creates actual release builds with intent to ship as-is but with debug info still produced in a separate file.

**Comment by sbc100** [comment]
Perhaps we could have another flag which which means `-Oreasonably-debuggable`?   Although I'm not sure how that would differ to `-O0`?

**Comment by sbc100** [comment]
The main thing is that I think the `-Oreasonably-debuggable` should be explicit and not enable implicitly just when `-g` is added.

**Comment by RReverser** [comment]
Ok, but coming back to earlier question - shouldn't this mean that Closure also should stay enabled even in debug mode?

**Comment by sbc100** [comment]
Yeah, I think `-g` should not change the executing code, and running closure certainly seems like it does that!

**Comment by kripken** [comment]
Regarding closure, the idea is that when closure runs it destroys debug info in JS - function names, local names, comments, etc. - so we have not choice but to not run it in a debug build. If there were a way to run its optimizations without affecting debug info, we would do that.

Seems reasonable to me to have a setting for "reasonable debuggability" if that can help. What other things would it affect aside from inlining?

**Comment by RReverser** [comment]
> If there were a way to run its optimizations without affecting debug info, we would do that.

Ah. Have you tried `--debug` by any chance? It's not perfect, because it still does variable renaming/wrapping, but it tries to preserve recognisable original names even in fully-optimised mode. Maybe it could be reasonable enough for optimisations+debug builds?

**Comment by kripken** [comment]
I haven't tried that, interesting. It would increase build times in those modes, however, and I'm not sure it would provide much benefit, as those builds are not shipped anyhow? But I agree it would be technically more correct to do.

**Comment by RReverser** [comment]
I believe we can close this; the Closure + `--debug` can be a separate discussion.
