### ISSUE TITLE
Range of pointer addresses

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#12831]
I have a legacy code which works something like this:
```cpp
#include <iostream>

using namespace std;

bool fun(int *p) {
    return p==nullptr ? true : false;
}

typedef bool (*fun_ptr)(int *p);

fun_ptr arr[2] = {
    reinterpret_cast<fun_ptr>(1), // any number less than 256
    reinterpret_cast<fun_ptr>(fun)
}

int main() {
    for(int i=0; i<2; ++i) {
        if(arr[i] < 256) {
            // This is a number not a function pointer
        }
        else {
            // This is a function pointer
        }
    }
    return 0;
}
```

This code was working on version `1.38.28` because all function pointers were having values greater than 256.
But with the latest version, I am seeing values less than 256 which is breaking our code.
I know this is not a good coding style but considering it is a legacy code and hard to change, is there any way in which I can set a minimum limit on pointer addresses.

**Comment by sbc100** [comment]
Function pointers are integers that happen to start 1.    This is currently hardcoded into LLVM and has always been true for the wasm backed.  I'm guess maybe you are saying that it wasn't try back in the fastcomp days.

It hard for me to imagine the kind of code that would be broken by this.  It certainly seems like the code itself its broken, and not the compiler.  

Changing the function pointer range to start at some other value other than 1 would be be easy, and would require modifications on the llvm side.
