### ISSUE TITLE
Add HarfBuzz flag to SDL2_ttf 

### ISSUE THREAD

**Issue by mehdisadeghi** [emscripten-core/emscripten#12845]
The [current SDL_ttf port](https://github.com/emscripten-core/emscripten/pull/3728) is apparently very old (5 years?) and lacks new features.

It is currently possible to compile SDL ttf with USE_UARFBUZZ flag which would enable  more complex script support.

I'd happily work on a PR if your consider the update and perhaps point me to the current compile/port scripts, since I didn't find them anywhere. Thanks.

**Comment by kripken** [comment]
A PR would be great!

The relevant code is in `tools/ports/sdl2_ttf.py` I believe. If we also need to update the port itself, that is at https://github.com/emscripten-ports/SDL2_ttf

**Comment by mehdisadeghi** [comment]
Hi @kripken,

I just made two PRs, one to update this repo and one to update the source. However, in the PR for this repo I'm still pulling the source directly from the SDL2_ttf mercurial repository. If for some reason it should be pulled from the GitHub clone, please le me know and I'll change that.

I'll appreicate your feedback on PR #12868 and PR2 of emscripten-ports/SDL2_ttf/pull/2.

Thanks.
