### ISSUE TITLE
SyntaxError when running emcc

### ISSUE THREAD

**Issue by nbarkhina** [emscripten-core/emscripten#12852]
I installed the latest version of Emscripten on Linux and am getting an invalid syntax error when trying to run emcc.

![image](https://user-images.githubusercontent.com/10982154/99889062-e2772700-2c1f-11eb-9702-5d111b0220a8.png)

I followed the instructions and checked my python version - 

![image](https://user-images.githubusercontent.com/10982154/99889073-f6228d80-2c1f-11eb-8143-c28066cbf7a8.png)

any ideas?

Thanks

**Comment by sbc100** [comment]
emscripten requires python3.  I think you probably need to install python3 and it should work.

**Comment by nbarkhina** [comment]
yes it does have python3 - 

![image](https://user-images.githubusercontent.com/10982154/99892384-63471a80-2c42-11eb-8014-c0ed40b7b944.png)

is there a specific version that I need? I ran this command - 

**sudo apt-get install python3**

That was the method in the emscripten install documentation

**Comment by sbc100** [comment]
Ah.. you need python 3.6 or above because use using python f-strings which are a 3.6 feature. 

What version of linux are you using?

**Comment by nbarkhina** [comment]
I am on Debian 9 

![image](https://user-images.githubusercontent.com/10982154/99902789-5d772680-2c8e-11eb-8fdb-d32e0fe848bd.png)

Ok I will look into upgrading my python version. What's weird is that in the installation docs it still says version 3.5 (though it is referencing the Mac version)

![image](https://user-images.githubusercontent.com/10982154/99902944-39681500-2c8f-11eb-8315-af5a3e331ed1.png)

Thank you

**Comment by sbc100** [comment]
Sorry, we clearly need to update those instructions.
