### ISSUE TITLE
Upgraded from v2.0.6 to v2.0.7 and above, getting undefined symbols

### ISSUE THREAD

**Issue by MarcelKlammer** [emscripten-core/emscripten#12874]
emsdk install 2.0.7 (and 2.0.8 and 2.0.9) 

While 2.0.6 produced my wasm files without problems, 2.0.7 and above  runs through as well, but produces warnings (see below).

On execution the first error that appears is the missing function _Znwm.

Adding __Znwm to EXPORTED_FUNCTIONS does nothing.

What am I missing here? 

warning: undefined symbol: _ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEmmPKcm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__219__shared_weak_count13__get_deleterERKSt9type_info (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__221__basic_string_commonILb1EE20__throw_length_errorEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__223__match_any_but_newlineIcE6__execERNS_7__stateIcEE (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__26locale4nameEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__26locale9has_facetERNS0_2idE (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__26locale9use_facetERNS0_2idE (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNKSt3__28ios_base6getlocEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcmm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEmc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKcm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignEPKc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertEmPKc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertEmPKcm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6resizeEmc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7replaceEmmPKcm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9push_backEc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_ (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_ (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSEc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_istreamIcNS_11char_traitsIcEEE6sentryC1ERS3_b (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_istreamIcNS_11char_traitsIcEEED0Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_istreamIcNS_11char_traitsIcEEED1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_istreamIcNS_11char_traitsIcEEED2Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE3putEc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_ (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEED0Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEED1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEED2Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEb (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEd (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEf (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEi (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEj (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEl (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEx (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEy (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215__get_classnameEPKcb (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE4syncEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE5imbueERKNS_6localeE (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE5uflowEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE6setbufEPcl (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE6xsgetnEPcl (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE6xsputnEPKcl (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEE9showmanycEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEEC2Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__215basic_streambufIcNS_11char_traitsIcEEED2Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__219__shared_weak_count14__release_weakEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__219__shared_weak_countD2Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__220__get_collation_nameEPKc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__26localeC1ERKS0_ (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__26localeC1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__26localeD1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__28ios_base4initEPv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__28ios_base5clearEj (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__29basic_iosIcNS_11char_traitsIcEEED2Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZNSt3__2plIcNS_11char_traitsIcEENS_9allocatorIcEEEENS_12basic_stringIT_T0_T1_EEPKS6_RKS9_ (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZTv0_n12_NSt3__213basic_istreamIcNS_11char_traitsIcEEED0Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZTv0_n12_NSt3__213basic_istreamIcNS_11char_traitsIcEEED1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZTv0_n12_NSt3__213basic_ostreamIcNS_11char_traitsIcEEED0Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZTv0_n12_NSt3__213basic_ostreamIcNS_11char_traitsIcEEED1Ev (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZdaPv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZdlPv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZdlPvSt11align_val_t (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _Znam (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _Znwm (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZnwmSt11align_val_t (referenced by top-level compiled C/C++ code)
warning: undefined symbol: __cxa_guard_acquire (referenced by top-level compiled C/C++ code)
warning: undefined symbol: __cxa_guard_release (referenced by top-level compiled C/C++ code)

**Comment by sbc100** [comment]
Are you build with `STRICT=1` by any chance?

In 2.0.7 we included this in the ChangeLog:

```
- In STRICT mode we no longer link in C++ mode by default.  This means if you
  are building a C++ program in STRICT mode you need to link via `em++` rather
  than `emcc`.  This matches the behaviour of gcc and clang.
```

**Comment by MarcelKlammer** [comment]
I didn't quite connect the dots. Thanks for pointing at it. It's working now.
