### ISSUE TITLE
function signature mismatch - idbrequest

### ISSUE THREAD

**Issue by cajus** [emscripten-core/emscripten#12894]
emsdk version: _2.0.9_
Build platform: _Linux_

I'm currently migrating a (Qt) project to `cmake` and the final build output seems to differ somewhere. The browser runs into this 

**Stacktrace**
```
0d250d6e:0x25bc62 Uncaught RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[7269]:0x25bc62
    at eval &#40;eval at completeLoadEmscriptenModule (http://10.0.8.201/test/qtloader.js:443:14&#41;, <anonymous>:1:233904)
    at IDBRequest.req.onsuccess (eval at completeLoadEmscriptenModule (http://10.0.8.201/test/qtloader.js:443:14), <anonymous>:1:233351)
```
The Qt build used is exactly the same as for the `qmake` build, so that _should_ work basically.

**Link flags**
```
-s FORCE_FILESYSTEM=1 
-s TOTAL_MEMORY=268435456
-lidbfs.js
--bind
-s FETCH=1
-s WASM=1
-s FULL_ES2=1
-s FULL_ES3=1
-s USE_WEBGL2=1
-s EXIT_RUNTIME=1
-s ERROR_ON_UNDEFINED_SYMBOLS=1
-s EXTRA_EXPORTED_RUNTIME_METHODS=[UTF16ToString,stringToUTF16]
```

Comparing them with the flags used in the `qmake` based build, does not come up with any obvious differences.

What does the message mean, and where can I search for the cause?

**Comment by kripken** [comment]
One option to debug this might be to literally compare object file by object file, to make sure nothing changed. And for the final link command, running with `EMCC_DEBUG=1` will emit enough to compare those as well (just ignore the timing and temp file names).

**Comment by cajus** [comment]
Thanks. There was one old object around. Fixed it ;-)
