### ISSUE TITLE
em++ build flag conflicts with g++ 

### ISSUE THREAD

**Issue by vvarma** [emscripten-core/emscripten#12911]
On compiling boost with em++ getting a conflict for the build flag "-s" 
In gcc:
 -s  Remove all symbol table and relocation information from the
       executable.

in em++:
"-s OPTION[=VALUE]"
   Emscripten build options. For the available options, see
   src/settings.js.

I am still new to this toolchain and the process, so please guide me in how to prevent this from happening.

Following is the log obtained from the build.
###
###
###
###
/home/nvr/work/misc/emsdk/emsdk/upstream/emscripten/em++ --version
emcc (Emscripten gcc/clang-like replacement) 2.0.9 (59aedd441c317b7064146d4d888eab272e92dd03)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

###
###
/home/nvr/work/misc/emsdk/emsdk/upstream/emscripten/em++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
**em++: error: Attempt to set a non-existent setting: '-DNDEBUG'**
 - did you mean one of DYLINK_DEBUG, GL_DEBUG, OPENAL_DEBUG?
 - perhaps a typo in emcc's  -s X=Y  notation?
 - (see src/settings.js for valid values)

**Comment by sbc100** [comment]
We have some code to try to distinguish between the `-s` for the linker and the `-s` for our settings but I guess its not doing the right think in the this case.

We can fix that, but in the mean time I suggest you just stop passing the `-s` flag in emscripten builds.   You might need to modify the boost build system to do this.
