### ISSUE TITLE
can't specify cmake cache args that contain spaces

### ISSUE THREAD

**Issue by justin-hackin** [emscripten-core/emscripten#12919]
Any cmake cache arguement value with a space causes cmake to be called with that arguement/key/value all enclosed in doublequotes.

with singlequotes
```
emcmake cmake . -DCMAKE_C_FLAGS='-s USE_BOOST_HEADERS=1' 
configure: cmake . "-DCMAKE_C_FLAGS=-s USE_BOOST_HEADERS=1" -....
```

same with doublequotes 

```
emcmake cmake . -DCMAKE_C_FLAGS="-s USE_BOOST_HEADERS=1"
configure: cmake . "-DCMAKE_C_FLAGS=-s USE_BOOST_HEADERS=1" ...
```

You can see it works properly if I remove the space

```
emcmake cmake . -DCMAKE_C_FLAGS='-sUSE_BOOST_HEADERS=1'
configure: cmake . -DCMAKE_C_FLAGS=-sUSE_BOOST_HEADERS=1 ...
```

I tried making the type explicit

```
emcmake cmake .  -DCMAKE_CXX_FLAGS:STRING="-s USE_BOOST_HEADERS=1"
configure: cmake . "-DCMAKE_CXX_FLAGS:STRING=-s USE_BOOST_HEADERS=1" 
```

and static 

```
emcmake cmake . -DCMAKE_C_FLAGS:STATIC="-s USE_BOOST_HEADERS=1"
configure: cmake . "-DCMAKE_C_FLAGS:STATIC=-s USE_BOOST_HEADERS=1"
```

I also tried "escaping" the space and the = character with `\`

**Comment by sbc100** [comment]
The quotes are are just an artifact of the fact that we are using "shlex_join" to display the command line.  This allows the command line showen in the output to be copied and pasted onto the command line.

Take a look at https://github.com/emscripten-core/emscripten/blob/dfb6fdadfd68b1478cda4654f55412552f7d8d09/tools/building.py#L338.  If you modify this file and just print the raw argument as a python array you will see that the quotes themselves are not actually passed down to cmake:

e.g.:
```
$ ./emcmake cmake tests/cmake/target_js/ -DCMAKE_C_FLAGS='-s USE_BOOST_HEADERS=1' 
['cmake', 'tests/cmake/target_js/', '-DCMAKE_C_FLAGS=-s USE_BOOST_HEADERS=1', '-DCMAKE_TOOLCHAIN_FILE=/usr/local/google/home/sbc/dev/wasm/emscripten/cmake/Modules/Platform/Emscripten.cmake', '-DCMAKE_CROSSCOMPILING_EMULATOR="/usr/local/google/home/sbc/dev/wasm/emsdk/node/12.18.1_64bit/bin/node"']
```

Are you seeing any adverse effects here?

**Comment by sbc100** [comment]
This is essentially the exact behaviour of `shlex.join`:  It add quotes around arguments that contain spaces.. otherwise the shell would see multiple arguments (https://docs.python.org/3/library/shlex.html#shlex.join)

**Comment by justin-hackin** [comment]
@sbc100 I guess this is a feature and not a bug so closing
