### ISSUE TITLE
Documentation search results un-navigable

### ISSUE THREAD

**Issue by justin-hackin** [emscripten-core/emscripten#12918]
All documentation search results' titles urls contain `undefined` preceding the page query parameters.  Removing the  `undefined`  from the url directs the user to the expected page.  Javascript is funny like that, sounds like it needs a default empty string like `(pageSuffix || '')`.

**Comment by kripken** [comment]
Thanks @justin-hackin !

Looks like this broke when my build machine's OS upgraded sphinx.. the new version indeed has a JS variable that needs a proper value, or the search results fail. Fix in that PR.

**Comment by justin-hackin** [comment]
Thanks for fixing @kripken, and quickly too!
