### ISSUE TITLE
Static initializers in linked static libraries not being called

### ISSUE THREAD

**Issue by stevenlovegrove** [emscripten-core/emscripten#12926]
Static initializers seem to only be getting invoked when included in source files built into the main executable directly. Initializers linked in via static libraries are not called and are behaving a lot like lazily loaded dynamic libraries. I say this because you can cause initialization by explicitly referencing other symbols in the static lib. 

Here is a minimal compiling example with cmake options to switch between the three cases (without static lib, with static lib, and with static lib with symbol reference).

[CMakeLists.txt](https://github.com/emscripten-core/emscripten/files/5618732/CMakeLists.txt)
[main.cpp.txt](https://github.com/emscripten-core/emscripten/files/5618733/main.cpp.txt)
[lib.cpp.txt](https://github.com/emscripten-core/emscripten/files/5618734/lib.cpp.txt)

Here are the interesting cases:
```
cmake -DUSE_STATIC_LIB=False -DFORCE_LOAD_WITH_FUNC_CALL=False .. && make -j && python3 -m http.server 8080
cmake -DUSE_STATIC_LIB=True -DFORCE_LOAD_WITH_FUNC_CALL=False .. && make -j && python3 -m http.server 8080
cmake -DUSE_STATIC_LIB=True -DFORCE_LOAD_WITH_FUNC_CALL=True .. && make -j && python3 -m http.server 8080
```
Case 1 works and will print `This doesn't always get called`. 2 doesn't. 3 shows how to force initialization by referencing a symbol in the static lib.

Not sure if this is a bug in static library loading or in symbol stripping or just documentation. The behavior differs from native compilation in any case.

I can't find any reference to this behavior in the docs (like https://github.com/emscripten-core/emscripten/wiki/Linking). I've tried all kinds of flags to try to change the behavior but I've been unsuccessful. 

https://github.com/emscripten-core/emscripten/issues/12005 is possibly related.

Thanks!

**Comment by sbc100** [comment]
If I understand you correctly this is the expected behaviour and does indeed match the native gcc and clang behaviour.

If you have a static constructor in an object file that lives in a `.a` archive that constructor will only run if the object in which is lives is pulled in to the link from some reason.

This is the way `.a` archive work.   Entire object files get excluded unless they are explicitly needed. 

One solution is to add `-Wl,--whole-archive` and `-Wl,--no-whole-archive` around your archive if you want this alternative behavour.  This means taht linker will always include each of the object in the archive (as if they were not in fact part of an archive but listed individually).

**Comment by sbc100** [comment]
https://stackoverflow.com/questions/1804606/static-initialization-and-destruction-of-a-static-librarys-globals-not-happenin

**Comment by stevenlovegrove** [comment]
Thank you for the quick response - this is really useful information! Just as your linked SO answer, I also assumed an archive was just a convenient store of object files. I didn't realize it behaved differently.

I'm embarrassed I didn't test this simple version with my native compiler first, sorry about that. I have a more complicated example that is behaving differently between enscripten and native gcc & clang and I thought this was the cause. Now the question for myself is the reverse - in the more complicated scenario, how are they getting called in the native compilation :). There I don't have the --whole-archive flag either and am not referencing any symbols, so there must be some other means that this can happen.

Thanks again!

**Comment by sbc100** [comment]
For that native example you might want to try using the `-Wl,-Map=map.txt` command line flag along with `-Wl,--trace-symbol=foo` to figure out why a given object is getting pulled into the link (and hence your ctors are running).
