### ISSUE TITLE
Assertion failed: Missing signature argument to addFunction: function _abort()

### ISSUE THREAD

**Issue by Faless** [emscripten-core/emscripten#12942]
I've been experimenting with dynamic linking support in Godot Engine for the WASM export, and found this issue with the `abort` function.

As reported here https://github.com/emscripten-core/emscripten/blob/496967e00735c1523299e116dc692572d3d6d082/src/library.js#L694-L697

There are 2 different `abort` function, one coming from runtime, one implemented as library.
I noticed that the signature (`abort__sig`) was missing, added it, and this fixed the issue (I would open a PR to add it, but given the comment above, I'm not sure it's the desired course of action).

The problem was that I couldn't reproduce the issue with a minimal project, since calling `abort()` worked just fine.
After spending few hours trying reproduce it, and trace from where it was coming from in the Godot build, I found out that referencing `abort` directly does not cause an error, only referencing it indirectly results in the library function being used spitting the error because the function is missing the signature (required in 2.0.9+).

Attached is a reproduction project, but here is a breakdown:
```cpp
// side.cpp
#include <stdlib.h>
#include <stdio.h>
#include <emscripten/emscripten.h>

static void (*no_memory)(void) = abort; // will use library function, spitting missing signature

extern EMSCRIPTEN_KEEPALIVE void side() {
        printf("Side");
        no_memory();
}
```

```cpp
// side.cpp
#include <stdlib.h>
#include <stdio.h>
#include <emscripten/emscripten.h>

extern EMSCRIPTEN_KEEPALIVE void side() {
        printf("Side");
        abort(); // will use the runtime function, not complaining.
}
```

The reproduction project: [abort.zip](https://github.com/emscripten-core/emscripten/files/5629061/abort.zip)

Compiled with (or use `build.sh`):
```bash
EMCC_FORCE_STDLIBS=libc emcc -s MAIN_MODULE=1 main.cpp -o main.html -s EXPORT_ALL=1 --pre-js pre.js
emcc -s SIDE_MODULE=2 side.cpp -o side.wasm
```

**Comment by sbc100** [comment]
Yes, please submit a PR to add the signature to abort.

I guess we should had a test case where a side module imports just the addresses of all our core functions... or perhaps add an assertion if `__sig` is missing from any function in the core libraries?
