### ISSUE TITLE
TypeError: Cannot read property 'refcount' of undefined

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#12958]
I suddenly started to observe this error. 

What does it means? What should I do to fix this?

**Comment by sbc100** [comment]
Can you give us a bit more context?   What flags are you passing?   Can you see in devtools where undefined is coming from?    Does it happen in debug (-O0) builder?

**Comment by jeffRTC** [comment]
Honestly, I can't see where it's coming from but I am still looking

Flags

`--bind -std=c++1z -Oz  -s EXPORT_ALL=1  -s MODULARIZE=1 -s "EXPORT_NAME='MyTestModule'" -s DISABLE_EXCEPTION_CATCHING=0 -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s WASM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']" -s ALLOW_MEMORY_GROWTH=1`

**Comment by jeffRTC** [comment]
I am using this inside Chrome Extension,

Apparently, it logging `The frame was removed.` runtime error 172 times. 

https://source.chromium.org/search?q=%22The%20frame%20was%20removed.%22&sq=&ss=chromium%2Fchromium%2Fsrc


After that, refcount error appear,

```
VM34:9 Uncaught (in promise) TypeError: Cannot read property 'refcount' of undefined
    at __emval_decref (eval at methodCaller_emscripten$$val_$emscripten$$val$ (eval at new_ (background.js:9)), <anonymous>:9:1372308)
    at Ha (<anonymous>:wasm-function[1275]:0xa7861)
    at ret.<computed> (eval at methodCaller_emscripten$$val_$emscripten$$val$ (eval at new_ (background.js:9)), <anonymous>:9:1403217)
    at invoke_vi (eval at methodCaller_emscripten$$val_$emscripten$$val$ (eval at new_ (background.js:9)), <anonymous>:9:1433834)
    at <anonymous>:wasm-function[73]:0x1394
    at <anonymous>:wasm-function[1209]:0x96750
    at Ia (<anonymous>:wasm-function[1274]:0xa77b5)
    at ret.<computed> (eval at methodCaller_emscripten$$val_$emscripten$$val$ (eval at new_ (background.js:9)), <anonymous>:9:1403217)
    at invoke_vii (eval at methodCaller_emscripten$$val_$emscripten$$val$ (eval at new_ (background.js:9)), <anonymous>:9:1434151)
    at <anonymous>:wasm-function[1656]:0xdf574
```

**Comment by jeffRTC** [comment]
We can safety ignore `The frame was removed.`

It's not related to Emscriptten

**Comment by jeffRTC** [comment]
I traced the error back to here,

```
     Module["__embind_register_float"] = __embind_register_float;
        function new_(constructor, argumentList) {
            if (!(constructor instanceof Function)) {
                throw new TypeError("new_ called with constructor type " + typeof constructor + " which is not a function")
            }
            var dummy = createNamedFunction(constructor.name || "unknownFunctionName", function() {});
            dummy.prototype = constructor.prototype;
            var obj = new dummy;
            var r = constructor.apply(obj, argumentList);   /// This is the line that causes the error
            return r instanceof Object ? r : obj
        }
```

**Comment by jeffRTC** [comment]
Interesting, I put a hook but the hook doesn't log anything and that means the Chrome Devtools showing me false code line

**Comment by jeffRTC** [comment]
I have a while loop inside the cpp that sleep for 15 min using em_sleep function then do some operations so on

**Comment by jeffRTC** [comment]
@sbc100 

Do you have any idea what refcount actually refers to?

**Comment by sbc100** [comment]
Its almost certainly related to embind.  I would be its this line here: https://github.com/emscripten-core/emscripten/blob/5b642f2a9fcea0a53b342b97915440bbb7aa05f6/src/embind/emval.js#L99

**Comment by jeffRTC** [comment]
@sbc100 

I was able to get more clean stack trace. It looks like it hitting at deconstruction of `emscripten::val::~val()`

```
    at __emval_decref (background.js:2117)
    at dynCall_vi (<anonymous>:wasm-function[1927]:0xd62d3)
    at ret.<computed> (background.js:2573)
    at invoke_vi (background.js:4661)
    at emscripten::val::~val() (<anonymous>:wasm-function[87]:0x11856)
    at Animals::getPet() (<anonymous>:wasm-function[100]:0x2b196)
    at dynCall_vii (<anonymous>:wasm-function[1929]:0xd6437)
    at ret.<computed> (background.js:2573)
    at invoke_vii (background.js:4683)
    at __original_main (<anonymous>:wasm-function[66]:0x1dc9)
```

**Comment by sbc100** [comment]
I'm afraid I don't know enough about embind to help you out much ehre.  Are you able to get this error in devtools and see what is going ?

The only place I can that we call __emval_decref is https://github.com/emscripten-core/emscripten/blob/5b642f2a9fcea0a53b342b97915440bbb7aa05f6/src/embind/embind.js#L803.  So it looks like `fromWireType` is being called with an `undefined` handle.

**Comment by react-cad-dev** [comment]
For anyone arriving via google, I had the same error message, it was caused by an object with an `emscripten::val` member being destroyed off the main thread, where the `val` did not exist.

**Comment by carsonDB** [comment]
@react-cad-dev Thanks. Your hint inspired me. I want to explain more to anyone who has similar problems.

Here is an example, that represents my bug.
```
Class A {
    val* a;
    A(emscripten::val c) {
        a = &c;
        // do something
        // c will be deleted at the end of the constructor
    }
    getVal() {
        // A::a points to nothing.
    }
}
```
`c` is `val` type. It has connected to JavaScript object (or others), when the constructor call starts.
But be careful about the lifetime of  `c`. It actually will be destroyed at end of the call.
Then `A::a` pointer is meaningless. Even if corresponding JS object still exists.
So in order to avoid this bug. I use `std::move` to move `c` to `a` object, not just pointer.
```
Class A {
    val a;
    A(emscripten::val c) {
        a = std::move(c);
        // dont use c, use a instead.
        // do something
    }
    getVal() {
         // you can visit a
    }
}
```
