### ISSUE TITLE
[2.0.9] Error using custom html shell

### ISSUE THREAD

**Issue by Flix01** [emscripten-core/emscripten#12951]
Hi,
I've just updated emscripten to current latest (2.0.9), and now when I use a custom shell, I get this error:
```bash
parseTools.js preprocessor error in emscripten_load_save.shell:47: "      #status {"!

undefined:111
        throw e;
        ^
Unknown preprocessor directive on line 46: `      #status {`
(Use `node --trace-uncaught ...` to show where the exception was thrown)
em++: error: '/,,,/emsdk/node/12.18.1_64bit/bin/node /,,,/emsdk/upstream/emscripten/tools/preprocessor.js /tmp/emscripten_temp_mcad8v6q/settings.js emscripten_load_save.shell' failed (1)
parseTools.js preprocessor error in emscripten_load_save.shell:47: "      #status {"!
```
I don't know much about html, but probably some blocks like this:
```js
     #status {
        display: inline-block;
        vertical-align: top;
        margin-top: 30px;
        margin-left: 20px;
        font-weight: bold;
        color: rgb(120, 120, 120);
      }
```
(that are probably commented out), in version 2.0.9 are detected as errors.

**Comment by Flix01** [comment]
... or maybe it's just me inventing a fake comment syntax that passed undetected in previous emscripten versions...

**Comment by Flix01** [comment]
...in any case I can just remove the code blocks and close this issue.

**Comment by Flix01** [comment]
Nope, in inline CSS lines starting with a hash (#), or a dot are perfectly legal and are NOT comments!

So it must be an emscripten issue.

**Comment by sbc100** [comment]
Lines that start with `#` are treated by out js preprocessor as directives.  This mean any code in library JS or `--pre-js` or `--post-js` or I guess `--shell-file` will not work with lines that start with `#` but are not directives.

I did make this more sensitive recently in #12702 by allowing directives to start at any position in a line (before they had to start in column 0).  

Presumably your `emscripten_load_save.shell` file is JS that happens to embed CSS inside of strings that right?

**Comment by Flix01** [comment]
> Presumably your ```emscripten_load_save.shell``` file is JS that happens to embed CSS inside of strings that right?

Yes, and '#'s are not in column 0.

**Comment by sbc100** [comment]
It does look like we have a specific test for this... so we need to figure out why the code we have for that isn't working for you.

**Comment by sbc100** [comment]
https://github.com/emscripten-core/emscripten/blob/00d2c8da1a36325a158f4dea34cabfba05dcd518/tests/test_other.py#L7655

**Comment by sbc100** [comment]
Can you post your full shell file by any chance?

**Comment by Flix01** [comment]
> Can you post your full shell file by any chance?

Sure: it's here: https://github.com/Flix01/imgui/blob/imgui_with_addons/examples/addons_examples/html/emscripten_load_save.shell

**Comment by sbc100** [comment]
Ah, I figured it out.   It looks like that preprocessor only handles <style> tags if the input file has the `.html` (or `.htm` extension:

See: https://github.com/emscripten-core/emscripten/blob/a44cb419138706bb2ea0c75dcf70bf0c3954758b/src/parseTools.js#L37

**Comment by sbc100** [comment]
Easiest fix is to rename your your file to `emscripten_load_save.html`

**Comment by Flix01** [comment]
OK. Thank you for your support!
