### ISSUE TITLE
Recompile without source?

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#12962]
My co-worker suddenly left for a vacation and I don't have source code with me, but there is WASM file and EM Generated JS file. 

I would like to recompile the EM JS file by adding more options or deleting options.

**Comment by jeffRTC** [comment]
I was able to get source file. This no longer relevant

**Comment by sbc100** [comment]
I recently added the `--post-link` argument that should be able to do exactly this!
