### ISSUE TITLE
ALLOW_MEMORY_GROWTH doesn't work with pthread under Node

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#12972]
This program:
```
#include <cstdlib>
int main() {
  malloc(30 * 1000 * 1000);
}
```

Completes successfully when compiled (Emscripten 2.0.6) with these flags:
```
-pthread -s INITIAL_MEMORY=67108864 -s EXIT_RUNTIME=1
```

But with the following flags the memory allocation fails when running under Node:
```
-pthread -s ALLOW_MEMORY_GROWTH=1 -s EXIT_RUNTIME=1
```
The failure is:
```
emscripten_realloc_buffer: Attempted to grow heap from 16777216 bytes to 35258368 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory.
Failed to grow the heap from 16777216 bytes to 35258368 bytes, not enough memory!
```

I know it's not a recommended configuration due to performance issues (and the compiler warns about that), but it seems that it's not just slow but is rather silently ignored?

**Comment by kripken** [comment]
Which version of node is this? It sounds like a possible node bug (unless your machine actually didn't have the memory to grow the array to 32MB, but I'm guessing it's not that :wink: ).

**Comment by emaxx-google** [comment]
I'm using Node 12.18.1 (that's the one that is coming with the Emscripten SDK currently).

I definitely have sufficient memory in the OS, since, as mentioned in comment 0, the program works when (a) the memory is preallocated via INITIAL_MEMORY, or (b) when the program is executed in Chrome.

**Comment by khuttun** [comment]
I saw the same issue with Node 12.18.3, but with 15.8.0 the issue seems to be resolved.
