### ISSUE TITLE
getaddrinfo() doesn't set sin_zero in emulation

### ISSUE THREAD

**Issue by TrueBrain** [emscripten-core/emscripten#12998]
A funny bug that took a bit of time to track down:

`sockaddr_in` is described in POSIX as:

```
sa_family_t     sin_family   AF_INET. 
in_port_t       sin_port     Port number. 
struct in_addr  sin_addr     IP address. 
```
(https://pubs.opengroup.org/onlinepubs/009695399/basedefs/netinet/in.h.html)

What it doesn't describe, it what happens with the last 8 bytes. In most OSes (Linux, BSD, Windows, ..) this is defined as `sin_zero`, and is zero'd.

For most functions dealing with `sockaddr_in`, the application is in charge of memory management, and as such, can zero the structure before it is being filled. Sadly, there is one function (that I know of) where the memory management is done by the library: `getaddrinfo`. And emscripten does not zero the last 8 bytes of `sockaddr_in`, resulting in funny bugs :)

In many applications, it is common to compare `sockaddr_in` with each other, to see if they are in fact the same address. It is quick, it is simple. The length used for this, is `sizeof(sockaddr_in)`. So .. I think you can see the problem now :D

With emscripten, comparing addresses does not work, well, it randomly works, heavily depending on what memory got `malloc`'d. It is very unpredictable.

So although not defined by POSIX, but implemented by any OS I know of, would it be wise for emscripten to also zero these bytes? (honest question, as it is not by any specs; but is by convention).

The malloc is done here:
https://github.com/emscripten-core/emscripten/blob/9e0303729419d2beac5143dd68c3e3a361fd574e/src/library.js#L2458
And no zero'ing is done. Neither in `_write_sockaddr`.

This is btw an old problem .. searching online shows the frustration people have with the POSIX specs:
https://silviocesare.wordpress.com/2007/10/22/setting-sin_zero-to-0-in-struct-sockaddr_in/
http://lists.kernelnewbies.org/pipermail/kernelnewbies/2011-February/000966.html

For good measure, here is libc doing the zero'ing:
https://code.woboq.org/userspace/glibc/sysdeps/posix/getaddrinfo.c.html#1114

Tnx for considering!

**Comment by kripken** [comment]
Interesting find... yes, it sounds like a good idea to me to fix this. PR would be welcome!
