### ISSUE TITLE
Ability to import memory

### ISSUE THREAD

**Issue by SoniEx2** [emscripten-core/emscripten#13016]
When using wasm on a server for sandboxing (see MightyPirates/OpenComputers#3379 ), it would be nice to be able to import memory. However emscripten doesn't seem to do importing memory.

Would it be possible to have emscripten import memory instead of exporting it? And somehow have that work with anything from 192kB of memory up to 2MB of memory...

**Comment by sbc100** [comment]
We have a setting called `IMPORTED_MEMORY` that is designed to allow for this.

**Comment by SoniEx2** [comment]
Can you set stack at runtime with that?

**Comment by sbc100** [comment]
You mean the stack location?     You can set the stack pointer value using stackRestore, but you can't move the location of the stack no.   The memory layout of the program is fixed at link time.     Do you need to be able to dynamically set the memory layout?

**Comment by SoniEx2** [comment]
Yeah, different memory sizes (192k, 256k, 384k, 2M, etc) would benefit from having different memory layouts, so being able to dynamically set the memory layout would be useful. (we looked into using SIDE_MODULE but providing the whole stdlib seems a bit overkill for dynamically adjusting the memory layout...)
