### ISSUE TITLE
Prevent emscripten from renaming imports

### ISSUE THREAD

**Issue by jeremyherbert** [emscripten-core/emscripten#13024]
I am using the following code:

```
#include <stdint.h>

extern int64_t get_int();
extern void debug_log(int64_t i);

void get_and_add_one() {
	int64_t tmp = get_int();
	debug_log(tmp);
	debug_log(tmp+1);
}
```

and compiling with 
```
emcc test.c -O3 -s WASM=1 -o test.html -s 'EXPORTED_FUNCTIONS=["_get_and_add_one"]' -s 'EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"]' -s ERROR_ON_UNDEFINED_SYMBOLS=0
```

I would like to replace the `extern` functions with javascript functions in the browser (my eventual goal is to implement a C API [like this](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript) but post-compilation, not pre-compilation). However, emscripten destroys the original names of the import like so:

```
...
  (import "a" "a" (func (;0;) (type 3))) ;; this should be "_debug_log"
  (import "a" "b" (func (;1;) (type 0))) ;; this should be "_get_int"
  (import "a" "c" (func (;2;) (type 0))) ;; this should be "_getTempRet0"
...
```

Is there some way to prevent emscripten from performing this mangling?

**Comment by sbc100** [comment]
First I recommend you remove `ERROR_ON_UNDEFINED_SYMBOLS`.

To implement you functions in JS you need to supply a JS library to emscripten with `--js-library=<file.js>`.   This will allow you to supply the undefined symbols yourself so you don't need `ERROR_ON_UNDEFINED_SYMBOLS=0` anymore.

See 
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript for more information on how to do this.

**Comment by jeremyherbert** [comment]
I have read that documentation, but unfortunately I can't use the library.js approach because I need to inject the dependencies at runtime (basically, the C API can be implemented with Web Serial or Web USB depending on which hardware is being used).

I ended up getting this working in case anyone else finds this via google.

C code (in `test.c`):
```
#include <stdint.h>

extern int64_t get_int();
extern void debug_log(int64_t i);

void get_and_add_one() {
	int64_t tmp = get_int();
	debug_log(tmp);
	debug_log(tmp+1);
}
```

Compile with:
```
emcc test.c -O3 -s WASM=1 -o test.html -s 'EXPORTED_FUNCTIONS=["_get_and_add_one"]' -s 'EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"]' -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s STANDALONE_WASM=1 --no-entry
```

Override instantiation in the page to inject custom imports:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Simple template</title>
  </head>
  <body>
    <script>
      function downloadWasm(url) {
        return new Promise(function(resolve, reject) {
          var wasmXHR = new XMLHttpRequest();
          wasmXHR.open('GET', url, true);
          wasmXHR.responseType = 'arraybuffer';
          wasmXHR.onload = function() { resolve(wasmXHR.response); }
          wasmXHR.onerror = function() { reject('error '  + wasmXHR.status); }
          wasmXHR.send(null);
        });
      }

      var wasm = downloadWasm('test.wasm');

      var Module = {
        preRun: [],
        postRun: [],
      };

      Module.instantiateWasm = function(imports, successCallback) {
        console.log('instantiateWasm: instantiating asynchronously');
        wasm.then(function(wasmBinary) {
          console.log('wasm download finished, begin instantiating');

          imports["env"]["get_int"] = function() {return BigInt(5);}
          imports["env"]["debug_log"] = console.log;


          var wasmInstantiate = WebAssembly.instantiate(new Uint8Array(wasmBinary), imports).then(function(output) {
            console.log('wasm instantiation succeeded');
            Module.testWasmInstantiationSucceeded = 1;
            successCallback(output.instance);
          }).catch(function(e) {
            console.log('wasm instantiation failed! ' + e);
          });
        });
        return {}; // Compiling asynchronously, no exports.
      }

      var script = document.createElement('script');
      script.src = "test.js";
      document.body.appendChild(script);
    </script>
  </body>
</html>
```
```

**Comment by sbc100** [comment]
You can provide a library JS file that then calls out to any JS library you want.   It doesn't need to be available at compile time.

e.g.  mylibrary.js:

```
get_int: function() {
   call_any_js_library_function_on_the_page();
}
```

Then you can remove `ERROR_ON_UNDEFINED_SYMBOLS=0` which is a problematic option because it hides link error.

Also, is there some reason why you are running with `STANDALONE_WASM=1`... there are some good reasons to using that option but if you are running emscripten-generated JS on the web you probably don't want it.

**Comment by jeremyherbert** [comment]
Thanks for your insight, it is greatly appreciated. For some reason I had assumed one could not call out from the library.js file, but in hindsight that is a bit silly. Your solution is much better.

I was using the `STANDALONE_WASM=1` to maintain the names of the WASM imports, but I have since discovered that I need to use Asyncify so that won't work.
