### ISSUE TITLE
Getting NODERAWFS error on Web

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#13030]
This all happens after I migrated to CMake and had no issues with my good old bat script. 

So, Here is the Chrome showing to me,

`Uncaught Error: NODERAWFS is currently only supported on Node.js environment.
`
I swear there is no NODE_ENV flag set on my CMake neither the Verbose output display any sign of NODE_ENV

**Comment by jeffRTC** [comment]
It works after setting env to web.

**Comment by foreverlms** [comment]
> 

how do you set env to web?

**Comment by kripken** [comment]
@foreverlms 

`-sENVIRONMENT=web` will do that.
