### ISSUE TITLE
cannot build hello_world.c: error globalBase must be set

### ISSUE THREAD

**Issue by sakra** [emscripten-core/emscripten#13031]
I am trying to build the `hello_world` example but upon compilation with `emcc` I run into the errror "Fatal: globalBase must be set".

```
$ cat hello.c
#include <stdio.h>
int main(int argc, char ** argv) {
  printf("Hello, world!\n");
}
$ emcc hello.c -s WASM=0
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/Users/kratky/Library/Caches/emscripten/wasm/generated_struct_info.json" for subsequent builds)
Fatal: globalBase must be set
emcc: error: '/usr/local/opt/binaryen/bin/wasm-emscripten-finalize --detect-features --minimize-wasm-changes --dyncalls-i64 /var/folders/6t/zgnyk5yx2f31tfl0rdg802040000gn/T/tmppugnf7uz.wasm -o /var/folders/6t/zgnyk5yx2f31tfl0rdg802040000gn/T/tmppugnf7uz.wasm' failed (1)
FAIL: Compilation failed!: ['/usr/local/Cellar/emscripten/2.0.10/libexec/emcc', '-D_GNU_SOURCE', '-o', '/var/folders/6t/zgnyk5yx2f31tfl0rdg802040000gn/T/tmppugnf7uz.js', '/var/folders/6t/zgnyk5yx2f31tfl0rdg802040000gn/T/tmpahrrfg3x.c', '-O0', '-Werror', '-Wno-format', '-s', 'BOOTSTRAPPING_STRUCT_INFO=1', '-s', 'WARN_ON_UNDEFINED_SYMBOLS=0', '-s', 'STRICT=1', '-s', 'SINGLE_FILE=1', '-Wno-error=version-check', '-Wno-deprecated']

```

**Comment by sbc100** [comment]
This looks like the version llvm, emscripten and binaryen are not in sync with each other.     This normally results from folks trying to package emscripten with stable version of llvm or binaryen which is not really supported.

In the short term I would try using emsdk and contact the package maintainer about fixing the issue in the long term.

**Comment by sakra** [comment]
I have installed emscripten and binaryen with homebrew:

```
$ brew list --version llvm emscripten binaryen
binaryen 98
emscripten 2.0.10
llvm 11.0.0
```

**Comment by sbc100** [comment]
Yup thats that problem.   Please use emsdk for now.

**Comment by sakra** [comment]
Thanks.

**Comment by redblobgames** [comment]
Homebrew emscripten includes its own llvm and binaryen separate from the llvm and binaryen homebrew packages, but the default .emscripten config file doesn't point to them. I used these shell environment variables to solve the globalBase problem without switching to emsdk:

    export EM_LLVM_ROOT=/usr/local/opt/emscripten/libexec/llvm/bin
    export EM_BINARYEN_ROOT=/usr/local/opt/emscripten/libexec/binaryen

**Comment by sbc100** [comment]
Sounds like the homebrew package needs to be updated to include a correct config file maybe?  @chenrui333 do you include a pre-baked config file?
