### ISSUE TITLE
static linking with ports: searching for .bc libraries

### ISSUE THREAD

**Issue by nopid** [emscripten-core/emscripten#13044]
This comes from porting pillow into pyodide https://github.com/iodide-project/pyodide/pull/861, I am very novice with emscripten.

Static libraries appear both as `.a` and `.bc` files. As an example, some ports produce `.a` libraries, like [freetype](https://github.com/emscripten-core/emscripten/blob/de12acd3becf7b0b3aec02316456d44bc205ad2c/tools/ports/freetype.py). Some other ports produce `.bc` libraries, like [libjpeg](https://github.com/emscripten-core/emscripten/blob/de12acd3becf7b0b3aec02316456d44bc205ad2c/tools/ports/libjpeg.py).

For ports `-s USE_LIBJPEG=1 -s USE_FREETYPE=1` is expected to handle everything for you.

Outside ports, it looks like `.bc` libraries are not searched into `LIB_PREFIXES` because `STATICLIB_ENDINGS` only contains `.a`:
https://github.com/emscripten-core/emscripten/blob/de12acd3becf7b0b3aec02316456d44bc205ad2c/emcc.py#L3129-L3153

It would be great to be able to use:
```sh
$ emcc ... -L /my/path/to/libs -lpng -ljpeg -lmynicelib
```

rather than:
```sh
$ emcc ... /my/path/to/libs/libpng.bc /my/path/to/libs/libjpeg.bc /my/path/to/libs/libmynicelib.bc
```

**Comment by rth** [comment]
Or alternatively is the a way to generate `libjpeg.a`, `libpng.a` static libraries with emscripten ports instead of `.bc` files?

**Comment by sbc100** [comment]
Yes we are trying to move away from using the `.bc` extension.   I don't think any of our libraries use `.bc`.  What makes you think libjpeg does?   `.a` would be the first choice for libraries. 

If you really want to use an object file then `.o` is better extension than `.bc` since our object files are normal not bitcode these days.

**Comment by nopid** [comment]
Oh, my bad, I see that in now it always generate `.a` libraries.
https://github.com/emscripten-core/emscripten/blob/0f298808fcad3a9ef25966154b83e1cb3a520901/tools/system_libs.py#L1614-L1616

Used to be different and `pyodide` might have been using an older version, before e81d3bb2dc93f7014ca6496966fb12d479f5fc53

Sorry for the useless issue then.
