### ISSUE TITLE
--sysroot= flag works now

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#13041]
... and that's probably not a good thing.

I found this trying to reproduce a partner's build, which used CMake's `-DCMAKE_SYSROOT` flag, which results in `--sysroot=` being passed to the compiler. This was a bug, because I don't think emscripten has ever supported that flag "correctly". However, before #12863 I believe we just ignored it (or I guess more correctly it was overridden by our use of `-nostdsysteminc`), but now it actually has an effect. In this case the correct thing to do was not to use a sysroot (since the sysroot they were using was for x86_64), but since the above NFC-intended change actually is user-visible, we should probably do one or more of the following:
1) Actually make sure that `-sysroot` does what it should. Probably this is what we want eventually but based on my interpretatation of #12863 I don't think we are quite there yet. 
2) (assuming we don't do 1 yet) Explicitly ignore (or error out?) `-sysroot` and related flags that don't work.
3) Add to the release notes if and when we make any user-visible changes.

**Comment by sbc100** [comment]
I think we should explicitly ignore it with a warning for now.  

In the future we can explicitly allow it, once we have a true sysroot ourselves that we might want people to be able choose a different location for.

Presumably the intermediate for for them is to just stop passing -DCMAKE_SYSROOT?

**Comment by dschuff** [comment]
Yeah, ignoring it sounds good. And yes, stop passing DCMAKE_SYSROOT is correct anyway in this case.

**Comment by dschuff** [comment]
Does #13090 mean this works "correctly" now, or that we ignore user-supplied `--sysroot`? or is this still broken in the way OP describes?

**Comment by sbc100** [comment]
We currently honor `--sysroot` due to the fact that we add our implicit `--sysroot` on the command line before any user flags.

I think this is a reasonable outcome.     If a user passes `--sysroot` we should probably respect that and assume they have a sysroot they want to use.

**Comment by dschuff** [comment]
Yeah, that makes sense to me, thanks for confirming. So that's option 1 above, and that means this bug is fixed.
