### ISSUE TITLE
Pass C++ Function to JS without EMSCRIPTEN_BINDINGS

### ISSUE THREAD

**Issue by gerald-dotcom** [emscripten-core/emscripten#13057]
I don't know if this is possible to do with emscripten but I have a case where I have to invoke addEventListener dynamically and pass the C++ function to that, but I find the only way to do this is of course by using `EMSCRIPTEN_BINDINGS`

Is there are any alternatives to `EMSCRIPTEN_BINDINGS ` where one could pass function directly to JS maybe pointer?

How was this done before `EMSCRIPTEN_BINDINGS `released?

**Comment by gerald-dotcom** [comment]
Looking at this https://stackoverflow.com/questions/29319208/call-c-function-pointer-from-javascript

There is a way using Module.Runtime.dynCall

But it doesn't look so elegant to me......

**Comment by sbc100** [comment]
In theory you should just be able to do `addEventListener(Module['myFunction'])`?   

The real problem is that C/C++ functions can't ever take JS objects as parameters, so really need some kind of intermediate function to handle the conversion to WebAssembly types.

`addEventListener(function() { args_for_c_func = convertargs(); return Module['myFunction'](args_for_c_func); }`

If you don't want to handle converting the arguments yourself and embind or ccall are the only ways that I know that can help you do that.

**Comment by gerald-dotcom** [comment]
@sbc100 

In my case, the function is a void type and doesn't takes any args at all.

Worth noting that I build with `EXPORT_ALL=1`

**Comment by gerald-dotcom** [comment]
I'm trying to do this directly from em_val without using any JS at all. I haven't compiled below code, because I don't know whether it would be the correct way to do it. 

```
    emscripten::val::global("whatever")["dummy"]
    .call<void>
    ("addListener", std::function(router));
```

**Comment by sbc100** [comment]
Oh I see, if you you were in JS you could just use `Module['myFunction']`, right?   I'm not sure how to do what you want using  only embind but I think dynCall is the right direction... there is a function called `getDynCaller` in the library that will create a JS function based on the wasm function pointer (a table entry).  It works with raw function pointers (table indexes).

**Comment by gerald-dotcom** [comment]
@sbc100 

I've made an attempt to do following,

```
   emscripten::val getFunctionPTR = emscripten::val::module_property("getDynCaller");
   emscripten::val functionPTR = getFunctionPTR(std::function(notify))();

   emscripten::val::global()
   .call<void>("addEventListener", std::string("Hello"), functionPTR);
```

This compiles, but at runtime, it outputs that parameter has unknown type.

I found an interesting thread on a previous attempt to do what I wanted. In there, Chad Austin mentioned that this is not possible to do due to name mangling and unclear life semantics BUT it's possible do something where we can generate JS function objects associated with integer handles and then C++ could map each integer handle back to the appropriate std::function.

I think this will need modifications to em-val. Maybe @RReverser can do that.

https://emscripten-discuss.narkive.com/5KRoykMN/registering-callbacks-as-argument-with-embind

I happen to have messaged Chad months ago for an un-related issue and he replied me back that he could not find your IRC channel.

**Comment by gerald-dotcom** [comment]
I realized that I misunderstood concept of `std::function` at whole and now switched to `&function` syntax but at compile it complains,

`Implicitly binding raw pointers is illegal. Specify allow_raw_pointer<arg<?>>`

Passing allow_raw_pointer() as second arg doesn't seem change anything as it return same error.

**Comment by gerald-dotcom** [comment]
@sbc100 

The below code works to some extent. But the issue is the function get called earlier....... I don't know why...... It also doesn't catch any more events on JS side...

```
   emscripten::val getFunctionPTR = emscripten::val::module_property("getDynCaller");
   int rawPTR = (int)&notify;

   std::cout << rawPTR << "\n";

   emscripten::val functionPTR = getFunctionPTR(std::string("v"), rawPTR)();

   emscripten::val::global()
   .call<void>("addEventListener", std::string("Hello"), functionPTR);
```

**Comment by gerald-dotcom** [comment]
In JS side, I have checked `getDynCaller` for few moments. it seems if I put `()` the function execute instantly. 


I have changed

`emscripten::val functionPTR = getFunctionPTR(std::string("v"), rawPTR)();
`
to

`emscripten::val functionPTR = getFunctionPTR(std::string("v"), rawPTR);
`

Now, what happen is that when an event calls the function that dyn thing returned  it throw this error,

`Uncaught RuntimeError: abort(Assertion failed: undefined) at Error
`

**Comment by RReverser** [comment]
@gerald-dotcom Problem seems to be is that you're still trying to use the Embind interface, just without binding declarations. This is prone to run into issues like what you're seeing. I'd back @sbc100's suggestion to use JS syntax instead, e.g. via `EM_ASM`:

```c
EM_ASM({
  addEventListener('customEvent', Module['_my_function']);
});
```

This should be much easier to get to work, and will be a lot more efficient than having to jump via `emscripten::val` wrappers between C++ <-> JS several times.

Or, if you can't export function with a known name, use `getDynCaller` to create one from an address. This will still keep you in the JS land and make things a long easier.

**Comment by gerald-dotcom** [comment]
@RReverser 

If you check the title of the issue, it's clearly says that I don't want to use binding declarations at all even `EM_JS`. 

`emscripten::val` is elegant and has lot of benefits. Performance is not a concern in my case.

I tried to use `getDynCaller` but the target callback function get executed earlier.

It's happening because I can't invoke it without specifying methodName or handle.

```
                EM_VAL handle,
                const char* methodName,
```

There is no methodName or handle when you already get reference to the function from here,

`emscripten::val::module_property("getDynCaller")
`
By invoking `()`  in `getFunctionPTR(std::string("v"), rawPTR)();` it actually case to execute  the function that `getDynCaller` constructed for us.

Of course,  I attempted to do `Module.getDynCaller.call("v", 1)` instead  `Module.getDynCaller("v", 1)` in C++ side but it's not working.

It would be nice if you can perhaps add C++17 Callback support to `emscripten::val` as requested earlier here,

https://emscripten-discuss.narkive.com/5KRoykMN/registering-callbacks-as-argument-with-embind

**Comment by RReverser** [comment]
> If you check the title of the issue, it's clearly says that I don't want to use binding declarations at all even `EM_JS`.

`EM_JS` does _not_ require binding declarations. It's raw JS embed just like inline assembly in regular C/C++. It only works with Wasm literals, and passes them via standard JS<->Wasm API with no overhead or extra declarations.

`emscripten::val`, on the other hand, _does_ require a binding generator - Embind (that's why it requires a special `--bind` compilation option), and generates a bunch of JS and Wasm under the hood to bind various methods and store/propagate results of various types.

In particular, I hope this answers your original question:

> How was this done before `EMSCRIPTEN_BINDINGS` released?

The answer is it wasn't, because both `emscripten::val` and custom `EMSCRIPTEN_BINDINGS` were added together as part of Embind and use the same mechanism under the hood.

---

Between those, it sounds like you're limiting yourself by choosing an option that is both more verbose and less efficient for this usecase, and yes, probably there is a way to still do what you want, but TBH this sounds like a self-imposed restriction rather than an Emscripten issue you need help with.

**Comment by gerald-dotcom** [comment]
@RReverser

https://www.pnfsoftware.com/jeb/manual/webassembly/

Commercial software like **_remote exam monitoring_** has variety of requirements than _hobby fun projects_.

We've used EM_JS initially for a quick dirty prototype but it's dependencies made it next to impossible for production use.

It's not a self-imposed restriction rather than a business decision. Our custom LLVM based compiler can't encrypt EM_JS literals because of it's dependencies eg EM_JS walker, visitExport and many more. We don't like to maintain a separate fork of Emscripten.

`emscripten::val` is straightforward for our compiler.

I don't think there are any qualified user than you to answer my question since @jgravelle-google is gone.

**Comment by RReverser** [comment]
Uh... further information aside, why are you including screenshots of my tweets in a Github issue and how are they relevant to the conversation?

**Comment by gerald-dotcom** [comment]
> Uh... further information aside, why are you including screenshots of my tweets in a Github issue and how are they relevant to the conversation?

Just to point out who are we are dealing with daily basis. I included that so you can reason better around our problem.

**Comment by RReverser** [comment]
Sorry, I don't see how including my personal tweets about my side projects as some evidence of "who you are dealing with" is supposed to help or relevant to this issue. I'll better refrain from commenting further here.

**Comment by gerald-dotcom** [comment]
> Sorry, I don't see how including my personal tweets about my side projects as some evidence of "who you are dealing with" is supposed to help or relevant to this issue. I'll better refrain from commenting further here.

I've included a **_public_** tweet made by someone to provide more depth background on the problem we are dealing with so that person can perhaps understand us better than anyone else. 

By your logic,, 

I also don't see how it helps this problem when you say that what I want is a self-imposed restriction.

I also don't see how it helps this problem, when you're gate keeping by saying "yes", there's probably a way to still do what you want

if you behave this way, I'm willing to bet there are gonna be increasing demand for a commercial alternative with enterprise grade support. 

It's not only us who wants this. I've linked you an another issue earlier from an user who requested Lambda callback support to em_val but you are not being open minded so you fail to see why people wants this.

Inline scripts are certainly a bad practice and harder to maintain. After you added await() capability to em_val, we migrated a ton of code to em_val 

But that's what it's. I can't change mind of people. Some people are way too sensitive.

**Comment by aardappel** [comment]
FYI, here's another Wasm decompiler, freely available, and with more advanced features than the one you linked (e.g. memory layout analysis): https://v8.dev/blog/wasm-decompile

Point is, Wasm wasn't designed to be easy to protect against de-compilation, and no-one owes you a solution to that :)

**Comment by gerald-dotcom** [comment]
> FYI, here's another Wasm decompiler, freely available, and with more advanced features than the one you linked (e.g. memory layout analysis): https://v8.dev/blog/wasm-decompile
> 
> Point is, Wasm wasn't designed to be easy to protect against de-compilation, and no-one owes you a solution to that :)


I'm aware of this one too, but the point is we already have protection through our custom LLVM compiler that turns code into something crazy thus increasing the barrier of reversing up-to 3-4 years.  

We have issues with EM_JS due to it's dependencies, but there are no issues with EM_VAL

I didn't ask a solution for this. If  you already have read my question, it seeks how to pass C++ function to JS without emscripten_bindings.  There are no where mentions about that I need solution for anti-reversing. 

I had to tell about this because the other guy asked so.

**Comment by RReverser** [comment]
> I didn't ask a solution for this. If you already have read my question, it seeks how to pass C++ function to JS without emscripten_bindings. 

You asked 

> Is there are any alternatives to EMSCRIPTEN_BINDINGS where one could pass function directly to JS maybe pointer?

and you were provided with an alternative solution that you didn't like.

You also asked

> How was this done before EMSCRIPTEN_BINDINGS released?

and this was also answered above (see the answer with "it wasn't").

You tagged me, presumably because

> I don't think there are any qualified user than you to answer my question since @jgravelle-google is gone.

and

> After you added await() capability to em_val, we migrated a ton of code to em_val

and I'm glad the `await()` capability helped you, as well as I was happy to answer your questions to my best knowledge, but then you started getting antagonizing and calling me out personally for... presumably, not helping you enough? 😕

With all due respect, this is an open-source project. I'm glad the PR I've made helped you already, and you were provided a suggested solution that would work best with Emscripten, but if you have a custom compiler with custom requirements, you're free to make the required changes either in the compiler or make your own PR to Emscripten too.

You can't tag someone on Github for help and, after it's been already provided, expect/demand them to work for free on customizations that would help your commercial software. That's not how open-source works.

**Comment by gerald-dotcom** [comment]
@RReverser 

Quoting @aardappel,

> Point is, Wasm wasn't designed to be easy to protect against de-compilation, and no-one owes you a solution to that :)

I didn't ask a solution for protection against de-compilation. Okay? 

> if you have a custom compiler with custom requirements, you're free to make the required changes either in the compiler or make your own PR to Emscripten too.

No need for either PR or change to anything cause you have already mentioned this,

**_yes, probably there is a way to still do what you want,_**
`
> `You can't tag someone on Github for help and, after it's been already provided, expect/demand them to work for free on customizations that would help your commercial software. That's not how open-source works.

@sbc100 himself admitted that he lacks expertise on EM VAL and I tagged you if you have any ideas for this particular issue.

In which instance, did I act like Stalin and demand you to work free for me?

To best my knowledge, I didn't. 

I thought that this project is open source and being funded by Google and I opened an issue on Github not knowing I have to pay for Emscripten authors for asking a question.

**Comment by RReverser** [comment]
> When an open source project have texts like HamishW-Replace with description. made me wonder if this really open source.

Yes, it's open source in the sense that everyone is free to contribute.

> I thought that this project is open source and being funded by Google and I opened an issue on Github not knowing I have to pay for Emscripten authors for asking a question.

I'm sorry, but as I pointed out, your questions from the original description have been already answered. Given that we're now onto Stalin references and whatnot, this thread really seems to be getting counter-productive 😅

If you have improvement ideas to EM_VAL, which you seem to have - whether to improve the documentation, or to add new conversion methods to EM_VAL, PRs to improve those are most welcome, but the original issue itself seems to be resolved:

> No need for either PR or change to anything cause you have already mentioned this

In general, if you have questions about Emscripten and WebAssembly, rather than issue reports, it might be better to ask them on Stackoverflow or other resources you've linked yourself, where more people might be able to help.

**Comment by gerald-dotcom** [comment]
@RReverser Original issue isn't solved neither answered. You made a false statement that I asked you to work free and I didn't. 

Thought that you know Stalin very well considering you are from an ex-Soviet country. 

You're happen to have solved this issue by _throwing me under the bus_ by claiming what I ask is more verbose and less efficient.

Why on earth @jgravelle-google invented `emscripten::val` in first place then if em_js that great?

**Comment by gerald-dotcom** [comment]
Fact is this is something other people wants too not just me. I've linked two previous attempts made by other people. 

EMSCRIPTEN_BINDINGS it self will not work for larger apps.

It itself has it own code refactoring curve when it comes to complex objects and methods.

The alternative I propose would be far easier to use and of course it's **efficient**.

**Comment by gerald-dotcom** [comment]
I found where the bug lives in.

`assert(args.length === sig.substring(1).replace(/j/g, '--').length);
`
This assert fail because for some reason getDynCaller's  arguments take the event object it self as a valid arg.
 
```
function getDynCaller(sig, ptr) {
      var argCache = [];
      return function() {
        argCache.length = arguments.length;
        for (var i = 0; i < arguments.length; i++) {
          argCache[i] = arguments[i];
        }
        return dynCall(sig, ptr, argCache);
      };
 }
```

You can try below JS code to reproduce the issue,

```
var evt = new CustomEvent("Hello");
window.dispatchEvent(evt);
```

**Comment by gerald-dotcom** [comment]
![exhabit-a](https://user-images.githubusercontent.com/60860426/102694622-e5961080-41e7-11eb-830d-3dc7d02e97c8.png)
![exhabit-b](https://user-images.githubusercontent.com/60860426/102694623-e62ea700-41e7-11eb-889d-a5c45578c386.png)
![exhabit-c](https://user-images.githubusercontent.com/60860426/102694624-e62ea700-41e7-11eb-9740-749064090755.png)
![exhabit-d](https://user-images.githubusercontent.com/60860426/102694625-e62ea700-41e7-11eb-8c9a-fd7782561d4d.png)
![exhabit-e](https://user-images.githubusercontent.com/60860426/102694626-e62ea700-41e7-11eb-9334-255d21a68332.png)

**Comment by RReverser** [comment]
If there are specific bugs you're running into, please report them separately with clear steps to reproduce, or feel free to make a PR.

Questions from the issue description - both about the alternative solutions, as well as the "how was it done before", have been repeatedly answered.

If there's a functionality you're missing (even if it's not just you who is missing it), please make a PR.

If you're interested in history of Embind, feel free to take a look at Git logs (for example, it would already help you to find out where EMSCRIPTEN_BINDINGS was added, or that @jgravelle-google, who you tagged couple of times, wasn't the one to create `emscripten::val`).

Any of those steps would help a lot more than spamming a thread with personal information, attacks or accusations.

**Comment by gerald-dotcom** [comment]
The following change has fixed the code  which adds this  `if(arguments.length && !(arguments[0] instanceof Event))` condition before calling

```
$getDynCaller: function(sig, ptr) {
#if !USE_LEGACY_DYNCALLS
    assert(sig.indexOf('j') >= 0, 'getDynCaller should only be called with i64 sigs')
#endif
    var argCache = [];
    return function() {
      
      if(arguments.length && !(arguments[0] instanceof Event)) {
        argCache.length = arguments.length;
        for (var i = 0; i < arguments.length; i++) {
          argCache[i] = arguments[i];
        }
      }

      return dynCall(sig, ptr, argCache);
    };
  },
#endif
```

Result

![Result](https://user-images.githubusercontent.com/60860426/102695262-ae296300-41eb-11eb-9de1-8463f3651cca.png)

**Comment by gerald-dotcom** [comment]
@RReverser  You're welcome to make PR on behalf of me because I don't write Python tests

**Comment by RReverser** [comment]
> You're welcome to make PR on behalf of me because I don't write Python tests

> You made a false statement that I asked you to work free and I didn't.

🤔

**Comment by gerald-dotcom** [comment]
> > You're welcome to make PR on behalf of me because I don't write Python tests
> 
> > You made a false statement that I asked you to work free and I didn't.
> 
> 🤔

@RReverser 

Welcome means you're or someone who knows Python are welcome to issue a PR. I never ever asked you to work for me.

**Comment by sbc100** [comment]
`getDynCaller` turns a WebAssembly function in the JS function.   Since a WebAssembly functions do not support JS objects are arguments the result will never be JS function which accepts JS objects (such as an event handler function which take a JS event object as arg0 as you discovered).    The only way to do this would be have some kind JS wrapper or shim to modify the argument list in some way such that the arguments are then suitable for a call into WebAssembly.   In your example, it looks like you chose to simply drop all the arguments, which is one possible approach, but whatever way you do this it seems like it necessitates JS code mediating in *some* way.   

There are several ways to add this JS mediation code, from modifying the existing JS library in emscripten, to adding a new JS library function that does this for you, to writing EM_JS, EM_ASM code.   But they all boil down to doing *something* in JS.    Modifying the existing `getDynCaller` function probably isn't the best solution here, since ignoring functions arguments is probably not desirable in most cases.

**Comment by gerald-dotcom** [comment]
@sbc100 

The change I made didn't completely drop args support. It just dropped `Event` type object as arg using the condition `instanceof Event`

```
template<typename T>
void addEventListener(T function, std::string eventName) {
    emscripten::val method = emscripten::val::module_property("getDynCaller")(std::string("v"), int(function));
    emscripten::val::global().call<void>("addEventListener", eventName, method);
}
```
I can invoke it like this,

`addEventListener(targetFunction, "Hello");`

FYI, There is an alternative to `EM_JS, EM_ASM` called `Module.addFunction` and it can be invoked directly within val.

**Comment by sbc100** [comment]
Right, sorry, that is what I meant: In the case the first argument is a JS event object you solution ignores *all* the arguments passed, which is how you avoid the issue of not being able to pass the event object.     My point was that real solution to this problem probably wouldn't discard the event object but somehow convert/translate/handle it (maybe in your case its fine to ignore it but probably not in the general case).

`addFunction` is kind of like the opposite of `getDynCaller`.  The former takes a JS function pointer and returns a wasm functions pointer (an integer).  The latter takes a wasm function pointer (an integer) and returns a JS function.

**Comment by gerald-dotcom** [comment]
@sbc100 

I think Emscripten should check whether the function takes any args at all so this can be avoided for my case. For all other cases, I think conversation is needed.
