### ISSUE TITLE
Inconsistent 'initial' env:memory declaration size with WebKit

### ISSUE THREAD

**Issue by rth** [emscripten-core/emscripten#13053]
While loading packages in pyodide with Safari (and I can reproduce in other Webkit based browsers e.g. Midori ) users are getting the following error,
```
Error: Memory import env:memory provided an 'initial' that is smaller than the module's declared 'initial' import memory size
```
which is raised in WebKit source code [here](https://github.com/WebKit/WebKit/blob/77e39e49cc3552b30d870822554fa94539d579ed/Source/JavaScriptCore/wasm/js/JSWebAssemblyInstance.cpp#L260). As far as I understand Webkit does indeed check the memory declared by the module, the actual memory used and raises an error if the first one is smaller. 

Currently, we are using following emscripten settings ([main module](https://github.com/iodide-project/pyodide/blob/3a06f5dfcb9b536e9ece1f68f6963717acf82486/Makefile#L33), [side modules](https://github.com/iodide-project/pyodide/blob/3a06f5dfcb9b536e9ece1f68f6963717acf82486/pyodide_build/common.py#L10)) with in particular `ALLOW_MEMORY_GROWTH=1` and using emcc 1.38.42. Sorry that I don't really have an minimal example. Maybe this was fixed since, but I couldn't find any related issues on the issue tracker. Would you have any suggestions as to what could cause it?

cf https://github.com/iodide-project/pyodide/issues/721 for more information

**Comment by sbc100** [comment]
Do you know if this error is coming from the side module or the main module loading ?

Can we get some more details?  e.g. Can you figure out that values specified in the main and side modules from initial memory size, and the size being used at runtime when the memory is created?

**Comment by rth** [comment]
The issue is with side modules loading. The main module loads fine.

A minimal example would be to open the [pyodide REPL](https://pyodide-cdn2.iodide.io/dev/full/console.html) (which loads the main module) then enter `import regex` (in Safari or Midori) to load the side module.

>  e.g. Can you figure out that values specified in the main and side modules from initial memory size, and the size being used at runtime when the memory is created?

As far as I can tell Midori on Linux doesn't have Memory Profiler in "Developer tools" unlike Firefox or Chrome. I'll try to install Safari on Windows tomorrow to check. Is there another way to measure memory used by a module at runtime?
For the declared size of the main module, that would be, in [pyodide.asm.js](https://pyodide-cdn2.iodide.io/dev/full/pyodide.asm.js)
```py
        Module["asm"] = function(global, env, providedBuffer) {
          env["memory"] = wasmMemory;
          env["table"] = wasmTable =
              new WebAssembly.Table({"initial" : 16384, "element" : "anyfunc"});
          env["__memory_base"] = 1024;         
          env["__table_base"] = 0;
          var exports = createWasm(env);
```
if I understand correctly? I can't find anything relevant in the side module ([regex.js](https://pyodide-cdn2.iodide.io/dev/full/regex.js)) but maybe I'm not looking in the right place?

**Comment by sbc100** [comment]
Do you have a link to the side module itself?  The side module should be just a `.wasm` file right (unless you are building it with WASM=0)?  From the error message it looks like the side module is a wasm file.  

When you build a side module it will require a minimal memory size.     You can see this by using `wasm-objdump` on the side module.   When creating your main module you need to specific a memory size the is big enough for both main and the size module.   It sounds like your main module just need to be built with a bigger memory size.  Have you tried that?

**Comment by rth** [comment]
Thanks for your feedback @sbc100 !

>  It sounds like your main module just need to be built with a bigger memory size. Have you tried that?

Right, that sounds like the root cause indeed, I have not tried that yet. But we currently have an initial memory of 8MB, and one optional side module that needs >200MB. So I we increase the initial memory in the main module too much, that would be problematic. But we can probably increase it a bit at least to have most common packages/side modules working. 

I'll investigate more beginning of January.

**Comment by rth** [comment]
Updating from emscripten 1.38.42 to 2.0.15 (latest) and increasing `TOTAL_MEMORY` from 10MB to 20MB (with `ALLOW_MEMORY_GROWTH=1`) appears to have resolved this issue. At least for Safari v13+. So I'm going to close it.

Thanks for the suggestions @sbc100 !
