### ISSUE TITLE
UInt8Array.buffer full of 0s

### ISSUE THREAD

**Issue by fraguada** [emscripten-core/emscripten#13065]
Hello! We are successfully using emscripten to create a js library from cpp code. I've recently found a strange occurence and am wondering if there is a way to solve it in our binding code. I've logged the issue in the repository where we have our bindings: https://github.com/mcneel/rhino3dm/issues/338

We have a [method ](https://github.com/mcneel/rhino3dm/blob/master/src/bindings/bnd_extensions.cpp#L1120-L1142) that returns a valid UInt8Array, but the buffer property is full of 0s. Here is the binding code:

```cpp
// cpp binding code
emscripten::val BND_ONXModel::ToByteArray2(const BND_File3dmWriteOptions* options) const
{
  BND_File3dmWriteOptions defaults;
  if (nullptr == options)
    options = &defaults;

  ON_Write3dmBufferArchive archive(0, 0, options->VersionForWriting(), ON::Version());
  archive.SetShouldSerializeUserDataDefault(options->SaveUserData());

  m_model->Write(archive, options->VersionForWriting());
  const unsigned char* buffer = (const unsigned char*)archive.Buffer();
  size_t length = archive.SizeOfArchive();

  emscripten::val Uint8Array = emscripten::val::global("Uint8Array");
  emscripten::val rc = Uint8Array.new_(emscripten::val::module_property("HEAPU8")["buffer"], size_t(buffer), length);
  for (size_t i = 0; i < length; i++)
  {
    rc.set(i, buffer[i]);
  }
  //  rc.call<void>("set", sourceTypedArray);
  //  std::string rc(reinterpret_cast<char const*>(buffer), length);
  return rc;
}
```

If called from javascript, we get a valid UInt8Array, but the buffer is full of 0s:

![image](https://user-images.githubusercontent.com/1014562/102493723-e148e680-4073-11eb-96ee-194770f61e60.png)

If I recreate the UInt8Array in javascript, I get the correct buffer:

```javascript
// javascript
let nCrv = rhino.NurbsCurve.create( false, 3, crvPoints)
let doc = new rhino.File3dm()
doc.objects().addCurve(nCrv, null)
let ba = doc.toByteArray(); //ba.buffer full of 0s
let newArr = new Uint8Array(ba); newArr.buffer contains data
```
![image](https://user-images.githubusercontent.com/1014562/102493919-2ec55380-4074-11eb-8bf4-10d05ef5c7b5.png)

Given how we're creating and returning the UInt8Array in our bindings, is there a way to ensure the buffer property is correct?

For context, this would make the result from our method compatible with the Transferable API.

We were using emscripten 1.39.5, but have recently started testing 2.0.9 for future releases.

**Comment by kripken** [comment]
I think this is a slightly confusing side of the JS ArrayBuffer API. The UInt8Array is a view into a larger ArrayBuffer. Such views are created without copying the underlying ArrayBuffer.

Recreating the data, as you mention, "solves" this as it creates a new ArrayBuffer (which has the cost of copying).

**Comment by fraguada** [comment]
Thanks @kripken, that helps me understand that the ArrayBuffer isn't actually filled with 0s, I'm just not seeing the data represented in the resulting Uint8Array.

That being said, how can I properly create and pass the correctly sized ArrayBuffer and not one with this suspect bytelength of 16777216?

Instead of:
`Uint8Array.new_(emscripten::val::module_property("HEAPU8")["buffer"], size_t(buffer), length);`

I tried:
`emscripten::val(emscripten::typed_memory_view(length, buffer));`

and it had the exact same result as previously posted.

**Comment by fraguada** [comment]
Closing this for now, as it seems the workaround of copying the data by creating a `new Uint8Array()` is satisfactory for our use case. Thank you!
