### ISSUE TITLE
SEPARATE_DWARF_URL should default to the basename

### ISSUE THREAD

**Issue by bmeurer** [emscripten-core/emscripten#13079]
Currently when you pass `-gseparate-dwarf` the `SEPARATE_DWARF_URL` is the path to the object file with the extension replaced. While that is an option, it doesn't seem to be the best default. From what I think, the most likely scenario is that the `.wasm` and the `.wasm.debug.wasm` files will be co-located in the same folder in the end, and the DevTools front-end would be able to just fetch the sidecar file easily if the `SEPARATE_DWARF_URL` would default to just the basename of the sidecar file.

cc @sbc100 @azakai

**Comment by sbc100** [comment]
Seems reasonable.   This was recently changed in #12549 (due to #12526).   @RReverser does this change make sense to you?

**Comment by RReverser** [comment]
TBH I don't really understand the proposal / what's going to change here based on the description... Can you provide example paths for all files involved before and after the change?

**Comment by bmeurer** [comment]
Take the simple example of `emcc -o dist/file.wasm file.cc -gseparate-dwarf`: Currently the `file.wasm` will end up referring to `dist/file.wasm.debug.wasm` (literally). It'd be a lot better (as a default) to only put the basename there and have `file.wasm` refer to `file.wasm.debug.wasm` instead.

**Comment by RReverser** [comment]
Huh, I thought https://github.com/emscripten-core/emscripten/pull/12549 was supposed to fix precisely that, but I guess it fixed only relative paths for explicitly specified `SEPARATE_DWARF_URL`.

Yeah, sounds very reasonable to change it to relative path too.

**Comment by kripken** [comment]
I think this already works?
```bash
$ mkdir zzz
$ ./emcc -o zzz/file.wasm tests/hello_world.c -gseparate-dwarf
$ ls zzz
file.wasm  file.wasm.debug.wasm
```
And the path inside the wasm is relative.

Existing test:

https://github.com/emscripten-core/emscripten/blob/72d6ae302df110ca02244a1e89ddf6d59993cd55/tests/test_other.py#L7636-L7648

**Comment by RReverser** [comment]
Maybe @bmeurer was testing on an older Emscripten version before those fixes?

**Comment by bmeurer** [comment]
Indeed. I just checked with 2.0.12 and it does the right thing. Thanks!
