### ISSUE TITLE
Error is WASM file load when using modularized output in webpack

### ISSUE THREAD

**Issue by creativefctr** [emscripten-core/emscripten#13074]
Hi,
I am trying to import the JS file generalized by Emscripten's MODULARIZE=1 flag in a Create React App which is obviously using Web Pack.

```
function loadLib(){
     // output.js is the js file generated by the compiler
     const AssemblyTest = require("./lib/output.js");
     await AssemblyTest();
}
```

When I try to load it, I see the data file being loaded but in the network tab of inspect, no request goes for the wasm file and then I get this error:

`Unhandled Rejection (RuntimeError): abort(sync fetching of the wasm failed: you can preload it to Module['wasmBinary'] manually, or emcc.py will do that for you when generating HTML (but not JS)). Build with -s ASSERTIONS=1 for more info.
`

* I don't know if this is relevant or not, but, web pack loads some chunks as soon as this function is called. 
* I am testing on localhost with the built in dev server on port 3000

**Comment by donalffons** [comment]
Hey there,

here is what I usually do when integrating Emscripten with CRA:

1. I use [react-app-rewired](https://www.npmjs.com/package/react-app-rewired), so that I can adjust the build configuration without ejecting. My `config-overrides.js` usually looks something like this:
```javascript
const path = require('path');

module.exports = function override(config, env) {
  const oneOfRule = config.module.rules.find(k => k.oneOf !== undefined);
  oneOfRule.oneOf = [
    // load wasm-files with a custom rule
    {
      test: /\.(wasm)$/,
      type: "javascript/auto",
      loader: "file-loader",
    },
    ...oneOfRule.oneOf,
  ];
  return config;
}
```
2. I build my Emscripten module using the following settings:
```bash
  -s ENVIRONMENT='web',
  -s EXPORT_ES6=1 # AFAIK, this enables MODULARIZE implicitly
  -s USE_ES6_IMPORT_META=0
  ```
3. When I instantiate the Emscripten module in my CRA, I pass a custom `locateFile` function in the [Module object](https://emscripten.org/docs/api_reference/module.html).
```javascript
import emscriptenProject from 'path/to/emscriptenProject.js';
import emscriptenProjectWasm from 'path/to/emscriptenProject.wasm'; // <= this will be loaded using "file-loader", i.e. it will be a hashed filename under which you can access the WASM file

// ...

emscriptenProject({
  locateFile: f => emscriptenProjectWasm
}).then(instance => {
  console.log("use it!");
});
```

**Comment by creativefctr** [comment]
Thanks Sebastian but this did not work for me and I got the same error message. I am not sure! can it be due to webpack or react version maybe?
And as for your EDIT2, I don't think that's the case because in such scenarios it should at lease appear in the console and for me nothing is happening.

**Comment by creativefctr** [comment]
OK, I found the issue.
This flag was the culprit. 
`-s WASM_ASYNC_COMPILATION=0 \
`
Thanks!

**Comment by amarav** [comment]
@creativefctr @donalffons I m facing the same issue with CRA ( Followed the above solution ) 

This is the command im using to generate WASM for my cpp solution  
emcc -I include -g1 -s ASSERTIONS=1 -s WASM_ASYNC_COMPILATION=0 -s DISABLE_EXCEPTION_CATCHING=0 -s ENVIRONMENT="web" -s USE_ES6_IMPORT_META=0 -s USE_LIBPNG=1 -s USE_ZLIB=1 -s FETCH=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_ES6=1 -s MODULARIZE=1 -s 'EXPORT_NAME="myModule"' --bind --profiling -O3 -s WASM=1 -Wl,--whole-archive librendercore.a - -fdebug-compilation-dir=".." -s NO_EXIT_RUNTIME=1 -s EXPORTED_FUNCTIONS='["_myFunction","_main","_getBufferData"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall","cwrap","stringToUTF8","lengthBytesUTF8"]'  

In App.js,


import emscriptenProject from './rc_index.mjs';
import emscriptenProjectWasm from './index.wasm';
 emscriptenProject({
        locateFile: f => {
          if(f.endsWith(".wasm")) return emscriptenProjectWasm;
          return f;
        }
      }).then(instance => {
        console.log("use it!");
      });


Any ideas on this?
