### ISSUE TITLE
SDL2 causes error when used in MAIN_MODULE

### ISSUE THREAD

**Issue by nowakowsk** [emscripten-core/emscripten#13086]
# Description
`main.cpp`:
```cpp
int main() {}
```
Build command:
```
emcc main.cpp -s MAIN_MODULE=1 -s USE_SDL=2 -o main.html
```
Runtime error:
```
Assertion failed: Missing signature argument to addFunction: function _eglWaitGL(
  ) {
  return _eglWaitClient();
  }
```
Removing either `-s MAIN_MODULE=1` or `-s USE_SDL=2` fixes the problem.

Possibly related to the discussion in #4387?

# Build platform
**OS:** Windows 10 64-bit
**Environment:** MSYS
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.10
clang version 12.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 445289aa63e1b82b9eea6497fb2d0443813a9d4e)
Target: x86_64-pc-windows-msvc
Thread model: posix
```

**Comment by sbc100** [comment]
#13087 fixes this issue but I noticed that once fixed another issue is uncovered:  `Assertion failed: undefined symbol "emscripten_glReadBuffer"`  If you also experience this issue in practice please file a separate bug as these two seem unrelated.

**Comment by nowakowsk** [comment]
Yes, I get the same error (`undefined symbol 'emscripten_glReadBuffer'`) after your fix. I'll create a new bug report.
