### ISSUE TITLE
libunwind is out of sync with other libraries we pull from llvm

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#13094]
According to system/lib/libunwind/readme.txt we are on version 8.0.0 where as compiler-rt, libc++, and libc++abi are all on 10.0.0.

**Comment by sbc100** [comment]
I noticed this because if out libunwind code doesn't compile if clang's builtin unwind.h (which is tip of tree) gets picked up (while working on #13090).  I'm not sure updating to 10.0.0 would solve this issue but its worth a try.

**Comment by sbc100** [comment]
@aheejin any reason this might not be a simple process?

**Comment by aheejin** [comment]
I don't think so. We use libunwind mostly for its headers and our own stub (Unwind-wasm.cpp), so I think we can mostly just use the 10.0.0 release as is and I can't think of any possible issues at the moment.

**Comment by sbc100** [comment]
Do you fancy doing and upgrade?  (no pressure I can do it if you don't have  time).

**Comment by aheejin** [comment]
I'll try, but where are we getting that error? I thought the new EH tests are the only place we use it and the new EH tests were temporarily disabled in #12960.

**Comment by aheejin** [comment]
Done in #13098 (By the way I updated it to 11.0.0). But I'm not sure if that resolves your issues, because as I said, new wasm EH tests are currently disabled so libunwind doesn't seem to be currently being used anyway.
