### ISSUE TITLE
The new version of emscripten is not compatible with the old version

### ISSUE THREAD

**Issue by iamjustadd** [emscripten-core/emscripten#13104]
sir, I got such problem currently. While using different version emscripten to compile our project.
It works well in emsdk2.0.0, but show undefined symbols Error In 2.0.10.
The Error log is:
```
error: undefined symbol: _emval_as (referenced by top-level compiled C/C++ code)
warning: Link with -s LLD_REPORT_UNDEFINED to get more information on undefined symbols
warning: To disable errors for undefined symbols use -s ERROR_ON_UNDEFINED_SYMBOLS=0
warning: __emval_as may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _emval_run_destructors (referenced by top-level compiled C/C++ code)
warning: __emval_run_destructors may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _emval_take_value (referenced by top-level compiled C/C++ code)
warning: __emval_take_value may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/emsdk/node/12.18.1_64bit/bin/node /emsdk/upstream/emscripten/src/compiler.js /tmp/tmpaphk0ngd.txt' failed (1)
```
what happed to newer emscripten , how can i fix such problesm .
Thank you.

**Comment by sbc100** [comment]
Can you show the full command line that fails (the em++ link command you are using).

Are you passing `--bind` at link time?

**Comment by iamjustadd** [comment]
sorry,sir. I dont got the notifications before.
em++ -std=c++17 -w -DSK_RELEASE -DSK_SUPPORT_LEGACY_IMPLICIT_FILTERQUALITY -DSK_GL -Oz -g2 -s EXPORTED_FUNCTIONS="['_emval_as','_emval_run_destructors','_emval_take_value']"  -I/emsdk/upstream/emscripten/system/include/emscripten/ -I../../lanhu/master/fb/jsoncpp/include -I../../lanhu/master/fb/jsoncpp/include/json -I../../lanhu/master/fb/jsoncpp/src -I../../lanhu/master/fb -I../../lanhu/master/fb/fbs -I../../lanhu/master/fb/core/changeset -I../../lanhu/master/fb/core -I../../lanhu/master/fb/core/layer -I../../lanhu/master/fb/core/style -I../../lanhu/master/fb/include -I../../lanhu/master/include -I../../lanhu/master/fb -I../../lanhu/master/fb/data -I../../lanhu/master/fb/validation -I../../lanhu/master/fb/include -I../../lanhu/master/generalIndex -I../../ -I../../third_party/boost_1_74_0 -I../../lanhu/master/touchvg/include -I../../lanhu/master/touchvg/include/cmd -I../../lanhu/master/touchvg/include/cmdbase -I../../lanhu/master/touchvg/include/cmdbasic -I../../lanhu/master/touchvg/include/cmdmgr -I../../lanhu/master/touchvg/include/cmdobserver -I../../lanhu/master/touchvg/include/export -I../../lanhu/master/touchvg/include/geom -I../../lanhu/master/touchvg/include/graph -I../../lanhu/master/touchvg/include/gshape -I../../lanhu/master/touchvg/include/jsonstorage  -I../../lanhu/master/touchvg/include/canvas -I../../lanhu/master/touchvg/include/jsonstorage/rapidjson -I../../lanhu/master/touchvg/jsonstorage/rapidjson/internal -I../../lanhu/master/touchvg/include/record -I../../lanhu/master/touchvg/include/shape -I../../lanhu/master/touchvg/include/shapedoc -I../../lanhu/master/touchvg/include/storage -I../../lanhu/master/touchvg/include/test -I../../lanhu/master/touchvg/include/view -I../../lanhu/master/touchvg/include/editor  -I../.. -I../../modules/skparagraph/include -I../../modules/skparagraph/src -I../../modules/skparagraph/utils -I../../modules/skshaper/include -I../../third_party/harfbuzz/src -I../../third_party/externals/icu/source/i18n -I../../third_party/externals/icu/source/common -I../../third_party/icu -I../../third_party/externals/expat/lib -I../../third_party/skcms ../../lanhu/master/touchvg/src/cmdbase/mgcmddraw.cpp ../../lanhu/master/touchvg/src/cmdbase/mgdrawarc.cpp ../../lanhu/master/touchvg/src/cmdbase/mgdrawline.cpp ../../lanhu/master/touchvg/src/cmdbase/mgdrawrect.cpp ../../lanhu/master/touchvg/src/cmdmgr/cmdsubject.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgactions.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgcmdmgr_.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgcmdmgr2.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgcmdselect.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgcmdedit.cpp ../../lanhu/master/touchvg/src/cmdmgr/penpath.cpp ../../lanhu/master/touchvg/src/cmdmgr/lanhgraphi.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgsnapimpl.cpp -o ../../out/lib/tv_cmd.bc

Here is the whole command.I'm a new user of emscripten. the //-s EXPORTED_FUNCTIONS="['_emval_as','_emval_run_destructors','_emval_take_value']"// is what I write into the command to fix such problem. And It is not work. This command is working well in emsdk2.0.0, So I guess maybe it is not necessary for using a --bind parameter?

**Comment by iamjustadd** [comment]
by the way , what im doing is update both emsdk and skia(for our project).  The newer emsdk is not completely compitable with old Skia's Release as well.But it is working well for newest emsdk and newest skia(superisingly.....)

**Comment by sbc100** [comment]
If you want to use embind (emval functions are all part of embind) you need to link with `--bind`.   If might have been that in the past you could get away without it but it should have always been required.   If you add  this argument do you still have any issues?

Unless you actually want to run those function from outside your program I would not recommend adding `-s EXPORTED_FUNCTIONS="['_emval_as','_emval_run_destructors','_emval_take_value']"`

**Comment by iamjustadd** [comment]
Thank you So much ,sir.  It did worked!
