### ISSUE TITLE
JS exceptions halts WASM execution

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#13103]
Consider below code, it try to fetch from invalid URL causing browser to throw an error which prevents printing the `Hello World`

My assumption is that the JS exception fully halts the WASM execution 

```
int main() {
   val res = val::global("fetch")(std::string("o")).await();

   std::cout << "Hello World" << "\n";
}
```

**Comment by sbc100** [comment]
I'm not sure I understand the problem.  It seems that your assumption is correct and that "Hello World" Is not printed, right?   Do this is working as intended?  Maybe I'm misunderstanding..  how would you like this program to behave?

**Comment by jeffRTC** [comment]
@sbc100 

The Hello World should be printed but in this case it's not printed due to the JS exception. 

Fetch API throws an exception in event of invalid URL and it causes WASM execution to halt perhaps exit?

**Comment by sbc100** [comment]
But as you say "My assumption is that the JS exception fully halts the WASM execution".  You assumption is correct, you can't catch JS exceptions in C/C++.  You would need call out of JS have to a try/catch to do that (either using JS library code or EM_JS or EM_ASM).

**Comment by jeffRTC** [comment]
@sbc100 

You can catch JS exceptions in C++ by creating  val and setting false to it. 

In JS, it would looks like this,

```
let res = false;
res = await fetch("oo");

if(res == false) {
   console.log("An error")
}
```

Is there any emscripten  specific flag to disable this behavior?

**Comment by jeffRTC** [comment]
@sbc100 I seriously believe this as bug. WASM execution should continue whether there are exceptions or not.

**Comment by sbc100** [comment]
I'm not sure exactly what you are proposing here, but JS exceptions will cause the stack to unwind in all the way to up the stack until it finds a "catch" in a JavaScript frame.   There is simply no way (today) to directly catch or handle exceptions in wasm, you would need to write a JS wrapper around whatever you are trying to do if you want to catch an exception and continue wasm execution. 

I don't think it makes sense it general to simply ignore all JS exceptions and continue as if they didn't.  Is that what you are proposing?  It could be possible to design such as system where all calls to JS imports were wrapped in try/catch blocks, and all exceptions were ignored, but I don't think most programs would want that behaviour.

**Comment by jeffRTC** [comment]
@sbc100 

But why either em_val or asyncify blindly hook to JS exceptions and unwind the stack?

Can you point out to me where exactly this happen so I can disable for my case?

**Comment by sbc100** [comment]
The stack unwinding that happens on a JS exception is not something we add.   This is the builtin behaviour of WebAssembly when running in the JS embedding.   JS exceptions always unwind to the inner-more JS catch block (if there is one at all) with no possibility of WebAssembly catching them.  WebAssembly simply doesn't have this ability (today).

Any kind of catching would have be done either explicitly your JS code of in the JS code produced by emscripten and/or embind.   For example emscripten itself will insert JS try/catch block to emulate C++ exceptions and C setjmp/longjmp behaviour.     As far as I know embind/em_val does not insert try/catch blocks (but I could be wrong) which is why exceptions here appear to un-handle-able.

**Comment by jeffRTC** [comment]
@sbc100 
I think this happen because I call with return type `<emscripten::val>` but since there are nothing to convert in order to return, it crash.

I guess I should experiment with `void* `

**Comment by jeffRTC** [comment]
I guess I could modify this code to add catch handler and return a fake value xD

```
#if ASYNCIFY
  _emval_await__deps: ['$requireHandle', '_emval_register', '$Asyncify'],
  _emval_await: function(promise) {
    return Asyncify.handleAsync(function () {
      promise = requireHandle(promise);
      return promise.then(__emval_register);
    });
  },
#endif
```

**Comment by sbc100** [comment]
Yes, exactly, it sounds like in your case you want to return some kind of error object.

**Comment by jeffRTC** [comment]
@sbc100  It turns out Fetch API doesn't throw any errors. I was not checking the ok property of response object so that caused code to halt..
