### ISSUE TITLE
Runtime.getFuncWrapper undefined

### ISSUE THREAD

**Issue by Sciss** [emscripten-core/emscripten#13115]
Hi there. I am trying to compile [this example](https://gist.github.com/aknuds1/533f7b228aa46e9ee4c8)

```cpp
// file: pass_array.cpp
#include <cstdio>

extern "C" {
    extern void initialize(void (*callback)(float*));
}

void callback(float* output)
{
    for (int i = 0; i < 2; ++i)
    {
        output[i] = i+1;
    }
    printf("Callback was invoked\n");
}

int main()
{
    initialize(&callback);
    return 0;
}
```
```javascript
// file: pass_array_library.js
// "use strict";

var LibraryTst = {
  initialize: function (callback) {
    callback = /* Runtime. */ getFuncWrapper(callback, 'vi') // error here
    var numBytes = 2 * Float32Array.BYTES_PER_ELEMENT
    var ptr = Module._malloc(numBytes)

    try {
      callback(ptr)

      console.log('Callback filled buffer like so:')
      var i = 0
      for (i = 0; i < 2; ++i) {
        console.log(HEAPF32[(ptr/Float32Array.BYTES_PER_ELEMENT)+i])
      }
    }
    finally {
      Module._free(ptr)
    }
  },
}

mergeInto(LibraryManager.library, LibraryTst)
```
I compile using

    emcc -O1 -Wall -Werror --bind -o pass_array.html --js-library pass_array_library.js pass_array.cpp

But when I run the page, I only get

```
exception thrown: ReferenceError: Runtime is not defined,ReferenceError: Runtime is not defined
    at _initialize (http://0.0.0.0:8000/pass_array.js:2119:7)
```
I also tried something like `-s 'EXTRA_EXPORTED_RUNTIME_METHODS=["getFuncWrapper"]'`, `-s LINKABLE=1`, and as the FAQ says, replace `Runtime.getFuncWrapper` by just `getFuncWrapper`; but I don't seem to get this runtime function. I can see it is in `modules.js`, but I don't understand why it's not made available.

**Comment by sbc100** [comment]
First of all it looks like you are missing `mergeInto(LibraryManager.library, LibraryTst)` from the end of your library?   Was that just a copy and paste omission perhaps?

The best way to declare your dependency on the `getFuncWrapper` library function is to add this line to your library js file:

```
initialize__deps: ['$getFuncWrapper'],
``` 

Then when calling `getFuncWrapper` you don't need the `Runtime` prefix you can just call `getFuncWrapper` directly.

Another way to pull in that dependency if you were not using a library js file would to link with `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[$getFuncWrapper]`

**Comment by Sciss** [comment]
Yes, sorry the `mergeInto(LibraryManager.library, LibraryTst)` was a copy/paste mistake, it was there.

**Comment by Sciss** [comment]
Thank you again; this works, either way (in bash to be careful to escape `$`, so `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[\$getFuncWrapper]` on the command line).
