### ISSUE TITLE
Documentation: Porting » Connecting C++ and JavaScript » Embind: Classes unclear how to use example

### ISSUE THREAD

**Issue by Sciss** [emscripten-core/emscripten#13116]
I am referring to [this documentation page](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#classes). It is totally unclear for newcomers how to use these examples. The only one that is clear and works is the quick-example on the very top. For classes, the full c++ code misses imports. I now have this:

```cpp
// file: classes.cpp
#include <string>
#include <emscripten.h>
#include <emscripten/bind.h>

using namespace emscripten;

class MyClass {
public:
  MyClass(int x, std::string y)
    : x(x)
    , y(y)
  {}

  void incrementX() {
    ++x;
  }

  int getX() const { return x; }
  void setX(int x_) { x = x_; }

  static std::string getStringFromInstance(const MyClass& instance) {
    return instance.y;
  }

private:
  int x;
  std::string y;
};

// Binding code
EMSCRIPTEN_BINDINGS(my_class_example) {
  class_<MyClass>("MyClass")
    .constructor<int, std::string>()
    .function("incrementX", &MyClass::incrementX)
    .property("x", &MyClass::getX, &MyClass::setX)
    .class_function("getStringFromInstance", &MyClass::getStringFromInstance)
    ;
}
```
And I have this JavaScript snippet:
```javascript
// file: classes_post.js
var instance = new Module.MyClass(10, "hello");
instance.incrementX();
instance.x; // 11
instance.x = 20; // 20
Module.MyClass.getStringFromInstance(instance); // "hello"
instance.delete();
```
I try to compile (there is no info on the page on how to do it):

    emcc -O1 --bind -o classes.html --post-js classes_post.cpp classes.cpp

But when I open the generated HTML, I only get:

```
classes.js:3553 Uncaught TypeError: Module.MyClass is not a constructor
    at classes.js:3553
```
How to make this example work?

**Comment by sbc100** [comment]
Most likely the problem is that module is not initialized synchronously so the example code needs to wait for he Module to ready before it can be run.   Can you running your code in `addOnPostRun(function() { ....code.... });` ?

**Comment by Sciss** [comment]
Excellent - that works! I thought `--post-js` was precisely for stuff that runs when the module was initialised, but I guess I misread. Using `addOnPostRun` works.

**Comment by Sciss** [comment]
I could submit a PR for the documentation to clarify this example

**Comment by kripken** [comment]
@Sciss a PR would be great, thanks!
