### ISSUE TITLE
"COMMAND may not contain literal quotes" when using emcmake

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#13126]
https://github.com/emscripten-core/emscripten/blob/e61e33c96bef626b046ee2187911d692b9435598/cmake/Modules/Platform/Emscripten.cmake#L396

This line sets `CMAKE_CROSSCOMPILING_EMULATOR` a quoted string, which then can't be used in cmake `COMMAND`:

```
add_custom_command(TARGET hwy POST_BUILD
    COMMAND ${CMAKE_CROSSCOMPILING_EMULATOR} $<TARGET_FILE:hwy_list_targets> || (exit 0))
```

```
CMake Error at third_party/highway/CMakeLists.txt:188 (add_custom_command):
  COMMAND may not contain literal quotes:

    "C:/Users/Kagami/Documents/GitHub/emsdk/node/12.18.1_64bit/bin/node.exe"
```

The value must be unquoted.

**Comment by sbc100** [comment]
I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/10028.  And yes we should fix it!

**Comment by saschanaz** [comment]
Cool, closing
