### ISSUE TITLE
wasm-ld: error: unknown file type: dist/lib/allformats.o

### ISSUE THREAD

**Issue by wanghuan578** [emscripten-core/emscripten#13129]
root@ubuntu:/home/git/WasmVideoPlayer# cat build_decoder.sh 
emconfigure ./configure --cc="emcc" --cxx="em++" --ar="emar" --ranlib="emranlib" --prefix=$(pwd)/../WasmVideoPlayer/dist --enable-cross-compile --target-os=none \
        --arch=x86_32 --cpu=generic --enable-gpl --enable-version3 --disable-avdevice --disable-swresample --disable-postproc --disable-avfilter \
        --disable-programs --disable-logging --disable-everything --enable-avformat --enable-decoder=hevc --enable-decoder=h264 --enable-decoder=aac \
        --disable-ffplay --disable-ffprobe --disable-ffserver --disable-asm --disable-doc --disable-devices --disable-network --disable-hwaccels \
        --disable-parsers --disable-bsfs --disable-debug --enable-protocol=file --enable-demuxer=mov --enable-demuxer=flv --disable-indevs --disable-outdevs
if [ -f "Makefile" ]; then
  echo "make clean"
  make clean
fi
echo "make"
emmake make -j4
echo "make install"
make install
cp ./libavformat/libavformat.a ../WasmVideoPlayer/dist/lib
cp ./libavcodec/libavcodec.a ../WasmVideoPlayer/dist/lib
cp ./libavutil/libavutil.a ../WasmVideoPlayer/dist/lib
cp ./libswscale/libswscale.a ../WasmVideoPlayer/dist/lib
cd ../WasmVideoPlayer
./build_decoder_wasm.sh

root@ubuntu:/home/git/WasmVideoPlayer# cat build_decoder_wasm.sh 
rm -rf libffmpeg.wasm libffmpeg.js
export TOTAL_MEMORY=67108864
export EXPORTED_FUNCTIONS="[ \
    '_initDecoder', \
    '_uninitDecoder', \
    '_openDecoder', \
    '_closeDecoder', \
    '_sendData', \
    '_decodeOnePacket', \
    '_seekTo', \
    '_main',
    '_malloc',
    '_free'
]"

echo "Running Emscripten..."
emcc decoder.c dist/lib/libavformat.a dist/lib/libavcodec.a dist/lib/libavutil.a dist/lib/libswscale.a dist/lib/allformats.o \
    -O3 \
    -I "dist/include" \
    -s WASM=1 \
    -s TOTAL_MEMORY=${TOTAL_MEMORY} \
    -s EXPORTED_FUNCTIONS="${EXPORTED_FUNCTIONS}" \
    -s EXTRA_EXPORTED_RUNTIME_METHODS="['addFunction']" \
    -s RESERVED_FUNCTION_POINTERS=14 \
    -s FORCE_FILESYSTEM=1 \
    -o libffmpeg.js

echo "Finished Build"

link error:
1 warning generated.
wasm-ld: error: unknown file type: dist/lib/allformats.o
emcc: error: '/home/git/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_4zjboqsr/libffmpeg.wasm /tmp/emscripten_temp_4zjboqsr/decoder_0.o dist/lib/libavformat.a dist/lib/libavcodec.a dist/lib/libavutil.a dist/lib/libswscale.a -L/home/tools/emscripten-2.0.8/system/local/lib dist/lib/allformats.o -L/home/tools/emscripten-2.0.8/system/lib -L/home/git/emsdk/upstream/emscripten/cache/wasm /home/git/emsdk/upstream/emscripten/cache/wasm/libc.a /home/git/emsdk/upstream/emscripten/cache/wasm/libcompiler_rt.a /home/git/emsdk/upstream/emscripten/cache/wasm/libc++-noexcept.a /home/git/emsdk/upstream/emscripten/cache/wasm/libc++abi-noexcept.a /home/git/emsdk/upstream/emscripten/cache/wasm/libdlmalloc.a /home/git/emsdk/upstream/emscripten/cache/wasm/libpthread_stub.a /home/git/emsdk/upstream/emscripten/cache/wasm/libc_rt_wasm.a /home/git/emsdk/upstream/emscripten/cache/wasm/libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --import-memory --strip-debug --export-table --growable-table --export initDecoder --export uninitDecoder --export openDecoder --export closeDecoder --export sendData --export decodeOnePacket --export seekTo --export main --export malloc --export free --export stackSave --export stackRestore --export stackAlloc --export __data_end --export __wasm_call_ctors --export __errno_location --export _get_tzname --export _get_daylight --export _get_timezone --export htons --export ntohs --export htonl --export emscripten_main_thread_process_queued_calls --export memalign --export memset -z stack-size=5242880 --initial-memory=67108864 --no-entry --max-memory=67108864 --global-base=1024' failed (1)

**Comment by wanghuan578** [comment]
any suggestion?

**Comment by sbc100** [comment]
What does `file  dist/lib/allformats.o` tell you?   I seems that it is not a wasm object file at all.    If you remove this file and then re-make it does command line is used to create it?

**Comment by wanghuan578** [comment]
Allformats. O is a product of ffmpeg. I understand it should be packaged into libavformat. But this is not the case. If allformats. O is removed during EMCC compilation, a link error wasm LD: error: unknown file type: allformats will be occur.  I don't know where the  dependency on this Allformats. O comes from? thank you

**Comment by sbc100** [comment]
Whatever build process is used to build that object file seems to be using the wrong compiler.    Most likely it is using the host compiler rather then emcc.

**Comment by wanghuan578** [comment]
![image](https://user-images.githubusercontent.com/11493412/103277244-8d3eea00-4a03-11eb-8955-e99a4aae773b.png)
i do use emcc for compiler

**Comment by sbc100** [comment]
Right, but you need to find the exact command that builds that object file.   I'm pretty sure its wrong.   Do you know what part of the script builds that object?  Can you attach the full output of a clean build?  It should show each compile command.

**Comment by wanghuan578** [comment]
![image](https://user-images.githubusercontent.com/11493412/103324234-979fc900-4a81-11eb-8919-03e285795965.png)

It's probably the problem of emscripten

**Comment by wanghuan578** [comment]
![image](https://user-images.githubusercontent.com/11493412/103324316-fd8c5080-4a81-11eb-95f6-93ce1e6287c1.png)
when i remove gcc，the compiler donot work，it was convinced using the gcc rathen than emcc. thanks

**Comment by wanghuan578** [comment]
i fix emcc error at version emsdk-2.0.2，the issue should be closed，thanks

**Comment by wanghuan578** [comment]
![image](https://user-images.githubusercontent.com/11493412/103333226-20c9f680-4aa8-11eb-95f2-10e147292e20.png)
