### ISSUE TITLE
pthread+modularize+ASan = exception

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#13138]
This program:
```
#include <thread>
int main() {
  std::thread([]{}).detach();
}
```
when compiled with the following flags:
```
--std=c++11 -pthread -fsanitize=address -s INITIAL_MEMORY=1073741824 -s 'EXPORT_NAME="loadEmscriptenModule"' -s MODULARIZE=1
```
fails at runtime directly after the module load (via the `loadEmscriptenModule()` call). The logged errors are:
```
a.out.js:2265 Module.instantiateWasm callback failed with error: ReferenceError: resetPrototype is not defined
createWasm @ a.out.js:2265
(anonymous) @ a.out.js:6960
onmessage @ a.out.worker.js:74
a.out.worker.js:24 worker.js onmessage() captured an uncaught exception: TypeError: Cannot read property 'emscripten_stack_set_limits' of undefined
threadPrintErr @ a.out.worker.js:24
onmessage @ a.out.worker.js:165
a.out.worker.js:24 TypeError: Cannot read property 'emscripten_stack_set_limits' of undefined
    at Module._emscripten_stack_set_limits (a.out.js:6987)
    at Object.establishStackSpace (a.out.js:2805)
    at onmessage (a.out.worker.js:111)
threadPrintErr @ a.out.worker.js:24
onmessage @ a.out.worker.js:166
a.out.js:2763 pthread sent an error! http://localhost:8000/a.out.worker.js:167: Uncaught TypeError: Cannot read property 'emscripten_stack_set_limits' of undefined
worker.onerror @ a.out.js:2763
error (async)
loadWasmModuleToWorker @ a.out.js:2762
getNewWorker @ a.out.js:2793
spawnThread @ a.out.js:5628
_emscripten_builtin_pthread_create @ a.out.js:5791
(anonymous) @ a.out.wasm:0x233e9
(anonymous) @ a.out.wasm:0x216a
(anonymous) @ a.out.wasm:0x1895
(anonymous) @ a.out.wasm:0x167b
main @ a.out.wasm:0x3bb1
(anonymous) @ a.out.js:2033
callMain @ a.out.js:7846
doRun @ a.out.js:7885
run @ a.out.js:7897
runCaller @ a.out.js:7829
removeRunDependency @ a.out.js:1980
(anonymous) @ a.out.js:2245
Promise.then (async)
(anonymous) @ a.out.js:2242
Promise.then (async)
instantiateAsync @ a.out.js:2240
createWasm @ a.out.js:2269
(anonymous) @ a.out.js:6960
(anonymous) @ VM1142:1
a.out.worker.js:167 Uncaught TypeError: Cannot read property 'emscripten_stack_set_limits' of undefined
    at Module._emscripten_stack_set_limits (a.out.js:6987)
    at Object.establishStackSpace (a.out.js:2805)
    at onmessage (a.out.worker.js:111)
Module._emscripten_stack_set_limits @ a.out.js:6987
establishStackSpace @ a.out.js:2805
onmessage @ a.out.worker.js:111
```

Note that removing `-fsanitize=address` avoids the issue. Alternatively, removing `EXPORT_NAME`+`MODULARIZE` options avoid the issue either. So, effectively, the ASan is unusable in case of a multithreaded modularized program. Emscripten version: 2.0.9.

**Comment by smileorigin** [comment]
Hello, do you now have other ways to detect memory leaks

**Comment by sbc100** [comment]
I've got a fix for fsanitize + threads:  #13183 , and another one to enable some testing of this: #13182

**Comment by smileorigin** [comment]
👍👍👍

**Comment by emaxx-google** [comment]
Thanks, Sam! I just tried fsanitize+threads (without modularize) and got the following exception:
```
function signature mismatch
    at __asan::AsanThread::ThreadStart(unsigned long long, __sanitizer::atomic_uintptr_t*)
    at __asan::asan_thread_start(void*)
    at Object.dynCall
    at onmessage
```
Is it a known issue (maybe already fixed by your changes?..) or should I file a new bug for that?

**Comment by sbc100** [comment]
Does your thread entry point have the correct signature (`void* func(void*)`)?

**Comment by emaxx-google** [comment]
Should be so, but let me try to minimize the reproducer and file a separate bug for that "function signature mismatch" issue.

**Comment by emaxx-google** [comment]
Hello, so "function signature mismatch" was indeed an unrelated thing (a bug in the code I'm porting).

But the overall combination "pthread+modularize+ASan" still doesn't work for me on the "tot" emscripten build. The current issue is, when using the same program as in the comment 0:

> a.out.worker.js:62 Uncaught (in promise) ReferenceError: WasmOffsetConverter is not defined
>    at moduleLoaded (a.out.worker.js:62)
>    at a.out.worker.js:90

I'm on "b50156cb04503580fdacb37239c7105dd26836c9" - that's what "emsdk install tot" pulls. I'm wondering if this version is supposed to already include the fix from #13183? (Is there a way to translate that build hash into date/commit?)

**Comment by sbc100** [comment]
b50156cb04503580fdacb37239c7105dd26836c9 is a revision from the emscripten-release repo here: 
 https://chromium.googlesource.com/emscripten-releases/.

You can find all the component revisions for a given release by looking at the DEPS file in that repo.  For example the emscripten revisions that went into b50156cb04503580fdacb37239c7105dd26836c9 can be seen here: https://chromium.googlesource.com/emscripten-releases/+/b50156cb04503580fdacb37239c7105dd26836c9/DEPS#24

**Comment by sbc100** [comment]
The easiest way to try the very latest emscripten is to check out emscripten from git.   You can do `./emcc` and it will use the local version of emscripten while still using emsdk for all other components.

I imagine that "pthread+modularize+ASan" is just not something that we have tested so is probably not expected to work yet.    Does "pthread+modularize" generally work?
