### ISSUE TITLE
Single quote in directory names to be packaged causes invalid JavaScript

### ISSUE THREAD

**Issue by thomasballinger** [emscripten-core/emscripten#13146]
When running a command like `emcc file.cpp -o file.html --preload-file myData` where myData contains a directory with a single quote `single'quote/`, invalid JavaScript like below is generated.

~~~
Module['FS_createPath']('/myData', 'single'quote', true, true);
~~~

Single quotes seem fine in non-directory paths.

Maybe adding a note to https://emscripten.org/docs/porting/files/packaging_files.html#valid-character-set would be useful, or maybe fixing this isn't bad.

**Comment by sbc100** [comment]
Seems worth fixing if you have such directories.   I'm not familiar with the file-packager code myself.  Do you think want to take a stab at it?  I will mark as help wanted in case anyone else does.

**Comment by thomasballinger** [comment]
Posted an initial fix before I forget, will look at contrib guidelines and tests and such sometime today.
