### ISSUE TITLE
Reset callMain() each time

### ISSUE THREAD

**Issue by nbarkhina** [emscripten-core/emscripten#13148]
I have an old C app which I compiled down to wasm with Emscripten. It works well the first time I invoke callMain() on the page. However the second time it throws many errors. It seems that the memory state from the first run is still there. Normally when I run the native version from the command line it works no matter how many times I run it. I was able to solve it eventually by copying the pre-run HEAPU8 array into a javascript variable and then loading it back in each time before I run the app. Is there a better way to do this?

Just wondering if this is by design or if there is some option or compiler flag that I missed that I could use.

Thanks

**Comment by sbc100** [comment]
If you want to run your main application many times and have a new state each time you really want to re-instantiate your module each time.   The way to do this with emscripten is to use `-s MODULARIZE` which allows you to create as many instances as you like.   You can even have many running at the same time.

**Comment by nbarkhina** [comment]
I did try that option as well. One thing I noticed though was that every time I instantiated a new instance of the Module, my Google Chrome's memory would jump up a few megs. Eventually it did go down a little, probably because of JavaScript's own garbage collector but when I used the method I described above the memory never jumped at least. So while it probably took a larger upfront memory requirement at least it seemed to be running steady. I guess since there's no controlling the garbage collector, and across different browsers I was worried about the performance hit as well since then I have to wait for onRuntimeInitialized again. This is the type of app where the user may re-run callMain many times in a session, maybe even hundreds of times I thought maybe the method I came up with would work. But do you see any issues with the first way I was doing it?

Thanks

**Comment by sbc100** [comment]
Re-setting the memory contents may work, but you could run into issues with other state, such as state stored in JS objects/libraries or in WebAssembly globals.   But if it works for you then maybe its fine in this case.

Re-instantiating everything should to pretty fast as the WebAssembly module itself should be re-used between instances, but it will generate garbage that is then collected each time you run your program, yes.

**Comment by nbarkhina** [comment]
Understood that is good to know. I will do a bit more testing around the issues you described.

Thank you!
