### ISSUE TITLE
Option to turn off chmod for .wasm files

### ISSUE THREAD

**Issue by ChrisgammaDE** [emscripten-core/emscripten#13158]
Hello,

I'm currently trying to compile with emcc on windows subsystem for linux (WSL).  
So far it compiles just fine and everything works, but llvm-objcopy tries to change the file permissions of the .wasm file and errors out. The permissions can't be changed because I access windows user files from WSL.

How can I turn this `chmod +x` off, because it breaks my compilation chain.

<details>
    <summary>File Permissions</summary>

````
$ ls -lha
-rwxrwxrwx 1 root root   97 Dec 31 13:04 hello.c
-rwxrwxrwx 1 root root  12K Dec 31 13:45 hello.wasm
````
</details>
<details>
      <summary>Error Output:</summary>
    
````
$ emcc hello.c -o hello.html

/home/chris/.emsdk/upstream/bin/llvm-objcopy: error: 'hello.wasm': Operation not permitted
Traceback (most recent call last):
  File "/home/chris/.emsdk/upstream/emscripten/emcc.py", line 3329, in <module>
    sys.exit(main(sys.argv))
  File "/home/chris/.emsdk/upstream/emscripten/emcc.py", line 3322, in main
    ret = run(args)
  File "/home/chris/.emsdk/upstream/emscripten/emcc.py", line 2192, in run
    post_link(options, wasm_target, wasm_target, target)
  File "/home/chris/.emsdk/upstream/emscripten/emcc.py", line 2289, in post_link
    do_binaryen(target, options, wasm_target)
  File "/home/chris/.emsdk/upstream/emscripten/emcc.py", line 2732, in do_binaryen
    building.strip(wasm_target, wasm_target, debug=strip_debug, producers=strip_producers)
  File "/home/chris/.emsdk/upstream/emscripten/tools/building.py", line 1362, in strip
    run_process(cmd)
  File "/home/chris/.emsdk/upstream/emscripten/tools/shared.py", line 94, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/chris/.emsdk/upstream/bin/llvm-objcopy', 'hello.wasm', 'hello.wasm', '--remove-section=.debug*', '--remove-section=producers']' returned non-zero exit status 1.
````

</details>

**Comment by sbc100** [comment]
How can you tell that it is a chmod operation that is causing llvm-objcopy to fail?

Does `llvm-objcopy` generally fail for you when using WSL?   (i.e. is this and upstream llvm bug?)

As a workaround can you build in the linux filesystem and then copy the result over to windows?

**Comment by sbc100** [comment]
The program that originally gives the wasm its executable permissions is (I believe) lld (wasm-ld).    If wasm-ld didn't do this does llvm-objcopy then start working?

**Comment by ChrisgammaDE** [comment]
> How can you tell that it is a chmod operation that is causing llvm-objcopy to fail?

When I try to execute chmod manually it throws this error too. 
When I execute chmod as root via sudo, no error message is displayed. 

When running emcc via sudo (running the emcc executable without path) everything works normally.

As far as my understanding goes, this should also happen in other folders when you can't update the file permissions.

My workaround so far is basically running it via sudo. Because with sudo the $Path isn't set I just looked up the path where the emcc script is located and pasted it into a transparent script.

**Comment by sbc100** [comment]
Can you run `llvm-objcopy` in isolation and see it fail?   If the file being copied is not executable that does that fix the issue?    It sounds like an possible llvm-objcopy but I think we need to understand a little more about exactly what is going on before filing a bug with the llvm project.

**Comment by ChrisgammaDE** [comment]
I don't know what arguments llvm-objcopy is called with, but running it manually seem to work fine now.
I rebooted my system a few times since posting this and interestingly it now seem to work fine. Even when not running it as sudo.

Thanks for your patience!
