### ISSUE TITLE
How can I interrupt `emscripten_sleep`?

### ISSUE THREAD

**Issue by embeddedt** [emscripten-core/emscripten#13162]
I am using Asyncify with Emscripten 2.0.4.

In my project I call `emscripten_sleep` to suspend for an indefinite amount of time. I would like to be able to interrupt that sleep and return control to my program early, similarly to how a signal would interrupt it on a real POSIX system.

I've read a number of posts but haven't found anything to indicate that Emscripten supports signals in this manner. What is the equivalent facility?

**Comment by curiousdannii** [comment]
Just write your own custom async function that resolves either when a timer runs or when your custom trigger runs.

**Comment by embeddedt** [comment]
That makes perfect sense. Not sure why I didn't think of that. Thanks; I'll
give it a try!

**Comment by embeddedt** [comment]
Evidently I forgot to write back here. This method worked perfectly!
