### ISSUE TITLE
Is it possiable for Emscripten to call ios native api, such as VideoToolBox ?

### ISSUE THREAD

**Issue by schyjxy** [emscripten-core/emscripten#13188]
Write a wrapper for videoToolBox api, and expose it to Emscripten. Will it work as expected?

**Comment by curiousdannii** [comment]
Anything a web page could do, an Emscripten compiled project can do. If there's a native web API, great! Otherwise you could look at Cordova to see what can be done. You can use Emscripten output in a Cordova app too.

**Comment by schyjxy** [comment]
@curiousdannii Thanks!

**Comment by sbc100** [comment]
Can this issue be closed now?
