### ISSUE TITLE
"ASSERTIONS=2" + "g" = broken in 2.0.10

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#13191]
Compiling the following program:
```
int main() {}
```
with the following flags:
```
-g -s ASSERTIONS=2
```
results in the following error in Emscripten 2.0.10:
```
Fatal: Module::addGlobal: __stack_base already exists
emcc: error: 'emsdk/upstream/bin/wasm-emscripten-finalize --detect-features --minimize-wasm-changes -g --dyncalls-i64 --check-stack-overflow --dwarf a.out.wasm -o a.out.wasm' failed (1)
```

This is a 2.0.10 regression, since on 2.0.9 this combination works fine.

**Comment by emaxx-google** [comment]
Maybe it's a dupe of #12834, but I don't know how to verify that.

**Comment by sbc100** [comment]
Yes its a dupe of #12834 which has been fixed.  I'm not sure if that change made it into 2.0.11 but its worth a try.

**Comment by emaxx-google** [comment]
Yup, confirmed that after switching to "tot" emsdk this problem disappeared. Thanks.
