### ISSUE TITLE
glfwGetKey always returns 0

### ISSUE THREAD

**Issue by wdanilo** [emscripten-core/emscripten#1320]
Hi!
I've noticed that, when using glfw with Emscripten, the glfwGetKey function always returns 0.

You can check it out with any example shipped with emscripten by writing:
printf("is 'a' pressed?: %d\n", glfwGetKey('a'));

and pressing keys over canvas.

**Comment by Tbwas** [comment]
the same issue, glfw 3.2.1 , glfwGetKey always returns 0
