### ISSUE TITLE
while Im linking  some .bc files and .a files together into a webasembly ,i got wasm-ld unknown file types problem

### ISSUE THREAD

**Issue by iamjustadd** [emscripten-core/emscripten#13206]
Here is the .bc file compile command:
`em++ -std=c++17 -w -DSK_RELEASE -DSK_GL --no-heap-copy -DSK_DISABLE_READBUFFER -s ERROR_ON_UNDEFINED_SYMBOLS=0 -DSK_DISABLE_AAA -lEGL -lGLESv2 -DSK_SUPPORT_GPU=1 -DGR_GL_CHECK_ALLOC_WITH_GET_ERROR=0 -Oz -g2  -I../../lanhu/master/fb/jsoncpp/include -I../../lanhu/master/fb/jsoncpp/include/json -I../../lanhu/master/fb/jsoncpp/src -I../../lanhu/master/fb -I../../lanhu/master/fb/fbs -I../../lanhu/master/fb/core/changeset -I../../lanhu/master/fb/core -I../../lanhu/master/fb/core/layer -I../../lanhu/master/fb/core/style -I../../lanhu/master/fb/include -I../../lanhu/master/include -I../../lanhu/master/fb -I../../lanhu/master/fb/data -I../../lanhu/master/fb/validation -I../../lanhu/master/fb/include -I../../lanhu/master/generalIndex -I../../ -I../../third_party/boost_1_74_0 (many many many include dirs) ../../lanhu/master/touchvg/src/cmdbase/mgcmddraw.cpp ../../lanhu/master/touchvg/src/cmdbase/mgdrawarc.cpp ../../lanhu/master/touchvg/src/cmdbase/mgdrawline.cpp ../../lanhu/master/touchvg/src/cmdbase/mgdrawrect.cpp ../../lanhu/master/touchvg/src/cmdmgr/cmdsubject.cpp ../../lanhu/master/touchvg/src/cmdmgr/mgactions.cpp(many many many source files) -o ../../out/lib/super.bc -s WASM=0`

And here is the WebAssembly compile command:
`em++ -std=c++17 -w -DSK_RELEASE -DSK_GL --no-heap-copy -DSK_DISABLE_READBUFFER -s ERROR_ON_UNDEFINED_SYMBOLS=0 -DSK_DISABLE_AAA -lEGL -lGLESv2 -DSK_SUPPORT_GPU=1 -DGR_GL_CHECK_ALLOC_WITH_GET_ERROR=0 -Oz -g2  -I../../lanhu/master/fb/jsoncpp/include -I../../lanhu/master/fb/jsoncpp/include/json -I../../lanhu/master/fb/jsoncpp/src -I../../lanhu/master/fb -I../../lanhu/master/fb/fbs -I../../lanhu/master/fb/core/changeset -I../../lanhu/master/fb/core -I../../lanhu/master/fb/core/layer -（many many many include dirs） -I../../lanhu/master/include/channel --bind  -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 -s FORCE_FILESYSTEM=0 -s NO_EXIT_RUNTIME=1 -s USE_FREETYPE=1 -s USE_LIBPNG=1 -s WARN_UNALIGNED=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s USE_WEBGL2=1 -s WASM=1 -s INITIAL_MEMORY=128MB ../../out/lib/super.bc /opt/lib/masterkit/libskshaper.a /opt/lib/masterkit/libharfbuzz.a /opt/lib/masterkit/libicu.a /opt/lib/masterkit/libskia.a /opt/lib/masterkit/libflatbuffers.a -o ../../out/masterkit_wasm/masterkit.html`

And here I got error:
`wasm-ld: error: unknown file type: ../../out/lib/super.bc
em++: error: '/emsdk/upstream/bin/wasm-ld -o ../../out/masterkit_wasm/masterkit.wasm ../../out/lib/super.bc -L/emsdk/upstream/emscripten/system/local/lib /opt/lib/masterkit/libskshaper.a -L/emsdk/upstream/emscripten/system/lib /opt/lib/masterkit/libharfbuzz.a -L/emsdk/upstream/emscripten/cache/wasm /opt/lib/masterkit/libicu.a /opt/lib/masterkit/libskia.a /opt/lib/masterkit/libflatbuffers.a /emsdk/upstream/emscripten/cache/wasm/libpng.a /emsdk/upstream/emscripten/cache/wasm/libz.a /emsdk/upstream/emscripten/cache/wasm/libfreetype.a --whole-archive /emsdk/upstream/emscripten/cache/wasm/libembind-rtti.a --no-whole-archive /emsdk/upstream/emscripten/cache/wasm/libc.a /emsdk/upstream/emscripten/cache/wasm/libcompiler_rt.a /emsdk/upstream/emscripten/cache/wasm/libc++.a /emsdk/upstream/emscripten/cache/wasm/libc++abi.a /emsdk/upstream/emscripten/cache/wasm/libdlmalloc-debug.a /emsdk/upstream/emscripten/cache/wasm/libc_rt_wasm.a /emsdk/upstream/emscripten/cache/wasm/libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --export-table --export main --export emscripten_stack_get_end --export emscripten_stack_get_free --export emscripten_stack_init --export emscripten_stack_get_base --export __cxa_demangle --export stackSave --export stackRestore --export stackAlloc --export __wasm_call_ctors --export fflush --export __errno_location --export malloc --export free --export _get_tzname --export _get_daylight --export _get_timezone --export memalign --export memset --export setThrew --export realloc --export testSetjmp --export saveSetjmp --export emscripten_main_thread_process_queued_calls --export _ZSt18uncaught_exceptionv --export __cxa_find_matching_catch --export __cxa_is_pointer_type --export __cxa_can_catch -z stack-size=5242880 --initial-memory=134217728 --no-entry --max-memory=2147483648 --global-base=1024' failed (1)
make: *** [Makefile:407: superwasm] Error 1`

So, What's happenning to my command or parameters? How can I  fix such problems and go ahead. Thank you sir

**Comment by iamjustadd** [comment]
`file ../../out/lib/super.bc
../../out/lib/super.bc: ASCII text, with very long lines`

```
/emsdk/upstream/bin/llvm-nm ../../out/lib/super.bc
/emsdk/upstream/bin/llvm-nm: error: ../../out/lib/super.bc The file was not recognized as a valid object file
```
```
 bc ../../out/lib/super.bc
bc 1.07.1
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006, 2008, 2012-2017 Free Software Foundation, Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'.
../../out/lib/super.bc 1: syntax error
../../out/lib/super.bc 1: syntax error
../../out/lib/super.bc 1: illegal character: ?
../../out/lib/super.bc 1: illegal character: :
```

Here is some supplement to my question .hope it can give you some hints.

**Comment by sbc100** [comment]
There was a change in emscripten behaviour in this area.   As of 2.0.3 that default for emscripten when linking (i.e. when building without -c) is to produce javascript output.   From th changelog:

```
- The default output format is now executable JavaScript.  Previously we would   
  default to output objecting files unless, for example, the output name ended   
  in `.js`.  This is contrary to behaviour of clang and gcc.  Now emscripten        
  will always produce and executable unless the `-c`, `-r` or `-shared` flags                    
  are given.  This is true even when the name of the output file ends in `.o`.   
  e.g, `emcc foo.c -o foo.o` will produce a JavaScript file called `foo.o`.         
  This might surprise some users (although it matches the behavior of existing   
  toolchains) so we now produce a warning in this case.   
```

You can still get the old behaviour if you really want it by passing `-r` to emcc.   However I would advise you to instead use separate compilation (-c to object files) and use archive files emar to combine your objects (using emar) before linking them.    Also, I would recommend against using the `.bc` extension as (unless you are doing `-flto`) the object files that emscripten produces by default are no longer bitcode files but wasm object files.

**Comment by iamjustadd** [comment]
Thanks sir ,this problem is done. So kind you are. THANKS.
