### ISSUE TITLE
Preload plugins not used when LZ4 enabled

### ISSUE THREAD

**Issue by dalcde** [emscripten-core/emscripten#13212]
If both `-s LZ4` and `--use-preload-plugins` is specified, then the preload plugins aren't actually used.

Without LZ4, the preload plugins are called via DataRequest.finish. If LZ4 is enabled, then the DataRequest code is still generated, but it is never called, as we use LZ4.loadPackage to load the package instead.

**Comment by rth** [comment]
@dalcde This can now be closed I think?
