### ISSUE TITLE
LinkError: module="env" function="pthread_mutexattr_init" when using webpack

### ISSUE THREAD

**Issue by fabmax** [emscripten-core/emscripten#13223]
Hi,

I'm compiling a rather large project (nvidia PhysX) with the latest emsdk (2.0.11). I can load the resulting wasm module in a browser and that works fine. But after packing it with webpack I get the following error:

```
wasm streaming compile failed: LinkError: WebAssembly.instantiate(): Import #21 module="env"
function="pthread_mutexattr_init" error: function import requires a callable
```

The thing is that everything works fine when I use emsdk 1.40.1.

I also tried a few other emsdk 2.0.x versions and got similar errors, however older ones complained about __handle_stack_overflow instead of pthread_mutexattr_init. Are there any extra steps I have to take when using webpack?

I'm sorry to bother you in case this is actually a webpack issue and not caused by emscripten.

**Comment by sbc100** [comment]
`pthread_mutexattr_init` should be a native functions (its part of libc.a) and should be be imported from the environment at all.    How are you linking your final binary?  (what flags are you passing?)

**Comment by fabmax** [comment]
Here are the linker flags:

```
-s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -s ALLOW_MEMORY_GROWTH=1 -std=c++11 
-fno-exceptions -ffunction-sections -fdata-sections -fstrict-aliasing -ferror-limit=0
-DNDEBUG -O2  -O2 --bind -s MODULARIZE=1 -s EXPORT_NAME=PHYSX -s ALLOW_MEMORY_GROWTH=1
-s ASSERTIONS=1
```

**Comment by fabmax** [comment]
Hmm, I just refactored the code I was using and threw away the entire Embind code and replaced it with WebIDL Binder and that seems to have fixed it somehow.

Maybe there was a problem in the Embind related code I removed. Anyway, it's working now so I'm fine with that.

**Comment by sbc100** [comment]
Well thats a copletely mystery .. I don't see how pthread_mutexattr_init could ever be left undefined when linking an executable (perhaps if you had built with SIDE_MODULE it would have been possible .. or maybe with `-Wl,-nostdib`, but I can't think of any other way).
