### ISSUE TITLE
glfwSetKeyCallback disables glfwSetCharCallback

### ISSUE THREAD

**Issue by wdanilo** [emscripten-core/emscripten#1322]
Hi, please take a look at emscripten/tests/glfw.c file.
According to glfw documentation: http://www.glfw.org/GLFWReference27.pdf
If you want to capture unicode characters you should use  glfwSetCharCallback and if you want to capture special key presses, you should use glfwSetKeyCallback and you can use both of them in the same time.

The problem is that when you're using them together in Emscripten only glfwSetKeyCallback is called. If you comment out the line with glfwSetKeyCallback, the glfwSetCharCallback starts working.

**Comment by satoshinm** [comment]
> E.g. while event.keyCode is mapped to the ASCII value for a bunch of characters, it takes a value of 40 for the down arrow, which is the ASCII value of (. 

event.keyCode is 40 when fired from the keydown event (testing using `addEventListener('keydown',(ev)=>{console.log(ev.keyCode)})`), and although is ASCII for the character "(", this is not the keyCode fired when pressing this key. I get event.keyCode == 57 when pressing "(" or "9" on Firefox 54.0b2, Safari TP 29, and Chrome 58.0.3029.96. Is there really an ambiguity with the arrow keys? However, all these browsers now also support `event.key` (set to "ArrowDown", etc.).
