### ISSUE TITLE
TypeError: addOnPostRun is not a function when building NodeJS module

### ISSUE THREAD

**Issue by loretoparisi** [emscripten-core/emscripten#13248]
Hello, I get this error when compiling the [FastText](https://github.com/facebookresearch/fastText/tree/master/webassembly) module for NodeJS. I already have the `EXTRA_EXPORTED_RUNTIME_METHODS` in the flags

```
EMCXXFLAGS = --bind --std=c++11 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['addOnPostRun','FS']" -s "DISABLE_EXCEPTION_CATCHING=0" -s "EXCEPTION_DEBUG=1" -s "FORCE_FILESYSTEM=1" -s "MODULARIZE=1" -s "EXPORT_ES6=1" -s 'EXPORT_NAME="FastTextModule"' -s "USE_ES6_IMPORT_META=0" -Isrc/
```

and to avoid OS related escaping issue as described in emscripten [FAQ](https://emscripten.org/docs/getting_started/FAQ.html#why-do-i-get-a-nameerror-or-a-problem-occurred-in-evaluating-content-after-a-s-when-i-use-a-s-option), I have also tried to read from a file the values with `-s "EXTRA_EXPORTED_RUNTIME_METHODS=@extra.txt"` having `['addOnPostRun','FS']` in the file `extra.txt`, but no solution worked for me.
My modularized library is [here](https://github.com/loretoparisi/fasttext.js/tree/master/wasm) and the error can be reproduced doing

```
cd fasttext.js/wasm
node predict.js
mbploreto:wasm loretoparisi$ node predict.js 
/Users/loretoparisi/Documents/Projects/AI/fasttext.js/wasm/fasttext_wasm.js:230
      throw ex;
      ^

TypeError: fastTextModule.addOnPostRun is not a function
```

The error comes out when trying to access the method `addOnPostRun` on the modularized object here:

```javascript
const fastTextModularized = require('./fasttext_wasm.js');
const fastTextModule = fastTextModularized();

let postRunFunc = null;
const addOnPostRun = function(func) {
  postRunFunc = func;
};

fastTextModule.addOnPostRun(() => { // <--- TypeError: addOnPostRun is not a function
  if (postRunFunc) {
    postRunFunc();
  }
});
```

**Comment by sbc100** [comment]
We should certainly look into why that method isn't be exported correctly... but there is another way you can add a post-run method.

You can pass a dictionary containing a `postRun` array to the constructor function.  So something like `const fastTextModule = fastTextModularized({postRun: [myFunc]});`

**Comment by kripken** [comment]
Testing
```
emcc tests/hello_world.c -s "EXTRA_EXPORTED_RUNTIME_METHODS=['addOnPostRun']"
```
It works, there is `Module["addOnPostRun"] = addOnPostRun;` in the output. Is it not present in the full testcase here? If so, then it might be good to check if one of the flags is at fault, to narrow this down.

**Comment by loretoparisi** [comment]
thanks, I solved it, it was related to [this](https://github.com/facebookresearch/fastText/issues/1173) issue. The modularized library was exported as a Promise, so there was some extra code to fix it.
