### ISSUE TITLE
Support loading of compiled wasm side modules

### ISSUE THREAD

**Issue by waterlike86** [emscripten-core/emscripten#13262]
use case:
for performance reasons we fetch and compile a side module on a separate thread and post it over to the worker thread with the main module.
it would be nice to extend the current code to allow loading of compiled wasm modules

**Comment by sbc100** [comment]
Have you looked at the existing `instantiateWasm` callback.  This is how our worker.js avoids re-loading the module on each worker.

According to the commend:

```
  // User shell pages can write their own Module.instantiateWasm = function(imports, successCallback) callback                                                              
  // to manually instantiate the Wasm module themselves. This allows pages to run the instantiation parallel
  // to any other async startup actions they are performing.   
```

**Comment by waterlike86** [comment]
> Have you looked at the existing `instantiateWasm` callback. This is how our worker.js avoids re-loading the module on each worker.

yes we use that for our main module, how can i use that with a side module?

**Comment by sbc100** [comment]
Oh I see, your original post didn't mention you were doing MAIN_MODULE/SIDE_MODULE splitting.   I guess we need to extend this framework.   In fact I'm most likely going to need that very soon in my work on pthreads + dynamic linking (which should soon be possible but isn't today).

**Comment by sbc100** [comment]
My apologies, you did mention the side module in your original post, I just didn't read it correctly.

**Comment by sbc100** [comment]
Can we re-title to `Support loading of compiled wasm side modules`
