### ISSUE TITLE
Bad warning if INITIAL_MEMORY is set without unit

### ISSUE THREAD

**Issue by anfelor** [emscripten-core/emscripten#13277]
An invocation of `emcc -O2 -Winline -s INITIAL_MEMORY=335104000` gives the warning: 
```
emcc: error: For wasm, INITIAL_MEMORY must be a multiple of 64KB, was 335104000
```
which is non-sensical since: `335104000 / 64000 = 5236`. This works if we use `-s INITIAL_MEMORY=335104KB`.
Expected behaviour would be a better error message or a documentation of the flag in the docs.

**Comment by sbc100** [comment]
64KB in this context is 60 x 1024 = 65536.    This the WebAssembly page side.   

I suppose we could write 64KiB to be more precise.  Generally in computing we still use kilobyte to mean 1024 bytes even though we should technically always say "kibibyte" I suppose.

**Comment by anfelor** [comment]
@sbc100 Yes, this also happens when it is a multiple of `64 * 1028`. The problem is the missing unit.

**Comment by sbc100** [comment]
Sorry, where is the missing unit?   If you interpret KB to be 1024 everything works fine, right?

**Comment by sbc100** [comment]
I updated the message to explicitly use KiB

**Comment by anfelor** [comment]
I think I expressed myself badly. The problem is that the error message does not indicate that one has to give a unit for the number like `KB` or now `KiB`. If you just give a number without a unit (assuming it stands for bytes), it will always throw that message no matter whether the number is divisible by `64 * 1028`.

**Comment by sbc100** [comment]
Thats not true you can give a raw numer if just has to be divisible by 64Kb (65536).

For example, in your case you want  335104Kb so you do 335104 * 1024 = 343146496.   And that works:

```
$ ./emcc tests/hello_world.c -s INITIAL_MEMORY=343146496
```

**Comment by anfelor** [comment]
Ah, yes, you are right. Sorry for the confusion
