### ISSUE TITLE
how to explicitly opts in to >2GB+ heaps?

### ISSUE THREAD

**Issue by yejun81** [emscripten-core/emscripten#13285]
as described in settings.js, i'm wondering how to explicitly opts in to >2GB+ heaps, thanks.

//   * If the maximum heap size is over 2GB, then pointers must be unsigned in
//     JavaScript, which increases code size. We don't want memory growth builds
//     to be larger unless someone explicitly opts in to >2GB+ heaps.
//   * Historically no VM has supported more >2GB+, and only recently (Mar 2020)
//     has support started to appear. As support is limited, it's safer for
//     people to opt into >2GB+ heaps rather than get a build that may not
//     work on all VMs.
//
// (This option was formerly called WASM_MEM_MAX and BINARYEN_MEM_MAX.)
var MAXIMUM_MEMORY = 2147483648;

**Comment by sbc100** [comment]
I think you opt in by setting this to a value that is greater then 2Gb.   e.g. `-s MAXIMUM_MEMORY=2.2Gb`.

**Comment by yejun81** [comment]
> I think you opt in by setting this to a value that is greater then 2Gb. e.g. `-s MAXIMUM_MEMORY=2.2Gb`.

i have tried this, it doesn't work.

**Comment by sbc100** [comment]
Sorry you can't use float value.  But you can do 2200mb or just specify that in kb or just bytes if you prefer.

**Comment by sbc100** [comment]
(You can also use `3gb`, for example)

**Comment by yejun81** [comment]
> (You can also use `3gb`, for example)

hi.
before i made this issue, i tried to set -s MAXIMUM_MEMORY=2684354560 ,（2.5G） and it didn't work(in chrome).Does it works well with you？

**Comment by sbc100** [comment]
Do you mean it didn't compile or it didn't run?   I thought this bug was that you not able to build a module that requested >2Gb.

What exactly do you mean "it didn't work"?  I can build hello world with `-s MAXIMUM_MEMORY=2684354560` and it works fine for me, but I guess I'm not trying to actually allocate that much.

If the problem is actually growing the memory to a size greater than 2gb there could be a chrome flag required to enable that, but I don't think so.   @kripken would know more.

**Comment by kripken** [comment]
This is on by default in recent chrome. But on node.js it may not work in older versions, for example.

There are some tests for this, that may help to look at - they definitely pass. Specifically, grep for `test_zzz_zzz_4GB` in `tests/*`. (You can run it with `./tests/runner.py browser.test_zzz_zzz_4GB`.)

**Comment by yejun81** [comment]
> Do you mean it didn't compile or it didn't run? I thought this bug was that you not able to build a module that requested >2Gb.
> 
> What exactly do you mean "it didn't work"? I can build hello world with `-s MAXIMUM_MEMORY=2684354560` and it works fine for me, but I guess I'm not trying to actually allocate that much.
> 
> If the problem is actually growing the memory to a size greater than 2gb there could be a chrome flag required to enable that, but I don't think so. @kripken would know more.

thanks.
the problem is exactly i can't growing the memory to a size greater than 2gb,and i want to know how to make this.

**Comment by yejun81** [comment]
> This is on by default in recent chrome. But on node.js it may not work in older versions, for example.
> 
> There are some tests for this, that may help to look at - they definitely pass. Specifically, grep for `test_zzz_zzz_4GB` in `tests/*`. (You can run it with `./tests/runner.py browser.test_zzz_zzz_4GB`.)

thanks.
yes, when i update chrome to newest version, i can get memory large than 2G.
but when i run `python3 tests/runner.py browser.test_4GB`,i get this error:
`ERROR: could not find the following tests: browser.test_4GB`
and there is test_4GB.cpp file right there in tests/browser/.

**Comment by sbc100** [comment]
The browser test is called `test_zzz_zzz_4GB`.  So you need to run `./tests/runner.py browser.test_zzz_zzz_4GB`.

It looks like the node test is in other and you can run it with `./tests/runner.py other.test_4GB`

**Comment by yejun81** [comment]
> The browser test is called `test_zzz_zzz_4GB`. So you need to run `./tests/runner.py browser.test_zzz_zzz_4GB`.
> 
> It looks like the node test is in other and you can run it with `./tests/runner.py other.test_4GB`

oh, i see.thanks a lot
