### ISSUE TITLE
Warn when using `-g` in combination with `-sASYNCIFY`

### ISSUE THREAD

**Issue by bmeurer** [emscripten-core/emscripten#13288]
When using `-sASYNCIFY` (or any other feature that involves complex program rewriting / optimizations via Binaryen) combined with `-g`, it'd be great to have `emcc` spit out a warning to let the developer know that what they are trying to do might not work, since the DWARF data is not updated correctly.

**Comment by sbc100** [comment]
@kripken is this true?   If it is then I guess that is a binaryen bug.. is it fixable?   If not, should we just ban that combination completely for now?
