### ISSUE TITLE
_gettimeofday is buggy

### ISSUE THREAD

**Issue by ikizir** [emscripten-core/emscripten#13351]
The bug is in javascript helper libraries provided by emscipten. The javascript counterpart of C standard gettimeofday function is buggy.

Original:
function _gettimeofday(ptr) {
var now = Date.now();
HEAP32[ptr >> 2] = now / 1e3 | 0;
HEAP32[ptr + 4 >> 2] = now % 1e3 * 1e3 | 0;
return 0;
}
It's definitely buggy.
I think, it should be something like this:

function _gettimeofday(ptr) {
var now = Date.now();
HEAP32[ptr >> 2] = (now / 1000) | 0;
HEAP32[(ptr >> 2)+1] = (now % 1000000) | 0;
return 0;
}
Version:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.12
clang version 12.0.0 (/b/s/w/ir/cache/git/https://lnkd.in/dZmPaQw-llvm-llvm--project 52e240a0721e4120a7143f6f5bab4760d28d48e8)
Target: wasm32-unknown-emscripten
Thread model: posix

The command which produces that code is:
emcc ./libHohhaEncBundle.a -O3  \
-s WASM=1 \
--minify 0 \
--js-library FunctionsToBeCalledFromC.node.js \
-s "EXPORTED_FUNCTIONS=[$EXPORTED_FUNCTIONS]" \
-s TOTAL_MEMORY=16777216 -s TOTAL_STACK=8388608 \
-s NO_FILESYSTEM=1 \
-s MODULARIZE=1 \
-s EXPORT_NAME="'HohhaEncModule'" \
--pre-js ./HohhaWASM-pre.tmp.js \
-s "EXPORTED_FUNCTIONS=[$EXPORTED_FUNCTIONS]" \
-s NO_EXIT_RUNTIME=1 \
-s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall",  "cwrap", "writeArrayToMemory", "UTF8ToString", "stringToUTF8"]' \
-o libHohhaEnc.js \
-s ASSERTIONS=1 \
-SAFE_HEAP=1

**Comment by gl84** [comment]
Why do you suspect the function is buggy?

I'm no JS expert but isn't ```ptr + 4 >> 2``` the same as ```(ptr >> 2) + 1``` when one respects JS operator precedence?

**Comment by ikizir** [comment]
Oh! Really?
You may be right. I may be wrong.
But I couldn't understand the reason to write same function in that way.
I thought about every single reason to write that code in that way. And I couldn't find any logical explanation.
Maybe, it's not buggy by functionality. But that function is definitely buggy.

**Comment by kripken** [comment]
> I'm no JS expert but isn't ptr + 4 >> 2 the same as (ptr >> 2) + 1 when one respects JS operator precedence?

Yes, it is confusing, but that is how it works.
