### ISSUE TITLE
WebGPU upgrade

### ISSUE THREAD

**Issue by bfierz** [emscripten-core/emscripten#13379]
Hi,

It looks like Emscriptens WebGPU implementation is not up to date with the latest changes in Chrome Canary (and Googles Dawn). Especially, the definition of WGPUBindGroupLayoutEntry.

I was trying to figure out how to upgrade the current implementation, but couldn't find any instructions. Given what I've found, I assume that there's a mix of automatic and manual work.
Google Dawn seems to be the source for the upgrade and it offers two targets (emscripten_bits_gen emscripten_bits_gen__json_tarball) generating some of the content of library_webgpu.js.

I would like to contribute, however, before trying to implement something manually that is generated otherwise, I am opening this issue. The background is rendering artifacts (https://github.com/ocornut/imgui/pull/3632#issuecomment-767550489). Building the given sample directly using Dawn doesn't show any issue.

Best regards

**Comment by kainino0x** [comment]
This is already almost done in #13266.

**Comment by bfierz** [comment]
Thank you for notifying me.
Are there any instructions on how to do it next time?

**Comment by kainino0x** [comment]
The best guide right now is to look at previous PRs, plus here are some notes.

For `webgpu.h`, my strategy is to take a 3-way diff between Emscripten, [Dawn](https://source.chromium.org/chromium/chromium/src/+/master:out/Debug/gen/third_party/dawn/src/include/dawn/webgpu.h), and [webgpu-headers](https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.h). This lets you cherry-pick the relevant changes (e.g. skipping Dawn's testing stuff) though requires some context on whether Dawn or webgpu-headers has the latest/currently-accepted version of something. (For example, the reference/release calls are in Dawn and Emscripten for now, but webgpu-headers hasn't chosen between that a single `free` type call.)

Only two parts can be automated, which are explicitly marked:

- Tables of string enums
- struct_info

These can be updated by hand but auto-generation can make it easier to get right. OTOH these generators are part of Dawn so you have to check out Dawn to run them.

Also note there might be bigger refactors coming for `library_webgpu.js`, though not sure when. If that happens soon, we may try to land that before doing version updates.

**Comment by bfierz** [comment]
Thank you for the detailed explanations. I could already generate the tables from dawn, so that's a good start.
If further WebGPU work comes up, in this respect, I'll happily do some testing on my side.

Sidenote: I've tested the branch mentioned PR, unfortunately, it doesn't resolve my issue with the ImGui sample. I'll dig deeper, so see where the difference between latest chrome and Dawn HEAD is.
