### ISSUE TITLE
Undefined symbols for MAIN_MODULE=2 + ERROR_ON_UNDEFINED_SYMBOLS=1

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#13388]
When compiling
```C++
int main() { return 0;}
```
with ERROR_ON_UNDEFINED_SYMBOLS i always get:
  - a crash (for MAIN_MODULE=1)
  - an undefined symbol error (for MAIN_MODULE=2):     __stack_pointer...

I'm especially interested in the second case and wonder how one can export the symbols __stack_pointer, __memory_base, __table_base and __heap_base.

Used cmd to compile:
`em++ -O1 main.cpp -s MAIN_MODULE=2 -s EXPORTED_FUNCTIONS=[_main] -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s LLD_REPORT_UNDEFINED`

Thanks

**Comment by ravisumit33** [comment]
@sbc100 Although these symbols are not causing issue at runtime, I am still curious why they come at link time ?

**Comment by sbc100** [comment]
The basic problem is that `ERROR_ON_UNDEFINED_SYMBOLS` is not designed to be used with `MAIN_MODULE`.   I'll take a look at making this work. or making it into an error.

**Comment by sbc100** [comment]
This should now be fixes as of #13848
