### ISSUE TITLE
-s ASSERTIONS=1|2 not working with ASYNCIFY=1

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#13423]
Hi. js-dos uses `ASYNCIFY=1` to avoid infinite loops in dosbox. And it works fine, however not all functions already added to asyncify list. I trying to use `-s ASSERTIONS=1|2` to get correct exception stack to add missed functions. However if I enable any assertion level dosbox didn't start with this exception:
```
direct.ts:25 Invalid UTF-8 leading byte 0xbb encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!
a @ direct.ts:25
warnOnce @ VM193:502
UTF8ArrayToString @ VM193:965
UTF8ToString @ VM193:996
emsc_client_stdout @ VM193:1858
imports.<computed> @ VM193:6190
client_stdout(char const*, unsigned int) @ 00854136:0x15d865
client_stdout_wrapper(char const*, unsigned int) @ 00854136:0x7ebb
DOS_WriteFile(unsigned short, unsigned char*, unsigned short*, bool) @ 00854136:0x8321
Program::WriteOut(char const*, ...) @ 00854136:0x13c0e1
DOS_Shell::Run() @ 00854136:0xebc1c
SHELL_Init() @ 00854136:0xed27a
jsdos_main(Config*) @ 00854136:0x14a83d
server_run() @ 00854136:0x14af8d
runRuntime @ 00854136:0x15d8d5
ret.<computed> @ VM193:6214
eval @ VM193:1680
```

All this wasm functions is already in asyncify list, and if I set `-s ASSERTIONS=0` dosbox starting to load.

**Comment by kripken** [comment]
That looks like a real problem that the assertion found. I think it would be worth investigating and fixing if possible. Or maybe you could work around it in `emsc_client_stdout`, make the output be simple ASCII there, for example.

It is just a warning, though - it should not stop the application. But you can remove that line in `UTF8ArrayToString` for local debugging if the message is annoying.

**Comment by caiiiycuk** [comment]
:+1: Thanks!
