### ISSUE TITLE
Finalize produces an invalid metadata JSON - emsdk 2.0.13

### ISSUE THREAD

**Issue by thokra1** [emscripten-core/emscripten#13445]
With the latest version of the **emsdk** on Windows, I reproducibly get "error : emscript: failure to parse metadata output from wasm-emscripten-finalize". While other tickets have described an LLVM/emscripten mismatch as the primary reason for this, the error in my case seems to be pretty clear cut: "json.decoder.JSONDecodeError: Expecting ',' delimiter: line 290 column 62 (char 9485)"

Looking at the JSON, we can see that multiple lines have some double-quotes where there shouldn't be any: 

    "__invoke_void_%class.SkPngCodec*_%struct.SkImageInfo*_%"struct.SkCodec::Options"*_i1",
    "__invoke_void_%"class.std::__2::__vector_base_common"*",
    "__invoke_void_%"class.std::__2::vector.11"*_i8**_i32*",

Please note the extra double quote before `struct.SkCodec::Options`. The first line of this dump is the one mentioned in the above parser error.

Putting this through a JSON linter makes it more obvious. The formated parse yields this for line 290:    
    
    "__invoke_i1_%class.SkPngCodec*_%struct.SkImageInfo*",
    "__invoke_void_%class.SkPngCodec*_%struct.SkImageInfo*_%"
    struct.SkCodec::Options "*_i1",
    "__invoke_%struct.png_struct_def*_i8*_i8*_void(%struct.png_struct_def*.i8*)*_void(%struct.png_struct_def*.i8*)*",

and determines:

    Error: Parse error on line 292:
    ...t.SkImageInfo*_%"		struct.SkCodec::Opti
    ----------------------^
    Expecting 'EOF', '}', ':', ',', ']', got 'undefined'

The last good version seems to be **2.0.6**. With 2.0.7 and up, the dump is slightly different here and there, but the incorrectly generated symbols are the same.

I sadly have no simple test case to reproduce this tho. :(

Any idea what's going on?

**Comment by AnzerWall** [comment]
A beginner's day is consumed with such things. 嘤嘤嘤

**Comment by kripken** [comment]
@thokra1 A good way to narrow this down (since I can think of no explanation for this) is to bisect on `tot` build, see https://emscripten.org/docs/contributing/developers_guide.html#bisecting - that should give us a short changelog.

**Comment by thokra1** [comment]
@kripken I did a little experiment and swapped the 'wasm-emscripten-finalize.exe' from 2.0.7 with the one from 2.0.6 and it worked. 

Intrigued by that, I bisected the binaryen commits relevant to the two SDK versions and found that the offending revision is https://github.com/WebAssembly/binaryen/commit/f4d074fc3ee8184cd89c870612fc316adaeb8e1a . More specifically, the removal of `generator.fixInvokeFunctionNames();` from `wasm-emscripten-finalize.cpp`  and the corresponding support code from `wasm-emscripten.cpp`. 

However, further digging revealed that the inputs to the renaming function were already "corrupt" (i.e. contained the extraneous double-quotes) and the result would be unproblematic, since all names would take the form "invoke_*". So it looks like the code hides a problem further up the pipeline. 

Interestingly, IIUC, the whole renaming thing has been moved directly to LLVM (https://github.com/llvm/llvm-project/commit/3bba91f64eef15956f589fa446c265a714cc7893), so I would expect the finalize stage to already receive names of the form "invoke_*". However, looking at the JSON again, there are no names at all in the `"invokeFuncs" - all functions have been put into the `"declares"` array. Is this intended?

I attached the abbreviated json: [invalid_json_bug13445.txt](https://github.com/emscripten-core/emscripten/files/5951642/invalid_json_bug13445.txt)

**Comment by kripken** [comment]
@thokra1 

Thanks for the info. I remember now, yes, that code has been moved to LLVM basically. And that removes the long names that need escaping, leaving stuff like `invoke_viiiiiii` - a wasm type signature basically (`i` = i32, etc.).

I don't recall which version that was on, but it was probably in the range you are looking at.

What I suspect is going wrong in your project is that you have object files or libraries built with the old compiler, and are linking them with the new one, which can no longer handle them. So a complete rebuild from scratch of your project should fix things.

**Comment by thokra1** [comment]
Thank you @kripken . Makes sense - we precompile Skia and other libraries, so in hindsight, this is not surprising at all. 

I also simply forgot the note regarding binary compatibility from the release notes: "You should also rebuild object files and
libraries in your project when you upgrade emscripten." Maybe it make sense to put this into a more prominent section of the docs, "Building Projects" maybe?

**Comment by kripken** [comment]
Better docs might be helpful here, I agree. Perhaps in the FAQ? if someone has time to write a PR that would be great.
