### ISSUE TITLE
EM_SAVE_DIR demoted to test suite only?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#13458]
Something I've noticed for a long while , but just now realized the intent behind.. there is

```py
# TODO(sbc): Remove this check for the legacy name once its been around for a while.
assert 'EM_SAVE_DIR' not in os.environ, "Please use EMTEST_SAVE_DIR instead of EM_SAVE_DIR"
```

but `EM_SAVE_DIR` is not a testing only option? Developers can use it themselves to debug the toolchain behavior on their own code during development, e.g. to capture .js files before and after an opt pass.

**Comment by sbc100** [comment]
Perhaps you thinking of `EMCC_DEBUG_SAVE`?  I don't think `EM_SAVE_DIR` ever effected anything outside the test suite.

BTW I recently made it so that EMCC_DEBUG implies EMCC_DEBUG_SAVE... I think that makes sense but let me know if you disagree.

**Comment by juj** [comment]
Hmm, I'm fairly certain at some point in time I have run `EM_SAVE_DIR=1 emcc foo.c -o foo.html ...` outside the test suite and captured the results. Not sure if that was `EMCC_DEBUG_SAVE=1` that I had been using instead. :o 

Perhaps my memory is failing, sorry about the noise then!
