### ISSUE TITLE
How to change the module namespace ("env") of a wasm file? 

### ISSUE THREAD

**Issue by liushuaidi** [emscripten-core/emscripten#13462]
When I used emcc to compile a C program to wasm, I found that the default module namespace is "env". Can I customize it? If so, how can I modify the "env"? If not,  can I add my own namespace.

**Comment by sbc100** [comment]
Emscripten has no option to change that default module name (and for that matter nor does llvm).   If you really need to change this I believe the simplest way would be to run some kind of post-processing script (you could decompile and then recompile the wasm file for example and do a sed on the text in between?).
