### ISSUE TITLE
acorn-optimizer taking at times over 20 minutes to finish the task

### ISSUE THREAD

**Issue by kspalaiologos** [emscripten-core/emscripten#13471]
The following command:
```
emcc -std=c++20 -o tau.html lexer.cpp symtab.cpp parser.cpp decl.cpp tau.cpp -O3 -s WASM=1
```
started the following process:
```
/usr/bin/node /usr/share/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_gwg74gkp/tau.js AJSDCE minifyWhitespace
```
... which has been processing the following file: https://b.catgirlsare.sexy/RZRADQm6.js (`tau.js`).
The command has been running for well over 10 minutes before i killed it yesterday, and today I've been running it for well around 20 minutes, without any progress.
Is this intended behavior? How long do i have to wait for this task to finish? Are there any specifics I should share?
![image](https://user-images.githubusercontent.com/27734421/107610703-8205ed80-6c42-11eb-8f1f-04e66dba2be1.png)

**Comment by kripken** [comment]
Odd, on my system I see this:
```
$ /usr/bin/time /usr/bin/node tools/acorn-optimizer.js ~/Downloads/RZRADQm6.js AJSDCE > /dev/null
0.83user 0.05system 0:00.61elapsed 144%CPU (0avgtext+0avgdata 75980maxresident)k
0inputs+0outputs (0major+14560minor)pagefaults 0swaps
```
So it runs in less than a second, and takes reasonable memory as well.

The input file is 181K, which is not huge, and I see nothing odd in it.

That's with node 12.20.1. Perhaps an older or newer version has some pathological behavior?
