### ISSUE TITLE
Dwarf doesnt load source files 

### ISSUE THREAD

**Issue by amarav** [emscripten-core/emscripten#13486]
I'm trying to debug my c++ application usind Dwarf on Chrome Version 89.0.4389.47 (Official Build) beta (64-bit)
But, Unable to see the source files in the Inspect window
Need help to resolve it

This is the option i use
emcc --preload-file rdf_cpp/resources/Resources.tar  -I include -s USE_LIBPNG=1 -s ALLOW_MEMORY_GROWTH=1 -s WASM=1  librendercore.a  main.cpp  rdf_cpp/*.cpp rdf_cpp/scripts/*.cpp -o rendercoreweb.js -o rendercoreweb.html -g -fdebug-compilation-dir=".."

In the console/sources window, i can see only the .html,.js and .wasm file.

Expected:  Source files to debug

**Comment by kripken** [comment]
cc @RReverser @pfaffe

**Comment by RReverser** [comment]
@amarav Sorry to hear it doesn't work. Did you install the extension and enable the flag as per instructions at https://goo.gle/wasm-debugging-with-dwarf?

**Comment by RReverser** [comment]
> I'm trying to debug my c++ application usind Dwarf on Chrome Version 89.0.4389.47 (Official Build) beta (64-bit)

Actually, this is probably the reason - as the instructions say, you need Chrome Canary at the moment. I don't think we're in Beta yet.

**Comment by pfaffe** [comment]
Beta channel should be fine! Did you remember to enable the DWARF Debugging experiment in DevTools? (Gear icon > Experiments)

**Comment by amarav** [comment]
@pfaffe You're right! Missed to enable Dwarf support in DevTools.
Although the source files i built as library are listed, I cant see the cpp files i compiled using emcc like main.cpp. It gives the error

Could not load content for wasm://wasm/main.cpp (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

I'm unable to see the contents of the source files now.

Any inputs to resolve this?

**Comment by amarav** [comment]
![err](https://user-images.githubusercontent.com/5337090/107931073-d215e480-6fa1-11eb-9a73-0857160bacc6.PNG)

I need to debug into main.cpp, rc_platform_fio.cpp etc but couldnt see the contents and got the error

**Comment by pfaffe** [comment]
You're hitting a corner case that we assumed would be quite rare in the wild. We have special treatment for when source files have relative paths in the debug symbols. In that case,  we treat the paths as relative to the base URL.

In your case, that base URL is a wasm:// origin, which are fake URLs assigned by the engine when modules are created from a buffer instead of through the streaming APIs. We generally discourage using the ArrayBuffer APIs for performance reasons.

Besides switching to streaming APIs, here's how you get out of that situation. The [web.dev blog post](https://developers.google.com/web/updates/2020/12/webassembly#path-mapping) briefly talks about remapping source file paths. Path substitutions match prefixes of your source file paths and replace it. For example, you could replace `.` with `file:///c:/foo/bar` to define a new base for relative paths.

**Comment by amarav** [comment]
May I know Where i could do this Path substitution? Is it in devTools? In my case i need to substitute wasm://wasm/ with file:///C:<myentirepath> is it?

**Comment by pfaffe** [comment]
The setting is in the extension's options page. You navigate to `chrome://extensions`, click the extensions `Details` button, and then the `Extension options` link near the bottom of the page.

**Comment by amarav** [comment]
Thanks @pfaffe but doesnt work yet
![err](https://user-images.githubusercontent.com/5337090/107936064-3176f300-6fa8-11eb-909e-4b90a4f846fa.PNG)

**Comment by pfaffe** [comment]
The left-hand side should just read `.`

The substitutions are applied to the (relative) paths that are in the debug symbols, not to the complete URLs that are shown in DevTools. So what you want to do is to replace the `.` in `./main.cpp`.

**Comment by amarav** [comment]
@pfaffe Thanks a ton! File contents load now.

**Comment by zackees** [comment]
Try this, worked for me. It's on none of the official docs

`-ffile-prefix-map=/src=itworked"`

```
debug_compile_flags = [
    "-g3",
    "-gsource-map=inline",
    "-ffile-prefix-map=/js=itworked",
    "-fsanitize=address",
    "-fsanitize=undefined",
    "-fno-inline",
]
```

And by omitting the leading slash it tells the browser to load it from a relative directory:

![Image](https://github.com/user-attachments/assets/52aeb7fd-7c17-4e4a-8619-d3f21a87b93c)
