### ISSUE TITLE
Fetch support for large heaps

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#13480]
Fetch.js (unlike most of the other libraries) does not use the unsigned shift idiom on its pointers returned from the module, so it fails when it tries to read or write data in the heap from JS.

**Comment by kripken** [comment]
I think this is not necessary to fix, as the JS optimizer should rewrite it. The underlying issue should be fixed by https://github.com/emscripten-core/emscripten/pull/13481
