### ISSUE TITLE
Is link_bitcode() needed anymore?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#13492]
In https://github.com/emscripten-core/emscripten/blob/e2773bbeaa40847e5dda9e5aeddc83659b3b3234/tools/building.py#L453 we call out to a `link_bitcode()` function. The comment there suggests that this is (only?) needed as a workaround a wasm-ld issue. 

However given the link in the comment, https://bugs.llvm.org/show_bug.cgi?id=40654, suggests that this has been fixed? Would we be able to nuke the whole `link_bitcode()` function after the issue has long been fixed?

When I run `wasm0` and `other` test suites with this change

```
def link_to_object(linker_inputs, target):
  link_lld(linker_inputs + ['--relocatable'], target)
```

I don't see anything breaking (that wasn't broken already).

**Comment by juj** [comment]
In PR #13493 I removed the code for link_bitcode(), and I don't see anything (reproducibly) failing, so maybe that linking path is no longer needed. PR #13493 deletes it and the associated code.

**Comment by sbc100** [comment]
Sadly we do still have at least one major user who wants to be able to run `emcc -r obj1.o obj2.o -o obj3.o` to combine multiple LTO/bitcode files into one.

The reason they need to do this is that they have a whole-program bitcode operation they do on their final binary.  We probably can't remove this until we switch them over to the binaryen-implemented version of this tool (basically wasm-split).

There may be other users too, we should ask on the mailing list now to get ahead it so we can move forward with this removal once we transition this once major user.
