### ISSUE TITLE
Uncaught (in promise) TypeError: wasmTable.get(...) is not a function

### ISSUE THREAD

**Issue by arpita1098** [emscripten-core/emscripten#13502]
I am trying to build my C++ project as the following toolkit as SIDE_MODULE=1, test libraries as static as ( dynamic didn't work ), then the test app as MAIN_MODULE =1;

But I keep getting this error

Uncaught TypeError: wasmTable.get(...) is not a function
    at invoke_v (TestXMPCoreAPI.js:72603)
    at _ZN7XMPMeta15ParseFromBufferEPKcmm (<anonymous>:wasm-function[2970]:0x2350a7)
    at invoke_viiii (TestXMPCoreAPI.js:72559)
    at WXMPMeta_ParseFromBuffer_1 (<anonymous>:wasm-function[362]:0x191658)
    at _WXMPMeta_ParseFromBuffer_1 (TestXMPCoreAPI.js:2613)
    at _ZN8TXMPMetaINSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEE15ParseFromBufferEPKcmm (<anonymous>:wasm-function[4149]:0x243529)
    at invoke_viiii (TestXMPCoreAPI.js:72559)
    at _ZN10bug04359515test1Ev (<anonymous>:wasm-function[7329]:0x2d42bf)
    at _ZN7CppUnit10TestCallerI10bug0435951E7runTestEv (<anonymous>:wasm-function[7500]:0x2db55e)
    at _ZNK7CppUnit21TestCaseMethodFunctorclEv (<anonymous>:wasm-function[12018]:0x3b782d)

**Comment by sbc100** [comment]
When you build with MAIN_MODULE=1 the resulting JS file should define a wasmTable variable.   Are you using the emscripten-generated JS file?   Do you not see a line that looks like `var wasmTable = new WebAssembly.Table...` in the generated JS file?

By the way if you can build your toolkit as a  static library too that might make your life simpler.  Using SIDE_MODULE/MAIN_MODULE adds a bunch of complexity that size overhead that is best avoided unless you really need it.   Fully static builds are a lot simpler with emscripten.

**Comment by arpita1098** [comment]
So, this is how my whole setup is 

for building side module A ( libraries toolkit)
set_target_properties(${TARGET_NAME} PROPERTIES LINK_FLAGS "-s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s SIDE_MODULE=1 -s EXPORT_ALL=1 -fPIC")

this always generated a .js file. So to make the compiler generate .wasm file, I did as 
 set(CMAKE_EXECUTABLE_SUFFIX ".wasm") 
set_target_properties(${TARGET_NAME} PROPERTIES LINK_FLAGS "-s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s SIDE_MODULE=1 -s EXPORT_ALL=1 -fPIC")

same for side_module B (test libraries toolkit)
 Now comes the main_module
 set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS " -s EXTRA_EXPORTED_RUNTIME_METHODS='[\"ccall\"]' -s EXPORTED_FUNCTIONS='[\"_runTest_web\", \"_main\"]' -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 -s DISABLE_EXCEPTION_CATCHING=0 -s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s MAIN_MODULE=1 -lidbfs.js")
 
 this I get the required files.
 Now in the generated .js file, i pass Module['dynamicLibraries] = ['sideModuleA.wasm', 'sideModuleB.wasm]; then run it on my local host, upon which i get the error


evn on tryinng. Module['dynamicLibraries] = ['MainModule.wasm"];, i receive the same error.

**Comment by arpita1098** [comment]
Now when I fix that by adding '_main' to EXPORTED_FUNCTIONS. That issue was maybe happening as not adding main() was causing it to consider as dead code() & eliminate it on dynamic initialisation. That's where I call all my test cases from.
I get this : 
Uncaught (in promise) RuntimeError: abort(Assertion failed: Missing signature argument to addFunction: function _system(command

**Comment by sbc100** [comment]
So the original issue is now fixed?

The `Missing signature argument to addFunction` is a different issue.  We need to a `__sig` to system function in `src/library.js` in order to make its address available in dynamic linking.  While we should add it, you might also want to take a look what code is taking the address of the `system` function.   This function is something that doesn't work at all, at least not on the web, so references too it could be sign that you can remove some of your code.

I think the fix is to add `system__sig: ['ii'],` to `src/library.js`.    It may be that you find more JS symbols that also need signatures added once you fix that one.

**Comment by arpita1098** [comment]
in my project main.cpp, we have a function x(), that calls main() when running for wasm.
as in 
x()
{
main()
}
when I set EXPORTED_FUNCTIONS= [x], it somehow never called main(), may be the main got eliminated as dead-code to optimise during dynamic-linking
i have attached the screennshot here Pic A
<img width="1152" alt="pic A" src="https://user-images.githubusercontent.com/22683597/108109930-94f04600-70b8-11eb-9d49-45df5be8da49.png">


then after adding in EXPORTED_FUNCTIONS = [x,main], it does call x() and main(), but again doesnt call functions called inside main()  Please refer Pic 2
<img width="970" alt="pic 2" src="https://user-images.githubusercontent.com/22683597/108109986-a8031600-70b8-11eb-9743-ec0058a06a2e.png">

please also read my 2nd comment where I've mentioned that the emcc compiler was emitting  toolkit.js file for SIDE_MODULE =1, but after using set(CMAKE_EXECUTABLE_SUFFIX ".wasm") it emitted toolkit.wasm

Is this a leit way? Things are getting quite tricky in dynamic linking.

**Comment by sbc100** [comment]
Firstly, if you build with `-s MAIN_MODULE=1` then specifying `EXPORTED_FUNCTIONS` should not be necessary since all functions will be exported by default in this mode.

Secondly, I assume when you say `EXPORTED_FUNCTIONS=[x]` you actually mean `EXPORTED_FUNCTIONS= [_x]`?   

Thirdly, calling main from anther function is probably not a good idea.   I'm not actually sure its valid to do this in C/C++ (even if it works).

Regarding `SIDE_MODULE=1`, yes you should always set the output to `.wasm` in this case as side modules don't have any JS code.   When you don't set the output name of the `.wasm` are you sure you are not actually getting a files called `.js` that actually is a wasm binary.  When I try it this is what I see:

```
$ emcc ~/test/hello.c -s SIDE_MODULE -o out.js
$ file out.js
```

So it not really a JS file at all, its just the cmake is setting the output name of `.js` by default so I guess you are right to override it.   Perhaps we should not have cmake set CMAKE_EXECUTABLE_SUFFIX at all?

**Comment by sbc100** [comment]
Also you can remove `-s WASM=1` and `-s EXPORT_ALL=1` since those are the defaults in this case.

Also, you can remove `ERROR_ON_UNDEFINED_SYMBOLS=0` since missing symbols are not reported in the MAIN_MODULE/SIDE_MODULE use case.

**Comment by arpita1098** [comment]
Thank you for being very generous & answering my queries!!

- yes I pass it as EXPORTED_FUNCTIONS=[_x]

- actually that x() function is nothing but declaring a function under  "extern C" as that's how we can run wasm, so I have made my code as such that it can also work without wasm like running on Xcode, VS, etc. Like main.cpp has
main() {  //code}

extern C
x(){ //if/else condition(s) 
      main(). ----->calling it
}

I did the changes as you have mentioned and removed those extra flags. 
with EXPORTED_FUNCTION=[_x], i get TypeError: wasmTable.get(...) is not a function as mentioned in pic 1

with EXPORTED_FUNCTION=[_x,_main] i received Uncaught (in promise) RuntimeError: abort(Assertion failed: Missing signature argument to addFunction: function _system(command) as mentioned in pic 2

Tried both Module['dynamic libraries'] = ['toolkit.wasm', 'test_librraies.wasm']  & Module['dynamic libraries'] = ['toolkit.js', 'test_librraies.js'] 

Am I doing something wrong or missing out on something? Are the modules not getting linked correctly?

**Comment by sbc100** [comment]
As I mentioned earlier, to solve the later problem you need at a `__sig` entry for the `_system` JS library function.

If you want to solve the former problem you would need to take a look at the generated JS and see why wasmTable is not being declared (it should be in all cases I believe so its a little strange).

**Comment by arpita1098** [comment]
Hi, we are able to build one library as a side module, then the main.cpp as main_module. 
Is it possible to build two libraries as side modules where library B is dependent on A and then main.cpp as main_module?

**Comment by sbc100** [comment]
> Hi, we are able to build one library as a side module, then the main.cpp as main_module.
> Is it possible to build two libraries as side modules where library B is dependent on A and then main.cpp as main_module?

You can compile as many modules as you like.   There are not really dependencies as such, you just need to load each of your libraries at startup by adding them to the `RUNTIME_LINKED_LIBS` command line setting e.g. `-s RUNTIME_LINKED_LIBS=[lib1.wasm,lib2.wasm]`.

**Comment by arpita1098** [comment]
I tried building Library B which is dependent on Libary A with flags -s WASM=1 -s SIDE_MODULE=1 -s RUNTIME_LINKED_LIBS=[libA.wasm] -s EXPORT_ALL=1 -fPIC" . I got libB.wasm as output, as per expected behaviour)

Then built my main.cpp with  "-s ALLOW_MEMORY_GROWTH=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='[\"ccall\"]' -s EXPORTED_FUNCTIONS='[\"_runTest_web\"]' -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 -s DISABLE_EXCEPTION_CATCHING=0 -s MAIN_MODULE=1 "

then in the main.js passed Module['dynamicLibraries] = ['libA.wasm', 'libB.wasm']
somehow i receive a runtime error :
 abort(Assertion failed: missing linked function `[X]`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment 
 
 Here [X] is synonymous to an internal function(keeping anonymous). But this error suggests that main.js has no side module linked, but thats no true. Right?

**Comment by sbc100** [comment]
Can you see if `'libA.wasm` and `libB.wasm` are both being loaded?    Can you verify that `X` exists as an export from either `libA.wasm` or `libB.wasm`?       

Do you know where the undefined `X` is coming from?  Is it from the main module or from one of the side modules?

Perhaps you could reduce this it a test case can we can we use to open a new bug and fix that issue.  In any case it seems like a seperate issue to this one (Uncaught (in promise) TypeError: wasmTable.get(...) is not a function) so maybe we can close this an open a new one to discuess furthur?

**Comment by arpita1098** [comment]
Thanks for the support! I'm closing this issue for now.
