### ISSUE TITLE
Reserved memory space

### ISSUE THREAD

**Issue by AGreat1** [emscripten-core/emscripten#13518]
Hi all, a newbie here!

On a project I'm working on, we plan to have a plugin system using wasm. This will have a completely custom runtime environment - no web and no wasi. I understand compiling standalone is the key here, but I have one additional problem: passing structs from the runtime to the plugin.

My understanding - based on reading AssemblyScript docs at least - is to have a memory space that is reserved, hence the runtime can write without worrying about writing over plugin intenal values. (with AS they have the memoryBase option) How can I accomplish the same with Emscripten? I was eyeing GLOBAL_BASE, but starting from 1024b it will be used for optimisation... Is there any way to achieve this in my distilled environment? without a _malloc call? Maybe after the heap of that is of fixed size? How would I know of its size then?

**Comment by sbc100** [comment]
Setting `-s GLOBAL_BASE` to something higher than 1024 could work yes.   The plugin won't use memory below GLOBAL_BASE for stack, heap or static data.

Alternatively you can include an extra source file in your plugin that allocates the data as part of the static region:

```
char data_region[1024];
```

And then add `_data_region` to EXPORTED_FUNCTIONS (yes I know its not a function, it should really be called EXPORTED_SYMBOLS). 

The the module will export an wasm global called `data_region` that will be the address of the memory and you can use that for whatever you want.

Another way (perhaps the ideal way) would probably be to use the stack itself.   Emscripten-build modules export stackAlloc, stackSave and stackRestore which allow you to put things on the stack and take them off again.   Looks for stackAlloc in the src directory for how JavaScript uses them.

**Comment by AGreat1** [comment]
Thanks for your input! I think my question stemmed from a misunderstanding of what the binaryen const optimization does. I thought it would write to memory before the global base, but I guess it doesn't.
