### ISSUE TITLE
Unable to build glbook examples

### ISSUE THREAD

**Issue by vyorkin** [emscripten-core/emscripten#13517]
Hello! I'm trying to build the examples in `tests/glbook`.
I have installed the `libgle-dev` and `libgles-dev` which I can confirm by running:

```sh
 △ emscripten/tests/glbook ldconfig -p | grep libEGL                                                                      
        libEGL_nvidia.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
        libEGL_nvidia.so.0 (libc6) => /lib/i386-linux-gnu/libEGL_nvidia.so.0
        libEGL_mesa.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL_mesa.so.0
        libEGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so.1
        libEGL.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so

 ▲ emscripten/tests/glbook ldconfig -p | grep libGLESv2         
        libGLESv2_nvidia.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2
        libGLESv2_nvidia.so.2 (libc6) => /lib/i386-linux-gnu/libGLESv2_nvidia.so.2
        libGLESv2.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLESv2.so.2
        libGLESv2.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLESv2.so
```
But when I ran `make` I get the linking error:

```sh
▲ emscripten/tests/glbook make  

cc Common/esShader.c Common/esTransform.c Common/esShapes.c Common/esUtil.c Chapter_2/Hello_Triangle/Hello_Triangle.c -r -o Chapter_2/Hello_Triangle/CH02_HelloTriangle.o -I./Common -lGLESv2 -lEGL -lm -lX11
/usr/bin/ld: cannot find -lGLESv2
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
make: *** [Makefile:40: Chapter_2/Hello_Triangle/CH02_HelloTriangle.o] Error 1

```

**Comment by sbc100** [comment]
That Makefile is not really designed to build that native version of those tools... but still it should work.   These are designed to be build with with emscripten (they are tests of emscripten).   If you want to build with emscripten you would run `emmake make`

The problem maybe related to the `-r` flag.   If you add `-v` to the cc command line you should be able to see what linker command is running.    Perhaps in `-r` mode you are not supposed to be able to reference system libraries?

The use of `-r` here is a little odd.. I think its a quirk of how we use to build a lot of stuff to bitcode before doing the final link.
