### ISSUE TITLE
Wasm EH: "Branch destination should be in scope" error

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#13515]
```
clang++: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyCFGStackify.cpp:1518: unsigned int (anonymous namespace)::WebAssemblyCFGStackify::getBranchDepth(const SmallVectorImpl<(anonymous namespace)::WebAssemblyCFGStackify::EndMarkerInfo> &, const llvm::MachineBasicBlock *): Assertion `Depth < Stack.size() && "Branch destination should be in scope"' failed.
```
```cpp
#include <stdio.h> // avoid iostream C++ code, just test libc++abi, not libc++
#include <stdint.h>

extern void refuel();
extern void checkRecursion();
extern bool getBoolean();

void func_0() {
  if (getBoolean()) {
    try {
      throw 0;
    } catch(...) {
    }
  }
  try {
    if (getBoolean()) {
      try {
        puts("log(1)");
      } catch(...) {
      }
    }
  } catch(...) {
  }
}

int main() {
  // func_0
  puts("calling func_0");
  refuel();
  try {
    func_0();
  } catch(...) {
    puts("main caught from func_0");
  }
  return 0;
}
```
STR: `emcc a.cpp -c -fwasm-exceptions`

Found by https://github.com/emscripten-core/emscripten/pull/13485

cc @aheejin @dschuff

**Comment by kripken** [comment]
A smaller testcase:
```cpp
extern bool getBoolean();

struct Class {
  ~Class();
};

int main() {
  if (getBoolean()) {
    try {
      throw 0;
    } catch(int) {
    }
  }
  Class instance1;
  if (getBoolean()) {
  }
  while (getBoolean()) {
  }
}
```

**Comment by dschuff** [comment]
@aheejin I know you are currently working on #13514 (which I agree is best since that's the one we saw in real code). Do you have a sense for whether this is likely to be an independent bug from that?  To me it looks like both of these result from control flow destinations not being in the stack, and a change to the grouping algorithm is likely to affect both of those (so in other words, my guess would be that it's not worth trying to investigate fixing this separately from a fix to #13514. does that sound right to you?)

**Comment by aheejin** [comment]
Sorry, I had to investigate this in order to find out whether it is independent or not, and it is independent. But also while investigating this I think I found out the cause for this bug too. So not sure if it is advisable to ask you to fix this separately.

**Comment by dschuff** [comment]
OK yeah, if your tentative fix for #13514 works out, then it probably makes sense for you to pick this one up too.

**Comment by dschuff** [comment]
btw If you want to upload something to phabricator I'd be happy to throw some testing at it too.

**Comment by kripken** [comment]
This appears to still happen after the fix landed, on other testcases. A reduced one:

```cpp
extern bool getBoolean();

struct Class {
  Class();
  ~Class();
};

int main() {
  if (getBoolean()) {
    try {
      throw 0;
    } catch (int) {
    }
    try {
      if (getBoolean()) {
      }
      throw 0;
    } catch (int) {
    }
  }
  Class instance1;
  try {
    getBoolean();
  } catch (int) {
  }
  getBoolean();
}
```

STR: `./em++ a.cpp -c -fwasm-exceptions` on https://github.com/emscripten-core/emscripten/pull/13485 (tot: `0fcee855ada6358c4fe6e8c2a7f291c54cde4876`).
