### ISSUE TITLE
test_exceptions_rethrow_missing has the wrong output expectation for wasm exceptions

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#13527]
I believe [test_exceptions_rethrow_missing](https://github.com/emscripten-core/emscripten/blob/2c16a02cdda7685b0d246ca99c363072b9411a2a/tests/test_core.py#L1435) has the wrong output expectation for wasm exceptions.
The text "no exception to throw" comes from the [JS implementation](https://github.com/emscripten-core/emscripten/blob/8e885f7b616d847c1d806b815da0e6914fd4df2a/src/library_exceptions.js#L262) of `__cxa_throw`, but of course wasm-eh uses the functions from libcxxabi instead.

When a there's a bad rethrow, libcxxabi calls `std::terminate` and then `demangling_terminate_handler`, which diagnoses uncaught exceptions and prints an error with `abort_message` (if the problem is not an uncaught exception it just prints "terminating"). But emscripten defines `abort_message` away as just a [trap](https://github.com/emscripten-core/emscripten/blob/9bb322f8a7ee89d6ac67e828b9c7a7022ddf8de2/system/lib/libcxxabi/src/abort_message.cpp#L38) (It has an `NDEBUG` check, but it appears that we link an NDEBUG libcxxabi even with debug builds currently).

Either way though, we should probably either remove the test's output expectation or make it different for wasm-exceptions builds.

We should also maybe consider fixing `abort_message` so that it prints something even in non-debug builds. 

This is probably low priority though, since it won't effect common situations found in the wild. And it doesn't represent a bug in LLVM or Binaryen.

**Comment by kripken** [comment]
Good catch. I propose we just remove the expectation, so the test just verifies an error code is set, https://github.com/emscripten-core/emscripten/pull/13529

I think the reason we made `abort_message` into a trap is that it appears in lots of places, and anything but a trap led to larger code sizes. The change to a trap was a pretty big win. In a debug build perhaps we should include some text, though, I agree. (For that we'd need to add a debug variant I guess.)

**Comment by aheejin** [comment]
Yeah this test was added in Dec 2020, after I tested the spec's wasm EH with Emscripten test suite in earlier that year. I agree just not checking the error message is a way to go.

**Comment by dschuff** [comment]
Was the code size savings (from making `abort_message` just a trap) just from avoiding the need to link printf formatters into code that otherwise wouldn't have it?

**Comment by kripken** [comment]
@dschuff I believe that was the largest factor, yes. I can re-run the numbers if you want?

**Comment by dschuff** [comment]
Not sure it's important enough to do right now. A quick search of emscripten shows only a few uses of `abort_message` in libcxx/libcxxabi code, so maybe at some point we can consider how valuable having those error messages would be, vs the cost. We could think about using `iprintf` or just `puts` instead to reduce size, or tune it for a particular case. Just from what I saw, the most useful one looks like the one that checks for uncaught exceptions in `demangling_terminate_handler` but it's not obvious to me that it would even end up being called when there are unhandled exceptions (it seems more likely that it would just end up propagating out to JS).
