### ISSUE TITLE
-g4 should be either removed or produce DWARF data like -g3

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#13534]
I know of at least two users now who were confused by `-g4` not producing DWARF data and seeing `$var0`-like variable names in DevTools.

It's currently documented as "The -g4 option provides the most debug information", however this is not true anymore: we produce only DWARF data with `-g3` and only source map data with `-g4`, making those options do very different things.

I think we should either:

1. Deprecate source map support altogether.
2. Keep it as-is to support browsers without DWARF support, and make `-g4` produce DWARF _in addition_ to source maps to cover everything.
3. Remove `-g4` and move source map generation to a separate opt-in flag.

**Comment by sbc100** [comment]
I vote for (3).

**Comment by sbc100** [comment]
Perhaps the opt-in flag can be `-gsource-map` to keep in the `-g` family.

**Comment by pfaffe** [comment]
Ultimately I think deprecating source maps is the right path forward, but people are used to it by now. Option 3 could be a "soft" step into that direction however. It moves it out of the way so people don't get confused by it, and we can deprecate the new source map option at any point in the future 

So +1 to option 3. I also like the `-gsource-map` flag!

**Comment by kripken** [comment]
I agree with all the above, (3) with @sbc100 's proposed alternative sgtm.

**Comment by RReverser** [comment]
@kripken I'm not sure which alternative you mean?

**Comment by kripken** [comment]
I meant option (3), like @sbc100 and @pfaffe (`Remove -g4 and move source map generation to a separate opt-in flag.`) and with @sbc100 idea of `-gsource-map`.

**Comment by RReverser** [comment]
Ah, sgtm.
