### ISSUE TITLE
test_proxy_to_pthread_stack is flaky on windows

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#13567]
Most of the time it passes, but occasionally fails.
Example: https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket.appspot.com/8854302553290478880/+/steps/Emscripten_testsuite__upstream__other_/0/stdout
(although i don't see any output from the test in there).

@sbc100 suggested that it could be related to the order of arrival of the `EM_ASM` and the shutdown messages.

**Comment by sbc100** [comment]
While working on another change I've noticed this is also flaky on linux
