### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles"

### ISSUE THREAD

**Issue by LukasKPetersen** [emscripten-core/emscripten#13587]
Hi, I'm having some problems with building with CMake, and I'm hoping to find some help!

I'm quite confident that I've installed CMake properly and applied it to the path as well. The error I get looks like this:

```
CMake Error at /Users/Shared/EpicGames/ue4-4.24.3-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'/Users/Shared/EpicGames/ue4-4.24.3-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/emscripten/emcc'
  -v"! Process returned with error code 1.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:4 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```

I'm working on macOS Big Sur 11.2 and CMake version 3.20.0-rc2. I've tried to look through the files noted in the error-message, but I don't see any problems anywhere. I might overlook something though, since I'm a relative beginner - especially when it comes to CMake.

Is this making sense? Is there a fix?

Thanks in advance

/Lukas

**Comment by midzer** [comment]
This might be related to https://github.com/emscripten-core/emscripten/issues/9669#issuecomment-1027138020

**Comment by sbc100** [comment]
What does running `/Users/Shared/EpicGames/ue4-4.24.3-html5/Engine/Platforms/HTML5/Build/emsdk/emsdk-1.39.18/upstream/emscripten/emcc -v` yourself say?

The second error looks like its because you don't have `make` in your path.   When using cmake you need to use to an underlying build system (in this it looks like you are using `Unix Makefiles` AKA make).  You can fix this by installing (somehow) make, or better still install ninja and use `-G Ninja`.

**Comment by sbc100** [comment]
Does this issue still exist for you?

**Comment by midzer** [comment]
Thanks for bumping @sbc100 
I will have a look at this next week.

**Comment by LukasKPetersen** [comment]
Thanks for your help guys! Unfortunately I dropped the project as I realized that it didn't work in practice. I wanted to make a small game to stream on a website but I had to either (a) make it small enough to be embedded in the htm or (b) have a machine running the game 24/7. None of these options seemed attractive so I dumped the project.

**Comment by LukasKPetersen** [comment]
Thanks for your help guys! Unfortunately I dropped the project as I realized that it didn't work in practice. I wanted to make a small game to stream on a website but I had to either (a) make it small enough to be embedded in the htm or (b) have a machine running the game 24/7. None of these options seemed attractive so I dumped the project.
