### ISSUE TITLE
Problems upgrading from emscripten 1.x.x to 2.0.14

### ISSUE THREAD

**Issue by johnwason** [emscripten-core/emscripten#13607]
I am updating to the new version of Pyodide which uses emscripten 2.0.14, and am having trouble building my C++ module. As discussed in https://github.com/emscripten-core/emscripten/issues/9691, I am statically linking my module into the main module to avoid the "C++ exception not caught" bug. When compiling with the previous 1.x.x versions, I haven't had any issue building and using the module. With the updated version, I am having problems loading the module.

The first problem I had was that boost was saying that the generated *.bc lbraries were an unknown format. I was able to fix this my modifying emscripten.jam to change:

    type.set-generated-target-suffix OBJ : <toolset>emscripten : "bc" ;

to

    type.set-generated-target-suffix OBJ : <toolset>emscripten : "o" ;

and

    "$(CONFIG_COMMAND)" $(AROPTIONS) -o "$(<)" "$(>)"

to

    "$(CONFIG_COMMAND)" $(AROPTIONS) -r -o "$(<)" "$(>)"

This stopped the compiler erorr.

Next, I got the error "cannot convert XXXXXX integer to BigInt" when I enabled exceptions with `-O2` set. I was able to work around this by setting `-O1`.

After this, I got the error "Too many exports". I have no idea how to deal with this problem.

For troubleshooting, I tried removing the Python module source and building just the core libraries and boost. I got the error: 

    Uncaught (in promise) RuntimeError: abort(Assertion failed: Missing signature argument to addFunction: 
    function _emscripten_clear_timeout(id) {
      clearTimeout(id);
    }) at jsStackTrace@http://192.168.1.133:8000/pyodide.asm.js:3138:19

At this point I am stuck. I've pushed my current work here:

https://github.com/johnwason/pyodide/tree/robotraconteur_pyodide_emscripten2x

https://github.com/johnwason/robotraconteur_pyodide/tree/emscripten2x

The repos are currently at the troubleshooting step of removing the SWIG Python module.

The working repository using the older Emscripten and Pyodide version is here:

    https://github.com/robotraconteur/robotraconteur_pyodide

The patch file for Pyodide to statically link in this code is here:

    https://github.com/robotraconteur/robotraconteur_pyodide/blob/pyodide/pyodide_patch.diff

I am building both Pyodide and the extension module in the provided Pyodide docker.

What should I do next to fix these issues?

**Comment by sbc100** [comment]
To fix the `Missing signature argument to addFunction` error we need to add a `__sig` to `emscripten_clear_timeout` in src/library_html5.js.   That should be easy enough but there may be more that need to be added to.  This is an unfortunate consequence of #12461.

Regarding the "Too many exports" I'm not sure where that is coming from I don't see that error in emscripten or in binaryen so I guess its coming from the engine.   Do you know how many exports you have?   One way to generate a huge number of exports is to build with `MAIN_MODULE=1` (as opposed to MAIN_MODULE=2 or 0 which is the default).   If you are hitting some kind of engine limit on exports you might want to try removing `MAIN_MODULE=1` if you can.  This could also save you a huge amount on code size (and therefore load time too).

**Comment by johnwason** [comment]
@sbc100 

Thanks, I will look over #12461

Pyodide makes heavy use of dynamic loading so I cannot disable it.

For the number of exports, I do not know, but it is probably a huge number. I am using Pyodide which has the complete Python runtime, several boost libraries, my library, and a SWIG wrapper. The current Pyodide build script uses EXPORT_ALL=1, so I assume it is exporting everything. Here is the location of the main linker step:

https://github.com/johnwason/pyodide/blob/59accadeb0b639914ef9510a724c1603bebe2874/Makefile#L69

Flags are set here:

https://github.com/johnwason/pyodide/blob/59accadeb0b639914ef9510a724c1603bebe2874/Makefile#L26

It is unclear if EXPORT_ALL is needed for using dynamic linking?

**Comment by sbc100** [comment]
The name of the `EXPORT_ALL` can be a little misleading.  Check out the docs on it in settings.js.    I don't think it will efect the numbero of exports from a wasm module.   It  is `MAIN_MODULE=1` that causes the number of exports on the wasm module to explode (since it means "include everything and don't DCE anything"!).

I'm not sure where the "Too many exports" error is coming from or who is generating it.  Do you have any more info on that?  Assuming its talking about exports from wasm than `EXPORT_ALL` is not the problem.   If its talking about exports from the JS module object then it could be. 

In any case I doubt you need `EXPORT_ALL`.. but it probably won't solve your issue to remove it either.

**Comment by johnwason** [comment]
How is emscripten defining visibility? Is there a flag I should be passing to Boost or my libraries to make their symbols hidden?

**Comment by sbc100** [comment]
Good question, I had assumed that we honored `__attribute__((visibility("hidden")))` as normal when building `MAIN_MODULE` and `SIDE_MODULE` but a quick test shows that we currently do not.

**Comment by johnwason** [comment]
For the moment I am going to downgrade to the latest Pyodide release that uses the older 1.x.x emscripten versions, and wait to upgrade until Emscripten fixes these issues. I'll create a github action that reproduces my build process for troubleshooting when I have some free time.

@sbc100 Thanks for the quick response

**Comment by johnwason** [comment]
I was able to upgrade to Pyodide commit a4fad9b which, was the last commit before the changed to Emscripten 2.0.x. The patch file for Pyodide is here:

https://github.com/robotraconteur/robotraconteur_pyodide/blob/pyodide/pyodide_patch.diff

**Comment by rth** [comment]
> The patch file for Pyodide is here:

@johnwason  Could you please open an issue at pyodide about this? In particular a PR to improve the exception handling in the WebLoop (included in your diff) would be great.

> The first problem I had was that boost was saying that the generated *.bc lbraries were an unknown format.

You would likely just need to replace all .bc by .o in your build script.

**Comment by johnwason** [comment]
@rth I will create PRs and patches once I am past a few upcoming deadlines that are taking most of my time

**Comment by johnwason** [comment]
@sbc100 and @rth I am finally getting back to looking at these issues. Has there been any progress I should be aware of?

**Comment by sbc100** [comment]
I've been making improvement to the dynamic linking system, but mostly around making `MAIN_MODULE=2` work better and export exactly the symbols needs by the side modules.

**Comment by sbc100** [comment]
I'm not aware of exactly what the issues are here I'm afraid.

**Comment by johnwason** [comment]
@sbc100 I am working to integrate a relatively complicated Python module written in C++ that uses Boost and C++ exceptions into Pyodide. I will try again this weekend and see if I can get it to work with the current 2.0.15 emscripten version.

**Comment by johnwason** [comment]
Everything is working with Emscripten 3.10.2. Great work!
