### ISSUE TITLE
--export not found error while build with 2.0.15

### ISSUE THREAD

**Issue by lazygyu** [emscripten-core/emscripten#13619]
I tried to build my project with emsdk 2.0.15 and got these:

```
wasm-ld: error: symbol exported via --export not found: __stop_em_asm
wasm-ld: error: symbol exported via --export not found: __start_em_asm
```

This project used to build successfully with 2.0.13.

**Comment by sbc100** [comment]
I guess you must be building with some kind a flag that enabled these errors since I don't believe these will generate errors by default.  Are you building with LLD_REPORT_UNDEFINED perhaps?

**Comment by ragingwind** [comment]
@lazygyu  Removing LLD_REPORT_UNDEFINED would work for this

**Comment by lazygyu** [comment]
Thanks!
