### ISSUE TITLE
EM_ASM + SIDE_MODULE=2 - error in wasm-emscripten-finalize

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#13644]
EM_ASM statements in side modules do not compile when dce is enabled:

```C++
#include <emscripten.h>
EMSCRIPTEN_KEEPALIVE void call_em_asm() {
    EM_ASM({ out("no args works"); });
}
```
Compiling with `emcc -s SIDE_MODULE=2 -o side.wasm  side.cpp`:
`Fatal: Unexpected arg0 type ((i32.atomic.load offset=29579328 align=29579224
 unexpected expression type
UNREACHABLE executed at /b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/wasm-traversal.h:68!
`

Note: EM_JS compiles fine so I'm using EM_JS for now. If possible an error message with more context information would be highly appreciated.

**Comment by sbc100** [comment]
I don't think either EM_JS or EM_ASM will work in a side module because they both require the JS strings to injected into the main JS file.. (and when you build with SIDE_MODULE there is no JS file generated).

Are you use EM_JS is actually working?

**Comment by sbc100** [comment]
I think the error you are seeing might be mismatch between the emscripten version and the binaryen version that you are using.

When I build the above example I don't see any error:

```./emcc -sSIDE_MODULE test.cc -O2
$ ./emcc -sSIDE_MODULE test.cc -O2
```

Are you using emsdk to install your tools?

**Comment by gl84** [comment]
I'm using emsdk to install emscripten.

It seems the error is produced only for SIDE_MODULE=2 and O0...

Thanks for the hint that it could be impossible to work in principle!

**Comment by gl84** [comment]
You're right, it doesn't work without the needed JS code in the main module.

**Comment by sbc100** [comment]
#13649 makes using EM_ASM or EM_JS in a side module into and error.

The code in binaryen then generated the error you saw is being completely removed in https://github.com/WebAssembly/binaryen/pull/3685.
