### ISSUE TITLE
Parallel GL program linking is impossible

### ISSUE THREAD

**Issue by stevenlr** [emscripten-core/emscripten#13650]
The [call to `populateUniformTable` inside `glLinkProgram`](https://github.com/emscripten-core/emscripten/blob/1c7484cd8f937eda5449eebfcfde8dfb3524ad2d/src/library_webgl.js#L3134) forces shader linking to complete, and prevents any attempt at parallelizing shader compilation & program linking. (See https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#compile_shaders_and_link_programs_in_parallel)

A better way of caching uniform locations would be when calling `glGetUniformLocation` for the first time, or maybe just letting the API user deal with that.

**Comment by juj** [comment]
This is something I've intended to refactor for a while, but haven't been able to get to it. There is another change upcoming for this area to add support for https://www.khronos.org/opengl/wiki/Uniform_(GLSL)/Explicit_Uniform_Location , maybe we can manage these both at the same time.

**Comment by juj** [comment]
Btw this issue is unrelated to taking glCompileShader vs glLinkProgram wide, that is already possible. But the practice of following sample code in https://www.khronos.org/registry/webgl/extensions/KHR_parallel_shader_compile/ what is unable to be done here.
