### ISSUE TITLE
PROXYFS is not documented

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emscripten#13660]
The documentation page about supported file systems (https://emscripten.org/docs/api_reference/Filesystem-API.html) mentions the existence of 4 file systems: 

 - NODEFS
 - IDBFS
 - WORKERFS
 - PROXYFS

The first 3 are documented, but not the last one. What is PROXYFS and what does it do ? Could a few sentences be added to the docs about it ?

**Comment by sbc100** [comment]
Good idea.  If you have some time perhaps you could send a PR, otherwise marking as "help wanted" so somebody will hopefully pick it up.

**Comment by kripken** [comment]
Fixed by #14668
