### ISSUE TITLE
C++ function returns incorrect value if it calls a JS function wrapped in Asyncify.handlerAsync

### ISSUE THREAD

**Issue by gwutama** [emscripten-core/emscripten#13677]
I'm trying to get a value returned from a C++ function, which calls a JS function declared with EM_JS and wrapped with Asyncify.handlerAsync.

The code below reproduces the issue:

```
// asyncify_return.cpp
#include <string>
#include <iostream>
#include <emscripten.h>
#include <emscripten/bind.h>

EM_JS(void, bar, (), {
  Asyncify.handleAsync(async () => {
    const cache = await caches.open('test123');
    console.log("BAR");
  });
});


int foo()
{
  std::cout << "FOO" << std::endl;
  bar();
  return 42; 
}


EMSCRIPTEN_BINDINGS(File)
{
  emscripten::function("foo", &foo);
}

```

Then I built it with:
`emcc asyncify_return.cpp -o asyncify_return.html --bind -s ASYNCIFY=1 -s ASYNCIFY_IMPORTS='["bar"]'`

Result (executed in Chrome 89.0.4389.82 developer console):
```
let foo = Module.foo()
FOO
BAR
console.log(foo) // yields 0 instead of 42
```

I'm wondering why I get 0 instead of 42 here. However, if I comment out Asyncify.handleAsync in bar(), everything works fine.

My emcc version:
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.14 (8dd277d191daee9adfad03e5f0663df2db4b8bb1)

```

Any help and pointers will be appreciated. Thanks.

**Comment by sbc100** [comment]
@RReverser ?

**Comment by RReverser** [comment]
This is more or less duplicate of https://github.com/emscripten-core/emscripten/issues/11890 (see discussion towards the end), https://github.com/emscripten-core/emscripten/issues/13302 and other similar issues.

> If so, that is because when a function sleeps, it just returns immediately. You then need to continue it later. Calls in C are all handled for you automatically, but a plain call from JS isn't.

(c) https://github.com/emscripten-core/emscripten/issues/11890#issuecomment-673699542

**Comment by gwutama** [comment]
@RReverser Thank you very much for the links to the other issues.

After reading the issues, I found the easiest way to solve this issue is by not using embind for exposing the C/C++ function to JS and calling it with `ccall` from JS. 

Here's a working example. Hope it could help others with similar problems.

```
// asyncify_return.cpp
#include <iostream>
#include <emscripten.h>

extern "C" int foo();


EM_JS(void, bar, (), {
  return Asyncify.handleAsync(async () => {
    const cache = await caches.open('test123');
    console.log("BAR");
  });
});


int foo()
{
  std::cout << "FOO" << std::endl;
  bar();
  return 42; 
}
```

Build flags:
`emcc asyncify_return.cpp -o asyncify_return.html -s EXPORTED_FUNCTIONS="['_foo']" -s ASYNCIFY=1 -s 'ASYNCIFY_IMPORTS=["bar"]' -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall']"`

Result (chrome developer console):
```
let foo = await Module.ccall('foo', 'number', [], [], {async: true})
FOO
BAR
console.log(foo) // yields 42
```

One can easily wrap `Module.ccall('foo', 'number', [], [], {async: true})` in a JS function to make the function call more natural.
