### ISSUE TITLE
IE10 and Safari hanging while loading files

### ISSUE THREAD

**Issue by KungPhoo** [emscripten-core/emscripten#1368]
Hi,

my game works good on Firefox. But in IE 10 and Safari it loops the output of:
still waiting on run dependencies: 
 dependency: fp Media/ingamefont.png 
 dependency: fp Media/joypad.png 
 dependency: fp Media/readme.txt 
 dependency: fp Media/zzz_game.gack 
 dependency: datafile_C:UsersgfAppDataLocalTempglbasicoutput.data 
 (end of list) 

Here's the link:
http://www.glbasic.com/beta/_test.html

I created it with:

> python.exe emcc -O1 -s ASM_JS=1 --llvm-lto 0 --typed-arrays 2 inputfiles... -o output.html --preload-file "Media"

Where "Media" is a directory.

**Comment by juj** [comment]
I wonder if this was resolved and can be closed now?
