### ISSUE TITLE
New compiler warnings introduced due to refactor in EM_ASM macro.

### ISSUE THREAD

**Issue by miwelc** [emscripten-core/emscripten#13699]
https://github.com/emscripten-core/emscripten/pull/13443 introduced a new compiler warning (`-Wgnu-statement-expression`).

I always compile with `-Werror -Wall -pedantic` and I've never experienced any error coming from emscripten code until now. It would be nice if this line could be refactored somehow to avoid this issue.https://github.com/emscripten-core/emscripten/blob/510d92417a9f4a39828dab0932dc5b27754d0d53/system/include/emscripten/em_asm.h#L178

**Comment by sbc100** [comment]
Ah yes.  I think @tlively has a trick to enable statement-expression in the code itself?

**Comment by tlively** [comment]
Yes, you just have to place `__extension__` before the use of the statement expression. See line 205 of https://clang.llvm.org/doxygen/wasm__simd128_8h_source.html for an example.

**Comment by miwelc** [comment]
Thank you for fixing this!
