### ISSUE TITLE
Emulating later versions of ES 3

### ISSUE THREAD

**Issue by graphitemaster** [emscripten-core/emscripten#13712]
Currently Emscripten has `-s FULL_ES3=1` to provide full ES 3.0 emulation. There are current draft WebGL proposals and extensions that bump WebGL 2.0 to supporting ES 3.1 and ES 3.2 features. Is there a roadmap or plan for these?

**Comment by kripken** [comment]
cc @juj @kainino0x

**Comment by kainino0x** [comment]
WebGL will not ship an ES 3.1/3.2-equivalent version.

> The WebGL 2.0 Compute specification was a tremendous effort spearheaded by Intel to bring compute shader support to the web via the WebGL rendering context. During the development of this specification, the decision was made to halt further expansion of the WebGL API, and instead focus the contributors' efforts on the WebGPU specification.
> 
> For this reason, this specification should be considered obsolete. The WebGL working group thanks all of the contributors to this specification for their tremendous efforts in specifying and implementing this significant potential addition to the WebGL API. WebGPU will be the path forward for compute shaders on the web.

https://www.khronos.org/registry/webgl/specs/latest/2.0-compute/

However any WebGL extensions should ideally be exposed in Emscripten.
