### ISSUE TITLE
printf family of functions with %p format specifier

### ISSUE THREAD

**Issue by graphitemaster** [emscripten-core/emscripten#13711]
I'm experiencing strange behavior when passing a pointer of type `void*` to printf variable argument functions in place of `%p` specifier. In particular, it seems to be "compressing" the address, null pointers just show up as "0" and addresses to functions fetched via `SDL_GL_GetProcAddress` are very short, like `loaded 0x2a8 'glEnable'`, shouldn't `%p`, given 32-bit web assembly always produce values that are of the form `0xaabbccdd` (i.e four bytes), thus a null pointer should appear as `0x00000000`?

**Comment by kripken** [comment]
I'm not sure if "0" is ok by the spec or not for null (but I'd guess musl is right). But short function ptrs are because they are table indexes in wasm, in `(1,..,num_indexed_funcs)`. Yes, they are much smaller than other platforms.

**Comment by sbc100** [comment]
Indeed it looks like printf can implement %p in various ways: https://stackoverflow.com/questions/41639002/why-doesnt-p-show-the-full-width-of-pointer

We are using musl libc and I guess prints "0" for %p of null pointer.   According to that article mac apparently does that same "on a Mac, that prints just 0 even though other values are printed 0x1234 style."

So I guess this can be closed as WAI?

**Comment by graphitemaster** [comment]
TIL. Closing as this is expected behavior of printf.
