### ISSUE TITLE
library_glfw.js: monitors count is always set to 1

### ISSUE THREAD

**Issue by AndriiVovkWorkspot** [emscripten-core/emscripten#13739]
[glfwGetMonitors() function](https://github.com/emscripten-core/emscripten/blob/main/src/library_glfw.js#L1242) of ported GLFW library always sets monitors count to 1.

Minimal reproducible example.
Prerequisite: connect 2 displays to a PC
Compile: `emcc main.cpp -std=c++11 -s WASM=1 -s USE_GLFW=3 -O3 -o index.html`
Expected behavior: `monitor_count == 2` message in logs
Actual behavior: `monitor_count == 1` message in logs
```
// File : main.cpp
// Compile : emcc main.cpp -std=c++11 -s WASM=1 -s USE_GLFW=3 -O3 -o index.html

#include <functional>
#include <emscripten.h>
#define GLFW_INCLUDE_ES2
#include <GLFW/glfw3.h>
#include <stdio.h>

int main()
{
    if (!glfwInit()) {
      emscripten_force_exit(EXIT_FAILURE);
    }
    
    int monitor_count;
    GLFWmonitor **monitors = glfwGetMonitors(&monitor_count);
    
    printf("monitor_count == %d\n", monitor_count);

    return EXIT_SUCCESS;
}
```

**Comment by sbc100** [comment]
Does the web platform export the number of monitors?  If not, we can't really fix this.   If so,  it should be easy to modify the `glfwGetMonitors` to use this API on the JS side.

**Comment by sbc100** [comment]
It looks like there are plans to add an API in the future but nothing yet: https://chromestatus.com/feature/5252960583942144

I guess this issue can be closed since there is no feasible way to implement it today?
