### ISSUE TITLE
undefined symbol on JS function when main module 2

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#13786]
Note:
- Broke off from https://github.com/emscripten-core/emscripten/issues/13633 to track it as a separate issue.
- Related issue #13696

```
undefined symbol `jsPrintHello`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
```

I believe we get this error when we attempt to call a JS function by it's address, e.g. through a function pointer.
The JS function then gets added into the GOT and when we run reportUndefinedSymbols(), we are not able to locate the JS function and thus asserts.

I have attached a small sample case which reproduces this issue.
Build command: emcc foo.cpp -s MAIN_MODULE=2 -s ASSERTIONS=1 -Oz --js-library jslibrary.js -o index.js
Run command: node index.js
[reproducer.zip](https://github.com/emscripten-core/emscripten/files/6219343/reproducer.zip)

**Comment by Mintyboi** [comment]
What I did to make it work in my code was to edit `resolveGlobalSymbol()` to include looking for the JS function in the global namespace.
It's ugly, and inefficient in node env, but it works as a patch. @sbc100 do you know of a more elegant way?
```
function resolveGlobalSymbol(symName, direct) {
    var sym;
    if (direct) {
        sym = Module["asm"]["orig$" + symName]
    }
    if (!sym) {
        sym = Module["asm"][symName]
    }
    if (!sym && direct) {
        sym = Module["_orig$" + symName]
    }
    if (!sym) {
        sym = Module[asmjsMangle(symName)]
    }
    if (!sym) {
        if (ENVIRONMENT_IS_NODE) eval(`sym = typeof(${asmjsMangle(symName)}) !== "undefined" ? ${asmjsMangle(symName)} : undefined;`);
        else sym = globalThis[asmjsMangle(symName)]
    }
    if (!sym && symName.indexOf("invoke_") == 0) {
        sym = createInvokeFunction(symName.split("_")[1])
    }
    return sym
}
```

_Originally posted by @Mintyboi in https://github.com/emscripten-core/emscripten/issues/13633#issuecomment-803542020_

**Comment by sbc100** [comment]
I think relying on the JS globalThis scope (and eval)  is probably the wrong approach.   I'm working on a better solution now.
