### ISSUE TITLE
A little ❤️  for the Emscripten logo 

### ISSUE THREAD

**Issue by trzecieu** [emscripten-core/emscripten#13783]
Hello! I've noticed that Emscripten logo has some artifacts, so that it doesn't look good on a dark background. For the instance: 
Twitter:
![image](https://user-images.githubusercontent.com/4076929/112737516-61c49080-8f5b-11eb-805d-61c3f0128918.png)
Discord:
![image](https://user-images.githubusercontent.com/4076929/112737530-802a8c00-8f5b-11eb-9b7e-a6d928436230.png)

I've cleaned out the logo, so it should look better on links preview.

**Cleaned logo**:
![emscripten_logo](https://user-images.githubusercontent.com/4076929/112737551-b10ac100-8f5b-11eb-9cfb-030424e577c3.png)

If it looks good, please update the logo of https://github.com/emscripten-core : )

Previews: 
|dark|light|
|-|-|
| ![image](https://user-images.githubusercontent.com/4076929/112737570-ce3f8f80-8f5b-11eb-845f-009d7e2f5009.png) | ![image](https://user-images.githubusercontent.com/4076929/112737577-d7c8f780-8f5b-11eb-8dd7-15ea8a6ea5c9.png) |

Cheers,

**Comment by kripken** [comment]
Nice @trzecieu !

Can you open a PR with this? I think the relevant files to update may be
```
./site/source/_static/Emscripten_logo_full.png
./docs/emscripten_powered_by_logo.svg
./media/powered_by_logo.png
./media/powered_by_logo.svg
./media/switch_logo.png
./media/switch_logo.svg
```
