### ISSUE TITLE
MINIMAL_RUNTIME and no main() causes error on compilation

### ISSUE THREAD

**Issue by arseneyr** [emscripten-core/emscripten#13791]
Running `emcc` with the `MINIMAL_RUNTIME` flag and an `EXPORTED_FUNCTIONS` without a `_main` causes the following error:
```
emscripten@a8ab8b8f5310:/src$ emcc test.c -o test.js -s MINIMAL_RUNTIME -s EXPORTED_FUNCTIONS=['_test'] --no-entry
emcc: error: expected to find pattern in input JS: <<< ATMAINS >>>
```

This does not repro on releases earlier than 2.0.14.

I'm not very familiar with this code, but it seems like this function is unconditionally looking for an `<<< ATMAINS >>>` tag which may not be present in libraries without a `main`:
https://github.com/emscripten-core/emscripten/blob/4396dd29fda87e19e5c50e3cab4b50684b18510d/emscripten.py#L148-L153

**Comment by kripken** [comment]
Does ATMAINS ring a bell @sbc100 ?

If not we could [bisect this](https://emscripten.org/docs/contributing/developers_guide.html#bisecting).

**Comment by sbc100** [comment]
I recently made the replacements strict.. I guess we don't have a test for this configuration.
