### ISSUE TITLE
How to deal with `TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function`?

### ISSUE THREAD

**Issue by linuxaged** [emscripten-core/emscripten#13806]
the link option i use:

    target_link_options(${PROJECT_NAME} PRIVATE "SHELL:-s TOTAL_MEMORY=64MB -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_FUNCTIONS='[\"_main\",\"_BonApi_getSteps\",\"_BonApi_step\",\"_BonApi_viewLeft\",\"_BonApi_viewRight\",\"_BonApi_viewFront\",\"_BonApi_viewBack\",\"_BonApi_viewTop\",\"_BonApi_viewBottom\",\"_BonApi_setJawUpVisible\",\"_BonApi_setJawLowVisible\",\"_BonApi_setGumVisible\",\"_BonApi_setAttachmentVisible\",\"_BonApi_setOriginalToothVisible\",\"_BonApi_setGridVisible\",\"_BonApi_setIprVisible\",\"_BonApi_getMovements\",\"_BonApi_setViewport\",\"_BonApi_loadBonV_wasm\"]'")

the html:

    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />
      <title>Magnum Emscripten Application</title>
      <link rel="stylesheet" href="WebApplication.css" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
    <body>
      <h1>Magnum Emscripten Application</h1>
      <div id="container">
        <div id="sizer"><div id="expander"><div id="listener">
          <canvas id="canvas"></canvas>
          <div id="status">Initialization...</div>
          <div id="status-description"></div>
          <script type="text/javascript">
            function BonVProgress(argument){}
            function RendererInited(argument){}
            function BonVInvalid(argument){}
          </script>
          <script src="EmscriptenApplication.js"></script>
          <script async="async" src="BonViewer.js"></script>
        </div></div></div>
      </div>
    </body>
    </html>

full error:

    wasm streaming compile failed: TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function
    printErr @ EmscriptenApplication.js:35
    (匿名) @ BonViewer.js:1
    EmscriptenApplication.js:35 falling back to ArrayBuffer instantiation
    printErr @ EmscriptenApplication.js:35
    (匿名) @ BonViewer.js:1
    EmscriptenApplication.js:35 failed to asynchronously prepare wasm: TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function
    printErr @ EmscriptenApplication.js:35
    (匿名) @ BonViewer.js:1
    EmscriptenApplication.js:35 TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function
    printErr @ EmscriptenApplication.js:35
    abort @ BonViewer.js:1
    (匿名) @ BonViewer.js:1
    BonViewer.js:1 Uncaught (in promise) RuntimeError: abort(TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function) at Error
        at jsStackTrace (http://localhost:8080/BonViewer.js:1:26096)
        at stackTrace (http://localhost:8080/BonViewer.js:1:26272)
        at abort (http://localhost:8080/BonViewer.js:1:20823)
        at http://localhost:8080/BonViewer.js:1:23325
        at abort (http://localhost:8080/BonViewer.js:1:20854)
        at http://localhost:8080/BonViewer.js:1:23325
    abort @ BonViewer.js:1
    (匿名) @ BonViewer.js:1

PS. HOW do you choose a nonsense name "a"???

**Comment by kripken** [comment]
The name `a` is a minified name. It's a short as possible in optimized builds to get the binary size down. If you build with a lower optimization level `-O2` or `-O1` then it would not do that optimization.

That error might indicate that the wasm and the JS have not been both updated. Like maybe the wasm file there is from an old build, or maybe an old wasm is being cached incorrectly somehow.

If that's not it, to investigate you can disassemble the wasm file and see what it has instead of `a` for its imports. The output of an optimized build should have the JS refer to a module `a` and for the wasm to have its imports import from that `a` (you can disassemble the wasm and look for lines starting with `(import`).

**Comment by linuxaged** [comment]
Thanks! the *.wasm file and *.js are not match actually! the error message should be more obvious here 😉
