### ISSUE TITLE
ioctl(): unknown requests cause abort()

### ISSUE THREAD

**Issue by skadisch** [emscripten-core/emscripten#13810]
Currently `abort()` is called when a ioctl request is unknown. This breaks the use case when an application would trigger fallback code if an ioctl is not available. Now it just aborts.

Is there any reason for `abort()` vs `EINVAL` or `ENOSYS`? Does it make sense to switch to error codes or make this behavior configurable?

https://github.com/emscripten-core/emscripten/blob/64011e101e56cf713825d2d6e0a74a41f95d96c8/src/library_syscall.js#L456

**Comment by kripken** [comment]
I agree it should probably be `ENOSYS` (or another code if more appropriate). A PR would be welcome.
