### ISSUE TITLE
error: undefined symbol: popen (referenced by top-level compiled C/C++ code)

### ISSUE THREAD

**Issue by ysk2014** [emscripten-core/emscripten#13826]
cd vendor/gifsicle && make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
emcc -W -Wall  -g -O2   -o gifsicle clp.o fmalloc.o giffunc.o gifread.o gifunopt.o merge.o optimize.o quantize.o support.o xform.o gifsicle.o  gifwrite.o 
error: undefined symbol: popen (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _popen may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/usr/local/bin/node /usr/local/Cellar/emscripten/2.0.12/libexec/src/compiler.js /var/folders/_7/ffkn81c512j22ql5khslpchm0000gp/T/tmpy0u4b5pu.txt' failed (1)
make[3]: *** [gifsicle] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [vendor/gifsicle/gifsicle.o] Error 2

**Comment by sbc100** [comment]
emscripten doesn't support multiple processes so popen doesn't exist.    

Ideally you would configure the upstream software not to call it.  If that fails (and you know you are not actaully going to call it) then you can suppy your own dummy popen implementation and asserts.
