### ISSUE TITLE
Compiling with closure enabled renames interface methods defined using embind

### ISSUE THREAD

**Issue by ackh** [emscripten-core/emscripten#13827]
I have a working C++ code base that I successfully compile into WebAssembly using `emcc` 2.0.16. It consists of a bunch of C++ classes that I expose to JavaScript using Embind. When compiling the code base I use `emcc`'s `--pre-js` and `--post-js` switches to add my own JavaScript code which makes use of those C++ classes. Everything works great and I'm getting exactly what I want.

Now, I would like to run the Closure compiler to reduce the size of the JavaScript code that gets generated as a result and here's where I hit a wall. I started by simply adding `--closure 1` to my `emcc` command line call. However, in the resulting JavaScript file all the methods and properties that I defined using Embind were renamed by the Closure compiler.

Because of these renames the constructor of my C++ classes cannot be found anymore and the whole thing fails. To figure out what is going I opened the JavaScript file generated by the Closure compiler and changed the constructor and all method and property names back to their original names which made everything work again.

Now, Emscripten's [documentation](https://emscripten.org/docs/optimizing/Optimizing-Code.html#miscellaneous-code-size-tips) states that

> ... if you add your own additional JavaScript code (in a --pre-js, for example) then you need to make sure it uses closure annotations properly.

That section links to the Closure compiler documentation which eventually points me to using `goog.exportSymbol` to prevent stuff from being renamed. However, adding a list of Embind interface methods and properties that way and attempting to compile using `emcc` results in the following error message for every use of `goog.exportSymbol`:

````
ERROR - [JSC_UNDEFINED_VARIABLE] variable goog is undeclared
````

If `goog.exportSymbol` is the way to go, I'm clueless as how to properly use it. Google's documentation seems to indicated that I have to use the Closure library in order to clarify what `goog` is. However, I couldn't figure out how to instruct the `emcc` call to use the Closure library.

Besides this, it is unclear to me as to _why_ the whole thing would even be necessary. Naively speaking, the compiler should be aware of my Embind definitions and hence prevent those definitions from being renamed in the JavaScript code in the first place.

Another part of the [documentation](https://emscripten.org/docs/tools_reference/emcc.html) recommends to

> Consider using -s MODULARIZE=1 when using closure, as it minifies globals to names that might conflict with others in the global scope. MODULARIZE puts all the output into a function (see src/settings.js).

However, adding `-s MODULARIZE=1` makes the situation worse in that the WebAssembly module is not loaded at all anymore by the generated JavaScript code.

Surely I'm missing something here but I read all documentation I could find about that topic and I'm still stuck.

How can I enable Closure without messing up my JavaScript code?

**Comment by kripken** [comment]
This sounds like a possible bug in embind - perhaps something needs a closure quote that is missing it. Yes, the compiler should be emitting code that works with closure. And this doesn't sound like a known issue to me

Can you provide a small testcase for investigation?

**Comment by ackh** [comment]
Good to know that it should work without requiring annotations in the JavaScript code. I have constructed a minimal sample that seems to reproduce the issue when compiling with `emcc` 2.0.16`. It is contained in the [attached .zip file](https://github.com/emscripten-core/emscripten/files/6271269/emscripten-2.0.16-closure-issue.zip). Unzipping it will reveal a Git repository with two commit.

The first commit contains C++ code to produce a minimal WebAssembly module, the JavaScript code necessary to use the module's functionality, an HTML file that renders a user interface for the module and a bash shell script to build everything. The build script in that commit does not use Closure and produces a sample that works as expected.

The second commit just modifies the build script so that Closure is used when compiling. On my machine (Windows 10 with Windows Subsystem for Linux (WSL) 2.0) that produces a sample where one of the two methods provided by the WebAssembly module via Embind gets renamed in the JavaScript code. Because of this, the functionality breaks. This is testable via HTML file by simply clicking the buttons.

From what I see, this is the same issue that I'm having with my production code. The difference seems to be the scope, i.e. pretty much all functions that I provide via Embind are renamed in my production code while for the sample its just one.

**Comment by kripken** [comment]
Thanks for the testcase. Ok, the issue is that embind will ensure the full name is exported, `Module.subtract` - not a minified name. The optimizer doesn't minify that intentionally. But your code lacks closure annotations so it is minified. To fix this, you can add closure annotations:

```javascript
function addButtonClickHandler(event) {
  addResult.value = math['add'](parseInt(addLeft.value), parseInt(addRight.value))
}

function subtractButtonClickHandler(event) {
  subtractResult.value = math['subtract'](parseInt(subtractLeft.value), parseInt(subtractRight.value))
}
```
(the `math['..']` stuff).

This isn't something that the optimizer can know about, as your object `math` there is assigned an instance of `Module`, and also the embind code is dynamic, so the compiler can't see all that at compile time.

Alternatively, you can place your code outside of a pre-js, where closure won't minify it.

(As to why it works anyhow with `.add` but not `.subtract`, my only guess is that `.add` is special-cased by closure, perhaps because it is short?)

**Comment by ackh** [comment]
Alright, so that's the part that I was missing. If I replace the dot syntax with the square bracket syntax for all methods and properties that are exposed to JavaScript via Embind the code that is emitted by the Closure compiler works as expected.

I think this is something that is worth mentioning in Emscripten's documentation. Could you point me to the location of it on GitHub so that I could propose a change?

Thanks for your help!

**Comment by kripken** [comment]
A PR would be great!

Our docs are all under `site/source/` in this repo. The embind page is `./docs/porting/connecting_cpp_and_javascript/embind.rst` under there, and probably the natural place to add this?

**Comment by ackh** [comment]
Alright, I have created a pull request to make the necessary clarifications in the documentation. I hope this prevents others from running into the same issue.

This is my first GitHub pull request ever, so please let me know if something is not as it should be.

**Comment by kripken** [comment]
Thanks for the PR! Much appreciated. It looks good, I commented there.
