### ISSUE TITLE
Clang crash "fatal error: error in backend: Broken function found, compilation aborted"

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#13828]
After updating to Emscripten 2.0.16, the build of my application started to fail with a Clang error:

> Offset not zero at the point of scalar access
>   store i32 %handler.unpack9, i32* %.fca.1.gep, align 4, !tbaa !369
> !369 = !{!367, !9, i64 12}
> 8
> in function _ZN17google_smart_card30PcscLiteClientRequestProcessor11WrapHandlerINSt3__25tupleIJEEEMS0_FNS_13RequestResultINS_5ValueEEEvEJEEENS2_8functionIFS7_NS2_6vectorIS6_NS2_9allocatorIS6_EEEEEEERKNS2_12basic_stringIcNS2_11char_traitsIcEENSC_IcEEEET0_NS_10ArgIndexesIJXspT1_EEEE
> fatal error: error in backend: Broken function found, compilation aborted!

Could the Emscripten team look into this, or should this bug report be submitted directly to LLVM?

[emscripten-2.0.16-build-crash.log](https://github.com/emscripten-core/emscripten/files/6263977/emscripten-2.0.16-build-crash.log)
[client_request_processor-b353b4.zip](https://github.com/emscripten-core/emscripten/files/6263983/client_request_processor-b353b4.zip)

**Comment by kripken** [comment]
Almost certainly this is an LLVM bug, yes. What I'd recommend is to [bisect this](https://emscripten.org/docs/contributing/developers_guide.html#bisecting) which is pretty fast (see details there - you don't need to rebuild anything). That should confirm it is in LLVM, and also give a (hopefully short) blame range. Then filing a bug with that for LLVM.

**Comment by emaxx-google** [comment]
Not reproducible on 2.0.24 anymore, therefore closing this.
