### ISSUE TITLE
Automatically perform main module DCE when side modules are visible at link time.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#13830]
Perhaps we should add `MAIN_MODULE=auto` for this purpose?

**Comment by kripken** [comment]
Specifying side modules does not indicate those are the only ones, though, I think? If more are linked in then a problem could occur.

**Comment by sbc100** [comment]
True, that is one reason we might not wan to make `=auto` the default.

Normally however I imagine that there are two types of apps:

1. Apps that link the side modules on the command lone
2. Apps that load side modules vai dlopen (and don't specify any on the command line).

I think it might make sense to assume that the application is of type (1) if there are side modules specified on the command line but I'm not proposing that initially.

Initially we can offer this as an opt-in vai explicit `-s MAIN_MODULE=auto`.

**Comment by sbc100** [comment]
Or maybe `-s MAIN_MODULE=2 -s AUTO_DEPS` to avoid overloading `MAIN_MODULE` more than it already is.

**Comment by sbc100** [comment]
If we want to be clever we could also tell at link time if dlopen is ever called.

**Comment by kripken** [comment]
How does this differ from the existing `MAIN_MODULE=2` then? Is it that we opt into mode 2 when the side modules are given, and not when not? If so then isn't specifying `MAIN_MODULE=2` as easy as `AUTO_DEPS=1`?

**Comment by sbc100** [comment]
`MAIN_MODULE=2` currently ignores the side modules completely and is only based on `EXPORTED_FUNCTIONS`.

I suppose one sensible way to introduce this features is to say that `MAIN_MODULE=2` includes anything in `EXPORTED_FUNCTIONS` *plus* anything needs by the side modules on the command line?

**Comment by sbc100** [comment]
Which could remove main issue that folks face when trying to use `MAIN_MODULE=2`.  WDYT?

**Comment by kripken** [comment]
> I suppose one sensible way to introduce this features is to say that MAIN_MODULE=2 includes anything in EXPORTED_FUNCTIONS plus anything needs by the side modules on the command line?

:+1: That's how I had thought it worked. Seems least surprising.
