### ISSUE TITLE
accessing module before instantiation

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#13850]
Today we read the first (custom) section (dylink) or all side modules before we load them.   We also read the dylink section of the main module, but only after its instantiated.

When loading the main module it would good to be able to parse the dylink section *before* instantiation so that we can use the information therein to construct the exports object (for example to determine the initial size of the table).   The impetus for wanting to do this is wasm-split, where the split module requires that large initial table than the module as it was at initial compile time.  However, I imagine there could be more data in custom section and indeed in non-custom section that we might want to read before loading the module.  For example, if we wanted to create a fully flexible module loader rather than a compile-time-fixed one.

The reason this is currently not possible/easy with the main module is that we rely on `instantiateStreaming` which takes the bytes off the wire and performs instantiation before we get a chance to look at the module.  

A few options I can think of:

1. Call response.clone() and try to read just enough of the bytes to parse the dylink section *before* calling `instantiateStreaming` with the original response.
2. Switch to `compileStreaming` so that we can access the module bytes before instantiation.

What are the downsides to calling `compileStreaming`?

**Comment by kripken** [comment]
`instantiateStreaming` may be more efficient than the alternatives. Aside from minor browser internals that may be simpler, getting the imports up front - before even compilation - may allow certain optimizations. So I don't think we should switch to it for everything. However, for dynamic linking and other things where we have no choice it's probably fine.

Why is this an issue for wasm-split? Can't that tool update the table size at compile time?

**Comment by sbc100** [comment]
> `instantiateStreaming` may be more efficient than the alternatives. Aside from minor browser internals that may be simpler, getting the imports up front - before even compilation - may allow certain optimizations. So I don't think we should switch to it for everything. However, for dynamic linking and other things where we have no choice it's probably fine.
> `instantiateStreaming` may be more efficient than the alternatives. Aside from minor browser internals that may be simpler, getting the imports up front - before even compilation - may allow certain optimizations. So I don't think we should switch to it for everything. However, for dynamic linking and other things where we have no choice it's probably fine.

Why is this an issue for wasm-split? Can't that tool update the table size at compile time?
> Why is this an issue for wasm-split? Can't that tool update the table size at compile time?

For normal modules yes.. since the table is embedded.  For dyanmic linking (MAIN_MODULE) that table is create in JS based on a constant value baked into the JS.

#13853 changes this to be a dyanmic valid read from the dylink section before wasmTable creation.

**Comment by kripken** [comment]
I'm confused, does `wasm-split` use dynamic linking? I thought it was a custom mechanism done to a normal build. Maybe I missed something of the recent iterations?

**Comment by sbc100** [comment]
Its a completely independent mechanism.  You can split a MAIN_MODULE just like you can split any other module.   I believe we have folks who would like to support runtime dynamic loading as well as a split module.

**Comment by sbc100** [comment]
> getting the imports up front - before even compilation - may allow certain optimizations

I'd love to find out if this is actually true.   If it turns out that compiling before instantiate has code size or other benefits then we should investigate the veracity of the above statement to make sure it really is worth keeping the old code path around.   I imagine we may be able to unify the loading code for the main module and the side module if we make the switch...

**Comment by kripken** [comment]
May be worth talking to VM people then. I remember there was discussion about such possible optimizations, but I'm not sure if anything came of them or not.

Doesn't wasm-split change the module quite a lot anyhow as it splits? Why is adjusting the table while doing so not the obvious thing to do?

**Comment by sbc100** [comment]
My understanding is that `wasm-split` is designed to make a new module appear (roughly, and within reason) the same as the original module.

**Comment by kripken** [comment]
Maybe I'm missing something, but I'd argue increasing the table size is within reason. It's not really observable by users (unless they test trapping behavior) and it's much simpler and more efficient than doing work on the client side to scan the module.

**Comment by sbc100** [comment]
Growing the table is fine.  

The problem is that the static JS is generated before the module splitting is done (based on the unsplit module) so it doesn't know that actual size the is needed.   I think having wasm-split do a little code-gen to generate a call to `table.grow` is fine (assuming that is what you referring to when you said "increasing the table size is within reason").

I will close this for now in favor of pursuing the option of having wasm-split leave the static table alone and modify its size at runtime instead.

**Comment by kripken** [comment]
The module creates the table by default, which would avoid that problem - can we not do that with wasm-split?

**Comment by sbc100** [comment]
The problem only exists in RELOCATABLE (i.e. MAIN_MODULE) mode where table is created up-front by JS.

**Comment by kripken** [comment]
Could we change that? I can't think of why it is necessary. We don't do anything with the table before the wasm file is loaded, do we? (even in dynamic linking)

**Comment by sbc100** [comment]
I do have an outstanding WIP to build MAIN_MODULE without RELOCATABLE (which I think is exactly what you are suggesting), but its currently stalled on a few issues (the main one I think is allocating space for the side modules static data before the main module is ready (i.e. before we can call malloc).

**Comment by kripken** [comment]
I think this might be orthogonal to `MAIN_MODULE` being with or without `RELOCATABLE`. Could the main module be relocatable but still define the table? (moving the table in and out of the module seems separate from whether there are offsets to table elements)

**Comment by sbc100** [comment]
I might be possible yes.   Perhaps we could switch the `-pie` linker flag (the one we use to build the main module) export the table rather than import it.      Or we could just build with `--export-table`.. I'll give that a go.
