### ISSUE TITLE
compiling with -s ASYNCIFY and --closure 1 fails with undeclared dynCall_*

### ISSUE THREAD

**Issue by rhashimoto** [emscripten-core/emscripten#13858]
Using 2.0.16 (52ed04f424ff0db7d8085c35df3afd7f7b1c9eb7), I'm compiling this minimal C code:
```c
#include <stdio.h>
#include <emscripten.h>

int main() {
  printf("Hello, world!\n");
}
```

When I build with Asyncify + Closure optimization, I get:
```
$ emcc -s ASYNCIFY --closure 1 hello.c -o hello.js
building:ERROR: Closure compiler run failed:

building:ERROR: tmpc2sg7vit.js:1810:27: ERROR - [JSC_UNDEFINED_VARIABLE] variable dynCall_v is undeclared
  1810|             (function() {  dynCall_v.call(null, func); })();
                                   ^^^^^^^^^

tmpc2sg7vit.js:1812:29: ERROR - [JSC_UNDEFINED_VARIABLE] variable dynCall_vi is undeclared
  1812|             (function(a1) {  dynCall_vi.apply(null, [func, a1]); })(callback.arg);
                                     ^^^^^^^^^^

2 error(s), 0 warning(s)

emcc: error: closure compiler failed (rc: 2): /home/dev/emsdk/node/14.15.5_64bit/bin/node --max_old_space_size=8192 /hom
e/dev/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --l
anguage_in ECMASCRIPT_2020 --language_out NO_TRANSPILE --emit_use_strict=false --externs tmpgm9p6ex7.js --externs tmpaff
kn6t9.js --externs tmp8bybq20t.js --externs tmp03_7rkmp.js --externs tmpod4ictzi.js --externs tmpcxlk_bv3.js --externs t
mpqu9gj0cy.js --externs tmp65p65c0k.js --externs tmpx33k798f.js --externs tmplf9hgc4v.js --externs tmp9ghfy38_.js --exte
rns tmpfk441d1l.js --externs tmpc8_nsbvv.js --externs tmp_g7a36t8.js --externs tmp1tmh7qq9.js --externs tmpvz2n8w95.js -
-externs tmpum_ggeb6.js --externs tmpiofwu7h6.js --externs tmpr_rgrgkz.js --externs tmp714r4b0d.js --externs tmpnkj8inws
.js --externs tmprxa17291.js --externs tmp5suzw_5u.js --externs tmp2896h20q.js --externs tmp8lmfmv5s.js --externs tmp5pi
s_q7m.js --externs tmpr3uule80.js --externs tmp6c48g27d.js --externs tmpfijl40q8.js --externs tmp6y_5x_ea.js --externs t
mpm94qid1b.js --externs tmpw2sswmjd.js --js_output_file tmpku06pakj.cc.js --formatting PRETTY_PRINT --js tmpc2sg7vit.js
```

In my real code where I first encountered the problem, I only saw `dynCall_v` undeclared; I didn't see an error for `dynCall_vi` until simplifying the test case. The compilation succeeds if either the Asyncify or the Closure flags are removed. I have not used any previous distributions so I don't know if this is a regression.

I am attaching the EMCC_DEBUG=2 console output and temporary files.
[emcc-bug.zip](https://github.com/emscripten-core/emscripten/files/6288577/emcc-bug.zip)

**Comment by rhashimoto** [comment]
This does appear to be a regression that occurred between emsdk 2.0.13 and 2.0.14.

**Comment by rhashimoto** [comment]
I think the first failing emsdk build is [4b7f8f6e...](https://chromium.googlesource.com/emscripten-releases/+/4b7f8f6e7213bca73efa95db0367022da2ec1dc4) (prior build [c7f5551c...](https://chromium.googlesource.com/emscripten-releases/+/c7f5551c8886272934f514627b9ddfad5ea99ec8) works).

That looks like the right place because [this commit](https://chromium.googlesource.com/external/github.com/emscripten-core/emscripten.git/+/0eb76b28146540fe313157e3e4aeb696a8c3335a%5E%21/) removes `dynCall_*` symbols. I think that's as far as I can go with it.

**Comment by kripken** [comment]
@juj PTAL as this points to your commit `Fix combined use of Closure, MINIMAL_RUNTIME and EXIT_RUNTIME=1` (#12046)

**Comment by tklajnscek** [comment]
+1 for a fix here as we've also hit this issue and the current workaround is pretty ugly...

We use Asyncify to run fibers in our web build like we do on other platforms.

I guess this ties into what the general plan is for Asyncify currently requiring the legacy DYNCALL support, but I still think it would make sense that the required dyncalls remain in closure-externs.js until that changes?

**Comment by kripken** [comment]
Agreed @tklajnscek . I opened https://github.com/emscripten-core/emscripten/pull/14716 with a possible fix for this now.
