### ISSUE TITLE
How can I get exception stack trace at wasm？

### ISSUE THREAD

**Issue by xdestiny110** [emscripten-core/emscripten#13868]
A simple C++ code like this
```
void foo() {
    std::unordered_map<int, int> m;
    m.at(0) = 10;
}
```
Javascript invoke this method
```
try {
    Module.foo();
} catch (e) {
    console.log(e.toString())
    console.log(e.stack?.toString())
}
```
Normally C++ would throw `std::out_of_range` exception and Javascript catch it. But I only see log like this
```
7615992
undefined
```
I wonder how can I get stack trace?

**Comment by xdestiny110** [comment]
@sbc100 I upload my demo code to [https://github.com/xdestiny110/emsdkexceptiontest](https://github.com/xdestiny110/emsdkexceptiontest) is my project. Could you help me?
My emcc version is 2.0.17.
BTW，I catch stack trace when I add `-s ABORT_ON_WASM_EXCEPTIONS =1`. But it is not what I need.

**Comment by artemjackson** [comment]
@xdestiny110 you may also be interested in https://emscripten.org/docs/porting/Debugging.html#handling-c-exceptions-from-javascript
