### ISSUE TITLE
Using JavaScript module export in files supplied via --pre-js/--post-js fails with a SyntaxError

### ISSUE THREAD

**Issue by ackh** [emscripten-core/emscripten#13894]
I'm attempting to export some symbols in the JavaScript code that I pass to `emcc`'s `--pre-js` and `--post-js` in order to provide an easier public JavaScript interface for my WebAssembly component. However, if I add `export { myFunction1, myFunction2 };` at the end of the `--post-js` file I'm getting the following error message:

````
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (3664:0)
export { myFunction1, myFunction2 };
^

    at Parser.pp$4.raise (/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/acorn/dist/acorn.js:2927:15)
    at Parser.pp$1.parseStatement (/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/acorn/dist/acorn.js:870:18)
    at Parser.pp$1.parseTopLevel (/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/acorn/dist/acorn.js:755:23)
    at Parser.parse (/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/acorn/dist/acorn.js:555:17)
    at Function.parse (/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/acorn/dist/acorn.js:578:37)
    at Object.parse (/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/acorn/dist/acorn.js:5095:19)
    at Object.<anonymous> (/mnt/c/Tools/emsdk/upstream/emscripten/tools/acorn-optimizer.js:1819:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  pos: 126980,
  loc: Position { line: 3664, column: 0 },
  raisedAt: 126986
}
emcc: error: '/mnt/c/Tools/emsdk/node/14.15.5_64bit/bin/node /mnt/c/Tools/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_a16t4n3q/math.js.pp.js AJSDCE --closureFriendly' failed (1)
````
From what I see, `emcc` invokes [acorn](https://github.com/acornjs/acorn) which eventually causes that error. I'm unsure about how to fix that issue.

Anyway, eventually I compile my code with `--closure 1` which means that the Closure Compiler optimizes my JavaScript anyway. Hence, I'm wondering whether I can somehow prevent Emscripten from running acorn in the first place.

I have attached a small sample that reproduces the problem: [emscripten-acorn-issue.zip](https://github.com/emscripten-core/emscripten/files/6311704/emscripten-acorn-issue.zip)

**Comment by ackh** [comment]
Apparently, Acorn needs to be told in which mode the code should be parsed in. Acorn's `parse` function contains two arguments, the source to be parsed and an object that specifies various parse settings (see https://www.npmjs.com/package/acorn). One of those settings is called `sourceType` which can either be `"script"` or `"module"` as the error message implies.

That `parse` function is called in `emscripten/tools/acorn-optimizer.js` (`emsdk/upstream/emscripten/tools/acorn-optimizer.js`) on line `1819`:

````javascript
...
1818: try {
1819:  ast = acorn.parse(input, {
1820:    // Keep in sync with --language_in that we pass to closure in building.py
1821:    ecmaVersion: 2020,
1822:    preserveParens: closureFriendly,
1823:    onComment: closureFriendly ? sourceComments : undefined
1824:  });
1825: } catch (err) {
...
````
Adding `sourceType: "module"` resolves the error:
````javascript
...
try {
  ast = acorn.parse(input, {
    // Keep in sync with --language_in that we pass to closure in building.py
    ecmaVersion: 2020,
    preserveParens: closureFriendly,
    onComment: closureFriendly ? sourceComments : undefined,
    sourceType: "module"
  });
} catch (err) {
...
````
However, the full implications of this are unclear to me right now. There might be side effects by this that I'm unaware of. But maybe this setting should be exposed to a command line flag or something. If I find out more about this I'll post again.

**Comment by sbc100** [comment]
Would using `--extern-pre-js` / `--extern-post-js` help in this situation?

**Comment by ackh** [comment]
Yes, `--extern-pre-js` and `--extern-post-js` prevent that problem. I'm currently using them and can compile the code.

However, maybe we should address that issue so that it works with `--pre-js` and `--post-js` as well.

**Comment by kripken** [comment]
I think we'd need to pass that `sourceType` argument to be `"module"`, yeah. Emscripten doesn't know you intend it to be a module, though, unless you build with `EXPORT_ES6` - but I assume you are building without that?

In that case maybe `--extern-*-js` are the best thing for someone that doesn't want to use emscripten's own support for ES6 modules?

**Comment by ackh** [comment]
Correct, I'm building without the flag `EXPORT_ES6`. 

The background here is that I'm turning my WebAssembly module into a Web Component. To do so, I authored an ES6 class that I would like to export:

````javascript
export default class MyWebComponent extends HTMLElement {
  ...
 }
````
So, instead of exposing the `Module` as JavaScript API I would just like to directly expose `MyWebComponent`.

Initially, I tried to achieve all this by merging that class with the emitted JavaScript code using the `--post-js` flag. However, after battling the closure compiler for some time I eventually settled for `--extern-post-js` which works for me without running into this issue anymore.

But maybe it makes sense to resolve this issue nonetheless by teaching Acorn which `sourceType` to use in which case.

**Comment by sbc100** [comment]
I think `--extern-post-js` is a perfectly reasonable solution here.   We want to avoid adding yet more build options if possible. 

If you are ok with that we can close this issue.

**Comment by ackh** [comment]
Yes, I think we can leave it at that for the Moment and close the issue.

**Comment by kripken** [comment]
I opened an issue #13937 for passing the module flag when EXPORT_ES6.
