### ISSUE TITLE
Create / populate a typed-array from WASM backed by JS memory

### ISSUE THREAD

**Issue by mikerreed** [emscripten-core/emscripten#13905]
My WASM api wants to return a typed-array. e.g.

Foo(...) : Float32Array;

where Foo is implemented in C++ / WASM.

For ease of use by the caller, I want the backing ArrayBuffer to live in the JS heap, not the WASM heap (so it will get GC'd).

Request: emscripten/bind API to do this.

Note: I see emscripten::val::array(), which seems to create an array backed by JS memory, but this is not an ArrayBuffer / typed-array, and my use case really wants to take advantage of the packing of typed arrays.

**Comment by wffurr** [comment]
You can do this by invoking the typed array constructor from wasm using val, e.g.

`val js_typed_array = val::global("Uint8Array").new_(length);`

You could then copy into it by creating a `typed_memory_view` of your C++ memory and using the TypedArray `set` method, e.g.

```
val CopyFromHeap(const std::vector<T>& bytes) {
  val length = val(bytes.size());
  val js_array = val::global("Uint8Array").new_(length);
  js_array.call<void>("set",
                      val(typed_memory_view(bytes.size(), bytes.data())));
  return js_array;
}
```

Swap in your own container or typed array types to taste or use a template.

**Comment by mikerreed** [comment]
Thanks!

**Comment by mikerreed** [comment]
This would be a handy utility to bake into emscripten, but the suggested code worked great, so closing this issue.
