### ISSUE TITLE
wasm-split fails with assertion 'Function already has multiple table slots' in wasm::ModuleSplitting::(anonymous namespace)::TableSlotManager::addSlot

### ISSUE THREAD

**Issue by sps-gold** [emscripten-core/emscripten#13928]
Using optimisation -Oz fails the wasm-split with following error:

```
wasm-split: /b/s/w/ir/cache/builder/emscripten-releases/binaryen/src/ir/module-splitting.cpp:153: void wasm::ModuleSplitting::(anonymous namespace)::TableSlotManager::addSlot(wasm::Name, wasm::ModuleSplitting::(anonymous namespace)::TableSlotManager::Slot): Assertion `it.second && "Function already has multiple table slots"' failed.
test_wasm_split (test_other.other) ... FAIL
```

Added test:
https://github.com/emscripten-core/emscripten/pull/13927

**Comment by sbc100** [comment]
I yes, I can imagine that wasm-split interacts badly with out table-slot-tracking code in JS.  Will need to be investigated.

**Comment by sps-gold** [comment]
I am not sure if I understand `table-slot-tracking code in JS`, but anyway thanks a ton @sbc100 for looking into it.

**Comment by sps-gold** [comment]
@tlively allow me to reply to your https://github.com/emscripten-core/emscripten/pull/13927#issuecomment-822790312 here, just to avoid two thread on this issue.

> Is the only difference between this new test and `test_split_main_module` the use of `-Oz`?

I think there are few other differences, like -
1. this builds as c++ linking against libc++, whereas test_split_main_module builds as c 
2. test_split_main_module uses `do_other_test` to build which adds few other flags like `-nostdlib++`
which is why even if we include -Oz flag in `test_split_main_module` we do not encounter the same error.

**Comment by sbc100** [comment]
I found what I think is the root cause.   When binaryen merges identical functions a single function can end up with multiple table slots.

In the test case you posted for example we have:

```
0186e2 func[1209]:
 0186e3: 41 00                      | i32.const 0
 0186e5: 0b                         | end
0186e7 func[1210]:
 0186e8: 41 00                      | i32.const 0
 0186ea: 0b       
```

And each of these is in the table, and binaryen merges them into the same function generating two elem entries for the same function:

```
  - elem[7] = func[249]
  - elem[8] = func[249]
```

Which wasm-split is not expecting it seems..

**Comment by awtcode** [comment]
Thanks @sbc100 :) @tlively , just curious, is this bug happening because we have to add the exported functions from the secondary module into the table and we first check if the function already occupies multiple slots?

**Comment by sbc100** [comment]
There is a basic assumption in the code that functions never exist more than once in the table.   While this is true for llvm-generated code, it appears then binaryen passes can invalided this assumption (by merging identical functions).  IIUC this is  unrelated to the secondary module.  The primary module one its own, even before splitting, can exhibit this trait.     This seems to explain why your test case doesn't fail unless `-Oz` is added.

**Comment by sbc100** [comment]
I confirmed this fixes the tests case presented here.

**Comment by tlively** [comment]
Thanks for confirming, @sbc100!

**Comment by sps-gold** [comment]
Thanks @sbc100 and @tlively for resolving it so fast. I will try the fix today.

PS: Guess I will need to build latest binaryen to validate, installing tot-upstream will not be sufficient.

**Comment by sbc100** [comment]
`tot` should include this change just as soon as it gets rolled into https://chromium.googlesource.com/emscripten-releases/.   In this case it looks like the roller is currently failing: https://autoroll.skia.org/r/binaryen-emscripten-releases, so we need to look into that.

Normally changes make it into tot withing a few hours of landing.

**Comment by sps-gold** [comment]
Also curious if we can use latest binaryen wasm-split pkg with this fix, with emsdk 2.0.15, as we are currently using 2.0.15 version. Or if that's not advisable.

**Comment by sbc100** [comment]
It might work.. and it is probably worth trying, but its not really advisable to mix binaryen and emscripten versions like that because there is an ABI between the two that we do break from time to time.    If there is an ABI break which makes it impossible it should be fairly obvious.

**Comment by sps-gold** [comment]
thanks, I will just cherry pick the fix in corresponding version of binaryen then

**Comment by sbc100** [comment]
Yes, if you have that ability that would be good idea.

**Comment by sps-gold** [comment]
sure and btw I too find wasm-split issue is fixed on latest emsdk ('sdk-releases-upstream-2e3477ce54fd38261b7db033556180176c8fb641-64bit'.) so closing this issue.

**Comment by sps-gold** [comment]
> Yes, if you have that ability that would be good idea.

@sbc100 I see that cherry-pick of that particular commit wasn't straight forward as there were some changes dependent on prior changes. I believe those are not related to this fix. So based on your explanation, I understand that assertion is no longer valid, so I just commented the [assertion here](https://github.com/WebAssembly/binaryen/blob/47c15838ad4378430b2d216fbf4474b71d3fb66f/src/ir/module-splitting.cpp#L147) and can now run wasm-split without fail and the splitted modules can be loaded fine. I think that is sufficient for me.

**Comment by sps-gold** [comment]
hi @sbc100, @tlively, though I do not encounter any error and wasm-split is working well for me, still I feel that a quick confirmation from any of you would be more reliable. 

As I am on 2.0.15 so am cherry-picking fix in corresponding version of wasm-split (version_100-12-g89b8af006). My question is, if in order to fix wasm-split error I just pick removal of assertion from [your PR](https://github.com/WebAssembly/binaryen/pull/3825/files) is that sufficient, or do I need to pick any other change to ensure I have complete fix. My current understanding is other changes in the PR are not related to this issue.

**Comment by tlively** [comment]
That's correct, removing that assertion should be sufficient and should not cause any other problems 👍

**Comment by sps-gold** [comment]
Thank you so much @tlively . Much appreciated.
