### ISSUE TITLE
AttributeError: module 'tools.shared' has no attribute 'Building'

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#13932]
in Emscripten V2.0.16 ,Compiling the Projects make a error;
In V1.39，Compile the script as `tools.shared.Building.emcc(file, emcc_args + Include_files , os.path.join('obj', arrs[-1]))`
then, in V2.0.16, how compile the projects?

**Comment by sbc100** [comment]
Emscripten is not designed to be used as a library like that.

I believe the function you calling moved to `tools.building.emcc`.. but please move away from using that if you can.  The supported way to use emscripten is to run the compile from the command line by invoking `emcc` or `em++`.

Can I ask what project you are trying to compile that using this method to call the compiler?

**Comment by sbc100** [comment]
I actually noticed that we can completely remove this method from emscripten: https://github.com/emscripten-core/emscripten/pull/13938

**Comment by yangfangfang1204** [comment]
How does a visual studio (C++) project compile into the WASM library? Do you have a compilation script template?

**Comment by sbc100** [comment]
I don't know of any way to have visual studio itself run emscripten although I imagine it is certainly possible via some kind of plugin.

To use the compiler itself you need to run the `emcc` on each of your source file.  See https://emscripten.org/docs/getting_started/Tutorial.html for examples of how to get started.

**Comment by sbc100** [comment]
Can you link to where you saw a reference to `tools.shared.Building.emcc` .. it would be good to get that corrected whereever it is.

**Comment by yangfangfang1204** [comment]
**First：**
`OBJPATH =  $(shell pwd)
CC       = emcc

INCLUDE_DIR = -Iinclude      \
-Isrc/Build/DLL \
-Isrc/Manager  \
-Isrc/AL \
-Isrc/algorithm \
-Isrc/Codec \

CFLAGS   = -Wall -Wno-unused-variable -Wno-unused-function -g  -pthread -shared $(INCLUDE_DIR)
LDFLAGS  = -D__WEBJS__ -DSUPPORT_OPENAL -O3 -flto

LIBS = $(wildcard bc/*)

SOURCES = $(wildcard src/Build/DLL/*.cpp) \
$(wildcard src/Manager/*.cpp) 	\
$(wildcard src/AL/*.cpp) 	\
$(wildcard src/algorithm/*.cpp) 	\
$(wildcard src/Codec/*.cpp) \

OBJS = $(patsubst %.cpp,%.o,$(SOURCES))

EXECUTABLE = STAudioInterCom.bc

.cpp.o:
	$(CC) $(CFLAGS) -c  $<

$(EXECUTABLE) : $(SOURCES)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(EXECUTABLE) $(SOURCES) $(LIBS)
	
.PHONY: clean

clean:
	rm -f $(notdir $(OBJS)) $(EXECUTABLE)`
**Second:**
`emcc -o3 --bind bc/aac.bc bc/AudioRender.bc STAudioInterCom.bc -o AudioInterCom.js -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'getValue','writeArrayToMemory']" -s USE_PTHREADS=1 -s INITIAL_MEMORY=1GB -s ALLOW_MEMORY_GROWTH=0 --js-library AudioData.js -lopenal`

**Finally**
there is a error :
`wasm-ld: error: linking module flags 'EnableSplitLTOUnit': IDs have conflicting values in 'STAudioInterCom.bc' and 'ld-temp.o'
`
In STAudioInterCom.bc , EnableSplitLTOUnit doesn't used, Do you know why?

**Comment by sbc100** [comment]
I'm not familiar with that error but its certainly related to LTO and the way you built `STAudioInterCom.bc`.

My advice would be to first get the build working without LTO, before trying to build and LTO version.   So build all your inputs `bc/aac.bc bc/AudioRender.bc STAudioInterCom.bc` as normal `.a` libraries.   It helps to have a non-LTO build configuration for debugging situations like this.

**Comment by yangfangfang1204** [comment]
Are there any problems or risks if compile the project links this way"tools.shared.Building.emcc(file, emcc_args + Include_files , os.path.join('obj', arrs[-1]))"？

**Comment by sbc100** [comment]
Yes, huge risk, you are import python files that are internal to the compiler.    Indeed, that function is now completely removed on emscripten `main` branch so it not an option.

I'm confused, what build system is using `tools.shared.Building.emcc`?    I would love to correct the issue if there is a build system out there using that method.   The Makefile you posted above seem to invoke the compiler in the normal way so there is no problem there.

**Comment by yangfangfang1204** [comment]
What's the difference between the .bc file and .a file  generated by the Makefile?

**Comment by sbc100** [comment]
`.bc` normally indicates an object file in bitcode format.   emscripten in that past used to recommend this format and this extensions but we don't anymore.   Today we prefer `.o` like other compilers.

`.o` is an ar archive produced by the `ar` tool (or `emar` in the case of emscripten).  Its kind of like zip file full of `.o` files and its the common way to combine object files.   

The `.bc` files you have might be combined bitcode object files.  emscripten can link smaller object files into a single large one with `emcc -r` (similar to `ld -r` on native platforms).  However, standard `ar` archives are preferred/recommended/better tested these days.
