### ISSUE TITLE
C++20 Coroutines support? 

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#13947]
Is the support for C++20 coroutines planned?

**Comment by sbc100** [comment]
I don't know a lot about C++20 coroutines but I hear they are stackless (in that they don't depend on manipulating the stack, but keep all needed data on the heap).   If that is that is true then they should just work, assuming that they are supported by libc++ and clang.   Have you tried using them?

**Comment by jeffRTC** [comment]
@sbc100  I didn't. Good to know. I am going to try and reopen this issue if they are not working.
