### ISSUE TITLE
[QUESTION] How to restrict exported symbols in final wasm file.

### ISSUE THREAD

**Issue by AlexanderSerov** [emscripten-core/emscripten#13968]
1) We have an external library which exported symbols using EMSCRIPTEN_KEEPALIVE and compiled like so:
```
emcc -O3 -std=c++14 -Wno-ignored-attributes -s ALLOW_MEMORY_GROWTH=1 -s STANDALONE_WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -c -o lib.bc lib.cc
```
As you can see, we get .bc file as output. We also can't affect lib sources and remove KEEPALIVE macro.

2) We have clinet code represented by main.cpp which use symbols exported by library above. We compile it independently from above lib to .bc file also with exactly the same options to emcc. We have some EXPORTED_FUNCTIONS=['func_a', 'func_b'] here

3) Link all together to final.wasm:
```
emcc -O3 -std=c++14 --no-entry -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s STANDALONE_WASM=1 -s ALLOW_MEMORY_GROWTH=1 -o final.wasm lib.bc main.bc
```

The problem is in final.wasm we have symbols stuck out from both lib.bc and main.bc. But we need only from main.bc(func_a', 'func_b') and don't expose symbols from lib.bc in final application.

**Comment by sbc100** [comment]
We don't provide any way to override that `EMSCRIPTEN_KEEPALIVE` in your input files.

If you are producing just a standalone wasm file that easiest way to remove the resulting exports would be to  `wasm2wat` + `wat2wasm` and modify the `.wat` files (either by hand or with script).   You would simply remove the exports, and then if you want to further reduce codesize you could then run `wasm-opt` to mop up any now-unused stuff.

**Comment by sbc100** [comment]
BTW, the first command you list is building an object file so `.o` would be better extension.  The extension `.bc` is little misleading.

Also since you are just compiling an object file you don't need any of these flags since they only apply to linking: 
`-s ALLOW_MEMORY_GROWTH=1 -s STANDALONE_WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0`
