### ISSUE TITLE
⚠ WebAssembly.instantiate(): Import #2 module="GOT.mem" error: module is not an object or function

### ISSUE THREAD

**Issue by danbugs** [emscripten-core/emscripten#13964]
Hi! 

I've ran into the error in the title (`WebAssembly.instantiate(): Import #2 module="GOT.mem" error: module is not an object or function`) and I'm having trouble fixing it — any help is appreciated!

For more info, I'm compiling two `.cpp` files like so:
`emcc side_module_system_functions.cpp validate.cpp -s SIDE_MODULE=2 -O1 -o validate.wasm`

Inside my `.cpp` files, I've marked the functions I want to export with `EMSCRIPTEN_KEEPALIVE`

In JS, I'm instantiating the WASM module like so:
```
let moduleMemory = null;
let moduleExports = null;
// ...
    moduleMemory = new WebAssembly.Memory({initial: 256});

    const importObject = {
        env: {
            __memory_base: 0,
            memory: moduleMemory
        }
    };

    WebAssembly.instantiateStreaming(fetch("validate.wasm"), importObject).then(result => {
        moduleExports = result.instance.exports;
    })
// ...
```
What could be causing the problem?

**Comment by sbc100** [comment]
You probably want to be using `STANDALONE_WASM` rather than `SIDE_MODULE` if you want to try to load the wasm module yourself without using emscripten-generated JS.

`SIDE_MODULE` builds in PIC mode and is designed for dynamic linking which is more complicated of an ABI.

Is there some reason you don't want to use the emscripten-generated JS code?

**Comment by danbugs** [comment]
Thanks for the quick reply!

> Is there some reason you don't want to use the emscripten-generated JS code?

**Just for fun! I'm trying to see if I can get by without emscripten-generated JS and making my own malloc and free implementations.**

Anyway, using `STANDALONE_WASM` worked but my memory management seems to have collapsed as consequence. When passing strings to my C++ it receives `NULL` now, could this have been caused from changing to `STANDALONE_WASM`?

For reference, here's how I'm copying strings to memory (in JS):
```
function copyStringToMemory(value, memoryOffset) {
  const bytes = new Uint8Array(moduleMemory.buffer);
  bytes.set(new TextEncoder().encode((value + "\0")), memoryOffset);
}
```

... and here's how I'm retrieving strings from memory (in JS):
```
function getStringFromMemory(memoryOffset) {
  let returnValue = "";

  const size = 256;
  const bytes = new Uint8Array(moduleMemory.buffer, memoryOffset, size);
  
  let character = "";
  for (let i = 0; i < size; i++) {
    character = String.fromCharCode(bytes[i]);
    if (character === "\0") { break;}
    
    returnValue += character;
  }

  return returnValue;
}
```

For example, if I say something like:
```
const namePointer = moduleExports.create_buffer((name.length + 1)); // create_buffer is my own malloc
copyStringToMemory("Hello, World", namePointer):
```

Now, I can say:
```
console.log(getStringFromMemory(namePointer);
```

... and that outputs `Hello, World` to the console!

Problem is, if I pass this `namePointer` as a parameter to one of my C++ functions, it's received as `NULL`. Any clue why that is? If  the problem is the use of `STANDALONE_WASM` instead of `SIDE_MODULE`, how could I get `SIDE_MODULE` to work?

**Comment by kripken** [comment]
One difference in standalone mode is that there is an exported `_start` method. Your custom loading code should call that, or any global initialization in your malloc will not happen.

**Comment by danbugs** [comment]
Ooo, I think you might have cracked it! 

However, just to be clear, my code does not have an entry point. I'm currently compiling like this: `emcc side_module_system_functions.cpp validate.cpp -O1 -o validate.wasm --no-entry`. All I'm doing is exposing my custom `malloc`/`free` functions and my normal logic (`ValidateName`, and `ValidateCategory`) in `validate.cpp`. Would I still have an exported `_start` method? I've tried calling it like:
``` 
// ...
  WebAssembly.instantiateStreaming(fetch("validate.wasm"), importObject).then(result => {
    moduleExports = result.instance.exports;
    moduleExports._start();
  });
// ...
```

... and that didn't work. Am I calling incorrectly? Also, I've tried calling it without the prefix underscore 'cause all my other functions exported without it and that didn't work either (not sure when functions export with or without it <- clarification would be appreciated 😅)

(ps. I do have global variables in my `side_module_system_functions.cpp` file that contains my custom `malloc` like:
```
// ...
  const int TOTAL_MEMORY = 65536;
  const int MAXIMUM_ALLOCATED_CHUNKS = 10;
  int current_allocated_count = 0;
// ...
```
... are you saying these are not being initialized?)

**Comment by sbc100** [comment]
If you don't have an entry point then you should call `exports._initialize` instead.   All `STANDALONE_WASM` modules should export either `_start` (which calls initialize then main) or just `_initialize` (which just does initialization).  Calling any other export before calling `_initialize` is undefined behaviour.

Static data such as `const int TOTAL_MEMORY = 65536;` doesn't need any startup code but other parts of libc may do.

Please do try use STANDALONE_WASM for these kinds of experiments rather than mis-using SIDE_MODULE (which is disigned for module that load alongside a MAIN_MODULE).

**Comment by sbc100** [comment]
Here is the ABI document that STANDALONE_WASM builds should be conforming to: https://github.com/WebAssembly/WASI/blob/main/design/application-abi.md

**Comment by danbugs** [comment]
Thanks for the document, @sbc100!

Out of curiosity, what is `_initialize` initializing? I've managed to call it but I'm still not getting desired behavior 🤔 (i.e., still receiving `NULL` on the C++ side of things)

Anything else I could try?

**Comment by sbc100** [comment]
`_initialize` calls any static constructors in your program.  It could well be that you don't have any, but certainly anything but tiny programs its important to run it:  See: https://github.com/emscripten-core/emscripten/blob/936046f9af825e05f86b8db5149c60dc8f2cfb2a/system/lib/libc/crt1_reactor.c#L10

**Comment by danbugs** [comment]
Yeah, I don't have any static constructors so I'm not surprised nothing changed 🤔

Thanks for the suggestion, though — I'll definitely keep it in mind for my "non-experiments"

**One more question,** I have this same code compiled from _2019_ to a `.wasm` with `emcc side_module_system_functions.cpp validate.cpp -s SIDE_MODULE=2 -O1 -o validate.wasm` and... It works! Is there any way I could use the old `.wasm` to figure out why this one isn't working?

**Comment by sbc100** [comment]
With `STANDALONE_WASM` the memory object is exported from the module as memory.  So I think you need to do something like `moduleMemory = moduleExports.memory` .. otherwise you are not sharing a memory with the same module so it makes sense that all strings would be NULL I guess :)

**Comment by danbugs** [comment]
Yep — that did it! Thank you so so much, @sbc100 and @kripken! You two are awesome ;D

~ closing the issue!
