### ISSUE TITLE
⚠ WebAssembly.instantiate(): Import #0 module="env" function="UpdateHostAboutError" error: function import requires a callable

### ISSUE THREAD

**Issue by danbugs** [emscripten-core/emscripten#13977]
I'm trying to pass a JS function via an `importObject` to my `.cpp` file but I'm getting the error in the title (i.e., WebAssembly.instantiate(): Import #0 module="env" function="UpdateHostAboutError" error: function import requires a callable).

Here's my `importObject`:
```
// ...
  moduleMemory = new WebAssembly.Memory({initial: 256});

  const importObject = {    
    env: {
      __memory_base: 0,
      memory: moduleMemory,
      _UpdateHostAboutError: function(errorMessagePointer) {
        setErrorMessage(getStringFromMemory(errorMessagePointer));
      },
    }
  };
// ...
```

... To access this JS function from my `.cpp`, I am doing this:
```
// ...
    extern void UpdateHostAboutError(const char* error_message);
// ...
```

_Note:_ I'm aware that I could make something like:
```
mergeInto(LibraryManager.library, {
    UpdateHostAboutError: function(errorMessagePointer) {
        setErrorMessage(Module.UTF8ToString(errorMessagePointer));
    }
})
```
... to add this JS to Emscripten's auto-generated JavaScript by compiling with something like `emcc validate.cpp --js-library mergeinto.js -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'UTF8ToString']" -o validate.js`.

Thing is, just for fun, I'm trying to see if I can get by without Emscripten's auto-generated JavaScript!

To compile my current `.cpp`, I did this: `emcc .\side_module_system_functions.cpp .\validate.cpp -O1 -o validate.wasm --no-entry -s ERROR_ON_UNDEFINED_SYMBOLS=0`

_Note:_ I'm using the `ERROR_ON_UNDEFINED_SYMBOLS=0` flag because, without it, I got:
![image](https://user-images.githubusercontent.com/39843321/115832849-39984800-a3c8-11eb-82b4-acc9cd33f6f5.png)

... but, I'm getting a feeling that adding `-s ERROR_ON_UNDEFINED_SYMBOLS=0` was just sweeping stuff under the rug. What's the right way to do what I'm trying to do?

**Comment by sbc100** [comment]
The symbol names imported by the wasm module don't include the extra leading `_` like they do on the JS side.     So removing the leaving `_` in the export code should do it:

```
      UpdateHostAboutError: function(errorMessagePointer) {
        setErrorMessage(getStringFromMemory(errorMessagePointer));
      },
```

You should be able to remove the undefined symbol error by providing that library.js file.. even if you don't actually use the generated JS that symbol resolution will use it to report genuinely-undefined errors.

**Comment by danbugs** [comment]
Alright, removing the leading `_` fixed the error but... I'm not getting my desired behaviour 🤔

> Side question, what is the convention for use of `_`? I usually just figure it out if I have to use it or not by trial and error .-.

Anyway, what I'm trying to do is:

(1) I created this `UpdateHostAboutError` JS function in the module's `importObject` that accepts a function pointer. 
```
// ...
  moduleMemory = new WebAssembly.Memory({initial: 256});

  const importObject = {    
    env: {
      __memory_base: 0,
      memory: moduleMemory,
      UpdateHostAboutError: function(errorMessagePointer) {
        setErrorMessage(getStringFromMemory(errorMessagePointer));
        console.log(errorMessagePointer);
      },
    }
  };
// ...
```

(2) I call it in C++ by providing a string I want to display in JS:
```
// ...
  extern void UpdateHostAboutError(const char* error_message);
// ...
    UpdateHostAboutError("Hello, World!");
// ...
```

_For reference:_ my `getStringFromMemory` function does the following:
```
function getStringFromMemory(memoryOffset) {
  let returnValue = "";

  const size = 256;
  const bytes = new Uint8Array(moduleMemory.buffer, memoryOffset, size);
  
  let character = "";
  for (let i = 0; i < size; i++) {
    character = String.fromCharCode(bytes[i]);
    if (character === "\0") { break;}
    
    returnValue += character;
  }

  return returnValue;
}
```

I've checked what the value for the `errorMessagePointer` received by `UpdateHostError` is and got `1024` (which is what I was expecting). Problem is, reading from `1024` is yielding an empty string. I don't have this problem when I inject `UpdateHostAboutError` into Emscripten's auto-generated JS like I mentioned in my previous comment so... What could be the issue?

Also @sbc100, I didn't really understand what you meant with:
> You should be able to remove the undefined symbol error by providing that library.js file.. even if you don't actually use the generated JS that symbol resolution will use it to report genuinely-undefined errors.

Could you please clarify?

**Comment by sbc100** [comment]
If you are using standalone wasm mode (which is the default of you specify `.wasm` as your `-o` output), then the memory is for the wasm module is created by the module and exported, so you need to read your `moduleMemory` from the exports object.

The `_` convention is legacy thing due to the fact the the old fastcomp compiler user to prepend `_` to all native symbols.   These days we maintain the convention in emscripten-generated JS for compatabiliy, so all native symbols on the JS side show up with a leading `_` (include the native symbols implemented in JS itself in the library code).

I believe the origin for the `_` prefix comes from Microsofts `cdecl` convention which mangles C symbols with leading underscore.

**Comment by danbugs** [comment]
> If you are using standalone wasm mode (which is the default of you specify .wasm as your -o output), then the memory is for the wasm module is created by the module and exported, so you need to read your moduleMemory from the exports object.

When I'm instantiating the module, I do:
```"
// ...
  WebAssembly.instantiateStreaming(fetch("validate.wasm"), importObject).then(result => {
    moduleExports = result.instance.exports;
    moduleExports._initialize();
    moduleMemory = moduleExports.memory;
  });
// ...
```

... and, in the `getStringFromMemory` function, I'm using my `moduleMemory.buffer`:
```
// ...
  const bytes = new Uint8Array(moduleMemory.buffer, memoryOffset, size);
// ...
```

Is that not how I should be reading my `moduleMemory`? 

Also, thanks for the info on the prefix underscore — That little `_` always had me curious ;D

**Comment by sbc100** [comment]
Yup.   Did `moduleMemory = moduleExports.memory;` fix your issue?

**Comment by sbc100** [comment]
You also don't need to export `__memory_base` to standalone modules.. that is for dynamic linking.

**Comment by danbugs** [comment]
> Yup. Did moduleMemory = moduleExports.memory; fix your issue?

Nop — I had it like that from the beginning (learned my lesson from #13964 haha)

> You also don't need to export __memory_base to standalone modules.. that is for dynamic linking.

Ooo, that's right — removed it! I'm not sure if that made much of a difference either, though 😅

Can you think of any other reasons for why the string might come out as empty? I'm kind of at a loss .-.

**Comment by sbc100** [comment]
I can't see anything obvious no.

Is errorMessagePointer pointing to 1024 because its static C string at the start of the static data region?   If so, it should be clear from wasm-objdump that that string lives a that address.  If that is true then you must have some kind of bug in getStringFromMemory, but its not obvious to me what it is.

**Comment by danbugs** [comment]
Yeah, it's just a static C string that I pass directly to the function. Thing is, I don't think there's a bug with `getStringFromMemory` because it works just fine when I inject `UpdateHostAboutError` into Emscripten's auto-generated JS 🤔

From my `wasm-objdump` disassemble output, you can see:

```
// ...
00035a func[5] <ValidateName>:
 00035b: 41 80 08                   | i32.const 1024
 00035e: 10 00                      | call 0 <env.UpdateHostAboutError>
 000360: 41 00                      | i32.const 0
 000362: 0b                         | end
// ...
```
... which I think confirms it lives at that address.

**Comment by sbc100** [comment]
Sounds like maybe you have the wrong memory object... can you dump the contents of memory when your first receive it an check the that the string exists at 1024.

**Comment by danbugs** [comment]
**I have some new info!** It mostly just made me more confused but perhaps it might spark an idea over there 😅

I'm not sure if I mentioned this before but my `UpdateHostAboutError` JS function gets called by one of my C++ exported functions (i.e., `ValidateName`). Here it is:

```
// ...
#ifdef __EMSCRIPTEN__
  EMSCRIPTEN_KEEPALIVE
#endif
  int ValidateName(char *name, int maximum_length)
  {
    // Validation 1: A name must be provided
    if ((name == NULL) || (name[0] == '\0'))
    {
      UpdateHostAboutError("Error #1");
      return 0;
    }

    // Validation 2: A name must not exceed the specified length
    if (strlen(name) > maximum_length)
    {
      UpdateHostAboutError("Error #2");
      return 0;
    }

    // Everything is ok (no issues with the name)
    return 1;
  }
// ...
```

For reference, here's how I'm calling `ValidateName` from the JS side:

```
function validateName(name) {
  const namePointer = moduleExports.create_buffer((name.length + 1)); // this is like `malloc`
  copyStringToMemory(name, namePointer); // see below for implementation

  const isValid = moduleExports.ValidateName(namePointer, MAXIMUM_NAME_LENGTH);
  moduleExports.free_buffer(namePointer); // this is like `free`

  return (isValid === 1);
}
```

Here's the `copyStringToMemory` function:

```
function copyStringToMemory(value, memoryOffset) {
  const bytes = new Uint8Array(moduleMemory.buffer);
  bytes.set(new TextEncoder().encode((value + "\0")), memoryOffset);
}
```

Anyway, I've discovered that the reason I was getting an empty string at the JS side is because I'm actually, somehow, retrieving the user input. That is, when I provide an empty string expecting it to fall under the `if` statement for validation 1 returning `Error #1`, I'm getting `\0` instead. Equally, if I provide a string larger than `maximum_length`, instead of getting `Error #2`, I'm getting whatever large string I entered. How is it possible that, even though I'm specifically passing `Error #1`/`Error #2` to `UpdateHostAboutError`, it is accessing the address of `name` from the parameter list? 

Also, funny enough, if under the `if` statement for validation 1 I do:
```
// ...
    // Validation 1: A name must be provided
    if ((name == NULL) || (name[0] == '\0'))
    {
      char* return_error_message;
      strcpy(return_error_message, "This is a test!");
      UpdateHostAboutError(return_error_message);
      return 0;
    }
// ...
```

... at the JS side, I get `Error #2` when giving input that falls under this validation error 🤣

**Comment by danbugs** [comment]
> Sounds like maybe you have the wrong memory object... can you dump the contents of memory when your first receive it an check the that the string exists at 1024.

@sbc100 ~ At this risk of sounding dumb, I have to ask... How can I dump the contents of memory like that? 😅

**Comment by danbugs** [comment]
> At this risk of sounding dumb, I have to ask... How can I dump the contents of memory like that? 😅

@sbc100 ~ Using my `getStringFromMemory` to get all strings from `1024` up to `256` (my module's initial memory size) and print to the console, I get:

![image](https://user-images.githubusercontent.com/39843321/115938300-ff25be00-a44e-11eb-980a-fcf782616acc.png)

I'm not sure if it was the dump you meant but, regardless, it serves to show my memory is messed up haha

(ps. If you can, I'd still love to know if there's a proper way to dump my memory's content and display it all, though — should come handy in the future!)

**Comment by sbc100** [comment]
I don't know if there is some proper way.  I would have thought that `console.log()` of the buffer would show you the bytes?   For sure in devtools you can see the whole thing.

wasm-objdump -x will show you the memory in a hexdump of the binary from the command line too.   You should see the same bytes in there obviously.

**Comment by danbugs** [comment]
Alright, in the end, I just made a little function that will display all the strings in memory:

```
// ...
function displayAllStringsInMemory (offset = 0) {
  console.log(getStringFromMemory(1024 + offset) + "\n");
  if(getStringFromMemory(1024 + offset) === ""){
      return;
  }
  return displayAllStringsInMemory(offset + getStringFromMemory(1024 + offset).length + 1);
}

function getStringFromMemory(memoryOffset) {
  let returnValue = "";

  const size = 256;
  const bytes = new Uint8Array(moduleMemory.buffer, memoryOffset, size);
  
  let character = "";
  for (let i = 0; i < size; i++) {
    character = String.fromCharCode(bytes[i]);
    if (character === "\0") { break;}
    
    returnValue += character;
  }
// ...
```

For project's using Emscripten's auto-generated JS, the equivalent would be:
```
function displayAllStringsInMemory (offset = 0) {
    console.log(Module.UTF8ToString(1024 + offset) + "\n");
    if(Module.UTF8ToString(1024 + offset) === ""){
        return;
    }
    return displayAllStringsInMemory(offset + Module.UTF8ToString(1024 + offset).length + 1);
}
```

My guess is that `UpdateHostAboutError`' s use without Emscripten's auto-generated JS Code is somehow leaking my memory. For a visual, here is my memory state from a couple of test runs:
![image](https://user-images.githubusercontent.com/39843321/115944897-939f1900-a46d-11eb-90e0-23524f7cb9f5.png)

... and, here's using Emscripten's auto-generated JS with the same runs:
![image](https://user-images.githubusercontent.com/39843321/115945029-6868f980-a46e-11eb-90e3-57f1c4f5a685.png)

I'll close the issue 'cause the initial problem is fixed but, if anyone has any clues how to fix this secondary problem, I'd still appreciate some input 😅

Thanks @sbc100 for all the help!
