### ISSUE TITLE
Undefined reference with ALLOC_NORMAL

### ISSUE THREAD

**Issue by ITotalJustice** [emscripten-core/emscripten#14000]
Hi, it seems this value gets removed when compiling with optimisations (`-O3`), as with `-O0` it works fine.

This is my build config:

```
emcc *.cpp -O3 -lidbfs.js -o index.html --shell-file test.html -s FORCE_FILESYSTEM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'allocate']" -s EXPORTED_FUNCTIONS="['_main', '_malloc', _free]"
```

The code i was testing this with is here <https://gist.github.com/ITotalJustice/8ce95ef8644e3c7d2bc0e67be46320ca#file-input-html-L39>

Passing 0 instead of the `ALLOC_NORMAL` will work, which is what i do for now.

**Comment by ITotalJustice** [comment]
I noticed that in the docs that it's mentioned that it's not recommend to use allocate, and instead use _malloc, so ive created a version that uses malloc, which works great!

```js
let name_array = intArrayFromString(input.files[0].name);

var data_ptr = _malloc(data.length * data.BYTES_PER_ELEMENT);
var name_ptr = _malloc(name_array.length * name_array.BYTES_PER_ELEMENT);
HEAPU8.set(data, data_ptr);
HEAPU8.set(name_array, name_ptr);
```

while not related to the issue, is this the correct way of setting the entire array by using the `HEAPU8.set` as a kind of `memset`? I see that the docs say to use SetValue, but i assume that only sets one value at a time?

**Comment by sbc100** [comment]
Yup, I was going to say.. just use `_malloc` here.

And yes I think your usage of `HEAPU8.set` is correct.

**Comment by sbc100** [comment]
If that works maybe we can close this issue?

**Comment by ITotalJustice** [comment]
> If that works maybe we can close this issue?

Yep I’m happy with that, thanks for your help
