### ISSUE TITLE
Is pre-js the correct way to embed JS that can be called from the C ++ side?

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#14008]
I have a case where I don't want to write a library instead I want to have the JS function available for em_val calls. So that I can catch exceptions. I found about the pre-js option in emcc but It's unclear whether it's the right option for my task. 

I need the function to be either global or local so I can use it like this,

`emscripten::val::global("myfunction")
`                  

`emscripten::val::module_property("myfunction")
`
Obviously, I can include the code by hand but I pretty much would like to do it automatically by emcc itself. 

Any thoughts?

**Comment by kripken** [comment]
The main issue is optimization. If you access it via `"myfunction"` as a string like that, then the function's name can't be minified (the minified name might be "a" for example). So you should *not* use a pre-js (or JS library), as they include that JS with the rest of the code that is minified. Instead you can include the code using an extern-pre-js, or by hand.

**Comment by jeffRTC** [comment]
@kripken  it works. 

Interesting that val's global can't find the function if I define function under const or let.
