### ISSUE TITLE
CMake find_package fails for Emscripten Ports libraries

### ISSUE THREAD

**Issue by ericoporto** [emscripten-core/emscripten#14003]
I am using SDL2 from Emscripten Ports and I noticed `find_package(SDL2)` will fail with it. For now I just skip it when using Emscripten with `-s USE_SDL=2`, and go on ~~since `SDL2_LIBRARIES` will be filled with the right values for it~~ actually this value is not filled but somehow it works?. But I am curious, is there a way to make Emscripten emcmake cmake satisfy a `find_package(SDL2 REQUIRED)`, so I don't need to figure a way to skip it?

I think something like generating a proper `sdl2-config.cmake` with just set SDL2_LIBRARIES and SDL2_INCLUDES in it would work.

**Comment by ericoporto** [comment]
I think the right way to solve this is to generate a `FindSDL2.cmake` file with a content like:

```CMake
SET(SDL2_FOUND TRUE)
set(SDL2_INCLUDE_DIRS "${EMSCRIPTEN_ROOT_PATH}/system/include" "${EMSCRIPTEN_ROOT_PATH}/system/include/SDL2/")
set(SDL2_LIBRARIES "nul")

mark_as_advanced(SDL2_LIBRARY
	SDL2_RUNTIME_LIBRARY
	SDL2_INCLUDE_DIR
	SDL2_SDLMAIN_LIBRARY)
```

But instead of system it's the `sysroot` in `emsdk/upstream/emscripten/cache/sysroot` maybe? I don't the right variable, it's not `EMSCRIPTEN_ROOT_PATH` I think. This file has to be generated by [`tools/ports/sdl2.py`](https://github.com/emscripten-core/emscripten/blob/main/tools/ports/sdl2.py) but it doesn't appear to have enough context to do so at this time.

Similar files must be created by other builds from Emscripten Ports.

**Comment by sbc100** [comment]
I think you are the on the right track.  Certainly you want to be using the `sysroot` rather than `system` directory these days.

Did this used to for you in past?  (i.e. did I break something with my sysroot change?)

**Comment by ericoporto** [comment]
SO IT WAS YOU! just joking, no, it didn't change anything for me, it's all working :)

I think I got something working for me, should I try to PR for everything or just SDL2 for now?

**Comment by sbc100** [comment]
I wonder if you can make this work with the official upstream sdl2 cmake file? (which i imagine is based on the pkgconfig file?)

**Comment by ericoporto** [comment]
Can you elaborate? Current SDL2 port is built by a weird python script instead of the original SDL2 `CMakeLists.txt`. 

I don't understand exactly how the linking in an application project (my application that uses both ports and other libraries) happens but apparently either everything is linked with everything or the linking happens at runtime, because I don't need to manually add SDL2 for linking when using `-s USE_SDL=2`.

The problem I am trying to solve here is I have other upstream libraries in use that I can't modify, that uses find_package(SDL2) (even though it's not needed), and they will fail to build because finding SDL2 will get nothing.

**Comment by sbc100** [comment]
I'm saying that whatever SDL2 normally installs to make `find_package(SDL2)` .. we should also install that (it might be cmake fragment and/or a pkg-config file).   Hopefully we can make our build of SDL2 locatable in the normal way even though we don't use the SDL2 build system.

**Comment by sbc100** [comment]
We so already include the sdl2-config file.   I would hope that `find_package(SDL2)` would use it.    I've got a PR open to move that file to the correct location: https://github.com/emscripten-core/emscripten/pull/14029

**Comment by ericoporto** [comment]
> (I tried sdl2-config.cmake but it didn't work for whatever reason, so Find is the way to go)

I don't really see `sdl2-config.cmake` on your PR, but when I tried it didn't work with the `emcmake cmake`

**Comment by sbc100** [comment]
Sorry, `sdl2-config` is an executable .. its not cmake-specific.   Its designed to run by build systems e.g. `sdl2-config --cflags` will list the cflags needs to use sdl2.   I would have imagined that `FindSDL2.cmake` would run `sdl2-config` under the hood but I've not looked into it.

**Comment by ericoporto** [comment]
There's no "official" `FindSDL2.cmake`, that's why I am writing one: https://github.com/Kitware/CMake/pull/149

`sdl2-config` executable is not used at any point.

**Comment by ericoporto** [comment]
this is still broken but it's fixed particularly for SDL2 case, so I am closing this.
