### ISSUE TITLE
Drawing text with OPENGL & SDL_ttf as texture 

### ISSUE THREAD

**Issue by omar1990** [emscripten-core/emscripten#1401]
I can not adapt my code which  use OpenGL and SDL_ttf  to draw a text as texture  with emscripten .
Here  is my code::
GLuint Bouton::creerTextureTexte(std::string texte)
{
    glEnable( GL_TEXTURE_2D );
    // Chargement de la police du bouton
    TTF_Font\* police = TTF_OpenFont("angelina.ttf", 20);

```
if (NULL == police)
{
    printf("Impossible de charger le fichier Cartonsix NC.ttf");
}

// Creation de l'image du texte avec la police associee
SDL_Color couleurTexte = {0, 0, 0};
SDL_Surface* texteBouton = TTF_RenderText_Blended(police, texte.c_str(), couleurTexte);
if (NULL == texteBouton)
{
    printf("Impossible de créer le texte du bouton");
}

// Liberation de la police
TTF_CloseFont(police);
SDL_SetAlpha(texteBouton, 0, 0);
// Activation de la transparence
glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);



// Generation de la texture pour le texte du bouton
GLuint textureTexte;
glGenTextures( 1, &textureTexte );

// Selection de la texture generee
glBindTexture( GL_TEXTURE_2D, textureTexte );

// Parametrage
glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR );
glTexParameteri( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR );

// Detection du codage des pixels
```

   GLenum codagePixel;
    if (texteBouton->format->Rmask == 0x000000ff)
    {
        printf("text 1 \n");
        codagePixel = GL_RGBA;
    }
    else
    {
        #ifndef GL_BGRA
            #define GL_BGRA 0x80E1
        #endif
        printf("text 2 \n");
        codagePixel = GL_BGRA;
    }

```
this->hauteurTexte = texteBouton->h;
this->largeurTexte =texteBouton->w;

// Chargement de la texture du texte precedament creee
glTexImage2D( GL_TEXTURE_2D, 0, texteBouton->format->BytesPerPixel, texteBouton->w, texteBouton->h, 0,
              codagePixel, GL_UNSIGNED_BYTE, texteBouton->pixels );


// Liberation de l'image du texte du bouton
SDL_FreeSurface( texteBouton );
glDisable( GL_TEXTURE_2D );

return textureTexte;
```

}

**Comment by GPMueller** [comment]
> 
> 
> it shows me a black rectangle.. :( ok i will try

Same for me. Looking at the pixel data, it's all just `0`s...

[These bindings](https://github.com/emscripten-core/emscripten/blob/053198dd1048217793d0acfcf23606c2867cc8f7/src/library_sdl.js#L3186-L3208) seem strange to me - I hope this will be fixed at some point, since it seems to make text rendering the usual pain again.
