### ISSUE TITLE
Help diagnosing "Aw Snap!" error on Chrome Mobile

### ISSUE THREAD

**Issue by ericoporto** [emscripten-core/emscripten#14013]
I have a rather complex code that works fine everywhere, including Chrome Mobile on Android, when compiled with Emscripten version 2.0.16 (`./emsdk activate 2.0.16`).

But when using the latest Emscripten, while the code has a huge performance improvement, it occasionally gives me a `Aw Snap!` crash on Chrome Mobile on Android. This error doesn't happen on Firefox mobile on Android or Chrome desktop.

I used Chrome DevTools to connect to the phone through USB and monitor memory and other things, but there's nothing that is visible there as something different from 2.0.16 and once the crash happens the connection with the device is lost.

Is there any way to diagnose what could possibly be causing this? For now I am building with 2.0.16 since it works but I would love to upgrade to newer Emscripten and benefit from the performance improvements that seems to have been made.

**Comment by ericoporto** [comment]
ok, figured. 

For reference if someone needs this:

- using adb and logcat, you should see at least a FATAL crash on it. You may be able to solve your problem by using logcat alone too.
- If it's not the case, after the crash, submit the crash report by going to chrome://crashes/
- pickup the crash id and report on crbug.com
- alternatively you need debug symbols for chrome itself to figure what happened

**Comment by ericoporto** [comment]
The chrome "Aw Snap!" screen changed and additionally I can't figure out how to read debug data from Chrome Mobile currently. Current Emscripten still generates code that occasionally crashes Chrome on Mobile - but not on Desktop.

**Comment by sbc100** [comment]
Can you provide more information and / or a repro case?   The most useful thing would probably be the full command line used to link your module (so we can see what settings you are using).

**Comment by ericoporto** [comment]
I can tell that there's a build here: https://ericoporto.github.io/agsjs/single_game/

Usually around a minute or two with that tab open walking around it crashes the tab on Chrome Mobile. This doesn't affect Firefox or other mobile browsers, and doesn't seem to affect any desktop browser. So **it feels like more a bug in Chrome Mobile** than anything else.

The code that built the website is from this branch: https://github.com/ericoporto/ags/tree/emscripten

From this line on in the CMakeLists.txt are the lines: https://github.com/ericoporto/ags/blob/ff221bc20984c8162d8b84c447b2b49676bf7f64/CMakeLists.txt#L114

Build log is here: https://cirrus-ci.com/task/6704388788977664

**Comment by sbc100** [comment]
Could you help us out by providing the full link command so we can see all the settings you are using (simply re-linking the project should be enough).  (I know we can derive that by checking out and building your project its easier if you can provide that kind of thing up front so we can know, for example:  "are you using threads?",  "are you using exceptions?", etc).

**Comment by ericoporto** [comment]
I think these are the asked build and link flags:

`CMAKE_CXX_FLAGS:   -sUSE_SDL=2  -sUSE_FREETYPE=1  -sUSE_VORBIS=1  -sUSE_OGG=1           -O3         -s DISABLE_EXCEPTION_CATCHING=0`

`CMAKE_C_FLAGS:   -sUSE_SDL=2  -sUSE_FREETYPE=1  -sUSE_VORBIS=1  -sUSE_OGG=1           -O3         -s DISABLE_EXCEPTION_CATCHING=0`

`CMAKE_EXE_LINKER_FLAGS:   -sUSE_SDL=2  -sUSE_FREETYPE=1  -sUSE_VORBIS=1  -sUSE_OGG=1          -s ALLOW_MEMORY_GROWTH=1          -s ASYNCIFY         -s ALLOW_TABLE_GROWTH=1         -s WASM=1         -s INVOKE_RUN=0 		-s EXIT_RUNTIME=1  		-s EMULATE_FUNCTION_POINTER_CASTS=1          -s FULL_ES2=1         -s FORCE_FILESYSTEM=1 -lidbfs.js          -s EXPORTED_FUNCTIONS=['_main']         -s EXTRA_EXPORTED_RUNTIME_METHODS=['ccall','callMain'] --shell-file /tmp/cirrus-ci-build/Emscripten/launcher_index.html `

I am not using Threads. I do am using exceptions!

**Comment by sbc100** [comment]
Thanks!

The only option that looks like it could cause something like this is `ALLOW_TABLE_GROWTH`.   Do you have a build you can do which operates on the fixed amount of memory instead?   If that makes the problem go away that would be quite a big clue.

Also, I wonder if there is some information you/we can get from the chromium crash report.  Do you have crash reporting enabled?  Does the crash show up in chrome://crashes?

**Comment by ericoporto** [comment]
> The only option that looks like it could cause something like this is ALLOW_MEMORY_GROWTH. Do you have a build you can do which operates on the fixed amount of memory instead?

I tried to do that here: https://ericoporto.github.io/agsjs/single_game_nogrowth/ 

But it still crashes.

> Also, I wonder if there is some information you/we can get from the chromium crash report. Do you have crash reporting enabled?

I turned it on, and clicked "Send now", but it's still greyed out. I don't know other  way to pickup them up from my phone. :/

**Comment by ericoporto** [comment]
Chrome issue talks about huge functions. What does it means by that? How huge are we talking about? 

I am curious why the same codebase doesn't cause Chrome Mobile to trigger this bug when building in old Emscripten (around 2.0.16) but does so in current Emscripten. Is this something that should be possible to inspect using something like bloatly?

**Comment by faerot** [comment]
Same problem here, Emscripten 3.1.3 makes Chrome on Android crash pretty fast, had to revert to 2.0.16 to make the game playable. ALLOW_MEMORY_GROWTH=0  did not help, triggering on and off lto didn't help either.

**Comment by ericoporto** [comment]
It appears something in Emscripten now triggers some unsupported Emscripten code in Chrome.

In my case I noticed disabling LTO reduced the time it takes for it to crash for OOM in Chrome, but it does still eventually crashes - it's curious that up to the crash I am at most using like 3 MB ram. Also disabling LTO **reduced** the size of my WASM code with zero performance penalty.

Anyway, if you can, try Chrome Canary (the next release), there is a fix in Chrome versions above 100 that seems to fix the case I was experiencing. It's this one: https://chromium.googlesource.com/v8/v8/+/ed1cd8f10505c2d8da0d9f896e7589b1299dc95b

I still believe something at some point broke in Emscripten though, since it should not output different size functions from the same codebase.

**Comment by faerot** [comment]
Build command for me is something along these lines: emcc ems_index.cpp -O3 -g2 -s "DISABLE_EXCEPTION_CATCHING=0" -DNDEBUG -std=c++11 --bind -flto^
 -Wno-switch -Wno-parentheses^
 -s TOTAL_MEMORY=128MB^
 -s ALLOW_MEMORY_GROWTH=0^
 -s EXPORTED_FUNCTIONS=['_main','_process_fetch_response']^
 -s EXPORTED_RUNTIME_METHODS=['ccall']^
 -s EXIT_RUNTIME=1^
 -s USE_ZLIB=1 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_LIBJPEG=1 -s SDL2_IMAGE_FORMATS=["png","jpg"]^
 -lwebsocket.js -s WEBSOCKET_SUBPROTOCOL="binary"^
 -lidbfs.js^
 --no-heap-copy^
...
 -o main.html

**Comment by ericoporto** [comment]
@faerot can you try:

- does it reproduces with Google Chrome Canary?
  - https://play.google.com/store/apps/details?id=com.chrome.canary
- can you remove `-flto` and see if it still happens on current chrome?

**Comment by ITotalJustice** [comment]
i believe i am having the same issue as described, not really sure how to start debugging this however.

i am building my gba emulator for the web, its worked fine for a while now. i recently added a few backends for the interpreter a `switch` and a `computed goto` version. the default before was LUT (lookup table).

when i switched to the `switch` version, my emulator instantly crashed showing the "Aw Snap!" error whenever the game i was emulating used arm mode (meaning it used this giant switch statement) <https://github.com/ITotalJustice/notorious_beeg/blob/d10c7c4f0e29c60ced328f49fdad0744c30b53b0/src/core/arm7tdmi/arm/arm_switch.cpp#L38>.

this function is huge, and all the functions inside get completely inlined.
> Chrome issue talks about huge functions. What does it means by that? How huge are we talking about?
maybe this is the issue here?

this only happens in mobile chrome based browsers. it works on mobile firefox and safari on ios. as well as on desktop and all popular browsers on desktop. i've opened an issue about it here as well <https://github.com/ITotalJustice/notorious_beeg/issues/89>. i've "fixed" this on my end by using a LUT instead of the giant switch when building for web.

**Comment by ericoporto** [comment]
Hey, I forgot to close this. The issue I had was in Chrome and it was closed and merged since Chromium 100. @ITotalJustice which chrome release are you using? It should work fine in Firefox if it's the same issue and in recent chrome releases too.

**Comment by ITotalJustice** [comment]
> Hey, I forgot to close this. The issue I had was in Chrome and it was closed and merged since Chromium 100. @ITotalJustice which chrome release are you using? It should work fine in Firefox if it's the same issue and in recent chrome releases too.

oh i see. ive tried chrome `105.0.5195.79` and canary `107.0.5282.0` as well as opera and edge (both are chromium based i believe).

yes it does work fine in firefox mobile.

**Comment by ericoporto** [comment]
hey, this is not fixed it seems, but since it may be a chromium bug instead, I am closing this.
