### ISSUE TITLE
What's the difference between HEAP and makeSetValue()

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14023]
**First:**
In the AlcCaptureSamples module of generated .js file by emcc , the values are copied as follows:
`function setF32Sample(i, sample) {
        HEAPF32[(((pFrames)+(4*i))>>2)] = sample;
 }
function setI16Sample(i, sample) {
      HEAP16[(((pFrames)+(2*i))>>1)] = sample;
}
function setU8Sample(i, sample) {
      HEAP8[(((pFrames)+(i))>>0)] = sample;
}`
**Second:**
In the AlcCaptureSamples module  of the GitHub of emscripten, the values are copied as follows:
`function setF32Sample(i, sample) {
      {{{ makeSetValue('pFrames', '4*i', 'sample', 'float') }}};
 }
 function setI16Sample(i, sample) {
      {{{ makeSetValue('pFrames', '2*i', 'sample', 'i16') }}};
 }
 function setU8Sample(i, sample) {
      {{{ makeSetValue('pFrames', 'i', 'sample', 'i8') }}};
 }`

So ,could you tell me the difference  between HEAP and makeSetValue() ?

And how can I use makeSetValue() ?

**Comment by yangfangfang1204** [comment]
And how can I use makeSetValue()？

**Comment by sbc100** [comment]
`makeSetValue` is a macro that can be used in JS library functions.  I gets run at compile time and generates the HEAP operations.
