### ISSUE TITLE
undefined behavior when calling fcntl(fd, F_GETFL)

### ISSUE THREAD

**Issue by msabwat** [emscripten-core/emscripten#14020]
Hi,

Calling :
```
    fcntl (fd, F_SETFL, fcntl (fd, F_GETFL) & ~O_NONBLOCK);
```
in [this module](https://code.videolan.org/b1ue/vlc/-/blob/master/modules/access/file.c#L188)
will give [a crash](https://code.videolan.org/b1ue/vlc/-/issues/60) if we enable assertions with SAFE_HEAP.

I think this is because of [this line](https://github.com/emscripten-core/emscripten/blob/aa66f92b790c8d319d1599d44657a6305bf74a8a/system/lib/libc/musl/src/fcntl/fcntl.c#L13), if we call va_arg() the argument should normally not be non-existent.

from C11 standard (ISO/IEC 9899:2011) :
```
If there  is  no  actual  next  argument,  or  if type is not compatible with the type of the actual next argument (as promoted according to  the  default  argument  promotions),  the  behavior  is  undefined,  except  for  the  following cases:
—  one type is a signed integer type, the other type is the corresponding unsigned integer type, and the value is representable in both types;
—  one type is pointer to void and the other is a pointer to a character type.
```

I fixed it locally like this :

```
diff --git a/system/lib/libc/musl/src/fcntl/fcntl.c b/system/lib/libc/musl/src/fcntl/fcntl.c
index 2b7c3df2f..cd594c42a 100644
--- a/system/lib/libc/musl/src/fcntl/fcntl.c
+++ b/system/lib/libc/musl/src/fcntl/fcntl.c
@@ -7,6 +7,7 @@
 
 int fcntl(int fd, int cmd, ...)
 {
+    if (cmd == F_GETFL) return syscall(SYS_FCNTL, fd, cmd);
        unsigned long arg;
        va_list ap;
        va_start(ap, cmd);
```

If it is okay, would you agree if I sent it as a PR?

Thanks, 
Regards

**Comment by kripken** [comment]
Interesting, thanks @msabwat ...

Looks like the code is unchanged in newer musl, so they may not consider this undefined behavior to be an issue, or it never caused problems for them: https://git.musl-libc.org/cgit/musl/tree/src/fcntl/fcntl.c Worth raising this issue with them.

The second question is why that's a null pointer. Does the LLVM backend's ABI really put a null pointer if there are no varargs? (as opposed to a non-null pointer referring to an "empty" vector) It seems like it could avoid a null there, which could fix other false positives with `SAFE_HEAP` and ASan etc. Not sure who would know this ABI stuff best, maybe @dschuff ?

**Comment by sbc100** [comment]
Oh wait this is dup of #12433 and the `test_fcntl` test is already disabled for this reason ..   Do you know why this doesn't show up in asan too?

**Comment by sbc100** [comment]
Closing as duplicate of #12433
