### ISSUE TITLE
Why do we require passing -msimd128 when passing -msse and related flags?

### ISSUE THREAD

**Issue by ngzhian** [emscripten-core/emscripten#14032]
Right now, if we pass `-msse` **without** passing `-msimd128` we get a compile error.

`-msse` looks like a clear signal that we should enable SIMD, maybe the presence of `-msse` should enable the `-msimd128` flag?

Seems like @juj added this when implementing the SSE compatibility headers.

**Comment by sbc100** [comment]
I believe this has been discusses at length in the past..  I can't remember exactly why this path was chosen.. but I do think this was the decided on best approach.   

@RReverser and @surma I believe were also involved with the discussion.

**Comment by RReverser** [comment]
Yeah I'm tempted to close this as duplicate of https://github.com/emscripten-core/emscripten/issues/12714 unless @ngzhian thinks this is a separate issue?

**Comment by ngzhian** [comment]
Ah, I should have searched! Thanks!

From that issue:

> While this works fine for Wasm-specific projects, it adds friction to building existing projects relying on SSE intrinsics. For example, CMake checks that try to use those flags, error out by default, and the only ways to fix it are either 1) modify CFLAGS / CXXFLAGS / etc. on the caller side to include -msimd128, which will now affect all targets in CMake and not only those that used -msse2 or 2) selectively modify CMakeFiles to include this extra flag only in places where -msse2 is used too and only on Emscripten target.

This was exactly what I faced :)

Closing as duplicate.
