### ISSUE TITLE
❓ What's the recommended way to benchmark Emscripten compiled WASM?

### ISSUE THREAD

**Issue by danbugs** [emscripten-core/emscripten#14045]
I wanted to quickly compare two programs to find prime numbers within a specified range — one written in C++ and the other written JS. Do you Emscripten folks recommend any specific way for doing so?

Here's how I currently have it setup:

### C++ side

File: `primes.cpp`:
```
int IsPrime(int value) {
    if (value == 2) { return 1; }
    if (value <= 1 || value % 2 == 0) { return 0; }
    for (int i = 3; (i * i) <= value; i += 2) {
        if (value % i == 0) { return 0; }
    }
    return 1;
}

EMSCRIPTEN_KEEPALIVE
int primes () {
    int start = 3;
    int end = 1000000000;
    for(int i = start; i <= end; i += 2) {
        if(IsPrime(i)) {
            // found a prime
        }
    }
    return 0;
}
```
... compiled with `emcc primes.cpp -o primes.wasm -s ERROR_ON_UNDEFINED_SYMBOLS=0 --no-entry`. 

File `primes.js`:
```
let moduleExports = null;

const init = () => {
    WebAssembly.instantiateStreaming(fetch("primes.wasm"))
        .then((result) => {
            moduleExports = result.instance.exports;
            moduleExports._initialize();
            let then = new Date; 
            moduleExports.primes();
            let now = new Date;
            document.write(now - then); // will print result in ms
        });
}
```

... other than this, there's an `index.html` file where I call `init()` in the body's `onload` and include the `primes.js` script.

### JS side

File `primes.js`:
```
let moduleExports = null;
let moduleMemory = null;

const init = () => {
    let start = 3;
    let end = 1000000000;
    let then = new Date;
    for(let i = start; i <= end; i += 2) {
        if(IsPrime(i)) {
            // found prime
        }
    }
    let now = new Date;
    document.write(now - then);
}

const IsPrime = (value) => {
    if (value == 2) { return 1; }
    if (value <= 1 || value % 2 == 0) { return 0; }
    for (let i = 3; (i * i) <= value; i += 2) {
        if (value % i == 0) { return 0; }
    }
    return 1;
}
```

... the JS side also has an `index.html` which is exactly the same as the C++ side.

### TL:DR;

Currently, I'm benchmarking **both** the C++ and JS by getting a reference to the clock before (`let then = new Date`) and after (`let now = new Date`) running the `primes` function, and subtracting the two.

> Note: I'm calculating the time taken in JavaScript for both the C++ and JS implementation of the `primes` function. 

### Results

C++ code took 40 minutes and 51 seconds to calculate all primes within 3 and 1 billion.

JS code took 44 minutes and 10 seconds to calculate all primes within 3 and 1 billion.

This doesn't feel like a super dramatic of a performance change so I figured I'd ask if there's a better/recommended way to do this! If not, and this is what I should be expecting, I'm guessing the example is just bad 'cause I am not really changing the types of any JS variables or something like that? 🤔

**Comment by sbc100** [comment]
WebAssembly is not generally expected that simply porting your JS code will necessarily give you big performance wins.   There is common misconception that simply converting your JS code to WebAssembly is going to make it go faster.  

Having said that the most obvious thing you should do here is try adding `-O3` to your compile call.  That will trigger a lot of optimizations both in llvm and in binaryen.

**Comment by danbugs** [comment]
> WebAssembly is not generally expected that simply porting your JS code will necessarily give you big performance wins. There is a common misconception that simply converting your JS code to WebAssembly is going to make it go faster.

Thank you for clearing this misconception! 

> Having said that the most obvious thing you should do here is try adding -O3 to your compile call. That will trigger a lot of optimizations both in llvm and in binaryen.

Uuuh, I tried adding the `-O3` flag and now it takes...

🥁🥁🥁

0 ms to find all primes between 3 and 1 billion!

I don't want to be pessimistic but I think something is wrong haha

One more thing, I've tried importing a function to return the numbers that are prime back to JS to print them (just to ensure the primes are being found even with O3` and the optimization isn't somehow skipping the for-loop) but that completely killed my C++ performance — I'm guessing because writing to memory is expensive and it's happening way often (i.e., every time a prime is found).

What do you think, @sbc100 ?

**Comment by sbc100** [comment]
Maybe just return the last prime you fine.

**Comment by danbugs** [comment]
Yep, that did it — now it's actually taking its' time. 

For finding all primes between 3 and 100 million w/ an optimization of `-O3`, C++ took 1 minute and 3 seconds and JS took 1 minute and 23 seconds. That is, about a 25% improvement as compared to a 7.5% improvement without the optimization 👌

Is this level of performance improvement what I should be expecting with a calculation of this sort? If so, I'm good with closing this issue ;D ~ Thanks for all the help, @sbc100 !

**Comment by sbc100** [comment]
There is a whole range of performance improvements that you might hope or see but it the range is pretty big.  IIUC 25% is pretty high for a pure compute thing like this.

**Comment by danbugs** [comment]
Awesome — glad to hear it!

 I'll close the issue now. Thanks again ;D
