### ISSUE TITLE
Websocket onclose callback is overwriting my memory!!!!

### ISSUE THREAD

**Issue by rickg-hcl** [emscripten-core/emscripten#14054]
https://github.com/emscripten-core/emscripten/blob/156ae7588a2dc7a93e19c987ac10dcf9ba6345ac/src/library_websocket.js#L223

This code de-references the HEAPU32 value when it should not, and copies the close reason into random memory.
I only saw the problem with the reason was long. 

The line should be:

stringToUTF8(e.reason, (WS.socketEvent+10), 512);

I want my 2 weeks back!!

**Comment by juj** [comment]
Thank you for investing two weeks to track down the bug. All transactions are final, no refunds. Fix in #14055.

**Comment by kripken** [comment]
Sorry it took so long to track this down, but good find @rickg-hcl and thanks for reporting it!

Btw, AddressSanitizer can help with bugs like this. Emscripten even instruments memory accesses from JS, like the faulty one here. In general if there is memory corruption it can be useful to try a build with that, https://emscripten.org/docs/debugging/Sanitizers.html#address-sanitizer
