### ISSUE TITLE
emcc doesn't work with filenames/paths with ! sign

### ISSUE THREAD

**Issue by fgsgn-las** [emscripten-core/emscripten#14063]
Trying to compile simple source file located in directory named "a!":

>emcc.bat a!\a.cpp
emcc: error: a\a.cpp: No such file or directory ("a\a.cpp" was expected to be an input file, based on the commandline arguments provided)

Same with "!" in filename:

>emcc.bat !!!a.cpp
emcc: error: a.cpp: No such file or directory ("a.cpp" was expected to be an input file, based on the commandline arguments provided)

Seems it just strips ! char from paths/filenames.

**Comment by sbc100** [comment]
Given the correct quoting this seems to work for.  At least on linux:

```
$ touch a\!.c
$ ls a*
'a!.c' 
$ emcc a\!.c -c
$ ls a*
'a!.c'  'a!.o' 
```

It looks like maybe you are on windows..  maybe you need to escape the exclamation mark some how there too?

Maybe try to open the file using notepad.exe from the command line.. so you know you have the escaping right.

**Comment by fgsgn-las** [comment]
Yes, we are using windows.
Notepad opens files with such names without problems (I mean a!.cpp for example)

If trying to escape chars, emcc shows the following result:
emcc.bat a\!.cpp
emcc: error: a\.cpp: No such file or directory ("a\.cpp" was expected to be an input file, based on the commandline arguments provided)

Following variants, that also used in windows, also doesn't work:
emcc.bat "a!.cpp"
emcc: error: a.cpp: No such file or directory ("a.cpp" was expected to be an input file, based on the commandline arguments provided)

emcc.bat "a\!.cpp"
emcc: error: a\.cpp: No such file or directory ("a\.cpp" was expected to be an input file, based on the commandline arguments provided)

**Comment by sbc100** [comment]
But I mean does notepad open from the command promt you are in ?   What escape method do you use when opening from the command line using `notepad.exe a!.cpp`?

**Comment by fgsgn-las** [comment]
Notepad open even following:
>notepad a!.cpp
No escape needed.
I suppose emcc using their own filename handling.

**Comment by sbc100** [comment]
emcc is using python's standard file handling.

Can you trying running a trivial program like this?:

`$ python -c "import sys; print(sys.argv[1]); print(open(sys.argv[1]))" a!.cpp`

When I next get a chance use windows machine I can take a look myself.

**Comment by fgsgn-las** [comment]
Looks strange, because it works:
**> python -c "import sys; print(sys.argv[1]); print(open(sys.argv[1]))" a!.cpp
a!.cpp
<_io.TextIOWrapper name='a!.cpp' mode='r' encoding='cp1251'>**

**Comment by sbc100** [comment]
This seems to be related to out `.bat` files that launch python.   If I run emcc via `python emcc.py` it works but if I run it via `emcc.bat` it fails:

Works:
```
$ python emcc.py a!.cpp -c
```

Fails:
```
$ emcc a!.cpp -c
emcc a!.cpp -c
emcc: error: a.cpp: No such file or directory ("a.cpp" was expected to be an input file, based on the commandline arguments provided)
```

**Comment by sbc100** [comment]
It looks like #13723 is to blame.   `emcc a!.cpp -c` works before that change an fails afterwards.   @aheejin any ideas?  This looks pretty nasty.

**Comment by sbc100** [comment]
Looks like this is known issue with EnableDelayedExpansion:

From https://ss64.com/nt/delayedexpansion.html:

"
If DelayedExpansion is used in conjunction with a FOR command looping through a set of files, if any file in the set has an exclamation mark '!' in the filename, that will be interpreted like a !variable!.
Although this is not a common character used in filenames, it can cause scripts to fail. This happens because the parameter expansion (%%P) happens just before the delayed expansion phase tries to interpret my!filen!ame.txt
"

**Comment by sbc100** [comment]
Makes me want to look into maybe seeing if we can just assume powershell and run that from the .bat file.
