### ISSUE TITLE
shader issue introduced in #13732

### ISSUE THREAD

**Issue by thomasballinger** [emscripten-core/emscripten#14079]
#13732 breaks [a port of Endless Sky](https://github.com/thomasballinger/endless-sky/tree/es-wasm-reformatted) at runtime. This app [uses `uniform`](https://github.com/thomasballinger/endless-sky/blob/1c36334b787f541baf77b360f02c3307c57358f7/source/SpriteShader.cpp#L67-L71) in some shaders.

```
Uncaught TypeError: Cannot read property 'uniformLocsById' of null
    at _glUniform1i (endless-sky.js:13301)
    at imports.<computed>
    ...
```
    
![image](https://user-images.githubusercontent.com/458879/116880275-aa184380-abd6-11eb-9c1f-7c9db7b477d6.png)

I think this points to https://github.com/thomasballinger/endless-sky/blob/1c36334b787f541baf77b360f02c3307c57358f7/source/SpriteShader.cpp#L240

Adding `-s GL_EXPLICIT_UNIFORM_LOCATION=1` doesn't change the error output.

I don't know much about graphics, is there more information that would be helpful here?

**Comment by sbc100** [comment]
@juj?

**Comment by juj** [comment]
Posted a fix PR in #14112.

**Comment by thomasballinger** [comment]
I'm still seeing this on main today with 716f38685ff73681402f04a6c7fb3d5fb26491c4 which includes #14112.

**Comment by thomasballinger** [comment]
This error was cause by the following code, which was fine before #13732:
```
	// Reset the swizzle.
	glBindVertexArray(0);
	glUseProgram(0);
	glUniform1i(swizzlerI, 0);
```
and [can be fixed](https://github.com/thomasballinger/endless-web/commit/39597d804d97daa18019512a4f8260a1adbed4bc) to work with latest Emscripten by making the glUniform1i call before the glUseProgram(0):
```
	// Reset the swizzle.
	glUniform1i(swizzlerI, 0);
	glBindVertexArray(0);
	glUseProgram(0);
```
@juj I don't understand if this behavior change is intentional or now, but this is resolved for me.
