### ISSUE TITLE
Building with `-fexceptions` and all optimizations fails

### ISSUE THREAD

**Issue by lovasoa** [emscripten-core/emscripten#14078]
Trying to build HiGHS with exceptions enabled and the closure compiler fails : 

```
emcc -O3 \
	-s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall']" \
	-s MODULARIZE=1 \
	-fexceptions \
	-flto \
	--closure 1 
        [...]
``` 

```
building:ERROR: Closure compiler run failed:

building:ERROR: /tmp/emscripten_temp/highs.js.pp.js.jso.js.jso.js.jso.js.jso.js:867:1: ERROR - [JSC_UNDEFINED_VARIABLE] variable _setThrew is undeclared
  867|  _setThrew(0);
        ^^^^^^^^^

1 error(s), 0 warning(s)
```

See: https://github.com/lovasoa/highs-js/runs/2492006893?check_suite_focus=true

**Comment by kripken** [comment]
Can you provide the temp files emitted by `EMCC_DEBUG=1`? That would help investigate this.

**Comment by lovasoa** [comment]
Sure ! Here they are :

[emscripten-14078.zip](https://github.com/emscripten-core/emscripten/files/6418211/emscripten-14078.zip)

**Comment by lovasoa** [comment]
The problematic code seems to be

```js
function ___cxa_end_catch() {
 _setThrew(0);
 var catchInfo = exceptionCaught.pop();
 exception_decRef(catchInfo.get_exception_info());
 catchInfo.free();
 exceptionLast = 0;
}
```

The file `/tmp/emscripten_temp/highs.js.pp.js.jso.js.jso.js.jso.js.jso.js` contains 21 calls to `_setThrew` but no definition for the function.

**Comment by kripken** [comment]
Thanks @lovasoa 

It looks like that `setThrew` method is not present. Having `__cxa_end_catch` in your code, which you do, should cause the deps_info mechanism to lead to its inclusion from `system/lib/compiler-rt/emscripten_exception_builtins.c`.

I don't see how that could fail on current `main`. Are you on an older version perhaps? (if so maybe we've fixed this meanwhile) If not, then please provide the input files at the link stage, and I'll debug the link.

**Comment by lovasoa** [comment]
@kripken : the bug occurred with emscripten 2.0.18, you can see the CI output here: https://github.com/lovasoa/highs-js/runs/2492058733

The code is here: https://github.com/lovasoa/highs-js, you just have to add -fexceptions to build.sh to reproduce.
