### ISSUE TITLE
Is it unsafe when JS event simultaneously invoke an already executing C++ function? 

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#14086]
I'm seeing memory access out of bounds errors when an JavaScript event calls an  already executing (probabilistic)  C++ function multiple times and the C++ function runs an async operation.

This never happened to me before. The program worked fine. 

I made a test case with `emscripten_sleep` and can reproduce the error.

```
void foo(emscripten::val data) {
        emscripten_sleep(100);
}

```

I have read the Reentrancy section of [https://emscripten.org/docs/porting/asyncify.html](https://emscripten.org/docs/porting/asyncify.html) but it's still not clear to me whether it is safe or unsafe.

If this unsafe, what should I do? 

Should I write a Javascript dispatcher that schedule calling C++ function?

I imagine schedulers centered setTimeout will have no way knowing whether function still executing or executed thus looping into same error.  I imagine that could happen at undefined periods. 

I don't see that as a feasible solution unless Emscripten provide a way to check whether function executing or not

Better yet, are there are native Emscripten C++ solutions for this problem? 

The code works flawlessly if I remove `emscripten_sleep(100);`

Stacktrace 

```
  | dynCall_vii | @ | 00358d1a:0x96391
  | ret.<computed> | @ | VM6890:4182
  | eval | @ | VM6890:4254
  | eval | @ | VM6890:3801
  | setTimeout (async) |   |  
  | safeSetTimeout | @ | VM6890:3798
  | eval | @ | VM6890:4040
  | handleSleep | @ | VM6890:4237
  | _emscripten_sleep | @ | VM6890:4039
  | imports.<computed> | @ | VM6890:4162
  | foo(emscripten::val) | @ | 00358d1a:0x5355
  | dynCall_vi | @ | 00358d1a:0x966e4
  | ret.<computed> | @ | VM6890:4182
  | eval | @ | VM6890:1620
  | invoke_vi | @ | VM6890:4558
  | imports.<computed> | @ | VM6890:4162
  | emscripten::internal::Invoker<void, emscripten::val>::invoke(void (*)(emscripten::val), emscripten::internal::_EM_VAL*) | @ | 00358d1a:0x5a48
  | dynCall_vii | @ | 00358d1a:0x963fa
  | ret.<computed> | @ | VM6890:4182
  | eval | @ | VM6890:1620
  | dynCallLegacy | @ | VM6890:2690
  | dynCall | @ | VM6890:2698
  | eval | @ | VM6890:2710
  | foo | @ | VM6896:8


```

**Comment by curiousdannii** [comment]
Why are you calling the function multiple times? Are you calling it with different inputs? Does each invocation need different results, or once the calculation has been done once can the result be reused?

Three options you could consider:
1. Implement a queue in JS so that the C++ function is only called once at a time.
2. If the calculation only needs to be done once, you could wrap it in a promise, which you can then call `.then()` as many times as you like, completely safely.
3. Make multiple instances of the Emscripten module/factory, so that each calculation can run completely independently.

**Comment by jeffRTC** [comment]
@curiousdannii 

It's not me who call the function multiple times. It's the browser event.

I'm about to experiment futures in C++ which I believe runs in Worker. 

> Make multiple instances of the Emscripten module/factory, so that each calculation can run completely independently.

Can this be done inside C++?

**Comment by jeffRTC** [comment]
@curiousdannii

I just went with your third suggestion because futures seems working however I can't get the workers correctly...

> Make multiple instances of the Emscripten module/factory, so that each calculation can run completely independently.

If I create 1 million instances, would it cause any sort of memory issues? 

I can't find a way to destroy the instances

**Comment by jeffRTC** [comment]
@curiousdannii 

It did as I predicted.

```
failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
```

**Comment by jeffRTC** [comment]
Googling tell me this is Chrome's GC bug? 

Apparently, the error thrown at random times.

@kripken  Is setting null to instance can make this go away?

**Comment by curiousdannii** [comment]
I forgot about #12740 - yes currently the event handlers mean that the module can't be garbage collected. Though possibly changing the `NODEJS_CATCH_EXIT` and `NODEJS_CATCH_REJECTION` settings might help?

**Comment by jeffRTC** [comment]
@curiousdannii 

I'm on Chrome not on NodeJS. So, what would be the browser solution for this?

**Comment by curiousdannii** [comment]
If possible I'd be rethinking what the code is doing so that it doesn't need to handle so many events at once. And I'd consider the queue idea.

**Comment by jeffRTC** [comment]
How about queue mixed with  multiple instances?

Let's say 5 instances so 5 concurrent throughput... 

Would it cause the same problem?

**Comment by curiousdannii** [comment]
A pool system will probably work, though I have no experience designing one.

**Comment by jeffRTC** [comment]
@curiousdannii 

I implemented a queue but still running into out of bounds errors.

I settled into Fire and Forget approach means I will not call .await in em_val instead just invoke the async function and discard the result.

I might well as go and implement reverse async function where you fire and forget but in case of error it re-call the exported module function.
