### ISSUE TITLE
memory import has no maximum limit, expected at most 4294967295

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#14130]
Hi,

I encountered an error during startup, that didn't arise with version 2.0.13 I used earlier.

```
RuntimeError: abort(LinkError: WebAssembly.instantiate(): memory import 448 has no maximum limit, expected at most 4294967295). Build with -s ASSERTIONS=1 for more info.
```

The error goes away when I change the following emcc flag from
```
-sMAXIMUM_MEMORY=4GB
```
to
```
-sMAXIMUM_MEMORY=4294901760
```

**Comment by kripken** [comment]
Which version does this fail on?

The last release has some fixes in this area, which might be related.

**Comment by donalffons** [comment]
I tested this using Google Chrome Version 90.0.4430.93 (Official Build) (64-bit).

**Comment by kripken** [comment]
That's very strange... I am on the exact same Chrome, and I can't reproduce any problem, with e.g.
```
./emcc tests/hello_world.c -sMAXIMUM_MEMORY=4GB -s ALLOW_MEMORY_GROWTH -o a.html
```
Perhaps some specific flags you use are causing this. Can you share the full build command and/or the output js and wasm? If not, you can do a [quick bisection](https://emscripten.org/docs/contributing/developers_guide.html#bisecting) to find where this regressed, and that would likely be enough information for us to fix this.

**Comment by donalffons** [comment]
...here is my test project. Its quite trivial.
[prototype2.zip](https://github.com/emscripten-core/emscripten/files/6462085/prototype2.zip)

**Comment by kripken** [comment]
Thanks @donalffons , now I see it... interesting, but puzzling.

Building `./emcc tests/hello_world.c -sMAXIMUM_MEMORY=4GB -s ALLOW_MEMORY_GROWTH -o b.html -s MAIN_MODULE` (this only happens with main module because then we create the memory in JS), we get this in the wasm:

```wat
 (import "env" "memory" (memory $mimport$0 256 65536))
```

That is, we import a memory, starting with 16MB and growing up to 4GB. On the JS side we have this:

```javascript
 wasmMemory = new WebAssembly.Memory({
  "initial": INITIAL_MEMORY / 65536,
 });
```

That fails with the error described above, in both Chrome and Firefox, `LinkError: WebAssembly.instantiate(): memory import 406 has no maximum limit, expected at most 4294967295`.

Changing the JS to this "fixes" it:

```javascript
 wasmMemory = new WebAssembly.Memory({
  "initial": INITIAL_MEMORY / 65536,
  "maximum": 65536
 });
```

(it can be 65535 or 65536 - works either way).

I guess the issue is that when no limit is specified on the JS side, then the wasm's "limit" of 4GB seems more restrictive - even though in wasm32 4GB is the absolute limit anyhow...?

We can work around this by adding the JS, but first I'd like to check if I'm understanding this right. cc @dtig @sbc100

**Comment by sbc100** [comment]
I thought a memory with no maximum at all is not growable, is that not true?

**Comment by kripken** [comment]
I believe both in wasm and in JS the API is the same: not setting a maximum means there is no maximum, and is the way to say "grow without limit". However, I can't seem to find the spec for the wasm JS API (where is that?) so I can't verify that. [The MDN page for the Memory constructor is ambiguous](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory), I suppose, although I think it says basically that.

**Comment by kripken** [comment]
Ah, it's here, and yes, it seems to defer to the wasm spec: https://webassembly.github.io/spec/js-api/#dom-memory-memory

**Comment by dschuff** [comment]
We got another report of this, (it's apparently a regression since 2.0.16). That case is in pthreads, where it's refusing to instantiate the memory because it's setting `"shared": true` but with no maximum.

**Comment by kripken** [comment]
We can easily add a patch to work around this - should we just do that?

[I am still very confused as to why VMs error on this](https://github.com/emscripten-core/emscripten/issues/14130#issuecomment-839237801). It seems like a bug in the spec to me (extrapolating from that both chrome and firefox error in the same way), so I'm probably missing something.

**Comment by sbc100** [comment]
Isn't it because shared memories require a maximum and we are not providing one?   Or are you seeing that even with non-shared memories?

**Comment by dschuff** [comment]
It's totally intentional that shared memories require a maximum. This allows the VM to reserve that amount of address space, and they can then guarantee that the memory will never have to be moved (with non-shared memories, they can just realloc on grow since there will be no concurrent access).

**Comment by kripken** [comment]
The second testcase @dschuff mentioned uses pthreads, but the original one here does not @sbc100 . So these may be different issues?

The original testcase, after reduction, needs only
```
./emcc tests/hello_world.c -sMAXIMUM_MEMORY=4GB -s ALLOW_MEMORY_GROWTH -o b.html -s MAIN_MODULE
```
(And it only needs main module so that we create the memory in JS, which is where the problem happens.)

**Comment by dschuff** [comment]
The fact that there's a mismatch error when the module has a limit of 4G and the memory has no limit is a bit surprising to me though.

**Comment by sbc100** [comment]
> The fact that there's a mismatch error when the module has a limit of 4G and the memory has no limit is a bit surprising to me though.

Oh I see.. so is the fix to remove the max from the wasm binary maybe?

**Comment by dschuff** [comment]
Well, putting the max in the JS would fix both cases, right? And the user gave a max on the command line so it seems we should have it anyway?

**Comment by kripken** [comment]
I didn't try to modify the binaryen side, but maybe it could be worked around there too.

I opened a PR to always write it on the JS side, which also simplifies the JS ifdefing a little.

I do think it would be nice if the spec were changed to handle this in a clearer way (i.e., treat a limit of 4GB the same as 'no limit' in wasm32), but this isn't a big deal I guess.

**Comment by dschuff** [comment]
Regarding #14178:, I'm not sure we *always* want to have a max though. Do engines treat 4G max differently from no max? @dtig might know. But more to the point, this is a regression. What did we do before?

**Comment by sbc100** [comment]
The used to always specify the max prior to #14088 I think

**Comment by sbc100** [comment]
Should we try to bring back the meaning of "-1" and have both JS and wasm both skip the max in that case?

**Comment by sbc100** [comment]
When we run wasm-ld we conditionally pass --max-memory but since MAXIMUM_MEMORY is currently never -1 then this is effectively unconditional:

```
    elif settings.MAXIMUM_MEMORY != -1:                                                                 
      cmd.append('--max-memory=%d' % settings.MAXIMUM_MEMORY)     
```

**Comment by dschuff** [comment]
Hm, brief testing on tot, just using  `-s USE_PTHREADS. -s INITIAL_MEMORY=1gb -s ALLOW_MEMORY_GROWTH=1` it does look like it is writing a max of 2G into the JS. However if you add `-s MAXIMUM_MEMORY=4gb` then it leaves the max out.
So maybe just always writing a max isn't a change for the pthreads case at least.

**Comment by sbc100** [comment]
We used to default to `MAXIMUM_MEMORY == -1` until #10601..  but after that it became impossible to set it to -1 (since the command line parser can't deal with it).

**Comment by dschuff** [comment]
So the intention was that -1 means "don't set a max" but after #10601 we were unintentionally always setting a max?

**Comment by sbc100** [comment]
Yes.. apparently:

```
    This also changes MAXIMUM_MEMORY to be 2GB. That
    is effectively no change from the previous -1 (no limit)
    since 2GB was the absolute limit anyhow. This has two benefits:
    first, people must opt-in explicitly to getting 2GB+ heap support
    with the code size downside, and also we expect only some
    browsers will support 2GB+ heaps for now, so requiring explicit
    opt-in from devs is safer to avoid web compat issues (i.e., only
    users that really need such heaps will set them, and then they
    may only work in some browsers, but at least that won't happen
    for users that could actually run in all browsers).
```

**Comment by donalffons** [comment]
...not sure if this is relevant (if not - then nevermind), but the [MDN docs ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory) say
> Unshared WebAssembly memories don't need to set a maximum, but shared memories do.

If we're using a MAIN_MODULE's, is the WebAssembly Memory automatically shared? If yes, that might mean that a maximum has to be set in that case (either automatically by Emscripten or via a command line argument)?!

**Comment by sbc100** [comment]
No, shared in this context means "shared between threads" not "shared between modules".. all memories can be shared between modules.  Somewhat confusing terminology maybe.

**Comment by dschuff** [comment]
(just bringing my comment from #14178) I think we should land that, since IIUC it fixes the regression and makes the behavior the same as it's been for the last year. I'd still be interested in whether engines treat modules with no max any differently from modules with a 2G or 4G max, and if we want to make any changes based on that, we can.

**Comment by sbc100** [comment]
I think we want to be able to specify no max.. at the very least we save a couple of bytes in JS and in Wasm.
