### ISSUE TITLE
How to add copyright notices to WASM files?

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#14148]
Is there a safe way to add copyright notices to WASM files?

Preferably, I'd like to add it to top of WASM file.

**Comment by sbc100** [comment]
Yes, you could add a custom section.   I'm not sure what the best tool to inject a custom section is ... perhaps its already possible with `llvm-objcopy` (@dschuff can we do this already?,  if not we should add it).

**Comment by sbc100** [comment]
Custom section can appear anywhere in the wasm file and WMs will ignore then.

**Comment by jeffRTC** [comment]
Good to know but can't find a tool to inject custom section. An example with llvm-objcopy would be appreciated.

**Comment by dschuff** [comment]
Yes, `llvm-objcopy` can do this. For example, suppose you have a wasm file:
```
$ llvm-objdump -h hello.wasm

hello.wasm:	file format wasm

Sections:
Idx Name          Size     VMA      Type
  0 TYPE          00000157 00000000
  1 IMPORT        00000261 00000000
  2 FUNCTION      00000072 00000000
  3 TABLE         00000005 00000000
  4 GLOBAL        00000044 00000000
  5 EXPORT        0000036b 00000000
  6 START         00000001 00000000
  7 ELEM          0000000c 00000000
  8 DATACOUNT     00000001 00000000
  9 CODE          00006774 00000000 TEXT
 10 DATA          00000d3e 00000000 DATA
```
You can put your content into a file:

`$ echo "Hello!" > hello.txt`

And append it to your binary:
`llvm-objcopy --add-section=HelloSection=hello.txt hello.wasm hello2.wasm`

And then see it:
```
$ llvm-objdump -h hello2.wasm

hello2.wasm:	file format wasm

Sections:
Idx Name          Size     VMA      Type
  0 TYPE          00000157 00000000
  1 IMPORT        00000261 00000000
  2 FUNCTION      00000072 00000000
  3 TABLE         00000005 00000000
  4 GLOBAL        00000044 00000000
  5 EXPORT        0000036b 00000000
  6 START         00000001 00000000
  7 ELEM          0000000c 00000000
  8 DATACOUNT     00000001 00000000
  9 CODE          00006774 00000000 TEXT
 10 DATA          00000d3e 00000000 DATA
 11 HelloSection  00000007 00000000
```
And also look inside it:
```
llvm-objdump --full-contents --section=HelloSection hello2.wasm

hello2.wasm:	file format wasm

Contents of section HelloSection:
 0000 48656c6c 6f210a                      Hello!.
```

**Comment by sbc100** [comment]
Thanks @dschuff .. pretty awesome how that just works.

**Comment by jeffRTC** [comment]
@sbc100  Should I close this or do you have any plans to add this to Emscripten itself?

**Comment by sbc100** [comment]
No please close.   It would be nice to document how to do this somewhere, but I'm not sure emscripten is the right place for since it would apply to any clang-based WebAssembly toolchain.
