### ISSUE TITLE
Performance regressions due to system libraries

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#14161]
Hi @sbc100, referring to a submission you made in https://github.com/emscripten-core/emscripten/pull/13078, system libraries are now built with debug information.

Because we are using `--emit-symbol-map` in our builds, the `strip-debug` did not get added during wasm-ld and we ended up building our app with debug system libraries which caused a 20% performance degradation.

I am thinking of 2 approaches to resolve this:
1. Link to syslibs built without debug symbols when we are building our app in release
2. Support `--emit-symbol-map` with `--strip-debug` (I'm not even sure this make sense, just throwing out here)

I'm currently leaning towards option 1, which would mean having the option to build a release version of syslibs via embuilder.
What do you think? Or do you have a different approach?

**Comment by sbc100** [comment]
I don't think `--emit-symbol-map` is supposed to effect the final output at all.  The final output should still be stripped of debug info (or not) according to the normal options that control debug stripping (`-g` I guess).  

If adding `--emit-symbol-map` to your build is changing the size of your final output I think that is a bug.  Are you sure it is?

**Comment by sbc100** [comment]
When I build hello.cc with `--emit-symbol-map` and without `--emit-symbol-map` I get exactly the same wasm file.. and in both cases it does not contain any debug info or any names section at all.

**Comment by Mintyboi** [comment]
>If adding --emit-symbol-map to your build is changing the size of your final output I think that is a bug. Are you sure it is?

Yep, it seems like it'll have to be paired with the WASM_BIGINT flag as  well.
These are the build flags that I'm using:
`emcc index.bc --emit-symbol-map -s MAIN_MODULE=2 -flto -fPIC -s WASM_BIGINT=1 -Oz`

**Comment by sbc100** [comment]
Indeed it does look like `--emit-symbol-map` when combined with `-sWASM_BIGINT` is having effect on the size of the final wasm.

I created the following test case that currently fails:

```
  def test_symbol_map_output_size(self):                                                             
    self.run_process([EMCC, test_file('hello_world.c'), '-sWASM_BIGINT', '-Oz', '-o', 'test1.js'])               
    self.run_process([EMCC, test_file('hello_world.c'), '-sWASM_BIGINT', '-Oz', '-o', 'test2.js', '--emit-symbol-map'])
    self.assertEqual(os.path.getsize('test1.js'), os.path.getsize('test2.js'))                       
    self.assertEqual(os.path.getsize('test1.wasm'), os.path.getsize('test2.wasm'))      
```

As far as I can tell the final wasm files should be exactly the same size.. but they are not.. @kripken any idea.. Its a little hard to debug because if we add names then the difference goes away.

**Comment by kripken** [comment]
Looks like what happens here is that when using `WASM_BIGINT` we don't process the wasm before the wasm-opt stage. As a result we see the original wasm file, which contains DWARF. The presence of DWARF inhibits a bunch of optimizations that we know destroys it.

I believe this is a bug on binaryen. We pass `--strip-dwarf` to wasm-opt properly, but despite our passing it, it scans the original wasm before anything and sees DWARF there, which confuses it. So we need to be a little more careful there I think. I'll look into a fix.

**Comment by sbc100** [comment]
Thanks alon!
