### ISSUE TITLE
Request for a more detailed diagnostic in wasm-opt

### ISSUE THREAD

**Issue by andrewevstyukhin** [emscripten-core/emscripten#14174]
Hi,
recently I got an error
`Fatal: Module::getFunction: (null Name) does not exist`
while running wasm-opt with an **--post-emscripten** option.

To diagnose a problem I've used a --debug switch. Then I got 1GB of "== readXXX" with a brief message about passes:

> getInt8: 41 (at 15208289)
> running passes...
> [PassRunner] running passes...
> [PassRunner]   running pass: post-emscripten...                Fatal: Module::getFunction: (null Name) does not exist
> 

Is it possible somehow to diagnose passes aside from IO to not waste additional 30 minutes?

The problematic source code is also known:
bad:
  `OnParseError(Format::format("Shader supports no more than {} samplers: {}", kMaxMaterialTextures, samplerId), ctx, var);`
good:
  `OnParseError("Sampler index is out of range: " + samplerId, ctx, var);`
Both versions compile on many other platforms.

Optimizations are always complicated by their nature so better insights might be very helpful.

BTW, it's not the first case with "Format::format" in my practice.
A problem reproduces in those manually checked versions: 1.39.11, 2.0.17 and 2.0.20.

**Comment by sbc100** [comment]
This is really binaryen issue I think.  I agree that currently fatal error don't really give much information.   It would be nice if such fatal error could include a stack dump like they do when clang/llvm crashes.

**Comment by andrewevstyukhin** [comment]
Even a name of problematic pass can help to dig faster:

> Fatal: Module::getFunction: (null Name) does not exist

vs something like this

> Fatal: [post-emscripten] Module::getFunction: (null Name) does not exist

**Comment by kripken** [comment]
Instead of `--debug` perhaps try `BINARYEN_PASS_DEBUG=1` in the env. That will print passes as it runs them.

I agree it would be nice to show a better error on the default abort(), somehow like LLVM does. That takes some low-level magic I think though for the stack trace. Without that, we'd need to add some special plumbing for the "current pass". Could be worth looking into.

**Comment by andrewevstyukhin** [comment]
Nice hint! wasm-opt ran really fast.

> [PassRunner] running passes
> [PassRunner]   running pass: post-emscripten...                Fatal: Module::getFunction: (null Name) does not exist

**Comment by andrewevstyukhin** [comment]
Hi. Now I have very long delays (some minutes) after lines "(validating)" and "(final validation)". Meanwhile "running pass" works pretty fast.

> [PassRunner] running passes...
> [PassRunner]   running pass: legalize-js-interface... 0.138498 seconds.
> [PassRunner]   (validating)
> [PassRunner] passes took 0.138498 seconds.
> [PassRunner] (final validation)
> [PassRunner] running passes...
> [PassRunner]   running pass: strip-target-features... 0.0029962 seconds.
> [PassRunner]   (validating)
> [PassRunner] passes took 0.0029962 seconds.
> [PassRunner] (final validation)

**Comment by kripken** [comment]
To debug that, I'd check the issue isn't running out of RAM, and if it's not that, I'd run a profiler and see what it slow. (If you can provide the file I can look at it.)

**Comment by andrewevstyukhin** [comment]
Really strange things happen:

1. upstream\bin\wasm-opt --version
wasm-opt version 90 (version_90-60-gcd8d82910)
[PassRunner]   running pass: post-emscripten...                    Fatal: Module::getFunction: (null Name)Fatal: Module::getFunctionFatal: Module::getFunctionFatal: Module::getFunction does not exist

2. The manual build from tag "version_90" under VS 16.10.2 just works on the same wasm
[PassRunner] running passes...
[PassRunner]   running pass: post-emscripten...                    1.0588 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: inline-main...                        0.0089156 seconds.
[PassRunner]   (validating)

Maybe emscripten has been released under broken compiler?

**Comment by sbc100** [comment]
emsdk doesn't use the tagged releases of binaryen.   To get a matching version you would need to sync to the revision mention in the `--version`.   In this case that would be `cd8d82910` which is (apparently) 60 commits after the `version_90` tag.

**Comment by andrewevstyukhin** [comment]
Looks like that is
https://github.com/WebAssembly/binaryen/commit/b880950c56673b36127438d432f0a24eca92c773#diff-925a0ed439d65f9c2fd3aa83f533e4894c883036819d9758978ed05c003a4756R174
auto* target = getModule()->getFunction(curr->target);

**Comment by kripken** [comment]
Hmm.. is that an LTO bug, if it only happens with `-flto`? Which compiler is that on?

**Comment by andrewevstyukhin** [comment]
I use `emcc (Emscripten gcc/clang-like replacement) 1.39.7 (commit da9419f42ad3ed112adedbb830ef5140f92af4b6)`
I can try to debug this case. It is reproducible 100%.

**Comment by kripken** [comment]
Wait, sorry, I misunderstood. You are not compiling binaryen with `-flto`, but using emscripten to compile something with `-flto`? If so then yes, please debug and reduce that, it sounds like a real bug.

**Comment by andrewevstyukhin** [comment]
https://github.com/WebAssembly/binaryen/commit/b880950c56673b36127438d432f0a24eca92c773#diff-925a0ed439d65f9c2fd3aa83f533e4894c883036819d9758978ed05c003a4756R178
curr->target == "__invoke_void", target: env.invoke_v
index = 0 `auto actualTarget = flatTable.names.at(index->value.geti32());` actualTarget = NULL
Fails at `if (!map[getModule()->getFunction(actualTarget)].canThrow) {` because flatTable.names has NULL name at index 0:
[0]=NULL
[1]="__cxx_global_array_dtor"
[2]="FMOD::ChannelReal::isStream()"

Since we removed additional options `--llvm-lto 3` and `--llvm-lto 1` all got working.

**Comment by andrewevstyukhin** [comment]
About validation,
```
struct PassOptions {
  ...
  // Whether to run the validator to check for errors.
  bool validate = true;
```
```
ToolOptions
...
      .add("--no-validation",
           "-n",
           "Disables validation, assumes inputs are correct",
```
With `--no-validation` option for wasm-opt I got significant X2 speedup.

Then I tried "--no-validation --pass-arg=no-validation" for emcc without success (any impact)...

**Comment by andrewevstyukhin** [comment]
And problematic code snippet is
```
std::string fn(...)
	return Format::sprintf(" %s [%s ts:%s]",
		info.file_name.c_str(), pack_type.c_str(), info.timestamp.c_str());
```		
where
```
// Format::sprintf
template <typename S, typename... Args, typename Char = fmt::enable_if_t<fmt::internal::is_string<S>::value, fmt::char_t<S>>>
std::basic_string<Char> sprintf(const S& format, Args&&... args) {
	fmt::internal::backup_error errorBackup;
	auto result = fmt::sprintf<S, Args...>(format, std::forward<Args>(args)...);
	CHECK_FMT_ERROR(format, std::basic_string<Char>());
	return result;
}

// fmt::sprintf
template <typename S, typename... Args,
          typename Char = enable_if_t<internal::is_string<S>::value, char_t<S>>>
inline std::basic_string<Char> sprintf(const S& format, const Args&... args) {
  using context = basic_printf_context_t<Char>;
  return vsprintf(to_string_view(format), {make_format_args<context>(args...)});
}
```
But such weird trick avoids the problem:
```
std::string fn(...)
	auto result = Core::Format::sprintf(" %s [%s ts:%s]",
		info.file_name.c_str(), pack_type.c_str(), info.timestamp.c_str());
	return result;
```

**Comment by kripken** [comment]
> because flatTable.names has NULL name at index 0

Very interesting... so the code has an invoke to the function pointer 0? Perhaps the code has undefined behavior which clang optimizes into that.

This PR will prevent binaryen from crashing: https://github.com/WebAssembly/binaryen/pull/3951
