### ISSUE TITLE
Update libcxx to v12

### ISSUE THREAD

**Issue by bansan85** [emscripten-core/emscripten#14187]
According to `system/lib/libcxx/readme.txt` emscripten uses `libc++, release branch 10.x`.

I just updated to the latest emscripten and `emcc -v` says:

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.20-git (8ed0f4fee2abd04923c2fd2bf44835169ce2ac2e)
clang version 13.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 642df18f1437b1fffea2343fa471aebfff128c6e)
Target: wasm32-unknown-emscripten
Thread model: posix
```

So emscripten uses new incoming clang v13. What do you think about updating libcxx to stable v12 ? It could help to solve #11552

**Comment by sbc100** [comment]
Fixed #14249.
