### ISSUE TITLE
Include the test if (ENVIRONMENT_IS_WEB) before referencing `document`

### ISSUE THREAD

**Issue by johhnsmmith198** [emscripten-core/emscripten#14198]
I am guessing here but it seems that emscripten generate this kind of code:

```
  } else if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
    if (ENVIRONMENT_IS_WORKER) {
      scriptDirectory = self.location.href;
    } else if (document.currentScript) {
      scriptDirectory = document.currentScript.src;
    }
```
This is an issue for react-native, more on this here:
https://github.com/uber/h3-js/issues/117#issuecomment-841605471

is it possible to still test `  if (ENVIRONMENT_IS_WEB) ` before referencing the `document` variable?

**Comment by johhnsmmith198** [comment]
Sorry I made a mistake, the problem is at some other place:
this code gets generated I presume and we miss the check ENVIRONMENT_IS_WEB before referencing `document`
```
  var readAsync;

  {
    if (document.currentScript) {
      scriptDirectory = document.currentScript.src;
    }

    if (scriptDirectory.indexOf("blob:") !== 0) {
      scriptDirectory = scriptDirectory.substr(0, scriptDirectory.lastIndexOf("/") + 1);
    } else {
      scriptDirectory = "";
    }
```

something like
```
   if (ENVIRONMENT_IS_WEB && document.currentScript) {
      scriptDirectory = document.currentScript.src;
    }
```

**Comment by kripken** [comment]
Is the issue that react-native gets detected as "web", but does not have `document`, or does not have `document.currentScript`?

**Comment by johhnsmmith198** [comment]
Hi @kripken . React-native is not detected as web.
React-native is failing to compile because of this piece of code
```
var readAsync;

  {
    if (document.currentScript) {
      scriptDirectory = document.currentScript.src;
    }

    if (scriptDirectory.indexOf("blob:") !== 0) {
      scriptDirectory = scriptDirectory.substr(0, scriptDirectory.lastIndexOf("/") + 1);
    } else {
      scriptDirectory = "";
    }
 ```
 The error is: ```ERROR    ReferenceError: Can't find variable: document```
 
 If I am not wrong, ecmsripten generated this code but forgot to test `ENVIRONMENT_IS_WEB` before accessing the `document` variable.
 The test would need to be on its own line for react-native to not complain about the code.
 
 Something like this:
 ```
 var ENVIRONMENT_IS_WEB = typeof window === "object";
  
  ...
  
 var readAsync;
  {
    if (ENVIRONMENT_IS_WEB) {
      if (document.currentScript) {
        scriptDirectory = document.currentScript.src;
      }
    }

    if (scriptDirectory.indexOf("blob:") !== 0) {
      scriptDirectory = scriptDirectory.substr(0, scriptDirectory.lastIndexOf("/") + 1);
    } else {
      scriptDirectory = "";
    }
 ```

**Comment by kripken** [comment]
The line `scriptDirectory = document.currentScript` appears inside a block of 
```javascript
if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
```
You say react-native is not detected as web, then I guess it is detected as worker, then? (If so, is that right?)

**Comment by kripken** [comment]
I am looking at https://github.com/emscripten-core/emscripten/blob/main/src/shell.js#L305

Perhaps that is not the right place?

**Comment by Dakuan** [comment]
any progress on this? We really want to use H3.js in our React Native app...

**Comment by johhnsmmith198** [comment]
The problem comes from trying to access:
```
document.currentScript.src;
```
without testing for `ENVIRONMENT_IS_WEB` before.

The react-native compiler is then returning an error: ReferenceError: Can't find variable: document
If the conditional was around it the compiler would compile just fine

**Comment by kripken** [comment]
@johhnsmmith198 Looking in the current code, all the locations appear to have a proper conditional. So perhaps this was fixed meanwhile?

If not, please look in `src/shell.js` and find the missing one, a PR would be welcome.

**Comment by casertap** [comment]
Yes this commit did the trick: https://github.com/emscripten-core/emscripten/commit/112b38f34b2f26712c66f19bed7ff70483bf8304#diff-4f85fcef2887e829b7ecf6e416efe0505f7e3c3a3885a44fc35bfde1e7c7fd98

Thank you very much

**Comment by johhnsmmith198** [comment]
Hi @kripken 
Thank you. It could be this commit that fixed it: https://github.com/emscripten-core/emscripten/commit/112b38f34b2f26712c66f19bed7ff70483bf8304
