### ISSUE TITLE
When pthread_create called more than PTHREAD_POOL_SIZE times, program hangs

### ISSUE THREAD

**Issue by axinging** [emscripten-core/emscripten#14202]
pthread_create will call allocateUnusedWorker(https://github.com/emscripten-core/emscripten/blob/main/src/library_pthread.js#L472) when the created thread size smaller than PTHREAD_POOL_SIZE.
So base on this, we can call pthread_create more than PTHREAD_POOL_SIZE.

However, when the called times(THREAD_COUNT) is bigger than PTHREAD_POOL_SIZE. The program will hang and got no outputs.

How to test:
```
emcc -O2 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2 -o thread_hang.js thread_hang.c
node  --experimental-wasm-threads --experimental-wasm-bulk-memory thread_hang.js
```

Test Code:
```
// thread_hang.c
/*
emcc -O2 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2 -o thread_hang.js thread_hang.c
node  --experimental-wasm-threads --experimental-wasm-bulk-memory thread_hang.js
*/
#include <pthread.h>
#include <stdio.h>

// Calculate helloonacci numbers shared function
int hello(int iterations) {
    return iterations;
}
// Start function for the background thread
void *bg_func(void *arg) {
    int     *iter = (void *)arg;

    *iter = hello(*iter);
    return arg;
}
// Foreground thread and main entry point
int main(int argc, char *argv[]) {
    int         fg_val = 54;
    int         bg_val = 42;
    const int THREAD_COUNT = 4;
    pthread_t   bg_thread[THREAD_COUNT];

    for (int i =0 ; i < THREAD_COUNT; i ++) {
    // Create the background thread
      if (pthread_create(&bg_thread[i], NULL, bg_func, &bg_val)) {
        perror("Thread create failed");
        return 1;
      }
    }
    // Calculate on the foreground thread
    fg_val = hello(fg_val);
    // Wait for background thread to finish
    for (int i =0 ; i < THREAD_COUNT; i ++) {
      if (pthread_join(bg_thread[i], NULL)) {
        perror("Thread join failed");
        return 2;
     }
    }
    // Show the result from background and foreground threads
    printf("hello(42) is %d, hello(6 * 9) is %d\n", bg_val, fg_val);

    return 0;
}
```

**Comment by sbc100** [comment]
This is a limitation of the web platform so in that sense this is WIA.    New workers / threads cannot start while you are blocking the main thread.  You would need to return from main before new workers can start.

@RReverser I seem to remember you added error reporting recently for this case?

**Comment by RReverser** [comment]
> @RReverser I seem to remember you added error reporting recently for this case?

Yeah but in the follow-up PR @kripken removed the error by default in optimised builds as warnings are not expected by some users. OTOH it means those warnings won't show up by default when using optimised builds like in the command in the issue description.

**Comment by RReverser** [comment]
@axinging It's best if you try to compile your code in debug mode or at least in optimised + `-s ASSERTIONS=1` - it helps catch those and other issues.

**Comment by axinging** [comment]
After add  "-s ASSERTIONS=1", the log is as below:
```
Tried to spawn a new thread, but the thread pool is exhausted.
This might result in a deadlock unless some threads eventually exit or the code explicitly breaks out to the event loop.
If you want to increase the pool size, use setting `-s PTHREAD_POOL_SIZE=...`.
If you want to throw an explicit error instead of the risk of deadlocking in those cases, use setting `-s PTHREAD_POOL_SIZE_STRICT=2`.
```

**Comment by sbc100** [comment]
@axinging during development I highly recommend running (at least occasionally) without optimizations (`-O0` which is the default, and also enabled ASSERTIONS by default).  Doing so help you find and fix many different types of issues.

Hopefully this issue can be closed as this is known/existing behaviour.

**Comment by axinging** [comment]
Thanks for all your help, I will close this.
