### ISSUE TITLE
is it possible to build emscripten itself to WASM?

### ISSUE THREAD

**Issue by leoleoasd** [emscripten-core/emscripten#14229]
is it possible to build emscripten (like emcc / em++) itself to WASM?
I'm trying to make an "Online IDE" that can compile c/c++ into wasm and run it in the browser.

**Comment by leoleoasd** [comment]
I've noticed that emcc is written in python. is it possible to build cpython using emscripten?

**Comment by RReverser** [comment]
Everything is possible with enough effort and investment :) But I don't think this is something Emscripten team would do itself.

Meanwhile, you might want to check out https://github.com/binji/wasm-clang which has at least Clang ported to Wasm and compiling other inputs to Wasm from within Wasm.

**Comment by leoleoasd** [comment]
> Everything is possible with enough effort and investment :) But I don't think this is something Emscripten team would do itself.
> 
> Meanwhile, you might want to check out https://github.com/binji/wasm-clang and the demo at https://binji.github.io/wasm-clang which has at least Clang ported to Wasm and compiling other inputs to Wasm from within Wasm.

Yes, I've tried that, and I implemented its stdin support. But it can't support interactive input. 
Opening this issue is only a discussion of the possibilities. I'm not expecting Emscripten team would do it.

**Comment by kripken** [comment]
I think this is a duplicate of https://github.com/emscripten-core/emscripten/issues/6432

**Comment by kripken** [comment]
(In general, I think this would be interesting, and if someone has the time to do it I'm be interested to see the results! But as @RReverser said, this isn't something anyone is currently working on AFAIK)
