### ISSUE TITLE
Implement AF_UNIX sockets for communication between web workers.

### ISSUE THREAD

**Issue by amatus** [emscripten-core/emscripten#1422]
The idea is that a POSIX process is a web worker and workers can communicate with each other using AF_UNIX sockets. We might need a worker to hold the socket namespace and service connect requests.
This issue is to start a dialog so that I'm not going off into the weeds trying to implement it.
My target application is [GNUnet](https://gnunet.org/).

**Comment by nhooyr** [comment]
https://emscripten.org/docs/api_reference/Filesystem-API.html#file-types claims the file system supports sockets.

Does this issue mean unix sockets are not supported?

**Comment by kripken** [comment]
There is partial support for sockets, but it is far from complete, both because of web limitations (no blocking) and that it just hasn't had a maintainer for a while now. See the `sockets` test suite for examples of things that work.

**Comment by sbc100** [comment]
This bug specifically relates to UNIX sockets, which are quite different TCP/UDP sockets.   I guess we should re-open since I don't think we have UNIX socket support yet do we?

**Comment by tiagoad** [comment]
I think this should be open, as there's a lot of existing software that would be much easier to port if the existing UNIX socket inter-thread (worker) communication could be reused.

**Comment by sbc100** [comment]
One problem is that emscripten isn't currently aware of multiple processes.  Wiring up the different emscripten-generated modules is not somthing  that emscripten itself supports, but something the user of the module would (currently) need to do.

Even communicating via a unix domain socket between two modules on the same page is not something that emscripten currently makes simple/easy.   Of course non of this means we shouldn't do it, just that we would be venturing into a very new space, with a lot of open questions.
