### ISSUE TITLE
How to Use Module in multiple wasm？

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14223]
How to use the Module to distinguish calls the 'C' methods，if web layer loads two WASM libraries.

such as Demo.html :
` <script src="Decoder.js"></script> 
<script src="Player.js"></script> `

Decoder.js and Decoder.wasm；Player.js and Player.js .

How can i use Module to call functions in different libraries （Decoder.js and Player.js）separately  ?

**Comment by sbc100** [comment]
I that case I think you need to use the `MODULARIZE` option: https://emscripten.org/docs/getting_started/FAQ.html#can-i-use-multiple-emscripten-compiled-programs-on-one-web-page

**Comment by yangfangfang1204** [comment]
i add the option in compile file :`-s EXPORT_NAME='JSPlayerModule'  -s MODULARIZE=1`

how can i get the exported function in html ?
`JSPlayerModule` ? `JSPlayerModule(Module)` ? `Module(JSPlayerModule)` ?

**Comment by sbc100** [comment]
I believe you could something like this:

```
var mymod = JSPlayerModule();
```

The documentation in the settings.js looks like it has more details: https://github.com/emscripten-core/emscripten/blob/main/src/settings.js#L1093-L1155

You can also look at the tests that use MODULARIZE in test_core.py for examples.

**Comment by yangfangfang1204** [comment]
First: use the compile script is 
`emcc --bind STCom.a ample.a -o AudioInterCom.js -s USE_PTHREADS=1 -s TOTAL_MEMORY=1GB -s ALLOW_MEMORY_GROWTH=0 --js-library AudioData.js -lopenal -s PTHREAD_POOL_SIZE=2 -s EXPORT_NAME='JSPlayerModule' -s MODULARIZE=1`

Seconde，I get the JSPlayer.js as :

`var JSPlayerModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(JSPlayerModule) {
 .........................................................
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = JSPlayerModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return JSPlayerModule; });
else if (typeof exports === 'object')
  exports["JSPlayerModule"] = JSPlayerModule;`

Finally I call the function in test.html ：
`var module = createModule();`

it tell me createModule is not defined . 

could you tell me why?

**Comment by sbc100** [comment]
I think you want `var module = JSPlayerModule();` no?

**Comment by sbc100** [comment]
I think you would use `createModule` only if you had used `-s EXPORT_NAME='createModule'`
