### ISSUE TITLE
CMake regression for Node.js as emulator

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#14230]
Upgrading https://github.com/GoogleChromeLabs/squoosh/tree/dev/codecs/jxl from Emscripten 2.0.8 to 2.0.21 started throwing the following error:

```
CMake Error at third_party/highway/CMakeLists.txt:188 (add_custom_command):
  COMMAND may not contain literal quotes:

    "/emsdk/node/14.15.5_64bit/bin/node"
```

After some investigation, I've narrowed it down to invocation of `emcmake` itself passing a quoted path to Node.js executable (whereas all other configs are unquoted, and I suppose CMake expects that to hold for all strings):

```
emcmake: error: 'cmake -DBUILD_SHARED_LIBS=0 -DJPEGXL_ENABLE_BENCHMARK=0 -DJPEGXL_ENABLE_EXAMPLES=0 -DBUILD_TESTING=0 -B node_modules/jxl/build/mt node_modules/jxl -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/emsdk/node/14.15.5_64bit/bin/node"' failed (1)
```

In turn, this quotation happens here: https://github.com/emscripten-core/emscripten/blob/4d864df0a57024d667e8db171aab2c3385d04c30/emcmake.py#L39-L41

However, I couldn't tell where it was introduced in the version range since the version range is fairly wide and there was quite a bit of refactoring done among those Python scripts, including moving functions between files.

Either way, it seems like the fix is fairly straightforward: remove quotes from Node.js.

However, another question I have on mind is why does `emcmake.py` need to provide this argument at all if it already passes `-DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake`, and Emscripten.cmake already sets `CMAKE_CROSSCOMPILING_EMULATOR` internally too (and does it correctly, IIUC):

https://github.com/emscripten-core/emscripten/blob/d3b809b96f69dd4b8187c15949993d4e3409445a/cmake/Modules/Platform/Emscripten.cmake#L385

cc @kripken @sbc100

**Comment by RReverser** [comment]
For now I managed to workaround by manually passing `emcmake cmake -DCMAKE_CROSSCOMPILING_EMULATOR=node ...` which overrides this quoted string and build works again, but it would be good to fix the built-in config since it's likely to affect other projects too.

**Comment by sbc100** [comment]
Yes, this has certainly come up before.

See: https://github.com/emscripten-core/emscripten/issues/13126
Which was closed as a duplicate of: https://github.com/emscripten-core/emscripten/issues/10028

**Comment by sbc100** [comment]
My only question is ... why were you not seeing this long standing issue before?

**Comment by RReverser** [comment]
> why were you not seeing this long standing issue before?

Huh, yeah, I haven't even looked at issues this old, because we didn't see this problem before the upgrade.

**Comment by RReverser** [comment]
But yeah, closing as a duplicate of #10028. I hope it gets fixed eventually.
