### ISSUE TITLE
emscripten archive contains node devDependencies

### ISSUE THREAD

**Issue by akoeplinger** [emscripten-core/emscripten#14246]
Those aren't necessary for users of the toolchain, adding the `--production` flag to the `npm ci` fixes this.

https://chromium.googlesource.com/emscripten-releases/+/refs/heads/main/src/build.py#1013

/cc @sbc100

**Comment by sbc100** [comment]
See https://chromium-review.googlesource.com/c/emscripten-releases/+/2911475

**Comment by sbc100** [comment]
outputSec
