### ISSUE TITLE
It seems USE_ES6_IMPORT_META=0 is ignored

### ISSUE THREAD

**Issue by jvail** [emscripten-core/emscripten#14269]
The build of my project with emsdk fails when I switch from version 2.0.20 to  2.0.21 and I could not figure out why. Guess it is related to the handling of  `USE_ES6_IMPORT_META`.

The relevant flags I use are `-s EXPORT_ES6=1 -s USE_ES6_IMPORT_META=0 -s MODULARIZE=1 -s EXPORT_NAME='PGL' -s ENVIRONMENT='web'`

With 2.0.21 my build fails here :
```
SyntaxError: Cannot use 'import.meta' outside a module (1244:41)
var wasmBinaryFile = new URL('pgl.wasm', import.meta.url).toString();
```
Which is puzzling since I disabled USE_ES6_IMPORT_META. Or is it possible to disable acorn?

Any ideas? Thanks, Jan

**Comment by kripken** [comment]
cc @RReverser

**Comment by RReverser** [comment]
Sigh, another thing that I used correctly for `library_pthread` but not for this usage. I'll fix in a sec.

**Comment by RReverser** [comment]
@jvail Btw, just curious - is there any reason you're avoiding `import.meta`? It's widely supported by now.

**Comment by jvail** [comment]
@RReverser Thank you for the quick response!

> @jvail Btw, just curious - is there any reason you're avoiding `import.meta`? It's widely supported by now.

I am importing the emsdk build myself in my own module to have more control over minification and paths (https://github.com/jvail/plantgl-jupyter/blob/master/src/pgljs/src/worker.js#L1). I also pass the wasmBinary directly (https://github.com/jvail/plantgl-jupyter/blob/master/src/pgljs/src/worker.js#L183). My setup might be a bit unusual but works fine for me so far.

**Comment by RReverser** [comment]
Oh... okay, thanks. But is there any specific issue with `import.meta` output that breaks in that setup? In theory you should still be able to pass `wasmBinary` directly as you currently do.

**Comment by jvail** [comment]
> Oh... okay, thanks. But is there any specific issue with `import.meta` output that breaks in that setup? In theory you should still be able to pass `wasmBinary` directly as you currently do.

Yes, I think in theory the line should do no harm. But the build fails due to the acorn error. If there is another - now recommended  (I have not followed all new features lately) - way to get it build I am fine with that either.

**Comment by RReverser** [comment]
@Alexufo You might want to use [module-workers-polyfill](https://www.npmjs.com/package/module-workers-polyfill) - that's what I did to successfully use ESM output in all browsers.
