### ISSUE TITLE
why the out.js is compressed file

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14268]
`emcc  Decoder.a IDemux.a -o AudioInterCom.js -s USE_PTHREADS=1 -s TOTAL_MEMORY=1GB -s ALLOW_MEMORY_GROWTH=0  -lopenal `

why the AudioInterCom.js is compressed file?  It affects debugging.

**Comment by kripken** [comment]
What do you mean by "compressed" - minified?

When I run a command like yours on 2.0.20, I get an unminified JS file, starting with a command (which shows it is unminified),
```javascript
// The Module object: Our interface to the outside world. We import
```
If upgrading does not fix things for you, and the file is still minified, please provide a full testcase.
