### ISSUE TITLE
Remove loading and compiling code from generated js, but keep instantiating

### ISSUE THREAD

**Issue by EPNW** [emscripten-core/emscripten#14281]
I already loaded and compiled a wasm module from a `Uint8Array`, which I then want to pass to the `.js` file generated by emscripten (with `-s MODULARIZE=1` set).
So the generated `.js` should not contain any code to load or compile the wasm, but only code to instantiate it. Is there an `emcc` option to remove wasm loading and compiling but to keep instantiating? I wasn't able to find such an option in `settings.js`.

Edit: So to clarify, I basically need only need a `.js` file that contains the import object `info`:
```js
                var info = {
                    "env": asmLibraryArg,
                    "wasi_snapshot_preview1": asmLibraryArg,
                    "GOT.mem": new Proxy(asmLibraryArg, GOTHandler),
                    "GOT.func": new Proxy(asmLibraryArg, GOTHandler)
                };
```

**Comment by sbc100** [comment]
I believe that you can supply you Uint8Array as Module['wasmBinary'] .. then emscripten will use that as the wasm binary.

**Comment by EPNW** [comment]
Yes, that should work, thanks for the suggestion 😁!
