### ISSUE TITLE
FS permissions ignored when HAS_MAIN is not true

### ISSUE THREAD

**Issue by radekdoulik** [emscripten-core/emscripten#14299]
https://github.com/emscripten-core/emscripten/commit/6e794e6b9f4e439503073a3871f7f895240d40a8 removed `preMain()` function when HAS_MAIN is false.

FS sets its `ignorePermissions` to false at the end of initialization, by using `addAtMain('FS.ignorePermissions = false;');`. This doesn't work anymore when the main is not present and we endup with FS not checking the permissions.

I am not sure what would be best solution here. Possible solutions:

* set the `ignorePermissions`  elsewhere during initialization
* keep `preMain` function around, for actions which need to run at the end of initialization
* introduce new function for the end of initialization (`afterInit` for example) and let FS use that

**Comment by sbc100** [comment]
Can we just switch to `addAtInit` perhaps?

**Comment by radekdoulik** [comment]
> Can we just switch to `addAtInit` perhaps?

The `FS.init` is already added with `addAtInit` https://github.com/emscripten-core/emscripten/blob/e3b345d4bb9854e8b158aacb84e9eecf9942a105/src/library_fs.js#L30-L31

so I am not sure if that would work right. The idea behind the `ignorePermissions` is described here https://github.com/emscripten-core/emscripten/blob/e3b345d4bb9854e8b158aacb84e9eecf9942a105/src/library_fs.js#L98-L102

**Comment by sbc100** [comment]
Fixed in #14306
