### ISSUE TITLE
Setting all three of SINGLE_FILE, EXPORT_ES6, and USE_ES6_IMPORT_META causes the contents of the .wasm file to be included twice in the generated file

### ISSUE THREAD

**Issue by xaroth8088** [emscripten-core/emscripten#14309]
This appears to be due to the code here: https://github.com/emscripten-core/emscripten/blob/3a1fcb84b58f529ec82b272adca4ffd30fdd4cd7/src/preamble.js#L749-L761

**Comment by RReverser** [comment]
I don't understand the issue description. What does "causes the contents of the .wasm file to be included" mean? Contents of Wasm are binary...

@kripken do we include Wasm as base64 in that mode or something like that?

**Comment by RReverser** [comment]
I know very little of `SINGLE_FILE` mode tbh, and not sure what the proper fix should be. Should we just disallow `SINGLE_FILE` + `USE_ES6_IMPORT_META`? Or add `&& !SINGLE_FILE` to those conditions?

How does `SINGLE_FILE` work with pthreads, for example - do we need to change conditions there too?

**Comment by xaroth8088** [comment]
> do we include Wasm as base64 in that mode or something like that?

Ah, sorry - yes, the Wasm is base64 encoded when `SINGLE_FILE` is on, and is stored in `WASM_BINARY_FILE`.  It gets expanded out on both lines 752 and 759.

From a naive reading, the simplest fix for this specific issue without touching anything else seems to be to move line 752 just above line 749, and then use that variable in the `new URL(...)` invocation.  So, something like this:

```
var wasmBinaryFile = '{{{ WASM_BINARY_FILE }}}';
#if EXPORT_ES6 && USE_ES6_IMPORT_META
if (Module['locateFile']) {
#endif
  if (!isDataURI(wasmBinaryFile)) {
    wasmBinaryFile = locateFile(wasmBinaryFile);
  }
#if EXPORT_ES6 && USE_ES6_IMPORT_META
} else {
  // Use bundler-friendly `new URL(..., import.meta.url)` pattern; works in browsers too.
  wasmBinaryFile = new URL(wasmBinaryFile, import.meta.url).toString();
}
#endif
```

**Comment by xaroth8088** [comment]
> How does SINGLE_FILE work with pthreads, for example - do we need to change conditions there too?

Currently, it generates two files: the `.js` file and the `.worker.js` file.  Personally, I find that to be confusing, and would much rather that `SINGLE_FILE` cause the `.worker.js` file to be inlined (using a strategy similar to the second example given on the [Mozilla web workers page](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#embedded_workers))

That sounds like a job for a separate feature request, though.

**Comment by RReverser** [comment]
> From a naive reading, the simplest fix for this specific issue without touching anything else seems to be to move line 752 just above line 749, and then use that variable in the `new URL(...)` invocation. So, something like this:

No, unfortunately the `new URL` pattern must use static string literal to be detected by bundlers. At the same time, the other variable (the one passed to `locateFile`) also needs to be just a filename, so we can't reuse the resolved URL there either, so sharing variable in either direction is not an option.

However, the only use-case for this EXPORT_ES6 branch at all is only to load Wasm & Worker files alongside  the main JS. If Wasm is inlined as base64 in this mode, then sounds like

> Should we just disallow `SINGLE_FILE` + `USE_ES6_IMPORT_META`? Or add `&& !SINGLE_FILE` to those conditions?

either of those options should work well. I guess second one - adding `&& !SINGLE_FILE` would be the easiest fix + would avoid emitting code that isn't necessary for `SINGLE_FILE` anyway.
