### ISSUE TITLE
Thread pool exhausted error

### ISSUE THREAD

**Issue by goldwaving** [emscripten-core/emscripten#14336]
I just upgraded to the latest version of Emscripten.  When I recompiled my project, the following warning appears when I run it:

"Tried to spawn a new thread, but the thread pool is exhausted."

This occurs the first time a thread is created and again when other threads are created.

Setting PTHREAD_POOL_SIZE helps, but I'm wondering why this message suddenly started appearing?  I do not see any related changes in the release notes.  It seems like the default PTHREAD_POOL_SIZE is now zero.

Also is there a significant drawback to setting a larger pool size (such as 20)?

**Comment by RReverser** [comment]
This check was added in https://github.com/emscripten-core/emscripten/pull/13591 to prevent issues where people unknowingly try to spawn + join threads, but the pool is empty. Previously in those cases the program would just hang silently.

If your program is designed in a way where it can spawn threads but doesn't block on them, you can ignore this warning via `-s PTHREAD_POOL_SIZE_STRICT=0`, but I'd suggest to double-check that it's indeed safe to do so.

> Also is there a significant drawback to setting a larger pool size (such as 20)?

Mostly longer startup time. It's best to choose maximum number of threads that your program will actually use.

**Comment by goldwaving** [comment]
Thanks for the answer.  I also noticed that threads start a bit differently, but I suspect that is due to the threads being pre-allocated rather than waiting for the next event loop to start.  Some minor changes to our code solved that issue.

**Comment by RReverser** [comment]
> I also noticed that threads start a bit differently, but I suspect that is due to the threads being pre-allocated rather than waiting for the next event loop to start.

If you only just added `PTHREAD_POOL_SIZE` option, then Workers do get preallocated, but I don't think you're supposed to see any change in execution.

Probably also worth noting:

> It seems like the default PTHREAD_POOL_SIZE is now zero.

It always used to be zero, it was just silently hanging if threads were created + joined synchronously with an empty pool. Now it's a bit more explicit about that.

**Comment by goldwaving** [comment]
Good to know.  Thanks!
