### ISSUE TITLE
wasm-split: unable to indentify missing function name in firefox

### ISSUE THREAD

**Issue by waterlike86** [emscripten-core/emscripten#14330]
when a page fault happens we get `placeholder function called: 91990`
then after instantiating the compiled module we try to print out the function at the table index to get the function index.
we get something like below 
in chrome `ƒ 67552() { [native code] }`
but in FireFox we get `function() { [native code] }`

this prevents us from obtaining the function which is missing in production environment. we need this in order to determine the workflow to train our primary module for.

**Comment by tlively** [comment]
@sbc100, ultimately this is about being able determine which function the dynamic library loader has placed in a particular table slot. Is there any way to recover that information at runtime?

@waterlike86, do I understand correctly that this already works correctly in Chrome? If so, it might be worth filing a FireFox bug about this.

**Comment by sbc100** [comment]
It sounds like what you want is some kind of unique ID for the function that replaced placeholder?   Before the placeholder runs the table slow contains the placeholder itself.. and then after the secondary module is loaded the slot should have been replaced by a the real target function in the secondary module.   What kind of ID are you looking for here?   Something in the function index space of the secondary module?   I don't think the function index space is exposed outside the module so it doesn't sounds like something that is easy to do.

Can you explain a bit more about what you hope to do with this function ID.   @tlively presumably wasm-split itself knows about what function it decides to put in a given table slot?   I'm not sure any other tool has the mapping from "table slot -> function name/ID" does it?

**Comment by tlively** [comment]
Oh right, I got mixed up between the table slots allocated by wasm-split and the table slots allocated by the dynamic loader. @waterlike86, would it be useful to add an option to wasm-split to write a file containing the map from placeholder number to original function name?

**Comment by sbc100** [comment]
Does wasm-split always have access to names though?

**Comment by tlively** [comment]
No, this is assuming the names are preserved up to wasm-split, which is also required to effectively use related features like wasm-split's `--symbolmap` option.

**Comment by waterlike86** [comment]
>Can you explain a bit more about what you hope to do with this function ID.

@sbc100 we use the function ID to identify the missing function in production, and together with the call stack, create workflows to provide an updated profile data, so it does not page fault in future releases.

>@waterlike86, would it be useful to add an option to wasm-split to write a file containing the map from placeholder number to original function name?

@tlively that would be great, instead of relying on the browser console logs, it would be much more reliable this way.

> Does wasm-split always have access to names though?
>No, this is assuming the names are preserved up to wasm-split, which is also required to effectively use related features like wasm-split's --symbolmap option.

we currently build the instrumented binary with `--profiling-funcs`, so the original wasm still has the function names intact.

**Comment by waterlike86** [comment]
@tlively will you be working on this

**Comment by tlively** [comment]
Yes! Sorry for the delay; I've been caught up with other things. I will be able to get this done tomorrow.

**Comment by waterlike86** [comment]
Thanks for the prompt action, appreciate it 👍

**Comment by tlively** [comment]
@waterlike86, this was merged in https://github.com/WebAssembly/binaryen/pull/3931.

**Comment by waterlike86** [comment]
just integrated this change. validation in progress..

**Comment by waterlike86** [comment]
validated this and its working in production now please close this @tlively . Thanks for the fix!
