### ISSUE TITLE
Add exports to Module.

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#14333]
I want to import functions from JS to wasm Module. Now I edit js file and change this line of code in "receiveInstance" function:
`var exports = instance.exports`
Is there declared way to define additional exports to "Module"?

**Comment by sbc100** [comment]
If you want to make JS functions available to native code you do that by creating a library js file and using the `--library-js` option.

See https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-c-in-javascript

However `instance.exports` represent have functions implement on the native side being exported to JavaScript.  If you are trying to add native function to the list of exports you can use `-sEXPORTED_FUNCTIONS` on the command line or `EMSCRIPTEN_KEEPALIVE` in the source code.

**Comment by DiachenkoIgor** [comment]
I'm sorry for inconsistent explanation. I have js library that starts before loading of wasm. Than I add functions from that library to `instance.exports` for Asyncify.instantiate in order to use that functions in `--js-library`.

**Comment by sbc100** [comment]
`instance.exports` represents the exports from the WebAssembly module.  Its really an internal detail of emscripten and you probably don't want to be adding thing to that at runtime. 

Functions in `--js-library` code should already be able to call arbitrary other JS.    Any library that is loaded should be callable from js library code.

**Comment by DiachenkoIgor** [comment]
I need to get `instance.exports.memory`. Is there any way to get it in `--js-library` ?

**Comment by sbc100** [comment]
That should be accessible as `wasmMemory` .. but you also have `buffer` (the ArrayBuffer backing the memory) and the `HEAP8` family of variables which are TypeArray views of that buffer.    I would prefer the HEAPXX family of functions if I were you.

**Comment by DiachenkoIgor** [comment]
Thank you so much!
