### ISSUE TITLE
Playing video file in opengl

### ISSUE THREAD

**Issue by nasrii1990** [emscripten-core/emscripten#1434]
Hi,
Can someone tell me how can i play a video file(.avi or any video format) as texture in opengl.
Thank you.

**Comment by sortofsleepy** [comment]
whoa this is an old thread haha - I only just stumbled across this during research of a somewhat opposite path but in any case, figured I'd ought to leave a note for anyone else that might be looking to do the same thing in 2018. 

It is possible and I have a working sample. I can't quite release it yet though and it is tied to a framework but I can explain the basic concept. 

The simplest way is to blend use of Javascript and C++. You'll need to include `Embind`.

Basically the broad concepts are

1. create video element in Javascript. 
2. create texture in c++. 
3. in the global GL object, you'll be able to look up the texture you created in C++ within the textures key ie `GL.textures[<id for your c++ texture>]` so store a reference to that somehow in your Javascript. 
4. From there, all the control is on the Javascript side of things. I won't go into how to play the video as that should be pretty simple but to update your texture with the video content 

```javascript

  var gl = GLctx;
  gl.bindTexture( gl.TEXTURE_2D,texture );
 
   gl.texImage2D( gl.TEXTURE_2D,0,gl.RGBA,width,height,0,gl.RGBA,gl.UNSIGNED_BYTE,<video element> );
      gl.bindTexture (gl.TEXTURE_2D,null );

```

**Comment by Jonathhhan** [comment]
The solution from sortofsleepy sound very interesting, sounds like it could be possible with Open Frameworks Emscripten too. I wanted to ask if there is a similar working example somewhere, because I could not find anything.

**Comment by sbc100** [comment]
Do you want me to reopen this issue?

**Comment by Jonathhhan** [comment]
Hi sbc100, thanks. I already opened a new issue with a reference to this issue (because it was not possible to reopen this one by myself.  https://github.com/emscripten-core/emscripten/issues/10487
I hope it is the right way to handle things like this, otherwise I will do it right the next time.
I will update the issue if I had some success with implementing the idea from sortofsleepy...

**Comment by sbc100** [comment]
Yeah.. I think github prevents re-opening issues unless you are project contributor.  If future you can just ask for it to be re-opened in a comment, but for now using the other issue fine.

**Comment by Jonathhhan** [comment]
Alright, then I will do it like that. 
As far as I understood you can close and reopen an issue if you are the contributor, or if you opened the issue.
