### ISSUE TITLE
Do we need the list of authors in AUTHORS?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#14354]
I believe I added that file back in 2010 or so because I saw it done in other projects, as a simple way to have a list of contributors, in case we ever wanted to change license. However, in recent years I don't think I see other projects maintaining such lists any more - the git history basically contains the same info anyhow.

Perhaps we can remove the list? This would make things slightly simpler for new contributors, to not need to add themselves to the file in their first PR.

**Comment by kripken** [comment]
For comparison, chromium does maintain [an AUTHORS file](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/AUTHORS) which is mentioned in the [contributing docs](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/contributing.md#first_time-contributors) as a requirement.

**Comment by kleisauke** [comment]
I noticed with several open source projects that the AUTHORS file is usually used in combination with the contributor license agreement (CLA). Perhaps it's not necessary when there's no CLA present at all (with the usual "I am not a lawyer" proviso)? https://opensource.google/docs/releasing/authors/ might also be relevant here.

Also for comparison, the [libjxl](https://github.com/libjxl/libjxl) project requires you to [sign Google's CLA](https://github.com/libjxl/libjxl/blob/main/CONTRIBUTING.md#contributing-checklist) and to add yourself to the [AUTHORS](https://github.com/libjxl/libjxl/blob/main/AUTHORS) file (which is checked by [`tools/check_author.py`](https://github.com/libjxl/libjxl/blob/main/tools/check_author.py) in CI). It also has [an CONTRIBUTORS file](https://github.com/libjxl/libjxl/blob/main/CONTRIBUTORS) for individuals who made significant contributions on this project.

**Comment by kripken** [comment]
Interesting, thanks @kleisauke 

I'll try to find time to look into this more offline. This does seem more complicated than I had thought.

**Comment by goldwaving** [comment]
The email address I provided in the AUTHORS list is receiving a rapidly increasing number of junk messages (mostly scams).  The address was created exclusively for the emscripten AUTHORS list and was not provided anywhere else.  AUTHORS lists seem to be an easy target for email address harvesters.

**Comment by kripken** [comment]
Sorry to hear that @goldwaving ...

We can remove your email there if you want (if so please open a PR doing that).

**Comment by kripken** [comment]
Good news, I've confirmed that AUTHORS is in fact not really necessary. I opened #14893 to mark it is optional. New contributors can ignore it from now on.

**Comment by mmarczell-graphisoft** [comment]
https://emscripten.org/docs/contributing/AUTHORS.html still says, in direct contradiction with the note in the file itself (emphasis mine):

> Authors **must** add themselves to the AUTHORS file before contributing. This act licenses their changes under the project’s open source licenses (MIT/LLVM). Note that the developer retains copyright.

**Comment by sbc100** [comment]
Looks like that was overlooked when we changed the policy in #14893.   The file in question that would need an update is `site/source/docs/contributing/AUTHORS.rst`.  Feel free to send a patch if you have time.
