### ISSUE TITLE
[gnutls]: does not compile if it uses musl's weak_alias()

### ISSUE THREAD

**Issue by msabwat** [emscripten-core/emscripten#14350]
[In musl](https://github.com/emscripten-core/emscripten/blob/4d864df0a57024d667e8db171aab2c3385d04c30/system/lib/libc/musl/src/internal/libc.h#L64), weak_alias has the following definition:

```C
#undef weak_alias
#define weak_alias(old, new) \
 __typeof(old) new __attribute__((weak, alias(#old)))
```

gnutls won't compile because of a missing semicolon after weak_alias()

```sh
memchr.c:171:39: error: expected ';' after top level declarator
weak_alias (__memchr, BP_SYM (memchr))
```

**Comment by sbc100** [comment]
libc.h is not installed into the sysroot, so should not be visible, except when building musl itself.

Are you perhaps using an older version of emscripten?
