### ISSUE TITLE
Recent chrome beta is causing strange CI failures

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#14369]
With today beta update the chrome browser seems to be sending back result to the test runner in way that gets out of sync.

This seems to generate 73 error consistently. e.g:

https://app.circleci.com/pipelines/github/emscripten-core/emscripten/13728/workflows/b0934789-a661-484e-9ff7-1a1360887df1/jobs/431453

```
--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+/report_result?85
```

It kind of looks like the results from previous test are being recieved.

**Comment by kripken** [comment]
This may be a regression in headless mode in chrome. This fails locally:
```
EMTEST_BROWSER="google-chrome-beta --headless --remote-debugging-port=1234" ./tests/runner browser.test_client*
```
Removing `-beta` makes it work.

**Comment by sbc100** [comment]
Indeed, pinning to stable made the issue go away.

**Comment by kripken** [comment]
I'm trying to do a regression now on chromium. Will file an issue when I am done.

**Comment by kripken** [comment]
I can't find a way to either bisect or debug this, due to it only happening in headless mode :disappointed: but I filed an issue and hopefully we can get help there, https://bugs.chromium.org/p/chromium/issues/detail?id=1216489
