### ISSUE TITLE
Cannot link anymore with 2.0.20 but 2.0.14 works

### ISSUE THREAD

**Issue by ymoreau** [emscripten-core/emscripten#14377]
I have a project compiling fine with 2.0.14. But when I tried to compile it with 2.0.20 (or 2.0.23) the link step is failing without telling why.
I just get this message:

> em++: error: '/home/me/apps/emsdk/upstream/bin/wasm-opt --strip-dwarf --post-emscripten --no-exit-runtime -O3 --low-memory-unused --zero-filled-memory --strip-debug --strip-producers MyProject.wasm -o MyProject.wasm -g --mvp-features' failed (-9)
> ninja: build stopped: subcommand failed.

The command called above this which is generated by a CMake (including a CMake of an external framework, so there many layers and many source files):

> [540/541] Linking CXX executable MyProject.js
> FAILED: MyProject.js
> : && /home/me/apps/emsdk/upstream/emscripten/em++  -s WASM=1 -s FETCH=1 -g2 -O3 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -s ERROR_ON_UNDEFINED_SYMBOLS=1 -fcolor-diagnostics -s WASM=1 -s FETCH=1 -g2 -O3 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -s ERROR_ON_UNDEFINED_SYMBOLS=1 -fcolor-diagnostics -s WASM=1 -std=c++11 -O2 -g -DNDEBUG  -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s WASM=1 -s FETCH=1 -g2 -O3 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -s ERROR_ON_UNDEFINED_SYMBOLS=1 -fcolor-diagnostics -s DISABLE_EXCEPTION_CATCHING=0 ...SOURCE_FILES....

I don't know why options are duplicated. Might come from all the different nested CMake. But nothing is different in my source repo when I compile with success using 2.0.14.
I did not try versions between 2.0.14 and 2.0.20, and I have not seen anything suspicious in the release note.

**Comment by kripken** [comment]
Bisecting should be pretty quick for a clear regression like this: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by sbc100** [comment]
Looks like a crash in binaryen.. maybe another reason to look into better binaryen crash reporting?

**Comment by ymoreau** [comment]
I have been doing more attempts to gather information but somehow it now works (I had tried several builds and confirmed the difference between 2.0.14 and 2.0.20 but it's magically working now).
Maybe it was related to my system (WSL) or the memory of the computer that day that was heavily used, I don't know.

**Comment by ymoreau** [comment]
After some other tests, I have been able to reproduce this crash in a docker with a fresh build, locally or not. This happens for 2.0.17 and above.

**Comment by sbc100** [comment]
Great news.

Since it seems to be binaryen crash (wasm-opt is crashing) perhaps you could share the single input file need in order to get it to crash.  I.e. the MyProject.wasm found in the failing command line:

`/home/me/apps/emsdk/upstream/bin/wasm-opt --strip-dwarf --post-emscripten --no-exit-runtime -O3 --low-memory-unused --zero-filled-memory --strip-debug --strip-producers MyProject.wasm -o MyProject.wasm -g --mvp-features' failed (-9)`

Given that file and that command it should be possible for anyone to reproduce the crash I would hope.   You may need to build with EMCC_DEBUG in order to get emscripten to keep the temporary files around so you can grab `MyProject.wasm` from `/tmp/emscripten_temp/`

**Comment by ymoreau** [comment]
Sorry I did not took the time to debug more into this back then.
And the issue did not reproduce after I updated to 2.0.25.
