### ISSUE TITLE
Severe performance issue with `std::vector`

### ISSUE THREAD

**Issue by nhhollander** [emscripten-core/emscripten#14390]
While debugging an application I noticed some strange behavior with `std::vector`, especially on firefox when the developer toolbox was open. The issue seems to be mostly caused by `std::vector::resize` and `std::vector::clear`, both of which are tens to *hundreds* of times slower when run in the browser. The source code for this test program can be found [here](https://gist.github.com/nhhollander/e700409d35104773cdc409a5b0bf285e).

Code was compiled natively with `g++ -O0 vectortest.cpp` and under emscripten with `g++ -O0 vectortest.cpp -o vectortest.html`.

When run with the developer tools closed, Firefox takes an about 40ms to complete each round of the test. This is slower than native, but that is expected. When the developer tools are open however, Firefox takes nearly 30 *seconds* to complete each round, nearly 750x slower. With the developer tools open, chrome executes the same code only ~2x slower.

Native:
```
std::vector: 1000 test rounds of 1048576 bytes
Completed in 0.015821 seconds, average of 0.015821ms per round
```

Firefox: Dev tools closed:
```
std::vector: 10 test rounds of 1048576 bytes
Completed in 0.394000 seconds, average of 39.400000ms per round
```

Firefox: Dev tools open
```
std::vector: 10 test rounds of 1048576 bytes
Completed in 261.593000 seconds, average of 26159.300000ms per round
```

**Comment by sbc100** [comment]
Do you know if this is regression is has this (as far as you know) always been this way?

Have you tried building with `-O2`?  

BTW, a certain amount of slowdown when devtools is open is to be expected since open devtools will often disable the higher tiers of the WebAssembly compiler (I'm not sure about the exact details of firefox vs chrome but it could even force you into the lowest tier which might be an interpreter loop). 

I'm also curious to know how much of the slowdown persists when you instead build with `-O2`?

**Comment by sbc100** [comment]
I'm also curious to know why you needed separate timing setup under emscripten.   Did the  `#include <chrono>` stuff not work as expected under emscripten?  That would be another bug if true.

**Comment by nhhollander** [comment]
@sbc100 
I haven't gotten a chance to test with previous versions, I'll try that later today.
Compiling with `-O2` does appear to fix the issue.

Some performance impact is expected, but it's unclear why the impact is so extreme under Firefox but not Chrome.

As for `emscripten_time_now()` vs `std::chrono`, I have absolutely no idea why I did that. I probably shouldn't be working on software so late at night!

Interestingly I am no longer able to reproduce the 700x slowdown I was previously encountering.

**Comment by nhhollander** [comment]
I can't reliably reproduce the issue anymore so for the time being I'm going to assume it was just something very strange with my setup. Any unusual slowness was resolved by adding `-O2` to the compilation options.

I'll update if I find a root cause.
