### ISSUE TITLE
Mention useful -ferror-limit=0 flag in Emscripten/emcc docs (to make it more googleable)

### ISSUE THREAD

**Issue by vadimkantorov** [emscripten-core/emscripten#14445]
I'm getting `wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)` from emcc. I tried passing adding `-error-limit=0` to emcc flags but now also getting `clang-12: warning: -e rror-limit=0: 'linker' input unused [-Wunused-command-line-argument]`

I'm having a lot of (dozens or hundreds) duplicate symbols and seeing them all at once is much better to fix them all at once.

How to instruct `emcc`/`wasm-ld` to print all errors?

Thanks :)

**Comment by kleisauke** [comment]
The clang compilation flag you're looking for is <code>-<b>f</b>error-limit=0</code> (notice the preceding `-f`). You can use this in combination with GNU make's `-k` (or `--keep-going`) flag to continue compiling if an error occurs (useful for catching all possible compilation errors).

**Comment by vadimkantorov** [comment]
Thanks! Maybe worth mentioning this flag in the docs, since analyzing the bulk of errors is frequent when porting to wasm :)

**Comment by sbc100** [comment]
Actually I think in this this case `-error-limit=0` is a linker flag so you need to pass it via `-Wl,-error-limit=0`.

**Comment by sbc100** [comment]
Is it really that useful to see more than the first 20 errors?   Normally more than 20 linker errors means a catastrophic failure of some kind where seeing more than 20 is not much more actionable than just seeing 20.   At least I think that is the motivation behind the default value of 20.   Maybe you can explain why you showing more is useful in your case?

**Comment by sbc100** [comment]
Yes, that makes sense.  That was the one use case I could think of:  feeding the errors into some kind of script that would then fix the errors in some automatic way.   I think that the existing `-Wl,-error-limit=0` is sufficient for that purpose, assuming that worked for you?    The existing `use -error-limit=0 to see all errors` hint that wasm-ld provides seems sufficient to point folks in the right direction.
If you agree maybe we can close this issue?

**Comment by vadimkantorov** [comment]
A problem is that it almost seemed like -error-limit=0 is a flag of emcc itself. I don't mind closing either way, but adding information about this flag specifically or maybe some other flags supported by wasm-ld to the emcc man page would be useful: it would make easier googling such a thing, imagine query `emcc "error-limit"`. Currently it would probably return only this issue :)

**Comment by sbc100** [comment]
I agree we could improve our documentation about how to pass linker flags (`-Wl,...`).

BTW, `wasm-ld --help` shoes some information:

```
wasm-ld --help
OVERVIEW: LLVM Linker

USAGE: ./upstream/bin/wasm-ld [options] file...

OPTIONS:
....
  --error-limit=<value>  Maximum number of errors to emit before stopping (0 = no limit)
....
```

One problem here is that the error message in question is coming from `wasm-ld` (hopefully that is somewhat clear) and it doesn't know that its being run from `emcc`.   The error message would be equally confusing when running native `clang` (i.e. it would tell you add `-error-limit=0` and you would need to know that add `-Wl,` to pass linker flags via clang).

**Comment by vadimkantorov** [comment]
I see, so clang should be improved
