### ISSUE TITLE
TypeError: canvas.getContextSafariWebGL2Fixed is not a function in eglCreateContext

### ISSUE THREAD

**Issue by fridenmf** [emscripten-core/emscripten#14455]
### Environment

Version: 2.0.24
Browsers: Chrome, FireFox

### To reproduce

[repro.zip](https://github.com/emscripten-core/emscripten/files/6656070/repro.zip)

1. Build attached main.cpp with CMakeLists.txt and build.sh.
2. Run attached main.html with built build/main.js and build/main.wasm in Chrome or FireFox.
3. Note the console output:
```
eglGetDisplay... done
eglInitialize... done
initialized EGL 1.4
eglChooseConfig... done
eglCreateWindowSurface... done
exception thrown: TypeError: canvas.getContextSafariWebGL2Fixed is not a function,TypeError: canvas.getContextSafariWebGL2Fixed is not a function
    at Function.canvas.getContext (http://localhost/emscripten_bugs/main.js:2871:29)
    at Object.createContext (http://localhost/emscripten_bugs/main.js:2876:26)
    at _eglCreateContext (http://localhost/emscripten_bugs/main.js:2994:24)
    at __original_main (http://localhost/emscripten_bugs/main.wasm:wasm-function[13]:0xb20)
    at main (http://localhost/emscripten_bugs/main.wasm:wasm-function[81]:0x26de)
    at http://localhost/emscripten_bugs/main.js:1517:22
    at callMain (http://localhost/emscripten_bugs/main.js:3541:15)
    at doRun (http://localhost/emscripten_bugs/main.js:3611:23)
    at run (http://localhost/emscripten_bugs/main.js:3626:5)
    at runCaller (http://localhost/emscripten_bugs/main.js:3519:19)
```

### Expected behavior

The context should be created successfully and the context should output "eglCreateContext... done" instead of the error.

### Additional notes

I've tried backing versions all the way back to 2.0.18 which also reproduces the bug, so I currently have no way running or maintaining our web backend. Any workaround until this is fixed is highly appreciated!

**Comment by sbc100** [comment]
The code in question is here: https://github.com/emscripten-core/emscripten/blob/4a9d5ab94f66b629b99c1104663bedbc80f799c1/src/library_webgl.js#L586-L599

This code was added back in #13659 which first landed in 2.0.16, so going back to 2.0.15 should work around your issue.

The question is why are you seeing this and nobody else is?  It looks like `canvas.getContext` is not a function for you?

Perhaps you are using some unusual link flags?

**Comment by fridenmf** [comment]
I've rewritten both our EGL code and build files recently, and I'm quite certain that everything ran OK at some point in 2.0.18 so I'm probably missing something, I just can't find what. You can see the link flags in the attached CMakeLists from the original post, can you see if anything is strange in there? And if you are not able to reproduce the error with my repro app, maybe it's something wrong in my environment?

I just get emsdk with:
```
git clone https://github.com/emscripten-core/emsdk.git
pushd emsdk
./emsdk install 2.0.24
./emsdk activate 2.0.24
```
, and then run the mininmal repro app attached in the original post, and I get this error in Chrome and Firefox.

I tried reverting to 2.0.15, running the app from the first post now instead logs this:
```
eglGetDisplay... done
eglInitialize... done
initialized EGL 1.4
eglChooseConfig... done
eglCreateWindowSurface... done
exception thrown: TypeError: canvas.getContext is not a function,TypeError: canvas.getContext is not a function
    at Object.createContext (http://localhost/emscripten_bugs/main.js:2819:26)
    at _eglCreateContext (http://localhost/emscripten_bugs/main.js:2966:24)
    at __original_main (http://localhost/emscripten_bugs_old/main.wasm:wasm-function[13]:0xb1d)
    at main (http://localhost/emscripten_bugs_old/main.wasm:wasm-function[82]:0x274c)
    at http://localhost/emscripten_bugs/main.js:1538:22
    at callMain (http://localhost/emscripten_bugs/main.js:3507:15)
    at doRun (http://localhost/emscripten_bugs/main.js:3578:23)
    at run (http://localhost/emscripten_bugs/main.js:3593:5)
    at runCaller (http://localhost/emscripten_bugs/main.js:3485:19)
    at removeRunDependency (http://localhost/emscripten_bugs/main.js:1441:7)
```

I think my repro app finds a code path that you're not used to for EGL, maybe skips some important step that's important for the context functions to be initiated properly.

Also note that I'm only using EGL here. I wrote a small app that instead uses the emscripten_webgl_create_context("#canvas", ...) function for context creation, and that seems to work well, unfortunately the function that we are porting to web is using EGL all over.

**Comment by fridenmf** [comment]
In the article "EGL Support in Emscripten", you reference the sample from the glbook as an example how to create a context through EGL, specifically the file esUtil.c. I ran code from esUtil in 2.0.15, and still get the same error. I then tried removing the X code, only running EGL, which looks very similar to my original example, and also still the same error message.

I have attached both source files if you want to test them, just rename the file you want to run to main.cpp and you can build it with the build scripts from the first post: glbook_egl_context.zip](https://github.com/emscripten-core/emscripten/files/6662050/glbook_egl_context.zip)

Since the glbook is under the test directory in your repo, I figured that the test/runner is running those tests, but i couldn't find any reference to the glbook in the runner.py, maybe pure EGL context creation is not tested?

**Comment by fridenmf** [comment]
I generated a new html file through emcc and finally found a small difference, the generated html had the content:
```
canvas: (function() { return document.getElementById('canvas'); })()
```
while my html had:
```
canvas: function () { return document.getElementById('canvas'); }
```
in the Module declaration. Mistake on my side, I'm leaving the solution here in case someone else does the same mistake.

**Comment by antichaosdb** [comment]
I hit this as well, upgrading from 1.39 when we didn't need to set a canvas on the Module until after initialization.  There really should be a sensible assertion to guide the user in this case, rather than this cryptic error.
