### ISSUE TITLE
Is Emscripten using musl-libc? And is it support IPC call?

### ISSUE THREAD

**Issue by leyao-daily** [emscripten-core/emscripten#14466]
I find that emscripten uses musl-libc and the source code have ipc call implementation such as ftok.cc and shm...

But when I complied a third library to wasm, it report undefined symbol ftok, shmdt and so on.

**Comment by sbc100** [comment]
We don't support any of the IPC stuff no.   Mostly becuase emscripten doesn't have any concept of multiple processes (at least not as of today).
