### ISSUE TITLE
Question: dealing with "Imported global cannot be mutable in wasm-opt"

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#14460]
While working on upgrading Pyodide to Python3.9 I run into the following errors from `wasm-opt` when compiling packages (which are `SIDE_MODULE`s linked against Python stdlib):
`[wasm-validator error in module] unexpected true: Imported global cannot be mutable`
This occurs in a call like the following:
```sh
wasm-opt --strip-dwarf --post-emscripten --no-exit-runtime -O2 --low-memory-unused --fpcast-emu --pass-arg=max-func-params@61 --strip-debug --strip-producers build/lib.linux-x86_64-3.9/PIL/_imagingft.cpython-39-x86_64-linux-gnu.so -o build/lib.linux-x86_64-3.9/PIL/_imagingft.cpython-39-x86_64-linux-gnu.so --mvp-features
```
I found that if I remove `--mvp-features` and add `--enable-mutable-globals` then the build succeeds and the test suite passes.

I made the following patch to remove `--mvp-features` and add `--enable-mutable-globals` to the `wasm-opt` calls:
https://github.com/hoodmane/pyodide/blob/python-3.9/emsdk/patches/fix-wasm-validator-error.patch

My question is whether there is a better way to do this or a way to do it without patching emsdk.

**Comment by sbc100** [comment]
When emscripten runs binaryen tools it does the following:

1. First it runs wasm-emscripten-finalize with `--detect-features`.
2. The features are then extracted from the binary into `metadata['features']` in the python code and then we do `settings.BINARYEN_FEATURES = ['--mvp-features'] + metadata['features']`
3. Future runs on binaryen should therefore includes all the features used by the binary

For some reason it looks like maybe `metadata['features']` is not being set correctly in your case.  If you run with EMCC_DEBUG=1 you should see all of the metadata being output from `wasm-emscripten-finalize`.  

For example whenever I build any SIDE_MODULE I always see `--enable-mutable-globals` in the extracted metadata:

```
$ EMCC_DEBUG=1 emcc hello.c -s SIDE_MODUL
...
emscripten:DEBUG: Metadata parsed: {'asmConsts': {},
 'declares': ['printf'],
 'emJsFuncs': {},
 'exports': ['__wasm_call_ctors', 'main', '__wasm_apply_data_relocs'],
 'features': ['--enable-mutable-globals'],
 'globalImports': ['__stack_pointer', '__memory_base', '__table_base'],
 'invokeFuncs': [],
 'mainReadsParams': 1,
 'namedGlobals': {'__dso_handle': '0'},
 'staticBump': 0,
 'tableSize': 0}
...
```

For some reason I guess you don't see  `'features': ['--enable-mutable-globals']`?

**Comment by hoodmane** [comment]
An odd feature of this is all of the same flags worked to compile the same libraries linked with Python 3.8 but it breaks when we try to link with Python 3.9. The side module code didn't change and the configuration / flags that we run emcc with didn't change for either the side modules or the main module, only the main module code changed.

I will try looking at what happens with `EMCC_DEBUG=1`, thanks.

**Comment by hoodmane** [comment]
Okay:
```js
emscripten:DEBUG: Metadata parsed: {'asmConsts': {},
 'declares': ['PyImport_ImportModule',
              'PyObject_GetAttrString',
              '_Py_Dealloc',
              'PyModule_Create2',
              'PyUnicode_InternFromString',
              'PyObject_CallFunctionObjArgs',
              'PyObject_GetAttr',
              'PyObject_CallObject',
              'PyErr_Clear',
              'PyObject_Str',
              'PyErr_WarnEx',
              '_PyUnicode_Ready',
              'PyUnicode_New',
              'memcpy'],
 'emJsFuncs': {},
 'exports': ['__post_instantiate',
             'PyInit__speedups',
             '__wasm_apply_data_relocs'],
 'externs': ['___stack_pointer',
             '___memory_base',
             '___table_base',
             '_PyLong_Type',
             '_PyFloat_Type',
             '__Py_NoneStruct',
             '_PyBool_Type',
             '_PyExc_DeprecationWarning'],
 'features': [],
 'invokeFuncs': [],
 'mainReadsParams': 0,
 'namedGlobals': {'__dso_handle': '0'},
 'staticBump': 0,
 'tableSize': 4}
```

**Comment by sbc100** [comment]
What version of emsdk are you using?  

Does the same thing happen (i.e. lack of `--enable-mutable-globals`) when you build a trivial example:

```
$ cat test.c
int foo = 0;
$ EMCC_DEBUG=1 ./emcc -s SIDE_MODULE test.c 2>&1 | grep mutable
 'features': ['--enable-mutable-globals'],
```

**Comment by hoodmane** [comment]
With this `int foo = 0;` trivial example I see exactly what you showed:
```js
 'features': ['--enable-mutable-globals'],
```

Using version 2.0.15. Again what's weird is that the bug didn't come up with Python 3.8. Working on building Python 3.8 + the side module (I'm using Jinja2 as my test case) to see what `EMCC_DEBUG=1` prints out in that case. Still seems weird that this changed with the Python version...

**Comment by hoodmane** [comment]
Okay confirmed that the version built against Python 3.8 has `--enable-mutable-globals`:
```js
emscripten:DEBUG: Metadata parsed: {'asmConsts': {},
<...>
 'features': ['--enable-mutable-globals'],
 'invokeFuncs': [],
 'mainReadsParams': 0,
 'namedGlobals': {'__dso_handle': '0'},
 'staticBump': 0,
 'tableSize': 4}
```

**Comment by hoodmane** [comment]
So is there any way to force `wasm-emscripten-finalize` to put `--enable-mutable-globals` in or otherwise to add this option to the metadata? I would like to avoid patching emscripten if possible.

**Comment by sbc100** [comment]
I don't think there is any way to do this no, it should all be fully automatic, so we didn't design any way to do that (at least I don't think so).

I thought you discovered that it was actually in your metadata?   If its not present in the metadata for a side module then I think we have a bug that needs fixing somewhere.

**Comment by hoodmane** [comment]
`--enable-mutable-globals` *was* present in the side module metadata when the main module is Python 3.8, but when we use as the main module Python 3.9, `--enable-mutable-globals` is missing from the side modules.

**Comment by sbc100** [comment]
So you kept the emscripten version constant and you updated python?  And at the point `--enable-mutable-globals` was not detected in the side module.  

And can you try with the latest emsdk or are you limited to specific older version?   I suppose there could have been a bug that has since been fixed.

Could you attach a copy of one of those side modules that is missing the mutable global feature?

(assuming this is bug in llvm, and if you don't have the option of upgrading emsdk, then patching could be your only option)

**Comment by hoodmane** [comment]
Well in the process of minifying things for this, I located the particular flag that is different between the two versions. It doesn't seem to matter whether we give Python 3.8 or 3.9 includes. The difference is that for some reason it added the option:
`-Wl,--strip-all`
With this, the error occurs. Without it, it works fine.

**Comment by sbc100** [comment]
Ah yes, I can see what that would be an issue.  It looks like we strip the target-features section completely in wasm-ld if you pass `--strip-all`.

That means that that flag is basically incompatible with emscripten today.    Not to worry though the optimizations that binaryen and emscripten do after linking will strip everything possible.

**Comment by sbc100** [comment]
I guess we should error on `-Wl,--strip-all`

**Comment by hoodmane** [comment]
Right so the Python version issue is that Python 3.9 setuptools adds `-Wl,--strip-all`. For now, we can just strip out that flag in our build tools.

Thanks so much for your help!
