### ISSUE TITLE
ASM_CONSTS in generated JS is empty even though ASM_JS is used

### ISSUE THREAD

**Issue by bennyhobart** [emscripten-core/emscripten#14521]
Hello!

As the title, passing -s LLD_REPORT_UNDEFINED=1 reveals both __start_em_asm and __stop_em_asm are undefined, when LLD_REPORT_UNDEFINED=0 everything compiles fine, the command I'm running is

`wasm-ld -o crypto-primitives.wasm main.c.o -Lwasm32-emscripten libgl.a libal.a libhtml5.a libc.a libcompiler_rt.a libc++-noexcept.a libc++abi-noexcept.a libdlmalloc.a libc_rt_wasm.a libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export main --export emscripten_stack_get_end --export emscripten_stack_get_free --export emscripten_stack_init --export stackSave --export stackRestore --export stackAlloc --export __wasm_call_ctors --export fflush --export __errno_location --export-table --export __start_em_asm --export __stop_em_asm -z stack-size=5242880 --initial-memory=16777216 --entry=main --max-memory=16777216 --global-base=1024`

I'm quite new to this but reading through it looks like this is required to generate the metadata used by emscripten.py to populate ASM_CONSTS, and it's possible for this to be undefined for dynamic libraries?

A library I'm using is libsodium which uses an EM_ASM macro to generate random number using  WebCrypto, https://github.com/jedisct1/libsodium/blob/6d566070b48efd2fa099bbe9822914455150aba9/src/libsodium/randombytes/randombytes.c#L55

Is the best answer to stop using EM_ASM* related macros? is there another path forward?

Thanks for building and supporting all this

**Comment by sbc100** [comment]
If `__start_em_asm` and `__stop_em_asm` are undefined that seems to suggest that non of the object files contains the `EM_ASM` macros are being included by the linker.     Do you know if anyone is referencing the code in `randombytes.c`? 

Are you seeing a runtime issue where code is trying read into the `ASM_CONSTS` but the elements are missing?

**Comment by sbc100** [comment]
BTW on recent version of emscripten those symbols should be exported using `--export-if-defined=__start_em_asm` in order to allow `LLD_REPORT_UNDEFINED=1` to work as expected.   What version of emscripten are you using?

**Comment by bennyhobart** [comment]
Sorry for taking a while to respond I've been trying to get a minimum repro, I've reduced the problem and it still occurs if I just have a main.c file with a EM_ASM macro in it  (-s LLD_REPORT_UNDEFINED=1 no longer errors), one thing that stands out is that we're using clang 12 whilst emcc used clang 13 so I'll see if changing that helps

**Comment by sbc100** [comment]
Yes, emscripten requires the very latest tip-of-tree build of llvm.   If you use emsdk it will install it for you.  If you don't use emsdk you need to build your own version of llvm.

Did you not get a warning about this from emscripten?  Perhaps we should make it into a hard error.

**Comment by bennyhobart** [comment]
Awesome thanks SBC will update now
