### ISSUE TITLE
Calling varargs functions from Javascript

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#14537]
How do I call a varargs C function from Javascript? The naive approach doesn't work:
```js
Module._printf("a : %d, b : %d\n", 7, 2);
```
prints `a : 0, b : 0`.

**Comment by kleisauke** [comment]
Here's a simple example to call the variadic printf function from JavaScript:
```c
#include <emscripten.h>

EM_JS(void, printf_js, (), {
    // Our printf format string
    var str = "a : %d, b : %d\n";

    var stackTop = stackSave();

    // Copy the given Javascript String object 'str' to the emscripten HEAP at
    // address 'strPtr', null-terminated and encoded in UTF8 form
    var len = lengthBytesUTF8(str) + 1;
    var strPtr = stackAlloc(len);
    stringToUTF8(str, strPtr, len);

    // Initialize varargs
    var varargs = stackAlloc(4 * 2);
    HEAP32[varargs >> 2] = 7;
    HEAP32[varargs + 4 >> 2] = 2;

    // Call the variadic printf function from JavaScript
    _printf(strPtr, varargs);

    stackRestore(stackTop);
});

int main() {
    printf_js();
    return 0;
}
```
```bash
$ emcc -O2 printf_js.c -s EXPORTED_FUNCTIONS='["_main", "_printf"]' -o printf.js
$ node printf.js
a : 7, b : 2
```

BTW, was this question related to the Emscripten port of libffi? I had a quick go with commit https://github.com/kleisauke/libffi-emscripten/commit/ab42d1f5bdfc7b107b9a5fa663b3bd386f2fdd87 to fix the variadic calls, but it didn't quite work out.

**Comment by hoodmane** [comment]
> was this question related to the Emscripten port of libffi?

Absolutely. I wanted to fix a downstream Pyodide test failure in `cpython_core-test_unicode` where Python tries to use `ctypes` to call `PyUnicode_FromFormat` which is variadic.

**Comment by hoodmane** [comment]
Thanks for the explanation! (I probably should have made a test file with a variadic function and then used `wabt/bin/wasm-disassemble` or `wasm2wabt` to work this out but I didn't want to bother...)

**Comment by hoodmane** [comment]
Closed as answered by @kleisauke.
