### ISSUE TITLE
Some SDL functions and sig missing in library_sdl.js

### ISSUE THREAD

**Issue by patrickyyang** [emscripten-core/emscripten#14530]
I can not find SDL_RWclose in library_sdl.js
and SDL_SetError has no sig

so when I run pygame in browser, it throws error in convertJsFunctionToWasm.

**Comment by sbc100** [comment]
Thanks for the report.   If you have time to make a PR it would be most welcome, otherwise marking as help wanted since it should be a fairly straight forward change.

**Comment by kaushambisharma** [comment]
I'd like to work on this but will need some guidance.

**Comment by patrickyyang** [comment]
I found out that, I can't run my code because only MAIN_MODULE link the system libs, SIDE_MODULE not link. So I add -s USE_SDL=2 to MAIN_MODULE， Then there is no dynamic linking problem. 

Thank you all!
