### ISSUE TITLE
Feature request: macro to inject javascript helper code for EM_JS

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#14545]
I frequently experience the issue that I need to use a helper method from multiple `EM_JS` functions. I think the current options are to duplicate the definition of the helper method, to define the helper method in an `init` function that we arrange to be called on startup, or to define the function in other Javascript files and add it to the `Module` or include it with `--js-library`.

It would be nice to have a macro to define helper methods:
```
EM_JS_HELPER_CODE({
    // This will be injected into the js file when linked
	function helper_method(x){
		console.log("I can be used in EM_JS!");
	}
});

EM_JS(void, js_func1, (), {
   call_helper_method(1);
});

EM_JS(void, js_func2, (), {
   call_helper_method(2);
});
```
This could avoid code duplication, keep related code together in the same file, and allow libraries to define common Javascript methods without requiring them to have init functions or require extra linker flags.

## Existing solutions that I am aware of

Is there some more convenient way to do this that I'm missing?

### Duplication
```js
EM_JS(void, js_func1, (), {
	function helper_method(x){
		// ... long code 
		console.log("Called helper method with arg", x);
	}

   call_helper_method(1);
});

EM_JS(void, js_func2, (), {
	function helper_method(x){
		// ... long code 
		console.log("Called helper method with arg", x);
	}
   call_helper_method(2);
});
```
This always works but can require a large amount of code duplication.

### Init function
```js
// Make sure to call this in main
EM_JS(int, this_file_init_js, (), {
    Module.helper_method = 	function(x){
		// ... long code 
		console.log("Called helper method with arg", x);
	};
	return 0;
});

EM_JS(void, js_func1, (), {
   Module.call_helper_method(1);
});

EM_JS(void, js_func2, (), {
   Module.call_helper_method(2);
});
```
This isn't so bad for a full application. For porting a library it is fine as long as the existing API has an init function, but otherwise it's a bit awkward.

### Define function in js file 

Similar to **Init function** but in some Js file we say
```js
wasm_module.helper_method = function(x){
	// ... long code 
	console.log("Called helper method with arg", x);
};
```
For a library, I guess this would have to be included by users with a `--js-library` flag or something which makes it more complicated for users to link.

**Comment by curiousdannii** [comment]
You can just define it with EM_JS:

```
EM_JS(void, helper_method, (x), {
   console.log("Called helper method with arg", x);
});
```

I'm not sure if it's perfectly efficient, but it works.

**Comment by hoodmane** [comment]
Oooh!

**Comment by hoodmane** [comment]
> I'm not sure if it's perfectly efficient, but it works.

Looking at the emitted js code, the call doesn't do a round trip translation js ==> C ==> js for the args / return value, which is the main thing that I would worry about efficiency-wise.

**Comment by hoodmane** [comment]
Thanks @curiousdannii!
