### ISSUE TITLE
 RuntimeError: abort(To use dlopen, you need to use Emscripten's linking support,

### ISSUE THREAD

**Issue by luopengting** [emscripten-core/emscripten#14552]
I tried em and need help.

1. I compile libadd.so use following files:
**add.h**
```
int add(int a, int b);
```

**add.cpp**
```
#include "add.h"
int add(int a, int b)
{
  return a + b;
}

```

Compile: `g++ -fPIC -shared -o libadd.so add.cpp`

**main.cpp**
```
#include <stdio.h>
#include <dlfcn.h>
#include <stdlib.h>
#include <iostream>
#include <unistd.h>
using namespace std;
int main()
{
        char *path;
        path = get_current_dir_name();
        std::cout << "path: " << path << std::endl;

        puts("=> come in main.");
        int res = 0;

        puts("handle begin");
        void *handle = dlopen("/absolute-path/libadd.so", RTLD_LAZY);
        puts("handle done");
        if(!handle)
        {
                printf("open lib error\n");
                cout<<dlerror()<<endl;
                return -1;
        }
        printf("begin to deal add");
        typedef int (*add_t)(int a, int b);
        add_t add = (add_t) dlsym(handle, "add");
        if(!add)
        {
                cout<<dlerror()<<endl;
                dlclose(handle);
                return -1;
        }
        int a = 3, b = 4;
        printf("calculate %d + %d ...\n", a, b);
        res = add(a, b);
        printf("res = %d\n", res);
        dlclose(handle);
        return 0;
}

```

**CMakeLists.txt**
```
# stop if cmake version is below 3.0
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)

# project name and enable C++ support
project(hello LANGUAGES CXX)

# add env variables
set(CMAKE_EXECUTABLE_SUFFIX ".html")

# require C++11
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(EMCC_DEBUG 1)
set(SIDE_MODULE 1)

# we define the executable
add_executable(hello main.cpp)

# link libadd.so
message(STATUS "PROJECT_SOURCE_DIR: ${PROJECT_SOURCE_DIR}")
add_link_options("SHELL:-L./ -ladd")
add_link_options("SHELL:-s MAIN_MODULE=1")
add_link_options("SHELL:-s EXPORT_ALL=1")
add_link_options("SHELL:s EXPORTED_FUNCTIONS")

```

2. Then compile html using `emcmake` and `emmake`

```
mkdir build
cd build
emcmake cmake ..
emmake make
```

Printed:
```
path: /
=> come in main.
handle begin

```

Errors:
```
exception thrown: RuntimeError: abort(To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking) at Error
    at jsStackTrace (http://10.78.234.15:8080/hello.js:1712:19)
    at stackTrace (http://10.78.234.15:8080/hello.js:1734:16)
    at abort (http://10.78.234.15:8080/hello.js:1448:44)
    at _dlopen (http://10.78.234.15:8080/hello.js:4156:7)
    at http://10.78.234.15:8080/hello.wasm:wasm-function[19]:0xe47
    at main (http://10.78.234.15:8080/hello.wasm:wasm-function[59]:0x2235)
    at http://10.78.234.15:8080/hello.js:1498:22
    at callMain (http://10.78.234.15:8080/hello.js:5090:15)
    at doRun (http://10.78.234.15:8080/hello.js:5160:23)
    at http://10.78.234.15:8080/hello.js:5171:7,RuntimeError: abort(To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking) at Error
    at jsStackTrace (http://10.78.234.15:8080/hello.js:1712:19)
    at stackTrace (http://10.78.234.15:8080/hello.js:1734:16)
    at abort (http://10.78.234.15:8080/hello.js:1448:44)
    at _dlopen (http://10.78.234.15:8080/hello.js:4156:7)
    at http://10.78.234.15:8080/hello.wasm:wasm-function[19]:0xe47
    at main (http://10.78.234.15:8080/hello.wasm:wasm-function[59]:0x2235)
    at http://10.78.234.15:8080/hello.js:1498:22
    at callMain (http://10.78.234.15:8080/hello.js:5090:15)
    at doRun (http://10.78.234.15:8080/hello.js:5160:23)
    at http://10.78.234.15:8080/hello.js:5171:7
    at abort (http://10.78.234.15:8080/hello.js:1454:11)
    at _dlopen (http://10.78.234.15:8080/hello.js:4156:7)
    at http://10.78.234.15:8080/hello.wasm:wasm-function[19]:0xe47
    at main (http://10.78.234.15:8080/hello.wasm:wasm-function[59]:0x2235)
    at http://10.78.234.15:8080/hello.js:1498:22
    at callMain (http://10.78.234.15:8080/hello.js:5090:15)
    at doRun (http://10.78.234.15:8080/hello.js:5160:23)
    at http://10.78.234.15:8080/hello.js:5171:7
```

**Comment by sbc100** [comment]
If you are seeing that message it means you are somehow not linking with `-s MAIN_MODULE`.   The message is coming from here and only included when MAIN_MODULE=0:  https://github.com/emscripten-core/emscripten/blob/0c070488619cf556e4917cd88c0a868faf611c13/src/library_dylink.js#L178-L181

Try running `make VERBOSE=1` after removing `hello.js` to see the full command the cmake ends up using to link your program.

Also, if you want the side module to be loadable via `dlopen` you need to compile it `-s SIDE_MODULE` rather than `-shared`

**Comment by sbc100** [comment]
e.g: `emcc -s SIDE_MODULE -o libadd.so add.cpp`   (you can't use g++ to build your side modules)

**Comment by luopengting** [comment]
Thank you for your time. 

I compile libadd.so with `emcc -s SIDE_MODULE=1 -o libadd.so add.cpp`.

`make VERBOSE=1` is very useful!! Thx a lot! I change the **CMakeLists.txt**:
```
# stop if cmake version is below 3.0
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)

# project name and enable C++ support
project(hello LANGUAGES CXX)

# add env variables
set(CMAKE_EXECUTABLE_SUFFIX ".html")

# require C++11
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_compile_options(-fPIC)

message(STATUS "PROJECT_SOURCE_DIR: ${PROJECT_SOURCE_DIR}")
add_link_options("SHELL:-s MAIN_MODULE=1")
add_link_options("SHELL:-s EXPORT_ALL=1")

add_executable(hello main.cpp)
target_link_libraries(hello ${PROJECT_SOURCE_DIR}/libadd.so)

```

But the `dlopen()` **failed**.

Output:
```
path: /
=> come in main.
handle begin
handle done
open lib error
Could not load dynamic lib: /absolute-path/libadd.so(File exists.)
Error: No such file or directory
```

According to https://github.com/emscripten-core/emscripten/wiki/Linking, i can use `dlopen()` to open but it failed.

**Comment by sbc100** [comment]
If you want o use `dlopen()` then (for now) you also need to make the file available in your virtual filesystem.  I quickest way to do this is via `--embed-file` or the `--preload-file` options.   e.g. `add_link_options("SHELL: --embed-file="${PROJECT_SOURCE_DIR}/libadd.so")`.   Then emscripten will make sure that file is downloaded and added to the filesystem before the program starts running.

I have a recent change that should make this unnessary in certain circumstances: https://github.com/emscripten-core/emscripten/pull/14528, but its not part of a release yet.

If you are using `dlopen` then you also don't need to specify `target_link_libraries(hello ${PROJECT_SOURCE_DIR}/libadd.so)`.  That option is for libraries that are loaded at startup before `main`.

**Comment by luopengting** [comment]
> If you want o use `dlopen()` then (for now) you also need to make the file available in your virtual filesystem. I quickest way to do this is via `--embed-file` or the `--preload-file` options. e.g. `add_link_options("SHELL: --embed-file="${PROJECT_SOURCE_DIR}/libadd.so")`. Then emscripten will make sure that file is downloaded and added to the filesystem before the program starts running.
> 
> I have a recent change that should make this unnessary in certain circumstances: #14528, but its not part of a release yet.
> 
> If you are using `dlopen` then you also don't need to specify `target_link_libraries(hello ${PROJECT_SOURCE_DIR}/libadd.so)`. That option is for libraries that are loaded at startup before `main`.

I add `add_link_options("SHELL: --embed-file="${PROJECT_SOURCE_DIR}/libadd.so")` and add `extern "C"` for add.*. It works!! :D

Thx a lot!!! :D

It seems that only packages compiled by `emcc` or `emxx` can be linked. Can we directly link the .so package compiled by `gcc`/`g++`?

**Comment by sbc100** [comment]
Thats right,  emscripten is a cross compiler that compiles to WebAssembly.   normal/native versions of gcc and clang output have host binaries that cannot be run on the Web.

**Comment by sbc100** [comment]
Ok to close this issue now?

**Comment by luopengting** [comment]
Thx. You can close this issue. :D
