### ISSUE TITLE
Emscripten pthreads are printing dummy debug prints...

### ISSUE THREAD

**Issue by terop2** [emscripten-core/emscripten#14553]
when pthreads are used alot, the browser dev console is filled with debug prints like this:
 Pthread 0x4874847 exited.

This is coming from the generated .js file, and we currently are using sed to comment out the err() command from the js files to get rid of the debug prints. This isn't our ideal solution, so we consider ticket to emscripten to fix it for everyone who uses pthreads.

If we try to use pthread_exit(NULL); to exit the pthread before returning, it prints double amount of debug prints, so that wont help with the problem. The only solution that would fix the problem globally would be to remove the debug print from the emscripten source code. We currently use sed to binary-patch generated js files, and maybe there's better solution for this problem?

**Comment by sbc100** [comment]
Agreed, we should not be printing that stuff by default.  

It does looks like this should only be happening when ASSERTIONS is enabled though.  Are you seeing this in your releases builds too?   (We should probably put this behind the `PTHREADS_DEBUG` flag instead).
