### ISSUE TITLE
llvm-objcopy: error: 'a.out.wasm': Operation not permitted

### ISSUE THREAD

**Issue by Alexufo** [emscripten-core/emscripten#14587]
I trying to  run example from
https://emscripten.org/docs/getting_started/Tutorial.html#tutorial
and getting this error
![image](https://user-images.githubusercontent.com/1562329/124341473-553c7d80-dbc5-11eb-9b30-99d57085e5de.png)

I see wasm file in root emsdk of but no js file.

emcc -v  `emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.25`

It is windows WSl 2 (ubuntu 20).

**Comment by Alexufo** [comment]
`/mnt/c/emscripten/emsdk/upstream/emscripten$ sudo ./emcc ./w.c

It works with sudo

**Comment by OliverXH** [comment]
Switch to root:
`sudo passwd root` 
then
`su root`
