### ISSUE TITLE
.wasm size increase by 40% (64kB) from 2.0.17->2.0.25

### ISSUE THREAD

**Issue by Birch-san** [emscripten-core/emscripten#14596]
_(more context of how the source is built at https://github.com/emscripten-core/emscripten/issues/14583)_  
I've noticed that upgrading from 2.0.17->2.0.25, the .wasm size has now increased 162kB->226kB. this is 64kB or a 40% increase: any idea what change causes this and whether there's some benefit that justifies the size? is it the new LLVM libraries/runtime from 2.0.23 or something?

**Comment by kripken** [comment]
That's a pretty large range of changes, so I'd recommend bisection to find the specific change responsible for the regression,

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

That should be pretty fast once you get started.

**Comment by Birch-san** [comment]
Okay my bad; the problem was that I introduced a [regression](https://github.com/Birch-san/box2d-wasm/commit/6ec863d23d28bc8aced657d4d3280a66e656d07f#diff-885c90134a4da6981f7c2fb931312d27389c9c0695d79fb5d4cbc7593cdcc2ffR34) to my shell script, which I've now [fixed](https://github.com/Birch-san/box2d-wasm/commit/b7dab1d61d96cb28e268e2923dfb916211aa6432#diff-885c90134a4da6981f7c2fb931312d27389c9c0695d79fb5d4cbc7593cdcc2ff).

Box2D.wasm is back to 162kB on latest (2.0.25) Emscripten. 🙂
