### ISSUE TITLE
Runtime Error: The application has corrupted its heap memory area(address zero)

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14597]
when the subThread exit , there is a error .
Pthread aborting at Error at Object.checkStackCookie . RuntimeError :abort(Runtime Error: The application has corrupted its heap memory area(address zero)!) at jsStackTrace ;

in EmscriptenV2.0.16 ; and in EmscriptenV1.39 it has no error.

when use --preload-file aa.data , there is the error.

**Comment by sbc100** [comment]
Can you try bisecting to find out which version of emscripten/emsdk triggered this error:

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by yangfangfang1204** [comment]
i use `-o3` solve the problem.
