### ISSUE TITLE
Pass string by reference from JS to C++

### ISSUE THREAD

**Issue by ssg3d** [emscripten-core/emscripten#14598]
I need to pass huge strings from javascript to emscripten (its a front end app). This is what I do today:

void foo(const std::string& string)
{
    //  I only need to access the string, not make changes to it.
}
EMSCRIPTEN_BINDINGS(_projectname_)
{
    function("foo", &foo);
}

Ofcourse in JS I do this:
Module.foo("my string....lots of chars..i get it from XmlHttpResponse");

I suspect despite the function signature passing it by reference in C++ it is copied from JS to C++. Is there a way to avoid this? It's a significant performance drag.

**Comment by sbc100** [comment]
There is no way for C++ to directly access the string data in JS without having it be copied into linear memory.   So if you want a directly accessible string it will always involve a copy.

The only way to access the JS without duplicating it from C++ would be to access via some kind of API.  For example, if you use embind I believe you can treat the string as `val` and using the JS string methods on it.   But ultimately if you want to inspect all the chars in the string from native code by far the fastest way is going to be to copy the string into linear memory as you are doing now.

**Comment by ssg3d** [comment]
Thanks, @sbc100.
