### ISSUE TITLE
Web Worker deadlock

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#14608]
Hi, I develop the program that uses a lot of networking and so uses threads. However I stuck with error that blocking operation from Web Worker to main thread may block all program. I created such test:
server.c
```int test();
void* start_in_thread(void* params)
{
  while(1){
    printf("Inside thread\n");
    sleep(5);
  }
}
int main() {
    pthread_t thread;
    pthread_create(&thread, 0, start_in_thread, NULL);
    test();
}
```

library_test.js
```mergeInto(LibraryManager.library, {
  test__proxy: 'sync',
  test__sig: 'i',
  test: function() {
    return Asyncify.handleAsync(async () => {
           console.log("test");
      await new Promise(resolve =>{
        setTimeout(resolve, 300000)});
      return 1;
    });
  }
});
```

Compile command:
'emcc server.c -s ASYNCIFY -s'ASYNCIFY_IMPORTS=["test","emscripten_receive_on_main_thread_js"]' -sUSE_PTHREADS=1 -sPROXY_TO_PTHREAD=1 --js-library ./library_test.js -o server.html'

This program blocks without creation thread. Thread doesn't run. However, If I run without 'PROXY_TO_PTHREAD' program works fine. Can you explain this behaviour ?
(Program blocks in method 'emscripten_sync_run_in_main_thread').

**Comment by RReverser** [comment]
Are you using the latest Emscripten? If so, it should warn you by default in the console explaining why the blocking occurs and how to solve it (tldr: you need to use `PROXY_TO_PTHREAD` like you do or `PTHREAD_POOL_SIZE` setting).

**Comment by DiachenkoIgor** [comment]
I'm sorry, but you haven't understood. Blocking occurs when 'main' starts in web worker `-sPROXY_TO_PTHREAD=1`. I know about deadlock caused by blocking main page thread. However, in my situation I start program in web worker. I don't know how, but web workers block each other because of execution of js `test` function.

**Comment by RReverser** [comment]
Hmm I see. Perhaps it's because you use `test__proxy: 'sync'` which sounds like blocks intentionally? I don't know much about `PROXY_TO_PTHREAD` though, so will leave to someone else to answer.

Offtop: can you please format longer code snippets using

````
```cpp
code
````

instead of

````
`code`
````

?

If you do this, it will look much better with multiline form and proper highlighting, e.g.:

```cpp
void* start_in_thread(void* params)
{
  while(1){
    printf("Inside thread\n");
    sleep(5);
  }
}
int m
ain() {
    pthread_t thread;
    pthread_create(&thread, 0, start_in_thread, NULL);
    test();
}
```

**Comment by DiachenkoIgor** [comment]
Thank you for advice.

I have tried `test__proxy: 'sync'` and `test__proxy: 'async'`. There is no difference.

**Comment by ravisumit33** [comment]
@DiachenkoIgor The same happened with me when I instantiated wasm in a web worker. Adding `Module['mainScriptUrlOrBlob']=/* worker file url */` before instantiation solved the issue. Did this solve the issue for you?

Have a look at https://gist.github.com/xaliphostes/6869989fadfb055ea40c2987b1150549 for more detail.

**Comment by DiachenkoIgor** [comment]
@ravisumit33 I am sorry for long response. I don't instantiate wasm from worker. The problem is with blocking execution thread before another worker creation. So the question is: How to handle 'sleep' functionality without blocking event loop.
