### ISSUE TITLE
Memory leak accessing members through embind interface

### ISSUE THREAD

**Issue by enoua5** [emscripten-core/emscripten#14617]
EDIT: while the below information describes the context in which this was found, I have created a much more succinct example that showcases the problem [here](https://github.com/enoua5/emscripten-bug-14617).

---

I am running out of memory calling functions that don't even allocate memory. According to debug output, the allocation is taking place in `ClassName* emscripten::internal::MemberAccess<ParentClassName, ClassName>::getWire<ClassName>(ClassName ParentClassName::* const&, Game const&)`.

**Full error message**
![Screenshot of error message](https://user-images.githubusercontent.com/16809690/125144771-2601a100-e0dc-11eb-8697-67e52b58dadc.png)
_transcription_
```
[warning] undefined
  abort		@revengechess.js:1451
  _abort		@revengechess.js:3777
  operator new(unsigned long)		@revengechess.wasm:0x24fe3
  Clock* emscripten::internal::MemberAccess<Game, Clock>::getWire<Game>(Clock Game::* const&, Game const&)		@revengechess.wasm:0x1b98f
  get		@revengechess.js:3229
  showTimes		@infopane.js:146
  
[error] Uncaught RuntimeError: abort(undefined) at Error
  at jsStackTrace (revengechess.js:1747)
  at stackTrace (revengechess.js:1764)
  at abort (revengechess.js:1456)
  at _abort (revengechess.js:3777)
  at operator new(unsigned long) (revengechess.wasm:0x24fe3)
  at Clock* emscripten::internal::MemberAccess<Game, Clock>::getWire<Game>(Clock Game::* const&, Game const&)		(revengechess.wasm:0x1b98f)
  at Game.get [as clock] (revengechess.js:3229)
  at showTimes (infopane.js:146)
  at abort (revengechess.js:1462)
  at _abort (revengechess.js:3777)
  at operator new(unsigned long) (revengechess.wasm:0x24fe3)
  at Clock* emscripten::internal::MemberAccess<Game, Clock>::getWire<Game>(Clock Game::* const&, Game const&)		(revengechess.wasm:0x1b98f)
  at Game.get [as clock] (revengechess.js:3229)
  at showTimes (infopane.js:146)
```

**Compile settings**
`-O3 -s WASM=1 --bind --no-entry -s ABORTING_MALLOC=0`
Error happens at all optimization levels, with and without `aborting_malloc`, with and without `assertions`, and with and without `g`.

**Relevant code**
 _infopane.js:146_
(Game.game is an instance of Module.Game)
`if(Game.game.clock.getResultFromFlag() != Module.GameResult.ONGOING)`

_Clock binding_
```
class_<Clock>("Clock")
    .constructor<>()
    /* irrelevant functions */
    .function("getResultFromFlag", &Clock::getResultFromFlag)
;
```
_Game binding_
(Property clock is just `Clock clock`)
```
class_<Game>("Game")
    .constructor<>()
    .property("board", &Game::board)
    .property("clock", &Game::clock)
    /* irrelevant functions */
  ;
```

_getResultFromFlag()_
(GameResult is just an enum)
```
GameResult Clock::getResultFromFlag()
{
  if(white_timer.update() <= 0)
    return BLACK_VICTORY;
  else if(black_timer.update() <= 0)
    return WHITE_VICTORY;
  return ONGOING;
}
```

_update()_
```
unsigned int Timer::update() // returns timeLeft
{
  if(running)
  {
    timeSpentThisTurn = std::chrono::duration_cast<timer_res>(get_current_time() - lastToggle).count();
    
    if(incType == DELAY)
    {
      if(timeSpentThisTurn > increment)
      {
        if(timeLeftAtStartOfTurn < timeSpentThisTurn + increment)
          timeLeft = 0;
        else
          timeLeft = timeLeftAtStartOfTurn - timeSpentThisTurn + increment;
      }
    }
    else if(incType == NO_CLOCK)
      timeLeft = timeLeftAtStartOfTurn;
    else
    {
      if(timeLeftAtStartOfTurn < timeSpentThisTurn)
        timeLeft = 0;
      else
        timeLeft = timeLeftAtStartOfTurn - timeSpentThisTurn;
    }
  }
  return timeLeft;
}
```

And that's the extent of the calls.

**Other notes**
- I have a suspicion that this may be related to https://github.com/emscripten-core/emscripten/issues/12455, but I'm not sure.
- The leak seems to be small per access, and so is only relevant when accessing it frequently. Here the initial function is being called every 50 milliseconds, and the system is running out of memory somewhere around  14-15k times before running out of memory.
- OS is Ubuntu 20.04.2 64-bit, program is running on Chromium 91.0.4472.114 snap (64-bit), compiler is em++ 2.0.14
- I have now confirmed that this also occurs in Firefox 89.0.2 (64-bit), and em++ 2.0.25

**Comment by enoua5** [comment]
I have created a much more succinct example that showcases the problem: [repository](https://github.com/enoua5/emscripten-bug-14617)

**Comment by enoua5** [comment]
From what I can tell, it seems the memory is being allocated [here](https://github.com/emscripten-core/emscripten/blob/c515787ea5ee0a9b1f65b10c32b427ccb573e74c/system/include/emscripten/wire.h#L348), though I'm not familiar enough with the project to tell if this is the line being ran, or of it even matters.

**Comment by enoua5** [comment]
I missed the `.delete()` method when reading the docs. That solves my problem.

**Comment by yangfangfang1204** [comment]
Could you tell me when do I use delete and how to use delete() ? 
 I also find a memory leak
