### ISSUE TITLE
"long double" - performance penalty

### ISSUE THREAD

**Issue by kallaballa** [emscripten-core/emscripten#14612]
I've implement a fractal zoom in C++ that nicely compiles to wasm (and even amiga :)). For a fractal zoom precision in the mandelbrot routine is crucial for the zoom depth and so I played around with different precisions and found that while there is no real difference between using float and double there is a huge performance penalty for "long double" when compiling to wasm (while it performs fine on linux x86_64). Is that to be expected?

**Comment by kripken** [comment]
Yes. On `x86_64` I believe long double turns into fp80, which is supported in hardware. But in wasm, long double turns into a software-emulated float128.

**Comment by kallaballa** [comment]
thx!
