### ISSUE TITLE
INITIAL_MEMORY option is broken

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#14621]
I have set INITIAL_MEMORY to 134217728 and then got an error which said that I should set the value to 278505584, but after setting that I got this error,

`em++: error: INITIAL_MEMORY must be a multiple of WebAssembly page size (64KiB), was 278505584
`

Then, I have set it to `33554432`, but now I'm getting this error,

`wasm-ld: error: initial memory too small, 278505584 bytes needed`

**Comment by jeffRTC** [comment]
As a side note,  I do use `ALLOW_MEMORY_GROWTH` option but to use Sanitizers it still require `INITIAL_MEMORY ` option to be set. This is not the actual behavior according to your docs,

`You probably need to increase INITIAL_MEMORY to at least 64 MB **or** pass -s ALLOW_MEMORY_GROWTH so that ASan has enough memory to start
`

`emcc -gsource-map -fsanitize=address -s ALLOW_MEMORY_GROWTH buffer_overflow.c
`

My CMake settings looks like this, 
```
add_compile_options("SHELL: -s ALLOW_MEMORY_GROWTH=1")
add_link_options("SHELL: -s ALLOW_MEMORY_GROWTH=1")
```

**Comment by jeffRTC** [comment]
cc @sbc100 @kripken

**Comment by sbc100** [comment]
What if you take the value that wasm-ld is requiring (278505584) and round it up to nearest 64k page?   Or just round it up to 300Mb for good measure? 

Do you know wasm-ld is requiring 278Mb?  That seems quite high?  IIRC that means you have that much static data in your program?    Can you share `buffer_overflow.c` so we can see why that static data requirements are so high for that file?

**Comment by jeffRTC** [comment]
@sbc100  `buffer_overflow.c` is from your docs. I used it as a reference that `-s ALLOW_MEMORY_GROWTH ` should not require `INITIAL_MEMORY ` option but in my case I have to add it because it don't let me to compile. 

`Do you know wasm-ld is requiring 278Mb? 
`
How to checkthis?

**Comment by sbc100** [comment]
I see the problem.   ALLOW_MEMORY_GROWTH means that the asan shadow memory needs to handle memories as large as MAXIMUM_MEMORY, which by default is 2Gb. 

To fix the issue you can either increase your INITIAL_MEMORY (to handle the larger shadow memory size).. or set your MAXIMUM_MEMORY.

Going forward we should probably increase INITIAL_MEMORY automatically when using ASAN (or at least give a better error here).

**Comment by jeffRTC** [comment]
@sbc100  500 MB fixed the issue for me. So, close?
