### ISSUE TITLE
`USE_OFFSET_CONVERTER=1` incompatible with `WASM=0`

### ISSUE THREAD

**Issue by trybka** [emscripten-core/emscripten#14630]
Results in a runtime error when trying to initialize.

I don't have a strong preference, but it might be prudent to at least cause a link error when trying to set the two incompatible settings. Alternatively if WASM=0 we could just ignore if it was requested.

WDYT?

**Comment by trybka** [comment]
+cc @walkingeyerobot

**Comment by kripken** [comment]
Looks like the issue is
```
Error: abort(Error: abort(TypeError: WebAssembly.Module.customSections is not a function) at Error
```
Which makes sense, as `customSections` is provided by the wasm runtime, and we'd need to polyfill it.

An error for now sounds ok to me. I opened #14639
