### ISSUE TITLE
Access to the requestAnimationFrame timestamp?

### ISSUE THREAD

**Issue by icculus** [emscripten-core/emscripten#14644]
If calling emscripten_set_main_loop() with an fps of zero, Emscripten will use requestAnimationFrame to drive the main loop.

Is there some way to get access to the timestamp that requestAnimationFrame passes to the callback function?

My concern is that the mechanisms for querying this timestamp directly are being nerfed to protect against Spectre and such...

https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#reduced_time_precision

...not to mention that resistFingerprinting makes it have a 100ms precision! Assuming that the animation frame callback gets a more meaningful resolution than this, it would be useful to have it.

Is there a reasonable way to extract this information, or does this need a patch to Emscripten?

**Comment by kripken** [comment]
You can use the lower-level API `emscripten_request_animation_frame` for that:

https://emscripten.org/docs/api_reference/html5.h.html?highlight=emscripten_request_animation_frame#c.emscripten_request_animation_frame

**Comment by icculus** [comment]
Nice, this works like a champ, thank you!
