### ISSUE TITLE
ReferenceError: window is not defined!

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#14660]
I have written js library with such code:

```
mergeInto(LibraryManager.library, {
  $Holder:{
  location: window.location
  },
.......
}
```

My compile options `... --js-library ./library_test.js -s ENVIRONMENT=web,worker ....`

I receive such error: `Exception message: "ReferenceError: window is not defined" | ReferenceError: window is not defined`

**Comment by kripken** [comment]
If you run this code on a worker, then `window` will not be defined there. You can get the location in other ways:

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/location

In particular, `self.location` may work in all places.

**Comment by jeffRTC** [comment]
use `globalThis`
