### ISSUE TITLE
How to set the initial and maximum memory

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14663]
i compile the C code to `.js .worker.js and .wasm` by makefile. and compile script set `-s TOTAL_MEMORY =1000MB -s USE_PTHREADS =1 `.

In the .js 
`wasmMemory = new WebAssembly.Memory({
      'initial': INITIAL_INITIAL_MEMORY / WASM_PAGE_SIZE
      ,
      'maximum': INITIAL_INITIAL_MEMORY / WASM_PAGE_SIZE
      ,
      'shared': true
    });`

i find initial size is equal to maximum .so how set the initial memory size and maximum memory size respectively?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory#parameters

**Comment by RReverser** [comment]
> how set the initial memory size and maximum memory size respectively

Set [`INITIAL_MEMORY`](https://emsettings.surma.technology/#INITIAL_MEMORY) and [`MAXIMUM_MEMORY`](https://emsettings.surma.technology/#MAXIMUM_MEMORY).
