### ISSUE TITLE
Set INITIAL_MEMORY and MAXIMUM_MEMORY must -s ALLOW_MEMORY_GROWTH=1 ?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14667]
I Set INITIAL_MEMORY =100MB, and MAXIMUM_MEMORY = 1000MB, -s ALLOW_MEMORY_GROWTH=0
the .js is 
`new WebAssembly.Memory({"initial":INITIAL_MEMORY/65536,"maximum":INITIAL_MEMORY/65536,"shared":true})`;

and if i set  -s ALLOW_MEMORY_GROWTH=1:
the .js is 
`new WebAssembly.Memory({"initial":INITIAL_MEMORY/65536,"maximum":1048576e3/65536,"shared":true})`;

so if i want to use the Memory greater than 100MB , i must set `-s ALLOW_MEMORY_GROWTH=1` ?

**Comment by sbc100** [comment]
Yes, if you want the memory to grow at all you need `-sALLOW_MEMORY_GROWTH`.   Without this option memory cannot grow and `maximum` will always be the same as `initial`.

(if that answers your question place go ahead and close this issue).

**Comment by yangfangfang1204** [comment]
` INITIAL_MEMORY =100MB, and MAXIMUM_MEMORY = 1000MB, -s ALLOW_MEMORY_GROWTH=1`
If  i set `-s ALLOW_MEMORY_GROWTH=1 ` , the memory will not be greater than 1000MB. right? Because I also set `MAXIMUM_MEMORY = 1000MB` ?

**Comment by sbc100** [comment]
Yes exactly.   I fact, `MAXIMUM_MEMORY` only makes sense if `ALLOW_MEMORY_GROWTH` is enabled.

**Comment by yangfangfang1204** [comment]
i use pthread and set allow_memory_growth. `-s ALLOW_MEMORY_GROWTH=1 -s USE_PTHREADS=1` , And there is a warnning.
`USE_PTHREADS+ALLOW_MEMORY_GROWTH may run non-wasm code slowly`,  What's the effect?Running speed down?

**Comment by yangfangfang1204** [comment]
the compile is 
`-s USE_PTHREADS=1 -s INITIAL_MEMORY=100MB -s MAXIMUM_MEMORY=1000MB -s ALLOW_MEMORY_GROWTH=1 -s MAX_WEBGL_VERSION=2 -s USE_FREETYPE=1 -lopenal -s PTHREAD_POOL_SIZE_STRICT=0  -s OFFSCREENCANVAS_SUPPORT=1 -s PROXY_TO_PTHREAD=1`

**Comment by sbc100** [comment]
> i use pthread and set allow_memory_growth. `-s ALLOW_MEMORY_GROWTH=1 -s USE_PTHREADS=1` , And there is a warnning.
> `USE_PTHREADS+ALLOW_MEMORY_GROWTH may run non-wasm code slowly`, What's the effect?Running speed down?

Yes, as the warning says this configuration runs JS code more slowly, I believe because it need to constantly check for a detached memory.   Perhaps @kripken can quantify the slowdown.  

Obviously, if you can avoid that combination it would be good idea to do so.
