### ISSUE TITLE
emscripten_set_main_loop_timing fails

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#14665]
@sbc100 

The following fails at runtime

```
        emscripten_set_main_loop_arg(someFunction, this, 1, -1);
        emscripten_set_main_loop_timing(EM_TIMING_SETTIMEOUT, 5000);
```

`Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.`

**Comment by sbc100** [comment]
I was not able to reproduce using the following complete example:

```
#include <emscripten.h>
#include <stdio.h>

void someFunction(void* arg) {
  printf("callback %d\n", (int)arg);
}

int main () {
  printf("main\n");
  emscripten_set_main_loop_arg(someFunction, (void*)1, 1, -1);
  emscripten_set_main_loop_timing(EM_TIMING_SETTIMEOUT, 1000);
  printf("done\n");
  return 0;
}
```

Maybe something else is going on here?

**Comment by sbc100** [comment]
Also the final argument to emscripten_set_main_loop_arg (simulate_infinite_loop) should probably be 1 or a 0.   I'm not sure what are you trying to do by passing `-1` there?

**Comment by jeffRTC** [comment]
This `-1` thing was from a stackoverflow answer. I tried `0 `but still same issue.

`  emscripten_set_main_loop_arg(&someFunction,  this, 0);
`
I call it inside a Class method and pass `this` as arg..

someFunction is also static void member function of the same class.

**Comment by jeffRTC** [comment]
Did you build with Assertion  enabled and -g flag?

**Comment by sbc100** [comment]
I build with no flags at all which defaults to `-O0` + `-sASSERTIONS`.. so yes I'm building with assertions.  Can you repro with my example code above?

**Comment by sbc100** [comment]
I'm building with `emcc test.c -o out.html`

**Comment by jeffRTC** [comment]
@sbc100 I'm planning to work out on this very soon. Been busy....

**Comment by jeffRTC** [comment]
@sbc100 it's working after clearing cmake cache
