### ISSUE TITLE
missing license for tools/ports/libpng.py and tests/third_party/libpng/pngtest.c

### ISSUE THREAD

**Issue by jonassmedegaard** [emscripten-core/emscripten#14687]
The file `tools/ports/libpng.py` contains the following notice:
> /* This code is released under the libpng license. */
> /* For conditions of distribution and use, see the disclaimer */
> /* and license in png.h */

The file `tests/third_party/libpng/pngtest.c` contains a similar notice.

The referenced file `png.h` is missing from this redistribution of the code.

Possibly the actual license is [libpng License](https://spdx.org/licenses/Libpng.html) or maybe it is [PNG Reference Library version 2](https://spdx.org/licenses/libpng-2.0.html) - both of which requiring inclusion of the full license text to comply with the license.

Please either ensure to comply with the granted license, or remove the code which is then (most likely - depending on the license which is currently unclear) **effectively not licensed for your redistribution of it**.

See also issue #12795 about one of the files. That issue report was seemingly repurposed for tracking _placement_ of third-party code: It was closed without solving the licensing issue.

**Comment by kripken** [comment]
Thanks @jonassmedegaard , I opened #14692 for this now.
