### ISSUE TITLE
tools/debug/bisect_pair_lines.py fails to compile: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jonassmedegaard** [emscripten-core/emscripten#14696]
File `tools/debug/bisect_pair_lines.py` fails to compile:
>   File "/usr/share/emscripten/tools/debug/bisect_pair_lines.py", line 25
>     shutil.copyfile(sys.argv[1], 'left')
>     ^
> SyntaxError: invalid syntax

**Comment by jonassmedegaard** [comment]
Likely directly related to #14074

**Comment by jonassmedegaard** [comment]
Comparing with the similar code in `tools/debug/bisect_pair_wast.py`, maybe this is the fix:
```patch
--- a/tools/debug/bisect_pair_lines.py
+++ b/tools/debug/bisect_pair_lines.py
@@ -20,7 +20,7 @@ __rootpath__ = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
 def path_from_root(*pathelems):
   return os.path.join(__rootpath__, *pathelems)

-exec(Path(path_from_root('tools', 'shared.py').read())
+exec(Path(path_from_root('tools', 'shared.py')).read_text())

 shutil.copyfile(sys.argv[1], 'left')
 shutil.copyfile(sys.argv[2], 'right')
```

I am not strong in python, but at least that silences the error... :-/

**Comment by sbc100** [comment]
Looks like a lot of the files in the directory could use some attention and possibly we can/should remove some of them..  I've never used them myself in many years working on emscripten.
