### ISSUE TITLE
🙋‍♂️ How can I get persistent data working on Windows?

### ISSUE THREAD

**Issue by danbugs** [emscripten-core/emscripten#14708]
I was trying to piece together info from the docs on the [File System API](https://emscripten.org/docs/api_reference/Filesystem-API.html) and [tests](https://github.com/emscripten-core/emscripten/blob/main/tests/fs/test_idbfs_fsync.c) on the feature itself to get it to work but got no luck so far.

The problem with the tests in my case is that they include the `unistd.h` header file (for things like `write`, ` fsync`, and `close`) , which is specifically for Unix systems. After learning that, I tried using WSL to compile my code but that seems to break `emcc` _sometimes_ (which never happened to me before, just now when working with files).

What is a good substitute to `unistd.h` on Windows?

Plus, is this more or less what I have to to do to get persistent data working?
```
#include <stdio.h>
#include <emscripten.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>

int result = 1;

int main()
{
    int fd;

    EM_ASM(FS.mount(IDBFS, {}, "/persistent_data/"));

    struct stat st;

    // a file whose contents are just 'az'
    if ((stat("/persistent_data/test.txt", &st) != -1) || (errno != ENOENT))
    {
        result = -1000 - errno;
    }

    fd = open("/persistent_data/test.txt", O_RDWR | O_CREAT, 0666);

    if (fd == -1)
    {
        result = -2000 - errno;
    }
    else
    {
        if (write(fd, "az", 2) != 2)
        {
            result = -3000 - errno;
        }
        if (fsync(fd) != 0)
        {
            result = -4000 - errno;
        }
        if (close(fd) != 0)
        {
            result = -5000 - errno;
        }
    }
    printf("Result: %d\n", result);
}
``` 
> That is: mount → open/read/write → fsync → close?

On the few times I actually managed to compile w/ WSL, nothing seemed to be being written to my `test.txt` file and the result variable was still coming out as `1`.

FYI, I'm compiling like: `emcc src/main.cpp -o main.js --preload-file persistent_data/test.txt -l"idbfs.js"` (added the `"`  around `idbfs.js` 'cause I'd get an error on Windows otherwise).

Any help is much appreciated! Thanks ;D

**Comment by danbugs** [comment]
To add onto my previous comment, I just want to clarify that I understand that we have to:
1) Add `-lidbfs.js`  during compilation
2) Sync the filesystem,
3) Perform operations (i.e., read/write), and
4) Sync the filesystem again. 

From this, I guessed that I could just completely drop `unistd.h` and do operations normally (i.e., with `fopen`, `fgetc`, `fwrite`, etc.) and just sync w/ an `EM_ASM` call to `FS.syncfs`. With that, my only problem is that even the simplest sort of sync is failing me 😅

That is, if I do:

```
#include <stdio.h>
#include <emscripten.h>

extern "C"
{
    int main()
    {
        EM_ASM(
            FS.mkdir("/offline");
            FS.mount(IDBFS, {}, '/offline');

            FS.syncfs(
                true, function(err) {
                    console.log("smt went wrong");
                }););
    }
}
``` 

After compiling with `emcc src/main.cpp -o main.js -l"idbfs.js"` and going to the browser (where I'm running a server w/ `py -m http.server`), I get "smt went wrong" in the console. BUT... What am I doing wrong?

**Comment by sbc100** [comment]
I think perhaps you are misunderstand what the emscripten "filesystem" is capable of.    emscripten can't write to your actual disk because the code is running on the web, and the web platform doesn't expose the native filesystem to the code running in the browser.    

emscripten's filesystem store data in other places, in this case IDBFS, which lives in your browser profile and not anywhere easily accessible/visible in the OS filesystem.

**Comment by danbugs** [comment]
Ooo, I see — Thank you for the clarification, @sbc100 !

To follow-up on that, considering what you said, does that mean that the information is persistent only until the users hard-clean their browser (i.e., clean things like cache and whatnot)? Plus, I'm guessing that means that, even if users are accessing my site hosted on a webserver, the information is only local to their computer — right? That is, there's no way users could share information, huh? If so, is there any way I could have the file created on the webserver where I'd host the application so several users can have access to the same data?

**Comment by sbc100** [comment]
You can use MEMFS (in memory filesystem) pro-populate the filesystem with files from your webserver if you like.    

See https://emscripten.org/docs/porting/files/file_systems_overview.html#file-system-overview for more information on how the filesystem layer works.

**Comment by danbugs** [comment]
I've used the `MEMFS` before but, problem is, it doesn't persist information — right? Also, I didn't really have info to pre-populate but just wanted users to have access to each other's data they entered while on the app. Is that possible, @sbc100 ?

**Comment by sbc100** [comment]
You can't do that out-of-box with emscripten no.   You would need some kind of remote filesystem API based on emscripten_wget() or some other JS ABI that is backed by fetch/XMLHttpRequest.   Each time a client wants to list a directory or get a file you would want to make a call the server in this way.   Is it hard requirement that normal block C API for file access work for you?   Its not a great fit since it is a synchronous/blocking API.    You might want to look into creating you own JS library and calling that instead.

**Comment by danbugs** [comment]
> You can't do that out-of-box with emscripten no.

Ooo, that's too bad! 

> Is it hard requirement that normal block C API for file access work for you?

To answer your question, I don't really have any hard requirements — just an idea I wanted to play around with, to be honest. Anyway, I've managed to get data to persist so I'll close the issue now. Thanks for all the ideas and for answering my questions! ;D
