### ISSUE TITLE
Docs site reports wrong version

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#14726]
Since we starting setting the emscripten version in git to the "next" release rather than the "previous" release the docs site now contains the wrong version and indeed the title of the site iself is misleading see:

https://emscripten.org/docs/introducing_emscripten/release_notes.html

It looks like we can either modify the `conf.py` to do something different, or we can checkout the last release when we build the docs.

One option would be to run `git describe --tags` rather than try to parse emscripten-version.txt in `conf.py`?

**Comment by kripken** [comment]
What does LLVM do here?

Glancing at the website, the docs page refers to LLVM 13, while the offered download is LLVM 12, so it's also off by one, like us?

**Comment by kripken** [comment]
Perhaps we could add "(dev)", making it `x.y.z (dev)`?

**Comment by sbc100** [comment]
Interesting that they also publish docs for unreleased vesions.. they do have a note though "If you are using a released version of LLVM, see the download page to find your documentation." : https://llvm.org/docs/

**Comment by kripken** [comment]
Interesting that they provide the docs as a download. Maybe we should do that eventually... We could also refer people to check out the emscripten repo and build the docs locally, for past versions.

For now I think adding " (dev)" to the reported version might be enough.

**Comment by sbc100** [comment]
OK that should be easy enough to modify conf.py
