### ISSUE TITLE
Avoid linking libc++

### ISSUE THREAD

**Issue by graphitemaster** [emscripten-core/emscripten#14723]
I have a codebase which uses `gcc` and `clang` with `-xc++` to compile C++ code to skip linking libc++ (which it does not use). Invoking `emcc` the same way doesn't appear to share in this behavior. Emscripten always generates a `libc++.a` and includes it into the resulting binary bloating the size. Is there a way to force disable the inclusion of it? It looks like `EMCC_FORCE_STDLIBS` may be an option but I'm not sure.

**Comment by sbc100** [comment]
We should probably fix that, however there is specific flag you can pass to disable linking with libc++: `-nostdlib++`.   Does that work for you?

BTW, as will all libraries, adding libc++ to the command line without actually using any symbols from within it should have no effect.    Are you perhaps linking with `-sMAIN_MODULE` or `-Wl,-whole-archive` or some other flag that might force it to be included even when it is not used?   

If you are linking with `-sMAIN_MODULE` then you might want to consider `-sMAIN_MODULE=2` which includes only what is needed.
