### ISSUE TITLE
please add -S "NO_FOAM" to the settings.js :)

### ISSUE THREAD

**Issue by yishengjiang99** [emscripten-core/emscripten#14741]
no particular reason.. I'd just like this Makefile to not throw a compile error

```
-s EXTRA_EXPORTED_RUNTIME_METHODS=['ccall','AsciiToString'] \
    -s EXPORTED_FUNCTIONS=['_filterForZone','_malloc','_free','_loadpdta','_findByPid','_shdrref','_presetRef'] \
    -s INITIAL_MEMORY=164mb              \
    -s USE_ES6_IMPORT_META=0 \
    -s ENVIRONMENT=web \
    --js-library=lib.js \
    -s MODULARIZE=1 \
    -s SINGLE_FILE=1 \
    -s EXIT_RUNTIME=0 \
    -s EXPORT_ES6=1 \
    -s EXIT_RUNTIME=0 \
    -s NO_FOAM
```

**Comment by sbc100** [comment]
I don't understand... why would you want this?  What does `NO_FOAM` mean?

**Comment by yishengjiang99** [comment]
https://youtu.be/wU-L3eAWfnw

**Comment by juj** [comment]
This is maybe a misunderstood 1st of April type of request. Or maybe a passive-aggressive way of criticizing the large number of -s settings that Emscripten has - unlike other compilers. Closing. (if you want, you can edit emcc.py yourself for such changes)

**Comment by yishengjiang99** [comment]
any comparison to Emma Roberts is an an exalted praise, no aggressiveness here.

> This is maybe a misunderstood 1st of April type of request. Or maybe a passive-aggressive way of criticizing the large number of -s settings that Emscripten has - unlike other compilers. Closing. (if you want, you can edit emcc.py yourself for such changes)

**Comment by sbc100** [comment]
Maybe a seasonal `-s PUMPKIN_SPICE`?
