### ISSUE TITLE
Project breaks from sdk-2.0.26-64bit

### ISSUE THREAD

**Issue by cuinjune** [emscripten-core/emscripten#14761]
I already posted about this here: https://github.com/emscripten-core/emsdk/issues/860 but I'm posting here again hoping that I could get some answer. 

My project works fine when I install and activate with sdk-2.0.25-64bit, but it breaks with sdk-2.0.26-64bit.

If I compile it, I don't see any difference in the console output, but I get an error when running in the browser.

Here's the error message from the browser console:
```
(index):181 exception thrown: ReferenceError: rv is not defined,ReferenceError: rv is not defined
    at Pd$setNoGui [as setNoGui] (eval at new_ (http://localhost:5000/main.js:1:641669), <anonymous>:12:70)
    at Object.mainInit (http://localhost:5000/:199:14)
    at __mainInit (http://localhost:5000/main.js:1:496474)
    at __original_main (http://localhost:5000/main.wasm:wasm-function[250]:0x8fb11)
    at main (http://localhost:5000/main.wasm:wasm-function[251]:0x8fb23)
    at ret.<computed> (http://localhost:5000/main.js:1:643121)
    at Module._main (http://localhost:5000/main.js:1:1220427)
    at callMain (http://localhost:5000/main.js:1:3989400)
    at doRun (http://localhost:5000/main.js:1:3990044)
    at run (http://localhost:5000/main.js:1:3990216)
```

And this is what I use to build my project:

```
build: $(SRC_FILES) $(DESTDIR)
	emcc $(CFLAGS) -s MAIN_MODULE=1 --bind -o $(TARGET) $(SRC_FILES) \
	-s ASYNCIFY -s "ASYNCIFY_IMPORTS=['__Pd_loadLib']" \
	-s USE_SDL=2 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s ALLOW_MEMORY_GROWTH=1 \
	-s FORCE_FILESYSTEM=1 -s "EXPORTED_RUNTIME_METHODS=['FS']" \
	--no-heap-copy --preload-file $(DESTDIR) $(LDFLAGS)
	@echo "emscripten build succeeded!"
```

Any idea what could be causing this issue? Thanks in advance!

**ADDED:** It seems the error occurs when I try to call any functions under `EMSCRIPTEN_BINDINGS` from JavaScript:

```
EMSCRIPTEN_BINDINGS(Pd_class) {
  class_<Pd>("Pd")
    .constructor<>()
    .function("init", &Pd::init)
    .function("clear", &Pd::clear)
    .function("getNoGui", &Pd::getNoGui)
    .function("setNoGui", &Pd::setNoGui)
    ;
}
```

I think this part is where it causes the "rv is not defined" error:

```
(function anonymous(throwBindingError,invoker,fn,runDestructors,retType,classParam,argType0,Asyncify
) {
return function Pd$setNoGui(arg0) {
if (arguments.length !== 1) {
throwBindingError('function Pd.setNoGui called with ' + arguments.length + ' arguments, expected 1 args!');
}
var thisWired = classParam.toWireType(null, this);
var arg0Wired = argType0.toWireType(null, arg0); // bool
invoker(fn, thisWired, arg0Wired);
function onDone(rv) {
}
return Asyncify.currData ? Asyncify.whenDone().then(onDone) : onDone(rv);
}

})
```

**UPDATE:** The error is gone if I remove `-s ASYNCIFY -s "ASYNCIFY_IMPORTS=['__Pd_loadLib']"` from build command, but then I cannot use the Asyncify features.
The above code is now being generated as the following:

```
(function anonymous(throwBindingError,invoker,fn,runDestructors,retType,classParam,argType0
) {
return function Pd$setNoGui(arg0) {
if (arguments.length !== 1) {
throwBindingError('function Pd.setNoGui called with ' + arguments.length + ' arguments, expected 1 args!');
}
var thisWired = classParam.toWireType(null, this);
var arg0Wired = argType0.toWireType(null, arg0); // bool
invoker(fn, thisWired, arg0Wired);
}

})
```
When I build with sdk-2.0.25-64bit, it generates the identical code as the right above one even if I include the `-s ASYNCIFY -s "ASYNCIFY_IMPORTS=['__Pd_loadLib']"` flag in the command.

So I guess this could be a bug because sdk-2.0.26-64bit seems to generate code for Asyncify even for functions under `EMSCRIPTEN_BINDINGS`?

**Comment by sbc100** [comment]
@RReverser might know about this?

It might be worth bisecting to specific change: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by RReverser** [comment]
Looks like related to Embind+Asyncify changes when return type is... idk, void? Hard to tell without seeing the specific function, but let me add a test.

**Comment by RReverser** [comment]
Thanks for the report. Fix in https://github.com/emscripten-core/emscripten/pull/14764.

**Comment by cuinjune** [comment]
@RReverser Thank you so much for fixing this issue. I tested the changed code and it works fine now.
May I ask when I can expect to get the latest Emscripten build that has the changes applied?
I used the following commands but it doesn't seem the changes are applied to the latest build.

```
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
```

**Comment by kripken** [comment]
The fix landed after the last release. Until we tag another release, you can use `tot` (tip of tree) instead of `latest`.

**Comment by cuinjune** [comment]
Got it, Thank you!
