### ISSUE TITLE
using set(CMAKE_EXECUTABLE_SUFFIX ".html")  breaks include(CheckCSourceRuns)

### ISSUE THREAD

**Issue by ericoporto** [emscripten-core/emscripten#14762]
I have a project that builds fine with Emscripten 2.0.16, but it breaks with the latest emsdk.

The problem is it's CMake script tries to build things to test if it has a capability

```CMake
check_c_source_runs("
        static int notsupported = 1;
        void test_ctor (void) __attribute__((constructor));
        void test_ctor (void) { notsupported = 0; }
        int main(void) { return (notsupported); }
        "  HAS_CONSTRUCTOR)
```

But this actually appears to build fine with 2.0.16. Show I not do a test like above when using Emcmake ?

Edit: made a test for this specifically -> **https://github.com/emscripten-core/emscripten/compare/main...ericoporto:test_check_c_source_runs**

unfortunately it doesn't fail, so [it's possibly some flag from my cmake script](https://github.com/ericoporto/ags/blob/emscripten/CMakeLists.txt#L114-L165) or something I am not seeing in [it's cmake script](https://github.com/ericoporto/ags/blob/emscripten/libsrc/allegro/CMakeLists.txt#L112-L118) that causes it to fail, but it does build fine with 2.0.16. :/

**Comment by sbc100** [comment]
Can you give some more details?  How exactly does it fail?   Can you show the command line you use and its output?   Any chance you could share a CMakeLists.txt that fails?

**Comment by ericoporto** [comment]
I would prefer if it was something I could put on the cake tests repository so it doesn't break again.

https://github.com/emscripten-core/emscripten/tree/main/tests/cmake

But this the most empty place ever, can you place a README here telling how to make these work? Or a script, just something to guide how to actually execute these!

**Comment by sbc100** [comment]
These test are part of the emscripten test suite which is documented here: https://emscripten.org/docs/getting_started/test-suite.html

The specific names of the tests to run you can find by looking that thest test_core.py and test_other.py files.   I quick git grep shows the following tests are likely the relevant ones:

```
$ git grep "def test_.*cmake" tests/test*.py
tests/test_core.py:  def test_zlib(self, use_cmake):
tests/test_core.py:  def test_bullet(self, use_cmake):
tests/test_other.py:  def test_cmake(self, test_dir, output_file, cmake_args):
tests/test_other.py:  def test_cmake_compile_features(self):
tests/test_other.py:  def test_cmake_with_embind_cpp11_mode(self):
tests/test_other.py:  def test_cmake_bitcode_static_libraries(self):
tests/test_other.py:  def test_cmake_static_lib(self, custom):
tests/test_other.py:  def test_cmake_emscripten_version(self):
tests/test_other.py:  def test_cmake_find_stuff(self):
tests/test_other.py:  def test_cmake_install(self):
```

To run a test from test_other.py you would run `./tests/runner other.test_cmake`.   To run a tests from test_core.py you would use something like `./tests/runner wasm2.test_bullet` (where wasm2 is one of the test suite variant names defined here: https://github.com/emscripten-core/emscripten/blob/16ff7282dc3ab1327209430c97b4450c9ea0aeb7/tests/test_core.py#L8630-L8674

**Comment by ericoporto** [comment]
ok, I am back at figuring out this again. Question, should the test runner be able to run on Windows or I should really use a Linux environment for it?

**Comment by sbc100** [comment]
Test runner works on windows.  We run the whole test suite on windows are part of our CI.

**Comment by sbc100** [comment]
We have some docs that might be helpful: https://emscripten.org/docs/getting_started/test-suite.html

**Comment by ericoporto** [comment]
ok, I managed to run on Linux (I will figure on Windows later). Unfortunately, I have a problem there, the following test is failing:

```
test_cmake_bitcode_static_libraries (test_other.other) ... ok
test_cmake_compile_features (test_other.other) ... FAIL
test_cmake_emscripten_version (test_other.other) ... ok
test_cmake_find_stuff (test_other.other) ... ok
test_cmake_html (test_other.other) ... ok
test_cmake_install (test_other.other) ... ok
test_cmake_js (test_other.other) ... ok
test_cmake_library (test_other.other) ... ok
test_cmake_post_build (test_other.other) ... ok
test_cmake_static_cpp (test_other.other) ... ok
test_cmake_static_lib (test_other.other) ... ok
test_cmake_static_lib__suffix (test_other.other) ... ok
test_cmake_stdproperty (test_other.other) ... ok
test_cmake_with_embind_cpp11_mode (test_other.other) ... ok
```

the `test_cmake_compile_features` is erroring on Ubuntu:

```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/home/erico/git/emsdk/upstream/bin/clang++"

  is not able to compile a simple test program.
```

Any idea why?

**Comment by sbc100** [comment]
You can run that test on its own with `--save-dir` and it will save the cmake error log:

`./tests/runner other.test_cmake_compile_features --save-dir -v`

**Comment by ericoporto** [comment]
I hastly wrote a test but it's working as it appears... I will try again tomorrow, to figure out.

https://github.com/emscripten-core/emscripten/compare/main...ericoporto:test_check_c_source_runs

**Comment by sbc100** [comment]
After running that take a look in /tmp/emscripten_test/ for the cmake logs

**Comment by sbc100** [comment]
emsdk is still contained.   You don't need any pre-installed compiler to use emscripten.   That test does use our version of clang to build a native project so maybe that test has some dependency on the system libc or linker that is not well documented.

**Comment by ericoporto** [comment]
> maybe that test has some dependency on the system libc or linker that is not well documented.

I think you are right, I found this on CMakeErrror.log:
```
The output was:
1
/usr/bin/ld: cannot find -lstdc++
```

**Comment by sbc100** [comment]
Indeed, it looks like that one test does depend on a working local dev toolchain.   Feel free to ignore the failure, or install the needed packages (probably `build-essential` or `libstdc++` is all that is needed).

**Comment by ericoporto** [comment]
I tried adding all possible flags to cmake test and it still didn't fail the error I have in my AGS Emscripten port... Some flag causes my the check c source runs to produce html files with the latest version, but on 2.0.16 it produced js files... Unfortunately after trying lots of ideas, I can't seem to figure why.

```
CMake Error: Unable to find the executable at any of:
  /home/USER/git/ags/build/CMakeFiles/CMakeTmp/cmTC_9b76f.html
  /home/USER/git/ags/build/CMakeFiles/CMakeTmp/Debug/cmTC_9b76f.html
  /home/USER/git/ags/build/CMakeFiles/CMakeTmp/Development/cmTC_9b76f.html
```

**Comment by ericoporto** [comment]
ok, so it appears it's `set(CMAKE_EXECUTABLE_SUFFIX ".html")` in `CMakeLists.txt`

I experimented with various versions of emsdk, found out `2.0.24` is the last version the `check_c_source_runs` worked and after that, in `2.0.25`, it started to not work anymore and instead produce html files that can't be run instead of js.

https://github.com/emscripten-core/emscripten/compare/main...ericoporto:test_check_c_source_runs

**Comment by ericoporto** [comment]
@sbc100 is it possible to do something like `./emsdk install 2.0.24` but instead passing commit hashes? I wanted to see if I can findout what broke experimentally since by reading commit messages there's nothing obvious.

**Comment by sbc100** [comment]
Yes, we have instructions for bisecting here: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by tuket** [comment]
I have the same problem when using `set(CMAKE_EXECUTABLE_SUFFIX ".html")`.
Do you know of any workaround?

**Comment by ericoporto** [comment]
I ran my tests, noted down the results, and manually set the values. It's dumb but it was the workaround.

**Comment by tuket** [comment]
Mmh, I'm not running tests. I get the error when I build my project.
Thanks!
