### ISSUE TITLE
A range of Unicode code points is wrong

### ISSUE THREAD

**Issue by on-keyday** [emscripten-core/emscripten#14784]
This is very simple and maybe not essential issue.
At ```runtime_strings.js``` line 190 ,
a range of valid Unicode code points is actually 0-0x10FFFF
but this message shows 0-0x1FFFFF is valid.
```
#if ASSERTIONS
      if (u >= 0x200000) warnOnce('Invalid Unicode code point 0x' + u.toString(16) + ' encountered when serializing a JS string to a UTF-8 string in wasm memory! (Valid unicode code points should be in range 0-0x1FFFFF).');
#endif
```
So it need to rewrite ```u>=0x200000``` to ```u>=0x110000``` and ```0-0x1FFFFF``` to ```0-0x10FFFF```.

evidence:
https://www.unicode.org/faq/blocks_ranges.html

**Comment by sbc100** [comment]
Sounds correct.  Would you mind submitting a PR to change that?  (I will also mark this as help wanted).
