### ISSUE TITLE
Possible regression in 2.0.26. now seeing error 'TypeError: Cannot read property 'ENOENT' of undefined'

### ISSUE THREAD

**Issue by kevodwyer** [emscripten-core/emscripten#14783]
I am a developer on the boxedwine.org (emulator that runs Windows applications)
We have had a WASM build for a number of years (and before that a asm.js build)

I recently tried building with 2.26
And now receive an error running a test program:

```
Uncaught RuntimeError: abort(TypeError: Cannot read property 'ENOENT' of undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (boxedwine.js:501)
    at ___sys_access (boxedwine.js:4188)
    at access (boxedwine.wasm:0x4db30)
    at Fs::doesNativePathExist(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&) (boxedwine.wasm:0x16911)
    at FsFileNode::rename(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&) (boxedwine.wasm:0x11bdff)
    at syscall_rename(CPU*, unsigned int) (boxedwine.wasm:0x72414)
    at normal_int80(CPU*, DecodedOp*) (boxedwine.wasm:0xb7912)
    at NormalBlock::run(CPU*) (boxedwine.wasm:0x10b6e6)
    at NormalCPU::run() (boxedwine.wasm:0x10b293)
    at mainloop() (boxedwine.wasm:0xd5849)
```

Where sys_access looks like:

```
function ___sys_access(path, amode) {
 try {
  path = SYSCALLS.getStr(path);
  return SYSCALLS.doAccess(path, amode);
 } catch (e) {
  if (typeof FS === "undefined" || !(e instanceof FS.ErrnoError)) abort(e);
  return -e.errno;
 }
}
```

Neither Boxedwine (https://github.com/danoon2/Boxedwine) or the version of BrowserFS used (https://github.com/jvilk/BrowserFS) has changed.

I confirmed that the error is not present in 2.0.25 when run against the same source.

I can work around it by removing the offending line:
if (typeof FS === "undefined" || !(e instanceof FS.ErrnoError)) abort(e);
But that line has not changed between versions, the regression must be elsewhere.

**Comment by kripken** [comment]
Try manually removing the try-catch to get a clearer error in the console. If that doesn't help, [bisection might](https://emscripten.org/docs/contributing/developers_guide.html#bisecting).

My guess is that there is an out of tree FS implementation (BrowserFS?) that needs to be updated for internal emscripten changes. My first guess would be #14722 but that landed after 2.0.26 if I read the changelog right.

**Comment by sbc100** [comment]
I think this was probably #14730.    I would guess that here is a missing `__deps` on `$ERRNO_CODES` in https://github.com/jvilk/BrowserFS.   Before #14730 it was much more likely that `$ERRNO_CODES`  would be pulled in by some indirect dependency.

**Comment by kevodwyer** [comment]
have added param to command line and all is now fine.
-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE='["$ERRNO_CODES"]'
