### ISSUE TITLE
logger.debug(f'(not saving intermediate {name} because not generating JS)')

### ISSUE THREAD

**Issue by ChristopherXuY** [emscripten-core/emscripten#14781]
After install emscripten,when I use emcc,turn out this problem:

 File "/root/emsdk/upstream/emscripten/emcc.py", line 164
    logger.debug(f'(not saving intermediate {name} because not generating JS)')
                                                                             ^
SyntaxError: invalid syntax

I can't figure out why.

**Comment by HarryGifford** [comment]
It looks like you're trying to run `emcc` using Python 2.x. Check that you have Python 3 on your path.

**Comment by ChristopherXuY** [comment]
> It looks like you're trying to run `emcc` using Python 2.x. Check that you have Python 3 on your path.

yes,I find this problem,I finally use docker to run emcc,tks!
