### ISSUE TITLE
function signature mismatch error when calling GLES2_CreateRenderer with MAIN_MODULE enabled

### ISSUE THREAD

**Issue by chkuendig** [emscripten-core/emscripten#14801]
Build command: 
`emcc -o main.html -g -s MAIN_MODULE=1 -s USE_SDL=2  -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2  main.cpp`

When compiling a simple main.cpp as in #13101 and  #13086,  this works without problems. But when trying with a sample which uses SDL_CreateRenderer, this breaks when SDL_CreateRenderer calls GLES2_CreateRenderer.

This can be easily reproduced with the unchanged hello_triangle.cpp from here (and presumably many other SDL apps with GLES2) : https://gist.github.com/SuperV1234/5c5ad838fe5fe1bf54f9

command: 
`emcc -o main.html -g -s MAIN_MODULE=1 -s USE_SDL=2  -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2  hello_triangle.cpp`

when opening in chrome, this results in the following exception:

```
main.html:1246 exception thrown: RuntimeError: null function or function signature mismatch,RuntimeError: null function or function signature mismatch
    at GLES2_CreateRenderer (<anonymous>:wasm-function[1268]:0xbf75b)
    at SDL_CreateRenderer (<anonymous>:wasm-function[1170]:0xb6c41)
    at main (<anonymous>:wasm-function[502]:0x8fbd0)
    at Module._main (http://localhost:8080/main.js:29114:60)
    at callMain (http://localhost:8080/main.js:71848:15)
    at doRun (http://localhost:8080/main.js:71921:23)
    at http://localhost:8080/main.js:71932:7
printErr @ main.html:1246
callMain @ main.js:71868
doRun @ main.js:71921
(anonymous) @ main.js:71932
setTimeout (async)
run @ main.js:71928
runCaller @ main.js:71824
removeRunDependency @ main.js:1252
receiveInstance @ main.js:1393
receiveInstantiationResult @ main.js:1402
Promise.then (async)
instantiateArrayBuffer @ main.js:1409
(anonymous) @ main.js:1430
Promise.then (async)
(anonymous) @ main.js:1425
Promise.then (async)
instantiateAsync @ main.js:1423
createWasm @ main.js:1451
(anonymous) @ main.js:29096
main.js:38 Uncaught RuntimeError: null function or function signature mismatch
    at GLES2_CreateRenderer (<anonymous>:wasm-function[1268]:0xbf75b)
    at SDL_CreateRenderer (<anonymous>:wasm-function[1170]:0xb6c41)
    at main (<anonymous>:wasm-function[502]:0x8fbd0)
    at Module._main (main.js:29114)
    at callMain (main.js:71848)
    at doRun (main.js:71921)
    at main.js:71932
```

Tested on 2.0.23 & 2.0.26, Firefox 91 and Chrome 92.

**Comment by kripken** [comment]
The quickest way to investigate this might be to look at the working tests using SDL2 with GLES2 in the test suite, and figure out how this program differs from them. That diff could make it obvious what needs to be fixed.

To find those tests, can grep for for the SDL2 method names under `tests/*`.

**Comment by gorinje** [comment]
Same problem here. Is there a way to disable GLES2 or use another renderer until this problem is solved?

**Comment by chkuendig** [comment]
I quickly checked the  tests and only `tests/sdl2_gl_read.c` is using SDL2 with GLES2 and it isn't calling SDL_CreateRenderer.

**Comment by chkuendig** [comment]
FWIW: This error disappears and the demo runs when 
`
data->glClearColor(1.0f, 1.0f, 1.0f, 1.0f);`

is removed from https://github.com/emscripten-ports/SDL2/blob/f9a06a3ed748033a0497bf266c8033d027553721/src/render/opengles2/SDL_render_gles2.c#L2099
Seems something is wrong with the wrapper/signature of `glClearColor`.

**Comment by chkuendig** [comment]
As luck will have it, it was the signature and #15003 from a few days ago actually fixed this.
