### ISSUE TITLE
Using NODEFS as default file system? 

### ISSUE THREAD

**Issue by alex-coinfund** [emscripten-core/emscripten#14800]
I've been trying to use emscripten-built C++ with node.js. Documentation says that MEMFS is the **default** file system, but I couldn't find any place that describes how to make a different FS be the default. I'd like my emscripten module to load and use NODEFS from the start, mounted at "/". Is that possible? 

Alternatively, I'm happy to force mount NODEFS at module initialization time, but if I do

FS.mount at "/" it gives me an error message that says that the mount point is busy
And if I try to unmount "/" than it gives me a different error at unmount time. 

Would greatly appreciate someone's help.

**Comment by kripken** [comment]
I believe `emcc -s NODERAWFS` is meant for exactly this,

https://github.com/emscripten-core/emscripten/blob/79c8d81a2ec2ed1634ad440c467f7acee13d61a8/src/settings.js#L871-L882

**Comment by alex-coinfund** [comment]
Ah, that's super useful! Thanks
