### ISSUE TITLE
EMSCRIPTEN environment variable is not available

### ISSUE THREAD

**Issue by cool-delete** [emscripten-core/emscripten#14803]
./emcc -v              
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.26 (5af6a110ee58ca4a6885fbcad830c92207fefea2)
clang version 13.0.0 (https://github.com/llvm/llvm-project 31e75512174e1bdaa242ee5c7f30fe56e68c3748)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /code/emsdk/upstream/bin

After using the command `source ./emsdk_env.sh` I still cannot find emcc
must using cd to emcc's path
When I build opencv prompt
`EMSCRIPTEN environment variable is not available. Please properly activate Emscripten SDK and consider using 'emcmake' launcher`

**Comment by sbc100** [comment]
emsdk does not set the `EMSCRIPTEN` environment variable.  It does however set `EMSCRIPTEN_ROOT` and also puts the `emcc` tools in the `PATH`.  

It sounds like the `opencv` code you are using needs to be updated/fixed.  Can you link to the code in question?

**Comment by cool-delete** [comment]
I gave up this method for the time being. I will try again in the next version. Thank you.

**Comment by simonbuehler** [comment]
for the ones stumbling upon this : the fix is in [this issue](https://github.com/opencv/opencv/issues/24572) for recent versions
