### ISSUE TITLE
How do I pass a structure from the C layer to the JS layer？

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14856]
we need to pass structure information (such as width, height, size, etc.) from layer C to layer JS ?  Only use `EMSCRIPTEN_BINDINGS(my_object)` ? but it not fits our needs, because `EMSCRIPTEN_BINDINGS(my_object)`  is global for JS .
Is there any other way to pass information from the C layer to the JS layer ?

**Comment by sbc100** [comment]
All the current methods to passing data between C and JS are documented here: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#

If you don't want stuff in the global JS namespace then I think make `-s MODULARIZE` is the solution.
