### ISSUE TITLE
emscripten_scan_registers infinite loop

### ISSUE THREAD

**Issue by thyrrestrup** [emscripten-core/emscripten#14851]
I've come across a problem with the `emscripten_scan_registers` function where it ends up in an infinite loop causing it to throw a `RangeError: Maximum call stack size exceeded`.

The following code snippet illustrates the problem:.
```c
// main.c
#include <emscripten.h>
#include <stdio.h>

void scan(void* a, void* b) {
    printf("%p %p\r\n", a, b);
}

int main() {

    emscripten_scan_registers(scan);
    
    while (1) {
        emscripten_sleep(100);
    }

    return 0;
}
```
This has been compiled and run with the following commands:
```bash
emcc -O3 main.c -s ASYNCIFY
node a.out.js
```

**Comment by thyrrestrup** [comment]
See #14852 for a proposed fix.

**Comment by dpgeorge** [comment]
Even without the `while (1)`, and with a single `emscripten_sleep(0)`, it crashes with `RuntimeError: memory access out of bounds`.

Using version `emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.26 (5af6a110ee58ca4a6885fbcad830c92207fefea2)`.
