### ISSUE TITLE
`emscripten_force_exit` changing ASYNCIFY state?

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#14902]
I noticed this when modifying `tests/browser/async_mainloop.cpp`

If I add a call to `emscripten_force_exit` to the top of the `iter` function I see the following exception when running `./tests/runner browser.test_async_mainloop`:

```
[client logging: /?exception=Uncaught Error: import emscripten_force_exit was not in ASYNCIFY_IMPORTS, but changed the state / undefined ]
FAIL
```

**Comment by ClintKilmer** [comment]
I saw this error message while porting a project with -s ASYNCIFY -s EXIT_RUNTIME=1 after a call to emscripten_force_exit(0).

**Comment by sbc100** [comment]
@kripken you said you might be interested in this?

**Comment by kripken** [comment]
Yes, I'll try to get to it soon, been busy with other urgent things, sorry.

**Comment by ClintKilmer** [comment]
I still see the same error message above, after updating with "emsdk install tot" and "emsdk activate tot".

**Comment by kripken** [comment]
It can take a little time for builds to reach `tot` - looks like that has not rolled through yet. Atm the last build was unlucky and hit a flakey error, https://ci.chromium.org/ui/p/emscripten-releases/builders/try/mac/b8837093706755386113/overview

**Comment by kripken** [comment]
Looks like it reached `tot`.
