### ISSUE TITLE
Annotating functions to be exported in the C/C++ source

### ISSUE THREAD

**Issue by codemonkey-uk** [emscripten-core/emscripten#1491]
Currently functions to be exposed to JavaScript must be listed in the EXPORTED_FUNCTIONS argument.

Would it be desirable for this to be automated in the function deceleration, as is done for dynamic library interfaces with "dllexport"? This is the approach used for dynamic library interfaces in other popular compilers:
- MSVC: http://msdn.microsoft.com/en-us/library/dabb5z75.aspx
- GCC: http://gcc.gnu.org/wiki/Visibility
- LLVM: http://llvm.org/docs/LangRef.html

Thanks

**Comment by peter-b** [comment]
Hi @ngld & @kripken, what needs to be done to implement & merge this?  I'm currently writing some code where I really need to be able to annotate which functions should be exported at C++-level!  I'm happy to have a play around myself if someone can give me some appropriate pointers to get started.

**Comment by ngld** [comment]
This has already been implemented using [EMSCRIPTEN_KEEPALIVE](https://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html#c.EMSCRIPTEN_KEEPALIVE).
If you're using it at the C++-level, you will have to deal with name mangling. It might be easier to write wrappers which you mark with ```extern "C"``` and export those.

**Comment by peter-b** [comment]
Perfect. So if I have

    #define MC_DLLEXPORT __attribute__((__visibility__("default")))

for normal Linux builds, and I change it to

    #define MC_DLLEXPORT EMSCRIPTEN_KEEPALIVE

for Emscripten builds, will that do what I think it will (i.e. make sure that functions marked with `MC_DLLEXPORT` remain callable by name even in optimised builds)?

/cc @livecodefraser

**Comment by peter-b** [comment]
@ngld Interestingly, when I compile with `EMSCRIPTEN_KEEPALIVE` — a.k.a. `__attribute__((used))` — I get **-Wignored-attributes** warnings from em++. Is that a bug in em++?

**Comment by ngld** [comment]
That shouldn't happen... [This example](https://github.com/kripken/emscripten/blob/master/tests/core/test_llvm_used.in) doesn't throw any warnings.
Can you post the full warning?

**Comment by peter-b** [comment]
I'm guessing that the problem is that I'm attaching  the attribute to the declaration, rather than the definition?

**Comment by CMCDragonkai** [comment]
If I wanted to emscripten up a library say libgit2, I would have to either create a C wrapper that annotates every function with `EMSCRIPTEN_KEEPALIVE`, or I would have to maintain a list of all the functions in `EXPORTED_FUNCTIONS`, is there anyway to make emscripten just export everything that is defined in the header: https://github.com/libgit2/libgit2/blob/master/include/git2.h

**Comment by d3x0r** [comment]
EMSCRIPTEN_KEEPALIVE Works...

You do have to apply the attributes to the declaration not the definition.

```
int jsox_parse( char * string, size_t stringLen, int reviver ) EMSCRIPTEN_KEEPALIVE;  // __attribute__((used))
int jsox_parse( char * string, size_t stringLen, int reviver )
{
}
```
