### ISSUE TITLE
Sleep without blocking Event Loop

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#14918]
Is there any way to sleep in C code without blocking Event loop? I use sleep function in C code in web worker and such operation block event loop.

**Comment by sbc100** [comment]
These is no way to run the event loop without returning back to it (i.e. unwinding the stack all the way out). 

If you would rather not restructure your program and really need the blocking behaviour of things like sleep then the only solution we have to today is ASYNCIFY: https://emscripten.org/docs/porting/asyncify.html.  Using ASYNCIFY effectively suspends your current stack and then resumes it a later day.    It does come at a fairly significant runtime code though, depending how it isued.
