### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined 

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14919]
When migrating the C project from Emscripten V1.37 to EmscriptenV2.0, a library loading `importScripts('Decoder.js'); Module.postRun.push(function(){......})` error was reported `Uncaught TypeError: Cannot read property 'push' of undefined `

**Comment by sbc100** [comment]
It looks like the `Module.postRun` object was removed back in #9072.

I think you can use `Module.addOnPostRun(function()..`..  and I think you will also need to do `-sEXPORTED_RUNTIME_METHODS=addOnPostRun`.

**Comment by sbc100** [comment]
Actually you can also just do `Module.postRun = [function ...]`.
