### ISSUE TITLE
logger.debug(f'(not saving intermediate {name} because not generating JS)')

### ISSUE THREAD

**Issue by MirrorYuChen** [emscripten-core/emscripten#14927]

**Comment by MirrorYuChen** [comment]
https://github.com/emscripten-core/emscripten/issues/14781

**Comment by MirrorYuChen** [comment]
My system is Ubuntu 16.04. I have set python to python3, but the error also exists.

![image](https://user-images.githubusercontent.com/49817428/130384312-609da28c-2604-495d-b640-401050082f59.png)

**Comment by MirrorYuChen** [comment]
How can I resolve this problem, can anyone give me some advice, THX a lot!

**Comment by SomeDevHere** [comment]
Python 3.6 or greater is required by Emscripten. You may need to update your python.

**Comment by MirrorYuChen** [comment]
OK，3Q~

**Comment by MirrorYuChen** [comment]
Solved! Thank U!
