### ISSUE TITLE
Why do I need to enable web services to use WASM

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14928]
when use .wasm library , i need to start a Web service in the current directory.

the normal .js libraries can be loaded locally and why can't .wasm be loaded ？

**Comment by juj** [comment]
I think you are hitting the issue that loading web pages via `file://` URL in web browsers will not allow accessing other files on the local hard drive. This security is implemented via CORS rules.

You can use the `-s SINGLE_FILE=1` Emscripten linker flag to bundle all the .html + .js and .wasm to a single file, that will prevent the network request.
