### ISSUE TITLE
[QUESTION] What is the behaviour when a main module is asked to link w/ a side module that includes a library that the system doesn't have?

### ISSUE THREAD

**Issue by danbugs** [emscripten-core/emscripten#14931]
I'm hoping to distribute a side module that includes `regex.h` that is to be linked to another user's main module. Considering linking w/ system libraries only happens at main modules, what is the behavior if the user's machine doesn't have `regex.h`? That is, I'm not sure if `regex.h` is standard but, still, how can I ensure that users have my required system librarires? Would I have to use `emconfigure`? I was hoping to just distribute the `.wasm` and `.js` library files 🤔

**Comment by sbc100** [comment]
`regex.h` is part of emscripten core C library (musl).   The functions declared in that header (just like all C library functions) will be linked in as needed when `MAIN_MODULE=1` used, or when `MAIN_MODULE=2` is used and the side module is listed on the link line.

**Comment by danbugs** [comment]
SOOO... If `regex.h` wasn't a part of musl, I wouldn't have been able to compile the side module in the first place — is that right? Thanks for the help, @sbc100 !

**Comment by sbc100** [comment]
Yes that is correct.

**Comment by danbugs** [comment]
Alright — Thanks! I'm closing the issue now ;D
