### ISSUE TITLE
Embedding files is much less efficient than preloading?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#14942]
Embedding files is much less efficient than preloading and should only be used when packaging small numbers of small files. Preloading also enables the option to separately host the data.

Does inefficient mean slow running or slow compiling?What is inefficient ?

**Comment by kripken** [comment]
It is both larger to download, and slower to start up, when using embedding. Embedding adds code in JS that needs to be parsed into the binary data. Preloading, instead, will load a binary file with the contents directly.
