### ISSUE TITLE
 RuntimeError: abort(Assertion failed: Missing signature argument to addFunction: ...) when building with -g

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#14959]
I am trying to enable debugging for wasm in chrome. So, I compiled and linked my code with `-g` instead of `-O3` which I was doing earlier. But I am facing this strange error below at runtime.
<img width="1456" alt="Screenshot 2021-08-27 at 6 37 54 PM" src="https://user-images.githubusercontent.com/19284116/131132350-8831dc01-654f-4ab8-aaac-44731dfbf3f0.png">

I also tried adding `gettimeofday` inside `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` and `_gettimeofday` in `EXPORTED_FUNCTIONS` but the issue still persists. It seems that this function is there in the generated js but its signature (`sig`) isn't.

**Comment by ravisumit33** [comment]
@kripken @sbc100 This seems to be only blocker in enabling debugging support in my build. If I manually add `gettimeofday.sig = ii` in the generated js everything works fine. Any idea why signature is not getting included automatically by emscripten ?

**Comment by sbc100** [comment]
We would need to add explicit signature to `src/library.js`.   Something like `gettimeofday__sig: 'ii',` around like 1456.

These explicit signatures should only be needed in certain cases, and only IIRC when using dynamic linking.    Can you confirm using are using dynamic linking (building with MAIN_MODULE)?

**Comment by ravisumit33** [comment]
@sbc100 Yes, we are using dynamic linking (building with MAIN_MODULE=2).

**Comment by sbc100** [comment]
Would you mind sending a PR to add `__sig` to `gettimeofday`?

**Comment by ravisumit33** [comment]
Sure, will send a PR adding line `gettimeofday__sig: 'ii'` to `src/library.js`.
