### ISSUE TITLE
rror: tool or SDK not found: 'sdk-incoming-64bit'

### ISSUE THREAD

**Issue by EysaDun** [emscripten-core/emscripten#14967]
`eysir@eysir-ubu:~/workspace/python/emsdk$ ./emsdk install sdk-upstream-incoming-64bit
Installing SDK 'sdk-upstream-incoming-64bit'..
error: manifest error: No tool by name 'llvm-git-master-64bit' found! This may indicate an internal SDK error!

eysir@eysir-ubu:~/workspace/python/emsdk$ ./emsdk install sdk-incoming-64bit binaryen-master-64bit
error: tool or SDK not found: 'sdk-incoming-64bit'

eysir@eysir-ubu:~/workspace/python/emsdk$ 
`

Im try add SDK targets like this:
`https://github.com/emscripten-core/emsdk/pull/413/commits/e910502f159818331b1f96ac2aedfa759d0b8326`

But also has issue here.
ubuntu20.04

**Comment by kripken** [comment]
Is that on the latest emsdk? The commands look a little outdated, perhaps based on docs we need to fix - where did you see them?

Replacing `incoming` etc. with `main` should work. Also it is even simpler to get `latest` like this:

```
./emsdk install latest
```

**Comment by EysaDun** [comment]
> Is that on the latest emsdk? The commands look a little outdated, perhaps based on docs we need to fix - where did you see them?
> 
> Replacing `incoming` or `master` with `main` should work. Also it is even simpler to get `latest` like this:
> 
> ```
> ./emsdk install latest
> ```

Thx, it works OK.
