### ISSUE TITLE
`malloc was not included` error when using GLFW and ImGui

### ISSUE THREAD

**Issue by janekb04** [emscripten-core/emscripten#14965]
I recieved the following message when trying to compile a simple Imgui project using Emscripten:
```
(index):766 malloc was not included, but is needed in glfwGetMonitors. Adding "_malloc" to EXPORTED_FUNCTIONS should fix that. This may be a bug in the compiler, please file an issue.
```
As such, I am filing this issue.

The project in question is [`janekb04/emscripten-test`](https://github.com/janekb04/emscripten-test). I will provide additional information if necessary.

**Comment by kripken** [comment]
Thanks @janekb04 , that does indeed look like a missing dependency. Fix in https://github.com/emscripten-core/emscripten/pull/14972

**Comment by janekb04** [comment]
@kripken Thanks for fixing it so quickly.
