### ISSUE TITLE
CLOSURE_COMPILER setting no longer works

### ISSUE THREAD

**Issue by leo60228** [emscripten-core/emscripten#14995]
```
AttributeError: module 'tools.shared' has no attribute 'CLOSURE_COMPILER'
```
I believe https://github.com/emscripten-core/emscripten/commit/13535ca57a071ccfa9ae1570677115f7e140c57b was responsible for this.

**Comment by kripken** [comment]
@leo60228 A full stack trace could help here. Also, which precise version are you on?

Skimming a grep of the relevant code locations, I can't see how this could crash on current main, but I may easily be missing something.

**Comment by leo60228** [comment]
I'm on 2.0.27 (from Nixpkgs). I can't easily get a stack trace at the moment, but I'm pretty sure this section of this diff is the cause:
```diff
 def get_closure_compiler():
   # First check if the user configured a specific CLOSURE_COMPILER in thier settings
-  if shared.CLOSURE_COMPILER:
+  if config.CLOSURE_COMPILER:
     return shared.CLOSURE_COMPILER
```

I think this should be:
```diff
 def get_closure_compiler():
   # First check if the user configured a specific CLOSURE_COMPILER in thier settings
-  if shared.CLOSURE_COMPILER:
-    return shared.CLOSURE_COMPILER
+  if config.CLOSURE_COMPILER:
+    return config.CLOSURE_COMPILER
```
