### ISSUE TITLE
`test_pthread_exit_process` suspicious log message on Node

### ISSUE THREAD

**Issue by kleisauke** [emscripten-core/emscripten#14993]
It prints this message:
https://github.com/emscripten-core/emscripten/blob/ad6e356df588646eb2569c8e9100b8991db799e8/tests/core/pthread/test_pthread_exit_runtime.c#L21

Which probably shouldn't happen, since the `exit(42);` call in the thread is expected to bring down the whole process.
https://github.com/emscripten-core/emscripten/blob/ad6e356df588646eb2569c8e9100b8991db799e8/tests/core/pthread/test_pthread_exit_runtime.c#L10

Reproducer:
```bash
$ ./tests/runner wasm2.test_pthread_exit_process -v 2>&1 | grep -B3 -A2 "should never get here"
-- begin program output --
main
calling exit
done join -- should never get here
onExit status: 42
-- end program output --
```

Although, on the browser it seems to work fine. Tested with:
```bash
$ ./tests/runner browser.test_pthread_exit_process --browser="/usr/bin/google-chrome --enable-logging=stderr --v=1" 2>&1 | grep -B3 -A2 "should never get here"
```

**Comment by kleisauke** [comment]
After further testing, it looks like PR #14481 will resolve this.

**Comment by sbc100** [comment]
This does indeed look wrong.  I think its because we send the `exitProcess` message back to the main thread but we then go ahead and exit the calling thread using `throw new ExitStatus(status);` which ends up marking the current thread as join-able, which we probably should not do.

**Comment by sbc100** [comment]
I'm not sure how #14481 will help because it doesn't (or I don't see how it will) stop the calling thread from marking itself as join-able in `_emscripten_thread_exit`.

**Comment by kleisauke** [comment]
It looks like some kind of race, from what I've seen. It can be fixed (or circumvented?) with moving this `PThread.terminateAllThreads()` call:
https://github.com/emscripten-core/emscripten/blob/0321203d3614a97e4042ffa0c19ab770b1f5aa6c/src/postamble.js#L444

after the `exitRuntime` function, for example:
```diff
diff --git a/src/postamble.js b/src/postamble.js
index 1111111..2222222 100644
--- a/src/postamble.js
+++ b/src/postamble.js
@@ -440,10 +440,10 @@ function exit(status, implicit) {
     }
 #endif // ASSERTIONS
   } else {
+    exitRuntime();
 #if USE_PTHREADS
     PThread.terminateAllThreads();
 #endif
-    exitRuntime();
   }
 
   procExit(status);
```
(a similar thing is done within PR #14481)

I haven't debugged it further yet, but it looks like the `PThread.terminateAllThreads()` call somehow causes the thread to mark itself as joinable/exited, and therefore causes this block to be executed:
https://github.com/emscripten-core/emscripten/blob/0321203d3614a97e4042ffa0c19ab770b1f5aa6c/src/library_pthread.js#L828-L838

Note that the musl upgrade might also fix this, as I didn't observe this behavior when I reverted commit https://github.com/emscripten-core/emscripten/pull/13007/commits/d3142ae494c19c5e6c9bf93f9802079b2e37c9af  in PR #13007 (perhaps moving `pthread_join` to native code is the proper way to resolve this).
