### ISSUE TITLE
Unable to link to combined archive(static library) using emar

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#15026]
I have many pre-built static libraries which i merged into single archive using following command:
`emar rcs libboost.a *.a`

When, I tried to link libboost.a to my executable wasm, I got following warnings & error:

```
em++: warning: libs/boost/libboost.a: archive is missing an index; Use emar when creating libraries to ensure an index is created [-Wemcc]
em++: warning: libs/boost/libboost.a: adding index [-Wemcc]
wasm-ld: error: libs/boost/libboost_lite.a: archive has no index; run ranlib to add one
```
I even tried running `emranlib` using below command with no luck:
`emranlib -D libboost.a`

However, if I link archives separately it works pretty well. Is this something not supported in emscripten ?

NOTE:- I built all separate archives using emscripten toolchain itself.

**Comment by sbc100** [comment]
I don't think nested `ar` archives are a thing.  You can't do that with the GNU toolchain or the llvm toolchain either.

If you want to combine archives I think the way to do it would be extract all object in each archive using `emar x ...` and then create  a new archive from all the resulting files.

**Comment by ravisumit33** [comment]
@sbc100 Thanks got it.
