### ISSUE TITLE
RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #7019:"cvRodrigues2" failed: Invalid opcode 0xfe (enable with --experimental-wasm-threads) @+1580665) at Error

### ISSUE THREAD

**Issue by luopengting** [emscripten-core/emscripten#15030]
I want to build WebAssembly and my program has imported opencv.

1. Build opencv.js and with `-s USE_PTHREADS=0`, and some `.a` are generated.
2. Build my program targeting those static library by step 1. Such as libopencv_calib3d.a
3. Open the web page and import the wasm.

If a browser without SharedArrayBuffer is used, the following error message is displayed:
```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #7019:"cvRodrigues2" failed: Invalid opcode 0xfe (enable with --experimental-wasm-threads) @+1580665) at Error
    at jsStackTrace (http://127.0.0.1:8081/slam/main.js:1729:19)
    at stackTrace (http://127.0.0.1:8081/slam/main.js:1746:16)
    at abort (http://127.0.0.1:8081/slam/main.js:1465:44)
    at http://127.0.0.1:8081/slam/main.js:1635:7
    at abort (http://127.0.0.1:8081/slam/main.js:1471:11)
    at http://127.0.0.1:8081/slam/main.js:1635:7
```

![image](https://user-images.githubusercontent.com/22173722/133086244-2e41ffb9-5433-4527-8a2d-e046eb749c89.png)

Does this function use multithreading? But I've turned off the multithreading switch in all compilation processes.
This problem may occur in some functions. How can I solve this problem? And my browser does not support `Threads and atomics`.

**Comment by kripken** [comment]
Yes, that error indicates that something in the program uses multithreading. You can disassemble the wasm to confirm that (but I think it's safe to say the browser is not wrong here). So something in the build is still using atomics.

**Comment by luopengting** [comment]
I use opencv 4.5.3 and it works! Thx a lot! @kripken
