### ISSUE TITLE
Outdated WEBGPU API

### ISSUE THREAD

**Issue by briangavin** [emscripten-core/emscripten#15031]
Now that Google Chrome has announced support for WEBGPU.   
https://blog.chromium.org/2021/08/chrome-94-beta-webcodecs-webgpu.html

Is there a plan to update the APIs for WEBGPU?   They appear to be outdated.

**Comment by kripken** [comment]
@kainino0x 's https://github.com/emscripten-core/emscripten/pull/14951 may be relevant.

**Comment by briangavin** [comment]
The problems I am seeing related to using a SwapChain.   It appears the WEBGPU now uses the canvas object instead.    

For example this is an error.  wgpuDeviceCreateSwapChain()

**Comment by kainino0x** [comment]
Yup I'm in the middle of an update. I was almost done when I got pulled away for the last 2 weeks. Sorry about that! It's my top priority this week.
