### ISSUE TITLE
Bug in page:Download and install 

### ISSUE THREAD

**Issue by RequireSun** [emscripten-core/emscripten#15047]
In this page, the document says:

```
On Windows, run emsdk instead of ./emsdk, and emsdk_env.bat instead of source ./emsdk_env.sh.
```

But in `docs/tools_reference/emsdk`, the document says:

```
On Windows, calling activate automatically sets up the required paths and environment variables.
```

So is it necessary to execute `emsdk_env.bat` on windows?

If it's nonessential, could to add some additional notes in `getting_started/downloads` ?

URL: ../../docs/getting_started/downloads

**Comment by sbc100** [comment]
Its its essential to setup the required paths and environment variables in each shell.

On windows `emsdk activate` is able also run `emsdk_env.bat` ... so `emsdk_env.bat` is not needed if `emsdk activate` has already been run.     So it is necessary, but in some cases its automatically performed for you. 

`emsdk_env.bat` is still useful as something you might run at startup, or in a shell that you want to use emsdk within.

**Comment by RequireSun** [comment]
Thanks a lot, I'd like to add some additional instructions to the getting_started section so that will make new hands more clear about it usage.

**Comment by RequireSun** [comment]
#15051
