### ISSUE TITLE
how to convert std::string to js Uint8Array other than default js string when using embind

### ISSUE THREAD

**Issue by hardfist** [emscripten-core/emscripten#15067]
![image](https://user-images.githubusercontent.com/8898718/133886889-3a54913f-ba03-457e-a83c-459283e6e341.png)

according to the embind doc,std::string corresponds to many js data type
```c++
std::string encode(){
  vector<uint8_t> vec(...);
  std::string res(vec.begin(),vec.end());
  return res;
}
function("encode",&encode);

```
when I call encode, I get js string type
```typescript
const loadModule = require('./lib');
const m = loadModule();
const result = m.encode(); // I get string other uint8Array or arrayBuffer
```
But since c++ std::string may contains invalid utf8 code, I want to get uint8Array instead of js string
![image](https://user-images.githubusercontent.com/8898718/133887152-b04469d9-a035-46f2-bcc2-54ed910027d0.png)

**Comment by sbc100** [comment]
@RReverser maybe you have a suggestion?

**Comment by brendandahl** [comment]
I think the table is a bit misleading. It goes the other way, from JS you can pass a UInt8Array to create std::string in C++. See [this test](https://github.com/emscripten-core/emscripten/blob/43d1f80f5dedff5ed391b168f9765200bfb22578/tests/embind/embind_test.cpp#L199-L201) for an example.

If you want the the raw data you could use c_str in c++ and then use a [memory view](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-views).

**Comment by AdelKS** [comment]
Please add to the documentation that `std::basic_string<unsigned char>` is mapped to an `Uint8Array`
