### ISSUE TITLE
Use musl implementation of pthread API where possible 

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#15061]
Historically a lot of the pthread implementation in emscripten was custom JS code.

We have been slowly moving towards using the musl C code where possible and there is
still some work to do here.  Doing this has several advantages:

- More portable / self-contained wasm modules (fewer JS imports)
- Better internal compatibility with the rest of musl 
- Fewer emscripten-specific bugs
- Less code to maintain

Even when we can't use the musl code directly, moving the code to C is from JS
has its advantages too.

Some of the work already done: #12861 #14858 #14853 #14775 #14707 #14484 #12839 #12615

**Comment by kleisauke** [comment]
PR https://github.com/emscripten-core/emscripten/pull/15603 and https://github.com/emscripten-core/emscripten/pull/15604 are also relevant here. After that, most pthread APIs have been moved to musl (I think).

Another advantage of doing this is that simplifying `library_pthread.js` becomes easier (see e.g. work-in-progress commit https://github.com/emscripten-core/emscripten/pull/13007/commits/bf592e83fdfa2c2bb95ae849bcce5d7c2bf13308).

**Comment by sbc100** [comment]
I think this is largely done now!
