### ISSUE TITLE
Module['_pthread_self']()

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#15073]
I'm trying to use method '_pthread_self' in web worker and it one time return id and other return 0. 
1. Is it defined behaviour?
2. Explain, please, mechanism of mentioned method.
3. Analogue of method '_pthread_self' for web worker ?

**Comment by sbc100** [comment]
_pthread_self will return zero when a thread exits and the worker is no longer hosting a pthread.

This happens during pthread_exit here:

https://github.com/emscripten-core/emscripten/blob/288955586095a45456d71a1d811d964894f71773/system/lib/pthread/pthread_create.c#L115

**Comment by DiachenkoIgor** [comment]
Thank you.
