### ISSUE TITLE
Custom JS library function proxying to main thread

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#15079]
Hi, I have created custom library and it is created and configured for every worker (pthread) separately. I use 'async' flag for not proxying calls to main thread, however it doesn't work.
1. Library code example:
```
 example__proxy: 'async',
     example__sig: 'iiii',
     example: function(domain, type, protocol) {
           return Asyncify.handleAsync(() => {
               return self.test(); // for every thread this function creates in ...worker.js. If this call is proxied, main thread doesn't 
                                             contains this function.
           });
       },
```
2. Function code after compilation
```
function _example(domain, type, protocol) {
    if (ENVIRONMENT_IS_PTHREAD)
      return _emscripten_proxy_to_main_thread_js(6, 0, domain, type, protocol);
    
      return Asyncify.handleAsync(() => {
        return  self.test(domain, type, protocol);
      });
  }
```
Maybe proxying is caused because of Asyncify?

**Comment by sbc100** [comment]
You say "I use 'async' flag for not proxying calls to main thread".. but `async` does enable proxying.  If you don't want to proxy at all then you would just not specify `example__proxy` at all, then the code would run in the worker.

**Comment by DiachenkoIgor** [comment]
@sbc100 , Thank you.
