### ISSUE TITLE
 undefined symbol: sched_getaffinity

### ISSUE THREAD

**Issue by everywill** [emscripten-core/emscripten#15088]
I am trying compiling a demo using x264.
I run emmake to genarate a libx264.a using 'host=x86-none-linux' and '--extra-cflags=pthread'. But when linking emcc emitted 'error: undefined symbol: sched_getaffinity (referenced by top-level compiled C/C++ code)'.

In x264(common/cpu.c), when 'host_os' is linux, sched_getaffinity is invoked. Also I find that emscripten’ libc there is a sched_getaffinity implementation(libc/musl/src/sched/affinity.c). I wonder how to link to emscripten's sched_getaffinity.

**Comment by sbc100** [comment]
Emscripten doesn't support the syscall that is needed to implement `sched_getaffinity` and AFAIK there is no way to map that feature to something available in web platform APIs

We could provide a dummy/placeholder in JS, but ideally you would find a way to configure the code not to call the function.   If its portable code it most likely has some way to opt out of that feature.   Failing that, you can always add your own stub version either in native code or in JS library code.
