### ISSUE TITLE
How to handle deadlocks when calling functions other than main directly from javascript ?

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#15102]
I have a codebase that is similar to below sample program:

```
#include <cstdio>
#include <iostream>
#include <future>
#include <sstream>
#include <utility>
#include <vector>
#include <boost/asio/post.hpp>
#include <boost/asio/thread_pool.hpp>
#include <boost/asio/use_future.hpp>
#include "emscripten.h"

int task_num = 1;


extern "C" {
int EMSCRIPTEN_KEEPALIVE replica()
{
    std::printf("Inside replica\n");
    boost::asio::thread_pool tp(5);
    auto task = [](){
        std::stringstream msg;
        msg << "Task " << task_num++ << std::endl;
        std::cout << msg.str(); 
    };
    std::vector<std::future<void>> vec;
    for (int i=0; i < 5; ++i) {
        vec.push_back(boost::asio::post(tp, boost::asio::use_future(task)));
    }
    for(auto& fut: vec){
        fut.wait();
    }
    std::cout << "Completed" << std::endl;
    return 0;
}

}
int main() {
    std::printf("Inside main\n");
    return 0;
}
```

I have to keep calling functions other than main (like in this case `replica`) directly from javascript. These functions can internally create threads and can wait upon them. Here, even if we use `PROXY_TO_PTHREAD`, function call to `replica` will still be on the main thread and will cause deadlock.

What is the ideal way to handle such scenarios ?

**Comment by kripken** [comment]
Can the functions called on the main thread just signal to a pthread to do the actual work? (So that no actual blocking happens on the main thread.)

**Comment by ravisumit33** [comment]
@kripken I was also thinking the same that a pthread will continuously poll for incoming tasks from the main thread and perform the required operation. But I was not liking this continuous polling approach and was thinking about if something general ( like `PROXY_TO_PTHREAD`) way emscripten provides.

**Comment by ravisumit33** [comment]
https://emscripten.org/docs/api_reference/proxying.h.html is the solution
