### ISSUE TITLE
`emsdk install` spawns 1000s of python processes

### ISSUE THREAD

**Issue by chippydip** [emscripten-core/emscripten#15113]
Trying to get setup on Windows following the getting started guide. Fresh install of Python (3.9.7), cloned the repo, and ran `emsdk install 2.0.13` from cmd.exe. The command didn't seem to do anything and after a while I tried to check task manager an saw thousands of python processes all with the same command line: `C:\WINDOWS\python.exe "C:\Projects\emsdk\\emsdk.py" install 2.0.13`.

I was eventually able to kill the parent process. Tried again with `emsdk install latest` with the same result. Also tried from a Git Bash command prompt and PowerShell, same deal.

**Comment by sbc100** [comment]
Do you know what phase the `emsdk install latest` command gets to when it spawns all these processes?

What do you see on the output when you run this command?  Can you also try running with `EMSDK_VERBOSE=1` in the environment?  

What version of emsdk are you using (i.e are you on the tot main branch?)

**Comment by chippydip** [comment]
Got it working! Adding the verbose flag still didn't print any output (nor did adding additional print statements to the script). This got me thinking maybe there was something wrong with Python itself...

The Python installer doesn't add `python.exe` to the PATH anymore and instead just adds the `py.exe` launcher to the WINDOWS folder. The `emsdk` script didn't pick this up since it's only looking for `python` in the path so I just copied and renamed `py.exe` to `python.exe` in that same folder. It worked fine for starting the interpreter and `python --version` worked as expected, but it seems like this setup ended up launching itself in a loop when trying to run a script.

I removed the `python.exe` copy and updated `emsdk.bat` to use `py` instead of  `python` and everything seems to be working now.

It would be nice if the script checked for the `py` command in the path before falling back to `python` since that seems to be the suggested/default setup for Python now, but it looks like the fork bomb behavior was unrelated the emscripten so I'll go ahead and close this ticket.

**Comment by sbc100** [comment]
Really?  Windows python no longer puts `python.exe` in the PATH?   That seems like a strange choice.. but if true when yes we should update the .bat file.

**Comment by sbc100** [comment]
It looks like its up to you if you add `python` to you `PATH` during installation: https://docs.python.org/3/using/windows.html#launcher

`py` is a kind of launcher that can launcher different versions of python.

**Comment by chippydip** [comment]
Looks like you can have the installer add it to the PATH, but it's not the default option anymore:
> Per-user installations of Python do not add the launcher to PATH unless the option was selected on installation.
Sounds like this is intentional to encourage people to use `py` instead which can use a better version selection algorithm is more than one version is installed on the system: 
> Unlike the PATH variable, the launcher will correctly select the most appropriate version of Python. It will prefer per-user installations over system-wide ones, and orders by language version rather than using the most recently installed version.
