### ISSUE TITLE
using embind in a complrex cmake project

### ISSUE THREAD

**Issue by olehnikolaiev** [emscripten-core/emscripten#15120]
Hello, I am trying to build my cmake based project using emscripten. the structure of project is following: I have a few third-party libraries compiled with emconfigure, emmake, emcmake (but with no bindings as far as they are third-party libraries and big enough), lets call them `libraries.a`. also, I have a planty of source files which I combined into my own library - `my_library.a`(also added there bindings I need). when I try to run `emcc --bind -o my_library.js -Wl,--whole-archive my_library.a -Wl,--no-whole-archive` (as from documentation) I got this error `wasm-ld: error: my_libte.a(my_library.cpp.o): undefined symbol: libraries::some_static_member`. does this mean that I HAVE TO write bindings for all the third-parties as well? if no, please correct which steps I should to do right to get bindings for `my_library.a`. Thanks in advance!

**Comment by sbc100** [comment]
I think you need to include the third party library on your link command line.  You can do this either by specifying `libraries.a` directly if by adding `-lfoo` (assuming you library is called `libfoo.a`).

**Comment by olehnikolaiev** [comment]
I link all the third party libraries to my library in `CMakeLists.txt` file while building `my_library.a` via `target_link_libraries`. Should I also specify them in `emcc --bind` command? it seems not working for me in any case

**Comment by sbc100** [comment]
The `--bind` command is not separate to your link command.. instead you should just add `--bind` to the link flag for your target.    `--bind` basically just tells the linker to include the embind library.

**Comment by sbc100** [comment]
Sorry.. didn't mean to close.

**Comment by olehnikolaiev** [comment]
add `--bind` to the executable file works, thanks! closing the issue.
