### ISSUE TITLE
addOnPostRun cant used in ios ,there is a error 'unhandled Promise Rejection'

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#15136]
there is a error when use addOnPostRun in ios chrome/safari . but it is ok in windows chrome 、android chrome etc.
`Unhandled Promise Rejection :RuntimeError :abort(CompileError:WebAssembly.Module doesn't parse at byte 1979:references are not enabled),build with -s ASSERTIONS=1 for more info.(evaluating 'new WebAssembly.RuntimeError(what)')`.

i can use `addOnPostRun` in windows/android chrome , but in ios/mac safari/chrome there is a error .

**Comment by sbc100** [comment]
I seems very unlikely that your `addOnPostRun` handler could cause this.    This seems like an issue with the wasm module itself using some feature that safari does not yet support. Are you sure it works on Safari with your `addOnPostRun` handler?

If you disassembly the binary what do you see at byte 1979?   If you can attach the wasm file that might be helpfull.

**Comment by sbc100** [comment]
BWT `addOnPostRun` does not effect the generated wasm file which is why it seems unlikely to be related.

**Comment by yangfangfang1204** [comment]
i try again , and find in the chrome of mac, it is ok ,but in the safari of mac , it is a error . and the same C code , i compile it in Emscripten V1.37 ，the .wasm is ok in the safari of mac . but compile it in Emscripten V2.0.30 is a error.

i agree with you, may be not the `addOnPostRun` caused the error , but i dont know what the problem is .

**Comment by yangfangfang1204** [comment]
In EmscriptenV1.37 , the compile script:
`#!/usr/bin/python
import os, sys, re, json, shutil
from subprocess import Popen, PIPE, STDOUT
exec(open(os.path.expanduser('~/.emscripten'), 'r').read())
sys.path.append(EMSCRIPTEN_ROOT)
import tools.shared as emscripten
emcc_args = [
  '-O3',
  '--memory-init-file', '0',
  '--llvm-opts', '3',
  '--llvm-lto', '3',
  '-s', 'NO_EXIT_RUNTIME=1',
  '-s', 'NO_FILESYSTEM=1',
  '-s', 'TOTAL_MEMORY=' + str(128*1024*1024),
  '-s', 'ALLOW_MEMORY_GROWTH=0',
  '-s', 'INVOKE_RUN=0',
  '-s', 'DOUBLE_MODE=0',
  '-s', 'PRECISE_I64_MATH=0',
  '-s', 'AGGRESSIVE_VARIABLE_ELIMINATION=1',
  '-s', 'ALIASING_FUNCTION_POINTERS=1',
  '-s', 'DISABLE_EXCEPTION_CATCHING=1',
  '--js-library', 'library.js'
]
OBJ_DIR = "obj"
if not os.path.exists(OBJ_DIR):
  os.makedirs(OBJ_DIR)
print 'build'
source_files = [
  'Memory.cpp',
   ...
 ]
object_files = [
  'obj/Memory.o',
  ...
 ]
for file in source_files:
  target = file.replace('.cpp', '.o')
  arrs = target.split("/")
  print 'emcc %s -> %s' % (file, arrs[-1])
  emscripten.Building.emcc(file, emcc_args + ['-Iplayctrl'], os.path.join('obj', arrs[-1]))
#object_files = [os.path.join('obj', x.replace('.cpp', '.o')) for x in source_files];
print 'link -> %s' % 'STDecode.bc'
emscripten.Building.link(object_files, 'STDecode.bc')
`

And in EmscriptenV2.0.30 , the compile script :
`CC = emcc
AR = emar
IFLAG = -I../../Decoder\
CFLAGS 	= $(IFLAG) -Wall
LDFLAGS = -s "EXPORTED_RUNTIME_METHODS=['ccall', 'getValue','writeArrayToMemory','print','UTF8ToString','cwrap','malloc','addOnPostRun','setValue']" -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=0 -s ENVIRONMENT=web,worker
SRCS += ../../Decoder/Decoder.cpp
LIBS = $(wildcard ./lib/web/*.a)
OBJS = $(patsubst %.cpp,%.o,$(SRCS))
TARGET = Player.js
OBJ_TARGET = Decoder.a
all: $(OBJS) $(OBJ_TARGET) $(TARGET)
$(OBJ_TARGET): $(OBJS)
	$(AR) rcs $(OBJ_TARGET) $(notdir $(OBJS))
$(TARGET):$(OBJ_TARGET)
	$(CC) -O3 --bind $(OBJ_TARGET) $(LIBS) -o $(TARGET) $(LDFLAGS)	
.cpp.o:
	$(CC) $(CFLAGS) -c $<
clean:
	rm -f *.o *.a $(OBJS) $(OBJ_TARGET) $(TARGET)
	rm -rf $(DIR)
`
may be the compile script exit some error ?

**Comment by yangfangfang1204** [comment]
how to disassembly the binary ?

**Comment by yangfangfang1204** [comment]
i compile script add `-s ASSERTIONS=1` , the error is 
`Unhandled Promise Rejection :RuntimeError :abort(CompileError:WebAssembly.Module doesn't parse at byte 1979:references are not enabled)at jsStackTrace ,promiseReactionJob@[native code](evaluating 'new WebAssembly.RuntimeError(what)')`

**Comment by yangfangfang1204** [comment]
the wasm is in `https://github.com/yangfangfang1204/wasm_error`

**Comment by yangfangfang1204** [comment]
the wasm file in https://github.com/yangfangfang1204/wasm_error

**Comment by yangfangfang1204** [comment]
the wasm file in https://github.com/yangfangfang1204/wasm_error , the jsPlugin.7z

**Comment by yangfangfang1204** [comment]
i solve the problem , my compile with -pthread or -flto -flto=full -flto=thin , compile without them ,it is ok in ios_safari
