### ISSUE TITLE
Emcmake generates invalid NMake files with CMake 3.21

### ISSUE THREAD

**Issue by gareth-morgan-autodesk** [emscripten-core/emscripten#15162]
I notice Emcmake generates invalid NMake files when used with CMake 3.21. So a cmakefile with an include path:
`target_include_directories(MyApp  PRIVATE ${include_paths})
`
Will generate a NMake file with this command:
`emcmake cmake .. -G "NMake Makefiles"`

That references a RSP resource file:
`em++.bat  @CMakeFiles/MyApp.dir/includes_CXX.rsp ...`

But that includes_CXX.rsp file will have  Byte Order Marks bytes at the start of the file.  em++ doesn't know how to process files with that encoding so will treat them as invalid characters and fail.  Rolling back to 3.20 will fix the issue, and there won't be BOM in the RSP file.

**Comment by sbc100** [comment]
This looks like an issue with cmake changing the format of the `@rsp` files.  Nothing to do with emcmake specifically I think but certainly and issue with emcc not handling all types of windows response files.  

Can I ask, doe this happen too if you use `-G "MinGW Makefiles"` ?

**Comment by yowl** [comment]
https://cmake.org/cmake/help/latest/release/3.21.html#other-changes is the cause I believe

**Comment by yowl** [comment]
Also notable perhaps is that Visual Studio 2022 now ships with CMake 3.21 so this is how I hit this.

**Comment by sbc100** [comment]
BTW, although we should certainly fix this, have you considered using the Ninja generator.  It has several advantages of makefiles and works on all platforms.

**Comment by yowl** [comment]
Yes, Should move to ninja, agree.

**Comment by sbc100** [comment]
The code where we read in the rsp files is here: https://github.com/emscripten-core/emscripten/blob/2fda25eea756c78c8cb024aa5b6c2b188bf7990f/tools/response_file.py#L87-L95

It looks like it should be reading in utf-8 by default .. which should be ok I think.     If anyone with a windows machine has time to take a look patches would be most welcome.

Alternatively if you could attach the filing `.rsp` file then perhaps I could repro on linux?

**Comment by yowl** [comment]
[objects1.txt](https://github.com/emscripten-core/emscripten/files/8111542/objects1.txt)
This is an example rsp file, starts with the odd looking bytes
```
scott@DESKTOP-K20F6IQ:/mnt/e/GitHub/runtimelab/artifacts/obj/coreclr/browser.wasm.Debug/CMakeFiles/CMakeTmp/CMakeFiles/cmTC_d6c1e.dir$ od -c objects1.rsp
0000000 357 273 277   C   M   a   k   e   F   i   l   e   s   /   c   m
```
I thought the BOM would be FE FF....

**Comment by yowl** [comment]
I think the line should be `guessed_encoding = 'utf-8-sig'` not `guessed_encoding = 'utf-8'`  I'll submit a PR
