### ISSUE TITLE
wrong cast float to byte

### ISSUE THREAD

**Issue by tmaurer3** [emscripten-core/emscripten#15165]
The C++ line 
Byte b = (Byte)x;
with x being a float of value 320 can result in 320 on the left side instead of the expected 64. This is for release mode only, it is correct in debug. (And with Byte defined as unsigned char.) 

I could correct this using the work around 
Byte b = (x >= 0 && x <= 255) ? (Byte)x : 0; 

I could not isolate this bug into a few lines of code. It only shows when building the library. 

To repro the bug: 

_ Download the source code from  https://github.com/Esri/lerc
_ Uncomment the line  https://github.com/Esri/lerc/blob/master/src/LercLib/include/Lerc_c_api.h#L27
_ Build it in release mode using CMakeLists.txt. 
I used (Ubuntu 20.4)
_ emcmake cmake .
_ emmake make
_ emcc libLerc.a src/LercTest/main.cpp -o lerc.html -s ALLOW_MEMORY_GROWTH=1
_ Run lerc.html in a browser. The error for the 1st test sample is way too big (should be < 0.1). 

To repro the work around: 

_ Repeat the above, but also uncomment  https://github.com/Esri/lerc/blob/master/src/LercLib/Defines.h#L41
_ Running lerc.html in the browser should now give the correct result (error < 0.1). 

The line that has the bug is  https://github.com/Esri/lerc/blob/master/src/LercLib/Lerc2.h#L496

I'm on version 2.0.26.

**Comment by kripken** [comment]
> I could not isolate this bug into a few lines of code. It only shows when building the library.

That is worrying - it suggests it is some result of complex optimizations somewhere in LLVM perhaps.

1. Does this only happen when optimizing? At which level?
2. Is this a regression? I'd try older versions, and if it works there, then [bisection](https://emscripten.org/docs/contributing/developers_guide.html#bisecting) would be very fast to figure this out.
3. [Sanitizers](https://emscripten.org/docs/debugging/Sanitizers.html) might help here - in particular, UBSan might find undefined behavior around that location that explains why LLVM optimizes it oddly.

**Comment by tmaurer3** [comment]
@kripken You are right: starts at -O1. Even better, I could isolate it now into a few lines of code: 

#include <cstdlib>
#include <cstdio>

int main(int argc, char* arcv[])
{
   float x = 320.0;
   unsigned char b = (unsigned char)x;
   int rv = ((float)b == x) ? 1 : 2;
   printf("%d\n", rv);
   return 0;
}

build this using
emcc repro.cpp -o repro.html -Oy

_ y = 0 outputs the correct result 2. 
_ y = 1 outputs the wrong result 0. 
_ y = 1 and casting x to (int) first outputs the correct result 2.

**Comment by tmaurer3** [comment]
@kripken  For some reason it lost the include files. They are cstdlib and cstdio.

**Comment by kripken** [comment]
I see, ok. Then I suspect this is undefined behavior in C, but I'm not an expert on that.

UBSan could probably confirm it. But in any case, to work around this, ensuring you cast values that are in range for the target type should fix things.

**Comment by tmaurer3** [comment]
@kripken  You are right again. I was not aware of this, it always worked for me with the compilers I use. As it says in 
https://www.cplusplus.com/doc/tutorial/typecasting/ :
"If the conversion is from a floating-point type to an integer type, the value is truncated (the decimal part is removed). If the result lies outside the range of representable values by the type, the conversion causes undefined behavior."
