### ISSUE TITLE
emscripten does not work with cygwin

### ISSUE THREAD

**Issue by wothke** [emscripten-core/emscripten#1516]
The existing installation instructions are useless when using Cygwin :-(

I built LLVM with Clang (version 3.2) - which took all night.. I installed Python 2.7.3. Just to then find out that Node.js is not supported for Cygwin and cannot be built! 

Therefore I installed the Win32 binary version of Node.js and at first this seemed to work, i.e the tests:
   clang tests/hello_world.cpp
   ./a.out 
and 
   node tests/hello_world.js

both worked.

But then running "python emcc" failed miserably.. the error message clearly indicates that  the win node.js messes up the linux/windows paths creating a bullshit path which cannot be found "D:\cygdrive\d\":

INFO     root: (Emscripten: Running sanity checks)

module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\cygdrive\d\emscripten\tests\hello_world.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
CRITICAL root: The JavaScript shell used for compiling (/cygdrive/d/nodejs/node) does not seem to work, check the paths in ~/.emscripten

Somewhere I read that using the windows Python version as well, might fix the problem - well I tried but it made things even worse..

Finally I tried to replace the rubbish node.js with Spidermonkey and I compiled the respective version 1.8 from scratch. But eventhough I tried to configure the .emscripten settings to use SPIDERMONKEY_ENGINE instead of NODE_JS (see COMPILER_ENGINE) I cannot seem to get rid of node.js, i.e. the above error message still appears :-((( 

Any suggestions for how I can get to a working Cygwin setup?

**Comment by jlmalet** [comment]
I got the same issue but in a different way : 
I tried at first to use the cygwin's CLang but since node.js can't be compiled into cygwin I ended to install a full emscripten in /cygdrive/c/Program Files/Emscripten/emscripten/1.35.0/emcc

in ~/.emscriptem 
```
# this helps projects using emscripten find it
EMSCRIPTEN_ROOT = 'c:\Program Files\Emscripten\emscripten\1.35.0' # directory
LLVM_ROOT = 'c:\Program Files\Emscripten\clang\e1.35.0_64bit' # directory
```
now time to run....
```
$ emcc
WARNING:root:did not see a source tree above or next to the LLVM root directory (guessing based on directory of c:\Program Files\Emscripten\clang\e1.35.0_64bit/llc), could not verify version numbers match
INFO:root:(Emscripten: Running sanity checks)
module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\cygdrive\c\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
Checking JS engine ['/cygdrive/c/Program Files/nodejs/node'] failed. Check ~/.emscripten. Details: Expected the command ['/cygdrive/c/Program Files/nodejs/node', '/cygdrive/c/Program Files/Emscripten/emscripten/1.35.0/src/hello_world.js'] to finish with return code 0, but it returned with code 1 instead! Output:
CRITICAL:root:The JavaScript shell used for compiling (['/cygdrive/c/Program Files/nodejs/node']) does not seem to work, check the paths in ~/.emscripten
````
first some strange things... that seems to be not related...
```
Error: Cannot find module 'C:\cygdrive\c\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js'
```
why is C:\ added?

anyway the main issue is here : 
```
 ['/cygdrive/c/Program Files/nodejs/node', '/cygdrive/c/Program Files/Emscripten/emscripten/1.35.0/src/hello_world.js']
```
which should be 
```
 ['/cygdrive/c/Program Files/nodejs/node', 'c:/Program Files/Emscripten/emscripten/1.35.0/src/hello_world.js']
```
and that's it!!!!
1. emscriptem seems to detect that it is in a cygwin environment since all path are translated to the standard cygwin path
2. node must always be run as a windows executable, not a cygwin one (unless it's path is configured as a cygwin path.. ie beginning with a "/"
3. not sure about this, but cygwin can work perfectly with both cygwin and windows path. for example 
``` 
cd 'c:\Program Files\'; #works correcly
ls 'C:\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js'
C:\Program Files\Emscripten\emscripten\1.35.0\src\hello_world.js; #ok also
```

=> either consider node as a windows program, or don't detect we are in cygwin and apply windows path everywhere if we are on a windows installation....

**Comment by jlmalet** [comment]
you might have a look at http://stackoverflow.com/questions/13162372/using-absolute-unix-paths-in-windows-with-python

**Comment by jlmalet** [comment]
to make it work...

install the full emscripten windows package found here : 
https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html  "Emscripten SDK Offline Installer"

then create a script (I called it emcc) with the following code : 
```
#!/bin/sh -x
IFS=$'\n'
i=0
while [ $# -gt 0 ]; do
        if [ -f "$1" ] || [ -d "$1" ]; then
                arg[$i]="$(cygpath -w $1)"
        else
                arg[$i]=$1
        fi
        i=$((i+1))
        shift
done
${WINPYTHON} $(cygpath -w $(which emcc))  "${arg[@]}"
````

run it once
edit ~/.emscripten file

change (as you see I made all the binaries point to the EMSCRIPTEN_ROOT installed version
````
EMSCRIPTEN_ROOT = os.path.expanduser(os.getenv('EMSCRIPTEN') or 'C:\\Program Files\\Emscripten\\emscripten\\1.35.0') # directory
LLVM_ROOT = os.path.expanduser(os.getenv('LLVM') or 'C:\\Program Files\\Emscripten\\clang\\e1.35.0_64bit') # directory

NODE_JS = os.path.expanduser(os.getenv('NODE') or 'C:\\Program Files\\Emscripten\\node\\4.1.1_64bit\\bin\\node.exe') # executable
SPIDERMONKEY_ENGINE = [os.path.expanduser(os.getenv('SPIDERMONKEY') or 'C:\\Program Files\Emscripten\spidermonkey\37.0.1_64bit\\js.exe')] # executable
````

now run 
````
./emcc hello_world.c
 /cygdrive/c/Program\ Files/Emscripten/node/4.1.1_64bit/bin/node.exe a.out.js
hello, world!

````

**Comment by jlmalet** [comment]
thread will continue on :
https://github.com/kripken/emscripten/issues/3947
