### ISSUE TITLE
WebGPU closure related error

### ISSUE THREAD

**Issue by cwoffenden** [emscripten-core/emscripten#15172]
Since #15063 when running closure it looks like `mgrDevice` is getting removed. This line here:

https://github.com/emscripten-core/emscripten/blob/12b2b675c202d2abc0a3f6c756939dde39eb199e/src/library_html5_webgpu.js#L65

After closure becomes, for example:
```
return I.mgrDevice.create(a, b)
```
But `mgrDevice` has been minified in `library_webgpu.js`. A simple working example is building [hello-webgpu](https://github.com/cwoffenden/hello-webgpu):
```
cd hello-webgpu
emcmake cmake -B out/web -DCMAKE_BUILD_TYPE=Release
cmake --build out/web --config Release
```
Running this in Chrome Canary errors with:
```
e544c2a2-0548-478c-8519-9deda0705349:formatted:177 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'create')
    at p (e544c2a2-0548-478c-8519-9deda0705349:formatted:177)
    at 6f3c1b6a:0x4ed
    at e544c2a2-0548-478c-8519-9deda0705349:formatted:184
```

**Comment by kainino0x** [comment]
Shoot, I forgot to update that one. I thought it would get caught by testing. I'll have to investigate why it didn't.

**Comment by kainino0x** [comment]
I figured out how to test it, but apparently there is more wrong than just this. Still haven't solved it.

**Comment by kainino0x** [comment]
@cwoffenden is the Closure build working for you before that change? I'm trying to test this and Closure is causing all sorts of issues that I haven't noticed before - in particular it keeps inlining/moving functions that are supposed to be methods (that use the `this` object) which causes them to repoint to a different `this` object and break entirely. I'm really not sure what's causing it or if it's been happening all along or not.

**Comment by kainino0x** [comment]
I figured out the issues, see #15180.

By the way, the preinitializedWebGPUDevice is no longer needed; I added support for requestAdapter and requestDevice.

**Comment by cwoffenden** [comment]
> is the Closure build working for you before that change

@kainino0x I don't think it's been working for a while (it works now though).
