### ISSUE TITLE
Uncaught RuntimeError: memory access out of bounds when use '_free’

### ISSUE THREAD

**Issue by donghang1994** [emscripten-core/emscripten#15184]
Hey everyone,
I am using _free to free the memory,but ran into an error: 
   Uncaught RuntimeError: memory access out of bounds;
and it comes up occasionally.

**Comment by sbc100** [comment]
This is almost certainly an application bug.. most likely memory corruption of some kind.    You can try building `-fsanitize=address` (both in your compiler and link flags) to try to track down where the error is coming from.

**Comment by donghang1994** [comment]
> This is almost certainly an application bug.. most likely memory corruption of some kind. You can try building `-fsanitize=address` (both in your compiler and link flags) to try to track down where the error is coming from.



> > This is almost certainly an application bug.. most likely memory corruption of some kind. You can try building `-fsanitize=address` (both in your compiler and link flags) to try to track down where the error is coming from.
> 
> What function is it? After I use it, do I run into memory problems and stop running directly

**Comment by donghang1994** [comment]
> This is almost certainly an application bug.. most likely memory corruption of some kind. You can try building `-fsanitize=address` (both in your compiler and link flags) to try to track down where the error is coming from.

What function is it? After I use it, do I run into memory problems and stop running directly

**Comment by donghang1994** [comment]
> `-fsanitize=address` is a tools called Address Sanitizer of ASan (https://clang.llvm.org/docs/AddressSanitizer.html). It should give you a report if detects any issues, and the report should be printed to the console.

Thank you very much. Let me try and look into the problem first and see if I can identify the talent problem.
