### ISSUE TITLE
multiple `may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library` causes link error

### ISSUE THREAD

**Issue by ericoporto** [emscripten-core/emscripten#15195]
I have multiple `warning: X may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library`, where X are mangled Cpp function names, and right after I get `error: undefined symbol: X (referenced by top-level compiled C/C++ code)`, where X is again the same function (but only the first from the many ones I get only a warning). 

And then finally this will error `Error: Aborting compilation due to previous errors` and this is all at link time AFAICT... These errors definitely didn't happen in a previous version of Emscripten. These functions are NOT called from JS code. These are just regular functions from my own code and they have nothing special...

**Comment by sbc100** [comment]
Is this is statically linked executable (i.e. its not MAIN_MODULE or SIDE_MODULE?)?    I assume so.  In which case it seems like the linker cannot find those C++ symbols.

Can you try to track down which very of emsdk these error started to occur in.  We have instruction for doing that here: https://emscripten.org/docs/contributing/developers_guide.html#bisecting.

My advice would be to take one of those X symbols that try to figure out why the linker can't find it.  Which object file or library should contain the symbol?  Is that object or archive be passed in correctly on the link command line?

**Comment by ericoporto** [comment]
I can't seem to be able to write a  code that reproduces this error, but it does appear with my more complex codebase, and it still happens with latest Emscripten. Only thing these functions have in common is that they are all `static` functions.

**Comment by ericoporto** [comment]
removing static keyword fixed.
