### ISSUE TITLE
clang++ is not a valid Win32 application 

### ISSUE THREAD

**Issue by wothke** [emscripten-core/emscripten#1520]
I followed the step by step instructions to setup a Windows toolchain (using the prebuilt gcc/clang supplied in the .7z files).

Unfortunately the respective prebuilt stuff seems to be unusable:

When I am trying to build my C file library (which compiles fine using gcc) I an getting the message that clang++ is not a valid Win32 application:

D:\emscripten>python emcc -c sidplayerJS/sidplayer.c
DEBUG    root: invocation: emcc -c sidplayerJS/sidplayer.c
ERROR    root:
subprocess.Popen(args=D:/mingw64/bin\clang++ -v) failed! Exception [Error 193] %
1 is not a valid Win32 application

WARNING  root: Could not verify LLVM version: [Error 193] %1 is not a valid Win3
2 application
INFO     root: (Emscripten: Running sanity checks)
DEBUG    root: compiling to bitcode
DEBUG    root: compiling source file: sidplayerJS/sidplayer.c
DEBUG    root: running:D:/mingw64/bin\clang -U__i386__ -U__i386 -Ui386 -U__SSE__
 -U__SSE_MATH__ -U__SSE2__ -U__SSE2_MATH__ -U__MMX__ -DEMSCRIPTEN -D__EMSCRIPTEN
__ -U__STRICT_ANSI__ -D__IEEE_LITTLE_ENDIAN -fno-math-errno -target le32-unknown
-nacl -U__native_client__ -U__pnacl__ -U__ELF__ -nostdinc -Xclang -nobuiltininc
-Xclang -nostdsysteminc -Xclang -isystemD:\emscripten\system\local\include -Xcla
ng -isystemD:\emscripten\system\include\libcxx -Xclang -isystemD:\emscripten\sys
tem\include -Xclang -isystemD:\emscripten\system\include\emscripten -Xclang -isy
stemD:\emscripten\system\include\bsd -Xclang -isystemD:\emscripten\system\includ
e\libc -Xclang -isystemD:\emscripten\system\include\gfx -Xclang -isystemD:\emscr
ipten\system\include\net -Xclang -isystemD:\emscripten\system\include\SDL -U__AP
PLE__ -U__linux__ -c -emit-llvm -c sidplayerJS/sidplayer.c -o /tmp\tmph1oqw3\sid
player_0.o
ERROR    root:
subprocess.Popen(args=D:/mingw64/bin\clang -U__i386__ -U__i386 -Ui386 -U__SSE__
-U__SSE_MATH__ -U__SSE2__ -U__SSE2_MATH__ -U__MMX__ -DEMSCRIPTEN -D__EMSCRIPTEN_
_ -U__STRICT_ANSI__ -D__IEEE_LITTLE_ENDIAN -fno-math-errno -target le32-unknown-
nacl -U__native_client__ -U__pnacl__ -U__ELF__ -nostdinc -Xclang -nobuiltininc -
Xclang -nostdsysteminc -Xclang -isystemD:\emscripten\system\local\include -Xclan
g -isystemD:\emscripten\system\include\libcxx -Xclang -isystemD:\emscripten\syst
em\include -Xclang -isystemD:\emscripten\system\include\emscripten -Xclang -isys
temD:\emscripten\system\include\bsd -Xclang -isystemD:\emscripten\system\include
\libc -Xclang -isystemD:\emscripten\system\include\gfx -Xclang -isystemD:\emscri
pten\system\include\net -Xclang -isystemD:\emscripten\system\include\SDL -U__APP
LE__ -U__linux__ -c -emit-llvm -c sidplayerJS/sidplayer.c -o /tmp\tmph1oqw3\sidp
layer_0.o) failed! Exception [Error 193] %1 is not a valid Win32 application

ERROR    root: Invoking Process failed: <<< D:/mingw64/bin\clang -U__i386__ -U__
i386 -Ui386 -U__SSE__ -U__SSE_MATH__ -U__SSE2__ -U__SSE2_MATH__ -U__MMX__ -DEMSC
RIPTEN -D__EMSCRIPTEN__ -U__STRICT_ANSI__ -D__IEEE_LITTLE_ENDIAN -fno-math-errno
 -target le32-unknown-nacl -U__native_client__ -U__pnacl__ -U__ELF__ -nostdinc -
Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystemD:\emscripten\syste
m\local\include -Xclang -isystemD:\emscripten\system\include\libcxx -Xclang -isy
stemD:\emscripten\system\include -Xclang -isystemD:\emscripten\system\include\em
scripten -Xclang -isystemD:\emscripten\system\include\bsd -Xclang -isystemD:\ems
cripten\system\include\libc -Xclang -isystemD:\emscripten\system\include\gfx -Xc
lang -isystemD:\emscripten\system\include\net -Xclang -isystemD:\emscripten\syst
em\include\SDL -U__APPLE__ -U__linux__ -c -emit-llvm -c sidplayerJS/sidplayer.c
-o /tmp\tmph1oqw3\sidplayer_0.o >>>
Traceback (most recent call last):
  File "emcc", line 1112, in <module>
    execute([call] + args) # let compiler frontend print directly, so colors are
 saved (PIPE kills that)
  File "D:\emscripten\tools\shared.py", line 1414, in execute
    return Popen(cmd, _args, *_kw).communicate() # let compiler frontend print d
irectly, so colors are saved (PIPE kills that)
  File "D:\emscripten\tools\shared.py", line 52, in **init**
    raise e
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by derofim** [comment]
still same problem

**Comment by mwroffo** [comment]
Hello, all, I am seeing this same error but with bin\asm2wasm. Has this been resolved? I am about to try installing a 32-bit version of asm2wasm.

**Comment by juj** [comment]
@mwroffo Does `emsdk install sdk-incoming-32bit binaryen-master-32bit` work for you to build from source? (then followed by `emsdk activate sdk-incoming-32bit binaryen-master-32bit`?) If not, log may help diagnose.
