### ISSUE TITLE
stringstream is broken

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#15216]
@kripken  @sbc100 

Running following program prints `4294967295`, but it should print `3298296754453734607`. It works fine on non-emscripten aka native.  

Anyway, I found this randomly. 

```
#include <iostream>
#include <sstream>
#include <string>

size_t to_size_t(std::string number) {
    std::stringstream sstream(number);
    size_t result;
    sstream >> result;

    return result;
}

int main()
{
  std::cout << to_size_t(std::string("3298296754453734607")) << "\n";
}

```

**Comment by sbc100** [comment]
This is because size_t is 32-bit on wasm (WebAssembly is ILP 32 platform).     For 32-bit targets that correct output is 4294967295.  You can verify this using `g++ -m32` or `clang++ -m32` on desktop linux.

**Comment by jeffRTC** [comment]
@sbc100  So, which one should I use to get 3298296754453734607 if size_t on wasm doesn't allow it?

**Comment by sbc100** [comment]
You should be able to use `long long` to get a 64-bit result... or of course `int64_t` / `uint64_t`

**Comment by jeffRTC** [comment]
`typedef unsigned long long size_txx;`

Works ..
