### ISSUE TITLE
Missed $DNS dependency for $getSocketAddress function in src/library_syscall.js

### ISSUE THREAD

**Issue by andrewevstyukhin** [emscripten-core/emscripten#15238]
`$getSocketAddress` function uses `DNS.lookup_addr` but doesn't publish all dependencies
https://github.com/emscripten-core/emscripten/blob/8e16c4ab8034c09dd917c0ff15989585e060927a/src/library_syscall.js#L455

And I have a runtime error:
> ReferenceError: DNS is not defined

=> `$getSocketAddress__deps: ['$readSockaddr', '$DNS'],`

**Comment by sbc100** [comment]
Looks like the correct fix.  How do you feel about uploading a PR?

**Comment by andrewevstyukhin** [comment]
I just tested it locally ;)

**Comment by andrewevstyukhin** [comment]
I'll try to make a PR with `$getSocketAddress__deps: ['$readSockaddr', '$FS', '$DNS'],`
