### ISSUE TITLE
Additional custom WebWorker interface?

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#15278]
Hi, I want to extend WebWorker interface for custom JS library implementation. I require this because library has to execute some action in main thread. For now I edit default library in js file created by emscripten. For example:
``` } else if (cmd === 'cleanupThread') {
       cleanupThread(d['thread']);
     } else if (cmd === 'killThread') {
        killThread(d['thread']);
     } else if (cmd === 'cancelThread') {
         cancelThread(d['thread']);
     } else if (cmd === 'custom') { // Custom 'onMessage' action
     ...........
     }
``` 
The same action in worker library:
``` 
postMessage({
   "cmd": "custom",
   "someData": someData
    });
 ```
Are there any other convenient way to make it or it is the only way ??

**Comment by juj** [comment]
You can add your own event listener to the same message event with `self.addEventListener('message', (event) => { ... });`. The browser will call all registered listeners with each received event. That way you can ignore the built-in events, and only process your own.

In your own events, you can just omit the `cmd` field altogether, and use some other identifying mechanism if you please (no need to adhere to Emscripten's message format)

**Comment by DiachenkoIgor** [comment]
@juj Thank you.
