### ISSUE TITLE
CMAKE_SYSTEM_PROCESSOR is fixed to x86, making it difficult to use NEON headers

### ISSUE THREAD

**Issue by ngzhian** [emscripten-core/emscripten#15284]
Many projects do some sort of CPU detection, e.g. [libgav1]. This CPU detection is then further used to enable SIMD extensions, x86 -> SSE, arm -> NEON.

(https://chromium.googlesource.com/codecs/libgav1/+/refs/heads/main/cmake/libgav1_cpu_detection.cmake#23), in Emscripten.cmake, it is fixed to "x86", so we will only be able to enable SSE.

With #15265, my hope was to be able to specify `CMAKE_SYSTEM_PROCESSOR` on the command line, like `emcmake cmake -DCMAKE_SYSTEM_PROCESSOR=arm` to easily overwrite what is specified in the toolchain path, alas it doesn't work (I should have tested it first).

So, I'm wondering what other things we can do here.

One way is to create another toolchain file that specifies arm, but that seems unscalable. An alternative is to try to read a special cmake property, then set CMAKE_SYSTEM_PROCESSOR to it, maybe something like:

```
if ("${EMSCRIPTEN_SYSTEM_PROCESSOR}" STREQUAL "")
  set(EMSCRIPTEN_SYSTEM_PROCESSOR x86)
endif()
set(CMAKE_SYSTEM_PROCESSOR ${EMSCRIPTEN_SYSTEM_PROCESSOR})
```

Would like to get opinions from CMake users, thanks!

**Comment by sbc100** [comment]
Can we just conditionally set `CMAKE_SYSTEM_PROCESSOR` if its not already set?
