### ISSUE TITLE
Change Response Files encoding to be identified by response file suffix?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#15292]
When python sees `open(file, 'r')` without explicit `encoding=` parameter, it opens a text file using the default system encoding. This happens today at https://github.com/emscripten-core/emscripten/blob/ff23b8c623d053dbeb9c1fd87fd5f47e27a5d8da/tools/response_file.py#L80

So when users are calling emcc and other tools with response files, they need to encode their response files using the current system encoding locale.

It would be preferable to always use utf-8 encoding to encode response files with, but there is a danger that changing `open(file, 'r', encoding='utf-8')` there will break existing user build systems.

For example on Windows if a shell script did `echo arg1 arg2 arg3 arg4 > file.rsp`, I believe that will create a current system encoding locale encoded file.

Also related, we have this quirky code when different Emscripten tools create response files:

https://github.com/emscripten-core/emscripten/blob/ff23b8c623d053dbeb9c1fd87fd5f47e27a5d8da/tools/response_file.py#L44-L53

here the code is making an assumption that the only time the Emscripten toolchain is creating response files, it would be creating those in a call to an LLVM tool. This might be true, though the intent of `create_response_file()` definitely is not to create response files only for LLVM to consume.

(btw I believe the answer to that TODO above is 'yes')

To fix both of these, I would propose that the response file logic would use the file suffix to decide what the encoding of the file should be:
 - if the suffix is `.utf8`, then the response file should be created and/or read using explicit utf-8 encoding.
 - if the suffix is anything else (e.g. the usual `.rsp`), then the response file should be created using current system encoding locale.

Then when Emscripten users are creating response files, they can create files with suffix `.rsp` or `.rsp.utf8` to choose either current locale (`open(file, 'r')` in python), or utf-8 locale (`open(file, 'r', encoding='utf-8')` for python). Likewise, the function `create_response_file()` can then be extended to take in a suffix, and the call sites to that tool can choose which encoding to use (I think they all will want `.rsp.utf8` at the moment)

Does that sound good?

**Comment by sbc100** [comment]
I remember digging into this a while back finding it very thorny.    I would not be opposed to your suggestion if it solves a real problem.

What other tools are you imagining `create_response_file` files being fed too?  Aren't llvm and binaryen the only tools that emscripten invokes internally?

**Comment by ab-unity** [comment]
Detecting the difference between ASCII and UTF-8 is hard without a Byte order Mark.

**Comment by juj** [comment]
> But we don't know if windows presents that problem to us or not. It could be that the BOM is present in all the cases we care about?

There is no guarantee that users who have crafted response files would have created the files with a BOM? Recall that these files all come from the users of Emscripten, and not just internally created by the Emscripten toolchain when invoking subprocesses.

> Detecting the difference between ASCII and UTF-8 is hard without a Byte order Mark.

Also to clarify, the issue here was not ASCII vs UTF-8 (ASCII is a subset of UTF-8, so would be fine to hoist to unconditionally decode ASCII files as UTF-8 in that case), but e.g. [Windows Codepage 437](https://en.wikipedia.org/wiki/Code_page_437) vs UTF-8 and/or [Windows Codepage 1252](https://en.wikipedia.org/wiki/Windows-1252) vs UTF-8, or some other "default system encoding" vs UTF-8.

We could try autodetecting the encoding by first attempting to decode it as UTF-8 and if parsing the file using that fails, then load it using the system current locale. But I find that it is better to have support to be explicit.

Posted #15406 to fix this.
