### ISSUE TITLE
Documentation of --default-obj-ext is misleading

### ISSUE THREAD

**Issue by RobertoBagnara** [emscripten-core/emscripten#15312]
It suggests that the following works, when dir is a directory:

    emcc -c a.c -o dir/

But it doesn't:

$ ls -ld dir
drwxrwxr-x 2 roberto roberto 4096 ott 17 18:49 dir
$ emcc -c a.c -o dir/
error: unable to open output file 'dir/': 'Is a directory'
1 error generated.
emcc: error: '/opt/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=31 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -c a.c -o dir/' failed (returned 1)
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.31 (4fcbf0239ccca29771f9044c990b0d34fac6e2e7)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by sbc100** [comment]
Ah, thanks for pointer that out.  The documented behaviour may have been how emscripten used to work a long time ago, but I can't find where in the history changed.  Today, just like with clang and gcc, the only way to compile multiple source files at the same time with `-c `is to not used `-o`.    In other works `-c` + multiple sources  + `-o` is not valid. I've created a change to update the doc: #15316.

For example if you try to do this with gcc you will get:

```gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or ‘-E’ with multiple files```
