### ISSUE TITLE
Preprocessor directives for defining constants causes mathematical errors on division when constant is defined twice.

### ISSUE THREAD

**Issue by traviszuleger** [emscripten-core/emscripten#15311]
As stated in the title, I've noticed this error while developing an Emulator where I wanted the bank size defined as a preprocessor directive.
```
#define KILOBYTES 1024
#define BANK_SIZE 16 * KILOBYTES
int numBanks = (this->size / BANK_SIZE) + 1; // this->size was checked and verified to be 256 (bytes). This SHOULD be 1.
std::cout << "(" << this->size << "/" << BANK_SIZE << ")+1 = " << numBanks << std::endl; // This yields the output of "(256/16384)+1 = 16385"
```

I feel like I haven't had this issue but I never cared to check how many banks were initialized on the start of the Emulator. While debugging, I happened to see there was 16385 banks initialized for only the Gameboy Bootrom (256 bytes would mean 1 bank to store that 256 bytes). I feel like part of it has to do with the fact I "redefined" BANK_SIZE in a different part of code. But all I did was redefine it back to itself of 16384.

This error doesn't similarly come up with different operations. It seems to ONLY happen with Division and my guess is that the the preprocessor parses and removes everything in the parentheses and replaces it with the directive, hence why it ends up as BANK_SIZE + 1 (16384 + 1 = 16385)

I also replaced BANK_SIZE with 16384 directly and I ended up getting 1 as expected.

**Comment by gl84** [comment]
The preprocessor only substitutes text. This means you get:
```C++
int numBanks = (this->size / 16 * 1024) + 1;
```
which is evaluated as ( this->size / 16 ) * 1024 + 1.

Either use something like
```C++
#define BANK_SIZE  (16 * KILOBYTES )
```
or even better use global constants like
```C++
const int KILOBYTES = 1024;
const int BANK_SIZE = 16 * KILOBYTES;
```

**Comment by traviszuleger** [comment]
I should've known that. Thank you for the clarification.
