### ISSUE TITLE
Subtle race conditions in websocket_to_posix_proxy

### ISSUE THREAD

**Issue by ddiminnie** [emscripten-core/emscripten#15341]
It appears that there are a few race conditions around the socket registry used in the "websocket_to_posix_proxy" server.  (Note that we are currently only running this server under Windows, using both "Release x64" and "Debug x64" builds.)

Commands like 'accept', are run in a separate thread, while commands like 'shutdown' are run in the main thread.

`Accept` adds a new socket to the socket registry via `TrackSocketUsedByConnection`.
`Shutdown` removes a socket from the socket registry via `CloseSocketByConnection`.

Because these run in separate threads there are rare occurrences where the sequence 'shutdown ... accept' can race (e.g. when the new socket created by 'accept' has the same handle as the socket closed by 'shutdown').  Here's one example:

```
Shutdown calls CloseSocketByConnection on main thread
(CloseSocketByConnection:) CLOSE_SOCKET(usedSocket);
     Accept calls accept on separate thread.
     accept returns the same socket handle as the one just closed (since the handle is now available again)
     Accept calls TrackSocketUsedByConnection
     IsSocketPartOfConnection(proxyConnection, usedSocket) returns true, so TrackSocketUsedByConnection returns
CloseSocketByConnection) sockets.erase(std::remove(sockets.begin(), sockets.end(), usedSocket), sockets.end()); wipes socket from registry.
```

In this case subsequent calls to 'recv' or 'send' on the socket returned by Accept will fail.  Here's a typical console log with POSIX_SOCKET_DEBUG enabled:

```
shutdown(socket=441300,how=2)->0
Closing socket fd 441300 used by proxy connection 232
accept returned 441300 (address="02 00 F4 F3 7F 00 00 01 00 00 00 00 00 00 00 00  (16 bytes)")
recv(): Proxy client connection client_fd=232 attempted to call recv() on a socket fd=441300 that it did not create (or has already shut down)
```

The other race we've seen appears to work in the opposite direction:  A socket is added to the registry between the calls to `std::remove` and `sockets.erase` in `CloseSocketByConnection`.  The observed symptom in this case (in debug builds) is an assertion failure in `sockets.erase`.

We appear to have fixed this problem locally by creating a new MUTEX_T object (e.g. "socketRegistryLock") and surrounding calls to `TrackSocketUsedByConnection` and `CloseSocketByConnection` (in "websocket_to_posix_proxy.cpp") by `MUTEX_LOCK(&socketRegistryLock);` and `MUTEX_UNLOCK(&socketRegistryLock);` calls.  (I say "appear" because the conditions mentioned above are rare even without the fix - on any given Sunday we might successfully execute 15000 'shutdown...accept...recv...send...' sequences without running into any problem, while on the next day we hit one in only 100 or so sequences.  Also, I can't guarantee that someone else's workflow on a platform other than Windows won't trigger a deadlock with this suggested change...  However, we've successfully made 250000 websocket calls to the "websocket_to_posix_proxy" server with this suggested change without seeing a problem.  I'll leave it to someone more adept at programming in multithreaded environments to judge whether the suggested fix is a good idea.)

**Comment by juj** [comment]
Good diagnosis - indeed looks like there is a possibility to race. Thanks also for working on a fix!

**Comment by ddiminnie** [comment]
I see that the proposed fix has been merged.  Do you need anything else from me before you can close this issue?

**Comment by kripken** [comment]
Thanks @ddiminnie , closing.
