### ISSUE TITLE
Update website theme for newer Sphinx

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#15365]
See https://github.com/emscripten-core/emscripten/pull/15361#issuecomment-952331375, the current theme appears to be tailored for older versions. Before we upgrade Sphinx we'll need to fix the theme.

**Comment by jonassmedegaard** [comment]
Possibly irrelevant if starting over from scratch, but Debian maintainer for Sphinx provided some insight into modernizing at https://bugs.debian.org/1000136

**Comment by sbc100** [comment]
This is awesome progess!  Thanks @lorsanta!

**Comment by sbc100** [comment]
And thanks @jonassmedegaard for making it possible!

**Comment by lorsanta** [comment]
No problem @sbc100 , happy to help!

**Comment by sbc100** [comment]
I noticed that that anchor symbols are missing. e.g. https://emscripten.org/docs/contributing/developers_guide.html#bisecting

There used to be a chainlink symbol after each heading I think.

**Comment by lorsanta** [comment]
The FontAwesome related files are missing from `_static\css`. It's strange, though, because they are present when you build the site locally.

**Comment by kripken** [comment]
Thanks @lorsanta , that was it! I didn't notice I needed to `git add` those new files. It looks fixed to me now.
