### ISSUE TITLE
Exceptions not working even with DISABLE_EXCEPTION_CATCHING=0

### ISSUE THREAD

**Issue by ekkxl** [emscripten-core/emscripten#15370]
I'm working on developing a programming language, which directly generates LLVM files which I compile with emscripten to generate JS files.  Everything works except exceptions which are not being caught properly.  I'm building with -fexception and -s DISABLE_EXCEPTION_CATCHING=0.  More strange is I also have a runtime library written in C++, and exceptions are being caught there.  So an example stack trace

1. some_function_that_throws
2. some_function_that_catches
3. cpp_function_that_catches

The exception should be caught by 2 but is being caught by 3.  Same problem with WASM on or off.  Here's a snippet of my LLVM assembly:

```
	invoke void @K_throw( %t_struct %t_16 ) to label %label_7 unwind label %label_6
label_7:
	; some code
label_6:
	%t_49 = landingpad { i8*, i32 } cleanup
	store { i8*, i32 } %t_49, { i8*, i32 }* %exceptionInfo
	%t_49_exception_value = extractvalue { i8*, i32 } %t_49, 0
	store i8* %t_49_exception_value, %t_exception* %exception
	; more code
```

So in this case K_throw will throw, but it's not being caught by the landingpad,  Looking at the generated JS code with WASM off, I see that it's not even generating an invoke_XXX call for the call to K_throw.

I've tried compiling the C++ runtime files with -S emit-llvm and compared that to the LLVM code I'm generated, and I don't see any significant difference in the way I'm defining functions, personality functions, landing pads, etc.

All of this code worked perfectly under an old version of emscripten (1.37.21).  I updated to the latest version (2.0.32) and exceptions stopped working without any changes to my files.

**Comment by aheejin** [comment]
Do we support compiling ll/bc files directly?
Also cc @sbc100 for the #12705 question.

**Comment by sbc100** [comment]
It appears that we do yes.   More specifically, if clang supports it then I think its good that we support it too.

**Comment by sbc100** [comment]
> ```
> emcc++ (options) -o foo.o foo.cpp
> ```
> 
> should be equivalent to
> 
> ```
> emcc++ (options) -c -S -emit-llvm foo.ll foo.cpp
> emcc++ (options) -o foo.o foo.ll
> ```
> 
> in all cases, but it's not here.

Are you expecting `foo.o` to be and object file here?  If so, don't you need a `-c` in both commands above?

**Comment by ekkxl** [comment]
My mistake, I meant .js.  I've edited my other comment.

**Comment by sbc100** [comment]
> My mistake, I meant .js. I've edited my other comment.

In that case yes, we would hope those would produce the same results.

**Comment by ekkxl** [comment]
It seems we agreed this is a bug, and have a small reproducible case - is this something that's going to be fixed?  I've looked at the change that introduced the issue, but I don't understand enough to figure out what the proper fix would be.

**Comment by sbc100** [comment]
Yes this certainly looks like a bug in our handling of `-S` + `-emit-llvm`

**Comment by sbc100** [comment]
I'll take a look at fixing it.

**Comment by ekkxl** [comment]
I believe the problem is not in -S -emit-llvm, but rather when compiling .ll files.  I believe what's happening is when given a file beside a .c or .cpp file, emscripten is stripping out all of the non-source options, such as -fexceptions.  This means that when given an .ll file with invokes/landingpads/etc, emscripten is removing them instead of lowering them to the appropriate invoke_XXX calls.

It seems the solution might be as simple as considering .ll files source files like .c and .cpp files.

Note in my use case I'm not using -S -emit-llvm.  I'm compiling a different language (not C++) to ll files, then running emscripten on them to enable web development for that other language.  This was working before 511bd90.

**Comment by ekkxl** [comment]
My use case works again.  Thank you!
