### ISSUE TITLE
Document NODERAWFS

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#15377]
[NODERAWFS](https://github.com/emscripten-core/emscripten/blob/fde55d2f0f54f167a64a77ed013d2bbf22ab152d/src/settings.js#L881-L892) is pretty useful as a simple way to make compiled code in node access files normally. We should document it on

https://emscripten.org/docs/api_reference/Filesystem-API.html#file-systems

**Comment by eleensmathew** [comment]
Hi I am interested to work on this. Since I am relatively new can you please guide me?

**Comment by kripken** [comment]
@eleensmathew Sure, here are some notes that might help: The link above is to where that doc page is rendered. The source page is at `site/source/docs/api_reference/Filesystem-API.rst`, so that would be the file to modify. `docs/process.md` has some notes on how to build the docs locally, which is basically
* `pip3 install -r requirements-dev.txt`
* go to `site/`
* `make html`

**Comment by eleensmathew** [comment]
What Exactly should i write in the document about NODERAWFS?

**Comment by eleensmathew** [comment]
Should i make a html about NODERAWFS site/?

**Comment by eleensmathew** [comment]
Should i git clone the entire repository?

**Comment by kripken** [comment]
I would add a similar amount of details as the others (NODEFS, MEMFS, etc.) already in that doc.

You can clone the repo to make a PR. For a single file's changes, though, I think github has a simpler UI that you can use, if you find an edit button on it when viewing on github.

**Comment by eleensmathew** [comment]
But where would I get details specifically about NODERAWFS. I am a complete newcomer so if this issue requires a certain skillset then please unassign me.

**Comment by kripken** [comment]
You can find some details in `src/settings.js`. If that's not enough, the test suite may be a good place to look - you can see how it is used there.

**Comment by eleensmathew** [comment]
I created a pull request. Please review it and tell me if there is anything I should change.

**Comment by dtroitskiy** [comment]
Hey guys, sorry for bringing this up, I guess, but I've stumbled upon this issue after I read about `NODERAWFS` in the docs, but there wasn't any hint about how to actually use it. I then figured out that you don't require any special actions, filesystem just works like in plain C / C++, BUT I had to blindly guess that you need to add `-lnoderawfs.js` linker flag together with already mentioned `-lnodefs.js`. I suppose this additional flag needs to be mentioned in the docs.
