### ISSUE TITLE
Request: Update libc++ to LLVM 13

### ISSUE THREAD

**Issue by Urfoex** [emscripten-core/emscripten#15396]
[LLVM 13.0.0 got released on 4 Oct 2021](https://releases.llvm.org/)

Would it be possible to update to it?

I would currently be most interested in
["The implementation of the C++20 concepts library has been completed."](https://releases.llvm.org/13.0.0/projects/libcxx/docs/ReleaseNotes.html#id3)

Older tickets:
[c++ 20 concept support](https://github.com/emscripten-core/emscripten/issues/14236)
[concepts not supported](https://github.com/emscripten-core/emscripten/issues/11552)

**Comment by kripken** [comment]
Updated title to focus on libc++, as this is special to that (the emsdk already uses newer LLVM, but not libc++ yet).

**Comment by kripken** [comment]
If someone is interested to work on this, Emscripten has a bundled version of libc++ in `system/lib/libcxx/`. I believe to upgrade libc++ the first step would be to open a PR with LLVM 13's libc++ replaced there, and then to work through any issues with tests if there are any.

**Comment by sbc100** [comment]
This change should probably also include updates to compiler-rt and libc++-abi as well.  There are some scripts that should make the process easier:
https://github.com/emscripten-core/emscripten/blob/main/system/lib/update_libcxx.py
https://github.com/emscripten-core/emscripten/blob/main/system/lib/update_compiler_rt.py
https://github.com/emscripten-core/emscripten/blob/main/system/lib/update_libcxxabi.py

**Comment by Urfoex** [comment]
> This change should probably also include updates to compiler-rt and libc++-abi as well. There are some scripts that should make the process easier: https://github.com/emscripten-core/emscripten/blob/main/system/lib/update_libcxx.py https://github.com/emscripten-core/emscripten/blob/main/system/lib/update_compiler_rt.py https://github.com/emscripten-core/emscripten/blob/main/system/lib/update_libcxxabi.py

Looking at those python scripts, they just copy files. I suspect, that there need some patches to be applied, or reapplied afterwards, as pointed out in e.g. https://github.com/emscripten-core/emscripten/blob/main/system/lib/libcxx/readme.txt

**Comment by kripken** [comment]
Yes, it may make sense to look at the diff before, then apply it afterwards.

**Comment by Urfoex** [comment]
Tried building LLVM.
Run into some RAM problems when linking.
Changing the linker from ld to ldd helped a lot. (Gold might also work.) 
Release instead of Debug might also have helped.
```
CMAKE_BUILD_TYPE: Release
CMAKE_LINKER: /usr/bin/lld
GOLD_EXECUTABLE: /usr/bin/lld
```

I created a pull request against main to update it to latest upstream. (If that was ok. Sounded sensible before branching off its tag: llvmorg-13.0.0 )

**Comment by sbc100** [comment]
Hopefully updating libc++/libc++abi/compiler-rt in emscripten will not actually require the building of llvm.   Is there some reason you need to build it that I'm missing?

**Comment by sbc100** [comment]
There should be no need to configure or build llvm to update emscripten's library code.     IIUC, all compiling and testing of these library copies is done in the emscripten tree.    The llvm tree is just the place where the upstream sources live, and where we hope to one day upstream all out changes (#15097)

**Comment by Urfoex** [comment]
You don't want to at least test compile the code to see if it might has problems?

Ah! 
I see.
Inside the emscripten tree.
That would make sense.
As I was now missing out on `wasi/api.h`. And installing wasi-libc didn't directly help...

**Comment by sbc100** [comment]
I'm afraid there might be a lot of internal implementation of knowledge required to do this update.   The process is (sadly) not well documented.   Unless you are keen to learn a lot of how all this fits together it might not be good task to take on as  new contributor.  

The `wasi/api.h` file should remain intact during this update, it comes from wasi-sdk originally.   The file lives in `system/include/wasi/api.h` which should not be effected by this change.

**Comment by Urfoex** [comment]
> I'm afraid there might be a lot of internal implementation of knowledge required to do this update. The process is (sadly) not well documented. Unless you are keen to learn a lot of how all this fits together it might not be good task to take on as new contributor.

I'm afraid you are very much right.
I dug through emsdk and emscripten, trying to get the tests running, as I thought, maybe after copying the new lib-versions over it would be good to see, that it still works. But I also didn't get them to work. Step by step hitting one roadblock after another. Frustrating. So, I'll better stop here and wait for some experienced people to solve this. Sorry.
