### ISSUE TITLE
Is there way to delay starting main?

### ISSUE THREAD

**Issue by jeffRTC** [emscripten-core/emscripten#15395]
@sbc100 

Is there a callback something like onStart (There is atExit already on Emscripten) that could halt the emscripten calling main for some period by supplying my await code?

Right now, I'm using emscripten_sleep on main but that has run time cost.

**Comment by sbc100** [comment]
I think simplest way it probably the -sNO_INVOKE_RUN option:

```
// Whether we will run the main() function. Disable if you embed the generated   
// code in your own, and will call main() yourself at the right time (which you  
// can do with Module.callMain(), with an optional parameter of commandline args).
// [link]                                                                        
var INVOKE_RUN = 1; 
```

**Comment by jeffRTC** [comment]
Thanks so I should use pre-js to add my delay code?

**Comment by sbc100** [comment]
I'm not quite sure what you are asking.   You can use onRuntimeInitialized to know when the module is available for use: https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions.  You can then delay as long as you want before calling into the module either via `callMain` or some other entry point.

**Comment by SirNate0** [comment]
This discusses another way to accomplish it (seeking to implement a click-to-play feature since audio is disabled until user interaction): https://github.com/libsdl-org/SDL/issues/6385#issuecomment-1276220297

The linked code is summarized below. A dependency is added for the module until the user clicks, at which point it is removed.

```js

function startGame()
{
    Module["removeRunDependency"]("dragonruby_init");
}

var Module = {
  noInitialRun: false,
  preInit: [],
  clickedToPlay: false,
  clickToPlayListener: function() {
    if (Module.clickedToPlay) return;
    Module.clickedToPlay = true;
    var div = document.getElementById('clicktoplaydiv');
    if (div) {
        div.removeEventListener('click', Module.clickToPlayListener);
        document.body.removeChild(div);
    }
    startGame();  // go go go!
  },

  startClickToPlay: function() {
    var base64 = base64Encode(FS.readFile(GDragonRubyIcon, {}));
    var div = document.createElement('div');
    div.id = 'clicktoplaydiv';
    // styling omitted

    p = document.createElement('p');
    p.innerHTML = 'Click or tap here to begin.';
    div.appendChild(p);

    document.body.appendChild(div);
    div.addEventListener('click', Module.clickToPlayListener);
    window.gtk.play = Module.clickToPlayListener;
  },
  preRun: function() {
    // this prevents the game from running. We'll remove the dependency when
    //  we have downloaded everything and the user has clicked-through to play.
    Module["addRunDependency"]("dragonruby_init");
    prepareFilesystem();   // will get data, async.
  },

  ...
}

```
