### ISSUE TITLE
Files larger than 2GB cannot be read (at least with workerfs)

### ISSUE THREAD

**Issue by mossroy** [emscripten-core/emscripten#15394]
Here is a test-case : https://mossroy.github.io/libzim_wasm/index-bigfile.html
It uses workerfs to access a file chosen by the user of the web page.
The C code tries to read bytes at increasing positions, and fails when the position exceeds 2 GB ("Invalid argument").

Please note that the file is never read entirely in memory : we only have to read some parts of it.

Source code is there : https://github.com/mossroy/libzim_wasm/blob/master/big_file_test.cpp
It has been compiled with emscripten 2.0.32 :

> em++ --bind -std=c++11 -O0 --pre-js prejs_file_api_testbigfile.js --post-js postjs_file_api_testbigfile.js big_file_test.cpp -lworkerfs.js -o bigfile.js

Reading very big files is a requirement for what we implement (offline reader, notably for wikipedia archives : https://www.kiwix.org)

NB : we opened #5250 a long time ago, which has been marked as fixed, but probably covers only a part of what is needed to read big files.

**Comment by nkbai** [comment]
@mossroy https://github.com/netpipe/emscripten-projects/tree/master/Loaders/Uploader  this is an example, it can deal with file larger than 2GB. but it reads all file data to the memory.

**Comment by mossroy** [comment]
Thanks @nkbai !
Unfortunately, reading all file content in memory is impossible for us.
Look at the side of our biggest files: https://download.kiwix.org/zim/wikipedia/?C=S;O=D
80+ GB will not fit in devices memory, and it would take much too long to transfer, too.

WorkerFS allows us to read only the bytes we need, at runtime, which is perfect for our use-case.
The "only" problem with WorkerFS is that it does not support files bigger than 2GB

**Comment by mossroy** [comment]
I've recompiled our test-case with latest emscripten (3.1.12) and ... the problem seems to be solved!
You can try by yourself (I updated the github pages): it's now possible to read bytes after 2GB with workerfs.

So I suppose it has been fixed in emscripten, somewhere between versions 2.0.32 and 3.1.12.

It's great news for us, as it was a major blocker since a long time.
Many thanks to whoever fixed that!
