### ISSUE TITLE
Query: Wasm EH with Emscripten SjLj support

### ISSUE THREAD

**Issue by sps-gold** [emscripten-core/emscripten#15404]
Can you please share, by when emscripten will start supporting setjmp/longjmp with Wasm exception handling.

PS:
My product has dependencies on 3rd party components like opencv. 
Loading side wasm built with wasm-eh using with 2.0.32 emsdk throws:
```
Aborted(Assertion failed: undefined symbol `longjmp`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
```

**Comment by aheejin** [comment]
Sorry for the delayed reply. Yeah I don't think we have a dylink + SjLj test cases yet. (#14976 includes some basic support for dynamic linking, but I don't think we have a test for it) Also the current support does not include using EH and SjLj together. I hope we can fix both problems by the end of Q4.

**Comment by sps-gold** [comment]
@aheejin I have created a [small reproducer](https://github.com/emscripten-core/emscripten/pull/15519). hope it helps.
