### ISSUE TITLE
Support for fast startup by restoring pre-initialized memory

### ISSUE THREAD

**Issue by kg** [emscripten-core/emscripten#15402]
For WASM applications it's theoretically feasible to generate a full heap offline and then do fast application startup by loading that data directly into memory at startup instead of running lots of init code. Is this something that emscripten could be made compatible with? Right now things like C++ constructors and the VFS seem to assume that an application is always being started fresh and there's no obvious way to adjust everything so that this could work.

**Comment by sbc100** [comment]
We have setting called `EVAL_CTORS` that can do some parts of this at compile time:

https://github.com/emscripten-core/emscripten/blob/bbc208cfdf0ced61f0cdaa73c096439c357340a5/src/settings.js#L1540-L1575

However, this settings I believe was disabled with under the upstream llvm backend and needs to be revived and re-enabled.

As for more advanced versions of snapshotting and I think best hope would be integration with something like https://github.com/bytecodealliance/wizer.

**Comment by kripken** [comment]
`EVAL_CTORS` basically does that, yes. The binaryen `wasm-ctor-eval` tool does the actual work.

It was disabled at some point due to integration with malloc/sbrk, https://github.com/emscripten-core/emscripten/issues/9527 Those are no longer an issue, so it could be revived if it's useful. And extending it to do work in `main` and not just in global ctors would be easy.

The reason I haven't focused on it myself is that the benefit usually comes with a tradeoff in larger size, and I wasn't aware of current use cases. I could try to find time though if it seems like it could be useful?

**Comment by kg** [comment]
If setting EVAL_CTORS will disable the emscripten logic that interferes, we may be able to do the rest ourselves. I'll let you know if we start testing it out and hit anything, we last attempted this mid-2020 and hit roadblocks then.

**Comment by sbc100** [comment]
I'm not sure what you mean by "disable the emscripten logic that interferes" but I don't think EVAL_CTORS effects the generated code at all.   All it does it take a wasm file an produce anther wasm file that does potentially less work at startup, and it has fairly limited powers... IIRC its mostly able to remove static constructors that do just set memory locations and not much else.

**Comment by kripken** [comment]
I opened https://github.com/emscripten-core/emscripten/pull/15403 to test if we can re-enable that option. I believe it should safe now (as @sbc100 noted in https://github.com/emscripten-core/emscripten/issues/9527#issuecomment-701138675, we don't dynamically allocate in JS, and sbrk is now 100% in wasm, etc.), and the one known failure does pass for me locally.

**Comment by kripken** [comment]
Heads up that I'll be looking into this soon. I've identified what I think are the main issues preventing this from working well now, and I intend to work on them in the coming weeks.

**Comment by kripken** [comment]
PR open: #16011
