### ISSUE TITLE
TypeError: undefined is not an object(evaluating 'Module["asm"]["B"]) in Decoder.js

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#15415]
i compile the C project in EmscriptenV2.0.30 with `-s SINGLE_FILE=1`，then i get only the Decoder.js，no Decoder.wasm ，and i run it in android/PC chrome ，it is all ok ，but in ios_chrome, there is an error `TypeError: undefined is not an object(evaluating 'Module["asm"]["B"]),TypeError: undefined is not an object(evaluating 'Module["asm"]["...."]),TypeError: undefined is not an object(evaluating 'Module["asm"]["K"])` ...

Even if i compile the C project in EmscriptenV2.0.30 without `-s SINGLE_FILE=1` , load the Decoder.js and Decoder.wasm , run it in android/PC chrome ，it is all ok ，but in ios_chrome, there is also an error.

Only i compile the C project in EmscriptenV1.37.22 without `-s SINGLE_FILE=1` , load the Decoder.js and Decoder.wasm , run it in ios_chrome, there is ok.

why ?

**Comment by yangfangfang1204** [comment]
and in mac safari ,the error is `failed to asynchronously prepare wasm:CompileError:WebAssembly.Module doesn't parse at byte4097:references are not enabled. Unhandled Promise Rejection:RuntimeError :abort(CompileError:WebAssembly.Module doesn't parse at byte 4097:references are not enabled ) at jsStackTrace`

**Comment by yangfangfang1204** [comment]
i solve the problem , my compile with -pthread or -flto -flto=full -flto=thin , compile without them ,it is ok in ios_safari

**Comment by dlliu114** [comment]
> and in mac safari ,the error is `failed to asynchronously prepare wasm:CompileError:WebAssembly.Module doesn't parse at byte4097:references are not enabled. Unhandled Promise Rejection:RuntimeError :abort(CompileError:WebAssembly.Module doesn't parse at byte 4097:references are not enabled ) at jsStackTrace`

Did you solve this problem? I have the same problem

**Comment by sbc100** [comment]
@dlliu114 can you perhaps open a new issue?  This issue relates to `Module['asm']` which doesn't exist anymore.
