### ISSUE TITLE
How does C++ call js Objects and  member methods on object

### ISSUE THREAD

**Issue by donghang1994** [emscripten-core/emscripten#15451]
![image](https://user-images.githubusercontent.com/91657327/140712393-651f7649-13ab-4315-a0ac-0bcae0c4a64d.png)

I want to pass the js object to C++ and call the object's member methods in c++.
I've seen official examples where you can pass global objects to c++, Is it okay if it's not global.

**Comment by sbc100** [comment]
Sure, IIUC you should be able to call methods on any JS `val` object.    The `val::global` method is just a way to access the global JS namespace but you can also receive `val`s in other ways such as via parameters or as returns values from `.call`.

To pass vals to C++ methods I think you would want to use embind: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html

**Comment by donghang1994** [comment]
void EM_PORT_API CallBack1(intptr_t hmem, emscripten::val object)
{
	emscripten::val globeWorkspace = emscripten::val::global("workspace");
	globeWorkspace.call<void>("callback");
}

This is my example, and 'workspace' is globe object, Can not be globe objects and pass directly to c++.

> Sure, IIUC you should be able to call methods on any JS `val` object. The `val::global` method is just a way to access the global JS namespace but you can also receive `val`s in other ways such as via parameters or as returns values from `.call`.
> 
> To pass vals to C++ methods I think you would want to use embind: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html

I tried using embind and it worked,Thank you very much!
