### ISSUE TITLE
Hiding exports from bc library

### ISSUE THREAD

**Issue by petermlyon** [emscripten-core/emscripten#15462]
Hi guys, thanks so much for everyone's work on emscripten, this is my first adventure into web assembly and you guys have made it a pretty smooth and fun experience!

I was wondering if someone could help me understand if it's possible to include `.bc` libraries into my emscripten project without exposing the methods of from the `.bc` library to javascript? Ideally I would also like to avoid bundling unused methods into my eventual WASM target.

I'm working on a c++ library, that wraps an existing `.bc` library from a third party.

At the moment my working build command looks like this:
```
em++ ./src/my-code.cpp \
./external-library.bc \
-I ./external-library-headers \
-s WASM=1 \
-s MODULARIZE=1 \
-s SINGLE_FILE=1 \
-s BINARYEN_ASYNC_COMPILATION=0 \
--no-entry \
-o output.wasm
```

This works great, although including the `.bc` library as `source` causes all it's methods to be exported to JS land.

Intuitively I thought that using -L to include the `.bc` library would yield the expected results.

However I get undefined errors for the library methods, and adding them to the `EXPORTED_FUNCTIONS` list doesn't appear to make any difference, in-fact the resulting errors are the same as if I were to remove the library and its `.h` files from the build command completely.

At this point I get the feeling that I'm misunderstanding the nature of `.bc` files, although I've struggled to find useful information about them (likely a lack of correct language on my behalf as I'm not totally familiar with this area).

Any hints will be greatly appreciated!

**Comment by sbc100** [comment]
You best bet would be to switch from a `.bc` files to library file (`.a`) created using emar. 

In general there should be no reason to use `.bc` files and your inputs should instead either be `.o` objects or `.a` archives.

To create an archive from `.o` files you would do something like: `emar rcs libfoo.a foo.o bar.o baz.o`

**Comment by sbc100** [comment]
I should note however that exporting of functions to JS is normally only done for functions listed in `EXPORTED_FUNCTIONS` or marked in the source code as `EMSCRIPTEN_KEEPALIVE`. 

Are the exports your are seeing here marked as `EMSCRIPTEN_KEEPALIVE` ?  If not they should not ever be exported, regardless of if you like them as `.bc` or `.o` or `.a`.

**Comment by petermlyon** [comment]
Hi sbc,

I've started looking at that route. Do you know if it's possible to use emar to generate a `.a` file from a `.bc` file? I've been looking into this but haven't come up with anything yet.

The library is proprietary and was provided to me in a `.bc`  file, the providers are responsive and I could certainly ask them for a `.a` file instead but there may be some reason on their end that they have provided it in `.bc`. I think this may be because they have provided some methods to support their library that must be exposed to JS (mostly related to getting data from JS->WASM memory).

My build command is exactly as above (no use of `EXPORTED_FUNCTIONS`), my assumption is that the methods were marked as `EMSCRIPTEN_KEEPALIVE` which is now 'baked in' to the `.bc`.

Before asking this question I've tried looking for an `EMSCRIPTEN_KEEPDEAD` or similar option, that could override any upstream `EMSCRIPTEN_KEEPALIVE` definitions, but I feel like this situation is fairly corner case (hence why I've struggled to find info on the proper inclusion of `.bc` files)

**Comment by petermlyon** [comment]
I was able to convert the `.bc` file to `.a` using `emar rcu external-library.a external-library.bc`, however on including it with `-L` I got the undefined errors again, and when including using `-l` I got the following error ```wasm-ld: error: unable to find library -lexternal-library.a```.

Upon including it as source (but from the `.a` file) everything works, but all methods are exported (as with the original `.bc` file).

I'll try requesting a raw `.a` file from the provider of the library

**Comment by sbc100** [comment]
I think requesting a `.a` from the vendor is the best solution.

You might also ask them if they are using `EMSCRIPTEN_KEEPALIVE` .. it would seem like a rather odd thing for them to do.   If they are not using `EMSCRIPTEN_KEEPALIVE` then something odd is going on and we should investigate further.

BTW if you are not specifying `EXPORTED_FUNCTIONS` or using `EMSCRIPTEN_KEEPALIVE` and you are building with `--no-entry` how do you expect to be able to use your program?   Without any of those then your program would be completely empty IIUC
