### ISSUE TITLE
emcmake -E broken in 2.0.32

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#15471]
2.0.31 (good):
```
$ emcmake cmake -E env CXXFLAGS="-pthread" LDFLAGS="-pthread" cmake src
configure: cmake -E env CXXFLAGS=-pthread LDFLAGS=-pthread cmake src -DCMAKE_TOOLCHAIN_FILE=/path/to/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/path/to/emsdk/node/14.15.5_64bit/bin/node
<...>
```

2.0.32 (bad):
```
$ emcmake cmake -E env CXXFLAGS="-pthread" LDFLAGS="-pthread" cmake src
configure: cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/path/to/env/emsdk/node/14.15.5_64bit/bin/node -DCMAKE_TOOLCHAIN_FILE=/path/to/env/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -E env CXXFLAGS=-pthread LDFLAGS=-pthread cmake src
CMake Error: Unknown argument -E
CMake Error: Run 'cmake --help' for all supported options.
```

**Comment by sbc100** [comment]
Hmm, it looks like the offending commit was #15265.   IIRC it turns out that commit was maybe not necessary and so we could revert it?  Is that right @ngzhian ?

Having said that does look like a rather odd way to run cmake.. you are running emcmake in order to run cmake's env in order to run cmake.   What exactly are you trying to do here?    Why not run env as the outermost command?  Or just set the environment variables directly?  e.g.

```env CXXFLAGS=-pthread LDFLAGS=-pthread emcmake cmake src```

or just

```CXXFLAGS=-pthread LDFLAGS=-pthread emcmake cmake src```

**Comment by sbc100** [comment]
(it just seems odd that there is a double invocation of cmake here.. but maybe you have good reason to do that?)

**Comment by ngzhian** [comment]
Didn't think of nested cmake invocations here, but we can revert that change since it's not super useful outside of some niche cases.

**Comment by emaxx-google** [comment]
Thanks for the quick reply. Yeah, this was a small repro; I guess any nested command is broken in this way.

**Comment by sbc100** [comment]
Do you need to run the `-E` commands via `emcmake`?  Can't you just run `cmake -E` directly?  (I don't think emcmake needs to be used except when generating a project file).

**Comment by sbc100** [comment]
We can revert that change of course.  But perhaps we should error when emcmake is passed `-E` command to avoid confusion?  (assuming it is not meaningful/useful to do so)

**Comment by emaxx-google** [comment]
> We can revert that change of course. But perhaps we should error when emcmake is passed `-E` command to avoid confusion? (assuming it is not meaningful/useful to do so)

I'll check whether I can avoid nested commands. I vaguely remember I had some issues with some environment flags not propagated through emcmake, but I haven't tried it again since a while.
