### ISSUE TITLE
[Asyncify] RuntimeError: unreachable

### ISSUE THREAD

**Issue by andersson09** [emscripten-core/emscripten#15488]
Hey,

I compiled a very simple program using `emcc test.c -o test.async.wasm -s ASYNCIFY --profiling` and the asyncify-wasm  js package. I'm getting the following errors in the browser:

```
test.async.wasm:0x1ae8 Uncaught (in promise) RuntimeError: unreachable
    at __stdio_write (test.async.wasm:0x1ae8)
    at __fwritex (test.async.wasm:0x2f36)
    at out (test.async.wasm:0x637c)
    at printf_core (test.async.wasm:0x470e)
    at __vfprintf_internal (test.async.wasm:0x3dfa)
    at vfprintf (test.async.wasm:0x6db6)
    at printf (test.async.wasm:0x9e4a)
    at main (test.async.wasm:0x55f)
    at main.1 (test.async.wasm:0x16e1)
    at __main_void (test.async.wasm:0x15a6)
```

**test.c:**

```
  #include <stdio.h>
  #include <stdlib.h>
  
  int add(int x, int y) {
    return x + y;
  }
  
  int main( int argc, char *argv[] )  
  {
      printf("hello, world!\n");
  
      printf("Arg count: %d\n", argc);
      printf("Arg 0: %s\n", argv[0]);
      printf("Arg 1: %s\n", argv[1]);
      printf("Arg 2: %s\n", argv[2]);
  
      char *p;
      long a = strtol(argv[1], &p, 10);
      long b = strtol(argv[2], &p, 10);;
  
      int numA = a;
      int numB = b;
  
      int result = add(numA,numB);
      printf("Result is %d\n", result);
  }
```

The non async version works fine.

I'm not sure if there's some modifications I'm missing to the test.c or if it should really be as simple as adding -s ASYNCIFY when compiling?

Thanks!

**Comment by kripken** [comment]
It should be as simple as `-s ASYNCIFY`, yes.

I'm not familiar with the `asyncify-wasm js` package you mention. The problem might be there (maybe it doesn't support all the imports?). Testing here with `./emcc a.cpp -s ASYNCIFY --profiling` I get this when I run `node a.out.js`:
```
hello, world!
Arg count: 1
Arg 0: /home/azakai/Dev/emscripten/a.out.js
Arg 1: (null)
Arg 2: (null)
Result is 0
```

**Comment by andersson09** [comment]
Did you try standalone on a wasi runtime?

**Comment by kripken** [comment]
Ah, I didn't before, but I did now and it seems to work too:
```sh
$ emcc a.cpp -s ASYNCIFY --profiling -o a.wasm
$ ~/Downloads/wasmtime-v0.18.0-x86_64-linux/wasmtime a.wasm
hello, world!
Arg count: 1
Arg 0: a.wasm
Arg 1: (null)
Arg 2: (null)
Result is 0

**Comment by andersson09** [comment]
Hmm must be something wrong with the js library or that I'm using it wrong since in the docs it states I need post process the non async wasm file using wasm-opt (https://github.com/GoogleChromeLabs/asyncify#readme). I just thought running it through emscripten with -s asyncify would achieve the same result.

**Comment by kripken** [comment]
cc @RReverser for insights about that library.

**Comment by RReverser** [comment]
Are you trying to use Wasm produced by Emscripten with that standalone 3rd-party library?

If so, that likely won't work, Emscripten relies on its own JS in quite a few places.

**Comment by andersson09** [comment]
Yeah but without the extra js. I thought compiling with emscripten standalone produced a wasi module since it works fine without asyncify. Are you saying that adding -s ASYNCIFY changes it so it depends on its own js? But then @kripken got the same emscripten produced wasm module working using wasmtime in his example above.

**Comment by RReverser** [comment]
> But then @kripken got the same emscripten produced wasm module working using wasmtime in his example above.

Because the resulting binary doesn't use any async APIs, so it works fine without Asyncify runtime. In particular, WASI support works synchronously in wasmtime (or in any other standalone WASI runtime).

**Comment by RReverser** [comment]
As for `unreachable` error, it's not particularly helpful but that's a standard Wasm trap, and with Asyncify in particular usually happens due to Asyncify's stack exhaustion. If you optimize the binary, that might help a bit.

**Comment by andersson09** [comment]
> > But then @kripken got the same emscripten produced wasm module working using wasmtime in his example above.
> 
> It's because the code and the resulting binary doesn't use any async APIs, so it works fine without Asyncify runtime. In particular, WASI support works synchronously in wasmtime (or in any other standalone WASI runtime).

You're right. I just tested the async wasm and removed asyncify and the async bindings and it worked in the js runtime. 

So what should be the steps in order to get async bindings working with the async-wasm package, similar to the wasi-fs-access example? I'm a bit lost here.

**Comment by RReverser** [comment]
The steps are outlined in the README of the package: https://github.com/GoogleChromeLabs/asyncify#webassembly-side

That is, you need to compile your module with optimizations, and then use Wasm-opt as shown, also with optimizations, and with flags like shown to enable Asyncify for specified imports.

**Comment by RReverser** [comment]
Alternatively, and likely easier in this case, you can still use Emscripten, but mark those same WASI imports via `-s ASYNCIFY_IMPORTS`

**Comment by andersson09** [comment]
Got it working! Thanks, this can be closed :)
