### ISSUE TITLE
[Memory64] wasi_snapshot_preview1::fd_write signature

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#15508]
Hi, Apologies if its premature to ask about memory64 support I see a lot of PRs so if this is WIP, then feel free to close and I'll check the release notes going forward.

emcc 2,0.34

If you compile with `-s MEMORY64=1 -o 1.wasm`  which I think is enough to enable `STANDALONE_WASM` then try to run in wasmtime with
`wasmtim --wasm-features memory64 1.wasm` 
you get a complaint about signatures:
```
C:\github\wasm64>wasmtime --wasm-features memory64 1.wasm 
Error: failed to run main module `1.wasm`

Caused by:
    0: failed to instantiate "1.wasm"
    1: incompatible import type for `wasi_snapshot_preview1::fd_write`
    2: function types incompatible: expected func of type `(i32, i64, i64, i64) -> (i32)`, found func of type `(i32, i32, i32, i32) -> (i32)`

```

**Comment by kripken** [comment]
I think it might be too early to expect this to work on wasmtime? cc @sunfishcode 

On the emscripten side I think things are ready for `fd_write` with memory64,  @aardappel implemented that.

**Comment by yowl** [comment]
Thanks, I just got the option wrong, it should be `wasmtime --wasm-features=memory64 1.wasm` .  Which fails still but not on the signatures
```
C:\github\wasm64>wasmtime --wasm-features=memory64 1.wasm 
Error: failed to run main module `1.wasm`

Caused by:
    0: failed to instantiate "1.wasm"
    1: unknown import: `env::emscripten_memcpy_big` has not been defined
```

**Comment by yowl** [comment]
I'll close this, the original title was just user error.
