### ISSUE TITLE
After migrating to official docker 1.39 - Module["asm"] is undefined

### ISSUE THREAD

**Issue by wclr** [emscripten-core/emscripten#15507]
To build my (quite old) project I've been using docker `apiaryio/emcc:1.38.11` version of emcc:

`emcc -s EXTRA_EXPORTED_RUNTIME_METHODS=.. -s EXPORTED_FUNCTIONS=.. -s WASM=0 -Oz --minify 0 -o ...`

And it works fine for me.

Decided to upgrade the version of emcc and so I tried the latest 2.x and the first  published 1.39.0, and with any of them when calling the exported function I get the error: 

`Cannot read property 'w' of undefined` or something like that that is related, it happens that `Module["asm"]` is undefined (inside such code:`_fn = Module["_fn"] = Module["asm"]["w"]`). 

Any advice how properly to upgrade?

**Comment by sbc100** [comment]
It sounds like maybe you are trying to call a function on the module before it is ready.     Have you tried building a debug build or using `-s ASSERTIONS`.  

See https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions for information on how to know when the module is ready to be called.

Also, do you need `-s WASM=0`.. there are only a very few places where that should be needed these day so hopefully you can remove it.

**Comment by wclr** [comment]
Right, need to wait for initialization (`onRuntimeInitialized`). Thanks!
