### ISSUE TITLE
Incorrect result for check_type_size when compiling with pthreads enabled

### ISSUE THREAD

**Issue by shanumantesc** [emscripten-core/emscripten#15522]
- When compiling with pthread enabled (via `-pthread` flag), the `check_type_size` CMAKE function returns incorrect results. I am appending `-pthread` to `CMAKE_C_FLAGS_INIT` and `CMAKE_CXX_FLAGS_INIT`
- Based on https://github.com/emscripten-core/emscripten/pull/3447/files , `check_type_size` relies on the return value of executing a function.
- However, when pthreads is enabled, this function fails to execute. Here is a sample output when trying to build a library which uses `check_type_size` with pthreads enabled
```
run_output = requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag
(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)
/home/my_library/build/CMakeFiles/CMakeTmp/cmTC_51c08.js:160
      throw ex;
      ^

Error: bad memory
    at Object.<anonymous> (/home/my_library/build/CMakeFiles/CMakeTmp/cmTC_51c08.js:1383:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
It looks like we try to run some code in a node environment, but the experimental flags are not provided. The output in this case is always `7` and so `check_type_size` returns 7 for all types.
This same library compiles fine if we do not provide `-pthread` flag.

**Comment by sbc100** [comment]
Ah, we should probably enable `--experimental-wasm-threads --experimental-wasm-bulk-memory` when running cmake/autoconf tests under node.

**Comment by shanumantesc** [comment]
@sbc100 can you point me to what would be the right place to add these flags?

**Comment by sbc100** [comment]
For `emcmake` it would probably in `emcmake.py` around line 38 where `CMAKE_CROSSCOMPILING_EMULATOR` is added.

For autoconf it would probably in `make_js_executable` in emcc.py.
