### ISSUE TITLE
What's the difference between setValue and writeArrayToMemory ?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#15520]
1、the setValue demo : 
` var pBmpSize = Module._malloc(4);
 Module.setValue(pBmpSize, 255, "i32");
res = Module._InputData(pBmpData, pBmpSize); `
2、the writeArrayToMemory demo : 
`var pBmpSize= Module._malloc(4);
let inputDataSize = new Uint8Array(255);
Module.writeArrayToMemory(inputDataSize, pBmpSize);
res = Module._InputData( pBmpSize); `

so What's the difference On compiler principle between setValue and writeArrayToMemory ? and which one is more high performance ?

**Comment by kripken** [comment]
setValue writes a single value. writeArray writes a sequence of values.

For setValue, the high-performance way to do this is to write to memory directly, like `HEAP32[addr >> 2] = value`. That requires handling the shifting yourself, though - setValue is basically a helper that makes it simpler.

writeArray will just call `HEAP8.set()`, which for a large-enough array will be fastest.

**Comment by yangfangfang1204** [comment]
ok, thanks
