### ISSUE TITLE
cannot get correct function from wasmTable when invoke `wgpuQueueOnSubmittedWorkDone`

### ISSUE THREAD

**Issue by hana-alice** [emscripten-core/emscripten#15521]
Hi, guys, 

I'm working on webgpu with emscripten, and when I call wgpuQueueOnSubmittedWorkDone:

![image](https://user-images.githubusercontent.com/18626925/141710544-d642d4a7-c2d8-473a-aa2d-259ef567f199.png)

I can't get the correct id of `callback` and `userdata`, with `return queue["onSubmittedWorkDone"]();` removed:

> Uncaught (in promise) TypeError: wasmTable.get(...) is not a function

Kai's commit here solved this issue: https://github.com/emscripten-core/emscripten/pull/15515
I apply this change and still got: 

![image](https://user-images.githubusercontent.com/18626925/141712142-3a94884f-c548-4c6f-8a86-62edec65a8db.png)

somehow I noticed in library_webgpu.js:

```
  wgpuQueueOnSubmittedWorkDone: function(queueId, callback, userdata) {
    var queue = WebGPU.mgrQueue.get(queueId);
    return queue["onSubmittedWorkDone"]();
    queue.onSubmittedWorkDone().then(function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Success }}}, userdata);
    }, function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Error }}}, userdata);
    });
  },
```

there's a QueueWorkDoneStatus as one of params in callback, so I add a placeholder in wgpuQueueOnSubmittedWorkDone, now it's:

```
  wgpuQueueOnSubmittedWorkDone: function(queueId, signalValue, placeholder,callback, userdata) {
    var queue = WebGPU.mgrQueue.get(queueId);
    queue.onSubmittedWorkDone().then(function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Success }}}, userdata);
    }, function() {
      {{{ makeDynCall('vii', 'callback') }}}({{{ gpu.QueueWorkDoneStatus.Error }}}, userdata);
    });
  },
```

it works.

------

test on emsdk 2.0.26.

**Comment by kripken** [comment]
cc @kainino0x
