### ISSUE TITLE
Better C struct/constant forwarding to JS

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#1554]
My current thoughts are:
1. Have a json file with a list of the structs (with field names for each) and constants (#defines) we need in our js code
2. Have a script that autogenerates a single C file (for everything) that prints out: for each struct, its size and the offset of the fields we named in the json file, and for each constant its value. The script parses the output and generates another json file.
3. We load that json file in the js compiler, and utilize it. So we can remove all generateStructInfo, and replace all those with {{{ cInfo.structname.fieldname }}} or something similar. {{{ cDefine .. }}} can remain of course.
4. The script output is stored in the cache, like libs and the relooper, so it is autogenerated when the version changes etc. We run it when we see it is missing, etc.

**Comment by nazar-pc** [comment]
Looks like this was already implemented
