### ISSUE TITLE
Rust´s struct fails in Blazor WASM

### ISSUE THREAD

**Issue by harveytriana** [emscripten-core/emscripten#15547]
One of the important novelties of Blazor in .NET6 is the ability to assemble native libraries through emscripten with your own WASM. I have tested the feature, beyond simple examples, with C, C++, and now with Rust. Works very well. In the case of Rust, we create a static library with build ```--target wasm32-unknown-emscripten```, which generates the ```lib[name].a``` file, which is the one we reference in Blazor. I have run tests with Rust math functions, Strings, and JSON transfer. This works perfectly in Console and Blazor. Initially check the validity of the code with the dynamic Rust library and a C# Console, before compiling to emscripten file and running in Blazor. The only flat that has been featured is by using a Rust structure; which works perfectly on the Console.

Show a step-by-step example to illustrate the issue.

Rust library:
```rust
// -------------------------------------------------------
// Simple structures by sample
// -------------------------------------------------------
#[repr(C)]
pub struct XY {
    pub x: i32,
    pub y: i32,
}
#[no_mangle]
pub extern "C" fn get_xy() -> XY {
    XY { x: 15, y: 23 }
}
#[no_mangle]
pub extern "C" fn sum_xy(p: XY) -> i32 {
    p.x + p.y
}
```

The cargo.toml is:
```
[package]
name = "rstlib"
version = "0.1.0"
authors = ["Harvey Triana <harveytriana@gmail.com>"]

[lib]
name="rstlib"

# WebAssembly for Emscripten (.a)
# -----------------------------------------------------------------
# Require: staticlib.
# compile: cargo build --target wasm32-unknown-emscripten --release
# crate-type = ["staticlib"]

# Console (.dll)
# -----------------------------------------------------------------
# Require: dylib 
# compile: cargo build --release
crate-type = ["dylib"]
```

*In the comments of the instruction to compile for dynamic or static library, which is required by WASM*

A simple console test in C# 10, net6, code is:

```csharp
using System.Runtime.InteropServices;

Console.WriteLine("Calling Rust Experiments\n");
RustTestStruct.Run();
Console.WriteLine("\nReady");

class RustTestStruct
{
    record struct XY(int x, int y); // see note (*)

    const string RUSTLIB = @"..\..\..\..\rstlib\target\release\rstlib.dll";

    [DllImport(RUSTLIB)] static extern XY get_xy();
    [DllImport(RUSTLIB)] static extern int sum_xy(XY p);

    public static void Run()
    {
        Console.WriteLine("STRUCT SAMPLE");
        // call rust functions
        var xy = get_xy();
        var sum = sum_xy(xy);

        Console.WriteLine("XY  : {0}", xy);
        Console.WriteLine("Sum : {0}", sum);
    }
}

// * Note.Is the same:
// [StructLayout(LayoutKind.Sequential)]
// struct XY { public int x; public int y; }

```

Running this C# code gives the expected result,
```text
Calling Rust Experiments

STRUCT SAMPLE
XY  : XY { x = 15, y = 23 }
Sum : 38
```
Now I compile for  emscripten  and create the reference in a Blazor application. The page Index has the following code

```csharp
@page "/"
@using System.Runtime.InteropServices

<PageTitle>Calling Rust Functions - Struct</PageTitle>

<h3>Test for Rust's struct</h3>
<pre>@echo</pre>
<hr />
<p>Look at the console output in browser development tools for details</p>

@code {
    const string RUSTLIB = "librstlib";

    record struct XY(int x, int y);

    [DllImport(RUSTLIB)] static extern XY get_xy();

    string echo = string.Empty;

    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(500);

        try {
            var xy = get_xy();
            echo = $"XY : {xy}";
        }
        catch (Exception exception) {// not fired
            // Does not pass this test
            // Chrome: Uncaught RuntimeError: null function or function signature mismatch
            // Firefox: Uncaught RuntimeError: indirect call signature mismatch
            echo = $"Exception: {exception.Message}";
        }
    }
}
```

When executing the application, an exception is generated. See the image.

![wa_rust_struct_little](https://user-images.githubusercontent.com/5245381/142095831-8db871b2-9325-4a9b-b876-f8ffef09abd1.png)

If it runs fine in Console and other functions have run fine in Blazor, I think there may be a bug in the assembly created in emscripten, only as regards Rust's struct.

**Comment by harveytriana** [comment]
Maybe I should have added that it is Blazor .net 6, the reference to the Rust library is the following:

```xml
<ItemGroup>
	<NativeFileReference Include="..\..\rstlib\target\wasm32-unknown-emscripten\release\librstlib.a" />
</ItemGroup>
```

The three projects are in the same folder. Are: BlazorRustExperiments, ConsoleApp, and rstlib. Github: https://github.com/harveytriana/BRE

**Comment by kripken** [comment]
Is this taking Rust and linking it with C? There are some ABI issues there, cc @tlively

**Comment by tlively** [comment]
There is currently a bug with Rust's implementation of the C ABI on WebAssembly. As a result, Rust and Clang (or Emscripten) produce different function signatures for functions that take nontrivial structs by value. The solution for now is to not pass structs by value on the boundary between Rust and C++ (or other languages). See discussion on the Rust side of this here: https://github.com/rustwasm/team/issues/291.

**Comment by harveytriana** [comment]
I found that the issue only happens when trying to get a struct from Rust, not when passing it as a parameter. The example:

![image](https://user-images.githubusercontent.com/5245381/142357852-cb3e9478-f031-4e0b-a012-c7ad7183396a.png)

The code was not modified, only the order of calls. I think I could find a way to get native structs from Rust functions with some strategy.

**Comment by tlively** [comment]
Looking a bit closer, the problem you're seeing is probably not due to the Rust ABI bug since you're compiling with `--target wasm32-unknown-emscripten`, which uses the correct ABI. It looks like maybe Blazor is just using the wrong signature for this function? It would be good to get someone more familiar with Blazor and how it interacts with Emscripten to take a look at this.

**Comment by harveytriana** [comment]
Emscripten does not have any BUG in this case. The point is that Emscripten imposes working with pointers in this case. The work around is as follows:

```rust
#[repr(C)]
pub struct XY {
    pub x: i32,
    pub y: i32,
}
// returns explicit struct. Not use in Emscripten's wasm : (
#[no_mangle]
pub extern "C" fn get_xy() -> XY {
    XY { x: 15, y: 23 }
}

// return a static struct in a pointer
static mut _P: XY = XY { x: 0, y: 0 };

// Good for Emscripten : )
#[no_mangle]
pub extern "C" fn get_xy_ptr() -> *mut XY {
    unsafe {
        _P.x = 15;
        _P.y = 23;
        &mut _P
    }
}
```

The code in the Blazor page is modified to use the pointer and resolve the value of the structure with Marshal.PtrToStructure

```csharp
@code {
    const string RUSTLIB = "librstlib";

    record struct XY(int x, int y);

    [DllImport(RUSTLIB)] static extern IntPtr get_xy_ptr();
    [DllImport(RUSTLIB)] static extern int sum_xy(XY p);

    string echo = string.Empty;

    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(500);

        var xy = new XY(15, 23);

        var sum = sum_xy(xy);

        Echo($"Calling a Rust function with struct as parameter, sum_xy({xy.x}, {xy.y}) = {sum}");

        // Pointers for emscripten. The function has to return a static result.
        IntPtr pointer = get_xy_ptr();
        XY z = Marshal.PtrToStructure<XY>(pointer);

        Echo("\nGetting a structure from Rust Library");
        Echo("1. Get Pointer");
        Echo("2. Marshal.PtrToStructure<T>(pointer)");
        Echo(string.Format("z record: {0}", z));
        Echo(string.Format("z.x: {0}", z.x));
        Echo(string.Format("z.y: {0}", z.y));
    }

    void Echo(string? message = null)
    {
        if (message is null)
            echo = string.Empty;
        else {
            echo += $"{message}\n";
            StateHasChanged();
        }
    }
}
```

The result is now correct:

![wa_rust_struct_ready](https://user-images.githubusercontent.com/5245381/142502780-cc65d21a-a882-4998-ba2a-ed73be7721c1.png)

> Precautions must be taken since in the Rust library we leave a static. However, from WASM the consumer is one and it would not be a major problem. You can add things to improve. The matter is resolved.

I updated the Git repository if anyone is interested in seeing the topic exposed here.
