### ISSUE TITLE
How to prevent  '.data / .wasm' from downloading if a dependency is not supported

### ISSUE THREAD

**Issue by macadev** [emscripten-core/emscripten#15541]
Hi Emscriptem team, thanks for the amazing work on this project. I'll keep my question short:

I'm working on a project that uses WebGL 2 and runs a C++ application that I compile using emscripten. My '.data' packaged payload that has textures / 3D models is around 10 Mb in size (compressed). I want the following behaviour:

- User hits URL to load website
- Browser receives HTML and JS
- JS checks whether the browser supports WebGL 2. If it is not supported, then JS does not send the requests to GET the '.data' and '.wasm' files which consume bandwidth unnecessarily since the application can't run.
 
I tried to accomplish the above using a preInit function on the Module object, but I haven't been able to figure out how to prevent the asset downloading from occurring. I could do hacky things like break xhr, but before resorting to something like that I want to know if there's a recognized way to do what I'm after.

```
preInit: [
      function () {
         if (/* webgl 2 not suported */) {
           // show popup, don't download assets.
         }
      },
    ],
```

Thanks for your time!
Daniel

**Comment by sbc100** [comment]
Would it not make sense to put you checks in a separate JS file and avoid even downloading and parsing the emscripten-generated JS file at all if they fail?

**Comment by macadev** [comment]
Hi @sbc100, I did consider that option, but that would mean making 1 extra round-trip to the server. But that does sound like a cleaner solution than my proposed idea of breaking xhr. Thanks for the suggestion.
