### ISSUE TITLE
Embind method caller registration issue when using pthreads

### ISSUE THREAD

**Issue by shanumantesc** [emscripten-core/emscripten#15557]
With pthreads enabled, embind fails when calling a function from C++ code when using the explicit `call` method (`ReturnValue call(const char* name, Args&&... args) const;`), if that same function has already been called by another thread. The issue manifests as something like
```
Uncaught TypeError: caller is not a function
    at __emval_call_void_method (MyLibrary.js:6910)
```

Pseudo code:
```
emscripten::val obj = constructObject();
emscripten::val argument = constructArgument();
obj.call<void>("mymethod", argument); // succeeds the first time we call from any thread, but after that point it must be called from the same thread
```

This seems to be caused by https://github.com/emscripten-core/emscripten/blob/e0d0489fcdaada8da6408b6d275fa4a59a6eb65a/system/include/emscripten/val.h#L129 where `mc` is declared static and so will be initialized in just one thread and rest of the threads will use that value without calling `init_method_caller` to register the function with JS. Instead, the correct behavior seems to be to call `init_method_caller` for each function signature for each thread. Changing the code to 
```
thread_local static EM_METHOD_CALLER mc = init_method_caller();
```
seems to fix the issue (and also feels like the right fix since we want to initialize each signature once per each thread).

Strangely, this issue doesn't happen if I use `operator()(Args&&... args) const` instead whereas I was expecting them to use the same underlying mechanism. I didn't yet have the time to debug this, but would be happy to know what is happening here.
Pseudo code:
```
emscripten::val obj = constructObject();
emscripten::val argument = constructArgument();
obj["mymethod"](argument); // succeeds on both threads
```

**Comment by sbc100** [comment]
Sounds like your fix is correct.  Can you upload a PR?  (Also apparently `thread_local` implies `static` so you don't need both).

**Comment by shanumantesc** [comment]
On taking a deeper look, while `thread_local` fixes the issue mentioned, it can lead to a different issue:
```
// DO NOT call this more than once per signature. It will
// leak generated function objects!
EM_METHOD_CALLER _emval_get_method_caller(
    unsigned argCount, // including return value
    const TYPEID argTypes[]);
```

If some worker thread is re-used as a new pthread, then we would call `_emval_get_method_caller` more than once per signature for that worker which will leak the function object (which we are being warned about). To overcome this, I also need to patch `_emval_get_method_caller` (https://github.com/emscripten-core/emscripten/blob/6cb821b7e35c39155ed4bce7fdb940c7f622ca86/src/embind/emval.js#L388) where we check if a given signature has already been registered and immediately return that signature's id instead of creating a new function object. And to handle the `#if DYNAMIC_EXECUTION == 0` section (which I'm not very familiar with), it looks like we should always try to calculate a unique signature first and check if has already been registered.

Pseudo code would be:
```
var registeredMethods = {};
  function __emval_get_method_caller(argCount, argTypes) {
      var types = __emval_lookupTypes(argCount, argTypes);
      var retType = types[0];
      var signatureName = retType.name + "_$" + types.slice(1).map(function (t) { return t.name; }).join("_") + "$";
      var returnId = registeredMethods[signatureName];
      if (returnId !== undefined) {
        return returnId;
      }

#if DYNAMIC_EXECUTION
...
#else
...
#endif
      returnId = __emval_addMethodCaller(invokerFunction);
      registeredMethods[signatureName] = returnId;
      return returnId;
```

Do you think this is a viable approach @sbc100 ?

**Comment by sbc100** [comment]
Sure that sounds reasonable.    Alternativly we could re-initialize embind from scratch on each thread.    Currently embind initialization is a special case that is don't in JS on startup of a new worker, but no on startup of each thread.   This might save a little time when workers are re-used but as you are discovering here it also adds complexity.

**Comment by shanumantesc** [comment]
For our use-case, we bind only a handful of functions/classes, and full re-initialization wouldn't hurt. However, I'm not sure if that is generally applicable. Given that we already have this optimization in place, would be be okay with introducing a potential regression?

Also, full embind reinitialization would require that we need to wipe out all the global variables that embind maintains like `emval_free_list`, `emval_symbols` (or maybe just a subset of these, need to look deeper to figure out which ones) and I don't see a way to do this cleanly in the current design.

Overall, I am leaning towards just handling re-initialization of already registered methods -- what do you think?

**Comment by sbc100** [comment]
Sure, sounds good to me.

**Comment by shanumantesc** [comment]
On a separate note, there is another issue that `EMSCRIPTEN_BINDINGS` block no longer works with pthreads because we rely on static initialization to invoke the registration methods, and this happens just once on the main thread. So it looks like we should also change that macro to use thread_local instead of static.

However, that again leads to the issue with re-use of a worker across multiple threads -- when we try to re-register a class on a new thread/old worker, we will fail at https://github.com/emscripten-core/emscripten/blob/6cb821b7e35c39155ed4bce7fdb940c7f622ca86/src/embind/embind.js#L132
For this case, the only workaround I can think of is to change that error to a warning and assume that the user is trying to register the same signatures. 
A full reinitialization might help in this case -- but we again need to consider the same things as in the discussion above, and also wipe out embind-registered module properties along with embind global state. Maybe a much larger refactor for embind is necessary to make it work well with pthreads.

For now, my workaround is to not use `EMSCRIPTEN_BINDINGS` block -- instead I first check if the name being registered exists as a Module property and use that to decide whether I need to register my classes.
