### ISSUE TITLE
Can't use OpenGL instancing methods with WebGL1

### ISSUE THREAD

**Issue by arielm** [emscripten-core/emscripten#15565]
I'm using the latest version of emscripten and when I compile my C++ code, I get the following errors:
```
error: use of undeclared identifier 'glDrawArraysInstanced'
error: use of undeclared identifier 'glDrawArraysInstancedARB'
error: use of undeclared identifier 'glDrawArraysInstancedANGLE'
```

Notes:
- I properly include `GLES2/gl2ext.h`
- `library_webgl.js` is supposed to handle calls like `glDrawArraysInstanced` or `glDrawArraysInstancedARB` or `glDrawArraysInstancedANGLE`
- The code compiles and links fine on macOS (using OpenGL 2.1 and `glDrawArraysInstancedARB`)

Am I missing the obvious?

**Comment by kripken** [comment]
Yes, if it's in `library_webgl.js` then it should work, so I'm not sure what's going wrong in your case. `grep -r glDrawArraysInstanced tests/*` shows we have tests for `glDrawArraysInstanced`, so comparing to those might help figure things out.

**Comment by kripken** [comment]
Building with `-sGL_ASSERTIONS` may also help, I see there is a check in the JS for that function, `Must have ANGLE_instanced_arrays extension or WebGL 2 to use WebGL instancing` - perhaps that is the issue actually, if you have not  done either of those two things?

**Comment by arielm** [comment]
Thanks Alon.

I found the test: `webgl_draw_base_vertex_base_instance_test.c`, but it's WebGL2 and it's using `glDrawArraysInstancedBaseInstanceWEBGL` which is defined in `webgl2_ext.h` and `library_webgl2.js`.

So currently, it's not really useful because I need to use `glDrawArraysInstanced` with WebGL1 (which is possible, in theory...)

**Comment by kripken** [comment]
I think it is possible in WebGL1, but you do need that `ANGLE_instanced_arrays` extension? Compatibility seems pretty broad: https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays

**Comment by arielm** [comment]
What puzzles me right now is why my C++ code fails at compilation time. If I understand correctly: it should compile and link and then at run-time I should allow the ANGLE_instanced_arrays extension.

Same with GL_ASSERTIONS: I believe it's a run-time check, so it's not helpful in my case. Right?

**Comment by kripken** [comment]
Yes, I'm not sure why it would fail at compile time. If comparing against the test suite examples isn't enough, maybe try to provide a testcase here that shows the problem.

**Comment by arielm** [comment]
I will definitely work on a test for WebGL1. But before that...

I tested the WebGL2 test and it fails on my machine (intel macOS with Big Sur):

```
emcc tests/webgl_draw_base_vertex_base_instance_test.c -o test.html
error: undefined symbol: emscripten_webgl_enable_WEBGL_draw_instanced_base_vertex_base_instance (referenced by top-level compiled C/C++ code)
```

**Comment by arielm** [comment]
I created a minimal [test](https://gist.github.com/arielm/bcd74cc210c18ccae76c8c17eb597623).

It fails at compilation time with:
```
error: implicit declaration of function 'glDrawArraysInstanced' is invalid in C99
error: implicit declaration of function 'glDrawArraysInstancedARB' is invalid in C99
error: implicit declaration of function 'glDrawArraysInstancedANGLE' is invalid in C99
```

Would appreciate if others could test it as well.
