### ISSUE TITLE
emscripten_sleep in side module corrupts stack

### ISSUE THREAD

**Issue by chkuendig** [emscripten-core/emscripten#15594]
I'm not sure this is the same issue as #13049, but I'm encountering a ` RuntimeError: unreachable` for any calls executed  after a call to `emscripten_sleep` in a side module.

I was able to reproduce this issue in tot as well as the few recently released versions I tested. From what I can tell this never worked so far. 

### Minimal test case:

**main_module.cpp**
 ```cpp
#include <iostream>
#include <dlfcn.h>

typedef int (*func_t)();

int main(int argc, char **argv)
{
    printf("loading side module\n");
    void *_dlHandle = dlopen("side_module.wasm", RTLD_NOW | RTLD_LOCAL);
    printf("get function\n");
    func_t my_func = (func_t)dlsym(_dlHandle, "side_module_run");
    printf("Plugin returns %d\n", my_func());
    return 0;
}
```

**side_module.cpp**
 ```cpp
#include <iostream>
#include <emscripten/emscripten.h>

extern "C"
{
	int side_module_run()
	{
		printf("Side module loaded. Sleeping now....\n");
		emscripten_sleep(1000);
		printf("Sleep done.\n");
		return 2;
	}
}
```

Built with:
```bash
em++ -O2 -g3 -s ASYNCIFY -s MAIN_MODULE=1 -o main_module.html main_module.cpp
em++ -O2 -g3 -s ASYNCIFY -s SIDE_MODULE=1 -o side_module.wasm side_module.cpp
```

Results in an unreachable exception with the following  stacktrace. It seems that it's not rewinding into the side module ("Sleep done" is never printed) but jumps to the next line (main_module.cpp:13) where it then encounters the exception when trying to printf.
<img width="894" alt="image" src="https://user-images.githubusercontent.com/748698/143036621-b07561ec-ee7e-48c8-8bdd-351299bc1811.png">

It's enough to comment out the `emscripten_sleep` part to get the code to run successfully.

**Comment by kripken** [comment]
I think this is not supported yet. Separate modules would need to share the asyncify state, but atm the Asyncify transform adds a different wasm global for the state to each of them, and nothing keeps them in sync.

One option might be to write a C file that defines those globals, and use that. The Asyncify pass would need to be able to find those globals, though, and I'm not sure how that would work.

Another option might be for the Asyncify pass to have an option that imports or exports the new globals that it adds. Then main modules would be build with exporting, and side modules with importing, say.

**Comment by chkuendig** [comment]
Do you mean any type of unwinding into a side module is not supported yet, i.e. this would also explain #13049? I'm trying to look for workarounds here (other than statically linking or rewriting everything into a proper main loop).

**Comment by kripken** [comment]
Yes, it could be the same there. I'd need to carefully read the testcase to be sure, though, as some things might happen to work, like a sleep in a side module where the main module is not on the stack at all. It's the case with a mixed stack where I am pretty sure we just need to do the work to share the Asyncify global state across the modules.

If you can avoid mixed stacks when sleeping then maybe that is a workaround (but as I said, I'm not sure). Otherwise, linking into a single module is the only really safe workaround until someone fixes this.

**Comment by sbc100** [comment]
I guess we should be disallowing this combination of flags then?

**Comment by sbc100** [comment]
It looks like its at least possible to use asyncify in the main module itself: https://github.com/emscripten-core/emscripten/pull/14996.. but its not clear if we should even allow this given that if it won't work across the module boundaries?

**Comment by kripken** [comment]
It might be safer to disallow it entirely. But a non-mixed stack might work actually (I can't think of a reason why not) and maybe some people find that useful. Perhaps printing a warning is a reasonable compromise for now?

**Comment by chkuendig** [comment]
FWIW, I encountered #14996 while debugging the same project (trying to get [ScummVM](https://github.com/scummvm/scummvm/) to load plugins dynamically to shrink code size). So that (running MAIN_MODULE with Asyncify) wasn't the actual goal but just something I ran into.
