### ISSUE TITLE
harfbuzz from ports not working?

### ISSUE THREAD

**Issue by ensisoft** [emscripten-core/emscripten#15601]
Hello, I'm on ArchLinux, emscripten installed from Arch repos. emscrpten 2.0.27.

Compling with -s USE_FREETYPE=1 -s USE_HARFBUZZ=1  doesn't do anything regarding harfbuzz. I can see that freetype appears in my ~/.emscripten_cache/ports but that's all. 

Couldn't find much information regarding emscripten and harfbuzz. Is this supposed to be working? 
Thanks!

**Comment by ensisoft** [comment]
Retested 3.0.0 from github repo. Same thing, doesn't do anything regarding harzbuff. How to debug this issue?

**Comment by sbc100** [comment]
Can you try with the official emsdk releases?  If it works with emsdk but fails on ArchLinux then this would be an bug in the arch linux package rather than emscripten itself.

**Comment by ensisoft** [comment]
Hi, so I tried with the emscripten from repo. It seems that if I invoke emcc manually (or lets say via Makefile) 

$ emcc ... -s USE_HARFBUZZ=1 

It works as expected and pulls in harfbuzz port. 

However if I try to accomplish the same using a CMake to generate the Makefile I'm not getting this to work.

I've tried the following in my CMake.

# based on the example at
# https://gist.github.com/WesThorburn/00c47b267a0e8c8431e06b14997778e4

set_target_properties(test PROPERTIES LINK_FLAGS "-s USE_HARFBUZZ=1")

Also tried
set(CMAKE_CXX_FLAGS "-s USE_HARFBUZZ=1")

and then 

$ mkdir build
$ cd build 
$ emcmake cmake .. 
$ make

Thank you for your time.

**Comment by sbc100** [comment]
I cmake getting confused about the arguments?   Can you try running the build with `make VERBOSE=1` to see the actual command line used?    Try removing the space between `-s` and `USE_HARFBUZZ` (you can also remove the =1).   Just `-sUSE_HARFBUZZ` should be enough.

**Comment by sbc100** [comment]
Also, if you want to use the harfbuzz headers during compilation you will need to add that flag to you C/CXXFLAGS, not just your link flags.

**Comment by ensisoft** [comment]
> Also, if you want to use the harfbuzz headers during compilation you will need to add that flag to you C/CXXFLAGS, not just your link flags.

This doesn't seem right. In fact when doing 'emcc source.cpp -s USE_HARFBUZZ=1' there's no need to specify any -I flags for the file inclusion. The harzbuff header dir is properly included automatically. (

**Comment by sbc100** [comment]
> > Also, if you want to use the harfbuzz headers during compilation you will need to add that flag to you C/CXXFLAGS, not just your link flags.
> 
> This doesn't seem right. In fact when doing 'emcc source.cpp -s USE_HARFBUZZ=1' there's no need to specify any -I flags for the file inclusion. The harzbuff header dir is properly included automatically. (

Yes, that is what I am saying.   You need to specify `-s USE_HARFBUZZ=1` when compiling source.cpp, not just when linking source.o into an executable. i.e. you need to add `-sUSE_HARFBUZZ` to both LINK_FLAGS and CXX_FLAGS.

**Comment by ensisoft** [comment]
Ok so I think I finally discovered the right incantation to make this work.

So I comment here what I did for posterity and in case it's useful for someone.

First some things I discovered:

- The emscripten -s flags  can be either *compile*  or *link* flags depending on the flag! 
   - WASM a link flag
   - USE_HARFBUZZ can be either compile *OR* link flag and you need both eventually
- The emscripten flags don't seem to play nice with cmake 'target_compile_options' or 'target_link_options' rules. (I got errors when trying to put multiple -s flags through these rules)
- The flags that go to the LLVM frontend seem to work as usual with 'target_compile_options' rules. (for example -O3 or -fexceptions)

```
cmake_minimum_required(VERSION 3.0)

project(ProjectName))

set(CMAKE_CXX_STANDARD 17)

add_executable(foobar source.cpp)

target_compile_options(foobar PRIVATE -fbracket-depth=1024 -fexceptions -O3)

set_target_properties(foobar PROPERTIES COMPILE_FLAGS "-s USE_HARFBUZZ=1 -s USE_FREETYPE=1 -s USE_BOOST_HEADERS=1")

set_target_properties(foobar PROPERTIES LINK_FLAGS "-s USE_HARFBUZZ=1 -s USE_FREETYPE=1 -s USE_BOOST_HEADERS=1 -s FORCE_FILESYSTEM=1 -s WASM=1")
```

Then to build

```
  $ mkdir build
  $ cd build
  $ emcmake cmake ..
  $ make -j16
```

That works for me (for now)

Thank you for your time and advice.

**Comment by sbc100** [comment]
As I mentioned earlier if you want `-s` options to play nicer with cmake you can remove the space between the `-s` and the option name (and also you can remove the =1 at the end.   e.g. `-sUSE_HARFBUZZ`.   'target_compile_options' and 'target_link_options' should then work fine.

**Comment by ensisoft** [comment]
> As I mentioned earlier if you want `-s` options to play nicer with cmake you can remove the space between the `-s` and the option name (and also you can remove the =1 at the end. e.g. `-sUSE_HARFBUZZ`. 'target_compile_options' and 'target_link_options' should then work fine.

Thanks, this seems to work. :+1:
