### ISSUE TITLE
write the render module by vulkan , and compile to the webgpu ?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#15623]
if i write the render module by vulkan in C code , and compile by emscripten , so can it generate the webgpu mode ?

**Comment by sbc100** [comment]
@kainino0x ?

**Comment by kainino0x** [comment]
No, there is no support to do so in Emscripten, and I'm not aware of any such translation layers being developed in the community at this time. Such a translation layer is an open problem but would gain wide interest in the WebGPU community. It wouldn't even have to be emscripten specific - just a C-to-C translation of Vulkan to webgpu.h. However it would be quite a large project!
