### ISSUE TITLE
.data file loading with preloaded package fails with pthread enabled

### ISSUE THREAD

**Issue by shanumantesc** [emscripten-core/emscripten#15627]
- I am overriding `Module['getPreloadedPackage']` to provide the .data file for the JS glue file (MyProject.js)
- However, when using pthreads, when the worker file (MyProject.worker.js) tries to load the glue file (MyProject.js) , preloaded package is not specified and since the .data file is not hosted at the default server root, the glue file now fails to load the .data file.

**Comment by shanumantesc** [comment]
I was able to work around this using the following changes - https://github.com/emscripten-core/emscripten/compare/main...shanumantesc:sh/fix-data-binary-pthread?expand=1

Is this the recommended approach, or can we do something better?

**Comment by kripken** [comment]
I think probably the general answer here is that we are working on a rewrite of the filesystem code, so it's probably better to work around issues with the old code atm while thinking about the proper solution in the new one. But to make sure I understand this, why is the worker trying to load a package? The main thread should preload files etc. as in the current FS logic all file operations happen there?

**Comment by shanumantesc** [comment]
From what I see, once the worker (created for pthread) loads the main glue file, the main glue file will always try to load the .data package (via code generated by https://github.com/emscripten-core/emscripten/blob/main/tools/file_packager.py) 

The reason to do so would be if we want the pthread to have access to the same set of preloaded files as the main thread. I'm not sure if all FS operations with pthread are being proxied to the main thread; if we are indeed proxying then we can just skip the preload by adding some flag in file_packager.py. This flag would have to check whether we are running within a worker spawned to support a pthread (not sure if we already have something like this). WDYT?

**Comment by sbc100** [comment]
Yes, FS operations are generally proxied back to the main thread so only the main runtime thread should do the file preloading (IIUC).     

The check for running in a thread is either `ENVIRONMENT_IS_PTHREAD `(from JS library code) or `!emscripten_is_main_runtime_thread()` (from native code)
