### ISSUE TITLE
Can I use more than one WASM for the same page.

### ISSUE THREAD

**Issue by donghang1994** [emscripten-core/emscripten#15634]
Can multiple WASM compilations from different code be called on the same page in browser

**Comment by kripken** [comment]
Yes. The best way is to compile with `MODULARIZE` and `EXPORT_NAME`. See the FAQ:

https://emscripten.org/docs/getting_started/FAQ.html#can-i-use-multiple-emscripten-compiled-programs-on-one-web-page

**Comment by donghang1994** [comment]
> Yes. The best way is to compile with `MODULARIZE` and `EXPORT_NAME`. See the FAQ:
> 
> https://emscripten.org/docs/getting_started/FAQ.html#can-i-use-multiple-emscripten-compiled-programs-on-one-web-page

Ok, Thank you !!

**Comment by donghang1994** [comment]
> Yes. The best way is to compile with `MODULARIZE` and `EXPORT_NAME`. See the FAQ:
> 
> https://emscripten.org/docs/getting_started/FAQ.html#can-i-use-multiple-emscripten-compiled-programs-on-one-web-page

At the same time use two wasm, Do the two modules use their own memory respectively? The maximum limit is that each module can use 2g.

**Comment by sbc100** [comment]
With emscripten, each module will get its own wasm memory.  They are not shared and can each of their own max.

Also, I think if you can go up to 4Gb these days (https://github.com/emscripten-core/emscripten/blob/5ce6706c16b5400608b04192e83cb92e7cf4f74f/src/settings.js#L188).

**Comment by donghang1994** [comment]
> With emscripten, each module will get its own wasm memory. They are not shared and can each of their own max.
> 
> Also, I think if you can go up to 4Gb these days (
> 
> https://github.com/emscripten-core/emscripten/blob/5ce6706c16b5400608b04192e83cb92e7cf4f74f/src/settings.js#L188
> 
> ).

I used “ALLOW_MEMORY_GROWTH=1”， the max wasm memory is it only going to be 2g ,not 4g?

**Comment by sbc100** [comment]
If you want to grow above 2Gb you need to set `MAXIMUM_MEMORY` to something larger than 2Gb (See the link to the docs for settings.js).

**Comment by spider853** [comment]
How does Module object works in case of two wasms, isn't Module shared? if one has a pre-js with some Module methods/properties, will they be shared in both wasms environment?

**Comment by sbc100** [comment]
If you have more than one module on the page you to wrap your modules into their own scope somehow.   You can have emscripten do this for you using the `-sMODULARIZE` setting.
