### ISSUE TITLE
Undefined symbol: vtable

### ISSUE THREAD

**Issue by CubicPP** [emscripten-core/emscripten#15635]
I am currently making a game using C++ and SDL. It was all working fine until i imported some code from another project of mine and it all stopped working for some reason.

This is the command i executed in emcmdprompt.bat:
```Batch
em++ -O2 -std=c++17 -s ALLOW_MEMORY_GROWTH=1 -s MAX_WEBGL_VERSION=2 -s MIN_WEBGL_VERSION=2 -s Application.cpp -o C:\Users\Gabriel\source\repos\Poinzle\bin\Emscripten\index.html --preload-file C:\Users\Gabriel\source\repos\Poinzle\Assets
```

And this is the error i get:
```Batch
wasm-ld: error: C:\Users\Gabriel\AppData\Local\Temp\emscripten_temp_uedmyk4m\Application_0.o: undefined symbol: vtable for Game::GameController
em++: error: 'C:/Users/Gabriel/source/repos/_Tools/emsdk/upstream/bin\wasm-ld.exe -o C:\Users\Gabriel\source\repos\Poinzle\bin\Emscripten\index.wasm C:\Users\Gabriel\AppData\Local\Temp\emscripten_temp_uedmyk4m\Application_0.o -LC:\Users\Gabriel\source\repos\_Tools\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL-webgl2 -lal -lhtml5 -lstubs -lc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -ldlmalloc -lc_rt -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__wasm_call_ctors --export-if-defined=__errno_location --export-if-defined=malloc --export-if-defined=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (returned 1)
```

It says the problem is with the GameController class, which has the following code:

GameController.h
```C++
#pragma once

#include "../ERIS/Controller.h"

namespace Game
{
	class GameController : public ERIS::Controller
	{
	private:


	public:
		void Initialize() override;
		void Update(int _deltaTime) override;
		void Render() override;
		void Clean() override;
	};
}
``` 
GameController.cpp
```C++
#include "GameController.h"

void Game::GameController::Initialize() { Game::GameController::Controller::Initialize(); }

void Game::GameController::Update(int _deltaTime) { Game::GameController::Controller::Update(_deltaTime); }

void Game::GameController::Render() { Game::GameController::Controller::Render(); }

void Game::GameController::Clean() { Game::GameController::Controller::Clean(); }
```

This is the code for it's parent class:

Controller.h
```C++
#pragma once

namespace ERIS
{
	class Controller
	{
	private:


	public:
		virtual void Initialize();
		virtual void Update(int _deltaTime);
		virtual void Render();
		virtual void Clean();
	};
}
```

Controller.cpp
```C++
#include "Controller.h"

void ERIS::Controller::Initialize() {}

void ERIS::Controller::Update(int _deltaTime) {}

void ERIS::Controller::Render() {}

void ERIS::Controller::Clean() {}
```

As you can see, there isn't much code in here, so i don't actually know where this error comes from. There is only *one* function that uses the GameController class, so i figured maybe it was the cause, but when i commented it out, i got a different error message:
```Batch
Nothing to do!
em++: error: 'C:\Users\Gabriel\source\repos\_Tools\emsdk\upstream\emscripten\tools\file_packager.bat C:\Users\Gabriel\source\repos\Poinzle\bin\Emscripten\index.data --from-emcc --export-name=Module --preload C:\Users\Gabriel\source\repos\Poinzle\Assets' failed (returned 1)
```

The only library it uses is SDL, which is linked properly and all that. It compiles and runs perfectly when using MSVC, with no warnings or errors. I made sure to install LLVM and Emscripten's other dependencies. I don't get what's going on at all...

**Comment by kripken** [comment]
The "Nothing to do!" error from the file packager seems unrelated to this. Try running with `EMCC_DEBUG=1` in the env to see if that shows something weird. If not that should be easy to reduce to a small testcase (it should not depend on the source files at all).

The vtable issue is likely some form of C++ undefined behaviour but I'm not sure exactly how.

**Comment by CubicPP** [comment]
I figured it out. It was actually a really dumb mistake...
In Emscripten, if you use arguments like "USE_SDL", the value after the "=" is actually the version. I was using "USE_SDL=1", so it was compiling with SDL 1.2, and i was using SDL2. All i had to do was change the "USE_SDL=1" to "USE_SDL=2".
