### ISSUE TITLE
Improve DX for missing system dependencies

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#15671]
Occasionally we have bugs or setting incompatibilities, where system functions are not found.

In many of those cases, it's bug on the Emscripten side rather than users mistake, but the output for undefined symbols today is exactly the same.

As a minimum, we should collect a list of system functions (e.g. libc one), check if a missing function is a system one, and if it is, print something more useful like "This seems to be an internal error, rather than a misconfiguration on your side. Please report a bug at https://github.com/emscripten-core/emscripten/issues/new.".

From there, we can refine things further and e.g. detect missing reverse dependencies in our configuration automatically. cc @sbc100

**Comment by sbc100** [comment]
Sorry for the extreme delay replying here.    This sounds like it could be good idea but i'm not sure what you mean by "missing function is a system one".   Specifically what is a system function in this case. 

What kind of internal error do you think might cause such as thing.  Maybe clear example would help me figure out way to make the error message different in that particular case.

**Comment by RReverser** [comment]
Pretty sure there was a specific issue back when I reported this that we discussed in private and I raised a bug for tracking afterwards... but, clearly, I haven't captured enough context in the issue description :(

I think it was something to do with ntohl shenanigans we had where some dependency in library*.js was incorrectly declared? Or I might be misremembering.

**Comment by RReverser** [comment]
Looking at your PRs around the date, perhaps was related to https://github.com/emscripten-core/emscripten/pull/15715.

Anyway, it's clearly not very actionable, so I'll just close it - sorry for not capturing enough context here.
