### ISSUE TITLE
Non-reproducible asmLibraryArg import names

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#15706]
So I haven't been able to reproduce this through manually compiling, but in my project's test and deploy Github Action, Emscripten is changing the names of asmLibraryArg imports for exactly the same code.

This is from this deploy commit: https://github.com/curiousdannii/parchment/commit/1de32c266199f38330a4a5847d25f8738f47ecc8

I don't have the original source code, so instead I have this rolluped-and-tersered-then-prettyjsified diff (for dist/web/git.js):
https://gist.github.com/curiousdannii/6d7e2226554b524a605c6179df1567c9/revisions

The .wasm also increased in size by 9 bytes.

That [first import](https://gist.github.com/curiousdannii/6d7e2226554b524a605c6179df1567c9#file-gistfile1-txt-L2490) is `___clock_gettime`. The other ones whose import names changed are `___syscall_access`, `___syscall_getcwd`, `___syscall_open`, `_fd_read`, `_fd_write`.

It's not really a big deal, but it would be nice to get perfect byte reproducible builds. Anyone else observed this happen?

**Comment by kripken** [comment]
Interesting. The import name changes looks like a possible closure compiler bug. If you can't reproduce this without closure then I'd assume it's that. (If it is that, then I don't think we can work around it - filing a closure bug is all we can do here.)

The wasm size increase is also puzzling. Can you maybe attach two such different wasm files? That could be an unknown determinism bug in either LLVM or binaryen. (I don't see how it could be related to closure compiler, so sounds like a separate issue.)

(In all these cases, I agree any nondeterminism is a bug - we should have perfectly reproducible builds, and I thought we did until now :smile: )

**Comment by curiousdannii** [comment]
I'm not using Closure!

Here are the two wasm files:
Old: https://github.com/curiousdannii/parchment/blob/f2fe49f06ab22aaa5fa93f1c44d0e4375ac0b49f/dist/web/git-core.wasm
New: https://github.com/curiousdannii/parchment/blob/1de32c266199f38330a4a5847d25f8738f47ecc8/dist/web/git-core.wasm

**Comment by kripken** [comment]
Oh, sorry, heh, that looked like closure to me... :smile: 

Diffing the wasm files, I see this:
```diff
- (data (i32.const 22296) "\t")
+ (data (i32.const 22296) "\05")
  (data (i32.const 22308) "#")
- (data (i32.const 22328) "\"\00\00\00\00\00\00\00 \00\00\00\e8x\00\00\00\04")
- (data (i32.const 22372) "\ff\ff\ff\ff")
- (data (i32.const 22440) "\f0\7fP\00\ff\ff\ff\ff")
+ (data (i32.const 22332) "!\00\00\00 \00\00\00\00}")
+ (data (i32.const 22356) "\02")
+ (data (i32.const 22372) "\ff\ff\ff\ff\ff\ff\ff\ff")
+ (data (i32.const 22440) "\18W\00\00\10\80P\00\ff\ff\ff\ff")
```

Those are actual changes to stuff in the data section, which Binaryen can't cause, so this nondeterminism must be happening in LLVM. Possibly wasm-ld as a first guess since it seems data may be moving around.

I'm less familiar with that side, but probably to get a good testcase for debugging there we should get the linker inputs + the emcc link command @sbc100 ?

**Comment by curiousdannii** [comment]
Both outputs come from this commit: https://github.com/curiousdannii/emglken/tree/3752188068957fd25708124c02deaae1a549507d
Build with `npm run build`

If it would help I could give you the output from make's verbose mode.

**Comment by sbc100** [comment]
Those data sections look pretty different.  For example `\t` only occurs in the old data section and `\05` only occurs in the new one.   That is probably a good thing to start investigating.

**Comment by curiousdannii** [comment]
It's happened again: https://github.com/curiousdannii/parchment/commit/89fb83ff5130d5d9fb2781dd01fccfe0d64dfe46

Again, no changes were made to any of the source files, and I'm using a pinned version Emsdk Docker image.

All the .wasm files lost bytes, mostly under 40 bytes, but one of them lost 506.

**Comment by sbc100** [comment]
If this is due to non-determinism, then this PR might help: https://github.com/emscripten-core/emscripten/pull/15780.

**Comment by sbc100** [comment]
Actually if you are using a pinned emsdk it won't help.

**Comment by sbc100** [comment]
One way to debug this is to run your link with `EMCC_DEBUG=1` set and save the intermediate files that live in /tmp/emscripten_temp.   When you see differences you can compare the output of various stages to figure out which stage has non-determinism.

I assume all of the inputs to `emcc` are fixed (i.e. all of the object files and all the emsdk libraries)?

Perhaps when you detect this issue you could re-run the link to see if its persistent?  I.e. does re-link immediately always give the same result?

**Comment by curiousdannii** [comment]
Well not now, but hopefully in the future ;)

When I initially reported this, I tried recompiling it manually probably close to 20 times, and never had any different results. I've only observed it happen in Github Actions. I wonder if it the Actions image might use a different file system which is less deterministic or something?

But I think I can turn on EMCC_DEBUG in actions, and then save those files... I'll give it a try and let you know.

**Comment by sbc100** [comment]
(Remember you only need to use `EMCC_DEBUG` for the linker action..  do you have many linker actions?)

**Comment by curiousdannii** [comment]
Ohhh. Yeah, I was trying it for everything, which was very noisy haha.

This is looking tricky. I'm using CMake... any idea how to set an env variable only for linking? `LDFLAGS` won't work, will it?

**Comment by sbc100** [comment]
Hmm.. good point, I guess maybe we should have version of `EMCC_DEBUG` that can be set from the command line too.. then you could add it to `LDFLAGS`. 

One method you could try would be to build the entire project .. then delete the .wasm output and run the build again with `EMCC_DEBUG` set.. and this time around only the link phase will be run.

**Comment by kleisauke** [comment]
I think I see a similar non-determinism behavior on the [wasm-vips](https://github.com/kleisauke/wasm-vips) project when I experimented with WasmFS (on the latest tip-of-tree build). I was able to reproduce it by adding `-sWASMFS -lpipefs.js` to the linker flags, for example:
```diff
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -105,8 +105,6 @@ set_target_properties(${TARGETS}
         PROPERTIES
             OUTPUT_NAME "vips"
             LINK_FLAGS "\
---closure=1 \
---closure-args=\"--externs ${CMAKE_CURRENT_SOURCE_DIR}/closure-externs/wasm-vips.js\" \
 --bind \
 -sMODULARIZE \
 -sEXPORT_NAME='Vips' \
@@ -118,7 +116,9 @@ set_target_properties(${TARGETS}
 -sTEXTDECODER=2 \
 -sASSERTIONS=0 \
 -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=emscripten_num_logical_cores \
--sEXPORTED_RUNTIME_METHODS=FS,ENV,deletionQueue,addFunction"
+-sEXPORTED_RUNTIME_METHODS=FS,ENV,deletionQueue,addFunction \
+-sWASMFS \
+-lpipefs.js"
         )
 
 if("node" IN_LIST ENVIRONMENT)
```
(this patch also disables Closure, just to be sure)

After executing `./build.sh`, I sometimes saw:
```bash
/home/kleisauke/wasm-vips/lib/node-commonjs/vips.wasm: OK
/home/kleisauke/wasm-vips/lib/node-es6/vips.wasm: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

Or:
```
/home/kleisauke/wasm-vips/lib/node-commonjs/vips.wasm: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

Which means that it fails on this sanity check:
https://github.com/kleisauke/wasm-vips/blob/bf146e3f1618bd604581c76c4f01817e4ccdee3e/build.sh#L376-L381
(but sometimes it just proceeds without any error)

I suspect this is due to the `EM_ASM` usage here:
https://github.com/emscripten-core/emscripten/blob/5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2/system/lib/wasmfs/file.cpp#L18-L30
(since that's the only place where `EM_ASM` is used)

But I'm not sure. I'll have a look to see if I can make a smaller reproduction.

**Comment by kleisauke** [comment]
Oh perhaps it's not due to the `EM_ASM` usage, I tried to comment that out to no avail. I've setup a smaller reproduction here:
https://github.com/kleisauke/emscripten-issue-15706

To reproduce:
```bash
$ git clone https://github.com/kleisauke/emscripten-issue-15706.git && cd emscripten-issue-15706
$ emcc -o vips.js vips.a -O3 --bind -pthread -sWASMFS -lpipefs.js
$ sha256sum vips.wasm
b7110b179c4fb62b1548e139cdb44ffeae654cacac8e4875af9273814fc552e8  vips.wasm
$ emcc -o vips.js vips.a -O3 --bind -pthread -sWASMFS -lpipefs.js
$ sha256sum vips.wasm
18c4c7a71f217a4a24e6c9d6fa03dfca2f7b57cf9facbc5ab91dbf129727ffac  vips.wasm
```

This was tested with Emscripten v3.0.1. Note that the non-determinism varies across these 2 checksums, so it doesn't generate a completely different checksum every run.

**Comment by kleisauke** [comment]
PR #15844 fixes this for me.

**Comment by curiousdannii** [comment]
I've never seen any non-determinism since upgrading to 3.1.1, so I'll call this fixed now. Thanks!
