### ISSUE TITLE
Add tests that measure JS code size

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#15709]
Currently we measure the size of the generated wasm file for tests in `tests/metadce` and we means sure size of the generated JS file for `tests/code_size` but we only measure for `-sMINIMAL_RUNTIME`.

We should extend one of both of these test types.

See #15708 for an example of JS codesize change (an improvement) that doesn't get picked up any current test.

**Comment by bkotsopoulossc** [comment]
I think it's worth discussing what it means to measure JS code size as well. For example, are we minifying it first? Are we measuring it gzip compressed? These are very standard ways of measuring JS code size, for example: https://bundlephobia.com/package/lodash@4.17.21

**Comment by sbc100** [comment]
We currently only measure minified (run through closure) code size.  We measure and track both gz and non-gz code size.   For an example of what we measure see: 
https://github.com/emscripten-core/emscripten/blob/main/tests/code_size/hello_webgl_wasm.json
 
Since we do already have a mechanism for measuring JS code size (we just only use it `MINIMAL_RUNTIME` mode) it seems like we can just re-use the same machamism for this issue.

If you think we are measuring wrong or could measure better that seems like a somewhat orthogonal issue.
