### ISSUE TITLE
Bug in page:Interacting with code: Command line doesn't work for my.

### ISSUE THREAD

**Issue by UnickSoft** [emscripten-core/emscripten#15701]
This command line didn't work for me under Windows:
`emcc tests/hello_function.cpp -o function.html -s EXPORTED_FUNCTIONS='["_int_sqrt"]' -s EXPORTED_RUNTIME_METHODS='["ccall","cwrap"]'`

I had these errors:
```
warning: invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: [ccall,'[ccall,cwrap]
emcc: error: undefined exported symbol: "[_int_sqrt]" [-Wundefined] [-Werror]
```
But I was able to use this:
`D:\emsdk\emcc.bat test.cpp -o function.html -s EXPORTED_FUNCTIONS='_int_sqrt' -s EXPORTED_RUNTIME_METHODS=ccall,cwrap`

I used this version:
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0 (3fd52e107187b8a169bb04a02b9f982c8a075205)`

URL: ../../../docs/porting/connecting_cpp_and_javascript/Interacting-with-code

**Comment by kripken** [comment]
Thanks @UnickSoft ! I opened #15702 to simplify those now.
