### ISSUE TITLE
Node+pthreads+wasm EH surprisingly slow

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#15727]
See

https://github.com/WebAssembly/binaryen/issues/4334#issuecomment-988264560

That builds wasm-opt with EH and pthreads, then optimizes a large file. Despite using multiple cores the wasm version running in node is over 10x slower.

Node profiler shows this:
```
 [C++]:
   ticks  total  nonlib   name
  31085   28.2%   28.4%  __lll_lock_wait
  14723   13.4%   13.4%  __pthread_mutex_unlock_usercnt
   5617    5.1%    5.1%  __pthread_cond_wait
   5279    4.8%    4.8%  __pthread_cond_timedwait
```
That's a lot of time spent in pthreads helper code for locking. I wonder if it's related to wasm atomics being always sequentially consistent or something like that? Just a random guess though.

**Comment by kripken** [comment]
Hmm, using builtins is a good idea - maybe we call these a lot and the overhead of going to JS is hitting us. But yeah, limitations on the web make it hard to do. What do you think about opening a PR though with your builtin work that keeps it behind a flag, for experimentation?

About `PTHREAD_POOL_SIZE`, I'll try that, maybe it will turn up something surprising.

**Comment by kleisauke** [comment]
I just opened draft PR #15740 to experiment with the use of atomic builtins on non-web environments.

**Comment by svenpilz** [comment]
Could it be possible that they are similar issues with Chrome? We have typical "parallel for loop"-kind of computations and noticed that Chrome does not really benefit from multiple threads, whereas Firefox performs as expected (compared to a native build). Meaning the same binary runs much faster on the same machine in Firefox compared to Chrome.

**Comment by kripken** [comment]
Data here shows that malloc/free become 2-3x slower when using atomics compared to without:

https://github.com/emscripten-core/emscripten/discussions/15914#discussioncomment-1948401

Not a big enough difference to explain this issue, but that might be something worth looking at too. Perhaps relaxed atomics could be used someday.

**Comment by kripken** [comment]
Good news, it looks like most of this slowdown is fixed by mimalloc.

[Building](https://gist.github.com/kripken/10ae73f44e939f8a5d7169e33777ebfb) a wasm EH+pthreads build now, I get the following numbers (running `-O3` on `poppler.wasm`):

|       | time (seconds) |
| ----------- | ----------- |
| Native (x86_64)      | 2.1   |
| Emscripten/mimalloc | 4.3 |
| Emscripten/dlmalloc   | 20.6        |

So with all modern features + mimalloc we are around 2x slower than a native build that uses all the CPU cores. Dlmalloc is still 10x slower as in the first measurement in this issue.

Closing as mimalloc basically resolved this.
