### ISSUE TITLE
Incompatibility with Catch2 CATCH_THROWS

### ISSUE THREAD

**Issue by ianhbell** [emscripten-core/emscripten#15749]
Catch2 is a very popular header-only testing library for C++.  It does some macro magic in its implementation, and a consequence is that emscripten is not able to decipher how to allow Catch2 to do the internal exception catching, even when exception handling is turned on. After compilation with exceptions enabled with a command line something like this in the emscripten/emsdk docker container (I'm building with cmake):
```console
/emsdk/upstream/emscripten/em++ -g -s DEMANGLE_SUPPORT=1 -s STACK_OVERFLOW_CHECK=2 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1 -fwasm-exceptions @CMakeFiles/emtest_catch_exception.dir/objects1.rsp  -o emtest_catch_exception.html
```
this code:
```C++
#define CATCH_CONFIG_MAIN
#include <catch/catch.hpp>
#include <exception>

TEST_CASE("test CHECK_THROWS", "[throws]")
{
    auto f = [](){throw std::invalid_argument("I'm an exception!"); };
    CHECK_THROWS(f());
}
```
yields the traceback
```
emtest_catch_exception.js:18 Uncaught WebAssembly.Exception: wasm exception
    at _Unwind_RaiseException (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[8877]:0x13853e)
    at __cxa_throw (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[8858]:0x138115)
    at ____C_A_T_C_H____T_E_S_T____0()::$_16::operator()() const (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[1890]:0x5ff19)
    at ____C_A_T_C_H____T_E_S_T____0() (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[1886]:0x5fcd0)
    at Catch::TestInvokerAsFunction::invoke() const (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[1310]:0x3f390)
    at Catch::TestCase::invoke() const (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[962]:0x2e844)
    at Catch::RunContext::invokeActiveTestCase() (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[869]:0x2a174)
    at Catch::RunContext::runCurrentTest(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&) (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[840]:0x28bd5)
    at Catch::RunContext::runTest(Catch::TestCase const&) (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[834]:0x27e3e)
    at Catch::(anonymous namespace)::runTests(std::__2::shared_ptr<Catch::Config> const&) (http://localhost:8000/emtest_catch_exception.wasm:wasm-function[1044]:0x334d9)
```

**Comment by sbc100** [comment]
`-fwasm-exceptions` enabled the new/experimental support for native WebAssemlby exceptions that is not yet shipping in browsers.

Can you confirm if this issue relates to native exceptions, or does it also show up with normal/traditional emscripten emscripten handling (`-sDISABLE_EXCEPTION_CATCHING=0`).

**Comment by ianhbell** [comment]
It always happens, even with ``-sDISABLE_EXCEPTION_CATCHING=0``.  That was the first thing I tried.

**Comment by ianhbell** [comment]
Same problem (cannot ``try...catch`` exceptions) with:
```c++
#include <exception>
#include <stdexcept>

int main(){
    auto f = [](){
        try{
            throw std::invalid_argument("I'm an exception!");
        }
        catch(...){
            // do nothing
        } 
        return 0;
    };
    f();
}
```

Tried with all the flag options, always fails without getting to the end of ``main()``. Any ideas?

**Comment by aheejin** [comment]
I tried your last example (https://github.com/emscripten-core/emscripten/issues/15749#issuecomment-993125618), and it looks both Emscripten EH and Wasm EH runs the code successfully. What I did was: I saved your code in test.cpp, and ran

- Emscripten EH:
```
emcc -s DISABLE_EXCEPTION_CATCHING=0 test.cpp -o test.js
node --experimental-wasm-eh test.js 
```
This requires a recent-enough node, which is probably later than v16.0, which is a later version than the node shipped with emsdk. You can use d8 too:
 ```
emcc -s DISABLE_EXCEPTION_CATCHING=0 -s ENVIEONMENT=shell test.cpp -o test.js
d8 --experimental-wasm-eh test.js 
```

- Wasm EH:
```
emcc -fwasm-exceptions test.cpp -o test.js
node --experimental-wasm-eh test.js
```
Or
```
emcc -fwasm-exceptions -s ENVIRONMENT=shell test.cpp -o test.js
d8 --experimental-wasm-eh test.js
```

All these runs successfully with the exit code 0 for me. Can you give me the exact command line you used?

Also I'm not sure how to use the CATCH library. If the bug can be only reproducible with that library, it would also help if you can give detailed instructions reproduce it too.

**Comment by ianhbell** [comment]
I'm with you - even with default node in emsdk, the problem does not appear with your command line calls when I tried on my side. 

I think there is a bug in the toolchain file, or it is not structured properly.  The cmake argument add_compiler_options has no effect (which is why the exception handling didn't make it to the compile step). Thus I think the problem comes from the ToolChain file for cmake provided in emsdk: ``/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake``.  It does a bunch of magical things, and it seems that some of those magical things cause compiler flags to be ignored.

A log from a build resulting in bad exception handling looks like this:
```
runner_1  | -- Build files have been written to: /bld
runner_1  | /usr/bin/cmake -S/src -B/bld --check-build-system CMakeFiles/Makefile.cmake 0
runner_1  | /usr/bin/make -f CMakeFiles/Makefile2 emtest_catch_exception2
runner_1  | make[1]: Entering directory '/bld'
runner_1  | /usr/bin/cmake -S/src -B/bld --check-build-system CMakeFiles/Makefile.cmake 0
runner_1  | /usr/bin/cmake -E cmake_progress_start /bld/CMakeFiles 2
runner_1  | /usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/emtest_catch_exception2.dir/all
runner_1  | make[2]: Entering directory '/bld'
runner_1  | /usr/bin/make -f CMakeFiles/emtest_catch_exception2.dir/build.make CMakeFiles/emtest_catch_exception2.dir/depend
runner_1  | make[3]: Entering directory '/bld'
runner_1  | cd /bld && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /src /src /bld /bld /bld/CMakeFiles/emtest_catch_exception2.dir/DependInfo.cmake --color=
runner_1  | Dependee "/bld/CMakeFiles/emtest_catch_exception2.dir/DependInfo.cmake" is newer than depender "/bld/CMakeFiles/emtest_catch_exception2.dir/depend.internal".
runner_1  | Dependee "/bld/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/bld/CMakeFiles/emtest_catch_exception2.dir/depend.internal".
runner_1  | Scanning dependencies of target emtest_catch_exception2
runner_1  | make[3]: Leaving directory '/bld'
runner_1  | /usr/bin/make -f CMakeFiles/emtest_catch_exception2.dir/build.make CMakeFiles/emtest_catch_exception2.dir/build
runner_1  | make[3]: Entering directory '/bld'
runner_1  | [ 50%] Building CXX object CMakeFiles/emtest_catch_exception2.dir/src/emtest_catch_exception2.cpp.o
runner_1  | /emsdk/upstream/emscripten/em++  -DUSE_TEQP_HMX @CMakeFiles/emtest_catch_exception2.dir/includes_CXX.rsp -g   -std=gnu++17 -o CMakeFiles/emtest_catch_exception2.dir/src/emtest_catch_exception2.cpp.o -c /src/src/emtest_catch_exception2.cpp
runner_1  | [100%] Linking CXX executable emtest_catch_exception2.js
runner_1  | /usr/bin/cmake -E cmake_link_script CMakeFiles/emtest_catch_exception2.dir/link.txt --verbose=1
runner_1  | /emsdk/upstream/emscripten/em++  -g   -s DISABLE_EXCEPTION_CATCHING=0 @CMakeFiles/emtest_catch_exception2.dir/objects1.rsp  -o emtest_catch_exception2.js
runner_1  | make[3]: Leaving directory '/bld'
runner_1  | [100%] Built target emtest_catch_exception2
runner_1  | make[2]: Leaving directory '/bld'
runner_1  | /usr/bin/cmake -E cmake_progress_start /bld/CMakeFiles 0
runner_1  | make[1]: Leaving directory '/bld'
```

Note how even though I have ``add_compile_options( -s DISABLE_EXCEPTION_CATCHING=0)`` in my CMakeLists.txt, that is not present in the compile step.

**Comment by sbc100** [comment]
One thing to be aware of is that when you use `add_compile_options` I think its best not to include the space between the `-s` and the option name.  `-sDISABLE_EXCEPTION_CATCHING=0` should work fine and prevent cmake from re-ordering stuff.

I don't think we do anything in `Emscripten.cmake` that could make your compiler flags be ignored.

**Comment by ianhbell** [comment]
Thanks for the heads up.  But for some reason the flags are entirely ignored.  I remember I had a similar problem before, so in my other project have this kludge of ``add_definitions`` instead of the more logical ``add_compiler_options``.

**Comment by aheejin** [comment]
I don't have any idea about `Emscripten.cmake` for now, but it would help to know which command I should run to reproduce the problem.

**Comment by ianhbell** [comment]
To get this to happen, you need to be running with cmake toolchain file.  You can see one example here: https://github.com/usnistgov/teqp/blob/1f29cd7dd9a935c13e4dbd7f6ae51274d5d27a26/interface/js/build.sh (that script runs inside the emsdk container)

**Comment by aheejin** [comment]
Can you give concrete steps of command line commands to reproduce the problem? If a library is necessary, including how to install it?

**Comment by ianhbell** [comment]
An example something like this would do it (check out compilation flags at both steps):

```console
mkdir /bld
cd /bld
cmake /src -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
```
with main.cpp:
```c++
#include <exception>
#include <stdexcept>

int main(){
    auto f = [](){
        try{
            throw std::invalid_argument("I'm an exception!");
        }
        catch(...){
            // do nothing
        } 
        return 0;
    };
    f();
}
```
and CMakeLists.txt
```
cmake_minimum_required(VERSION 3.16)
project(emsdktest)

####  SETUP
set(CMAKE_CXX_STANDARD 17)

add_compile_options( -s DISABLE_EXCEPTION_CATCHING=0) # appears to have no effect with toolchain file in effect
add_executable(main main.cpp)
```

**Comment by aheejin** [comment]
Those exception options are both compile and link time options.

For Emscripten EH, you need
```
add_compile_options(-sDISABLE_EXCEPTION_CATCHING=0)                             
add_link_options(-sDISABLE_EXCEPTION_CATCHING=0) 
```
This also works for Emscripten EH: (`-fexceptions` uses the default EH, which is currently Emscripten EH)
```
add_compile_options(-fexceptions)
add_link_options(-fexceptions)
```

For Wasm EH, you need
```
add_compile_options(-fwasm-exceptions)
add_link_options(-fwasm-exceptions)
```

We recently wrote a short doc on EH support: https://emscripten.org/docs/porting/exceptions.html
This also says those options are needed to be passed both compile and link time. 

Also generally, for `-s` settings, you can refer to https://github.com/emscripten-core/emscripten/blob/main/src/settings.js to check if each setting is whether a compile option, a link option, or both. For example, `DISABLE_EXCEPTION_CATCHING` is written as a `compile+link` option: https://github.com/emscripten-core/emscripten/blob/8e1e305519e1027726a48861a1fec5662f7e18a2/src/settings.js#L675

**Comment by ianhbell** [comment]
But you didn't try my example - the compile options are not set at the compile step

**Comment by aheejin** [comment]
No I tried your example, and added `add_link_options` to your CMakeLists.txt, and got it working both with Emscripten EH and Wasm EH.

So I downloaded your two files into a directory: 
```
aheejin@aheejin:~/test/ianhbell$ ls
CMakeLists.txt  main.cpp
```

And added `add_link_options` line to your CMakeLists.txt. So it is now this:
```cmake
cmake_minimum_required(VERSION 3.16)
project(emsdktest)

####  SETUP
set(CMAKE_CXX_STANDARD 17)

add_compile_options(-sDISABLE_EXCEPTION_CATCHING=0)
add_link_options(-sDISABLE_EXCEPTION_CATCHING=0) ;; Newly added
add_executable(main main.cpp)
```

And I ran your `cmake` command. Note that the path has changed to match my setup:
```
aheejin@aheejin:~/test/ianhbell$ cmake . -DCMAKE_TOOLCHAIN_FILE=~/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release
```

And I ran `make`. The below is the output of `make`. You can see `-sDISABLE_EXCEPTION_CATCHING=0` is added to both compilation and link commands:
```
aheejin@aheejin:~/test/ianhbell$ make
/usr/bin/cmake -S/usr/local/google/home/aheejin/test/ianhbell -B/usr/local/google/home/aheejin/test/ianhbell --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /usr/local/google/home/aheejin/test/ianhbell/CMakeFiles /usr/local/google/home/aheejin/test/ianhbell//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/usr/local/google/home/aheejin/test/ianhbell'
make  -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/depend
make[2]: Entering directory '/usr/local/google/home/aheejin/test/ianhbell'
cd /usr/local/google/home/aheejin/test/ianhbell && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /usr/local/google/home/aheejin/test/ianhbell /usr/local/google/home/aheejin/test/ianhbell /usr/local/google/home/aheejin/test/ianhbell /usr/local/google/home/aheejin/test/ianhbell /usr/local/google/home/aheejin/test/ianhbell/CMakeFiles/main.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/usr/local/google/home/aheejin/test/ianhbell'
make  -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
make[2]: Entering directory '/usr/local/google/home/aheejin/test/ianhbell'
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
/usr/local/google/home/aheejin/emsdk/upstream/emscripten/em++   -O3 -DNDEBUG -sDISABLE_EXCEPTION_CATCHING=0 -std=gnu++17 -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c /usr/local/google/home/aheejin/test/ianhbell/main.cpp
[100%] Linking CXX executable main.js
/usr/bin/cmake -E cmake_link_script CMakeFiles/main.dir/link.txt --verbose=1
/usr/local/google/home/aheejin/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG -sDISABLE_EXCEPTION_CATCHING=0 @CMakeFiles/main.dir/objects1.rsp -o main.js 
make[2]: Leaving directory '/usr/local/google/home/aheejin/test/ianhbell'
[100%] Built target main
make[1]: Leaving directory '/usr/local/google/home/aheejin/test/ianhbell'
/usr/bin/cmake -E cmake_progress_start /usr/local/google/home/aheejin/test/ianhbell/CMakeFiles 0
```

In the log above, the compilation command is:
```
/usr/local/google/home/aheejin/emsdk/upstream/emscripten/em++   -O3 -DNDEBUG -sDISABLE_EXCEPTION_CATCHING=0 -std=gnu++17 -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c /usr/local/google/home/aheejin/test/ianhbell/main.cpp
```
The link command is:
```
/usr/local/google/home/aheejin/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG -sDISABLE_EXCEPTION_CATCHING=0 @CMakeFiles/main.dir/objects1.rsp -o main.js 
```
You can see `-sDISABLE_EXCEPTION_CATCHING=0` in both.

And then I run the program:
```
aheejin@aheejin:~/test/ianhbell$ node main.js
```
This ran without any error.

Am I missing something?

**Comment by ianhbell** [comment]
Hmm.  No indeed that seems fine.  I think the problem is that I needed perhaps to also add ``add_link_options``, which I did not do, and instead set link flags via:
```
set(CMAKE_EXE_LINKER_FLAGS " -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 ")
```

It might be nice to have a sample ``CMakeLists.txt`` showing how to set options as you need non-standard CMake approaches for Emscripten.  Perhaps it could be here: https://emscripten.org/docs/porting/exceptions.html

**Comment by sbc100** [comment]
Can you explain what you mean by non-standard CMake approaches?    It sounds like you are saying that `CMAKE_EXE_LINKER_FLAGS` doesn't work under emscripten.   If that is that case that would be a bug, and something we would want to fix rather than document (if possible).   All the normal methods for setting compile and linker flags should work the same under emscripten.. at least the is the intention.

**Comment by ianhbell** [comment]
I mean to say that I have always had to do something like this: https://github.com/CoolProp/CoolProp/blob/71a82276ffd1d19bc886b0377b9838468ef0ace2/CMakeLists.txt#L1421-L1435 .

Because in my approach, if I set *compilation* flags in set_compile_flags, they are ignored when combined with ``set(CMAKE_EXE_LINKER_FLAGS ...)``

**Comment by ianhbell** [comment]
I still maintain that a clear cmake example would help a lot

**Comment by aheejin** [comment]
> Hmm. No indeed that seems fine. I think the problem is that I needed perhaps to also add `add_link_options`, which I did not do, and instead set link flags via:
> 
> ```
> set(CMAKE_EXE_LINKER_FLAGS " -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 ")
> ```

I did the same and it works for me too. I removed both `add_compile_options` and `add_link_options`, and added compile and link flags using `CMAKE_CXX_FLAGS` and `CMAKE_EXE_LINKER_FLAGS` as you did:
```cmake
cmake_minimum_required(VERSION 3.16)                                             
project(emsdktest)                                                               
                                                                                 
####  SETUP                                                                      
set(CMAKE_CXX_STANDARD 17)                                                       
                                                                                 
add_executable(main main.cpp)                                                    
     
# These two lines are added                                                                            
set(CMAKE_CXX_FLAGS " -s DISABLE_EXCEPTION_CATCHING=0")                          
set(CMAKE_EXE_LINKER_FLAGS " -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 ")
```

And this works for me fine.

**Comment by ianhbell** [comment]
Seems like I have something funny going on with one of my other dependencies. I tried to reproduce precisely this problem again and I don't seem to be able to.  I suspect a CMake flag caching issue.  We can close this issue

**Comment by ianhbell** [comment]
One last note: it seems like some confusion about the order in which one must specify ``add_compile_options`` and define targets. I guess this is an argument in favor of setting the options on the target rather than generally with ``add_compile_options``.

**Comment by ianhbell** [comment]
``add_compile_options`` is a global setting.  Granular setting of options/properties on a per target basis is almost always a better idea, especially when you get complicated dependencies between CMake projects.

**Comment by aheejin** [comment]
You can use target-specific options too:
```cmake
target_compile_options(main PUBLIC -sDISABLE_EXCEPTION_CATCHING=0)
target_link_options(main PUBLIC -sDISABLE_EXCEPTION_CATCHING=0)
```

**Comment by sbc100** [comment]
I don't think any of this is specific to emscripten though, is it?  There are general cmake characteristics we are discussing now, no?

**Comment by ianhbell** [comment]
Correct.  I just want to keep highlighting how a CMake example for Emscripten is so essential.

**Comment by sbc100** [comment]
Ah yes, I agree.   I think we recently had someone send PR to include one.   

I yes, here it is: https://github.com/emscripten-core/emscripten/pull/15347.  It looks like others agree with you :)
