### ISSUE TITLE
Dynamic linking and -fsanitize=null fails

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#15773]
**Version of emscripten/emsdk:**
Tip of tree build
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1-git (ad282f9824f37f3efdf0646ef0d514e1f568e749)
clang version 14.0.0 (https://github.com/llvm/llvm-project e7a95b067490dc90faea1baa78a66d08e1b2a7d4)
Target: wasm32-unknown-emscripten
Thread model: posix`

**Failing command line in full:**
`emcc -fsanitize=null -s MAIN_MODULE=1 main.cpp`
for simple c file
```c
int main() { return 0; }
```
fails due to the following wasm-ld errors:

`wasm-ld: error: symbol exported via --export not found: __heap_base`
`wasm-ld: error: symbol exported via --export not found: __global_base`

**Comment by sbc100** [comment]
Thanks, I imagine it was my recent change: #15716.

We have checks that prevent asan and lsan from running with dynamic linking since its not yet supported / tested.   Have you been able to use `sanitize=null` with dynamic linking in the past?

**Comment by gl84** [comment]
To be honest I don't know. I didn't disable the sanitizers in my project and compiling/linking worked as expected...

I did a quick test and it didn't work in 2.0.28 either. Seems that e.g. wasmTable.get(0) is null and is never set to something different...

**Comment by gl84** [comment]
Thanks for the quick fix
