### ISSUE TITLE
SDL mixer throws an error in firefox and chrome while playing wav files. 

### ISSUE THREAD

**Issue by RavikumarTulugu** [emscripten-core/emscripten#15772]
I am seeing this error in firefox and chrome when the code plays a wav file.  i am using --use-preload-plugins option to preload files. image files work fine but audio files fail to play. 
firefox error:
playWebAudio failed: TypeError: AudioBufferSourceNode.buffer setter: Value being assigned does not implement interface AudioBuffer.
All 32 channels in use!

chrome error: 
(index):1246 playWebAudio failed: TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': Failed to convert value to 'AudioBuffer'.
All 32 channels in use!

I am using SDL1 version due to certain limitations. 
I am using version emsdk-2.0.32 unmodified.

**Comment by RavikumarTulugu** [comment]
I am not sure whether the issue belongs here, so closing this.

**Comment by sbc100** [comment]
I think the emscripten repository seems like probably the right place for such a bug.
