### ISSUE TITLE
JS stack trace that bubbles up through wasm

### ISSUE THREAD

**Issue by bkotsopoulossc** [emscripten-core/emscripten#15781]
So let's say I have some JS and some C++, and I am using embind, with exceptions turned on (throwing and catching):

```
// main.cpp
#include <bind.h>

std::string getExceptionMessage(intptr_t exceptionPtr) {
  return std::string(reinterpret_cast<std::exception *>(exceptionPtr)->what());
}

EM_JS(void, bar, (), {
  throw new Error("some error msg");
});

void foo() {
  bar();
}

EMSCRIPTEN_BINDINGS(Bindings) {
  emscripten::function("foo", &foo);
  emscripten::function("getExceptionMessage", &getExceptionMessage);
};

// index.js
try {
  Module.foo()
} catch (e) {
  console.log("something went wrong", Module.getExceptionMessage(e))
}
```

This calls from JS into wasm, which then calls into JS, which throws. The exception will unravel back to the initial JS callsite, and I can catch it, then go back into wasm to get the c++ string message from the exception pointer.

This all is great, and I'm able to get the message from the JS error.

But unlike exceptions thrown by C++, this JS exception has other information. It has a stack trace and a type. Currently, as this JS exception bubbles up through wasm stack traces, that information is lost. Is there some way that we can also include the stack trace as a string, concatenated with the message, in these cases?

I assume that somewhere, this JS exception is converted into a c++ one and the c++ exception message is initialized with just the JS error message. I'm not sure where that happens though. Thoughts @sbc100 ?

**Comment by sbc100** [comment]
If you run this program with exceptions turned off completely in emscripten does it work as you expect?  i.e. without any loss of information?

**Comment by sbc100** [comment]
Can you also include the full command line you used to build this example?  (Also I assume the issue is reproducible under node as well as in the browser?)

**Comment by bkotsopoulossc** [comment]
I will try with exceptions disabled. I will also figure out a simple working repro. I haven’t tried node but I imagine it is the same. 

In general, do you know where in the emscripten tech stack that the JS error is converted into a C++ exception? That code might give us some clues

**Comment by sbc100** [comment]
Take a look at `create_invoke_wrappers` in `emscripten.py` and `JS.make_invoke()` in `tools/shared.py`

**Comment by sbc100** [comment]
It looks like we just catch and rethrow using `throw e;`

**Comment by sbc100** [comment]
It looks like rethrowing an exception is supposed to preserve the original stack: https://stackoverflow.com/questions/3734236/how-can-i-rethrow-an-exception-in-javascript-but-preserve-the-stack

**Comment by bkotsopoulossc** [comment]
But when we re-throw, the type being thrown is a number not an error object. The error object itself contains the stack trace.

**Comment by sbc100** [comment]
If we catch as JS exception is try just re-throw it I think, because we know we can't handle it.

The `new Error("some error msg");` that you throw should be caught and then re-thrown by emscripten code and then caught again by your code.

**Comment by sbc100** [comment]
In you example I don't think there are any C++ exception ever thrown or generated are there?

**Comment by sbc100** [comment]
Oh I see.. when you catch the exception you first need to check if its a raw number (a pointer) before you call `getExceptionMessage`.   Calling `getExceptionMessage` on a JS exception will never work, right?

**Comment by sbc100** [comment]
In other words you probably need to distinguish between the case when you catch C++/emscripten exception and when you catch a JS exception.

**Comment by bkotsopoulossc** [comment]
Hmm maybe my example is incomplete. I'm trying to take a big convoluted codebase and rip out a small example to make this simple, but I may have missed something. I am specifically talking about the case where there is a c++ exception involved, that bubbles back out to the original caller in JS, as a number, which internally is the memory address of the c++ exception_ptr. To create that scenario, maybe my example needs to have this change:
```
void foo() {
  try {
    bar();
  } catch (const std::exception& e) {
    throw e;
  }
}
```

I'll dig into it more, but somewhere there is code that turns a JS Error into a c++ exception, and that's really what I'm interested in finding - to see what we initialize the c++ exception message with.

**Comment by sbc100** [comment]
Yes, I think perhaps a fully working example would be useful.   In the current example it looks like it would be thrown and caught as a JS exception and not as a pointer/number.

@aheejin will probably be help here, especially once we have a full example what the problem is.

**Comment by bkotsopoulossc** [comment]
Looking into this deeper, I'm not sure I see any explicit try/catches on the c++ side, yet the JS error is in fact bubbling out of the c++ API and into JS as a c++ exception (number), not a JS one. Is this unexpected? I do however see that many of the call frames in the stack trace on the c++ side are wrapped with the `invoke_viiiii` type of JS wrappers. This is with exception catching and throwing enabled.

**Comment by sbc100** [comment]
Yes when emscripten exceptions you can expect to see a lot of you calls wrapping in `invoke_viiiii` JS wrappers which are used to facilitate exception catching and throwing in C++.   However as far as I know they should leave JS exceptions alone and just rethrow them without changing them.

**Comment by bkotsopoulossc** [comment]
I think the issue here was on my side, there's some custom stuff preventing the exception from bubbling out untouched. Sorry for wasting your time, I'll close this. Thank you for your pointers though, that helped a lot with debugging!

**Comment by aheejin** [comment]
It's unclear where to look given that I don't know whether you are using [Emscripten EH](https://emscripten.org/docs/porting/exceptions.html#javascript-based-exception-support) or [Wasm EH](https://emscripten.org/docs/porting/exceptions.html#webassembly-exception-handling-proposal). I guess you are using Emscripten EH if you are seeing invokes? Anyway AFAIK neither EH converts JS exceptions into integers. A concrete reproducer with a command line would help diagnose the issue.

**Comment by bkotsopoulossc** [comment]
I did not know wasm EH was out yet. Where do I find browser support versions? But yes, since we are talking about exceptions as integers and getExceptionMessage() calls, this is definitely emscripten EH

**Comment by bkotsopoulossc** [comment]
I am a bit confused conceptually though. If the call stack is JS -> C++ -> JS, and your exception usage looks like JS -> C++ (catches) -> JS (throws), then isn’t the JS error getting converted to a C++ exception where the catch is? How else would you be able to catch on the C++ side? Or does that not work?

**Comment by sbc100** [comment]
Prior to wasm EH there is no such thing as catching or throwing in C++.   We have to use JS stubs to help us to all of that   So when you say "C++ catches" that is not true.   Its a JS stub (invoke_xx) that catches in JS and tries to determine if the exception looks interesting (i.e. destined for the emulated "C++ catch").   If its JS a exception (as opposed to just a pointer/number) is will just rethrow up stack.

At least that is my understanding.    wasm EH is a completely different beast.

**Comment by bkotsopoulossc** [comment]
That makes sense, thanks.
