### ISSUE TITLE
Question about increasing heap size under sbrk

### ISSUE THREAD

**Issue by miladfarca** [emscripten-core/emscripten#15793]
I have a question on how sbrk detects if heap needs to be increased, on this line:
https://github.com/emscripten-core/emscripten/blob/main/system/lib/sbrk.c#L76
```c
if (new_brk > old_size) {
   // Try to grow memory.
   ...
}
```
Is `old_size` a pointer to the top of the heap or the actual size of the heap as an integer? if it's the latter then shouldn't the statement be something like `if (new_brk > (old_brk + old_size)){}` ?

**Comment by sbc100** [comment]
`old_size = emscripten_get_heap_size()` and `emscripten_get_heap_size` returns the size of the WebAssembly memory in bytes: 

https://github.com/emscripten-core/emscripten/blob/5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2/system/lib/libc/emscripten_get_heap_size.c#L11-L13

**Comment by miladfarca** [comment]
Correct, but isn't `new_brk` a pointer to an address (`old_brk + increment;`) ? and if so the expression is comparing a memory address with a memory chunk size? shouldn't it compare an address with another address instead? Maybe i'm missing something.

**Comment by sbc100** [comment]
addresses are integers, and `old_size` can also be seen as an address.. its the address of the end of the memory.. technically its the address of the first bytes past the end of memory.

**Comment by sbc100** [comment]
`new_brk` is an address, not a pointer to an address, but actually an address.    

Its the address that will then be stored in memory at `sbrk_ptr` which is a pointer an address.

**Comment by miladfarca** [comment]
Sorry, yes I meant to say `new_brk` is an address.
Did you mean `old_size` is end of memory or just end of heap? `old_size` can be seen as an address yes if `wasm heap` also starts at memory address 0, but does it? This is the image I have in mind which show `old_size != heap_top address` so maybe I'm misunderstanding something about wasm heap:
```
High address
---------------
kernel
-------
stack
------- <--------------------------- heap_top address
heap (includes wasm heap?)                              } old_size
------- <--------------------------- heap_bottom address = old_brk
.data
-------
.txt
---------------
Low address
```

**Comment by sbc100** [comment]
Ah yes, `emscripten_get_heap_size()` is wrongly names.  The header file `emscripten/heap.h` and most of the functions therein can be misleading.     

`emscripten_get_heap_size` gets the total size of the wasm memory.
`emscripten_get_heap_max` gets the biggers size that the wasm memory can be grown too.
`emscripten_resize_heap` resizes the wasm memory

**Comment by sbc100** [comment]
We should really fix that bad naming..  (while maintaining backwards compatibility with old / misleading names)

**Comment by sbc100** [comment]
I think the naming is that way for historical reason.   In the asm.js world the word heap was used to refer to the whole of the linear memory, not just the part managed by malloc.   That we why we still have HEAPU32 and HEAPSU8 which refer to the wasm memory buffers (not just the malloc heap).

**Comment by miladfarca** [comment]
Ah I see, so `emscripten_get_heap_size` and `__builtin_wasm_memory_size` isn't heap size, it's the total memory size, thanks for clarifying and for the information, will close this issue now.

**Comment by miladfarca** [comment]
@sbc100 wanted to clarify, by `wasm memory` are you referring to the entire virtual address space dedicated to this running process or just a portion of memory (heap) dedicated to wasm within this process?

**Comment by sbc100** [comment]
Yes exactly.   Wasm memory is the entire C/C++ address space starting at zero.

I opened a bug to consider renaming these functions.

**Comment by miladfarca** [comment]
Thank you so much.
