### ISSUE TITLE
duplicate symbol when using -fwasm-exceptions with STANDALONE_WASM

### ISSUE THREAD

**Issue by SaratAdiraj** [emscripten-core/emscripten#15800]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0 (3fd52e107187b8a169bb04a02b9f982c8a075205)

OS : Windows 10

Code:
######## hello.cpp ##################
```
#include <stdio.h>

int main() {
  try {
    puts("throw...");
    throw 1;
    puts("(never reached)");
  } catch(...) {
    puts("catch!");
  }
  return 0;
}
```

**Failing command line in full:**

```
em++ hello.cpp -fwasm-exceptions -o hello.wasm -flto

wasm-ld: error: duplicate symbol: __cxa_throw
>>> defined in C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libc++abi-except.a(cxa_exception.o)
>>> defined in C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libstandalonewasm.a(standalone.o)

wasm-ld: error: duplicate symbol: __cxa_allocate_exception
>>> defined in C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libc++abi-except.a(cxa_exception.o)
>>> defined in C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\libstandalonewasm.a(standalone.o)
em++: error: 'C:/emsdk/upstream/bin\wasm-ld.exe -o hello.wasm C:\AppData\Local\Temp\emscripten_temp_q67o46xz\hello_0.o -LC:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\lto\crt1.o -lGL -lal -lhtml5 -lstubs-debug -lc -lcompiler_rt -lc++-except -lc++abi-except -lunwind-except -ldlmalloc -lstandalonewasm -lc_rt -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -mllvm -wasm-enable-eh -mllvm -exception-model=wasm --import-undefined --strip-debug --export-if-defined=emscripten_stack_get_end --export-if-defined=emscripten_stack_get_free --export-if-defined=emscripten_stack_init --export-if-defined=stackSave --export-if-defined=stackRestore --export-if-defined=stackAlloc --export-if-defined=__errno_location --export-if-defined=malloc --export-if-defined=setThrew --export-if-defined=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-table -z stack-size=5242880 --initial-memory=16777216 --max-memory=16777216 --global-base=1024' failed (returned 1)
```

**Comment by sbc100** [comment]
Does this only also occur with you don't use LTO?

**Comment by sbc100** [comment]
This also looks like it might be specific to STANDALONE_WASM mode.. if you link to a `.js` file does the issue still occur?

**Comment by SaratAdiraj** [comment]
It occurs if I do not use LTO too.
It does not occur if i link to a .js file with -fexceptions

This works for js:
em++ hello.cpp -fexceptions -o hello.js

C:\emsdk>node hello.js
throw...
catch!

**Comment by SaratAdiraj** [comment]
> This also looks like it might be specific to STANDALONE_WASM mode.. if you link to a `.js` file does the issue still occur?

The following is the output :

em++ hello.cpp -fwasm-exceptions -o hello.js -flto

C:\emsdk>wavm run --enable all hello.wasm
Error loading WebAssembly binary file: Module was malformed: unknown section ID (13

C:\emsdk>node hello.js
failed to asynchronously prepare wasm: CompileError: AsyncCompile: Wasm decoding failed: unexpected section: <unknown> @+363
Aborted(CompileError: AsyncCompile: Wasm decoding failed: unexpected section: <unknown> @+363)
C:\emsdk\hello.js:141
      throw ex;
      ^

RuntimeError: Aborted(CompileError: AsyncCompile: Wasm decoding failed: unexpected section: <unknown> @+363)
    at abort (C:\emsdk\hello.js:1500:11)
    at C:\emsdk\hello.js:1685:7

**Comment by SaratAdiraj** [comment]
> The duplicate error occurs if I do not use LTO too.

The duplicate error occurs even if I do not use LTO .

**Comment by sbc100** [comment]
I don't know if wavm or node support wasm exception yet but it would appear that they don't (or at least the versions you are running do not).  Does that answer you question regarding running binaries produced with ` -fwasm-exceptions`?

It seems that the duplicate symbols error is due to STANDALONE_WASM mode (implied by `-o <foo>.wasm`).    Should we rename this issue `duplicate symbol when using -fwasm-exceptions with STANDALONE_WASM`?

**Comment by SaratAdiraj** [comment]
> I don't know if wavm or node support wasm exception yet but it would appear that they don't (or at least the versions you are running do not). Does that answer you question regarding running binaries produced with ` -fwasm-exceptions`?
> I will circle back with the other projects about this.  


> It seems that the duplicate symbols error is due to STANDALONE_WASM mode (implied by `-o <foo>.wasm`). Should we rename this issue `duplicate symbol when using -fwasm-exceptions with STANDALONE_WASM`?
done

**Comment by SaratAdiraj** [comment]
I have the following workarounds/fixes:

FIX/WORKAROUND 1: 
           step 1: Remove or comment out the offending functions in standalone.c file (__cxa_throw , __cxa_allocate_exception)
           step 2: Clear the cache be running "emcc --clear-cache" command
           step3: execute the command to compile in standalone mode "em++ -fwasm-exceptions test.cpp -o test.wasm -flto"
           step 4:  get the WAVM runtime from with the fix for supporting exception handling from https://github.com/SaratAdiraj/WAVM
           step 5: execute the command to run the wasm file "wavm run --enable all test.wasm"

FIX/WORKAROUND 2:  (without commenting out the offending functions)
           step 1: execute the command  "em++ -fwasm-exceptions test.cpp -flto"
           step 2:  get the WAVM runtime from with the fix for supporting exception handling from https://github.com/SaratAdiraj/WAVM
           step 3: execute the command to run the wasm file "wavm run --enable all a.out.wasm"
