### ISSUE TITLE
Clang asserts compiling LLVM with -fwasm-exceptions

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#15824]
Hi,

With the top of tree, and -fwasm-exceptions, I'm getting this assert with the attached `ll` input.  I assumed that code that compiled with "emscripten exceptions" would be ok with `-fwasm-exceptions` maybe that's a bad assumption.  The LLVM attached I could probably binary chop if you think it's too big.  To reproduce download the attachment, change the extension to `.ll` and run the command listed below.

Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.2-git (e4163cc2a5ea43a103dc8eda3c1b8620ec0d991e)
clang version 14.0.0 (https://github.com/llvm/llvm-project 1ba99eaf70951a4aa062688577047d8a23bfe54c)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: E:\GitHub\emsdk\upstream\bin
```

**Failing command line in full:**
```
emcc -fwasm-exceptions wasm_exceptions_fail.ll
```

```
E:\tmp>emcc -fwasm-exceptions wasm_exceptions_fail.ll
Assertion failed: R == 0 && "Already initialized this value register!", file C:\b\s\w\ir\cache\builder\emscripten-releases\llvm-project\llvm\include\llvm/CodeGen/FunctionLoweringInfo.h, line 209
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: E:/GitHub/emsdk/upstream/bin\\clang++.exe -target wasm32-unknown-emscripten -DEMSCRIPTEN -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=2 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=E:\\GitHub\\emsdk\\upstream\\emscripten\\cache\\sysroot -Xclang -iwithsysroot/include\\compat -fwasm-exceptions wasm_exceptions_fail.ll -c -o C:\\Users\\SCOTTW~1\\AppData\\Local\\Temp\\emscripten_temp_ncc4fh0n\\wasm_exceptions_fail_0.o
1.      Code generation
2.      Running pass 'Function Pass Manager' on module 'wasm_exceptions_fail.ll'.
3.      Running pass 'WebAssembly Instruction Selection' on function '@S_P_CoreLib_System_Runtime_EH__FailFastViaClasslib'
 #0 0x00007ff7cb2a1336 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x651336)
 #1 0x00007ff7ce37786b (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x372786b)
 #2 0x00007ff7ce36ce7c (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x371ce7c)
 #3 0x00007ff7ce36d430 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x371d430)
 #4 0x00007ff7ce36d35e (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x371d35e)
 #5 0x00007ff7cc67f665 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1a2f665)
 #6 0x00007ff7cc67e09f (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1a2e09f)
 #7 0x00007ff7cc67f4d5 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1a2f4d5)
 #8 0x00007ff7cc68022a (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1a3022a)
 #9 0x00007ff7cc666f0b (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1a16f0b)
#10 0x00007ff7cc5fd45b (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x19ad45b)
#11 0x00007ff7cc5fcf15 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x19acf15)
#12 0x00007ff7cc5f8e3c (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x19a8e3c)
#13 0x00007ff7cb7c2fa0 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0xb72fa0)
#14 0x00007ff7cb5014ae (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x8b14ae)
#15 0x00007ff7cae7c437 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x22c437)
#16 0x00007ff7cae838ac (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x2338ac)
#17 0x00007ff7cae7cb3a (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x22cb3a)
#18 0x00007ff7cbe47365 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x11f7365)
#19 0x00007ff7cc21af14 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x15caf14)
#20 0x00007ff7cc18a814 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x153a814)
#21 0x00007ff7cb3ea123 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x79a123)
#22 0x00007ff7cb478d8b (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x828d8b)
#23 0x00007ff7cac57ed3 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x7ed3)
#24 0x00007ff7cac54d04 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x4d04)
#25 0x00007ff7cbf51be6 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1301be6)
#26 0x00007ff7cb262682 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x612682)
#27 0x00007ff7cbf51871 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x1301871)
#28 0x00007ff7cb3af875 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x75f875)
#29 0x00007ff7cb3afd5b (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x75fd5b)
#30 0x00007ff7cb3c50f7 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x7750f7)
#31 0x00007ff7cac54505 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x4505)
#32 0x00007ff7ce358c24 (E:\GitHub\emsdk\upstream\bin\clang++.exe+0x3708c24)
#33 0x00007ffbd9777034 (C:\WINDOWS\System32\KERNEL32.DLL+0x17034)
#34 0x00007ffbd9962651 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x52651)
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project 1ba99eaf70951a4aa062688577047d8a23bfe54c)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: E:\GitHub\emsdk\upstream\bin
clang++: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
emcc: error: 'E:/GitHub/emsdk/upstream/bin\clang++.exe -target wasm32-unknown-emscripten -DEMSCRIPTEN -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=2 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=E:\GitHub\emsdk\upstream\emscripten\cache\sysroot -Xclang -iwithsysroot/include\compat -fwasm-exceptions wasm_exceptions_fail.ll -c -o C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp_ncc4fh0n\wasm_exceptions_fail_0.o' failed (returned 1)
```
[wasm_exceptions_fail.txt](https://github.com/emscripten-core/emscripten/files/7739433/wasm_exceptions_fail.txt)

**Comment by kripken** [comment]
Odd that the stack trace is mostly empty. Maybe that's a windows issue? When I compile your testcase using `tot` I get this:
```
$ ./emcc a.ll -fwasm-exceptions
clang++: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/include/llvm/CodeGen/FunctionLoweringInfo.h:209: llvm::Register llvm::FunctionLoweringInfo::InitializeRegForValue(const llvm::Value *): Assertion `R == 0 && "Already initialized this value register!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ -target wasm32-unknown-emscripten -DEMSCRIPTEN -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=1 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -fwasm-exceptions a.ll -c -o /tmp/emscripten_temp_8khjw2wo/a_0.o
1.	Code generation
2.	Running pass 'Function Pass Manager' on module 'a.ll'.
3.	Running pass 'WebAssembly Instruction Selection' on function '@S_P_CoreLib_System_Runtime_EH__FailFastViaClasslib'
 #0 0x00007fecd016ef43 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../lib/libLLVM-14git.so+0x1a37f43)
 #1 0x00007fecd016cd2e llvm::sys::RunSignalHandlers() (../lib/libLLVM-14git.so+0x1a35d2e)
 #2 0x00007fecd016e28d llvm::sys::CleanupOnSignal(unsigned long) (../lib/libLLVM-14git.so+0x1a3728d)
 #3 0x00007fecd008f963 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x00007fecd008fb0e CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007fecd61b38e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x138e0)
 #6 0x00007fecce11fe71 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #7 0x00007fecce109536 abort ./stdlib/abort.c:81:7
 #8 0x00007fecce10941f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #9 0x00007fecce10941f _nl_load_domain ./intl/loadmsgcat.c:970:34
#10 0x00007fecce1187f2 (/lib/x86_64-linux-gnu/libc.so.6+0x357f2)
#11 0x00007fecd096f3b3 llvm::FunctionLoweringInfo::InitializeRegForValue(llvm::Value const*) FastISel.cpp:0:0
#12 0x00007fecd0a643bb llvm::SelectionDAGBuilder::getValueImpl(llvm::Value const*) (../lib/libLLVM-14git.so+0x232d3bb)
#13 0x00007fecd0a64a32 llvm::SelectionDAGBuilder::getNonRegisterValue(llvm::Value const*) (../lib/libLLVM-14git.so+0x232da32)
#14 0x00007fecd0a6593f llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(llvm::Value const*, unsigned int) (../lib/libLLVM-14git.so+0x232e93f)
#15 0x00007fecd0a4ebda llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (../lib/libLLVM-14git.so+0x2317bda)
#16 0x00007fecd0af19b0 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, bool&) (../lib/libLLVM-14git.so+0x23ba9b0)
#17 0x00007fecd0af0e27 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (../lib/libLLVM-14git.so+0x23b9e27)
#18 0x00007fecd0aed504 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (../lib/libLLVM-14git.so+0x23b6504)
#19 0x00007fecd05b2cbe llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (../lib/libLLVM-14git.so+0x1e7bcbe)
#20 0x00007fecd02eacf8 llvm::FPPassManager::runOnFunction(llvm::Function&) (../lib/libLLVM-14git.so+0x1bb3cf8)
#21 0x00007fecd02f3581 llvm::FPPassManager::runOnModule(llvm::Module&) (../lib/libLLVM-14git.so+0x1bbc581)
#22 0x00007fecd02eb960 llvm::legacy::PassManagerImpl::run(llvm::Module&) (../lib/libLLVM-14git.so+0x1bb4960)
#23 0x00007fecd4d9974a clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::__2::unique_ptr<llvm::raw_pwrite_stream, std::__2::default_delete<llvm::raw_pwrite_stream> >) (../lib/libclang-cpp.so.14git+0x264674a)
#24 0x00007fecd5115496 clang::CodeGenAction::ExecuteAction() (../lib/libclang-cpp.so.14git+0x29c2496)
#25 0x00007fecd572dbc0 clang::FrontendAction::Execute() (../lib/libclang-cpp.so.14git+0x2fdabc0)
#26 0x00007fecd56aa05f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (../lib/libclang-cpp.so.14git+0x2f5705f)
#27 0x00007fecd57b20ab clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (../lib/libclang-cpp.so.14git+0x305f0ab)
#28 0x0000000000214725 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (clang+++0x214725)
#29 0x0000000000212470 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#30 0x00007fecd5363ee2 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#31 0x00007fecd008f877 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (../lib/libLLVM-14git.so+0x1958877)
#32 0x00007fecd5363a40 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >*, bool*) const (../lib/libclang-cpp.so.14git+0x2c10a40)
#33 0x00007fecd532f254 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (../lib/libclang-cpp.so.14git+0x2bdc254)
#34 0x00007fecd532f687 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__2::pair<int, clang::driver::Command const*> >&) const (../lib/libclang-cpp.so.14git+0x2bdc687)
#35 0x00007fecd5348adb clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__2::pair<int, clang::driver::Command const*> >&) (../lib/libclang-cpp.so.14git+0x2bf5adb)
#36 0x0000000000211a78 main (clang+++0x211a78)
#37 0x00007fecce10ae4a __libc_start_main ./csu/../csu/libc-start.c:314:16
#38 0x000000000020ed8a _start (clang+++0x20ed8a)
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project 1c66691ea770c2049bbc5a27fa6e998e01a7eaf8)
Target: wasm32-unknown-emscripten
Thread model: posix
```
cc @aheejin

**Comment by aheejin** [comment]
> I assumed that code that compiled with "emscripten exceptions" would be ok with `-fwasm-exceptions` maybe that's a bad assumption.

Yes, you need to use the same EH method for .c/cpp -> .ll compilation and .ll -> .o compilation. And the .ll file you uploaded was created by Emscripten EH.
So either of these will work:
```
emcc -fexceptions wasm_exceptions_fail.ll
```
or
```
emcc -s DISABLE_EXCEPTION_CATCHING=0 wasm_exceptions_fail.ll
```
(`-fexceptions` uses the default EH, which is Emscripten EH at the moment.)

**Comment by yowl** [comment]
The file I uploaded was created by me, via libLLVM, so you are saying my LLVM is not correct for wasm exceptions?  Is there any documentation about what the LLVM should look like to take advantage of wasm exceptions, i.e. where it needs to differ?

**Comment by yowl** [comment]
or maybe a better question would be is there some input that is ok for `llc -exception-model=wasm` that I can use to compare?

**Comment by yowl** [comment]
Ok, I found https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/WebAssembly/wasm-eh.ll which I think is good for me.  Thanks!

**Comment by aheejin** [comment]
https://emscripten.org/docs/porting/exceptions.html explains the two ways (Emscripten EH and Wasm EH) of doing EH in Emscripten. You pass either `-fexceptions` or `-fwasm-exceptions`, but you need to use the same flag if you want to stop at the bitcode stage.

**Comment by yowl** [comment]
Yep, thanks.  I should have said up front that I'm creating LLVM bitcode from c#, then using emscripten to go from there.  I want to move the C# compiler over to wasm exceptions and the test case and LLVM docs should give me enough to know how I should alter the LLVM generation.

**Comment by aheejin** [comment]
Which C# compiler are you using? I don't think there is a C# compiler that support Wasm exceptions now.

**Comment by yowl** [comment]
No, there isn't yet.  I contribute to NativeAOT-LLVM (https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM) and I'll be changing it to support Wasm exceptions.

**Comment by aheejin** [comment]
I see. I don't think the task will be trivial though. First of all, Wasm frontend in LLVM uses [Windows EH instructions](https://llvm.org/docs/ExceptionHandling.html#exception-handling-using-the-windows-runtime), which consists of `catchswitch`/`catchpad`/`catchret`/`cleanuppad`/`cleanupret`. This doesn't mean Wasm EH runs only on Windows or anything. Those IR instructions were first invented by Windows EH guys so that's I call it Windows EH instructions, but it is just a different set of instructions that can support EH. Especially, it is good at describing scoping relationship.

It would be necessary to understand https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGException.cpp and  possibly https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/CGCleanup.cpp. CGEcxeption.cpp is where we generate EH instructions. I don't recall we made nontrivial changes, if any, to CGCleanup.cpp, but it is used with CGException.cpp so it might be necessary to know what it is about. Search for "Wasm" in CGException.cpp can yield what kind of wasm-specific modifications we made for Wasm EH to use Windows EH instructions. I'm not sure how NativeAOT-LLVM uses the upstream LLVM and how much change you would need to make to use it though.

**Comment by yowl** [comment]
Ok, thanks a lot for the links, as a part timer I need all the help I can get :-).  I will read them to help my understanding.  I don't think dotnet/C# can rely too much on the semantics of C++ exceptions as the filter handling is different I believe (and currently not working with emscripten exceptions either) so it has its own first and second pass handlers to identify and call the correct catch block.   There may be something good to come out of that if the LLVM implementation is more aligned with windows.  I don't know enough about it yet to say.

https://stackoverflow.com/questions/57544142/in-c-sharp-try-finally-how-to-catch-the-original-exception/57544409#57544409 describes some of the less obvious behaviour.

 If I get something going I'll post back here.

**Comment by aheejin** [comment]
So if you compile with Emscripten EH, it will generate Itanium-style EH instructions, which include `landingpad`. Some of that stuff is explained in https://llvm.org/docs/ExceptionHandling.html#llvm-code-generation. This EH is more widely used, meaning, more targets in the LLVM backend use this Itanium-style EH instructions. And for Emscripten EH we do our own lowering in https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp. This file is very long because it contains Emscripten EH, Emscripten SjLj, and also some of Wasm SjLj stuff (SjLj handling using Wasm EH), but I don't think you need to know what this file does, because this happens in the backend, and as long as you can produce Itanium-style (`landingpad`-based) ll files, you can just use our backend to make Emscripten EH work. If your frontend at least support the Itanium EH this will be not very difficult I think.

Making Wasm EH work involves generating Windows EH instructions from the frontend, which will be trickier if your compiler doesn't support it, and that's what I described in my previous comment.

For the example in https://stackoverflow.com/questions/57544142/in-c-sharp-try-finally-how-to-catch-the-original-exception/57544409#57544409 that `catch` has a condition function, [Our current proposal](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md) doesn't provide a way to directly encode that in the low level instructions. (There was a discussion about that but I'm not sure if or when that will ever happen at this point) But we can always catch, and within the catch block, we check the function and if it is not satisfied we can rethrow.

**Comment by yowl** [comment]
Thanks, one last thing before I start hacking away.  

https://github.com/llvm/llvm-project/blob/13992498cd96dcef34cdf1ff02730d266feb0730/clang/lib/CodeGen/CGException.cpp#L1035-L1045

This call which can compile to
```
  %33 = call i32 @llvm.wasm.get.ehselector(token %31)
```
If there's only one catch block then its not used, so would it be a problem to drop it?

**Comment by aheejin** [comment]
What do you mean by only one catch block? In C++, it wouldn't be used in `catch (...)`, but will be used in other `catch` clauses. Even if there's only one catch block, say, `catch (int n)`, we still need to test if the currently caught exception matches the typeinfo for `int`.

In `catch (...)`, I think that and also `llvm.wasm.get.exception`, can be dropped.

**Comment by yowl** [comment]
Yes sorry, you are right of course.
