### ISSUE TITLE
Closure compiler and inline JS

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#15832]
After enabling closure compiler on my code, I am facing `undefined variable` errors for my inline JS code. I can see the reason to be minification of the variables that I want to use from the JS code. What is the ideal way to handle this i.e. use variables from JS side in the inline JS (c++) with closure compiler ON ?

**Comment by sbc100** [comment]
If you use `EM_JS` and `EM_ASM` your code should be run through closure with the rest of the code.

If you want to use variables from code that is not run through closure (i.e. code external the main module JavaScript) then I think you would need to export those symbols using `EXPORTED_FUNCTIONS=foo,bar,baz` and then run them as `Module.foo`, etc, just like you would do from external code living in different JavaScript files.

**Comment by sbc100** [comment]
Alternatively I think maybe you could try using a closure externs file and pass that via `--closure-args` on the emcc on the command line.   See https://developers.google.com/closure/compiler/docs/externs-and-exports
