### ISSUE TITLE
error with  std::vector<std::map<std::string,std::string>> when call operator "[]" of map

### ISSUE THREAD

**Issue by Mr-shadow** [emscripten-core/emscripten#15856]
emscripten virsion:
`
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1 (5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2)
clang version 14.0.0 (https://github.com/llvm/llvm-project d98dfb2baabb647a6ac4c4f4399999cfc44433db)
Target: wasm32-unknown-emscripten
Thread model: posix
`

my cpp code is :
```
void test_func()
{
	std::vector<std::map<std::string, std::string>> vecMapStr(2, std::map<std::string, std::string>());
	std::map<std::string, std::string> mapStr;
	vecMapStr[0]["a"] = "lidi";
	vecMapStr[0]["b"] = "lishifu";
	vecMapStr[0]["c"] = "liniupi";
	std::map<std::string, std::string> mapStr1;
	mapStr1["a"] = "lidi01";
	mapStr1["b"] = "lishifu01";
	mapStr1["c"] = "liniupi01";
	vecMapStr[1] = mapStr1;
	for (auto _map : vecMapStr)
		for (auto _pair : _map)
			EM_ASM({
				console.log("test -->" + $0 + ":" + $1);
			},
				   _pair.first, _pair.second);
}

EMSCRIPTEN_BINDINGS(stl_wrappers)
{
	register_vector<std::map<std::string, std::string>>("VectorTag");
	register_map<std::string, std::string>("MapString");

	function("test_func", &test_func);
}
```

and my shell command is

```emcc .\xx.cpp -o xx.js --std=c++14 --bind -O3```

and this error occured:

cannot pass object of non-trivial type 'const std::string' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                                   _pair.first, _pair.second);

what should i do for this?

**Comment by sbc100** [comment]
Basically, the `embind` bindings have no effect on `EM_ASM`.    You can only pass raw low level types to to `EM_ASM` because it uses varargs.  Kind of like printf.   For example you could pass the raw poiner to the C string and then to `UTF8ToString` at on the JS side:

```
EM_ASM({
				console.log("test -->" + UTF8ToString($0) + ":" + UTF8ToString($1));
			},
				   _pair.first.c_str(), _pair.second.c_str());
```

**Comment by sbc100** [comment]
@RReverser please correct me if I'm wrong.. I know you did some work to help join these two worlds recently.

**Comment by Mr-shadow** [comment]
thank you! 
In fact, I am trying to use ```std::map<std::string,std::string>``` in webassembly, i would prase the data witch passed by javascript in my cpp code, like this:
```
bool checkFunc(std::vector<std::map<std::string,std::string>> data)
{
     for(auto _mapdata :data)
         if(std::stoi( data['someKey']) < 100)
             return false;
     return true;
}
```
 i build MapString in javascript successfully, but this error attached in run time:  
"stoi : no conversion. " so i write the above test_func to make sure I send right data.   
for this, should i change my data structrue like  ```std::map<char*, char*>```?

**Comment by Mr-shadow** [comment]
thank you!
