### ISSUE TITLE
TypeError: WebAssembly.instantiate():Import #0 module="a" error :module is not an object or function

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#15853]
`function loadWebAssembly (url) {
	  return fetch(url).then(response =>
		response.arrayBuffer()
	  ).then(bytes =>
		WebAssembly.instantiate(bytes,{})
	  ).then(result =>
		result.instance
	  );
    }`
and use it 
`loadWebAssembly('./Decoder.wasm').then(instance => {
                   	Module = instance.exports;
					PlayM4_Init();
					PlayM4_Play();
                });`

there is error , 'module is not an object or function' ?

**Comment by sbc100** [comment]
The means you are providing the modules exported imports.   It looks like the module here is expecting something called `a` but you are not providing any imports at all (only the empty object `{}`).

It looks like you might be trying to instantiate a WebAssembly module build using emscripten, but without using the emscripten-generated JavaScript.   If you want to do this you will need to provide implementations of all the JS functions that emscripten would normally provide to the module.  While not impossible, this is quite complex and requires understand fair amount of internal details.   Unless you really want to do this I would suggest using the JS generated by emscripten (e.g. `-o Decoder.js`).
