### ISSUE TITLE
Bug in page:Glossary 

### ISSUE THREAD

**Issue by yihonglyu** [emscripten-core/emscripten#15852]
The link https://github.com/emscripten-core/emscripten/blob/main/tools/nativize_llvm.py of https://emscripten.org/docs/site/glossary.html#term-llvm-nativizer is no longer valid.

URL: ../../docs/site/glossary

**Comment by sbc100** [comment]
If you have time, you like to upload a PR to remove this entry?

**Comment by eleensmathew** [comment]
Hi i would like to work on this issue. Please assign this to me and since I've not resolved a bug before please guide me.

**Comment by sbc100** [comment]
It looks like the solution is simply to remove the glossary entry for LLVM Nativizer from site/source/docs/site/glossary.rst.

**Comment by eleensmathew** [comment]
i have removed the glossary entry for LLVM Nativizer. Please review my pull request.

**Comment by eleensmathew** [comment]
I have removed the glossary item. Please review my pull request.
