### ISSUE TITLE
Example Links in Documentation Broken

### ISSUE THREAD

**Issue by conorpo** [emscripten-core/emscripten#15865]
**Documentation Error**

In the [Building Projects](https://emscripten.org/docs/compiling/Building-Projects.html) page, under the ["Examples / test code"](https://emscripten.org/docs/compiling/Building-Projects.html#examples-test-code) heading, the examples listed don't link to the correct project folder, instead the link to some sort of testing folder associated with the project. I'm not sure if this issue is on other pages as well.

**Comment by conorpo** [comment]
#15866

**Comment by kripken** [comment]
Fixed by that PR.
