### ISSUE TITLE
Compiling the libntru library with emcc for use in emscripten project fails

### ISSUE THREAD

**Issue by Lucaskyy** [emscripten-core/emscripten#15863]
Hi there, I'm trying to compile [`libntru`](https://github.com/tbuktu/libntru) to WASM, so I can use it in the browser.
It's made in C, but unfortunately uses GCC extensions (such as `__builtin_cpu_supports`. this is called at compile time) which caused `emcc` to fail. After removing them, I got it to compile the C files. But `libntru` also contains Assembly source (`*.s`) files which it tries to compile to object files (`*.o`), but this completely breaks with errors such as: `invalid alignment value`, `unexpected token`, `invalid instruction` and more.

Compiling `libntru` with `gcc` does work though, just not with `emcc`.

Is it even possible to compile this library, or should I just give up on this?

**Comment by Lucaskyy** [comment]
Here are 2 screenshots showing what happens with the source files.

compiling with `gcc`, works fine:
![gcc](https://i.imgur.com/MM5IhiZ.png)

compiling with `emcc`, doesn't work: (there are at least 1000 errors below this image, this is just a snippet of the top)
![emcc](https://i.imgur.com/nhhMGx5.png)

**Comment by kripken** [comment]
Assembly files for x86_64 can't be compiled to wasm. Hopefully the project has an option to use portable code instead?

**Comment by Lucaskyy** [comment]
`libntru` on WASM was a lost cause. We switched over to `NTRUEncrypt` instead and that worked flawlessly.
