### ISSUE TITLE
externref/funcref support

### ISSUE THREAD

**Issue by kg** [emscripten-core/emscripten#15878]
Does emscripten expose support for externref and funcref? If not, is there a plan to eventually expose it? It's not clear to me how I would generate special wasm opcodes and then wrap them in a callable C function via the way emscripten is currently set up - i.e. an EM_WASM equivalent of EM_ASM, or something.

**Comment by kripken** [comment]
@pmatos is working on this in LLVM and can hopefully provide more details. I believe this has a summary of the plans: https://github.com/Igalia/ref-cpp

I imagine that eventually we'd try to find a way to integrate that with EM_ASM, embind, etc., but I don't think there are concrete plans atm.

**Comment by sbc100** [comment]
I imagine it will be possible to write functions `.s` or `.S` files way before any other higher level solutions exist.   It sounds like that would be enough for your use case and it may well work already.   I will see if I can add a simple test/example of this..

**Comment by pmatos** [comment]
@kg  we are working on integrating this into LLVM and hopefully it should make its way later to emscripten.

As @sbc100 said, I think if you can for now write some parts (which use externref/funcref) in wasm or even llvm ir, you could potentially already get it to work. Take a look at the wasm and ll files here: https://github.com/Igalia/ref-cpp/tree/main/milestones/m3 and feel free to let me know if there's anything you are missing or have any further questions.

**Comment by sbc100** [comment]
I've added an example of how to use externref from assembly code: #15913.. is that enough to satisfy your use case @kg ?

**Comment by kg** [comment]
Absolutely, thank you both. I'll post here if I hit any problems when prototyping with it later.
