### ISSUE TITLE
WasmFS: Design for persistent backends

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#15946]
There are a number of open questions about how persistent storage should work in WasmFS:

1. How should persisted directory entries refer to files in other backends?

2. What happens when a directory entry references a persisted file that no longer exists?

3. Should the user be responsible for recreating the backends necessary to read persisted data or should the system somehow create the backends automatically?

4. What happens when the data format a backend uses changes?

5. What additional backend APIs will we need to allow backends to create meaningful names for persisted files?

**Comment by curiousdannii** [comment]
I want to make a FS that connects to Dropbox. Would that be classified as "persisted"?

**Comment by tlively** [comment]
Yes, because there might be data already there and ready to open on application startup.

**Comment by mere-human** [comment]
Will the backend API be officially available for external usage?
