### ISSUE TITLE
WasmFS: Node FS backend

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#15941]
Add a concrete WasmFS backend for managing files via Node's file system APIs, analogous to [NODEFS](https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-nodefs).

Depends on #15946.

**Comment by kripken** [comment]
Thinking about this, I wonder if our current backend API is enough for NODEFS etc.

Current state: Backends define `createFile` (and directory and symlink). When the open syscall fails to find a file already present on the parent directory, it calls that method on the backend. Then it creates a generic OpenFileState for it etc.

Perhaps we should also have backends define `openFile`, and allow them to create a subclass of OpenFileState. Doing so would let NODEFS mirror the WasmFS state onto node file operations: when a file is opened in WasmFS, we'd open it in node, and when it is closed in WasmFS we'd close it in node as well. Without adding something like this, all a backend defines is a custom `File` structure, but that stays around forever and there is no signal as to when it is closed.

**Comment by tlively** [comment]
Backends can override the `File` constructor and destructor to implement custom logic for opening and closing files.

**Comment by kripken** [comment]
Sorry if I wasn't clear. There is a single `File` for a particular file. That is create once and never destroyed. But we can create and destroy multiple `OpenFileState`s for that file, say if we open it, write, close it, then much much later open it again. So if we want to track that behavior, we'd need to customize the latter.

In practical terms: In the constructor of `File` we don't know the flags the file is opened in (writing? reading?), and even if we did, they would be constant forever. So we can't open the file using Node.js APIs at that time. We would need to say open it and close it immediately in each write syscall, which doesn't sound good. Does that make more sense now?

**Comment by tlively** [comment]
Oh right, my bad. The `File` destructor is for deleting files, not just closing them. Letting backends provide custom `OpenFileState`s would be one solution, but another option would be for `File` to have open and close hooks that backends could override. I think the hooks would probably be the simpler option since they don't have the overhead of defining a full new class and adding a new top-level function to the backend interface.

**Comment by kripken** [comment]
Interesting, what would those hooks look like? Receiving the OpenFileState perhaps? I think that might work.

> The File destructor is for deleting files, not just closing them

I'm not sure that's accurate. A File object represents a file, but is not necessarily tied to the underlying file's lifetime. For example, the underlying file on Node might remain on the user's drive, but when the wasm program shuts down all destructors are called - we wouldn't delete the file at that time. I think this is separate from the issue of persistence. But, maybe our design here is not clear enough yet.

**Comment by tlively** [comment]
Yep, definitely not clear enough. The JS backend, for instance, overrides the destructor to actually delete files, and I would have expected other backends to do the same. You're right that that doesn't work at all if a file is meant to outlive the process, though.

**Comment by tlively** [comment]
Oh, and I would expect the hooks to just look something like this:

```
File::registerOpen(token, <... same arguments passed to open syscall ...>);
File::registerClose(token);
```

Where there is some sort of token for pairing opens with closes, possibly the `OpenFileState` or maybe just it's address. This also made me think of whether we would want to notify backends of `dup` events, but I can't think of a use case for that.

**Comment by kripken** [comment]
> The JS backend, for instance, overrides the destructor to actually delete files

Interesting, I had forgotten that. Yes, I think that behavior makes sense - we want to keep the JS side alive exactly while the C++ can access it. I guess each backend will just do what the right thing for it, then. For NODEFS, we don't want the destructor to actually tell Node.js to delete the file, and so we'll need to have a hook for `delete()` I guess, like for `open()`. So deletion will happen on user indication of deletion, and not cleanup of the object. And the difference makes sense because the JS backend's File keeps the JS alive, while in Node, the actual storage has a separate existence.

> `File::registerOpen(token, <... same arguments passed to open syscall ...>);`
> `File::registerClose(token);`

If the token is a reference to the OpenFileState, as you suggest, than I think we don't need the arguments to open? The caller could get them from the OpenFileState.

This API makes sense I think. It does mean that when we want to keep info around for an OpenFileState that we'd have a map from those addresses to the extra info, which adds an extra indirection and overhead. But that's probably fine I think.

**Comment by tlively** [comment]
> If the token is a reference to the OpenFileState, as you suggest, than I think we don't need the arguments to open? The caller could get them from the OpenFileState.

This is a possibility, but would make backends implemented in JS or other external languages more complex because we would have to expose an API for querying `OpenFileState` objects to them.

**Comment by kripken** [comment]
Good point, it might. I don't have a clear picture yet for how a JS impl of a backend would look

**Comment by tlively** [comment]
I think we would have a wrapper C++ backend that implements all the backend functions in terms of function pointers it has received from JS.

Another point is that we've said we want the file names  in the NodeFS and OPFS backends to match the filenames used by WasmFS. Right now file names are never exposed to the backends, so this isn't possible. We will probably want to add more backend event notification functions for creating a new file and for renaming files so the names can be kept in sync.

**Comment by kripken** [comment]
This has been implemented:



* JS side: https://github.com/emscripten-core/emscripten/blob/main/src/library_wasmfs_node.js
* C++ side: https://github.com/emscripten-core/emscripten/blob/main/system/lib/wasmfs/backends/node_backend.
* NODERAWFS integration: https://github.com/emscripten-core/emscripten/blob/main/system/lib/wasmfs/backends/noderawfs_root.cpp
