### ISSUE TITLE
WasmFS: OPFS AccessHandles backend

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#15950]
We should write a new WasmFS backend using OPFS AccessHandles to provide efficient access to the native file system.

Depends on #15946.

**Comment by tlively** [comment]
The error handling issue has been fixed and the OPFS backend is generally usable now.

**Comment by rulkens** [comment]
Is there any documentation on this? I've looked in the emscripten docs but I can't find any info about it (https://emscripten.org/docs/api_reference/Filesystem-API.html#file-system-api). I'd love to use it for my custom PNG encoder wasm implementation.

**Comment by hangxingliu** [comment]
@rulkens coincidence, i am also looking for it for a better data persistence process. I found that there is a good example c source code, which can be used as a documentation at <https://github.com/emscripten-core/emscripten/blob/main/test/wasmfs/wasmfs_opfs.c>
