### ISSUE TITLE
WasmFS: `fcntl`

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#15970]
[man page](https://man7.org/linux/man-pages/man2/fcntl.2.html)

**Comment by kripken** [comment]
Initial pipe/poll support does not yet include fcntl. When we implement fcntl we should enable the relevant parts of the test that are being disabled in https://github.com/emscripten-core/emscripten/pull/16391

**Comment by kripken** [comment]
https://github.com/emscripten-core/emscripten/blob/4020709cc54160996bc539e30164b0d22c3933b0/system/lib/wasmfs/file_table.h#L71-L73

However, fcntl has `F_SETFL` which can set the flags. Should I change the file table to that, or am I missing something? (Just checking if there was a strong reason to assume it would never change.)

**Comment by tlively** [comment]
Sounds like we should update the file table implementation to put the flags behind the lock. We probably just didn't know changing them was possible when we wrote that.

**Comment by kripken** [comment]
Got it, thanks!
