### ISSUE TITLE
Intercepting syscalls conditionally

### ISSUE THREAD

**Issue by rstz** [emscripten-core/emscripten#16022]
Prior to the change in [15202](https://github.com/emscripten-core/emscripten/pull/15202), the PThreadFS library would intercept syscalls like this:
```
long __syscall10(long path) {  // Using unlink as an example.
  if (is_pthreadfs_file(path)) {
    // Do something special...
    return 0;
  }
  // On a non-pthreadfs file, use the normal Emscripten FS implemented in Javascript.
  return __sys_unlink(path);
}
```
With the renaming in [15202](https://github.com/emscripten-core/emscripten/pull/15202), this trick no longer works, since both the intercepted syscall (in C++) and the Javascript call have the same name (`__syscall_unlink` in our example). Is there a way to still intercept syscalls nicely?

**Comment by sbc100** [comment]
I, this came up the other day and I believe it should be possible to do it like this:

```
EM_IMPORT(__syscall_unlink)  long __env_syscall_unlink(long path);
long __syscall_unlink(long path) {
  ...
  return __env_syscall_unlink(path);
}
```

I've not confirmed that this worked by I see no reason why it shouldn't.   I guess we should add a test for this kind of thing if its happening in the wild.

**Comment by sbc100** [comment]
BTW, EM_IMPORT here just expands to llvm attributes. e.g. `__attribute__((import_module("env"), import_name("__syscall_unlink")))`

**Comment by rstz** [comment]
Works like a charm, thank you very much!
