### ISSUE TITLE
emscripten's C library sets __progname to NULL

### ISSUE THREAD

**Issue by guijan** [emscripten-core/emscripten#16037]
It seems emscripten's libc sets __progname to NULL.

I've created a repository with a test for this: https://github.com/guijan/emscripten-bug/
It's just a single .c source file that triggers the bug and a Github Action that compiles and runs it.

Here's the Github Action's output: https://github.com/guijan/emscripten-bug/runs/4826341202?check_suite_focus=true

**Comment by sbc100** [comment]
Indeed it looks like we compile libc.c but we never set this to anything else:

https://github.com/emscripten-core/emscripten/blob/583000b8e2431e7d97ccd850ea656ed9285b7eb5/system/lib/libc/musl/src/internal/libc.c#L6

Do you have code that uses this symbol?  (If its open source could you link to it maybe?).   I don't believe its covered by any kind of stadard.. so I'm not sure how much effect we should expend it attempting to support?

**Comment by guijan** [comment]
Thanks for pointing out that Javascript variable, I wrote a kludge that uses a clang extension to initialize __progname: https://github.com/guijan/libobsd/blob/ba0c4bc5d685f60f034158732ff9724feba85b47/src/stdlib/getprogname_emscripten.c
That way emscripten's err() works and I don't need to provide my own err().

As it currently stands there's the issue that 2 public emscripten APIs (err.h and program_invocation_short_name) don't work though.

**Comment by sbc100** [comment]
Yes, if we can find a cost-free way to fix the issue (where programs that don't directly depend on __progname don't end up pulling in malloc and free).  That would be great.  Perhaps we can even use the static ctor and dtor trick in `lib.c`?

**Comment by sbc100** [comment]
I'll mark as help wanted and good first bug in case anyone wants to look into that option.
