### ISSUE TITLE
3.1.1 doesn't build: SmallBuffer’ may be used uninitialized

### ISSUE THREAD

**Issue by svenstaro** [emscripten-core/emscripten#16040]
Full log including all used versions attached. seems to me like a problem while compiling llvm with the provided options. Not sure why that's suddenly a problem to be honest. Previous versions compiled just fine.
[emscripten.log](https://github.com/emscripten-core/emscripten/files/7875913/emscripten.log)

**Comment by kripken** [comment]
This seems like a problem in upstream LLVM, and some bad interaction between it and your local system compiler. I'd suggest [opening an LLVM bug](https://github.com/llvm/llvm-project/issues).

**Comment by svenstaro** [comment]
Hm turns out this is an LTO issue for some weird reason. Nevermind.
