### ISSUE TITLE
uncaught runtimeerror: index out of bounds

### ISSUE THREAD

**Issue by RavikumarTulugu** [emscripten-core/emscripten#16080]
I am new to emscripten and trying to port a game, the game runs fine till some time and then i see this on console. The crash is at random places at different times. I understand that this is some kind of guard put in place and not a bug.  please advise on how and why this happens ?? 
my settings are like these 
-s TOTAL_STACK=128MB -s INITIAL_MEMORY=256MB -s ALLOW_MEMORY_GROWTH=1

**Comment by kripken** [comment]
That may be a bug somewhere, for example memory corruption. The best thing is usually to try the sanitizers to see if they find anything:

https://emscripten.org/docs/debugging/Sanitizers.html

If that doesn't help, more ideas are here:

https://emscripten.org/docs/porting/Debugging.html

**Comment by RavikumarTulugu** [comment]
i will try the sanitizer and get back.
