### ISSUE TITLE
lengthBytesUTF8 not in EXPORTED_RUNTIME_METHODS

### ISSUE THREAD

**Issue by behunin** [emscripten-core/emscripten#16098]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.2 (a77b559a8b40b7e89fc8c17e41034128df9543e4)
clang version 14.0.0 (https://github.com/llvm/llvm-project 782c0dd1a1c235afb09a34e7da4a1267ead14765)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/lev/emsdk/upstream/bin

**Failing command line in full:**

target_link_options(wexiv PUBLIC
        --bind
        --no-entry
        --js-library ${PROJECT_SOURCE_DIR}/library/getmeta.js
        -sALLOW_MEMORY_GROWTH
        -sEXPORT_ES6
        -sEXPORT_NAME=wexiv
        -sEXPORTED_RUNTIME_METHODS=["stringToUTF8", "lengthBytesUTF8"]
        -sMODULARIZE
        -sNO_FILESYSTEM
        -sLLD_REPORT_UNDEFINED
        -Wl,-error-limit=0
        -v
    )

 When I set option: -sEXPORTED_RUNTIME_METHODS=["stringToUTF8", "lengthBytesUTF8"]
It fails to add lengthBytesUTF8 to the output.

**Full link command and output with `-v` appended:**
```
[build]  "/home/lev/emsdk/node/14.18.2_64bit/bin/node" /home/lev/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpy69u7qdt.json
[build] warning: invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: ;lengthBytesUTF8;
[build]  "/home/lev/emsdk/upstream/bin/wasm-ld" -o ../bin/wexiv.wasm -error-limit=0 CMakeFiles/wexiv.dir/wexiv.cpp.o ../lib/libexiv2.a ../lib/libstaticXMPCore.a ../lib/libz.a /home/lev/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a -L/home/lev/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmplapg9s9c.undefined --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=malloc --export=free --export=_get_tzname --export=_get_daylight --export=_get_timezone --export=setThrew --export=__cxa_is_pointer_type --export=__cxa_can_catch --export=ntohs --export=htons --export=emscripten_main_thread_process_queued_calls --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024
[build]  "/home/lev/emsdk/upstream/bin/wasm-emscripten-finalize" --minimize-wasm-changes -g --dyncalls-i64 --dwarf ../bin/wexiv.wasm -o ../bin/wexiv.wasm --detect-features
[build]  "/home/lev/emsdk/node/14.18.2_64bit/bin/node" /home/lev/emsdk/upstream/emscripten/src/compiler.js /tmp/tmp11zzo1c9.json
[build] warning: invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: ;lengthBytesUTF8;
[build]  "/home/lev/emsdk/upstream/bin/llvm-objcopy" ../bin/wexiv.wasm ../bin/wexiv.wasm --remove-section=producers
```

**Comment by kripken** [comment]
Please provide a full testcase, as this works for me, and I don't see any problem in the code. Here is what I did:
```
$ ./emcc -sEXPORTED_RUNTIME_METHODS=stringToUTF8,lengthBytesUTF8 tests/hello_world.c -O3 -g1
$ grep lengthBytesUTF8 a.out.js
function lengthBytesUTF8(str) {
Module["lengthBytesUTF8"] = lengthBytesUTF8;
```
That builds hello world with your relevant -s flag. The last line shows the function in the output, and properly exported.

**Comment by sbc100** [comment]
Its probably an issue with the quoting in your build file.  Try the new syntax which avoids quotes an brackets:

`-sEXPORTED_RUNTIME_METHODS=stringToUTF8,lengthBytesUTF8`

**Comment by behunin** [comment]
> 

This solved the problem for me. Thank you!
