### ISSUE TITLE
Installation on windows 10 fails

### ISSUE THREAD

**Issue by ifcquery** [emscripten-core/emscripten#16137]
**Version of emscripten/emsdk:**
'3.1.2'

**Failing command line in full:**
>emsdk activate latest
Resolving SDK alias 'latest' to '3.1.2'
Resolving SDK version '3.1.2' to 'sdk-releases-upstream-6626e25d6d866cf283147ca68d54ac9326fe399f-64bit'
error: error: tool is not installed and therefore cannot be activated: 'node-14.18.2-64bit'

OS: Windows 10 x64
"node-14.18.2-64bit" is actually installed.

**Comment by sbc100** [comment]
Did you run `emsdk install latest` first?
