### ISSUE TITLE
feature help: target to WXAssembly 

### ISSUE THREAD

**Issue by Jeff-Tian** [emscripten-core/emscripten#16153]
I can run c++ programs in the browser by running

```
emcc main.cpp -o index.html
```

The glew js file works in the browser perfectly.

However, if I want the same `wasm` file to be running in the "Wechat Mini Program", then I need to do many tweaks to the glew js file to make it work, as the "Wechat Mini Program" doesn't have a "WebAssembly" object. Instead, they provide a similar "WXAssembly" object (https://developers.weixin.qq.com/miniprogram/dev/framework/performance/wasm.html). 

Besides the renaming, there are many other trival tweaks need to be done. Since the mannual work is not fun, is that possible we add a feature to the `emcc` to target the "WXAssembly" runtime?

I want to add the feature, so I think I need to go through the "glew js" generating logic first. I checked the "glew js" file is very similar to "https://github.com/emscripten-core/emscripten/blob/581d2aedaccb779b71bb31815353f330edebc0e2/src/library_dylink.js", but didn't find any specific logic relates to the "library_dylink.js" file.

I aslo checked the tests folder, and didn't find any tests is referencing "library_dylink.js". 

Is anyone familiar with that "library_dylink.js" file? Could you please help elaborate more on it?

Thanks in advance!

**Comment by Jeff-Tian** [comment]
The tweaks can be summarized as the following line:

```
const converted = text.replace(/WebAssembly/g, 'WXWebAssembly').replace('self.location.href', '(self || this).location.href').replace(/return getBinaryPromise\(\)\.then\(.+?\}\)/s, `return WXWebAssembly.instantiate('/pages/wasm/hello.wasm', info)`).replace('instantiateAsync();', 'instantiateArrayBuffer(receiveInstantiationResult);');

```

As the tweaks work for now, so it's not urgent to implement the feature into emcc.

**Comment by aizigao** [comment]
@Jeff-Tian 666 打call

**Comment by Yongle-Fu** [comment]
does anything update

instantiateAsync(wasmBinary, wasmBinaryFile, info, receiveInstantiationResult)

**Comment by Yongle-Fu** [comment]
which ENVIRONMENT should be used in WXWebAssembly
```js
var ENVIRONMENT_IS_WEB = typeof window == "object";
var ENVIRONMENT_IS_WORKER = typeof importScripts == "function";
var ENVIRONMENT_IS_NODE = typeof process == "object" && typeof process.versions == "object" && typeof process.versions.node == "string";
var ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
```

**Comment by ctxqlxs** [comment]
any update?

**Comment by aizigao** [comment]
It time to share my solution, I use uniapp


1. 强制使用 envionment 为 woker, 其他的感觉用处不大，再加上导出为 esm
其中

```shell
emcc \
-o wasm/yourTargetName.js \
-s WASM=1 \
-s "EXPORTED_RUNTIME_METHODS=['ccall']" \
-s EXPORTED_FUNCTIONS="['youTargetFnName','_malloc','_free']" \
-s ALLOW_MEMORY_GROWTH=1 \
-fsanitize=address \
-sABORTING_MALLOC=0 \
-sENVIRONMENT=worker
```

2. wasm 文件很大，所以需要将wasm 或 wasm.br 文件放到subPackage 分包中
3. 然后修改 生成的 yourTargetName.js 胶水代码
**WebAssembly 为 WxWebAssembly**
```js
var WebAssembly = WXWebAssembly;
WebAssembly.RuntimeError = Error;
```
**加载入口修改**
```js
var wasmBinaryFile;
wasmBinaryFile = "pages-sub/youPath/wasm/yourTargetName.wasm.br";
```
 搜索 `else  if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER)` 下的 都是 加载wasm 的代码，小程序中是不需要的，都部干掉
 
 
![image](https://github.com/user-attachments/assets/eafa6841-0be3-41b0-8ab8-141e5e579877)

**找到实际加载代码 , 搜索 WebAssembly.instantiate **
![image](https://github.com/user-attachments/assets/0b4f848b-75f2-4381-a293-5fe2596d4690)

干掉 getBinaryPromise, 这个是多余的，修改为
![image](https://github.com/user-attachments/assets/61799837-5bde-4092-a973-36f1ccb6e108)


WasmOffsetConverter 是不支持的方法 需要移除
![image](https://github.com/user-attachments/assets/fc691a50-d856-474f-8d49-a71b0095e0d9)

搜索convertFrameToPC,注释掉这个assert

![image](https://github.com/user-attachments/assets/0bfd7e3f-83a5-44b8-ae81-04c52dac695c)


4. worker 存放目录为 src/workers, uniapp 不会打包 workers，也不会复制wasm 文件，需要建一个 vite.worker.config, 如下
```
import path from 'node:path'
import { viteStaticCopy } from 'vite-plugin-static-copy'
import { defineConfig } from 'vite'
 
 
const buildPath = path.resolve(__dirname, 'dist/dev/mp-weixin')
// const buildPath = path.resolve(__dirname, 'dist/build/mp-weixin')
 
 
export default defineConfig({
  resolve: {
    alias: {
      '~/': `${path.resolve(__dirname, 'src')}/`,
    },
  },
  plugins: [
    viteStaticCopy({
      // --------------- wasm 复制
      targets: [
        {
          src: `${path.resolve(__dirname, 'src/pages-sub/yourPath/*.wasm.br')}`,
          dest: `${path.resolve(__dirname, 'dist/dev/mp-weixin/pages-sub/yourPath/mupdf/')}/`
        },
      ]
    })
  ],
  build: {
    target: 'es6',
    emptyOutDir: false,
    
    outDir: 'dist/dev/mp-weixin/workers',
    minify: false,
    lib: {
      // workers 打包
      entry: [
        path.resolve(__dirname, 'src/workers/yourworker.ts'),
      ],
      formats: ['cjs'],
      fileName: (format, entryName) => {
        console.log(format, entryName)
        return entryName + '.js'
      }
    }
  }
});
```
然后pakage.json, scripts 里添加
"dev:workers": " vite build --config ./vite.worker.config.mts -w"

5. worker 示例

```js
import module from '~/pages-sub/yourPath/youWasm' // 胶水代码位置
 
 
const { postMessage, onMessage } = worker
 
const methods: any = {}
 
methods.someFn = () => {
  return module.ccall('someFn')
}
 
onMessage((event: any) => {
  let [func, id, args] = event
  try {
    let result = methods[func](...args)
    console.log('[worker onMessage]', event, result)
    postMessage({ type: "RESULT", id, result })
  } catch (error: any) {
    postMessage({ type: "ERROR", id, result: { name: error.name, message: error.message, stack: error.stack } })
  }
})
 
 
postMessage({ type: "INIT", id: 0, result: Object.keys(methods) })
```
然后需要在wasm 对应的subpackage里尝试加载它，才能正常加载 如 src/pages-sub/yourPath/yourWasmHelper.ts
```
let worker: any = {
  onMessage: (e: any) => { },
  postMessage: (...arg: any[]) => {
    throw new Error('还未加载完成wasm')
  },
  _promise_id: 1,
  _promise_map: new Map(),
  wrap: function (name: string) {
    return function (...args: any[]) {
      return new Promise(function (resolve, reject) {
        let id = worker._promise_id++
        worker._promise_map.set(id, { resolve, reject })
        if (args[0] instanceof ArrayBuffer)
          worker.postMessage([name, id, args], [args[0]])
        else
          worker.postMessage([name, id, args])
      })
    }
  }
}
 
 
const startListen = () => {
  worker.onMessage(function (data: any) {
    let { type, id, result } = data
    console.log("mmMesg", data);
    let error
 
    switch (type) {
      case "INIT":
        for (let method of result)
          worker[method] = worker.wrap(method)
        break
 
      case "RESULT":
        worker._promise_map.get(id).resolve(result)
        worker._promise_map.delete(id)
        break
 
      case "ERROR":
        error = new Error(result.message)
        error.name = result.name
        error.stack = result.stack
        worker._promise_map.get(id).reject(error)
        worker._promise_map.delete(id)
        break
 
      default:
        error = new Error(`Invalid message: ${type}`)
        worker._promise_map.get(id).reject(error)
        break
    }
  })
}
 
uni.preDownloadSubpackage({
  packageType: 'workers',
  success() {
    // 创建 worker。 如果 worker 分包没下载完就调 createWorker 的话将报错
    const workerR = uni.createWorker('workers/yourWorker.js')
    Object.assign(worker, workerR)
    startListen()
  },
  fail() {
    console.log('load worker fail')
  },
} as any)
```


5. ios 端的worker 传输ArrayBuffer 速度极其慢(没有JIT)
postMessage中传arrayBuffer 非常慢，有大数据的需求很难整

- 小游戏提供了一个现在提供 wx.createSharedArrayBuffer 处理 https://developers.weixin.qq.com/minigame/dev/game-engine/worker/tutorial.html
  - 小程序真机ios useExperimentalWorker, 从而会打开JsCore 的JIT, 性能可以大大提高，但开启时不能用createSharedArrayBuffer
  - useExperimentalWorker 关闭时可以用createSharedArrayBuffer, 但没有jsCore JIT 处理性能非常低 (8-10 倍性能)
Transferable Object 没有效果
- WebAssembly.Memory  也不行, worker.postMessage 后 只是复制了一个空对象


综上，还是应该用非 useExperimentalWorker + createSharedArrayBuffer 的方案， ios 速度慢很多很多，只能优化文件大小

**Comment by ctxqlxs** [comment]
"WasmOffsetConverter 是不支持的方法 需要移除" 这个咋移除呀。。

**Comment by ctxqlxs** [comment]
@aizigao

**Comment by Yongle-Fu** [comment]
https://gist.github.com/Yongle-Fu/c4b8e9b0302a01fe6bac16e265e31077

My example works, but it only supports single-threaded execution.

**Comment by ctxqlxs** [comment]
any update?
