### ISSUE TITLE
hash of zlib port in the latest release is wrong

### ISSUE THREAD

**Issue by ShuangLiu1992** [emscripten-core/emscripten#16163]
Download https://github.com/madler/zlib/archive/refs/tags/v1.2.11.zip or https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz
their hash respectively: 

9ec7c573fac2cd4d6ba64dd4dfd7330f317be75367575013da4004d7da7ff51b70b85783dc8533df081e70527135cdbf2ffc12b40f2d011fd7fbe6cb52d2f47d

104c62ed1228b5f1199bc037081861576900eb0697a226cafa62a35c4c890b5cb46622e399f9aad82ee5dfb475bae26ae75e2bd6da3d261361b1c8b996970faf

But the hash in https://github.com/emscripten-core/emscripten/blob/main/tools/ports/zlib.py is a42b8359e76cf7b3ae70bf31f0f8a8caa407ac80e8fe08b838076cd5e45ac2e685dae45eb59db2d25543fb3b5bd13b843a02bb8373cda704d7238be50d5e9c68

Not sure if they fix something in the code and updated the tag or was it recorded wrong in emsdk?

**Comment by dirkharbinson** [comment]
Looks like the archive at https://github.com/madler/zlib/archive/v1.2.11.zip is working now

**Comment by ShuangLiu1992** [comment]
https://github.com/emscripten-core/emscripten/commit/81106e2f283595da4d0741c51487ec6d0970d8d0
