### ISSUE TITLE
request: add support for thin-lto in embuilder.py

### ISSUE THREAD

**Issue by ericoporto** [emscripten-core/emscripten#16172]
I am tracking from https://github.com/emscripten-core/emscripten/discussions/16165#discussioncomment-2090182 , the answer from @kleisauke 

> For regular/full LTO, you could use `embuilder.py build libc --lto`. For thin LTO (which is not heavily tested), there isn't such argument. Perhaps we should extend the `--lto` setting of `embuilder.py` by accepting value arguments (e.g., `--lto=thin`), just like `emcc`.
> 
> https://github.com/emscripten-core/emscripten/blob/e415e01e8e6ddc7c453e97e557ea0e2cf37d5d23/emcc.py#L2996-L3000
> 
> 
> https://github.com/emscripten-core/emscripten/blob/e415e01e8e6ddc7c453e97e557ea0e2cf37d5d23/embuilder.py#L153-L154
> 
> (Or allowing something like `EMCC_CFLAGS="-flto=thin" embuilder.py build libc`)

This is more to decide the implementation before submitting a PR. Also emcc doesn't use argparse, so the code won't be exactly the same in embuilder.

**Comment by kripken** [comment]
cc @dschuff who I think may have been looking into this?

**Comment by ericoporto** [comment]
I opened and closed the PR just to show a naive code. But the exact mimic through argparse of the behavior in emcc I could not figure how to replicate (it fails as the comment in the PR explains).

**Comment by dschuff** [comment]
In principle thinLTO should work, and I'd like to improve our support for it. I think it would be fine to add support in embuilder as a start to making it easier to use and test.

**Comment by ericoporto** [comment]
Aha, I found out WHY I was using thinlto: https://github.com/emscripten-core/emscripten/issues/15676

Apparently LTO on CMake with Emscripten is defaulting to `thinlto`. This is very curious, because the default on other systems seem to be `full`.
