### ISSUE TITLE
HEAPU32 used instead of HEAP32 in checkStackCookie

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#16176]
I guess this is not too important, but in a runtime generated with:
```
em++ -pthread -fwasm-exceptions -s PTHREAD_POOL_SIZE=4 -s MINIMAL_RUNTIME=1 --minify 0 code.cpp -o code.html
```
`writeStackCookie` is using `HEAP32`, while `checkStackCookie` is using `HEAPU32`. 

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1 (5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2)
clang version 14.0.0 (https://github.com/llvm/llvm-project d98dfb2baabb647a6ac4c4f4399999cfc44433db)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by kripken** [comment]
This executes the same, but for consistency it would be good to fix, nice that you noticed this. A PR would be welcome.

**Comment by rajkumarananthu** [comment]
Hi, I would like to work on this issue, may I? Any first hand inputs?

**Comment by kripken** [comment]
@rajkumarananthu That would be great!

I think you need to start by finding those two functions `writeStackCookie, checkStackCookie` in `src/*`, and then switch them to use the same heap view.

**Comment by rajkumarananthu** [comment]
Thanks for the inputs, can you assign this issue to me, I'll start working on it.

**Comment by rajkumarananthu** [comment]
Hi @kripken I went through the code and found the following information:
`writeStackCookie` is seeing `HEAP32`, it is using `makeSetValue()`
and
`checkStackCookie` is seeing `HEAPU32`, it is using `makeGetValue()`

Should I make both of them use HEAPU32 or HEAP32, which would be a good choice, any suggestions.

Thanks,
Rajkumar Ananthu.

**Comment by sbc100** [comment]
`HEAPU32` probably makes sense for the stack cookie as it being read a written as a raw hex value (not a signed number).

**Comment by rajkumarananthu** [comment]
Hi @sbc100 , @kripken , I have raised a pull request #16433 can you please review and provide any suggestions or if the changes are fine, can you please accept the changes and close the pull request.

Thanks
Rajkumar Ananthu
