### ISSUE TITLE
`allocate(..)` function doesn't work for consecutive stack allocations

### ISSUE THREAD

**Issue by twwwt** [emscripten-core/emscripten#16218]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.3-git
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 30efee764d95d425b480758ed02682fab6426d28)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
**Full link command and output with `-v` appended:**
Irrelevant. The problem lays in Emscripten's `allocate` function.

The following code (simplified to remove irrelevant parts) was working well for a couple of years:
```javascript
var p1 = Module.allocate(512, 'i8', Module.ALLOC_STACK);
var p2 = Module.allocate(64, 'i8', Module.ALLOC_STACK);
var p3 = Module.allocate(64, 'i8', Module.ALLOC_STACK);
```

Recently, we have upgraded from (a rather outdated) Emscripten 1.37.29 to the latest version 3.1.3. Given that the `allocate` function was changed meanwhile, we changed our code accordingly to:
```javascript
var p1 = Module.allocate(512, Module.ALLOC_STACK);
var p2 = Module.allocate(64, Module.ALLOC_STACK);
var p3 = Module.allocate(64, Module.ALLOC_STACK);
```

If this code executes, `p1`, `p2`, and `p3` all get the same pointer address (integer) assigned (i.e., `pi === pj` is true pairwise for each combination of `i` and `j`). This is obviously wrong. In the former version, all three pointer addresses returned  are different and sufficiently distant such that, given the respective size of memory to allocate, they do not overlap; i.e., the former version was working correctly.

We then tried `stackAlloc` instead:
```javascript
var p1 = Module.stackAlloc(512);
var p2 = Module.stackAlloc(64);
var p3 = Module.stackAlloc(64);
```
This works as expected; `p1` to `p3` get different addresses assigned.

We also noticed that `allocate` works if the first argument is an array (i.e., data for which we want to allocate some memory on the stack and write the data given into it):
```javascript
var someArray = [/**/];
var p1 = Module.allocate(someArray, Module.ALLOC_STACK);
```
Consecutive memory allocations get another address.

To conclude, `allocate` doesn't seem to work correctly if the first argument is an integer.

**Comment by kripken** [comment]
I think that's right - at some point this internal API was simplified. This is the current code:

https://github.com/emscripten-core/emscripten/blob/69ef07c7ac5bd8680a1ceaa65d3c6007eac23e6f/src/preamble.js#L209-L236

That is basically a small wrapper around stack allocation or malloc, and then it does a write to memory. The "shorthand" of interpreting an integer as "just allocate, don't write to memory", was removed. In such a case, it is simpler to replace code like this that you quoted:
```js
Module.allocate(64, 'i8', Module.ALLOC_STACK)
```
with
```js
stackAlloc(64)
```
From your usage, I think that's what you want to be using here.

Sorry for the churn here, but we do change internal APIs now and then. APIs intended to be stable are documented, or should be, and I don't think we've ever done that for the rather-complex `allocate()` method. Still, yeah, this can be annoying as in JS it's not always obvious what's internal and what's not...

**Comment by twwwt** [comment]
Sorry for the noise. Before opening this issue, I was browsing the code and just had a look at the state of the code immediately after you made the change to the `allocate` function (sometime in 2020). At that state the docs still mentioned that the first argument may be a number. Now that you pointed me to the current state of the code, it became all clear to me.

> From your usage, I think that's what you want to be using here.
Thanks for confirming that.

> [...] we do change internal APIs now and then.
Which is fully ok, given the fact that you explicitly marked it as internal. No complaints about that. As you probably know, sometimes your users want or even need to use internal things; which just means that you should still care about documentation of internal things to be in line with it actually done/implemented.

This issue can be closed.

**Comment by kripken** [comment]
Sounds good, closing
