### ISSUE TITLE
Chrome crashes with STATUS_BREAKPOINT related to worker count

### ISSUE THREAD

**Issue by jozefchutka** [emscripten-core/emscripten#16228]
Hi,

I am reporting this issue just to check if there is anything emscripten can do to restrict the total amount concurrent workers.

Using libs like ffmpeg compiled with pthreads its relatively easy to reach a point where browser crashes with STATUS_BREAKPOINT related to amount (505 or more) of running Workers. I wonder if there are any options for pthreads implementation to limit the amount of used workers.

I am also [reporting the limitation to chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1295633). 

In case there is no solution by pthread design/implementation on emscripten side, feel free to close this issue.

**Comment by kripken** [comment]
Do you mean via the thread pool? You can set `PTHREAD_POOL_SIZE` to a string (see settings.js docs), and so you can limit the thread pool to 4 like this:
```
-sPTHREAD_POOL_SIZE="Math.min(4, navigator.hardwareConcurrency)"
```
Otherwise, if you mean just lots of calls to `pthread_create` as the program runs, Emscripten doesn't have a flag to limit that - you'd need to modify the application AFAIK.

**Comment by jozefchutka** [comment]
I am trying with `PTHREAD_POOL_SIZE` flag, but it seem to ignore the value in runtime. When I execute `main()` it opens up many workers, not limited to the defined pool size. `PTHREAD_POOL_SIZE_STRICT` also has no effect, neither it seems to result with any changes myapp.js file. May that by a conflict of other flags used?

```
  ...
  -O3
  -s USE_PTHREADS=1
  -msimd128
  -lworkerfs.js
  -s USE_SDL=2
  -s INVOKE_RUN=0
  -s EXIT_RUNTIME=1
  -s MODULARIZE=1
  -s EXPORT_NAME="createMyapp"
  -s EXPORTED_FUNCTIONS="[_main, ___wasm_init_memory_flag]"
  -s EXPORTED_RUNTIME_METHODS="[callMain, FS, WORKERFS]"
  -s INITIAL_MEMORY=128mb
  -s ALLOW_MEMORY_GROWTH=1
  -s MAXIMUM_MEMORY=4gb
  -s ENVIRONMENT=worker
  -s PROXY_TO_PTHREAD=1
  -s PTHREAD_POOL_SIZE="Math.min(4, navigator.hardwareConcurrency)"
  -s PTHREAD_POOL_SIZE_STRICT=2
  -pthread
  -o myapp.js
```

**Comment by kripken** [comment]
I can't think of a problem, reading those flags. It might be quickest to inspect the JS. Find where the `Math.min(4, navigator.hardwareConcurrency)` appears, and then see that it is used properly at the place that reads that value. I think that is a function called `initMainThread` (we create the workers in the pool as we init the main thread).

**Comment by jozefchutka** [comment]
Indeed the (minified) .js file contains:
 
```
initMainThread:
function(){
  var pthreadPoolSize=Math.min(4,navigator.hardwareConcurrency);
  for(var i=0;i<pthreadPoolSize;++i){PThread.allocateUnusedWorker()}
}
```

but still, for some unknown reason it generates unlimited amount of workers soon after... While debugging I can see `getNewWorker` called many times, but there is no guard in place to restrict the amount of used workers and if there is empty `unusedWorkers` it would create one:

```
getNewWorker:function(){
	if(PThread.unusedWorkers.length==0){
		PThread.allocateUnusedWorker();
		PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0])
	}
	return PThread.unusedWorkers.pop()
}
```

call stack: __pthread_create_js -> spawnThread -> getNewWorker

Using emc 3.1.2

**Comment by kripken** [comment]
`PTHREAD_POOL_SIZE` just affects the pool we create during startup. If the application tries to call `pthread_create` beyond that we will try to create more. But `PTHREAD_POOL_SIZE_STRICT=2` (mode 2 specifically, see settings.js) should enforce a hard limit, if that's what you want?

**Comment by jozefchutka** [comment]
I am trying to understand (or propose) if, there is or could be, in general, any possible option on emscripten side to provide some kind of worker scheduling mechanism to avoid browser crash. Or this is impossible by design of pthreads thus not applicable.

In my project, I tried restricting the amount of concurrent workers by `PTHREAD_POOL_SIZE` and `PTHREAD_POOL_SIZE_STRICT=2`, but I just cant avoid the crash caused by huge amount of workers created at the same time. Considering `PTHREAD_POOL_SIZE` affects the initial pool size (which works) in combination with `PTHREAD_POOL_SIZE_STRICT=2` (make thread pool exhaustion a hard error). It seems to me that the latter is being ignored.

**Comment by jozefchutka** [comment]
@kripken thanks for the response. I am closing this issue as I understand enough to resolve on my end.
