### ISSUE TITLE
Couldn't find boost when using emcmake, but work propperly when only using cmake

### ISSUE THREAD

**Issue by ramdanhere** [emscripten-core/emscripten#16238]
This is the error
PackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem
  unit_test_framework program_options system) (Required is at least version
  "1.65.0")

**Comment by kripken** [comment]
Emscripten is a cross-compiler, and even if you have boost installed on your system, it will not access that. It must be compiled to the emscripten target, basically.

That has been done for the boost headers, which you can use with `-sUSE_BOOST_HEADERS` to `emcc`. Adding that to CMake's C flags might fix things. If you use more than the headers, though, then you'd need to compile boost with `emcc` first.
