### ISSUE TITLE
-fshort-wchar does not change sizeof(wchar_t)

### ISSUE THREAD

**Issue by yosmo78** [emscripten-core/emscripten#16241]
**Version of emscripten/emsdk:**
emcc 2.0.34

**Failing command line in full:**
emcc -fshort-wchar main.cpp

when compiling with -fshort-wchar and doing
```
printf("Size: %d\n", sizeof(wchar_t));
```
will report `4` instead of `2`. So does this mean sizeof is broken? or the whole string is still UTF32 not UTF16 like I want.

Thanks

**Comment by sbc100** [comment]
Oddly, I upload a patch to llvm last week that fixes this: https://reviews.llvm.org/D118573

**Comment by sbc100** [comment]
Fixed in https://reviews.llvm.org/D118573
