### ISSUE TITLE
how to use pthread in WebAssembly without SharedArrayBuffer?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#16279]
1、the C source code :
```
void *threadFunc(void* arg)
{
	std::cout<<"enter thread2 func"<<std::endl;
	for(int i=0;i<1000;i++)
	{
		std::cout<<"enter 2"<<std::endl;
	}
	return arg;
}

int main() {
    pthread_t *thread_id;
    int ret = pthread_create(thread_id, NULL, threadFunc, NULL);
	if(ret)
	{
		std::cout<<"create thread failed!"<<std::endl;
	}
	pthread_detach(*thread_id);//分离线程
	return 1;
}
```

2、the compile script:
`the emcc test.c -o test.js -s PTHREAD_POOL_SIZE=2 -s USE_PTHREADS=1 `

so if there is a method , the wasm would not use the sharedArrayBuffer ?

**Comment by sbc100** [comment]
No, there is no way to use multi-threading without SharedArrayBuffer.     Please close this issue if that answers your question.

**Comment by sam-bunger** [comment]
@sbc100, is there a way to use just the Wasm Workers API without the use of SharedArrayBuffer? Something where each worker has it's own memory, and a postMessage and onmessage system is available in C++? Compiling with `-sWASM_WORKERS` seems to also always turn on SharedArrayBuffers as well.

**Comment by sbc100** [comment]
I don't think so no, wasm workers, like pthreads, are defined as sharing memory.   

We do have an API for creating regular web workers: https://emscripten.org/docs/api_reference/emscripten.h.html#worker-api.  IIUC they don't use shared memory.
