### ISSUE TITLE
Side module calls __cxa_find_matching_catch_n which is missing from main module

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#16302]
When I have a main module and a side module with exception support, I get an error like `Cannot read properties of undefined (reading 'apply')` because `resolveGlobalSym` fails to find a global symbol called `__cxa_find_matching_catch_14`, since the main module only defines e.g., `__cxa_find_matching_catch_2`, `__cxa_find_matching_catch_3`, and `__cxa_find_matching_catch_5`.

Adding the following to the end of `resolveGlobalSym`:
```js
    if(!sym && symName.startsWith("__cxa_find_matching_catch")){
      sym = Module.___cxa_find_matching_catch;
    }
```
fixes it.

**Comment by kripken** [comment]
I think that makes sense, yes, these functions have a shared prefix. I'm surprised we don't already have this, but I guess our testing of exceptions(/setjmp) + dynamic linking is limited?

Would you like to open a PR?

**Comment by hoodmane** [comment]
> Would you like to open a PR?

Sure, will do.

**Comment by hoodmane** [comment]
A related question: suppose I want to enable exception handling on side modules (if they are compiled with `-fexceptions` or `-sEXCEPTION_CATCHING_ALLOWED=[...]`) but do not need exception handling in the main module. From looking at `test_core.py:test_exceptions_allowed`, it seems like the way to do this is to link the main module with `-sEXCEPTION_CATCHING_ALLOWED=['fake']`. Is this right?

**Comment by kripken** [comment]
Yes, I think it will do what you want - enable exceptions in general but with an (effectively) empty allow-list it will not add overhead to functions in the main module (or hopefully very little). It will mostly just link in the library support which side modules will need.
