### ISSUE TITLE
emscripten_set_window_title does not support Unicode

### ISSUE THREAD

**Issue by Ghabry** [emscripten-core/emscripten#16327]
The string is passed through AsciiToString here https://github.com/emscripten-core/emscripten/blob/1ebd4c8932eaceb05ccdc0fed6be611c682da43e/src/library_browser.js#L1228

Is there any reason for this? Could it be replaced with utf8ToString?

**Comment by kripken** [comment]
I think that's an oversight - good find! A PR would be very welcome.

**Comment by lychees** [comment]
Thanks for the help. I will keep an eye and will leave a message once it be validated in our side.

**Comment by sbc100** [comment]
I think its fair to call this closed due to #16330.   We can always reopen if needed.
