### ISSUE TITLE
Enabling Address Sanitizer causes runtime to exit despite `NO_EXIT_RUNTIME` being set

### ISSUE THREAD

**Issue by cheinr** [emscripten-core/emscripten#16348]
I've been trying to get the address sanitizer working for a project I'm working on, and it appears to be causing the runtime to exit, even if I set `NO_EXIT_RUNTIME`.

Here's an example program that does something asynchronously:

```
// main.c
#include <stdio.h>
#include "emscripten.h"

int main() {
  EM_ASM({
      setTimeout(() => {
          const foo = cwrap('foo', null, null, { async: false });
          foo();
        }, 5000);
    });

  return 0;
}

EMSCRIPTEN_KEEPALIVE void foo() {
  printf("blam!\n");
}
```

For the latest version of emscripten (`3.1.5`), I get the following when I **don't** provide the `-fsanitize=address` flag:

```
> emcc -s ALLOW_MEMORY_GROWTH main.c 
> node a.out.js
blam!   // (after 5 seconds)
```

However, when the address sanitizer is enabled the program exits immediately without waiting for the async operation:
```
> emcc -s ALLOW_MEMORY_GROWTH -fsanitize=address main.c 
> node a.out.js
> (no output)

```

This occurs even if I add `-s NO_EXIT_RUNTIME=1` when compiling. I've also tried using emscripten versions `3.0.0` and `2.0.0`. `3.0.0` had the same behavior, but `2.0.0` worked as I would have expected with the `fsanitize=address` flag enabled, so I'm assuming this might be a regression?

**Comment by sbc100** [comment]
Ah, I think this might be a bug.  `-fsanitize=address` should default to enabling `EXIT_RUNTIME` but it should no override your command line settings.    I hope/think this will not occur if you use `-sEXIT_RUNTIME=0` (which is logically the same as `-sNO_EXIT_RUNTIME`).

Regardless we should fix the way to handle defaulting settings to handle this case.
