### ISSUE TITLE
`emscripten/version.h` missing?

### ISSUE THREAD

**Issue by tralves** [emscripten-core/emscripten#16371]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5-git
clang version 15.0.0 (https://github.com/llvm/llvm-project.git f3bc7fd5465a3a919388b6a0307553ef4a6d39c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/homebrew/opt/emscripten/libexec/llvm/bin
```

`emscripten/3.1.5/libexec/system/include/emscripten.h` has `#include "version.h"`, but `version.h` is not there. After a small research in [this commit](https://github.com/emscripten-core/emscripten/commit/f99af02045357d3d8b12e63793cef36dfde4530a), seems like the file should have been generated at some point.

I installed 3.1.5 through `brew upgrade emscripten` from 3.1.0.

for now, I'll just create this file directly.

Thanks.

**Comment by sbc100** [comment]
The file is auto-generated when the sysroot is first created.   Please file a bug with the brew package as it seems likely to be specific the brew packaging.   See https://emscripten.org/docs/getting_started/downloads.html#installation-using-unofficial-packages for info on the brew package.

**Comment by Squareys** [comment]
This also seems to be the case in the official docker image.

**Comment by sbc100** [comment]
Did you file a bug with the brew package?  If co can you link to it here?  (and close this issue?)

**Comment by Etchelon** [comment]
I've just installed emscripten with the [official method](https://emscripten.org/docs/getting_started/downloads.html) (python scripts it seems) on Windows 11 and I'm missing this file as well:

![image](https://user-images.githubusercontent.com/4141889/160839631-748b8e82-664f-419b-8fc3-771556b7e035.png)

**Comment by sbc100** [comment]
Your IDE seems to think the emscripten include path is "system/include" whereas it it should be looking inside "cache/sysroot/include" which is where the headers get installed.

**Comment by Etchelon** [comment]
I actually pointed it to that folder because I looked inside the emsdk folder myself and ended up spotting that include folder. Changing folder worked, thanks 👍
