### ISSUE TITLE
Export C++ exception tag

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#16380]
I am looking into how to do a similar task to #16343 with `-fwasm-exceptions`. If there is an uncaught C++ exception with `-fwasm-exceptions`, a `WasmException` object is thrown which contains a single i32 which is the same pointer that is thrown as a number when using `-fexceptions`. The `WasmException` API has a `getArg` API which can be used to get the pointer like `exception.getArg(tag, 0)`. The problem is that the tag isn't exported and without the tag the `WasmException` is completely opaque.

Once I have this tag, we can get access to the pointer from the `WasmException` and then handle it similarly to as in the `-fexceptions` case. I have checked that this works by using `wasm2wat` then adding `(export "cpp_exception_tag" (tag 0))` to the wat, then using `wat2wasm`. (Though there is still the remaining issue that `__cxa_can_catch` doesn't exist in this case.)

**Comment by hoodmane** [comment]
Actually I am not sure what to do with the pointer we get out either. But I think the first step is definitely getting access to it.

**Comment by aheejin** [comment]
Closing this, given that #17064 landed. As I described in that PR, using this to extract thrown values still requires multiple options, which is inconvenient at the moment, but it is at least possible. Refer to the example test to see how it is used and which options should be turned on: https://github.com/emscripten-core/emscripten/blob/2a3bb65cdea614451e4dc6227ae8e338902bfd1d/tests/test_core.py#L1636-L1713
(The test uses `EM_ASM`, but  you can do the same thing with normal JS code as well)

I'm planning to make this easier to use, possibly creating a single option that adds all necessary imports and exports the tag, but I'd like to let you know that using this is at least possible now. I'll CC this issue again when the one-stop option is added later too.

**Comment by aheejin** [comment]
You can use these methods to access the tag and thrown values, and print `what()` message (if any) for an exception: 
- `getCppExceptionTag`
- `getCppExceptionThrownValue`
- `getExceptionMessage`
https://github.com/emscripten-core/emscripten/blob/2a3bb65cdea614451e4dc6227ae8e338902bfd1d/src/library_exceptions.js#L396-L447

Note that `getExceptionMessage` uses `getCppExceptionThrownValue` and `getCppExceptionThrownValue` uses `getCppExceptionTag`, so in case you don't need direct access to the tag and thrown values and the only thing you want is to print the message, you only need to call `getExceptionMessage`.
