### ISSUE TITLE
Mark a block of codes to avoid be minified by closure compiler.

### ISSUE THREAD

**Issue by xbcnn** [emscripten-core/emscripten#16390]
Some times I need a way mark a block of codes won't be minified, keep their function, variable names, or property names, which is used outside in other js files.  

Such as I have a EM_JS block returns an object through emscripten::val. Their property names would be a contract to the consumer and should not be changed in anyway.

> EM_JS(EM_VAL, makeVal, (int v), {
>    var item = {};
>    item.value = v;
>    Emval.toHandle(item);
> });

Both the `item` and `value` might be minified.

Is that possible. to mark it?

**Comment by sbc100** [comment]
To make property resistant to closure minification you can use strings as keys.  e.g. `item['value'] = v`.   

If you want to make something accessible outside the module itself you could assign a property on the module object.  e.g. `Module['myItem'] = item;`

**Comment by xbcnn** [comment]
This works!  Thanks.
