### ISSUE TITLE
wasm-ld: error: unknown file type: SDL_dynapi.o

### ISSUE THREAD

**Issue by TheStaticBits** [emscripten-core/emscripten#16398]
I've just started out using Emscripten, and have tried to compile an SDL2 program with it, however it's giving me an error which I don't know how to handle. Help will be appreciated!

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.6 (c102a423a06d9833a8481d6859888bebf22842b0)
clang version 15.0.0 (https://github.com/llvm/llvm-project 6eec4835844439ab932515ff4ac857773c639171)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Emscripten\emsdk\upstream\bin
```

**Command:**
```
em++ -g src\animation.cpp src\entity.cpp src\game.cpp src\main.cpp src\particle.cpp src\player.cpp src\window.cpp src\world.cpp -s WASM=1 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -o bin\debug\application.html -IC:\SDL2-w64\include -LC:\SDL2-w64\lib -lSDL2main -lSDL2 -lSDL2_image -Iinclude -Wall
```

**Output:**
wasm-ld: error: unknown file type: SDL_dynapi.o
em++: error: 'C:/Emscripten/emsdk/upstream/bin\wasm-ld.exe -o bin\debug\application.wasm C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\animation_0.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\entity_1.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\game_2.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\main_3.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\particle_4.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\player_5.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\window_6.o C:\Users\mtthw\AppData\Local\Temp\emscripten_temp_tvexxmvx\world_7.o -LC:\SDL2-w64\lib C:\SDL2-w64\lib\libSDL2main.a C:\SDL2-w64\lib\libSDL2.a C:\SDL2-w64\lib\libSDL2_image.a -LC:\Emscripten\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten C:\Emscripten\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libSDL2_image.a C:\Emscripten\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libSDL2.a -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=malloc --export=free --export=memcpy --export=fileno --export=__dl_seterr --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (returned 1)

**Comment by sbc100** [comment]
the problem is that you are trying to link against `C:\SDL2-w64\lib\libSDL2.a` and `C:\SDL2-w64\lib\libSDL2_image.a` which are most likely windows libraries and not Wasm libraries.   The easiest way to use SDL in emscripten is to use the `-sUSE_SDL=2` setting.
