### ISSUE TITLE
`__syscall_munmap` is not always releasing lock

### ISSUE THREAD

**Issue by blaugold** [emscripten-core/emscripten#16406]
When `__syscall_munmap` returns early, because of a partial munmapping the lock that is used to protect the mappings is not unlocked. Subsequent calls to other mmap functions are never able to acquire the lock and cause a deadlock.

https://github.com/emscripten-core/emscripten/blob/1311431954a678ca8f8470f6b8de8360849173d0/system/lib/libc/emscripten_mmap.c#L55-L67

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.6 (c102a423a06d9833a8481d6859888bebf22842b0)
clang version 15.0.0 (https://github.com/llvm/llvm-project 6eec4835844439ab932515ff4ac857773c639171)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/gabriel/Dev/emsdk/upstream/bin

**Comment by sbc100** [comment]
Thanks for spotting this!
