### ISSUE TITLE
emscripten_get_canvas_element_size returning wrong value

### ISSUE THREAD

**Issue by blitz-research** [emscripten-core/emscripten#16415]
Hi,

emscripten_get_canvas_element_size is returning the wrong initial size for me when my app starts up, it's always returning 300, 150 whereas the canvas is 100% width/height.

This used to work (about 6 months ago) when it was called emscripten_get_css_element_size (Ithink) and if I replace the new version with the old one it works again.

The diferent betweem the two is that the old version returns canvas.getBoundingClientRect().width and .height while the new one returns canvas.width and .height directly.

I've long ago given up on trying to keep up with how css layout works so I have no idea what this means but perhaps this is a clue...?

Or perhaps I'm just doing it wrong - I'm trying to determine the size to pass to glfwCreateWindow before the mainloop is started.

Bye,
Mark

Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.6 (c102a423a06d9833a8481d6859888bebf22842b0)
clang version 15.0.0 (https://github.com/llvm/llvm-project 6eec4835844439ab932515ff4ac857773c639171)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/marksibly/dev/emsdk/upstream/bin

**Comment by juj** [comment]
There are two different sizes with canvases: the canvas render target size, and then the visible CSS pixel size on the page. See e.g. https://www.khronos.org/webgl/wiki/HandlingHighDPI for more information.

**Comment by blitz-research** [comment]
Ok, so emscripten_get_canvas_element_size is like backbuffer width/height?

But does this mean there's no longer any (built in) way to get the css size? The compiler says emscripten_get_element_css_size has been deprecated and I should use emscripten_canvas_element_size instead.

No a big deal, I've EM_ASM'd around it, thanks for your help!

**Comment by juj** [comment]
> emscripten_get_canvas_element_size is like backbuffer width/height?

Yes.

> The compiler says emscripten_get_element_css_size has been deprecated and I should use emscripten_canvas_element_size instead.

Can you show the log of what you are getting? `emscripten_get_element_css_size` should not be deprecated.

**Comment by blitz-research** [comment]
Ok, my bad. I wasn't #including emscripten/html.5 and it ended up telling me emscripten_get_canvas_size (which I've never used) was deprecated instead for some reason:

```
/home/marksibly/dev/wasmbasic/blitzworld/main.cpp:54:2: error: use of undeclared identifier 'emscripten_get_element_css_size'; did you mean 'emscripten_get_canvas_size'?
        emscripten_get_element_css_size("canvas", &w, &h);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        emscripten_get_canvas_size
/home/marksibly/dev/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/emscripten.h:84:6: note: 'emscripten_get_canvas_size' declared here
void emscripten_get_canvas_size(int *width, int *height, int *isFullscreen) __attribute__((deprecated("This variant does not allow specifying the target canvas", "Use emscripten_get_canvas_element_size() and emscripten_get_fullscreen_status() instead")));
     ^
/home/marksibly/dev/wasmbasic/blitzworld/main.cpp:54:2: warning: 'emscripten_get_canvas_size' is deprecated: This variant does not allow specifying the target canvas [-Wdeprecated-declarations]
        emscripten_get_element_css_size("canvas", &w, &h);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Use emscripten_get_canvas_element_size() and emscripten_get_fullscreen_status() instead
/home/marksibly/dev/emsdk/upstream/emscripten/cache/sysroot/include/emscripten/emscripten.h:84:92: note: 'emscripten_get_canvas_size' has been explicitly marked deprecated here
```
