### ISSUE TITLE
WebGPU: Incorrect GPURenderPassDepthStencilAttachment

### ISSUE THREAD

**Issue by pplux** [emscripten-core/emscripten#16426]
This code is not working, it doesn't allow to setup a value for clearing properly the depth attachment.

https://github.com/emscripten-core/emscripten/blob/a29f6682a579b5d94e69f6d5bb8b99a1e6944897/src/library_webgpu.js#L1536-L1545

* depthLoadValue : should depthLoadOp
* depthClearValue: is missing (default is 0... so basically you can not use Less or equal to render)
* stencilLoadValue: it should be stencilLoadOp, but weirdly it is supposed to be "load" or "clear" but the variable stenciLoadValue reads a U32
* stencilClearvalue: is missing (I guess it is mixed in the code with stencilLoadValue)

**Comment by kainino0x** [comment]
Thanks, I think there's two issues here: 1, the API changed recently and this code is outdated, and 2, there's probably also a bug in the outdated code too. We'll have to update the headers/cpp as well (from Dawn's code generators).

@shrekshao will take a look.
