### ISSUE TITLE
-sFOO=<number/string/array> settings should validate the type of the argument passed to it

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#16440]
Building e.g. any of

```
emcc tests/hello_world.c -o a.html -sWASM=off
emcc tests/hello_world.c -o a.html -sWASM=no
emcc tests/hello_world.c -o a.html -sWASM=false
emcc tests/hello_world.c -o a.html -sWASM=sun_is_shining
```
will all build ok, and result in a Wasm-enabled build.

I think we should distinguish -s settings that take in an integer/string/array, and if user passes a wrong kind of type argument, abort building up front.

Even though I used falsey words above, I think we should not recognize true/false name strings for boolean args, but treat boolean args as integer args, and require an integer 0 or 1 as input. That is so that we will leave room in the future to expand the value setting of such args to take in more number values (as an example, WASM used to be just a 0/1 true/false setting, but then later gained WASM=2 mode that is wasm with a JS fallback. If we had accepted WASM=false and WASM=true, then we might expand to a funny WASM=false/true/2 type of scenario)

This caused an issue in #16438 , where I innocuously changed

```
#if TEXTDECODER == 2
...
#else
#if TEXTDECODER
...
#endif
#endif
```
to a
```
#if TEXTDECODER == 2
...
#elif TEXTDECODER == 1
...
#endif
```
which uncovered a silent problem in [one of the tests](https://github.com/emscripten-core/emscripten/pull/16438/commits/123336ac09a5b59165ad47856d6a92bf64644c34), which was building with `-sTEXTDECODER=False`, that had gone undetected, and actually tested `-sTEXTDECODER` being enabled all the time (it would pass `#if TEXTDECODER` test, but now began to fail `#if TEXTDECODER == 1` test)

**Comment by sbc100** [comment]
I agree.  I think I even have an outstanding change to do this.   

The main tricky part is that we don't know exactly which settings are boolean, which are integers and which can be both.   My guess is that we would need to add types for to the settings somewhere.. and sadly not all of them have single time (e.g. `PTHREAD_POOL_SIZE` accepts as string!   ugg).

I think we might be able to get away to type inference for most settings if we switch from using 1/0 to true/false in `settings.js`  (side note, settings.js is only ever parsed from python these days!  but thats separate issue I'm looking at).    This way we can infer the types of most settings based on the default value (int, bool, string, list) and we only need to enumerate the special cases of settings that are polymorphic (e.g. `PTHREAD_POOL_SIZE`).

**Comment by juj** [comment]
I wonder if we could either do a simple comment-based annotation,
```js
var WASM = 0; // [0,1,2]
```
where the comment states the possible values for the object. That way we'll also get validation on the actual range of values, and -sWASM=3 would fail to compile.

If parsing comments feel icky, could alternatively wrap it to some kind of type object based thing:
```js
function A(...args) {
  return args[0];
}
var WASM = A(0,1,2);
var PTHREAD_POOL_SIZE = A(0, '*i', 'navigator.hardwareConcurrency');
```
where establishing code values like '*i' could mean "any nonnegative integer", `*s` could mean "any string", and so on.

> I think we might be able to get away to type inference for most settings if we switch from using 1/0 to true/false

I was thinking we would not do true/false at all, since that would restrict the future expansion of the options. (true/false -> true/false/2 would not expand well)

**Comment by sbc100** [comment]
> I was thinking we would not do true/false at all, since that would restrict the future expansion of the options. (true/false -> true/false/2 would not expand well)

My though that we would just default to `[true, false]` if we see that either `true` or `false` is the default.   We would then have a mechanism for overriding (e.g. as you suggest some kind of `[true,false,2]` syntax that would only be used as needed).
