### ISSUE TITLE
`pip` is not available on windows using the emsdk-bundled version of python

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#16466]
This means we can't run `pip install -r requirements-dev.txt` which in turn means we
can can't run some tests under windows when using the emsdk version of
python on windows.  For example the `websockify`-based tests in `test_sockets.py`.

The simplest short term solution is to run these tests using some other version
of python.  e.g. #16378, but in the long term it would be nice to be able to install
the packages we need in the emsdk version of python.

**Comment by tiran** [comment]
Does ``python -m pip`` work for you?

**Comment by sbc100** [comment]
Not with the version of python that we bundle under windows.

Try running `$EMSDK_PYTHON -m pip` or sdk/python/path/to/exectuable -m pip` and you will see that pip is missing.

This is because we base out package on the "Windows embeddable package" form https://www.python.org/downloads/windows/.   I can't find any other way to get a tar archive of a win32 python build.  I'm considering just building python myself, or maybe using the windows install and then zipping up the result.. but both options seem kind of hacky.

**Comment by tiran** [comment]
I don't have access to a Windows machine.

The embeddable package does not come with ensurepip. You could either use [get-pip.py](https://pip.pypa.io/en/stable/installation/) or copy ensurepip directory from another Python installation and run it. Let me ping @zooba for advise. He is our resident Windows experts and maintains Python's Windows installer.

**Comment by sbc100** [comment]
Oh nice!   Thanks for the help.  Our main requirement is that we want a python that we can download and unzip from our emsdk install script (which also happens to be written in python).   So we are using "whatever-python-the-user-has.exe" to install our own hermetic and specifically versioned python.   I was not able to make this work using the `.msi` installer.

Here is the script I use to build our zip file downloadable versions of python:

https://github.com/emscripten-core/emsdk/blob/main/scripts/update_python.py

**Comment by sbc100** [comment]
Essentially I believe we are close to the embedded case but we also want to be able to use pip to install whatever extra packages we might depend on.

**Comment by zooba** [comment]
If you're in a position to download the embedded runtime, use a separate Python install to `pip install --target <runtime dir> ...`, and then package up and redistribute the whole thing, then you're close to the embedded case.

If you just want a regular-but-not-installed copy of Python, you could base it on the Nuget package instead, which does include pip: https://www.nuget.org/packages/python/

This one is primarily meant for CI systems, and particularly those that follow Nuget-like conventions (essentially, things in Visual Studio, but it's totally usable anywhere - it's just a zip file with a bit of internal structure). So you'd be "off label" to repackage and redistribute it, but probably fine. We don't distribute any binaries for redistribution other than the embeddable package.

**Comment by sbc100** [comment]
Nice.  That nuget package sounds like what we want.  We run into a couple of issues in the past regarding the embedded package.

Thanks!
