### ISSUE TITLE
WebGPU bindings ahead of Chrome Stable

### ISSUE THREAD

**Issue by tyrmullen** [emscripten-core/emscripten#16465]
**Version of emscripten/emsdk:**
3.1.6

The WebGPU API is migrating from EndPass() to End() for compute and render passes.  Emscripten has already migrated over to using End(), but Chrome Stable doesn't yet have the new API, which means I can't yet use the newest Emscripten.  Rather than having a hard cutoff, so that Emscripten version A works only with Chrome X, and version B works only with Chrome Y, it would be nice to have a bit of a grace period.  Two possible approaches for this specific issue:
- Keep both End and EndPass APIs for a while
- Migrate C++ API to End, but in library_webgpu.js, use whichever of pass["end"] and pass["endPass"] exists

**Comment by kainino0x** [comment]
+myself +@shrekshao

**Comment by dschuff** [comment]
Looks like #16467 is the fix, please reopen if there's more that needs to be done.

**Comment by kainino0x** [comment]
This is going to be an ongoing policy, but yeah, I think we can call it resolved. We're changing our update policy a little bit so that we don't have to do breaking changes in Emscripten so much.
