### ISSUE TITLE
Browser shortcut keys don't work with an SDL2 Emscripten page that handles keypress events

### ISSUE THREAD

**Issue by adam4235** [emscripten-core/emscripten#16462]
I reported this issue here a while ago:

https://github.com/emscripten-ports/SDL2/issues/128

That repository got archived but the issue still remains (Emscripten 3.1.7).

To summarize, I want my application to handle some keypresses, but I want the other keypresses that I don't handle to fall back on the regular browser behaviour (such as F11 making the window full screen, for Firefox).

There was a patch that fixed it which @Daft-Freak said he would need to test before applying.

I also noticed that the issue did not seem to be present in an older version of Emscripten, 1.39.8 (i.e. without the patch, the behaviour I wanted was already happening, as long as I created the FilterEvents function mentioned in that issue).  I can't downgrade to work around it because that version has other issues, but it might be interesting that something other than that patch caused this behaviour to change.

**Comment by Daft-Freak** [comment]
Ah, I got as far as committing https://github.com/emscripten-ports/SDL2/commit/65c131602a0039437bb1a8782249828c4eba9fd4, but apparently never merged it.

The only side-effect I can see there is not preventDefault-ing keys that SDL doesn't handle... which probably isn't a bad thing. May just rebase and push upstream when I get the chance.

**Comment by Daft-Freak** [comment]
Did a quick check that `SDL_EventState` still worked and... pushed: https://github.com/libsdl-org/SDL/commit/9de97e19ccd8f97989a78629fe08d47fb758c97f

**Comment by adam4235** [comment]
Thanks!

**Comment by sbc100** [comment]
Presumably we still to update the SDL version used in emscripten?

**Comment by adam4235** [comment]
OK sorry I'm not sure of the process - maybe I wasn't supposed to close this?  Is there anything else I need to do?

**Comment by Daft-Freak** [comment]
Hmm, yeah need to update the tag here. Not sure what we're doing for updates outside of upstream releases now though...

**Comment by kripken** [comment]
I believe we can update the "tag" in `ports/sdl2.py` to any hash of a commit in that repo. That is, the `https://github.com/libsdl-org/SDL/archive/???.zip` notation works with both tag names and hashes. So if we want a commit before there is a tag that is possible.

**Comment by jdarpinian** [comment]
This fix was undone shortly after it was committed, by this commit https://github.com/libsdl-org/SDL/commit/92215481146f9225a458e9a09abb85a33b52d9ff
