### ISSUE TITLE
SDL2: emscripten generates deprecated code, with improper arguments.

### ISSUE THREAD

**Issue by km19809** [emscripten-core/emscripten#16470]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.7 (48a16209b1a0de5efd8112ce6430415730008d18)
clang version 15.0.0 (https://github.com/llvm/llvm-project fbce4a78035c32792b0a13cf1f169048b822c06b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/minsoo/emsdk/upstream/bin

**Problem**
SDL2 audio generates deprecated web audio API, [BaseAudioContext.createScriptProcessor](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor)

such as:
```js
SDL2.capture.scriptProcessorNode=SDL2.audioContext.createScriptProcessor($1,$0,1)
```
or
```js
159055:function($0,$1,$2,$3){
var SDL2=Module["SDL2"];
SDL2.audio.scriptProcessorNode=SDL2.audioContext["createScriptProcessor"]($1,0,$0);
//...
```

In addition, it does not use API with proper arguments.
The MDN says: 
> the bufferSize must be one of the following values: 256, 512, 1024, 2048, 4096, 8192, 16384. 

However, my code raises:
`Uncaught DOMException: Failed to execute 'createScriptProcessor' on 'BaseAudioContext': buffer size (1470) must be 0 or a power of two between 256 and 16384.`

As I know, [there are some PRs to support audio worklets](https://github.com/emscripten-core/emscripten/pulls?q=is%3Apr+is%3Aopen+worklets). Will them help this problem?

**Comment by sbc100** [comment]
@Daft-Freak

**Comment by km19809** [comment]
Where can I find the implementation?  I want to try to fix this issue, but I could not find how emscripten implemented SDL audio API.

**Comment by Daft-Freak** [comment]
In this file in SDL: https://github.com/libsdl-org/SDL/blob/main/src/audio/emscripten/SDL_emscriptenaudio.c

**Comment by km19809** [comment]
> In this file in SDL: https://github.com/libsdl-org/SDL/blob/main/src/audio/emscripten/SDL_emscriptenaudio.c

Thank you a lot!

**Comment by km19809** [comment]
Closed by https://github.com/libsdl-org/SDL/commit/90b86b132af02d0a8b1d39103b04ebb667687fec
