### ISSUE TITLE
undefined __syscall_accept4  when building with PROXY_POSIX_SOCKETS

### ISSUE THREAD

**Issue by engineer1109** [emscripten-core/emscripten#16482]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.7 (48a16209b1a0de5efd8112ce6430415730008d18)
clang version 15.0.0 (https://github.com/llvm/llvm-project fbce4a78035c32792b0a13cf1f169048b822c06b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/wjl/github/emsdk/upstream/bin

**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

undefined symbol: __syscall_accept4 (referenced by top-level compiled C/C++ code)

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

I wanted to try compile the demo of grpc native helloworld examples.
I found the __syscall_accept4 is not impl.

**Comment by sbc100** [comment]
Can you share the to full link command that generated that error (Mostly its very useful to know what `-s` settings you used).

**Comment by sbc100** [comment]
I suspend that perhaps you are not building with `-sPROXY_POSIX_SOCKETS`.  WIthout this option emscripten doesn't support any socket syscalls.  See:  https://github.com/emscripten-core/emscripten/blob/c19b2bece855562fa890c9403ac13b3de9e57ee0/src/settings.js#L390-L393

**Comment by sbc100** [comment]
(Deleted message regarding PROXY_POSIX_SOCKETS.. this symbol should be defined either with or without that setting).

Normally its defined right here in the library_syscalls.js: https://github.com/emscripten-core/emscripten/blob/c19b2bece855562fa890c9403ac13b3de9e57ee0/src/library_syscall.js#L444

**Comment by engineer1109** [comment]
@sbc100 if delete PROXY_POSIX_SOCKETS
then, 
undefined symbol: emscripten_init_websocket_to_posix_socket_bridge

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Os -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=512MB -s MAXIMUM_MEMORY=4GB -lwebsocket.js -lsyscall.js -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s LLD_REPORT_UNDEFINED")

the old is 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Os -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=512MB -s MAXIMUM_MEMORY=4GB -lwebsocket.js -lsyscall.js -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s LLD_REPORT_UNDEFINED -s PROXY_POSIX_SOCKETS=1")

**Comment by sbc100** [comment]
It seems that PROXY_POSIX_SOCKETS does not support proxying of accept()... do you need this features in the emscripten build, or could you perhaps remove the use of accept()?   If not, then somebody would need to add accept() support to the proxy perhaps you would like to add support the the proxy.

Perhaps adding a dummy implementation would be enough to make your code work.  Can you try this by simply adding this line of code somewhere in your application: `long __syscall_accept4(long sockfd, long addr, long addrlen, long flags, long dummy1, long dummy2) { return -ENOSYS; }`

**Comment by sbc100** [comment]
Actually it looks like `PROXY_POSIX_SOCKETS` does include a definition of `accept`: https://github.com/emscripten-core/emscripten/blob/48945f0a2454245ddc0741b5fd263b777758d245/system/lib/websocket/websocket_to_posix_socket.c#L427

Can you try building with `-sLLD_REPORT_UNDEFINED`?  It should hopefully tell you where the undefined `__syscall_accept4` is coming from?  Is there change that your code is calling `accept4` directly as opposed to `accept`?  That could explain the issue.

**Comment by xReveres** [comment]
I have the same problem. With and without `-sLLD_REPORT_UNDEFINED` prints the same errors:
```
error: undefined symbol: __syscall_accept4 (referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: ___syscall_accept4 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: gethostbyname (referenced by top-level compiled C/C++ code)
warning: _gethostbyname may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```
**emcc -v**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/debian/tools/emsdk/upstream/bin
```

**Comment by sbc100** [comment]
This is rather odd.   That error message is not generated by wasm-ld but is coming from the later JS-symbol resolution phase.. which implies that wasm-ld was successful. 

Do you think you could share the entire link command that cmake ends up using?    If you using ninja as you generator (hightly recommended) it will be part of the output and you can just copy and paste the failing command here.   If you are not using `make` then cmake defaults to hiding the full command so you would need to add `VERBOSE=1` to get it to show.

**Comment by xReveres** [comment]
I'm using WAF to build my project.
Here is link command
```
22:41:45 runner ['/home/debian/tools/emsdk/upstream/emscripten/em++', '-g', '-gsource-map', '--source-map-base=http://192.168.1.29/cs/', '-sALLOW_MEMORY_GROWTH=1', '-sINITIAL_MEMORY=536870912', '-sUSE_SDL=2', '-sEXPORTED_RUNTIME_METHODS=ccall,cwrap', '-lwebsocket.js', '-sPROXY_POSIX_SOCKETS', '-s LLD_REPORT_UNDEFINED', '-sMAIN_MODULE=1', 'engine/client/client.c.1.o', '-o/home/debian/game/build/engine/client']
error: undefined symbol: __syscall_accept4 (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: ___syscall_accept4 may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: gethostbyname (referenced by top-level compiled C/C++ code)
warning: _gethostbyname may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
em++: error: '/home/debian/tools/emsdk/node/14.18.2_64bit/bin/node /home/debian/tools/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpwzeajhk6.json' failed (returned 1)
```

**Comment by sbc100** [comment]
Ah, that explains it.   `MAIN_MODULE=1` causes all symbols in your program and in libc to be exported.    Which means all symbols are "used" including `accept4` which depends on `__syscall_accept4`. 

At least that explains why you are seeing this issue.

**Comment by sbc100** [comment]
I have fix for this issue in https://github.com/emscripten-core/emscripten/pull/16620.

BTW, if you can switch to `-sMAIN_MODULE=2` you get a much smaller binary (and would not have hit this issue).  In this mode emscripten only exports that symbols that it needs.  The only limitation is that you need to either pass you side module on  the command line (so emcc can see which symbols are needed) or you need to enumerate all of your symbols in `EXPORTED_FUNCTIONS`.

**Comment by xReveres** [comment]
Yes. Using `MAIN_MODULE=2` error gone, but now I need to fix `gethostbyname`. In `src/library.js` I see `gethostbyname` declaration.

**Comment by sbc100** [comment]
The `gethostbyname` in `src/library.js`.  For the `PROXY_POSIX_SOCKETS` case there should be an equivalent definition in `system/lib/websocket/websocket_to_posix_socket.c`.   It looks like this file implements the more modern `getaddrinfo` but not `gethostbyname`.  So somebody would need to add that functionality.
