### ISSUE TITLE
emconfigure fails to find libraries AC_CHECK_LIB(pcap...

### ISSUE THREAD

**Issue by wtfbbqhax** [emscripten-core/emscripten#16503]
Version: 3.1.7

I'm working on a generic/old C/C++ project port that requires libpcap which I've already built via the `em` wrappers.. My actual tool is also an autotools project that depends on libpcap via the autotools macro `AC_CHECK_LIB([pcap]...`

I've read the book _WebAssembly: The Definitive Guide_ in full and googled my problem and didn't find much guidance- though this seems like something I should have missed as it's pretty normal.

# Reproduction

This should be directly copy-pastable, with zero dependencies. Please tell me where I messed up.
```Dockerfile
mkdir wtfbbqhax-trash-issue/
cd wtfbbqhax-trash-issue

cat >>Dockerfile <<EOF
FROM emscripten/emsdk:3.1.7 as emsdk

ENV LIBPCAP="libpcap-1.10.1"

RUN apt-get update
RUN apt-get install -y flex bison

RUN wget https://www.tcpdump.org/release/${LIBPCAP}.tar.gz
COPY ${LIBPCAP}.sha .
#RUN sha256sum -c ${LIBPCAP}.sha
RUN tar -xzf ${LIBPCAP}.tar.gz

WORKDIR $LIBPCAP
RUN emconfigure ./configure --with-pcap=null &&\
    emmake make &&\
    emmake make install

RUN find -name "libpcap.so*" -o -name "libpcap.a"

WORKDIR /src

# XXX Reduce to bare minimum
RUN apt install -y autoconf libtool automake autotools-dev

ENV ABCIP_TAG="2.4.0"
ENV ABCIP="abcip-${ABCIP_TAG}"
RUN wget https://github.com/crc181/abcip/archive/refs/tags/v${ABCIP_TAG}.tar.gz -O ${ABCIP}.tar.gz
COPY ${ABCIP}.sha .
#RUN sha256sum -c ${ABCIP}.sha
RUN tar -xzf ${ABCIP}.tar.gz

WORKDIR $ABCIP
RUN autoreconf -ivf --warnings=all
RUN emconfigure ./configure &&\
     emmake make &&\
     emmake make install
EOF

docker build -t wtfbbqhax/trashissue:1 -f Dockerfile .
```

Actual Result

```make
#23 17.12 checking for pcap_lib_version in -lpcap... no
#23 17.26 configure: error: Missing libpcap >= 1.0.0
```

**Comment by sbc100** [comment]
I think the issue is that the `make install` step is probably install stuff in the wrong place.   Can you see where its being installed?  What does `emmake make install` output?

In order for your project to find the pcap library it would need to be installed inside the emscripten sysroot, or somewhere that you project is other setup to look (via -I and -L paths).   I would try running `emconfigure` with `--prefix=xxx` set.  You could set it to `emsdk/upstream/emscripten/cache/sysroot` to install directly into the sysroot.

BTW you don't need the `emmake` prefix when running make, assuming the Makefile was generated by emconfigure.

**Comment by wtfbbqhax** [comment]
@sbc100 Thanks for the response

Is there a way to add additional library paths to the `emcc`? 

Even if we set the prefix to that sysroot, it doesn't work because emcc doesn't search that directory.

```make
# emcc test.c -lpcap -o test
wasm-ld: error: unable to find library -lpcap
emcc: error: '/emsdk/upstream/bin/wasm-ld -o test.wasm 
      /tmp/emscripten_temp_qsrrcrva/test_0.o 
      -lpcap -L/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten 
...
```

Is there a way to specify additional library search paths so we can include 
`/emsdk/upstream/emscripten/cache/sysroot/lib`?


---
```bash
root@649a1e83ba3f:/src/abcip-2.4.0# ls /emsdk/upstream/emscripten/cache/sysroot/lib/
cmake  libpcap.a  libpcap.so  libpcap.so.1  libpcap.so.1.10.1  pkgconfig  wasm32-emscripten

# cd /src/abcip-2.4.0
# emconfigure ./configure
checking whether /emsdk/upstream/emscripten/em++ supports C++11 features with -std=gnu++11... yes
checking for pcap_lib_version in -lpcap... no
configure: error: Missing libpcap >= 1.0.0
```

After moving them into the subdir, it does work.
```
# mv /emsdk/upstream/emscripten/cache/sysroot/lib/libpcap* /emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/
# emconfigure ./configure
..success...
```

**Comment by sbc100** [comment]
If you are going to add new library and include paths I would just use a custom prefix. e.g. `./emconfigure --prefix=/my/install" and then you can add `-L/my/install/lib` and `-I/my/install/include` to the LDFLAGS and CFLAGS respectively if any project that want to consume the stuff you have installed there.
