### ISSUE TITLE
iOS 15.4 issue with Unity wasm - ideas for workarounds to try?

### ISSUE THREAD

**Issue by tangobravo** [emscripten-core/emscripten#16526]
This is almost certainly a Safari bug and not an issue with emscripten.

Many Unity WebGL wasm builds have started failing to run in iOS 15.4 (with various out-of-bounds access, functions not found, corrupted address 0 errors).

The webkit bug is here: https://bugs.webkit.org/show_bug.cgi?id=237180

There's a hint it might be related to the wasm size, and perhaps triggered when it gets over 8MiB (8 x 1024 x 1024). Saying that, other reports have suggested that size might not be the determining factor.

Many of our users are likely to be impacted by this, so I'm here to ask the experts for any thoughts on workarounds or how to try them - I know GitHub issues is likely the wrong place for this, but I could really use a little help 🙏 

I've tried forcing ArrayBuffer instantiation in case it was related to the streaming compile - unfortunately not.
I also tried adding a 20 second timeout as a run dependency, as someone suggested the wasm worked for them after waiting a bit in the JS debugger, but I didn't see any improvement from either of those.

I successfully ran `wasm2js` but not sure how to get the loader to use that instead of the wasm build?
I'm also digging into `wasm-split` in case that helps - any docs or guides that anyone can provide would be gratefully received.

I'm not familiar with how Unity goes about the emscripten build process, so ideally I'm looking for things I can apply given the js / wasm that has already been built by Unity.

**Comment by kripken** [comment]
> I successfully ran wasm2js but not sure how to get the loader to use that instead of the wasm build?

Just link with `emcc -sWASM=0` to get wasm2js to run. Then the output will not contain any wasm.

Other workarounds that helped in the past include linking with different levels, like `-Oz/-Os/-O1/-O2/-O3`, worth trying them all. Varying them at compile time may also make a difference.

**Comment by tangobravo** [comment]
Thanks for the hints. I currently don't have the Unity project source or build environment set up, so I'm hoping to convert the wasm/js from an existing Unity build (specifically looking at the examples of failing builds attached to the webkit bug).

I've been digging into the runtime differences when compiling a simple hello-world with -s WASM=0 (or 2 to get the wasm or js build) to figure out the changes I might need to make.

Looks like if I do a separate `wasm2js -O web.wasm -o web.wasm.js` I'll need to load that script before the usual one that loads the WebAssembly, and perhaps need to patch in some of the base64 bits. I'll keep plugging away at that.

Also wondering if it would be feasible at all to do the wasm2js in the browser? The Unity builds are big and it looks like the JS will be significantly bigger than the wasm, both compressed and uncompressed.

**Comment by kripken** [comment]
Both are possible in theory. For the first, you can maybe build small hello world with and without `WASM=0` to see how the builds differ, to get an idea. But I think that might be a lot of work. For the second, you can compile wasm2js itself to wasm, sure, but on a big project like Unity the compile times will be very large, I worry.
