### ISSUE TITLE
How can I make emscripten support two or more canvas elements?

### ISSUE THREAD

**Issue by ucanudo** [emscripten-core/emscripten#16541]
How can I make emscripten support two or more canvas elements?

**Comment by ucanudo** [comment]
like mutil-document? I can get Module.canvas only...

**Comment by goldwaving** [comment]
I don't think this is the place to ask general usage questions.  StackOverflow and similar sites would be better.

Any number of canvases can be created and used within Emscripten, just as any number of canvases can be created and used in an HTML page.  First look into creating canvases in [HTML in javascript](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API).  Second, use the features in Emscripten that allow you to use javascript within C [(EM_ASM)](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native).  I think you can create a variable array in Module to hold all the canvases, such as Module.myCanvases[].

**Comment by kripken** [comment]
After you create canvases on the HTML, some emscripten APIs can access them, like this one:

https://emscripten.org/docs/api_reference/html5.h.html#c.emscripten_get_canvas_element_size

The first parameter there is an identifier of which canvas you want it to operate on.

However, I believe some APIs just read `Module.canvas`, which assumes a single one exists at a time.
