### ISSUE TITLE
Document settings.js settings better

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#16563]
See the suggestion to link to

https://emsettings.surma.technology/

[here](https://github.com/emscripten-core/emscripten/pull/16532#issue-1174341720). Linking sounds like a good idea. We can also consider the other suggestions there as well to make it part of emscripten.org, but that could be separate.

**Comment by ancientstraits** [comment]
Although the PR that I made adds the link, a further suggestion i have is to add `settings.js` to the [API Reference page](https://emscripten.org/docs/api_reference/index.html) and have the content of https://emsettings.surma.technology there. However, we also need to do that "auto-generation" that emsettings does, which could be done in the `site` Makefile.
