### ISSUE TITLE
Can't call JS function added by addFunction from secondary thread

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#16567]
https://github.com/emscripten-core/emscripten/issues/11317

I have a pipelined compute process I'm implementing in WASM using pthreads. Tasks are started from the main thread, but they're executed on a secondary thread in the background. When a task is done, it needs to make a callback into the JS to inform the control logic to retrieve its data. I have used addFunction to turn a JS function (the "callback") into a function pointer, which I can pass to the WASM code. If I call this callback through the main thread, it works fine. But if I call it from the secondary thread, I get a bunch of errors as follows:
`testAddFunction.worker.js:1 worker.js onmessage() captured an uncaught exception: RuntimeError: table index is out of bounds
threadPrintErr @ testAddFunction.worker.js:1
self.onmessage @ testAddFunction.worker.js:1
testAddFunction.worker.js:1 RuntimeError: table index is out of bounds
    at testAddFunction.wasm:0x5306
    at Object.invokeEntryPoint (testAddFunction.js:9:20876)
    at self.onmessage (testAddFunction.worker.js:1:1908)`

the error information is different with #11317 .
So in Emscriptenv3.0 , the callback in different thread is still unsupported ?

**Comment by sbc100** [comment]
Since the function table is not shared between threads, any pointers returned from `addFunction` only work on the calling thread.   This is current limitation of the Worker thread model: only wasm memory is shared and nothing else.

In theory you want to keep the table in sync somehow (for example by calling addFunction in the same order on each thread)... then you could share the function pointers.

**Comment by yangfangfang1204** [comment]
`In theory you want to keep the table in sync somehow (for example by calling addFunction in the same order on each thread)... then you could share the function pointers.`

this mean i can Implement calling JS function in different threads? is there some demo ?

**Comment by sbc100** [comment]
I'm afraid we don't have any support for, or example of, the use of `addFunction` in multi-threaded programs.  

My advice would be try to re-structure your program to avoid the use of `addFunction` if you can.   Alternatively, the way to make this work is to somehow ensure that all code that calls `addFunction` in JS is run on each thread.

**Comment by yangfangfang1204** [comment]
we have another method is “Implement a C API in JavaScript” ：

`mergeInto(LibraryManager.library, {

  YUVCB__proxy: 'async',
  YUVCB__sig: 'viii',
  YUVCB: function(port,yuvData,size,timestamp) {
    //do something
	JSPlayM4_AudioResampleCallBack(port, yuvData, size);
  },
});`

But the API implement `JSPlayM4_AudioResampleCallBack` is global in JS , it doesn't belong to any class , it cause thestructural design is difficult ?

**Comment by sbc100** [comment]
If that method allows you to avoid using addFunction I would highly recommend it.   As you have discovered one of the limitations of `addFunction` is that it doesn't work well with multi-threaded programs.

**Comment by yangfangfang1204** [comment]
I create a webworker in JS  named `play.worker.js` , and i use `-s USE_PTHREADS=1` in c code , i got decoder.js /decoder.worker.js/decoder.wasm , so can i load the decoder.js in play.worker.js ?

**Comment by yangfangfang1204** [comment]
And if emscripten has the plan to support `addFunction` used in multi-threaded programs ?

**Comment by sbc100** [comment]
No that I know of.  It would quite tricky to do this since JS functions cannot be shared or transferred between workers.

So if I call `addFunction(foo)` on one thread, how do that same thing on other workers, which might not have that function in their JS at all.

**Comment by yangfangfang1204** [comment]
ok , i will try to re-structure my program to avoid the use of addFunction.

**Comment by sbc100** [comment]
I don't think this will ever work directly (at least not without some large change to how JS functions can be shared between threads).
