### ISSUE TITLE
Significant wasm size increases after upgrading emscripten toolchain 2.0.27 -> 3.18git

### ISSUE THREAD

**Issue by erikmchut** [emscripten-core/emscripten#16568]
I'm seeing a large increase in wasm sizes after upgrading an emscripten toolchain from 2.0.27 -> 3.18git. Any ideas what changes or flags are causing this?

My release binary of size 6.5 MB is ballooning to 12 MB when compiling under 3.18git. Performance and speed of the resulting binary is unchanged. We compile with -O3, -g0, -flto, and we do link-time optimization. 

Relevant compile flags:
```
emcc -std=c++17 -fno-exceptions -fno-threadsafe-statics -flto -g0 -O3 -DNDEBUG -ffunction-sections -fdata-sections -c hello.cc -o hello.o
```

Relevant link flags:
```
emcc -o hello hello.o -no-canonical-prefixes -flto -g0
```

Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8-git (e9f070c8dd8869b4325be25b39c7f830119b4092)
clang version 15.0.0 (https://github.com/llvm/llvm-project.git dc19c70c81630f8a7b9d0a6a3c90272234ce978d)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing command line in full:**
n/a

**Full link command and output with `-v` appended:**
n/a

**Comment by erikmchut** [comment]
Looks like the impact is across both the .js and .wasm files, with massive impact in .js.
```
188K - 2.0.27-application.js
4.4M - 2.0.27-application.wasm

6.6M - 3.18git-application.js
6.1M - 3.18git-application.wasm
```

The `3.18git-application.js` file is filled with tens of thousands of new function definitions of the form:
```
            var __ZdaPvRKSt9nothrow_t = Module["__ZdaPvRKSt9nothrow_t"] = function() {
                return (__ZdaPvRKSt9nothrow_t = Module["__ZdaPvRKSt9nothrow_t"] = Module["asm"]["D1c"]).apply(null, arguments)
            };
            var __ZdaPvm = Module["__ZdaPvm"] = function() {
                return (__ZdaPvm = Module["__ZdaPvm"] = Module["asm"]["E1c"]).apply(null, arguments)
            };
            var __ZNSt3__222__libcpp_aligned_allocEmm = Module["__ZNSt3__222__libcpp_aligned_allocEmm"] = function() {
                return (__ZNSt3__222__libcpp_aligned_allocEmm = Module["__ZNSt3__222__libcpp_aligned_allocEmm"] = Module["asm"]["F1c"]).apply(null, arguments)
            };
            var __ZnwmSt11align_val_tRKSt9nothrow_t = Module["__ZnwmSt11align_val_tRKSt9nothrow_t"] = function() {
                return (__ZnwmSt11align_val_tRKSt9nothrow_t = Module["__ZnwmSt11align_val_tRKSt9nothrow_t"] = Module["asm"]["G1c"]).apply(null, arguments)
            };
```
Are these being enabled by a new flag?

**Comment by sbc100** [comment]
The definitions are created for each the exported from your wasm module.  Unless you are requesting them to be exported somehow, or build with `-sMAIN_MODULE=1` (which exports everything) I would not expect to see very many of them.   You should see one per exported function.

**Comment by erikmchut** [comment]
Here are all the emscripten flags we have:
-sTOTAL_MEMORY=96mb
-sALLOW_MEMORY_GROWTH=1
-sSPLIT_MEMORY=0
-sWEBGL2_BACKWARDS_COMPATIBILITY_EMULATION=1
-sMODULARIZE=1
-sEXPORT_NAME=XRCC
-sEXPORTED_RUNTIME_METHODS=[GL,stringToUTF8,writeArrayToMemory]
-sEXPORTED_FUNCTIONS=[_malloc,_free]
-sEXPORT_ES6=1
-sUSE_ES6_IMPORT_META=0

**Comment by sbc100** [comment]
This looks suspiciously like another current open issue that relates to weakly defined symbols: https://github.com/emscripten-core/emscripten/issues/15487.  But my previous understanding was this this only effect dynamic linking use cases.

**Comment by sbc100** [comment]
I'm trying to repro the is issue locally, but I'm not seeing what you are seeing.

I'm trying using the following command:

```
$ ./em++ tests/hello_world.cpp -flto -sEXPORT_ES6=1 -sMODULARIZE=1 -sUSE_ES6_IMPORT_META=0 -sWEBGL2_BACKWARDS_COMPATIBILITY_EMULATION=1
```

And I only see the following export stubs generated:

```
/** @type {function(...*):?} */                                                  
var _emscripten_stack_init = Module["_emscripten_stack_init"] = function() {        
  return (_emscripten_stack_init = Module["_emscripten_stack_init"] = Module["asm"]["emscripten_stack_init"]).apply(null, arguments);
};                                                                               
                                                                                 
/** @type {function(...*):?} */                                                  
var _emscripten_stack_get_free = Module["_emscripten_stack_get_free"] = function() {
  return (_emscripten_stack_get_free = Module["_emscripten_stack_get_free"] = Module["asm"]["emscripten_stack_get_free"]).apply(null, arguments);
};                                                                               
                                                                                 
/** @type {function(...*):?} */                                                  
var _emscripten_stack_get_base = Module["_emscripten_stack_get_base"] = function() {
  return (_emscripten_stack_get_base = Module["_emscripten_stack_get_base"] = Module["asm"]["emscripten_stack_get_base"]).apply(null, arguments);
};                                                                               
                                                                                                                                                         
/** @type {function(...*):?} */                                                  
var _emscripten_stack_get_end = Module["_emscripten_stack_get_end"] = function() {
  return (_emscripten_stack_get_end = Module["_emscripten_stack_get_end"] = Module["asm"]["emscripten_stack_get_end"]).apply(null, arguments);
}; 
```

**Comment by erikmchut** [comment]
Thanks Sam. In my attempt to provide a minimal repro case, I think I found the culprit.

In our link step, we are adding the linker flag `-Wl,--export-dynamic`. According to our pull request comments, this was a necessary addition when we upgraded to emscripten 1.38.42 in Sept. 2019. It has been present in our build ever since, and it 
hasn't been causing any issue, though perhaps not fixing any real problem.

Removing this flag now fixes my issue, and it doesn't appear to have any negative effect. Our code works as expected and is the compiled output is the size it was with 2.0.27.

If you are curious to try, I would expect you can repro with the following command:
```
$ ./em++ tests/hello_world.cpp -Wl,--export-dynamic
```

**Comment by sbc100** [comment]
yes, I think its reasonable that adding `-Wl,--export-dynamic` would have this effect.   I guess that clears it up!   I'm not sure why it would have needed back in 2019 but I guess this issue can be closed now?

**Comment by erikmchut** [comment]
Yes, I'll close it out now. Thanks for the help.
