### ISSUE TITLE
Fetch API post json data error

### ISSUE THREAD

**Issue by vertexpotato** [emscripten-core/emscripten#16579]
Using ```emscripten_fetch``` api to post json data to a server like the following

```
 emscripten_fetch_attr_t attr;
            emscripten_fetch_attr_init(&attr);
            attr.userData = (void*)respObj.get();

            const char* headers[] = { "Content-Type", "application/json; charset=UTF-8", NULL};
            attr.requestHeaders = headers;
             strcpy(attr.requestMethod, "POST");

            attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
            attr.onsuccess = downloadSucceeded;
            attr.onerror = downloadFailed;
            if (!requestdata.empty())
            {
                attr.requestData = requestdata.c_str();
                attr.requestDataSize = strlen(attr.requestData);
            }
            emscripten_fetch(&attr, url.c_str());
```

however, the server responds with a 400 bad request, with the following message:
```
{"detail":"JSON parse error - 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte"}
```

it seems that the JSON string I'm sending is not being encoded in UTF-8 ?

I have tried to issue the same request with other clients like curl and postman, the request went through and returned 200

**Comment by sbc100** [comment]
It looks like the data from linear memory is sent directly to the xhr API:

https://github.com/emscripten-core/emscripten/blob/48945f0a2454245ddc0741b5fd263b777758d245/src/Fetch.js#L320

https://github.com/emscripten-core/emscripten/blob/48945f0a2454245ddc0741b5fd263b777758d245/src/Fetch.js#L422-L426

The result of HEAPU8.slice is sent directly, which is an ArrayBufferView, so it looks like its sending the data as binary?  See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send.

Maybe try modifying Fetch.js to call `UTF8ToString(dataPtr, dataLength)` rather then HEAP.slice.  It that works maybe want some modification to the API to allow such a thing

**Comment by vertexpotato** [comment]
After investigating the onerror callback, I did the following : 

```
        void downloadFailed(emscripten_fetch_t* fetch) {
            printf("Downloading %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
            std::cout << resp->responseData << std::endl;

            std::cout << fetch->__attributes.requestData << std::endl;
            emscripten_fetch_close(fetch); // Also free data on failure.
        }
```
```fetch->__attributes.requestData``` was a null pointer, I was assigning the attribute.requestData in the wrong way, I should have allocated memory for it before assigning the json paylod because I was using the non blocking fetch... 

this is how I fixed it :

```
                const char* data = requestdata.c_str();
                attr.requestData = (const char*)malloc(requestdata.size() * sizeof(char));
                strcpy((char*)attr.requestData, data);
                attr.requestDataSize = strlen(attr.requestData);
```

do I have to manually free ```attr.requestData``` by myself ? or emscripten takes care of it in the ```emscripten_fetch_close()``` function ?

**Comment by sbc100** [comment]
It looks like its up to you to free the requestData
