### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by victorsand** [emscripten-core/emscripten#1659]
Hi, friends!

It seems like Emscripten does not output strict mode compatible code (testing test/hello_world.cpp etc). Is this correct and if so, are there ways to compile to strict mode compatible code?

I dug around in the src and it seems like commented "use strict" directives started showing up in some files, for example in the commit https://github.com/kripken/emscripten/blob/d2b0d9924aa9a3603b0b16bd957832faf503c32d/src/compiler.js (various fixes from js strict mode testing).

Thanks,
Victor

**Comment by VirtualTim** [comment]
> (i.e. it uses octal literals)
[Octal literals are now allowed in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_octal) (with 0o prefix).
