### ISSUE TITLE
Add `HEAP64` and `HEAPU64`

### ISSUE THREAD

**Issue by Yanis-F** [emscripten-core/emscripten#16608]
[quoting from documentation](https://emscripten.org/docs/api_reference/preamble.js.html?highlight=heapf64#type-accessors-for-the-memory-model)
> The [Emscripten memory representation](https://emscripten.org/docs/porting/emscripten-runtime-environment.html#emscripten-memory-model) uses a typed array buffer (ArrayBuffer) to represent memory, with different views into it giving access to the different types. The views for accessing different types of memory are listed below

- HEAP8: Int8Array;
- HEAP16: Int16Array;
- HEAP32: Int32Array;
- HEAPU8: Uint8Array;
- HEAPU16: Uint16Array;
- HEAPU32: Uint32Array;
- HEAPF32: Float32Array;
- HEAPF64: Float64Array;

However, a few year ago the type `BigInt` was added to javascript, allowing us to manipulate signed and unsigned 64 bit integers.
With the release of `BigInt` comes two new types: [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) and [BigUint64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array)
see [JavaScript typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)

For consistency, emscripten should add two new memory representation : `HEAP64` and `HEAPU64` which can be defined as follow:

```js
import em_factory from "./generated/emscripten"

async function main() {
    emjs = await em_factory()
    
    emjs.HEAP64 = new BigInt64Array(emjs.asm.memory.buffer)
    emjs.HEAPU64 = new BigUint64Array(emjs.asm.memory.buffer)

    // Enjoy the ability to manipulate memory as signed and unsigned 64 bits integers
}
main()

```

**Comment by kleisauke** [comment]
`HEAP64` and `HEAPU64` should already be defined when linking with `-sWASM_BIGINT`.
https://github.com/emscripten-core/emscripten/blob/acbf9e6749780f1e5d41ab941ed2f40263b62f99/src/settings.js#L1330-L1334
https://github.com/emscripten-core/emscripten/blob/acbf9e6749780f1e5d41ab941ed2f40263b62f99/src/preamble.js#L282-L285

Docs should probably be updated to reflect this as well.
