### ISSUE TITLE
EM_JS will be compiled to output a JS file that is very easy to be tampered.

### ISSUE THREAD

**Issue by fintechee** [emscripten-core/emscripten#16616]
Hi,

I have a question.

EM_JS will be compiled to output a JS file that is very easy to be tampered.
If we need to call browser's crypto.subtle object to do some signature or verification, the JS file is very easy to be bypassed.

For example, we code like this:
EM_JS(bool, main, () {
    if (veriSig()) {
        return true;
    } else {
        return false;
    }
})

The cracker may abuse this vulnerability to re-code and make the embedded function just always return "true".

Is there a better way to make this JS not that easy to tamper?
Many thanks.

**Comment by curiousdannii** [comment]
Anything on the client side can be tampered with. So do anything important to security on the server side instead.

**Comment by fintechee** [comment]
Thank you for your response.

Understood.
I didn't expect the client side EM_JS is secure enough to be prevented from tampering.

I just want to seek some better solution to make it not that easy to be tampered.
Such as, why not put the compiled EM_JS into the wasm.

**Comment by sbc100** [comment]
The compiled EM_JS would stll be a string, even if was embedded in the wasm, and as such it would still be modify-able.   Wasm files are no less modifiable than JS files. 

Another good reason not to embed the EM_JS JavsScript code inside the wasm file is that we would then require something like eval() to execute it which itself is big security risk.
