### ISSUE TITLE
std::ranges::copy and std::ranges::fill not in namespace

### ISSUE THREAD

**Issue by ITotalJustice** [emscripten-core/emscripten#16619]
hi, im having an issue building my project with emsdk, the problem comes from the error:
```
main.cpp:8:18: error: no member named 'copy' in namespace 'std::ranges'
    std::ranges::copy(a, b);
    ~~~~~~~~~~~~~^
```
i do not get this error by using clang15 without setting target to wasm32 or setting sysroot.

im using cmake, so the flags etc are generated for me. here is a short example, which causes the error
```c++
/*
/home/total/Documents/emsdk/upstream/bin/clang++ main.cpp -std=c++20 -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=8 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/compat --sysroot=/home/total/Documents/emsdk/upstream/emscripten/cache/sysroot
*/

/*
main.cpp:10:18: error: no member named 'copy' in namespace 'std::ranges'
    std::ranges::copy(a, b);
*/
#include <algorithm>
#include <ranges>

int main(int argc, char** argv) {
    int a[4];
    int b[4];
    std::ranges::copy(a, b);
    return 0;
}

```

**Comment by david-fong** [comment]
Is there an open issue for the update to LLVM 14.0? I'd also like to be able to use some newer standard library features. I kind of doubt there's any way I can help but do let me know if there is!

**Comment by sbc100** [comment]
Coincidentally that update just landed in #17000!

**Comment by sbc100** [comment]
The next release of emscripten (3.1.11) will contain the fix (you can try it now with `emsdk install tot`).

**Comment by david-fong** [comment]
ah that's fantastic! Thank you guys for your work :) It looks like latest already points to 3.1.11 now.

Side question- what does "tot" mean and how is it different from "latest"?

**Comment by ITotalJustice** [comment]
> ah that's fantastic! Thank you guys for your work :) It looks like latest already points to 3.1.11 now.
> 
> Side question- what does "tot" mean and how is it different from "latest"?

tot= tip of the tree. im guessing it pulls from master branch, rather than any specific release
