### ISSUE TITLE
[Question] How to add custom preprocessor macro?

### ISSUE THREAD

**Issue by wxfred** [emscripten-core/emscripten#16626]
I‘m using **emcc** command to compile my c project on **PowerShell**, is there any option to add preprocessor macro? There are some macros deel with platform in my codes. Any advice is appreciated.

**Comment by sbc100** [comment]
emcc supports the same arguments clang/gcc for defining preprocessor macros.  For example `-DFOO=bar` to define `FOO` to `bar`.

If you are looking for detect emscripten you can use `#ifdef __EMSCRIPTEN__` or you can detect WebAssembly in general using `#ifdef __wasm__`.
