### ISSUE TITLE
Add SDL_list.{c,h} to sdl2.py

### ISSUE THREAD

**Issue by 1bsyl** [emscripten-core/emscripten#16646]
two new files: 
src/SDL_list.c
src/SDL_list.h
because of this SDL2 files added (https://github.com/libsdl-org/SDL/commit/1c9299b00d95485447f5b1b915d80c4cda3df8c9) ,  you'll probably need to add it to :
https://github.com/emscripten-core/emscripten/blob/main/tools/ports/sdl2.py

cc @ericoporto

**Comment by ericoporto** [comment]
@1bsyl this can be closed now.

**Comment by 1bsyl** [comment]
@ericoporto thanks
