### ISSUE TITLE
Error only when optimized with -O2 flag

### ISSUE THREAD

**Issue by irniat** [emscripten-core/emscripten#16648]
Hello,

I have a project that is compiling successfully on -O0 flag, but runs into compiler error on -O2 and above flag
The error is quite encryptic

> Fatal: Module::getFunction: (null Name) does not exist
> emcc: error: '/<redacted>/tools/emsdk/linux_buck_transform#link-tree/xplat/tools/emsdk/binaryen/Toolchains/emsdk-Asserts.xctoolchain/usr/bin/wasm-opt --strip-dwarf --post-emscripten --no-exit-runtime -O2 --low-memory-unused --zero-filled-memory --strip-debug --strip-producers <redacted>/output.wasm -o <redacted>/rsys_translator.wasm --mvp-features' failed (1)

I know which line is causing the error (because commenting out that line fixes the issue), but that line calls into a deep stack and I don't know exactly which part of that stack is causing the error.

Any pointer on how to debug this? Let me know if you need more information.

Thank you!

**Comment by irniat** [comment]
Here's more information if that helps:

- Seems like the error happened during the binaryen step
`
emcc:DEBUG: using binaryen
building:DEBUG: saving debug copy .../output.js#binary/emscripten_temp/emcc-4-pre-byn.wasm
Fatal: Module::getFunction: (null Name) does not exist
emcc: error: '.../tools/emsdk/macos_buck_transform#link-tree/xplat/tools/emsdk/binaryen/Toolchains/emsdk-Asserts.xctoolchain/usr/bin/wasm-opt --strip-dwarf --post-emscripten --no-exit-runtime -Oz --low-memory-unused --zero-filled-memory --strip-debug --strip-producers .../output.wasm -o .../output.wasm --mvp-features' failed (1)
profiler:DEBUG: block "binaryen" took 0.29 seconds
profiler:DEBUG: block "post_link" took 1.29 seconds
`
- Running the same command on the saved debug file **emcc-0-base.wasm**, generated by -O2 flag, also returned an error.
- Running the same command on the saved debug file **emcc-0-base.wasm**, generated by -O0 flag, did not return an error.

Therefore, my guess is that when compiling with -O2 flag, the name of the function causing the error was stripped out at the very beginning of all compilation steps. But I don't know how to figure out the name of that function, nor why its name is null. Any pointers would be greatly appreciated :)

**Comment by kripken** [comment]
Sounds like a bug in wasm-opt, since you have a specific command that fails. Please provide that `emcc-0-base.wasm` so that we have a way to reproduce the bug.

(If you can't provide the full file, perhaps you can extract a small testcase from it, either manually or using [wasm-reduce](https://github.com/WebAssembly/binaryen/wiki/Fuzzing#reducing).)

**Comment by irniat** [comment]
Attached are the emcc-0-base outputs from failed run and successful run

[emcc-0-base.wasm-error.zip](https://github.com/emscripten-core/emscripten/files/8413980/emcc-0-base.wasm-error.zip)
[emcc-0-base.wasm-success.zip](https://github.com/emscripten-core/emscripten/files/8413985/emcc-0-base.wasm-success.zip)

**Comment by kripken** [comment]
Trying to reproduce this, I see that `--no-exit-runtime` no longer exists, and it was removed a while ago, so I suspect you are on an older version? What version are you on?

Using the latest code, I don't see an error with `-O2` and the rest of those flags. So this may be a bug that has been fixed meanwhile.

**Comment by irniat** [comment]
Thank you so much for helping me. I'm indeed using an older version, 2.0.21, and when compiling using the latest version I don't see such error.
