### ISSUE TITLE
is pthread_mutex_lock  supported in Emscripten?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#16652]
If i call the 'play' API and 'stop' API async , that mean i call the 'Stop'API  when the 'play' API is not return, the browser will crash. so we want to use the `pthread_mutex_lock` , but i find it doesn't work ? so do you konw why ?

**Comment by connorjclark** [comment]
I don't understand your example, but yes locking should work. You probably have a deadlock? Compile with -g and pause your threads to see where the deadlock may be.

If your program is using conditional variables (locks) you may be running into this issue: https://github.com/libsdl-org/SDL/issues/5428
