### ISSUE TITLE
timer_create/timer_settime is not define while compiling c source code

### ISSUE THREAD

**Issue by versaloon** [emscripten-core/emscripten#16663]
Below is the last lines outputted while compiling:

utilities/template/vsf_queue.c.o  -o vsf_template.js  libvsf_host_linux.a  -lpthread  -lrt  -lm && :
error: undefined symbol: timer_create (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _timer_create may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: timer_settime (referenced by top-level compiled C/C++ code)
warning: _timer_settime may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/home/simonqian/emsdk/node/14.18.2_64bit/bin/node /home/simonqian/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpnr_lkrhk.json' failed (returned 1)
ninja: build stopped: subcommand failed.

If I remove call to timer_create and timer_settime, compiling will be OK.
Is there any options I missed in cmake? I have -lrt in the link command line.

emcc -v:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/simonqian/emsdk/upstream/bin

**Comment by aharondavid** [comment]
I have the same problem.
the `-lrt`  doesn't include in C:\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten

**Comment by sbc100** [comment]
Indeed, emscripten does not currently include the timer functions: `timer_create.c`, `timer_getoverrun.c`, `timer_settime.c`, `timer_delete.c`, `timer_gettime.c`.   

This is most likely because these functions (largely) depend on asynchronous signals which emscripten doesn't support.    What applications are you compiling that requires these functions?  Can it be configured not to use them?   It could be possible to make these at least partially work under emscripten, but it could be tricky.

**Comment by versaloon** [comment]
> Indeed, emscripten does not currently include the timer functions: `timer_create.c`, `timer_getoverrun.c`, `timer_settime.c`, `timer_delete.c`, `timer_gettime.c`.
> 
> This is most likely because these functions (largely) depend on asynchronous signals which emscripten doesn't support. What applications are you compiling that requires these functions? Can it be configured not to use them? It could be possible to make these at least partially work under emscripten, but it could be tricky.

I commented out the related functions, and it works OK without timer feature. If these functions are not implemented, are there any other functions can be used to implement a timer? I can implement a work around for emscripten.

**Comment by sbc100** [comment]
Yup, see `emscripten_set_timeout` in `emscripten/eventloop.h` for a more JS-friendly API.

**Comment by aharondavid** [comment]
Understood.
Thanks

**Comment by versaloon** [comment]
> Yup, see `emscripten_set_timeout` in `emscripten/eventloop.h` for a more JS-friendly API.

Thanks.
