### ISSUE TITLE
Alignment error with emscripten exceptions + -O2 + SAFE_HEAP

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#16685]
After investigating the [testsuites bot failure](https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8817505275249906481/+/u/Emscripten_testsuite__SAFE_HEAP_/stdout) of `core2s.test_exceptions_multiple_inherit`, this is what we found.

#16611 increased the size of `struct __cxa_exception` from 16 to 20, which means that `__cxa_allocate_exception` in library_exceptions.js now returns a pointer that is 20 bytes into the result of `malloc` rather than 16 bytes into the result of `malloc`. Meanwhile -O2 causes an 8-byte write to the beginning of the allocated exception. Since that's no longer 8-byte aligned, SAFE_HEAP throws an error. A likely fix would be to update `__cxa_allocate_exception` to ensure that its result is still 8-byte aligned, no matter what size the `struct __cxa_exception` is.

However, it's still unclear why SAFE_HEAP assumes the alignment of the store should be 8, given that the alignment of `struct __cxa_exception` seems like it should be only 4.

**Comment by chenzx** [comment]
use `-sSAFE_HEAP=2`, which is for wasm only, `-sSAFE_HEAP=1` is for asm.js & wasm, which may be not a real alignment error

**Comment by sbc100** [comment]
I believe this was fixed in #16770.  Please re-open if you disagree.
