### ISSUE TITLE
bug: Emscripten doesn't generate PIC libc

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#16680]
Tested 
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.9-git (7e4a0ae4bdd99abbbf299c025aa2ce7b339c8521)
clang version 15.0.0 (https://github.com/llvm/llvm-project b2a7f1c3904ede781565c6ed772f155167aa8325)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/hood/Documents/programming/emsdk/upstream/bin
```

Example:
test.c:
```
int f(x){
	return x+4;
}
```

```
emcc -c test.c -o test.o -fPIC
emcc test.o -o test.so -sSIDE_MODULE=1 -lc
```
fails with:
```
wasm-ld: error: unable to find library -lc
emcc: error: '/src/emsdk/emsdk/upstream/bin/wasm-ld -o tst.so --whole-archive tst.o -lc -L/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic --no-whole-archive -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --import-memory --strip-debug --export-all --no-gc-sections --experimental-pic -shared' failed (returned 1)
```

**Comment by hoodmane** [comment]
Or probably it makes no sense to link `-lc` against a side module and we should be filtering out?

**Comment by kripken** [comment]
Does replacing `-fPIC` with `-sMAIN_MODULE` fix this perhaps? (we don't have full dynamic linking support, just the limited model of main and side modules)

**Comment by hoodmane** [comment]
So perhaps I should close this as resolved?

**Comment by kripken** [comment]
Oh, ignore my comment on main module, I misread those commands...

I'm not sure where we landed on automatically ignoring redundant link libraries like `-lc`. @sbc100 ?

**Comment by sbc100** [comment]
When building a side module we don't add `-lc` automatically like we do normally.   However, if you explicitly ask for it we don't ignore it.  

I think its probably bug that we don't auto-build wasm32-emscripten/pic/libc.a here.

**Comment by sbc100** [comment]
On the other hand you almost certainly don't want to be including libc in your side module... I'm not sure if its best to just ignore it or to give a warning in this case?

**Comment by hoodmane** [comment]
Yeah we are filtering it out. Maybe dropping it and printing a warning would be best?

**Comment by kleisauke** [comment]
I think PR #19405 might be an alternative solution for this.

**Comment by kleisauke** [comment]
Or, if possible(?), perhaps we could avoid that rust passes `-lc` to the linker.
```console
$ rustc --target=wasm32-unknown-emscripten --crate-type staticlib --print native-static-libs - < /dev/null
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lc
```

**Comment by hoodmane** [comment]
Well the rust people rejected my suggestions to adjust rust since in their opinion passing `-shared -lc` is totally reasonable. I think it is reasonable: 
```
gcc -shared -lc side.c -o side.so
``` 
works fine and same with clang. So Emscripten is really doing the wrong thing here by failing. We currently pass `-Z link-native-libraries=no` but this requires using nightly rust.

I also don't think #19405 is the right solution for this particular problem because we don't really want or need to actually link anything extra into the `.so` file. The native compilers produce exactly the same output whether `-lc` is passed or not and Emscripten should too IMO.

**Comment by hoodmane** [comment]
But #19405 does look independently helpful. I guess we should check if the #19405 solution has the same code size in the output as this solution. If they are the same code size, then that solution is indeed strictly better.

**Comment by hoodmane** [comment]
Out of curiousity does passing `-lc` when linking a main module (or with no dylink) change the behavior in any way? What does `-lc` actually do?

**Comment by sbc100** [comment]
`-lc` resolves of `libc.a` that contains our modified version of musl libc.  It defined everything from `printf` to global such as `stdout`

**Comment by sbc100** [comment]
In emscripten we don't build libc as a side module (shared library) but always link it statically into the main module.

**Comment by hoodmane** [comment]
> always link it statically into the main module

"always" as in independently of whether `-lc` is passed or not?

**Comment by hoodmane** [comment]
Ah I see from #19414 that `-lc` does something when `-nostdlib` or `-nodefaultlibs` is passed. That answers my question.

**Comment by hoodmane** [comment]
This doesn't seem to reproduce anymore, so I'll close it as fixed.
