### ISSUE TITLE
std::string does not have operator<=>

### ISSUE THREAD

**Issue by Sainan** [emscripten-core/emscripten#16692]
Trying to compile the following valid C++20 code with emscripten

```CPP
std::string("abc") <=> std::string("def")
``` 

results in

> error: invalid operands to binary expression ('std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') and 'std::string')

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 (d33328b22db1aa62a51c50731e9645951a2038bc)
clang version 15.0.0 (https://github.com/llvm/llvm-project f3bc7fd5465a3a919388b6a0307553ef4a6d39c9)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by Sainan** [comment]
I'm assuming this is just an artifact of clang claiming to support C++20 while not supporting all of its features. Just gonna keep compiling as C++17.

**Comment by sbc100** [comment]
Yeah, it looks like llvm/libc++ has not added support yet (or at least not in version 14 which we are using).
