### ISSUE TITLE
Support generation of both DWARF and source maps in a single invocation

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#16699]
Currently you can build either with DWARF or source maps debugging information, but not both. But this limitation is artificial (since the source map is actually generated from a DWARF line table), so it should be straightforward to just not strip the DWARF after generating the source map.  One possible use case is to have full dwarf info for part of the binary, and source maps for all of it.

**Comment by mmarczell-graphisoft** [comment]
Is there a workflow where these two formats can be simultaneously used for the same code?
For example, I am developing in VSCode which only understands sourcemaps. It would be better than the current situation, if I could set breakpoints in VSCode, and then only after breaking, switch to Chrome DevTools to see variable values. It would also be great if when I set a C++ breakpoint in Chrome, but there is a VSCode debugger attached too, breaking in Chrome did not completely freeze the VSCode debugger and in turn the stepping feature in Chrome.

**Comment by dschuff** [comment]
I am not sure how the Chrome debugger interacts with external debuggers. Maybe @pfaffe has an idea.
