### ISSUE TITLE
Disable import/export name mangling in -O3 builds

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#16695]
I am working with a custom runtime and would like to disable the name mangling in the generated runtime, i.e., the renaming of imports/exports inside the WebAssembly module to `a`, `b`, `c`, etc. While `STANDALONE_WASM` sounds ideal for this use case, unfortunately it is nowhere near ready for more complicated applications that need runtime support for Pthreads and Asyncify. Is there a hack or a workaround to disable this name mangling so that the module imports/exports have deterministic names?

**Version of emscripten/emsdk:**
>emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1 (5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2)
clang version 14.0.0 (https://github.com/llvm/llvm-project d98dfb2baabb647a6ac4c4f4399999cfc44433db)
Target: wasm32-unknown-emscripten
Thread model: posix

**Comment by allsey87** [comment]
There is an option in one of the Binaryen tools [wasm-emscripten-finalize.cpp on line 60](https://github.com/WebAssembly/binaryen/blob/main/src/tools/wasm-emscripten-finalize.cpp#L60) that could be relevant. Also this issue is marked as relevant in the code: https://github.com/WebAssembly/binaryen/issues/3043.

**Comment by kripken** [comment]
You can build at `-O2` instead of `-O3` to disable that optimization.

**Comment by sbc100** [comment]
We did have another request to explicitly disable this minification from @eyebrowsoffire.. should we consider making this separately configurable?

**Comment by kripken** [comment]
I guess that would mean moving `MINIFY_WASM_IMPORTS_AND_EXPORTS` from an internal setting to an external one (plus some minor changes in emcc.py). I wouldn't be opposed, but it is a new public setting. Is `-O2` not good though, @eyebrowsoffire ?

**Comment by medmunds** [comment]
For anyone else running into this, if you want to disable `wasmImports` name minification/mangling while still using `-O3` or higher, either of these link options seems to do the trick (tested with emscripten/emsdk:4.0.8):
- `-sASSERTIONS`
- `-lexports.js`

There are several other interdependent public settings that should prevent enabling the internal `MINIFY_WASM_IMPORTS_AND_EXPORTS` setting: see the "[enable minification](https://github.com/emscripten-core/emscripten/blob/3e1cffc7598dd10c1d5e082d2d2cfd11ead1297a/tools/link.py#L1497-L1510)" logic in tools/link.py.

[Also, the earlier reference to `--minimize-wasm-changes` in wasm-emscripten-finalize.cpp no longer seems to apply.]
