### ISSUE TITLE
Regression: --profiling-funcs no longer works as it is supposed to

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#16722]
The build option `--profiling-funcs` was originally added way back in https://github.com/emscripten-core/emscripten/commit/f35e8bd6c438e1c4bee354b2bb9139bcaf4908b8 with the purpose that it would be a flag that did not hinder any performance or code size optimizations, except that it would have only the one specific effect that it would retain the embedded function symbols in the generated .wasm file, so that browsers console logs and profiling tools would readily show callstacks properly (instead of the `wasm-function[2342]` strings)

That is, one could be 100% sure that if profiling a `-O3 --profiling-funcs` or a `-Oz --profiling-funcs` build, that they would get the exact same optimizations and code size that they would get in just `-O3` or `-Oz`, but that only the function names were added/retained as extra size overhead.

Later when wasm came about, this translated to only having the wasm name section, that one could strip away after the build (with `llvm-strip --strip-all x.wasm -o x.stripped.wasm`), and get effectively the same .wasm that would have been built with `-O3` and `-Oz` as if `--profiling-funcs` had not been passed.

Looks like that intent has been lost at some point, and now one gets

```
$ emcc tests/hello_world.c -o a.html -O3 --profiling-funcs
emcc: warning: running limited binaryen optimizations because DWARF info requested (or indirectly required) [-Wlimited-postlink-optimizations]
```

but the intent of `--profiling-funcs` was that it would not limit any optimization passes?

**Comment by kripken** [comment]
I think that warning is spurious. It should only affect DWARF, not the name section. I opened #16727 now.

There should be tests that verify that `--profiling-funcs` does not alter anything but add the name section - if we don't have any atm that might be good to add (a test could literally build with and without it and then strip the names section, then compare).
