### ISSUE TITLE
std::filesystem::recursive_directory_iterator throws `attempting recursion into "/proc/self/fd": Not a directory`

### ISSUE THREAD

**Issue by debevv** [emscripten-core/emscripten#16730]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/valerio/opt/emsdk/upstream/bin

The C++ code throws when `std::filesystem::recursive_directory_iterator` reaches the `/proc/self/fd` folder. This is the `what()` of the exception:
```
filesystem error: in recursive_directory_iterator::operator++(): attempting recursion into "/proc/self/fd": Not a directory
```
But `/proc/self/fd` is usually a directory, right? The same code on Linux x86_64 iterates the directory with no errors.

This is the command line I'm using to build the application:
```
em++ -v -fexceptions --std=c++17 iterator.cpp -o iterator.html
```

I attached some sample code and the output of the build with the `-v` flag: [iterator.zip](https://github.com/emscripten-core/emscripten/files/8492351/iterator.zip)

**Comment by pweiskircher** [comment]
Got a very similar issue here.

**Comment by pweiskircher** [comment]
Using latest version (3.1.8) fixed this for me.
