### ISSUE TITLE
Races between proxying and thread initialization result in dropped work

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#16765]
When proxying work to a thread that has not finished initializing, the postMessage notification to execute the queue on the uninitialized target thread is dropped and the work is never executed unless the target thread explicitly calls `emscripten_proxying_execute_queue`. This is a big footgun in the API because it is a common pattern to spawn a worker thread and immediately send it work, so it would be nice to handle these races without user intervention.

The only way I can think of to handle races automatically would be to store a list of `processProxyingQueue` messages that come in while the thread is uninitialized in JS, then have the pthread runtime process that list after the thread is initialized but before calling the pthread main function. @sbc100, what do you think of that solution? Is there a way to differentiate between threads that have not yet been initialized and threads that have died?

**Comment by sbc100** [comment]
Oh wait because the message itself has the queue pointer.. and there is no global list of queues?

**Comment by sbc100** [comment]
Can we add `emscripten_proxying_execute_all_queues` and call that before main?

**Comment by tlively** [comment]
That would be possible, but it would be unfortunate to have to check every queue in the system at thread startup rather than just those queues that have work for that thread. It would be possible to keep track of queues per-thread to avoid that unnecessary work, but it would be a lot simpler to do that in JS rather than C. This is all about dealing with postMessages on workers without live runtimes, so it seems reasonable for this to be handled in JS rather than C.

**Comment by sbc100** [comment]
Can you explain a little bit more about how the race occurs?   Surely the `run` command will always arrive before the `processProxyingQueue` command since `run` should always be sent before pthread_create returns?

**Comment by tlively** [comment]
`pthread_create` calls `__pthread_create_js`, which either calls $spawnThread` or `$pthreadCreateProxied`, which synchronously proxies `$spawnThread` to the main thread. So either way `$spawnThread` is synchronously executed before `pthread_create` returns.

If the worker has already been loaded, `$spawnThread` sends the `run` message to the worker. This is till during `pthread_create`,  so assuming postMessages are FIFO, the pthread will initialize and start running before any notifications for subsequently proxied work are received.

However, the race condition happens when the worker has not already been loaded. In that case, `$spawnThread` returns without sending the `run` command, instead leaving the `run` command to be sent asynchronously in response to the worker reporting `loaded`. In that case, `pthread_create` returns before the `run` command is sent, so any subsequently proxied work will produce notifications that arrive before `run`.

**Comment by tlively** [comment]
I guess it's not really a race, per se. When using `PROXY_TO_PTHREAD`, spawning a thread that requires a fresh worker then trying to proxy work to that thread will deterministically result in the work being dropped.

**Comment by sbc100** [comment]
I see.. so the problem only occurs when workers are first used.. and not when they are recycled.   In that case yes I think it should possible to detect that state.   We already have `initializedJS` which is used only when EMBIND is used.. but something like that could be used to detect this startup state.

**Comment by sbc100** [comment]
Ah I see.   So we would also handle processProxyingQueue by adding them to a queue when a thread is inactive?   And alwasy run the queue before calling main?

What happens if a detached thread exits while another thread is attempted to queue work on it?   I guess that is undefined behaviour?

**Comment by tlively** [comment]
Yep, that's exactly what I have in mind.
