### ISSUE TITLE
Bug in page:Advanced APIs - not showing method descriptions

### ISSUE THREAD

**Issue by connorjclark** [emscripten-core/emscripten#16785]
https://emscripten.org/docs/api_reference/advanced-apis.html#advanced-file-system-api

<img width="785" alt="image" src="https://user-images.githubusercontent.com/4071474/164646841-b3093441-bf72-4228-bce2-0103d2b83bc7.png">

URL: ../../docs/api_reference/advanced-apis

**Comment by kripken** [comment]
It may be good to document these, but they are for the old FS that we hope to replace with WasmFS in the not far future. The API there may look somewhat different - that's not clear yet. So it's probably best to wait for WasmFS to stabilize before any efforts here.

**Comment by connorjclark** [comment]
I assumed this page was previously showing descriptions. The odd mouse hover behavior resulting in layout shifting + lack of text/links to somewhere with text made me think this page had a bug, but it sounds like there was never text here? looking at the source I can see that more clearly now https://github.com/emscripten-core/emscripten/blob/main/site/source/docs/api_reference/advanced-apis.rst#advanced-file-system-api

maybe good to modify how that markdown is displayed in the docs, because the current UI made me think something was wrong. For example, if these were not inlined it'd be easier to read. Maybe newlines in the markdown would do that? That would also fix the layout shifting.

**Comment by sbc100** [comment]
FYI, this page is generated from ReST that lives here: https://raw.githubusercontent.com/emscripten-core/emscripten/main/site/source/docs/api_reference/advanced-apis.rst.

**Comment by kripken** [comment]
@connorjclark Oh, that's funny, I also thought it was a bug on the page before I read the source... yes, I agree it would be good to figure out some way to improve the display. Or perhaps we could add a TODO in that section. Removing it for now would also be an option.
