### ISSUE TITLE
glBufferSubData overflows when size == 0

### ISSUE THREAD

**Issue by paradust7** [emscripten-core/emscripten#16799]
The optimization for WebGL2 is incorrect in the case of size == 0, because WebGL2 interprets size 0 as "the entire array buffer from the offset until the end".

https://github.com/emscripten-core/emscripten/blob/ec0d9c7d352d0fb694c3493f21d8ba8279e57589/src/library_webgl.js#L1803A

Original commit that added this line:
https://github.com/emscripten-core/emscripten/commit/38b559ca862264ff939bd297d6211ec47cd0b245

Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.8 (3ff7eff373d31d8c0179895165462019221f192e)
clang version 15.0.0 (https://github.com/llvm/llvm-project 80ec0ebfdc5692a58e0832125f2c6a991df9d63f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/mtuser/emsdk/upstream/bin

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
I recall we had a conversation some time before about this? or even a PR, or something?

Anyhow, authored #16837 which goes through all the different WebGL 1&2 API functions that suffer from this issue.

**Comment by juj** [comment]
> Original commit that added this line: https://github.com/emscripten-core/emscripten/commit/38b559ca862264ff939bd297d6211ec47cd0b245

That commit is not related, the issue has existed since the advent of WebGL 2.
