### ISSUE TITLE
Improvements to glfw keyboard input.

### ISSUE THREAD

**Issue by blitz-research** [emscripten-core/emscripten#16805]
Hi,

The GLFW onKeyDown handler has some code in it to prevent certain keys from being sent to the browser and acted upon, currently just backspace and tab.

I've found this to be very incomplete though, in particular arrow keys, space bar and home/end still cause problems so I expanded on it a bit.

Also, I'm using ImGui in my project and that expects space key to be sent via the 'character' callback so I had to fudge that too. My new hack is:

    if([8, 9, 32, 33, 34, 35, 36, 37, 38, 39, 40, 45, 46].includes(event.keyCode)) {

      if(event.keyCode === 32){
        getWasmTableEntry(GLFW.active.charFunc)(GLFW.active.id, event.keyCode);
      }

      event.preventDefault();
    }

This just replaces the existing code at the end of onKeyDown. 

Be nice to see this incorporated in the release, but in the meantime I'm posting this here in case someone finds it useful - it's been driving me nuts on and off for years!

Bye,
Mark

**Comment by kripken** [comment]
A PR with this would be welcome! It may also be a good idea to compare to what the SDL2 backend does.

**Comment by blitz-research** [comment]
OK, I created a PR for this, added some notes about SDL too.
