### ISSUE TITLE
segfault in wasm-opt when compiling simple app with emscripten 3.1.9 on M1 Mac

### ISSUE THREAD

**Issue by DoDoENT** [emscripten-core/emscripten#16826]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.9 (54675bac246e84ca024c182e477665d21fe2e2f7)
clang version 15.0.0 (https://github.com/llvm/llvm-project faef447e72a5c63dfb12bb7b02d44c3c916d31cd)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin
```

**Failing command line in full:**
```
/Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin/wasm-opt --strip-dwarf --post-emscripten -O3 --low-memory-unused --zero-filled-memory --strip-debug --strip-producers bin/test_package.wasm -o bin/test_package.wasm --mvp-features
```

**Stack trace of the above command when run under `lldb`:**
```
[dodo@nm-nmiksa: 560714e5e74630bfce1eb427be0d90b26aaf1627 (master)]$ lldb -- /Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin/wasm-opt --strip-dwarf --post-emscripten -O3 --low-memory-unused --zero-filled-memory --strip-debug --strip-producers bin/test_package.wasm -o bin/test_package.wasm --mvp-features                       
(lldb) target create "/Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin/wasm-opt"
Current executable set to '/Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin/wasm-opt' (arm64).
(lldb) settings set -- target.run-args  "--strip-dwarf" "--post-emscripten" "-O3" "--low-memory-unused" "--zero-filled-memory" "--strip-debug" "--strip-producers" "bin/test_package.wasm" "-o" "bin/test_package.wasm" "--mvp-features"
(lldb) run
Process 82956 launched: '/Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin/wasm-opt' (arm64)
Process 82956 stopped
* thread #3, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001b6b914f4 libunwind.dylib`libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE(libunwind::LocalAddressSpace&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::FDE_Info*, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::CIE_Info*) + 48
libunwind.dylib`libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE:
->  0x1b6b914f4 <+48>: ldr    w22, [x23], #0x4
    0x1b6b914f8 <+52>: cmn    w22, #0x1
    0x1b6b914fc <+56>: b.eq   0x1b6b91620               ; <+348>
    0x1b6b91500 <+60>: cbz    x22, 0x1b6b9162c          ; <+360>
  thread #5, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001b6b914f4 libunwind.dylib`libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE(libunwind::LocalAddressSpace&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::FDE_Info*, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::CIE_Info*) + 48
libunwind.dylib`libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE:
->  0x1b6b914f4 <+48>: ldr    w22, [x23], #0x4
    0x1b6b914f8 <+52>: cmn    w22, #0x1
    0x1b6b914fc <+56>: b.eq   0x1b6b91620               ; <+348>
    0x1b6b91500 <+60>: cbz    x22, 0x1b6b9162c          ; <+360>
Target 0: (wasm-opt) stopped.
(lldb) bt
* thread #3, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001b6b914f4 libunwind.dylib`libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE(libunwind::LocalAddressSpace&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::FDE_Info*, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::CIE_Info*) + 48
    frame #1: 0x00000001b6b9359c libunwind.dylib`libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step() + 204
    frame #2: 0x00000001b6b95314 libunwind.dylib`_Unwind_RaiseException + 468
    frame #3: 0x00000001ac03ebc0 libc++abi.dylib`__cxa_throw + 132
    frame #4: 0x0000000100239020 wasm-opt`wasm::ConstantExpressionRunner<wasm::PrecomputingExpressionRunner>::trap(char const*) + 32
    frame #5: 0x0000000100238eec wasm-opt`wasm::ExpressionRunner<wasm::PrecomputingExpressionRunner>::visit(wasm::Expression*) + 1464
    frame #6: 0x0000000100237d78 wasm-opt`wasm::Precompute::precomputeExpression(wasm::Expression*, bool) + 148
    frame #7: 0x00000001002379d4 wasm-opt`wasm::Precompute::visitExpression(wasm::Expression*) + 168
    frame #8: 0x0000000100235400 wasm-opt`wasm::Walker<wasm::Precompute, wasm::UnifiedExpressionVisitor<wasm::Precompute, void> >::walk(wasm::Expression*&) + 172
    frame #9: 0x0000000100234fcc wasm-opt`wasm::WalkerPass<wasm::PostWalker<wasm::Precompute, wasm::UnifiedExpressionVisitor<wasm::Precompute, void> > >::runOnFunction(wasm::PassRunner*, wasm::Module*, wasm::Function*) + 52
    frame #10: 0x0000000100066ba4 wasm-opt`wasm::PassRunner::runPassOnFunction(wasm::Pass*, wasm::Function*) + 296
    frame #11: 0x00000001000671b8 wasm-opt`std::__1::__function::__func<wasm::PassRunner::run()::$_1::operator()() const::'lambda'(), std::__1::allocator<wasm::PassRunner::run()::$_1::operator()() const::'lambda'()>, wasm::ThreadWorkState ()>::operator()() + 108
    frame #12: 0x0000000100420938 wasm-opt`wasm::Thread::mainLoop(void*) + 84
    frame #13: 0x0000000100421738 wasm-opt`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(void*), wasm::Thread*> >(void*) + 52
    frame #14: 0x00000001ac08226c libsystem_pthread.dylib`_pthread_start + 148
```

**Program being compiled:**
```c++
#include <cstdlib>
#include <iostream>

int main()
{
    std::cout << "Bincrafters\n";
    return EXIT_SUCCESS;
}
```

using following `CMakeLists.txt`:

```cmake
project(test_package)
cmake_minimum_required(VERSION 2.8.11)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

set(CMAKE_VERBOSE_MAKEFILE TRUE)

file(GLOB SOURCE_FILES *.cpp)

add_executable(${PROJECT_NAME} ${SOURCE_FILES})
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```

**Environment information:**

OS: macOS
`uname -a`: `Darwin nm-nmiksa 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64`

**Comment by dasa** [comment]
I'm also running into this, and I was trying to diagnose it by following #15340, and to add to the above, with `BINARYEN_PASS_DEBUG=1`, the output when building my code is:

```
[PassRunner] running passes
[PassRunner]   running pass: generate-i64-dyncalls... 0.00668196 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: legalize-js-interface... 0.00260629 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: strip-target-features... 8.7709e-05 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: strip-dwarf...           8.1292e-05 seconds.
[PassRunner]   (validating)
[PassRunner] passes took 0.00945725 seconds.
[PassRunner] (final validation)
[PassRunner] running passes
[PassRunner]   running pass: strip-dwarf...                        0.000105166 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: post-emscripten...                    0.00043375 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: duplicate-function-elimination...     0.0126875 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: memory-packing...                     0.00450817 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: once-reduction...                     0.00168742 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: ssa-nomerge...                        0.104049 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: dce...                                0.0506759 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-names...                0.009771 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-brs...                  0.0507902 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: remove-unused-names...                0.00926546 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: optimize-instructions...              0.0635596 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: pick-load-signs...                    0.0123807 seconds.
[PassRunner]   (validating)
[PassRunner]   running pass: precompute-propagate...               em++: error: ...
```

This is the same as that older issue, but seems to be a different cause.

**Comment by kripken** [comment]
That precompute code uses exceptions, which is the one thing kind of special about it among all the other passes. So one guess is that exceptions are broken somehow on M1..?

If you build binaryen locally, does it work? Also would be interesting to know if both the wasm-opt from the emsdk and from a local build pass the binaryen test suite (run `./check.py wasm-opt` for example).

Hopefully someone with an M1 machine can look into this.

**Comment by kripken** [comment]
@sbc100 Do we run tests on M1 in our CI anywhere?

**Comment by sbc100** [comment]
No, we don't have any M1 hardware in our CI systems.  

@DoDoENT are you able to confirm if this is an issue that only effects M1 Mac?  (i.e. does it happen on x86 mac?)

**Comment by DoDoENT** [comment]
> does it happen on x86 mac?

No, it doesn't. It works correctly on Intel Mac.

> That precompute code uses exceptions, which is the one thing kind of special about it among all the other passes. So one guess is that exceptions are broken somehow on M1..?

Are you also building with custom unstable libc++ on Mac as well on Linux? I've had a similar issue on Linux before where it [clashed with custom-built libc++ in my docker](https://github.com/emscripten-core/emscripten/issues/15340#issuecomment-962103673). However, on my M1 mac, I don't have any custom-built libc++ installed anywhere on the system (I use regular Xcode 13.3.1 and it's libc++ - the same version of Xcode is installed on the Intel Mac where I tested and where everything works).

**Comment by DoDoENT** [comment]
> If you build binaryen locally, does it work? Also would be interesting to know if both the wasm-opt from the emsdk and from a local build pass the binaryen test suite (run ./check.py wasm-opt for example).
> Hopefully someone with an M1 machine can look into this.

I've built the latest `main` branch on my M1 mac (Xcode 13.3.1, apple-clang 13.1.6), and executed `./check.py wasm-opt` and it outputted a bunch of text and the last entry was `[ success! ]`, so I guess that everything works (I didn't check if there are any individual failures - I hope that the last entry wouldn't be success if anything failed).

After that, I tried using the built `wasm-opt` manually instead of the one distributed with emscripten to process my wasm file and it worked.
Then, I simply copied the built binaries from my cmake binary folder to emscripten's `upstream/bin` folder and tried running the whole compilation again and this then failed with 

```
em++: error: error running binaryen executable (/Users/dodo/.conan/data/emsdk_installer/3.1.9/microblink/stable/package/3c9d8fb1b383ce27cf8b0942dcbdbb6add8cbee9/upstream/bin/wasm-opt). Please check your binaryen installation
```

At first, I though that the reason is the dependency on `libbinaryen.dylib`, which was true, but then I rebuilt everything with `BUILD_STATIC_LIB=OFF` cmake option and ensured with `otool -L wasm-opt` that it only depends on `libc++.dylib` and `libSystem.dylib`, but it didn't help - even this binary, after moved to different folder, no longer works.

Maybe some paths get hardcoded into the binary?

I've even tried building with assertions disabled, but this fails in `Werror` mode due to some unused variables, such as: 

```
/Users/dodo/Work/CloneOuts/binaryen/src/cfg/cfg-traversal.h:271:14: warning: variable 'found' set but not used [-Wunused-but-set-variable]
        bool found = false;
             ^
1 warning generated.
```

I've even tried building with LTO enabled, but then linking fails with

```
[221/232 2.8/sec] Linking CXX executable bin/wasm-shell
FAILED: bin/wasm-shell
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBUILD_LLVM_DWARF -flto=thin -Wall -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -fno-rtti -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -Wswitch -Wimplicit-fallthrough -Wnon-virtual-dtor -fPIC -O3 -DNDEBUG -O2 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -fuse-ld=lld src/tools/CMakeFiles/wasm-shell.dir/wasm-shell.cpp.o -o bin/wasm-shell  -Wl,-rpath,@loader_path/../lib  lib/libbinaryen.a && :
ld64.lld: warning: ignoring unknown argument: -platform_version
ld64.lld: warning: ignoring unknown argument: -search_paths_first
ld64.lld: warning: ignoring unknown argument: -headerpad_max_install_names
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
lld (LLVM option parsing): Unknown command line argument '-disable-aligned-alloc-awareness=1'.  Try: 'lld (LLVM option parsing) --help'
lld (LLVM option parsing): Did you mean '--disable-inlined-alloca-merging=1'?
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[222/232 2.9/sec] Linking CXX executable bin/wasm-opt
FAILED: bin/wasm-opt
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBUILD_LLVM_DWARF -flto=thin -Wall -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -fno-rtti -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -Wswitch -Wimplicit-fallthrough -Wnon-virtual-dtor -fPIC -O3 -DNDEBUG -O2 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -fuse-ld=lld src/tools/CMakeFiles/wasm-opt.dir/fuzzing/fuzzing.cpp.o src/tools/CMakeFiles/wasm-opt.dir/fuzzing/heap-types.cpp.o src/tools/CMakeFiles/wasm-opt.dir/fuzzing/random.cpp.o src/tools/CMakeFiles/wasm-opt.dir/wasm-opt.cpp.o -o bin/wasm-opt  -Wl,-rpath,@loader_path/../lib  lib/libbinaryen.a && :
ld64.lld: warning: ignoring unknown argument: -platform_version
ld64.lld: warning: ignoring unknown argument: -search_paths_first
ld64.lld: warning: ignoring unknown argument: -headerpad_max_install_names
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
lld (LLVM option parsing): Unknown command line argument '-disable-aligned-alloc-awareness=1'.  Try: 'lld (LLVM option parsing) --help'
lld (LLVM option parsing): Did you mean '--disable-inlined-alloca-merging=1'?
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

In general, it appears that latest `main` branch of binaryen works on M1, but only if binary is used from the folder where build process put it.

**Comment by dschuff** [comment]
I can reproduce this on my M1 mac. It does appear to be crashing on throw. I suspect it has something to do with the way we build release builds (Can you verify that it does not reproduce if you use `3.1.9-asserts` from emsdk?). Recent changes include our switch to lld (https://chromium.googlesource.com/emscripten-releases/+/d2ba6f02d844850a1341d606eec4d8b742102dfb) which affects our LTO build, and our DEPLOYMENT_TARGET update (https://chromium.googlesource.com/emscripten-releases/+/d33ae3c8d16f04b004b76c1d7c1989d637aa36e0) which switched us away from our custom libcxx and back to  the SDK's version.

**Comment by dasa** [comment]
> Can you verify that it does not reproduce if you use `3.1.9-asserts` from emsdk?

This fixes it for me.

**Comment by dschuff** [comment]
Another note, I don't seem to be able to reproduce the issue when building locally, even with the waterfall build scripts, which are supposed to be hermetic. I'm going to trigger another LTO build, we'll see if it reproduces there.

**Comment by DoDoENT** [comment]
Appears to be fixed with 3.1.10

**Comment by dschuff** [comment]
Actually if you don't mind I'd like to keep this open. I worked around the problem for now by disabling building ThinLTO in the Binaryen emscripten-releases build (obviously we need to release working builds), but I don't think the underlying cause is really fixed.

**Comment by haberbyte** [comment]
Appears to be happening again with 3.1.18

**Comment by brion** [comment]
Confirmed regression in 3.1.18 (3.1.17 was fine).

``../../../dav1d/meson.build:25:0: ERROR: Compiler emcc can not compile programs.``

``checking whether the C compiler works... emconfigure: error: '../../../libogg/configure --prefix=/Users/brion/src/media/ogv.js/build/wasm/root --disable-shared' failed (returned 77)``

etc

**Comment by dschuff** [comment]
This isn't exactly the same bug, but I can confirm that the M1 build of Binaryen is broken. You should be able to work around it locally by copying libbinaryen.dylib from lib/ to bin/ in your local install. I'll try to get a fix out today.

**Comment by gobetti** [comment]
+1
3.1.17 is fine on an M1, 3.1.18 is not

**Comment by dschuff** [comment]
This should be fixed with https://github.com/emscripten-core/emsdk/pull/1083
I elected to update 3.1.18 in place, rather than roll a 3.1.19. This means if you've installed 3.1.18 with emsdk and you are affected, the fix is to first update emsdk itself, and then install 3.1.18 again. When you do that, 3.1.18 should be resolved to something like `sdk-releases-upstream-49d45744895c7d7e28acd94a385d7ee361653b4a-64bit` (and not 56271c44baca883fddb4a58d0ebc137f9ae43d1a).

If you already have 3.1.18 and it works, then you don't need to do anything, the release should be identical except for the Mac binaries.

**Comment by dschuff** [comment]
The [fix](https://chromium.googlesource.com/emscripten-releases/+/49d45744895c7d7e28acd94a385d7ee361653b4a) also fixed the original problem underlying this issue report, so I'm going to declare everything here as "fixed" and close this issue. Please reopen if the fix didn't work for you. Thanks for the report!
