### ISSUE TITLE
How to pass a JavaScript function as a function parameter of [std::function] type to C/C++？

### ISSUE THREAD

**Issue by vq0599** [emscripten-core/emscripten#16835]
Hello,

I want to pass a JavaScript function to C++ as a callback. From the [documentation](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-function-pointers-from-c), I know it is possible to add function pointers using `addfunction`:
```c++
#include <iostream>

extern "C" {
  typedef int(*callback)(int);

  int add (int a, int b, callback cb) {
    return cb(a + b);
  };
}
```
```js
const callback = Module.addFunction(v => v * 2, 'ii')
Module.add(2, 3, callback) // 10
```
And It's work well.

But when using `std::function` as the type of callback:
```c++
#include <emscripten/bind.h>
#include <iostream>

using namespace emscripten;

int add (int a, int b, std::function<int(int)> cb) {
  return cb(a + b);
};

EMSCRIPTEN_BINDINGS() {
  emscripten::function("add", &add);
}
```
```shell
# compiler CLI
emcc math.cpp --bind -s ALLOW_TABLE_GROWTH -s EXPORTED_RUNTIME_METHODS=addFunction -o math.js
```

I get a runtime error:
![image](https://user-images.githubusercontent.com/20247366/165671176-127e2291-e1c7-4f27-903f-ed99349198a0.png)

What should I do to solve this problem? Thanks.

**Comment by sbc100** [comment]
When you call `Module.addFunction` what you get is a function pointer, not a `std::function`.  The are not the same thing and trying to pass a function pointer to a function that expects a std::function won't work.

Better to expose function that take a function pointer to JS since function pointers a simple types (just pointers) whereas std::function is a more complex beast and trying to pass C++ objects like this across the JS/Wasm boundary is more involved.

**Comment by alexprogrammr** [comment]
You can achieve it using [val.h](https://emscripten.org/docs/api_reference/val.h.html) API. Define your bindings like:

```cpp
#include <emscripten/bind.h>
#include <emscripten/val.h>

int add (int a, int b, emscripten::val cb) {
  return cb.call<int>("call", 0, a + b);
};

EMSCRIPTEN_BINDINGS() {
  emscripten::function("add", &add);
}
```

Assuming that the passed object is a function, we call [call()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) method on it passing 0 as `this` argument (it doesn't make an important role for this case) and other arguments expecting by the callback. Probably, [val operator()(Args... args) const](https://emscripten.org/docs/api_reference/val.h.html#_CPPv4NK10emscripten10emscripten3valclEDpRR4Args) could also work but I didn't have a chance to play with it.

```js
const result = Module.add(2, 3, v => v * 2);
console.log(result); // 10
```

**Comment by vq0599** [comment]
Thanks for. it will work well use `emscripten::val`.

**Comment by paulocoutinhox** [comment]
Hi @vq0599 , i have the same problem. What is the second "call"?

```
return cb.call<int>("call", 0, a + b);
                                    ^
```
