### ISSUE TITLE
cmake modules add "system/include" to the include path

### ISSUE THREAD

**Issue by paradust7** [emscripten-core/emscripten#16833]
I encountered this problem trying to build something that uses OpenAL. It also appears in FindOpenGL.cmake.

https://github.com/emscripten-core/emscripten/blob/2840b1d822d037e50e7acf21e4005c7b0cef43d7/cmake/Modules/FindOpenAL.cmake#L14-L14

https://github.com/emscripten-core/emscripten/blob/2840b1d822d037e50e7acf21e4005c7b0cef43d7/cmake/Modules/FindOpenAL.cmake#L22-L22

This triggers the compile-time error:

https://github.com/emscripten-core/emscripten/blob/2840b1d822d037e50e7acf21e4005c7b0cef43d7/system/include/emscripten/version.h#L8

**Comment by sbc100** [comment]
Thanks for the report.  I guess we don't have any tests for this!
