### ISSUE TITLE
Unable to use `emstrip` in 3.1.10 (`llvm-strip` is missing)

### ISSUE THREAD

**Issue by tommitytom** [emscripten-core/emscripten#16884]
Trying to use `emstrip` in the 3.1.10 docker image, but it appears that llvm-strip is not included.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin
```

**Failing command line in full:**
```
$ emstrip
Traceback (most recent call last):
  File "/emsdk/upstream/emscripten/emstrip.py", line 14, in <module>
    sys.exit(shared.run_process(cmd, stdin=sys.stdin, check=False).returncode)
  File "/emsdk/upstream/emscripten/tools/shared.py", line 106, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/emsdk/upstream/bin/llvm-strip'
```

**Comment by sbc100** [comment]
Hmm .. yes it does seem that maybe it should be added to that list.  That doesn't explain the difference between release and tot builds though.. those should be the same ...  @dschuff could this be relates to LTO?

**Comment by dschuff** [comment]
> I think `llvm-strip` should probably be added to this list as well: https://chromium.googlesource.com/emscripten-releases/+/76991dd30f1fa44df7dcde5e12998bd67bccd6a4/src/build.py#709

Actually that line only affects the CI builds that build on every commit (these builds are optimized for build speed and package size). The tagged release builds are optimized with LTO and use different CMake commands. So we need to update the list on line 787.

**Comment by dschuff** [comment]
And I guess maybe we should have an `other` test that exercises emstrip?

**Comment by dschuff** [comment]
This is fixed now.
