### ISSUE TITLE
Are COOP/COEP headers needed for the WASM Worker API

### ISSUE THREAD

**Issue by Agupta00** [emscripten-core/emscripten#16880]
Hello, is it possible to use the WASM worker API without adding the COOP/COEP headers on my page? As I understand it I think I do since I think `SharedArrayBuffer` is [guarded under these headers](https://web.dev/coop-coep/)? 

Wasn’t 100% sure and wanted to double check since I didn’t see the warning about these headers anywhere in the source code as they are present for [pthreads](https://github.com/emscripten-core/emscripten/pull/12540/files#diff-c836356502eba3e3c9a620d07549113571f1fd60f3ff5706900f36c1e9f18449R7   Thanks!): 

Thanks!

**Comment by sbc100** [comment]
Wasm Workers uses `SharedArrayBuffer` yes.. so it has the same requirements as using pthreads.
