### ISSUE TITLE
How to use an initialized class outside of the async function?

### ISSUE THREAD

**Issue by needle1989** [emscripten-core/emscripten#16899]
I'm using the example from:https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#classes
C++ code:
```
class MyClass {
public:
  MyClass(int x, std::string y)
    : x(x)
    , y(y)
  {}

  void incrementX() {
    ++x;
  }

  int getX() const { return x; }
  void setX(int x_) { x = x_; }

  static std::string getStringFromInstance(const MyClass& instance) {
    return instance.y;
  }

private:
  int x;
  std::string y;
};

// Binding code
EMSCRIPTEN_BINDINGS(my_class_example) {
  class_<MyClass>("MyClass")
    .constructor<int, std::string>()
    .function("incrementX", &MyClass::incrementX)
    .property("x", &MyClass::getX, &MyClass::setX)
    .class_function("getStringFromInstance", &MyClass::getStringFromInstance)
    ;
}
```
JS code:
```
var myModule = require('../../legacy/dist/sample.js');
myModule.onRuntimeInitialized = async function() {
    test = new myModule.MyClass(10,"hello");
    test.incrementX();
}
```
this way the code works as expected, but how can i use the initialized class instance outside of the async function if i want to use this instance again?
```
var myModule = require('../../legacy/dist/sample.js');
myModule.onRuntimeInitialized = async function() {
    global.test = new myModule.MyClass(10,"hello");
    global.test.incrementX();
}
myModule.onRuntimeInitialized = async function() {
    global.test.incrementX();
}
```
it wont work this way...

**Comment by needle1989** [comment]
I need to call this class multiple times while modifying its private member so i'd rather not initialize a class whenever i need it...

Do i have to use onRuntimeInitialized before using the module? cause otherwise it shows:

TypeError: myModule.MyClass is not a constructor

**Comment by levno-710** [comment]
Just put your entire code into the async function

**Comment by brendandahl** [comment]
Yes, you have to wait for it to be initialized to use it. In the above code you're overwriting the onRuntimeInitialized property since you set it twice. The initialized class can be saved, but you'll need to hold on to it. e.g.

```
let myClass = new Promise((resolve) => {
  myModule.onRuntimeInitialized = () => {
    resolve(new myModule.MyClass(10,"hello"));
 }
}
```

then you can do 
```
(await myClass).incrementX();
(await myClass).incrementX();
...
```
