### ISSUE TITLE
wasm-ld reports undefined symbol: hb_icu_get_unicode_funcs but it's declared in harfbuzz port's hb-icu.h

### ISSUE THREAD

**Issue by chenzx** [emscripten-core/emscripten#16900]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
 % emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/czx/repo/emsdk/upstream/bin

**Failing command line in full:**
I'm using emscripten's harfbuzz port by `emcc -s ENVIRONMENT=web,worker --no-entry -s LLD_REPORT_UNDEFINED -s EXPORT_ES6=1 -s MODULARIZE=1 -s USE_ES6_IMPORT_META=0 -s USE_SDL=2 -s USE_FREETYPE=1 -s USE_HARFBUZZ=1 -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_ICU=1 -s USE_PTHREADS=1 -sSHARED_MEMORY -sFETCH -lembind ...`
but wasm-ld reports undefined symbol: hb_icu_get_unicode_funcs
however, it's defined in harfbuzz port's hb-icu.h

**Full link command and output with `-v` appended:**
[100%] Built target myapp
/usr/local/Cellar/cmake/3.21.1/bin/cmake -E cmake_progress_start /Users/czx/repo/myapp/wasm-build/CMakeFiles 0
czx@chenzx wasm-build % emcc -s ENVIRONMENT=web,worker --no-entry -s LLD_REPORT_UNDEFINED -s EXPORT_ES6=1 -s MODULARIZE=1 -s USE_ES6_IMPORT_META=0 -s USE_SDL=2 -s USE_FREETYPE=1 -s USE_HARFBUZZ=1 -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_ICU=1 -s USE_PTHREADS=1 -sSHARED_MEMORY -sFETCH -lembind -o myapp.js -Wl,--whole-archive libmyapp.a     
wasm-ld: error: libmyapp.a(HbFontCache.cpp.o): undefined symbol: hb_icu_get_unicode_funcs
emcc: error: '/Users/czx/repo/emsdk/upstream/bin/wasm-ld -o myapp.wasm --whole-archive libmyapp.a -L/Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2-mt.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libjpeg.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libpng-mt.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libz.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libharfbuzz-mt.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libfreetype.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libicu_i18n-mt.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libicu_stubdata-mt.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libicu_common-mt.a /Users/czx/repo/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o --whole-archive -lfetch-mt -lembind-rtti --no-whole-archive -lGL-mt -lal -lhtml5 -lstubs-debug -lnoexit -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/var/folders/qj/tzf9z8g94ns2mbxztgd1xb240000gp/T/tmp2u5wkks8.undefined --import-memory --shared-memory --strip-debug --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=_emscripten_allow_main_runtime_queued_calls --export=emscripten_main_browser_thread_id --export=emscripten_main_thread_process_queued_calls --export=emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=emscripten_builtin_memalign --export=malloc --export=free --export=memcpy --export=setThrew --export=__dl_seterr --export=saveSetjmp --export=__cxa_is_pointer_type --export=__cxa_can_catch --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (returned 1)

**Comment by sbc100** [comment]
BTW you probably want to do ` -Wl,--no-whole-archive` after `libmyapp.a` to avoid including the whole of all the system libraries.

**Comment by sbc100** [comment]
It does seem very odd that the linking is not picking up that symbol from libharfbuzz-mt.a.

Can you try adding  `-Wl,--trace-symbol=hb_ucd_get_unicode_funcs`?

**Comment by sbc100** [comment]
Ah the problem seems to be that we are building harfbuzz without icu support.  HAVE_ICU is not being defined in `tools/ports/harfbuzz.py`.

Do you need that symbol?   If so it could be possible to  build the ICU library and then rebuild harfbuzz with `HAVE_ICU` but it would most likely increase the size of you app a fair bit.  If you can instead disable the code that is referencing `hb_icu_get_unicode_funcs` it might be an easier option for you.

**Comment by chenzx** [comment]
I just want to know if there is any severe running problem if i replace hb_icu_get_unicode_funcs by hb_ucd_get_unicode_funcs, if no, then it's ok, for now.

i'm porting a legacy C++ GUI rendering engine to wasm to build a web-based UI design preview module. It currently only needs to display chinese characters, no needs for advanced unicode BIDI font support.

But i hope this can be resolved since code size is not a problem, if ICU can be bundle into .data file by --preload-file mechanism, or if chrome can load it ok...

**Comment by chenzx** [comment]
> BTW you probably want to do ` -Wl,--no-whole-archive` after `libmyapp.a` to avoid including the whole of all the system libraries.

I have not set this, myapp.wasm is 7.3MB in release version, it's ok. & I can see emcc takes LTO optimization as default when convert .a to .wasm.
