### ISSUE TITLE
getting an error when setting WASM=0

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#16919]
When trying to find any clue to a run time error: **'Uncaught unwind'** , I had set WASM=0  to get a debug call stack which I didn't get 
in WASM.
but, when setting WASM=0, I got the following error:

`[wasm-validator error in function NCompress::NBcj2::CEncoder::CodeReal\28ISequentialInStream*\20const*\2c\20unsigned\20long\20long\20const*\20const*\2c\20unsigned\20int\2c\20ISequentialOutStream*\20const*\2c\20unsigned\20long\20long\20const*\20const*\2c\20unsigned\20int\2c\20ICompressProgressInfo*\29] i32 != i64: extend type must be correct, on`

**Version of emscripten/emsdk:**
latest

link flags:
`-s WASM=0 -g  --preload-file com.skyline.terraexplorer --bind -s USE_PTHREADS     -s ALLOW_MEMORY_GROWTH=1   -s EXPORTED_RUNTIME_METHODS=ccall,cwrap -s EXPORTED_FUNCTIONS=_openFly,_main -s PTHREAD_POOL_SIZE=16  -lworkerfs.js  -lproxyfs.js -lnodefs.js -lidbfs.js  `

**Comment by kripken** [comment]
It looks like you found a bug in binaryen, likely in the wasm2js code. Can you provide the input wasm file? (You can save the temp files and see the commands with `EMCC_DEBUG=1` in the env.)

**Comment by sbc100** [comment]
Removing the `-g` should greatly reduce the size of the file.
