### ISSUE TITLE
Bug in page:Asyncify 

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#16920]
Add the following notes for `ASYNCIFY_IMPORTS`:

If the import is not inside `env` the full path must be specified, for example, `ASYNCIFY_IMPORTS=["wasi_snapshot_preview1.fd_write"]`

URL: ../../docs/porting/asyncify

**Comment by polarvoid** [comment]
Hey there, I'd love to get started with this issue. Is that all right?

**Comment by kripken** [comment]
@polarvoid Yes, that would be great!

**Comment by polarvoid** [comment]
Hey, I made a PR at #17984

While adding the note itself was really easy, getting sphinx set up correctly was a pain XD.

**Comment by kripken** [comment]
Fixed by that PR, thanks @polarvoid !

**Comment by polarvoid** [comment]
Glad to contribute :)
