### ISSUE TITLE
error when setting: -fsanitize=undefined

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#16929]
when setting `-fsanitize=undefined ` and `ALLOW_MEMORY_GROWTH `I got the following error:
`wasm-ld : error : initial memory too small, 36392192 bytes needed`
although I have a lot more then 36M bytes memory free space 

under module with `-fsanitize=undefined ` compiled successfully, but I get the run time error immediately in the initialization: 

![image](https://user-images.githubusercontent.com/41375082/167649731-25483ec9-010e-4d36-9de7-2aaf07f47f08.png)

trying to set -s SAFE_HEAP , as  alternative to `-fsanitize=undefined `, but it  significantly delay the the linking process.

**Version of emscripten/emsdk:**
latest

**Comment by ancientstraits** [comment]
@aharondavid please close the issue
