### ISSUE TITLE
Unable to export function from nested static library

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#16953]
I have the following situation where I would like to export functions from both libutils.a and libapi.a for use in Javascript. I was under the impression that if I added `-Wl,--whole-archive` and `-Wl,--no-whole-archive` during linking, the symbol for `add_two_numbers` would stick around long enough that I would be able to export it (unfortunately this doesn't seem to be the case).

The following diagram demonstrates what I am trying to do and [issue.tar.gz](https://github.com/emscripten-core/emscripten/files/8686925/issue.tar.gz) is a MRE of the problem (note that the toolchain in the MRE assumes that the esdk is installed under `/opt`)
<img src="https://user-images.githubusercontent.com/3796345/168268569-0c2fa722-79a9-4d49-8723-849138601393.svg" width="250">

Each component, utils, api, and main are separate CMake projects. In my toolchain, I have `CMAKE_EXE_LINKER_FLAGS_INIT` set as follows: 
```cmake
set(CMAKE_EXE_LINKER_FLAGS_INIT -s'EXPORTED_FUNCTIONS=[\"_main\",\"_add_two_numbers\",\"_add_three_numbers\"]'")
```
and in the CMakeLists.txt for main and api, I have linked the dependent library as follows respectively:
```cmake
target_link_libraries(main -Wl,--whole-archive ${CMAKE_SOURCE_DIR}/libapi.a -Wl,--no-whole-archive)
```

```cmake
target_link_libraries(api -Wl,--whole-archive ${CMAKE_SOURCE_DIR}/libutils.a -Wl,--no-whole-archive)
```

**Failing command line**
```bash
rm -rf main/build/* api/build/* utils/build/* && \
(cd utils/build && cmake -DCMAKE_TOOLCHAIN_FILE=../../toolchain.cmake ../src && make) && \
(cd api/build && cmake -DCMAKE_TOOLCHAIN_FILE=../../toolchain.cmake ../src && make) && \
(cd main/build && cmake -DCMAKE_TOOLCHAIN_FILE=../../toolchain.cmake ../src && make)
```
The above command line is for the MRE and fails during linking in the final step with the following error:
```
em++: error: undefined exported symbol: "_add_two_numbers" [-Wundefined] [-Werror]
make[2]: *** [CMakeFiles/main.dir/build.make:85: main.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
Everything works if I remove `_add_two_numbers` from `EXPORTED_FUNCTIONS` but that of course is what this issue is about :)
```bash
node -p "WebAssembly.Module.exports((new WebAssembly.Module(fs.readFileSync('main/build/main.wasm'))))" \
| grep add
{ name: 'add_three_numbers', kind: 'function' },
```

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.1 (5ebe1d421445fa9a4a02c1efc6d42bde3ac90da2)
clang version 14.0.0 (https://github.com/llvm/llvm-project d98dfb2baabb647a6ac4c4f4399999cfc44433db)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/emsdk/upstream/bin
```

**Related issues:**
- #13411
- #362
- #14729
- #7972

**Comment by sbc100** [comment]
Indeed, that is how static libraries generally work. 

I think that can probably be closed?

**Comment by sbc100** [comment]
Yes, you can't include a static library inside another one like this with linker flags.

There are ways to combine static librarys with the `ar` / `emar` tools if that is something you really want to do, but normally the solutions is simply include both libraries on the final link line.

**Comment by allsey87** [comment]
Thanks Sam! I will close this now.

**Comment by spirobel** [comment]
> There are ways to combine static librarys with the ar / emar tools if that is something you really want to do, but normally the solutions is simply include both libraries on the final link line.

can you give more info about how to do this? 

How do I rexport from a static library?
I try to link a library written in zig together with a library compiled with emcc. I want to rexport functions from the zig library in the final linker step for which I use emcc.
 The only difference to this gist is: https://gist.github.com/kripken/58c0e640227fe5bac9e7b30100a2a1d3#emscripten-as-a-linker-for-zig-and-c I create a .a file instead of a .o file. the issue I face is this: I have a function defined here https://github.com/spirobel/monero-zig/blob/5769f44028807afd4785ec5d387bf05dc8f4498e/src/main.zig#L20 and I want to rexport it after linking everything together here: https://github.com/spirobel/monero-zig/blob/5769f44028807afd4785ec5d387bf05dc8f4498e/build.zig#L46 but the compiler tells me the symbol is not defined: emcc: error: undefined exported symbol: "monero_base58_encode" [-Wundefined] [-Werror] 
is this a fundamental issue with static libraries? can I use zig as an entry point instead of a c file similar to here: https://github.com/floooh/pacman.zig/blob/ede394ec6c9b6a69ba69d0f9f4219d8910bea5c1/build.zig#L103 ?
thaaanks

**Comment by tjpalmer** [comment]
Somewhat related, should I be able to export a function defined in SDL? For example, part of my emcc options include `-s USE_SDL=2`, but if I say `-s EXPORTED_FUNCTIONS=_SDL_Init`, I get this message:

```
emcc: error: undefined exported symbol: "_SDL_Init" [-Wundefined] [-Werror]
```

**Comment by sbc100** [comment]
That seems to work just fine for me:

```
$ ./emcc -sUSE_SDL=2 -sEXPORTED_FUNCTIONS=_SDL_Init test/hello_world.c
```

Perhaps you could share the full command line?

**Comment by tjpalmer** [comment]
> Perhaps you could share the full command line?

Thanks much for the reply! I've tried some [variations on this command](https://github.com/contextfreecode/cobol-explore/blob/814c7415ba94da0c9e0fa1bf5dbf72350ac25f4f/scripts/build.sh#L25), which I copied from a different repo. The real goal is to get GnuCOBOL to find the SDL functions, which I suspect has to do with internal symbol lookup, but I'm not super sure.

But your example shows that things ought to work. I've mostly given up on getting the wasm build to work at the moment, but I appreciate having the reference on things in case I get back to it.

**Comment by 8Observer8** [comment]
> BTW. the -s options no longer requre quotes or braces

Thanks a lot! So, the solution is don't use quotes, braces and spaces after `-sEXPORTED_FUNCTIONS=`

CMakeLists.txt

```cmake
target_link_options(${EXECUTABLE_NAME} PRIVATE
    -sEXPORTED_FUNCTIONS=_main,_onGetMessage)
```

main.cpp

```cpp
extern "C"
{
    void onGetMessage(char *message)
    {
        emscripten_websocket_send_utf8_text(socket, message);
    }
}
```

index.html

```html
    <button id="sendMessage">Send</button><br><br>

    <script>
        const sendMessageButton = document.getElementById("sendMessage");

        sendMessageButton.onclick = () => {
            const onGetMessage = Module.cwrap("onGetMessage", null, []);
            onGetMessage(stringToNewUTF8(JSON.stringify({
                message: "hello"
            })));
        }

    </script>
```

**Comment by sbc100** [comment]
You can also remove the quotes and the braces from `EXPORTED_RUNTIME_METHODS`
