### ISSUE TITLE
URL is ignored in WasmFS Fetch Backend

### ISSUE THREAD

**Issue by mere-human** [emscripten-core/emscripten#16954]
It is not possible to fetch several different files via WasmFS Fetch Backend.
I wanted to use fetch backend for something like createLazyFile() but with WasmFS.

It seems that `base_url ` parameter is ignored in `wasmfs_create_fetch_backend()`:
https://github.com/emscripten-core/emscripten/blob/2a4e2958792f7978082d310441e3421f318a44fd/system/lib/wasmfs/backends/fetch_backend.cpp#L22
Moreover, the file URL is hardcoded to `data.dat` here: https://github.com/emscripten-core/emscripten/blob/22c23bd81cb3700b531913dc4ee43fb7af5b40f6/src/library_wasmfs_fetch.js#L29
This doesn't allow using multiple files in fetch backend.
How this could work:
* allow fetching several files by using different backends for each file (e.g. use base_url)
* allow fetching several files that are relative to the base URL (e.g. don't hardcode `data.dat`)
* or both of the above

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing code:**
```cpp
#include <assert.h>
#include <emscripten/emscripten.h>
#include <emscripten/wasmfs.h>
#include <stdio.h>
#include <sys/stat.h>

int main()
{
    auto orig = (char *)EM_ASM_INT({
        const origin = self.location.origin;
        const nb = lengthBytesUTF8(origin) + 1;
        const ptr = _malloc(nb);
        stringToUTF8(origin, ptr, nb);
        return ptr;
    });
    backend_t backend = wasmfs_create_fetch_backend(orig);

    int fd1 = wasmfs_create_file("/testfile", 0777, backend);

    struct stat st1 = {};
    assert(fstat(fd1, &st1) != -1);
    printf("file size: %lld\n", st1.st_size);

    int fd2 = wasmfs_create_file("/testfile2", 0777, backend);

    struct stat st2 = {};
    assert(fstat(fd2, &st2) != -1);
    printf("file size: %lld\n", st2.st_size);

    assert(st1.st_size != st2.st_size); // This should not fail!

    return 0;
}
```

**Full link command:**
```bash
rm -rf build
mkdir -p build
em++ -v -std=c++11  -s WASMFS=1 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD wasmfs_fetch_backend.cpp -o build/wasmfs_fetch_backend.html
cd build
echo 1 > data.dat
echo 12 > testfile
echo 123 > testfile2
emrun wasmfs_fetch_backend.html
```

**Comment by mere-human** [comment]
The reason I'm reporting it is either someone takes a look at it or I can try creating a PR for that.

**Comment by tlively** [comment]
PRs to improve the fetch backend would be very welcome! We built it to explore what building new WasmFS backends looks like, but getting it working fully is not a top priority for us, so help finishing it would be great.
