### ISSUE TITLE
use GROWABLE_HEAP_F64,but that's going to come up again "offset is out of bounds".

### ISSUE THREAD

**Issue by donghang1994** [emscripten-core/emscripten#16978]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
v3.1.0

When create double array to interacting with c++, use GROWABLE_HEAP_F64,but that's going to come up again "offset is out of bounds".

Is there a good way to pass double array with c++.
Or is there a problem with using "USE_PTHREADS" now.

**Comment by kripken** [comment]
It's hard to say if this is a bug in your application or a bug in emscripten, without more details. If you can provide a small testcase that shows the issue that would help.

**Comment by donghang1994** [comment]
> It's hard to say if this is a bug in your application or a bug in emscripten, without more details. If you can provide a small testcase that shows the issue that would help.

I'm not sure it was caused by "USE_PTHREADS=1" and "ALLOW_MEMORY_GROWTH=1".Don't you have buffer growth problems when you use it.

**Comment by kripken** [comment]
Sorry, I'm not sure what you mean?

**Comment by donghang1994** [comment]
> Sorry, I'm not sure what you mean?

Oh, I use the "-fsanitize=address" and found a lot of problems is "alloc-dealloc-mismatch (malloc vs operator delete [])". Does this create a memory leak problem?  I'm working on  fixing it.

**Comment by donghang1994** [comment]
> It's hard to say if this is a bug in your application or a bug in emscripten, without more details. If you can provide a small testcase that shows the issue that would help.

I keep requesting data in the thread, memory keeps growing. What's wrong with using this, this is my example:
https://github.com/donghang1994/emscripten-threads-test.  
@kripken @sbc100   
Please kindly help to test it.

**Comment by kripken** [comment]
How are you measuring that memory keeps growing?

If you measure using the JS devtools, they might show memory grow over time because of GC allocations. Eventually a GC will happen and it will then free those all at once.

**Comment by kripken** [comment]
Ok, sounds like that might be normal then. As long as eventually the browser does a GC and reduces that memory, it's ok. If not, then it could be a browser bug.
