### ISSUE TITLE
emscripten_webgl_commit_frame cost high CPU in -sOFFSCREEN_FRAMEBUFFER proxy mode

### ISSUE THREAD

**Issue by chenzx** [emscripten-core/emscripten#16980]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix

After successful load test of my UI engine wasm version, i tested its performance using a simple View transform animation, fps is 60, but chrome's renderer process cost CPU too high: reaching 150...

<img width="1440" alt="2022-05-19 19 23 55" src="https://user-images.githubusercontent.com/622927/169288863-4cd5d9fe-1dda-4b13-b5d5-f66ea8d03f97.png">

from chrome's perf tools, I see emscripten_webgl_commit_frame() costs almost all CPU. can it be impoved?

I'm considering to switch to `-sOFFSCREENCANVAS_SUPPORT` mode, but i have to refact the legacy code to extract a `frame_render_iteration_callback` function from the render thread code...

**Comment by kripken** [comment]
cc @juj @kainino0x who I think know that `blitOffscreenFramebuffer` code path best.

**Comment by kainino0x** [comment]
I mentioned this issue to kenrussell and he suggested that you could also track this state at the WebGL layer, in a shim under WebGL (by patching the methods on the WebGLRenderingContext). Then it doesn't matter whether the user makes additional GL calls from JavaScript, you'll still catch the state changes. It would probably be a bit more involved, but it's an option.

**Comment by chenzx** [comment]
close this issue, see https://github.com/emscripten-core/emscripten/issues/16983#issuecomment-1140370382
