### ISSUE TITLE
Help Wanted: --closure 1 and UTF8ToString

### ISSUE THREAD

**Issue by jhirschberg70** [emscripten-core/emscripten#16990]
I'm sure I'm missing something obvious, but I haven't found what I'm looking for in the docs or scanning through tests/searching online. I'm trying to use the Closure Compiler, but I'm getting a runtime error. Here are my link flags:

```
-O3
-flto
-sEVAL_CTORS=2
-lidbfs.js  
-sENVIRONMENT=web
-sEXIT_RUNTIME=1
-sEXPORTED_FUNCTIONS="['_main']"
-sEXPORTED_RUNTIME_METHODS="['UTF8ToString']"
-sINVOKE_RUN=0
-sLLD_REPORT_UNDEFINED
-sSINGLE_FILE=1
-sTOTAL_MEMORY=16MB
--closure 1
--embed-file data
--pre-js src/io-emscripten.js
--pre-js src/main.js
```
I've narrowed the issue to this block of C++ code:
```
void BrowserUserOutput::configScreen(const JSON &screen) {
  std::string configString = screen.dump();

  EM_ASM({
      const config = JSON.parse(Module.UTF8ToString($0));
      IO.configScreen(config);
    }, configString.c_str());
}
```
After some debugging, the problem appears to be my call to `Module.UTF8ToString($0)`. I get the following error:

```
Uncaught TypeError: g.Ta is not a function
    at 30361 (index.html:329:78)
    at f (index.html:406:369)
    at 0011be66:0x3b50b
    at 0011be66:0x309cd
    at Bc (index.html:371:457)
    at qc (index.html:371:254)
```
I know that `g.Ta` is referring to `Module.UTF8ToString()`. My question is, what do I need to do differently to get this to run? I'm sorry if I'm being totally boneheaded here, but I'm just not sure of the issue, and I'd really like to get this working.

Jeff

**Comment by kripken** [comment]
[Closure compiler advanced opts](https://developers.google.com/closure/compiler/docs/api-tutorial3) can be tricky to get used to. One main thing is you must quote things whose name will be preserved after minification. Specifically changing `Module.UTF8ToString` to `Module['UTF8ToString']` should work, because the `Module` object is where we export stuff, so those names are kept even when minifying.

However, you can also replace `Module.UTF8ToString` with `UTF8ToString` - that would just use the name from the definition of the function, not its export. That can be minified, but it will be minified together with the definition, so it will work.

**Comment by jhirschberg70** [comment]
Thanks for the reply! I'm not able to try this out right at the moment, but I'll give it a shot later today. I will say that I thought I tried Module['UTF8ToString'] and it didn't work, but maybe I entered something incorrectly.

Thanks for the help!

Jeff

**Comment by sbc100** [comment]
`Module['UTF8ToString']` would require you to also export that library function .. I think just using `UTF8ToString` without any prefix is simpler and cleaner here.

**Comment by jhirschberg70** [comment]
I was able to do some more work on this today, and your suggested modifications solve the issue. I had actually tried `Module['UTF8ToString']` (which I neglected to mention). I thought it yielded the same error I mentioned, but upon trying it again, I got no error. There was still an issue though, as my program was no longer working correctly. You may have noticed the call to `IO.configScreen(config);` in my C++ code snippet. `IO` is an IIFE I made, and I concluded that I needed to use bracket notation for accessing some object properties inside that code, as well. Once I did that everything was back to normal. Thanks for the help @kripken
