### ISSUE TITLE
Linking is extremely slow

### ISSUE THREAD

**Issue by int255** [emscripten-core/emscripten#17019]
We're working on a big project, and the link time is more than **3 minutes**. Which is very counter productive.

We're doing somewhat an editor product, which has Gigs of c++ source code, after compile, the .wasm (release build) is something around 20MB. What makes us very frustrated is that it takes up to 3 minutes to link if I changed my .cpp code, I found that most of the time is spent on re-generating the .js runtime code for the .wasm. Although I modified the .cpp, but it only changes some internal parts of the calculation, sometimes I expose few APIs in the binary, but the relinked .js didn't change a bit after all.

Any suggestions how we can avoid unnecessary re-linking? or reducing the link time?

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)

I attached the tool chain profiling result.
[toolchain_profiler.results_20220523_0904.html.zip](https://github.com/emscripten-core/emscripten/files/8750663/toolchain_profiler.results_20220523_0904.html.zip)

**Comment by sbc100** [comment]
Can you attach the results of running just your like command with `EMPROFILE=2`?   Just to get a high level picture of what is taking the time?

**Comment by sbc100** [comment]
Avoiding the JS generation something we could consider,  based on some kind of hashing maybe?  Maybe we could has the wasm module metadata along with some kind of has of the emscripten version?  

In that past though we have found that link time is almost always dominated by binaryen tools, so maybe there is something odd going on here in your case.

**Comment by sbc100** [comment]
Perhaps, if you are using MAIN_MODULE/SIDE_MODULE you could be effected by a known issue: https://github.com/emscripten-core/emscripten/pull/16972 ?

**Comment by int255** [comment]
I attached the output and the emprofile result with EMPROFILE=2 exported in my env.
[toolchain_profiler.results_20220523_1247.html.zip](https://github.com/emscripten-core/emscripten/files/8751555/toolchain_profiler.results_20220523_1247.html.zip)
[build_output.txt](https://github.com/emscripten-core/emscripten/files/8751558/build_output.txt)

**Comment by sbc100** [comment]
It looks like basically all your time is taken in `block "get_metadata_binaryen" took 171.524 seconds`.     This is performed using wasm-emscripten-finalize from binaryen.   It can be slow under certain circumstances, for example if your program is large and your building with debug info.  

Are you building with debug info?   Can you maybe share your full link line (ninja -v)?

We have an option called `-sERROR_ON_WASM_CHANGES_AFTER_LINK` if you want to ensure that binaryen doesn't have to re-write your binary after linking (its the re-writing part that can slow it down).   To use this option you currently also need to opt into `-sWASM_BIGINT`.

**Comment by int255** [comment]
I was building with debug info which takes ~180s, however if I build with release, the situation is only slightly better -> ~100s.

I shared the full link line for the release build: see attached .txt file
[ninja_output_verbose.txt](https://github.com/emscripten-core/emscripten/files/8754985/ninja_output_verbose.txt)
.

**Comment by kripken** [comment]
For quick iteration you can also link with `-O1`. That will not run binaryen optimizations. So combining the suggestions, `-sERROR_ON_WASM_CHANGES_AFTER_LINK -sWASM_BIGINT -O1` should give a fast build during development. But for final release builds, if code size matters for you then it is recommended to run binaryen opts (with `-O2` or even `-O3`).

**Comment by int255** [comment]
@sbc100 @kripken Thanks both!

Great suggestions! I wish I had posted this ealier! 
By setting **"-sERROR_ON_WASM_CHANGES_AFTER_LINK -sWASM_BIGINT -O1"** in my release build, the build/link time has been reduced to just couple of seconds. The release .wasm binary size is now 30MB (was at 20MB with -O3 flag set). Those are nice flags for fast iterations! 

I think this issue can be closed now.
