### ISSUE TITLE
Allow module.exports when environment is not node to support bundlers

### ISSUE THREAD

**Issue by WolfgangDrescher** [emscripten-core/emscripten#17033]
[Verovio](https://github.com/rism-digital/verovio/) is using the following flags to build a JS WASM file:

```
em++ -v libverovio.a  -s WASM=1 -s INITIAL_MEMORY=512MB -s TOTAL_STACK=256MB -s SINGLE_FILE=1 -O3 -DNDEBUG -std=c++17 -s STRICT=1 --embed-file data/ -s EXPORTED_FUNCTIONS="[...]" -s EXPORTED_RUNTIME_METHODS='["cwrap"]' -o build/verovio.js
```

I'm trying to modernize the verovio npm package and make it ESM compatible (see discussion [here](https://github.com/rism-digital/verovio/discussions/2815)), which is not very easy as pointed out by @curiousdannii and discussed in https://github.com/emscripten-core/emscripten/issues/11792 due to some CJS expressions that end up in the ESM build. However for now I'm keeping support with a CJS build of emscripten. I want to bundle a wrapper JS library and the emscripten module together into one file with rollup.js. The problem is, that `module.exports` is currently included inside a `if (ENVIRONMENT_IS_NODE)` condition. Here is a minimal example of the emscripten module:

```js
// emscripten-module.js
var Module = typeof Module != "undefined" ? Module : {};
var ENVIRONMENT_IS_NODE = typeof process == "object" && typeof process.versions == "object" && typeof process.versions.node == "string";
if (ENVIRONMENT_IS_NODE) {
    {
        module["exports"] = Module;
    }
}
```

Rollup.js is bundling this into a UMD build using `@rollup/plugin-commonjs`:

```js
// bundle.js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.myPackage = factory());
})(this, (function () { 'use strict';

    var wasm = {exports: {}};

    (function (module) {
        // emscripten-module.js code goes here
    } (wasm));

    var Module = wasm.exports;

    var index = {
        module: Module,
    };

    return index;

}));
```

Like this the module actually will never be exported in the browser, because the if-condition with `ENVIRONMENT_IS_NODE` is preventing it. My suggestion is to remove `module["exports"] = Module;` from the `if(ENVIRONMENT_IS_NODE)` condition and wrap it around another condition that would still be compatible with node but also with UMD builds of bundlers like rollup.js. Something like this perhaps:

```js
if (typeof exports === 'object' && typeof module !== 'undefined') {
    // will probably fail because the exports variable is not around in the browser
    module["exports"] = Module;
}
```

Btw: Using the `-s MODULARIZE=1 ` option emscripten is already doing something similar:

```js
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
```

**Comment by curiousdannii** [comment]
Why not just use MODULARIZE? IMO it should probably be on by default.

**Comment by WolfgangDrescher** [comment]
In this case we want to support a "legacy build" that is fully backward compatible with existing setups. I'm planning to support both modules side by side for a while but deprecate the one without `MODULARIZE`.

**Comment by WolfgangDrescher** [comment]
I realized that adding another `module.exports = Module` at the end of the file fixed the problem.Here is a little rollup plugin I wrote for this:

```js
const targets = [
    '/emscripten-module.js',
];

function appendModuleExports(string) {
    return `${string}
    module.exports = Module;`;
}

export default function addModuleExports() {
    return {
        name: 'add-module-exports',
        transform(source, id) {
            if (!targets.some(s => id.endsWith(s))) {
                return;
            }
            return {
                code: appendModuleExports(source),
                map: null,
            };
        },
    };
};
```

This could also be done by adding a flag to the build: `--post-js append-module-exports.js` and just add `module.exports = Module;` into this file. However it would be nice, if emscripten would support this without the need of adding an additional export.

**Comment by sbc100** [comment]
If I understand correctly what you are asking for is for something that the `MODULARIZE` option also provides... but you don't want to use that option?    As a stop gab solution to provide some thing that is partially modularized, but not fully?   

If I understand correctly that that sounds niche enough that maybe the `-post-js append-module-exports.js` is good enough to fill that gap?   It might not be worth adding more complexity to emscripten itself.  But I could be wrong?
