### ISSUE TITLE
How to import test.js(test.worker.js and test.wasm) in webworker

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#17048]
in c code ,i create a pthread ,and generate the test.js ,test.worker.js and test.wasm by emscripten.

and in WebWorker, i need import the test.js ,so how can i import it .
 
the demo.html :
`<!doctype html>
<html>
<head>

</head>
<body>
 <div class="button_box">
    <div class="items">
       <button type="button" onClick="init()" style = "width:100px;height:60px">start</button>
       <button type="button" onClick="stop()"style = "width:100px;height:60px" >stop</button>
    </div>
</div>

 <div id="playWind"></div>
 <script>
    var worker2 = null;
	function init() {
	    //Module._test();

		worker2 = new Worker('./bitmap_worker.js');

		////向worker传递信息
		worker2.onmessage = function (e) {
			if(e.data.name==="loaded")
			{
				worker2.postMessage({name:"test"});
			}
			
		}
	}
	function stop()
	{
	    worker2.terminate();  // 停止 Worker 工作
        worker2 = null;
		console.log("stop worker!!!!");
	}
 </script> 
</body>
</html>`

the bitmap_worker.js :
`'use strict';
importScripts("testThread.js");
Module.addOnPostRun(function () {
        postMessage({'name': "loaded"});
    });

var offscreen,ctx,gl;

onmessage = function (e) {
  if(e.data.name == 'test'){
    console.log('>>>>Worker test 11');
    test();
	postMessage({'name': "testRes", 'res': 1});
  }
}

function test()
{
	Module._test();
}

`
And the compile  is `emcc -O3 testThread.cpp -o testThread.js -s PTHREAD_POOL_SIZE=2 -s USE_PTHREADS=1 -s "EXPORTED_RUNTIME_METHODS=['addOnPostRun']" -s EXPORTED_FUNCTIONS="['_test','_stop']" -s TOTAL_MEMORY=128MB -s ENVIRONMENT='worker'`

the pthread in c code can not run ?

**Comment by yangfangfang1204** [comment]
test.html
`<!doctype html>
<html>
<head>

</head>
<body>
 <div class="button_box">
    <div class="items">
       <button type="button" onClick="init()" style = "width:100px;height:60px">start</button>
       <button type="button" onClick="stop()"style = "width:100px;height:60px" >stop</button>
    </div>
</div>
 <div id="playWind"></div>
 <script>
    var worker1 = null;
	function init() {

        var worker1 = new Worker('./testThread.js');

		//向worker传递信息
		worker1.onmessage = function (e) {
			var event = e['data'];
			switch(event.cmd)
			{
				case 'loaded':
					console.log(">>>js loaded");
					var Module = e.urlOrBlob;
					var wasmModule = e.wasmModule;
					break;
				case '':
					break;
			}
			
		}
	}

	function stop()
	{
	    worker1.terminate();  // 停止 Worker 工作
        worker1 = null;
		console.log("stop worker!!!!");
	}
 </script> 
</body>
</html>`

but how can i postMessage the data to the testThread.js ?

**Comment by sbc100** [comment]
The emscripten code generated in ` testThread.js` rakes case of managing the workers/pthreads for you.  You shouldn't need to call `new Worker` in your own code.  

To start a new thread you call `pthread_crearte` and that take care of starting a new worker and running the thread within it.

Node that you might also need to use `-sPTHREAD_POOL_SIZE` and/or `-sPROXY_TO_PTHREAD` if you want your new threads to be usable right away.

**Comment by yangfangfang1204** [comment]
But in https://github.com/emscripten-core/emscripten/pull/10036 , there is a discussion about how to support running a pthreads-using program in a worker , and there is a example in `tests/test_browser.py ,  def test_pthreads_started_in_worker :` 
`Tests that pthreads code works as intended in a Worker. That is, a pthreads-using program can run either on the main thread (normal tests) or when we start it in a Worker in this test (in that case, both the main application thread and the worker threads are all inside Web Workers).`
So if i need run the testThread.js(testThread.worker.js and test.wasm) in webworker, how can i postMessage the data to the testThread?

**Comment by sbc100** [comment]
Sure, you can start your pthread program in worker if you like... but that just represents the main thread.  Its still up to emscripten's code to the start any extra workers need to run threads.

One your are running your main thread in your worker, that thread will need to return (either by returning from `main` or by calling `emscripten_set_main_loop` or by calling `emscripten_exit_with_live_runtime`).. and then that worker will run its even loop as normal and be able to receive messages from the outside.

**Comment by yangfangfang1204** [comment]
the testThread.js that include  the main thread and the main thread return , so how can i postMessage to the testThread.js ? because the testThread.js is generated by Emscripten，how can i call the API exported by testThread.js ?

**Comment by sbc100** [comment]
The main runtime thread of emscripten (i.e. the worker where you load `testThread.js` yourself).. can/should contain other JS code that can do whatever it wants.   Loading just `testThread.js` is not enough.. unless you have some `pre.js/post.js` code there too which does something useful.    Its can communicate with the outside world by postMessage and also make calls into the `Module`.

**Comment by yangfangfang1204** [comment]
ok , i got it ,thanks

**Comment by AlexMold** [comment]
Guys, could you show a minimal working example with pthreads with integration on client side?

**Comment by sbc100** [comment]
There are lots of examples of threads in the test suite.  For examples `./test/runner core0g.test_pthread_create` and `./test/runner browser.test_pthread_create`.   If you run with `--save-dir` the tests output is saved and you can check it out or run a webserver (e.g. `./emrun --no_browser /tmp/emscripten_test`) and browser to the generated output.

Perhaps I don't understand your question "integration on client side"?

**Comment by AlexMold** [comment]
I mean the examples of the launching of produced by emscripten artifact(js, worker, wasm) on Javascript side and executing С++ API.
I have not found such examples across repo.

**Comment by sbc100** [comment]
Sorry, I still don't quite understand, don't all of our browser tests load the artifacts and run the C++ code.     

For example `browser.test_pthread_create` generates and html file that shows how to load the generated JS code, the generated JS code then loads the wasm file, and calls the `main` function in C++, this main function than starts a new pthread, which then creates a worker based on the generated worker.js.  The workers JS then loads the wasm file, and runs the C++ entry point.

**Comment by AlexMold** [comment]
I've shortly described my [problem here](https://github.com/emscripten-core/emscripten/issues/17523)

**Comment by AlexMold** [comment]
Maybe I fundamentaly do not understand how to launch the generated js file with workers (
