### ISSUE TITLE
how to make 'ENVIRONMENT_IS_PTHREAD' is true?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#17050]
We could be an application pthread running in a worker. (ENVIRONMENT_IS_WORKER == true and ENVIRONMENT_IS_PTHREAD == true) ?

**Comment by sbc100** [comment]
Those variables should all be managed automatically by emscripten.  `ENVIRONMENT_IS_PTHREAD` will be true on any worker that was created by the emscripten for running a pthread.

**Comment by yangfangfang1204** [comment]
OK , Thanks for your answer
