### ISSUE TITLE
WasmFS should support case insensitive file paths

### ISSUE THREAD

**Issue by mere-human** [emscripten-core/emscripten#17079]
The  flag `-s CASE_INSENSITIVE_FS=1` doesn't seem to  work with WasmFS.

**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.10 (c3fe57af0504fe24fc4ba697feb8c204f3c80022)
clang version 15.0.0 (https://github.com/llvm/llvm-project 8bc29d14273b05b05d5a56e34c07948dc2c770d3)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/src/emsdk/upstream/bin`

**Failing code:**
```cpp
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include <ctype.h>

int main()
{
    char fileName[] = "Test.txt";
    FILE *fp1 = fopen(fileName, "wt");
    assert(fp1);
    printf("Writing to '%s'...\n", fileName);
    fputs("test", fp1);
    fclose(fp1);

    fileName[0] = tolower(fileName[0]);  // make file path lower case
    FILE *fp2 = fopen(fileName, "rt");
    assert(fp2);
    char buffer[10] = {};
    assert(fgets(buffer, sizeof(buffer), fp2) != nullptr);
    printf("Read '%s' from '%s'\n", buffer, fileName);
    assert(strcmp(buffer, "test") == 0);
    fclose(fp2);
    return 0;
}

```

**Full link command and output with `-v` appended:**
Build command:
```bash
emsdk install latest && emsdk activate latest
rm -rf build
mkdir -p build
cd build
em++ -v ../fs_case.cpp -s CASE_INSENSITIVE_FS=1 -s WASMFS=1 -o a.html
emrun a.html
cd ..
```
Program output:
```
Writing to 'Test.txt'...
a.js:1451 Aborted(Assertion failed: fp2, at: ../fs_case.cpp,17,main)
abort @ a.js:1451
a.js:34 Uncaught RuntimeError: Aborted(Assertion failed: fp2, at: ../fs_case.cpp,17,main)
    at abort (a.js:1466:11)
    at ___assert_fail (a.js:1800:7)
    at a.wasm:0x86f
    at a.wasm:0x9a1
    at a.js:1510:22
    at callMain (a.js:2366:15)
    at doRun (a.js:2423:23)
    at a.js:2434:7
```

**Comment by tlively** [comment]
How important is this to support in the new file system?

**Comment by mere-human** [comment]
> How important is this to support in the new file system?

@tlively 
I'm trying WasmFS on a large project. That project was originally designed to work on case-insensitive FS. Occasionally a path with the wrong case is used to open a file. Spotting and fixing all such paths is hard. 

This causes issues when WasmFS is enabled. Files that used to open, won't be found anymore because of the case sensitivity.

So, it would be really nice if WasmFS supported case-insensitive paths. I hope that answers the question.

**Comment by tlively** [comment]
Thanks, @mere-human! I've added this issue to the WasmFS project so it doesn't get lost.

**Comment by mere-human** [comment]
Any ideas how hard it will be to make case-insensitive WasmFS work? 
Or any ideas how to implement it? I might try creating a PR.

**Comment by kripken** [comment]
For experimenting with this, maybe a good starting point would be to add ifdefing around a new `WASMFS_CASE_INSENSITIVE` define. There are hopefully not many places under `system/lib/wasmfs/*` that compare filenames that would need the ifdef.
