### ISSUE TITLE
What is wasmer ?

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#17073]
What is wasmer ? Wasmer's emergence also gives WebAssembly an opportunity to shine on non-Web platforms ? Is there any documentation about Wasmer ？

**Comment by kripken** [comment]
Wasmer is a non-Web runtime, like wasmtime, WAVM, and others. You can do a search for any of them and the first result should have their official website with lots more info.

In Emscripten we use wasmer and wasmtime to test [standalone wasm](https://v8.dev/blog/emscripten-standalone-wasm).
