### ISSUE TITLE
SIDE_MODULE and USE_PTHREADS provoke memory growth

### ISSUE THREAD

**Issue by alexander-veselov** [emscripten-core/emscripten#17077]
### Discussed in https://github.com/emscripten-core/emscripten/discussions/17034

<div type='discussions-op-text'>

<sup>Originally posted by **alexander-veselov** May 24, 2022</sup>
I understand that "SIDE_MODULE + USE_PTHREADS" is experimental. But I would still like to know if this is a known issue and if it can be fixed somehow.

We have a lot of side modules (about 350MB). USE_PTHREADS=1 and PTHREAD_POOL_SIZE=20. With this configuration, an "out of memory" error occurs. It seems that all side modules are loaded several times for each thread.

For example, if you set PTHREAD_POOL_SIZE=1, then the problem will disappear.
I know that when building without side modules, the problem will also disappear, but we need side modules.

Is it possible to make threads use shared memory and not load copies of dynamic libs several times?</div>

**Comment by AngenimyWhu** [comment]
Hi, how did you solve this problem ? I meet the same problem and need use SIDE_MODULE in my project. it will download 1GB （30MB * (30+1)）for startup when I set PTHREAD_POOL_SIZE=30.

**Comment by alexander-veselov** [comment]
> Hi, how did you solve this problem ? I meet the same problem and need use SIDE_MODULE in my project. it will download 1GB （30MB * (30+1)）for startup when I set PTHREAD_POOL_SIZE=30.

Hello. I accidentaly created and closed this issue. Unfortunately it hasn't been fixed yet. There is an open issue https://github.com/emscripten-core/emscripten/issues/17078

**Comment by AngenimyWhu** [comment]
Thanks ervery much!!
