### ISSUE TITLE
Dynamic linking: emscripten_get_now.sig is undefined

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#17106]
I am running into the following issue when building the cryptography PyO3 module:
```js
RuntimeError: abort(Assertion failed: bad export type for `_emscripten_get_now`: undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (http://127.0.0.1:32797/pyodide.asm.js:10:234384)
    at assert (http://127.0.0.1:32797/pyodide.asm.js:10:224838)
    at Object.reportUndefinedSymbols (http://127.0.0.1:32797/pyodide.asm.js:10:319214)
```

`wasm-objdump` shows that we are trying to import `emscripten_get_now`:
```wat
$ cryptography_rust.so -j Import -x | grep emscripten_get_now
 - func[62] sig=57 <env._emscripten_get_now> <- env._emscripten_get_now
 - global[57] i32 mutable=1 <- GOT.func._emscripten_get_now
```
but `resolveGlobalSymbol("emscripten_get_now")` returns undefined and so we get an error from `reportUndefinedSymbols`.

Adding the lines
```js
Module["__emscripten_get_now"] = Module["_emscripten_get_now"];
Module["__emscripten_get_now"].sig = "d";
```
fixes the problem.

cf https://github.com/pyodide/pyodide/pull/2378

**Comment by sbc100** [comment]
It looks like that side module is trying to import this symbol with an `_` prefix.   But that symbols doesn't start with and underscore:

https://github.com/emscripten-core/emscripten/blob/922cf56100de7dd162593f64481c73d16931643e/system/include/emscripten/emscripten.h#L86

Do you know where the `_emscripten_get_now` symbol is coming from?  Which object contains that reference?  In the native object files non of the symbols should have an `_` prefix.

**Comment by hoodmane** [comment]
Even if I fix that, there is still an error because there is a GOT entry for `emscripten_get_now` but `Module.resolveGlobalSymbol("emscripten_get_now").sig` is undefined:

```js
TypeError: Cannot read properties of undefined (reading 'slice')
    at convertJsFunctionToWasm (pyodide.asm.js:9356:24)
    at addFunctionWasm (pyodide.asm.js:9480:23)
    at Object.reportUndefinedSymbols (pyodide.asm.js:14952:34)
```

**Comment by sbc100** [comment]
That sounds like a real bug.    Feel free to send a PR adding a `__sig` attribute to `emscripten_get_now` (if you don't have time someone else will get it).

**Comment by sbc100** [comment]
Can you re-title this bug (or open a new one)?
