### ISSUE TITLE
FS.createStream: Cannot add property XX, object is not extensible

### ISSUE THREAD

**Issue by bkotsopoulossc** [emscripten-core/emscripten#17105]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
3.1.7

I am getting a TypeError at runtime from this [line](https://github.com/emscripten-core/emscripten/blob/3.1.7/src/library_noderawfs.js#L99). The error is `Cannot add property XX, object is not extensible`, where XX is the file descriptor index value. 

If we look at what `streams` is, it's initialized to a [JS array](https://github.com/emscripten-core/emscripten/blob/3.1.7/src/library_fs.js#L97). The `FS.nextfd` logic is supposed to pick the first empty slot in the array, or will be equal tot he length of the array. In the case where all slots are filled, we are implicitly extending the array by indexing into it. It seems to work most of the time, but I am seeing this code sometimes fail, and it's unclear why. Is this valid JS? 
CC @sbc100 

![image](https://user-images.githubusercontent.com/25588019/171075182-0b895770-b4c0-48e9-850e-90608bc02dc8.png)

**Comment by sbc100** [comment]
As far as I can tell the only way that the streams object would cause this error would be if via the `preventExtensions` API.. which we don't use.  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible

The the exception happen at startup during `createStandardStreams`?   Or at runtime when you open some other files?

**Comment by bkotsopoulossc** [comment]
I'm a bit confused by that error message because it says object is not extensible, but the type being extended, FS.streams is an Array

**Comment by bkotsopoulossc** [comment]
it doesn't look like there is any code that changes `FS.streams` to an object. Maybe the error message is just incorrect? is it actually valid to extend a JS array by indexing into it rather than using `push()`? It seems like it works most of the time but it's possible to get into a state where it doesn't?

**Comment by bkotsopoulossc** [comment]
Hmm okay another hint. This is only reproducible after linking with `-s EXPORTED_RUNTIME_METHODS=FS`, which exports FS as part of the module object

**Comment by bkotsopoulossc** [comment]
Figured this out, it was an issue on our end with how we were holding the wasm module in a store that deep-freezes the entire module object. Prior to this, we were never actually doing things like extending arrays inside the module object (even though we had code that opened files). Exporting the runtime method then meant FS was part of the module object, and was part of the freezing operation. Opening any file from C++ after inserting the wasm module into the store then caused this runtime error to get thrown
