### ISSUE TITLE
`--whole-archive` causes trouble when linking rust

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#17109]
Continuing the discussion from https://github.com/llvm/llvm-project/issues/55786 xref https://github.com/rust-lang/rust/issues/80775, xref https://github.com/pyodide/pyodide/pull/2378.

Rust libraries contain a `lib.rmeta` file and must be linked with `--no-whole-archive`. When I try to build rust libraries targeting `wasm32-unknown-emscripten` I run into linker errors because the rust libraries are being loaded with `--whole-archive` set. 

I think that emscripten is indeed the culprit here:

https://github.com/emscripten-core/emscripten/blob/2aa89c2cc99b2423c9d82187d3c59b752f2592f8/tools/building.py#L363

```py
  # Emscripten currently expects linkable output (SIDE_MODULE/MAIN_MODULE) to
  # include all archive contents.
  if settings.LINKABLE:
    args.insert(0, '--whole-archive')
    args.append('--no-whole-archive')
```
We probably need a separate setting to disable this.

<details>
<summary>Response file with problematic linker args</summary>

```
root:WARNING: Creating response file /tmp/emscripten_w2dsyqtv.rsp with following contents: -o
/src/packages/cryptography/build/cryptography-36.0.2/src/rust/target/wasm32-unknown-emscripten/release/deps/cryptography_rust.wasm
--whole-archive
<... tons of files, some of which require --no-whole-archive>
-lc
-L/src/.docker_home/.rustup/toolchains/nightly-2022-05-28-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib
-L/src/.docker_home/.rustup/toolchains/nightly-2022-05-28-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-emscripten/lib/self-contained
--fatal-warnings
-L/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic
--no-whole-archive
-mllvm
-combiner-global-alias-analysis=false
-mllvm
-enable-emscripten-cxx-exceptions
-mllvm
-enable-emscripten-sjlj
-mllvm
-disable-lsr
--import-undefined
--import-memory
--strip-debug
--export-all
--no-gc-sections
--experimental-pic
-shared
```

</details>

**Comment by sbc100** [comment]
I wonder if we can/should just remove this block... folks could always add it back themselves if they really wanted to force all symbols from libraries

**Comment by adamnovak** [comment]
So since #17221 was closed without being merged, is the resolution here "just use `-sMAIN_MODULE=2` and not `-sMAIN_MODULE=1` when building Rust code"?
