### ISSUE TITLE
c++ class constructor does not bind unless external (to class) function is added to cpp file (em++ 3.1.13)

### ISSUE THREAD

**Issue by irishScott** [emscripten-core/emscripten#17143]
Working through Emscripten documentation sample code, merging the quick_example and class examples.  Encountered the following stack trace in Firefox 101.0 when attempting to execute the code below (note the commented-out lines):

Exception:
> Uncaught (in promise) ReferenceError: craftInvokerFunction is not defined
    __embind_register_class_constructor http://localhost:8000/quick_example.js:2843
    onComplete http://localhost:8000/quick_example.js:1907
    whenDependentTypesAreResolved http://localhost:8000/quick_example.js:1931
    registerType http://localhost:8000/quick_example.js:1964
    registerType http://localhost:8000/quick_example.js:1964
    __embind_register_std_string http://localhost:8000/quick_example.js:3156
    callRuntimeCallbacks http://localhost:8000/quick_example.js:1711
    initRuntime http://localhost:8000/quick_example.js:1298
    doRun http://localhost:8000/quick_example.js:3894
    run http://localhost:8000/quick_example.js:3913
    runCaller http://localhost:8000/quick_example.js:3855
    removeRunDependency http://localhost:8000/quick_example.js:1423
    receiveInstance http://localhost:8000/quick_example.js:1607
    receiveInstantiationResult http://localhost:8000/quick_example.js:1625
    promise callback*createWasm/instantiateAsync/< http://localhost:8000/quick_example.js:1659
    promise callback*instantiateAsync http://localhost:8000/quick_example.js:1651
    createWasm http://localhost:8000/quick_example.js:1688
    <anonymous> http://localhost:8000/quick_example.js:3462

quick_example.html:
```
<!doctype html>
<html>
	<script>
		var Module = {
			onRuntimeInitialized: function() {
				//console.log('lerp result: ' + Module.lerp(1, 2, 0.5));

				var instance = new Module.MyClass(10, "hello");
				console.log(instance.x);
			}
		};
	</script>
	<script src="quick_example.js"></script>
</html>
```

quick_example.cpp
```
#include <emscripten/bind.h>

using namespace emscripten;

class MyClass {
	public:
		MyClass(int x, std::string y) : x(x), y(y) {}

		int getX() const {return x;}
		void setX(int newX) {x = newX;}

	private:
		int x;
		std::string y;
};


//float lerp(float a, float b, float t) {
//	return (1 - t) * a + t * b;
//}

EMSCRIPTEN_BINDINGS(my_module) {
	class_<MyClass>("MyClass")
		.constructor<int, std::string>()
		.property("x", &MyClass::getX, &MyClass::setX);

//	function("lerp", &lerp);
}
```
transpiled with: `em++ -lembind -o quick_example.js quick_example.cpp`

However when the "lerp" related code is uncommented, the code executes as expected after retranspiling:
>lerp result: 1.5
 10

**Comment by brendandahl** [comment]
Looks like the craftInvokerFunction is not generated without the `function` call. The function dependency is missing in https://github.com/emscripten-core/emscripten/blob/59fef9d2c48a98fd816e834a2d2b4ce49954bb9d/src/embind/embind.js#L2076. I'll put up a PR to fix.
