### ISSUE TITLE
Polymorphism doesn't work with SIDE_MODULE + USE_PTHREADS at all

### ISSUE THREAD

**Issue by alexander-veselov** [emscripten-core/emscripten#17150]
It seems that polymorphism doesn't work with `SIDE_MODULE` + `USE_PTHREADS` at all (see code below):
- strange `Implementation` typeid name: `emsc`
- you can't call `Implementation` methods through pointers (neither through the base pointer nor through the derived)
- `dynamic_cast` / `static_cast` don't work

I think this is a serious problem. Am I missing something?

**Important: If you remove -sUSE_PTHREADS=1 and -pthread, then everything works.**

Implementation.h
```cpp
#pragma once

struct Interface
{
    virtual ~Interface() {} // for std::unique_ptr
    virtual void Foo() const = 0;
};

struct Implementation : public Interface
{
    void Foo() const override;
};
```

Implementation.cpp
```cpp
#include "Implementation.h"

#include <iostream>

void Implementation::Foo() const
{
    std::cout << "Foo" << std::endl;
};
```

main.cpp
```cpp
#include "Implementation.h" // separate side module (dynamic linking)

#include <memory>
#include <iostream>

int main()
{
    std::cout << typeid(Interface).name() << std::endl; // 9Interface
    std::cout << typeid(Implementation).name() << std::endl; // emsc

    Implementation().Foo(); // works

    std::unique_ptr<Interface> interfacePointer(new Implementation());
    std::unique_ptr<Implementation> implementationPointer(new Implementation());

    // All calls below cause error 'null function or function signature mismatch'
    implementationPointer->Foo();
    interfacePointer->Foo(); 
    Interface* castedPointer = static_cast<Interface*>(implementationPointer.get());

    return 0;
}
```

Build commands:
```
emcc Implementation.cpp -fPIC -pthread -sSIDE_MODULE=1 -sUSE_PTHREADS=1 -o SideModule.wasm
emcc main.cpp -fPIC -pthread -sMAIN_MODULE=1 -sUSE_PTHREADS=1 -sPROXY_TO_PTHREAD=1 -o main.html SideModule.wasm
```

Runtime error:
```
Uncaught RuntimeError: null function or function signature mismatch
```

**Comment by Maksim-Bozhko** [comment]
This seems like a very serious bug, do emscripten devs have any comments or suggestions, are there any plans to fix this?

**Comment by goldwaving** [comment]
I'm not having any success with dynamic linking and pthreads in a real world multithreaded app.  Statically linked, everything works as expected.  Dynamically linked (on load or dlopen), strange and unexpected errors always occur.  These errors occur on pure C libraries, so I think the issue goes beyond polymorphism.

**Comment by sbc100** [comment]
I'm working a fix this for this issue.  It relates the weakly defined symbols that C++ uses for rtti info.

If you have other issues please file them.

**Comment by sbc100** [comment]
Fix is in flight upstream in llvm: https://reviews.llvm.org/D127333

**Comment by Maksim-Bozhko** [comment]
Thanks for a quick fix
