### ISSUE TITLE
C++ functions with vector return type do not work

### ISSUE THREAD

**Issue by anonymouscoder999** [emscripten-core/emscripten#17166]
test.h

```std::vector<int> test();```

test.cpp

```
#include <emscripten/bind.h>
using namespace emscripten;

std::vector<int> test() {
    std::vector<int> result;
    result.push_back(2);
    result.push_back(7);
    result.push_back(100);
    result.push_back(5);
    return result;
}

EMSCRIPTEN_BINDINGS(my_module) {
    function("test", &test);
}
```

Compile with

`em++ -lembind -o out.js -O2 test.cpp`

index.html

```
<script>
    var Module = {
	onRuntimeInitialized: () => {
	    Module.test();
	}
    };
</script>
<script type="text/javascript" src="out.js"></script>
```

Upon running the above code, this error appears:

`Cannot call test due to unbound types: NSt3__26vectorIiNS_9allocatorIiEEEE`

Version: emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.13

**Comment by alexprogrammr** [comment]
@anonymouscoder999 I was facing this issue in the past and fixed it by adding the following to the file with bindings:

```c++
namespace emscripten::internal {

template <typename T, typename Allocator>
struct BindingType<std::vector<T, Allocator>> {
    using ValBinding = BindingType<val>;
    using WireType = ValBinding::WireType;

    static WireType toWireType(const std::vector<T, Allocator> &vec) {
        return ValBinding::toWireType(val::array(vec));
    }

    static std::vector<T, Allocator> fromWireType(WireType value) {
        return vecFromJSArray<T>(ValBinding::fromWireType(value));
    }
};

template <typename T>
struct TypeID<T,
              typename std::enable_if_t<std::is_same<
                  typename Canonicalized<T>::type,
                  std::vector<typename Canonicalized<T>::type::value_type,
                              typename Canonicalized<T>::type::allocator_type>>::value>> {
    static constexpr TYPEID get() {
        return TypeID<val>::get();
    }
};

}
```

@kripken is it possible to handle std::vector automatically by embind? If you can point me to the place where it makes sense to add it - I can try))

**Comment by anonymouscoder999** [comment]
Yup, that worked! I found an even simpler solution than the one @alexprogrammr gave. Adding the line `register_vector<moves::Move>("MoveVector");` at the end of EMSCRIPTEN_BINDINGS did the trick.

**Comment by alexprogrammr** [comment]
@anonymouscoder999 nice! The approach with `register_vector<int>("IntVector");` works too but for my case, I found it inconvenient when there are a lot of possible `std::vector` types 😅
