### ISSUE TITLE
CRITICAL root: Cannot find /usr/bin/llvm-link, check the paths in ~/.emscripten

### ISSUE THREAD

**Issue by drawcall** [emscripten-core/emscripten#1723]
In your tutorial:12. (Optional) Compile a simple test program to check that everything works:
I want to test but there were errors!!! can you help me thanks!!!

WARNING  root: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.24) (based on LLVM 3.2svn)", expected "clang version 3.2")
INFO     root: (Emscripten: Running sanity checks)
CRITICAL root: Cannot find /usr/bin/llvm-link, check the paths in ~/.emscripten

**Comment by amilajack** [comment]
I'm getting this error:

```bash
WARNING:root:LLVM version appears incorrect (seeing "7.3", expected "3.9")
CRITICAL:root:fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
===========================================================================
(no targets could be identified: [Errno 2] No such file or directory)
===========================================================================
CRITICAL:root:you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
CRITICAL:root:Cannot find /usr/bin/llvm-link, check the paths in ~/.emscripten
```

**Comment by amilajack** [comment]
Also:
```bash
➜  ~ which llvm-link
llvm-link not found
➜  ~
```

**Comment by amilajack** [comment]
Does `llvm-link` come with `llvm`?

**Comment by kripken** [comment]
Yes, it is part of llvm - when you build it from source, or use the emscripten SDK, it should be there. And it should be in the LLVM_ROOT directory specified in ~/.emscripten.

**Comment by amilajack** [comment]
These are the steps that I followed:
```bash
# Fetch the latest registry of available tools.
./emsdk update

# Download and install the latest SDK tools.
./emsdk install latest

# Make the "latest" SDK "active"
./emsdk activate latest
```

Did I miss anything?

**Comment by kripken** [comment]
Might be an sdk bug then, which I'm not knowledgeable about. But I would check ~/.emscripten.

**Comment by amilajack** [comment]
Oh I forgot to mention that I installed emscripten globally via brew: `brew insatll emscripten`

**Comment by amilajack** [comment]
So I think I found the issue:

I assumed that ` source ./emsdk_env.sh` would append the PATH variables to my bash profile for me:

```
To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.
```

Also after uninstalling the global emscripten, the compilation made much progress. However, I am getting the following error now:

```bash
Compiling 3DPrimitivesExample for Release
HOST_OS=Darwin
find: /Users/amila/Downloads/of_v0.9.3_osx_release/examples/3d/3DPrimitivesExample/emsdk_portable/emscripten/1.35.0/third_party/websockify/Windows/noVNC: No such file or directory
find: Websocket: No such file or directory
find: Service: No such file or directory
find: Project: No such file or directory
```

Seems to be looking for a windows specific. Do you think this is something project-specific?

**Comment by amilajack** [comment]
So I think it is trying to fine the folder:

[noVNC Websocket Service Project](https://github.com/kripken/emscripten/tree/master/third_party/websockify/Windows/noVNC%20Websocket%20Service%20Project)

But something about the url path's makes it try to find the files separately, ignoring the spaces (ex. tries to find folders/files Websocket, Service, Project instead of **noVNC Websocket Service Project**)

**Comment by amilajack** [comment]
@kripken `emmake make` it works now! Is it possible to make `emmake make` work with wasm? I've looked around for how to do this but I haven't found a method yet.

**Comment by kripken** [comment]
wasm is still in development, with the spec still changing and browser support very partial. But if you're interested to try it, emscripten details are here: https://github.com/kripken/emscripten/wiki/WebAssembly

**Comment by ThierryKaya** [comment]
Actually as stated per homebrew post-install comment:
"Manually set LLVM_ROOT to /usr/local/opt/emscripten/libexec/llvm/bin
  in ~/.emscripten after running `emcc` for the first time."

It should do the trick.

**Comment by juj** [comment]
If you are using brew or ports some other package manager, you should avoid using emsdk. Those two are orthogonal ways of sourcing Emscripten, i.e. Emsdk is a standalone SDK.
