### ISSUE TITLE
Support for EXPORT_NAME without MODULARIZE

### ISSUE THREAD

**Issue by WolfgangDrescher** [emscripten-core/emscripten#17274]
Currently it does not seem to be possible to use a custom module name like `EXPORT_NAME=VerovioModule` without using the `MODULARIZE=1` along with it. The output is something like this:

```js
// first line
var Module=typeof VerovioModule!="undefined"?VerovioModule:{};...
// somewhere later in the code
module["exports"]=Module;
```

This will in any case assign a `window.Module` variable when used in a browser context. Like this it is not possible to use multiple modules on the same page without using `MODULARIZE=1`.

Is this behaviour intended like this? To me it seems like it would be better to wrap this in a IIFE statement similar like with the `MODULARIZE=1` option.

```
var VerovioModule = (function () {
    var Module=typeof VerovioModule!="undefined"?VerovioModule:{};...
    return Module;
})();

module.exports = VerovioModule;
```

However, I see the problem that the export will probably no longer work like this. And I'm also not aware how such a change would affect other build options for an emscripten module.

**Comment by sbc100** [comment]
Would `--post-js` containing `var Foo = Module;` do the trick?
