### ISSUE TITLE
Keep program output for tests/runner

### ISSUE THREAD

**Issue by xbcnn** [emscripten-core/emscripten#17282]
Need a way to keep program/tests output from tests/runner without --verbose option, which is too much noise information.   This is useful when running tests like benchmarking.
Maybe there is already one which I don't know yet.

**Comment by sbc100** [comment]
Maybe `--save-dir` is what you are looking for?

**Comment by sbc100** [comment]
BTW, `--save-dir` is best used when running one test at time, since the directory is re-used by each test that runs.

**Comment by xbcnn** [comment]
Oh. I once add a benchmark test into test_core.py which used do_runf() and NO `expected_output` provided.  Under this case, I just want to an option which `save the output`, like the `--save-dir` does.
But I have removed it.

**Comment by sbc100** [comment]
When you say "save the output" do you mean "save the intermediate files generated by the test"... or "save the output of running the generated program under node"?

The former is handled by `--save-dir`.. but we don't have anyway to handle the later, it would be up to you to capture the output and write it to a file (most likely by passing `stdout=PIPE` to `do_runf`).  We do have some tests that can automatically update files in the checkout based on the output of the program (look for EMTEST_REBASELINE in the source code).

**Comment by xbcnn** [comment]
I mean the "save the output of running the generated program under node".
