### ISSUE TITLE
WasmFS asserts in close() instead of returning EBADF

### ISSUE THREAD

**Issue by alshamma** [emscripten-core/emscripten#17329]
In `emscripten/system/lib/wasmfs/backends/opfs_backend.cpp` the function `close()` asserts on openCount. Instead it should return `EBADF`. 

I wonder if there are other asserts that should be returning error codes. I see quite a few asserts in the code.

Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.14-git (4343cbec72b7db283ea3bda1adc6cb1811ae9a73)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

**Full link command and output with `-v` appended:**
Using -sWASMFS & -sFORCE_FILESYSTEM=1

**Comment by tlively** [comment]
This was fixed in https://github.com/emscripten-core/emscripten/pull/17301. The assertion in close was correct, but `open` was not increasing `openCount` correctly.
