### ISSUE TITLE
Can it upgrade freetype up to FreeType 2.10.2 or higher? 2.4.4 cannot support woff2 font type

### ISSUE THREAD

**Issue by Athsx** [emscripten-core/emscripten#17321]
Can it upgrade freetype up to FreeType 2.10.2 or higher? 2.4.4 cannot support woff2 font type

**Comment by sbc100** [comment]
Looks like there is an ongoing effort to update it: https://github.com/emscripten-core/emscripten/pull/16298

Can this be closed as a duplicate of that?

**Comment by Athsx** [comment]
ok
