### ISSUE TITLE
Multi-threaded Embind fails when used with multiple worker threads

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#17372]
Hi :wave:!

My project uses Embind and `-pthread`. I would like to use multiple worker threads in JavaScript to execute different (independent) WASM methods in parallel, which I would like to all use the same `SharedArrayBuffer` memory.

Everything works great while I'm just having a single JavaScript thread to interact with the Emscripten-generated module. But things start to break when I use multiple worker threads in JavaScript. Here is some code to better explain my use case:

```cpp
// embind-main.cpp

void performWork() {
  int *i = new int;
}

EMSCRIPTEN_BINDINGS(myBindings) {
  emscripten::function("performWork", &performWork);
}
```

```sh
# build.sh

emcc \
  --bind embind-main.cpp \
  -s EXPORT_ES6=1 \
  -s USE_ES6_IMPORT_META=1 \
  -pthread \
  -s PTHREAD_POOL_SIZE='navigator.hardwareConcurrency' \
  -s ENVIRONMENT='web,worker' \
  -s ALLOW_MEMORY_GROWTH \
  -o ../my-app/emscripten/main.js
```

```js
// my-js-main-thread.js

const mem = new WebAssembly.Memory({ initial: 256, shared: true, maximum: 4096 });
const mainWorker = new Worker(new URL("../src/worker.js", import.meta.url));
mainWorker.onmessage = () => {
  const secondWorker = new Worker(new URL("../src/worker.js", import.meta.url));
  secondWorker.postMessage(mem);
};
mainWorker.postMessage(mem);
```

```js
// my-js-worker.js

import main from '../emscripten/main';

self.onmessage = async m => {
  const { performWork } = await main({
    wasmMemory: m.data,
  });
  self.postMessage("let's go");

  for (let i = 0; i < 10000000; i++) { // reducing the loop count makes the error go away (presumably, because it avoids memory growth?!)
    performWork();
  }
  console.log("done");
};
```

The execution fails with either of the following error messages. It looks like these errors occur when a memory growth is happening.

```
Uncaught (in promise) RuntimeError: Aborted(Assertion failed: _emscripten_thread_supports_atomics_wait(), at: /b/s/w/ir/x/w/install/emscripten/system/lib/pthread/emscripten_futex_wake.c,40,emscripten_futex_wake)
```
```
Uncaught RangeError: WebAssembly.Table.get(): invalid index 14782264 into function table
```

Is this / should this be a supported use case? Am I doing something wrong? Is there a work-around to allow me to use these wasm functions in parallel?

**Comment by sbc100** [comment]
To start an emscripten thread you are best of using `pthread_create` .. that will take care of creating the worker for you.

You can then send it work in various ways.  One easy way it to use the Proxying API: https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/proxying.h.

Another way would be use `emscripten_exit_with_live_runtime` in the pthread and then use `addEventListener` in the worker to listen for message sent via `postMessage` from the main thread.

**Comment by donalffons** [comment]
Thanks a lot for looking into this. For some context: [My project](https://ocjs.org/) is using Embind to expose a large C++ API to JavaScript. Users can now use this C++ API from JavaScript. I'm wondering if there is a way that would allow a user of my JavaScript API to run their code (JavaScript code, not C++ code) in parallel on multiple threads.

I believe the proxying API wouldn't help me in this case, since it's a C++ API - but I would like to have a way to allow parallel execution from the JS side.

> To start an emscripten thread you are best of using pthread_create .. that will take care of creating the worker for you.

In a naive attempt, I tried to create a new thread from C++ and then using `emscripten_run_script` to evaluate JS code passed as a string. However, that doesn't seem to work:

```cpp
// embind-main.cpp
void performWork() {
  int *i = new int;
}

void runInThread(std::string msg) {
  std::thread t1([](std::string msg) {
    emscripten_run_script(msg.c_str());
  }, msg);
  t1.join();
}

EMSCRIPTEN_BINDINGS(myBindings) {
  emscripten::function("performWork", &performWork);
  emscripten::function("runInThread", &runInThread);
}
```

```js
// my-js-main-thread.js
const m = await main();
console.log(m.performWork); // prints out the correct "function"
m.runInThread("console.log(Module.performWork);"); // prints undefined - so I cannot use Embind code here
```

> Another way would be use emscripten_exit_with_live_runtime in the pthread and then use addEventListener in the worker to listen for message sent via postMessage from the main thread.

I didn't fully understand this part. Do you suggest to have Emscripten create a thread for me, but then using my own JS code, instead of the Emscripten-generated `xxx.worker.js`?!

**Comment by donalffons** [comment]
@sbc100 @kripken

Trying to put this simple / into one sentence: Can I use one Emscripten module with an Embind-generated API from multiple worker-threads in JavaScript (with shared memory) to execute code in parallel?

This is a sketch of what I roughly have in mind:

![Untitled Diagram drawio](https://user-images.githubusercontent.com/33040347/178975130-5361c97a-d861-414d-be2f-fd67b246ce93.png)

I have tried to research this more and it looks to me like this hasn't been done yet (but I hope I'm wrong :wink:). In my layman understanding of Emscripten, I believe this should be possible.

Thanks a lot for your fantastic work and continued help :slightly_smiling_face:!

**Comment by sbc100** [comment]
I don't quite understand why you have two different types of worker here.. you have the emscripten-managed pthread workers and then you seem to have another type of non-emscripten-manged worker?

In general you want emscripten to manage the workers / pthreads otherwise there is a risk that you are going going setup them up correctly (e.g. TLS init, contructors, pthread_self, etc, etc)..  a lot of stuff has to be setup correctly for the emscripten-generated code to run on a thread in thread safe manor.  

How are setting you Worker 1 and Worker 2, are you post-messaging the module and the memory over yourself?

**Comment by sbc100** [comment]
;TLDR; I would not recommend trying to use both your own hand roller worker threads and emscripten's pthreads.   It sounds like a lot of work and a lot could go wrong.

**Comment by donalffons** [comment]
> I don't quite understand why you have two different types of worker here.. you have the emscripten-managed pthread workers and then you seem to have another type of non-emscripten-manged worker?

Simple example: My Emscripten Module has a single-threaded JS API function named `loadFile`. If I want to load 100 files via that API, I have no way of parallelizing that, except by introducing a new C++ function incl bindings. If I could have JS workers that have parallel access to the same Emscripten module, I could parallelize that task.

My project has a large number of functions and use-cases (not just loading files). Therefore, I'm trying to understand if there's a way to make parallel calls from JS.

> In general you want emscripten to manage the workers / pthreads [...]

Yes, thanks for making that clear.

> How are setting you Worker 1 and Worker 2, are you post-messaging the module and the memory over yourself?

In my tests, I was post-messaging only the memory around and then ran into problems.

> ;TLDR; I would not recommend trying to use both your own hand rolled worker threads and emscripten's pthreads. It sounds like a lot of work and a lot could go wrong.

But I cannot use Embind API's on emscripten-managed pthreads, can I?! I tried that in my previous post and failed miserably :wink:.

**Comment by donalffons** [comment]
@sbc100 sorry to bug you again.
I don't think this works. In this example, the embound function (is this a thing?) `runInThread` is supposed to `eval` js code in the string `msg`.
```cpp
void runInThread(std::string msg) {
  std::thread t1([](std::string msg) {
    EM_ASM(
      eval(UTF8ToString($0)); // I've tried emscripten_run_script too with no success
    ,msg.c_str());
  }, msg);
  t1.join();
}
```

Trying to use another embound function `emscripten::function("runInThread", &runInThread)` fails. The `Module` object is defined, though...
```js
m.runInThread("console.log(Module);"); // {wasmModule: null, wasmMemory: Memory(256), buffer: SharedArrayBuffer(16777216), ENVIRONMENT_IS_PTHREAD: true, instantiateWasm: ƒ, …}
m.runInThread("Module.performWork();"); // Error! Module.performWork is not a function
```

**Comment by sbc100** [comment]
I see yes.  Just to confirm, `performWork` in this case is something from `EMSCRIPTEN_BINDINGS`? 

I guess you are correct, and that `EMSCRIPTEN_BINDINGS` just doesn't work on anything but the main thread, since it relies on global constructors that run on just the main thread, vbut create a bunch of JS-side stuff which is all effectively TLS.

@brendandahl if we just made `EMSCRIPTEN_BINDINGS` run on every thread would that be enough, or are there also other C++ side structures which would also need to be thread-local?

**Comment by donalffons** [comment]
> performWork in this case is something from EMSCRIPTEN_BINDINGS

Yes (details are in the original issue / first post).

Thanks for taking a closer look. I think this would be an important feature to have!

**Comment by brendandahl** [comment]
> @brendandahl if we just made `EMSCRIPTEN_BINDINGS` run on every thread would that be enough, or are there also other C++ side structures which would also need to be thread-local?

I think running those on each thread would be enough. I wonder if this did work at some point in the past, since worker.js does currently handle [loading the native embind types](https://github.com/emscripten-core/emscripten/blob/d947b506149902497628c3114dbb89e50ee12c0a/src/worker.js#L216).

**Comment by donalffons** [comment]
Fantastic, thank you @sbc100!
Trying this out with a minimal example works but also logs an error to the console: `Pthread 0x5065b0 initializing embind.`

![image](https://user-images.githubusercontent.com/33040347/180618864-df8320b2-4713-41a8-8c7b-7fbf3adbc408.png)


```cpp
// embind-main.cpp
#include <string>
#include <exception>
#include <iostream>
#include <thread>

#include <emscripten.h>
#include <emscripten/bind.h>

void performWork() {
  std::cout << "performWork" << std::endl;
  int *i = new int;
}

void runInThread(std::string msg) {
  std::thread t1([](std::string msg) {
    EM_ASM(
      console.log("runInThread ", UTF8ToString($0));
      eval(UTF8ToString($0));
    ,msg.c_str());
  }, msg);
  t1.join();
}

EMSCRIPTEN_BINDINGS(myBindings) {
  emscripten::function("performWork", &performWork);
  emscripten::function("runInThread", &runInThread);
}
```

```js
// main.js
(async () => {
  const m = await main();
  m.runInThread("Module.performWork();");
})();
```

```sh
# build.sh
emcc \
  --bind embind-main.cpp \
  -s EXPORT_ES6=1 \
  -s USE_ES6_IMPORT_META=1 \
  -pthread \
  -s PTHREAD_POOL_SIZE='navigator.hardwareConcurrency' \
  -s ENVIRONMENT='web,worker' \
  -s ALLOW_MEMORY_GROWTH \
  -o ../my-app/emscripten/main.js
```

**Comment by sbc100** [comment]
At it looks like I left a unguarded log message in there.
