### ISSUE TITLE
Bug in page: Download and install 

### ISSUE THREAD

**Issue by twome** [emscripten-core/emscripten#17394]
It seems like the "Note:" asides/boxouts are not being closed properly in the markup, as the entire article keeps descending into futher and further nested "Note"s.

URL: ../../docs/getting_started/downloads

**Comment by sbc100** [comment]
Thanks!  

@kripken do you think was the recent update you just did?

**Comment by kripken** [comment]
PR lgtm. But do we know what could have caused this? I built locally with the right sphinx version...

**Comment by kripken** [comment]
I tried that and the diff is empty. So perhaps #17400 fixed it..?
