### ISSUE TITLE
Incorrect definition of bigintToI53Checked()/MAX_INT53/MIN_INT53 (off by one)

### ISSUE THREAD

**Issue by sgbeal** [emscripten-core/emscripten#17391]
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.13 (531257621816c200bc7c3be53129494afd029aec)
```

The generated JS glue code includes this snippet:

```
        var MAX_INT53 = 9007199254740992;
        var MIN_INT53 = -9007199254740992;
        function bigintToI53Checked(num) {
            return (num < MIN_INT53 || num > MAX_INT53) ? NaN : Number(num);
        }
```

However, that does not jive with:

```
Number.MIN_SAFE_INTEGER ==> -9007199254740991
Number.MAX_SAFE_INTEGER ==>  9007199254740991
```

Note that the `(num < MIN_INT53 || num > MAX_INT53)` check is off by one in each direction, counting 9007199254740992 and -9007199254740992 as valid integers, which they're not. The solution is for the MIN/MAX_INT53 values each need to be adjusted by 1 step towards zero. Even better, remove the MIN/MAX decls and use `Number.MIN/MAX_SAFE_INTEGER`.

**Comment by sbc100** [comment]
See the discussion here https://github.com/emscripten-core/emscripten/pull/16787#discussion_r863809229. 

@juj, WDYT, can we just use Number.MIN_SAFE_INTEGER?
@sgbeal is there a particular reason you care about this?  Is it causing you any issue?

**Comment by sgbeal** [comment]
It's not causing me any issue because i'm not using that code - just randomly stumbled across it while reading. i care about it only in the sense that i generically care that the software i'm using is behaving correctly ;).

FWIW, it's curious that it's apparently the spec which is off by one, but it seems most prudent to follow the spec even when it's wrong. (For example, note how the `HTTP_REFERER` header is _still_ spelled wrong because it made it through the standardization process before anyone noticed.)

Closing this, as it's apparently already under discussion by folks who care about it more than i do ;).
