### ISSUE TITLE
[WEBGPU] Consider removing the explicit size when creating a GPUCanvasContext

### ISSUE THREAD

**Issue by gracicot** [emscripten-core/emscripten#17416]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.15 (8b4443a87f5eab5dbb9adb690f9ebed0a9da4bd9)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Here's the browser warning:

> Setting an explicit size when calling configure() on a GPUCanvasContext has been deprecated, and will soon be removed. Please set the canvas width and height attributes instead. Note that after the initial call to configure() changes to the canvas width and height will now take effect without the need to call configure() again.

Emscripten should consider updating it's webgpu context initialization code.

**Comment by kripken** [comment]
cc @shrekshao @kainino0x

**Comment by kainino0x** [comment]
Work will be needed on [`webgpu.h`](https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.h) if we want to remove the size from the C API - but that API is common to both web and native, so we probably won't actually want to remove it. (That API needs some rework too, but we haven't been able to do it.)

To fix this warning, I think we can remove the `"size"` field from the JS descriptor and instead set `context["canvas"]["width"]` and `context["canvas"]["height"]` if they're not 0 in the C descriptor.

https://github.com/emscripten-core/emscripten/blob/fb8375f67e302aa9bf3cce9bdf71901fcd9c5b50/src/library_webgpu.js#L2584-L2589

**Comment by kainino0x** [comment]
@gracicot maybe you can try out this change and open a PR? Otherwise @shrekshao can probably look into it at some point.
