### ISSUE TITLE
Asyncify. RuntimeError: indirect call to null

### ISSUE THREAD

**Issue by DiachenkoIgor** [emscripten-core/emscripten#17422]
Hi, after upgrade emcc from [3.0.0] to [3.1.4] I have started to receive error 'RuntimeError: indirect call to null'. Such exception occurs in place where Asyncify is used for sync call to JS async API. I haven't reproduced simple example of this bug(my project has complex structure). However, can you help me with way to research and fix this problem? Maybe exception refers to optimization mechanism?
** Error disappears when code that invokes Asyncify calls is wrapped around std::cerr.

**Comment by kripken** [comment]
The best thing might be to bisect on that range,

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by DiachenkoIgor** [comment]
Thank you for this tool. Problem appears between 3.1.10 and 3.1.11 versions. There were a lot of changes. Can you give me some information for fixing it?

**Comment by kripken** [comment]
The link above shows how to bisect within a specific version, which would give a much smaller range of changes I hope. Then the fix might become very obvious.
