### ISSUE TITLE
How to customize Binaryen optimization in emsdk?

### ISSUE THREAD

**Issue by everywill** [emscripten-core/emscripten#17442]
I encounter a problem when compiling Release version of my library, it makes the webpage crash(ios 15.1 and 15.2), but the Debug version of the same library works well. 
The difference between them is '-g' flag which make Binaryen run limited optimization on Debug version. I want to figure out which optimization affect, is there a way to customize Binaryen optimization in emsdk?

**Comment by kripken** [comment]
The simplest thing might be to run `wasm-opt` after emscripten. Build with say `emcc -O1` (and not `O2` or above which would run binaryen for you). Then you can run `wasm-opt` with various options and see what matters to that iOS issue.

You can also use `emcc -sBINARYEN_EXTRA_PASSES=-g` for example to add flags for `emcc` to pass to `wasm-opt`.
