### ISSUE TITLE
addFunction is dropped from emscripten generated js file

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#17456]
Hi,

My java script has the following call to c++ and it failed to load `addFunction`:
```
 _Native_Attach(this.getID,
                            allocateUTF8("OnObjectSelected"),
                            Emval.toHandle(eventFunc),
                            addFunction((eventFunc_ ,V0) => {
                                var jseventFunc = Emval.toValue(eventFunc_);                                                
                                jseventFunc(UTF8ToString(V0));
                            }, 'vii'));
```

The emscripten `addFunction `is dropped from js file when compiling it with any optimization flag.
compiling with -g is OK.
what can be the reason of addFunction disappearing ?

**Version of emscripten/emsdk:**
3.1.9

**Comment by sbc100** [comment]
`addFunction` should still be part of the emscripten output in 3.1.9 and even in the latest release (3.1.16).   Even after the recent change in #17370 which made it into 3.1.16 the default output should still contain that function.

For example:

```
$ ./emcc tests/hello_world.c -o out.js
grep "function addFunction" out.js 
function addFunction(func, sig) {
```

Can you specify the full link command that you are using so we can maybe figure out what is going on?

How are you injecting the _Native_Attach function?  Is it in a `--pre-js` or a `--js-library`, maybe?

**Comment by aharondavid** [comment]
you right, `--pre-js` fixed the problem, but
if the `--pre-js` is done on a large js file (500k, and it is use in a lot of  c++ exported functions), I get an error:  `myProject.Emscripten.js.pp.js growableHeap' failed`.
am I missing another flag ?

**Comment by kleisauke** [comment]
Linking with `-sEXPORTED_RUNTIME_METHODS=addFunction` would probably resolve this as well. You might also need to link with `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$addFunction` before Emscripten 3.1.16.

**Comment by aharondavid** [comment]
with the both of those flags, I get an error:
error : undefined symbol: addFunction (referenced by top-level compiled C/C++ code)

**Comment by kleisauke** [comment]
> referenced by top-level compiled C/C++ code

It looks like you're calling `addFunction` in C or C++? You might need to use the [EM_JS()](https://emscripten.org/docs/api_reference/emscripten.h.html#c.EM_JS) or [EM_ASM()](https://emscripten.org/docs/api_reference/emscripten.h.html#c.EM_ASM) macros for that, see:
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-from-c-c

If you're using Embind (I noticed `Emval.toHandle()` in your above example), you could use `emscripten::val::module_property("addFunction")`, see for example:
https://github.com/kleisauke/wasm-vips/blob/797022a66ea9992ef9e66b9329dc16cd66397131/src/bindings/connection.cpp#L57-L60
or:
https://github.com/emscripten-core/emscripten/blob/a41b1a37d25f85c85c269150f49172642a93b73d/tests/embind/test_custom_marshal.cpp#L65-L68

**Comment by aharondavid** [comment]
fixed.
using -s EXPORTED_RUNTIME_METHODS=addFunction is enough.
I hade duplicate EXPORTED_RUNTIME_METHODS definition.

Thanks !

**Comment by aharondavid** [comment]
> you right, `--pre-js` fixed the problem, but if the `--pre-js` is done on a large js file (500k, and it is use in a lot of c++ exported functions), I get an error: `myProject.Emscripten.js.pp.js growableHeap' failed`. am I missing another flag ?

but this question still relevant

**Comment by kleisauke** [comment]
Perhaps you're not linking the final JS with `-sALLOW_MEMORY_GROWTH`?

**Comment by aharondavid** [comment]
sALLOW_MEMORY_GROWTH is used.
here is the emcc command:
`emcc.bat Main.o --pre-js TEApiWrapper_for_emscripten.js  -g0 -s ALLOW_TABLE_GROWTH -s WASM_BIGINT   -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,addFunction  -s EXPORTED_FUNCTIONS=_main,_CreateTE4WEB,_openFly  -s OFFSCREEN_FRAMEBUFFER=1 -s OFFSCREENCANVAS_SUPPORT=1  --bind -s USE_PTHREADS -s ALLOW_MEMORY_GROWTH=1   -s PTHREAD_POOL_SIZE=40 -Os --preload-file com.skyline.terraexplorer -o TerraExplorerApp.Emscripten.js`

**Comment by sbc100** [comment]
I won't understand that you man by `if the --pre-js is done on a large js file`.  Do you have code that didn't used to be part of pre-js that you are trying to make part of the pre-js? 

If all you want to do is call exports from the emscripten module you don't need to make you code part of `--pre-js`.    `--pre-js` can be useful in some circumstances, but there if you code simple wants to call `addFunction` it doesn't have to live there.

**Comment by aharondavid** [comment]
> I won't understand that you man by `if the --pre-js is done on a large js file`. Do you have code that didn't used to be part of pre-js that you are trying to make part of the pre-js?
> 
> If all you want to do is call exports from the emscripten module you don't need to make you code part of `--pre-js`. `--pre-js` can be useful in some circumstances, but there if you code simple wants to call `addFunction` it doesn't have to live there.

using the `pre-js` is just for telling to compiler - do not eliminate `addFunction `from the generated emscripten js.
adding it to EXPORTED_RUNTIME_METHODS is also a good solution for me.
