### ISSUE TITLE
llvm-objcopy.exe: error: permission denied

### ISSUE THREAD

**Issue by caxapexac** [emscripten-core/emscripten#17452]
Everything worked fine before the update from the older version
Used: emsdk update, emsdk install latest, emsdk activate latest
Now it crashes even on the hello world example (tried run cmd as administrator already, didn't help)

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.16 (6f1214164cb4b854755689060e91fd8167bc97a4)
clang version 15.0.0 (https://github.com/llvm/llvm-project ffa7384f10b89b6322c827d29d25108e34b8f6f0)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: F:\Apps\emsdk\upstream\bin

**Failing command line in full:**
>F:\Apps\emsdk\upstream\emscripten\emcc main.c       
F:\Apps\emsdk\upstream\bin\llvm-objcopy.exe: error: permission denied
emcc: error: 'F:/Apps/emsdk/upstream/bin\llvm-objcopy.exe a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers' failed (returned 1)

**Full link command and output with `-v` appended:**
>F:\Apps\emsdk\upstream\emscripten\emcc main.c -v
 "F:/Apps/emsdk/upstream/bin\clang.exe" -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=16 -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=F:\Apps\emsdk\upstream\emscripten\cache\sysroot -Xclang -iwithsysroot/include\compat -v main.c -c -o C:\Users\caxap\AppData\Local\Temp\emscripten_temp_kcfo4xvo\main_0.o
clang version 15.0.0 (https://github.com/llvm/llvm-project ffa7384f10b89b6322c827d29d25108e34b8f6f0)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: F:\Apps\emsdk\upstream\bin
 (in-process)
 "F:\\Apps\\emsdk\\upstream\\bin\\clang.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v "-fcoverage-compilation-dir=F:\\Accel_2021\\W4\\t" -resource-dir "F:\\Apps\\emsdk\\upstream\\lib\\clang\\15.0.0" -D EMSCRIPTEN -D __EMSCRIPTEN_major__=3 -D __EMSCRIPTEN_minor__=1 -D __EMSCRIPTEN_tiny__=16 -isysroot "F:\\Apps\\emsdk\\upstream\\emscripten\\cache\\sysroot" -internal-isystem "F:\\Apps\\emsdk\\upstream\\lib\\clang\\15.0.0\\include" -internal-isystem "F:\\Apps\\emsdk\\upstream\\emscripten\\cache\\sysroot/include/wasm32-emscripten" -internal-isystem "F:\\Apps\\emsdk\\upstream\\emscripten\\cache\\sysroot/include" -Werror=implicit-function-declaration "-fdebug-compilation-dir=F:\\Accel_2021\\W4\\t" -ferror-limit 19 -fmessage-length=229 -fvisibility default -fgnuc-version=4.2.1 -fignore-exceptions -fcolor-diagnostics -iwithsysroot/include/SDL "-iwithsysroot/include\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o 
"C:\\Users\\caxap\\AppData\\Local\\Temp\\emscripten_temp_kcfo4xvo\\main_0.o" -x c main.c
clang -cc1 version 15.0.0 based upon LLVM 15.0.0git default target x86_64-pc-windows-msvc
ignoring nonexistent directory "F:\Apps\emsdk\upstream\emscripten\cache\sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 F:\Apps\emsdk\upstream\emscripten\cache\sysroot/include/SDL
 F:\Apps\emsdk\upstream\emscripten\cache\sysroot/include\compat
 F:\Apps\emsdk\upstream\lib\clang\15.0.0\include
 F:\Apps\emsdk\upstream\emscripten\cache\sysroot/include
End of search list.
 "F:/Apps/emsdk/upstream/bin\wasm-ld.exe" -o a.out.wasm C:\Users\caxap\AppData\Local\Temp\emscripten_temp_kcfo4xvo\main_0.o -LF:\Apps\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free 
--export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024
 "F:/Apps/emsdk/upstream\bin\wasm-emscripten-finalize" --dyncalls-i64 a.out.wasm -o a.out.wasm --detect-features
 "F:/Apps/emsdk/node/14.18.2_64bit/bin/node.exe" F:\Apps\emsdk\upstream\emscripten\src\compiler.js C:\Users\caxap\AppData\Local\Temp\tmpxobuclyf.json
 "F:/Apps/emsdk/upstream/bin\llvm-objcopy.exe" a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers
F:\Apps\emsdk\upstream\bin\llvm-objcopy.exe: error: permission denied
emcc: error: 'F:/Apps/emsdk/upstream/bin\llvm-objcopy.exe a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers' failed (returned 1)

UPD: a.out.wasm was created before the crash btw

UPD2: 
Manually calling `F:/Apps/emsdk/upstream/bin\llvm-objcopy.exe a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers` seems working (at least no errors in the terminal)

UPD3: fully reinstalled sdk following the getting started guide, still the same issue

UPD4: emcc --check
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.16 (6f1214164cb4b854755689060e91fd8167bc97a4)
shared:INFO: (Emscripten: Running sanity checks)

UPD5: emcc tests/hello_world.cpp (bundled hellow world from troubleshooting guide)
F:\Apps\emsdk\upstream\bin\llvm-objcopy.exe: error: permission denied
emcc: error: 'F:/Apps/emsdk/upstream/bin\llvm-objcopy.exe a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers' failed (returned 1)

**Comment by caxapexac** [comment]
3.0.0 works

**Comment by caxapexac** [comment]
It works on the same terminal that I used to reinstall the sdk
It doesn't work on another terminal

**Comment by caxapexac** [comment]
Sometimes I'm getting this after reinstalling to older versions (3.0.0-3.1.16):

F:\Apps\emsdk\upstream\emscripten>emcc tests\hello_world.c
shared:INFO: (Emscripten: Running sanity checks)
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "F:\Apps\emsdk\upstream\emscripten\cache\sysroot_install.stamp" for subsequent builds)
cache:INFO:  - ok
Traceback (most recent call last):
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 4011, in <module>
    sys.exit(main(sys.argv))
  File "F:\Apps\python\lib-python\3\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 4004, in main
    ret = run(args)
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 1136, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "F:\Apps\python\lib-python\3\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 2698, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 2678, in compile_source_file
    cmd = get_clang_command(input_file)
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 2619, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "F:\Apps\emsdk\upstream\emscripten\\emcc.py", line 888, in get_cflags
    ports.add_cflags(cflags, settings)
  File "F:\Apps\emsdk\upstream\emscripten\tools\ports\__init__.py", line 359, in add_cflags
    needed = get_needed_ports(settings)
  File "F:\Apps\emsdk\upstream\emscripten\tools\ports\__init__.py", line 309, in get_needed_ports
    needed = set(p for p in ports if p.needed(settings))
  File "F:\Apps\emsdk\upstream\emscripten\tools\ports\__init__.py", line 309, in <genexpr>
    needed = set(p for p in ports if p.needed(settings))
  File "F:\Apps\emsdk\upstream\emscripten\tools\ports\sqlite3.py", line 20, in needed
    return settings.USE_SQLITE3
  File "F:\Apps\emsdk\upstream\emscripten\tools\settings.py", line 160, in __getattr__
    assert attr in self.allowed_settings, f"internal error: attempt to read setting '{attr}' while in limited settings mode"
AssertionError: internal error: attempt to read setting 'USE_SQLITE3' while in limited settings mode

**Comment by caxapexac** [comment]
3.1.16 permission denied
3.1.15 permission denied
3.1.14 https://github.com/emscripten-core/emscripten/issues/17452#issuecomment-1186424909

**Comment by sbc100** [comment]
The `USE_SQLITE3` issue looks like a stale file is being left around somehow.  The `upstream\emscripten\tools\ports\sqlite3.py` file should not exist on any version prior to 3.1.15 (it was added in 3.1.15). 

I'm guess there some kind of issue where the old `upstream\emscripten\tools\ports\sqlite3.py` (or .pyc) is not being deleted correctly when you downgrade.. although this should not be possible since I'm sure we replace the entire `upstream` directory.

**Comment by sbc100** [comment]
The `objcopy` issue looks like it was fixed by #17271 which was released as part of 3.1.14.   However, it doesn't looks like the issue should have effected any actual releases since the `objcopy` was should not have effect anything before (#17255).

**Comment by sbc100** [comment]
Can you see if setting `EMCC_READ_METADATA=binaryen` in your environment make the issue do away with the latest SDK?

**Comment by sbc100** [comment]
Do you mean that `EMCC_READ_METADATA=binaryen` fixed it?  Or that it just starting working for some unknown reason?

If `EMCC_READ_METADATA=binaryen` fixed it then I'm rather confused because #17271 fixed that issue...

**Comment by sbc100** [comment]
The "permission denied" occurs on windows then one process still has a file handle open to the wasm files `llvm-objcopy.exe` cannot write to it.  There was a bug where the python code for extracting the metadata would not close the file handle once it was done, but that bug was fixed in #17271.

**Comment by caxapexac** [comment]
> Do you mean that `EMCC_READ_METADATA=binaryen` fixed it? Or that it just starting working for some unknown reason?
> 
> If `EMCC_READ_METADATA=binaryen` fixed it then I'm rather confused because #17271 fixed that issue...

@sbc100 yes I mean it fixed the issue and I don't know why. We have two completely different windows machines with the same issue so it isn't because of hardware or something. What can I do to help you locate the root of the problem? Because current solution looks like a hack just a bit

**Comment by sbc100** [comment]
Firstly, can you completely remove your emsdk directory and try installing from scratch?  The other issue you are seeing look like perhaps some remnants is prior version are not correctly being removed.    Then can you verify that the issue occurs with `./emsdk install tot`?  

If the issue persists then can you add some debugging to `tools/webassembly.py`?  I suspect this is the place where the wasm file is being left open perhaps.

Can you add some looking in the `Module.__init__` and `Module.__del__` methods.  Perhaps print the name of the file when it is opened on line 187, and then print something when it is closed on line 196.  You should see a close for every open before the call the objcopy.

**Comment by sbc100** [comment]
I'd like to figure out why it broken in on your machine and not on others.    We have to figure it out because the plan is to removing `EMCC_READ_METADATA=binaryen` soon.

Could you help by adding the debug print statements to `tools/webassembly.py`?

**Comment by caxapexac** [comment]
@sbc100 of course
Just haven't enough time before

```
F:\Apps\emsdk\upstream\emscripten>emcc tests\hello_world.c
!!! webassembly.py
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py once
!!! webassembly.py end file
!!! webassembly.py memoize
!!! webassembly.py memoize end
!!! webassembly.py Module __init__
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_exports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module get_exports end
!!! webassembly.py memoize wrapper end
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_imports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py memoize wrapper end
!!! webassembly.py Module parse_features_section
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_custom_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py memoize wrapper end
!!! webassembly.py Module get_function
!!! webassembly.py once helper
!!! webassembly.py Module _calc_indexes
!!! webassembly.py memoize wrapper
!!! webassembly.py memoize wrapper end
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_functions
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py memoize wrapper end
!!! webassembly.py Module read_type
!!! webassembly.py Module __init__
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_imports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py memoize wrapper end
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_exports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string end
!!! webassembly.py Module get_exports end
!!! webassembly.py memoize wrapper end
F:\Apps\emsdk\upstream\bin\llvm-objcopy.exe: error: permission denied
emcc: error: 'F:/Apps/emsdk/upstream/bin\llvm-objcopy.exe a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers' failed (returned 1)
```
[webassembly.txt](https://github.com/emscripten-core/emscripten/files/9143586/webassembly.txt)

**Comment by caxapexac** [comment]
With file open (seems like garbage collector wont destroy Module cuz of some reason...)

```
F:\Apps\W4Trial\emsdk\upstream\emscripten>emcc tests\hello_world.c
!!! webassembly.py
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py memoize
!!! webassembly.py once
!!! webassembly.py end file
!!! webassembly.py memoize
!!! webassembly.py Module __init__ a.out.wasm
!!!!! webassembly.py Module OPENED FILE a.out.wasm
!!! webassembly.py Module __init__ end a.out.wasm size: 13643
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_exports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module get_exports end
!!! webassembly.py memoize wrapper end
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_imports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py memoize wrapper end
!!! webassembly.py Module parse_features_section
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_custom_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py memoize wrapper end
!!! webassembly.py Module get_function
!!! webassembly.py once helper
!!! webassembly.py Module _calc_indexes
!!! webassembly.py memoize wrapper
!!! webassembly.py memoize wrapper end
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_functions
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py memoize wrapper end
!!! webassembly.py Module read_type
!!! webassembly.py Module __init__ a.out.wasm
!!!!! webassembly.py Module OPENED FILE a.out.wasm
!!! webassembly.py Module __init__ end a.out.wasm size: 12226
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_imports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py memoize wrapper end
!!! webassembly.py memoize wrapper
!!! webassembly.py Module get_exports
!!! webassembly.py Module get_section
!!! webassembly.py Module sections
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module read_string
!!! webassembly.py Module get_exports end
!!! webassembly.py memoize wrapper end
F:\Apps\W4Trial\emsdk\upstream\bin\llvm-objcopy.exe: error: permission denied
emcc: error: 'F:/Apps/W4Trial/emsdk/upstream/bin\llvm-objcopy.exe a.out.wasm a.out.wasm --remove-section=.debug* --remove-section=producers' failed (returned 1)
```
[webassembly.txt](https://github.com/emscripten-core/emscripten/files/9143641/webassembly.txt)

**Comment by caxapexac** [comment]
@sbc100 hi, can I help you with anything else?

**Comment by sbc100** [comment]
So it looks like the `__del__` is never called on the webassembly object, is that right?

**Comment by sbc100** [comment]
Can you check if you are using the python executable that comes with emsdk (you can `print(sys.executable)` if you need to)

**Comment by sbc100** [comment]
I think #17516 should fix this.

**Comment by sbc100** [comment]
Can you confirm that the `tot` emsdk release fixes this issue?  (`./emsdk install tot`)

**Comment by caxapexac** [comment]
@sbc100 please wait for 1-2 days, really out of time, will check asap

**Comment by caxapexac** [comment]
@sbc100 I'm sorry, life went crazy these months :)
Just checked out on 3.1.24, everything works fine and compiles without `EMCC_READ_METADATA=binaryen`, thanks!
