### ISSUE TITLE
emscripten_get_canvas_element_size has no signature in compiled .js

### ISSUE THREAD

**Issue by Neuhaus24** [emscripten-core/emscripten#17460]
When compiling with the following command the output .js file is missing '_emscripten_get_canvas_element_size.sig="ipii"'

emcc --bind -s LINKABLE=1 --profiling-funcs -s MAIN_MODULE=1 -s EXPORT_ALL=1 -fPIC -s WASM=1 -s USE_SDL=2 -s ASSERTIONS=0 -s FETCH=1 -s ALLOW_MEMORY_GROWTH=1 -s DEMANGLE_SUPPORT=1 -s DISABLE_EXCEPTION_CATCHING=0   -s MODULARIZE=1 -s EXPORT_NAME="MediaPlayer" -O3  build/HtmlMediaElement.o build/HtmlPlayer.o build/mediaPlayer.o build/wasmLogger.o build/wasmMainLoop.o build/wasmVideoRenderer.o video/build/video_core.bc --preload-file /src/api/c/../../mediaplayer/ffmpeg-4.2.9001/solib/libffmpeg.so@/ --use-preload-plugins -o dist/mediaPlayer.js 

When editted manually to include the missing line the project runs completely fine, and none of the other equivalent functions are missing signatures

**Version of emscripten/emsdk:**
3.1.13 using docker image

**Comment by sbc100** [comment]
I do see a signature entry for that function here: https://github.com/emscripten-core/emscripten/blob/a41b1a37d25f85c85c269150f49172642a93b73d/src/library_html5.js#L2608

It does looks like its only included when USE_PTHREADS is not set.. and you are not setting USE_PTHREADS so I wonder why we don't see it.

**Comment by Neuhaus24** [comment]
Is there more information that would be helpful for you to have here?

**Comment by sbc100** [comment]
Oh, it looks like this was already fixed in #17214.   All you should need to do is update to 3.1.14 or above.

**Comment by Neuhaus24** [comment]
Great, thanks
