### ISSUE TITLE
-s ASYNCIFY=1 and -g

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#17461]
Hi. I recently updated to latest emscripten for Dune2. It uses `ASYNCIFY=1`, but now when I compile project normally I have a lot of message like:

```
warning: Asyncify onlylist contained a non-existing function name: GameOptions_Save (GameOptions_Save)
warning: Asyncify onlylist contained a non-existing function name: Game_Init (Game_Init)
warning: Asyncify onlylist contained a non-existing function name: Game_LoadScenario (Game_LoadScenario)
```

Almost every function that I have in asyncify list generate this warning. And of course when I run the game in browser it didn't work. But if I add `-g` to compile command this warnings goes away and game works.

I bisected the emscripten and I found this:
```
2.0.16 - good
2.0.17 - bad

36b5542aabc779a683f68df501938a9342df64ca is the first bad commit
commit 36b5542aabc779a683f68df501938a9342df64ca
Author: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
Date:   Tue Mar 30 00:14:38 2021 +0000

    Roll binaryen from 9c1d69f6596b to 9b38e4394034 (6 revisions)
    
    https://chromium.googlesource.com/external/github.com/WebAssembly/binaryen.git/+log/9c1d69f6596b..9b38e4394034
    
    2021-03-29 7121787+tlively@users.noreply.github.com LUBs (#3731)
    2021-03-29 azakai@google.com Scan module-level code in necessary places (#3744)
    2021-03-29 azakai@google.com [Wasm GC] Fix SSA pass on non-nullable parameters (#3745)
    2021-03-29 azakai@google.com Fix reduction of nondefaultable tuples (#3746)
    2021-03-29 azakai@google.com handleNonNullableLocals(): Do not modify params (#3740)
    2021-03-29 azakai@google.com Inlining: Always inline single-use functions (#3730)
    
    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/binaryen-emscripten-releases
    Please CC wasm-waterfall@grotations.appspotmail.com on the revert to ensure that a human
    is aware of the problem.
    
    To report a problem with the AutoRoller itself, please file a bug:
    https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
    
    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
    
    Tbr: wasm-waterfall@grotations.appspotmail.com
    Change-Id: I62bfb18af403bbab989cef0b3cb8ab023f855d84
    Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/2791984
    Commit-Queue: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>
    Bot-Commit: chromium-autoroll <chromium-autoroll@skia-public.iam.gserviceaccount.com>

 DEPS | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by sbc100** [comment]
Interesting, those revisions of emscripten (2.0.16 and 2.0.17) are over a year old now.    I assume the problem persists with the latest version too?

@kripken?

**Comment by curiousdannii** [comment]
2.0.17 changed how functions were inlined, I saw this in my own project. Can you change from ASYNCIFY_ONLY to one of the other settings?

**Comment by caiiiycuk** [comment]
Nope, project stop working. If I use -s ASSERTIONS=1 I can see unreachable executed exceptions. This mean I can build asyncify list for build without -g. But it’s strange cause I think -g only should change name of functions. And building list without -g is harder cause you should look into mapping list for function name. More over I am not sure not if this list will be “stable”

**Comment by kripken** [comment]
Yes, likely it is inlining, I think @curiousdannii is right. Specifically:

> Inlining: Always inline single-use functions (WebAssembly/binaryen#3730)

If the project stops working then what I'd bet is happening is something like this:

```js
function main() {
  Game_Init();
}
```

`Game_Init` ends up inlined, and now `main` needs to be in the list.

To avoid this you can do `-sBINARYEN_EXTRA_PASSES=--one-caller-inline-max-function-size=15` (that goes back to the old behavior.

Or, find and add the function that the code ends up inlined into. Maybe it is just `main`? As you said @caiiiycuk that might change over time in theory, but probably it would be rare.

> But it’s strange cause I think -g only should change name of functions

In general yes, but there are some exceptions. In debug builds we may inline slightly differently to make the code more readable (clang emits a wrapper for `main`, and it makes debugging harder). I suspect that's what you are seeing here.

**Comment by caiiiycuk** [comment]
I can confirm `-sBINARYEN_EXTRA_PASSES=--one-caller-inline-max-function-size=15` fix the build. What about adding new flag that only minify function names? `-s ASYNCIFY=1 -g` is handy to build asyncify list.

**Comment by caiiiycuk** [comment]
Ahh, probably need to add flag to not minify names in release build --profiling-funcs still works? So I can use it with -s ASYNCIFY=1 to build the list...

**Comment by kripken** [comment]
Yes, `--profiling-funcs` just leaves function names, but otherwise it's a release build.
