### ISSUE TITLE
[EH] Stack trace support for Wasm EH

### ISSUE THREAD

**Issue by aheejin** [emscripten-core/emscripten#17466]
Currently, both in Emscripten and Wasm EH, if you throw an exception, stack traces are not attached by default. This was, at least for Wasm EH, an intentional decision, because Wasm exception itself can be used not only for errors but for other control flow structures with which slowdown can be problematic. Native C++ exceptions don't have stack traces either.

But it is still convenient to see stack traces when debugging. I think we can attach stack traces when in debug / assert mode, by throwing an `Error` object instead of [a raw string](https://github.com/emscripten-core/emscripten/blob/d2e80a6a4c16d3be8d7fd0ca69c4bacdfce70be0/src/parseTools.js#L687) in case of Emscripten EH, and turning the optional `traceStack` option on in [the JS API](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md#api-additions) for Wasm EH.

Related request: #17437

**Comment by aheejin** [comment]
I think I can make this work for Wasm EH, but I'm not sure if the same is possible for Emscripten EH. If we throw a JS `Error` object in Emscripten EH, that's not going to be recognized as a C++ exception in our wasm code... Maybe we should only solve this for Wasm EH and recommend people to use it more.

**Comment by kripken** [comment]
+1 for fixing only in Wasm EH. Even if people can't ship with it yet on all browsers, for local debugging a developer can use a recent browser with Wasm EH.
