### ISSUE TITLE
resetPrototype creates an object without attributes set if passed undefined

### ISSUE THREAD

**Issue by SamiKalliomaki** [emscripten-core/emscripten#17472]
When:
 - `Module['instantiateWasm']` is set
 - `Module['wasmOffsetData']` is undefined

[resetPrototype](https://github.com/emscripten-core/emscripten/blob/6f1214164cb4b854755689060e91fd8167bc97a4/src/preamble.js#L832) creates an [invalid WasmOffsetConverter object](https://github.com/emscripten-core/emscripten/blob/6f1214164cb4b854755689060e91fd8167bc97a4/src/preamble.js#L1135).

When using `absl::Symbolize` this results in a crash because it [checks if `wasmOffsetConverter` is undefined](https://github.com/abseil/abseil-cpp/blob/master/absl/debugging/symbolize_emscripten.inc#L33).

```
  - TypeError: Cannot read properties of undefined (reading 'length')
      at WasmOffsetConverter.getIndex
      at WasmOffsetConverter.getName
      at _emscripten_pc_get_function
      at absl::Symbolize(void const*, char*, int)
```

I propose `resetPrototype` to be changed.
```diff
 function resetPrototype(constructor, attrs) {
+  if (attrs === undefined || attrs === null) {
+    return attrs;
+  }
   var object = Object.create(constructor.prototype);
   return Object.assign(object, attrs);
 }
```

An alternative would be to change `absl::Symbolize` to do additional checks but it seems easier to fix this in emscripten.

**Comment by sbc100** [comment]
emscripten_pc_get_function should only be defined in the presence of `USE_OFFSET_CONVERTER`... and if `USE_OFFSET_CONVERTER` is set then shouldn't wasmOffsetConverter always be non-null?

I.e. this line should never result in a null wasmOffsetConverter should it?

`wasmOffsetConverter = resetPrototype(WasmOffsetConverter, Module['wasmOffsetData']);`

**Comment by sbc100** [comment]
Are you building with `USE_OFFSET_CONVERTER` but then wanting to dynamically not support it?

**Comment by SamiKalliomaki** [comment]
We specify `Module['instantiateWasm']` because we already have already downloaded the WASM and want to avoid redownloading. (In practice I think browser might also cache it.) The reason we download it beforehand is that we want to track the download progress and show it to the user.

You are correct that we have a runtime flag to not specify `Module['instantiateWasm']` and to have the offset converter actually work.

I was also considering trying to create the `WasmOffsetConverter` object manually and pass it in `wasmOffsetData`. However, I am not sure if this class supposed to be internal to emscripten or if it can be used in our code. Yet another project level fix could be passing in a dummy object with the expected properties set but that seems brittle.

**Comment by SamiKalliomaki** [comment]
Do you think it would be enough to unit test `resetPrototype` or would we need a test that sets `Module['instantiateWasm']` and `Module['wasmOffsetData']`?
