### ISSUE TITLE
Question about "C/C++ DevTools Support (DWARF) extension"

### ISSUE THREAD

**Issue by bgnx** [emscripten-core/emscripten#17490]
Everyone knows where is the source code of C/C++ DevTools Support (DWARF) browser [extension](https://goo.gle/wasm-debugging-extension) (from this article https://developer.chrome.com/blog/wasm-debugging-2020) ? Is it open-sourced (like chromium devtools itself) ?

**Comment by bgnx** [comment]
cc @RReverser @pfaffe

**Comment by pfaffe** [comment]
The extension is not open-source.

**Comment by bgnx** [comment]
> The extension is not open-source.

Why? It's weird considering that the chrome devtools themselves are completely open sourced. Any plans to open source this extensions?

**Comment by bgnx** [comment]
@pfaffe, there was older open sourced version (back_end/CXXDWARFSymbols) in devtools tree https://chromium.googlesource.com/devtools/devtools-frontend.git/+/f56f06bae08d1591ed51f7a25ba2c34028109dbc. 
Can I build something working using wasm build of this CXXDWARFSymbols folder with js wrappers from current version of extension (DWARFSymbols.js and SymbolsBackend.js) ?
