### ISSUE TITLE
Launch emscripten artifact with pthreads in Javascript

### ISSUE THREAD

**Issue by AlexMold** [emscripten-core/emscripten#17523]
```
Emscripten: 3.1.13
EMBIND
CMAKE linking/compiling
set(CMAKE_CXX_FLAGS "-O0 -lembind -pthread -g3 -s ALLOW_MEMORY_GROWTH=1 -s USE_PTHREADS=1")
${PROJECT_NAME}
    "-s WASM=1"
    "-s EXPORT_ES6=1"
    "-s ALLOW_MEMORY_GROWTH=1"
    "-s ENVIRONMENT=web,worker"
    "-s PTHREAD_POOL_SIZE='navigator.hardwareConcurrency'"
    "-s MODULARIZE=1"
```

On C++ side guys are using code with pthreads
Emscripten produces the following files
```
wasm_test.js
wasm_test.wasm
wasm_test.worker.js
```
on the frontend side, we are using the following code to launch the binary within web worker produced by emscripten
```
    const worker = new Worker('%PUBLIC_URL%/test/test_web.worker.js');
    const memory = getSharedMemory()
    worker.onmessage = (data) => {
      if (data.data.cmd === 'loaded') {
        worker.postMessage({ cmd: 'run', threadInfoStruct: ??? })
      }
    };
    worker.onerror = console.log.bind(null, 'on error ');
    fetch('/test/test_web.wasm').then(data => data.arrayBuffer()).then(bytes => {
      const mod = WebAssembly.compile(bytes);
      mod.then((wasmModule) => {
        worker.postMessage({
          cmd: 'load',
          wasmModule,
          urlOrBlob: '%PUBLIC_URL%/test/test_web.js',
          wasmMemory: memory
        })
      })
    });
```

Worker firing the `loaded` event but I can't figure out how to launch the run event/method
What is the right payload for the following event `worker.postMessage({ cmd: 'run', ??? })`???
How to run any C++ bound method?

**Comment by sbc100** [comment]
With emscripten, the way to create new workers/threads is to call `pthread_create` from the main thread.  If you don't it this way you will end up duplicating all the code we have in `library_pthread.js` for managing workers, and pthread APIs will likely not work correctly if you do this.   

For example, `library_pthread.js` expects to have visibility of all threads in the system, trying to create threads in some other way is going to problematic.

**Comment by AlexMold** [comment]
The entry point in the application is wasm_test.js file or wasm_test.worker.js???
Do you mean that I should not handle/create threads at all, but invoke APIs methods from the main thread?

**Comment by sbc100** [comment]
Yes, exactly.  Creation of threads/workers is really an implementation detail that you should not have to worry about.  

You should load `wasm_test.js` on your main thread and from there call C++ exports (for example `main`).  From there you can call pthread_create (or C++ std::thread) to create new threads.

**Comment by AlexMold** [comment]
It's was my first assumption, but for some reasons I though that worker file should be an entry point. Thank you

But if your wasm or worker file should be lazy loaded or cached in the browser, do you have the mechanism to allow developer to provide for `wasm_test.js` those files from another source?

**Comment by sbc100** [comment]
I believe you can use the `locateFile` override on the `Module` object specify alternative locations for these files.   See https://emscripten.org/docs/api_reference/module.html#Module.locateFile.     If you want to override the entire module instantiation process you can also override ` instantiateWasm`: https://emscripten.org/docs/api_reference/module.html#Module.instantiateWasm.

**Comment by AlexMold** [comment]
Thank you exhaustive explanation

**Comment by AlexMold** [comment]
@sbc100 Appeared  question during use )
chrome promts that `Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread`
and indeed it blocks the browser.

I thought that workers creating from the main thread and all calculations spread to workers. Is it true?
Or I need manually invoke smth to create threads for every calculation?

Thanks in advance

**Comment by sbc100** [comment]
See the documentation in https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread.   Basically you cannot synchronously start new worker threads.    So you either need to use `PROXY_TO_PTHREAD` (so that the main thread is not busy) or you need to pre-start you threads using `PTHREAD_POOL_SIZE`.
