### ISSUE TITLE
Fetch response data adds random characters (some kinda of overflow bug?)

### ISSUE THREAD

**Issue by rruipinheiro** [emscripten-core/emscripten#17530]
Hi,
I'm trying to use the fetch API to POST some data to my backend, and, for some strange reason, fetch->data adds more characters to the output. 

Details:

**Code**
```
void onsuccess(struct emscripten_fetch_t *fetch) {
  printf("fetch->data: %s\n", fetch->data);
  emscripten_fetch_close(fetch);
}

int main() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);
  strcpy(attr.requestMethod, "POST");
  attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
  attr.onsuccess = onsuccess;
  emscripten_fetch(&attr, "http://myapi.com/endpoint);
  return 0;
}

```

**Output:**
`{"JHABSDASJKDL":"user_name"}񎀀 `

**Expected output:** 
`{"JHABSDASJKDL":"user_name"}`

**Version of emscripten/emsdk:** 
os: macOS
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17-git
clang version 15.0.0 (https://github.com/llvm/llvm-project.git ffa7384f10b89b6322c827d29d25108e34b8f6f0)
Target: wasm32-unknown-emscripten
Thread model: posix

This happens depending on the backend output message. Does someone have some theories for this?
Thanks

**Comment by brendandahl** [comment]
There's extra stuff at the end because `fetch->data` is a char array, not a c string that is null terminated. You'll need to copy it to a string using fetch->numBytes or do something else with it.

e.g.
```c++
  std::string str(fetch->data, fetch->numBytes);
  printf("str: '%s'\n", str.c_str());
```

**Comment by rruipinheiro** [comment]
That makes sense... thanks for the help!
