### ISSUE TITLE
Extremely high memory usage on step "wasm-emscripten-finalize" with "-gsource-maps" or "-g" enabled

### ISSUE THREAD

**Issue by major-mayer** [emscripten-core/emscripten#17538]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17 (fbc532773d84d2bd7da876275671970e792ad1cd)
clang version 15.0.0 (https://github.com/llvm/llvm-project 17e4c217b66305e60657a48f10fe3c428c2fe4d2)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/laurenz/Checkouts/emsdk/upstream/bin

**Failing command line in full:**
```
/home/laurenz/Checkouts/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG -g2 -Os -gsource-map -fwasm-exceptions -sSUPPORT_LONGJMP=wasm -sEXPORT_EXCEPTION_HANDLING_HELPERS=1 -O0 -lembind -sLLD_REPORT_UNDEFINED -sINITIAL_MEMORY=131072000 -sPTHREAD_POOL_SIZE=8 -sASSERTIONS=1 -sDEMANGLE_SUPPORT=1 -pthread --no-entry --preload-file assets -Wl,-error-limit=0 -sFULL_ES2 -sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 -sOFFSCREEN_FRAMEBUFFER=1 -sEXPORTED_RUNTIME_METHODS=FS -sUSE_FREETYPE=1 -sUSE_GLFW=3 ShopFloorProgramming/mwNGSPWASM/CMakeFiles/mwNGSPWASM.dir/bind.cpp.o -o Binaries/build/mwNGSPWASM.js  ShopFloorProgramming/mwNGSP/libmwNGSP.a [ ... lots and lots of libraries ... ]  third_party/gl4es/gl/src/libGL.a
```

I am trying to build a relatively large project using Emscripten.
The builds work fine normally, but i would like to be able to set breakpoints into the compiled WASM code for a better debugging experience.
So i tried enabling the `-gsource-maps` or `-g` flags for regular source maps or the even better DWARF debugging information.

The problem that i have is:

1. It takes a really long time to generate those source maps (i mean the step when `wasm-sourcemaps.py` is running), but i could live with that if ...
2. After the source maps have been generated and the `wasm-emscripten-finalize` tool starts working, it takes huge amounts of memory and eventually it crashes completely, because it runs out of memory

I already have 32 GB of memory and 10 GB of swap space, but this doesn't seem to be enough. 
The memory consumption steadily grows until it reaches the maximum capacity and gets aborts eventually with the following message:

```
em++: error: '/home/laurenz/Checkouts/emsdk/upstream/bin/wasm-emscripten-finalize --output-source-map-url=mwNGSPWASM.wasm.map -g --dyncalls-i64 --dwarf Binaries/build/mwNGSPWASM.wasm -o Binaries/build/mwNGSPWASM.wasm --detect-features --input-source-map=Binaries/build/mwNGSPWASM.wasm.map --output-source-map=Binaries/build/mwNGSPWASM.wasm.map' failed (received SIGKILL (-9))
```

Just to try it, i once generated a whopping 100GB swap file and run the compilation, and it again filled up the (combined) memory up to 60+ GB.
Unfortunately though, despite the huge amount of "memory" available, it crashed with a SIGSEGV. 

Here is a picture of htop showing `wasm-emscripten-finalize` taking up lots of ram:
![wasm-emscripten-finalize](https://user-images.githubusercontent.com/17907799/181575823-ee71406c-017d-4db2-baef-0674ef692224.png)

**Comment by major-mayer** [comment]
I will try it :+1: 
Is it enough to put this flags on the final link step, or do i have to recompile everything from scratch?

**Comment by sbc100** [comment]
No.. you only need to relink to add those flags.

**Comment by major-mayer** [comment]
```
[build] em++: error: changes to the wasm are required after link, but disallowed by ERROR_ON_WASM_CHANGES_AFTER_LINK: ['/home/laurenz/Checkouts/emsdk/upstream/bin/wasm-emscripten-finalize', '--output-source-map-url=mwNGSPWASM.wasm.map', '-g', '--bigint', '--no-dyncalls', '--no-legalize-javascript-ffi', '--dwarf', 'Binaries/build/mwNGSPWASM.wasm', '-o', 'Binaries/build/mwNGSPWASM.wasm']
```

Do you see any flags that require changes to the WASM module after link time?

**Comment by sbc100** [comment]
I guess maybe `-gsource-maps` is requiring this.   Can you try dropping `-gsource-maps`?

**Comment by major-mayer** [comment]
Yes this was the cause for the error.
I replaced `-gsource-maps` with `-g` and now can finally use real DWARF-based debugging (at least on Chrome, Firefox tells me, that my wasm module is too big...).
Thank you very much man :heart:

**Comment by major-mayer** [comment]
By the way, is there some way to delay the execution of my WASM code until the C/C++ DevTools extension has loaded all symbols successfully?

I tried setting a breakpoint, before i call my expored c++ function, but that way often the symbol loading doesn't finish at all, especially when i reload the page: 
![grafik](https://user-images.githubusercontent.com/17907799/181615799-1189661d-ae2d-4c02-af71-536282ebd2e1.png)
