### ISSUE TITLE
try-catch not working as expected with -fwasm-exceptions

### ISSUE THREAD

**Issue by MAG-MichaelKelley** [emscripten-core/emscripten#17531]
**Version of emscripten/emsdk:**
3.1.17

We are experiencing an issue with `std::make_exception_ptr()` when enabling native WASM exceptions. It seems that the `catch(...)` body in the try-catch used to grab the value of `current_exception()` is not being executed in Chrome. I tried this manually to verify, and I get the same behaviour, even when adding a catch clause with the exact exception type we want to catch. Is this a limitation of wasm-exceptions currently?

**Comment by kripken** [comment]
I am not aware of any relevant known limitations of wasm exceptions. If you can provide a testcase that would be good as it could be an unknown bug.

**Comment by MAG-MichaelKelley** [comment]
I feel silly posting this, but we found the issue. For anyone else with this issue, here's the really simple and obvious fix:
Compile all of your static dependencies with exceptions enabled. Our issue was that we were only enabling exceptions in our main binary, but not for dependencies, so exceptions thrown there were not caught.
