### ISSUE TITLE
how to use cmake link a third static library to my new static library?

### ISSUE THREAD

**Issue by pkujhd** [emscripten-core/emscripten#17540]
Hi everybody!
 
I'm trying to use cmake toolchains link a third static library(e.g protobuf) into my new static library, I already add target_link_libraries(TARGET, protobuf), but generate link.txt only has command "emar qc target *.o"

How to change CMakeLists.txt to link static library?

thanks.

**Comment by sbc100** [comment]
As far as I know there is no easy way to link one static library into another with cmake.   Instead you would have like that additional library into all the binaries that use your library.

**Comment by pkujhd** [comment]
> tic library into another with cmake. Instead you would have like that additional library into all the binaries that use your library.

ok, Thank you for your answer
