### ISSUE TITLE
A bug report: (-1L is signed long)

### ISSUE THREAD

**Issue by Anonymity20202** [emscripten-core/emscripten#17585]
The minimal code example:
```C
#include <stdio.h>
#include <stdint.h>

static uint32_t a = 0x1509CF13L;
static int32_t b = 0xBA1441E2L;
static int32_t * volatile c = &b;

static int8_t  foo(void)
{
    (*c) ^= (a > (-1L));
    return 0;
}
int main (int argc, char* argv[])
{
    foo();
    printf("b: %x\n", b);
    return 0;
}
```

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.14 (4343cbec72b7db283ea3bda1adc6cb1811ae9a73)
clang version 15.0.0 (https://github.com/llvm/llvm-project 7effcbda49ba32991b8955821b8fdbd4f8f303e2)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Compilation option:**
`emcc -O2 -g -w `

**Bug Description:**
If I compile the program above with Clang-12, the generated x86 native executable prints: `b: ba1441e3`
But if I compile it with emcc, the generated WASM code prints: `b: ba1441e2`
(-1L) is  a signed long value (8 bytes in x64 system). Thus, `(a > (-1L))` is always true. I am not sure about the root cause, but it seems that emcc takes (-1L) as an i32 value.

**Comment by sbc100** [comment]
WebAssembly is a ILP32 platform which means int, long and pointer are all 32bit.  This is similar to i386 (x86-32).   

If you compile with gcc or clang on your x86 machine and you pass `-m32` you will see the same result as with emscripten:

```
$ clang test.c -m32
$ ./a.out 
b: ba1441e2
```

We are working on a wasm64 target, but its not yet shipping in any browsers today.  If you want to try it out you can use `-sMEMORY64=1` or `-sMEMORY64=2`.  This is will result in the same output as x86-64 becasue wasm64 and x86-64 are both LP64 platforms (long and pointers are 64-bit):

```
$ ./emcc test.c -sMEMORY64=2
$ node --experimental-wasm-bigint ./a.out.js 
b: ba1441e3
```

**Comment by Anonymity20202** [comment]
It is indeed due to the difference between ILP32 and ILP64 platforms. I did not realize that wasm is an ILP32 platform before. Thank you for your explanation! I will close this issue with this comment.
