### ISSUE TITLE
A bug report: possible incorrect loop unrolling

### ISSUE THREAD

**Issue by Anonymity20202** [emscripten-core/emscripten#17586]
The minimal code example:
```C
#include <stdio.h>
#include <stdint.h>

static int32_t a = -1;
volatile uint16_t b;
uint8_t c;
int f;

uint32_t d() {
  int64_t e;
  for (a = 0; a >= 0; a--)
    for (e = 0; e < 9; e++)
      for (c = 0; c < 2; c++)
        for (b; b; b++)
          f++;
}
void main() {
  d();
  printf("f: %d\n", f);
  printf("a: %d\n", a);
}
```

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.14 (4343cbec72b7db283ea3bda1adc6cb1811ae9a73)
clang version 15.0.0 (https://github.com/llvm/llvm-project 7effcbda49ba32991b8955821b8fdbd4f8f303e2)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Compilation option:**
`emcc -O2 -g -w `

**Bug Description:**
If I compile the program above with Clang-12 (-O0), the generated x86 native executable prints:
```
f: 0
a: 0
```
But if I compile it with emcc, the generated WASM code prints: 
```
f: 0
a: -1
```

**Comment by sbc100** [comment]
If I compile that code with gcc 11 I get the same results that emcc gives:

```
$ gcc -O2 -g -w test.c 
$ ./a.out 
f: 0
a: -1
```

If I compile with clang 13 I also get the same results:

```
$ clang-13 -O2 -g -w test.c 
$ ./a.out 
f: 0
a: -1
```

If I compile with clang 15 (tip of tree) I also get the same results.

So it seems that this is more likely an issue with clang 12 than with emcc?

Actually even if I compile 12 I get the same results.. so I guess I can't repro the 0,0 case at all here.. any idea what is going on?

```
$ clang-12 -O2 -g -w test.c 
$ ./a.out 
f: 0
a: -1
```

**Comment by Anonymity20202** [comment]
Hi @sbc100, thank you for your prompt reply. And sorry I have pasted the output incorrectly. The output of clang-12 compiled x86 code is `0, -1`, but the output of WASM code is `0, 0`. Could you please check again whether this result can be reproduced?
Thanks!

**Comment by sbc100** [comment]
emcc also produces the same result for me:

```
./emcc -O2 test.c 
$ node a.out.js 
f: 0
a: -1
```

**Comment by Anonymity20202** [comment]
I just tried with the latest version of emcc (3.1.18), and the result is indeed `0, -1`. This problem seems have been fixed already. Thanks

**Comment by sbc100** [comment]
Great!
