### ISSUE TITLE
glGetBufferSubData does not work

### ISSUE THREAD

**Issue by ssg3d** [emscripten-core/emscripten#17603]
I cant seem to get glGetBufferSubData to work. 
I am at tag 3.1.18.
I have the following flags while building:
```
-s USE_WEBGL2 ^
-s ALLOW_MEMORY_GROWTH=1 ^
```

And the code is:
```
#include <GLES2/gl2.h>
#include <webgl/webgl2.h>

GLuint buffer;
glGenBuffers(1, &buffer);
glBindBuffer(GL_ARRAY_BUFFER, buffer);
glBufferData(GL_ARRAY_BUFFER, <somesize>, <somedata>, GL_STATIC_DRAW);
float data[1000];
glGetBufferSubData(GL_ARRAY_BUFFER, 0, 1, data);
```
And the error I get in my browser (Firefox/Chrome/Edge) is:
```
Uncaught TypeError: GLctx.getBufferSubData is not a function
```

I have been trying to use this function for past one year hoping someday it will work but it does not still. What am I doing wrong? I do see there is a pull request "Implement glGetBufferSubData. #13776",  so it should be there, no?

**Comment by sbc100** [comment]
Does the test in `test/webgl2_get_buffer_sub_data.cpp` work for you?  (`./test/runner browser.test_webgl2_get_buffer_sub_data`)

**Comment by ssg3d** [comment]
Sorry but how do I run this test? OS shell (I am on win/ubuntu)? There seems to be no "runner" exe inside emsdk/test

**Comment by ssg3d** [comment]
If this helps, trying to use copyBufferSubData also gives me the same error "GLctx.copyBufferSubData is not a function"

**Comment by ssg3d** [comment]
Also, I cant find this js function when using the console either. Is it something to do with this function not packaged in the wasm/js thats built when we build an emscripten project?

**Comment by sbc100** [comment]
`./test/runner` lives inside the emscripten directory.  Yes you run it in your shell.  The emscripten directory is under `upstream` if you use `emsdk`.    See https://emscripten.org/docs/getting_started/test-suite.html#emscripten-test-suite for more on how to run the tests.

Assuming you are building without optimization on you should be able to see the glGetBufferSubData defined in JS.  Its part of the JS file that is generated by emscripten.      To see where its defined inside of emscripten itself you can take a look at  #13776

**Comment by juj** [comment]
`glGetBufferSubData` is a function only on WebGL 2 contexts. If the context version that got initialized is a WebGL 1 context, it will be expected that the application will crash on calling that function.

**Comment by ssg3d** [comment]
I got this on the command prompt. Browser says test passed:
```
D:\emsdk\upstream\emscripten\test>runner browser.test_webgl2_get_buffer_sub_data
posixtestsuite not found (run git submodule update --init?)
Test suites:
['test_browser']
Running test_browser: (1 tests)
(checking sanity from test runner)
shared:INFO: (Emscripten: Running sanity checks)
[Browser harness server on process 15172]
common:INFO: Using default system browser

Running the browser tests. Make sure the browser allows popups from localhost.

test_webgl2_get_buffer_sub_data (test_browser.browser) ... 127.0.0.1 - - [09/Aug/2022 16:09:55] code 404, message File not found
ok
[Browser harness server terminated]

----------------------------------------------------------------------
Ran 1 test in 1.973s

OK
```
So we conclude the test works?

**Comment by ssg3d** [comment]
> If the context version that got initialized is a WebGL 1 context, it will be expected that the application will crash on calling that function.

That was a huge help. My context was 1.0. I realize it is not sufficient specifying USE_WEBGL2, but we need to set EmscriptenWebGLContextAttributes::majorVersion to 2 as well. 

Now I am able to call glCopyBufferSubData and glGetBufferSubData. Ofcourse, getting them to work is ...sigh... another story.

**Comment by ssg3d** [comment]
Well, surprise - it all works. I got this warning on Firefox though:

> WebGL warning: getBufferSubData: Reading from a buffer with usage other than *_READ causes pipeline stalls. Copy through a STREAM_READ buffer.

Am not reopening this as I guess it may not be an issue on your side, but any chance you know how to get rid of this warning?

**Comment by sbc100** [comment]
I'm not sure myself, maybe open a new issue to track that.

**Comment by juj** [comment]
That message is a Firefox performance hint: it does not want users to call `getBufferSubData` on buffers that were not copied through an intermediate buffer that was created with STREAM_READ usage, as indeed otherwise it would cause a pipeline stall.
