### ISSUE TITLE
Compile with --closure fails with ERROR - [JSC_UNDEFINED_VARIABLE] variable i is undeclared

### ISSUE THREAD

**Issue by DrazenMatijacic** [emscripten-core/emscripten#17615]
Missing var declaration in file upstream/emscripten/src/embind/emval.js

Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
```
root@358fabc77907:/repo/sdk.update_emsdk# emcc -v
config:DEBUG: emscripten config is located in /emsdk/.emscripten
tools.filelock:DEBUG: Attempting to acquire lock 140504617977680 on /tmp/emscripten_temp/emscripten.lock
tools.filelock:DEBUG: Lock 140504617977680 acquired on /tmp/emscripten_temp/emscripten.lock
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.16 (6f1214164cb4b854755689060e91fd8167bc97a4)
clang version 15.0.0 (https://github.com/llvm/llvm-project ffa7384f10b89b6322c827d29d25108e34b8f6f0)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin
shared:DEBUG: executed /emsdk/upstream/bin/clang -v -target wasm32-unknown-emscripten
emcc:DEBUG: total time: 0.01 seconds
profiler:DEBUG: block "main" took 0.006 seconds
tools.filelock:DEBUG: Attempting to release lock 140504617977680 on /tmp/emscripten_temp/emscripten.lock
tools.filelock:DEBUG: Lock 140504617977680 released on /tmp/emscripten_temp/emscripten.lock

```
**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

        building:ERROR: /tmp/emscripten_temp/xxxx.js.pp.js.jso.js:7110:6: ERROR - [JSC_UNDEFINED_VARIABLE] variable i is undeclared
          7110|  for (i = 0; i < view.length; i++) a[i] = view[i];
                      ^
                      ^

        1 error(s), 0 warning(s)

        emcc: error: closure compiler failed (rc: 1): /emsdk/node/14.18.2_64bit/bin/node --max_old_space_size=8192 /emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT_2020 --language_out NO_TRANSPILE --emit_use_strict=false --externs /emsdk/upstream/emscripten/src/closure-externs/closure-externs.js --externs /emsdk/upstream/emscripten/src/closure-externs/node-externs.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/tls.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/string_decoder.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/https.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/assert.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/url.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/vm.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/domain.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/events.js --externs /emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/path.js --externs /emsdk/upstream/emscripten/third_party/closure-compile

        7109:  var a = new Array(view.length);
        7110:  for (i = 0; i < view.length; i++) a[i] = view[i];
        7111:  return Emval.toHandle(a);

Missing var in front of i in for loop in file:
[ upstream/emscripten/src/embind/emval.js](https://github.com/emscripten-core/emscripten/blob/1056be2ad4bc63a047b8dfc32396b0393fd70ef6/src/embind/emval.js)

```
135     var a = new Array(view.length);
136     for (var i = 0; i < view.length; i++) a[i] = view[i];
137     return Emval.toHandle(a);

**Comment by brendandahl** [comment]
I'm surprised testing didn't pick this up, but it looks like we don't run with only `--closure 1`. We usually do optimization with it (-02 or -O3) which seems to fix this issue.

**Comment by DrazenMatijacic** [comment]
Please check can you reproduce it with -Oz and --closure 1.
