### ISSUE TITLE
[WebGPU] segment fault when wgpuBuffer remap. 

### ISSUE THREAD

**Issue by hana-alice** [emscripten-core/emscripten#17624]
I'm trying to implement staging buffer by reuse wgpuBuffer, but I met segment fault when I tried to `getMappedRange` on wgpuBuffer after its `mapAsync`:
![image](https://user-images.githubusercontent.com/18626925/184072436-fcc8066b-052d-4fbc-a347-c1ae35b40c6f.png)

here's a piece of code that can reproduce:
```
void onMapDone(WGPUBufferMapAsyncStatus status, void *userdata) {
    if (status == WGPUBufferMapAsyncStatus_Success) {
        auto *semaphore = static_cast<Semaphore *>(userdata);
        semaphore->signal();
    }
}

WGPUBuffer stagingBuffer;

void updateBuffer(Buffer *buff, const void *data, uint32_t size) {
    size_t buffSize = 1024 * 2024 * 4;
    WGPUBufferDescriptor descriptor = {
        .nextInChain = nullptr,
        .label = nullptr,
        .usage = WGPUBufferUsage_MapWrite | WGPUBufferUsage_CopySrc,
        .size = buffSize,
        .mappedAtCreation = true,
    };
    static uint32_t count = 0;
    if (!count++) {
        stagingBuffer = wgpuDeviceCreateBuffer(CCWGPUDevice::getInstance()->gpuDeviceObject()->wgpuDevice, &descriptor);
    } else {
        Semaphore sem{0};
        wgpuBufferMapAsync(stagingBuffer, WGPUMapMode_Write, 0, buffSize, onMapDone, &sem);
        sem.wait();
    }
    auto *mappedBuffer = wgpuBufferGetMappedRange(stagingBuffer, 0, buffSize);
    memcpy(mappedBuffer, data, size);
    wgpuBufferUnmap(stagingBuffer);

    return;
}
```

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17 (fbc532773d84d2bd7da876275671970e792ad1cd)
clang version 15.0.0 (https://github.com/llvm/llvm-project 17e4c217b66305e60657a48f10fe3c428c2fe4d2)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\project\emsdk\upstream\bin

**Full link command and output with `-v` appended:**
`-v --bind --no-entry -O3 -s USE_ES6_IMPORT_META=0 -s EXPORT_ES6=1 -s MODULARIZE=1 -s EXPORT_NAME='wasmDevice' -s ENVIRONMENT=web -s WASM=1 -s USE_WEBGPU=1 -s NO_EXIT_RUNTIME=1 -s LLD_REPORT_UNDEFINED -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -s SAFE_HEAP -s WARN_UNALIGNED=1`

**Comment by juj** [comment]
The segfault probably occurs due to `mappedBuffer` being a null pointer, as a result of `wgpuBufferGetMappedRange()` failing. Try adding an `assert(mappedBuffer);` to verify.

Not sure why `wgpuBufferGetMappedRange()` fails there though.

On the async path, the function `wgpuBufferMapAsync` operates asynchronously. Asynchronous functions in a web browser can only complete after the main code has yielded back to the browser's main event loop. This means that the `onMapDone` completion callback will never fire while the main thread is "parked" to wait for it inside `sem.wait();`. I.e. `sem.wait()` will produce a deadlock.

**Comment by hana-alice** [comment]
> The segfault probably occurs due to `mappedBuffer` being a null pointer, as a result of `wgpuBufferGetMappedRange()` failing. Try adding an `assert(mappedBuffer);` to verify.
> 
> Not sure why `wgpuBufferGetMappedRange()` fails there though.
> 
> On the async path, the function `wgpuBufferMapAsync` operates asynchronously. Asynchronous functions in a web browser can only complete after the main code has yielded back to the browser's main event loop. This means that the `onMapDone` completion callback will never fire while the main thread is "parked" to wait for it inside `sem.wait();`. I.e. `sem.wait()` will produce a deadlock.

This helps a lot, thank you very much. Since it's not the correct way waiting in native, I'll have a try on async wait. Any issue met will be updated.
