### ISSUE TITLE
was change in structure padding intended?

### ISSUE THREAD

**Issue by mithrendal** [emscripten-core/emscripten#17640]
beginning with `emcc 3.1.16` we see structure padding was changed from 4 bytes alignment to 8 bytes alignment.

was this done by intention? Normally 8 bytes alignment is for 64bit, but emsdk is still 32 bit ... no? 
Can you tell us why the 4 bytes alignment was not sufficient anymore? Is emsdk maybe going 64 Bit soon ?

e.g. 

```
struct SnapshotHeader {    
    // Magic bytes ('V','A','S','N','A','P')
    char magic[6];
    
    // Version number (major.minor.subminor['b'beta])
    u8 major;
    u8 minor;
    u8 subminor;
    u8 beta;

    //<--- here after byte 10, up to 3.1.15 emcc inserted a padding of 2 Bytes
    // to get the following struct aligned to an address divisable by 4 

    //<--- here after byte 10, 3.1.16 emcc and later inserts a padding of 6 Bytes
    // to get the following struct aligned to an address divisable by 8

    // this is the following struct
    Thumbnail screenshot;
};
```

code extract from vAmigaWeb emulator see the https://vamigaweb.github.io/doc/about.html

**Comment by juj** [comment]
What is the type `Thumbnail`?

This reads like a bug if Thumbnail only needs to be aligned to 4, but now is getting aligned to 8 (independent of targeting Wasm as 64bit or 32bit)

**Comment by mithrendal** [comment]
```

struct Thumbnail {
    
    // Image size
    i32 width, height;
    
    // Raw texture data
    u32 screen[(HPIXELS / 2) * (VPIXELS / 1)];
    
    // Creation date and time
    time_t timestamp;
    
    // Takes a screenshot from a given Amiga
    void take(Amiga &amiga, isize dx = 2, isize dy = 1);
};

struct SnapshotHeader {
    
    // Magic bytes ('V','A','S','N','A','P')
    char magic[6];
    
    // Version number (major.minor.subminor['b'beta])
    u8 major;
    u8 minor;
    u8 subminor;
    u8 beta;
    
    // Preview image
    Thumbnail screenshot;
};
```

https://github.com/vAmigaWeb/vAmigaWeb/blob/fbd0907e01ce998972d4afff6469e703ccc319ef/Emulator/Media/Snapshot.h#L17

**Comment by juj** [comment]
Given the `time_t` in the struct, this might then be caused by #17401 . That change now necessitates that `Thumbnail` must be 8-byte aligned.

**Comment by mithrendal** [comment]
`time_t` is now 64 Bit. Ok that perfectly explains it.  Thank you very much for clarification. I close the issue then.
