### ISSUE TITLE
A possible bug when optimization is enabled

### ISSUE THREAD

**Issue by Anonymity20202** [emscripten-core/emscripten#17666]
The minimal code example:
```C
#include <stdio.h>
#include <stdint.h>

static uint64_t a = 0;
static int32_t b = 0;
static uint64_t  foo(void){
    for (b = (-19); (b >= (-19)); b += 8){
        const int32_t l_8 = (-1L);
        a += 1;
        if (l_8)
            continue;
    }
    return a;
}

int main (){
    uint64_t res = foo();
    printf("0x%llx\n", res);
}
```

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.14 (4343cbec72b7db283ea3bda1adc6cb1811ae9a73)
clang version 15.0.0 (https://github.com/llvm/llvm-project 7effcbda49ba32991b8955821b8fdbd4f8f303e2)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Compilation option:**
`emcc -O0 -g -w ` and `emcc -O3 -g -w `

**Bug Description:**
When compiled with `-O0` option, the generated wasm program prints:
```
0x10000003
```
But when compiled with `-O3` option, then wasm code throw an error: 
```
RuntimeError: unreachable
```
Not sure if this is a bug, could you take a look please?

**Comment by tlively** [comment]
Your loop counter `b` will overflow and since it is signed, that is undefined behavior. It's possible that the compiler is detecting that unconditional undefined behavior and compiling it away to a trap. If you make `b` unsigned, does that fix the problem?

**Comment by Anonymity20202** [comment]
Thanks! Making `b` unsigned fixes this problem. It seems that an overflow indeed causes the problem. I will close this issue.
