### ISSUE TITLE
___syscall_newfstatat: Aborted(Assertion failed: 2048)

### ISSUE THREAD

**Issue by luoxuhai** [emscripten-core/emscripten#17660]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
 `emcc -v`
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.15 (8b4443a87f5eab5dbb9adb690f9ebed0a9da4bd9)
clang version 15.0.0 (https://github.com/llvm/llvm-project 27abff670bc7ad9702c4f9fc8b82aae6b530bf0f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/emsdk/upstream/bin
```

**Failing command line in full:**
<img width="937" alt="image" src="https://user-images.githubusercontent.com/37284154/185006508-35ea251a-883b-48c0-86a3-d3e39a876319.png">

```
flags = 2048
```
**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

**Comment by sbc100** [comment]
What command did you use the link you application?

I don't see any flags that could be passed to that system call that are 0x2048.  See https://github.com/emscripten-core/emscripten/blob/11053684521f6830fa4aa36bc79e0266cce0228d/system/lib/libc/musl/include/fcntl.h#L65-L67

Can you see where that call is coming from?  Maybe build with `--profiling-funcs` and attach a backtrace?

**Comment by ravisumit33** [comment]
@sbc100 I am getting the same error and the flag used is below:
https://github.com/emscripten-core/emscripten/blob/11053684521f6830fa4aa36bc79e0266cce0228d/system/lib/libc/musl/include/fcntl.h#L111

Actually its 0x800 and in decimal it turns out to be 2048.
