### ISSUE TITLE
How to make sure downloaded wasm libray not be de-compiled?

### ISSUE THREAD

**Issue by foreverlms** [emscripten-core/emscripten#17696]
For security reason, how to keep wasm library safe for source code?

**Comment by sbc100** [comment]
wasm binaries are not too different binaries for other ISAs such as x86 or arm binaries in that limited decompilation will always be possible.  However its hard to get something that is close to the fidelity of the original source code (when compiling with optimizations enabled).   

Obfuscation techniques can be used (just as the can with other ISAs) but, in practice, there are limits to what they can do and normally just mean slowing down somebody who wants to understand/decompile you binaryen.

**Comment by foreverlms** [comment]
thanks, I got it. Sorry to reply to you so lately. Have a good day...
