### ISSUE TITLE
how to stub  wasi_snapshot_preview1 fd_close

### ISSUE THREAD

**Issue by weiqingtangx** [emscripten-core/emscripten#17705]
Hi guys，
I use emscripten to build standalone wasm file,  then I convert to wat file, wat file includes
```
(import "wasi_snapshot_preview1" "fd_close" (func $__wasi_fd_close (type $t0)))
```

according to this link [17331](https://github.com/emscripten-core/emscripten/issues/17331), I stubed the ```fd_close``` function in main.cpp as below:
```
int __wasi_fd_close(int) {
  __builtin_trap();
}
```

and set the cmake linker flag like this
```
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--trace-symbol=__wasi_fd_close")
```

then use emcmake to build, however the ```fd_close``` line  could not be removed. Are there any details I missed? Thanks.

**Comment by sbc100** [comment]
What output does this linker show from the `--trace-symbol`?   Does it show the definition?

Are you compiling as C++?  Did you remember to wrap the definition of __wasi_fd_close in extern "C"?

**Comment by weiqingtangx** [comment]
@sbc100 Thank you for reply.
the ```--trace-symbol``` shows
```
[100%] Linking CXX executable f2.js
/Users/weiqing.twq/Documents/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(__map_file.o): reference to __wasi_fd_close
/Users/weiqing.twq/Documents/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(__stdio_close.o): reference to __wasi_fd_close
/Users/weiqing.twq/Documents/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(fopen.o): reference to __wasi_fd_close
[100%] Built target f2
```

Yes, I compiled with C++ and CMake. If I wrap ```extern "C" ```
```
extern "C" int __wasi_fd_close(int) {
  __builtin_trap();
}
```

there is an error output
```
/Users/weiqing.twq/Documents/F2Native/core/wasi/Wasi.cpp:6:16: error: functions that differ only in their return type cannot be overloaded
extern "C" int __wasi_fd_close(int) {
```

**Comment by sbc100** [comment]
it looks like `__wasi_fd_close` returns `__wasi_errno_t` and not `int`

**Comment by weiqingtangx** [comment]
Yes, I figure out the right way, ```__wasi_fd_close``` function should  have the right argument and return type, as below 
```
__wasi_errno_t __wasi_fd_close(__wasi_fd_t) {
  __builtin_trap();
}
```
Then it will be removed from the wat file. I will close this issue. Thank you. @sbc100
