### ISSUE TITLE
Compile error when upgrading to 3.1.19

### ISSUE THREAD

**Issue by nathan-stouffer-onx** [emscripten-core/emscripten#17700]
We are using emscripten to build google's protobuf library. When we upgraded our emsdk from version 3.1.18 to 3.1.19, we now get the following compile error that we didn't get before.

```
/usr/local/var/vcpkg/buildtrees/protobuf/src/23fa7edd52-3ba2225d30.clean/src/google/protobuf/wire_format_lite.cc:102:9:
error: integer value -1 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
    static_cast<WireFormatLite::WireType>(-1),  // invalid         
1 error generated.
```

Here is the link to the offending line of source code and it's definition: https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wire_format_lite.cc#L104
https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wire_format_lite.h#L104

My first thought is that something with `SWIG` changed and the `WireType` enum is no longer defined as an int, but an unsigned int. But I don't really know what `SWIG` is or why it is there.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.19 (a5f7b1c9a1c74a830bebedc122d204800ce8dff9)
clang version 16.0.0 (https://github.com/llvm/llvm-project 30171e76f0e5ea8037bc4d1450dd3e12af4d9938)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/var/emsdk/upstream/bin
```

**Comment by tlively** [comment]
A more likely explanation is that Emscripten pulled in a new upstream version of clang that introduced this error. (Emscripten continuously pulls in upstream clang, so it unexpectedly gets new errors like this occasionally.) The simplest workaround is probably to turn off the error with `-Wno-enum-constexpr-conversion` until this is fixed upstream in the protobuf library.

**Comment by sbc100** [comment]
Can I ask where you seeing references to SWIG?  I don't see any in your error message.  As far as I know nobody has made a version of SWIG that generates JS bindings using emscripten, but I would curious to know if they had.

**Comment by nathan-stouffer-onx** [comment]
The `SWIG` is part of the preprocessor macro for defining the `WireType` enum. If `SWIG` is not defined then the enum uses int

https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wire_format_lite.h#L104

**Comment by sbc100** [comment]
yes, I think this @tlively is correct, you just need to add `-Wno-enum-constexpr-conversion`.. at least until protobuf project fixes the warning.
