### ISSUE TITLE
SDL_GetScancodeFromKey not defined

### ISSUE THREAD

**Issue by hsdk123** [emscripten-core/emscripten#17711]
Hi, it looks like `SDL_GetScancodeFromKey` isn't defined in `library_sdl.js` - would it be possible to add this?

**Comment by sbc100** [comment]
Sounds reasonable.  Would you be interesting in uploading a patch?   Alternatively you might want to try `-sUSE_SDL=2` which is the more up-to-date port of SDL2 to WebAssembly.

**Comment by hsdk123** [comment]
I'm sadly not too familiar with javascript so I wouldn't be too comfortable. But it shouldn't be anything other than just a hash map lookup so should be straightforward for those who know js.

**Comment by mooosh-milllie** [comment]
Is this issue still open, and can you explain on how to tackle it?

**Comment by kripken** [comment]
@mooosh-milllie 

The relevant file is [library_sdl](https://github.com/emscripten-core/emscripten/blob/main/src/library_sdl.js).

To fix this, we need to add a new method, `SDL_GetScancodeFromKey`. That is declared in `system/include/SDL/SDL_keyboard.h` and the implementation should go in that JS file. Implementing a function there looks like this:

https://github.com/emscripten-core/emscripten/blob/7228844e2ce00e1da25c423d6dc272a5f5d225d5/src/library_sdl.js#L3711-L3713

And if you search for `scanCodes` in that file you can find the information that the function implementation needs.

**Comment by mooosh-milllie** [comment]
@kripken thanks for the guide, I will get to work on that.

**Comment by mooosh-milllie** [comment]
@kripken  @sbc100 This is my result, I have been doing javascript for a while now, but this codebase is totally new, because I am unable to access the scanCodes object, my implementation is because of how I saw scanCodes was handled in the file. if this is the right way to make it accessible I want to know if it needs a key or the whole object should be returned
`SDL_GetScancodeFromKey: function (key) {
    return SDL.scanCodes[key];
  },`

**Comment by sbc100** [comment]
> @kripken @sbc100 This is my result, I have been doing javascript for a while now, but this codebase is totally new, because I am unable to access the scanCodes object, my implementation is because of how I saw scanCodes was handled in the file. if this is the right way to make it accessible I want to know if it needs a key or the whole object should be returned `SDL_GetScancodeFromKey: function (key) { return SDL.scanCodes[key]; },`

The syntax looks correct.  I'm afraid I don't know enough about the SDL implementation to know if that the semantics are correct.

One thing to do would be add a test to show if it is working or not.  See `test_sdl_endianness` in test_other.py for an example of test that you could copy.

**Comment by mooosh-milllie** [comment]
`def test_sdl_endianness(self):
    create_file('main.cpp', r'''
      #include <stdio.h>
      #include <SDL/SDL_keyboard.h>

      int main() {
        printf("%d", SDL_GetScancodeFromKey(8));
        return 0;
      }
    ''')
    self.run_process([EMXX, 'main.cpp'])
    self.assertContained('42')`
The above is the the possible test that I have written as python is just a past time, the test should print 42 when the key 8 is passed. I don't know how to run test a little guidance is needed. 
@kripken @sbc100

**Comment by sbc100** [comment]
The docs for running the test are at: https://emscripten.org/docs/getting_started/test-suite.html

(Not to be snaky but googling for "running emscripten test suite" gives this page as the first result).

**Comment by mooosh-milllie** [comment]
I resolved the comments you left, removed the extra line and changed the test assertion, I hope everything is okay now? @sbc100
