### ISSUE TITLE
FSNode Memory Leak

### ISSUE THREAD

**Issue by ryan-weisenberger** [emscripten-core/emscripten#17739]
### Discussed in https://github.com/emscripten-core/emscripten/discussions/17699

<sup>Originally posted by **ryan-weisenberger** August 22, 2022</sup>

```
% ./emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.19 (a5f7b1c9a1c74a830bebedc122d204800ce8dff9)
clang version 16.0.0 (https://github.com/llvm/llvm-project 30171e76f0e5ea8037bc4d1450dd3e12af4d9938)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/misha/wahoo/systm/crux_tools/submodules/emsdk/upstream/bin
```

We have a memory leak when calling our WASM through javascript generated by emscripten 3.1.19.

Our WASM converts a CSV file to a binary file in memory. Every time the converter finishes, it leaves behind a `FSNode` object. So after several hundred conversions, we get several hundred of these FSNode objects clogging up memory.

I'm using Node's `v8.getHeapSnapshot()` to take a heap snap before the conversions, after the conversions, and again after I have forced run the GC. I'm attaching those snapshots here.

The number of FSNode objects left over exactly matches the number of conversions. In this case, 978.

We've gone over the WASM code quite extensively, and cannot find a memory leak.

Any ideas what could cause this, and how to resolve it? If this looks like an emscripten problem, I can move this to Issues.

![Chrome Memory Dev Tool](https://user-images.githubusercontent.com/74564699/185997527-9358c8b1-f9d4-42d0-9a10-8c622a1d372c.png)

[heapSnapshots.zip](https://github.com/emscripten-core/emscripten/files/9396864/heapSnapshots.zip)

Thanks,
Ryan

**Comment by michaelfominwahoo** [comment]
@ryan-weisenberger see https://github.com/emscripten-core/emscripten/issues/17940

It's possible your virtual file system is simply getting filled up with 1000s of files.  You should try deleting the files after you have finished with them and you should see your FSNode count decrement

**Comment by ryan-weisenberger** [comment]
Yes, this was caused by creating files in the virtual file system and then not deleting those files. It is not an emscripten issue.
