### ISSUE TITLE
access to xml http request from origin blocked by CORS . 

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [emscripten-core/emscripten#17744]
Please include the following in your bug report:

**emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.20 (5d878c99921ec247d34fb26a20b5a13d60d69e93)
clang version 16.0.0 (https://github.com/llvm/llvm-project 75767a0f9a926641edbef08e31ec2148ff45da67)
running on macos (apple silicon m1 mac montery)

Access to XMLHttpRequest at 'file:/full_path_to_program_location/hello.wasm' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.

**Comment by kripken** [comment]
`file://` URLS are fairly limited. It's better to test locally with a full webserver. You can use `emrun hello.html` or set up the server yourself (see also [this FAQ entry](https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing)).

**Comment by bloodgroup-cplusplus** [comment]
works using emrun . Thanks kripken
