### ISSUE TITLE
[Bug] Swapped loop and conditional in file_packager.py?

### ISSUE THREAD

**Issue by jaraujo98** [emscripten-core/emscripten#17753]
The symlinks I was specifying with the `src@dst` syntax of the `file_packager.py` utility kept getting overwritten at seemingly random times. After digging a little bit, I came across this. Aren't these two lines swapped?

https://github.com/emscripten-core/emscripten/blob/88e06222680d96f158d00d781d353b2c893dbe64/tools/file_packager.py#L477-L478

`file_` happens to be defined because it is used as loop variable in a `for` loop shortly before. Basically what this does is that, if the last file that happened to be preloaded does not have an explicit destination, then the destination for every preloaded file gets overwritten.

**Comment by kripken** [comment]
Good catch! That does look like a bug. Would you like to open a PR with it? (for a small change like this, a simple way would be to open that file on the `main` branch and press the "edit" button, I think)

**Comment by jaraujo98** [comment]
Just opened it. Hopefully I did not mess up the indentation on GitHub's web editor :-)
