### ISSUE TITLE
Problems with uploading mat4 uniforms to the vertex shader

### ISSUE THREAD

**Issue by techie-guy** [emscripten-core/emscripten#17750]
Hello, 

I'm having problems in rendering a cube using emscripten

I have a VAO, a VBO, and an EBO and I am trying to draw it using glDrawElements
It works fine in native opengl and the cube is rendered

### Buffer Initialization
```
 glGenVertexArrays(1, &VAO);
 glBindVertexArray(VAO);

 glGenBuffers(1, &VBO);
 glBindBuffer(GL_ARRAY_BUFFER, VBO);
 glBufferData(GL_ARRAY_BUFFER, sizeof(Utils::Vertex) * vertices.size(), vertices.data(), GL_STATIC_DRAW);

 glGenBuffers(1, &EBO);
 glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, EBO);
 glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(GLushort) * indices.size(), indices.data(), GL_STATIC_DRAW);

 glVertexAttribPointer(shaderProgram.getAttributeLocation("aPos"), 4, GL_FLOAT, GL_FALSE, sizeof(Utils::Vertex), (void*)offsetof(Utils::Vertex, position));
 glVertexAttribPointer(shaderProgram.getAttributeLocation("aColor"), 4, GL_FLOAT, GL_FALSE, sizeof(Utils::Vertex), (void*)offsetof(Utils::Vertex, color));

 glEnableVertexAttribArray(shaderProgram.getAttributeLocation("aPos"));
 glEnableVertexAttribArray(shaderProgram.getAttributeLocation("aColor"));

 glBindBuffer(GL_ARRAY_BUFFER, 0);
 glBindVertexArray(0);
 glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
```
### The Rendering Part
```
shaderProgram.bind();
shaderProgram.uploadMat4("projection", projection);
shaderProgram.uploadMat4("view", view);
shaderProgram.uploadMat4("transform", transform);
glBindVertexArray(VAO);
glDrawElements(GL_TRIANGLES, indices.size(), GL_UNSIGNED_SHORT, 0);
```
### Vertex Shader
```
#version 300 es

in vec4 aPos;
in vec4 aColor;

out vec4 fColor;

uniform mat4 transform;
uniform mat4 projection;
uniform mat4 view;

void main()
{
    fColor = aColor;
    gl_Position = transform * view * projection * aPos;
}
```
### Fragment Shader
```
#version 300 es

out mediump vec4 FragColor;
in mediump vec4 fColor;

void main()
{
    FragColor = fColor;
} 
```

### **Build Options**
 ```
-sUSE_GLFW=3 -sLLD_REPORT_UNDEFINED -sWASM=1 -fwasm-exceptions -sEXCEPTION_DEBUG=1 --profiling-funcs --preload-file ./Assets --shell-file ./Assets/index.html -lglfw -lGL
```

~~### Please Can Anyone Tell Me Where The Problem Is?~~

### **Update**
 I found the issue, it is in uploading the mat4 uniforms to the vertex shader
I do it as the following
```
glUniformMatrix4fv(varLocation, 1, GL_FALSE, glm::value_ptr(mat4));
```
It works when I hard code the matrix values in the vertex shader, but does not work when uploading the matrices as uniforms using ```glUniformMatrix4fv```

### **I found the problem, but I don't know how to fix it?**

**Comment by octy-sonity** [comment]
So how are you supposed to work around this?

**Comment by octy-sonity** [comment]
If someone stumbles on this old thread: In my case _glUseProgram_() hasn't been called to set the correct shader program. One would expect this to throw a runtime error, alas in the browser I tested with (Chrome on OSX) you don't get any errors. Rather the shader seems to interpret a missing uniform as null values and the screen remains blank.

After making sure to always properly call _glUseProgram_() getting the Matrix location and calling _glUniformMatrix4fv_() works just fine and as expected.
