### ISSUE TITLE
Is OffscreenCanvas rendering supported in WebGPU context?

### ISSUE THREAD

**Issue by lisanlow** [emscripten-core/emscripten#17776]
I see that webgpu **OffscreenCanvas** rendering is already available in chromium with this bug fix:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1169710
- https://github.com/gpuweb/cts/blob/main/src/webgpu/web_platform/canvas/context_creation.spec.ts

Looking at current implementation of wgpuInstanceCreateSurface(), it appears to me that rendering to OffscreenCanvas is currently not available in native webgpu API.
This code section shows that wgpuInstanceCreateSurface() asserts expect webgpu surface to be associated only to HTML canvas element?
https://github.com/emscripten-core/emscripten/blob/main/src/library_webgpu.js#L2410
![WebGPUOffscreenNotSupported](https://user-images.githubusercontent.com/11375089/187867896-52523512-cd2f-4a19-b218-c5007ca7f2d6.PNG)
Is my understanding correct?
If so, is there any known alternatives to render to canvas on webworker then transfer rendered output to main thread for chrome browser display?

In my prototype code, I am trying to configure OffscreenCanvas in the HTML and referencing this canvas in wgpuInstanceCreateSurface() call to be used for subsequent rendering.
It appears mandatory to define WGPUSurfaceDescriptorFromCanvasHTMLSelector when creating webgpu surface.
https://github.com/emscripten-core/emscripten/blob/main/src/library_webgpu.js#L2399
![OffscreenHTML](https://user-images.githubusercontent.com/11375089/187872166-8dab6be7-7de2-44d6-83be-a91c70d6b1c8.PNG)

**Comment by sbc100** [comment]
@kainino0x

**Comment by lisanlow** [comment]
@sbc100 and @kainino0x FYI, I managed to overcome this issue in my prototype by setting `specialHTMLTargets["!canvas"] = Module.canvas;` and referencing it in the HTML selector with `"!canvas"` in the worker thread.

**Comment by kainino0x** [comment]
Sorry, I forgot to reply to this. We haven't put any work specifically into getting OffscreenCanvas to work. I never tried it but thought it would work with `WGPUSurfaceDescriptorFromCanvasHTMLSelector` which calls findCanvasEventTarget which has special logic for OffscreenCanvases:
https://github.com/emscripten-core/emscripten/blob/44fd8b15cf1f69210bac2ce1dce09b10064a64a2/src/library_html5.js#L333

However it looks like this is only for transferControlToOffscreen and not for raw OffscreenCanvases.

Thanks for reporting your workaround!

**Comment by lisanlow** [comment]
@kainino0x Thanks for your attention on this issue.

I just realized that the approach that I described above with **specialHTMLTargets** is mentioned in [emscripten documentation](https://emscripten.org/docs/api_reference/html5.h.html) for WebGL.

It's great that this works seamlessly for WebGPU too :)

**Comment by lisanlow** [comment]
@kainino0x This ASSERT line in failing for me when working with offscreen canvas in debug build.
https://github.com/emscripten-core/emscripten/blob/main/src/library_webgpu.js#L2412

Any chance that its possible to update this line to broaden the check to include offscreen canvas type?

**Comment by lisanlow** [comment]
> @lisanlow Of course! Thanks for finding that bug. #17889

@kainino0x Thanks for the prompt fix!  Really appreciate it.

**Comment by alienself** [comment]
I am facing a similar issue: https://github.com/emscripten-core/emscripten/discussions/19225

I would like to run webgpu off the main thread in a separate thread while rendering on an offscreen canvas passed from the main thread. Is this possible with emscripten? I am using proxy to pthread but i am unable to retrieve the canvas context.
