### ISSUE TITLE
 conflicting types for 'pthread_setcancelstate'

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#17799]
After updating to latest emscripten, I have this compilation error:

```
cache:INFO: generating system library: sysroot/lib/wasm32-emscripten/libc-optz.a... (this will be cached in "/home/caiiiycuk/sdk/emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/libc-optz.a" for subsequent builds)

/home/caiiiycuk/sdk/emsdk/emscripten/main/system/lib/pthread/library_pthread_stub.c:284:5: error: conflicting types for 'pthread_setcancelstate'
int pthread_setcancelstate() {
    ^
/home/caiiiycuk/sdk/emsdk/emscripten/main/system/lib/libc/musl/src/include/../../include/pthread.h:95:5: note: previous declaration is here
int pthread_setcancelstate(int, int *);
    ^
/home/caiiiycuk/sdk/emsdk/emscripten/main/system/lib/pthread/library_pthread_stub.c:288:5: error: conflicting types for 'pthread_setcanceltype'
int pthread_setcanceltype() {
    ^
/home/caiiiycuk/sdk/emsdk/emscripten/main/system/lib/libc/musl/src/include/../../include/pthread.h:96:5: note: previous declaration is here
int pthread_setcanceltype(int, int *);
    ^
2 errors generated.

```

I think it is related to #5048

**Comment by sbc100** [comment]
I'm not sure why this would be happening for you but other folks.   Are you using emscripten from git or from emsdk?   Can you include the full failing command line?  I think it should be reported when any build command fails.

**Comment by sbc100** [comment]
When I run `$ ./embuilder build libc_optz --force` I don't see any such error.  Can you run that commend?

**Comment by sbc100** [comment]
Also,  library_pthread_stub.c is no longer part of libc_optz as of #17179, so I suspect some kind of version mismatch is happening here.

Also, the current version of emscripten has the correct signature for this function: https://github.com/emscripten-core/emscripten/blob/7cf27ff075be9a97efbc5891b9ceb99fda71c741/system/lib/pthread/library_pthread_stub.c#L288-L290

**Comment by caiiiycuk** [comment]
> I'm not sure why this would be happening for you but other folks. Are you using emscripten from git or from emsdk? Can you include the full failing command line? I think it should be reported when any build command fails.

Ohh, sorry for this. I hastened to create a bug, i thought that I will add additional info into comments, but got distracted. My fault. I will check your suggestions and provide detailed info asap.

**Comment by caiiiycuk** [comment]
Probably I missconfigure my environment. The problem was in cmake files or project, seems that build script was generated when emscripten was located in emsdk/emscripten/main/. Seems newer emsdk uses emsdk/upstream/emscripten. After regenerating cmake build script everything is fine. Thank you for quick response.
