### ISSUE TITLE
`node_shell_read`:  `read_()` should be tolerant of File URLs

### ISSUE THREAD

**Issue by LoneRifle** [emscripten-core/emscripten#17797]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
2.0.26+

**Failing command line in full:**
N/A; runtime issue

**Full link command and output with `-v` appended:**
Not known; reporter is dependent on library built with Emscripten, issue investigated through debugging on Chrome Dev Tools

**Caveat:**
Issue concerns ESM modules in Node.js, unsupported until #11792 resolved

**Description:**
When the flag `EXPORT_ES6` is active, in `preamble`, `wasmBinaryFile` would be set to a URL string, which could potentially be a file URL:
https://github.com/emscripten-core/emscripten/blob/88e06222680d96f158d00d781d353b2c893dbe64/src/preamble.js#L649-L654

If the environment is Node, the module eventually calls `read_()` in `node_shell_read`, which would treat the given argument as a regular file path, resulting in the file being not found:
https://github.com/emscripten-core/emscripten/blob/a741b999ab528861d11254b9ca26588391587793/src/node_shell_read.js#L20-L30

I propose that if the given argument is a file URL, `read_()` could translate it to a regular path accepted by `fs.readFileSync()`, and continue as before. `locateFile` could be provided to the Emscripten module to provide the correct path to the binary as a routine [workaround](https://github.com/emscripten-core/emscripten/issues/11792#issuecomment-1024077848), but as a consumer of a library built using Emscripten I may not be so famiiliar with the latter, and would want the library to work out of the box.

**Comment by LoneRifle** [comment]
> I think PR #17915 would fix this.

Cool =) Could I trouble you to add an additional line in the opening post in your PR that indicates that the PR `Resolves: #17797`? Thanks again!

**Comment by kleisauke** [comment]
Sure, I just added that line.
