### ISSUE TITLE
Linker fails to resolve calloc symbol under specific circumstances.

### ISSUE THREAD

**Issue by floooh** [emscripten-core/emscripten#17808]
version: emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.20 (5d878c99921ec247d34fb26a20b5a13d60d69e93)

(but it goes back to at least 3.0.0, couldn't test older versions)

Under specific circumstances, emscripten fails to link simple programs which are calling malloc+memset because of a missing calloc symbol.

These circumstances are:

1. malloc+memset being 'optimized' to a call to calloc via -O1 or better
2. ...where malloc is called through a function pointer
3. ...and emmalloc is used instead of the vanilla allocator
4. ...and -flto must be enabled

A minimal reproducer is here:

https://github.com/floooh/emsc-calloc-emmalloc-repro

(originally the problem is triggered by the spine-c runtime: https://github.com/EsotericSoftware/spine-runtimes/tree/4.1/spine-c/spine-c, Spine is a fairly popular 2D animation tool)

For more background information see this emscripten-discuss thread:

https://groups.google.com/g/emscripten-discuss/c/11fw5kJuq-4

(cc: @sbc100)

**Comment by curiousdannii** [comment]
Could this be related to #15676?

**Comment by floooh** [comment]
Just want to cofirm that the PR fixes the original issue when building the spine-c runtime.
