### ISSUE TITLE
"ReferenceError: ccall is not defined" error happens on startup

### ISSUE THREAD

**Issue by Wohlstand** [emscripten-core/emscripten#17831]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
SDK version 3.1.21

**Failing command line in full:**
Failure happens in runtime, build is fully valid:
- The build of the game that fails: https://wohlsoft.ru/projects/TheXTech/smbx-on-web/
- The build log where I installed the latest SDK and all dependent components: https://github.com/Wohlstand/TheXTech/runs/8294744041

**Full link command and output with `-v` appended:**

**Notes**
In past versions, the same build worked fine. However, in recent times, I found that game fails to start because of the missing "ccall" exception.

The source code that uses ccall: https://github.com/Wohlstand/TheXTech/blob/master/lib/AppPath/private/app_path_emscripten.cpp

I use it to change the state of the variable and synchronize the work (I implemented the mutex that gets unlocked by the JavaScript side to continue C code)

**Comment by Wohlstand** [comment]
Okay, seems I shall add the `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=ccall` link flag, however, I was totally unnoticed by this change. Just now I figured out the change at the log: https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3121---09092022

**Comment by Wohlstand** [comment]
EDIT: No, I should specify the `-s EXPORTED_RUNTIME_METHODS=ccall` and mention the `ccall()` method as `Module.ccall()` rather as global function.

**Comment by sbc100** [comment]
You can also do `-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$ccall` (note the extra dollar sign).. and avoid calling it via the `Module` object.
