### ISSUE TITLE
Linking to ApplicationServices framework while compiling with emcc gives error

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [emscripten-core/emscripten#17830]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.21 (f9e81472f1ce541eddece1d27c3632e148e9031a)

**Failing command line in full:**

>> emcc progname.cpp -framework ApplicationServices  (this is the command that was given)
>> emcc: error: ApplicationServices: No such file or directory ("ApplicationServices" was expected to be an input file, based on the commandline arguments provided) (error message received)

machine: macos monterey(12.5)
looks like ApplicationServices is a cocoa framework

**Comment by sbc100** [comment]
You can't link in any `-frameworks` when using emcc since its cross copiler.  

`-framework` is a flag that is specific to the macOS native compiler.
