### ISSUE TITLE
Discussion for MINIMAL_RUNTIME + MODULARIZE preventing symbols export

### ISSUE THREAD

**Issue by DavidPeicho** [emscripten-core/emscripten#17852]
**Version of emscripten/emsdk:**

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.7 (48a16209b1a0de5efd8112ce6430415730008d18)
clang version 15.0.0 (https://github.com/llvm/llvm-project fbce4a78035c32792b0a13cf1f169048b822c06b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/me/Tools/emsdk/upstream/bin
```

I wanted to open a discussion on the use of `MINIMAL_RUNTIME` with `MODULARIZE`. Basically, generating an output only with `MODULARIZE` leads to:

```js
var asm = createWasm();
...
var _my_export = Module["_my_export"] = createExportWrapper("my_export");
```

So far so good, `_my_export` can thus be used when the promise resolve. However, building with `-sMINIMAL_RUNTIME=1 -sMODULARIZE=1` leads to:

```js
var asm = createWasm();
...
WebAssembly.instantiate(Module["wasm"], imports).then(function(output) {
    _my_export = asm["my_export"];
}
```

Which is not exported and not available after loading the module.

It looks like the "issue" comes from here: https://github.com/emscripten-core/emscripten/blob/main/emscripten.py#L729

I am wondering if this is really the expected behavior of `MINIMAL_RUNTIME`? I don't see a use case where someone doesn't want to access its `EMSCRIPTEN_KEEPALIVE` marked symbols.

Are we expected to mark every single symbol we want to export?

I have some time to spend on that to help, if there is a modification to do we can agree on, that would be awesome :)

Thanks a lot!

**Comment by DavidPeicho** [comment]
To add to this issue: `HEAP8`, `HEAP16` will have the exact same issues

**Comment by kripken** [comment]
I think the original use case for minimal runtime was an application with a `main()`, and not something more like a library with multiple exports. So exports might not be supported yet, but would definitely be worth adding, with the right design (that avoids any extra code size in the general case).

Is that right @juj ?

**Comment by DavidPeicho** [comment]
So right now, for standalone there is a lot of unneeded code because exports are still saved in local variables:

```js
WebAssembly.instantiate(Module["wasm"], imports).then(function(output) {
    var asm = output.instance.exports;
     _my_export = asm["my_export"];
     ...
}
```

Locally, I did the same thing as `make_export_wrappers`:

```js
WebAssembly.instantiate(Module["wasm"], imports).then(function(output) {
    var asm = output.instance.exports;
     _my_export = Module["_my_export"] = asm["my_export"];
     ...
}
```

For libraries that's perfect, for standalone indeed it adds a few bytes per export. We could add an extra flag for building libraries, but I am afraid it starts to get really complex, there are already many code paths.

**Comment by DavidPeicho** [comment]
Closing in favor of #17911
