### ISSUE TITLE
print error when use format %d for type "unsigned long int"

### ISSUE THREAD

**Issue by zyz9740** [emscripten-core/emscripten#17865]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.16 (6f1214164cb4b854755689060e91fd8167bc97a4)
clang version 15.0.0 (https://github.com/llvm/llvm-project ffa7384f10b89b6322c827d29d25108e34b8f6f0)
Target: wasm32-unknown-emscripten
```

**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

random.c

```
#include <stdio.h>
#include <stdint.h>

void func (uint64_t val, char* vname) {
    // Print 0
    printf("val %s :%d\n", vname, val);
    // Print 0
    printf("val %s :%lu\n", vname, val);
    // This will print 120
    printf("val :%d\n", val);
    // This will print 120
    printf("val %s :%lld\n", vname, val);
}

int main() { func(120, "j"); }
```

reproduce.sh

```
gcc -O3 -w random.c -o random.o
./random.o
echo ================================
emcc -w -sENVIRONMENT=shell -O3 -o random_em.js random.c
v8 random_em.js
```

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

I got this output

```
val j :120
val j :120
val :120
val j :120
================================
val j :0
val j :0
val :120
val j :120
```

It's so weird to me...

**Comment by sbc100** [comment]
In general with printf you need to use the correct format specifiers, otherwise strange/bad things like this can happen.   %d is for printing `int` and `%lu` is for printing unsigned longs.  

When you compile that code emcc warns you about the issue:

```
$ emcc test.c 
test.c:6:35: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
    printf("val %s :%d\n", vname, val);
                    ~~            ^~~
                    %llu
test.c:8:36: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
    printf("val %s :%lu\n", vname, val);
                    ~~~            ^~~
                    %llu
test.c:10:25: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
    printf("val :%d\n", val);
                 ~~     ^~~
                 %llu
3 warnings generated.

```

**Comment by zyz9740** [comment]
What confuse me are as below:
1. the behavior of "printf" in gcc and emscripten is different. I'm not sure whether misunderstanding will happen when developers transform a C program to wasm
2. this phenomenon only happens when variable "vname" is followed by variable "val". If you remove the  ahead "vname", it print the right value 120 instead of 0

However, just as you said, we must use the correct format specifier in printf. If this issue is not interesting, you can close this issue.

**Comment by sbc100** [comment]
I think that the issue comes from the fact that x86_64 and wasm have different ABIs for handling var_args.   When you use the wrong format specifiers for things in printf I think you can expect odd, and platform-dependent, failures like this.

I think we can close this.. we can re-open if we think there is a bug worth fixing there, but as it stands I don't think there is.
