### ISSUE TITLE
ERROR_ON_UNDEFINED_SYMBOLS should ignore symbols with import names

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#17913]
I compiled the following program that uses a WASI import as a source of randomness:

```c
#include <assert.h>
#include <fcntl.h>
#include <unistd.h>

__attribute__((import_module("wasi_snapshot_preview1"),
               import_name("random_get")))
int random_get(uint8_t* buffer, uint32_t length);

int getentropy(void* buffer, size_t length) {
  return random_get(buffer, length);
}

int main() {
  int fd = open("/dev/urandom", O_RDONLY);
  assert(fd != -1);

  uint8_t buffer[1024] = {};
  int nread = read(fd, buffer, 1024);
  assert(nread == 1024);

  return *(unsigned int*)buffer % 126;
}
```

Compiling with `./emcc test.c -o test.wasm -sWASMFS -sSTANDALONE_WASM` gives this error:

```
error: undefined symbol: random_get (referenced by top-level compiled C/C++ code)
warning: Link with `-sLLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _random_get may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

I had to compile with `-sERROR_ON_UNDEFINED_SYMBOLS=0` to resolve the error, but I would have preferred that Emscripten see that I had explicitly configured `random_get` with a custom import module and name and infer that I intended for that symbol to be undefined. Ideally Emscripten would have supressed the error for that symbol but would keep the error for other symbols that don't have import modules and names.

**Comment by sbc100** [comment]
Unfortunately I don't know of a good way to distinguish between imports with these attributes and normal undefined symbols. 

In this case we could specifically ignore imports from the non-default module (i.e. anything not imported from `env`).  That would help but not in the case that you only specified `import_name`.  Maybe that is enough?

**Comment by jerbob92** [comment]
@sbc100 Do you know why other wasi imports do not result in this error, like `__wasi_clock_res_get`?

**Comment by sbc100** [comment]
@jerbob92 because they are defined in our JS library: `src/library_wasi.js`.   Symbols need to either be defined in the wasm file, or in the JS library to avoid being reported as undefined.

**Comment by jerbob92** [comment]
Ah that actually makes sense. We actually need that implementation anyway @tlively to properly support JS urandom in standalone mode.

**Comment by tlively** [comment]
> Unfortunately I don't know of a good way to distinguish between imports with these attributes and normal undefined symbols.
> 
> In this case we could specifically ignore imports from the non-default module (i.e. anything not imported from `env`). That would help but not in the case that you only specified `import_name`. Maybe that is enough?

That sounds like enough to me. It would cover the case of importing WASI APIs, at least.

**Comment by sbc100** [comment]
Actually it won't work for wasi I think because our JS library implements both `env` and `wasi_snapshot_preview1` .. so its kind of our domain.  We could treat imports from any other module as outside of our domain maybe.  

However, I do think the emcc linker approach of requiring every symbol to have a definition is reasonable... what about if we made `-sERROR_ON_UNDEFINED_SYMBOLS=0` more ergonomic?   What if you it could be spelled `-Wno-undefined` (like other warning/error flags).

**Comment by tlively** [comment]
TBH I misunderstood `-sSTANDALONE_WASM` and thought it only produced a Wasm module until looking at the docs today. Given that it produces a JS file as well and is meant to produce programs that can be run on the Web, requiring JS definitions makes perfect sense.

Making the flag look like a normal error flag sounds good to me, but I guess it is separate from this issue, which I'll go ahead and close.
