### ISSUE TITLE
Unable to build boost starting from 3.1.18 due to new LLVM

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#17926]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.18 (d5ca9bba6513763d5bdddbd0efff759332bd85d7)
clang version 16.0.0 (https://github.com/llvm/llvm-project 48129cf0ed5053ed3fdf4f928180635e84892614)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/apple/AcroJS/emsdk/upstream/bin
```

**Failing command line in full:**
```
 "emcc" "-v" -x c++ -fvisibility-inlines-hidden -std=c++17 -DBOOST_RESULT_OF_USE_TR1_WITH_DECLTYPE_FALLBACK -DBOOST_FILESYSTEM_NO_CXX20_ATOMI
C_REF -O3 -Wall -fvisibility=hidden -Wno-inline -Wextra -Wno-long-long -Wno-unused-parameter -Wno-variadic-macros -Wunused-function -std=c++17 -
sMAIN_MODULE=2 -fwasm-exceptions -sSUPPORT_LONGJMP='wasm' -DBOOST_ALL_NO_LIB=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_DONT_USE_CHRONO -DBOOST
_THREAD_POSIX -DNDEBUG -I"."  -c -o "bin.v2/libs/thread/build/clang-darwin-emscripten/release/link-static/threadapi-pthread/threading-multi/visi
bility-hidden/pthread/thread.o" "libs/thread/src/pthread/thread.cpp"
```

Below is the error I am gettng:
<img width="1312" alt="Screenshot 2022-09-25 at 5 38 01 PM" src="https://user-images.githubusercontent.com/19284116/192144518-d3da13de-241b-44ea-be18-9c0b53a34067.png">

On doing a quick search on web, it seems this is some kind of SFINAE issue. I can compile the same code with 3.1.17 but not with 3.1.18 . Looks like new LLVM in 3.1.18 has some [issues](https://pullanswer.com/questions/integer-value-out-of-range-for-enumeration-type-causes-hard-error-rather-than-sfinae)

**Comment by kripken** [comment]
It looks like the newer clang that emcc now uses has a new warning/error that happens on that code. Perhaps a newer version of boost already has a fix for that. Or, you can disable that error (based on what it says, you can do `-Wno-enum-constexpr-conversion`).
