### ISSUE TITLE
Embind not exporting class member function

### ISSUE THREAD

**Issue by elttuercas** [emscripten-core/emscripten#17928]
Hello,
I am running into a weird issue which I haven't managed to find anywhere else. I am trying to use emscripten to compile a C++ library I am creating. I have implemented my library classes using a pointer to implementation pattern and I am trying to export the public API class with embind, which works halfway.

In a simplified example, these are the source code files, with a brief explanation:

`Interface.h`
This is an interface implemented by many of the classes of the library, particularly data models, and it's meant to handle JSON serialisation and deserialisation since I'm building the library for use in the web and JSON makes working with APIs very convenient.

```c++
#pragma once

#include <string>
#include <json/value.h>
#include <json/writer.h>

class Interface
{
public:
    /**
     * Define how the class implementing this interface should serialise itself to a JSON value.
     * @return
     */
    virtual Json::Value jsonSerialize() const = 0;

    /**
     * Define how the class implementing this interface should deserialise itself from a JSON object which contains
     * data for all of its properties.
     */
    virtual void jsonDeserialize(const Json::Value &v) = 0;

    /**
     * Use the JSON serialisation capabilities of the class to convert the object into a valid JSON string.
     * @return
     */
    std::string toJsonString() const
    {
        static Json::FastWriter writer;
        return writer.write(jsonSerialize());
    }
};
```

`Sample.h`
A sample data model which holds an integer value.

```c++
#pragma once

#include <cstdint>
#include <memory>
#include <Interface.h>

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#include <emscripten/bind.h>
#endif

class Sample;

using SamplePtr = std::shared_ptr<Sample>;

class Sample : public Interface
{
public:
    /**
     * Create a new sample view model object.
     * @return
     */
    static SamplePtr newSample();

    /**
     * Default destructor.
     */
    virtual ~Sample() = default;

    /**
     * Sample value getter.
     * @return
     */
    virtual int32_t getValue() const = 0;

    /**
     * Sample value setter
     * @param v
     */
    virtual void setValue(int32_t v) = 0;
};

#ifdef __EMSCRIPTEN__
using namespace emscripten;

EMSCRIPTEN_KEEPALIVE
EMSCRIPTEN_BINDINGS(sample)
{
   class_<Sample>("Sample")
       .smart_ptr_constructor("Sample", &Sample::newSample)
       .function("toJsonString", &Sample::toJsonString)
       // Why doesn't function bind, but property does? No idea!
       .property("json", &Sample::toJsonString)
       .property("value", &Sample::getValue, &Sample::setValue);
}
#endif
```

As you can probably guess, the issue is that the function inherited from `Interface`, `toJsonString()` doesn't get exported to WASM, but if I bind the function to a property getter, such as "json", it works fine.

And here is the implementation of the `Sample` data model's public API.

`SampleImpl.h`

```c++
#pragma once

#include <cstdint>
#include <memory>
#include <json/value.h>
#include <Sample.h>

class SampleImpl : public Sample
{
public:
    /**
     * Default constructor.
     */
    SampleImpl() = default;

    /**
     * Default destructor.
     */
    ~SampleImpl() override = default;

    /**
     * Sample value setter.
     * @param v
     */
    void setValue(int32_t v) override;

    /**
     * Sample value getter.
     * @return
     */
    int32_t getValue() const override;

    /**
     * JSON serialisation implementation.
     * @return
     */
    Json::Value jsonSerialize() const override;

    /**
     * JSON deserialisation implementation.
     * @param v
     */
    void jsonDeserialize(const Json::Value &v) override;

protected:
    /**
     * A sample value to demonstrate getters/setters.
     */
    int32_t m_iSampleValue {};
};
```

`SampleImpl.cc`

```c++
void SampleImpl::setValue(int32_t v)
{
    m_iSampleValue = v;
}

int32_t SampleImpl::getValue() const
{
    return m_iSampleValue;
}

Json::Value SampleImpl::jsonSerialize() const
{
    Json::Value value;
    value["value"] = m_iSampleValue;

    return value;
}

void SampleImpl::jsonDeserialize(const Json::Value &v)
{
    m_iSampleValue = v["value"].as<int32_t>();
}

SamplePtr Sample::newSample()
{
    return std::make_shared<SampleImpl>();
}
```

I am using CMake to build my library as well as the JsonCpp library so I can easily target both WASM with emcmake and a standard system with regular cmake. After building libjsoncpp.a and libsample.a with emcmake and emmake, I build the JS and WASM with `em++ lib/libjsoncpp.a lib/libsample.a -lembind --bind -sLINKABLE=1 -o libsample.js`

This produces a ~1.5 to 2 MB JS file and a WASM file of roughly the same size, which when used in a web project properly expose the `Sample` class, properly use the smart pointer constructor and properly expose the exported properties. Everything works fine except for the exported function. Any input would be greatly appreciated, thank you.

**Comment by elttuercas** [comment]
Created a repository with the sample code to make the issue as easy to replicate as possible: [https://github.com/elttuercas/embind-sample-issue](https://github.com/elttuercas/embind-sample-issue)

Additionally, a simple demonstration of the issue can be found in index.html, which produces the following console output:
![image](https://user-images.githubusercontent.com/42558820/192866369-829aaea1-2b67-44bd-8315-652f63188951.png)

**Comment by brendandahl** [comment]
You need to tell embind that class is derived from another class:
e.g.
```cpp
  class_<Interface>("Interface");
  class_<Sample, base<Interface>>("Sample")
```

I'm not quite sure why using it as a property is okay. I'll have to check that out.

**Comment by elttuercas** [comment]
> You need to tell embind that class is derived from another class: e.g.
> 
> ```c++
>   class_<Interface>("Interface");
>   class_<Sample, base<Interface>>("Sample")
> ```
> 
> I'm not quite sure why using it as a property is okay. I'll have to check that out.

Ah, that makes a lot of sense. Prior to this I was using the `property` method to bind some getters and setters from a base class in the export of a derived class and I was scratching my head as to why it wouldn't work with the `function` method. It's documented, but I had skimmed past it several times while scrolling through the Embind documentation. Sorry for the hassle hehe.

I'll mark the issue as closed on my end since your comment helpfully addresses my problem :)
