### ISSUE TITLE
Asyncify : Error instanciating "LibRaw::dcb_color_full()"

### ISSUE THREAD

**Issue by EmmanuelBIGEON** [emscripten-core/emscripten#17927]
Hi.

I can't compile with "-s ASYNCIFY".

![errorr](https://user-images.githubusercontent.com/43699856/192232274-4b765a1b-6b00-4760-a1e9-b86e9ae5034e.PNG)

I'm guessing it is shipped with emscripten and I don't know how to fx this error, i really need asyncify and everything i have been using so far. 
Should i try a more recent version ?

Current version : 3.1.9
Thank you.

**Comment by kripken** [comment]
`local count too large` might be fixed by running with more optimizations. Try `-O3` during link.

**Comment by EmmanuelBIGEON** [comment]
I was compiling with `-O0`, compiling with `-O1` didn't fixed it for me but `-O2` did. So i am sure `-O3` will. 
Thank you !
