### ISSUE TITLE
sys/timex.h has disappeared

### ISSUE THREAD

**Issue by MarkCallow** [emscripten-core/emscripten#17932]
My unchanged code is getting

```
/src/lib/basisu/encoder/basisu_enc.cpp:245:10: fatal error: 'sys/timex.h' file not found
#include <sys/timex.h>
```

when compiled with Emscripten 3.1.23. It compiled fine with 3.1.20 so somewhere between 20 and 23, the file disappeared or was moved.

I looked in an old Emscripten installation I have and found the file in `system/lib/libc/musl/include/sys` hence reporting here.

Is the removal intentional or an error? If intentional, what am I supposed to use instead?

**Comment by sbc100** [comment]
This header file (along with several others) were removed in #17638.  This was a deliberate change since emscripten doesn't support any of these linux specific headers / APIS.   

In the case of `timex.h` specifically it declares there two functions:

```
int adjtimex(struct timex *);                                                    
int clock_adjtime(clockid_t, struct timex *); 
```

Emscripten doesn't support either of these functions.

**Comment by sbc100** [comment]
If they upstream code doesn't have an easy way to avoid including that header we could consider adding stubs for these functions.

**Comment by MarkCallow** [comment]
Thanks @sbc100. Our code that includes this is part of a subrepo import so I was not familiar with it. It turns out it is not using these functions, only functions declared in `sys/time.h` which is included by `sys/timex.h`. This explains why the code worked when compiled with previous versions of Emscripten. I can easily fix it. I don't see any need for stubs.
