### ISSUE TITLE
Value seems to be optimized out but it should not be

### ISSUE THREAD

**Issue by kovzol** [emscripten-core/emscripten#17934]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.22 (a9981ae2a7dc3c45f833d0b2202f739d87ac05c8)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8491d01cc385d08b8b4f5dd097239ea0009ddc63)
Target: wasm32-unknown-emscripten
Thread model: posix

I successfully use emscripten to port a terminal based application to the web. When reading the width of the terminal via sys/ioctl.h, winsize.ws_col, the correct value is obtained in the old version emscripten-2.0.22. Now I updated emscripten to version 3.1.22 and it does a very good job in general, but it seems to optimize out the value of winsize.ws_col if it is not used earlier than in a return statement. (I do use it in a return statement.) When adding a dummy manipulation of that value before the return statement, it will not be optimized out (that is correct). See the workaround at https://github.com/kovzol/tarski/commit/9b358bdb2905f61ca4f6426b94397f05f988c150. I assume `-O3` optimization is responsible for creating the wrong binary code.

Maybe this is an LLVM issue, but anyway, the binary code is incorrect.

**Comment by sbc100** [comment]
Are you observing the wrong value on the caller side?  What value are you observing?

**Comment by kovzol** [comment]
That's very strange, indeed.
Is there a suggested way how to do it safely in emscripten?

**Comment by sbc100** [comment]
We don't implement this yet in emscripten so it seems like you should just hardcode a value?   What value were you getting before?  How was this working with older emscripten?

**Comment by kovzol** [comment]
That's something odd. For some reason, it is always set to 82, so the application thinks the column width is 82. I have no idea where this number comes from... Not from our source code, and seemingly not from [jquery.terminal](https://terminal.jcubic.pl/) that puts this in a modern UI.
I tried this minimal example, but you are right, the column value is set to 0:
```cpp
#include <iostream>
#include <sys/ioctl.h>
#include <unistd.h>
#include <emscripten/emscripten.h>

int main()
{
  struct winsize w;
  ioctl(STDOUT_FILENO, TIOCGWINSZ, &w);
  int cols = w.ws_col;
  int rows = w.ws_row;
  std::cout << "cols = " << cols  << std::endl;
  return 0;
}
```

I used `emcc main.cpp -o 17934.html -s EXPORTED_FUNCTIONS="['_main']" -s SINGLE_FILE=1` to compile this and I get `cols = 0`.

**Comment by kovzol** [comment]
OK, I think everything is clear now. Since TIOCGWINSZ is not implemented yet, the data it provides is unsafe and it does not contain what the user expects. I close this for now since it is clear that it cannot be used for the moment. Maybe emscripten should warn the user to not use this feature yet.
