### ISSUE TITLE
Compiling code that uses libstdc++ libraries.

### ISSUE THREAD

**Issue by braulio-balanza** [emscripten-core/emscripten#17937]
Hello! I wanted to know if there were, to your knowledge, any pre-built archives of libstdc++ that I could include when compiling code that uses `<ext/pb_ds/assoc_container.hpp>` using em++. I know there is the -stdlib flag to use the libstdc++ library instead of libc++, but I have failed to find a port of libstdc++. Any help or guidance would be greatly appreciated!

**Comment by sbc100** [comment]
I don't know of anyone that has tried to compile libstdc++ with emscripten.   Its might be a tricky thing to do, although probably not impossible.  I imagine it will be easier to port your code to a standard container type, but its hard to say.

**Comment by braulio-balanza** [comment]
Thank you for the reply! Well, I will try giving it a shot and compiling libstdc++, but it might take me quite some time.
