### ISSUE TITLE
emcc on windows: The system cannot find the path specified

### ISSUE THREAD

**Issue by Darker** [emscripten-core/emscripten#17950]
The batch for running emscripten is broken and there is no way it worked in a recent time. It referrences files that don't exist.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.23 (5ae63ce7dd955df449cb419bfe5afc51d1bd57f2)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\lib\emsdk\upstream\bin
```

**Failing command line in full:**
```
C:\Users\USERNAME>emcc
The system cannot find the path specified.
C:\Program Files\Python310\python.exe: can't open file 'C:\\emcc.py': [Errno 2] No such file or directory
```
Modifying the batch `emcc.bat` as following fixes the issue:
```
@ECHO OFF

@call %~dp0\..\..\emsdk_env.bat 2>nul

py -3 %EMSDK%\upstream\emscripten\emcc.py %*
```

**Comment by sbc100** [comment]
That is rather odd since the bat files work fine in all the various test environments.

What does `where emcc` say?  It should live in the same directory as the emcc.py file.   

If you are using emsdk then you should be running emsdk_env.bat before trying to run emcc.  Are you doing that?  if not perhaps there is an old version of `emcc.bat` in your PATH?

**Comment by Darker** [comment]
This is all brand new. Running `emsdk_env` every time is not viable if you want to run `emcc` as compiler from an IDE. In what context exactly would the batch I mention work? It literally mentions paths and filenames that do not exist in the whole project.

```
C:\Users\USERNAME>where emcc
D:\lib\emsdk\bazel\emscripten_toolchain\emcc.bat
```

It is possible that I put the wrong file on my path, but I doubt it - the only purpose this batch seems to serve is making sure the env is set before invoking `emcc.py`, except the paths to both things are outdated. If I tried to run `emcc.py` directly, it would fail unless I set the env first.

**Comment by sbc100** [comment]
Do you know where `D:\lib\emsdk\bazel\emscripten_toolchain\` might have come from?   Maybe try completely removing that path and also removing it from your `PATH` environment variable.

It should b enough to just add the correct emcc location to your PATH.  I believe `emsdk activate latest` will tell you what to do.  It should show instructions.

You can use try passing `--permanent` to `emsdk activate latest` which should update your resistivity settings.

**Comment by Darker** [comment]
Further investigation shows that `emsdk\bazel\emscripten_toolchain\` is not part of this repo, I accidentally posted in a wrong repository. Sorry about that, I just googled "emscripten github". This problem is in the repo https://github.com/emscripten-core/emsdk refferenced in this tutorial: https://emscripten.org/docs/getting_started/downloads.html

**Comment by Darker** [comment]
Closing as this is the wrong repo for this issue.
