### ISSUE TITLE
Inline js functions

### ISSUE THREAD

**Issue by caxapexac** [emscripten-core/emscripten#17974]
I want to make my js library fast enough. Method calls cost some time (I can't relate to V8 optimizations, its non-determinated)

E.g.:
```js
$Render: {
    draw: function() {
        for (const obj: objects) {
            this.prepareObject(obj);
        }
    },
    prepareObject: function(context) {
        // Literally anything
    } 
}
```

`prepareObject` method here was moved to a separate method just because of readability, really no more reasons creating it. It would be hillarious trying to fit all the render code in the single function

I ask this kind of stuff because library declaration code is yours 'extended-macro-js' with `ifdef` and other kind of stuff so Im wondering if there is some ways optimizing high-load js code

**Comment by sbc100** [comment]
I think its normally safe to assume the V8 and/or closure compiler will do a good job with inlining when it makes sense.  Have you observed specific cases where doing manual inlining makes a big difference?  

We don't really a good way to do inlining with the JS compile in emscripten.. and indeed its not really an emscripten issue, perhaps there are tools out there in the JS world that can help you get the result you want.   Maybe closure compiler can do it?

**Comment by caxapexac** [comment]
Okay it makes sense, thanks, I'll take a look at closure
