### ISSUE TITLE
Building conan recipes for WebAssembly - `AR` and `RANLIB` variables are not being picked up when CMakeToolchain is being used

### ISSUE THREAD

**Issue by szigetics** [emscripten-core/emscripten#17992]
Details : 
https://github.com/conan-io/conan/issues/12232

Proposed solution : 
https://github.com/conan-io/conan/issues/12232#issuecomment-1268105148

Do you think that it would make sense to do this toolchain file (`upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake`) update?

**Comment by sbc100** [comment]
I'm not sure why you mean since `CMAKE_AR` and `CMAKE_RANLIB` are already set in `upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake`: https://github.com/emscripten-core/emscripten/blob/40fb7d2071e439f1de614898b88518df582faa94/cmake/Modules/Platform/Emscripten.cmake#L97-L103

**Comment by sbc100** [comment]
Oh I see you are proposing something like this:

```
if ("${CMAKE_AR}" STREQUAL "" OR (NOT "${CMAKE_AR}" STREQUAL "$ENV{AR}"))
  set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar" FORCE)
endif()
```

Do you know why this would be needed?  Do you know where `CMAKE_AR` is being set?

**Comment by sbc100** [comment]
I wonder if we should just unconditionally set all of those variables instead?

**Comment by szigetics** [comment]
> Oh I see you are proposing something like this:
> 
> ```
> if ("${CMAKE_AR}" STREQUAL "" OR (NOT "${CMAKE_AR}" STREQUAL "$ENV{AR}"))
>   set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/emar${EMCC_SUFFIX}" CACHE FILEPATH "Emscripten ar" FORCE)
> endif()
> ```
> 
> Do you know why this would be needed? Do you know where `CMAKE_AR` is being set?

I spent some time trying to check where `CMAKE_AR`is being set, but I couldn't track it down yet.
Normally I would try to call the cmake generate command with `--trace --debug-output`, but using the new CMake conan helper I don't see a way to do this ( https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake.html#configure ) .

(Using the previous CMake helper, it was possible to pass additional `args` to the cmake generator call ( https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#configure ).)

**Comment by sbc100** [comment]
I think #17997 will fix the issue.
