### ISSUE TITLE
Unreachable code warning in 3.1.20 in Firefox

### ISSUE THREAD

**Issue by nullStandard** [emscripten-core/emscripten#17996]
Compilation with `-sPTHREAD_POOL_SIZE_STRICT=2` leads to `unreachable code` warning in Firefox. Chrome is good, it just doesn't care.

A simple program is given: 
```cpp
#include <iostream>
#include <thread>
int main() {
  std::thread t([]() {
    std::cout << "Hello world" << std::endl;
  });
  t.join();
  return 0;
}
```

Compiled with `emcc main.cpp -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2 -s PTHREAD_POOL_SIZE_STRICT=2 -o main.html`

If you look at the indicated line, you will see that there is indeed an unreachable code in `getNewWorker` function:

```js
getNewWorker:function() {
  ...
  // Don't return a Worker, which will translate into an EAGAIN error.
  return;
  PThread.allocateUnusedWorker();
  PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0]);
  ...
}
```
I suspect the issue lies in incorrect code generation in `src/library_pthread.js`:

```cpp
getNewWorker:function() {
  ...
#if PTHREAD_POOL_SIZE_STRICT == 2
  // Don't return a Worker, which will translate into an EAGAIN error.
  return;
#endif
  ...
  PThread.allocateUnusedWorker();
  PThread.loadWasmModuleToWorker(PThread.unusedWorkers[0]);
  ...
}
```

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.20 (5d878c99921ec247d34fb26a20b5a13d60d69e93)
clang version 16.0.0 (https://github.com/llvm/llvm-project 75767a0f9a926641edbef08e31ec2148ff45da67)
Target: wasm32-unknown-emscripten
Thread model: posix

**Comment by sbc100** [comment]
I'm actually surprised that is the only unused code warning in the output file, since I don't think we have any tests or checks for such things.   I'll upload a fix for this issue, but it would be nice I think to run some basic checks on the generated code.
