### ISSUE TITLE
Apply ASYNCIFY to all functions

### ISSUE THREAD

**Issue by ChrisJefferson** [emscripten-core/emscripten#18030]
I think I have a problem with ASYNCIFY, and I'd like to test this by marking all functions to be compiled as async.

I tried using `ASYNCIFY_IMPORTS`, but I can't (easily) generate a list of every function, to then pass to `ASYNCIFY_IMPORTS` (separately, it's not clear to me what the format is for passing multiple functions to `-sASYNCIFY_IMPORTS`.

`ASYNCIFY_REMOVE` mentions that is takes wildcards in settings.js. Could `ASYNCIFY_IMPORTS` or `ASYNCIFY_ADD` take wildcards too? (Then could I just pass `*`?)

**Comment by kripken** [comment]
Wildcards should work in all the lists. Here are the lower-level binaryen docs for Asyncify:

https://github.com/WebAssembly/binaryen/blob/b83450ed1fd98cec4453024f57f892b31851ea50/src/passes/Asyncify.cpp#L253-L278

The `settings.js` text saying `See notes on ASYNCIFY_REMOVE about the names` means that the same wildcards etc. can be applied there. But if that's not clear enough, suggestions for better text would be welcome.

**Comment by algestam** [comment]
Would perhaps changing the doc text for `ASYNCIFY_ADD` and `ASYNCIFY_ONLY` from `See notes on ASYNCIFY_REMOVE about the names` to `See notes on ASYNCIFY_REMOVE about the names, including wildcard matching and character substitutions` be an acceptable change? If so, I'm happy to prepare a PR.

**Comment by kripken** [comment]
@algestam Sounds good! Yes, a PR would be great.
