### ISSUE TITLE
How to detect / determinate the Emscripten version at build time?

### ISSUE THREAD

**Issue by jmglogow** [emscripten-core/emscripten#18032]
I used to detect the Emscripten build version in my `autoconf` script using `echo | emcc -dM -E - | grep __EMSCRIPTEN_`, to get major, minor and tiny version parts nicely split in different variables. But these defines were removed in PR #17883.

Now I'm looking for a more stable way (probably not parsing `emcc --version`?). I checked `em-config`, but it doesn't provide that information. Then I looked into `tools/shared.py` and saw that code parses `emscripten-version.txt`. Including `shared.py` into `config.py` doesn't work, because it creates a circular include, so I would simply move set_version_globals to `config.py`, so it's accessibly from both modules?

Or maybe I'm missing something else?

P.S. I shortly thought about including `emscripten/version.h` into a C `check` program to dump the variables, but all this seems highly overengineered (but probably most stable w.r.t. API changes…).

**Comment by sbc100** [comment]
Sorry about that I hadn't imagined anyone was using `emcc -dM -E -` in that way.

Would parsing `emcc --version` be overly complicated?  That is how we detect the emscripten version in the make plugin: https://github.com/emscripten-core/emscripten/blob/main/cmake/Modules/Platform/Emscripten.cmake#L99-L111
I beliive that parsing the output of `CC --version` is also how autoconf normally does it version detection too.

If you want to make the C pre-processor method continue to work you could do something like this:

```
$ echo "#include <emscripten/version.h>" | ./emcc -dM -E - | grep EMS
#define EMSCRIPTEN 1
#define __EMSCRIPTEN__ 1
#define __EMSCRIPTEN_major__ 3
#define __EMSCRIPTEN_minor__ 1
#define __EMSCRIPTEN_tiny__ 25
```

**Comment by jmglogow** [comment]
> Sorry about that I hadn't imagined anyone was using `emcc -dM -E -` in that way.
> 
> Would parsing `emcc --version` be overly complicated? That is how we detect the emscripten version in the make plugin: https://github.com/emscripten-core/emscripten/blob/main/cmake/Modules/Platform/Emscripten.cmake#L99-L111 I beliive that parsing the output of `CC --version` is also how autoconf normally does it version detection too.

No, it's not complicated. I was just looking for some stable way, after my autoconf script broke. I'll just look what `autoconf` is doing to get the compiler version; that actually should be stable. And it's even used by the emscripten cmake module, which I didn't see before.

> If you want to make the C pre-processor method continue to work you could do something like this:
> 
> ```
> $ echo "#include <emscripten/version.h>" | ./emcc -dM -E - | grep EMS
> #define EMSCRIPTEN 1
> #define __EMSCRIPTEN__ 1
> #define __EMSCRIPTEN_major__ 3
> #define __EMSCRIPTEN_minor__ 1
> #define __EMSCRIPTEN_tiny__ 25
> ```

That would work too.

I hadn't really thought about the fact, that the emcc output had to pass the tests when used by `emconfigure` for `autoconf` scripts. The output looked so convoluted with all the text in the brackets, that I thought there should be something more easy to "parse".

Thanks for your fast reply.
