### ISSUE TITLE
Safari 16: WebAssembly.Module doesn't parse

### ISSUE THREAD

**Issue by cajus** [emscripten-core/emscripten#18043]
Hi, I'm not sure if this is the right place to ask - if not, please redirect me ;-)

Problem: I'm getting a `CompileError: WebAssembly.Module doesn't parse at byte 7: can't get Function local's type in group 2, in function at index 156106` in Safari. Loads fine on FF/Chrome/etc.

```
$ emcc -v                                                                                                                   ✔ 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.23 (5ae63ce7dd955df449cb419bfe5afc51d1bd57f2)
clang version 16.0.0 (https://github.com/llvm/llvm-project 8b587113b746f31b63fd6473083df78cef30a72e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/prcs1076/.emscripten/upstream/bin
```

Running `wasm-objdump -d` seems to have an "end" on the given index. Or it's decimal. Or it's the wrong place to look at all...

```
 1560dd: 20 01                      |               local.get 1
 1560df: 29 03 00                   |               i64.load 3 0
 1560e2: 21 02                      |               local.set 2
 1560e4: 02 7c                      |               block f64
 1560e6: 20 03                      |                 local.get 3
 1560e8: 45                         |                 i32.eqz
 1560e9: 04 40                      |                 if
 1560eb: 20 02                      |                   local.get 2
 1560ed: 42 00                      |                   i64.const 0
 1560ef: 59                         |                   i64.ge_s
 1560f0: 0d 07                      |                   br_if 7
 1560f2: 20 02                      |                   local.get 2
 1560f4: ba                         |                   f64.convert_i64_u
 1560f5: 0c 01                      |                   br 1
 1560f7: 0b                         |                 end
 1560f8: 20 02                      |                 local.get 2
 1560fa: 42 00                      |                 i64.const 0
 1560fc: 59                         |                 i64.ge_s
 1560fd: 0d 06                      |                 br_if 6
 1560ff: 20 02                      |                 local.get 2
 156101: 42 01                      |                 i64.const 1
 156103: 7c                         |                 i64.add
 156104: ba                         |                 f64.convert_i64_u
 156105: 9a                         |                 f64.neg
 156106: 0b                         |               end 
```

Any idea what that means?

**Comment by juj** [comment]
Here `in function at index 156106` likely does not refer to a byte offset in the binary file, but to the wasm function index. If you `wasm-dis` the file, you can search for the function with that index number.

Is this on macOS desktop Safari or on iOS Safari? Do you know if older Safari did work? Do you have a build command line repro that would produce this kind of failing Safari build, in particular what command line flags you used to create the wasm that doesn't work?

Either there was some build flag you added to the build that uses a feature that Safari does not yet support, or then Safari has indeed regressed their wasm support (which has happened in the past a few times, so curious to know which one would be the case here)

**Comment by cajus** [comment]
Ah, thanks @juj - using wasm-dis, the index pointed to a method of an external library that was using SIMD instructions... Seems like safari does not support this. Going to disable that.
