### ISSUE TITLE
Adding support for memfd_create

### ISSUE THREAD

**Issue by AithaTarun** [emscripten-core/emscripten#18062]
Hello, I get to know that emscripten doesn't support the method memfd_create (). So, is there a way to add support for this?

**To reproduce the error** 
```
#include <stdio.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stdlib.h>
#define _GNU_SOURCE

int memfd_create(const char *name, unsigned int flags);

int main()
{
    int fd = memfd_create("temp", 0);

    printf("Fd : %d\n", fd);

    int wrote = write(fd, "Hello", 5);

    printf("Wrote : %d\n", wrote);

    char * buf = malloc(5);

    int red = pread(fd, buf, 5, 0);

    printf("Read : %d\n", red);
    printf("Content %s\n", buf);
}
```

**Error**
![1](https://user-images.githubusercontent.com/67645139/195970099-144a580d-40fe-4c0b-bdc3-9bbdd146ae06.png)

**Comment by sbc100** [comment]
IIUC `memfd_create` is a linux-specific thing.  Its possible we could implement it in emscripten, but it might be easier if you found a way to compile you code such that it does not depend on this function.   Most portable code should not have a hard dependency on this function.. is there some macro you can define to disable this call in the source code in which lives?

**Comment by AithaTarun** [comment]
> IIUC `memfd_create` is a linux-specific thing. Its possible we could implement it in emscripten, but it might be easier if you found a way to compile you code such that it does not depend on this function. Most portable code should not have a hard dependency on this function.. is there some macro you can define to disable this call in the source code in which lives?

Thanks for the response, I just need to create a temporary shared memory and get its file descriptor. I have tried open() function with the flag O_TMPFILE and this. I can't create temporary shared memory with both approaches. I am defining this function in my code and it won't be dependent on other source code, I just want to send some data from JS to C and store that in shared temporary memory and later read from it.

**Comment by sbc100** [comment]
If you are using emscripten's default MEMFS filesystem then all files exist solely in memory, so you can just use `open` or `fopen` with any path you like.

**Comment by AithaTarun** [comment]
Ok, thanks. I will give it a try

**Comment by vadimkantorov** [comment]
> If you are using emscripten's default MEMFS filesystem then all files exist solely in memory, so you can just use `open` or `fopen` with any path you like.

I'm implementing a portable in-memor, readonly FS, so also was needing `memfd_create` or `shm_open` :)

Unfortunately, `fmemopen` does not produce a valid `fileno`/fd object in glibc.

What would be a way to accompany it with a valid (and guaranteed) in-memory fd in musl libc/emscripten? Is `shm_open` supported? 

I found https://github.com/emscripten-core/emscripten/issues/3020, but it was auto-closed :( @sbc100 It would be nice if emscripten somewhere had a table with libc functions to know what is supported and what not and maybe link to existing issues (when they are closed/auto-closed it's a bit confusing)

**Comment by sbc100** [comment]
In terms of documentation for libc/posix stuff, I agree it would be nice have.   Perhaps we could create that main that in the wiki? Or a new page in the site docs?   Feel free to send a PR to feel inclined to make a start on that.

**Comment by vadimkantorov** [comment]
I'll try to create a wiki or docs page on known missing functions! (And later we can expand it into a more systematic list of all libc/posix functions)

**Comment by vadimkantorov** [comment]
Btw, is `fmemopen` supported on Emscripten?

**Comment by sbc100** [comment]
It looks like we do include musl's `fmemopen.c`, so it should work, although we don't have any test code for that.

**Comment by vadimkantorov** [comment]
Now that `shm_open` is supported (https://github.com/emscripten-core/emscripten/issues/3020 ), maybe `memfd_create` could be as well?

**Comment by sbc100** [comment]
Implementing `memfd_create` doesn't seem to hard, but since its linux-specific (unlike shm_open which is POSIX) its likely to be less used.    Emscripten doesn't tend to try to implement linux-specific stuff in the general case.   What is your use case for `memfd_create`?
