### ISSUE TITLE
Asyncify problems after update to 3.1.24

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#18067]
Hi, I updated js-dos project to use latest emscripten **3.1.24**. But now even simpliest test didn't work. When I built it with **-s ASSERTIONS=1 --profiling-funcs** I have following error:
```
007591d2:0x63c1 Uncaught RuntimeError: unreachable
    at Normal_Loop() (.llvm.10015310407968227838) (007591d2:0x63c1)
    at DOSBOX_RunMachine() (007591d2:0x6c57)
    at CALLBACK_RunRealInt(unsigned char) (007591d2:0x92724)
    at DOS_Shell::Execute(char*, char*) (007591d2:0xe2e4e)
    at DOS_Shell::DoCommand(char*) (007591d2:0xda01d)
    at DOS_Shell::ParseLine(char*) (007591d2:0xd7fe3)
    at DOS_Shell::Run() (007591d2:0xd8724)
    at SHELL_Init() (007591d2:0xd9b16)
    at runRuntime (007591d2:0x14149f)
    at ret.<computed> (wdosbox.js:9:129411)
```

But all this functions **already in asyncify lists,** so I bisected and first bad commit is:

```
6a58eafa5dd62f26c6bc38d8bf0a55dee97b79ff is the first bad commit
commit 6a58eafa5dd62f26c6bc38d8bf0a55dee97b79ff
Author: chromium-autoroll <[chromium-autoroll@skia-public.iam.gserviceaccount.com](mailto:chromium-autoroll@skia-public.iam.gserviceaccount.com)>
Date:   Tue Sep 13 23:04:38 2022 +0000

    Roll emscripten from ea154b19446b to fff3775abca4 (3 revisions)

    https://chromium.googlesource.com/external/github.com/emscripten-core/emscripten.git/+log/ea154b19446b..fff3775abca4

    2022-09-13 [sbc@chromium.org](mailto:sbc@chromium.org) Don't pass `-fno-inline-functions` when `-Oz`/`-Os` are used (#17843)
    2022-09-13 [7121787+tlively@users.noreply.github.com](mailto:7121787%2Btlively@users.noreply.github.com) [Proxying][NFC] Avoid unnecessary copies of std::function (#17834)
    2022-09-13 [7121787+tlively@users.noreply.github.com](mailto:7121787%2Btlively@users.noreply.github.com) [WasmFS][NFC] Do not eagerly execute queue in ProxyWorker (#17835)

    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/emscripten-emscripten-releases
    Please CC [wasm-waterfall@grotations.appspotmail.com](mailto:wasm-waterfall@grotations.appspotmail.com) on the revert to ensure that a human
    is aware of the problem.

    To report a problem with the AutoRoller itself, please file a bug:
    https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

    Tbr: [wasm-waterfall@grotations.appspotmail.com](mailto:wasm-waterfall@grotations.appspotmail.com)
    Change-Id: I217fac3bc67b0d69ff19fe04daae10f95d9d5f1e
    Reviewed-on: https://chromium-review.googlesource.com/c/emscripten-releases/+/3894706
    Commit-Queue: chromium-autoroll <[chromium-autoroll@skia-public.iam.gserviceaccount.com](mailto:chromium-autoroll@skia-public.iam.gserviceaccount.com)>
    Bot-Commit: chromium-autoroll <[chromium-autoroll@skia-public.iam.gserviceaccount.com](mailto:chromium-autoroll@skia-public.iam.gserviceaccount.com)>

 DEPS | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

What is **(.llvm.10015310407968227838)**? Maybe problem is in signature of **Normal_Loop()**? 

----
From em-discuss

> I would imagine the problem relates to the `-fno-inline-functions` change.  If you add that to your CFLAGS does the problem go away?

Yes this helps. But, how I make it work without this flag? I mean all functions already in asyncify list, but asyncify didn't work.

> Is there something about the above error (or some other error you saw) that makes you think this is an asyncify issue?  I'm not saying it isn't, I'm just wondering how you know it is?

`Uncaught RuntimeError: unreachable` this is typical message when something from stack is not in asyncify list, but I don't have any idea how I can verify that it is 100% asyncify issue.

**Comment by sbc100** [comment]
But adding `-fno-inline-functions` so clearly its #17843 that is to blame right?

**Comment by kripken** [comment]
Hmm, good point, that does point at that PR.

In that case, the obvious guess would be that inlining changes the list of functions that need to be in the asyncify list. But @caiiiycuk you say all those on the stack are already in the list. Perhaps there's a typo or such, though? One way to check is to inspect the wasm to see that those functions are all indeed instrumented for pausing and resuming. (Such functions have a typical shape, with a section up front to restore locals if resuming, and a section at the end to serialize then if pausing. If it's not obvious then I can take a look at a binary.)

**Comment by caiiiycuk** [comment]
Apologize, my notebook suddenly died, I will back with update when get new one. Thanks.

**Comment by caiiiycuk** [comment]
The **error stack**:
```sh
Uncaught RuntimeError: unreachable
    at Normal_Loop() (.llvm.15768448087407787512) (007594d6:0x63c1) **asyncify.txt: Normal_Loop() (.llvm.15768448087407787512)**
    at DOSBOX_RunMachine() (007594d6:0x6c57) **asyncify.txt: DOSBOX_RunMachine()"**
    at CALLBACK_RunRealInt(unsigned char) (007594d6:0x92724) **asyncify.txt: CALLBACK_RunRealInt(unsigned char)"
    at DOS_Shell::Execute(char*, char*) (007594d6:0xe2ee9) **asyncify.txt: DOS_Shell::Execute(char*, char*)**
    at DOS_Shell::DoCommand(char*) (007594d6:0xda0b8) **asyncify.txt: DOS_Shell::DoCommand(char*)**
    at DOS_Shell::ParseLine(char*) (007594d6:0xd7fe3) **asyncify.txt: DOS_Shell::ParseLine(char*)**
    at DOS_Shell::Run() (007594d6:0xd8724) **asyncify.txt: DOS_Shell::Run()**
    at SHELL_Init() (007594d6:0xd9b16) **asyncify.txt: SHELL_Init()**
    at runRuntime (007594d6:0x14153a)
    at ret.<computed> (wdosbox.js:9:129411)
```

The **DOSBOX_RunMachine** (asyncify function):
```wasm
 (func $DOSBOX_RunMachine\28\29
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (if
   (i32.eq
    (global.get $global$4)
    (i32.const 2)
   )
   (block
    (i32.store
     (global.get $global$5)
     (i32.sub
      (i32.load
       (global.get $global$5)
      )
      (i32.const 4)
     )
    )
```

The **Normal_Loop** function (I guess the problem function):
```wasm
 (func $Normal_Loop\28\29\20\28.llvm.15768448087407787512\29 (result i32)
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  (local $5 i32)
  (local $6 i32)
  (local $7 f64)
  (local $8 f64)
  (local $9 f32)
  (local $10 f32)
  (local $11 f32)
  (local $12 i64)
  (local $13 i64)
  (local.set $3
   (global.get $global$4)
  )
  (if
   (i32.eqz
    (i32.load8_u
     (i32.const 276960)
    )
   )
```

When I compile the wdosbox.wasm, I have following warning:
```sh
 warning: Asyncify onlylist contained a non-existing function name: Normal_Loop() ( llvm 15768448087407787512) (Normal_Loop\28\29\20\28\20llvm\2015768448087407787512\29)
```

I think it means that `$Normal_Loop\28\29\20\28.llvm.15768448087407787512\29` does not have an "asyncify magic".  Currently it in a asyncify.txt with this signature:
`Normal_Loop() (.llvm.15768448087407787512)` (copied from chrome browser)

Looks I need to escape something? Anyway I little bit worry that `(.llvm.15768448087407787512)` part can change after rebuild.

**Comment by caiiiycuk** [comment]
Before the bad commit, `Normal_Loop() (.llvm.15768448087407787512)` was a simple `Normal Loop`

**Comment by caiiiycuk** [comment]
Seems that there are not proper combination for escaping dot. I tried '.','\.','\\.' nothing works.

**Comment by kripken** [comment]
Wildcards should work, so perhaps try `Normal_Loop*`

**Comment by caiiiycuk** [comment]
Hi. I checked that wildcards are working. Anyway I think we have bug with dots processing, there is another example. I have this function in asyncify list:

```
Program::WriteOut(char const*, ...)
```

When I start program in browser, I see a message about unreachable in `Program::WriteOut(char const*, ...)`.
When I compile a wasm, I have following warning:

```
warning: Asyncify onlylist contained a non-matching pattern: Program::WriteOut(char const*,    ) (Program::WriteOut\28char\20const*\2c\20\20\20\20\29)
```

As you can see dots are replaced with spaces:
```
expected (from wasm dis): Program::WriteOut\28char\20const*\2c\20...\29
actual                  : Program::WriteOut\28char\20const*\2c\20\20\20\20\29
```

Of course if I put wildcard `Program::WriteOut*` it start working, however it looks like workaround and not real solution.

--
Is `*` treated as wildcard even it inside `()`, e.g. `some(const char*, int x)`? I have following function in asyncify list:
```
jsdos_main(Config*)
```
When I added it to list, I thought that I declare a single function not a pattern. However while compile I see this warning:
```
warning: Asyncify onlylist contained a non-matching pattern: jsdos_main(Config*) (jsdos_main\28Config*\29)
```

Is it treated as pattern? I worry that all this time I am using asyncify in wrong way 😃

**Comment by caiiiycuk** [comment]
Looks I can use this pattern, to match using only function name `name(*)*`
Closed, cause I think it more related to binaryen WebAssembly/binaryen#5271
