### ISSUE TITLE
wcstod return long instead of double 

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#18079]
`wcstod `return long instead of double.
for example, wcstod(L"123456.7777") is return  123456.
my suspicion is in the "C:\emsdk\upstream\emscripten\system\lib\libc\musl\src\stdlib\wcstod.c" line 43:
`long double y = __floatscan(&f, prec, 1);`

**Version of emscripten/emsdk:**
emcc 3.1.9
windows 11

**Linker Flags:**
  -s ALLOW_TABLE_GROWTH -s WASM_BIGINT   -s EXPORTED_RUNTIME_METHODS=ccall,cwrap -s EXPORTED_FUNCTIONS=_main  -g  --bind -s USE_PTHREADS -s ALLOW_MEMORY_GROWTH=1   -s PTHREAD_POOL_SIZE=50  -s EXIT_RUNTIME -s ASSERTIONS  -s FETCH   -s NO_DISABLE_EXCEPTION_CATCHING -s TEXTDECODER=0

**Comment by sbc100** [comment]
How are you reading/printing the return value of wcstod?

Can you give a full example of a broken program?

**Comment by aharondavid** [comment]
I see it in the Chrome Debugger (tstof is defined as  wcstod):
return long:

![image](https://user-images.githubusercontent.com/41375082/197249379-b277bf32-c4af-4ec5-ae50-73c73ad34bff.png)

return not accurate number:

![image](https://user-images.githubusercontent.com/41375082/197249638-22cfe1a1-414c-4e03-9180-c2670b2651bb.png)

**Comment by aharondavid** [comment]
Correction: the _`tstof` is defined as (`float)wcstod` The casting to float, of corset,  is the reason to the above result.
Sorry.
Thanks.
