### ISSUE TITLE
Disable SDL2 by default

### ISSUE THREAD

**Issue by aleck099** [emscripten-core/emscripten#18072]
`USE_SDL` is 1 by default
Everything is fine except for building SDL2
When USE_SDL=1, emcc will add an include path of its built-in SDL1, which contains same files with SDL2 (e.g. SDL_config.h)
Building SDL2 without additional flags will result in redefination errors

How to disable USE_SDL globally? Is there any configuration file or environment variable? Please don't tell me to use CFLAGS= because of many compability issues of many build systems

**Comment by sbc100** [comment]
If you want the system version of SDL you can use `-sUSE_SDL=0`

**Comment by sbc100** [comment]
Is there some reason the emscripten builtin SDL2 port doesn't work for you? (i.e. `-sUSE_SDL=2`)?

**Comment by sbc100** [comment]
If you really don't want to pass `-sUSE_SDL=0` on the command line you could edit `src/settings.js` and change the default for `USE_SDL` from 1 to 0... we don't normally recommend editing this file, but its one option.

**Comment by aleck099** [comment]
> If you really don't want to pass `-sUSE_SDL=0` on the command line you could edit `src/settings.js` and change the default for `USE_SDL` from 1 to 0... we don't normally recommend editing this file, but its one option.

Finally I edited `settings.js`

**Comment by Akaricchi** [comment]
I think `USE_SDL=1` is a bad default. SDL1 has been obsolete for years. How much maintained software even still depends on it?

**Comment by Akaricchi** [comment]
Common enough to have been noticed by at least two people here. Building your own SDL isn't that crazy when you build for multiple platforms and want precise and centralized control over your dependencies. We do that in Taisei; I wrote meson build definitions for all of our deps and we use the same set of subprojects for official emscripten, windows, macos, and linux builds. Building a custom SDL also allows us to disable a bunch of dead code that our game is not using, such as the built-in 2D renderer.

**Comment by sbc100** [comment]
Re-opening because there is some ongoing discussion about whether its a good idea to make `USE_SDL` default to 0 instead of 1.

**Comment by Akaricchi** [comment]
FWIW, SDL3 is now under development, so even SDL2 will be on its way out fairly soon (hopefully more gracefully than SDL1 was).
