### ISSUE TITLE
Acorn Optimizer Source Type Module

### ISSUE THREAD

**Issue by 5cript** [emscripten-core/emscripten#18094]
When building with optimizations, acorn_optimizer.js complains 
```
acorn-optimizer.js:1852
  throw err;
  ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (34:0)
export default Module;
```
As a workaround, I am currently patching [acorn_optimizer.js](https://github.com/emscripten-core/emscripten/blob/00daf403cd09467c6dab841b873710bb878535b2/tools/acorn-optimizer.js#L1916) to "exportES6 = true".
I dont know how or if I can pass the "--exportES6" somehow through emscripten to acorn optimizer. I am also not sure about where it actually finds the import/export statements, as my pre_js doesnt have any.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17 (fbc532773d84d2bd7da876275671970e792ad1cd)
clang version 15.0.2
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:/msys2/clang64/bin

**Full link command and output with `-v` appended:**
emscripten\em++.bat -O3 -DNDEBUG -sENVIRONMENT=web -sSINGLE_FILE -sNO_EXIT_RUNTIME=1 -sEXPORTED_FUNCTIONS=_frontendMain -O2 -sALLOW_MEMORY_GROWTH=1 -lembind --pre-js="E:/DevelopmentFast/minecraft-modpack-maker/frontend/src/frontend/js/module.js" @CMakeFiles\minecraft-modpack-maker.dir\objects1.rsp -o bin\index.js @CMakeFiles\minecraft-modpack-maker.dir\linklibs.rsp

**Comment by sbc100** [comment]
Can you link with `EMCC_DEBUG=1` in the environment?  I will save the intermediate files, such as the input to acorn, and you can see where the `import` / `export` is coming from?  Perhaps you could attach that file to this issue?

**Comment by 5cript** [comment]
Oh, I am sorry. It is coming from my js code.
Sorry for the inconvenience. Although I would not mind it as a feature sometime ;)
