### ISSUE TITLE
Support for WebAssembly externref in non-web environments

### ISSUE THREAD

**Issue by kwerner8** [emscripten-core/emscripten#18101]
My goal is to compile a function written in C/C++ to WebAssembly which has as an input/output type `externref`.
Then I want to call this function as an export in Wasmtime. So, this function will receive an `externref `as an input and also return one.

The WebAssembly Code in the wat format should look similar to this:

```
(func (export "func") (param externref) (result externref)
... WebAssembly Code ... )
```

I have seen that there exists [`wasm-bindgen`](https://crates.io/crates/wasm-bindgen) for browser hosts.

Is there a way to produce `externref `as an input and output for exports of functions written in C/C++ that can be called in non-web environments like Wasmtime?

**Comment by sbc100** [comment]
Currently there is no way to use the `externref` type from C/C++.  There are plans to enable this in the future but for now if you want to use externref you would need to write your function in assembly.  e.g. https://github.com/emscripten-core/emscripten/blob/main/test/core/test_externref.s.

**Comment by kwerner8** [comment]
Okay. Thank you very much!
Is there a timeline that I can use to track the process?

**Comment by sbc100** [comment]
I think the effort is being coordinated by igalia here: https://github.com/Igalia/ref-cpp.

**Comment by kwerner8** [comment]
Okay. Thank you very much.

**Comment by sbc100** [comment]
Closing for now since we do already have support in asm, and support in clang is outside the scope of emscripten.
