### ISSUE TITLE
Posting message from application thread to main UI thread in pthreads

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#18108]
**Description:**
I have an application built with pthreads and with my application running on a web worker.
I'm trying to post a message from the application thread to the main UI during the `instantiateWasm` call.
```
[pseudo code]
Module.instantiateWasm = function (imports, successCallback) {
    postMessage({........});

    continue with instantiating wasm file
}
```
This works for my main application thread (ENVIRONMENT_IS_PTHREAD = false).
However when my pthread worker is instantiating (ENVIRONMENT_IS_PTHREAD = true), it posts the message back to the main application thread which does not handle it.

Is there a way to forward the message back to the main UI thread? I've tried using the -sPROXY_TO_PTHREAD flag but that does not help me in this scenario.

I have a working application with logs to better understand this issue. Steps to run it:
[reproducer.zip](https://github.com/emscripten-core/emscripten/files/9885384/reproducer.zip)

1. call npm install
2. call npm start
3. Open browser dev console and navigate to `localhost:9999`

Results:
```
1. [Application Thead] ENVIRONMENT_IS_PTHREAD = false; Making async call; Posting message to Main UI thread;
2. [Main UI Thread] Received message from Application Thread
3. [Main UI Thread] Sending back 'Huge JSON object' to Application Thread
4. [Application Thead] ENVIRONMENT_IS_PTHREAD = false; Received 'Huge JSON object' from Main UI thread; ==== LOOP SUCCESS
1. [Application Thead] ENVIRONMENT_IS_PTHREAD = true; Making async call; Posting message to Main UI thread;
x. [Application Thread] ENVIRONMENT_IS_PTHREAD = false We should not be receiving message from another worker
still waiting on run dependencies:
dependency: wasm-instantiate
(end of list)
still waiting on run dependencies:
dependency: __asyncCall__
(end of list)
...
...
```

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.24 (68a9f990429e0bcfb63b1cde68bad792554350a5)
clang version 16.0.0 (https://github.com/llvm/llvm-project 277c382760bf9575cfa2eac73d5ad1db91466d3f)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
emcc main.cpp --profiling -pthread -s PTHREAD_POOL_SIZE=1 --pre-js preload.js -o dist/main.js

**Comment by sbc100** [comment]
I think you can do this by somehow attaching your own `onmessage` handler to the worker object.   See https://github.com/emscripten-core/emscripten/issues/15278

**Comment by Mintyboi** [comment]
@sbc100 Thanks for responding. I don't think that will help my scenario.
My application is running on a different thread as compared to the main UI thread and my application posts a message back to the main UI thread to get more information. i.e.
`Main UI thread <-> Application thread worker`

My issue is that the pthreads worker is unable to post a message back to the main UI thread because the application is the owner.
`Main UI thread <-> Application thread worker <-> PThreads worker`

Is there currently a way for the pthreads worker to talk to the main UI thread?
`Main UI thread <-> PThreads worker`
I can think of creating a messagechannel between each pthread worker and main UI thread to facilitate this requirement

**Comment by sbc100** [comment]
@Mintyboi can you explain a little more?   In particular, is the "main UI thread" the place where you create the emscripten module?   If so if `Application thread worker` actually a pthread too?   

Another way of asking the question: which of these threads is the main emscripten runtime thread (the thread from which pthreads are all managed and coordinated).

**Comment by Mintyboi** [comment]
Ah, the main emscripten runtime is my so called `application thread worker`.
That worker is started by explicitly calling a new worker in my JS file. In my reproducer attached, that's the index.js.

**Comment by sbc100** [comment]
In order for a pthread to communicate with the `Main UI thread` you would need to have the `Application thread worker` forward the messages back and forth. 

Alternately, I think you can pass a message port to the pthread so that it can then send message directly to the `Main UI thread`

**Comment by Mintyboi** [comment]
@sbc100 I have a draft PR (https://github.com/emscripten-core/emscripten/pull/18184) for the messagechannel approach I was thinking of above.
It helps to resolve the issue I'm seeing above. Do you think it's the right approach and if this is something we can get in?

**Comment by sbc100** [comment]
If possible,  I think it would be great if this could be done outside of emscripten itself, using pre-js/post-js/library-js.

**Comment by Mintyboi** [comment]
I agree, it would be cleaner and more manageable for us if that's possible.

However I don't seem to be able to find a way to inject a message channel port into the dynamically spawned pthreads worker and handle the port's onmessage handler without touching emscripten codes.

Might you have an idea that I can possibly try out?

**Comment by sbc100** [comment]
Which part it causing your the issue?  Is it hooking into the worker creation logic, or is it modifying the logic on the worker side?  I would hope that both as hookable.

**Comment by Mintyboi** [comment]
Yes, both actually.
- worker creation so that I can pass it a message port
- logic on worker side to handle the message port

**Comment by RReverser** [comment]
Just curious, why do you want to use browser's messaging mechanism specifically? Do you need to send JS objects? If not, it might be much easier to just "send" data in C++ land (via shared memory).

**Comment by sbc100** [comment]
I believe the main browser thread is not running any C++ code and doesn't shared memory with the worker on which the emscripten module starts (the emscripten runtime thread).

I think the intent is to allow direct communication between pthread workers and the main browser thread, even though there is no emscripten code at all running on the main browser thread and it did not create them.

**Comment by RReverser** [comment]
> even though there is no emscripten code at all running on the main browser thread

Hm, but they explicitly mention "main application thread" as `ENVIRONMENT_IS_PTHREAD = false`, aka it does run Emscripten's "main thread" code?

**Comment by sbc100** [comment]
yes but "Main UI thread", is the thread they they want to talk too, and they is not the "main application thread".  See https://github.com/emscripten-core/emscripten/issues/18108#issuecomment-1302809387.

I could still be misunderstanding I think.   However,  if the problem was just "how can pthreads talk to the main application thread which started them", then there are already ways to do that, as you say.

**Comment by sbc100** [comment]
See the above comment: `My issue is that the pthreads worker is unable to post a message back to the main UI thread because the application is the owner.
Main UI thread <-> Application thread worker <-> PThreads worker`

**Comment by RReverser** [comment]
> See the above comment: `My issue is that the pthreads worker is unable to post a message back to the main UI thread because the application is the owner. Main UI thread <-> Application thread worker <-> PThreads worker`

Ah I missed this one.

**Comment by RReverser** [comment]
Wait, but then I don't get

>  a way to inject a message channel port into the dynamically spawned pthreads worker and handle the port's onmessage handler without touching emscripten codes

If they want to talk to pthreads workers from their application thread worker, that can be done in the C++ land. But if they want to talk from the main UI thread to the application thread worker, there is no need to touch emscripten's own code. I don't get it :/

**Comment by sbc100** [comment]
In order to for a pthread worker to talk directly the main UI thread, the pthread worker needs to have a message port which communicates with the main UI thread.

The issue now, IIRC, is how to pass the message port to each of the new pthread workers and how to setup the various onmessage handler.    Some kind of hook in the pthread creation process would needed I think, but as you say, I think/hope it should be possible without modifying emscripten.

**Comment by sbc100** [comment]
The proposed emscripten changes are here: https://github.com/emscripten-core/emscripten/pull/18184.  I'm hoping they will not be needed.

**Comment by RReverser** [comment]
Ok, I see now what the scenario is. I think [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) might be the easiest option here as in that case you don't have to send message channels all the way to individual workers, but instead can have everyone subscribed to the same global uniquely-named broadcast.

**Comment by Mintyboi** [comment]
@RReverser Thanks for trying to understand my problem and finding a solution for it, I'm afraid I'll need to return something back to each individual workers instead of broadcasting to all the workers at the same time.
And also, thanks for clarifying my problem @sbc100.

I'll use my patch in my own emscripten build for now (as this request seem rather niche). I'll try other ways to see if I can move most of the changes outside of emscripten code, or maybe even not having to do a skip level communication

**Comment by mannk123** [comment]
This seems like an interesting problem! I tried taking a stab at it, created a PR at https://github.com/mannk123/emscripten/pull/1 to show a potential way using pre-js/post-js/library-js as suggested above.

**Comment by Mintyboi** [comment]
Closing this thread, there is no longer a need for me to return back to individual workers and I'll be changing my architecture so that there is no longer a skip level communication
