### ISSUE TITLE
emcc produces wrong code 

### ISSUE THREAD

**Issue by merlinsun** [emscripten-core/emscripten#18110]
Hi, 
For this case, there seems to be a discrepancy between emcc and clang.
**Version of emscripten/emsdk:**
```console
$ /emsdk/upstream/emscripten/emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.24 (68a9f990429e0bcfb63b1cde68bad792554350a5)
clang version 16.0.0 (https://github.com/llvm/llvm-project 277c382760bf9575cfa2eac73d5ad1db91466d3f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin
```

**Program:**
```console
$ cat small.c
#include <stdio.h>
struct S0 {
  signed f0 : 19
};
struct S0 g_1891[];
int main() {
  int i;
  for (; i < 9; i++)
    printf("%d\n", g_1891[i].f0);
}
```

**Command lines:**
```console
$ /emsdk/upstream/emscripten/emcc -w small.c -o small.js; node small.js
0
0
0
0
0
0
48
0
0
$ clang -w small.c -o small; ./small
0
0
0
0
0
0
0
0
0
```

**OS:** Ubuntu 22.04.1 LTS

**Comment by sbc100** [comment]
There are several things about this program that are undefined behaviour.  Firstly, `i` is not initialized to zero, but more importantly g_1891 isn't actually defining any data.  If you want to declare an array of 9 structs you would need to do `struct S0 g_1891[9];`

**Comment by merlinsun** [comment]
I feel sorry that I improperly simplified the original program.

Could you please take a glance at the following case, please? @sbc100 
```console
$ gcc -fsanitize=undefined test.c -o test;./test
0
$ /emsdk/upstream/emscripten/emcc test.c -o test.js; node test.js
8
$ cat test.c

#include <stdint.h>
#include <stdio.h>
int32_t a;
uint32_t b() {
  uint32_t c = 0;
  if (c <= -1L)
    for (a = 8; 0;)
      ;
  return c;
}
int main() {
  b();
  printf("%d\n", a);
}
```

**Comment by ChrisJefferson** [comment]
This is a 32-bit vs 64-bit issue -- emscripten compiles to 32-bits. `-m32` forces `gcc` to produce a 32-bit executable.

```
temp/ $ gcc t.c -m32
temp/ $ ./a.out
8
```

**Comment by sbc100** [comment]
I believe @ChrisJefferson is correct.    Building with `-sMEMORY64` would give the same results as x86_64 in that case.

Unless you disagree we can close this as WAI.

**Comment by merlinsun** [comment]
Thanks for your explanation!
I agree that this issue can be closed now.
