### ISSUE TITLE
Local count too large with debug info in big project

### ISSUE THREAD

**Issue by caxapexac** [emscripten-core/emscripten#18159]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.24

**Error:**
wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Compiling function #68624:"reactphysics3d::SolveBallAndSocketJointSystem::..." failed: local count too large @+39257309

Everything works on the small projects but fails on the main big project (272 more compilation units)

Everything works on the big project in release builds

Everything works on the big project on debug with `-g1` but fails with `-g2 -fsanitize=undefined`

Maybe there is a way to manually increase this locals max size in chrome launch settings or maybe some kind of link flag?

**Comment by kripken** [comment]
That is an agreed limitation in browsers, see https://github.com/WebAssembly/spec/issues/607 I am not aware of browser-specific flags to work around it.

However, you may be able to work around it manually using `wasm-opt -O1 file.wasm -o file.wasm`. Even the low (`-O1`) opts will remove many locals, which may be enough to get it runnable. You can also just link with `emcc -O2` but that will do a lot more optimizations.

**Comment by caxapexac** [comment]
@kripken thanks!
Any chances `wasm-opt` would be added to a sdk pipeline? If not - lets close the issue then (1k opened issues here and this is wild, I hope to find some time and maybe participate in closing some of them...)

**Comment by kripken** [comment]
@caxapexac `wasm-opt` is included in the emsdk, so if you use that you can run it from there. `emcc` will run it automatically at `-O2` and above, so you just need this as a manual workaround if you compile at lower optimization levels.

Help with the open issues would be great btw! :smile: Yes, there are quite a lot open. Many are just stale, I think, and people forget to close them.

**Comment by caxapexac** [comment]
Thanks!
