### ISSUE TITLE
test_pthread_run_on_main_thread seems to be causing chrome to stop responding

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#18210]
I'm not sure what changed .. perhaps the version of chrome we test under.

**Comment by kripken** [comment]
Does it fail consistently, or randomly?

**Comment by sbc100** [comment]
Not consistently, but I was seeing it fail more often than not in the last day or so.   For example, I saw it fail 4 or 5 times in a row on a single PR, and at the same time file across 5 separate PRs, but at the same time of those PRs did eventually land.

**Comment by sbc100** [comment]
Seems like maybe this was effecting firefox too: #18307

**Comment by sbc100** [comment]
I was trying to make this test pass under node and I found the cause of the deadlock.   The following simple program wil consistently reproduce the issue under node:

```
#include <emscripten/threading.h>                                                
#include <stdio.h>                                                               
#include <assert.h>                                                              
#include <math.h>                                                                
                                                                                 
void v() {                                                                       
  assert(emscripten_is_main_runtime_thread());                                   
  printf("Hello!\n");                                                            
}                                                                                
                                                                                 
void *thread_main(void*) {                                                       
  // Make the main thread call printf                                            
  emscripten_async_run_in_main_runtime_thread(EM_FUNC_SIG_V, v);                 
                                                                                 
  // Now call printf outselves.                                                  
  printf("never see this\n");                                                                                              
                                                                                 
  return 0;                                                                      
}                                                                                
                                                                                 
int main() {                                                                     
  pthread_t thread;                                                              
  int rc = pthread_create(&thread, NULL, thread_main, NULL);                     
  assert(rc == 0);                                                               
  rc = pthread_join(thread, 0);                                                  
  assert(rc == 0);                                                               
  return 0;                                                                      
}      
```

The problem comes down to this:

1. main thread spawns worker thread and then blocked until its done
2. main thread "blocks" by waking up ever 1ms to check for tasks
3. worker thread sends `v` as an async task for main thread
4. before main thread wakes up, worker thread calls `printf` which essentially does:
   - acquires stdout lock
   - syncronously proxy fd_write syscall to main thread (worker thread never returns from this)
   - release stdout lock
5. main thread wakes up and starts performing its first task which is `v`
6. main thread calls `printf` as part of running `v`
7. main thread attempt to acquire the printf lock of the worker thread is holding it.
8. main thread waits forever, and does not perform any more tasks because we don't run tasks recursively

**Comment by sbc100** [comment]
@tlively and I discussed the issue but cannot find a reasonable fix.  For now I think I will re-enable the test but use `-sPROXY_TO_PTHREAD` to avoid the deadlock.

**Comment by sbc100** [comment]
Actually `PROXY_TO_PTHREAD` doesn't make any difference.   Replacing `printf` with `emscripten_outf` works around it though.
