### ISSUE TITLE
std::log returns bogus answers

### ISSUE THREAD

**Issue by applmak** [emscripten-core/emscripten#18216]
**Version of emscripten/emsdk:**
% emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.25 (febd44b21ecaca86e2cb2a25ef3ed4a0a2076365)
clang version 16.0.0 (https://github.com/llvm/llvm-project effd75bda4b1a9b26e554c1cda3e3b4c72fa0aa8)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/applmak/Desktop/emsdk/upstream/bin

Hi! I'm using std::log, and I'm noticing some weird answers when I use emscripten on my M1 MacBook.

Here's my command-line:
```
emcc -g --no-entry -sMODULARIZE -sEXPORTED_FUNCTIONS=_render -sENVIRONMENT=web routines.cc -o routines.wasm
```

Here is my use of std::log:
```
double log2 = std::log(2);
```

Here is what the Chrome debugger is telling me (which is itself experimental and could be causing problems): 
```
0.0000075896644518014256
```

This isn't right, and I'm confused as to why this would happen. No variable in the debugger shows a value near the correct one (0.30102999566). Interestingly, `e^0.0000075896644518014256` is near 1, but that's probably a coincidence.

Am I just holding this wrong?

**Comment by sbc100** [comment]
Can you confirm if its debugging issue printing the value using printf?    

BTW how are you using the chrome debugger externsion if you are not building with `-g`?

**Comment by applmak** [comment]
Oh, you're right! I copied the wrong line from my history. The updated one is this: 
```
emcc -g --no-entry -sMODULARIZE -sEXPORTED_FUNCTIONS=_render -sENVIRONMENT=web routines.cc -o routines.wasm
```

I also updated the original issue.

**Comment by applmak** [comment]
Using printf("%f\n", log2) showed that the value in memory was 0.693147, which is actual, for realz, correct value. Strange behavior from the experimental debugger, then, and not a real issue.
