### ISSUE TITLE
test_embind seems to need more than 1MB of stack space.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#18246]
Specifically that tests that seems to need this are: 

- "custom smart pointer"
- "custom smart pointer can take and give null"
- "custom smart pointer passed through wiretype"
- "custom smart pointers can be passed to shared_ptr parameter"

Removing those two tests allows the test to run in 64KB.   These two tests seem to require over 1MB.  Might be worth investigating.

**Comment by sbc100** [comment]
@brendandahl do you know why these particular embind test might be needing MBs of stack?

**Comment by brendandahl** [comment]
I think it's because the custom smart pointer creates a pretty big array and fills it with valid values and invalid values on destruction.

**Comment by sbc100** [comment]
Thanks for investigating!  That is exactly what I was looking for.
