### ISSUE TITLE
Improve sizeof in Emscripten CMake implementation

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#18278]
Currently the CMake `check_type_size` check in Emscripten is implemented by returning the size as an exit code. This is problematic when Node.js itself throws an error and exits with an exit code - most commonly 7 - and that value ends up propagated to actual C code, which can lead to some rather surprising and hard to debug behaviour. It also doesn't work for sizes > 255 bytes.

This leads to issues like https://github.com/emscripten-core/emscripten/issues/18238, https://github.com/emscripten-core/emscripten/issues/17268, https://github.com/emscripten-core/emscripten/issues/18084, https://github.com/emscripten-core/emscripten/discussions/17811 and others.

This check was implemented back in https://github.com/emscripten-core/emscripten/pull/3447 because the upstream implementation - that instead relies on `strings` extraction from the binary - can't work on asm.js files. Now that we have Wasm as a default, perhaps the easy fix would be to at least use the upstream implementation for Wasm files, and something custom for asm.js to at least cover most common use-cases.

**Comment by RReverser** [comment]
Could we maybe just emit memory into a separate file during CMake checks? (IIUC, Emscripten has an option for that)

Then we could do binary scanning consistently for both output formats.

**Comment by sbc100** [comment]
I believe scanning the wasm would work fine, no need to a separate memory file.    The problem is the the upstream cmake test assumes the direct output file is that one to scan.. so I don't see how we could forking the cmake plugin (which I was hoping to do).

**Comment by RReverser** [comment]
Yeah, I think a small change will be still necessary then.

stdout check sounds good too, I just thought that doing binary scanning might be more future-proof and make it easier to revert to upstream CMake support if we ever drop JS output. Or maybe we could leave custom CMake overrides for asm.js only at some point.

Maybe it would be possible to contribute the stdout check upstream? Unless they want it to work for cross-compiling too when you can't run the output binary...

**Comment by sbc100** [comment]
Agreed, binary scanning of the .wasm is probably the best bet.. we might even be able to get away with simply injecting `-oformat=wasm` linker flag to force the output to just be the wasm file.

**Comment by RReverser** [comment]
Hm, if there are no sizeof differences between the two targets, sure, that sounds great too.
