### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by LGCoding** [emscripten-core/emscripten#18325]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.27 (afa75f342eef4d925172479afa8e6233eb0ae5a9)
clang version 16.0.0 (https://github.com/llvm/llvm-project dee009d3b5c71a340eb4ebb3cfb49f6015a789cc)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/liamgavin/Downloads/emsdk/upstream/bin

I am trying to compile a simple program but whenever I try and run an HTML file I get the error Uncaught SyntaxError: Unexpected token '<'. I was originally trying to compile a more complex program but when I couldn't get it to work I tried the simplest program I could. I am using live-server to host the local server.

My file:
#include <stdio.h>
#include <emscripten.h>

int main()
{
    printf("hello world!");
    return 0;
}
/////////////////////

The compile command:
emcc hello_world.c -o hello_world.html

**Comment by sbc100** [comment]
Can you attach the full error message?   Is the error in your browser?   Can you perhaps attach the html and js output too?

**Comment by LGCoding** [comment]
[Archive.zip](https://github.com/emscripten-core/emscripten/files/10162010/Archive.zip)
Yes, the error is in the browser.

**Comment by sbc100** [comment]
So where is the syntax error exactly?    Is it in the html of the JS?     I don't see any html file in the archive.. only the .js and the .wasm.

**Comment by sbc100** [comment]
(BTW, you probably want to add a `\n` to end of your printf string so that it actually goes to stdout.

**Comment by LGCoding** [comment]
[hello_world.html.zip](https://github.com/emscripten-core/emscripten/files/10165871/hello_world.html.zip)
Oh, sorry, I forgot to add the HTML file. The error is in the javascript console. I have also tried using a different HTML file that just has a canvas and the scripts, but that gave the same error.
