### ISSUE TITLE
onRuntimeInitialized called on Chrome but not Safari

### ISSUE THREAD

**Issue by stevedekorte** [emscripten-core/emscripten#18357]
This FAQ says Module.onRuntimeInitialized will be called when everything is ready:
https://emscripten.org/docs/getting_started/FAQ.html?highlight=onruntimeinitialized

This works for me on Chrome, but not on Safari. 

My emscripten compiled&linked x.js file has the line:

    if (Module["onRuntimeInitialized"]) Module["onRuntimeInitialized"]();

In Chrome, Module["onRuntimeInitialized"] returns the function I defined in the file that calls:

    Module['onRuntimeInitialized'] = function () { console.log("got it!") }
    import initModule from "./x.js";
    initModule(Module)

But in Safari, Module["onRuntimeInitialized"] returns undefined.
I can manually edit the x.js file to call some other global function, but it would be nice if it worked as described in the FAQ.

My emcc version is:
% emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.27 (afa75f342eef4d925172479afa8e6233eb0ae5a9)
clang version 16.0.0 (https://github.com/llvm/llvm-project dee009d3b5c71a340eb4ebb3cfb49f6015a789cc)
Target: wasm32-unknown-emscripten
Thread model: posix

**Comment by sbc100** [comment]
That should certainly works the same in both cases.

How/where/when are you setting `onRuntimeInitialized`?

**Comment by stevedekorte** [comment]
I've put together a minimal demo project you can use to verify the bug:

https://github.com/stevedekorte/onRuntimeInitialized_test

**Comment by kripken** [comment]
What happens on Firefox?

**Comment by stevedekorte** [comment]
It works on Firefox. Note: you can click on this link to test it on any browser:

https://stevedekorte.github.io/onRuntimeInitialized_test/

**Comment by kripken** [comment]
Thanks. Ok, hopefully someone with Apple hardware can try to confirm the problem on Safari. Worth seeing if there is anything odd in the dev console when it fails there.

If we can't figure this out then it would likely be a WebKit bug, and the right next step could be to open an issue there.

**Comment by stevedekorte** [comment]
Perhaps the way Module is defined could be simplified? It seems a bit complicated and confusing, at least to me.

**Comment by sbc100** [comment]
Yes, I also find it a little confusing/complicated.  If we can find a way to simplify that would be great, but its most likely non-trivial due to so much history/legacy with in emscripten.. we don't want to break existing users if possible.

**Comment by stevedekorte** [comment]
This line in the emcc produced .js file seems to be problem:

```
  var Module = typeof Module != "undefined" ? Module : {};
```

This appears (on Safari) to silently overwriting the argument passed by "async function(Module)".
 I'd suggest replacing:

```
async function(Module) {
  Module = Module || {};

  var Module = typeof Module != "undefined" ? Module : {};
```

with:

```
async function(Module = {}) {
```

For now, I can hack my build script to do this.

**Comment by sbc100** [comment]
Those sound like good ideas.    There could be reason we don't do that already (IIRC that part of the codegen is already pretty complex), but certainly worth trying.   @RReverser wdty?

**Comment by RReverser** [comment]
> This appears (on Safari) to silently overwrite the argument passed by "async function(Module)".

Wat. How did Safari miss this? It's clearly a bug / a violation of JS spec :/

Out of curiousity, if you try an isolated example like this

```js
(function foo(bar) { var bar=bar; console.log(bar) })(42)
```

what does it print in Safari?

But yeah, the suggested fix makes sense to me.

**Comment by sbc100** [comment]
`(function foo(bar) { var bar=bar; console.log(bar) })(42)` does print 42 on safari

**Comment by stevedekorte** [comment]
If I reduce my emcc compiled js file to:

```
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
    async function(Module) {
      console.log("Module 1:", Module);
      Module = Module || {};
      console.log("Module 2:", Module);
      var Module = typeof Module != "undefined" ? Module : {};
      console.log("Module 3:", Module);
      return Module.ready
    }
  );
})();
export default Module;

```
And my file which imports it to:

```
import initModule from "./test.js";
initModule({ foo: 42 });
```

the console log on Safari is:
```
[Log] Module 1: – undefined (test.js, line 7)
[Log] Module 2: – {} (test.js, line 9)
[Log] Module 3: – {} (test.js, line 11)
```

the console log on Chrome is:
```
iovm_test.js:7 Module 1: Object foo: 42[[Prototype]]: Object
iovm_test.js:9 Module 2: Object foo: 42[[Prototype]]: Object
iovm_test.js:11 Module 3: Object foo: 42[[Prototype]]: Object
```

**Comment by RReverser** [comment]
That's so weird... maybe it's `async` function specifically that has this bug? What if you try to remove it and make it a simple function?

**Comment by RReverser** [comment]
Too bad I don't have access to Safari, it'd be interesting to try and reduce this JS further.

**Comment by sbc100** [comment]
Is there some kind of compiler explorer thing but for JS engines?

**Comment by stevedekorte** [comment]
Btw, while I have the ear of some experienced emscripten folks here, could anyone point me to how to set up VSCode so I can debug my emcc compiled C code such that I can see the C locals and step though C function statements instead of seeing the WASM ASM registers and stepping through WASM instructions? If this is possible, I'd like to move my C projects to target emscripten by default.

**Comment by sbc100** [comment]
@RReverser you could do `jsvu --engines=javascriptcore` .. sadly it looks like there is a bug in the current jsvu that prevents installing on linux64: https://github.com/GoogleChromeLabs/jsvu/issues/126

**Comment by sbc100** [comment]
> Btw, while I have the ear of some experienced emscripten folks here, could anyone point me to how to set up VSCode so I can debug my emcc compiled C code such that I can see the C locals and step though C function statements instead of seeing the WASM ASM registers and stepping through WASM instructions? If this is possible, I'd like to move my C projects to target emscripten by default.

The only way that I know of to get a better debugging experience is to use the chrome devtools plugin: https://developer.chrome.com/blog/wasm-debugging-2020/

As far as I know there is no way (yet) to make the work in VSCode.

**Comment by RReverser** [comment]
> @RReverser you could do `jsvu --engines=javascriptcore` .. sadly it looks like there is a bug in the current jsvu that prevents installing on linux64: [GoogleChromeLabs/jsvu#126](https://github.com/GoogleChromeLabs/jsvu/issues/126)

Oh right, forgot about jsvu.

**Comment by RReverser** [comment]
Yeah can reproduce in raw JSC:

```js
var Module = (() => {
	return (
	  async function(Module) {
		print("Module 1:", Module);
		Module = Module || {};
		print("Module 2:", Module);
		var Module = typeof Module != "undefined" ? Module : {};
		print("Module 3:", Module);
	  }
	);
  })();
Module({ foo: 42 }).then(print, print);
```

```
Module 1: undefined      
Module 2: [object Object]
Module 3: [object Object]
undefined
```

**Comment by RReverser** [comment]
And yeah, seems limited to async functions. I'll try to report upstream, but for those curious here's minimal repro:

```js
async function initModule(foo) {
	var foo = foo || 'bug';
	print(foo);
}

initModule('ok');
```

Prints 'ok' in V8, 'bug' in JSC.

**Comment by sbc100** [comment]
> And yeah, seems limited to async functions. I'll try to report upstream, but for those curious here's minimal repro:
> 
> ```js
> async function initModule(foo) {
> 	var foo = foo || 'bug';
> 	print(foo);
> }
> 
> initModule('ok');
> ```
> 
> Prints 'ok' in V8, 'bug' in JSC.

Woah.. looks like a fairly serious bug.  So it only happens with async function and it only happens when there is a var inside that has the same name as one of the arguments?

Does it happens if async function is called from something other than the global scope?

**Comment by RReverser** [comment]
> So it only happens with async function and it only happens when there is a var inside that has the same name as one of the arguments?

Yeah I guess that's why it was never caught - it requires a certain combination of things to happen at once.

> Does it happens if async function is called from something other than the global scope?

Yeah the scope doesn't matter, as you can see I already unwrapped IIFE, even though in the original it was enclosed and still reproduced.

**Comment by RReverser** [comment]
Ah, in the process of submitting found an existing bug report... submitted almost 2 years ago. Webkit being Webkit 😢 https://bugs.webkit.org/show_bug.cgi?id=223533

**Comment by stevedekorte** [comment]
> @stevedekorte Do you want to submit a fix/workaround PR meanwhile? Seems like a good opportunity for a contribution.

@RReverser I tried to find out where that code is generated, but searching my emscripten source didn't turn up anything.

**Comment by RReverser** [comment]
You want to look at shell.js template (around here https://github.com/emscripten-core/emscripten/blob/efc18ae6e268373ff984d1622979422f99f3db0a/src/shell.js#L39) and preamble.js + postamble.js in the same dir.

**Comment by kleisauke** [comment]
This `async` function is only emitted for multi-environment ES6 builds since Emscripten version 3.1.27.
https://github.com/emscripten-core/emscripten/blob/fa10d78251ff1b7766988d0b76e1e80b01f4c326/emcc.py#L3761-L3766

So, a possible workaround is to also build with `-sENVIRONMENT=web`.

**Comment by martinbooth** [comment]
> Ah, in the process of submitting found an existing bug report... submitted almost 2 years ago. Webkit being Webkit 😢 https://bugs.webkit.org/show_bug.cgi?id=223533

Yeah.. this broke messenger on facebook.com for days.. maybe I could have emphasized the impact of this bug a bit more to try and get it fixed.. we also had to work around it by changing our minifier for safari only

**Comment by stevedekorte** [comment]
Where is the initModule function created and put into the global namespace? I don't see it anywhere.

**Comment by RReverser** [comment]
@stevedekorte How is it going? Given the severity, we probably want to fix this soon-ish, so if you don't have time to work on this bug, please let us know.

**Comment by stevedekorte** [comment]
I'm recovering from Covid at the moment, but can probably take a look at it later next week.

**Comment by RReverser** [comment]
@stevedekorte That's rough, sorry to hear. Maybe it's best if someone else takes a look for now.
