### ISSUE TITLE
Add return value to `emscripten_proxy_async_with_callback`

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#18378]
For my use case in #18376 it would be useful to have a `void*` return value for the function being proxied.  I would like to be able to then use the in my callback.

**Comment by sbc100** [comment]
I can work around this by defining a new "pair" struct and stashing the result in that.. but its less elegant.

**Comment by tlively** [comment]
Would you want the new callback argument to replace the current `callback_arg` chosen by the initial caller or to be passed alongside it?

IMO it would make sense to pass both, but then there is the usability downside of having two void* arguments that can be confused.
