### ISSUE TITLE
emcc generates large amount of unused boilerplate JS code for small amount of C code

### ISSUE THREAD

**Issue by JamesDunne** [emscripten-core/emscripten#1838]
My emcc command-line is:

```
emcc c_files_here -o output.js -s TOTAL_STACK="192" -s TOTAL_MEMORY="2048" -s FAST_MEMORY="2048" -s EXPORTED_FUNCTIONS="[my functions here]"
```

This gives me a JS file size of 142KB. That's exceedingly large, in my opinion. My C code compiles to just 363 lines of JS code (about 7KB), whereas the remainder of the enormous generated JS code, 3247 lines, is almost all unused boilerplate code. My C code does not use any emscripten features at all. It is just portable logic and uses no dependencies or external libraries.

I toyed with `-O2` but it only made my code broken because the functions I declared as `extern` to be defined in JS were complained about being missing:

```
function _externed_function() {
Module['printErr']('missing function: externed_function'); abort(-1);
}
```

That seems like a bug to me; extern functions should always be externally "linkable" regardless of optimization. Also, -O2 did not reduce any of the boilerplate code.

I added `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['memcpy','memset','malloc','free','strlen']"` to my emcc commandline (i.e. removing the `'$Browser'` element from `src/settings.js`).

This significantly reduced the file size to just 53KB, a considerable improvement for sure, but even 53KB is still too large in my opinion. I really just want my portable and independent C code to be compiled to a minimal JS module with no bells or whistles.

**Is there no other way to reduce the generated size by chopping out bits of boilerplate?** Obviously I don't want to hack up emscripten itself because I want a clean upgrade path. I'd like to see more emphasis on reducing generated code size and even optimizing for it. Outlining is fine but it's not an issue in my code; the excessive amount of boilerplate is.

**Also, is there a nice way to define JS-exported functions in my C code as opposed to supplying the EXPORTED_FUNCTIONS list on the emcc commandline?** I pored over what little documentation there is but couldn't find anything like this.

I don't mean to sound whiny; this is a great project and I'm loving the results!

**Comment by makc** [comment]
is there any official advice on this?
```
-s LINKABLE="1" -O2 --closure 1
```
actually blows the file up to 1.3MB now, where
```
 -O2 --closure 1
```
generates 115KB (both also have --bind and --memory-init-file 0). All I am compiling here is this cpp:
```
int test() {
	return 42;
}

#include <emscripten/bind.h>
using namespace emscripten;
EMSCRIPTEN_BINDINGS(my_module) {
	function("test", &test);
}
```
with these pre/post js:
```
window['Some'] = (function () {
...
	return Module;
}) ();
```
yet there are things like d.da("/tmp");d.da("/home");d.da("/home/web_user")}, which are surely not used.

**Comment by makc** [comment]
by getting rid of --bind magic in favor of exprort "C" / -s EXPORTED_FUNCTIONS="['_test']" I was able to go down to 85KB from 115 above, but still nowhere near 16KB that are claimed here.

**Comment by makc** [comment]
and adding this
```
-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['memcpy','memset','malloc','free','strlen']"
```
only cuts it down to 41KB.

**Comment by makc** [comment]
and DEFAULT_LIBRARY_FUNCS_TO_INCLUDE + bind = 71KB. I think I will try to stick with this way as it seem to give good compromise, but if there is anything else I can do - please give me the link.

**Comment by kripken** [comment]
`LINKABLE` disables all dead code elimination, so it will increase code size substantially.
