### ISSUE TITLE
-pthread generates code dependant on wasi_snapshot_preview1

### ISSUE THREAD

**Issue by ArthurMLago** [emscripten-core/emscripten#18396]
**Version of emscripten/emsdk:**
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.28 (f11d6196dd4e8748a726f19895c859b40ff6a4f3)
clang version 16.0.0 (https://github.com/llvm/llvm-project ea4be70cea8509520db8638bb17bcd7b5d8d60ac)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/arthurmlago/Desktop/emsdk/upstream/bin
```
**The problem:**
I'm trying to compile a webassembly module using STANDALONE_WASM, so I can instantiate it myself(no idea if that's good, just the way I started doing it when learning webAssembly). I also want to use threads and shared memories, so I USE IMPORTED_MEMORY and SHARED_MEMORY.

I'm using this simple code to demonstrate my problem:
```cpp
#include <math.h>
#include <stdlib.h>
#include <stdint.h>
#include <emscripten/emscripten.h>

extern "C" EMSCRIPTEN_KEEPALIVE int test_func(uint8_t* out){
    out[5] = 12;
    return 0;
}
```

And I'm trying to compile it with

```
emcc test_func.cpp -o test.wasm  --no-entry -s STANDALONE_WASM -s IMPORTED_MEMORY  -s SHARED_MEMORY=1 -O3
```

I get the error `error: library_pthread_stub.js:11: #error "STANDALONE_WASM does not support shared memories yet"`, which is weird since there is no mention of threads yet, but I believe it's unrelated(and might go away soon, due to https://github.com/emscripten-core/emscripten/pull/18355), since `test.wasm` is generated, and I can use it fine in my website!

However, when I try to use pthreads:
```
emcc test_func.cpp -o test.wasm  --no-entry -s STANDALONE_WASM -s IMPORTED_MEMORY  -s SHARED_MEMORY=1 -pthread -O3
```
Now suddenly test.wasm uses `wasi_snapshot_preview1` on multiple occasions:
```
$ wasm-objdump -d -s -x -h test.wasm  | grep wasi
 - func[0] sig=18 <wasi_snapshot_preview1.clock_time_get> <- wasi_snapshot_preview1.clock_time_get
 - func[1] sig=0 <wasi_snapshot_preview1.proc_exit> <- wasi_snapshot_preview1.proc_exit
 - func[3] sig=1 <wasi_snapshot_preview1.fd_close> <- wasi_snapshot_preview1.fd_close
 - func[4] sig=7 <wasi_snapshot_preview1.fd_write> <- wasi_snapshot_preview1.fd_write
 - func[5] sig=19 <wasi_snapshot_preview1.fd_seek> <- wasi_snapshot_preview1.fd_seek
 000971: 10 01                      | call 1 <wasi_snapshot_preview1.proc_exit>
 000abe: 10 00                      |   call 0 <wasi_snapshot_preview1.clock_time_get>
 003cc0: 10 03                      | call 3 <wasi_snapshot_preview1.fd_close>
 003d2b: 10 04                      |           call 4 <wasi_snapshot_preview1.fd_write>
 003db5: 10 04                      |           call 4 <wasi_snapshot_preview1.fd_write>
 003e44: 10 05                      | call 5 <wasi_snapshot_preview1.fd_seek>
0000171: 0e16 7761 7369 5f73 6e61 7073 686f 745f  ..wasi_snapshot_
0000191: 696d 655f 6765 7400 1216 7761 7369 5f73  ime_get...wasi_s
00001f1: 7761 7369 5f73 6e61 7073 686f 745f 7072  wasi_snapshot_pr
0000211: 0716 7761 7369 5f73 6e61 7073 686f 745f  ..wasi_snapshot_
```
These are not present in the version without `-pthread`, and then my browser complains about it when compiling. I'm aware that I could stub them(https://github.com/emscripten-core/emscripten/issues/17331 and https://github.com/emscripten-core/emscripten/issues/17705) but I'm not sure if this is the right course of action, or there is a bug, or if I'm doing something wrong. Either, since I'm not even using any thread in the code, only the `-pthread` flag, doesn't look like these should be required?

**Comment by sbc100** [comment]
If you look at the full output of `wasm-objdump -d`, you sahould be able to see what code is calling those imports.  You can also use `-Wl,--trace-symbol=foo` to see why a given symbol foo is getting included at link time. 

Using imports from `wasi_snapshot_preview1` is not surprising though, that is what standalone mode is supposed to use (so the output has a better chance of running under wasi runtimes).

**Comment by ArthurMLago** [comment]
`-Wl,--trace-symbol=foo` doesn't seem to help much:

```
 $ emcc test_func.cpp -o test.wasm  --no-entry -s STANDALONE_WASM -s IMPORTED_MEMORY  -s SHARED_MEMORY=1 -pthread -O3 -Wl,--trace-symbol=__wasi_clock_time_get
/home/arthurmlago/Desktop/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libstandalonewasm.a(clock_gettime.o): reference to __wasi_clock_time_get
```
```
 $ emcc test_func.cpp -o test.wasm  --no-entry -s STANDALONE_WASM -s IMPORTED_MEMORY  -s SHARED_MEMORY=1 -pthread -O3 -Wl,--trace-symbol=__wasi_fd_close
/home/arthurmlago/Desktop/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc-mt.a(__stdio_close.o): reference to __wasi_fd_close
```
They all point places that are not in my code, and I'm not that experienced yet to read disassembled code and figure out who's who yet.

As I understand, that's what standalone is supposed to use when it needs them, but should it need them? Again, I'm new to this, but isn't this the correct way to compile my code to be instantiated by my own javascript in a browser? There is no way for me to implement `fd_close` there, right?  I wouldn't be surprised if I was doing this all wrong though(does it even make sense to prefer the standalone instead of using the JS glue code?)

**Comment by sbc100** [comment]
Unless you have good reasons not to I would use the generates js code.  Otherwise you will likely end up having to do a lot more work.

Separately I ages it seem odd that all those imports are needed... we should figure out why

**Comment by sbc100** [comment]
I tracked down the reason for the extra code and it comes down the compiler asking for these extra exports:
https://github.com/emscripten-core/emscripten/blob/7fa75206c3876cb1df807b70150ff80601df7c9d/emcc.py#L1627-L1635

Pretty much all pthread-based programs in emscripten require these to be exported.

**Comment by sbc100** [comment]
The simplest solution here might just be to remove these 3 lines so you can build with `SHARED_MEMORY` but without `-pthread`: https://github.com/emscripten-core/emscripten/blob/7fa75206c3876cb1df807b70150ff80601df7c9d/src/library_pthread_stub.js#L10-L12

However if you do actually want to be able to start native pthread then you really will need to use the emscripten-generated JS, since there is lot of JS support code to make thread creation work.

**Comment by ArthurMLago** [comment]
Yeah, I actually wanted to use threads, so I guess I have some changes to make.

If it is intended behavior, there's nothing to be done, just seemed weird. Thank you very much for the clarification!
