### ISSUE TITLE
Calling JS callback from C thread

### ISSUE THREAD

**Issue by gabrik** [emscripten-core/emscripten#18390]
Hi, I'm trying to call a JS callback from a secondary thread spawned in C, but I get the following error:

```
worker.js onmessage() captured an uncaught exception: RuntimeError: index out of bounds [client.worker.js:205:8](http://localhost:9000/client.worker.js)
call_js_function@http://localhost:9000/client.wasm:wasm-function[135]:0x9187a
dynCall_ii@http://localhost:9000/client.wasm:wasm-function[9008]:0x3f94fd
instrumentWasmExports/</ret[x]@http://localhost:9000/client.js:16674:24
createExportWrapper/<@http://localhost:9000/client.js:861:20
invokeEntryPoint/result<@http://localhost:9000/client.js:4007:43
invokeEntryPoint@http://localhost:9000/client.js:4007:68
self.onmessage@http://localhost:9000/client.worker.js:160:16
EventHandlerNonNull*@http://localhost:9000/client.worker.js:103:1
```

The code is actually quite simple.

```C

#include <emscripten/emscripten.h>

typedef void external_js_method_t(const char *, size_t);

void* call_js_function(void* js_callback_ptr) {
    printf("JS callback is at: %p\n",js_callback_ptr);
    external_js_method_t *js_callback = (external_js_method_t*)js_callback_ptr;
    (js_callback)("Hello from C", 12);
}

EMSCRIPTEN_KEEPALIVE void call_js_function_on_another_thread(int js_callback_ptr) {

   pthread_t cb_thr;
   pthread_create(&cb_thr, 0, &call_js_function, (void*) js_callback_ptr);
}
```
and the JS is 
```javascript
Module.onRuntimeInitialized = async () => {
    const api = {
      call_js_function: Module.cwrap("call_js_function_on_another_thread", "", ["number"]),
    };
    
    var pointer = await Module.addFunction(function (data, len) {
      var data = Module.UTF8ToString(data, len);
      console.log("called from C - ", data);
    }, 'vii');


      api.call_js_function(pointer);
```

If I call the same function directly using the following C code everything works:
```C
void call_js_function(int js_callback_ptr) {
    printf("JS callback is at: %p\n",js_callback_ptr);
    external_js_method_t *js_callback = (external_js_method_t*)js_callback_ptr;
    (js_callback)("Hello from C", 12);
}
```
So I guess the issue comes from calling it from a thread that is not the main one. Unfortunately, as I'm porting a communication stack, user callbacks are going to be called by the thread that is reading on the network, and that comes from the C implementation that I cannot touch.
Any idea/suggestion?

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.28-git
clang version 16.0.0 (https://github.com/llvm/llvm-project.git ea4be70cea8509520db8638bb17bcd7b5d8d60ac)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/local/Cellar/emscripten/3.1.28/libexec/llvm/bin
```

**Failing command line in full:**
N/A

**Full link command and output with `-v` appended:**
Compile flags: `-sALLOW_TABLE_GROWTH -sPTHREAD_POOL_SIZE=8 -s ASYNCIFY=1 -s MAIN_MODULE=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s EXPORTED_RUNTIME_METHODS='[\"ccall\", \"cwrap\",\"UTF8ToString\"]' --bind -s ALLOW_MEMORY_GROWTH=1 -s USE_PTHREADS=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -lwebsocket.js`
Link flag: `-sALLOW_TABLE_GROWTH -s RESERVED_FUNCTION_POINTERS=100 -s ASYNCIFY=1 -s MAIN_MODULE=1 -s LINKABLE=1 -s EXPORT_ALL=1 `

**Comment by sbc100** [comment]
The problem is that `Module.addFunction` only works on the calling thread.  The resulting function pointer won't be valid on other threads.

Fixing `addFunction` so it works on all threads could be quite hard.  Can you avoid using `addFunction` by using JS library file?  (or my using EM_ASM or EM_JS?)

**Comment by gabrik** [comment]
Thanks, @sbc100 for the explanation. We cannot use `EM_ASM` or `EM_JS`, at least from what I got from the docs they are used to inline JS at compilation time.
In our case the callback is passed by user code, so if I got your suggestion right instead of using `addFunction` it should be possible to do something like this.


```JS
function data_cb(data, len) {
      var data = Module.UTF8ToString(data, len);
      console.log("called from C - ", data);
}
...
Module.onRuntimeInitialized = async () => {
   const api = {
       call_js_function: Module.cwrap("call_js_function_on_another_thread", "", ["number"]),
    };
    
     api.call_js_function(data_cb);
}
```

Am I right? Sorry but I'm not really a JS expert.

Because I tested it and I get this in the console

```
JS callback is at: 0 
[client.js:1380:8](http://localhost:9000/client.js)
worker.js onmessage() captured an uncaught exception: RuntimeError: indirect call to null
....
Pthread 0x00079688 sent an error! http://localhost:9000/client.wasm:596971: RuntimeError: indirect call to null
```

Seems like the reference to the function is not being passed to the C code, I'm pretty sure I'm doing it wrong.

**Comment by sbc100** [comment]
In your example `call_js_function` expects a number but `data_cb` is a JS function, so that won't work.

I suggest you do something like this to create your own mapping on integer  to JS function.

1. Create a JS library file that looks something like this:

```
mergeInto(LibraryManager.library, {
  // returns an integer that maps to the given JS function
  registerJSCallback: function(jsFunc) {
  },
  call_js_callback: function(id, other, args) {
    // lookup callback by id and call it.
  },
});
```

Then link with `--js-library=mylib.js`.  Then instead of calling `addFunction` you can use `registerJSCallback` and in your native code you would do `call_js_callback(js_callback, "Hello from C", 12);`

**Comment by sbc100** [comment]
If you use emscripten tot you could even use the new `handleAllocator` helper that was recently added in #18392

**Comment by gabrik** [comment]
Thanks, so in this case my "JS wrapper" will be called from C and is then this one that is going to actually call the JS function, make sense, we were anyway going to provide a JS wrapper over the WAMS and the `client.js`.

I'm going to test it and update this issue accordigly. 

Just out of curiosity, there is something I can put here 
```JS
call_js_function: Module.cwrap("call_js_function_on_another_thread", "", ["number"]),
``` 
Instead of `number` to pass a JS function?
I was using it as a way to pass references, but seems that is not the right thing to do.

**Comment by sbc100** [comment]
No, there is no way to pass a JS object or function to wasm... At least not today with emscripten.   You need to pass everything as numbers (pointers).

**Comment by sbc100** [comment]
My the way if you just want to run a function an another thread there are helpers for that in `emscripten/threading.h` that don't involve writing any JS at all.

**Comment by gabrik** [comment]
I'll have a look also at `emscripten/threading.h, thank you!

**Comment by gabrik** [comment]
I tried the JS library approach, but I'm pretty sure I'm doing something wrong (and the doc is not helping me out)

So I created a `func-wrapper.js` with this content:

```JS
var func_map = new Map()
var func_idx = 0

mergeInto(LibraryManager.library, {
    registerJSCallback: function(ke, fn){
        index = func_idx
        func_map.set(index, [ke, fn])
        func_idx++;
        return index;
    },
    call_js_callback: function(id, string_pointer, string_len){
        var [ke, fn] = func_map.get(id)
        fn(string_pointer, string_len)
    }
  });
```

Then in the C code I have 
```C
extern void call_js_callback(int, uint8_t*, int);

void* call_js_function(void* js_callback_id) {
    int js_callback = (int)js_callback_id;
    printf("JS callback ID is: %d\n",js_callback);
    call_js_callback(js_callback, "Hello from C", 12);
}

EMSCRIPTEN_KEEPALIVE void call_js_function_on_another_thread(int js_callback_id) {

   pthread_t cb_thr;
   pthread_create(&cb_thr, 0, &call_js_function, (void*) js_callback_id);
}
```


and in the HTML page calling all of this I have

```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>EM Test</title>
    <script type="text/javascript" src="client.js"></script>
    <script type="text/javascript" src="func-wrapper.js"></script>
</head>
<body>
Check browser console.

<script>

function data_cb (data, len) {
      var data = Module.UTF8ToString(data, len);
      console.log("called from C - ", data);
}

console.log("Calling code from Pico");
  Module.onRuntimeInitialized = async () => {
    const api = {
      call_js_function: Module.cwrap("call_js_function_on_another_thread", "", ["number"]),
    };


  var index = registerJSCallback("useless/for/the/time/being", data_cb);
  api.call_js_function(index);

  };

</script>

</body>
</html>
```

Building and linking are fine, but when opening the page I got this in the console.


```
Uncaught ReferenceError: mergeInto is not defined
```

Do I just need to link and then the symbols defined there will appear in the module generated when building?
In that case should I call `Module.registerJSCallback("useless/for/the/time/being", data_cb);`?

**Comment by gabrik** [comment]
Edit: I was able to call it, it was remapped to `_registerJSCallback`. Still some issues with the global variables I was using.

**Comment by sbc100** [comment]
You can'y use global variables like that in library JS functions.  You would need to create a new library entry for each global, and then add a dependency on it.  For an example see:  https://github.com/emscripten-core/emscripten/blob/bfabc4e0b82539ba46dfdd1675198dab32a25cfb/src/library_eventloop.js#L160

**Comment by gabrik** [comment]
Thank you, now both methods can access the "global variable", but seem that the one called form C does not have access to the same instance, the C calls the callback from a thread (created with pthread).

This is the code I have on the HTML page
```JS
function data_cb (data, len) {
      var data = Module.UTF8ToString(data, len);
      console.log("called from C - ", data);
}

console.log("Calling code from Pico");
  Module.onRuntimeInitialized = async () => {
    const api = {
      call_js_function: Module.cwrap("call_js_function_on_another_thread", "", ["number"]),
    };


  var index = Module.registerJSCallback("useless/for/the/time/being", data_cb);
  var index2 = Module.registerJSCallback("useless/for/the/time/being/2", data_cb);
  api.call_js_function(index);

  };
```

So I'm registering two times with the same callback and then asking C to call the first one.
I added some `console.log` for the map in order to see what was going on and on the browser I can see:

![Screenshot 2022-12-27 at 09 05 13](https://user-images.githubusercontent.com/4215504/209633444-0ac1a569-c0bc-4cfd-b75e-937201a37a83.png)

So seems that the two calls to `registerJSCallback` are using the same map, while the one to `call_js_function` is not.

I modified the JS library accordingly to what you shared:


```JS
mergeInto(LibraryManager.library, {
    $func_map: "new Map()",
    $func_idx: "0",
    $registerJSCallback__deps: ['$func_map', '$func_idx'],
    $registerJSCallback: function(ke, fn){
        index = func_idx
        func_map.set(index, [ke, fn])
        func_idx++;
        console.log(func_map, func_idx);
        return index;
    },
    call_js_callback__deps: ['$func_map', '$func_idx'],
    call_js_callback: function(id, value, ctx){
        console.log(func_map, func_idx);
        var [ke, fn] = func_map.get(id)
        fn(value, ctx)
    },
  });
  ```
  
  and indeed in the generated JS file I can see
  
  ```JS
  ...
    var func_map = new Map();
  Module["func_map"] = func_map;
  
  var func_idx = 0;
  Module["func_idx"] = func_idx;
  function _call_js_callback(id, value, ctx){
          console.log(func_map, func_idx);
          var [ke, fn] = func_map.get(id)
          fn(value, ctx)
      }
  Module["_call_js_callback"] = _call_js_callback;
  ...
    function registerJSCallback(ke, fn){
          index = func_idx
          func_map.set(index, [ke, fn])
          func_idx++;
          console.log(func_map, func_idx);
          return index;
      }
  Module["registerJSCallback"] = registerJSCallback;
  ...
  
  ```
  
  Do I need to change the way the JS code is called from C?

**Comment by gabrik** [comment]
Adding `    call_js_callback__proxy: 'sync',` to the library solves the above issue.

I'm keeping this open for the time being as I'm going now to test with a callback being called from an actual network thread.

**Comment by gabrik** [comment]
It works! Thank you very much @sbc100!
I'm closing this issue as everything seems fine now!

**Comment by abdullahaygun** [comment]
> It works! Thank you very much @sbc100! I'm closing this issue as everything seems fine now!

i am having the same problem. I haven't fix it out for days. can you help?

**Comment by sbc100** [comment]
Have you tried proxying your work back to the main thread?
