### ISSUE TITLE
undefined symbol: std::__2::__vector_base_common<true>::__throw_length_error() const

### ISSUE THREAD

**Issue by jinfagang** [emscripten-core/emscripten#18409]
using EMSdk toolchains to build got this error, does there any reason ?

**Comment by sbc100** [comment]
My first guess is that you upgraded from an older version but didn't rebuild all of your object files and libraries.

Can you give the full command line and the full error message?

**Comment by jinfagang** [comment]
it was because I linked with some .a from internet which might not consistent with my own PC's toolchain. I built it myself and then solved it.
