### ISSUE TITLE
MIN_CHROME_VERSION  not work on pthread worker file

### ISSUE THREAD

**Issue by sharemeans** [emscripten-core/emscripten#18437]
When compiled with pthread enabled, code below use "Nullish coalescing operator" which belongs to ecmascript 2020. 
https://github.com/emscripten-core/emscripten/blob/bfabc4e0b82539ba46dfdd1675198dab32a25cfb/src/worker.js#L113-L115
I need min support for chrome v78, legacy browser support option "MIN_CHROME_VERSION" seems not working.

**Comment by sbc100** [comment]
I think the assumption was that if you are targeting older versions of chrome like that you can't use wasm threads anyway.    Can chrome 78 use wasm shared memory?

**Comment by sbc100** [comment]
I guess the roadmap says threads are available from version 74, https://webassembly.org/roadmap/, but nullish coalescing isn't available until 80: https://caniuse.com/mdn-javascript_operators_nullish_coalescing.

I would be rather surprised if modern emscripten pthread code runs on chrome 78.  Can you confirm if you remove the nullish coalescing that it does? 

Should be and easy fix if it does work.

Either way we should error out if MIN_CHROME_VERSION is set too low in pthreads build.

**Comment by sharemeans** [comment]
> 

You are right. I remove the nullish coalescing and test on chrome 78 & 80, pthread code did not runs as expected(no error info).

Although shared array buffer is available on chrome 68+, maybe other compatibility problem exists.
