### ISSUE TITLE
-Wl,-[no]-whole-archive

### ISSUE THREAD

**Issue by arcanis** [emscripten-core/emscripten#1843]
Hi,

The whole-archive option is currently unused by em++, and it breaks some programs. Is there a workaround ?

Test repository : https://github.com/arcanis/issue.emscripten-whole-archive

**Comment by sbc100** [comment]
We recently ran into this.  I'll take a look at adding it.  Looks like we currently honor --start-group/--end-group but not whole-archive which seems strange.
