### ISSUE TITLE
HEAPF32 got values wrong

### ISSUE THREAD

**Issue by jinfagang** [emscripten-core/emscripten#18450]
```
HEAPU8.set(data, dst);
            HEAPF32.set(0., blendshapesArray);
            _run_export(dst, canvas.width, canvas.height, blendshapesArray);
            var result = HEAPU8.subarray(dst, dst + data.length);
            var resultBs = HEAPF32.subarray(blendshapesArray, blendshapesArray + 57);
            console.log('bs in js: ', resultBs)
```

the HEAPU8 is a image data, HEAPF32 is a vector float from wasm. 

the iamge return are right, but the HEAPF32 treturns here were wrong.

I set it to 0 at first, so it should be 0 if i didn't change it's values inside wasm, but the values fromn `HEAPF32.subarray`  are random.

Why?

**Comment by sbc100** [comment]
I assume you are aware that HEAPU8 and HEAPF32 are TypedArrays on the same backing store buffer?  So changes made through one view will effect the other if the offsets overlap?

Also, I assume the line `HEAPF32.set(0., blendshapesArray)` just sets a single element to zero.. is that what you intended?

**Comment by jinfagang** [comment]
@sbc100 hello, I have managed to retrive data successfully.
