### ISSUE TITLE
The wasm file was downloaded twice？

### ISSUE THREAD

**Issue by donghang1994** [emscripten-core/emscripten#18468]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.0.

During initialization, my wasm file was downloaded twice.  Because parsing failed in the ‘createWasm’ method，
`    function instantiateAsync() {
                    if (!wasmBinary && typeof WebAssembly.instantiateStreaming === "function" && !isDataURI(wasmBinaryFile) && typeof fetch === "function") {
                        return fetch(wasmBinaryFile, {credentials: "same-origin"}).then(function (response) {
                            var result = WebAssembly.instantiateStreaming(response, info);
                            return result.then(receiveInstantiationResult, function (reason) {
                                err("wasm streaming compile failed: " + reason);
                                err("falling back to ArrayBuffer instantiation");
                                return instantiateArrayBuffer(receiveInstantiationResult)
                            })
                        })
                    } else {
                        return instantiateArrayBuffer(receiveInstantiationResult)
                    }
                }`

in the function instantiateStreaming,report an error：“TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.”

The wasm file was downloaded again.so Is this a normal question？

**Comment by donghang1994** [comment]
![1672888438423](https://user-images.githubusercontent.com/91657327/210694648-69d34729-436d-4db8-b97e-eef3910b6d28.png)

**Comment by sbc100** [comment]
I don't know the detail of the code but it seem logical that if the stream instantiate fails then a new download would be required.

Can you fix the failure that caused instantiateStreaming to fail?

**Comment by donghang1994** [comment]
> I don't know the detail of the code but it seem logical that if the stream instantiate fails then a new download would be required.
> 
> Can you fix the failure that caused instantiateStreaming to fail?

Can't see why it instantiateStreaming failed.But Why not judge after the second download，I have a feeling we're both going to fail in our wasm file judgment.

**Comment by sbc100** [comment]
The error says `：“TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.”`.. so I assume you server needs to have the mime type fixed?

**Comment by donghang1994** [comment]
> The error says `：“TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.”`.. so I assume you server needs to have the mime type fixed?

Do not want to configure service Settings，Should I use the "instantiate" method instead of "instantiateStreaming", How do I compile that.

**Comment by sbc100** [comment]
Just to be clear, your wasm module is being successfully loaded, but only have a first, failed attempt at instantiateStreaming?    And you want to just skip that and go direct to instantiateArrayBuffer?

I don't think there is any official way to do that using emscripten.  Looking at the code it looks like you might be able to do `WebAssembly.instantiateStreaming = undefined` in your `pre.js` to convince the code to skip that path:

https://github.com/emscripten-core/emscripten/blob/de13451bd0ee7ee6b8d1327a0d5a2a7051e98b73/src/preamble.js#L1006-L1009

**Comment by donghang1994** [comment]
> Just to be clear, your wasm module is being successfully loaded, but only have a first, failed attempt at instantiateStreaming? And you want to just skip that and go direct to instantiateArrayBuffer?
> 
> I don't think there is any official way to do that using emscripten. Looking at the code it looks like you might be able to do `WebAssembly.instantiateStreaming = undefined` in your `pre.js` to convince the code to skip that path:
> 
> https://github.com/emscripten-core/emscripten/blob/de13451bd0ee7ee6b8d1327a0d5a2a7051e98b73/src/preamble.js#L1006-L1009

Very thankful，I configured the mime type “pplication/wasm” for the server，The wasm file is only downloaded once；
I find that the size of the browser download wasm file is getting smaller,This is why.
![1672933716533](https://user-images.githubusercontent.com/91657327/210823307-0249cb81-3cdb-486c-adfd-703df0e4db1b.jpg)

**Comment by donghang1994** [comment]
This is the original effect，The download size is the size of the entire file.
![1672934106322](https://user-images.githubusercontent.com/91657327/210824122-52dcc3e8-2de2-4aeb-941e-ba3497c5c7de.jpg)

**Comment by sbc100** [comment]
Perhaps you got a cache hit in the browser.  The wasm file on the server is still 14.7 Mb I assume, that won't change.

**Comment by donghang1994** [comment]
> Perhaps you got a cache hit in the browser. The wasm file on the server is still 14.7 Mb I assume, that won't change.

Oh, that's right!!
