### ISSUE TITLE
Linking problem in generated JS code

### ISSUE THREAD

**Issue by bztsrc** [emscripten-core/emscripten#18473]
Hi,

This used to work, but I've updated emscripten, and ever since the generated JS throws an error:
```
Aborted(Assertion failed: Invalid character 106("j") in readAsmConstArgs! Use only [d,f,i], and do not specify "v" for void return argument.)
```
The best part is, it's not my code that causes this, but one of *your emscripten libraries* (I'm assuming it's SDL maybe, in SDL_video.c most likely, but I'm not sure). I wanted to track it down, but using `wasm-objdump` it is completely impossible to identify the faulting function... That's all I can see:
```
 - func[2213] sig=112 <dynCall_iidiiii>
 - func[2214] sig=10 <dynCall_jiji>
 - func[2215] sig=3 <dynCall_ji>
 - func[2216] sig=10 <dynCall_iiji>
 - func[2217] sig=24
 - func[2218] sig=0 <asyncify_start_unwind>
```
I've also tried to add `console.log` to the generated JS code, but all I can see is, it's in `exports[x]` array, and:
```
dynCall_jiji function 2214() {
    [native code]
}
```

Suggested solution: please fix your emscipten compiler to generate a JS wrapper that accepts `j` as argument, if your own libraries are generating such reference... Or rewrite your libraries not to use `j` argument type, however that's very difficult as your debugger can't tell which function has it...

Cheers,
bzt

**Comment by bztsrc** [comment]
Few more bugs related to this: when compiled with `-g`, then I still can see these prototypes (and still no more info where these are located in the source...):
```
 - func[2306] sig=113 <dynCall_iidiiii>
 - func[2307] sig=3 <dynCall_ji>
 - func[2308] sig=10 <dynCall_jiji>
 - func[2309] sig=10 <dynCall_iiji>
 - func[2310] sig=24
 - func[2311] sig=0 <asyncify_start_unwind>
 - func[2312] sig=5 <asyncify_stop_unwind>
 - func[2313] sig=0 <asyncify_start_rewind>
 - func[2314] sig=5 <asyncify_stop_rewind>
 - func[2315] sig=6 <asyncify_get_state>
Table[1]:
 - table[0] type=funcref initial=796 max=796
```
But interestingly the **assertation does not occur** this time, no errors, everything works in the browser. I must stress that the only difference was using `-g`, which should not influence the generated functions nor the code (it is supposed to add additional debug info that's all, and I still see `j` in the prototype). What's going on?

Cheers,
bzt

**Comment by bztsrc** [comment]
Digging deeper just revealed even more bugs... I've linked with `-s WASM_BIGINT`, now the error message says:
```
Uncaught TypeError: can't convert BigInt to number
```
Interestingly, just as before, compiling with `-g` works....

Cheers,
bzt

**Comment by sbc100** [comment]
What version of emscripten are you using?  What was that last version when it worked?  

Can you try with the latest version (3.1.29 was just released).

Interestingly  `readAsmConstArgs` was renamed to #18218 which made it into the 3.1.27 release.  So if you using 3.1.27 then something very odd is going on.

Can you try making sure that all your object files and libraries are rebuilt on upgrade?

Also, `readAsmConstArgs` relates to EM_ASM constants which are unrelated to the `dynCall` functions.

**Comment by sbc100** [comment]
'j' is indeed an invalid argument type when `WASM_BIGINT` is not defined: https://github.com/emscripten-core/emscripten/blob/0d7014e1b20ead9739f1fce54b316152413601c3/src/library.js#L2945-L2948.

The `j` in the EM_ASM signature represents a `long long` or `int64` argument and as far I know has never worked with WASM_BIGINT support.  We even have test to check that it fails in this way without WASM_BIGINT:

https://github.com/emscripten-core/emscripten/blob/0d7014e1b20ead9739f1fce54b316152413601c3/test/test_other.py#L7077-L7081

Can you see which EM_ASM function is causing the issue (I imagine you should be able to tell from the backtrace)?  Can you share it, or its signature here?

**Comment by bztsrc** [comment]
Thank you for your answer!

> What version of emscripten are you using?

I'm using the latest that my distro ships, 3.1.26-git 8eaf19fc6a9a1b0

> What was that last version when it worked?

Maybe I wasn't clear. It's not the emscripten upgrade that was problematic, but when I executed `emcc` for the first time after the upgrade with an internet connection it automatically upgraded all the libraries and that's when the issue was introduced. I don't know what the libraries version were, but about half a year ago it was working for sure, and it was working with the latest emcc before the lib upgrade too.

> Can you try making sure that all your object files and libraries are rebuilt on upgrade?

I'm sure those are the latest, actually that's what caused the trouble. The problem appeared after the library upgrade.

> Also, readAsmConstArgs relates to EM_ASM constants which are unrelated to the dynCall functions.

Not exactly, some of the emscripten libraries have `EM_ASM` calls in them and those libraries are producing such exports. Sorry I can't tell exactly which one, but I've narrowed it down to SDL or ogg. One of those have an exported function with a `j` in it. I'm trying to create a minimal example with ogg only, but that's not easy because currently I'm using it through SDL_mixer which depends on SDL.

> Can you see which EM_ASM function is causing the issue (I imagine you should be able to tell from the backtrace)?

Yeah, that's my other problem. It is not shown in any backtrace, not even if I compile with `-g`. If you know a way how to display it, please let me know.
```
Uncaught RuntimeError: Aborted(Assertion failed: Invalid character 106("j") in readAsmConstArgs! Use only [d,f,i], and do not specify "v" for void return argument.)
    abort file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1016
    assert file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:486
    readAsmConstArgs file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:5242
    _emscripten_asm_const_int file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:5255
    x file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:8114
    x file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:8148
    createExportWrapper file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1061
    browserIterationFunc file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:7557
    callUserCallback file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:4052
    runIter file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:4104
    Browser_mainLoop_runner file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:4018
    setTimeout handler*Browser_mainLoop_scheduler_setTimeout file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:3838
    setMainLoop file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:4038
    _emscripten_set_main_loop file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:7558
    x file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:8114
    x file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:8148
    createExportWrapper file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1061
    callMain file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:9317
    doRun file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:9371
    run file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:9386
    runCaller file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:9294
    removeRunDependency file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:979
    receiveInstance file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1151
    receiveInstantiationResult file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1169
    promise callback*instantiateArrayBuffer file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1177
    instantiateAsync file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1221
    createWasm file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:1240
    <anonymous> file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:8761
tngp.js:1016:11
```
I've put lots on `console.log` in the generated code (in `createExportWrapper`, `_emscripten_asm_cont_int` and in `readAsmConstArgs`), but couldn't figure out which exported function causes it (other than it is `func[2214]`).

> 'j' is indeed an invalid argument type when WASM_BIGINT is not defined

That's okay, the problem is, one of the updated libraries has it now, so requiring the `-s WASM_BIGINT` linker flag is mandatory but non-intuitive, and not checked in compile time. It should be simply the default IMHO (considering one of the libraries needs it anyway). Or at least a compile time warning (when more info about the faulting function available than in run-time) would be nice.

Thank you for your help! For the records, using `-s WASM_BIGINT` linker flag solved my issue, it was just hard to figure out that from now on it's required.

Cheers,
bzt

**Comment by bztsrc** [comment]
Ok, I did a through check, you can download and test the wasm binaries from here:
- 6 months ago: [this](https://codeberg.org/tirnanog/pages/commit/422354538a0b7e4985a00f92b57b8a92a5422863) commit was the last that was working before the lib upgrade
- 4 weeks ago: [this](https://codeberg.org/tirnanog/pages/commit/5f70f969f5434c4eb9b6c1775359c429e31cb88a) commit was the first one with the upgraded libraries and failed assert. (As you can see, my code hasn't changed, and there's no other commits in between)
- yesterday: [this](https://codeberg.org/tirnanog/pages/commit/eab82260af5d4b8d87b228d8caba27923ecf461f) commit is the one *without* `-s WASM_BIGINT` but *with* `-g` that surprisingly works (even though it has `j`).

What I don't understand, how come that with `-g` it works even without bigint support? You can debug that, but TBH I think it would be the best just to make `WASM_BIGINT` the default (and maybe introduce `WASM_NO_BIGINT` to get the current behaviour for those who really don't want `int64` support).

Also I think if compiled with `-g` then `wasm-objdump` should display the source file and line reference next to the functions (not just `func[2307] sig=3 <dynCall_ji>`), that would be extremely helpful.

Cheers,
bzt

**Comment by bztsrc** [comment]
> Firstly, 3.1.26-git 8eaf19fc6a9a1b0 doesn't exist in the emscripten repo 

Yes, it does exists, and as it happens, YOU were the one who commited it.
https://github.com/emscripten-core/emscripten/commit/8eaf19f1c6a9a1b0cd0f9a91657366829e34ae5c

> Again dynCall_ji is not related to EM_ASM and therefore likely not related to your crash.

Then what is generating those functions if not EM_ASM?

> In your backtrace I only see JS functions.

Yes, because the emscripten generated JS crashes before it could run the wasm. This issue is happening entirely in emscripten's territory, my wasm compiled code doesn't even have a chance to run.

> What do you see at x file:///home/bzt/Documents/sources/tirnanog/player/emscripten/tngp.js:8114 ? Are those functions really called x or are you modifying the backtrace to hide the real names?

Yes, those functions are really called `x`, that's the name emscripten gave to that function... And you can see the source on the links I gave.

> are you modifying the backtrace to hide the real names?

What the f* are you talking about? With this attitude no wonder emscripten is such a mess.

Do as you please. I've reported the issue, provided all the information, even dates and git history, links to sources that reproduce the issue, etc. etc. etc. It is up to you if you fix it, please don't waste my time any further. Thanks.

Cheers,
bzt

**Comment by sbc100** [comment]
> > Firstly, 3.1.26-git 8eaf19fc6a9a1b0 doesn't exist in the emscripten repo
> 
> Yes, it does exists, and as it happens, YOU were the one who commited it. [8eaf19f](https://github.com/emscripten-core/emscripten/commit/8eaf19f1c6a9a1b0cd0f9a91657366829e34ae5c)

That is strange `git show 8eaf19f` seems to work but not `8eaf19fc6a9a1b0`

```
$ git show 8eaf19fc6a9a1b0
fatal: ambiguous argument '8eaf19fc6a9a1b0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Oh I see.. there is 1 missing after the `c` in the SHA you shared: `8eaf19fc6a9a1b0`... can you confirm that emscripten is not actaully reporting the sha with missing 1?  Just in case something odd is going on.

**Comment by sbc100** [comment]
> > are you modifying the backtrace to hide the real names?
> 
> What the f* are you talking about? With this attitude no wonder emscripten is such a mess.

Not trying to be rude.  Some people do like to do that when reporting bugs (to avoid exposing thier IP I suppose).  Not offence meant.

**Comment by sbc100** [comment]
> > Again dynCall_ji is not related to EM_ASM and therefore likely not related to your crash.
> 
> Then what is generating those functions if not EM_ASM?

dynCall imports IIRC are most often generated when using C++ exceptions and/or setjmp/longjmp.    They are not used in the implementation of EM_ASM.

**Comment by bztsrc** [comment]
> Not trying to be rude.

Surely sounded like it.

> Some people do like to do that when reporting bugs (to avoid exposing thier IP I suppose).

Not here, I'm working on a FOSS app.

> Not offence meant.

Apology accepted.

> dynCall imports IIRC are most often generated when using C++ exceptions and/or setjmp/longjmp.

This is a pure ANSI C project, no C++ exceptions. And I did a grep, no longjmp either.

> They are not used in the implementation of EM_ASM.

Then why does `readAsmConstArgs` checking that function? I mean in the first test case the argument to it was obviously `function 2214()` and from the wasm-objdump that function's prototype is undeniably `dynCall_jiji`. Just a theoretical question.

Anyway, keep up the good work and fix emscripten. For now I know I always have to add `-s WASM_BIGINT` to the linker flags to get it working.

Cheers,
bzt
