### ISSUE TITLE
Is (binary) file redirection possible with emcc-compiled utilities? (Doesn't seem to work.)

### ISSUE THREAD

**Issue by geoff-nixon** [emscripten-core/emscripten#1847]
Hi — sorry to bug you with this, as I'm sure it is documented _somewhere_, but I'm a... newly converted believer (your keynote totally blew me away), and so here I am I  guess. Anyway: I'm trying to compile [xzminidec](https://gist.github.com/g-nix/7595928) (which I've concatenated here) from [xz-embedded](http://tukaani.org/xz/embedded.html). The file compiles fine, and lli and pNaCl do not have a problem with it. emcc doesn't protest at all either at any optimization or debug level; but its output fails to handle any file I try to pipe in.  (This utility _only_ streams from stdin to stdout.) So am I correct in assuming that the JS conversion process does not handle a traditional file pipeline particularly well? I did read the bit in the wiki about 'virtual stdin/stdout', but this is more suited towards TTY-style text redirection, no?

Is there any quick fix here? I suppose I could try adding file handlers the original code... or is this something better addressed by tweaking the javascript post-compile?

Thanks for your time.

**Comment by gallypette** [comment]
bump
