### ISSUE TITLE
Application, that doesn't built with dynamic link,  aborted on _emscripten_thread_sync_code ->_dlopen_js  

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#18478]
emcc 3.1.9
Windows 11.

My App is built staticly - without using MAIN\SIDE_MODULE and all the linkage Modules are static libs.
In some point, I get an Abort in _emscripten_thread_sync_code that trying to load a module by _dlopen_js despite of none 
dynamic link is done in the build process.

**Build command line:**
`C:\emsdk\upstream\emscripten\\emcc.bat Emscripten/Debug/TEApiWrapper80_for_emscripten.o Emscripten/Debug/Main.o -ljpeg.Emscripten -lxml2 -lprjplg.Emscripten -lproj -lgdal -lgeos -lgeos_c -l3ds.Emscripten -lTerraExplorerX.Emscripten -lCore.Emscripten -l7zip.Emscripten -llibzip.Emscripten -lgisplg.Emscripten -lMptDll.Emscripten -lOpenGL.Emscripten -lPlgShell.Emscripten -lSLLogger.Emscripten -lSLLoggerLib.Emscripten -lSLStrings.Emscripten -lTerraCommon.Emscripten -lTerra.Emscripten -lTESWQ.Emscripten -lWFSPlugin.Emscripten -lsl_png.Emscripten -ldraco.Emscripten -lOpenCTM.Emscripten -lwebp.Emscripten -lMPTPlg.Emscripten -s ALLOW_TABLE_GROWTH -s WASM_BIGINT  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap -s EXPORTED_FUNCTIONS=_main  -g  -gsplit-dwarf -gdwarf-5 -gpubnames --bind -s USE_PTHREADS -s ALLOW_MEMORY_GROWTH=1    -s EXIT_RUNTIME -s ASSERTIONS  -s FETCH   -s NO_DISABLE_EXCEPTION_CATCHING -s TEXTDECODER=0  -lidbfs.js -s PTHREAD_POOL_SIZE=60 -s ERROR_ON_WASM_CHANGES_AFTER_LINK -s REVERSE_DEPS=all -O0 --preload-file com.skyline.terraexplorer -o C:/Projects/TerraExplorer_v8_0_0_Dev/SLSource/Emscripten/Debug/TEW/TerraExplorerApp.Emscripten.js -LC:/Projects/TerraExplorer_v8_0_0_Dev/SLSource/Emscripten/Debug/ -LC:/Projects/TerraExplorer_v8_0_0_Dev/SLSource/Emscripten/TerraExplorerApp.Emscripten/libs`

**the crash:**
![image](https://user-images.githubusercontent.com/41375082/211195020-9208ba23-b48d-4c82-866b-81e797b68708.png)

**looking into dynlink.c:**

![image](https://user-images.githubusercontent.com/41375082/211195103-0cc441e0-c509-4ced-b3f7-dbd8f699cabd.png)

**_dlopen_js that do the abort:**
![image](https://user-images.githubusercontent.com/41375082/211195184-dd353841-5cae-428e-ac2b-9d59354a56e5.png)

**Comment by sbc100** [comment]
Can you confirm if this issue still exists with the latest version of emscripten (3.1.29)?

**Comment by aharondavid** [comment]
It a little bit complicate, because, I have a several Third Party Libs that compiled with 3.1..9 
I need to compile them also in 3.1.29 , it might take several hours to do.
do you have any idea about that issue and you think that 3.1.29 solve it?

**Comment by sbc100** [comment]
This issue does look vaguely familiar which means I think it could have been fixed.. but I didn't find the precise fix on first search through the history so I'm not 100% sure.

In theory, thread `thread_local_tail->next` should always be null until you call dlopen, do if you are never calling dlopen then you should never get into that block of code.

**Comment by sbc100** [comment]
Do you really have that much code that it takes hours to rebuild?  

In debugging issues like this (or indeed any emscripten issue) it is highly advantageous to have a setup where you can easily "rebuilt the world" with different version of emsdk.  If you have time to be able to setup such an environment I think it be worth you while.

**Comment by aharondavid** [comment]
I had build my App with 3.1.29 but I get an exception that thrown from getWasmTableEntry.
![image](https://user-images.githubusercontent.com/41375082/211588178-bd75bcd5-c9a1-4beb-8e36-68fb9fbfe084.png)

**Comment by sbc100** [comment]
That looks like a separate issue, right?    Would you mind closing this one assuming that original issue is fixed?

Regarding the `invoke_iii` crash its most likely the call to function that lives in the table that is throwing, rather than the getWasmTableEntry function itself.  You should get a stack trace from the exception which should show where it was originally thrown?

**Comment by aharondavid** [comment]
yes, you right.
by testing in 3.1.14, I can confirm that it solved in 3.1.14
Unfortunately, I cannot confirm that in 3.1.29 because this issue: https://github.com/emscripten-core/emscripten/issues/18488
