### ISSUE TITLE
Crashes when build with 3.1.29

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#18488]
When I upgrade from 3.1.14 to 3.1.29 I get a lot of unexpected crashes.
those weird crashes make me think that there is something wrong with 3.1.29.
I do get a call stack for those crashes, but the call stack doesn't point to a real problem in my code.
I can tell that when debugging my App in memory view, an allocated pointer 
is starting from address less then 0x10000 whereas in 3.1.9 it was greater then 0x10000.

OS: Windows 11

**Build command line:**
`C:\emsdk\upstream\emscripten\\emcc.bat Emscripten/Debug/TEApiWrapper80_for_emscripten.o Emscripten/Debug/Main.o -ljpeg.Emscripten -lxml2 -lprjplg.Emscripten -lproj -lgdal -lgeos -lgeos_c -l3ds.Emscripten -lTerraExplorerX.Emscripten -lCore.Emscripten -l7zip.Emscripten -llibzip.Emscripten -lgisplg.Emscripten -lMptDll.Emscripten -lOpenGL.Emscripten -lPlgShell.Emscripten -lSLLogger.Emscripten -lSLLoggerLib.Emscripten -lSLStrings.Emscripten -lTerraCommon.Emscripten -lTerra.Emscripten -lTESWQ.Emscripten -lWFSPlugin.Emscripten -lsl_png.Emscripten -ldraco.Emscripten -lOpenCTM.Emscripten -lwebp.Emscripten -lMPTPlg.Emscripten -s ALLOW_TABLE_GROWTH -s WASM_BIGINT  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap -s EXPORTED_FUNCTIONS=_main  -g  -gsplit-dwarf -gdwarf-5 -gpubnames --bind -s USE_PTHREADS -s ALLOW_MEMORY_GROWTH=1    -s EXIT_RUNTIME -s ASSERTIONS  -s FETCH   -s NO_DISABLE_EXCEPTION_CATCHING -s TEXTDECODER=0  -lidbfs.js -s PTHREAD_POOL_SIZE=60 -s ERROR_ON_WASM_CHANGES_AFTER_LINK -s REVERSE_DEPS=all -O0 --preload-file com.skyline.terraexplorer -o C:/Projects/TerraExplorer_v8_0_0_Dev/SLSource/Emscripten/Debug/TEW/TerraExplorerApp.Emscripten.js -LC:/Projects/TerraExplorer_v8_0_0_Dev/SLSource/Emscripten/Debug/ -LC:/Projects/TerraExplorer_v8_0_0_Dev/SLSource/Emscripten/TerraExplorerApp.Emscripten/libs
`

**Comment by sbc100** [comment]
This perhaps could be related to the reduced default stack size.   Can you trying building with `-sSTACK_SIZE=5mb` to see if that fixes it?   (Also add `-sDEFAULT_PTHREAD_STACK_SIZE=5mb`, at least until #18479 gets shipped).

Can you try bisecting (google "emscripten bisect") to find out which version caused the issue?

**Comment by aharondavid** [comment]
Ok, with those flags everything Ok, I can also confirm that the bug #18478 is not reproduced.
