### ISSUE TITLE
[WasmFS] Flush not reaching backend

### ISSUE THREAD

**Issue by goldwaving** [emscripten-core/emscripten#18491]
I am working on an IndexedDB backend.  To improve performance, writes are cached in the backend until a much large amount of data has been written.  However this causes a problem with flushing the cache.  Calls to flush (C++ fstream flush, for example) in the program don't always reach the backend.  It seems that if the layer above the backend believes it's buffers have been flushed, it will not attempt to flush the backend buffers.  If I close the file instead (which also flushes it on the backend) the file works as expected.

This problem typically occurs when exactly 4kb is written to the file, then flush is called.  Flush is not called on the backend, therefore the data does not get stored in the IndexedDB.  I'm also noticing that each 4kb write has a 0kb write as well.

**Comment by kripken** [comment]
Is this a backend for the JS FS, or WasmFS, or something else?

Either way, you may be seeing caching behavior in musl. At least I remember seeing similar things there. Looking in the code in `flush.c` might be a good starting point to debug this, if so.

**Comment by goldwaving** [comment]
This is for a WasmFS backend.  After studying this some more, perhaps this is the expected behaviour.  On other operating systems, flush is not propagated to lower (disk) level.  Other calls are required to flush/sync cached data to the disk.  

What is the correct way to sync the entire WasmFS file system, similar to FS.syncfs?

**Comment by kripken** [comment]
IIANM `fsync()` should do it. That calls `__wasi_fd_sync` which then calls the WasmFS `flush` method on DataFiles:

https://github.com/emscripten-core/emscripten/blob/087b0ece8957bd8b483253a86006ec65bdde61c7/system/lib/wasmfs/file.h#L151-L153

**Comment by goldwaving** [comment]
Thanks for suggestion!  Would be nice is there was a single call to sync the entire WasmFS file system, but I think we can close this issue.

**Comment by kripken** [comment]
Hmm, I thought `fsync(-1)` or such might do that, but it doesn't seem to be the case... Yes, perhaps it would be useful to add a WasmFS method, then. I opened https://github.com/emscripten-core/emscripten/issues/18514 now.
