### ISSUE TITLE
Difference between EXPORTED_RUNTIME_METHODS and DEFAULT_LIBRARY_FUNCS_TO_INCLUDE

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#18504]
AFAIU both of these are used for js library elements. If we want to export any js library element we can both use `EXPORTED_RUNTIME_METHODS` and `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` + `EXPORTED_FUNCTIONS`. Is there anything specific about these flags that I may be missing ?

**Comment by kripken** [comment]
Yes, there is some overlap here for historical reasons.

`DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` only includes the method in the build - you'll end up with `function foo() {}` for example. But note that it is not exported.

`EXPORTED_RUNTIME_METHODS` will also export it, by adding `Module['foo'] = foo;`. I believe it also includes it by default, these days, for convenience (but once you needed `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` to include it before exporting).

So, yes, `EXPORTED_RUNTIME_METHODS` is similar in effect to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` + exporting it using `EXPORTED_FUNCTIONS`.

**Comment by ravisumit33** [comment]
Thanks, got it.
