### ISSUE TITLE
support for std::binary_semaphore and std::counting_semaphore

### ISSUE THREAD

**Issue by fe-dagostino** [emscripten-core/emscripten#18506]
Please include the following in your bug report:

**Version of emscripten/emsdk: 3.1.28
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.28 (f11d6196dd4e8748a726f19895c859b40ff6a4f3)
clang version 16.0.0 (https://github.com/llvm/llvm-project ea4be70cea8509520db8638bb17bcd7b5d8d60ac)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
error: no type named 'binary_semaphore' in namespace 'std';

**Comment by sbc100** [comment]
binary_semaphore seems to be part of C++20.   Are you linking with `-std=c++20`?

**Comment by fe-dagostino** [comment]
I'm using    set(CMAKE_CXX_STANDARD 20) in my CMake  and this is the result

[build] /home/fedagostino/works/github/emsdk/upstream/emscripten/em++  -I/home/fedagostino/works/github/fe-dagostino/lock-free/include -I/home/fedagostino/works/github/fe-dagostino/lock-free/build/_deps/nanobench-src/src/include -g   -ggdb3 -march=native -mtune=native -Wall -Wextra -pedantic -std=c++20 -MD -MT benchmarks/CMakeFiles/bm_mt_arena_allocator.dir/bm_mt_arena_allocator.cpp.o -MF benchmarks/CMakeFiles/bm_mt_arena_allocator.dir/bm_mt_arena_allocator.cpp.o.d -o benchmarks/CMakeFiles/bm_mt_arena_allocator.dir/bm_mt_arena_allocator.cpp.o -c /home/fedagostino/works/github/fe-dagostino/lock-free/benchmarks/bm_mt_arena_allocator.cpp
[build] clang-16: warning: argument unused during compilation: '-march=native' [-Wunused-command-line-argument]
[build] clang-16: warning: argument unused during compilation: '-mtune=native' [-Wunused-command-line-argument]
[build] In file included from /home/fedagostino/works/github/fe-dagostino/lock-free/benchmarks/bm_mt_arena_allocator.cpp:5:
[build] /home/fedagostino/works/github/fe-dagostino/lock-free/include/core/arena_allocator.h:681:3: error: no type named 'binary_semaphore' in namespace 'std'; did you mean simply 'binary_semaphore'?

With both gcc and clang the same project build.  There is the same issue with 'syncstream' too, but I do not exclude that is my CMakefiles the cause of this issue. do you seem any parameter that is incopatible?  why do you refers to the liniking ? c++20 is supposed to be a compile flag, in fact  the issue is that compiler do not find any definition for std::binary_semaphore I do not reach linking stage. You can download the project if you want to try locally, it may help to understand if is my problem or something else.  

In case download/clone  **lock-free** repo and change  **core::binary_semaphore** to **std::binary_semaphore** in include/core/arena_allocator.h , if you try to build examples using em++ you will get the error.

**Comment by sbc100** [comment]
It seems to work for me (even without C++20 flag):

```
$ cat test.cpp 
#include <semaphore>

int main() {
  std::binary_semaphore foo{0};
  foo.acquire();
  return 0;
}
$ ./em++ test.cpp 
```

Does that example work for you?

**Comment by fe-dagostino** [comment]
Hi Sem, I confirm that your example is working, my mistake I didn't try before to open the issue, but all other functionalties related to c++20 was working, so I supposed a different error. I will check my CMakefiles.txt since the problem seems coming from there. Thanks so much for your time.
