### ISSUE TITLE
[question] Can EMSCRIPTEN_BINDINGS work with precompiled static libraries?

### ISSUE THREAD

**Issue by harsszegi** [emscripten-core/emscripten#18532]
Hi,

this might be a pretty dumb question, but couldn't really find the answer to it in the documentation. 
I have multiple libraries exposing C++ types via EMSCRIPTEN_BINDINGS. I compile those libraries to .a files only,
e.g. I don't generate bindings with "--bind" for them.
I have a top-level C++ library, which uses types from these dependencies and also this top-level library also exposes
certain functionality via EMSCRIPTEN_BINDINGS. The library links to its dependencies.
I generate both the ".js" and the ".wasm" for this top-level library only. However when I load it up in HTML and try to use
datatypes from the dependencies, the binding layer complains that those types are not registered (using types from
the top-level C++ library appears to be working though).

So my question is, how can I use EMSCRIPTEN_BINDINGS properly if scattered around in various different libraries?
Thanks,

**Comment by harsszegi** [comment]
Ok, closing it. It appears linker optimized out the .o containing the static Emscripten binding init. Found a workaround to add that .o to the final image

**Comment by sbc100** [comment]
You can also use `-Wl,--whole-archive -lfoo -Wl,--no-whole-archive` to for all object in libfoo to be included.
