### ISSUE TITLE
[WASM Exception]: Stacktrace of thrown exceptions in release build

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#18533]
With javascript exceptions, we used to override `__cxa_throw` to log the callstack of thrown exception in production (release build). We are moving to wasm exceptions now and are wondering how can we achieve the same with this. I tried exporting `__cxa_throw` in emitted js and override it as we did before but that is not getting called now with wasm exceptions.

**Comment by ravisumit33** [comment]
@kripken Is it even possible to get the stacktrace in release build with wasm exceptions ?

**Comment by kripken** [comment]
Is the exception caught? If not, then an error handler on the page can get a stack trace.

Or, if it is caught, then a page-level error handler won't get it. Then you need to do something when a C++ exception is thrown, I guess, to log the stack at that time. I don't know if there is any kind of hook for that in the wasm exceptions library code - @aheejin ?

**Comment by aheejin** [comment]
In Wasm exception mode, stack traces are embedded automatically when `ASSERTIONS` is enabled. `ASSERTIONS` is enabled by default in `-O0`, and you can enable it manually by `-sASSERTIONS` in optimized builds. See https://emscripten.org/docs/porting/exceptions.html#debugging-exceptions.
(You also need `-g` or `-gsource-map` to display Wasm function names)

When `ASSERTIONS` is enabled, uncaught exceptions will automatically display stack traces. You can also catch it in JS and manually print or examine it using the [`stack`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Exception/stack) property, like:
```js
try {
  call_wasm_function();
} catch (e) {
  // Do things with `e.stack`
}

**Comment by ravisumit33** [comment]
@aheejin @kripken I guess enabling `-sASSERTIONS` in optimized builds have a performance cost, right ?

**Comment by ravisumit33** [comment]
@aheejin @kripken Enabling assertions in production may have some other side effects like increase in error cases which were handled earlier without assertions. Can we have a flag just for enabling stack traces (e.g. `EXCEPTION_STACKTRACE=1`) without enabling all the assertions ?

**Comment by kripken** [comment]
That sounds reasonable to me, unless @aheejin there is some technical reason not to do so? I'm not sure offhand how best to manage building of `system/lib/libcxxabi/src/cxa_exception.cpp` but we can figure that out I hope.

**Comment by ravisumit33** [comment]
@aheejin What are your views on this ?
