### ISSUE TITLE
cannot seem to make a simple working example: Uncaught (in promise) LinkError: import object field 'emscripten_resize_heap' is not a Function

### ISSUE THREAD

**Issue by colabogey** [emscripten-core/emscripten#18542]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

@ubuntu:~$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.28 (f11d6196dd4e8748a726f19895c859b40ff6a4f3)
clang version 16.0.0 (https://github.com/llvm/llvm-project ea4be70cea8509520db8638bb17bcd7b5d8d60ac)
Target: wasm32-unknown-emscripten
Thread model: posix

colabogey/webasm is where all this lives
cd basicMath/src
make clean
make

cd basicMathControl/src
make clean
make

cd basicMathControl/src/html
in here is streaming.html

I fire this up from VS code to get:
Uncaught (in promise) LinkError: import object field 'emscripten_resize_heap' is not a Function

but you can just
cd basicMathControl/src/bin
and 
wasm-objdump basicMathControl.wasm -s

there are numerous items in there that doom this to failure.

I can neither satisfy these dependencies nor eliminate these dependencies using any build switches or webassembly.instantiateStreaming parameters.

FY(S)I: I cannot find mention of emscripten_resize_heap (and the other items in the wasm file).
I have looked for quite some time.
I am sure its me.

Thanks

**Comment by sbc100** [comment]
`emscripten_resize_heap` is an emscripten library function normally implemented in JS: https://github.com/emscripten-core/emscripten/blob/da4d94b0a02ef8303cba9be86e9534558b1f4d30/src/library.js#L213

Its normally for a the wasm binary to have a dependency on this function and the emscripten-generated JS code should include this function.    Are you using the emscripten-generated JS code?    Can you share the full link command you are using the produce the wasm binaryen?

**Comment by colabogey** [comment]
Here is what the build looks like:
emcc -c -std=c++2a -O0 -g3 -MMD -MP -Wall -Wno-unknown-pragmas -Wno-sign-compare -Woverloaded-virtual -Wwrite-strings -Wno-unused -I../include -I/home/yackey/projects/webasm/include/basicMath -DLINUX=1  -o build/basicMathInterface.o basicMathInterface.cpp
emcc -c -std=c++2a -O0 -g3 -MMD -MP -Wall -Wno-unknown-pragmas -Wno-sign-compare -Woverloaded-virtual -Wwrite-strings -Wno-unused -I../include -I/home/yackey/projects/webasm/include/basicMath -DLINUX=1  -o build/basicMathMain.o basicMathMain.cpp
emcc  -o ./bin/basicMathControl.js ./build/basicMathInterface.o ./build/basicMathMain.o -lbasicMath -lpthread -lc -lrt -L/home/yackey/projects/webasm/bin

Note: I am not using threads even though -lpthread is in there

I am doing the instantiatestreaming 'mechanism' so there is no js file involved.
the html looks like
    <script>

        const importObj = {
            env: {
                abort(_msg, _file, line, column) {
                    console.error("abort called:" + line + ":" + column)
                }
            }
        };

        function run_add() {
            WebAssembly.instantiateStreaming(
                fetch("../bin/basicMathControl.wasm"), importObj
            ).then(results => {
                var a = document.querySelector("#a").value;
                var b = document.querySelector("#b").value;
                var sum = results.instance.exports.basicMathAdd(a, b);
                document.querySelector("#ret").innerHTML +=
                    `${a} ${b} => #{sum} >br/>`;
            });
        }
        
    </script>

Thanks

**Comment by sbc100** [comment]
If you use the generated JS file (`bin/basicMathControl.js`) it will load the wasm module for you and supply all the needed JS support code.   Writing your own loading code (and your own importObj) is not recommended.

If you really want to write your own JS loading code you would want to use standalone wasm mode (`-o foo.wasm` or `-sSTANDALONE_WASM`) but this is not recommended unless you want to learn a lot about emscripten internals.

**Comment by colabogey** [comment]
Just want to make sure I understand.
Doing the 'fetch' as shown in:
https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running
Is not the recommended way ?

I am fairly new to this, so I am trying to get a feel for where to find all the info.

Thanks

**Comment by sbc100** [comment]
Emscripten takes care of all the fetching and loading for you in its generated JS file.

**Comment by colabogey** [comment]
ok, thanks
