### ISSUE TITLE
BigInt not work when enable asyncify option

### ISSUE THREAD

**Issue by carsonDB** [emscripten-core/emscripten#18557]
Please include the following in your bug report:

Latest version: 3.1.30

When I enable BigInt by `-s WASM_BIGINT=1` without asyncify, it works for `int64_t` transferring between JS and C++.
But when I enable both BigInt and asyncify `-s ASYNCIFY`
<img width="640" alt="image" src="https://user-images.githubusercontent.com/11520061/213340236-5451414f-2d23-42c7-9b3a-f854304c0fd6.png">

Await works well. But `BigInt` will not work. Here is a runtime error when I transfer a struct having `int64_t` numbers.
Here is the struct.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/11520061/213340843-d31aad58-fc05-45fc-9480-76c38925e66d.png">

And here is the runtime error in google chrome devtool console.
<img width="248" alt="image" src="https://user-images.githubusercontent.com/11520061/213341499-3df7a044-44c1-4907-990c-3e449b0c5f87.png">

**Comment by sbc100** [comment]
Looks like maybe an issue with embind?    @brendandahl might be able to help.   If you have smaller example of failure case that would make fixing it much easier.

**Comment by carsonDB** [comment]
Thank you! My project currently may be a little bit complex. Maybe I should create a demo project. Currently I've changed all `int64_t` (bind) to `int`, and work fine.
