### ISSUE TITLE
wasm-ld: error: unknown argument: -retain-symbols-file

### ISSUE THREAD

**Issue by milkliker** [emscripten-core/emscripten#18559]
Please include the following in your bug report:

when I use `emmake make` to make lib `fdk-acc`, error comes follow:
```
wasm-ld: error: unknown argument: -retain-symbols-file
wasm-ld: error: unknown file type: ./fdk-aac.sym
```

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.25 (febd44b21ecaca86e2cb2a25ef3ed4a0a2076365)
clang version 16.0.0 (https://github.com/llvm/llvm-project effd75bda4b1a9b26e554c1cda3e3b4c72fa0aa8)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
`/Users/zj/Desktop/emsdk/upstream/emscripten/emmake make`

**Full link command and output with `-v` appended:**
/Users/zj/Desktop/emsdk/upstream/bin/wasm-ld -o .libs/libfdk-aac.2.dylib libAACdec/src/.libs/FDK_delay.o libAACdec/src/.libs/aac_ram.o libAACdec/src/.libs/aac_rom.o libAACdec/src/.libs/aacdec_drc.o libAACdec/src/.libs/aacdec_hcr.o libAACdec/src/.libs/aacdec_hcr_bit.o libAACdec/src/.libs/aacdec_hcrs.o libAACdec/src/.libs/aacdec_pns.o libAACdec/src/.libs/aacdec_tns.o libAACdec/src/.libs/aacdecoder.o libAACdec/src/.libs/aacdecoder_lib.o libAACdec/src/.libs/block.o libAACdec/src/.libs/channel.o libAACdec/src/.libs/channelinfo.o libAACdec/src/.libs/conceal.o libAACdec/src/.libs/ldfiltbank.o libAACdec/src/.libs/pulsedata.o libAACdec/src/.libs/rvlc.o libAACdec/src/.libs/rvlcbit.o libAACdec/src/.libs/rvlcconceal.o libAACdec/src/.libs/stereo.o libAACdec/src/.libs/usacdec_ace_d4t64.o libAACdec/src/.libs/usacdec_ace_ltp.o libAACdec/src/.libs/usacdec_acelp.o libAACdec/src/.libs/usacdec_fac.o libAACdec/src/.libs/usacdec_lpc.o libAACdec/src/.libs/usacdec_lpd.o libAACdec/src/.libs/usacdec_rom.o libAACenc/src/.libs/aacEnc_ram.o libAACenc/src/.libs/aacEnc_rom.o libAACenc/src/.libs/aacenc.o libAACenc/src/.libs/aacenc_lib.o libAACenc/src/.libs/aacenc_pns.o libAACenc/src/.libs/aacenc_tns.o libAACenc/src/.libs/adj_thr.o libAACenc/src/.libs/band_nrg.o libAACenc/src/.libs/bandwidth.o libAACenc/src/.libs/bit_cnt.o libAACenc/src/.libs/bitenc.o libAACenc/src/.libs/block_switch.o libAACenc/src/.libs/channel_map.o libAACenc/src/.libs/chaosmeasure.o libAACenc/src/.libs/dyn_bits.o libAACenc/src/.libs/grp_data.o libAACenc/src/.libs/intensity.o libAACenc/src/.libs/line_pe.o libAACenc/src/.libs/metadata_compressor.o libAACenc/src/.libs/metadata_main.o libAACenc/src/.libs/mps_main.o libAACenc/src/.libs/ms_stereo.o libAACenc/src/.libs/noisedet.o libAACenc/src/.libs/pnsparam.o libAACenc/src/.libs/pre_echo_control.o libAACenc/src/.libs/psy_configuration.o libAACenc/src/.libs/psy_main.o libAACenc/src/.libs/qc_main.o libAACenc/src/.libs/quantize.o libAACenc/src/.libs/sf_estim.o libAACenc/src/.libs/spreading.o libAACenc/src/.libs/tonality.o libAACenc/src/.libs/transform.o libArithCoding/src/.libs/ac_arith_coder.o libDRCdec/src/.libs/FDK_drcDecLib.o libDRCdec/src/.libs/drcDec_gainDecoder.o libDRCdec/src/.libs/drcDec_reader.o libDRCdec/src/.libs/drcDec_rom.o libDRCdec/src/.libs/drcDec_selectionProcess.o libDRCdec/src/.libs/drcDec_tools.o libDRCdec/src/.libs/drcGainDec_init.o libDRCdec/src/.libs/drcGainDec_preprocess.o libDRCdec/src/.libs/drcGainDec_process.o libMpegTPDec/src/.libs/tpdec_adif.o libMpegTPDec/src/.libs/tpdec_adts.o libMpegTPDec/src/.libs/tpdec_asc.o libMpegTPDec/src/.libs/tpdec_drm.o libMpegTPDec/src/.libs/tpdec_latm.o libMpegTPDec/src/.libs/tpdec_lib.o libMpegTPEnc/src/.libs/tpenc_adif.o libMpegTPEnc/src/.libs/tpenc_adts.o libMpegTPEnc/src/.libs/tpenc_asc.o libMpegTPEnc/src/.libs/tpenc_latm.o libMpegTPEnc/src/.libs/tpenc_lib.o libSACdec/src/.libs/sac_bitdec.o libSACdec/src/.libs/sac_calcM1andM2.o libSACdec/src/.libs/sac_dec.o libSACdec/src/.libs/sac_dec_conceal.o libSACdec/src/.libs/sac_dec_lib.o libSACdec/src/.libs/sac_process.o libSACdec/src/.libs/sac_qmf.o libSACdec/src/.libs/sac_reshapeBBEnv.o libSACdec/src/.libs/sac_rom.o libSACdec/src/.libs/sac_smoothing.o libSACdec/src/.libs/sac_stp.o libSACdec/src/.libs/sac_tsd.o libSACenc/src/.libs/sacenc_bitstream.o libSACenc/src/.libs/sacenc_delay.o libSACenc/src/.libs/sacenc_dmx_tdom_enh.o libSACenc/src/.libs/sacenc_filter.o libSACenc/src/.libs/sacenc_framewindowing.o libSACenc/src/.libs/sacenc_huff_tab.o libSACenc/src/.libs/sacenc_lib.o libSACenc/src/.libs/sacenc_nlc_enc.o libSACenc/src/.libs/sacenc_onsetdetect.o libSACenc/src/.libs/sacenc_paramextract.o libSACenc/src/.libs/sacenc_staticgain.o libSACenc/src/.libs/sacenc_tree.o libSACenc/src/.libs/sacenc_vectorfunctions.o libSBRdec/src/.libs/HFgen_preFlat.o libSBRdec/src/.libs/env_calc.o libSBRdec/src/.libs/env_dec.o libSBRdec/src/.libs/env_extr.o libSBRdec/src/.libs/hbe.o libSBRdec/src/.libs/huff_dec.o libSBRdec/src/.libs/lpp_tran.o libSBRdec/src/.libs/psbitdec.o libSBRdec/src/.libs/psdec.o libSBRdec/src/.libs/psdec_drm.o libSBRdec/src/.libs/psdecrom_drm.o libSBRdec/src/.libs/pvc_dec.o libSBRdec/src/.libs/sbr_deb.o libSBRdec/src/.libs/sbr_dec.o libSBRdec/src/.libs/sbr_ram.o libSBRdec/src/.libs/sbr_rom.o libSBRdec/src/.libs/sbrdec_drc.o libSBRdec/src/.libs/sbrdec_freq_sca.o libSBRdec/src/.libs/sbrdecoder.o libSBRenc/src/.libs/bit_sbr.o libSBRenc/src/.libs/code_env.o libSBRenc/src/.libs/env_bit.o libSBRenc/src/.libs/env_est.o libSBRenc/src/.libs/fram_gen.o libSBRenc/src/.libs/invf_est.o libSBRenc/src/.libs/mh_det.o libSBRenc/src/.libs/nf_est.o libSBRenc/src/.libs/ps_bitenc.o libSBRenc/src/.libs/ps_encode.o libSBRenc/src/.libs/ps_main.o libSBRenc/src/.libs/resampler.o libSBRenc/src/.libs/sbr_encoder.o libSBRenc/src/.libs/sbr_misc.o libSBRenc/src/.libs/sbrenc_freq_sca.o libSBRenc/src/.libs/sbrenc_ram.o libSBRenc/src/.libs/sbrenc_rom.o libSBRenc/src/.libs/ton_corr.o libSBRenc/src/.libs/tran_det.o libPCMutils/src/.libs/limiter.o libPCMutils/src/.libs/pcm_utils.o libPCMutils/src/.libs/pcmdmx_lib.o libFDK/src/.libs/FDK_bitbuffer.o libFDK/src/.libs/FDK_core.o libFDK/src/.libs/FDK_crc.o libFDK/src/.libs/FDK_decorrelate.o libFDK/src/.libs/FDK_hybrid.o libFDK/src/.libs/FDK_lpc.o libFDK/src/.libs/FDK_matrixCalloc.o libFDK/src/.libs/FDK_qmf_domain.o libFDK/src/.libs/FDK_tools_rom.o libFDK/src/.libs/FDK_trigFcts.o libFDK/src/.libs/autocorr2nd.o libFDK/src/.libs/dct.o libFDK/src/.libs/fft.o libFDK/src/.libs/fft_rad2.o libFDK/src/.libs/fixpoint_math.o libFDK/src/.libs/huff_nodes.o libFDK/src/.libs/mdct.o libFDK/src/.libs/nlc_dec.o libFDK/src/.libs/qmf.o libFDK/src/.libs/scale.o libSYS/src/.libs/genericStds.o libSYS/src/.libs/syslib_channelMapDescr.o -L/usr/local/opt/node@16/lib -lc -retain-symbols-file ./fdk-aac.sym -L/Users/zj/Desktop/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --relocatable -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr

**Comment by sbc100** [comment]
`-retain-symbols-file` is not a valid linker flag when targeting emscripten or Wasm.   I imagine your build system is adding `-Wl,-retain-symbols-file`.    

My advise would be track down where that link flag is being added and make it conditional.

**Comment by milkliker** [comment]
> `-retain-symbols-file` is not a valid linker flag when targeting emscripten or Wasm. I imagine your build system is adding `-Wl,-retain-symbols-file`.
> 
> My advise would be track down where that link flag is being added and make it conditional.

Okay, it works!

I put additional ignore lld flags into `UNSUPPORTED_LLD_FLAGS` in emcc.py

```python
UNSUPPORTED_LLD_FLAGS = {
    # macOS-specific linker flag that libtool (ltmain.sh) will if macOS is detected.
    '-bind_at_load': False,
    '-retain-symbols-file': True, # <-- ignore this
    # wasm-ld doesn't support soname or other dynamic linking flags (yet).   Ignore them
    # in order to aid build systems that want to pass these flags.
    '-soname': True,
    '-allow-shlib-undefined': False,
    '-rpath': True,
    '-rpath-link': True,
    '-version-script': True,
}
```

**Comment by milkliker** [comment]
Thanks a lot! @sbc100

**Comment by sbc100** [comment]
> > `-retain-symbols-file` is not a valid linker flag when targeting emscripten or Wasm. I imagine your build system is adding `-Wl,-retain-symbols-file`.
> > My advise would be track down where that link flag is being added and make it conditional.
> 
> Okay, it works!
> 
> I put additional ignore lld flags into `UNSUPPORTED_LLD_FLAGS` in emcc.py
> 
> ```python
> UNSUPPORTED_LLD_FLAGS = {
>     # macOS-specific linker flag that libtool (ltmain.sh) will if macOS is detected.
>     '-bind_at_load': False,
>     '-retain-symbols-file': True, # <-- ignore this
>     # wasm-ld doesn't support soname or other dynamic linking flags (yet).   Ignore them
>     # in order to aid build systems that want to pass these flags.
>     '-soname': True,
>     '-allow-shlib-undefined': False,
>     '-rpath': True,
>     '-rpath-link': True,
>     '-version-script': True,
> }
> ```

Thats one way to address the issue, but it might be better for the long term health of your project if you investigate why a macOS linker flags is being added in the first place.    It could mean other things are configured incorrectly.

**Comment by milkliker** [comment]
> Thats one way to address the issue, but it might be better for the long term health of your project if you investigate why a macOS linker flags is being added in the first place. It could mean other things are configured incorrectly.

Ah, yes! Deep investigate is needed.

**Comment by DanyPell** [comment]
Where is emcc.py located?

**Comment by COOLMSF** [comment]
I had the same problem

``` bash
[cmake]     wasm-ld: error: unknown argument: -search_paths_first
[cmake]     wasm-ld: error: unknown argument: -headerpad_max_install_names
[cmake]     em++: error: '/Users/cooldercoolder/Git/emsdk/upstream/bin/wasm-ld -o cmTC_ee28d.wasm -search_paths_first -headerpad_max_install_names -L/Users/cooldercoolder/Git/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten CMakeFiles/cmTC_ee28d.dir
```

how to find where  macOS linker flags come from?

**Comment by sbc100** [comment]
> I had the same problem
> 
> ```shell
> [cmake]     wasm-ld: error: unknown argument: -search_paths_first
> [cmake]     wasm-ld: error: unknown argument: -headerpad_max_install_names
> [cmake]     em++: error: '/Users/cooldercoolder/Git/emsdk/upstream/bin/wasm-ld -o cmTC_ee28d.wasm -search_paths_first -headerpad_max_install_names -L/Users/cooldercoolder/Git/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten CMakeFiles/cmTC_ee28d.dir
> ```
> 
> how to find where macOS linker flags come from?

This is really a cmake question I guess.  I would start by grepping your project and any dependency libraries for `search_paths_first` and `headerpad_max_install_names`.

**Comment by COOLMSF** [comment]
> > I had the same problem
> > ```shell
> > [cmake]     wasm-ld: error: unknown argument: -search_paths_first
> > [cmake]     wasm-ld: error: unknown argument: -headerpad_max_install_names
> > [cmake]     em++: error: '/Users/cooldercoolder/Git/emsdk/upstream/bin/wasm-ld -o cmTC_ee28d.wasm -search_paths_first -headerpad_max_install_names -L/Users/cooldercoolder/Git/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten CMakeFiles/cmTC_ee28d.dir
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > how to find where macOS linker flags come from?
> 
> This is really a cmake question I guess. I would start by grepping your project and any dependency libraries for `search_paths_first` and `headerpad_max_install_names`.

Thx, I have tried greping, but not found those flags.

``` bash
Qt-6.7.0/opengl/hellogl2 via ⬢ v21.5.0 via 🅒 base
➜ grep search_paths_first

Qt-6.7.0/opengl/hellogl2 via ⬢ v21.5.0 via 🅒 base
➜ \grep  -r search_paths_first

Qt-6.7.0/opengl/hellogl2 via ⬢ v21.5.0 via 🅒 base
➜ pwd
/Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2

Qt-6.7.0/opengl/hellogl2 via ⬢ v21.5.0 via 🅒 base
➜
```

**Comment by sbc100** [comment]
Can you share the full cmake command you are using?   Also, it would also be able to see the full em++ command that is failing

**Comment by COOLMSF** [comment]
> Can you share the full cmake command you are using? Also, it would also be able to see the full em++ command that is failing

I'm using qtcreator to create webassembly project. Here's full error log from qtcreator.

error.log
``` bash
[cmake] Running /Users/cooldercoolder/Qt/Tools/CMake/CMake.app/Contents/bin/cmake -S /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2 -B /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release -DCMAKE_GENERATOR:STRING=Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=/Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release/.qtc/package-manager/auto-setup.cmake -DQT_QMAKE_EXECUTABLE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/bin/qmake -DCMAKE_PREFIX_PATH:PATH=/Users/cooldercoolder/Qt/6.7.0/macos -DCMAKE_C_COMPILER:FILEPATH=/Users/cooldercoolder/Git/emsdk/upstream/emscripten/emcc -DCMAKE_CXX_COMPILER:FILEPATH=/Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++ -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/lib/cmake/Qt6/qt.toolchain.cmake -DCMAKE_CXX_FLAGS_INIT:STRING= in /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release.
[cmake] -- The CXX compiler identification is Clang 19.0.0
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - failed
[cmake] -- Check for working CXX compiler: /Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++
[cmake] -- Check for working CXX compiler: /Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++ - broken
[cmake] CMake Error at /Users/cooldercoolder/Qt/Tools/CMake/CMake.app/Contents/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:60 (message):
[cmake]   The C++ compiler
[cmake] 
[cmake]     "/Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: '/Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release/CMakeFiles/CMakeScratch/TryCompile-QJQDjT'
[cmake]     
[cmake]     Run Build Command(s): /Users/cooldercoolder/Qt/Tools/Ninja/ninja -v cmTC_ee28d
[cmake]     [1/2] /Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=11.0 -fcolor-diagnostics -MD -MT CMakeFiles/cmTC_ee28d.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_ee28d.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_ee28d.dir/testCXXCompiler.cxx.o -c /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release/CMakeFiles/CMakeScratch/TryCompile-QJQDjT/testCXXCompiler.cxx
[cmake]     clang++: warning: argument unused during compilation: '-mmacosx-version-min=11.0' [-Wunused-command-line-argument]
[cmake]     [2/2] : && /Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++ -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=11.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_ee28d.dir/testCXXCompiler.cxx.o -o cmTC_ee28d   && :
[cmake]     FAILED: cmTC_ee28d 
[cmake]     : && /Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++ -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=11.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_ee28d.dir/testCXXCompiler.cxx.o -o cmTC_ee28d   && :
[cmake]     wasm-ld: error: unknown argument: -search_paths_first
[cmake]     wasm-ld: error: unknown argument: -headerpad_max_install_names
[cmake]     em++: error: '/Users/cooldercoolder/Git/emsdk/upstream/bin/wasm-ld -o cmTC_ee28d.wasm -search_paths_first -headerpad_max_install_names -L/Users/cooldercoolder/Git/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten CMakeFiles/cmTC_ee28d.dir/testCXXCompiler.cxx.o -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/6r/x7m8d4z16y90vv2xwybvy_qw0000gn/T/tmpwejplvmmlibemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)
[cmake]     ninja: build stopped: subcommand failed.
[cmake]     
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:5 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] 
[cmake] The command "/Users/cooldercoolder/Qt/Tools/CMake/CMake.app/Contents/bin/cmake -S /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2 -B /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release -DCMAKE_GENERATOR:STRING=Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=/Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release/.qtc/package-manager/auto-setup.cmake -DQT_QMAKE_EXECUTABLE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/bin/qmake -DCMAKE_PREFIX_PATH:PATH=/Users/cooldercoolder/Qt/6.7.0/macos -DCMAKE_C_COMPILER:FILEPATH=/Users/cooldercoolder/Git/emsdk/upstream/emscripten/emcc -DCMAKE_CXX_COMPILER:FILEPATH=/Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++ -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/lib/cmake/Qt6/qt.toolchain.cmake -DCMAKE_CXX_FLAGS_INIT:STRING=" terminated with exit code 1.
[cmake] 
[cmake] Elapsed time: 00:03.
```

CMakeLists.txt
``` 
# Copyright (C) 2022 The Qt Company Ltd.
# SPDX-License-Identifier: BSD-3-Clause

cmake_minimum_required(VERSION 3.16)
project(hellogl2 LANGUAGES CXX)

if(NOT DEFINED INSTALL_EXAMPLESDIR)
    set(INSTALL_EXAMPLESDIR "examples")
endif()

set(INSTALL_EXAMPLEDIR "${INSTALL_EXAMPLESDIR}/opengl/hellogl2")

find_package(Qt6 REQUIRED COMPONENTS Core Gui OpenGL OpenGLWidgets Widgets)

qt_standard_project_setup()

qt_add_executable(hellogl2
    glwidget.cpp glwidget.h
    logo.cpp logo.h
    main.cpp
    mainwindow.cpp mainwindow.h
    window.cpp window.h
)

set_target_properties(hellogl2 PROPERTIES
    WIN32_EXECUTABLE TRUE
    MACOSX_BUNDLE TRUE
)

target_link_libraries(hellogl2 PRIVATE
    Qt6::Core
    Qt6::Gui
    Qt6::OpenGL
    Qt6::OpenGLWidgets
    Qt6::Widgets
)

install(TARGETS hellogl2
    RUNTIME DESTINATION "${INSTALL_EXAMPLEDIR}"
    BUNDLE DESTINATION "${INSTALL_EXAMPLEDIR}"
    LIBRARY DESTINATION "${INSTALL_EXAMPLEDIR}"
)
```

**Comment by sbc100** [comment]
[cmake] Running /Users/cooldercoolder/Qt/Tools/CMake/CMake.app/Contents/bin/cmake -S /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2 -B /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release -DCMAKE_GENERATOR:STRING=Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=/Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release/.qtc/package-manager/auto-setup.cmake -DQT_QMAKE_EXECUTABLE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/bin/qmake -DCMAKE_PREFIX_PATH:PATH=/Users/cooldercoolder/Qt/6.7.0/macos -DCMAKE_C_COMPILER:FILEPATH=/Users/cooldercoolder/Git/emsdk/upstream/emscripten/emcc -DCMAKE_CXX_COMPILER:FILEPATH=/Users/cooldercoolder/Git/emsdk/upstream/emscripten/em++ -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/lib/cmake/Qt6/qt.toolchain.cmake -DCMAKE_CXX_FLAGS_INIT:STRING= in /Users/cooldercoolder/Qt/Examples/Qt-6.7.0/opengl/hellogl2/build/Webassembly-Release.


The problem is that `CMAKE_TOOLCHAIN_FILE` (`CMAKE_TOOLCHAIN_FILE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/lib/cmake/Qt6/qt.toolchain.cmake`)   

Emscripten provides it own cmake toolchain file that takes care of setting the compiler, etc.  Its not enough to simply set `CMAKE_C_COMPILER`, etc.   

Emscripten has a wrapper you can run call `emcmake` .. you use it before `cmake` in the `cmake` command.  See https://emscripten.org/docs/compiling/Building-Projects.html#integrating-with-a-build-system

**Comment by COOLMSF** [comment]
> The problem is that `CMAKE_TOOLCHAIN_FILE` (`CMAKE_TOOLCHAIN_FILE:FILEPATH=/Users/cooldercoolder/Qt/6.7.0/macos/lib/cmake/Qt6/qt.toolchain.cmake`)
> 
> Emscripten provides it own cmake toolchain file that takes care of setting the compiler, etc. Its not enough to simply set `CMAKE_C_COMPILER`, etc.
> 
> Emscripten has a wrapper you can run call `emcmake` .. you use it before `cmake` in the `cmake` command. See https://emscripten.org/docs/compiling/Building-Projects.html#integrating-with-a-build-system

Thanks, I'll have a try.
