### ISSUE TITLE
Arbitrary Sleep and Awake

### ISSUE THREAD

**Issue by nbarkhina** [emscripten-core/emscripten#18573]
Hi,

Is it possible to do a sleep and awake in an arbitrary location in the code? Basically I am looking for a way to do emscripten_sleep() but in a way that yields better performance. Normally I use emscripten_set_main_loop() which gives me the best performance and is tied to requestionAnimationFrame() however in this particular codebase, it is not suited for a mainLoop function that I can just call. So i'm trying to get the best of both worlds. I would like to put the app to sleep in a certain location and then wake it up from javascript when needed. I have tried it like this but it doesnt seem to work:

C++ Code:
```c++
EM_JS(int, my_custom_sleep, (), {
  return Asyncify.handleSleep(function (wakeUp) {
    myApp.fpsPromise.then(function (response) {
	    myApp.fpsPromise = new Promise(function(resolve, reject){
            myApp.promiseResolve = resolve;
            myApp.promiseReject = reject;
        });
      wakeUp(0);
    });
  });
});
#endif

void someFunction()
{
    my_custom_sleep();
}
```

Then in Javascript:

```javascript
    myLoop() {
        window.requestAnimationFrame(myClass.myLoop);

        myClass.promiseResolve();
    }
```

However this does not work and just hangs. Do you know if there is a way to achieve what I am trying to do? 

Thanks

**Comment by kripken** [comment]
Asyncify sounds like what you need: https://emscripten.org/docs/porting/asyncify.html

It does have a speed penalty atm, but there is experimental browser support for making it super-fast: https://v8.dev/blog/jspi
