### ISSUE TITLE
Module.locateFile is not called when loading side modules

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#18586]
We have a case where we load emitted js from a domain and download wasm binaries from different domain. We have used `Module.locateFile` to provide proper url as mentioned in the doc ([here](https://emscripten.org/docs/api_reference/module.html?highlight=locatefile#Module.locateFile)). `Module.locateFile` is appropriately used for main module ([here](https://github.com/emscripten-core/emscripten/blob/1ec7dc0b71c38e075810560384872a6bf9efa8b5/src/preamble.js#L616)). But for side modules, side module names are used without using `Module.locateFile`. This creates an issue in cases where emitted js and side module wasm binaries are hosted on different domains.

**Comment by ravisumit33** [comment]
@sbc100 We are getting this issue since a while. Can you please confirm if this is a bug or we are missing something ?

**Comment by sbc100** [comment]
Sounds like a real bug yes.  If you have time to write a PR to fix that would be amazing.  Otherwise, we will try to prioritize it soon.

**Comment by ravisumit33** [comment]
Looks like this has been fixed.
