### ISSUE TITLE
Passing the same pointer to `__randname` twice before the clock ticks generates the same random path

### ISSUE THREAD

**Issue by maraf** [emscripten-core/emscripten#18591]
If we pass the same pointer for `template` to the `__randname` before the clock ticks, we are getting the same random path.

https://github.com/emscripten-core/emscripten/blob/085fe968d43c7d3674376f29667d6e5f42b24966/system/lib/libc/musl/src/temp/__randname.c#L13

**Comment by sbc100** [comment]
Maybe we could have `static int` inside this function that we increment on each call and add into `r`?

**Comment by pavelsavara** [comment]
> Maybe we could have `static int` inside this function that we increment on each call and add into `r`?

Probably unsigned type would be better so that it could overflow back to zero if called too many times.
