### ISSUE TITLE
Up and down arrow keys scroll the browser with SDL2

### ISSUE THREAD

**Issue by rtrussell** [emscripten-core/emscripten#18594]
[This issue](https://github.com/emscripten-core/emscripten/issues/3665) seems to be current again, in Chrome at least (I was previously using 2.0.5, so I don't know when it reappeared).   Is there a way to arrange for those keys (and possibly others) to be handled only by SDL2 and not affect the browser directly?  I've tried all the options available from SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT without success.

**Comment by sbc100** [comment]
Reopened #3665

**Comment by rtrussell** [comment]
This turned out to be because I was calling `SDL_SetEventFilter()` in my code.  Changing this to `SDL_AddEventWatch()` restored the desired behavior of the arrow keys not scrolling the browser (canvas).  I don't claim to understand why calling `SDL_SetEventFilter()` had that effect (especially since it didn't in Emscripten 2.0.5) but I'm happy to have a solution.
