### ISSUE TITLE
[WASM Exception]: WasmOffsetConverter fails with: bad import kind: 12

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#18592]
I tried switching from emscripten EH -> wasm EH (using -sASSERTIONS + dynamic linking).

Unfortunately running the code fails with
`failed to asynchronously prepare wasm: bad import kind: 12`.

It seems that the produced wasm sections are not considered in WasmOffsetConverter

**Comment by sbc100** [comment]
I guess we must not have any testing of that particular configuration.   We should fix that.

**Comment by aheejin** [comment]
Can you provide a reproducer? I did a simple test but it seemed working. What I did was:

`main.cpp`:
```cpp
void side_throw();
int main() {
  side_throw();
  return 0;
}
```

`liblib.cpp`:
```cpp
void side_throw() {
  throw 3;
}
```

```console
$ em++ liblib.cpp -o liblib.so -g -sASSERTIONS -sSIDE_MODULE -O0 -fwasm-exceptions -sENVIRONMENT=shell

$ em++ main.cpp -o main.js -sMAIN_MODULE=2 -O0 -fwasm-exceptions -sASSERTIONS liblib.so -sENVIRONMENT=shell

$ d8 main.js
aheejin@aheejin:~/test/stack/dylink$ d8 main.js
exiting due to exception: [object WebAssembly.Exception],Error: int,
    at wasm://wasm/00073456:wasm-function[149]:0xb639
    at side_throw() (wasm://wasm/6d51dda6:wasm-function[4]:0x140)
    at __Z10side_throwv (main.js:2069:41)
    at wasm://wasm/00073456:wasm-function[12]:0x525a
    at wasm://wasm/00073456:wasm-function[13]:0x5277
    at callMain (main.js:5050:15)
    at doRun (main.js:5118:23)
    at run (main.js:5133:5)
    at runCaller (main.js:5024:19)
```

**Comment by gl84** [comment]
I've created a small repro case:

reader.hpp:
```
struct reader {
    public:
        reader() {}
        ~reader();
};
```

reader.cpp:
```
#include "reader.hpp"
#include "emscripten.h"
EMSCRIPTEN_KEEPALIVE reader::~reader() {}
```

exported_api.cpp:
```
#include "emscripten.h"
#include "reader.hpp"
extern "C" {
    EMSCRIPTEN_KEEPALIVE void reader_destroy(reader* r) {
        delete r;
    }
}
EMSCRIPTEN_KEEPALIVE int main() {}
```

Compile it with:
`em++ -fPIC -o lib.so -sSIDE_MODULE=2 -sEXPORTED_FUNCTIONS=[_ZN6readerD1Ev]  -fwasm-exceptions  reader.cpp`
`em++  -fwasm-exceptions  -o exported_api.cpp.o -c exported_api.cpp`
`em++ -fsanitize=null   -sMAIN_MODULE=2  -sASSERTIONS=2 -sEXPORTED_FUNCTIONS=_main  -fwasm-exceptions exported_api.cpp.o -o exported_api.js  lib.so`

and execute it.
