### ISSUE TITLE
Quiet cache:INFO messages?

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#18607]
I am trying to get the tests working on the libffi port and there are two remaining test failures due to the emcc `cache:INFO` messages:
```
cache:INFO: generating system asset: symbol_lists/blah.txt
cache:INFO:  - ok
```
Is there a way to quiet these?

**Comment by sbc100** [comment]
Are you referring the standard emscripten tests?  Or new tests in your repository?

I agree we should probably add a way to silence these, but I'm curious, why do your tests case about the stderr of the compiler?

**Comment by hoodmane** [comment]
The upstream libffi test suite uses dejagnu which has a "test for excess errors" which seems to assume that extra stuff written to stderr indicates that something went wrong with the compiler. Maybe I should talk to the libffi people and figure out how to whitelist them.

**Comment by sbc100** [comment]
No, you are correct that we should have some way to silence these messages..
