### ISSUE TITLE
STRICT_JS is actually harmful when used with EXPORT_ES6

### ISSUE THREAD

**Issue by dhdaines** [emscripten-core/emscripten#18610]
Obviously `STRICT_JS=1` is redundant when building ES6 modules since they are strict by default, but actually it should probably be disabled, as the `"use strict"` that gets inserted into the `Module` function can lead to this error:

```Illegal 'use strict' directive in function with non-simple parameter list```

This seems to happen in particular with certain versions of Node.js and esm, at least, when using `chai` under the Node version that comes with https://github.com/mymindstorm/setup-emsdk.

Suggest that STRICT_JS should do nothing (or at least output a warning) when used with EXPORT_ES6.

**Comment by sgbeal** [comment]
This is hitting the sqlite project in a non-ES6 build with emcc 3.1.31. The offending piece is:

```js
var sqlite3InitModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(sqlite3InitModule = {})  {

// include: shell.js
"use strict";   //////////////////////////// HERE

// The Module object: Our interface to the outside world. We import
// and export values on it. There are various ways Module can be used:
...
```

3.1.30 does not do this.

**Comment by curiousdannii** [comment]
`"use strict"` is normally not an issue if it would be redundant. It's only an error in [certain situations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Strict_Non_Simple_Params), in this case a function with default parameters. So this is caused by #18551.

**Comment by sbc100** [comment]
Thanks for the report.  Sounds like fairly simple fix: We should avoid setting `STRICT_JS` internally in this case, and error if anyone tries to set `STRICT_JS` and `EXPORT_ES6` at the same time.

**Comment by sgbeal** [comment]
@sbc100 it's not limited to ES6 builds. See the 2nd comment.

**Comment by sbc100** [comment]
> @sbc100 it's not limited to ES6 builds. See the 2nd comment.

Can you elaborate a little, what is the issue with your non-ES6 build?   i.e. what is the problem with having `use strict` at that point?

**Comment by sbc100** [comment]
Oh I see its the default parameters... i wonder how non of our tests that run in strict mode found that..  investigating.
