### ISSUE TITLE
closure compiler throws "variable arguments_ is undeclared" (3.1.31)

### ISSUE THREAD

**Issue by haberbyte** [emscripten-core/emscripten#18630]
With the latest release `3.1.31` I get the following error in my build during linking with `--closure 1`:

```
building:ERROR: /var/folders/c6/2dhh2dzx0d92vcvh7b1fgy2m0000gn/T/emscripten_temp_9ehu0dk0/mapasm.jso4.js:2635:52: ERROR - [JSC_UNDEFINED_VARIABLE] variable arguments_ is undeclared
  2635| /** @type {function(Array=)} */ function run(args = arguments_) {
                                                            ^^^^^^^^^^

1 error(s), 0 warning(s)
```

I think this refers to the following code in [postamle.js#L147](https://github.com/emscripten-core/emscripten/blob/801e66386b33adf017b2da2e6b65a4e9f50674f3/src/postamble.js#L147).

...

Changing this back to this fixes it for me:

```js
function run(args) {
  args = args || arguments_;

  ...
}
```

**Comment by sbc100** [comment]
Can you share you full link command?   Or better still full failing example?   This wan't picked up by any of our tests so obviously we have gap somewhere.

**Comment by haberbyte** [comment]
Tried to come up with a minimal failing example, but then realized it must be a misconfiguration on my end...

For the record, setting `INCOMING_MODULE_JS_API=[]` leads to this error for me.
I didn't have to do this before 3.1.31, but passing `INCOMING_MODULE_JS_API=[arguments]` fixes it.

I believe this issue can be closed? Feel free to re-open if this is not intended behavior.

**Comment by sbc100** [comment]
If setting `INCOMING_MODULE_JS_API=[]` leads to this error we should probably fix that.   I'll take a look now

**Comment by sbc100** [comment]
I was not able to reproduce this using `-sINCOMING_MODULE_JS_API=[]`.   It looks to be like `arguments_` is unconditionally defined here: https://github.com/emscripten-core/emscripten/blob/b08191b8301871b12c139069dc3c242883dda451/src/shell.js#L84

Can you share the full list of link flags you are passing to emscripten?
