### ISSUE TITLE
SDL2_ttf port is very old

### ISSUE THREAD

**Issue by rtrussell** [emscripten-core/emscripten#18639]
I raised this at the [Emscripten Ports](https://github.com/emscripten-ports/SDL2_ttf/issues/3) project but was redirected here.  The version of **SDL2_ttf** that you get from `-s USE_SDL_TTF=2` (**2.0.15**) is over four years old, it was released in January 2019!  Are there any plans to update this to a newer version (ideally **2.20.1**)?  There have been major developments in the support of HarfBuzz text shaping in the meantime, such as the introduction of the `TTF_SetFontScriptName()` and `TTF_SetFontDirection()` functions.

**Comment by sbc100** [comment]
We don't have any specific existing plans to update.  If you need a recent version you could to try to propose and update as a PR?  Otherwise I will mark flag this issue such that someone should pick it up at some point.

**Comment by sbc100** [comment]
Oh way, I think you are looking at an old repo.   The port looks like it now directly points to upstream: https://github.com/emscripten-core/emscripten/blob/008017bde42a4b891b0fa0175a1dbe000df99caf/tools/ports/sdl2_ttf.py#L8

It was updated last here: #13484

**Comment by rtrussell** [comment]
> I think you are looking at an old repo. The port looks like it now directly points to upstream:

I've installed the latest version of Emscripten (3.1.31):

```
emsdk install 3.1.31
emsdk activate 3.1.31

```
The version of SDL2_ttf I'm getting from `-s USE_SDL_TTF=2` is **2.0.15**.  Is there something else I am supposed to do to get a later version?

**Comment by sbc100** [comment]
The commit we use is https://github.com/libsdl-org/SDL_ttf/commit/38fcb695276ed794f879d5d9c5ef4e5286a5200d.

This is from Oct 29 2020.   Upgrading to more recent version should be fine.   If you have time perhaps you could upload a PR?

**Comment by rtrussell** [comment]
> The commit we use is [libsdl-org/SDL_ttf@38fcb69](https://github.com/libsdl-org/SDL_ttf/commit/38fcb695276ed794f879d5d9c5ef4e5286a5200d). This is from Oct 29 2020. 

From this [list of releases](https://www.libsdl.org/projects/SDL_ttf/release/) I conclude that it is indeed **2.0.15** (using commits that were never released is questionable, I would say, because they won't have undergone extensive testing).  The next official release was **2.0.18** on Jan 11 2022.  

> Upgrading to more recent version should be fine. If you have time perhaps you could upload a PR?

Sorry, I have not the slightest idea how to do that.   I assumed that the latest Emscripten would give me a reasonably recent version of SDL2_ttf, as it doesn't I'll have to live with that.

**Comment by sbc100** [comment]
We can certainly upgrade the version that we ship, and I'm sure we will, its just question of time and priorities.    

I didn't mean pressure you to be the one to do the upgrade, I was just offering your the opportunity, since that is often a practical way get things done quickly.

**Comment by rtrussell** [comment]
> didn't mean pressure you to be the one to do the upgrade, I was just offering your the opportunity, since that is often a practical way get things done quickly.

I presume another way would be to use the EMCC_LOCAL_PORTS environment variable, which is easier for me to understand.

**Comment by rtrussell** [comment]
> Bear in mind that that option is mostly an internal/development aid IIUC, so YMMV

I see.  It's referred to [here](https://emscripten.org/docs/tools_reference/emcc.html) but without any details.  I've just tried both of these, neither has any effect:

```
EMCC_LOCAL_PORTS="SDL_TTF=/SDL2_ttf-2.20.1/"
EMCC_LOCAL_PORTS="SDL2_TTF=/SDL2_ttf-2.20.1/"

```
The environment variable is being recognised because I get  this warning, repeated five times:

`ports:WARNING: using local ports: "SDL2_TTF=/SDL2_ttf-2.20.1/"`

but the build doesn't seem to be affected at all.

**Comment by waywardmonkeys** [comment]
I've submitted PR #18804 that addresses this port specifically. But we should also probably update the FreeType and Harfbuzz ports as well.
