### ISSUE TITLE
`ASYNCIFY_STACK_SIZE not being large enough` when using memory64 and asyncify together

### ISSUE THREAD

**Issue by asdfsx** [emscripten-core/emscripten#18644]
I'm new to Emscripten, and I'm testing `ASYNCIFY` with following code

```
// example.cpp
#include <emscripten.h>
#include <stdio.h>

// start_timer(): call JS to set an async timer for 500ms
EM_JS(void, start_timer, (), {
  Module.timer = false;
  setTimeout(function() {
    Module.timer = true;
  }, 500);
});

// check_timer(): check if that timer occurred
EM_JS(bool, check_timer, (), {
  return Module.timer;
});

int main() {
  start_timer();
  // "Infinite loop", synchronously poll for the timer.
  while (1) {
    if (check_timer()) {
      printf("timer happened!\n");
      return 0;
    }
    printf("sleeping...\n");
    emscripten_sleep(100);
  }
}
```

When build the code with `emcc  example.cpp -s ASYNCIFY`, it works great, both building and executing.

When build the code with `EMCC_CFLAGS=-sMEMORY64=1 emcc  example.cpp -s ASYNCIFY`, building failed with error `emcc: error: MEMORY64=1 is not compatible with ASYNCIFY`

When build the code with `EMCC_CFLAGS=-sMEMORY64=2 emcc  example.cpp -s ASYNCIFY`, building succesed. But when execute `node a.out.js`, it failed with error

```
sleeping...
Aborted(RuntimeError: unreachable)
/src/attestation/wasm/test/a.out.js:137
      throw ex;
      ^

RuntimeError: Aborted(RuntimeError: unreachable). "unreachable" may be due to ASYNCIFY_STACK_SIZE not being large enough (try increasing it)
    at abort (/src/attestation/wasm/test/a.out.js:865:11)
    at runAndAbortIfError (/src/attestation/wasm/test/a.out.js:1434:9)
    at Object.handleSleep (/src/attestation/wasm/test/a.out.js:1664:13)
    at _emscripten_sleep (/src/attestation/wasm/test/a.out.js:1350:23)
    at imports.<computed> (/src/attestation/wasm/test/a.out.js:1475:35)
    at wasm://wasm/0002ef82:wasm-function[7]:0x69d
    at wasm://wasm/0002ef82:wasm-function[8]:0x78b
    at ret.<computed> (/src/attestation/wasm/test/a.out.js:1509:35)
    at /src/attestation/wasm/test/a.out.js:1770:14
    at /src/attestation/wasm/test/a.out.js:923:22

Node.js v18.13.0
```

I tried to build the code with `EMCC_CFLAGS=-sMEMORY64=2 emcc  example.cpp -s ASYNCIFY -s ASYNCIFY_STACK_SIZE=5120000`, the problem is the same.

Is there any way to solve the problem?

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.31 (e88336121cfe6da4a96c88e46f314552f07dfed0)
clang version 17.0.0 (https://github.com/llvm/llvm-project 1142e6c7c795de7f80774325a07ed49bc95a48c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin

Node version  v18.13.0

**Comment by sbc100** [comment]
Interesting, I have though that MEMORY64 doesn't support ASYNCIFY at all.   In fact, I have some (old) outstanding work to try and make it work: https://github.com/emscripten-core/emscripten/pull/18647

We should currently be erroring on that configuration I think.

**Comment by sbc100** [comment]
Oh wait.. its `MEMORY64=1` that is not compatible with `ASYNCIFY`.    `MEMORY64=2` should work.

**Comment by sbc100** [comment]
BTW I was able to make this fail with a much simple example:

```
$ cat example.cpp 
#include <emscripten.h>
#include <stdio.h>

int main() {
  printf("sleeping...\n");
  emscripten_sleep(100);
}
$ em++ -O0  example.cpp -sASYNCIFY -sMEMORY64=2
$ node a.out.js
Aborted(RuntimeError: unreachable)
/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:137
      throw ex;
      ^

RuntimeError: Aborted(RuntimeError: unreachable). "unreachable" may be due to ASYNCIFY_STACK_SIZE not being large enough (try increasing it)
    at abort (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:866:11)
    at runAndAbortIfError (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1436:9)
    at Object.handleSleep (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1666:13)
    at _emscripten_sleep (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1353:23)
    at imports.<computed> (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1477:35)
    at wasm://wasm/0002e5a6:wasm-function[5]:0x4cb
    at wasm://wasm/0002e5a6:wasm-function[6]:0x5a0
    at ret.<computed> (/usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1511:35)
    at /usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:1769:14
    at /usr/local/google/home/sbc/dev/wasm/emscripten/a.out.js:924:22
```

**Comment by sbc100** [comment]
@kripken might I have a better clue about what is going on here

**Comment by kripken** [comment]
Hmm, in Asyncify we assume pointers are 32-bit, for the data structure. That could be the issue here. But I'm not sure it's worth fixing as (1) Asyncify will be replaced by JSPI, and (2) `MEMORY64=2` is mainly meant for internal testing. I'm actually curious @asdfsx what is your use case for `sMEMORY64=2`?

**Comment by asdfsx** [comment]
I'm trying to create digest for some text under wasm environment, then compare them with the digest create from 64bit environment. 
The library I use can work properly with the parameter `sMEMORY64=2`. But without the parameter the digest created under wasm environment is only 32bit long, and is different from the 64bit digest which is 64 bit long.

**Comment by asdfsx** [comment]
I'll close the issue, and try to do it in some other way
