### ISSUE TITLE
parse exception: attempted pop from empty stack / beyond block start boundary

### ISSUE THREAD

**Issue by afeder** [emscripten-core/emscripten#18666]
When trying to build my project for the first time since 2019, I now get this error:

```
wasm-ld: warning: function signature mismatch: s_copy
>>> defined as (i32, i32, i32, i32) -> i32 in /tmp/webspice/lib/libwebspice.a(ucase.o)
>>> defined as (i32, i32, i32, i32) -> void in /tmp/webspice/lib/libwebspice.a(s_copy.o)

wasm-ld: warning: function signature mismatch: zzsetnnread_
>>> defined as (i32) -> i32 in /tmp/webspice/lib/libwebspice.a(rdker.o)
>>> defined as (i32) -> void in /tmp/webspice/lib/libwebspice.a(rsfe.o)

wasm-ld: warning: function signature mismatch: s_cat
>>> defined as (i32, i32, i32, i32, i32) -> i32 in /tmp/webspice/lib/libwebspice.a(trcpkg.o)
>>> defined as (i32, i32, i32, i32, i32) -> void in /tmp/webspice/lib/libwebspice.a(s_cat.o)
[parse exception: attempted pop from empty stack / beyond block start boundary at 13080 (at 0:13080)]
Fatal: error in parsing input
```

Am I doing something wrong or could there be a bug at play?

This is the version I am using:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.31 (e88336121cfe6da4a96c88e46f314552f07dfed0)
clang version 17.0.0 (https://github.com/llvm/llvm-project 1142e6c7c795de7f80774325a07ed49bc95a48c9)
Target: wasm32-unknown-emscripten
Thread model: posix
```

The error can be reproduced as follows:
```
$ git clone git@gitlab.com:afeder/webspice.git
$ cd webspice/
$ git checkout develop
$ ./build.sh
```
This is my emscripten_temp directory after compiling:

[emscripten_temp.zip](https://github.com/emscripten-core/emscripten/files/10609368/emscripten_temp.zip)

The last succesful build I made can be found at https://www.npmjs.com/package/webspice.

**Comment by kripken** [comment]
The error may be related to those warnings. That is undefined behavior in C/C++, which can cause issues in wasm. Basically a function is defined twice, in different ways.

If you resolve those warnings but still get that pop error then it would be either a wasm-ld or a binaryen bug. To check which of those two, build without binaryen (using https://github.com/emscripten-core/emscripten/blob/5402fc921374cf11f19600e5c3f23eeae76fba5c/src/settings.js#L1982-L1994 which will guide you how to do it, but iirc `-O0 -sWASM_BIGINT` should do it).

**Comment by afeder** [comment]
Thank you, it does seem to be the duplicate function definitions that are causing the error.
