### ISSUE TITLE
IDBFS doesn't save/restore data

### ISSUE THREAD

**Issue by iliakan** [emscripten-core/emscripten#18699]
I'm building with -sMODULARIZE and repeatedly create a new module.

Although, FS doesn't save/restore data.

Does the code look good?

```js
let FS;
async function run() {
  Module = await createMyModule();

  FS = Module.FS;

  FS.mkdir('/project');

  FS.mount(FS.filesystems.IDBFS, {}, '/project');
  await sync();
  FS.chdir('/project');

  console.log(FS.analyzePath('content').exists);  // <---- (*)

  FS.writeFile('content', '...');

  await sync();
}

async function sync() {
   // should save/load existing data here? (doesn't work)
  await new Promise((res, rej) => {
    FS.syncfs(true, err => err ? rej(err) : res());
  });
}

(async () => {
  await run();
  await run();
})();
```

Expected: on the second run the file at `(*)` should exist (true), but it doesn't.
Shows `false`. 
No errors.

**Comment by iliakan** [comment]
TYPO, closed.

**Comment by ericoporto** [comment]
@iliakan what was the typo?

**Comment by iliakan** [comment]
`syncfs(true, callback)` loads, while `syncfs(callback)` saves.

That's kind of confusing, @sbc100 :/ if I may say so.

**Comment by sbc100** [comment]
That API pre-dates my involvement I'm afraid.   The whole filesystem API is due to be replaced by wasmfs soon so it might be not worth attempting to change at this point.
