### ISSUE TITLE
Assertion failure with ASan + PROXY_TO_PTHREAD + EXIT_RUNTIME

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#18708]
test.c:

```
int main() {}
```

Build with `emcc test.c -o test.html -g -pthread -sPROXY_TO_PTHREAD -sEXIT_RUNTIME -fsanitize=address`.

test.html aborts after main exits because the (legacy) proxying machinery calls `free` after performing the proxied `exitOnMainThread`. The intercepted `free` gathers a stack trace, which requires some JS, which ends up calling `_asan_js_stroe_4`, which fails an assertion because `runtimeExited` is now true.

Stack trace: 

```
abort (test.js:755)
assert (test.js:387)
(anonymous) (test.js:777)
_asan_js_store_4 (test.js:358)
_emscripten_stack_unwind_buffer (test.js:4466)
__sanitizer::BufferedStackTrace::UnwindFast(unsigned long, unsigned long, unsigned long, unsigned long, unsigned int) (sanitizer_stacktrace_emscripten.cpp:37)
__sanitizer::BufferedStackTrace::Unwind(unsigned int, unsigned long, unsigned long, void*, unsigned long, unsigned long, bool) (sanitizer_stacktrace_libcdep.cpp:172)
__sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int) (asan_stack.cpp:69)
__sanitizer::BufferedStackTrace::Unwind(unsigned long, unsigned long, void*, bool, unsigned int) (sanitizer_stacktrace.h:133)
::free(void *) (asan_malloc_linux.cpp:52)
em_queued_call_free (library_pthread.c:132)
_do_call (library_pthread.c:315)
em_task_queue_execute (em_task_queue.c:86)
receive_notification (proxying.c:256)
em_task_queue_execute (em_task_queue.c:86)
_emscripten_proxy_execute_task_queue (proxying.c:219)
(anonymous) (test.js:781)
executeNotifiedProxyingQueue (test.js:4110)
worker.onmessage (test.js:3771)
```

A possible fix might be to port the implementation of `$XXX__proxy: 'yyy'` to use the new proxying API, which would not involve that particular call to `free`. That might run into some other similar issue, though.

**Comment by sbc100** [comment]
I can't reproduce this on either node or chrome.   Has it been fixed since you reported it?  Or is it very intermittent?

**Comment by tlively** [comment]
It was deterministic when I reported it, so it must have been fixed. Did you end up changing `__proxy:` to use the new proxying API?

**Comment by sbc100** [comment]
Nope.   Perhaps you could try one time to repro since maybe I did something wrong in the steps?

**Comment by sbc100** [comment]
Were you running under node?

**Comment by tlively** [comment]
Looks like I was using the browser, but I don't think this was browser specific.

I can't repro now, and digging in, it looks like the program is dying before it gets to the code that was exhibiting the problem.

It also looks like the program is dying before doing leak checking? That seems bad.

**Comment by sbc100** [comment]
OK.. I will double check that leak checks get run

**Comment by sbc100** [comment]
I guess we can close this now?
