### ISSUE TITLE
em++ did not successfully convert llvm bitecode to js, wasm.

### ISSUE THREAD

**Issue by CommanderXL** [emscripten-core/emscripten#18713]
**Version of emscripten/emsdk:**
emcc: 3.1.31;
clang version: 17.0.0;

**Failing command line in full:**
```shell
em++ amrnb.bc -O3 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=524288 -s TOTAL_STACK=65536 -s \
		EXPORTED_FUNCTIONS="['_Decoder_Interface_init','_Decoder_Interface_exit','_Decoder_Interface_Decode','_Encoder_Interface_init','_Encoder_Interface_exit', '_Encoder_Interface_Encode']" \
		--pre-js pre.js --memory-init-file 0 -o out.js
```

The background:

I try to clone [an old repo](https://github.com/yxl/opencore-amr-js) that port open-amrcore to wasm，
It has two phase in the `js/Makefile`: one for generating llvm bitecode, next step using em++ for transferring  bitecode to js and wasm.

Well, the old repo was 8 years ago. The first phase(using `automake`、`autoconf`) which generating llvm bitecode (about 890KB) is ok. But the second step does not meet expectations, because the output js file contains only a little js glue code (16KB), and 8 years ago using emscripten tool output js code (500KB) compared to the lack of a lot of content, giving the impression that emscripten did not successfully convert llvm bitecode to js, wasm.

I'm not sure if it's the version of emscripten that's causing the problem, it's 8 years old after all. So how can I fix this problem now? Successfully converted llvm bitecode to the js, wasm code I was expecting.

**Comment by sbc100** [comment]
These days you should get an `.js` and `.wasm` fie alongside it.

These days there is no need to llvm bitcode at all.   You can just compile you sources to object files and link them with em++.   As an implementation detail of the object files themselves might still be bitcode if you compile with `-flto`.

For `EXPORTED_FUNCTIONS` can you can also switch the simpler form which is `-s_Decoder_Interface_init,_Decoder_Interface_exit,_Decoder_Interface_Decode`
