### ISSUE TITLE
Global function pointers do not work with dlopen dynamic linking and threads

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#18719]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.27 (afa75f342eef4d925172479afa8e6233eb0ae5a9)
clang version 16.0.0 (https://github.com/llvm/llvm-project dee009d3b5c71a340eb4ebb3cfb49f6015a789cc)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/apple/emsdk/upstream/bin
```

I have created a simple reproducer [here](https://github.com/ravisumit33/emscripten-bug-reproduce)
If you build the reproducer, it generates two files - `test.html`(without threads) and `test_mt.html`(with threads)

Running `test.html` works as expected giving the following output:
```
Inside fun
Inside my create
6
```

But running `test_mt.html` gives a runtime error of function signature mismatch:
```
Inside fun
Uncaught RuntimeError: null function or function signature mismatch
    at fun (side.cpp:20:10)
    at __original_main (main.cpp:24:16)
    at _main_thread (crt1_proxy_main.c:29:13)
    at Object.invokeEntryPoint (test_mt.js:4236:42)
    at self.onmessage (test_mt.worker.js:163:35)
```

It looks like with threads enabled `fun_ptr()` call is failing to resolve. If I only declare `fun_ptr` globally and do`fun_ptr = my_create` inside`fun` function of if I make that `fun_ptr` local by defining it inside `fun` function it works as expected. Looks like function pointers in side module in global scope creates issue with dlopen dynamic linking. I also checked with load time dynamic linking by giving side module at command line to main module and it worked as expected.

**Comment by sbc100** [comment]
Thanks for the repro case.   If you get a chance you try with `tot` version of `emsdk`?  There have been some very recent changes to how threads and dlopen work together.   Otherwise I will try to take a look soon.

**Comment by ravisumit33** [comment]
@sbc100 I will try with `tot` version. I updated some of my findings in the descripton may be that helps.

**Comment by ravisumit33** [comment]
@sbc100 Thanks for the suggestion. Issue is not reproducible on tot. Closing this issue.

**Comment by kleisauke** [comment]
Just wondering, was this fixed with commit https://github.com/llvm/llvm-project/commit/a0495e6b008c7b1f5af2d0756bf62aefdc6a43ea?

I noticed a similar issue on Emscripten v3.1.31 when compiling the develop branch of zlib-ng. Reverting commit https://github.com/zlib-ng/zlib-ng/commit/101653c0201a2f487ca7268dd23c5b62c9ad9c79 or building with Emscripten v3.1.32 seems to fix that (see e.g. commit https://github.com/kleisauke/wasm-vips/commit/e1d90f0f60efb4528784709332e1cdf06b8bc060 for details).

**Comment by sbc100** [comment]
That llvm commit would have fixed that issue it if was related to relocations in TLS data.

**Comment by sbc100** [comment]
I suspect that this particular issue was likely fixed by something on the emscripten side though.
