### ISSUE TITLE
Can't set break point when build with "-g -sEVAL_CTORS"

### ISSUE THREAD

**Issue by xbcnn** [emscripten-core/emscripten#18766]
Please include the following in your bug report:

emsdk: 3.1.28
```
% emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.28 (f11d6196dd4e8748a726f19895c859b40ff6a4f3)
clang version 16.0.0 (https://github.com/llvm/llvm-project ea4be70cea8509520db8638bb17bcd7b5d8d60ac)
Target: wasm32-unknown-emscripten
```

Can be reproduced by following simple src:
```
int main(void) {
    return 1+1;
}
```

command line:
`emcc -o a.html a.cc -g  -sEVAL_CTORS=2`

Open Chrome-Devtools-src tab, open the file, the line number panel is greyed and can NOT set break points there.
While using `emcc -o a.html a.cc -g` is OK.

I can see the symbol sections with `wasm-objdum`
```
test % wasm-objdump a.wasm -h

a.wasm:	file format wasm 0x1

Sections:

     Type start=0x0000000a end=0x0000002f (size=0x00000025) count: 7
 Function start=0x00000031 end=0x00000043 (size=0x00000012) count: 17
    Table start=0x00000045 end=0x0000004a (size=0x00000005) count: 1
   Memory start=0x0000004c end=0x00000052 (size=0x00000006) count: 1
   Global start=0x00000054 end=0x00000068 (size=0x00000014) count: 3
   Export start=0x0000006b end=0x00000166 (size=0x000000fb) count: 13
     Code start=0x00000169 end=0x00000324 (size=0x000001bb) count: 17
   Custom start=0x00000327 end=0x00000471 (size=0x0000014a) "name"
   Custom start=0x00000474 end=0x000025aa (size=0x00002136) ".debug_info"
   Custom start=0x000025ad end=0x00002737 (size=0x0000018a) ".debug_loc"
   Custom start=0x0000273a end=0x00002a28 (size=0x000002ee) ".debug_ranges"
   Custom start=0x00002a2b end=0x00003076 (size=0x0000064b) ".debug_abbrev"
   Custom start=0x00003079 end=0x0000381c (size=0x000007a3) ".debug_line"
   Custom start=0x0000381f end=0x00004776 (size=0x00000f57) ".debug_str"

```

And here is the output in Console, which indicates it found and loaded the symbols.
```
[C/C++ DevTools Support (DWARF)] Loading debug symbols for http://localhost:8080/a.wasm...
[C/C++ DevTools Support (DWARF)] Loaded debug symbols for http://localhost:8080/a.wasm, found 17 source file(s)
```

Might be a bug? @kripken @sbc100

**Comment by kripken** [comment]
This is likely because running the `wasm-ctor-eval` tool changes the debug info, maybe removing or incorrectly updating things. Similar things happen in `-O2` and above from running `wasm-opt`.

Can you avoid running ctor-eval in a debug build? It's mainly useful for release build performance, not local debugging.

**Comment by xbcnn** [comment]
> Can you avoid running ctor-eval in a debug build? It's mainly useful for release build performance, not local debugging.

Sure. We have done that.  Previously we added the `-sEVAL_CTORS` in common setting for several build types.

I just curious what the `wasm-ctor-eval` tool changed and how/where to start investigation.  And I doubt it could potentially still destroy things for using separate symbols of release build later(but seems not supported yet?).

**Comment by sbc100** [comment]
While symbols files work fine in release mode, if you what full DWARF debug info there are several post-link steps used in release builds (e.g. `wasm-ctor-eval`, but others too) that can limit or damage the DWARF info.    Conversely if you enable DWARF info in release builds there are some binaryen optimizations that cannot be run, so its best to avoid using DWARF for your actual release build.

**Comment by kripken** [comment]
> I just curious what the wasm-ctor-eval tool changed 

In general it will read the wasm, eval and optimize, and write it back out, so it could end up removing or modifying debug info in any part of the optimizer. All the binaryen tools are known to have limitations with DWARF processing - that's not a use case that has been focused on much - so in general we recommend debugging without binaryen optimizations when using DWARF. As @sbc100 said, the use cases are generally separate anyhow: DWARF for local debugging, and without DWARF for optimized release builds.

**Comment by xbcnn** [comment]
OK, I see. Thanks @kripken @sbc100 for the explanations.

**Comment by xbcnn** [comment]
btw, is that possible to generate split DWARF file for release build, so that it can be used for postmortem analysis like PDB does on Windows?

**Comment by sbc100** [comment]
If you want basic stack trace information for you release builds that that is fairly simple.

If you want full DWARF information for your release builds it is a little more complicated.    Just like on native platform the DRAWF information will be lot less useful and lot more spotty in its coverage in release build.  

Unlike native platforms we actually have to turn off  some optimizations completely when you enable DWARF (because binaryen doesn't know how to transform it in all cases).   It not a lot, but you may loose some amount of optimization if you do this.

**Comment by xbcnn** [comment]
> If you want basic stack trace information for you release builds that that is fairly simple.

Did you mean symbol map, by adding linker option `--emit-symbol-map` ?  I don't know if there are other ways.

**Comment by kripken** [comment]
There is support for [separate dwarf](https://emscripten.org/docs/tools_reference/emcc.html) using `-gseparate-dwarf`, but it does have the downsides @sbc100 mentioned with optimizations and accuracy.

Yes, `--emit-symbol-map` is the best approach if all you need are stack traces. That does not affect optimizations at all.

**Comment by xbcnn** [comment]
Get it.  Thanks.

**Comment by sbc100** [comment]
Actually, if you just want backtraces you don't even need a symbol map.  You can just use `--profiling-funcs` to ensure a name section exists in the output.
