### ISSUE TITLE
cmake cache makes upgrade fail

### ISSUE THREAD

**Issue by elalish** [emscripten-core/emscripten#18763]
I'm on macOS, having installed emscripten before via homebrew, which worked great, with v3.1.24. When I ran `brew upgrade` it happily upgraded emscripten to 3.1.31 along with everything else (apparently successfully). However, on running `emcmake cmake -DCMAKE_BUILD_TYPE=Release .. && emmake make`, it didn't work, saying it couldn't find 3.1.24. It pointed me to the following file, and I eventually found the problem at the following lines: https://github.com/emscripten-core/emscripten/blob/main/cmake/Modules/Platform/Emscripten.cmake#L90-L97

These `CACHE` indicators apparently cache the value forever and there's no easy way to change them after first run, so even though the whole system was happy with 3.1.31, it keeps trying to use the cached value from 3.1.24. Remove those `CACHE` statements fixed the problem, and I doubt they're significantly improving performance anyway. Cmake recommends they not be used except for things that never change: https://cmake.org/cmake/help/book/mastering-cmake/chapter/CMake%20Cache.html

**Comment by sbc100** [comment]
Did the path to the compilers change when updated then?  i.e. is the version number embedded in the path?

My initial response would be that cleaning your entire build directory (cache and all) is the probably good thing to do when you upgrade your compiler, but I guess we should see what other toolchains do for these value.

**Comment by sbc100** [comment]
Having looked around at other toolchain files I'm inclined to agree.  Would you like to send a PR to remove these?

**Comment by elalish** [comment]
Yes, the version is embedded in the path (at least on homebrew). You may be right - I had thought the cache was somewhere deeper than that when it pointed me to emscripten.cmake, but perhaps it is in the cache of my local build. Still, it's nice to avoid a confusing error and another reason to have to blow up the build directory. 

Yes, I can send a PR.

**Comment by juj** [comment]
There is no need to blow up the build directory. Deleting `CMakeCache.txt` alone would help.

One benefit of having the cache has been that one can do subsequent reconfigures of the project without needing to rebuild the same environment on each `make` step that was used to originally invoke the first `emcmake cmake` call.

I.e. when the paths to emcmake and Emscripten are cached, CMake will remember what the compiler was that was used to originally configure, and later configures repeat that configuration. I saw that to be a feature before.

Looking at https://gitlab.kitware.com/cmake/cmake/-/issues/20225 there is no consensus whether the paths should, or should not be cached by toolchains. Checking out e.g. native make against macOS Clang, I see that there is inconsistency in that CMAKE_C/CXX_COMPILER is not cached, but e.g. CMAKE_AR is. Figures.

I am open going either way with this, although it is good to recognize that landing the PR will affect existing behavior as well.

**Comment by sbc100** [comment]
Can you explain a little more about what you think the benefits to caches these might be? 

For steps that involve building and running code (e.g. checking the size of int) I can see the value of caching because it means the step doesn't need to be repeated each time you run cmake.

However, for simple paths like this, there is no cost to setting it, its simply hardcoded.    What am I missing here?

**Comment by ericoporto** [comment]
https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry

from what I can tell from the docs, the cache stuff means that a previous set variable is not overwritten, so you can set it once and then rerun cmake without setting those again.

And then there is this in the docs:

> Furthermore, if the <type> is PATH or FILEPATH and the <value> provided on the command line is a relative path, then the set command will treat the path as relative to the current working directory and convert it to an absolute path.

So the relative paths become absolute, and then it happens what elalish is saying it does - I haven't actually experienced that but it's what I can tell.

> However, for simple paths like this, there is no cost to setting it, its simply hardcoded. What am I missing here?

There is actually a difference of how these behave in scope, between a cache entry and a variable. Can't we run these with a FORCE on activate?

**Comment by sbc100** [comment]
`emsdk activate` is something that is run when the emsdk is installed.  User could have any number of different cmake build directories, and emsdk is not aware of them.

@ericoporto do you see anything wrong with the proposed solution of removing the CACHE keyword?

**Comment by ericoporto** [comment]
no, I don't really, was just giving an alternative using FORCE. But yes, it does look fine to remove too, I think I wrote this in a more complicated way than I should.

**Comment by ericoporto** [comment]
Ah, @juj is the author of the original commit with a cache there: https://github.com/emscripten-core/emscripten/commit/cfecdac66f1bde8da28adf34d782cfff6be9f83e

**Comment by ericoporto** [comment]
ok, I figured what this does. When running `ninja` (just ninja, no additional commands here) in command line, if any CMakeLists.txt file has been touched or similar, it will automatically rerun the CMake configuration. But because things are cached, it doesn't need emcmake to run, and all things work.
