### ISSUE TITLE
runtimeKeepalivePush does not work with EXIT_RUNTIME=0

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#18782]
Most of the `test_pthread_proxying*` tests run with `EXIT_RUNTIME=1` because they incorrectly hang otherwise. If I remember the details of our investigation into this correctly, it was because those tests are waiting for a thread to receive a message, but the thread has unexpectedly already exited, so it never receives the message. The tests are careful to use `emscripten_exit_with_live_runtime` or `emscripten_keepalive_push`, but these fail to actually keep the runtime alive with EXIT_RUNTIME=0, since in that mode `runtimeKeepaliveCounter` is ifdeffed out entirely.

**Comment by sbc100** [comment]
I think the root cause is #16339.  I'm working on change that basically reverts this.
