### ISSUE TITLE
Dwarf debug with source code on remote server

### ISSUE THREAD

**Issue by junyuecao** [emscripten-core/emscripten#18797]
I was trying to find a way to debug with dwarf and everything look good to me when I am developing on a local machie. But for remote developing I am not able to debug because the file path in dwarf is the path on that remote server. Devtools shows an error  like this 
![image](https://user-images.githubusercontent.com/1000408/219953085-b29c910a-1dc6-43ab-b970-f32624865614.png)

So how can we change the path in the dwarf file or specify another URL when compiling?

**Comment by sbc100** [comment]
@pfaffe might know about this?

**Comment by xbcnn** [comment]
I think you should add path substitutions to your `C/C++ DevTools Support extension` option.

**Comment by junyuecao** [comment]
@xbcnn Thank you. That's exactly what I am looking for. 

Thanks @sbc100 by the same.
