### ISSUE TITLE
std::format not available in emscripten

### ISSUE THREAD

**Issue by alienself** [emscripten-core/emscripten#18795]
Hi, 

I would like to use std::format in my c++ code with emscripten, however I am not able to do so.

here is my code

```c++
#include <iostream>
#include <format>

int main() {
    int x = 42;
    std::string s = "hello";
    double d = 3.14159;
    std::string result = std::format("x = {}, s = {}, d = {}", x, s, d);
    std::cout << result << '\n'; // prints "x = 42, s = hello, d = 3.14159"
}
```

Please include the following in your bug report:

**Version of emscripten/emsdk:**
`emcc version 3.1.3`

```sh
 no member named 'format' in namespace 'std'
    std::string result = std::format("x = {}, s = {}, d = {}", x, s, d);   
```

I added `-std=c++20` and even `-std=c++2b` to emcc but no luck

Any idea how to get this to work?

**Comment by sbc100** [comment]
Emscripten uses a mostly unmodified version libc++from llvm.   It was last updated in #18612.  It looks like we currently track 15.0.7, which is that latest stable llvm release.  I imagine that std::format was not part of llvm 15 and this will be available once we update to llvm 16 (once llvm 16 is released).

**Comment by bedrich-schindler** [comment]
Version 3.1.20 was working correctly with `std::format`. After update to version 3.1.45, it was necessary to add flag `-fexperimental-library` to make it working.  Reason is update of LLVM from 14 to 15 in version 3.1.20.

**Comment by sbc100** [comment]
Thanks @bedrich-schindler.  I'll close this issue for now then.  Feel free to re-open.
