### ISSUE TITLE
Feature Request: MINIMAL_RUNTIME + MODULARIZE selective export of symbols

### ISSUE THREAD

**Issue by DavidPeicho** [emscripten-core/emscripten#18814]
**Version of emscripten/emsdk:** **3.1.31**

We had a big discussion in #17911 and I think it would be great to talk about that again. The current solution to export symbols on `Module` with MINIMAL_RUNTIME+MODULARIZE is to use `EXPORT_ALL` (added in the linked PR). However, this is also going to export internal library symbols, which is most likely not wanted.

Some of the ideas that were added in the PR:
* Create a new `EMSCRIPTEN_EXPORT` macro
* Create a new flag `EXPORT_KEEPALIVE`

From what I remember, `EMSCRIPTEN_EXPORT` required a patch to LLVM, so I would vote for the second solution. If I am correct, the solution would be to take all kept alive symbols and to append it to `EXPORTED_FUNCTIONS`. AFAIK, this should just work because `EXPORTED_FUNCTIONS` is used here: https://github.com/emscripten-core/emscripten/blob/fbc5d5c23a02659530101ce9405a4221bc5aed0f/src/jsifier.js#L424

Am I correct? If you are happy with the idea, I can start implementing it, maybe with some guidelines.

**Comment by DavidPeicho** [comment]
I am also wondering what should we do about other stuff like `HEAP8`? Is that supposed to be manually exported inside a library?

**Comment by sbc100** [comment]
I kind of like that idea of a  new flag `EXPORT_KEEPALIVE` which could default to 1 for the normal runtime (so as not to break existing code) but default to 0 for minimal runtime.   Then you could set that flag to have just the keepalive subset of symbols exported?

Obviously being able to choose on a per-symbol basis would be better but also a lot more work to make it happen.

Regarding `HEAPX` symbols, I think we they should probably be treated as if they were JS library symbols (i.e. they should be exportable via `-sEXPORTED_FUNCTIONS`.

**Comment by DavidPeicho** [comment]
Good idea! Made a PR here: #18819

For the `HEAP` symbols, this should maybe be another PR.
