### ISSUE TITLE
Return response from asynchronous fetch call made inside C++ function bound using Embind

### ISSUE THREAD

**Issue by harichards** [emscripten-core/emscripten#18834]
I am writing a function in C++ that uses the Emscripten Fetch API. This function is invoked from JavaScript using Embind. I would like to return the response of an asynchronous Fetch call back to JS. Ideally, I would return a promise, as is the case when using Asyncify. However, according to https://github.com/emscripten-core/emscripten/issues/12255, Fetch is not compatible with Asyncify.

Here is an attempt at a solution, but it does not return a promise like Asyncify would:

```cpp
#include <emscripten/bind.h>
#include <emscripten/fetch.h>

#include <future>

unsigned short worker()
{
    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);

    strcpy(attr.requestMethod, "GET");
    attr.attributes = EMSCRIPTEN_FETCH_SYNCHRONOUS;
    
    emscripten_fetch_t *fetch = emscripten_fetch(&attr, "https://example.com/");
    auto status = fetch->status;
    emscripten_fetch_close(fetch);

    return status;
}

unsigned short foo()
{
    auto status = std::async(&worker);
    return status.get();
}

EMSCRIPTEN_BINDINGS(my_module)
{
    emscripten::function("foo", &foo);
}
```

What would be the best way to accomplish this? Any help would be greatly appreciated. Thanks!

**Comment by sbc100** [comment]
We have recently add a C and C++ interface to JS promises.  See #18598.

However, making this work with embind would likely require some kind of magic such that the actual JS promise is returned rather then integer handle.  @tlively @brendandahl any ideas?

**Comment by sbc100** [comment]
@tlively I guess step one would be some kind of std::future and promise.h integration?   i.e. being able to create a promise based on a std::future?

**Comment by sbc100** [comment]
`PROXY_TO_PTHREAD` only applies to the main function itself.   If you call `foo` from the main thread it will still run on the main thread. 

We have APIs for proxying other work to background threads though.   See `threading.h` and the new `proxying.h`

**Comment by tlively** [comment]
> @tlively I guess step one would be some kind of std::future and promise.h integration? i.e. being able to create a promise based on a std::future?

Although it may be possible to integrate with `<future>` via a custom `std::launch` flag, I expect that using C++20 coroutines (which are completely unrelated to `std::future`, unfortunately) will be a better match.

I don't know enough about embind to say what would be required to make it work nicely with promise.h. Once we have a C++ API for promises, let's discuss this again and figure something nice out.
