### ISSUE TITLE
Efficient Single Threaded Main Loop 

### ISSUE THREAD

**Issue by Grey41** [emscripten-core/emscripten#18843]
In my program, it’s necessary that I return from the caller after the main animation loop has ended. For example, I used to use the following while loop:

```c
static int program() {
    while (!glfwWindowShouldClose(window)) {
        // render; swap buffers
        if (error) return -1;
    }

    printf("Program completed!\n");

    return 0;
}
```

I can’t use `emscripten_set_main_loop` because it exits the thread. I also tried `emscripten_request_animation_frame_loop`, but this doesn’t work either.

Is there any way of creating an efficient loop? I want to be able to return a status code after the program has completed.

**Comment by sbc100** [comment]
`emscripten_set_main_loop` is designed for this purpose.     Its not perfect, and it may still require you to do some refactoring of your code, but its the best we can do on the web we you can't actually block the main loop.  Have you read the docs for (including the `simulate_infinite_loop` arg): 
 https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_set_main_loop

Can you clarify what you mean by "cancelling the loop terminates the program"?   If you want to keep the program alive there are several options available to you.  See `emscripten_exit_with_live_runtime` and `emscripten_runtime_keepalive_push` for example.

**Comment by Grey41** [comment]
Thanks for the extra info. My program involves the Python interpreter and according to the docs, the exception state is maintained per-thread.

> unhandled exceptions are automatically propagated to the caller, then to the caller’s caller, and so on, until they reach the top-level interpreter, where they are reported to the user accompanied by a stack traceback.

So I need to find some way of maintining the thread for exceptions. This person seems to have the same problem: <https://news.ycombinator.com/item?id=29376774>.

You mentioned that you can't block the main loop on the web, but I also need to return the state to the Python interpreter.

**Comment by sbc100** [comment]
You might want to look at ASYNCIFY: https://emscripten.org/docs/porting/asyncify.html.  This is way to suspend and resume the wasm portion of your program but it comes with some performance and size costs.

Another alternative is run basically all of your code on a background thread, and just use the main thread to send it work and get results back.

**Comment by Grey41** [comment]
Asyncify is the solution. It’s a shame about the impact on performance and size but it does solve my problem. Thank you for the answer.

**Comment by brendandahl** [comment]
You may want to keep an eye on [JavaScript Promise Integration](https://v8.dev/blog/jspi). That should give a lighter weight solution when standardized. We have experimental support for it in emscripten.
