### ISSUE TITLE
 "Blocking on the main thread is very dangerous...." show up despite of setting ALLOW_BLOCKING_ON_MAIN_THREAD=1

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#18855]
"Blocking on the main thread is very dangerous...." show up despite of setting ALLOW_BLOCKING_ON_MAIN_THREAD=1.

emcc : 3.1.29
OS: Windows 11

**Comment by kripken** [comment]
I think I remember discussing this in an issue back then with @RReverser . Maybe the concern was that this is an easy cause of deadlocks, so the warning is still worthwhile even with the flag? But perhaps it could be behind ASSERTIONS or PTHREAD_DEBUG in that case.

**Comment by RReverser** [comment]
> I think I remember discussing this in an issue back then with @RReverser .

I don't remember that discussion tbh - I don't think I was involved with this warning - but looks like it's already shown only under `ASSERTIONS`? https://github.com/emscripten-core/emscripten/blob/cc8f7a2ffe2205b935f325fceaea1500ba05f3ec/src/library_pthread.js#L911

**Comment by kleisauke** [comment]
I remembered having seen a similar issue in wasm-vips, let me try to upstream commit https://github.com/kleisauke/emscripten/commit/c245e7da54e945b724c0e41ad6eb0d738b2d8229.

**Comment by kleisauke** [comment]
I just opened PR #18871 for this.
