### ISSUE TITLE
Try to use emscripten to build ngnix, but something wrong

### ISSUE THREAD

**Issue by hungryzzz** [emscripten-core/emscripten#18878]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.24 (68a9f990429e0bcfb63b1cde68bad792554350a5)
clang version 16.0.0 (https://github.com/llvm/llvm-project 277c382760bf9575cfa2eac73d5ad1db91466d3f)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Failing command line in full:**
I try to run standalone `nginx.wasm` generated by emscripten in WasmEdge but I get something wrong, followings are my steps to do it (on 20.04.1-Ubuntu):
1. Build nginx(v1.23.3) using Emscripten
- `emconfigure ./configure --without-http_rewrite_module --without-http_gzip_module --with-cc-opt="-Wno-sign-compare"`
- `emmake make`
When I run the second cmd, I meet some errors but solve them by adding two build options(-sSTANDALONE_WASM -sERROR_ON_UNDEFINED_SYMBOLS=0) in file obj/Makefile.
![1677656089194](https://user-images.githubusercontent.com/32137313/222087685-c138a85a-ac99-4669-8421-8bf9d9be079d.jpg)
After building it successfully, I can find the final .wasm file in obj/nginx.wasm.

2. Execute the nginx in WasmEdge using sudo wasmedge nginx.wasm -v, but I get the errors as following:
```
[2023-03-01 02:21:49.361] [error] instantiation failed: unknown import, Code: 0x62
[2023-03-01 02:21:49.361] [error]     When linking module: "env" , function name: "getaddrinfo"
[2023-03-01 02:21:49.361] [error]     At AST node: import description
[2023-03-01 02:21:49.361] [error]     This may be the import of host environment like JavaScript or Golang. Please check that you've registered the necessary host modules from the host programming language.
[2023-03-01 02:21:49.361] [error]     At AST node: import section
[2023-03-01 02:21:49.361] [error]     At AST node: module
```
It seems that the `env` library is lack in the compiled `.wasm` file, so the runtime can't find it. 
And I also compie the nginx to `.wasm` with JS glue code, an object defined by JS is imported to the `wasm` module, which contains these functions.
Is there something wrong during the building or do I need to add some other options when building to get this `env` lib?
Thanks a lot!

**Comment by sbc100** [comment]
It looks like you are trying to run the resulting module in pure-wasm runtime?

If you want to do that you would need to either remove the dependency of your program on symbols like `getaddrinfo` or somehow implement those symbols in the runtime.

There is no way to implement `getaddrinfo` in the wasm module itself, because it depends on the system network stack.

**Comment by hungryzzz** [comment]
Okay I got it! Thank you for your answer!
