### ISSUE TITLE
 "GetMainExecutable is not implemented" (and other errors) when building LLVM with latest Emscripten

### ISSUE THREAD

**Issue by donalffons** [emscripten-core/emscripten#18898]
I'm working on a project that uses [llvm-project](https://github.com/llvm/llvm-project) compiled via Emscripten. After running into some issues with Emscripten `3.1.32`, I did some research and realized that the same exact error happens in [jprendes/emception](https://github.com/jprendes/emception) (/cc @jprendes). The build works fine up to Emscripten `3.1.31` (this can be easily verified by [changing the Emscripten version in the Dockerfile](https://github.com/jprendes/emception/blob/master/docker/Dockerfile#L3)).

The error happens during compilation on [this line](https://github.com/jprendes/emception/blob/master/build-llvm.sh#L96) with the following message:
```
/home/user/emception/upstream/llvm-project/llvm/lib/Support/Unix/Path.inc:333:2: error: GetMainExecutable is not implemented on this host yet.
#error GetMainExecutable is not implemented on this host yet.
```
The error messages is produced [on this line by llvm](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Unix/Path.inc#L333). Updating llvm to the latest version (by removing [this line](https://github.com/jprendes/emception/blob/master/build-llvm.sh#L29)) does not resolve the error.

As a workaround, I tried manually #defining `__linux__`, which resolves this particular error. But then other errors arise (undefined SYS_gettid, undefined syscall, ...)

**Comment by sbc100** [comment]
I think this relates to `dladdr`.  The stub for this function was inadvertently removed in 3.1.32 and the fix for that is in #18896.

However that llvm code in question probably shouldn't be using `dladdr` since that has never actually worked in emscripten.    A batter solution that might have a chance of actually working would be to add `__EMSCRIPTEN__` to this line: https://github.com/llvm/llvm-project/blob/2708869801ae00f4681f6b2d9d69b25b3fce26b6/llvm/lib/Support/Unix/Path.inc#L253

**Comment by donalffons** [comment]
With the change you suggested (and also adding `defined(__EMSCRIPTEN__)` [here](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Unix/Path.inc#L129), because otherwise the compiler complains about `getprogpath` not being defined), the compilation stage seems to work alright, but then I get this error in the linker stage:

```
wasm-ld: error: lib/libclang.a(CIndexer.cpp.o): undefined symbol: dladdr
```

I guess I could define a stub for that function somewhere... But with the PR you mentioned, I assume this problem will also get resolved. The bits of LLVM that I've been using (mostly clang / libclang), have worked without issues so far. So I believe that code probably doesn't rely on `dladdr`.

Thanks a ton for your help. I appreciate it a lot!

**Comment by sbc100** [comment]
Indeed, what I guess you have been doing is building a version of llvm that includes several calls to `dladdr`, but doesn't actually depend the result at runtime.  

If you are ever interested in trimming the fat and producing a more optimimal binary that doesn't included any stub/missing functions you can use the `-sALLOW_UNIMPLEMENTED_SYSCALLS=0`.

In the mean time #18896 should be in the next release which I hope will be early next week.
