### ISSUE TITLE
the cppm extension is not supported.

### ISSUE THREAD

**Issue by karikera** [emscripten-core/emscripten#18910]
**Version of emscripten/emsdk:**
3.1.32

**Failing command line in full:**
+ `emcc foobar.cpp -std=c++20` - succeeded. emcc+cpp (even `foobar.cpp` is a c++20 module)
+ `clang foobar.cppm -std=c++20` - succeeded. clang+cppm
+ `emcc foobar.cppm -std=c++20` - **failed**. emcc+cppm

**Comment by karikera** [comment]
is there a way to bypass this issue?
I want to use the ixx extension for matching with VC++ filenames.
Ironically, VC++ refuses to export a module in cpp extensions.

**Comment by sbc100** [comment]
Sure we can add `.cppm` to the list of extensions we consider source files.

What is the `ixx` issue?  Is that separate?

**Comment by karikera** [comment]
> Sure we can add `.cppm` to the list of extensions we consider source files.
> 
> What is the `ixx` issue? Is that separate?

Thanks for your support. :)

`.ixx` is the file extension of the C++20 module in VC++. (another name for cppm)
but clang also can't compile it. maybe a little out of emscripten issues.
