### ISSUE TITLE
gmp emconfigure cannot determine label suffix

### ISSUE THREAD

**Issue by LeenHawk** [emscripten-core/emscripten#18965]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```shell
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/leen/tools/emsdk/upstream/bin
```

**Failing command line in full:**
```shell
wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
tar -xvf gmp-6.2.1.tar.xz && cd gmp-6.2.1
emconfigure ./configure
```
**Output:**
[configure.txt](https://github.com/emscripten-core/emscripten/files/10976527/configure.txt)

**Comment by sbc100** [comment]
The WebAssembly assembly format using in llvm is somewhat nonstandard so it not particularly surprising that it can't figure this out.

Furthermore even if could determine the label suffix it seems unlikely this project has wasm assembly language in it.  Is it possible to simply disable all the assembly features instead?  (that seems like the easiest/only way to get such a project working without having to port the asm).

**Comment by LeenHawk** [comment]
> The WebAssembly assembly format using in llvm is somewhat nonstandard so it not particularly surprising that it can't figure this out.
> 
> Furthermore even if could determine the label suffix it seems unlikely this project has wasm assembly language in it. Is it possible to simply disable all the assembly features instead? (that seems like the easiest/only way to get such a project working without having to port the asm).

I’ll find a way.

**Comment by qingyuealone** [comment]
How did you solve this issue? I am also compiling GMP with similar emcc configuration as yours.

**Comment by danieljohnprojects** [comment]
I got it working using `emconfigure ./configure --enable-cxx --host wasm32` rather than `emconfigure ./configure`.
