### ISSUE TITLE
EM_JS functions go missing when linked from an archive

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#18982]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
```

**Failing command line in full:**
main.c:
```C
void emjs_func(void);

int main(void) { 
   emjs_func();
   return 0; 
}
```
archive.c:
```C
#include <emscripten.h>

EM_JS(void, emjs_func, (), {
   console.log("Hello!");
})
```

Build as follows:
```
emcc -c main.c
emcc -c archive.c
emar rcs libarchive.a archive.o
emcc main.o libarchive.a
```
Fails with:
```
wasm-ld: error: main.o: undefined symbol: emjs_func
emcc: error: '/home/ubuntu/pyodide/emsdk/emsdk/upstream/bin/wasm-ld -o a.out.wasm main.o libarchive.a -L/home/ubuntu/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpv5d6hapt.undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
```

On the other hand, if we link using `archive.o` instead of `libarchive.a` the linker succeeds and the result program works (it prints `Hello` and quits with exit code 0). 
```
emcc main.o archive.o
```
The following also works:
```
emcc main.o libarchive.a -s MAIN_MODULE=1
```

**Full link command and output with `-v` appended:**
#### Input:
```
$ emcc main.o libarchive.a -v
 "/home/ubuntu/pyodide/emsdk/emsdk/upstream/bin/clang" --version
 "/home/ubuntu/pyodide/emsdk/emsdk/upstream/bin/wasm-ld" -o a.out.wasm main.o libarchive.a -L/home/ubuntu/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpl8dzjigo.undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first
wasm-ld: error: main.o: undefined symbol: emjs_func
emcc: error: '/home/ubuntu/pyodide/emsdk/emsdk/upstream/bin/wasm-ld -o a.out.wasm main.o libarchive.a -L/home/ubuntu/pyodide/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/tmp/tmpl8dzjigo.undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
```

@antocuni

**Comment by sbc100** [comment]
This is an extension of #18927, but a little harder to solve.  

There are a couple of workaround you could use for now:

1. Create a defined wrapper around your undefined `emjs_func` function.   e.g. 

```
EM_JS(void, emjs_func_impl, (), {
   console.log("Hello!");
})

void emjs_func() {
  emjs_func_impl();
}
```

2. Use `-Wl,--whole-archive libarchive.a -Wl,--no-while-archive` to force the object in question to be included.

3. Use `-Wl,-u,emjs_func` which I think might also force the object to be included (not sure about this one, I didn't test it).

**Comment by hoodmane** [comment]
Thanks @sbc100. For now we can use `--whole-archive`.

But I would like to get archives with `EM_JS` functions to be first class citizens. There are a few things needed for this:

1. A fix for this bug
2. A way to ask for C functions to be added to `EXPORTED_FUNCTIONS` from inside the C source.
3. A way to ask for runtime dependencies to be added to `EXPORTED_RUNTIME_METHODS` from inside the C source (I think `EM_JS_DEPS` already does this.)

**Comment by sbc100** [comment]
With (2) are you talking about function that live inside of `.a` archives?

I think even if we fix (1) (and (3) as you say is already fixed I think), I'm not sure how we can make `EXPORTED_FUNCTIONS` work for object files that are inside of `.a` archives are are not included in the link. 

In other words I think (1) and (3) are achievable, but I'm not sure (2) is.  At least not without some fundamental change in the way the linker handler `.a` archives.    Likely there are several workaround for (2), depending on your use case.  For example, or you can use symbol dependencies to force a given object to be loaded out of a `.a` archive, and once that happens the `EXPORTED_FUNCTIONS` in that file will be honored.

**Comment by hoodmane** [comment]
> once that happens the `EXPORTED_FUNCTIONS` in that file will be honored.

What does the `EXPORTED_FUNCTIONS` in a file mean? How can I ensure that a function is in the list?

>  For example, or you can use symbol dependencies to force a given object to be loaded out of a .a archive

For instance I could have a symbol in `library_exports.o` that depends on a symbol in each other file in the archive? Is there some `__attribute__((depends_on(symbol_b)))` that can force the linker to think that `symbol_a` depends on `symbol_b`? Or should I make a no-op function in each compilation unit and call it from `library_exports`?

**Comment by sbc100** [comment]
I don't think there is any kind of `depends_on` attribute, but you easily create a dummy reference.  For example:
`static void* myaddr = &myfunc` in a `.o` file will cause `myfunc` to be undefined and therefor the object in which it is defined will be pulled out of the `.a` archive.

**Comment by hoodmane** [comment]
What about the `EXPORTED_FUNCTIONS` question? I assume that putting `EMSCRIPTEN_KEEPALIVE` in front of a symbol does less than adding it to the `-sEXPORTED_FUNCTIONS` list?

**Comment by sbc100** [comment]
1EMSCRIPTEN_KEEPALIVE` does the same thing as adding it to `-sEXPORTED_FUNCTIONS`, but only if the object file which contains the symbol is included by the linker.

**Comment by hoodmane** [comment]
I'm having trouble getting this `static void* myaddr = &myfunc` trick to work. Is there a verbose flag that I can use to make the linker explain its reasoning in a bit more detail?

**Comment by hoodmane** [comment]
Nevermind, I got it to work by actually calling a function.
