### ISSUE TITLE
audioWorklet userData

### ISSUE THREAD

**Issue by Jonathhhan** [emscripten-core/emscripten#18989]
I wonder, if it is possible to pass a struct like this as userData:
```
struct AudioStruct{
  int numInputs = 0; 
  int numOutputs = 0; 
  ofBuffer inBuffer; 
  ofBuffer outBuffer; 
}
```
```
AudioStruct audioData;  //defined somewhere in the class 

        audioData.inputs = 2; 
        audioData.outputs = 0; 
	emscripten_start_wasm_audio_worklet_thread_async(context, wasmAudioWorkletStack, sizeof(wasmAudioWorkletStack), WebAudioWorkletThreadInitialized, (void *)&audioData);
```

And then read it in ProcessAudio?
```
EM_BOOL ProcessAudio(int numInputs, const AudioSampleFrame *inputs, int numOutputs, AudioSampleFrame *outputs, int numParams, const AudioParamFrame *params, void *userData)
{
#ifdef REPORT_RESULT
	++audioProcessedCount;
#endif

AudioStruct * audioData = (AudioStruct *) userData; //everything you need in the struct 
audioData->outBuffer = ..... 
```
I copied the code examples from here: https://github.com/openframeworks/openFrameworks/pull/7363

**Comment by sbc100** [comment]
@juj?

**Comment by juj** [comment]
Yes, that is possible. You can pass a pointer to anything in userData, as long as you make sure that the thing pointed to by the pointer is held alive as long as the ProcessAudio callback is being called (i.e. the AudioStruct instance cannot be put on the caller stack).

However the userData pointer that is passed to a call to `emscripten_start_wasm_audio_worklet_thread_async()` is not the userData pointer that will flow in to `ProcessAudio()`.

I've proposed a PR above to clarify documentation about which userData flows where, so it will hopefully be more clear.

**Comment by Jonathhhan** [comment]
@juj thank you.
