### ISSUE TITLE
Accessing Local FS with permission

### ISSUE THREAD

**Issue by aVoman7** [emscripten-core/emscripten#18993]
I have issues accessing local files in my build. I need not use `--preload-file`. I have a function similar to `fopen()`(it also needs the path of a file to access it). It is important that I should use this function. I know the local FS is not available for the the browser to access. So I have used `EM_ASYNC_JS()` to code through JS. I'm using windows OS. My emscripten version is 3.1.32. 

### MY CODE
Untitled-1.cpp
```
#include <iostream>
#include <emscripten.h>

EM_ASYNC_JS(char *, waitForButtonClick, (), {
  var stringOnWasmHeap;

  function getPromiseFromEvent(item, event)
  {
    return new Promise((resolve) => {
      const listener = (e) =>
      {
        function displayContents(contents)
        {
          var element = document.getElementById('file-content');
          element.textContent = contents;
        }

        var file = e.target.files[0];
        if (!file)
        {
          return;
        }
        var reader = new FileReader();
        reader.onload = function(e)
        {
          var contents = e.target.result;
          displayContents(contents);
        };
        reader.readAsText(file);

        const filePath = file.path || file.name;
        console.log(filePath);
        var lengthBytes = lengthBytesUTF8(filePath) + 1;
        stringOnWasmHeap = Module._malloc(lengthBytes);
        stringToUTF8(filePath, stringOnWasmHeap, lengthBytes);

        item.removeEventListener(event, listener);
        resolve();
      };
      item.addEventListener(event, listener);
    });
  }
  const button = document.getElementById('file-input');
  console.log("wait for");
  await getPromiseFromEvent(button, "change");
  return stringOnWasmHeap;
});

int main()
{
  char *str2 = waitForButtonClick();
  FILE *file = fopen(str2, "rb");
  free(str2);
  if (!file)
  {
    printf("cannot open file\n");
    return 1;
  }
  else
    printf("success open file\n");
}
```

### CMD Line Options
`emcc -sASYNCIFY Untitled-1.cpp -o out\indx.html -sEXPORTED_FUNCTIONS=_malloc,_main -sFORCE_FILESYSTEM`

FYI, I have added the FileSaver.min.js in the html file and also a input tag with id as `file-input`

**Comment by sbc100** [comment]
It looks like your JS code is just displaying the file contents and not adding it to the emscripten VFS.   If you want to be able to call fopen() on the file you need to some how add it to the emscripten fileystem.   One way to do this is using the  JS filesystem API.  See https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.createPreloadedFile
