### ISSUE TITLE
Consider not logging an error when emscripten_unwind_to_js_event_loop is called when using -sASSERTIONS=1

### ISSUE THREAD

**Issue by lambdageek** [emscripten-core/emscripten#19036]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.30 (cfe2bdfe2692457cb5f5770672f6e5ccb3ffc2f2)
clang version 16.0.0 (https://github.com/llvm/llvm-project 800f0f1546b2352ba42a4777149afb13cb874fcd)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/alklig/work/dotnet-runtime/runtime/src/mono/wasm/emsdk/upstream/bin
```

**Failing command line in full:**
N/A

**Full link command and output with `-v` appended:**
N/A

---

We build our product with `-s ASSERTIONS=1` in some circumstances because some of the assertions are valuable.

However, when using pthreads, these lines log a scary message to the console whenever `emscripten_unwind_to_js_event_loop` is used.  But this is not an error, it's just the expected way that function is supposed to work.  Is it reasonable to just remove the error?  If it's used for some tests in Emscripten, is there some other way to validate the expected behavior?

https://github.com/emscripten-core/emscripten/blob/13b1f81e1ef6089321fc4ac1a3a2aa273d436b89/src/worker.js#L252-L254

**Comment by sbc100** [comment]
Yes, at least it should not be `err` but `dbg` (which doesn't generate errors in the console). 

In fact perhaps it we should use `#if RUNTIME_DEBUG` and `dbg`.. that should be good.
