### ISSUE TITLE
[RuntimeError]: operation does not support unaligned accesses

### ISSUE THREAD

**Issue by turran** [emscripten-core/emscripten#19040]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.32 (eab98adf462c39f3c31d348331c4830bcaa36949)

The compile and link commands are just too bing to dump here, they include a lot of dependencies. In general this happens on GLib by using pthreads.

The stacktrace is the following
``
Error [RuntimeError]: operation does not support unaligned accesses
    at a_inc.5 (wasm://wasm/02d92876:wasm-function[6599]:0x1fc0db)
    at __pthread_mutex_timedlock (wasm://wasm/02d92876:wasm-function[6597]:0x1fc081)
    at __pthread_mutex_lock (wasm://wasm/02d92876:wasm-function[6595]:0x1fbf8f)
    at g_rec_mutex_lock (wasm://wasm/02d92876:wasm-function[620]:0x19548)
``
and happens when using recursive mutexes. 

I'm not really sure if the position in the structure where the mutex is, is not aligned and therefore the problem, or it is actually something else, more in the Emscripten toolchain itself, any hint will be appreciated.

**Comment by sbc100** [comment]
Can you find the declaration of the mutux in question?    I wonder if its inside struct is being marked as unaligned?   We've not seen this kind of bug report before so I'm guessing something unusual is going on.

**Comment by turran** [comment]
It isn't. The definition of the mutex can be found at https://github.com/GNOME/glib/blob/main/glib/gthread.h#L81 where the pointer is filled with the actual pthread's mutex in https://github.com/GNOME/glib/blob/main/glib/gthread-posix.c#L315 and the inclusion is at https://github.com/GStreamer/gstreamer/blob/main/subprojects/gstreamer/gst/gstelement.h#L761 . In fact, a simple test of locking/unlocking the original GLib's one or the one from GStreamer works correctly, but at runtime, in the application itself, it triggers the runtime error.

**Comment by sbc100** [comment]
The access in question must be this one: https://github.com/emscripten-core/emscripten/blob/07af96af4a1fbfe293aa2fb6c64236f00afc201f/system/lib/libc/musl/src/thread/pthread_mutex_timedlock.c#L86

a_inc in emscripten is implemented here using ` __c11_atomic_fetch_add`: https://github.com/emscripten-core/emscripten/blob/07af96af4a1fbfe293aa2fb6c64236f00afc201f/system/lib/libc/musl/arch/emscripten/atomic_arch.h#L85

`__c11_atomic_fetch_add` compiles down to essentially a single wasm instruction `i32.atomic.rmw.add 2 0`, and that instruction requires its input to be 32-bit aligned.  

In order for that to be unaligned something odd must be going on.   Perhaps memory corruption?  Can you trying building `-fsantizer=addr`?   That that doesn't show anything then we/you would need to debug in other ways to find out how that pointer came to be unaligned.  I don't see how it could be under normal cursumstances.

Just checking, you are not be build with `-sMEMORY64` are you?   Could use share you link command so we can see all the different options you using?

**Comment by turran** [comment]
Hi @sbc100 , thanks for your information. Indeed, the asan sanitizer pointed out the problem, the memory was overwritten somehow and the pointer to the mutex had garbage. I've found already the issue, thanks for the feedback and your prompt response :+1:
