### ISSUE TITLE
huge memory usage with firefox

### ISSUE THREAD

**Issue by thekend** [emscripten-core/emscripten#1904]
Hi!

We have a strange Firefox memory consumption problem that we cannot fix for a time. 

We have a web-based scuplting application that is built with emscripten. While sculpting, the memory consumption of firefox can suddenly raise from 300 Mb to 1-2 Gb for some seconds, then it drops down to 300 Mb again (looks like it’s garbage collected). It makes stalling in Firefox or even in the whole system, and for 32 bit systems the browser sometimes crashes too. There’s no such behavior when using Chrome. Although I don’t know if this “bug” is related to ff or emscripten.

We created a test build:
http://leopoly.com/create/?v=Testff&id=18
May take a long time to download for the first time.
Just draw to the sphere with the left mouse button and see the memory consumption.

I can’t figure out what can cause this huge memory consumption, because emscripten’s HEAP is constantly 64 Mb or growing very rarely (we modified emscripten’s enlargeMemory function to log the growing to the console). So I guess the heap in emscripten is not garbage collected (only when growing, but it happens very rarely). While the user sculpts we don’t allocate other memory in javascript (like with FS API or other), so everything allocated is only for emscripten’s functioning, but it should be the same for cases when we don’t sculpting, because the main loop always runs (rendering and rayhit calculations).

Any help is highly appreciated.

Thanks:
Endre

**Comment by juj** [comment]
I wonder if this is still an issue? Since reporting, memory growth has been added to asm.js mode, and the compiler has improved a lot in terms of optimizations, so is this still a problem with the latest compiler?
