### ISSUE TITLE
Converting val(typed_memory_view())s back into Pointers

### ISSUE THREAD

**Issue by zalo** [emscripten-core/emscripten#19051]
Hello, I'm porting [the MuJoCo Physics Engine to WASM](https://zalo.github.io/mujoco_wasm/).

I've had great success exposing its internal state pointers as typed memory arrays: 
```C++
// double* -> val -> "Float64Array"
val get() { return val(typed_memory_view(m->nq, s->qpos)); }
```
However, I'd like users to be able to pass these same arrays back into functions for modification:
```C++
// "Float64Array" -> val -> ??? -> double*
void integratePos(val qpos, val qvel, double dt) { return mj_integratePos(qpos.???, qvel???, dt); }
```
How do I get the `double*` back out of the `val` containing the `typed_memory_view`?

EDIT: I notice TypedArrays have a `byteOffset` with a value like `1635520`... is this an address into the `HEAP8`?
Can I cast this `byteOffset` to a `double*`?

EDIT: It looks like I can! `reinterpret_cast<mjtNum*>(myTypedArrayByteOffset)` works when I pass the `int` over the pipe!
But how do I access this `byteOffset` from WebAssembly directly?

**Comment by zalo** [comment]
I notice TypedArrays have a `byteOffset` with a value like `1635520`... is this an address into the HEAP8?

Can I cast this `byteOffset` to a pointer?

**Comment by brendandahl** [comment]
> But how do I access this `byteOffset` from WebAssembly directly?

```cpp
auto byteOffset = val["byteOffset"].as<int>();
```

**Comment by zalo** [comment]
Thanks!   That worked great

Here's the incantation I ended up with for ingesting `Float64Array`'s that had been previously passe to Javascript via `val(typed_memory_view())`:
```python
void solveM (val x, val y, int n ) { 
    return mj_solveM (reinterpret_cast<double*>(x["byteOffset"].as<int>()), 
                      reinterpret_cast<double*>(y["byteOffset"].as<int>()), n);
}
```
