### ISSUE TITLE
emscripten_return_address is not fast enough 

### ISSUE THREAD

**Issue by junyuecao** [emscripten-core/emscripten#19060]
There is  emscripten_return_address(https://github.com/emscripten-core/emscripten/pull/8617) which is frequently called in some sanitizer code. But current implementation is based on Error.stack in JS which is very slow. Do we have any chance to have a faster one?

**Comment by kripken** [comment]
Wasm can't get a stack trace by itself, so we need to do this on the JS side. But perhaps that function could be optimized in JS somehow.

**Comment by junyuecao** [comment]
@kripken new Error().stack cost about 0.02ms which is the major cost in this function. It seems there is no straightforward way to optimize it. 

Maybe V8 could provide a fast way  to get return address of current pc.

**Comment by juj** [comment]
`emscripten_return_address()` calls into a function that contains three regex matches: https://github.com/emscripten-core/emscripten/blob/574f4f449780f63ab97970d5d6b5625e124c7d79/src/library.js#L2672-L2680

which it compiles on the fly. One optimization would be to precompile the regexes up front via https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp and reuse the already compiled regexes in the function.

However I think it might be even faster to rewrite the code to not use regexes at all, and write ad hoc string searching that matches in one pass against the known different forms in C-style linear advancing form.

Assuming the above would be too slow still, maybe it would be possible to investigate adding a two-stage API to JS+Wasm, where acquiring a callstack vs decoding/interpreting it would be separated to two different stages, like native APIs have ([backtrace vs backtrace_symbols](https://linux.die.net/man/3/backtrace). That way hot paths that need to e.g. hash callstacks or search "is this function in the callstack" could do so without needing to do string manipulation.

**Comment by junyuecao** [comment]
@juj Thank you for the investigation. 
I've tried to add `console.time` to get the time cost of each part and I got data like this.
```
stack: 0.026123046875 ms
convert: 0.001953125 ms
```
I seems the major cost is getting the stack of an Error.  

> Here is the test code
> ```
> function _emscripten_return_address(level) {
>  console.time("stack")
>  var callstack = jsStackTrace().split("\n");
>  if (callstack[0] == "Error") {
>   callstack.shift();
>  }
>  var caller = callstack[level + 3];
>  console.timeEnd("stack")
>  
>  console.time("convert")
>  var ret = convertFrameToPC(caller);
>  console.timeEnd("convert")
>  return ret;
> }
> ```
> 
>

**Comment by junyuecao** [comment]
I digged into llvm and on the other platform the RETURNADDR is supported by a register and the compiler. It should be very fast theoretically. 

https://github.com/emscripten-core/llvm-project/blob/main/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L8150-L8171

**Comment by quantum5** [comment]
The way it currently works is the least bad way I could find, and I tried pretty hard. There's no LLVM magic that can save the day.

**Comment by sbc100** [comment]
@quantum5!  Nice to hear from you again.  Hope you are doing well!

**Comment by junyuecao** [comment]
If the DevTools is not activated, getting stack is a lot faster.  So I close this issue for now.  
Thank you all for kindly help
