### ISSUE TITLE
Emscripten produces degenerate if-else chain for switch inside a loop

### ISSUE THREAD

**Issue by rfk** [emscripten-core/emscripten#1909]
I've found a certain pattern of spaghetti-goto code that seems to confound the relooper, causing it to produce a degenerate if-elif chain when handling a switch inside a loop.

Full test case: https://gist.github.com/rfk/7889732

The generated code uses a switch to set a flag variable, then uses a big if-elif chain to decide what to do based on this flag variable, like so:

```
   LOOP: while (1) {
     switch (input[i]) {
       case '0':
         flag = 1;
         break LOOP;
         break;
       case '1':
         flag = 2;
         break LOOP;
         break;
       ...etc...
     }
     i++;
   }
   if (flag == 1) {
     ...code for case 1...
   } else if (flag == 2) {
     ...code for case 2...
   }
```

If there are many cases in this switch, the result can be some extremely inefficient code.  I discovered the issue in the code generated by PyPy for its bytecode dispatch loop, which has more than 200 cases in a switch-in-a-loop like this.

It seems "obvious" that the generated code could be improved by pushing these blocks inside the switch statement, like so:

```
   LOOP: while (1) {
     switch (input[i]) {
       case '0':
         ...inline code for case 1...
         break LOOP;
         break;
       case '1':
         ...inline code for case 2...
         break LOOP;
         break;
       ...etc...
     }
     i++;
   }
```

So I'm hopeful that, while it's probably quite an obscure corner case, it can be improved without too much hassle.  I'd be happy to try my hand at adding this optimisation - can you suggest a good place to start poking?

**Comment by dreamlayers** [comment]
Has anyone encountered this problem with recent versions, using fastcomp? I was just looking through CPU_Core_Normal_Run() in DOSBox without my source-level transformation, compiled with Emscripten 1.29.6 at -O3. The JS code looks good. There is a switch setting a variable and another testing the variable it set, but everything is done via switches, so it should be fast. It performs well in Firefox 35. 

Performance is *horrible* in Chrome 40, but that is a [V8 JS engine issue with big switches](https://code.google.com/p/v8/issues/detail?id=2275). It may make sense to have some workaround for that V8 issue in Emscripten, but at least this if-else chain problem might be fixed now.

**Comment by kripken** [comment]
Yeah, hopefully this should now be ok. The relooper emits switches when LLVM suggests to.

Regarding chrome performance, they are now using turbofan, a new backend, instead of crankshaft, for asm.js content, which is promising. Hopefuly turbofan won't have the same limitations on switch size. However, when I tried the massive-sqlite benchmark - which tests among other things a very large switch - it didn't run correctly, so might be too early to test. But hopefully soon. (bug: https://code.google.com/p/v8/issues/detail?id=3800 )
