### ISSUE TITLE
WasmFS/OPFS: std::filesystem::remove_all() errors out when attempting to remove a non-empty directory

### ISSUE THREAD

**Issue by fguinan** [emscripten-core/emscripten#19106]
After creating an opfs backend with a call to wasmfs_create_opfs_backend(), we will sometimes see the call to std::filesystem::remove_all() fail with error code '55' when called on a non-empty directory. None of the files in the directory are open. 

Even though error code '55' is returned, some of the files and subfolders in the directory are removed. If we call remove_all() in a loop until we stop seeing error code '55', then the directory is eventually removed in full.

**Comment by fguinan** [comment]
Spent a little time trying to debug this issue in Chrome running on macOS. From what I could tell, the remove_all_impl() function in libcxx/src/filesystem/operations.cpp was unable to iterate thru all the child files in its 'while' loop. For example, if there were 12 files in the directory, it would iterate thru its 'while' loop 7 times, remove those 7 items, but then break early because the next entry it fetched from the directory stream was null (even though there were still 5 items remaining). 

It makes me wonder whether the act of removing child items somehow interfered with the stream's ability to iterate thru the items. Then, because the directory still had 5 items left, trying to remove it resulted in an error.

**Comment by tlively** [comment]
Do you know if the same problem happens in other browsers?

**Comment by fguinan** [comment]
Sorry, I'm unable to test other browsers quickly. I discovered and debugged the issue in our web app, which is currently targeting Chrome and Chromebooks only for its first version.

**Comment by fguinan** [comment]
Just curious if there was any update on this issue. Thanks.

**Comment by kripken** [comment]
@fguinan If you are unable to test on other browsers, then creating a small standalone testcase for others to do that testing could help move things forward here.

**Comment by fguinan** [comment]
[WasmFSRemoveAll.zip](https://github.com/emscripten-core/emscripten/files/11482501/WasmFSRemoveAll.zip)

@kripken, @tlively - Attached is a sample project that exhibits the issue. The project requires the emsdk, npm, ninja, and cmake. 

In order to run, you'll need to put a copy of the emsdk into the expanded folder. The emsdk should be in a folder titled 'emsdk'.

Once the emsdk folder exists, run the following commands:
- npm install
- npm run build:testApp:[debug|release]
- npm run launch_server:[debug|release]

Then, open Chrome and navigate to https://localhost:8000. Bring up the dev tools panel in Chrome and type 'window.testModule._createTestFiles()' followed by 'window.testModule._removeAllSubFolders()'. Notice that the call to _removeAllSubFolders() results in an error because it is unable to delete all the files within the folder specified.

If you have trouble building or running the project, the following C++ code is all it takes to exhibit the issue in Chrome. You can copy and paste it into your own setup if you already have one.

```
    EMSCRIPTEN_KEEPALIVE int main() 
    {
        // Initialize wasmfs
        auto wasmfs_backend = wasmfs_create_opfs_backend();
        const char* rootMount = "/persistent";
        bool exists = access(rootMount, F_OK) == 0;
        if (!exists)
            wasmfs_create_directory(rootMount, 0777, wasmfs_backend);

         // Keep the standard library runtime alive even after exiting main
        emscripten_exit_with_live_runtime();
        return 0;
    }

    EMSCRIPTEN_KEEPALIVE void createTestFiles()
    {
        // Create subfolder hierarchy
        std::string folderHierarchy("/persistent/data/dataStore/StateStorage");
        bool result = std::filesystem::create_directories(folderHierarchy);

        for (int i=0; i< 50; i++)
        {
            // Create subfolder level 1
            std::string subFolderPath1 = folderHierarchy + std::string("/SubFolder1-") + std::to_string(i);
            result = std::filesystem::create_directory(subFolderPath1);

            // Create subfolder level 2
            for (int j=0; j< 3; j++)
            {
                std::string subFolderPath2 = subFolderPath1 + std::string("/SubFolder2-") + std::to_string(j);
                result = std::filesystem::create_directory(subFolderPath2);

                std::string path = subFolderPath2 + "/blankFile.txt";
                std::ofstream stream(path);
                stream << "1234";
                stream.close();
            }
        }
    }

    EMSCRIPTEN_KEEPALIVE void removeAllSubFolders()
    {
        std::string folderHierarchy("/persistent/data/dataStore/StateStorage");
        std::filesystem::remove_all(folderHierarchy);
    }

**Comment by fguinan** [comment]
Curious if there has been any movement on this issue. We're a little stuck because of it. Thanks.
cc: @kripken, @tlively

**Comment by kripken** [comment]
@fguinan Can you provide the full instructions to run that C++ file to see the problem? I tried a few things, and ended up compiling with `./emcc a.cpp -o a.html -sWASMFS -pthread -sPROXY_TO_PTHREAD` (without pthreads+proxy to pthread it errors on not being able to create the OPFS backend), but then when I load the page I don't see any error thrown.

**Comment by fguinan** [comment]
@kripken - You could try opening the dev tools panel in Chrome and calling 'createTestFiles()' followed by 'removeAllSubFolders()' from the console. Otherwise, you could try altering the code above to call both 'createTestFiles()' and 'removeAllSubFolders()' from within the 'main()' function.

**Comment by fguinan** [comment]
Here is an updated C++ code snippet that calls those functions directly from main(). It should show the error in Chrome on load:

```
#include <emscripten.h>
#include <emscripten/wasmfs.h>
#include <unistd.h>

#include <filesystem>
#include <fstream>
#include <string>

extern "C"
{
EMSCRIPTEN_KEEPALIVE void createTestFiles()
{
    // Create subfolder hierarchy
    std::string folderHierarchy("/persistent/data/dataStore/StateStorage");
    bool result = std::filesystem::create_directories(folderHierarchy);
    
    for (int i=0; i< 50; i++)
    {
        // Create subfolder level 1
        std::string subFolderPath1 = folderHierarchy + std::string("/SubFolder1-") + std::to_string(i);
        result = std::filesystem::create_directory(subFolderPath1);
        
        // Create subfolder level 2
        for (int j=0; j< 3; j++)
        {
            std::string subFolderPath2 = subFolderPath1 + std::string("/SubFolder2-") + std::to_string(j);
            result = std::filesystem::create_directory(subFolderPath2);
            
            std::string path = subFolderPath2 + "/blankFile.txt";
            std::ofstream stream(path);
            stream << "1234";
            stream.close();
        }
    }
}

EMSCRIPTEN_KEEPALIVE void removeAllSubFolders()
{
    std::string folderHierarchy("/persistent/data/dataStore/StateStorage");
    std::filesystem::remove_all(folderHierarchy);
}

EMSCRIPTEN_KEEPALIVE int main()
{
    // Initialize wasmfs
    auto wasmfs_backend = wasmfs_create_opfs_backend();
    const char* rootMount = "/persistent";
    bool exists = access(rootMount, F_OK) == 0;
    if (!exists)
        wasmfs_create_directory(rootMount, 0777, wasmfs_backend);
    
    createTestFiles();
    removeAllSubFolders();
    
    // Keep the standard library runtime alive even after exiting main
    emscripten_exit_with_live_runtime();
    return 0;
}

}

**Comment by kripken** [comment]
Thanks, taking a look at that, it aborts with the compile command I mentioned before. That seems to be because a C++ exception is thrown. So `std::filesystem` may not work properly with exceptions disabled. Adding `-fexceptions`, the error is much clearer:
```
worker.js onmessage() captured an uncaught exception: std::__2::__fs::filesystem::filesystem_error: filesystem error: in remove_all: Directory not empty ["/persistent/data/dataStore/StateStorage"]
```

Looking into that, IIUC the testcase generates 300 files (outer loop 50, inner loop 3, and inner loop both creates a dir and a file). Somehow, `std::filesystem` code ends up trying to remove the `StateStorage` directory - the parent of them all - after only removing 182 of the children.

I didn't look into the `std::filesystem` code itself, but that's where I suspect a bug might be, since I didn't see anything wrong in the syscall or OPFS layers in Emscripten, and @fguinan you say you see this in 2 browsers, so it's likely not a browser bug. It's possible `std::filesystem` is quite new in libc++ and hasn't been tested yet.

To move forward, some options:

1. Try to build the exact same libc++ as Emscripten uses natively (can grab it from `system/lib/libcxx`), and see if the problem happens there too. If so, it's likely a libc++ bug.
2. Write a version of that cpp that avoids `std::filesystem` and uses lower-level APIs. If the problem doesn't happen then it's likely a libc++ bug.

**Comment by fguinan** [comment]
@kripken, @tlively - I built llvm from https://github.com/emscripten-core/llvm-project/tree/emscripten-libs-15.0.0 at commit e980b747, which I believe is what is included in emsdk v3.1.37 (the version we are using). I then built a simple native app on my macOS with the same sample code above and linked it against this llvm version. Running the app did not exhibit the error. Everything succeeded, and the folders were all created and then removed properly.

While debugging, I did notice that the 'readdir()' function in emscripten does not come from llvm but instead from musl. When debugging in emscripten, I saw that the 'readdir()' function calls thru to "__syscall(SYS_getdents, dir->fd, dir->buf, sizeof dir->buf)" which is implemented in emscripten. I had difficulty stepping thru this function, but it looks like the issue is somewhere in this function, since at some point, it returns the value 0, even though we haven't finished going thru all the entries in the directory. 

The call to this function is made five times for the top-level directory in the sample code above. On each of the first four times, it returns 7 'dirent' entries, but on the fifth time, it returns 0, even though there are still numerous entries left. As a result, we end up only processing 28 of the 50 entries in the top-level directory.

**Comment by kripken** [comment]
Interesting. Do you know why `readdir()` is called 5 times for the top-level directory? (I would expect once.) Also, why is 7 the right number of entries for the first calls? (The toplevel directory should have 50 children.)

**Comment by fguinan** [comment]
readdir() is called in a while loop by remove_all_impl() in operations.cpp in llvm's libc++ library. The readdir() function is implemented in readdir.c in the musl library, and it is supposed to return a single 'dirent' struct that represents a single child entry in the directory. Therefore, it should actually be called 50 times for the top-level directory. (Well, 50 + 2, because the entries "." and ".." are also considered distinct entries in the directory.) 

The implementation of readdir() in the musl library calls thru to "__syscall()", which does the actual legwork of retrieving the actual 'dirent' instances. Those instances are then stored in a "stream", and the stream tracks which entry was returned last. That way, the next call to readdir() will return the next entry in the stream. Once the end of the stream is reached, the next call to readdir() will result in another call to "__syscall()" for the next batch of 'dirent' instances. It repeats this process until all the entries are iterated.

The implementation of "__syscall()" inside the wasmfs implementation returns batches of 7 'dirent' structs at a time the first four times it is called. But on the fifth time, it returns no 'dirent' structs. This feels like a bug in the way the wasmfs is tracking the 'dirent' instances. It may be either starting the stream in the wrong location, or it is not able to see the end of the stream.

**Comment by kripken** [comment]
Thanks, I think I follow that, aside from "batches" - not sure what that means (readdir is an iterator, and over all of them each time?)

But probably I just need to debug that syscall, I think you're right there. To do that, though, it would be really useful if you can do suggestion 2 from earlier, @fguinan , which is to write a testcase without libc++ involvement. Just some C code that does readdir and shows the bug would be much simpler for me to debug. As I debug I'll need to look at the callers to readdir, and I suspect that perhaps there is undefined behavior in the libc++ impl (in the ordering, or reentrancy, or such) - seeing plain C code using readdir would make that much easier to reason about.

**Comment by fguinan** [comment]
"batches" == "groups".  The implementation of "__syscall()" inside the wasmfs implementation returns groups of 7 'dirent' structs at a time.

Further debugging shows that the act of unlinking the entries is what causes the stream to stop returning entries. Here is code that calls directly to readdir():

```
#include <emscripten.h>
#include <emscripten/wasmfs.h>
#include <unistd.h>

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>

#include <fstream>
#include <iostream>
#include <string>
#include <system_error>

namespace
{
    template <class Cleanup>
    struct scope_exit {
        explicit scope_exit(Cleanup const& cleanup)
        : cleanup_(cleanup)
        { }
        
        ~scope_exit() { cleanup_(); }
        
    private:
        Cleanup cleanup_;
    };

    std::error_code capture_errno() {
        return std::error_code(errno, std::generic_category());
    }

    uintmax_t remove_all_impl(int parent_directory, const std::string& p, std::error_code& ec) {
        // First, try to open the path as a directory.
        const int options = O_CLOEXEC | O_RDONLY | O_DIRECTORY | O_NOFOLLOW;
        int fd = ::openat(parent_directory, p.c_str(), options);
        if (fd != -1) {
          // If that worked, iterate over the contents of the directory and
          // remove everything in it, recursively.
          DIR* stream = ::fdopendir(fd);
          if (stream == nullptr) {
            ::close(fd);
            ec = capture_errno();
            return 0;
          }
          // Note: `::closedir` will also close the associated file descriptor, so
          // there should be no call to `close(fd)`.
          scope_exit close_stream([=] { ::closedir(stream); });

          uintmax_t count = 0;
          while (true) {
            std::string str;
            struct dirent* dir_entry_ptr = ::readdir(stream);
            if (dir_entry_ptr)
              str = dir_entry_ptr->d_name;
            else if (errno)
              ec = capture_errno();
            if (str == "." || str == "..") {
              continue;
            } else if (str.empty()) {
              break; // we're done iterating through the directory
            } else {
              count += remove_all_impl(fd, str, ec);
            }
          }

          // Then, remove the now-empty directory itself.
          if (::unlinkat(parent_directory, p.c_str(), AT_REMOVEDIR) == -1) {
            ec = capture_errno();
            return count;
          }

          return count + 1; // the contents of the directory + the directory itself
        }

        ec = capture_errno();
        
        // If we failed to open `p` because it didn't exist, it's not an
        // error -- it might have moved or have been deleted already.
        if (ec == std::errc::no_such_file_or_directory) {
          ec.clear();
          return 0;
        }

        // If opening `p` failed because it wasn't a directory, remove it as
        // a normal file instead. Note that `openat()` can return either ENOTDIR
        // or ELOOP depending on the exact reason of the failure.
        if (ec == std::errc::not_a_directory || ec == std::errc::too_many_symbolic_link_levels) {
          ec.clear();
          if (::unlinkat(parent_directory, p.c_str(), /* flags = */0) == -1) {
            ec = capture_errno();
            return 0;
          }
          return 1;
        }

        // Otherwise, it's a real error -- we don't remove anything.
        return 0;
    }
}

extern "C"
{
EMSCRIPTEN_KEEPALIVE void createTestFiles()
{
    // Create subfolder hierarchy
    std::string folderHierarchy("/persistent/data/dataStore/StateStorage");
    bool result = std::filesystem::create_directories(folderHierarchy);
    
    for (int i=0; i< 30; i++)
    {
        std::string path = folderHierarchy + std::string("/blankFile-") + std::to_string(i);
        std::ofstream stream(path);
        stream << "1234";
        stream.close();
    }
}

EMSCRIPTEN_KEEPALIVE void removeAllSubFolders()
{
    std::string folderHierarchy("/persistent/data/dataStore/StateStorage");
    std::error_code mec;
    uintmax_t count = remove_all_impl(AT_FDCWD, folderHierarchy, mec);
    std::cout << "final count: " << count;
}

EMSCRIPTEN_KEEPALIVE int main()
{
    // Initialize wasmfs
    auto wasmfs_backend = wasmfs_create_opfs_backend();
    const char* rootMount = "/persistent";
    bool exists = access(rootMount, F_OK) == 0;
    if (!exists)
        wasmfs_create_directory(rootMount, 0777, wasmfs_backend);
    
    createTestFiles();
    removeAllSubFolders();
    
    // Keep the standard library runtime alive even after exiting main
    emscripten_exit_with_live_runtime();
    return 0;
}

}
```

The code above simplifies the test case so that it is just a folder of 30 files, no subdirectories. The code attempts to iterate thru the 30 files and delete (unlink) each one of them, and attempts to delete the parent directory, thinking that it is now empty. It gets thru 18 of the files before the directory stream stops returning entries. 

If you comment out the 'if' blocks that call 'unlinkat()', then the directory stream is able to return all 30 entries.

It's looking like the wasmfs system implementation is comparing the current position in the directory stream with the number of items that are currently still inside the directory. If the code is deleting those entries during iteration, then the implementation is unable to return the remaining entries that haven't been iterated yet.

**Comment by tlively** [comment]
The documentation for `rewinddir` says,

> This function also notices if files have been added or removed to the directory since it was opened with opendir. (Entries for these files might or might not be returned by readdir if they were added or removed since you last called opendir or rewinddir.)

This implies that while scanning through an open directory with a sequence of `getdents64` syscalls, no entries present at the time the directory was opened should be skipped, but any files deleted since then are valid to include and entries added since then are valid to exclude. That means a valid implementation would be to gather and cache a list of directory entries when a directory is opened rather than gathering a list of entries on every call to `getdents64`. Such an implementation would also solve the problem described in this issue.

**Comment by fguinan** [comment]
@tlively, @kripken - Thank you for the fix. Was wondering what version of emsdk you anticipate will have this fix. Thanks!

**Comment by tlively** [comment]
This will be in the next release, which will be Emscripten 3.1.42.

**Comment by sbc100** [comment]
(Oe you can try it now with `emsdk install tot`
