### ISSUE TITLE
Threads not starting under some circumstances

### ISSUE THREAD

**Issue by ricardperez** [emscripten-core/emscripten#19130]
**Version of emscripten/emsdk:**
Tried `3.1.23` and `3.1.34`.

**Failing command line in full:**
_This is more of a runtime issue. No failing command line._

**Full link command and output with `-v` appended:**
```
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin/clang" --version
shared:INFO: (Emscripten: Running sanity checks)
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN --sysroot=/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -O0 -g3 -v -pthread lib.cpp -c -o /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/emscripten_temp_re7ucp3u/lib_0.o
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin
 (in-process)
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin/clang-17" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name lib.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-feature +atomics -target-feature +bulk-memory -target-feature +mutable-globals -target-feature +sign-ext -target-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -v -fcoverage-compilation-dir=/Users/ricardperez/gitlab/ricard/hello-webassembly -resource-dir /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/lib/clang/17 -D __EMSCRIPTEN_SHARED_MEMORY__=1 -D EMSCRIPTEN -isysroot /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/lib/clang/17/include -internal-isystem /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include -O0 -fdeprecated-macro -fdebug-compilation-dir=/Users/ricardperez/gitlab/ricard/hello-webassembly -ferror-limit 19 -fvisibility=default -pthread -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/emscripten_temp_re7ucp3u/lib_0.o -x c++ lib.cpp
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-apple-darwin21.6.0
ignoring nonexistent directory "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/lib/clang/17/include
 /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
em++: warning: -pthread + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
cache:INFO: generating system asset: symbol_lists/38aa8fcf7af19663f001a02ef5ce4e7dd3954a74.txt... (this will be cached in "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/symbol_lists/38aa8fcf7af19663f001a02ef5ce4e7dd3954a74.txt" for subsequent builds)
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/node/14.18.2_64bit/bin/node" /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/src/compiler.js /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/tmpgilwmvt2.json --symbols-only
cache:INFO:  - ok
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin/wasm-ld" -o lib.wasm /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/emscripten_temp_re7ucp3u/lib_0.o -L/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crt1_proxy_main.o --whole-archive -lembind-rtti --no-whole-archive -lGL-mt -lal -lhtml5 -lstubs-debug -lnoexit -lc-mt-debug -ldlmalloc-mt -lcompiler_rt-mt -lc++-mt-noexcept -lc++abi-debug-mt-noexcept -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined-file=/var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/tmpcmcp1d8w.undefined --import-memory --shared-memory --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=emscripten_dispatch_to_thread_ --export=_emscripten_thread_free_data --export=emscripten_main_runtime_thread_id --export=emscripten_main_thread_process_queued_calls --export=_emscripten_run_in_main_runtime_thread_js --export=emscripten_stack_set_limits --export=__get_temp_ret --export=__set_temp_ret --export=malloc --export=free --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --entry=_emscripten_proxy_main --max-memory=2147483648 --stack-first
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin/wasm-emscripten-finalize" -g --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers --dwarf lib.wasm -o lib.wasm --detect-features
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/node/14.18.2_64bit/bin/node" /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/src/compiler.js /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/tmpf8bbbdgd.json
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/bin/llvm-objcopy" lib.wasm lib.wasm --remove-section=producers
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/node/14.18.2_64bit/bin/node" /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/tools/acorn-optimizer.js /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/emscripten_temp_re7ucp3u/lib.js growableHeap -o /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/emscripten_temp_re7ucp3u/lib.jso1.js
 "/Users/ricardperez/gitlab/emscripten-core/emsdk/node/14.18.2_64bit/bin/node" /Users/ricardperez/gitlab/emscripten-core/emsdk/upstream/emscripten/tools/preprocessor.js /var/folders/nw/669_3plx2jl5sts50b2x101r0000gn/T/emscripten_temp_re7ucp3u/settings.js worker.js --expandMacros
```

Hello, I am facing an issue where threads might not get started. I am using pthread and proxying the main to a web worker. I created a sample project that can be used to reproduce the issue.  This is the contents of it:

[lib.cpp](#lib.cpp)
[worker.js](#worker.js)
[index.html](#index.html)

> ⚠️ links are broken, contents are at the bottom

The idea is that `index.html` has a button that when clicked triggers some logic that spawns threads and waits for them. Such logic has been derived to a worker to avoid blocking the UI.

Such `worker.js` is invoking the C++ logic.

## Problem
The problem is that when the application loads, it starts running the main() function. The main is itself calling the same functionality that will be run when clicking the button - so threads are also being started from the main thread.

If I wait for such threads to finish and click the button, everything works as expected. But if I click the button while main is still running the threads, then the application hangs and the new call will not be able to run its threads.

Another important thing that I don't understand is that if I don't have an infinite loop in main, it won't work even after waiting for the threads from the main call to be finished. This is broken for version `3.1.34` but it would work fine on `3.1.23`.

## Building
```sh
em++ lib.cpp -lembind -o lib.js -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 -s ALLOW_MEMORY_GROWTH=1 -s EXIT_RUNTIME=0 -O0 -g3
```

## Running
```sh
emrun --browser=chrome index.html
```

## Screenshot
<img width="1613" alt="Screenshot 2023-04-04 at 06 39 37" src="https://user-images.githubusercontent.com/487084/229688537-145a3584-9f2a-44de-a67a-7526c77e762a.png">

Am I missing any obvious thing here?

Thanks a lot!

##### `lib.cpp`
```c++
#include <chrono>
#include <iostream>
#include <thread>

#include <emscripten.h>
#include <emscripten/bind.h>

using namespace emscripten;

using namespace std::chrono_literals;

int counter = 0;

// This function will be executed in a new thread
void threadFunction(int count, int counter) {
    for (int i = 0; i < count; i++) {
        std::cout << "[" << counter << "] " << "Thread function running..." << std::endl;
        std::this_thread::sleep_for(1000ms);
        std::cout << "[" << counter << "] " << "finished thread" << std::endl;
    }
}

EMSCRIPTEN_KEEPALIVE void sayhello() {
    int counter_ = counter++;
    std::cout << "[" << counter_ << "] " << "About to say hello from thread " << std::this_thread::get_id() << "..." << std::endl;
    // Create a new thread and start running the threadFunction
    std::thread t(threadFunction, 5, counter_);
    std::cout << "[" << counter_ << "] " << "  first thread spawned... now let's sleep for a bit and spawn one more!" << std::endl;
    std::this_thread::sleep_for(500ms);
    std::thread t2(threadFunction, 2, counter_);
    std::cout << "[" << counter_ << "] " << "  second thread spawned... now we need to join them" << std::endl;

    // Wait for the thread to finish executing
    t.join();
    t2.join();

    std::cout << "[" << counter_ << "] " << "Finished" << std::endl;
}

int main() {
    std::cout << "[XX] main()" << std::endl;
    sayhello();
    
    // Running an infinite loop to allow for std::threads to start running
    while (true) {
        std::this_thread::sleep_for(1000ms);
        std::cout << "[XX] sleeping from main thread..." << std::endl;
    }

    std::cout << "[XX] main finished..." << std::endl;
    return 0;
}

EMSCRIPTEN_BINDINGS(my_module) {
    function("sayhello", &sayhello);
}
```

##### `worker.js`
```js
importScripts('lib.js');

function sayHello() {
    console.log("Hello from the web worker!");
    Module.sayhello();
}

self.addEventListener('message', (event) => {
    if (event.data === 'hello') {
        sayHello();
    }
});
```

##### `index.html`
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World with WebAssembly and Emscripten</title>
</head>
<body>
    <h1>Hello World!</h1>
    <button>Say Hello</button>
    <script>
        const worker = new Worker('worker.js');
        const button = document.querySelector('button');
        button.addEventListener('click', () => {
          worker.postMessage('hello');
        });
    </script>
</body>
</html>
```

**Comment by ricardperez** [comment]
I just realised that if I avoid calling `sayhello()` from `main`, then any call to the button will not be able to start any threads. It's like the application is not able to start new web workers to handle the threads.

**Comment by sbc100** [comment]
The two most common workarounds for this issue are using `PTHEAD_POOL_SIZE` or `PROZY_TO_PTHREADS`

**Comment by sbc100** [comment]
So that problem is that you are calling `sayhello` from your main runtime thread, even though your main function is being proxied to a separate thread, which means new threads that are created during `sayhello` will not be started until your return from the `sayhello` function (until the event loop runs).

**Comment by ricardperez** [comment]
> So that problem is that you are calling `sayhello` from your main runtime thread, even though your main function is being proxied to a separate thread, which means new threads that are created during `sayhello` will not be started until your return from the `sayhello` function (until the event loop runs).

Actually, the call to `sayhello` from main is working as expected, triggering the threads. As you said, if I didn't use the `PROXY_TO_PTHREADS` flag, it wouldn't work and it would hang at that very initial moment.

Then, the call to `sayhello` when clicking the html button, is processed by another worker, and it usually runs fine. The problem is when such button is clicked while the `main()` has not finished processing its own `sayhello()` yet. It is like no more web workers are allowed to be spawned other than the ones the `main()` did create, but also that they enter some kind of deadlock when triggering this data race.

**Comment by sbc100** [comment]
The worker you are creating with `new Worker` is acting as the main runtime thread.   This is thread that is in charge or creating all new pthreads, and the thread the receives the "hello" message from the main browser thread.

In order for new pthreads to actually start running the main runtime thread but return to its event loop.   In this case that means that the event handler for the `hello` message must return before threads created during the handling of the message will start running.    You can verify that this is indeed the source of your problem by building with `-sPTHREAD_POOL_SIZE=N` where N is the total number of pthreads needed by your test code (looks like N=2 or N=3 should be enough in this case but try N=10 just to be sure).    If that fixes you problem than you are running into the classic "cannot access new threads" issue, and you can look into various options to address that.   

I'm curious why you don't see a useful error message in debug builds though.  I think maybe `emscripten_check_blocking_allowed` does not handle the case where the entire emscripten program is running in a worker.

**Comment by ricardperez** [comment]
Thanks @sbc100 for your help.

It's true that using the `PTHREAD_POOL_SIZE` option with the right value helps. But this is not an option for my real application because the amount of pthreads depends a lot on how the application is used - remember this is just a sample project I created to try to replicate my app problem.

I think I understand the problem now. I thought that by using `PROXY_TO_PTHREADS` I would be able to spawn new pthreads from the `hello` handle as if they were spawned from the main (proxied to a pthread). I guess this was incorrect.

But then, how can I do it for the `hello` handle (`function sayHello()`) to return before it does spawn the threads? Something like this doesn't seem to work:
```
function sayHello() {
    return new Promise( resolve => {
        console.log("[worker] starts sayHello()");
        Module.sayhello();
        console.log("[worker] finished sayHello()")
    });
}
```

**Comment by sbc100** [comment]
Perhaps I can try to explain in terms of describing situation in which `sayhello` will or will not work.   Firstly, lets be clear about what `sayhello` is doing that cannot work under certain circumstances.  That is that it wants to start a new thread synchronously, and depends on that thread doing work before it will return.

Functions like `sayhello` **always** work when they are run from any secondary thread.  

Functions like `sayhello` **can** work on the primary thread, but only if there is free worker in the pool.

By primary thread I mean the thread/worker where emscripten runs, normally this is the main browser thread but not always.  For example in your case you are are loading the emscripten program in worker, so it never runs in the main browser thread.

If you want to run functions like `sayhello` from your primary thread you need to make sure you have enough threads in your pool.   You can work around this problem by avoiding this type of code on the primary thread if possible.  One way to do this is proxying all your actual work over to background threads (this is what `PROXY_TO_PTHREAD` does but only for the `main` function).

**Comment by ricardperez** [comment]
> You can work around this problem by avoiding this type of code on the primary thread if possible. One way to do this is proxying all your actual work over to background threads

This is what I don't know how to achieve in my sample. How do I proxy a message callback to a background thread? I would have thought running it from a web worker would be running in a background thread implicitly.

**Comment by sbc100** [comment]
> > You can work around this problem by avoiding this type of code on the primary thread if possible. One way to do this is proxying all your actual work over to background threads
> 
> This is what I don't know how to achieve in my sample. How do I proxy a message callback to a background thread? I would have thought running it from a web worker would be running in a background thread implicitly.

A agree it can be confusing, but in this case your "new Worker" ends up being the main emscripten thread, from which all other threads are spawned.

There are several ways you can proxy work to other threads.  See https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/proxying.h and  https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/threading.h.

However, remember that you won't be able to use any of the synchronous proxying methods since they block the calling the read, and in your case you need to the event loop of the calling thread (the main runtime thread) to be running, otherwise the new threads can't spawn.

**Comment by ricardperez** [comment]
Thanks @sbc100 for all your help. I am closing the issue now.

I sorted all my problems related with the original thread already. Thanks for being active in the conversation again.
