### ISSUE TITLE
 external symbol  “******” is missing. perhaps a side module was not linked in?

### ISSUE THREAD

**Issue by DoneListen** [emscripten-core/emscripten#19151]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.15 (8b4443a87f5eab5dbb9adb690f9ebed0a9da4bd9)
clang version 15.0.0 (https://github.com/llvm/llvm-project 27abff670bc7ad9702c4f9fc8b82aae6b530bf0f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\SvnCode\emsdk-main\upstream\bin
```
My main module references side-module classes, which is very common in c++.However, the following error was reported when using the web：
```
Aborted(external symbol '_ZN4MathC1Ev' is missing. perhaps a side module was not linked in? if this function was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
```
'_ZN4MathC1Ev'  Is a member method of a class of my sidemodule，Do I need to export the required classes when compiling sidemodules.

**Comment by DoneListen** [comment]
@sbc100  I see an old problem #11507，I  have the same problem, Has the ”wasm-objdump“  been dropped.

**Comment by DoneListen** [comment]
@sbc100  I see the need to use EMSCRIPTEN KEEPALIVE to export the sidemodule's methods,But what if I want to use the c++ class of the sidemodule in the main module.

**Comment by sbc100** [comment]
wasm-objdump is part of the wabt tool.    We don't ship that with emscripten but you can still use it.

Can you share how you are linking your side module (i.e. the full link command)?  Are you using `-sSIDE_MODULE=1` or `-sSIDE_MODULE=2`?

**Comment by sbc100** [comment]
Can you try with `-sSIDE_MODULE=1` ?

**Comment by DoneListen** [comment]
> Can you try with `-sSIDE_MODULE=1` ?

Oh,I thought If the main module uses main doule=2, the sidemodule must use side module=2.

**Comment by DoneListen** [comment]
> > > Can you try with `-sSIDE_MODULE=1` ?
> > 
> > 
> > Oh,I thought If the main module uses main doule=2, the sidemodule must use side module=2.
> 
> Nope, they are independent.

Ok, thank you very much for your reply.Do we support side-modules dependent side-modules

**Comment by sbc100** [comment]
Not really, no.  But you can link the main module against any number of side modules and they can see each others symbols.

**Comment by DoneListen** [comment]
> Not really, no. But you can link the main module against any number of side modules and they can see each others symbols.

I understand. There is another problem. When compiling, the symbol of the side-module used by the main module will warn that the symbol does not undefined. That's normal, right? Can we get rid of these warnings， Because it's too much

**Comment by sbc100** [comment]
No you should no see warnings.   When are you seeing the warnings?   At build time or at run time?  Are you passing the side module as a command line argument when linking the main module?

**Comment by DoneListen** [comment]
> No you should not see warnings. When are you seeing the warnings? At build time or at run time? Are you passing the side module as a command line argument when linking the main module?

build time.I used  -s AUTOLOAD_DYLIBS=0 so I didn't add side module as a command line argument. I tried to add it. There's no warning. Thanks.

**Comment by DoneListen** [comment]
@sbc100  Each worker will download side-modules once. When there are more sub-modules, is there any good optimization method?

**Comment by sbc100** [comment]
Currently that is the only method we have.  I'm looking into finding a way to postMessage modules over to new threads, and that should help in many cases (but probably not all).    This is the bug if want to track the progress: https://github.com/emscripten-core/emscripten/issues/17078

I guess this issue can now be closed?  (if so place go ahead and close it).

**Comment by DoneListen** [comment]
> Currently that is the only method we have. I'm looking into finding a way to postMessage modules over to new threads, and that should help in many cases (but probably not all). This is the bug if want to track the progress: #17078
> 
> I guess this issue can now be closed? (if so please go ahead and close it).

Ok.
