### ISSUE TITLE
Update musl once it supports C23

### ISSUE THREAD

**Issue by tlively** [emscripten-core/emscripten#19179]
C23 adds a number of new standard library features, including new library headers like <stdckdint.h> and new math functions like `roundeven`.

Library calls to `roundeven` in particular, and possibly other new math functions, can be emitted by clang to lower builtin functions like `__builtin_roundeven`, so it would be good to support these functions as soon as possible because clang claims to support them.

Unfortunately at time of writing it does not look like musl supports the new C23 features. Once it does, we should make sure to update it.

**Comment by tlively** [comment]
@sbc100, has this been done? Apparently the `roundevenf` problem went away.

**Comment by sbc100** [comment]
I don't think anything has changed on the emsciprten or musl side related to this.

Can you share an example of how to reproduce the issue.  If its no longer reproducible I guess we can close this?

**Comment by mr-c** [comment]
``` shell
emsdk install a6b372d7f0867dd9828a8c1e9b7402351d008e2a
git clone https://github.com/simd-everywhere/simde.git
cd simde
mkdir build
cd build
meson setup --cross-files docker/cross-files/emscripten32.cross build ..
# may need to edit the paths to emsdk there
meson test x86/sse2/emul/c
# get error like https://github.com/simd-everywhere/simde/issues/1001#issue-1650382278
emsdk install tot
meson setup --wipe
meson test x86/sse2/emul/c
# test passes
```

**Comment by mr-c** [comment]
Git bisecting shows that the fix occurred in https://chromium.googlesource.com/emscripten-releases/+/59c7dcf6de3f78d790b19480eb834be41d59f810
which includes https://github.com/llvm/llvm-project/commit/bb648c9177cda700ae63cfced347f62d417a4824 "[WebAssembly] Add lowering for llvm.rint and llvm.roundeven"

From SIMDe's perspective we are good; you all may want an updated musl for other reasons

**Comment by sbc100** [comment]
I don't see any relevant changes to musl, although they release a new version 3 weeks ago (v1.2.5).
