### ISSUE TITLE
Wrong type for WGPUDepthStencilState.DepthBias

### ISSUE THREAD

**Issue by glspud** [emscripten-core/emscripten#19175]
https://github.com/emscripten-core/emscripten/blob/4e15675e29ce1d2bc826b21e79ac42b0acf3bccf/src/library_webgpu.js#L1308
DepthBias is a signed integer, while it's treated here as a u32/pointer?. This causes an error when DepthBias = -1

**Comment by kainino0x** [comment]
Good catch!
@kripken I've created a webgpu GitHub label to collect our bugs, is that alright? (you can keep assigning me though)

**Comment by kripken** [comment]
Sounds good about the label! And let me know if you want me to do something different than assigning you.

**Comment by beaufortfrancois** [comment]
FYI I've started https://github.com/emscripten-core/emscripten/pull/19777 to fix this issue.
