### ISSUE TITLE
Emscripten Tool errors with "Exception: Attempt to lock the cache but FROZEN_CACHE is set"

### ISSUE THREAD

**Issue by kihea** [emscripten-core/emscripten#19198]
When trying to build with cmake, an emscripten tool errors saying that FROZEN_CACHE is set. I've tried setting it to false in emscripten_config, but that has no effect on the error.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 ()
Ubuntu clang version 13.0.1-2ubuntu2.1
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/bin

**Failing command line in full:**
cmake --build .

**Full link command and output with `-v` appended:**
/usr/bin/cmake -S/mnt/c/Users/kihea/build/K.Engine -B/mnt/c/Users/kihea/build/K.Engine/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /mnt/c/Users/kihea/build/K.Engine/build/CMakeFiles /mnt/c/Users/kihea/build/K.Engine/build//CMakeFiles/progress.marks
/usr/bin/gmake  -f CMakeFiles/Makefile2 all
gmake[1]: Entering directory '/mnt/c/Users/kihea/build/K.Engine/build'
/usr/bin/gmake  -f CMakeFiles/K.Engine.dir/build.make CMakeFiles/K.Engine.dir/depend
gmake[2]: Entering directory '/mnt/c/Users/kihea/build/K.Engine/build'
cd /mnt/c/Users/kihea/build/K.Engine/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/c/Users/kihea/build/K.Engine /mnt/c/Users/kihea/build/K.Engine /mnt/c/Users/kihea/build/K.Engine/build /mnt/c/Users/kihea/build/K.Engine/build /mnt/c/Users/kihea/build/K.Engine/build/CMakeFiles/K.Engine.dir/DependInfo.cmake --color=
gmake[2]: Leaving directory '/mnt/c/Users/kihea/build/K.Engine/build'
/usr/bin/gmake  -f CMakeFiles/K.Engine.dir/build.make CMakeFiles/K.Engine.dir/build
gmake[2]: Entering directory '/mnt/c/Users/kihea/build/K.Engine/build'
[ 20%] Linking CXX executable bin/K.Engine.html
/usr/bin/cmake -E cmake_link_script CMakeFiles/K.Engine.dir/link.txt --verbose=1
/usr/bin/em++ -sALLOW_MEMORY_GROWTH=1 -sMAX_WEBGL_VERSION=2 -sMIN_WEBGL_VERSION=2 -sUSE_LIBPNG=1 -sUSE_SDL_MIXER=2 -sLLD_REPORT_UNDEFINED --preload-file /mnt/c/Users/kihea/build/K.Engine/Assets@Assets @CMakeFiles/K.Engine.dir/objects1.rsp -o bin/K.Engine.html
Traceback (most recent call last):
  File "/usr/share/emscripten/em++.py", line 14, in <module>
    sys.exit(emcc.run(sys.argv))
  File "/usr/share/emscripten/emcc.py", line 1178, in run
    phase_calculate_system_libraries(state, linker_arguments, linker_inputs, newargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2677, in phase_calculate_system_libraries
    extra_files_to_link += ports.get_libs(settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 342, in get_libs
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "/usr/share/emscripten/tools/ports/sdl2.py", line 23, in get
    ports.fetch_project('sdl2', 'https://github.com/libsdl-org/SDL/archive/' + TAG + '.zip', SUBDIR, sha512hash=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
**Exception: Attempt to lock the cache but FROZEN_CACHE is set**
gmake[2]: *** [CMakeFiles/K.Engine.dir/build.make:150: bin/K.Engine.html] Error 1
gmake[2]: Leaving directory '/mnt/c/Users/kihea/build/K.Engine/build'
gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/K.Engine.dir/all] Error 2
gmake[1]: Leaving directory '/mnt/c/Users/kihea/build/K.Engine/build'
gmake: *** [Makefile:91: all] Error 2

**Comment by sbc100** [comment]
You emscripten install is setup with `FROZEN_CACHE` set to true in the config file.   How did you install emscripten?  Do you know where the config file is (its called `.emscripten` normal) and what its contents are?    I'm guessing you are using some kind of distro package which sets `FROZEN_CACHE`?

**Comment by kihea** [comment]
Was able to fix the problem indirectly by deleting emsdk, installing emscripten through chocolatey, then compiling.

**Comment by wernight** [comment]
I found that this only happens when I try to set the "ports" I need in `CMakeLists.txt` like:

    set_target_properties(MyLibrary PROPERTIES COMPILE_FLAGS "-sUSE_SDL=2 -sUSE_SDL_IMAGE=2 -sUSE_SDL_MIXER=2 -sUSE_BOOST_HEADERS=1" LINK_FLAGS "-sUSE_SDL=2 -sUSE_SDL_IMAGE=2 -sUSE_SDL_MIXER=2 -sUSE_BOOST_HEADERS=1")

Then `emmake make` will fail with the above error.

I also installed it using Ubuntu's package manager.

**Comment by sbc100** [comment]
I guess ubuntu is configuring emscripten with FROZEN_CACHE..  this prevents new libraries from being added to the cache in this way.  Perhaps open a bug against that package if you want new pre-built libraries to be packaged.

**Comment by andrewrgarcia** [comment]
I had the same problem with my installation. My operating system is Ubuntu LTS 22.04 (LINUX). 

My problem came from a `sudo apt install emscripten`

My solution was to uninstall emscripten and reinstall using the [emsdk (recommended by emscripten)](https://emscripten.org/docs/getting_started/downloads.html). Then running the compilation with `emcc` and running the compiled with `emrun`

**Comment by radekdoulik** [comment]
@sbc100 how does `FROZEN_CACHE` option work? Is there more documentation besides https://github.com/emscripten-core/emscripten/blob/61d4ae0324a402eb776780282781fa5ca0c76d98/tools/config_template.py#L50?

**Comment by sbc100** [comment]
`FROZEN_CACHE` just means that emcc won't write to the cache/sysroot.  Its useful for cases like this where the sysroot is read only so new things can't be added to it.

**Comment by hotorujix** [comment]
@andrewrgarcia, a workaround:

1. Copy /usr/share/emscripten/cache/ to /home/user/.

2. Copy /usr/share/emscripten/.emscripten to /home/user/config.

3. In `config` set `FROZEN_CACHE = False` and `CACHE = '/home/user/cache'`.

4. Build `emcc --em-config /home/user/config app.cpp -o app.html -s USE_SDL=2`.

5. Set `FROZEN_CACHE = True` back.

Tools: `apt-file list emscripten` and `man emcc`.

**Comment by andrewrgarcia** [comment]
Why would I need a workaround if my solution worked?

**Comment by andrewrgarcia** [comment]
> @andrewrgarcia, a workaround:
> 
> 
> 
> 1. Copy /usr/share/emscripten/cache/ to /home/user/.
> 
> 
> 
> 2. Copy /usr/share/emscripten/.emscripten to /home/user/config.
> 
> 
> 
> 3. In `config` set `FROZEN_CACHE = False` and `CACHE = '/home/user/cache'`.
> 
> 
> 
> 4. Build `emcc --em-config /home/user/config app.cpp -o app.html -s USE_SDL=2`.
> 
> 
> 
> 5. Set `FROZEN_CACHE = True` back.
> 
> 
> 
> Tools: `apt-file list emscripten` and `man emcc`.

Why would I need a workaround if my solution worked?
