### ISSUE TITLE
custom worker runs multiple times when compiled with pthreads

### ISSUE THREAD

**Issue by TheTrio** [emscripten-core/emscripten#19210]
Here's the output of `emcc -v`
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 (d33328b22db1aa62a51c50731e9645951a2038bc)
clang version 15.0.0 (https://github.com/llvm/llvm-project f3bc7fd5465a3a919388b6a0307553ef4a6d39c9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/lib/emsdk/upstream/bin
```

I have defined a worker which does nothing but call the emscripten glue code(`a.out.js`). 

```js
// file: my_worker.js

console.log('called')
importScripts('a.out.js')
```

The C++ code is irrelevant I think. I used to following to reproduce the issue

```cpp
// file: main.cpp
#include <emscripten/bind.h>
using namespace emscripten;
EMSCRIPTEN_BINDINGS(my_module){}
```

The JS does just one thing - it creates a worker from `worker.js`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script>
      const worker = new Worker('./my_worker.js')
    </script>
  </head>
</html>
```

I compile the code with the following command `emcc  main.cpp --bind -s PTHREAD_POOL_SIZE=4 -pthread -O2 -s ALLOW_MEMORY_GROWTH=1`

Notice that the worker is executed multiple times(confirmed by the multiple console.logs). You can also see in the dev tools that its requested more than once by `a.out.worker.js` which I find confusing.

![image](https://user-images.githubusercontent.com/10794178/233329125-8bf00f6d-f419-4153-ade5-1a1c20ca717a.png)

Is this expected behavior? Why is `a.out.worker.js` executing `my_worker.js`? In this example, this perhaps isn't that big of an issue. However, the real code I had defined `onmessage` on the worker as follows

```js
// file: worker.js
importScripts('a.out.js')
onmessage = (e) => ...
```

The problem was, since this code was being run by `a.out.worker.js` as well, it redefined their `onmessage` and my worker was getting a bunch of events I didn't expect it to. 

Is there some flag or some configuration I'm missing here? Thanks!

**Comment by sbc100** [comment]
The 4 requests would seem to correspond to the 4 worker threads that correspond to `PTHREAD_POOL_SIZE=4`.

The new threads should load `a.out.worker.js` which should then load `a.out.js`.    Are you sure it not the case that this is 4 loads of  `a.out.worker.js` ?  That would make some sense, but it would make any sense that your `my_worker.js` would be loaded 4 times.

**Comment by TheTrio** [comment]
> Are you sure it not the case that this is 4 loads of a.out.worker.js ?

I don't think so. In the screenshot I posted above, you can see the multiple fetches to `my_worker.js`. This is in the 4th column. The 5th column is the initiator - which is `a.out.worker.js`

In either case, the console.log can only appear from my worker so I'm pretty certain its being called from the other workers from some reason

**Comment by sbc100** [comment]
Can you using devtools to figure out why `my_worker.js` would be loaded by `a.out.worker.js` .. it odd since I don't see how the emscripten-generated code could even know about the existence or `my_worker.js`?  Perhaps you can share the backtrace that leads to the loading the the code?

**Comment by TheTrio** [comment]
Looks like its here(I've added the console.log)

![image](https://user-images.githubusercontent.com/10794178/233501624-e47d7e87-ab97-4dca-bf03-d82b6f2a4c8c.png)
![image](https://user-images.githubusercontent.com/10794178/233501666-d0ddd6ba-b4b0-4991-9130-62ecae6e16a4.png)

**Comment by TheTrio** [comment]
I think I've figured it out - this is part of `a.out.js` which does a postmessage on the workers

```js
file: a.out.js
worker.postMessage({
      cmd: 'load',
      urlOrBlob: Module['mainScriptUrlOrBlob'] || _scriptDir,
      wasmMemory: wasmMemory,
      wasmModule: wasmModule,
    })
```

and `_scriptDir` is defined as `my_worker.js`. That happens here

```
file: a.out.js
if (ENVIRONMENT_IS_WORKER) {
  _scriptDir = self.location.href
}

Indeed, if I rewrite my worker as follows, everything works as expected

```js
console.log('called')
var Module = {
  mainScriptUrlOrBlob: 'a.out.js',
}
importScripts('a.out.js')
```

**Comment by sbc100** [comment]
I see, so when you load `a.out.js` within a worker like that you need tell it its own name.   I guess it can't figure it out on its own and it just uses `self.location.href` a best guess.

Sounds like you found the solution using the `mainScriptUrlOrBlob` fix which I assume is indented for this very purpose.

**Comment by TheTrio** [comment]
Looks like its documented [here](https://emscripten.org/docs/api_reference/module.html?highlight=mainscripturlorblob#Module.mainScriptUrlOrBlob), although I don't see how I could've found it without knowing exactly what I was looking for :shrug: 

So I guess nothing survives in this issue?

**Comment by sbc100** [comment]
Yes, I think this can be closes.

**Comment by TheTrio** [comment]
Well, hopefully this prevents someone from scratching their heads in confusion in the future. 

Thanks for your help! Closing this.

**Comment by TheTrio** [comment]
This is unrelated but it arises out of this - is there a way to bundle `a.out.js` into `a.out.worker.js`? `importScripts` in `a.out.worker.js` does a network request and so `a.out.js` is fetched multiple times, slowing things down.

**Comment by sbc100** [comment]
We don't currently have a way to do that no.   Presumably it would result in the same number of bytes over the network though?

**Comment by TheTrio** [comment]
Yes, it will probably be cached by the browser but I think bundling might be more performant overall.
