### ISSUE TITLE
DynCall exports in STANDALONE_WASM

### ISSUE THREAD

**Issue by mhils** [emscripten-core/emscripten#19211]
I'm trying to compile a relatively complex C++ program (Wireshark's sharkd) to WebAssembly. Ideally I would like to end up with a WASI executable that could be run with wasmtime, but I cannot use wasi-sdk as Wireshark transitively depends on libffi (which only has an emscripten port). So now I'm trying to compile with `emscripten/emsdk:3.1.36` in `STANDALONE_WASM` mode, and then implement the non-WASI imports myself. I have successfully done that for a few `__syscall_*` functions (yay), but now I'm stuck with implementing `invoke_x`.

1. My first naive attempt was to take the first argument passed to `invoke_ii` as an index for `__indirect_function_table`, but this points to a function that takes 16 arguments instead of one. I must be holding something wrong here?
2. My second attempt was to compile with `-sSUPPORT_LONGJMP=0 -fno-exceptions`, but that does not fly because Wireshark makes some non-trivial use of longjmp.
3. Third, Looking at the generated `sharkd.js`, I see `invoke_ii` being implemented with a call to `dynCall_ii`. However, there are no `dynCall_` exports in the `sharkd.wasm` module. Running `node sharkd.js -` crashes with `ReferenceError: dynCall_ii is not defined`. **This seems like an emscripten bug?**
4. Fourth, I tried compiling without `STANDALONE_WASM`. The good news is that I _do_ get `dynCall` exports, but not unexpectedly there also are a lot of non-WASI imports I don't want to implement.

Does anyone have any hints on:

1. Why using `__indirect_function_table` does not work?
2. How I can get `STANDALONE_WASM` builds to contain `dynCall` exports? I've tried setting 
`-sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$dynCall` [^1], setting `-sINCLUDE_FULL_LIBRARY=1`, as well as fiddling with `sEXPORTED_FUNCTIONS` and `EXPORTED_RUNTIME_METHODS`. Unfortunately I was not able to figure out why I'm not getting `dynCall` exports.

Thanks!

Related: #15894 https://github.com/emscripten-core/emscripten/issues/18253#issuecomment-1332355421

[^1]: I also tried dynCall_ii, \\$dynCall, $$dynCall, dynCall, getWasmTableEntry, $getWasmTableEntry, as well as various other variants in an attempt for something to show up.

**Comment by kripken** [comment]
> this points to a function that takes 16 arguments instead of one

Are you using `EMULATE_FUNCTION_POINTER_CASTS` perhaps? That uses 16 parameters by default:

https://github.com/WebAssembly/binaryen/blob/113db86e5e83e8eacd676871b32a651fc9ce064c/src/passes/FuncCastEmulation.cpp#L153-L157

**Comment by kripken** [comment]
In that mode, the calling convention has 16 arguments in each function, and all are `i64`. So that is why the function seemed wrong for the signature, but it's probably right, since what you did is correct (to take the first argument of `invoke` methods as the function pointer). So continuing with option 1 should be ok I think.
