### ISSUE TITLE
emsdk 3.1.36 is causing an undefined symbol: malloc linker error when 3.1.35 did not

### ISSUE THREAD

**Issue by farzonl** [emscripten-core/emscripten#19234]
Please include the following in your bug report:

**Version of emscripten/emsdk:** 3.1.36
Please include the output `emcc -v` here
```bash
root@8965ce12fb5f:~/emsdk# emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.36 (518d9fea335f7cd2b5771e43df76e0535c6df5dd)
clang version 17.0.0 (https://github.com/llvm/llvm-project 5084abbea933b1a510556726a9e226b5ae22f19f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /root/emsdk/upstream/bin

```
**Failing command line in full:**
The last good version was 3.1.35. Starting with 3.1.36 I am seeing the following issue
https://github.com/farzonl/warfLang/issues/36

```bash
#16 53.94 [100%] Linking CXX executable WarfLang_TEST.html
#16 54.93 error: undefined symbol: malloc (referenced by $stringToNewUTF8__deps: ['$lengthBytesUTF8','$stringToUTF8','malloc'], referenced by _tzset_js__deps: ['$stringToNewUTF8'], referenced by top-level compiled C/C++ code)
#16 54.93 warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
#16 54.93 warning: _malloc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
#16 54.95 Error: Aborting compilation due to previous errors
#16 54.97 em++: error: '/root/emsdk/node/15.14.0_64bit/bin/node /root/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpdajmrd54.json' failed (returned 1)
#16 54.99 make[2]: *** [test/CMakeFiles/WarfLang_TEST.dir/build.make:101: test/WarfLang_TEST.html] Error 1
#16 54.99 make[2]: Leaving directory '/root/build'
#16 54.99 make[1]: Leaving directory '/root/build'
#16 54.99 make[1]: *** [CMakeFiles/Makefile2:424: test/CMakeFiles/WarfLang_TEST.dir/all] Error 2
#16 54.99 make: Leaving directory '/root/build'
#16 54.99 make: *** [Makefile:91: all] Error 2
#16 55.00 emmake: error: 'make -C build' failed (returned 2)
```
For testing this docker file will work:
https://github.com/farzonl/warfLang/blob/master/Dockerfile.emscripten

**Comment by farzonl** [comment]
From looking at:
https://github.com/emscripten-core/emscripten/compare/3.1.35...3.1.36

I think this might have to do with:
https://github.com/emscripten-core/emscripten/pull/19164/files

```
The `USES_DYNAMIC_ALLOC` setting has been deprecated.  You can get the same
  effect from `-sMALLOC=none`.
```

I tried adding `-sMALLOC=none` as a CFLAG and CXXFLAG but that didn't work. For cmake how should we pass in this setting?

**Comment by kleisauke** [comment]
> I tried adding `-sMALLOC=none` as a CFLAG and CXXFLAG but that didn't work. For cmake how should we pass in this setting?

`-sMALLOC=none` is a linker flag, so one should add it to the `LDFLAGS` environment variable. CMake provides the [`target_link_options`](https://cmake.org/cmake/help/latest/command/target_link_options.html) feature for this.

**Comment by sbc100** [comment]
Does you build use `-sUSES_DYNAMIC_ALLOC=0`?

**Comment by coderedart** [comment]
I was getting a new error in rust projects using wgpu/emscripten, so i had to manually add the flag for `MALLOC=none`

**Comment by sbc100** [comment]
What is the error you were seeing @coderedart?

**Comment by coderedart** [comment]
missing function error. the js file just had a dummy function called `_malloc` that crashed.

If i add the flag `MALLOC=none`, then i get another similar error `missing function: emscripten_builtin_malloc`

**Comment by coderedart** [comment]
This is the live deployed page https://coderedart.github.io/rust-sdl2-wasm/

The flags i use are listed in https://github.com/coderedart/rust-sdl2-wasm/blob/master/.cargo/config.toml

If i use the latest version of emscripten (3.1.37) i get `missing function: malloc` error with an abort.

But, if i set the version to 3.1.35 by commenting out https://github.com/coderedart/rust-sdl2-wasm/blob/master/.github/workflows/deploy.yaml#L15 , then everything works fine.

**Comment by farzonl** [comment]
The only broken version for me was 3.1.36. Using 3.1.37 fixed my problem.

**Comment by sbc100** [comment]
@coderedart do you have backtrace, or the full error message to see why the reference to `malloc` is coming from?   

Does adding `_malloc` to `-sEXPORTED_FUNCTIONS` fix the issue for you?

**Comment by coderedart** [comment]
@sbc100 Yes, adding `-sEXPORTED_FUNCTIONS=_malloc` fixes it with latest 3.1.37 :)

**Comment by sbc100** [comment]
Thanks, that sounds like a bug in the dependency system somewhere.   Any program that calls eglQueryString from native code should end up exporting malloc automatically.

In order to help debug this issue could you show the full call stack?  Who is calling `eglQueryString`?  Is it native code or JS code?

**Comment by coderedart** [comment]
finally found the problem. When you add the flag `ERROR_ON_UNDEFINED_SYMBOLS=0`, we get the _malloc missing error. If i remove that flag, malloc work fine.

you can comment out the flag at https://github.com/coderedart/emscripten_malloc/blob/master/.cargo/config.toml#LL10C15-L10C43 and see how it resolves the issue.

made a simple 10 lines example at https://github.com/coderedart/emscripten_malloc which just calls eglQueryString function.

deployed at https://coderedart.github.io/emscripten_malloc/ where you can see the problem in console.

Wgpu recommends using that flag at https://github.com/gfx-rs/wgpu/wiki/Running-on-the-web-with-Emscripten .

**Comment by sbc100** [comment]
Thanks for the repro case!   BTW, how can I tell the cargo world exactly which version of emscripten is being used?

**Comment by coderedart** [comment]
@sbc100 It just calls `emcc`, so use emsdk or something else to activate the relevant env.
