### ISSUE TITLE
"undefined symbol: errno" when linking with WASI libs

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#19236]
@sbc100 mentioned that linking libraries built for wasm32-wasi with Emscripten binaries should work, and it mostly does, but there's one difference I'm running into: `errno` is declared as a macro in Emscripten (and, in my understanding, same on most popular platforms), but it's an actual variable in WASI SDK: https://github.com/WebAssembly/wasi-libc/blob/38f48942fabf1b59e73bca126340b219fa9a78aa/libc-bottom-half/cloudlibc/src/libc/errno/errno.c#L87

As a result, building a sample like

```c
#include <errno.h>
#include <stdio.h>

int main() {
	printf("errno: %d\n", errno);
}
```

via WASI SDK Clang and then linking via Emscripten results in

```
$ /opt/wasi-sdk/bin/clang temp.c -target wasm32-wasi -o temp.o -c
$ emcc temp.o -o temp.wasm
wasm-ld: error: temp.o: undefined symbol: errno
```

**Comment by RReverser** [comment]
I'm not actually sure what the solution is here if any... I guess it doesn't make sense for Emscripten to also use a variable just to be compatible with WASI SDK, but on the other hand adding my own stub for this variable won't interact properly with Emscripten implementation of system functions...

**Comment by sbc100** [comment]
Yeah, I'm not sure we want to try make the C libraries compatible in that way.   The low level ABI should be the same but I'm not sure we can ensure that the two libc ABI are the same.   IIUC there is no standard ABI for libc, so for example, I don't think you can mix objects files build with glibc header with object files build with musl headers... but I could be wrong.

BTW it looks like calling `___errno_location` is the musl way of finding libc, but wasi-libc patches in its own custom support.  So I would suggest that removing the patch from wasi-libc would be more logical than trying to make emscripten do what wasi-libc does: https://github.com/WebAssembly/wasi-libc/blob/38f48942fabf1b59e73bca126340b219fa9a78aa/libc-top-half/musl/include/errno.h#L10-L21

**Comment by RReverser** [comment]
Anyway, I'll close it here as Emscripten does seem the wrong place to change this.
