### ISSUE TITLE
`_free` is not defined runtime error

### ISSUE THREAD

**Issue by jeswr** [emscripten-core/emscripten#19267]
Upgrading from emsdk 3.1.36 to 3.1.37 we have observed that we now get a `_free` is undefined error at runtime in particular environments, in particular trying to execute [this line of code](https://github.com/jeswr/swipl-devel/blob/dd40767447da7d7aec14288a96cb3951c15d831b/src/wasm/prolog.js#L507-L508) when no `.data` file is provided and instead we are generating a dl image in advance that gets loaded (for example [see this sample project](https://github.com/SWI-Prolog/npm-swipl-wasm/tree/master/examples/generation)).

I suspect the removal of the global `_free` function for these environments occurred in [this commit](https://github.com/emscripten-core/emscripten/commit/1e7b78fe45cee0b96b64938f9742368923cd0713).

Is this an intentional breaking change? If so is there an easy fix on our end?

cc @rla @JanWielemaker

**Comment by sbc100** [comment]
I agree that the likely candidate is #18905.

If you want to use `_malloc` or `_free` outside of emscripten then you need to explicitly export them by adding them to `EXPORTED_FUNCTIONS`.  e.g. `-sEXPORTED_FUNCTIONS=_malloc,_free`.  This has been the case for a while now but I think perhaps the old reverse deps system was hiding the issue.

**Comment by jeswr** [comment]
Thanks for the info and response!
