### ISSUE TITLE
Pthread doesn't start in my build

### ISSUE THREAD

**Issue by DoLevi** [emscripten-core/emscripten#19265]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.32

**Failing command line in full:**
*No build-/link-time failure*

**Full link command and output with `-v` appended:**
```bash
emconfigure ./autogen.sh
emconfigure ./configure --host=none
emmake make -j$(nproc)

emcc -O3 -g -v \
  -fsanitize=undefined -fsanitize=address \
  -I /kvazaar/src \
  -s MODULARIZE=1 \
  -s EXPORT_ES6=1 \
  -s EXPORT_NAME="kvazaarEncoder" \
  -o "/dist/kvazaar-encoder.out.js" \
  -s WASM=1 \
  -s EXPORTED_FUNCTIONS=_malloc,_free \
  -s EXPORTED_RUNTIME_METHODS=addFunction,removeFunction,ccall,GROWABLE_HEAP_U8 \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s ALLOW_TABLE_GROWTH=1 \
  -s USE_PTHREADS=1 \
  -s SHARED_MEMORY=1 \
  -pthread \
  --cache "/cache" \
  /src/kvazaar_encoder.cc \
  /kvazaar/src/*.c /kvazaar/src/strategies/*.c /kvazaar/src/strategies/generic/*.c /kvazaar/src/strategies/avx2/*.c \
  /kvazaar/src/strategies/sse2/*.c /kvazaar/src/strategies/sse41/*.c /kvazaar/src/strategies/x86_asm/*.c \
  /kvazaar/src/strategies/altivec/*.c /kvazaar/src/extras/*.c
```
Build log [here](https://github.com/emscripten-core/emscripten/files/11359707/kvazaar-wasm-build.log)

Now my basic issue is that the code I compiled makes a call to `pthread_create` but its start routine is not run.
I am pretty sure that I am overlooking something obvious. Do you happen to know what?

Thank you!

**Comment by sbc100** [comment]
I imagine you are running into this very common problem where new workers don't actually get created until the event loop runs.   See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread.

You can try `-sPROXY_TO_PTHREAD` or `-sPTHREAD_POOL_SIZE=N`.. or you can yield the event loops before trying to use new threads.

**Comment by DoLevi** [comment]
Do any of these mentioned approaches work if I do not use a `main` function?

**Comment by sbc100** [comment]
Yes, its only the `-sPROXY_TO_PTHREAD` setting that is limited to programs main function.  The other two approaches both work regardless.

**Comment by DoLevi** [comment]
That's great and works very well. Thank you!

**Comment by DoLevi** [comment]
Oh sorry...
Except that I just saw an error being thrown from within a pthread when I try to use it:
```bash
RuntimeError: memory access out of bounds
    at __pthread_getspecific (pthread_getspecific.c:7)
    at __asan::AsanTSDGet() (asan_posix.cpp:130)
    at __asan::GetCurrentThread() (asan_thread.cpp:424)
    at __sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned __sanitizer::BufferedStackTrace::UnwindImpl(unsigned long, unsigned long, void*, bool, unsigned int) (asan_stack.cpp:63)
    at __sanitizer::BufferedStackTrace::Unwind(unsigned long, unsigned long, void*, bool, unsigned int) (sanitizer_stacktrace.h:133)
    at ::malloc(__sanitizer::uptr) (asan_malloc_linux.cpp:69)
    at // ..
```

This occurs at a call to `malloc(sizeof(kvz_data_chunk))` where `kvz_data_chunk` is
```C
typedef struct kvz_data_chunk {
  uint8_t data[4096];
  uint32_t len;
  struct kvz_data_chunk *next;
} kvz_data_chunk;

The same call not being executed in a pthread is executed without issues

**Comment by sbc100** [comment]
Actually it looks like you already have a separate issue for the asan crash: https://github.com/emscripten-core/emscripten/issues/19268?   Is that the same thing?
