### ISSUE TITLE
keydown callback stops working after i register mousedown callback

### ISSUE THREAD

**Issue by pegvin** [emscripten-core/emscripten#19266]
**Version of emscripten/emsdk:** 3.1.34-git

If I set the mousedown callback, it overrides the keydown callback (it seems like):

```c++
  // Keyboard Key Down:
  emscripten_set_keydown_callback("#canvas", this, 0, +[](int eventType, const EmscriptenKeyboardEvent* e, void* userData) -> EM_BOOL {
    std::cout << "Key down: " << e->keyCode << "\n";
    return EM_FALSE;
  });

  // Mouse Button Down:
  emscripten_set_mousedown_callback("#canvas", this, 0, +[](int eventType, const EmscriptenMouseEvent* e, void* userData) -> EM_BOOL {
    std::cout << "Mouse down: " << e->button << "\n";
    return EM_FALSE;
  });
```

In this case, only the mouse down works... if I don't register this mouse callback, then the keyboard works...

**Comment by sbc100** [comment]
Do you know if this is new issue?  (i.e. did it work in some older version of emscripten?)

**Comment by pegvin** [comment]
no i did not try it with previous versions of emscripten.

**Comment by pegvin** [comment]
closing the issue as the person i opened it on behalf doesn't seem to be following or doesn't give a shit at all.

thanks all for help!
