### ISSUE TITLE
Installation error on macbook: HTTP Error 404 on wasm-binaries-arm64.tbz2

### ISSUE THREAD

**Issue by OceanOak** [emscripten-core/emscripten#19275]
**Version of emscripten/emsdk:**
3.1.37
I've tried version 3.1.36, and it failed as well.

**Failing command line in full:**
git clone https://github.com/emscripten-core/emsdk.git   && cd emsdk   && ./emsdk install 3.1.37   && ./emsdk activate 3.1.37

**Error: Downloading URL** 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7c905cfc1ca6699f6ccb288ae174902cfbdcf0a2/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found

**Full error**
```
RUN git clone https://github.com/emscripten-core/emsdk.git   && cd emsdk   && ./emsdk install 3.1.37   && ./emsdk activate 3.1.37:
#0 0.216 Cloning into 'emsdk'...
#0 4.797 Resolving SDK version '3.1.37' to 'sdk-releases-7c905cfc1ca6699f6ccb288ae174902cfbdcf0a2-64bit'
#0 4.797 Installing SDK 'sdk-releases-7c905cfc1ca6699f6ccb288ae174902cfbdcf0a2-64bit'..
#0 4.797 Installing tool 'node-15.14.0-64bit'..
#0 4.797 Downloading: /home/dark/emsdk/zips/node-v15.14.0-linux-arm64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v15.14.0-linux-arm64.tar.xz, 21182264 Bytes
#0 4.797  [----------------------------------------------------------------------------]
#0 11.31 Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/7c905cfc1ca6699f6ccb288ae174902cfbdcf0a2/wasm-binaries-arm64.tbz2': HTTP Error 404: Not Found
#0 11.31 error: installation failed!
#0 11.31 Unpacking '/home/dark/emsdk/zips/node-v15.14.0-linux-arm64.tar.xz' to '/home/dark/emsdk/node/15.14.0_64bit'
#0 11.31 Done installing tool 'node-15.14.0-64bit'.
#0 11.31 Installing tool 'releases-7c905cfc1ca6699f6ccb288ae174902cfbdcf0a2-64bit'..
------
ERROR: failed to solve: executor failed running [/bin/sh -c git clone https://github.com/emscripten-core/emsdk.git   && cd emsdk   && ./emsdk install 3.1.37   && ./emsdk activate 3.1.37]: exit code: 1
```

**More information:**
- Python3 —version  : Python 3.11.2
- chip M1 Pro
- Accessing the URL from the browser I get: 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: webassembly/emscripten-releases-builds/linux/7c905cfc1ca6699f6ccb288ae174902cfbdcf0a2/wasm-binaries-arm64.tbz2</Details>
</Error>
```

**Comment by sbc100** [comment]
Are you running linux on that macbook?  It looks like its trying to download the linux arm64 binaryen, rather than the macOS ones.

For linux binaries you need to use `./emsdk install latest-arm64-linux` since we don't have linux arm64 binaries for all releases just yet.

**Comment by OceanOak** [comment]
This is really helpful. Thank you! I am running it inside a Docker container.
Do you have an estimated timeline for when you might have linux arm64 binaries available for all releases?

**Comment by sbc100** [comment]
Currently there is a manual update step that someone (i.e. myself) has has to do for each release.   While it would be nice to make it automatic and/or faster we don't currently have a plan for how to do it.  

See https://github.com/emscripten-core/emsdk/issues/547 for the background on this.

Also, I think this issue is a dup of https://github.com/emscripten-core/emsdk/issues/1211

**Comment by sbc100** [comment]
Is there some reason you can't use the native macOS toolchain?

**Comment by OceanOak** [comment]
> Is there some reason you can't use the native macOS toolchain?

I'm working on a large project in an Ubuntu-based devcontainer

**Comment by jozefchutka** [comment]
Just hit the same issue with latest binaries missing. There seems to be a couple github issues and PR related to this topic. I wonder which one to track?
