### ISSUE TITLE
conflicting documentation statements about the performance of webassembly vs native

### ISSUE THREAD

**Issue by artificiel** [emscripten-core/emscripten#19297]
here it says emscripten WebAssembly is "almost as fast" as native:
https://github.com/emscripten-core/emscripten/blob/29cb1f5ad50c5e2b4dd521e137ca0499bbd9efb3/site/source/docs/introducing_emscripten/about_emscripten.rst?plain=1#L28-L30

here it says it's half as fast:
https://github.com/emscripten-core/emscripten/blob/29cb1f5ad50c5e2b4dd521e137ca0499bbd9efb3/site/source/docs/optimizing/Optimizing-Code.rst?plain=1#L248

which one is correct?

**Comment by kripken** [comment]
Thanks, I'll update the docs. The first link is more accurate - "half the speed" was true back in the early asm.js days, but that's about a decade ago :smile: The speed today is often very close to native, but there are exceptions with things like certain SIMD operations.

**Comment by artificiel** [comment]
great -- that's what I assumed (we are currently preparing a roadmap for a project that could go with emscripten, and the deciders will probably do a bit of research to confirm the claims of approximate native performance, so better not to have remnants lying around)

**Comment by sbc100** [comment]
I think we can close this now?
