### ISSUE TITLE
Hope emscripten can support more glu and glut functions, much appreciated!

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#1929]
I just tried to convert my previous OpenGL projects into WebGL ones, however, I found:

warning: unresolved symbol: glutSolidCube
warning: unresolved symbol: glutSolidSphere
warning: unresolved symbol: gluNewQuadric
warning: unresolved symbol: gluCylinder

I had attached both glu and glut headers, but it seems that didn't work compatibly and when I open the generated html file, "Could not create canvas".

Hope someone can help me figure it out, much appreciated!!

**Comment by skyfore** [comment]
@kripken  hello, I want to know how can I implements it and build it in my own cpp file ? just wirte that function in my cpp file ?

**Comment by juj** [comment]
You could try compiling FreeGLUT from https://github.com/dcnieho/FreeGLUT, but that is probably not a simple short project, but will require knowledge to port build systems and integrate with Emscripten specific APIs.
