### ISSUE TITLE
Abnormal Printf Behavior

### ISSUE THREAD

**Issue by MoMo-UMN2021** [emscripten-core/emscripten#19296]
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Language used: C

Printf  with format specifier when used inside a loop behaves weirdly. When a newline character is present in the print statement, the program executes normally. When no newline character is found, the program stops the execution all together. 

One example code: 
```
#include <stdio.h>
#include <string.h>

int main() {
  int x = 0;

 printf("hello, world! \n");   
  while (x <= 10)
  {
    printf("hello, world! %d", x);    
    x++;
  }

  return 0;
}
```

The programs only output the first **hello, world!** and then stops the execution.

**Comment by sbc100** [comment]
Are you running on the web or under node?  Can you trying building with `-sEXIT_RUNTIME`?

**Comment by MoMo-UMN2021** [comment]
@sbc100 , I am running on web. I tried to use the command: `emcc printf_no_newline.c -sEXIT_RUNTIME -o printf_no_newline.html` but got the same issue.

**Comment by sbc100** [comment]
Why I build your example (without optimizations, or with assertions enabled) I see the following in the JS console:

```
out.js:1091 stdio streams had content in them that was not flushed. you should set EXIT_RUNTIME to 1 (see the FAQ), or make sure to emit a newline when you printf etc.
```

If I rebuild with `-sEXIT_RUNTIME` then it fixes the issue and I see the full output in the console both under node.  

Can you double check that you rebuild with `-sEXIT_RUNTIME` and can you check the output in the html console?

**Comment by MoMo-UMN2021** [comment]
I tried building with command:
`emcc printf_no_newline.c -sEXIT_RUNTIME -o printf_no_newline.html`

The output seems to be correct in this case.

Are we expected to add -sEXIT_RUNTIME always or should this be internally enabled while building any C code?

**Comment by sbc100** [comment]
`-sEXIT_RUNTIME` in this case is only needed because you didn't end you output with a newline.

If you know that you module is finished once main returns then yes you should set `-sEXIT_RUNTIME`.. otherwise the runtime doesn't exit and buffered standard output won't be written (standard output only gets written once a new lines is seen.. otherwise it is buffered).

**Comment by sbc100** [comment]
If this answers your question,  perhaps this issue can be closed?
