### ISSUE TITLE
on js side, how to addFunction to c/c++ child thread

### ISSUE THREAD

**Issue by iyouw** [emscripten-core/emscripten#19307]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.37 (d02c29f95e9e68f2f50c2b0432c56a671814d5c8)
**the real problem:**
when instantiate the webassembly module in the webworker which is created by a pthread, the emcc generated js pass the import environment and the memory of the parent thread to the webworker, but did not pass the web assembly table to the web worker. so when the webworker invoke the function which is dynamic register by the addFunction, because of  the parent did not pass the dynamic webassembly table to the webworker, so the webworker failed  invoking by throwing a `table index is out of bounds` error.  maybe the question is that webassembly can not be shared as webassembly memory.  Would somebody like to give me some advice to handle this case? 
**the solution(i think)**
i think it is  maybe a solution that when the webworker failed to invoking the callback, the webworker can send a message to it's parent to invoking the callback function.

**Comment by sbc100** [comment]
This won't work since threads don't share the wasm table between them.    

See https://github.com/emscripten-core/emscripten/issues/19292.. I think this can be closed as duplicate of that issue?

**Comment by iyouw** [comment]
thank you very much, i will took a look at proxying.h @sbc100

**Comment by iyouw** [comment]
@sbc100  i have been readed your solution. i did not know,how to  pass `callJSFuntion` to native(c/c++) side. the follow is my use case. could you  give me some advice?
**native side(main.c)**
```c
#include "emscripten.h"

#include "pthread.h"
#include "stdio.h"

typedef void (*Callback)(int arg);

static Callback callback;

static pthread_t child_thread;

static int count;

static void *start_child(void *arg)
{
    while(1)
    {
       printf("hello from child thread\n");
       (*callback)(count++);
       if (count >= 10000) count = 0;
    }
}

EMSCRIPTEN_KEEPALIVE
void open(Callback cb)
{
  callback = cb;
  count = 1;
  if (pthread_create(&child_thread, NULL, &start_child, NULL) != 0)
  {
    perror("create thread failed");
    exit(EXIT_FAILURE);
  }
}

EMSCRIPTEN_KEEPALIVE
void close()
{
  if (pthread_cancel(child_thread) != 0)
  {
    perror("can not cancel child thread");
    exit(EXIT_FAILURE);
  } 
}
```
**JS Side**
```javascript
import main from "./main.js"

main().then((instance) => {
  const callback = (count) => {
    console.log(`child thread loops: ${count}`);
  };
  const p = instance.addFunction(callback, 'vi');

  instance._open(p);

  setInterval(()=>console.log(`main loop`), 1000);
})
```

**Makefile**
```bash
CC := emcc

CFLAGS = -sMODULARIZE
CFLAGS += -sEXPORT_NAME=pt
CFLAGS += -pthread
CFLAGS += -sEXPORTED_RUNTIME_METHODS=addFunction

all: main

main: main.c
	$(CC) $(CFLAGS) -o main.js main.c -lpthread
```

**Comment by sbc100** [comment]
In my example, callJSFuntion would be written as a normal static JS function, just like any JS function that you call from native code.  In general you can either write such functions as EM_JS, or as JS library files that you pass in with `--js-library`

See  https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript

**Comment by iyouw** [comment]
@sbc100  thank you very much for taking time to reply me. but there still have problems when implement the `callJSFunction` either by using `EMJS`  or  `--js-library` .
**firstly**
let us look at implement it by using `EMJS`.  the `callJSFunction` assume there is a  `jsFunctionMap`  variable in the context(or   global).  but we can not pass the `jsFunctionMap` variable  to the webworker. since neither the webworker is generated by the `emcc` tool,  nor the `jsFunctionMap`  variable is not match the `clone algorithm` .
**secondly** 
let us look at implement it by using `--js-library`. the problem here is that, when we dynamicly add or replace function to the global `jsFunctionMap`, we cannot pass this change to the webworker. because only object that matches the `clone algorithm` can be passed to webworker. 
**conclution**
as we want to support dynamicly regsiter js function callback to native side(c/c++) with multithread, and there is a limitation that we can not directly pass this functions to webworker. how about the solution that i memtioned early? firstly invoke the callback in the webworker, when it failed, then invoke it in the parent(main) thread. 
**the end**
thank you again @sbc100 . please taking a seconds for my suggestion!

**Comment by sbc100** [comment]
You can make the `--js-library` functions with `__proxy` attributes such that they will be proxied back to the main thread and run there.   e.g. https://github.com/emscripten-core/emscripten/blob/347262aec9c4450e34b6af617d1420dbda2f6662/src/library.js#L1815

**Comment by iyouw** [comment]
@sbc100  thank you for your reply. i think the idea behind my suggestion and  the `--js-library` with `__proxy` is the same. so why not just move forward a little further to support all this use case(EMJS, addFunction etc...) when dynamicly register callbacks to native side's child thread.

**Comment by iyouw** [comment]
@sbc100 thank you very much. i find the `proxying.h` api  is the best solution for me.
