### ISSUE TITLE
Sync IDBFS before start C++ code

### ISSUE THREAD

**Issue by pinguin999** [emscripten-core/emscripten#19309]
Hi 

I want to use the IDBFS in my game engine for loading the savegames.
As I see there are 2 ways to initial sync the FS:

1. in C++ via, but this does run async and C++ does not know when FS is ready to use. 
```cpp
EM_ASM(
function myAppStartup(callback) {
  FS.mkdir('/data');
  FS.mount(IDBFS, {}, '/data');

  FS.syncfs(true, function (err) {
  // handle callback
  });
)
}
```

2. In JS, it works good but does not work in default emscripten html file.
```js
       Module.addRunDependency('syncfs);
        FS.syncfs(true, function (err) {
          if (err)
            console.error('Failure to synchronize from backing store: ' + err);
          else
            console.log('Successfully synced from backing store.');

          // Tell Emscripten to stop waiting.
          Module.removeRunDependency('syncfs');
        });
...

// And call it in preRun
    var Module = {
      preRun: [
         initUserFolder,
      ],

```

Is there a third way how I can elegantly initialise FS from C++ (without `ccall()`)

Thanks a lot!

**Comment by sbc100** [comment]
Why doesn't method 2 work with the default html output?  It seems like that method should work the same everywhere?  Where are you setting the `preRun` are you using `--pre-js=..`

**Comment by pinguin999** [comment]
Hi @sbc100 thank you for pointing out [--pre-js](https://emscripten.org/docs/tools_reference/emcc.html#emcc-pre-js)
For all want to do the same here is my js file: 

**pre.js**
```js
Module["preRun"].push(function () {
    addRunDependency('syncfs')

    FS.mkdir('/working1')
    FS.mount(IDBFS, {}, '/working1')
    FS.syncfs(true, function (err) {
      if (err) throw err
      removeRunDependency('syncfs')
      console.log("FS Synced")
    })
  });
```

In cmake I had to add the following flags:
```cmake
--pre-js pre.js -lidbfs.js -s FORCE_FILESYSTEM
```


After writing to disk in C++ you have to sync with JS with:

```cpp
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif


....

// After write to disk
#ifdef __EMSCRIPTEN__
	EM_ASM(
		FS.syncfs(false, function(err) {
			if (err) {
				console.warn("Error saving:", err);
			}
		})
	);
#endif
```


All is also in the visible in the ALPACA and JNGL commit: 
https://github.com/pinguin999/ALPACA/commit/06cdcde8cc5f3071dc9412f6771ce3ea9e00c23b

https://github.com/jhasse/jngl/commit/1f61d6455096e5a84ef737a7f54b9dead18dae8d
