### ISSUE TITLE
Where are saved files downloaded with C++ fetch API ?

### ISSUE THREAD

**Issue by JeromeDesfieux** [emscripten-core/emscripten#19335]
I need to download a file to persistant storage, and I use the fetch API from C++ for that purpose.

I think that everything is OK (I can see that with the FETCH_DEBUG flag) and the status is 200.

But I don't know how to retrieve my file !
I used `attr.destinationPath` to specify the location but `std::filesystem::exists(path)` always returns false.
I tried to call the FS sync methods and wait but it doesn't change the result.

I have also a mounted IDBFS. Can it conflict ?

That might be related to https://github.com/emscripten-core/emscripten/issues/11589.
But the proposed workaround is not very nice as it requires to load all data in memory first which can be problematic if the size is important.

The source code:
```C
bool network_download(const std::string& urlSrc, const std::filesystem::path& dest)
{
    // From https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState
    const auto state_done{4};

    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    strcpy(attr.requestMethod, "GET");
    attr.attributes = EMSCRIPTEN_FETCH_PERSIST_FILE | EMSCRIPTEN_FETCH_REPLACE;
    attr.destinationPath = dest.c_str();

    emscripten_fetch_t* fetch = emscripten_fetch(&attr, urlSrc.c_str());
    while(fetch->readyState < state_done)
        emscripten_sleep(100);

    emscripten_fetch_close(fetch);

    return fetch->status == 200;
}

int main()
{
    std::string url = "https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_land.geojson";
    std::filesystem::path savepath = "ne_50m_land.geojson";
    bool download_ok = network_download(url, savepath);

    CATCH_REQUIRE(download_ok);             // assertion passes
    CATCH_REQUIRE(fs::exists(savepath));     // assertion fails
}
```

**Comment by sbc100** [comment]
Can you share the full link command line you are using?

**Comment by sbc100** [comment]
Can maybe can you share your filesystem startup/mount code?

**Comment by sbc100** [comment]
BTW instead of looping waiting for `fs_is_ready` I think you can do `addRunDependency('fs')` in your `preRun` and then `removeRunDependency('fs')` when the FS is ready.  Also, I would recommend using `--pre-js` to setup your preRun.
Not related to your actual issue, just a couple of tips.

**Comment by sbc100** [comment]
I think `test/fetch/to_indexeddb.cpp` might actually be broken.. since I don't see it actually testing that the file exists..

**Comment by sbc100** [comment]
So it looks like the use of IDB as a cache by the Fetch API is completely separate to use IDBFS usage.   See https://emscripten.org/docs/api_reference/fetch.html#persisting-data.   You can have the fetch API read and write data the an IDB store but this is not the same store used by the filesystem.

if you want the file to appear in the filesystem you would need to take the resulting bytes and using the normal `fopen`/`fwrite` calls to write the file.

**Comment by JeromeDesfieux** [comment]
OK. Thank you.
Can I maybe access the file in JS side (I am newbie with web techno, maybe the answer is obvious...)?
Otherwise, it'd look like EMSCRIPTEN_FETCH_PERSIST_FILE is not really usefull...

(thank you for the tips, I appreciate 🙂)

**Comment by JeromeDesfieux** [comment]
So it looks it is possible to retrieve the file afterwhile with a fetch request, using the `EMSCRIPTEN_FETCH_NO_DOWNLOAD` attribute.

About my use case, I adapted the code in order to request per range when possible, and then flush from memory from my custom IDBFS.
