### ISSUE TITLE
Cannot create WGPUInstance

### ISSUE THREAD

**Issue by Ravbug** [emscripten-core/emscripten#19349]
The generated function for `_wgpuCreateInstance` is not complete:
```js
function _wgpuCreateInstance() {
 abort("TODO: wgpuCreateInstance unimplemented");
}
```
However, other functions (like `_wgpuInstanceRequestAdapter`) are implemented. Is it possible to use WebGPU with Emscripten?

**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.38 (9eff02bc816c50ab0e3b70a3bd5b72a8dc2893a2)`

**Comment by kripken** [comment]
I believe at least this test is known to pass:

https://github.com/emscripten-core/emscripten/blob/9677b7df77e61db0b2eb91f5c7525429968cb084/test/webgpu_basic_rendering.cpp#L4

@kainino0x would know more.

**Comment by kainino0x** [comment]
Use a nullptr instance, as in the tests and this sample: https://github.com/kainino0x/webgpu-cross-platform-demo

```cpp
    // Left as null (until supported in Emscripten)
    static const WGPUInstance instance = nullptr;
```
