### ISSUE TITLE
-sMAXIMUM_MEMORY=5GB, memory has maximum limit

### ISSUE THREAD

**Issue by wph03634** [emscripten-core/emscripten#19345]
**Version of emscripten/emsdk:**
Version: 3.1.35
Target: wasm64

**Failing command line in full:**
-sMAXIMUM_MEMORY=5GB

**JS Error:**
Uncaught RangeError: WebAssembly.Memory(): Property 'maximum': value 81920 is above the upper bound 65536

I need more memory than 4G, But memory has  maximum limit. What I have to do?

**Comment by wph03634** [comment]
> Where are you trying to run this code? Are you running under node with memory64 enabled? Can you share the full command line?

emcc test.cpp --bind -s MAIN_MODULE=1 -s MAXIMUM_MEMORY=5GB -s ALLOW_MEMORY_GROWTH=1 -s MEMORY64=2 -s WASM=1 -o test.html

**Comment by sbc100** [comment]
Is there some reason you are using `-sMEMORY64=2` ?   In this mode wasm64 operations are lowered away to wasm32 and you don't get access to a 64-bit address apace.

**Comment by wph03634** [comment]
> Is there some reason you are using `-sMEMORY64=2` ? In this mode wasm64 operations are lowered away to wasm32 and you don't get access to a 64-bit address apace.

I need more memory than 4G in my project, wasm32 does not meet needs, So I need to use wasm64. I don't know what -sMEMORY64=2 means,What should I do?

**Comment by sbc100** [comment]
`-sMEMORY64=2` is a special lower mode that doesn't actually use wasm64 at runtime.  You probably just want `-sMEMORY64` (without the =2).. although bear in mind that this is still experimental and won't work in any browser by default... its still behind a flag everywhere.

**Comment by wph03634** [comment]
I can't find all *emcc* options.   `emcc --help` incomplete information

**Comment by wph03634** [comment]
> `-sMEMORY64=2` is a special lower mode that doesn't actually use wasm64 at runtime. You probably just want `-sMEMORY64` (without the =2).. although bear in mind that this is still experimental and won't work in any browser by default... its still behind a flag everywhere.

Thank you.

**Comment by wph03634** [comment]
> > `-sMEMORY64=2` is a special lower mode that doesn't actually use wasm64 at runtime. You probably just want `-sMEMORY64` (without the =2).. although bear in mind that this is still experimental and won't work in any browser by default... its still behind a flag everywhere.

Command line:
`emcc test.cpp --bind -s MAIN_MODULE=1 -sMEMORY64 -s WASM=1 -o test.html`

JS Error:
`Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): invalid memory limits flags 0x5 (enable via --experimental-wasm-memory64) @+2035)`

There will still be errors.Currently, wasm64 is don't get access to a 64-bit address apace？/(ㄒoㄒ)/~~

**Comment by sbc100** [comment]
As I said above, memory64 has not yet been turned on by default in any browsers.  As of today its not something you can use in production because it requires a flag to enable.
