### ISSUE TITLE
Can't export gl functions in main module for dynamic linking

### ISSUE THREAD

**Issue by junyuecao** [emscripten-core/emscripten#19357]
```
 emcc -sUSE_SDL=2 -g0 -O0 -o mandelbrot.html mandelbrot.cc -sALLOW_MEMORY_GROWTH -sWASM_BIGINT -sFULL_ES2=1 -sFULL_ES3=1 -sMAIN_MODULE=2 -sEXPORTED_FUNCTIONS="[\"_main\", \"_glGenBuffers\"]"
```

error code is :
`emcc: error: undefined exported symbol: "_glGenBuffers" [-Wundefined] [-Werror]`

**Comment by sbc100** [comment]
yes, by default any side module you specify on the command line will be loaded on startup.  If you want to delay loading until `dlopen` time you can use `-sAUTOLOAD_DYLIBS=0`
