### ISSUE TITLE
Emscripten Fetch API defaults to "GET" request after explicitly setting the attr to "POST"

### ISSUE THREAD

**Issue by unix-based-system** [emscripten-core/emscripten#19399]
Hi,

After updating Emscripten from version 3.1.21 to 3.1.39 the following code no longer works (even though I did not change a single line) in the fetch function. The server (also unchanged) now throws back a 405 METHOD NOT ALLOWED error. I suspect a change in the fetch API that is causing the error as the explicitly set POST attribute seems to be ignored.

confirmed also to still work with version: 3.1.33 (so between 3.1.33 and 3.1.39 something went wrong)

```cpp
void Screen003::doFetchAsync(const std::string& controller, const json& jsonBind){
    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    strcpy(attr.requestMethod, "POST");
    attr.userData = this;
    attr.attributes = EMSCRIPTEN_FETCH_REPLACE | EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
    attr.onprogress = GLOB_PROGRESS_003_00;
    attr.onsuccess = GLOB_SUCCESS_003_00;
    attr.onerror = GLOB_FAILED_003_00;
    const char *headers[] = {"Content-Type", "application/json", nullptr};
    attr.requestHeaders = headers;

    std::string jsonDump = jsonBind.dump();
    attr.requestData = jsonDump.c_str();
    attr.requestDataSize = jsonDump.length();
    std::string fullRequest = GLOB_URL + controller;
    emscripten_fetch(&attr, fullRequest.c_str());
}
```

See the request details below (see the reverted GET method even though the server only allows POST):
![z_result](https://github.com/emscripten-core/emscripten/assets/54240100/033ad583-5256-4098-be2b-8728b4083caf)

Thanks for the help!

**Comment by kripken** [comment]
> confirmed also to still work with version: 3.1.33 (so between 3.1.33 and 3.1.39 something went wrong)

It would be good to bisect to find out the exact range of commits where this regressed. That's usually the fastest thing if there isn't an obvious reason (and I can't think of one myself, at least, and don't see anything relevant in the changelog):

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by unix-based-system** [comment]
Working on it and testing every version 1.34/35/36/37 until 3.1.38 it seems to work. Only in version 3.1.39 it breaks.

**Comment by unix-based-system** [comment]
I am very new to git bisect (not grasping the full context) but I manged to track the error down to one of the following commits:
![image](https://github.com/emscripten-core/emscripten/assets/54240100/4d21b2a2-ed41-4dbe-9d6d-4fe82204f7a9)

**Comment by kripken** [comment]
Thanks @unix-based-system !

@sbc100 The middle commit in that screenshot looks like the likely cause, #19337

**Comment by sbc100** [comment]
Could also be #19336 which changes how/when fetchAttributes is read.  Maybe it wasn't NFC after all.  Checking now.

**Comment by sbc100** [comment]
Yup, this line looks wrong:

`UTF8ToString({{{ makeGetValue('fetch_attr', C_STRUCTS.emscripten_fetch_attr_t.requestMethod, '*') }}})`   

Yup.. the requestMethod member a C array and not a pointer.
