### ISSUE TITLE
Node + MEMORY64 + MAXIMUM_MEMORY

### ISSUE THREAD

**Issue by TobiasNoell** [emscripten-core/emscripten#19455]
I'm trying to build a WASM file for node where I can allocate more than 4GB.
I am compiling with the following settings
`-s MODULARIZE=1 -s WASM=1 -s NO_EXIT_RUNTIME=1 --bind -s MAXIMUM_MEMORY=8GB -s FILESYSTEM=0 -s USE_ZLIB=1 -O3 -s MEMORY64 -s ASSERTIONS -s ALLOW_MEMORY_GROWTH=1`

It is also definitely compiled under 64 bit as I get e.g. `sizeof(size_t)` as 8.

I run my node with the `--experimental-wasm-memory64` command.
My node version is `v18.16.0`

However, I get a runtime exception:
`failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): maximum memory size (131072 pages) is larger than implementation limit (65536) @+3843`

If I set `-s MAXIMUM_MEMORY=4GB` it runs fine, but then I cannot allocate more than 4GB of memory.

What am I doing wrong here?

My emscripten version is
```
emcc -v:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.37 (d02c29f95e9e68f2f50c2b0432c56a671814d5c8)
clang version 17.0.0 (https://github.com/llvm/llvm-project 86339ef088e9aac6cf52cf9022d7a5bd144d4c42)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\cmPlatform\emsdk.git\upstream\bin
```

**Comment by TobiasNoell** [comment]
I have upgraded to the newest node version and the above error is now gone.
Instead I get the following error if I try to allocate more than 4 GB of memory:

```
RuntimeError: memory access out of bounds
    at dlmalloc (wasm://wasm/01071cde:wasm-function[3016]:0x1f795e)
    at operator new(unsigned long) (wasm://wasm/01071cde:wasm-function[4999]:0x221c90)
    at operator new[](unsigned long) (wasm://wasm/01071cde:wasm-function[5000]:0x221cc7)
```

**Comment by kripken** [comment]
I'm not sure if sanitizers work with wasm64, but it's worth trying: https://emscripten.org/docs/debugging/Sanitizers.html

This could also be a compiler or toolchain bug, as wasm64 is fairly now. If you can get a fully reproducible testcase that would be good @TobiasNoell

**Comment by TobiasNoell** [comment]
@kripken: Thanks, I will try this.

Meanwhile I have digged a bit deeper into the emscripten code.
My current assumption is that the WASM is correctly compiled in 64 bit, the target is also indicated as `wasm64-unknown-emscripten` during verbose build.

However the emscripten generated JS glue code seems to be not capable allocating more than 4GB no matter if wasm32 or wasm64 is used. This seems to be a little bit strange because for me the only reason to use wasm64 would be to allocate more than 4GB of memory.

This is also indicated by the following generated JS glue code related to my 64 bit webassembly:

Generated:
```
function getHeapMax() {
    return 4294901760 //Here emscripten returns 4GB hardcoded
}
```
Origin:
https://github.com/emscripten-core/emscripten/blob/ceb2e284a2a714d9261ccb8d8721e5f92bb3cde7/src/library.js#L129

Generated:
```
function _emscripten_resize_heap(requestedSize) {
    requestedSize = Number(requestedSize)
    var oldSize = HEAPU8.length
    requestedSize = requestedSize >>> 0 //Here emscripten cast the requested memory size to 32 Bit
```
Origin:
https://github.com/emscripten-core/emscripten/blob/ceb2e284a2a714d9261ccb8d8721e5f92bb3cde7/src/library.js#L197

**Comment by kripken** [comment]
@TobiasNoell Those look like bugs in the current code, things that need to be modified to fully support wasm64. We probably just need ifdefs in those places.

cc @sbc100 who has been working on wasm64.

**Comment by kripken** [comment]
@sbc100 - I guess we don't have actual tests allocating over 4GB, maybe for CI reasons? Have we tested locally?

**Comment by sbc100** [comment]
I think we may not :(   Something we should for sure add, but we have been focused on feature parity with wasm32 thus far.

**Comment by kripken** [comment]
@TobiasNoell #19475 should have fixed those issues, please test your project again with that (`./emsdk install tot` would get that code).

**Comment by TobiasNoell** [comment]
@kripken: Very cool! Will do this ASAP and report back!

**Comment by TobiasNoell** [comment]
I tried it, but unfortunately it is not working (but getting a new error message now)

```
emscripten_realloc_buffer: Attempted to grow heap from 16777216 bytes to 4295229440 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
emscripten_realloc_buffer: Attempted to grow heap from 16777216 bytes to 4295229440 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
Failed to grow the heap from 16777216 bytes to 4295229440 bytes, not enough memory!
```

**Comment by sbc100** [comment]
I think there is currently an issue with WebAssembly.Memory.grow() not being able to grow memory over 4Gb..

Also HEAPU8 can't currently view the entire memory if it was to grow over GB:  https://bugs.chromium.org/p/v8/issues/detail?id=4153

In other words, the support for actual memories larger than 4Gb is not there yet, but we are working on it.

**Comment by sbc100** [comment]
I created a tracking issue for accessing > 4Gb memories: https://github.com/emscripten-core/emscripten/issues/19512.

Maybe we can close this one given that the original issue is now fixed?

**Comment by TobiasNoell** [comment]
Ok, would be fine for me
