### ISSUE TITLE
-sUSE_PTHREADS is simultaneously required and deprecated

### ISSUE THREAD

**Issue by dhdaines** [emscripten-core/emscripten#19471]
Hi, I don't use `-sUSE_PTHREADS` anywhere in my configuration, yet `emcc` 3.1.39 crashes my build because it expects it to be defined somewhere.

If I define it, I don't just get a warning (as per the changelog) but actually failure, unless I also disable `-sUSE_STRICT`.  According to the documentation:

> The -sUSE_PTHREADS setting still works but is marked as legacy and will generate a warning in -sSTRICT mode.

This is false.  It generates a warning without `-sSTRICT` but actually fails with it.

My linker options are (were):

```
-Oz
-sFILESYSTEM=0
-sALLOW_MEMORY_GROWTH=1
-sINITIAL_MEMORY=33554432
-sSUPPORT_BIG_ENDIAN=1
-sSTRICT=1
-sSTRICT_JS=0
-sSUPPORT_LONGJMP=0
--memory-init-file=0
-sENVIRONMENT=web
-sWASM=0
```

Here is the error:

```
Traceback (most recent call last):
  File "/home/dhd/work/emsdk/upstream/emscripten/emcc.py", line 4398, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/dhd/work/emsdk/upstream/emscripten/emcc.py", line 4391, in main
    ret = run(args)
  File "/home/dhd/work/emsdk/upstream/emscripten/emcc.py", line 1336, in run
    phase_post_link(options, state, wasm_target, wasm_target, target, js_syms)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/dhd/work/emsdk/upstream/emscripten/emcc.py", line 3115, in phase_post_link
    phase_binaryen(target, options, wasm_target)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/dhd/work/emsdk/upstream/emscripten/emcc.py", line 3761, in phase_binaryen
    wasm2js = building.wasm2js(wasm2js_template,
  File "/home/dhd/work/emsdk/upstream/emscripten/tools/building.py", line 891, in wasm2js
    if not debug_info and not settings.USE_PTHREADS:
  File "/home/dhd/work/emsdk/upstream/emscripten/tools/settings.py", line 184, in __getattr__
    raise AttributeError(f"no such setting: '{attr}'")
AttributeError: no such setting: 'USE_PTHREADS'
ninja: build stopped: subcommand failed.

```

Please include the following in your bug report:

**Version of emscripten/emsdk:**

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.39 (36f871819b566281d160470a1ec4515f379e9f77)
clang version 17.0.0 (https://github.com/llvm/llvm-project c672c3fe05adbb590abc99da39143b55ad510538)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/dhd/work/emsdk/upstream/bin

```

**Failing command line in full:**

see above

**Comment by dhdaines** [comment]
Seems like the offending option here is `-sWASM=0`.  Probably pretty easy to fix!

**Comment by sbc100** [comment]
I think this is due a combination of `-sWASM=0` and `-sSTRICT=1`.   

We do have a pretty huge test suite which should prevent this kind of breaking in most cases, but testing every possible combination of settings is hard.   In order to improve things we are constantly looking ways to pair down the number of settings (and/or valid combinations or settings) while also growing our test suite.

**Comment by sbc100** [comment]
Actually it looks like `-sWASM=0` + `-STRICT` + `-O2` (or above) is needed to repro.  Working on a fix now.

**Comment by dhdaines** [comment]
Thanks!  I erased my snarky original comment, sorry about that, I realize it isn't easy to test everything...

**Comment by sbc100** [comment]
> Thanks! I erased my snarky original comment, sorry about that, I realize it isn't easy to test everything...

Thanks for being understanding.. I can also understand your frustration when a version upgrade breaks your project!
