### ISSUE TITLE
Fetch api: incomplete response headers

### ISSUE THREAD

**Issue by dapeipa** [emscripten-core/emscripten#19523]
I have the following code that sends a GET request and prints the result and headers.

```c++
#include <emscripten.h>
#include <emscripten/fetch.h>
#include <iostream>

void download_succeeded(emscripten_fetch_t *fetch) {
  std::cout << "Finished downloading " << fetch->url
            << ", response data:\n" << fetch->data << std::endl;

  size_t headersLength = emscripten_fetch_get_response_headers_length(fetch);
  char* headersBuffer = new char[headersLength + 1];
  emscripten_fetch_get_response_headers(fetch, headersBuffer, headersLength + 1);

  std::string headersString(headersBuffer);   
  std::cout << "Headers length:" << headersLength << " -> " << headersString << std::endl;
  emscripten_fetch_close(fetch);
}

void download_failed(emscripten_fetch_t *fetch) {
  std::cout << "Downloading " << fetch->url
            << " failed, HTTP status: " << fetch->status << std::endl;
  emscripten_fetch_close(fetch);
}

int main() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);
  strcpy(attr.requestMethod, "GET");
  attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
  attr.onsuccess = download_succeeded;
  attr.onerror = download_failed;

  emscripten_fetch(&attr, "https://jsonplaceholder.typicode.com/todos/2");
  return 0;
}
```

The response data is correct but the response headers are not retrieved complete (only a part).
This is what is printed in the browser console:

`Finished downloading https://jsonplaceholder.typicode.com/todos/2, response data:`
`{`
`"userId": 1,`
`"id": 2,`
`"title": "quis ut nam facilis et officia qui",`
`"completed": false`
`}>ٛ`
`Headers length:109 -> cache-control: max-age=43200`
`content-type: application/json; charset=utf-8`
`expires: -1`
`pragma: no-cache`

And these are the full response headers (obtained with curl. The browser in Developer Tools->Network also gets the same headers as curl).

```
$ curl -i -X GET "https://jsonplaceholder.typicode.com/todos/2"
```

`HTTP/2 200` 
`date: Sun, 04 Jun 2023 09:13:10 GMT`
`content-type: application/json; charset=utf-8`
`content-length: 99`
`x-powered-by: Express`
`x-ratelimit-limit: 1000`
`x-ratelimit-remaining: 999`
`x-ratelimit-reset: 1685868021`
`vary: Origin, Accept-Encoding`
`access-control-allow-credentials: true`
`cache-control: max-age=43200`
`pragma: no-cache`
`expires: -1`
`x-content-type-options: nosniff`
`etag: W/"63-+s0zIP5ZEQN9hypVJUneLybJ+L0"`
`via: 1.1 vegur`
`cf-cache-status: HIT`
`age: 1999`
`accept-ranges: bytes`
`report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=GXOf%2BnCTNA9f9vtiDm4cm%2BXHt7CWJthED%2FNpK6l3K51snQd3FN%2BVm4xpAbOGnnTSO7Ri1j9lHV19qzBs%2BCkgV%2BykeY6dfF3vdSGIv2wZFRYvxEl%2BrEGHajCb4p8UPM6HmvtqUjrw6NW0XuAdVyJWD%2FozthZ8EHL2Lxo%3D"}],"group":"cf-nel","max_age":604800}`
`nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}`
`server: cloudflare`
`cf-ray: 7d1f0eef6f1586cc-MAD`

`{`
  `"userId": 1,`
  `"id": 2,`
  `"title": "quis ut nam facilis et officia qui",`
  `"completed": false`
`}`

Why don't the emscripten_fetch_get_response_headers_length and emscripten_fetch_get_response_headers functions retrieve the full response headers?

emcc --version                                                      
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35-git (a90c5abb489c516f59c0d16864d953d4bedd37da)

**Comment by sbc100** [comment]
The fetch API reports the result of the `getAllResponseHeaders()` method on the XHR object: https://github.com/emscripten-core/emscripten/blob/accfb24329f87f0354e561510ce2c6f0f1b1e1af/src/Fetch.js#L572

I confirmed that this method only returns a subset of all the headers.    In this case just:

```
cache-control: max-age=43200
content-type: application/json; charset=utf-8
expires: -1
pragma: no-cache
```

I guess this is a limitation of the XMLHttpRequest?  Perhaps somebody else knows more?

**Comment by sbc100** [comment]
Ah, I think I found that answer: https://stackoverflow.com/questions/8945587/xmlhttprequest-getallresponseheaders-not-returning-all-the-headers.

If you want all header your server would need to add `Access-Control-Expose-Headers` to the response.

**Comment by dapeipa** [comment]
Thank you, it works like a charm.
