### ISSUE TITLE
How to reset emscripten to it's original state

### ISSUE THREAD

**Issue by sadasant** [emscripten-core/emscripten#1956]
After I run some scripts, it says "cannot enlarge memory arrays", but programs work if I run them separately and with a refresh in between, is there a way to reset Emscripten to it's original state without refreshing the website?

Thank you so much for your time and effort.

**Comment by DimaN-RuSlan** [comment]
Is there a way to handle OOM error inside C++ app?
e.g. if  new operator would return NULL, I could free all memory allocated in last high-level operation that run OOM, report that but allow user to choose another operation (or same operation with another smaller data).
Thank you.

**Comment by juj** [comment]
In the current Emscripten incoming, there is the new linker option `-s ABORTING_MALLOC=0` that you can set up to have malloc fail. I hope that should translate to a `throw` for `operator new`, but that might currently be untested. In either case, see #3822 for that discussion.
