### ISSUE TITLE
Possibility of restoring a pure link time disable-exception-catching feature?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#19585]
Something we have now found out to happen with migration from fastcomp days to the wasm backend is that DISABLE_EXCEPTION_CATCHING has moved from being a link-time variable into a compile+link variable.

That is, in the old fastcomp days, catch() statements were stripped away by `-sDISABLE_EXCEPTION_CATCHING` at the final asm.js->wasm conversion stage, and one only needed to specify the flag during the final link.

Now with the LLVM backend and wasm object files, `-sDISABLE_EXCEPTION_CATCHING` is then naturally a compile+link stage item.

So the straightforward way would be, if we wanted to support both exception catching enabled + disabled builds, to ship two sets of precompiled object files, with `-sDISABLE_EXCEPTION_CATCHING` on and off, to our users, and then choose the appropriate set when compiling+linking our game engine code against the user's game project code.

Though we find that we cannot actually afford to do that, since it would double the configuration permutation space of object code we would have to ship, and we are already handling a lot of other config permutations, so this is not feasible.

But in the fastcomp days, we enjoyed a nice ~-10% code size reduction when exception catching was disabled. So the regression is noticeable.

That makes me wonder - would it be possible to implement an Emscripten/Binaryen link time pass to remove exception catching, so that the old style postprocessing-like model could be used to disable exception catching from a whole Wasm Module? This would help our code size noticeably.

**Comment by sbc100** [comment]
We do have binaryen passes for lowering away various other wasm features, so this one seems reasonable to add.  

However, remember that requiring this lower pass forces us to run binaryen as part of this link.  In release builds we always do this anyway so that is not a problem, but for debug build its sometimes advantageous to avoid running binaryen at all.   The two main advantages being link times, and debug info preservation.  We even added an option (`-sERROR_ON_WASM_CHANGES_AFTER_LINK`) to allow folks to explicitly error in binaryen was needed at link time.

If for users want to enable exceptions in debug builds, or are willing to pay the extra costs or the lowering pass then I think it seems reasonable to add.

**Comment by sbc100** [comment]
Oh, wait, are we talking about wasm EH, or emscripten EH?  I'm not sure binaryen can lower away emscripten EH as easily since more of it is in userspace.

**Comment by juj** [comment]
The original situation was with Emscripten EH, but we are in the process of migrating to Wasm EH, so a solution that worked in Wasm EH would be wholly suitable as well.

The Wasm changes after link setup sounds good. We would have a scenario where developers who do opt in to removing exceptions, they could disable that option while iterating to get fastest iteration times.

**Comment by sbc100** [comment]
@aheejin (for EH knowledge) @azakai (who has written lowering passes in the past)

**Comment by kripken** [comment]
I worry about regressions from doing it this way. Having exceptions enabled may prevent various LLVM optimizations from control flow transformations to inlining. After removing try-catch perhaps Binaryen can regain some of that, but I have no idea how much (possibly most, possibly little).

@juj is the on-demand building of Emscripten libraries not helpful for you? I mean, `emcc` will automatically build say pthreads+exceptions+etc as actually needed by the user, and hopefully each user really only needs one or two such configurations. The downside is the first build, but maybe you can mitigate that in other ways, like starting the build in the background when the project is loaded (when you can read the project data to see which flags will be used)?

**Comment by kripken** [comment]
Oh, I see... and you don't want to build all of Unity itself on the user's machine. Makes sense.

I think removing removing try-catch in Binaryen seems feasible to do, my only concern is possible regressions. But maybe I'm worried too much.

**Comment by aheejin** [comment]
Lowering in Binaryen is possible, but can you use `-fignore-exceptions` in Clang? Unlike `-fno-exceptions`, it allows `throw`s and `try`-`catch`es in the code but just lowers away all the `catch` part and crashes when an exception is thrown.

**Comment by aheejin** [comment]
Oh, compile time options don't work for you.. Yeah `-fignore-exceptions` is a compile time option in Clang.
