### ISSUE TITLE
Undefined symbols when including <emscripten/webaudio.h>

### ISSUE THREAD

**Issue by vicente-azorin** [emscripten-core/emscripten#19589]
Hello, 

I am running into issues when trying to work with the new Wasm Audio Worklets API.  

I am attempting to compile test/webaudio/audioworklet.c

Emscripten version: 3.1.41

Undefined symbols:
wasm-ld: error: CMakeFiles/SDKWASM.dir/src/WASM/WASMMain.c.o: undefined symbol: emscripten_create_wasm_audio_worklet_node
wasm-ld: error: CMakeFiles/SDKWASM.dir/src/WASM/WASMMain.c.o: undefined symbol: emscripten_create_wasm_audio_worklet_processor_async
wasm-ld: error: CMakeFiles/SDKWASM.dir/src/WASM/WASMMain.c.o: undefined symbol: emscripten_create_audio_context
wasm-ld: error: CMakeFiles/SDKWASM.dir/src/WASM/WASMMain.c.o: undefined symbol: emscripten_start_wasm_audio_worklet_thread_async

**Comment by sbc100** [comment]
Wjhen reporting bugs like this can you share your full link command?

Are you linking with `-sAUDIO_WORKLET` ?

**Comment by vicente-azorin** [comment]
I wasn't linking with `-sAUDIO_WORKLET`... now it works, thank you!
