### ISSUE TITLE
Failing to create audio worklet using emscripten_start_wasm_audio_worklet_thread_async

### ISSUE THREAD

**Issue by vicente-azorin** [emscripten-core/emscripten#19603]
Hello again, 

I am trying to run some simple code based on one of your examples in the Wasm Audio Worklets API (test/webaudio/audioworklet.c).  I am building with the following link options:
```
-pthread
-sUSE_PTHREADS 
-sPTHREAD_POOL_SIZE=150 
-sALLOW_MEMORY_GROWTH
-sASSERTIONS=2
-sLLD_REPORT_UNDEFINED
-sFORCE_FILESYSTEM
-sTOTAL_MEMORY=700448768
-g
-sWASM_WORKERS=1
-sAUDIO_WORKLET=1
-sEXPORTED_FUNCTIONS=_initWasmAudio,_initWasmAudioThread,_createWasmAudioProcessor,...
-sEXPORTED_RUNTIME_METHODS=ccall,cwrap
-sSAFE_HEAP=1
-sDEMANGLE_SUPPORT=1
-sWEBAUDIO_DEBUG=2
```

I am using Emscripten version: 3.1.41

Here is the C code:

[WASMMain.c.txt](https://github.com/emscripten-core/emscripten/files/11736924/WASMMain.c.txt)

In the html code, I import the main js file for my module and then use buttons to test each step:

```
  <script src="WASM.js"></script>

  <script>
    document.getElementById('initButton').addEventListener('click', () => {
      Module.ccall("initWasmAudio");
    });
    document.getElementById('initThreadButton').addEventListener('click', () => {
      Module.ccall("initWasmAudioThread");
    });
    document.getElementById('createButton').addEventListener('click', () => {
      Module.ccall("createWasmAudioProcessor");
    });
  </script>
```

The output I get when I press the first button (run initWasmAudio):
```
INIT WASM AUDIO CONTEXT
(index):30 Creating new WebAudio context with parameters:
SDKWASM.js:4899 ObjectlatencyHint: "interactive"sampleRate: 48000[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(index):30 Registered new WebAudio object [object AudioContext] with ID 1
(index):30 Context state: 
(index):30 RUNNING
```

But when I press the second button (run initWasmAudioThread), I get:

```
emscripten_start_wasm_audio_worklet_thread_async() adding audioworklet.js...
WASM.js:5082  emscripten_start_wasm_audio_worklet_thread_async() addModule() failed!
audioWorkletCreationFailed @ WASM.js:5082
Promise.catch (async)
_emscripten_start_wasm_audio_worklet_thread_async @ WASM.js:5109
$initWasmAudioThread @ WASM.wasm:0x1fb4af
(anonymous) @ WASM.js:705
ccall @ WASM.js:5635
(anonymous) @ (index):50
(index):30 CALL CREATE WASM PROCESSOR
```

The debug output states "adding audioworklet.js..." before failing with "addModule() failed!", not sure if this is relevant but I tried embedding a valid audioworklet.js file using the link option `--embed_file=audioworklet.js` with no luck.

Any chance you could shed some light into what I'm doing wrong here?

**Comment by juj** [comment]
Built the test code with

```
emcc wasmmain.c -pthread -sPTHREAD_POOL_SIZE=2  -sALLOW_MEMORY_GROWTH -sASSERTIONS=2 -sLLD_REPORT_UNDEFINED -sFORCE_FILESYSTEM -sTOTAL_MEMORY=700448768 -g -sWASM_WORKERS=1 -sAUDIO_WORKLET=1 -sEXPORTED_FUNCTIONS=_initWasmAudio,_initWasmAudioThread,_createWasmAudioProcessor -sEXPORTED_RUNTIME_METHODS=ccall,cwrap -sSAFE_HEAP=1 -sDEMANGLE_SUPPORT=1 -sWEBAUDIO_DEBUG=0 -o wasmmain.html
```
Notable differences are that there is no need to pass `-sUSE_PTHREADS` in addition to `-pthread`. Also I would not recommend `-sPTHREAD_POOL_SIZE=150`, that will make the page load hang for a long time.

Here is the result I get

![image](https://github.com/emscripten-core/emscripten/assets/225351/1dcd83d7-4251-48b3-9a4d-1f06f3abb598)

pressing the Toggle playback button does work in my test, and I get a sine wave playing back.

Added a new debug print in the above PR, maybe that might help catch an error.

**Comment by vicente-azorin** [comment]
It turns out the answer to the problem was quite trivial... I am building the code via CMake, where I have an install step as follows:

```
install(FILES
  $<TARGET_FILE_DIR:${WASM_TARGET}>/${WASM_TARGET}.js
  $<TARGET_FILE_DIR:${WASM_TARGET}>/${WASM_TARGET}.worker.js
  $<TARGET_FILE_DIR:${WASM_TARGET}>/${WASM_TARGET}.wasm
  ${CMAKE_CURRENT_SOURCE_DIR}/web/index.html
  DESTINATION ${WASM_LIB_INSTALL_DIR}
  COMPONENT wasmLibs
)
```

I wrote this before enabling AUDIO_WORKLET, when there were only two .js files and a .wasm file being generated.  Once I added the following files to the install step everything worked:
```
  $<TARGET_FILE_DIR:${WASM_TARGET}>/${WASM_TARGET}.aw.js
  $<TARGET_FILE_DIR:${WASM_TARGET}>/${WASM_TARGET}.ww.js
```

Your PR provided the hint for this: `{{{ TARGET_BASENAME }}}.aw.js`

@juj, thank you for trying the code out and providing such an in-depth response, it's much appreciated!

**Comment by juj** [comment]
Sounds great, awesome to see Audio Worklets see being utilized 👍
