### ISSUE TITLE
reinterpret_cast  between <void*> AND <uint64> maybe NOT  work well  

### ISSUE THREAD

**Issue by navegador5** [emscripten-core/emscripten#19647]
**LINUX VERSION**

Linux dev 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**EMCC VERSION**:
 em++ -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 ()
Ubuntu clang version 13.0.1-2ubuntu2.1
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/bin

cpp code sample:

```
        // in one included file :  i changed the page size  
            
             int r = posix_memalign(&p, huge_page_size, sz);
                 madvise(p, sz, MADV_HUGEPAGE);
      
  
         // in main function      

         std::cout << std::boolalpha;
         std::cout << "Data is_standard_layout:" << std::is_standard_layout<Data>::value << "\n";
         std::cout << "sizeof(Data):"            << sizeof(Data) << "\n";

         // #LINE0 
         printf("forest-calc: %p\n",reinterpret_cast<void*>(reinterpret_cast<uint64_t>(forest) + sizeof(ID) * (mcnt+1) *7  + (8)*(mcnt+1)));
        
         //  the get_data_ary is similiar to the prev line(#LINE0) ,  it just cast uint64_t  to void*
         printf("forest:        %p\n",get_data_ary<Data>(forest)); 
                
                                                                                                  
         assert(
              reinterpret_cast<void*>(
                  reinterpret_cast<uint64_t>(forest) + sizeof(ID) * (mcnt+1) *7  + (8)*(mcnt+1)
              ) == get_data_ary<Data>(forest)
         );
```

**IN C++ , it worked:**

**_g++ small-mem.cc -O3 -std=c++20 -o small-65536_**
./small-65536

Data is_standard_layout:true
sizeof(Data):16
forest-calc: 【0x7f2880240024】          // the output is 【same】 
forest:        【0x7f2880240024】         // the output is   【same】

**WHEN I translate it TO emcc-wasm:**
 
**_em++ -std=c++20 ../small-mem.cc -msse4.2 -msimd128 -s WASM=1 -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=1 --bind -o nvcsp.html_**

forest-calc:【 0x40240024】               //------------【DIFFERENT】
forest:        【0x40200020】                //------------【DIFFERENT】

nvcsp.js:1511 Uncaught RuntimeError: Aborted(Assertion failed: reinterpret_cast<void*>( reinterpret_cast<uint64_t>(forest) + sizeof(ID) * (mcnt+1) *7 + (8)*(mcnt+1) ) == get_data_ary<Data>(forest), at: ../small-mem.cc,430,main)
    at abort (nvcsp.js:1511:11)
    at ___assert_fail (nvcsp.js:1836:7)
    at 000b375e:0x5006
    at 000b375e:0x24544
    at nvcsp.js:1556:22
    at callMain (nvcsp.js:5637:15)
    at doRun (nvcsp.js:5694:23)
    at nvcsp.js:5705:7

-------------------------------------------------------------------------------------------------------------------------------------

**Comment by sbc100** [comment]
I think this is because sizeof(void*) is 4 under WebAssembly (unless you build with -sMEMORY64).   wasm32 is an ILP32 platform which mean `int`, `long` and pointers are all 32-bits.   If you add `-m32` to your desktop build to target x86 you will most likely see the same result as with wasm.

**Comment by navegador5** [comment]
thanks.
