### ISSUE TITLE
Export the suspender global on Module when using JSPI?

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#19652]
Without the JSPI, it is possible to use JS trampolines internal to a library and keep this as an implementation detail. With the JSPI, this is not possible since the suspending call will trap if a JS call frame is on the suspender's stack. I think to fix this, the binaryen pass at least needs to be altered to import the suspender global. Then Emscripten can make the `suspenderGlobal` in JavaScript and export it on `Module`.

It would also be helpful if we could have two wrapper functions:
* `suspending_wrapper` which takes a JS function and a signature and creates a `WebAssembly.Function` wrapper with `suspending: "first"` and then makes a wasm adaptor that satisfies the suspender argument from `suspenderGlobal`.
* `promising_wrapper` which takes a Wasm function and creates another wasm wrapper with an extra extern argument and then wraps it with `promising: true`.

These are runtime versions of `makeWrapperForImport` and `makeWrapperForExport` from the JSPI binaryen pass.

**Comment by brendandahl** [comment]
I'm not sure I follow why this is needed with JSPI. Do you have any examples of your trampolines?

**Comment by hoodmane** [comment]
Yeah there's a few examples:
* a trampoline to call a function pointer that might have the incorrect number of arguments (I can't use `call_indirect` if I don't know how many arguments the function takes, but I can use a webassembly trampoline:
```C
EM_JS(void*, trampoline, (FuncType fptr, int arg1, int arg2, int arg3, int arg4), {
   return wasmTableMirror[fptr](arg1, arg2, arg3, arg4);
})
```
* the invoke trampolines for JS exception handling
* the JS trampolines in libffi: https://github.com/libffi/libffi/blob/master/src/wasm32/ffi.c#L424

**Comment by hoodmane** [comment]
Okay I tried it out with the following code:
```Cpp
#include <iostream>
#include <emscripten.h>

using namespace std;

EM_ASYNC_JS(int, async_func, (), {
  await new Promise(res => setTimeout(res, 1000));
  return 5;
});

int main () {
  try
  {
    int x = async_func();
    cout << "got: " << x << '\n';
    throw 20;
  }
  catch (int e)
  {
    cout << "An exception occurred. Exception Nr. " << e << '\n';
  }
  return 0;
}
```
If I compile with:
```sh
emcc -c test.cpp -fwasm-exceptions
emcc test.o -o test.js -sASYNCIFY=2 -fwasm-exceptions
node --experimental-wasm-stack-switching test.js 
```
then it prints:
```
got: 5
An exception occurred. Exception Nr. 20
```
exactly as expected.
If instead I compile with:
```sh
emcc -c test.cpp -fexceptions
emcc test.o -o test.js -sASYNCIFY=2 -fexceptions
node --experimental-wasm-stack-switching test.js 
```
it says:
```
Aborted(Assertion failed: Missing __sig for invoke_diii)
```
is this an intended limitation that `-sASYNCIFY=2` doesn't work with `-fexceptions`? Maybe there should be a warning or something?

**Comment by hoodmane** [comment]
Probably I should open a separate issue about this.

**Comment by hoodmane** [comment]
Opened #19672.

**Comment by brendandahl** [comment]
Closing this as the JSPI API has changed quite a bit since this and there is no longer a global suspender.
