### ISSUE TITLE
[Feature request] emrun with gzip

### ISSUE THREAD

**Issue by FrostKiwi** [emscripten-core/emscripten#19680]
This is a low priority QoL improvement for analyzing how your WASM up deals with data after compression.

I was planing on compressing assets before including it, but was pleasantly surprised to see how effective gzip compresses data, especially fonts and shaders, shipped via `-embed-file` and `--preload-file`.
![image](https://github.com/emscripten-core/emscripten/assets/60887273/210b1337-0d3c-4c39-a9f0-eaa407340f23)
It would be very useful to see that compression ratio in the developer tools when running emrun as well. However, emrun doesn't do gzip compression, so you don't actually know how well your assets compress when doing emrun.

Nothing prevents one from running an own local http server with gzip turned on, but having emrun do it by itself would be a nice QoL improvement.

**Comment by sbc100** [comment]
Can you maybe just run gzip on your wasm file before running emrun?   Or is there more too it than that?    It seems to me that the job of emrun is to serve the project rather than modify it so maybe it would make sense to add this extra complexity.

**Comment by FrostKiwi** [comment]
Ohh, totally can do that as well. Guess I didn't completely think this through...
