### ISSUE TITLE
gmtime is still 32 bit (wrapping to 1900 after 2038)

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [emscripten-core/emscripten#19694]
Parts of the time.h / ctime API still don't support 64 bit time, as demonstrated by the following snippet:

```
#include <iostream>
#include <ctime>

int main () {
	struct tm tm;
	memset (&tm, 0, sizeof (tm));
	tm.tm_mon = 1;
	tm.tm_mday = 2;
	tm.tm_hour = 3;
	tm.tm_min = 4;
	tm.tm_sec = 5;
	tm.tm_isdst = -1;
	tm.tm_zone = "UTC";

	for (int year :  { 2035, 2040 }) {
		tm.tm_year = year - 1900;
		
		time_t timeVal = timegm (&tm);

		struct tm* ptm = gmtime (&timeVal);
		if (ptm) {
			std::cout << ptm->tm_year + 1900 << " should equal " << year << std::endl;
		}
	}	
}
```

It prints
> 2035 should equal 2035
> 1903 should equal 2040

Related:
https://github.com/emscripten-core/emscripten/issues/17393, https://github.com/emscripten-core/emscripten/pull/17401, https://github.com/emscripten-core/emscripten/pull/17471

I understand the reasons behind this with JS Number being less than 64 bit, but I still think it's a bug.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.34 (57b21b8fdcbe3ebb523178b79465254668eab408)
clang version 17.0.0 (https://github.com/llvm/llvm-project a031f72187ce495b9faa4ccf99b1e901a3872f4b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/SSD/git/emsdk/upstream/bin
```
But I believe the bug is present in latest too.

**Comment by sbc100** [comment]
JS Number can hold up to 53bits, so that should be plenty.

Any idea where the remaining bug lies.. it not in the definition of time_t..

**Comment by sbc100** [comment]
I found the source of the problem: https://github.com/emscripten-core/emscripten/blob/eab65a007b401f231b38b8635f24646c5617cddc/system/lib/libc/emscripten_internal.h#L38-L43

I wonder if this is actually urgent to fix?  i.e. does real world code care about this today?    Fixing would likely involve a slight code size bump for all users.

**Comment by sbc100** [comment]
The reason I ask is that in a few months when we have wasm-bigint enabled by default this should be trivial to fix.

**Comment by kripken** [comment]
Good find. Sgtm to wait for WASM_BIGINT by default - that will surely happen before 2038! :rofl:

**Comment by sbc100** [comment]
Actually it looks like we can fix without regressing code size for most programs..
