### ISSUE TITLE
I believe `EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD` is broken and has been for a long time.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#19690]
IIUC the idea behind `EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD` is that a thread
can register for DOM events (which always happen on the main thread) but then receive
those events on an separate application thread.

The mechanism by which this works relies on `PThread.currentProxiedOperationCallerThread`
being set at the time when `getTargetThreadForEventCallback` is called.   But as far as I can
tell `PThread.currentProxiedOperationCallerThread` is only ever set when messages are
received from background threads during `postMessage`.

All the of event registration function such as `emscripten_set_keydown_callback` can
arrive without going vis postMessage.   They use bottom out in `do_dispatch_to_thread`
which calls `_do_call` with `EM_PROXIED_JS_FUNCTION`.

In order to make this work correctly again we would need to attached the calling thread
somehow when calling `do_dispatch_to_thread`.

**Comment by sbc100** [comment]
@tlively .. I'm not sure if this maybe stopped working when we switch to the new proxying system?

**Comment by tlively** [comment]
Ah yes, sounds like this would have stopped working when we started using `Atomics.waitAsync` instead of `postMessage` for most of our proxying.
