### ISSUE TITLE
The Header file "source_location" of the c++20 standard is missing

### ISSUE THREAD

**Issue by w4454962** [emscripten-core/emscripten#19706]
When using emcc, the "- std=c++20" flag is added, but when referencing this Header file, the compiler will prompt that it cannot be used,

error: src\main.cpp:1:10: fatal error: 'source_location' file not found
#include <source_location>
^~~~~~~~~~~~~~~~~
1 error generated.

**Comment by sbc100** [comment]
It looks like it was added fairly recently in #19515

See https://github.com/emscripten-core/emscripten/blob/main/system/lib/libcxx/include/source_location.

That change first appeared in 3.1.41 .. are you using 3.1.41 or above?

**Comment by w4454962** [comment]
Okay, I am using the version from a month ago. I just updated it and it is now working properly.
