### ISSUE TITLE
[Question] Using FS API inside pthread

### ISSUE THREAD

**Issue by guthriec** [emscripten-core/emscripten#19715]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)

**Full link command and output with `-v` appended:**
```
I'm compiling using Bazel.

EMSCRIPTEN_LINKOPTS = [
    "--bind",  # Compiles the source code using the Embind bindings to connect C/C++ and JavaScript
    #"-lidbfs.js",
    "-s MALLOC=emmalloc",  # Switch to using the much smaller implementation
    "-s EXPORT_ES6=1",
    "-s MODULARIZE=1",  # Allows us to manually invoke the initialization of wasm
    "-s WASM_BIGINT=1",  # We need to pass int64_t
    "-s USE_ES6_IMPORT_META=0",
    "-s ENVIRONMENT='web,worker'",
    "-s NO_DYNAMIC_EXECUTION=1",
    "-s PTHREAD_POOL_SIZE=20",
    "-s NO_DISABLE_EXCEPTION_CATCHING=1",
    "-sALLOW_MEMORY_GROWTH",
    "-sPTHREADS_DEBUG",
    "-fexceptions",
    "-fsanitize=address",
]
```

My code looks like:
```
std::thread thread([this] {
   ...
  printf("before file open...\n");
  std::ofstream output_stream("my_file.bin", std::ios::binary);
  printf("after file open...\n");
   ...
});
thread.detach();
```

And it runs in the browser. The "before file open" message appears in the console, but not "after file open" message. Instead, I see messages like: 
<img width="714" alt="Screenshot 2023-06-26 at 8 58 58 AM" src="https://github.com/emscripten-core/emscripten/assets/1740665/8bf29c5c-c51f-4a79-ae18-bbdb304345bf">

The app runs without errors if I don't try to go to a different thread.

Any thoughts?

**Comment by sbc100** [comment]
When the main thread of the program return/exits, the default behaviour is to exit the entire application, killing all child threads.

If you want to your child thread to run to completion you need to either wait for it (using `thread.join`) or keep the main runtime alive (for example, by calling `emscripten_exit_with_live_runtime`.

**Comment by guthriec** [comment]
Thank you! Setting `noExitRuntime: true` helped.
