### ISSUE TITLE
`llvm-cxxfilt` doesn't work for symbols containing `$` 

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#19734]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/emsdk/upstream/bin

I am writing a script which needs demangling of all linkage names found in the output of `llvm-dwarfdump`. I thought of using `llvm-cxxfilt` for demangling but it looks like it is not able to demangle some symbols which has `$` in their names. Example: 
```sh
> llvm-cxxfilt -n _ZNKSt3__210__function6__funcIN2t53$_0ENS_9allocatorIS3_EEFvRN5boost8optionalINS2_13memory_detail14memory_contextEEEEE7__cloneEv

> _ZNKSt3__210__function6__funcIN2t53
```

Is this the correct demangling tool to use? Or emscripten has something else for this purpose?

**Comment by sbc100** [comment]
It looks like your shell is interpreting the $ as the start of an environment variable.  You can use single quotes in back to tell not to do this.. or you can use double quotes and backslash to escape the dollar sign.

```
$ llvm-cxxfilt -n '_ZNKSt3__210__function6__funcIN2t53$_0ENS_9allocatorIS3_EEFvRN5boost8optionalINS2_13memory_detail14memory_contextEEEEE7__cloneEv'
std::__2::__function::__func<t5::$_0, std::__2::allocator<t5::$_0>, void (boost::optional<t5::memory_detail::memory_context>&)>::__clone() const
$ llvm-cxxfilt -n "_ZNKSt3__210__function6__funcIN2t53\$_0ENS_9allocatorIS3_EEFvRN5boost8optionalINS2_13memory_detail14memory_contextEEEEE7__cloneEv"
std::__2::__function::__func<t5::$_0, std::__2::allocator<t5::$_0>, void (boost::optional<t5::memory_detail::memory_context>&)>::__clone() const
```

**Comment by ravisumit33** [comment]
Got it. Thanks 👍
