### ISSUE TITLE
sqlite3 SELECT performance is far worse than native.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#1977]
Sqlite3 is being used in one game project that I'm benchmarking, and I notice that it is giving very slow performance when compiled. I wrote a benchmark for that, which is available at

https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/sqlite_benchmark.zip

Unzip, and go to project directory and run:

native:
1. `mkdir native_build`
2. `cd native_build`
3. `cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..`
4. `make VERBOSE=1`
5. `./test_sqlite3_no_outlining`

emcc:
1. `mkdir emcc_build`
2. `cd emcc_build`
3. `emconfigure cmake -DCMAKE_BUILD_TYPE=Release ..`
4. `make VERBOSE=1`
5. Run `test_sqlite3_no_outlining.html` and `test_sqlite3_with_outlining.html` in browser.

The results I get:
- native Win32 exe: `Selecting statements took 38.000000 msecs. result: 2970`
- emcc no outlining: `Selecting statements took 346.901948 msecs. result: 2970`
- emcc with outlining limit set to 90000: `Selecting statements took 487.277541 msecs. result: 2970` 
- emcc with outlining limit set to 60000: `Selecting statements took 633.499834 msecs. result: 2970`
- emcc with default outlining limit in the .zip file (30000): `Selecting statements took 1108.744872 msecs. result: 2970`
- emcc with outlining limit set to 10000: `Selecting statements took 2004.403546 msecs. result: 2970`

Already the version without outlining is 10x slower than native, and outlining makes the performance increasingly worse. The offending function seems to be `_sqlite3VdbeExec`, which starts off at 165856 lines.

This slowdown causes multiple second pauses when run on Firefox OS device. @kripken, could you take a look at this to see if there's something that could be improved?

**Comment by kripken** [comment]
The question from the last comment [came up again](https://twitter.com/UnitZeroOne/status/748655601534767104) - any reason not to turn on `MEMFS_APPEND_TO_TYPED_ARRAYS` by default? cc @juj
