### ISSUE TITLE
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_newstate

### ISSUE THREAD

**Issue by JackTam1993** [emscripten-core/emscripten#19779]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.41 (71634e036d20209a5d81c2b2171e145b44de1e12)
clang version 17.0.0 (https://github.com/llvm/llvm-project 88421ea973916e60c34beb26597a5fc33f83dd8f)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
main.c:40:15: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
   40 |         char *json_str = lua_tostring(L, -1);
      |               ^          ~~~~~~~~~~~~~~~~~~~
main.c:45:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
   45 | }
      | ^
main.c:79:15: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
   79 |         char *json_str = lua_tostring(L, -1);
      |               ^          ~~~~~~~~~~~~~~~~~~~
main.c:84:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
   84 | }
      | ^
4 warnings generated.
emcc: warning: /usr/local/lib/liblua.a: archive is missing an index; Use emar when creating libraries to ensure an index is created [-Wemcc]
emcc: warning: /usr/local/lib/liblua.a: adding index [-Wemcc]
cache:INFO: generating system asset: symbol_lists/8a71ad60e6f03281a3d002adbb9c4a046d8a32bd.json... (this will be cached in "/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/symbol_lists/8a71ad60e6f03281a3d002adbb9c4a046d8a32bd.json" for subsequent builds)
cache:INFO:  - ok
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_newstate
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_openlibs
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_loadfile
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_pcall
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_tolstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_getfield
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_pushstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_pcall
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_tolstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_isstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_tolstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_close
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_newstate
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_openlibs
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: luaL_loadfile
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_pcall
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_tolstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_getfield
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_pushstring
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o: undefined symbol: lua_pcall
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
emcc: error: '/Users/tanjj4/Documents/github/emsdk/upstream/bin/wasm-ld -o ../dist/main.wasm /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_h3tb36qo/main_0.o /usr/local/lib/liblua.a -L/usr/local/lib -L/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crt1.o -lGL -lal -lhtml5 -lstandalonewasm-nocatch -lstubs -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/tmpk93j96vflibemscripten_js_symbols.so --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --global-base=1024' failed (returned 1)

**Full link command and output with `-v` appended:**
CC=/opt/homebrew/bin/gcc-13 emcc main.c -o ../dist/main.wasm -llua -I/usr/local/include -I/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/include -L/usr/local/lib  -g -O2 -sEXPORTED_FUNCTIONS=_main -sEXPORTED_RUNTIME_METHODS=ccall,cwrap

**Comment by JackTam1993** [comment]
```c
#include <stdio.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include <stdlib.h>
#include <emscripten.h>


EMSCRIPTEN_KEEPALIVE
char* jsonToData(const char *s1) {
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    int retLoad = luaL_loadfile(L, "../lua/FA.lua");

    if (retLoad == 0)
    {
        printf("load file success retLoad:%d\n", retLoad);
    }

    if (retLoad || lua_pcall(L, 0, 0, 0))
    {
        printf("error %s\n", lua_tostring(L, -1));
        char* failed;
        return failed;
    }

    lua_getglobal(L, "jsonToData");
    lua_pushstring(L, s1);

    int pcallRet = lua_pcall(L,1,1,0);
    if (pcallRet != 0)
    {
        printf("error %s\n", lua_tostring(L, -1));
        char* failed;
        return failed;
    }

    // 获取 Lua 函数的返回值
    if (lua_isstring(L, -1)) { // 如果返回值是一个字符串
        char *json_str = lua_tostring(L, -1);
        return json_str;
    }

    lua_close(L);
}

EMSCRIPTEN_KEEPALIVE
char* dataToJson(const char *s1) {
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    int retLoad = luaL_loadfile(L, "../lua/FA.lua");

    if (retLoad == 0)
    {
        printf("load file success retLoad:%d\n", retLoad);
    }

    if (retLoad || lua_pcall(L, 0, 0, 0))
    {
        printf("error %s\n", lua_tostring(L, -1));
        return "failed";
    }

    char* hex = (char*)malloc(256); // allocate memory for JSON string
    sprintf(hex, "{\"deviceinfo\": {\"deviceType\": \"\", \"deviceSubType\": \"23\", \"deviceSN\": \"\"}, \"status\": { }, \"msg\": {\"data\": \"%s\"}}", s1);
    lua_getglobal(L, "dataToJson");
    lua_pushstring(L, hex);

    int pcallRet = lua_pcall(L,1,1,0);
    if (pcallRet != 0)
    {
        printf("error %s\n", lua_tostring(L, -1));
        char* failed;
        return failed;
    }

    // 获取 Lua 函数的返回值
    if (lua_isstring(L, -1)) { // 如果返回值是一个字符串
        char *json_str = lua_tostring(L, -1);
        return json_str;
    }

    lua_close(L);
}

int main(void) {
    return 0;
}

```

**Comment by sbc100** [comment]
I suspect the problem here is the use of `/usr/local/lib/liblua.a`.. that looks likely to be a library built for the current host (i.e. x86_64).  If that is the case then the solution is to build a wasm-specific version of liblua.a and link against that instead.

In particular, you almost certainly don't want to be passing ` -L/usr/local/lib` to emcc.

**Comment by JackTam1993** [comment]
I compile the lua source code on my mac with adding the option "-arch arm64" in the makefile. And I just leave the central part of the code that relevant to the lua part. 
When I execute the command 
```emcc -s EXPORTED_FUNCTIONS="['_say_hello']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" --post-js post.js --js-library console.js hello.c -o hello.js```. 

it returns
```
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_ax85e86w/hello_0.o: undefined symbol: luaL_newstate
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_ax85e86w/hello_0.o: undefined symbol: luaL_openlibs
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_ax85e86w/hello_0.o: undefined symbol: lua_close
emcc: error: '/Users/tanjj4/Documents/github/emsdk/upstream/bin/wasm-ld -o hello.wasm /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_ax85e86w/hello_0.o -L/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/tmpnj3m0wz2libemscripten_js_symbols.so --strip-debug --export-if-defined=say_hello --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
make: *** [build] Error 1
```

Here is the c code.
```c
#include <stdio.h>
#include "include/lua/lua.h"
#include "include/lua/lauxlib.h"
#include "include/lua/lualib.h"
#include <stdlib.h>
#include "console.h"

void say_hello() {
  console_log("Hello, World!");

  lua_State *L = luaL_newstate();
  luaL_openlibs(L);
  lua_close(L);
}

int main(int argc, const char *argv[])
{
  say_hello();
  return 0;
}
```

**Comment by sbc100** [comment]
You still need to link against the resulting lua library.  I don't see it references in your link line (`emcc -s EXPORTED_FUNCTIONS="['_say_hello']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" --post-js post.js --js-library console.js hello.c -o hello.js.`). 

I would expect either something like `/path/to/liblua.a` or both `-Lpath/to` and `-llua`.  Either one should work.

Also, when you compile lua you need to make you are suing `emcc` as the compiler.  `-arch arm64` should not be need and sounds wrong.  emscripten is a cross compiler that targets the wasm architecture, not arm64.

**Comment by JackTam1993** [comment]
I followed your sugguestion compiled lua with emcc, and got another error: `fatal error: 'readline/readline.h' file not found`. I saw another guy also mentioned about this question and the solution is compile readline with emcc. I just want to confirm am I understanding right?

**Comment by sbc100** [comment]
Yes emscripten doesn't come with readline, so you would need to figure out how to make it work.  But also emscripten doesn't really have a PTY/TTY layer so you are better of configuring lua to build without readline support if you can.   I imagine there is an option to turn it off... since we build lua in our test suite and it seems to work find without readline.

**Comment by JackTam1993** [comment]
Yes It works. After compiling lua with emcc, I copy the code to the original project and the problem still exists. 
```
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o: undefined symbol: luaL_newstate
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o: undefined symbol: luaL_openlibs
wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o: undefined symbol: lua_close
emcc: error: '/Users/tanjj4/Documents/github/emsdk/upstream/bin/wasm-ld -o hello.wasm /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o -L/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/tmp6tfkasfwlibemscripten_js_symbols.so --strip-debug --export-if-defined=say_hello --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
make: *** [build] Error 1
```

**Comment by JackTam1993** [comment]
> Yes emscripten doesn't come with readline, so you would need to figure out how to make it work. But also emscripten doesn't really have a PTY/TTY layer so you are better of configuring lua to build without readline support if you can. I imagine there is an option to turn it off... since we build lua in our test suite and it seems to work find without readline.

I remove `-DLUA_USE_READLINE` in the makefile so it can be built without readline.

**Comment by sbc100** [comment]
> Yes It works. After compiling lua with emcc, I copy the code to the original project and the problem still exists.
> 
> ```
> wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o: undefined symbol: luaL_newstate
> wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o: undefined symbol: luaL_openlibs
> wasm-ld: error: /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o: undefined symbol: lua_close
> emcc: error: '/Users/tanjj4/Documents/github/emsdk/upstream/bin/wasm-ld -o hello.wasm /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_oy3lic30/hello_0.o -L/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/tmp6tfkasfwlibemscripten_js_symbols.so --strip-debug --export-if-defined=say_hello --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
> make: *** [build] Error 1
> ```

I don't see `-llua` or `/some/path/to/liblua.a` anywhere in that link command.  Did you remember to pass the lua library to the linker on the command line?

**Comment by JackTam1993** [comment]
Thank you for your patience! It works! There is no error at all finally.

**Comment by sbc100** [comment]
No worries!  Glad to help out!

**Comment by JackTam1993** [comment]
I have another problem and I don't know if caused by emscripten. The code below is to load a lua file in the same directory. When I compile it with gcc, it works, but can't find the file when I compile it with emcc.
```c
char* jsonToData(const char *s1) {

    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    int retLoad = luaL_loadfile(L, "./lua_script/FA.lua");

    if (retLoad == 0)
    {
        printf("load file success retLoad:%d\n", retLoad);
    }

    if (retLoad || lua_pcall(L, 0, 0, 0))
    {
        printf("error %s\n", lua_tostring(L, -1));
        return "failed";
    }

    lua_getglobal(L, "jsonToData");
    lua_pushstring(L, s1);

    int pcallRet = lua_pcall(L,1,1,0);
    if (pcallRet != 0)
    {
        printf("error %s\n", lua_tostring(L, -1));
        char* failed = "failed";
        return failed;
    }

    // 获取 Lua 函数的返回值
    if (lua_isstring(L, -1)) { // 如果返回值是一个字符串
        char *json_str = lua_tostring(L, -1);
        return json_str;
    }

    lua_close(L);
}
```

**Comment by sbc100** [comment]
Where are you trying to run the resulting program?  If you are using node you might want to try `-sNODERAWFS`..  otherwise if you are trying to run on the web then you will need to somehow inject that files you need into the emscripten VFS.  One simple way to do this is using `--preload-file=lua_script/FA.lua`.  

You can read more about this stuff in the docs: https://emscripten.org/docs/api_reference/Filesystem-API.html

**Comment by JackTam1993** [comment]
Thank you again~
