### ISSUE TITLE
lxml installation on mac CI bots is failing

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#19785]
It seems that the new version of lxml doesn't (yet) have a pre-built python wheel file available for it and so that mac bots are trying to build it form source and failing with:

```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -mmacosx-version-min=10.11 -Werror=partial-availability -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/Users/distiller/emsdk/python/3.9.2_64bit/include/python3.9 -c src/lxml/etree.c -o build/temp.macosx-10.11-x86_64-3.9/src/lxml/etree.o -w -flat_namespace
    src/lxml/etree.c:96:10: fatal error: 'Python.h' file not found
    #include "Python.h"
             ^~~~~~~~~~
    1 error generated.
```

See https://app.circleci.com/pipelines/github/emscripten-core/emscripten/29147/workflows/736207b0-aad1-4291-9664-e95a033767cf/jobs/656953

**Comment by wa008** [comment]
I meet the same problem.

Did this problem only occur on macos?

**Comment by sbc100** [comment]
I'm not sure how this bug resolved but our mac bots seem to be working fine again.   Sorry I can't be of more help.

**Comment by wa008** [comment]
> I'm not sure how this bug resolved but our mac bots seem to be working fine again. Sorry I can't be of more help.

My mac machine is M1 chip, could I know is mine same with you? Thanks anyway

**Comment by sbc100** [comment]
> > I'm not sure how this bug resolved but our mac bots seem to be working fine again. Sorry I can't be of more help.
> 
> My mac machine is M1 chip, could I know is mine same with you? Thanks anyway

Yes we do run tests of mac M1 these days.
