### ISSUE TITLE
dynamic linking error wasm-ld: error: lua/liblua.a(lstring.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC

### ISSUE THREAD

**Issue by JackTam1993** [emscripten-core/emscripten#19822]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.41 (71634e036d20209a5d81c2b2171e145b44de1e12)
clang version 17.0.0 (https://github.com/llvm/llvm-project 88421ea973916e60c34beb26597a5fc33f83dd8f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/tanjj4/Documents/github/emsdk/upstream/bin
tanjj4@tanjj4-Mac252 emscripten-example % 

**Failing command line in full:**
emcc -s EXPORTED_FUNCTIONS="['_say_hello', '_jsonToData']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" -sSIDE_MODULE=2  -Llua/ -llua --post-js post.js --js-library console.js --preload-file ./lua_script hello.c -o hello.wasm

**Full link command and output with `-v` appended:**
wasm-ld: error: lua/liblua.a(lstring.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `luaT_init.luaT_eventname`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.35`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `luaT_typenames_`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.36`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.37`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.36`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.37`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.36`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(ltm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.37`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.1`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.2`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.3`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.4`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.5`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.6`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `luaV_execute.disptab`; recompile with -fPIC
wasm-ld: error: lua/liblua.a(lvm.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.6`; recompile with -fPIC
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
emcc: error: '/Users/tanjj4/Documents/github/emsdk/upstream/bin/wasm-ld -o hello.wasm -Llua/ lua/liblua.a /var/folders/pr/bp4hg36x7bqgnln4b_t7q3s40000gp/T/emscripten_temp_j_fz6ujn/hello_0.o -L/Users/tanjj4/Documents/github/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-memory --strip-debug --export-if-defined=say_hello --export-if-defined=jsonToData --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__wasm_apply_data_relocs --export-if-defined=fflush --export=__wasm_call_ctors --experimental-pic -shared --no-export-dynamic --stack-first' failed (returned 1)
make: *** [build] Error 1
emmake: error: 'make' failed (returned 2)

I loaded the lua file through luaL_loadfile, which works well. But the lua file "FA.lua" require a module called "cjson". Under the guideline I use dynamic linking with adding -sSIDE_MODULE=2 in the command and the problem occurs. Here is the code:
```c
char* jsonToData(const char *s1) {

    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    int retLoad = luaL_loadfile(L, "./lua_script/FA.lua");

    lua_close(L);
}
```

```lua
local JSON = require "./lua_script/cjson"
local _bit = require "bit"
```

The project structure is:
|---
|--hello.c
|--lua_script
|---FA.lua
|---cjson.so

**Comment by sbc100** [comment]
Any code that is built into a side module needs to be compiled with `-fPIC`.  So if you want to link `liblua.a` into your side module then you would need rebuild `liblua.a` with `-fPIC`.

However, are you sure you want to build lua into your side module?  Can you explain why you need to do that?  Using static linking is a lot simpler and more efficient with emscripten, and most use cases don't require dynamic linking.

**Comment by JackTam1993** [comment]
The background of the project is that I have a c program called "hello.c" which will load a lua file called "FA.lua" and I need to load "FA.lua" and execute the function defined in the lua file. Inside the "FA.lua", it requires modules call "cjson" and "bit". When I tried to compile it with the command: 
```
emcc -s EXPORTED_FUNCTIONS="['_say_hello', '_jsonToData']" -s EXPORTED_RUNTIME_METHODS="['ccall', 'cwrap']" -Llua/ -llua --post-js post.js --js-library console.js --preload-file ./lua_script hello.c -o hello.js
```
It returned this:
```
Aborted(To use dlopen, you need enable dynamic linking, see https://emscripten.org/docs/compiling/Dynamic-Linking.html)
```
So I use dynamic linking and results the problem above.

**Comment by JackTam1993** [comment]
I have comfirmed that when lua calls require it will finally call dlopen. I am figuring out how to make it into one module. It's not the problem of emscripten so I close this issue. Thanks a lot.
