### ISSUE TITLE
How does emscripten generate 32-bit and 64-bit wasm

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#19833]
Does wasm distinguish between 32-bit and 64-bit, and why does it appear `Target: wasm32-unknown-emscripten` after emcc-v .

How does emscripten generate 32-bit and 64-bit wasm ?

**Comment by sbc100** [comment]
We use the `-sMEMORY64` setting.

**Comment by yangfangfang1204** [comment]
and i add `-sMEMORY64` , there is a warning: `-sMEMORY64 is still experimental. Many features may not work`. so what features can't be used ? 

And i run the hello.html in chromeV114-64bit , chrome return the error: `invalid memory limits flags 0x5(enable via --experimental-wasm-memory64)` ?  so memory64 is still experimental , if i want to use it , What do I need to pay attention to ？

**Comment by sbc100** [comment]
The places where support is limited is in the JS library code and in the interaction with JS.     

Some major features that I know don't work yet are -sASYNCIFY and webgl bindings.

**Comment by yangfangfang1204** [comment]
if i decode a video by ffmpeg and render the yuv by opengl , then emcc the ffmpeg-decode module and opengl render module to the ffmpeg.wasm.

the ffmpeg.wasm not support wasm64 ？

**Comment by sbc100** [comment]
I imagine it will easy to compile ffmpeg.wasm for memory64.   The rendering part might not work correctly though.. there are some open PRs related to webGL support.

**Comment by yangfangfang1204** [comment]
OK， where is the open PRs related to webGL support in wasm64 ?

**Comment by sbc100** [comment]
https://github.com/emscripten-core/emscripten/pull/18744
https://github.com/emscripten-core/emscripten/pull/19289

**Comment by yangfangfang1204** [comment]
thanks. and i run the helloword.html (-s MEMORY64 ) , the chrome return the error `invalid memory limits flags 0x5 (enable via --experimental-wasm-memory64) @+365)` , this need some setting ?

**Comment by sbc100** [comment]
You can use `--enable-experimental-webassembly-features` and `--js-flags=--experimental-wasm-memory64`

**Comment by yangfangfang1204** [comment]
that means chrome doesn't support memory64  now , we need set experimental flags to enable it ?

**Comment by sbc100** [comment]
Yes, its not yet standardized and still experimental, both in the toolchain and the browsers.

**Comment by sbc100** [comment]
What is more, until this change land you won't even be able to actually allocate a memory larger than 4gb: https://github.com/emscripten-core/emscripten/pull/19737

**Comment by yangfangfang1204** [comment]
When will it be standardized and released, and how long will it take, one year? two year? We can plan our work according to stadardized time.

**Comment by sbc100** [comment]
My hope is that it will reach stage 4 (This basically means it is standardized and will be available in chrome and other browsers without a flag) this year.   However, there is obviously no guarantee.

**Comment by yangfangfang1204** [comment]
ok , thanks . i test a decode time , it need 20ms to decode one frame by ffmpeg.wasm32 , and it need 30ms to decode the same frame by ffmpeg.wasm64 . Why does wasm64  take longer to decode than wasm32？

**Comment by sbc100** [comment]
Thats pretty hard to say.   One possible cause of slowdown is the larger pointer size..  this can effect the data locality since it can increase the sizes of structs (and things like vtables).

**Comment by sbc100** [comment]
I think the original question has been answered here: `-sMEMORY64`.

**Comment by sbc100** [comment]
You need to recompile `ffmpeg/src/ffmpeg_project-build/libavutil/libavutil.a` (and all the object files within in) with `-sMEMORY64`
