### ISSUE TITLE
expected identifier on extern syntax

### ISSUE THREAD

**Issue by wolfviking0** [emscripten-core/emscripten#1983]
Hi,

I have a trouble with a sample using this syntax :

extern "C" cl_uint gReSeed;
extern "C" cl_uint gRandomSeed;

That give me an error :

Wrappers.h:24:8: error: 
      expected identifier or '('
extern "C" cl_uint gReSeed;
       ^

I try the sample natively with clang3.2 the same use by emscripten, and it's work perfect.

I will try to extract the part for have a small sample, but any idea ??

**Comment by urielzen** [comment]
@eteq Thank you!
