### ISSUE TITLE
on[10225]:0x3fcfb1 MonoBleedingEdge.framework.js:2 DllNotFoundException: Unable to load DLL 'FirebaseCppApp-11_2_0': The specified module could not be found. Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE.SWIGExceptionHelper' threw an exception.  Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.  Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.  Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.

### ISSUE THREAD

**Issue by johntitor08** [emscripten-core/emscripten#19862]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

**Comment by johntitor08** [comment]
To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking

**Comment by johntitor08** [comment]
Failed to copy package file to Assets/Firebase/Plugins/x86_64/FirebaseCppApp-11_2_0.dll

**Comment by brendandahl** [comment]
This looks like it was filed in wrong place, if not please fill out more detail.
