### ISSUE TITLE
ASYNCIFY=1 emscripten_sleep broken

### ISSUE THREAD

**Issue by benjamin-sieffert** [emscripten-core/emscripten#19872]
It seems that `emscripten_sleep` with `ASYNCIFY=1`, when called with low amount of ms (e.g. 16 or 1) often sleeps for 1000 ms or 0 ms instead of the requested amount.
See further down for bisection.

Reproducer: https://github.com/benjamin-sieffert/emscripten-sleep-bug
All details for how to run are in the repo.
Sorry the reproducer being in Rust – it does work with older versions of emscripten (see below), so this must be related to emscripten somehow.

**Comment by brendandahl** [comment]
I was unable to reproduce with the following:

```c
#include <stdio.h>
#include <emscripten.h>

int main() {

  for (int i = 0; i < 100; i++) {
    EM_ASM(
      globalThis.start = performance.now();
    );
    emscripten_sleep(16);
    EM_ASM(
      console.log(performance.now() - start);
    );
  }

}
```

`emcc -sASYNCIFY=1 -g main.c -o a.out.html`

Could you try [bisecting](https://emscripten.org/docs/contributing/developers_guide.html#bisecting)?

**Comment by benjamin-sieffert** [comment]
Is indeed hard to reproduce in C.
The best I can do is run code in an inactive tab, which at least results in 1000 ms sleeps. But no early wakeups.
So I figure the 1000ms come from the browser suspending for a long time if the code is not 'active' for the user.
Meanwhile I removed all SDL code from my reproducer and still had the same issue. So it seems to be a Rust/emscripten integration issue after all.

Now the questions are maybe:
- Why might the Rust code be treated as inactive by the browser?
- Why does it so often wake up early, though?
- Why was it not the case on emscripten from May last year?

I will try filing a bug in the Rust repo, too, but maybe you have an idea what could be wrong from a WASM perspective?
It might be related to stack layout etc.
It might also be a compiler optimization, but turning them all off and black-boxing the call to sleep does not help.

**Comment by brendandahl** [comment]
setTimeout is [throttled](https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html) to 1000ms on background tabs. Are you seeing a 1000ms pause on foreground tabs too?

**Comment by benjamin-sieffert** [comment]
>Could you try [bisecting](https://emscripten.org/docs/contributing/developers_guide.html#bisecting)?

I bisected manually by jumping commits in this repo. The culprit is c8857a6152c3954014d2aefb706471ee4c80fe30.

>Are you seeing a 1000ms pause on foreground tabs too?

Yes, but what is more, when trying to sleep 16 ms I see e.g.
- 50 early wake ups where sleep time was mostly less than 0 ms (maybe immediate wakeup)
- then suddenly one sleep for 1000 ms

**Comment by benjamin-sieffert** [comment]
OK, I think this hinted in the right direction. When I use `emscripten_get_now` instead of `Instant::now()` for timekeeping, I do not get the "sleep bug" – so it is not a sleep bug after all, but an issue of how the Rust-std `Instant::now` for emscripten has internally corrupted timestamps, because c8857a6152c3954014d2aefb706471ee4c80fe30 was not picked up properly.
This probably leads to all sorts of insane glitches.

**Comment by benjamin-sieffert** [comment]
May it not be that `long` is 32-bit on wasm32, yet `_Int64` is 64-bit?
Referring to the comment of @sbc100 in https://github.com/emscripten-core/emscripten/pull/16966 …
>This doesn't change the size of the type for wasm32

**Comment by benjamin-sieffert** [comment]
Fixing this in https://github.com/rust-lang/libc/pull/3307.
The only wrong/misleading thing was the description of #17401
> The change to 32-bit was only recently made in https://github.com/emscripten-core/emscripten/pull/16966.

– on wasm32, `time_t` had always been 32 bit. It’s 64 bit now and that’s alright, just needs to be reflected in the Rust-side shim.
