### ISSUE TITLE
How to get all functions called by `__wasm_call_ctors`?

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#19888]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c51
6f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb42240
4f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/apple/emsdk/upstream/bin
```

I want to get all functions that are called by `__wasm_call_ctors` at start. It doesn't matter whether they are minified names into numbers or un-minified. Is it possible to get such a list?

**Comment by ravisumit33** [comment]
We are trying to split all function symbols inside a folder into a deferred wasm using wasm-split. Issue is that some of the symbols are getting called by `__wasm_call_ctors` which is causing deferred wasm to load. If we somehow get all such symbols we will keep them in the primary wasm itself.

**Comment by sbc100** [comment]
@tlively re wasm-split

**Comment by ravisumit33** [comment]
I can use `pre_main` hook to get most of the functions. Thanks.
