### ISSUE TITLE
How to overwrite `__attribute__((__weak__)) int getentropy` ?

### ISSUE THREAD

**Issue by lum1n0us** [emscripten-core/emscripten#19899]
Recently, we noticed `std::random_device::operator()` always raises an exception in the standalone mode. And turns out `emscripten/system/lib/standalone/standalone.c` contains a "weak" implementation :

```c++
//  in emscripten/system/lib/libcxx/src/random.cpp

unsigned
random_device::operator()()
{
    unsigned r;
    size_t n = sizeof(r);
    int err = getentropy(&r, n);
    if (err)
        __throw_system_error(errno, "random_device getentropy failed");
    return r;
}

// in emscripten/system/lib/standalone/standalone.c

// There is no good source of entropy without an import. Make this weak so that
// it can be replaced with a pRNG or a proper import.
__attribute__((__weak__))
int getentropy(void* buffer, size_t length) {
  abort();
}
``` 

Therefore, it seems we should use a "strong" implementation to overwrite the "weak". But we failed. We can't achieve the overwrite.

We've tried below options:

- like *simple test case*, give a "strong" implementation
- `-Wl,--wrap=<xx>=<xx>`
- `-Wl,--undefined=getentropy`

---

A simple test case

```c++
// it is main.cc
// - transfer it to .wasm
// $ em++ -o test.wasm main.cc
// - check the output with 
// $ /opt/wabt-1.0.31/bin/wasm-objdump -j Code -d test.wasm | grep -A 4 getentrop
int
getentropy(void *buffer, size_t length)
{
    std::cout << "in my getentropy" << std::endl;
    return 100;
}

int
main()
{
    std::random_device rd;

    std::cout << "default random_device characteristics:" << std::endl;
    std::cout << "entropy: " << rd.entropy() << std::endl;
    std::cout << "a random number: " << rd() << std::endl;  // <--- abort()

    std::cout << "minimum: " << rd.min() << std::endl;
    std::cout << "maximum: " << rd.max() << std::endl;

    return 0;
}
```

---

Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.32 (eab98adf462c39f3c31d348331c4830bcaa36949)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

**Comment by sbc100** [comment]
I think the problem is that your `main.cc` is a C++ file so you may need to add `extern "C"` around the declaration.   

Alternatively, including  `#include <unistd.h>` should also do that trick since it will pre-declare `getentropy` as `extern "C"`

**Comment by lum1n0us** [comment]
Thanks for reminding me.
