### ISSUE TITLE
support fesetround(FE_UPWARD)?

### ISSUE THREAD

**Issue by Innovgame** [emscripten-core/emscripten#19908]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.43 (a6b8143cf3c1171db911750359456b15a8deece7)
clang version 17.0.0 (https://github.com/llvm/llvm-project 71513a71cdf380efd6a44be6939e2cb979a62407)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\emsdk\upstream\bin

**Failing command line in full:**
fesetround(FE_UPWARD) not work. My code relies on it, what should I do?

**Comment by renqh123** [comment]
I have also encountered this issue recently and I really hope to find an effective solution.

**Comment by sbc100** [comment]
Can you give an example that fails?   Does it fail to build or does it fail to produce the correct results?

**Comment by sbc100** [comment]
IIUC this is a feature is missing from the underlying WebAssembly instruction set.  IIUC we have no way to control the floating point unit in this way.  @tlively can you confirm?   

Update: It looks like there is an active proposal to add rounding mode control: https://github.com/WebAssembly/rounding-mode-control.  The discussion that let to this proposal is https://github.com/WebAssembly/design/issues/1456.   However from the looks of the proposal it doesn't look like it would provide a way to implement `fesetround` which requires the ability to change the ambient rounding mode.   Is my understanding correct @tlively ?

**Comment by tlively** [comment]
Yes, that is correct. While having an ambient rounding mode was considered, most folks want per-operation rounding mode instead because it is more in line with WebAssembly's design principles. The people in that discussion might be interested in hearing more about your use case, @renqh123. For the time being, you will have to change your code to not depend on an ambient rounding mode.
