### ISSUE TITLE
"ERROR: Parameter 0 has unknown type 17CameraChangeEvent" ? (Emscription, Embind)

### ISSUE THREAD

**Issue by addie293** [emscripten-core/emscripten#19915]
I have been trying to call a Typescript function that I passed as a pointer into the C++ file using emscripten:: val. Thereafter, I am calling the function using the argument necessary using val.
 
````
struct CameraChangeEvent{
    double *position;
    double viewAngle;
    double *clippingRange;
    double *focalPoint;
    bool parallelProjection;
    double *physicalTranslation;
    double *viewUp;
    double parallelScale;
};

class Renderer {
private:
  emscripten::val vtkCameraChangeFn;
  vtkNew<vtkRenderer> renderer;

public:

  void Run(emscripten::val vtkCameraChangeFn) {
     CameraChangeEvent positionChange;
     positionChange.position = this->renderer->GetActiveCamera()a->GetPosition();
     positionChange.viewAngle = this->renderer->GetActiveCamera()->GetViewAngle();
     positionChange.clippingRange = this->renderer->GetActiveCamera()->GetClippingRange();
     positionChange.focalPoint = this->renderer->GetActiveCamera()->GetFocalPoint();
     positionChange.parallelProjection = this->renderer->GetActiveCamera()->GetParallelProjection();
     positionChange.parallelProjection = this->renderer->GetActiveCamera()->GetParallelProjection();
     positionChange.viewUp = this->renderer->GetActiveCamera()->GetViewUp();
     positionChange.parallelScale = this->renderer->GetActiveCamera()->GetParallelScale();
    this->vtkCameraChangeFn = vtkCameraChangeFn;

    this->vtkCameraChangeFn.operator()(positionChange);

  }

````
However, in the Web UI chrome debugger, I seem to be receiving the following error:
![image](https://github.com/emscripten-core/emscripten/assets/40389482/4cd6bfcf-4d79-4a68-86ff-806fe7c8c537)
I am very new to Emscripten and C++, so I do not understand where the binding error comes from out here. I have already used Embind for the run function so that it can be used in Typescript to pass a specific Typescript function as a pointer. And of course, I am using the operator function in [val.h](https://emscripten.org/docs/api_reference/val.h.html) for it.

**Comment by sbc100** [comment]
Presumably `vtkCameraChangeFn` is expecting a JS object as argument 0, but it looks like `positionChange` is just a regular C struct.   I think you would need to somehow construct a JS object handle which you pass as argument zero.  One way to do this I believe is via the `val` API. 
  See https://emscripten.org/docs/api_reference/val.h.html#_CPPv4N10emscripten10emscripten3val6objectEv

@brendandahl

**Comment by brendandahl** [comment]
You'll need to [define a binding](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#classes) for your `CameraChangeEvent` struct.

**Comment by addie293** [comment]
Thanks a lot for the response! This seem to have worked. :)
