### ISSUE TITLE
 Uncaught (in promise) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #0 module="env" function="_emval_get_global" error: function import requires a callable)

### ISSUE THREAD

**Issue by LilyZhou52** [emscripten-core/emscripten#19928]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.38 (9eff02bc816c50ab0e3b70a3bd5b72a8dc2893a2)
clang version 17.0.0 (https://github.com/llvm/llvm-project 004bf170c6cbaa049601bcf92f86a9459aec2dc2)
Target: wasm32-unknown-emscripten
Thread model: posix

**my code:**
#include <emscripten.h>
#include <emscripten/val.h>
int main()
{
	 emscripten::val location =  emscripten::val::global("location");
}

**Failing command line in full:**
when I use emcc to compile the code, there is something wrong.
wasm-ld: error: /tmp/emscripten_temp_ub8rzf38/aesplus_0.o: undefined symbol: _emval_get_global
wasm-ld: error: /tmp/emscripten_temp_ub8rzf38/aesplus_0.o: undefined symbol: _emval_decref

then I check the use of val.h in the websit of emscripten.org, I add the" -lembind" in compile command，
as "emcc aesplus.cpp -I resource/openssl/include -L resource/openssl/libs -lcrypto -s EXPORTED_RUNTIME_METHODS='["cwrap", "ccall"]' -s EXPORTED_FUNCTIONS='["_free","_malloc"]' -s ALLOW_MEMORY_GROWT
H=1 -lembind -o aesplus.js"

now I can compile the code correctly，but when I use the wasm file in my web project, the brower console shows error：
aesplus.js:678 Uncaught (in promise) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #0 module="env" function="_emval_get_global" error: function import requires a callable)

**Comment by andrei-tatar** [comment]
@LilyZhou52 How did you solve your issue?
I'm also getting this weird message, even though it was working fine. I haven't changed anything. It just started happening.
