### ISSUE TITLE
worker.js uses nullish-coalescing operator

### ISSUE THREAD

**Issue by dipidoo** [emscripten-core/emscripten#19923]
https://github.com/emscripten-core/emscripten/blob/5c0799f08ca04a6601a56a43d4f28239f3da9212/src/worker.js#L102C18-L102C20
```
self.onunhandledrejection = (e) => {
  throw e.reason ?? e;
};
```

Per [compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#browser_compatibility), not too terribly modern, but still newer than WebAssembly or SharedArrayBuffer in general.

Perhaps `||` would be an acceptable substitute? If anyhow the boolean coercion is different to `??`, the container would be thrown which is not too bad. It does change the behavior slightly however, it's just that the full-blown polyfill might be verbose.

**Comment by sbc100** [comment]
BTW, are you targeting a platform without support for this operator?  (Which one?)
