### ISSUE TITLE
Re-fix EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD

### ISSUE THREAD

**Issue by rgriege** [emscripten-core/emscripten#19921]
**Version of emscripten/emsdk:**
`emcc -v`:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472c
cc3da)
clang version 17.0.0 (https://github.com/llvm/llvm-project f3b64887de61020c09404bfee97b2fadd30df10a)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
This is a run-time issue, see explanation below

**Full link command and output with `-v` appended:**
See Makefile below.  I'm just running `make` to compile a pretty simple project.

At runtime, I'm getting an assertion with the following console output:
```
Uncaught RuntimeError: Aborted(Assertion failed)
    abort http://bug.localhost/index.js:768
    assert http://bug.localhost/index.js:421
    getTargetThreadForEventCallback http://bug.localhost/index.js:6565
    registerMouseEventCallback http://bug.localhost/index.js:9364
    _emscripten_set_mousemove_callback_on_thread http://bug.localhost/index.js:9425
    createExportWrapper http://bug.localhost/index.js:805
    callMain http://bug.localhost/index.js:10968
    doRun http://bug.localhost/index.js:11027
    run http://bug.localhost/index.js:11038
```

** Background & Reproduction **
#19691 broke the debug version of my application.  Everything worked fine when running emsdk 3.1.42, but running a build compiled with 3.1.43 now triggers the assertion above.  I'm building a graphical/interactive SDL-based application with some background threads that don't need any interaction with the mouse / web page / DOM.

I've narrowed it down to a pretty simple use case that demonstrates the problem.  When built with version 3.1.42 of the sdk, I get a fuchsia screen.  In 3.1.43 I get a black screen and an assertion.  All I have to do is call `make` and open `index.html` in a browser.

Makefile:
```
index.html: main.o
	emcc main.o -o index.html -sUSE_SDL=2 -sUSE_PTHREADS=1

main.o: main.c
	emcc -sUSE_SDL=2 -sUSE_PTHREADS=1 -c $< -o $@

clean:
	rm main.o index.*
```

main.c:
```
#include <emscripten.h>
#include <SDL2/SDL.h>
#include <GL/glew.h>

SDL_Window *window;
SDL_GLContext gl_context;
int w;
int h;

/* NOTE: Use the width of the canvas' parent.  The canvas itself seems to have a finnicky width. */
EM_JS(int, get_canvas_width, (), { return canvas.parentElement.getBoundingClientRect().width; });

void frame(void)
{
	SDL_GL_MakeCurrent(window, gl_context);

	glViewport(0, 0, w, h);
	glClearColor(255, 0, 255, 255);
	glClear(GL_COLOR_BUFFER_BIT);
	glFlush();

	SDL_GL_SwapWindow(window);
}

EMSCRIPTEN_KEEPALIVE int main(int argc, char *const argv[])
{
	w = get_canvas_width();
	h = w * 9 / 16; /* typical aspect ratio */

	/* Prevent the WASM from consuming all keyboard input on the page. */
	SDL_SetHint(SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT, "#canvas");

	/* Initialize SDL */
	SDL_SetMainReady();
	if (SDL_Init(SDL_INIT_VIDEO) < 0) {
		fprintf(stderr, "SDL_Init(VIDEO) failed: %s\n", SDL_GetError());
		return 1;
	}

	/* Use OpenGLES 3.0 */
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

	/* Create a window */
	window = SDL_CreateWindow("test", 0, 0, w, h, SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS);
	if (!window) {
		fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
		return 1;
	}

	/* Create a GL context */
	gl_context = SDL_GL_CreateContext(window);
	if (gl_context == NULL) {
		fprintf(stderr, "SDL_CreateContext failed: %s\n", SDL_GetError());
		return 1;
	}

	/* Initialize GLEW */
	glewExperimental = GL_TRUE;
	GLenum glew_err = glewInit();
	if (glew_err != GLEW_OK) {
		fprintf(stderr, "glewInit error: %s\n", glewGetErrorString(glew_err));
		return 1;
	}
	glGetError(); /* clear error flag */

	emscripten_set_main_loop(frame, 0, 0);
out:
	return 0;
}
```

** Analysis **
The problem seems to be in some additional validation added to `getTargetThreadForEventCallback()` in `library_html5.js`.  I won't claim to fully understand why the new validation was added, but I'm fairly confident I don't want it for my program.  I only request or want to run these event callbacks on the main thread.  However, the SDL port has hard-coded a value of `cDefs.EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD ` for the `targetThread` parameter in this function, so I trip the assertion despite my intended usage.  I don't know if that's a problem with SDL or the Emscripten toolchain, I just know that the most recent "breaking" commit in either repository is the PR I mentioned above.

My naive suggestions would be to either
1) Update the `case EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD` to handle being called from the main thread as a "special" case returning `0`.
2) Update SDL to not hard-code `EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD` as the parameter.  That would require a PR in a different repo, which I'm more than happy to do but would appreciate some assistance in understanding why it's the right change.  I don't think I could communicate that very well at this point in time.

** Other **
This is my first interaction with the maintainers of this project, so I just want to say thanks for you work.

**Comment by sbc100** [comment]
I think `EM_CALLBACK_THREAD_CONTEXT_CALLING_THREAD` should work fine when calling thread is the main thread so it looks like the issue is with the assertion itself.    I'll take a look.  I wonder why we are not seeing that assertion fire in any of out normal single-threaded SDL2 tests.

**Comment by rgriege** [comment]
Removing the assertion would also work just fine for my case.  To clarify, I'm _only_ tripping this assertion when multi-threading is enabled - I've had no issue with single-threaded builds.  If I recall correctly, the `getTargetThreadForEventCallback()` function is stripped out of the `index.js` file in a single-threaded build, so the assertion just doesn't exist in those builds.
