### ISSUE TITLE
Preloaded file won't get modified when using CMake to build.

### ISSUE THREAD

**Issue by hjenryin** [emscripten-core/emscripten#19958]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472ccc3da)
clang version 17.0.0 (https://github.com/llvm/llvm-project f3b64887de61020c09404bfee97b2fadd30df10a)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Decription**

I'm using CMake to build a project on linux. I specified `set_target_properties(${target_name} PROPERTIES LINK_FLAGS "--preload-file ${CMAKE_CURRENT_SOURCE_DIR}/data.json@./data.json -sALLOW_MEMORY_GROWTH ")` so that I can preload `data.json`. However, if I modify the `data.json` file and rerun `emmake make`, the built `.data` is not updated. Even if I delete the built `.data`, as long as I don't delete the `.js` (or `.html`, depending on the cmake executable), `emmake make` will consider the files unchanged and won't link the preload file.

I'm not sure if this is made intentionally. Indeed, all files that needed to be compiled aren't change, so a c++ `make` doesn't have to do anything. But now that preloaded files are included in the linking phase, modification to them should also be taken into consideration when using `emmake make`. 

Note that when using `emcc file.cpp -o file.html --preload-file asset_dir` directly instead of CMake as introduced in the documentation instead of CMake, any changes will be updated in the built `.data` file after rebuilding. 

I think this is fairly easy to reproduce, but anyway, an example can be found at https://github.com/hjenryin/wasm_test.

**Comment by naszly** [comment]
I had the same problem, this line worked for me:
`set_target_properties(${target_name} PROPERTIES LINK_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/data.json)`

**Comment by hjenryin** [comment]
This works! Thanks a lot!
