### ISSUE TITLE
Bug in page:Download and install 

### ISSUE THREAD

**Issue by asialiugf** [emscripten-core/emscripten#19983]
source:  On Windows, run emsdk instead of ./emsdk, and emsdk_env.bat instead of source ./emsdk_env.sh.

should be:   On Windows, run emsdk.bat instead of ./emsdk, and emsdk_env.bat instead of source ./emsdk_env.sh.

URL: ../../docs/getting_started/downloads

**Comment by Mash707** [comment]
Hii @kripken , I have created a PR and made the necessary changes , please have a look

**Comment by sbc100** [comment]
Doesn't it work when you just type `emsdk` though?  Won't window look for `emsdk.bat` when you type that?

**Comment by kripken** [comment]
@sbc100 Sorry, I just saw your comment now. It seems like it might be clearer at least, even if it does work anyhow? But I haven't used windows in a very long time, so I'm not sure, and ok either way.

**Comment by sbc100** [comment]
> @sbc100 Sorry, I just saw your comment now. It seems like it might be clearer at least, even if it does work anyhow? But I haven't used windows in a very long time, so I'm not sure, and ok either way.

I don't really mind which is mentioned in the docs ... But I would like to know if there are any times when not adding the .bat on the end doesn't work.   If that is the case I need to update my understanding
