### ISSUE TITLE
docs: `_initialize`/`_start` is undocumented

### ISSUE THREAD

**Issue by bakkot** [emscripten-core/emscripten#20002]
The [Building Projects](https://emscripten.org/docs/compiling/Building-Projects.html#emscripten-linker-output-files) page says the following:

> `emcc ... -o output.wasm` omits generating either JavaScript or HTML launcher file, and produces a single Wasm file built in standalone mode as if the `-sSTANDALONE_WASM` settting had been used

It does _not_ say that [you must manually invoke the `_initialize` or `_start` exports before using any other exports](https://github.com/emscripten-core/emscripten/issues/13964#issuecomment-824462096) (for `--no-entry` and regular builds respectively). If you fail to do so, you get undefined behavior when calling any other export. I can't find any mention of this whatsoever in the documentation. I ran into this yesterday and it was _incredibly_ painful to track down.

It should probably also mention that you may need to provide some WASI imports, depending on the project you're compiling. (In my case there's some imports which aren't actually used but which are still present in the `imports` of the generated file, even with `-Oz`, which is annoying but at least easy to stub out.)

**Comment by kripken** [comment]
Good point. I am actually not sure where the proper docs for this would be, but we should find and link to those.

E.g. the [tool conventions repo](https://github.com/WebAssembly/tool-conventions/blob/be8ebbf73682e4b2dc5f2b4637bff76504f1885c/BasicCABI.md?plain=1#L239) mentions `_start` but not `_initialize`. @sunfishcode should that be fixed? And in general, where do we document the current state of `_start/_initialize`? (somewhere in wasi perhaps?)

**Comment by bakkot** [comment]
If you want a place to link, the best thing I've found is [the WASI ABI doc](https://github.com/WebAssembly/WASI/blob/4712d490fd7662f689af6faa5d718e042f014931/legacy/application-abi.md).

**Comment by kripken** [comment]
Thanks @bakkot , that does seem like the best place, so we should link to it. I'll mark this PR as help-wanted and hopefully someone can find time for that.
