### ISSUE TITLE
Issue with Typescript Binding generation

### ISSUE THREAD

**Issue by Neirth** [emscripten-core/emscripten#20012]
**Description of the bug report:**
I have been trying to generate a Typescript binding with the latest version of the SDK. I ran into the problem that it was throwing some strange errors. In that case I was getting an error like "An input file is expected" when I was trying to link different .bc modules of a commercial project. From that case I tried to replicate the example given in the documentation and I found the problem that I have been able to expose with logs. Is this feature working correctly? Thanks in advance for the effort.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.44 (bec42dac7873903d09d713963e34020c22a8bd2d)
clang version 17.0.0 (https://github.com/llvm/llvm-project a8cbd27d1f238e104a5d5ca345d93bc1f4d4ab1f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/neirth/.sdks/emsdk/upstream/bin
```

**Failing command line in full:**
```
neirth@better-crawdad:~/Downloads$ emcc -lembind quick_example.cpp --embind-emit-tsd interface.d.ts
wasm-ld: error: /tmp/emscripten_temp_gaob5rdr/quick_example_0.o: undefined symbol: _embind_register_class_property
wasm-ld: error: /tmp/emscripten_temp_gaob5rdr/quick_example_0.o: undefined symbol: _embind_register_class_class_function
emcc: error: '/home/neirth/.sdks/emsdk/upstream/bin/wasm-ld -o a.out.wasm /tmp/emscripten_temp_gaob5rdr/quick_example_0.o -L/home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpmbzwf4cdlibemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
```

**Full link command and output with `-v` appended:**
```
neirth@better-crawdad:~/Downloads$ emcc -v -lembind quick_example.cpp --embind-emit-tsd interface.d.ts
 "/home/neirth/.sdks/emsdk/upstream/bin/clang" --version
 "/home/neirth/.sdks/emsdk/upstream/bin/clang++" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -v quick_example.cpp -c -o /tmp/emscripten_temp_0wq2u0ze/quick_example_0.o
clang version 17.0.0 (https://github.com/llvm/llvm-project a8cbd27d1f238e104a5d5ca345d93bc1f4d4ab1f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/neirth/.sdks/emsdk/upstream/bin
 (in-process)
 "/home/neirth/.sdks/emsdk/upstream/bin/clang-17" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name quick_example.cpp -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/neirth/Downloads -resource-dir /home/neirth/.sdks/emsdk/upstream/lib/clang/17 -D EMSCRIPTEN -isysroot /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot -internal-isystem /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1 -internal-isystem /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1 -internal-isystem /home/neirth/.sdks/emsdk/upstream/lib/clang/17/include -internal-isystem /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten -internal-isystem /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include -fdeprecated-macro -fdebug-compilation-dir=/home/neirth/Downloads -ferror-limit 19 -fvisibility=default -fgnuc-version=4.2.1 -fcxx-exceptions -fignore-exceptions -fexceptions -fcolor-diagnostics -iwithsysroot/include/fakesdl -iwithsysroot/include/compat -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o /tmp/emscripten_temp_0wq2u0ze/quick_example_0.o -x c++ quick_example.cpp
clang -cc1 version 17.0.0 based upon LLVM 17.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten/c++/v1"
ignoring nonexistent directory "/home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/fakesdl
 /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/compat
 /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1
 /home/neirth/.sdks/emsdk/upstream/lib/clang/17/include
 /home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/include
End of search list.
 "/home/neirth/.sdks/emsdk/upstream/bin/wasm-ld" -o a.out.wasm /tmp/emscripten_temp_0wq2u0ze/quick_example_0.o -L/home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmp2d7rg9ollibemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first
wasm-ld: error: /tmp/emscripten_temp_0wq2u0ze/quick_example_0.o: undefined symbol: _embind_register_class_property
wasm-ld: error: /tmp/emscripten_temp_0wq2u0ze/quick_example_0.o: undefined symbol: _embind_register_class_class_function
emcc: error: '/home/neirth/.sdks/emsdk/upstream/bin/wasm-ld -o a.out.wasm /tmp/emscripten_temp_0wq2u0ze/quick_example_0.o -L/home/neirth/.sdks/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmp2d7rg9ollibemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --no-entry --max-memory=16777216 --stack-first' failed (returned 1)
neirth@better-crawdad:~/Downloads$ 
```

**Source code for testing:**
[https://raw.githubusercontent.com/emscripten-core/emscripten/main/test/other/embind_tsgen.cpp](https://raw.githubusercontent.com/emscripten-core/emscripten/main/test/other/embind_tsgen.cpp)

**Comment by brendandahl** [comment]
Can you try with the current main of emscripten? I recently added support for class properties in #19875

**Comment by Neirth** [comment]
Good afternoon @brendandahl, I tried with the content that was in master as of August 10, 2023. Both in the commercial project and in the replica that I could do with my computer. I understand that if it was merged a month ago, your patch should be present. Still, if you need me to repeat tests, no problem.

**Comment by Neirth** [comment]
I could test it with the commercial project actually, because I know that in the SDK it was already a few versions behind. In the one I have exposed the logs, it is a new virtual machine with the emsdk just installed ``emsdk install latest``, I understand that in this last case it should not fail under those conditions.

**Comment by sbc100** [comment]
You can also use `emsdk install tot` to get the very latest build of emsdk.

**Comment by Neirth** [comment]
Ok, I have been trying to install ``emsdk install tot`` with its corresponding activation. So far it's been going great. The problem I found when I wanted to use it with the combination of parameters ````-s EXPORT_ES6=1 -s USE_ES6_
IMPORT_META=0 -s MODULARIZE=1 -s ENVIRONMENT=web```` because it would be the case that I have in production and I have found the following problem: 

```
neirth@better-crawdad:~/Downloads$ emcc -lembind quick_example.cpp --embind-emit-tsd interface.d.ts -s EXPORT_ES6=1 -s USE_ES6_
IMPORT_META=0 -s MODULARIZE=1 -s ENVIRONMENT=web -o Module.js
(node:1636) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/neirth/Downloads/Module.js:2643
export default Module;
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1124:15)
    at Module._compile (node:internal/modules/cjs/loader:1160:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
emcc: error: '/home/neirth/.sdks/emsdk/node/16.20.0_64bit/bin/node Module.js' failed (returned 1)
neirth@better-crawdad:~/Downloads$
```

**Comment by sbc100** [comment]
I guess we should probably just ignore `-sMODULARIZE` when running with `--embind-emit-tsd`?

**Comment by sbc100** [comment]
My understanding is that when you run with `--embind-emit-tsd` the resulting JS file is not actually usable or interesting in any way.. its only purpose is to generate the TS bindings.

You would need to then re-link without `--embind-emit-tsd` to get a usable module.   So it don't think its really observable if we honor `-sMODULARIZE` or not internally when running with `--embind-emit-tsd`.  I could be misunderstanding though.

**Comment by sbc100** [comment]
Yes, there has yet to be a release that contains the fix.  You can try it out using `emsdk install tot` to install the tip-of-tree build of emsdk.

**Comment by frank-pian** [comment]
I'm using emsdk in an offline environment, so I can only use the built docker image : )
I tested 3.1.46, but still have the problem.
![1695033821027](https://github.com/emscripten-core/emscripten/assets/8214804/d943dfe6-05c8-4549-9ce4-837e5f0673da)
![1695033864707](https://github.com/emscripten-core/emscripten/assets/8214804/a2ffc079-28d8-4d65-aca6-3692820d5723)
Trying to close MODULARIZE.
![1695033959250](https://github.com/emscripten-core/emscripten/assets/8214804/61ba4df5-49d8-49a6-89fb-3b753a5b0719)
![1695034045127](https://github.com/emscripten-core/emscripten/assets/8214804/88547f49-9231-4bcc-83c0-73418aaf70ee)

**Comment by brendandahl** [comment]
Can you try adding `--experimental-wasm-eh` to your .emscripten configuration file to the NODE_JS option:
e.g.
```js
NODE_JS = ['/whever/your/node/is/node', '--experimental-wasm-eh']
```

**Comment by frank-pian** [comment]
> Can you try adding `--experimental-wasm-eh` to your .emscripten configuration file to the NODE_JS option: e.g.
> 
> ```js
> NODE_JS = ['/whever/your/node/is/node', '--experimental-wasm-eh']
> ```

yes, adding this parameter adds a few more error messages. The type file is generated, but the empty.
![1695104488491](https://github.com/emscripten-core/emscripten/assets/8214804/9562f5be-72bb-475f-b3f5-315245c3b580)

**Comment by brendandahl** [comment]
What about commenting out `-s -fwasm-exceptions` altogether? It seems the node version is not compatible with whatever emscripten is producing.

**Comment by frank-pian** [comment]
I tried turning off all the flags.
![图片](https://github.com/emscripten-core/emscripten/assets/8214804/50a4c158-7fd5-4c6a-8314-c076dd6cfa12)
![图片](https://github.com/emscripten-core/emscripten/assets/8214804/a202af70-d408-4d86-9d3b-6528929aa45f)

**Comment by sbc100** [comment]
> ```js
> NODE_JS
> ```

What version of node are you using?  Is the it version of node that comes with emsdk, or some other version?

**Comment by brendandahl** [comment]
Looks like it's node 16.20.0 from the second screen shot path.

Maybe something is going wrong with a binding. Can you try commenting out all of your `EMSCRIPTEN_BINDINGS` and running without any flags except the `--lembind --embind-emit-tsd inteface.d.ts`? If that runs without failing try commenting out different bindings within to `EMSCRIPTEN_BINDINGS` to see if one is causing an issue.

**Comment by frank-pian** [comment]
> > ```js
> > NODE_JS
> > ```
> 
> What version of node are you using? Is the it version of node that comes with emsdk, or some other version?

@sbc100 The node version is v16.20.0. I use emsdk's internal.





> Looks like it's node 16.20.0 from the second screen shot path.
> 
> Maybe something is going wrong with a binding. Can you try commenting out all of your `EMSCRIPTEN_BINDINGS` and running without any flags except the `--lembind --embind-emit-tsd inteface.d.ts`? If that runs without failing, try commenting out different bindings within to `EMSCRIPTEN_BINDINGS` to see if one is causing an issue.

@brendandahl OK, it looks like there are a lot of places that don't support. For example, the pointer vector.
![1695300861693](https://github.com/emscripten-core/emscripten/assets/8214804/849b2755-b867-4a01-943d-f1a2a5b99722)
![1695300953262](https://github.com/emscripten-core/emscripten/assets/8214804/edcc61ba-db97-45b8-bc5f-6fc3ffe8169b)

**Comment by brendandahl** [comment]
That looks like a different issue than the previous message of `TypeError: Cannot read properties of undefined`. The missing binding error is likely from not having a binding for the `DbLine` class. Embind will technically let you use register_vector without defining the binding for `DbLine` but you won't be able to do anything with the vector in JS e.g. if you try to do `vector_DbLine_ptr.get(x);` you'll get a similar error of `Uncaught BindingError: _emval_take_value has unknown type ...`.

When commenting out some of the bindings are you able to reproduce the error of `TypeError: Cannot read properties of undefined` and narrow it down to a single binding that causes that issue?

**Comment by frank-pian** [comment]
I went class by class and finally found the function that was causing the error.
![图片](https://github.com/emscripten-core/emscripten/assets/8214804/45119614-bdbc-4820-b6fc-f4b05a9fbeda)
![图片](https://github.com/emscripten-core/emscripten/assets/8214804/6ae2e4dc-7653-4aa6-b828-051da9359913)
![图片](https://github.com/emscripten-core/emscripten/assets/8214804/292a8ba4-8bd0-409c-90cc-41b9fe5e060c)

**Comment by frank-pian** [comment]
I found the cause of the problem, a static method was incorrectly bound with "function".
Because there is so much embind code, the whole troubleshooting process is very lengthy, and it would probably be easier to specify in the error message which line of embind code is at fault.
