### ISSUE TITLE
Some errors happend when emmake build fontconfig;

### ISSUE THREAD

**Issue by twabr** [emscripten-core/emscripten#20038]
I want to compile the fontconfig2.14.2 source code with emscripten,but there were some problems.
Firstly, When I download the source code to compile:
Execute the command:`emconfigure ./configure`
Error:no "freetype2" and  configure error : expat is required. or try to use --enable-libxml2
so,I compiled the freetype2.13.1.
Since the path cannot be found in the EMSDK environment, manually include the environment variables before running:
```
export FREETYPE_CFLAGS="-I/../tools/freetype-install/include"
export FREETYPE_LIBS="-L/../tools/freetype-install/lib -lfreetype"
export CFLAGS="-I/../tools/freetype-install/include/freetype2/"
export LIBXML2_CFLAGS="-I/usr/include/libxml2"
export LIBXML2_LIBS="-lxml2"
emconfigure ./configure --enable-libxml2
```
Normal execution, and then I execute `emmake make`.
Error:fatal error: 'unicode/ucnv.h! file not found
So I moved the unicode folder to /../include/freetype2/.

Then emmake make,Still an error:wasm-ld: error: unable to find library -lxml2.
You can consult the project file here : https://github.com/twabr/fontconfig.git

Of course I try to export expat, but it fail, 

```
checking for EXPAT... yes
checking for expat.h... yes
checking for XML_SetDoctypeDeclHandler... no
configure: error: 
*** expat is required. or try to use --enable-libxml2
```
otherwise, i try to set pkg-config, but it  didn't work I've heard that emscripten doesn't support pkg-config.
so i need some help.

**Comment by twabr** [comment]
I installed libxml2 with emscripten, executed the command: `emconfigure ./configure --with-sax1 --disable-shared --with-python=no,` 
enabled the sax1 function, checked config.log, and also showed WITH_SAX1='1',
 why use In the process of emscripten compiling fontconfig, an error is still reported: `checking SAX1 support in libxml2... configure: error:*** SAX1 support in libxml2 is required. enable it or use expat instead.`
and i try to use emscripten compile expat, error:`wasm-ld: error: unknown file type: element_declarations.o`;I feel that I need to use emscripten to compile this dependent library again, but I don't know what this library is

**Comment by twabr** [comment]
> 看起来您需要使用 emscripten 编译 libxml2 或 expat。您不能使用目录中的 libxml 系统版本`/usr`。



> It looks like you need to compile either libxml2 or expat using emscripten. You can't use the system version of libxml that lives in your `/usr` directory.

I installed libxml2 with emscripten, executed the command: emconfigure ./configure --with-sax1 --disable-shared --with-python=no,
enabled the sax1 function, checked config.log, and also showed WITH_SAX1='1',
why use In the process of emscripten compiling fontconfig, an error is still reported: checking SAX1 support in libxml2... configure: error:*** SAX1 support in libxml2 is required. enable it or use expat instead.
and i try to use emscripten compile expat, error:wasm-ld: error: unknown file type: element_declarations.o;I feel that I need to use emscripten to compile this dependent library again, but I don't know what this library is

**Comment by twabr** [comment]
> It looks like you need to compile either libxml2 or expat using emscripten. You can't use the system version of libxml that lives in your `/usr` directory.

I installed libxml2 with emscripten, executed the command: emconfigure ./configure --with-sax1 --disable-shared --with-python=no,
enabled the sax1 function, checked config.log, and also showed WITH_SAX1='1',
why use In the process of emscripten compiling fontconfig, an error is still reported: checking SAX1 support in libxml2... configure: error:*** SAX1 support in libxml2 is required. enable it or use expat instead.
and i try to use emscripten compile expat, error:wasm-ld: error: unknown file type: element_declarations.o;I feel that I need to use emscripten to compile this dependent library again, but I don't know what this library is

**Comment by twabr** [comment]
> It looks like you need to compile either libxml2 or expat using emscripten. You can't use the system version of libxml that lives in your `/usr` directory.
I built expat with emscripten, but an error was reported when executing emmake make：
 ```
 CC       fc-cache.o
  CCLD     fc-cache
emcc: warning: ignoring unsupported linker flag: `-rpath` [-Wlinkflags]
cache:INFO: generating system asset: symbol_lists/7b9009563f62d8ab6144e2c6d6a1f96c4b834abf.json... (this will be cached in "/home/wangyao/emsdk/upstream/emscripten/cache/symbol_lists/7b9009563f62d8ab6144e2c6d6a1f96c4b834abf.json" for subsequent builds)
cache:INFO:  - ok
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_MM_Var
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Sfnt_Table
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Sfnt_Name_Count
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Sfnt_Name
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Sfnt_Name
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Sfnt_Name
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Postscript_Name
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_Sfnt_Table
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_PS_Font_Info
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_BDF_Property
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_BDF_Property
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_BDF_Property
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_BDF_Property
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_BDF_Property
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Get_X11_Font_Format
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Done_MM_Var
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Done_MM_Var
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Load_Sfnt_Table
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Select_Charmap
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: FT_Select_Charmap
```

This should be a problem when I compiled fontconfig with emscripten,
```
Library configuration:
  external zlib: no
  bzip2:         no
  libpng:        no
  harfbuzz:      no
  brotli:        no
  pthread:       yes
```
So I want to know how to enable these libraries,When I execute emconfigure ./configure, I cannot directly add -s USE_ZLIB=1,-s USE_BZIP2=1....

**Comment by sbc100** [comment]
You can use the `embuilder` tool to build most of these libraries.  For example `./embuilder build zlib` will build and install zlib into the emscripten sysroot.    `./embuilder --help` will list all the possible targets.

**Comment by twabr** [comment]
> You can use the `embuilder` tool to build most of these libraries. For example `./embuilder build zlib` will build and install zlib into the emscripten sysroot. `./embuilder --help` will list all the possible targets.

i use ./embuilder build harfbuzz, and it succeed,whhy do I use emscripten to build fontconfig, and execute the `emmake make `error:
make[2]: 离开目录“/home/wangyao/tools/fontconfig/src”
Making all in fc-cache
make[2]: 进入目录“/home/wangyao/tools/fontconfig/fc-cache”
  CC       fc-cache.o
  CCLD     fc-cache
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_font_get_face
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_ot_tags_from_script_and_language
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_create
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_ot_layout_collect_lookups
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_is_empty
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_create
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_next
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_ot_layout_lookup_collect_glyphs
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_create
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_ot_layout_collect_lookups
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_create
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_next
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_ot_layout_lookup_collect_glyphs
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_next
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_ot_layout_lookup_would_substitute
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_subtract
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_next
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_destroy
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_destroy
wasm-ld: error: ../src/.libs/libfontconfig.so: undefined symbol: hb_set_destroy
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
emcc: error: '

**Comment by twabr** [comment]
There is another problem. I think two are similar. I have successfully installed ZLIB, Libpng ..., so when I use emscripeten to build FreeType, I execute Emconfigure:
`emcc libfreetype.a -o freetype_module.js -s WASM=1 -s EXPORTED_FUNCTIONS="['_FT_Init_FreeType']" -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' -lfreetype`
Error:
emcc: ```
warning: EXTRA_EXPORTED_RUNTIME_METHODS is deprecated, please use EXPORTED_RUNTIME_METHODS instead [-Wdeprecated]
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateInit2_
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateEnd
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateReset
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateEnd
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflate
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateInit2_
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflate
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateEnd
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftgzip.o): undefined symbol: inflateEnd
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftbzip2.o): undefined symbol: BZ2_bzDecompressInit
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftbzip2.o): undefined symbol: BZ2_bzDecompressEnd
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftbzip2.o): undefined symbol: BZ2_bzDecompressEnd
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftbzip2.o): undefined symbol: BZ2_bzDecompressInit
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(ftbzip2.o): undefined symbol: BZ2_bzDecompress
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(sfnt.o): undefined symbol: png_create_read_struct
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(sfnt.o): undefined symbol: png_create_info_struct
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(sfnt.o): undefined symbol: png_destroy_read_struct
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(sfnt.o): undefined symbol: png_set_longjmp_fn
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(sfnt.o): undefined symbol: png_set_read_fn
wasm-ld: error: /home/wangyao/tools/freetype-install/lib/libfreetype.a(sfnt.o): undefined symbol: png_read_info
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
```

Can't EMSCRIPEN pack the entire library file directly? What kind of library I lack, I would like to ask similar projects, thank you for helping

**Comment by twabr** [comment]
> You can use the `embuilder` tool to build most of these libraries. For example `./embuilder build zlib` will build and install zlib into the emscripten sysroot. `./embuilder --help` will list all the possible targets.

I used EMSDK to build FreeType. I wanted to verify its functions. I wrote a main.c file to execute the command:
```
emcc -I ./include -c main.c -o main.o
emcc -O3 --embed-file OCRA.otf --embed-file OCRB.otf -s NO_EXIT_RUNTIME=1 \
  -s EXPORTED_FUNCTIONS='["_main","_monochrome","_load_font","_find_font","_get_bitmap","_get_left","_get_top","_get_width","_get_height","_get_advance"]' \
  main.o ./libfreetype.a -o freetype.js -lz -lbz2 -lpng -lharfbuzz
```

Then in the browser verification function, report an error：
` Module.cwrap is not a function`，Can't find the corresponding function.Can you help me see this project?https://github.com/twabr/fontconfig.git

**Comment by twabr** [comment]
> You can use the `embuilder` tool to build most of these libraries. For example `./embuilder build zlib` will build and install zlib into the emscripten sysroot. `./embuilder --help` will list all the possible targets.

Do you know how to use the compiled fontconfig? There is too little information about this on the Internet. Do you have any relevant recommendations?

**Comment by twabr** [comment]
I execute the command：
```
emcc -O3 -s WASM=1 \
  -s EXPORTED_FUNCTIONS=_init_fontconfig,_find_font_path \
  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap \
  fontcons.o ./libfontconfig.a -o fontcons.js \
 -lfreetype -lexpat -lz -lbz2 -lpng -lharfbuzz -v
```
 ,The .js and .wasm files are generated, the files are called in html, and an error is reported:
` Fontconfig error: Cannot load default config file: No such file: (null),`
 I think this is because the path to the fonts.conf file cannot be found during initialization
