### ISSUE TITLE
Add support for C macros

### ISSUE THREAD

**Issue by andreasrosdal** [emscripten-core/emscripten#20064]
Hello, I am trying to compile the Freeciv C server using emscripten.

However, it fails because emscripten doesn't support macros. 

Source code:   https://github.com/freeciv/freeciv

So please add support for C macros to emscripten, so that I can compile the Freeciv C server.

**Comment by sbc100** [comment]
I'm not sure what you mean here.  Emscripten is a frontend for clang so we support any macros that clang does.  Perhaps you could elaborate on the precise failure you are seeing?
