### ISSUE TITLE
Is there any way to get detail information of Data section in wasm?

### ISSUE THREAD

**Issue by xbcnn** [emscripten-core/emscripten#20060]
I'd like to know:
1. How are they arranged by wasm-ld
2. Does it merge similar items like collecting all globals together
3. How to find the range of .rdata like literal strings, vtables, ...

Maybe there is some link option to dump this?

**Comment by sbc100** [comment]
You can get some basic information from `-Wl,--verbose`.  For exmaple:

```
$ emcc test/hello_world.c -Wl,--verbose
...
wasm-ld: mem: stack size  = 65536
wasm-ld: mem: stack base  = 0
wasm-ld: mem: stack top   = 65536
wasm-ld: mem: global base = 65536
wasm-ld: mem: .rodata         offset=65536    size=560      align=4
wasm-ld: mem: .data           offset=66096    size=148      align=3
wasm-ld: mem: .bss            offset=66256    size=1236     align=4
wasm-ld: mem: static data = 1956
wasm-ld: mem: total pages = 256
wasm-ld: mem: max pages   = 256
...
```

By default, as you can see data is grouped in three segments (rodata, data, bss).  If you want to keep each data symbol in its own segment you can link with `-Wl,--no-merge-data-segments` in which case you will see a lot more data segments (one per symbol).

On top of that you can use tools such as bloaty: https://github.com/google/bloaty, or twiggy https://rustwasm.github.io/twiggy to get more details.

**Comment by xbcnn** [comment]
Very instructive!  Thanks @sbc100

**Comment by xbcnn** [comment]
btw, why the .data segment is aligned with 3

```
wasm-ld: mem: .data           offset=66096    size=148      align=3
```

**Comment by sbc100** [comment]
It looks like it just takes the max aligned of any of the input segments that make comprise it: https://github.com/llvm/llvm-project/blob/f64eb69d962fb4e78961094354bd7a5d89471263/lld/wasm/OutputSegment.cpp#L21

**Comment by xbcnn** [comment]
Hi @sbc100, following is output of `wasm-objdump`.  It looks like the segments number is 5710.  Is that correct? 

```
Sections:

     Type start=0x0000000b end=0x000009b5 (size=0x000009aa) count: 281
   Import start=0x000009b8 end=0x00002326 (size=0x0000196e) count: 936
 Function start=0x0000232a end=0x00009e8a (size=0x00007b60) count: 31407
    Table start=0x00009e8c end=0x00009e95 (size=0x00000009) count: 1
   Global start=0x00009e97 end=0x00009ea0 (size=0x00000009) count: 1
   Export start=0x00009ea3 end=0x0000d5a1 (size=0x000036fe) count: 2018
     Elem start=0x0000d5a5 end=0x0001cfbe (size=0x0000fa19) count: 1
     Code start=0x0001cfc3 end=0x0111566c (size=0x010f86a9) count: 31407
     Data start=0x01115671 end=0x013256d0 (size=0x0021005f) count: **5710**
   Custom start=0x013256d4 end=0x013dc30a (size=0x000b6c36) "name"
   Custom start=0x013dc30c end=0x013dc33e (size=0x00000032) "external_debug_info"
   Custom start=0x013dc340 end=0x013dc35d (size=0x0000001d) "build_id"
```

**Comment by sbc100** [comment]
I guess so.  You can add `-x` to your `wasm-objdump` to see the actual segment data.

**Comment by sbc100** [comment]
(normally run `wasm-objdump` with `-d -r -x` to get all the information I can and then redirect this to a file).

**Comment by xbcnn** [comment]
I used to think that there should be normally 2 or 3 segments, if not used `-Wl,--no-merge-data-segments`, which is in most cases.

**Comment by sbc100** [comment]
Yes there should only be 2 or 3 segments unless you link with `-Wl,--no-merge-data-segments` .  Does does `-x` show?  Do you really have 5710 segments?

**Comment by xbcnn** [comment]
The .wasm file I used `wasm-objdump` is not mine and I don't think they are linked with `-Wl,--no-merge-data-segments` as it is using in web applications.  But it does have 5710 segments. See the -x details. 

```
Section Details:

Data[5710]:
 - segment[0] memory=0 size=468779 - init i32=1024
  - 0000400: c2bf 00c2 ba00 d0a6 d0bb d197 cf82 cf83  ................
...
...
- segment[5700] memory=0 size=9 - init i32=2681944
  - 028ec58: c8eb 2800 0000 0000 05                   ..(......
 - segment[5701] memory=0 size=2 - init i32=2681964
  - 028ec6c: 8b5f                                     ._
 - segment[5702] memory=0 size=14 - init i32=2681988
  - 028ec84: 885f 0000 8c5f 0000 38be 2c00 0004       ._..._..8.,...
 - segment[5703] memory=0 size=1 - init i32=2682012
  - 028ec9c: 01                                       .
 - segment[5704] memory=0 size=5 - init i32=2682028
  - 028ecac: ffff ffff 0a                             .....
 - segment[5705] memory=0 size=9 - init i32=2682096
  - 028ecf0: 60ec 2800 0000 0000 09                   `.(......
 - segment[5706] memory=0 size=2 - init i32=2682116
  - 028ed04: 8a5f                                     ._
 - segment[5707] memory=0 size=18 - init i32=2682136
  - 028ed18: 895f 0000 0000 0000 875f 0000 58c2 2c00  ._......._..X.,.
  - 028ed28: 0004                                     ..
 - segment[5708] memory=0 size=4 - init i32=2682180
  - 028ed44: ffff ffff                                ....
 - segment[5709] memory=0 size=2 - init i32=2682248
  - 028ed88: aa61                                     .a
```

**Comment by sbc100** [comment]
If the file was produced by wasm-ld and it has 5710 segments then it must have been linked with `-Wl,--no-merge-data-segments`.

Alternatively, it could be the product of a different toolchain, or maybe it as wasm object file and not the output of the linker?

**Comment by xbcnn** [comment]
Are you sure about this?   It's not wasm object file.  Actually it is Figma's wasm. You may download and check it here(https://static.figma.com/fullscreen/7668623c0f9fb990226d34d02c11d03539f62b0b/fullscreen-wasm/compiled_wasm.wasm.br)

**Comment by xbcnn** [comment]
Oh, I tested locally on a project by only adding `-Wl,--verbose`.  
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.1 (1934a98e709b57d3592b8272d3f1264a72c089e4)
$ wasm-ld --version
LLD 11.0.1
```

The outputs:

```
wasm-ld: mem: global base = 1024
wasm-ld: mem: .rodata         offset=1024     size=1292520  align=4
wasm-ld: mem: .data           offset=1293552  size=104156   align=4
wasm-ld: mem: em_js           offset=1397708  size=2771     align=0
wasm-ld: mem: em_asm          offset=1400479  size=442      align=0
wasm-ld: mem: .bss            offset=1400928  size=120052   align=4
...
wasm-ld: Data segment: size=1292520, startVA=400, name=.rodata
wasm-ld: Data segment: size=104156, startVA=13bcf0, name=.data
wasm-ld: Data segment: size=2771, startVA=1553cc, name=em_js
wasm-ld: Data segment: size=442, startVA=155e9f, name=em_asm
wasm-ld: createHeader: DATA body=1399926 total=1399930
```

Looks like it generates only 4 segments.  Then I use `wasm-objdump -h`, the output shows that there are 2227 data segments, which is not the expects.

```
     Type start=0x0000000b end=0x00000a81 (size=0x00000a76) count: 290
   Import start=0x00000a84 end=0x00002925 (size=0x00001ea1) count: 250
 Function start=0x00002929 end=0x00007cb0 (size=0x00005387) count: 21166
    Table start=0x00007cb2 end=0x00007cb9 (size=0x00000007) count: 1
   Memory start=0x00007cbb end=0x00007cc2 (size=0x00000007) count: 1
   Global start=0x00007cc4 end=0x00007ccd (size=0x00000009) count: 1
   Export start=0x00007cd0 end=0x0000800d (size=0x0000033d) count: 45
     Elem start=0x00008011 end=0x00010603 (size=0x000085f2) count: 1
     Code start=0x00010608 end=0x00bb9fc2 (size=0x00ba99ba) count: 21166
     Data start=0x00bb9fc6 end=0x00d05fac (size=0x0014bfe6) count: 2227
   Custom start=0x00d05fb1 end=0x00fc52b3 (size=0x002bf302) "name"
```

Why is that?

**Comment by sbc100** [comment]
The resulting file really does have 5710 data segments.  You can see them by looking at the output of `wasm-objdump -x`.

What is likely happening here is that `wasm-opt` (binaryen) is running as part of the post-link process and it is noticing that there are a lot zeros in your static data and deciding its more efficient to split it up into 5710 chunks of non-zeros with the assumption that the gaps between the segments well be zero filled automatically when the memory is created.

See https://github.com/WebAssembly/binaryen/blob/main/src/passes/MemoryPacking.cpp

**Comment by xbcnn** [comment]
Great!  This is totally reasonable.

BTW, can I explicitly disable Binaryen running in an O2+ build? And even more, just the specific pass.

**Comment by sbc100** [comment]
If you don't want to run wasm-opt at all I think you would need to drop the `-O2` from the link line.  You could still compile all your object files with `-O2` and link with `-sASSERTSION=0` so you wouldn't get the debug versions of the standard libraries.

If you want to control exactly what binaryen passes we run, the only thing we have today is `-sBINARYEN_EXTRA_PASSES`.. and that only adds more passes.   So we offer the kind of control you are asking for.

**Comment by sbc100** [comment]
(Can I ask why you don't want that pass run.. if there are downsides they might be shared with other folks).

**Comment by xbcnn** [comment]
> (Can I ask why you don't want that pass run.. if there are downsides they might be shared with other folks).

Oh, not really important.  I just wanted to do a convenient test if there were something like link options.  I have confirmed that with debug build(-g).

Anyway, Thanks.

**Comment by sbc100** [comment]
NP!  Glad to be of help
