### ISSUE TITLE
WebGPU support seems to be incompatible with -sWASM=0

### ISSUE THREAD

**Issue by dragostis** [emscripten-core/emscripten#20061]
Generating a JS file with `-sWASM=0 -sUSE_WEBGPU=1` generates a JS file that seems to depend on `webgpu.wasm`. Does this mean that WebGPU support works exclusively with the Wasm back-end? If so, there should at least be some warning that the JS file generated ends up using Wasm.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.44-git
clang version 17.0.0 (https://github.com/llvm/llvm-project.git a8cbd27d1f238e104a5d5ca345d93bc1f4d4ab1f)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
```bash
cd /tmp && \
git clone https://github.com/beaufortfrancois/webgpu-cross-platform-app && \
cd webgpu-cross-platform-app && \
em++ main.cpp -sWASM=0 -sUSE_WEBGPU=1 -sUSE_GLFW=3 -o webgpu.js && \
cat webgpu.js | grep webgpu.wasm
```

**Comment by sbc100** [comment]
No, the string `webgpu.wasm` does appear in the source code but the resulting JS file doesn't depend on WebAssembly.

For example:

```
$ emcc test/hello_world.c -sWASM=0 -o hello.js
$ grep hello.wasm hello.js 
  wasmBinaryFile = 'hello.wasm';
$ ls hello.wasm
ls: cannot access 'hello.wasm': No such file or directory
```

**Comment by dragostis** [comment]
Thanks you for the reply. I'll close the comment as it solves my issue completely.
