### ISSUE TITLE
instantiateStreaming not work , and the page crash

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#20092]
we emcc the ffmpeg in emscripten V3.1.42. and run the ffmpeg.js/ffmpeg.wasm in CEF(Chromium Embedded Framework) , and instantiateStreaming should return the promise, but it does not work , the page crashed .

before we emcc the ffmpeg in emscriptenV2.0.30 , it work well , but we update the emscripten , it does not work ?

**Comment by sbc100** [comment]
That's quite a large version range so its hard to narrow down what the issue might be.  One way to help would be bisect fo find out which the was the last version that did work for you.  See https://emscripten.org/docs/contributing/developers_guide.html#bisecting for how to do this.

**Comment by yangfangfang1204** [comment]
i find `emcc -O3 ffmpeg.js` , instantiateStreaming does not work  and the page crash . 
but if i set `emcc -O2 ffmpeg.js ` in emscriptenV3.1.42 , it work well
