### ISSUE TITLE
How should I export stringToNewUTF8

### ISSUE THREAD

**Issue by frank-pian** [emscripten-core/emscripten#20096]
I was using`EXPORTED_RUNTIME_METHODS=ccall,cwrap,stringToNewUTF8` or `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=$stringToNewUTF8` . It didn't work;

**Comment by sbc100** [comment]
`-sEXPORTED_RUNTIME_METHODS=ccall,cwrap,stringToNewUTF8` should work fine.  For example:

```
$ emcc test/hello_world.c -sEXPORTED_RUNTIME_METHODS=stringToNewUTF8 -o out.js
$ grep stringToNewUTF8 out.js 
var stringToNewUTF8 = (str) => {
Module['stringToNewUTF8'] = stringToNewUTF8;
```

Here you can see the function be declared and exported on the Module object.  Does this not work for you?  What version of emscripten are you using?

Indeed if you were to spell the name wrong you would see and error:

```
$ emcc test/hello_world.c -sEXPORTED_RUNTIME_METHODS=stringToNewUTF9 -o out.js
warning: invalid item in EXPORTED_RUNTIME_METHODS: stringToNewUTF9
emcc: warning: warnings in JS library compilation [-Wjs-compiler]
```
