### ISSUE TITLE
Cannot use ALLOW_MEMORY_GROWTH=1

### ISSUE THREAD

**Issue by c-dvl** [emscripten-core/emscripten#20106]
Hi!
I need to allow more memory to my wasm but the compilation fails when I add the `-s ALLOW_MEMORY_GROWTH=1` arg.

**Version of emscripten/emsdk:**
3.1.44

**Compilation**
`em++ src/main.cpp -o test.wasm -Iinclude/  -s ALLOW_MEMORY_GROWTH=1 -s  EXPORTED_FUNCTIONS=_stress --no-entry -s PURE_WASI=1`

**Runtime**
`wasmtime test.wasm --invoke stress < input_medium.json`

I have this error:
```
Error: failed to run main module `/home/****/test.wasm`
Caused by:
    0: failed to instantiate "/home/*****/test.wasm"
    1: unknown import: `env::emscripten_notify_memory_growth` has not been defined
```

Any help please?

Céline

**Comment by sbc100** [comment]
Yes, I guess we should probably not call `emscripten_notify_memory_growth` when `-sPURE_WASI` is used.

(BTW, you don't need the `=1` at the end of your `-s` settings since that is the default).

**Comment by c-dvl** [comment]
I still have the same error when removing the -sPURE_WASI arg

**Comment by sbc100** [comment]
I'm sorry, I should have been more clear.   `emscripten_notify_memory_growth` is and expected import, even in standalone mode.   However, we should probably not require it in `PURE_WASI` mode.  That is what #20112 done/  Once that lands it should fix your problem.
