### ISSUE TITLE
How to build "wasm_static_lib" with "minimal_build"?

### ISSUE THREAD

**Issue by Ucag** [emscripten-core/emscripten#20140]
I'm doing a project with onnxruntime-web with pure c++. 

I've tried minimal build with wasm, it works fine. However, when I build it with "--build_wasm_static_lib" the "libonnxruntime_webassembly.a" is too large (about 73M) which is not acceptable. It seems that minimal build not working for static lib. If I build with "--build_wasm", the size reduces to 1.2M. 

How can I reduce the size of "libonnxruntime_webassembly.a" when I offerring a config of ORT model.

**Comment by sbc100** [comment]
`libonnxruntime_webassembly.a` is a static library which is not something ship in production.  Instead you link against the static library when building and executable.

If you want to provide your library to others developers to link against the size is not normally an issue and the resulting executables will be a more reasonable size (e.g. 1.2M in your case).

**Comment by Ucag** [comment]
Actually, I tried to build the executable with "libonnxruntime.a", it is 12M instead of 1.2M (almost 10 times larger). This size is still too large for a web application. I want to reduce it to around 2MB.

**Comment by Ucag** [comment]
This is the wasm with minimal_build 
![image](https://github.com/emscripten-core/emscripten/assets/19625839/091c8711-0420-4071-a0d4-cb78fa152a7d)

**Comment by sbc100** [comment]
Can you share the link flags you using?     

If you want to small module you need to build with `-O2`, `-O3` or `-Oz`. and you want to avoid `-sMAIN_MODULE`  (if you need dynamic linking then `-sMAIN_MODULE=2` is better).

**Comment by Ucag** [comment]
My linking flags are:

```
        set(WASM_BUILD_FLAGS "\
        -s SINGLE_FILE=0 \
        -s EXPORT_ES6=0 \
        -s MODULARIZE=1 \
        -s EXPORT_NAME=createModule \
        -s NO_EXIT_RUNTIME=1 \
        -s ALLOW_MEMORY_GROWTH=1 \
        -s ENVIRONMENT=web \
        -s INVOKE_RUN=0 \
        -s INITIAL_MEMORY=52428800 \
        -s STACK_SIZE=655360 \
        -s EXPORTED_RUNTIME_METHODS=ccall,cwrap  \
        -s EXPORTED_FUNCTIONS=${WASM_EXPORTED_FUNCTIONS} \
        -O3")
    set_target_properties(clibwebsr PROPERTIES LINK_FLAGS "${WASM_BUILD_FLAGS}")
```

**Comment by sbc100** [comment]
I don't see anything in those link flags that would lead to a bloated binary, so perhaps you really do have 12mb of code in your wasm file that is needed/alive.  However that is very large amount so there is a chance something is not right here.    If your program really is that big there are some tools you can use to analysis the various code size costs such as bloaty and twiggy:   https://github.com/google/bloaty  https://github.com/rustwasm/twiggy

(BTW you can remove `NO_EXIT_RUNTIME=1`,  `SINGLE_FILE=0` and `EXPORT_ES6=0` since all of those are the default, and I would recommend removing the space between the `-s` and the name of the setting).

**Comment by Ucag** [comment]
Thanks for your reply. Actually, the c++ code I added is just some inference code with only one 3rd party dependence in 5.9kb. But the final wasm goes to 12MB, much bigger than "minimal_build". I wonder is there any way for me to manually check the cmake build graph or something like that. Thus, I can link the static lib with reduced size.

**Comment by sbc100** [comment]
If you want to find out why your binary is growing to 12MB then tools like bloaty and twiggy can help you.  You can also use tools like `wasm-objdump` (part of the wabt project) as part of that investigation.  

One you find out why C/C++ symbols are causing the code bloat you can use `-Wl,--trace-symbol=foo` at link time to find out why a given symbol is being included.

**Comment by Ucag** [comment]
Thanks, I'll try it.
