### ISSUE TITLE
CCache regression in Emscripten 3.1.43

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#20152]
Prior to the Emscripten 3.1.43 update we mostly got ccache hits:
```
cache hit rate                      91.61 %
```
After updating to Emscripten 3.1.43 but changing nothing else we mostly get cache misses:
```
cache hit rate                      0.21 %
```

I can provide more information as needed.

cc @juj since he maintains Emscripten Ccache. xref https://github.com/pyodide/pyodide/issues/4099

**Comment by juj** [comment]
I wonder if something may have changed in the flags that you are passing?

To debug ccache misses, one would need to reduce the build down to a single invocation that does not hit in the cache, and then examine the command line and the content hashes of the files to see what is different. I can't think off the top of my head what could have changed in Emscripten that would break ccaching - but I'd suspect some file contents being new on every build.

**Comment by hoodmane** [comment]
The pull request that caused the regression doesn't have may changes other than bumping the emscripten version:
https://github.com/pyodide/pyodide/commit/5db49494dd9675ca4ff7e1f8cbac7f1b8d3db31e

**Comment by hoodmane** [comment]
Closed since @ryanking13 says it's not an upstream issue.
