### ISSUE TITLE
EMTEST_SAVE_DIR is silently ignored when EMCC_DEBUG is not set

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#20155]
Running `set EMTEST_SAVE_DIR=1` is getting silently ignored when one has not set `EMCC_DEBUG`.

E.g.

```
set EMTEST_SAVE_DIR=1
emcc test\hello_world.c -o a.js --closure 1 -O3
```
does not generate output in `C:\Users\jukkaj\AppData\Local\Temp\emscripten_temp`. But setting

```
set EMTEST_SAVE_DIR=1
set EMCC_DEBUG=1
emcc test\hello_world.c -o a.js --closure 1 -O3
```
does. Did this behavior change at some point?

Also, I am using EMTEST_SAVE_DIR also when not running tests. I was under the impression that the `EMTEST_` environment variable names were only intended to have an effect for running the test suite? Though the old `EM_SAVE_DIR` feature was useful for debugging e.g. Closure compiler output, which currently does print warnings and errors for file contents that point to system temp directory, that vanish after the build so are unaccessible without setting EMTEST_SAVE_DIR .

**Comment by sbc100** [comment]
`EMTEST_SAVE_DIR` only relates to the test data, not the temporary files generated by emscripten.    

These files uses to live in `%TEMP/emscripten_test` (note, this is different to emscripten_temp).

However, I changed this to use `emscripten/out/test` to make them easier to access when working from the emscripten directory: #18562  My rational is that when running tests there is no need to use the system temp directory when the project/out directory works just fine. 

The `out/test` directory is also now always used by default when you run just a single test.

The `out/test` directory (if used) is never cleaned until the next test runs.

**Comment by sbc100** [comment]
If you want to save emscripten temp files you can instead use `EMCC_DEBUG_SAVE` which should work even without `EMCC_DEBUG` set.   `EMCC_DEBUG` does imply `EMCC_DEBUG_SAVE` though.

**Comment by sbc100** [comment]
Note that unlike `EMCC_DEBUG=1`,  `EMCC_DEBUG_SAVE=1` doesn't use the canonical temp directory (and therefore doesn't limit you to just a single job at a time).

emcc will print the location used on exit:

```
$ EMCC_DEBUG_SAVE=1 ./emcc ~/test/hello.c
not cleaning up temp files since in debug-save mode, see them in /tmp/emscripten_temp_25i5rsas
```
