### ISSUE TITLE
Issue when calling WebGPU's SetVertexBuffer without size parameter

### ISSUE THREAD

**Issue by kohakukun** [emscripten-core/emscripten#20167]
There seems to be issues converting the size parameter, either when setting it explicitly 
`renderPassEncoder.SetVertexBuffer(index, buffer, offset, WGPU_WHOLE_SIZE);`
or by skipping it:
`renderPassEncoder.SetVertexBuffer(index, buffer, offset);`

Presumably the issue happens because we are trying to convert an 64 unsigned into to javascript and values are overflown.

When inspecting the debugger, the size value is transformed into -1 when calling the corresponding emscripten function.
Other parameters seem to be correctly resolved, including the Buffer

```
 // size_low = -1 and size_high = -1
function _wgpuRenderPassEncoderSetVertexBuffer(passId, slot, bufferId, offset_low, offset_high, size_low, size_high) {
 passId >>>= 0;
 bufferId >>>= 0;
 var offset = convertI32PairToI53Checked(offset_low, offset_high);
 var size = convertI32PairToI53Checked(size_low, size_high);
 var pass = WebGPU.mgrRenderPassEncoder.get(passId);
 var buffer = WebGPU.mgrBuffer.get(bufferId);
 // size = -1
 pass["setVertexBuffer"](slot, buffer, offset, size);
}
```

which throws `Uncaught TypeError: Failed to execute 'setVertexBuffer' on 'GPURenderPassEncoder': Value is outside the 'unsigned long long' value range.`

This function call was correctly working in `3.1.33`

**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.45 (ef3e4e3b044de98e1811546e0bc605c65d3412f4)`

**Comment by kohakukun** [comment]
FYI @kainino0x

**Comment by kainino0x** [comment]
Looks like we're missing the special casing to catch `-1` and transform it into `undefined`, like so:
https://github.com/emscripten-core/emscripten/pull/19929

**Comment by kainino0x** [comment]
Fix opened in https://github.com/emscripten-core/emscripten/pull/20168
If you can test it locally please let me know if it works!

**Comment by kohakukun** [comment]
Works locally for my use case where I dont pass a value, not sure what is the expected behaviour if I pass something that will overflow like `WGPU_WHOLE_SIZE`.
