### ISSUE TITLE
[Embind] Cannot convert a BigInt value to a number with MAXIMUM_MEMORY=4294967296

### ISSUE THREAD

**Issue by Honry** [emscripten-core/emscripten#20185]
**Version of emscripten/emsdk:**
3.1.43+

**Failing command line in full:**
`emcc -O2 -Wall -Werror --bind -s WASM_BIGINT -s MAXIMUM_MEMORY=4294967296 -s ALLOW_MEMORY_GROWTH=1 -o val_example.html val_example.cc`

**Issue description**

This is a regression since emsdk 3.1.43, several Embind APIs, e.g. `val::object()`, `val::global("console")` and etc. throw error `Cannot convert a BigInt value to a number` when building behind `-s WASM_BIGINT -s MAXIMUM_MEMORY=4294967296`, while with 2GB maximum memory works (with flag `-s WASM_BIGINT -s MAXIMUM_MEMORY=2147483648`). 

Both  `MAXIMUM_MEMORY`  and `BIGINT` are related to wasm64. We suppose the real cause is that pointers are returned as 64bit which is not correct in wasm32.

Following is my code snippet. 

```
#include <emscripten/val.h>
#include <emscripten.h>
#include <stdio.h>
#include <math.h>
#include <unordered_map>


using namespace emscripten;

int main() {
  val console = val::global("console");
  console.call<void>("log", val("This is console log from val"));
  val b = val::object();
  const int64_t a = 1;
  b.set("int64_data", a);
  console.call<void>("log", a);
  console.call<void>("log", b);
  std::vector<int32_t> int32data = {1, 2, 3 ,4};
  std::vector<int64_t> int64data = {4, 5, 6, 7};
  val view32 = val{typed_memory_view(int32data.size(), int32data.data())};
  console.call<void>("log", view32);
  val view64 = val{typed_memory_view(int64data.size(), int64data.data())};
  console.call<void>("log", view64);
}
```

**Comment by Honry** [comment]
Similar issue in WebGPU: https://github.com/emscripten-core/emscripten/issues/20183.

**Comment by kripken** [comment]
Perhaps related to @sbc100 's recent work on 4GB mode?

@Honry can you provide a testcase? Either that or [bisection](https://emscripten.org/docs/contributing/developers_guide.html#bisecting) could help speed this up a lot.

**Comment by Honry** [comment]
@kripken, what kind of testcase do you want?

The code snippet in my issue description is exactly the testcase I used, you can just paste it to a file named e.g. `val_example.cc`, then build with emsdk 3.1.43 via following command:

`emcc -O2 -Wall -Werror --bind -s WASM_BIGINT -s MAXIMUM_MEMORY=4294967296 -s ALLOW_MEMORY_GROWTH=1 -o val_example.html val_example.cc`

It will generate a `val_example.html` file, then you should set up a http-server to access the `val_example.html` on browser, you will see the error `Cannot convert a BigInt value to a number` in the Console of the Developer Tools.

This issue regresses from 3.1.43, i.e. 3.1.42 works, how to bisect the adjacent release versions?

**Comment by sbc100** [comment]
I verified that this issue was fixed in my recent changes on top of tree.   @Honry, can you test with `emsdk install tot` ?   We should make a 3.1.46 release soon that will include the fix.

**Comment by kripken** [comment]
> how to bisect the adjacent release versions?

@Honry Sounds like it's not necessary now, but for the future, there is info about that in the link I gave before, which is

https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by Honry** [comment]
Thanks @sbc100, @kripken, I've verified the latest build, the issue should be fixed. Let's close this issue.

**Comment by jspanchu** [comment]
> I verified that this issue was fixed in my recent changes on top of tree. @Honry, can you test with `emsdk install tot` ? We should make a 3.1.46 release soon that will include the fix.

One of our [VTK](https://vtk.org/) users runs into this issue and it's fixed by `emsdk install tot`. I know many things are in flux. We're curious if there is a timeline for 3.1.46?

Thanks.

**Comment by sbc100** [comment]
I'll try to cut the 3.1.46 release today.

**Comment by sbc100** [comment]
> I'll try to cut the 3.1.46 release today.

Done
