### ISSUE TITLE
Uncaught TypeError: Failed to construct 'URL'

### ISSUE THREAD

**Issue by slavek-kucera** [emscripten-core/emscripten#20190]
When the `mainScriptUrlOrBlob` is a Data URL and `EXPORT_ES6`, `USE_PTHREADS` are enabled, the following code
https://github.com/emscripten-core/emscripten/blob/0566a76b500bd2bbd535e108f657fce1db7f6f75/src/preamble.js#L638C58-L638C58
produces exception `Uncaught TypeError: Failed to construct 'URL'`

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.33 (c1927f22708aa9a26a5956bab61de083e8d3e463)
clang version 17.0.0 (https://github.com/llvm/llvm-project 671eeece457f6a5da7489f7b48f7afae55327b8b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /emsdk/upstream/bin

**Comment by sbc100** [comment]
Is there any chance you could share a full failing example?

**Comment by slavek-kucera** [comment]
So I eventually managed to create a small project:
main.cpp:
```
int main(){ }
```
build command:
```
em++ -o main.mjs -s EXPORT_ES6=1 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1 main.cpp
```
run.html:
```
<html>
    <head>
        <script>
            function onLoad() {
                console.log('crossOriginIsolated', crossOriginIsolated);
                const worker = new Worker('./worker.script.js');
            }
        </script>
    </head>
    <body onload="onLoad()"/>
</html>
```
worker.script.js (this replicates the original conditions):
```
console.log('crossOriginIsolated', crossOriginIsolated);
const asDataUri = (x) => new Promise((resolve, reject) => {
    const filereader = new FileReader();
    filereader.onload = (e) => typeof e.target?.result === 'string' ? resolve(e.target.result) : reject(Error('fail'));
    filereader.readAsDataURL(x);
});

Promise.all(['main.mjs', 'main.wasm', 'main.worker.js'].map(f => fetch(new URL(f, self.location.href)).then(x => x.blob()))).then(([main_blob, wasm_blob, worker_blob]) => {
    asDataUri(main_blob).then(main_text => import(main_text).then(m => m.default({
        mainScriptUrlOrBlob: main_text,
        locateFile(path) {
            if (typeof path !== 'string') return path;
            if (path.endsWith(".wasm")) {
                return URL.createObjectURL(wasm_blob);
            }
            else if (path.endsWith(".worker.js")) {
                return URL.createObjectURL(worker_blob);
            }
            return path;
        },
    })))
});
```
server.js (headers needed to ensure crossOriginIsolated is true):
```
const express = require('express');
const app = express();

// Setting up the public directory
app.use(express.static(__dirname, {
  setHeaders: (res) => {
    res.set("Access-Control-Allow-Origin", "*");
    res.set("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    res.set('Cross-Origin-Opener-Policy', 'same-origin');
    res.set('Cross-Origin-Embedder-Policy', 'require-corp');
  }
}));

app.listen(3000, () => console.log('listening on port 3000!'));
```

I hotfixed the problem essentially by replacing https://github.com/emscripten-core/emscripten/blob/0566a76b500bd2bbd535e108f657fce1db7f6f75/src/preamble.js#L631 condition with `} else if(!Module["wasmModule"]) {` since the module should be incoming in the posted message.

**Comment by sbc100** [comment]
Is this still an issue for you?   A few things have changed in the last year WRT to how this stuff works.

I was able to reproduce the issue a similar issue but when trying to construct the a URL for the the pthread worker js (these days we just use the main script in the pthread worker and `main.worker.js` no longer exists).

Is there some reason you need to import the main mjs file as a data URL?   I.e. Do you need to use `import(main_text)` and not `import("./main.mjs")`.  It looks like we don't currently support the main mjs file being a data URL (in the case of pthreads anyway).

**Comment by slavek-kucera** [comment]
With the removal of `main.worker.js` I no longer need to do all these workarounds.
