### ISSUE TITLE
Function signature mismatch: time issue

### ISSUE THREAD

**Issue by starlord2826** [emscripten-core/emscripten#20233]
Hi all. I am using emsdk version 3.1.45 to build a C++ project and consume it in our javascript project. The C++ project inturn uses openssl library. Whenever I try to generate the wasm files, I get the following warning.

``` 
wasm-ld: warning: function signature mismatch: time
>>> defined as (i32) -> i32 in {ROOTDIR}\/openssl-3-wasm/libdtlschromeos.a(libdtlschromeos-lib-sslsdk_trace.o)
>>> defined as (i32) -> i64 in {ROOTDIR}\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libc-mt-debug.a(emscripten_time.o) 
```

I am new to emscripten. So, wanted to know how I can resolve this issue.

This seems to be causing an issue in our main project which is consuming the generated wasm files. Whenever we are tring to initialize DTLS, we are getting signature mismatch: time in the logs and it looks like emscripten is adding unreachable in this code path.

**Comment by sbc100** [comment]
It looks like `libdtlschromeos.a` needs to be rebuilt as the type of `time_t` changed in recent versions of emscripten.   I recommend rebuilding all your libraries every time you update emscripten/emsdk.

**Comment by starlord2826** [comment]
That worked! Thank you @sbc100 !
