### ISSUE TITLE
Using AES intrinscis

### ISSUE THREAD

**Issue by tbuchs** [emscripten-core/emscripten#20244]
I am trying to compile a C++ project which uses different SSE intrinsics. I have added the correspoding flags and header files. It worked great for SSE2/4. However I have also a file containing AES instructions and therefore wanted to include the header file "wmmintrin.h" and the corresponding compile flags "-maes" and "-mpclmul".

`clang++: error: unsupported option '-maes' for target 'wasm32-unknown-emscripten'`
`clang++: error: unsupported option '-mpclmul' for target 'wasm32-unknown-emscripten'`
`emcc: error: '/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN --sysroot=/emsdk/upstream/emscripten/cache/sysroot -D__SSE__=1 -D__SSE2__=1 -D__SSE3__=1 -D__SSSE3__=1 -D__SSE4_1__=1 -D__SSE4_2__=1 -D__AVX__=1 -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -I./local/include -maes -mpclmul -msimd128 -g3 -Wextra -Wall -O3 -I. -I./deps -pthread -DUSE_GF2N_LONG -Werror -std=c++17 -fPIC -MMD -MP -c -matomics -mbulk-memory Data.cpp -o Data.o'`

**Comment by sbc100** [comment]
I'm guessing this is simply not supported.  @tlively will know for sure.

**Comment by tlively** [comment]
No, there is no way to use PCMUL or AES intrinsics with Emscripten. There are no plans to implement them, because there is no high-performance way to lower them to WebAssembly AFAIK. All of the SIMD intrinsics we support are documented here: https://emscripten.org/docs/porting/simd.html.
