### ISSUE TITLE
Emscripten crashes/freezes after switching tabs

### ISSUE THREAD

**Issue by Xevion** [emscripten-core/emscripten#20247]
Hi,

**Please don't close my issue.**

I know my setup is unusual, but I'm at a complete diagnostic dead end. Nothing I have searched or researched has presented hints or potential solutions. I have contacted other authors, but none of them are responding to me at this point. This is my last resort.

I am building a Pac-Man clone in Rust + SDL2 + Emscripten for a WASM build (SDL2 is C++, so I need Emscripten). Builds are working flawlessly through CI.

My issue is that when my game starts, it works and loops fine - as long as I stay on the tab. If I switch tabs for more than 1 second, the tab freezes when I come back to it. I believe it is Emscripten's javascript. My program will continue running in the background normally, although it is very slow and cannot receive inputs or render to the canvas.

- Firefox notices the script doing something weird and suggests stopping or debugging the script - pressing Debug lets me skip to whatever line it is on. It usually emscripten's `_sleep` function. I don't immediately notice anything wrong with the arguments.
- Pressing continue resumes the script, and the **game resumes normally.** Somehow, the script gets out of whatever loop it's stuck on.
- If I do nothing, the script never seems to resume. It also lags the browser unrelentingly. I have only let it try for around 60 seconds, so perhaps after several minutes it would resolve - I do not know yet.

You can try it out online (early versions of the project; please don't judge): https://pacman.xevion.dev

### What have I tried

- I've been studying the game loop for a similarly structured project; RuggRogue (I have already emailed the developer, no response).
  - At this time, while our projects are in very different stages, it does not yet appear he is processing events that much differently. Our versions are similar, and the extensive documentation he has written does not talk about the window hiding event, special sleep methods, crashing/freezing, or special emscripten logic.
  - I am building Emscripten in the same way, more or less. All my scripts are based on RuggRogue.
- I've tried adding traces to see if the game is freezing or taking long in any way. Weirdly enough, while the script freezes, the WASM program and console output DOES NOT. It is only the canvas that is behind. My program runs fine. This suggests that it isn't my code doing something wrong.
- I've searched everything I can think of relating to freezing, crashing, window events, usleep, emscripten and Rust, SDL2 and Rust, switching/changing/leaving tabs, and emscripten loops.
- I've emailed all developers involved with Rust + Emscripten and scoured the internet for documentation. I'm stuck.

#### References

- [Source Code](https://github.com/Xevion/Pac-Man) for Pac-Man
- [Live Deployment](https://pacman.xevion.dev) for Pac-Man
- [RuggRogue](https://tung.github.io/ruggrogue/) ([source](https://github.com/tung/ruggrogue/))
- [RuggRogue Development Book](https://tung.github.io/ruggrogue/source-code-guide/)
- [A Guide to Rust + SDL2 + Emscripten](https://web.archive.org/web/20210618192808/https://blog.therocode.net/2020/10/a-guide-to-rust-sdl2-emscripten)

#### Notes

I am running `emcc` 1.39.20, as that is the only version of Emscripten that works for me at this time. It's documented in "A Guide to Rust + SDL2 + Emscripten" (above).

**Comment by floooh** [comment]
Can't help much since I'm using a much simpler frame loop setup (`emscripten_request_animation_frame`: https://emscripten.org/docs/api_reference/html5.h.html#c.emscripten_request_animation_frame), but one thing you need to be aware of is that browser will deactivate your application when the tab is in the background (e.g. the app will essentially be "frozen" until the tab switches to the foreground again).

And looking at your timing code, it looks like it could get out of what if there's suddenly a "frame" that takes many seconds or even a minute.

In any case, this is almost definitely not an Emscripten problem, but a code structure problem :)

(for an example, check my Pacman clone written in C, and note how it "stops" when the tab is switched into the background and back into the foreground again. This is because the browser doesn't call the request-animation-frame callback while the tab is "suspended": https://floooh.github.io/pacman.c/pacman.html.

**Comment by Xevion** [comment]
Interesting; I had my suspicions that it was a timing issue, but I unfortunately had no proof yet. Also, since the game loop seemed to work fine behind the scenes, I had no reason to suspect the loop wasn't running... I took a break from the project to work on stuff for my org, but my next plan for figuring it out was to create a minimal example of the issue - the least amount of code that can reproduce the issue.

Given that the RuggRogue project doesn't have the issue, I narrowed it down to it likely being something unique to my project:
- Rust version
- Crate versions
- SDL2 Features
- Emscripten build environment (not version, though)

Also, I'm fairly sure that I disabled the sleep timing mechanisms in a build and it *did not* change the issue - it still froze. I'll look into if there's a way for me to hook the `emscripten_request_animation_frame` thing, or however it works - but so far I'm only familiar with using `main` as my loop mechanism.

---

Also, very cool Pacman clone - feels like the more I talk about it, the more people come out of the woodwork to show their stuff. It's inspiring me to take more liberties with my version of the game, and try less on creating a "perfectly faithful" or "optimized" version, and instead create one with features, clean code, and one that uses can crack open and see verbose diagnostics.

**Comment by Xevion** [comment]
@floooh This was a pretty frustrating problem at the time, and it still is. I took a long break, several months, but returned to see if I could crack it.

Unfortunately, I'm still stuck, but I developed a very stripped down repostiory and example, as well as narrowed it down to the Window being hidden. It's less 'laggy' when it freezes, but the script is still stuck in a loop.

[Repository](https://github.com/Xevion/rust-sdl2-emscripten), [Example](https://xevion.github.io/rust-sdl2-emscripten/)

The code is very much stripped, so even if you don't know Rust, it shouldn't be hard to use, or even iterate on if you fork it (automatic builds with GitHub Actions means no compiling on your side is necessary).

Please help, if I don't fix this issue, my project is dead for good this time. Very few people work on Rust + SDL2/Emscripten.

**Comment by curiousdannii** [comment]
Are you still using Emscripten 1.39.20? That's almost 4 years old, you really need to update. Unfortunately no one is likely to put in any time to diagnose this issue when there's a pretty good chance that it's been fixed since then.

**Comment by Xevion** [comment]
> fortunately no one is likely to put in any time to diagnose this issue when there's a pretty good chance that it's been fixed

Hmm, so, interesting sequence of events:
- I tried building with latest tag of emsdk, compiled, but the program does not function (SDL 'Shown' event, and then freezes like usual).
- I looked into more examples by some people online and found a repo with a latest target, and IT WORKS. Which is awesome. No freezing, Linux + Emscripten (latest) builds.
- I have to investigate whether or not SDL2 is fully workable in this realm. I'll have to try and port it over and stuff. But this is a really good start.

Also, the reason for targeting 1.39.20 is because of RuggRogue documentation stating that it was all that works.  If you can't tell, I'm out of my depth here.

Regardless, I have something new to try; I'm mostly worried that SDL2 images and/or audio mixing won't work, or some other annoying issue will appear.

**Comment by Xevion** [comment]
I'm going to close this thread as I no longer think that the issues for Emscripten crashing or freezing are relevant; they may be solved as a result of updating, or they may be solved because I'm no longer depending on `std::thread::sleep` while using Asyncify.

If anyone comes across this while developing for Rust+SDL2, I have a couple of tips:

- Look at examples online. GitHub has [a search feature](https://github.com/search) you can use, you can also press **S** while inside a repository and it'll bring up a local search within it. Fantastic for finding domain-specific functions or calls, usually it shows relevantly updated or useful examples in real-world applications. Make sure to use the language filter for Rust. It's been indispensable for solving all my problems.

- Learn about Asyncify, Emscriptem's Main Loop Callback, and how to Sleep/Get Timings for FPS management. Make sure you're on the latest EMSDK (although, SDL2 TTF refused to work on WASM unless I was on 3.1.43). Before trying to work on your project, confirm that you have working access to all the features you need to use.

- Check out my repositories; they contain some decent resources, links to more repos, examples, and should be working well for the relative future. [rust-sdl2-emscripten](https://github.com/Xevion/rust-sdl2-emscripten) [Pac-Man](https://github.com/Xevion/Pac-Man)
