### ISSUE TITLE
Set up default signal handlers

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20254]
(Raising for tracking purposes after a short discussion.)

Emscripten has basic support for raising signals and handling them within the same process. However, default signal handlers are normally processed by the OS and Emscripten currently doesn't emulate them, so they do nothing and only handlers explicitly set by the user are invoked.

Example:

```c
#include <signal.h>
#include <stdio.h>

int main() {
	printf("foo\n");
	raise(SIGINT);
	printf("bar\n");
}
```

In native executable, the program would stop after printing "foo", but in Emscripten-compiled code it will keep going.

We should set default handlers at least for signals that are meant to gracefully exit or abort the app as these are most common and relatively trivial to implement.

**Comment by sbc100** [comment]
Sounds like a good idea.

As a temporary workaround perhaps you could somehow inject your down default handlers on startup.  e.g. using static constructors or some kind of other startup hook?

**Comment by RReverser** [comment]
> As a temporary workaround perhaps you could somehow inject your down default handlers on startup. e.g. using static constructors or some kind of other startup hook?

Yeah I could do that if I had control over the C code, but in current scenario I'm working on a JS library that you can pass via `--js-library` when linking arbitrary programs.

In principle it might be still possible by combining `stackAlloc`, `addAtInit` and so on, or by providing yet another library user should link with their program, but one way or another more cumbersome than if those handlers were assigned by Emscripten.

**Comment by sbc100** [comment]
I think `addAtInit` could work yes.   But also the PR to fix this issue is probably fairly straight forward.

**Comment by RReverser** [comment]
Also not sure if it's okay that `signal` will return pointer to those default handlers or it needs to be integrated somehow differently.

**Comment by sbc100** [comment]
I think sigaction should return `SIG_DFL` when there is no user action set.

I think the default actions should probably be defined in `system/lib/libc/raise.c`.

**Comment by sbc100** [comment]
See the check for `__sig_actions[sig].sa_handler == SIG_DFL` in that file.. that is where the default actions should be triggered I think.

**Comment by RReverser** [comment]
Good point.

**Comment by RReverser** [comment]
> I'm just not 100% sure if the default handlers can really just call `abort` & `exit` or whether I'm missing some more details on their behaviour.

One correction: since `abort` raises `SIGABRT` signal itself, I can't use it in the handler. I'll use `__builtin_unreachable` instead since it's closest to simulating abnormal termination.

**Comment by sbc100** [comment]
> > I'm just not 100% sure if the default handlers can really just call `abort` & `exit` or whether I'm missing some more details on their behaviour.
> 
> One correction: since `abort` raises `SIGABRT` signal itself, I can't use it in the handler. I'll use `__builtin_unreachable` instead since it's closest to simulating abnormal termination.

I'm not sure that is true.  We don't compile musl's abort (`./system/lib/libc/musl/src/exit/abort.c`), but instead implement in JS I believe: https://github.com/emscripten-core/emscripten/blob/a5e071037f937315c225a00fe072cfaa3bf83d05/src/preamble.js#L438

We could possibly change that once we have the default handler for `SIGABRT` but that seems like a separate issue/PR.

**Comment by RReverser** [comment]
Ah, good to know. I only looked up default behaviour of `abort` and the one in `abort.c`. I think it's still better to be more standard-compliant / future-proof here.
