### ISSUE TITLE
Weird __proxy stripping for arrow functions

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20264]
Please include the following in your bug report:

**Version of emscripten/emsdk:**

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46-git (19607820c447a13fd8d0b7680c56148427d6e1b8)
clang version 18.0.0 (https://github.com/llvm/llvm-project d2ab97b00ce702006f7b1098e3530094759c8841)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/rreverser/emsdk/upstream/bin
```

**Failing command line in full:**

```bash
emcc test.c --js-library test-lib.js -pthread -s PROXY_TO_PTHREAD
```

`test.c`:

```c
extern void foobar();

int main() {
	foobar();
}
```

`test-lib.js`:

```js
addToLibrary({
	foobar: () => setTimeout(() => {
		console.log('hello from main thread');
	}, 1000),
	foobar__proxy: 'sync',
});
```

For some reason arrow functions wrapped like this (whether it's `setTimeout`, `Asyncify.handleSleep` or anything else) get quietly unwrapped in the output so it becomes:

```js
  function _foobar() {
  if (ENVIRONMENT_IS_PTHREAD)
    return proxyToMainThread(4, 1);
  
  		console.log('hello from main thread');
  	
  }
```

Which, of course, behaves very differently in weird ways in runtime.

**Comment by sbc100** [comment]
Yes, there is some fairly gross logic in the `modifyJSFunction` helper .. I imagine there is a bug in there.  Thanks for the report.

**Comment by RReverser** [comment]
Oh wow just looked and saw that it parses JS with a regex not Acorn or something 😬

**Comment by sbc100** [comment]
I have a fix.. just testing it now.
