### ISSUE TITLE
404s for console.h in the documentation at emscripten.org

### ISSUE THREAD

**Issue by ntoll** [emscripten-core/emscripten#20288]
Visit emscripten.org, click through to docs, then API reference and finally click the menu link for `console.h`. The URL looks good (https://emscripten.org/docs/api_reference/console.h.html) but returns a 404. I presume the missing file is supposed to be created via https://github.com/emscripten-core/emscripten/blob/main/site/source/docs/api_reference/console.h.rst..?

Perhaps rebuild and check all the assets are in place..?

**Comment by kripken** [comment]
Thanks! Yes, this is a file that was added at some point to the `site/` docs but we forgot to `git add` it to the docs repo after the build. Fixed now.
