### ISSUE TITLE
embind: TypeScript generation fails `error: undefined symbol: free `

### ISSUE THREAD

**Issue by brendandahl** [emscripten-core/emscripten#20297]
main.cpp
```cpp
#include <emscripten/bind.h>

using namespace emscripten;

int global_fn(int, int) { return 0; }

EMSCRIPTEN_BINDINGS(Test) {
  function("global_fn", &global_fn);
}
```
compiling with:
```
emcc main.cpp -lembind --embind-emit-tsd a.out.d.ts
```
errors with:
```
error: undefined symbol: free (referenced by $getTypeName, referenced by $embindEmitTypes, referenced by root reference (e.g. compiled C/C++ code))
```
even though getTypeName has: `$getTypeName__deps: ['$readLatin1String', '__getTypeName', 'free'],`

**Comment by brendandahl** [comment]
@sbc100 I thought there was a linker fix for this already, but it still seems to be an issue with emsdk tot.

**Comment by sbc100** [comment]
Hmm, yes, it looks like symbols that are only needed due to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` might still not be working correctly. 

I thought I fixed that but maybe it never landed.

**Comment by sbc100** [comment]
Yes this should have been fixed in #19843.. but I guess maybe you are adding to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` at a later point so its not being picked up.  Checking..

**Comment by sbc100** [comment]
Yup we handle it here: https://github.com/emscripten-core/emscripten/blob/a322be5cca6ecfe73dacce41e5f54b2b29f2419d/emcc.py#L1328-L1329

And here `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` won't include the additions made to it in `src/embind/embind_ts.js`.

I'm struggling to think of a simple solution to this problem... maybe its such a niche case that we just move that addition to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` to somewhere else...

**Comment by sbc100** [comment]
I think I have a fix.
