### ISSUE TITLE
-sSIDE_MODULE=2 doesn't hide all unexported code 

### ISSUE THREAD

**Issue by junyuecao** [emscripten-core/emscripten#20300]
The wasm-ld prams with EMCC_DEBUG=1
```
-o
/media/junyuecao/work/project/libsidemodule.wasm
/tmp/emscripten_temp/empty_0.o
-L/media/junyuecao/work/project/lib
/media/junyuecao/work/projects/libsidemodule.a
--error-limit=0
--no-check-features
-L/home/junyuecao/Soft/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto-pic
/home/junyuecao/Soft/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto-pic/crtbegin.o
-mllvm
-combiner-global-alias-analysis=false
-mllvm
-wasm-enable-sjlj
-mllvm
-disable-lsr
-mllvm
-wasm-enable-eh
-mllvm
-exception-model=wasm
--allow-undefined-file=/tmp/emscripten_temp/tmpd66gzukd.undefined
--import-memory
--shared-memory
--export-if-defined=my_func1
--export-if-defined=my_func2
....other exports
--export=__wasm_call_ctors
--experimental-pic
-shared
--no-export-dynamic
```
But the output wasm exported with many other functions that is not listed in the wasm-ld command.

Is there some params that I missed for linking the side module?

emcc.py -o /media/junyuecao/work/project/libsidemodule.wasm /media/junyuecao/work/projec/empty.cpp -L/media/junyuecao/work/project/libs/ -lsidemodule -sEXPORTED_RUNTIME_METHODS='["ccall","cwrap","allocate","removeFunction","addFunction","intArrayFromString","intArrayToString","ALLOC_NORMAL","UTF8ToString","FS","PATH","writeArrayToMemory"]' -sEXPORTED_FUNCTIONS=@/media/junyuecao/work/project/ExportFunctions.txt -Wl,--error-limit=0 -sSIDE_MODULE=2 -sAUTOLOAD_DYLIBS=0 -sLEGACY_RUNTIME -Wno-deprecated -Wno-pthreads-mem-growth -Wno-keyword-macro -Wno-unused-command-line-argument -Wno-int-conversion -Wno-error=unused-but-set-variable -Wno-error=bitwise-instead-of-logical -s WASM=1 -s WASMFS=1 -s ENVIRONMENT=web,worker -s USE_PTHREADS=1 -s FULL_ES2=1 -s FULL_ES3=1 -s FORCE_FILESYSTEM=1 -s WARN_ON_UNDEFINED_SYMBOLS=1 -s WASM_MEM_MAX=1073741824 -s TOTAL_MEMORY=1073741824 -s INITIAL_MEMORY=67108864 -s ALLOW_MEMORY_GROWTH=1 -s FETCH=1 -s RESERVED_FUNCTION_POINTERS=10 -s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORT_NAME='createModule' -frtti -fPIC -DENABLE_WASM_SIMD=ON -msimd128 -mbulk-memory -fwasm-exceptions -sSUPPORT_LONGJMP=wasm  -lopenal -lembind -D__linux__=1 -Wl,--no-check-features -Wno-experimental -s PTHREAD_POOL_SIZE=20 -Oz -g0 -DNDEBUG -sWASM_BIGINT --emit-symbol-map -flto -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -sEXCEPTION_STACK_TRACES -s OFFSCREENCANVAS_SUPPORT=1 -s OFFSCREENCANVASES_TO_PTHREAD='#canvas'

**Comment by sbc100** [comment]
This could be related to symbol visibility.  Can you try rebuilding all the side modules sources with `-fvisibility=hidden`?

**Comment by junyuecao** [comment]
@sbc100 That works for me. I thought there were some link-time machanisms to eliminate dead code for a shared library.  If not so then I just add `-fvisibility=hidden` for all sources.
