### ISSUE TITLE
Invalid handling of shorthand methods in JS libraries

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20314]
Example:

```js
addToLibrary({
	foo: () => {
		console.log('Hello, world!');
	},

	bar() {
		console.log('Hello, world!');
	}
});
```

during compilation gets transformed into:

```js
...
  bar() {
  		console.log('Hello, world!');
  	}

  var _foo = () => {
  		console.log('Hello, world!');
  	};
...
```

So, `foo` is correctly inlined as an arrow function, but `bar` results in an invalid JS syntax as it's stringified as-is. Both should result in valid code as shorthand syntax is pretty convenient for multiline functions. For that, shorthand methods need to be somehow detected and prepended with `function`.

**Comment by sbc100** [comment]
Do we need/want to support this though?   

These are fundamentally not methods here, but free functions in an object literal.

**Comment by sbc100** [comment]
But since JS library files a kind of like a DSL why not just mandate one style.. there is no advantage to switching or using two different styles is there?

**Comment by RReverser** [comment]
Main advantage is somewhat cleaner library code, otherwise they're equal. I was mainly caught by this when writing my own JS library and was surprised that output is silently broken.

I agree codestyle-wise it might be worth sticking to a single style (even though I visually prefer this one as it has less punctuation, but it's a matter of taste), but it still seems kinda bad that the tool silently emits broken JS code for anyone who tries to use such syntax.

**Comment by sbc100** [comment]
Agreed.  Certainly not great that it silently breaks.  If you feel like fixing (or error'ing) that would be great.
