### ISSUE TITLE
Confusing documentation on proxying.h

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20324]
[proxying.h docs](https://emscripten.org/docs/api_reference/proxying.h.html) say:

> On the target thread, queued work can be executed in two ways. First, the user may explicitly call emscripten_proxy_execute_queue to execute any tasks that have been queued for the current thread. Alternatively, queued work will execute automatically if the target thread returns to the JS event loop, for example via emscripten_exit_with_live_runtime.

I might be missing something, but from some quick experimentation and reading the code & tests, it seems the "work will execute automatically" actually only applies to the Emscripten's system queue - which is not recommended to be touched by end users. It seems any custom queues need to be scheduled and executed manually.

Is that correct? If so, the docs should probably be adjusted. It would also be helpful to provide an example of how such scheduling could look like if user doesn't have a good place to invoke manual queue execution (e.g. they also want to proxy to main thread, but want to use their own queue).

**Comment by RReverser** [comment]
Hmm no in a simple demo it does work with my own queues too... So it's only `emscripten_yield` that for some reason executes only main thread's queued tasks? https://github.com/emscripten-core/emscripten/blob/9bdb310b89472a0f4d64f36e4a79273d8dc7fa98/system/lib/pthread/emscripten_yield.c#L44-L46

Anyway, I'll close this for now until I figure out what exactly wrong.

**Comment by RReverser** [comment]
Ah I guess the problem is that it's more difficult to return to the event loop in non-main threads, since things like "exit with live runtime" don't operate on per-thread basis, that's why it didn't work.

**Comment by sbc100** [comment]
You can do `emscripten_runtime_keepalive_push` and `emscripten_unwind_to_js_event_loop` on each thread.  Each thread has its own keepalive counter.

**Comment by RReverser** [comment]
TIL about `emscripten_unwind_to_js_event_loop`.

**Comment by RReverser** [comment]
@sbc100 I wonder, why _does_ `emscripten_yield` execute only main thread's queue and not the current thread's one? Is that intentional limitation?

**Comment by sbc100** [comment]
> @sbc100 I wonder, why _does_ `emscripten_yield` execute only main thread's queue and not the current thread's one? Is that intentional limitation?

It is intentional yes. 

Note that it is only the system queue that is run while blocking/yielding.   We support any number of other queues that don't get run during yield.

As to why it is the way it is, I believe we experimenting with having background threads also process their system queue when blocking but it leads to deadlocks.  @tlively might remember more about the specific details of the deadlocks.

IIUC, even the current system (where only main thread runs it queue while blocking) can lead to deadlocks so we need to be careful about the kind of work we proxy using the system queue (i.e. `__proxy` attributes).

**Comment by tlively** [comment]
Basically, running proxied code at arbitrary pthread cancellation points means that it's wildly unsafe to proxy non-trivial code. The system proxying queue should only run code that essentially behaves like signal handlers. Having user-created proxy queues only execute when explicitly requested or when there is no other code on the stack makes it safe to use the to proxy arbitrary work, which makes them much more useful.
