### ISSUE TITLE
Update llvm libs to llvm 17

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#20378]
LLVM 17 was released a few weeks about and we already have 17.0.2:
https://discourse.llvm.org/t/llvm-17-0-2-released/73840

**Comment by sbc100** [comment]
@aheejin do you fancy having a go at this and following the instructions you wrote?   If not, I'm happy to have a go.

**Comment by aheejin** [comment]
I can try that.

**Comment by sbc100** [comment]
Awesome.  

Remember, the important first step is to make sure all our current changes are pushed to the branch in the llvm fork

**Comment by sbc100** [comment]
As of #21638 we are now on 18.1.2
