### ISSUE TITLE
Documentation for using `bitwise_xor` intrinsic targetting webassembly seems wrong

### ISSUE THREAD

**Issue by anutosh491** [emscripten-core/emscripten#20397]
Please include the following in your bug report:
<img width="533" alt="image" src="https://github.com/emscripten-core/emscripten/assets/87052487/80088ada-3be0-42d7-bc77-5b4bac9d1677">

I think this should be `wasm_v128_xor` instead of `wasm_v128_or` on this page 
https://github.com/emscripten-core/emscripten/blob/2c15c6e295319d4537d5230a8b656a0681b08706/site/source/docs/porting/simd.rst?plain=1#L789-L792

**Version of emscripten/emsdk:**
3.1.46

**Failing command line in full:**
None

**Full link command and output with `-v` appended:**
None

**Comment by juj** [comment]
Thanks!
