### ISSUE TITLE
Invalid Acorn optimization

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#20393]
Input file:
```js
globalThis.f = function(r) {
    let { a, b, c } = r;
    return g(a, b, c);
}
```
Run: `emsdk/node/16.20.0_64bit/bin/node emsdk/upstream/emscripten/tools/acorn-optimizer.js JSDCE test.js -o test.jso1.js`

Output:
```js
globalThis.f = function(r) {
 return g(a, b, c);
};
```

**Version of emscripten/emsdk:**
3.1.45

**Comment by kripken** [comment]
Thanks for the small testcase @hoodmane !
