### ISSUE TITLE
Documentation for cast intrinsic unclear

### ISSUE THREAD

**Issue by anutosh491** [emscripten-core/emscripten#20419]
<img width="325" alt="image" src="https://github.com/emscripten-core/emscripten/assets/87052487/3b0f2e96-0487-43ae-b831-80b0499f0c92">
 
https://github.com/emscripten-core/emscripten/blob/2c15c6e295319d4537d5230a8b656a0681b08706/site/source/docs/porting/simd.rst?plain=1#L387-L388

As per the legend ✅ stands signifies that Wasm SIMD has a native opcode that matches the x86 SSE instruction, should yield native performance.
Is this is the correct sign✅ being used ? 
But I am not sure if we have a wasm intrinsic for this ? do we ?  If not can we emulate the cast intrinsic somehow ?

**Version of emscripten/emsdk:**
3.1.46

**Failing command line in full:**
None

**Full link command and output with `-v` appended:**
None

**Comment by tlively** [comment]
In both x86 and in WebAssembly, the cast intrinsic is just for the compiler and does not emit any instructions, so it has zero cost.

Was there a separate issue about `wasm_v128_xor` and `wasm_v128_or`? Can you elaborate on that?

**Comment by anutosh491** [comment]
The issue is listed here (https://github.com/emscripten-core/emscripten/issues/20397)

**Comment by anutosh491** [comment]
Also I'm somewhat new to wasm simd intrinsics. I'll try to understand what this means and if we would need a complementary wasm based intrinsic for `_mm_castpd_ps`
> In both x86 and in WebAssembly, the cast intrinsic is just for the compiler and does not emit any instructions, so it has zero cost.

**Comment by tlively** [comment]
To be more precise, Wasm does not need a cast instrinsic because its intrinsics only use a single type, `v128_t`. Where you would need to cast in the x86 intrinsics, you just continue using the same `v128_t` value in the Wasm intrinsics.

**Comment by anutosh491** [comment]
Ahh I think so I got it. Because wasm SIMD uses a unified vector type for all SIMD operations, there's no need for explicit type casting between different SIMD register types, as there's only one type to work with.

P.S I was just about to comment but you did it first. I hope my understanding is correct :)
