### ISSUE TITLE
new android chrome 117 breaks web app

### ISSUE THREAD

**Issue by mithrendal** [emscripten-core/emscripten#20422]
```
emcc -v 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46 (19607820c447a13fd8d0b7680c56148427d6e1b8)
clang version 18.0.0 (https://github.com/llvm/llvm-project 75501f53624de92aafce2f1da698b249a7293dc7)
Target: wasm32-unknown-emscripten
Thread model: posix
```

web app vAmigaWeb crashes with `memory out of bounds` during app startup in the wasm related part on android chrome 117 only. All other browsers work fine on any other plattform.

run the web app 
https://vamigaweb.github.io

(it will show a dialog on first run, on android chrome 117 it crashes)

To investigate into detail the app was built with the following sanitizers 

built with `-sSAFE_HEAP=1`
->showed no warnings

built with `-fsanitizer=address`
->showed no warnings

What was unexpected was the fact that instead of bringing some light into the problem on androids chrome 117, these two sanitizer settings above made it run on android chrome 117 with no warnings or errors in the javascript console. i.e. they fixed the problem of the memory out of bounds instead of reporting warnings about the problem…
albeit they fixed the problem they are very performance hungry and the binary size is huge, so its of course no solution. 

What I tried too: 
  `-sSTACK_OVERFLOW_CHECK=1` => which shows no warnings
   increasing the `stack size` and `memory size` => did not change anything
   used only `-O1` settings for compile and link stage instead of `-O3` => did not change anything
   Tried chrome 117 in `android studio emulator (x86 built)` result: that one compared to its ARM based brother works fine.

All other browser except android chrome 117 on android phones are working fine. Any platform.

more infos
https://vamigaweb.github.io/doc/about.html
https://github.com/vAmigaWeb/vAmigaWeb

failing chrome version: `117.0.5938.140`
operating system: `Android 13`; SM-F926B Build/TP1A.220624.014
device: `samsung fold z3` (also another different android device failed)

before chrome version 117 it worked on the failing system...

Does anyone have any suggestions what to do next or how to proceed  ? Could it also be a bug in that specific chrome build ?

**Comment by kripken** [comment]
I tested on Android Chrome `117.0.5938.153` and after closing the dialog it seems to start, it shows two large eyes and "waiting for bootable media". Should it have crashed before that?

**Comment by mithrendal** [comment]
>Should it have crashed before that?

yes, the dialog does not even come up when it crashes ...

I do not have any android device except the android studio emulator where the problem does not show up.  I will ask @Vweber73 who reported the issue to our project to retest with version `117.0.5938.153`

**Comment by mithrendal** [comment]
@kripken 
retested with `117.0.5938.153` on the two different failing android devices. They don't crash anymore with that chrome build. 

Because the binary deployment of the vAmigaWeb Commodore Amiga Emulator app was never touched since, it seems most likely to me that `117.0.5938.140 for android` had an issue which caused the `memory out of bounds`.

just for reference I had opened issue in chromium bugtracker for the problem
https://bugs.chromium.org/p/chromium/issues/detail?id=1488764

Alon, should I close this emscripten issue then ?

**Comment by kripken** [comment]
I think your guess makes sense, yeah: very possibly there was a bug in the older version which was just fixed. Good to know it's resolved at least. As there's nothing left here to do, let's close this.
