### ISSUE TITLE
onRuntimeInitialized not called in code generated with 3.1.46

### ISSUE THREAD

**Issue by lpugin** [emscripten-core/emscripten#20445]
We are having a problem with the code generated with 3.1.46, and namely that the `onRuntimeInitilized` callback is not called when the codebase is compiled with the emsdk 3.1.46 (and 3.1.47). When running with Node or in the browser (Firefox and Chrome), the module seems to be there but `onRuntimeInitialized` in not triggered.

This works with 3.1.45 and previous versions.

The codebase is https://github.com/rism-digital/verovio/. I can dig more, but any ideas what could be the cause of the issue? Or what information should I provide?

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here
```bash
emcmake cmake ../cmake -DBUILD_AS_WASM=ON -DNO_HUMDRUM_SUPPORT=ON -DCMAKE_CXX_FLAGS="-O3 -DNDEBUG -std=c++17 -s STRICT=1"
configure: cmake ../cmake -DBUILD_AS_WASM=ON -DNO_HUMDRUM_SUPPORT=ON "-DCMAKE_CXX_FLAGS=-O3 -DNDEBUG -std=c++17 -s STRICT=1" -DCMAKE_TOOLCHAIN_FILE=/Users/laurent/tools/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/Users/laurent/tools/emsdk/node/16.20.0_64bit/bin/node
```

```bash
em++ -v libverovio.a  -s WASM=1 -s INITIAL_MEMORY=512MB -s STACK_SIZE=256MB -s SINGLE_FILE=1 -O3 -DNDEBUG -std=c++17 -s STRICT=1 --embed-file data/ -s EXPORTED_FUNCTIONS="['_enableLog','_enableLogToBuffer','_vrvToolkit_constructor','_vrvToolkit_destructor','_vrvToolkit_edit','_vrvToolkit_editInfo','_vrvToolkit_getAvailableOptions','_vrvToolkit_getDefaultOptions','_vrvToolkit_getDescriptiveFeatures','_vrvToolkit_getElementAttr','_vrvToolkit_getElementsAtTime','_vrvToolkit_getExpansionIdsForElement','_vrvToolkit_getHumdrum','_vrvToolkit_convertHumdrumToHumdrum','_vrvToolkit_convertHumdrumToMIDI','_vrvToolkit_convertMEIToHumdrum','_vrvToolkit_getLog','_vrvToolkit_getMEI','_vrvToolkit_getMIDIValuesForElement','_vrvToolkit_getNotatedIdForElement','_vrvToolkit_getOptions','_vrvToolkit_getPageCount','_vrvToolkit_getPageWithElement','_vrvToolkit_getTimeForElement','_vrvToolkit_getTimesForElement','_vrvToolkit_getVersion','_vrvToolkit_loadData','_vrvToolkit_loadZipDataBase64','_vrvToolkit_loadZipDataBuffer','_vrvToolkit_redoLayout','_vrvToolkit_redoPagePitchPosLayout','_vrvToolkit_renderData','_vrvToolkit_renderToExpansionMap','_vrvToolkit_renderToMIDI','_vrvToolkit_renderToPAE','_vrvToolkit_renderToSVG','_vrvToolkit_renderToTimemap','_vrvToolkit_resetOptions','_vrvToolkit_resetXmlIdSeed','_vrvToolkit_select','_vrvToolkit_setOptions','_vrvToolkit_validatePAE','_malloc','_free']" -s EXPORTED_RUNTIME_METHODS='["cwrap"]' -o build/verovio.js
```

**Comment by lpugin** [comment]
It seems that removing `-s STRICT=1` fixes the issue. What change would be needed in order be able to keep `STRICT` enabled?

**Comment by sbc100** [comment]
It looks like you were effected by #16372.  With this change, when you use `-sSTRICT` you need to opt into incoming module API elements such as `onRuntimeInitialized` using `-sINCOMING_MODULE_JS_API=onRuntimeInitialized`.

Do you run a debug build?  If a debug build you should see an error message right away telling you how to fix the issue.

BTW, regarding the `EXPORTED_FUNCTIONS` and `EXPORTED_RUNTIME_METHODS` settings, you no longer need to quote each of the strings use the opening closing square brackets.  You can just do `EXPORTED_FUNCTIONS=foo,bar,baz`.   this can make quoting in Makefiles and CMakeLists.txt files simpler.   

When you have a long list of functions like you do you can also do `-sEXPORTED_FUNCTIONS=@exports.txt` where `exports.txt` contains you list of symbols to export, one per line.

**Comment by lpugin** [comment]
Great, many thanks for the detailed feedback and the additional suggestions. I'll make the necessary changes.
