### ISSUE TITLE
Runtime error when running with -sSPLIT_MODULE=1 and -sMEMORY64=1

### ISSUE THREAD

**Issue by shinji-TH** [emscripten-core/emscripten#20448]
Hi @tlively, 
I'm currently experimenting with MEMORY64 with my app. 
However I am encountering the following errors when running the app. 
Seem like the `__write_profile` was inserted as i32 function instead of i64.

![image](https://github.com/emscripten-core/emscripten/assets/33003856/b9aec8aa-97a3-451d-af31-77d444e6c6bd)

Hence wish to check if the combination is supported and are there any plans to support it. 

**Version of emscripten/emsdk:**
`emcc -v
tools.filelock:DEBUG: Attempting to acquire lock 140535313156704 on /tmp/emscripten_temp/emscripten.lock
tools.filelock:DEBUG: Lock 140535313156704 acquired on /tmp/emscripten_temp/emscripten.lock
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.47 (431685f05c67f0424c11473cc16798b9587bb536)
clang version 18.0.0 (https://github.com/llvm/llvm-project 21030b9ab4487d845e29792063f5666d8c4b8e09)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/yapt/emsdk/upstream/bin
shared:DEBUG: executed /home/yapt/emsdk/upstream/bin/clang -v -target wasm32-unknown-emscripten
emcc:DEBUG: total time: 0.01 seconds
profiler:DEBUG: block "main" took 0.006 seconds
tools.filelock:DEBUG: Attempting to release lock 140535313156704 on /tmp/emscripten_temp/emscripten.lock
tools.filelock:DEBUG: Lock 140535313156704 released on /tmp/emscripten_temp/emscripten.lock`

**Comment by tlively** [comment]
I have a fix out for review: https://github.com/WebAssembly/binaryen/pull/6013.

**Comment by shinji-TH** [comment]
@tlively, thank you so much for the fix. Sorry for the delay in verifying and closing the issue.
