### ISSUE TITLE
Support for calling clang directly?

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#2045]
I'm trying to use precompiled headers with emscripten to speed up builds. However, it doesn't seem like there is any support for calling clang directly. One hack that almost works is to pass flags via EMMAKEN_CFLAGS, but that doesn't work when there are no input files since in that case emcc doesn't even call clang. The only way I could get it to work was to run emcc with -v and copy the correct arguments to clang (defines, header include paths, and such) from the verbose output. But this feels like a fragile hack. Is there a way to drive clang directly with all of the correct include paths and other stuff set up?

**Comment by jenvannier** [comment]
After doing: 
`em++ -c -xc++-header file.h`
and
`em++  -include-pch file.h.gch -DEMSCRIPTEN otherfile.cc -o output.bc`
I get:
`ERROR:root:file.h.gch: Input file has an unknown suffix, don't know what to do with it!`
(With the newest version of the sdk installed.)

Ideas?

**Comment by missmah** [comment]
@kripken - are you planning to add -emit-pch and -include-pch support to emscripten?

See https://clang.llvm.org/docs/PCHInternals.html for details.

**Comment by missmah** [comment]
For reference, our use-case doesn't work without using -o to set the output location for the .gch (or .pch) file.

This is the output I get trying to use the PCH with -include-pch:
dev/Build/Output/HTML5-Profile/TestCore_Plugin/stdafx.gch: Input file has an unknown suffix, don't know what to do with it!

Thanks in advance for any help!

**Comment by kripken** [comment]
The [last part](https://github.com/kripken/emscripten/blob/incoming/tests/test_other.py#L3151) of `other.test_precompiled_headers` seems to test that, so at least what is there should work. Are you using different flags/options, what specifically is missing for your use case?

**Comment by missmah** [comment]
After some testing, what is there in `other.test_precompiled_headers` does indeed work, with some caveats:

1. It has issues if there happens to be a .gch or .pch file in the local directory (where it will mistakenly pick that one up instead, rather than always being forced to use the requested absolute path).

2. It would be really nice to unify syntax with Clang and be able to use -emit-pch and -include-pch, and force absolute paths to the PCH (which would fix #1).

**Comment by kripken** [comment]
Not sure I understand the issue in 1 - perhaps you can write out a full testcase? (Even better would be to add to the test, then when we fix it, we'll have a test already.)

For 2, we have `-include-pch` so if I understand correctly, we're just missing `-emit-pch`? That's probably easy to add.
