### ISSUE TITLE
"user callback triggered after runtime exited or application aborted" started on 3.1.47

### ISSUE THREAD

**Issue by emaxx-google** [emscripten-core/emscripten#20457]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
Please include the output `emcc -v` here

**Failing command line in full:**
The failure is runtime. It happens when running Smart Card Connector when built via Emscripten (https://github.com/GoogleChromeLabs/chromeos_smart_card_connector) or its tests.

I observe the `user callback triggered after runtime exited or application aborted` warning, and the Emscripten module startup doesn't seem to ever complete.

**Full link command and output with `-v` appended:**
```
emcc -v -o ./out-artifacts-emscripten/Debug/integration_tests.js -L../../../env/emsdk/lib/Debug ./out-artifacts-emscripten/Debug/__/__/src//chrome_certificate_provider/api_bridge.o ./out-artifacts-emscripten/Debug/__/__/src//chrome_certificate_provider/api_bridge_integration_test_helper.o ./out-artifacts-emscripten/Debug/__/__/src//chrome_certificate_provider/types.o ./out-artifacts-emscripten/Debug/__/__/__/common/integration_testing/src/entry_point_emscripten.o -lgoogle_smart_card_integration_testing -lgoogle_smart_card_common -pthread -s DISABLE_EXCEPTION_CATCHING=0  -O0 -g  --bind --post-js=../../../common/js/src/executable-module/emscripten-module-js-epilog.js.inc -s ABORTING_MALLOC=1 -s ALLOW_MEMORY_GROWTH=1 -s DYNAMIC_EXECUTION=0 -s ENVIRONMENT=web,worker -s 'EXPORT_NAME="loadEmscriptenModule_integration_tests"' -s INCOMING_MODULE_JS_API=[buffer,instantiateWasm,onAbort,preRun,print,printErr,wasmMemory] -s MIN_CHROME_VERSION=96 -s MIN_EDGE_VERSION=-1 -s MIN_FIREFOX_VERSION=-1 -s MIN_IE_VERSION=-1 -s MIN_SAFARI_VERSION=-1 -s MODULARIZE=1 -s PTHREAD_POOL_SIZE_STRICT=0 -Wno-pthreads-mem-growth  -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 -s SAFE_HEAP=1 -s TOTAL_STACK=1048576 -Wno-limited-postlink-optimizations
 "/home/emaxx/smart_card_connector/env/emsdk/upstream/bin/clang" --version
 "/home/emaxx/smart_card_connector/env/emsdk/upstream/bin/wasm-ld" -o ./out-artifacts-emscripten/Debug/integration_tests.wasm -L../../../env/emsdk/lib/Debug ./out-artifacts-emscripten/Debug/__/__/src//chrome_certificate_provider/api_bridge.o ./out-artifacts-emscripten/Debug/__/__/src//chrome_certificate_provider/api_bridge_integration_test_helper.o ./out-artifacts-emscripten/Debug/__/__/src//chrome_certificate_provider/types.o ./out-artifacts-emscripten/Debug/__/__/__/common/integration_testing/src/entry_point_emscripten.o ../../../env/emsdk/lib/Debug/libgoogle_smart_card_integration_testing.a ../../../env/emsdk/lib/Debug/libgoogle_smart_card_common.a -L/home/emaxx/smart_card_connector/env/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /home/emaxx/smart_card_connector/env/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/crtbegin.o --whole-archive -lembind-rtti --no-whole-archive -lGL-mt -lal -lhtml5 -lbulkmemory -lstubs-debug -lnoexit -lc-mt-debug -ldlmalloc-mt-debug -lcompiler_rt-mt -lc++-mt -lc++abi-debug-mt -lsockets-mt -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpp5k21vm1libemscripten_js_symbols.so --import-memory --shared-memory --export-if-defined=main --export-if-defined=_emscripten_thread_init --export-if-defined=_emscripten_thread_exit --export-if-defined=_emscripten_thread_crashed --export-if-defined=_emscripten_tls_init --export-if-defined=pthread_self --export-if-defined=__get_exception_message --export-if-defined=free --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=sbrk --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=__cxa_demangle --export=free --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=emscripten_get_sbrk_ptr --export=_emscripten_thread_free_data --export=emscripten_main_runtime_thread_id --export=emscripten_main_thread_process_queued_calls --export=_emscripten_run_on_main_thread_js --export=emscripten_stack_set_limits --export=__get_temp_ret --export=__set_temp_ret --export=__cxa_is_pointer_type --export=__cxa_can_catch --export=__cxa_increment_exception_refcount --export=__cxa_decrement_exception_refcount --export=setThrew --export=__cxa_free_exception --export=__wasm_call_ctors --export=_emscripten_thread_init --export=_emscripten_thread_exit --export=__get_exception_message --export-table -z stack-size=1048576 --initial-memory=16777216 --max-memory=2147483648 --no-entry --stack-first --table-base=1
 "/home/emaxx/smart_card_connector/env/emsdk/upstream/bin/llvm-objcopy" ./out-artifacts-emscripten/Debug/integration_tests.wasm ./out-artifacts-emscripten/Debug/integration_tests.wasm --remove-section=producers
 "/home/emaxx/smart_card_connector/env/emsdk/upstream/bin/wasm-emscripten-finalize" -g --dyncalls-i64 --pass-arg=legalize-js-interface-exported-helpers --check-stack-overflow --dwarf ./out-artifacts-emscripten/Debug/integration_tests.wasm -o ./out-artifacts-emscripten/Debug/integration_tests.wasm --detect-features
 "/home/emaxx/smart_card_connector/env/emsdk/node/16.20.0_64bit/bin/node" /home/emaxx/smart_card_connector/env/emsdk/upstream/emscripten/src/compiler.js /tmp/tmp2akztafl.json
 "/home/emaxx/smart_card_connector/env/emsdk/upstream/bin/wasm-opt" --safe-heap ./out-artifacts-emscripten/Debug/integration_tests.wasm -o ./out-artifacts-emscripten/Debug/integration_tests.wasm -g --mvp-features --enable-threads --enable-bulk-memory --enable-mutable-globals --enable-sign-ext
 "/home/emaxx/smart_card_connector/env/emsdk/node/16.20.0_64bit/bin/node" /home/emaxx/smart_card_connector/env/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_0phcie6f/integration_tests.js growableHeap --closureFriendly -o /tmp/emscripten_temp_0phcie6f/integration_tests.jso1.js
 "/home/emaxx/smart_card_connector/env/emsdk/node/16.20.0_64bit/bin/node" /home/emaxx/smart_card_connector/env/emsdk/upstream/emscripten/tools/acorn-optimizer.js /tmp/emscripten_temp_0phcie6f/integration_tests.js.pgrow.js safeHeap --closureFriendly -o /tmp/emscripten_temp_0phcie6f/integration_tests.js.pgrow.jso2.js
 "/home/emaxx/smart_card_connector/env/emsdk/node/16.20.0_64bit/bin/node" /home/emaxx/smart_card_connector/env/emsdk/upstream/emscripten/tools/preprocessor.js /tmp/emscripten_temp_0phcie6f/settings.js worker.js --expandMacros
```

**Comment by emaxx-google** [comment]
My current guess is that the original error is something different (e.g., just as a shot in the dark, the recent changes to `emscripten::val`), but for some reason it gets hidden by this uninformative `user callback triggered after runtime exited or application aborted` error.

**Comment by sbc100** [comment]
Can you set a break point at the "user callback triggered after runtime exited or application aborted" message location and see which of `runtimeExited` or `ABORT` is set?

Then maybe set a breakpoint in `abort` or `exitJS` to see how/why you program exist or aborts?

**Comment by emaxx-google** [comment]
In my case `ABORT` is true. My build doesn't set `EXIT_RUNTIME`, so in this build mode `runtimeExited` isn't checked.

The stack trace at the moment when `exitJS` is called indicates it happened inside `callUserCallback` - see the attached file.
![Screenshot from 2023-11-06 22-15-31](https://github.com/emscripten-core/emscripten/assets/17597418/3541823f-4c07-4057-89f6-6cd05667246b)

**Comment by sbc100** [comment]
Can you break on the line that sets ABORT to true?  There should be just one IIRC.

**Comment by emaxx-google** [comment]
`ABORT` is set to `true` from inside that same `exitJS` call: 
![image](https://github.com/emscripten-core/emscripten/assets/17597418/a2609737-a218-466f-8436-87f2389913f7)

**Comment by emaxx-google** [comment]
I've narrowed it down to this flag in my command line being the culprit:
`-s INCOMING_MODULE_JS_API=[buffer,instantiateWasm,onAbort,preRun,print,printErr,wasmMemory]`

Is there a way to get to the original error, so that the missing value can be identified?

**Comment by sbc100** [comment]
> I've narrowed it down to this flag in my command line being the culprit: `-s INCOMING_MODULE_JS_API=[buffer,instantiateWasm,onAbort,preRun,print,printErr,wasmMemory]`
> 
> Is there a way to get to the original error, so that the missing value can be identified?

Its is very odd.   I have no idea why that setting would cause this error.

What do you mean by "get to the original error"?

**Comment by emaxx-google** [comment]
> What do you mean by "get to the original error"?

I meant my guess was that some code tried to call a function not mentioned on that list, which triggered an exception, and the latter wasn't logged anywhere itself and only led to a "silent" termination.

That's how I ended up with this `[buffer,instantiateWasm,onAbort,preRun,print,printErr,wasmMemory]` list: start from a small list, try running the module, observe an exception that mentions an attempt to call a missing function, add it and go back to step#1.

**Comment by sbc100** [comment]
Ah I see.. you mean like if someone did `Module['instantiateWasm'](xxx)`  without first checking if that property existed and that would generate something like "undefined is not a function" ?

Those types of runtime errors are not normally handled by emscripten so would normally show up as global errors or promise rejections.   Presumably you have visibility of those things when they happen on your page?

**Comment by emaxx-google** [comment]
> Ah I see.. you mean like if someone did `Module['instantiateWasm'](xxx)` without first checking if that property existed and that would generate something like "undefined is not a function" ?
> 
> Those types of runtime errors are not normally handled by emscripten so would normally show up as global errors or promise rejections. Presumably you have visibility of those things when they happen on your page?

I think I wasn't clear - my page doesn't call these methods, so they were needed by Emscripten's own logic.

In any case, I think the current bug can be closed as the original discussion, before we narrowed it down to the actual problem with `INCOMING_MODULE_JS_API`, is confusing. I filed #20636 and #21167 for specific problems, and in the meantime I worked around my problems by not using `INCOMING_MODULE_JS_API`.
