### ISSUE TITLE
Memory growth checks not included with wasm workers

### ISSUE THREAD

**Issue by rnconrad** [emscripten-core/emscripten#20456]
When using wasm workers `-sWASM_WORKERS` (and NOT pthreads) along with `-sALLOW_MEMORY_GROWTH`, the memory growth checks are not included, and thus reading memory from js can fail after the heap is resized.

Here is the condition for applying the memory growth fixes:

https://github.com/emscripten-core/emscripten/blob/5b24a09de582f3943d75aa6af9be36ba719c08c0/emcc.py#L3816

A possible fix is to change the above to:
```python
if settings.SHARED_MEMORY and settings.ALLOW_MEMORY_GROWTH:
````
which I can happily PR if that is satisfactory.

**Comment by kripken** [comment]
That sounds right @rnconrad , a PR would be great!
