### ISSUE TITLE
Expose arch-specific library dir

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20469]
I wanted to move an old project to Emscripten's sysroot system, but had issues with installed libraries not being found by default.

In the end I tracked it down to my `make install` installing libraries in `$prefix/lib` (which is the common place for them), while linker only searching in `$prefix/lib/wasm32-emscripten`:

```
> emcc -print-search-dirs
programs: =/home/rreverser/emsdk/upstream/bin
libraries: =/home/rreverser/emsdk/upstream/lib/clang/18:/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten
```

Note that `wasm-ld` receives only `-L/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten`. It should search in `-L/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib` as well.

Alternatively, if this is the intended installation path as we want to differentiate between libraries built for different targets, 1) we should move pkgconfig under it as well for consistency as pkgconfig files often have hardcoded prefix / libdir paths, 2) I think it would be still inconsistent with traditional sysroot structure.

Maybe instead there should be separate sysroots built per-target?

**Comment by RReverser** [comment]
cc @sbc100 as you know most about our sysroot structure :)

**Comment by sbc100** [comment]
What we have is a multi-arch sysroot structure, which I believe is not too uncommon.

The problem with also searching the parent is that it would mean that wasm32 libs would be found when wasm64 was used (or vice versa), and than wasm32 and wasm64 libs would clobber each other.

I would have though that autotools could handle multi-arch sysroots these days but I don't remember the details.

It is true that on my desktop multi-arch system `-L/lib -L/usr/lib`  are always injected in addition to `-L/usr/lib/x86_64-linux-gnu` or `-L/usr/lib/i386-linux-gnu`... but that seem pretty risky.

**Comment by sbc100** [comment]
Indeed it does look like pkgconfig files should live in the arch-specific subdir:

```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/zlib.pc 
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: zlib
Description: zlib compression library
Version: 1.2.13

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lz
Cflags: -I${includedir}
```

**Comment by RReverser** [comment]
> I would have though that autotools could handle multi-arch sysroots

Problem is that default dirs are derived from `${prefix}` as you can see above. I'm guessing those projects like zlib override `libdir=...` explicitly to get arch subdir... but I'll need to check.

At least, that's not the default I'm observing across 3 libs I compiled so far - they all default to `libdir=${prefix}/lib`.

**Comment by sbc100** [comment]
Perhaps we can override the default somehow in our config.site?  Perhaps there are some clues here: https://wiki.debian.org/Multiarch/Implementation

**Comment by RReverser** [comment]
I guess I can override `libdir` in the "universal" autotools config for Emscripten I'm working on, but it's not clear to me how to ask emcc for this target directory from current CFLAGS.

It's not the full triplet received from `print-target-triple` or `dumpmachine`, but some short version...

Also it's unclear which other dirs need to be overridden then. Is `libdir` and `bindir` enough?

**Comment by sbc100** [comment]
Perhaps we can override the default somehow in our config.site?  Perhaps there are some clues here: https://wiki.debian.org/Multiarch/Implementation#autotools_with_no_helper

See `Add --libdir=\$${prefix}/lib/$(DEB_HOST_MULTIARCH) to each invocation of configure in debian/rules`.. perhaps we can have emconfigure inject that?

**Comment by RReverser** [comment]
Yeah we can do that via `config.site`, but see my question above. It's not clear to me how to ask for this short arch variant from Emscripten. Do I need to construct it manually or is there a way to get it automatically, similar to `dumpmachine`?

**Comment by sbc100** [comment]
Can we just create a separate config.site file for each lib/xxx/ dir?

**Comment by RReverser** [comment]
Uh we could but seems like overkill to have two copies. Can't we normalise sysroot to use full triples like everywhere else?

**Comment by RReverser** [comment]
I guess I can add some simple `sed`in there for now, but I do think it would be nice to have same triple reported from emcc, used in CMake, used in `--host` etc

**Comment by sbc100** [comment]
I don't think I would object to using the longer form triple in the library subdir.  It does make the paths longer, but thats not a huge deal I think.

**Comment by RReverser** [comment]
Meanwhile looking through various Clang options, I thought I could use `-print-file-name` with libc, but for some reason that also doesn't work correctly with `MEMORY64` (also processed too early like `dumpmachine` perhaps?).

```
> emcc -print-file-name=libc.a
/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a
> emcc -s MEMORY64 -print-file-name=libc.a
/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a
```

There is also undocumented `-print-multi-directory, --print-multi-directory` but I couldn't get it to output anything at all.

**Comment by sbc100** [comment]
I'll take a look at fixing those.  `MEMORY64` is still experimental to is not too surprising they don't work yet.

**Comment by RReverser** [comment]
Yeah that's absolutely fair; I just want to make sure I get `config.site` correctly so looking at different options.

**Comment by RReverser** [comment]
OTOH I guess for binaries it doesn't matter as much and it's fine to clobber one implementation (wasm32 vs wasm64) with another, as long as it runs...

**Comment by sbc100** [comment]
I don't think we need to worry to much about binaries.  I'm not sure it makes sense to install binaries into the sysroot since its a sysroot just built for cross compiling.

If you have binaries that need to run as part of the build process they should be built for the host and not installed in the sysroot.

What is more, installing "binaries" won't work in the emscripten case because our "binaries" are a pair of "js" and "wasm" files which is not something that autoconf supports installing (it very much assumes that the linker outputs a single file).

**Comment by RReverser** [comment]
> What is more, installing "binaries" won't work in the emscripten case because our "binaries" are a pair of "js" and "wasm" files which is not something that autoconf supports installing (it very much assumes that the linker outputs a single file).

Ah that's true, we'd need custom replacement for `/bin/install` that copies both, or automatically set `SINGLE_FILE`. You're probably right it doesn't matter for now.

**Comment by RReverser** [comment]
> I guess I can add some simple `sed`in there for now, but I do think it would be nice to have same triple reported from emcc, used in CMake, used in `--host` etc

Looks like this was moot anyway, I'll have to construct hacky triple like `wasm32-unknown-linux-gnu` to prevent errors like "system emscripten not recognised".

Even if autotools recognised it, most projects don't know what to do with that OS anyway, so for now a middle ground will have to do. This would be similar to what CMake does with `UNIX` variable:

https://github.com/emscripten-core/emscripten/blob/687061683d90bb53fdecc8d2a0f7f6fb2a59955a/cmake/Modules/Platform/Emscripten.cmake#L49-L53

**Comment by RReverser** [comment]
Apparently it's more complicated than just arch difference.

For example, if I build with LTO:

```
> echo 'int main(){}' | emcc -xc -  -flto -v

"/home/rreverser/emsdk/upstream/bin/wasm-ld" -o a.out.wasm /tmp/emscripten_temp_jmyzf7yt/-_0.o -L/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpfni2y657libemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --no-entry --stack-first --table-base=1
```

then wasm-ld is asked to search only in `/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto` and it doesn't find libraries installed under `/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten`.

Interestingly, this doesn't match the directories printed by `-print-search-dirs` which has both non-LTO directory and a LTO directory with different path than used by Emscripten:

```
> emcc -flto -print-search-dirs
programs: =/home/rreverser/emsdk/upstream/bin
libraries: =/home/rreverser/emsdk/upstream/lib/clang/18:/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/llvm-lto/18.0.0git:/home/rreverser/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten
```

**Comment by RReverser** [comment]
Looks like library directory is computed in `tools/cache.py` -> `get_lib_dir`.

As far as I can tell, that function is only used to add that `-L` flag as well as for building system libs, but not exposed via command line anywhere yet.

**Comment by RReverser** [comment]
> Interestingly, this doesn't match the directories printed by `-print-search-dirs` which has both non-LTO directory and a LTO directory with different path than used by Emscripten:

Looks like there is even a test for that particular CLI flag in `other.test_emcc_print_search_dirs`, but it doesn't cover those other variants (wasm64, LTO) so doesn't catch this bug. Not that it would help with original issue here.

**Comment by RReverser** [comment]
Ah, same for `-print-file-name` nearby - `other.test_emcc_print_file_name`. Now that one _could_ help if fixed for other variants.

**Comment by sbc100** [comment]
> Looks like library directory is computed in `tools/cache.py` -> `get_lib_dir`.
> 
> As far as I can tell, that function is only used to add that `-L` flag as well as for building system libs, but not exposed via command line anywhere yet.

get_lib_dir is used to set the default library directory in emcc.py: https://github.com/emscripten-core/emscripten/blob/0f15c2a8dc6134c96b82292f9de68cee05ea225d/emcc.py#L1819

**Comment by RReverser** [comment]
> get_lib_dir is used to set the default library directory in emcc.py:

Right; the problem is that it's not used anywhere where it can be retrieved via public commands. I guess I could use the new `-###` to extract `-L` argument, but there might be more than one which makes it a bit more difficult.

`get_lib_dir` should be taken in `-print-file-name` and `-print-search-dirs` as mentioned above, but currently isn't - all of those return same static wasm32 path instead of the one that varies on lto/wasm64/etc.

**Comment by sbc100** [comment]
Yes, sorry, I didn't mean to suggest that we shouldn't fix `-print-search-dirs`

**Comment by RReverser** [comment]
I think `-print-file-name` would make this even easier, as then I could just do `dirname $(emcc -print-file-name=libc.a)`. For other options the extraction process is slightly more involved as they have more output.

**Comment by sbc100** [comment]
Sorry, yes, of course they should both work.

**Comment by sbc100** [comment]
BTW `-print-file-name` it looks like works for files that are already installed:

```
$ clang -print-file-name=libc.a
/lib/x86_64-linux-gnu/libc.a
$ clang -print-file-name=foo.a
foo.a
```

So it might be useful for decided where to install something.

**Comment by sbc100** [comment]
Can we close this now that #20575 has landed?

**Comment by RReverser** [comment]
It didn't land yet though? It will auto-close this issue when it does.

**Comment by sbc100** [comment]
:doh:

**Comment by RReverser** [comment]
I know the feeling 🤗
