### ISSUE TITLE
Bug in page:Download and install 

### ISSUE THREAD

**Issue by objectwizard** [emscripten-core/emscripten#20471]
Suggestion for making install and run easier so newbies can get started more easily. Instructions jump straight to checking the version.

On installation instructions please include setting PATH by adding 

`export PATH="/path/to/emsdk/upstream/emscripten:$PATH"`

to

`/home/username/.bashrc`

URL: ../../docs/getting_started/downloads

**Comment by rajat99-default** [comment]
can you assign me this issue
and give some guidance on how to solve this

**Comment by kripken** [comment]
@rajat99-default Feel free to work on the issue. The file to update is `site/source/docs/getting_started/downloads.rst`.

**Comment by sbc100** [comment]
Note that the recommended thing to add to your bashrs is actually `source "/usr/local/google/home/sbc/dev/wasm/emsdk/emsdk_env.sh`.

This avoids hardcoding the paths where the tools live.

**Comment by rajat99-default** [comment]
I am getting this error plz help

Rajat_99@DESKTOP-CCV9SPJ MINGW64 ~/emscripten (main)
$ git push origin main
remote: Permission to emscripten-core/emscripten.git denied to rajat99-default.
fatal: unable to access 'https://github.com/emscripten-core/emscripten.git/': The requested URL returned error: 403

**Comment by sbc100** [comment]
You can't push directly to `emscripten-core/emscripten.git` because you don't have commit access there.  You need to first create your own fork and then push to that.

**Comment by man0045** [comment]
is this issue still open , please assign me this issue and guide me  i'm beginer here

**Comment by rajat99-default** [comment]
Wait I am doing this
