### ISSUE TITLE
Dynamic File loading while running in the Browser

### ISSUE THREAD

**Issue by mgreter** [emscripten-core/emscripten#2047]
Hi

First of all, pretty impressive monster you created here :-)

I came across this project, because of sass.js. I saw that there were some (two) issues (already closed) about a similar topic, but from the text I'm not sure if this was to target node.js or browsers.

https://github.com/medialize/sass.js

I implemented (hacked together) something that allows sass.js (libsass actually) to load files as requested. To do this I added a small hook to the stat syscall. In this hook I try to fetch the file via XHR and fill the virtual FS accordingly, if a 200 status is returned. This seems to work pretty well.

http://ocbnet.ch/sass.link.js/example/demo.html

I've chosen stat to add the hook as I guess that it will be called pretty much always before any real FS operations take place (i.e. before open). But I'm not sure if this is actually by design (POSIX?) or just coincidentally done by libsass (https://github.com/mgreter/sass.js/commit/254726aa04907f9844e8f092722153e4365867b2).

https://github.com/mgreter/sass.link.js/blob/master/src/sass.link.js#L330

Not sure if this has already been brought up? Maybe this would be worth adding to emscripten? I'm pretty sure that the performance overhead should be minimal, as FS operation always tend to be expensive anyway.

The way I did it is pretty sure not optimal, I just abused to global Module array. It may be wise to add a specific feature to enable dynamic loading. If you add a hook just for stat, I'm pretty sure someone would expect it for other syscalls too. IMO this could go any way, just add a hook or implement the whole fetching within emscripten (or even a full implementation to a restfull api or webdav).

https://github.com/mgreter/sass.link.js
https://github.com/mgreter/sass.js

Feedback welcome!

Have a nice day
Marcel Greter

**Comment by httpdigest** [comment]
It's been a while, but while searching through the issues to find something related to "XHR downloading files dynamically on demand" I found this issue here.
First, there is http://kripken.github.io/emscripten-site/docs/porting/files/Synchronous-Virtual-XHR-Backed-File-System-Usage.html#instructions which mentions that lazy file loading is possible when first declaring all needed files before.
Is it possible to do that without declaring them beforehand with FS.createLazyFile?
I have some need for this in my journey to Emscriptenify JamVM, because I would like to download all jar and class files in the user-set classpath of the Java application into the virtual file system to enable the JVM to scan them and interpret them. And if the classpath contains an entry that is a file system directory and not a jar file, there would potentially be hundreds of possible files to download, that cannot be statically FS.createLazyFile'd.

**Comment by mgreter** [comment]
I recently made some progress here and wanted to share what seems to work for me:

```js
var lookup = Sass.FS.lookup;
var dynloader = Sass.FS.lookup =
function dynloader(parent, name)
{
  syncXHR(name, parent,
    function (e, data)
    {
      if (!e && data) {
        Sass.FS.lookup = lookup;
        Sass.FS.writeFile(name, data);
        Sass.FS.lookup = dynloader;
      }
    }
  );
  return lookup.apply(this, arguments);
};
```

It seems that `writeFile` also triggers a `lookup`, so I had to workaround this, which makes it feel a little bit more hackish then anticipated. But it looks like a valid way to get on demand file loading.

**Comment by Tails** [comment]
> It's been a while, but while searching through the issues to find something related to "XHR downloading files dynamically on demand" I found this issue here. First, there is http://kripken.github.io/emscripten-site/docs/porting/files/Synchronous-Virtual-XHR-Backed-File-System-Usage.html#instructions which mentions that lazy file loading is possible when first declaring all needed files before. Is it possible to do that without declaring them beforehand with FS.createLazyFile? I have some need for this in my journey to Emscriptenify JamVM, because I would like to download jar and class files in the user-set classpath of the Java application into the virtual file system. And if the classpath contains an entry that is a file system directory and not a jar file, there would potentially be hundreds of possible files to download, that cannot be statically FS.createLazyFile'd. So, is it possible to dynamically read-in files into the virtual file system, which are not known beforehand?

I'm also interested in the answer to this. After finding https://github.com/bittorrent/sqltorrent it seems it could be reimplemented for the browser by using https://emscripten.org/docs/porting/files/Synchronous-Virtual-XHR-Backed-File-System-Usage.html. 

What is the state of the Virtual XHR feature now? Does it only work with synchronous XHR requests?
