### ISSUE TITLE
[wasm-split] Not able to set breakpoint while debugging

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#20483]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/3.1.35/emsdk/upstream/bin

I used to debug my C++ code following [this](https://developer.chrome.com/blog/wasm-debugging-2020/) tutorial. As mentioned in that tutorial, we can open C/C++ source code in the devtools and add breakpoints there to have a good debugging experience. Recently, I integrated module splitting in my code and now I am unable to add breakpoints in the source code. I can still open source code in the devtools but can't add breakpoints.

This can be clearly reproduced on a sample code with wasm-split.

**Comment by tlively** [comment]
Unfortunately I don't think we can fix this. Debugging depends on DWARF debugging info and we have no way to fix up the DWARF when we split the module. Your best bet will be to disable the splitting when you need to debug unrelated problems.

**Comment by ravisumit33** [comment]
Got it, thanks.

**Comment by OgnjenO** [comment]
@tlively is this still the case or has something changed in the last 2 years? If this is till the case (debugging of split modules not possible), what would be the work needed to make the debugging work?

**Comment by tlively** [comment]
Nothing has changed here in the past two years. We're still unable to maintain meaningful DWARF debugging information when we split the module. Updating source maps would be easier than updating DWARF in principle, but it looks like wasm-split doesn't currently support that, either.
