### ISSUE TITLE
Warnings acting as errors?

### ISSUE THREAD

**Issue by Ethanscharlie** [emscripten-core/emscripten#20508]
Every warning my project acts as an error when compiling with emscripten
I was wondering if there was a way to get around this (Besides fixing every warning)?

**Comment by kripken** [comment]
`emcc` should act like clang or gcc, so the usual `-w` etc. should work.

If you have `-Werror` then that could cause the problem you see, so make sure your build system does not add that.

**Comment by sbc100** [comment]
Can you give an example of such a warning?  

Are you talking about console messages at runtime or build time diagnostics?   If the latter, do they show up in release builds too?

**Comment by sbc100** [comment]
I'm pretty sure all our warnings can be disabled and will only show up as errors if you build with `-Werror`.

Closing for now, feel free to reopen.
