### ISSUE TITLE
Controversy in Emscripten documentation

### ISSUE THREAD

**Issue by dsuponitskiy** [emscripten-core/emscripten#20501]
https://emscripten.org/docs/porting/files/packaging_files.html#packaging-files:
"**Embedding files is much less efficient** than preloading and should only be used when packaging small numbers of small files. Preloading also enables the option to separately host the data."
**vs**
https://emscripten.org/docs/tools_reference/emcc.html#emcc-embed-file:
"**Embedding files is generally more efficient** than [preloading](https://emscripten.org/docs/tools_reference/emcc.html#emcc-preload-file) as it avoids copying the file data at runtime."

**Comment by kripken** [comment]
:smile: I think what happened here is that embedding used to mean encoding the data inside JS (using base64 or such) which was very slow. But then @sbc100 made it store the data inside the wasm itself in binary, which is actually better than preloading, but not all the docs were updated I suppose. @sbc100 does that sound right?

**Comment by sbc100** [comment]
Yup, docs just need updating I think
