### ISSUE TITLE
wgpuDeviceCreateSampler does not need to check descriptor

### ISSUE THREAD

**Issue by xdestiny110** [emscripten-core/emscripten#20523]
version of emcc: 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.47 (431685f05c67f0424c11473cc16798b9587bb536)

In library_webgpu.js, 
https://github.com/emscripten-core/emscripten/blob/a0a3f24b17a308791d417831d060a46b54f15fbd/src/library_webgpu.js#L905-L907
The above code requires descriptor is non-null.  

However, accroding from [https://www.w3.org/TR/webgpu/#dom-gpudevice-createsampler](https://www.w3.org/TR/webgpu/#dom-gpudevice-createsampler)，the descriptor is optional, which means we should not always require it to be non-null. Also, in webgpu_cpp.h,
https://github.com/emscripten-core/emscripten/blob/a0a3f24b17a308791d417831d060a46b54f15fbd/system/include/webgpu/webgpu_cpp.h#L970
it has a default value as nullptr.

BTW, we're willing to provide a PR.

**Comment by kainino0x** [comment]
Good catch, I agree with your conclusion. Would love to take a PR! Please @ me on it.
