### ISSUE TITLE
webgl: lot of functions fail when pointers go above 2GB

### ISSUE THREAD

**Issue by jspanchu** [emscripten-core/emscripten#20533]
Here's a list of functions we had to patch to use `>>>` instead of `>>`.

```c
_glClearBufferfv
_glClearBufferiv
_glClearBufferuiv
_glTexImage2D
_glTexImage3D
_glTexSubImage2D
 
_glReadPixels
 
_glUniform1fv
_glUniform1iv
_glUniform1uiv
_glUniform2fv
_glUniform2iv
_glUniform2uiv
_glUniform3fv
_glUniform3iv
_glUniform3uiv
_glUniform4fv
_glUniform4iv
_glUniform4uiv
 
_glUniformMatrix2fv
_glUniformMatrix2x3fv
_glUniformMatrix2x4fv
_glUniformMatrix3fv
_glUniformMatrix3x2fv
_glUniformMatrix3x4fv
_glUniformMatrix4fv
_glUniformMatrix4x2fv
_glUniformMatrix4x3fv
```

**Comment by kripken** [comment]
@juj I think you had a PR for that?

**Comment by Ono-Sendai** [comment]
I'm running into this issue as well.  Some examples (from Firefox:)

TypeError: WebGL2RenderingContext.uniform4fv: Float32Array branch of (Float32Array or sequence<unrestricted float>) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB

TypeError: WebGL2RenderingContext.compressedTexSubImage2D: Argument 8 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB

TypeError: WebGL2RenderingContext.bufferSubData: Argument 3 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB

This is from some C++ code compiled to WASM with Emscripten.
None of my buffers in my C++ code are greater than 2 GB in size, they are individually quite small.

**Comment by jspanchu** [comment]
Yup. That seems about correct. None of the buffers were bigger than 2GB. We ran into this issue when there were so many small buffers that memory addresses beyond 2GB were passed into gl functions. 

Data structures like transform matrices which maybe allocated and passed to glUniform at a later frame were the most hit by this issue.

**Comment by sbc100** [comment]
I believe all the issues in emscripten related to these function have now been fixed.   See #21268 and #21334.

What remain and browser implementation limits.   I wonder if there is already an open firefox bug for the  `...can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB` issue?

@Ono-Sendai would you mind opening a new issue for the `...can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB` firefox issue here in emscripten so we can close this one?

**Comment by Ono-Sendai** [comment]
It looks like there is an open issue for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1838218

Emscripten could work around this by copying or making new buffer views that are smaller than 2GB, to work around this Firefox limitation.

**Comment by sbc100** [comment]
@Ono-Sendai do you know if we can pass a smaller view of larger 2Gb+ array buffer?
