### ISSUE TITLE
Fullscreen scaling ignores canvas ratio

### ISSUE THREAD

**Issue by abergmeier** [emscripten-core/emscripten#2053]
When a canvas with a ratio 4:3 is created and then the canvas element is taken fullscreen, the canvas may be incorrectly scaled e.g. on a 16:10 display.

It would perhaps be better to get the screen size and calculate the necessary margins to keep the aspect ratio of the canvas.

**Comment by zobertke** [comment]
Just a small question related to this PR. What to do in the case of having the canvas in a container div with a temporary sibling (for ex. at a point we overlay over the canvas a video element to play some video and then detach it from the container not to kick in the compositor)? It is impossible to keep both in fullscreen, as with the current solution the canvas will detach from the container having a temporary div.
