### ISSUE TITLE
Building openssl-1.1.1w with emsdk

### ISSUE THREAD

**Issue by tony-is-working** [emscripten-core/emscripten#20539]
**Problem**
I have some crypto functions written in c++ using openssl.
I want to use those functions in javascript, so I use emsdk to build openssl.
Then I encountered bugs.
It seems configuration or makefile are not right.
How to fix it ? Does anyone succeed building openssl with emsdk ?

**Version of emscripten/emsdk:**
$emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.47 (431685f05c67f0424c11473cc16798b9587bb536)
clang version 18.0.0 (https://github.com/llvm/llvm-project 21030b9ab4487d845e29792063f5666d8c4b8e09)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/yinggao.jt/emsdk/upstream/bin

**Failing command line in full:**
If this is compile or link-time failure please include the full failing command
along with its entire output.

$wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz --no-check-certificate
$tar zxvf openssl-1.1.1w.tar.gz
$cd openssl-1.1.1w.tar.gz
$emconfigure ./config
configure: ./config
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1w (0x1010117fL) for linux-x32
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************

$emmake make
make: make
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _all
make[1]: Entering directory '/home/yinggao.jt/openssl-1.1.1w'
make[1]: Leaving directory '/home/yinggao.jt/openssl-1.1.1w'
make[1]: Entering directory '/home/yinggao.jt/openssl-1.1.1w'
/home/yinggao.jt/emsdk/upstream/emscripten/em/home/yinggao.jt/emsdk/upstream/emscripten/emcc  -I. -Iinclude -fPIC -pthread -mx32 -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG   -c -o apps/app_rand.o apps/app_rand.c
/bin/sh: /home/yinggao.jt/emsdk/upstream/emscripten/em/home/yinggao.jt/emsdk/upstream/emscripten/emcc: No such file or directory
make[1]: *** [Makefile:699: apps/app_rand.o] Error 127
make[1]: Leaving directory '/home/yinggao.jt/openssl-1.1.1w'
make: *** [Makefile:172: all] Error 2
emmake: error: 'make' failed (returned 2)

$vi Makefile
CROSS_COMPILE=/home/yinggao.jt/emsdk/upstream/emscripten/em
CC=$(CROSS_COMPILE)/home/yinggao.jt/emsdk/upstream/emscripten/emcc
CXX=$(CROSS_COMPILE)/home/yinggao.jt/emsdk/upstream/emscripten/em++
CPPFLAGS=
CFLAGS=-Wall -O3
CXXFLAGS=-Wall -O3
LDFLAGS=
EX_LIBS=

MAKEDEPEND=

PERL=/usr/bin/perl

AR=$(CROSS_COMPILE)/home/yinggao.jt/emsdk/upstream/emscripten/emar
ARFLAGS= r
RANLIB=$(CROSS_COMPILE)/home/yinggao.jt/emsdk/upstream/emscripten/emranlib
RC= $(CROSS_COMPILE)windres
RCFLAGS=

** System environment **
$gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$cat /etc/issue
Alibaba Group Enterprise Linux Server release 7.2 (Paladin)
Kernel \r on an \m

It is a Centos-based system.

**Comment by sbc100** [comment]
The important error message here looks like `/bin/sh: /home/yinggao.jt/emsdk/upstream/emscripten/em/home/yinggao.jt/emsdk/upstream/emscripten/emcc: No such file or directory`

Does `/home/yinggao.jt/emsdk/upstream/emscripten/em/home/yinggao.jt/emsdk/upstream/emscripten/emcc` exist?  Can you run `/home/yinggao.jt/emsdk/upstream/emscripten/em/home/yinggao.jt/emsdk/upstream/emscripten/emcc --version`?

**Comment by sbc100** [comment]
Ah I see the issue:

```
CROSS_COMPILE=/home/yinggao.jt/emsdk/upstream/emscripten/em
CC=$(CROSS_COMPILE)/home/yinggao.jt/emsdk/upstream/emscripten/emcc
CXX=$(CROSS_COMPILE)/home/yinggao.jt/emsdk/upstream/emscripten/em++
```

This should just be:

```
CROSS_COMPILE=/home/yinggao.jt/emsdk/upstream/emscripten/em
CC=$(CROSS_COMPILE)cc
CXX=$(CROSS_COMPILE)++
```

Also, if you are configuring the `Makefile` directly like that then I don't think you need to use `emmake`.. you can just run `make`

**Comment by tony-is-working** [comment]
Ok, i fixed the Makefile and run `make`, the output still has error:
```shell
$make
make depend && make _all
make[1]: Entering directory '/home/yinggao.jt/openssl-1.1.1w'
make[1]: Leaving directory '/home/yinggao.jt/openssl-1.1.1w'
make[1]: Entering directory '/home/yinggao.jt/openssl-1.1.1w'
/home/yinggao.jt/emsdk/upstream/emscripten/emcc -fPIC -pthread -mx32 -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG  -c -o crypto/aes/aesni-mb-x86_64.o crypto/aes/aesni-mb-x86_64.s
clang++: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_USE_NODELETE' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D L_ENDIAN' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_PIC' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_CPUID_OBJ' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_IA32_SSE2' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_BN_ASM_MONT' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_BN_ASM_MONT5' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSL_BN_ASM_GF2m' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D SHA1_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D SHA256_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D SHA512_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D KECCAK1600_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D RC4_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D MD5_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D AESNI_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D VPAES_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D GHASH_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D ECP_NISTZ256_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D X25519_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D POLY1305_ASM' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D OPENSSLDIR="/usr/local/ssl"' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D ENGINESDIR="/usr/local/lib/engines-1.1"' [-Wunused-command-line-argument]
clang++: warning: argument unused during compilation: '-D NDEBUG' [-Wunused-command-line-argument]
crypto/aes/aesni-mb-x86_64.s:7:8: error: invalid alignment value
.align  32
        ^
crypto/aes/aesni-mb-x86_64.s:10:7: error: Unexpected token in operand: $
        cmpl    $2,%edx
                ^
crypto/aes/aesni-mb-x86_64.s:11:2: error: invalid instruction
        jb      .Lenc_non_avx
        ^
crypto/aes/aesni-mb-x86_64.s:12:26: error: Expected ,, instead got: (
        movl    OPENSSL_ia32cap_P+4(%rip),%ecx
                                   ^
crypto/aes/aesni-mb-x86_64.s:13:8: error: Unexpected token in operand: $
        testl   $268435456,%ecx
                ^
crypto/aes/aesni-mb-x86_64.s:14:2: error: invalid instruction
        jnz     _avx_cbc_enc_shortcut
        ^
crypto/aes/aesni-mb-x86_64.s:15:2: error: invalid instruction
        jmp     .Lenc_non_avx
        ^
crypto/aes/aesni-mb-x86_64.s:18:7: error: Unexpected token in operand: %
        movq    %rsp,%rax
                ^
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/yinggao.jt/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fPIC -pthread -mx32 -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR=\"/usr/local/ssl\" -DENGINESDIR=\"/usr/local/lib/engines-1.1\" -DNDEBUG -c -matomics -mbulk-memory crypto/aes/aesni-mb-x86_64.s -o crypto/aes/aesni-mb-x86_64.o
#0 0x000055e63d0502b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/yinggao.jt/emsdk/upstream/bin/clang+++0x2ce72b8)
#1 0x000055e63d04d90e llvm::sys::RunSignalHandlers() (/home/yinggao.jt/emsdk/upstream/bin/clang+++0x2ce490e)
#2 0x000055e63d04f55e llvm::sys::CleanupOnSignal(unsigned long) (/home/yinggao.jt/emsdk/upstream/bin/clang+++0x2ce655e)
#3 0x000055e63cfafbe9 CrashRecoverySignalHandler(int) (.llvm.14972460974340508749) CrashRecoveryContext.cpp:0:0
#4 0x00007f8f2b721630 __restore_rt sigaction.c:0:0
#5 0x000055e63be70523 llvm::SmallVectorTemplateBase<std::__2::unique_ptr<llvm::MCParsedAsmOperand, std::__2::default_delete<llvm::MCParsedAsmOperand>>, false>::reserveForParamAndGetAddress(std::__2::unique_ptr<llvm::MCParsedAsmOperand, std::__2::default_delete<llvm::MCParsedAsmOperand>>&, unsigned long) WebAssemblyAsmParser.cpp:0:0
#6 0x000055e63be6a318 (anonymous namespace)::WebAssemblyAsmParser::ParseInstruction(llvm::ParseInstructionInfo&, llvm::StringRef, llvm::SMLoc, llvm::SmallVectorImpl<std::__2::unique_ptr<llvm::MCParsedAsmOperand, std::__2::default_delete<llvm::MCParsedAsmOperand>>>&) WebAssemblyAsmParser.cpp:0:0
clang++: error: clang integrated assembler command failed with exit code 139 (use -v to see invocation)
clang version 18.0.0 (https://github.com/llvm/llvm-project 21030b9ab4487d845e29792063f5666d8c4b8e09)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/yinggao.jt/emsdk/upstream/bin
clang++: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
emcc: error: '/home/yinggao.jt/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fPIC -pthread -mx32 -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines-1.1" -DNDEBUG -c -matomics -mbulk-memory crypto/aes/aesni-mb-x86_64.s -o crypto/aes/aesni-mb-x86_64.o' failed (returned 1)
make[1]: *** [Makefile:737: crypto/aes/aesni-mb-x86_64.o] Error 1
make[1]: Leaving directory '/home/yinggao.jt/openssl-1.1.1w'
make: *** [Makefile:172: all] Error 2
```
I modified variables which use $CROSS_COMPILE in the makefile:
```shell
CROSS_COMPILE=/home/yinggao.jt/emsdk/upstream/emscripten/em
CC=$(CROSS_COMPILE)cc
CXX=$(CROSS_COMPILE)++
AR=$(CROSS_COMPILE)ar
RANLIB=$(CROSS_COMPILE)ranlib
RC= $(CROSS_COMPILE)windres
```
So how to fix the new bug?

**Comment by sbc100** [comment]
You won't be able to compiler those x86 assembly files (such as `crypto/aes/aesni-mb-x86_64.s`) using emscripten.    You would need to configure openssl not to build those and to use the `.c` alternatives, assuming they exist.

**Comment by tony-is-working** [comment]
You are right. I add `no-asm` to `emconfigure ./config no-asm` and this passes.
But now the new error comes:
```shell
emcc: warning: linking a library with `-shared` will emit a static object file.  This is a form of emulation to support existing build systems.  If you want to build a runtime shared library use the SIDE_MODULE setting. [-Wemcc]
emcc: warning: ignoring unsupported linker flag: `-soname=libcrypto.so.1.1` [-Wlinkflags]
emcc: warning: ignoring unsupported linker flag: `--version-script=libcrypto.map` [-Wlinkflags]
/home/yinggao.jt/emsdk/upstream/bin/wasm-ld: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/yinggao.jt/emsdk/upstream/bin/wasm-ld)
emcc: error: '/home/yinggao.jt/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_3ywjrqco.rsp.utf-8' failed (returned 1)
make[1]: *** [Makefile:711: libcrypto.so] Error 1
make[1]: Leaving directory '/home/yinggao.jt/openssl-1.1.1w'
make: *** [Makefile:172: all] Error 2
```
I searched and found that centos7 has GLIBC_2.17 but GLIBC_2.18 is required.
Upgrading to GLIBC_2.18 may be harmful.

So is there a tested os that can build openssl successfully using emsdk?
My goal is to compile two functions (encrypt & decrypt) in c++ to javascript functions and use them in javascript.
It would be grateful if you could tell me what I should do to solve the problem.

**Comment by sbc100** [comment]
I recommend disabling shared library support and just building a static library.  This is normally done via something like `--disable-shared`.

**Comment by tony-is-working** [comment]
I've tried everything but still cannot get it right.
I'm going to give up.
The most related question I found is: [stackoverflow-openssl](https://stackoverflow.com/questions/52327290/linking-openssl-with-webassembly)
The most related github is: [web-assembly-crypto](https://github.com/lneir/web-assembly-crypto)
I guess the wasm and emsdk have changed a lot since those posts.

**Comment by tony-is-working** [comment]
I'm not an expert in c compiler toolchains.
Maybe I will try it later.
