### ISSUE TITLE
Issues with `Asyncify.handleAsync` in Emscripten FS device

### ISSUE THREAD

**Issue by patrickcorrigan** [emscripten-core/emscripten#20566]
I've been experimenting with creating a filesystem (FS) device in Emscripten that has asynchronous callbacks. My goal is to leverage `Asyncify.handleAsync` to manage these asynchronous operations.

**Question**: Is it feasible to use asynchronous callbacks in this manner with the Emscripten FS? Are the FS callbacks structured to handle methods that have been wrapped with `Asyncify`?

While trying to implement this, I encountered this error:

```plaintext
start is not a function
    at Object.doRewind
```

from `doRewind`

```javascript
doRewind(ptr) {
    var start = Asyncify.getDataRewindFunc(ptr);
    // Once the stack has been rewound, we don't need to artificially keep the runtime alive.
    runtimeKeepalivePop();
    return start();
}
```

This is the custom FS device I'm working on:

```javascript
mountFakeDevice() {
    console.log('mounting fake device');
    const deviceOps = {
        open: function(stream) {
            console.log('dev ops open called', stream);
        },
        close: function(stream) {
            console.log('dev ops close called', stream);
        },
        read: function(stream, buffer, offset, length, position) {
            console.log('dev ops read called', stream, buffer, offset, length, position);
            return Module.Asyncify.handleAsync(async function() {
                return length;
            });
        },
        write: function(stream, buffer, offset, length, position) {
            console.log('dev ops write called');
            return length;
        },
        llseek: function(stream, offset, whence) {
            console.log('dev ops write called');
            return length;
        }
    };
    var id = Module.FS.makedev(64, 0);
    Module.FS.registerDevice(id, deviceOps);
    Module.FS.mkdev('/dummy', id);
}
```

Any insights or guidance on this matter would be highly appreciated. If this approach isn't viable, I'd like to know so I can explore other solutions :)

Thank you in advance for your assistance :)

**Comment by kripken** [comment]
The normal FS would need some work, as the JS there is not async-friendly. But WasmFS works with this today, see the OPFS backend in particular:

https://github.com/emscripten-core/emscripten/blob/main/src/library_wasmfs_opfs.js

**Comment by patrickcorrigan** [comment]
Thanks @kripken :)

My plan was to implement a fake device that allowed reading one large file in OPFS without loading the whole thing into memory. I tried using WORKERFS but my code doesn't run with `-s PROXY_TO_PTHREAD` as I get some `WebGL` errors. 

In the end I created a web worker that would call the synchronous OPFS read and write methods and used  https://github.com/GoogleChromeLabs/comlink to make interacting with it easier. When I was about to run it I was like wait a second.... these methods probably need to be synchronous 😅 So then I tried using Asyncify and ended up here :)

If I were to build with `-S WASMFS` what do you think the easiest way to allow reading one large file from OPFS is? I just need to read from it. No writing. I don't need persistence for any other files on the file system.  

Am I right in thinking that WASMFS doesn't have the same JS api yet for mounting? I'm happy to write some c to mount the file from OPFS to the filesystem if needed.

Thank you so much for your help I really appreciate it. Even if you just point me in the right direction I would be very greatful

From what you said about WASMFS I could create a fake device there that read from my OPFS filesystem using the web worker I created but it looks like there is an OPFS backend for WASMFS that I could maybe use instead?

**Comment by kripken** [comment]
> If I were to build with -S WASMFS what do you think the easiest way to allow reading one large file from OPFS is? I just need to read from it. No writing. I don't need persistence for any other files on the file system.

Just doing `FS.read` should work if you use the OPFS backend (see below). Make sure to build with `-sFORCE_FILESYSTEM` to include the full JS API, including `FS.read`. (You don't need that if you read from C - in that case, just a normal read.)

> Am I right in thinking that WASMFS doesn't have the same JS api yet for mounting? I'm happy to write some C to mount the file from OPFS to the filesystem if needed.

There is minimal mounting support,

https://github.com/emscripten-core/emscripten/blob/b7c778ebf6300363c835a3c2aab16cdcdc29f970/src/library_wasmfs.js#L346-L356

The backend needs to define that `createBackend` method.  Looks like OPFS lacks that, but e.g. NODEFS does, and its simple to add,

https://github.com/emscripten-core/emscripten/blob/b7c778ebf6300363c835a3c2aab16cdcdc29f970/src/library_nodefs.js#L8-L14

> From what you said about WASMFS I could create a fake device there that read from my OPFS filesystem using the web worker I created but it looks like there is an OPFS backend for WASMFS that I could maybe use instead?

Yes, I would just use the existing OPFS backend. It is being used in production already, so it's very stable, but it may be missing minor things (like mount support as I said - PRs welcome if you find stuff to fix!)

**Comment by patrickcorrigan** [comment]
Thanks @kripken, 

I've spend the last few days trying to get things working. I think what's causing most of my issues is not being able to run my Emscripten Module in a worker. I get GL errors, I've tried `proxyToPthread`, `proxyToWorker`, using `MODULARIZE` and creating my own worker but I'm not having any success.

What I'm trying to achieve is read a large file without bringing it into memory. It's about 600mb and crashes iOS safari if I do. I just need to read it not write anything.

I've tried using using the OPFS filesystem and disabling assertions to get past the check of it being in a worker or the browser having JSPI support but when I read the mounted OPFS directory it's just empty but I do have files in my OPFS. Do I need to call a sync method? 

I've looked at the OPFS tests but I can't see anything to do with syncing there. 

I thought I might be able to hack a fake devices with my own async steaming methods which does work with WASFS as it seems to support using async streaming methods , but the device has a size of 0 (which makes sense) so after the first read it finishes. I was thinking I could use `lookUpPath` to get a node and modify it's stream methods and its size but WASMFS doesn't seem to have a lookUpPath method. 

What do you think the best thing to do is? Should I just concentrate on getting the Module to run in a worker?

**Comment by patrickcorrigan** [comment]
Marking this as @kripken solved the original issue. If you want to use async stream methods you can with WASMFS :) Thank you

**Comment by kripken** [comment]
I'm not sure about OPFS, but another option here is to use a Blob. At least some browsers optimize files in Blobs to not load them entirely into memory. That is what the WORKERFS filesystem is based on. (But you'd still have issues with needing to run in a worker. GL at least should have proxying support already, so you might be hitting a bug there?)
