### ISSUE TITLE
--print-target-triple shouldn't require input files

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#20588]
When using `-print-target-triple` / `--print-target-triple` with CFLAGS and no other arguments, Clang prints it but Emscripten errors out with "no input files" as it seems to try and run the compilation phase:

```
> clang -print-target-triple
x86_64-pc-linux-gnu
> emcc -print-target-triple
emcc: error: no input files
```

This is easy to work around with

```
> emcc -print-target-triple /dev/null -E
wasm32-unknown-emscripten
```

but Emscripten should probably match Clang's behaviour.

**Comment by sbc100** [comment]
Looks like an easy fix.

BTW, is there some reason you are using that over the more standard (i.e. also supported by gcc) `-dumpmachine`, which emcc does seem to fully support.

**Comment by RReverser** [comment]
> BTW, is there some reason you are using that over the more standard (i.e. also supported by gcc) `-dumpmachine`, which emcc does seem to fully support.

None tbh. I thought this one was more standard, but now I see it's not.
