### ISSUE TITLE
callMain vs. ccwrap/ccall documentation

### ISSUE THREAD

**Issue by qknight** [emscripten-core/emscripten#20599]
I see **cwrap/ccall** and **EM_JS** is well integrated in the documentation at https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html 

Using **callMain** on the other hand is not mentioned at all (except in the API references)

I've been using:

* **EM_JS** at https://lastlog.de/blog/ruckig_motion_planning.html
* **callMain** a lot at https://lastlog.de/blog/tour_of_nix.html#implementation

I think I also used cwrap/ccall in a project but don't have a reference here.

# Proposal

I'd like to add a section for **callMain** in this https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html for using callMain.

I also like the chatgpt summary https://chat.openai.com/share/5b555265-fbb5-498b-83f3-c17d09f40311

Thoughts?

**Comment by sbc100** [comment]
Can you explain why you need to call `callMain` directly? 

I'm hoping most folks should not need to do that, and it would be great if we could avoid making part of the official/recommended API.

**Comment by qknight** [comment]
@sbc100 calling callMain basically let's me call the program from the command line like with arguments. Is there some equivalent for doing so without having to write a new function to call into the program I want to port to javascript/wasm?

So you advice to only use cwrap/ccall, is that right?

**Comment by sbc100** [comment]
Yes, the recommended way to pass argument is to set `Module['arguments']` before loading your module.

**Comment by sbc100** [comment]
I'm not sure what you mean by `only use cwrap/ccall`.. there are lots ways to interact with your module, `cwrap/ccall` is just one of them.  See https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

**Comment by qknight** [comment]
@sbc100 In my code i use Module['arguments'] as you mentioned already, see:

```
var input_text = editor.getValue();
    FS.writeFile('/test.nix', input_text, {encoding: 'utf8'});
    Module['arguments'] = ['-I', 'nixpkgs=nixpkgs', '--eval', '--strict', '--show-trace', '/test.nix'];
    Module.callMain(Module['arguments'])
```

So how should I call the **main()** function in the cpp instead? Should I modify the code and add 'another' function which replaces the original main() function of the code?

**Comment by sbc100** [comment]
Normally `main` run only once.   If you want to call something more than once its best not to use `main`.

If you just want to call main one you can specify `Module['arguments']` before the module is loaded.   Its read as the module is loaded.   See https://emscripten.org/docs/api_reference/module.html#creating-the-module-object.

If you want to use the `main` function and call it more than once you should really re-instantiate the module each time.  See the `MODULARIZE` setting for how to do this.

If you want to use the same module instance and call a function more than once then its best to avoid `main` and create a new C/C++ function that you can call that doesn't have the assumption of being called only once.
