### ISSUE TITLE
Use Embind in dynamically-loaded side module

### ISSUE THREAD

**Issue by Y--** [emscripten-core/emscripten#20612]
Hi,

First thanks a lot for this great project!

I am trying to build a side module that is `dlopen`-ed by a main module and depends on Embind symbols that are (if I [understand correctly](https://github.com/emscripten-core/emscripten/blob/8ecbdb3fc694f659aadb85a00d80777b20477281/src/embind/emval.js#L132-L136)) defined in the JS library such as `_emval_take_value`.

Here is a simple reproduction of my issue: https://github.com/Y--/wasm-dlopen-embind

I am using Emscripten 3.1.46.

This is probably related to [this issue](https://github.com/emscripten-core/emscripten/issues/16711), though I am not entirely sure.

Reading [this section](https://emscripten.org/docs/compiling/Dynamic-Linking.html#system-libraries) of the documentation it seems possible to force the main module to include "system libraries" symbols, though adding `EMCC_FORCE_STDLIBS=1` to environment variables when building the main module doesn't seem to solve the problem.

Could you confirm my understanding and hopefully provide a solution to this issue?

Many thanks in advance!

**Version of emscripten/emsdk:**
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46 (19607820c447a13fd8d0b7680c56148427d6e1b8)
clang version 18.0.0 (https://github.com/llvm/llvm-project 75501f53624de92aafce2f1da698b249a7293dc7)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/y/workspace/emsdk-latest/upstream/bin
```

**Comment by sbc100** [comment]
For refererence the error from the linked repo is:

```
Starting side_func
Got typed_memory_view
hello.js:675 Aborted(Assertion failed: undefined symbol '_emval_take_value'. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
[... stack ...]
hello.js:694 Uncaught (in promise) RuntimeError: Aborted(Assertion failed: undefined symbol '_emval_take_value'. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
    at abort (hello.js:694:11)
    at assert (hello.js:368:5)
    at resolveSymbol (hello.js:1883:11)
    at stubs.<computed> (hello.js:1916:43)
    at b9fa315a:0x991
    at stubs.<computed> (hello.js:1920:33)
    at b9fa315a:0x8b7
    at hello.wasm:0x8e94a
    at hello.wasm:0x8e999
    at callMain (hello.js:38055:15)
```

**Comment by Y--** [comment]
I was able to make it work by adding `-lembind` to the main module compilation. But it doesn't work when I add it to the side module command. Is that something that could work in the future?

**Comment by sbc100** [comment]
Ah yes, that makes sense.  

When you link the main module do you pass the side module?  The best way to get an optimized main module is to link with `-sMAIN_MODULE=2` and then also pass the side module on the command line.  This should give you all the undefined symbol errors at build time and will also result in an optimized main module.    If you don't want to side module to auto-load on startup you can also pass `-sAUTOLOAD_DYLIBS=0`. e.g

```
$ emcc -sMAIN_MODULE=2 -sAUTOLOAD_DYLIBS=0 main.c libside.so
```

**Comment by Y--** [comment]
> When you link the main module do you pass the side module?

I actually don't. The idea is that the main module is produced by a different team/company and I'm providing an extension/plugin if you want.

That is why, I would like to link `embind` in my side module rather than in the main module. Do you know if that is/will be feasible?

Thanks!

**Comment by sbc100** [comment]
> > When you link the main module do you pass the side module?
> 
> I actually don't. The idea is that the main module is produced by a different team/company and I'm providing an extension/plugin if you want.
> 
> That is why I would like to link `embind` in my side module rather than in the main module. Do you know if that is/will be feasible?
> 
> Thanks!

No, you can't link JS library code into a side module, that all gets linked in when the main module is built.

The downside of using `-sMAIN_MODULE=1` (rather than `-sMAIN_MODULE=2`) is that we can't do any dead code elimination so your main module will be very big.

**Comment by Y--** [comment]
I see. Thanks for confirming!
