### ISSUE TITLE
Where is the emsdk.bat?

### ISSUE THREAD

**Issue by wxfred** [emscripten-core/emscripten#20640]
According to https://emscripten.org/docs/getting_started/downloads.html,
**On Windows, run emsdk.bat instead of ./emsdk, and emsdk_env.bat instead of source ./emsdk_env.sh.**

I can't find emsdk.bat on github now, anyone help?

**Comment by sbc100** [comment]
emsdk.bat is part of emsdk.   The instructions for install it on that page: https://emscripten.org/docs/getting_started/downloads.html#installation-instructions-using-the-emsdk-recommended

**Comment by wxfred** [comment]
@sbc100 Thanks, didn't figure out there are two repositories.
