### ISSUE TITLE
wasm-ld-13: error: unknown file type: e_aes.o

### ISSUE THREAD

**Issue by lenninghuiliu** [emscripten-core/emscripten#20652]
I'm using emcc to compile a C code that uses Openssl.

emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.5 ()
Ubuntu clang version 13.0.1-2ubuntu2.2
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /usr/bin

emcc AES1.c -o AES1.js -lcrypto -I/usr/local/include -L/usr/local/lib

wasm-ld-13: error: unknown file type: e_aes.o
emcc: error: '/usr/bin/wasm-ld-13 -o AES1.wasm /tmp/emscripten_temp_zkqdknpj/AES1_0.o /usr/local/lib/libcrypto.a -L/usr/local/lib -L/usr/share/emscripten/cache/sysroot/lib/wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__stdio_exit --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (returned 1)

**Comment by sbc100** [comment]
In general you can't use the libraries found in `/usr/local/lib` with emscripten.  Those libraries are (normally) system libraries for the host OS and not built with emscripten.  This is what the `unknown file type` means... most likely that file is an ELF or machO object files rather than a wasm object file.

**Comment by lenninghuiliu** [comment]
I have used emmake, but this error still occurs

**Comment by lenninghuiliu** [comment]
The problem is solved 
@sbc100 Thank you
