### ISSUE TITLE
Unsure how to return null-terminated array of pointers

### ISSUE THREAD

**Issue by willcohen** [emscripten-core/emscripten#20659]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.47-git
clang version 16.0.6
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /nix/store/gd3hl3r1g5a80w6k0d3k4md5a7v9id35-emscripten-llvm-3.1.47/bin

**Issue**
I am trying to access a [null-terminated list of null-terminated strings](https://proj.org/en/9.3/development/reference/datatypes.html#c.PROJ_STRING_LIST). If I take the original pointer to this list, use `getValue` on it, and run `UTF8ToString` on that result, I get the first null-terminated string. If I don't have access to a worker thread or `TextDecoder`, is there a way to instead return the array of pointers, which themselves point to the strings? I don't have a fixed a number of bytes, but instead need to scan till I hit a null terminator. The JNA equivalent of this would be [getPointerArray](https://java-native-access.github.io/jna/4.2.1/com/sun/jna/Pointer.html#getPointerArray-long-).

**Comment by willcohen** [comment]
Barring some kind of helper function, the low-ish level way would be to offset the pointer by the length of the returned value from `UTF8ToString`, get the value of that offset value and turn it into a string, and repeat until the returned string is itself null. This may be the simplest solution here.

**Comment by sbc100** [comment]
If you are have an array of pointers then you would just want to increase the original pointer by 4 (or `{{{ POINTER_SIZE }}}`  if you are JS library code) each time around the loop.

Something like this in your JS code should do it:

```
function forEachUTF8String(null_terminated_pointer_list, callback) {
   // Loop will end when null pointer is read from list 
   while (let strptr = getValue(null_terminated_pointer_list, '*')) {
     // Each pointer in the list points to a UTF8 string
     callback(UTF8TString(strptr));
     null_terminated_pointer_list += 4;
   }
}
```

**Comment by sbc100** [comment]
Of if you want to instead return list of pointer from JS when you would do something like this:

```
function stringArrayToPointerList(jsStrings) {
  let rtn = malloc(jsStrings.length) * 4;
  var offset = 0;
  for (let str of jsStrings) {
    setValue(rtn + offset, stringToNewUTF8(str), '*');
    offset += 4;
  }
  return rtn;
}
```

Bare in mind these are example of how to do this type of thing that the lowest level.   There are also higher level options in https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html.   For example I think you can do this with cwrap using `['string']` in the signature since it knows how to handle strings (char*) and also arrrays.

**Comment by willcohen** [comment]
Of course. Thank you so much!
