### ISSUE TITLE
About async method in library_webgpu.js

### ISSUE THREAD

**Issue by xdestiny110** [emscripten-core/emscripten#20668]
I noticed that several async methods in WebGPU, including `wgpuDeviceCreateRenderPipelineAsync` and `wgpuShaderModuleGetCompilationInfo`, have not been implemented yet. Do you have a timeline or plan for their implementation? If there are plans for implementing these functions, I am willing to contribute code.

**Comment by kainino0x** [comment]
I totally forgot we hadn't implemented wgpuDeviceCreate{Compute,Render}PipelineAsync. We're going to be refactoring all of the async code _soonish_, so I won't plan to implement them now. But if these methods are useful to you then I'd be happy to accept a contribution!

**Comment by xdestiny110** [comment]
@kainino0x I'm glad to hear that things will be refactored! I have some of the methods implemented already and I'd like to submit a PR.
BTW, I observed significant changes in webgpu_native, such as removing swapchain and moving related functionality into surface. How will the synchronization in this regard be approached?

**Comment by kainino0x** [comment]
> BTW, I observed significant changes in webgpu_native, such as removing swapchain and moving related functionality into surface. How will the synchronization in this regard be approached?

The changes in https://github.com/webgpu-native/webgpu-headers/pull/203 are modeled after what wgpu has, so it would be best to look at their documentation. Maybe here https://docs.rs/wgpu/latest/wgpu/type.SurfaceConfiguration.html#structfield.present_mode
