### ISSUE TITLE
Embind is slow without DYNAMIC_EXECUTION

### ISSUE THREAD

**Issue by brendandahl** [emscripten-core/emscripten#20673]
`DYNAMIC_EXECUTION=0` mode is much slower than `DYNAMIC_EXECUTION=1`. This is of course is expected, but I think it can be improved. Also, while `DYNAMIC_EXECUTION=1` is the default for emscripten, we've found that many users disable this since `Function/eval` is often not permitted by CSP.

**Idea**
To improve the speed my plan is to use a similar code pathway as the TypeScript definition generation feature for embind, but instead generate JS glue code that would be incorporated into the JS output file. This would allow sites that don't permit `Function` to have the same speed as when `DYNAMIC_EXECUTION` is allowed. 

**Downsides**
While this would improve performance, this does have some potential downsides:

1. Code size could potentially increase - if there are many glue functions, the generated code could bloat the JS. In practice though,  most large projects don't have that many bindings and the glue code is small (especially when minified). The bloat is also offset by the fact that the "jitting" code no longer needed in the final output. Another way this could be offset is with dead code elimination (see long term vision below).
2.  Building is more complicated - similar to the TS generation, the wasm binary will need to be run in node during the build process to build the JS definitions. While the overhead is pretty low, it does create a failure point where the binary may not be able to be run in node.

**Potential Options:**
1. Add a third `DYNAMIC_EXECUTION=3` option - In this mode, AOT JS generation would be enabled, and we'd keep the previous two modes as is. The big downside of this is now we'd have to support three modes.
2. Remove `DYNAMIC_EXECUTION` all together from `embind.js` - With this change we'd always AOT generate the JS and only have to support this one mode. The downsides of this are mentioned above.
3. Replace `DYNAMIC_EXECUTION=0` with AOT generation mode - This is a compromise between the first two options. We'd still have two modes, but if you want to disable JITing you have to use AOT.

**Longer Term Vision**
The initial version would be just to get back to the same performance level as `DYNAMIC_EXECUTION=1`, but I think we could do even better in the future. 
1) Improve the AOT generated code to directly call function pointers when it's possible and we don't wire type translation or to go through a single invoker function. This would further improve perfomance and allow perf to be near "raw" wasm export speed.
2) The AOT generated JS code could be static enough that it would allow dead code elimination (DCE) to be performed. We'd have to teach the DCE tool about function pointers and how to remove them, but it should be possible.

**Benchmarks**
Comparisons below from the `embind_benchmark` in the repo. (note: that the overhead is even worse when more arguments are added).

| | DYN (ms)      | NO_DYN (ms) |
| ---- | ----------- | ----------- |
| JS embind sum_float | 23 | 184 |
| JS embind sum_int 100000 | 19 | 125 |
| JS embind increment_counter 100000 | 21   |     71   |
| JS embind increment_class_counter 100000 | 22 | 81 |
| JS embind move_gameobjects | 19 | 26 |

**Comment by brendandahl** [comment]
\cc @sbc100 @kripken @RReverser I'd be curious to hear your thoughts, especially on "Potential Options".

**Comment by sbc100** [comment]
`while DYNAMIC_EXECUTION=0 is the default for emscripten`  i think you mean =1?

**Comment by sbc100** [comment]
I love this idea.   @RReverser has speculated that is could actually be code size win in many cases since the generator code that we need to ship is pretty big/complex and can't be DCE'd at all.

Regarding the options, I think our long term goal would be to opt remove the current `-sDYNAMIC_EXECUTION=0` code path in favor of AOT.

In the short term I think a new option such as `-sEMBIND=AOT` is probably the right way to go. 

I don't love `-sDYNAMIC_EXECUTION=2` because `DYNAMIC_EXECUTION` is a setting that applies to several parts of emscripten, not just embind.

If AOT proves to be a win in most cases we could even consider completely removing the runtime stuff one day!

**Comment by kripken** [comment]
> While the overhead is pretty low, it does create a failure point where the binary may not be able to be run in node.

In what situations can the binary not be run in node? I assume this is a simplified version of the binary - we just need to execute some startup code, not actually get to executing user code? But maybe I don't understand what "run in node" means here.

**Comment by sbc100** [comment]
I can imagine link flags that probably don't make any sense under node, for example `-sAUDIO_WORKLET`  or `-sFETCH`.. I'm not sure if there are any that cause link-time errors, but its possible.

**Comment by brendandahl** [comment]
Yeah, it seems pretty unlikely to be an issue the more I think about it. I was also imagining a situation where a user builds for web and targets some wasm feature that node doesn't support yet. In practice, this probably won't be an issue since node will usually follow the web or have flags to enable the experimental feature.

**Comment by kripken** [comment]
Got it, thanks!

In that case I think my views are basically the same as @sbc100 's here: https://github.com/emscripten-core/emscripten/issues/20673#issuecomment-1804419281 (long-term remove `-sDYNAMIC_EXECUTION=0` in favor of AOT, short term embind flag).

**Comment by RReverser** [comment]
I'm definitely in favour of AOT. I had a bit different idea in terms of implementation, but then I didn't consider approach that TSD took.

Instead I was thinking that we could use C++ constexpr - which nowadays allows compile-time construction of string literals - to generate static strings that would be recognised just like output of EM_ASM.

So it would do same thing as EM_ASM, except a C++ `em_asm<"someStaticJS(", templateSubst, "anotherStaticJS", ...>` would allow to construct any pieces of JS Embind needs entirely at compile-time while preserving all the functionality currently produced by `new Function`.

Your approach would probably be much easier to implement though, at the extra compilation cost of running this extra preprocessing pass. I don't have personal opinion on which tradeoff is right here, and would be happy to see any AOT implementation happen.
