### ISSUE TITLE
Decoder.js generated by emscripten V3.1.42 loaded in iPhone11 error

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#20697]
we load the Decoder.js  generated by emscripten V3.1.42, it load failed in iPhone11. the error is 
`failed to asynchronously prepare wasm : CompileError: WebAssembly.Module doesn't parse at byte 30: invalid opcode 193,in function at index 13`,

if compile the Decoder.js by emscripten V2.0.30 , it could loaded success in  iphone11 .

**Comment by sbc100** [comment]
Can you share the full set of link flags you are using to build your module?

Can you disassembly function 13 to see what this opcode is?  (e.g. using wasm-objdump).

**Comment by yangfangfang1204** [comment]
the link flags :
`emcc --bind STPlayer1.a ./lib/web/*.a  -s "EXPORTED_RUNTIME_METHODS=['ccall', 'getValue','writeArrayToMemory','print','UTF8ToString','cwrap','malloc','addOnPostRun','setValue']" -s EXPORTED_FUNCTIONS="['_Play','_Stop']" -s INITIAL_MEMORY=128MB -s ALLOW_MEMORY_GROWTH=0 -s ENVIRONMENT=web,worker -s USE_PTHREADS=0 -I../../include  -Wall -DHK_WEBJS -O3`

**Comment by sbc100** [comment]
Ah I see the problem.   Opcode 193 is the `i32.extend16_s` which is part of the Sign-extension operations proposal which we not include support for by default.    See https://webassembly.org/roadmap/.  It looks like it was added in Safai 14.1.  

So you know what Safari version you are trying to run on?   For example if you build with `-sMIN_SAFARI_VERSION=13000` (i.e. 13.0.0) then your binary should not contain that opcode.

**Comment by yangfangfang1204** [comment]
the iphone11 os 14.4.2 , i can't the safari version

**Comment by sbc100** [comment]
It looks like there is some more detail on the roadmap: `Supported in desktop Safari since 14.1 and iOS Safari since 14.5`.   Can you try building `-sMIN_SAFARI_VERSION=14000` and see if that fixes it?

**Comment by sbc100** [comment]
Here is how you can check the version of safari on your device: https://www.lifewire.com/check-the-version-number-of-safari-446563

**Comment by yangfangfang1204** [comment]
thanks, i  building`-sMIN_SAFARI_VERSION=13000` fixes it.
we hope the decoder.js could loaded in iphone 11/android/iphone 12...., so should we set `-sMIN_SAFARI_VERSION=13000` or `-sMIN_SAFARI_VERSION=14000` ?

**Comment by sbc100** [comment]
I think `-sMIN_SAFARI_VERSION=14000` should be enough.

**Comment by yangfangfang1204** [comment]
ok, thanks very much, i colse with comment
