### ISSUE TITLE
can i convert llvm bitecode(.bc file or .ll filei) to js, wasm ?

### ISSUE THREAD

**Issue by Tt421** [emscripten-core/emscripten#20719]
can i convert llvm bitecode(.bc file or .ll filei) to js, wasm ?
just like convert hello_world.c to a.out.js and a.out.wasm.(use command : "./emcc test/hello_world.c")
if can, how can i do that?

**Comment by sbc100** [comment]
Yes, emcc (just like clang) can take `.bc` and `.ll` files as input.   e.g.:

```
$ ./emcc -c -emit-llvm test/hello_world.c
$ ./emcc hello_world.bc -o a.out.ja
```

Remember that those need to have been built using the correct llvm target (you can't use `.bc` or `.ll` files built for x86, for example).
