### ISSUE TITLE
how to parse crash stack function symbols cross MAIN Module and SIDE Module

### ISSUE THREAD

**Issue by oatgnauh** [emscripten-core/emscripten#20730]
### Discussed in https://github.com/emscripten-core/emscripten/discussions/20729

<div type='discussions-op-text'>

<sup>Originally posted by **oatgnauh** November 16, 2023</sup>
if i have only one wasm, i can generate a symbol file which contain function index & function name, that's good.

now I use wasm dynamic link, there are two wasm, and two symbol files.
Assume I got a crash stack like this:
![img_v3_0257_9f41e089-0499-429d-8246-7830f395cfag](https://github.com/emscripten-core/emscripten/assets/17978322/39f0ee07-c4c9-4be1-bf39-7387d59eba15)
which is log inside SIDE module, how can i figure out which mudule such function index belong to ?
Both main and side module's function index starts from 0 in their symbols file
</div>

**Comment by kripken** [comment]
There is no need for both a discussion and an issue. The discussion was opened first so let's close this and focus talk on there.
