### ISSUE TITLE
Crash on Struct  Memory Alignment 

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#20749]
emcc version 3.1.29
Windows 11.

**Compiler flags:** `-Wsign-compare -Wno-import -Wformat=2 -Wmain -Wmissing-braces -w -Wformat-nonliteral -Wformat-nonliteral  -fpermissive -pthread  -gsplit-dwarf -gdwarf-5 -gpubnames `

**Linking Flags:** `-s ALLOW_TABLE_GROWTH -s WASM_BIGINT  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,addFunction  -s EXPORTED_FUNCTIONS=_main  -gsplit-dwarf -gdwarf-5 -gpubnames --bind -g -s USE_PTHREADS -s ALLOW_MEMORY_GROWTH=1    -s ASSERTIONS  -s FETCH   -s NO_DISABLE_EXCEPTION_CATCHING -s TEXTDECODER=0  -lidbfs.js -s PTHREAD_POOL_SIZE=20 -s ERROR_ON_WASM_CHANGES_AFTER_LINK -s REVERSE_DEPS=all -s STACK_SIZE=5mb -s DEFAULT_PTHREAD_STACK_SIZE=5mb -s ALLOW_BLOCKING_ON_MAIN_THREAD=1  -s PTHREAD_POOL_SIZE_STRICT=2 -s MAXIMUM_MEMORY=4gb -s INITIAL_MEMORY=200mb -s MAXIMUM_MEMORY=700mb `

I have the following  struct declaration :
```
struct MyDeviceState
{
  DWORD Dirty;
  float mWorld[16];
  float mView[16];
  float mProjection[16];
  void* pTexture0;
  void* pTexture1;
  BOOL  bUseMaterial;
  float vMaterialDiffuse[4];
  float vMaterialAmbient[4];
  float vMaterialEmissive[4];
  float fAlhpaRef;
  BOOL  bUseLight;
  D3DLIGHT9 Light;
  BOOL  bUseFog;
  DWORD lFogColor;
  float fFogStart;
  float fFogEnd;
  DWORD lFVF;
  DWORD TintColor;
  float vTintColor[4];
  BOOL  bUseTint;
} 
```
If I add a one DWORD (unsigned int) to the end of the struct, I get an arbitrary crash without any indication to this Struct.
If I add two DWORD the crash is not happen !
My assuming is it related to Memory Alignment which is 4 bytes instead of 8 bytes (tested by `alignof`).
I didn't found a way to force Memory Alignment 8 Bytes on all Structs and I not sure  about this solution.

**Comment by sbc100** [comment]
Do you know what causes the crash?  Crashes like that should not generally happen if you are using the struct in invalid ways, the alignment should mostly be an implementation detail.  You code should crash based on the alignment of the struct.  

What makes you think the alignment of this struct should 8?  i.e. why would making that align to 8 fix your crash?

A struct is normally aligned to max alignment of any of its members, and it looks like that biggest-aligned members are the pointers, and pointers 4 bytes on wasm32 and aligned to 4 bytes.   Do you have code perhaps that is assuming pointers are 8 bytes somewhere?

**Comment by aharondavid** [comment]
I found a memory overflow by LLVM ASan around that struct,  fixing that solve the crash.
Padding the struct is defiantly not the right solution.

Thanks.
