### ISSUE TITLE
unable to work with embind

### ISSUE THREAD

**Issue by pvssvikas** [emscripten-core/emscripten#2074]
Hi,

can any one please help me to get cpp functions to get used at javascript.

Facing below warnings at compilation,

warning: unresolved symbol: _embind_register_class_function
warning: unresolved symbol: _embind_register_class_constructor
warning: unresolved symbol: _embind_register_class
warning: Casting a function pointer type to a potentially incompatible one (use -s VERBOSE=1 to see more)

Got the below error when tried to use it with nodejs
node bindtest.js
missing function: _embind_register_class
-1
-1

CPP Code, 
# include <student.h>
# include "emscripten/bind.h"

  Student::Student() {
  }
 void Student::setName(std::string name_) {
     name = name_;
  }
  const std::string& Student::getName() {
    return name;
  }

  EMSCRIPTEN_BINDINGS(Student_example) {
    class_<Student>("Student").constructor()
      .function("setName", &Student::setName)
      .function("getName", &Student::getName);

   }

Thanks,
-Vikas.

**Comment by franckyinuk** [comment]
Hi, 

I know that this is an old thread, but I have tried the student example above.
And like @chadaustin it works nicely on the command line.

But if I put everything in a js file (example.js) 
````var student = require('./student.js');
var a = new student.Student();
a.setName("hi");
a.getName();
````

And run it with 

> node  example.js

I get
````
/mnt/d/SVN/Xenon/Learn-WebAssembly/chapter-09-node/student/student.js:120
      throw ex;
      ^

TypeError: student.Student is not a constructor
    at Object.<anonymous> (/mnt/d/SVN/Xenon/Learn-WebAssembly/chapter-09-node/student/example.js:2:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
````

Is that expected?

**Comment by brion** [comment]
Did you mean `Module.Student` instead of `student.Student`? And did you allow for the module to initialize before calling the constructor?
