### ISSUE TITLE
wasmfs bug

### ISSUE THREAD

**Issue by n0trace** [emscripten-core/emscripten#20741]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
``` 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.48 (e967e20b4727956a30592165a3c1cde5c67fa0a8)
clang version 18.0.0 (https://github.com/llvm/llvm-project a54545ba6514802178cf7cf1c1dd9f7efbf3cde7)
Target: wasm32-unknown-emscripten
Thread model: posix 
```

**Failing command line in full:**
emcc main.cpp -o hello.html -s WASM=1 -s FORCE_FILESYSTEM=1   -s ENVIRONMENT='web' -g3 -O1 -s ALLOW_MEMORY_GROWTH=1 -s RESERVED_FUNCTION_POINTERS=1 -s MAXIMUM_MEMORY=4294967296 -sASSERTIONS  -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -sWASMFS 

**Full link command and output with `-v` appended:**
Even for runtime issues it helps a lot if you can include the full link command.
Adding `-v` to the link command will show all of the sub-commands run which
can help us diagnose your issue.

Note:  Where possible, please avoid attaching screen shots of code or console
logs.  Instead, please include them as text so that they may be copied /
searched.  To make code blocks more readable and syntax highlighted, please
escape them with three backticks before and after, like this:

```cpp
#ifndef EM_PORT_API
#if defined(__EMSCRIPTEN__)
#include <emscripten.h>
#if defined(__cplusplus)
#define EM_PORT_API(rettype) extern "C" rettype EMSCRIPTEN_KEEPALIVE
#else
#define EM_PORT_API(rettype) rettype EMSCRIPTEN_KEEPALIVE
#endif
#else
#if defined(__cplusplus)
#define EM_PORT_API(rettype) extern "C" rettype
#else
#define EM_PORT_API(rettype) rettype
#endif
#endif
#endif

#include <iostream>
#include <fstream>
#include <emscripten.h>
using namespace std;


void createFile(const char* filename,long long fileSize) {
    FILE *file;
    char data = 0;

    file = fopen(filename, "wb"); 

    if (file == NULL) {
        printf("Error creating file!\n");
        return;
    }

    // Seek to fileSize - 1 position
    fseek(file, fileSize - 1, SEEK_SET);
    // Write at the end to extend the file size
    fwrite(&data, sizeof(char), 1, file);

    fclose(file);
    printf("File created successfully.\n");
}


void mergeFiles(const char *file1_path, const char *file2_path, const char *merged_file_path) {
    FILE *file1, *file2, *mergedFile;
    char c;

    file1 = fopen(file1_path, "r");
    file2 = fopen(file2_path, "r");
    mergedFile = fopen(merged_file_path, "w");

    while ((c = fgetc(file1)) != EOF) {
        fputc(c, mergedFile);
    }

    rewind(file2);

    while ((c = fgetc(file2)) != EOF) {
        fputc(c, mergedFile);
    }

    fclose(file1);
    fclose(file2);
    fclose(mergedFile);
	printf("merge successfully.\n");
}

int main() {
    const char* filename = "file.txt";
    createFile(filename,1LL * 1024 * 1024 * 1024 );

	const char* filename1= "file1.txt";
    createFile(filename1,1LL * 1024 * 1024 * 1024);

	const char* filename2= "file2.txt";
	mergeFiles(filename,filename1,filename2);
    return 0;
}

```

<img width="701" alt="image" src="https://github.com/emscripten-core/emscripten/assets/18096911/233a302b-19e3-4b4f-b00d-1a0886fd2918">

But when I create a larger file, it doesn't throw an error.
```cpp
int main() {
    const char* filename = "file.txt";
    createFile(filename,3LL * 1024 * 1024 * 1024 );

	const char* filename1= "file1.txt";
    createFile(filename1,3LL * 1024 * 1024 * 1024);

	const char* filename2= "file2.txt";
	mergeFiles(filename,filename1,filename2);
    return 0;
}
```

**Comment by kripken** [comment]
Looks like an overflow in MemoryFile. MemoryFile is backed by `std::vector`, so the size of buffers is limited to `size_t` (32 bits) but files in general can be of size `off_t` (64 bits).

Fix for that is in #20765, see some notes there on the weird situation this ends up hitting with buffering. To add to that, this testcase stopped erroring when the overflow started - at that time, the overflow caused the file to be of size 1. With the PR, we error on the overflow, but it only happens when musl flushes out the write, which is much later than the `fwrite`, so the user does not seem to be able to detect this.
