### ISSUE TITLE
RuntimeError: unreachable with Asyncify (proc_exit returns)

### ISSUE THREAD

**Issue by attilaolah** [emscripten-core/emscripten#20769]
I'm trying to figure out why I'm getting a `RuntimeError: unreachable` when compiling BusyBox with `-sASYNCIFY`. (Without Asyncify, it works, but I need Asyncify for intercepting the read() syscall in an asynchronous way).

There are two scenarios, both of which result in an error.

1. I wrap `read()` with an async function that returns a Promise, **which then resolves immediately**. In this case, my program exists with the above exception.
2. I wrap `read()` with an async function that blocks, i.e. the returned Promise is not immediately resolved. Then, the program exits and calls the "quit" callback (but not Module.onExit), with exit status 0. When I resolve the promise, it correctly unwinds the stack, and it can repeat the `read()` as many times as necessary. When I return EOF (-1) from `read()`, BusyBox (running the `hush` shell) terminates with `_exit()`. That termination eventually causes the same "unreachable" error.

The error seems to come from this function:

```wat
  (func $func94 (param $var0 i32)
    (local $var1 i32)
    global.get $global7
    local.set $var1
    local.get $var0
    call $wasi_snapshot_preview1.proc_exit
    global.get $global7
    local.get $var1
    i32.ne
    if
      unreachable
    end
    unreachable
  )
```

It reaches the very last `unreachable`. Decompiling the wat with `wasm2c` I get this:

```c
void w2c__f94(w2c_* instance, u32 var_p0) {
  u32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = instance->w2c_g7;
  var_l1 = var_i0;
  var_i0 = var_p0;
  w2c_wasi__snapshot__preview1_proc_exit(instance->w2c_wasi__snapshot__preview1_instance, var_i0);
  var_i0 = instance->w2c_g7;
  var_i1 = var_l1;
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    UNREACHABLE;
  }
  UNREACHABLE;
  FUNC_EPILOGUE;
}
```
Clearly the only way to avoid the unreachable traps above is if the `w2c_wasi__snapshot__preview1_proc_exit()` never returns — but it does for some reason, an I don't know why.

I'll try to turn up the verbosity and dig out the exact link commands if that helps.

---

Please include the following in your bug report:

**Version of emscripten/emsdk:**
4.1.49 from git, via @emdsk + bazel 

**Failing command line in full:**
This is a runtime error.

**Full link command and output with `-v` appended:**
This is my full make command, which contains the flags:

```
make: /home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/bazel-out/k8-opt-exec-BC9EC77D/bin/external/rules_foreign_cc~0.10.1/toolchains/make/bin/make install HOSTCC=cc HOSTCXX=c++ AR=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/external/emscripten_bin_linux/emscripten/emar AS=false CC=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/external/emscripten_bin_linux/emscripten/emcc NM=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/external/emscripten_bin_linux/emscripten/emnm OBJCOPY=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/external/emscripten_bin_linux/emscripten/../bin/llvm-objcopy OBJDUMP=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/external/emscripten_bin_linux/emscripten/../bin/llvm-objdump SKIP_STRIP=y CFLAGS_busybox=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/external/emscripten_bin_linux/emscripten/system/lib/libc/musl/src/signal/sigisemptyset.c --pre-js=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/src/wrap/pre.js --post-js=/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/src/wrap/post.js -sASYNCIFY=1 -sASYNCIFY_STACK_SIZE=1048576 -sENVIRONMENT=web -sEXPORT_ES6 -sMODULARIZE -sWASM_BIGINT -fno-exceptions -L/home/atl/.cache/bazel/_bazel_atl/ec6a2ca185f9d28467187500817dd540/sandbox/linux-sandbox/146/execroot/_main/bazel-out/k8-fastbuild/bin/src/wrap -lwrap -Wl,--wrap=read -sASSERTIONS -sASYNCIFY_DEBUG=1
```

**Comment by attilaolah** [comment]
For completeness, this is how my `wrap.c` looks like:

```c
#include <unistd.h>

#include <emscripten.h>

EM_ASYNC_JS(ssize_t, js_read, (int fd, void *buf, size_t count), {
  return await OS.read(fd, buf, count);
});

ssize_t __wrap_read(int fd, void *buf, size_t count) {
  return js_read(fd, buf, count);
}
```

The `OS.read` function is then populated in `--pre-js`:

```js
const OS = Module.os;
```

And `Module.os` comes from `moduleArg.os`, which is passed in by the calling function (which is a `wasm-bindgen` binary).

**Comment by attilaolah** [comment]
Eventually I found a "workaround" of sorts: I can also wrap `_exit`, and then throw an exception that I catch in the calling module. It unwinds the stack and gets the control flow back to the original caller, which is several hundreds of stack frames above.

I'm not sure if this terminates all the process and allows garbage collection to clean up everything, or maybe I'm intercepting some cleanup this way, it certainly doesn't seem like the best way to exit, but at least it doesn't throw an ancaught exception.

**Comment by sbc100** [comment]
Do you know where the call to exit is coming from?   My guess is that ASYNCIFY causes the wasm stack to be unwound and  that the `callMain` function doesn't know how to handle the suspended state of the `main` function.  

See `callMain` in `preamble.js`.  I see handling there for `ASYNCIFY=2` but not for `ASYNCIFY=1`.

**Comment by sbc100** [comment]
My understanding is that the problem here is that `exit` should not be a called just because `main` suspends, so the solution is to figure out how to avoid calling `exit` at all in this case.

**Comment by attilaolah** [comment]
I don't fully understand how stack unwinding/rewinding works, my assumption was that when I suspend the program for Asyncify, it would actually more-or-less terminate, and then the next time I run it, it would basically re-enter main, and somehow short-path right to where the suspend happened. The stack should already be set up, and the heap was never modified.

I'm not exactly sure whether `exit` is called if I suspend, I just know that `Module.quit` gets called with an exit status of 0 (or maybe undefined, and I end up coercing it to a zero, I'm not sure).

I also tried using ASINCIFY=2 and flipping the relevant browser flags, if I could get that to work then I wouldn't worry about ASYSNCIFY=1 since I assume in some not-so-distant future we'll all be using ASYNCIFY=2. But when I tried that, I got some runtime errors, presumably due to exceptions somehow sneaking in? And when I tried `-fno-exceptions` or `-fwasm-exceptions`, then the compile broke.

In any case, I'll try to figure out why the quit is called on suspend. Thanks for the pointers here!

**Comment by sbc100** [comment]
This is the code that gets called after `main` returns: https://github.com/emscripten-core/emscripten/blob/1c7c271c5bf64d74297202c180224c14e51a3a4e/src/postamble.js#L107-L119

As far as I can tell this gets run even when main returns due to being suspended.

**Comment by attilaolah** [comment]
That would explain the exitJS. But I'm not sure what would be the right course of action if ASINCIFY == 1?

I tried a few different scenarios now:

- ASYNCIFY=1, don't wrap `_exit`, but resolve `read()` promise immediately with EOF, causing `hush` to quit. This is perhaps a degenerate case that results in `proc_exit` being called twice in a row, then `unreachable`. I can easily avoid this case by simply `setTimeout(…, 0)` the resolve.
- `ASYNCIFY=1, don't wrap `_exit`, delay resolving the promise on `read()`. There is a call to `proc_exit` when the binary suspends, but otherwise things work normally. I can talk to `hush` via `read()`. When I finally send the `EOF` marker, it tries to quit again, runs `proc_quit` again and returns `unreachable`.
- `ASYNCIFY=1`, wrap `_exit`, tried either resolving immediately or delaying the promise. In either case, it seems like `proc_exit` is never called since the binary never tries to exit. This works fine, but eventually I want the binary to be able to quit. If I can do that externally (from the wrapped `_exit`, having access to the Module object in JS), that could work. I could call `exitJS()` myself if necessary.

Alternatively, I could try to modify the snippet from your previous comment, and do something special if `ASYNCIFY == 1`, trying to avoid calling `exitJS()` maybe. Again, I'm not sure what is the correct thing to do here.

**Comment by sbc100** [comment]
Yes, calling `exitJS` when main suspends seems wrong to me.  I had thought that `ASYNCIFY=1` worked when main suspended, but if `exitJS` is being called that can't be true.   @kripken do you know if this is supposed to already work somehow?

**Comment by kripken** [comment]
Suspending during main is definitely tested. I took a quick look in the code. Indeed `exitJS` is called after we unwind, as we start to sleep. Then `exitJS` throws an ExitStatus for the exit, which is swallowed by `handleException` (the comment there says it does so since exiting from main is internal control flow; we handle it by swallowing it and setting the proper exit code). Later, we call back into the wasm when we resume execution.

**Comment by kripken** [comment]
(It might be less confusing to not call `exitJS` during a sleep, but it does seem to work atm; it sets the exit code global, which seems weird - since we did not exit - but that is not read.)

**Comment by attilaolah** [comment]
```js
if (Module['quit']) quit_ = Module['quit'];
```
It seems like I was preventing `ExitStatus` from being thrown when I set "quit". I thought "quit" was a way to hook into getting notified of program exit, but apparently that's not a good idea. All it does is throw the exception.

(So I guess I could still hook into that, as long as I throw the exception.)

**Comment by attilaolah** [comment]
OK so not setting `quit` actually resolves _almost_ all my issues. The one thing remaining is the final `ExitStatus`, when the program exits. That one is not swallowed by Asyncify.

It doesn't hurt much, but now I wonder if I should be catching that somewhere higher up.

**Comment by attilaolah** [comment]
I guess this issue can be closed now that it turned out that overwritin `Module.quit` and not throwing the exception was what caused the problem. But it was really surprising. I have no idea there was a hidden exception that I silently… silenced.

**Comment by sbc100** [comment]
Calling exitJS calls exitRuntime, which certainly seems wong under those circumstances!  

We should probably fix it so that exitJS is not called when unwinding.   And also we should check that we do call exitJS (and exitRuntime) are eventually called in when main really returns.
