### ISSUE TITLE
wasm build with: EXPORT_NAME not used in shell, 

### ISSUE THREAD

**Issue by simonbuehler** [emscripten-core/emscripten#20801]
hi,

when building opencv.js with  `MODULARIZE=1 -s EXPORT_NAME="'cv'"` around the line

https://github.com/emscripten-core/emscripten/blob/58cf85c5b17918c4c3d7ad4f9e0800d68dca2591/src/shell.js#L41

the final code is this:

```js
  var cv = (() => {
    var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
    if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
    return (
      function (moduleArg = {}) {

        var Module = moduleArg;
        var cv = Module; <-- this is missing to make the code in e.g. Module[imread] work (which uses cv.somemethod)

        var readyPromiseResolve, readyPromiseReject; Module["ready"] = new....

```
so the `Module` is set but should be named `EXPORT_NAME` ( cv in this case) ?

i always have to add the `var cv = Module` line in the generated code, how can this be fixed?

**Comment by sbc100** [comment]
IIUC, within the generated code the name `Module` is still valid and used.  The "outside" name is the one set by `EXPORT_NAME` and that is set via `var cv = ` at the top.

Where is `Module[imread]` defined?

**Comment by simonbuehler** [comment]
https://github.com/opencv/opencv/blob/5df28f1eaa4e7433cfb2d51898384bbb30da8468/modules/js/src/helpers.js#L69

This is added via --post-js and uses cv.matFromImageData

**Comment by sbc100** [comment]
Do you know why they use `cv.matFromImageData` there?  I think that should really be Module.matFromImageData since this is internal-to-the-module code.

**Comment by simonbuehler** [comment]
i guess the difference of internal/external context was unclear (for me it was new) so that might be the cause - thanks for your explanation and I just replaced all `cv.` with `Module.`  and it does indeed work!

So closing here - thanks a lot for your input, do you think #20800  has the same cause?

**Comment by sbc100** [comment]
BTW, did this used to work in the part with `MODULARIZE` or was it always broken in this way?

**Comment by sbc100** [comment]
#20800 looks a little different.  I can't see why that doesn't work.   `var cv = ..` should be defined in the file that is imported on each worker so I don't see why `cv` would not be defined at that point.  I'm also fairly sure we have have tests for `MODULARIZE` + pthreads, but I would need to check.

**Comment by sbc100** [comment]
Also, regarding this issue, do you know what the `cv` variable is not defined at the point in the code?  The global `var cv =` should be defined by the time the module is loaded.. are you calling `imread` during load perhaps?

**Comment by simonbuehler** [comment]
> BTW, did this used to work in the part with `MODULARIZE` or was it always broken in this way?

i didn't test that yet but will try tomorrow

> Also, regarding this issue, do you know what the `cv` variable is not defined at the point in the code? The global `var cv =` should be defined by the time the module is loaded.. are you calling `imread` during load perhaps?

i tried different ways - just reference the opencv.js (wasm) in a html page with a async script tag, there i always get a promise back and use this code:
```js

 <script type="text/javascript">
        function onOpenCvReady() {
            console.log("meep");
            if (typeof cv.then === "function") { // only this gets triggered
                cv.then((loadedCv) => {
                    cv = loadedCv;
                    console.log(cv.getBuildInformation());
                    initialise();
                });
            } else if (cv.getBuildInformation) { //never reached this
                console.log(cv.getBuildInformation());
                initialise();
            } else {
                // WASM - this also never gets called
                cv["onRuntimeInitialized"] = () => {
                    console.log(cv.getBuildInformation());
                    initialise();
                };
            }
        }
```
imread is always called after initialise() so i have no idea whats wrong there

**Comment by simonbuehler** [comment]
> #20800 looks a little different. I can't see why that doesn't work. `var cv = ..` should be defined in the file that is imported on each worker so I don't see why `cv` would not be defined at that point. I'm also fairly sure we have have tests for `MODULARIZE` + pthreads, but I would need to check.

console.log(cv) gives` [object Promise]`, so cv(Module) fails
