### ISSUE TITLE
Incorrect TouchEvent mouse mapping for GLFW

### ISSUE THREAD

**Issue by br0nk** [emscripten-core/emscripten#20804]
Current behavior for GLFW TouchEvent handling:
- Each touchstart TouchEvent causes 2 mousedown events.
- Each touchend TouchEvent causes 2 mouseup events.
- touchmove events are ignored completely.

Expected behavior:

Until GLFW adds more fine-grained multitouch support, for a single primary touch:
- touchstart is mapped to  a single mousedown event.
- touchend is mapped to a single mouseup event.
- touchmove is mapped to a single mousemove event.

The reason mousedown/mouseup events are duplicated is that the GLFW callbacks for mouse events are added for touchstart/touchend, but the default browser behavior of emulating a mousedown/mouseup event for these touch events is **not** suppressed with a call to preventDefault in the event handler, resulting in a duplicate call to the mousedown/mouseup event handlers and the associated GLFW callebacks (note: touchmove does not trigger an emulated mouse event by default in the browser).

**Comment by morew4rd** [comment]
Sorry for bringing this back. But I'm having issues on ios safari and android firefox: touch event does not seem to update mouse location. A slight movement is needed.

Is this related to the op, or a different issue?

Android chrome/edge does not have this problem.

**Comment by morew4rd** [comment]
FYI: I worked around by using GetCursorPos API instead of relying on events.
