### ISSUE TITLE
bogus warning 'Output contains some very large functions'

### ISSUE THREAD

**Issue by manxorist** [emscripten-core/emscripten#20811]
Receiving the warning `warning: Output contains some very large functions (5116 lines in vY), consider building source files with -Os or -Oz)` is rather pointless when I am already compiling with `-Oz`. If emscripten thinks functions are too big (for whatever reason), it is its job to make them smaller instead of complaining to the user without providing any way to suppress the warning.
Big functions are fine - they do exist. Emscripten should frankly just shut up in this case.

**Comment by manxorist** [comment]
This may be a result of using `-g1` (see #20810), but the warning with default `-g0` looks so scary that I am not willing to risk using it.

Still, the combination of these 2 issues makes it impossible to build libopenmpt without any warning with emscripten, and there is absolutely nothing in libopenmpt that I can do to avoid it. Emscripten currently fails our CI, and I am considering blacklisting compiling with 3.1.50.

**Comment by manxorist** [comment]
Building with `-g2` revealed that emscripten is complaining about <https://github.com/OpenMPT/openmpt/blob/c79066216ca280341a09fccec1f7642a1edb8298/soundlib/Load_it.cpp#L411-L1359> and <https://github.com/OpenMPT/openmpt/blob/c79066216ca280341a09fccec1f7642a1edb8298/src/mpt/io/tests/tests_io.hpp#L36-L562>. While these functions are large, there is really nothing wrong with them at all, and it is very much not a compilers job to have opinions about the size of functions and complain with a `***WARNING***` to the user about it.

**Comment by sbc100** [comment]
Quick question: Are you seeing this warning when building with `-sWASM=0`  (i.e. wasm2js)? 

@kripken do you know of any reason why such large JS function might be problem for wasm2js users these days?

**Comment by manxorist** [comment]
> Quick question: Are you seeing this warning when building with `-sWASM=0` (i.e. wasm2js)?

I get this warning with `-s WASM=2` and with `-s WASM=0`, but not with `-s WASM=1`.

> @kripken do you know of any reason why such large JS function might be problem for wasm2js users these days?

Even if this causes some kind of obscure performance problem for some JS engine, a warning that the user cannot do anything about must not exist.

**Comment by sbc100** [comment]
> Even if this causes some kind of obscure performance problem for some JS engine, a warning that the user cannot do anything about must not exist.

Fair enough, I'm just trying to gather all the background information on this warning.

**Comment by kripken** [comment]
I think historically this was a major performance problem, but likely not today, and also far less important given wasm, anyhow. I agree this can be removed.
