### ISSUE TITLE
"undefined symbol: main" error on a super simple C code

### ISSUE THREAD

**Issue by vault-thirteen** [emscripten-core/emscripten#20827]
**Source files:**
`sum.c`

```c
int sum(int a, int b) {
    return a+b;
}
```

**Version of emscripten/emsdk:**
`emcc -v`

> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.50 (047b82506d6b471873300a5e4d1e690420b582d0)
> clang version 18.0.0 (https://github.com/llvm/llvm-project 14028ec0a62210d68a4dd7a046ac79c8c3b7727e)
> Target: wasm32-unknown-emscripten
> Thread model: posix
> InstalledDir: D:\Temp\1\emsdk\upstream\bin

**Failing command line in full:**
`emcc sum.c -o sum.wasm`

> wasm-ld: error: D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libstandalonewasm-nocatch.a(__main_void.o): undefined symbol: main
emcc: error: 'D:/Temp/1/emsdk/upstream/bin\wasm-ld.exe -o sum.wasm C:\Users\xxx\AppData\Local\Temp\emscripten_temp__4id5kza\sum_0.o -LD:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\crt1.o -lGL -lal -lhtml5 -lstandalonewasm-nocatch -lstubs-debug -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\xxx\AppData\Local\Temp\tmpa3637_8alibemscripten_js_symbols.so --strip-debug --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --stack-first --table-base=1' failed (returned 1)

**Full link command and output with `-v` appended:**
`emcc sum.c -o sum.wasm -v`

> "D:/Temp/1/emsdk/upstream/bin\clang.exe" -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --sysroot=D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot -DEMSCRIPTEN -Werror=implicit-function-declaration -Xclang -iwithsysroot/include\fakesdl -Xclang -iwithsysroot/include\compat -v sum.c -c -o C:\Users\xxx\AppData\Local\Temp\emscripten_temp_v55c46pk\sum_0.o
clang version 18.0.0 (https://github.com/llvm/llvm-project 14028ec0a62210d68a4dd7a046ac79c8c3b7727e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: D:\Temp\1\emsdk\upstream\bin
 (in-process)
 "D:\\Temp\\1\\emsdk\\upstream\\bin\\clang.exe" -cc1 -triple wasm32-unknown-emscripten -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name sum.c -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -debugger-tuning=gdb "-fdebug-compilation-dir=D:\\Temp\\2" -v "-fcoverage-compilation-dir=D:\\Temp\\2" -resource-dir "D:\\Temp\\1\\emsdk\\upstream\\lib\\clang\\18" -D EMSCRIPTEN -isysroot "D:\\Temp\\1\\emsdk\\upstream\\emscripten\\cache\\sysroot" -internal-isystem "D:\\Temp\\1\\emsdk\\upstream\\lib\\clang\\18\\include" -internal-isystem "D:\\Temp\\1\\emsdk\\upstream\\emscripten\\cache\\sysroot/include/wasm32-emscripten" -internal-isystem "D:\\Temp\\1\\emsdk\\upstream\\emscripten\\cache\\sysroot/include" -Werror=implicit-function-declaration -ferror-limit 19 -fmessage-length=154 -fvisibility=default -fgnuc-version=4.2.1 -fignore-exceptions -fcolor-diagnostics "-iwithsysroot/include\\fakesdl" "-iwithsysroot/include\\compat" -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -o "C:\\Users\\xxx\\AppData\\Local\\Temp\\emscripten_temp_v55c46pk\\sum_0.o" -x c sum.c
clang -cc1 version 18.0.0 based upon LLVM 18.0.0git default target x86_64-pc-windows-msvc
ignoring nonexistent directory "D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot/include/wasm32-emscripten"
#include "..." search starts here:
#include <...> search starts here:
 D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot/include\fakesdl
 D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot/include\compat
 D:\Temp\1\emsdk\upstream\lib\clang\18\include
 D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot/include
End of search list.
 "D:/Temp/1/emsdk/upstream/bin\clang.exe" --version
 "D:/Temp/1/emsdk/upstream/bin\wasm-ld.exe" -o sum.wasm C:\Users\xxx\AppData\Local\Temp\emscripten_temp_v55c46pk\sum_0.o -LD:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\crt1.o -lGL -lal -lhtml5 -lstandalonewasm-nocatch -lstubs-debug -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\xxx\AppData\Local\Temp\tmpdy5ddu0plibemscripten_js_symbols.so --strip-debug --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --stack-first --table-base=1
wasm-ld: error: D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libstandalonewasm-nocatch.a(__main_void.o): undefined symbol: main
emcc: error: 'D:/Temp/1/emsdk/upstream/bin\wasm-ld.exe -o sum.wasm C:\Users\xxx\AppData\Local\Temp\emscripten_temp_v55c46pk\sum_0.o -LD:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten D:\Temp\1\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\crt1.o -lGL -lal -lhtml5 -lstandalonewasm-nocatch -lstubs-debug -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\xxx\AppData\Local\Temp\tmpdy5ddu0plibemscripten_js_symbols.so --strip-debug --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --stack-first --table-base=1' failed (returned 1)

**Comment by sbc100** [comment]
If you want to build a standalone wasm module without a main function you need to pass `--no-entry`.    See https://emscripten.org/docs/compiling/Building-Projects.html#emscripten-linker-output-files

**Comment by sbc100** [comment]
BTW, if you build with `-o out.js` the default is it simply ignore the missing main, so you would only see this error in `-sSTRICT` mode.

**Comment by vault-thirteen** [comment]
@sbc100 , thank you.

Is it possible to automate this so that the tool searches for the `main` function automatically and uses the flag `--no-entry` when no `main` function is found ? I mean, when I set output to a single WASM file without JS, like so `-o xxx.wasm`.
