### ISSUE TITLE
Browser tests often fail with "[no http server activity]"

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#20820]
I believe what is happening here is the browser dies or becomes unresponsive, causing all future tests to fail in the same way.

I don't believe our current retry mechanism helps in this case because it doesn't do anything to restart the browser.

I think we need some way to kill and restart the browser in this case.

See #20584 and #20531

**Comment by kripken** [comment]
If the entire browser crashes or is unresponsive then restarting it is the right thing, yeah. And that could be the reason. Another possibility is that only the browser *tab* crashes ("Aw, snap"), in which case opening another browser tab (without restarting the browser) might be enough. But I don't have any idea either way, and a full restart seems simpler, so sgtm.

**Comment by sbc100** [comment]
As long as we are using our current test harness mode, I don't think we have a way to kill just one tab.
