### ISSUE TITLE
how can i known what EXPORTED_FUNCTIONS should be?

### ISSUE THREAD

**Issue by g1204** [emscripten-core/emscripten#20857]
when call a function in side module, it shows an error about a type error : 'NSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEEE', I can resolve it by adding '_ZTINSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEEE' to EXPORTED_FUNCTIONS when building main module. (_ZTI prefix means typeinfo for).

Question is how can i known excactly what EXPORTED_FUNCTIONS should be, without meeting an runtime error first?

I have tried this way:(but did not work)
emsdk/upstream/bin/wasm-dis side_module.wasm
it has a line: 
(import "GOT.mem" "_ZTINSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEEE" (global $typeinfo\20for\20std::__2::basic_string<wchar_t\2c\20std::__2::char_traits<wchar_t>\2c\20std::__2::allocator<wchar_t>> (mut i32)))

but it also has a line:
(export "_ZTINSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEEE" (global $global$686))

(I thought import means dependency, but export means ?)

**Comment by sbc100** [comment]
There are two ways to make sure you main module exports everything needed for your side mode:

1. Export everything by building with `-sMAIN_MODULE=1` (results in a large main module)
2. Build with `-sMAIN_MODULE=1` and also pass the side module when linking (this allows emcc to know what it needs to export).  You might wan to combine this with `-sAUTOLOAD_DYLIBS=0` if you don't want to load them at startup.

**Comment by g1204** [comment]
@sbc100 can I change the 2 way to -sMAIN_MODULE=2 ? (As it's still very large)

**Comment by sbc100** [comment]
Sorry, option 2 should have been -sMAIN_MODULE=2 (I will update above)

**Comment by g1204** [comment]
@sbc100 Thanks. It works!

Here I met another problem:
when build side module, how can i known what EXPORTED_FUNCTIONS should be?
in this testcase I pass libside2.wasm to build libside1.wasm, but it doesn't work. (error: undefined symbol: side1)
`def test_foo(self):
    create_file('side1.c', r'''
      void side1() {}
    ''')
    create_file('side2.c', r'''
      #include <emscripten.h>
      void side1();
      EMSCRIPTEN_KEEPALIVE void side2() {
        side1();
      }
    ''')
    self.run_process([EMCC, 'side2.c', '-sSIDE_MODULE=2', '-o', 'libside2.wasm'])
    self.run_process([EMCC, 'side1.c', '-sSIDE_MODULE=2', '-o', 'libside1.wasm', 'libside2.wasm'])
    create_file('main.c', r'''
      void side2();
      int main() {
        side2();
      }
    ''')
    self.run_process([EMCC, '-sMAIN_MODULE=2', 'main.c', '-L.', '-sLLD_REPORT_UNDEFINED', 'libside1.wasm', 'libside2.wasm'])
`
run it from test_other.py

**Comment by sbc100** [comment]
You can use `-sSIDE_MODULE` (rather than `-sSIDE_MODULE=2`) when building the side modules.   This will export all the symbols in the side module that have `default` visibility.   Is that turns out th be much you can use the `visibility` attributes in the source code to control which symbols are externally visiible by marking some of the as `hidden`.  See https://gcc.gnu.org/wiki/Visibility

**Comment by g1204** [comment]
Thanks for the advice!
