### ISSUE TITLE
Issues detecting Meta/Command key on Mac in GLFW

### ISSUE THREAD

**Issue by bdenhollander** [emscripten-core/emscripten#20891]
I had to make the following changes to [library_glfw.js](https://github.com/emscripten-core/emscripten/blob/main/src/library_glfw.js) to improve detection of the Command Key on Mac:

**Adding `0xE0` to `DOMToGLFWKeyCode` for Mac Firefox.**
`keyCode` is marked as deprecated but GLFW relies on it. Variances between browsers are available on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#non-printable_keys_function_keys).

```JavaScript
case 0xE0:return 343; // DOM_VK_META -> GLFW_KEY_LEFT_SUPER
```

**Adding `win.keys[348]` to detect the right Meta key.**

```JavaScript
getModBits: function(win) {
      var mod = 0;
      if (win.keys[340]) mod |= 0x0001; // GLFW_MOD_SHIFT
      if (win.keys[341]) mod |= 0x0002; // GLFW_MOD_CONTROL
      if (win.keys[342]) mod |= 0x0004; // GLFW_MOD_ALT
      if (win.keys[343] || win.keys[348]) mod |= 0x0008; // GLFW_MOD_SUPER
      return mod;
}
```

**Version of emscripten/emsdk:**
Noticed in 3.1.2 and the code is the same on `main`. SDL may have similar issues since the GLFW port is based on it.

**Comment by sbc100** [comment]
Looks like that might be a simple fix.  Would you like to open a PR?   If not, I'll open it up to others.
