### ISSUE TITLE
emcc.bat prints out extra lines if emsdk is installed in path with spaces (HostOS: Windows)

### ISSUE THREAD

**Issue by aportale** [emscripten-core/emscripten#20913]
When executing `emcc.bat -dumpversion`, I would usually just get an output with a version number. If emsdk is installed in a path that contains spaces, I get more output than expected.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.50 (047b82506d6b471873300a5e4d1e690420b582d0)
clang version 18.0.0 (https://github.com/llvm/llvm-project 14028ec0a62210d68a4dd7a046ac79c8c3b7727e)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Users\alportal\path with spaces\emsdk\upstream\bin

**Failing command line in full:**
`emcc.bat -dumpversion`

If emsdk is installed within a path that contains spaces, the output contains extra lines:
```
c:\Users\alportal\path with spaces\emsdk>set MYDIR=C:\Users\alportal\path with spaces\emsdk\upstream\emscripten\

c:\Users\alportal\path with spaces\emsdk>goto FOUND_MYDIR
3.1.50
```

This extra output of the compiler can cause issues, like for example in the Qt Creator IDE: [QTCREATORBUG-29758](https://bugreports.qt.io/browse/QTCREATORBUG-29758) [QTCREATORBUG-29981](https://bugreports.qt.io/browse/QTCREATORBUG-29981)

**Comment by sbc100** [comment]
Man.. what a strange bug.  I found a fix but I have no idea why it works: #20916
