### ISSUE TITLE
ES6 with pthread cannot be built by vite

### ISSUE THREAD

**Issue by wangyuanhao11** [emscripten-core/emscripten#20934]
When using emscripten's es6 and pthreads, the dynamic import of import("./CbWebLib.js")).then(exports=>exports.default(Module)) in worker.js will cause the vite build to fall into an infinite loop.
![image](https://github.com/emscripten-core/emscripten/assets/40970845/231fd92e-b4ca-40fd-b93e-6e3c6ff2ec24)

**Comment by sbc100** [comment]
I think this is a duplicate of #20580
