### ISSUE TITLE
long double. The program output varies between Linux & Wasm version.

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#20947]
Hi, while working on DOSBox-X, I encountered a corner case in FPU emulation. For some reason, when I run DOSBox-X on a PC, I get one output, but when I run it in a browser, I get a different output. I delved into the FPU core in DOSBox-X and found that FPU math yields different results, but only when DOSBox-X is using long doubles. Then, I wrote a sample program:

```c
#include <stdio.h>

void printMemory(long double *d) {
    char *ptr = (char *) d;
    for (int i = 0; i < sizeof(long double); ++i) {
        printf("%02x ", *(ptr + i) & 0xFF); 
    }
    printf("\n");
}

int main() {
    long double d1 = 0.500004;
    long double d2 = 0.500004;
    long double d3 = d1 * d2;

    printf("sizeof(long double): %lu\n%Lf\n%Lf\n%Lf\n", sizeof(long double), d1, d2, d3);
    printMemory(&d1);
    printMemory(&d2);
    printMemory(&d3);

    return 0;
}
```

When you compile it natively with GCC/Clang (on Ubuntu), you will get this result:
```
sizeof(long double): 16
0.500004
0.500004
0.250004
00 d8 82 de 1b 43 00 80 fe 3f 00 01 01 01 00 00 
00 d8 82 de 1b 43 00 80 fe 3f 8b 17 00 00 00 00 
02 e3 34 e0 37 86 00 80 fd 3f 00 00 00 00 00 00
```

but with emcc result is:
```
sizeof(long double): 16
0.500004
0.500004
0.250004
00 00 00 00 00 00 00 b0 05 bd 37 86 00 00 fe 3f 
00 00 00 00 00 00 00 b0 05 bd 37 86 00 00 fe 3f 
00 59 00 06 43 b8 04 c6 69 c0 6f 0c 01 00 fd 3f 
```

While the answer remains the same, the memory footprint is different. I believe this is the reason why DOSBox-X is not functioning properly. Actually, I am not certain whether it's a bug or by design, but I expect the same output for both native and WASM builds.

The compile commands I used are:
```
clang ld.c -o ld && ./ld
gcc ld.c -o ld && ./ld
emcc ld.c -o ld.js && node ./ld.js
```

**Comment by kripken** [comment]
I believe long doubles on Intel will use fp80 in hardware, while in wasm they will use emulated fp128. So those results may differ, and the difference is allowed by the C spec - the spec only says they must be "at least as precise as 64-bit doubles" ([wikipedia](https://en.wikipedia.org/wiki/Long_double)).

**Comment by joncampbell123** [comment]
> I believe long doubles on Intel will use fp80 in hardware, while in wasm they will use emulated fp128. So those results may differ, and the difference is allowed by the C spec - the spec only says they must be "at least as precise as 64-bit doubles" ([wikipedia](https://en.wikipedia.org/wiki/Long_double)).

Right. DOSBox-X expects "long double" to mean the 80-bit Intel 8087 format, not the 128-bit floating point format.

**Comment by caiiiycuk** [comment]
@azakai  Does this also mean that using long double will not give any performance boost because they are emulated?

**Comment by sbc100** [comment]
Yes, using `long double` today comes with code size cost and runtime code due to the fp128 emulation code.
