### ISSUE TITLE
STANDALONE_WASM is not used if an output file other than x.wasm is not provided

### ISSUE THREAD

**Issue by ChinYikMing** [emscripten-core/emscripten#20959]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.46 (19607820c447a13fd8d0b7680c56148427d6e1b8)
clang version 18.0.0 (https://github.com/llvm/llvm-project 75501f53624de92aafce2f1da698b249a7293dc7)
```

Is it required to provide the wasm file extension, such as `x.wasm` (x can be any string), when using the `STANDALONE_WASM` flag during compilation in order to produce a single wasm file?

What I want to do is make sure that the created file is always a single WASM file, regardless of whether `-o` is present, if the `STANDALONE_WASM` flag is set.

Or any misunderstanding of `STANDALONE_WASM` flag ?

**Comment by sbc100** [comment]
`-sSTANDALONE_WASM` will force standalone mode regardless of the file extension.

**Comment by ChinYikMing** [comment]
> `-sSTANDALONE_WASM` will force standalone mode regardless of the file extension.

Thanks for replying!

But it will generate wasm and glue js in my case, see the figure below, is it abnormal?
![Screenshot from 2023-12-21 09-41-26](https://github.com/emscripten-core/emscripten/assets/58044437/8376242e-0abb-4788-9b62-61708c5ba8c9)

**Comment by sbc100** [comment]
Yes, the wasm file is built in standalone mode, but the JS file is built do that it can load that wasm file.

By default emscripten emits JS + wasm.   If you specify `-sSTAND_ALONE` that will cause it go generate a wasm file that is more "standalone" than it otherwise would be.

If you want to force emscripten to only emit the wasm file and not the JS file than you can either pass `--oformat=wasm` or pick and output name with the `.wasm` extension (e.g. `-o out.wasm`).

The `a.out*` names are the default names produced by the compiler, similar to how gcc and clang produce `a.out` by default.

**Comment by ChinYikMing** [comment]
> If you want to force emscripten to only emit the wasm file and not the JS file than you can either pass `--oformat=wasm` or pick and output name with the `.wasm` extension (e.g. `-o out.wasm`)

This work!

May I know what `-sSTANDALONE_WASM` does in this mode?

**Comment by sbc100** [comment]
> > If you want to force emscripten to only emit the wasm file and not the JS file than you can either pass `--oformat=wasm` or pick and output name with the `.wasm` extension (e.g. `-o out.wasm`)
> 
> This work!
> 
> May I know what `-sSTANDALONE_WASM` really does in this mode? I am a bit confuse with that.

It attempts to minimize the use of web-only imports, and maximize the use of imports more likely to work outside the web, such as WASI imports.

**Comment by sbc100** [comment]
> > > If you want to force emscripten to only emit the wasm file and not the JS file than you can either pass `--oformat=wasm` or pick and output name with the `.wasm` extension (e.g. `-o out.wasm`)
> > 
> > 
> > This work!
> > May I know what `-sSTANDALONE_WASM` really does in this mode? I am a bit confuse with that.
> 
> It attempts to minimize the use of web-only imports, and maximize the use of imports more likely to work outside the web, such as WASI imports.

Depending on what kind of APIs your program uses is more likely to run in standalone wasm runtimes

**Comment by ChinYikMing** [comment]
> > > If you want to force emscripten to only emit the wasm file and not the JS file than you can either pass `--oformat=wasm` or pick and output name with the `.wasm` extension (e.g. `-o out.wasm`)
> > 
> > 
> > This work!
> > May I know what `-sSTANDALONE_WASM` really does in this mode? I am a bit confuse with that.
> 
> It attempts to minimize the use of web-only imports, and maximize the use of imports more likely to work outside the web, such as WASI imports.

Thanks for replying!
