### ISSUE TITLE
TypeScript Types for FS

### ISSUE THREAD

**Issue by Mike-Bell** [emscripten-core/emscripten#20953]
In general, I don't see any existing TypeScript type definitions for Emscripten's `FS`. In particular, if I do `EXPORTED_RUNTIME_METHODS=["FS"]` in addition to `--embind-emit-tsd`, emscripten's types have no awareness at all that `FS` exists on my Module, let alone what Type it is.

**Comment by sbc100** [comment]
`--embind-emit-tsd` currently only emits types of embind type (i.e types declared in EMSCRIPTEN_BINDINGS blocks).  

There are plans to extends this to non-embind types.. at which point we might want to rename the option simply `--emit-tsd`.

See #20296  (I guess we can probably close this as duplicate?)

**Comment by Mike-Bell** [comment]
yep, looks like a duplicate of the linked issue
