### ISSUE TITLE
Is there a way to suppress WARNING if main is not exported?

### ISSUE THREAD

**Issue by ChinYikMing** [emscripten-core/emscripten#20967]
**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)
clang version 18.0.0git (https://github.com/llvm/llvm-project f2464ca317bfeeedddb7cbdea3c2c8ec487890bb)
```

If I am confirm that I do not want to export the main function from a C program, is there a way to suppress the WARNING message like below?
```
emscripten:WARNING: main() is in the input files, but "_main" is not in EXPORTED_FUNCTIONS, which means it may be eliminated as dead code. Export it if you want main() to run.
```
Note: I found `-Oz` can do it, but I am wondering if it will lose some optimization for both Wasm and JavaScript?

If not, I might send a PR to support this.

**Comment by sbc100** [comment]
We can make this into a warning that can be suppressed.

If its possible you can modify the code that you are compiling another option is to put an `#ifndef __EMSCRIPTEN__` around the your main function to make it clear emscripten is not using it.    Alternatively maybe you can exclude the entire file that contains the main function?  Both these options come with possible build and runtime perf improvments.

**Comment by ChinYikMing** [comment]
> Alternatively maybe you can exclude the entire file that contains the main function? Both these options come with possible build and runtime perf improvments.

This solve my problem, nice solution. 

Normally, the helper function are modularized into several file (e.g., C language are x.[ch]) so we could only compile helper function code and that is good, but what if we want to export some function inside the file which includes main function without modifying the source code (e.g., add `#ifndef __EMSCRIPTEN__`)? Thus, I think support suppressing the WARNING during build level (e.g., `-w` option in gcc) could be proposed?

**Comment by sbc100** [comment]
Fix is in https://github.com/emscripten-core/emscripten/pull/20969
