### ISSUE TITLE
How to bind a struct member variable that is also a struct in Emscripten's embind to JavaScript?

### ISSUE THREAD

**Issue by Innovgame** [emscripten-core/emscripten#20974]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.25 (febd44b21ecaca86e2cb2a25ef3ed4a0a2076365)
clang version 16.0.0 (https://github.com/llvm/llvm-project effd75bda4b1a9b26e554c1cda3e3b4c72fa0aa8)
Target: wasm32-unknown-emscripten
Thread model: posix

```cpp
struct Inner {
  int x = 0;
  int y = 0;
};

struct Outer {
  Inner inner;
  int z = 0;
};

EMSCRIPTEN_BINDINGS(my_module) {
  emscripten::class_<Inner>("Inner")
    .constructor<>()
    .property("x", &Inner::x)
    .property("y", &Inner::y);

  emscripten::class_<Outer>("Outer")
    .constructor<>()
    .property("inner", &Outer::inner)
    .property("z", &Outer::z); 
}
```

```js
var outer = new Outer();
outer.inner.x = 10;  // error
outer.z = 10; // ok
```
After the assignment above，
why outer.inner.x is 0,  outer.z is 10 ???
I recently started learning about emscripten and would like to know how to use embind to make the operations above work.

**Comment by Innovgame** [comment]
```js
var outer = new Outer();
const inner = new Inner();
inner.x = 10;
outer.inner = inner; // ok
outer.z = 10; // ok
```
like this, it's work. I am very confused.

**Comment by brendandahl** [comment]
Embind is copy by default when accessing objects, so when you do `outer.inner` the copy constructor of `Inner` will be called and why you won't see the value of `x` updated on the original object. Same issue as #3551

**Comment by Innovgame** [comment]
@brendandahl thank you very much.
