### ISSUE TITLE
Is it possible avoid binding js to use unsafe-eval syntax?

### ISSUE THREAD

**Issue by yunsii** [emscripten-core/emscripten#20994]
I have tried to migrate https://github.com/yunsii/fasttext.wasm.js to used in background script of browser extension, after wasm file loaded successful, the binding js encounter the below error:

![image](https://github.com/emscripten-core/emscripten/assets/18096089/12a70ebe-854f-4de3-997e-3cbb730e6b32)
![image](https://github.com/emscripten-core/emscripten/assets/18096089/942bcac2-77aa-44e4-b2b7-f3fd4582ef40)
![image](https://github.com/emscripten-core/emscripten/assets/18096089/3b06431a-36b6-4956-928d-81dbe9176d35)

**Comment by brendandahl** [comment]
`-sDYNAMIC_EXECUTION=0` 
https://github.com/emscripten-core/emscripten/blob/25308a1446bee94c7c1c4dd099fc130f4d6492ca/src/settings.js#L1302-L1333

**Comment by yunsii** [comment]
@brendandahl Thanks for your quick response, I will have a try today and the `settings.js` I will read carefully.

**Comment by brendandahl** [comment]
I'd note that the bindings will be much slower without eval. Whether that matters is how frequently the JS->C++ code path is used, but there's a new option [-sEMBIND_AOT](https://github.com/emscripten-core/emscripten/blob/249cf8c650c7fa27e358cfd759dbc30483b6038f/src/settings.js#L1719-L1724) to generate the binding glue code during compilation and keep the speed of the old bindings.

**Comment by yunsii** [comment]
> bindings will be much slower without eval

Yes, I've noticed this problem, but `-sDYNAMIC_EXECUTION` comment: https://github.com/emscripten-core/emscripten/blob/249cf8c650c7fa27e358cfd759dbc30483b6038f/src/settings.js#L1316-L1317 do not provide the `-sEMBIND_AOT` infomation.

I will try to use `-sEMBIND_AOT` today.

**Comment by yunsii** [comment]
After add `-sEMBIND_AOT` option, encounter runtime error:

![image](https://github.com/emscripten-core/emscripten/assets/18096089/045cbcb6-9eb1-4c0d-9d35-5769cac30b03)

**Comment by brendandahl** [comment]
Can you set a breakpoint or log what `humanName` is in `craftInvokerFunction` and also share the c++ function and what the binding is for it?

**Comment by yunsii** [comment]
![image](https://github.com/emscripten-core/emscripten/assets/18096089/6d5a984d-07c8-4e86-95b1-1a4bdba48b6d)

C function here: https://github.com/facebookresearch/fastText/blob/6c2204ba66776b700095ff73e3e599a908ffd9c3/src/fasttext.h#L105

For the convient, my reproduction repo with branch reproduction: https://github.com/yunsii/fasttext.wasm.js/blob/reproduction/xmake.lua#L26
