### ISSUE TITLE
infinite loop because emscripten_fetch_close calls onerror

### ISSUE THREAD

**Issue by keminming** [emscripten-core/emscripten#21005]
we have a problem of getting into infinite loop because emscripten_fetch_close calls onerror method if the request is in-flight and error again calls emscripten_fetch_close.
So we need to either have a different method to clean up for error cases or completely avoid calling close in error cases. 

**Version of emscripten/emsdk:**
all

**Comment by dschuff** [comment]
by "error again calls emscripten_fetch_close" you mean your onerror handler calls emscripten_fetch_close?

**Comment by keminming** [comment]
> by "error again calls emscripten_fetch_close" you mean your onerror handler calls emscripten_fetch_close?

True. I've the piece of code in the enterprise workspace.

**Comment by dschuff** [comment]
So IIUC the context here is that the onresponse handler wants to clean up the fetch, so it calls `emscripten_fetch_close()` to free the resources. But if the fetch is not done, then `emscripten_fetch_close` calls the onerror handler, which in this case is the same function as the onresponse handler, resulting a a recursion. But the second call to the handler has no way to know that there's already a close in progress, it can only tell whether the fetch is done or not. So currently to avoid infinite recursion, the handler doesn't call `emscripten_fetch_close` unless fetch->readystate is 4 (DONE), which has the problem that the fetch object isn't cleaned up in that case.

Actually, looking at the implementation, [emscripten_fetch_close](https://github.com/emscripten-core/emscripten/blob/main/system/lib/fetch/emscripten_fetch.c#L211) sets the status to -1 when it calls the onerr handler. So it seems like the handler should be able to detect the abort case and early-exit to avoid the recursion?

**Comment by Akhilmanchikanti** [comment]
> So IIUC the context here is that the onresponse handler wants to clean up the fetch, so it calls `emscripten_fetch_close()` to free the resources. But if the fetch is not done, then `emscripten_fetch_close` calls the onerror handler, which in this case is the same function as the onresponse handler, resulting a a recursion. But the second call to the handler has no way to know that there's already a close in progress, it can only tell whether the fetch is done or not. So currently to avoid infinite recursion, the handler doesn't call `emscripten_fetch_close` unless fetch->readystate is 4 (DONE), which has the problem that the fetch object isn't cleaned up in that case.
> 
> Actually, looking at the implementation, [emscripten_fetch_close](https://github.com/emscripten-core/emscripten/blob/main/system/lib/fetch/emscripten_fetch.c#L211) sets the status to -1 when it calls the onerr handler. So it seems like the handler should be able to detect the abort case and early-exit to avoid the recursion?

@dschuff That's correct, we can avoid the recursion. But in that case how would the fetch be cleaned? We are trying to check if fetch needs to be cleared in case of abort requests or not. If yes, is there any other method we can invoke other than `emscripten_fetch_close`

cc: @keminming

**Comment by dschuff** [comment]
In the case I'm imagining, you are in your onresponse handler, and find that you want to abort the fetch. The fetch is still running (`readyState` is e.g. `STATE_LOADING` and `status` is 200 or whatever),  so you call `emscripten_fetch_close` on it. `emscripten_fetch_close` then calls your onerror handler. The onerror handler (regardless of which function it is) can check whether the `status` is -1, and if so, just return. Then after it returns `emscripten_fetch_close` will continue and call `fetch_free` itself.

**Comment by keminming** [comment]
@dschuff That seems to be a solution which is based on the assumption is when onerror is invoked for the 1st time, the status will not be -1. @Akhilmanchikanti maybe we can verify if it's the case, then try with this approach.

**Comment by dschuff** [comment]
Yeah, I think that assumption should hold. I don't see anywhere else in emscripten_fetch.c or in [Fetch.js](https://github.com/emscripten-core/emscripten/blob/main/src/Fetch.js) where we set it to anything other than a real HTTP status code.

**Comment by Akhilmanchikanti** [comment]
> Yeah, I think that assumption should hold. I don't see anywhere else in emscripten_fetch.c or in [Fetch.js](https://github.com/emscripten-core/emscripten/blob/main/src/Fetch.js) where we set it to anything other than a real HTTP status code (or 0, which is what it initializes to and what XHR sets the status to before completion).

@dschuff Can we also assume `onresponse` will never be called with -1 as status? Because in our implementation we have same method registered for `onresponse` and `onerror`, so want to be careful we don't miss any other case.

**Comment by dschuff** [comment]
Yes I think so; all locations that set the status and call the C onprogress, onerror and other handlers are in those 2 files, and they only show 0, real status codes, and the result of XHR.status (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status) which should also only be 0 or HTTP codes.
