### ISSUE TITLE
FS.staticInit() crashes in browser

### ISSUE THREAD

**Issue by ericvergnaud** [emscripten-core/emscripten#21015]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.50 (047b82506d6b471873300a5e4d1e690420b582d0)
clang version 18.0.0 (https://github.com/llvm/llvm-project 14028ec0a62210d68a4dd7a046ac79c8c3b7727e)
Target: wasm32-unknown-emscripten
Thread model: posix

**Failing command line in full:**
Not a compile or link time failure

**Full link command and output with `-v` appended:**
Happens when compiling binaryen, so I don't have access to the actual cmd line

Binaryen/CmakeLists.txt sets FILESYSTEM as follows `add_link_flag("-sFILESYSTEM")`.
This results in including `library_fs.js` in the output.

The browser crashes when loading the generated js (binaryen_wasm.js)

The included code from `library_fs.js` makes an imperative call to:
`FS.staticInit();` (line 95)
which calls `FS.createDefaultDirectories();` (line 1465)
which call `FS.mkdir('/tmp');` (line 1314)
which calls `FS.mknod(path, mode, 0);` (line 666)
which calls `FS.mayCreate(parent, name);` (line 641)
which calls `FS.lookupNode(dir, name);` (line 326)
which calls `FS.lookup(parent, name);` (line 250)
which calls `parent.node_ops.lookup(parent, name);` (line 631)
which throws `FS.genericErrors[{{{ cDefs.ENOENT }}}];` (line 177 of library_memfs.js)

This is blocking, because the code is not guarded by a try/catch, and for some reason it results in a page reload.

**Comment by sbc100** [comment]
This seems odd since we have many tests that use `-sFILESYSTEM`.   Any idea why this doesn't effect all those tests?

**Comment by ericvergnaud** [comment]
Maybe these tests never call FS.staticInit() ?I noticed something strange where I’m able to load the wasm and execute it before it actually crashes. Is there a possibility that due to async calls, the crash happens after the test succeeds and is therefore not noticed ?Envoyé de mon iPhoneLe 4 janv. 2024 à 23:58, Sam Clegg ***@***.***> a écrit :﻿
This seems odd since we have many tests that use -sFILESYSTEM.   Any idea why this doesn't effect all those tests?

**Comment by sbc100** [comment]
`FS.staticInit()` is called during startup in any application that uses the filesystem.   It happens at the top level as the JS is being loaded.  See https://github.com/emscripten-core/emscripten/blob/a6e638d9160609a2b1873e1a1dd48fe0bdc47583/src/library_fs.js#L95

**Comment by ericvergnaud** [comment]
That seems logical but is not what I’m observing. I’ll add some logs manually to better understand the execution sequence.Envoyé de mon iPhoneLe 5 janv. 2024 à 00:53, Sam Clegg ***@***.***> a écrit :﻿
FS.staticInit() is called during startup in any application that uses the filesystem.   It happens at the top level as the JS is being loaded.  See https://github.com/emscripten-core/emscripten/blob/a6e638d9160609a2b1873e1a1dd48fe0bdc47583/src/library_fs.js#L95

**Comment by ericvergnaud** [comment]
Ok, here is what I'm seeing when loading the page:

[localhost-1704447143495.log](https://github.com/emscripten-core/emscripten/files/13840327/localhost-1704447143495.log)

So you are correct that staticInt gets executed. The thrown exception is actually caught, hence why it goes unnoticed. The page reload was caused by an unrelated issue. Closing.
