### ISSUE TITLE
Bug when use wgpuBufferGetMapState

### ISSUE THREAD

**Issue by xdestiny110** [emscripten-core/emscripten#21018]
version of emcc:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)

In library_webgpu.js, the following code will be overwritten by the automatically generated code section that follows it
https://github.com/emscripten-core/emscripten/blob/c0c2ca1314672a25699846b4663701bcb6f69cca/src/library_webgpu.js#L332-L350
This causes errors in places that need to use the string-number mapping relationship, especially for BufferMapState and CompilationMessageType. Should we move this part of the code together to the end? Or should this mapping relationship be declared somewhere else? @kainino0x

**Comment by kainino0x** [comment]
Ah... oops. Let's either put these in a subobject like:
```
    JSToC: {
      BufferMapState: {
        'unmapped': 0,
        'pending': 1,
        'mapped': 2,
      },
      CompilationMessageType : {
        'error': 0,
        'warning': 1,
        'info': 2,
      },
      DeviceLostReason: {
        'undefined': 0,
        'destroyed': 1,
      },
      PreferredFormat: {
        'rgba8unorm': 0x12,
        'bgra8unorm': 0x17,
      },
    },
```
or just give them a different naming convention:
```
    Int_BufferMapState: {
      'unmapped': 0,
      'pending': 1,
      'mapped': 2,
    },
    Int_CompilationMessageType : {
      'error': 0,
      'warning': 1,
      'info': 2,
    },
    Int_DeviceLostReason: {
      'undefined': 0,
      'destroyed': 1,
    },
    Int_PreferredFormat: {
      'rgba8unorm': 0x12,
      'bgra8unorm': 0x17,
    },
```
(no opinion about these names)
