### ISSUE TITLE
wasm-ld: error: AsposePDFforJS.wasm: not a relocatable wasm file

### ISSUE THREAD

**Issue by aidscooler** [emscripten-core/emscripten#21025]
Please include the following in your bug report:
I'm trying to translate a .wasm file into text file. At first I've tried wasm2c.exe by using 'wasm2c AsposePDFforJS.wasm -o AsposePDFforJS.c --enable-threads' , but it is too hard to understand. Then I turned to emscripten hoping to translate it into JS,but it occured a error 'wasm-ld: error: AsposePDFforJS.wasm: not a relocatable wasm file', I'm wondering if there is something wrong,beacause the same error occured again even if I used command 'emcc AsposePDFforJS.wasm -o AsposePDFforJS.c --enable-threads'

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.51 (c0c2ca1314672a25699846b4663701bcb6f69cca)

**Failing command line in full:**
wasm-ld: error: AsposePDFforJS.wasm: not a relocatable wasm file
emcc: error: 'D:/projects/WebAssemblyTest/emsdk/upstream/bin\wasm-ld.exe -o AsposePDFforJS.wasm AsposePDFforJS.wasm -LD:\projects\WebAssemblyTest\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\Bling\AppData\Local\Temp\tmpn4yc0m82libemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)

**Full link command and output with `-v` appended:**
 emcc AsposePDFforJS.wasm -o AsposePDFforJS.js --enable-threads -v
 "D:/projects/WebAssemblyTest/emsdk/upstream/bin\clang.exe" --version
 "D:/projects/WebAssemblyTest/emsdk/upstream/bin\wasm-ld.exe" -o AsposePDFforJS.wasm AsposePDFforJS.wasm -LD:\projects\WebAssemblyTest\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\Bling\AppData\Local\Temp\tmpn4yc0m82libemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --no-entry --stack-first --table-base=1
wasm-ld: error: AsposePDFforJS.wasm: not a relocatable wasm file
emcc: error: 'D:/projects/WebAssemblyTest/emsdk/upstream/bin\wasm-ld.exe -o AsposePDFforJS.wasm AsposePDFforJS.wasm -LD:\projects\WebAssemblyTest\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten -lGL -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr C:\Users\Bling\AppData\Local\Temp\tmpn4yc0m82libemscripten_js_symbols.so --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export-if-defined=fflush --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)

**Comment by sbc100** [comment]
Feel free to re-open if the above answer doesn't make sense is some way.

**Comment by aidscooler** [comment]
> The inputs to emcc much be object files, not executables like that one you have.
> 
> To translate a wasm file into a text format you can use `wasm2wat` (from wabt) or `wasmdis` (from binaryen). This will give you a wat file, which is kind of like the normal text form of a wasm binary. However, don't expect to be able to read and understand large programs in that format as its very low level. There is a another tool in wabt called wasm-decompile with tries to give you a more human readable output. You might want to try that. In any case, emscripten is not the right tool for this task.

Thanks very much.
