### ISSUE TITLE
Duplicate key values for Hash and Double Quote

### ISSUE THREAD

**Issue by ifiddynine** [emscripten-core/emscripten#21030]
DOM_VK_DOUBLE_QUOTE and DOM_VK_HASH have the same values.

See https://github.com/emscripten-core/emscripten/blob/04b4d32115dba2efc01f3c94d75cfc1517bbb652/system/include/emscripten/key_codes.h#L150 as well as https://github.com/emscripten-core/emscripten/blob/04b4d32115dba2efc01f3c94d75cfc1517bbb652/system/lib/html5/key_codes.c#L278.

I'm guessing that it is because of an error in Mozilla's docs https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode where it's claiming that both have the value of 0xA3, but in parantheses it says that DOM_VK_DOUBLE_QUOTE should be 162.

**Comment by sbc100** [comment]
Looks like it was already fixed (by you) upstream so the website no longer shows the wrong hex value (https://github.com/mdn/content/pull/31567)

**Comment by sbc100** [comment]
Would you like to send a PR to fix this?  (I'm happy to make one if not).

**Comment by ifiddynine** [comment]
> Looks like it was already fixed (by you) upstream so the website no longer shows the wrong hex value ([mdn/content#31567](https://github.com/mdn/content/pull/31567))

Yeah sorry I didn't think they'd merge it so quickly! I can make a PR soon, no worries.

**Comment by sbc100** [comment]
No need to apologize!    Thanks for fixes it!
