### ISSUE TITLE
test/printf/test.c take 22 seconds to compile

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#21048]
It seems that clang is doing something very different with the same target here.

`emcc -c test/printf/test.c` take 22 seconds bug `clang -c test/printf/test.c` take less than 1 second.

**Comment by kripken** [comment]
`perf record/report` says:
```
  61.96%  clang    libLLVM-18git.so       [.] llvm::MachineInstr::findRegisterDefOperandIdx(llvm::Register, bool, bool, llvm::TargetRegisterInfo const*) const
  33.76%  clang    libLLVM-18git.so       [.] llvm::WebAssemblyDebugValueManager::WebAssemblyDebugValueManager(llvm::MachineInstr*)
   0.84%  clang    libLLVM-18git.so       [.] llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&)
   0.32%  clang    libLLVM-18git.so       [.] llvm::WebAssemblyFrameLowering::getLocalForStackObject(llvm::MachineFunction&, int)
```
So almost 100% of time in just the top two methods. I'm not familiar enough with the LLVM backend offhand though to guess what that means.

ccing @aheejin as this may be debug related? (however, the STR do not include `-g`... :thinking: )

**Comment by sbc100** [comment]
STR = steps to reproduce?
