### ISSUE TITLE
clang-scan-deps is required for CMake 3.28 C++ 20 module support

### ISSUE THREAD

**Issue by ShuangLiu1992** [emscripten-core/emscripten#21042]
In 
https://chromium.googlesource.com/emscripten-releases/+/refs/heads/main/src/build.py
clang-scan-deps is in the list of unneeded_tool, but it is required by cmake to scan dependencies of cxx 20 modules.
is it possible to include "clang-scan-deps" in emscripten releases?

**Comment by sbc100** [comment]
Sounds reasonable to me.  @dschuff WDYT?

**Comment by dschuff** [comment]
Yeah, I think it would be fine to just add that to the emscripten-releases build.

**Comment by dschuff** [comment]
https://chromium-review.googlesource.com/c/emscripten-releases/+/5182235

**Comment by ShuangLiu1992** [comment]
ran into some issue finding the right headers with the clang-scan-deps tool

```
In file included from /upstream/emscripten/../include/c++/v1/cmath:319:
In file included from /upstream/emscripten/../include/c++/v1/math.h:380:
In file included from /upstream/emscripten/../include/c++/v1/stdlib.h:94:
In file included from /usr/include/stdlib.h:32:
/upstream/emscripten/../include/c++/v1/stddef.h:17:15: fatal error: 'stddef.h' file not found
```

**Comment by sxstd001** [comment]
**Please provide detailed instructions on how to proceed? Specifically, how can I compile C++20 modules, and what is the proper configuration for CMake?**

**Comment by sxstd001** [comment]
**if I use Ninja in clion ide compiles wasm, errors: ** 
clang++: error: unknown argument: '-fmodules-ts'
clang++: error: unknown argument: '-fdeps-file=CMakeFiles/wasm.dir/main.cpp.o.ddi'
clang++: error: unknown argument: '-fdeps-target=CMakeFiles/wasm.dir/main.cpp.o'
clang++: error: unknown argument: '-fdeps-format=p1689r5'
