### ISSUE TITLE
won't compile if folding expression size larger than 256

### ISSUE THREAD

**Issue by zeagle01** [emscripten-core/emscripten#21090]
I was using folding expression in variadic templates with 388 template arguments
but emcc doesn't compiles :
fatal error: instantiating fold expression with 388 arguments exceeded expression nesting limit of 256

with emcc version:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.42 (6ede0b8fc1c979bb206148804bfb48b472ccc3da)

it helps a lot if emcc accept compile flag  "-fbracket-depth=1024" 

I tried add the following in cmake , but it doesn't work
target_compile_options(${TARGET_NAME} PRIVATE "-fbracket-depth=1024")

**Comment by kripken** [comment]
This is likely a clang limitation and not an emscripten one. Does it happen when using `clang` instead of `emcc`?

**Comment by zeagle01** [comment]
it works on mac clang @kripken

**Comment by kripken** [comment]
Ok, then I'm not sure what is causing your issue. That is strange.

Regarding `-fbracket-depth=1024` it does look like `emcc` supports it, because clang does,

```
$ ./emcc test/hello_world.c -fbracket-depth=1024
$ 
```
It just passes it to clang. (If emcc's clang did not recognize that flag, it would error.)

**Comment by zeagle01** [comment]
ok, looks like I set the flag wrong way:  I'm not set this flag at top level cmakelist.txt
I did the following to fixed it:
 I used 
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-fbracket-depth=1024 -pthread -sALLOW_MEMORY_GROWTH -O3") 
at top level CMakeList.txt insdead of setting
target_compile_options(${TARGET_NAME} PRIVATE "-fbracket-depth=1024") 
at subproject CMakeList.txt and the compile error of "nesting limit of 256" is gone!
