### ISSUE TITLE
Building FreeType 7.2.1 using wasm exceptions with error "undefined symbol: emscripten_longjmp"

### ISSUE THREAD

**Issue by frank-pian** [emscripten-core/emscripten#21109]
I try to build a freetype example using emsdk 3.1.51.
http://freetype.org/freetype2/docs/tutorial/example1.c

1. Build freetype
```
cd freetype-2.7.1/build
emcmake cmake -DWITH_ZLIB=OFF -DWITH_BZip2=OFF -DWITH_PNG=OFF -DCMAKE_EXE_LINKER_FLAGS="-fwasm-exceptions" ..
emmmake make
```
2. Install library
3. Build example
```
cd example
emcc example1.c -I./include -L./lib -lfreetype -fwasm-exceptions -sSUPPORT_LONGJMP=wasm
```
```
error: undefined symbol: emscripten_longjmp (referenced by root reference (e.g. compiled C/C++ code))
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _emscripten_longjmp may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: 'C:/Users/bianyongfang/project/emsdk/node/16.20.0_64bit/bin/node.exe C:\Users\bianyongfang\project\emsdk\upstream\emscripten\src\compiler.js C:\Users\BIANYO~1\AppData\Local\Temp\tmp0vjp3n5_.json' failed (returned 1)
```

**Comment by kripken** [comment]
Does adding `-sSUPPORT_LONGJMP=wasm` to the first command help?

I did a quick test in the test suite with this (which does apply that flag IIUC):
```diff
diff --git a/test/test_core.py b/test/test_core.py
index 6b16159a5..029b83189 100644
--- a/test/test_core.py
+++ b/test/test_core.py
@@ -6649,10 +6649,7 @@ void* operator new(size_t size) {
                 includes=[test_file('lua')],
                 output_nicerizer=lambda output: output.replace('\n\n', '\n').replace('\n\n', '\n'))
 
-  @no_asan('issues with freetype itself')
-  @needs_make('configure script')
-  @no_wasm64('MEMORY64 does not yet support SJLJ')
-  @is_slow_test
+  @with_both_eh_sjlj
   def test_freetype(self):
     if self.get_setting('WASMFS'):
       self.emcc_args += ['-sFORCE_FILESYSTEM']
```
```
$ ./test/runner core0.test_freetype_wasm core2.test_freetype_wasm
```
`core2` works but `core0` fails at link time:
```
wasm-ld: error: symbol exported via --export not found: __get_exception_message
wasm-ld: error: symbol exported via --export not found: __cpp_exception
wasm-ld: error: symbol exported via --export not found: __cxa_increment_exception_refcount
wasm-ld: error: symbol exported via --export not found: __cxa_decrement_exception_refcount
wasm-ld: error: symbol exported via --export not found: __thrown_object_from_unwind_exception
```
Not the same error as you so might be something else.

But since `core2` works, that suggests maybe that flag is needed. If it's not that I would look for other differences vs your case that fails and that one that works.

@aheejin might also have an idea here.

**Comment by aheejin** [comment]
As long as you have `-fwasm-exceptions`, you don't need the extra `-sSUPPORT_LONGJMP=wasm`; the SjLj mode follows whatever EH mode you are using.

```console
error: undefined symbol: emscripten_longjmp (referenced by root reference (e.g. compiled C/C++ code))
```
I think the likeliest reason you get this error is when you try to link multiple object files where some of which were built with Emscripten EH and others with Wasm EH. I think freetype has its own Makefile stuff that doesn't have `-fwasm-exceptions` in that so freetype library was built with Emscripten EH and you might be trying to link it with an object file you built with `-fwasm-exceptions`.

**Comment by frank-pian** [comment]
> I think the likeliest reason you get this error is when you try to link multiple object files where some of which were built with Emscripten EH and others with Wasm EH. I think freetype has its own Makefile stuff that doesn't have `-fwasm-exceptions` in that so freetype library was built with Emscripten EH and you might be trying to link it with an object file you built with `-fwasm-exceptions`.

I added the flag -DCMAKE_EXE_LINKER_FLAGS="-fwasm-exceptions" to the freetype build, but it doesn't seem to work.

**Comment by aheejin** [comment]
It is both a compile time and a link time flag. Can you pass it to the compilation flags too?

**Comment by frank-pian** [comment]
> It is both a compile time and a link time flag. Can you pass it to the compilation flags too?
Thanks a lot, I added the “-DCMAKE_C_FLAGS=’-fwasm-exceptions‘” flag and it passes compilation ！
