### ISSUE TITLE
NODEFS and NODERAWFS broken since v3.1.45 with node < v18.3.0

### ISSUE THREAD

**Issue by mzoliker** [emscripten-core/emscripten#21118]
Hi,

In https://github.com/emscripten-core/emscripten/pull/20077 the functions fs.readSync and fs.writeSync have been updated with signatures that did not exist in node v10.19.0 (for instance fs.writeSync with options was only added in node v18.3.0), which breaks running with any earlier version of node.

The four occurrences should really be rewritten as follows for them to work as expected as from node v10.19.0:

```js
return fs.readSync(stream.nfd, new Int8Array(buffer.buffer, offset, length), 0, length, position);
return fs.writeSync(stream.nfd, new Int8Array(buffer.buffer, offset, length), 0, length, position);
var bytesRead = fs.readSync(stream.nfd, new Int8Array(buffer.buffer, offset, length), 0, length, position);
var bytesWritten = fs.writeSync(stream.nfd, new Int8Array(buffer.buffer, offset, length), 0, length, position);
```

Thanks a lot for the fix!

Kind regards,
Maurice

**Comment by sbc100** [comment]
Good to know that someone is still targeting a version of node that old. 

We need to find a way to make those calls work with both wasm64 and old versions of node I guess.

Can I ask why you are targetting such an old version of node?   Are you planning on one day dropping support for older versions like that?   I'm wondering when its reasonable for us to do that same.

**Comment by mzoliker** [comment]
In fact I am using node v18.1.0 (with which my code cannot run as from emscripten v3.1.45), but I need to keep compatibility with node v12.16.0 for historical reasons (run on iOS). That’s why I build with -sMIN_NODE_VERSION=101900 (by the way, not sure which other versions I can safely use other than 101900).

**Comment by sbc100** [comment]
Can you explain what "run on iOS" means?    How do you use node on iOS in your use case?

For sure we need to support node version older than v18.3.0 so we need to fix this issue regardless.

**Comment by kleisauke** [comment]
I just opened PR #21863 for this.

**Comment by mzoliker** [comment]
Hi! Thanks a lot for the fix. When released, I will try to remove the post-processing sed to confirm it now works fine without it :-).
Kind regards,
Maurice
