### ISSUE TITLE
Latest nightly build of firefox is failing all thread threads

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#21163]
It seems the link the wasmMemory that we postMessage to each worker is not actually arriving correctly resulting in `TypeError: can't access property "byteLength", wasmMemory.buffer is undefined / undefined` on each thread.

I took a look at is in firefox devtool and indeed the `e.data.wasmMemory` that arrives on the workers seems to not have any properties at all.

**Comment by kripken** [comment]
Upstream Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1876355
