### ISSUE TITLE
emsdk 3.1.53 leading to:  wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libunwind-b74949c4c5c827f2.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode

### ISSUE THREAD

**Issue by ajgrah2000** [emscripten-core/emscripten#21212]
Sorry if this isn't particularly helpful, but emsdk was working a treat until today (was running latest), so thought I'd flag this (just incase it's of some value).  I haven't looked for a 'minimal repeatable' case.

emsdk version '3.1.52' is leading to a 'wasm-ld' link error.

     archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode

The same build command with 'emsdk version '3.1.52'  (all other steps being equal), works as expected.

Please include the following in your bug report:

emsdk install 3.1.53
emsdk activate 3.1.53

**Failing command line in full:**

linking with `emcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/home/runner/work/_temp/1d1f723c-fd25-4eb0-b3e3-b288c1e932a3/emsdk-main:/home/runner/work/_temp/1d1f723c-fd25-4eb0-b3e3-b288c1e932a3/emsdk-main/upstream/emscripten:/opt/hostedtoolcache/node/20.11.0/x64/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" VSLANG="1033" "emcc" "-s" "EXPORTED_FUNCTIONS=[\"_display_data\",\"_main\"]" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.00.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.01.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.02.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.03.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.04.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.05.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.06.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.07.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.08.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.09.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.10.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.11.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.12.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.13.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.14.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.rusted_atari2600.72de507ca1bf7dd2-cgu.15.rcgu.o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.3g798tusoerxbm2l.rcgu.o" "-L" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps" "-L" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/release/deps" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libhound-29db562b9db31f7e.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libstrum-6dff126ddf2c1562.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libargh-e61b79ba29162820.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libargh_shared-ec61013426edf1d4.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libserde-787b2b34692df155.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libbitfield-98ace053c82e3ed9.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libsdl2-d8af545b1d3c4a39.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libsdl2_sys-8ab4e77d468e8b90.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libbitflags-cc1085192c639d32.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/liblazy_static-2f4e7de96d7ae3c1.rlib" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/liblibc-c5c36a0056a8c234.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd-b883750b59b91630.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libpanic_unwind-880301e073eefa3b.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librustc_demangle-066264b9317419fb.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd_detect-cc031d5997d99ab2.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libhashbrown-22843b220270c3a6.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librustc_std_workspace_alloc-cc2cd0b57807f819.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libminiz_oxide-fedc49ae5e29784d.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libadler-ee7e80cc8ae1075f.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libunwind-b74949c4c5c827f2.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcfg_if-df34262d529e9c78.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liblibc-29e870ad16856240.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/liballoc-1e2a526e06ad848b.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librustc_std_workspace_core-ea6fd1b6d14f889b.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcore-4684818826dd28d6.rlib" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libcompiler_builtins-3457f502b21ed1fe.rlib" "-l" "c" "-B/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "--target=wasm32-unknown-emscripten" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib" "-L" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/self-contained" "-o" "/home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/rusted_atari2600-de428f3583f5a197.js" "-O3" "--profiling-funcs" "-sABORTING_MALLOC=0" "-Wl,--fatal-warnings" "-sWASM=0" "--memory-init-file" "0"
  = note: cache:INFO: generating system asset: symbol_lists/10c8f8f37bc8e6bf34b8d86fb75afc66abd99508.json... (this will be cached in "/home/runner/work/_temp/1d1f723c-fd25-4eb0-b3e3-b288c1e932a3/emsdk-main/upstream/emscripten/cache/symbol_lists/10c8f8f37bc8e6bf34b8d86fb75afc66abd99508.json" for subsequent builds)
          cache:INFO:  - ok
          ports:INFO: retrieving port: sdl2 from https://github.com/libsdl-org/SDL/archive/release-2.24.2.zip
          ports:INFO: unpacking port: sdl2
          cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2.a... (this will be cached in "/home/runner/work/_temp/1d1f723c-fd25-4eb0-b3e3-b288c1e932a3/emsdk-main/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a" for subsequent builds)
          system_libs:INFO: compiled 115 inputs in 8.87s
          cache:INFO:  - ok
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libhound-29db562b9db31f7e.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libstrum-6dff126ddf2c1562.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libargh-e61b79ba29162820.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libargh_shared-ec61013426edf1d4.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libserde-787b2b34692df155.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libbitfield-98ace053c82e3ed9.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libsdl2-d8af545b1d3c4a39.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libsdl2_sys-8ab4e77d468e8b90.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/libbitflags-cc1085192c639d32.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/liblazy_static-2f4e7de96d7ae3c1.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/work/rusted_atari2600/rusted_atari2600/target/asmjs-unknown-emscripten/release/deps/liblibc-c5c36a0056a8c234.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd-b883750b59b91630.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libpanic_unwind-880301e073eefa3b.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librustc_demangle-066264b9317419fb.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libstd_detect-cc031d5997d99ab2.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libhashbrown-22843b220270c3a6.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/librustc_std_workspace_alloc-cc2cd0b57807f819.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libminiz_oxide-fedc49ae5e29784d.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libadler-ee7e80cc8ae1075f.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/asmjs-unknown-emscripten/lib/libunwind-b74949c4c5c827f2.rlib: archive member 'lib.rmeta' is neither Wasm object file nor LLVM bitcode
          wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
          emcc: error: '/home/runner/work/_temp/1d1f723c-fd25-4eb0-b3e3-b288c1e932a3/emsdk-main/upstream/bin/wasm-ld @/tmp/emscripten_ycvpjtfj.rsp.utf-8' failed (returned 1)

**Comment by sbc100** [comment]
Apparently this was fixed upstream in rust: https://github.com/rust-lang/rust/pull/120278

**Comment by ajgrah2000** [comment]
Thanks for you're impressively fast response (and sorry for the extra noise). 
Just adding a comment to confirm that the issue was resolved (as you'd predicted) when I switched to:

rustc 1.77.0-nightly  (was previously using rustc 1.75.0)
emscripten 3.1.53

(I also changed the target to wasm32-unknown-emscripten)
