### ISSUE TITLE
How to pass a pointer of type const in the EMSCRIPTEN_WRAPPER

### ISSUE THREAD

**Issue by Dachong233** [emscripten-core/emscripten#21254]
How to pass a pointer of type const in the EMSCRIPTEN_WRAPPER, I am trying to add a function void passConstObj(const PolyDerived* o), and the compilation prompts the following error:
`error: assigning to 'void *' from 'const PolyDerived *' discards qualifiers`

Reproduction method:
The code comes from the AbstractClassWrapper class in the embind_test of the emscripten repository
```cpp
class AbstractClassWrapper : public wrapper<AbstractClass> {
    ....

void passConstObj(const PolyDerived* o)  override {
        call<void>("passConstObj", o);
    }
};
```

**Comment by JankingWonn** [comment]
> Embind generally doesn't like raw pointers being sent across since it unclear who owns the object. Can you instead use a `std::shared_ptr`?

Thank you @brendandahl. I'm also bothered by this issue. When I tried to change the function to `void passConstObj(const std::shared_ptr<PolyDerived> o)`, the problem was solved. 

But I have a question, ignoring the question of whether embind likes the original pointer preference (because it doesn't affect the compilation of `PolyDerived*` type arguments), why `const PolyDerived*` can't compile the same const argument, but `const std::shared_ptr<PolyDerived>` can

**Comment by brendandahl** [comment]
I misremembered, I thought `val::call` had the same restrictions as bind.h `function` bindings where you must explicitly pass `allow_raw_pointers` if you want to use pointers as arguments. `val::call` doesn't appear to have that restriction, so yes it is strange that `const` pointers don't work. I'm not the original author of this code so I'm not sure what the intent was there or if it was just an oversight.

It seems reasonable to automatically remove the const in the val.h code.

**Comment by brendandahl** [comment]
As for why `const std::shared_ptr` works, that will be a const reference which has a helper `static WireType toWireType(const T& v) {` for sending it to JS so it works.

**Comment by brendandahl** [comment]
There was a relevant discussion previously #7292 but nothing ever came of it.

**Comment by JankingWonn** [comment]
Thanks @brendandahl again. Although I didn't figure it out thoroughly, at least there was a solution.
