### ISSUE TITLE
Bug in page:Optimizing Code 

### ISSUE THREAD

**Issue by MichalGrzymek** [emscripten-core/emscripten#21265]
The section "WebAssembly" reads:

> Emscripten will emit WebAssembly by default. You can switch that off with -sWASM=0 (in which case emscripten emit JavaScript), which is necessary if you want the output to run in places where Wasm support is not present yet, but the downside is larger and slower code.

"emscripten emit" should be replaced with "emscripten will emit" or "emscripten emits"

URL: ../../docs/optimizing/Optimizing-Code

**Comment by sbc100** [comment]
Sounds good.  Feel free to send a PR.

**Comment by MichalGrzymek** [comment]
https://github.com/emscripten-core/emscripten/pull/21269/files
