### ISSUE TITLE
pthread_equal(thread, pthread_self()) && "val accessed from wrong thread

### ISSUE THREAD

**Issue by Charles-Schleich** [emscripten-core/emscripten#21347]
Hello,

I am running into the following issue 

```
Aborted(Assertion failed: pthread_equal(thread, pthread_self()) && "val accessed from wrong thread", at: /emsdk/upstream/emscripten/cache/sysroot/include/emscripten/val.h,400,as_handle)
```

When i try to call 

TS
```ts
      const WasmModule: Module = await wasmmodule();
      var cbFunc = function() {
            console.log("Hi, this is a cb");
      }

      WasmModule.ccall('cbTest', 'number', ['number'], [cbFunc]);  // Assert fail Caused by this line
```

CPP
```c++
  void cbTest(emscripten::val cb)
  {
      cb();
  }
```

I understand WASM has this concept of web workers acting like threads, and sharing their memory via a (SharedArrayBuffer)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer]

Why is this callback function being put into a different thread / Worker ? 

With all of my synchronous TS -> CPP function calls, i get the same thread id output from 

```c++
    std::cout << std::this_thread::get_id();
    std::cout << std::endl;

    std::cout << pthread_self();
    std::cout << std::endl;
```

Why in my case are async function calls handled differently and how do i get the desired behavior, 
Here is a minimal example to replicate.
https://github.com/Charles-Schleich/emsdk-cpp-callbacks

Thank you in advance, and thanks for making an really cool project !

**Comment by sbc100** [comment]
The C++ function you wrote takes an `emscripten::val`.. but you are passing JS function object to it.    You can't pass JS function as a number like that to native code.  I think it will result in the number 0 being passed and then embind (emscripten::val is part of embind) is treating that integer as an `emscripten::val` and things are getting very confused.

See https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html for more on how to call between JS and C++

**Comment by sbc100** [comment]
Closing for now.  Please re-open if needed.
