### ISSUE TITLE
MUNMAP leaks the memory if file descriptor is closed

### ISSUE THREAD

**Issue by nightelf3** [emscripten-core/emscripten#21360]
I noticed a memory leak using Skia's SkStream::MakeFromFile with EMSDK caused by the inability to release the allocated memory when a file descriptor is not valid (even for MAP_PRIVATE mode).

Here are Skia sources as an example.

[[SkStream::MakeFromFile](https://github.com/google/skia/blob/main/src/core/SkStream.cpp#L915)]
```
static sk_sp<SkData> mmap_filename(const char path[]) {
    FILE* file = sk_fopen(path, kRead_SkFILE_Flag);
    if (nullptr == file) {
        return nullptr;
    }

    auto data = SkData::MakeFromFILE(file);  // <--- this calls sk_fmmap and remembers the memory
    sk_fclose(file);  // <--- this releases the file handle, mmaped buffer in `data` won't be released
    return data;
}
```

[[sk_fdmmap](https://github.com/google/skia/blob/main/src/ports/SkOSFile_posix.cpp#L97)]
```
void* addr = mmap(nullptr, fileSize, PROT_READ, MAP_PRIVATE, fd, 0);
```

munmap() [documentation](https://pubs.opengroup.org/onlinepubs/9699919799/functions/munmap.html) specifies the following:
> The munmap() function shall remove any mappings for those entire pages containing any part of the address space of the process starting at addr and continuing for len bytes.

So we should be safe to release the `addr` pointer when `stream` is closed in [munmap_js](https://github.com/emscripten-core/emscripten/blob/59e6b8f1262d75585d8416b728e8cbb3db176fe2/src/library_syscall.js#L163), something like:
```
var stream = FS.getStream(fd);
if (!stream) {
  _free(addr);
 } else {
   ...
 }
```

What do you think about it?
Thank you!

**Comment by sbc100** [comment]
What is the value passed as `fd` in `sk_fdmmap`?  Is it 0 in this case?

**Comment by nightelf3** [comment]
Wow, thank you a lot!
