### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by wojdyr** [emscripten-core/emscripten#21372]
Sorry to bother you with such a trivial matter.
I like to use [codespell][1] to check my code, and it flags one typo in JS generated by emscripten:

    mtz.js:8: nonexistant ==> nonexistent

It originates from this line:
https://github.com/emscripten-core/emscripten/blob/e0c3ce6d2b3f121abab481e6e79a1a60e2fcd18b/src/embind/embind.js#L153

[1]: https://github.com/codespell-project/codespell

**Comment by sbc100** [comment]
Feel free to send a PR to fix this.
