### ISSUE TITLE
-sSUPPORT_ERRNO=0 has regressed

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#21400]
```
git clone https://github.com/juj/emgc.git
cd emgc
emcc emgc.c -o a.js -I. --js-library test/library_test.js -sBINARYEN_EXTRA_PASSES=--spill-pointers -sALLOW_MEMORY_GROWTH -sMAXIMUM_MEMORY=4GB -O3 -g3 -DNDEBUG -mbulk-memory -sMALLOC=emmalloc -msimd128 -flto test\global.c -sSUPPORT_ERRNO=0
wasm-dis a.wasm > a.wast
```
Observe that

```
 (func $__errno_location (result i32)
  (i32.const 1520)
 )
```
is still there.

I see that at some point the documentation in settings.js has gained `[deprecated]` on SUPPORT_ERRNO, though looks like it is now unconditionally coming in. Looks like it is being referenced by `(func $sbrk (param $0 i32) (result i32)`.

**Comment by juj** [comment]
Hmm actually it looks like maybe it is there due to `-g3`.. if I go down to `-g2`, errno disappears.. but I am not 100% sure if its name went away, or if the actual use did also... Let me close this as invalid until I figure out which.

**Comment by sbc100** [comment]
I don't think `-sSUPPORT_ERRNO=0` ever imlied that `__errno_location` would not be part of the native wasm binary.    I don't think it ever effected how we using errno within native code.   Perhaps I'm wrong though.  

My understanding is that any time you call a native function that sets errno you will end up seeing `__errno_location` (or its inline form) in the native binary.  If that isn't true please let met know.

**Comment by juj** [comment]
You're right of course. Indeed -sSUPPORT_ERRNO=0 only applied to the JS side. Or maybe we did have a `-noerrno` variant of some libs in the system_libs.py at some point, don't quite recall.

Though I was happy to see that this was just me tripping up with `-g3`. In `-g2`, that Wasm side `__errno_location` does seem to go away, as there are only writes to that location, and no reads.
