### ISSUE TITLE
Should `FS.mkdirTree` throw if path points to a file?

### ISSUE THREAD

**Issue by hoodmane** [emscripten-core/emscripten#21421]
I think it's a bit unexpected that it returns silently in this case.

**Comment by kripken** [comment]
That does sound like a bug. Reading the source I can't tell why it would happen though, do you have a testcase?

**Comment by hoodmane** [comment]
Let me check, maybe I misinterpreted.

**Comment by hoodmane** [comment]
I was indeed wrong.
```js
FS.writeFile("/lib/a", "xyz");
FS.mkdirTree("/lib/a");
FS.readFile("/lib/a",{encoding: "utf8"}); // returns "xyz"
```
it doesn't raise an error, but it also doesn't overwrite.
```js
FS.mkdirTree("/lib/a");
FS.writeFile("/lib/a", "xyz");
```
raises `errno 31: EISDIR`.
