### ISSUE TITLE
Embuilder fails to build when using the `--lto` flag

### ISSUE THREAD

**Issue by ericoporto** [emscripten-core/emscripten#21466]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.55

**Failing command line in full:**
In 3.1.28 I could run

```
embuilder.py build --lto libstubs libc libc++ libc++abi sdl2 ogg vorbis
```

To build these ports. In 3.1.55, this will give the error

```
embuilder.py: error: unrecognized arguments: libstubs libc libc++ libc++abi sdl2 ogg vorbis
```

When trying to figure it out, apparently what doesn't work anymore is the `--lto` flag.

```
 ./embuilder build vorbis
embuilder:INFO: building vorbis
ports:INFO: retrieving port: ogg from https://github.com/emscripten-ports/ogg/archive/version_1.zip
ports:INFO: unpacking port: ogg
cache:INFO: generating system library: sysroot\lib\wasm32-emscripten\libogg.a... (this will be cached in "C:\Users\user\git\Emscripten\emscripten\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libogg.a" for subsequent builds)
system_libs:INFO: compiled 2 inputs in 0.27s
cache:INFO:  - ok
ports:INFO: retrieving port: vorbis from https://github.com/emscripten-ports/vorbis/archive/version_1.zip
ports:INFO: unpacking port: vorbis
cache:INFO: generating system library: sysroot\lib\wasm32-emscripten\libvorbis.a... (this will be cached in "C:\Users\user\git\Emscripten\emscripten\emsdk\upstream\emscripten\cache\sysroot\lib\wasm32-emscripten\libvorbis.a" for subsequent builds)
system_libs:INFO: compiled 22 inputs in 1.36s
cache:INFO:  - ok
embuilder:INFO: ...success. Took (3.27s)
```

now with `--lto`

```
 ./embuilder build --lto vorbis
usage: embuilder.py [-h] [--lto] [--lto=thin] [--pic] [--force] [--verbose] [--wasm64]
                    {build,clear,rebuild} [targets ...]
embuilder.py: error: unrecognized arguments: vorbis
```

Edit: apparently now it only works when running `./embuilder --lto build vorbis`.

**Comment by ericoporto** [comment]
From code changes there isn't something obvious to cause the change, or at least not with intent, but the workaround works for me

**Comment by sbc100** [comment]
Yeah I think this is working as intended.  Everything after the "command" (in this case `build`) is considered a target.   We could try to make this work but I'm not sure its worth it.

**Comment by ericoporto** [comment]
It's not worth it I think. I still reported because

- it took me a minute to figure it out
- I like to register things in case I forget I can Google and find the answer from my previous self

**Comment by sbc100** [comment]
Oh I just noticed that this is regression.   I bisected it to #17871.  It looks like maybe it was the change from `nargs='*'` to `nargs='+'`. 

We could try to revert that part perhaps?
