### ISSUE TITLE
3.1.55 does not contain ports changes

### ISSUE THREAD

**Issue by ypujante** [emscripten-core/emscripten#21465]
I can see that 3.1.55 has been released 

<img width="632" alt="Screenshot 2024-03-03 at 11 51 31" src="https://github.com/emscripten-core/emscripten/assets/357116/1a600a63-d962-4d3a-955f-900503b386d4">

I did an update of my local emscripten and install latest:

```
Resolving SDK alias 'latest' to '3.1.55'
Resolving SDK version '3.1.55' to 'sdk-releases-f5557e3b7166d05bddb5977e363ec48cd06e9d32-64bit'
Installing SDK 'sdk-releases-f5557e3b7166d05bddb5977e363ec48cd06e9d32-64bit'..
Skipped installing node-16.20.0-64bit, already installed.
Skipped installing python-3.9.2-64bit, already installed.
Installing tool 'releases-f5557e3b7166d05bddb5977e363ec48cd06e9d32-64bit'..
Downloading: /usr/local/emsdk/downloads/f5557e3b7166d05bddb5977e363ec48cd06e9d32-wasm-binaries-arm64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/mac/f5557e3b7166d05bddb5977e363ec48cd06e9d32/wasm-binaries-arm64.tar.xz, 226230644 Bytes
Unpacking '/usr/local/emsdk/downloads/f5557e3b7166d05bddb5977e363ec48cd06e9d32-wasm-binaries-arm64.tar.xz' to '/usr/local/emsdk/upstream'
Done installing tool 'releases-f5557e3b7166d05bddb5977e363ec48cd06e9d32-64bit'.
Done installing SDK 'sdk-releases-f5557e3b7166d05bddb5977e363ec48cd06e9d32-64bit'.
```

None of the 2 changes I did (fix the exception for file:// protocol or new version of the contrib port) are in the distribution. Is this expected? The commit marking 3.1.55 as "released" happened after these 2 commits. I am fine to wait until the next release, but I just want to make sure that it is not something unintended...

**Comment by curiousdannii** [comment]
That commit is just to prepare the source code for the next release, which happens after it was made (though usually quicker, I thought). The actual tag is even earlier: https://github.com/emscripten-core/emscripten/tags

**Comment by ypujante** [comment]
That makes sense. Thank you for confirming.
