### ISSUE TITLE
JS Atomics.add is failed  when Allocated Memory is over than 2G despite of declaration of MAXIMUM_MEMORY=4G 

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#21476]
**The App is crash on that line:** 
Atomics.add(GROWABLE_HEAP_I32(), this.ptr + 0 >> 2, 1);

isn't should it replaced by GROWABLE_HEAP_U32() in case of MAXIMUM_MEMORY=4G ?

**App Running in Chrome Browser.** 

**emcc version**: 3.1.29

**Linker flags:**
`-s ALLOW_TABLE_GROWTH -s WASM_BIGINT  -s EXPORTED_RUNTIME_METHODS=ccall,cwrap,addFunction  -s EXPORTED_FUNCTIONS=_main  -g  -gsplit-dwarf -gdwarf-5 -gpubnames --bind -s USE_PTHREADS -s ALLOW_MEMORY_GROWTH=1    -s ASSERTIONS  -s FETCH   -s NO_DISABLE_EXCEPTION_CATCHING -s TEXTDECODER=0  -lidbfs.js -s PTHREAD_POOL_SIZE=60 -s ERROR_ON_WASM_CHANGES_AFTER_LINK -s REVERSE_DEPS=all -s STACK_SIZE=5mb -s DEFAULT_PTHREAD_STACK_SIZE=5mb -s ALLOW_BLOCKING_ON_MAIN_THREAD=1  -s PTHREAD_POOL_SIZE_STRICT=2 -s MAXIMUM_MEMORY=4gb`

**Screenshot of the crash:**

![image](https://github.com/emscripten-core/emscripten/assets/41375082/4bfe0508-0722-48fa-aca0-1e56430f8ef0)

**Comment by kripken** [comment]
Yes, that looks like a bug in 3.1.29. It is no longer an issue though in 3.1.36+ since that code path was moved into wasm, so upgrading should fix this for you.
