### ISSUE TITLE
Uncaught ReferenceError error in abort (preamble.js) when WebAssembly is not available 

### ISSUE THREAD

**Issue by localpcguy** [emscripten-core/emscripten#21484]
The [abort method in preamble.js tries to use WebAssembly to create a RuntimeError](https://github.com/emscripten-core/emscripten/blob/e0bd10a0b61e08d1ed30966b6d8351ea06376fd4/src/preamble.js#L461) and crashes with an Uncaught ReferenceError when WebAssembly is not available. Looking at the [history](https://github.com/emscripten-core/emscripten/issues/9715#issuecomment-547141350), this used to be wrapped in a [check for WASM](https://github.com/emscripten-core/emscripten/pull/9730/files), but once fastcomp was removed, that check would always be true, and so [the check was removed](https://github.com/emscripten-core/emscripten/pull/12122/files#diff-340052a3814c9bb184b46dce8b603735acd1ef361001c3710e63650512a700c5). 

My question is, is it intentional for it to fail with an `Uncaught ReferenceError: WebAssembly is not available` or was that a side effect of WASM being true and then being removed? It does seem per the original intent that there should be an error thrown at this point to exit/abort the script, so would any fix just end up throwing a manually crafted error instead of failing due to WebAssembly being undefined?

This [error is currently seen when using Rive-Canvas](https://github.com/rive-app/rive-wasm/issues/147), which using emscripten, if I don't check for WebAssembly support prior to trying to use their code.
![image](https://github.com/emscripten-core/emscripten/assets/593240/51e1009d-0dba-4fd3-8882-9f0b1315da3f)
![image](https://github.com/emscripten-core/emscripten/assets/593240/d1ee9300-0c04-4f04-b14d-0754f27dfbb2)

**Comment by kripken** [comment]
Is this in a debug or release build?

In a debug build we should make sure we have a clear error for this. If we don't have one we should add one.

In a release build that targets wasm (i.e. not wasm2js) we do not generally add to the output size in order to get nicer error messages. Running such a build on a VM without the `WebAssembly` object would be a such a case, I think - not worth adding to size for, in release.

**Comment by localpcguy** [comment]
I believe it is in a release build. I agree it would be nice to have a clear error in a debug build, if nothing else, it would make it clear when reading that code that it is throwing intentionally and is not an error that requires resolution.
