### ISSUE TITLE
WebSocket onmessage error with wasm64

### ISSUE THREAD

**Issue by tbuchs** [emscripten-core/emscripten#21515]
Hi, as already explained in https://github.com/emscripten-core/emscripten/issues/21503 im currently trying to work with -sMEMORY64. The previous bug is resolved, thank you for that. However, now if I receive a message I have the weird bug, that there is no data even though the debug message prints the data.
I have the following code to test:
```
static EM_BOOL WebSocketMessage([[maybe_unused]]int eventType, const EmscriptenWebSocketMessageEvent *e, void *userData) {
  cerr << "Received message" << endl;
  if(!e)
    cerr << "e is null" << endl;
  cerr << "e is not null";
  cerr << " " << e->numBytes;
  cerr << " " << e->isText;
  cerr << " " << e->socket;
  cerr << " " << e->data;
  string message = (char*)e->data;
```
The Debug Output is the following:
```
w:0,t:0x001782f0: websocket event "open": socketId=1,userData=1720968,callbackFunc=2620)
w:0,t:0x001782f0: emscripten_websocket_send_utf8_text(socketId=1,textData=42 ' chars, "{"conten...") 
w:0,t:0x001782f0: WebSocket onmessage, received data: "{"type":"login","success":true}", 31 chars, 32 bytes encoded as UTF-8: "{"type":"login","success":true}"
Received message
e is not null 0 0 1
Uncaught RuntimeError: index out of bounds
```
I get that the index is out of bounds, because there is no data - however the debug message prints the received message correctly? Thanks for your help!

**Comment by sbc100** [comment]
What error are you seeing now?

Are you referring to the changed made in #21531?   Did you remove the new `getSocket` helper along with all the callers of that function?

**Comment by sbc100** [comment]
Maybe open a new bug?  Unless you think the new issue is is the same thing (i.e. wasm64 related).
