### ISSUE TITLE
Did 3.1.56 get mis-tagged?

### ISSUE THREAD

**Issue by chenrui333** [emscripten-core/emscripten#21520]
👋 raise this issue to ask if 3.1.56 get mis-tagged, as it did not show in https://github.com/emscripten-core/emsdk/blob/main/emscripten-releases-tags.json. Thanks!! 🙏 

relates to https://github.com/Homebrew/homebrew-core/pull/165953

cc @sbc100

**Comment by sbc100** [comment]
IIUC the release is still be worked on.   I imagine by EOD those tags will be in place.

**Comment by chenrui333** [comment]
Cool, thanks @sbc100!
