### ISSUE TITLE
Update llvm libraries to 18.1.1

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#21530]
According to https://releases.llvm.org/, 18.1.1 was released on March 8th

**Comment by sbc100** [comment]
@aheejin, do you fancy doing this again?   If not I can take this one.

**Comment by aheejin** [comment]
Sounds good but do you mind if we do it next week-ish? Not sure if I have the chance this week.

**Comment by sbc100** [comment]
I don't know of any rush no.

**Comment by sbc100** [comment]
Hopefully this will fix #21382

**Comment by sbc100** [comment]
As of #21638 we are now on 18.1.2.
