### ISSUE TITLE
loading-workers error

### ISSUE THREAD

**Issue by DylanShang** [emscripten-core/emscripten#21547]
**Version of emscripten/emsdk:**
3.1.51

**Failing command line in full:**
<img width="1440" alt="Screenshot 2024-03-16 at 14 12 51" src="https://github.com/emscripten-core/emscripten/assets/25336419/57c3a5ee-afed-4587-aebc-0fdfc54e870a">

It runs well when I compile without -pthread. And if I compile with -pthread, there are no problems in the compilation process, and wasm and js files are generated. But once I run wasm.js, this error occurs, I debugged the program and it seems that blocking occurs at wasm.js:
`let pthreadPoolReady = Promise.all(PThread.unusedWorkers.map(PThread.loadWasmModuleToWorker));
  pthreadPoolReady.then(onMaybeReady);`

It seems that `loadWasmModuleToWorker` is not executed correctly

Assertions and -g are enabled, but no error occurs during the compiling

**Comment by sbc100** [comment]
Can you share the full list of the link flags you are using?

Do you see any error occur other than the logging message you shared here?  Do you see any messages early on about failing to start workers?

**Comment by DylanShang** [comment]
It disappeared for unknown reason.

**Comment by DylanShang** [comment]
close it because it disappeared

**Comment by DylanShang** [comment]
close because it disappeared
