### ISSUE TITLE
Using UTF8ToString with Wasm64

### ISSUE THREAD

**Issue by tbuchs** [emscripten-core/emscripten#21541]
When running a C++ code built with `-sWASM64=1` containing a call to the preamble.js function `UTF8ToString` the function throws the assertion `assert(typeof ptr == 'number', UTF8ToString expects a number (got ${typeof ptr}));` which gives the following output:
`Aborted(Assertion failed: UTF8ToString expects a number (got bigint))`

**Comment by sbc100** [comment]
With `-sWASM64` we convert all incoming pointers to `number` (technically a 53 bit integer which we refer to as int53 internally) when they arrive on the JS side.   In other words, from JS code, pointers should still be `number`.

How are you receiving the pointer value that you are passing to `UTF8ToString`?

**Comment by sbc100** [comment]
The fix here would be to add a `__sig` entry to your `testWasm64ToString` function in the JS library.

Something like `testWasm64ToString__sig: 'ip'`.     This says the return value is an `i` (integer) and the first and only argument is a`p` (pointer).   This will enable emscripten to automatically convert the incoming bigint value to an integer.
