### ISSUE TITLE
emprofile generates an HTML with a syntax error

### ISSUE THREAD

**Issue by mere-human** [emscripten-core/emscripten#21551]
The resulting HTML code contains a JavaScript syntax error due to a missing parentheses:
https://github.com/emscripten-core/emscripten/blob/918e131fae0b5c7b1d05a5c75d7e8e676c377713/tools/toolchain_profiler.results_template.html#L78

**Version of emscripten/emsdk:**
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.54 (a95c44ee924d02fa1498f846595485d27c31daa8)
clang version 19.0.0git (https://github.com/llvm/llvm-project e769fb8699e3fa8e40623764f7713bfc783b0330)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Users\user\emsdk\3.1.54\upstream\bin
```

**Failing command line in full:**
`emprofile.bat --outfile=myresults.html`

**Full link command and output with `-v` appended:**
Build with `EMPROFILE=1` as documented at https://emscripten.org/docs/optimizing/Profiling-Toolchain.html

**Comment by sbc100** [comment]
Would you have time to send a PR?
