### ISSUE TITLE
dlopen + pthreads with FS not working

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#21576]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.35 (a90c5abb489c516f59c0d16864d953d4bedd37da)
clang version 17.0.0 (https://github.com/llvm/llvm-project 6865cff8ea8b07d9f2385fd92cecb422404f0f35)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: ~/emsdk/upstream/bin
```

We currently do runtime dynamic linking (`dlopen`) in our app which is single-threaded. For `dlopen` to work, we have used `FS.createLazyFile` for all the side modules in `Module.preInit`. When `dlopen` is called side-modules are downloaded and used. Now, we are trying to enable pthreads in our app. When `dlopen` is called on a thread other than main application thread (on which we have mounted the side modules), `FS` is unable to find these mounted side modules and hence our whole logic fails. Does `FS` even work with pthreads? Or is there any alternate way of using `dlopen` with pthreads?

**Comment by ravisumit33** [comment]
@sbc100 Thoughts on this?

**Comment by ravisumit33** [comment]
@kripken @sbc100 Please confirm if FS does supoort multithreading. If not, what are other options to try for the scenario described above?

**Comment by sbc100** [comment]
The FS object only exists (or rather is only usable) on the main thread.

However, all filesystem operations in C/C++ are proxied back to the main thread.  In particular with `dlopen` the operation is always proxied back to the main thread.    So we have several test for dlopen on multiple threads so we know it works in the general case and there should no no FS operations that occur on the side module.  

Can you try with the latest version of emscripten (3.1.35 is a year old now)?   It could be that some of the fixes needed for side modules and threading happened in more recent versions.

**Comment by ravisumit33** [comment]
Yes, fixed in latest version. Thanks.
