### ISSUE TITLE
std::vector<MyBoundType> returns UnboundTypeError

### ISSUE THREAD

**Issue by fraguada** [emscripten-core/emscripten#21572]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.30

I have an issue related to using arrays of custom types as function arguments. When trying to use these arrays, I get an UnboundTypeError.

In js I create an array like
```
const arr = [myCustomType, myCustomType]
callTheMethod(arr)
```

in cpp `callTheMethod` is something like
`void callTheMethod(std::vector<MyCustomType> stuff) {}`
`MyCustomType` is a bound class from a cpp lib
Looking around, I see that I should use `emscripten::register_vector<MyCustomType>("MyCustomTypeArray");`, but I have a lot of types, and I don't want to create a new object for every one of my custom classes so that I can pass an array of them to a function. Is there an alternative?

**Comment by brendandahl** [comment]
Are you trying to avoid just calling `register_vector` for each bound type or avoid `register_vector` and a `class_` binding for each type?

If you're fine with still doing the class bindings, you can create a template wrapper around `class_` or a macro that registers the class and vector at the same time.

**Comment by fraguada** [comment]
I already have all of the class bindings. How would I 

> create a template wrapper around class_ or a macro that registers the class and vector at the same time.

?

**Comment by brendandahl** [comment]
Something like:

```c++
using namespace emscripten;

struct Foo {};

template<typename T>
class_<T> class_and_vector(const char* name) {
  std::string vectorName(name);
  vectorName.append("Vector");
  register_vector<T>(vectorName.c_str());
  return class_<T>(name);
}

EMSCRIPTEN_BINDINGS(xxx) {
  class_and_vector<Foo>("Foo")
    .constructor<>();
}
```

**Comment by fraguada** [comment]
So on the js side, I'd have `Module.Foo` and `Module.FooVector`?

**Comment by fraguada** [comment]
I believe I didn't have a great understanding of `emscripten::val` and am fine with having function args in cpp that I then interrogate for `myArray["length"]` and access like `myArray[i].as<MyBoundClass>();`

I appreciate your help in any case!
