### ISSUE TITLE
undefined symbol `__cpp_exception` without enabled exceptions

### ISSUE THREAD

**Issue by svenpilz** [emscripten-core/emscripten#21570]
Hi all!

We switched from _3.1.52_ to _3.1.56_ and noticed a new `undefined symbol __cpp_exception` linker error.

Happy for any pointers here :). Thanks and greetings from Berlin.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.56 (cf90417346b78455089e64eb909d71d091ecc055)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 34ba90745fa55777436a2429a51a3799c83c6d4c)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Settings:**
* `-pthread`
* `-sALLOW_MEMORY_GROWTH=1`
* `-sENVIRONMENT=worker`
* `-sEXPORTED_RUNTIME_METHODS=['ENV']`
* `-sINITIAL_MEMORY=128mb`
* `-sLLD_REPORT_UNDEFINED`
* `-sMALLOC=mimalloc`
* `-sMODULARIZE=1`
* `-sSTACK_SIZE=2MB`

Neither `-fwasm-exceptions` no `-fexceptions` was specified.

**Output:**
```
wasm-ld: error: HOME/.conan/data/boost/1.84.0/user/stable-rev2/package/b5d313b8104b482c4b43f96d3236c337eb02d6da/lib/libboost_thread.a(thread.o): undefined symbol: __cpp_exception
```
Note: `Boost` was build using conan with the same Emscripten version.

**Comment by sbc100** [comment]
I think the problem here is that `libboost_thread.a` must be being built with `-fwasm-exceptions`.   Can you see that flags being used to build that library?

**Comment by svenpilz** [comment]
Seems you are right, Boost's build tool seems to handle this now

```
toolset.flags emscripten.compile.c++ OPTIONS <exception-handling>on/<exception-handling-method>js : -fexceptions ;
toolset.flags emscripten.link        OPTIONS <exception-handling>on/<exception-handling-method>js : -fexceptions ;
toolset.flags emscripten.compile.c++ OPTIONS <exception-handling>on/<exception-handling-method> : -fwasm-exceptions ;
toolset.flags emscripten.link        OPTIONS <exception-handling>on/<exception-handling-method> : -fwasm-exceptions ;
```

https://github.com/boostorg/build/blob/efbf6ce59b4023f7adc9be2fc3875d371c7f52c6/src/tools/emscripten.jam#L133

Thank you very much and sorry the noise.
