### ISSUE TITLE
put_time returning time zone as "Easter"

### ISSUE THREAD

**Issue by jrobichaux** [emscripten-core/emscripten#21582]
In the latest emscripten, a call to `std::put_time( std::localtime(&t_time), "%Z" )` on my Windows machine returns "Easter" instead of "Eastern Daylight Time". 

This worked properly on the previous version I was using (3.1.51).

Minimal repro:

**time_test.cpp**
```cpp
#include <ctime>
#include <iomanip>
#include <iostream>

int main()
{
	std::time_t t_time = std::time( NULL );
	std::cout << "time zone = " << std::put_time( std::localtime(&t_time), "%Z" ) << std::endl;
	return 0;
}
```

**Compile with:**
`em++ time_test.cpp`

**Run with:**
`node a.out.js`

On my machine (Windows 10) this returns "time zone = Easter". If I compile as a standard Windows executable it properly returns "time zone = Eastern Daylight Time".

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.56 (cf90417346b78455089e64eb909d71d091ecc055)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 34ba90745fa55777436a2429a51a3799c83c6d4c)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by sbc100** [comment]
I believe this is due to #21375.

The max number of chars in timezone name in POSIX is defined to be 6 (https://github.com/emscripten-core/emscripten/blob/2316d8abdc3b6f403cfce357a59f58a46e6af638/system/lib/libc/musl/include/limits.h#L151) and musl's internal data structures use this limit.     

If we could fix node on windows to give the abbreviated name (EDT) would that be enough to fix your issue?  Or do you really need/want to full unabbreviated name?

**Comment by jrobichaux** [comment]
Wow, fast answer. Abbreviated name works for me, that's what we're getting on iOS and Mac already. 

Thanks!

**Comment by sbc100** [comment]
Sadly I couldn't find any easy way to get such names on windows :(

BTW is node your target environment or it the browser?   Do you know if the same results are produced when running the browser on windows?

**Comment by jrobichaux** [comment]
It's a browser app. I get the same (Easter) when I run it on Chrome in Windows.

**Comment by sbc100** [comment]
OK, in that case I think we need to increase out TZNAME_MAX so allow for these windows timezone names.

**Comment by jrobichaux** [comment]
If it helps, the [TIME_ZONE_INFORMATION struct](https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/ns-timezoneapi-time_zone_information) uses a max length of 32 for Windows timezone names. 

Ironically the example on that page shows a return value of "EST" for the StandardName, but when I call GetTimeZoneInformation I get the full "Eastern Daylight Time" for that value.

**Comment by sbc100** [comment]
Thanks @jrobichaux , do you happen to know if there is any way to access the `StandardName` on the web or under node?  I'm guessing the answer is no?

**Comment by jrobichaux** [comment]
> do you happen to know if there is any way to access the `StandardName` on the web or under node? I'm guessing the answer is no?

Not that I know of. I was just thinking if you were going to increase the size of `TZNAME_MAX` then 32 should be a good number. 

But I saw what you did in #21585 by using Javascript directly, and that's a good/clever workaround. Thanks!
