### ISSUE TITLE
No transitive dependency with emscripten ports

### ISSUE THREAD

**Issue by ypujante** [emscripten-core/emscripten#21597]
I am currently working on a new port (ImGui) which depends on `contrib.glfw3`.

The (imgui) port code declare the dependency on `contrib.glfw3`:

```python
deps = ['contrib.glfw3']
```

If I compile using only the imgui port, then it doesn't work

```python
/usr/local/emsdk/emscripten/main/emcc --shell-file shell_minimal.html --use-port=../../ports/ImGui/imgui.py main.cpp -o /tmp/imgui/index.html
wasm-ld: error: /var/folders/wz/zqhny4ks031bqlr6r27bfkzm0000gn/T/emscripten_temp_sfrjpsah/main_0.o: undefined symbol: glfwSetErrorCallback
... skipped other errors
emcc: error: '/usr/local/emsdk/upstream/bin/wasm-ld -o /tmp/imgui/index.wasm /var/folders/wz/zqhny4ks031bqlr6r27bfkzm0000gn/T/emscripten_temp_sfrjpsah/main_0.o -L/usr/local/emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten /usr/local/emsdk/emscripten/main/cache/sysroot/lib/wasm32-emscripten/lib_imgui_1.90.4-opengl3.a -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lnoexit -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /var/folders/wz/zqhny4ks031bqlr6r27bfkzm0000gn/T/tmpg_nu5h31libemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)
```

If instead I explicitly add `--use-port=contrib.glfw3` to the command line then it works fine

```python
/usr/local/emsdk/emscripten/main/emcc --shell-file shell_minimal.html --use-port=contrib.glfw3 --use-port=../../ports/ImGui/imgui.py main.cpp -o /tmp/imgui/index.html
```

How could we address this issue?

I have a feeling that `port.process_args` needs to be called on dependent ports as well. But I am not sure if that is the right approach.

I can obviously work on this if you provide guidance.

**Comment by ypujante** [comment]
Actually looking/playing with the code, the function:

```python
def get_libs(settings):
  """Called add link time to calculate the list of port libraries.
  Can have the side effect of building and installing the needed ports.
  """
  ret = []
  needed = get_needed_ports(settings)

  for port in dependency_order(needed):
    print(f'get_libs for {port.name}')
    # if port.needed(settings):
    if True:
      print(f'get_libs needed for {port.name}')
      port.linker_setup(Ports, settings)
      # port.get returns a list of libraries to link
      ret += port.get(Ports, settings, shared)

  ret.reverse()
  return ret
```

seems to the be the cause of the problem. If I unconditionally (`if True:`) call `port.linker_setup` then the problem goes away...

**Comment by sbc100** [comment]
I think the solution here it explicitly add `--use-port=contrib.glfw3` to the build commands within your iwfui build file.

This is what we do for sdl2_image, for example: https://github.com/emscripten-core/emscripten/blob/ecdca7ba001306e4361584bbfcd873945143434f/tools/ports/sdl2_image.py#L61.  Note the `-sUSE_SDL=2` on that line.

**Comment by sbc100** [comment]
> I think the solution here it explicitly add `--use-port=contrib.glfw3` to the build commands within your iwfui build file.
> 
> This is what we do for sdl2_image, for example:
> 
> https://github.com/emscripten-core/emscripten/blob/ecdca7ba001306e4361584bbfcd873945143434f/tools/ports/sdl2_image.py#L61
> 
> . Note the `-sUSE_SDL=2` on that line.

Basically the `emcc` subcommands you are using the build your new port (imgui) don't know that they are part of imgui, or that they need to include glfw, unless you explicitly tell them to use glfw.

**Comment by sbc100** [comment]
We could of course try to automatically add the correct flags the sub-commands.   But I'm not sure its worth it.

**Comment by ypujante** [comment]
I don't think that adding `-sUSE_SDL=2` to the port file like you showed is what makes it work (it is only used for compiling the sdl2_image library, not linking). It is also added on the command line explicitly every time sdl2_image is used:

```python
  # example
  def test_sdl2_image_prepare_data(self):
    # load an image file, get pixel data.
    shutil.copyfile(test_file('screenshot.jpg'), 'screenshot.not')
    self.reftest('test_sdl2_image_prepare_data.c', 'screenshot.jpg',
       args=['--preload-file', 'screenshot.not', '-sUSE_SDL=2', '-sUSE_SDL_IMAGE=2'], manually_trigger_reftest=True)
```

The part that doesn't make any sense to me and would like to understand is why cflags is picking up all the args from all dependencies but linker flags are not.

```python
# add_cflags
  for port in dependency_order(needed):
    port.get(Ports, settings, shared)
    args += port.process_args(Ports)

#  get_libs
  for port in dependency_order(needed):
    if port.needed(settings):
      port.linker_setup(Ports, settings)
      # port.get returns a list of libraries to link
      ret += port.get(Ports, settings, shared)
```

Everytime somebody uses `-sUSE_SDL_IMAGE=2` you MUST write `-sUSE_SDL=2 -sUSE_SDL_IMAGE=2`. Now you are saying every time somebody uses my new port, they MUST write `--use-port=contrib.glfw3 --use-port=contrib.imgui`.

I understand that this is the way it is, but it is exposing the internals of how the port is implemented. The fact that this port uses glfw3 is purely an implementation detail that gets surfaced.

The fix I am suggesting is to have `get_libs` follow the same pattern as `add_cflags`.

```python
#  get_libs (fix)
  for port in dependency_order(needed):
    port.linker_setup(Ports, settings)
    # port.get returns a list of libraries to link
    ret += port.get(Ports, settings, shared)
```

This works perfectly on my local version of emscripten

**Comment by ypujante** [comment]
After spending more time with the code, I realized that current ports actually add their dependencies for link time. There is just no way to do it for ports that don't use `settings` which are the new ports moving forward (including contrib ports). It was definitely an overlook from when I implemented contrib ports.

The PR #21602 is a proposed solution which works great IMO.
