### ISSUE TITLE
Template Instantiation Error in system/lib/libcxx/include/__memory/pointer_traits.h

### ISSUE THREAD

**Issue by SaraBaradaran** [emscripten-core/emscripten#21603]
I faced the following error when compiling proxy (https://github.com/microsoft/proxy) using Emscripten. It seems there is a bug in `system/lib/libcxx/include/__memory/pointer_traits.h` header.

version: latest and even 3.1.54

```
/home/sara/emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/__memory/pointer_traits.h:118:22: error: implicit instantiation of undefined template 'std::__pointer_traits_element_type<std::nullptr_t>'
  118 |     typedef typename __pointer_traits_element_type<pointer>::type    element_type;
      |                      ^
```
You can reproduce the error using the following commands:

```
$ git clone https://github.com/microsoft/proxy
$ cd proxy/build
$ emcmake cmake ..
$ emmake cmake --build .
```

**Comment by sbc100** [comment]
Our C++ headers come from clang's libc++.   Do you happen to know if this issue also occurs with libc++?   You can try this by building using `-stdlib=libc++`.

If this is an issue was was already fixes in libc++ then this could be fixed when https://github.com/emscripten-core/emscripten/issues/21530 is fixed
