### ISSUE TITLE
typedef redefinition with different types

### ISSUE THREAD

**Issue by adokhugi** [emscripten-core/emscripten#21616]
**Version of emscripten/emsdk:**

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.56 (cf90417346b78455089e64eb909d71d091ecc055)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 34ba90745fa55777436a2429a51a3799c83c6d4c)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: C:\Projects\levasoft\emsdk\upstream\bin
```

**Failing command line in full:**
```
emcc -Iinclude main.cpp -O2 -std=c++14 -I. -I./eigen/ -Ic:/protobuf/src c:/protobuf/src/.libs/libprotobuf.a crn/crn.o -s USE_SDL=2 -s FETCH=1 -s TOTAL_MEMORY=1073741824 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=4 -o main.html

In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\cstddef:43:
include\stddef.h:437:3: error: typedef redefinition with different types ('struct max_align_t' vs 'struct max_align_t')
  437 | } max_align_t;
      |   ^
C:\Projects\levasoft\emsdk\upstream\lib\clang\19\include\__stddef_max_align_t.h:24:3: note: previous definition is here
   24 | } max_align_t;
      |   ^
```

**Comment by sbc100** [comment]
Can you share a little more about what is contained in `main.cpp`?  What files are being included in what order?

**Comment by sbc100** [comment]
It looks like maybe you have your own copy of `stddef.h` in the `include` directory which conflicts with emscripten's version.

```
include\stddef.h:437:3: error: typedef redefinition with different types ('struct max_align_t' vs 'struct max_align_t')
  437 | } max_align_t;
```

Any idea why `include\stddef.h` exists or where it comes from?

**Comment by adokhugi** [comment]
Thanks for your answers. I don't include stddef.h directly from main.cpp but there appear some include statements in some of the files that are themselves directly or indirectly included in main.cpp. I'm just puzzled at the error message that says "('struct max_align_t' vs 'struct max_align_t')" because for me these two type definitions are identical and therefore they should not pose a problem.

**Comment by adokhugi** [comment]
Apparently the includes appear in these files:

In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\fstream:182:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__algorithm/max.h:14:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__algorithm/max_element.h:15:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__iterator/iterator_traits.h:14:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__concepts/constructible.h:12:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__concepts/convertible_to.h:13:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__type_traits/is_convertible.h:14:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\__type_traits/is_array.h:14:
In file included from C:\Projects\levasoft\emsdk\upstream\emscripten\cache\sysroot/include/c++/v1\cstddef:43:

So all of these files are files that come along with emscripten, that's why my problem is related to emscripten. It's really strange IMHO and I wonder whether maybe some compiler flags have to be set to solve it.

**Comment by sbc100** [comment]
The error message says that you have a typedef of `max_align_t` in your `include\stddef.h` that is different to emscripten's typedef.

It almost impossible to avoiding including `stddef.h` so that problem is not that its being included but that the *wrong* copy is being include (i.e. the one from your project).

Can you see what the definition on line 437 of your `include\stddef.h` file says?

My advice you would remove that `include\stddef.h` completely, or the remove the `-Iinclude` flag which causes it to be included.

**Comment by adokhugi** [comment]
OK, I noticed that indeed I made copies of the include files, which I have now removed and now I no longer get the error message. Thanks!
