### ISSUE TITLE
how to generated only one file *.js if i use pthread 

### ISSUE THREAD

**Issue by yangfangfang1204** [emscripten-core/emscripten#21627]
https://github.com/emscripten-core/emscripten/issues/9796 

so is there a option that i can use inline webworker when i use pthread, i want to generated only one file *.js.
because one .worker.js and one .js , there is a cors error , failed to construct 'Worker' accessed from origin.

**Comment by kripken** [comment]
There is no way atm to avoid a separate `worker.js` file. In theory maybe SINGLE_FILE could be improve to support that, see https://github.com/emscripten-core/emscripten/issues/17547#issuecomment-2022263978

**Comment by sbc100** [comment]
Lets close this as a duplicate of #17547
