### ISSUE TITLE
Any example to compile a project via emscripten and use it in wasmtime?

### ISSUE THREAD

**Issue by am2222** [emscripten-core/emscripten#21647]
Hi,
So I am able to compile my project to `.wasm` and use it in js without any issues. But have a hard time to loading it in python using wasmtime. I have have enabled `standalone_wasm` but cannot find a way to load it in wasmtime. 
is there any examples I can check to see how to do it?

Thanks!

**Comment by sbc100** [comment]
Even with `-sSTANDALONE_WASM` mode it likely the module is not compatible with wasmtime/WASI due to one or more emscripten-specific imports.   I'm afraid what you are trying to do is likely very hard.

Do you know which imports your module is using?  Can you share them here?

**Comment by am2222** [comment]
Thanks @sbc100 ,
By the imports do you mean the c++ imports? it is a bigger c++ library which I am trying to port it for python.
[Here](https://github.com/am2222/webDggrid/tree/main/lib-wasm) is the repository  I am working on and the binary files are shared there. the source c++ files are also available in that repository. 

May I ask what imports can be problematic?

**Comment by sbc100** [comment]
No C++ stuff should be fine.

The problem will be system calls to things that are not part of the WASI API.   If you any non-standard imports (emscripten uses many) then you would need to somehow implement them in wasmtime.

You can see the imports your binary has by using by running wasm2wat (from wabt) or wasm-dis (from binaryen) or maybe even `llvm-nm`.

You can also look at the generated file and look for `wasmImport` to see which ones emscripten is providing to the Wasm module.

**Comment by am2222** [comment]
Thanks @sbc100 ,

So I used wasm2wat (online version) and here are the imports that are listed at the beginning of the file


``
  (import "env" "_embind_register_class_function" (func $env._embind_register_class_function (type $t52)))
  (import "env" "_embind_register_memory_view" (func $env._embind_register_memory_view (type $t2)))
  (import "env" "_emval_decref" (func $env._emval_decref (type $t0)))
  (import "env" "_emval_take_value" (func $env._emval_take_value (type $t1)))
  (import "env" "_embind_register_integer" (func $env._embind_register_integer (type $t12)))
  (import "env" "_embind_register_function" (func $env._embind_register_function (type $t22)))
  (import "env" "_embind_register_class_constructor" (func $env._embind_register_class_constructor (type $t13)))
  (import "env" "_embind_register_class" (func $env._embind_register_class (type $t56)))
  (import "env" "_embind_register_optional" (func $env._embind_register_optional (type $t4)))
  (import "env" "_emval_run_destructors" (func $env._emval_run_destructors (type $t0)))
  (import "env" "_emval_new_array_from_memory_view" (func $env._emval_new_array_from_memory_view (type $t3)))
  (import "env" "_embind_register_std_wstring" (func $env._embind_register_std_wstring (type $t2)))
  (import "env" "_emval_call_method" (func $env._emval_call_method (type $t41)))
  (import "env" "_emval_get_method_caller" (func $env._emval_get_method_caller (type $t5)))
  (import "env" "_emval_incref" (func $env._emval_incref (type $t0)))
  (import "env" "_emval_as" (func $env._emval_as (type $t42)))
  (import "env" "_emval_get_property" (func $env._emval_get_property (type $t1)))
  (import "env" "_emval_new_cstring" (func $env._emval_new_cstring (type $t3)))
  (import "wasi_snapshot_preview1" "fd_close" (func $wasi_snapshot_preview1.fd_close (type $t3)))
  (import "wasi_snapshot_preview1" "fd_write" (func $wasi_snapshot_preview1.fd_write (type $t7)))
  (import "env" "_embind_register_std_string" (func $env._embind_register_std_string (type $t4)))
  (import "env" "_embind_register_float" (func $env._embind_register_float (type $t2)))
  (import "env" "_embind_register_bigint" (func $env._embind_register_bigint (type $t34)))
  (import "wasi_snapshot_preview1" "environ_get" (func $wasi_snapshot_preview1.environ_get (type $t1)))
  (import "wasi_snapshot_preview1" "environ_sizes_get" (func $wasi_snapshot_preview1.environ_sizes_get (type $t1)))
  (import "wasi_snapshot_preview1" "fd_seek" (func $wasi_snapshot_preview1.fd_seek (type $t69)))
  (import "wasi_snapshot_preview1" "fd_read" (func $wasi_snapshot_preview1.fd_read (type $t7)))
  (import "wasi_snapshot_preview1" "proc_exit" (func $wasi_snapshot_preview1.proc_exit (type $t0)))
  (import "env" "emscripten_notify_memory_growth" (func $env.emscripten_notify_memory_growth (type $t0)))
  (import "env" "_embind_register_emval" (func $env._embind_register_emval (type $t0)))
  (import "env" "_embind_register_bool" (func $env._embind_register_bool (type $t6)))
  (import "env" "_embind_register_void" (func $env._embind_register_void (type $t4)))
``

it seems the only one is `emscripten_notify_memory_growth` which I think I can disable it in the build configuration. Does this make sense?

**Comment by sbc100** [comment]
It should be possible to remove the `emscripten_notify_memory_growth` import.... however it looks like you are using embind here, which is certainly not supported in wasmtime since embind is all about binding to JavaScript.  You would need to remove all your embind usage.

**Comment by am2222** [comment]
@sbc100 thank you!

So I guess all of the Val data type I use should also change, right?

**Comment by sbc100** [comment]
Yes, the `val` data type is for referring to JavaScript objects, and since there is not JavaScript in wasmtime this won't work.

**Comment by am2222** [comment]
Thanks @sbc100 
I was hoping once I compile library with emscripten I can load it in python as well. 
It would be nice to  have a python wrapper like what we have in js.

**Comment by sbc100** [comment]
That sounds reasonable, but such a Wasm program could not use embind/val since that is an API for JavaScript bindings.

The best way to biuld wasmtime compatible programs is to use wasi-sdk, not emscripten.

**Comment by am2222** [comment]
Thanks @sbc100 ! I think I will have a look at the tools you mentioned me!
