### ISSUE TITLE
Make mimalloc headers accessible

### ISSUE THREAD

**Issue by Markus87** [emscripten-core/emscripten#21652]
mimalloc provides a lot of options to change its behaviour: https://microsoft.github.io/mimalloc/group__options.html

The headers of mimalloc are here right now: `./emsdk/upstream/emscripten/system/lib/mimalloc/include`
My understanding is these headers are not meant to be accessed directly, but as a workaround one could of course.

If there is no reason to hide them they should be copied here: `./emsdk/upstream/emscripten/system/include`

**Version of emscripten/emsdk:**
> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.56 (cf90417346b78455089e64eb909d71d091ecc055)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 34ba90745fa55777436a2429a51a3799c83c6d4c)
Target: wasm32-unknown-emscripten
Thread model: posix

**Comment by sbc100** [comment]
I don't see why we wouldn't install the header(s) in the sysroot.   @kripken WDYT?

**Comment by kripken** [comment]
Makes sense to me. The right place, if someone wants to submit a PR, is in `install_system_headers()` in `tools/system_libs.py` if I am not mistaken.
