### ISSUE TITLE
'emcc' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by VeryUniqeName** [emscripten-core/emscripten#21685]
Please include the following in your bug report:

Version of emscripten/emsdk:  i put ./emsdk install latest (april 2nd 2024)

Please include the output `emcc -v` here

 'emcc' is not recognized as an internal or external command,
operable program or batch file.

**Failing command line in full:** 

Microsoft Windows [Version 10.0.22631.3296]
(c) Microsoft Corporation. All rights reserved.

C:\Users\export>cd emsdk

C:\Users\export\emsdk>source emsdk_env.bat
'source' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\export\emsdk>source ./emsdk_env.sh
'source' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\export\emsdk>emsdk_env.bat
Setting up EMSDK environment (suppress these messages with EMSDK_QUIET=1)
Adding directories to PATH:
PATH += C:\Users\export\emsdk

Setting environment variables:
PATH = C:\Users\export\emsdk;C:\Python312\Scripts\;C:\Python312\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\export\AppData\Local\Microsoft\WindowsApps;;C:\Users\export\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\export\AppData\Roaming\npm
EMSDK = C:/Users/export/emsdk
Clearing existing environment variable: EMSDK_PY

C:\Users\export\emsdk>emcc -v
'emcc' is not recognized as an internal or external command,
operable program or batch file.

i just finished the install guid, and everything is installed i followed it to a T,  but now im getting this. (this is my first time compiling code so im sorry if its a stupid mistake)

**Comment by sbc100** [comment]
Did you run `emsdk install latest` and `emsdk activate latest` ?
