### ISSUE TITLE
[wasm-eh] Getting exception stacktraces with pthreads

### ISSUE THREAD

**Issue by ravisumit33** [emscripten-core/emscripten#21702]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.56 (cf90417346b78455089e64eb909d71d091ecc055)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 34ba90745fa55777436a2429a51a3799c83c6d4c)
Target: wasm32-unknown-emscripten
Thread model: posix
```

In single-threaded mode I used to call exported cpp function from js inside a `try..catch`. This enabled me to get thrown`WebAssembly.Exception` from cpp code, if any, inside the catch block. And then I can derive error stacktrace (built with `-sEXCEPTION_STACK_TRACES=1`) if I want.

With multi-threaded builds built with `-sPROXY_TO_PTHREAD`, I no longer have this convenience. I can see the thrown `WebAssembly.Exception` object from `worker.js` in the console. But main js doesn't get the object in its `onWorkerError`. Only gets `Uncaught [object WebAssembly.Exception]` printed as error message from main js in the console. Is there a way of sending the stacktrace (or the whole _WebAssembly.Exception_ object) to the main application thread?

**Comment by sbc100** [comment]
@aheejin ?

I think it might not be possible to serialize the `WebAssembly.Exception` back to the main thread.  I assume it contains all kind of referenced to the tag and maybe even the module instance, in which case that wouldn't be transferable or serializable I think. 

One way to achieve what you want would be to run the try/catch JS code on the worker itself.  To do this would you need to have your thread call out to a JS helper function.   e.g. `doRunWithTryCatch(myCxxFunction)`.  Then `doRunWithTryCatch` would call back into the wasm module and call the `myCxxFunction` but wrap it in a try/catch on the JS.

**Comment by sbc100** [comment]
You could extra any strings you want and send them via `postMessage`, or you could send the strings back into C/C++ code to transfer the information via shared memory.

What are you trying to do with this information on the main thread?

**Comment by ravisumit33** [comment]
This information is logged as error analytics for our app which help us in debugging production crashes. Also, the app-level logic to handle these errors are on main application thread.

Regarding sending extra strings via `postMessage`, if I call `postMessage` from `worker.js` won't it lands on the `worker.onMessage` in the main js file  where these workers are created? Is there a way to get the desired data from that `onMessage`?

**Comment by aheejin** [comment]
I'm not very familiar with how these things work myself, but I got a similar question before and tried to come up with something in #19113, which ended up working for a certain case but not for others, so I closed it. Does the approach in that PR possibly help in your case?

**Comment by ravisumit33** [comment]
@sbc100 @aheejin 
Approach of calling out a JS helper function `doRunWithTryCatch(myCxxFunction)` from the thread works well. I have added following in my `pre-js`
```js
self.doRunWithTryCatch = (paramsToSend) => {
  try {
    Module._myCxxFunction(paramsToSend);
  } catch (err) {
    Module._sendErrDetailsToMainThread(err.message, err.stack);
  }
};
```

The only issue I can see here is the calling of `sendErrDetailsToMainThread` function defined in _cpp_ which internally call `MAIN_THREAD_EM_ASM` to send error details to main thread. Can it be not done on js side itself without calling into _cpp_ again?

**Comment by sbc100** [comment]
> @sbc100 @aheejin Approach of calling out a JS helper function `doRunWithTryCatch(myCxxFunction)` from the thread works well. I have added following in my `pre-js`
> 
> ```js
> self.doRunWithTryCatch = (paramsToSend) => {
>   try {
>     Module._myCxxFunction(paramsToSend);
>   } catch (err) {
>     Module._sendErrDetailsToMainThread(err.message, err.stack);
>   }
> };
> ```
> 
> The only issue I can see here is the calling of `sendErrDetailsToMainThread` function defined in _cpp_ which internally call `MAIN_THREAD_EM_ASM` to send error details to main thread. Can it not be done on js side itself without calling into _cpp_ again?

There are a basically two different ways of communicating with the main thread: postMessage or shared memory.

If you using shared memory to communicate the message back the main thread its normally much simpler to do that from C++ which deal with reading/writing shared memory is much more natural.   However, the downside is that after an exception has occurred the state of shared memory is in an undefined state so you could run into issues where one crash lead to anther (e.g. if the heap or stack are corrupted by the crash).    Technically this could also occur on the JS side, but its less likely.  i.e. is possible that a program crash could corrupt arbitrary thing on the JS side, so even calling `postMessage` is not guaranteed to work.

Another downside of doing this stuff in C++ is that the crash might occur while a lock is being held, and the main thread might try to the acquire that lock at a later time, causing a deadlock.   For example musl has locks around its file streams, so if the crash happens while writing to a file handle, then that lock will forever be held by the crashed thread and any other thread trying to write to that handle will deadlock.  Basically error recovery, or even error reporting, from crashes/traps is not going ever be 100% reliable. 

If you want to use postMessage to communicate the information back to the main thread that would require you to install your on `onmessage` handler on each of the pthread workers.  IIRC you can do this using `worker.addEventListener('message')` but it will involve interacting with the internals of the pthread library.   IIUC you would need to use `event.stopImmediatePropagation()` when you receive the custom message to prevent the emscripten event handler from seeing it.

**Comment by ravisumit33** [comment]
I definitely do not want to involve in interacting with the pthread internals. If there was a way I could add that without fiddling with internal structure (e.g. a hook on `Module` object), I may have looked into that but otherwise I am better with my current approach.

Regarding your points on calling via c++, the cpp function `sendErrDetailsToMainThread` just send the recieved data to main thread using `MAIN_THREAD_EM_ASM` (which I believe use shared memory internally). This is done when other app logic has completed so I think case of deadlock is very less likely and crash probability will be the same as crashing of `MAIN_THREAD_EM_ASM`. So I think current approach is better and fulfills my use case.

Thanks a lot for your suggestions.
