### ISSUE TITLE
Include `alext.h` header for AL

### ISSUE THREAD

**Issue by gabeklavans** [emscripten-core/emscripten#21723]
The [docs claim support for some OpenAL extensions](https://emscripten.org/docs/porting/Audio.html#supported-openal-extensions), however I was a bit confused to find the `alext.h` missing when trying to utilize the `ALC_HRTF_SOFT` extension. Based on [this test](https://github.com/emscripten-core/emscripten/blob/main/test/openal_playback.cpp#L123), it looks as if the define value must be used directly in order to use the extension, which is a little difficult to figure out, to me.

Is there a reason to not add the `alext.h` file found in the [openal-soft include folder](https://github.com/kcat/openal-soft/blob/master/include/AL/alext.h) to the "emscripten/system/include/AL" folder? I believe this would also alleviate issues like #9851 and would render #9852 obsolete.

As of writing I see that the discussion in #9852 suggests doing exactly this, but I figured I'd make this issue just to make the potential solution even clearer for anyone willing to revive the effort to remedy this (I may do so myself, if I find the time)

**Comment by sbc100** [comment]
Sounds like it would be a good idea to add that header.   It may also take some implementation work to make those extensions work.  Would you be interesting in working on this and sending a PR?

**Comment by gabeklavans** [comment]
Yeah I'm definitely interested in making a PR to bring in the header

> It may also take some implementation work to make those extensions work.

By "those" do you mean the ones currently supported by emscripten? Or all the extensions available in the header (that would be possible to implement in emscripten)?

**Comment by sbc100** [comment]
I would imagine that the extensions could be probed for at runtime?  So you wouldn't need to make them all work, just the ones that we report as working.  having said that I know almost nothing about this API so that it might not work that way :)

**Comment by gabeklavans** [comment]
> I would imagine that the extensions could be probed for at runtime?

Yes, openal-soft provides a function to check if an extension is available at runtime. However, I also don't know how it works haha. I'll look into to it when I start on the PR
