### ISSUE TITLE
WebGPU new Surface API

### ISSUE THREAD

**Issue by Olle-Lukowski** [emscripten-core/emscripten#21745]
So, ever since https://github.com/webgpu-native/webgpu-headers/pull/203, the SwapChain API was merged with the Surface API. I want to use WebGPU for my project and was wondering if anyone is working on making emscripten compatible with the new `webgpu.h`? If not, I could try to help out, even though I haven't contributed before.

**Comment by kainino0x** [comment]
No one is working on it right now. Contribution would be welcome - I'm happy to give pointers (you can also find me on Matrix chat `@kainino:matrix.org`).

Dawn recently implemented the surface API so we're definitely ready to catch Emscripten up to be compatible.

**Comment by beaufortfrancois** [comment]
@kainino0x Can you share pointers as I'm also working on updating our cross-platform app to use the new surface API. Right now, it works only with native, not emscripten. See https://github.com/beaufortfrancois/webgpu-cross-platform-app/pull/7

I'd be happy to help on that front.

**Comment by beaufortfrancois** [comment]
@eliemichel FYI
