### ISSUE TITLE
Please set EMSCRIPTEN as an INTERNAL variable in the Emscripten.cmake toolchain file

### ISSUE THREAD

**Issue by starball5** [emscripten-core/emscripten#21753]
**Version of emscripten/emsdk:**
3.1.57

I don't see why I should ever feel the need to touch this variable. If you agree, please set it as [`INTERNAL`](https://cmake.org/cmake/help/latest/command/set.html).

`EMSCRIPTEN_FORCE_COMPILERS` and `EMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES` are just fine as non-internal cache variables since they're actually options.

**Comment by sbc100** [comment]
Seems reasonable to me.  Would you have time to create a PR?
