### ISSUE TITLE
Support omitting optional arguments in js embind bindings

### ISSUE THREAD

**Issue by synoet** [emscripten-core/emscripten#21776]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.55 (165133b1cc977f0b9a277e42ef809b823157189c)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 6c7805d5d186a6d1263f90b8033ad85e2d2633d7)
Target: wasm32-unknown-emscripten
Thread model: posix
```
**Issue**
When using optional arguments with embind, it would be more intuitive and convenient to allow omitting the optional arguments entirely, rather than requiring passing undefined for the optional parameters.

```cpp
inline std::string testOptional(std::string str, std::optional<std::string> optionalString)
{
}

EMSCRIPTEN_BINDINGS(test)
{
    register_optional<std::string>();
    function("test", &testOptional);
}
```
I would expect the generated JavaScript bindings to allow calling the function like this:

```javascript
testOptional("someString")
```
Instead of requiring the following:
```javascript
testOptional("someString", undefined)
```

I noticed a comment on the original optional implementation pull request ([#21076](https://github.com/emscripten-core/emscripten/pull/21076/files#r1454072957)) mentioning plans to support this feature.

**Comment by synoet** [comment]
Thanks!

**Comment by i-saint** [comment]
Has anyone confirmed that it works as expected?
It seems that the trailing `undefined` is still required on latest SDK (3.1.64).

**Comment by brendandahl** [comment]
There are tests testing this, so if you're having issues please file a new issue with STR.

**Comment by i-saint** [comment]
(Thanks for prompt reply)
I continued to dig into this issue. but it seems trailing `undefined` cannot be omitted in any case (at least in JavaScript. I have not tested this in TypeScript). I have submitted a new issue #22389
