### ISSUE TITLE
In `v3.1.58`, why pthreads don't inherit the `moduleArg`?

### ISSUE THREAD

**Issue by DenizUgur** [emscripten-core/emscripten#21826]
I'm not sure if this was an oversight but with the latest version, pthreads don't use the same `moduleArg` that was given to the main module. I'm relying on this argument to supply hashed version of my wasm file. Is there any other suggested way to achieve this?

https://github.com/emscripten-core/emscripten/blob/e5f1e343f827b477058e462e840b00b53478c1a8/tools/link.py#L2458

**Comment by sbc100** [comment]
Can you share more details of your use case?  In particular I'm not sure how the `moduleArg` would be transmitted to the worker.  

How were you populating the `moduleArg`?  Do you know how it was visible to the workers?

**Comment by sbc100** [comment]
`mainScriptUrlOrBlob` should still be supported.    See: https://github.com/emscripten-core/emscripten/blob/7c31c12cfc03f1130a63e379f6858f82e4337ca8/src/library_pthread.js#L458-L466

So there must be some way this usage is different and not working for your use case.   Hopefully we can figure it and add a test for that technique.

**Comment by DenizUgur** [comment]
What would be the suggested way of setting wasm binary name during runtime? Also how do you enable `mainScriptUrlOrBlob` because I don't see it in my build output.

**Comment by DenizUgur** [comment]
I think I'll use a combination of `sessionStorage` and `locateFile`. Not sure what would be the most elegant way to do this natively with Emscripten but if you believe this is a valid use-case then I think it's worth looking into.

**Comment by sbc100** [comment]
Pthreads don't need to locate the wasm file because they all get the wasm module delivered via postMessage on startup.  i.e. the module is shared from the main thread.

`mainScriptUrlOrBlob` tells the system is used to the control the name/content for the main JavaScript script itself.

If `mainScriptUrlOrBlob` is not showing up in your output it could be you are overriding `INCOMING_MODULE_JS_API`?  Or maybe you are using `-sSTRICT` with makes `INCOMING_MODULE_JS_API` empty by default?

**Comment by sbc100** [comment]
I don't understand this comment: https://github.com/ffmpegwasm/ffmpeg.wasm/blob/ae1cdac7db79c5315f9a1b716fcbd9bcfe27c902/src/bind/ffmpeg/bind.js#L93-L96,  It seems to suggest that each worker needs to locate the wasm file.. but IIUC workers have always recieved the wasm module via postMessage so have never needed to know its location.

**Comment by DenizUgur** [comment]
Well that may be the case, but for me I can confirm that it tries to locate the file twice (verified via good old `console.log`). Second one returns empty because the variable I've set in the main module is lost on the second instance.

For reference here is my link flags:

```
-O2 -sMODULARIZE=1 -sEXPORT_ES6=1 -sEXPORT_NAME=foo -sEXPORTED_FUNCTIONS=_free,_malloc,_main -sENVIRONMENT=web,worker -sEXPORTED_RUNTIME_METHODS=FS,OPFS,getValue,setValue,UTF8ToString,lengthBytesUTF8,stringToUTF8,cwrap,addFunction,PThread -sPTHREAD_POOL_SIZE=1 -sPTHREAD_POOL_SIZE_STRICT=0 -lopfs.js -sWASMFS -sFORCE_FILESYSTEM
```

I've also tried to set `INCOMING_MODULE_JS_API` to `mainScriptUrlOrBlob` but that didn't produced `mainScriptUrlOrBlob` either.

**Comment by sbc100** [comment]
Can you elaborate on "it tries to locate the file twice"?  Which file and what is function are where is the it trying to be located from?

Also when you say "the variable I've set in the main module", which variable exactly are you talking about and how exactly do you set it?

When you say "it didn't produced mainScriptUrlOrBlob" is that string not seen at all in your output JS file?

I certainly see it when I build a simple moulde:

```
$ emcc test/hello_world.c -pthread
$ grep mainScriptUrlOrBlob a.out.js 
        // call URL.createObjectURL on the mainScriptUrlOrBlob.
        if (Module['mainScriptUrlOrBlob']) {
          pthreadMainJs = Module['mainScriptUrlOrBlob'];
```

**Comment by sbc100** [comment]
Oh wait.. I think its because you are using `EXPORT_ES6`.  In that scenario it should not necessary to use  mainScriptUrlOrBlob since the main script can always be located via `import.meta.url`.   I wonder why that is not working in your case?

**Comment by DenizUgur** [comment]
> Can you elaborate on "it tries to locate the file twice"? Which file and what is function are where is the it trying to be located from?

I've put a `console.trace("load")` before this line and the second trace shows that the pthread is accessing this line. In this instance, I haven't supplied a `locateFile` function in my `--pre-js`. 

https://github.com/emscripten-core/emscripten/blob/7c31c12cfc03f1130a63e379f6858f82e4337ca8/src/preamble.js#L617

> Also when you say "the variable I've set in the main module", which variable exactly are you talking about and how exactly do you set it?

Similiar to how ffmpeg.wasm was supplying `mainScriptUrlOrBlob`, I've defined a new variable defined in my `--pre-js` called `hashedWasmBinaryFile`. When I call my emscripten module load function, I supplied this variable to where `moduleArg` supposed to be.

It works okay for the main module but whenever pthread creates the instance again that variable is lost because it didn't supplied that variable. That's expected because it doesn't know what to set that variable to. The ffmpeg.wasm solution uses the hash portion of `mainScriptUrlOrBlob` to create an artifical state across threads to mitigate this.

> When you say "it didn't produced mainScriptUrlOrBlob" is that string not seen at all in your output JS file?

Yes, it's not there. I've used `-sINCOMING_MODULE_JS_API=mainScriptUrlOrBlob`

> the main script can always be located via `import.meta.url`

Correct, but wasm file is hardcoded during build so there is no way to infer the wasm file name if it changes during bundling. That wouldn't be an issue with the main script as it's loaded from the application script anyway.

**Comment by sbc100** [comment]
So IIUC `mainScriptUrlOrBlob` has always been about locating the main JavaScript file, and never about locating the wasm file (which can be controled via adding a custom `locateFile`).   So I'm a little confused about why your use case (or the ffmpeg one) even use `mainScriptUrlOrBlob`.

Also IIUC `locateFile` should only be used to find the wasm file exactly once, one the main thread, and never on worker threads (I will double check that now since it seems you are seeing otherwise).

Is there any chance you should share your completely setup?  i.e. is your project open source?

**Comment by sbc100** [comment]
> I've put a `console.trace("load")` before this line and the second trace shows that the pthread is accessing this line.

While its true that `wasmBinaryFile` might be calculated on by worker when it loads the main script, that value of it should never be used since pthreads override the nomral module loading process by overriding `instantiateWasm`.   By using this override they bypass all of the module creation code and instead use the module they receive via postMessage from the main thread.

**Comment by DenizUgur** [comment]
The project itself is not open-source but I'm using https://github.com/gpac/gpac as the wasm binary. Use the same link flags I gave above (edit [here](https://github.com/gpac/gpac/blob/205bfe3196764b61b19b63494a2b4708ac774b71/applications/gpac/Makefile#L32)) and configure using `./configure --emscripten`. Please note that the upstream requires some patches to support `EXPORT_ES6` so demo page you see [here](https://github.com/gpac/gpac/blob/master/share/emscripten/gpac.html) will not work.

**Comment by DenizUgur** [comment]
> While its true that wasmBinaryFile might be calculated on by worker when it loads the main script, that value of it should never be used since pthreads override the nomral module loading process by overriding instantiateWasm. By using this override they bypass all of the module creation code and instead use the module they receive via postMessage from the main thread.

Oh wait... that's where I went wrong. I assumed since `locateFile` is being called it should be properly populated. I'll add a check with `ENVIRONMENT_IS_PTHREAD` to fix this.

I tried it and it works like a charm. If I only haven't been so defensive in my implementation I would've probably gotten away :)

For future readers, to override the default wasm file path you can use the following `locateFile` override:

```js
function _locateFile(path, prefix) {
  const hashedWasmBinaryFile = Module["hashedWasmBinaryFile"];
  if (hashedWasmBinaryFile && path.endsWith(".wasm")) {
    return hashedWasmBinaryFile;
  }
  return prefix + path;
}
```

**Comment by DenizUgur** [comment]
Thank you @sbc100 for your insight and sorry to bother you with such a simple overisight.

**Comment by sbc100** [comment]
Thats great to hear!   

Can you explain the fix a little more?   It sounds like the fact that locateFile was being called from a pthread was causing the issue?   Perhaps we should try to avoid that completely.

**Comment by DenizUgur** [comment]
> It sounds like the fact that locateFile was being called from a pthread was causing the issue?

That's exactly what was going on. Seems like the PR you opened would prevent the issue I've faced yesterday.
