### ISSUE TITLE
pthread initialization for 40 pthreads takes 5.8seconds because of 40 separate network roundtrips..

### ISSUE THREAD

**Issue by terop2** [emscripten-core/emscripten#21833]
We expect pthreads initialization to fast, but currently it causes 5.8s delay to startup of our web page. Reason is that each pthread initialization requires separate network wide roundtrip. It would be better if the task would be done in 1 roundtrip for all 40 pthreads instead of 40 separate roundtrips executed sequentially that take HUGE amount of time.

The issue is completely invisibile on local machine. Need to have far distance machine available for debugging.

=> this feature makes pthreads completely unusable for our 3d engine.

**Comment by terop2** [comment]
![pthread_init](https://github.com/emscripten-core/emscripten/assets/18078535/6e03c130-d0a9-4b4a-a3ad-aac9748fdd49)

See this picture of pthread_init taking huge amount of time for 40 separate pthreads.

**Comment by terop2** [comment]
pthreads taking this long time to initialize is completely unacceptable for a feature that saves only a little time further down the road.

**Comment by sbc100** [comment]
Do you know which resource is being repeatedly fetched?  Each worker does need to load the `.js` file.. but its always the same one so the browser should cache it. 

I'm afraid I can't read anything in the picture you attached.. what is the pre-thread resource being fetched?

Can you try with version 3.1.58 that was recently released, it reduces the number of resources used per thread (although the overall amount of data needed is about the same).

Multi-threading is more expensive on the web than on native platforms due the current limitations of the platform so it unlikely we can get pthread start time close the native speed.  However, I hope we can improve on where we are today.

**Comment by terop2** [comment]
that resource is the web_page_highmem_worker.js file. i.e. it's emscripten's pthread system that causes the sequential delay.

**Comment by terop2** [comment]
(it's possible we're using "no cache" flag enabled when we did the perf measurements, since that's the default in the network tab)

**Comment by sbc100** [comment]
The good news is that we eliminated that `.worker.js` file completely in 3.1.58.. that file as fairly small though so I'm not sure it will have too much of an effect on the overall code size

**Comment by terop2** [comment]
oh, I need to try the new versions if they work. I'm currently in 3.1.30 since the newer version had significant regression, but will need to try the new versions...

**Comment by terop2** [comment]
got newest version of emscripten to work. Figured out that "static int foobar444=0;" to the top of the file will fix the top level entity problem in draco library. newer version looks otherwise ok, but debug console window dragging will give errors...

**Comment by terop2** [comment]
thanks, this looks like its been solved already in newest emscripten... => proposing to close the issue

**Comment by kripken** [comment]
Great, closing.
