### ISSUE TITLE
Unity webgl build error: [parse exception: attempted pop from empty stack / beyond block start boundary]

### ISSUE THREAD

**Issue by meta-winster** [emscripten-core/emscripten#21895]
**Version of emscripten/emsdk:**

Emscripten 3.1.8
Unity 2022.3.27f1
Mujoco 3.1.1

**What I'm trying to do**

I'm trying to build mujoco (a native c++ physics library) into a Unity WebGL build. Fortunately, mujoco comes with a Unity plugin; however, the package relies on a DLL, which cannot be used in web builds. To get around this, I've tried pre-compiling the mujoco library from source via emscripten into static library .a files, which is what the Unity docs recommend (https://docs.unity3d.com/Manual/webgl-native-plugins-with-emscripten.html). I made sure to use the correct emscripten version as well. I place the .a files into my plugins folder under assets, and mujoco has a bindings script that links itself to the .a files. In theory, this should be buildable for WebGL.

**The error**

Here's the error I get after the WebGL build fails:

```Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
wasm-ld: warning: function signature mismatch: mjv_averageCamera
>>> defined as (i32, i32) -> i32 in C:/Users/winster/projects/MujocoNewEmsdk/Library/Bee/artifacts/WebGL/il2cppOutput/build/GameAssembly.a(09gffyudb6z8.o)
>>> defined as (i32, i32, i32) -> void in Assets/Plugins/build2/lib/libmujoco.a(engine_vis_interact.c.o)
 
wasm-ld: warning: function signature mismatch: mjr_maxViewport
>>> defined as (i32) -> i32 in C:/Users/winster/projects/MujocoNewEmsdk/Library/Bee/artifacts/WebGL/il2cppOutput/build/GameAssembly.a(09gffyudb6z8.o)
>>> defined as (i32, i32) -> void in Assets/Plugins/build2/lib/libmujoco.a(render_gl2.c.o)
 
wasm-ld: warning: function signature mismatch: mjui_themeColor
>>> defined as (i32) -> i32 in C:/Users/winster/projects/MujocoNewEmsdk/Library/Bee/artifacts/WebGL/il2cppOutput/build/GameAssembly.a(09gffyudb6z8.o)
>>> defined as (i32, i32) -> void in Assets/Plugins/build2/lib/libmujoco.a(ui_main.c.o)
[parse exception: attempted pop from empty stack / beyond block start boundary at 8986318 (at 0:8986318)]
Fatal: error in parsing input
emcc: error: '"C:/Program Files/Unity/Hub/Editor/2022.3.27f1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/binaryen\bin\wasm-emscripten-finalize" -g Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.wasm -o Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.wasm --detect-features' failed (returned 1)
```

**Notes**

The signature mismatches are strange -- I've triple checked that there are not multiple versions of the same function defined in the library. I successfully made the warnings go away by removing the functions from the bindings, but the parse exception stays. 

Mujoco has been successfully compiled for the web with emscripten (see [mujoco wasm](https://github.com/zalo/mujoco_wasm)), and I followed their instructions for compiling mujoco from source. However, the emscripten compiler in Unity for some reason is encountering this error.

Happy to add any more information that's needed, or to help reproduce.

**Comment by sbc100** [comment]
Regarding the signature mismatches, it looks like those two libraries have different ideas about the signature of `mjv_averageCamera`?  What is the correct signature?  i.e. Does it return void (as `ui_main.c.o` thinks?) or should it return non-void (GameAssembly.a) thinks?

Regarding the binaryen parse error that looks more serious.   Could you perhaps attach the problematic wasm file (`Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.wasm`)?

**Comment by meta-winster** [comment]
Thanks so much for your help!!

I've attached here the problematic wasm file from Unity.

Re: versioning, yes, I'm using the [same version to compile](https://docs.unity3d.com/2023.2/Documentation/Manual/webgl-native-plugins-with-emscripten.html) the source as Unity -- Emscripten 3.1.8. 

Re: the signature mismatch, the correct signature of `mjv_averageCamera` is what GameAssembly.a thinks -- it should return i32. I think the GameAssembly.a is the C# binding definition of `mjv_averageCamera` while the `ui_main.c.o` is the mujoco pre-compiled version. However, looking at the source `ui_main.c.o`, the signatures match **before they are compiled**.

[build.zip](https://github.com/emscripten-core/emscripten/files/15225466/build.zip)

**Comment by sbc100** [comment]
Looking at `engine_vis_interact.c` it looks like it is returning a struct by value:
https://github.com/google-deepmind/mujoco/blob/3e35eebbb9480709638011861dc3df8bf09f0f62/src/engine/engine_vis_interact.c#L699

This struct is fairly large: 
https://github.com/google-deepmind/mujoco/blob/3e35eebbb9480709638011861dc3df8bf09f0f62/include/mujoco/mjvisualize.h#L201-L215

The C ABI for webassembly means that this return value is actually passed in by the caller as an additional third argument.  So the caller allocates the struct and then passes a pointer to is as the final argument.    So I suspect that `GameAssembly.a` is somehow not aware of this ABI or doesn't know that correct size of the struct?

**Comment by sbc100** [comment]
See https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md#function-arguments-and-return-values

**Comment by meta-winster** [comment]
You're totally right, it is a struct.

Though the two seem to match from what I can tell (see below). And other functions in the plugin are returning structs, but don't seem to flag the same warning.

Are there any additional debugging steps I can take on the binaryen parse error?

**From the bindings:**

First is the function import and definition:
```[DllImport("__Internal")]
public static unsafe extern mjvGLCamera_* mjv_averageCamera(mjvGLCamera_* cam1, mjvGLCamera_* cam2);
```
but it also defines the struct:
```
[StructLayout(LayoutKind.Sequential)]
public unsafe struct mjvGLCamera_ {
  public fixed float pos[3];
  public fixed float forward[3];
  public fixed float up[3];
  public float frustum_center;
  public float frustum_width;
  public float frustum_bottom;
  public float frustum_top;
  public float frustum_near;
  public float frustum_far;
}
```

**From the source:**

```// return the average of two OpenGL cameras
mjvGLCamera mjv_averageCamera(const mjvGLCamera* cam1, const mjvGLCamera* cam2) {
  mjtNum pos[3], forward[3], up[3], projection, tmp1[3], tmp2[3];
  mjvGLCamera cam;

  // compute pos
  mju_f2n(tmp1, cam1->pos, 3);
  mju_f2n(tmp2, cam2->pos, 3);
  mju_add3(pos, tmp1, tmp2);
  mju_scl3(pos, pos, 0.5);

  // compute forward
  mju_f2n(tmp1, cam1->forward, 3);
  mju_f2n(tmp2, cam2->forward, 3);
  mju_add3(forward, tmp1, tmp2);
  mju_normalize3(forward);

  // compute up, make it orthogonal to forward
  mju_f2n(tmp1, cam1->up, 3);
  mju_f2n(tmp2, cam2->up, 3);
  mju_add3(up, tmp1, tmp2);
  projection = mju_dot3(up, forward);
  mju_addToScl3(up, forward, -projection);
  mju_normalize3(up);

  // assign 3d quantities
  mju_n2f(cam.pos, pos, 3);
  mju_n2f(cam.forward, forward, 3);
  mju_n2f(cam.up, up, 3);

  // average frustum
  cam.frustum_bottom = 0.5f * (cam1->frustum_bottom + cam2->frustum_bottom);
  cam.frustum_top    = 0.5f * (cam1->frustum_top + cam2->frustum_top);
  cam.frustum_center = 0.5f * (cam1->frustum_center + cam2->frustum_center);
  cam.frustum_width  = 0.5f * (cam1->frustum_width + cam2->frustum_width);
  cam.frustum_near   = 0.5f * (cam1->frustum_near + cam2->frustum_near);
  cam.frustum_far    = 0.5f * (cam1->frustum_far + cam2->frustum_far);

  return cam;
}
```
and its struct:
```struct mjvGLCamera_ {             // OpenGL camera
  // camera frame
  float    pos[3];                // position
  float    forward[3];            // forward direction
  float    up[3];                 // up direction

  // camera projection
  float    frustum_center;        // hor. center (left,right set to match aspect)
  float    frustum_width;         // width (not used for rendering)
  float    frustum_bottom;        // bottom
  float    frustum_top;           // top
  float    frustum_near;          // near
  float    frustum_far;           // far
};
typedef struct mjvGLCamera_ mjvGLCamera;```

**Comment by sbc100** [comment]
> You're totally right, it is a struct.
> 
> Though the two seem to match from what I can tell (see below). And other functions in the plugin are returning structs, but don't seem to flag the same warning.
> 
> Are there any additional debugging steps I can take on the binaryen parse error?

I imagine that binaryen error is simply because of the function being called with the wrong number of args.  In other words, if you fix the struct issue it should also fix the binaryen issue.
  
> 
> **From the bindings:**
> 
> First is the function import and definition:
> 
> ```
> public static unsafe extern mjvGLCamera_* mjv_averageCamera(mjvGLCamera_* cam1, mjvGLCamera_* cam2);
> ```
> 

That function definition is wrong though.. since it claims to be returning a pointer,... but the function in quesiton doesn't return a pointer it returns a struct by value.. which is different.  So this line is wrong I think.

**Comment by meta-winster** [comment]
That worked! For anyone else who comes across this, below are the functions in `MjBindings.cs` that I had to edit the return types of:

```mjv_averageCamera
mjui_themeSpacing
mjui_themeColor
mjr_maxViewport
```

For some reason the bindings have them returning a pointer to a struct instead of the struct by value. Removing the pointer solved the issue.
