### ISSUE TITLE
emcc/wasm-ld fails autoconf sanity check

### ISSUE THREAD

**Issue by Hex4dec** [emscripten-core/emscripten#21961]
`emcc` is failing autoconf (OpenJDK flavored toolchain)'s CC sanity check. I would try to figure out how to fix this, but I'm not going through the multithousand-lined `toolchain.m4` file.

Note that I've already removed the version check, since all of autoconf's version checks fail: `--version`, `-V`, and `-qversion` with no input files.

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.59 (0e4c5994eb5b8defd38367a416d0703fd506ad81)
clang version 19.0.0git (https:/github.com/llvm/llvm-project df762a1643bb5b0b3c907611d118c82d4b68a39d)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: .../emsdk/upstream/bin
```

**Failing command line in full:**
`.../emsdk/upstream/emscripten/emcc -m64    -m64   conftest.c -sUSE_GLFW=3 >&5`

**Autoconf logs:**
```
configure:74925: checking whether the C compiler works
configure:74947: .../emsdk/upstream/emscripten/emcc -m64    -m64   conftest.c -sUSE_GLFW=3 >&5
... (cache logging)
wasm-ld: error: /tmp/emscripten_temp_nyjcrln9/conftest_0.o: must specify -mwasm64 to process wasm64 object files
emcc: error: '.../emsdk/upstream/bin/wasm-ld -o a.wasm -L.../emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /tmp/emscripten_temp_nyjcrln9/conftest_0.o -lGL-getprocaddr -lal -lhtml5 -lstubs-debug -lc-debug -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-debug-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpd_p7trldlibemscripten_js_symbols.so --strip-debug --export=emscripten_stack_get_end --export=emscripten_stack_get_free --export=emscripten_stack_get_base --export=emscripten_stack_get_current --export=emscripten_stack_init --export=_emscripten_stack_alloc --export=__get_temp_ret --export=__set_temp_ret --export=__funcs_on_exit --export=__wasm_call_ctors --export=_emscripten_stack_restore --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=main --export-if-defined=__main_argc_argv --export-if-defined=fflush --export-table -z stack-size=65536 --no-growable-memory --initial-heap=16777216 --no-entry --stack-first --table-base=1' failed (returned 1)
... (celebrating how well the C compiler worked)
configure:74996: error: C compiler cannot create executables
```

**Test program used:**
```c
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "openjdk"
| #define PACKAGE_STRING "OpenJDK openjdk"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.java.net"
| #define PACKAGE_URL "http://openjdk.java.net"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
```

**Comment by Hex4dec** [comment]
Adding `-sMEMORY64` with `--with-extra-cflags` somewhat worked. Now it's yelling at me about `bits/c++config.h` not existing.

**Comment by Hex4dec** [comment]
I got farther by unsetting `CPLUS_INCLUDE_PATH`, seems like my system does funny things with that.

Now, it's complaining with `configure: error: cannot run C compiled programs. If you meant to cross compile, use '--host'.`. Putting `--host wasm32-unknown-emscripten` in the configure command yields `checking host system type... Invalid configuration 'wasm32-unknown-emscripten': system 'emscripten' not recognized`

**Comment by Hex4dec** [comment]
I fixed it by replacing my previous `--host` with `--host=x86_64-unknown-linux-gnu`. With this I feel like I've gotten to a point I'm comfortable with leaving this issue at (missing X11 headers). This has been a journey!

**Comment by CaglaNurYuva** [comment]
I also have the same issue recently. Did you manage to configure openjdk with emcc? If you did, could you please write all flags you use while configuring openjdk?

**Comment by Hex4dec** [comment]
Farthest I've gotten is:

```sh
unset C_INCLUDE_PATH
unset CPLUS_INCLUDE_PATH

CFLAGS="-sMEMORY64 -sSIDE_MODULE -sUSE_FREETYPE=1"
export SSL_CERT_DIR="/etc/ssl/certs/"

cd src

emconfigure ./configure --with-tools-dir=/home/pjals/Development/Clones/emscripten-guix/emsdk/upstream/emscripten \
        --with-extra-cflags="$CFLAGS" --with-extra-cxxflags="$CFLAGS" \
        --host=x86-unknown-linux-gnu --enable-headless-only \
        --with-cups-include="/usr/include" --with-fontconfig-include="/usr/include" --with=freetype=include="../emsdk/upstream/emscripten/cache/ports/freetype/FreeType-version_1/include/"

emmake make all
```

**Comment by CaglaNurYuva** [comment]
Thank you.  How did you test whether your configuration with emscripten is successful or not? How did you use openjdk after configuring it like this?

**Comment by Hex4dec** [comment]
I set the shopt to stop execution when anything doesn't have an exit code of 0. Then I can use my eyes.

**Comment by CaglaNurYuva** [comment]
I was trying to ask how you used openjdk after configuring it with emscripten. Did you use it in any project? If you did, can you describe what kind of project was that? What was the role of openjdk in this project?

The thing is, I sent an email to build-dev mailing list of openjdk to ask if openjdk supports emscripten or not. Here is the conversation:

+ Does OpenJDK configure file has support for emscripten toolchain? If it is not, how can I add this support to openJDK? I would like to hear your suggestions.
- Short answer is that there is no support for emscripten yet. It's an interesting idea, but it's almost a PhD-level research project. In addition, HotSpot is a virtual machine, and so is JavaScript. There are some projects aimed at Java to WebAssembly. Googling "java to WebAssembly" will find them.

+ I really want to give it a try. Can I accomplish this by only modifying .m4 files and [configure.ac](http://configure.ac/) file? 
- No.

+ Are there any other things to do other than these?
- Yes, many things. In particular, OpenJDK is not just written in C++, but a lot of assembly language. OpenJDK also needs real threads, which ECMAScript does not support. And that's just for starters.

**Comment by Hex4dec** [comment]
Oh, I didn't get anywhere with the project. I gave up and moved onto other things.

**Comment by CaglaNurYuva** [comment]
Thanks a lot for your replies and help. I wish you luck with your projects :) I will be checking on them once in a while :)
