### ISSUE TITLE
`alignof(long double) == 8` even though `sizeof(long double) == 16`—why?

### ISSUE THREAD

**Issue by jonathanmarvens** [emscripten-core/emscripten#21977]
I was going to report a bug, but [upon further investigation](https://github.com/WebAssembly/tool-conventions/blob/5b40a861b04716c9bbfe4b94489ef78a335ced6f/BasicCABI.md?plain=1#L58), this seems deliberate. Has the rationale for this discrepancy been documented anywhere?

Thank you!

**Comment by sbc100** [comment]
See #14599 and #10072

**Comment by jonathanmarvens** [comment]
@sbc100 Sorry about that! When I searched the existing issues/PR’s earlier, I didn’t see those (I forgot what I specifically searched for).

Anyway, I understand the rationale now. I’m going to close this issue. Thank you!
