### ISSUE TITLE
isinf() can return -1

### ISSUE THREAD

**Issue by stsp** [emscripten-core/emscripten#22004]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.60 (42a6ea2052f19f70d7d994e8c324bcad2f1f8939)

isinf() is documented as:
```
       isinf(x)      returns 1 if x is positive infinity, and -1 if x is nega‐tive infinity.
```

But when compiling with emcc, I am getting
the warning that the comparison to -1 is always
false.

**Comment by sbc100** [comment]
It looks like the musl implementation of `isinf` only returns a bool:

https://github.com/bminor/musl/blob/007997299248b8682dcbb73595c53dfe86071c83/include/math.h#L73-L76

I'm not sure if this is an upstream musl issue or just an implementation detail and warning you can/should ignore?

**Comment by sbc100** [comment]
Looking at the C standard it looks like this macro just return non-zero for both positive and negative infinity: https://en.cppreference.com/w/c/numeric/math/isinf.   The ability to distinguish between the positive and negative infinity must be a GNU extension.

**Comment by sbc100** [comment]
From the man page it looks like glibc used to do this too:

```
HISTORY
       POSIX.1-2001, C99.

       In  glibc 2.01 and earlier, isinf() returns a nonzero value (actually: 1) if x is positive in‐
       finity or negative infinity.  (This is all that C99 requires.)

```

**Comment by stsp** [comment]
Thanks for info.
In this case this can probably be closed.
