### ISSUE TITLE
clang fails to compile

### ISSUE THREAD

**Issue by sasmaster** [emscripten-core/emscripten#2203]
I am having this error when compiling hello_world or any other file with clang:

clang.exe:error:unable to execute command:program not executable
clang.exe:error:linker command failed with exit code 1

What do I miss here?I run the command via emscipten command prompt.

Also emcc compiler does seems to be working ok.

**Comment by ArashPix** [comment]
I tried to run "hello-jni" and faced this issue:
_Error	TRK0005	Failed to locate: "clang.exe". The system cannot find the file specified._	
any idea?
