### ISSUE TITLE
How to re-generate libdlmalloc.a after changed dlmalloc (system/lib/dlmalloc.c)?

### ISSUE THREAD

**Issue by xbcnn** [emscripten-core/emscripten#22101]
Seems `dlmalloc` is not linked from source but a pre-built lib `libdlmalloc.a`.  I did some changes in it for debugging purposes, but how can I get the updated `libdlmalloc.a` quickly?  Hopefully won't rebuild whole emsdk.
 
 @sbc100, could you give some advice?

**Comment by sbc100** [comment]
You can use `./embuilder build libdlmalloc --force`

**Comment by xbcnn** [comment]
Cool!  Thanks @sbc100
