### ISSUE TITLE
SDL keyboard bidings are not the same

### ISSUE THREAD

**Issue by Noxalus** [emscripten-core/emscripten#2210]
I'm currently testing a project that detect the space key (with scan code) to perform some actions. That's work great for Windows but I don't have the same behavior in HTML5.

I looked at the differences between SDL 1.2 and 2.0 headers (_SDL_scancode.h_) but this is the same scan code for every keys so I suppose that this bug comes from Emscripten.

Into **library_sdl.js** Emscripten's file, line 85, there is a conversion map from DOM code to SDL code and key codes to scan codes, but for my space key, we can see that the id 44 (space scan code) is associated to the comma key (line 124) and indeed, when I press "comma", I have the same behavior that pressing space on Windows.

Do you remember why you associate the comma key with the scan code of the space key ?

**Comment by Sgeo** [comment]
This is my attempt to make keycodes (I haven't thought about scancodes at all) work cross-browser: https://gist.github.com/Sgeo/f9fff3a49cd0d910f125df54b2ee61d7 . This might not work for other keyboard layouts than the US keyboard layout.

Testing in VICE seems to suggest this mostly works.
