### ISSUE TITLE
Outdated package link on emscripten.org

### ISSUE THREAD

**Issue by kjkent** [emscripten-core/emscripten#22147]
Hello!

While checking out if emscripten.org, I noted there's a link to an outdated, archived Arch Linux GitHub repository [on the install page](https://emscripten.org/docs/getting_started/downloads.html#installation-using-unofficial-packages). In case you'd like to update this, a better link would likely be [https://archlinux.org/packages/extra/x86_64/emscripten/](https://archlinux.org/packages/extra/x86_64/emscripten/)

**Comment by sbc100** [comment]
Perhaps you, or @svenstaro could send a PR to update the link?

**Comment by kjkent** [comment]
@sbc100 happily; will update when done.
