### ISSUE TITLE
Has ldinfo.c been intentionally excluded from libc?

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#22159]
Perhaps this is intentional, however, I noticed today that only a subset of the files under [system/lib/libc/musl/src/ldso/](https://github.com/emscripten-core/emscripten/tree/3.1.58/system/lib/libc/musl/src/ldso) are being built here: [tools/system_libs.py#L1248](https://github.com/emscripten-core/emscripten/blob/3.1.58/tools/system_libs.py#L1248).

In particular, it seems that the lack of `dlinfo.c` in that list is the cause of the following link error when building [rcutils](https://github.com/ros2/rcutils/blob/rolling/src/shared_library.c#L132):
```
error: undefined symbol: dlinfo (referenced by root reference (e.g. compiled C/C++ code))
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _dlinfo may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

**Comment by sbc100** [comment]
We don't currently support dlinfo I'm afraid.  

It would need to be added to `system/lib/libc/dynlink.c` since we don't share dlopen code with musl.

The simplest thing to do is probably to add `&& !defined(__EMSCRIPTEN__)` to this line https://github.com/ros2/rcutils/blob/rolling/src/shared_library.c#L130C1-L130C69

**Comment by allsey87** [comment]
> The simplest thing to do is probably to add && !defined(__EMSCRIPTEN__) to this line https://github.com/ros2/rcutils/blob/rolling/src/shared_library.c#L130C1-L130C69

Yes, this is exactly what I have done. If this isn't planned perhaps this issue can be closed?

**Comment by sbc100** [comment]
Closing for now.  If we see enough demand for this function we could consider implementing it.
