### ISSUE TITLE
CompileError

### ISSUE THREAD

**Issue by sexmastercc** [emscripten-core/emscripten#22168]
im getting a compile error when i run my site in nodejs. Theres no error in the console its just in the browser.
![image](https://github.com/emscripten-core/emscripten/assets/174076060/9fbdbd71-7b8c-4456-a07b-74fef5896ac7)

**Comment by kripken** [comment]
That error probably indicates that the VM does not support SIMD (it is supported in most places, [but not all](https://webassembly.org/features/)). Building without SIMD should work, or running with SIMD in a newer VM.

**Comment by sexmastercc** [comment]
yea it did
