### ISSUE TITLE
In release mode, the "minification" of shell.html remove spaces that should not be removed 

### ISSUE THREAD

**Issue by ypujante** [emscripten-core/emscripten#22188]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.61

I have a custom `shell.html` that I provide to emcc via the `--shell-file=` option.

When I do a build in release mode (with optimizations), `shell.html` gets minified.

Here is an excerpt:

```html
<p>This tool has no tracking, ads or server-side component: it is running 100% in your browser. It uses<a href=https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage>localStorage</a>to store information across browser sessions.</p><p>You can provide feedback or report issues on<a href=https://github.com/pongasoft/webgpu-shader-toy>GitHub</a>.</p>
```

This is the original:

```html
<p>This tool has no tracking, ads or server-side component: it is running 100% in your browser. It uses <a href="https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage">localStorage</a> to store information across browser sessions. </p>
<p>You can provide feedback or report issues on <a href="https://github.com/pongasoft/webgpu-shader-toy">GitHub</a>.</p>
```

As you can see all the spaces BEFORE and AFTER all anchor tags are removed which makes the rendering wrong and TBH quite unreadable...

<img width="1393" alt="Screenshot 2024-07-04 at 11 46 26" src="https://github.com/emscripten-core/emscripten/assets/357116/053dcd61-36cc-4e06-8f30-fda362508a97">

**Comment by kripken** [comment]
The tool we use to minify HTML is `html-minifier-terser`, called from here:

https://github.com/emscripten-core/emscripten/blob/217010a223375e6e9251669187d406ef2ddf266e/tools/link.py#L2565

Perhaps adjusting the flags there can fix this? Or perhaps this is a bug in that project?

**Comment by sbc100** [comment]
@ypujante I've been wondering if `--shell-file` is actually a very useful feature.  Would it not be simpler to just maintain your html file outside of emscripten?  Is there any advantage you get from having emscripten process/use your html?

IIUC most folks who use emscripten just have it generate the js + wasm and take a care of maintain there own html on the side.  Would that work for you?

**Comment by ypujante** [comment]
@sbc100 I found another issue with the minification process:

original:
```html
<input type="text" value="-" disabled>
```

minified:
```html
<input value=- disabled>
```

My code uses the selector: `".GetClipboardString input[type='text']"` to access this element and since `type="text"` is removed, it then fails to find the element...

I think it is time to seriously consider removing support for shell.html since there are so many issues with the minification process...

**Comment by sbc100** [comment]
I guess we could start by simply removing support for automatic minification of the shell.html, since there may still be some use cases for shell.html in test I think.

**Comment by ypujante** [comment]
@sbc100 I think that is a great idea.

Also, as a user of emscripten, I was kind of surprised that `shell.html` would be minified when optimizations are turned on:
* I was definitely expecting `index.wasm` to be compiled with optimizations since this is what I am asking the compiler to do.
* I was semi-expecting `index.js` to be minified (this is not an "optimization" per se)
* I was not expecting `shell.html` to be modified in any fashion

I think keeping `shell.html` (but removing support for automatic minification) is good because:
a) there is a ton of examples and projects out there that use `shell.html` because it is the way that it has been described
b) you don't need an extra step or build framework, since you can simply describe how to build the code with a single command line.

**Comment by sbc100** [comment]
> a) there is a ton of examples and projects out there that use `shell.html` because it is the way that it has been described 

Agreed

> b) you don't need an extra step or build framework, since you can simply describe how to build the code with a single command line.

I somewhat agree.  Although I think trying to cram all features like this into emscripten so it can do everything for you is one of the reasons emscripten is hard to maintain.   Sometimes it is ok/better to require separate tools.

**Comment by ypujante** [comment]
> I somewhat agree. Although I think trying to cram all features like this into emscripten so it can do everything for you is one of the reasons emscripten is hard to maintain. Sometimes it is ok/better to require separate tools.

That is very true!

**Comment by sbc100** [comment]
> @sbc100 I found another issue with the minification process:
> 
> original:
> 
> ```
> <input type="text" value="-" disabled>
> ```
> 
> minified:
> 
> ```
> <input value=- disabled>
> ```

Apparently the default type of an input element is `text`... so I guess this is safe.. do selectors not see the defaults for things like `type`?


> My code uses the selector: `".GetClipboardString input[type='text']"` to access this element and since `type="text"` is removed, it then fails to find the element...
> 
> I think it is time to seriously consider removing support for shell.html since there are so many issues with the minification process...

**Comment by ypujante** [comment]
> Apparently the default type of an input element is `text`... so I guess this is safe.. do selectors not see the defaults for things like `type`?

Yes unfortunately that seems to be the case. Hence the issue I bumped into...

**Comment by sbc100** [comment]
I guess you you can always add `-sMINIFY_HTML=0` ?

**Comment by ypujante** [comment]
> I guess you you can always add `-sMINIFY_HTML=0` ?

I guess I didn't know that this option existed. 

I'm wondering (thinking out loud here) whether this option should be set by default to 0 even when compiling with -O2 since there are issues with HTML minification... It can then be turned on manually if really required

**Comment by juj** [comment]
Posted a fix to the eager whitespace minification in https://github.com/emscripten-core/emscripten/pull/22346
