### ISSUE TITLE
Sorry for asking here but does anyone know where the Emscripten Discussion Github folder has gone?

### ISSUE THREAD

**Issue by aharondavid** [emscripten-core/emscripten#22186]

**Comment by sbc100** [comment]
Sorry, yes, I decided we were not getting much value out of the discussions tab, and folks were using it mostly for same purpose as bug reports.  So I think its simpler just to use bugs for everything.  Did you find some feature of discussions useful?

**Comment by sbc100** [comment]
I guess maybe that was a bad idea if access the old discussions was lost :(   I can look into re-enabling them perhaps?

**Comment by curiousdannii** [comment]
Maybe you could add extra issue templates for questions or discussions? That way it wouldn't feel so naughty to create an issue when [the only options now](https://github.com/emscripten-core/emscripten/issues/new/choose) are bug reports or security vulnerabilities.

**Comment by aharondavid** [comment]
I liked the Discussion folder because when I was unsure about a bug, it provided a space to discuss it without cluttering the Issue tab. The Discussion tab was the best place for those kinds of "bugs."

I think it would be a significant loss to dismiss this folder, which contains a lot of historical information and documentation. These pages are valuable assets that help and support Emscripten on the Net, including searching and AI.

**Comment by sbc100** [comment]
Fair enough.   Lets consider re-opening it.

BTW, @aharondavid do you know that have the emscripten-discuss mailing list, and the emscripten channel on the webassembly discord server to general discussions?

**Comment by aharondavid** [comment]
re-opening it just for ready only is also a good solution.

No I didn't know about the emscripten-discuss mailing list, I will use it.

Thanks.

**Comment by sbc100** [comment]
I reopened the discussions section.  I couldn't find a way to make it read only sadly, but its not a big deal
