### ISSUE TITLE
Bug in page: Emscripten Documentation | Small Typo

### ISSUE THREAD

**Issue by serene-meadow** [emscripten-core/emscripten#22234]
There is a typo. "settings" is misspelled as "serttings" in the "Reference" section.

"Emscripten Compiler Settings is a reference of all the Emscripten compiler **_serttings._**"

URL: [../docs/index](https://emscripten.org/docs/index.html)

**Comment by sbc100** [comment]
Feel free to send a PR for this kind of thing
