### ISSUE TITLE
Is `--fatal-warnings` too strict for `STRICT` mode?

### ISSUE THREAD

**Issue by allsey87** [emscripten-core/emscripten#22253]
Somewhat related to #14824, when enabling `STRICT` mode (which in turn [adds `--fatal-warnings` to the link options](https://github.com/emscripten-core/emscripten/blob/main/tools/building.py#L267-L268)) autoconf's method of detecting the presence of functions will usually fail due to the arguments/return types not lining up during linking.

```c
/* confdefs.h */
#define PACKAGE_NAME "libtest_configure_make"
#define PACKAGE_TARNAME "libtest_configure_make"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "libtest_configure_make 1.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "libtest_configure_make"
#define VERSION "1.0"
/* end confdefs.h.  */
/* Define sin to an innocuous variant, in case <limits.h> declares sin.
   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
#define sin innocuous_sin

/* System header to define __stub macros and hopefully few prototypes,
   which can conflict with char sin (); below.  */

#include <limits.h>
#undef sin

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char sin ();
/* The GNU C library defines this for functions which it implements
    to always fail with ENOSYS.  Some functions are actually named
    something starting with __ and the normal name is an alias.  */
#if defined __stub_sin |defined __stub___sin
choke me
#endif

int
main (void)
{
return sin ();
  ;
  return 0;
}

```

```
wasm-ld: error: function signature mismatch: sin
>>> defined as () -> i32 in /tmp/emscripten_temp_8d0df98f/conftest_0.o
>>> defined as (f64) -> f64 in /tmp/cache/sysroot/lib/wasm32-emscripten/pic/libc-mt.a(sin.o)
```

If `--fatal-warnings` is not added to the link options, these tests pass with a warning from the linker instead of an error. Considering how many C/C++ projects use Autoconf, perhaps `--fatal-warnings` is a bit too strict even for `STRICT` mode? 

**Version of emscripten/emsdk:**
3.1.58

**Comment by sbc100** [comment]
Yes, in general all the things that `-sSTRICT` enabled should be individually configurable.

However about we just allow you to specify `-sSTRICT -Wl,--no-fatal-warnings` (then we don't need to add any new settings?)

**Comment by allsey87** [comment]
> Yes, in general all the things that `-sSTRICT` enabled should be individually configurable.
> 
> However about we just allow you to specify `-sSTRICT -Wl,--no-fatal-warnings` (then we don't need to add any new settings?)

I will have to double check this but I think `--no-fatal-warnings` would come too early in the link command and would be overridden by the `--fatal-warnings`.

**Comment by sbc100** [comment]
I meant that `-sSTRICT` would not add `--fatal-warnings` in that case
