### ISSUE TITLE
FEATURE REQUEST: browser's jpg, png, webp decoders should be usable from emscripten

### ISSUE THREAD

**Issue by terop2** [emscripten-core/emscripten#22267]
We have identified that jpg, png and webp decoders are eating most of our load time and we need better performance. The decoders that use c++-side codecs from stb_image.h probably have unnecessary perf problems because of webassembly's security/boundschecking reasons. For this reason we request new interfaces to access browser's native decoders.

**Comment by terop2** [comment]
https://meshpage.org/process.php -page has our engine running and profiling data clearly indicates decoders to eat too much time

**Comment by terop2** [comment]
![profile3](https://github.com/user-attachments/assets/ae3996f8-7283-45ef-8dc8-59b5185641d7)

**Comment by brendandahl** [comment]
Emscripten can only expose what the browser exposes (e.g. JS/DOM apis). Are you proposing we add an interface to an existing JS API or that the browser should expose the decoders in a new API? If you're asking for the latter, emscripten is probably not the place to request this.

**Comment by terop2** [comment]
I don't know if js side has access to the decoders other than <img> tag. If there's actual js api available, then of course that should be used. But we just need access to the browser's native decoders for performance reasons.

**Comment by kripken** [comment]
Emscripten currently has support for using browser decoders for jpg, png, and bmp files:

https://github.com/emscripten-core/emscripten/blob/8c81cac1bbae378bc7dde0c21c99602cbaf452d0/src/library_browser.js#L127

That works using an Image that that browser decodes asynchronously (so it is part of the preloading logic).

I think we can add webp to that list as well, as it now has [wide browser support](https://caniuse.com/webp).

**Comment by kripken** [comment]
You can also use it after the application loads, with [emscripten_run_preload_plugins](https://emscripten.org/docs/api_reference/emscripten.h.html?highlight=run_preload_plugins#c.emscripten_run_preload_plugins).

**Comment by terop2** [comment]
is there a way to use this without filesystem support compiled in? The preload_plugins() should have filename and contents of the file as parameter instead of trying to load it from filesystem?

**Comment by kripken** [comment]
Yes, `emscripten_run_preload_plugins_data` is the "data, instead of file" version of this.

**Comment by terop2** [comment]
ok, I will need to implement the feature/check if replacing the decoders will improve performance as expected. But it might be that the issue is with correct placement of the decoders in the execution flow, and the actual perf of the decoders isn't the real problem. But will see that after I have working implementation.

**Comment by kripken** [comment]
(Meanwhile I opened #22282 to add WebP support.)

**Comment by terop2** [comment]
i'm halfway through the implementation, but -sJSPI fläg didnt work/I cant change the loading from async to syncronous...

**Comment by terop2** [comment]
(hmm, maybe i need to use await in javascript side?)

**Comment by terop2** [comment]
I have a better plan. I'm going to split LoadImageFromString() into two functions, LoadImageFromString_start(), and LoadImageFromString_finish(). And then do proper async stuff/calling event loop in between them. Then convert all uses of the function to use the new calling pattern. No need for -sJSPI.

**Comment by terop2** [comment]
the only big problem is tinygltf library that might not survive with the async image loading.

**Comment by terop2** [comment]
I found significant problems with the feature/it's not going to work correctly => the feature goes to trashcan.

**Comment by terop2** [comment]
I have implemented concurrent png/texture decoding in 8 cpus using pthreads. It still uses stb image, but at least the perf problem is solved => this issue can be closed as "not implemented" since our solution uses different kind of implementation.

**Comment by kripken** [comment]
Ok, closing. Meanwhile as mentioned above we added webp preloading support, so using he browser's codecs is possible for all the relevant formats, but it is an async operation. Perhaps it would be worth adding Asyncify/JSPI-enabled versions that are sync, but we can consider that separately.
