### ISSUE TITLE
Opening a JS based file with WASMFS hits unimplemented code

### ISSUE THREAD

**Issue by jonahgraham** [emscripten-core/emscripten#22262]
The unreachable is because we are trying to truncate the file (I `fopen`ed it in `"w"` mode). If I open in `"a"` mode so we don't truncate it works fine.

The truncating happens here:

https://github.com/emscripten-core/emscripten/blob/d72d7226f4733af8ff993dec70198cf09a24142d/system/lib/wasmfs/syscalls.cpp#L563-L564

_Originally posted by @jonahgraham in https://github.com/emscripten-core/emscripten/pull/22261#discussion_r1683665630_

**Comment by jonahgraham** [comment]
The test case added in #22261 can be modified to fail by changing the fopen from `"a"` to `"w"`.

**Comment by jonahgraham** [comment]
Thanks @kripken for fixing this :-) And for all the reviews and merging on the related items.

**Comment by kripken** [comment]
Thanks for filing the issue, and the PRs!
