### ISSUE TITLE
Argument order passed to the em_dlopen_callback does not match the declaration.

### ISSUE THREAD

**Issue by davits** [emscripten-core/emscripten#22265]
**Version of emscripten/emsdk:**
`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.44 (bec42dac7873903d09d713963e34020c22a8bd2d)`

The code below is copied from main branch, so the problem most probably is there as well.

emscripten.h declares `emscripten_dlopen()` function and success callbacks as follows:
```cpp
// Asynchronous version of dlopen.  Since WebAssembly module loading in general
// is asynchronous the normal dlopen function can't be used in all situations.
typedef void (*em_dlopen_callback)(void* handle, void* user_data);
void emscripten_dlopen(const char *filename, int flags, void* user_data, em_dlopen_callback onsuccess, em_arg_callback_func onerror);
```
But in my local tests, user_data is passed as first argument and the handle is second.
Also async dlopen test in emscripten lists success callback arguments in (user_data, handle) order:
https://github.com/emscripten-core/emscripten/blob/a1fe3902bf73a3802eae0357d273d0e37ea79898/test/other/test_dlopen_async.c#L9

**Comment by kripken** [comment]
Thanks @davits , that does look wrong.

It seems to have been wrong from the first landing in #14503, though, so maybe we are reading that wrong..? There are tests in that PR, so it seems odd. @sbc100 what do you think?
