### ISSUE TITLE
ASYNCIFY=1

### ISSUE THREAD

**Issue by danchitnis** [emscripten-core/emscripten#22293]
I have been compiling [EEsim.dev](https://eesim.dev/) using Asyncify flags below:
```
-s ASYNCIFY=1 -s ASYNCIFY_ADVISE=0 -s ASYNCIFY_IGNORE_INDIRECT=0
```

However in emcc version `3.1.59` my application breaks.  In the documentation [here](https://emscripten.org/docs/porting/asyncify.html) It says ASYNCIFY option is still available but I cannot find `=1` anymore.

I noticed you are changing ASYNCIFY. please can you advise on how to fix?

PS: I am injecting [custom JS](https://github.com/danchitnis/EEsim/blob/main/Docker/inject.js) into to the glue code

**Comment by curiousdannii** [comment]
`-sASYNCIFY` without a number is the same as `-sASYNCIFY=1`. 

It's hard to give you advise when it's not clear exactly what is wrong. Does it have errors when compiling? Does it compile fine but there are errors in the browser console?

It is possible you are getting errors through those JS injections. In particular, replacing `_emscripten_sleep` seems risky. What are you trying to do with them? Did you try [one of the normal ways of calling JS code](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html)?

**Comment by danchitnis** [comment]
I kind of hacked my way into the glue code back in 2020, and until version 3.1.59, it was fine. So, I need to refresh my memory, but the high-level summary is that the compiled C executable is an interactive command line programme (like Python interactive). Hence, first, I write a file from JS to WASM runtime, then issue a series of terminal commands and collect stdout, stderr etc, and then read a file from WASM to JS.

Is there a list of PRs that lead to version 3.1.59? At the moment, version 3.1.58 is working, but version 3.1.59 is not. Unfortunately, there is no compile error or runtime error. That's why I need some hints on what has changed in this version of emcc and chase those leads. I am not fully sure this is related to ASYNCIFY yet.

**Comment by kripken** [comment]
> Is there a list of PRs that lead to version 3.1.59

You can do

```
git log 3.1.58..3.1.59
```

in an emscripten checkout.

Bisecting may also help here, using `git bisect` in the emscripten checkout (another option is to [bisect over binary builds](https://emscripten.org/docs/contributing/developers_guide.html#bisecting)).

**Comment by danchitnis** [comment]
@kripken I am trying to learn how to use `git bisect` here. Is what I am doing here correct?

```bash
git clone https://chromium.googlesource.com/emscripten-releases
cd emscripten-releases/
git bisect start
```

for 3.1.59
```bash
git bisect bad e20ee09a8a740544c4bc6de5d4ba5f81f74b74d6
```

for 3.1.58
```
git bisect good a4d4afb626c5010f6ccda4638b8d77579a63782e
```

but then what after this? The guide says `emsdk install [hash]` in the release repo. First, there is no `emsdk` file here, second, which hash? `3.1.58` or `3.1.59`?

Thanks.

**Comment by kripken** [comment]
You then run `./emsdk install [hash]` in the emsdk repo, which provides the `emsdk` script. The hash you give it is the one to test. That is, it is a good idea to first see that `./emsdk install [bad-hash]` then leads to an error when you build with that emsdk, and `./emsdk install [good-hash]` then leads to success. And then, the git-bisect tool will tell you the next hash to test as it you make progress.

**Comment by danchitnis** [comment]
The bug was upstream in the C code base. It was printing a message in stderr instead of stdout, and my app was halting. Also, I think the Docker cache was interfering with my build process, hence the confusion with `3.1.58` and `3.1.59`

Nevertheless, what is the roadmap for Asynicify? Are you phasing out Asyncify in favour of JSPI? Which one to use for a new project?

**Comment by kripken** [comment]
In practice you should be able to write the same code and flip between ASYNCIFY and JSPI just using a linker flag, so it's just an implementation detail in that sense. You can decide which to use based on which browsers you need to support (JSPI doesn't have widespread support yet).

Once JSPI is everywhere then we may consider deprecating Asyncify, since it does the same thing but JSPI is much more efficient. But that might take some time.

**Comment by danchitnis** [comment]
Thanks for the support. I am closing this issue.
