### ISSUE TITLE
Runtime Link Error

### ISSUE THREAD

**Issue by MikhailGorobets** [emscripten-core/emscripten#22313]
I'm encountering the following runtime error when running my WASM application.
`wasm streaming compile failed: LinkError: WebAssembly.instantiate(): Import #33 "env" "_tzset_js": function import requires a callable`
What could be the cause? I didn't experience this error with version 3.1.61

**Comment by sbc100** [comment]
This is JS function that is normally provided by the emscripten-generated code.   The function itself was added way back in 
 #16118 but its possible a more recent change caused your program to start depending on this JS function where in that past it didn't.
 
Are you using the generated JS code?

**Comment by MikhailGorobets** [comment]
This might sound strange, but it seems the linking issue occurred when a certain tab was open in the browser. When I closed all tabs except the necessary webpage, I stopped getting the error.
