### ISSUE TITLE
WASM_BIGINT leads to RuntimeError

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#22334]
Compiling the following program with 3.1.64

```cpp
#include <iostream>

std::iostream::pos_type main_default_seekoff() {
  return std::iostream::pos_type{0};
}

int main() {
  main_default_seekoff( );
  return 0;
}
```

with ``em++ main.cpp -sMAIN_MODULE=1 -sWASM_BIGINT -o main.js``

fails with the following error message

`RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #115:"do_callback" failed: expected table index 0, found 0 @+606033)`.

Compiling with ASSERTIONS=2 works as expected.

**Comment by sbc100** [comment]
That above seems to work fine for me:

```
$ em++ main.cpp -sMAIN_MODULE=1 -sWASM_BIGINT -o main.js
$ node main.js
```

I don't see where `do_callback` is defined in your example so I think we must be missing part of your program?

**Comment by gl84** [comment]
Strange, above snippet is the whole code I use to reproduce the issue.

The do_callback seems to come from the emscripten html5 library. Running above code snippet using MAIN_MODULE=2
`em++ main.cpp -sMAIN_MODULE=2 -sWASM_BIGINT -o main.js -sEXPORTED_FUNCTIONS=_main` the error now is `failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #17:"fflush" failed: expected table index 0, found 0 @+1296`

Btw I'm using an M2 Apple.

em++ --version: `emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.64 (a1fe3902bf73a3802eae0357d273d0e37ea79898)`

node --version: `v16.20.0`

**Comment by gl84** [comment]
Sorry about the noise, it seems somehow an old node version crept in. With the current one it works as excepted...
