### ISSUE TITLE
Error with JSPI (works with ASYNCIFY)

### ISSUE THREAD

**Issue by BugraBarin** [emscripten-core/emscripten#22396]
Hi, trying to understand a problem with JSPI. Here's a simple repro:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.64 (a1fe3902bf73a3802eae0357d273d0e37ea79898)
clang version 19.0.0git (https:/github.com/llvm/llvm-project 4d8e42ea6a89c73f90941fd1b6e899912e31dd34)
Target: wasm32-unknown-emscripten
Thread model: posix
```

async.cpp listing
```cpp
#include <emscripten.h>
#include <emscripten/bind.h>

#include <chrono>
#include <stdio.h>
#include <thread>

using namespace emscripten;

EM_JS(void, enter_from_js, (), {
  console.log("--------");
  console.log("enter_from_js");
  Module.sleep_loop();
  console.log("enter_from_js end");
});

void sleep_loop() {
  printf("sleep_loop begin\n");
  while (1) {
    std::this_thread::sleep_for (std::chrono::seconds(1));
    printf("before sleep...\n");
    emscripten_sleep(1);
    printf("after sleep...\n");
  }
}

EMSCRIPTEN_BINDINGS(main) {
  function("sleep_loop", &sleep_loop);
};

```
Entry html page:
```html
  <html lang=en-us>
  <body>
    <button onclick="window.enter_from_js()">Start</button>
    <script async src=async.js></script>
  </body>
  </html>
```

Compile with
```
emcc -lembind -sJSPI async.cpp -o async.js
```

Load the page on Chrome Version 127.0.6533.120 (with JSPI enabled)
Console output after clicking the button:
```
--------
enter_from_js
sleep_loop begin
before sleep...
Uncaught RuntimeError: invalid suspender object for suspend
    at async.wasm:0x920
    at async.wasm:0xf13
    at Object.sleep_loop (eval at newFunc (async.js:1351:27), <anonymous>:8:10)
    at enter_from_js (async.js:898:90)
    at HTMLButtonElement.onclick (async.html:3:53)
```

This works as expected with -s ASYNCIFY. Wondering if this is a bug or I'm missing something.
Thank you!

**Comment by brendandahl** [comment]
[Asyncify and JSPI are slightly different](https://emscripten.org/docs/porting/asyncify.html#differences-between-asyncify-and-jspi). JSPI requires imports and exports to wrapped in special functions. With embind you can add the async attribute:

```
EMSCRIPTEN_BINDINGS(main) {
  function("sleep_loop", &sleep_loop, async());
};
```

then in js
```js
await Module.sleep_loop()
```

There's also an async version of EM_JS called EM_ASYNC_JS. However, it looks like you're using EM_JS to expose some JS on the global, which seems a bit odd. Usually I'd just call embind export directly from JS. EM_JS is more to make it easy to call JS from C++.

**Comment by BugraBarin** [comment]
Thank you Brendan. I was missing the async() parameter in the Embind function.
Forgive the odd example -- I was trying to duplicate what I was seeing with a minimal (though admittedly nonsensical) example.

**Comment by BugraBarin** [comment]
Thanks for pointing out the oddness of EM_JS. I don't know what I was thinking. Changed the
