### ISSUE TITLE
Export pointers as nullable in Typescript

### ISSUE THREAD

**Issue by giuseppesalvo** [emscripten-core/emscripten#22406]
It seems that when exposing a function through embind that returns a raw pointer, the exported type will be:

```typescript
interface TestClass {
  getPtr(): Type
}
```

But the actual JS type will be `null` if the pointer is `nullptr`, so I suppose the exported return type should instead be:

```typescript
interface TestClass {
  getPtr(): Type | null
}
```

**Version of emscripten/emsdk:**
3.1.64

**Comment by brendandahl** [comment]
This was fixed in #22184
