### ISSUE TITLE
Is it correct to pass a JS object with method properties to a C++ class constructor on the js side?

### ISSUE THREAD

**Issue by Dachong233** [emscripten-core/emscripten#22417]
I want to save a val member variable in a C++ class and call its methods when appropriate.
But it seems to throw an exception`Cannot read properties of null (reading ‘getResultFromJs‘)`
Is it right to do that like the following? Here is an example, thank you for any help!
```cpp
class Foo  {
 public:
  Foo(val obj): obj_(obj) {
    // I printf the obj.isNull() is false
    result_ = obj_.call<float>("getResultFromJs");
  };

  float GetResult() { return result_; }

  val obj_;
  float result_;
};
```

```js
const obj = {
  getResultFromJs: () => { return 100; }
};
const foo = new Module.Foo(obj);
...
```

**Comment by Dachong233** [comment]
I tested the code below, both of them can get return value from func in js object
```cpp
auto result0 = jsObj["func"]().as< getResultFromJs >();
auto result1 = jsObj.call<float>("getResultFromJs");
```

I found the fail reason in my project is: I use `this.xxx` in `getResultFromJs`, perhaps `this` is invalidated in C++? Just my guess.

**Comment by brendandahl** [comment]
Do you have an example that reproduces the issue? I tried your example above and it seems to work fine.

**Comment by Dachong233** [comment]
> Do you have an example that reproduces the issue? I tried your example above and it seems to work fine.

Sure. I tried a slightly more complex demo using both of the above methods and found that `result_ = obj_["getResultFromJs"]().as<float>()` maybe result in the error.

```cpp
// cpp
class Foo  {
 public:
  Foo(val obj): obj_(obj) {
    // I printf the obj.isNull() is false
    //result_ = obj_["getResultFromJs"]().as<float>(); // throw error
    result_ = obj_.call<float>("getResultFromJs"); // work fine
    LogUtil::D("Foo init with result_: %f", result_);
  };

  float GetResult() { return result_; }

  val obj_;
  float result_;
};
```
```cpp
// bind
class_<Foo>("Foo")
    .constructor<val>()
    .function("GetResult", &Foo::GetResult);
```

```js
// js
interface JsInterface {
  getResultFromJs: () => number;
}


class JsClass implements JsInterface {
  private result?: number;
  constructor(result: number) {
    this.result = result;
    console.log('JsClass init with result: ', result);
  }


  getResultFromJs(): number {
    console.log('JsClass GetResult: ', this.result, this); // throw error 'Cannot read properties of null (reading 'result')'
    return this.result ?? -1;
  }
}

const obj = new JsClass(100);
const foo = new this.Module.Foo(obj);
console.log('getResultFromCPP result: ', foo.GetResult());
```

```js
// index.js generated by emscripten
var JsClass = /*#__PURE__*/
function() {
    function JsClass(result) {
        _classCallCheck(this, JsClass);
        _defineProperty(this, "result", void 0);
        this.result = result;
        console.log('JsClass init with result: ', result);
    }
    return _createClass(JsClass, [{
        key: "getResultFromJs",
        value: function getResultFromJs() {
            var _this$result;
            console.log('JsClass GetResult: ', this.result, this);
            return (_this$result = this.result) !== null && _this$result !== void 0 ? _this$result : -1;
        }
    }]);
}();
```

```log
// error
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'result')
    at getResultFromJs (index.ts:88:47)
    at methodCaller<(:1234/) => emscripten::val> (webpack://Test/src/test.js?:2399:67)
    at __emval_call (test.js:2321:14)
    at test.wasm:0x1e113
    at test.wasm:0xbc2e4
    at test.wasm:0x1e1f7
    at test.wasm:0xb31b7
    at ret.<computed> (test.js:1317:33)
    at dynCallLegacy (test.js:1129:16)
    at dynCall (test.js:1134:17)
```

**Comment by brendandahl** [comment]
This is expected. `val` is a little counterintuitive with it's naming in respect to JS. The embind `call` method will pass in the `this` object to the js `call` function (i.e. `this` will be the context). Whereas if you use the embind `operator()`, embind will not pass in this to the `call` function, but just invoke the function with `null` as the context.

**Comment by Dachong233** [comment]
> This is expected. `val` is a little counterintuitive with it's naming in respect to JS. The embind `call` method will pass in the `this` object to the js `call` function (i.e. `this` will be the context). Whereas if you use the embind `operator()`, embind will not pass in this to the `call` function, but just invoke the function with `null` as the context.

Thanks again for your explanation and help! Now I use the `call` method and everything works fine.
