### ISSUE TITLE
Add an option to use a custom download script for reproducible offline builds

### ISSUE THREAD

**Issue by egonk** [emscripten-core/emscripten#22424]
I would like to build with emscripten without network communication to make sure the builds are reproducible and offline. Current script in tools/ports (fetch_project) makes it difficult to achieve that.

I propose adding an environment variable EMCC_DOWNLOAD_SCRIPT=/path/to/script so retrieve function would do something like:
```
dlscript = os.environ.get('EMCC_DOWNLOAD_SCRIPT')
if dlscript:
    data = subprocess.check_output([dlscript, url])
```

The alternatives right now are quite difficult and/or hacky (hijacking HTTPS proxy communication from curl/urllib, EMCC_LOCAL_PORTS).

**Comment by sbc100** [comment]
I would recommend using `embuilder` to build all of the ports and libraries you need when you online.

You can confirm that you have built everything you need by running your build with `EM_FROZEN_CACHE`.  This will prevent any new libraries from being built, and ensure that all the libraries you need have already been "prebuilt" via `embuilder`.

**Comment by egonk** [comment]
@sbc100

We have no online mode, all our builds are offline - we have 100 or more other dependencies already working in true offline mode. `embuilder` still needs to be online when fetching dependencies, is that right?

If EMCC_DOWNLOAD_SCRIPT is not desirable, I see another possibility: EMCC_DOWNLOAD_METHOD=curl or EMCC_DOWNLOAD_METHOD=urllib so we can choose our own download method. In our case, we would choose curl and provide our own curl-like tool.

**Comment by egonk** [comment]
@sbc100 

> But don't have have some time when you download emscripten itself? (and binaryen and llvm)? Can't you run embuilder.py at that point. i.e. when you build the emscripten package?
> Or another way of putting it: I assume you want to redirect downloads to some local cache that you have? When do you build that cache? Can you not run embuilder at that point?

The developers are quite free to download and experiment with software, however getting new external dependencies into official builds is then a process:
- all source code assets are re-downloaded and stored into a local cache, file checksums independently verified
- build scripts are reviewed so they build everything from scratch using just the local cache and no binary blobs have sneaked in
- this gives us full control to patch and rebuild everything offline at every single stage quickly

I've checked also emsdk and there seems to be ` if os.path.exists(file_name) and not download_even_if_exists:`
https://github.com/emscripten-core/emsdk/blob/main/emsdk.py#L734

I think gcc build also works like this, the last time I checked we just put gmp, mpfr, etc. tarballs into the right spot and the script picks them up.

So as a third option, if there was a standard download cache folder support in emscripten, that would be equally great!

**Comment by sbc100** [comment]
Emscripten will use cached file if they exist yes.  When building ports if the archive file already exists, and has the correct sha256 checksum then it will not go to the network to fetch it.  These files live in `cache/ports`.

e.g. in my current checkout:

```
$ ll cache/ports/*.zip
-rw-r----- 1 sbc primarygroup  25M Aug 22 16:22 cache/ports/boost_headers.83.0.zip
-rw-r----- 1 sbc primarygroup 7.2M Aug 22 16:22 cache/ports/bullet.zip
-rw-r----- 1 sbc primarygroup 788K Aug 22 16:22 cache/ports/bzip2.0.6.zip
-rw-r----- 1 sbc primarygroup 109K Aug 22 16:21 cache/ports/contrib.glfw3.4.0.20240817.zip
-rw-r----- 1 sbc primarygroup 2.2M Aug 22 16:16 cache/ports/freetype.zip
-rw-r----- 1 sbc primarygroup  25M Aug 22 16:17 cache/ports/icu.zip
-rw-r----- 1 sbc primarygroup 318K Aug 22 16:14 cache/ports/ogg.zip
-rw-r----- 1 sbc primarygroup 8.5M Aug 22 16:16 cache/ports/sdl2.28.4.zip
-rw-r----- 1 sbc primarygroup 1.4M Aug 22 16:16 cache/ports/sdl2_gfx.zip
-rw-r----- 1 sbc primarygroup 9.6M Aug 22 16:20 cache/ports/sdl2_image.6.0.zip
-rw-r----- 1 sbc primarygroup  11M Aug 22 16:16 cache/ports/sdl2_mixer.8.0.zip
-rw-r----- 1 sbc primarygroup 8.7M Aug 22 16:17 cache/ports/sdl2_ttf.20.2.zip
-rw-r----- 1 sbc primarygroup 1.4M Aug 22 16:15 cache/ports/vorbis.zip
```

**Comment by egonk** [comment]
@sbc100 

Aha I'm sorry, you are right. I was looking at retrieve+unpack pair in this code but missed that the fullpath in `if os.path.exists(fullpath):` is stable and not inside some temporary locked dir!

```
    # main logic. do this under a cache lock, since we don't want multiple jobs to
    # retrieve the same port at once
    with cache.lock('unpack port'):
      if os.path.exists(fullpath):
        # Another early out in case another process unpackage the library while we were
        # waiting for the lock
        if up_to_date():
          return
        # file exists but tag is bad
        logger.warning('local copy of port is not correct, retrieving from remote server')
        utils.delete_dir(fullname)
        utils.delete_file(fullpath)

      retrieve()
      unpack()

      # we unpacked a new version, clear the build in the cache
      Ports.clear_project_build(name)
```
