### ISSUE TITLE
[webgpu] Support WGPUCompositeAlphaMode_Premultiplied

### ISSUE THREAD

**Issue by SergeyLebedkin** [emscripten-core/emscripten#22491]
Browsers already supports Premultiplied alpha mode in surface configuration if use JS way to create webgpu context handles.
But emsdk still have it as TODO option.
Please, make it works.

```c++
WGPUSurfaceConfiguration surfaceConfiguration {
    .device = device,
    .format = preferredFormat,
    .usage = WGPUTextureUsage_RenderAttachment,
    .alphaMode = WGPUCompositeAlphaMode_Premultiplied, // <-- does not supported
    .width = w,
    .height = h,
    .presentMode = WGPUPresentMode_Fifo,
};
wgpuSurfaceConfigure(surface, &surfaceConfiguration);
```

**Comment by kainino0x** [comment]
Ah... we left this as TODO in https://github.com/emscripten-core/emscripten/pull/21939#discussion_r1609172689 but forgot to follow up. Thanks for reporting!

I've started trying to fix this.
