### ISSUE TITLE
Calling allocate(intArrayFromString(source), 'i8', ALLOC_STACK) from JavaScript.

### ISSUE THREAD

**Issue by fadams** [emscripten-core/emscripten#2261]
In https://github.com/kripken/emscripten/wiki/Interacting-with-code the recommended approach for converting a JavaScript String to a pointer is to use:
allocate(intArrayFromString(someString), 'i8', ALLOC_STACK)

The implication of this is that the memory is allocated on the stack and would be released at the end of say a function scope, but TBH I've had a bit of a crisis of confidence about that - say I had some code like this:

```
/**
 * Set the address of the Message.
 * @param address the address we want to send the Message to.
 */
_Message_['setAddress'] = function(address) {
    this._check(_pn_message_set_address(this._message, allocate(intArrayFromString(address), 'i8', ALLOC_STACK)));
};
```

That I'm using as a binding "wrapper" to some compiled code, would the allocated memory get automagically freed.

FWIW my crisis of confidence came when I looked at the JavaScript created by the compiler (for a different function) which contained code like this:

```
function _test($data,$text){
 var label=0;
 var sp=STACKTOP;STACKTOP=(STACKTOP+8)|0; (assert((STACKTOP|0) < (STACK_MAX|0))|0);
 var $1;
 var $2;
 var $3=sp; // STACKTOP
 $1=$data;
 $2=$text;
 var $4=$1;
 var $5=$2; //$text
 var $6=_strlen($5);
 var $7=$2; //$text
 _pn_bytes($3,$6,$7); // sp
 var $8=_pn_data_put_string($4,$3);
 STACKTOP=sp;return;
}
Module["_test"] = _test;
```

where I'm seeing a stack pointer variable created at the start and reset just before the return, which made me wonder if the ALLOC_STACK only automagically tidied itself up if it was to be called from inside generated JavaScript (with the STACKTOP=sp;return; stuff).

I'd be grateful is someone was able to reassure me (or otherwise) so that I don't inadvertently create a whole bunch of leaks in my binding.

MTIA

**Comment by kg** [comment]
stackSave/stackRestore don't exist anymore. What's the current approach for this? I need to stackalloc and manually restore the stack (I'm not calling into emscripten from inside emscripten code.)

**Comment by fadams** [comment]
"stackSave/stackRestore don't exist anymore"? WTF? When did this change? I've used emscripten to help create a set of bindings from JavaScript to a fairly significant (in terms of API calls) C library.

I've used stackSave/stackRestore all over the place when I want to convert from a JavaScript string to C style strings, for example (just one of many).
````
    /**
     * The emscripten idiom below is used in a number of places in the JavaScript
     * bindings to map JavaScript Strings to C style strings. ALLOC_STACK will
     * increase the stack and place the item there. When the stack is next restored
     * (by calling Runtime.stackRestore()), that memory will be automatically
     * freed. In C code compiled by emscripten saving and restoring of the stack
     * is automatic, but if we want to us ALLOC_STACK from native JavaScript we
     * need to explicitly save and restore the stack using Runtime.stackSave()
     * and Runtime.stackRestore() or we will leak emscripten heap memory.
     * See https://github.com/kripken/emscripten/wiki/Interacting-with-code
     * The _pn_messenger constructor copies the char* passed to it.
     */
    var sp = Runtime.stackSave();
    this._messenger = _pn_messenger(name ? allocate(intArrayFromString(name), 'i8', ALLOC_STACK) : 0);
    Runtime.stackRestore(sp);
````
I *really* hope this hasn't changed and if it has could you put it back please?

I've not pulled an update for a little while now (I'm currently using 1.28.2) if this has changed when did it happen?

My bindings are now part of another project (Apache Qpid Proton) and if this change has indeed happened it's going to cause me a whole load of rework, which isn't great really.

**Comment by fadams** [comment]
Hmm I've just looked at runtime.js here: https://github.com/kripken/emscripten/blob/incoming/src/runtime.js and I can see:
````
var Runtime = {
// When a 64 bit long is returned from a compiled function the least significant
// 32 bit word is passed in the return value, but the most significant 32 bit
// word is placed in tempRet0. This provides an accessor for that value.
setTempRet0: function(value) {
tempRet0 = value;
},
getTempRet0: function() {
return tempRet0;
},
stackSave: function() {
return STACKTOP;
},
stackRestore: function(stackTop) {
STACKTOP = stackTop;
},
````
Which is as I seem to remember it last time I looked. Has @kg got the wrong end of the stick or should I go back to panicking?

I'm specifically using
var sp = Runtime.stackSave();
perhaps ther was another stackSave that wasn't scoped in Runtime?

**Comment by kg** [comment]
I'm using the latest sdk build compiling a simple js app and stackSave/stackRestore aren't in Runtime. Does closure compiler remove them when minifying? Is there a trick to make it not do that? (I don't remember if I turned Closure on, though...)

**Comment by kg** [comment]
Thanks @fadams for the sanity check; I investigated more deeply.

Enabling closure causes the 'Runtime' global variable to go away, and Module.Runtime loses stackSave/stackRestore. I'm guessing that's because my test application doesn't exercise them. I see the tokens still in the code but it looks like they never get exported.

Definitely a nasty bug but at least that means these features still exist. :-)

**Comment by fadams** [comment]
I'm using closure - I'm using -O2 --closure 1 in my link options.

It might well be a closure thing, I suffered from quite a few closure quirks. What I did with my bindings was to make quite heavy use of --pre-js too so I had my bindings preceed the core library and I also wrapped the whole thing in a self calling lambda too.
````
(function() {
.....

})();
````

**Comment by kripken** [comment]
Runtime.stackSave and stackRestore have not been changed, they are still
there. If closure removes them, you might need to export them, if you use
them from code outside of what closure could see (but that should not have
changed either).

- Alon

**Comment by Ujjwal21** [comment]
@kripken I am looking at ways to convert JS string to char* and other way apart from this is using allocateUTF8 (https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html). What are the scenarios we should use one over other. I am encountering OOM issue when using "**allocate(intArrayFromString(address), ALLOC_STACK))**" with -sASYNCIFY=1

**Comment by sbc100** [comment]
I don't think `allocate(intArrayFromString(address), ALLOC_STACK))` will work because `intArrayFromString` returns a JS object and `allocate` takes a number as its first argument.

The two simplest ways to allocate a `char*` from a JS string are `allocateUTF8` and `allocateUTF8OnStack`.  One allocates memory in the heap and the other on the stack.  I'm not sure where is any other way to go.. what is your rational for not wanting to use those?

**Comment by sbc100** [comment]
Yes `ASYNCIFY` does use memory.   Is the problem that you are just using a lot of memory do you have a memory leak?   if simply increasing your `-sINIITIAL_MEMORY` setting fixes the problem, then is likely be to the latter. 

Are your strings very big?  It seems unlikely that normal-sized string allocated with `allocateUTF8` would use a lot of memory.

**Comment by Ujjwal21** [comment]
Yes, we are using big strings allocated with `allocateUTF8` and increasing the `-sINITIAL_MEMORY` didn't help with OOM issue :(

**Comment by sbc100** [comment]
Increasing `-sINITIAL_MEMORY` should at least delay the OOM.   If it doesn't delay it then its likely not an OOM but some kind of memory corruption. 

Are you sure you are free'ing the strings you allocate with `allocateUTF8`?

**Comment by Ujjwal21** [comment]
Yes, we are freeing in C++ using `free(ptr)`. Actually, we had the same code for allocation and freeing of memory before we started using Asyncify. After adding Asyncify option, I have started encountering this issue.
