### ISSUE TITLE
Breaking the loop in Worker

### ISSUE THREAD

**Issue by andrzejlisek** [emscripten-core/emscripten#22677]
I am trying to write simple program, which uses the Worker, without the SharedArrayBuffer. The program is very simple and print the messages into web browser console.

The GUI has four buttons:
1. **Start** - Run the worker infinite loop, which increments the counter continuously.
2. **Stop** - Stop the infinite loop by changing the loop iteration condition, the function finish will be also printed.
3. **Iterate** - Single counter increment without loop, simulates single iteration.
4. **Status** - Print the current status of work loop (idle or busy) and the current counter value.

I wrote this application using pure JavaScript and its works very well, as I expected. I can start the loop, get status during the loop working and stop the loop.

Then, I am trying to write the same application in C++ using Emscripten, without the SharedBufferArray. How to change the variable value or get the status during the loop working? If I try to compile this code as is, the Start button emits the JavaScript error "await is only valid in async functions and the top level bodies of modules".

Compiling script
```
rm worker.js
rm *.wasm
emcc -std=c++20 main.cpp -s "EXPORTED_RUNTIME_METHODS=['ccall','cwrap']" -o main.js
emcc -std=c++20 worker.cpp -s BUILD_AS_WORKER=1 -o worker.js
```
There is attachment, which contains my application:
[TestWorker3.zip](https://github.com/user-attachments/files/17246215/TestWorker3.zip)
* index.html - main file to run in web browser, its contains both versions (JavaScript and WebAssembly)
* workerjs.js - the JavaScript version of worker core, which works good
* main.cpp - the interface in C++ to run the C++ worker
* worker.cpp - the C++/WASM version of worker core, which not works
Other files are generated by compiler and are unmodified.

How to solve the problem? How to get the C++ to work with the following scenario?
1. Click the "status" several times, print the "idle" and the same number everytime
2. Click the "start".
3. Click the "status" several times, print the "busy" and the another number everytime
4. Click the "stop".
5. Click the "status" several times, print the "idle" and the same number everytime

This scenario works in JavaScript, but not works in the WASM/C++ version.

**Comment by sbc100** [comment]
The alternative (if you cannot break your loop) would be to use something like `-sASYNCIFY`, but it comes with a runtime cost.

**Comment by andrzejlisek** [comment]
Let't assume, that the program to convert from console to WASM is the simple program, simmilar to the programs existing in tutorials.

```
#include <cstdio>
#include <cstring>

int main()
{
    char name[100];

    puts("Please, enter your name: ");
    fgets(name, 100, stdin);
    puts("Hello, ");
    puts(name);
    puts("\n");

    return 0;
}
```

There are two I/O function, the `puts` and `fgets`. I want to print every text as output worker message and input character get as worker messages.

For simplify, assume, that one message carries single character. I done follwong approach with threads:
1. Renamie system functions and write to own implementations
2. Run whole progam in separate thread
3. The input characters will be queued from messages.

The program after changes.
```
#include <cstdio>
#include <cstring>
#include <queue>
#include <thread>

std::queue<int> BufferI;
std::queue<int> BufferO;

bool progWorking = false;
std::thread * progThread = NULL;

// Replacement for original fgets function, assumes that only standard input stream will be used
void fake_fgets(char * str, int num, FILE * stream)
{
    int i = 0;
    while (true)
    {
        if (!BufferI.empty())
        {
            str[i] = BufferI.pop_front();
            if (str[i] == '\n')
            {
                str[i] = 0;
                return;
            }
            else
            {
                if (i == (num - 1))
                {
                  str[i + 1] = 0;
                  return;
                }
            }
            i++;
        }
    }
}

// Replacement for original puts function
void fake_puts(const char * str)
{
    int i = 0;
    while (str[i] != 0)
    {
        BufferO.push_back(str[i])
        i++;
    }
}

// Modified original program code as slightly as possible
void fake_main()
{
    char name[100];

    fake_puts("Please, enter your name: ");
    fake_fgets(name, 100, stdin);
    fake_puts("Hello, ");
    fake_puts(name);
    fake_puts("\n");

    //return 0;
}

// Program start
EMSCRIPTEN_KEEPALIVE
void progStart()
{
    BufferI.clear();
    BufferO.clear();
    Wrk = new std::thread(fake_main);
    progWorking = true;
}

// Program event function to be run periodically using JavaScript setTimeout
EMSCRIPTEN_KEEPALIVE
std::string progEvent(std::string inputChars)
{
    // Enqueue the string passed in argument to the input buffer
    for (int i = 0; i < inputChars.size(); i++)
    {
        BufferI.push_back(inputChars[i]);
    }

    // Return all of outpput buffer contents into the string and return this string
    std::string outputChars = "";
    while (!BufferO.empty)
    {
        outputChars.push_back(BufferO.pop_front());
    }
    return outputChars;
}

// Program stop
EMSCRIPTEN_KEEPALIVE
void progStop()
{
    pthread_cancel(progThread->native_handle());
    progThread->join();
    delete progThread;
    progThread = NULL;   
    progWorking = false;
}

```

As you can see, the original code and original program control flow is almost intact, there was simply "find and replace" for I/O function names (input and print text) and there are some additional functions.

The usage is as following.
1. Run the page, the program will not run automatically.
2. Execute the `progStart` function to start the program work.
3. Periodically, for instance per 200ms, execute the `progEvent`, where the input for user treated as keystroke stream should be passed as argument and the returned string should be displayed to user as text printed by program.
4. If you want to break the prorgam execution, execute the `progStop`.

Fos simplify and clarify, the thread-security routines and elements are skipped, I hope, that the approach is understable.

Applying this approach, it seems to the many console programs can be ported to WASM, the only challenge is rename all occurences of input/print routines and write own implementation of these functions.

Now, I am searching for, how to apply similar approach, using workers instead of thread fo not necessaty SharedBufferArray anymore.

The splitting loop function into two separated functions and `emscripten_cancel_main_loop` routine usage seems be very difficult to apply in this example. In real, I already successfully ported the VTTEST program using threads, which originnaly is written in C.

A tried to compile worker with `-sASYNCIFY` as following:
```
emcc -std=c++20 worker.cpp -s BUILD_AS_WORKER=1 -o worker.js -sASYNCIFY
```
This parameter does not help or I am applying this incorrectly.

**Comment by sbc100** [comment]
If you have threads available we have a settings called `-sPROXY_TO_PTHREAD` that will run your main function in a pthread, leaving the main browser thread free to run its event loop.   This way the main function doesn't need to be broken up and is free to block forever (since communication between pthreads happens in shared memory and not via postMessage).

The `-sBUILD_AS_WORKER` setting is sadly not compatible with pthreads (at least not yet) and is a lot less well tested.   If you can I would suggest using pthreads and loading your program on the main browser thread rather than creating your own workers.

if you want to use `-sASYNCIFY` to break up your infinite loop you should read the docs for it: https://emscripten.org/docs/porting/asyncify.html.   The main thing you need to do it an async import (for example emscripten_sleep()) inside your loop.  This will allow the worker's event loop to run and then return to your code where it left off.

**Comment by andrzejlisek** [comment]
I tried the AYNCIFY again and seems work fine with the example attached in the opening post, the `start` and `stop` functions was slightly modified:
```
void start()
{
    respondProv("Worker start");

    Working = true;
    
    while (Working)
    {
        // Increment iteration counter
        LoopCounter++;
        
        // !!! This line does nothing, but is necessary for allow to get status or stop during the lop work !!!
        emscripten_sleep(1);
    }

    respondLast("Worker finish");
}

void stop()
{
    Working = false;
    respondProv("Worker stop");
}
```

Compiled with this command:
```
emcc -O3 -std=c++20 worker.cpp -s BUILD_AS_WORKER=1 -o worker.js -sASYNCIFY
```
I also tried the `-sJSPI` option, but does not work and is experimental, so the `-sASYNCIFY` solves the problem sufficient.

Where is the examples of worker using? In this doc https://emscripten.org/docs/api_reference/emscripten.h.html there are described the library routines, such as `emscripten_call_worker`, `emscripten_worker_respond`, but some time ago, if I tried to find some example, I found this description: https://stackoverflow.com/questions/32291084/minimal-working-example-for-emscripten-webworker

The mentioned description in the StackOverflow seems to be the best example, how to get started with workers.

**Comment by sbc100** [comment]
We have some simple tests that use the worker API but I don't know of anything more illustrative that that:

```
$ git grep  emscripten_create_worker test
test/worker_api_2_main.cpp:    int w2 = emscripten_create_worker("worker.js");
test/worker_api_2_main.cpp:  w1 = emscripten_create_worker("worker.js");
test/worker_api_3_main.cpp:  w1 = emscripten_create_worker("worker.js");
test/worker_api_main.cpp:  w1 = emscripten_create_worker("worker.js");
```

From you test case it looks like you already have the basics working.  

I guess we can close this issue now?

**Comment by andrzejlisek** [comment]
> I guess we can close this issue now?

Yes, I consider, that this issue is solved.
