### ISSUE TITLE
createModule hangs on WebAssembly.instantiateStreaming in Firefox

### ISSUE THREAD

**Issue by TwoAbove** [emscripten-core/emscripten#22685]
Loading of wasm files through (`createModule()`) sometimes hangs in Firefox and it's not fixable even through uncached reloads, but in Chrome things work. I have encountered this error while working on noitool locally (http://localhost:3000), but some of my users have reported seeing this issue in prod (https://www.noitool.com).

You can check out the wasm loader and the wasm files here: [loader.mjs](https://github.com/TwoAbove/noita-tools/blob/develop/src/services/SeedInfo/noita_random/noita_random.mjs) [binary.wasm](https://github.com/TwoAbove/noita-tools/blob/develop/src/services/SeedInfo/noita_random/noita_random.wasm). The loader is called [here](https://github.com/TwoAbove/noita-tools/blob/develop/src/services/SeedInfo/random/index.ts).

I have traced the issue back to the `createModule()` function, specifically `instantiateAsync()` and `WebAssembly.instantiateStreaming`:
```js
function instantiateAsync(binary, binaryFile, imports, callback) {
      if (
        !binary &&
        typeof WebAssembly.instantiateStreaming == "function" &&
        !isDataURI(binaryFile) &&
        !ENVIRONMENT_IS_NODE &&
        typeof fetch == "function"
      ) {
        return fetch(binaryFile, { credentials: "same-origin" }).then(response => {
          var result = WebAssembly.instantiateStreaming(response, imports);
          // v Promise hangs as "pending"
          return result.then(callback, function (reason) { 
            err(`wasm streaming compile failed: ${reason}`);
            err("falling back to ArrayBuffer instantiation");
            return instantiateArrayBuffer(binaryFile, imports, callback);
          });
        });
      }
      return instantiateArrayBuffer(binaryFile, imports, callback);
    }
```

The `WebAssembly.instantiateStreaming` Promise never actually resolves and it hangs on `"pending"`. I'm not sure where to go from here in debugging this, and I'll be happy to help in any way I can.

**Version of emscripten/emsdk:**
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.68 (ceee49d2ecdab36a3feb85a684f8e5a453dde910)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 5cc64bf60bc04b9315de3c679eb753de4d554a8a)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Users/twoabove/p/build/emsdk/upstream/bin
```

**Failing command line in full:**
I have a compiling script for this wasm module. The wasm gets compiled and used in both the browser and node environments.
```sh
OS="$(uname)"
ARCH="$(uname -m)"

run_empp() {
  output_file="$1"
  shift

  em++ --bind -O3 "$@" \
    -o "$output_file" \
    --std=c++20 \
    --extern-pre-js="pre.js" \
    -s WASM=1 \
    -s FILESYSTEM=0 \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s MODULARIZE=1 \
    -s NO_EXIT_RUNTIME=1 \
    -s ENVIRONMENT="web,worker,node" \
    -s EXPORT_NAME="create_noita_random" \
    -s "EXPORTED_FUNCTIONS=['_generate_path_map','_free','_malloc']" \
    -s "EXPORTED_RUNTIME_METHODS='cwrap'" \
    src/wasm_in.cpp
}

run_empp noita_random.mjs -msse2 -msimd128
run_empp noita_random-base.mjs
```

I see this issue in Firefox 130.0.1 (64-bit). Also tested in Chrome 129.0.6668.90. macOS 15.0 (24A335)

**Comment by brendandahl** [comment]
I don't think there's much action we can take on this with the current info. It sounds like it's a Firefox bug, but a small reproducible example would be helpful to figure where the issue is. If it is a bug with Firefox, [please file an issue with them](https://bugzilla.mozilla.org/).

**Comment by TwoAbove** [comment]
Thanks! 
I had hoped you might have encountered something similar. 

I'll get a minimal working example ready

**Comment by TwoAbove** [comment]
https://gist.github.com/TwoAbove/72afeac61dce7dcd858cf485dc0de696 
https://github.com/TwoAbove/noita-tools/raw/8d7794f56b7dbb7fa843d7455bbb4db9bc3b6060/src/services/SeedInfo/noita_random/noita_random.wasm

Download the html and the wasm file. Put them in one place and then run `python3 -m http.server` and go to http://localhost:8000/emscripten.html to see the reproducible result

But with this minimal reproducible example, I see that I do have an error message and not the hanging that I've seen. 

```
Uncaught (in promise) TypeError: import object field 'a' is not an Object 
```

May that be why it might hang? It's actually a bad wasm compilation?

**Comment by sbc100** [comment]
@TwoAbove it looks like you are not providing any imports (i.e. you are passing {} to instantiateAsync).   The wasm module will almost certainly require some imports.   The `a` import likely means that emscripten has minified the names of the imports and exports by renaming `env` to just `a`. 

(I would not normally recommend trying to write you own JS loader code for emscripten-generated wasm, better to use the emscripten-generated JS)

**Comment by TwoAbove** [comment]
Turns out this is a Firefox bug, I'll create a bug report with them. Thanks for the support!
