### ISSUE TITLE
Add deleteLater() and setDelayFunction(...) to TypeScript definitions and make them official API

### ISSUE THREAD

**Issue by arnog-ms** [emscripten-core/emscripten#22701]
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.68-git
clang version 20.0.0git
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/emscripten/3.1.68/libexec/llvm/bin
```

We are using the `deleteLater()` function a lot in our TypeScript codebase to not forget to delete a short lived reference. This works quite well. The only drawback is that we have to patch the generated TypeScript definitions to include the `deleteLater()` function for each interface that also has the `delete()` function. And we patch the `MainModule` export to include the `setDelayFunction(...)` definition, so that we can set the delay function at MainModule instantiation.

It would be great, if these two could be added to the generated TypeScript definitions and also be made an official API.

**Comment by sbc100** [comment]
I believe if you want to have `setDelayFunction` exported you should add it to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE`.   This should result it being part of the module definition.

**Comment by sbc100** [comment]
It looks like we were exported some functions under the hood so `setDelayFunction` was being made available, even if it wasn't needed.  I'm fixing that in #22705.

Regarding `deleteLater`, that looks like maybe a different issue.  @brendandahl should be declaring these methods in the generated TS?

**Comment by arnog-ms** [comment]
I tried to add `-sEXPORTED_RUNTIME_METHODS=setDelayFunction` but received the following warning

```
warning: invalid item in EXPORTED_RUNTIME_METHODS: setDelayFunction
em++: warning: warnings in JS library compilation [-Wjs-compiler]
```

Is this due to the bug mentioned above? If so, should this work with 3.6.19 once it's released?

**Comment by sbc100** [comment]
Thats odd. Are you passing `--bind`?   Is seems to work fine for me:

```
((3.1.68)) $ ./emcc test/hello_world.c -sEXPORTED_RUNTIME_METHODS=setDelayFunction --bind
```

**Comment by arnog-ms** [comment]
This is an excerpt from our cmake file. -lembind is equivalent to --bind, isn't it?

```
if(${CMAKE_SYSTEM_NAME} MATCHES "Emscripten")
    set(CMAKE_EXECUTABLE_SUFFIX ".js")

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --no-entry --emit-tsd wasmtypes.d.ts")

    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -sWASM=1 -sEXPORT_ES6=1 -sMODULARIZE=1 -sEXPORTED_RUNTIME_METHODS=setDelayFunction -lembind -sEXPORT_NAME=ManagerModule")
endif()
```

**Comment by brendandahl** [comment]
I think that is hitting the bug about runtime exports combined with emit-tsd. That is fixed #22705

**Comment by sbc100** [comment]
Ah yes, try `emsdk install tot` to get ta build with that change in.

**Comment by arnog-ms** [comment]
OK, I will give that a try in the next few days.

If I understand correctly, this would only solve the `setDelayFunction` export, right? So the `deleteLater` is not covered by this?

**Comment by brendandahl** [comment]
Correct, I'll add a separate fix for that.

**Comment by arnog-ms** [comment]
Thank you very much!

**Comment by sbc100** [comment]
Yes `setDelayFunction` is just a normal library function so should be part of your generated TS once its exported normally.

`deleteLater` looks like its a method that exists on all embind objects.  Should we be declaring this (and other builtin methods)?  Is it possible for a user method to collide with one of these builtin method names?

**Comment by arnog-ms** [comment]
I think, at the moment, only `delete` is exported automatically. For me it would be great to also export `deleteLater` automatically.

Together with `setDelayFuntion` this makes it much easier to not forget to delete a reference.

It might also be worthwile to set the delay function to `setTimeout(fn, 0)` by default.

**Comment by brendandahl** [comment]
> Yes `setDelayFunction` is just a normal library function so should be part of your generated TS once its exported normally.
> 
> `deleteLater` looks like its a method that exists on all embind objects. Should we be declaring this (and other builtin methods)? Is it possible for a user method to collide with one of these builtin method names?

 I think we just need to update the defaults. These definitions were mostly from the previous TS project, so I'm not sure why they're missing. The names could collide, but that should really be an error.

**Comment by arnog-ms** [comment]
I tested with 3.16.9 and I can see the export of setDelayFunction in the .d.ts file. Thanks for that. :-)
