### ISSUE TITLE
Enable to use multiple canvas

### ISSUE THREAD

**Issue by jihoonbyun** [emscripten-core/emscripten#2271]
In some c/c++ opengl projects, can see multiple windows. And
"glutSetWindows" function sets current window, and "glutGetWindows" return current window id.

Thus, for porting the glutSetWindow and glutGetWindow functions to JS, the emscripten should support multiple canvas at least.
But, after few look , I think the whole architecture is based on single canvas.
this is glutCreateWindow (library_glut.js)

``` javasript
  glutCreateWindow: function(name) {
    var contextAttributes = {
      antialias: ((GLUT.initDisplayMode & 0x0080 /*GLUT_MULTISAMPLE*/) != 0),
      depth: ((GLUT.initDisplayMode & 0x0010 /*GLUT_DEPTH*/) != 0),
      stencil: ((GLUT.initDisplayMode & 0x0020 /*GLUT_STENCIL*/) != 0)
    };  
    Module.ctx = Browser.createContext(Module['canvas'], true, true, contextAttributes);
    return Module.ctx ? 1 /* a new GLUT window ID for the created context */ : 0 /* failure */;
  }
```

Module.ctx is just one canvas tag. It's not Array. and There's no use of parameter 'name'. ( I think the parameter should be the window 'id'. so maybe it's suitable for canvas classname or id).

for using multiple canvas, the 'Module.ctx must be changed in some parts. But is it OK?  and where's Module.ctx and how to implement into html?

Do you have any good solutions?

**Comment by zivsha** [comment]
@kripken, @juj has this changed in the last 4 years? Is it possible to bind multiple canvases to different windows (OpenGL contexts)? I couldn't find a way or example for doing that. Currently only by creating an `iframe` and assigning it with a different script (that creates a window and renders with OpenGL) I am able to display multiple canvases.

**Comment by zivsha** [comment]
Could you point me to which function(s) I should use to target a specific GL context to a specific canvas?

**Comment by juj** [comment]
Apologies, somehow missed the followup question. I suppose you did figure it out as there were no further pings. :)

To summarize, the function `emscripten_webgl_create_context` can be used to create a context against a specific canvas on the page, and the function `emscripten_webgl_make_context_current` can then be used to switch between the active context.

**Comment by zivsha** [comment]
Hi @juj , this was a long time ago so I don'r remember if I was able to complete my little experiment. Thanks anyways

**Comment by damien-monni** [comment]
Hi @juj, it seems that I am able to create new contexts with `emscripten_webgl_create_context` and `emscripten_webgl_make_context_current` but it does not behave as I expected with the SDL port :

```c
EmscriptenWebGLContextAttributes contextAttr;
emscripten_webgl_init_context_attributes(&contextAttr);
EMSCRIPTEN_WEBGL_CONTEXT_HANDLE context = emscripten_webgl_create_context("#canvas2", &contextAttr);

emscripten_webgl_make_context_current(context);

SDL_Init(SDL_INIT_VIDEO);
window = SDL_CreateWindow("SDL Tutorial", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 500, 500, SDL_WINDOW_SHOWN);

```
I thought it would switch the SDL context but the window is created on the first canvas instead of my canvas with the id #canvas2. Am I doing something wrong?

**Comment by juj** [comment]
I think `SDL_CreateWindow` or will on its own create a WebGL context, so the emscripten_webgl_* functions are ignored/"overwritten". I don't recall off the top of my head if there is a way to let SDL 2 specify which canvas to target.

The SDL 1.4 support code in Emscripten repository is old and hardcoded to looking at `Module.canvas` as the target canvas - to choose the target canvas one should set a different canvas DOM element there.

**Comment by clo-yunhee** [comment]
AFAIK the canvas id that is used as the window surface is hardcoded as `#canvas` in SDL2

**Comment by damien-monni** [comment]
> AFAIK the canvas id that is used as the window surface is hardcoded as `#canvas` in SDL2

Yes, I just opened a issue about this: https://github.com/emscripten-ports/SDL2/issues/130
