### ISSUE TITLE
Help with debugging wasm and page generated with Emscripten 3.1.68

### ISSUE THREAD

**Issue by netolcc06** [emscripten-core/emscripten#22733]
Hi everyone,

I'd like to have some guidance on how to properly debug one issue I'm having.

A few months ago I worked on using Emscripten to generate a wasm version of [cvc5](https://github.com/cvc5/cvc5). At that time I was using Emscripten v3.1.18 and managed to produce successful builds and pages by setting the `HTML` option. Flags such as `-s EXPORTED_RUNTIME_METHODS='["ccall","cwrap"]' -s ENVIRONMENT=web -s EXPORTED_FUNCTIONS=_main -s INVOKE_RUN=1 -s EXIT_RUNTIME=0 -s INCOMING_MODULE_JS_API=argument` also worked fine.

Recently I tried to use Emscripten 3.1.68 with the same flags, but the generated page just throws a generic message `Uncaught (in promise) 868912` when it starts. I thought the issue could be related to changes in cvc5's build system, but nothing has changed there - and old versions of the program that used to produce valid wasm + html pages present the same behaviour if built with 3.1.68. From what I checked from Emscripten docs, compilation instructions seem to be the same as a few months back though.

With that said, what is the best way of moving forward here and debug what is happening with the page? I want to figure out what actually got broken with the most recent version and adjust my source code, if necessary, in order to produce valid wasm binaries.

Thanks in advance!

**Comment by kripken** [comment]
For a regression like this, [bisection](https://emscripten.org/docs/contributing/developers_guide.html#bisecting) is often a fast way to find what caused the issue.

**Comment by sbc100** [comment]
Also, building with without optimization (i.e. with -O0 which is the default) and/or with `-sASSERTIONS` can help a lot.   

When you get the `Uncaught (in promise)` I would expect some kind of backtrace that might give you a clue as to what the issue is.

**Comment by sbc100** [comment]
> Ok. Apart some missing flags I need to add, the ultimate exception is `unsupported syscall: __syscall_prlimit64`.

I don't think the `unsupported syscall: __syscall_prlimit64` message is the direct cause.  That just means that syscall is not fully implemented, but it still returns and your program continues, to the actual exception is something else.  Put another way, the "unsuppoered syscall" message is just a console warning, and nothing more.
