### ISSUE TITLE
Question: Is there a way to write a file to local hard disk

### ISSUE THREAD

**Issue by JD31** [emscripten-core/emscripten#22740]
I am running autotests with emrun and everything works fine.
On test errors I save screenshots to emscripten IndexedDB.
I know that it is not directly possible to write it as well on the local hard disk but I wonder if there are some workarounds.
I am thinking of "writing" the file to stdout and then rebuilding it from the log file. I guess that should make the trick but do you have other advices ?
Thanks!

**Comment by juj** [comment]
If you're using emrun, then you're in luck: you can use this syntax to upload a file to the emrun "host" filesystem:

https://github.com/emscripten-core/emscripten/blob/ac381b83585cb89a33739e4cfb33e674b8db208e/test/test_emrun.c#L20-L23

Maybe that helps?

Hmm, that actually doesn't show how to upload a given byte array. That would be done with

```js
EM_ASM({emrun_file_dump("test.dat", HEAPU8.subarray($0, $0+$1));}, pointerToByteBuffer, lengthBytes);
```

**Comment by juj** [comment]
Implementation comes from https://github.com/emscripten-core/emscripten/blob/ac381b83585cb89a33739e4cfb33e674b8db208e/src/emrun_postjs.js#L81-L90 , so requires building with Emscripten linker flag `--emrun`.

**Comment by JD31** [comment]
Great, it is exactly what I am looking for. Will have a try today and post here if everything works.

**Comment by JD31** [comment]
It raises the following error:

```
Uncaught TypeError: Failed to execute 'send' on 'XMLHttpRequest': The provided ArrayBufferView value must not be shared.
    at emrun_file_dump (http://localhost:6931/Line.js:9924:10)
    at 827040 (http://localhost:6931/Line.js:1474:5)
    at runEmAsmFunction (http://localhost:6931/Line.js:5948:26)
    at _emscripten_asm_const_int (http://localhost:6931/Line.js:5951:59)
```

What does mean 'The provided ArrayBufferView value must not be shared' ?

**Comment by juj** [comment]
Oh, this is due to having a multithreaded build. Try changing 

```js
EM_ASM({emrun_file_dump("test.dat", HEAPU8.subarray($0, $0+$1));}, pointerToByteBuffer, lengthBytes);
```
to
```js
EM_ASM({emrun_file_dump("test.dat", new Uint8Array(HEAPU8.subarray($0, $0+$1)));}, pointerToByteBuffer, lengthBytes);
```

**Comment by JD31** [comment]
That works ! Thanks so much.

**Comment by juj** [comment]
Thanks - this gives an idea to improve the ergonomy here: I think it would be interesting to have a header `#include <emscripten/emrun.h>`, which would include this kind of a `emrun_file_dump()` C function out of the box, without needing to EM_ASM() it in, and manage the multithreading quirk manually.

I'll reopen this ticket to track that development.

**Comment by JD31** [comment]
For info if it can help, I ended with the following function:


```
void dumpFile(const std::filesystem::path& sourcePath)
{
    const auto destinationPath{sourcePath.filename()};
    std::ifstream file{sourcePath, std::ios::binary};
    const std::vector<unsigned char> buffer(std::istreambuf_iterator<char>(file), {});
    EM_ASM({emrun_file_dump(UTF8ToString($0), new Uint8Array(HEAPU8.subarray($1, $1 + $2)));}, destinationPath.c_str(), buffer.data(), buffer.size());
}
```

**Comment by oatgnauh** [comment]
> For info if it can help, I ended with the following function (for thread case):
> 
> ```
> void dumpFile(const std::filesystem::path& sourcePath)
> {
>     const auto destinationPath{sourcePath.filename()};
>     std::ifstream file{sourcePath, std::ios::binary};
>     const std::vector<unsigned char> buffer(std::istreambuf_iterator<char>(file), {});
>     EM_ASM({emrun_file_dump(UTF8ToString($0), new Uint8Array(HEAPU8.subarray($1, $1 + $2)));}, destinationPath.c_str(), buffer.data(), buffer.size());
> }
> ```

but this seems can not be used in online application? looks like a debug tool

**Comment by JD31** [comment]
> but this seems can not be used in online application? looks like a debug tool

Yes it is for debug purpose and for emrun builds/tooling only.
