### ISSUE TITLE
Missing WebGPU texture format enum values

### ISSUE THREAD

**Issue by jankrassnigg** [emscripten-core/emscripten#22766]
There are missing enum values for WebGPU texture formats.

Emscripten version "Release 3.1.67 (#1448)" (SHA a2383b33581adb7383c8f874d2dc34e07d055332)

In emsdk\upstream\emscripten\system\include\webgpu\webgpu_cpp.h 

`enum class TextureFormat` at least these values are missing:
* `RG16Unorm`
* `RG16Snorm`
* `R16Unorm`
* `R16Snorm`
* `RGBA16Unorm`
* `RGBA16Snorm`

These are present in Dawn, thus can be used in desktop builds, but they seem to have been forgotten in Emscripten. It is currently not possible to compile valid WebGPU code for Emscripten, because the enum constant value don't exist.

Additionally in `enum class FeatureName` the value `Unorm16TextureFormats` is missing as well, which is why one cannot request runtime support for this feature through Emscripten at the moment.

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.65 (7f8a05dd4e37cbd7ffde6d624f91fd545f7b52e3)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 547917aebd1e79a8929b53f0ddf3b5185ee4df74)
Target: wasm32-unknown-emscripten
Thread model: posix

**Comment by kainino0x** [comment]
These formats do not exist in the Web API yet (they are proposed but not accepted):
https://gpuweb.github.io/gpuweb/#enumdef-gputextureformat
So they can't be used via Emscripten except with non-standard extensions enabled. We do expose some of Chromium's (command line flag gated) experimental features via Emscripten, but this one is not even in Chromium, it's only in Dawn.

If you'd like to advocate for adding it to the API (it's not terribly hard, we just haven't done it), please comment on https://github.com/gpuweb/gpuweb/issues/3001

**Comment by jankrassnigg** [comment]
Thanks for the information, I wasn't aware that this is not in the official spec!
