### ISSUE TITLE
FS no longer populated after "Micro-optimize preRun/postRun handling. NFC (#22671)"

### ISSUE THREAD

**Issue by stbergmann** [emscripten-core/emscripten#22790]
As originally described at <https://groups.google.com/g/emscripten-discuss/c/eJyqgMCWnCs/m/SrA2CtuBAQAJ> 'FS no longer populated after 'Micro-optimize preRun/postRun handling. NFC (#22671)'":

When building my app (LibreOffice on top of Qt6) with a build of latest emsdk 3.1.69, I found that the virtual file system would no longer be populated and only contained the bare hardcoded minimum.

Turned out that <https://github.com/emscripten-core/emscripten/commit/483cdcd5306780520a2de8856fcd13910e71497e> "Micro-optimize preRun/postRun handling. NFC (https://github.com/emscripten-core/emscripten/pull/22671)"
```
> diff --git a/src/preamble.js b/src/preamble.js
> index d37cb9fe7..3a6aee9c9 100644
> --- a/src/preamble.js
> +++ b/src/preamble.js
> @@ -195,11 +195,10 @@ function preRun() {
>    assert(!ENVIRONMENT_IS_PTHREAD); // PThreads reuse the runtime from the main thread.
>  #endif
>  #if expectToReceiveOnModule('preRun')
> -  if (Module['preRun']) {
> -    if (typeof Module['preRun'] == 'function') Module['preRun'] = [Module['preRun']];
> -    while (Module['preRun'].length) {
> -      addOnPreRun(Module['preRun'].shift());
> -    }
> +  var preRuns = Module['preRun'];
> +  if (preRuns) {
> +    if (typeof preRuns == 'function') preRuns = [preRuns];
> +    preRuns.forEach(addOnPreRun);
>    }
>  #endif
>    callRuntimeCallbacks(__ATPRERUN__);
```
caused the function `runWithFS` to no longer be called, because it gets added to` Module.preRun` from within the function `runMetaWithFS` that itself is called from within the function `preRun`.

Locally reverting that commit fixed the issue for me for now.

**Comment by sbc100** [comment]
Revert in flight. 

BTW, are you attached to using file preloading?  Does file embedding not for your use case for some reason?

**Comment by sbc100** [comment]
Actually looking at the code I'm struggling to see where `preRun` is added within `runMetaWithFS`: https://github.com/emscripten-core/emscripten/blob/fb2ae6165e786f13d1202403d49767039f7d88ad/tools/file_packager.py#L1105-L1116

Where in `runMetaWithFS` does `preRun` get modified?

**Comment by stbergmann** [comment]
> Where in `runMetaWithFS` does `preRun` get modified?

See the `then(loadPackage)` there, where towards the end of `loadPackage` it does
```
    if (Module['calledRun']) {
      runWithFS(Module);
    } else {
      if (!Module['preRun']) Module['preRun'] = [];
      Module["preRun"].push(runWithFS);
    }
```
where it enters the `else`-branch.
