### ISSUE TITLE
How to get the used memory of a webassembly instance in real time

### ISSUE THREAD

**Issue by wohencainiao** [emscripten-core/emscripten#22859]
When I create an instance of webassembly, I use the MAXIMUM_MEMORY compilation directive to limit the maximum memory to 1023M，Then I'll load the webassembly instance in Google Chrome and run it，During use, I need to request new memory until the maximum memory limit is reached，Then the Google Chrome console will report an error “Cannot enlarge memory, asked to go up to 1078722560 bytes, but the limit is 1072693248 bytes”，I don't want Google Chrome to get an error，So I'm wondering if there are some methods or functions that let me get the memory usage of my webassembly instance，So that in my code I can judge for myself that new memory is not allowed to be requested when the maximum memory limit is about to be exceeded，thanks

**Comment by sbc100** [comment]
Yes, you can use `emscripten_get_heap_size`: https://github.com/emscripten-core/emscripten/blob/01f89dcd3cb505f3fdfa3b2bd3d4ef654c753f0a/system/include/emscripten/heap.h#L34-L35

**Comment by wohencainiao** [comment]
My use case is to compile my C project into a webassembly file，In C code, I would use the “malloc” and “free” functions to request and free memory，I've tested and found that the memory that this function “emscripten_get_heap_size” gets only increases, When I use “free” in C code to free up memory，The value obtained again using this function“emscripten_get_heap_size” does not decrease，It's not the same effect I wanted，I want to know the used and free memory of webassembly in real time，Is there any other way to do it, thank you

**Comment by sbc100** [comment]
> My use case is to compile my C project into a webassembly file，In C code, I would use the “malloc” and “free” functions to request and free memory，I've tested and found that the memory that this function “emscripten_get_heap_size” gets only increases, When I use “free” in C code to free up memory，The value obtained again using this function“emscripten_get_heap_size” does not decrease，It's not the same effect I wanted，I want to know the used and free memory of webassembly in real time，Is there any other way to do it, thank you

Unforteuntly wasm memory can never shink so the value of `emscripten_get_heap_size` will never decrease and the browser will never be able to reclaim that memory as long as the program continues to run.  At least not until some new standard such as https://github.com/WebAssembly/memory-control allows for it.

If you are interested in the amount of free memory inside the wasm memory you can use functions like https://linux.die.net/man/3/mallinfo to get this data.

**Comment by wohencainiao** [comment]
Thank you for your answer to your questions about the memory of webassembly，I understand，I have one more question for you by the way，I create an instance of webassembly, I use the MAXIMUM_MEMORY compilation directive to limit the maximum memory to 1023M，When I open two Google pages and load the webassembly instance separately，I'll print the acquired webassembly memory to Google Console，I found that the webassembly memory of the two Google pages is independent，It's not that the two pages add up to the maximum memory，It seems that the maximum memory of each page is counted independently，I would like to inquire if this is normal，Does each individual browser page use its own maximum memory, rather than multiple pages sharing a single maximum memory?

**Comment by sbc100** [comment]
> Thank you for your answer to your questions about the memory of webassembly，I understand，I have one more question for you by the way，I create an instance of webassembly, I use the MAXIMUM_MEMORY compilation directive to limit the maximum memory to 1023M，When I open two Google pages and load the webassembly instance separately，I'll print the acquired webassembly memory to Google Console，I found that the webassembly memory of the two Google pages is independent，It's not that the two pages add up to the maximum memory，It seems that the maximum memory of each page is counted independently，I would like to inquire if this is normal，Does each individual browser page use its own maximum memory, rather than multiple pages sharing a single maximum memory?

Yes, its not just each page that has its won memory, but each wasm instance.  So if you instantiate the same module more then once on the same page each instance will have its own memory with its own maximum.

Note the the maximum memory is just the, a maximum, so the memory won't necessarily start of that large, but could grow to that large over time.

**Comment by wohencainiao** [comment]
Thank you for the answer, I understand；In this principle, when I open multiple browser pages at the same time and load multiple wasm instances，I've found that when each wasm instance memory is used close to the maximum，The browser freezes or crashes，Is this normal? Is there any way to prevent this from happening? thank you

**Comment by sbc100** [comment]
> Thank you for the answer, I understand；In this principle, when I open multiple browser pages at the same time and load multiple wasm instances，I've found that when each wasm instance memory is used close to the maximum，The browser freezes or crashes，Is this normal? Is there any way to prevent this from happening? thank you

When the system is at its memory limit that it can become unstable yes.   Some OSs such as linux have an OOM killer which will start terminating random processes.   If you are using more memory than you system has I'm not sure what mitigation browser have in place to deal with that.

**Comment by oatgnauh** [comment]
> Yes, you can use `emscripten_get_heap_size`:
> 
> https://github.com/emscripten-core/emscripten/blob/01f89dcd3cb505f3fdfa3b2bd3d4ef654c753f0a/system/include/emscripten/heap.h#L34-L35

this function seems get the same value as `Module.wasmMemory.buffer.byteLength` ?

**Comment by sbc100** [comment]
> this function seems get the same value as `Module.wasmMemory.buffer.byteLength`

Yes, that is what this function does.  It gets the current size of the webassembly memory.   The word `heap` could be a bit misleading which is why I added some more docs in #22871
