### ISSUE TITLE
--js-library can not recieve calls to posix_spawn

### ISSUE THREAD

**Issue by Antony74** [emscripten-core/emscripten#22903]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.71

**Failing command line in full:**
Below

**Full link command and output with `-v` appended:**
N/A

The following works as expected, allowing a JavaScript function called not_posix_spawn to be called from the C code.

```javascript
// library.js

addToLibrary({
    posix_spawn: () => {
        console.log('posix_spawn has been called in library.js');
        return 0;
    },
    not_posix_spawn: () => {
        console.log('not_posix_spawn has been called in library.js');
        return 0;
    },
});
```

```C
// interacting-with-code.c
//
// Usage:
//     emcc -O2 -s NODERAWFS=1 --js-library library.js interacting-with-code.c
//     node a.out.js

#include <stdio.h>
#include <spawn.h>

int posix_spawn(pid_t *pid, const char *path,
                       const posix_spawn_file_actions_t *file_actions,
                       const posix_spawnattr_t *attrp,
                       char *const argv[], char *const envp[]);

int not_posix_spawn(pid_t *pid, const char *path,
                       const posix_spawn_file_actions_t *file_actions,
                       const posix_spawnattr_t *attrp,
                       char *const argv[], char *const envp[]);

int main() {
    pid_t pid = -1;

    int result = not_posix_spawn(&pid, "fakeExecutable", 0, 0, 0, 0);

    printf("result %d\n", result);

    return 0;
}
```
Output as expected:

    # emcc -O2 -s NODERAWFS=1 --js-library library.js interacting-with-code.c
    cache:INFO: generating system asset: symbol_lists/9748aa9895a042df517cb4758f147263de2ef395.json... (this will be cached in "/emsdk/upstream/emscripten/cache/symbol_lists/9748aa9895a042df517cb4758f147263de2ef395.json" for subsequent builds)
    cache:INFO:  - ok
    # node a.out.js
    not_posix_spawn has been called in library.js
    result 0

@sbc100 expressed the hope [here](https://github.com/emscripten-core/emscripten/issues/14453#issuecomment-2465663356) that posix_spawn should be similiarly deferable to JavaScript.  Unfortunately however, when I change line 23 of interacting-with-code.c from `not_posix_spawn` to `posix_spawn`:

BUG:

    # emcc -O2 -s NODERAWFS=1 --js-library library.js interacting-with-code.c
    cache:INFO: generating system asset: symbol_lists/9748aa9895a042df517cb4758f147263de2ef395.json... (this will be cached in "/emsdk/upstream/emscripten/cache/symbol_lists/9748aa9895a042df517cb4758f147263de2ef395.json" for subsequent builds)
    cache:INFO:  - ok
    # node a.out.js
    result -1

EXPECTED:

    # emcc -O2 -s NODERAWFS=1 --js-library library.js interacting-with-code.c
    # node a.out.js
    posix_spawn has been called in library.js
    result 0

Note that the value of -1 returned by the call to posix_spawn is what it is stubbed to return in system/lib/libc/emscripten_libc_stubs.c

i.e. this would be the correct behavior were no posix_spawn function defined in library.js.

**Comment by sbc100** [comment]
You would then just need to include your native posix_spawn on the link command line either as a library or an object file.

**Comment by Antony74** [comment]
I confirm your workaround is effective, and I am happy with it, thanks :-)

**Comment by sbc100** [comment]
Awesome!  I think we can close this bug then?
