### ISSUE TITLE
Browsers don't well show info about uncaught C++ exceptions.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#2292]
Posting this bit of info that seems to semi-regularly come up for users, to give keywords to search and help on debugging uncaught C++ exceptions.

If your application throws a C++ exception that is not caught by the application, it will most likely show up in the web console as "uncaught exception: 4232526" (the number is a pointer/address to the thrown structure) without good file:line information.

See https://bugzilla.mozilla.org/show_bug.cgi?id=996060 and https://bugzilla.mozilla.org/show_bug.cgi?id=996063.

As a workaround for browsers that do show file:line info, but fail to show info about chained re-throws, one can find the place in the generated output and **comment out** the try-catch, e.g. like follows:

```
//  try {
    var ret = Module['_main'](argc, argv, 0);
    // if we're not running an evented main loop, it's time to exit
    if (!Module['noExitRuntime']) {
      exit(ret);
    }
/*  }
    catch(e) {
    if (e instanceof ExitStatus) {
      // exit() throws this once it's done to make sure execution
      // has been stopped completely
      return;
    } else if (e == 'SimulateInfiniteLoop') {
      // running an evented main loop, don't immediately exit
      Module['noExitRuntime'] = true;
      return;
    } else {
      if (e && typeof e === 'object' && e.stack) Module.printErr('exception thrown: ' + [e, e.stack]);
      throw e;
    }
    } finally { */
    calledMain = true;
//  }
```

Note that if the throws occur inside an event callback such as requestAnimationFrame,  the call site of the try-catch you need to comment out will be different. Commenting out the catch statement allows you to get the file:line info of the original throw call site, instead of the chained throw that Emscripten does.

Another workaround is to manually wrap `main()` and all your C++ event callbacks facing JavaScript side with a global try-catch block and compile with the link flag `-s DISABLE_EXCEPTION_CATCHING=0` to enable catching exceptions. For example:

```
void callback() {
  try {
    some_work_that_might_throw();
  } catch(const std::exception &e) {
    std::cout << "Uncaught exception " << e.what() << "!\n";
  } catch(...) {
    std::cout << "Uncaught unknown exception!\n";
  }
}

int main() {
    emscripten_set_main_loop(callback, 0, 0);
}
```

Printing out the `e.what()` can give more info to better understand what the exception is that was thrown, which is something that the web console will not be able to print out.

A third workaround is to try running the output on multiple browsers, as each browser prints things out differently. Perhaps one of them might give that helpful clue to figuring out the source.

Btw, is there anything we can do to aid the prints in the Emscripten side?

**Comment by HOuaghad** [comment]
I have been struggling for the last two days to figure this out. I would always receive:
```
Uncaught 0
```

or 

```
Uncaught 5135153
```

Regardless of whether I comment out the try and catch blocks as mentioned up there, or add the catch-all block.

Adding the catch-all block indicated that none of my custom exceptions were raised, only some unknown one.

Turns out, some of my functions that were being `try-ied` had a return value, and I was not return anything.

Example:

```
bool init()
{
   /* code code code*/
  if(!something){ throw myCustomException }
 /*And no, no return statement*/
}

int main()
{
     try{
           init()
     }
    catch(const std::exception& e)
    {
      std::cout << "Exception caught" << std::endl;
    }
   catch(...)
   {
    std::cout << "Uncaught Exception" << std::endl;
   }
```

so I was not returning anything... and that was the problem.

I wonder why my compiler did not show any warnings regarding this, although I was using the flag for it... could it be because I passed the flag at `emconfigure` time using `-DCMAKE_CXX_FLAGS` ?

**Comment by makc** [comment]
> `EXCEPTION_DEBUG` should emit stack traces when we throw, which might help here.

@kripken so I have added ` -s EXCEPTION_DEBUG=1` to em++ command line and yet am getting all anonymous stack trace:
![image](https://user-images.githubusercontent.com/242577/171837837-abcb0218-5284-4d38-98ee-09bc595ae536.png)

were there any changes to this since 2014?

**Comment by kripken** [comment]
@makc To get names in stack traces, build with `--profiling-funcs` for example.

**Comment by makc** [comment]
thanks, can I just put it on emcmake line, I used .a files built with that - maybe thats why EXCEPTION_DEBUG fails. but at least part of that stacktrace is build with em++ from sources 🤔
