### ISSUE TITLE
Memory access out of bounds due to SDL2 and many other things

### ISSUE THREAD

**Issue by Buggem** [emscripten-core/emscripten#22923]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.71 (4171ae200b77a6c266b0e1ebb507d61d1ade3501)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
(Latest stable release at current time)

**Full link command and output with `-v` appended:**
```
emcc  -m32 -g -s USE_SDL=2 -Wall -DNORMALUNIX -DLINUX -DSDL  -c i_sdl_video.c -o linux/i_sdl_video.o
i_sdl_video.c:350:15: warning: unused variable 'sdl_event' [-Wunused-variable]
  350 |     SDL_Event sdl_event;
      |               ^~~~~~~~~
i_sdl_video.c:26:1: warning: unused variable 'rcsid' [-Wunused-const-variable]
   26 | rcsid[] = "$Id: i_x.c,v 1.6 1997/02/03 22:45:10 b1 Exp $";
      | ^~~~~
2 warnings generated.
```

Emscripten crashes with memory out of bounds too many times in SDL2. Live demo here: https://buggem.github.io/sdl_doom_em

I get these weird errors like `Uncaught DOMException: Document.querySelector: '-14673908' is not a valid selector`  when I move my mouse well. What could possibly be going on. It's simply chaos in the console.

**Comment by kripken** [comment]
Weird errors like that can be undefined behavior or memory corruption. The sanitizer tools can help figure things out:

https://emscripten.org/docs/debugging/Sanitizers.html

**Comment by sbc100** [comment]
When you see `Uncaught DOMException: Document.querySelector` can see a backtrace?  It might provide some insight into what is going on here.

If you don't see wasm function names in your backtraces you can try linking with `-g`.

**Comment by Buggem** [comment]
I do see wasm function names in my backtraces but not all of them. Idk, it seems pretty unrelated, but the main thing looks like `emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.`. I am using `emscripten_request_animation_frame_loop` only but not `emscripten_set_main_loop`

**Comment by Buggem** [comment]
> Weird errors like that can be undefined behavior or memory corruption. The sanitizer tools can help figure things out:
> 
> https://emscripten.org/docs/debugging/Sanitizers.html

Sanitizing for undefined behavior showed nothing, so I don't know.
