### ISSUE TITLE
__embind_initialize_bindings is stripped from export table in Release + pthreads build

### ISSUE THREAD

**Issue by laminowany** [emscripten-core/emscripten#22968]
This is a regression in 3.1.70, on previously tested version 3.1.56 it worked correctly. My application gets undefined reference to __embind_initialize_bindings during runtime.

There is a code which adds `__embind_initialize_bindings` to exported symbols:

https://github.com/emscripten-core/emscripten/blob/119a427e18eca02192fea679256c021834835cb4/tools/link.py#L508-L509

but this seems to be stripped during call to binaryen:

https://github.com/emscripten-core/emscripten/blob/119a427e18eca02192fea679256c021834835cb4/tools/building.py#L842-L847

The binaryen takes an DCEGraph as an input, and when I inspect the json of graph it has following entry:
```
{
    "name": "emcc$export$__embind_initialize_bindings",
    "export": "_embind_initialize_bindings",
    "reaches": []
 },
```
 I can fix this issue by manually editing this intermediate file and changing this entry to:
```
   {
    "name": "emcc$export$__embind_initialize_bindings",
    "export": "_embind_initialize_bindings",
    "reaches": [],
    "root": true
  }
```

My guess: `_embind_initialize_bindings` should be marked with `root: true` but for some reason is not.

Another workaround is manually exporting this function via:
`EXPORTED_FUNCTIONS=_main,__embind_initialize_bindings"`
but I believe it should not be needed.

This issue is similiar to: https://github.com/emscripten-core/emscripten/issues/21844

**Comment by kripken** [comment]
Metadce can strip things that are not used, so somehow it is not seeing a use of that function, is my best guess. Do you have a testcase showing the issue that we can investigate?

cc @brendandahl

**Comment by sbc100** [comment]
@laminowany can you share more details about your use case?   What link flags are you using?   I assume you are using pthreads since that is the only place _embind_initialize_bindings is called.

**Comment by laminowany** [comment]
I don't really have minimal reproducible case yet, I was trying to build https://github.com/mitchcurtis/slate with Qt dev built from source.

Linker flags are following:
`em++.py -O3 -DNDEBUG -profiling-funcs -s MODULARIZE=1 -s EXPORT_NAME=app_entry -s EXPORTED_RUNTIME_METHODS=UTF16ToString,stringToUTF16,JSEvents,specialHTMLTargets,FS,callMain -s PTHREAD_POOL_SIZE=4 -s INITIAL_MEMORY=50MB -s MAXIMUM_MEMORY=4GB -s MAX_WEBGL_VERSION=2 -s FETCH=1 -s WASM_BIGINT=1 -s STACK_SIZE=5MB -pthread -s ALLOW_MEMORY_GROWTH -sASYNCIFY_IMPORTS=qt_asyncify_suspend_js,qt_asyncify_resume_js -s ERROR_ON_UNDEFINED_SYMBOLS=1 -Wno-pthreads-mem-growth`

**Comment by sbc100** [comment]
I don't see either `-lembind` or `--bind` on the command line there, which mean that program doesn't look like its using embind at all.

The resulting code should therefor not contains a call to `_embind_initialize_bindings` in the pthread startup code: https://github.com/emscripten-core/emscripten/blob/bd2de9cd7c2a5b8343b90bb5164ef4ec30d4b68b/src/runtime_pthread.js#L168-L175.

Can you confirm where the call from `_embind_initialize_bindings` is coming from?  Is it the pthread startup code, or somewhere else?

If possible perhaps you can bisect to figure out which change caused the regression: https://emscripten.org/docs/contributing/developers_guide.html#bisecting

**Comment by laminowany** [comment]
Sorry for late reply, but I needed to double check that the flags I got are right. I missed the `-lembind` flag because it was hidden between list ot *.a files on linker argument list.

So the total list of flags looks like this:
```
-O3 -DNDEBUG -s MODULARIZE=1 -s EXPORT_NAME=app_entry -s EXPORTED_RUNTIME_METHODS=UTF16ToString,stringToUTF16,JSEvents,specialHTMLTargets,FS,callMain -s PTHREAD_POOL_SIZE=4 -s INITIAL_MEMORY=50MB -s MAXIMUM_MEMORY=4GB -s MAX_WEBGL_VERSION=2 -s FETCH=1 -s WASM_BIGINT=1 -s STACK_SIZE=5MB -pthread -s ALLOW_MEMORY_GROWTH -sASYNCIFY_IMPORTS=qt_asyncify_suspend_js,qt_asyncify_resume_js -s ERROR_ON_UNDEFINED_SYMBOLS=1 -Wno-pthreads-mem-growth -lembind -o app/app.js
```

The application depends on Qt framework which uses embind internally, and all Qt projects will get this flag set by default.
This is done by:

https://github.com/qt/qtbase/blob/a13eb28329b08c53085bc2902c4a99d0758f972c/src/corelib/Qt6WasmMacros.cmake#L187

initialize_bindings is being called from pthread startup code:
![image](https://github.com/user-attachments/assets/f388428d-4fb3-4987-b86b-03cc06dcd922)

**Comment by sbc100** [comment]
Can you link with `EMCC_DEBUG=1` and attach the output?

**Comment by laminowany** [comment]
Output looks following: https://pastebin.com/A9aVVTx7

Relevant part is here I guess:
```
building:DEBUG: unused_exports: ['_embind_initialize_bindings', '_emscripten_thread_crashed', 'emscripten_main_runtime_thread_id', 'emscripten_main_thread_process_queued_calls']
```

**Comment by sbc100** [comment]
Can you attach a copy of `/tmp/emscripten_temp/emcc-02-original.js` after running the build? (or maybe the entire `/tmp/emscripten_temp` directory)

**Comment by laminowany** [comment]
Here is the entire `/tmp/emscripten_temp/` dir: https://drive.google.com/file/d/1CmDsPpUk2srMFzeuFSYIcha0RkTF2qsI/view?usp=sharing

**Comment by laminowany** [comment]
From what I tested the breakage was somewhere between 3.1.56 and 3.1.58 version.

**Comment by laminowany** [comment]
This seems to be a culprit: https://github.com/emscripten-core/emscripten/commit/37e1e68d5162c8bef0a842bd6efbd78b6130d43c

**Comment by sbc100** [comment]
There is some kind of bug in DCE here though since `_embind_initialize_bindings` should never be detected as part of `unused_exports` since it *is* clearly used in the output right?  So metadce must be somehow confused about that symbol.

**Comment by kripken** [comment]
@sbc100 that does sound likely. Looking at the `emcc-NN-*` temp files, `emcc-09-AJSDCE.js` looks ok (there is a use and a definition of that function), while the next JS file, `emcc-11-applyDCEGraphRemovals.js` looks bad (there is only a use, no def). I'm looking into it.

**Comment by laminowany** [comment]
This is fix for me: https://github.com/emscripten-core/emscripten/compare/main...laminowany:emscripten:22968?expand=1

But I dont know if its a "proper" fix.

**Comment by laminowany** [comment]
The problems is that here it gets filtered out and not marked as a root:
https://github.com/emscripten-core/emscripten/blob/1092ec30a3fb1d46b1782ff1b4db5094d3d06ae5/tools/building.py#L793

While it was rooted in previous emscripten

**Comment by laminowany** [comment]
Emscripten 3.1.56 was doing something similiar:
![image](https://github.com/user-attachments/assets/5eea95ce-d780-4fb9-ba62-0b651ce0f9a1)

**Comment by sbc100** [comment]
Nice work find that alon!   What a horrible bug

**Comment by laminowany** [comment]
I tested your patch @kripken  and it does solve a problem on my machine, thanks for looking into it!

**Comment by kripken** [comment]
@laminowany Ok, #23159 should fix this properly. If it's not too much trouble, can you try that PR on your code?

**Comment by laminowany** [comment]
I tested with my code and https://github.com/emscripten-core/emscripten/pull/23159 does fix it for me!

**Comment by kripken** [comment]
Perfect, thanks @laminowany ! I'll land it as soon as tests pass.
