### ISSUE TITLE
there is no emscripten_builtin_realloc

### ISSUE THREAD

**Issue by graph** [emscripten-core/emscripten#23080]
I see a thread here: https://github.com/emscripten-core/emscripten/issues/9337 which suggests to do emscripten_builtin_malloc/free. I don't know where that is defined but managed to make use of it by doing

```
extern "C" {
    void* emscripten_builtin_malloc(size_t);
    void emscripten_builtin_free(void*);
}

void* malloc(size_t size) {
    size += sizeof(MyHeader);
    MyHeader* header = (MyHeader*)emscripten_builtin_malloc(size);
    // do stuff
    return header+1;
}
// similarly adjusts the pointer provided as appropriate.
```

There is no emscripten_builtin_realloc/~~calloc~~ and it seems the dlXXXX functions have been made completely hidden. Can all the builtins be made available for override? I don't see any documentation on this subject.

Thanks

**Comment by sbc100** [comment]
You can find them in `emscripten/heap.h`.

**Comment by graph** [comment]
https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/heap.h

Thanks, I see there is calloc, I must have messed up something doing the extern manually. I see no realloc. Tomorrow I will try doing the calloc override and see if that is sufficient for the use case above.

**Comment by sbc100** [comment]
We don't have an emscripten_builtin_realloc (I'm not actually sure why we don't.. perhaps we could add one).

**Comment by graph** [comment]
calloc is not enough. Yes please do add realloc so I can properly handle the custom header adjustment. Thank you.
