### ISSUE TITLE
Issue with SDL2 Game in Emscripten: Errors When Accessing via LAN IP Address

### ISSUE THREAD

**Issue by db-tech** [emscripten-core/emscripten#23102]
Hey everyone,  

I'm building a small game using SDL2 with Emscripten. The game requires `-pthread` for threading support. For testing, I host it locally using a simple Go server.  

When I access the game via **localhost** (e.g., `http://localhost:8080/game`), everything works as expected—the game starts without issues.  

However, when I try to access it using my LAN IP address (e.g., `http://192.168.0.30:8080/game`), I encounter multiple errors, including:  
```

w:0,t:0x00d8b6c8: pthread_create: environment does not support SharedArrayBuffer, pthreads are not available game.js:1253:11
w:0,t:0x00d8b6c8: __resumeException 0x00da02b8,std::runtime_error: SDL_Init Error: Not enough resources to create thread game.js:1253:11
Uncaught (in promise) std::runtime_error: SDL_Init Error: Not enough resources to create thread
```

I suspect this has something to do with the environment or the way browsers handle threading and `SharedArrayBuffer` over non-localhost connections, but I'm not sure.  

## What I've Tried:  
1. Ensured that `-pthread` is properly configured during the build.  
2. Checked server logs for any anomalies—everything seems fine from the server side.  
3. Verified the browser console for additional clues—errors point to threading issues as shown above.  

## Questions:  
1. Could this be related to browser security policies (e.g., `SharedArrayBuffer` support)?  
2. Is there a specific setting I need to enable for LAN testing?  

I'd appreciate any insights or solutions. Thanks in advance!

**Comment by sbc100** [comment]
See the note at the top of https://emscripten.org/docs/porting/pthreads.html#pthreads-support.    It links to https://web.dev/articles/coop-coep for more info.
