### ISSUE TITLE
Issue setting an object's vector with embind's vector.set

### ISSUE THREAD

**Issue by mttjcksn** [emscripten-core/emscripten#23109]
Hi there, 

I have been caught out by the behaviour of vector.set and am wondering if it is expected.

In the example below, `ProcessTest` contains a vector of  ints called `paramInfo` that is initialised with 1 item, value 0.

I make an instance of ProcessTest and want to change the value inside the vector. If I try to set the value directly with vect.set, it works. If I try to set it via it's parent object with testObj.paramInfo.set, it returns ok, but does not work. Is this expected?

   ```ts
    let testObj: ProcessTest = new wasmModuleRef.current.ProcessTest(69, 13);

    // Set just the vector...
    let vect: IntVector = testObj.paramInfo;
    console.log(vect.get(0)); // Should be 0
    if(vect.set(0, 100))
    {
        console.log("set returned true");
    }
    console.log(vect.get(0)); // Should be 100

    console.log("----");

    // Set via the object that contains the vector
    console.log(testObj.paramInfo.get(0)); // Should be 0
    if(testObj.paramInfo.set(0, 100))
    {
        console.log("set returned true");
    }
    console.log(testObj.paramInfo.get(0)); // Should be 100
```

Results in:

```
0
set returned true
100
----
0
set returned true
0
```

I have a large class I need to bind with vectors of objects that contain vectors of objects, and so on. So if this is the case, the process of updating values might be a bit arduous.

Many thanks

**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.73-git

**Comment by brendandahl** [comment]
I don't see the EMSCRIPTEN_BINDINGS section posted, but I'm guessing what is happening is when you call `testObj.paramInfo` you're triggering the copy constructor of the vector. You probably want to use a reference instead something like `.property("paramInfo", & ProcessTest::paramInfo, return_value_policy::reference())`

More info on return value policies [here](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#advanced-class-concepts)

**Comment by mttjcksn** [comment]
Hah, that was it! Thanks so much for a quick response.
Using my example, I was under the impression that testObj was a copy, but that it would contain all members and that I could access testObj.paramInfo without creating a further copy.  I'll read up.

Thanks
