### ISSUE TITLE
Dynamic linking with -`sFETCH`: symbol type mismatch

### ISSUE THREAD

**Issue by laminowany** [emscripten-core/emscripten#23123]
Not sure if it should be bug ticket in Emscripten or LLVM project.

There is regression in 3.1.64, which actually seems to come from LLVM 19 and this commit:
https://github.com/llvm/llvm-project/commit/22b7b84860d39da71964c9b329937f2ee1d875ba

Basically dynamic linking with '-sFETCH' no longer works and errors with:

```
wasm-ld: error: symbol type mismatch: _emscripten_get_fetch_queue
>>> defined as WASM_SYMBOL_TYPE_DATA in /emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libfetch.a(emscripten_fetch.o)
>>> defined as WASM_SYMBOL_TYPE_FUNCTION in qtbase/lib/libQt6Qml.so

wasm-ld: error: symbol type mismatch: emscripten_proxy_fetch
>>> defined as WASM_SYMBOL_TYPE_DATA in /emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libfetch.a(emscripten_fetch.o)
>>> defined as WASM_SYMBOL_TYPE_FUNCTION in qtbase/lib/libQt6Qml.so

wasm-ld: error: symbol type mismatch: emscripten_fetch_attr_init
>>> defined as WASM_SYMBOL_TYPE_DATA in /emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libfetch.a(emscripten_fetch.o)
>>> defined as WASM_SYMBOL_TYPE_FUNCTION in qtbase/lib/libQt6Qml.so

(...)
```

**Comment by sbc100** [comment]
The file in `/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libfetch.a` seems to be wrong about the type of that symbol.  I have no idea how that could happen.

Are you using emsdk? 

When I build that libfetch library with `./embuilder build libfetch --pic` those functions all have the correct symbol type:

```
$ llvm-objdump -t /usr/local/google/home/sbc/dev/wasm/emscripten/cache/sysroot/lib/wasm32-emscripten/pic/libfetch.a | grep emscripten_proxy_fetch
0000004f g     F CODE	0000007f emscripten_proxy_fetch
```

Can you try deleting that file and rebuilding it?  If the problem persists can you attach the `libfetch.a` file.

**Comment by sbc100** [comment]
If possible, could you provide a (small-ish) reproducer?   Perhaps a simple program that uses fetch and fails to link in this way?

**Comment by laminowany** [comment]
I've used both emsdk and emscripten from source.
When trying to come up with minimal reproducer I realized that we are passing the `-sFETCH` flag both to side modules as well as main modules.
Changing our build system so only MAIN_MODULE is linked with `-sFETCH`, while SIDE_MODULEs are not, actually fixes the issue.
Thanks for assistance!
