### ISSUE TITLE
How to implement a new version of malloc?

### ISSUE THREAD

**Issue by Tt421** [emscripten-core/emscripten#23121]
I need to use the following version of malloc in my source code:

`(i64) -> i32` 

But I only found the following version of malloc in emscripten:
`(i32) -> i32` 

Does emscripten support other library functions including malloc in i64 version? If not, will it be realized in the future?
If I were to implement other library functions for the i64 version myself, how would I proceed? give me some suggestions, thanks.

**Comment by Tt421** [comment]
Thanks for reply. I understand. And how to use Memory64 in emscripten (version 3.1.14)? I did not find any running programs and commands on official or other sources. Can you give an example to illustrate how to use Memory64?

**Comment by kripken** [comment]
The flag is here:

https://emscripten.org/docs/tools_reference/settings_reference.html#memory64

You can find working examples in the test suite by searching for that flag, `MEMORY64`.

But `3.1.14` may not be new enough.  Looking in the changelog, `3.1.49` had many relevant fixes, and only in `3.1.72` was the flag no longer experimental. I would recommend using the latest version.

**Comment by Tt421** [comment]
oh, thanks! I still have a small question. When compiling the source code for the X86_64 platform, my C code uses the `c99 `standard, and my C++code uses the `gnu++14` standard. I want to know how to specify the C/C++standard using emscripten?

I tried changing `clang `to `emcc `and `clang++`to `em++`in the original compilation script. However, the function signature of `malloc ` (similar to other C/C++standard library functions) in the generated LLVM IR is inconsistent with the original, that is:
original: `(i64) -> i32`
Now: `(i32) -> i32`

I want to make the C/C++function signatures in the LLVM IR generated by emscripten consistent with the original.

Is the inconsistency in function signatures the difference between X86_64 platform and wasm32 (or wasm64)

**Comment by sbc100** [comment]
Where are you seeing malloc defined as `(i64) -> i32`?   Can you share the full error message?   That signature should never be the signature of malloc unless something is configured badly.   Specifically, which object contains the bad malloc signature?    Can you point to the source code for that object file?

**Comment by sbc100** [comment]
No, it does not look related to X86_64 platform and wasm32 since malloc should always have he same return type as its parameter type.

**Comment by Tt421** [comment]
oh I have resolved this issue by adding the option `-sMEMORY64` to the original compilation script. Now their signatures are consistent, the problem is because I previously modified LLVM IR.Thank you very much for your help.
