### ISSUE TITLE
Using -mavx for libsndfile fails

### ISSUE THREAD

**Issue by jozefchutka** [emscripten-core/emscripten#23138]
Please include the following in your bug report:

**Version of emscripten/emsdk:**
3.1.73
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.73 (ac676d5e437525d15df5fd46bc2c208ec6d376a3)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 1d810ece2b2c8fab77720493864257f0ea3336a9)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /ffmpeg-wasm/issue-xx/emsdk/upstream/bin

Using the latest emscripten 3.1.73 and `-mavx` it fails on error `error: must use 'union' tag to refer to type 'm256_data'`

Scritp to reproduce

```sh
#!/bin/bash

apt-get update
apt-get install -y git python3.11 build-essential cmake autoconf autogen automake libtool pkg-config ragel wget
git config --global pull.rebase false
ln -sf /usr/bin/python3.11 /usr/bin/python

# EMSDK
git clone --depth=1 --branch main https://github.com/emscripten-core/emsdk/
(cd emsdk && ./emsdk install 3.1.73)
(cd emsdk && ./emsdk activate 3.1.73)
source ./emsdk/emsdk_env.sh

# SETUP
export PATH=$PATH:$EMSDK/upstream/bin
ROOT_DIR=$PWD
WASM_DIR=$ROOT_DIR/wasm
BUILD_DIR=$ROOT_DIR/build
PKG_CONFIG_PATH=$BUILD_DIR/lib/pkgconfig
export EM_PKG_CONFIG_PATH=$PKG_CONFIG_PATH
TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
export CFLAGS="-O3 -flto -I$BUILD_DIR/include -pthread -msimd128 -mavx"
export CXXFLAGS=$CFLAGS
export LDFLAGS="$CFLAGS -L$BUILD_DIR/lib"
mkdir -p $WASM_DIR

# libsndfile
git clone --depth=1 --branch master https://github.com/libsndfile/libsndfile
(cd libsndfile && \
  emconfigure autoreconf -vif && \
  CFLAGS=$CFLAGS emconfigure ./configure \
    --prefix=$BUILD_DIR \
    --host=i686-gnu \
    --enable-shared=no \
    --disable-asm \
    --disable-rtcd \
    --disable-doc \
    --disable-extra-programs \
    --disable-stack-protector)

emmake make -C libsndfile clean
emmake make -C libsndfile install
```

Output log

```
make[2]: Entering directory '/ffmpeg-wasm/issue-xx/libsndfile'
  CC       programs/sndfile-info.o
  CC       programs/common.o
  CC       src/libsndfile_la-sndfile.lo
In file included from src/sndfile.c:28:
In file included from src/common.h:49:
In file included from /ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/immintrin.h:11:
/ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1774:3: error: must use 'union' tag to refer to type 'm256_data'
 1774 |   m256_data ret;
      |   ^
/ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1781:3: error: must use 'union' tag to refer to type 'm256_data'
 1781 |   m256_data ret;
      |   ^
/ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1788:3: error: must use 'union' tag to refer to type 'm256_data'
 1788 |   m256_data ret;
      |   ^
/ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1795:3: error: must use 'union' tag to refer to type 'm256_data'
 1795 |   m256_data ret;
      |   ^
/ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1802:3: error: must use 'union' tag to refer to type 'm256_data'
 1802 |   m256_data ret;
      |   ^
/ffmpeg-wasm/issue-xx/emsdk/upstream/emscripten/cache/sysroot/include/compat/avxintrin.h:1809:3: error: must use 'union' tag to refer to type 'm256_data'
 1809 |   m256_data ret;
      |   ^
6 errors generated.
make[2]: *** [Makefile:2827: src/libsndfile_la-sndfile.lo] Error 1
make[2]: Leaving directory '/ffmpeg-wasm/issue-xx/libsndfile'
make[1]: *** [Makefile:3275: install-recursive] Error 1
make[1]: Leaving directory '/ffmpeg-wasm/issue-xx/libsndfile'
make: *** [Makefile:3678: install] Error 2
make: Leaving directory '/ffmpeg-wasm/issue-xx/libsndfile'
emmake: error: 'make -C libsndfile install' failed (returned 2)
```

Is this something to be resolved on emscripten side?

**Comment by jozefchutka** [comment]
SImilarly building ffmpeg fails with these:

```
In file included from ./libavutil/intmath.h:34:
./libavutil/x86/intmath.h:127:16: error: invalid output constraint '+&x' in asm
  127 |              : "+&x"(a) : "xm"(amin), "xm"(amax));
      |                ^
./libavutil/x86/intmath.h:143:16: error: invalid output constraint '+&x' in asm
  143 |              : "+&x"(a) : "xm"(amin), "xm"(amax));
      |                ^
./libavutil/x86/intmath.h:160:16: error: invalid output constraint '+&x' in asm
  160 |              : "+&x"(a) : "xm"(amin), "xm"(amax));
      |                ^
./libavutil/x86/intmath.h:173:16: error: invalid output constraint '+&x' in asm
  173 |              : "+&x"(a) : "xm"(amin), "xm"(amax));
```

related file https://github.com/wide-video/ffmpeg/blob/wide.video/libavutil/x86/intmath.h#L127C14-L127C51

**Comment by sbc100** [comment]
Did this work in the past?     Are you able to build without `-mavx`?

**Comment by jozefchutka** [comment]
I never tried with `-mavx` before. Build works ok without it or with just `-msimd128`

**Comment by sbc100** [comment]
OK, sounds like a genuine bug with `-mavx` then.   It looks like that was added fairly recently in #22430 so its not too unexpected.

BTW, do you have reason to be believe that emulating `-mavx` will be better than just `-msimd128`?

**Comment by jozefchutka** [comment]
I want to compare both. I am using simd for now and have many performance tests in place. Once mavx is working I can do comparision. I thought ffmpeg is a good lib to test

**Comment by sbc100** [comment]
@jiepan-intel can you take a look?

**Comment by jiepan-intel** [comment]
There are two different issue mentioned here, for the first issue, libsndfile build error, it's fixed by [22850](https://github.com/emscripten-core/emscripten/pull/22850), the PR is not merged yet.

For the second issue, Emscripten supports compiling existing codebases that use x86 SSE instructions by passing the -msimd128 flag, and additionally one of the following:
SSE: pass -msse and #include <xmmintrin.h>. Use #ifdef __SSE__ to gate code.
SSE2: pass -msse2 and #include <emmintrin.h>. Use #ifdef __SSE2__ to gate code.
...

Emscripten can compile x86 intrinsic into WASM SIMD intrinsic, but can't compile inline assembly. The file(./libavutil/x86/intmath.h) is written in inline assembly, not intrinsic, so it' will not compile. It's not specific to -mavx flag, -msse/-msse2/-msse3... will faill too.

static av_always_inline av_const double av_clipd_sse2(double a, double amin, double amax)
{
#if defined(ASSERT_LEVEL) && ASSERT_LEVEL >= 2
    if (amin > amax) abort();
#endif
    __asm__ ("maxsd %1, %0 \n\t"
             "minsd %2, %0 \n\t"
             : "+&x"(a) : "xm"(amin), "xm"(amax));
    return a;
}

**Comment by jozefchutka** [comment]
Thank you for prompt response and resolution with https://github.com/emscripten-core/emscripten/pull/22850 . 
I will try to use `--disable-asm` for ffmpeg build the next time I try and see if there are any more `-mavx` related issues.

**Comment by sbc100** [comment]
Lets close this for now then.  Feel free to re-open.
