### ISSUE TITLE
Missing info in 3.1.74 change log

### ISSUE THREAD

**Issue by adamscott** [emscripten-core/emscripten#23178]
In the current changelog, [for 3.1.74](https://github.com/emscripten-core/emscripten/blob/0c3c07f2829f4165c2619ac3dbc7fa19b6c0daa6/ChangeLog.md?plain=1#L24-L39), [there's content missing for one of the changes](https://github.com/emscripten-core/emscripten/blob/0c3c07f2829f4165c2619ac3dbc7fa19b6c0daa6/ChangeLog.md?plain=1#L31). (I added emphasis)

> 3.1.74 - 12/14/24
> -----------------
> - The file system was updated to independently track atime, mtime and ctime
  instead of using the same time for all three. (#22998)
> - Emscripten-generated code will now use async/await internally when loading
  the Wasm module.  This will be lowered away by babel when targeting older
  browsers. (#23068)
> - **Due to the discontinued support for invalid specializations of**
> - `std::basic_string` (https://github.com/llvm/llvm-project/pull/72694), the
  support for `std::basic_string<unsigned char>` was removed from embind.
  (#23070)
> - The minimum supported versions of browser engines that we support were updated
  to versions that support Promise, Fetch and Object.asign APIs, allowing the 
  polyfills for these to be removed.  Chrome 32 -> 45, Firefox 34 -> 40, Safari
  9.0 -> 10.1.  These browser engines version are all over 8 years old now.
  (#23077, #23118)

**Comment by kripken** [comment]
Thanks, looks like there is an unneeded bullet point there, from #23070 

#23181 will fix it.
