### ISSUE TITLE
Race condition: WebAssembly threads freeze when initialized without delay

### ISSUE THREAD

**Issue by ErikSom** [emscripten-core/emscripten#23250]
**Version of emscripten/emsdk:**
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.74 (1092ec30a3fb1d46b1782ff1b4db5094d3d06ae5)
clang version 20.0.0git (https:/github.com/llvm/llvm-project 322eb1a92e6d4266184060346616fa0dbe39e731)
Target: wasm32-unknown-emscripten
Thread model: posix

## Build files:
https://github.com/Birch-san/box2d3-wasm/tree/03bd012746630e3cf0ae51f25126c0f6d427fcb6/box2d3-wasm/shell

## Issue Description
When initializing and immediately executing WebAssembly threads without delay, the application freezes. This appears to be a race condition where the initialization complete event fires before the WASM threads are fully initialized.

## Expected Behavior
The application should run smoothly with threaded execution, regardless of the initial delay.

## Actual Behavior
- With delay=0: Application freezes completely
- With delay=100: Application works as expected

## Runtime examples:
- With delay=0: https://box2d-v3-threading.netlify.app/?threading=1&pyramidheight=50&delay=0
- With delay=100 https://box2d-v3-threading.netlify.app/?threading=1&pyramidheight=50&delay=100

## Related Issues
Similar behavior was reported in: https://github.com/emscripten-core/emscripten/issues/15730#issuecomment-1456960538

**Comment by sbc100** [comment]
This sounds like it could be the well known issue that threads cannot be started without yielding on the main browser thread?  See https://emscripten.org/docs/porting/pthreads.html#special-considerations.   If adding `-sPTHREAD_POOL_SIZE=N` (where N is the number of threads you are trying to start) fixes the issue then this is almost certainly the that issue.

**Comment by ErikSom** [comment]
> This sounds like it could be the well known issue that threads cannot be started without yielding on the main browser thread? See https://emscripten.org/docs/porting/pthreads.html#special-considerations. If adding `-sPTHREAD_POOL_SIZE=N` (where N is the number of threads you are trying to start) fixes the issue then this is almost certainly the that issue.

We are using that, i also had it fixed to a number at some point, still had this problem.

https://github.com/Birch-san/box2d3-wasm/blob/03bd012746630e3cf0ae51f25126c0f6d427fcb6/box2d3-wasm/shell/1_build_wasm.sh#L50

**Comment by sbc100** [comment]
How many threads are you trying to create in total?   Is the freeze on the first thread creation?  Can you perhaps try to reduce the size of the reproducer to something smaller that can more easily reason about?   Can you try removing as many linker settings as possible (for example, can you remove `-sALLOW_MEMORY_GROWTH` and still reproduce the hang?

**Comment by ErikSom** [comment]
@sbc100 , you were correct. I missed the -sPTHREAD_POOL_SIZE=N in my linking step.
Thanks again for your input.

working runtime example:
https://box2d-v3-threading.netlify.app/?threading=1&pyramidHeight=100

**Comment by ErikSom** [comment]
@sbc100 , you were correct. I missed the -sPTHREAD_POOL_SIZE=N in my linking step.
Thanks again for your input.

working runtime example:
https://box2d-v3-threading.netlify.app/?threading=1&pyramidHeight=100
