### ISSUE TITLE
When EXPORTED_FUNCTIONS em++ do not create valid output

### ISSUE THREAD

**Issue by wolfmanfx** [emscripten-core/emscripten#2408]
Hi,

When I use EXPORTED_FUNCTIONS w emsdk-1.16.0 on OSX it does not create a valid output. The output page fails to load when I remove the flag everything works again. I looking for an easy way to bind c++ code to js but embind is not supported anymore with fastcomp and this feature seems somehow broken.
Any ideas what to use instead?

**Comment by hugoam** [comment]
Just ran into this issue. Please add the fact that `_main` needs to be exported to the documentation ?

**Comment by kripken** [comment]
@hugoam - that is documented in `settings.js`. Perhaps it should be documented in other places too, though, was there a specific section you were reading?

**Comment by hugoam** [comment]
I read both these pages while adding cwrap/ccall to my application (but not entirely apparently):
https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html
https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

The `Interacting with code` first example doesn't export `_main` so it's error inducing (I based myself on that one). I just noticed the `_main` issue is mentioned later on on the page, but I didn't get that far, as I used the first example right away.
The `preamble.js` doc only mentions it implicitly (the example indeed exports `_main`). Could be nice to have a warning there too.

The fact that forgetting `_main` simply silently results in a corrupt build without any error message either at link time or at runtime makes it quite hard to track down the issue also.

**Comment by kripken** [comment]
Thanks, and I see what you mean, this can be confusing.

Perhaps if we have a "build an executable" vs "build a shared library" flag, it could help us emit clearer errors or warnings. gcc/clang do error if building an executable without main, so maybe we should too. It would be a breaking change, though.
