### ISSUE TITLE
Best way to tweak environment setup?

### ISSUE THREAD

**Issue by inklesspen** [emscripten-core/emscripten#2415]
I'm attempting to package up an Emscripten-compiled thing as an AMD module for RequireJS, and I want to make a few tweaks to the environment setup stuff at the beginning of the file. Similar detection lines appear in a few files, but I think what actually gets put in the compiled file is in `src/shell.js`.

The first issue is pretty minor: in the `ENVIRONMENT_IS_WEB` block, the code puts the `Module` into `window`; since I'm using AMD modules, I'd rather not do that and instead return the `Module` at the end of my `post.js`.

The second issue is a bit weirder. I'm using this in a node-webkit app, which is essentially both node.js and a browser at the same time. Thus, the environment setup detects node.js's `require` and `process` and goes into `ENVIRONMENT_IS_NODE`, even when I'm loading it using RequireJS in the browser context. This is a pretty niche situation so I'm not expecting you to make a big change to support it; I just want to know the sanest way to override this environment setup stuff.

**Comment by meleyal** [comment]
Running through [browserify](http://browserify.org/) (and I guess [webpack](http://webpack.github.io/)?) has the same issue going into `ENVIRONMENT_IS_NODE` but actually intended for running in a browser.

So any fix would ideally take these tools into account too (as they are [increasingly popular](https://www.google.com/trends/explore#q=require.js%2C%20browserify%2C%20webpack&cmpt=q&tz=Etc%2FGMT-2)).

**Comment by XVincentX** [comment]
:+1: 

I think a good idea would be to let us override the values, something like

```javascript
ENVIRONMENT_IS_NODE = ENVIRONMENT_IS_NODE || typeof(window) === 'object'
```

In that way, we can easily override it using some mechanism. For example, in webpack would be ok to use `DefinePlugin`

```javascript
    pluginsArray.push(new DefinePlugin({
      ENVIRONMENT_IS_WEB: JSON.stringify('production')
    }));
```

**Comment by kripken** [comment]
I would be ok with an option to override these. We could check if `Module['ENVIRONMENT_IS_NODE']`, and so forth, so people could pass it on the Module object (and with the quotes it would work under closure compiler minification).

**Comment by XVincentX** [comment]
That would be really great!
Thanks for the attention.

**Comment by kripken** [comment]
Marking as a good first bug. Overview of how to approach this:

1. Can add the `ENVIRONMENT*` options to `settings.js` (which can be set using `emcc -s ENVIRONMENT*=..`. Then in `shell.js`, adjust all the `var ENVIRONMENT* = ` to check if they were set. This way, we can set them at compile time.
2. Or, if we want to do it at runtime, then we would just check `shell.js` for `Module['ENVIRONMENT_*']` instead.

I'm ok with either way.

**Comment by XVincentX** [comment]
If you're ok with me, I'd go with the latter. Setting them at compile time would force me to create two separate builds (one for `node.js`, one for the `browser`). 

On the other hands, I'd prefer to have a minimal overhead but a single build for my projects.

Agreed?

**Comment by kripken** [comment]
Sure, sounds fine to me. We can always add the other way too at a late date, if people want it.
