### ISSUE TITLE
VS2010 plugin not working - error MSB4044

### ISSUE THREAD

**Issue by jignatius** [emscripten-core/emscripten#2489]
Hi,

I have followed the installation instructions given here but I am having a lot of problems trying to use the VS2010 plugin on Windows. Every time I try to build using the Emscripten platform set I get the following error:

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(30,5): error MSB4044: The "GCCCompile" task was not given a value for the required parameter "GCCToolPath".

I guess this means the 'GCCCompile' variable is not set anywhere. Where should this be set? I have MinGW installed on my machine.

I would appreciate some help.

**Comment by codenat13** [comment]
I get this same error. I just followed the tutorial and I tried building the project in Visual Studio 2010.  The only error that pops up is: error MSB4044: The "GCCCompile" task was not given a value for the required parameter "GCCToolPath". C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets

I checked the path and that file is there.
