### ISSUE TITLE
In optimized build, fs.js looks for $name.js.mem in the cwd instead of same directory as $name.js

### ISSUE THREAD

**Issue by kmaccara2** [emscripten-core/emscripten#2537]
This becomes apparent when running from a different directory.

This sample expects the following directory structure:

``` text
<dir>
  |-> src
  |-> debug
  |-> release
```

The code can be anything.  I created a basic hello_world.cc for this example.  The build commands below are expecting this to be saved as `src/hello_world.cc`

``` c++
#include <iostream>

int main()
{
  std::cout << "hello world" << std::endl;
  return 0;
}
```

Build the debug version:

``` text
em++ -O2 -o release/hello_world.js src/hello_world.cc
```

Build the optimized version:

``` text
em++ -g4 -o debug/hello_world.js src/hello_world.cc
```

Run the debug version and observe no issues.  Though there is no hello_world.js.mem file, so likely an irrelevant step.

``` text
$ node debug/hello_world.js
hello world
```

Run the optimized version and observe that the generated javascript assumes that the hello_world.js.mem file is in the current working directory instead of in the same path from which node invoked it.

``` text
$ node release/hello_world.js

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'hello_world.js.mem'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.read (/home/kmaccara/test/release/hello_world.js:1:905)
    at Object.readBinary (/home/kmaccara/test/release/hello_world.js:1:1172)
    at Object.<anonymous> (/home/kmaccara/test/release/hello_world.js:26:28396)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by whitecolor** [comment]
@kripken 
> When they are emitted, they must be alongside the .js file so it can find it.

As it was said it will try to load from `cwd` not from dir with `.js` file.

**Comment by jleni** [comment]
Yes, I am having the same problem. It is not enough to have them both in the same directory. It seems that the mem file is loaded from `cwd` so unless the working directory is the directory where files are, the file is not found.

**Comment by sijakret** [comment]
yes. seems like the example in the docs just happens to work because in that case the cwd dir and js dir are identical..
