### ISSUE TITLE
Support Objective-C

### ISSUE THREAD

**Issue by ehsan** [emscripten-core/emscripten#254]
I looked into this a bit.  This should be possible given the fact that the clang front-end supports Objective-C.  For the runtime library, we can use Apple's own Objective-C runtime library (http://www.opensource.apple.com/source/objc4/), which is written in C on top of libc.

**Comment by Frityet** [comment]
Apple Objective C is not portable, a better base (which I am trying to get to work) is [ObjFW](https://github.com/ObjFW/ObjFW)
