### ISSUE TITLE
Emscripten 1.21.4 strange error: Error: ENOENT, no such file or directory 'proton.js.mem'

### ISSUE THREAD

**Issue by fadams** [emscripten-core/emscripten#2542]
I've just pulled in the latest incoming and the latest fastcomp/clang on 18 July and recompiled my application. The compilation went OK with no errors, but when I run my app I'm seeing:

```
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'proton.js.mem'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.d.read (/home/fadams/qpid/fadams-javascript-binding/node_modules/qpid-proton/lib/proton.js:73:301)
    at Object.d.readBinary (/home/fadams/qpid/fadams-javascript-binding/node_modules/qpid-proton/lib/proton.js:73:466)
    at /home/fadams/qpid/fadams-javascript-binding/node_modules/qpid-proton/lib/proton.js:248:82
    at Object.<anonymous> (/home/fadams/qpid/fadams-javascript-binding/node_modules/qpid-proton/lib/proton.js:250:119)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

```

This is a new one on me, I've never seen the proton.js.mem thing before (my library compiles to proton.js)

Any idea what has happened?

**Comment by whitecolor** [comment]
It is 2017 -) Running in node it looks up file in CWD, not near js file `https://github.com/kripken/emscripten/issues/2537`

I build using `-o lib/lib.js`, and `lib/lib.mem` is here, but it looks up it in just in cwd, not 'lib'

**Comment by CMCDragonkai** [comment]
Is this separation between `.js` and `.js.mem` relevant to libraries only intended to be used by Node.js and other server-side JS. Because I was going to use the outputted module with rollup and rollup would produce a single JS file, but I'm not sure it would bundle up the `.js.mem` files as well.

**Comment by whitecolor** [comment]
By default currently in a browser it will try load memory file using standard `XMLHttpRequest`.

My solution to load with webpack as a part of a bundle:

In the `output-file-name.js` replace async browser loader code which starts with:
```js
addRunDependency("memory initializer");
  var applyMemoryInitializer = (function(data) {
 ....
```
with the code:
```js
var data = require('./output-file-name.js.mem');
if (data.byteLength) data = new Uint8Array(data);
HEAPU8.set(data, Runtime.GLOBAL_BASE);
```

And use `arraybinary-loader` for this file. Works fine.

@kripken I believe there is need to add some param to allow using `require` instead of `XMLHttpRequest` for loading memory file.
