### ISSUE TITLE
hello_world.cpp generates much more JavaScript than necessary

### ISSUE THREAD

**Issue by abarth** [emscripten-core/emscripten#2545]
When compiling hello_world.cpp, the generated JavaScript contains thousands of lines of code, the vast majority aren't needed to execute hello_world.js.  Instead, the generated JavaScript should contain only what's needed.

(I'm a new emscripten contributor, and I'm filing this bug mostly to ask whether work on this topic would be valued by the emscripten community.  If so, I'll be happy to send pull requests.  Thanks!)

**Comment by gagern** [comment]
I like the fact that you are also thinking about “small emscripten-compiled projects”, since that's my main use case. Anyway, I've [just found out](http://stackoverflow.com/q/29452006/1468366) that a tiny program using `std::shared_ptr` will result in 400k of code (100k after compression), with a lot of code from the I/O subsystem and locale management, even though none of this should ever get called, particularly with `DISABLE_EXCEPTION_CATCHING=1` so there should be no exception text formatting or similar. The example I have is

```cpp
#include <memory>
int main(int argc, char** argv) {
  std::shared_ptr<int> sp(new int);
}
```

```sh
em++ -std=c++11 -s DISABLE_EXCEPTION_CATCHING=1 -s NO_FILESYSTEM=1 \
     -s NO_BROWSER=1 -s NO_EXIT_RUNTIME=1 -O3 -o foo.js foo.cc
```

The way I see it, most of this is just functions which are included since they are placed in virtual function tables. Do we have any chance of detecting and dropping the unneeded ones there? Do you even agree with my assessment? Should I open a new ticket for that aspect?

**Comment by kripken** [comment]
Eliminating code through function pointers is very hard, but perhaps LLVM can do it with lto, does that help?

**Comment by gagern** [comment]
Adding `--llvm-lto 3` *increases* the size by 20k. Not a win.

**Comment by kripken** [comment]
It's likely an issue that we should take upstream then. If we can narrow down what is not being eliminated, and why we think it should be eliminated, at the LLVM IR level in as small a testcase as we can, then we can suggest it to LLVM.

**Comment by gagern** [comment]
I had a look at the `llvm-dis`-assembled version of the `--save-bc`-generated output. Seems most of the stuff in question comes from `ios_base::Init::Init()` which is used to initialize the global `__start_std_streams` object. This global initializer is run whenever something links to the `libcxx.bc` library, e.g. also for this:

```cpp
#include <algorithm>
int main(int argc, char** argv) {
  int a[] = {3, 5, 2};
  std::sort(a, a + 3);
  return a[0];
}
```

The way I see it, this `ios_base::Init::Init` in `iostream.cpp` is mainly responsible for initializing `cin, cout, cerr`. So if you were to provide a version of the library where these symbols don't exist, or are initialized lazily, then we might stand a better chance. Of course, once someone starts using an I/O stream, `ios_base::init` will do a `::new(&__loc_) locale`, which leads to pretty much the same initialization. So people would be safe as long as they don't use ios.

----

If we want to take this upstream, here is a small reproducing example:

```cpp
struct Base { virtual int foo() = 0; };
struct Derived1 : public Base { int foo() { return 15263; } };
Base* b;
struct Init { Init(); } init_guard;
Init::Init() { b = new Derived1; }
int main(int argc, char** argv) { }
```

Here the implementation `Derived1::foo` is preserved in the code even though noone ever calls this either directly or indirectly. Looking at the IR, I see `_ZTV8Derived1`, the virtual function table for `Derived1`, where this function is entered. The global constructor then stores the address of that list in the memory returned from the `new` operator. Perhaps one aspect of this problem could be that LLVM sees this `new` operator just as any other external function. That function returns a pointer, we write to that pointer, and theoretically there could be someone somewhere else outside our control who observes what we wrote and calls the function using that pointer. So the function has to be preserved. I'm just guessing, but this sounds plausible to me.

I guess the kind of dead code elimination I have in mind would require more knowledge about C++. It has to look at the name of that constant and figure out that it's a `vtable`. It has to identify calls to virtual functions. And – probably hardest of all – it has to work out inheritance to see which virtual function calls could be referring to which virtual functions. That last part sounds *really* hard if all you have is the LLVM IR.

----

So unless someone comes up with an idea, I consider the approach of a stripped-down or lazily-initializing standard library to be more promising. I just had a look at `system_libs.py`, and see that you are auto-detecting which libs to use. So if we can get things split up the right way, we might move all the locale and ios and so on stuff into one library, and the rest into a different library, and things will work out automagically.

**Comment by kripken** [comment]
Splitting is indeed one option, but cc'ing @sunfishcode for thoughts on LLVM optimizing this somehow.
