### ISSUE TITLE
emscripten has slightly odd default values for some environment variables

### ISSUE THREAD

**Issue by absmall** [emscripten-core/emscripten#2549]
emscripten sets some default values for environment variables:
      // Set default values. Use string keys for Closure Compiler compatibility.
      ENV['USER'] = 'root';  
      ENV['PATH'] = '/';  
      ENV['PWD'] = '/';  
      ENV['HOME'] = '/home/emscripten';  
      ENV['LANG'] = 'en_US.UTF-8';  
      ENV['_'] = './this.program';                    

The default values for HOME and LANG are not what I would have expected. For LANG, it seems strange to default to English - I happen to speak English, but I would not expect this is a reasonable default for all users of programs compiled with emscripten - would "C" make more sense? It's a bit more neutral. For HOME, this is a directory that is not very likely to exist. Would "/" make more sense?

**Comment by alecazam** [comment]
I can't seem to get toupper/tolower to work in Emscripten, but haven't delved too deeply yet. I don't think setting a non UTF-8 default was great for developers.   I set the locale, and that doesn't help either with my test case (although this code works on OSX).  

We had UTF8 code that was expecting these routines to just work.  Try the following with and without setlocale called.  This is Cyrllic A converted to lowercase A, and vice versa.

  setlocale(LC_ALL, "en_US.UTF-8");

  int upperCaseA = 0x0410;
  int lowerCaseA = 0x0430;
  ASSERT(lowerCaseA == tolower(upperCaseA));
  ASSERT(toupper(lowerCaseA) == upperCaseA);

**Comment by alecazam** [comment]
I should add this is with Emscripten 1.36.1

**Comment by alecazam** [comment]
It turns out that even after setting the locale to UTF-8, that Emscripten's toupper/tolower still don't work, so we'll have to roll our own solution here instead of using those.
