### ISSUE TITLE
Functions to asyncify

### ISSUE THREAD

**Issue by coolwanglu** [emscripten-core/emscripten#2599]
Some functions were dummies without Asyncify, now we can implement them with asyncify.

Here's a (might not complete) candidate list:
### sleep function
- `glfwSleep`
- `nanosleep`
- `clock_nanosleep`
- `sleep`
- `std::this_thread::sleep_until`
- `std::this_thread::sleep_for`
- `SDL_Delay`
### IO
- `select`
- `pselect`
- `poll` (done)
- `fgetc`
- `getc`
- `getchar`
- Sync IDBFS
### Event
- `SDL_WaitEvent`
### Emscripten
- `emscripten_wget`  (done)
- `emscripten_sleep` (done)
### Notes

`fgetc`, `getc` only need to transform when called with `stdin`, i.e. the case of `getchar`, since it might be frequently used, maybe we don't want to transform it, instead, we can show a runtime warning, to tell the user to user to use a (transformed) `getchar` instead of `fgetc(stdin)`.

**Comment by OCTAGRAM** [comment]
Would be interesting to compare it with kerneis/cpc (Continuation Passing C). Is it also producing 10x code like asyncify? I noted that CPC has no longjmp support, and that's a huge problem for me personally, but maybe it can be implemented.
