### ISSUE TITLE
emscipten does not work with rhino

### ISSUE THREAD

**Issue by user1095108** [emscripten-core/emscripten#2601]
Rhino is a js interpreter from Mozilla it supposedly supports JS 1.7. The problem is in a regular expression:

  var sourceRegex = /^function\s_(([^)]_))\s_{\s_([^_]_?)[\s;]_(?:return\s_(._?)[;\s]_)?}$/;
  function parseJSFunc(jsfunc) {
    // Match the body and the return value of a javascript function source
    var parsed = jsfunc.toString().match(sourceRegex).slice(1);
    return {arguments : parsed[0], body : parsed[1], returnValue: parsed[2]}
  }

Which does not match anything (i.e. match() returns null), hence the interpretation stops with:

js: "ld.js", line 651: uncaught JavaScript runtime exception: TypeError: Cannot call method "slice" of null
        at ld.js:651 (parseJSFunc)
        at ld.js:659
        at ld.js:577

**Comment by rodneyrehm** [comment]
Regarding typed arrays support and little- vs big-endianess in Rhino see mozilla/rhino#265

**Comment by etlovett** [comment]
FYI, this may have happened to be fixed by the change that fixed #4111.
