### ISSUE TITLE
Websocket to connection with pathname and port number does not work

### ISSUE THREAD

**Issue by maugf214** [emscripten-core/emscripten#2610]
When connecting to a WebSocket address which includes both a pathname and a port number, the port number is appended to the wrong part of the URL. For example, connecting to `localhost/example` on port 8080 will use the URL `localhost/example:8080` rather than `localhost:8080/example`. I'm not sure if this is a feature that is supposed to be supported as it is not directly analogous to connecting to a TCP socket, as TCP socket addresses do not have a path name. However, I think it would be fairly simple to add support, and would be very useful.

```
diff --git a/src/library_sockfs.js b/src/library_sockfs.js
index 2364146..99379e6 100644
--- a/src/library_sockfs.js
+++ b/src/library_sockfs.js
@@ -147,7 +147,8 @@ mergeInto(LibraryManager.library, {
             }

             if (url === 'ws://' || url === 'wss://') { // Is the supplied URL config just a prefix, if so complete it.
-              url = url + addr + ':' + port;
+              addressComponents = addr.split('/');
+              url = url + addressComponents[0] + ":" + port + "/" + addressComponents.slice(1).join('/');
             }

             // Make the WebSocket subprotocol (Sec-WebSocket-Protocol) default to binary if no configuration is set.

```

**Comment by promethe42** [comment]
How can we use this in C?

**Comment by promethe42** [comment]
Here you go:

```
emscripten_run_script(std::string("Module['websocket']['url'] = '" + uri + "'").c_str());
```

**Comment by trivigy** [comment]
Can anyone give a more complete example please? In the examples set in tests the connection is made via inet_pton() which does not allow for a path to be passed. I am not sure how to apply what @promethe42  shows.
