### ISSUE TITLE
Linker eating functions in JSMESS again

### ISSUE THREAD

**Issue by DopefishJustin** [emscripten-core/emscripten#2619]
Compare https://github.com/kripken/emscripten/issues/131#issuecomment-7089116

Getting a bunch of warnings about unresolved symbols when compiling JSMESS for the Tandy 1000 with current Emscripten incoming:

```
/0/home/dfjustin/jsmess/third_party/emscripten/emcc  -O3 -s DISABLE_EXCEPTION_CATCHING=0 -s NO_EXIT_RUNTIME=1 -s ASSERTIONS=0 -s COMPILER_ASSERTIONS=1 -s FORCE_ALIGNED_MEMORY=1 -s TOTAL_MEMORY=67108864       -s EXCEPTION_CATCHING_WHITELIST='["__ZN15running_machine17start_all_devicesEv"]' -s EXPORTED_FUNCTIONS="['_main', '_malloc', '__Z14js_get_machinev', '__Z9js_get_uiv', '__Z12js_get_soundv', '__ZN10ui_manager12set_show_fpsEb', '__ZNK10ui_manager8show_fpsEv', '__ZN13sound_manager4muteEbh', 'SDL_PauseAudio']" -g2 -s ASSERTIONS=2 -s SAFE_HEAP=1 -s DEMANGLE_SUPPORT=1 /0/home/dfjustin/jsmess/third_party/mame/messtandy1t.bc -o /0/home/dfjustin/jsmess/build/tandy1t/messtandy1t.js --pre-js /0/home/dfjustin/jsmess/build/tandy1t/pre.js --post-js /0/home/dfjustin/jsmess/templates/default/post.js
warning: unresolved symbol: _ZN17centronics_device11write_data7Ei
warning: unresolved symbol: pthread_attr_setdetachstate
warning: unresolved symbol: _ZN17centronics_device12write_autofdEi
warning: unresolved symbol: _ZN17centronics_device11write_data4Ei
warning: unresolved symbol: _ZN17centronics_device10write_initEi
warning: unresolved symbol: _ZN17centronics_device11write_data6Ei
warning: unresolved symbol: _ZN17centronics_device15write_select_inEi
warning: unresolved symbol: _ZN17centronics_device11write_data1Ei
warning: unresolved symbol: SDL_UnlockYUVOverlay
warning: unresolved symbol: _ZN17centronics_device11write_data3Ei
warning: unresolved symbol: SDL_CreateYUVOverlay
warning: unresolved symbol: _ZN17centronics_device11write_data0Ei
warning: unresolved symbol: _ZN17centronics_device12write_strobeEi
warning: unresolved symbol: pthread_create
warning: unresolved symbol: SDL_GL_LoadLibrary
warning: unresolved symbol: SDL_LockYUVOverlay
warning: unresolved symbol: _ZN17centronics_device11write_data5Ei
warning: unresolved symbol: SDL_DisplayYUVOverlay
warning: unresolved symbol: SDL_FreeYUVOverlay
warning: unresolved symbol: _ZN17centronics_device11write_data2Ei
warning: unresolved symbol: CENTRONICS
warning: unresolved symbol: CENTRONICS_COVOX
warning: unresolved symbol: CENTRONICS_COVOX_STEREO
warning: unresolved symbol: CENTRONICS_PRINTER
warning: unresolved symbol: _ZTI17centronics_device
```

The pthread and SDL stuff is expected but the centronics functions seem to be getting munched by the linker - they are compiled into libbus.a but not the final binary.

To reproduce, use the following files: http://interbutt.com/temp/tandylinkerbug.zip

```
$ llvm-nm libbus.a | grep _ZN17centronics_device11write_data7Ei
         T _ZN17centronics_device11write_data7Ei
$ emcc -s version.o mess.o drivlist.o tandy1t.o genpc.o pc_t1t.o libosd.a libbus.a liboptional.a libemu.a libdasm.a libutil.a libexpat.a libsoftfloat.a libjpeg.a libflac.a lib7z.a libformats.a liblua.a libsqlite3.a libweb.a libz.a libocore.a libportmidi.a -o messtandy1t
$ llvm-nm messtandy1t | grep _ZN17centronics_device11write_data7Ei
         U _ZN17centronics_device11write_data7Ei
```

**Comment by xxuejie** [comment]
Sorry to bump this up, but I think I'm hitting the same problem while trying to upgrade [webruby](https://github.com/xxuejie/webruby).

In the original `.o` file, the symbol(`mrb_init_symtbl`) exists:

```
$ llvm-nm symbol.o | grep mrb_init_symtbl
         T mrb_init_symtbl
```

**NOTE**: all the commands here are for demostration purposes and are not runnable, I can provide all the object files, archive files and bitcode files if needed.

Then we create an archive file with the following-like command:

```
$ emar rs libmruby.a <other files...> symbol.o <other files...>
```

In the archive file, it at least appears that this function exists:

```
$ llvm-nm build/mruby/emscripten/lib/libmruby.a | grep mrb_init_symtbl
         U mrb_init_symtbl
         T mrb_init_symtbl
```

Then we link a few archive files to the final `.bc` file:

```
emcc -o mrbtest.bc <archive files...> libmruby.a <archive files...>
```

At this level, I can confirm the order of archive files is correct: all functions that depend on `mrb_init_symtbl` appears after libmruby.a file.

However, at this point, the function appears to be gone:

```
$ llvm-nm mrbtest.bc | grep mrb_init_symtbl
         U mrb_init_symtbl
```

On more thing is: if we try to extract the `.a` file:

```
emar x libmruby.a
```

And do `llvm-nm` on the extracted `symbol.o` file, we can see the actual function is gone:

```
llvm-nm extracts/symbol.o | grep mrb_init_symtbl
(nothing shows up here)
```

So, is it true that we are still limiting to the solution of not using `.a` file? Any rough idea on other ways that this can be solvable?

Thanks!

**Comment by xxuejie** [comment]
In case it might be useful, I've uploaded all the object files, archive files and the final JS files in this archive: http://cl.ly/3U3e2p2C0l2Q. Please refer to the `readme.txt` file included for how to locate each file as well as how to run commands to generate files in each step.

Let me know if more information is needed!

**Comment by kripken** [comment]
The problem in this testcase is that you create an archive with `A/symbol.o` and `B/symbol.o`, but llvm-ar creates an archive with entries `symbol.o, symbol.o`, i.e., only the basenames, no path info. When extracting them, the last one overwrites the first. The first has that symbol that is missing, so the final linked output doesn't have it.

This might be a bug in llvm-ar? I'm not sure if llvm-ar is supposed to add relative paths if you provide them (as is the case here). Can you verify that doing this with the system ar does not in fact have this bug? If so we should file an issue on llvm.

I added some code to warn if we see duplicate entries in an archive, in which case the earlier ones will get overwritten, which seems like always a dangerous thing.

**Comment by kripken** [comment]
Worth checking if that warning shows up on MESS, might indicate it is the same issue, which seems likely.

**Comment by xxuejie** [comment]
@kripken Yes, I can confirm this is working using native `ar`, since this is already part of the mruby build process.

Or should this be classified as an undefined behaviour?

**Comment by kripken** [comment]
I honestly don't know what is defined and undefined behavior for `ar`. However, I tested `ar` on linux here, and it works identically to how `llvm-ar` does. So `llvm-ar` seems fine.

````
$ gcc -c tests/hello_world.c -o tests/a.o
$ file a.o
a.o: ELF 64-bit LSB  relocatable, x86-64, version 1 (SYSV), not stripped
$ ar rs a.a tests/a.o
ar: creating a.a
$ ar t a.a
a.o
$ cd waka
$ ar xo ../a.a
$ ls
a.o
````

So only the basename is retained, and files are dumped in the current dir, so ones with identical basenames trample previous ones.

Are you on mac? Perhaps mac `ar` works differently, and the build system is not cross-platform?

We could work around this issue if we could extract files by their index number, and not by name. But I don't see an option for that on `ar` or `llvm-ar`...

**Comment by DopefishJustin** [comment]
Definitely the issue with MESS:

```
WARNING  root: loading from archive /0/home/dfjustin/jsmess/third_party/mame/obj/sdl/libemu.a, which has duplicate entries (files with identical names). this is dangerous as only the last will be taken into account, and you may see surprising undefined symbols later. run |llvm-ar t archive.a| to see the list of entries
WARNING  root:    duplicate: none.o
WARNING  root:    duplicate: generic.o
```

**Comment by kripken** [comment]
Thanks, good to know that with the simpler testcase we at least know what the problem is now. Although, given that `ar` works the same, something is still unclear.

**Comment by xxuejie** [comment]
For the native `ar`, I think the case is: if are are extracting all files at once, the latter file will override the former file with the same name. However, if we are extracting only one file, we can preserve the former file:

```
$ nm build/clang/src/symbol.o | grep mrb_init_symtbl  # original object file
0000000000000cf0 T _mrb_init_symtbl

$ nm build/clang/lib/libmruby.a | grep mrb_init_symtbl    # archive file
                 U _mrb_init_symtbl
0000000000000cf0 T _mrb_init_symtbl

$ ar x build/clang/lib/libmruby.a symbol.o    # extract one file
$ nm symbol.o | grep mrb_init_symtbl
0000000000000cf0 T _mrb_init_symtbl
```

So this still looks like a bug of `llvm-ar` to me.

And yes, I'm on a mac, but I can confirm the same behaviour occurs on Linux(tested on a Linode VM).

In mruby's case, the problem will be gone if we avoid using `.a` files completely, in other words, specifying all object files in the final linking phase will work. Not sure if that applies to MESS though.

**Comment by kripken** [comment]
But if you extract a single file, using the basename (which is all there is at this point), then you can only extract one of the two? How can you specify the other?

**Comment by xxuejie** [comment]
I don't have an answer for that, sorry, Google tells us that maybe we have to use more trickier [way](http://stackoverflow.com/questions/9199806/how-can-i-extract-static-libs-containing-repeated-object-files), so it makes me wonder if this should be categorized as "undefined behavior" rather than "bug".

**Comment by kripken** [comment]
Based on that, it seems like `ar` will have the same problem as `llvm-ar`. In which case, how do these build systems work natively? The exact same issue should arise. The native build systems must be doing something differently, just tracing the commands should show how.

**Comment by xxuejie** [comment]
Well, here's the complete build steps of mruby on a native platform: https://gist.github.com/xxuejie/915269285747b66a796b

Basically what it does is the following 3 steps:

1. Compile every `.c` file in to `.o` file.
2. Archive a set of `.o` files(including multiple `symbol.o` files with the same name but different path) into a single `.a` file.
3. Link some other `.o` files with the `.a` file to create a single executable, which will work.

I guess the case here is that `ar` does include symbols from every file on the system even though they might contain duplicate names. It is only the extraction phase of `ar` that is not working well: like the standard command interface has limitations on extraction of files with duplicate name.

**Comment by kripken** [comment]
Ah, ok, so it sounds like `ar x`, the commandline extraction, is faulty - in both `ar` and `llvm-ar`, while the native linker apparently has it's own logic to handle archives, which is better then `ar x`. I suppose we need to do something similar.

**Comment by xxuejie** [comment]
If `llvm-ar` has a bug handling this(from my test results, `llvm-ar` won't preserve symbols from the former file, even if 2 files are shown in `llvm-ar t`), can we do anything at the linker level?

**Comment by kripken** [comment]
Yes, the only option is to write our own code to extract files from archives, I suppose. Perhaps like the link you posted above, I didn't take a close look yet though.

**Comment by kripken** [comment]
@sunfishcode noticed the `N` option, which in `ar` is precisely how one can actually access multiple files with the same names. This seemed like a perfect solution here... except that it was removed

http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20130708/180847.html

````
Remove the 'N' modifier from llvm-ar.

* It is not present on OS X.
* It is untested.
* It is not needed for using ar in a build system.
````

So this was intentionally removed from llvm-ar, and I'm fairly sure there's no point in filing a bug to ask for it to be re-implemented. So LLVM is not going to help us here.

The only solution seems to be to write a new archive file parser. If someone can find a nice standalone one, that seems like a possibility. Writing one from scratch sounds like a bad idea - we'd need to debug it on multiple platforms, etc. etc.

**Comment by kripken** [comment]
I can't find a workaround here. Deleting entries from a `.a` does not let us read them all out one by one, even slowly. And there does not seem to be a good standalone ar handler.

I pushed a test to verify that we issue a proper warning on this. As the workaround is fairly simple once the problem is known - rename a few source files, as mentioned in the warning text - I think that's the best we can do here.

**Comment by xxuejie** [comment]
Thanks for the help! Webruby now works by ignoring the `.a` file and links all `.o` files directly. I will verify if I can reproduce the same bug with LLVM 3.5 and report it back to mruby. What's strange, it seems `llvm-ar` in LLVM 3.5 distribution does not play well with its own linker out of box.

**Comment by DopefishJustin** [comment]
There ended up being too many affected files in MESS for renaming to be a good workaround so I used some makefile tricks to use .bc files instead of .a: https://github.com/mamedev/mame/commit/31bc7f4bbb8f805e1f05623d9d8d784750de92ad

**Comment by bkaradzic** [comment]
I ran into this issue only with emscripten toolchain. Can't you fix it by adding random numbers at the end of filename that goes into archive? Does it really matter what name is inside archive?

**Comment by kripken** [comment]
Well, if the user inserts `file.o` and later tries to extract that entry by name, then if we added random characters that would be broken. That is definitely an interesting idea, though - perhaps it's better to have that broken than the current problem? Perhaps it's very rare for people to manually extract from archives themselves, and only the linker does?

**Comment by bkaradzic** [comment]
Another idea is that once you start extracting those files get their hash, and then use hash to identify identical files, not by name. I have case where files have identical name but their content is completely different. I assume you want to remove redundant content when linking and you're using name to identify that which causes this issue.

**Comment by kripken** [comment]
The problem is that llvm-ar can only extract **one** file out of all the files with identical basenames in the archive. The only way to fix it would be to modify llvm-ar, however it already had such an option and they removed it, so I'm not sure they would even be interested.

**Comment by bkaradzic** [comment]
Ah ok, `emar` maybe then needs to add some value to make names unique. I don't think it's ever needed to extract exact file-name anyway (not even possible as you can only extract one with given name).

**Comment by kripken** [comment]
It is possible to extract individual files by name, and on native ar's except for OS X, apparently even when there is an identical basename. It's possible no one uses this functionality, though.

Making the names unique isn't trivial though - should the same full path lead to the same unique name? or not? I'm not sure.

Regardless, if this would be a useful option for people, I'm not opposed. But it would need to be an option and not the default behavior, I think.

**Comment by bkaradzic** [comment]
I can pack foo/bar.o and bar/bar.o into the same library and not have any issues linking on any platform other than Emscripten. Solution like foo_bar.o, bar_bar.o would be acceptable too.

**Comment by kripken** [comment]
Let's move discussion to #2142 which is still open and focused on the last issue here. I'll give an update in there.
