### ISSUE TITLE
LLVM ERROR: invalid vector instr

### ISSUE THREAD

**Issue by rodrigob** [emscripten-core/emscripten#2645]
I am trying to compile my first emscripten project, I am currently stuck with the error

```
%call = call <4 x float> @_ZL1cIDv4_fET_f(float 0x3FDB8E8640000000)
LLVM ERROR: invalid vector instr
```

the problem seems related to pull #2405 however I am failing to get things running.
I updated the emsdk to use the `incoming` branch however I still have the same error.
Any idea of how to fix this or go around it ?

```
emsdk list

The following individual tools exist:
           clang-incoming-32bit         INSTALLED
     *     clang-incoming-64bit         INSTALLED
           clang-master-32bit           INSTALLED
           clang-master-64bit           INSTALLED
           emscripten-1.21.0        
    (*)    emscripten-incoming          INSTALLED
           emscripten-master            INSTALLED


The following Emscripten SDK versions are available:
         sdk-incoming-32bit         INSTALLED
    *    sdk-incoming-64bit         INSTALLED
         sdk-master-32bit           INSTALLED
         sdk-master-64bit           INSTALLED
```

```
 emcc --version
emcc (Emscripten GCC-like replacement) 1.22.1 (commit 65136b45a5dd29f3426a146e229eba5e0b89d030)
```

**Comment by anirudhsasikumar** [comment]
I'm running into a similar error and was wondering if there was some easy way to check which C++ file has the offending code. This is the error I get:

```
%112 = uitofp <4 x i16> %111 to <4 x float>, !dbg !644783
LLVM ERROR: invalid vector instr
```

I've tried putting an error into all the header files in `system/include/SSE` and can confirm those aren't getting pulled in.

Any other tips on narrowing down to the exact header or C++ file that has the SIMD value?
