### ISSUE TITLE
Keyboard events get captured for the whole document when using SDL

### ISSUE THREAD

**Issue by jplatte** [emscripten-core/emscripten#2668]
I added a textarea to a document with an Emscripten SDL canvas no it today, and wasn't able to input text in it. I `grep`ed through the generated .js and found [this](https://github.com/kripken/emscripten/blob/46d00a9b4f825955cbc5588285db92d237525074/src/library_sdl.js#L1224).

It's nice and also sufficient for what I do at the moment, that I can just set `Module.doNotCaptureKeyboard` to true to make the textarea work, though I don't think this is the best solution.

Wouldn't it be possible to (optionally?) add event listeners for `Module.canvas` instead of the whole document?

**Comment by garrettmaring** [comment]
What is the current standard here?
