### ISSUE TITLE
Default to erroring out link stage if there are any remaining undefined symbols.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#2714]
Similar to issue #2713, we would like to mature towards having Emscripten linker behave conformant to how native linkers work. The native linkers fail with an error if linking to an executable results in any undefined symbols that were not found. Currently by default, Emscripten will only issue a warning, but still continue and return with a success and error code of 0.

We should instead behave like native linkers do, and by default raise an error if the link step finishes with undefined symbols. This error should be presented with a helpful error message that instructs how the developer can acknowledge that the symbols are expected to be missing (e.g. "Pass the linker flag -s ERROR_UNDEFINED_SYMBOLS=0 to hide this warning").

**Comment by juj** [comment]
We have this now implemented, but we don't yet default to `-s ERROR_UNDEFINED_SYMBOLS=1`. Also, we have warned users in https://groups.google.com/d/msg/emscripten-discuss/1bB-OnNmM0g/40bxdgOkBwAJ that at some point `-s ERROR_UNDEFINED_SYMBOLS=1` will become the default.

I think with a good error message like `"Pass the linker flag -s ERROR_UNDEFINED_SYMBOLS=0 to revert to old behavior"` we should be ready to flip this now?

**Comment by kripken** [comment]
Sounds ok to me.
