### ISSUE TITLE
Add support for conditionally excluding all handwritten JS code for SDL.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#2730]
Currently we have SDL code in at least `src/library_sdl.js` and some also in `src/library_browser.js`. Alon added link flags `-s NO_FILESYSTEM=1` and `-s NO_BROWSER=1` in relation to https://github.com/kripken/emscripten/issues/2545 , and in the same style, we should add a link flag `-s NO_SDL=1` or similar, which would strip out all the handwritten JS code that implements Emscripten's SDL 1.3.

The motivation for this is with our SDL 2 implementation, which seems to have some bits still using these handwritten JS paths, so this flag would help explicitly confirm that the SDL 2 port would properly use only the SDL2 code. Also, this would secondarily benefit other codebases to allow them explicitly opt out of linking to SDL at all.

**Comment by kripken** [comment]
Note that using SDL_mixer from our JS code is possible with SDL2. So this flag would only need to limit core SDL stuff, I suppose.
