### ISSUE TITLE
fflush does not flush stdout or stderr in browser environment.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#2770]
Place the following code in the file `test.cpp`:

```
#include <stdio.h>

int main()
{
    printf("hello!");
    fflush(stdout);
    fprintf(stderr, "hello from stderr too!");
    fflush(stderr);
}
```

and compile with `emcc test.cpp -o test.html -s NO_EXIT_RUNTIME=1`. Then run the resulting `test.html` in the browser.

Observed: No text is printed.

Expected: fflush should flush, and both texts should be visible.

**Comment by xloem** [comment]
It looks to me like the solution to this would be to move the endline handling to the javascript side.  So that '\n' is sent normal to javascript.  Also note I've put some effort into implementing xterm at https://github.com/xloem/emterm which provides better for flushes of partial lines.

**Comment by vadimkantorov** [comment]
@kripken Also hit the same issue while using busybox for an in-browser terminal application (https://busytex.github.io).

In particular, busybox clear doesn't print a new line: https://github.com/brgl/busybox/blob/master/console-tools/clear.c

This is aggravated by the fact that I don't let the emscripten module clean up and exit, and instead I reset the module's memory myself.
