### ISSUE TITLE
Link error 

### ISSUE THREAD

**Issue by stefanhusmann** [emscripten-core/emscripten#2786]
Under Arch Linux I get a link error 

../../lib/libLLVMSupport.a(Allocator.cpp.o): In function `llvm::BumpPtrAllocator::Allocate(unsigned long, unsigned long)':
/home/haawda/paketierung/maintained_by_me/emscripten-git/src/emscripten-fastcomp/lib/Support/Allocator.cpp:(.text+0x286): undefined reference to`__msan_allocated_memory'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
utils/TableGen/CMakeFiles/llvm-tblgen.dir/build.make:887: recipe for target 'bin/llvm-tblgen' failed

Unrelated to this error, I think  there is a typo in  emscripten-fastcomp/lib/Bitcode/NaCl/Writer/CMakeLists.txt

sed -i 's+intinsics_gen+intrinsics_gen+' \
      $srcdir/emscripten-fastcomp/lib/Bitcode/NaCl/Writer/CMakeLists.txt

**Comment by CoolOppo** [comment]
I have the same issue when building with Clang version `3.5.1-1~exp1~gd~u` on Ubuntu 14.10. I will have to try using GCC I guess, although it would be nice to be able to build this without it.
