### ISSUE TITLE
Automatically wrap EXPORTED_FUNCTIONS

### ISSUE THREAD

**Issue by daurnimator** [emscripten-core/emscripten#2794]
Let's automatically wrap everything exported.

> 20:32:42 < azakai|2_> we don't want to wrap everything by default, as it adds overhead
> 20:32:59 < azakai|2_> although we could wrap EXPORTED_FUNCTIONS, hmm
> 
> 20:39:05 < azakai|2_> daurnimator: i think it's a reasonable idea to auto-wrap some things, but best to file an issue if you want that, we'd need to discuss how it would work, how it would fit in with things like the embind and the webidl bindings generator, etc

**Comment by kripken** [comment]
This issue regards `ccall` and `cwrap` (took me a few minutes to remember!).

**Comment by daurnimator** [comment]
.

**Comment by daurnimator** [comment]
.

**Comment by kripken** [comment]
Embind and/or a future improved version of it is probably what makes most sense for this, closing as this was about ccall/cwrap specifically.
