### ISSUE TITLE
mousewheel direction reversed in glut (chrome)

### ISSUE THREAD

**Issue by rsturgell** [emscripten-core/emscripten#2864]
I think this is the result of 

https://github.com/kripken/emscripten/commit/2ef851bfff5e720e363fc85f0f29ced5486971fe

I'm now getting button=4 for "up" and button=3 for "down". Looks like that change reversed the sign in  getMouseWheelDelta but kept the usage the same in library_glut onMouseWheel, so it makes sense that it reversed which button is reported.

**Comment by 00v1** [comment]
Still not fixed.

**Comment by usagi** [comment]
It's not only glut problem, I have check the same behavior in glfw3(em-1.29).
// I was fix a like the problem in GLFW2 at #2304 . The problem is regression.
