### ISSUE TITLE
stdout is not flushed (in safari)

### ISSUE THREAD

**Issue by 4ntoine** [emscripten-core/emscripten#2959]
```
#include <stdio.h>

int main() {
    char name[64];
    printf("what is your name ?\n");
    scanf("%s", name);
    printf("hi, %s\n", name);
}
```

in chrome input dialog is shown when printf output is done and visible, but in safari printf output is not actually done

![2014-11-02 12 02 33](https://cloud.githubusercontent.com/assets/846671/4874534/92692146-625e-11e4-8375-75b2448fa58e.png)

![2014-11-02 12 01 33](https://cloud.githubusercontent.com/assets/846671/4874535/98c6b332-625e-11e4-9abf-b71e515e9d64.png)

in safari the first printf is done after input is done.

![2014-11-02 12 01 45](https://cloud.githubusercontent.com/assets/846671/4874537/af158bea-625e-11e4-9347-56bf1d7be0d5.png)

Discussion https://groups.google.com/forum/#!topic/emscripten-discuss/5EN4FxJwYUU

**Comment by grantrostig** [comment]
I have the same/similar problem in chrome and firefox running on linux fedora 24.   Also even running the a.out.js program in node, has the same problems.  

Nothing works as expected, but using \n does improve the situation by not showing text out-of-order.
All systems and software are fully updated.  

Output from node.js:
[grostig@localhost emsripten1]$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.0
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 271ce598c3d1fe74efadc254f5be1b57edea9f41) (https://github.com/kripken/emscripten-fastcomp/ 61acfb230665464544f2e8db292f8999fc3c628c) (emscripten 1.36.0 : 1.36.0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/grostig/src/emsdk_portable/clang/fastcomp/build_master_64/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/6.1.1
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/6.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
[grostig@localhost emsripten1]$ 

[grostig@localhost emsripten1]$ emcc -std=gnu++11 main.cpp
[grostig@localhost emsripten1]$ node ./a.out.js 
y
Print hello world output printf_nl? (y/n):Hello World!
y
Print hello world output printf? (y/n):Hello World!
Print hello world output printf_nl? (y/n):
y
Hello World!
y
Print hello world output cout? (y/n):Hello World!
y
Print hello world output via cout_flush? (y/n):Hello World!
Print hello world output via cout_endl? (y/n):
y
Hello World!
Print hello world output via cout_nl? (y/n):
y
Hello World!

See program source here:
[main.txt](https://github.com/kripken/emscripten/files/484031/main.txt)

This long standing bug/feature limits use of emscripten for many linux command line programs.

Any assistance appreciated.

**Comment by juj** [comment]
Your issue and the Safari one are likely different issues. The Safari one looks like is that Safari does not update DOM when entering a text input box. Your issue sounds like due to stdout/stderr buffering being line ending -based. See https://github.com/kripken/emscripten/issues/2770 for more discussion. You can try reverting https://github.com/kripken/emscripten/commit/b759913f3d96d5d3544e0a0872fa3edc3fc0055d to see if that helps for your case.
