### ISSUE TITLE
Add ability to mount an existing filesystem

### ISSUE THREAD

**Issue by ddevault** [emscripten-core/emscripten#2963]
Rather than creating a new filesystem from scratch when calling `FS.mount`, I would like to be able to pass in an existing filesystem. I'm thinking something like this:

```
var fs = FS.mount(MEMFS, {}, "/example-1");
FS.mountfs(fs, "/example-2");
```

The justification for this is that I need to have several programs on the same page, each of which will have its own FS object. If I can mount the same filesystem on both, then I can share files between them.

```
require(["thing1", "thing2"], function(thing1, thing2) {
    thing1.FS.mkdir("/share");
    thing2.FS.mkdir("/share");
    var share = thing1.FS.mount(MEMFS, { }, "/share");
    thing2.FS.mountfs(share, "/share");
});
```

I'm happy to implement this feature myself, but would like to gather feedback before getting started.

**Comment by vadimkantorov** [comment]
@kripken Also stumbled on this: in context of https://github.com/emscripten-core/emscripten/issues/12074. My usecase is also a toolchain (yet another attempt of latex in browser, much like in https://github.com/emscripten-core/emscripten/issues/12074). I'd like to share a file system across modularized programs (xetex, bibtex/biber, dvipdmx, some small unix-like programs like cat).

**Comment by kripken** [comment]
I see @vadimkantorov , let's reopen this then.

**Comment by vadimkantorov** [comment]
A workaround is an ability to copy directories recursively from one FS to another. Maybe it's a simpler thing from an API point of view and could be developed faster

**Comment by vadimkantorov** [comment]
@kripken I just found PROXYFS (that has zero documentation, so it took some time to discover). Does it not implement this functionality? https://github.com/emscripten-core/emscripten/pull/4737

**Comment by kripken** [comment]
@vadimkantorov I'd forgotten about it too - yes, I think it can help here. If you look into it and it does, a documentation PR would be great!

**Comment by kripken** [comment]
Documentation added in #14668

**Comment by vadimkantorov** [comment]
There also has been a bug in PROXYFS: https://github.com/emscripten-core/emscripten/issues/12367#issuecomment-700971131
