### ISSUE TITLE
Source maps not generated for libraries

### ISSUE THREAD

**Issue by warrenseine** [emscripten-core/emscripten#2970]
From the mailing list:

> I finally had the time to make a test case, and indeed, there's a bug in the source mapper. Please download [this archive](https://dl.dropboxusercontent.com/u/2831026/Bugs/source-map-test.tar.bz2) and run "make" on Linux / OS X. This example will build a library and a program, all with -g4.
> 
> Here's the output if you don't want to bother compiling:
> 
> `▶ make`
> `make -C libfoo`
> `em++ -g4 -o foo.o -c src/foo.cpp`
> `emar rcs libfoo.a foo.o`
> `make -C bar`
> `em++ -g4 -o bar.o -c src/bar.cpp -I../libfoo/src`
> `emcc -g4 -o bar.bc bar.o -L../libfoo -lfoo`
> `emcc -g4 -o bar.html bar.bc`
> `sourcemapper: Unable to find original file for src/foo.cpp at /Users/Warren/Downloads/source-map-test/bar/src/foo.cpp`
> 
> I have noticed that if I move the source files in their parent directory, the source mapper doesn't produce this error. I suspect the source mapper is confused by the fact that both the library and the program source files are located in a "src" directory.

**Comment by kripken** [comment]
This patch makes fastcomp emit full absolute paths in debug info:

````
diff --git a/lib/Target/JSBackend/JSBackend.cpp b/lib/Target/JSBackend/JSBackend.cpp
index ace15ac..883a2c7 100644
--- a/lib/Target/JSBackend/JSBackend.cpp
+++ b/lib/Target/JSBackend/JSBackend.cpp
@@ -562,7 +562,9 @@ static void emitDebugInfo(raw_ostream& Code, const Instruction *I) {
     DILocation Loc(N);
     unsigned Line = Loc.getLineNumber();
     StringRef File = Loc.getFilename();
-    Code << " //@line " << utostr(Line) << " \"" << (File.size() > 0 ? File.str() : "?") << "\"";
+    StringRef Dir = Loc.getDirectory();
+    // XXX "/" is not the right separator on windows...
+    Code << " //@line " << utostr(Line) << " \"" << (File.size() > 0 ? Dir.str() + "/" + File.str() : "?") <<  "\"" ;
   }
 }
 ````

However, I'm not sure if that is the right thing to do, it works in chrome but not in firefox. We should find out if that's a bug in firefox, or a spec issue. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1128766

**Comment by evanw** [comment]
I'm running into the "Unable to find original file" issue too. It seems that sourcemapper.js supports a source root parameter via "--sourceRoot" but there's no way to pass that down from emcc. Could you add an emcc setting for the source root that's then passed down to sourcemapper.js?

**Comment by kripken** [comment]
I'd be ok with that. So it would let you provide the absolute root dir of where the source files are, basically? That might be a better solution than baking all the absolute paths as in that diff, but not sure...

**Comment by warrenseine** [comment]
I may have multiple source roots (just like I've got multiple include dirs), so I'd like to be able to pass the option multiple times. That, I guess, would require a change in the source mapper.

Warren.

**Comment by kripken** [comment]
In that case, sounds like it would be better to just pass absolute paths. But the size of them would be too big to just do naively, we'd need to do something more clever here, like add a table at the end - much like LLVM does. Not sure how much work that would be.

**Comment by promethe42** [comment]
> In that case, sounds like it would be better to just pass absolute paths. But the size of them would be too big to just do naively, we'd need to do something more clever here

Could we use "response files" (https://gcc.gnu.org/wiki/Response_Files)? @warrenseine I think that's what we do already for some other paths: premake generates *.rsp files used to avoid command lines that might be too long.

**Comment by jlmatchlock** [comment]
I was running into this issue recently (with version 1.37.15 installed by emcc install sdk-incoming-64bit)
where some files across several libraries would not have their sourcemaps generated.

By applying the patch above, it reversed the list of files that successfully had their sourcemaps generated with the ones that do not.

After digging a little bit, it seems like fastcomp doesn't yet handle having a mix of absolute and relative paths so I've made the following change to EmitDebugInfo() in JSBackend.cpp, to check whether a file already has its full path appended or not.

```
// Requires Path.h
#include "llvm/Support/Path.h"

  if (Line > 0)
  {
	  const StringRef Dir = Loc->getDirectory();
	  const Twine currentFilePath(File);

	  if (llvm::sys::path::is_absolute(currentFilePath))
		Code << " //@line " << utostr(Line) << " \"" << (File.size() > 0 ? File.str() : "?") << "\"";
	  else
		Code << " //@line " << utostr(Line) << " \"" << (File.size() > 0 ? Dir.str() + "/" + File.str() : "?") << "\"";
  }
```

With this, all files have their sourcemaps correctly handled.

This was tested with both Chrome and Firefox (on their latest version)

**Comment by kripken** [comment]
Thanks @jlmatchlock, can you please open a PR with that?

**Comment by jlmatchlock** [comment]
@kripken PR submitted. Thanks for looking into it !
