### ISSUE TITLE
implicit declaration of function 'mkstemp' is invalid in C99  error while trying to build ffmpeg.js

### ISSUE THREAD

**Issue by ajithreddy** [emscripten-core/emscripten#2973]
I am trying to build a javascript version of ffmpeg. When I run the ./configure I get the error 
**implicit declaration of function 'mkstemp' is invalid in C99  error while trying to build ffmpeg.js**

**Here are the logs:**
libavutil/timer.h:45:31: warning: 'HAVE_GETHRTIME' is not defined, evaluates to 0 [-Wundef]
# if !defined(AV_READ_TIME) && HAVE_GETHRTIME

```
                          ^
```

libavutil/file.c:169:10: error: implicit declaration of function 'mkstemp' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    fd = mkstemp(_filename);
         ^
1 warning and 1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
make: *_\* [libavutil/file.o] Error 1

I have been trying hard for 2 days but could not find a solution

**Comment by ShawZG** [comment]
@ajithreddy  do you compile ffmpeg with emscripten successfully?

**Comment by ajithreddy** [comment]
I was not able to find a solution and left it. As we have moved our media processing parts to server, we stopped working on this.

**Comment by ShawZG** [comment]
@ajithreddy Thank you for your reply.  I've been obsessed with this problem for a long time, maybe I should look for other solutions.

**Comment by juj** [comment]
Tested this to work with the following program:

	#define _POSIX_SOURCE

	#include <stdlib.h>
	#include <stdio.h>

	int main()
	{
	  int fd = mkstemp("abcXXXXXX");
	  printf("%d\n", fd);
	}

Running this prints file descriptor number `3`, so it looks like the function call is successful.

The explanation of `_POSIX_SOURCE` is available in [GNU C Library documentation](http://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html): "If you define this macro, then the functionality from the POSIX.1 standard (IEEE Standard 1003.1) is available, as well as all of the ISO C facilities. "

**Comment by ShawZG** [comment]
@juj Can you help me this problem ?  #4687
