### ISSUE TITLE
hello_world_gles_full.c does not work in 1.25.0

### ISSUE THREAD

**Issue by salos1982** [emscripten-core/emscripten#2991]
go to tests directory
emcc hello_world_gles_full.c -o gles.html

then start gles.html in browser
nothind is drawn and in console there are
vertex shader info: (unknown error)
fragment shader info: (unknown error)

**Comment by jamesfolk** [comment]
Hello! I am getting the same error (unknown error) from `glGetShaderInfoLog' after I `glCompileShader` even when i have the `-s FULL_ES2=1` option set..

This code is working for iOS and Android NDK, so I know it should be working...

`CXXFLAGS = -O2 -I. $(INCLUDES:%=-I%) -std=gnu++11 -frtti -fexceptions -DDEBUG=1 -s FULL_ES2=1 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 1`
`LDFLAGS = --embed-file ../COMMON/assets@/	`

**Comment by kripken** [comment]
how are those flags used? you need CXXFLAGS during "link".
