### ISSUE TITLE
Using em++ when including ports for the first time causes build problems.

### ISSUE THREAD

**Issue by marningmol** [emscripten-core/emscripten#3024]
Fresh install of emsdk portable. 

Compile something with `em++ -s USE_SDL=2`

Fail as it tries to build C code in what I assume is C++ mode. (i.e. `error: cannot initialize return object of type 'SDL_bool' with an rvalue of type 'bool'`)

**Comment by echeese** [comment]
This happens to me on 1.27.0

**Comment by kripken** [comment]
This should now be working on incoming, 1.28.3.
