### ISSUE TITLE
emscripten ports USE_SDL=2 auto compile fails when using multiple emcc processes for the first time. 

### ISSUE THREAD

**Issue by ankitkk** [emscripten-core/emscripten#3033]
We have threaded build system and starts multiple emcc process, if SDL2 hasn't been compiled before, all emcc processes try to compile SDL2, with many processes ultimately failing.  

I think auto compile is not entirely a good option, maybe let emcc download prebuilt .a's SDL2 on demand and limit emscripten ports to prebuilt .a's and header files.

**Comment by michaKFromParis** [comment]
Compiling a simple test does not resolve the issue on OSX.
Wether you install 1.27, 1.29, 1.30 or master the port compilation of SDL2 ends up spawning multiple processes and breaking the build.
Only the incoming branch seems to resolve the issue for good.

**Comment by kripken** [comment]
The `embuilder.py` tool should help avoid this problem. The bots use it, for example.
