### ISSUE TITLE
emscripten on Arch linux uses python3 by default

### ISSUE THREAD

**Issue by modeswitch** [emscripten-core/emscripten#304]
On Arch systems /usr/bin/python points to python3. I had to edit emcc, em++, et. al. to look for /usr/bin/env python2 instead. An option in ~/.emscripten to specify location of python2 would be helpful.

**Comment by GuillaumeLeclerc** [comment]
Any news about this ? It has been more than two years and the problem is still not solved for me

**Comment by kripken** [comment]
There is a plan to improve this in https://github.com/kripken/emscripten/issues/3872#issuecomment-151115726
