### ISSUE TITLE
Rounding mode control is missing for _mm_cvtss_si32 and _mm_cvt_ss2si

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3047]
In the current SSE 1 test, the cvtss and cvt instruction tests are disabled with the following comment:

```
#ifndef __EMSCRIPTEN__ // TODO: Fix banker's rounding in cvt functions.
    Assert(_mm_cvtss_si32(c) == 4); Assert(_mm_cvtss_si32(e) == 4); // Convert lowest channel of m128 from float to int.
    Assert( _mm_cvt_ss2si(c) == 4); Assert( _mm_cvt_ss2si(e) == 4); // _mm_cvt_ss2si is an alias to _mm_cvtss_si32.
#endif
```

For full emulation completeness, we need to add support for different rounding modes, however slow that may be. Granted, it is expected that most codebases will disable this and use something else, and we can then experiment with a fast noncompatible version, but this is mostly for cases that need correct emulation.

**Comment by hugoam** [comment]
Hi ! What's the status on this ? It seems `_MM_GET_ROUNDING_MODE` doesn't appear in any tests, but it doesn't seem to be present in Emscripten SSE1 implementation either ?
Also, it appears all conversion tests are enabled. Is supporting `_MM_GET_ROUNDING_MODE` just a matter of adding the corresponding macros ?

**Comment by juj** [comment]
There has not been activity on this since the original push to add SIMD to asm.js. The SIMD JavaScript specification was put on hold after it was realized it is not possible to make it usefully fast in JavaScript, and there was friction with providing a unified API that covers both NEON and SSE. SIMD will be likely be revisited in WebAssembly at some point in the future.

PRs to add emulation for proper rounding modes would be appreciated, although it is not expected to be possible to get anything that would be performant in any way.

**Comment by hugoam** [comment]
Yep, after a little bit of reading on the topic I understand Emscripten SIMD progress is tied to the progress and implementation of the SIMD proposal to WebAssembly. As for emulating rounding modes, I would gladly help but I have no knowledge of how these things should be done. Being able to compile that code even with non-SIMD performance would definitely be nice until wasm/SIMD goes forward.
