### ISSUE TITLE
Crash compiling benchcpp

### ISSUE THREAD

**Issue by sunfishcode** [emscripten-core/emscripten#3128]
As of this bug report, compiling benchcpp [0] causes the following crash in Emscripten:

lib/Target/JSBackend/ExpandI64.cpp:548: bool (anonymous namespace)::ExpandI64::splitInst(llvm::Instruction *): Assertion `I->getOpcode() == Instruction::LShr || I->getOpcode() == Instruction::AShr || I->getOpcode() == Instruction::Shl' failed.

This is because the code is doing a simple-seeming delay loop, which innocently happens to be computing a sum which innocently _happens_ to be polynomial in nature, but little does it know that it's awaking a powerful but rarely seen beast within LLVM that totally optimizes polynomial recurrences, and it does so by emitting 65-bit integer arithmetic, because the computations it's doing would overflow if done in 64-bit, and the lowering passes Emscripten uses don't know how to handle that.

I filed a benchcpp issue to fix up the delay loop code, since the whole point is to defeat optimization. It happens that applying this patch also avoids the situation which awakes the polynomial optimizations, thus working around the bug.

But nonetheless, it is still a bug, even if an obscure one.

[0] https://github.com/PeterJensen/benchcpp
[1] https://github.com/PeterJensen/benchcpp/issues/1

**Comment by kripken** [comment]
Here's a small testcase:

````
#include <stdint.h>

uint64_t preventOptimize;

uint64_t simd(uint64_t n) {
  uint64_t s = 0;
  for (uint64_t i = 0; i < n; ++i) {
    preventOptimize++;
    s += i;
  }
  return s;
};
````

is compiled to

````
; ModuleID = 'a.o'
target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
target triple = "asmjs-unknown-emscripten"

@preventOptimize = global i64 0, align 8

; Function Attrs: nounwind
define i64 @_Z4simdy(i64 %n) #0 {
entry:
  %cmp4 = icmp eq i64 %n, 0
  br i1 %cmp4, label %for.end, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %entry
  %preventOptimize.promoted = load i64* @preventOptimize, align 8, !tbaa !1
  %0 = add i64 %n, -1
  %1 = zext i64 %0 to i65
  %2 = add i64 %n, -2
  %3 = zext i64 %2 to i65
  %4 = mul i65 %1, %3
  %5 = lshr i65 %4, 1
  %6 = trunc i65 %5 to i64
  %7 = add i64 %6, %n
  %8 = add i64 %7, -1
  %9 = add i64 %preventOptimize.promoted, %n
  store i64 %9, i64* @preventOptimize, align 8, !tbaa !1
  br label %for.end

for.end:                                          ; preds = %for.body.lr.ph, %entry
  %s.0.lcssa = phi i64 [ %8, %for.body.lr.ph ], [ 0, %entry ]
  ret i64 %s.0.lcssa
}

attributes #0 = { nounwind "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.ident = !{!0}

!0 = metadata !{metadata !"clang version 3.5.0 (git@github.com:kripken/emscripten-fastcomp-clang.git 9c715dc2014b86ede35b6f794d49f74470a7d493) (https://chromium.googlesource.com/native_client/pnacl-llvm 3de18350c236cc57463ab2fdc60fc1b70e338439)"}
!1 = metadata !{metadata !2, metadata !2, i64 0}
!2 = metadata !{metadata !"long long", metadata !3, i64 0}
!3 = metadata !{metadata !"omnipotent char", metadata !4, i64 0}
!4 = metadata !{metadata !"Simple C/C++ TBAA"}
````

due to MergedLoadStoreMotion.
