### ISSUE TITLE
No such file or directory (with nodejs) ?

### ISSUE THREAD

**Issue by alexino2** [emscripten-core/emscripten#3136]
Hello everybody,

My emcc script works fine in web mode (using FS.createDataFile), but when i'm trying to use nodejs, I'm getting this error : myFile.avi : "no such file or directory"

With nodejs, i'm able to use the --help command or any action that does not involve any file...

Any idea on injecting files with Modules["arguments"] and nodejs ?

**Comment by kripken** [comment]
Can you be more specific, perhaps provide a testcase showing what you're trying?

**Comment by alexino2** [comment]
Of course, still working with x264 encoder : 

my server.js :

```
var http = require("http");
var x264 = require('./encoder.js');

function start() {
	
	function onRequest(request, response) {
		response.writeHead(200, {"Content-Type": "text/plain"});
		response.write("Hello World");		
		response.end();
	}

	http.createServer(onRequest).listen(8080);
	
	setTimeout( function() { 
		var args = { arguments: ["-o", "out.mkv", "in.y4m"]};
		x264.encoderEmcc(args); 
	}, 500 );
}

start();
```

my encoder.js:

```
function encoderEmcc(args) {
	var Module;
	if (!Module) Module = eval('(function() { try { return Module || {} } catch(e) { return {} } })()');
	for (var i in args) {
		Module[i] = args[i];
	 }

		/* All Emscripten Core here */

 }
exports.encoderEmcc = encoderEmcc;
```

the "in.y4m" is not found/open by emcc in node.js. 

The error seems to be catched on FS.open method here :

```
          try {
            var lookup = FS.lookupPath(path, {
              follow: !(flags & 131072)
            });
            node = lookup.node;
          } catch (e) {
            // ignore
          }
```


What should I add in my code ?

**Comment by alexino2** [comment]
Ok, I resolved it using this in encode/out.js
```   
  Module['preRun'] = function() {
            FS.mkdir('/in');
            FS.mount(NODEFS, { root: '.' }, "/in");
     }
```

But the result is almost twice slower than web mode ! Is there any other way to access local data without mount ?

**Comment by choikwa** [comment]
Also affected by similar issue. I can compile bzip2 and when I load it with node.js, it can't find any file argument (No such file or directory). It does see dash options like --help.
