### ISSUE TITLE
False clang version mismatch error with Emscripten SDK?

### ISSUE THREAD

**Issue by dreamlayers** [emscripten-core/emscripten#3143]
I used Emscripten SDK to build incoming and master clang. This means I have the following directories

```
clang/fastcomp/src
clang/fastcomp/build_incoming_64
clang/fastcomp/build_master_64
```

I first built master and then incoming, and the `src` directory has incoming there now. Emscripten master complains even though path includes `clang/fastcomp/build_master_64` and does not include `clang/fastcomp/build_incoming_64`:

```
ERROR    root: Emscripten, llvm and clang versions do not match, this is dangerous (1.29.0, 1.29.3, 1.29.3)
ERROR    root: Make sure to use the same branch in each repo, and to be up-to-date on each. See https://github.com/kripken/emscripten/wiki/LLVM-Backend
INFO     root: (Emscripten: Running sanity checks)
```

This is due to [tools/shared.py](https://github.com/kripken/emscripten/blob/master/tools/shared.py#L324) checking `clang/fastcomp/src/emscripten-version.txt` and `clang/fastcomp/src/tools/clang/emscripten-version.txt`. I guess the errors are wrong because the version of the source tree does not matter, and what matters is the binaries.

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
Hmm indeed. To save space, the LLVM repo is not cloned twice, but only once and the `incoming` and `master` builds are done off of the same source tree, but to different binary directories. I think the correct fix here is to locate `emscripten-version.txt` to the build output directory and have tools/shared.py check that first. I can fix that up, but does that sound ok @kripken ?

**Comment by kripken** [comment]
Hmm, when would you copy the version to the build output dir? As part of the LLVM build?

**Comment by dreamlayers** [comment]
Could you use [CLANG_VENDOR](http://marc.info/?l=llvm-commits&m=134713877201303) instead of a file?

**Comment by kripken** [comment]
Interesting option, ccing @sunfishcode

**Comment by juj** [comment]
Yeah, copying the `emscripten-version.txt` would then need a post-build copy command (e.g. http://stackoverflow.com/questions/13429656/cmake-how-to-copy-contents-of-a-directory-into-build-directory-after-make ) in LLVM CMake configuration script, which is a oneliner to add.

**Comment by kripken** [comment]
Sounds ok then, but we'll need to test it carefully of course. Possible that existing `sanity` tests suffice, but will likely need changes.
