### ISSUE TITLE
tracing support for current stack frame

### ISSUE THREAD

**Issue by nickdesaulniers** [emscripten-core/emscripten#3153]
from the [tracing docs](https://kripken.github.io/emscripten-site/docs/api_reference/trace.h.html):

```
Rather than getting a stack trace on every tracing call, we can often look at the current context stack and record that instead, which is much cheaper.
```

I'd like to be able to hook into every call to stackAlloc, which is not possible currently since it is closed over within the asm module.  My ultimate goal is to be able to keep a record of the deepest stack depth (water mark), and possibly the current stack depth, either as addresses or number of bytes, since either can be used with STACKTOP to find the other.

This would allow me to implement the final piece of @juj 's demo memory profiler.

**Comment by kripken** [comment]
cc @waywardmonkeys

**Comment by waywardmonkeys** [comment]
@nickdesaulniers Do you mean ``stackAlloc`` the runtime call or the ``stackAlloc`` that happens during code generation?

Few things use ``stackAlloc`` (the runtime call), since most stack manipulation just happens in the JS generation.

**Comment by waywardmonkeys** [comment]
And as for @juj's memory profiler ... a good bit of what it can do (and more than it can do) can be done with the tracing front end that I have written and link to from the docs.

**Comment by nickdesaulniers** [comment]
I believe @juj 's memory profiler was using runtime stackAlloc to measure stack depth (and seems to work).  If it doesn't make sense anymore then I can leave that feature out.

I'm experimenting with writing a few different visualizations of memory; I'm reusing a lot of the tracing stuff, but not the server.
