### ISSUE TITLE
interaction between resolution changes and full-screen mode

### ISSUE THREAD

**Issue by db48x** [emscripten-core/emscripten#3157]
Currently when the compiled program changes video modes emscripten adjusts the canvas size to match. This works perfectly most of the time, but when the canvas has been put into full-screen mode it's actually insufficient.

As a test-case, you can visit https://www.archive.org/stream/msdos_Zzt_1991_Epic_Megagames_Inc/Zzt_1991_Epic_Megagames_Inc.zip?module=dosbox. This is the game ZZT running inside of DosBox, compiled with emscripten. Once you get past the opening menu (choosing keyboard and color, for instance, though what you pick doesn't matter much), the game changes video modes, and the canvas size is adjusted. If you enter full-screen mode before that size change happens, then after the size change the display will stay in the same aspect ratio, rather than changing. (Of course in this case both aspect ratios are historically inaccurate, but let's ignore that for the moment.) I'm not sure what the right fix for this is yet.

Additionally, if the compiled program switches video modes while in full-screen mode, then the browser restores the old dimensions of the canvas when the user leaves full-screen mode. This causes an unsightly but benign blank area around the program when the new size is smaller than the old, or clipping when the new size is larger. A simple event listener that restores the correct dimensions after the transition from full-screen mode will suffice. This event listener will also fix a visual glitch that happens in chrome when leaving full-screen mode which leaves the canvas entirely blank.

Both of these bugs happen regardless of whether we use FSEvents.requestFullScreen or not; fixing them will probably require that we actually call that, or possibly adding a method to the Module (so that emscripten can notify the page of the resolution change), or both.

**Comment by juj** [comment]
See this pull request which gives more control over the size and aspect ratio: https://github.com/kripken/emscripten/pull/2975 . That functionality has not been merged to FS.requestFullscreen, because I could not figure out a good way to do so - some code might be assuming manual canvas resize functionality when calling the function, so I was afraid that I might break some code if I had changed the existing shell functionality.

**Comment by db48x** [comment]
Actually the code in #2975 is merged, or at any rate merged into the branch we're using at the moment. It's pretty good, and gets us most of the way there. However, as I mentioned it doesn't fix the interactions between resolution changes by the compiled program and full-screen mode. In EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT mode, for example, it should update the letterboxing as the aspect ratio changes; this would give the new display mode the correct aspect ratio after the browser scales it up to fill the screen.

**Comment by juj** [comment]
Oh, now I understand. It is not possible in JavaScript to listen to size changes of a DOM element, so we cannot react to changes using an event at least.

You are right that emscripten_set_canvas_size and emscripten_set_element_CSS_size will conflict if used on an element that is currently in full screen mode. I think we do need some amount of combined awareness of those functionalities, however, I wonder what the behavior should be if I first go to full screen, then resize the canvas, and then come back to windowed mode? Should the canvas retain the original windowed size, or the changed size?

**Comment by db48x** [comment]
I'm not sure about the general case, but in this case the program in question is some arcade or dos game from the 80s; they really don't expect the display size to change once they put the computer into a particular video mode. If we restore the old dimensions then the result is either clipping (the new mode is larger than the old), or a blank area on the canvas (new is smaller than the old). I'd like to avoid both, obviously.
