### ISSUE TITLE
non-square pixels

### ISSUE THREAD

**Issue by db48x** [emscripten-core/emscripten#3158]
Archive.org is using emscripten to create web-based emulators for older software, such as arcade games, console games, etc. Most of these used CRT displays with a 4:3 aspect ratio, even when the video mode had some other aspect ratio. (EGA, for example, had a pixel grid of 640x350, but the CRT always made this into a 4:3 display.)

We'd like to be able to call FSEvents.requestFullScreen to put the canvas into full-screen mode, but it'll need a new mode which keeps the correct aspect ratio. It'll be quite similar to the current EMSCRIPTEN_FULLSCREEN_SCALE_ASPECT mode, but will take the aspect ratio not from the current screen dimensions but from a property (method?) of the Module instead.

**Comment by kripken** [comment]
A property on `Module` is one option, but perhaps it would change over time? Seems like adding a parameter to the C method in the HTML5 APi might be simplest. I'm ok either way though.

**Comment by juj** [comment]
I dislike adding parameters to module. Adding a new option to html5 api full screen transition that specifies a custom non-square aspect ratio sounds ok. Would that be enough for you?

**Comment by db48x** [comment]
Sorry about that, I see that I've inadvertently left out the important bit. I'd like to be able to set an aspect ratio and have it be in effect all the time, in full-screen mode and out. 

I can kinda do this myself, in some cases. I can set the css width/height to 640x480 and it'll scale properly whenever the program is in CGA (320x200) or EGA (640x350) or VGA (640x480) mode, but then it breaks whenever a program goes to the Hercules text/graphics mode (720x350), SVGA (800x600), etc. Because the program can change modes whenever it wants emscripten should probably take care of this itself.

An alternative to having an aspect ratio property on the Module would be to have a method on the Module that emscripten could call any time the resolution changes; this would allow me to update the scaling to match. I tried doing this using a mutation observer on the canvas, to catch the width/height properties changing, but it's quite glitchy, especially around the transition to/from full-screen mode.

**Comment by juj** [comment]
The reason I dislike adding anything new to `Module` is that it introduces global singleton state variables and logic to the system and new dependencies to the runtime where behavior is defined by statically once-existing data fields. That is not very good encapsulation, and more these kinds of fields exist, the more it makes Emscripten behave like a special architecture compared to native. Any code we add to `Module` is not subject to dead code elimination and all projects in existence will have to pay the code impact of carrying the logic around even if they don't need it, which has the pressure of bloating the runtime, that people have already been complaining about. It is far better to have these kind of configuration be defined in the respective APIs in question, and in this case I think the proper solution would be to have the HTML5 API allow configuring a custom non-square aspect ratio, and your application can call those functions to set up the fullscreen mode. That way the feature will be self-contained and will not be included when not used.

**Comment by db48x** [comment]
I completely understand, but adding an option to the full-screen api won't do anything to help the rest of the time. We want it to be the right aspect ratio before the user activates full-screen mode, and after they leave it.

**Comment by juj** [comment]
You can specify a custom aspect ratio before activating fullscreen mode by simply calling `emscripten_set_element_css_size` and `emscripten_set_canvas_size` in the beginning of your application. The first call defines the visible rectangle of the canvas, and the second call defines the actual render target size of the canvas. These can have arbitrarily different sizes and aspect ratios, so there should not be a problem there(?).

**Comment by DopefishJustin** [comment]
There's already a forcedAspectRatio property on Module that does that though (unless it went away). E.g. forcedAspectRatio: 4/3

IMO for the purposes of emulation it's better to have aspect correction only for fullscreen and stick to 1:1 pixels when in a tiny window, which would require something new in Emscripten, I think.

**Comment by db48x** [comment]
Ooh, that's probably just what I need; I'll test it right away. Where is it supposed to be documented though; searching the code found it easily enough (now that I know the name), but I can't find anything in the documentation.
