### ISSUE TITLE
better heap checking mode

### ISSUE THREAD

**Issue by mlogan** [emscripten-core/emscripten#3185]
I had a nasty memory corruption bug, and since my project unfortunately isn't set up to compile natively, I couldn't use valgrind. I ended up writing some fairly basic memory checking code built on top of emscripten's `SAFE_HEAP=1` compilation mode. I had edited it directly into emscripten's asm.js output. Here's a patch that should apply to emscripten modules built in with `-s SAFE_HEAP=1` and `-g`.

https://gist.github.com/mlogan/d5d0b964ba65433dfb87

It checks for reads/writes to unallocated memory, pads allocations with sentinel bytes to detect array overruns, detects double-free() calls, and delays free() calls to make dangling pointer writes less likely to go undetected.

Unfortunately, it doesn't appear to be feasible to detect reads from uninitialized memory, as that requires white-listing of many common library functions that contain uninitialized reads, and the only way I can think of to do such whitelisting is to inspect the call stack, which is slow enough that it results in something like a 1000x slow-down.

I'd be happy to integrate a cleaned-up version of this code into emscripten as a `-s` option, possibly as a replacement for the defunct `-s CORRUPTION_CHECK` flag, if it's something you'd be interested in merging, but I have no idea where to start to make that happen. Can you point me in the right direction?

**Comment by kripken** [comment]
Interesting work! And yes, I would like to see this merged in in to replace `CORRUPTION_CHECK`.

Overall, you would need to do the following:

1. Add the option to src/settings.js
2. Add a check in emcc, that if the option is present, do some stuff. Specifically you will want to also add to what is being built, a dlmalloc.c file with the instrumented code. See https://github.com/kripken/emscripten/pull/3179 for a similar thing, and some discussion. Basically, malloc (and I am pretty sure, calloc etc.) are all weakly linked. So your added file will just override the system one.
3. You will likely want to add ifdef'd instrumentation in system/lib/dlmalloc.c, although a separate file might be ok too, depends what works best I guess.
4. Add code in src/preamble.js with ifdefs for the option, that hooks into SAFE_HEAP stuff
5. Add some testing.

**Comment by kripken** [comment]
I suppose another option is actually what you did here - apply a diff. The output in early stages is pretty easy to apply a diff against, although function order might be an issue - but can apply multiple diffs. That would all be done in emcc, I guess.

This might be simpler - no messing with C code at all, just applying arbitrary patches to the emitted code. Right after the backend emits it, before the js optimizer runs, a little after `log_time('emscript (llvm=>js)')` in emcc.

Not sure which approach is best, would be good to think about both for a while.

**Comment by mlogan** [comment]
If you think the un-optimized output is stable enough across different inputs for the patch to always apply, that certainly would be easier. But it feels pretty hacky. I'll take a look at the different places you pointed me at in your first comment and see how much work that will be.

Regarding dlmalloc.c, `#ifdefs` seem like a reasonable way to handle this, although it will make switching to a different malloc implementation more painful. Do you think there's any significant chance of that happening?

**Comment by kripken** [comment]
A literal patch might be tricky, but something like a python script that replaces `function _malloc(..) {` with `function _malloc(..) { preHook() ` would be fairly safe to do. Hackish, but I don't mind hacks as long as they are safe and not going to break later.

We might change malloc at some point, in fact we probably should, the one we have right now is quite old. We should use the current one in musl perhaps.

**Comment by mlogan** [comment]
Ok, I went back to this, and am close to having something mergable. I believe I can do this almost entirely without patches, just using `#if` macros when generating `SAFE_HEAP_LOAD/SAFE_HEAP_STORE`, and then adding a bunch of stuff to `postamble.js`

The one thing that does need to be patched is that `_malloc/_free/_realloc/_calloc` have to be renamed so that calls within the anonymous function at `EMSCRIPTEN_START_ASM` don't bind to those functions, and instead bind to the wrapper functions I define in the outer-most scope of the module.

And this is where I've run into the only real problem with this approach - I'm currently doing the renaming from within a `--js-transform` script, and it appears that calls to `calloc` can get inlined _before_ I rename the system `calloc`. I'm pretty sure this is because clang is inserting its own definition of `calloc` during the compilation step.

Do you know how to disable this? I've googled and looked in the clang manual and can't find anything. The patching approach is very simple and I'd hate to have to abandon it because of this.

**Comment by mlogan** [comment]
Ok, I thought that `-fno-builtin` would fix this, but apparently the sole cause is `--llvm-tlo 1` (and presumably any higher level), so I'll just need to disable that when running in corruption check mode.

**Comment by kripken** [comment]
It seems a slight shame to disallow LTO, however - that might be the only build showing a bug (sadly, not 100% a joke ... ;)

But, this would still be very useful even so, i wouldn't worry about it too much.
