### ISSUE TITLE
Difficulty handling Emscripten canvas scaling

### ISSUE THREAD

**Issue by jgranick** [emscripten-core/emscripten#3206]
When I implemented Emscripten support in the past, I was able to resize the canvas element in HTML, and handle resize events within my "native" code. However, it seems that Emscripten content now wrestles with my code changes on resize, forcing itself back to an original (or different) size.

For example, this code is meant to size the canvas to whatever size the DIV element it is in is sized to:

```
    var container = document.getElementById ("content");
    Module.canvas.width = container.clientWidth;
    Module.canvas.height = container.clientHeight;

    window.addEventListener ("resize", function (e) {

        Module.canvas.width = container.clientWidth;
        Module.canvas.height = container.clientHeight;

    }, true);
```

By default, when targeting HTML5, OpenFL projects usually do one of two behaviors by default. Either the window size is set to 100%, so it handles the DOM element parent as the maximum. This allows for a custom HTML template to constrain or expand the content by resizing that DIV, and the project takes up that full space accordingly.

The second is when you specify an exact size. Due to mobile device screen sizes varying so much, the default template for this will stretch to match the parent DIV size as well, but will maintain aspect ratio, and automatically allow letterboxing. This preserves the original pixel size, but uses CSS to improve usability.

Anyway, both of these methods allow the project to constrain to it's parent DOM element, with some scripting to handle the resize. I have tried to implement some of this outside of Emscripten in the page, but to no avail.

This used to work with Emscripten, but this was before the SDL2 port. Is there some way I can "turn off" Emscripten canvas sizing after the initial size, or is there a way within C++ that I could size relative to the parent DOM element, like I'm hoping to? It's sort of simulated fullscreen.

Thank you!

**Comment by juj** [comment]
What do you mean by "before SDL2 port"? Do you use SDL2, and it is giving undesired behavior? Or are you not using SDL2 and after the SDL2 support landed, it broke your code even though you are not using SDL2? Can you locate where the conflicting code comes from?

**Comment by jgranick** [comment]
I implemented my first Emscripten support almost two years ago, before SDL2 officially released, when we were still using SDL1 in our code. This code sample above is what I used to resize my canvas element to the full size of my page.

Things have obviously gotten a lot better in that time. I wasn't able to use asm.js, but needed the linux-gnu LLVM target in order to get a proper compile. I'm excited about the Emscripten SDL2 support, and seeing if I can nail down the last few issues to provide full OpenFL support for it.

Everything is fine within the "C++" world, it's me trying to manipulate by outside forces :)

I'm happy if there's something that can be done within the C++ code to either disable the resize behavior of the canvas (which likely is related to fullscreen support, which is nice!) or to use a "psuedo-fullscreen" that scales up to the parent DOM element, but does not use actual fullscreen APIs to take over the screen.

Maybe there's also some other solution, I presume that there is an "onresize" within the Emscripten generated code, and that it's being handled after mine. Maybe it's something else

**Comment by juj** [comment]
Let me ask again to clarify, are you using SDL2 from https://github.com/emscripten-ports/SDL2/ ?

If so, I can see one hardcoded behavior that that repository has, which is that when the browser window is resized, there is a handler to the JS 'resize' event that does this: https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenevents.c#L531 . Note the `if ()`s in that function above that control the conditions when that occurs. Perhaps that is the conflicting case?

**Comment by jgranick** [comment]
Yep, that looks like it probably is. As a workaround, perhaps I can disable RESIZABLE, though I wonder if there's a way to implement this behavior from within the C++ "world"

I'll look again at the flags I'm using for fullscreen or resizable, and see if I can't get it to behave a little better. thank you

**Comment by remram44** [comment]
Did you ever figure this out? I can set the canvas size using `Module.setCanvasSize()`, but if I call this from a window.onresize event handler, emscripten-sdl2 resizes it back.

**Comment by kolumb** [comment]
Changing attribute don't work, because SDL_emscriptenevents.c checks for CSS properties. This worked for me:
```js
canvas.style.width = container.clientWidth + "px";
canvas.style.height = container.clientHeight + "px";
```
