### ISSUE TITLE
sscanf: converting floating point number that is followed by a string that starts with "e"

### ISSUE THREAD

**Issue by dertom95** [emscripten-core/emscripten#3217]
Hi there,
I found a difference between emscripten and clang/gcc in sscanf using the [libRocket-library](https://github.com/libRocket/libRocket). That is actually something I would consider an undefined behaviour as gcc and clang don't return the expected result either, but better than emscripten.

Imagine trying to convert a string like "10.0em". Manuals say sscanf can convert floating points with optional exponential value. The problem here is that the 'e'-character is part of the unit-name and have nothing to do with an exponential part. 
Using scanf("%f%s",...) returns for gcc/clang 10.0 and m. It consumes the e-character which is not intended, but at least the floating point value is converted in the right manner. 
Emscripten returns 0.0 and empty-string.

This issue is obviously only for strings starting with e directly after a float, using something like "10.0dem" works as intended.

Here is a test case:

```
#include <stdio.h>
#include <stdlib.h>

int main()
{
   float floatVal;
   char unit[20],dtm[20];

   strcpy( dtm, "10.0em" );
   sscanf( dtm, "%f%s", &floatVal,unit );

   printf("value:%f unit:%s\n",floatVal,unit );

   return(0);
}
```

Not sure if there is a switch in sscanf where you can turn off the conversion of exponential behaviour!?

**Comment by kripken** [comment]
This is in [MUSL](http://www.musl-libc.org/) code. I'm not sure if it's undefined behavior or not, and if it's a bug in MUSL or not. But we should report it to them. I checked and it is still the same on MUSL master.

**Comment by juj** [comment]
On a related note, we've raised discussions over at MUSL to set up a bug tracker, which they don't have, so it's difficult to track these issues. The best place to report this now is to send an email to the MUSL mailing list and ask how they see this.
