### ISSUE TITLE
Strange behaviour with attribute constructor and binding

### ISSUE THREAD

**Issue by Gregwar** [emscripten-core/emscripten#3220]
The following program:

``` c
#include <stdio.h>

__attribute__((constructor))
void test()
{
    printf("Testing\n");
}
```

Through the following compile chain:

```
$ emcc -c test.c -o test.o
$ emar cr test.a test.o
$ em++ --bind test.a
$ node a.out.js 
$ 
```

Does not works, the constructor method is never called. Why?

**Comment by Gregwar** [comment]
(However, it works perfectly if I don't bind, or if I don't archive)

**Comment by Gregwar** [comment]
This also applies to C++ objects, for example:

```
#include <stdio.h>

class Testing
{
    public:
        Testing() {
            printf("Testing\n");
        }   
};

Testing t;
```

Won't be constructed with the above compile chain

**Comment by kripken** [comment]
The main issue here is that `.a` linking checks for currently-needed symbols. When you don't bind, we see you are building just a `.a` file, so we **disable** that, and include all the contents of the file. But when you bind, we include in the bindings files, and then run normal `.a` linking. Which sees that there is no need for the contents of the `.a` file provided.

We could fix the problem here by making the call to `force_archive_contents` in emcc more careful - it needs to ignore the added bind files.

**Comment by Gregwar** [comment]
I thought `.a` was just a way to package a group of `.o`s
Another issue, maybe related, when you bind and produce a `.a`, and then build your program linking with this `.a`, you "loose" the binding:

```
$ em++ --bind a.cpp
$ node test.js 
Including a.out.js, calling Module.f()
42
$ em++ --bind -c a.cpp -o a.o
$ emar cr a.a a.o
$ em++ b.cpp a.a
$ node test.js 
 
Including a.out.js, calling Module.f()

/tmp/ex/a.out.js:84
      throw ex;
            ^
TypeError: Object #<Object> has no method 'f'
    at Object.<anonymous> (/tmp/ex/test.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by kripken** [comment]
I can't follow that example - none of those commands emits `test.js`? Where is it coming from?

**Comment by Gregwar** [comment]
Test.js is just a simple scripr that loads the module and call the bound function

**Comment by kripken** [comment]
Then I think the issue in that example is that `--bind` is an option relevant only when building to JS, not to bitcode. It's a global operation that is done on the entire program being converted to JS.

**Comment by eagleoflqj** [comment]
I'm still suffering from this issue, though I can bypass it by `emar x xxx.a`.

**Comment by sbc100** [comment]
@eagleoflqj, have you tried `-Wl,--whole-archive -la -Wl,--no-whole-archive`?
