### ISSUE TITLE
Possible embind optimization

### ISSUE THREAD

**Issue by neon12345** [emscripten-core/emscripten#3226]
Embind often creates JavaScript functions with the same body but different names from the templates in wire.h. Like the convertPointer templates which are registered with a ptr to function with embind.

Is this optimized in any way? Isn't it possible to remove these duplicates with a single function when type info is removed by js what makes them identical functions?

**Comment by kripken** [comment]
cc @chadaustin @waywardmonkeys

Perhaps on incoming which is llvm 3.5, we can run llvm mergefunc?

**Comment by chadaustin** [comment]
mergefunc helps a lot here.  However, it doesn't go all the way, because C++ requires that every unique function have a different address :/  I've wondered if it would be possible to detect at compile time whether a derived class and a base class have exact same bitwise pointer value, and if so, use an identity function to convert from one to the other...

**Comment by neon12345** [comment]
simple mergefunc does not help here because of the function ptrs we take to register with embind. The code for the pass is in "/lib/Transforms/IPO/MergeFunctions.cpp". There are different strategies:
1. replace the function with an Alias if possible.
2. replace one function with a smaller forward function, so that we still have two functions but less code. This does not work for small functions.

The "if possible" is given by the C and C++ rules. On the compiler side the attribute "unnamed_addr" could help to bypass this rules and let the pass merge these functions. Unfortunately I don't see a way to set this attribute from the source code. One could annotate the functions and handle them in the compiler but I don't know if it is worth it.
This optimization could be applied in general to all functions known that they are not compared by reference/ptr.

**Comment by chadaustin** [comment]
Agreed.  It would be awesome if clang provided a way to set that attribute from source code.
