### ISSUE TITLE
NODEFS flags conflict with Windows DELETE_ON_CLOSE / TEMPORARY / ...

### ISSUE THREAD

**Issue by julien33** [emscripten-core/emscripten#3229]
in src/library_nodefs.js function "flagsToPermissionString" :
if flags contain unrecognized value, it is transmitted directly to :
fs.openSync(path, NODEFS.flagsToPermissionString(stream.flags));

but some bit fields above the 16th bit, set for example by a compilation under linux (O_CLOEXEC)  have different meaning under windows, this one cause the file to be deleted on close for instance.

One solution would be to add a binary AND with 0xFFFF :

flagsToPermissionString : function(flags)
{
        flags &= 0xFFFF;
        if (flags in NODEFS.flagsToPermissionStringMap)
        {
                return NODEFS.flagsToPermissionStringMap[flags];
        }
        return flags;
}

The problem was encountered while trying to use an improved version of sql.js from https://github.com/kripken/sql.js/ with direct file access.
The sqlite database file was deleted right after it was closed.

**Comment by kripken** [comment]
Hmm, I have no idea what the "right" thing to do here is. I guess we would need to translate the emscripten flags (`O_CLEXEC`) etc. from the emscripten headers, to something that makes sense for the current native platform that node js running on? Is there a reason why `0xffff` is the right one, or is that just for windows?

**Comment by julien33** [comment]
You're right, the 0xFFFF filter was an over simplification, to be right, as the function is supposed to be a replacement for fcntl open, I would translate every single flags from fcntl.h for each OS.

**Comment by kripken** [comment]
I see. That does sound a little tricky though. @inolen , did you consider this issue when designing NODEFS?
