### ISSUE TITLE
Doubt related to Join and Merge Operations using compiled ffmpeg.js (using emscripten)

### ISSUE THREAD

**Issue by ajithreddy** [emscripten-core/emscripten#3268]
Hi,

I have been trying to use ffmpeg.js to join two audio files

**The syntax is similar to :**
-i female.mp3 -i female.mp3 -filter_complex "[0:0] [1:0] concat=n=2:v=0:a=1 [a]" -map "[a]" out.mp3

**I keep getting this error:**
Invalid stream specifier: "[a]"
Last message repeated 1 times
Stream map '"[a]"' matches no streams.

What am I doing wrong here. Am I not including the required libraries during compiling using emscripten or is it not possible to do this join/merge operation using ffmpeg.js at all.

Your advice would help me a great deal..
Thank you.

**Comment by kripken** [comment]
Might be useful to look at http://kripken.github.io/emscripten-site/docs/porting/Debugging.html , and specifically for that project, maybe someone else has already ported it and knows more about that error.
