### ISSUE TITLE
AL_SAMPLE_OFFSET implementation

### ISSUE THREAD

**Issue by urkle** [emscripten-core/emscripten#3271]
Is it possible to implement AL_SAMPLE_OFFSET in emscripten's OpenAL implementation?  I have a game I'm porting that is using that value to loop samples at certain offsets.

**Comment by mad-rain** [comment]
I'm also very interested in AL_SAMPLE_OFFSET implementation. We use it to crossfade tracks from one from another when the first one is going to finish.

As I know there is starting time available in source and currentTime in Web Audio context, so

AL_SAMPLE_OFFSET = currentTime - source.startTime

**Comment by juj** [comment]
It does look like that is implementable. Does there exist good tests for that to build the implementation against?

**Comment by urkle** [comment]
From the OpenAL 1.1 spec,
There are 3 values that can be retrieved and set in both integer and float values.

AL_SEC_OFFSET - the playback position in seconds (not affected by the pitch setting)
AL_SAMPLE_OFFSET - the playback position in samples (for a compressed format, this represents the uncompressed sample offset)
AL_BYTE_OFFSET - the playback position in bytes (for a compressed format, this represents an approximate offset in the compressed buffer)

**Comment by 4yk4a007** [comment]
I ended up with following hack for starting a sound at offset:

`alSourcePlay(sourceId); // switch to play state`

`// hack src.bufferPosition value`
`EM_ASM_({`
&nbsp;&nbsp;` var src = AL.currentContext.src[$0];`
&nbsp;&nbsp;` if (src && src.queue.length>0) {`
&nbsp;&nbsp;&nbsp;&nbsp;` var buffer = src.queue[0].buffer;`
&nbsp;&nbsp;&nbsp;&nbsp;` src.bufferPosition = AL.currentContext.ctx.currentTime - $1*1.0/buffer.sampleRate;`
&nbsp;&nbsp;` }`
`}, sourceId, sampleOffset);`

`alSourcePause(sourceId); // remember modified value, when switching to paused state`
`alSourcePlay(sourceId); // switching state from pause to play will start the sound from new offset`

**Comment by JacksonAllan** [comment]
Was this issue ever addressed?

At the moment, it seems that calls to alGetSourcei with AL_SAMPLE_OFFSET returns the current playing position, but calls to alSourcei (or alSourcef) with AL_SAMPLE_OFFSET, AL_BYTE_OFFSET, or AL_SEC_OFFSET have no effect at all regardless of whether they are placed before the sound is played, while it is playing, or while it is paused.

The hack mentioned by 4yk4a007 also doesn't seem to work anymore.

Is there an alternative way to begin playing a sound at a specific buffer position?

**Comment by JacksonAllan** [comment]
I did some further investigating and found that:

1. Setting AL_SAMPLE_OFFSET (or AL_BYTE_OFFSET or AL_SEC_OFFSET)  with alSourcei does, in fact, change the offset value if the source is stopped.
2. Calling alSourcePlay on the source resets the AL_SAMPLE_OFFSET to 0.
3. Calling alSourcei with AL_SAMPLE_OFFSET while the sound is playing has no effect at all.

The latter two points are in direct conflict with OpenAL specifications, which state that:

> When setting AL_SAMPLE_OFFSET on a source which is already playing, the playback
> will jump to the new offset unless the new offset is out of range, in which case an
> AL_INVALID_VALUE error is set. If the source is not playing, then the offset will be
> applied on the next alSourcePlay call. An alSourceStop, alSourceRewind, or a second
> alSourcePlay call will reset the offset to the beginning of the buffer
