### ISSUE TITLE
Reference to window object in library_trace.js breaks trace.h support

### ISSUE THREAD

**Issue by MichaelBalazs** [emscripten-core/emscripten#3278]
https://github.com/kripken/emscripten/blob/c4b8ad6343950fcd479908ca11d5dff8a8c4081c/src/library_trace.js#L51

Simply changing to `window.URL.createObjectURL(blob)` to `URL.createObjectURL(blob)` resolves the issue and is supported in all major browsers: https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

**Comment by kripken** [comment]
cc @waywardmonkeys

**Comment by waywardmonkeys** [comment]
If it works, it seems fine to me.

**Comment by waywardmonkeys** [comment]
@MichaelBalazs: Did you want to submit a pull request for this?

**Comment by MichaelBalazs** [comment]
I don't have this have this checked out anymore at this point. I can if you want but if it is easier for you do it, I would suggest that.
