### ISSUE TITLE
jsCall() is unoptimizable

### ISSUE THREAD

**Issue by tjgq** [emscripten-core/emscripten#3290]
I have some code that receives a pointer to a Javascript function (created via `Runtime.addFunction`) and calls it a large number of times.

When profiling the execution, the run time is dominated by the `jsCall` function. This seems to be because `jsCall` calls `Array.prototype.slice` on `arguments`, which is known to prevent optimization [0].

To check whether this was indeed the case, I replaced `jsCall` in `preamble.js` with the following implementation, which does not manipulate `arguments`:

```
function jsCall(a0, a1, a2, a3, a4) {
    return runtime.functionPointers[a0](a1, a2, a3, a4);
}
```

This caused the run time fraction spent on `jsCall` to drop from 98% to 4% for my workload (Chrome 41 on OSX). I've observed similar numbers on Firefox.

Is this an optimization worth pursuing for Emscripten? If so, the implementation above probably wouldn't cut it; we'd have to handle an arbitrary number of arguments, perhaps by falling back to the non-optimized version when they exceed a fixed number.

I'd be willing to work on a patch for this; let me know if you're interested.

[0] https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

**Comment by juj** [comment]
I agree that a solution that would avoid accessing `arguments` (and also avoiding `Array.prototype.slice`) would be nice, but I'm not sure what an optimized version would look like here. @kripken : when is `jsCall` used exactly? I see that it's not referred to in the codebase in JS code at all.

**Comment by kripken** [comment]
@juj: jsCall is used to call an arbitrary JS function from compiled code. This lets you wrap a JS function as a C function pointer at runtime, and a C function pointer call will call into a stub that calls jsCall, which then calls the wrapped method.

@tjgq: I think `emscripten.py` emits jsCall stuff. We could optimize this by seeing which argument lengths it needs, then having `jsCall1, jsCall2` etc. as necessary, and emitting those outside the asm module. So this could be optimizable, at the cost of some complexity. Sounds ok to me, if you're interested to work on it.

**Comment by tjgq** [comment]
Having separate jsCall0, ..., jsCallN functions emitted as required seems fine to me too. I'll take a stab at it and let you know how it's going.

**Comment by fabiosantoscode** [comment]
There's some interesting code here to handle this issue:

https://github.com/defunctzombie/events-browserify/blob/master/events.js#L44

How does it perform?
