### ISSUE TITLE
OpenGL Support

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#33]
In theory it should be straightforward to support OpenGL ES, which is very close to WebGL. Some initial work is in src/library_gl.js There are some differences though, WebGL doesn't have clientside arrays for example.

It might also be possible to do full OpenGL, by emulating the function calls. This might end up being very slow. Might be interesting to look at ShaderGen, an open source tool to generate shader code for fixed-function code.

http://mew.cx/glsl/shadergen/
http://www.gp32x.com/board/index.php?/topic/55746-shadergen-for-linux/

**Comment by klaiderklai** [comment]
@kripken Hey, sorry for the idiot question, but how can I use this WebGL subset in my project? I.e., how do I include it and where's the API?

**Comment by klaiderklai** [comment]
I'm new to this :(

**Comment by kripken** [comment]
An overview is here:

http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html

You can find GL tests in the test suite which are working examples, can be helpful to read.

**Comment by klaiderklai** [comment]
@kripken I've checked it. I just didn't note the tests. Thank u for ur time
