### ISSUE TITLE
Intermittent OSX build bot failures

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3356]
Not sure yet what's going on, but the OSX bot now started showing random failures, likely related to the parallel test runner.

Run 793 http://clb.demon.fi:8112/builders/osx-incoming/builds/793/steps/Tests-default/logs/stdio failed tests

```
test_64bit_return_value (test_core.asm3i)
test_64bit_return_value (test_core.asm3)
test_64bit_return_value (test_core.asm2)
```

whereas test 794 passed all, and 795 http://clb.demon.fi:8112/builders/osx-incoming/builds/795/steps/Tests-default/logs/stdio failed

```
test_i64_cmp2 (test_core.asm2g)
test_fuzz (test_core.asm3)
```

After run 795, I had the bot clean and do full rebuild of LLVM and optimizer, so 796 http://clb.demon.fi:8112/builders/osx-incoming/builds/796/steps/Tests-default/logs/stdio was built from the same revisions, and this time it failed on

```
test_64bit_return_value (test_core.asm1i)
test_64bit_return_value (test_core.asm1)
test_mathfuncptr (test_core.asm3i)
```

Running the default suite on the same revision on another Mac laptop passed all those failing tests. It does suggest that the parallel test runner has some kind of race condition issue, but I don't yet know what.

**Comment by kripken** [comment]
One guess is an OOM. Those first tests might build some libs using multiple cores. And I think the OS X bot has a quite large number of cores in fact? Running with `EMCC_CORES` at a lower value might avoid this, as we discussed earlier.

**Comment by kripken** [comment]
Another option which might be better is to limit the # of cores the parallel test runner uses, instead of the cores everything else does. Because reducing `EMCC_CORES` will limit single-core speed of the test runner. Limiting the parallel test runner processes seems safer and faster.

**Comment by juj** [comment]
That sounds like a good thing to try. I'll modify the parallel test runner to use a configurable limit of cores, and let's see if it's due to that.

**Comment by kripken** [comment]
Another option is to have the parallel runner run `embuilder.py` before everything, to build all the libs and optimizer etc, so those are not attempted by the various parallel builds. That seems reasonable to do since the parallel runner will need most of those things anyhow. I'll look into adding that as an option.

**Comment by kripken** [comment]
Well, I guess it's silly to add that to the parallel test runner. Could we just add to the bots a one-line command to run before the parallel test runner? Just this:

````
python embuilder.py build libc libcxx libcxx_noexcept libcxxabi gl struct_info native_optimizer
````

**Comment by kripken** [comment]
I noticed that the first test that runs is always `test_64..`, and it uses closure. Closure can take lots of memory, perhaps running 4 or 8 or those is just too much. I renamed the test so it happens later, which should reduce this at least, if that is the cause. But if it is, then we might want to reduce the # of cores so it doesn't happen at all.

**Comment by aidanhs** [comment]
`/Users/clb/.emscripten_cache/libc.bc: error: Invalid record` after just merging my optimizer changes, which can't have had an effect on bc generation - http://clb.demon.fi:8112/builders/osx-incoming/builds/802

The subsequent build (http://clb.demon.fi:8112/builders/osx-incoming/builds/803) fixed it somehow.

**Comment by juj** [comment]
Ok, added the embuilder prerun line, and also now configured the parallel suite to be run with `PARALLEL_SUITE_EMCC_CORES=9 EMCC_CORES=2`, i.e. all the suites are still run in parallel, but each suite only uses two cores to run. That is still quite aggressive, and I'm hoping to keep it that way. If there are still issues, I'll further reduce the number of parallel runs. Let me know if you spot any flukes in the OS X bot.
