### ISSUE TITLE
HTML shell: "All downloads complete" appears when data file download starts

### ISSUE THREAD

**Issue by fdelapena** [emscripten-core/emscripten#3366]
If the .data file is big, this can be confusing. Other files are already downloaded except this one.

Example:
https://easy-rpg.org/play/ib/?window

**Comment by kripken** [comment]
I believe that message comes from the default html shell (`src/shell*.html`). Are you saying that message shows up too early? I'm not sure how to check that.

**Comment by fdelapena** [comment]
Yes, it comes from the default html shell. The message is shown once the runDependencies counter is done. Seems like because .data file is not a script is not counted.
