### ISSUE TITLE
printf of 'long long' value prints double instead of 'long long' textual representation

### ISSUE THREAD

**Issue by httpdigest** [emscripten-core/emscripten#3374]
The following program wrongly prints 9223372036854776000 instead of the correct value 9223372036854775807 (as per limits.h -> libc/bits/limits.h):

``` C
#include <stdio.h>
#include <limits.h>
int main(int argc, char** argv) {
  printf("%lld \n", LLONG_MAX);
  return 0;
}
```

Tested on Firefox Trunk/Nightly with both the 'incoming' branch on Ubuntu as well as the Windows downloadable SDK version 1.29.0.

**Comment by kripken** [comment]
The issue there is that we avoid including a large amount of i64 code when we don't see i64 code being used. If the only use is a printf or other vararg call, we can't tell (without reading the format string) if i64 code is needed.

You can force i64 code inclusion with `-s PRECISE_I64_MATH=2`. This was actually broken, but i fixed it now on incoming.

It's possible we could do better now; we might be able to avoid all that extra i64 code. Not sure. Would be nice if someone had time to look into it.

**Comment by httpdigest** [comment]
But does fastcomp not know that it is handling i64, even for printf?
I have just emitted the LLVM IR for the example program above and it shows this:

`call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([7 x i8]* @.str, i32 0, i32 0), i64 9223372036854775807)`

There, we see the i64 type qualifier. Is that what fastcomp needs?

**Comment by kripken** [comment]
Yes, but we don't need all the i64 support code if all the i64 is doing is being bitcast or or'd or and'd, etc. It's the "heavy" emulation stuff like printing and i64 divide that we try to avoid bringing in.

Seeing an i64 by itself isn't enough to prove we need all that code. Perhaps seeing one passed to a varargs function should indicate so, though? Currently we just notice the direct heavy operations like i64 divide etc. I am ok with adding i64 varargs arguments as an indicator as well, but I don't know how easy that would be.
