### ISSUE TITLE
emcc shared library warning based on file ending rather than '-shared' cmd arg

### ISSUE THREAD

**Issue by httpdigest** [emscripten-core/emscripten#3376]
The invocation of the emcc linker to generate a shared library in the following way:
`./emcc -shared test.o -o libtest.so`
will generate a warning that building shared libraries with Emscripten is currently not possible.

There are projects however, that do this:
`./emcc -shared test.o -o libtest.so.0.0.0`
and then do `ln` to created symbolic links.
In this case, NO warning will be generated and static libraries are _silently_ generated.

So, it seems that the warning will be generated based on the output file name rather than the real link mode, which is specified by `-shared`.
It would be good, if not the output file name is considered but instead the specified link mode.

**Comment by kripken** [comment]
I am not very familiar with those `libx.so.0.0.0` things. Is it also possible for it to be any combo of numbers and any length, e.g. `libx.so.2.5.2.3.4.2.10.1.4.12.9`?

**Comment by juj** [comment]
My familiarity of these is also quite limited, but at least when compiling libraries with CMake on linux, some libraries might generate a shared library file `somelib.so.1.2.3.4` which is the real library file with most specific version number, and then the compiler (or CMake, not sure which?) also emits symbolic links `somelib.so.1.2.3`, `somelib.so.1.2`, `somelib.so.1` and `somelib.so` that all link to `somelib.so.1.2.3.4`. I understood this to be some kind of mechanism to add a limited form of update compatibility, e.g. I could depend on `somelib.so.1.2`, which could always direct to the latest point release of 1.2, but if version 1.3 comes along, my code would not attempt to automatically load with that. Someone probably has the gory details on how this system is supposed to work in detail :)

My understanding is that linux favors version identifiers with four digits `1.2.3.4` to denote `major.minor.bugfix.buildnumber` ( http://stackoverflow.com/questions/65718/what-do-the-numbers-in-a-version-typically-represent-i-e-v1-9-0-1 ), though I do not know if this is a strict convention for this symbolic link hierarchy for `.so` files.

**Comment by weitjong** [comment]
To my understanding the shared library ```soname``` can only have up to 3 parts (major.minor.release). See this [reference](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#AEN49). Apple Clang only accepts 32-bit soname in the format of 0xFFFF.0xFF.0xFF. However, it appears that Linux GCC accepts any number for all the 3 parts.

**Comment by httpdigest** [comment]
Thank you all for having a look at that issue!
In general I'd say you can give `-o` of `gcc` any filename and it will happily build the shared library.
So is it possible that, instead of figuring out how to alter the filename ending pattern to match against the "expected" file names to "work around" the issue, we might instead have fastcomp see the `-shared` command line argument? I don't know how LLVM works and what the internal model is in that regards, but I reckon it should be possible.
