### ISSUE TITLE
emrun stdout/stderr capture race condition

### ISSUE THREAD

**Issue by kg** [emscripten-core/emscripten#3392]
There's a race condition between emrun setup and emscripten module startup.

Emrun uses a window.load handler to replace print and printerr, but this can happen after some code has already run. In my case, I'm adding a `preInit` handler:

``` javascript
Module["preInit"].push(function () {
  Module.print("test");
});
```

The preInit handler runs and dumps "test" into the browser's output panel, but emrun never captures this output, because the emrun handlers are installed _after_ the preInit handler has run.

I think making emrun use preInit would solve this.

**Comment by kg** [comment]
Putting this in my preInit handler seems to have made things work okay:

```javascript

    if (typeof (emrun_register_handlers) === "function") {
        // Run the handler registration early to fix a race condition
        emrun_register_handlers();

        // Prevent it from running again
        window.removeEventListener("load", emrun_register_handlers);
        emrun_register_handlers = null;
    }
 ```

**Comment by juj** [comment]
The scope of emrun has been primarily to be used in conjunction with `printf` and `std::cout`, i.e. the C runtime print functions. Manually initializing for now sounds probably like the simplest way for code that needs to log before the C runtime is up. The issue with `Module['preinit']` would then be if existing code unconditionally sets preInit to their own content. I think the proper fix is probably to remove emrun from using the pre and post js features, and instead use `#ifdef`s to directly inject the appropriate logging, that way there is no lose the registration.

**Comment by kg** [comment]
Sounds good. Thanks.
