### ISSUE TITLE
how to emcc update?

### ISSUE THREAD

**Issue by steveboks** [emscripten-core/emscripten#3397]
hi. my emcc version 1.10.
how to try to 1.3 update...problem..
The question is how're you doing?
Please tell me.

**Comment by juj** [comment]
Emscripten SDK downloads are available at links from https://groups.google.com/d/msg/emscripten-discuss/b06iW6T2uSw/7Pq2gT3keSgJ . Try downloading and installing one of those packages, depending on which OS you are on.
