### ISSUE TITLE
Weird 8 bpp mode without SDL_HWPALETTE in SDL 1

### ISSUE THREAD

**Issue by dreamlayers** [emscripten-core/emscripten#3400]
It seems [Emscripten uses the SDL_HWPALETTE flag given to SDL_SetVideoMode() to decide whether to set an 8 bpp mode](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L336). The [depth parameter of SDL_SetVideoMode() seems to be ignored](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L1406). There is still a way to use an 8 bpp mode without that flag, [by setting a palette](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L1561). However, that mode is weird and buggy.

Since the depth is ignored `surface->format` will show that you have a 32 bpp mode. Also, `surface->pitch` will be 4 \* width, but the 8 bpp data needs to be packed in the first width bytes of every line, with the remaining 3 \* width bytes being unused. The conversion to 32 bpp is done by a [less optimized routine in SDL_UnlockSurface()](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L1631) instead of [SDL.copyIndexedColorData(), which is used with SDL_HWPALETTE](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L417). Unlike SDL.copyIndexedColorData(), the alpha values are not set, so `SDL.defaults.opaqueFrontBuffer == true` is required. It seems the [alpha values are set in SDL_LockSurface()](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L1509). The code setting them there seems otherwise unnecessary, because in a 32 bpp mode they would be [set in a more optimized way in SDL_UnlockSurface()](https://github.com/kripken/emscripten/blob/c0e750b7cae1b13acc41fd71efe72ed8c611b779/src/library_sdl.js#L1602). Yet it still runs in 32 bpp and wastes CPU time. Also in SDL_LockSurface() it's possible to to use `SDL.defaults.copyOnLock == true`, but that just copies RGB values, which an application which set an 8 bpp mode would not expect. This also means simply doing `SDL_LockSurface(); SDL_UnlockSurface();` can corrupt the screen.

According to [SDL_SetVideoMode() documentation](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetvideomode.html), `SDL_HWPALETTE` means:

> Give SDL exclusive palette access. Without this flag you may not always get the the colors you request with SDL_SetColors or SDL_SetPalette.

I interpret this to mean that if you set an 8 bpp mode without the flag, you still get an 8 bpp mode, but you may use a shared system palette. Some colours might be wrong or mapped to the closest system colour, and some palette effects might not work. Since Emscripten doesn't have access to a system palette and is always able to put exact colours in the 32 bpp canvas, then SDL_HWPALETTE seems irrelevant here. It might make a difference [when blitting from an RGB to an 8 bpp surface](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetpalette.html), but that's not implemented yet.

It seems to me calling SDL_SetVideoMode with `depth == 8` but without SDL_HWPALETTE should result in the same mode as the current mode with SDL_HWPALETTE. It also seems that code which is only used for supporting this weird 8 bpp mode should be removed.

The following code can be used for exploring this issue:

``` C
#include <stdlib.h>
#include <stdio.h>
#include <SDL.h>

static void sdlError(const char *str) 
{
    fprintf(stderr, "Error at %s: %s\n", str, SDL_GetError());
    exit(1);
}

#define WIDTH 256
#define HEIGHT 256

int main(int argc, char *argv[])
{
    SDL_Surface *surface;
    SDL_Color colors[256];
    int i, j;

    if (SDL_Init(SDL_INIT_VIDEO) != 0) sdlError("SDL_Init");
    surface = SDL_SetVideoMode(WIDTH, HEIGHT, 8,
    /* SDL video mode flags are below. You can add SDL_HWPALETTE or others. */
                               0);
    if (surface == NULL) sdlError("SDL_SetVideoMode");

    for(i = 0; i < 256; i++){
      colors[i].r = i;
      colors[i].g = i;
      colors[i].b = 255 - i;
    }
    printf("SDL_SetColors() returns %i\n",
           SDL_SetColors(surface, colors, 0, 256));

    if (SDL_LockSurface(surface) != 0) sdlError("SDL_LockSurface 1");
    printf("pitch = %i\n", surface->pitch);
    printf("pixel format: bitpp = %i, bytepp = %i\n", 
           surface->format->BitsPerPixel, surface->format->BytesPerPixel);
    for (i = 0; i < HEIGHT; i++) {
        for (j = 0; j < WIDTH; j++) {
            ((Uint8*)(surface->pixels))[i * surface->pitch + j] = i ^ j;
        }
    }
    SDL_UnlockSurface(surface);
    if (SDL_Flip(surface) != 0) sdlError("SDL_Flip 1");

#if 1
    /* This corrupts the screen in Emscripten without SDL_HWPALETTE */
    if (SDL_LockSurface(surface) != 0) sdlError("SDL_LockSurface 2");
    SDL_UnlockSurface(surface);
    if (SDL_Flip(surface) != 0) sdlError("SDL_Flip 2");
#endif

    return 0;
}
```

**Comment by kripken** [comment]
Might be a good idea to use git blame/history to see who wrote those bits (I don't think it was me - hopefully it wasn't ;) and cc them.

**Comment by caiiiycuk** [comment]
Hi. When this code was added, i worked on porting openttd to js. Original game was worked in SDL_HWPALETTE mode, so i decided to implement this mode. I tried to make my changes in isolation of other modes, because i was afraid to break something. In my experiences HWPLATTE mode is more performant than default mode.

**BUT**, current imentation does not support copyOnLock in [SDL_LockSurface](https://github.com/kripken/emscripten/blob/incoming/src/library_sdl.js#L1521). So you can`t mix direct writing to canvas (used in SDL_FillRect and [SDL.blitSurface](https://github.com/kripken/emscripten/blob/incoming/src/library_sdl.js#L507)) and pixel manipulation. Unfortunettly many games do that (for example load image in SDL video buffer and then blit it). Implementing copyOnLock will significant decrease perfomance. However this problem is related to all modes. 

After reading explanation by @dreamlayers, i think that HWPALLETE mode should be enabled automatically when 8bpp depth is set.

**Comment by kripken** [comment]
Sounds ok to me.

**Comment by dreamlayers** [comment]
So, should SDL_SetVideoMode() simply set the  SDL_HWPALETTE flag if the depth parameter is 8?

I think it would make more sense to add a depth parameter to makeSurface(), but that would involve changes at other calls to that function, and I'm not sure if this is wanted. I'm okay with simply setting SDL_HWPALETTE in SDL_SetVideoMode().

I could make pull request with this plus removal of the old code mentioned earlier that's is only needed for 8 bpp without SDL_HWPALETTE.

There is probably some code using 8 bpp without SDL_HWPALETTE out there, and it will break, hitting `throw 'CopyOnLock is not supported for SDL_LockSurface with SDL_HWPALETTE flag set' + new Error().stack;`. I actually had that in one program, ported back when I was first learning about Emscripten. Back then I didn't fully understand, and after seeing that error message, I removed SDL_HWPALETTE, and the program worked perfectly.  Breaking such code is beneficial in a way. It's unlikely that any 8 bpp program actually uses the 32 bpp format data copied back from the canvas. The copying was just wasting CPU time.

**Comment by caiiiycuk** [comment]
>> The copying was just wasting CPU time.

I think that performance problem is less important than compatibility problem. For performance tuning there are disableCopyOnLock flag.

**Comment by kripken** [comment]
If it's cleaner I am ok with changing `makeSurface`. But if you feel just setting that value in `SDL_SetVideoMode` is the more straightforward solution, I am ok with that too.

**Comment by SlightlyCyborg** [comment]
@caiiiycuk  
> So you can`t mix direct writing to canvas (used in SDL_FillRect and SDL.blitSurface) and pixel manipulation. Unfortunettly many games do that (for example load image in SDL video buffer and then blit it). Implementing copyOnLock will significant decrease perfomance. However this problem is related to all modes. 

Is this why I get an error "surfData undefined" when I try to load an img using SDL_image and then try to then do SDL_Fillrect?

I've been trying to beat this bug for a couple of hours.

**Comment by caiiiycuk** [comment]
@SlightlyCyborg I don`t think so. "surfData undefined" means that emscripten unable to create surface by some reason. Looks like a bug.

**Comment by SlightlyCyborg** [comment]
@caiiiycuk [Here](https://gist.github.com/SlightlyCyborg/3bb1294ae8da228ad730) is the minimum gist isolating the problem. If I put FillRect into the emscripten helloworld program, it fails
