### ISSUE TITLE
emcc -v version issue. I need your help.

### ISSUE THREAD

**Issue by steveboks** [emscripten-core/emscripten#3402]
Hi, kripken
I'm Bokseong KIM. in Korea

this issue is emcc version check.
This is a problem? 
emcc -v version is 1.10.0
./emcc -v version is 1.31.0 and WARNING message.
I need your help.
thanks.
## the codes below path in accordance with version looks different.

root@ubuntu:~# emcc -v
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.10.0
clang version 3.6.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 1e87fd50b108143298407eb4b9a802cea4662937) (https://github.com/kripken/emscripten-fastcomp/ cb8b737f3d49e9edd214d5214db6ace92b5e68ea)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64

---

root@ubuntu:~/emsdk_portable/emscripten/master# ./emcc -v
WARNING  root: (Emscripten: system change: 1.31.0|asmjs-unknown-emscripten|/root/emsdk_portable/clang/fastcomp/build_master_64/bin|3.6 vs 1.10.0|le32-unknown-nacl|/root/emsdk_portable/clang/fastcomp/build_master_64/bin|3.6.0, clearing cache)
INFO     root: (Emscripten: Running sanity checks)
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.31.0
clang version 3.6.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 1e87fd50b108143298407eb4b9a802cea4662937) (https://github.com/kripken/emscripten-fastcomp/ cb8b737f3d49e9edd214d5214db6ace92b5e68ea)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
root@ubuntu:~/emsdk_portable/emscripten/master#

**Comment by fabiosantoscode** [comment]
You seem to have two emcc on your system.

If you do `which emcc` you will probably not find the emcc in your directory. So the problem is in your PATH.

About the warning message. If you compile from source you need to make sure all your emscripten repositories were compiled in the same branch. So if you checked out the main repository (this one) in `incoming` you have to checkout the other two in `incoming` as well.

**Comment by ZengruiWang** [comment]
As indicated by @fabiosantoscode there are two versions of emcc on you system, I guess apart from compiling and building the portable emscripten by yourself, you still used sudo apt-get install emscripten installed an old version of emscripten(1.10.0). You could try to uninstall to old version and see if it solves your problem.
