### ISSUE TITLE
noinline attribute is not respected in -O1 and above

### ISSUE THREAD

**Issue by httpdigest** [emscripten-core/emscripten#3409]
In the resulting asm.js code the function `someNumber` is being inlined and the `result` constant-folded, which I wanted to avoid using the noinline attribute. But that did only work with `-O0` (explicitly or implicit) but not with `-O1` and above:

``` C
#include <stdio.h>
float __attribute__ ((noinline)) someNumber() {
  return 1E+2f;
}
int main(int argc, char** argv) {
  float result = 1E+37f * someNumber();
  printf("%f \n", result);
  return 0;
}
```

**Comment by juj** [comment]
Hmm, this looks like a regression if so (didn't test this though). I've often used noinline before on Emscripten code when debugging, and it has worked ok for me. That was in LLVM 3.4 time though, and we are now up at LLVM 3.6. Perhaps something has changed in there.

**Comment by kripken** [comment]
I still see the method emitted separately, and still see it marked `noinline` in the LLVM IR, even in -O1. It does constant fold, so I guess LLVM doesn't consider that "inlining" - it folds away into methods when it can.

Might be worth filing an upstream bug on LLVM if you think that is wrong.

**Comment by httpdigest** [comment]
Ah, interesting find. I was kinda assuming that folding can only occur if inlining also happens, so I was assuming that it does inline and erase the other function, even though I did not check that this really was the case.
Personally, I am okay with that then.

**Comment by waywardmonkeys** [comment]
Can this be closed then?
