### ISSUE TITLE
DeviceMotion & OrientationChange reporting NOT_SUPPORTED

### ISSUE THREAD

**Issue by pixelnerve** [emscripten-core/emscripten#3411]
Hello,
I'm just testing these 2 options and i'm getting a not supported from the set callback.
Are these implemented or still under the works ?

thanks

**Comment by juj** [comment]
The return value NOT_SUPPORTED means that the browser you are running it in does not support the features. See https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L1155 and e.g. http://www.sitepoint.com/using-device-orientation-html5/ . Can you check if your environment actually does support those features?

**Comment by pixelnerve** [comment]
I'm testing on 3 devices, iphone, nexus7 and note4. All with latest Safari, Chrome and Firefox.

I wrote a small test using js and it reports success for OrientationChange.

Using Emscripten 1.30 the only one that returns success is DeviceOrientation. Both others DeviceMotion and OrientationChange report not supported.

**Comment by pixelnerve** [comment]
I've used window.orientation and window.onorientationchange. 
Not sure why the window.screen and addEventListener to window.screen check on the function.

**Comment by pixelnerve** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation It says screen.orientation is experimental and is not supported on anything other than firefox.
