### ISSUE TITLE
SDL_KeyboardEvent keysym.sym has wrong.

### ISSUE THREAD

**Issue by cloud9370** [emscripten-core/emscripten#3439]
Hi, I'm using emscripten 1.30.0 Windows version.

While I am trying the keysym.sym to process key event.
I found something incorrect.

switch(sym)
{...}

Couldn't match SDLK_MINUS, SDLK_EQUALS, SDLK_SEMICOLON
The variable sym got value in hex-decimal are 0xbd, 0xbb, 0xba.

Please check if any problem on there, thanks.

**Comment by kripken** [comment]
Not sure I understand that. If you can provide a testcase showing the issue, that would be best.

**Comment by cloud9370** [comment]
I take screen shot.

![embug1](https://cloud.githubusercontent.com/assets/7732799/7529289/83dee460-f568-11e4-8614-2862c4e25fb8.png)
![embug2](https://cloud.githubusercontent.com/assets/7732799/7529292/899b3cbe-f568-11e4-8464-2657b8fa5ae4.png)
