### ISSUE TITLE
keyboard event should be released by SDL_Quit

### ISSUE THREAD

**Issue by parisseb** [emscripten-core/emscripten#3445]
inside library_sdl.js, SDL_Quit should look like
  SDL_Quit: function() {
    _SDL_AudioQuit();
      var keyboardListeningElement = Module['keyboardListeningElement'] || document;
      keyboardListeningElement.removeEventListener("keydown", SDL.receiveEvent);
      keyboardListeningElement.removeEventListener("keyup", SDL.receiveEvent);
      keyboardListeningElement.removeEventListener("keypress", SDL.receiveEvent);
    Module.print('SDL_Quit called (and ignored)');
  },
otherwise you can't access the keyboard in an input field anymore after using SDL.

**Comment by kripken** [comment]
To be sure I understand the issue, I tried to write a test, but it doesn't show the problem - the event still gets noticed even though SDL is still capturing events. Maybe you can take a look at it? I have no idea what I am doing wrong.

````
#include <stdio.h>
#include <SDL/SDL.h>
#include <SDL/SDL_ttf.h>
#include <assert.h>
#include <emscripten.h>

void main_2();

void EMSCRIPTEN_KEEPALIVE quit() {
  printf("quit!\n");
  SDL_Quit();
}

int main() {
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Surface *screen = SDL_SetVideoMode(300, 500, 32, SDL_HWSURFACE);

  EM_ASM({
    var STATE = 3;
    var abort = false;

    document.body.addEventListener('keydown', function() {
      Module.print('got event');
      var xhr = new XMLHttpRequest();
      xhr.open('GET', 'http://localhost:8888/report_result?' + STATE);
      xhr.send();
      setTimeout(function() {
        window.close();
      }, 1000);
      abort = true;
    });

    function sendEvent() {
      var event = document.createEvent("KeyboardEvent");
      event.initKeyEvent("keydown", true, true, window,
                         0, 0, 0, 0,
                         50, 50);
      Module['canvas'].dispatchEvent(event);
    }

    Module.print('send a failure');
    sendEvent(); // should fail, events are captured

    setTimeout(function() {
      if (abort) return;
      Module.print('quitting and sending a success');
      Module._quit();
      sendEvent(); // should succeed, SDL_Quit should free the events
    }, 2000);
  });
}
````

**Comment by parisseb** [comment]
Hello,

Sorry, my understanding of javascript/c code interaction is almost void, 
I do not understand what you are doing. I did experience a problem with 
my first attempt to add a graphic output to my computer algebra system 
compiled with emscripten. The compiled code is here
http://www-fourier.ujf-grenoble.fr/~parisse/webxcas.html
You can use it like a super-calculator, for example
ifactor(2^128+1)
will factor this integer, but there is no graphical output available 
currently. If you try a plotting function like
plot(sin(x))
you will get the output of one of the emscripten SDL test (I'm going to 
change that with an SDL graphical output). With the modification in 
SDL_Quit() you can enter new inputs in the input field, but without, the 
input field seems frozen (unless something has changed, I'm with emsdk 
portable 1.30.0).
The C++ source code is available here:
http://www-fourier.ujf-grenoble.fr/~parisse/giac/emgiac.tgz
it should compile with the build command
