### ISSUE TITLE
Schedule a syncfs() call on fclose() and/or other disk operations

### ISSUE THREAD

**Issue by timdream** [emscripten-core/emscripten#3453]
I propose we should implement a scheduler and call `syncfs()` periodically for pending disk ops, and when the Emscripten runtime ends.

This is somewhat similar to #2492 and what's discussed in #3398. So after searches for answers, I realized `fclose()` indeed does not imply `fsync` at all, and it is indeed a common misconception often asked on StackOverflow. `man 2 close` while [clarify](http://linux.die.net/man/2/close), also states when the content should actually be written:

> A successful close does not guarantee that the data has been successfully saved to disk, as the kernel defers writes.

I believe when translating the analogy to Emscripten, this means the programs rely on Emscripten to schedule disk writes to IDBFS, instead of never write to the disk as Emscripten currently do.

Thought?

**Comment by kripken** [comment]
We could start an fsync when the runtime shuts down, but it might not complete in time before the page is closed. So it would not be a guarantee. I'm not sure if there would be a way to fix that. Preventing the page from being closed is possible I believe, but not sure we want that.

We could do an fsync every so frames, however, it might be a very slow operation, and I'm worried about surprising people with it.

Overall it seems safer to leave this to developers to do in a direct manner. However, we could also add an option to do it automatically at times, perhaps?

**Comment by timdream** [comment]
> We could start an fsync when the runtime shuts down, but it might not complete in time before the page is closed. So it would not be a guarantee. I'm not sure if there would be a way to fix that. Preventing the page from being closed is possible I believe, but not sure we want that.

From IDBFS point of view, if an transaction is not completed before the page is closed, it would get rolled back. I agree with you there is nothing we could do in that case. However, on a desktop/laptop this shouldn't be possible unless disk i/o is slower than the user.

> We could do an fsync every so frames, however, it might be a very slow operation, and I'm worried about surprising people with it.
> Overall it seems safer to leave this to developers to do in a direct manner. However, we could also add an option to do it automatically at times, perhaps?

Let's implement it behind a new build flag perhaps? It can either be implemented in IDBFS or FS -- depend on how useful this can be for filesystems other than IDBFS.

**Comment by timdream** [comment]
Wait, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Warning_About_Browser_Shutdown), transaction is not aborted when the page is closed but only when the browser exits.

**Comment by kripken** [comment]
The page might also be closed before the transaction is started.- depending on how this is implemented. Overall this seems risky.

Another concern is when do you do a transaction - after every `fclose()`? Then if 1,000 files are fclosed, you get 1,000 transactions, which is bad. I think The proper solution is to call `fsync()` once after those 1,000 `fclose()`s.

Perhaps one way to do it is to log something on `fclose()`, and do one fsync every 10 seconds at most, if there has been one disk operation in that time. Not simple though. But as an optional flag perhaps worth trying.

**Comment by timdream** [comment]
> The page might also be closed before the transaction is started.- depending on how this is implemented. Overall this seems risky.

The point here being we are protected by transactions -- if we lost the changes on the last one the database is still kept in a clean state (i.e. the state when the transaction before that finishes).

> Another concern is when do you do a transaction - after every fclose()? Then if 1,000 files are fclosed, you get 1,000 transactions, which is bad. I think the proper solution is to call fsync() once after those 1,000 fclose()s. 
> Perhaps one way to do it is to log something on fclose(), and do one fsync every 10 seconds at most, if there has been one disk operation in that time. Not simple though. But as an optional flag perhaps worth trying.

The algorithm I have in mind is pretty close to what you proposed :) -- Set a dirty state and a timer when there is an `fclose`. Don't set another timer when the dirty flag is already set. When the timer fires, start the transaction and remove the dirty state. This should merge the transactions so we don't get 1,000 transactions for 1,000 fclosed files.

This can even be optimize further by tracking the dirty state per file (instead of per mount), but I can start by tracking all `syncfs` calls first (inc. calls from `fsync` in previous patch and also manual calls).

**Comment by kripken** [comment]
Sounds reasonable. Hard to say what will work here, we'll just need to experiment and see I think. But that sounds like a good plan to start with.

**Comment by timdream** [comment]
This is the current WIP (with tests): https://github.com/kripken/emscripten/compare/kripken:incoming...timdream:deferred-syncfs-on-write

I am able to trigger a deferred `syncfs()` call after `mknod`, `rename`, `close`, and `unlink` calls. Still investigating how to add a trigger to start `syncfs()` right away when the runtime exits if the dirty flag is there. `addOnPostRun` nor `addOnExit` does not do what I want. `addOnPostRun` triggers at `emscripten_exit_with_live_runtime()` call and `addOnExit` doesn't seem to get invoked in the browser test environment.

**Comment by timdream** [comment]
I think I've figured out why `addOnExit` didn't work.

**Comment by timdream** [comment]
I have pushed a new commit and will be submitting my pull request now.
`addOnExit` callbacks does not get invoked in the first test script because the runtime never exits, since `emscripten_exit_with_live_runtime()` is called. Runtime only ends, instead, when emscripten_force_exit()` is called there. I created another test for that anyway just to ensure we don't squeeze to much thing in one test.
