### ISSUE TITLE
FS_unlink not available

### ISSUE THREAD

**Issue by tomas** [emscripten-core/emscripten#3462]
Hi,

The [advanced FS API](https://kripken.github.io/emscripten-site/docs/api_reference/advanced-apis.html#advanced-file-system-api) provides a way to create files (via `Module['FS_createDataFile']`), but it doesn't provide a way to delete them. Is this on purpose?

A simple `Module["FS_unlink"] = FS.unlink;` after [this line](https://github.com/kripken/emscripten/blob/master/src/library_fs.js#L14) would do the trick. :)

Thanks!

**Comment by kripken** [comment]
That line is indeed kind of a hack. I think it is enough for the test suite, basically. We should probably refactor that into something cleaner, and I agree, we should add `unlink` while we are at it.

This would be pretty easy to do, I could guide you or someone else that is interested to do this, if that would help.

**Comment by tomas** [comment]
I actually have a workaround for this using the --js-transform at compile time. 

```
out.replace('FS.createDevice;', 'FS.createDevice; Module["FS_unlink"] = FS.unlink;');
```

It would be prettier not having to, though. :)

**Comment by CWelshE** [comment]
I would be interested in fixing this! I would appreciate any guidance offered to me, but I'll attempt it anyways :)

**Comment by kripken** [comment]
The code is in `src/library_fs.js` at the very top. The real question is if we can think of a nicer way to do that, that makes it more extensible. I don't have any ideas myself.

**Comment by CWelshE** [comment]
I might be misunderstanding the problem, but what if we generated the strings instead? For example:
`'Module["FS_createFolder"] = FS.createFolder;'` could be generated, instead, by some Array/Object/File containing `createFolder` (and _n_ other items), which would make it a little easier to maintain.

**Comment by kripken** [comment]
Yes, I think that would be an improvement.

I wonder if we should have that be an option in `settings.js`, so people can easily add or remove from it.

**Comment by CWelshE** [comment]
Seems like that would be a good fit for the format!

**Comment by CWelshE** [comment]
How does one reference an object in `settings.js` from another file? Is it just globally scoped?

**Comment by kripken** [comment]
Yes, `settings.js` is run in the global scope of the js compiler, so it is available in other files. In `library*.js` files, you can access it in `{{{ ... }}}` blocks, which we simply eval, also in the global scope of the compiler.
