### ISSUE TITLE
Embind and references

### ISSUE THREAD

**Issue by AlexPerrot** [emscripten-core/emscripten#3480]
Hello,

I made a simple API that uses method chaining in C++. This is achieved by returning a reference from member function, like this :

``` c++
class Chain {
    Chain& foo() {
        return *this;
    }

   Chain& bar() {
        return *this;
    }
};
```

So, I can write `Chain().foo().bar()`.

Now, when binding this with embind, references are copies of the original object, so memory leaks since I should call `delete` after each function call, preventing chaining.
I know I have several solutions to deal with this, namely using pointers, either directly in my class or in the embind bindings, but those are not very elegant solutions.

Is there any reason for which embind makes copies when using reference instead of using the same pointer (at least for objects) ?
If it is possible to implement reference support, I am willing to participate. Where should I start ?

**Comment by matthiasI** [comment]
I also realized that returning a pointer is different from returning a reference. In my eyes this is a bit an unexpected behavior.
I don't know the reasons. If it is not possible to do that, I think it would be at least good to warn about, similar as it is for pointers with allow_raw_pointers.

**Comment by SergeySeroshtan** [comment]
Will be nice to implement this feature!

**Comment by AlexPerrot** [comment]
I have been making tests to implement this feature in the last few days.

The simplest way I have to do this client-side is :
``` c++
template <typename T, T> struct proxy;

template <typename T, typename R, typename ...Args, R (T::*mf)(Args...)>
struct proxy<R (T::*)(Args...), mf>
{
	using ptr = typename std::add_pointer<typename std::remove_reference<R>::type>::type;
    static ptr call(T & obj, Args &&... args)
    {
        return &((obj.*mf)(std::forward<Args>(args)...));
    }
};

#define RETURN_POINTER(value) &proxy<decltype(value), (value)>::call
```

This way, you can do `class_(...).function("myFunc",RETURN_POINTER(&myClass::myFunc), allow_raw_pointers());`. You can also add another specialization for free functions.

I have tried several ways of adding support for reference in embind, but every time, it breaks something existing. For now, references are treated as regular objects, so they are sometimes copied and sometimes not. There also seem to be tests in `test_embind` that rely on references being copied, which is not what they are supposed to do in C++. The problems I encountered concern mainly (but not exlusively) `val`, `string`, smart pointers and inheritance.

If it is not possible to transparent support for references, at least having a policy similar to `allow_raw_pointers()` would be nice. However, this would require extensive changes to embind. Namely, being able to specify independently (not from the client side, but internally based on the policy) for each return value and argument its real type and the desired binding type.

**Comment by isc30** [comment]
what if the implementation is specialized for std::reference_wrapper and gets unwrapped when creating the JS object?
