### ISSUE TITLE
Is there a way to build a library as a separate js file from your main application

### ISSUE THREAD

**Issue by whackashoe** [emscripten-core/emscripten#3483]
Is there anyway for example I could have sdl.asm.js & application.asm.js, and index.html which has:

```
<script src="sdl.asm.js"></script>
<script src="application.asm.js"></script>
```

I understand if application is a normal js file this could work, but can we have shared libraries working this way?

If this isn't possible currently, consider this a feature request :dancers:

**Comment by kripken** [comment]
Recent emscripten versions do have dynamic linking support,

https://github.com/kripken/emscripten/wiki/Linking

As this is a fairly new feature, it may have bugs. Please report any issues you find.
