### ISSUE TITLE
Dynamically add a C++ function to emscripten::val

### ISSUE THREAD

**Issue by iboB** [emscripten-core/emscripten#3488]
I want to dynamically bind some C++ code to JavaScript. The thing is the functions from C++ I need to expose are not known at compile time, so I want to add them to js objects dynamically, depending on various conditions.

Here is some _(pseudo-)_code of what I basically need:

```
val foo(val args) 
{
       // do something with args 
       // proxy to the real foo
}

val v = val::object();
v.add_class_function("foo", foo);
```

Is something similar possible to do?

**Comment by danguafer** [comment]
I have been looking for a feature like this for using along with addEventListener.
