### ISSUE TITLE
More atomic bitwise ops?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3503]
From the bitwise ops, only atomic and, or and xor operations are supported. There exists atomic nand operation and some others, which are not currently implemented. Those seem to be extremely rare, but if there is a need, those could be added. Atomic NAND in particular is a bit ill-defined since there is historical conflict whether the operation is supposed to be `(x & ~y)` or `~(x & y)`.

**Comment by lars-t-hansen** [comment]
GCC has an atomic "nand" intrinsic but C++11 does not provide that information.

Also, it seems that the first of your interpretations can be supported directly with "and".  For its older "__sync" primitives, gcc documents the second behavior, though it has no documentation for its modern "__atomic" primitives.  Do you have other documentation and/or documentation for other compilers?
