### ISSUE TITLE
Implement __lock, __unlock, __lockfile and __unlockfile.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3506]
The pthreads implementation is currently missing a few internal musl lock operations, see https://github.com/kripken/emscripten/blob/incoming/src/library.js#L8430 . Add these in.

**Comment by kripken** [comment]
I believe these may come in "for free" if we merge the syscalls pull, assuming we decide to do so. Just noting that here since it might motivate leaving this for later.

**Comment by juj** [comment]
Yeah, that might be an option, though this in particular should be more work in adding a test, impl. should be easy. Btw, these bug reports are written in a rather imperative tone, mostly to serve as a "note to self" documentation for me, since I anticipate there will likely be some weeks of a gap, before I have time to focus on these again.
