### ISSUE TITLE
Beware use of c++11 nullptr in global initializers.

### ISSUE THREAD

**Issue by PaulAustin** [emscripten-core/emscripten#3511]
I'll post this as an FYI since I only encountered the problem on my emscripten builds, not other clang, Xcode, visual studio.

//Case 1  constant initializer: foo1 is guaranteed to be NULL before any global constructor is called.
void\* foo1 = NULL; 

//Case 2 using c++11's nullptr. This is much more vague, may be implemented by global constructor.
void\* foo2 = nullptr;  

In the second case foo2 may be non null when other global initializers. Given C++11's definition is seems like this may be "reasonable" behavior, though not so helpful. (If so just close this issue) But in my desktop builds it is treated like a constant initializer. For now I'll just stick to NULL.

**Comment by kripken** [comment]
Which version of emscripten is that with? On incoming 1.33.0, LLVM 3.7, I don't see a global constructor created for assigning a nullptr. Perhaps this was optimized recently, if you are using an earlier version?

**Comment by juj** [comment]
This sounds scary. Assigning a `nullptr`, `NULL` or `0` should definitely be initialized to zero immediately at program startup time without a dynamic initializer. @PaulAustin , would you have a test case to show where you are seeing this?
