### ISSUE TITLE
code with bitfields miscompiled at -O1 and above on x86_64-unknown-linux-gnu 

### ISSUE THREAD

**Issue by zhendongsu** [emscripten-core/emscripten#3522]
The following code (small.c) seems to be miscompiled at -O1 and above: 

```
int printf (const char *, ...);

struct S0
{
  int f0:32;
  int f1:32;
  int f2:32;
  int f3:32;
  int f4:32;
} a = {0, 0, 1, 0, 0};

int b;

int
main ()
{
  struct S0 c = a;
  for (; b < 2; b++)
    c.f0 = 0;
  printf ("%d\n", c.f2);
  return 0;
}
```

$ emcc -v
emcc (Emscripten gcc/clang-like replacement) 1.33.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 2a66b5ffba63f1e36458d41fafc2874a1abf63fe) (https://github.com/kripken/emscripten-fastcomp/ e2939f6878307899c17d1a23f51ba3fe5afbe6af)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
$ 
$ emcc -O0 small.c
$ node ./a.out.js
1

$ 
$ emcc -O1 small.c
$ node ./a.out.js
0

$

**Comment by kripken** [comment]
It looks like some phis have `undefs` in them, leading to zero values where they shouldn't be. I believe they are caused by https://github.com/kripken/emscripten-fastcomp/blob/c439cf259d109871a191d311e69fbff896213200/lib/Transforms/NaCl/ExpandLargeIntegers.cpp#L412

I found it easier to debug on this modified testcase:

````
#include <stdio.h>

struct S0
{
  int f0:32;
  int f1:32;
  int f2:32;
  int f3:32;
  int f4:32;
} a = {1, 1, 1, 1, 1};

int
main ()
{
  printf ("     %d:%d:%d:%d:%d\n", a.f0, a.f1, a.f2, a.f3, a.f4);
  for (volatile int b = 0; b < 2; b++) {
    a.f2 = 0;
    printf ("(%d)  %d:%d:%d:%d:%d\n", b, a.f0, a.f1, a.f2, a.f3, a.f4);
  }
  printf ("     %d:%d:%d:%d:%d\n", a.f0, a.f1, a.f2, a.f3, a.f4);
  return 0;
}
````

**Comment by kripken** [comment]
Filed upstream as https://code.google.com/p/nativeclient/issues/detail?id=4204
