### ISSUE TITLE
Update uglify

### ISSUE THREAD

**Issue by gagern** [emscripten-core/emscripten#3523]
Our version of uglify is some pretty ancient 1.0.7. Working on #3326 I noticed in particular that it only generates `\u????` escapes in string literals, never `\x??` where that is possible. mishoo/UglifyJS2@81f5efe39a6d44d3037dda8bcff01195f5699139 from two years ago fixed that. On the other hand, reading the [history of that directory](https://github.com/kripken/emscripten/commits/master/tools/eliminator/node_modules) I see that there were quite a number of customizations to the code. This suggests several possible approaches.
1. Keep the code base in emscripten as is, only cherry-pick selected features as the need arises
2. Make an effort to cherry-pick as many featurs and fixes as possible into the emscripten tree
3. Set up a branch of uglify-js, and replay emscripten changes in there, dealing with conflicts as they arise, then use one of the following ways to include that into the emscripten tree
4. Commit a plain vanilla npm install of uglify-js, then check which of the modifications are still required
5. Commit a plain vanilla npm install of uglify-js and hope that all custom modifications are no longer needed, or that if this still breaks anything then we have a test case to detect that breakage
6. Make uglify-js (and its dependencies?) submodules of the emscripten git repository
7. Drop uglify-js from the emscripten repository, and use npm to install it and its dependencies (where would such an `npm` call go, since we have no top level `Makefile` or similar?)

Personally, I consider having a third party npm project committed to the emscripten code tree to be a bad thing. I'd prefer an `npm` call to install things. I guess that any features we need, others might need as well, so if there is anything to be modified, we should try to get those modifications included upstream. Until then we could let the `package.json` refer to a github commit on some branch which includes the neccessary features.

Here is a closer look at all the commits which affect that directory:
- 4d12c91bfb26979d00714843a038f916629e040d Added a redundant-variable eliminator script and its dependencies.  
  _Initial import, including coffeescript as a dependency._
- 536bad16ce88bad71fe94af285f9a9d2f721b2ad Updated UglifyJS to preserve object key quotedness (Closure Compiler compatibility).  
  _Do we want to run closure after uglify, or rather instead of uglify?_
- c746d2005286626f8a468b32df59073c7ec88639 Made sure uglify's code generator re-parenthesizes anonymous functions.  
  _Current uglify apparently does that._
- be2dafadec0e5a39e3e55a3663183ca6a8dd5d8e Coffee-script fix for new node.js  
  86c90950a8ea0b942acb8fd17798b30c00fd72fa update coffeescript to d8905e2  
  a79d6118ba9af2cdcdc17a43ae2d03327c9e87e3 remove no longer needed coffeescript  
  2d9ed2565414ec926436817f47578055a99ce1d5 kill symlinks to coffeescript  
  _Current uglify no longer uses coffeescript._
- 0c3cb9305358d34d0f7cdcee6cdb3d60a7b4b507 Delete uglify code that was only needed for compression.  
  0f73e28bab1c1b8caa8f7b77692bebd705bebe6a Map source lines for assignment statements.  
  d680f5e81b4bae6cbc46ba04b24c5809679d0bcc Implement source maps for optimized builds.  
  5459b3543fdc8eb01806e6fb03b05d19bd2815e9 Fix line numbering for invoke instructions.  
  7212198353b83e2e8b638a8755708cc14d39aee6 Make optimizer handle both strings and string-like type objects.  
  4eef4beff61d4efae4e372e7f4ee66090f9bcef5 Put uglify back the way it was.  
  88feddf045882bbddd29d9286eae4e6a9086e286 Get test_source_map passing again.  
  566447048806a59eb6e102fc364191ce292d7045 Move line numbers to the AST node itself.  
  _All from #1274, requires a closer look to see whether we can avoid modifying uglify for this._
- ffb887d170000f64250c9ce4aca4e8661d677957 add a newline to source comments in uglify, where necessary  
  _Still have to work out the use case here, but I doubt it's still an issue with current upstream._

**Comment by kripken** [comment]
Note that Uglify and Uglify2 are different projects. I believe 2 has a different AST, which would make it hard for us to switch to it. And 1 has not seen much work, so I'm not sure updating it would help us.
