### ISSUE TITLE
emscripten_wget doesn't create the path of the target file

### ISSUE THREAD

**Issue by iboB** [emscripten-core/emscripten#3524]
Say you get a resource with `emscripten_wget("path/file.dat", "path/file.dat");` Since you don't have the path `path` at your browser file system this will always lead to the exception "no such file or directory".

I think that `emscripten_wget` should create the target path or at least be configurable to allow this.

**Comment by iboB** [comment]
This is actually pretty hard to work around... one should either create a js library that creates the appropriate path, or generate a js string to do so

**Comment by kripken** [comment]
Hmm, personally i would prefer to not have it automatically create the subdirs, nor to add an option to do so (because of clutter).

**Comment by iboB** [comment]
Not having a standard way to handle directoris and paths is generally a C/C++ problem, but I think there should be some way of handling them from C++ with Emscripten.

**Comment by crankycoder** [comment]
I agree with @kripken - if you can't create your own directories, you've really done something wrong.  Automagically creating file system paths is a good way to introduce silent bugs into your code if you have a typo in your path.

**Comment by iboB** [comment]
Then this should probably be morphed into a feature request "Create filesystem API for C/C++"
