### ISSUE TITLE
VS10 CompileAs C++ a project containing only C files

### ISSUE THREAD

**Issue by lbarnabas88** [emscripten-core/emscripten#3532]
I'm trying to compile a VS10 project as C++. The project contains only C files, so it's automatically tries to compile as C, but I want it to try as C++. I have tried the -xc++ argument in Properties/Clang
C/C++/Command Line tab as Additional Options.

The test code to check if it's compile as c++ or c:

``` c++
#ifdef __cplusplus
int ItsCpp[ -1 ];
#endif

#ifndef __cplusplus
int ItsC[ -1 ];
#endif
```

Error:

```
1>c:\Users\blaszloffy\NNG\src\BulletTrain\ThirdParty\Freetype\include\ft2build.h(42,11): error : 'ItsC' declared as an array with a negative size
1>  int ItsC[ -1 ];
1>            ^~
```

I've also tried:
- /TP, but in this case it tries to compile '/TP' as a file.
- <CompileAs>CompileAsCpp</CompileAs> in vcproj, but it has no effect either.

Version:

```
emcc (Emscripten GCC-like replacement) 1.30.0 ((unknown revision))
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
I believe the Visual Studio plugin is hardcoded to look at the file extension for each file individually to choose how to build it. So if you have `.c` files, those should get built with `-x c`, and all `.cpp` files should get built with `-x c++`. You can try going to the project property pages and add the `Echo Command Lines ` option to see what is passed to the build.

**Comment by lbarnabas88** [comment]
I see. If I set '-x c++' to a project with only .c files, there are both '-x c' and '-x c++' in the command line. If it's hardcoded I'll use some workaround. Thanks!

**Comment by lbarnabas88** [comment]
It turns out we'll need this feature, so if possible please implement it!
