### ISSUE TITLE
how to create file onto local filesystem  from browser ?

### ISSUE THREAD

**Issue by fulean** [emscripten-core/emscripten#3547]
I want to access a file abc.txt under d:/test directory ,and i have read the idbfs and nodefs test demo , but didn't figure out how to use the idbfs to access  d:/test/abc.txt, could you please give me some suggession on access local file system ? thanks !

**Comment by kripken** [comment]
You probably want to preload those files, see http://kripken.github.io/emscripten-site/docs/porting/files/packaging_files.html#packaging-files
