### ISSUE TITLE
Accessing member variables without a copy using Embind

### ISSUE THREAD

**Issue by ianba3** [emscripten-core/emscripten#3551]
It appears that member variables are always accessed via a copy, which I find makes modifying data difficult.

Given the following classes:

```
class vec2
{
public:
    float x, y;
};

class obj
{
public:
    vec2 vector;
};

class_<obj>("obj")
  .property("vector", &obj::vector) 
  ;
```

I would like to call:

```
var myObj = new obj();
myObj.vector.x = 5;
```

However, this appears to result a new vector being created that is a copy of myObj.vector, and the x component of that is modified.

I tried creating accessors like the following, but this does not compile (being unable to use allow_raw_pointers() on a property.

```
class obj
{
public:
    vec2 vector;
    vec2* vGet() const { return &vector; }
    void gSet(vec2* a) { vector = *a; }
};

class_<obj>("obj")
  .property("vector", &obj::vGet, &obj::vSet, allow_raw_pointers()) 
  ;
```

Do you have any advice?  Should allow_raw_pointers be added to properties?  The following technically works, but it will certainly confuse people:

```
class_<obj>("obj")
  .function("vector_get", &obj::vGet, allow_raw_pointers()) 
  .function("vector_set", &obj::vSet, allow_raw_pointers()) 
;

myObj.vector_get().x = 5;
```

Thanks!

**Comment by kpeeters** [comment]
Is there any update on this? Is the workaround presented here still the only option?

**Comment by froydnj** [comment]
I looked at this today.  I put what is a reasonable facsimile of a solution up in #6402, with a limitation or two noted therein.  I realize it's been a while since the initial request, or even a request for current status, was made.  But if you're still interested, please comment over there and we can try to get something worked out.
