### ISSUE TITLE
Embinded when compiling with MinGW get removed (Bug?)

### ISSUE THREAD

**Issue by zapfdk** [emscripten-core/emscripten#3555]
Hi,
after successfully compiling my project with the Visual Studio integration I am currently trying to compile it with MinGW to secure, that the project can be cross-compiled from command line easily, too. 
In the project I am using Embind.
I now faced the problem, that the classes and functions are completely removed when I am compiling the project with MinGW. Bizarrely, when I am including a trivial main() function like:

```
int main()
{}
```

the functions and classes are kept alive and it is working without a problem.
So is this a bug or did I simply forget to set a flag somewhere?

**Comment by juj** [comment]
Not quite sure about this, but are you aware of the `-s EXPORTED_FUNCTIONS=...` linker option? That refers to `_main_` by default, I wonder if there might be some interaction with it via that?
