### ISSUE TITLE
code with packed struct and bitfields miscompiled at -O1 and above on x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [emscripten-core/emscripten#3556]
The following code (small.c) seems to be miscompiled at -O1 and above:

```
#include <stdio.h>

#pragma pack(1)
struct
{
  int:32;
  unsigned int f1:8;
  unsigned int:32;
} a;

int b;

int
main ()
{
  b = a.f1 < 2;
  printf("%d\n", b);
  return 0;
}
```

$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 3d7aff0906f41c562d70c6e0483012de758f9bfa) (https://github.com/kripken/emscripten-fastcomp/ dccd6517fcc00126e4e74d77c5a8fa06efd3a2ad)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
$ 
$ clang -O0 small.c; ./a.out
1
$ emcc -O0 small.c; node ./a.out.js
1

$ emcc -O1 small.c; node ./a.out.js
0

$

**Comment by kripken** [comment]
I can't reproduce the problem here, but also, this is reading from uninitialized memory, isn't it?

**Comment by zhendongsu** [comment]
No, because in C, all global variables are initialized (to 0).

**Comment by zhendongsu** [comment]
Alon, here are the temp files generated with "EMCC_DEBUG=2 emcc -O1 small.c": 
https://dl.dropboxusercontent.com/u/10788753/pr3556.zip

**Comment by kripken** [comment]
Ok, right.

Meanwhile I can reproduce it, it only happens on C files, not C++ ones.

**Comment by kripken** [comment]
Are these fuzzer testcases, btw?

**Comment by zhendongsu** [comment]
Alon, yes.  I recently launched some tests using the following work: 

PLDI 2014: Compiler Validation via Equivalence Modulo Inputs (http://web.cs.ucdavis.edu/~su/publications/emi.pdf)

The talks slides (http://web.cs.ucdavis.edu/~su/publications/emi-talk.pdf) provide a quick summary.

**Comment by kripken** [comment]
Interesting, thanks! I'll read those.

Meanwhile I looked more into this. It's a PNaCl legalization bug it appears, I filed https://code.google.com/p/nativeclient/issues/detail?id=4209
