### ISSUE TITLE
GLFW3 not firing glfwSetWindowSizeCallback when canvas resizes

### ISSUE THREAD

**Issue by xcodedave** [emscripten-core/emscripten#3558]
Hi,

I believe when the canvas resizes (i.e. to go fullscreen or otherwise due to the webpage window being resized), then the callback registered using glfwSetWindowSizeCallback should get called.

I've tested this, but I don't seem to be seeing the callback being called. I've attached code which will reproduce the issue and have compiled with these flags:  -std=c++11 -s USE_GLFW=3 
using the following code:

```
#include<stdio.h>
#include<stdlib.h>
#include<emscripten/emscripten.h>
#define GLFW_INCLUDE_ES2
#include<GLFW/glfw3.h>

int windowWidth;
int windowHeight;

void window_size_callback(GLFWwindow* window, int width, int height)
{
    printf("window_size_callback received width: %i, height: %i\n", width, height);
}

void do_frame(){
}

int main(int argc, char **argv) {
GLFWwindow *window;

if (glfwInit()!=GL_TRUE) {
    printf("glfwInit() failed\n");
    glfwTerminate();
} else {
    printf("glfwInit() success\n");
    window = glfwCreateWindow(640, 480, "GLFW test", NULL, NULL);
    if (!window){
        printf("glfwCreateWindow() failed\n");
        glfwTerminate();
    } else {
      printf("glfwCreateWindow() success\n");
      glfwMakeContextCurrent(window);
      glfwGetFramebufferSize(window, &windowWidth, &windowHeight);
      glfwSetWindowSizeCallback(window, window_size_callback);
      emscripten_set_main_loop(do_frame, 0, 1);
      glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    }
}

    glfwTerminate();
return EXIT_SUCCESS;
}
```

**Comment by kripken** [comment]
We do listen on `resizeListeners`. But looks like all we do is call `onFullScreenEventChange`. I suppose we should also call `glfwSetWindowSizeCallback`, around [here](https://github.com/kripken/emscripten/blob/incoming/src/library_glfw.js#L726). Should be easy to do, do you want to make a pull request?

**Comment by xcodedave** [comment]
Currently I've been developing using the SDK rather than straight off the repo, but will give this a go tomorrow :) Thanks!

**Comment by chemecse** [comment]
I was unable to reproduce the error on Mac OS X 10.9.5 using Google Chrome Version 44.0.2403.130 (64-bit).

The following screenshot was the result after running in fullscreen mode and then exiting using the provided test case.
<img width="1185" alt="screen shot 2015-08-07 at 1 49 27 pm" src="https://cloud.githubusercontent.com/assets/10465575/9142099/8df263ba-3d0b-11e5-98f7-12e0f9d1049e.png">

**Comment by cgibson** [comment]
@chemecse , you're not incorrect. Window resizes from fullscreen to windowed are captured. However, changes to the canvas are not. A lot of applications require the WebGL canvas to be responsive, and we're missing that functionality here.

Would it be reasonable to expect a window resize when the canvas element itself is resized?

**Comment by cgibson** [comment]
Additionally, glfw3 now separates the window size from its framebuffer size. If we want to properly emulate the behavior of glfw3 in native apps, we may want to call the window size callback when canvas.clientWidth or canvas.clientHeight of the canvas is updated, and the framebuffer size callback when the canvas.width or canvas.height are changed.

According to the glfw3 docs, apps should refer to the framebuffer size when deciding what the viewport size should be. Merely updating the window size in this context wouldn't change the pixel resolution of the app.

**Comment by cgibson** [comment]
I submitted a pull request (#4265) that I believe properly implements changes to the window size. Instead of just handling situations where you enter or exit full screen (as seen in `onFullScreenEventChange` ), this change handles any situations where the canvas size needs to be resized.

It also allows for better `glfwSetWindowSizeCallback` and `glfwSetFramebufferSizeCallback` behavior (though the behavior is admittedly naive, since LibraryGLFW has no concept of framebuffer vs window size. That's an entire discussion on its own.)

The major caveat is you still need to call `glfwSetWindowSize()` yourself. AFAIK, you can't listen for a resize event from the canvas object itself, so we won't know when to update the window and framebuffer sizes.

**Comment by cgibson** [comment]
Re-opened pull request to point to the incoming branch
