### ISSUE TITLE
MODULARIZE=1 and --proxy-to-worker should modularize WebGLClient

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#3565]
When both options are used with `emcc`, the resulting `.worker.js` file is modularized, while the client proxy javascript remains unchanged. It seems to me that the client js file instead should be modularized so that we can write `var someClient = new WebGLClient({ canvas: canvas, ... });` which will then create the web worker (which I believe no longer needs to be modularized)

**Comment by kripken** [comment]
From my perspective, the client code is just support, basically, for a situation in which everything runs in the worker. So I don't feel this is a bug. Curious to hear what other people think.

**Comment by hoongern** [comment]
I guess it depends on the purpose of modularizing - for me it was so that I can control when the WebGLClient/module is actually created, as well as having the ability to run multiple WebGLClient/module instances within the same document.
