### ISSUE TITLE
emscripten_get_pointerlock_status not working with proxy-to-worker

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#3566]
When using the SDL port (`USE_SDL=2`) and `--proxy-to-worker`, mouse movement calls [Emscripten_HandleMouseMove](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenevents.c#L300) which in turn calls [emscripten_get_pointerlock_status](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenevents.c#L314). This then checks [document.body.requestPointerLock](https://github.com/kripken/emscripten/blob/2643bd9513638ea32f8023c153f50d2564745a5f/src/library_html5.js#L1543) which is non-existent in the web worker environment and throws a TypeError exception.

I'm currently working around this issue by adding `document.body = {}; document.body.requestPointerLock = function (){};` to `proxyWorker.js`, which I'm not sure is the correct solution.

**Comment by kripken** [comment]
The correct solution would be to send a message to the main thread in order to do that. Shouldn't be hard.
