### ISSUE TITLE
Zero dimension SDL_WINDOWEVENT_SIZE_CHANGED when creating window with --proxy-to-worker and SDL port

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#3570]
When [`emscripten_CreateWindow`](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenvideo.c#L187) is called, the worker's `canvas.boundingClientRect` has not been set yet. Thus, when `emscripten_get_element_css_size` is [called](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenvideo.c#L210), [`canvas.getBoundingClientRect`](https://github.com/kripken/emscripten/blob/master/src/proxyWorker.js#L218-L219) returns undefined dimensions which are interpreted as zero width & height.

It seems that this data should either be proxied over before `run()` is called, or in the case of the SDL port, which [sets the canvas size](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenvideo.c#L208) before calling `emscripten_get_element_css_size`, perhaps the [`worker-init` method](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenvideo.c#L208) should use the width/height property setters to fire resize events back to the client, and wait for the client to send back the `boundingClientRect` before running (would potentially require an additional run dependency?

**Comment by kripken** [comment]
I would guess that the best thing is to proxy it over before run is called, as part of the `worker-init` event. Feel free to write a pull request for that. Even a pull with just a test would be useful.
