### ISSUE TITLE
emscripten_set_wheel_callback doesn't work with --proxy-to-worker

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#3571]
[`emscripten_set_wheel_callback`](https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L1083-L1094) checks for `onwheel` or `onmousewheel` properties on the target (in the case of the SDL port, on the [`canvas`](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenevents.c#L582)). Since these properties don't exist on the worker's canvas, this is a no-op. Seems that `canvas.onwheel = function (){};` could be added to `proxyWorker.js`.

Also, is there a reason why [`DOMMouseScroll` and `mousewheel`](https://github.com/kripken/emscripten/blob/master/src/proxyClient.js#L227) are being proxied? Shouldn't the more standard `wheel` event be proxied?

**Comment by kripken** [comment]
Related to #3572. We should probably proxy those, if possible.

I honestly don't remember why those two were proxied. I probably saw what worked in firefox and chrome, at the time - perhaps something better exists now?
