### ISSUE TITLE
--proxy-to-worker event proxying issues and SDL port

### ISSUE THREAD

**Issue by hoongern** [emscripten-core/emscripten#3572]
The SDL port [registers various event handlers](https://github.com/emscripten-ports/SDL2/blob/3adbfbb3a80dffb3ff9e42f43f6b6837d6ba093c/src/video/emscripten/SDL_emscriptenevents.c#L571-L604) on either the window/canvas. However, it does not seem that [`proxyClient`](https://github.com/kripken/emscripten/blob/master/src/proxyClient.js#L214-L232) uses the same targets, meaning that various events (keydown/keyup/keypress/mouseup) are lost.

I'm not sure if this is due to differences between the various SDL implementations, but when I set the events on the correct targets in `proxyClient`, they work as expected.

**Comment by kripken** [comment]
I think in general, the proxying support has a bunch of missing connection points with client-side events. It would be good to refactor this entirely, I suppose - some client-side class that handles this, and can be used either by code running on the main thread, or the client-side portion of a `--proxy-to-worker` app.
