### ISSUE TITLE
Boost::python module issue

### ISSUE THREAD

**Issue by ZengruiWang** [emscripten-core/emscripten#3580]
Hi, I have a weird problem with the boost::python.
What I am trying to do now is I create a module and call the function in the module.

``` javascript
void foo(){ printf("foo!"); }
BOOST_PYTHON_MODULE(myfoo)
{
    boost::python::def("foo", foo, "call foo!");
}
int main(int argc, char** argv)
{
    Py_NoSiteFlag = 1;
    Py_SetPythonHome("/data/Python-2.7.6/..");
    Py_InitializeEx(0);
    boost::python::object module = boost::python::import("__main__");
    printf("After boost::python::import'__main__'\n");
    boost::python::object dict  = module.attr("__dict__");
    printf("After boost::python::attr'__dict__'\n");
    initmyfoo();
    PyRun_SimpleString("import myfoo\nmyfoo.foo()");
    return 0;
}
```

I mounted the Python2.7.6 Libs into the FS which contains the following sub-directories:
/include (contains `pyconfig.h`)
/Lib(copied from Python-2.7.6 source code which contains a bunch of `.py` files)
/libs(contains the python LLVM biccode static library)

The problem is if I don't mount the Python2.7.6 into the file system, everything is fine. It could import the myfoo module and call the foo function. But if I mount the file into the file system, it exits and shows the following message:
<b>
pre-main prep time: 2039 ms
After boost::python::import'**main**'
After boost::python::attr'**dict**'
exit(0) called, but noExitRuntime, so not exiting (you can use emscripten_force_exit, 
if you want to force a true shutdown)
Module.printErr @ BoostPython.html:1245
exit            @ BoostPython.js:548143
callMain        @ BoostPython.js:548090
doRun           @ BoostPython.js:548125
(anonymous function) @ BoostPython.js:548134

What have I done wrong of mounting the python library into the file system?
Thank you!

**Comment by kripken** [comment]
I don't know anything about boost::python, but it looks like the program is exit()ing. Was that expected?

**Comment by ZengruiWang** [comment]
No. The expected behavior should be printing the `foo!` on the console. 
If I don't mount the Python library the output is like:
<b>
After boost::python::import'__main__' BoostPython.html:1233 
After boost::python::attr'__dict__'        BoostPython.html:1233 
foo!

Also is it correct and necessary to mount the Python library to the file system when porting Python not boost python? Thanks!

**Comment by kripken** [comment]
When porting python, it just worked without any filesystem access. I didn't need to mount any directories.

If you can reduce this bug to a standalone issue without boost::python, I can take a look at that. But most likely it is a boost::python issue somehow.

**Comment by ZengruiWang** [comment]
Hmm, I could make a standalone issue but since our project heavily relies on boost::python, I still hope that boost::python could work.
