### ISSUE TITLE
nested web workers supported?

### ISSUE THREAD

**Issue by yyzone** [emscripten-core/emscripten#3582]
hi all,
is it valid to use the web worker API calls (i.e. void emscripten_call_worker) within the context of a web worker (to create and use another web worker) and not just from the main thread?
thanks!

**Comment by kripken** [comment]
I'm not sure. Try it! :)

If it doesn't work, we can use this as a bug to track the issue, as it should work.

**Comment by yyzone** [comment]
we are porting a large codebase and are still far from running it; but we'll get there eventually and try it.
I just thought someone here already used it so we know what to anticipate.

I'll report back, thanks!

**Comment by kripken** [comment]
You can assume it will work - if it doesn't, it should be very easy to fix.

However, I just remembered that browser support might not be consistent here. Firefox supports them, but Chrome does not: https://code.google.com/p/chromium/issues/detail?id=31666&q=nested%20workers&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

**Comment by yyzone** [comment]
hmm that's a real bummer, thanks for pointing it out.. 
we will probably need to change the threading model to avoid nested workers for now due to this

**Comment by juj** [comment]
Would it make sense/be useful for `emscripten_call_worker` to always ask the main thread to spawn the worker, instead of spawning it directly by the calling worker. That is what we do currently for pthreads when they spawn other pthreads.

**Comment by yyzone** [comment]
might not be a bad idea to help avoid problems with various browsers...  we
decided to simply stick to always spawning/calling on main thread to stay
away from trouble

**Comment by surma** [comment]
Just a quick update: [Chrome supports Nested dedicated web workers now](https://www.chromestatus.com/features/6080438103703552)

**Comment by y-ich** [comment]
Hi.

I tried to spawn a thread from web worker and failed.
Here is a reproduction code.
https://github.com/y-ich/thread-by-worker

The line 157 in XX.worker.js generated by the compiler below never return.

    var result = Module['dynCall_ii'](e.data.start_routine, e.data.arg);

What I did is assigning Module["mainScriptUrlOrBlob"] in pre.js.
I am not sure if it is right.

Please tell me how I can solve this issue.

Thanks.

**Comment by juj** [comment]
I don’t recall if chrome has added support for creating nested web workers.

Nested pthreads are avoided in emscripten by always having the main browser thread spawn the workers.

Though Emscripten pthreads support requires that the application runs on the main browser thread. Check out -s PROXY_TO_PTHREAD=1 build option.

**Comment by juj** [comment]
Oh, just saw surma’s comment above.. so technically that might be viable now, though not sure if there is something in such configuration that is missing.

**Comment by y-ich** [comment]
@juj san,

Thank you for your comments.
I tried -s PROXY_TO_PTHREAD=1, but nothing changed.
What is the meaning of this option?
