### ISSUE TITLE
Suggest FAQ entry: how to use a C library in Javascript

### ISSUE THREAD

**Issue by qwertie** [emscripten-core/emscripten#3583]
So I wrote this file, `lowercase.c`:

```
char toLower(char c)
{
  return c >= 'A' && c <= 'Z' ? c + ('a' - 'A') : c;
}
void strToLower(char* buf)
{
  for (int i = 0; buf[i]; i++)
    buf[i] = toLower(buf[i]);
}
```

`emcc lowercase.c` succeeds, but the output is 9000 lines and I can't find `toLower` in the output anywhere. After browsing the FAQ, I try adding `--closure 1` to get shorter output and `-s EXPORTED_FUNCTIONS=...` to hopefully make my symbols appear. Neither of these works for me:

```
D:\...>emcc lowercase.c -s EXPORTED_FUNCTIONS="['strToLower','toLower']" --closure 1
WARNING  root: disabling closure because debug info was requested
WARNING  root: function requested to be exported, but not implemented: "strToLower"
WARNING  root: function requested to be exported, but not implemented: "toLower"
```

How do I fix this, and then, how could I use this code to convert a Javascript string to lowercase?

**Comment by kripken** [comment]
See the examples in the docs, for example [here](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html?highlight=exported_functions#calling-compiled-c-functions-from-javascript-using-ccall-cwrap) it shows wrapping a simple function. Note that there is a `_` prefix for compiled methods.

**Comment by juj** [comment]
I believe by default `toLower` will get inlined in `-O1` and higher, and therefore optimized out. Passing `-s EXPORTED_FUNCTIONS="['_toLower']"` should be enough to pin it down so that an implementation exists in the generated code uninlined. If issues still persist, does it work without closure enabled?

**Comment by qwertie** [comment]
Notice the error message - `--closure 1` wasn't working anyway. Adding underscores in the `EXPORTED_FUNCTIONS` list makes the functions appear in the output starting at line 5333.

    emcc lowercase.c -o lowercase.html -s EXPORTED_FUNCTIONS="['_strToLower','_toLower']" --closure 1 -g0
    WARNING  root: disabling closure because debug info was requested

`-g0` is supposed to disable debug info, but it doesn't seem to work - the output appears to be the same with or without `-g0`, although I don't see any sign of "debug info" in the output either way. So what's it complaining about?

**Comment by qwertie** [comment]
Ping. I'm still wondering how to get output that isn't massively inflated. It seems to me that a trivial example like this should be able to compile to something of size 1-2KB. If I add `-O2` I get something that is 81KB minified (which makes me wonder - I'd like to comprehend the output, so can I optimize the code without minifying it?)

**Comment by kripken** [comment]
We have not yet optimized things to be able to remove parts of the runtime that are not needed. For example, string conversion between C and JS is in the output. I agree this would be good to improve, but no one has focused on it so far.

You should be able to just read the generated code to see what is taking up all that space, use `-g2` to keep it fairly readable (function names and whitespace are preserved).

**Comment by qwertie** [comment]
Soooo... you're saying --closure 1 wouldn't remove the unused things, even if it worked?

**Comment by kripken** [comment]
Depends how smart closure is. If the code is put in a function scope (MODULARIZE), then it is provable that most of the code is dead. Not sure if closure actually does that, though.

**Comment by kripken** [comment]
Also, we export a lot of things on `Module`, and would need to make that optional. There have been discussions about that, but no one has done it.
