### ISSUE TITLE
Detect memory growth?

### ISSUE THREAD

**Issue by croes** [emscripten-core/emscripten#3586]
Hello,

Is there any way you can detect/get notified when Emscripten enlarges the memory?
I looked at [enlargeMemory()](https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/preamble.js#L1015), but didn't find any hooks.
The reason we want to do this, is because we keep some TypedArray views on certain parts of the heap. If Emscripten enlarges the memory, those views should be invalidated.

Kind regards,
Glenn

**Comment by kripken** [comment]
Actually the tracing calls there (`emscripten_trace_report_memory_layout`) could be used as hooks. If you build with `EMSCRIPTEN_TRACING`, but override those defaults - just use a js library that implements them - that should work.

That is a little inconvenient though. We could add a `Module` hook if that would be better, pull request would be welcome.

**Comment by croes** [comment]
Done: https://github.com/kripken/emscripten/pull/3590
