### ISSUE TITLE
use compression for faster startup...

### ISSUE THREAD

**Issue by jedie** [emscripten-core/emscripten#3589]
I try to optimize the startup time for http://pypyjs.org/ and validate existing general purpose data compression libraries.

I also find the ticket #2048 - "reconsider lzma approach" ... So LZMA was used in the past, but was removed.

There exists many compression libraries, e.g.:
- https://quixdb.github.io/squash-benchmark/
- http://mattmahoney.net/dc/text.html

From the first link: 
- data: **Tarred executables of Mozilla 1.0 (Tru64 UNIX edition)**
- machine: **beagleboard-xm**

![df578568-18d1-11e5-91a3-6fd37f556f0f](https://cloud.githubusercontent.com/assets/71315/8426555/20774f20-1f11-11e5-8c55-73421330227a.PNG)
My Conclusion:
- bzip2 is pretty slow
- zlib (It's deflate) has a good ratio vs. decompression speed
- lzham seems to be very interesting: good ratio and more speed than LZMA

The most interesting one: **lzham** doesn't exist as a JavaScript implementation. So i tried to compile it via emscripten, without success, see: https://github.com/richgel999/lzham_codec/issues/9

So i looked, which decompression implementation exists in JavaScript. There are not many. I just found only this:
- https://github.com/nmrugg/LZMA-JS
- https://github.com/dankogai/js-deflate
- https://github.com/imaya/zlib.js
- https://github.com/Stuk/jszip
- https://github.com/nodeca/pako/
- https://github.com/abraidwood/minilzo-js
- https://github.com/google/zopfli
- https://github.com/devongovett/brotli.js (only for node.js)

The list looks bigger than it is:
- zopfli is only a compressor that creates smaller zlib compatible archives. It seems it's not worth it: https://github.com/pypyjs/pypyjs.github.io/issues/4#issuecomment-113078793
- js-deflate, zlib.js, jszip and pako are all different implementation of zlib:deflate
- jszip used pako for decompression but can handle the **.zip** container, too.

I also started a thread about this here: http://encode.ru/threads/2227-Search-compressor-for-PyPyJS-better-than-deflate (Seems to be the biggest forum about data compression)

Next related thing: I would like to bundle files: So what's about container formats? It seems, there is only **.tar** or **.zip**
I found two implementations for **.tar** and https://github.com/Stuk/jszip for **.zip**
Seems that **jszip** is the fastes one. More information here: https://github.com/pypyjs/pypyjs.github.io/issues/7

I have made tests for all of these combinations. try out here: http://jedie.github.io/pypyjs_test_compression/

My results:
- .zip with 'github.com/Stuk/jszip' -> avg: 124,825MB/s 
- .tar.gz with pako + untar -> avg: 110,15MB/s
- .tar.gz with 'gist.github.com/stuartpb/10416747/' -> avg: 21,125MB/s 
  *.tar.xz with 'github.com/nmrugg/LZMA-JS' -> ~1MB/s

So it seems that **.zip** via https://github.com/Stuk/jszip is currently the best choice :(
But this is sad, because server/browser can also compress with **zlib:deflate** interiorly and faster.

Anyhow, i made a test to compare the "normal" emscripten startup, here:
- https://jedie.github.io/pypyjs.github.io/editor.html (with .zip)
- http://pypyjs.org/editor.html (without .zip)

With empty cache, it's: ~9sec vs. ~11sec on my ~14MBit downlink.
With filled cache: ~6.5sec vs. ~11sec

This is not really a big difference and maybe:
- it's slower on slow CPU with better bandwidth
- it's only faster on fast CPU with less bandwidth

On my TODO:
- Test https://github.com/abraidwood/minilzo-js
- compare with "memory-file compressor to use a deflate-like scheme" by https://github.com/rfk here: https://github.com/pypyjs/pypyjs/commit/a1cb945cc04ee64acfb3e4a5a109cc1df95b6d5a

btw. WebAssembly has the same question, see: https://github.com/WebAssembly/design/issues/206

Has someone also investigate how to tune the startup time via compression?
Can someone help here: https://github.com/richgel999/lzham_codec/issues/9 ?

EDIT: I just found: https://github.com/ukyo/zlib-asm and the benchmark: http://imaya.github.io/demo/zlib/index.html than compares:
- https://github.com/ukyo/zlib-asm
- https://github.com/imaya/zlib.js
- https://github.com/nodeca/pako

**Comment by kripken** [comment]
In the last we've tried LZMA, but due to it using 64-bit integers, it was quite slow. Overall we therefore have been recommending that people use gzip, which is quite ok, and natively supported in browsers. But if there is a better approach, that is fast to run (no 64-bit ints), that would be very interesting.

**Comment by juj** [comment]
Hey, this is very cool results! Thanks for the work here! It would be very nice to have an automated benchmark repo that would build some compressors and decompressors from source, both to native and emscripten, and then run a compression and decompression test with native vs Emscripten, and graph out the results. This could be used to track a performance differential between native and JS, as well as track Emscripten performance over time.
