### ISSUE TITLE
Binding a class as a main module with a method returning a float causes embind to fail

### ISSUE THREAD

**Issue by JonathanPicques** [emscripten-core/emscripten#3592]
Hi, I faced a very strange bug using embind and float,
Binding a simple class as a main module with inside a method returning a float will crash at runtime

Consider this simple code
https://gist.github.com/JonathanPicques/52f257523b876d1d5550

Compiled like this:

```
em++ -std=c++11 -s MAIN_MODULE=1 --bind embind_float.cpp 
```

Will throw this error

```
$ node a.out.js

a.out.js:90
      throw ex;
            ^
BindingError: No dynCall invoker for signature: fii
    at BindingError.<anonymous> (a.out.js:1934:24)
    at new BindingError (eval at createNamedFunction (a.out.js:1921:14), <anonymous>:4:34)
    at throwBindingError (a.out.js:1954:13)
    at requireFunction (a.out.js:7418:19)
    at __embind_register_class_property (a.out.js:7506:16)
    at __ZN38EmscriptenBindingInitializer_BindFloatC2Ev (a.out.js:31400:2)
    at ___cxx_global_var_init (a.out.js:31612:2)
    at __GLOBAL__sub_I_embind_float_cpp (a.out.js:31606:2)
    at asm.__GLOBAL__sub_I_embind_float_cpp (a.out.js:119614:46)
    at __ATINIT__.push.func (a.out.js:1651:67)
```

Simply changing float to double will make this code runs.

**Comment by kevinoe** [comment]
I'm seeing the same problem, though with a parameter rather than a return type.  Would love to see this fixed.  

It seems like dynamic linking isn't really targeting the embind usage.  Am I correct in this understanding?  I'm interested in fragmenting a toolkit consisting of a large number of libraries rather than an executable linked to several libraries.

**Comment by JonathanPicques** [comment]
I have the same use case, but using doubles work so I'll stick to doubles.

Would love to see this fixed or maybe I can help if I'm pointed in the right direction.

**Comment by kevinoe** [comment]
Unfortunately, I'm not able to change the codebase (it is used in C++ already and is very extensive), so I'm a bit stuck unless I wrap all my code in dummy functions.

**Comment by arcanis** [comment]
I'm noticing the same issue even when using nbind. It seems that emscripten is emitting `dynCall_viiid` instead of `dynCall_viiif`, so it crashes as soon as it tries to call it.
