### ISSUE TITLE
Emscripten and WebAssembly

### ISSUE THREAD

**Issue by httpdigest** [emscripten-core/emscripten#3594]
Hi,

I just recently got aware of WebAssembly.
I know there is not even a spec right now, only design proposals.
But is Emscripten going to provide a WebAssembly backend for LLVM?
Or will there be a new tool based on LLVM to replace Emscripten for WebAssembly?

Thanks!
Kai

**Comment by juj** [comment]
Yes. WebAssembly development is driven (among others) by the same people who develop Emscripten, and there will eventually be a WebAssembly backend for LLVM. @kripken and @sunfishcode are working on it.
