### ISSUE TITLE
Error building tesseract in visual studio 2010

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [emscripten-core/emscripten#3598]
I'm having following error when i'm trying to build tesseract VS2010 bundle in visual studio 2010 using emscripten.
I configured visual studio as they have mentioned in their documentation. but when i click build solution i get following error.

error MSB4044: The "GCCCompile" task was not given a value for the required parameter "GCCToolPath"

How can i fix this.

**Comment by juj** [comment]
Where is the tesseract VS2010 bundle and the documentation? It might be best to contact the tesseract bundle developers to ask if they have it building for Emscripten in Visual Studio.
