### ISSUE TITLE
Porting sockets to emscripten

### ISSUE THREAD

**Issue by VinnyVicious** [emscripten-core/emscripten#3611]
I wanted to port a simple application i have that relies on sockets to communicate. I'm using functions like `connect()`, `send()`, and `recvfrom()`. How can i port it to emscripten? Is there a simple abstraction layer, like with SDL?

**Comment by kripken** [comment]
It should just work. As in #3610, see the test suite for concrete examples, `tests/test_sockets.py` runs the network tests, many of which use `connect(), send()` etc.

**Comment by VinnyVicious** [comment]
What do you mean by "if asynchronous"? I'm just making the calls, normally, when i make new connections or send messages around.

**Comment by kripken** [comment]
You can't do a blocking call on a socket. The timeout, for calls thath ave one, has to be 0.

**Comment by VinnyVicious** [comment]
Is there a good way to debug this? Also, does it need any special server configuration? The code compiles, but doesn't seem to work.

**Comment by kripken** [comment]
I believe there is a `SOCKET_DEBUG` option.

On the server, it needs a webserver with websockets support, not normal tcp or udp.

**Comment by VinnyVicious** [comment]
I see. But i already have the server written in C and i'm compiling with emscripten. Would that work, or i would have to rewrite the server in pure javascript with WS lib?

**Comment by kripken** [comment]
And you're running it in node? That should just work, that's what some of the testcases in the test suite do.

**Comment by VinnyVicious** [comment]
No, i'm running both client and server on the browser. Is that the Isaura? Why?

**Comment by VinnyVicious** [comment]
I'm getting this error when running the server from node: 

```
Error: Cannot find module 'ws' : Error
```

Maybe i'm missing some env var?

**Comment by kripken** [comment]
I think `ws` is the node websockets module? Perhaps you need to run `npm` to install it.

**Comment by VinnyVicious** [comment]
Do i need to setup a websockets server or something?

**Comment by kripken** [comment]
See the sockets test suite. We use websockify, I believe, since normal http webservers can't connect to websockets (intentionally, due to websockets security) but I don't remember the details.
