### ISSUE TITLE
LLVM LTO can rename libc functions, adding dependencies after linking

### ISSUE THREAD

**Issue by shlomif** [emscripten-core/emscripten#3616]
Hi all!

When trying to build this branch of my repository - https://github.com/shlomif/libxmp-4.3.0/tree/shlomif--fix-build-with-emscripten using the latest emsdk from GitHub I am getting this:

```
$ cd emscripten
$ bash makeEmscripten.sh 
[Output trimmed]
$ grep -C 5 exp2 htdocs/webXmp.js | head
      HEAP32[(((tmPtr)+(40))>>2)]=zonePtr;

      return tmPtr;
    }

  function _exp2() {
  Module['printErr']('missing function: exp2'); abort(-1);
  }

  function _unlink(path) {
shlomif@telaviv1:~/Download/unpack/multimedia/xmp/libxmp-4.3.0/emscripten$ 
```

If I modify makeEmscripten.bat to also link exp2.c and rerun "perl bat2sh.pl" and "bash makeEmscripten.sh" I am getting this:

```
shlomif@telaviv1:~/Download/unpack/multimedia/xmp/libxmp-4.3.0/emscripten$ bash makeEmscripten.sh 
WARNING  root: disabling closure because debug info was requested
../src/load_helpers.c:290:11: warning: comparison of array 'mod->xxo' equal to a
      null pointer is always false [-Wtautological-pointer-compare]
        if (mod->xxo == NULL || mod->xxp == NULL || mod->xxt == NULL)
            ~~~~~^~~    ~~~~
1 warning generated.
ERROR: Linking globals named 'exp2': symbol multiply defined!
Traceback (most recent call last):
  File "/home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/emscripten/tag-1.34.1/emcc", line 1197, in <module>
    shared.Building.link(linker_inputs, in_temp(target_basename + '.bc'), force_archive_contents=force_archive_contents)
  File "/home/shlomif/Download/unpack/prog/llvm-to-js/emsdk/emscripten/tag-1.34.1/tools/shared.py", line 1397, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error: 
```

I am on Mageia Linux x86-64 6/Cauldron. How can the problem be fixed?

Best -- @shlomif

**Comment by shlomif** [comment]
Hi all! I should note that the code compiled correctly after I removed the offending "--llvm-lto 1" flag. Should it be handled more gracefully? It appears it used to work in the past.

**Comment by kripken** [comment]
This sounds like a known issue with LLVM LTO that I filed, https://llvm.org/bugs/show_bug.cgi?id=23814 . Basically, LTO can change function calls surprisingly, my bug was `printf/puts`, and I think yours is `exp/exp2`.

Sadly I don't see any attention on the bug, so I'm not sure what to do, except to avoid LTO.

**Comment by shlomif** [comment]
@kripken: thanks for your comment. Did LTO work in the past?

**Comment by kripken** [comment]
LTO has never passed the entire test suite, so we do not have it on by default. It sometimes works, and can be useful when it does, but otherwise I would just leave it off. LLVM doesn't seem focused on fixing LTO bugs, perhaps because no LLVM-based compiler uses LTO by default.

**Comment by shlomif** [comment]
@kripken: thanks for the update. Bye!

**Comment by kripken** [comment]
Btw, a workaround could be to add `exp2` to `EXPORTED_FUNCTIONS`.
