### ISSUE TITLE
SDL_RWseek

### ISSUE THREAD

**Issue by daniele-rapagnani** [emscripten-core/emscripten#3618]
Hi there, I can't make SDL_RWseek to work.
It seems like the underlying function pointers for seek, tell, ecc in SDL_RWops are note assigned.
Is this a known issue or am I missing something?

Steps to reproduce:

``` cpp
// test.cpp
#include <SDL/SDL.h>
#include <cstdio>
#include <cassert>
#include <emscripten.h>

int main(int argc, char** argv) {
    assert(argc > 1);

    EM_ASM(
        FS.mkdir('/working');
        FS.mount(NODEFS, { root: '.' }, '/working');
    );

    SDL_RWops* file = SDL_RWFromFile(argv[1], "rb");
    printf("size: %lu\n", SDL_RWseek(file, 0, RW_SEEK_END));
}
```

compile and run with:

```
em++ test.cpp -o test.js -s ASSERTIONS=2
echo "just a test" > test.txt
node test.js /working/test.txt
```

Running the compiled file results in:

```
Invalid function pointer '0' called with signature 'iiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
```

**Comment by kripken** [comment]
I suspect this is a limitation of our SDL1 support, which is limited RW code. [Using SDL2 from ports](http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#emscripten-ports) should fix this.

**Comment by daniele-rapagnani** [comment]
Thanks for your reply. Sadly the codebase I'm trying to port is really big, and porting it to SDL2 would be a huge effort from my understanding. Is there anyway I can work around this? Maybe implement the required function myself?

**Comment by kripken** [comment]
Yes, see `src/library_sdl.js` to see similar things. Hopefully this would be easy to add.
