### ISSUE TITLE
running empscripten on "botli" yields a .js library that uses 1GB of memory

### ISSUE THREAD

**Issue by Pomax** [emscripten-core/emscripten#3628]
there's a potential conversion issue in empscripten that surfaces when the `brotli` library (a codec used in WOFF2 de/compression) is compiled through it as described in https://github.com/devongovett/fontkit/issues/11 and https://github.com/devongovett/brotli.js/issues/3 -- while the C++ code uses some predefined arrays, the JS conversion sets up a number of array buffers that end up taking up 1GB of memory, which is way more than should be the case.

**Comment by kripken** [comment]
Hard to know what's going on without a testcase. Or without a link to an example build that shows the issue (non-minified so it is readable, preferably).

**Comment by kripken** [comment]
Without seeing anything, I would guess perhaps embedded or preloaded files, or could be too large a value for `TOTAL_MEMORY`.

**Comment by Pomax** [comment]
yep, good request - I asked @devongenett whether he would be able to generate that non-minified conversion result in https://github.com/devongovett/brotli.js/issues/3. I saw the memory spiking the moment that lib got loaded in, so with the separate lib it should be relatively straightforward to write a test case that makes use of the conversion result for analysis

**Comment by devongovett** [comment]
[You're right](https://github.com/devongovett/brotli.js/blob/master/Makefile#L5) about the large `TOTAL_MEMORY` setting. I think I had to raise it in order to get Brotli working though. At least the compressor requires a lot of memory I think.
