### ISSUE TITLE
node crashes in the sourcemapper.js if input js file is large

### ISSUE THREAD

**Issue by systemmind** [emscripten-core/emscripten#3638]
If -g4 option is used the node.js crashes if emscripten generated js file is bigger then 200 Mb. This issue is appeared because sourcemapper.js tries to load whole input file to the memory, see line 182 in the sourcemapper.js:

var generatedSource = toUnixLineEnding(fs.readFileSync(fileName, 'utf-8'));

The readFileSync() function is used and it cannot work with large files.
Actually this is V8 issue http://code.google.com/p/v8/issues/detail?id=3853 , but it can be resolved if read any files asynchronously.

**Comment by kripken** [comment]
I think I'm confused, isn't that a node.js function? Or does it depend on that functionality of v8, which fails?

Is this in a 32-bit or 64-bit build?

**Comment by systemmind** [comment]
Yes, the function readFileSync() is a node.js function. But it seems that v8 does not processes it properly (I can just imagine because I am not into javascript and node.js :))
But when sourcemapper.js is executed (if -g4 options is set) and if one of it input files is large (my file was more than 300 Mb) emscripten build process is interrupted with error like this:

#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int)
 3: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
 4: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: ??
 7: ??

I have investigated this issue and my solution was a rewriting emscripten/tools/source-maps/sourcemapper.js file i.e using fs.readFile(filename[, options], callback) instead of fs.readFileSync(filename[, options]). So I could work around this problem.

I am working on Ubuntu 12.04 LTS 32-bit, node.js v0.12.6

**Comment by kripken** [comment]
I see, thanks. Can you please open a pull request with that change? It looks like the right solution.

**Comment by ricochet** [comment]
I'm hitting this on my project as well. Any progress with a pull request?

**Comment by systemmind** [comment]
I'm sorry for delay. I'll create it as soon as possible.

**Comment by haraldreingruber** [comment]
Hi @systemmind,
could you share your workaround to the string size limit? I would love to have a look at it, probably I am facing the same problem...

**Comment by haraldreingruber** [comment]
@systemmind Do you still have your fix somewhere? If not please let me know. Thx.

**Comment by systemmind** [comment]
Hi. This is my git patch. Copy it to the source-map (it is ~/emsdk_portable/emscripten/master/tools/source-maps/ in my machine) folder and apply.
[sourcemapper.patch.txt](https://github.com/kripken/emscripten/files/219691/sourcemapper.patch.txt)

Regards.

**Comment by kripken** [comment]
@systemmind: can you please open a PR with your fix?

**Comment by haraldreingruber** [comment]
Thanks for your patch.

Unfortunately I now run into another issue:

`events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/var/folders/sj/6zxpkd214k15qxdww88t7v9m0000gt/T/tmpFr3Er5tmpWQT7ny.jsfunc_51.js.jo.js.jo.js'
    at Error (native)
Traceback (most recent call last):
  File "/Users/roman/Projects/emsdk_portable/emscripten/tag-1.36.1/em++", line 13, in <module>
    emcc.run()
  File "/Users/roman/Projects/emsdk_portable/emscripten/tag-1.36.1/emcc.py", line 1771, in run
    '--offset', str(0)])
  File "/Users/roman/Projects/emsdk_portable/emscripten/tag-1.36.1/tools/jsrun.py", line 75, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/Users/roman/Projects/emsdk_portable/node/4.1.1_64bit/bin/node', '/Users/roman/Projects/emsdk_portable/emscripten/tag-1.36.1/tools/source-maps/sourcemapper.js', '/var/folders/sj/6zxpkd214k15qxdww88t7v9m0000gt/T/tmpKFId5p/ViewAR.bc.o.js.pp.js', '/var/folders/sj/6zxpkd214k15qxdww88t7v9m0000gt/T/tmpFr3Er5tmpWQT7ny.jsfunc_51.js.jo.js.jo.js', '/var/folders/sj/6zxpkd214k15qxdww88t7v9m0000gt/T/tmpFEan8utmp5n_n3E.jsfunc_20.js.jo.js.jo.js', '--sourceRoot', '/Users/roman/Projects/viewar-build-chain/WebGLBuild/ViewARApps/ViewARTemplate/Emscripten', '--mapFileBaseName', '../../../bin/ViewAR.html', '--offset', '0'] to finish with return code 0, but it returned with code 1 instead! Output:
make[2]: *** [bin/ViewAR.html] Error 1
make[1]: *** [ViewARApps/ViewARTemplate/Emscripten/CMakeFiles/ViewAR.dir/all] Error 2
make: *** [all] Error 2`

Maybe the temporary file get's cleaned up too early... Maybe it has to do with generating sourcemaps from emterpretified code, has anybody ever tried that?

**Comment by kripken** [comment]
I'm not sure, but I would not be surprised if sourcemaps are not compatible with the emterpreter option. Looks like in the test suite, source maps tests are disabled in that mode.

**Comment by haraldreingruber** [comment]
@kripken Do you think it would be feasible to skip sourcemaps generation for functions contained in the EMTERPRETIFY_WHITELIST?

**Comment by kripken** [comment]
I'm not that familiar with the source maps code, so I'm not sure offhand.
