### ISSUE TITLE
handleMessage of library_sockfs.js: array good, string bad... why?

### ISSUE THREAD

**Issue by emrahgunduz** [emscripten-core/emscripten#3651]
Hi,

Currently I'm working on a project in Unreal Engine 4 with a custom networking background. I already have a good tcp socket client implementation written with native socket on osx.

I wanted to give a try for the HTML output, and was told that the tcp socket implementation will be converted to websocket by emscripten... which is something magical like unicorns, you can't believe when you hear :) . Anyway...

Server part is node.js so implementing a websocket on top of the current tcp stack was easy. We used "ws". However, when it came to testing the TCP part, websocket implementation started to throw errors.

As it turned out the data was coming to the browser in string form, even though ws has a `socket.send(message,{binary:true, mask:false})` kind of setting.

So I was wondering. Would it be a nicer implementation if current https://github.com/kripken/emscripten/blob/667dcd241886fdb878e248d95d8e03abb09c80b7/src/library_sockfs.js#L275

``` javascript
assert(typeof data !== 'string' && data.byteLength !== undefined);
```

was changed with something like

``` javascript
if( typeof data == 'string' ) {
  var strUtf8 = unescape( encodeURIComponent( data ) );
  var ab = new Uint8Array( strUtf8.length );
  var le = strUtf8.length;
  for ( var i = 0; i < le; i++ ) {
    ab[i] = strUtf8.charCodeAt(i);
  }
  data = ab;
} else {
  data = new Uint8Array(data);  // make a typed array view on the array buffer
}
```

Is assert (binary must) a protocol requirement?

**Comment by kripken** [comment]
Hmm, do you know why it was not sent as binary, even though it was supposed to? Perhaps a node or ws bug?

We could accept strings, but it definitely makes things slower, and also opens up some risks for bugs (very long strings, strings with odd escaped characters due to how strings work in JS, etc.), which is why I think it is best to fix the origin of the data so it sends binary.

**Comment by emrahgunduz** [comment]
I have currently no idea but will look deep into ws and node for a better solution. As we are only using ascii characters for messaging this is not creating any problems for us. But utf8 is another can of worms, so you are definitely right about the long strings... especially in a stream environment.
