### ISSUE TITLE
FS.lookupPath doesn't list files with "__proto__" name

### ISSUE THREAD

**Issue by Kagami** [emscripten-core/emscripten#3663]
Hi. The following examle demonstrates the problem:

``` c
#include <stdio.h>
#include <unistd.h>
#include <emscripten.h>

int main(void)
{
    chdir("/home/web_user");
    FILE* f = fopen("__proto__", "w");
    fclose(f);
    FILE* f2 = fopen("toString", "w");
    fclose(f2);
    EM_ASM(
        console.log(FS.lookupPath(".").node.contents);
    );
    return 0;
}
```

There is only `toString` file present in the output.

**Comment by kripken** [comment]
This is due to how JS stringifys objects, if toString is present, it tries to call that. And also it ignores `__proto__` when iterating over an object, so manually doing

````
      var x = FS.lookupPath(".").node.contents;
      for (var t in x) console.log(t);
      console.log('__proto__' in x);
      console.log(x.__proto__);
````

would miss `__proto__`, but would show `toString`.

One solution to this is to write a custom method to print the object, instead of normal `console.log`.

Another solution would be for emscripten to use ES6 `Set` instead of a JS object that we use like a set. We would need to check if all browsers and node etc. support it though. Right now, I can see that node 0.10.25 does not yet.

**Comment by Kagami** [comment]
>One solution to this is to write a custom method to print the object

Huh, I haven't checked (I thought it won't work that way) but it's possible to get value back by accessing it manually, like this:

```js
FS.lookupPath(".").node.contents.__proto__
```

I'm using the `Object.keys` to iterate over the file list and it ignores the `__proto__` like you said, but I think I can use my custom method instead (something like `"contents" in FS.lookupPath(".").node.contents.__proto__` would be sufficient to check the "hidden" file). Great, thanks!

>Another solution would be for emscripten to use ES6 Set

Yea, that would be nice. Another way is to introduce new method which return array instead - arrays don't have such problems.

>We would need to check if all browsers and node etc. support it though

We can use polyfill for that. But I would prefer the array result.

**Comment by kripken** [comment]
The polyfill would increase our code size though, which we already have complaints about. I think that would be hard to justify.

**Comment by evanw** [comment]
If I remember correctly, __proto__ was changed from a general-purpose prototype manipulation tool to an accessor predefined off of Object.prototype. This means that if Object.prototype isn't in the prototype chain, then __proto__ isn't either and it's not an issue. This works fine for me in Chrome and Firefox:

```
var x = Object.create(null);
x.__proto__ = 100;
for (var y in x) console.log(y, x[y]);
```

**Comment by Kagami** [comment]
@evanw nice! So we just need to fix this two objects: [[1]](https://github.com/kripken/emscripten/blob/1.34.4/src/library_fs.js#L45), [[2]](https://github.com/kripken/emscripten/blob/1.34.4/src/library_fs.js#L105). I still don't quite like the usage of object as a result type for that type of operations though.

I'm currently using this workaround (probably not ideal, but works for me):

```js
    function listFiles(dir) {
      var obj = FS.lookupPath(dir).node.contents;
      var names = Object.keys(obj);
      // Fix for possible file with "__proto__" name. See
      // <https://github.com/kripken/emscripten/issues/3663> for
      // details.
      if (obj.__proto__ && obj.__proto__.name === "__proto__") {
        names.push("__proto__");
      }
      return names.map(function(name) {
        return obj[name];
      });
    }
```

**Comment by Kagami** [comment]
Hm, I misread this function. Actually code that handles the node contents is much deeper.
