### ISSUE TITLE
Possible bug in the file system

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [emscripten-core/emscripten#3675]
Hello,

While porting a project I noticed a strange error using boost::filesystem.

When running `boost::filesystem::is_directory("/bop")`. I get this "exception", (which is not really an exception but is still fired) : 

`boost::filesystem::status: Success: "/bop"`

Do you have any idea where does it could come from ? Should I fill a bug report for boost instead ? 

Thank you very much

**Comment by kripken** [comment]
If you build the same boost and testcase and see that in emscripten but not in native, it might be a bug in emscripten. If natively it looks the same, it is more likely a bug in boost.

**Comment by GuillaumeLeclerc** [comment]
I'am using the 1.58 for my emscripten project but 1.54 on my computer. I will just build the same version natively and tell you the result

**Comment by GuillaumeLeclerc** [comment]
The bug is not present in the native executable. They both use boost 1.58 (compiled from the same tarball). As you said it is more likely to be a bug in emscripten

**Comment by GuillaumeLeclerc** [comment]
While this bug is under investigation I made workaround using the non-throwing signature of is_directory : https://gist.github.com/GuillaumeLeclerc/447bf65199b152ece16d
