### ISSUE TITLE
Running optimization passes in LLVM backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#3688]
I tried a new approach to speeding up builds this week. It appears to have failed, but I thought I'd write it up nonetheless.

The background is that right now we run the LLVM backend, then we get that output, and we use a Python process pool of workers that run our optimizer.

LLVM itself is single-threaded, so all the time we spend in the backend uses just a single core. I integrated the optimizer in the backend, so that it spawns worker threads, and sends code to be optimized while it is still running.

Another potentially nice thing in this approach is that it does more in the backend and less in Python. It's already possible to run the backend by itself, and with this change, you could also get optimizations while doing so.

I did manage to get a 5% speedup on moderate-sized codebases like Poppler. However, on large codebases like Unity, I get no improvement and perhaps a tiny slowdown. There might be some opportunities to make this faster, like using lock-free data structures (there is a work queue which we block on, right now), but this probably wouldn't make a big enough difference to justify this change. Worse, on a large codebase like Unity, we used to take 1GB max memory, but now take 2GB, simply because both the backend and the N optimizer threads are in memory at once, and each takes about 1GB.

I don't think the complexity is worth merging this even as a disabled-by-default option.

Code is in internal-optimizer branches in fastcomp and emscripten if anyone is curious.

**Comment by aidanhs** [comment]
Interesting. What was the motivation for this? My gut feeling is that the time spent in python dispatching to the optimizer is a small percentage for compilation of any reasonable size, and the time taken for small compilation probably only matters for the emscripten tests. 

Aside from the above, I personally would want to see ~10% improvement across the board to compensate for the new inconvenience of trying to use the optimizer directly. I suppose this would probably come from the parsing stage - being able to transform directly from backend to optimizer in-memory structures without having to serialize to a string must give at least some speedup.

**Comment by kripken** [comment]
Yeah, parsing is where I was hopeful too. But the benefits just don't seem big enough compared to the cost of keeping everything in memory, I suspect that's the main cause of the slowdown.

Anyhow, I managed to speed up build times significantly in a simpler way, by deferring linking to opt, so instead of llvm-link and then opt, we send opt the files to link, and so we avoid llvm-link serializing and opt deserializing the entire module. Probably possible to further improve that by merging that opt call with the later call to llc, however that seems trickier to do.
