### ISSUE TITLE
How-to call a javascript function 

### ISSUE THREAD

**Issue by hendrik-weiler** [emscripten-core/emscripten#3694]
Hello,

im new to c++ and im trying to call a function already existing in javascript
called "createWidget" within c++.

This is what im trying to call in c++:
createWidget({
    ns : 'test.Test',
    name : 'Test',
    icon : './images/test.png',
    category : 'Uncategorized'
},function(document, window, undefined) {

```
var Test = function(arg1,arg2) {
}
return Test;
```

});

This is as far as i could get.

´´´
# include <stdio.h>
# include <emscripten/val.h>
# include <string>

using emscripten::val;

struct WidgetDefinition{
  std::string ns;
  std::string name;
  std::string icon;
  std::string category;
};

class Widget
{
public:
    Widget() {
        printf("%s\n", "hello there");
    }

};

class WidgetWrapper
{
private: 
    Widget\* _callWidget;
public:
    WidgetWrapper() {

```
}
void SetWidget(Widget* wid) {
    _callWidget = wid;
}
```

};

extern void createWidget(WidgetDefinition\* definition,WidgetWrapper\* cb);

int main() {

```
WidgetDefinition* def = new WidgetDefinition();
def->ns = "test.Test";
def->name = "Test";
def->icon = "./images/test.png";
def->category = "Uncategorized";

Widget* wid = new Widget();

//val doc = val::global("document");
//val test = doc.call<int>("getElementsById","test");
//test.set("innerHTML","hello there");

WidgetWrapper* wrapper = new WidgetWrapper();
wrapper->SetWidget(wid);

createWidget(def, wrapper);
return 0;
```

};
´´´

I compile it with ´´´emcc test.cpp -std=c++11´´´.

Does someone know how to solve this problem?

**Comment by kripken** [comment]
See http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html 

There are multiple ways to do this. If you just to pass some strings from C to JS, you can use an `EM_ASM`, where you receive the C strings, convert them to JS, then create the object and call `createWidget`.

**Comment by hendrik-weiler** [comment]
createWidget({
ns : 'test.Test',
name : 'Test',
icon : './images/test.png',
category : 'Uncategorized'
},function(document, window, undefined) {

var Test = function(arg1,arg2) {
}
return Test;
});

Im basically trying to convert this javascript code to c++, which converts back to this code.
