### ISSUE TITLE
Unable to comple with AGGRESSIVE_VARIABLE_ELIMINATION=1 option

### ISSUE THREAD

**Issue by Andrey1024** [emscripten-core/emscripten#3696]
I compile project with huge code base with emscripten. It started to work on Firefox when I compiled with EMULATE_FUNCTION_POINTER_CASTS=1 option. But on other browsers it raises "max call stack size exceeded" exception. To avoid that i tried to compile with AGGRESSIVE_VARIABLE_ELIMINATION=1 and got following error:

```
end of EMCC_DEBUG output (emscripten version 1.34.4):

chunkification: num funcs: 31264 actual num chunks: 15 chunk size range: 102031282 - 1198069
DEBUG    root: js optimizer using native
splitting up js optimization into 15 chunks, using 4 cores  (total: 163.31 MB)
.
.
.....
.
.
DEBUG    root: applying js optimization passes: asm receiveJSON aggressiveVariableElimination emitJSON
chunkification: num funcs: 17 actual num chunks: 15 chunk size range: 450483887 - 2981586
splitting up js optimization into 15 chunks, using 4 cores  (total: 587.36 MB)
.
.
.......
.


#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int)
 3: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
 4: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: ??
 7: ??
.
Traceback (most recent call last):
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/emcc", line 1553, in <module>
    flush_js_optimizer_queue()
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/emcc", line 1461, in flush_js_optimizer_queue
    run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/emcc", line 1431, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/tools/shared.py", line 1561, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 521, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 521, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/home/andrey/Work/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 436, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError: Error in optimizer: 
...
```

Same issue are with OUTLINING_LIMIT option.
How can I solve it?

**Comment by juj** [comment]
When you get the "max call stack size exceeded" error, do the other browsers print a callstack of what the stack looked like during execution?

I would not recommend using `-s AGGRESSIVE_VARIABLE_ELIMINATION=1` on such huge codebases. It is a great optimization pass, but since it's current implemented as JS code, it does have trouble with huge codebases. If I read that correctly, you have 587.36MB of Javascript code! That can't be minified, is it? What are your compiler and linker flags like? Are you linking with at least one of `-O1`, `-O2`, `-O3`, `-Os` or `-Oz` and are not specifying a `-g<num>` setting? Unfortunately building extremely large projects with debugging info intact is not currently feasible.

**Comment by Andrey-Vlasov** [comment]
It works fine on Firefox and node with v8 stack size 4023(if less - call stack size error) on any optimization level. Chrome is just hanging. Output js takes 60-70 MB with O2+. I compiling project with disable exception catching and emulate function pointers cast options.

**Comment by kripken** [comment]
What happens when chrome hangs? Is it running out of memory, or just running very slowly or something else?

**Comment by Andrey-Vlasov** [comment]
After some time, it shows crash message "Aw, Snap!" and offers to reload page. And pop-up message "Inspected target disconnected" in debugger. Nothing in console.

**Comment by kripken** [comment]
Probably running out of memory in chrome, then. There is a known issue where chrome takes a lot of memory to compile large asm.js modules.

Splitting the codebase up into smaller modules, and using [dynamic linking](https://github.com/kripken/emscripten/wiki/Linking), might be a way to work around this.

**Comment by Andrey-Vlasov** [comment]
Okay, I will try it. Thank you for the quick reply.
