### ISSUE TITLE
problem with sdl_ttf

### ISSUE THREAD

**Issue by mockthebear** [emscripten-core/emscripten#3703]
i was porting my game to emscripten. Everything was fine until SDL_ttf. Actually i am using sdl2 + sdl2 image + sdl mixer.

I will show an example:

SDL_Color color = {255,255,255};
    std::cout << "1\n";
    font = TTF_OpenFont("saucery/font/font1.otf", 8);
    if (!font)
        printf("Unable to load font: %s \n",  TTF_GetError());
    std::cout << "2\n";
    SDL_Surface *surf = TTF_RenderText_Solid(font,"Oieee",color);
    std::cout << "3\n";
    if (surf){
        std::cout << (int)surf << "\n";
        texture = SDL_CreateTextureFromSurface(Game::instance->GetRenderer(),surf);
        std::cout << "4\n";
        Uint32 format;
        int acess,w,h;
        SDL_QueryTexture(texture, &format,&acess,&w,&h);
        dimensions2.x = 0;
        dimensions2.y = 0;
        dimensions2.h = h;
        dimensions2.w = w;

```
    SDL_FreeSurface(surf);


}
```

n this code i just open an font (i have already changed the size and the type to .ttf). Everything seems to run fine until:

SDL_CreateTextureFromSurface

I put some std::cout to see where the code was "crashing". Everytime it calls the createTextureFrom on the console shows to me "45" and the running stops there.

Even with any std::cout i still get this error. this is driving me crazy already ._.

edit: with -o2 i got:
Unable to load font: No GL driver has been loaded

**Comment by kripken** [comment]
A risk factor is that we don't have a port of `sdl2_ttf`, so we use our sdl1 code for it. There might be an incompatibility that you are hitting. Can you provide a full standalone testcase I can take a look at?

**Comment by mockthebear** [comment]
Of course!
http://pastebin.com/MkDKVCAh
With assets:
https://www.dropbox.com/s/5xttf04x4aebnhd/testttf.zip?dl=0

I have noticed that this time it dont crash. But create only an black square and the sprite that i have loaded dont show. But when i remove the thext parte. everything works.

**Comment by kripken** [comment]
I also don't see a crash, but running with `SAFE_HEAP` does show a segfault. And it looks like the cause is what I suspected - we need a proper port of `SDL2_ttf` from source, instead of our SDL1 version (SDL2 is looking into the internals of the surface that our SDL1 code generated).

It takes a little work to add a port, but hopefully it would be easy for `SDL2_ttf`. It depends on TrueType which we already have in ports, #3685. Another recent pull that added ports code is #3646 which can help see how it's done, if you or someone else are interested to do this.

**Comment by mockthebear** [comment]
In this example i dontt get crashes as i said, but everything was not behaing as expected. I will try some of these solutions, if any help me i will use some bitmap fonts and clip it. 
#LD33 Here we go c:

**Comment by TheKK** [comment]
I would like to give this a try!

**Comment by kripken** [comment]
Great, let me know if you need any guidance.

**Comment by mockthebear** [comment]
Maybe this could work:
https://groups.google.com/forum/#!topic/emscripten-discuss/lfXaVdyYztw

**Comment by TheKK** [comment]
@mockthebear
Hi, I have good news for you. I've create a patch for porting SDL2_ttf :)
Here it is, #3728. I've tried the test case you gave and it successfully shown a rotating bear head and a line of text on top left corner (after I remove // before the text rendering code).

**Comment by mockthebear** [comment]
Thanks!!!!! I will try do the same here.
