### ISSUE TITLE
Building fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by AppPlusPlus** [emscripten-core/emscripten#3706]
Hi. I have tried building from source using emsdk for the Ubuntu 12.04. Both approaches below failed with the same error message:

1- emsdk install latest
2-  emsdk install sdk-incoming-64bit

`[ 26%] Building CXX object tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/DiagnosticIDs.cpp.o`
`c++: internal compiler error: Killed (program cc1plus)`
`Please submit a full bug report,`
`with preprocessed source if appropriate.`
`See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.`
`make[2]: *** [tools/clang/lib/ASTMatchers/CMakeFiles/clangASTMatchers.dir/ASTMatchFinder.cpp.o] Error 4`
`make[2]: *** Waiting for unfinished jobs....'
'[ 27%] Building CXX object tools/clang/lib/Basic/CMakeFiles/clangBasic.dir/FileManager.cpp.o`

...

`[ 31%] Building CXX object tools/clang/lib/AST/CMakeFiles/clangAST.dir/DeclOpenMP.cpp.o'
'c++: internal compiler error: Killed (program cc1plus)'
'Please submit a full bug report,'
'with preprocessed source if appropriate.'
'See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.'
'make[2]: *** [tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/clangDynamicASTMatchers.dir/Registry.cpp.o] Error 4'
'make[1]: *** [tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/clangDynamicASTMatchers.dir/all] Error 2'
'[ 31%] Building CXX object tools/clang/lib/AST/CMakeFiles/clangAST.dir/DeclPrinter.cpp.o`

It continues, but at [32%] fails:
....
`Command '['make', '-j7']' returned non-zero exit status 2'
'Installation failed!`

Do you have any idea why?
Thanks

**Comment by kripken** [comment]
Perhaps it runs out of memory? Running with less parallel jobs might makj a difference.

**Comment by AppPlusPlus** [comment]
Increased the swap file by 2GB. No success! It seems to be  a memory problem.
By the way, is there any way to clean the unfinished job using emsdk? I couldn't find a clean command.

**Comment by juj** [comment]
To clean an unfinished build of clang, just go in the build directory (something like `emsdk/clang/fastcomp/build_incoming_64bit/`) and type `make clean`. To also do a full reconfigure, you can simply delete the build artifact directory `emsdk/clang/fastcomp/build_incoming_64bit/` and reissue the install command.

To attempt to reduce memory pressure, try doing a singlethreaded build by running `make`  in the build directory. (e.g. incrementally after the failed first install) Does that give the same internal compiler error? If so, possibly upgrade to newer compiler on your system, or search if that's a known LLVM issue?

**Comment by AppPlusPlus** [comment]
Thanks @juj! I experienced a similar problem on my Mac. Solved it by "incremental" build after each fail or freeze. Try to resolve it on my Linux machine as well. I will update this post.

**Comment by juj** [comment]
Good to hear you got it working. Were the failures inside a virtualized environment perhaps? Or how much RAM does it have? I'm thinking we could do some kind of memory limit/thread to avoid risking out of memory issues.

**Comment by AppPlusPlus** [comment]
The Mac machine was just freezing. I didn't get any errors. I will try the Linux machine again

**Comment by juj** [comment]
@AppPlusPlus: did you ever manage to build it on linux? Does `./emsdk install sdk-incoming-64bit -j1` work for you? Note the `-j1` flag to have the build force a singlethreaded run to avoid running out of memory.

**Comment by tlightsky** [comment]
`-j1` works for me :)
