### ISSUE TITLE
Compiling an existing C++ project

### ISSUE THREAD

**Issue by AppPlusPlus** [emscripten-core/emscripten#3707]
I successfully ran a medium sized project.
Now, I would like to compile a huge project with heavy uses of STL, templates, void\* pointers, pointers to member functions, and C++11 features. How can I proceed by imposing minimum change on the existing code?

I use:
`em++ -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=16 --std=c++11`
I got errors like:

`error: no template named '_Deque_iterator' in namespace 'std';`
`error: indirection requires pointer operand ('iterator' (aka 'int') invalid)`
`error: 'reference' is a protected member of ...`
`reference to non-static member function must be called`

The code compiles with a couple of warnings with g++4.9, but here exited with "too many errors"

I don't expect to have my code compiled without any effort, but at least how can I get rid of the "protected members" errors?

For example, from `#include <deque>`, I get `error: 'reference' is a protected member of ...`, `error: 'pointer' is a protected member of ...` I have seen that they have a definition in `/tag-1.34.6/system/include/libcxx/deque.` But I cannot figure out what is the error about!

**Comment by kripken** [comment]
That is libc++ code. It's possible you are using c++ standard library features that hit a bug in libc++.

It might be useful to build your project natively against libc++, to check. If you find that a newer version of libc++ fixes the issue, it would mean we should try to upgrade our libc++.

**Comment by AppPlusPlus** [comment]
Thanks! I don't know. It might be related to compiling on Mac. I couldn't figure it out. But I have changed the path to the libc++ and I still got the same errors:

 `error: no template named '_Deque_iterator' in namespace
      'std'; did you mean '__deque_iterator'?
        typedef std::_Deque_iterator<LType, LType&, LType*> iterator;
                ~~~~~^~~~~~~~~~~~~~~
                     __deque_iterator
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/deque:266:29: note:
      '__deque_iterator' declared here
class _LIBCPP_TYPE_VIS_ONLY __deque_iterator`

**Comment by kripken** [comment]
Not sure I understood that - did you build natively using emscripten's libc++ headers, and get the same errors?

**Comment by AppPlusPlus** [comment]
Yes, but what I said in the second comment is that I got the same errors when using g++ instead of g++-mp-4.9, so it might not be related to emscripten

**Comment by kripken** [comment]
Oh, ok.

If you look more into this and reduce it to a small testcase, that might be easier to further investigate.

**Comment by AlexanderKozhevin** [comment]
@AppPlusPlus What options did you use to compile it? So it's not just like 
```
emcc myApp.cpp -o myApp.wasm
```
Isn't it ? :)
I tried to compile C++ file with a lot of includes. But looks like it doesn't see them. 
Can you give me small hint, please?
