### ISSUE TITLE
Using static and dynamic libraries

### ISSUE THREAD

**Issue by AppPlusPlus** [emscripten-core/emscripten#3713]
Hi. I have seen that the support for linking has been changed over time. I have a general question. Which one of these are supported in the latest version?

1- Using .a static libraries? 
2- Using .so shared libraries?
3- Using .lib static libraries?
4- Using .dll dynamic libraries?

So, if a library is created by another gcc compiler, then would it be possible to link it with a emscripten project?

**Comment by kripken** [comment]
The docs at https://github.com/kripken/emscripten/wiki/Linking are up to date.

gcc can't emit LLVM bitcode or JS, so we can't link to that.

**Comment by AppPlusPlus** [comment]
Probably I didn't ask my question clearly. If you have a C++ library and a C++ user code, would it be possible to link them together? I mean, in principle, it should be possible to define a JavaScript wrapper around unresolved functions and use their definition from the C++ library. Isn't it?

**Comment by kripken** [comment]
Yes, you can statically and dynamically link a C++ library and C++ user code. Statically is trivial, it's just bitcode that LLVM links for us. Dynamically, see for example in the test suite we have `test_dylink_class` that links a simple C++ class.

**Comment by AppPlusPlus** [comment]
I think we are talking about different things. By library, I mean I don't have the source. I cannot recompile it. it is just a C++ dll. Is it something similar to glue code in node.js available?

**Comment by kripken** [comment]
A C++ DLL containing x86 binary code? Emscripten doesn't know how to interface with that.

A C++ DLL containing LLVM IR - i.e., an Emscripten-compiled bitcode file - would be fine of course.

**Comment by amanvm** [comment]
I guess what AppPlusPlus is asking is: If I write a new C++ function-A that calls another function-B and function-B resides in a dynamic shared library compiled from GCC (source code of function-B is unavailable, it was compiled by GCC into a dynamic library eons ago, and we have the headers of course), will this scheme work with emscripten?

Thanks,

AM

**Comment by kripken** [comment]
No, function-B is in x86 or some other native format, so emscripten can't compile code to work with it. (For that to work, you would need an x86-to-JS or x86-to-wasm compiler, which is possible in theory but a  very large amount of work.)

**Comment by pixelherodev** [comment]
"A C++ DLL containing LLVM IR - i.e., an Emscripten-compiled bitcode file - would be fine of course." Really glad I found this issue, thanks!

Nice work on this project, it's amazing!
