### ISSUE TITLE
Using enum int for binding DEFINES in WebIDL

### ISSUE THREAD

**Issue by zz85** [emscripten-core/emscripten#3720]
This is more of a question or a discussion more than an issue.

What I was trying to archive was figuring out how to expose some defined constants via WebIDL. Eg.

``` c
#define HELLO_WORLD 1 
```

It seems like [WebIDL](https://heycam.github.io/webidl/) unfortunately only describes classes or interfaces, and doesn't seem to have keywords to expose defines. The only thing which lives outside of interface is typedef and enums.

It turns out (after observing how the bindings are creating for enum), that I could abuse enum to expose the constant. and it seems to work!

``` c
enum int {
     "HELLO_WORLD"
};
```

So my question is: do you think this approach is acceptable? Is there a better way to do this? (eg. using Embind? Wrap all defines under extern?)

**Comment by zz85** [comment]
So it seems like this approach works for int but not for doubles..

**Comment by kripken** [comment]
How about just creating a class to hold those constants?

````
interface Constants {
  int HELLO_WORLD = 1;
};
````

**Comment by zz85** [comment]
thanks again @kripken! however the need to redefine constants here doesn't seem like an ideal approach to me... 

turns out that I could use embind + webidl without too much baggage, and i think that might be my approach to get defines working together with webidl ;)

```c
constant("HELLO_WORLD", HELLO_WORLD);
```

**Comment by kripken** [comment]
Oh, the redefining is the issue.

Reopening, hopefully we can find a better solution for this. It would be nice to not need to mix embind in here just for constants.
