### ISSUE TITLE
Prevent browser crash for -s ALLOW_MEMORY_GROWTH=1

### ISSUE THREAD

**Issue by yurevich1** [emscripten-core/emscripten#3744]
As I found before usually 512Mb is maximum. But some browsers crashes with lower memory usage.
E.g. in Chrome browser on Android device my script totally crashes the page but in browser the same Browser on my laptop (win7x64) all works correctly.
Is it possible to detect max memory that browser can support in order to prevent crashing?
I think TOTAL_MEMORY=... wouldn't help here. Or not?

**Comment by kripken** [comment]
In general browsers don't tell you how much memory is available. Allocation of typed arrays can fail with an exception, and if the browser runs out of memory internally it can crash the page, but this is arguably a browser bug.

Are you sure your crash is due to the amount of memory used?

**Comment by yurevich1** [comment]
I've tested to compressing xz library using emscripten port. I found the used memory correlates to 'compression value'. I.e., '9' is 1Gb (that's why this value doesn't work in all browsers), '8' - 512Mb. Lesser values works on my laptop browsers but not always on Android Chrome browser (the page crashes). I will test this again and prepare a link to show in 2 days.

**Comment by yurevich1** [comment]
I've found Chrome browser page crashing if, for instance, I set TOTAL_MEMORY up to 512Mb. It says 'Oops.. not enoght memory, plz close the other pages and apps, etc...'
at this line:
var buffer.
buffer = new ArrayBuffer(TOTAL_MEMORY);

If I use default value, it crashes with such values:
Warning: Enlarging memory arrays, this is not fast! 67108864,268435456.

Opera browser gives has behavior.

Don't know how can I prevent this. The only idea is to disable this features in Chrome and Opera.

**Comment by kripken** [comment]
Yes, looks like limitations of those browsers, they are not succeeding to allocate a contiguous chunk of memory of the right size. This should not be a problem on 64-bit browsers, but I believe those browsers on Android are still 32-bit.

**Comment by yurevich1** [comment]
Is it possible to detect 32 bit browsers? Or the only solution is to detect something like 
if(!((is.chrome() || is.opera()) && is.mobile()))  {
//use the lib
} else {
//alert something
}

**Comment by juj** [comment]
I can see that some applications might want to allocate a heap of size up to e.g. 512MB, but they'd settle for less if 512MB is not available. I wonder if that kind of heap allocation mode might make sense? i.e. "get me as much as possible <= 512MB" or something like that.

It is possible to detect browsers, operating systems and bitness. See http://www.w3schools.com/jsref/obj_navigator.asp and StackOverflow/Google the different fields.

**Comment by yurevich1** [comment]
Just wanna say, "I have errors again!"  If I try to optimize code using 
```
 ../emscripten/emcc -O2 ./emsc/fs.c src/liblzma/.libs/liblzma.a -Isrc/liblzma/api -s TOTAL_MEMORY=536870912  -o emsc/html/fs.min.html
```

but without -O2 all works.
I can't find an error because on correct callstack is show.
It just says, "No such file or directory"

This problem appears in Firefox. But in Chrome it works.
