### ISSUE TITLE
Array Support in WebIDL?

### ISSUE THREAD

**Issue by zz85** [emscripten-core/emscripten#3747]
currently 

eg

``` c
interface Klass {
  bool bla(double[] testinig);
}
```

generates

``` c
bool EMSCRIPTEN_KEEPALIVE emscripten_bind_Klass_bla(Klass* self, double arg0) {
  return self->bla(arg0);
}
```

Are arrays supported in emscripten WebIDL?

**Comment by kripken** [comment]
There is partial support, see `ArrayClass` in `test_webidl` (idl file is at `tests/webidl/test.idl`), the stuff there is known to work. Perhaps we don't support arrays as arguments, though, which is what your example needs.

**Comment by sasha240100** [comment]
@kripken Any updates on this issue?

**Comment by kripken** [comment]
I don't think so. We did hit the problem in [ammo](https://github.com/kripken/ammo.js/issues/159) too. Definitely worth fixing. I might not have time myself, but can guide someone that does.

**Comment by sasha240100** [comment]
@kripken Faced a problem with ammo.js - i am trying to add [this api](http://bulletphysics.com/Bullet/BulletFull/structbtSoftBody_1_1Link.html) and getting following errors:
![image](https://cloud.githubusercontent.com/assets/7657429/21701071/45de841c-d3ac-11e6-99af-c9f5463ce636.png)

See line 740:
![image](https://cloud.githubusercontent.com/assets/7657429/21701092/600a5ee2-d3ac-11e6-81a1-e6583b8d59ee.png)

**Comment by sasha240100** [comment]
@kripken What am i doing wrong?

**Comment by kripken** [comment]
Not sure. Is the return type of the function a fixed-size array? That's my guess based on the error message. In that case, we don't have a simple solution for it, we'd need to add something.

**Comment by sasha240100** [comment]
@kripken Already fixed that. The problem was that I forgot to specify `Const` in WebIDL file

**Comment by VirtualTim** [comment]
Pretty sure this is long fixed.
I'm using things like `void idlDefinedFunction(unsigned long[] pRGBA);`, which generates:
```
void EMSCRIPTEN_KEEPALIVE emscripten_bind_idlDefinedFunction_1(interfaceName* self, unsigned int* arg0) {
  return self->idlDefinedFunction(arg0);
}
```
