### ISSUE TITLE
Not obvious how to call C functions from Javascript

### ISSUE THREAD

**Issue by reduz** [emscripten-core/emscripten#3759]
I'm trying to call C functions from javascript, but running into a few issues with the documentation, which I believe is not clear:

**First**, the example shows a single file compile+link so it's not obvious if this is a compiler or linker flag:

```
./emcc tests/hello_function.cpp -o function.html -s EXPORTED_FUNCTIONS="['_int_sqrt']"
```

I assumed this is a compiler flag, so I used it like this:

```
emscripten/tag-1.34.7/emcc -o platform/javascript/audio_server_javascript.javascript.debug.bc -D_DEBUG -Wall -O2 -DDEBUG_ENABLED -s EXPORTED_FUNCTIONS="['_audio_server_mix_function']"  platform/javascript/audio_server_javascript.cpp

```

**Second** I put my function as extern C but nothing calls it from the C++ code. Must I expect this not to be optimized away by the linker?

```
extern "C" {


void audio_server_mix_function(int p_frames) {

    print("mixer called");
}

}
```

**Third** As always, the documentation is expecting that my function will return a value, which it won't, quoting: 

"The first parameter is the name of the function to be wrapped, the second is the return type of the function, and the third is an array of parameter types (which may be omitted if there are no parameters). The types are native JavaScript types, “number” (for a C integer, float, or general pointer) or “string” (for a C char\* that represents a string)."

This is nice and well, but what I don't want is the return type and it is not explained here how to skip it. Please make this clearer. As a result, I wrote "undefined" instead like this and expect it to work: 

```
audio_server_mix_function = Module.cwrap('audio_server_mix_function', 'undefined', ['number']);
```

**Fourth** When I run my code it doesn't work, I get the following message: 

```
Assertion failed: Cannot call unknown function audio_server_mix_function (perhaps LLVM optimizations or closure removed it?)
```

I believe I did everything right (as far as my knowledge allows me to understand), yet it's not working. I'm reporting this issue because I believe the problem may be either my misunderstanding or a failure in the documentation.

**Comment by brion** [comment]
* exports are a link-time parameter (when creating the JS output)
* exports are what keep the linker from optimizing out your unused function
* I believe you want 'void'

**Comment by reduz** [comment]
Thanks, will test tonight when i get back home!

Would really appreciate if the doc had these issues clarified, too.. so leaving open.

**Comment by kripken** [comment]
1 and 3: Added fixes to docs, thanks!

2: Functions **will** be optimized out by LLVM by default. You can use `EMSCRIPTEN_KEEPALIVE` to keep things alive, see the [faq](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process).
