### ISSUE TITLE
Is initial FS syncinc synchronous?

### ISSUE THREAD

**Issue by reduz** [emscripten-core/emscripten#3772]
I'm noticing that FS.syncfs has a function that lets you know when it's done:

```
function myAppStartup(callback) {
  FS.mkdir('/data');
  FS.mount(IDBFS, {}, '/data');

  FS.syncfs(true, function (err) {
        // handle callback
  });
}
```

Also here.

https://github.com/kripken/emscripten/blob/master/tests/fs/test_idbfs_sync.c

Is this function Synchronous? as in, does it return immediately or sometime later when the "//handle callback" function is called? If Asynchronous, how can I make sure my application waits until this is done synching back the fs?

**Comment by kripken** [comment]
It's an asynchronous JS function. It returns immediately, and some time later the callback will be run. When the callback is run, you know that the syncing has completed, so you should not do things until that point that depend on the data.

You might use a pattern like this:

````
void func() {
  ..
  EM_ASM({
    FS.syncfs(.., function(err) {
      Module._continue();
    });
  });
  // might want to pause the main loop here, if one is running
}

extern "C" {
void EMSCRIPTEN_KEEPALIVE continue() {
  // data is now here, continue and use it
  // can resume main loop, if you are using one
}
````

**Comment by reduz** [comment]
Oh OK, I guess then first of all things will sync FS then, thanks!

**Comment by reduz** [comment]
At the end I made it so it syncs the filesystem while the engine
initializes, this worked pretty well with no noticeable delay :)
