### ISSUE TITLE
Missing setsockopt() options

### ISSUE THREAD

**Issue by raptor** [emscripten-core/emscripten#3773]
Hi,

My code uses two `setsockopt` options that do not seem to be supported with emscripten (I am unsure if they can be):

```
SO_RCVBUF
SO_SNDBUF
```

Here is a test case for both (both throw `Protocol not available`):

```
#include <sys/socket.h>
#include <netinet/in.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>

int main() {
   unsigned int netNum[4] = {0};
   unsigned short port = 0;
   signed int recvBufferSize = 32768;
   signed int sendBufferSize = 32768;
   signed int error = 0;

   sockaddr address;

   // UDP
   signed int sock = socket(AF_INET, SOCK_DGRAM, 0);

   // Create socket address from port and IP
   memset(&address, 0, sizeof(sockaddr_in));
   ((sockaddr_in *) &address)->sin_family = AF_INET;
   ((sockaddr_in *) &address)->sin_port = htons(port);
   ((sockaddr_in *) &address)->sin_addr.s_addr = htonl(netNum[0]);
   socklen_t addressSize = sizeof(sockaddr_in);

   error = bind(sock, &address, addressSize);
   if(error) printf("bind() errno %s\n", strerror(errno));

   error = getsockname(sock, (sockaddr*) &address, &addressSize);
   if(error) printf("getsockname() errno %s\n", strerror(errno));

   error = setsockopt(sock, SOL_SOCKET, SO_RCVBUF, (char *) &recvBufferSize, sizeof(recvBufferSize));
   if(error) printf("1 setsockopt() errno %s\n", strerror(errno));

   error = setsockopt(sock, SOL_SOCKET, SO_SNDBUF, (char *) &sendBufferSize, sizeof(sendBufferSize));
   if(error) printf("2 setsockopt() errno %s\n", strerror(errno));

   return 0;
}
```

The bottom 2 `printf` statements trigger.

I suspect I may hit a number of similar issues as this is older network code.

Thanks!

**Comment by raptor** [comment]
On second thought, below is a full test case containing how we initialize the UDP socket in full.  There is an added `setsockopt` call and an `ioctl` call which also fail (unless I'm calling `errno` incorrectoly):
```
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

int main() {
   unsigned int netNum[4] = {0};
   unsigned short port = 0;
   signed int recvBufferSize = 32768;
   signed int sendBufferSize = 32768;
   bool acceptBroadcast = true;
   unsigned int notblock = 1;
   signed int error = 0;

   sockaddr address;

   // UDP
   signed int sock = socket(AF_INET, SOCK_DGRAM, 0);

   // Create socket address from port and IP
   memset(&address, 0, sizeof(sockaddr_in));
   ((sockaddr_in *) &address)->sin_family = AF_INET;
   ((sockaddr_in *) &address)->sin_port = htons(port);
   ((sockaddr_in *) &address)->sin_addr.s_addr = htonl(netNum[0]);
   socklen_t addressSize = sizeof(sockaddr_in);

   error = bind(sock, &address, addressSize);
   if(error) printf("bind() errno %s\n", strerror(errno));

   error = getsockname(sock, (sockaddr*) &address, &addressSize);
   if(error) printf("getsockname() errno %s\n", strerror(errno));

   error = setsockopt(sock, SOL_SOCKET, SO_RCVBUF, (char *) &recvBufferSize, sizeof(recvBufferSize));
   if(error) printf("1 setsockopt() errno %s\n", strerror(errno));

   error = setsockopt(sock, SOL_SOCKET, SO_SNDBUF, (char *) &sendBufferSize, sizeof(sendBufferSize));
   if(error) printf("2 setsockopt() errno %s\n", strerror(errno));

   error = setsockopt(sock, SOL_SOCKET, SO_BROADCAST, (char*)&acceptBroadcast, sizeof(acceptBroadcast));
   if(error) printf("3 setsockopt() errno %s\n", strerror(errno));

   error = ioctl(sock, FIONBIO, &notblock);
   if(error) printf("ioctl() errno %s\n", strerror(errno));

   close(sock);

   return 0;
}
```

**Comment by kripken** [comment]
Hmm, I'm not sure from the docs what `SO_RCVBUF` exactly does. Is it necessary for you to call it? I'm wondering if it's an option and that things would still work without that adjustment.

**Comment by raptor** [comment]
Yes, commenting out the first two, `SO_RCVBUF` and `SO_SNDBUF` will just let the system default to its internal values.  The test case still returns an error on the last `SO_BROADCAST` of `Protocol not available` and fully aborts on the `ioctl` with `abort("bad ioctl syscall 21537")`.

I've looked into ENet and I find these options in their code.  Is there a different source that had emscripten changes?

**Comment by raptor** [comment]
Commenting out the `ioctl` line will allow the game to not abort and try and connect to our server..  Admittedly, I do not know much (yet) about browser implementations of sockets.  Compiling with `SOCKET_DEBUG=1` shows this:
```
connect: ws://bitfighter.org:25955/, binary
websocket adding peer: bitfighter.org:25955
websocket queuing port message (port 0)
websocket queuing (10 bytes): 0,30,47,17,196,199,215,27,228,220
Socket close fd = 5
```
Wireshark shows TCP packets attempting to connect to our master server at the correct port (25955).  Our master server isn't responding because they're not UDP.

**Comment by kripken** [comment]
We use ENet pretty much unchanged, see the BananaBread repo. Perhaps they just don't call that method?

Yes, WebSockets are TCP. You can use some sort of WebSockets bridge to UDP, but you would still have TCP exponential backoff, etc. Another option is to use WebRTC which has UDP-like data channels, but it is still not plain raw UDP, and would require some bridge as well.

**Comment by raptor** [comment]
I looked a little into WebRTC and found that emscripten has experimental support.  I compiled with `SOCKET_WEBRTC=1` with no issues, but runtime throws various `abort` messages which I'll have to diagnose later.

I don't think I'll mind programming a bridge on our master server if we can still get browser clients over UDP.

Do you know of any project using WebRTC and emscripten?

Thanks!

**Comment by kripken** [comment]
The main one was BananaBread, we have a multiplayer FPS game working. It's Cube 2 so ENet is used. It worked well at the time, but I don't think it's maintained.

**Comment by raptor** [comment]
Compiling with `-s SOCKET_WEBRTC=1` on the following test case yields an abort:
```
TypeError: sock.sock_ops is undefined
```
Test case:
```
#include <sys/socket.h>
#include <netinet/in.h>
#include <string.h>

int main() {
   unsigned int netNum[4] = {0};
   unsigned short port = 0;
   signed int error = 0;

   // UDP
   signed int sock = socket(AF_INET, SOCK_DGRAM, 0);

   // Create socket address from port and IP
   sockaddr address;
   memset(&address, 0, sizeof(sockaddr_in));
   ((sockaddr_in *) &address)->sin_family = AF_INET;
   ((sockaddr_in *) &address)->sin_port = htons(port);
   ((sockaddr_in *) &address)->sin_addr.s_addr = htonl(netNum[0]);
   socklen_t addressSize = sizeof(sockaddr_in);

   error = bind(sock, &address, addressSize);

   return 0;
}
```
I'm looking into BananaBread - it looks like it doesn't have WebRTC for network in the master branch, but I found this which was never merged:  https://github.com/kripken/BananaBread/pull/38
I can't tell if that was using emscripten or if they coded that directly into the JS libraries (maybe both?)

**Comment by kripken** [comment]
Yeah, that might have never been merged. I don't remember why.

In general WebRTC support in emscripten has not been well tested, so it might not be in good shape. We need more help there.

**Comment by missmah** [comment]
Any updates here?

There seem to be **incredibly mixed messages **across the web about this, including  [this article](https://hacks.mozilla.org/2013/03/webrtc-data-channels-for-great-multiplayer/), whichs says that WebRTC support has been implemented in BananaBread...

**Comment by kripken** [comment]
Sorry for the confusion here. We had initial WebRTC support that was kind of hackish, but worked well in BananaBread. However, it was hard to keep it properly tested, and it broke eventually, and is no longer officially supported.

There is however some activity in #3818, hopefully we can restore WebRTC support.

**Comment by lucast70** [comment]
I face exactly the same problem trying to compile libpq (Postgresql client library) using emscripten 1.37.3. Is there any workaround on this?

**Comment by raptor** [comment]
As far as UDP support in a browser, have any options matured since I opened this issue?  

Seems like WebRTC was one idea, but UDP sockets at the browser level in both firefox and chrome might be another...

**Comment by sbc100** [comment]
I think both WebRTC, and other web standard that are coming down the pipe still only all for connecting back to the origin.

I believe emscripten does now have socket emulation on top of WebRTC though.   See tests/test_sockets.py for some example of how to use it.
