### ISSUE TITLE
Some GL tests fail on gamma(?) differences.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3778]
Now this is a rather odd situation. Running locally the tests

```
browser.test_gl_ps, error=2 (allowed slack was=1)
browser.test_gl_ps_packed, error=2 (allowed slack was=1)
browser.test_gl_ps_strides, error=1 (allowed slack was=0)
browser.test_gl_ps_worker, error=2 (allowed slack was=1)
browser.test_sdl2_fog_linear, error=2 (allowed slack was=1)
browser.test_sdl_fog_density, error=1 (allowed slack was=0)
browser.test_sdl_fog_linear, error=2 (allowed slack was=1)
browser.test_sdl_ogl, error=2 (allowed slack was=1)
browser.test_sdl_ogl_defaultmatrixmode, error=2 (allowed slack was=1)
browser.test_sdl_ogl_p, error=2 (allowed slack was=1)
browser.test_sdl_ogl_proc_alias, error=2 (allowed slack was=1)
browser.test_sdl_rotozoom, error=6 (allowed slack was=3)
```

on my brand new Windows 8.1 64bit with Core i7 5960X and a MSI GTX 980 4G Gaming with latest Geforce Driver 355.82 (also occurred on an older driver version), each of the above tests fail the per pixel reftest by a very small margin. Looking closer, the failures are due to the image brightness being just so slightly different on the tests (hand-examined test_sdl_rotozoom and test_gl_ps to check). This is really odd, since for one, any display gamma settings should not affect the generated pixel values (gamma is applied at the end of the pipeline in the hdmi output circuitry), and since the recent emunittest reftests do work correctly. Things tested so far:
- Verified that it is not any display driver setting by attempting to tune the different brightness/contrast/gamma knobs in the control panel, that did not change anything. 
- In addition to FF 40, tried old Firefox version from 2012, and current FF Nightly 2015-09-15, the issue persists in each.
- The failure occurs also on Chrome (45) on the same computer.
- The failure does _not_ occur on IE11.
- Running the same Emscripten compiled test page of test_sdl_rotozoom on a Mac OS X computer passes the test, so it is not Emscripten compilation time specific.
- Another Windows computer with Windows 7 and nVidia Geforce GTX 980 passes the tests.

Since IE11 passes the test, I don't think this should be specific to the display driver. I haven't run the browser suite on this computer before, so I don't think the tests have ever passed, so this is not likely a regression. Perhaps it is something to do with ANGLE shader compiler specifically against the MSI GTX 980.. Not sure yet how to fix.

**Comment by kripken** [comment]
I'd be ok to just accept that output as valid. Sounds like "normal GL variation"?

**Comment by juj** [comment]
No, this definitely should not be, the brightness of the images should not change like that. I'd like to understand what the cause of this is before adding the extra slack.
