### ISSUE TITLE
LLVM optimizations generate temporary 128-bit integers which fail compilation.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3789]
The following SSE2 functions end up generating temporary 128-bit wide integer types when LLVM optimizations are applied:

```
_mm_adds_epi16
_mm_adds_epu16
_mm_madd_epi16
_mm_mulhi_epi16
_mm_mulhi_epu16
_mm_subs_epi16
_mm_subs_epu16
_mm_cvtepi32_ps
_mm_load_si128
_mm_loadu_si128
_mm_movemask_epi8
_mm_packs_epi32
_mm_avg_epu16
_mm_srli_epi16
_mm_max_epi16
_mm_max_epu8
_mm_min_epi16
_mm_min_epu8
```

These functions work in debug builds, but not in `-O2` and higher, where they fail with an error message like

```
Unsupported:   %504 = bitcast <4 x i32> %479 to i128
LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
```

**Comment by kripken** [comment]
Testcase?

**Comment by juj** [comment]
Currently to test, commenting out `#define BREAKS_UNDER_OPTIMIZATION` in https://github.com/kripken/emscripten/blob/incoming/tests/test_sse2_full.cpp#L20 exposes the issue.

**Comment by kripken** [comment]
Is this addressed by an outstanding pulls, or does it still need attention?

**Comment by juj** [comment]
Testing in current incoming, this does still exhibit an issue. Compiling

	#include <stdio.h>

	typedef int m128i __attribute__((__vector_size__(16)));

	m128i __attribute__((noinline)) add_epi16(m128i a, m128i b)
	{
	  union {
	    signed short x[8];
	    m128i m;
	  } src, src2, dst;
	  src.m = a;
	  src2.m = b;
	  dst.x[0] = src.x[0] + src2.x[0];
	  return dst.m;
	}

	int main()
	{
	  m128i a = (m128i){ 1, 2, 3, 4 };
	  m128i b = add_epi16(a, a);
	  printf("%d\n", b[0]);
	}

with `em++ a.cpp -o a.js -O2` gives the error

	Unsupported:   %1 = bitcast <4 x i32> %a to i128
	LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
	warning: incorrect target triple '' (did you use emcc/em++ on all source files and not clang directly?)

(Btw, that last warning looks like a bogus error message after first error has already occurred and the output file doesn't exist.)

**Comment by kripken** [comment]
Possibly fixed in that pull to fastcomp. This testcase emits the same in -O0 an -O2 but we should probably have a better testcase for that bitcast.

**Comment by juj** [comment]
When compiling Bullet with SSE2 enabled, I am seeing a 4xf32 getting casted to i128:

    Unsupported:   %41 = bitcast <4 x float> %35 to i128
    LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
    warning: incorrect target triple '' (did you use emcc/em++ on all source files and not clang directly?)

so it looks like the bitcast needs to be flexible on the float vs int case here?

**Comment by kripken** [comment]
How can I test that to see the error? I couldn't find how to build bullet with sse2.

**Comment by juj** [comment]
I am currently testing with the Urho3D engine, STR:

	git clone https://github.com/juj/Urho3D.git
	cd Urho3D
        git checkout emunittest_sse2
	mkdir build_emscripten
	./cmake_emscripten.sh build_emscripten -DURHO3D_SAMPLES=1 -DCMAKE_BUILD_TYPE=Release -DURHO3D_SSE=1
	cd build_emscripten
	make 12_PhysicsStressTest VERBOSE=1

and verify in the prints that `-msse2` is being passed in the compile and link flags.

**Comment by kripken** [comment]
Added support for this bitcast in that pull. But it will be slow, since it needs to bitcast float to int :(

**Comment by juj** [comment]
I wonder if it would be possible to make the NaCl ExpandIntegers ignore `i128` type altogether, and we would treat it as if Emscripten had native support for it via the `SIMD.Int32x4` type? We could use that as a value type to support loads, stores and in-memory moves of `i128`s? Bit-discarding casts to `i32` should also be easy to do, although I'm not sure how to do bit-discarding casts to `i64`, that would probably need to somehow integrate with the NaCl ExpandIntegers code?

**Comment by juj** [comment]
As a sidenote, did a debug build of Urho3D physics with SSE2 enabled, and it's extremely slow and there's 140MB of JS code, but looks like the physics works correctly, so it feels that the LLVM optimizer doing bad things is the last remaining issue here (and hoping that asm.js validation will be ok)

**Comment by kripken** [comment]
Fixed on incoming.

**Comment by svenstaro** [comment]
This is the case again now with 1.38.15/1.38.19, perhaps reopen?

[log.txt](https://github.com/kripken/emscripten/files/2603033/log.txt)

**Comment by kripken** [comment]
@svenstaro reopening, and a PR would be welcome, but I think this is low priority as at this point most developer effort is on emscripten with the LLVM wasm backend (which uses LLVM legalization and avoids such issues).

**Comment by svenstaro** [comment]
Honestly, no idea how to approach this since I got zero knowledge of llvm internals. I'll post this to appropriate places in rust and maybe some knowledgeable can take a look.
