### ISSUE TITLE
Firefox error "not well-formed" when optimizing out Math.fround calls.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3792]
STR:
1. `em++ tests/hello_world.cpp -o a.html -s PRECISE_F32=2 -O1`
2. Edit `a.html` and change `if (!(!Math.fround)) {`to `if (false)` to force Firefox also to go down the path of optimizing out `Math.fround` (even though it does support it).
3. Run the page a.html.

Observed: The page prints an error "not well-formed a.js:1:1". Everything seems to run ok though.

Expected: Optimizing out `Math.fround` should be safe in Firefox as well and no error should be issued. Filed a separate bug https://bugzilla.mozilla.org/show_bug.cgi?id=1206403 to ask for a better error message of what is actually not well-formed here.

**Comment by kripken** [comment]
I only see the error when using a file URL, when using a proper webserver it goes away. If you see the same, this is probably a firefox bug with file URLs.

**Comment by juj** [comment]
That looks true - I can confirm that I do only see it with `file://`. Though let's keep this open until the Firefox side issue is resolved.

**Comment by juj** [comment]
Sometimes instead of "not well-formed", the message can instead be "syntax error". Updated the above bugzilla entry for a test case that shows the second error message instead.
