### ISSUE TITLE
emcc should read from stdin when no input files given

### ISSUE THREAD

**Issue by smehrbrodt** [emscripten-core/emscripten#3800]
The following command works with clang: 
`echo "__clang_major__.__clang_minor__.__clang_patchlevel__" | clang -E -P -`

If you try the same with emcc: 
`echo "__clang_major__.__clang_minor__.__clang_patchlevel__" | emcc -E -P -`
you get an error: `ERROR    root: no input files`

emcc should read from stdin when no input files are given.

**Comment by kripken** [comment]
#3552 also talks about this. But it has a mix of other things so let's keep this open too.

**Comment by smehrbrodt** [comment]
Is someone already working on this or could I go ahead and create a pull request?

**Comment by kripken** [comment]
No one that I know, feel free to work on it.

**Comment by smehrbrodt** [comment]
Might use something like https://docs.python.org/2/library/fileinput.html
Will see if I can get this working.

**Comment by workless** [comment]
can't you just use /dev/stdin as a workaround?

**Comment by pimlu** [comment]
`/dev/stdin` would work on Linux and OSX, but not on Windows, unfortunately.

**Comment by smehrbrodt** [comment]
> can't you just use /dev/stdin as a workaround?

I tried to replace `emcc -E -P -` with `emcc -E -P /dev/stdin`. Unfortunately, this hit another bug (#3845)
