### ISSUE TITLE
Reduce build size

### ISSUE THREAD

**Issue by VinnyVicious** [emscripten-core/emscripten#3815]
I'm trying to reduce the binary filesize for a few projects i'm using Emscripten. I'm much more comfortable writing C++ code than using pure Javascript, and that's the reason i'm not using Babylon.js or other JS-based engines. However, using Emscripten comes with the downside of huge binaries and slow startup. 

My `.js` files usually have 4~5 MB. But what really bothers me is the `.mem` files, which can be up to 50 MB! Are there any special techniques for reducing the build size and improving overall performance?

**Comment by kripken** [comment]
The `.mem` file is the static data in your application. Perhaps your app has some large zero-initialized data structures in the global scope? If so, that would explain the size, but it would also mean that the file would gzip extremely well, so nothing to worry about.
