### ISSUE TITLE
Websockets example

### ISSUE THREAD

**Issue by VinnyVicious** [emscripten-core/emscripten#3817]
We could benefit a lot from a simple example, like a chat program in C, showcasing how sockets work in Emscripten.

**Comment by kripken** [comment]
See the test suite, `tests/test_sockets.py` has a bunch of socket-using examples.

**Comment by juj** [comment]
Emscripten emulates the BSD sockets API, with WebSockets being utilized as the underlying backend. The emulation is not perfect, so see the tests for which code patterns currently are expected to work.
