### ISSUE TITLE
Clarify Environments in shell.js

### ISSUE THREAD

**Issue by rodneyrehm** [emscripten-core/emscripten#3821]
I've stumbled across this because of medialize/sass.js#36.

It looks as if the emscripten runtime identifies `WEB`, `NODE`, `WORKER`, `PTHREAD` (??), `SHELL` (??) as execution environments. Apparently people like to use emscripted projects in Java using [Rhino](https://en.wikipedia.org/wiki/Rhino_%28JavaScript_engine%29) or [Nashorn](https://en.wikipedia.org/wiki/Nashorn_%28JavaScript_engine%29), because that prevents them from having to deal with JNI (or so I assume, I'm not a Java developer). Also there are a [few more JS engines](https://en.wikipedia.org/wiki/List_of_ECMAScript_engines) - most of which I've never heard before.

sass.js is failing on Rhino either because of #2601 or because Rhino was identified as `SHELL` and then fails because of the missing [global print](https://github.com/kripken/emscripten/blob/master/src/shell.js#L108). I have no idea what `SHELL` is supposed to be and I don't know if Rhino should be considered `NODE` or not.
- is it possible to extract / refactor the environment stuff to make it clear to
  - make it clear what part of the environment is actually required
  - it becomes "easily" exensible for "niche" runtimes
- should compilation accept a flag to specify the target environment (node doesn't need the web stuff and vice versa) for optional optimization
- are there any tests for the envirnments so that we (the victims of "niche" environments) could start looking at what actually needs to be done?

**Comment by juj** [comment]
The comment https://github.com/kripken/emscripten/issues/2601#issuecomment-58218226 implies that Rhino would not have typed array support? That is required for Emscripten, and it's not possible to run without. Historically Emscripten did support compilation targeting non-typed arrays, but it was slow and brittle. Emscripten 1.23.1 deprecated the support for non-typed arrays, see https://github.com/kripken/emscripten/blob/master/ChangeLog.markdown#v1231-8262014. 

`ENVIRONMENT_IS_SHELL` currently means that not running in a browser and not running in Node.js. Rhino should not be considered Node.js unless it is a Node.js derivative fork (which I don't think it is).

What is the functional equivalent of printing to standard output or a "console" or similar in Rhino? Try changing the line https://github.com/kripken/emscripten/blob/master/src/shell.js#L108 to something like

    if (!Module['print']) {
        if (typeof print != 'undefined')  Module['print'] = print;
        else if (/*feature-detect Rhino print*/) Module['print'] = rhinoSpecificPrint;
        else Module['print'] = function(){}
    }

If Rhino is capable of running `.js` files from the command line, then you can edit your `~/.emscripten` configuration file, which should have lines like this:

    NODE_JS='C:/code/emsdk/node/4.1.1_64bit/node'
    JS_ENGINES = [NODE_JS]

There you can replace Rhino as a JS engine. After that change, tests will be run in that engine when you run `python tests/runner.py`. Set the environment variables `EMCC_DEBUG=1` and/or `EM_BUILD_VERBOSE=3` to verify that the test runner is picking up the correct command line to spawn.

There is not much that the environment bootstrap code does. `ENVIRONMENT_IS_WORKER` and `ENVIRONMENT_IS_PTHREAD` are internal Emscripten things to differentiate main thread from spawned threads (and what is called a `--proxy-to-worker` thread), and not actually something that the user would ever control by choice of software. That leaves `ENVIRONMENT_IS_WEB`, `ENVIRONMENT_IS_NODE` and `ENVIRONMENT_IS_SHELL` as the only ones that are dictated by what program user is running in.

The distinction between these three does not do much, and only the following things define the environment:

    Module['print']: A function that prints to standard output or info log channel or similar. Must exist.
    Module['printErr']: A function that prints to standard error or error log channel. Must exist.
    Module['read'](filename): A function that synchronously reads a text file from local filesystem and returns it as a string. If this does not apply, the function can throw.
    Module['readBinary'](filename): A function that synchronously reads a binary file from local filesystem and returns it as a typed array. If this does not apply, the function can throw, but in that case, one must build with `--memory-init-file 0`.

**Comment by rodneyrehm** [comment]
wow, thank you for the explanation!

> The comment #2601 (comment) implies that Rhino would not have typed array support?

it seems they were only just introduced with [version 1.7.6](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_6_RELEASE) in April.

> What is the functional equivalent of printing to standard output or a "console" or similar in Rhino?

apparently it's `java.lang.System.out.println('some string');`

> `ENVIRONMENT_IS_SHELL` currently means that not running in a browser and not running in Node.js.

So I guess it's fine for Rhino to identify as `ENVIRONMENT_IS_SHELL` then…

> The distinction between these three does not do much, and only the following things define the environment: […]

so all we'd have to do is to provide the proper Rhino-compatible implementations for `print`, `printErr`, `read` and `readBinary`?

**Comment by juj** [comment]
Yes, that sounds right. Like mentioned, `read` and `readBinary` can be omitted, since the codepaths that use them should not be critical, and avoided by using the `--memory-init-file 0` linker flag. Naturally of course if they are easy to implement, then why not.

**Comment by rodneyrehm** [comment]
> […] and avoided by using the `--memory-init-file 0` linker flag

which can't be used together with emterpreter (unless that has changed in the last 6 months).

> Naturally of course if they are easy to implement, then why not.

I'll pass the hints along to the Java developer trying to get sass.js running on Rhino, we'll see if we can make it work (and submit a PR to emscripten afterwards). Thanks!

**Comment by kripken** [comment]
Emterpreter is now compatible with mem init file. Was refactored a few
months back.

**Comment by rodneyrehm** [comment]
thank you guys! closing this for now… :)

**Comment by rodneyrehm** [comment]
Regarding typed arrays support and little- vs big-endianess in Rhino see mozilla/rhino#265
