### ISSUE TITLE
browser.test_html_source_map issues

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3827]
Not sure how I haven't seen this before, but looking at `browser.test_html_source_map`, there is a problem that it will fail on OS X. The test calls `webbrowser.open_new('file://' + html_file)` to run the compiled file, however, that is not safe on OS X, because spawning the browser will not work because of Firefox profile manager will not allow opening a new Firefox instance to the existing profile (`webbrowser.open_new` can only be called once). To fix this, one needs to run the test in another Firefox profile. Is it important that the test uses `file://` URI? Could the test use `btest` instead? If not, then I think the test should use `emrun` to spawn the page, which can correctly work around the Firefox profile issue.

Also, the test does not seem to actually test anything, but it is an interactive test. Should we move that test to the `interactive` suite instead?

**Comment by kripken** [comment]
Agreed to all. Should move to `interactive`, and should use `btest`. The interactive instructions should say what is in the comment about "manually bisecting" at the end of the test code in `test_browser.py`.
