### ISSUE TITLE
'webkitMovementX' is deprecated. Please use 'movementX' instead.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3834]
Chrome is vocal about that pages should no longer use `webkitMovementX`. We refer to that in a few places in `src/library_browser.js` and `src/library_html5.js`. I could not find with a quick search when Chrome added support for `movementX`, I wonder if that's ancient enough that we could remove `webkitMovementX` support?

There's also `mozMovementX`, but Firefox doesn't complain about using it yet at least.

**Comment by kripken** [comment]
If stable chrome has `movementX`, and if we don't need `webkitMovementX` for WebKit/Safari, then I'm ok with removing it.

**Comment by kripken** [comment]
Sadly, I think we need to keep supporting movementX/Y because of Safari, which still lacks it, https://caniuse.com/#search=movementx
