### ISSUE TITLE
Add debug build mode that checks integer division and modulus by zero.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#3836]
This came up more than a year ago, and now I was reminded by it again. Rather low priority, but marking down to make a note of this.

In Emscripten code integer `x / 0` and `x % 0` both silently return `0`. In native Windows, it generates a SEH exception that can be caught, and in native POSIX, it generates the `SIGFPE` signal that can be trapped. We don't really support any of that, and the C spec says integer divide by zero is UDB. Still, it might be nice to have a debug flag we could enable, `-s TEST_SIGFPE=1` perhaps? or `-s ABORT_ON_INT_DIV0=1` or similar, which would emit checks before all integer division and modulus operations and call `abort()` if division/modulus by zero is attempted. This might help some developers catch bugs they didn't know they had.

**Comment by kripken** [comment]
Another option is to use ubsan which would catch other stuff too. I made progress on this a while ago, but there were still a bunch of instrinsics that needed implementing. Might not be a lot more though.
