### ISSUE TITLE
pauseWebAudio failed: TypeError: Not enough arguments on Safari

### ISSUE THREAD

**Issue by Dimitory** [emscripten-core/emscripten#3861]
When before music was started before via Mix_PlayMusic, the next call this method returns exceprion.
`pauseWebAudio failed: TypeError: Not enough arguments`
And so previus and new music continues to play together.

Workaround for this bug:
`calling Mix_HaltMusic before Mix_PlayMusic`

**Comment by kripken** [comment]
Thanks for reporting this. It would be good to fix it properly: In a non-minified build, do you see which line is failing? That should tell us which specific WebAudio method is not working ok in Safari.

**Comment by Dimitory** [comment]
Oh, sorry, Ive forgot it.
```
pauseWebAudio: function(audio) {
      if (!audio) return;
      if (audio.webAudioNode) {
        try {
          // Remember where we left off, so that if/when we resume, we can restart the playback at a proper place.
          audio.currentPosition = (SDL.audioContext['currentTime'] - audio.startTime) % audio.resource.webAudio.decodedBuffer.duration;
          // Important: When we reach here, the audio playback is stopped by the user. But when calling .stop() below, the Web Audio
          // graph will send the onended signal, but we don't want to process that, since pausing should not clear/destroy the audio
          // channel.
          audio.webAudioNode['onended'] = undefined;
          audio.webAudioNode.stop();						<= exception gained there
          audio.webAudioNode = undefined;
        } catch(e) {
          Module.printErr('pauseWebAudio failed: ' + e);
        }
      }
      audio.paused = true;
    },
```


As I understood, `stop()` method should be replaced to `stop(0/*currentTime*/);` or ` pause(); currentTime = 0;`

**Comment by kripken** [comment]
Thanks!

Ok, this looks like a WebKit bug, since that is [an optional parameter](https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/specification.html#AudioBufferSourceNode-section). Do you want to file a bug for them?

Meanwhile I'll add the `0` parameter as a workaround.
