### ISSUE TITLE
emcmake breaks in the face of cmake versioning

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#3866]
I have a project using cmake that uses cmake's versioning support.

This breaks doing a build for emscripten due to the output file name not ending in `.js` and so the output file ends up just being bitcode:

```
[1/2] : && /Users/bruce/Development/emscripten/emcc  -fcolor-diagnostics  -Wall ... -o bin/mindycomp.js-2.7.0   && :
[2/2] /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_symlink_executable bin/mindycomp.js-2.7.0 bin/mindycomp.js && :
```

This happens when I do:

```
PYTHON=`which python` emcmake cmake -G Ninja ..
```

The same thing happens with the `Unix Makefiles` as well, just takes longer due to using `make`.

**Comment by waywardmonkeys** [comment]
cc: @juj

**Comment by waywardmonkeys** [comment]
FWIW, the version is set in ``CMakeLists.txt`` in the usual way:

```
SET_TARGET_PROPERTIES(mindycomp PROPERTIES VERSION ${MINDY_VERSION})
```

**Comment by juj** [comment]
The versioning suffix is implemented somewhere in the depths of CMake binary and not set in a custom manner.

In native code, if one specifices a version, say, `2.7.0.0`, the (CMake? POSIX?) versioning convention for is to generate e.g. for shared libraries a tower of `mindycomp.so`, `mindycomp.so.2`, `mindycomp.so.2.7`, `mindycomp.so.2.7.0` and `mindycomp.so.2.7.0.0`, which are all symlinks `mindycomp.so` -> `mindycomp.so.2` -> `mindycomp.so.2.7` -> `mindycomp.so.2.7.0` -> `mindycomp.so.2.7.0.0`. I believe for executables it is the same. Most likely CMake does not have any kind of method to specify the version numbers before the suffix, i.e. it is never `mindycomp.2.7.0.so`. I wonder if we even would like to switch the ordering here(?)

(Btw, @waywardmonkeys , in Emscripten CMake, one can use `if (EMSCRIPTEN)` to directly detect the Emscripten compiler, similar to how it has `if (MSVC)` and `if (APPLE)` and `if (UNIX)` and so on, though the longer form is good as well.)

Perhaps we should make Emscripten detect and treat all output files `x.js.<digits>.<digits>.<digits>.<digits>` as being output type of JavaScript? Though I'm not sure if some project might then add 'alpha' or 'beta' or similar letter or word suffixes, they could have `x.so.1.2.0beta' or something equivalent, which would not be detected. On the other hand, during internal compile steps in Emscripten we do generate bitcode files of form `x.o.js.o.bc` and so on, so autodetecting the output type needs to be careful. Perhaps we should find the last `*.something.*` where we recognize what the `something` part is, and detect based on that.

Or another way might be to introduce a new `--output-type-is=llvm_bitcode`/`--output-type-is=js_executable`/`--output-type-is=html_file` linker flag to explicitly say what kind of output to target(with a less verbose name for the linker flag of course), similar to how `-x c`/`-x c++` enforces how to treat an input file by autodetecting from a suffix. Perhaps GCC/Clang already might have a linker flag with such a meaning? CC @kripken.
