### ISSUE TITLE
Build on Visual Studio 2015

### ISSUE THREAD

**Issue by cchara11** [emscripten-core/emscripten#3878]
Is it possible to build the solution to Visual Studio 2015?
I tried to build it using Emscripten as the platform target but i get an error about GCCCompile.

**Comment by juj** [comment]
Do you mean using VS2015+vs-tool to build your own code project for Emscripten? Or using VS2015 to build the Emscripten LLVM/Clang compiler?

Neither of these are currently supported. Vs-tool was an experimental project, only developed for VS2010, and it's not currently maintained anymore. VS2015 build for LLVM/Clang is not yet supported, but it is on the roadmap to be added to emsdk.

**Comment by cchara11** [comment]
Well i meant the first one, to use VS2015 and vs-tool to build a project for Emscripten. But ok if it's not supported i can't proceed with my project. Thanks

**Comment by crosire** [comment]
Leaving this here in case somebody wants to build a VS2015 project with Emscripten and comes across this topic: I wrote an Emscripten MSBuild platform toolset for VS2015 a while back and started using it it frequently recently hence I thought somebody else might find it useful.

It uses a similar approach to vs-tool but is modeled more closely after Microsoft's MSBuild scripts. Supports changing Clang compiler and Emscripten linker options in the VS property pages, different targets (LLVM bitcode library, JavaScript or HTML + JavaScript) and debugging the JavaScript code Emscripten outputs within Visual Studio. Works well with larger codebases and multiple projects that are linked together aswell.

Anyway, here it is: https://github.com/crosire/vs-toolsets.

**Comment by holland01** [comment]
@crosire Thanks, fam. I was literally in the process of translating a unix Makefile into something compatible with nmake, and then I found this. You da real MVP.
