### ISSUE TITLE
ALLOW_MEMORY_GROWTH doesn't play well with SIDE_MODULEs

### ISSUE THREAD

**Issue by hgy29** [emscripten-core/emscripten#3893]
Hi,

It looks like side modules (dynamically linked) memory buffer isn't updated when a memory growth occurs. HEAPxx variables in the side module context do not match those in the main module anymore, which means a lot of trouble when trying to exchange data between the side module and the main module.

**Comment by kripken** [comment]
Yes, this can't work currently. I'll add a proper compile-time error.

I think we could get it to run, if we called the asm modules of the side modules to update their views, using `emscripten_replace_memory`. Should not be too hard to try that, but I'm not sure it's enough.
