### ISSUE TITLE
Multiple libraries with multiple file system instances

### ISSUE THREAD

**Issue by keent** [emscripten-core/emscripten#3901]
I'm including multiple libraries for a project and in the 2nd library I use the _--embed_ parameter but  I cannot access the supposedly mounted directories in the 2nd library via 
1. 

```
var secondlibraryinstance = window.secondModule()
secondlibraryinstance.FS // there are no FS functions here aside from the legacy?
```

AND
1. 

```
FS.stat() calls
// this seem to access only the first library's file system

```

Can anyone please tell me how would I include multiple libraries and access the File system's of those?

**Comment by kripken** [comment]
Each compiled program of library has its own FS object, and FS.root is the filesystem data in it. They are not shared by default, and I'm not sure if they easily can be. It might be possible though to just make them share FS or FS.root, and that could work, but I'm not sure.

Another option is to build libraries as [side modules](https://github.com/kripken/emscripten/wiki/Linking), and load them in the main module. Those definitely share all the global stuff like the filesystem.

**Comment by keent** [comment]
@kripken thanks, Anyway I can help copy/move those docs to the user docs from the dev docs? I think the concept of main modules with side modules anything about multiplicity would be useful to the common user.

**Comment by kripken** [comment]
Sure, help with those docs would be great. The feature is pretty stable now so it makes sense to do so.
