### ISSUE TITLE
scanf doesn't work

### ISSUE THREAD

**Issue by artemskikh** [emscripten-core/emscripten#3904]
simple c code with scanf gets translated into js incorrectly, for example the following code never prints anything:
# include < stdio.h >

int main() 
{
  int n = 0;
  do
  {
     scanf("%d", &n);
     printf("%d", n);
  }
  while (n != 0);
  return 0;
}

**Comment by kripken** [comment]
You need to define a stdin stream. You can use `emcc --pre-js` with something like this in the file:

````
var Module = {
  stdin: function() {
    return '5';
  }
};
````

That always returns `5`. Return null for eof.
