### ISSUE TITLE
calling stub instead signal and unresolved symbol

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#3914]
calling stub instead signal and unresolved symbol (emscripten 1.35.0 )

first issue :

Emscripten at execution time, send me message
to use : stub function instead signal or raise;

in the example below i've used stub function
without success

can you show me other way to use signal or raise ?

Emscrinten console.log 

```
pre-main prep time: 7 ms
main.js:139 Calling stub instead of signal()
main.js:139 Calling stub instead of raise()
main.js:139 raise() returning an error as we do not support it
main.js:136 signaled is 0.
```

second issue : 

compiler can't found these function
but i think you have also reply me in other post
regarding swap musl c++ lib

```
quick_exit() ;      // warning  unresolved symbol
at_quick_exit() ;   // warning  unresolved symbol
_Exit () ;          // warning  unresolved symbol
```

source code example :

```
#include <stdio.h>       
#include <signal.h>      

sig_atomic_t signaled = 0;

void mySTUB (int param)
{
  //signaled = 1;
}

int main ()
{
  void (*prev_handler)(int);

  prev_handler = signal (SIGINT, mySTUB );

  /* ... */
  raise(SIGINT);
  /* ... */

  printf ("signaled is %d.\n",signaled);


  return 0;
}
```

regards

**Comment by kripken** [comment]
JavaScript doesn't provide enough for us to properly support OS-level signals. Perhaps on node we could though? In general, however, our main focus is on the web, where we can't.

**Comment by claudiodaffra** [comment]
i have resolved oveload method
as you can see, in this example

	#include <signal.h>
	#include <stdio.h>
	 
	static void (*pf[100])(void) ; 
			
	void signal ( int sig, void (*func)(void) )
	{
		pf[sig] = func ;
	}
	int raise ( int s  )
	{
		(*pf[s])() ;
		return 0 ;
	}

	void f1 ( void )
	{
		puts ( "f1");
	}
	void f2 ( void )
	{
		puts ( "f2");
	}

	int main()
	{
		 signal ( SIGABRT , f1 ) ;
		 signal ( SIGINT , f2 ) ;
		
		 raise	( SIGINT  ) ;
		
	   return(0);
	}

 ciao Kripken

**Comment by juj** [comment]
Looks like in singlethreaded execution that doesn't care about threads, we could support signals like used in the above example. These would be in https://github.com/kripken/emscripten/blob/master/src/library_signals.js .

In multithreaded execution we can't support real signals (except SIGKILL), but the current multithreaded execution does have a small amount of emulation for signals - it would be possible to emulate more if someone wants to take on that project.

**Comment by claudiodaffra** [comment]
are you saying to emulate a small amount of  signal.h posix lib ?

**Comment by juj** [comment]
Yes, the way you emulated the signal api in the above code, you could place the emulation code in `src/library_signals.js` in order to support the emulation for singlethreaded code in other codebases as well.

When building multithreaded applications, we probably won't include `src/library_signals.js` in it, or gate in some way to distinguish between singlethreaded and multithreaded builds, since their implementation would be different.

**Comment by claudiodaffra** [comment]
ok i played for a while and i have changed emscripten code
in library_signals.js

this is new signal function :

	  signal: function(sig, func) 
	  {

		if (sig == 14 /*SIGALRM*/) {
		  __sigalrm_handler = func;
		} 
		Module['pf'] = [] ;
		Module['pf']['sig'] = func ;

		return 0;
	  },
	  
and the this is new raise function :

	raise: function(sig) 
	{
	  var ff = Module['pf']['sig'] ;

	  Runtime.dynCall('vi', ff, [0])
	  
	  ___setErrNo(ERRNO_CODES.ENOSYS);

	return 0;
	},
	  
may be in this days, i'm try to fix other
but i'm working a lot and i have 
finish my marshmallow

regards
claudio

**Comment by claudiodaffra** [comment]
i've send you a pull request

**Comment by claudiodaffra** [comment]
hi juj

i need to ask you a question about : Runtime.dynCall ( ... )
if i've understood about this line of code in library_signals.js :

Runtime.dynCall('vi', __sigalrm_handler, [0]);

	alarm: function(seconds) 
	{
		setTimeout(function() {
		  if (__sigalrm_handler) Runtime.dynCall('vi', __sigalrm_handler, [0]);
		}, seconds*1000);
	},
	

first parameter		:	type signature
second parameter	:	pointer 
third parameter	:	:	array argument
	
	
	vi : return void , receive , integer
	
so 
	vv : void return and void parameter ;
	vf	: void return float parameter
	ififi ... : integer return and float,integer,float ,integer ...
	
and so on 

is that right ?

where can i find a detailed explanation ?

**Comment by kripken** [comment]
Yes, that's correct.

And there aren't really docs for that, I'm afraid, but you can look in the code (simplest to just look in the output from the compiler).
