### ISSUE TITLE
warning: unresolved symbol: Mix_RegisterEffect

### ISSUE THREAD

**Issue by MikeDX** [emscripten-core/emscripten#3924]
I'm having issues using a custom callback for sdl_mixer after initialising the channels (normal sounds play as they should)

Is this just a known bug? Any workaround possible?

**Comment by juj** [comment]
Is this for SDL 1 or SDL 2? (they have separate codebases) For SDL 1, this is probably something that hasn't been implemented, but SDL 2 is built from source, so for that it could be something else.

**Comment by MikeDX** [comment]
This is SDL1. I was under the impression SDL2 sound wasnt working yet.

**Comment by MikeDX** [comment]
Tested with SDL2, same problem although linker does not complain of missing function

**Comment by juj** [comment]
This is probably something we don't currently implement at all. If you have a small test case that should work that you can post, perhaps someone might be able to pick this up. I worked on the SDL1 raw audio queueing, so might be able to give this a look at some point, but no promises.

**Comment by MikeDX** [comment]
Hi Juj

I've created a small program which you can test, it compiles with gcc and operates correctly (fills buffer with static), whilst compiling with emscripten gives the original sample and complains about unresolved symbol: Mix_RegisterEffect (so the callback is never called)

[test.zip](https://github.com/kripken/emscripten/files/311942/test.zip)

Hope this helps with implementing the function, it would be incredibly useful for me to have it for sound manipulation (not just generating static)

**Comment by originalsouth** [comment]
Same problem with `Mix_SetMusicCMD`.
