### ISSUE TITLE
Handling Audio with PTHREADS, SDLAudioCallback not behaving like a thread.

### ISSUE THREAD

**Issue by alexandrelessard** [emscripten-core/emscripten#3925]
I switched to Emscripten 1.35.0 to start taking advantage of PTHREADS in our Audio Engine.
(with Firefox Nightly)

I successfully use the new threading system with only minors changes in my code base. I am now using threads to load asynchronously Audio Data while rendering, this is great, good job guys.

But I stumbled on one thing I did not find a viable workaround at this time.

This system normally works (with exact same source code) with a system with threads, where the SDLAudioCallback can pop in anytime, regularly, as an external thread call.

But it seems that the SDLAudioCallback will never happen if one of my thread (the main loop in fact) is waiting on an event that will be triggered by the SDLAudioCallback. 
(*Take note that the main loop does not directly wait on the SDLAudioCallback for audio processing but instead ends up having to wait after a cycle of threads that end up waiting for the next callback to free resources and go forward.)

This might be a limitation of the system, I believe this could be because the SDLAudioCallback  is not a real thread call and is a simulated call that can come only in between two main loop run, (but in fact i don't know I am just guessing)

Questions:
- Are my assumptions right to believe SDLAudioCallback is not a real thread call as the other ones and will never happen but in between two main_loop loop?
- (only if I am right about my assumptions) Is there any way to receive the SDLAudioCallback as if it was another thread?

I believe I could possibly work around this issue by making my main loop to be a separate thread, but i am getting a bit afraid of adding more threads as it seems that the limit number of simultaneous threads is quickly reached. I am up to 4 threads at the moment (which is an already reduced subset  of what we normally use on this system).

Note:
I am compiling with -s PTHREAD_POOL_SIZE=4
And if I make it -s PTHREAD_POOL_SIZE=6, i apparently get a significant increase in load time even if i don't really use the additional threads, I don't have details/metrics about this issue.
And if I try:
-s PTHREAD_POOL_SIZE=16
The page will never get passed the message: "Preallocating 16 workers for a pthread spawn pool." My computer freezes completely and the only option is to cold shut down my Computer.

-Alex

**Comment by juj** [comment]
Your hunch is correct. The SDL audio callback runs on the main thread in between main event loop ticks, and not in a separate thread. Technically it might be very difficult to make it run in a separate thread, because we do have a current limitation that Web Audio API (and hence SDL) is only available in the main thread.

Regarding the second issue, can you check the web console during load time? Nightly currently has a bug that each pthread in the pool will independently compile the asm.js module on the first run, but on the second page load after the asm.js module has been compiled and cached, each thread should load up quickly. This is something that we are naturally looking to fix before the feature ships.

**Comment by alexandrelessard** [comment]
I finally found out a workaround, but it was not as simple as expected.

My main loop was previously handling Game logic and drawing.
I wanted to offload all to a separate thread to make sure the Main_Loop would always be free, i would only make it pop a wake up signal and return... But I faced a problem where i cannot Draw SDL2 from any thread that is not the Main_Loop.

Now my main loop goes like:

```c++
static void main_loop()
{
	// I run into issues as the main loop can not be considered as a normal thread as SDL callbacks run in this thread too.
	// What that means is that the main loop is not allowed to use the pthread synchronisation features.
	if (!bIsMainLoopThreadStarted)
	{
		g_pUpdateDemoMgr = new UpdateDemoMgr();
		if (g_pUpdateDemoMgr)
			g_pUpdateDemoMgr->Init(); //Starting the thread inside Init()

		bIsMainLoopThreadStarted = true;
	}

	if (g_pUpdateDemoMgr)
		g_pUpdateDemoMgr->SignalUpdate();

	IntegrationDemo::Instance().Render();// Try to make the main loop to call Render and let the other thread call Update. //TEchnically unsafe threadwise , but lets try it....
}
```

I wanted to offload the UI rendering part "Render()" to the new thread as well, but I was inexplicably receiving.

"TypeError: GLctx is undefined"

errors when trying to draw from any thread that was not the main Loop.
(i searched and found this old report: https://github.com/emscripten-ports/SDL2/issues/11)
But I cannot see

**Comment by alexandrelessard** [comment]
I want to highlight that I still get a Computer Complete crash if I run with an application that was compiled with:
-s PTHREAD_POOL_SIZE=16

I understand i would normally get 
<Successfully compiled asm.js code>
And it does increase the load time and this is a known issue,

, but if i specify 16 threads, it crashes before being able to
