### ISSUE TITLE
Emcc is not responding

### ISSUE THREAD

**Issue by K-Adam** [emscripten-core/emscripten#3941]
I've used emscripten many times. It worked well. But today it stopped working. I haven't changed anything in the emscripten settings. I've just compiled some projects. Now even the most basic hello word program cannot be compiled.

When emscripten starts, it prints out the warnings and notices (if there were any), but after that, nothing happens.

Now I tried to compile the "hello word" program in verbose mode, to find out what is wrong. Here is the result:

![emcc_freeze](https://cloud.githubusercontent.com/assets/9156245/11449205/f77eab2c-956c-11e5-96f4-63f7701ab8fb.png)

Beyond this point, nothing happens.

**Comment by deadmanswitch** [comment]
The `.o` object files are generated in the `temp_dir`. Something goes wrong after that

**Comment by juj** [comment]
This looks peculiar indeed. Does the issue still persist or did you resolve it some way?

Could you try installing `emsdk install sdk-incoming-64bit` or `emsdk install sdk-master-64bit` to see if those help any? Also, you can try setting the following environment variables before the call:

    set EMCC_DEBUG=1
    set EM_BUILD_VERBOSE=3

which will cause more verbose printing to be passed to the compiler.
