### ISSUE TITLE
Speed up build time?

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#3953]
We'd like to speed up our build time and I was wondering if there are any easy wins. For example, the "calculate system libraries" step takes a good chunk of time (4 seconds). Is it possible to just provide the system libraries on the command line? It also looks like the closure step is significant (10 seconds). Is there a way to speed up that invocation using something like [Nailgun](http://www.martiansoftware.com/nailgun/) to keep the JVM running? Are there any efforts that you know of to set up something like incremental linking for emscripten? I'm assuming all of this will get much better after WebAssembly lands but I'm wondering if there are things we can do until then.

**Comment by kripken** [comment]
* You can force all system libs to be included using `EMCC_FORCE_STDLIBS=1 EMCC_ONLY_FORCED_STDLIBS=1` in the env. However, that system libs calculation takes so long is likely due to it encountering many small files in this command, either because you provide many separately, or if many arrive from .o files inside a .a. It's more efficient to create a hierarchy, linking .os into bigger .bc files (and linking only when something changes, etc.).

* Closure compiler is simply slow. I'm not familiar with nailgun, but if it just helps startup, I don't think that would help much.

* If you want fast builds during development, then we do support [shared libraries](https://github.com/kripken/emscripten/wiki/Linking).

* The WebAssembly backend in LLVM should eventually help here, yes.

**Comment by evanw** [comment]
My impression was that shared libraries didn't work with memory growth, which is essential for us: https://github.com/kripken/emscripten/issues/3893. I wonder if there's a way to avoid closure compiler entirely if only C++ code has changed.

**Comment by kripken** [comment]
Yes, shared libs don't work with memory growth. We could fix that with some work, but I'm not sure how much exactly.

Could fixed-size memory be good enough for iteration builds, though? I assume your personal machine has plenty of RAM to spare :)

**Comment by evanw** [comment]
Build time is still very frustrating for us so I started looking into this. I already found a quick win: #5025.

Much of the time spent appears to be in JS optimizations though which, ironically, don't appear to be optimized (i.e. they are written in JS instead of C++). Would you be open to a rewrite of the JS optimizations in C++ for speed? I'm guessing it could have a big impact on build time but wanted to check if it was a possibility first before investing any time in it.

**Comment by kripken** [comment]
We've actually done that rewrite, the JS optimization passes do run in C++ (code is under `tools/optimizer`). If you do see it run them in JS, it might be forced to fall back to that due to using a non-standard optimization or some other reason - it should say why in the logging from `EMCC_DEBUG=1` in the env, what do you see there? (in the lines around where it runs the js opts)

Btw, other plans for speedup here include replacing that C++ optimizer with the Binaryen optimizer, which is far faster. That's just for wasm though, but it's why wasm builds are faster already. More generally, further speedups in builds are also focused on wasm (e.g. optional separate compilation is planned).

#5025 looks nice, thanks (and I commented there).

**Comment by evanw** [comment]
Oh cool that's great news! Sorry about that, I misunderstood what was going on. The file `tools/js-optimizer.js` was being run so I assumed it was doing JavaScript-based optimizations, but the log also says `js optimizer using native` so I guess it is also using the C++ optimizer after all. I'm not familiar with emscripten's internals but it appears that `tools/js-optimizer.js` is running because we have `--emit-symbol-map` turned on. That seems to be run on a reduced version of the code though because it only takes ~300ms to run, so it's not performance sensitive. False alarm :)

I'd love to add a WebAssembly target to Figma but having to build everything twice is hard to swallow. I was considering building everything once instead and just shipping with the asm.js code that's generated in wasm mode but it didn't appear to be meant for production (it wasn't minified, for example). The [wiki](https://github.com/kripken/emscripten/wiki/WebAssembly) says combination builds like these "disable some optimizations ... so it's not a good idea in general" so it seems like it may just be for debugging the compiler. Is that true? I'm considering doing it anyway if the performance difference is negligible but I wouldn't want to use this as the foundation of our build system unless combination builds are going to be heavily tested and supported.

**Comment by kripken** [comment]
Right, we do a quick run of the js optimizer on the non-compiled code, to minify it. (The C++ version only supports asm.js so we can't use it for that.)

A single build for both asm.js and wasm is not recommended for the reasons in that link - it will be forced to make compromises for both asm.js and wasm. It will definitely reduce wasm speed by a noticeable amount - basically it disables wasm-specific features that can't be done in asm.js (like 64-bit integers, popcount/copysign/etc.). It may also be the case that the asm.js isn't minified, although that is fixable.

**Comment by dschuff** [comment]
More generally I would be curious to hear what the issues are for you with doing both an asm.js and a wasm build. We've generally been thinking that this will be the best option for most people and thinking about trying to make this use case easier. For example we want to ensure that both build types accept the same C/C++ source and that the emscripten JS glue supports the same APIs, so that ideally it's as easy as writing all the C and JS code just once, and then swapping in the asm.js or wasm module based on the browser. So if there are things that make this difficult we'd like to hear about it.

**Comment by aidanhs** [comment]
Not sure if you're on the emscripten mailing list, but if you're finding the C++ optimizer slow for your full project I'd be interested to hear if [ayzim](https://groups.google.com/d/msg/emscripten-discuss/pFTcf3lsL3M/W_pucD8MAwAJ) helps you out (I personally use it exclusively instead of the C++ optimizer). But it sounds like it might not be a big part of your build after all, in which case it's probably not worth messing with.

**Comment by evanw** [comment]
@kripken @dschuff: Our use of emscripten at Figma is probably different than most people; instead of just using it for ports every now and then, the web is our primary development platform so we actually build with emscripten all the time. The reason we care about the build time is that our iteration speed is often directly tied to build time, at least for problems that must be debugged in the browser. Build times are already pretty terrible compared to other web apps (web developers are used to build times in seconds, not minutes) so idea of doubling build times isn't appealing. We already have separate debug and release builds but some of the hardest-to-debug issues are in the release builds, so ideally debugging release builds shouldn't be too painful. I'm willing to compromise on missing out on 64-bit math (our code is written for asm.js and so doesn't use it much) and wasm-specific micro-optimizations (running at the current speed of asm.js is fine for now). I'll give it another shot with the latest release and see how it goes.

@aidanhs: I'll try looking more into our build performance and see if there's something I can do to speed it up.

**Comment by evanw** [comment]
This is still very much an issue for us. The emscripten compiler still has the slowest link times of any C++ compiler I've ever used. We're really looking forward to the 7x faster link times mentioned in https://v8.dev/blog/emscripten-llvm-wasm.

From what I understand we can't use it yet because the new wasm backend still isn't supported in a stable release of emscripten. However I think we can close this issue out since it's about the old backend which will be phased out at some point.

**Comment by kripken** [comment]
@evanw It is supported in stable releases currently :) Just use `latest-upstream` when installing/activating instead of `latest`. Then you should get that huge speedup in link times.

**Comment by sbc100** [comment]
@evanw can you confirm if using the wasm backend solves this issue for you?

I'll reopen for now.

**Comment by evanw** [comment]
Sorry, by stable I mean a version of the compiler that we can pin our code base to and make sure that all of our developers and CI machines are using the same version of the compiler. I assume `latest-upstream` means a continually moving target. We don't want to deal with bugs due to different compiler versions on different machines, which I'm especially concerned about given how new this code is.

Is there a stable build with a specific release number that supports the new wasm backend? Also, I've been following along regularly with https://github.com/emscripten-core/emscripten/projects/1 but it looks like there are still quite a few blocker bugs. I assumed that means it's not ready yet. Is that right?

I'm happy to try `latest-upstream` for us and give feedback if that's useful. I think last time I tried it there was still some issue with undefined `__cxa_` exception-related symbols.

**Comment by kripken** [comment]
@evanw You can also pin versions, any recent one has upstream support. For example the latest is `1.38.43-upstream` (like with `latest`, just add `-upstream`). Any version from `1.38.33` and later is ok.

The blocker bugs are enough that we don't want to switch the default. But we have many users that use the upstream backend already. If you aren't hit by those blockers, I'd recommend switching - they are very specific issues.

**Comment by sbc100** [comment]
Any feedback from switch to upstream would be great.   And if you notice the build times are better then we can at least close out this particular issue as being fastcomp only (and therefore most likely a wontfix).

**Comment by evanw** [comment]
Thanks so much for the tip! I didn't know you could add `-upstream` to a version. Just tried it out now. I get this when I try to build:

```
error: undefined symbol: __cxa_uncaught_exceptions
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
```

We're setting `-fno-exceptions` and `-s DISABLE_EXCEPTION_CATCHING=1` on the command line of all of our compiler invocations. And when I use `grep __cxa_uncaught_exceptions -r .` on our object file directory, it comes up blank. That's proof that the flags are working correctly and exceptions are disabled for us, right?

Doing it in the emscripten directory comes up with this:

```
grep __cxa_uncaught_exceptions -r .
Binary file ./.emscripten_cache/wasm-obj/libc++-noexcept.a matches
./upstream/emscripten/tests/other/metadce/hello_libcxx_O2.sent:__cxa_uncaught_exceptions
./upstream/emscripten/tests/other/metadce/hello_libcxx_fastcomp_O2.sent:___cxa_uncaught_exceptions
./upstream/emscripten/tests/other/metadce/hello_libcxx_fastcomp_O2_EMULATED_FUNCTION_POINTERS.sent:___cxa_uncaught_exceptions
./upstream/emscripten/tests/other/metadce/hello_world_fastcomp_O3_MAIN_MODULE.sent:___cxa_uncaught_exceptions
./upstream/emscripten/tests/other/metadce/hello_world_O3_MAIN_MODULE.sent:__cxa_uncaught_exceptions
./upstream/emscripten/system/lib/libcxx/support/runtime/exception_libcxxabi.ipp:    return __cxa_uncaught_exceptions();
./upstream/emscripten/system/lib/libcxxabi/include/cxxabi.h:extern _LIBCXXABI_FUNC_VIS unsigned int __cxa_uncaught_exceptions() throw();
./upstream/emscripten/system/lib/libcxxabi/src/cxa_exception.cpp:__cxa_uncaught_exception() throw() { return __cxa_uncaught_exceptions() != 0; }
./upstream/emscripten/system/lib/libcxxabi/src/cxa_exception.cpp:__cxa_uncaught_exceptions() throw()
./upstream/emscripten/system/lib/libcxxabi/src/cxa_noexception.cpp:__cxa_uncaught_exceptions() throw() { return 0; }
./upstream/emscripten/system/lib/libcxx.symbols:         U __cxa_uncaught_exceptions
./upstream/emscripten/src/library_exceptions.js:  __cxa_uncaught_exceptions__deps: ['_ZSt18uncaught_exceptionv'],
./upstream/emscripten/src/library_exceptions.js:  __cxa_uncaught_exceptions: function() {
```

Maybe there's an issue with `libc++-noexcept.a` somehow? Apparently it's present in `exception.cpp.o` in this archive. Not sure if that's important. I can work around it by doing this:

```c++
extern "C" void* __cxa_begin_catch(void*) { std::abort(); }
extern "C" bool __cxa_uncaught_exception() { std::abort(); }
extern "C" unsigned int __cxa_uncaught_exceptions() { std::abort(); }
```

That seems kind of sketchy though. Can you confirm if this is a valid workaround? I found #8856 which seems similar. Maybe that's related.

**Anyway:** When I apply all of my workarounds, our link time on `1.38.43-upstream` drops from 60 seconds to 30 seconds. We're using -O3 for both compiling and linking. Using -O2 drops link time down to 18 seconds and passing -O0 only to the linker (the compiler is still -O3) drops link time down to 7 seconds! This is such a relief. So I think we can say this ticket is about a fastcomp-only issue and close it.

**Comment by sbc100** [comment]
Hmm.. that issue with __cxa_uncaught_exceptions is odd.  if we don't have an issue for that already we should certainly open one.  I'm confused as to why you would be the only one seeing that.

**Comment by sbc100** [comment]
BTW DISABLE_EXCEPTION_CATCHING defaults to 1 so you don't need to set that.

So I think it must be related to `-fno-exceptions` which is think is roughly the same as setting `DISABLE_EXCEPTION_THROWING=1`

**Comment by sbc100** [comment]
It looks like the fix would be add __cxa_uncaught_exceptions to src/library_exceptions_stub.js?

But I'd like to figure out what triggered this so I can write a test.

**Comment by dschuff** [comment]
Just out of curiosity, what happens if you remove `-fno-exceptions` but leave DISABLE_EXCEPTION_CATCHING=1 as the default?

**Comment by sbc100** [comment]
Nobody is setting DISABLE_EXCEPTION_CATCHING to anything but 1 here, right?  Which is the default, so I don't see how it can be relevant?

**Comment by sbc100** [comment]
The __cxa_uncaught_exceptions symbol seems to be referced in libc++.a and libc++-noexcept.a .. seeing if I can figure out why its being pulled in for you but not others.

Try `grep __cxa_uncaught_exceptions ~/.emscripten_cache -r` to search all the prebuilt libraries.

**Comment by sbc100** [comment]
Looks like std::uncaught_exception() and std::uncaught_exceptions() are the only two symbols that directly reference __cxa_uncaught_exceptions.  Can you search you object files for references to  `std::uncaught_exception(s)`?

Does the problem sill occur if you build without `-fno-exceptions`?

**Comment by evanw** [comment]
> Looks like std::uncaught_exception() and std::uncaught_exceptions() are the only two symbols that directly reference __cxa_uncaught_exceptions. Can you search you object files for references to `std::uncaught_exception(s)`?

I just searched our entire object file directory using `grep uncaught_exception -r .` and it came up blank. That should have caught `std::uncaught_exception` and `std::uncaught_exception` because those are called `__ZSt18uncaught_exceptionv` and `__ZSt19uncaught_exceptionsv`. According to `grep uncaught_exception -r .` that string is present in both `exception.cpp.o` and `ios.cpp.o`.

> Does the problem sill occur if you build without `-fno-exceptions`?

Woah, weird. The problem goes away if I remove `-fno-exceptions` and `-s DISABLE_EXCEPTION_CATCHING=1`. I'm now able to build fine. I assume `-fno-exceptions` is still in effect because the resulting binary is still the same size. It never occurred to me that removing `-fno-exceptions` would change anything. Thanks for the easy fix!

**Comment by dschuff** [comment]
`-fno-exceptions` actually means something different than DISABLE_EXCEPTION_CATCHING. It will refuse to compile code that throws, but IIRC it will still generate invokes (i.e. calls that can deal with exceptions that propagate out of the callee). This is surprising to most people and not what we actually want for emscripten, so instead DISABLE_EXCEPTION_CATCHING which converts all the invokes to regular calls (and also converts throws to aborts).

It sounds like we have a bug with `-fno-exceptions` then. I'll file a separate one for that.

**Comment by evanw** [comment]
Ah, that's good to know. I had assumed those settings were the same thing, just one was for clang and one was for emscripten.

I just re-read https://emscripten.org/docs/optimizing/Optimizing-Code.html#c-exceptions which says that you are supposed to add both `-fno-exceptions` and `-s DISABLE_EXCEPTION_CATCHING=1` for optimal code.

Should we wait to use the new WASM backend until we can re-enable `-fno-exceptions`? Or do you think it's reasonable to ship code to production with `-fno-exceptions` off?

**Comment by kripken** [comment]
> Should we wait to use the new WASM backend until we can re-enable -fno-exceptions? Or do you think it's reasonable to ship code to production with -fno-exceptions off?

I'd expect the code size difference to be small, so I wouldn't wait. But worth measuring to see.

**Comment by dschuff** [comment]
I think DISABLE_EXCEPTION_CATCHING=1 (even without `-fno-exceptions`) is basically everything you want optimization-wise, and it's the most-used/most-tested configuration for emscripten. So I think you should be fine just switching to the wasm backend whenever you are ready and leaving out `-fno-exceptions` if you need to.
