### ISSUE TITLE
How to get LLVM to merge identical function implementations?

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#3954]
It looks like LLVM has a [MergeFunctions](http://llvm.org/docs/MergeFunctions.html) pass but it's not being run as far as I can tell. It would make a huge difference for us; half of the symbols in the compiled code are in the std namespace and the top offenders are std::unordered_map, std::vector, and std::function.

Is it possible to get this LLVM's function merging pass to work with emscripten? If it's impossible, we can maybe look into using or writing something like [uSTL](https://msharov.github.io/ustl/) which uses inlining to accomplish this. It would be nice for emscripten to do this automatically though.

Example code:

```
#include <vector>

struct Foo {};
struct Bar {};

int main(int argc, char *argv[]) {
  std::vector<Foo *> foo;
  std::vector<Bar *> bar;
  for (int i = 0; i < argc; i++) {
    foo.emplace_back(new Foo);
    bar.emplace_back(new Bar);
  }
  return 0;
}
```

Example output:

```
function _main($argc, $argv) {
 $argc = $argc | 0;
 $argv = $argv | 0;
 var $$pre = 0, $0 = 0, $1 = 0, $10 = 0, $16 = 0, $17 = 0, $2 = 0, $26 = 0, $27 = 0, $33 = 0, $36 = 0, $4 = 0, $7 = 0, $8 = 0, $9 = 0, $bar = 0, $foo = 0, $i$015 = 0, sp = 0;
 sp = STACKTOP;
 STACKTOP = STACKTOP + 32 | 0;
 $foo = sp + 20 | 0;
 $bar = sp + 8 | 0;
 $0 = sp + 4 | 0;
 $1 = sp;
 HEAP32[$foo >> 2] = 0;
 $2 = $foo + 4 | 0;
 HEAP32[$2 >> 2] = 0;
 HEAP32[$foo + 8 >> 2] = 0;
 HEAP32[$bar >> 2] = 0;
 $4 = $bar + 4 | 0;
 HEAP32[$4 >> 2] = 0;
 HEAP32[$bar + 8 >> 2] = 0;
 if (($argc | 0) > 0) {
  $7 = $foo + 8 | 0;
  $8 = $bar + 8 | 0;
  $i$015 = 0;
  do {
   $9 = __Znwj(1) | 0;
   HEAP32[$0 >> 2] = $9;
   $10 = HEAP32[$2 >> 2] | 0;
   if ($10 >>> 0 < (HEAP32[$7 >> 2] | 0) >>> 0) {
    HEAP32[$10 >> 2] = $9;
    HEAP32[$2 >> 2] = (HEAP32[$2 >> 2] | 0) + 4;
   } else __ZNSt3__16vectorIP3FooNS_9allocatorIS2_EEE24__emplace_back_slow_pathIJS2_EEEvDpOT_($foo, $0);
   $16 = __Znwj(1) | 0;
   HEAP32[$1 >> 2] = $16;
   $17 = HEAP32[$4 >> 2] | 0;
   if ($17 >>> 0 < (HEAP32[$8 >> 2] | 0) >>> 0) {
    HEAP32[$17 >> 2] = $16;
    HEAP32[$4 >> 2] = (HEAP32[$4 >> 2] | 0) + 4;
   } else __ZNSt3__16vectorIP3BarNS_9allocatorIS2_EEE24__emplace_back_slow_pathIJS2_EEEvDpOT_($bar, $1);
   $i$015 = $i$015 + 1 | 0;
  } while (($i$015 | 0) < ($argc | 0));
  $$pre = HEAP32[$bar >> 2] | 0;
  $26 = $$pre;
  if ($$pre) {
   $27 = HEAP32[$4 >> 2] | 0;
   if (($27 | 0) != ($$pre | 0)) HEAP32[$4 >> 2] = $27 + (~(($27 + -4 - $26 | 0) >>> 2) << 2);
   __ZdlPv($$pre);
  }
 }
 $33 = HEAP32[$foo >> 2] | 0;
 if (!$33) {
  STACKTOP = sp;
  return 0;
 }
 $36 = HEAP32[$2 >> 2] | 0;
 if (($36 | 0) != ($33 | 0)) HEAP32[$2 >> 2] = $36 + (~(($36 + -4 - $33 | 0) >>> 2) << 2);
 __ZdlPv($33);
 STACKTOP = sp;
 return 0;
}

function __ZNSt3__16vectorIP3FooNS_9allocatorIS2_EEE24__emplace_back_slow_pathIJS2_EEEvDpOT_($this, $__args) {
 $this = $this | 0;
 $__args = $__args | 0;
 var $$0$i2 = 0, $$0$i3 = 0, $0 = 0, $12 = 0, $13 = 0, $18 = 0, $2 = 0, $20 = 0, $22 = 0, $25 = 0, $26 = 0, $31 = 0, $32 = 0, $39 = 0, $4 = 0, $42 = 0, $43 = 0, $7 = 0, $9 = 0, label = 0;
 $0 = $this + 4 | 0;
 $2 = HEAP32[$this >> 2] | 0;
 $4 = $2;
 $7 = ((HEAP32[$0 >> 2] | 0) - $4 >> 2) + 1 | 0;
 if ($7 >>> 0 > 1073741823) __ZNKSt3__120__vector_base_commonILb1EE20__throw_length_errorEv($this);
 $9 = $this + 8 | 0;
 $12 = $2;
 $13 = (HEAP32[$9 >> 2] | 0) - $12 | 0;
 if ($13 >> 2 >>> 0 < 536870911) {
  $20 = $13 >> 1;
  $22 = $20 >>> 0 < $7 >>> 0 ? $7 : $20;
  $25 = (HEAP32[$0 >> 2] | 0) - $12 | 0;
  $26 = $25 >> 2;
  if (!$22) {
   $$0$i3 = 0;
   $31 = 0;
   $32 = $26;
   $39 = $25;
  } else {
   $$0$i2 = $22;
   $42 = $26;
   $43 = $25;
   label = 6;
  }
 } else {
  $18 = (HEAP32[$0 >> 2] | 0) - $12 | 0;
  $$0$i2 = 1073741823;
  $42 = $18 >> 2;
  $43 = $18;
  label = 6;
 }
 if ((label | 0) == 6) {
  $$0$i3 = $$0$i2;
  $31 = __Znwj($$0$i2 << 2) | 0;
  $32 = $42;
  $39 = $43;
 }
 HEAP32[$31 + ($32 << 2) >> 2] = HEAP32[$__args >> 2];
 _memcpy($31 | 0, $2 | 0, $39 | 0) | 0;
 HEAP32[$this >> 2] = $31;
 HEAP32[$0 >> 2] = $31 + ($32 + 1 << 2);
 HEAP32[$9 >> 2] = $31 + ($$0$i3 << 2);
 if (!$4) return;
 __ZdlPv($4);
 return;
}

function __ZNSt3__16vectorIP3BarNS_9allocatorIS2_EEE24__emplace_back_slow_pathIJS2_EEEvDpOT_($this, $__args) {
  // This code is exactly the same as __ZNSt3__16vectorIP3FooNS_9allocatorIS2_EEE24__emplace_back_slow_pathIJS2_EEEvDpOT_()
}
```

**Comment by kripken** [comment]
@waywardmonkeys knows best about this pass. We haven't enabled it by default due to previous issues.

How effective is it on your codebase, btw? (`opt -mergefunc`,  I think)

**Comment by evanw** [comment]
I'm not sure how to unravel emcc so I can run opt separately and inject the right arguments. Any tips?

I just tried swapping out STL in our app. I couldn't get uSTL working so I wrote my own (very buggy!) implementation of std::vector: https://github.com/evanw/light/blob/master/src/light_vector.h. Using it instead of std::vector shaves off over 800kb of code, which is 10% of our entire app. Further gains are likely possible by reimplementing other types like std::unordered_map.

**Comment by waywardmonkeys** [comment]
Should be safe to use `-mergefunc` ... We've been using it for a while after getting fixes done upstream in the LLVM 3.4 days ...

**Comment by kripken** [comment]
@evanw: you can run opt separately. just link all your code into a bitcode file (using emcc, with `-o something.bc`, and then run `opt -mergefunc something.bc -o merged.bc` where `opt` is from fastcomp. Then you can run that `merged.bc` in emcc.

@waywardmonkeys: good to know you're using this. Perhaps emscripten should enable it on -Os and/or -Oz builds. I'll see what happens on the test suite.

**Comment by kripken** [comment]
I did some tests and I don't see a significant benefit to mergefunc (less than 1%). I also don't see any bugs though.

**Comment by kripken** [comment]
I created a `mergefunc` branch with a commit to enable it in `-Oz` and add a test. But without clear benefits, I'm not sure this is worth merging.

**Comment by evanw** [comment]
I tried running `opt -mergefunc` on the example above and it didn't do anything. Am I doing this right?

```
~/Downloads/emsdk_portable/emscripten/1.35.0/emcc foo.cpp -O2 -g -std=c++11 -o foo.bc
~/Downloads/emsdk_portable/clang/e1.35.0_64bit/opt -mergefunc foo.bc -o foo.opt.bc
ls -l foo.bc foo.opt.bc
```

This shows the files as the same size before and after the optimization pass:

```
-rw-r--r--  1 evan  staff  97536 Dec 10 10:12 foo.bc
-rw-r--r--  1 evan  staff  97536 Dec 10 10:12 foo.opt.bc
```

**Comment by kripken** [comment]
Testing on unity, I see a 3% improvement, which is not amazing but still nice.

**Comment by kripken** [comment]
@evanw: yes, that looks correct. looks like mergefunc doesn't manage to remove anything on your codebase.

To verify another way, you can add some obviously-redundant methods, to see that that works.

Can also try `-Oz` on the incoming branch vs. mergefunc branch, only difference is mergefunc is run in the latter.
