### ISSUE TITLE
Support minimal asm.js generation

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#3955]
We can already emit the asm.js separately with `--separate-asm`, but due to linking bringing in libc, it generally contains more than the user's own code. It would be nice to also support people writing C and getting literally just what they wrote in the output asm.js.

cc @wycats @lukewagner

**Comment by kripken** [comment]
Ok, I landed a first step towards this on incoming, which should get us most of the way. With `-s ONLY_MY_CODE=1` to emcc, it will only emit the user's own code in the asm module - no system libs (C or JS) are linked in.

A full command might look something like this:

````
emcc -O3 -s ONLY_MY_CODE=1 -g2 --separate-asm input.cpp -o output.js
````

That will emit an optimized but fairly readable build of the compiled code in `output.asm.js`.

It still contains a bunch of unnecessary globals, and one unnecessary empty function. We can remove those as well as followups.

**Comment by kripken** [comment]
(patches were 26bcb06f0d9983c7bbf177615bb857e18c243ab5 and 7ab7daeac0b1524baa033d6f12e3c6a742a73faf)

**Comment by kripken** [comment]
I landed some followups. There should now be no unnecessary globals or that unnecessary function. The output should now be as minimal as is possible, at a quick glance.

Feedback welcome, I have nothing else obvious to work on here, except for thinking about a blogpost.

**Comment by juj** [comment]
Hey, nice, I like this! Being able to scale small is a worthy goal I think. I wonder if there might be ways to improve our dead code elimination and preamble management so that we could do more stripping with less flags(?)

**Comment by kripken** [comment]
Closure compiler should strip unneeded parts of preamble. With `EXPORTED_RUNTIME_METHODS` one can define which methods will be kept by closure.

**Comment by bmccallion** [comment]
Nice. I've been working on functions and the ability to strip out the excess code is something I was trying to figure out.

**Comment by bmccallion** [comment]
When I call like this I get a message stating that this invocation only works if I'm building to HTML:

 emcc -O3 -s ONLY_MY_CODE=1 -g2 --separate-asm SwapValuation.o -o SwapValuation.js

INFO:root:(Emscripten: Running sanity checks)
Traceback (most recent call last):
  File "/data/code/emsdk_portable/emscripten/master/emcc", line 856, in <module>
    assert not (separate_asm and final_suffix != 'html'), '--separate-asm requires building to HTML'
AssertionError: --separate-asm requires building to HTML

**Comment by kripken** [comment]
Yes, because it's a little tricky otherwise. When you build to html and split out, the HTML loads both your JS files. But if you build to JS and split, the user will need to load the `.asm.js` file first - which seems like a likely mistake.

**Comment by kripken** [comment]
@juj: regarding stripping with less flags, I started a JSDCE pass

https://github.com/kripken/emscripten/blob/incoming/tools/js-optimizer.js#L7761

which removes obviously unused code, using closure rules (no use, no export on Module, then kill it). To be really useful it would need recursive mark and sweep, though, probably.

**Comment by parasyte** [comment]
Using `-s ONLY_MY_CODE=1` with emcc 1.37.9 creates broken JavaScript:

```
parasyte@Turkatron:~/Desktop/emtest$ node hello-exe.js
Assertion failed: undefined
Assertion failed: undefined

/Users/parasyte/Desktop/emtest/hello-exe.js:134
      throw ex;
      ^
abort("Assertion failed: undefined") at Error
    at jsStackTrace (/Users/parasyte/Desktop/emtest/hello-exe.js:1145:13)
    at stackTrace (/Users/parasyte/Desktop/emtest/hello-exe.js:1162:12)
    at abort (/Users/parasyte/Desktop/emtest/hello-exe.js:1904:44)
    at assert (/Users/parasyte/Desktop/emtest/hello-exe.js:445:5)
    at Array.Runtime.staticAlloc (/Users/parasyte/Desktop/emtest/hello-exe.js:421:80)
    at allocate (/Users/parasyte/Desktop/emtest/hello-exe.js:675:189)
    at Object.callMain (/Users/parasyte/Desktop/emtest/hello-exe.js:1766:15)
    at doRun (/Users/parasyte/Desktop/emtest/hello-exe.js:1842:60)
    at run (/Users/parasyte/Desktop/emtest/hello-exe.js:1856:5)
    at Object.<anonymous> (/Users/parasyte/Desktop/emtest/hello-exe.js:1930:1)
```

I did some debugging and found that a `_malloc` function must be present, or this assertion is raised when `callMain` attempts to allocate a string for argv: https://github.com/kripken/emscripten/blob/1.37.9/src/postamble.js#L137

I was able to workaround this by copying the implementation of `Runtime.stackAlloc` to a top-level function named `_malloc`.
