### ISSUE TITLE
Trouble building projects into LLVM (.bc) file. 

### ISSUE THREAD

**Issue by akadmc** [emscripten-core/emscripten#3957]
Hello,

Ubuntu 14.04 here. 

I'm new to using emscripten, so please forgive me if I'm making some sort of newbie mistake. According to this documentation (https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries) I should be able to compile a project or library into LLVM by using the following code:

> ./emconfigure ./configure
> ./emmake make

Essentially, if my understanding is correct, we run the configuration file for the project (if it exists) and then run the make file through emmake, and then I'm supposed to get a LLVM (.bc) file instead of the normal binary. 

I've tried this on two separate projects / libraries :

1.) zlib (https://github.com/akadmc/SmashBattle/tree/master/zlib-1.2.8)

As far as I could tell, the only thing that came to close to something that could possibly be was the libz.so.1.2.8 file. 

2.) SmashBatle (https://github.com/akadmc/SmashBattle)

It seemed to just generate the same executable that make would create without using emmake (smashBattle). Note: I replaced the projects original Makefile (now named Makefile.bak) with one I wrote because I was having trouble getting the original one running on my system. 

So, finally I figure maybe these execs appear to be the same but really they are LLVM. So i try the final step as indicated in the link I gave earlier:

> emcc smashBattle libz.so.1.2.8 -o final.html

However, I keep getting the following errors:

1.) smashBattle: Input file has an unknown suffix, don't know what to do with it!

Then, if i perhaps foolishly rename the file to smashBattle.bc it says: 

2.) smashBattle.bc is not valid LLVM bitcode

I'm pretty lost, any help would be appreciated.

**Comment by akadmc** [comment]
Okay, so I figured out that you can just compile with em++ and specify the outfile as .bc and that does the trick, but I still don't see how this applies to using make files for a specific project, they always seem to come out in the format specified in the makefile so why use emmake?

**Comment by kripken** [comment]
emconfigure/emmake set up some env vars, basically, they make configure/make use emcc (and emar, etc.) instead of gcc. That's basically it, so if you can make the build system use emcc/etc. in another way, that should be fine too.

Yes, emconfigure/emmake leave the output target file with the name the build system defines, which can be libfoo.so.0.0.1. You then need to rename it to .so (or .o or .bc), then build that into JS.

**Comment by akadmc** [comment]
Thanks for the speedy response. Basically if a project doesn't rely on a ./configure file then this approach wont work correct?

**Comment by kripken** [comment]
Well, if a project has just a makefile, and the makefile uses the standard env vars for the compiler, then emmake would still help.

**Comment by kripken** [comment]
Also emconfigure can help with other configuration systems like cmake.
