### ISSUE TITLE
Unresolved symbol Warnings for SDL_WaitEvent, SDL_DisplayFormat during final compliation. 

### ISSUE THREAD

**Issue by akadmc** [emscripten-core/emscripten#3959]
I've built two files into bitcode using emcc, one file is a game, the other is zlib. Then, I performed the final compiling into HTML as such:

>  emcc smashBattle.bc libz.so.1.2.8.bc -o test_1.html

upon which I get the following warnings: 

> warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
> warning: unresolved symbol: SDL_WaitEvent
> warning: unresolved symbol: SDL_DisplayFormat

I understand the first warning, but the the last two I don't. I'm unsure of their severity or exactly what they mean. Is this something I need to worry about?

**Comment by akadmc** [comment]
Also, when I try to run the compiled HTML, among other errors, I get "missing function: SDL_DisplayFormat"

**Comment by akadmc** [comment]
After some research, I'm assuming that these SDL functions don't translate into the flavor of SDL being used in emscripten. 

I found this article (http://blog.cfiet.net/posts/2014/bringing-back-eighties-with-emscripten-part3.html) that outlines how you can change SDL_DisplayFormat to SDL_DisplayFormatAlpha in the source code... still looking into the SDL_WaitEvent.

However, any input is still welcomed.

**Comment by kripken** [comment]
`SDL_WaitEvent` does a synchronous wait on user input, which is incompatible with how the event loop works on the web. You can check for events in your main loop with `SDL_PollEvent`, instead of doing a synchronous wait.

**Comment by akadmc** [comment]
OK, I'll look into it. Thanks again for your speedy help!
