### ISSUE TITLE
fseeko() fails when called with a value >= 2^31 on Mac OS X and Windows

### ISSUE THREAD

**Issue by mbarthelemy** [emscripten-core/emscripten#3968]
It's difficult to tell exactly why I am getting an EINVAL errno by calling fseeko. It seems that both Mac OS X and Windows don't have SYS_llseek defined as used by emscripten/system/lib/libc/musl/src/stdio/__stdio_seek.c. I have been attempting to create an isolated test program but have been struggling to get /tmp to mount in node. Both programs work as expected when compiled natively. Running the first test program natively and via node on the file created by the second program below should report the same result.

Values smaller than 2147483648 seem to work fine on both platforms without errors.

Test program:

```
// compile natively
// cc test.c -o test
// run
// ./test

// compile emscripten 1.35.0
// emcc test.c -o test.js
// run
// node test.js

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#ifdef EMSCRIPTEN
#include <emscripten/emscripten.h>
#endif

int main(int argc, char **argv)
{
#ifdef EMSCRIPTEN
  emscripten_run_script("FS.mount(NODEFS, { root: '/tmp' }, '/tmp')");
#endif
  FILE *fl = fopen("/tmp/bigfile", "r");
  off_t position = 133LL * 20000000LL; // line number 20 million from the program below (byte 2660000000)

  // reset errno
  errno = 0;

  fseeko(fl, position, SEEK_SET);

  if (errno) {
#ifdef EMSCRIPTEN
    // expected errno = 22 (EINVAL) after call
    emscripten_log(EM_LOG_CONSOLE, "fseeko errno: %d\n", errno);
#else
    printf("fseeko errno: %d\n", errno);
#endif
  }
  else {
    char buffer[132];

    fread(buffer, 132, 1, fl);

#ifdef EMSCRIPTEN
    emscripten_log(EM_LOG_CONSOLE, "bytes: %s", buffer);
#else
    printf("bytes: %s\n", buffer);
#endif
  }

  return 0;
}
```

Here is a c program to create a 2992500000 byte test file:

```
// compile natively
// cc bigfilecreate.c -o bigfilecreate
// run
// ./bigfilecreate

#include <stdio.h>
#include <stdlib.h>

#define BUFLENGTH   133

int main(int argc, char **argv)
{
  FILE *fl = fopen("/tmp/bigfile", "w");
  off_t length = 22500000;
  char buffer[BUFLENGTH];
  int32_t i, j;

  buffer[132] = '\n';

  for (i = 0; i < length; i++) {
    for (j = 0; j < BUFLENGTH - 1; j++) {
      // append ascii characters from space to ~
      buffer[j] = (random() % 94) + 32;
    }

    fwrite(buffer, BUFLENGTH, 1, fl);
  }

  return 0;
}
```

**Comment by mbarthelemy** [comment]
Here is a workaround, tested to work on Mac OS X and will be tested shortly for Windows. The offset argument is deliberately typed to int64_t.

```
#include <limits.h>
#include <errno.h>

int fseeko_workaround(FILE *stream, int64_t offset, int whence)
{
    int result = 0;

#ifdef EMSCRIPTEN
    if (offset > INT_MAX || offset < INT_MIN) {
        int64_t remainingOffset = offset;
        int32_t offsetIncrement = 2000000000;
        int thisWhence = whence;

        // If we're seeking from the end the offsets will be negative.
        if (whence == SEEK_END) {
            offsetIncrement *= -1;
        }

        while (remainingOffset) {
            if (remainingOffset < offsetIncrement) {
                int32_t offsetToSend = remainingOffset;

                result = fseeko(stream, offsetToSend, thisWhence);

                remainingOffset = 0LL;
            }
            else {
                result = fseeko(stream, offsetIncrement, thisWhence);

                remainingOffset -= offsetIncrement;
                // After the first seek we are seeking relative to the current location.
                thisWhence = SEEK_CUR;
            }
        }
    }
    else {
        result = fseeko(stream, offset, whence);
    }
#else
    result = fseeko(stream, offset, whence);
#endif

    return result;
}
```

**Comment by kripken** [comment]
I think emscripten assumes 32-bit offsets since JS memory is in effect 32-bit (max size of a typed array). Perhaps in NODEFS we could directly go to the system, though, but I'm not sure.

**Comment by mbarthelemy** [comment]
We're using emscripten to compile some C which works with movie metadata. (We're essentially building a video editor in Electron and using emscripten for some of the heavy backend lifting.) Our files are often over 2GiB. Since Javascript numbers can represent 53-bit integer values without a loss of precision it isn't a limitation that we're terribly worried about for now. We are definitely interested in having as close to full 64-bit support via emscripten as is reasonable with the POSIX libraries.

**Comment by kripken** [comment]
I see. There shouldn't be much to fix for that to work, but I honestly don't know. It would help if you created some standalone testcases to check the functionality you need, and then we could add them to the test suite and make sure they pass and don't regress.

**Comment by mbarthelemy** [comment]
I believe that the only two calls we're using today are fseeko and ftello. The code in my initial submission should be easy enough to turn into a test case but I couldn't get the mount working when running via node. If you have any suggestions I would appreciate it. I will also write up a test case for ftello. I have been meaning to do it since I discovered the fseeko issue. We can certainly write further test cases as we cover more of the POSIX calls with our code.

**Comment by kripken** [comment]
Is it necessary to get it working via node? Is your main target node, or the browser?

**Comment by kripken** [comment]
(Might be a silly question, but I don't know much about Electron :))

**Comment by mbarthelemy** [comment]
With Electron we're both node and a browser which creates all sorts of problems. :) We have a script that swaps out the way that ENVIRONMENT_IS_SHELL, ENVIRONMENT_IS_WEB, ENVIRONMENT_IS_NODE and ENVIRONMENT_IS_WORKER are computed. In addition we have a wrapper of the initialization of the emscripten compiled code and we pass an argument for if we want to run as node or not.

As for your question, when we're using it for the file operations we're are running as node. In other operations we want to run as a browser because of fun with CORS.

**Comment by kripken** [comment]
I see, interesting.

The optimal thing for testing would be to create a pull request with literally commits that add tests to our test suite. For this type of test, it can go in `tests/test_other.py`.

**Comment by fallenoak** [comment]
@kripken @mbarthelemy  I just hit this issue in a project I'm working on. Unfortunately, I am targeting Node and need to work with files larger than `(2 ^ 31) - 1` bytes in size.

What would it take to get emscripten to support FS operations on files sized up to `(2 ^ 32) - 1` bytes?
