### ISSUE TITLE
aggressive usage of general _memcpy

### ISSUE THREAD

**Issue by weilianglin** [emscripten-core/emscripten#3983]
When compiling fannkuch.cpp with "-O2", below C++ code will be translated into _memcpy

   perm1 = (int_)malloc(n \* sizeof(int));
   perm = (int_)malloc(n \* sizeof(int));
        for (i = 0; i < n; i++)
            perm[i] = perm1[i];

==>  _memcpy(i5 | 0, i4 | 0, i3 | 0) | 0;

_memcpy is too general and check the byte length of data and also the alignment of arrays.  If we already know perm and perm1 are int32 arrays, we can directly use "HEAP32[i1 >> 2] = HEAP32[i2 >> 2];" rather than calling to the general function.

function _memcpy(i1, i2, i3) {
 i1 = i1 | 0;
 i2 = i2 | 0;
 i3 = i3 | 0;
 var i4 = 0;
 if ((i3 | 0) >= 4096) return _emscripten_memcpy_big(i1 | 0, i2 | 0, i3 | 0) | 0;
 i4 = i1 | 0;
 if ((i1 & 3) == (i2 & 3)) {
  while (i1 & 3) {
   if (!i3) return i4 | 0;
   HEAP8[i1 >> 0] = HEAP8[i2 >> 0] | 0;
   i1 = i1 + 1 | 0;
   i2 = i2 + 1 | 0;
   i3 = i3 - 1 | 0;
  }
  while ((i3 | 0) >= 4) {
   HEAP32[i1 >> 2] = HEAP32[i2 >> 2];
   i1 = i1 + 4 | 0;
   i2 = i2 + 4 | 0;
   i3 = i3 - 4 | 0;
  }
 }
 while ((i3 | 0) > 0) {
  HEAP8[i1 >> 0] = HEAP8[i2 >> 0] | 0;
  i1 = i1 + 1 | 0;
  i2 = i2 + 1 | 0;
  i3 = i3 - 1 | 0;
 }
 return i4 | 0;
}

**Comment by kripken** [comment]
Agreed, this could be optimized. But at the LLVM level we have
````
  call void @llvm.memcpy.p0i8.p0i8.i32(i8* %7, i8* nonnull %5, i32 %4, i32 4, i1 false)
````
where the third argument is alignment, so it does know that the source and dest are 4-byte aligned. However, we do *not* know that the number of bytes is a multiple of 4, according to LLVM semantics. So we couldn't just replace the memcpy call with a loop, it would also need to handle trailing bytes as well..

Unless I am missing something about LLVM memcpy semantics? @sunfishcode

**Comment by sunfishcode** [comment]
You're correct; the intrinsic doesn't say anything about the size.

One option for optimizing this might be to use the ComputeMultiple function in Analysis/ValueTracking.h. This should succeed in many cases, because the input to a memcpy is fairly often a shift or a multiply converting the count of elements to a byte count.
