### ISSUE TITLE
Document FS.analyzePath

### ISSUE THREAD

**Issue by yurevich1** [emscripten-core/emscripten#3984]
I can find in manual.
How can I check file/directory with the same name exists?
For instance, if I call `FS.mkdir(dirpath)` it calls an error. No information in manual!

**Comment by kripken** [comment]
One way is to try to open, and catch an error.

Another is to use analyzePath, but I don't think it's well-documented - we should fix that. Let's rename this bug to that purpose.

**Comment by mmontag** [comment]
In lieu of documentation:
`fileExists = FS.analyzePath('filename.txt').exists`

**Comment by cancerberoSgx** [comment]
I can't find analyzePath in the docs. https://emscripten.org/docs/api_reference/Filesystem-API.html systems Is that public ? if so would you accept a PR in the docs ? thanks

**Comment by kripken** [comment]
@cancerberoSgx a PR would be great! :)

**Comment by kripken** [comment]
A PR here would still be great if @cancerberoSgx or someone else has time :smiley:
