### ISSUE TITLE
Optimize emscripten logo in default HTML

### ISSUE THREAD

**Issue by behdad** [emscripten-core/emscripten#3999]
I managed to compile GLyphy through emscripten tonight (last time I tried was in 2012).  It works, and the optimized output is less than 2MB.  Back in 2012 it used to be 13MB.  Nice job!

It looks to me that bulk of the 100kb html file generated is the emscripten logo.  If I remove that, the html file becomes 8kb.  Maybe you replace it with something simpler?  Thanks.

**Comment by kripken** [comment]
You can use a custom html file, `--shell-file`. See for example `src/shell_minimal.html`.

I think most people don't use the default html file anyhow, so we haven't focused on optimizing it. However, if someone with graphics skills wants to optimize the logo I'd be happy of course.

**Comment by jgamble** [comment]
I thought I'd look at this (I've been a lurker for a while), and I see that the SVG file has a eleven base64-encoded images in it, two of which (the largest) are JPEGS. It looks like the SVG logo was developed from these images, but afterwards the images weren't cleared out (it's also possible that they were kept for "fallback" purposes in case the browser couldn't display SVG).

(There's also the usual scruff that Inkscape leaves in if you don't tell it to clean up, but that's probably not significant right now).

A good first start would be to remove the images. Bearing in mind I'm looking at this with no background into its history, would you like me to take a crack at it?

**Comment by kripken** [comment]
Sure, that would be great!

I don't know much about the history of the file, git might have something, but I think it was just contributed as-is. It was a huge improvement on our previous HTML, which I think may have had no logo at all.
