### ISSUE TITLE
Failure on cmake test "TestEndianess"

### ISSUE THREAD

**Issue by cmundi** [emscripten-core/emscripten#400]
I've built llvm (including clang) and have run the emscripten tutorials but this is my first attempt to use emscripten on an existing project.

My project uses CMake and tests for endianess using  /usr/share/cmake-2.8/Modules/TestEndianess.c.in

Natively, cmake works when I'm using the gcc toolchain, but when I switch to 

   emconfigure.py cmake

then I get a failure on the endianess test.  I provide some context leading up to it in case it is important.

Performing Test SEMUN_DEFINED
Performing Test SEMUN_DEFINED - Failed
Performing Test SEMOP_NO_REFERENCE
Performing Test SEMOP_NO_REFERENCE - Failed
Performing Test SEMCTL_NO_REFERENCE
Performing Test SEMCTL_NO_REFERENCE - Failed
Performing Test DEF_IOS_OK
Performing Test DEF_IOS_OK - Failed
Performing Test OSTREAM_FORM_OK
Performing Test OSTREAM_FORM_OK - Failed
Check if the system is big endian
Searching 16 bit integer
Check size of unsigned short
Check size of unsigned short - failed
Check size of unsigned int
Check size of unsigned int - failed
Check size of unsigned long
Check size of unsigned long - failed
CMake Error at /usr/share/cmake-2.8/Modules/TestBigEndian.cmake:44 (MESSAGE):
  no suitable type found
Call Stack (most recent call first):
  CMakeLists.txt:637 (TEST_BIG_ENDIAN)

Should I be looking for an issue with LLVM or an issue with emscripten?  In either case, any suggestions will be appreciated!

**Comment by jeromewu** [comment]
Just for people who might come here from googling solution for TestBigEndian issue.

For a newer version of emscripten, there is a cmake/Modules to fix the issue, all you have to do is adding folling line to your CMakeLists.txt:

```
# It will work when using docker image trzeci/emscripten:sdk-tag-1.38.16-64bit
set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};/emsdk_portable/sdk/cmake/Modules")
```

This will fix the issue without hard code anything.
