### ISSUE TITLE
String memory initializer corrupts memory

### ISSUE THREAD

**Issue by waywardmonkeys** [emscripten-core/emscripten#4007]
We have a really fun bug where, when using the string memory initialize, at some point, memory is shifted backwards by 3 bytes.  So, an address pointing to some data ends up pointing to the 4th byte in the data instead.

I haven't tracked down why exactly yet.

We're on a slightly older revision of emscripten (2414ad898a83a9d2d3efa248a2d17f3a27e1e730 from October 21, 2015).

**Comment by juj** [comment]
This definitely sounds like an effect resulting from a memory alignment problem. Does the issue still persist? If so, try the `-s SAFE_HEAP=1` linker flag to see if that uncovers any problems.
