### ISSUE TITLE
Using unsupported immediate mode GL_POLYGON

### ISSUE THREAD

**Issue by jeffrey-effendy** [emscripten-core/emscripten#4010]
So, I was trying to emulate <code>glBegin(GL_POLYGON)</code> and I received an error <code>Uncaught unsupported mode 9</code>, which is caused by calling the GL_POLYGON. Is there any way to emulate it? 

I have turned on option LEGACY_GL_EMULATION=1 and GL_UNSAFE_OPTS=0, but still fails.

**Comment by kripken** [comment]
You can try to see how hard it is to add to the legacy emulation code, but there's a good chance it isn't easy.

A more general solution is to build with Regal, the GL emulation library. It's intended to help with this kind of thing, but I'm not aware of anyone with a current emscripten port.
