### ISSUE TITLE
EMTERPRETIFY throwing error

### ISSUE THREAD

**Issue by jenvannier** [emscripten-core/emscripten#4018]
For the program

> # ifdef EMSCRIPTEN
> # include <emscripten/emscripten.h>
> # include <SDL/SDL.h>
> # include <GLES2/gl2.h>
> # endif
> 
> int main() {
>   return 0;
> }

I compile with the command line:

> em++ -std=c++11  -DEMSCRIPTEN -s USE_PTHREADS=1 -s  -s EMTERPRETIFY=1  -s EMTERPRETIFY_ASYNC=1   test.cc  -o test.html

and it throws this error:

> WARNING:root:clearing cache
> INFO:root:(Emscripten: Running sanity checks)
> WARNING:root:generating system library: libc-mt.bc...
> WARNING:root:                                        ok
> WARNING:root:generating system library: pthreads.bc...
> WARNING:root:                                         ok
> WARNING:root:generating system library: dlmalloc_threadsafe.bc...
> WARNING:root:                                                    ok
> Stack: Error
>     at assertTrue (eval at globalEval (/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:114:8), <anonymous>:59:26)
>     at /Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:7003:9
>     at Array.forEach (native)
>     at makeCall (/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:6998:15)
>     at getReg (/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:6381:24)
>     at getReg (/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:6148:27)
>     at getReg (/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:6135:29)
>     at /Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:7034:19
>     at Array.forEach (native)
>     at walkStatements (/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js-optimizer.js:7032:13)
> 
> undefined:60
>     throw msg;
>     ^
> Assertion failed: undefined
> Traceback (most recent call last):
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/emterpretify.py", line 824, in <module>
>     shared.Building.js_optimizer(infile, ['emterpretify'], extra_info={ 'emterpretedFuncs': list(emterpreted_funcs), 'externalEmterpretedFuncs': list(external_emterpreted_funcs), 'opcodes': OPCODES, 'ropcodes': ROPCODES, 'ASYNC': ASYNC, 'PROFILING': PROFILING, 'ASSERTIONS': ASSERTIONS }, output_filename=temp, just_concat=True)
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/shared.py", line 1656, in js_optimizer
>     ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 539, in run
>     return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 64, in run_and_clean
>     return func()
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 539, in <lambda>
>     return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 449, in run_on_js
>     filenames = [run_on_chunk(command) for command in commands]
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 279, in run_on_chunk
>     assert proc.returncode == 0, 'Error in optimizer (return code ' + str(proc.returncode) + '): ' + output
> AssertionError: Error in optimizer (return code 1): function _malloc($bytes) {
>  $bytes = $bytes | 0;
>  var $$1 = 0, $$lcssa = 0, ...

with a traceback:

> Traceback (most recent call last):
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/em++", line 13, in <module>
>     emcc.run()
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/emcc.py", line 1701, in run
>     JSOptimizer.flush()
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/emcc.py", line 1544, in flush
>     run_passes(chunks[0], title, just_split=False, just_concat=False)
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/emcc.py", line 1517, in run_passes
>     final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/shared.py", line 1656, in js_optimizer
>     ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 539, in run
>     return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 64, in run_and_clean
>     return func()
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 539, in <lambda>
>     return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
>   File "/Users/jennifer/workspace/emsdk_portable/emscripten/incoming/tools/js_optimizer.py", line 297, in run_on_js
>     js = open(filename).read()
> IOError: [Errno 2] No such file or directory: '/var/folders/xh/_txhctk92kb2ycj44h09zjq80000gn/T/tmpC4IhtatmpoKbGRm.jsfunc_0.js.jo.js.jo.js.em.js'

Am I using EMTERPRETIFY wrong? Without EMTERPRETIFY=1 it doesn't throw this error, but it is my understanding that for EMTERPRETIFY_ASYNC (which I need for my rendering loops later) to work I need to have EMTERPRETIFY. Thank you for your time!

**Comment by kripken** [comment]
It's probably pthreads. We should have a better error for this. Basically, pthreads requires atomics and other special things that are not in the subset of asm.js that emterpretify can handle, currently.

**Comment by jenvannier** [comment]
Ok, thanks. Do we have any estimation on when Emscripten will be able to handle this or is it a far off goal?

**Comment by kripken** [comment]
I don't have plans to work on it, and I am not aware of anyone else. If you or someone else wants to, though, I can give guidance. It's not a massive effort, but it would take some careful work - basically adding some new emterpreter opcodes.

**Comment by jenvannier** [comment]
I could take a crack at it! I would appreciate any guidance on the matter.

**Comment by kripken** [comment]
Ok, great. Here is how I would approach this:

1. Verify that without pthreads, it builds ok (but probably it won't run).
2. Diff a pthreads build vs a non-pthreads build, both without emterpretify (with `-g2` for readability). Aside from libpthreads code being pulled in, I would expect to see some atomic operations, `Atomic_*`, etc. The problem must be in that difference. Might be easier to do the difference on as small a program as possible.
3. Can run emterpretify on the pthreads one, to verify that it fails to build (by calling `tools/emterpretify.py`; can look at the arguments emcc calls it with).
4. After that, it should be easy to see what specifically emterpretify is failing on.

Alternatively to all that, it might be possible to figure it out from the emterpretify stack trace when it fails. But, 1-4 should be useful anyhow, I think, for testing and so forth.

Then, there might be some new opcodes that are necessary. I'm not sure what - I would hope that `Atomic_*` etc. are just function calls which should just work, so there must be something else. Or perhaps we don't need a new opcode, and the error is something else? But if it is a new opcode, then that can be added in

a. `tools/emterpretify.py` has the implementations of the opcodes, near the top of the file (`ADD`, etc.). The code for them is a little lower down.
b. `tools/js-optimizer.js` has the translation from asm.js to the opcodes, in `emterpretify()`.

If we don't need a new opcode here, and just some kind of fix, it's likely that would be in (b). A new opcode would need code in both (a) and (b).

I hope this is helpful, let me know how things go.

**Comment by kripken** [comment]
Maybe a longshot, but https://github.com/kripken/emscripten-fastcomp/pull/131 might help here, it makes the Atomics code more "regular" for asm.js. Could be worth trying after that lands.
