### ISSUE TITLE
Precompiled version of EMscripten with Clang 3.6?

### ISSUE THREAD

**Issue by Maher4Ever** [emscripten-core/emscripten#4021]
Hello there,

Is it possible to provide a precompiled SDK based on Clang 3.6? You have one for 3.5 (1.30) and for 3.7 (1.34) but not for the one in the middle,

Thanks in advance.

**Comment by juj** [comment]
Unfortunately we don't have historical releases archived with that version. If you are using emsdk, you can try building various tagged releases with the `./emsdk install sdk-tag-x.yy.z-64bit` where `x.yy.z` is some version between `1.30.0` and `1.34.1` to see if any of those would be closer to what you need. At that time, we were following the PNaCl LLVM/Clang upstream repository, so the upstream updates with respect to LLVM trunk were not that frequent as they are now, when we are directly based on upstream LLVM.
