### ISSUE TITLE
longjmp not caught when being called from emscripten_set_main_loop

### ISSUE THREAD

**Issue by gyf304** [emscripten-core/emscripten#4042]
I commented the original code out and tried a fix. Not certain if is correct.

```
        },runIter:function (func) {
          if (ABORT) return;
          if (Module['preMainLoop']) {
            var preRet = Module['preMainLoop']();
            if (preRet === false) {
              return; // |return false| skips a frame
            }
          }
          try {
            func();
          } catch (e) {
            if (e instanceof ExitStatus) {
              return;
            } else {
              if (typeof e !== 'number' && e !== 'longjmp') throw e;
                asm["setThrew"](1, 0);
              //if (e && typeof e === 'object' && e.stack) Module.printErr('exception thrown: ' + [e, e.stack]);
              //throw e;
            }
          }
          if (Module['postMainLoop']) Module['postMainLoop']();
        }},isFullScreen:false,pointerLock:false,moduleContextCreatedCallbacks:[],workers:[],init:function () {
        if (!Module["preloadPlugins"]) Module["preloadPlugins"] = []; // needs to exist even in workers

```

**Comment by kripken** [comment]
Do you have a minimal testcase showing the issue?

Also, I'm not sure what to look for in that code you pasted?

**Comment by gyf304** [comment]
Here's the minimal test case
Expected output:
```
i = 0
i = 2
```
What actually happens:
Crash with "uncaught longjmp"
```
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include <emscripten.h>

jmp_buf env;

void jmp(){
  longjmp(env, 2);
}

int main()
{
  int i;
  i = setjmp(env);
  printf("i = %d\n", i);

  if (i != 0) exit(0);

  //jmp();
  emscripten_set_main_loop(jmp, 1, 1); // crashes with "uncaught longjmp"
  
  printf("Should not reach here\n");
  return 0;
}
```

**Comment by kripken** [comment]
Thanks, now I see.

The main loop is asynchronous - it's called from the JS event loop, later, after `main()` exits. That means that trying to jump back is an attempt to jump into a stack that has been unwound already, which is undefined behavior, that we don't support (there is no practical way to support it).

I can't think of a good way to improve the error message here, but I'm open to suggestions.

**Comment by gyf304** [comment]
OK, thanks. I understand now. That also explains why trying to jump back yields some weird results. 
I would like to see emscripten having error messages with short descriptions like "setjmp not available in ...", with a link to the page which describes the problem, like what angular.js does.

**Comment by kripken** [comment]
Agreed, but I can't think of a good way offhand. We'd need to maintain some global state "a setjmp was done", then note that we went async, then notice that combination. It seems like a lot of complexity. But, maybe I'm missing something.
