### ISSUE TITLE
Installing git package breaks compilation with cmake+make on Windows 10

### ISSUE THREAD

**Issue by jimon** [emscripten-core/emscripten#4047]
Software :
- clean Windows 10 (no git, no msvs, no mingw, no cygwin, no python)
- latest emsdk installer (tried both online and offline installers)
- sdk-1.35.0-64bit (I installed it to `C:\emscripten`)
- cmake 3.3.2
- gnu make 4.1

For some strange magic absurd reason, if you run `emsdk install git-1.9.4` and `emsdk activate` it breaks compilation with cmake->make completely with exactly the same error as in #3877

**Comment by juj** [comment]
Which CMake generator are you using? The mention of `make` suggests it was `-G Unix Makefiles`? That is not supported or tested on Windows, it is advisable to have MinGW toolchain installed and use `-G MinGW Makefiles` instead.

**Comment by jimon** [comment]
Yes, it was ```-G Unix Makefiles```.
