### ISSUE TITLE
-g4 flag not working

### ISSUE THREAD

**Issue by rtwk** [emscripten-core/emscripten#4049]
For a project I am calling C program files from a node app and creating js files and in turn HTML files. Now this is working properly expect if the C program has some errors (syntax errors), even after using -g4 flag, emcc does not show any error in the HTML file.

**Comment by kripken** [comment]
Please provide more details, it's hard to understand exactly what the problem is that you are seeing.

**Comment by rtwk** [comment]
I am executing "var child = exec("emcc " + fname_c + " --shell-file shell.html  -o " + fname_html);" through 
nodejs. Then I render the said html file which shows output properly. But when the C program is having some syntax error, program just fails to render HTML. I tried by including -g4 in the statement, but in vein.

**Comment by soliton4** [comment]
@rtwk you should probably evaluate the build output and check for compiler errors
