### ISSUE TITLE
Fix llvm_uadd_with_overflow_i64 to detect overflows properly

### ISSUE THREAD

**Issue by SiggyBar** [emscripten-core/emscripten#405]
main.cpp:

``` cpp
#include <stdint.h>

extern uint64_t a, b;

int main(int argc, char *argv[])
{
    if (a > a + b || a > a + b + 1)
        return 1;

    return 0;
}
```

(I know this looks a bit strange, it is a condensed repro from 7zip's lzma extractor.)  And then I compile like this:

```
python em++ -O2 --closure 0 main.cpp
```

The generated JS code for main.cpp is:

``` js
function _main($argc, $argv) {
  var $1$0 = HEAP32[_a >> 2];
  var $1$1 = HEAP32[_a + 4 >> 2];
  var $2$0 = HEAP32[_b >> 2];
  var $2$1 = HEAP32[_b + 4 >> 2];
  var $uadd = _llvm_uadd_with_overflow_i64($1$0, $1$1, $2$0, $2$1);
  var $3 = $uadd.f1;
  do {
    if ($3) {
      var $_0 = 1;
    } else {
      var $5 = $uadd.f0;
      var $6$0 = (i64Math.add($5$0, $5$1, 1, 0), i64Math.result[0]);
      var $6$1 = i64Math.result[1];
      if ($1$1 >>> 0 > $6$1 >>> 0 || $1$1 >>> 0 == $6$1 >>> 0 && $1$0 >>> 0 > $6$0 >>> 0) {
        var $_0 = 1;
        break;
      }
      var $_0 = 0;
    }
  } while (0);
  var $_0;
  return $_0;
  return null;
}
```

There are two problems here:
1. `llvm_uadd_with_overflow_i64` is not implemented in library.js
2. The code uses undeclared variables `$5$0` and `$5$1`.

I do not think it is correct to implement `llvm_uadd_with_overflow_i64` in the same way as `llvm_uadd_with_overflow_i32`, e.g.

``` js
  llvm_uadd_with_overflow_i64: function(x, y) {
    x = x>>>0;
    y = y>>>0;
    return {
      f0: (x+y)>>>0,
      f1: x+y > 18446744073709551615
    };
  },
```

since `18446744073709551615`  is too large to represent in JavaScript's number type (and potentially also `x+y`).

I could not find any tests that exercise `llvm_uadd_with_overflow_i32` and `llvm_umul_with_overflow_i32`.  (See also issues #48 and #108.)

**Comment by juj** [comment]
Is this still an unsupported item? Do we have this as a test case in bug tracker?
