### ISSUE TITLE
Very slow compilation for sha1 implementation in -O2

### ISSUE THREAD

**Issue by SigmundVik** [emscripten-core/emscripten#406]
Compiling this sha1 implementation:
http://svn.peeklinux.com/trunk/qemu/tests/sha1.c

takes more than 20 minutes on my machine with `python emcc -O2 sha1.c`.  With `-s RELOOP=1` it takes a little more than 6 minutes.

(Normally I can compile code that are several orders of magnitude larger in a few minutes.)

The generated code also has very bad performance characteristics, it is more than 100 times slower than when running a native binary.

I know that hand-written sha1 implementations in JavaScript also are slow (about 50 times slower than native code when I last measured).  I was under the impression that bitwise operations mapped pretty well to JavaScript..

One more data point: When I compile 7zip's lzma decoding with Emscripten the generated code runs more than 15 times slower than the native version.

**Comment by MichaelBalazs** [comment]
@kripken / @SiggyBar,

I have a piece of code that needs to leverage sha1 with on the order of 100k+ calls. What are the best optimization settings for compiling sha1.c? 

Crude examination shows I am getting about 4x slower than native using a straight -O2, which is great, but would love to reduce that if possible. 

Thanks

**Comment by kripken** [comment]
`-O3` should be optimal. You can also try `--llvm-lto 1` but it is risky.

Which browser is the 4x number on? How do others compare?

**Comment by MichaelBalazs** [comment]
Both seem to have helped a small amount. However, both improvements might
be within statistic fluctuations.

I had been testing with node for ease, but switching to Firefox made it
only about 2x slower. I can work with that.

Thanks,
Michael
