### ISSUE TITLE
Assume native optimizer?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#4067]
Right now everything in the native optimizer in C++ can be run by the JS optimizer in JS. If we decided to assume the native optimizer must always work, then we could remove all the duplicate code and leave just the C++ side of things.

(We would still need the JS optimizer because there are many passes that are only there, and not duplicated. It is also very useful for prototyping, etc.)

The risk is that we use a C++ compiler to build the native optimizer, and it requires c++11. We've had reports of issues in the past. Not sure if there still are any.

Thoughts?

**Comment by juj** [comment]
There was this commit https://github.com/kripken/emscripten/commit/d3c384d133ed234f15cccddefd6f64bbce1ed251 to add support at least to GCC 4.6 to build via the earlier `-std=c++0x` flag, which might improve the historical coverage a bit.
