### ISSUE TITLE
memset is extremely slow

### ISSUE THREAD

**Issue by shooshx** [emscripten-core/emscripten#4098]
In my particular program
http://shooshx.github.io/happysolver/emscripten/index.html
compiled with -O3, under Chrome profiler, run-time is dominated by calls to memset()
when I compile this code for native x86-64, this memset() barely registers in the Visual Studio profiler and the program runs about 4 times faster.
Are there any plans for making memset() be something better than a simple loop?
Is there any workaround I can use?

**Comment by kripken** [comment]
Native `memset` can use SIMD instructions which JS engines don't yet. That could explain part of this. SIMD is coming to browsers, though, so this is just for now.

I tried to verify, though, and I don't see the same as you. The profile is mostly graphics, glReadPixels and glDrawElements. That's on firefox, so perhaps there is a specific chrome issue here?

Which memset is hitting this problem? Might be a specific workaround depending on the arguments it's called with, etc.

**Comment by shooshx** [comment]
Well, actually, if you want to make that program grind, you need to build a bigger structure, otherwise it just sits idle. You add a cube by double clicking on an existing face of a cube. Try this bigger structure, watch the CPU climb to 100% and start the chrome profiler

![grind](https://cloud.githubusercontent.com/assets/1285088/13030444/291b0f5c-d2b4-11e5-8ef0-9282fe708f1e.png)

**Comment by kripken** [comment]
Ok, I tried that bigger shape and now I see almost 7% in `memset`, which does seem high. But I see 30% in `makePossibilities2`, and a few others are higher than `memset` as well. Looks similar in the firefox and chrome profilers. (this is on dev versions of those browsers)

With what kind of values is memset called there? If it's called with 1 for the number of bytes, maybe the function call overhead is already most of the effect.

**Comment by shooshx** [comment]
memset() is called with the value of 916 bytes, filling zeros.
For reference, I checked again and the Visual Studio profiler shows memset() at 0.02% - 2 samples out of 8500.
I'm guessing that another factor that is in effect here is that in the native compiled run, all of the data used by the algorithm is kept hot in the L1 cache and that's unlikely to be the case with JS.

Question - isn't it possible for memset() to just use Int32Array.fill()? isn't that function implemented in C?

**Comment by shooshx** [comment]
Well, I just tested replacing that memset() with HEAP32.fill() and oddly enough, it produced exactly the same result. O_o

**Comment by kripken** [comment]
Might be sensitive to the benchmark. I've been testing over here too, with this gist, https://gist.github.com/kripken/81d32fbf0073b70573da

It looks like `fill` is around twice as fast! Looks promising, but need to test more.

**Comment by kripken** [comment]
It is indeed faster in firefox, but slower in chrome.

We should file a bug on chrome to see why that is, and figure out what the optimal solution here is. Marking as "good first bug" - the next task here is to double-check the benchmark, file an issue on v8, and report the feedback.

**Comment by juj** [comment]
Hey, we just landed optimizations to `memset`, see #4924. Perhaps this can help here?
