### ISSUE TITLE
Serious problem with generateStructInfo

### ISSUE THREAD

**Issue by apatrushev** [emscripten-core/emscripten#410]
I'm trying to compile unrar and encountered a big problem. I can't reproduce it on small piece of code. Below some description of reproducing problem on unrar codebase.

Unrar source code: http://www.rarlab.com/rar/unrarsrc-4.1.4.tar.gz

Compile minimal set of code reproducing a bug (problem reproduced on full set of code, also).

```
emcc -c file.cpp
emcc -c find.cpp
emcc -c cmddata.cpp
emcc -c rar.cpp
```

Let's see on some strange behaviour:

```
emcc -o res.bc file.o find.o cmddata.o rar.o
llvm-dis res.bc
grep "^%struct.stat" res.ll

>>>
%struct.stat = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [2 x i32] }
%struct.stat.3 = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [2 x i32] }
```

As you can see we have two different %struct.stat here.

And later when we make "global dead code elimination":

```
opt -internalize -globaldce res.bc -o res.opt.bc; mv res.opt.bc res.bc
llvm-dis res.bc
grep "^%struct.stat" res.ll
>>>
%struct.stat.3 = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [2 x i32] }
```

, only second version of %struct.stat is left.

And no __stat_struct_layout in resulting JavaScript.

How I can fix this problem ? It's too hard for me to explore deeper... :(

**Comment by kirkouimet** [comment]
@apatrushev did you have any luck getting unrar to work with emscripten?
