### ISSUE TITLE
SDL DOM event binding

### ISSUE THREAD

**Issue by GGAlanSmithee** [emscripten-core/emscripten#4106]
Calling `SDL_Init()` initializes `key(down|up)` event listeners in such a way that it prevents the events from bubbling. This has the consequence that it renders `input` elements etc. useless. It is possible to opt-out of this behaviour by setting `Module['doNotCaptureKeyboard'] = true;`, but this removes all SDL keyboard events. In other words, you are either all in or all out regarding handling keyboard events via SDL or the browser.

In [this SO thread](http://stackoverflow.com/questions/13892688/emscripten-call-to-sdl-init-freezes-browser-textinput), @kripken [makes the point](http://stackoverflow.com/a/13898042/3303776) that events are bound to the page in order to handle situations like full screen games etc, which is a fair point. It seems to me that the current behaviour favors the usecase of porting C++ games, ie you don't care to much about browser synergy. However it doesn't really handle the usecase of treating the canvas as just a part of a page, where part of user input could be handled by leveraging standard HTML and JS techniques.

A concrete example for this is a chat, which is trivial to implement with standard browser techniques, such as HTML input elements and JS events, but considerably harder to implement in the context of a game loop. This kind of event based functionality just lends itself very well to how browsers works.

In order to better support the "browser synergy" usecase, I suggest the following changes:
- Either
  - add an option to bind events to a canvas by `Module['captureKeyboardOnCanvas'] = true;` or 
  - don't prevent the page-bound events from bubbling, allowing other elements to function
- Add document for this behaviour, since it's as far as I can tell not documented atm

**Comment by kripken** [comment]
First option sounds good, that is, adding an option for this. But maybe it can fit in with the HTML5 API stuff (so it's not just SDL1), @juj, what do you think?
