### ISSUE TITLE
Overloading by Type in webIDL 

### ISSUE THREAD

**Issue by chepilot** [emscripten-core/emscripten#4115]
Hi,

Trying to write webIDL for a class with constructors differentiated by argument type but with the same argument number.

It gives me the assertionError during the glue phase:

```
assert i not in sigs, 'overloading must differentiate by # of arguments 
(cannot have two signatures that differ by types but not by length)'
AssertionError: overloading must differentiate by # of arguments 
(cannot have two signatures that differ by types but not by length)
```

Does it mean that webIDL doesn't support overloading by type?
Is there a way to resolve this issue?

Thanks!

**Comment by kripken** [comment]
That's an existing limitation, yes. We could add runtime code to do type checking for this, but it's complicated and would add runtime overhead, and no one has experimented with it as far as I know.
