### ISSUE TITLE
webIDL macro 

### ISSUE THREAD

**Issue by chepilot** [emscripten-core/emscripten#4116]
Hi, 

Not so sure if it is appropriate to post it here, but I couldn't find a solution for this anywhere else.
I have a macro to expose in webIDL:

```
# define   Handle(ClassName)      Handle_##ClassName
```

The usage in C++ would be:

```
  Handle(Geom_TrimmedCurve) aSegment1 = GC_MakeSegment(arg1, arg2);
```

I wonder how I can write webIDL for this and what would be the usage method in javascript.

Thank you very much!

**Comment by kripken** [comment]
We don't have macro binding support. Maybe I'm missing an easy solution but it doesn't seem easy to support. Instead, if you can wrap usages of the macro in C/C++ and bind those, that would be a workaround.
