### ISSUE TITLE
Old safe heap alignment error message is more descriptive than the new one.

### ISSUE THREAD

**Issue by marc40000** [emscripten-core/emscripten#4118]
Whenever I use -s SAFE_HEAP=1 and I get an alignment issue, the error message I get always just says "alignment fault"

Replacing 

```
asm_safe_heap = settings['SAFE_HEAP'] and not settings['SAFE_HEAP_LOG'] and not settings['RELOCATABLE'] # optimized safe heap in asm, when we can
```

by

```
asm_safe_heap = False
```

in emscripten.py, the error message is more descriptive, telling me for example

"alignment error storing to address 7617, which was expected to be aligned to a multiple of 4"

I'm using emsdk-1.35.0-portable-64bit.zip

Simple testcase, compile without optimizations:

```

int main(int argc, char * argv[])
{
    char b[5];
    *((int*)(b + 1)) = 5;
    printf("alignment test %u\n", *((int*)(b + 1)));
}

```

**Comment by kripken** [comment]
It was simpler to not do this when moving the code into asm.js for speed. But we could add it, by calling out to print the error, adding an import like `safe_heap_print_error`. Should be fairly easy to add if someone wants to.
