### ISSUE TITLE
Error is not obvious when VS2013/VS2015 is not installed

### ISSUE THREAD

**Issue by gouletr** [emscripten-core/emscripten#4120]
Activating Emscripten built elsewhere on another machine that only have VS2012 installed, it doesn't set `LLVM_ROOT` property, ending up with the following error when trying to build with Emscripten later. I understand Emscripten requires VS2013 or above, but perhaps it would be nice to error out earlier because it wasn't obvious why the build failed.

```
Traceback (most recent call last):
  File "D:\dev\stingray\lib\emscripten-1.35.20-r0\emscripten\tag-1.35.20\\em++", line 11, in <module>
    import emcc
  File "D:\dev\stingray\lib\emscripten-1.35.20-r0\emscripten\tag-1.35.20\emcc.py", line 28, in <module>
    from tools import shared, jsrun, system_libs
  File "D:\dev\stingray\lib\emscripten-1.35.20-r0\emscripten\tag-1.35.20\tools\shared.py", line 656, in <module>
    CLANG_CC=os.path.expanduser(build_clang_tool_path('clang'))
  File "D:\dev\stingray\lib\emscripten-1.35.20-r0\emscripten\tag-1.35.20\tools\shared.py", line 582, in build_clang_tool_path
    return os.path.join(LLVM_ROOT, tool)
NameError: global name 'LLVM_ROOT' is not defined
```

**Comment by juj** [comment]
Hmm, this is something else. I think if you do build that tag with VS2013 on one computer, and then zip up the emsdk directory(?), and then `emsdk activate sdk-tag-1.35.31-64bit` on the computer you migrate it to, it should work even if the system does not have any Visual Studio installed (presuming that the correct VC redist runtimes are still present). What is the full result of `emsdk activate sdk-tag-1.35.31-64bit` on that system?

**Comment by gouletr** [comment]
The system with VS2012 only output this upon `emsdk activate --build=Release --global`:
```
Registering active Emscripten environment globally for all users.

Writing .emscripten configuration file to user home directory C:\Users\test/
The Emscripten configuration file C:\Users\test\.emscripten has been rewritten with the following contents:

import os
NODE_JS='d:/dev/lib/emscripten-1.35.20-r0/node/4.1.1_64bit/bin/node'
PYTHON='d:/dev/lib/emscripten-1.35.20-r0/python/2.7.5.3_64bit/python.exe'
JAVA='d:/dev/lib/emscripten-1.35.20-r0/java/7.45_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='d:/dev/lib/emscripten-1.35.20-r0/emscripten/tag-1.35.20'
EMSCRIPTEN_NATIVE_OPTIMIZER='d:/dev/lib/emscripten-1.35.20-r0/emscripten/tag-1.35.20_64bit_optimizer/Release/optimizer.exe'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/test/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Adding directories to PATH:
PATH += d:\dev\lib\emscripten-1.35.20-r0
PATH += d:\dev\lib\emscripten-1.35.20-r0\node\4.1.1_64bit\bin
PATH += d:\dev\lib\emscripten-1.35.20-r0\python\2.7.5.3_64bit
PATH += d:\dev\lib\emscripten-1.35.20-r0\java\7.45_64bit\bin
PATH += d:\dev\lib\emscripten-1.35.20-r0\emscripten\tag-1.35.20

Setting environment variables:
EM_CONFIG = C:\Users\test\.emscripten
```
After installing VS2015, the following lines appears in addition to the above, when re-activating:
```
LLVM_ROOT='d:/dev/lib/emscripten-1.35.20-r0/clang/tag-e1.35.20/build_tag-e1.35.20_vs2013_64/Release/bin'
...
PATH += d:\dev\lib\emscripten-1.35.20-r0\clang\tag-e1.35.20\build_tag-e1.35.20_vs2013_64\Release\bin
```
So if we don't need Visual Studio at all, then there must be an issue preventing the emsdk script to properly get the clang folder within the Emscripten build?

**Comment by gouletr** [comment]
Forgot to mention, yes we built Emscripten on another system, and the error happens on the system we migrate to.

**Comment by juj** [comment]
Oh, on the VS2012 system, did you run "emsdk activate sdk-tag-1.35.20-64bit` or just `emsdk activate emscripten-tag-1.35.20-64bit`?

**Comment by gouletr** [comment]
`emsdk activate sdk-tag-1.35.20-64bit`
