### ISSUE TITLE
Pass string from JS to C++ lib 

### ISSUE THREAD

**Issue by Valerun666** [emscripten-core/emscripten#4131]
Hi. Got really big troubles with passing JS string to C++ lib compiled with Emscripten. What exactly I did:
1. there is a C++ lib with method:

void printString(char \* str) {
    std::cout << str << std::endl;
}

I try to pass JS String to this method in such way:

var em_module = require('./res.js');

var str = "TEST";

var buffer = em_module._malloc(str.length + 1);
em_module.writeStringToMemory(str, buffer);
em_module.ccall('printString', 'null',['string'], buffer);

But as a result I receive something like this: ￀�...

Can you explain what I am doing wrong with transferring strings from JS to C++ part?

**Comment by kripken** [comment]
That looks correct. So you might have a typo somewhere. Perhaps create a gist with a full runnable example of what you are doing, and we can try to reproduce the problem and debug it?

**Comment by kripken** [comment]
Actually one possible issue is that you use `'string'` as the input type. For that, you can just pass in the string itself. If you write to a C buffer yourself manually as you do, you can pass it as a `'number'`.

**Comment by Valerun666** [comment]
Runnable example:

res.cpp:

#include <iostream>

extern "C" {
	void printString(char * str) {
		std::cout << str << std::endl;
	}
}

test.js:
var em_module = require('./a.out.js');

var str = "TEST";
var buffer = em_module._malloc(str.length + 1);
em_module.writeStringToMemory(str, buffer);
em_module.ccall('printString', 'null','number', buffer);

**Comment by kripken** [comment]
Did my suggestion in the last comment not help?

If not, please create a gist or use escaping (four ` before and after0 on that example, so it is readable.

**Comment by Valerun666** [comment]
Unfortunately no. No result. Tried to put as you suggested 'number', but nothing.



res.cpp:

#include <iostream>

extern "C" {
    void printString(char * str) {
        std::cout << str << std::endl;
    }
}




test.js:

var em_module = require('./a.out.js');

var str = "TEST";
var buffer = em_module._malloc(str.length + 1);
em_module.writeStringToMemory(str, buffer);
em_module.ccall('printString', 'null',['number'], buffer);

**Comment by kripken** [comment]
1. I think you have a typo, `end` should be `endl`?
2. You need to export that function to keep it alive. You didn't mention the command you used to build, so I'm not sure if you did that or not.
3. The main problem was a typo near the end, you need `[buffer]` and not `buffer`. The last argument is a list of parameters. It happens that you have just one here, so it's easy to forget that, but the syntax doesn't special-case 1 argument.

**Comment by kripken** [comment]
Looks like we have that mistake in one place in our docs. Fixing now.
