### ISSUE TITLE
SDL2 with error on built

### ISSUE THREAD

**Issue by mockthebear** [emscripten-core/emscripten#4132]
Well, i was working in a project i had compiled before using emscripten.
One day, sudenlly, it get an error on SDL lib, without i changing anything in my original code.

i have tried reinstaling the emsdk, but still the same errors:

`n file included from C:\Users\Mock.emscripten_cache\ports-builds\sdl2\include\SDL.h:48:
C:\Users\Mock.emscripten_cache\ports-builds\sdl2\include/SDL_log.h:140:30: error: variable has incomplete type 'void'
extern DECLSPEC void SDLCALL SDL_Log(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
                             ^
C:\Users\Mock.emscripten_cache\ports-builds\sdl2\include/SDL_log.h:140:38: error: use of undeclared identifier 'SDL_PRINTF_FORMAT_STRING'
extern DECLSPEC void SDLCALL SDL_Log(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
                                     ^
C:\Users\Mock.emscripten_cache\ports-builds\sdl2\include/SDL_log.h:140:80: error: expected expression
extern DECLSPEC void SDLCALL SDL_Log(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
                                                                               ^
C:\Users\Mock.emscripten_cache\ports-builds\sdl2\include/SDL_log.h:140:84: error: expected ';' after top level declarator
extern DECLSPEC void SDLCALL SDL_Log(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);

<and errors go on>`

http://pastebin.com/yfr5i3Ua

Seriously, i have no idea whats going on
When i build it for the first time: http://hungrybear.com.br/ld34/snakescape.html
Now i just ran the script to build again, and get this... whats wrong?

**Comment by lamelizard** [comment]
I'm not quite sure if this is the same issue, but I had the exact same error messages after I tried to switch to the Emscripten version of SDL_mixer (When I'm building it myself (version 2 of SDL_mixer) everything just works fine). I'm not sure if SDL_mixer is what's causing causing your errors, but it could?
Note: I'm using the SDL2 port from Emscripten.

**Comment by lamelizard** [comment]
I looked a bit more into it. My program compiles fine after I made sure that I do not include the SDL_mixer.h before SDL.h. Do you include SDL.h after a SDL addon or after emscripten.h?

**Comment by mockthebear** [comment]
WOW. thats an strange bug! it worked!

<3
