### ISSUE TITLE
Query string to command line args? (feature proposal)

### ISSUE THREAD

**Issue by mtarini** [emscripten-core/emscripten#4149]
Apologies for hijacking the Issues section---this is not really an _issue_, it is more of a _feature proposal_. Also, apologies if this was already considered (and maybe decided against?)---not that it seemed to be.

Anyway, the title says it all: it would (superficially?) seem to make a lot of sense if 
**the URL of the web page was fed to the C++ `main` as args,** instead of the current default string. 
###### Details:

`argv[0]`, would be assigned to the URL without the query string (i.e. up to the `?`), and the other `argv` would be the "query string", as separated by the usual `&`. 
Not sure about the `=` (because command line args do not came, by default, as label+value pairs). See the alternative variations below.
###### Example:

A web page loaded from:
    `http://www.example.com/index.html?aaa=12&bbb=15`
would produce one of three things.

Variation 1:
    `argc` : `3`
    `argv` : `{ "http://www.example.com/index.html" , "aaa=12" , "bbb=15" }`

Variation 2: 
    `argc` : `5`
    `argv` : `{ "http://www.example.com/index.html" , "aaa" , "12" , "bbb" , "15" }`

Variation 3: _(striving to map a common practice into another)_
    `argc` : `5`
    `argv` : `{ "http://www.example.com/index.html" , "-aaa" , "12" , "-bbb" , "15" }`  

Note the extra `-` signs in the last variation, making the same source produce both a command line application and a web application accepting end-user input equally neatly... in the example, 
`./myProgram -aaa 12 -bbb 15` 
is probably the most sensible 'command line equivalent' of the URL above

I, for one, would have many great uses for something like this. 
Then again, I'm new to Emscripten and I might fail to see reasons against this.

**Comment by juj** [comment]
You can do this yourself by specifying something like `Module['arguments'] = window.location.search.substr(1).split('&')` in your shell file. That is where startup args are read from to be passed to main().

I have no objections against doing this for the default shell file. This has been discussed in a few occassions in the past, but I think the thinking has been indifferent for this, since it was so easy to do it manually. @kripken : what do you think?

**Comment by kripken** [comment]
Yeah, easy to do manually, and surprising if the user didn't want it, is my take on this.
