### ISSUE TITLE
File_packager.py generated assets.data XHR code doesn't allow developer to react to network errors.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4153]
In our current form of XHR being performed by the code generated by `tools/file_packager.py` at https://github.com/kripken/emscripten/blob/incoming/tools/file_packager.py#L658, we simply throw an exception when an error occurs.

We should have some kind of machinery to allow user to do custom logic for network errors, e.g. if there are transient network failures due to poor network conditions or something else. One might want to retry a few times, or use a custom timeout mechanism (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout)

Not sure what would be the best way to make this more flexible. Perhaps we should do the thing we do with memory initializer, and allow user to pre-download the XHR and feed that in. That would allow the developer to treat the XHR manually the way he likes.

However, if we do that, should allow some mechanism to inject into the indexedDB caching mechanism? Or should that be on the developer's burden as well if he wants to treat the XHR manually?

**Comment by kripken** [comment]
Yes, like mem init, I suppose we could let people provide us with the xhr itself, and then they can handle it however they want. Yes I think if so, they would be in charge of caching themselves too.
