### ISSUE TITLE
C++ callback dies inside emscripten::val#call

### ISSUE THREAD

**Issue by AndriiHeonia** [emscripten-core/emscripten#4154]
I'm working on product which is based on Emscripten and recently I stuck with one problem.

What I need to do:
1. from the C++ code I want to call method of the JS object and pass callback (which is C++ object) as a parameter;
2. when my JS method receives data from the server I want to call my C++ callback.

I wrote some demo code which represents my problem, you can find it [here](https://github.com/AndriiHeonia/async-emcc/tree/master). The problem is that at [this moment](https://github.com/AndriiHeonia/async-emcc/blob/master/index.html#L23) my callback is already dead and I can't call it (BindingError: Cannot pass deleted object as a pointer of type Callback*). How can I keep it alive and call asynchronously?

Also I tried to write workaround without emscripten::val#call and it works (you can see the code [here](https://github.com/AndriiHeonia/async-emcc/tree/em_asm)) but [this](https://github.com/AndriiHeonia/async-emcc/blob/em_asm/index.html#L18) signature of JS method is unacceptable for our product. Another problem with workaround is that I lose context ('this' inside sendRequest points to the wrong object).

Thank you in advance!

**Comment by MegaJsTeam** [comment]
javascript function has method "call"

callback.call<void>("call", this, 1, 2, 3)

**Comment by k2snowman69** [comment]
I literally just ran into a similar problem and was stumped for about two months... and then I finally found a little gem of a solution which just worked for me called `clone`. Applying it to your code it would look like this:

      // we call this function from C++ code
      var callbackHolder = null;
      var requestManager = {
        sendRequest: function(callback) {
          console.log('call callback synchronously');
          callback["sayHi"]();
          callbackHolder = callback.clone(); // Clone the callback so you can maintain a handle on the pointer

          setTimeout(function() {
            console.log('call callback asynchronously');
            // TODO: how to keep callback alive?
            callbackHolder["sayHi"]();
            callbackHolder.delete(); // Don't forget to delete the cloned object or you may run into memory leaks
          }, 100);
        }
      };

I didn't try it with your code specifically but doing a similar thing for my code solved my problem.
