### ISSUE TITLE
Emterpreter emulating pthreads

### ISSUE THREAD

**Issue by aidanhs** [emscripten-core/emscripten#4162]
A conversation on IRC sparked this thought - could the emterpreter be extended to support multithreading? Since it has complete control of the stack it can presumably context switch whenever it likes.

I'm not sure what the timeline currently looks like for pthreads in release versions of browsers - if it's only a couple of months out then there's no point. But if it's going to be 6 months or more then it seems like it could be an interesting experiment. Has this been considered before? Any technical complexities?

**Comment by kripken** [comment]
Yes, this could be done. I'd be very happy to see it happen, I just don't have enough time myself to do it.

My guess is that there is a very good chance that native pthreads in browsers will take more than 6 months. There is a workable implementation in firefox nightly and perhaps also chrome canary as well, but there isn't a date for when those will reach stable browsers - the spec isn't finalized yet.

**Comment by aidanhs** [comment]
Cool, I currently have a few different ongoing emscripten side projects so I might take a look at this when I get one done.

**Comment by aidanhs** [comment]
Possibly sort-of related - #4018
