### ISSUE TITLE
PhysFS library not working when compiled using Emscripten

### ISSUE THREAD

**Issue by Alexander-r** [emscripten-core/emscripten#4167]
I was trying to build a project that uses PhysFS library using Emscripten.

PhysFS is a library that provides access to files stored in archives. It is used by some games and game engines. More information can be found at https://icculus.org/physfs/.

I was able to build a project but I get errors at runtime when I try to access the files. The same project works if it is compiled on desktop using gcc (tested on version 5.3.0) and clang (tested on version 3.7.1) and does not produce any warnings.

The source code and the build script that I used to test this error can be found at:
https://www.dropbox.com/s/hg9zx0m7auy8lw5/physfstest.tar.gz?dl=1

This are the errors that I get when I try to open the project compiled using Emscripten 1.36.0 in Firefox 45.0:

```
Invalid function pointer '3' called with signature 'viiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)

This pointer might make sense in another type signature: viii: 0  vii: undefined  vi: _ZIP_destroy  v: undefined  iiii: _ZIP_openArchive  iiiii: _nativeIo_read  iii: _DIR_openAppend  ii: _ZIP_duplicate  i: undefined
```

This error occures in file physfstest/physfs/src/physfs.c around line 2328:

```
i->funcs->enumerateFiles(i->opaque, arcfname,
                         callback, _fname, data);
```

i->funcs is a structure that contains pointers to functions that perform operations on different archive types. For zip archives the implementation is located in archiver_zip.c. The functions have the same signatures for all archive types and are located in physfs.h.

What can cause this problem and how can it be fixed?

**Comment by kripken** [comment]
The docs here might help: http://kripken.github.io/emscripten-site/docs/porting/guidelines/function_pointer_issues.html

**Comment by Alexander-r** [comment]
Thank you for the link.
After adding -s EMULATE_FUNCTION_POINTER_CASTS=1 I did not get the errors. But now when I run it the program acts as if there are no files in the archive. And if I just list the files in the root dirictory of Emscripten virtual file system I see the archive that I added with --preload-file so the programm should be able to open it or at least give an error.
Is there any way to check which function was called when the archive was opened to see if EMULATE_FUNCTION_POINTER_CASTS is working?

**Comment by kripken** [comment]
You can add some debug printing directly in the code, using `console.log`. That's helpful if you know the called function is one of a small set.

Otherwise, you can build the app with the [autodebugger](https://kripken.github.io/emscripten-site/docs/porting/Debugging.html#debugging-autodebugger) which adds tons of logging everywhere. Then you can look in the code to see (e.g. if `AD|3125,0` is printed, search for 3125 in the source, and you should find a call to `emscripten_autodebug` etc.).
