### ISSUE TITLE
Make emscripten/wire.h work with -fno-rtti

### ISSUE THREAD

**Issue by Matheus28** [emscripten-core/emscripten#4187]
Currently, `emscripten/wire.h` has a fallback that doesn't use `typeid`, however, the condition for using the fallback is `!(has_unbound_type_names || std::is_polymorphic<C>::value)`. The problem is that it still fails to compile if you have `-fno-rtti` in the build options. A fix for that would be checking if `__GXX_RTTI` is not defined and using the fallback `LightTypeID`.

**Comment by kripken** [comment]
cc @waywardmonkeys

**Comment by xor2k** [comment]
I have made a pull request to address this issue: https://github.com/kripken/emscripten/pull/5356
