### ISSUE TITLE
Why SDL2 port use old SDL_config.h.cmake?

### ISSUE THREAD

**Issue by weitjong** [emscripten-core/emscripten#4191]
I don't know if this question or issue has been asked before (I have tried to search for it and found nothing). Anyway, the reason I ask this because I found out that the generated `SDL_config.h` file in the `~/.emscripten_cache/ports-builds/sdl2/include` has a wrong copyright year. Of course, the actual year is not important here but it means that all the compiler defines found in that file may not be as up to date as one would think. In our project we have tried to use a modified version of SDL own CMakeLists.txt to build the SDL library using Emscripten compiler toolchain. We need a way to verify the generated `SDL_config.h` so I try to diff it with Emscripten SDL2 port and surprise to find the discrepancy. I can only guess that somehow Emscripten SDL2 port is still using an old version of `SDL_config.h.cmake` file to generate the `SDL_config.h` file.

**Comment by kripken** [comment]
This should be ok, although perhaps I'm missing something.

Basically, we are a cross-compiler, so we don't need a config.h that is custom for each machine. We just use on portable one (we are always a 32-bit target, always use the same libc, etc.). And it should also be portable between versions of emscripten. In other words, it should be fine to use an old one, unless some compiler feature changed in a surprising way.

**Comment by weitjong** [comment]
Thanks for prompt reply. I think I understand what you are saying. It explains why the generated header appears to be different than the one that should be generated by CMake. There is even a case where the old/portable one is more correct, e.g the setting for GCC_ATOMIC/SDL_ATOMIC. I guess the only drawback with the current approach is it may mask out setting mistake in the SDL CMakeLists.txt because in essence its generated config header is being discarded.
