### ISSUE TITLE
C++ switch blocks and jump tables

### ISSUE THREAD

**Issue by reubenscratton** [emscripten-core/emscripten#4198]
I've ported a 6502-based emulator project to Emscripten and wanted to share the little trouble I had getting satisfactory performance on mobile browsers.

The core of the 6502 emulator code is a 256-entry 'switch' statement which, when compiled with LLVM and run natively on ARM and X86, always uses a jump table - even in debug mode and without any optimisation flags. 

But with Emscripten I tried all the optimisation flags but would always end up with a huge 256-entry switch block in the emitted javascript. Performance on all browsers save Firefox was dismal. 

So I tried to force the use of a jump table by changing my C++ 'switch' to a table of label values, i.e.  `static void* jump_table[] = {&&op00, &&op01, ..., &&opFF};`. But I was very surprised when Emscripten _still_ emitted the same huge switch block!

Next I tried to use a function table rather than a jump table, and luckily this worked. My framerate instantly leapt from 35fps on an iPhone 6S (Safari) to the full 60fps. 

So, problem solved, but I thought I'd report the experience anyway as it feels like it's something that should maybe have worked right first go. And while I know Javascript engines _could_ theoretically use jump tables when executing a switch block, I don't see any evidence that they do.

**Comment by kripken** [comment]
What did the function table compile to? An indirect call based on a table, I guess? If so I suppose that's a workaround for generating a switch, although in theory LLVM might optimize out the indirect call, and you'd still get a switch.

In any case, the good news is that in Firefox and Edge asm.js switches are guaranteed to be properly optimized. That will happen in Chrome and Safari as well in WebAssembly.

**Comment by reubenscratton** [comment]
A look at the emitted javascript shows what gets produced is pretty much exactly as hoped for:

`var FUNCTION_TABLE_vi = [b2,_op0x00,_op0x01,_op0x02, ... `

(No idea what 'b2' is, maybe it's there to catch array index -1?)

**Comment by kripken** [comment]
Index 0. Function pointer 0 can't be a valid function pointer, and we need to place some function there, so `b2` will abort if called.
