### ISSUE TITLE
Execute code before main() aka. run()

### ISSUE THREAD

**Issue by IngwiePhoenix** [emscripten-core/emscripten#4202]
I want to run my JS code externaly from my C++ code, so that I can just add the JS code in. In my example, it translates the real ENV into the virtual ENV, and mounts top-level dirs to enable "real" `fopen()` and such. Unfortunately, neither `--pre-js` nor `--post-js` can do that, and `--js-library` seems to make my code execute somewhere very early... So what can I do to enforce my code to run just before the `int main()` is executed?

**Comment by kripken** [comment]
Code in a `--pre-js` will literally be added before the rest of the emitted code, so it has to execute earlier. Unless it only creates a callback for later, of course. A relevant callback you might want to use is [preRun](http://kripken.github.io/emscripten-site/docs/api_reference/module.html?highlight=prerun#Module.preRun).

**Comment by IngwiePhoenix** [comment]
I am currently trying a combination of `-s INVOKE_RUN=0` and `--post-js`.

What I am actually trying to achieve is to run this bit of code _just before main() is executed_:

```javascript
function debugLog(str) {
    if(process.env.DEBUG) {
        process.stdout.write('[IceTea:Emscripten]: '+str+'\n');
    }
}

// Make the ENV available.
for(var name in process.env) {
    ENV[name] = process.env[name];
}

// Mount the paths
var path = require('path');
var fs = require("fs");
var list = fs.readdirSync(path.resolve('/'));
list.forEach(function(item){
    var p = path.join('/', item);
    var stat = fs.lstatSync(p);
    if(stat.isDirectory()) {
        debugLog('Mounting...');
        try {
            debugLog('mkdir('+p+')');
            FS.mkdir(p);
            debugLog('mount('+p+')');
            FS.mount(NODEFS, {root: p}, p);
        } catch(e) {
            debugLog("Skipped");
        }
    }
});
FS.chdir(process.cwd());
```

It simply translates the ENV vars and chdirs into the current folder after mounting pretty much everything in. Its sort of a hackish aproach, but being aware that the code only runs on Node, this actually works very fine when embedded in C++ source. But since I want to trick another tool (incbin) into using the FS correctly, I need to run this bit of code before it's main() too. So I am trying to inject this piece of code as a way to run before main().

So far, I hard-modified the output and tried to use `addOnPreRun` or just `Module.preRun.push`. At both, I'd get `ENV not defined`. Then I just removed these alltogether and instead the above setting and tried to call `run()` manually, and seeing as that didn't work, i tried to `Module.callMain(Module.arguments)` but to no avail.

In most cases, it's just that `ENV` is not defined. But I thought it was a global variable... So I am  pretty lost here.

Any idea how I could inject that code so it'd run before `main()`?

**Comment by IngwiePhoenix** [comment]
Looks like that actually _was_ the right track.

Using `-s INVOKE_MAIN=0` and calling it manually, that works. what I didn't consider was that the ENV library might not actually be included since `getenv` and alike were not used. So, this is what it looks like:

```
Ingwie@Ingwies-MBP.Speedport_W723_V_Typ_A_1_01_012 ~/W/IceTea $ cat src/icetea-emscripten.js
if(!ENVIRONMENT_IS_NODE) {
    throw new Error("Can only run on NodeJS!");
}

function debugLog(str) {
    if(process.env.DEBUG) {
        process.stdout.write('[IceTea:Emscripten]: '+str+'\n');
    }
}

if(typeof ENV != "undefined") {
    // Make the ENV available.
    for(var name in process.env) {
        ENV[name] = process.env[name];
    }
}

// Mount the paths
var path = require('path');
var fs = require("fs");
var list = fs.readdirSync(path.resolve('/'));
list.forEach(function(item){
    var p = path.join('/', item);
    var stat = fs.lstatSync(p);
    if(stat.isDirectory()) {
        debugLog('Mounting...');
        try {
            debugLog('mkdir('+p+')');
            FS.mkdir(p);
            debugLog('mount('+p+')');
            FS.mount(NODEFS, {root: p}, p);
        } catch(e) {
            debugLog("Skipped");
        }
    }
});

// Navigate to current folder
FS.chdir(process.cwd());

// Call main
Module.callMain(Module.arguments);
postRun();
Ingwie@Ingwies-MBP.Speedport_W723_V_Typ_A_1_01_012 ~/W/IceTea $ emcc -s INVOKE_RUN=0 --post-js src/icetea-emscripten.js -I deps/incbin/ deps/incbin/incbin.c -o incbin.js
deps/incbin/incbin.c:103:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
Ingwie@Ingwies-MBP.Speedport_W723_V_Typ_A_1_01_012 ~/W/IceTea $ node incbin.js src/scripts.rc -o out/scripts.js.c
included `src/scripts.rc'
generated `out/scripts.js.c'
```

I wish there was an easier solution... :) But it works!

**Comment by kripken** [comment]
Might be helpful to look at the code in `src/postamble.js` which calls the callbacks during run. In particular, `preMain()` will call functions added via `addOnPreMain` right before main.
