### ISSUE TITLE
SDL_FreeSurface crash on some images

### ISSUE THREAD

**Issue by newnon** [emscripten-core/emscripten#4210]
SDL_Surface *iSurf = IMG_Load(_filePath.c_str());
SDL_FreeSurface(iSurf);

100% crash on some png(example png)
![helloworld](https://cloud.githubusercontent.com/assets/5040118/14141249/ae967cf2-f686-11e5-93d4-126bd89f5e0d.png)

this png has no alpha

**Comment by kripken** [comment]
What is the crash error message? Which browser does it crash on? What build command was used?

**Comment by eukarpov** [comment]
you need to check a return value after IMG_Load
```
if(!iSurf)
    printf("IMG_Load: %s\n", IMG_GetError());
```
