### ISSUE TITLE
embind's std::string marshalling is hardcoded to Latin-1

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#4221]
Per [this email thread](https://groups.google.com/forum/#!topic/emscripten-discuss/mhy4pkudm9k), marshaling of std::string values to/from JavaScript is currently hardcoding Latin-1. If the C++ code is using UTF-8 or another 8-bit or multibyte encoding, the strings get incorrectly converted.

This should be made locale aware in some way, or at least provide some configurable way to swap out the conversion functions if a program needs UTF-8 or one of the old-school 8-bit encodings.

The relevant code is in embind.js; search for '_embind_register_std_string' and see the 'fromWireType' and 'toWireType' methods that get defined there.

Workaround is to use std::wstring on all your binding methods, which marshals Unicode chars correctly as long as using 4-byte mode.

**Comment by TomiBelan** [comment]
I think this is solved since #4255 which added EMBIND_STD_STRING_IS_UTF8, so maybe this issue can be closed now.
