### ISSUE TITLE
getenv: Calling getenv deallocate string previously returned

### ISSUE THREAD

**Issue by jcfr** [emscripten-core/emscripten#4226]
First, thanks @kripken for the awesome work :+1: 

Here are the details:

In C code where there are consecutive calls to `getenv`, the memory allocated after returning the first value is freed doing an other call.

The following scenario illustrates the problem:

Modified `tests/env/src.c` adding:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main() {

  [...]

 printf("setenv(checkpersist_VALUE1) ret: %d\n", setenv("checkpersist_VALUE1", "env_value_should_persist", 0));
  printf("setenv(checkpersist_VALUE2) ret: %d\n", setenv("checkpersist_VALUE2", "an_other_env_value", 0));
  char* checkpersist_VALUE1 = getenv("checkpersist_VALUE1");
  printf("checkpersist_VALUE1: %s\n", checkpersist_VALUE1);
  printf("getenv(checkpersist_VALUE2): %s\n", getenv("checkpersist_VALUE2"));
  printf("checkpersist_VALUE1 (after getenv call): %s\n", checkpersist_VALUE1);

  return 0;
}
```

Running `python tests/runner.py test_env` gives:

```
--- expected
+++ actual
@@ -33,5 +33,5 @@
 setenv(checkpersist_VALUE2) ret: 0
 checkpersist_VALUE1: env_value_should_persist
 getenv(checkpersist_VALUE2): an_other_env_value
-checkpersist_VALUE1 (after getenv call): env_value_should_persist
+checkpersist_VALUE1 (after getenv call): an_other_env_value
```

This is confirmed looking at the implementation of `getenv` in [src/library.js](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library.js#L589-L602)

The following line is freeing the memory:

```
if (_getenv.ret) _free(_getenv.ret);
```

PR will follow shortly.

Cc: @thewtex

**Comment by Matheus28** [comment]
That seems to be conformant to the [man page](http://man7.org/linux/man-pages/man3/getenv.3.html) for getenv(3). Or maybe I'm missing something?

```
The implementation of getenv() is not required to be reentrant.  The
string pointed to by the return value of getenv() may be statically
allocated, and can be modified by a subsequent call to getenv(),
putenv(3), setenv(3), or unsetenv(3).
```

**Comment by jcfr** [comment]
@Matheus28  Thanks for reviewing.

Agree with you, the current emscripten implementation is conformant.

To provide some background, I first discovered the problem while working with the cpython code base. See [Modules/getpath.c](https://github.com/python/cpython/blob/2cb76de6054831624114b4be6efc50df5390a4bb/Modules/getpath.c#L482-L485)

After your comment, I did some more searching and ...  it seems common for existing implementation to assume multiple call to `getenv` do not modify the underlying environment.

For example, here are some occurrences within  the  `git` codebase:
* [notes-utils.c](https://github.com/git/git/blob/c2c5f6b1e479f2c38e0e01345350620944e3527f/notes-utils.c#L122-L123)
* [daemon.c](https://github.com/git/git/blob/c2c5f6b1e479f2c38e0e01345350620944e3527f/daemon.c#L676)
* [editor.c](https://github.com/git/git/blob/c2c5f6b1e479f2c38e0e01345350620944e3527f/editor.c#L12-L13)

In the case of `git`, this was discussed on the the associated project mailing list. Back in 2013, someone [reported](http://permalink.gmane.org/gmane.comp.version-control.git/212657) a similar issue on the `z/OS` platform mentioning the current use in git wasn't conformant either . Then, after few back and forth, the conclusion was ` [...] this patch is useful for reaching strict conformance to the published specs, but [...] we can go back to assuming no [other] known platforms are broken and unusable because of this.` Source [here](http://permalink.gmane.org/gmane.comp.version-control.git/212899)

Looking at the current [setup.c](https://github.com/git/git/blob/6a269e52a5d0c82567c5b39cc194cc90f9fa9156/setup.c#L816-L824) confirms no change have been made.

Considering that the glibc implementation of `getenv` ( [stdlib/getenv.c](https://github.com/bminor/glibc/blob/5cd7af016d8587ff53b20ba259746f97edbddbf7/stdlib/getenv.c#L32-L91) ) stores the environment within a static variable `__environ` and doesn't modify it,  I suggest that we modify the emscripten implementation.

Let me know what you think ?

Thanks again for your time, 
Jc

**Comment by kripken** [comment]
In general, if this is a common bug then I am ok to work around it, and behave in the more expected way. However, this means memory will leak, so we should allocate carefully (one per string, not one per call).
