### ISSUE TITLE
Don't use a trampoline for EM_ASM_*

### ISSUE THREAD

**Issue by Matheus28** [emscripten-core/emscripten#4228]
When you use `EM_ASM_*`, it puts the javascript code into a function in an array called `ASM_CONSTS`. Then in the asm.js code, it uses a library function called `_emscripten_asm_const_<arity>` to then call functions in that array.

Wouldn't it be more efficient to, instead of using that trampoline, simply adding that javascript directly as a library function, and importing it into asm.js the same way other library functions are imported? It would avoid the unnecessary extra function call to reach the inline javascript, thus reducing overhead.

**Comment by kripken** [comment]
A possible downside is that we'd need to import more methods into the asm.js module, and that would increase code size. Otherwise, though, I agree that would be more efficient. I suspect it is not big in benchmarks, though, so code size matters more, but I could be wrong.

**Comment by Matheus28** [comment]
I think that if the idea is to minimize code size (`-Os` and such), it'd make sense to have those trampolines. But for code compiled with `-O2` and such, it would probably be better if we didn't have those trampolines whenever possible.

**Comment by kripken** [comment]
Sounds reasonable. If it doesn't add too much code complexity that sounds good. However this would require changes in both the llvm backend and emscripten.py, at minimum.
