### ISSUE TITLE
Create archive (.a) file from c files

### ISSUE THREAD

**Issue by sandeepmalode** [emscripten-core/emscripten#4229]
Hi, 
I want to create archive (.a) file from (.o) files by compiling c files with emscripten.
Can anyone please provide commands to create archive (.a) file.

Thanks.

**Comment by kripken** [comment]
The `llvm-ar` command can create archives. An example should be in tests/, grep for `LLVM_AR`.

**Comment by sandeepmalode** [comment]
Thanks Alon. I used "emar" to create the archive file. What option should I use to use this archive file as input to compile another set of c files as I get lot of "warning: unresolved symbol" messages?
