### ISSUE TITLE
Using inline asm puts the original code in the memory initializer

### ISSUE THREAD

**Issue by Matheus28** [emscripten-core/emscripten#4231]
It seems that, since `EM_ASM` stringifies the code and passes it to `emscripten_asm_const` (so it can be handled in `CallHandlers.h`), the original code ends up wasting some space in the memory initializer and exposing pre-compilation code in production builds.

**Comment by Matheus28** [comment]
I haven't gotten too familiar with the code base yet, but it seems that the fix could be changing `JSBackend.cpp`, in `JSWriter::getAsmConstId` somehow removing the reference to that `GlobalVariable`, so it's not allocated in `JSWriter::parseConstant`. Now, I haven't gotten much experience with LLVM code so I'm not quite sure which way to go about this.

**Comment by kripken** [comment]
I think we first parse constants, then parse code. So the string would already be allocated by the time we call getAsmConstID.

A patch like this might be a start,

````
@@ -3472,11 +3485,29 @@ void JSWriter::parseConstant(const std::string& name, const Constant* CV, int Al
          dyn_cast<ConstantDataSequential>(CV)) {
     assert(CDS->isString());
     if (calculate) {
-      HeapData *GlobalData = allocateAddress(name, Alignment);
-      StringRef Str = CDS->getAsString();
-      ensureAligned(Alignment, GlobalData);
-      for (unsigned int i = 0; i < Str.size(); i++) {
-        GlobalData->push_back(Str.data()[i]);
+      // If this is a string only used by emscripten_asm_const*, then we don't
+      // need to actually emit it
+      bool needed = false;
+      for (auto *CU : CDS->users()) {
+        auto *SV = CU->stripPointerCasts();
+        auto *CI = dyn_cast<CallInst>(SV);
+        if (!CI) {
+          needed = true;
+          break;
+        }
+        auto *CF = dyn_cast<Function>(getActuallyCalledValue(CI));
+        if (!CF || !CF->getName().startswith("emscripten_asm_const")) {
+          needed = true;
+          break;
+        }
+      }
+      if (needed) {
+        HeapData *GlobalData = allocateAddress(name, Alignment);
+        StringRef Str = CDS->getAsString();
+        ensureAligned(Alignment, GlobalData);
+        for (unsigned int i = 0; i < Str.size(); i++) {
+          GlobalData->push_back(Str.data()[i]);
+        }
       }
     }
   } else if (const ConstantFP *CFP = dyn_cast<ConstantFP>(CV)) {
````

However the tricky thing is that each use of that string might be a bitcast, or a getelementptr, or a sequence of those, before it flows into an `emscripten_asm_const*` call. I'm not sure if there's a good way to do that in LLVM that isn't messy.

(see also notes [here](https://github.com/kripken/emscripten/issues/4230#issuecomment-206481995))

**Comment by Matheus28** [comment]
Since you're not supposed to use `emscripten_asm_const*` directly, but only through the macros that stringify the code, I think it might be safe to assume that the function will only ever receive a string literal?

**Comment by kripken** [comment]
Yes.

**Comment by Matheus28** [comment]
The patch looks good to me, what do you feel that's missing? If the user is doing anything tricky before handing the string to `emscripten_asm_const*` (instead of using the macro), worst case is that we actually put that string in the memory, which is the current behavior.

**Comment by kripken** [comment]
It's not the user, it's LLVM. The simple call with that string as an argument can still turn into a bunch of geps and/or bitcasts. For example, I see this in a hello world using EM_ASM:

````
  call void @emscripten_asm_const(i8* getelementptr inbounds ([25 x i8], [25 x i8]* @.str, i32 0, i32 0))
````

and optimizations etc might change things up as well.

**Comment by Matheus28** [comment]
Oh, I see. A better solution could be changing `emscripten_asm_const*` to a builtin in clang and making it emit something that we catch in the JSWriter. What do you think?

**Comment by kripken** [comment]
I don't know much about clang builtins. But even if it were a special function, it's arguments could still be gep'ed or bitcasted? Anyhow, worth trying, the attempt might help understand the problem more even if it fails.

**Comment by Matheus28** [comment]
Another question, why do we use `EM_ASM` instead of `__asm__`? There probably is built in support in `__asm__` to do what we're trying to accomplish.

**Comment by kripken** [comment]
`__asm__` has it's own rules about quoting, escaping, interaction with the C preprocessor, etc., in particular it ends up placing strings inside LLVM `asm()` calls, which are a little special. We had a bunch of bugs there, and ended up avoiding `__asm__` entirely. The `EM_ASM` macros simply create a C string using the `#` C macro operation. Then we just copy that string into JS.
