### ISSUE TITLE
Pointer_stringify(ptr, len) does not handle the case of 0 in the string as expected

### ISSUE THREAD

**Issue by shooshx** [emscripten-core/emscripten#4233]
When I call Pointer_stringify() with just a pointer, I expect it will read the string until a null termination but for the version that takes a pointer and length I expect it will read all the bytes in the given length, even if they are 0. This is what std::string c'tor does.
This essentially makes passing strings that contain 0 from C++ to JS impossible.

**Comment by kripken** [comment]
I guess this is a difference between C and C++. In C++, std::string can allow a string with 0's in the middle. But Pointer_stringify works on C strings. We could perhaps add a version for non-null-terminated strings.

**Comment by cforger** [comment]
I'd expect the C behaviour myself, though I see why that's a problem when C++ allows a more complex behaviour. 

Perhaps an entry into the wiki on how strings are expected to be handled (for instance, do I need to enter \n's on prinfts? I see _puts replaces them with nulls), and a switch to call a different stringify if you're in C++ land?

**Comment by kripken** [comment]
printf doesn't add a newline by default, puts does. printf output without newlines can end up buffered (separately for stdout and stderr) until a newline arrives, or the program exits. This should be pretty standard for native execution, but if there's a place you can find in the docs to mention this, that would be good of course.
