### ISSUE TITLE
ASYNCIFY problem

### ISSUE THREAD

**Issue by Batov** [emscripten-core/emscripten#4246]
Hi!

I am need to wait for async function. And use ASYNCIFY for it:

`  
int main ()
{
   int data = 0x00;
  sync_func_1();
   async_func();
  /\* Need for wait here for get 0xAA from data */
   sync_func_2();
return 0;
}

void async_func()
{
 /\* do something and call callback function: callback() */
}

void callback()
{
   data = 0xAA;
   _emscripten_async_resume();
}
`

Build with -s ASYNCIFY=1 -s ASYNCIFY_FUNCTIONS="['async_func']"

But at browser console has error:
`exception thrown: TypeError: asm.setAsync is not a function,TypeError: asm.setAsync is not a function
    at _emscripten_sleep (chrome-extension://oboleflmhblphpjdbknkjmljdggelach/index.js:2376:11)
........`

Can you help me?

**Comment by kripken** [comment]
First thing, please note that the asyncify option is no longer in development and not recommended, as the note at the top of the [wiki page](https://github.com/kripken/emscripten/wiki/Asyncify) says.

Regarding this issue, I think the compiler looks for asyncify-using calls, like emscripten_sleep. If the only asyncify call you have is `emscripten_async_resume`, that might confuse it. I would take a look at `test_async` in `tests/test_core.py` (runnable via `tests/runner.py test_async`), to see a working example, then see what is different between your programs.
