### ISSUE TITLE
OpenAL buffer destruction crash

### ISSUE THREAD

**Issue by emrahgunduz** [emscripten-core/emscripten#4249]
In some cases [this line in openal library](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_openal.js#L710) implementation crashes the javascript loop and exported code.

Changing

``` javascript
if (!src) {
    continue;
}
```

to

``` javascript
if ( !(typeof  src !== 'undefined' && typeof src.queue !== 'undefined') ) {
    continue
}
```

solved the problem.

**Comment by kripken** [comment]
@juj, can you please take a look at this?
