### ISSUE TITLE
DEAD_FUNCTIONS does not work in 1.35

### ISSUE THREAD

**Issue by salos1982** [emscripten-core/emscripten#4252]
I've created build with -O2 optimization and got emitted functions (attached)
[hero.js.symbols.zip](https://github.com/kripken/emscripten/files/223687/hero.js.symbols.zip)

however if I add
-s 'DEAD_FUNCTIONS=["_SW_CreateRenderer"]'

The symbol map does not changed. I still contains _SW_CreateRenderer and SW_CreateRendererForSurface functions (the last one is called only from SW_CreateRenderer).

SW_CreateRenderer is used from sdl2

**Comment by kripken** [comment]
Looks like we don't have support for this in the JS backend. It would need to be added, or the function could be removed later in the js optimizer perhaps.

Meanwhile I'll update the docs to mention that this option only works on JS library methods.

**Comment by salos1982** [comment]
it seems strange because I see in tests\test_benchmark.py in the end following command 
 emcc_args = ['-s', 'DEAD_FUNCTIONS=["__ZSt9terminatev"]']
I don't think that __ZSt9terminatev is very common javascript name

**Comment by kripken** [comment]
Not sure why that's there but it is a js library method, look in src/library.js.
