### ISSUE TITLE
WORKERFS created nodes cannot be found in FS.nameTable

### ISSUE THREAD

**Issue by holland01** [emscripten-core/emscripten#4254]
I'm honestly not certain if there was a specific reason for using absolute paths in the names
of nodes created in WORKERFS, but none-the-less: if you mount packaged bundles to WORKERFS, any subsequent calls made to fopen using a path which is handled by a relevant bundle in the worker thread can't be found.

The source of the problem is here, in $EMSCRIPTEN/src/library_ws.js (line 11):

```
var createdParents = {};
function ensureParent(path) {
  // return the parent node, creating subdirs as necessary
  var parts = path.split('/');
  var parent = root;
  for (var i = 0; i < parts.length-1; i++) {
    var curr = parts.slice(0, i+1).join('/');
    if (!createdParents[curr]) {
      createdParents[curr] = WORKERFS.createNode(parent, curr, parts[i], WORKERFS.DIR_MODE, 0);
    }
    parent = createdParents[curr];
  }
  return parent;
}
function base(path) {
  var parts = path.split('/');
  return parts[parts.length-1];
}
// We also accept FileList here, by using Array.prototype
Array.prototype.forEach.call(mount.opts["files"] || [], function(file) {
  WORKERFS.createNode(ensureParent(file.name), base(file.name), WORKERFS.FILE_MODE, 0, file, file.lastModifiedDate);
});
(mount.opts["blobs"] || []).forEach(function(obj) {
  WORKERFS.createNode(ensureParent(obj["name"]), base(obj["name"]), WORKERFS.FILE_MODE, 0, obj["data"]);
});
(mount.opts["packages"] || []).forEach(function(pack) {
  pack['metadata'].files.forEach(function(file) {
    var name = file.filename.substr(1); // remove initial slash
    WORKERFS.createNode(ensureParent(name), base(name), WORKERFS.FILE_MODE, 0, pack['blob'].slice(file.start, file.end));
  });
```

In particular:

```
var parts = path.split('/');
var parent = root;
for (var i = 0; i < parts.length-1; i++) {
  var curr = parts.slice(0, i+1).join('/');
  if (!createdParents[curr]) {
    createdParents[curr] = WORKERFS.createNode(parent, curr, WORKERFS.DIR_MODE, 0);
  }
  parent = createdParents[curr];
}
```

Each time `curr` is calculated, the name of the node is given the full absolute path,
as opposed to _just_ the name of the folder itself that `i` represents. For example,
say we're adding the file 'asset/scripts/somescript.shader'; we'll have the following
parent nodes out of this:

```
"asset"
"asset/scripts"
```

And one child name of "somsecript.shader"

The thing is that any File System lookup that occurs through a call to FS.open has
the potential to rely on a call into FS.lookupPath to attain the information it
needs to continue. The FS lib (which WORKERFS implements as a
    "sub-interface") depends heavily on a hash table that's used to employ
    quick lookups in memory in the filesystem. If the item to be fetched isn't found
    in that table, then a default lookup function is called, which will lean towards
    a stubbed out MEMFS function (I haven't figured out why this is the case for
    a path with a non-existent hash value yet - it's weird, because the function
    which is stubbed is bound to a parent that can actually be part of the FS given
    that its 'curr' path is only a single name). In my experience all that's happened
    from this is a thrown exception (in the stub) which gets caught back in FS.open,
    and then ignored.

The fix was pretty simple, though.

This,

```
if (!createdParents[curr]) {
  createdParents[curr] = WORKERFS.createNode(parent, curr, WORKERFS.DIR_MODE, 0);
}
```

becomes this:

```
if (!createdParents[curr]) {
  createdParents[curr] = WORKERFS.createNode(parent, /*curr*/ parts[i], WORKERFS.DIR_MODE, 0);
}
```

And this is provable: we still use curr to maintain consistency and ensure the correct
parent is fetched in the table; since the newly created node is dependent
on its path within the parent table, which is in turn dependent on the path itself,
this doesn't break anything - it actually conforms to the standard the main FS module
expects.

**Comment by kripken** [comment]
Thanks for looking into this! Do you want to open a PR with the fix?

**Comment by holland01** [comment]
No problem! I can have one for you by tonight, PST :)
