### ISSUE TITLE
Running emscripten_trace_configure from trace.h in a worker fails with "Worker is not defined"

### ISSUE THREAD

**Issue by michalc** [emscripten-core/emscripten#4256]
It looks like library_trace.js tries to load js file as a worker from the tracing server at https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_trace.js#L59

This fails when run in a web-worker since it doesn't have the ability to create another web-worker. For reference, I'm not using BUILD_AS_WORKER.

**Comment by kripken** [comment]
Which browser is this on? It's a known [bug on chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=31666&q=nested%20workers&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) that they haven't implemented nested workers yet (their [intent to implement](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/1HveyWzj9CM/Uo4AtKBSZt0J) is 2 years old at this point). Looks like [not on Safari either](https://bugs.webkit.org/show_bug.cgi?id=22723).

**Comment by michalc** [comment]
It's Chrome.

I wonder if the worker is needed at all though. If it's only to get around cross domain issues talking to the trace collector server, could the trace collector be modified to set the appropriate cross domain headers/responses?

**Comment by kripken** [comment]
Perhaps @waywardmonkeys knows.

**Comment by waywardmonkeys** [comment]
Indeed, I do.

I wrote it that way so that any blocking or delays would happen in the worker instead of the thread doing the tracing.

If that isn't a valid thing, we can surely adjust this.

**Comment by michalc** [comment]
My suspicion is that a (asynchronous) XMLHttpRequest triggered at most every 500ms as in https://github.com/waywardmonkeys/emscripten-trace-collector/blob/b9bfa91232857a4dcc729fa6ca35ca3732ceb621/trace_collector/static/worker.js won't cause any significant effect in the thread doing the tracing compared to a postMessage to a worker, but I haven't measured this so I'm not 100% sure. (And actually I can see an argument that it might even be better, as it looks like there would be fewer XHMLHttpRequests than postMessages)

One thing to note is that since the content-type of the request is application/json, then according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS it will require a preflight request. However, it's my understanding that these can be cached per URL for up to 10 minutes.

**Comment by seankibler** [comment]
I'm also experiencing this issue. Not being picky about what browser I can use this in I switched to Firefox where I then get window is not defined.
