### ISSUE TITLE
postamble.js: issue with sending multiple messages consecutively in a single worker

### ISSUE THREAD

**Issue by holland01** [emscripten-core/emscripten#4258]
Say we have two functions defined in a worker (in c):

```
// #ifdef __cplusplus extern c blah blah

void WorkerFun_A(char* data, int size) {
     /// do some stuff here with data
     emscripten_worker_respond(someresponse, somesize);
}

void WorkerFun_B(char* data, int size) {
     /// do some stuff here with data
     emscripten_worker_respond(someresponse, somesize);
}
```

Now, in the main thread, we have the following two callbacks:

```
static worker_handle gSomeWorker;

void Response_A(char* data, int size, void* userParam) {
      // do something with the above parameters
     char data2[] = "whatevers";
      emscripten_call_worker(gSomeWorker, "WorkerFun_B", data2, strlen(data2), Response_B, NULL);
}

void Response_B(char* data, int size, void* userParam) {
      // do something with above parameters
      // evaluate 'data', which is assumed to be whatever was passed
      // from Response_A (in this case, we expect "whatevers" to be what data points to)
     printf("Data Received: %s\n", data);
      // close gSomeWorker here 
}

int main(void) {
    // initialize gSomeWorker
    char data1[] = "1234567891337FEED";
    emscripten_call_worker(gSomeWorker, "WorkerFun_A", data2, strlen(data2), Response_A, NULL);
    while (true) {
         puts("Dummy");
    }
    return 0;
}
```

The buffer data2 is 9 bytes, whereas data1 is 17 bytes. So, initially, data1 is a larger
buffer of memory. 

When Response_B is inadvertently invoked from Response_A, the output from the printf will be:

```
"whatevers1337FEED"
```

I've tracked the source of the issue to two separate locations; only one has actually proved to be relevant in this case, but it looks like the other is likely to suffer from it as well. The relevant file is postamble.js, in particular:

```
if (data) {
   if (!data.byteLength) data = new Uint8Array(data);
   if (!buffer || bufferSize < data.length) {
       if (buffer) _free(buffer);
       bufferSize = data.length;
       buffer = _malloc(data.length);
    }
    HEAPU8.set(data, buffer);
}
```

Which lies in the `onmessage()` definition (line 372) of the file.

After a quick modification:

```
if (data) {
   if (!data.byteLength) data = new Uint8Array(data);
   // if bufferSize >= the new data.length,
   // buffer won't be reallocated, so zero it out.
   if (buffer && bufferSize >= data.length) {
      _memset(buffer, 0, bufferSize);
   }
   if (!buffer || bufferSize < data.length) {
       if (buffer) _free(buffer);
       bufferSize = data.length;
       buffer = _malloc(data.length);
    }
    HEAPU8.set(data, buffer);
}
```

The problem stops. 

Nearly the same exact code lies in library_browser.js, on line 1310:

(shown with the addition)

```
    if (!data.byteLength) data = new Uint8Array(data);
        // if bufferSize >= the new data.length,
        // the buffer won't be reallocated, so zero it out.
        if (info.buffer && info.bufferSize >= data.length) {
          _memset(info.buffer, 0, info.bufferSize);
        }
        if (!info.buffer || info.bufferSize < data.length) {
          if (info.buffer) _free(info.buffer);
          info.bufferSize = data.length;
          info.buffer = _malloc(data.length);
        }
        HEAPU8.set(data, info.buffer);
        callbackInfo.func(info.buffer, data.length, callbackInfo.arg);
```

I'm not quite certain what library_browser.js's worker functionality is used for, exactly (I stumbled on it when tracking down the issue, before realizing the problem was actually related to postamble.js, specifically), but I'd think the same issues would occur.

**Comment by kripken** [comment]
I think the problem might be on

````
emscripten_call_worker(gSomeWorker, "WorkerFun_B", data2, strlen(data2), Response_B, NULL);
````

You need to send `strlen(data2) + 1` bytes, so that you also include the null terminator. (Assuming you depend on a C string being null-terminated on the other side.)

**Comment by holland01** [comment]
Yup, that's a good point. Maybe it would be beneficial to incorporate a check for that, in the location the memset was proposed?

Something like (pseudo code):

```
if buffer.length > data.length && buffer[data.length] != 0:
     buffer[data.length] = 0
```

**Comment by holland01** [comment]
To clarify, it would accomplish the same thing in place of the memset, and would be more efficient. 

My only concern is alignment in situations where data isn't a string, which, if required taking into account, wouldn't be very beneficial over all.

**Comment by kripken** [comment]
The buffer is just pure data, though - there is no reason to have a zero at the end. (Unless your program assumes such a thing, which C strings do.)
