### ISSUE TITLE
compile SDL_net 2.01 under Enscripten

### ISSUE THREAD

**Issue by veso266** [emscripten-core/emscripten#4259]
Hi I have a program that depends on SDL2_net but the problem is that (SDL is included in Enscripten install script) I don't know how to properly compile SDL2_Net that enscripten will see it and allow the program to normaly run emconfigure ./configure now I can compile SDL2_net fine with ./configure, make and then sudo make install but the problem is that emscripten won't see it if I then run emconfigure ./configure on that project  it isn't finding SDL2_net it just errors out

> checking SDL_net.h usability... no
> checking SDL_net.h presence... no
> checking for SDL_net.h... no
> checking for SDLNet_Init in -lSDL2_net... no
> configure: WARNING: Can't find SDL2_net, internal modem and ipx disabled
> .

Do you thinnk you could include SDL2_net under Portable Enscripten SDK? or tell me what is the best way to include SDL2_net into Emscripten portable SDK so I can then compile applications with SDL2_net?

Thanks for Anwsering and Best Regards

**Comment by lukasschmit** [comment]
Any update on this? According to
https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#emscripten-ports
SDL_net should be included by default with emscripten, however running `emcc --show-ports`does not list SDL_net.

**Comment by veso266** [comment]
if you install the latest enscripten then its included you just have to tell it to build it with this `emconfigure ./configure CPPFLAGS="-s USE_SDL=2 -s USE_SDL_NET=2" LDFLAGS="-s USE_SDL_NET=2"`

**Comment by isc30** [comment]
any updates on this? seems like `SDL_net.h` isn't anywhere even tho it appears in the list after running `emcc --show-ports`

**Comment by kripken** [comment]
There is a port for SDL_net, usable with `-s USE_SDL_NET=2`. It appears in `emcc --show-ports`,
```
    SDL2_net (zlib license)
```
Perhaps you're not on the latest version?

**Comment by isc30** [comment]
Yup I'm in the latest version, the issue is that the `SDL_net.h` isn't included in the libraries from emscripten

**Comment by kripken** [comment]
It should be downloaded and in the include path if you build with that option. See the test in the test suite (`sockets.test_sdl2_sockets_echo`; can search for `USE_SDL_NET` in `tests/`).
