### ISSUE TITLE
FreeType FT_DivFix() wrong result

### ISSUE THREAD

**Issue by metafloor** [emscripten-core/emscripten#4262]
I have successfully compiled freetype in the past with older versions of freetype and emscripten.  Upgraded to the latest version of each.  Compiles without issue but I am getting a nonsense math result from within freetype.

Here is the problem code (freetype-2.6.3/src/cff/cf2ft.c line 73):

```
    printf("unitsPerEm=%d, CF2_MAX_SIZE=%d\n", unitsPerEm, CF2_MAX_SIZE);
    printf("cf2_intToFixed=%d\n", cf2_intToFixed(unitsPerEm));

    maxScale = FT_DivFix( CF2_MAX_SIZE, cf2_intToFixed( unitsPerEm ) );

    printf("maxScale=%d\n", maxScale);
```

The output from the printf()s show:

```
    unitsPerEm=1000, CF2_MAX_SIZE=131072000
    cf2_intToFixed=65536000
    maxScale=0
```

The result of FT_DivFix(a,b) should be:  a \* 0x10000 / b, which for the given values is 131072.

I have tried compiling with different levels of optimization with no luck.

Platform:  4.2.0-16-generic #19-Ubuntu SMP x86_64

Thanks!

**Comment by kripken** [comment]
Can you add this to the freetype test in `tests/test_core.py`? That way it is easy for us to reproduce, and also we'll have a test for after we fix things.

**Comment by metafloor** [comment]
One problem is the test suite is running against freetype 2.4.4

I have verified that freetype 2.4.4 compiles and works correctly with the latest emscripten on linux x64.
  
freetype 2.5+ compiles but fails to render any character because FT_DivFix() always returns 0.  I don't think a new test case is needed; just upgrade freetype to current 2.6.3 and the existing test case should fail.

**Comment by kripken** [comment]
Ok, I see. If you or someone else wants to make a PR with an update of freetype, that sounds like the next step here, and then we can debug on that PR.

**Comment by kripken** [comment]
Another option might be to make the test suite use freetype from ports, as the version there looks like 2.6. The PR could remove freetype in the emscripten repo, and use the ports one instead. Should be examples of using zlib from ports in the test suite.

**Comment by kripken** [comment]
Btw, were you trying on ports? It might have fixes that are necessary.

**Comment by maxabrams** [comment]
This bug persists with current versions of both. Results in CFF fonts being unusable.

**Comment by kripken** [comment]
Ok, then the next steps sounds like what was suggested a few comments back: a PR that moves the test suite to use freetype from ports, and shows the bug clearly.

**Comment by maxabrams** [comment]
It looks like I don't have access to make a PR; even tried to make a branch with the changes. Attatched zip contains:
freetype - update test library to 2.6.3
freetype-js-port - JS port of Freetype 2.6.3

To see the error:
1) Navigate to freetype-js-port
2) Launch a http server to host demand-loaded files. Easiest way (from freetype-js-port directory): python -m SimpleHTTPServer 8000
3) Open freetype.html and observe console output with text render

More details can be found from Metafloor's wiki: https://github.com/metafloor/bwip-js/wiki/Compiling-FreeType

[freetype.zip](https://github.com/kripken/emscripten/files/337776/freetype.zip)

**Comment by kripken** [comment]
No special access is needed to make a PR. You need a fork of this repo, to create a branch there, and to open a PR for that in this repo.

**Comment by maxabrams** [comment]
Doing that now...

**Comment by maxabrams** [comment]
#4419

**Comment by maxabrams** [comment]
Additional information: http://savannah.nongnu.org/bugs/?48309

Seems to be coming from 64 bit division

**Comment by kripken** [comment]
If it's indeed a 64-bit division issue, then we should create a standalone testcase of just that `FT_DivFix` method, being run on the input that it gets wrong.
