### ISSUE TITLE
Raw pointers with val.h

### ISSUE THREAD

**Issue by jkm** [emscripten-core/emscripten#4286]
I want to pass a raw pointer to C++ using `val.h`. I'm passing the pointer as property of a Javascript object. The HTML/Javascript is

``` html
<html>
<meta charset="utf-8"></meta>
<script src="test.js"></script>
<script>
    window.onload = function(){ 
        var data = new Float64Array(100);
        var ptr = Module._malloc(data.length * data.BYTES_PER_ELEMENT);

        var obj = { ptr : ptr };
        Module.test(obj);

        Module._free(ptr);
    };
</script>
<body>
</body>
</html>
```

The HTML is _untested_ because the C++ part does not compile. On the C++ side I have written

``` c++
#include <emscripten/bind.h>
#include <val.h>

void test(emscripten::val input)
{
    auto ptr = input["ptr"].as<double*>();
}

EMSCRIPTEN_BINDINGS(what_is_this_name_for)
{
    emscripten::function("test", &test);
}
```

Compiling fails with

``` c++
/path/to/emscripten/wire.h:86:13: error: static_assert failed "Implicitly binding raw pointers is
      illegal. Specify allow_raw_pointer<arg<?>>"
            static_assert(!std::is_pointer<T*>::value, "Implicitly binding raw pointers is illegal.  Specify allow_raw_pointer<arg<?>>");
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/emscripten/val.h:427:17: note: in instantiation of template class 'emscripten::internal::TypeID<double *>' requested here
                TypeID<T>::get(),
                ^
test.cc:6:26: note: in instantiation of function template specialization 'emscripten::val::as<double *>' requested here
        auto ptr = input["ptr"].as<double*>();
                                ^
In file included from test.cc:1:
In file included from /path/to/emscripten/bind.h:10:
/path/to/emscripten/val.h:427:26: error: incomplete definition of type 'emscripten::internal::TypeID<double *>'
                TypeID<T>::get(),
                ~~~~~~~~~^~
test.cc:6:26: note: in instantiation of function template specialization 'emscripten::val::as<double *>' requested here
        auto ptr = input["ptr"].as<double*>();
```

How do I set `allow_raw_pointers()` with `val.h`? I couldn't figure it out by reading `val.h` and `wire.h`.

Many thanks for reading this report. I hope there is an easy solution that I just haven't found.

**Comment by AlexPerrot** [comment]
This is described in the documentation for embind : https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#advanced-class-concepts

You need to pass `allow_raw_pointers()` as third argument to `emscripten::function` when describing the bindings :

```
EMSCRIPTEN_BINDINGS(what_is_this_name_for)
{
    emscripten::function("test", &test, allow_raw_pointers());
}
```

**Comment by blackccpie** [comment]
Hi, I'm struggling with the same use case, and I didn't manage to make it compile putting `allow_raw_pointers()` in the `emscripten::function` arguments. The only solution I found was to write something like this:


```cpp
auto ptr = input["ptr"].as<double*>( allow_raw_pointers() );
```

This way compilation is ok, but I get runtime exception saying 

> BindingError: emval::as has unknown type Pd

Could someone help me on this?

My config : compiling with clang 8 on OS X, using emscripten 1.37.12

**Comment by AlexPerrot** [comment]
IIRC, the problem is that raw pointers to primitive types are not bound, so you can't use them with embind. However, this works fine with pointers to object types.

A simple workaround is to pass the pointer as a number and then cast in c++ style to a pointer. I think it should be reasonably safe.

**Comment by blackccpie** [comment]
It works indeed writing the pointer like this:

```cpp
auto ptr = reinterpret_cast<double*>( image["ptr"].as<int>() );
```

Thanks for the workaround!
