### ISSUE TITLE
Support SEPARATE_ASM together with MODULARIZE

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#4296]
The `separate_asm.py` script that implements the extraction of `.asm.js` from the main module body doesn't currently work with the `MODULARIZE` mode where the Module initialization is wrapped inside a constructor.

It looks like this should still be doable with a little hacking; I whipped up an experimental branch tweaking the tool: https://github.com/brion/emscripten/commit/db0ee1f2ae7a0f1fe6a8d9d3e33398cb830257a4

In modularize mode the extraction wraps the `Module["asm"] = ...` in a closure function, which is assigned to a property on the modular constructor. The constructor then calls that to initialize the new Module instance's `asm` property. It _should_ work. :)

If that seems feasible, I'll clean up the patch, figure out how to get the frontend to call it properly, and add some tests etc.

**Comment by kripken** [comment]
I'm having trouble following this. What is `asmSetup`, by which I mean, who would call it, when, and what would it do?

The asm.js would still be in a separate file? Would it still need to be loaded ahead of time? If so where would it write the asm.js  code to, as there is no global for it to use? I'm probably just not yet seeing your basic approach here... :)

**Comment by brion** [comment]
In modularize mode we do have a global, which is the wrapper function itself... Roughly, MODULARIZE=1 turns this:

```lang=js
if (!Module) Module = {};
Module["asm"] = {...};
```

into this:

```lang=js
function ModuleWrapperFunc(Module) {
  if (!Module) Module = {};
  Module["asm"] = {...};
  return Module;
}
```

where ModuleWrapperFunc is the customizable module name set via `EXPORT_NAME`. So while `Module` is a local variable, `ModuleWrapperFunc` is a global symbol that we can attach properties to. In this case I'm transforming the above into:

```lang=js
function ModuleWrapperFunc(Module) {
  if (!Module) Module = {};
  Module["asm"] = ModuleWrapperFunc["asmSetup"](Module);
  return Module;
}
```

plus the separate .asm.js file which creates its own closure function around the `Module["asm"]` setting and assigns it to the `asmSetup` property:

```lang=js
ModuleWrapperFunc["asmSetup"] = function(Module) {
  Module["asm"] = {...};
}
```

`ModuleWrapperFunc` is responsible for calling into its `asmSetup` function property and passing in `Module` (which is a local symbol); this is what allows us to set things up on the Module without exposing Module itself as a global.

The shell app would have to execute the primary file first (creating the ModuleWrapperFunc symbol), then execute the secondary file (setting the "asmSetup" property on it), and then you can instantiate the module with `var myModule = new ModuleWrapperFunc()`.

If it's important to allow the files to load in either order, that could change to use a second global symbol instead of a property of the wrapper function, for instance `ModuleWrapperFunc` and `ModuleWrapperFuncAsmSetup`.

**Comment by kripken** [comment]
Thanks! Now I get it. Yes, this looks like a good approach. My only concern is it might be confusing for people to know how to use this, but I guess we can fix that with good error reporting (if the order is wrong, etc.).
