### ISSUE TITLE
Error with "llvm.used" global variable

### ISSUE THREAD

**Issue by sparkagain** [emscripten-core/emscripten#4302]
Hello All,

I was trying to run emcc on a bunch of arbitrary llvm bc. The one I got stumbled upon is [attached](https://github.com/sparkagain/emcc/blob/master/test.ll) and it contain type descriptors and  got the following error.

> Not handled: i32 sub (i32 ptrtoint (i32\* @0 to i32), i32 10)
> LLVM ERROR: FlattenGlobals: ConstantExpr opcode not handled: sub

Please let me know your opinion/suggestions about this. Are you guys already  aware of this and planning to fix it or there is something that the clients of emcc need to fix ? 

Please help.

**Comment by kripken** [comment]
Emscripten can't handle arbitrary LLVM IR, just the subset emitted by clang, basically. We do try to support more IR when people ask, though. However, this is getting lower priority as there are other options on the horizon, specifically the new WebAssembly backend in LLVM which is in progress.

**Comment by sparkagain** [comment]
Thanks @kripken 
I tried implementing the feature and now I want to test it. I can see that you provide a test folder with a lot of test cases and expected outputs  in 
./bullet/output.txt
./ctype/output.txt
./env/output.txt
./fcntl/output.txt
./fcntl-misc/output.txt
./fcntl-open/output.txt
./filesystem/output.txt
./hyperbolic/output.txt
./langinfo/output.txt
./parseInt/output.txt
./printf/output.txt
./systypes/output.txt
./time/output.txt
(from the less number of expected outputs than the files i assume that there are many libraries code and actual test cases are very few)
But I could not find a automated way to test it. Can you please point me out to that ?

**Comment by kripken** [comment]
The python code in `tests/runner.py` runs the tests. See `test_core.py` etc that it calls. See also http://kripken.github.io/emscripten-site/docs/getting_started/test-suite.html

**Comment by sparkagain** [comment]
Thanks @kripken  and I am glad the main webpage is up now.
