### ISSUE TITLE
Update `Module.requestFullScreen` for WebVR v1.0 API

### ISSUE THREAD

**Issue by cvan** [emscripten-core/emscripten#4309]
See [this line](https://github.com/kripken/emscripten/blob/5f091840/src/library_browser.js#L378).

There's a new version of the WebVR API. Support has been in [experimental Chromium builds](https://webvr.info/get-chrome/) since March, and support is landing in Firefox Nightly soon (in the coming weeks, we hope).

The WebVR team here at Mozilla can help with this change. There's a [WebVR Polyfill](https://github.com/borismus/webvr-polyfill) that polyfills the WebVR APIs for mobile browsers that don't yet support the APIs. We have some snippets of code that will let folks use the WebVR v1.0 interfaces, but if the browser supports the WebVR pre-v1.0 API, we'll fall back to use that.

We contributed these changes to a Unity WebVR Template/Prefab: https://github.com/gtk2k/Unity-WebVR-Sample-Assets/blob/master/WebGLTemplates/WebVR/js/UnityWebVRManager.js

Soon, we can isolate the code and upstream it here too so the new WebVR v1.0 API works out out of the box too.

https://mozvr.com/webvr-spec/
https://hacks.mozilla.org/2016/03/introducing-the-webvr-1-0-api-proposal/

**Comment by kripken** [comment]
Sounds good.
