### ISSUE TITLE
Fullscreen is not work in Safari

### ISSUE THREAD

**Issue by xvAcid** [emscripten-core/emscripten#4322]
I'm using emscripten version 1.36.1 and safari v9.0.3 (11601.4.4).

When clicking in button change to fullscreen safari didn't change state.

I found how to fix this bug, should modified function **requestFullScreen** in file **src/library_browser.js**

And change this code:

`canvasContainer.requestFullScreen = canvasContainer['requestFullScreen'] ||
                                          canvasContainer['mozRequestFullScreen'] ||
                                          canvasContainer['msRequestFullscreen'] ||
                                         (canvasContainer['webkitRequestFullScreen'] ? function() { canvasContainer['webkitRequestFullScreen'](Element['ALLOW_KEYBOARD_INPUT']) } : null);`

to 

`canvasContainer.requestFullScreen = canvasContainer['requestFullScreen'] ||
               canvasContainer['mozRequestFullScreen'] ||
               canvasContainer['msRequestFullscreen'] ||
               (canvasContainer['webkitRequestFullScreen'] ? function() 
                { 
                    canvasContainer['webkitRequestFullScreen'](Element['ALLOW_KEYBOARD_INPUT']);
                    if (!document.webkitCurrentFullScreenElement) canvasContainer['webkitRequestFullScreen']();
                } : null);`

Safari should be used **webkitRequestFullScreen** without parameter ALLOW_KEYBOARD_INPUT.

**Comment by kripken** [comment]
There were some recent changes to that code, worth trying on latest incoming. Maybe @juj knows offhand if it would fix this?

**Comment by juj** [comment]
The pull request that touched this area is #4318, although I think it might not have changed anything regarding this issue specifically. Reading here http://stackoverflow.com/questions/8427413/webkitrequestfullscreen-fails-when-passing-element-allow-keyboard-input-in-safar, I believe that request fullscreen is asynchronous so `if()` in the above sniffing code might return true in all browsers. The stackoverflow post suggests that user agent sniffing might be required, which is a bit depressing. Do you agree @xvAcid ?
