### ISSUE TITLE
val::global doesn't "see" declared functions

### ISSUE THREAD

**Issue by iboB** [emscripten-core/emscripten#4328]
Here is the simple test case:

```
emscripten_run_script(
    "function high5() { return 5; }"
    "downLow = function() { return -1; };"
);

val high5 = val::global("high5");
cout << high5.typeof().as<string>() << endl;

auto g = val::global();
high5 = g["high5"];
cout << high5.typeof().as<string>() << endl;

val downLow = val::global("downLow");
cout << downLow.typeof().as<string>() << endl;
```

When executed this produces the following output:

```
undefined
undefined
function
```

Declared functions are `undefined` for `val` and there seems to be no way of referencing them.

A workaround idea, until there is a fix, which doesn't involve changing the JS code, will be appreciated

**Comment by AlexPerrot** [comment]
This is just a consequence of using `eval` to implement `emscripten_run_script`.

Function declared in the script are scoped to the enclosing function and thus are not declared globally.
More info [here](http://stackoverflow.com/questions/2999207/trouble-using-eval-to-define-a-toplevel-function-when-called-from-within-an-ob).

**Comment by iboB** [comment]
Indeed. Since there was no solution I ended up changing the JS code. Given @AlexPerrot's comment, I think it won't be such a great idea to actually fix this. I guess a "wontfix" for this issue would be the best way to go.
