### ISSUE TITLE
V8 compilation crash and possible solutions

### ISSUE THREAD

**Issue by julianjensen** [emscripten-core/emscripten#4329]
I'm having a problem with **Emscripten**, specifically with a _Unity 3D_ project in _webgl_. Essentially, the final output is too large to load on lower-end Chromebooks, which constitute the bulk of our required target platform.

The source file varies in size based on settings but is, at least, 3.2 million lines long, all in 1 large source file. V8 simply dies during compilation. The Chromebook has enough memory to run the program but the compilation process itself spikes the memory usage past platform capacity.

My initial thought to save memory would be to split the source into a number smaller files, under the assumption that memory usage is some exponential factor correlated with the source file size. In other words, if _S_ is source lines, _C_ is the exponent expressing resource cost, and _N_ is the number of modules, then I figure that given _N(S/N)^C_, then _N = 20_, for example, is many orders of magnitude more memory efficient than _N = 1_. In addition to allowing for concurrent loading of source files, it should also result in a huge memory requirement reduction. The problem is that I see no easy way to split up this single monolithic module. Searching around, I found this: [Hard to debug large JS files](https://groups.google.com/forum/#!msg/emscripten-discuss/R9mwSGgtRm4/UetCEa4yCQAJ), but he doesn't provide source code he refers to. He does, however, link to this: [ASM JS Break Up Into Multiple Files](https://docs.google.com/viewer?a=v&pid=forums&srcid=MTUxNDYyNzczNzEzNzczODk2MjABMDkzMzI2OTI1NzAxMzM1NTgwMDIBSEk4MGRNTVFCd0FKATAuMQEBdjI) which seems to address my issue. A lot of searching has failed to turn up any ready-made solutions.

So, my question is, what are my options here? Are there any tools or other techniques that could solve this? I could write a tool based on the document linked above, but, being pressed for time on my project, I figured I'd try the easier way out first and see if anything was available already.

I've already considered restricting the loop unrolling limit and also adding `llvm-lto 1` to the command line but a post from Unity on their forum seems to indicate that this leads to crashes.

It should also be noted that _Unity 3D_ builds the command line for building the project and, while it is possible to add flags to that command line, for some flags already set by _Unity_, any additional flags of the same group are being ignored, thus limiting what we can do via the command line for the build step. That being said, I'm perfectly fine with a post-process solution.

Any help would be greatly appreciated.

Julian

**Comment by kripken** [comment]
This is a chrome issue that they have made progress on. Is that using very latest chrome?

There are a bunch of ways to [optimize code for size](http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#code-size), which might help here. However, splitting the JS module is not possible in asm.js, and without asm.js performance is generally very bad. You can however generate [multiple modules](https://github.com/kripken/emscripten/wiki/Linking) and I believe Unity has support for this - it will be somewhat slower, though.

A more radical solution may be to move some code in the [emterpreter](https://github.com/kripken/emscripten/wiki/Emterpreter), if it's ok that it is slow.

**Comment by julianjensen** [comment]
Slow is not an option, unfortunately. I believe we're using the latest Chrome, but I'll make sure that we're on 50. Slightly slower might be okay as we're not pushing the performance limits on this game.

I'm not certain what kind progress, if any, **V8** is making on the `asm.js` issue. They've been working on it for at least 5 years and they still have problems. They seem to focus more heavily on **WebAssembly** from what I can tell. 

Multiple modules would probably be an option but between my unfamiliarity with *Unity* and the inner workings of *emscripten*, I'm unclear as to how to do this. The documentation you linked is less specific and lacking in examples than one might like. I will, of course, look at the test suite as the docs suggest and see what I can learn from there.

Does this mean that the approach shown in the document I linked will not work? Or, it will work but it's no longer `asm.js`? I was hoping for a post-process to avoid having to dance with *Unity*. :)

In any case, thanks for getting back to me on this issue. I'll start bugging *Unity* and **V8** on this issue until someone breaks (probably me). ;)

**Comment by kripken** [comment]
Chrome basically is starting to compile asm.js through their new wasm pipeline. It's close to ready. Right now though, yeah, it's slow.

Yes, breaking stuff up as in that link makes it no longer asm.js.

I believe Unity already has module support. I've seen it in action. But you'd need to ask them for details.
