### ISSUE TITLE
Fast initial calloc

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#4334]
If calloc returns a range of memory that was never used, we don't need to zero it out, as typed arrays start that way. Subsequent use though can't do this. But it would still help especially during startup, perhaps.

**Comment by juj** [comment]
Linking back to the original emscripten-discuss conversation for reference, here: https://groups.google.com/forum/#!topic/emscripten-discuss/GEftClbwmYg

Test case:

    #include <iostream>
    #include <vector>
    #include <chrono>

    using double_sec = std::chrono::duration<double, std::ratio<1>>;

    template <typename Func,typename... Args>
    double profile(Func f, Args&&... args)
    {
     using namespace std::chrono;
     auto start = system_clock::now();
     
      f(std::forward<Args>(args)...);
     
     return duration_cast<double_sec>(system_clock::now() - start).count();
    }


    int main() {

     std::size_t n = 48000000;
     auto t1 = profile([](std::size_t n)
     {
      void* ptr = malloc(n);
      free(ptr);
     }, n);
     auto t2 = profile([](std::size_t n)
      { 
       std::vector<unsigned char> vec(n); 
      }, n);

     auto t3 = profile([](std::size_t n)
     {
      std::vector<unsigned char> vec;
      vec.resize(n);
     }, n);

     auto t4 = profile([](std::size_t n)
     {
      std::vector<unsigned char> vec;
      vec.reserve(n);
     }, n);

     
     std::cout << "malloc/free: " << t1 << "s"<< std::endl;
     std::cout << "vector ctor: " << t2 << "s" << std::endl;
     std::cout << "vector resize: " << t3 << "s" << std::endl;
     std::cout << "vector reserve: " << t4 << "s" << std::endl;
     
     return 0;
    }

**Comment by juj** [comment]
Building above test case with `em++ vectorspeed.cpp -o a.html -std=c++11 -s TOTAL_MEMORY=134217728 -O1 -g2`, I get

	malloc/free: 0s
	vector ctor: 0.112s
	vector resize: 0.129s
	vector reserve: 0s

(Higher optimization flags would optimize out the operations altogether, resulting in 0s in each test). Reading through the generated asm.js code, it looks like

	auto t2 = profile([](std::size_t n)
	 { 
	  std::vector<unsigned char> vec(n); 
	 }, n);

generates

	function __ZZ4mainENK3__1clEj($n) {
	 $n = $n|0;
	 var $vec = 0, label = 0, sp = 0;
	 sp = STACKTOP;
	 STACKTOP = STACKTOP + 16|0;
	 $vec = sp;
	 __ZNSt3__16vectorIhNS_9allocatorIhEEEC2Ej($vec,$n);
	 __ZNSt3__113__vector_baseIhNS_9allocatorIhEEED2Ev($vec);
	 STACKTOP = sp;return;
	}

where the call to the allocator is

	function __ZNSt3__16vectorIhNS_9allocatorIhEEEC2Ej($this,$__n) {
	 $this = $this|0;
	 $__n = $__n|0;
	 var $__end_$i = 0, $__end_cap_$i = 0, $cmp = 0, label = 0, sp = 0;
	 sp = STACKTOP;
	 HEAP32[$this>>2] = 0;
	 $__end_$i = ((($this)) + 4|0);
	 HEAP32[$__end_$i>>2] = 0;
	 $__end_cap_$i = ((($this)) + 8|0);
	 HEAP32[$__end_cap_$i>>2] = 0;
	 $cmp = ($__n|0)==(0);
	 if ($cmp) {
	  return;
	 }
	 __ZNSt3__16vectorIhNS_9allocatorIhEEE8allocateEj($this,$__n);
	 __ZNSt3__16vectorIhNS_9allocatorIhEEE18__construct_at_endEj($this,$__n);
	 return;
	}

and there the call to `construct_at_end` is

	function __ZNSt3__16vectorIhNS_9allocatorIhEEE18__construct_at_endEj($this,$__n) {
	 $this = $this|0;
	 $__n = $__n|0;
	 var $0 = 0, $1 = 0, $__end_ = 0, $__n$addr$0 = 0, $cmp = 0, $dec = 0, $incdec$ptr = 0, label = 0, sp = 0;
	 sp = STACKTOP;
	 $__end_ = ((($this)) + 4|0);
	 $__n$addr$0 = $__n;
	 while(1) {
	  $0 = HEAP32[$__end_>>2]|0;
	  HEAP8[$0>>0] = 0;
	  $1 = HEAP32[$__end_>>2]|0;
	  $incdec$ptr = ((($1)) + 1|0);
	  HEAP32[$__end_>>2] = $incdec$ptr;
	  $dec = (($__n$addr$0) + -1)|0;
	  $cmp = ($dec|0)==(0);
	  if ($cmp) {
	   break;
	  } else {
	   $__n$addr$0 = $dec;
	  }
	 }
	 return;
	}

Mapping this back to `system/include/libcxx/vector`, there's the `__construct_at_end` function, which reads

	//  Default constructs __n objects starting at __end_
	//  throws if construction throws
	//  Precondition:  __n > 0
	//  Precondition:  size() + __n <= capacity()
	//  Postcondition:  size() == size() + __n
	template <class _Tp, class _Allocator>
	void
	vector<_Tp, _Allocator>::__construct_at_end(size_type __n)
	{
	    allocator_type& __a = this->__alloc();
	    do
	    {
	        __RAII_IncreaseAnnotator __annotator(*this);
	        __alloc_traits::construct(__a, _VSTD::__to_raw_pointer(this->__end_));
	        ++this->__end_;
	        --__n;
	        __annotator.__done();
	    } while (__n > 0);
	}

I think the performance difference comes from that libcxx is missing out on an optimization, and it's doing a loop of u8 stores to construct the `unsigned char`s, instead of optimizing that to a single call to `memset` for example.

Does a newer libcxx have that kind of optimization? Then pull request #4288 might bring it in. If not, then this sounds like an issue to take up to libcxx.

@kripken: Not sure about the `calloc` optimization, it might be too narrow to be useful. Although it certainly looks like it would not improve this performance issue, since this is not calling to `calloc`? (err, did I piggyback this issue and the test case into unrelated conversations(?))

**Comment by kripken** [comment]
Nice analysis!

#4288 landed, so we are at libcxx from 2 weeks ago. So probably they didn't add more since then.

libc++ is probably assuming llvm can turn that loop into a memset. Maybe the question is why it doesn't.

Regarding calloc, given this analysis, it seems unlikely to be worth optimizing. **In theory**, though, if we knew a memset to 0 were happening to memory never used before, we could make it a no-op. But I don't see a way to do that here. Seems like libc++ should call calloc, then we could optimize that..?

**Comment by dherre3** [comment]
Hello! Thank you for all your nice work. I was wondering if you ever got around to optimizing calloc, or whether it is using _memset_ all the time? Thank you!

**Comment by kripken** [comment]
I don't think anyone looked into optimizing calloc yet. Would be an interesting investigation though. Probably in dlmalloc, if we use sbrk for calloc, then we know it will be all zeros, but otherwise not.

**Comment by kripken** [comment]
Still worth optimizing, I think, if someone has time.
