### ISSUE TITLE
Is LLVM's Intrinsic llvm.sin.f64 unsupported?

### ISSUE THREAD

**Issue by Maher4Ever** [emscripten-core/emscripten#4338]
Hello Emscripten devs!

I'm trying to compile an LLVM IR file to JS using emscripten. Some functions in that file use the Sin function and it's declared as follows:

``` llvm
declare double @llvm.sin.f64(double) #2

; Other code ...

attributes #2 = { nounwind readnone }
```

When I compile my LLVM IR file, `emcc` complains about a missing sin function:

```
warning: unresolved symbol: llvm_sin_f64
```

I noticed that the dots are replaced with underscores in the function name, but my files doesn't contain any references to that function; only to the standard LLVM one with dots.

Since `emcc` can't find this function it has an incomplete implementation in the generated JS:

``` Javascript
function _llvm_sin_f64() {
  Module['printErr']('missing function: llvm_sin_f64'); abort(-1);
}
```

I'm running the 64 bit version of emscripten from the `incoming` branch.

Is the `@llvm.sin.f64` intrinsic unsupported? Or is this a bug?

**Comment by kripken** [comment]
This does look like a bug. We should implement it the same way as `lllvm.fabs.*` etc., in fastcomp's `lib/Target/JSBackend/CallHandlers.h`. Alternatively it could be added to `library.js`, which would make it work, but be a slower call out of asm.js.

**Comment by Maher4Ever** [comment]
I tried only modifying `CallHandler.h` in fastcomp and redirecting the call to the Math Sin function, but that didn't work. I also had to redirect the call in `library.js`. Now It's working, I'll run the tests and if everything goes fine I'll submit a pull request.

**Comment by Maher4Ever** [comment]
I submitted the fix as promised above. I ran the complete test suite and everything passed.
