### ISSUE TITLE
How to set gcc flags?

### ISSUE THREAD

**Issue by bobvanluijt** [emscripten-core/emscripten#4359]
Hi all,

I compile with the following command:

`gcc -Wall -march=native -O3 -ffast-math -I/usr/local/include -I/usr/local/include -o waon main.o notes.o midi.o analyse.o fft.o hc.o snd.o -L/usr/local/lib -L/usr/local/lib -lfftw3 -L/usr/local/lib -lsndfile -lm`
I now would like to compile with Emscripten. How do I convert the above `gcc` command into an `emcc` command?

Thanks,

PS:
Also asked here: http://stackoverflow.com/questions/37422269/how-to-set-gcc-flags-in-emscripten

**Comment by kripken** [comment]
Generally you just replace `gcc` with `emcc`. However, this is cross-compiling, so those includes of local system headers are not going to work, you need to include and also link with portable code, either emscripten's built-in system headers and libs, or code that has been ported with them.

**Comment by bobvanluijt** [comment]
Hi Kripken,

Thanks for getting back! Not 100% I understand what you mean with: "so those includes of local system headers are not going to work, you need to include and also link with portable code". Can I find an example of this somewhere?

**Comment by kripken** [comment]
See [this page](http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries) and [this faq entry](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-do-i-link-against-system-libraries-like-sdl-boost-etc).
