### ISSUE TITLE
Fullscreen operation detaches any sibling

### ISSUE THREAD

**Issue by zobertke** [emscripten-core/emscripten#4370]
With this pr: https://github.com/kripken/emscripten/issues/2053 the functionality changed in such way, that canvas is always temporarily detached from the DOM and wrapped in a temp div during fullscreen.
The problem with this is that we need sometimes to temporarily have a full screen overlay over the canvas(ex . video player) and it is impossible as the original DOM structure is not kept during fullscreen.
The overlay is temporary (not to affect the performance). What if there we would leave the possibility for the user to inject the existing canvas container and have the temp div creation as a fallback? In this case the DOM would not be altered while we go to fullscreen.
I was thinking something like this:
https://github.com/kripken/emscripten/pull/4369

**Comment by juj** [comment]
Could you instead use the HTML5 API for managing entering and exiting fullscreen? That is a separate implementation that does not change the DOM in any way (but does change CSS styles), and enters any given DOM element to fullscreen. See here http://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#fullscreen for the documentation and https://github.com/kripken/emscripten/blob/master/tests/test_html5_fullscreen.c#L130 for an example.

**Comment by zobertke** [comment]
Thanks for the feedback, that is what I did finally, but in that case I needed to take care separately of resizing the canvas too. But it works.
