### ISSUE TITLE
Windows 7 "emsdk activate latest" configuration file path missing slash

### ISSUE THREAD

**Issue by Brenden-Morales** [emscripten-core/emscripten#4376]
There seems to be a problem with the latest emscripten (1.35.0) install procedure on windows 7. I tried all three installers for windows and they all gave a similar error :

`C:\Users\MyUser\Desktop\emsdk-1.35.0-portable-64bit>emsdk activate latest`

`Writing .emscripten configuration file to user home directory C:UsersMyUser/.emscripten`

Clearly it's missing a slash when specifying the path, right? What needs to be done to fix this?

**Comment by juj** [comment]
Hmm, that looks odd. Tried this locally, and I'm getting

	C:\code\emsdk>emsdk activate latest
	Writing .emscripten configuration file to user home directory C:\Users\Jukka/
	The SDK/tool 'clang-e1.35.0-64bit' cannot be activated since it is not installed! Skipping this tool...
	The SDK/tool 'emscripten-1.35.0' cannot be activated since it is not installed! Skipping this tool...
	The SDK/tool 'sdk-1.35.0-64bit' cannot be activated since it is not installed! Skipping this tool...
	The Emscripten configuration file C:\Users\Jukka\.emscripten has been rewritten with the following contents:

	import os
	JAVA='C:/code/emsdk/java/7.45_64bit/bin/java.exe'
	EMSCRIPTEN_ROOT='C:/code/emsdk/emscripten/incoming'
	EMSCRIPTEN_NATIVE_OPTIMIZER='C:/code/emsdk/emscripten/incoming_64bit_optimizer/RelWithDebInfo/optimizer.exe'
	NODE_JS='C:/code/emsdk/node/4.1.1_64bit/bin/node'
	PYTHON='C:/code/emsdk/python/2.7.5.3_64bit/python.exe'
	SPIDERMONKEY_ENGINE = ''
	V8_ENGINE = ''
	TEMP_DIR = 'c:/users/jukka/appdata/local/temp'
	COMPILER_ENGINE = NODE_JS
	JS_ENGINES = [NODE_JS]

	The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to permanently register this environment globally to all users in Windows Registry, rerun this command with the option --global.

	C:\code\emsdk>

Can you try installing emsdk portable via

   > git clone https://github.com/juj/emsdk.git
   > cd emsdk
   > emsdk install latest
   > emsdk activate latest

(the version from github is some commits ahead of the downloadable installer) Does that give the same error?

**Comment by Brenden-Morales** [comment]
Same thing.

```
Traceback (most recent call last):
  File "C:\Users\UserName\git\emsdk\\emsdk", line 1861, in <module>
    sys.exit(main())
  File "C:\Users\UserName\git\emsdk\\emsdk", line 1804, in main
    tools_to_activate = set_active_tools(tools_to_activate, permanently_activate=permanently_activate)
  File "C:\Users\UserName\git\emsdk\\emsdk", line 1410, in set_active_tools
    generate_dot_emscripten(tools_to_activate)
  File "C:\Users\UserName\git\emsdk\\emsdk", line 829, in generate_dot_emscripten
    with open(dot_emscripten_path(), "w") as text_file: text_file.write(cfg)
IOError: [Errno 2] No such file or directory: 'C:UsersUserName/.emscripten'
```

In the meantime I got everything working fine in a linux VM. I think I might try this out on my home Windows 10 install just to see if I get something different.

**Comment by juj** [comment]
Hmm, that's peculiar. If you print out the internal `emscripten_config_directory = os.path.expanduser("~/")` variable in https://github.com/juj/emsdk/blob/master/emsdk#L61, what does that say? (`print(emscripten_config_directory)`)

Also, what do the following environment variables print as result in command prompt?

    set %HOMEDRIVE%
    set %HOMEPATH%
    set %USERPROFILE%

**Comment by xGreylee** [comment]
same problem as @Brenden-Morales ..
any solution for this ?

**Comment by xGreylee** [comment]
same problem as @juj ...
any solutions for this ?

**Comment by Brenden-Morales** [comment]
Man, in the end I just made a linux VM and worked through that.

**Comment by xGreylee** [comment]
ok, I had resolved this in another way,thx dude @Brenden-Morales
