### ISSUE TITLE
We implement but don't declare usleep()

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4394]
Curiously, noticed that we do have an implementation of `usleep`, in https://github.com/kripken/emscripten/blob/master/src/library_pthread_stub.js#L156 (singlethreaded) and https://github.com/kripken/emscripten/blob/master/system/lib/pthread/library_pthread.c#L235 (multithreaded), but we don't declare the function in our musl headers. The declaration is in https://github.com/kripken/emscripten/blob/incoming/system/include/libc/unistd.h#L154 which is inaccessible due to the preprocessor definitions being excluded:

```
#if defined(_GNU_SOURCE) || defined(_BSD_SOURCE) \
 || (defined(_XOPEN_SOURCE) && _XOPEN_SOURCE+0 < 700)
int usleep(unsigned);
unsigned ualarm(unsigned, unsigned);
#endif
```

Should we define one of those preprocessor defines for Emscripten builds? (perhaps not) Or should we rather add a 

```
#ifdef __EMSCRIPTEN__
int usleep(unsigned);
#endif
```

section there?

**Comment by kripken** [comment]
I'd be ok with either. Maybe the last option, in `include/compat` (so we don't touch musl)?

**Comment by juj** [comment]
Hmm, that would require users to add a new #include in their code?

Btw, what is the intent of the #defines `_GNU_SOURCE`/`_BSD_SOURCE`/`_XOPEN_SOURCE`? Are those something fixed when musl is targeting a specific platform, or are there config options that calling code should be able to configure in some scenarios?

One another way might be to just add `__EMSCRIPTEN__` to that list, i.e.

    #if defined(_GNU_SOURCE) || defined(_BSD_SOURCE) \
     || (defined(_XOPEN_SOURCE) && _XOPEN_SOURCE+0 < 700)
     || defined(__EMSCRIPTEN__) // XXX Emscripten
    int usleep(unsigned);
    unsigned ualarm(unsigned, unsigned);
    #endif

although we don't implement `ualarm` (we can't implement "hard" support for that, but could emulate it and other signals like we already do cooperatively for thread cancellation)

**Comment by kripken** [comment]
`compat` is earlier, and with `include_next` (see examples there) it includes the musl one. So users would not need a new include.

No idea what `GNU_SOURCE` etc. are. But I'd be wary of defining one of those...

I'm also ok with the last option you mentioned.
