### ISSUE TITLE
Unsupported integer vector type Int64x2

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4395]
Here is an example of a problematic Int64x2 usage that was mentioned recently:

https://dl.dropboxusercontent.com/u/40949268/emcc/bugs/unsupported_integer_vector_type_int64x2.bc

run `llc unsupported_integer_vector_type_int64x2.bc -march=js -filetype=asm -o a.js -emscripten-global-base=8 -O3 -emscripten-no-exit-runtime`

which will give

```
LLVM ERROR: Unsupported integer vector type with numElems: 2, primitiveSize: 64!
```

that comes from a

```
<2 x i64>
i64 bitcast (double extractelement (<2 x double> bitcast (<4 x i32> <i32 0, i32 0, i32 undef, i32 undef> to <2 x double>), i32 0) to i64)
LLVM ERROR: legalization problem
```

SIMD.js does have Float64x2 (in our unofficial polyfill), but it doesn't have Int64x2. I wonder if that `llc` step should be prepared to handle Int64x2 internally, or did things go bad already previously when such a `<2 x i64>` type was introduced into the bitcode?

**Comment by kripken** [comment]
The full relevant line is

````
%add.i.i.i.i1169 = fadd fast <4 x float> %119, bitcast (
  <2 x i64> <i64 bitcast (
    double extractelement (
      <2 x double> bitcast (
        <4 x i32> <i32 0, i32 0, i32 undef, i32 undef> to <2 x double>
      ), i32 0
    ) to i64
  ), i64 0> to <4 x float>
)
````

That's an odd pattern I've never seen before. It would be good to understand what generated it. If possible, we should not run an optimization that creates such things, unless there is some easy workaround to handle it internally, but in my experience, the better solution is to avoid generating it in the first place.

**Comment by juj** [comment]
Here's a small test case (thanks to Philip!):

	#include <emmintrin.h>
	 
	typedef unsigned long long ssp_u64;
	 
	typedef union
	{
	    __m128i i;
	    ssp_u64 u64[2];
	} ssp_m128;
	 
	int main(int argc, char** argv)
	{
	    ssp_m128 t;
	    t.i = _mm_packs_epi32(t.i, _mm_setzero_si128());
	    return t.u64[0] != 0;
	}

Building with `em++ s.cpp -o s.js -msse2 -O1` (or `-Os`, `-O2`, or `-O3`):

      %t.sroa.0.0.vec.extract.extract = extractelement <2 x i64> %dst.i.sroa.0.0.dst.i.sroa.0.0.30, i32 0
    Assertion failed: 0 && "some i64 thing we can't legalize yet. possible hint: optimize with -O0 or -O2+, and not -O1", file C:\code\emsdk\clang\fastcomp\src\lib\Target\JSBackend\NaCl\ExpandI64.cpp, line 972
    #0 0x00007ff796cbd325 rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0xccd325)
    #1 0x00007ffba3b68b68 raise (C:\WINDOWS\SYSTEM32\ucrtbase.dll+0x68b68)
    #2 0x00007ffba3b698e1 abort (C:\WINDOWS\SYSTEM32\ucrtbase.dll+0x698e1)
    #3 0x00007ffba3b6b67a _get_wpgmptr (C:\WINDOWS\SYSTEM32\ucrtbase.dll+0x6b67a)
    #4 0x00007ffba3b6b571 _get_wpgmptr (C:\WINDOWS\SYSTEM32\ucrtbase.dll+0x6b571)
    #5 0x00007ffba3b6b8cf _wassert (C:\WINDOWS\SYSTEM32\ucrtbase.dll+0x6b8cf)
    #6 0x00007ff796ddc078 rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0xdec078)
    #7 0x00007ff796dd825e rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0xde825e)
    #8 0x00007ff7968d5293 rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0x8e5293)
    #9 0x00007ff7968d4706 rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0x8e4706)
    #10 0x00007ff79604d050 rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0x5d050)
    #11 0x00007ff796054b1d rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0x64b1d)
    #12 0x00007ff796ef7810 rl_relooper_calculate (C:\code\emsdk\clang\fastcomp\build_incoming_vs2015_64\RelWithDebInfo\bin\llc.exe+0xf07810)
    #13 0x00007ffba5e78102 BaseThreadInitThunk (C:\WINDOWS\system32\KERNEL32.DLL+0x18102)
    #14 0x00007ffba839c5b4 RtlUserThreadStart (C:\WINDOWS\SYSTEM32\ntdll.dll+0x5c5b4)
    Traceback (most recent call last):
      File "C:\code\emsdk\emscripten\incoming\\em++", line 13, in <module>
        emcc.run()
      File "C:\code\emsdk\emscripten\incoming\emcc.py", line 1481, in run
        final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
      File "C:\code\emsdk\emscripten\incoming\tools\shared.py", line 1685, in emscripten
        call_emscripten(cmdline)
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1721, in _main
        temp_files.run_and_clean(lambda: main(
      File "C:\code\emsdk\emscripten\incoming\tools\tempfiles.py", line 64, in run_and_clean
        return func()
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1726, in <lambda>
        DEBUG=DEBUG,
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 1627, in main
        temp_files=temp_files, DEBUG=DEBUG)
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 86, in emscript
        funcs, metadata, mem_init = get_and_parse_backend(infile, settings, temp_files, DEBUG)
      File "C:\code\emsdk\emscripten\incoming\emscripten.py", line 153, in get_and_parse_backend
        start_funcs = backend_output.index(start_funcs_marker)
    ValueError: substring not found

Generated bitcode with `-Os` looks like this:

    ; ModuleID = 's.bc'
    target datalayout = "e-p:32:32-i64:64-v128:32:128-n32-S128"
    target triple = "asmjs-unknown-emscripten"

    %union.anon = type { [4 x i32] }
    %union.anon.0 = type { <4 x i32> }

    ; Function Attrs: norecurse nounwind optsize readnone
    define i32 @main(i32 %argc, i8** nocapture readnone %argv) #0 {
    entry:
      %src.i = alloca %union.anon, align 16
      %src2.i = alloca %union.anon, align 16
      %dst.i = alloca %union.anon.0, align 16
      %0 = bitcast %union.anon* %src.i to i8*
      call void @llvm.lifetime.start(i64 16, i8* %0) #2
      %1 = bitcast %union.anon* %src2.i to i8*
      call void @llvm.lifetime.start(i64 16, i8* %1) #2
      %2 = bitcast %union.anon.0* %dst.i to i8*
      call void @llvm.lifetime.start(i64 16, i8* %2) #2
      %m1.i = bitcast %union.anon* %src2.i to <4 x i32>*
      store <4 x i32> zeroinitializer, <4 x i32>* %m1.i, align 16, !tbaa !1
      %x12.i = bitcast %union.anon.0* %dst.i to [8 x i16]*
      br label %for.body.i

    for.body.i:                                       ; preds = %for.body.i, %entry
      %i.02.i = phi i32 [ 0, %entry ], [ %inc.i, %for.body.i ]
      %arrayidx.i = getelementptr inbounds %union.anon, %union.anon* %src.i, i32 0, i32 0, i32 %i.02.i
      %3 = load i32, i32* %arrayidx.i, align 4, !tbaa !4
      %cmp2.i = icmp sgt i32 %3, -32769
      %cmp5.i = icmp sgt i32 %3, 32767
      %..i = select i1 %cmp5.i, i32 32767, i32 %3
      %4 = trunc i32 %..i to i16
      %conv.i = select i1 %cmp2.i, i16 %4, i16 -32768
      %arrayidx13.i = getelementptr inbounds [8 x i16], [8 x i16]* %x12.i, i32 0, i32 %i.02.i
      store i16 %conv.i, i16* %arrayidx13.i, align 2, !tbaa !6
      %arrayidx15.i = getelementptr inbounds %union.anon, %union.anon* %src2.i, i32 0, i32 0, i32 %i.02.i
      %5 = load i32, i32* %arrayidx15.i, align 4, !tbaa !4
      %cmp16.i = icmp sgt i32 %5, -32769
      %cmp20.i = icmp sgt i32 %5, 32767
      %.1.i = select i1 %cmp20.i, i32 32767, i32 %5
      %6 = trunc i32 %.1.i to i16
      %conv30.i = select i1 %cmp16.i, i16 %6, i16 -32768
      %add.i = add nuw nsw i32 %i.02.i, 4
      %arrayidx32.i = getelementptr inbounds [8 x i16], [8 x i16]* %x12.i, i32 0, i32 %add.i
      store i16 %conv30.i, i16* %arrayidx32.i, align 2, !tbaa !6
      %inc.i = add nuw nsw i32 %i.02.i, 1
      %exitcond.i = icmp eq i32 %inc.i, 4
      br i1 %exitcond.i, label %_ZL15_mm_packs_epi32Dv4_iS_.exit, label %for.body.i

    _ZL15_mm_packs_epi32Dv4_iS_.exit:                 ; preds = %for.body.i
      %7 = bitcast %union.anon.0* %dst.i to <2 x i64>*          // XXXXXXXXXXXXX
      %8 = load <2 x i64>, <2 x i64>* %7, align 16, !tbaa !1
      call void @llvm.lifetime.end(i64 16, i8* nonnull %2) #2
      call void @llvm.lifetime.end(i64 16, i8* nonnull %1) #2
      call void @llvm.lifetime.end(i64 16, i8* nonnull %0) #2
      %t.sroa.0.0.vec.extract.extract = extractelement <2 x i64> %8, i32 0
      %cmp = icmp ne i64 %t.sroa.0.0.vec.extract.extract, 0
      %conv = zext i1 %cmp to i32
      ret i32 %conv
    }

    ; Function Attrs: argmemonly nounwind
    declare void @llvm.lifetime.start(i64, i8* nocapture) #1

    ; Function Attrs: argmemonly nounwind
    declare void @llvm.lifetime.end(i64, i8* nocapture) #1

    attributes #0 = { norecurse nounwind optsize readnone "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
    attributes #1 = { argmemonly nounwind }
    attributes #2 = { nounwind }

    !llvm.ident = !{!0}

    !0 = !{!"clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 4fddcbc67c8950a54b169030ad9b2d66288d5d5f) (https://github.com/kripken/emscripten-fastcomp/ 21f1267bad4d8c523fae483104d4348cfb279cfe) (emscripten 1.36.5 : 1.36.5)"}
    !1 = !{!2, !2, i64 0}
    !2 = !{!"omnipotent char", !3, i64 0}
    !3 = !{!"Simple C/C++ TBAA"}
    !4 = !{!5, !5, i64 0}
    !5 = !{!"int", !2, i64 0}
    !6 = !{!7, !7, i64 0}
    !7 = !{!"short", !2, i64 0}

The interesting bit above marked with `// XXXXXXXXXXXXX`, which corresponds to `_mm_packs_epi32` implementation, specifically this line with `return` statement: https://github.com/kripken/emscripten/blob/master/system/include/emscripten/emmintrin.h#L2175

However in no place in that code do we have `i64`s involved, and somehow LLVM is thinking it's ok to introduce `<i64 x 2>` in there. I'm not sure if that is the problem, or if LLVM should be allowed to do that, and then the the breaking down to `i32`s should happen elsewhere. How does that look to you?

**Comment by kripken** [comment]
It's because of the union, I believe. We don't have a vector type of i64, but we have 2 i64s and they alias an actual vector type. Seems reasonable for LLVM to emit an `<i64 x 2>` there for the bitcast.

Hopefully this is something we can work around in the source. I verified that replacing the i64 array of 2 with an i32 array of 4 does not hit any problem.

**Comment by chris-rudmin** [comment]
@kripken Do you have any updates on this issue? I have encountered this error when compiling libopus with intrinsics enabled.

**Comment by kripken** [comment]
No updates I am aware of. Can you work around it in the source as suggested above?

**Comment by chris-rudmin** [comment]
I took a look, but I'm not familiar enough with the sources to implement a workaround. For the time being I will disable intrinsics.

**Comment by skal65535** [comment]
Hi

here's a small sample that generates the same error:
`LLVM ERROR: Unsupported integer vector type with numElems: 2, primitiveSize: 64!`
but isn't using an union:

```
#include <emmintrin.h>
int main(int argc,const char** argv) {
  const __m128i A = _mm_loadu_si128((const __m128i*)argv[0]);                    
  const __m128i B = _mm_srli_epi64(A, 32); 
  _mm_storel_epi64((__m128i*)argv[0], B);  
  return 0;
}
```

I compile it with: emcc -o test.js main.c -msse2 -O1
but the error occurs with -Os -O2 -O3 too.

hope it helps!
skal/

**Comment by elspru** [comment]
It's because emscripten only supports a limited number of SIMD vectors, 
it specifically mentioned int64x2 as unsupported:
https://kripken.github.io/emscripten-site/docs/porting/simd.html

**Comment by juj** [comment]
Thanks @skal65535. These kinds of test cases will be useful. SIMD is currently planned to be revisited to be reintroduced to WebAssembly, at which point WebAssembly will likely have a Int64x2 type, which allows implementing direct support to these operations.

**Comment by ThorstenBux** [comment]
Hi everyone, any update on this or on SIMD support for WASM?

**Comment by tlively** [comment]
@ThorstenBux SIMD support in the tools is under way and making fast progress. Upstream LLVM has a more-or-less complete implementation of the current SIMD proposal in the wasm backend, and work on Binaryen is ongoing. Look for PRs adding SIMD support over then next few weeks to Binaryen followed by Emscripten.

**Comment by ThorstenBux** [comment]
Hi @tlively thanks for your fast and helpful response, much appreciated. One follow-up if you got the time. Would SIMD compiled code have a performance increase on mobile platforms (Android, iOS) or only on Desktop?
Thanks

**Comment by tlively** [comment]
@ThorstenBux Yes, a design goal of the SIMD proposal is to achieve speedup on all common platforms where wasm is run and where SIMD support is available in the hardware.
