### ISSUE TITLE
emscripten code fails to work under nashorn (jjs)

### ISSUE THREAD

**Issue by user1095108** [emscripten-core/emscripten#4400]
The error message is:

v.js:137 ReferenceError: "read" is not defined

The relevant javascript code is:

```
  Module['readBinary'] = function readBinary(f) {
    if (typeof readbuffer === 'function') {
      return new Uint8Array(readbuffer(f));
    }
    var data = read(f, 'binary'); // bug is here
    assert(typeof data === 'object');
    return data;
  };
```

**Comment by kripken** [comment]
We probably would need to add support for nashorn's approach to read/write etc., like we have for node, sm shell, v8 shell.

**Comment by bzz** [comment]
@kripken sorry for digging this up and thank you very much for prompt help! 

Could you please advise, what would be the relevant place to start looking into adding such support? Thanks in advance!

**Comment by kripken** [comment]
`src/shell.js` contains all the "glue" to work in various environments. The section for "SHELL" might be the right place for nashorn (but if it's very different than other shells, might need a different approach).
