### ISSUE TITLE
Use TextDecoder to optimize decoding C strings to JS

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#4402]
There is a recent API for this,

https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/decode

Looks like it's currently in firefox and chrome.

We could check if it's present and use it if so, instead of the probably much slower code we have now that does it manually in JS, which is in `Pointer_stringify` in `src/preamble.js` (there is TODO there for this).

**Comment by hackcasual** [comment]
One possibility for fallback might be https://github.com/coolaj86/TextEncoderLite

**Comment by hackcasual** [comment]
Looks like this may only be suitable for utf8 going forward: https://www.chromestatus.com/feature/5630760492990464

**Comment by juj** [comment]
@hackcasual: hmm, that article refers specifically to `TextEncoder`. We don't use `TextEncoder` at all, at least not yet, but only `TextDecoder` (as introduced by #4403). I wonder if `TextDecoder` has the same limitation of not supporting UTF-16 in the future? With quick searching, couldn't find a paragraph about that at least.

**Comment by juj** [comment]
So far functions `UTF8ArrayToString` and `UTF16ToString` use `TextDecoder`, though only if `-s TEXTDECODER=1` linker flag is specified. `Pointer_stringify` calls to `UTF8ArrayToString` if the input string contains UTF-8, so it gets TextDecoder in that case. If the input string does not contain UTF-8, `Pointer_stringify` does a chunked `String.fromCharCode.apply(String, HEAPU8.subarray(ptr, ptr + Math.min(length, MAX_CHUNK)))` approach. Perhaps that part could be turned into a `TextDecoder` based version, but will need benchmarking to know if that's a win.
