### ISSUE TITLE
[SDL2] Problem with SDL_RWFromMem

### ISSUE THREAD

**Issue by mockthebear** [emscripten-core/emscripten#4406]
Basically i was trying the same thing on this example:
https://github.com/kripken/emscripten/blob/master/tests/sdl_stb_image_data.c

`FILE _f = fopen(name.c_str(), "rb");
                fseek(f, 0L, SEEK_END);
                int sz = ftell(f);
                fseek(f, 0L, SEEK_SET);
                char_ buffer = (char*)malloc(sz);
                fread(buffer, sz, 1, f);
                fclose(f);
                SDL_Surface *image = IMG_Load_RW(SDL_RWFromMem(buffer, sz), 1);
                if (!image)
                {
                    printf("IMG_Load: %s\n", IMG_GetError());
                    return 0;
                }

```
            printf("load succeeded\n");
            SDL_FreeSurface (image);`
```

So yeah, i am trying open an file called "test.png". When i try this using the default gcc compiler, it works okay, But when i try on emscripten, i just got the error
IMG_Load: Unsupported image format

Actually i designed my aplication to load an file with N assets, then it return every asset as an SDLRWop created from SDL_RWFromMem;

If i just load the file using
`SDL_RWFromFile(name.c_str(),"rb");`
it will work. Any idea why i there is this "bug" that dont allow me load png files from memmory?

**Comment by juj** [comment]
You can run the test with `python tests/runner.py browser.test_sdl_stb_image_data`. That test loads a .jpg, but if I rename src/test_browser.py line ~574 (def test_sdl_stb_image_data(self):) to load a .png instead of .jpg, it does work properly. Does the test pass for you?

**Comment by mockthebear** [comment]
Tried without any changes:

C:\Program Files\Emscripten\emscripten\1.35.0>python tests/runner.py browser.test_sdl_stb_image_data
WARNING:root:use EM_ALL_ENGINES=1 in the env to run against all JS engines, which is slower but provides more coverage
[Browser harness server on process 7140]

Running the browser tests. Make sure the browser allows popups from localhost.

test_sdl_stb_image_data (test_browser.browser) ... [browser launch: test.html ]
ERROR
[Browser harness server terminated]

======================================================================
ERROR: test_sdl_stb_image_data (test_browser.browser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tests\test_browser.py", line 461, in test_sdl_stb_image_data
    self.btest('sdl_stb_image_data.c', reference='screenshot.jpg', args=['-s', 'STB_IMAGE=1', '--preload-file', 'screenshot.not'])
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tests\runner.py", line 813, in btest
    self.run_browser(outfile + url_suffix, message, ['/report_result?' + e for e in expected], timeout=timeout)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tests\runner.py", line 672, in run_browser
    self.assertIdentical(expectedResult, output)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tests\runner.py", line 395, in assertIdentical
    limit_size(''.join([a.rstrip()+'\n' for a in difflib.unified_diff(x.split('\n'), y.split('\n'), fromfile='expected', tofile='actual')]))
Exception: Expected to have '/report_result?0' == '[no http server activity]', diff:

--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+[no http server activity]


----------------------------------------------------------------------
Ran 1 test in 12.854s

FAILED (errors=1)

**Comment by mockthebear** [comment]
i guess anyone can figureout what is happening?

**Comment by juj** [comment]
Did the harness launch a browser window to run the test in? If so, which browser did it launch, perhaps there is a browser-specific issue. The test does pass unchanged on the current Windows, Linux and OS X unit test servers. Those test in Firefox with `set EMSCRIPTEN_BROWSER="C:/Program Files (x86)/Mozilla Firefox/firefox.exe"`.

Also I see this is on Emscripten 1.35.0, you could try installing the latest incoming, I can't recall but there might have been some fixes in trunk.
