### ISSUE TITLE
LLVM version appears incorrect (seeing "(tags/RELEASE_380/final)" , expected "3.4")

### ISSUE THREAD

**Issue by grapechenxy** [emscripten-core/emscripten#4407]
Hey I got this error when I run emcc -v: LLVM version appears incorrect (seeing "(tags/RELEASE_380/final)" , expected "3.4")
I've uppdated to the latest version of emscripten and LLVM(3.8.1). Since it especially mentioned LLVM 3.4, I tried to install this version as well, but it said "is not recoverable: exiting now".

Could anyone help me? thanks!

**Comment by kripken** [comment]
What version of emscripten are you using? If it expects 3.4, it sounds like an old one. Best to use the SDK to get a recent version (or build from source).

**Comment by peterdelevoryas** [comment]
I am also getting this error. (I included my clang and distribution version output, in case that might be helpful) I was following the instructions for building from source [here](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#platform-notes-installation-instructions-portable-sdk).
![2017-02-22-131819_564x506_scrot](https://cloud.githubusercontent.com/assets/8096834/23230492/6a3b2020-f901-11e6-948a-b6ffcefb753c.png)
