### ISSUE TITLE
unresolved symbol timerfd_create

### ISSUE THREAD

**Issue by seibelj** [emscripten-core/emscripten#4414]
My code contains:

``` c
#include <sys/timerfd.h>
timerfd_create(CLOCK_REALTIME, TFD_NONBLOCK);
```

emcc says `warning: unresolved symbol: timerfd_create`

javascript logs `missing function: timerfd_create`

Pulling my hair out trying to debug this, am I missing something basic? Thanks for your time.

**Comment by kripken** [comment]
Looks like we don't have this in our libc. musl does have it, under `linux/` (linux-specific additions). However, since this interacts with `epoll` etc., it might not be easy to get working in a browser environment. Probably best to look for an alternative to using it.

**Comment by seibelj** [comment]
Gotcha, thanks!

**Comment by meelash** [comment]
> musl

@kripken what is musl? Sorry if this is a noob question. I was going to use: https://github.com/fd00/cygepoll/blob/master/epoll.c for the epoll and hoping I could get something timerfd somehow.

**Comment by meelash** [comment]
> > musl
> 
> @kripken what is musl? Sorry if this is a noob question. I was going to use: https://github.com/fd00/cygepoll/blob/master/epoll.c for the epoll and hoping I could get something timerfd somehow.

nvm, I got it. Does it make sense to add epoll to musl, also....
