### ISSUE TITLE
Could not create EGL context (context attributes are not supported)

### ISSUE THREAD

**Issue by piece-o-ham** [emscripten-core/emscripten#4425]
Nothing shows up on the canvas. I just get `Could not create EGL context (context attributes are not supported)` in the web console. I have found a solution. If I comment out the following lines, the program works:

``` C++
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
// I create my context after this
```

However, I don't have any problems with these lines when I compile natively. I would prefer to avoid writing a preprocessor check to disable these lines when I compile with Emscripten.

Is this supposed to be this way, or is this a bug?

**Comment by kripken** [comment]
That does seem surprising. Do you have a full standalone testcase showing the problem? And on which browser do you see it? (the error message doesn't seem to be from emscripten, so it could be a browser error)

**Comment by piece-o-ham** [comment]
I don't have very much code right now, but I still got the error when I reduced the code to only include the window and context creation. I also noticed that the message is being returned by SDL_GetError. I am using Firefox ESR 45.0.2. I also tried it in Chromium and got the same results.

**Comment by bsurmanski** [comment]
I believe the issue is that emscripten is parsing the context version as an GL ES version (since I think emscripten maps GL ES to WebGL). The latest stable version of GL ES(as of today) is GLES 3.2 (https://en.wikipedia.org/wiki/OpenGL_ES).

The following works for me:
```
#ifdef __EMSCRIPTEN__
 SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
 SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
 SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
#else
 // put Desktop GL definitions here
#endif
```

And remember to set "-s USE_WEBGL2=1" when building. (Remember WebGL2 = GL ES 3)
