### ISSUE TITLE
More Flexible Emterpreter Blacklist/Whitelist specification

### ISSUE THREAD

**Issue by dctsystems** [emscripten-core/emscripten#4428]
I've got a project which builds code with emscripten with highly flexible configuration options. There are multiple modules which get dynamically included, each with multiple functions of which any combination can be used. Blacklisting a few key functions produces good performance in Emterpreter. However these functions aren't always included in every configuration. Even if the module containing them is linked, they may not be called.

Currently blacklisting a function that is not included results in an error. This prevents use of an "optimistic" list, blacklisting all known safe functions in case they might be needed. This should probably be an optional warning.

It would be useful to be able to blacklist/whitelist on a per file basis, marking whole modules as safe.

It would also be useful to add code to lists using a #pragma in the source code.

**Comment by kripken** [comment]
Error by default seems best, but optionally making it just a warning sounds reasonable to me.
