### ISSUE TITLE
Upstream LLVM has changed the NaN semantics of the SIMD compare-to-integer instructions

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4435]
Continuing from #4430, the remaining breakage in `next-merge` is that the SIMD comparison functions that compare the lowest lanes of two SIMD registers and return an `int` of the result, have changed behavior in LLVM 3.9.0 trunk, with respect to how comparing NaNs works. These affected intrinsics are the (U)COMI\* family of intrinsics as listed here: https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=comi&techs=SSE,SSE2

In Clang 3.8.0 and before, comparing two scalars of which at least one is a NaN would return 1. This is also the behavior that GCC, Visual Studio, and our current Emscripten code implements. This behavior is unintuitive in the sense that comparing NaNs in `float`s have the opposite tradition in IEEE-754, i.e. "nothing is equal to a NaN".

Intel is the original author of these intrinsics, and it must be admitted that these functions have long suffered from poor documentation. Intel doesn't spec in detail how these intrinsics should work with respect to NaNs (https://software.intel.com/en-us/node/514308), but presumably the reference implementation in their own compiler was held as the ground truth. The behavior that GCC, VS and Clang <= 3.8 each follow likely comes from adhering to the original code as implemented in Intel's compilers, where `_mm_comieq_ss` is implemented to perform the `COMISS` instruction and return the resulting zero flag (ZF) register state as the output `int` value of the intrinsic function. The `COMISS` instruction itself is though well documented since it's part of the ISA, and is shown e.g. at http://x86.renejeschke.de/html/file_module_x86_id_44.html. This shows the origin of the unexpected NaN behavior, since the zero flag is set if the comparison is equal, or if the comparison result is unordered, i.e. at least one of the registers is a NaN.

Microsoft's documentation does highlight this unintuitive behavior with NaNs (documented since Visual Studio 2005): https://msdn.microsoft.com/en-us/library/windows/hardware/93yx2h2b(v=vs.80).aspx:

```
If a and b are equal, 1 is returned. Otherwise, 0 is returned. If a or b is a NaN, 1 is returned.
```

The question here is whether this breaking change in LLVM/Clang 3.9.0 to start comparing NaNs to 0 in the `_mm_(u)comi{eq,ge,gt,le,lt,neq}_s{s,d}` intrinsics is some kind of intentional decision to break suit from the other compilers to align with IEEE-754 scalar float comparisons, or whether it is a regression. I'll poke around a bit if I can find a conversation trail regarding this. As an STR, one can build and run the following code:

```
#include <xmmintrin.h>
#include <math.h>
#include <stdio.h>

int main()
{
    __m128 a = _mm_set1_ps(42.f);
    __m128 b = _mm_set1_ps(NAN);

    int equal = _mm_comieq_ss(a, b);
    printf("equal: %d\n", equal);
}
```

Visual Studio, GCC and Emscripten and Clang <= 3.8 will each return 1 here, but Clang 3.9 in the next-merge branch will return 0. Emscripten code compiled with the new Clang from next-merge branch will return 1 as well, which causes the SIMD tests fail, since they expect that native code produces the same results as Emscripten compiles.

**Comment by kripken** [comment]
Very interesting!

@sunfishcode, maybe this rings a bell for you?

**Comment by juj** [comment]
Referenced this in LLVM bug tracker as well, https://llvm.org/bugs/show_bug.cgi?id=28510. Hopefully the developers there have more info, they should certainly be more knowledgeable to the history and changes here.

**Comment by kripken** [comment]
Ok, there is a possible temporary workaround in eb94bd77cd4632d8717d612893c2f6c88085384e. Otherwise everything looks good in my testing.

Assuming you're ok with that workaround @juj, when do you think is a good time to merge the `next-merge` branches to the `incoming` branches? I see some failures on the bots, not sure how serious they are.

**Comment by sunfishcode** [comment]
For the record, it looks like the upstream change is intentional and will be kept.

**Comment by kripken** [comment]
Ok, in that case I guess I should update the temporary workaround in that commit to be permanent? I.e., we'll ignore nans in that test from now on? (still nice to make sure they compile at least, so we can keep them in the test)

**Comment by kripken** [comment]
Ok, there isn't anything else to do in this issue, since LLVM is keeping the new NaN semantics, so the workaround in place (that ignores NaNs in those tests) should stay in place.

Aside from that, rust has moved their LLVM merge target ahead, so I've tracked that, the `next-merge` branches contain a merge of the LLVM 3.9 release branches (more precisely, somewhere in them, as rust branched before they are final). Running tests now.

**Comment by pcordes** [comment]
Intel's current intrinsics guide (https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=MMX,SSE_ALL,AVX_ALL,Other&text=comiss&ig_expand=1424) has pseudocode that matches Clang's current implementation that makes it work like  `a[0] == b[0]`  using IEEE compare semantics where unordered is not equal.  (This means the code-gen has to check PF as well as ZF, unless `-ffast-math` lets us assume neither input was NaN).

```
Operation
    RETURN ( a[31:0] != NaN AND b[31:0] != NaN AND a[31:0] == b[31:0] ) ? 1 : 0
```

I don't know when this changed; perhaps as late as when the Intel ICX compiler was developed, using the LLVM back-end.

GCC still uses the historical behaviour of only checking the ZF result, ignoring PF, so unordered is treated as `eq`ual.  (As discussed in https://stackoverflow.com/questions/75818896/mm-comieq-ss-difference-between-clang-and-gcc)

**Comment by juj** [comment]
Thanks for the update, this is valuable to keep a good track of information available.

Must agree that it was not the best way that breaking changes to live shipping code was handled, but I find it's great that the direction has consensus. I.e. it reads like LLVM, Microsoft and Intel all implement this new behavior, whereas GCC is the odd one out.

Maybe GCC's divergent behavior could be raised as a bug to their tracker?
