### ISSUE TITLE
Embedded \0s in binary strings cannot be output via stdio (or write calls)

### ISSUE THREAD

**Issue by spathiwa** [emscripten-core/emscripten#4437]
in library_tty.js,  default_tty_ops and default_tty1_ops, function put_char:, the line

```
      if (val != 0)  tty.output.push(val); // val == 0 would cut text output off in the middle.
```

causes embedded \0's to be skipped, making any program which outputs binary data to stdout produce incorrect results. 

Removing the val != 0 test would indeed truncate the string unless changes similar to Pull request
https://github.com/kripken/emscripten/pull/4255 are committed to add support for embedded \0's in UTF8ArrayToString.

**Comment by kripken** [comment]
Hmm, hen I (by mistake) print a `\0` to stdout on linux in a native build, it seems to stop printing. So I am guessing it's undefined behavior?

**Comment by spathiwa** [comment]
You have to use write or fwrite with a length; printf and other C stdio functions will otherwise terminate C strings at \0.

**Comment by spathiwa** [comment]
You have to use write or fwrite with a length; printf and other C stdio functions will otherwise terminate C strings at \0.

**Comment by kripken** [comment]
Sure, or `printf %c`, which is how I think I've seen that behavior natively.
