### ISSUE TITLE
Yet another unresolved external symbol warning

### ISSUE THREAD

**Issue by afraidofdark** [emscripten-core/emscripten#4445]
I use "sdl2 sdl2main opengl32 glew32s" libraries. I didn't link any of these. Instead I compiled my game engine and link it which is libabt however I get unresolved symbol errors eventhough libabt is linked. By the way I compiled my game engine without any error or important warnings.

`
C:\MinGW\msys\1.0\home\cihan\YASS\Source>emmake make
emcc -I../Header -I../../ABT/Header -I../../ABT/Header/glm -I../../ABT/Dependencies/rapidxml-1.13 -I../../ABT/Dependencies/glew-1.13.0/include -I../../ABT/Dependencies/SDL2-2.0.4/include -std=gnu++11 -DGLEW_STATIC -L../../ABT/Dependencies -llibABT main.cpp
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: _ZN3ABT4MeshD1Ev
warning: unresolved symbol: _ZN3ABT4Node14GetTranslationENS_19TransformationSpaceE
warning: unresolved symbol: _ZN3ABT4Node12GetTransformENS_19TransformationSpaceE
warning: unresolved symbol: _ZN3ABT4Node8AddChildEPS0_
warning: unresolved symbol: _ZN3ABT8MeshPathENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
warning: unresolved symbol: _ZN3ABT11TexturePathENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
warning: unresolved symbol: _ZN3ABT6Camera9TranslateEN3glm5tvec3IfLNS1_9precisionE0EEE
warning: unresolved symbol: _ZN3ABT6CameraC1Ev
warning: unresolved symbol: _ZN3ABT8DrawableD2Ev
warning: unresolved symbol: _ZN3ABT15SpriteAnimationC1ENSt3__110shared_ptrINS_11SpriteSheetEEE
warning: unresolved symbol: _ZN3ABT4MeshC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
warning: unresolved symbol: _ZN3ABT10SpritePathENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE
warning: unresolved symbol: _Z23SpherePointIntersectionRKN3glm5tvec3IfLNS_9precisionE0EEEfS4_
warning: unresolved symbol: _ZN3ABT6Camera5PitchEf
warning: unresolved symbol: _ZN3ABT6Camera13GetViewMatrixEv
warning: unresolved symbol: _ZN3ABT8DrawableC2Ev
warning: unresolved symbol: _ZN3ABT4NodeC1Ev
warning: unresolved symbol: _Z24SphereSphereIntersectionRKN3glm5tvec3IfLNS_9precisionE0EEEfS2_f
warning: unresolved symbol: _ZN3ABT8DrawableC1Ev
warning: unresolved symbol: _ZN3ABT8RendererD1Ev
warning: unresolved symbol: _ZN3ABT8Renderer16InitBasicShadersEv
warning: unresolved symbol: _ZN3ABT8Renderer8Render2dEPNS_15SpriteAnimationEN3glm5tvec2IiLNS3_9precisionE0EEE
warning: unresolved symbol: _ZN3ABT8Renderer6RenderEPNS_8DrawableEPNS_6CameraE
warning: unresolved symbol: SDL_CreateWindow
warning: unresolved symbol: _ZN3ABT4Node9TranslateEN3glm5tvec3IfLNS1_9precisionE0EEENS_19TransformationSpaceE
warning: unresolved symbol: _ZN3ABT4Node6RotateEN3glm5tquatIfLNS1_9precisionE0EEENS_19TransformationSpaceE
warning: unresolved symbol: _ZN3ABT8DrawableD1Ev
warning: unresolved symbol: SDL_GL_CreateContext
warning: unresolved symbol: _ZN3ABT11SpriteSheetD1Ev
warning: unresolved symbol: _ZN3ABT11SpriteSheetC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
warning: unresolved symbol: _ZN3ABT6CameraD1Ev
warning: unresolved symbol: _ZN3ABT15SpriteAnimation6UpdateEf
warning: unresolved symbol: _ZN3ABT7SurfaceC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEN3glm5tvec2IiLNS8_9precisionE0EEE
warning: unresolved symbol: _ZN3ABT6Camera16RotateOnUpVectorEf
warning: unresolved symbol: _ZN3ABT6Camera7SetLensEfffffff
warning: unresolved symbol: SDL_SetRelativeMouseMode
warning: unresolved symbol: _ZN3ABT8Renderer8Render2dEPNS_7SurfaceEN3glm5tvec2IiLNS3_9precisionE0EEE
warning: unresolved symbol: _ZN3ABT8RendererC1Ev
warning: unresolved symbol: _ZN3ABT4Main12m_textureManE
warning: unresolved symbol: _ZN3ABT4Main16m_spriteSheetManE
warning: unresolved symbol: _ZN3ABT4Main9m_meshManE
warning: unresolved symbol: _ZTIN3ABT8DrawableE
warning: unresolved symbol: glewExperimental

C:\MinGW\msys\1.0\home\cihan\YASS\Source>`

**Comment by kripken** [comment]
Looks like parts of the game engine aren't linked in? Or optimized out. See [this faq entry](http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process), in particular the part at the end about `.a` files if you use those, and `llvm-nm` as a debugging tool.

**Comment by amilajack** [comment]
I am running into a similar. I am not very familiar with C++ and LLVM so sorry for any confusion. How can I add the `-s "EXPORTED_FUNCTIONS=['_main', '_my_func']"` flag to `emmake` instead of `emcc`?

**Comment by kripken** [comment]
@amilajack if you're using emmake and running `make`, then there should be a `Makefile` that you can edit (find where it calls emcc, and add those flags - look for "CFLAGS" also, often Makefiles define that for compiler args). See for example this Makefile, https://github.com/kripken/box2d.js/blob/master/Makefile#L15

**Comment by amilajack** [comment]
Oh okay that makes. Thanks!
