### ISSUE TITLE
Bad ioctl syscall -2147202862

### ISSUE THREAD

**Issue by lugi7** [emscripten-core/emscripten#4451]
Im trying to compile a program called hcitool.c using emcc.
Using following command compiles it from C:

`sudo gcc /home/pi/download/bluez/bluez/hcitool.c /home/pi/download/bluez/bluez/lib/bluetooth.c /home/pi/download/bluez/bluez/lib/hci.c /home/pi/download/bluez/bluez/lib/sdp.c /home/pi/download/bluez/bluez/lib/uuid.c /home/pi/download/bluez/bluez/src/oui.c -o /home/pi/test/hcitool.out`

Compiles and works flawlessly

So i tried to compile it into Javascript, using following command:

`sudo ./emcc /home/pi/download/bluez/bluez/hcitool.c /home/pi/download/bluez/bluez/lib/bluetooth.c /home/pi/download/bluez/bluez/lib/hci.c /home/pi/download/bluez/bluez/lib/sdp.c /home/pi/download/bluez/bluez/lib/uuid.c /home/pi/download/bluez/bluez/src/oui.c -o /home/pi/test/hcitool.js`

Compiles, but running it gives the following message:

> bad ioctl syscall -2147202862                                                                                                                                   │···············
> bad ioctl syscall -2147202862                                                                                                                                   │···············
> abort("bad ioctl syscall -2147202862") at Error                                                                                                                 │···············
>     at jsStackTrace (/home/pi/test/hcitool.js:1060:13)                                                                                                          │···············
>     at stackTrace (/home/pi/test/hcitool.js:1077:22)                                                                                                            │···············
>     at abort (/home/pi/test/hcitool.js:37036:44)                                                                                                                │···············
>     at ___syscall54 (/home/pi/test/hcitool.js:4812:18)                                                                                                          │···············
>     at _ioctl (/home/pi/test/hcitool.js:28907:8)                                                                                                                │···············
>     at _hci_for_each_dev (/home/pi/test/hcitool.js:18575:10)                                                                                                    │···············
>     at _hci_get_route (/home/pi/test/hcitool.js:18682:9)                                                                                                        │···············
>     at Array._cmd_scan [as 3](/home/pi/test/hcitool.js:6852:11)                                                                                                │···············
>     at _main (/home/pi/test/hcitool.js:6363:33)                                                                                                                 │···············
>     at Object.asm._main (/home/pi/test/hcitool.js:36771:19)                                                                                                     │···············
> abort("bad ioctl syscall -2147202862") at Error                                                                                                                 │···············
>     at jsStackTrace (/home/pi/test/hcitool.js:1060:13)                                                                                                          │···············
>     at stackTrace (/home/pi/test/hcitool.js:1077:22)                                                                                                            │···············
>     at abort (/home/pi/test/hcitool.js:37036:44)                                                                                                                │···············
>     at ___syscall54 (/home/pi/test/hcitool.js:4812:18)                                                                                                          │···············
>     at _ioctl (/home/pi/test/hcitool.js:28907:8)                                                                                                                │···············
>     at _hci_for_each_dev (/home/pi/test/hcitool.js:18575:10)                                                                                                    │···············
>     at _hci_get_route (/home/pi/test/hcitool.js:18682:9)                                                                                                        │···············
>     at Array._cmd_scan [as 3](/home/pi/test/hcitool.js:6852:11)                                                                                                │···············
>     at _main (/home/pi/test/hcitool.js:6363:33)                                                                                                                 │···············
>     at Object.asm._main (/home/pi/test/hcitool.js:36771:19) 

Have no idea what to do from here to make it work like its supposed to do.
Im doing all this on raspberry pi 3, so maybe i have to somehow run emcc with optimalisation settings.

**Comment by kripken** [comment]
In `src/library_syscall.js` we have a list of which ioctl stuff we support (search for `ioctl`). The list is fairly limited, and I think you're just building a library that uses something not yet supported. I would look in the source code to see what flag is being sent there, using that stack trace (possibly `hci_for_each_dev`).

I tried to look for `-2147202862` in the system headers (should be hex `0x800448d2`), but I don't see it. Maybe it's sending an invalid flag?

**Comment by lugi7** [comment]
And why would it send invalid flag? This number comes from op = SYSCALLS.get() function.

**Comment by kripken** [comment]
Yes, looking up the call stack at the method that made the syscall would help understand what flag it is passing (very possible it is valid,  but not supported yet).

**Comment by dequis** [comment]
Got here while googling that ioctl, so might as well add what i found: That's HCIGETDEVLIST, which returns a list of bluetooth devices.

Now, uh, may I ask, how does it make any sense at all to try to get this running under emscripten?

**Comment by kripken** [comment]
There is some wip spec for bluetooth on the web, I have heard, but I don't think it's close to stable or present in browsers yet.

**Comment by dequis** [comment]
Yeah but even if that's ever a thing, it won't provide something that can be reasonably mapped to the linux specific low level HCI interface. This [web bluetooth spec draft][1] has a very high level interface which supports service discovery and only one bluetooth profile, GATT. Compare with [the average linux bluez stack chart][2]

If anything, you want to implement HCIGETDEVLIST to always return EINVAL. Or to succeed writing 0 to dev_num of the struct that is passed to it (it usually receives a 16 in that field)

```
struct hci_dev_list_req {
	uint16_t dev_num;
	struct hci_dev_req dev_req[0];	/* hci_dev_req structures */
};
```

That would be so that the caller thinks there are no bluetooth devices, just in case some ported app happens to depend on this somehow and not handle EINVAL properly. 

But getting bluez/hcitool working, with all the low-level nonsense they deal with? Forget about it.

[1]: https://webbluetoothcg.github.io/web-bluetooth/
[2]: https://www.google.com/search?tbm=isch&q=bluez+stack
