### ISSUE TITLE
linking bytecompiled project "assimp" fails. Finds no symbol. 

### ISSUE THREAD

**Issue by sanderboer** [emscripten-core/emscripten#4452]
Hi,
I'm trying to use the 3d import/export library http://www.assimp.org/ .
I dl'd it, it is a cmake project, so I configure it with the emscripten toolchain file.
[assimp-es.zip](https://github.com/kripken/emscripten/files/386069/assimp-es.zip)
For the life of me I cannot get this project to compile .bc files, but when I run "llvm-nm libassimp.a" , it lists a whole bunch of symbols. So I'm just guessing I could rename/copy it to .bc
Now, a test:

```
#include <stdio.h>
#include <assimp/Importer.hpp>
int main (){
    Assimp::Importer importer; 
     printf("hi how are you ?");
}
```

and I build it with:

```
emcc \
    -Iassimp-es/include \ 
    -Lassimp-es/lib \
    -lassimp \
    test-assimp.cpp \
    -o test-assimp.js
```

Result:
    warning: unresolved symbol: _ZN6Assimp8ImporterC1Ev
    warning: unresolved symbol: _ZN6Assimp8ImporterD1Ev

Same file compiled with clang++ works fine btw.
now:

```
$ llvm-nm assimp-es/lib/libassimp.a |grep _ZN6Assimp8ImporterC1Ev
     U _ZN6Assimp8ImporterC1Ev
     U _ZN6Assimp8ImporterC1Ev
     -------- T _ZN6Assimp8ImporterC1Ev

$ llvm-nm assimp-es/lib/libassimp.a |grep _ZN6Assimp8ImporterD1Ev
     U _ZN6Assimp8ImporterD1Ev
     U _ZN6Assimp8ImporterD1Ev
     -------- T _ZN6Assimp8ImporterD1Ev
```

So in each case it finds two undefined refs to the requested symbol, and one global function.

My uneducated guess is that the linker stops after finding the first entry.

Anyway, I would greatly appreciate a way forward.

thank you,
Sander

**Comment by kripken** [comment]
Renaming a `.a` to `.bc` would probably not work. But just linking with the `.a` file should work.

**Comment by sanderboer** [comment]
Nope.

    $ emcc -Iassimp-es/include  assimp-es/lib/libassimp.a test-assimp.cpp -o test-assimp.js
        warning: unresolved symbol: _ZN6Assimp8ImporterC1Ev
        warning: unresolved symbol: _ZN6Assimp8ImporterD1Ev

Or:
    $ emcc -Iassimp-es/include test-assimp.cpp -o test-assimp.bc
    $ emcc assimp-es/lib/libassimp.a test-assimp.bc -o test-assimp.js
        warning: unresolved symbol: _ZN6Assimp8ImporterC1Ev
        warning: unresolved symbol: _ZN6Assimp8ImporterD1Ev

**Comment by sanderboer** [comment]
OK, I'm having some success here.

I built assimp as shared libs and linked to it like any ol' lib and it worked .......
[assimp-test.zip](https://github.com/kripken/emscripten/files/388186/assimp-test.zip)

In the attached zip is a test dir with compiled assimp lib (only imports blend and obj), an html and js.
In the browser (after firing python -m SimpleHTTPServer):

    now importing file: data/suzanne.blend 
    SUCCESS importing file: data/suzanne.blend 

test-assimp.cpp:
`
#include <stdio.h>
#include <assimp/Importer.hpp>      // C++ importer interface
#include <assimp/scene.h>           // Output data structure
#include <assimp/postprocess.h>     // Post processing flags
#include <string>
bool doImport( const std::string& pFile)
{
  printf("now importing file: %s \n", pFile.c_str());
  Assimp::Importer importer;
  // And have it read the given file with some example postprocessing
  // Usually - if speed is not the most important aspect for you - you'll 
  // propably to request more postprocessing than we do in this example.
  const aiScene* scene = importer.ReadFile( pFile, 
					    aiProcess_CalcTangentSpace       | 
					    aiProcess_Triangulate            |
					    aiProcess_JoinIdenticalVertices  |
					    aiProcess_SortByPType);
  
  // If the import failed, report it
  if( !scene)
    {
      printf("FAILED importing file: %s \n", pFile.c_str());
      return false;
    }
  // Now we can access the file's contents. 
  printf("SUCCESS importing file: %s \n", pFile.c_str());
  // DoTheSceneProcessing( scene);
  // We're done. Everything will be cleaned up by the importer destructor
  return true;
}
int main (){
  doImport("data/suzanne.blend");
  printf("\nsup ?\n");

}
`
build-test.emscripten:
`
#!/bin/sh
emcc \
    -Lassimp-es-dyn/lib \
    -Iassimp-es-dyn/include \
    -lassimp test-assimp.cpp \
    --preload-file data/ \
    -o test-assimp.html
`

This is the good kind of voodoo I guess.

Sander

**Comment by makc** [comment]
@sanderboer I was trying to reproduce this build from your last zip, and got following oops:
```
Traceback (most recent call last):
  File "xxx/emsdk_portable/emscripten/1.35.0/emcc", line 1309, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "xxx/emsdk_portable/emscripten/1.35.0/tools/shared.py", line 1471, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
$ 
```
any idea?

**Comment by sanderboer** [comment]
The point of my post is that I think linking to libs is some sort of voodoo.
