### ISSUE TITLE
llvm and clang build versions do not match

### ISSUE THREAD

**Issue by ToniKroos** [emscripten-core/emscripten#4453]
Hello.

i want new version emscripten update.

so download release ver 1.36.5

but error.

clang llvm emscripten different.

searching page

http://kripken.github.io/emscripten-site/docs/building_from_source/building_fastcomp_manually_from_source.html#building-fastcomp-from-source

after clang llvm make.

but.. error message. T.T

$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.5
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang 271ce598c3d1fe74efadc254f5be1b57edea9f41) (https://github.com/kripken/emscripten-fastcomp 61acfb230665464544f2e8db292f8999fc3c628c) (emscripten 1.36.0 : 1.36.0)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Users/inkeansong/Dev/emsdk_portable/clang/e1.36.5_64bit
ERROR:root:Emscripten, llvm and clang build versions do not match, this is dangerous (1.36.5, 1.36.0, 1.36.0)
ERROR:root:Make sure to rebuild llvm and clang after updating repos
INFO:root:(Emscripten: Running sanity checks)

$ emmake make
Traceback (most recent call last):
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/em++", line 13, in <module>
    emcc.run()
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/emcc.py", line 1778, in run
    JSOptimizer.flush()
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/emcc.py", line 1678, in flush
    run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/emcc.py", line 1648, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/tools/shared.py", line 1747, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/tools/js_optimizer.py", line 544, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/tools/tempfiles.py", line 64, in run_and_clean
    return func()
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/tools/js_optimizer.py", line 544, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5/tools/js_optimizer.py", line 446, in run_on_js
    filenames = pool.map(run_on_chunk, commands, chunksize=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory
make: **\* [compile] Error 1

.emscripten
LLVM_ROOT='/Users/inkeansong/Dev/emsdk_portable/clang/e1.36.5_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Users/inkeansong/Dev/emsdk_portable/clang/e1.36.5_64bit/optimizer'
NODE_JS='/Users/inkeansong/Dev/emsdk_portable/node/4.1.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/var/folders/1g/l5620l157kz4cf1gxhwxfghh0000gn/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

.bash_profile
export PATH=$PATH:/Users/inkeansong/Dev/emsdk_portable
export PATH=$PATH:/Users/inkeansong/Dev/emsdk_portable/clang/e1.36.5_64bit
export PATH=$PATH:/Users/inkeansong/Dev/emsdk_portable/node/4.1.1_64bit/bin
export PATH=$PATH:/Users/inkeansong/Dev/emsdk_portable/emscripten/1.36.5
export PATH=$PATH:/System/Library/Frameworks/Python.framework/Versions/2.7/bin

path..
$ pwd
/Users/inkeansong/Dev/emsdk_portable/emscripten
$ ls
1.35.0  1.36.5

$ pwd
/Users/inkeansong/Dev/emsdk_portable/clang
$ ls
e1.35.0_64bit   e1.36.5_64bit

version...
$ pwd
/Users/inkeansong/Dev/emsdk_portable/clang/e1.36.5_64bit
$ cat emscripten-version.txt 
1.36.5

this is file copy and paste e1.35.0_64bit -> e1.36.5_64bit. and then change version

help me.

ps.
os = os x ei capitan 10.11.6

**Comment by kripken** [comment]
Check the paths in `~/.emscripten`. LLVM_ROOT says where it looks for LLVM. Check that that is of latest incoming, and also `tools/clang` underneath it for clang. There is an `emscripten-version.txt` file in those two and in the emscripten root dir, which is where the numbers (1.36.0 vs 1.36.5) come from.

**Comment by ToniKroos** [comment]
Confirmed. Still not.

> OSError: [Errno 2] No such file or directory

So Check file No such file or directory 

I know what the problem was.

optimizer file copy and paste
/Users/inkeansong/Dev/emsdk_portable/clang/e1.35.0_64bit -> /Users/inkeansong/Dev/emsdk_portable/clang/e1.36.5_64bit

 So that I do not fit that resolution.

**Comment by juj** [comment]
If you want to try a clean build from source of the latest, you can run

    git clone https://github.com/juj/emsdk.git
    cd emsdk
    ./emsdk install sdk-incoming-64bit
    ./emsdk activate sdk-incoming-64bit
    source ./emsdk_env.sh
    cd emscripten/incoming
    em++ tests/hello_world.cpp -o hello_world.html

and try out hello_world.html in browser.

When you come back to emsdk later on in a new terminal, reissue the `source ./emsdk_env.sh` (or add it manually to `~/.bash_profile` or similar) if you want to have the tools in PATH.

**Comment by ToniKroos** [comment]
thanks you. before mac version portable not install cmake. first cmake install. and then I'll install.
