### ISSUE TITLE
IO Buffer Bug with Standard Input

### ISSUE THREAD

**Issue by Yangff** [emscripten-core/emscripten#4454]
First, take a look at code near here [underflow/fstream](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/system/include/libcxx/fstream#L591)

It looks like `fstream` use `fread` when the buffer underflow..

Then, Look at this function used by fstream [fread/fread](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/system/lib/libc/musl/src/stdio/fread.c#L27)

Notice that, `fread` will find it have nothing to read, if and only if `k <= 0`.

And, Look [get_char/library_tty.js](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_tty.js#L111)

If I try to open `stdin` using fstream, it will go to that code.

And, `readSync` will return after it read something... some bytes or EOF... 
No matter what it reads, it will make `k > 0`.

So, in terminal, you typed, for example, `123\n`, and `readSync` passed it to `fread`.
But, `fread` will not satisfied with only 4 bytes. It will try to fill the buffer so `read` in `library_tty` will be called and so `readSync` will be called... and waiting for your typing. 
I have to input enough chars to make fread return so fstream can read what it want...

The same problem seems to happen on `cin`. And I'm not sure if it happens in any other where...

It looks like

```
C:\Users\****\Documents\Toys\tests>node test
getch called
start read.
123
123
read done.
getch called
getch called
getch called
getch called
getch called
start read.
123
read done.
getch called
getch called
getch called
getch called
getch called
start read.
123
read done.
getch called
getch called
getch called
getch called
getch called
start read.
123
read done.
getch called
getch called
getch called
getch called
getch called
start read.
read done.
^C
```

``` cpp
#include <iostream>
#include <cstdio>
#include <fstream>
using namespace std;

int main()
{
    int a;
    ifstream fin("/dev/stdin");
    fin >> a;
    cout << (a * 10) << endl;
    return 0;
}
```

**Comment by Yangff** [comment]
Also, it seems because of this function [__stdio_read/__stdio_read](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/system/lib/libc/musl/src/stdio/__stdio_read.c#L11) (i'm not so sure) but the same issue happens on scanf.

**Comment by kripken** [comment]
Nice analysis!

Looks like our [stdin test](https://github.com/kripken/emscripten/blob/incoming/tests/module/test_stdin.c) only reads single chars, which is why this wasn't noticed before, I think.

I'm not sure what to do here, there are so many layers... perhaps we need to send an EOF from the JS code?

**Comment by Yangff** [comment]
@kripken I'm not sure..

On my windows & ubuntu, cin & fin(/dev/stdin & conIN$) will return after I typed enter. 
But `fread` (from stdin) will try to read enough characters...(ignore new line) If JS send EOF from JS, `fread` may not work as expected... 
I'm not sure about this... I tried the same code using clang++ on ubuntu and it works correctly, maybe this is problem of somewhere else.

**Comment by Yangff** [comment]
I'm not sure what will fstream works on Clang's libcxx... 

And here is a possible reason from a lower level.. 
`scanf` or `istream` will use some kinds of `getchar` --> `uflow` --> and [__stdio_read/__stdio_read](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/system/lib/libc/musl/src/stdio/__stdio_read.c#L11) this function.
It calls `SYS_readv` syscall and goto here [doReadv/library_syscall](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_syscall.js#L122) .

And `len` is very small (`uflow` pass `1` for `len`) but `FS.read` will be call twice. 

First time, it can read one char(zero when `len=1`), but the second time, it faced on a large buffer. And this function [read/library_tty.js](https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_tty.js#L48) will fill it by get chars from `default_tty_ops.get_char`. 

The comment said ` b.) undefined to signal that no data is currently available` but I cannot find any code path to return `undefined`, maybe this is the problem (I guess). But not return `undefined` every time, only the first time... 

Perhaps, `get_char` can return `undefined` every time after it has popped all data from it buffer. (Also I guess)..

**Comment by Yangff** [comment]
It looks like (not sure about other platform) and even fstream works correctly... 
```js
          if (!tty.input) {
            var result = null;
            if (ENVIRONMENT_IS_NODE) {
              //console.log("hi")
              // we will read data by chunks of BUFSIZE
              var BUFSIZE = 256;
              var buf = new Buffer(BUFSIZE);
              var bytesRead = 0;
              
              var fd = process.stdin.fd;
              // Linux and Mac cannot use process.stdin.fd (which isn't set up as sync)
              var usingDevice = false;
              try {
                fd = fs.openSync('/dev/stdin', 'r');
                usingDevice = true;
              } catch (e) {}
              console.log("start read.")
              bytesRead = fs.readSync(fd, buf, 0, BUFSIZE, null);
              console.log("read done.")
              if (usingDevice) { fs.closeSync(fd); }
              if (bytesRead > 0) {
                result = buf.slice(0, bytesRead).toString('utf-8');
              } else {
                result = null;
              }
  
            } else if (typeof window != 'undefined' &&
              typeof window.prompt == 'function') {
              // Browser.
              result = window.prompt('Input: ');  // returns null on cancel
              if (result !== null) {
                result += '\n';
              }
            } else if (typeof readline == 'function') {
              // Command line.
              result = readline();
              if (result !== null) {
                result += '\n';
              }
            }
            if (!result) {
              return null;
            }
            tty.input = intArrayFromString(result, true);
          } else if (!tty.input.length) {
            tty.intput = null;
            return undefined;
          }
          return tty.input.shift();
```
