### ISSUE TITLE
MODULARIZE  option  relation..

### ISSUE THREAD

**Issue by ToniKroos** [emscripten-core/emscripten#4455]
If  MODULARIZE enabled this option causes a performance bad.

but disabled performance good.

why MODULARIZE and not MODULARIZE are the difference in performance?

option name

```
LINK_OPTS = -O3 --llvm-lto 1
LINK_OPTS += -s NO_EXIT_RUNTIME=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1
LINK_OPTS += -s NO_DYNAMIC_EXECUTION=1
LINK_OPTS += --memory-init-file 0 -s NO_FILESYSTEM=1
LINK_OPTS += -s EXPORTED_FUNCTIONS="['_malloc', '_free']"
LINK_OPTS += -s TOTAL_MEMORY=50331648
LINK_OPTS += -s ABORTING_MALLOC=1
LINK_OPTS += -s NO_BROWSER=1
```

ifeq ($(MD), md)
    LINK_OPTS += -s EXPORT_NAME="'$(JSNAME)'"
    LINK_OPTS += -s MODULARIZE=1
endif

**Comment by kripken** [comment]
On which JS engine or browser is this?

The main issue is that with modularize everything is in a function. Some JS engines optimize code in the global scope better.

**Comment by ToniKroos** [comment]
browser is chrome.

i want good performance.

so i want MODULARIZE option not use.

if so how variable name change?

ex)
var d;d||(d=eval("(function() { try { return Module || {} } catch(e) { return {} } })
->
var xx;xx||(xx=eval("(function() { try { return Module || {} } catch(e) { return {} } })

**Comment by kripken** [comment]
Sorry, I don't understand the question.

**Comment by ToniKroos** [comment]
Sorry. 

i want global variables name change.

Something like bottom code.

original code.
var d;d||(d=eval("(function() { try { return Module || {} } catch(e) { return {} } })
-> i want code.
var xx;xx||(xx=eval("(function() { try { return Module || {} } catch(e) { return {} } })

**Comment by kripken** [comment]
The name of global variables is determined by the minifier. If you are using closure compiler, it might have an option to set it. If not, then that is from the emscripten minifier. It doesn't have an option for this, but you could modify the source to achieve what you want, search for `ensureMinifiedNames` in `tools/`.

**Comment by ToniKroos** [comment]
thank you!
