### ISSUE TITLE
When I run './emsdk install latest', the program always failed and show "Command '['make', '-j1']' returned non-zero exit status 2"

### ISSUE THREAD

**Issue by tsangint** [emscripten-core/emscripten#4470]
Performing a singlethreaded build.
Running build: ['make', '-j1']
[  8%] Built target LLVMSupport
[  8%] Built target LLVMTableGen
[  8%] Built target obj.llvm-tblgen
[  8%] Built target llvm-tblgen
[  8%] Built target AttributeCompatFuncTableGen
[  8%] Built target intrinsics_gen
[  8%] Building CXX object lib/IR/CMakeFiles/LLVMCore.dir/Function.cpp.o
c++: error: unrecognized command line option ‘-Wcovered-switch-default’
make[2]: **\* [lib/IR/CMakeFiles/LLVMCore.dir/Function.cpp.o] Error 1
make[1]: **\* [lib/IR/CMakeFiles/LLVMCore.dir/all] Error 2
make: **\* [all] Error 2
Build failed due to exception!
Working directory: /home/vagrant/temp/emsdk_portable/clang/fastcomp/build_master_64
Command '['make', '-j1']' returned non-zero exit status 2
Installation failed!

**Comment by juj** [comment]
Looks like the first error is `c++: error: unrecognized command line option ‘-Wcovered-switch-default’`. This is part of the LLVM build system itself. Which compiler do you have on your system? Perhaps it is too old.

**Comment by tsangint** [comment]
My current compiler is gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3).
Which compiler I should use to complie.

**Comment by juj** [comment]
Not sure about what is the minimum required version of GCC. On my system I have GCC 5.4.0 which works. Another attempt could be to try building the `incoming` branch of emsdk, which has a newer version of LLVM in it, that might have fixed the problem. Run

    ./emsdk install sdk-incoming-64bit

if you want to test it out.
