### ISSUE TITLE
Deactivate the Virtual File System during build time

### ISSUE THREAD

**Issue by gmarty** [emscripten-core/emscripten#4472]
Is there an option to deactivate the File System?
My problem is that the IndexedDB API used under the hood causes issues on iOS in UIWebView and web app mode.

**Comment by kripken** [comment]
IndexedDB is not used by default in the filesystem, so something else is going wrong. One possibility is caching in the file packager (enabled by `--use-preload-cache`), or if your project uses IDBFS.

In general the filesystem code is not included when it is not used. You can also set `NO_FILESYSTEM` to 1 to force that.

**Comment by juj** [comment]
Also would be interesting to know the exact line/statement that causes errors, which iOS this is on, perhaps it might be something that could be worked around.

**Comment by gmarty** [comment]
The bug I'm referring to is [this one](https://bugs.webkit.org/show_bug.cgi?id=137034). Though it's marked as fixed, it still affects version 9 of iOS but has been fixed in version 10.

It only affects web apps in web view mode or apps added to homescreen.

There is a [workaround](https://github.com/axemclion/IndexedDBShim/issues/161#issuecomment-90704722) that involves wrapping the code inside a closure. The `IndexedDB` parameter can then be a shim or the `null` value.

I think a fix for this bug should be added to Emscripten. Maybe completely deactivating the IndexedDB is good enough as it will allow the app to run.
What do you think?

**Comment by kripken** [comment]
IndexedDB is deactivated by default as mentioned above. It should not be used unless you explicitly use an option that requires it. What build options are you using, and what is the stack trace? Those should help find out why you are hitting this.
