### ISSUE TITLE
When I built it on my ubuntu 14.04(inside virtualbox and created by vagrant);There is a err :'c++: internal compiler error: Killed (program cc1plus)'

### ISSUE THREAD

**Issue by tsangint** [emscripten-core/emscripten#4480]
[  9%] Building CXX object lib/IR/CMakeFiles/LLVMCore.dir/Dominators.cpp.o
[  9%] Building CXX object lib/IR/CMakeFiles/LLVMCore.dir/Function.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [lib/IR/CMakeFiles/LLVMCore.dir/Function.cpp.o] Error 4
make[1]: **\* [lib/IR/CMakeFiles/LLVMCore.dir/all] Error 2
make: **\* [all] Error 2

**Comment by kripken** [comment]
That is probably either a gcc bug (as the text suggests), or that you ran out of memory or disk space or something like that.

**Comment by dschuff** [comment]
In my experience, `error: Killed` usually means that the program was killed
externally because you ran up against some ulimit or similar (probably
memory or CPU time rather than disk space, since the latter usually results
in different errors like file I/O failure).
