### ISSUE TITLE
[embind] emscripten::val should be default constructible

### ISSUE THREAD

**Issue by arximboldi** [emscripten-core/emscripten#4485]
Hi!

To me, it feels natural that `val` should be default constructible (with `val{} == val::undefined()`). This would it easier to use with generic algorithms and containers that require default-constructibility.

What do you think? Is there any fundamental reason why this is not the case?

**Comment by AlexPerrot** [comment]
Here is my workaround :
```
static val undef = val::undefined();
class myval : public emscripten::val{
public:
    myval() : emscripten::val(undef)
    {}
    myval(const emscripten::val& emval) : emscripten::val(emval)
    {}
};
```
`myval` is default-constructible and uses the copy constructor of `val`.
