### ISSUE TITLE
str.charCodeAt is not a function

### ISSUE THREAD

**Issue by daryl-williams** [emscripten-core/emscripten#4487]
First off, I want to thank everyone that works on emscripten, I think it is truly amazing, so thank you.

Having said that, I have some C code that I have run through emscripten and the program actually works well (except for some reason printing to stdout does not print to the screen). However while trying to understand why printing to stdout does not seem to work I started it up using the devtools console by Matt Deslauriers and I saw this error message:

/usr/local/lib/node_modules/devtool/lib/require-hook.js:50 Uncaught TypeError: 
/Users/daryl/Projects/Development/Emscripten/emsdk_portable/emscripten/1.35.0/lms/source_files/ds.js
str.charCodeAt is not a function

Looking into it further I saw that in the function lengthBytesUTF8(str) the value of str was actually a function. I added a if (typedef == 'string') around that functionality but the error continued to happen. Stepping though the code I saw that str had the value of 'function require(path)' and typeof also said it was a function.

The output of emcc -v follows:

WARNING:root:invocation: ../../emcc -v  (in /Users/daryl/Projects/Development/Emscripten/emsdk_portable/emscripten/1.35.0/lms/source_files)
WARNING:root:(Emscripten: system change: 1.35.0|asmjs-unknown-emscripten|/Users/daryl/Projects/Development/Emscripten/emsdk_portable/clang/e1.35.0_64bit|3.7 vs 1.36.5|/Users/daryl/Projects/Development/Emscripten/emsdk_portable/clang/e1.35.0_64bit|3.7, clearing cache)
INFO:root:(Emscripten: Running sanity checks)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
INFO:root:(Emscripten: Running sanity checks)

I compiled with EMCC_DEBUG=1 but there was no /tmp/emscripten_temp directory and even after I created it and ran compiled again there was nothing in it. There was however output to the screen which I saved to a file and have attached as emcc-output.txt. 

Regards,

Daryl Williams

[emcc-output.txt](https://github.com/kripken/emscripten/files/414392/emcc-output.txt)

**Comment by kripken** [comment]
Doesn't sound like a known issue. Do you have a small testcase that shows it?

**Comment by ricejasonf** [comment]
This is just a stab in the dark, but I experienced this bug the other day, and it was caused by some confusion with the "environment". Setting a global window object and then running an emscripten js file in nodejs will reproduce the same error (or at least it's similiar).

Using nodejs:
```js
var fs      = require('fs');
var process = require('process');

global.window = {};

// "include" a test js file
eval(fs.readFileSync(process.argv[2], 'utf8'));

// emscripten set exit status
if (typeof EXITSTATUS == 'undefined')
  EXITSTATUS = 1
process.exit(EXITSTATUS);
```

I worked around it with this as it is the arguments that it passes to main that it explodes on.
```js
var Module = {
  "arguments": []
};
```

**Comment by daryl-williams** [comment]
Hi Jason, Thanks for your reply. I tried adding your suggestion but was 
not sure where to place it. Putting it after the Module is initialized 
and before the moduleOverrides, i.e:

var Module;
if (!Module) Module = (typeof Module !== 'undefined' ? Module : null) || {};

var Module = {
     "arguments": []
};

var moduleOverrides = {};
for (var key in Module) {
   if (Module.hasOwnProperty(key)) {
     moduleOverrides[key] = Module[key];
   }
}

Yields the following error: 
/usr/local/lib/node_modules/devtool/lib/require-hook.js:50 Uncaught 
abort("Assertion failed: undefined")

Your saying that it is the arguments to main makes a lot of sense 
because my program does take command line arguments.Is there somewhere 
specifically to put the lines you suggested?

Thanks.

**Comment by ricejasonf** [comment]
Ah, sorry. You define it before "including" the emscripten script.

```js
var fs      = require('fs');
var process = require('process');


global.window = {};

var Module = {
  "arguments": []
};

// "include" a test js file
eval(fs.readFileSync(process.argv[2], 'utf8'));

// emscripten set exit status
if (typeof EXITSTATUS == 'undefined')
  EXITSTATUS = 1
process.exit(EXITSTATUS);
```

In the documentation, see _Creating the Module Object_. 
https://kripken.github.io/emscripten-site/docs/api_reference/module.html#creating-the-module-object

Note that I've only used that workaround on programs that don't use any of the args passed to `main`.

**Comment by promethe42** [comment]
Related to #4123 ?

**Comment by holgerd77** [comment]
We are running in exactly the same issue (described at https://github.com/ethereum/browser-solidity/issues/822), I tried to bridge this with adding ``if (!str.charCodeAt) return 0;`` similar to the ``(typedef == 'string')`` addition above, this results in no code added.

In our case the value of ``str`` passed to ``lengthBytesUTF8(str) `` actually is a ``Buffer()`` function.

Not sure where to start to debug this (or actually tried various path but got stuck every time).

**Comment by kripken** [comment]
Do you have a small testcase showing the issue? I tried the testcase from earlier above (last year) and can't reproduce with it.

**Comment by cdetrio** [comment]
In the case of https://github.com/ethereum/browser-solidity/issues/822 the problem was [browserify](https://github.com/browserify/browserify#usage) `--detect-globals` defaulting to true, which causes `process` and `Buffer` to be passed as arguments to the asm.js module. A fix is to [patch](https://github.com/cdetrio/rustbn.js/commit/4f2305f8e7219ade6c64063b967c463205245f70) the asm.js output, inserting around `run()` at the end of the file:
```
Module["arguments"]=[];
run();
module.exports=Module;
```

**Comment by kripken** [comment]
Ok, sounds like there isn't anything we need to do on the Emscripten side? But not sure I understand what's going on in that code fragment
 * What value does arguments have, that you need to erase? (is it the process and Buffer stuff you mention?)
 * The export looks like the node.js export code we have. Should we move it out of `if (ENVIRONMENT_IS_NODE)` and do

````
  if (typeof module !== 'undefined') {
    module['exports'] = Module;
  }
````
in all environments? I guess there's some risk if we do.

**Comment by cdetrio** [comment]
@kripken that's right, `arguments` has `process` and `Buffer` because Browserify tries to inject them as globals. I was curious what emscripten uses `Module.arguments` for, but I can't understand what the [docs](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.arguments) mean here:

> The commandline arguments. The value of arguments contains the values returned if compiled code checks argc and argv

I did notice that `module.exports` is set when `ENVIRONMENT_IS_NODE`, and I guess it would help for browserify etc. compatibility to do that for all environments.

**Comment by kripken** [comment]
The docs are saying that if you run
````
jsvm program.js arg1 arg2
````
then `Module.arguments = ['arg1', 'arg2']].

**Comment by nachitoes** [comment]
g
