### ISSUE TITLE
cannot run emcc command on OSX

### ISSUE THREAD

**Issue by yilunyu** [emscripten-core/emscripten#4498]
I am following the tutorial http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html for emscripten. I have all of the required tools installed. Then I ran `emcc -v` in `emsdk_portable/emscripten/1.35.0` directory. It produced `env: python2: No such file or directory`. How do I fix this error?

**Comment by kripken** [comment]
Is python installed? You might need to create a link from `python` to `python2` so that `python2` is runnable.

**Comment by yilunyu** [comment]
I ran python --version and it gave me Python 2.7.10. What do you mean by creating a link from python to python2 and how do I do that?

**Comment by kripken** [comment]
I'm not familiar with OS X. On linux though you could add a symlink in `~/bin/` using `ln -s /usr/bin/python python2`. Then running `python2` would run `python`.

**Comment by yilunyu** [comment]
should i add python2 to PATH variable?

**Comment by juj** [comment]
This issue is fixed in 1.35.9, see this commit: https://github.com/kripken/emscripten/commit/d1d2b3428ad3fcc6a4fb6f5e32bb8c9f132426c5 . The emsdk prebuilt version is a bit out of date, so at the moment, we recommend building the emsdk version from source. For example, you can run

    cd /path/to/emsdk
    ./emsdk update
    ./emsdk install sdk-tag-1.36.7-64bit
    ./emsdk activate sdk-tag-1.36.7-64bit

**Comment by yilunyu** [comment]
i got `Error: No tool or SDK found by name 'sdk-tag-1.35.9-64bit'.`

**Comment by yilunyu** [comment]
and also `Error: No tool or SDK found by name 'sdk-tag-1.36.7-64bit'.`

**Comment by juj** [comment]
Ops, very sorry, I think there was an issue with the update procedure on OS X. Try bootstrapping from scratch:

    git clone https://github.com/juj/emsdk.git
    cd emsdk
    ./emsdk list
    ./emsdk install sdk-tag-1.36.7-64bit
    ./emsdk activate sdk-tag-1.36.7-64bit
    source ./emsdk_env.sh

(note that in this form when bootstrapping via `git clone`, `emsdk update` is not used)
