### ISSUE TITLE
--separate-asm and --proxy-to-worker flags are incompatible

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4512]
STR:

```
./em++ tests/hello_world.cpp -o a.html --proxy-to-worker --separate-asm
```

will print

```
running code in a web worker
TypeError: Module.asm is not a function 
```

when attempting to run. The issue is that the file `a.asm.js` is loaded up in the main browser thread, but the worker is spawned with `a.js`, so it does not see the asm.js module since it's on the wrong thread. Not quite sure yet how to fix cleanly though.

**Comment by asRIA** [comment]
It looks this issue has a place with combination: `-s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=1` and calling manually `separate_asm.py` command.

**Comment by phoenixx2** [comment]
Also experiencing the issue. @juj , did asRIA's recommendation work for you? Is there another workaround that wouldn't require this extra step?
