### ISSUE TITLE
Can I embind a `void*` type class property?

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#4523]
I have a following C++ class:

``` cpp
struct FLIF_DECODER
{
    void* callback;
};
```

Binding this with `.property("callback", &FLIF_DECODER::callback)` causes `error: static_assert failed
      "Implicitly binding raw pointers is illegal. Specify allow_raw_pointer<arg<?>>"`

And with `.property("callback", &FLIF_DECODER::callback, allow_raw_pointers())` causes `error: implicit
      instantiation of undefined template 'emscripten::internal::GetterPolicy<void *FLIF_DECODER::*>'`

Is there a way to solve this problem? I will be OK to bind `void*` to number type.

**Comment by sunnypurewal** [comment]
I also get this error when trying to bind a ```uint8_t* field```. Can anyone provide some guidance?
