### ISSUE TITLE
dup() (syscall 41) should reuse the file description, and not open a new one.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4529]
Reading through the syscalls and filesystem library, it looks like the semantics for the `dup` syscall are being handled incorrectly. The documentation at http://man7.org/linux/man-pages/man2/dup.2.html says

```
   "the old and new file descriptors [...] refer to the same open file description
   (see open(2)) and thus share file offset and file status flags; for
   example, if the file offset is modified by using lseek(2) on one of
   the file descriptors, the offset is also changed for the other."
```

but it looks like the implementation of `dup` opens the same file separately:

```
__syscall41: function(which, varargs) { // dup
  var old = SYSCALLS.getStreamFromFD();
  return FS.open(old.path, old.flags, 0).fd;
},
```

so these won't have an effect of being linked on the file offset when seeking? There is a test for `dup` in `tests/unistd/dup.c`, but looks like it does not test the case of read pointers being shared in seeks.

This is not much of an issue all and zero priority, don't need this for anything, just noticed while going through the code.

**Comment by jakogut** [comment]
Duplicate (ha) of #4017.
