### ISSUE TITLE
Wrong fabs function usage

### ISSUE THREAD

**Issue by antelle** [emscripten-core/emscripten#4532]
I'm trying to build WebAssembly with LLVM wasm backend, and here's the error I get:

```
INFO:root:generating system library: libc.bc...  (this will be cached in
  "/Users/Antelle/.emscripten_cache/wasm/libc.bc" for subsequent builds) /Users/Antelle/emsdk_portable/emscripten/incoming/system/lib/libc/musl/src/internal/floatscan.c:290:7:
  error: absolute value function 'fabs' given an argument of type 'long
  double' but has parameter of type 'double' which may cause truncation of
  value [-Werror,-Wabsolute-value]
                  if (fabs(y) >= CONCAT(0x1p, LDBL_MANT_DIG)) {
                      ^
 /Users/Antelle/emsdk_portable/emscripten/incoming/system/lib/libc/musl/src/internal/floatscan.c:290:7:
  note: use function 'fabsl' instead
                  if (fabs(y) >= CONCAT(0x1p, LDBL_MANT_DIG)) {
                      ^~~~
                      fabsl
  1 error generated.
  ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

I'm not sure if I should fix it directly here, as musl is external dep, but replacing `fabs` with `fabsl` in this line resolved compilation issue:
https://github.com/kripken/emscripten/blob/incoming/system/lib/libc/musl/src/internal/floatscan.c#L290

**Comment by kripken** [comment]
Yeah, this is a known issue on master currently. Being discussed not in an issue but in a thread in another repo, so it's hard to find: https://github.com/kripken/emscripten/pull/4501/files/7a7b482216ed681c5bfbd380aa98234abf681cd6#r76284751 (let's leave this issue open to represent it in this repo)
