### ISSUE TITLE
SDL_Mixer only playing out of one speaker on chrome

### ISSUE THREAD

**Issue by Denthor** [emscripten-core/emscripten#4535]
Sound only comes out of one speaker in chrome. Tested on multiple PC's.

> C:\Program Files\Emscripten\emscripten\1.35.0>emcc tests/sdl_audio_mix.c -o audio.html --preload-file tests/sounds

sdl_audio_mix.c :

``` c++
#include <stdio.h>
#include <SDL/SDL.h>
#include <SDL/SDL_mixer.h>
#include <assert.h>
#include <emscripten.h>

static Mix_Chunk *sound = NULL;
static int soundChannel = 0;

void one_iter();
void one_iter() {
  static int frames = 0;
  frames++;

  switch( frames ) {
    case 1:
      soundChannel = Mix_PlayChannel(-1, sound, 0);
      printf("channel = %d", soundChannel);
      assert(soundChannel != -1 && soundChannel != 0);
      break;
    case 2:
      printf("channel %d is playing = %d", soundChannel, Mix_Playing(soundChannel));
      assert(Mix_Playing(soundChannel));
      break;
    case 31:
      assert(Mix_Paused(soundChannel));
      break;
    case 60:
      Mix_Resume(soundChannel);
      break;
    case 61:
      assert(Mix_Playing(soundChannel));
      break;
    case 120:
      Mix_HaltChannel(soundChannel);
      int result = 1;
#ifdef REPORT_RESULT
      REPORT_RESULT();
#endif
      break;
  };
}


int main(int argc, char **argv) {
  SDL_Init(SDL_INIT_AUDIO);
  Mix_Init(MIX_INIT_OGG);

  Mix_ReserveChannels(1);

  int ret = Mix_OpenAudio(0, 0, 0, 0); // we ignore all these..
  assert(ret == 0);

  sound = Mix_LoadWAV("/tests/sounds/the_entertainer.ogg");
  assert(sound);
  emscripten_set_main_loop(one_iter, 30, 0);

  // force a quit
  while(Mix_Init(0))
    Mix_Quit();
  Mix_CloseAudio();

  return 0;
}

```

**Comment by kripken** [comment]
What happens in other browsers? If it's just in chrome, it could be a chrome bug.

**Comment by Denthor** [comment]
WEBAUDIO17014: Decoding error: The stream provided is corrupt or unsupported.(Edge)
Firefox (works in stereo)

Browsing in chrome (YouTube, html5 games etc.) all works through both speakers

**Comment by kripken** [comment]
Interesting. Either Edge and Chrome have different bugs here, or we are emitting bad audio somehow.

**Comment by Denthor** [comment]
A bit more digging on Chrome; the issue may be with panning?

Replacing 

```js
          audio.webAudioNode['connect'](audio.webAudioPannerNode);
          audio.webAudioPannerNode['connect'](audio.webAudioGainNode);
```

In playWebAudio:function (audio) in the outputted audio.js (not sure where to update it to replace the source in build)

With
```js
        audio.webAudioNode['connect'](audio.webAudioGainNode);
//          audio.webAudioPannerNode['connect'](audio.webAudioGainNode);
```

Outputs stereo again. What should I look for in the panner? I'm unfamiliar with web audio, and how to update base emscripten packages. I'm also sure we want to keep the panner.

**Comment by Denthor** [comment]
It get's simpler. Just changing

```js
audio.webAudioPannerNode['panningModel'] = 'equalpower';
```

to

```js
audio.webAudioPannerNode['panningModel'] = 'HRTF';
```

and leaving everything else the same (in playWebAudio) fixes the stero problem.

It seems others have hit the same issue : 

[https://github.com/CreateJS/SoundJS/issues/182](url)

but have solved it internally, I'm not sure what settings on equalpower would get that result.

What would be the implications of moving to HRTF? From what I understand it is more processor intensive.

**Comment by Denthor** [comment]
With HRTF Firefox still works, Edge still returns

WEBAUDIO17014: Decoding error: The stream provided is corrupt or unsupported.

(I'm not sure where to start with that one, occurs both with and without -s USE_OGG=1)

**Comment by kripken** [comment]
Interesting. I'm not that familiar with Web Audio myself. @juj if you get a chance, maybe you can take a look here?

**Comment by juj** [comment]
Briefly, this does read like a Web Audio implementation bug in Chrome. 'equalpower' panning is a simple volume level change in left and right channels, and that is what SDL API offers as well. We definitely would not want to use HRTF panning here, that is a considerably more complex model that typically performs FFT de- and re-construction to do frequency-based level mixing, as well as delays left or right channel audio playback to simulate audio arriving the more distant ear with a tiny delay compared to the closer ear.

@Denthor : if you are able to take a peek at this, I'd go through src/library_sdl.js and look for any places that change parameters on the panner node, and see if there is a particular setting that is activate that triggers the bug.

Or does it occur even if all panning values are at their defaults? I'd presume not, surely Chrome's 'equalpower' stereo panning should not be that obviously broken(?).

Then if you can figure out what the smallest setting change compared to the defaults is that triggers the issue, we can figure out if it is a problem with a setting that the library_sdl.js does or if it's something that Chrome gets wrong. Are there other settings besides the HRTF change that trigger the issue?

**Comment by Denthor** [comment]
The only thing I could do that worked was incorporating the soundjs fix. Adding the extra line after createPanner fixes the issue

```js
            audio.webAudioPannerNode = SDL.audioContext["createPanner"]();
            audio.webAudioPannerNode["setPosition"](0, 0, -.5); // Allow equal panning
            audio.webAudioPannerNode["panningModel"] = "equalpower";
```

The relevant section from soundjs 

```js
	p._updatePan = function() {
		this.panNode.setPosition(this._pan, 0, -0.5);
		// z need to be -0.5 otherwise the sound only plays in left, right, or center
	};
 ```

I assume this means the panner is created with incorrect values, too close on the z to determine the pan.

I still can't get ogg working on Safari/IE (even with -s USE_OGG=1), is this coming? In the meantime I split extra packages between ogg and m4a so I don't download both.

**Comment by juj** [comment]
Ah ok, now I think I understand. The root issue looks like is that the scenario of when the audio source position is identical to the listener position (both lying at origin=(0,0,0)). Although we should be accounting for that in https://github.com/kripken/emscripten/blob/master/src/library_sdl.js#L2574. I wonder if that is never called at load time? If so, nudging the audio source a little bit forward should be a good fix. It looks like the listener is at origo by default.
