### ISSUE TITLE
Linker - user friendly errors with source code details

### ISSUE THREAD

**Issue by mazko** [emscripten-core/emscripten#4536]
_foo.cc_

```
extern int bar(void);

int main()
{
  return bar();
}
```

_bar.cc_

```
extern int myFunction(void);

int bar()
{
  return myFunction();
}
```
#### GCC error message is user friendly:

`gcc -g foo.cc bar.cc` ->  `/home/oleg/Desktop/ngspice-26/bar.cc:5: undefined reference to `myFunction()`
#### EMCC error has no soure file name, line  number, e.t.c.:

`emcc -g4  foo.cc bar.cc` -> `warning: unresolved symbol: _Z10myFunctionv`

I tried `-g`, `-v`, `EM_BUILD_VERBOSE=3  EMCC_DEBUG=1` and still nothing useful. So how can i determine soure **file name**, **line  number** where linker error occurred ?

P.S.
In my real project emcc error is `LLVM ERROR: Signed comparisons not yet supported for integer types larger than 64 bits`

```

DEBUG:root:emscript: llvm backend: /root/emsdk_portable/clang/fastcomp/build_master_64/bin/llc /tmp/tmpxqapC9/ngspice.bc -march=js -filetype=asm -o /tmp/emscripten_temp/tmpBPU2qa.4.js -O1
Unsupported:   %1607 = icmp slt i472 %1606, 0
LLVM ERROR: Signed comparisons not yet supported for integer types larger than 64 bits
INFO:root:Process 17416 finished after 5.44532895088 seconds. Exit code: 1
DEBUG:root:  emscript: llvm backend took 5.44910478592 seconds
```

---

```
EM_BUILD_VERBOSE=3 EMCC_DEBUG=1 emcc -v
DEBUG:root:PYTHON not defined in /root/.emscripten, using "/usr/bin/python"
DEBUG:root:JAVA not defined in /root/.emscripten, using "java"
WARNING:root:invocation: /root/emsdk_portable/emscripten/master/emcc -v  (in /home/src)
INFO:root:(Emscripten: Running sanity checks)
INFO:root:Blocking on process 12: ['/root/emsdk_portable/node/4.1.1_64bit/bin/node', '/root/emsdk_portable/emscripten/master/src/hello_world.js'] until it finishes.
INFO:root:Process 12 finished after 0.134427785873 seconds. Exit code: 0
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.0
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 271ce598c3d1fe74efadc254f5be1b57edea9f41) (https://github.com/kripken/emscripten-fastcomp/ 61acfb230665464544f2e8db292f8999fc3c628c) (emscripten 1.36.0 : 1.36.0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/emsdk_portable/clang/fastcomp/build_master_64/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
INFO:root:Blocking on process 36: ['/root/emsdk_portable/node/4.1.1_64bit/bin/node', '/root/emsdk_portable/emscripten/master/src/hello_world.js'] until it finishes.
INFO:root:Process 36 finished after 0.137655973434 seconds. Exit code: 0
```

**Comment by kripken** [comment]
This is a current limitation of that warning, I'm afraid. (The technical reason is that LLVM has the debug info, but we perform an extra linking step with JS so that it is easy to call to and from JS methods; we don't send debug info into JS.)

You can find out which function it is in by just seaching in the generated code. In the asm.js output you'll see the call to that missing function, and can see in which function that call is.

**Comment by mazko** [comment]
Thanks. Finally i used `llvm-dis` to find source file name which causes linker error:

```
~$ find -name '*.o' | xargs -n1 sh -c 'file $0 && llvm-dis $0 -o - | grep "%[[:digit:]]\+ = icmp slt i472 %[[:digit:]]\+" && exit 255'
# output
.................
./src/spicelib/devices/jfet2/jfet2par.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdtrunc.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipd.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipddel.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdinit.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdmask.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdcheck.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipddest.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdcvtest.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdask.o: LLVM IR bitcode
./src/spicelib/devices/bsim3soi_pd/b3soipdset.o: LLVM IR bitcode
  %766 = icmp slt i472 %765, 0, !dbg !2758
xargs: sh: exited with status 255; aborting
```
So `emcc ngspice.bc -o ngspice.js` passed after i removed bsim3soi_pd from source code.

**Comment by juj** [comment]
@kripken: I presume this limitation will carry over to WebAssembly in the current form? I think it would be good to track this, perhaps at some point we could add something to fix this. In large applications this has proven to be an annoying thing to have to manually track down.

**Comment by kripken** [comment]
Yes, same issue will be present in wasm.

Full debug info might be heavy to pass around into the JS linking stage, unless we radically reorder things. But it might be fairly easy to at least print in which method this happens, just by scanning the asm.js code and seeing where the call to the undefined symbol happens (i.e. doing in code what was suggested to do manually above).
