### ISSUE TITLE
std::future causes "Assertion failed: undefined" crash if std::promise is gone

### ISSUE THREAD

**Issue by haukeduden** [emscripten-core/emscripten#4546]
I think I found a bug - probably in the standard library implementation of std::promise / std::future.

Steps to reproduce:
1.  create a std::promise
2. obtain a std::future from it with get_future
3. set an exception result in the future object
4. destroy the promise  object
5. call std::future::get

=> "Assertion failed: undefined" crash.

I believe it is supposed to be valid to access the future even after the promise that created it has been destroyed. I was unable to find the documentation in the C++ standard about this, but at least on cplusplus.com the documentation of the promise destructor states that: "Note that if other (future) objects are associated to the same shared state, the shared state is itself not destroyed (until all those objects also release it).". See http://www.cplusplus.com/reference/future/promise/~promise/

Also note that we use the same code in a cross-platform project on 8 platforms with various compilers and standard libraries. All other implementations handle this case just fine (for what that is worth).

Code to reproduce the problem:

``` c++
#include <iostream>
#include <future>

int main()
{   
    std::future<int> f;

    {
        std::promise<int> p;
        p.set_exception( std::make_exception_ptr(std::invalid_argument("bla")) );
        f = p.get_future();
    }

    try
    {
        f.get();
        std::cout << "Error: no exception thrown" << std::endl;
    }
    catch(std::exception& e)
    {
        std::cout << "OK" << std::endl;
    }

    return 0;
}
```

Note that the crash disappears when the promise object is moved up into the parent scope. So the crash is apparently caused by the promise object being destroyed.

The crash also disappears if set_value is used instead of set_exception. So the problem seems to be connected to the way exceptions are stored.

**Comment by kripken** [comment]
This could be a bug in upstream libc++ (especially since promises/futures are a recent feature). Worth checking if our version of libc++ has the same bug in a native build.

**Comment by haukeduden** [comment]
I haven't tested the specific same libc++ version, but we do use libc++ for native builds on some of our other target platforms. And we do not see this bug on these other platforms.
