### ISSUE TITLE
Desktop OpenGL emulation does not support glVertex2d

### ISSUE THREAD

**Issue by bobWinner** [emscripten-core/emscripten#4573]
I'm trying to compile this : 
# include <GL/glfw.h>
# include <emscripten.h>

int main () {
    glfwInit();
    glfwOpenWindowHint(GLFW_WINDOW_NO_RESIZE, GL_TRUE);
    glfwOpenWindow(320, 240, 8, 8, 8, 8, 0, 0, GLFW_WINDOW);
    glClearColor(0.65f, 0.45f, 0.65f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    glBegin(GL_QUADS);
    glVertex2d(-0.5f, -0.5f);
    glVertex2d( 0.5f, -0.5f);
    glVertex2d( 0.5f,  0.5f);
    glVertex2d(-0.5f,  0.5f);
    glEnd();
    glfwSwapBuffers();
    return 0;
}

using this command : 

../../../../../home/tf/Documents/emsdk_portable/emscripten/master/em++ hello-glfw.cpp -s LEGACY_GL_EMULATION=1 -s USE_GLFW=2 -std=c++11 -O0 --llvm-opts 2 -o hello.html

the issue is : 

warning: unresolved symbol: glVertex2d

**Comment by juj** [comment]
`glVertex2d` is part of old legacy OpenGL, which is not supported by WebGL. Emscripten emulates some bits of legacy OpenGL, but it is far from complete. See the documentation here: http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html#opengl-support-legacy-and-mobile

It might be possible to improve the emulation to cover this case, although GL emulation has not been a particularly active area of Emscripten in a while. Contributions to this are welcome.

**Comment by bobWinner** [comment]
thank you for the answer

i'm not really interested in using especially this glVertex2d symbol.

actually i'm looking around for understanding what technology to use for writing emscripten/webgl from draft

**Comment by juj** [comment]
Ah, I see. The recommendation is to use the intersection of OpenGL ES 2.0 and WebGL 1.0 features. That is, write OpenGL ES 2.0 but adhere to the restrictions outlined in https://www.khronos.org/registry/webgl/specs/1.0/#6. Specifically `6.2` is an important distinction that should be noticed.

Let's leave this bug open (even if there is no much interest in tackling it), so if others might be using OpenGL emulation they can stumble on this.

**Comment by bobWinner** [comment]
ok cool thank
