### ISSUE TITLE
Should store blobs instead of typed arrays in --use-preload-cache

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4574]
Discussing best practices with IndexedDB folks, it looks like both Firefox and Chrome implementations of IndexedDB have an implementation defined limit on how large typed arrays can be stored in one transaction to IndexedDB.

Currently our file packager's `--use-preload-cache` feature just stores the file with the size that is given, so it fails for too large (>128MB) stores on Firefox and Chrome.

One way to mitigate this would be to split up the stores to <128MB chunks, although it looks like the better practice is to store the data as blobs instead of typed arrays. (current code storing typed arrays here https://github.com/kripken/emscripten/blob/master/tools/file_packager.py#L697) The rationale is that IndexedDB implementations special case storing blobs more efficiently, and the contents of the blobs are stored as separate files instead of putting them as byte data inside a (SQLite-backed or similar) database on disk. Storing blobs should not have any file size restrictions.

**Comment by kripken** [comment]
Sounds good.
