### ISSUE TITLE
recv MSG_PEEK flag ignored

### ISSUE THREAD

**Issue by Deins** [emscripten-core/emscripten#4586]
I wanted to check socket errors without reading the data by using MSG_PEEK flag on recv, but it seems emscripten just ignores it and treats as regular recv.
`err = recv(soc, &data, 1, MSG_PEEK);`

Any suggestions how can i check when socket is connected and when it fails (js onerror and onopen) if getsockopt and MSG_PEEK isn't available ?

**Comment by juj** [comment]
Would the Emscripten websockets event extensions help here? https://github.com/kripken/emscripten/blob/master/system/include/emscripten/emscripten.h#L95

**Comment by Deins** [comment]
I think it could do the trick. Thanks :)
