### ISSUE TITLE
changes to shared.Settings.BINARYEN_ROOT?

### ISSUE THREAD

**Issue by 257** [emscripten-core/emscripten#4596]
i'm getting this trying to compile a webasm 'hello word!' code:

```
Traceback (most recent call last):
  File "/home/foo/src/w/emsdk_portable/emscripten/master/emcc", line 13, in <module>
    emcc.run()
  File "/home/tl/foo/w/emsdk_portable/emscripten/master/emcc.py", line 1777, in run
    binaryen_bin = os.path.join(shared.Settings.BINARYEN, 'bin')
  File "/usr/lib64/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'int' object has no attribute 'endswith'
```

which makes sense since emcc.py:1777 is trying to append 'bin' to an int 'shared.Settings.BINARYEN'. this is after 'activate latest'. i see in older version shared.Settings.BINARYEN_ROOT is being used as prefix...

**Comment by kripken** [comment]
Yes, that changed a while ago. `Settings.BINARYEN` should be 0 or 1, and you can set `BINARYEN_ROOT` in `~/.emscripten` to override the default binaryen. It's generally best not to set it though, and let emcc get the right binaryen version for you automaticaly.

**Comment by juj** [comment]
@257 : were you able to resolve this? Can this be closed?
