### ISSUE TITLE
resize a glfw canvas

### ISSUE THREAD

**Issue by bobWinner** [emscripten-core/emscripten#4597]
is there a way to resize a glfw canvas window at runtime?
-without reinitializing/recreate all the window-

**Comment by juj** [comment]
There does exist the [emscripten_set_canvas_size](https://github.com/kripken/emscripten/blob/master/system/include/emscripten/emscripten.h#L142) function, though not exactly sure how that will interact with GLFW. Does that work?

**Comment by bobWinner** [comment]
`emscripten_set_canvas_size(width, height);`

doesn't seems to work by itself.

also glfw3 has it's own window_size_callback :

	void window_size_callback(GLFWwindow* window, int width, int height)
	{
		printf("window_size_callback %i, %i\n", width, height);
	}
	(...)
	glfwSetWindowSizeCallback(window, window_size_callback);

and it's window size setter :

`glfwSetWindowSize(window, 640, 480);`

but i can't afford make them throw

**Comment by juj** [comment]
Oh right, there's the function `glfwSetWindowSize()`. That should do the trick then. Does that not work?

**Comment by bobWinner** [comment]
unfortunately glfwSetWindowSize() doesn't seems to work

**Comment by bobWinner** [comment]
i've just found out that there was an argument to pass to glfw : 
glfwWindowHint(GLFW_RESIZABLE, GL_TRUE);

unfortunately the browser refuse to change the size (Element.mozRequestFullScreen() which i've never requested !?!) because the event wasn't fired by an user generated handler
