### ISSUE TITLE
BUG OpenAL caused exception after switching browser tab in call to _alSourcef with AL_PITCH (0x1003)

### ISSUE THREAD

**Issue by EyeGem** [emscripten-core/emscripten#4605]
**Issue:**
Program crashed with call stack after user switched tab back to emscripten tab in a call to _alSourcef( sourceID, AL_PITCH, pitch );

**Log:**
exception thrown: TypeError: entry.src is undefined,_alSourcef

**Code line:**
var oldrate = entry.src.playbackRate.value;

**Context:**
1) Windows 7, Firefox browser
2 ) user switched browser tab and after 20-30 seconds returned back to emscripten tab
3) _alSourcef was being called at every frame in our code (now fixed when same pitch value)

**Suggestions:**
1) var entry = src.queue[src.buffersPlayed]; // not checked for undefined or null?
2) 'is undefined' means value was made =undefined on purpose, otherwise it should be 'not defined'
3) src = AL.currentContext.src[source]; // invalid src?

**Comment by juj** [comment]
A gut feeling has that this might be something that was fixed in https://github.com/kripken/emscripten/pull/4107. Does the issue occur in latest incoming branch? (`sdk-incoming-64bit` sdk target)

**Comment by EyeGem** [comment]
After small fix our audio system doesn't update pitch if it wasn't changed, so the issue never occured again, because our current project does not use audio pitching. I can only state Emscripten version used: tag-1.36.5
