### ISSUE TITLE
Can I copy the content of the emscripten canvas to another canvas?

### ISSUE THREAD

**Issue by paul-ferragut** [emscripten-core/emscripten#4615]
Can I copy the content of the emscripten canvas to another canvas?

I would like to copy the content of my emscripten canvas as a texture and display it in another canvas. As well being able to save as an image.

Normally I would do the following

```
//grab the context from your destination canvas
var destCtx = destinationCanvas.getContext('2d');

//call its drawImage() function passing it the source canvas directly
destCtx.drawImage(sourceCanvas, 0, 0);
```

**Comment by kripken** [comment]
Yes, you can get the emscripten canvas on `Module.canvas`, and then do normal web stuff on it.

**Comment by paul-ferragut** [comment]
Thank you for your answer!
I tried to copy with Module.canvas but it didn't work

```
function copyToCanvas(){

    var c1 = Module.canvas;
    var c2 = document.getElementById("canvas2");

  var destCtx = c2.getContext('2d');
  destCtx.drawImage(c1, 0, 0);

}
```

my test is here http://codepen.io/paul-ferragut/pen/WGJvQJ

**Comment by kripken** [comment]
I'm not sure offhand what's going wrong, but I'd start with adding some `console.log` debug prints to see that `Module.canvas` contains the canvas. (Normally it is assigned to in the HTML, look for `canvas` in `src/shell.html`.)
