### ISSUE TITLE
Socket 'connect' and socket tests fail

### ISSUE THREAD

**Issue by cipri-tom** [emscripten-core/emscripten#4630]
Hi,

I am trying to run a C program which uses TCP sockets. I understood these are compiled into WebSockets, so I am using WebSockify to forward requests to the server.

However, the `connect` method fails in the browser. Specifically, on Firefox in just returns `-1`, without sending any data. On Chrome, it seems that it tries to send some data (seen in WebSockify output) but fails before the reply arrives.

I should mention that the [server + WebSockify] pair works correctly when I am using WebSockets from a pure JavaScript client that I wrote.

Before I try to create a small example, I thought I should run the tests. These give me 4 errors. I removed the stack traces to keep this small:

```
ERROR: test_sockets_async_echo (test_sockets.sockets)
--- expected
+++ actual
@@ -1 +1 @@
-/report_result?0
+[no http server activity]

======================================================================
ERROR: test_sockets_partial (test_sockets.sockets)
--- expected
+++ actual
@@ -1 +1 @@
-/report_result?165
+[no http server activity]

======================================================================
ERROR: test_sockets_select_server_closes_connection_rw (test_sockets.sockets)
--- expected
+++ actual
@@ -1 +1 @@
-/report_result?266
+[no http server activity]


======================================================================
ERROR: test_sockets_select_server_down (test_sockets.sockets)
--- expected
+++ actual
@@ -1 +1 @@
-/report_result?266
+[no http server activity]
```

P.S. I believe this StackOverflow question is related: http://stackoverflow.com/questions/38383200/emscripten-websockify-raw-tcp-unexpected-hung-up

**Comment by kripken** [comment]
Those pass on emscripten incoming with firefox nightly. So if you are on an earlier version of either, perhaps that's the cause?

Otherwise, it's true the sockets code is less-tested than other parts of the codebase, so I wouldn't be too surprised if there was a problem here. We need someone to spend time on this.

**Comment by cipri-tom** [comment]
Thanks for promptness!
Yes, I am on emscripten 1.36 and Firefox release (so way before nightly).
On Chrome, it appears to work, in the sense that it tries to connect before dying.

I'm not sure what the tests are. I thought I'm only using the standard features of sockets and since there are games that have been ported, I imagined it would work.

Until a fix is found, is there a way I can instruct my code to work with webSockets? I'm thinking of something like

```C
#ifdef EMSCRIPTEN
    emscripten_do_ws_connect(...);
#else
   connect(...); // 'classic' C connect
#endif
```

**Comment by kripken** [comment]
I tested on incoming, 1.36.12, so perhaps this changed between those versions. Also it's possible that me testing on nightly shows something was fixed since the release version you are on.

I think @juj was at some point thinking of adding sockets to the emscripten `html_*` API?

**Comment by cipri-tom** [comment]
I can't tell if the tests are related to my problem, namely `connect(socket, address, size)` failing . Partially on Chrome, totally on Firefox

I expected basic sockets to work, right ? I thought there are many applications relying on it.
Could it be a problem of the browser blocking cross-domain stuff ? I'm running all locally with `emrun`, so from `localhost:6931` connecting to `127.0.0.1:my_port`.

**Comment by kripken** [comment]
I'm actually not sure if many people use sockets. I'm not aware of any major products shipping that use it, but of course this is open source so anything is possible.

If it's the browser blocking stuff, you should see errors or warnings in the devtools (in the network tools perhaps).

**Comment by cipri-tom** [comment]
I love it you're so prompt! Thank you!

Ah, I was counting on it. I've seen a couple of blog posts here and there porting games, but indeed nothing major. 
I'm afraid I have abandoned the idea for now :( ... There's really no easy way to debug it :cry: 
Thank you for support!
