### ISSUE TITLE
Compiler error with lots of unresolved symbol 

### ISSUE THREAD

**Issue by ShawZG** [emscripten-core/emscripten#4634]
I just want to compile c code to Js code, and meet the problem of unresolved symbol. 

Use the command below to compile c code to Js code:
shaw@ubuntu:~/tmp$ ./myfastcomp/emscripten/emscripten/emcc simplest_video.c -I /home/shaw/tmp/ffmpeg/include/ -I /usr/local/include/ -o simplest_video.bc
shaw@ubuntu:~/tmp$ ./myfastcomp/emscripten/emscripten/emcc simplest_video.bc --libavcodec.so --libavformat.so --libavutil.so -o fina.html

warning: unresolved symbol: sws_freeContext
warning: unresolved symbol: avformat_open_input
warning: unresolved symbol: av_read_frame
warning: unresolved symbol: SDL_UpdateTexture
warning: unresolved symbol: avcodec_close
warning: unresolved symbol: SDL_WaitEvent
warning: unresolved symbol: SDL_RenderCopy
warning: unresolved symbol: avcodec_decode_video2
warning: unresolved symbol: avcodec_find_decoder
warning: unresolved symbol: SDL_CreateTexture
warning: unresolved symbol: avpicture_fill
warning: unresolved symbol: SDL_CreateWindow
warning: unresolved symbol: sws_scale
warning: unresolved symbol: avformat_close_input
warning: unresolved symbol: av_malloc
warning: unresolved symbol: avformat_find_stream_info
warning: unresolved symbol: SDL_RenderClear
warning: unresolved symbol: av_frame_free
warning: unresolved symbol: avcodec_open2
warning: unresolved symbol: sws_getContext
warning: unresolved symbol: avformat_alloc_context
warning: unresolved symbol: avpicture_get_size
warning: unresolved symbol: av_free_packet
warning: unresolved symbol: av_register_all
warning: unresolved symbol: av_frame_alloc
warning: unresolved symbol: SDL_CreateRenderer
warning: unresolved symbol: avformat_network_init
warning: unresolved symbol: SDL_RenderPresent

all the unresolved symbol  are the functions in Ffmpeg lib and SDL lib.
I have compiled the Ffmpeg code wit emcc as below:

sudo ~/tmp/myfastcomp/emscripten/emscripten/emconfigure ./configure --prefix=/home/shaw/tmp/ffmpeg --enable-gpl --enable-version3 --enable-nonfree --enable-postproc --enable-pthreads --enable-libfaac --enable-libmp3lame --enable-libtheora --enable-shared --enable-libx264 --enable-libxvid --enable-x11grab --enable-libvorbis
sudo ~/tmp/myfastcomp/emscripten/emscripten/emmake make
sudo ~/tmp/myfastcomp/emscripten/emscripten/emmake make install

My OS is ubuntu14.04(64 bit) that runs in VMware Workstaion
My Emscripten is as below:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.0
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang 271ce598c3d1fe74efadc254f5be1b57edea9f41) (https://github.com/kripken/emscripten-fastcomp 61acfb230665464544f2e8db292f8999fc3c628c) (emscripten 1.36.0 : 1.36.0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/shaw/tmp/myfastcomp/emscripten-fastcomp/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64

The source code is as below, can someone help me ? thanks.
# include <stdio.h>
# define __STDC_CONSTANT_MACROS
# include "libavformat/avformat.h"
# include "libavcodec/avcodec.h"
# include "libswscale/swscale.h"
# include "libavutil/imgutils.h"
# include "libavutil/pixfmt.h"
# include "SDL2/SDL.h"

//Refresh Event
# define SFM_REFRESH_EVENT  (SDL_USEREVENT + 1)
# define SFM_BREAK_EVENT  (SDL_USEREVENT + 2)

int thread_exit=0;

int sfp_refresh_thread(void *opaque){
    thread_exit=0;
    while (!thread_exit) {
        SDL_Event event;
        event.type = SFM_REFRESH_EVENT;
        SDL_PushEvent(&event);
        SDL_Delay(40);
    }
    thread_exit=0;
    //Break
    SDL_Event event;
    event.type = SFM_BREAK_EVENT;
    SDL_PushEvent(&event);

```
return 0;
```

}

int main(int argc, char\* argv[])
{

```
AVFormatContext *pFormatCtx;
int             i, videoindex;
AVCodecContext  *pCodecCtx;
AVCodec         *pCodec;
AVFrame *pFrame,*pFrameYUV;
uint8_t *out_buffer;
AVPacket *packet;
int ret, got_picture;

//------------SDL----------------
int screen_w,screen_h;
SDL_Window *screen; 
SDL_Renderer* sdlRenderer;
SDL_Texture* sdlTexture;
SDL_Rect sdlRect;
SDL_Thread *video_tid;
SDL_Event event;

struct SwsContext *img_convert_ctx;

char filepath[]="/home/shaw/tmp/titanic.ts";

av_register_all();
avformat_network_init();
pFormatCtx = avformat_alloc_context();

if(avformat_open_input(&pFormatCtx,filepath,NULL,NULL)!=0){
    printf("Couldn't open input stream.\n");
    return -1;
}
if(avformat_find_stream_info(pFormatCtx,NULL)<0){
    printf("Couldn't find stream information.\n");
    return -1;
}
videoindex=-1;
for(i=0; i<pFormatCtx->nb_streams; i++) 
    if(pFormatCtx->streams[i]->codec->codec_type==AVMEDIA_TYPE_VIDEO){
        videoindex=i;
        break;
    }
if(videoindex==-1){
    printf("Didn't find a video stream.\n");
    return -1;
}
pCodecCtx=pFormatCtx->streams[videoindex]->codec;
pCodec=avcodec_find_decoder(pCodecCtx->codec_id);
if(pCodec==NULL){
    printf("Codec not found.\n");
    return -1;
}
if(avcodec_open2(pCodecCtx, pCodec,NULL)<0){
    printf("Could not open codec.\n");
    return -1;
}
pFrame=av_frame_alloc();
pFrameYUV=av_frame_alloc();
out_buffer=(uint8_t *)av_malloc(avpicture_get_size(AV_PIX_FMT_YUV420P, pCodecCtx->width, pCodecCtx->height));
avpicture_fill((AVPicture *)pFrameYUV, out_buffer, AV_PIX_FMT_YUV420P, pCodecCtx->width, pCodecCtx->height);

img_convert_ctx = sws_getContext(pCodecCtx->width, pCodecCtx->height, pCodecCtx->pix_fmt, 
    pCodecCtx->width, pCodecCtx->height, AV_PIX_FMT_YUV420P, SWS_BICUBIC, NULL, NULL, NULL); 


if(SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER)) {  
    printf( "Could not initialize SDL - %s\n", SDL_GetError()); 
    return -1;
} 
//SDL 2.0 Support for multiple windows
screen_w = pCodecCtx->width;
screen_h = pCodecCtx->height;
screen = SDL_CreateWindow("Simplest ffmpeg player's Window", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
    screen_w, screen_h,SDL_WINDOW_OPENGL);

if(!screen) {  
    printf("SDL: could not create window - exiting:%s\n",SDL_GetError());  
    return -1;
}
sdlRenderer = SDL_CreateRenderer(screen, -1, 0);  
//IYUV: Y + U + V  (3 planes)
//YV12: Y + V + U  (3 planes)
sdlTexture = SDL_CreateTexture(sdlRenderer, SDL_PIXELFORMAT_IYUV, SDL_TEXTUREACCESS_STREAMING,pCodecCtx->width,pCodecCtx->height);  

sdlRect.x=0;
sdlRect.y=0;
sdlRect.w=screen_w;
sdlRect.h=screen_h;

packet=(AVPacket *)av_malloc(sizeof(AVPacket));

video_tid = SDL_CreateThread(sfp_refresh_thread,NULL,NULL);
//------------SDL End------------
//Event Loop

for (;;) {
    //Wait
    SDL_WaitEvent(&event);
    if(event.type==SFM_REFRESH_EVENT){
        //------------------------------
        if(av_read_frame(pFormatCtx, packet)>=0){
            if(packet->stream_index==videoindex){
                ret = avcodec_decode_video2(pCodecCtx, pFrame, &got_picture, packet);
                if(ret < 0){
                    printf("Decode Error.\n");
                    return -1;
                }
                if(got_picture){
                    sws_scale(img_convert_ctx, (const uint8_t* const*)pFrame->data, pFrame->linesize, 0, pCodecCtx->height, pFrameYUV->data, pFrameYUV->linesize);
                    //SDL---------------------------
                    SDL_UpdateTexture( sdlTexture, NULL, pFrameYUV->data[0], pFrameYUV->linesize[0] );  
                    SDL_RenderClear( sdlRenderer );  
                    //SDL_RenderCopy( sdlRenderer, sdlTexture, &sdlRect, &sdlRect );  
                    SDL_RenderCopy( sdlRenderer, sdlTexture, NULL, NULL);  
                    SDL_RenderPresent( sdlRenderer );  
                    //SDL End-----------------------
                }
            }
            av_free_packet(packet);
        }else{
            //Exit Thread
            thread_exit=1;
        }
    }else if(event.type==SDL_QUIT){
        thread_exit=1;
    }else if(event.type==SFM_BREAK_EVENT){
        break;
    }

}

sws_freeContext(img_convert_ctx);

SDL_Quit();
//--------------
av_frame_free(&pFrameYUV);
av_frame_free(&pFrame);
avcodec_close(pCodecCtx);
avformat_close_input(&pFormatCtx);

return 0;
```

}

**Comment by kripken** [comment]
One thing I'm puzzled by is `--libavcodec.so` - is that meant to link in `libavcodec.so`? Then it should be without the `--` prefix, unless it's an alternate syntax I'm not familiar with.

If that's not it, you can use `llvm-nm` to see if those symbols are defined in the libraries mentioned there.

**Comment by ShawZG** [comment]
@kripken Thanks for your help

I use llvm-nm to see the undefined symbols with input file **libavformat.a**, the result is as below:
shaw@ubuntu:~/tmp$ ./myfastcomp/emscripten-fastcomp/build/bin/llvm-nm -defined-only ~/tmp/ffmpeg/lib/libavformat.a | grep av_register_all
0000000000000000 T av_register_all
If I use llvm-nm to see the undefined symbols with input file **libavformat.so**, there is nothing to display.
Do you konw some possilbe reason that ffmpeg compiled fail?

And if I use the command below to compile my c code, it comes warning information.
shaw@ubuntu:~/tmp$ ./myfastcomp/emscripten/emscripten/emcc simplest_video.bc libavcodec.so libavformat.so libavutil.so -o fina.html
WARNING:root:emcc: cannot find library "avcodec"
WARNING:root:emcc: cannot find library "avformat"
WARNING:root:emcc: cannot find library "avutil"

**Comment by kripken** [comment]
What does `file` say on `libavcodec.so`? Perhaps it failed to build, and the file is just empty or corrupt.

Looking at the command that emits that file might show an error that indicates the problem.
