### ISSUE TITLE
LLVM Optimisation issue with Emscripten 1.35

### ISSUE THREAD

**Issue by GMoHughes** [emscripten-core/emscripten#4639]
Hello,

Have been trying to solve this for a while now and having no luck. LLVM and Clang versions appear to match and have the latest version of Emscripten

Anyone have any ideas?

``````
--- Compiling web version with Emscripten ---
mkdir -p Web
/Users/georgia.hughes/babylon-pgm-visualisation/emsdk_portable/emscripten/1.35.0/em++ --bind -std=c++11 -I./ -I../ -I../raindance/Lib/glm-0.9.5.4 Main.cc -s FULL_ES2=1 -s TOTAL_MEMORY=268435456 -o Web/graphiti.html
error: Linking globals named 'send': symbol multiply defined!
Traceback (most recent call last):
  File "/Users/georgia.hughes/babylon-pgm-visualisation/emsdk_portable/emscripten/1.35.0/emcc", line 1309, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/Users/georgia.hughes/babylon-pgm-visualisation/emsdk_portable/emscripten/1.35.0/tools/shared.py", line 1471, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
make: *** [web] Error 1```
``````

**Comment by kripken** [comment]
Try to run `llvm-nm` on the input files and libraries to that command, it can show you where that symbol is defined. It should be defined only in one.

**Comment by kripken** [comment]
Or, if it is defined in one, it might be a system linking bug we are not aware of, in which case if you can provide a small testcase that would be great.

**Comment by GMoHughes** [comment]
Hey, thanks for getting back. Not sure which input files and libraries you're referring to?

**Comment by kripken** [comment]
The files that emcc is given as inputs: `Main.cc` and any libraries if you added them - looking again now, it seems like there are none, at first glance I saw `/Lib/` and assumed it was a library. So this might be a linker bug indeed.
