### ISSUE TITLE
libcurl.bc ported?

### ISSUE THREAD

**Issue by aashidham** [emscripten-core/emscripten#4642]
Not sure this qualifies as an open issue, so apologies if this is posted to the wrong place. Has anybody here been able to successfully port curl (https://curl.haxx.se/) to emscripten-compatible llvm bitcode? Furthermore, is it fully possible to port it to emscripten? According to my understanding, there are some limitations to the socket library that might not make it possible. I'd be willing to pay somebody in order to carry this out in a timely manner.

**Comment by AlexPerrot** [comment]
I'm not sure porting libcurl is the way to go, but it depends on your use case.
Do you plan on using it inside a browser or node.js ?
Personally, I use a class that will use libcurl when compiled to native and `emscripten_wget` when compiled to js. This works really well if you only plan on retrieving documents through http.

**Comment by fbitti** [comment]
@aashidham I'm curious to know whether you managed to compile libcurl to wasm, or whether you found someone who did

**Comment by sbc100** [comment]
Its very unlikely libcurl will work on the web since we don't have sockets.

**Comment by fbitti** [comment]
Understood, @sbc100. I'd be happy if it just runs on the server side (node.js). Would this be possible?

**Comment by curiousdannii** [comment]
If you only need it to work in Node, then it would probably be easier to run the network code in JS, and just pass back a buffer to the WASM when it's finished.
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

**Comment by fbitti** [comment]
Thanks for the tips
