### ISSUE TITLE
Not all exceptions from idb are catched.

### ISSUE THREAD

**Issue by Kaosumaru** [emscripten-core/emscripten#4650]
Under chrome, I've got uncatched exception "exception thrown: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.,Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing."
I've no idea why or when this is happening - probably chrome was evicting storage, or something? From documentation this could happen if DB was explicitly closed before via 'close', but I'm bit doubting if that's the case.

It's seemingly thrown by https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_idbfs.js#L112 . Probably this should be handled like https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/library_fs.js#L1859 . 

I've searched in codebase, and `transaction` is called multiple times, though only in that one place it's in try/catch block. This should probably be changed?

If it's an acceptable idea, I can make a PR in next week.

**Comment by kripken** [comment]
Thanks, yes, idb can throw in many places and I guess we didn't put a try-catch around them all. Would be great to fix this.
