### ISSUE TITLE
Emscripten Finalization error

### ISSUE THREAD

**Issue by Lafia-King** [emscripten-core/emscripten#4661]
I'm trying to install Emscripten but right at the end I get the following error:
**CRITICAL root: Cannot find /usr/bin/llvm-link, check the paths in ~/.emscripten.** 
This error occurs when I do "python emcc" after  replacing 
"LLVM_ROOT = os.path.expanduser(os.getenv('LLVM') or '/usr/bin') # directory" 
**with**
 "LLVM_ROOT = os.path.expanduser(os.getenv('LLVM') or '/usr/local/Cellar/llvm/3.2/bin') # directory"

**Comment by kripken** [comment]
Perhaps `LLVM` is set in your env? And to `/usr/bin/`? That would explain why it is looking there for `llvm-link`.

**Comment by Lafia-King** [comment]
@kripken Alright, I think I understand that but I'm still unclear on how to fix the issue.
Can I get a little more help?

**Comment by kripken** [comment]
Was `LLVM` set in your env? Then just removing it might fix things.
