### ISSUE TITLE
Emscripten installs MSVC package for VS 2013 even though I only have VS 2015

### ISSUE THREAD

**Issue by Boscop** [emscripten-core/emscripten#4683]
I want to compile Rust to JS, so I followed [this guide](https://users.rust-lang.org/t/compiling-to-the-web-with-rust-and-emscripten/7627) but it installs the package for VS 2013 (which fails) even though I only have VS 2015: http://dpaste.com/2K52NBF

What can I do to get it to recognize the correct version?

Thanks a lot!

**Comment by mohamedmansour** [comment]
This got regressed :/ You have to pass --vs2015

**Comment by Boscop** [comment]
Like this?
```
emsdk install sdk-incoming-64bit --vs2015
```

**Comment by juj** [comment]
Sorry about this, LLVM no longer supports Visual Studio 2013 to build, the trunk version of emsdk enforces vs2015. The above command line to explicitly say vs2015 should work.
