### ISSUE TITLE
Pointer_stringify with UTF-8 string and byte length copies entire heap buffer

### ISSUE THREAD

**Issue by rajsite** [emscripten-core/emscripten#4693]
I think a difference in behavior was uncovered with Pointer_stringify being passed a length + either an ASCII string or a UTF-8 String.

This is my interpretation reading Pointer_stringify: https://github.com/kripken/emscripten/blob/07b87426f898d6e9c677db291d9088c839197291/src/preamble.js#L458

When Pointer_stringify is passed a pointer to an ASCII string with a length, the length is respected (and null characters are copied over when within the string).

When passed a pointer to an ASCII string and no length is provided, the string is copied up to the first null character.

When passed a pointer to a string that contains a UTF-8 code points outside the ASCII range the call falls through to UTF8ToString and the pointer is passed but not the length. It seems like UTF8ToString requires null termination.

We have UTF-8 strings encoded in memory with a known byte length (and not null terminated) that may contain UTF-8 encoded astral code points and null character code points. https://github.com/ni/VireoSDK/blob/4be361ad7009607216dbcc24d0c9ecd798929512/source/core/ExecutionContext.cpp#L132

It seems that ASCII strings are allowed to contain null characters when a length is provided. If that is the case I would expect UTF-8 strings would also allow null characters when a length is provided. As there is ambiguity to the 'length' of a UTF-8 string (codepoints vs byte counts), throwing an exception when a length is provided with a UTF-8 string also seems reasonable (it looks like the current behavior ends up copying the entire heap from the starting pointer to the first null or something similar).

Beyond the behavior of Pointer_stringify, does Emscripten provide a safe way for us to extract a UTF-8 string with known byte length that may contain nulls and encoded astral plane code points into one of JavaScript's "UTF-16"-ish strings that encode astral code points as surrogate pairs?

**Comment by rajsite** [comment]
Seems like it might be related to this pull request https://github.com/kripken/emscripten/pull/4255

**Comment by juj** [comment]
I'd recommend marshalling the data over as raw memory buffer in the HEAP, and implementing your own variants of the `src/preamble.js` functions `stringToUTF8` and `UTF8ToString` which don't stop when meeting a null byte. These functions convert UTF8 strings in the HEAP to JavaScript (UTF-16) strings.

**Comment by RReverser** [comment]
@juj Why not add a new option to `Pointer_stringify` or `UTF8ToString` to avoid duplication of code? It already contains good fallback when `TextDecoder` is not available, and is likely used by other parts, so it would be a shame to have two very similar functions in the output...

This use-case is especially important for Rust which represents all strings as `data` + `length` and not zero-terminated.

**Comment by rajsite** [comment]
A couple of other issues we ran into using the provided UTF8ArrayToString algorithm:

It attempts to accept 5 and 6 character UTF8 byte sequences but the largest valid Unicode code point (U+10FFFF) is expressed as a 4 byte sequence: https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/preamble.js#L565

Also if the byte sequence is reduced to 4 bytes the largest value that can be represented 
 is U+1FFFFF which is also outside the Unicode range: https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/preamble.js#L572

In the end we have written a function that does a [lossy conversion of an arbitrary unsafe UTF-8 byte array of known byte length to an unsafe UTF-16 JavaScript string](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/core/module_coreHelpers.js#L87).

Our source is not under a permissive open source license but if y'all would be interested in a pull request I can try to whip up the permissions :)

I also see that since this issue was opened a code path relying on TextDecoder was added but I haven't checked how it handles these scenarios. At least the mdn docs and spec are vague about it.

**Comment by juj** [comment]
> This use-case is especially important for Rust which represents all strings as data + length and not zero-terminated.

Can you be more precise about the Rust use case? Are you suggesting that the existing behavior of string marshaling should be changed to allow zero bytes in the middle of a string on some call path, or are you looking to have new provided built-in functions that would do this as part of Emscripten?

**Comment by RReverser** [comment]
@juj 

>the existing behavior of string marshaling should be changed to allow zero bytes in the middle of a string on some call path

basically this, yes. Probably via extra option that explicitly asks to ignore zero bytes, but it seems like a pretty simple addition that would benefit many people (given requests for this feature).

**Comment by juj** [comment]
> A couple of other issues we ran into ...

> It attempts to accept 5 and 6 character UTF8 byte sequences but the largest valid Unicode code point (U+10FFFF) is expressed as a 4 byte sequence:

It is true that all Unicode code points only need 4 byte sequences, but UTF8 compression defines a scheme for storing any 32-bit number, and developers sometimes want a way to be able to marshal any 32-bit data in a UTF-8 string, so the full encoding scheme is implemented. This should not be a bug, since it's a path that should never be taken for Unicode-restricted UTF8 strings. Is there some specific reason why this poses an issue?

**Comment by rajsite** [comment]
> This should not be a bug, since it's a path that should never be taken for Unicode-restricted UTF8 strings

Ah yea, that's under the assumption that the array does represent a Unicode-restricted UTF8 string though, not that any validation is done for that right?

>Is there some specific reason why this poses an issue?

If a user does include 32-bit code points will they get any sane output? I don't think the output of pushing a greater than 0x1FFFF through the [Surrogate Pair algorithm](https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/preamble.js#L574) will be meaningful.

**Comment by RReverser** [comment]
😢

**Comment by sbc100** [comment]
@RReverser is this still an issue for you?  Happy to re-open if it is.
