### ISSUE TITLE
wrong object returned in a modularized build

### ISSUE THREAD

**Issue by CDanU** [emscripten-core/emscripten#4696]
Since updating from Release 1.36.11 to Release 1.36.13 and 1.36.14 the handling of input and output objects in a MODULARIZEd build has changed which leads an empty return object.

Build script:
```
emcc -O1 \
    ${COMMENT# initialy increase memory for big input files } \
    -s TOTAL_MEMORY=67108864 \
    ${COMMENT# let the memory grow dynamically if even more is needed  } \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s VERBOSE=1 \
    -s MODULARIZE=1 \
    -s EXPORT_NAME="'libUncrustify'" \
    -s ERROR_ON_UNDEFINED_SYMBOLS=1 \
    -s ALLOW_MEMORY_GROWTH=1 \
    --bind \
    --pre-js prefix_module.js \
    --post-js postfix_module.js \
    ${COMMENT# TODO: handle async ajax load to enable this } \
    --memory-init-file 0 \
    -o $out \
    ../*.cpp \
&& cat "./prefix_file" "$out" "./postfix_file" > "$outTmp" \
&& mv "$outTmp" "$out" \
&& ./test/run.sh
```

Generated Output with Release 1.36.11:
```
var libUncrustify = function(Module) {
  Module = Module || {};
...
  return Module;
};
```

Generated Output since updating to Release 1.36.13 and 1.36.14:
```
var libUncrustify = function(libUncrustify) {
  libUncrustify = libUncrustify || {};
  var Module = libUncrustify;
...
  return libUncrustify;
};
```

As far as I see in the source the libUncrustify isn't touched anymore.  The returned object should not be  libUncrustify but Module.

Changing this manually to:
```
var libUncrustify = function(libUncrustify) {
  var Module = libUncrustify || {};
...
  return Module;
};
```

makes everything work again.

**Comment by kripken** [comment]
The line `var Module = libUncrustify;` makes them both refer to the same object. So it is ok for the code in `...` to refer to `Module`, and the return to return `libUncrustify`.

The only problem I can think of is if somewhere in `...` we assign something else to one of those two names?

**Comment by CDanU** [comment]
Ahh ok, thanks, my --pre-js prefix_module.js caused the issue.

**Comment by kripken** [comment]
I see. I wonder if there is a way we can warn about that, but nothing obvious that I can think of.

**Comment by CDanU** [comment]
Checking if both objects are the same object after pre-js and after post-js should be possible right?.

**Comment by kripken** [comment]
Hmm, yes. In fact just once right before returning the object at the end could be enough. We could do that in `ASSERTIONS` builds. Definitely worth doing. If you or someone else doesn't get to it, I'll add it to my list to get to eventually.
