### ISSUE TITLE
missing destructor on link

### ISSUE THREAD

**Issue by HeeroYui** [emscripten-core/emscripten#4716]
I compile my program, and the end linking will return this:

warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: _ZN4ewol11CompositingD2Ev
warning: unresolved symbol: _ZN4ewol6ObjectD2Ev
warning: unresolved symbol: _ZN4ewol6widget5PopUpD2Ev
warning: unresolved symbol: _ZN4ewol6widget14WidgetScrolledD2Ev
warning: unresolved symbol: _ZN7esignal4BaseD2Ev
warning: unresolved symbol: _ZN4ewol6widget4ListD2Ev
warning: unresolved symbol: _ZN4ewol6widget9ContainerD2Ev
warning: unresolved symbol: _ZN4ewol6widget5SizerD2Ev
warning: unresolved symbol: _ZN4ewol8resource7TextureD2Ev
warning: unresolved symbol: _ZN4ewol6widget8ComposerD2Ev

I have build with no optimisation, and if we check they are only  virtual destructor, If I set the destructor by default the error is removed.

I have try some simple code, and I do not reproduce it...

If I set the destructor "=default" the warning is removed

But I need to specify some destructor (sometime) ==> and for me this is not a "warning" but an "error"

**Comment by kripken** [comment]
I've never seen this issue with destructors specifically, so maybe something weird is going on. But in general, first thing I would check is you are not using `.a` files to link (as the order matters there, and some code might not be linked in), and then to use `llvm-nm` on your input files to make sure those symbols do indeed exist in one of your inputs.

**Comment by juj** [comment]
Which Emscripten version was this on?

I've seen a similar issue when the project did not specify the linking order of `-lfoo`/`libfoo.a` libraries on the command line in the correct order. See for example http://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc and http://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking
