### ISSUE TITLE
"RangeError: Source is too large" while porting ICU4C

### ISSUE THREAD

**Issue by dg10a** [emscripten-core/emscripten#4729]
I'm trying to port ICU4C 58.1 (same issues with 57.1) and I run into this error whenever I try to run the JavaScript output with node.

Here are the steps I followed to build ICU:

- Add `--without-assembly` flag to calls to pkgdata in icu/source/data/Makefile.in (lines 50 and 52) and in icu/source/extra/uconv/Makefile.in (lines 157 and 169)

- Build ICU natively:
`sh ../icu/source/runConfigureICU Linux --disable-shared --enable-static --disable-dyload`
`make`

- Cross-compile with emscripten:
`emconfigure ../icu/source/configure --host=i686-pc-linux-gnu --with-cross-build=/home/.../dev/testing/native--disable-shared --enable-static -disable-dyload`
`emmake make`

- Both builds produce these static libraries: libicudata.a (~30M)  libicui18n.a (~7M)  libicuio.a (100K) libicutu.a (~400K) libicuuc.a (~4M)

- Any program that uses libicudata.a seems to throw this error when called with node:
`(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="func`
` `
`RangeError: Source is too large
    at Uint8Array.set (native)
    at allocate (/home/.../dev/testing/emscripted/test/cintltst/cintltst.js:1:12598)
    at Object.<anonymous> (/home/.../dev/testing/emscripted/test/cintltst/cintltst.js:1:110864)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)`

- This works correctly in the native build, tested on both 32 and 64 bit systems.

This is using the incoming branch of emscripten, emscripten-fastcomp, and emscripten-fastcomp-clang. Any suggestions on how to debug this?

**Comment by kripken** [comment]
First thing, which browser or JS engine is that in? Worth testing in more than one to see if it's consistent, as it could be a browser bug.

**Comment by dasith-gunawardhana** [comment]
The above is with node 7.1.0.

Firefox 49.0.2:
`Successfully compiled asm.js code (total compilation time 1749ms; stored in cache)`
`RangeError: invalid or out-of-range index`
`allocate()`
`<anonymous>`

Chromium 54.0.2840.100:
`Uncaught RangeError: Source is too large(…)`

**Comment by juj** [comment]
Try building with the linker flags `-g2` and `--separate-asm`, then grab the file:line information in the browser of where the `RangeError` occurs, and add some prints before the call to identify what the values are that go to the bad call. That should hopefully give a clue of what's not working out here.

**Comment by bluthen** [comment]
Different code but maybe similar issue that could be helpful. My issue was total  memory. I had to set -s TOTAL_MEMORY=33554432
I put print statements to check the sizes of the array and noticed it was too small. Note TOTAL_MEMORY needed to be multiples of 16777216 (the default)
