### ISSUE TITLE
Initializing pointers with js library values error

### ISSUE THREAD

**Issue by jgravelle-google** [emscripten-core/emscripten#4740]
Pointers don't get the correct address when globals are initialized to an externed value.
Extern value addresses do get correctly resolved when initialized as a local value.

Compiled with `emcc src/global_err.c -O2 --js-library src/global_err.js`
C:
```c
#include <stdio.h>

struct Foo {
    int a;
    int b;
    int c;
};
extern struct Foo foo;
extern int bar;

int *x = &foo.a;
int *y = &foo.c;
int *z = &bar;

void local_test() {
  int *x = &foo.a;
  int *y = &foo.c;
  int *z = &bar;

  puts("local");
  printf("x=%p, y=%p, z=%p, *x=%d, *y=%d, *z=%d\n",
         x, y, z, *x, *y, *z);
  printf("&a=%p, &c=%p, &bar=%p, a=%d, c=%d, bar=%d\n",
         &foo.a, &foo.c, &bar, foo.a, foo.c, bar);  
}
int main() {
  foo.a = 7;
  foo.c = 9;
  bar = 11;
  puts("global");
  printf("x=%p, y=%p, z=%p, *x=%d, *y=%d, *z=%d\n",
         x, y, z, *x, *y, *z);
  printf("&a=%p, &c=%p, &bar=%p, a=%d, c=%d, bar=%d\n",
         &foo.a, &foo.c, &bar, foo.a, foo.c, bar);
  puts("");
  local_test();
  return 0;
}
```
JS:
```js
mergeInto(LibraryManager.library, {
  foo: '{{{ makeStaticAlloc(8) }}}',
});
```

Asmjs output:
```
global
x=0, y=0x8, z=0, *x=11, *y=0, *z=11
&a=0x11a0, &c=0x11a8, &bar=0, a=7, c=9, bar=11

local
x=0x11a0, y=0x11a8, z=0, *x=7, *y=9, *z=11
&a=0x11a0, &c=0x11a8, &bar=0, a=7, c=9, bar=11
```

Native output:
```
global
x=0x600ba0, y=0x600ba8, z=0x600b9c, *x=7, *y=9, *z=11
&a=0x600ba0, &c=0x600ba8, &bar=0x600b9c, a=7, c=9, bar=11

local
x=0x600ba0, y=0x600ba8, z=0x600b9c, *x=7, *y=9, *z=11
&a=0x600ba0, &c=0x600ba8, &bar=0x600b9c, a=7, c=9, bar=11
```

**Comment by kripken** [comment]
Yeah, looks like this is a corner case we don't handle: those "relocations" or whatever they are called, when a global refers to another global and so the value of a global depends on the location of globals, does not cross the boundary of C and JS. In other words, we set the C globals, finalize them, and only later run the JS library stuff.

To fix this, we'd have to emit some metadata in the backend, and create the assignment to memory with the right value in JS. Not too hard, but not trivial either.

How important is this?

**Comment by jgravelle-google** [comment]
Apparently not very important? Nobody seems to have ran into it for real yet.

I found this while working on importing globals for s2wasm, and there was the case of what to do with imported globals in initializers. I was curious how asm2wasm handled it: asm2wasm defers to the JS backend, which doesn't implement it.
It's not a problem for me, just something I noticed.

**Comment by kripken** [comment]
I see, thanks.

Ok, let's leave this open in case someone wants to fix this. It does seem like if it hasn't happened til now, it's not a high priority, but would be nice of course.
