### ISSUE TITLE
emcc: IndexError: string index out of range

### ISSUE THREAD

**Issue by xapantu** [emscripten-core/emscripten#4748]
It happens while trying to compile z3. Maybe the command line is not correct, however it should output a more user-friendly message.

~/D/z/build> /usr/lib/emscripten/em++ -o libz3.so -shared api/dll/mem_initializer.o api/dll/dll.o api/dll/install_tactic.o api/dll/gparams_register_modules.o api/api_interp.o api/api_arith.o api/api_seq.o api/api_array.o api/api_pb.o api/api_numeral.o api/api_algebraic.o api/api_opt.o api/api_stats.o api/api_commands.o api/api_datalog.o api/api_bv.o api/api_log.o api/api_context.o api/api_polynomial.o api/api_ast_vector.o api/api_rcf.o api/api_quant.o api/api_tactic.o api/api_params.o api/api_log_macros.o api/api_datatype.o api/api_parsers.o api/api_config_params.o api/api_ast_map.o api/api_model.o api/z3_replayer.o api/api_solver.o api/api_ast.o api/api_goal.o api/api_fpa.o opt/opt.a parsers/smt/smtparser.a tactic/portfolio/portfolio.a tactic/fpa/fpa_tactics.a tactic/smtlogics/smtlogic_tactics.a sat/sat_solver/sat_solver.a tactic/ufbv/ufbv_tactic.a tactic/nlsat_smt/nlsat_smt_tactic.a muz/fp/fp.a muz/duality/duality_intf.a muz/ddnf/ddnf.a muz/bmc/bmc.a muz/tab/tab.a muz/clp/clp.a muz/pdr/pdr.a muz/rel/rel.a muz/transforms/transforms.a muz/dataflow/dataflow.a muz/base/muz.a duality/duality.a qe/qe.a tactic/sls/sls_tactic.a smt/tactic/smt_tactic.a tactic/bv/bv_tactics.a smt/smt.a smt/proto_model/proto_model.a smt/params/smt_params.a ast/rewriter/bit_blaster/bit_blaster.a ast/pattern/pattern.a ast/macros/macros.a ast/fpa/fpa.a ast/simplifier/simplifier.a ast/proof_checker/proof_checker.a parsers/smt2/smt2parser.a cmd_context/extra_cmds/extra_cmds.a cmd_context/cmd_context.a interp/interp.a ackermannization/ackermannization.a solver/solver.a tactic/aig/aig_tactic.a math/subpaving/tactic/subpaving_tactic.a nlsat/tactic/nlsat_tactic.a tactic/arith/arith_tactics.a sat/tactic/sat_tactic.a tactic/core/core_tactics.a math/euclid/euclid.a math/grobner/grobner.a parsers/util/parser_util.a ast/substitution/substitution.a tactic/tactic.a model/model.a ast/normal_forms/normal_forms.a ast/rewriter/rewriter.a ast/ast.a math/subpaving/subpaving.a math/realclosure/realclosure.a math/interval/interval.a math/automata/automata.a math/simplex/simplex.a math/hilbert/hilbert.a nlsat/nlsat.a sat/sat.a math/polynomial/polynomial.a util/util.a  -lrt
Traceback (most recent call last):
  File "/usr/lib/emscripten/emcc.py", line 2216, in <module>
    run()
  File "/usr/lib/emscripten/emcc.py", line 860, in run
    if shared.Building.is_bitcode(arg):
  File "/usr/lib/emscripten/tools/shared.py", line 1940, in is_bitcode
    if b[0] == 'B' and b[1] == 'C':
IndexError: string index out of range

**Comment by xapantu** [comment]
A (probably) related issue https://github.com/bgrins/videoconverter.js/issues/53.

emcc version: emcc (Emscripten gcc/clang-like replacement) 1.36.14 ()

It turns out that I have several empty .a files. I have no idea why they are empty, but maybe it is not emcc fault (I interrupted make with Ctrl-c, so maybe something went wrong at some point). Anyway, the error message should be more meaningful.

**Comment by kripken** [comment]
Thanks, yeah, we should add some better error handling to that line, so it shows something clear about `llvm-nm` not providing valid output or something like that.

**Comment by hydrocat** [comment]
Hello, seems that Building.is_bitcode isn't returning a False if it encounters an error but instead, it's raising a exception that isn't being caught.
My pull request surrounds the the index operations in a try-except block, happily returning false if the file is of a unknown format.
