### ISSUE TITLE
fatal error: 'error.h' file not found

### ISSUE THREAD

**Issue by DL-Thompson** [emscripten-core/emscripten#4769]
I'm getting the following error when trying to compile a library using emmake. I believe error.h is a standard system header. It is located in my /usr/include/ directory and seems to be part of the GNU C Library. Is there any way to get past this error?

```
./argumentHandlers.h:33:10: fatal error: 'error.h' file not found
#include <error.h>
         ^
8 warnings and 1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

**Comment by kripken** [comment]
Hmm, I've not heard of a standard system header called `error.h`. Searches bring up `errno.h` instead. And musl doesn't have it.

**Comment by DL-Thompson** [comment]
I assumed it was standard since the file contains the comment at the top saying its part of the GNU C library. I couldn't find anything from a search either.

**Comment by kripken** [comment]
Must be a gnu c extension then.

Looking in github search, it finds lots of `include "error.h"` for internal stuff, but no `include <error.h>` that I can see.

**Comment by DL-Thompson** [comment]
I have done some more looking into this, and the only references I found to <error.h> are fairly old, so I'm not really sure where it was coming from. I found some references in autoconf to a AC_FUNC_ERROR_AT_LINE, which the error.h contains some declarations for error_at_line, but I'm not sure that helps much.

I have the libraries compiled successfully using make, but when I use emmake I run into these problems. Is there any other way I can get these to work without compiling them with emmake? 

I'm still new to emscripten, but I looked through the website and I believe they have to be compiled that way, but I figured I would check before I decided to take a more difficult approach of trying to fix the errors or something.

**Comment by kripken** [comment]
No, you do need to build them using emmake (or more generally emcc). That's the only way they are in a format that emscripten can handle. When you just use make, you get a local binary for your system, likely x86 or x86_64, which is not linkable with asm.js.
