### ISSUE TITLE
string bit or 

### ISSUE THREAD

**Issue by feipengnju** [emscripten-core/emscripten#4772]
hi:
 I write test code:
 
    #include <stdio.h>

    char * abc(char *str) {
        return str;
    }

    int main(){
        abc("abc");
        return 0;
    }

when convert to js,char *str become  $str = $str|0; I passed argument "adada",then 'adada'|0 run result is 0,How can I fix it?

**Comment by rahulchaphalkar** [comment]
When I compile it with default flags, `_main()` passes a numeric argument to the `abc` function (in my case 675) which corresponds to the starting location of the string in the slab of data passed to `allocate` function. (I can see values `97,98,99` in position 674)
When you change `abc` to `adada` are you probably need to add it in the data slab given to `allocate`, as its hard coded there.

**Comment by juj** [comment]
Can you elaborate what you're trying to do and what doesn't work?

When I build the test code file with `emcc a.c -o a.js`, I get the following relevant bits as output:

    function _abc($0) {
     $0 = $0|0;
     var $1 = 0, $2 = 0, label = 0, sp = 0;
     sp = STACKTOP;
     STACKTOP = STACKTOP + 16|0; if ((STACKTOP|0) >= (STACK_MAX|0)) abortStackOverflow(16|0);
     $1 = $0;
     $2 = $1;
     STACKTOP = sp;return ($2|0);
    }

    function _main() {
     var $0 = 0, label = 0, sp = 0;
     sp = STACKTOP;
     STACKTOP = STACKTOP + 16|0; if ((STACKTOP|0) >= (STACK_MAX|0)) abortStackOverflow(16|0);
     $0 = 0;
     (_abc(124)|0);
     STACKTOP = sp;return 0;
    }

which looks correct as expected. The memory address at location `124` contains the string "abc".
