### ISSUE TITLE
webassembly __embind_register_memory_view error

### ISSUE THREAD

**Issue by AndreasMadsen** [emscripten-core/emscripten#4790]
I'm compiling the follow code:

```c++
#include <emscripten/val.h>
#include <stdio.h>
#include <string>

using namespace emscripten;

int main() {
  val alert = val::global("alert");

  alert(std::string("hallo world"));
  printf("All done!\n");
}
```

using:

```bash
em++ hello.cpp --bind -s WASM=1 -o hello.html
```

When I open hello.html in _Chrome Canary 57.0.2949.0_ I get the error:

```
failed to compile wasm module: TypeError: WebAssembly.Instance():
Import #33 module="env" function="__embind_register_memory_view" error:
function import requires a callable
```

If I compile to asm.js (without `-s WASM=1`) it works fine.

The expected result is that I get an alert box showing `hallo world` and it prints `All done!\n`.

**Comment by kripken** [comment]
Building on latest and testing in spidermonkey shell, I see `TypeError: handle is undefined` which is an internal embind error I don't understand, but I'm pretty sure it happens after your error which is a wasm compilation or link error.

Did you test on emscripten incoming and binaryen master? If not, maybe it's been fixed already. If you did, then please make sure you are on latest chrome canary. If it still fails there, test on firefox nighty too, it's possible this is a bug in chrome.

**Comment by AndreasMadsen** [comment]
> Did you test on emscripten incoming?

Yes. I used the install instructions from http://webassembly.org/getting-started/developers-guide/

> If that's not it, please make sure you are on latest chrome canary.

At the time is was the latest. Today (57.0.2951.0) the simple alert test passes, however it doesn't talk much to break it:

```c++
#include <emscripten/val.h>
#include <stdio.h>
#include <string>

using namespace emscripten;

int main() {
  val document = val::global("document");
  document["body"]["style"].set("backgroundColor", "SteelBlue");
}
```

will throw the following error:

```
failed to compile wasm module: TypeError: WebAssembly.Instance():
Import #37 module="env" function="__emval_get_property" error:
function import requires a callable
```

> firefox nighty too

Firefox nighly (`53.0a1 (2016-12-14) (64-bit)`) appears to work.

**Comment by kripken** [comment]
Interesting, and very strange...

I'm on 32-bit linux here, so I can't test chrome or v8 shell. But this sounds like it could be either a chrome bug, or case where chrome and spidermonkey disagree on what is correct, which could be a bug in either one or in the spec.

cc @dschuff - any known chrome issues with that error? ("function import requires a callable")

**Comment by zzarcon** [comment]
I'm having the same issue with `strlen` method:

**LinkError: WebAssembly.Instance(): Import #1 module="env" function="_strlen" error: function import requires a callable**

```c
#include <string.h>

size_t getLength(char* str) {
  size_t len = strlen(str);

  return len;
}
```

As soon as I change `return len;` for `return 1;`  the error goes away.

The code im using to load the module is:

```javascript
function loadModule(filename, imports) {
  return fetch(filename)
    .then(response => response.arrayBuffer())
    .then(buffer => WebAssembly.compile(buffer))
    .then(module => {
      imports = imports || {};
      imports.env = imports.env || {};
      imports.env.memoryBase = imports.env.memoryBase || 0;
      imports.env.tableBase = imports.env.tableBase || 0;

      if (!imports.env.memory) {
        imports.env.memory = new WebAssembly.Memory({
          initial: 256
        });
      }

      if (!imports.env.table) {
        imports.env.table = new WebAssembly.Table({
          initial: 0,
          element: 'anyfunc'
        });
      }

      return new WebAssembly.Instance(module, imports);
    });
}
```

And it fails in the line `return new WebAssembly.Instance(module, imports);` trowing a **LinkError**.

@kripken I took the loader from [your gist](https://gist.github.com/kripken/59c67556dc03bb6d57052fedef1e61ab), do you have any idea of what is going on? Maybe Im missing something in the `imports.env`?

Thanks a lot!

**Comment by lrecknagel** [comment]
Also have this Issue and tried it under:
* macOS 10.12.2
    * Chrome Canary@58.0.2997.0 canary (64-bit)
    * Chromium@58.0.2988.0 (64-bit)
    * Firefox Nightly@54.0a1 (2017-01-30) (64-bit)

* Compiled via: 

```bash
emcc filter.cpp -Os -s WASM=1 -s SIDE_MODULE=1 -o filter.wasm
```

* Code

```c++
#include <string>
#include <vector>

using namespace std;

int test() {

  std::vector<std::string> v;
  std::vector<std::string> r;

  v.push_back("value_01");
  v.push_back("value_02");
  v.push_back("value03");

  for (unsigned int i = 0; i < v.size(); i++) {
    if (v[i].find("value_") != std::string::npos) {
      printf("%s\n", v[i].c_str());
      r.push_back(v[i].c_str());
    }
  }

  return 0;
}
```

* Error which appears in Browsers:

```js
Uncaught (in promise) LinkError: WebAssembly.Instance(): Import #2 module="env" function="abort" error: function import requires a callable
    at fetch.then.then.then.module
```

(Also using your gist loader code to fetch the wasm file)

Hope there is help :)

Thanks a lot 🥇

**Comment by cpitclaudel** [comment]
Same issue here:

```
cvc4.wasm.js:5 Uncaught (in promise) LinkError: Import #8 module="env" function="abortOnCannotGrowMemory" error: function import requires a callable
```

**Comment by cpitclaudel** [comment]
(A workaround seems to be to compile with `-s BINARYEN_ASYNC_COMPILATION=0`)

**Comment by vans163** [comment]
im getting the same error when I try to link with a library compiled with emmake -s BINARYEN_ASYNC_COMPILATION=0 does not do anything for me

**Comment by tiagoinacio** [comment]
I'm also having this issue: 

`
Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #6 module="env" function="abortOnCannotGrowMemory" error: function import requires a callable
`

**Comment by kripken** [comment]
There are 2 C++ testcases here and a bunch of other details, so I'm not sure anymore what the testcase is to reproduce this problem. Please report a full set of steps to reproduce (as if filing a new bug).

**Comment by tiagoinacio** [comment]
I was able to compile an example using the following command:

`em++ src/wasm/utils.cpp -O3 -s WASM=1 -s MODULARIZE=1 -Wall -s VERBOSE=1 -o src/wasm/utils.js`

This will generate an `utils.js` file, which connects those missing functions like `__embind_register_memory_view` and `abortOnCannotGrowMemory`. We need to include that JS file in our html, and then fetch the wasm file.

**Comment by maoliangwu** [comment]
Is it resolved?

**Comment by VivianoRiccardo** [comment]
same issue
