### ISSUE TITLE
WebIDL - enum issues

### ISSUE THREAD

**Issue by JerryYangJin** [emscripten-core/emscripten#4793]
Hello, I'm using `WebIDL` for my c++ project, I found couple of issues regarding `enum'

This is from emscripten document for enum in a namespace

```
// C++
namespace EnumNamespace {
  enum EnumInNamespace {
        e_namespace_val = 78
  };
};

// WebIDL
enum EnumNamespace_EnumInNamespace {
  "EnumNamespace::e_namespace_val"
};
```

However, the generated glue cpp code is using `EnumNamespace_EnumInNamespace` instead of `EnumNamespace::EnumInNamespace`, which will fail during compiling; This looks like a bug.

Another issue, I can't use`[Prefix="namespace::"]` for enum, this is handy for interface though
If enum in c++ is in a namespace, then in a class, since I can't use prefix, I have to put something like this: 

```
enum namespace_class_enum {
  "namespace::class::enum_value"
}
```

This will also raise error for weidl binder

Please advise, thanks!

**Comment by kripken** [comment]
For the first issue, see `test_webidl` in `tests/test_core.py`, it appears to test what you say is not working. Perhaps there is some typo that explains the difference? Or is it not testing the same thing somehow?

**Comment by JerryYangJin** [comment]
@kripken , I'm using `1.36.0`, I've tried couple of times, in `glue.cpp`, the enum type used on function return or parameter is `EnumNamespace_EnumInNamespace`, it's only 'EnumNamespace::EnumInNamespace' when returning enum value in the enum bind part

e.g.

```
enum Rounding_Type {
	"Rounding::Closest"
};
```

```cpp

// function return type is not right
const Rounding_Type EMSCRIPTEN_KEEPALIVE emscripten_bind_Rounding_type_0(Rounding* self) {
  return self->type();
}

// same as above, but the return statement is right
Rounding_Type EMSCRIPTEN_KEEPALIVE emscripten_enum_Rounding_Type_Closest() {
  return Rounding::Closest;
}

```

**Comment by kripken** [comment]
Is that what happens in your example, or in the test I mentioned? Does the test pass for you?

**Comment by cqq626** [comment]
@JerryYangJin Have you fix your problem yet? I've encountered the same error "error: unknown type name 'EnumClass_EnumWithinClass'".

**Comment by jupake** [comment]
Not sure if this helps. I just fixed this with a typedef. In the test.cpp file from the repo you will find this line before glue.cpp: 

```cpp
typedef EnumClass::EnumWithinClass EnumClass_EnumWithinClass;
typedef EnumNamespace::EnumInNamespace EnumNamespace_EnumInNamespace;
```
I did something similar in my code and it compiled correctly with enums.

**Comment by microaaron** [comment]
I got the same issue:

error: unknown type name 'EnumClass_EnumWithinClass'
EnumClass_EnumWithinClass EMSCRIPTEN_KEEPALIVE emscripten_bind_EnumClass_GetEnum_0(EnumClass* self) {

error: unknown type name 'EnumNamespace_EnumInNamespace'
EnumNamespace_EnumInNamespace EMSCRIPTEN_KEEPALIVE emscripten_bind_EnumClass_GetEnumFromNameSpace_0(EnumClass* self) {

error: unknown type name 'EnumClass_EnumWithinClass'
EnumClass_EnumWithinClass EMSCRIPTEN_KEEPALIVE emscripten_enum_EnumClass_EnumWithinClass_e_val() {

error: unknown type name 'EnumNamespace_EnumInNamespace'
EnumNamespace_EnumInNamespace EMSCRIPTEN_KEEPALIVE emscripten_enum_EnumNamespace_EnumInNamespace_e_namespace_val() {
