### ISSUE TITLE
Installing emscripten sdk on travis-ci environment

### ISSUE THREAD

**Issue by guillaumeblanc** [emscripten-core/emscripten#4794]
Hi,

Is there a recommended way to install emcripten sdk on travis-ci linux environment ?

I tried installing with the portable sdk, but unfortunately installation takes too long (building clang https://travis-ci.org/guillaumeblanc/ozz-animation/jobs/183579148#L5411) compared to travis build time limit. 

Is there an example I can follow?

Cheers,
Guillaume

**Comment by kripken** [comment]
There are now binary builds for linux in the sdk, so this should be possible,

https://groups.google.com/forum/#!topic/emscripten-discuss/JCpNkUfaJ_Y

Would be great if in this repo we could run tests using that (probably can't do the whole suite, but at least a subset).

**Comment by kripken** [comment]
Experimenting with this in #5087. Help is welcome, I don't know much about this stuff.

**Comment by guillaumeblanc** [comment]
I don't know much about it either, but I'll try that and see what I can do.

Thanks for the update!

**Comment by curiousdannii** [comment]
This is now very straightforward. Please have a look at [the new page in the docs I wrote](http://kripken.github.io/emscripten-site/docs/compiling/Travis.html).
