### ISSUE TITLE
EGL in sub-thread?

### ISSUE THREAD

**Issue by answer1103** [emscripten-core/emscripten#4796]
I have a piece of code ,which run successfully in main thread ,but when put it in sub-thread ,it failed.

    EGLDisplay display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
    EGLint major = 0, minor = 0;
    EGLBoolean ret = eglInitialize(display, &major, &minor);

    EGLint numConfigs;
    ret = eglGetConfigs(display, NULL, 0, &numConfigs);

    EGLint attribs[] = {
        EGL_RED_SIZE, 5,
        EGL_GREEN_SIZE, 6,
        EGL_BLUE_SIZE, 5,
        EGL_NONE
    };
    EGLConfig config;
    ret = eglChooseConfig(display, attribs, &config, 1, &numConfigs);

    EGLNativeWindowType dummyWindow;
    EGLSurface surface = eglCreateWindowSurface(display, config, dummyWindow, NULL);

    // The correct attributes, should create a good EGL context
    EGLint contextAttribs[] =
    {
        EGL_CONTEXT_CLIENT_VERSION, 2,
        EGL_NONE
    };
    context = eglCreateContext(display, config, NULL, contextAttribs);

Is it because egl can't run in sub-thread?

Any idea about load data in sub-thread to gles?

**Comment by answer1103** [comment]
get the EGL error 0x3009 (egl_bad_match).

**Comment by chpio** [comment]
nope, WebGL is not allowed in a worker. Maybe you could use this: https://github.com/kripken/webgl-worker
