### ISSUE TITLE
Wasm ABI?

### ISSUE THREAD

**Issue by qwertie** [emscripten-core/emscripten#4804]
Is there a particular ABI - i.e. a convention for passing primitives and `struct`s, for name mangling - that has become popular for linking Wasm C++ modules together? If so I'd probably like to grow a multi-language standard ABI out of that.

**Comment by dschuff** [comment]
There is no documented ABI yet (and in particular when we have documented any related things we have taken pains to state that what binary interface exists is not stable yet). But it is very much on the list of things we are interested in. We created a repo https://github.com/WebAssembly/tool-conventions for the purposes of documenting things like this and have just recently started adding things to it. Also on our list is to make asm.js/fastcomp and the new upstream LLVM wasm backend use the same ABI (currently they don't).

**Comment by dschuff** [comment]
Oh, and just in case it wasn't clear, we'd love to have your participation. Even before the ABI is stable, I'd like to at last have it documented but one of the reasons there's nothing there yet is that nobody has gotten to it yet. So if you are interested in interoperating with C or C++, you can start making some noise and things will likely start happening.

**Comment by qwertie** [comment]
Thanks, @dschuff. I'd like to help, but I lack a background in C/C++ back-ends. I'm driven by the dream of high-level interoperability, like "how can we let different languages share a graph of precisely garbage-collected objects?" - but of course, magic like that can't happen without figuring out some low-level questions first. I'll have a look at that repo.

**Comment by dschuff** [comment]
https://github.com/WebAssembly/tool-conventions/blob/master/BasicCABI.md and https://github.com/WebAssembly/tool-conventions/blob/master/ItaniumLikeC%2B%2BABI.md exist for this purpose. They are not complete but issues should be filed and discussed there.
