### ISSUE TITLE
clang crash when compiling header with emcc

### ISSUE THREAD

**Issue by labsin** [emscripten-core/emscripten#4810]
Some build systems (at least qt's) try to compile headers to check if they compile with the provided compile options.

When issuing `em++ -c -pipe -g -fPIC -std=c++1z -xc++ test.h -o test.o` I get a segfault in clang with attached output.
When issuing `clang++ -c -pipe -g -fPIC -std=c++1z -xc++ test.h -o test.o` there is no issue. (with the clang from the sdk)

With test.h being just:
```
/*
 * test.h
 * Copyright (C) 2016 Sam Segers <sam.sgrs@gmail.com>
 *
 * Distributed under terms of the The Unlicense license.
 */

#ifndef TEST_H
#define TEST_H

class Test {
};

#endif /* !TEST_H */
```

[output.txt](https://github.com/kripken/emscripten/files/661666/output.txt)

**Comment by kripken** [comment]
Interesting, looks like it's the `-xc++` flag here. It should be fine to run it without that flag actually, since you are calling `clang++` anyhow so it's in c++ mode. But clang does issue a deprecation warning about that.

I'm not sure why it crashes. Perhaps with `-xc++` it re-invokes clang as `clang++` or something like that?

**Comment by labsin** [comment]
Indeed, without -xc++, it's not crashing.
I tried:
`clang -c -pipe -g -fPIC -std=c++1z -xc++ test.h -o test.o`
`clang++ -c -pipe -g -fPIC -std=c++1z -xc++ test.h -o test.2.o`
And they produce an identical file (md5sum)

Issuing:
`clang++ -c -pipe -g -fPIC -std=c++1z test.h -o test.3.o` (without the -xc++)
gives the warning: _clang-3.9: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated_

This last one produces a different file, which is not an ELF but an precompiled header.
The default language for header files is x++-header when using clang++ and following gives the same file:
`clang -c -pipe -g -fPIC -std=c++1z -xc++-header test.h -o test.4.o`

So issuing emcc without -xc++ is working as it produces precompiled headers instead of the bitcode

**Comment by labsin** [comment]
Ok, found the difference with emcc by using EMCC_DEBUG=1.

`EMCC_DEBUG=1 em++ -c -xc++ test.h -o test.5.o`
Calls clang++ with:
`/home/sam/Apps/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=36 -D__EMSCRIPTEN_tiny__=14 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libcxx -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libcxxabi/include -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/compat -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/emscripten -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SSE -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libc -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/local/include -c -xc++ -std=c++03 test.h -o test.5.o -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SDL`

`EMCC_DEBUG=1 em++ -c -xc++ test.cpp -o test.5.o` (test.cpp is a copy of test.h)
Calls clang++ with:
`/home/sam/Apps/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=36 -D__EMSCRIPTEN_tiny__=14 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libcxx -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libcxxabi/include -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/compat -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/emscripten -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SSE -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libc -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/local/include -c -xc++ -std=c++03 test.cpp -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SDL -emit-llvm -c -o test.5.o`

So with the cpp file, emcc adds  -emit-llvm. With the header it doesn't add it (probably because it expects them to be compiled as precompiled headers)

Emcc should probably also add  -emit-llvm with header files if -xc++ or -xc is explicitly added (so -x<language>-header is not implied)

**Comment by labsin** [comment]
If I run
```
/home/sam/Apps/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang++ -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=36 -D__EMSCRIPTEN_tiny__=14 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libcxx -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libcxxabi/include -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/compat -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/emscripten -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SSE -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libc -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/local/include -c -xc++ -std=c++03 test.h -o test.5.o -Xclang -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SDL -emit-llvm
```
It seems to be working as it should, producing llvm bitcode

**Comment by labsin** [comment]
The proposed fix is not 100% because there will probably be other cases that are not working (whith the -x directives), but it's very minimal and working in my case.
But that is now also not possible as emcc is not filtering any -x arguments.
