### ISSUE TITLE
Trap error, name demangling

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#4817]
This piece of code generates the following error message at runtime
due to this line of code, the compiler warns me with a
warning that this is not the return parameter however has problems in runtime.

	char* each ( std::vector<int> v , void (*callback)(int) ) 
	{
		for_each ( v.begin() , v.end() , callback ) ;

	}

normally it works so
	
	void each ( std::vector<int> v , void (*callback)(int) ) 
	{
		for_each ( v.begin() , v.end() , callback ) ;
	}

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang dbe68fecd03d6f646bd075963c3cc0e7130e5767) (https://github.com/kripken/emscripten-fastcomp.git 4e83be90903250ec5142edc57971ed4c633c5e25)
Target: x86_64-pc-windows-msvc
Thread model: posix
INFO:root:(Emscripten: Running sanity checks)

pre-main prep time: 2 ms
main.js:143 
main.js:143 10
main.js:143 
main.js:143 20
main.js:143 
main.js:143 30
main.js:143 trap!
main.js:146 trap!
main.js:146 warning: a problem occurred in builtin C++ name demangling; build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
main.js:16154 Uncaught abort("trap!") at Error
    at jsStackTrace (file:///C:/project/$/ex/main.js:1173:13)
    at stackTrace (file:///C:/project/$/ex/main.js:1190:22)
    at abort (file:///C:/project/$/ex/main.js:16272:44)
    at _llvm_trap (file:///C:/project/$/ex/main.js:5808:7)
    at Array.__Z4eachNSt3__16vectorIiNS_9allocatorIiEEEEPFviE [each?N()] (file:///C:/project/$/ex/main.js:6269:2)
    at Object.dynCall_iii (file:///C:/project/$/ex/main.js:15911:38)
    at invoke_iii (file:///C:/project/$/ex/main.js:5978:33)
    at _main (file:///C:/project/$/ex/main.js:6515:6)
    at Object.asm._main (file:///C:/project/$/ex/main.js:16003:19)
    at Object.callMain (file:///C:/project/$/ex/main.js:16137:30)

source code

	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#include <iostream>
	#include <algorithm>
	#include <vector>

	#include <emscripten.h>
	#include <emscripten/html5.h>

	void doSomething ( int x )
	{
		printf ("\n%d\n",x);
	}

	char* each ( std::vector<int> v , void (*callback)(int) ) 
	{
		for_each ( v.begin() , v.end() , callback ) ;

	}

	int main ( void )
	{

		std::vector<int> v;
		v.push_back(10);
		v.push_back(20);
		v.push_back(30);

		
		each ( v , doSomething );

		return 0 ;
	}

compiled with demangling supported, situation does not change

emcc prova2.cpp -o main.js -s DEMANGLE_SUPPORT=1
prova2.cpp:24:2: warning: control reaches end of non-void function [-Wreturn-type]
        }
        ^
1 warning generated.
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')

**Comment by kripken** [comment]
I think this is expected behavior. It warns at compile time about a non-void function not having a return value. Then it puts a trap at that location, because it's undefined behavior and shouldn't be reached. That is the trap you see at runtime.

(It's true that the return value isn't used, so in a sense it's "safe" to not return anything there, but I guess LLVM doesn't know that.)

**Comment by ssx71** [comment]
this predictable behavior is then only restricted to this example? or we
can run into other traps?

2016-12-23 19:35 GMT+01:00 Alon Zakai <notifications@github.com>:

**Comment by kripken** [comment]
That is the only one I can think of where LLVM adds a trap that can be hit in normal execution. But there might be more I am unaware of in theory.

In general, if you get rid of all warnings at compile time, you can avoid problems like this.
