### ISSUE TITLE
Webbrowser.open_new() is problematic in test harness

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4828]
The test `browser.test_html_source_map` uses the construct `webbrowser.open_new('file://' + html_file)` as part of the test. This is problematic because it attempts to open a new browser instance, which fails on the Firefox profile manager saying the current profile is already in use in an open Firefox instance. 

Also related, the test harnesses run with a custom `EMSCRIPTEN_BROWSER` environment variable, which can look something like

    EMSCRIPTEN_BROWSER="C:/Program Files (x86)/Mozilla Firefox/firefox.exe" -P test_stable --no-remote

or

    EMSCRIPTEN_BROWSER="C:/Program Files/Nightly/firefox.exe" -P test_nightly --no-remote

so in this case, opening two browser process instances with the same Firefox profile is attempted, which fails the test.

The `emrun` script could be used to launch the file if `file://` URLs are absolutely needed, in a way that a new temporary Firefox profile is created (`emrun` parameter `--safe_firefox_profile`). Is that the case for this test? It's a bit unclear if the intent here is to specifically test `file://` URLs, or if this came to happen by coincidence? Also, Chrome takes issues with `file://` URLs when XHRing files relative to it, so this test would probably not work for Chrome either.

**Comment by kripken** [comment]
I think what happened is file urls were the only way i could get source maps to work. But if they work - i.e. the source map is present in the debugger - then we can make this open a tab normally.

**Comment by kripken** [comment]
(That was a long time ago, I filed a bunch of browser bugs as I recall, hopefully fixed.)
