### ISSUE TITLE
Boost emscripten compilation 

### ISSUE THREAD

**Issue by YairMobile19** [emscripten-core/emscripten#4834]
Hello,

We have a large project in C++ which we have successfully compiled using Emscripten.
We are now in the process of converting the Boost library and order to support multi threading in our project.
I've followed the procedure described at http://stackoverflow.com/questions/15724357/using-boost-with-emscripten
and managed to compile the Boost 'thread' library into an .so file ( doing so on an Ubuntu machine ).
Now, when I try to 'Link' this .SO with our own .BC libraries I get various warnings and errors like:
warning: Linking two modules of different data layouts...
warning: Linking two modules of different target triplets...

and lastly:
LLVM ERROR: ExpandSmallArguments does not handle varargs functions

So, my question is this:

A. Perhaps by some kind of a miracle someone already compiled Boost 1.55 using Emscripten and can point me to the binaries?

B. If not - Is it OK to compile on an Ubuntu machine and link on a Windows based OS?

Thank you.

**Comment by juj** [comment]
In general it should be ok to reuse code compiled on different OSes, but make sure to have the exact same compiler version. Also you can try using 'llvm-dis' on the compiled code to compare what the data layouts and triplets were, to rule out if it might have been possible that the compilation got somehow botched and built a native Ubuntu library for example.
