### ISSUE TITLE
node_modules checked in to Emscripten?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4836]
We have a `node_modules/` directory checked in to the repository, namely here:

https://github.com/kripken/emscripten/tree/master/tools/eliminator/node_modules

In general `node_modules/` contains installed build artifacts resulting from a `npm install`, so those aren't traditionally checked in to a repository.

When doing uploads of precompiled SDKs to Amazon, I filtered out `node_modules/` directories because I thought them to be temporary, but that killed uglify-js from working. (https://github.com/juj/emslave/issues/1)

I wonder if we should `npm install` uglify-js on demand before attempting to use it, and remove `tools/eliminator/node_modules`?

Or alternatively, perhaps keep `tools/eliminator/node_modules` but still first check if it is missing and  `npm install` it if so?

Although the current uglify-js library that is checked in is very small, so perhaps could be considered as a special case. But then, I wonder if we might want to relocate it so that it doesn't live in such a build-artifacty sounding directory name?

**Comment by kripken** [comment]
In theory we could do it the more npm-friendly way, but we do need the very specific old versions of Uglify, and also we modified it. So I don't think we can do `npm install uglify-js`. Perhaps we could just rename the directory to clarify things, but I'm not sure how it's imported, maybe it depends on the specific name?

**Comment by asRIA** [comment]
Hi,
We've just hit this issue when we tried to compile our game with the latest nightly build. 
Right now js-optimizer requires this package by relative path: 
https://github.com/kripken/emscripten/blob/master/tools/js-optimizer.js#L132 

I understand motivation of not having it repository, can js-optimizer `require("uglify-js")` instead?

**Comment by kripken** [comment]
Strange, this didn't change recently - the location is very old. So I'm surprised this would break anything recently? Unless I am forgetting a change. Is it feasible for you to bisect to find the bad changeset?

**Comment by asRIA** [comment]
Ough sorry, I was imprecise, it didn't happened between update to latest nightly and one before. This error has happened after a while of not updating SDK, so most likely I used before a version when it worked fine.
