### ISSUE TITLE
intArrayToString doesn't stop at null

### ISSUE THREAD

**Issue by dasa** [emscripten-core/emscripten#4840]
Ref: https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html#intArrayToString

**Test**
`lib.intArrayFromString("abc")` -> `[ 97, 98, 99, 0 ]`
`lib.intArrayToString([ 97, 98, 99, 0 ])` -> `abc\u0000`

Should `intArrayToString` just return `abc` in this case?

**Comment by kripken** [comment]
Good point, those two functions are apparently not the inverse of each other. Which is asymmetrical and a little inelegant. Also the docs suggest the current behavior is wrong, the zero shouldn't be added.

Changing the second function would be a breaking change, though, so we should be careful. Perhaps we should just document this and not change it? cc @juj

**Comment by dasa** [comment]
I would prefer that it was fixed since I have a use case to call it and would like it to work as doc'ed.

Thanks for taking a look at this.

**Comment by dasa** [comment]
Ping please 😄

**Comment by dasa** [comment]
I'm not sure if this was fixed, but if not, it looks like the doc should be updated: https://emscripten.org/docs/api_reference/preamble.js.html?highlight=intarraytostring#intArrayToString
