### ISSUE TITLE
Permissions of target.js file messed up with -s WASM

### ISSUE THREAD

**Issue by lukester1975** [emscripten-core/emscripten#4858]
Hi

Minor issue. On Linux, most output files from emscripten have 0644 (& umask) permission. Except the target.js file, if wasm is enabled, when it only sets owner bits (no group or other AFAICT). E.g. with my umask of 0027:

```
-rw-r----- 1 luke luke 106874 Jan 13 17:42 main.asm.js
-rw-r----- 1 luke luke     26 Jan 13 17:29 main.cpp
-rw-r----- 1 luke luke 103077 Jan 13 17:42 main.html
-rw------- 1 luke luke  91103 Jan 13 17:42 main.js
-rw-r----- 1 luke luke  23302 Jan 13 17:42 main.wasm
-rw-r----- 1 luke luke 517010 Jan 13 17:42 main.wast
```

My no-python knowledge has tracked this down to python's tempfile.NamedTemporaryFile(), as it doesn't seem there's any emscripten code setting the bits.

I've hacked my emcc.py to add

```
import stat
os.chmod(temp_target, stat.S_IMODE(os.stat(js_target).st_mode))
```

after the call out to separate_asm.py.

I tripped over it because my local apache needs group access (apache is in my user's group and I mask off all other bits).

I can create a PR if it's useful but I suspect there's much better ways to solve it, if indeed it's considered a problem.

Thanks

Luke.

**Comment by kripken** [comment]
Can you please check if that is still the case on very latest incoming? A PR landed that affected how wasm's js is emitted. After that change, I think it should be the same for wasm and non-wasm. But maybe both are wrong? ;)

**Comment by lukester1975** [comment]
Hi

No change at 62dfd0f886bfc0a4bf7fb0663ba164dcda6ba253 - permissions OK with non-wasm and only user bits set with wasm. Doesn't look like the area around where I did my hack changed at all.

Thanks

**Comment by kripken** [comment]
I see, thanks for checking. Ok, I confirmed this locally. Not sure why python gives the wrong permissions to temp files, but anyhow, we don't need a temp file there. So it's more efficient anyhow to not use one. I opened #4866, please confirm it fixes things for you too.

**Comment by lukester1975** [comment]
Yeah works for me, thanks!
