### ISSUE TITLE
.as<Instance *>() isn't supported

### ISSUE THREAD

**Issue by arcanis** [emscripten-core/emscripten#4863]
Using `val.as<Instance *>()` crash because of the safety policy that prevents us from using raw pointers. I haven't been able to find how to disable it ... even using `internal::AllowRawPointers` isn't sufficient, since it messes with the function return value :(

**Comment by AlexPerrot** [comment]
Hello,

Can you provide a use case where you would need to pass a pointer as `val` ?

I recently stumbled into a similar issue (but in reverse) where 

``` c++
return emscripten::val(new Foo());
```

isn't allowed due to raw pointers binding.

But

``` c++
Foo* fp = new Foo();
return emscripten::val(fp);
```
is fine.

**Comment by arcanis** [comment]
iirc, it was because I need to convert a javascript array of pointers into a `std::string<Foo *>`. I ended up patching the `as<>` specialization to correctly allow for raw pointers (https://github.com/atom/superstring/pull/7/files#diff-5250a5a28e24ded85a19f944193677a2).

**Comment by AlexPerrot** [comment]
With PR #4992, you can now pass `allow_raw_pointers()` to `val::as` to be able to cast to pointers, just like using embind.
So you do : 

``` C++
val.as<Instance *>(allow_raw_pointers());
```

**Comment by AlexPerrot** [comment]
Support was added, so we can close this.
