### ISSUE TITLE
emscripten_async_wget2_data not accepting username and password and custom headers

### ISSUE THREAD

**Issue by sahilagnihotri** [emscripten-core/emscripten#4864]
I am using emscripten_async_wget2_data but sometimes the server can have a username and password authentication. So we are doing this:
emscripten_async_wget2_data_myCopy : function(url, request, param, arg, free, onload, onerror, onprogress, username, password, headers) 
/////
      var _username = Pointer_stringify(username);
      var _password = Pointer_stringify(password);
/////////
      http.open(_request, _url, true, _username, _password);
      if (_username.length != 0 || _password.length != 0) {
          http.setRequestHeader("Authorization", "Basic " + btoa(_username + ":" + _password));
          http.withCredentials = true;
      }
//////

and then in the     http.onload = function http_onload(e), i am not doing the match against http _url.substr(0,4).toLowerCase() != "http") 

/////// and similarly for custom headers

Is it possible to include it in Emscripten through pull request?
Or may be there is certain reason to not include authetication support method to Emscripten?

**Comment by kripken** [comment]
I think the goal has been to not add more functionality to that method, and instead work on @juj's fetch API. @juj can provide more details.

**Comment by sahilagnihotri** [comment]
@juj when do we plan to have some docs about it. I can implement using .h file, just wondering if its finalized or still in dev phase ?
@kripken i have some issues with memory on my current implemenation and i stumbled upon this: https://github.com/kripken/emscripten/issues/2621 I did added my functions in deps_info.json but still same, is there any specific way ? Also on totally unrelated but interesting note came accross issues with memory peaks in javascript n gpu memory going 1.8 Gb n reseting driver. Funny bit different mem usage accross if angle used or not   :)

**Comment by kripken** [comment]
#2621 looks fixed, so maybe you are seeing some other problem?
