### ISSUE TITLE
EM_ASM_STRING_ family functions

### ISSUE THREAD

**Issue by newnon** [emscripten-core/emscripten#4870]
i have made helper functions for emscripten to get string from js code
it is sample but working code it will be nice to see it inside emscripten
```cpp
#define EM_ASM_STRING_MALLOC(code, ...) \
    (const char*)EM_ASM_INT({ \
        var result = (function () {code}()); \
        return allocate(intArrayFromString(result), 'i8', ALLOC_NORMAL); \
    }, __VA_ARGS__)

#define EM_ASM_STRING_SHARED(code, ...) \
    (const char*)EM_ASM_INT({\
        if(typeof Module.em_asm_string_malloc_buffer === 'undefined') \
            Module.em_asm_string_malloc_buffer = {}; \
        var result = (function () {code}()); \
        var me = Module.em_asm_string_malloc_buffer; \
        var utf8Length = lengthBytesUTF8(result); \
        if (!me.bufferSize || me.bufferSize < utf8Length+1) { \
            if (me.bufferSize) _free(me.buffer); \
                me.bufferSize = utf8Length+1; \
                me.buffer = _malloc(me.bufferSize); \
        } \
        stringToUTF8(result, me.buffer, me.bufferSize); \
        return me.buffer; \
    }, __VA_ARGS__)

#define EM_ASM_STRING_MALLOC_V(code) \
    (const char*)EM_ASM_INT_V( \
        var result = (function () {code}()); \
        return allocate(intArrayFromString(result), 'i8', ALLOC_NORMAL); \
    )

#define EM_ASM_STRING_SHARED_V(code) \
    (const char*)EM_ASM_INT_V( \
        if(typeof Module.em_asm_string_malloc_buffer === 'undefined') \
            Module.em_asm_string_malloc_buffer = {}; \
        var result = (function () {code}()); \
        var me = Module.em_asm_string_malloc_buffer; \
        var utf8Length = lengthBytesUTF8(result); \
        if (!me.bufferSize || me.bufferSize < utf8Length+1) { \
            if (me.bufferSize) _free(me.buffer); \
                me.bufferSize = utf8Length+1; \
                me.buffer = _malloc(me.bufferSize); \
        } \
        stringToUTF8(result, me.buffer, me.bufferSize); \
        return me.buffer; \
    )
```

**Comment by kripken** [comment]
Interesting idea, nice.

The risk is that people might forget to free the malloc'ed version, or misuse the shared version. But with proper documentation maybe that is ok.

Do you want to open a PR with this?

**Comment by newnon** [comment]
i'm not sure about where to place this, i think its better if you just take this code and place it where it really should be. Its better to make some js functions inside which you will call <code> because with my code you will get copy of it every time

**Comment by kripken** [comment]
It should be in emscripten.h alongside the other EM_ASM methods, probably. But we'd need to write up docs and add tests, all of which would be necessary in a PR for it to be merged.

If you don't have time for that there is no problem of course. We can leave this open and maybe someone else will pick it up. If you do have time and interest, though, I can help you with the steps to make the PR.

**Comment by newnon** [comment]
it is pr for this feature but i'm not sure about it correctness https://github.com/kripken/emscripten/pull/4875
