### ISSUE TITLE
Create an emscripten GitHub organization

### ISSUE THREAD

**Issue by Croydon** [emscripten-core/emscripten#4880]
Right now it's harder to get an overview of all emscripten repositories as it needs to be.

The best approach currently is to scroll through the list of all repositories of @kripken - but the official advertised SDK is here: https://github.com/juj/emsdk

Using an organistation would solve that. Also don't worry about old links, GitHub is redirecting from the previous place.

**Comment by kripken** [comment]
Seems like a good idea to me. Curious what others think.

**Comment by DeepakRajendrakumaran** [comment]
+1. As someone who is new to webassembly and the compilation toolchain for it using emscripten, I have a related question. Is there any documentation showing the 'c language support' provided by the toolchain to compile to wasm? I see an API limitation page but that seem to point out browser limitation as opposed to compiler tool-chain limitation. and I am more interested in the current emscripten capability as I am interested in non-browser applications.

**Comment by dschuff** [comment]
I like this idea too. We already have emscripten, emsdk, the fastcomp repos, ports, the website, etc. I'd also like to eventually move system libs and ports out of the emscripten repo a la  https://github.com/kripken/musl-emscripten (obviously we can discuss that in a separate thread). But in any case it seems like a good idea even with the repos we already have.

**Comment by kripken** [comment]
Hmm, so there already exists an emscripten organization, https://github.com/emscripten . It has no public members and no apparent way to tell who created it or when? Looks like a placeholder.

I guess we could just create something with an alternative name like emscripten-org?

**Comment by bontibon** [comment]
@kripken I have had success with Github transferring ownership of dormant accounts. Try [contacting](https://github.com/contact) them to see what they can do.

**Comment by kripken** [comment]
Thanks, I contacted them now.

**Comment by Croydon** [comment]
There might be still some repositories which aren't transferred yet (?), but there is now an emscripten org.
