### ISSUE TITLE
EMbinding template functions and classes. Is it even possible?!

### ISSUE THREAD

**Issue by DAB0mB** [emscripten-core/emscripten#4887]
Hello there!
I'm trying to bind a template class using `embind`, but unfortunately I failed with each of my attempts. I tried lots of different ways, and I also approached the documentation page in the official website, but there are lots of things which are missing in there and I could't really follow it. Here's the class that I'm trying to bind:

```cpp
template<typename T>
  class Chain {
    private:
      T accumulator;

      template<typename U, typename Fn, class... Args>
      Chain<U> link(Fn fn, Args&&... args);

    public:
      Chain(T accumulator);

      template<typename... Args>
      Chain<double> mod(Args&&... args);

      template<typename... Args>
      Chain<double> trim(Args&&... args);

      template<typename... Args>
      Chain<boolean> isBetween(Args&&... args);

      template<typename... Args>
      Chain<boolean> compare(Args&&... args);

      T result();
  };
```

Does anyone know how to do it? Any comment would be very appreciated.

**Comment by AlexPerrot** [comment]
Hello,

In C++, templates are generated at the compilation time, not the execution.
So, embind cannot bind the templated version, you need instantiate the template in order to bind it.

The type `emscripten::val` can represent any js value, so using `Chain<emscripten::val>` should all js use cases. 

```
EMSCRIPTEN_BINDINGS(chain) {
  class_<Chain<val>>("Chain")
}
```

Not sure about varidic templates support, though.

**Comment by kostyfisik** [comment]
It helped me to review test file for possible use cases. Instantation during binding is a possible option: https://chromium.googlesource.com/external/github.com/kripken/emscripten/+/asm2wasm/tests/embind/embind_test.cpp#1783
