### ISSUE TITLE
curl calls not working via browser or native node

### ISSUE THREAD

**Issue by barrystyle** [emscripten-core/emscripten#4906]
Hi all,

Have been playing with some TCP sockets code using curl; tearing my hair out gradually.
While the code comes across and compiles correctly, the sockets fail each time.
There seem to be some mixed announcements; some saying that TCP calls don't work from browser, some saying that CONNECT etc works.

When I compile my code in C++, using either TCP or Websockets (with a redirect on the webserver itself from :8080 to intended TCP destination) it works correctly. However, every time i bring the code across via Emscripten; it doesnt work either in node.js or in Chrome/Firefox. Neither gives an error, the socket attempt is just never successful. In Nodejs, the code starts and doesnt emit any debugging information - nor is anything seen on the logger of the forwarder.

Any ideas/hints guys?
james

**Comment by fbitti** [comment]
@barrystyle I hope you are doing well. I'd like to try it out, could you share the steps you used to compile curl to wasm and to run it on node? 👍 Thank you

**Comment by jrynkiew** [comment]
I'm interested in this topic as well, but it's 4 years old...

**Comment by barrystyle** [comment]
thankyou for the response.. i think back then i hadnt realised that code running in a browser just isnt going to perform tcp calls like a native application would, i think there was some movement towards wrapping calls via websockets?

**Comment by jrynkiew** [comment]
You have to use emscripten_fetch instead of curl. Like so:

First define the variables needed for cURL and a string buffer for use with emscripten WASM or Windows/Linux binaries (determined at build time)


```
CURL *curl;
CURLcode res;
std::string readBuffer;
```

Then the implementation
```

#if defined(__EMSCRIPTEN__)
    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    strcpy(attr.requestMethod, "GET");
    attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
    attr.onsuccess = onLoaded;
    attr.onerror = onError;
    attr.userData = &readBuffer;
    emscripten_fetch(&attr, "http://localhost");
    printf("Wallet Connection in progress....");
    printf(readBuffer.c_str());

#else
    curl = curl_easy_init();
    if(curl) {
        curl_easy_setopt(curl, CURLOPT_URL, "https://jrpc.pl/");
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &readBuffer);
        res = curl_easy_perform(curl);
        curl_easy_cleanup(curl);
        printf(readBuffer.c_str());
    }   
#endif
```

and the callback functions for cURL and emscripten_fetch

```
static size_t WriteCallback(void *contents, size_t size, size_t nmemb, void *userp)
{
    ((std::string*)userp)->append((char*)contents, size * nmemb);
    return size * nmemb;
}
```

```
#if defined(__EMSCRIPTEN__)
    static void onLoaded(emscripten_fetch_t *fetch) 
    {
        printf("Finished downloading %llu bytes from URL %s.\n", fetch->numBytes, fetch->url);
        ((std::string*)(fetch->userData))->append((char*)fetch->data, fetch->totalBytes * fetch->numBytes);
        emscripten_fetch_close(fetch);
    }
    static void onError(emscripten_fetch_t *fetch)
    {
        printf("Connecting to ioPay %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
        ((std::string*)(fetch->userData))->append((char*)fetch->data, fetch->totalBytes * fetch->numBytes);
        emscripten_fetch_close(fetch);
    }
#endif

```
