### ISSUE TITLE
-s BINARYEN=1 -s BINARYEN_METHOD='native-wasm,asmjs' downloads .wasm even if wasm is not supported

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#4910]
Related to #4909, when one builds `em++ tests\hello_world.cpp -s BINARYEN=1 -s BINARYEN_METHOD='native-wasm,asmjs' -o a.html`, and runs on a browser that does not support Wasm, we get

	C:\code\emsdk\emscripten\incoming>python -m SimpleHTTPServer
	Serving HTTP on 0.0.0.0 port 8000 ...
	127.0.0.1 - - [02/Feb/2017 01:03:12] "GET /a.html HTTP/1.1" 200 -
	127.0.0.1 - - [02/Feb/2017 01:03:12] "GET /a.wasm HTTP/1.1" 200 -
	127.0.0.1 - - [02/Feb/2017 01:03:12] "GET /a.html.mem HTTP/1.1" 200 -
	127.0.0.1 - - [02/Feb/2017 01:03:18] "GET /a.js HTTP/1.1" 200 -
	127.0.0.1 - - [02/Feb/2017 01:03:18] "GET /a.asm.js HTTP/1.1" 200 -

but one doesn't really need to download the `.wasm` file if lack of support for WebAssembly was detected, but it would be possible to directly just jump to downloading `.asm.js`.

**Comment by kripken** [comment]
Yes, I suppose we could check for wasm support in the HTML first, and skip loading the wasm if it's not present.
