### ISSUE TITLE
isatty() not detecting output redirection properly

### ISSUE THREAD

**Issue by mosra** [emscripten-core/emscripten#4920]
I'm using `isatty()` to decide whether to have ANSI-colored output (when outputing to terminal) or not (when redirected to file). However, with Emscripten I'm always getting a positive result regarless of file redirection. Currently I have to ask Node.js as a workaround -- it gives the expected result.

Minimal test case:

```cpp
#include <iostream>
#include <unistd.h>

#ifdef EMSCRIPTEN
#include <emscripten.h>
#endif

int main() {
    std::cout << (isatty(1) ? "isatty() says YES" : "isatty() says NO") << std::endl;

    #ifdef EMSCRIPTEN
    int nodeIsatty = EM_ASM_INT_V({
        if(typeof process !== 'undefined')
            return process.stdout.isTTY;
        return false;
    });
    std::cout << (nodeIsatty ? "Node.js says YES" : "Node.js says NO") << std::endl;
    #endif
}
```

And output:

```
![mosra@don-perverzo tests]$ c++ tty.cpp -o tty
![mosra@don-perverzo tests]$ ./tty
isatty() says YES
![mosra@don-perverzo tests]$ ./tty | cat
isatty() says NO
![mosra@don-perverzo tests]$ em++ tty.cpp -o tty.js
![mosra@don-perverzo tests]$ node tty.js
isatty() says YES
Node.js says YES
![mosra@don-perverzo tests]$ node tty.js | cat
isatty() says YES
Node.js says NO
```

I'm on version 1.37.1, if that makes any difference. Thanks a lot!

**Comment by kripken** [comment]
If you're interested to investigate this, I would start to look in the emitted code (in a non-optimized build, so whitespace is present) to see what `isatty()` ends up calling. Or use `-s LIBRARY_DEBUG=1`, or `SYSCALL_DEBUG` which will print out library calls/syscalls, as I am pretty sure it will end up doing a syscall. We then need to add support in that syscall to hook into node.js somehow.

**Comment by mosra** [comment]
Tracked it down to a TCGETS ioctl [here](https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/library_syscall.js#L311), which always returns 0 for standard in/out and emits a warning (probably related). The originating commit was https://github.com/kripken/emscripten/commit/fca780db9168bbd10b9a9724914a8a345eebabea, if that helps something.
```cpp
      case {{{ cDefine('TCGETS') }}}: {
        if (!stream.tty) return -ERRNO_CODES.ENOTTY;
#if SYSCALL_DEBUG
        Module.printErr('warning: not filling tio struct');
#endif
        return 0;
      }
```

**Comment by mosra** [comment]
I'm still using that Node.js workaround on my side and due to how busy I am it's unlikely I will have time to implement support for this on Emscripten side. Interesting that nobody else encountered the same problem in the past 2 years tho :)
