### ISSUE TITLE
ELIMINATE_DUPLICATE_FUNCTIONS=1 produces invalid asm.js

### ISSUE THREAD

**Issue by ImplOfAnImpl** [emscripten-core/emscripten#4926]
Emscripten version: 1.37.1 and earlier.

Steps to repoduce:
1) Create EliminateDupFuncsTest.cpp:
```
double f()
{
    return 1;
}

int main()
{
    f();
}
```
2) Run
```
em++  EliminateDupFuncsTest.cpp -O2 -g2 -s OUTLINING_LIMIT=10 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -o EliminateDupFuncsTest.html
```
3) Open EliminateDupFuncsTest.html in Firefox. The following is printed to its Web Console:
```
TypeError: asm.js type error: double is not a subtype of int
```
I.e. it fails to recognize the generated js as asm.js

Details:
`eliminate-duplicate-functions.js` uses Uglify to parse js code which always turns literals like `xxx.0` into just `xxx`. Though Emscripten protects the code from this by temporarily changing such literals into `DOT$ZERO(xxx)`, some of them remain in the plain form, namely, the initial values `0.0` for variables `tempDouble`, `tempBigIntR` and `tempFloat`. The last two of them seem to never be used, but `tempDouble` may be used, e.g. if OUTLINING_LIMIT is specified. If that happens, it gets assigned with floating point values, which is incorect asm.js, because due to the initial assignment of `0` the type of `tempDouble` is now `int`.

As a hotfix I may suggest to change the initial value of those variables to non-zero, e.g. to `1.1`, so that they're not touched by Uglify. This shouldn't break anything, since the initial values don't seem to be ever used, they only specify the types of the variables.

**Comment by kripken** [comment]
Thanks for the report and analysis. That all sounds correct, however, the fix needs to be a little more complicated, since the initial value must be `0.0` due to asm.js typing rules.

**Comment by ImplOfAnImpl** [comment]
Perhaps I'm missing something, but according to [asmjs.org](http://asmjs.org/spec/latest/#variable-type-annotations) it's enough for the initializer to contain `.` for the variable to be typed as `double`

**Comment by kripken** [comment]
Perhaps I'm wrong, I thought that was true for function vars, but maybe global ones are different?

Anyhow, easy to test :) PR welcome if it works, of course.
