### ISSUE TITLE
How do you update Binaryen in emscripten ports?

### ISSUE THREAD

**Issue by rahulchaphalkar** [emscripten-core/emscripten#4928]
I updated emscripten to master (1.37.0), but my binaryen in emscripten ports is tagged 21. How do I get the latest one? I can't see it here https://github.com/emscripten-ports , although it does show up in `./emcc --show-ports`.

**Comment by kripken** [comment]
There can be a dependency between emscripten version and binaryen version, for example, if binaryen changed an api, emscripten needs to use it properly. So in general, the version of binaryen that emscripten uses is the correct one.

So to use the newest binaryen, you'd need to use newer emscripten. For example incoming (1.37.2) uses binaryen 26.

**Comment by rahulchaphalkar** [comment]
Okay. I wondered if I'm using the older binaryen version, as I'm getting errors related to this issue https://github.com/kripken/embenchen/issues/2, i.e. 
`failed to compile wasm module: CompileError: at offset 146: non-fallthrough instruction must be followed by end or else` 
I'm getting the same error when I compile the emscripten test suite with `python runner.py  benchmark` with `WASM=1` enabled.

**Comment by kripken** [comment]
Yeah, I think it is because of that. Firefox and Chrome are changing the wasm validation rules. A recent binaryen version fixed most of that (there is still some more fixing in the works).

Latest emscripten incoming should be ok (except for the other issues still in progress).

**Comment by rahulchaphalkar** [comment]
Okay, thanks! I'll give `incoming` a try.

**Comment by rahulchaphalkar** [comment]
Incoming branch installation failed with the following (clang installation failure):
```
[ 99%] Linking CXX executable ../../bin/llvm-dsymutil
[ 99%] Building CXX object tools/opt/CMakeFiles/opt.dir/NewPMDriver.cpp.o
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
tools/clang/tools/driver/CMakeFiles/clang.dir/build.make:222: recipe for target 'bin/clang-3.9' failed
make[2]: *** [bin/clang-3.9] Error 1
make[2]: *** Deleting file 'bin/clang-3.9'
CMakeFiles/Makefile2:10809: recipe for target 'tools/clang/tools/driver/CMakeFiles/clang.dir/all' failed
make[1]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object tools/opt/CMakeFiles/opt.dir/PassPrinters.cpp.o
[ 99%] Building CXX object tools/opt/CMakeFiles/opt.dir/PrintSCC.cpp.o
[ 99%] Building CXX object tools/opt/CMakeFiles/opt.dir/opt.cpp.o
[ 99%] Built target llvm-dwp
[ 99%] Linking CXX executable ../../bin/opt
[ 99%] Built target llvm-c-test
[ 99%] Built target llvm-dsymutil
[ 99%] Built target opt
[ 99%] Built target libclang
[ 99%] Built target clang-check
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Build failed due to exception!
Working directory: /home/rahulchaphalkar/emsdk_portable/clang/fastcomp/build_incoming_64
Command '['make', '-j7']' returned non-zero exit status 2
Installation failed!
```

**Comment by kripken** [comment]
`ld terminated` could be due to out of memory, perhaps?

**Comment by rahulchaphalkar** [comment]
Ah it installed when I retried. However, with the incoming branch, I'm still seeing binaryen-21 in emscripten ports folder.
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.2
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ a828c709b9ea5f74b5dd305759f6fc4cc541b3e3) (https://github.com/kripken/emscripten-fastcomp/ 048eb19b8d349cd5182599cfef9b01fab2d43846) (emscripten 1.37.2 : 1.37.2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/rahulchaphalkar/emsdk_portable/clang/fastcomp/build_incoming_64/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
rahulchaphalkar@wos-ubuntu:~/emsdk_portable/emscripten/incoming/tests$ ls ~/.emscripten_ports/binaryen/
binaryen-version_21  tag.txt
```

**Comment by kripken** [comment]
You may need to build a file using it, it will then rebuild it (should use 26, see version in `tools/ports/binaryen.py`).

**Comment by rahulchaphalkar** [comment]
Closing, its resolved, thanks for help
