### ISSUE TITLE
Safari web worker shows incorrect steady_clock values

### ISSUE THREAD

**Issue by isaacl** [emscripten-core/emscripten#4929]
steady_clock prints incorrect values in safari.  chrono::system_clock does not have this issue.

Safari (wrong)
```
Main: elapsed 1
Worker: elapsed -71000
```

Chrome / Firefox:
```
Main: elapsed 4
Worker: elapsed 4
```

---**Code Below**---

```
$ cat simpleEm.cpp

#include <chrono>
#include <iostream>
#include <stdio.h>

typedef std::chrono::milliseconds::rep TimePoint;

inline TimePoint now() {
  return std::chrono::duration_cast<std::chrono::milliseconds>
        (std::chrono::steady_clock::now().time_since_epoch()).count();
}

int main() {
  TimePoint start = now();
  std::cout << "elapsed " << now() - start << "\n";
  return 0;
}
``` 

```
$ cat pre.js

var Module = {
  print: function(e) { postMessage(e); }
};

```

```
$ cat index.html

<head>
    <script>
      postMessage = function(msg) {
          console.log("Main: " + msg);
      }
    </script>
    <script src="a.out.js"></script>
    <script>
        var worker = new Worker('a.out.js');

        worker.addEventListener('message', function(e) {
              console.log("Worker: " + e.data);
          }, false);

        worker.postMessage('');
      </script>
</head>
```

build with: `em++ -std=c++11 --pre-js pre.js -O3 simpleEm.cpp`

emscripten 1.37.1
OS X 10.11.6
Safari 9.1.3

**Comment by kripken** [comment]
Hmm, this could be a safari bug? I don't have a mac to test, but that's what I'd guess. Might be best to reduce this to a small testcase using the relevant APIs and file a bug for WebKit.

**Comment by isaacl** [comment]
> Hmm, this could be a safari bug?

Possibly. But `chrono::system_clock` works fine. So I suspect `emscripten_get_now_is_monotonic()` is returning false.

**Comment by gauravdewan007** [comment]
High resolution clock(Performance.now) is not supported in Safari and Edge WebWorker. See the thread:
https://groups.google.com/forum/#!msg/emscripten-discuss/6sKiD-EyMxQ/CiHMqLBZAgAJ
There is simple polyfill work-around.

**Comment by isaacl** [comment]
Is this an emscripten bug? (using the wrong time source)
