### ISSUE TITLE
ftello/fseeko define behavior doesn't match glibc

### ISSUE THREAD

**Issue by tdaede** [emscripten-core/emscripten#4932]
From the man page http://man7.org/linux/man-pages/man3/ftello.3.html

       fseeko(), ftello():
           _FILE_OFFSET_BITS == 64 || _POSIX_C_SOURCE >= 200112L
           (defining the obsolete _LARGEFILE_SOURCE macro also works)

However, in
https://github.com/kripken/emscripten/blob/master/system/include/libc/stdio.h#L136
they are only defined for _POSIX_C_SOURCE. This currently affects compilation of libaom.

**Comment by kripken** [comment]
I don't know enough about libc defines and standards to know if we should be defining `_POSIX_C_SOURCE`. I'd guess though that there is a reason we haven't defined it so far. @juj, perhaps you have an idea?

**Comment by tdaede** [comment]
You don't need to define _POSIX_C_SOURCE, just ftello and fseeko need to be broken out into their own section in stdio.h that is additionally guarded by || _FILE_OFFSET_BITS. I can open a PR if you like.

**Comment by kripken** [comment]
Oh, in that case, sounds like this is a bug in upstream musl? (We use the musl headers almost entirely unchanged, and I don't see any changes in that file.)
