### ISSUE TITLE
Huge heap allocations when using 'auto' keyword

### ISSUE THREAD

**Issue by PentagramPro** [emscripten-core/emscripten#4940]
Our application compiled with emscripten crashes trying to allocate 1GB of heap memory. Investigation shows that the reason is in this line of code:
`auto rewardInfo = mDailyLoginEvent->GetRewardLevel(mRewardIndex);`
GetRewardLevel returns const reference to a structure. If I replace this line with the next one:
`const CDailyLoginEvent::SRewardLevel& rewardInfo = mDailyLoginEvent->GetRewardLevel(mRewardIndex);`
everything works fine. 

In attached zip you can find:
- Sources of function that contains problematic call
- Two files containing fragments of asm.js, one for working and one for crashing case
[test2.zip](https://github.com/kripken/emscripten/files/770988/test2.zip)

What additional information do you need to look into this issue?

**Comment by crazyjul** [comment]
Hi Maxim,

```auto``` does not take a reference automatically. In this case, it will
take a copy of your structure.

I believe, to match your working code, you need to write ``` auto &
refwardInfo = ... ```

**Comment by crazyjul** [comment]
Hi Maxim,

`auto` does not take a reference automatically. In this case, it will
take a copy of your structure.

I believe, to match your working code, you need to write `auto &refwardInfo = ...`
