### ISSUE TITLE
What's the character encoding of path in MEMFS ?

### ISSUE THREAD

**Issue by xiyanggudao** [emscripten-core/emscripten#4951]
I am working on a project transplant, from desktop (C++) to web(Javascript). The path of filesystem is std::wstring type, and should transform to std::string type with UTF-8, because the standard c++ dosen't support wchar_t path. When the path only contains English, the program work. But if the path contains other character such as Chinese or Japanese, the opendir function broke. What is the reason, the right character encoding is not UTF-8 or the filesystem only support English path?

**Comment by xiyanggudao** [comment]
https://github.com/kripken/emscripten/issues/3584. It says the problem has solved, maybe I need to update emscripten (now I use emscripten 1.35.0)

**Comment by xiyanggudao** [comment]
#3584. It says the problem has solved, maybe I need to update emscripten (now I use emscripten 1.35.0)

**Comment by xiyanggudao** [comment]
I found that "Getting Started » Download and install" in the emscripten docs still use version 1.35.0, http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html. Will it update in the near future？

**Comment by kripken** [comment]
I think @juj will have an update soon. @juj?

**Comment by xiyanggudao** [comment]
I upgrade emscripten to 1.37.0, but the problem still exist. I debug this problem and found that the returned value of readdir is not correct sometimes. When the file name in the directory contains character which is more than one byte, the d_name in struct dirent is cut off. The particular example code is:
#include <dirent.h>
#include <unistd.h>
#include <sys/stat.h>
#include <string>
#include <fstream>
#include <iostream>

int main ()
{
    std::string dirName="test/";
    mkdir(dirName.data(), 0777);
    std::string u8s="目"; // a charater contains 3 bytes
    std::ofstream ofs(dirName+u8s);
    ofs.close();

    DIR *dirData = opendir(dirName.data());
    struct dirent *ptr;
    if((ptr = readdir(dirData)))
    {
        std::cout<<u8s.size()<<std::endl; // output 3
        std::string filePath=dirName+u8s;
        std::cout<<(access(filePath.data(), F_OK) == 0?"exist":"not exist")<<std::endl; //output exist

        std::cout<<strlen(ptr->d_name)<<std::endl; // output 1, surprise, should be 3
        filePath=dirName+ptr->d_name;
        std::cout<<(access(filePath.data(), F_OK) == 0?"exist":"not exist")<<std::endl; // output not exist, surprise !
    }
    closedir(dirData);
    return 0;
}
I want to find the reason and figure out this problem. But I do not kown where is the implement of readdir. I find an readdir function in library_memfs.js, but it seems not. Where is the real implement of readdir function in dirent.h ?
Thanks.

**Comment by xiyanggudao** [comment]
Finally I found it. The detail of this problem is bellow:
version: 1.37.0
branch: master
source file: library_syscall.js
function: __syscall220
line: 993

the code line is: 
{{{ makeSetValue('dirp + pos', C_STRUCTS.dirent.d_name + ' + i', 'name.charCodeAt(i)', 'i8') }}};

The default charactor encoding of clang is UTF-8, but the default charactor encoding of javascript is UCS-2(UTF-16). So assign a char variable from UTF-16, it is cut off when charCode exceeds [-128, 127].
Will emscripten repair this ?
Thanks.
