### ISSUE TITLE
Unreal Engine

### ISSUE THREAD

**Issue by clp3777** [emscripten-core/emscripten#4963]
I am getting a LOT of issues with trying to compile HTML5 from Unreal.  All of the errors I get from my build stem from directory path issues with Emscripten and LLVM and CMAKE and Closure etc... I am using UE4 4.14... I will try and post logs soon... but there seems to be a huge disconnect with UE4, the HTML5 compilers...

Since this repo and LLVM seems to be the core tech UE4 is using to compile C++ to Javascript Is there anyway better docs that we could look through to set up our environment?  I have tried reading through various comments in your config files, but nothing is commented with the common layperson in mind... it's like all of the comments are shorthand and techy lingo that are geared to experienced developers and make assumptions that the client is someone that can easily traverse directories and os environment paths...

Most of us are designers first... and developers second and that only out of necessity... can you please please please head over to the UE4 forums and start looking through the posts regarding HTML5 compiling and packaging... we need your help to get this up and running.  The thread admins over there don't really have a clue and close threads without resolution... blaming the issues on third party plugins from the marketplace.  While that may be part of the issue... I know from trying to compile my project that the Emscripen and LLVM files are outdated and many of the config files point to misplaced directories for modules ... again, I'll get some examples to recreate soon...

**Comment by clp3777** [comment]
By the way, I have tried updating emsdk using the cmd prompt provided and this is what I get...

Setting environment variables:
EM_CONFIG = C:\Users\Casey\.emscripten


C:\Program Files\Emscripten>./emsdk update
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Emscripten>

**Comment by juj** [comment]
The UE4 master repository does not yet carry the latest set of updates that are needed to build with latest Emscripten. I cannot say for certain, but I believe UE 4.16 release later this year will have the needed fixes. UE 4.15 was released very recently and unfortunately just barely missed the deadline to get those fixes in.

We are actively working with Epic to ensure that UE4 builds fine, but there's a waterfall for the workflow to get the patches landed to the main tree that we provide. I'll ping some of the Epic devs in house to get feedback from them about when the changes might be in. I presume you are working off of the UE4 GitHub master repo and built it manually?

**Comment by juj** [comment]
On Linux and OS X, the forward slash `/` is used as the path delimiter character. On Windows, it is instead the backslash character `\`.

On Linux one needs to prepend commands with `./` when invoking scripts in the current working directory, so on Linux and OS X, one types `./emsdk`. On Windows this is not needed, but there is no harm to do so though. So on Windows one can type either `.\emsdk` or just `emsdk`.

**Comment by clp3777** [comment]
Thank you for the fast response!  I attempted to go that route, but as you can probably tell... I am at best a novice when it comes to setting up environments and putting packages together.  Github repos are a bit greek to me.

I have just uninstalled 4.14 and installed 4.15 to run some tests... I also just found docs for an OLD 4.9 html setup guide that walks through setting up emscripten better than I have found in other places.  I now have Emscripten 1.35 installed, activated, and environment paths set globally in my Windows 64 environment...

I created a new blank project in UE4 4.15, with no plugins installed, and I will test both a C++ build and a normal blank build... I will reply with those logs soon...

Thank you again!

**Comment by clp3777** [comment]
BTW, The docs I found were on the unreal wiki...

[https://wiki.unrealengine.com/Html5_-_Building_On_Windows#Overview](url)

**Comment by nickshinpho** [comment]
side note: you will need to recompile all of the 3rd party libraries when ever you use a new/different toolchain version. (your project may crash due to different run time instructions...)

you can fire off the build scripts from: Engine/Build/BatchFiles/HTML5/BuildThirdParty.bat

the python scripts are made by @juj (hi jukka!)

**Comment by clp3777** [comment]
Ok, so fresh install of UE4-4.15 and blank C++ project builds "successfully", but it is, as you have stated above, not configured correctly with missing modules/utils and incorrect deployment paths for Closure, LLVM, etc... here is a link to the build logs ...

[http://artbycasey.us/UE4-4.1.5_html5Compile_logs.txt](url)

**Comment by clp3777** [comment]
Link to the build logs for successful html5 build in Unreal-4.15..

However, the LLVM and Closure modules/utils are still missing or not in correct directories...

http://artbycasey.us/UE4-4.1.5_html5Compile_logs.txt
[UE4-4.1.5_html5Compile_logs.txt](https://github.com/kripken/emscripten/files/790634/UE4-4.1.5_html5Compile_logs.txt)

**Comment by nickshinpho** [comment]
glad to hear your build is successful.

as for the missing closure messages in the build logs, UE4 does not include emscirpten's third_party tools -- this was a business decision (legal department had kittens with them).  that said, the closure compiler is not necessary to build the game.  your game should still be able to run without it.

**Comment by clp3777** [comment]
Thanks for the replies.  I was able to get that initial build, but upon adding any sort of plugins or content, the build fails again.  There is just too much for a novice like me to try and debug given my timeline/deadline for the project I'm working on ... so I will have to hold off until the packaging compilers in UE4 work as advertised.  Hopefully 4.16 will have this nailed down :)

Thanks again guys

**Comment by nickshinpho** [comment]
we did have a bug where blueprint projects were getting automatically promoted to code projects.  this hasn't been pushed up to main yet.  you might get it to work with this:

in the file:

- **Engine/Build/Target.cs.template**

remove the chunk:

- **if (Target.Platform == UnrealTargetPlatform.HTML5) { ... }**
