### ISSUE TITLE
[WebGL] TypeError: nextFreeBufferIndex is undefined

### ISSUE THREAD

**Issue by mittorn** [emscripten-core/emscripten#4979]
issue with gl-wes-v2 renderer (used with xash3d) and full es2 emulation
https://github.com/FWGS/gl-wes-v2/blob/master/src/wes_begin.c

```
getTempVertexBuffer:function getTempVertexBuffer(sizeBytes) {
        var idx = GL.log2ceilLookup[sizeBytes];
        var ringbuffer = GL.currentContext.tempVertexBuffers1[idx];
        var nextFreeBufferIndex = GL.currentContext.tempVertexBufferCounters1[idx];
        GL.currentContext.tempVertexBufferCounters1[idx] = (GL.currentContext.tempVertexBufferCounters1[idx]+1) & (GL.numTempVertexBuffersPerSize-1);
        var vbo = ringbuffer[nextFreeBufferIndex];
        if (vbo) {
          return vbo;
        }
        var prevVBO = GLctx.getParameter(GLctx.ARRAY_BUFFER_BINDING);
        ringbuffer[nextFreeBufferIndex] = GLctx.createBuffer();
        GLctx.bindBuffer(GLctx.ARRAY_BUFFER, ringbuffer[nextFreeBufferIndex]);
        GLctx.bufferData(GLctx.ARRAY_BUFFER, 1 << idx, GLctx.DYNAMIC_DRAW);
        GLctx.bindBuffer(GLctx.ARRAY_BUFFER, prevVBO);
        return ringbuffer[nextFreeBufferIndex];
```

**Comment by mittorn** [comment]
idx is 10

**Comment by kripken** [comment]
A small standalone testcase would help here.

**Comment by mittorn** [comment]
I've got many strange things in xash3d project, but cannot reproduce it in standalone tests.
It seems that something internal was broken during engine start and even some pointer arithmethics goes wring after that.
For example:
```C
char buf[80000] = "\xFF\xFF\xFF\xFF";
...
char pbuf = buf;
...
*pbuf=1;
printf("%x\n", *(int*)pbuf)
```
prints "ff010000"
And only when engine already started in browser. Standalone tests works normally.
Maybe some sanity checks help?
Here is test demo: with broken internal network protocol
http://mittorn.the-swank.pp.ua/uplinken/

**Comment by kripken** [comment]
Sounds like you might be hitting memory corruption. These options might help: https://kripken.github.io/emscripten-site/docs/porting/Debugging.html#compiler-settings

**Comment by mittorn** [comment]
Thank you, already found it. It was unaligned access, i fixed it by forcing unaligned mode in fastcomp code.
I'll try to test opengl emulation tomorrow.
