### ISSUE TITLE
powf( -1, Infinity )

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#4980]
I've run into a problem caused by the differences between C and Javascript's `pow` function.

C has [a few edge cases](http://en.cppreference.com/w/c/numeric/math/pow):
>pow(-1, ±∞) returns 1  
>pow(+1, exponent) returns 1 for any exponent, even when exponent is NaN

But JS [instead returns NaN](http://www.ecma-international.org/ecma-262/5.1/#sec-15.8.2.13):
>If abs(x)==1 and y is +∞, the result is NaN.  
>If abs(x)==1 and y is −∞, the result is NaN.

I have tried the `PRECISE_F32` but it does not help.

If I need to I can implement my own powf function, but I've currently got a fairly clean port and would prefer not to have to hack the code too much. (Also I'm not sure how you'd go about replacing a function from libc, my C knowledge is rather limited.)

Any ideas?

**Comment by kripken** [comment]
Maybe the simplest thing is to manually include the `pow.c` file from musl (under `system/lib/libc/musl/src/math/powl.c`) among your project source files. It should then be used instead of the JS one.

**Comment by curiousdannii** [comment]
Editing my C code works, but I think this is something which should be fixed in the asm.js generator.

I was able to manually edit the asm Math_pow function to refer to a custom env function rather than global.Math.pow, and I can see in emscripten.py how that could be changed, but I think any pull request I could make would be very rough. I can try if you think I should though.

**Comment by kripken** [comment]
Yeah, good point, this is actually specified in the C spec, so we should fix it. Actually, I think we do so in wasm mode, since then we use a lot more of musl math code, as wasm doesn't have asm.js builtins like pow. So this is on the road to getting fixed already if I am not mistaken.

**Comment by dschuff** [comment]
+1 to just using musl's implementation of `pow`
