### ISSUE TITLE
Memory initialization seems to be broken in dlopened libraries

### ISSUE THREAD

**Issue by mittorn** [emscripten-core/emscripten#4981]
dopen'ed libraries has wrong values of global variables. 
I 'am always getting here:
https://github.com/FWGS/hlsdk-xash3d/blob/master/dlls/client.cpp#L802
because g_pGameRules is not NULL at start.

**Comment by kripken** [comment]
This tested in the test suite, so it should work in general. Please provide a standalone testcase if you can.

**Comment by mittorn** [comment]
Cannot reproduce it in simple test app. Maybe working with WebGL or async mode have some side effect.

**Comment by mittorn** [comment]
Tried to add module manually from JS,, getting this error:
"parentModule.__Znwj is undefined"

**Comment by mittorn** [comment]
fixed "parentModule.__Znwj is undefined" by forcing c++ libraries in main c module.

**Comment by mittorn** [comment]
Added dlopen call to first frame, seems to fix memory errors.
