### ISSUE TITLE
Release notes are outdated

### ISSUE THREAD

**Issue by sagamusix** [emscripten-core/emscripten#5010]
The release notes on http://kripken.github.io/emscripten-site/docs/introducing_emscripten/release_notes.html as well as the linked-to release notes document right here on Github is severely outdated (almost one year since the last update). There is no way to know what has been changed and improved in 1.37.x releases!

**Comment by sagamusix** [comment]
I just updated the portable SDK from an earlier emscripten version (probably updated around the time I opened this issue) to the latest, 1.37.9 and now it no longer compiles on Debian. Without a changelog, I cannot even see which requirements might have changed or what I need to do.

**Comment by kripken** [comment]
We should update those, but meanwhile, the compilation issue is likely due to LLVM/clang, so looking at their release notes for 4.0 might help. Also you can post the compilation error here, might be familiar to people.

**Comment by sagamusix** [comment]
This is the error I get:
```
CRITICAL:root:Could not verify LLVM version: argument of type 'NoneType' is not iterable
/home/saga/emsdk_portable/clang/e1.37.9_64bit/llc: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/saga/emsdk_portable/clang/e1.37.9_64bit/llc)
CRITICAL:root:fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
===========================================================================
(no targets could be identified: need more than 1 value to unpack)
===========================================================================
CRITICAL:root:you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
CRITICAL:root:failing sanity checks due to previous fastcomp failure
```
I tried using the clang source package instead of the precompiled one but sadly I'm running out of disk space when compiling Clang on the VM this is running on.

**Comment by kripken** [comment]
Looks like the binaries are built with a dependency on that glibcxx version, which it can't find on your system.

**Comment by 0joshuaolson1** [comment]
I have the same problem (I'm on Sabayon, a Gentoo-based system with no customizations and no libstdc++6). I followed the instructions [here](http://webassembly.org/getting-started/developers-guide/) to build Emscripten from source with emsdk.

**Comment by sagamusix** [comment]
Yeah, I think the only way to use it on Jessie right now is to also build Clang from source, which is sadly not possible on the VM I am using it on right now because the virtual hard disk is a bit too small. ;)

**Comment by bsokol** [comment]
Are there any important changes worth mentioning between v1.37.28 and 1.37.32 release?

I'm always looking at this changelog but there is no info about it :/
https://github.com/kripken/emscripten/blob/incoming/ChangeLog.markdown

**Comment by kripken** [comment]
We should also update the notes, though. The main thing I can think of offhand is the LLVM update, @juj please remember to add that to the Changelog.

**Comment by juj** [comment]
I'll do a pass on the ChangeLog soon, the new tags were done all this week, it was basically a LLVM 4.0 -> 4.0.1 merge that happened and created a few tags on that before and after the merges.
