### ISSUE TITLE
Non-US international keys don't work in Firefox

### ISSUE THREAD

**Issue by dreamlayers** [emscripten-core/emscripten#5022]
If I switch my keyboard layout to Croatian (HR), then `[`, `]`, `\`, `:`, and `'` keys are used to input characters which don't exist in English. These keys then don't work right in Emscripten generated code in Firefox 52.0 (32-bit) with both SDL 1 or SDL 2.

In SDL 1, key events are received, but scancode and sym are both zero. The unicode property is correct though.

In SDL 2, key events are not received for those keys.

They do work in Chrome 57.0.2987.98 (Official Build) (32-bit), and only the SDL 1 unicode property changes based on keyboard layout.

The probable cause of this issue is obvious at http://unixpapa.com/js/testkey.html . Firefox will zero out `keyCode`, `which` and `charCode` in `keydown` and `keyup` events for the keys sending non-US characters. Only the DOM 3 fields (which can be viewed if you enable the checkbox for it) show something via the `key` property, which is set to the character that should be generated by that keypress. At https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent Mozilla says that `keyCode`, `which` and `charCode` are depreciated. However, Chrome is not setting the `key` property.

BTW The Croatian layout also swaps `y` and `z` compared to the US layout. Windows native SDL 1 doesn't swap them and retains US layout names, only changing the unicode field, while Windows native SDL 2 swaps them. Both Emscripten SDL versions swap them in both Firefox and Chrome. I guess either way is fine, and the main thing is that both keys continue to work?

Here's the program I used to explore this. In Windows because output goes to stdout.txt and Cygwin's `tail -f` may not see it immediately.
```C
#include <stdio.h>
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#else
#include <stdlib.h>
#include <unistd.h>
#endif
#include <SDL.h>

#if SDL_VERSION_ATLEAST(2,0,0)
SDL_Window *window = 0;
#else
SDL_Surface *screen = 0;
#endif

/* From https://www.libsdl.org/release/SDL-1.2.15/docs/html/guideinputkeyboard.html */

/* Print modifier info */
void PrintModifiers( 
#if !SDL_VERSION_ATLEAST(2,0,0)
    SDLMod mod 
#endif
                    ){
#if SDL_VERSION_ATLEAST(2,0,0)
    SDL_Keymod mod = SDL_GetModState();
#endif

    printf( "Modifers: " );

    /* If there are none then say so and return */
    if( mod == KMOD_NONE ){
        printf( "None\n" );
        return;
    }

    /* Check for the presence of each SDLMod value */
    /* This looks messy, but there really isn't    */
    /* a clearer way.                              */
    if( mod & KMOD_NUM ) printf( "NUMLOCK " );
    if( mod & KMOD_CAPS ) printf( "CAPSLOCK " );
    if( mod & KMOD_LCTRL ) printf( "LCTRL " );
    if( mod & KMOD_RCTRL ) printf( "RCTRL " );
    if( mod & KMOD_RSHIFT ) printf( "RSHIFT " );
    if( mod & KMOD_LSHIFT ) printf( "LSHIFT " );
    if( mod & KMOD_RALT ) printf( "RALT " );
    if( mod & KMOD_LALT ) printf( "LALT " );
    if( mod & KMOD_CTRL ) printf( "CTRL " );
    if( mod & KMOD_SHIFT ) printf( "SHIFT " );
    if( mod & KMOD_ALT ) printf( "ALT " );
    printf( "\n" );
}

/* Print all information about a key event */
void PrintKeyInfo( SDL_KeyboardEvent *key ){
    /* Is it a release or a press? */
    if( key->type == SDL_KEYUP )
        printf( "Release:- " );
    else
        printf( "Press:- " );

    /* Print the hardware scancode first */
    printf( "Scancode: 0x%02X", key->keysym.scancode );
    /* Print the name of the key */
    printf( ", Sym: %i, Name: %s", key->keysym.sym, 
            SDL_GetKeyName( key->keysym.sym ) );
#if !SDL_VERSION_ATLEAST(2,0,0)
    /* We want to print the unicode info, but we need to make */
    /* sure its a press event first (remember, release events */
    /* don't have unicode info                                */
    if( key->type == SDL_KEYDOWN ){
        /* If the Unicode value is less than 0x80 then the    */
        /* unicode value can be used to get a printable       */
        /* representation of the key, using (char)unicode.    */
        printf(", Unicode: " );
        if( key->keysym.unicode < 0x80 && key->keysym.unicode > 0 ){
            printf( "%c (0x%04X)", (char)key->keysym.unicode,
                    key->keysym.unicode );
        }
        else{
            printf( "? (0x%04X)", key->keysym.unicode );
        }
    }
#endif
    printf( "\n" );
    /* Print modifier info */
    PrintModifiers(
#if !SDL_VERSION_ATLEAST(2,0,0)
    key->keysym.mod 
#endif
                   );
#ifndef __EMSCRIPTEN__
    /* Important in Windows to make output seen in stdout.txt */
    fflush(stdout);
#endif
}

static void input(void) { 
  SDL_Event event;

  while ( SDL_PollEvent(&event) > 0 ) {
    switch (event.type) {
    case SDL_KEYDOWN:
    case SDL_KEYUP:
      PrintKeyInfo(&event.key);
      break;
#ifndef __EMSCRIPTEN__
    case SDL_QUIT:
      SDL_Quit();
      exit(0);
#endif
    default:
    break;
    }
  }
}

static void mainloop() {
    input();
}

int main(int argc, char **argv) {
    SDL_Init(SDL_INIT_VIDEO);
#if SDL_VERSION_ATLEAST(2,0,0)
    window = SDL_CreateWindow(NULL, 
                              SDL_WINDOWPOS_UNDEFINED, 
                              SDL_WINDOWPOS_UNDEFINED, 
                              600, 450,
                              SDL_WINDOW_SHOWN);
#else
    screen = SDL_SetVideoMode(600, 450, 32, SDL_HWSURFACE);
    SDL_EnableUNICODE( 1 );
#endif

    printf("Press keys in the graphical window and view text output.\n");
#ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(mainloop, 0, 0);
#else
    while (1) { 
        usleep(1000);
        mainloop();
    }
#endif
    return 0;
}
```

**Comment by kripken** [comment]
Thanks for investigating. Seems like a problem area in web compat...

Sounds like the best we can do is use `key`, but fall back to the deprecated other fields when it's not present?

**Comment by mittorn** [comment]
This works for me:
https://github.com/FWGS/xash3d/blob/reconnection-fix/engine/platform/sdl/events.c

**Comment by dreamlayers** [comment]
@mittorn, I don't understand how https://github.com/FWGS/xash3d/blob/reconnection-fix/engine/platform/sdl/events.c can work for you. What I'm seeing is that `key.keysym.scancode` is zero for these keys in SDL 1, and events do not even arrive in SDL 2. So how can code based on that work? The only possible workaround would be to use SDL 1 and keysym.unicode, but that is only practical for text input.

The problem for SDL is and any application that wants to use SDLK_\* or SDL_SCANCODE_\* values is how to map characters from various international layouts to those values.  You would need to have lookup tables from characters to SDLK_\* values for many keyboard layouts.

I can also reproduce this with Firefox in Linux. It also affects keys sending Latin-1 characters with codes under 256, like é (U+00E9).
