### ISSUE TITLE
SDL 1 SDL_VIDEORESIZE has old size after resize via shell with "Resize canvas"

### ISSUE THREAD

**Issue by dreamlayers** [emscripten-core/emscripten#5051]
When the canvas is resized by the user by checking "Resize canvas" and pressing the "Fullscreen" button in the shell, the application receives an SDL_VIDEORESIZE event with old windowed canvas size. It should receive the new full screen canvas size. Then, if the user leaves full screen by pressing escape, the  SDL_VIDEORESIZE event has the full screen canvas size.

This causes the application to resize itself inappropriately, not scaling up for full screen and then displaying in full screen size in normal mode.

The problem seems to be in library_browser.js. Both setFullscreenCanvasSize() and setWindowedCanvasSize() call Browser.updateResizeListeners(). However, at that time canvas element size has not changed, and updateResizeListeners() updates listeners with the current size of the canvas element. Those functions are called within the if and else statements in fullscreenChange(), and the canvas is in both cases resized afterwards by calling Browser.updateCanvasDimensions();. 

Seems a solution could be to call Browser.updateResizeListeners() from Browser.updateCanvasDimensions() instead. That would require adding a noUpdates parameter, which can be passed by setCanvasSize() so it continues to work the same way.

Here's a small program to demonstrate this behaviour. I put in SDL 2 conditionals because I wanted to check that behaviour too, but I'm not getting resize events there. I guess SDL 2 is still affected by https://github.com/kripken/emscripten/issues/1731

```C
#include <stdio.h>
#include <SDL.h>
#include <emscripten.h>

static void mainloop(void) {
    SDL_Event e;
    while (SDL_PollEvent(&e) > 0) {
#if SDL_VERSION_ATLEAST(2,0,0)
        if (e.type == SDL_WINDOWEVENT &&
            e.window.event == SDL_WINDOWEVENT_RESIZED)
            printf("SDL 2 resized to %i x %i\n",
                   e.window.data1, e.window.data2);
#else
        if (e.type == SDL_VIDEORESIZE)
            printf("SDL 1 resized to %i x %i\n", e.resize.w, e.resize.h);
#endif
    }
}

int main() {
    SDL_Init(SDL_INIT_VIDEO);
#if SDL_VERSION_ATLEAST(2,0,0)
    {
        SDL_Window *w = 
            SDL_CreateWindow(NULL, 0, 0, 320, 200,
                             SDL_WINDOW_RESIZABLE | SDL_WINDOW_SHOWN);
        SDL_GetWindowSurface(w);
    }
#else
    SDL_SetVideoMode(320, 200, 32, SDL_RESIZABLE);
#endif
    emscripten_set_main_loop(mainloop, 0, 0);
    return 0;
}
```

**Comment by stolk** [comment]
Any progress made on this? I am still having resize issues with SDL2.
Full screen without resizing works, but if I enable the resize tickbox, then the content is just drawn in the corner of the bigger screen.

**Comment by juj** [comment]
No progress that I can recall. Though this issue refers to SDL 1, whereas you describe SDL 2 case. Perhaps https://github.com/emscripten-ports/SDL2 might have an updated version.
