### ISSUE TITLE
Entering full screen from touch event handlers does not work

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [emscripten-core/emscripten#5052]
I have noticed this in the source code:
https://github.com/kripken/emscripten/blob/6da649535161a3a1843479f2f1fd64df4579096a/src/library_html5.js#L909

Referenced Firefox bug seems to be resolved already.

It should work both on `touchstart` and `touchend` events, like this:
`allowsDeferredCalls: eventTypeString == 'touchstart' || eventTypeString == 'touchend',`

**Comment by kripken** [comment]
Good, yeah, we should verify this works after that bug was fixed - and also works in other browsers too - and then update the code assuming so.
