### ISSUE TITLE
Make getenv, setenv, putenv, clearenv, unsetenv and environ multithread-capable

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5054]
Currently the environment is local to each pthread, which is wrong. The environment should be visible in multiple threads, i.e. one thread setting an env. var should be visible in another thread when it gets the corresponding env. var. Currently each thread gets their own copy of environment variables.

Reading the [spec](http://man7.org/linux/man-pages/man3/getenv.3.html), getenv does need to be multithread safe ("MT-Safe env"), but does not need to be re-entrant, although I am not sure what exactly that means even after reading the descriptions. Looking at musl's implementation we have available, it is not MT safe at least in the sense that one thread calling `getenv()` while another is calling `setenv()` can lead to completely corrupted output, though the linux man page spec's wording above of MT safe seems to be very weak that perhaps that is not even guaranteed.

**Comment by tml1024** [comment]
Is this still intentionally WONTFIX?

**Comment by kripken** [comment]
No, it is just stale. Reopening.

**Comment by sbc100** [comment]
I believe this was fixed way back in #9525.  the environment is stored in the C heap under `__environ` these days, and is shared between threads.

**Comment by sbc100** [comment]
As to weather we should fix musl's own implementation of getenv/setenv to be thread safe... I think its probably not worth it.  If its good enough for upstream musl its probably good enough for us?

**Comment by sbc100** [comment]
Apparently these are not required to be thread safe: https://stackoverflow.com/a/50479023

```
The getenv() function need not be thread-safe.
```

and:

```
The set of environment names and the method for altering the environment list are implementation-defined. The getenv function need not avoid data races with other threads of execution that modify the environment list.
```

**Comment by sbc100** [comment]
So I think we can close this..

**Comment by kripken** [comment]
Good find, yes, it sounds like the spec doesn't require any more than we do already.

If there is an important use case that needs this we can reconsider later though.
