### ISSUE TITLE
Failed to asynchronously prepare wasm: memory import has larger maximum

### ISSUE THREAD

**Issue by PetterS** [emscripten-core/emscripten#5069]
I have compiled my wasm with the incoming branch and I have not set TOTAL_MEMORY (so the default is 16MB, I guess).

Loading my wasm works nicely in Chrome and Firefox. However, for large programs I get the familiar "Cannot enlarge memory arrays." error message. With Javascript, I fix this my adding total memory to my module:

    var Module = {
        ...
        TOTAL_MEMORY: 200 * 1024 * 1024,

But when using wasm I get the following error message:

    failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): memory import 47 has larger maximum than maximum 256, got 3200

So I cannot set Module.TOTAL_MEMORY when using wasm, even though the error message after "Cannot enlarge memory arrays." suggests that as an option.

**Comment by kripken** [comment]
Yeah, thanks, in wasm the max memory size is baked into the wasm binary. We should improve the error message there, I opened #5073
