### ISSUE TITLE
SDL Img_Load constantly fails

### ISSUE THREAD

**Issue by pbferre** [emscripten-core/emscripten#5076]
I cannot get SDL Img_Load to work no matter what I do. I tried compiling hello-image_sdl.c, using a png file that i loaded with the --preload-file switch. I also tried loading it from a file I downloaded from the web using the Fetch API. In every case, it fails with "unknown SDL-emscripten error". I have USE_SDL, USE_SDL_IMAGE and USE_LIBPNG all set to 1. If I try using SDL2 instead of SDL1, it still fails, only Img_GetError returns an empty error message, instead of just a useless one. Any idea what I am missing?

**Comment by kripken** [comment]
For SDL1 you may be missing the `--use-preload-plugins` flag. If that doesn't fix it, does the `browser.test_sdl_image` test pass on your machine?

For SDL2 I'm less sure, but see `browser.test_sdl2_image_formats` which uses a `SDL2_IMAGE_FORMATS` flag.

**Comment by pbferre** [comment]
I was able to get it to work, using image data downloaded from the web, but not with preloaded images. Set the ASYNCIFY and ALLOW_MEMORY_GROWTH switches to 1, and things seemed to work. Thanks. Incidentally, don't seem to have the browser.test_sdl_image file. Not in the incoming branch?

**Comment by kripken** [comment]
It should be there, look for `test_sdl_image` in `tests/test_browser.py`.
