### ISSUE TITLE
adding example to Embind documentation

### ISSUE THREAD

**Issue by lomateron** [emscripten-core/emscripten#5082]
In the **Using val to transliterate JavaScript to C++** section of [this](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html)
How would this translate:
`node.onaudioprocess = fillBuffer;`
when **fillBuffer** is a C++ function?
if **fillBuffer** was on javascript it would have an event parameter, how will this translate into the C++ function parameters?
also inside the C++ **fillBuffer** function I will use the javascript 
**AudioBuffer.copyToChannel(source, channelNumber, startInChannel)**, How would I set it's **source** parameter if it is a C++ float array?

**Comment by AlexPerrot** [comment]
Hi,
Can you provide a code example of what you're trying to achieve ?

**Comment by lomateron** [comment]
How this javascript code translate to C++
```
function fillBuffer(event) {
    var data = new Float32Array(256);
    for (var i = 0; i < data.length; ++i) {
        data[i] = Math.random();
    }
    event.outputBuffer.copyToChannel(data, 0, 0);
}
var sCx = new window.AudioContext();
var node = sCx.createScriptProcessor(256, 1, 1);
node.onaudioprocess = fillBuffer;
node.connect(sCx.destination);
```

**Comment by lomateron** [comment]
I have this incomplete translation
```
void fillBuffer( event ) {
	float data[256];
	for (int i = 0; i < 256; ++i) {
		data[i] = emscripten_random();
	}
	event["outputBuffer"].call<void>("copyToChannel", data, val(0), val(0));
}
int main() {
	val sCx = val::global("AudioContext").new_();
	val node = context.call<val>("createScriptProcessor",val(256), val(1), val(1));
	node.set("onaudioprocess", fillBuffer);
	node.call<void>("connect", sCx["destination"]);
}
```
how will I translate 
**event** in the line `void fillBuffer( event ) {`
**data** in the line `event["outputBuffer"].call<void>("copyToChannel", data, val(0), val(0));`
**fillBuffer** in the line `node.set("onaudioprocess", fillBuffer);`

**Comment by Sciss** [comment]
I have exactly the same question; did you find a solution? The example on the [embind documentation](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#using-val-to-transliterate-javascript-to-c) unfortunately does not cover the case of setting a property to a C++ function (in my case, it's not even a static function, but a member of a C++ class); I'm kind of lost there.

**Comment by Sciss** [comment]
Here is my attempt at the static version; same questions as OP - what's the argument type of the event, and how to set `onaudioprocess`. Please re-open issue, thanks!

```cpp
#include <emscripten/val.h>
#include <stdio.h>
#include <math.h>

using namespace emscripten;

void fillBuffer(void* ev) {
  float data[256];
  for (int i = 0; i < 256; ++i) {
    double x = (double) rand() / RAND_MAX * 2.0 - 1.0; // float in range -1 to 1
    data[i] = (float) x;
  }
  ev["outputBuffer"].call<void>("copyToChannel", data, 0, 0);
}

int main() {
  val ctx   = val::global("AudioContext").new_();
  val proc  = ctx.call<val>("createScriptProcessor", 256, 0, 1);
  proc.set("onaudioprocess", &fillBuffer);
  proc.call<void>("connect", ctx["destination"]);
  printf("All done!\n");
}
```
