### ISSUE TITLE
How update emcc version ?

### ISSUE THREAD

**Issue by kenshero** [emscripten-core/emscripten#5102]
I use emcc version 1.37.0 and try to complie webassemby and get error

in chrome
 "failed to compile wasm module: RangeError: WebAssembly.Module(): Wasm compilation exceeds internal limits in this context for the provided arguments"

in firefox 
"failed to compile wasm module: CompileError: at offset 8: binary version 0xd does not match expected version 0x1"

my friend use emcc version 1.37.5. It works complie native wasm. 

Can you help me ?

**Comment by atrosinenko** [comment]
I'm not sure if it will resolve your issue, but in case you just want to try to compile with the new version of Emscripten, for now you can install the `incoming` branch of the SDK. Please note, that at least on my system the build directory of `incoming` version of `fastcomp` is about 24Gb in size. After building, activating and setting up environment, check that versions of Emscripten and Clang match using `emcc -v`.

**Comment by finneyr** [comment]
One comment (#1) and a question (#2) ...

#1 Similar problem. I wrote a big program that works fine with Firefox 53.0.  Doens't work on chrome.
I downloaded what I *think* is the latest , greatest emsdk.

It fails with Chrome (Google Chrome 58.0.3029.81 (Official Build) (64-bit)
Revision	ac0bae59f0aa5b391517e132bf172144b1939333-refs/branch-heads/3029@{#746} )

emcc is from ( JUJ, not kripken )version is: 
emcc (Emscripten gcc/clang-like replacement) 1.37.10 (commit 1c4a5f958266e23b9bbe8ff1746e85085bcd72e9)

Error message in "console" is ...
chromatic.js:1 failed to compile wasm module: RangeError: WebAssembly.Module(): Wasm compilation exceeds internal limits in this context for the provided arguments

#2
Which is best source for emcc (juj or kripken) ..
https://github.com/juj/emsdk OR https://github.com/kripken/emscripten

**Comment by finneyr** [comment]
Follow up on "failed to compile wasm module: RangeError: WebAssembly.Module(): Wasm compilation exceeds internal limits in this context for the provided arguments" in Chrome ( but works in Firefox).
Apparently Chrome needs a little more room to get my application going.
I fixed the loading into Chrome by upping the  TOTAL_MEMORY like this :-1:  "  -s TOTAL_MEMORY=100663296 " as a parameter to emcc.
So ... anybody duckduckgo'ing for a solution to this problem ( i.e. how I found this page) might try this and see if it fixes your loading your webassembly program into Chrome.

**Comment by dschuff** [comment]
The "wasm compilation exceeds internal limits" error doesn't have anything to do with the total memory size; it's because of the use of the synchronous (`new WebAssembly.Instance(...)`) rather than asychronous (`WebAssembly.instantiate(...)`) wasm instantiation APIs. Newer versions of emscripten use the async APIs by default, and so should work on all browsers (async is the preferred style in any case to avoid blocking the main thread).
