### ISSUE TITLE
Loading extra files like the `.wasm`

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#5104]
Consider a library like ammo.js or box2d.js, where a site can have structure like this:
````
ammo.js
demos/
  demo1/
    index.html
  demo2/
    index.html
````
Both html files can have `<script src="../../ammo.js"></script>`. That way, we have one copy of ammo.js, used by multiple locations, and this just works. And likewise, if the code is run in a worker, the worker can do `importScripts("../../ammo.js");

If, on the other hand, there is an extra file like `ammo.js.mem` or `ammo.wasm`, that is loaded by `ammo.js`, then things are trickier. If `ammo.js` just loads the URL `"ammo.wasm"` then it won't find it - the current directory is `demos/demoX/`. There hasn't been a great solution to this, so to work around it we avoided such extra files, disabling the `.mem` file in particular - despite the downsides of doing so (larger code size, slower startup).

But with wasm this is unavoidable - we have to have another file.

Some options:

 * Modify the URL inside `ammo.js`, either to an absolute path like `"http://mysite.com/ammo.wasm"` or the proper relative one `"../../ammo.wasm"`. The relative path won't work if it can be called from different nesting depths, so really only the absolute one seems like an option here. But it seems bad to ask users to do this, and do it every time they move the file around...
 * Auto-detect the proper relative path. This seems possible using `document.currentScript.src`, but this is not available in a web worker. Another issue is that the code may not be in a normal script tag if it is `eval`ed (but that shouldn't be done, so maybe we can ignore it).

Maybe there's a better way to do this?

**Comment by curiousdannii** [comment]
>Auto-detect the proper relative path. This seems possible using document.currentScript.src, but this is not available in a web worker. Another issue is that the code may not be in a normal script tag if it is evaled (but that shouldn't be done, so maybe we can ignore it).

Another messy situation is when the script is loaded with require() in Electron. I'm not sure how that's implemented, perhaps even through eval(), but it's less obviously bad practice.

>Maybe there's a better way to do this?

For me, the ideal is to be able to pass in a path at my leisure. [I've done this by making a dummy XHR for memoryInitializerRequest](https://github.com/curiousdannii/hugo/blob/emglken/heglk/pre.js#L88) to delay loading, and then calling `doBrowserLoad` myself later.

What I would love is a compile setting which made it not attempt to load anything, like `Module.noInitialRun` except all encompassing, and then if there was a single function to call with a path to load the mem, asm, emterpreter data.

**Comment by drola** [comment]
In theory it is possible to embed .wasm binary data to .js file by using something like base64 encoding. There is a size and conversion tradeoff though:
```
792K	wasm_bullet.wasm
320K	wasm_bullet.wasm.gz
1,1M	wasm_bullet.wasm.base64
496K	wasm_bullet.wasm.base64.gz
```

**Comment by dschuff** [comment]
Once browsers implement the response-based embedding API (
https://github.com/WebAssembly/design/blob/master/Web.md#additional-web-embedding-api)
we will really want to use that because it will allow streaming compilation
(i.e. overlapping wasm compilation with download) and implicit caching. So
trying to go back to a world where we stuff everything into one synchronous
script isn't what we want. Obviously there are issues around asynchrony and
URLs etc, but tackling them head-on will buy us a lot of nice things. (and
we can use the same approach for memory files, dynamic libraries, and even
user files such as game assets).

**Comment by kripken** [comment]
I noticed we don't support the locateFile API for the wasm binary. That lets you customize where e.g. the mem init file is. Seems like we should do that, which helps here, but is still not great as you need to create a locateFile method.

**Comment by kripken** [comment]
@mbebenita reminds me that setting `Module.wasmBinaryFile` to a custom path works, but we should still support locateFile for full flexibility.

**Comment by buu700** [comment]
+1. It'll be easier to update my existing asm.js libraries to wasm if I don't have to implement bundling them into single js files on my own. Base64 sounds like the best solution to me, and after Brotli compression it doesn't really have enough of an impact to matter when testing with one of my libs ([ntru.js](https://github.com/cyph/ntru.js)):

```
82K	ntru.wasm
16K	ntru.wasm.br
110K	ntru.wasm.base64
25K	ntru.wasm.base64.br
```

**Comment by kkimdev** [comment]
So is this considered resolved with SINGLE_FILE and locateFile options? Or is there anything more to do?

**Comment by curiousdannii** [comment]
Lots more to do. It's far from ideal IMO. The Emterpreter data must still be manually loaded for example.
