### ISSUE TITLE
MEM_INIT_METHOD doesn't do anything if you build with -O2 or -O3

### ISSUE THREAD

**Issue by db48x** [emscripten-core/emscripten#5108]
It gets overridden in emcc.py (<https://github.com/kripken/emscripten/blob/051ef318558e96d32377f9333fb5e51ab1251249/emcc.py#L800>) whenever the build is optimized.

**Comment by erikdubbelboer** [comment]
Will this ever get fixed?

**Comment by kripken** [comment]
`--memory-init-file 0` will work, but MEM_INIT_METHOD might not - do you specifically need the latter?

In any case, though, MEM_INIT_METHOD is changing with the new SINGLE_FILE option #5296, so probably best to wait for that to land before considering any work there.

**Comment by erikdubbelboer** [comment]
I'll wait for SINGLE_FILE, that would be perfect.
