### ISSUE TITLE
1.37.9 emscripten_async_wget returns filename prepended with forward slash

### ISSUE THREAD

**Issue by shaovoon** [emscripten-core/emscripten#5119]
Just updated to 1.37.9, emscripten_async_wget returns filename prepended with forward slash. For example, /filename.jpg

My workaround for the callback is increment the char pointer by one. I cannot use preloaded files because some assets are chosen by my users before emscripten page is loaded.
 
```
emscripten_async_wget("...", "...", file_callback, error_callback);
...
void file_callback(const char * file)
{
	if(file[0] == '/')
		++file;
	gDownloadSingleton.ReceiveFile(file);
}

void error_callback(const char * file)
{
	if (file[0] == '/')
		++file;
	gDownloadSingleton.FileError(file);
}
```

**Comment by kripken** [comment]
Strange, I dont think we changed anything here, and our tests still pass.

Do you have a small complete testcase showing the issue? Or, perhaps can you bisect to find where this broke for you?

**Comment by shaovoon** [comment]
Hi, I have created a small cpp which reproduces this problem. The source code is [here](https://github.com/shaovoon/async_wget_error).
