### ISSUE TITLE
glfwGetKey() stuck key state, GLFW_PRESS persists after onblur - should clear key state on window losing focus

### ISSUE THREAD

**Issue by satoshinm** [emscripten-core/emscripten#5122]
glfwGetKey() continues to return `GLFW_PRESS` even after the user has switched to another window and released the key, causing keyboard-based controls to act as if they are "stuck".

Consequently, if a user is interacting with a game, for example by pressing WASD to move around, then they switch out of it to somewhere else, they'll keep interacting (moving, jumping, etc.) while outside of the game, and even when they switch back to it.

---

Example demo for testing:

* https://satoshinm.github.io/emglfwbugs/test_glfw_get_key_stuck/test_glfw_get_key_stuck.html
* Source: https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_glfw_get_key_stuck/test_glfw_get_key_stuck.c

This calls glfwGetKey() in a loop and reports when it changes, and also updates the canvas color (red=pressed, green=released).

Hold down the spacebar, then switch out of the browser (used Cmd-Tab) and switch back.

The key will behave as if it is stuck, until you press and release it again (canvas stays red) and logs:

```
glfwGetKey says space pressed? 0
glfwGetKey says space pressed? 1
blur
```

Proposed fix: I added `emscripten_set_blur_callback()` to demonstrate an idea how this problem could be fixed in emscripten. If it reset all input states (keyboard, mouse, anything else) when receiving the onblur event, then keys should no longer stick.

emscripten 1.37.9, same behavior on Chrome, Firefox, and Safari. The problem does not occur with native glfw 3.2.1, which lets you Cmd-Tab out of the window and glfwGetKey() stops returning pressed.

---

Workaround: the user can press and release the key to unstick it -- iff they know what key that was stuck.  Sometimes this is obvious, if they are moving left then tap and release 'A', for the classic WASD controls, and so on, but depending on the application, what key got stuck is not always apparent. Especially if modifier keys are stuck, then many normal game controls no longer function. I haven't found an application-level workaround for this yet (listen for onblur, set a global blurred=1, and replace glfwGetKey() with !blurred && glfwGetKey()? I think this would be better resolved within emscripten's glfw port, or deeper down the stack.)

**Comment by kripken** [comment]
It might be a good idea to see if SDL1/2 have the same issue. I think they used to, so we might have fixed it - if so, there might be a utility function (probably somewhere in `library_browser.js` that can help).

**Comment by satoshinm** [comment]
Yes src/library_sdl.js has this code, unpresses all keys on blur and visibilitychange, not directly applicable to glfw but same general idea:

```javascript
      function unpressAllPressedKeys() {
        // Un-press all pressed keys: TODO
        for (var code in SDL.keyboardMap) {
          SDL.events.push({
            type: 'keyup',
            keyCode: SDL.keyboardMap[code]
          });
        }
      };
...

        case 'blur':
          SDL.events.push(event);
          unpressAllPressedKeys();
          event.preventDefault();
          break;
        case 'visibilitychange':
          SDL.events.push({
            type: 'visibilitychange',
            visible: !document.hidden
          });
          unpressAllPressedKeys();
          event.preventDefault();
          break;
```
