### ISSUE TITLE
Runtime.addFunction incorrectly passes 0 on its argument

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5130]
~~I need to pass three arguments on JS callback but Runtime.addFunction always gives zero on the third argument. Is there a limit relevant to this?~~

```cpp
thread_local auto _callback = reinterpret_cast<uint32_t (*)(uint32_t,int64_t,uintptr_t)>(callback);
```

This gives 0 for the third argument.

```cpp
thread_local auto _callback = reinterpret_cast<uint32_t (*)(uint32_t,uintptr_t,int64_t)>(callback);
// also changed argument passing order
```

Changing order gives correct expected value. What's going on here?

**Comment by kripken** [comment]
One possible issue is that the `int64_t` will be turned into two separate 32-bit values, the low and high bits.

**Comment by SaschaNaz** [comment]
It seems `_embind_register_integer` and `integerReadValueFromPointer` have no support for 64bit integer. JS itself has no support for full 64bit but I think precision lost is better than getting 0.

**Comment by kripken** [comment]
Ir would be consistent with other stuff to return the low bits, and store the high bits where they are accessible via `Runtime.getTempRet0()`. For passing 64-bit ints, they should be split into two 32-bit ones. Not sure how feasible those are in embind though.

**Comment by SaschaNaz** [comment]
This gets slightly more serious with `-s WASM=1`.

asm.js behavior: passing four arguments (uint32_t, lower 32 bits of int64_t, higher 32 bits of int64_t, uintptr_t)

wasm behavior: passing three arguments (uint32_t, lower 32 bits of int64_t, higher 32 bits of int64_t) where the original third argument is now inaccessible.

**Comment by kripken** [comment]
That's very strange, the ABI should be the same. Must be something specific to embind going on here somehow.
