### ISSUE TITLE
Maintaining a custom Emscripten FS

### ISSUE THREAD

**Issue by jabooth** [emscripten-core/emscripten#5132]
I've begun an effort to port a full LaTeX toolchain to Node with Emscripten:
https://github.com/latexjs/latexjs

A key goal was to minimise the number of LaTeX files downloaded (typically TeX installations are 5+GB) - my solution is to write a custom Emscripten FS that emulates the behaviour of having a full TeX Live install up to the point where a file is opened - at this stage if the file is not in a local cache, it is downloaded from a server. I call this FS `THINFS`, and I have a working solution:

https://github.com/latexjs/latexjs/blob/8c2ab6b4b825a3bca045d009576c6c4b78b8a513/latexjs/pre.js#L42

I define the FS in a `pre.js` file that [passed using the `--pre-js`](https://github.com/latexjs/latexjs/blob/8c2ab6b4b825a3bca045d009576c6c4b78b8a513/latexjs/Dockerfile#L50) flag. This is all working fine, but feels rather hacky for the following reasons:

1. I would rather maintain `THINFS` in it's own module, similar to how [`library_nodefs.js`](https://github.com/kripken/emscripten/blob/master/src/library_nodefs.js) is maintained, and have my `pre.js` files be just the specific initialisations I need for each binary. This would be nice for the development of the project, and would make it easier to re-use the same custom FS with different emscripten projects.

2. I'm unclear _how_ all this is actually working. By that I mean, it seems Emscripten uses it's own custom module system (`mergeInto(LibraryManager.library, {...` and I don't fully understand what objects end up in the compiled code.  I literally copy/pasted the `library_nodefs.js` contents to get started, and hence the dependencies I need seem to just exist. For instance, I need to access `ERRNO_CODES` which is not defined anywhere in my source, yet it is just around it seems at run time. Likewise, `FS` and `PATH` are available, even if I don't define them myself. I believe this is only the case because in my project I also use `NODEFS` in `pre.js`.

My goal here is to basically write a third-party FS that is a first class Emscripten citizen, and that I can maintain separately to the core library and that I or others can include in projects. And I guess my questions are:

1. Is this possible in the current design of Emscripten?
2. How should I structure my custom FS file (e.g. how do I import dependencies) and how should I include it in my project? I saw the docs about the [`--js-library` option](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#implement-a-c-api-in-javascript), so I'm thinking this might be the way to go, but it's not clear to me if that is specific to implementing C APIs or whether it's a generic way to add custom functionality to Emscripten.

Thanks!

**Comment by kripken** [comment]
Yeah, this isn't very well documented, as you said. The best thing is to read or copy/paste from existing FSes. You may also want to just read the code in `mergeInto` to see what that boilerplate does (almost nothing, in that case - it just merges the object into the main library object, from which we pull stuff as needed).

For ERRNO_CODES, you can add a dependency on them using
````
  your_func__deps: ['$ERRNO_CODES'],
````
etc. (see examples in e.g. `library_signals.js`. Ditto for FS, PATH, etc. you can add them to the list of deps.
