### ISSUE TITLE
Add version information to linux portable archive

### ISSUE THREAD

**Issue by sanpii** [emscripten-core/emscripten#5133]
Hello,

Can you add version to linux portable archive? ie https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-1.35.0-portable.tar.gz

**Comment by jcalfee** [comment]
Agreed, wrenjs is broken probably by a release upgrade.  The build instructions refer to the portable tar gz with no version.

https://github.com/ppvk/wrenjs/issues/9

**Comment by jcalfee** [comment]
Probably a good opportunity to move to github releases..
