### ISSUE TITLE
Disassembly/decompile/debug Emscripten compiled code

### ISSUE THREAD

**Issue by alfonmga** [emscripten-core/emscripten#5140]
Hello,

I'm trying to investigate a malicious Emscripten build.
Is there any way to debug it so I can review it better and understand what the malicious code is doing?

i'm not familiar with Emscripten yet so I'm not sure if it's technically possible.

Thanks.

**Comment by kripken** [comment]
You can prettify the asm.js code, and then with proper whitespace it can be somewhat readable. And you can debug by adding prints to the console, using a browser debugger, etc. But it is still a low-level representation, just loads and stores of 'registers' and 'memory'. For real decompilation back to source, there's nothing special about emscripten, perhaps existing decompilers can be modified to work on it.
