### ISSUE TITLE
Test case of extractelement-incompatibility with Int64-related SIMD

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5164]
Here is a tiny test case (originally from #5103) of a code snippet which works with `-O0` but not when any optimization flags are passed in:

	#include <stdint.h>
	#include <emmintrin.h>

	void __attribute__((noinline)) print128_num(__m128i a)
	{
	  int64_t *b = (int64_t*)&a;
	  printf("%.16lld %.16lld\n", b[1], b[0]);
	}

	int main() {
	  print128_num(_mm_set_epi64x(-1588454185101182573, 437384867522774919));
	}

Running `emcc a.c -o a.js -msse2 -O1` gives

	  %.8.vec.extract.extract = extractelement <2 x i64> %.8.vec.extract.bc, i32 1
	  %.0.vec.extract.extract = extractelement <2 x i64> %.8.vec.extract.bc, i32 0
	LLVM ERROR: Unsupported integer vector type with numElems: 2, primitiveSize: 64!

Running `llvm-dis` on the BC file shows

	; Function Attrs: nounwind
	define void @print128_num(<4 x i32>) local_unnamed_addr #0 {
	  %.8.vec.extract.bc = bitcast <4 x i32> %0 to <2 x i64>
	  %.8.vec.extract.extract = extractelement <2 x i64> %.8.vec.extract.bc, i32 1
	  %.0.vec.extract.extract = extractelement <2 x i64> %.8.vec.extract.bc, i32 0
	  %2 = tail call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @.str, i32 0, i32 0), i64 %.8.vec.extract.extract, i64 %.0.vec.extract.extract)
	  ret void
	}

Running `llvm-dis` on the unoptimized file gives

	; Function Attrs: noinline nounwind
	define void @print128_num(<4 x i32>) #0 {
	  %2 = alloca <4 x i32>, align 16
	  %3 = alloca i64*, align 4
	  store <4 x i32> %0, <4 x i32>* %2, align 16
	  %4 = bitcast <4 x i32>* %2 to i64*
	  store i64* %4, i64** %3, align 4
	  %5 = load i64*, i64** %3, align 4
	  %6 = getelementptr inbounds i64, i64* %5, i32 1
	  %7 = load i64, i64* %6, align 8
	  %8 = load i64*, i64** %3, align 4
	  %9 = getelementptr inbounds i64, i64* %8, i32 0
	  %10 = load i64, i64* %9, align 8
	  %11 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([17 x i8], [17 x i8]* @.str, i32 0, i32 0), i64 %7, i64 %10)
	  ret void
	}

Presumably the break 64-bit stuff to 32-bit parts is unable to operate on vectors. I wonder if there might be an easy way to expand that, or disable the offending SIMD related optimization?

**Comment by kripken** [comment]
One option: ExpandStructRegs does similar things to structs and arrays, but not vectors. We could add code for vectors that have i64 values, might be as easy as adding arrays which was done recently in pieces.

Another option: The ExpandInsertExtractElement does something similar for variable indexes. It seems like we could make it operate on constant indexes, if the value size is i64, but then we'd also need to run ExpandI64 after it.

**Comment by erikdubbelboer** [comment]
Any update on this?
