### ISSUE TITLE
Sourcemap debugging doesn't work when generating a separate asm.js file

### ISSUE THREAD

**Issue by haraldreingruber** [emscripten-core/emscripten#5191]
I have had issues with sourcemap debugging (debugging level -g4) for my project, until I discovered that this is related to the flag for generating a separate asm.js file holding the cross-compiled C++ code (--separate-asm). 

As a workaround we only activated the --separate-asm flag for release builds.

**Comment by martijnthe** [comment]
Maybe related? https://github.com/kripken/emscripten/issues/5246
