### ISSUE TITLE
Add some kind of shader manipulator option to library_gl.js?

### ISSUE THREAD

**Issue by greggman** [emscripten-core/emscripten#5201]
I recently ported some GL 3.3 code. I found the easiest way to do it was to modify `library_gl.js` like this

```
getSource: function(shader, count, string, length) {

 ...

  const shaderType = GLctx.getShaderParameter(GL.shaders[shader], 0x8B4F /* GL_SHADER_TYPE */);
  const isFragmentShader shaderType  === 0x8B30 /* GL_FRAGMENT_SHADER */;
  const header = isFragmentShader 
        ? "#version 300 es\nprecision mediump float;\n" 
        : "#version 300 es\n";
  source = source.replace(/#version.*?\n/, header);

  return source;
},
```

Basically this is replacing whatever `#version` directive is in the shader to the one compatible with WebGL2 and it's adding a default precision if it's a fragment shader. I checked that it's okay for a new default precision to be specified. In other words

       precision mediump float;
       precision highp float;

is okay. Since `#version` has to be the first line it just worked.

I'm not suggesting this exact change but It seems like something along those lines would be really useful? For the programs I tried almost no other changes were needed.

Maybe using something like `-s "COARSE_GLSL_SHADER_VERSION=300 es"` and maybe `-s DEFAULT_FRAGMENT_SHADER_PERCISION=mediump` and then adjusting the code so that **if** one of those are set then the shader is changed inside `library_gl.js`.

Thoughts?

**Comment by satoshinm** [comment]
For what it's worth I've been modifying my shaders with something like this, to allow supporting both native OpenGL and WebGL:

```glsl
#ifdef GL_ES
precision mediump float;
precision mediump int;
#endif
```

Having emscripten make this change automatically (or with an option) might be useful to reduce the porting differences, but some notes about problems that could arise:

* Fragment shaders are not the only shader type requiring precision; vertex shaders also need `precision` if they use the respective numeric types
* `float` is not the only type requiring `precision`, if it is used, then `int` also needs it (any others?)
* WebGL 1.0 (most well-supported currently) [only](http://stackoverflow.com/questions/21103484/is-it-possible-to-run-version-120-shaders-with-webgl#21105201) supports `#version 100` shaders

**Comment by greggman** [comment]
My point is that *something* that lets you manipulate the shaders inside `library_gl.js` is a useful feature for porting. 

So for example `getSource` could be this

```
getSource: function(shader, count, string, length) {

 ...

  #if USER_SHADER_MOD != ""
        source = USER_SHADER_MOD(GLctx, shader, source);
  #endif 
```

Then you could supply a user function at compile time. 

The goal I'm trying to achieve is to be able to port with less manual work. The solution I presented worked for me. I didn't have to dig through the code and find all the shaders nor did I have to dig through the code and find the places shaders were compiled. All I had to do was some small manipulation at a low level. That seems like a useful general feature

**Comment by kripken** [comment]
Nice idea, I think that make sense. This could be a hook on Module, something like if `Module.shaderMod` exists then we call it as you suggested.
