### ISSUE TITLE
WebGL on web-workers failing emscripten's initialization on browsers with no WebGL support

### ISSUE THREAD

**Issue by yairlev** [emscripten-core/emscripten#5208]
Apparently when using web-workers on a browser that does not support WebGL, emscripten's runtime does not complete its [run dependencies](https://kripken.github.io/emscripten-site/docs/porting/emscripten-runtime-environment.html), hence the run() method is not being invoked. 

After researching a bit I found out the the problem is that emscripten [adds a 'gl-prefetch' run dependency](https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/proxyWorker.js#L376) regardless of whether the browser supports WebGL. On the other hand, it removes the 'gl-prefetch' dependency [only if the browser supports WebGL](https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/webGLClient.js#L308), which creates a dangling run dependency. 

This prevents us from running automated js tests on VMs that do not have OpenGL support.

**Comment by juj** [comment]
Thanks, this certainly looks like an item to fix. If instead of just returning you first do the postMessage, i.e. something like

    if (!ctx) {
        worker.postMessage({ target: 'gl', op: 'setPrefetched', parameters: {}, extensions: {}, precisions: {}, preMain: true });
        return;
    }

does that work?

**Comment by yairlev** [comment]
I think we first need to make sure that we don't call the `addRunDependency('gl-prefetch');` 
[here](https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/proxyWorker.js#L376) if there's no WebGL support.
In addition to that we should not call `WebGLClient.prefetch()` [here](https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/src/proxyClient.js#L102) if there's no WebGL support.
So we can define a global helper (e.g. isWebGLSupport) and then use it as follows:

`isWebGLSupport() && addRunDependency('gl-prefetch');`
`isWebGLSupport() && WebGLClient.prefetch();`

**Comment by yairlev** [comment]
@juj  How should we proceed? Should I create a pull request?
