### ISSUE TITLE
GLFW3 window size doesn't account for forcedAspectRatio when switching to fullscreen

### ISSUE THREAD

**Issue by basic4gl-guy** [emscripten-core/emscripten#5209]
If you set Module['forcedAspectRatio'] then later perform a Module.requestFullscreen(...) the canvas will be correctly sized taking into account the forced aspect ratio, with letterboxing applied as necessary.

However the GLFW window object will report the window size as if the window occupies the full screen including any letterbox regions. I believe reporting the active window size would be more useful here.

My suggestion is to modify "onCanvasResize" in src/library_glfw.js. After it calls Browser.setCanvasSize it could read back the actual resulting canvas size from the Browser object (which might require introducing a Browser.getCanvasSize method).

**Comment by juj** [comment]
Agreed. Any chance you'd be able to submit a PR?

**Comment by basic4gl-guy** [comment]
Would be my first ever, but sure, I'll give it a go.
