### ISSUE TITLE
in C mode, the assignment of struct variable has problem. 

### ISSUE THREAD

**Issue by justincui** [emscripten-core/emscripten#5212]
When I try to use emscripten (latest one, LLVM & emscripten are manually installed on Ubuntu 14.04 according to instructions on emscripten website.) to compile kissfft, I got a strange problem that it works with DATATYPE=float but doesn't work with DATATYPE=double. I tracked the bug and found the bug is an assignment of kiss_fft_cpx struct. Attached is the zip file containing all the source code to reproduce the problem. You may unzip the file and open the ./Build/test_float.html & ./Build/test_double.html in Firefox. You will see the problem.

[kissfft.zip](https://github.com/kripken/emscripten/files/987529/kissfft.zip)

**Comment by kripken** [comment]
I added `-s SAFE_HEAP=1` to the emcc commands here, and then the double version hits `alignment fault`. That means that the code is somehow doing an unaligned load of the double, which is undefined behavior in C/C++ and will fail on asm.js (and on some ARM platforms too).
