### ISSUE TITLE
Allow linking JS libraries just like .a

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#5221]
Would it be possible to allow JS libraries to be linked as normal objects (via `-l` and recognising `.js` extension suffix like linker already does for other extensions)?

This would help a lot, for example, to avoid teaching Rust `--js-library` specifically for Emscripten target  - https://github.com/rust-lang/rust/pull/41409 - and likely would help other tooling that can already pass objects to downstream linker via `-l`.

If not, that's fine, I can continue working to bring this as a separate gated feature to Rust, but decided to ask if this is something that can be considered changing on Emscripten side.

**Comment by kripken** [comment]
We had a PR for that, I believe. I think it was motivated by Rust in fact. I don't remember if it landed or not, but it was on the way to, so maybe we should find it and move it along.

**Comment by RReverser** [comment]
Sounds good to me if you're on board. I'll try to find it and, if not, will make my own.

**Comment by RReverser** [comment]
Found https://github.com/kripken/emscripten/pull/4816 if that's what you mean. Also found similar but older https://github.com/kripken/emscripten/pull/2809.

**Comment by kripken** [comment]
Thanks, yeah, #4816 is the one I meant. Reading it again now, I'm not sure why it was closed. @juj had a few concerns, but they weren't fully discussed, and I think they could be addressed - we could reduce the risk of confusion in a few ways, like useful debug logging etc.

In terms of next steps, maybe @juj can say if he's strongly opposed to this? If we can convince him, then that PR is a good starting point.
