### ISSUE TITLE
Clamping f32 infinity to integer returns a negative value?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5223]
Building the following file

	#include <stdio.h>
	#include <limits>

	int __attribute__((noinline)) foo()
	{
		float f = std::numeric_limits<float>::infinity();
		int i = (int)f;
		return i;
	}

	int main()
	{
		printf("%d\n", foo());
	}

with `em++ a.cpp -o a.html -s WASM=1 -g2 -s BINARYEN_TRAP_MODE='clamp'` and running, the application prints `-2147483648`. Is that intentional? I was expecting this to print `2147483647`.

**Comment by juj** [comment]
Related, it looks like

	#include <stdio.h>
	#include <limits>

	int __attribute__((noinline)) foo()
	{
		float f = std::numeric_limits<float>::quiet_NaN();
		int i = (int)f;
		return i;
	}

	int main()
	{
		printf("%d\n", foo());
	}

gives `-2147483648` as well, I wonder if there's sense to output `0` here? (Or I wonder if that would just blow up the number of instruction needed in codegen?)

**Comment by kripken** [comment]
The wasm code we emit for clamping is this:
````
 (func $f64-to-int (param $0 f64) (result i32)
  (if i32
   (f64.ne
    (get_local $0)
    (get_local $0)
   )
   (i32.const -2147483648)
   (if i32
    (f64.ge
     (get_local $0)
     (f64.const 2147483648)
    )
    (i32.const -2147483648)
    (if i32
     (f64.le
      (get_local $0)
      (f64.const -2147483649)
     )
     (i32.const -2147483648)
     (i32.trunc_s/f64
      (get_local $0)
     )
    )
   )
  )
 )
````
which indeed returns `-2147483648` if out of range or nan. As I recall, CPU people said that is what x86 does, and since this is somewhat arbitrary, we figured doing what x86 does might be good.

**Comment by juj** [comment]
Yeah, I agree no strong sense to adjust this from the current behavior, although the term 'clamp' for this mode could be a bit misleading. I suppose this can be brushed over by documentation (or I wonder if this was mentioned already and I just missed it) and that would be good.

**Comment by kripken** [comment]
Hmm, perhaps we should improve the docs. They say "clamp to something reasonable", which I thought was vague enough (leaving "reasonable" to be interpreted), but perhaps that text could be added to.
