### ISSUE TITLE
Missing C11 conditional feature macros

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#5224]
According to § 6.10.8.3 of the C11 spec, `__STDC_NO_ATOMICS__` should be defined in C11 mode when `stdatomic.h` is not available, as is the case for emscripten.

Testing is easy:

```c
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) && !defined(__STDC_NO_ATOMICS__)
#include <stdatomic.h>
#endif
```

I use variants of that snippet in several places.  I'm working around the issue with an additional ` && !defined(__EMSCRIPTEN__)`, but that's obviously sub-optimal.

You should probably also define `__STDC_NO_THREADS__` until threads.h provides a complete implementation (i.e., until `mtx_t` and `cnd_t` are implemented).

**Comment by paulshapiro** [comment]
This would be very useful for me. @kripken any idea on the level of effort on this? I may be able to help with a bit of guidance.

**Comment by kripken** [comment]
The best place to add that define is in `tools/shared.py` (around where we define `-D__EMSCRIPTEN__` etc.).

However, it seems like we could provide that header - we do have threads and atomics support, in particular pthreads works. Maybe it clang integration, though - if so, I'm not sure of the status of that.
