### ISSUE TITLE
__builtin_bitreverse8/16/64 unimplemented

### ISSUE THREAD

**Issue by nemequ** [emscripten-core/emscripten#5225]
When attempting to compile code which uses the `__builtin_bitreverse*` functions, I get 

> warning: unresolved symbol: llvm_bitreverse_i16
> warning: unresolved symbol: llvm_bitreverse_i64
> warning: unresolved symbol: llvm_bitreverse_i8

The code compiles, but errors are thrown at runtime.  Interestingly, `__builtin_bitreverse32` works fine.  Test case:

```c
#include <stdint.h>
#include <assert.h>

int main (void) {
#if __has_builtin(__builtin_bitreverse8)
  assert(__builtin_bitreverse8(UINT8_C(42)) == UINT8_C(84));
#endif
#if __has_builtin(__builtin_bitreverse16)
  assert(__builtin_bitreverse16(UINT16_C(1729)) == UINT16_C(33632));
#endif
#if __has_builtin(__builtin_bitreverse32)
  assert(__builtin_bitreverse32(UINT32_C(1729)) == UINT32_C(2204106752));
#endif
#if __has_builtin(__builtin_bitreverse64)
  assert(__builtin_bitreverse64(UINT64_C(1729)) == UINT64_C(9466566416732782592));
#endif
}
```

They should either be implemented, or __has_builtin() should return false.

**Comment by kripken** [comment]
Yes, looks like only the [32-bit one is currently implemented](https://github.com/kripken/emscripten/blob/incoming/src/library.js#L1473). Should be easy to add the rest if someone wants to, it would be similar to the existing code for 32.

**Comment by nemequ** [comment]
The project I was trying to build when I encountered with this has [a version which works for other widths](https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h#L822) which you're welcome to.  That should make a patch pretty trivial for someone with an emscripted source tree already good to go.
