### ISSUE TITLE
Microsoft Edge and USE_PTHREADS: initMainThreadBlock throws TypeError

### ISSUE THREAD

**Issue by sbalko** [emscripten-core/emscripten#5229]
I have successfully produced a build of our stack using the USE_PTHREADS option. It works fine in Firefox beta and Safari. I could not get it to work in Microsoft Edge though after enabling SharedArrayBuffer and Atomics (still behind a flag in Edge). Running our stack then throws an exception:

```
TypeError: The operation is not supported on this typed array type
at PThread.initMainThreadBlock ...
```

Not sure if this is something that can be worked around.

**Comment by kripken** [comment]
Have you filed a bug on Edge? Or maybe Chakra is the right place, not sure - if there's no obvious place, I can ask around.

**Comment by brion** [comment]
This is https://github.com/Microsoft/ChakraCore/issues/2672 -- they've fixed it upstream but it hasn't made it to public Edge builds yet afaik.
