### ISSUE TITLE
How to port python library to Javascript?

### ISSUE THREAD

**Issue by takahashi64** [emscripten-core/emscripten#5233]
I want to convert my python library to Javascript that can run in the browser. I tried the following so far without success. Is it possible to get emscripten to output a javascript file with all the functions below implemented?

```
cython --embed -a saidpythonlibrary.pyx
eemcc -isystem /Users/username/anaconda/envs/my_env/include/python2.7 saidpythonlibrary.c -o saidpythonlibrary.js
```

But eemcc complains with the following:

```
warning: unresolved symbol: PySys_SetArgv
warning: unresolved symbol: Py_Initialize
warning: unresolved symbol: PyNumber_Absolute
warning: unresolved symbol: PyList_New
warning: unresolved symbol: PyObject_IsTrue
warning: unresolved symbol: PyList_Append
warning: unresolved symbol: PyFrame_New
warning: unresolved symbol: Py_Finalize
warning: unresolved symbol: PyNumber_FloorDivide
warning: unresolved symbol: PyFloat_FromString
warning: unresolved symbol: PyUnicodeUCS2_DecodeUTF8
warning: unresolved symbol: PyObject_GetItem
warning: unresolved symbol: PyNumber_Remainder
warning: unresolved symbol: PyDict_SetItem
warning: unresolved symbol: Py_FlushLine
warning: unresolved symbol: PySequence_Tuple
warning: unresolved symbol: PyErr_Print
warning: unresolved symbol: PyObject_Size
warning: unresolved symbol: PyErr_ExceptionMatches
warning: unresolved symbol: PyObject_Call
warning: unresolved symbol: PyObject_GetIter
warning: unresolved symbol: PyNumber_Index
warning: unresolved symbol: PyString_Size
warning: unresolved symbol: PyNumber_Int
warning: unresolved symbol: PyObject_RichCompare
warning: unresolved symbol: PyInt_FromSsize_t
warning: unresolved symbol: PyDict_GetItem
warning: unresolved symbol: PyErr_Occurred
warning: unresolved symbol: PyLong_AsSsize_t
warning: unresolved symbol: PyModule_GetDict
warning: unresolved symbol: PyFloat_FromDouble
warning: unresolved symbol: PyLong_FromLong
warning: unresolved symbol: PyUnicodeUCS2_Compare
warning: unresolved symbol: PyDict_Size
warning: unresolved symbol: PyString_AsString
warning: unresolved symbol: PyNumber_InPlaceDivide
warning: unresolved symbol: PyErr_WarnEx
warning: unresolved symbol: PyNumber_InPlaceSubtract
warning: unresolved symbol: PyOS_snprintf
warning: unresolved symbol: _PyString_Join
warning: unresolved symbol: PyEval_EvalCodeEx
warning: unresolved symbol: PyNumber_InPlaceRemainder
warning: unresolved symbol: PyNumber_Subtract
warning: unresolved symbol: PyInt_AsSsize_t
warning: unresolved symbol: _PyString_Eq
warning: unresolved symbol: PyErr_Clear
warning: unresolved symbol: PyObject_SetAttrString
warning: unresolved symbol: PyLong_AsDouble
warning: unresolved symbol: PyFile_SoftSpace
warning: unresolved symbol: PyCFunction_NewEx
warning: unresolved symbol: _Py_CheckRecursiveCall
warning: unresolved symbol: PyNumber_Add
warning: unresolved symbol: PyString_FromString
warning: unresolved symbol: PyErr_SetString
warning: unresolved symbol: PyEval_EvalFrameEx
warning: unresolved symbol: PyCode_New
warning: unresolved symbol: PySys_GetObject
warning: unresolved symbol: PyErr_NormalizeException
warning: unresolved symbol: PyErr_Format
warning: unresolved symbol: PyNumber_InPlaceAdd
warning: unresolved symbol: Py_InitModule4_64
warning: unresolved symbol: PyTuple_Pack
warning: unresolved symbol: PyString_FromStringAndSize
warning: unresolved symbol: PyErr_SetObject
warning: unresolved symbol: PyNumber_InPlaceFloorDivide
warning: unresolved symbol: PyString_InternFromString
warning: unresolved symbol: PyType_IsSubtype
warning: unresolved symbol: PyTuple_New
warning: unresolved symbol: PyNumber_Multiply
warning: unresolved symbol: Py_GetVersion
warning: unresolved symbol: PyMem_Realloc
warning: unresolved symbol: PyDict_Next
warning: unresolved symbol: Py_SetProgramName
warning: unresolved symbol: PyMem_Malloc
warning: unresolved symbol: PyDict_New
warning: unresolved symbol: PyObject_GetAttr
warning: unresolved symbol: PyNumber_Divide
warning: unresolved symbol: PyNumber_Power
warning: unresolved symbol: PyFile_WriteObject
warning: unresolved symbol: PyInt_FromLong
warning: unresolved symbol: PyObject_SetItem
warning: unresolved symbol: PyLong_FromLongLong
warning: unresolved symbol: PyImport_AddModule
warning: unresolved symbol: PyErr_GivenExceptionMatches
warning: unresolved symbol: PyObject_CallFunctionObjArgs
warning: unresolved symbol: PyTraceBack_Here
warning: unresolved symbol: PyUnicodeUCS2_FromStringAndSize
warning: unresolved symbol: PyString_FromFormat
warning: unresolved symbol: PyFile_WriteString
warning: unresolved symbol: PyCFunction_Type
warning: unresolved symbol: PyExc_AssertionError
warning: unresolved symbol: PyExc_AttributeError
warning: unresolved symbol: PyExc_BaseException
warning: unresolved symbol: PyExc_Exception
warning: unresolved symbol: PyExc_ImportError
warning: unresolved symbol: PyExc_NameError
warning: unresolved symbol: PyExc_OverflowError
warning: unresolved symbol: PyExc_RuntimeError
warning: unresolved symbol: PyExc_StopIteration
warning: unresolved symbol: PyExc_SystemError
warning: unresolved symbol: PyExc_TypeError
warning: unresolved symbol: PyExc_UnboundLocalError
warning: unresolved symbol: PyExc_ValueError
warning: unresolved symbol: PyExc_ZeroDivisionError
warning: unresolved symbol: PyFloat_Type
warning: unresolved symbol: PyFunction_Type
warning: unresolved symbol: PyInt_Type
warning: unresolved symbol: PyList_Type
warning: unresolved symbol: PyLong_Type
warning: unresolved symbol: PyMethod_Type
warning: unresolved symbol: PyString_Type
warning: unresolved symbol: PyTraceBack_Type
warning: unresolved symbol: PyTuple_Type
warning: unresolved symbol: PyUnicode_Type
warning: unresolved symbol: Py_OptimizeFlag
warning: unresolved symbol: _PyThreadState_Current
warning: unresolved symbol: _Py_CheckRecursionLimit
warning: unresolved symbol: _Py_NoneStruct
warning: unresolved symbol: _Py_TrueStruct
warning: unresolved symbol: _Py_ZeroStruct
```
These functions are missing in the c input, and in the JS output, they exist as unimplemented stub functions e.g.
```

 function _Py_SetProgramName() {
  Module['printErr']('missing function: Py_SetProgramName'); abort(-1);
  }
```
As expected, when I try run the JS via node, it errors out with:

```
missing function: Py_SetProgramName
-1
-1
exception thrown: abort(-1) at Error
    at jsStackTrace (/Users/username/code/saidpythonlibrary/saidpythonlibrary/saidpythonlibrary.js:1121:13)
    at stackTrace (/Users/username/code/saidpythonlibrary/saidpythonlibrary/saidpythonlibrary.js:1138:12)
    at abort (/Users/username/code/saidpythonlibrary/saidpythonlibrary/saidpythonlibrary.js:80725:44)
    at _Py_SetProgramName (/Users/username/code/saidpythonlibrary/saidpythonlibrary/saidpythonlibrary.js:2022:62)
    at _main (/Users/username/code/saidpythonlibrary/saidpythonlibrary/saidpythonlibrary.js:6736:3)
    at Object.asm._main (/Users/username/code/saidpythonlibrary/saidpythonlibrary/saidpythonlibrary.js:80371:19)
```

I'm using the Portable Emscripten SDK on OSX with Anaconda.

**Comment by kripken** [comment]
emcc [doesn't link with system libraries](https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries), so you need to build python and include it as an input to emcc. The test suite has python there, so you can see how that's done there if you run into any issues.

**Comment by takahashi64** [comment]
I got a bit further this time thanks to your help @kripken  :) 

Compiling the JS seemed to go fine (I think the stub functions were correctly pruned this time).
`emcc: warning: cannot represent a NaN literal '0x7fdd221e3410' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %22 = select i1 %21, double 0xFFF8000000000000, double 0x7FF8000000000000 in _Py_parse_inf_or_nan()
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
warning: unresolved symbol: posix_spawn_file_actions_init
warning: unresolved symbol: endgrent
warning: unresolved symbol: setgrent
warning: unresolved symbol: pthread_setcancelstate
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: pthread_sigmask
warning: unresolved symbol: __wait
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: getgrent
`

But when I run the resulting JS file via node, or open the generated html file via Chrome:
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Calling stub instead of sigaction()
Calling stub instead of sigaction()
Calling stub instead of sigaction()
Calling stub instead of sigaction()
ImportError: No module named site
Calling stub instead of sigaction()
```

Cheers

**Comment by takahashi64** [comment]
I think this might be because I'm using the `python.so` straight out of the emscripten test suite, and I should actually rebuild it

**Comment by kripken** [comment]
The warnings can be ignored, and the sigaction stuff also (assuming you don't try to use signals). The import error is python saying it can't find that module. You need to either build it in with python (there is a way to do "builtin" modules, I vaguely remember), or if it's a pure python module, you can add it to the filesystem where python will look for it.

**Comment by takahashi64** [comment]
@kripken I thought I'd try something that possibly won't work, so please assume you only got my first comment/post in this thread, plus this one, while reading this.

I realised that if I do `emcc python.bc -o python.js`, the resulting JS file has all the said missing functions - do you think it's possible to "transplant" these into saidpythonlibrary.js? I tried appending everything from python.js between `// EMSCRIPTEN_START_FUNCS` and `// EMSCRIPTEN_END_FUNCS` into saidpythonlibrary.js, but I think the procedure might be more involved (got some fatal errors) - like I would still need to update the `FUNCTION_TABLE_XXX` variables. Do you think this is pure madness? Or am I a few more hacks away from getting this to work? 

But ideally I'd like some automated way to combined `python.bc` and ` saidpythonlibrary.c` - do you have any ideas? Cheers.

**Comment by takahashi64** [comment]
> But ideally I'd like some automated way to combined python.bc and `saidpythonlibrary.c` 
Managed to do just that with:
`llvm-link -only-needed saidpythonlibrary.bc python.bc -o saidpythonlibrarywith_python.bc`
And then compiled saidpythonlibrarywith_python.bc with emscripten.

But got this error again:
`ImportError: No module named site`

I don't think any of the code I wrote in `saidpythonlibrary` uses the `site` module though. Do you have any tips for getting the `site` module into `python.bc`?

**Comment by kripken** [comment]
Those are python details I don't know much about, but as I said earlier, I remember that C++ python modules can be "built in" so they are part of the binary, and pure python ones can just be added as python files in the filesystem. So I would first find out which type that module is. Or, maybe you can look at the stack trace and figure out what is using that module (but i'm not sure python stack traces are useful for that or not).

**Comment by takahashi64** [comment]
I got a bit further. Fortunately the built-in modules were all python files to I just added them to the file system. Problem number 1 solved.

Now I am trying to get my Python.js to run a python file called main.py (which has been added to the FS) to import the python module I wrote using [this approach](https://github.com/kripken/emscripten/wiki/Linking#dlopen-dynamic-linking). 

main.py:
```
import my_custom_module
print "hello world!" 
for i in dir(my_custom_module): 
    print i
print dir(my_custom_module)
print dir()
print my_custom_module
dir(my_custom_module)
print "goodbye" 
```

output:
```
hello world!
__doc__
__file__
__name__
__package__
['__doc__', '__file__', '__name__', '__package__']
['__builtins__', '__doc__', '__file__', '__name__', '__package__', 'i', 'occulta']
<module 'my_custom_module' from '/assets/my_custom_module.so'>
goodbye
```
The problem is that the functions I wrote for my python module are not listed in the output above.

**Comment by takahashi64** [comment]
I got a bit further. Fortunately the built-in modules were all python files to I just added them to the file system. Problem number 1 solved.

Now I am trying to get my Python.js to run a python file called main.py (which has been added to the FS) to import the python module I wrote using [this approach](https://github.com/kripken/emscripten/wiki/Linking#dlopen-dynamic-linking). 

main.py:
```
import my_custom_module
print "hello world!" 
for i in dir(my_custom_module): 
    print i
print dir(my_custom_module)
print dir()
print my_custom_module
dir(my_custom_module)
print "goodbye" 
```

output:
```
hello world!
__doc__
__file__
__name__
__package__
['__doc__', '__file__', '__name__', '__package__']
['__builtins__', '__doc__', '__file__', '__name__', '__package__', 'i', 'my_custom_module']
<module 'my_custom_module' from '/assets/my_custom_module.so'>
goodbye
```
The problem is that the functions I wrote for my python module are not listed in the output above.

**Comment by takahashi64** [comment]
@kripken sorry I know I've been bugging you quite a bit, but I await any feedback at your earliest convenience, thanks!

**Comment by kripken** [comment]
Sorry, as I said, this gets into Python details I am not familiar with. The Python community might be a better place to ask.
