### ISSUE TITLE
Browser is included for non-browser lib with `-Oz` flag

### ISSUE THREAD

**Issue by whitecolor** [emscripten-core/emscripten#5254]
In the built result I have browser functions like (`audioPlugin_handle`) etc, though my C lib code doesn't have any relation to browser/web.

I use max level of optimization `-Oz`. Something I missed?

**Comment by kripken** [comment]
I don't see `audioPlugin_handle` when I build a simple hello world with `-Oz`, so something in your project or build command must be pulling it in. Perhaps files are preloaded, I think that could cause it?

**Comment by whitecolor** [comment]
First, I use enscripten for Windows.
```
emcc (Emscripten gcc/clang-like replacement) 1.35.0 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This is gist that contains input file (hello wold), build command, and output file.
https://gist.github.com/whitecolor/7ab57b2e39d1529a795b1b3e382dc88b

You may check that `audioPlugin_handle` is there.

**Comment by kripken** [comment]
It's possible this was fixed since 1.35.0, building your file with your command on 1.37.13 does not have that extra code.

**Comment by whitecolor** [comment]
Is it possible to try it on windows?

**Comment by kripken** [comment]
If installing the latest version using the sdk doesn't work for you on windows, I would open a new bug on that with the details.

**Comment by whitecolor** [comment]
On download page it is the latest `emsdk-1.35.0-web-64bit.exe` and it doesn't work, should I open an issue?

**Comment by kripken** [comment]
I think these commands should get the latest http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#updating-the-sdk

**Comment by whitecolor** [comment]
@kripken it seems to work fine, thanks!
Btw there is a problem with location of memory file: https://github.com/kripken/emscripten/issues/2542 it exists for me.
