### ISSUE TITLE
export Module even if ENVIRONMENT_IS_NODE is false

### ISSUE THREAD

**Issue by whitecolor** [emscripten-core/emscripten#5255]
Currenlty Module is exported:
```js
if (typeof module !== "undefined") {
  module["exports"] = Module;
}
```
 only if `ENVIRONMENT_IS_NODE` is `true`.

But it doesn't when module is run in browser by bundlers like I checked with ([fuse-box](https://github.com/fuse-box/fuse-box)), didn't check webpack/browserfy yet, but pretty sure it will fail due to this too.

Think `module["exports"] = Module;` without checking the env.

**Comment by kripken** [comment]
I think you're right, we just did something similar for `MODULARIZE` mode in #5239. Something similar to the code there (check if `module` exists, and if so, export on it) seems reasonable.

**Comment by whitecolor** [comment]
I tried MODULARIZE but it didn't work for me at all, it can not be required by node.
