### ISSUE TITLE
Javascript with MAIN_MODULE=2 becomes very big

### ISSUE THREAD

**Issue by ehaufler** [emscripten-core/emscripten#5256]
We are trying to port our C++/ opengl based library for diagrams to webgl via Emscripten.
This works great, when the whole source is ported into one module. The only drawback is the javascript size. 9.5 MB must be loaded in one block. And this is already the optimized minified release-build.
So I tried to split the library with the 'dynamic linking' ability of Emscripten. 

But when I extract e.g. a MainModule (7.5 MB) and  compile with "-s MAIN_MODULE=2  -O3"  the size increases to over 13 MB. 
So there is no benefit in splitting off a 2 MB module anymore...

Is this normal for the dynamic linking, or do I miss some other switches or other possibilities, that would reduce the size again? 

I read several threads here, were splitting of javascript files is desired for easier debugging. 
But for us, the use case is the normal usage of the library in the release (minified) build: 
A webpage starts with basic diagrams, and only loads the MainModule. When a polar diagram is needed, this module could be loaded in addition, and when 3D charts are necessary, the 3D module is loaded etc.

Could dynamic linking be a reasonable approach for that? 
I also saw the ideas to simply split the javascript files, 
like in https://groups.google.com/forum/#!topic/emscripten-discuss/R9mwSGgtRm4 ,  but anything like that is  not included int he current Emscripten version, or am I wrong here 
(I currently use 1.37.9) ?

Thanks very much for any answers/comments
Eckart

**Comment by kripken** [comment]
There was some recent discussion on this here: https://groups.google.com/forum/#!topic/emscripten-discuss/DSn54oTwZqc

Overall, separate modules are somewhat larger (they add relocation offsets etc.), and also there are the dead code elimination issues mentioned in that link (that hopefully we can improve). So currently, splitting into modules might not help you with total code size. It's probably mainly useful now for faster iteration times when compiling.

For your specific use case, it sounds like the main program wants to load small additional code modules and call them, and maybe those modules don't need to be able to call into the main program? If so, then in principle we should be able to not increase code size much for the main program - we'd just need the loading code for the side modules, but not code to make the main module code available to be called. I'm not sure though how much work that would take, someone would need to investigate it.

**Comment by ehaufler** [comment]
Hi, thanks very much for the quick reply!
I hadn't found this forum discussion. Interesting point, that EXPORT_ALL will explain, why the MAIN_MODULE becomes so big.

In my case, the main module would indeed contain some base classes for c++ classes in the SIDE module. So some well defined export would be necessary; I don't know, what minimal size of the MAIN_MODULE would result. 

The approach to simply split the big module in parts, similar to the way in this other discussion
 in https://groups.google.com/forum/#!topic/emscripten-discuss/R9mwSGgtRm4
sounded like it would not increase the modules significantly. 
The idea could be to compile all modules in one step, without the necessary big tables for exports, but only put the resulting source in separate javascript files according to some criterion, like the cpp-file list for a static-library, and adding this sort of 'forward declarations' to the main module.
I don't know the emscripten process in detail, how much effort this would be, but could this result in a reasonable solution?

thanks very much, regards
Eckart

**Comment by kripken** [comment]
Perhaps another option might be to split **after** compiling it all together. So the dev would build everything as one huge build, then would have a tool to split off pieces. I'm not sure how practical that would be, but it might be worth experimenting with.

**Comment by kripken** [comment]
Btw, experimentation with that could be a lot simpler in wasm (using binaryen) than asm.js.

**Comment by ehaufler** [comment]
>> Perhaps another option might be to split **after** compiling 
Yes I think, this should 'theoretically' work. No extra source would be generated, but the resulting js sorted to different files according to some mapping of the generated functions to source - file names or class-names. 

The wasm output is in my case already 2 times smaller and 2 times faster (in Chrome), which is great. But not yet supported natively in Internet Explorer (11), and thereby slower, so I can't rely on that.
