### ISSUE TITLE
Compile C++ Library like DLIB ?

### ISSUE THREAD

**Issue by farazirfan47** [emscripten-core/emscripten#5260]
I can compile simple c++ programs via emcripten but not understanding how to compile c++ library into JS code and use it at client-side ? What should be the step to do it ?

**Comment by sourabh2k15** [comment]
You need to run : 
emconfigure ./configure 
emmake make 

To compile the object ( .a or .so file ) , then you can run 

emcc lib.a -o lib.js 
or 
emcc lib.so -o lib.js . 

Just out of curiosity which lib are you trying to compile ? I am trying to compile Htslib , which has zlib dependency so I compiled zlib too using the above process, now need help figuring out how to use the compiled zlib object in compiling htslib

**Comment by Becavalier** [comment]
It seems that `emconfigure ` and `emmake ` are not working well for some projects.

**Comment by sourabh2k15** [comment]
The more important question is, these tools do work after some efforts, but the output given by the JS functions are numbers regardless of whether the C function returned pointers, structs or anything. So are these pointers we need to dereference somehow ? if so please guide me in doing so .

**Comment by farazirfan47** [comment]
@sourabh2k15  I want to compile dlib see the detail about it from here http://dlib.net/ but I am still no successful because I am doing it on windows and got errors. Did you successfully compiled your libraries ?

**Comment by sourabh2k15** [comment]
Yes I did . Though I had to try all crazy permutations. So ideally in theory including the binary files in emcc should work , but in my case I had to include all C file paths , binary paths . It compiled and gave the javascript only in that way.
