### ISSUE TITLE
Add documentation for FS.filesystems

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5265]
Currently postamble.js has `{{{ maybeExport('FS') }}}` but not `{{{ maybeExport('NODEFS') }}}`, so I cannot do `
instance.FS.mount(instance.NODEFS, { root: '.' }, '/working')` [as documented](http://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html#FS.mount).

Alternatively we can allow users to use string so that `FS.mount("nodefs")` can be done without NODEFS exposure.

**Comment by SaschaNaz** [comment]
It seems FS.filesystems.NODEFS can be used instead. Couldn't find this in the documentation.

**Comment by kripken** [comment]
Thanks, yeah, we should document that if it isn't already.

**Comment by juj** [comment]
Tests do call `FS.mount(NODEFS, ...` e.g. [here](https://github.com/kripken/emscripten/blob/master/tests/fs/test_nodefs_rw.c#L21) so the documented form is currently being tested to be functional. Is the issue in conjunction with `-s MODULARIZE=1` or when not using `EM_ASM` or `--js-library` blocks?

I think the cleanest would be to add `{{{ maybeExport('NODEFS') }}}` to postamble.js to support those if that works?

**Comment by saschanaz** [comment]
>Is the issue in conjunction with -s MODULARIZE=1

Yes. (Sorry for too late response)
