### ISSUE TITLE
.asm.js file emitted with `-s WASM=1` is not minified at all

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5271]
Compiling with `-s WASM=1 -s BINARYEN_METHOD='native-wasm,asmjs'` emits asm.js file with no minification even with `-O2`. It should be minified somehow.

**Comment by kripken** [comment]
This hasn't been a priority since such a build is a [compromise build anyhow](https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects), so it's not fully optimized. It's useful mainly for debugging.

**Comment by SaschaNaz** [comment]
I want to use it as an automatic fallback on earlier browsers (including MSEdge 15 😅). My makefile already has been generating a compromise build because of `-s ALLOW_MEMORY_GROWTH=1` so I don't bother with it.

**Comment by kripken** [comment]
I see. Seems reasonable to do this I guess.

We should probably show a warning at compile time though, in addition to the documentation, about the downsides of compromise builds.
