### ISSUE TITLE
*__postset should be inserted after *__deps were resolved

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#5283]
I hoped I understand the way Emscripten libraries work by now, but just runned into something that looks like a bug:

```js
mergeInto(LibraryManager.library, {
    $a: void 0,
    $a__postset: 'a = 10',

    $b: void 0,
    $b__postset: 'b = a',
    $b__deps: ['$a'],

    get_b: function () {
        return b;
    },
    get_b__deps: ['$b']
});
```

should have all the information for the correct ordering of dependencies.

However, when linking against a sample like

```c
#include <stdio.h>

int get_b();

int main() {
    printf("%d\n", get_b());
    return 0;
}
```

I see `0` in the output.

The reason for this is in the generated output:

```js
  var a=undefined;var b=undefined;function _get_b() {
          return b;
      }

...

b = a;
a = 10;
```

As you can see, `$b__postset` was inserted earlier than `$a__postset` despite `$b` having an explicit dependency on `$a`.

**Comment by RReverser** [comment]
From the `finalCombiner` looks like it is supposed to use dependencies to order post-sets, so feeling even more confident that this is some nasty bug now.

**Comment by RReverser** [comment]
Although it is called *after* they're already printed, hmm.

```js
var generated = itemsDict.functionStub.concat(itemsDict.GlobalVariablePostSet);
generated.forEach(function(item) { print(indentify(item.JS || '', 2)); });
```

**Comment by RReverser** [comment]
```
        itemsDict.GlobalVariablePostSet.push({
          intertype: 'GlobalVariablePostSet',
          JS: postset + ';'
        });
```

is this supposed to add `ident` and `deps` so that `finalCombiner` could order them?

**Comment by kripken** [comment]
Hmm, yeah, this does look like a bug. Perhaps the order of postset emitting should just be reversed: we know thanks to dependencies that `a` is processed first. So that should emit the postset into a first-in-first-out data structure, and I am guessing right now it is the reverse?

**Comment by RReverser** [comment]
Right now it seems to just add stuff to postset as it traverses dependencies, meaning:

 - entered `get_b`
 - entering `b` as a dependency
 - saw `b__postset`, added to `GlobalVariablePostSet`
 - entering `a` as a dependency
 - saw `a__postset`, added to `GlobalVariablePostSet`

So yeah, reversing should fix this particular case but I don't know if that's a correct generic solution. Also, as I said, it seems weird that `finalCombiner` already has logic for correct reordering of `GlobalVariablePostSet` that have `ident` and `dependencies` set, but such properties are not created anywhere so it never gets a chance to reorder as that code is simply unused...

**Comment by RReverser** [comment]
So the only case where it won't work, I think, is when you have a recursive dependency. You shouldn't have it in the first place, and Emscripten already doesn't warn about that I think, so for now I'll go ahead and just prepare this fix.

**Comment by RReverser** [comment]
Actually yeah, as I said, it seemed that `finalCombiner` was simply unused and slightly outdated. Fixed it now, so all postsets are sorted and it detects cycles.
