### ISSUE TITLE
SDL_thread support

### ISSUE THREAD

**Issue by 0joshuaolson1** [emscripten-core/emscripten#5286]
[Source for this claim](https://github.com/kripken/emscripten/issues/5267) (sdl_thread). asm.js has parallelism, right?

**Comment by kripken** [comment]
In browsers with SharedArrayBuffer support, yes, and emscripten has pthreads support. So SDL_thread could be built on top of that, I believe.

**Comment by juj** [comment]
If one builds with `-s USE_PTHREADS=1`, it is possible to create threads with the pthread API. This requires SharedArrayBuffer support in the browser, and currently only works in asm.js. WebAssembly working group is currently speccing out SharedArrayBuffer for WebAssembly, but that is not yet available.
