### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by phraemer** [emscripten-core/emscripten#5294]
Hi,

There are a few things in since the last tag date that I'd really like to benefit from and I'd like to update but we are using the tags in our CI. Is there a release schedule or when is it looking like the next one is?

thanks!

**Comment by kripken** [comment]
There are minor version tags happening every week or few weeks (1.37.13 is latest). I assume you mean a major version tag / merge to master? No immediate plans for that, but we probably should I think, at this point our wasm support is quite stable.

**Comment by juj** [comment]
`1.37.14` tag sounds good even if not merged to master. Though the OS X bot is now back online after the Xcode regression fix, so I want to see that through before tagging. I'll post back here.
