### ISSUE TITLE
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting

### ISSUE THREAD

**Issue by imvetri** [emscripten-core/emscripten#5298]
OS - Windows 7

I get following error if I try run emcc

After following the steps from the website, I got this error
![llvm_error](https://user-images.githubusercontent.com/6542274/27092858-6a16a460-5082-11e7-9288-26790de685cc.PNG)

When I tried the same command in the new terminal I got below error.
![error in new terminal](https://user-images.githubusercontent.com/6542274/27092872-756a8fca-5082-11e7-8d67-e80657485e6c.PNG)

**Comment by kripken** [comment]
Look in `~/.emscripten` for LLVM_ROOT, and running with `EMCC_DEBUG=1` in the env will show you more details on the command it runs that fails. Perhaps LLVM_ROOT is pointing to the wrong place, although the emsdk should set that up properly, so it's strange.

Perhaps a reinstall would fix it.

**Comment by imvetri** [comment]
I looked in `~/.emscripten` and following is what I had
`LLVM_ROOT='C:/Users/USER/Desktop/mine/emsdk/clang/e1.37.13_64bit'`

Plus, this time I got slightly different error message.

![new error](https://user-images.githubusercontent.com/6542274/27282769-0eb89ca4-550f-11e7-8c11-c7c2be9cb115.PNG)

**Comment by wizofe** [comment]
I am getting the same.
