### ISSUE TITLE
Error with emsdk install sdk-incoming-64bit

### ISSUE THREAD

**Issue by IhanaMies** [emscripten-core/emscripten#5315]
CMake Warning:
  Manually-specified variables were not used by the project:
    CLANG_INCLUDE_EXAMPLES
-- Build files have been written to: C:/Program Files/Emscripten/clang/fastcomp/build_incoming_64
Performing a parallel build with 3 cores.
Running build: ['mingw32-make', '-j3']
Build failed due to exception!
Working directory: C:/Program Files/Emscripten/clang/fastcomp\build_incoming_64
[Error 2] File not found
Installation failed!

**Comment by juj** [comment]
The issue here is probably that neither Visual Studio or MinGW G++ is installed. Emsdk does not default to bundling a compiler that would be able to build LLVM. Try installing Visual Studio 2015, if that is present emsdk should default to using that.
