### ISSUE TITLE
compiled JS functions return numbers instead of objects

### ISSUE THREAD

**Issue by sourabh2k15** [emscripten-core/emscripten#5331]
I have compiled HtsLib to javascript using emscripten. In the C code a function returns a struct , so I naturally assumed that the JS code would return an object, but it returns a number. Is it a pointer to the actual value ? if so how do I dereference it to get actual values ?

Thanks.

**Comment by curiousdannii** [comment]
Yes, it's probably a pointer to the struct. You can use code like this to get the values:

```
val1 = Module.getValue( ptr, 'i32' )
val2 = Module.getValue( ptr + 4, 'i32' )
```

**Comment by sourabh2k15** [comment]
I tried that but returns 0 , maybe because it is not a simple struct but has structs as its members ? Can you tell me how to access values in this case . More specifically , 

```
typedef struct {
	int32_t tid;
	int32_t pos;
	uint32_t bin:16, qual:8, l_qname:8;
	uint32_t flag:16, n_cigar:16;
	int32_t l_qseq;
	int32_t mtid;
	int32_t mpos;
	int32_t isize;
} bam1_core_t;

```
```
typedef struct {
	**bam1_core_t core;**
	int l_data, m_data;
	uint8_t *data;
#ifndef BAM_NO_ID
	uint64_t id;
#endif
} bam1_t;
```

`**bam1_t *bam_init1(void);**`

the struct bam1_t is what is returned from the C function. In js my code is, here aln in C is of type struct bam1_t : 

```
var f = Module.FS_createDataFile('/', 'bamfile', file, 1, 1, 1);
var fp_in = Module.ccall('hts_open', 'var', ['string', 'string'], ['bamfile', 'r']);
var bam_hdr = Module.ccall('sam_hdr_read', 'var', ['var'], [fp_in]);

**var aln = Module.ccall('bam_init1', 'var', [], []);
console.log(Module.getValue(aln,'i32')); // returns 0** 

```
