### ISSUE TITLE
Register/Mount Device Drivers to NODEFS

### ISSUE THREAD

**Issue by Guardado** [emscripten-core/emscripten#5339]
I had the impression that you could link current Linux Device Drivers using `FS.makedev(), FS.registerDevice() and FS.mkdev()`, but it looks that you need to write the operations for open(), read(), write(), etc from scratch. Is there a way to mount or interact with current Linux Device Drivers using Emscripten NODEFS?. 
Thanks!

**Comment by Guardado** [comment]
Okay. So to be more specific with the issue. The problem is that you can't open linux device drivers with Emscripten NODEFS. In Node this is possible using the same nodejs fs library. The ability to interact with device drivers using WebAssembly would be very useful because in C/C++ is much easier to interact with them. 

For example for a device driver I wrote for the Integrated Circuit [mcp24AA02](http://ww1.microchip.com/downloads/en/DeviceDoc/21709c.pdf). 

Opening it in C would look something like this:
```C
int fd = open("/dev/mcp24AA02", O_RDWR);
if (fd < 0) {
    printf("Error: %s\n", strerror (errno));
    return 0;
} else {
    printf("Success!!\n");
    return 1;
}
```
Using NODEJS FS also works: 
```javascript
var fs = require("fs");

var fd = fs.openSync("/dev/mcp24AA02", fs.constants.O_RDWR);
if (fd < 0) {
	console.log("Error opening file");
	return 0;
} else {
	console.log("Success!!");
	return 1;
}
```

But using Emscripten NODEFS, although I have tried many things, it doesn't work, for example:
```C
EM_ASM(
    	FS.mkdir('/drivers');
    	FS.mount(NODEFS, { root: '/dev' }, '/drivers');
  	);

int fd = open("/drivers/mcp24AA02", O_RDWR);
if (fd < 0) {
    printf("Error: %s\n", strerror (errno));
    return 0;
 } else {
    printf("Success!!");
    return 1;
 }
```

The applications of this would be easier integration of html interfaces with the hardware. To build for example embedded devices e.g. smart phones like (FireFox OS, Tizen which are based on html, javascript, etc) or just for robotics. Also I haven't tried **ioctl()** in WebAssembly and I don't know if this works too. 

Thanks :)!!

**Comment by juj** [comment]
If it does work with node.js filesystem API with your handwritten JavaScript snippet, then it is possible that it could be made to work with `src/library_nodefs.js`. Not sure what the discrepancy there is however. You could try debugging around line 224 in `src/library_nodefs.js` which has

```javascript
stream.nfd = fs.openSync(path, NODEFS.flagsToPermissionString(stream.flags));
```

to try to figure out why that fails, if that is the location where it aborts.

**Comment by Guardado** [comment]
Thank you for the advice. I was able to find the problems in ```src/library_nodefs.js``` and make the program work. 

The problem was that the file (file node) wasn't being created in ```createNode()``` in the ```lookup()``` processes, and thus wasn't being found. This was because the file I'm trying to open is a Char Device and not a File. ```createNode()``` line 14:
```javascript
if (!FS.isDir(mode) && !FS.isFile(mode) && !FS.isLink(mode)) {
  throw new FS.ErrnoError(ERRNO_CODES.EINVAL);
}
```
So I added also a check for Char Devices and Block Devices. 
```javascript
if (!FS.isDir(mode) && !FS.isFile(mode) && !FS.isLink(mode) &&
    !FS.isChrdev(mode) && !FS.isBlkdev(mode)) {
  throw new FS.ErrnoError(ERRNO_CODES.EINVAL);
}
```

I also check if the functions open(), read(), write() and close() work correctly for Char Devices. 

The open() function also checks only for Files. ```open()``` line 223:
```javascript
if (FS.isFile(stream.node.mode)) {
  stream.nfd = fs.openSync(path, NODEFS.flagsToPermissionString(stream.flags));
}
```
So I added checks for Char Devices and Block Devices too. 
```javascript
if (FS.isFile(stream.node.mode) || FS.isChrdev(stream.node.mode) || FS.isBlkdev(stream.node.mode)) {
  stream.nfd = fs.openSync(path, NODEFS.flagsToPermissionString(stream.flags));
}
```

Same was for close(). ```close()``` line 233:
```javascript
if (FS.isFile(stream.node.mode) && stream.nfd) {
  fs.closeSync(stream.nfd);
}
```
After the changes.
```javascript
if ( (FS.isFile(stream.node.mode) || FS.isChrdev(stream.node.mode) 
  || FS.isBlkdev(stream.node.mode)) && stream.nfd) {
  fs.closeSync(stream.nfd);
}
```

And for llseek(). Although I didn't test this, but it should work too. ```llseek()``` line 274:
```javascript
if (FS.isFile(stream.node.mode)) {
```
After the changes.
```javascript
if (FS.isFile(stream.node.mode) || FS.isChrdev(stream.node.mode) 
    || FS.isBlkdev(stream.node.mode)) {
```
.
.
.
Now I also found something strange. I wasn't able to read anything with read(). For example with this code in C that should read fine, I was getting nothing and no errors:
```C
char rdata[32];
memset(&rdata, 0, sizeof(rdata));
int result = read(fd, rdata, 32);
if (result < 0)
{
        printf("Error Reading: %s \n", strerror(errno));
} else {
        printf("Driver Read = %s \n", rdata);
}
```
In the following code: ```read()``` line 247
```javascript
res = fs.readSync(stream.nfd, nbuffer, 0, length, position);
```
I found that position was getting the same value as length. In the above case position was getting the value of 32. So res was getting 0 and so nothing was being read as result.
I changed position to null, or it can also be 0. With this I was able to read correctly. 
```javascript
res = fs.readSync(stream.nfd, nbuffer, 0, length, null);
```
Now I haven't find the root of the above problem and that change can introduce some problems if using llseek(), I guess. 


[Here](https://gist.github.com/Guardado/168436ea75fb7c830391437abf0548ee#file-testdevicedriver-c) is the C code I used for testing the device driver.
[Here](https://gist.github.com/Guardado/9813495a39ddb7066e856bdc6c07dc01) is the device driver, is a simple echo device driver for testing and it should work in any Linux machine.

**Comment by Guardado** [comment]
Hi, so I found the problem to the last issue I was having. Basically the problem is that ```fread()``` and ```fwrite()``` are being implemented with the low level functions ```write()``` and ```read()```, in NODEFS. And ```write()``` is not equal to ```fwrite()``` as well as ```read()```  is not equal to ```fread()```. By this I mean that in ```write()``` and ```read()``` never do anything with ```position```. In ```write()``` and ```read()``` position should always be null or 0, like the following:
```javascript
res = fs.writeSync(stream.nfd, nbuffer, 0, length, 0);
res = fs.readSync(stream.nfd, nbuffer, 0, length, 0);
```
Currently in Web-assembly when doing a ```write()``` and ```read()``` position gets increased.  This is correct for ```fwrite()``` and ```fread()```, but is not correct for ```write()``` and ```read()```. 
```javascript
// Current...
res = fs.writeSync(stream.nfd, nbuffer, 0, length, position);
res = fs.readSync(stream.nfd, nbuffer, 0, length, position);
```

So for device drivers that do not handle position, like the one I included above, although the C implementations works correct the translation to Webassembly doesn't.
