### ISSUE TITLE
Add support for creating SDL and OpenAL audio contexts with specified sampling rate

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5349]
Web Audio API has added a feature where you can create a context with custom specified sampling rate. This support is landing to browsers now/soon, so should add support for this:

https://webaudio.github.io/web-audio-api/#idl-def-AudioContextOptions

**Comment by feliwir** [comment]
Any news on this? I need to use a custom sample rate

**Comment by briancullinan** [comment]
This was extremely slow for me at 30 fps. After 10 minutes the frame rate would drop to 1 fps. Specifically the vertex based Respatializer. The one in quake3 is faster when compiled to wasm. And I've even rate limited it to 30fps like OpenAL with no memory problems. Maybe garbage collection? Or heap isn't getting cleared?
