### ISSUE TITLE
sdk-incoming or sdk-1.37.14 llvm-ar failed to link .lib

### ISSUE THREAD

**Issue by trippleflux** [emscripten-core/emscripten#5350]
I have got the following when linking d3dcompiler.lib with emcc which resulting llvm-ar error : 
```
1>------ Build started: Project: EsenthelEngine, Configuration: Release GL Emscripten ------
1>GCCLIB : warning : root:loading from archive C:\Dev\EsenthelEngine\ThirdPartyLibs\DirectX\x64\d3d9.lib, which has duplicate entries (files with identical base names). this is dangerous as only the last will be taken into account, and you may see surprising undefined symbols later. you should rename source files to avoid this problem (or avoid .a archives, and just link bitcode together to form libraries for later linking)
1>GCCLIB : warning : root:   duplicate: d3d9.dll
1>GCCLIB : warning : root:loading from archive C:\Dev\EsenthelEngine\ThirdPartyLibs\DirectX\x64\d3dcompiler.lib, which has duplicate entries (files with identical base names). this is dangerous as only the last will be taken into account, and you may see surprising undefined symbols later. you should rename source files to avoid this problem (or avoid .a archives, and just link bitcode together to form libraries for later linking)
1>GCCLIB : warning : root:   duplicate: D3DCOMPILER_47.dll
1>Traceback (most recent call last):
1>  File "C:\Program Files\Emscripten\emscripten\1.37.14\\emcc", line 13, in <module>
1>    emcc.run()
1>  File "C:\Program Files\Emscripten\emscripten\1.37.14\emcc.py", line 1377, in run
1>    shared.Building.link(linker_inputs, specified_target)
1>  File "C:\Program Files\Emscripten\emscripten\1.37.14\tools\shared.py", line 1762, in link
1>    Building.read_link_inputs(filter(lambda x: not x.startswith('-'), files))
1>  File "C:\Program Files\Emscripten\emscripten\1.37.14\tools\shared.py", line 1688, in read_link_inputs
1>    raise Exception('llvm-ar failed on archive ' + archive_names[n] + '!')
1>Exception: llvm-ar failed on archive C:\Dev\EsenthelEngine\ThirdPartyLibs\DirectX\x64\d3dcompiler.lib!
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(69,5): error MSB6006: "C:\Program Files\Emscripten\emscripten\1.37.14\emcc.bat" exited with code 1.
1>Done building project "EsenthelEngine.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Those files and libs are previously linkable with emscripten sdk 1.36.14

**Comment by kripken** [comment]
Are you trying to load older bitcode or archive files with a newer toolchain? You may need to rebuild them if so. If not, can you make a standalone testcase showing the problem?

**Comment by trippleflux** [comment]
@kripken 
Thanks for the reply, it's correct for issue #5347, unfortunately it's a proprietary product, perhaps i could send you the compiled .o object files including the used d3dcompiler.lib, i cannot host it on public, could you please give me your e-mail?

**Comment by trippleflux** [comment]
Probably it's better to use twitter DM?, i have followed you on twitter under @life_tips_4u twitter handle, please follow me so i can send you the link through twitter DM.

**Comment by kripken** [comment]
My email is in the AUTHORS file.

**Comment by juj** [comment]
You cannot link to `DirectX\x64\d3dcompiler.lib` with Emscripten, that is a Microsoft provided closed source natively compiled Windows library. Emscripten is not a native code translator that could take already compiled code and translate it to asm.js/WebAssembly, but you'll need to have the source code to compile over to Emscripten.

There is a live demo of Esenthel Engine already ported to asm.js at http://www.esenthel.com/?id=live_demo, so porting has already been done. It looks like Esenthel's build system has somehow regressed and it's attempting to link to Microsoft's D3D compiler even when using Emscripten, which it shouldn't. Esenthel's support should be able to help you there.
