### ISSUE TITLE
Separate Browser.mainLoop from the browser API functions

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#5355]
If you use EmterpreterAsync it pulls in the whole Browser object, which is about 30KB of code. The majority of this is not required by EmterpreterAsync. It would be possible to separate out Browser.mainLoop and the handful of other functions which are needed (resumeAsyncCallbacks, pauseAsyncCallbacks, etc.)

While it may be possible, I'm not sure how much work it would be or whether it would be worth it... but it doesn't hurt to post an issue suggesting it.

**Comment by curiousdannii** [comment]
Just nothing that [@juj mentioned a possible future overhaul of the main loop functions in another issue](https://github.com/kripken/emscripten/issues/5028#issuecomment-323019359).

**Comment by curiousdannii** [comment]
I haven't looked at this for a while. Is Browser still included with the new ASYNCIFY mode?

**Comment by kripken** [comment]
@curiousdannii looks like it is. For similar reasons, it needs to check the main loop, uses asyncLoad, etc.

I agree it would be nice to refactor those out. However, I hope this already would be pretty well minified when closure is enabled, as it can remove unneeded properties of things?

**Comment by curiousdannii** [comment]
Ah, I haven't used Closure. Guess I'll give it a try.

**Comment by curiousdannii** [comment]
It would still be great if this could happen. I was even thinking yesterday of having a go at making a PR myself.

**Comment by kripken** [comment]
I think this would still be nice to do. Could be a useful refactoring!

**Comment by curiousdannii** [comment]
I no longer need this, #12181 removed `mainLoop` itself from my output. But I'll still keep working on it as it will probably be helpful for others.
