### ISSUE TITLE
Emrun fails to detect that code was compiled with --emrun

### ISSUE THREAD

**Issue by AaronViviano** [emscripten-core/emscripten#5358]
Hello,
I am having an issue with emrun where it doesn't seem to detect that code has been compiled with the --emrun flag. The code is as follows:

```
#include <stdio.h>
#inlcude <iostream>
using namespace std;

int main(int argc, char ** argv)
{
    int test = 0;
    printf("Hello World!\n");
    cin >> test;
    cout << "The value entered is: " << test << endl;
}
```
The commands used to compile and run are:
```
emcc hello.cpp --emrun -s WASM=1 -o hello.html
emrun --no_browser --port 8080 hello.html
```
The site loads and creates an input dialogue. Once I close the input window in my browser (chrome or firefox) I receive the following error message in my terminal: "The html page you are running is not emrun-capable. Stdout, stderr and exit(returncode) capture will not work. Recompile the application with the --emrun linker flag to enable this, or pass --no_emrun_detect to emrun to hide this check."

Is this expected to happen?
Thank you.

**Comment by juj** [comment]
This should not happen. When trying out locally, I see that the input dialog keeps appearing again and again after I close it. The prints do come through to terminal window:

```
C:\code\emsdk\emscripten\incoming>emrun --no_browser --port 8080 c.html
Web server root directory: C:\code\emsdk\emscripten\incoming
Now listening at http://localhost:8080/
pre-main prep time: 18 ms
Hello World!
The value entered is: 234234
```

Is the issue somehow related to blocking with `cin`, or does it also occur for you if you just print out with `cout`?

**Comment by AaronViviano** [comment]
It only occurs with cin.

**Comment by Humma4** [comment]
Hi,

not sure if it's relevant or not, but I receive the same warning when I run the "hello3" example from [this page](https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm).

Cin isn't used in that example, only printf.

**Comment by evandrix** [comment]
`#inlcude <iostream>` - `include` is mis-spelled!

**Comment by AaronViviano** [comment]
> 
> 
> `#inlcude <iostream>` - `include` is mis-spelled!

Not surprising really. That is a fairly common mistake for me. *sigh*
