### ISSUE TITLE
BINARYEN_IMPRECISE not recognized 

### ISSUE THREAD

**Issue by sjfricke** [emscripten-core/emscripten#5360]
Trying to run
`emcc -o change.js change.c -lm -O3 -s WASM=1 -s EXPORTED_FUNCTIONS="['_change']" -s BINARYEN_IMPRECISE=1`

And getting this

```
WARNING:root:Assigning a non-existent settings attribute "BINARYEN_IMPRECISE"
WARNING:root: - did you mean one of BINARYEN_PASSES, BINARYEN_METHOD, BINARYEN_MEM_MAX?
WARNING:root: - perhaps a typo in emcc's  -s X=Y  notation?
WARNING:root: - (see src/settings.js for valid values)
```

while it clearly is in the [settings already](https://github.com/kripken/emscripten/blob/master/src/settings.js#L670)

**Comment by kripken** [comment]
That option was removed, see the `BINARYEN_TRAP_MODE` option.

**Comment by sjfricke** [comment]
Is this on some branch? I can't find `BINARYEN_TRAP_MODE` option on either the Emscripten nor Binaryen master branch

**Comment by kripken** [comment]
Yes, it's on the incoming branch. We haven't merged to master for a while, so incoming is recommended.
