### ISSUE TITLE
Unescape arguments passed via URL

### ISSUE THREAD

**Issue by avaskoog** [emscripten-core/emscripten#5369]
Hey. Based on [this interaction](https://twitter.com/avaskoog/status/883070222621691906) I'd like to make a request.

## Issue

When starting up a program with arguments (`argv` in `main()`) by slapping them onto the `emrun` invocation, the arguments are passed as GET values to the URL of the page, resulting in escaped strings, like so:

![deigccvxyaadvjg](https://user-images.githubusercontent.com/25255407/27969881-ff5b22e4-634c-11e7-8e78-3eb481450253.jpg)

The invocation looks something like this:

```
emrun <path to html> some arguments "with spaces"
```

These strings are then passed like this (with the escaping) on to the program, and so I get _"with%20spaces"_ instead of the expected _"with spaces"_.

## Proposed solution

Obviously I could unescape this manually, but it feels like a bug that Emscripten functionality doesn't quite mirror functionality elsewhere here, so I think it would be better if this were fixed at the root of the problem.

I'm assuming it is Emscripten itself that generates code where these strings are placed into the `argv` of `main()`, and that it was overlooked in this implementation that the strings need to be unescaped first. So I presume all that needs to be done is to make sure this happens? Maybe even by hitching a ride on the built-in JS function `decodeURI()`?

Thanks!

**Comment by juj** [comment]
The input processing of emrun arguments is done in https://github.com/kripken/emscripten/blob/incoming/src/emrun_prejs.js#L3. Feel free to propose a fix there. There is a test at https://github.com/kripken/emscripten/blob/master/tests/test_browser.py#L2095, which would be good to be updated to verify the desired behavior.
