### ISSUE TITLE
Some strange things when use char* in C.

### ISSUE THREAD

**Issue by messset** [emscripten-core/emscripten#5376]
Hello!
I compile c to wasm in side_module,
But there are some wrong results with using char*.

Sorry, I can't get a conclusion,because I always get different results with similar logic.
I reproduce the failure with some simple code.(But I'm not sure the result is same on different computers. ) 

First,I have a "print" function in Javascript.(it's no problem) 
Then,there are some codes and wrong results:

<1>O
`print("Hello_Before");`
`char str[10] = "";`
`print(str);`
`print("Hello_After");`

result is right
line 1:Hello_Before
line 2:
line 3:Hello_After

<1.1>X
`print("Hello_Before");`
`char str[30] = "";`
`print(str);`
`print("Hello_After");`

result is wrong (line 3)
line 1:Hello_Before
line 2:
line 3:

<2>X
`void passStr(char* str)`
`{`
`	print("HELLO?");`
`	if (str == NULL)`
`	{ print("HELLO?"); }`
`}`
`void enterFunc()`
`{`
`	char str[30] = "ssss";`
`	passStr(str);`
`}`

result is wrong 
line 1:ssss
line 2:ssss

Thanks!

**Comment by juj** [comment]
The above lines don't really have anything relevant that would be possible to diagnose. Can you please build a complete minimal test case with `-g2` linker setting that showcases the issue?

**Comment by messset** [comment]
is it like this?
https://github.com/messset/char-test-wasm

And , in case1 , I find the initial memory buffer is: "Hello_Before\00Hello_After"
Hownever , I print the buffer after  char str[10] = "";
the buffer is: "\00\00\00\00\00\00\00\00\00\00re\00Hello_After"
in str[30] case;
the buffer is: "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00.......\00"

*str*  covered over the initial data.
The index of string "Hello_After" is 13,
so print("Hello_After") show noting if *str*'s lengh is bigger then 14.

**Comment by juj** [comment]
The issue in your above example is that you are bypassing the Emscripten runtime initialization, and the stack space is not initialized and stack top ends up at address 0, which collides with global memory area. The zero initialization of `char str[30] = "";` then ends up nuking over the global data section that contains the strings.

Emscripten-outputted .js file cannot be ignored when running .wasm code, but it sets up the needed runtime for compiled code (global initializers and stack space and so forth)

**Comment by messset** [comment]
Thank you very much.

Can I set initialization and stack info by writting JS code with self,
or I must output it by using Emscripten?

**Comment by juj** [comment]
We don't currently support a mechanism for developers to initialize the runtime by themselves, since that changes along time as runtime features change (most recent being threads initialization). You can try being careful and following `src/preamble.js` and extracting the initialization paths from there if you want to do it manually, but that can be brittle on the long run.

**Comment by messset** [comment]
oh...
Is it mean I can't use SIDE_MODULE wasm to complete the program independently?

**Comment by juj** [comment]
SIDE_MODULE is intended to allow dynamic linking, not to avoid having to initialize the runtime.

Strings need to be marshalled via memory, there is no built-in string type in wasm. Check out the runtime functions such as `stringToUTF8` and `UTF8ToString` that can be used to perform such memory<->JS string conversion.

**Comment by messset** [comment]
Sorry for not making my points clear. 
My question is that : If somebody can get the all memory data by JS code?
In other words , someone can get the string(char array) parameters ,whether they are  transferred between two functions in the same wasm module or wasm <-> JS.

For  security consideration , I must be sure that nobody can get the data in  program 
easily.(Like IE ActiveX) 
That's my motivation for using WebAssembly. But is it wrong?

**Comment by juj** [comment]
WebAssembly does not create a new web security boundary between JavaScript and WebAssembly, but anyone who has access to the JavaScript context will also have full access to everything in the WebAssembly side, including all the code, stack, function locals and the memory. The web security boundary that is applied is the same as with JavaScript, i.e. [access is restricted at origin boundaries](https://developer.mozilla.org/en-US/docs/Web/Security). WebAssembly does not provide a DRM solution that would encrypt or prevent access further, though it does obfuscate the code by being at a lower level than JavaScript, so it does give a harder time for people to figure out what is located where.
