### ISSUE TITLE
Add SDL2 support to --proxy-to-worker

### ISSUE THREAD

**Issue by fallenoak** [emscripten-core/emscripten#5380]
I'm attempting to get em-dosbox running with `--proxy-to-worker`. em-dosbox uses the emscripten SDL2 port. It appears there are a few issues with how `proxyWorker` sets up its proxies and fakes re: what SDL2 expects.

I've created this issue to document what seems to be missing, and potential implementations to improve SDL2 support.

My discoveries so far:

**1. Missing `CanvasRenderingContext2D.createImageData()`**

`proxyWorker` defines a partial implementation of `CanvasRenderingContext2D` here:
https://github.com/kripken/emscripten/blob/incoming/src/proxyWorker.js#L182

Unfortunately, it appears the emscripten SDL2 port expects `createImageData()` to be available:
https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenframebuffer.c#L83

This expectation can be met by adding the following to `proxyWorker`'s `CanvasRenderingContext2D`:
```
createImageData: function(w, h) {
  return {
    width: w,
    height: h,
    data: new Uint8Array(w * h * 4)
  };
}
```

This at least gets to a point where the DOSBox splash screen displays in the canvas (courtesy of the existing `putImageData()`.

I'm not sure (and didn't quite catch from the MDN docs) if `createImageData` is supposed to zero out `canvas.data`.

**2. Missing `AudioContext.createScriptProcessor()`**

`proxyWorker` defines a partial implementation of `AudioContext` here:
https://github.com/kripken/emscripten/blob/incoming/src/proxyWorker.js#L321

Unfortunately, it appears the emscripten SDL2 port expects `createScriptProcessor()` to be available:
https://github.com/emscripten-ports/SDL2/blob/master/src/audio/emscripten/SDL_emscriptenaudio.c#L382

This expectation can be met by adding the following to `proxyWorker`:
```
function AudioContext() {
  // snip
  this.createScriptProcessor = makeNode;
}
```

After meeting these two expectations, I'm able to get em-dosbox to boot and reach a command prompt. Input appears to not be working, but I suspect that's unrelated to SDL2 support.

Once I have a bit more time to play around with things, I'll see about opening a PR to remedy these issues (and any others I find).

**Comment by Beuc** [comment]
I confirm we still miss createImageData().
```
exception thrown: TypeError: SDL2.ctx.createImageData is not a function,ASM_CONSTS<@http://...
```
The events don't seem to propagate correctly either when I try with your fix.
Did you progress with your worker-based build?

More generally, `--proxy-to-worker` was supposed to be deprecated in favor to pthread/SharedArrayBuffer support (see #5961), but since SharedArrayBuffer was [disabled](https://kripken.github.io/emscripten-site/docs/porting/pthreads.html), `--proxy-to-worker` is relevant again?

**Comment by Beuc** [comment]
Update: the events do propagate, but `document` lacks the mouseup event, meaning the button stays pressed when clicked and this causes surprising behavior.
Relevant src/video/emscriten/SDL_emscriptenevents.c hooks:
```
    emscripten_set_mousedown_callback("#canvas", data, 0, Emscripten_HandleMouseButton);
    emscripten_set_mouseup_callback("#document", data, 0, Emscripten_HandleMouseButton);
```
Fix for proxyClient.js:
```
-['keydown', 'keyup', 'keypress', 'blur', 'visibilitychange'].forEach(function(event) {
+['keydown', 'keyup', 'keypress', 'blur', 'visibilitychange', 'mouseup'].forEach(function(event) {
   document.addEventListener(event, function(event) {
```

--

Another thing I'd really need is SDL_WaitEvent() support, but this seems to just lock the Worker.
This could come from src/video/emscripten/SDL_emscriptenvideo.c:
```
static void
Emscripten_PumpEvents(_THIS)
{
    /* do nothing. */
}
```
while this should pop the Worker messages. I'll have to make some more tests to be sure.
