### ISSUE TITLE
Can I embind a `union` type struct property?

### ISSUE THREAD

**Issue by cqq626** [emscripten-core/emscripten#5381]
I have a following C++ code:

    typedef struct _RGEvent_t
    {
        ng_uint priority;                  
        RGEventKindEnum eventKind;         
        RGEventTiming_t timing;            
        RGEventCheckTiming_t checkTiming;  
        
        union{
            RGVIInfo_t viInfo;
            RGDIInfo_t diInfo;
            RGBIInfo_t biInfo;
        };
        
        int status;
        int eventId;
        
    }RGEvent_t;

I have tried to search the document and benchmark [here](https://github.com/kripken/emscripten/tree/master/tests/embind).But I still have no idea how to deal with the union type.
I also try to write code belows:

    value_object<RGEvent_t>("RGEvent_t")
        .field("priority", &RGEvent_t::priority)
        .field("eventKind", &RGEvent_t::eventKind)
        .field("timing", &RGEvent_t::timing)
        .field("checkTiming", &RGEvent_t::checkTiming)
        .field("viInfo", &RGEvent_t::viInfo)
        .field("diInfo", &RGEvent_t::diInfo)
        .field("biInfo", &RGEvent_t::biInfo)
        .field("status", &RGEvent_t::status)
        .field("eventId", &RGEvent_t::eventId)
        ;

However, I can't be access to the RGEvent struct using Module.
Is there a way to solve this problem?

**Comment by juj** [comment]
If there are no tests for this, I believe unions are not recognized. Perhaps try going the route of creating set and get functions to access unions as a workaround.
