### ISSUE TITLE
Is emscripten transform OpenGL to WebGL?

### ISSUE THREAD

**Issue by skyfore** [emscripten-core/emscripten#5386]
Recently, I'm trying to compile my OpenGL C++ code to Web.

But I receive much of problems, such as `unresolved symbol`, and I search for reslut ,I just see https://github.com/kripken/emscripten/issues/4573.

This link suggest I write OpenGL ES 2.0 but adhere to the restrictions outlined in https://www.khronos.org/registry/webgl/specs/1.0/#6.

So,  I guess that when emscripten compile OpenGL C++ code to Web need to transform OpenGL to WebGL. And If there isn't match API between OpenGL and WebGL, it will not work.

That's all my deduce, if it's true, so I need change my C++ code?

Can someone tell me truth? Thks! :smiley:

**Comment by skyfore** [comment]
And there are some interactions in web canvas when I compiled OpenGL to Web?

Such as click, drag and keyboard input etc. Just like OpenGL native code performance.

**Comment by juj** [comment]
Does this help? http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html

**Comment by skyfore** [comment]
@juj Thks for your reply!
I had read this doc and try the examples in test/glbook

But, I feel not good, because I just got a static canvas just like pic, such as Chapter_2

I don't know if my build method is wrong. 

Can you give me more examples such as a cube can drag in webpage writen by OpenGL C++ code?

**Comment by juj** [comment]
> Can you give me more examples such as a cube can drag in webpage writen by OpenGL C++ code?

Sorry, I don't have such an example at hand. Try searching for OpenGL ES 2.0 based examples on the web that can help get started.

**Comment by skyfore** [comment]
Thank you very much! :smiley:
