### ISSUE TITLE
SDL SDL_RenderDrawPoint Slow

### ISSUE THREAD

**Issue by Dwordcito** [emscripten-core/emscripten#5388]
Hi, im use a SDL_RenderDrawPoint and obtaining a low performance in emscripten
this is a normal? , in android, windows, linux, this is a not issue, and run with good performance.

**Comment by caspervonb** [comment]
`SDL_RenderDrawPoints` essentially translates to `glDrawElements`, there is no batching/buffering so each call will create and upload to a new vertex buffer.

In other words, I wouldn't expect that to be performant on desktop but maybe raise it over on SDL's new forums at https://discourse.libsdl.org.

**Comment by caspervonb** [comment]
Ryan added batching a while back https://hg.libsdl.org/SDL/rev/0d5da1145cad
