### ISSUE TITLE
libc math file exclusion/re-inclusion inconsistency

### ISSUE THREAD

**Issue by mvogelsang** [emscripten-core/emscripten#5392]
Looking at the files built by emscripten's port of libc, I notice that several math-related files are excluded for asm.js but later get re-included as separate libs for wasm (wasm_libc and wasm_libc_rt). Upon cross checking the files that get re-included, it seems that these files never get included by either of the wasm libraries.
`'abs.c', 'sqrt.c', 'sqrtf.c', 'sqrtl.c', 'fabs.c', 'fabsf.c', 'fabsl.c', 'ceil.c', 'ceilf.c', 'ceill.c', 'floor.c', 'floorf.c', 'floorl.c', 'round.c', 'roundf.c'`
Am I missing something? Is there a reason for this? or is it a mistake?

**Comment by juj** [comment]
Wasm has built-in opcodes for some instructions, and I think these are all ones that get directed to wasm instructions rather than using library files. Is this causing some issues in your project?

**Comment by mvogelsang** [comment]
I just saw it but didn't see a comment mentioning it. I had no context for knowing why this would be the case so I thought I'd check. Good to know. 
If it causes an issue it's likely on our end. We're building the emscripten port of libc (and eventually other furnished libraries) with just plain clang 5. So if emcc/fastcomp has the knowledge of using the builtin instructions but not clang 5 we'll continue to include them for now.
After some experimentation I'll report back here for future reference of others.
I'll go ahead and close the issue now though.

**Comment by dschuff** [comment]
I don't think wasm has instructions for all of these. They were not needed for asm.js which used JS for a lot of math stuff, and some of that is inherited by asm2wasm. But wasm may need some of them when we switch to the upstream backend. So I'm going to leave this open for now so we can check on it.

**Comment by dschuff** [comment]
cc @jgravelle-google

**Comment by mvogelsang** [comment]
As a note, so using a build of libc with the mentioned files included, I'm able to compile and successfully run main function that looks like this [this](https://gist.github.com/mvogelsang/2c97b76a22b7dab8c6db38c5809cdde8).  
This `main` exercises each of the functions in the files in question except `sqrtl`. `sqrtl` refuses to work, and looking at its implementation, it seems like its reliance on `long double` might be part of the problem. 
And of course, plain clang 5 does not magically know what to do for these math functions when the mentioned files are not included in the build of libc.
