### ISSUE TITLE
Add Google Protocol Buffers?

### ISSUE THREAD

**Issue by birgersp** [emscripten-core/emscripten#5396]
I've been trying to build Google Protocol Buffers with emscripten, to include it in my project. But I'm sorry to say it's a bit beyond my current level...

Could Google Protocol Buffers be added with the other tools/built-in libraries of emscripten?

(Or could someone help me figure out how to build Google Protocol buffers with emscripten on Windows?)

**Comment by chicoxyzzy** [comment]
Not sure what do you mean by Emscripten protobuf support but I'm interested wasm protobuf encoding/decoding module. Actually I've started some experiments but I have no anything to share yet.

**Comment by birgersp** [comment]
Came across this repo: https://github.com/invokr/protobuf-emscripten

Works like a charm. But maybe an "official" protobuf emscripten module is a good idea.
