### ISSUE TITLE
Type info not available to library code

### ISSUE THREAD

**Issue by max99x** [emscripten-core/emscripten#54]
Currently the type info, in particular pre-calculated struct layouts, is not available to library code at either compile- or run-time. Since this info is already calculated from the LL, it would be nice to have it available directly, so one could call `Runtime.generateStructInfo('foo')` (or something similar) and get an object defining the size of the `foo` struct and the offsets of its members.

**Comment by lucidvizion** [comment]
> If I need to allocate a struct and set its members in a library function, I have to know its layout.

What is the solution to this problem with FastComp?  I see that Runtime.typeInfo is not available anymore.

**Comment by kripken** [comment]
You can create a method in C that returns the size and/or positions of elements, and compile that, then call it. This is essentially what the webidl binder and embind do, so might be useful to look at their code or output.
