### ISSUE TITLE
Cannot find /opt/emsdk-portable/clang/e1.37.16_64bit/llvm-ar, check the paths in ~/.emscripten

### ISSUE THREAD

**Issue by jasmad** [emscripten-core/emscripten#5403]
Following this tutorial https://tutorialzine.com/2017/06/getting-started-with-web-assembly

Running this command "emcc dice-roll.c -s WASM=1 -O3 -o index.js"

The console throws: 

INFO:root:(Emscripten: Running sanity checks)
CRITICAL:root:Cannot find /opt/emsdk-portable/clang/e1.37.16_64bit/llvm-ar, check the paths in ~/.emscripten

The funny thing is that file does not exists.
Listing the directory:
`ls /opt/emsdk-portable/clang/e1.37.16_64bit/ `

`binaryen      clang-cpp              emscripten-version.txt  lli-child-target  llvm-cxxfilt  llvm-link  llvm-opt-report      llvm-tblgen  sanstats             yaml2obj
c-arcmt-test  clang-offload-bundler  llc                     llvm-bcanalyzer   llvm-diff     llvm-mc    llvm-PerfectShuffle  opt          scan-view
clang++       clang-tblgen           lli                     llvm-config       llvm-dwp      llvm-nm    llvm-rtdyld          sancov       verify-uselistorder`

Did I installed it the wrong way?

1. /opt/emsdk-portable/emsdk update
2. /opt/emsdk-portable/emsdk install latest
3. /opt/emsdk-portable/emsdk activate latest
4. PATH=$PATH:/opt/emsdk-portable:/opt/emsdk-portable/clang/e1.37.16_64bit:/opt/emsdk-portable/emscripten/1.37.16
export PATH
5. source ~/.bash_profile
6. emcc --version 
emcc (Emscripten gcc/clang-like replacement) 1.37.16 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
7. emcc dice-roll.c -s WASM=1 -03 -o proba2.js

**~/.emscripten contents**
```
import os
LLVM_ROOT='/opt/emsdk-portable/clang/e1.37.16_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/opt/emsdk-portable/clang/e1.37.16_64bit/optimizer'
BINARYEN_ROOT='/opt/emsdk-portable/clang/e1.37.16_64bit/binaryen'
NODE_JS='/opt/emsdk-portable/node/4.1.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/opt/emsdk-portable/emscripten/1.37.16'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```
I am on fedora 23

**Comment by juj** [comment]
This looks like perhaps something went wrong during the `emsdk install` step, and the download did not complete. There is siupposed to exist a path `emsdk-portable/emsdk/clang/e1.37.16_64bit/` with `clang` and a bunch other executables in it. Does `emsdk list` display `clang-e1.37.16-64bit` as installed? If not, try redoing the `emsdk install latest` step. You can also try `emsdk uninstall clang-e1.37.16-64bit` first in case the directory has some kind of partial corrupted installation.

**Comment by AjBreidenbach** [comment]
I had this issue installing over a bad internet connection.  It worked after deleting the clang folder and running`emsdk install` again.

**Comment by sjfricke** [comment]
Can confirm that this deleting the `clang` folder and running 
`emsdk install latest` 
`emsdk activate latest` 
fixed this same issue for me
