### ISSUE TITLE
Test other.test_llvm_nativizer regression on Linux

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5409]
The test `other.test_llvm_nativizer` still worked on Linux bot run 382: 

http://clb.demon.fi:8112/#/builders/4/builds/382

which consists of

```
clang: f0ecddc366274df7ddf93c166dc3fc1baa7edda7
emscripten: a38d392a3a51005ee384ee98f87558c13faef170
llvm: 8ea13cdd62f2f0b58dc19e77be96a20f8d3a14f5
```

but began to fail on Linux bot run 383:

http://clb.demon.fi:8112/#/builders/4/builds/383

which is

```
clang: f0ecddc366274df7ddf93c166dc3fc1baa7edda7
emscripten: 519de4c4160f37af5e0c24a5cc2f57d142ad0c65
llvm: 8ea13cdd62f2f0b58dc19e77be96a20f8d3a14f5
```

Diffing `git log a38d392a3a51005ee384ee98f87558c13faef170... 519de4c4160f37af5e0c24a5cc2f57d142ad0c65` says

```
commit 519de4c4160f37af5e0c24a5cc2f57d142ad0c65
Author: Sam Clegg <sbc@chromium.org>
Date:   Thu Jun 22 13:49:32 2017 -0700

    Cleanup use of EMCC_WASM_BACKEND env (#5327)
    
    
    In some places were were checking EMCC_WASM_BACKEND
    directly.
    
    Rather than checking the environment or calculating it
    based on get_llvm_target() we should consistently
    using Settings.
```

and this seems to reproduce locally on Linux with that commit as the offending one.

@sbc100 : would you be able to reproduce? @kripken : does the failure occur on your linux system?

**Comment by kripken** [comment]
Yeah, I see this locally too. #5364 should fix it. I think it's waiting on a question for @sbc100
