### ISSUE TITLE
How to pass emscripten options to emcmake cmake

### ISSUE THREAD

**Issue by DutchKevv** [emscripten-core/emscripten#5414]
Hi There,

First off all, great project!!!

I have been playing for a few weeks now but cant figure out how to use the MakeList file with 

`emcmake cmake` and pass `emscripten` options to it 

(-o dist/engine.js -g  -s DISABLE_EXCEPTION_CATCHING=0 -s TOTAL_MEMORY=33554432  -s DEMANGLE_SUPPORT=1 -s SAFE_HEAP=1 --bind -s WASM=1 -Os -s LEGACY_GL_EMULATION=0  -s GL_UNSAFE_OPTS=0 --pre-js pre-module.js --post-js post-module.js -s ASSERTIONS=2 -s GL_ASSERTIONS=1 -s INVOKE_RUN=0  -std=c++11 -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_GLFW=3 -s OFFSCREENCANVAS_SUPPORT=1 --preload-file textures --preload-file shaders --preload-file extern --use-preload-plugins )

This is my CMakelist file ->

```
cmake_minimum_required(VERSION 3.7)
project(Engine)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_MAKE_PROGRAM:FILEPATH "/usr/bin/make")
set(CMAKE_C_COMPILER "emcc")

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/cmake")
set(CMAKE_INCLUDE_PATH /usr/local/include)
set(SOURCE_FILES main.cpp src/Background.cpp src/Background.h src/Camera.cpp src/Chart.cpp src/Chart.h src/logger.cpp src/Engine.cpp src/Engine.h src/GL.cpp src/GL.h src/Instrument.cpp src/Instrument.h)
set(EMCC_LINKER_FLAGS "-s SAFE_HEAP=1 --bind -s WASM=1 -O3 -o ../index.js -s LEGACY_GL_EMULATION=0  -s GL_UNSAFE_OPTS=0 --pre-js pre-module.js --post-js post-module.js -s ASSERTIONS=1 -s GL_ASSERTIONS=1 -s INVOKE_RUN=0  -std=c++11 -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_GLFW=3 -s OFFSCREENCANVAS_SUPPORT=1 --preload-file shaders --preload-file extern --use-preload-plugins")
set(CMAKE_REQUIRED_FLAGS "${EMCC_LINKER_FLAGS}")

find_package(OPENGL REQUIRED)
#find_package(GLEW REQUIRED)
#find_package(SDL2 REQUIRED)
#find_package(glfw3 REQUIRED)
#find_package(assimp REQUIRED)
#find_package(Freetype REQUIRED)

include_directories(/emscripten/ /emscripten/emscripten/incoming/system/include)
#include_directories(/usr/local/include)
include_directories(${FREETYPE_INCLUDE_DIRS} ${GLEW_INCLUDE_DIR} ${SDL2_INCLUDE_DIR} ${OPENGL_INCLUDE_DIR} ${SDL2_IMAGE_INCLUDE_DIR} ${SDL2_TTF_INCLUDE_DIR})

#add_subdirectory(shaders)

add_executable(Engine ${SOURCE_FILES} extern/stb_image.cpp src/Camera.h src/Cubes.cpp src/Chart.cpp)
set_target_properties(Engine PROPERTIES LINK_FLAGS "${EMCC_LINKER_FLAGS}")
target_link_libraries(Engine ${FREETYPE_LIBRARIES} ${OPENGL_gl_LIBRARY} ${SDL2_LIBRARY} ${SDL2_IMAGE_LIBRARIES} ${SDL2_TTF_LIBRARIES} glfw glew)
#
#file(GLOB shaders/**/*.glsl shaders/*.glsl)

file(INSTALL shaders DESTINATION .)
file(INSTALL textures DESTINATION .)
#set(CMAKE_EXE_LINKER_FLAGS "${EMCC_LINKER_FLAGS}")
```

But it gives these errors ->

lang: error: unsupported option '--pre-js'
clang: error: unsupported option '--post-js'
clang: error: unsupported option '--preload-file'
clang: error: unsupported option '--preload-file'
clang: error: unsupported option '--use-preload-plugins'
clang: error: no such file or directory: 'SAFE_HEAP=1'
clang: error: no such file or directory: 'WASM=1'
clang: error: no such file or directory: 'LEGACY_GL_EMULATION=0'
clang: error: no such file or directory: 'GL_UNSAFE_OPTS=0'
clang: error: no such file or directory: 'ASSERTIONS=1'
clang: error: no such file or directory: 'GL_ASSERTIONS=1'
clang: error: no such file or directory: 'INVOKE_RUN=0'
clang: error: no such file or directory: 'USE_WEBGL2=1'
clang: error: no such file or directory: 'FULL_ES3=1'
clang: error: no such file or directory: 'USE_GLFW=3'
clang: error: no such file or directory: 'OFFSCREENCANVAS_SUPPORT=1'

It works if I do it like this->

`emcc main.cpp ./src/*.cpp ./extern/*.cpp -o dist/engine.js -g  -s DISABLE_EXCEPTION_CATCHING=0 -s TOTAL_MEMORY=33554432  -s DEMANGLE_SUPPORT=1 -s SAFE_HEAP=1 --bind -s WASM=1 -Os -s LEGACY_GL_EMULATION=0  -s GL_UNSAFE_OPTS=0 --pre-js pre-module.js --post-js post-module.js -s ASSERTIONS=2 -s GL_ASSERTIONS=1 -s INVOKE_RUN=0  -std=c++11 -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_GLFW=3 -s OFFSCREENCANVAS_SUPPORT=1 --preload-file textures --preload-file shaders --preload-file extern --use-preload-plugins "`

I also made a stackoverflow post but no response

https://stackoverflow.com/questions/45260216/emscripten-cmake-pass-emscripten-options-in-cmakelist-file

Thanks!!

**Comment by kripken** [comment]
`clang: error: unsupported option '--post-js'` suggests that clang is being invoked, instead of emcc. Make sure to do `emconfigure cmake .` and `emmake make`. If it's still not working, I'd read the Makefile to see what's going on.

**Comment by DutchKevv** [comment]
Thanks for your reply. I fixed it after posting it on SO. You are right about not using it properly

https://stackoverflow.com/questions/45260216/emscripten-cmake-pass-emscripten-options-in-cmakelist-file
