### ISSUE TITLE
SIDE_MODULE=2 ignores EXPORTED_FUNCTIONS and exports everything (+ no DCE)

### ISSUE THREAD

**Issue by karel-3d** [emscripten-core/emscripten#5419]
When I compile with `SIDE_MODULE=2`, `EXPORTED_FUNCTIONS` seems to be completely ignored, everything is exported and the dead code elimination doesn't work - so everything is always included.

**Comment by kripken** [comment]
Thanks for reporting, looks like this was indeed missing. Fix in #5422.

**Comment by nic-hartley** [comment]
@kripken looks like this is done, maybe it should be closed?

**Comment by kripken** [comment]
Thanks, closing.
