### ISSUE TITLE
rand() implementation not really random

### ISSUE THREAD

**Issue by peppsac** [emscripten-core/emscripten#542]
rand() implementation from library.js exhibits an odd behaviour.

``` C
#include <stdlib.h>
#include <time.h>
#include <stdio.h>
#include <string.h>

int main() {
    #define N 8
    int counter[N], i;
    memset(counter, 0, sizeof(counter));
    srand(time(NULL));

    for (i=0; i<1000; i++) {
        counter[rand() % N]++;
    }

    for (i=0; i<N; i++) {
        printf("%d  ", counter[i]);
    }
    printf("\n");
    return 0;
}
```

Compiling with emcc and executing with "node a.out.js" outputs: 
$ node a.out.js
999  1  0  0  0  0  0  0  
$ node a.out.js
996  4  0  0  0  0  0  0  
$ node a.out.js
999  1  0  0  0  0  0  0

Replacing rand() implementation by 

``` javascript
return Math.random() * 0x7FFFFFFF;
```

produces the correct result.

**Comment by paulshapiro** [comment]
Hi @kripken,

I hear `Math.random` is [not suitable for usage](https://davidgerard.co.uk/blockchain/2018/04/11/javascript-securerandom-isnt-securely-random-most-web-wallets-affected-and-the-bug-was-warned-of-five-years-ago/) in applications which require 'randomness' with a higher number of bits of entropy. `window.crypto` is recommended instead (for which I have some [slightly disorganized code](https://github.com/mymonero/mymonero-core-js/blob/master/cryptonote_utils/mnemonic.js#L136)). Does it make sense to switch away from `Math.random`?

Thanks

**Comment by paulshapiro** [comment]
Actually, I made a mistake. Didn't realize that `crypto` would of course be equivalent to `window.crypto`. However, how about just removing the `Math.random` call and throwing to warn? For my case I shouldn't take the risk.

Thanks!

**Comment by kripken** [comment]
I see what you mean here. However, I think in JS you just need to add 1 line, like
```
Module.random = function() { throw 'unsafe' };
```
Which is easy to add for those that need it, so I think adding an emscripten option is overkill.

**Comment by paulshapiro** [comment]
That's an interesting point. Nice solution. Thanks!

**Comment by paulshapiro** [comment]
@kripken now that I've finally gotten around to actually implementing this, I realize I have a small handful of trivial usages of Math.random that it would be fairly awkward to work around. I have settled on making a 'random' interface fn and having all of them implement it. Not quite optimal.

**Comment by paulshapiro** [comment]
@kripken Turns out our other users are blocked by this too, and the solution of throwing does not work for them. I would like to request that we move the `throw` to emscripten's fallback random case as well. I do not think it's reasonable to fall back to a bad RNG when the device of /dev/random is so generalized and is generally thought to be a good source of entropy.

https://github.com/mymonero/mymonero-core-js/issues/54#issuecomment-417787667

**Comment by kripken** [comment]
Where in emscripten do you need to call your custom random function?

If it's in a function the JS library, then you can just override it with another JS library, for example.

**Comment by paulshapiro** [comment]
@kripken No, it's not that… there's a `Math.random` call as a fallback in [the emscripten implementation of the `random_device`](https://github.com/kripken/emscripten/blob/cd42e9d1da3afae66ddbc57ec009fb00c26c7eb9/src/library_fs.js#L1304) - I think that's unsafe and in any case it must be removed for my cryptographic application, but afaict it would require modifying emscripten's sourcecode or textual replacement in what gets emitted.

**Comment by kripken** [comment]
I see. Yeah, I guess it makes sense to throw there - a PR with that sounds good.

**Comment by msorvig** [comment]
This now trows on modern browsers for me. 

Is the crypto feature detection In library_fs.js correct? It looks for `crypto`,  but I think it should look for `window.crypto`.

**Comment by kripken** [comment]
This regressed, but was fixed in https://github.com/emscripten-core/emscripten/commit/fb03abc13058b0090e9f5a2b1b8c7fb29e0bc8f6 (in 1.38.27).
