### ISSUE TITLE
Duplicate file names in .r with response files

### ISSUE THREAD

**Issue by simondass** [emscripten-core/emscripten#5425]
I seem to have the problem with duplicate files too if using response files.
The issue is in the emar script
`shutil.copyfile(orig_name, full_newname)`
Will fail due to the '@' character in the path so we will not have hashing which can eventually result in linker failure through undefined symbols.
We could do something like change this to
`shutil.copyfile(orig_name.replace(CMAKE_C_RESPONSE_FILE_LINK_FLAG, ''), full_newname)`
and
`full_name = os.path.abspath(orig_name)`
to
`full_name = os.path.abspath(orig_name.replace(CMAKE_C_RESPONSE_FILE_LINK_FLAG, ''))`

I tried this with replacing '@' specifically but don't know how to get CMAKE variables into the script.

See also https://github.com/kripken/emscripten/issues/3731

**Comment by simondass** [comment]
If this seems reasonable I can raise a pull request.

**Comment by kripken** [comment]
cc @juj

**Comment by n0clu3** [comment]
@simondass https://github.com/kripken/emscripten/pull/5505 this fixed the problem for me.
With this change emar takes the list of object files from the response file, add hashes to them similarly to as if they would be passed directly as input files. Then modifies(rewrites) the response file with the paths to the new files.
