### ISSUE TITLE
--shell-file does not work with non-html output

### ISSUE THREAD

**Issue by mittorn** [emscripten-core/emscripten#5428]
i'm trying to preload dynamic library (like dlopen) without placing it to filesystem.
I changed shell_sharedlib.js to register library to the main module automaticly and add fake filename, but i can't specify path to new js file
Is there any alternative to --shell-file for js?

**Comment by kripken** [comment]
I don't understand what you're trying to do. `--shell-file` only works with html because it's purpose is to let you customize the html.

If you want to add some js to load a library, you can use `--pre-js` to create the Module object and any additional setup code you want.

**Comment by mittorn** [comment]
i found that -s SHELL_FILE work now. Will it work in future?

**Comment by kripken** [comment]
Oh, I see, you want to replace the js shell and not the html shell. The names are misleading...

Yeah, that option should stay usable in the future too.

**Comment by mittorn** [comment]
I have main module in html+js  and 3 side modules that need to work as dlopened, but should not be placed to filesystem.
https://github.com/FWGS/microndk/blob/master/shell_fakedynamiclib.js
Other bat thing that i cannot use not-existing settings as macros. Is there some option to define custom macros for javascript and shell preprocessing for better integration with build systems?

**Comment by kripken** [comment]
Do you mean the macros and settings in emscripten that we use with `#if` and `{{{ CONDITION }}}` etc.? Those are internal details in emscripten, they only work inside the compiler.

**Comment by mittorn** [comment]
Yes, i want to preprocess shell, pre and post js files with custom options
