### ISSUE TITLE
Wasm external server

### ISSUE THREAD

**Issue by felipellrocha** [emscripten-core/emscripten#5431]
Hey y'all.

I'm using emscripten to compile my c++ code into wasm. So far, everything works well, but I'm now wrapping everything into a deployable app, and I'm running into a few walls trying to do that.

I have an app that runs on localhost:3000, and my wasm stuff lives on localhost:8000. At first I thought I'd ask the app on 3000 to download the wasm stuff on 8000, but it seems like the js file created `emcc` assumes the app that runs wasm runs on the same domain as the wasm file.

Anyway I can change that?

**Comment by felipellrocha** [comment]
Any updates on this?

**Comment by juj** [comment]
You can use the `Module.locateFile()` function to provide the custom location of the other files. See the documentation http://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile
