### ISSUE TITLE
Webgl offscreen canvas commit problem due to tansfer conversion between worker

### ISSUE THREAD

**Issue by etienne02** [emscripten-core/emscripten#5437]
Hi, I have the offscreencanvas enabled on firefox. But when the emscripten_webgl_commit_frame is called, i get ``emscripten_webgl_commit_frame() failed: OffscreenCanvas is not supported by the current GL context!``. After investigating, i saw that GL.currentContext.GLctx = " [object WebGL2RenderingContext]".  It's a string and so the method commit does not exists.

After more investigating, i saw that the transfer of context transform the object to a string. I put a ``console.log()`` in the receiveObjectTransfer function to see what object is received and the 
data.offscreenCanvas[i] contains a string :  [object OffscreenCanvas] instead of the object OffscreenCanvas.

**Comment by juj** [comment]
To run with  OffscreenCanvas:

1. Use Firefox Nightly and set the pref `gfx.offscreencanvas.enabled` to true in `about:config`. Chrome Canary might have a similar option.
2. Build with the linker flag `-s OFFSCREENCANVAS_SUPPORT=1`: https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L850
3. If rendering is performed on an offscreen thread, pass the ID of the canvas to `emscripten_pthread_attr_settransferredcanvases()` when creating the thread to transfer control of the canvas from main thread to the pthread. Search for that function in Emscripten's `tests/` directory for example code.
3. Create the WebGL context with the attribute `explicitSwapControl=1`: https://github.com/kripken/emscripten/blob/incoming/system/include/emscripten/html5.h#L416. Otherwise implicit swap control will be used.

**Comment by etienne02** [comment]
This is what I did. I'm just not in firefox nightly but the offscreencanvas are suported. I will try with FF nightly.

**Comment by etienne02** [comment]
I have the problem with FF nightly too.

**Comment by juj** [comment]
If none of the above points help, then try running the tests to cross reference. Those work for me without issues.

**Comment by etienne02** [comment]
I reproduce this isssue with this example :

```
#include <stdio.h>
#include <pthread.h>
#include <emscripten.h>
#include <emscripten/html5.h>
#include <emscripten/threading.h>

void* threadFunc(void* arg)
{

	const EmscriptenWebGLContextAttributes attr = {
		.alpha = 1,
		.depth = 1,
		.stencil = 1,
		.antialias = 1,
		.explicitSwapControl = 1,
		.majorVersion = 2,
		.minorVersion = 0,
	};

	EMSCRIPTEN_WEBGL_CONTEXT_HANDLE context = emscripten_webgl_create_context("#canvas", &attr);
	if (context == 0) {
		printf ("error can't create context\n");
		return NULL;
	}
	if (emscripten_webgl_make_context_current(context) != EMSCRIPTEN_RESULT_SUCCESS) {
		printf("error can't make context current\n");
		return NULL;
	}

	EM_ASM("console.log(GL.currentContext);");
	emscripten_webgl_commit_frame();

	emscripten_webgl_make_context_current(0);
	emscripten_webgl_destroy_context(context);

	return NULL;
}

int main()
{

	pthread_t pth;
	pthread_attr_t attr;

	pthread_attr_init(&attr);
	emscripten_pthread_attr_settransferredcanvases(&attr, "#canvas");
	pthread_create(&pth, &attr, threadFunc, NULL);

	return 0;
}
```
I compile with ``` emcc -s USE_PTHREADS=1 -s NO_EXIT_RUNTIME=1 -s OFFSCREENCANVAS_SUPPORT=1 -s USE_WEBGL2=1 -s FULL_ES2=1 -s GL_ASSERTIONS=1 -s GL_DEBUG=1 thread.c -o experimental.html --emrun```

and when I run, in firefox console i have the message for the commit function. And I do a console.log to show that the ``GL.currentContext.GLctx`` is a string instead of an object.

**Comment by etienne02** [comment]
I tested with google chrome and I have not the bug. It's seem to be a Firefox bug

**Comment by juj** [comment]
Thanks for the good test case. It looks like the relevant bit in Firefox Nightly is that WebGL 2 is not working with OffscreenCanvas. If I change the above test case to initialize a WebGL 1 context, then the example works. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1388299 about this.

Let's keep this bug report open to remind to add a test case of WebGL 2 + OffscreenCanvas to Emscripten unit test suite.
