### ISSUE TITLE
Optimize function aliases in JS libraries

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#5444]
Currently when one does things like

```javascript
    func1: function(a, b) {
      return a + b;
    },
    alias_to_func1: 'func1',
```

To duplicate `func1` as `alias_to_func1`, we generate the following:

```javascript
function func1(a, b) {
  return a + b;
}
function _alias_to_func1() {
  return _func1.apply(null, arguments)
}
```

This is (relatively) inefficient because of referring to `.apply()` and `arguments`, which both have been sources of perf issues in hot paths. A faster form would be to recognize the arguments and emit

```javascript
function func1(a, b) {
  return a + b;
}
function _alias_to_func1(a, b) {
  return _func1(a, b);
}
```

or would it be possible to just do like this?

```javascript
function func1(a, b) {
  return a + b;
}
var _alias_to_func1 = _func1;
```

**Comment by nazar-pc** [comment]
#5463 optimizes exports like this:
```javascript
var _sbrk = Module["_sbrk"] = function() { return Module["asm"]["_sbrk"].apply(null, arguments) };
```

So that direct assignment is used instead of `.apply()`, exports could potentially work a bit faster.
