### ISSUE TITLE
sendmsg function has a bug

### ISSUE THREAD

**Issue by avfounder** [emscripten-core/emscripten#5445]
emscripten version 1.37.18

in output js sendmsg: function
"data = buffer.buffer.slice(buffer.byteOffset + offset, buffer.byteOffset + offset + length); " is wrong.
"data = buffer.slice(buffer.byteOffset + offset, buffer.byteOffset + offset + length);" is correct.

please fix.

**Comment by juj** [comment]
In `src/library_sockfs.js`, I see

```javascript
        // create a copy of the incoming data to send, as the WebSocket API
        // doesn't work entirely with an ArrayBufferView, it'll just send
        // the entire underlying buffer
        var data;
        if (buffer instanceof Array || buffer instanceof ArrayBuffer) {
          data = buffer.slice(offset, offset + length);
        } else {  // ArrayBufferView
          data = buffer.buffer.slice(buffer.byteOffset + offset, buffer.byteOffset + offset + length);
        }
```

https://github.com/kripken/emscripten/blob/incoming/src/library_sockfs.js#L587

I'm not sure outright what is wrong. Could you create a test case that showcases the issue?

**Comment by avfounder** [comment]
For example, when buffer [buffer.byteOffset + offset, buffer.byteOffset + offset + length] is "aaa", after "data = buffer.buffer.slice(buffer.byteOffset + offset, buffer.byteOffset + offset + length);", data is "[object sharedBufferArray]". But if after "data = buffer.slice(buffer.byteOffset + offset, buffer.byteOffset + offset + length);", data is "aaa". This was tested with a libwebsockets based server and in emscripten , i just call a function sequece "socket/connect/poll/send".
I will give you the test case next tormorrow, because tomorrow I must take my baby to hospital and sorry about that.
