### ISSUE TITLE
redirecting incorrect #include <sys/poll.h> to <poll.h> , compilation failed

### ISSUE THREAD

**Issue by DimTheo** [emscripten-core/emscripten#5447]
![screenshot from 2017-08-08 23-45-24](https://user-images.githubusercontent.com/17296068/29093773-aebe66ec-7c93-11e7-8574-f4cbeb1f36d1.png)

I'm trying to compile MAME (https://github.com/mamedev/mame) but this is what I get. The first time I tried to compile, it converted, compressed, compiled some stuff, then it threw this error. Now every time I try to compile, I get the same error right away.

I haven't run ./configure by the way,  because I can't figure a proper way to do it.

**Comment by kripken** [comment]
It says "gcc 5.4.0 detected" which I think means it is not using emcc. So it is compiling using the wrong compiler, and you may need to run a configure script or something like that. Might be best to ask the MAME project directly, I believe their emscripten port is upstream (another possible place is the jsmess irc channel on EFNet, some people working on that port are usually there i believe).

**Comment by DopefishJustin** [comment]
The GCC message is not meaningful, the MAME build system prints it even when compiling under Emscripten and I haven't bothered figuring out why.

The poll.h error on the other hand is real and I get it as well. It can be worked around by adding NOWERROR=1 to the make command line.

**Comment by DimTheo** [comment]
Un-commenting NOWERROR=1 in the makefile of the mame directory solved the problem.
Thank you for your help.

**Comment by juj** [comment]
The history of that warning is that at least [POSIX.1-2001, POSIX.1-2008](http://man7.org/linux/man-pages/man2/poll.2.html) and [Single Unix Specification](http://www.unix.org/version2/) (at http://pubs.opengroup.org/onlinepubs/7908799/xsh/poll.h.html) state that the include directive should be `#include <poll.h>`.

Looking at Android's implementation, there exist both `sys/poll.h`, and `poll.h`, where `poll.h` includes to `sys/poll.h` without issuing a warning:

https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/jb-dev/sysroot/usr/include/sys/poll.h
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/jb-dev/sysroot/usr/include/poll.h

Perhaps we should then just drop the warning as well, it looks a bit pedantic in nature, given that other platforms support the nonstandard(?) `#include <sys/poll.h>` in addition to `#include <poll.h>`.

**Comment by juj** [comment]
Oh, on other thought, it looks like that warning is not an Emscripten-specific added warning, but comes directly from upstream musl: https://git.musl-libc.org/cgit/musl/tree/include/sys/poll.h. So perhaps we don't want to change this then.

Would it be possible for MAME to change to using the standard(?) `#include <poll.h>` instead of `#include <sys/poll.h>`? What motivates `#include <sys/poll.h>` ? I wonder if there is some other BSD or other related standard that has `sys/poll.h` instead?

**Comment by DopefishJustin** [comment]
It's not MAME code, it comes from upstream asio. It seems to have recently been fixed there so we should be able to just update: https://github.com/chriskohlhoff/asio/commit/5adce6e26769228f2c9fcc0b9dda8bf00279821f

**Comment by DopefishJustin** [comment]
The commit mentioned above does not actually fix the problem for Emscripten but I have created a pull request that does: https://github.com/chriskohlhoff/asio/pull/260
