### ISSUE TITLE
Module['_sbrk'] reassignment

### ISSUE THREAD

**Issue by nazar-pc** [emscripten-core/emscripten#5461]
With `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[] -s WASM=1` the code I'm getting contains following piece:
```javascript
  function ___setErrNo(value) {
      if (Module['___errno_location']) HEAP32[((Module['___errno_location']())>>2)]=value;
      return value;
    } 
  Module["_sbrk"] = _sbrk;
DYNAMICTOP_PTR = allocate(1, "i32", ALLOC_STATIC);

STACK_BASE = STACKTOP = Runtime.alignMemory(STATICTOP);

STACK_MAX = STACK_BASE + TOTAL_STACK;
....
var _sbrk = Module["_sbrk"] = function() { return Module["asm"]["_sbrk"].apply(null, arguments) };
```

In particular I'm interested in `Module["_sbrk"] = _sbrk;` piece and `var _sbrk = Module["_sbrk"]` few lines below it.

I've tried to find where it comes from and why is even needed. It comes from [this line](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/emscripten.py#L506), from `metadata['declares']`, then through [this line](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/src/jsifier.js#L78) it gets printed [here](https://github.com/kripken/emscripten/blob/3858294f58b2baa03108d08494e837b4ef10d3fd/src/jsifier.js#L388).

Can anyone tell me why is it there and why needed?
For me it doesn't make any sense.

I'm working on a way to reduce build size a bit, but this piece causes issues with final build, since after changes I'm doing `var _sbrk` is not present anymore (while `Module["_sbrk"]` is still there). Since `_sbrk` is not used anywhere else, I'd like to make it disappear.

**Comment by nazar-pc** [comment]
This is not funny. When compiling with `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[] -s WASM=1 -s "BINARYEN_METHOD='interpret-asm2wasm'"` I'm getting multiple useless constructions like following (copied with exact spaces and order as in compiled code):
```
...
Module["_bitshift64Ashr"]=_bitshift64Ashr;
...
var _bitshift64Ashr=Module["_bitshift64Ashr"]=asm["_bitshift64Ashr"];
...
Module["_bitshift64Ashr"] = _bitshift64Ashr;
...
var _bitshift64Ashr = Module["_bitshift64Ashr"] = asm["_bitshift64Ashr"];
...
```

It doesn't make any sense to reassign the same stuff back and forth.

https://github.com/kripken/emscripten/compare/incoming...nazar-pc:functions-export-optimization?expand=1 implements everything (I believe so) necessary to export all of the functions with any method. Now I'd like to remove all of those redundant constructs, but need additional information why are they present in the first place.

**Comment by juj** [comment]
`sbrk` forms the foundation of the memory allocator in Linux processes, and it operates on an even lower level than `malloc`. `malloc` is built on top of `sbrk`, and whereas malloc allows allocating and freeing individual blocks of memory in independent orders, `sbrk` only has a notion of linearly growing or shrinking the "ceiling" of the used dynamic memory region of the process. It is possible to compile applications with `malloc` and `free` and use one's own memory allocator, but building without `sbrk` is not possible, since Emscripten's memory layout on the dynamic heap is built on top of that, and it also manages growing and shrinking WebAssembly memory buffer space.

Most of the `Module['foo'] = foo;` constructs come from the need to export functions in the presence of code minifiers, since in minified code, the function names will be something like `Module['foo']=Aa` and then would otherwise be inaccessible.

However the duplicate export seems like a bug. I am no sure why those would be present twice, but if we can remove the duplicate accounts, that would be good.

**Comment by nazar-pc** [comment]
I have nothing about `_sbrk` itself, it was just an example of exported function (thanks for details about it though!).

My point is that `Module['foo']=Aa` is basically unnecessary as soon as we have `Module['foo']` already (which shouldn't be mangled by minifier when quotes are used). And for this we only need to copy all of the functions from `Module['asm']` to `Module` itself (when `Module['asm']` is constructed).

This would mean that for functions that are exported, but not used for Emscripten's internals/runtime/whatever, we'll only have a since instance of its full name in `*.asm.js` or `*.wasm` file, no need to enumerate all of them explicitly in the source code.

I'll try to cut the relevant pieces that generate said code and then will ask you or other maintainers to cleanup all of that if it looks reasonable.

**Comment by nazar-pc** [comment]
Looks like first 2 parts come from Binaryen directly, which in turn seems to be compiled by Emscripten. So #5463 eliminates `var _sbrk = Module["_sbrk"]`-like pieces, but I'm not really sure what to do with `Module["_bitshift64Ashr"] = _bitshift64Ashr;`-like parts. I've tracked down where part of those things come from previously, but have no idea why.

Here is an excerpt of redundant code with context:
```javascript
// {{PRE_LIBRARY}}


   
  Module["_bitshift64Ashr"] = _bitshift64Ashr;

   
  Module["_bitshift64Lshr"] = _bitshift64Lshr;

  
   
  Module["___muldsi3"] = ___muldsi3; 
  Module["___muldi3"] = ___muldi3;

   
  Module["_i64Add"] = _i64Add;

  
  function ___setErrNo(value) {
      if (Module['___errno_location']) HEAP32[((Module['___errno_location']())>>2)]=value;
      return value;
    } 
  Module["_sbrk"] = _sbrk;

   
  Module["_bitshift64Shl"] = _bitshift64Shl;

   
  Module["_i64Subtract"] = _i64Subtract;
DYNAMICTOP_PTR = allocate(1, "i32", ALLOC_STATIC);
```

By the time assignment happens, those variables are `undefined`, and when they are defined, `Module`'s properties are defined as well, so it doesn't make any sense to me to have those assignments.

**Comment by kripken** [comment]
Yes, I think those are not needed - some old code probably includes them and it wasn't noticed. Would be good to fix. I would suggest looking in jsifier.js and emscripten.py, those assigns to Module are in one of those, and modifying things to find where those assignments are, then seeing if something breaks when they are removed.

**Comment by nazar-pc** [comment]
New closure compiler also complains about these lines like so:
```
supercop.bc.o.js.mem.js:192287 (JSC_REFERENCE_BEFORE_DECLARE)
Variable referenced before declaration: _bitshift64Ashr
  Module["_bitshift64Ashr"] = _bitshift64Ashr;
                              ^

supercop.bc.o.js.mem.js:192290 (JSC_REFERENCE_BEFORE_DECLARE)
Variable referenced before declaration: _bitshift64Lshr
  Module["_bitshift64Lshr"] = _bitshift64Lshr;
                              ^

supercop.bc.o.js.mem.js:192294 (JSC_REFERENCE_BEFORE_DECLARE)
Variable referenced before declaration: ___muldsi3
  Module["___muldsi3"] = ___muldsi3; 
                         ^

supercop.bc.o.js.mem.js:192295 (JSC_REFERENCE_BEFORE_DECLARE)
Variable referenced before declaration: ___muldi3
  Module["___muldi3"] = ___muldi3;
                        ^

supercop.bc.o.js.mem.js:192298 (JSC_REFERENCE_BEFORE_DECLARE)
Variable referenced before declaration: _i64Add
  Module["_i64Add"] = _i64Add;
                      ^
```

Will make another PR on top of #5463
