### ISSUE TITLE
EMSCRIPTEN_KEEPALIVE doesn't work with static libraries

### ISSUE THREAD

**Issue by vvuk** [emscripten-core/emscripten#5465]
I've got a project that has a number of modules; each module has some `EMSCRIPTEN_KEEPALIVE` decorated functions.  That decoration is lost if each module's object files are combined into a static library, and that library referenced in the final link.  If the direct object files are used, things work fine.

Any chance of making `EMSCRIPTEN_KEEPALIVE` work even in static libraries?

**Comment by juj** [comment]
Are your static libraries `.bc` or `.a`? The semantics differ between linking the two, i.e. linking `.bc` files should be a dumb "append all symbols", whereas linking `.a` is a "fulfill only the missing symbols". I wonder if `EMSCRIPTEN_KEEPALIVE` behaves differently between these two.

**Comment by vvuk** [comment]
Yeah I guessed as much -- they're `.a` (created via cmake's `STATIC` libraries).  With a bit of work I could probably make `.bc` files...

**Comment by juj** [comment]
There exists a CMake directive https://github.com/kripken/emscripten/blob/master/cmake/Modules/Platform/Emscripten.cmake#L172 to make CMake treat all static libraries to be `.bc` files, although whether that works probably depends wildly on the overall linking structure of the project. It should be possible to do that on a per library basis though in CMake.

**Comment by kripken** [comment]
Yeah, I think `.a` linking is the issue here. Keepalive marks the function as used, but if `.a` linking rules don't even bring in that file, it doesn't get a chance to work.

I think this is how native linking works too, but that might be worth verifying.

**Comment by glenne** [comment]
`set (EMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES TRUE)` worked for me to link without error.

**Comment by sbc100** [comment]
Yes, this is how .a archive work so I think is WAI.

**Comment by hanseuljun** [comment]
Is there a way currently available to expose functions in a static library using EMSCRIPTEN_KEEPALIVE?

Unfortunately, EMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES is no longer supported...
https://github.com/emscripten-core/emscripten/blob/0fbf9cf10f6359770c43cc43386af093b6a4df2c/cmake/Modules/Platform/Emscripten.cmake#L280

EXPORTED_FUNCTIONS does work but I would like to know if there is a better way to expose dozens of functions!

**Comment by sbc100** [comment]
Yes, you can wrap `-Wl,--whole-archive` .. `-Wl,--no-whole-archive` around the library.  See https://stackoverflow.com/questions/7253801/how-to-force-symbols-from-a-static-library-to-be-included-in-a-shared-library-bu

**Comment by hanseuljun** [comment]
Thank you so much for a super quick reply!! I'll look in to it!!

**Comment by hanseuljun** [comment]
It worked!!! Yay no more copy pasting function names to the CMake file!!!
