### ISSUE TITLE
Strange function names in .js file

### ISSUE THREAD

**Issue by newnon** [emscripten-core/emscripten#5479]
i have got many functions with names like this __GLOBAL__sub_I_CCBXWidget_stdout_SergeyMac_local_31770_9RBGyO_ii
in every function is name of machine on which it was builded 
and even if project builded with same version from same sources every time i got different binary

**Comment by juj** [comment]
That does look odd. Can you find the definition of some of those symbols? I wonder if there could be some preprocessor macro that creates them, or some mistaken name in C++ constructors that adds these in.

**Comment by newnon** [comment]
it looks like it is some static initializers but i can't find what exactly generates this
