### ISSUE TITLE
whether emscripten only supports 32-bit compilation?

### ISSUE THREAD

**Issue by ZhangQP** [emscripten-core/emscripten#5485]
When I build project libpmem ( https://github.com/pmem/nvml    libpmem is in nvml/src/libpmem) with command 'emmake make' without configure (according to the emscripten wiki, the configure process can be omitted), a problem appears that '32-bit builds of NVML are not supported, please use 64-bit platform/compiler'. I find at   https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#detecting-emscripten-in-preprocessor  , the forth point from bottom says that emscripten is a 32-bit platform.
The OS is Ubuntu 16.04, and the emscripten version is emsdk-portable.
So my question is, how should I solve this problem? Whether emscripten supports 64-bit compilation? If no, why there are many big projects based on wasm, which I think should be 64-bit?

**Comment by ZhangQP** [comment]
I run the project on Ubuntu 16.04 with emscripten version 'emsdk-portable'

**Comment by juj** [comment]
Both asm.js and WebAssembly standards are 32-bit architectures, so pointers are 32-bits wide and address space is limited to about 2 GB. In WebAssembly spec, design documents and GitHub, you may see off mentions about a "wasm64", which is a future planned expansion that would migrate WebAssembly to 64-bit.

Your best bet is to port the library to work again on 32-bit. Not sure what their reason with no longer working on 32-bit is, but perhaps that limitation can be lifted by working on the project.

**Comment by ZhangQP** [comment]
Sorry, I don't understand why 32-bit address space is not 2^32=4GB. And the project is designed to work on Non-volatile memory, both 2GB and 4GB are actually not suitable, I think that is why the library can't work on 32-bit. So now it's a dilemma for me.

**Comment by juj** [comment]
> Sorry, I don't understand why 32-bit address space is not 2^32=4GB.

JavaScript Typed Arrays are limited to maximum size being < 2^31 bytes, which is why it is not possible to allocate a larger array. Undoubtedly in the future Wasm will evolve to 64-bit, but the standard is not there yet.
