### ISSUE TITLE
Problem with special character folders

### ISSUE THREAD

**Issue by mockthebear** [emscripten-core/emscripten#5490]
I just installed emscripten as usual but was not working.

`E:\zkripten>em++ -v
Traceback (most recent call last):
  File "E:\zkripten\emscripten\1.37.1\\em++", line 13, in <module>
    import emcc
  File "E:\zkripten\emscripten\1.37.1\emcc.py", line 32, in <module>
    from tools import shared, jsrun, system_libs
  File "E:\zkripten\emscripten\1.37.1\tools\shared.py", line 207, in <module>
    raise Exception('File ' + EM_CONFIG + ' passed to --em-config does not exist!')
Exception: File C:\Users\Usu▀rio\.emscripten passed to --em-config does not exist!
`

Then i noticed...

`Exception: File C:\Users\Usu▀rio\.emscripten passed to --em-config does not exist!`

"\Usu▀rio" means to be "Usuário".

I cant compile anything or even run an simple command because of that.

**Comment by juj** [comment]
Try out latest Emscripten 1.37.19, I recall doing some unicode path fixes not too long ago, but 1.37.1 probably didn't yet have those.

**Comment by mockthebear** [comment]
`# Install git. Skip if the system already has it.
./emsdk install git-1.8.3

# Clone+pull the latest kripken/emscripten/incoming.
./emsdk install sdk-incoming-64bit

# Set the "incoming SDK" as the active version.
./emsdk activate sdk-incoming-64bit`

I did this. And i got the same error.

`    raise Exception('File ' + EM_CONFIG + ' passed to --em-config does not exist!')
Exception: File C:\Users\Usu▀rio\.emscripten passed to --em-config does not exist!`
