### ISSUE TITLE
emar : add --help option

### ISSUE THREAD

**Issue by etienne02** [emscripten-core/emscripten#5501]
I tried to use emar, but it was not easy. So i tried emar --help but it does nothing, the option is not existing. The help appear when we do a wrong usage of emar, but its not really clear. Finaly i got to see the source code to know how to use emar (for me `emar r archive.a all_files.a`)

**Comment by juj** [comment]
`emar` is intended to be equal to `llvm-ar`, so the docs here should work: https://llvm.org/docs/CommandGuide/llvm-ar.html. llvm-ar itself is a compatible copy of GCC ar: https://sourceware.org/binutils/docs/binutils/ar-cmdline.html

Though there are probably some Emscripten specific adaptations, agree about adding docs for that.
