### ISSUE TITLE
Move Browser.init() from library_fs.js

### ISSUE THREAD

**Issue by nazar-pc** [emscripten-core/emscripten#5511]
There is this line https://github.com/kripken/emscripten/commit/5f0918409a1407dd168f57cfa34b109cd1770a8a#diff-349daa47efec0b4193bc556a841c6920R1762 in library_fs.js that appears to be the only place mentioning `Browser` anywhere in some builds, so with `Browser` not being defined it shouldn't be called anyway.

This makes Closure Compiler complaining about undefined variable (just warning, but still). I have no idea why is it there and what it does, but comment says it can be moved from there, so this is an issue to track just that.

**Comment by halfnelson** [comment]
Just got bitten by this. And a strange bug where even adding  `-s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE="['$Browser']"` was not getting browser into my wasm module on OSX (but does work fine on windows)
