### ISSUE TITLE
Proper support of «-s TOTAL_MEMORY» for standalone WebAssembly.

### ISSUE THREAD

**Issue by Joffrey** [emscripten-core/emscripten#5523]
For historical reasons, «-s TOTAL_MEMORY» cannot be set under 16 MB. It could be a really waste for some lightweight Web app in the case of a standalone WebAssembly app (-S SIDE_MODULE 1 -S WASM=1).
We should be able to put a small amount of memory.

**Comment by dasa** [comment]
I'd also like to be able to set the `TOTAL_MEMORY` to be less than 16 MB.
