### ISSUE TITLE
embinded class export missing (by dead code elimination?)

### ISSUE THREAD

**Issue by kwonoj** [emscripten-core/emscripten#5537]
I maybe doing something stupid but couldn't figure out myself, so would like to ask some help.

I've exported one class via embind, as below:
```
  EMSCRIPTEN_BINDINGS(cld3) {
    class_<chrome_lang_id::NNetLanguageIdentifier>("NNetLanguageIdentifier")
      .constructor<int, int>()
      .class_property("kMinNumBytesToConsider", &chrome_lang_id::NNetLanguageIdentifier::kMinNumBytesToConsider)
      .class_property("kMaxNumBytesToConsider", &chrome_lang_id::NNetLanguageIdentifier::kMaxNumBytesToConsider)
      .class_property("kMaxNumInputBytesToConsider", &chrome_lang_id::NNetLanguageIdentifier::kMaxNumInputBytesToConsider)
      .class_property("kReliabilityThreshold", &chrome_lang_id::NNetLanguageIdentifier::kReliabilityThreshold)
      .class_property("kReliabilityHrBsThreshold", &chrome_lang_id::NNetLanguageIdentifier::kReliabilityHrBsThreshold)
      .function("FindLanguage", &chrome_lang_id::NNetLanguageIdentifier::FindLanguage)
      .function("FindTopNMostFreqLangs", &chrome_lang_id::NNetLanguageIdentifier::FindTopNMostFreqLangs)
      ;
}
```
and build it via emcc, 
```
em++ \
-O3 \
-Oz \
--llvm-lto 1 \
-s MODULARIZE=1 \
-s NO_EXIT_RUNTIME=1 \
-s ERROR_ON_UNDEFINED_SYMBOLS=1 \
--bind \
./.libs/libprotobuf.bc \
./libcld3.a \
--pre-js ./preprocessor.js \
```

and output does not contains exported class in module. 

If I created dummy fn to hold reference of class only
```
  void dummy() {
    chrome_lang_id::NNetLanguageIdentifier* dummy;
    throw "should not be called";
  }
```

and export it explicitly via `-s EXPORTED_FUNCTIONS="['_dummy']" `, then embinded class also exported as well. This makes me guess if this is somehow related with dead code elimination, but couldn't figure out how to prevent this. Am I missing some configurations? Repo I've used for this is at https://github.com/kwonoj/docker-cld3-wasm/tree/master/build, specifically https://github.com/kwonoj/docker-cld3-wasm/blob/master/build/build.sh / https://github.com/kwonoj/docker-cld3-wasm/blob/master/build/embind.patch .

**Comment by AlexPerrot** [comment]
I've had a similar issue.
Based on the repository you linked, I assume your binding are in `libcld3.a`.
IIRC, linking `.a` archives only links used symbols, so bindings should be defined in a `.bc` file, since by definition they are not used in the compiled code.

**Comment by bzz** [comment]
Was anyone able to figure out, why -O3 removes the embinded code?

Trick with `_dummy()` does not work for me, in case when a function is binded instead of a class.

**Comment by bzz** [comment]
It might be a different case of binding a class vs a single function, but 
 - after careful re-reading of https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process 
- and following https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions 

by building \w `-s MODULARIZE=1 -s 'EXPORT_NAME="CLD3"'`,  an example of `
```js
CLD3().langId(utf.encode(text))
```

works for me.
