### ISSUE TITLE
WebAssembly.Memory max memory

### ISSUE THREAD

**Issue by Avatarchik** [emscripten-core/emscripten#5559]
Hi! Can I use 2g of memory? When initializing 
var memory = new WebAssembly.Memory ({
            initial: 16384,
            maximum: 65535
        });
only 1024 mb does not give up anymore, it gives an error if I indicate initial: 32768

**Comment by kripken** [comment]
You may be hitting a current browser limitation or bug. Which browser is that in?

**Comment by Avatarchik** [comment]
Chrome (x64) 60.0.3112.113  and Firefox(x64) 55.0.3

**Comment by juj** [comment]
The limitation here is that you cannot initially allocate such a large memory block, but you can later grow to such large sizes. I think this was made to prevent applications from blindly hogging all memory they can get, but encourage them to gracefully reserve the memory by setting a maximum, and then growing to raise the needed usage.

**Comment by Avatarchik** [comment]
I'm using Unity3d, there is an initialization of the form:
```
  var TOTAL_STACK = 5242880;
        var TOTAL_MEMORY = 2130706432;

        var WASM_PAGE_SIZE = 64 * 1024;

        var totalMemory = WASM_PAGE_SIZE;
        while (totalMemory < TOTAL_MEMORY || totalMemory < 2 * TOTAL_STACK) {
            if (totalMemory < 16 * 1024 * 1024) {
                totalMemory *= 2;
            } else {
                totalMemory += 16 * 1024 * 1024;
            }
        }
        if (totalMemory !== TOTAL_MEMORY) {
            TOTAL_MEMORY = totalMemory;
        }

        var memory = new WebAssembly.Memory({
            initial: TOTAL_MEMORY / WASM_PAGE_SIZE,
            maximum: TOTAL_MEMORY / WASM_PAGE_SIZE
        });
```


In the new version of chrome 61.0.3163.79, it works and allocates 2gb, but firefox 55.0.3 error "RangeError: bad Memory initial size"

**Comment by kripken** [comment]
Checking with the browsers, there is a current limitation in firefox of the initial size being <2GB. So you should be able to allocate an initial size of 2GB - 64K (one wasm page size).

Do you even need to allocate that size initially, though? As @juj said, you can grow memory to 4GB, that should work ok in all browsers. It's best in wasm to use memory growth and to have the initial allocation be as small as possible.

**Comment by juj** [comment]
> As @juj said, you can grow memory to 4GB

In Firefox the maximum size one can grow to is 2GB - 64KB, and the maximum initial size is somewhere around 1GB. Firefox does not support 4GB Wasm memory (https://bugzilla.mozilla.org/show_bug.cgi?id=1392234). Chrome 64-bit does not seem to support 2GB-64KB Wasm memories even, but (still) Awwsnap-crashes the content process.
