### ISSUE TITLE
Embind + pthreads

### ISSUE THREAD

**Issue by llchan** [emscripten-core/emscripten#5584]
It seems that the embind machinery is only called on the main thread, and adding the `class_<T>(...)` calls inside the thread succeeds in registering those classes, but the builtins are still missing. Can we make `--bind` mode inject all its stuff into the `pthread-main.js` script too? Or is there a more idiomatic way to do this?

If this is nontrivial I could just wrap my stuff with a C API.

**Comment by kripken** [comment]
Looks like we filed a duplicate of this later, but there is more discussion there, so closing in favor of that one, https://github.com/emscripten-core/emscripten/issues/8299
