### ISSUE TITLE
Embind: private destructors

### ISSUE THREAD

**Issue by dasa** [emscripten-core/emscripten#5587]
The class I'm trying to use has a private destructor so the error I'm getting is: 

`bind.h:452:20: error: calling a private destructor of class 'X'`

Is there a workaround for this?

The class does have a `Delete` method, so maybe an option similar to [External constructors](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#external-constructors) would work. 

Another use case could be for singletons as discussed here: https://github.com/pybind/pybind11/issues/114#issuecomment-242585000

This [thread](https://groups.google.com/forum/#!topic/emscripten-discuss/F1U123cLVMg) from 2014 is the only prior discussion I could find on this topic.

**Comment by dasa** [comment]
@kripken - can you please give this the `embind` label?

**Comment by kripken** [comment]
Added.

**Comment by AlexPerrot** [comment]
I think there currently is no way to use an external or private destructor with embind.
You're welcome to try and add the functionality :)

**Comment by Zubnix** [comment]
Is there a way to work around this error?  (I get `error: 'operator delete' is a private member`)

**Comment by prideout** [comment]
To avoid this error, you can replace emscripten's default definition of `raw_destructor` by using explicit template instantiation:

```
namespace emscripten {
    namespace internal {
        template<> void raw_destructor<MyClass>(MyClass* ptr) { /* do nothing */ }
    }
}
```

Watch out for leaks though!
