### ISSUE TITLE
support EXTRA_EXPORTED_RUNTIME_METHODS for "GL"

### ISSUE THREAD

**Issue by irov** [emscripten-core/emscripten#5592]
postamble.js
{{{ maybeExport('FS') }}}
{{{ maybeExport('GL') }}} <-- add?

**Comment by kripken** [comment]
What is your use case - what are you doing, that this would help?

**Comment by irov** [comment]
gl = canvas.getContext("webgl2");
      var webGLContextAttributes = {}
      webGLContextAttributes['majorVersion'] = 2;
      webGLContextAttributes['minorVersion'] = 0;
      console.log(movie.GL)
      var glctxhandle = movie.GL.registerContext(gl, webGLContextAttributes);
      movie.GL.makeContextCurrent(glctxhandle)

something like that

**Comment by kripken** [comment]
I see. Yeah, that makes sense to do. Would you like to open a PR with that change?

**Comment by irov** [comment]
i create PR
https://github.com/kripken/emscripten/pull/5609
