### ISSUE TITLE
Errors with compiling with the GNU Scientific Library

### ISSUE THREAD

**Issue by kleingeo** [emscripten-core/emscripten#5601]
I have been wanting to use the GNU Scientific Library (GSL) with emscripten. I downloaded GSL and have been trying to compile it, but I have no luck.  This is the error I have been getting. I am not entirely sure why the error is with python files though. 

C:\EMSDK>cd C:\GSL\gsl-2.4

C:\GSL\gsl-2.4>emconfigure ./configure
ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure"!
Traceback (most recent call last):
  File "C:\EMSDK\emscripten\1.37.21\\emconfigure", line 13, in <module>
    emconfigure.run()
  File "C:\EMSDK\emscripten\1.37.21\emconfigure.py", line 46, in run
    shared.Building.configure(sys.argv[1:])
  File "C:\EMSDK\emscripten\1.37.21\tools\shared.py", line 1533, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "C:\EMSDK\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\EMSDK\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by kripken** [comment]
Does the project build without emscripten using that method? That is, does normal `./configure` for a native build work?

**Comment by gaklein2007** [comment]
Ya, it works with that. I use cygwin and it configures fine with it.

**Comment by kripken** [comment]
Might be a cygwin issue then. I don't know much about it. The error says `Exception thrown when invoking Popen in configure with args: "./configure"!` - maybe that fails in python even though it works when you write it in the cygwin shell?

**Comment by gaklein2007** [comment]
I don't think it has to do with cygwin. This error came up before I started using it. I tried cygwin afterwards to see if it could even configure using a normal gcc compiler, which it could.

**Comment by kripken** [comment]
And you get the same error in and out of cygwin? Very strange. Might add some debug printouts in those python files, to see what's going wrong.

**Comment by gaklein2007** [comment]
Ya. I'm not entirely sure. And I'm also not sure why it's using python code at all. Is it thinking that the library is in python instead of C, or are those python commands doing the transpiling?

**Comment by kripken** [comment]
That python is emscripten's code, emconfigure itself is written in python.
