### ISSUE TITLE
Optimize WebAssembly dynamic linking

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#5602]
This mostly works now, but many things should be improved, as this was basically a direct port of the asm.js support we had, which was hackish and also limited by asm.js in ways wasm isn't.

In particular we should use emulated function pointers, make sure we don't export unnecessary things, don't use unnecessary thunks, etc.

Sub-bugs:
 * https://github.com/kripken/emscripten/issues/5586

**Comment by dschuff** [comment]
Projects are pretty easy. I created one at https://github.com/kripken/emscripten/projects/2
You can add bugs to projects on the bug page, or from the project page, and stick them in a column (where columns can have whatever name and meaning you want). In the simplest case, it's just a list of bugs.

**Comment by kripken** [comment]
Thanks, I added the issues so far to there. Took me a while to figure out the only way is to drag&drop from the right in the UI there ;)

**Comment by dschuff** [comment]
Yeah, that part is... not the best.

**Comment by gopal1022** [comment]
I cannot Find your project on Dynamic Linking.
Can you please provide the link.
@kripken

**Comment by kripken** [comment]
@gopal1022 here: https://github.com/kripken/emscripten/projects/2
