### ISSUE TITLE
Emscripten + MSBuild

### ISSUE THREAD

**Issue by Foxsa** [emscripten-core/emscripten#5613]
Can I use emscripten with MSBuild and without Visual Studio?
I have installed emsdk according to manual but no luck. 
I`ve got error like:
```
error MSB8020: The build tools for emcc (Platform Toolset = 'emcc') cannot be found
```

**Comment by juj** [comment]
That is a combination that I have never tried. I presume if there is a good plugin architecture, it could be enabled, but I am not familiar enough with that.

I did do a research prototype implementation of Emscripten+CMake+Visual Studio solutions a couple of years back, where one could use MSBuild to build these .sln/.vcxproj files. That was not upstreamed to CMake at the time however.

I am not sure what the difference would be to not having Visual Studio at all, but just MSBuild - that is a configuration I haven't used before. If there exists some kind of Platform Toolset plugin development guide for MSBuild(?), then perhaps someone would be able to contribute this kind of support. Fundamentally there is nothing special that Emscripten needs to consider, the build structure is very traditional compile and link -based, and is GCC compatible. If someone has created a GCC or a Clang plugin to MSBuild, then that could likely also be adapted for an emcc plugin.

**Comment by wangchow** [comment]
I have been using it on my project for initial development. So far I have had success. I have instructions on my gitlab page:
https://gitlab.com/wangchow/wungchungery

One thing that I am working through now is getting the file-system to mount a NODEFS into the virtual file system properly.
