### ISSUE TITLE
Compiled asm.js double declaration error

### ISSUE THREAD

**Issue by czizzy** [emscripten-core/emscripten#5615]
C code:
```
double add(double a, double b) {
  return a + b;
}
```
Compile with this command:
```emcc --separate-asm -O1 -s ONLY_MY_CODE=1 -s EXPORTED_FUNCTIONS="['_add']" test.c -o test.asm.js```

Compiled AsmJS code:
```
Module["asm"] = (function(global, env, buffer) {
 "use asm";
 var STACKTOP = env.STACKTOP | 0;
 function _add($0, $1) {
  $0 = +$0;
  $1 = +$1;
  var $2 = 0, label = 0, sp = 0;
  sp = STACKTOP;
  $2 = $0 + $1;
  return +$2;
 }
 return {
  _add: _add
 };
});
```
I believe this is not a valid asm.js, because the "$2" was declared as int, but then assigned to ($0 + $1) which is double. 
If I use the above compiled asm.js in Firefox, the firefox will report this error:
```TypeError: asm.js type error: double is not a subtype of int```

My emcc version is:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.21
clang version 4.0.0  (emscripten 1.37.21 : 1.37.21)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Users/chenzhuo03/sites/emsdk-portable/clang/e1.37.21_64bit
INFO:root:(Emscripten: Running sanity checks)
```
Did I use emcc in wrong way or miss something?

Thank you very much.

**Comment by kripken** [comment]
This looks like a bug in `ONLY_MY_CODE`, as without it it works ok. Probably it is parsing the JS and turning `0.0` into `0`, which makes validation fail.

`ONLY_MY_CODE` isn't tested that much, though. I'd recommend using `SIDE_MODULE` for that use case. It does include a little more code (for dynamic linking support), but it is well-tested, and I verified it works here.

If you or someone else is interested to fix the `ONLY_MY_CODE` bug, that's great of course.

**Comment by czizzy** [comment]
I will try to fix it. Thank you very much.
