### ISSUE TITLE
emconfigure error

### ISSUE THREAD

**Issue by masterofdaemon** [emscripten-core/emscripten#5625]
Hello, i've got error from emconfigure while i compile sgminer (https://github.com/Atrides/sgminer-monero) : 

checking for pthread_create in -lpthread... yes
checking for library containing addstr... -lncurses
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBCURL... no
checking for LIBCURL... no
configure: error: Missing required libcurl dev >= 7.18.2
ERROR:root:Configure step failed with non-zero return code 1! Command line: ['./configure', 'CC=gcc'] at /root/sgminer-monero

If i run just 'configure', all ok.

**Comment by kripken** [comment]
configure run natively will look through your local system libraries. emconfigure will point it to the emscripten portable system libraries, and libcurl is not in there, so you'd need to have a port of that first, see https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries

**Comment by masterofdaemon** [comment]
Thanks, i get it, another project: all is compiled by emmake, binary is created, but no bc file or .o file, so i need to rewrite make file to make all in one OBJ file?

**Comment by kripken** [comment]
If it's creating an output "binary" that contains all the bitcode, but just doesn't have the suffix `.o` or `.bc`, then you can just rename it to `.bc` and run emcc on that.

**Comment by masterofdaemon** [comment]
nop:
 WARNING:root:bin/xmr-stak-cpu.bc is not valid LLVM bitcode
ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')

**Comment by kripken** [comment]
If it's not bitcode, something went wrong. Running make with `VERBOSE=1` will show the commands it runs, so you can see if it is using emcc as it should.
