### ISSUE TITLE
use -s WASM=1 or not use will be a same result

### ISSUE THREAD

**Issue by mingChen2017** [emscripten-core/emscripten#5639]
I have two question.

  one is when I use emcc  -o tests/test.js tests/test.cpp -O2 -s WASM=1 or emcc  -o tests/test.js tests/test.cpp -O2 have a same size file ,and the run time is also equal .

  another is I see other people use -o tests/test.html tests/test.cpp -O2 -s WASM=1 generate three file ,include .html,.wasm and .js,but I only generate one .html file,please tell me why .

  thank you very much!

**Comment by kripken** [comment]
You should see `tests/tests.js, tests/tests.wasm` files created. If the wasm file isn't created, maybe somehow you aren't passing the `-s WASM=1` argument properly on the command line. Run with `EMCC_DEBUG=1` in the env to see what command emcc is receiving.
