### ISSUE TITLE
Assertion failed: TOTAL_MEMORY not big enough for stack

### ISSUE THREAD

**Issue by Xaratas** [emscripten-core/emscripten#5662]
Source i want to compile: Head of https://github.com/swipetospin/libbpg

Problem: The attached example crash right at the start with an Out of Memory error. Which is logged three times: as info, as warning and as error. I tested in Chrome and FF with the same results. The Chrome memory snapshot shows 32mb of allocated memory, matching the limit defined in the makefile. Different limits did not change the result.

For the attached example i added this to the makefile, and removed the -O3: 
EMLDFLAGS+=-s ASSERTIONS=2 -s SAFE_HEAP=1 -s SAFE_HEAP_LOG=1 -O0

With ALLOW_MEMORY_GROW=1 it get in an infinite(?) loop allocating new memory. The tab becomes unresponsive.

Stacktrace:

> uncaught exception: abort("Assertion failed: TOTAL_MEMORY not big enough for stack") at jsStackTrace@http://localhost:8000/bpgdec8_assert.js:937:13
stackTrace@http://localhost:8000/bpgdec8_assert.js:951:12
abort@http://localhost:8000/bpgdec8_assert.js:31932:44
assert@http://localhost:8000/bpgdec8_assert.js:417:4
@http://localhost:8000/bpgdec8_assert.js:1318:2
@http://localhost:8000/bpgdec8_assert.js:1:3

FF version: 56.0 (64bit)
Chromium version: Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)

Emscripten version:

> emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.21
clang version 4.0.0  (emscripten 1.37.21 : 1.37.21)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/xar/emsdk-portable/clang/e1.37.21_64bit
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

Zip contains demo html page, demo image and with debug mode compiled js
[bpg_example.zip](https://github.com/kripken/emscripten/files/1380843/bpg_example.zip)

**Comment by kripken** [comment]
> With ALLOW_MEMORY_GROW=1 it get in an infinite(?) loop allocating new memory. 

This is what I would focus on debugging. Some debug printfs can help in my experience, it might be entering a code path it shouldn't etc.
