### ISSUE TITLE
Building OpenCV bitcode

### ISSUE THREAD

**Issue by shubhamagarwal003** [emscripten-core/emscripten#5705]
Hi,
I am pretty new to Emscripten and Cmake. I was trying to build OpenCV bit code using emcmake. I tried 
```
emcmake cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_C_EXAMPLES=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D WITH_TBB=ON \
      -D WITH_V4L=ON \
      -D WITH_QT=ON \
      -D WITH_OPENGL=ON \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D BUILD_EXAMPLES=ON ..
```

But I was getting the error Couldn't find QTCore, but If I run without emcmake it builds successfully without any errors. Can you help me about what I might be missing.

**Comment by kripken** [comment]
emcmake will not link to your local system Qt install, as it needs a version compiled to the web, not to x86. So you'd need to port Qt first using emscripten.

See https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries

**Comment by happytoTom** [comment]
do you fix the problem? thanks...
