### ISSUE TITLE
[Question] Is any way to use nodejs pkg from C sources? Using nanomsg.

### ISSUE THREAD

**Issue by DeckerSU** [emscripten-core/emscripten#5714]
Hi, all! Is any examples how i can use an nodejs pkg function calls from C sources? For example, i want to build this example source - http://nanomsg.org/gettingstarted/index.html (Pipeline (A One-Way Pipe)) with **emcc**. But i can't find any sources of nanomsg that succefully compiled with emscripten, but i found nodejs-nanomsg implementation - https://github.com/nickdesaulniers/node-nanomsg . Can i use node-nanomsg from C code? Or may be exists nanomsg library for emscripten? 

Main aim is to understand how to correctly use nanomsg functions from app compiled via emcc.

Any advice is appreciated. Thx in advance.

**Comment by curiousdannii** [comment]
http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

There are multiple ways, various pros and cons. I'd recommend trying a few and seeing which you like more.

**Comment by DeckerSU** [comment]
@curiousdannii , thx, i was already read this. On simple examples like:

`emscripten_run_script("alert('hi')");`

or
```
#include <emscripten.h>

int main() {
  EM_ASM(
    alert('hello world!');
    throw 'all done';
  );
  return 0;
}
```
It's clear. But unfortunatelly i'm still don't clearly understand how i can use full node-nanomsg module (every function from it) from "C" code. Can you provide a small example?

**Comment by curiousdannii** [comment]
It depends what exactly you want to do. If that involves sockets then it will probably be very complicated, and beyond my experience I'm afraid.
