### ISSUE TITLE
Drop BlobBuilder support

### ISSUE THREAD

**Issue by nazar-pc** [emscripten-core/emscripten#5724]
I've discovered usage of `MozBlobBuilder` and `WebKitBlobBuilder` in Emscripten. Those are VERY old APIs and modern `Blob` is supported in all major browsers including Mobile versions since at least 2013: https://caniuse.com/#feat=blobbuilder

I think it might be time to stop using these old APIs in Emscripten.

**Comment by saschanaz** [comment]
This will remove compatibility with Android 4.4.x default browsers. I'm not sure, probably okay?

**Comment by nazar-pc** [comment]
We need maintainers to identify how important is that. At least, older versions will be available for those, who need older hardware/software.

**Comment by kripken** [comment]
4.4 seems to have [almost 10% market share on mobile](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=1), which seems significant, sadly.

**Comment by juj** [comment]
I'd be ok this being pushed behind a `-s TARGET_BLOBBUILDER=0/1` option, default to 1 for now, and allowing users to do a `-s TARGET_BLOBBUILDER=0` to omit codegen related to that.

**Comment by nazar-pc** [comment]
It is not that big piece of code, probably does not worth a separate option.

Caniuse says Android < 5.0 default browser is about 1.5% of market share combined (many people are using alternative browser, so stats about OS alone are not accurate).

**Comment by kripken** [comment]
Good point about people using non-default browsers. 1.5% still feels significant enough to keep it, to me, but at such low numbers it's not very clear. Perhaps we should develop an "official" approach to things like this, a concrete market share number beneath which we are ok dropping obsolete browser support?
