### ISSUE TITLE
Relative Mouse movement inconsistent results on Chrome only, but OK on FireFox

### ISSUE THREAD

**Issue by GregSlazinski** [emscripten-core/emscripten#5737]
Hi,
I'm experiencing an issue on Chrome Canary (on FireFox works OK) where relative mouse movement gives different speed when moving left vs moving right.
I've posted this on Chromium bugs, but Chrome team can't reproduce it.
There are details in the posts, including videos, and the code that I'm using.
https://bugs.chromium.org/p/chromium/issues/detail?id=780404

Is there something you know what could go wrong?
(note that you have to use Chrome Canary, Windows, and a Mouse, not touchpad or touchscreen).
Thank you,
Greg

Edit: I was able to find out what's this related to, the mouse polling rate. 125Hz works better, while 1000Hz generates different speed results. I've posted about it on the chromium bugs page.

**Comment by juj** [comment]
Looks like an interesting bug. I'd recommend doing a test case to Chrome bug tracker that is detached from the rendering engine to verify that it's not e.g. an interaction with requestAnimationFrame or something else complex. Perhaps just a mouse handler and capture and print numbers in the Emscripten log?
