### ISSUE TITLE
Compiling LLVM

### ISSUE THREAD

**Issue by arcanis** [emscripten-core/emscripten#579]
Ok, so I'm trying to compile LLVM (only interpreter, so without JIT) with Emscripten (not sure if it will work, but let's try).

First problem : it seems there is a conflict somewhere inside Emscripten headers :

```
/home/user/llvm/utils/TableGen/CodeGenSchedule.cpp:1299:12: error: use of overloaded operator '+' is ambiguous (with operand types 'int' and 'RecIter' (aka '__wrap_iter<const_pointer>'))
  return 1 + PRPos - ProcResourceDefs.begin();
         ~ ^ ~~~~~
/home/user/emscripten/system/include/libcxx/iterator:1210:5: note: candidate function [with _Iter1 = llvm::Record *const *]
    operator+(typename __wrap_iter<_Iter1>::difference_type, const __wrap_iter<_Iter1>&) _NOEXCEPT;
    ^
/home/user/emscripten/system/include/libcxx/iterator:1298:1: note: candidate function [with _Iter = llvm::Record *const *]
operator+(typename __wrap_iter<_Iter>::difference_type __n,
^
```

I'm currently using this line for cmake :

```
cmake .. -DCMAKE_CXX_COMPILER=em++ -DLLVM_ENABLE_THREADS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_TARGETS_WITH_JIT=OFF -DHAVE_SYS_IOCTL_H=OFF -DHAVE_TERMIOS_H=OFF -DHAVE_DLFCN_H=OFF -DHAVE_POSIX_SPAWN=OFF -DHAVE_GETRLIMIT=OFF -DHAVE_EXECINFO_H=OFF -DHAVE_BACKTRACE=OFF -DHAVE_VALGRIND_VALGRIND_H=OFF
```

Please not that the file Path.inc will not compile. I have tried to force the code to use the __freebsd path in this part in order to make it compile. Not sure if it will work but ... well, it worth the try.

**Comment by httpdigest** [comment]
Has anyone recently tried compiling LLVM (together with the javascript fastcomp backend) with Emscripten?
It would be quite interesting if MCJIT could be used as asm.js/JavaScript JIT backend within the runtime of JIT languages, so as to benefit from LLVM optimizations when generating asm.js at runtime.
I wonder though how linking with already statically compiled asm.js code would work at runtime.

**Comment by arcanis** [comment]
Recently no, but I managed to compile LLVM back in 2013, and use its interpreter to run any Module object. I think someone else also did it too more recently (I kinda remember seeing some article about this), but I can't find it.

The only thing remaining is [this gist](https://gist.github.com/arcanis/5889108), which contains the flags I was using and the minimal running code (should print 42).
