### ISSUE TITLE
Call external async JavaScript library in Emterpreter

### ISSUE THREAD

**Issue by pjb7687** [emscripten-core/emscripten#5791]
Is there a way to call external asynchronous JavaScript library (via EM_ASM) in Emterpreter?

I would like to use PouchDB to store persistent data instead of native IDB (for compatibility reason), but the library works asynchronous way.

It would be great e.g. if I could manually make Emterpreter stop executing after the async library call, so that it restore stack and work again after the async call is completed.

**Comment by kripken** [comment]
Yes, look at how [emscripten_sleep](https://github.com/kripken/emscripten/blob/incoming/src/library_async.js#L354) is defined for example,
````
  emscripten_sleep__deps: ['$EmterpreterAsync'],
  emscripten_sleep: function(ms) {
    EmterpreterAsync.handle(function(resume) {
      setTimeout(function() {
        if (ABORT) return; // do this manually; we can't call into Browser.safeSetTimeout, because that is paused/resumed!
        resume();
      }, ms);
    });
},
````
The `handle()` call does most of the work, and you code calls `resume()` whenever it wants to.

**Comment by curiousdannii** [comment]
What's the ABORT check for? Any reason it couldn't moved inside resume?

**Comment by pjb7687** [comment]
Thanks for the answer. Could I ask how could I access 'EmterpreterAsync' via 'EM_ASM'? I searched member of 'Module' but I couldn't find this.

**Comment by kripken** [comment]
> What's the ABORT check for? Any reason it couldn't moved inside resume?

Hmm, yeah, we can't resume if the program has been shut down, good idea. Want to submit a PR?
