### ISSUE TITLE
GCCLINK error

### ISSUE THREAD

**Issue by enchashiki** [emscripten-core/emscripten#5805]
1>  Unsupported:   %141 = lshr i96 %140, %.sink19
1>GCCLINK : LLVM error : Expansion of variable-sized shifts not yet supported for integer types larger than 64 bits

i use "sdk-1.37.21-64bit" on windows.
How can I solve this problem.

it is not problem "sdk-1.37.5-64bit"

**Comment by kripken** [comment]
This is a limitation of the legalization that the fastcomp backend uses. If it worked before, it's a regression, which is strange. Is this code generated using clang?

Using the [new wasm backend](https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend) instead would avoid the legalization issue, but it isn't yet stable.

**Comment by zenorogue** [comment]
I get the same problem. 
`Unsupported:   %282 = lshr i96 %281, %.sink
LLVM ERROR: Expansion of variable-sized shifts not yet supported for integer types larger than 64 bits`

em++ -v says:
 `emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.33
clang version 5.0.0  (emscripten 1.37.33 : 1.37.33)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/emscripten-fastcomp
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/6.4.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
`

I have tried to pinpoint the cause of the problem, but this is difficult -- separate cpp files are compiled correctly, but not the whole project. I have not tried the new wasm backend.

**Comment by zenorogue** [comment]
Checked the version 1.37.5 as mentioned by enchashiki -- it works with -O0, but not with -O2. Version 1.37.33 does not seem to work even with -O0.

**Comment by zenorogue** [comment]
WASM does not work either (internal error in LLVM), but I have managed to compile by avoiding bitfields.
