### ISSUE TITLE
EM_ASM WASM Side Module can not compile bug

### ISSUE THREAD

**Issue by MarilynDafa** [emscripten-core/emscripten#5812]
AssertionError: EM_ASM is not yet supported in shared wasm module (it cannot be stored in the wasm itself, need some solution)

**Comment by MarilynDafa** [comment]
here is my compile flag
-s FULL_ES3=1 -s USE_WEBGL2=1 -s USE_GLFW=3 -s WASM=1 -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 -s FORCE_FILESYSTEM=1  -s BINARYEN_ASYNC_COMPILATION=1 -s SIDE_MODULE=1

**Comment by rugged517** [comment]
Same Error for me when Compiling rogue.bc and libcurses.bc to rogue.html/.wasm with "-s SIDE_MODULE=1" Flag.
I want to use this Flag for keeping the function names from the C-Sources. 
Any Solutions or Workarounds for this?
