### ISSUE TITLE
link error when link POCO lib

### ISSUE THREAD

**Issue by navidad7** [emscripten-core/emscripten#5825]
I am struggling to compile my wasm module(using wss) with POCO Net/NetSSL library. First of all, I have compiled OpenSSL & POCO library successfully using emscripten env. But when I compile my module with POCO, I met a following warning message.

warning: unresolved symbol: epoll_ctl
warning: unresolved symbol: epoll_create
warning: unresolved symbol: epoll_wait

I assume that POCO lib uses the system call but linking is broken.

Can it be a solution to use musl library instead of stdlib? If yes, how can I get a detail instructions?

It seems that emcc -nostdlib option does not work..

**Comment by juj** [comment]
`epoll` does not exist in Emscripten. There is an emulation layer for some BSD sockets code to route to WebSockets, but the implementation is quite partial, so you will likely need to improve that implementation a great deal to port a project that largely stresses networking. Note that web browsers do not have access to raw TCP or UDP sockets, but only to WebSockets, XHRs and WebRTC Data Channels. So the project will need to address this somehow, e.g. by using [websockify](https://github.com/novnc/websockify) or similar.
