### ISSUE TITLE
__ATINIT__ defined in JS

### ISSUE THREAD

**Issue by tjpalmer** [emscripten-core/emscripten#5841]
Would it be possible to have `__ATINIT__` entries added by wasm modules themselves in some fashion?

I'm trying to make a common js environment for somewhat arbitrary wasm modules, and this is one of the compatibility problems I've found.

**Comment by kripken** [comment]
A wasm module might be able to use the wasm `start` method, that code will run as the module is instantiated - is that good enough for your use case?

Otherwise, if you need a more C-like environment, there currently isn't a way to do that - there is `atexit` for adding exit callbacks, but not the reverse. We could add it, though, it would be just a few lines.

**Comment by tjpalmer** [comment]
Any general solution needs to be contained within the wasm module itself. If there's a common method that's the same for all emscripten-generated modules (such as the start you mention), that would be fine. Having to guess arbitrary entries to add from the js side is what I need to avoid.

Or if there is a way to guess which atinits to add, that would work, too, I guess.

**Comment by kripken** [comment]
Yeah, if `start` can work it's the best option. However, it doesn't support reentrancy (it's called before the module was fully created and received on the outside).

In a dynamic linking context, you can use `__post_instantiate` ([docs](https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md), but dynamic linking is not stable).

**Comment by tjpalmer** [comment]
Is it possible to modify emscripten to put the atinit registrations there, then? Any pointers if I or others would have a chance to contribute in the regard? I can't make promises, but I might be interested, if it seems doable, and if you'd be willing to take a contribution in this regard.

**Comment by kripken** [comment]
`__post_instantiate` is meant for dynamic linking, though, and we don't emit dynamic libraries by default.

Overall, a lot of this is up in the air, see e.g. https://github.com/WebAssembly/tool-conventions/issues/25 for a discussion. Sorry this isn't in clearer shape yet.

**Comment by tjpalmer** [comment]
Thanks for the feedback and the link. That's interesting reading.
