### ISSUE TITLE
Multiple SDL port compiler flags failing in CMake

### ISSUE THREAD

**Issue by conormackeigan** [emscripten-core/emscripten#5852]
I'm trying to use SDL2, SDL2_Image and SDL2_TTF libraries with emscripten. I figured the easiest way to do this was use the included ports, but for some reason only the first one in the list is retrieved from git, while the rest get:

"ERROR:root:USE_SDL_TTF=2: No such file or directory ("USE_SDL_TTF=2" was expected to be an input file, based on the commandline arguments provided)"

However, I've confirmed the ports are all valid and will load correctly if they are the first in the list. As far as I can tell the compiler flag list syntax is correct, but maybe I'm missing something? I'm including the flags with this line at the end of my CMakeLists.txt:

target_compile_options(AttackOnPanel PUBLIC -s USE_SDL_IMAGE=2 USE_SDL_TTF=2)

Any help is greatly appreciated, I'm a noob to emscripten and CMake so I might be making a dumb mistake, but everything seems fine according to the documentation I've read.

**Comment by echeese** [comment]
You need to put `-s` in front of `USE_SDL_TTF=2`

**Comment by conormackeigan** [comment]
Doesn't make a difference, still interprets it as an input filename. Used all sorts of combinations of "" and -s prefixes, it either results in invalid syntax or the input file error.

**Comment by tay10r** [comment]
This can be fixed by using the `SHELL: ` syntax. It's a known behaviour of CMake to remove flags that look redundant.

```cmake
target_compile_options(AttackOnPanel PUBLIC "SHELL: -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2")
```
