### ISSUE TITLE
compile failed with emcc in _types.h

### ISSUE THREAD

**Issue by WingLazz** [emscripten-core/emscripten#5853]
my command is:

` em++ -Wwarn-absolute-paths -emit-llvm -std=c++11 -S 
		-I /usr/include -I /usr/local/include 
		-I /usr/local/Cellar 
		-I /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include 
		main.cpp -o main.ll `

and the output is:

`WARNING:root:-I or -L of an absolute path "-I/usr/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). [-Wabsolute-paths]
In file included from main.cpp:10:
In file included from /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:23:
In file included from /usr/include/stdio.h:64:
/usr/include/sys/cdefs.h:761:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from main.cpp:10:
In file included from /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:23:
In file included from /usr/include/stdio.h:67:
In file included from /usr/include/_types.h:27:
In file included from /usr/include/sys/_types.h:33:
/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^
In file included from main.cpp:10:
In file included from /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:23:
In file included from /usr/include/stdio.h:67:
In file included from /usr/include/_types.h:27:
/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
        ^
/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
        ^
/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_dev_t;         /* dev_t */
        ^
/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
        ^
/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
        ^
/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
        ^
/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
        ^
/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'
typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
        ^
/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
        ^
/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
        ^
/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
        ^
/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
        ^
/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
        ^
/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
        ^
In file included from main.cpp:10:
In file included from /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:23:
In file included from /usr/include/stdio.h:71:
/usr/include/sys/_types/_va_list.h:31:9: error: unknown type name '__darwin_va_list';
      did you mean '__builtin_va_list'?
typedef __darwin_va_list va_list;
        ^
note: '__builtin_va_list' declared here
In file included from main.cpp:10:
In file included from /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:23:
In file included from /usr/include/stdio.h:72:
/usr/include/sys/_types/_size_t.h:30:9: error: unknown type name '__darwin_size_t'; did
      you mean '__darwin_ino_t'?
typedef __darwin_size_t        size_t;
        ^
/usr/include/sys/_types.h:64:26: note: '__darwin_ino_t' declared here
typedef __darwin_ino64_t __darwin_ino_t;        /* [???] Used for inodes */
                         ^
In file included from main.cpp:10:
In file included from /Users/chenchen/workspace/emsdk/emscripten/incoming/system/include/emscripten/emscripten.h:23:
In file included from /usr/include/stdio.h:442:
/usr/include/sys/_types/_ssize_t.h:30:9: error: unknown type name '__darwin_ssize_t'
typedef __darwin_ssize_t        ssize_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting`

I has no idea what's wrong with it. Could anyone tell me what the reason is. Appreciate !

**Comment by kripken** [comment]
The warning at the very beginning explains what's wrong: `/usr/include` is a local system path of yours, and the headers there contain code for your local system. `emcc` has its own system headers, and it needs to use those to compile to the web, not the local system ones. For example, your local system may be ARM or x86_64, while the web can't use code specific to those CPUs, etc.

**Comment by ChanMQ** [comment]
But what can I do if I want to use openCV. It throw errors without the local path '/usr/include'.

**Comment by ChanMQ** [comment]
But what can I do if I want to use openCV. It throw errors without the local path '/usr/include'.

**Comment by ChanMQ** [comment]
@kripken But what can I do if I want to use openCV. It throw errors without the local path '/usr/include'.

**Comment by kripken** [comment]
I believe there is a working port of OpenCV already, I would look how they handle this. In general, the question is what it needs from `/usr/include`, and then you need to get a portable version of that for compiling to the web.

**Comment by juj** [comment]
One such Emscripten port of OpenCV can be found at https://github.com/juj/OpenCV/tree/opencvjs, though it has not been worked on in a while, so might not be up to date with latest OpenCV and could run into some glitches. You could try checking out the commit history in that tree to see what kind of changes had been applied to make the build system go through Emscripten.
