### ISSUE TITLE
Support source maps with the emterpreter, for non-emterpreted code

### ISSUE THREAD

**Issue by janjongboom** [emscripten-core/emscripten#5862]
I'm cross-compiling embedded C++ code which relies on blocking the main thread a lot. To not lock up the browser I'm implementing this with `emscripten_sleep_with_yield`. This works fine. However... when generating source maps for the application (`-g4`) this fails with:

```
INFO:root:generating system library: dlmalloc_debug.bc... (this will be cached in "/home/ubuntu/.emscripten_cache/asmjs/dlmalloc_debug.bc" for subsequent builds)
INFO:root: - ok
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/tmpHVck4YtmpBLzhMd.jsfunc_0.js.jo.js.jo.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/home/ubuntu/emsdk-portable/emscripten/1.37.22/tools/source-maps/sourcemapper.js:186:49)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
Traceback (most recent call last):
  File "/home/ubuntu/emsdk-portable/emscripten/1.37.22/emcc", line 13, in <module>
    emcc.run()
  File "/home/ubuntu/emsdk-portable/emscripten/1.37.22/emcc.py", line 1800, in run
    emit_js_source_maps(target, optimizer.js_transform_tempfiles)
  File "/home/ubuntu/emsdk-portable/emscripten/1.37.22/emcc.py", line 2181, in emit_js_source_maps
    '--offset', str(0)])
  File "/home/ubuntu/emsdk-portable/emscripten/1.37.22/tools/jsrun.py", line 131, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/home/ubuntu/emsdk-portable/node/4.1.1_64bit/bin/node', '/home/ubuntu/emsdk-portable/emscripten/1.37.22/tools/source-maps/sourcemapper.js', '/tmp/tmpGX5tsl/blinky2.bc.o.js', '/tmp/tmpHVck4YtmpBLzhMd.jsfunc_0.js.jo.js.jo.js', '/tmp/tmpdHzZVCtmpSna9wW.jsfunc_0.js.jo.js.jo.js', '--sourceRoot', '/home/ubuntu/mbed-simulator', '--mapFileBaseName', '/home/ubuntu/mbed-simulator/out/blinky2.js', '--offset', '0'] to finish with return code 0, but it returned with code 1 instead! Output:
```

(On both MacOS and Ubuntu 16)

When removing the `EMTERPRETIFY=1` and `EMTERPRETIFY_ASYNC=1` flags the source map gets generated, so it seems to be something related to Emterpretify. 

@kripken mentioned in [#3638](https://github.com/kripken/emscripten/issues/3638#issuecomment-210548044) that emterpretify and source maps might not be compatible.

I'm wondering if there is a way to emulate `emscripten_sleep_with_yield` without emterpretify... Or a way to generate sourcemaps regardless.

**Comment by janjongboom** [comment]
Actually, with `ASYNCIFY=1` and normal `emscripten_sleep` it seems to work pretty well... Wondering why I needed `emscripten_sleep_with_yield` in the first place.

**Comment by kripken** [comment]
Note that ASYNCIFY is not currently supported. We are actually considering removing it (#5801). But maybe we shouldn't - how important is the combination of async operations + source maps to you?

**Comment by janjongboom** [comment]
@kripken Ah interesting. So I'm using Emscripten for [this](http://ec2-52-211-146-247.eu-west-1.compute.amazonaws.com:7829), which is an in-browser simulator for Cortex-M devices. Because these are often single-threaded applications I need a way to pause the application w/o locking up the whole browser (preferably in a way where I can still inject events in the runtime to simulate interrupts, but that's another story). Right now I don't see how I could implement this without async operations.

Source maps are currently the only way a user can debug their application, which is a nice selling point of the simulator, as it makes the feedback loop a lot shorter (rather than build, flash, debug on real device).

**Comment by kripken** [comment]
Let's reopen this for source maps support for non-interpreted code in emterpeter mode.
