### ISSUE TITLE
Example of how to do networking

### ISSUE THREAD

**Issue by felipellrocha** [emscripten-core/emscripten#5866]
Is there any way we could get an example of how to do networking in emscripten (wasm)? I've been struggling with this issue for a long time now, even as I have already implemented something natively. I'm a total beginner at c++ and networking programming at this level, and I'm sure others are as well, so it would be extremely helpful.

**Comment by kripken** [comment]
The sockets tests have working code, see `tests/test_sockets.py`.

**Comment by felipellrocha** [comment]
I finally figured out what was wrong with my code. I was trying to support both native and emscripten. I was using a library that read the WS headers for me on native, but the browser already does that and gives you back the raw message sent to you. All I needed to do was comment out the code from my library that read the WS headers, and everything was back in order!

**Comment by gopal1022** [comment]
May I know how to use that test_sockets.py ?
I have to port my c++ code containing socket code to WebAssembly.

**Comment by kripken** [comment]
You can run them with `python tests/runner.py sockets`. Replace `sockets` with `sockets.test_X` with a specific test to run just one, etc.

**Comment by kripken** [comment]
I would just read the test code to see what it does. Even if you don't know python, you can see what function calls what, and in the end it emits some commands to emcc.py and others, etc.. Also, you can use `EMCC_DEBUG=1` in the env to make it print out the emcc commands and their debug output (including the arguments they were called with).

**Comment by Squareys** [comment]
For those who come by this issue: you may find this blog post ["Introduction to Emscripten Sockets"](http://blog.squareys.de/emscripten-sockets/) helpful.

**Comment by d3x0r** [comment]
Server sockets?  Listen and bind? :)
