### ISSUE TITLE
error: Linking globals named 'emscripten_float64x2_add': symbol multiply defined!

### ISSUE THREAD

**Issue by RudyAramayo** [emscripten-core/emscripten#5867]
So I am trying to see why this is happening, I have tried to remove optimizations by adding the following to a Ninja Build script file:

1. ELIMINATE_DUPLICATE_FUNCTIONS=0
2.--llvm-opts 0 -O2
3.ALLOW_MEMORY_GROWTH=0
this allow memory growth removed a warning I kept getting.

The project is an OpenCV build and I am trying to use the library for a simple build... There is an issue with the exact same error but you guys did not address the issue enough for me to fix it alone.

I tried latest EMSDKs:
emscripten-nightly-1.37.22-2017_11_25_22_12
emscripten-1.37.21
emscripten-1.37.22
emscripten-1.36.14****

This project is awesome and very important, thank you for your contributions...
What is going on?

**Comment by kripken** [comment]
I think @juj fixed this after 1.37.22. There should be a 1.37.23 tag up soon, or you can get the incoming branches directly.

**Comment by froydnj** [comment]
@RudyAramayo did the 1.37.23 build fix this for you?
