### ISSUE TITLE
FS.currentPath is undocumented

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5873]
`FS.currentPath` is a way to change working directory but is not documented:

https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/tests/filesystem/src.js#L33

**Comment by vedadkajtaz** [comment]
`FS.readdir` is undocumented as well.

**Comment by saschanaz** [comment]
@vedadkajtaz It's documented as 'Advanced File System API' but well, without details. http://kripken.github.io/emscripten-site/docs/api_reference/advanced-apis.html?highlight=readdir#FS.readdir

**Comment by vedadkajtaz** [comment]
Indeed!
