### ISSUE TITLE
namespaces in js / nested objects in output

### ISSUE THREAD

**Issue by sijakret** [emscripten-core/emscripten#5874]
I am crosscompiling an existing c++ library to wasm and i would like to transfer also the organization of namespaces from c++ to js as transparently as possible. 

I have been looking all over but couldn't find anything on this topic.
Ill i could find is this old post: https://www.mail-archive.com/search?l=emscripten-discuss@googlegroups.com&q=subject:%22Using+embind+on+an+API+using+namespaces%22&o=newest&f=1

So, for instance i would like the constructor `a::b::c::MyClass` to be exposed as `MyModule.a.b.c.MyClass` in js.

I tried this
```c++
EMSCRIPTEN_BINDINGS(MyClass) {
  class_< a::b::c::MyClass >("a.b.c.MyClass")
 //...
}
```
But it gives me some sort of mangeled output where the export goes to `a$b$c$`.

Is there an off-the-shelve way of accomplishing what i am looking for or do i need do generate some sort js glue code to do this?

Seems like a relevant feature for exposing apis of larger libraries..

Thanks a lot!

**Comment by sijakret** [comment]
I created some quick glue code that, for the time being, leads to the behavior i am looking for.
Maybe it is of interest to anyone..

Given a module, this function returns an object with all namespaced objects (see comment on how to export something so this function picks it up)
```javascript
/**
 * generates an object that corresponds to the namespaces in c++
 * if classes are exported like this
 * EMSCRIPTEN_BINDINGS(MyClass) {
 *  class_< a::b::c::MyClass >("a.b.c.MyClass")
 *  //..
 *  }
 */ 
function namespaces(module) {
  // final namespace
  const ns = {};

  // find all fields in module with replaced special chars
  // (all special characters seem to be replaced by $)
  const filtered = Object.keys(module).filter(k => k.indexOf('$') !== -1);

  // merge discovered fields into ns
  // no collision handling or anything
  filtered.map(name => name.split("$").reduce((ns_, key, i, a) => 
    ns_[key] = (i !== a.length-1 ? {} : module[name])
  , ns));

  return ns;
}
```
By then adding a postRun hook in the module the namespace object can, for example be merged with the orignal module (or put elsewhere)
```js
var Module = {
  postRun: [() => {
    // merge namespaces with original module
    // note: this spread operator might need a recent browser
    Module = { ...Module, ...namespaces(Module) };
  }]
};
```

**Comment by saschanaz** [comment]
It seems this line is related:

https://github.com/kripken/emscripten/blob/93479ecbd390aec4f8a3765fe04bcb365d0b31b2/src/embind/embind.js#L1799

**Comment by sijakret** [comment]
ah - this one replaces the illegal characters i mentioned earlier!
I am surprised no one else is missing a 'namespace feature' - seems like everyone is only exporting flat APIs..

**Comment by saschanaz** [comment]
We may fix the logic in this function to get namespaces!
 https://github.com/kripken/emscripten/blob/93479ecbd390aec4f8a3765fe04bcb365d0b31b2/src/embind/embind.js#L119-L141

**Comment by sijakret** [comment]
yes, this should be the place to add it!
@kripken is this of interest?

**Comment by kripken** [comment]
cc @AlexPerrot , the embind expert.
