### ISSUE TITLE
Prevent CI failure after tagging new version

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#5886]
Continuing from https://github.com/kripken/emscripten/pull/5544:

We need a way to prevent test failure which occurs when we add a new version tag. Fixing SDK builder logic will reduce the effect from failure but will not fundamentally prevent the error.

We may have to skip the test if the runner already knows there is a version difference.

**Comment by kripken** [comment]
Good idea, yeah. If `emcc.py -v` reports a version mismatch, we could skip the few tests that are affected by that.
