### ISSUE TITLE
What is stdio.html

### ISSUE THREAD

**Issue by felipellrocha** [emscripten-core/emscripten#5888]
I've moved the contents that emscripten creates into a separate proxy (The stuff you usually put in `/build`).
Everything is loading except for this one stdio.html which just keeps `404`ing. I see no reference to it anywhere in the documentation. What is it, and how come the proxy doesn't pick up on it?

**Comment by kripken** [comment]
Looks like it's part of `emrun`, it's referenced in `emrun.py` and the files it uses.
