### ISSUE TITLE
Is there support for building in visual studio 2017?

### ISSUE THREAD

**Issue by emilekberg** [emscripten-core/emscripten#5889]
I'm looking into the documentation and i see this https://kripken.github.io/emscripten-site/docs/building_from_source/manually_integrating_emscripten_with_vs2010.html for instance, mentioning that there is no such support. 

I find some issues referencing this, such as #5259 but i do not find any documentation that suggests how this should be used? 

I might just be confused :) please help me clear this out if this is possible :)

**Comment by saschanaz** [comment]
The tool is not maintained anymore. https://github.com/juj/vs-tool

Someone may fork and maintain if interested.

**Comment by saschanaz** [comment]
(#5259 is for EMSDK where it requires VC++ compiler.)
