### ISSUE TITLE
Warning: unresolved symbol: glfwCreateWindow

### ISSUE THREAD

**Issue by pickaus** [emscripten-core/emscripten#5895]
Hiya, I'm trying to compile a fairly large OpenGL program with emscripten, and surprisingly, I'm only getting a very few warnings and 1 unresolved external, (em++) I've defined GLFW_INCLUDE_ES3 before including glfw. Everything seems ok, except that the unresolved symbol is quite worrying: "glfwCreateWindow"

I've tried searching on the net about others having similar issues but no luck. "glfwCreateWindow" to the best of my knowledge is supported in GL_ES, it's a standard glfw function that otherwise works on a PC build. What might I be missing here? I'm sure if I messed something up there should be lots of errors and probably a lot more unresolved symbols.

By the way, I really like the idea of emscripten! Hope to get it working soon :) Keep up the good work, and thanks for the help in advance

**Comment by echeese** [comment]
Try passing `-s USE_GLFW=3` to `em++`, by it's set to GLFW 2 by default.

**Comment by pickaus** [comment]
Thanks, that did solve the unresolved symbol issue! :) My code compiles and runs but something is up with the file management, for some reason only "_embedding_" works, "_preloading_" seems to break the program, but nothing is printed to the console during compilation or execution.

So I've created a simple program with just a main function that reads a .txt file and prints it to the console. Same issue, --embed works and the program runs fine. --preload breaks the program, but no errors or warnings.

Both --embed & --preload create the exact same DATA file.

I'm using: em++ main.cpp -o index.html --preload-file config.txt

Latest emscripten version. Thanks again for taking the time to help me, I've looked around and only found a few posts online where people were discussing --preload but others mostly seemed to have had problems with using relative paths including "../" or ".".

Thank you again!

**Comment by echeese** [comment]
The only thing I can think of is you may be trying to run from the filesystem. Emscripten needs XHR to load the preload file (among others) which won't work if you're not loading from a web server (even if it's just a local one)

**Comment by pickaus** [comment]
I see! I've just tried this on a web server, and preload worked as expected. I see now. I'll need to find a workaround for this so I can test locally. Thanks!

**Comment by ad8e** [comment]
Use `--memory-init-file 0` to test locally on chrome, or just use firefox
