### ISSUE TITLE
Feature request: API to get currently executing coroutine

### ISSUE THREAD

**Issue by martijnthe** [emscripten-core/emscripten#5897]
Use cases:
- port an implementation of a "thread assertion" that asserts whether the a particular thread is currently executing.
- port non-standard synchronization primitives such as semaphores.
- ...

It doesn't seem to hard to implement this. Can someone give me some pointers to how to add this?

**Comment by atrosinenko** [comment]
I think you may look at the `emscripten_coroutine_next` function [here](https://github.com/kripken/emscripten/blob/incoming/src/library_async.js#L145) and [here](https://github.com/kripken/emscripten/blob/incoming/src/library_async.js#L452). There are two implementations of async code and coroutines: Asyncify (deprecated) and Emterpreter.
