### ISSUE TITLE
Emscripten CMake library support

### ISSUE THREAD

**Issue by Faerbit** [emscripten-core/emscripten#5903]
I've written a simple game over the weekend: https://github.com/Faerbit/blobbies
It's dependencies are glfw3 and freetype2, so it should be pretty easy to compile with emscripten, as both those libs are supported officially by emscripten.
However I'm having a hard time getting it to work:

 1) There doesn't seem to be a `FindGLFW.cmake` or similar in the `cmake/Modules` folder. Is this just a case of library support being faster than CMake support for those libs?
 2) I have no idea how to integrate emscripten ports with my `CMakeLists.txt`.

I even tried dirty hacks like hard coding paths to desired locations, but was unable to get it to compile.
How is this supposed to work?

I am willing to improve this situation myself (by writing documentation and CMake scripts), if somebody could give me some pointers.

**Comment by kripken** [comment]
I believe CMake has `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`, to which you can append `-s USE_FREETYPE=1` and `-s USE_GLFW=3`.

**Comment by Faerbit** [comment]
But this would be a problem for Freetype, right? Because the headers are not installed on the system. I would have to invoke this previously, right?

**Comment by kripken** [comment]
When emcc is invoked with that option, it will fetch the freetype port, and the headers will be available. So it should just work.
