### ISSUE TITLE
glDrawElements throws glError 1282, nothing is displayed 

### ISSUE THREAD

**Issue by pickaus** [emscripten-core/emscripten#5906]
When I try to render a simple quad (no texture) I get error 1282 straight after glDrawElements(); in the browser.

My vertex attributes are all stored in one buffer: indices first, then positions, then uvs. But that shouldn't be a problem, as long as all the attributePointers are set correctly, right? Plus, the entire program runs smooth and as expected on the PC build. No errors.

Compiling with:

em++ -std=c++11 -s USE_GLFW=3 -s FULL_ES3=1 -s ALLOW_MEMORY_GROWTH=1 -o index.html

Drawing code:

`glBindVertexArray(m_Quad->getVaoId());
glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_SHORT, (void*)0);
glBindVertexArray(0);`

Shaders:

`precision mediump float;

attribute vec3 position;

void main()
{
	gl_Position = vec4(position, 1.0);
}`

`precision mediump float;

void main()
{
	gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}`

Not sure if this is a bug(?), but if it is that, then it seems to be a pretty heavy one.

**Comment by Faerbit** [comment]
Your draw call `glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_SHORT, (void*)0);` seems fishy. You're trying to get a pointer to 0. This might be the error. The black screen might be because of something else wrong with your setup. I'd advice to try it without the `(void*)`.

**Comment by pickaus** [comment]
Hi thank you for the quick response, I've tried it, no luck there, but good spotting! Btw my program is insanely small & simple, and the PC build works just fine - hence my confusion. 

I just create context (code below), load shaders normally (no errors, shaders compile fine), bind shaderprogram like normal, create the VAO and VBO for a quad, set the attributePointers and render it in the main loop, then update the screen with glfwSwapBuffers(m_WinInstance);

Here's the context creation:

`glfwInit();
if (!glfwInit()) { fprintf(stderr, "glFw Initialization FAILED"); glfwTerminate(); return false; }

glfwWindowHint(GLFW_SAMPLES, 0);
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

m_WinInstance = glfwCreateWindow((int)m_Width, (int)m_Height, m_Name.c_str(), nullptr, nullptr);`

that's literally it. I've gone through the debugging/error checking and everything should be good. It's only glDrawElements that's tripping me up...

**Comment by pickaus** [comment]
I think **glDrawElements** is **broken**.

This is my code:

    #define WEB 1

    #if WEB
	    #ifndef GLFW_INCLUDE_ES3
		#define GLFW_INCLUDE_ES3
	    #endif
	    #include <functional>
	    #include "../Middleware/EM/include/emscripten.h"
    #else
	    #include <GL\glew.h>
    #endif

    #include <GLFW/glfw3.h>
    #include <vector>

    #if WEB
	    void dispachMain(void* fp)
	    {
	        std::function<void()>* func = (std::function<void()>*)fp;
	        (*func)();
	    }
    #endif

    int main()
    {
    // Window
	    glfwInit();

	    glfwWindowHint(GLFW_SAMPLES, 0);
	    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

	    GLFWwindow* m_Instance = glfwCreateWindow(720, 480, "emscripten test", nullptr, nullptr);

    #if !WEB
	    glewExperimental = true;
	    unsigned int glewError = glewInit();
    #endif

    // Shaders

	    unsigned int vertShaderId = glCreateShader(GL_VERTEX_SHADER);
	    unsigned int fragShaderId = glCreateShader(GL_FRAGMENT_SHADER);

	    const char* vertShaderCode =
		    "precision mediump float;"
		    ""
		    "attribute vec3 position;"
		    ""
		    "void main()"
		    "{"
		    "	gl_Position = vec4(position, 1.0);"
		    "}";


	    const char* fragShaderCode =
		    "precision mediump float;"
		    ""
		    "void main()"
		    "{"
		    "	gl_FragColor = vec4(1.0, 0.5, 0.1, 1.0);"
		    "}";

	    // Compile Vertex Shader
	    glShaderSource(vertShaderId, 1, &vertShaderCode, NULL);
	    glCompileShader(vertShaderId);

	    // Compile Fragment Shader
	    glShaderSource(fragShaderId, 1, &fragShaderCode, NULL);
	    glCompileShader(fragShaderId);

	    // Link the program
	    unsigned int programId = glCreateProgram();
	    glAttachShader(programId, vertShaderId);
	    glAttachShader(programId, fragShaderId);
	    glLinkProgram(programId);

	    glDetachShader(programId, vertShaderId);
	    glDetachShader(programId, fragShaderId);

	    glDeleteShader(vertShaderId);
	    glDeleteShader(fragShaderId);

    // Quad VAO & VBO
	    float tmp_Positions[12]{ -0.5f, -1.0f, 0.0f, 1.0f, -1.0f, 0.0f, -1.0f,  1.0f, 0.0f, 1.0f,  1.0f, 0.0f };
	    unsigned short tmp_Indices[6]{ 0, 1, 2, 2, 1, 3 };

	    unsigned int VaoId, VboId;

	    glGenVertexArrays(1, &VaoId);
	    glBindVertexArray(VaoId);

	    int bufferSize = (6 * sizeof(unsigned short)) + (12 * sizeof(float));
	    int offset = 0;

	    glGenBuffers(1, &VboId);
	    glBindBuffer(GL_ARRAY_BUFFER, VboId);
	    glBufferData(GL_ARRAY_BUFFER, bufferSize, 0, GL_STATIC_DRAW);

	    glBufferSubData(GL_ARRAY_BUFFER, offset, 6 * sizeof(unsigned short), tmp_Indices);
	    offset += 6 * sizeof(unsigned short);

	    glBufferSubData(GL_ARRAY_BUFFER, offset, 12 * sizeof(float), tmp_Positions);
	    glEnableVertexAttribArray(0);
	    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, (void*)offset);

	    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, VboId);
	    glBindBuffer(GL_ARRAY_BUFFER, 0);
	    glBindVertexArray(0);
	    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);

    // Bind default framebuffer & shader program
	    glBindFramebuffer(GL_FRAMEBUFFER, 0);
	    glUseProgram(programId);

    #if WEB
	    std::function<void()> mainLoop = [&]()
    #else
	    while (true)
    #endif
	    {
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

		glBindVertexArray(VaoId);

		glGetError(); // Clear any previous errors
		glDrawElements(GL_TRIANGLES, 6, GL_UNSIGNED_SHORT, 0);
		int error = glGetError(); if (error != 0) printf("Error: %i\n", error);

		glBindVertexArray(0);

		glfwPollEvents();
		glfwSwapBuffers(m_Instance);
	    }
    #if WEB
	    ;
	    emscripten_set_main_loop_arg(dispachMain, &mainLoop, 0, 1);
    #endif

	    glDeleteProgram(programId);

	    glDeleteBuffers(1, &VboId);
	    glDeleteVertexArrays(1, &VaoId);

	    return 0;
    }

Simplified to the limit, all error checking taken out (glfw, context, glew, shaders) **except the glDrawElements error checking**. Everything else should work and compile fine, so for the sake of this demo I removed those sections.

This demo compiles on Win7 with no issues, using the shaders hardcoded in the code (vertShaderCode, fragShaderCode).

Compiling using:

    em++ -std=c++11 -s USE_GLFW=3 -s FULL_ES3=1 -s ALLOW_MEMORY_GROWTH=1 --emrun main.cpp -o t.html

This 1-page demo should just work out of the box (_copy+paste, save as main.cpp in the same folder as the em-terminal, compile_) without any additional dependencies or anything, so if anyone could try this out and confirm for me if it works for them in the browser or not, I'd be extremely grateful. I just want to know if it's worth spending time on - or if it's an emscripten bug.

Thank you in advance.

**Comment by ad8e** [comment]
I ran it and get error 1282 as well. No idea if it's your program's fault, I didn't read the code. I have glDrawElementsInstanced working, so I wouldn't necessarily blame the compiler.

**Comment by floooh** [comment]
It's quite common that GL code runs without errors on desktop GL implementations, but fails on WebGL, because WebGL has a lot of additional validations to remove undefined behaviour.

I think the error in your case is that you have indices and vertices in the same buffer object, this is forbidden as per WebGL spec, see here: https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.1
