### ISSUE TITLE
Sourcemap comment not added to .js file with -s WASM=1

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#5914]
Hi,

When I compile my project with `-s WASM=1` the` //# sourceMappingURL=` is missing in the .js file. But the .map file is generated correctly. 

I have no problem when I compile to asm.js.

emcc (Emscripten gcc/clang-like replacement) 1.37.22 (commit d3a5609c5f1cf786de9e205a154e1ffacd80a173)

**Comment by kripken** [comment]
The source map integration stuff should be in the wasm file, not the JS, I believe, when building to wasm. cc @yurydelendik to make sure.

**Comment by yurydelendik** [comment]
The WebAssembly source maps proposal is at https://github.com/WebAssembly/design/pull/1051 . The source map can be referenced from the WASM file itself.

See also examples at https://github.com/yurydelendik/sqlite-playground/blob/master/Makefile and https://github.com/yurydelendik/old-man-sandbox/tree/master/rust-wasm-hey

**Comment by th0mas** [comment]
OK, thanks. After taking a look of the hexdump of my .wasm file, I see trace of sourceMappingURL, but is there an option to set this URL when I compile?

**Comment by kripken** [comment]
I think `--source-map-base` does that.

**Comment by th0mas** [comment]
Perfect, thanks for your help. It seems only Firefox Developer Edition can handle source map reference from .wasm? I was not able to see my C++ files in Chrome or standard Firefox.

**Comment by Becavalier** [comment]
Currently, this feature still only working on Firefox Developer Edition.
