### ISSUE TITLE
Run-time override of TOTAL_MEMORY with wasm

### ISSUE THREAD

**Issue by buu700** [emscripten-core/emscripten#5925]
Relevant to https://github.com/jedisct1/libsodium/issues/631. libsodium.js provides a feature where users can define `sodium` in the global namespace as an object with a custom total memory value, e.g. `window.sodium = {totalMemory: 134217728}`. (This is particularly useful for users of the memory-hard [`crypto_pwhash`](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html), who in many cases will want to give it a higher mem limit than libsodium.js's default `TOTAL_MEMORY`.)

As per the linked issue, since adding support for wasm, that functionality of libsodium.js has stopped working. @jedisct1's investigation found that the root cause seems to be that `TOTAL_MEMORY` is copied directly into the wasm binary, rather than being referenced from `Module.TOTAL_MEMORY` as in the asm.js output.

How much trouble would it be to have the wasm handle this the same way? Would it be as simple as the emscripten runtime writing the number to a static hardcoded index in the wasm binary?

**Comment by dschuff** [comment]
I don't think the intention of TOTAL_MEMORY is to be overridable at runtime? In any case I don't think I'd want that to be the intention for wasm, because as you noticed, the initial size of the memory has to be written into the wasm binary itself.  It's also not just a fixed offset in the binary, because the location depends on the number of types and imports used in the binary. In any case I don't think we should have emscripten modify the binary at runtime anyway, because then you couldn't use streaming compilation (you'd have to load the whole binary into memory and then instantiate). For wasm it makes much more sense just to enable memory growth, because it doesn't come with the performance penalty that it does in asm.js. Then you could grow the memory up to the desired size at runtime if needed. For ideal best results you can also set a maximum limit on the amount of memory growth.

**Comment by buu700** [comment]
Got it, that makes sense. Streaming compilation was my biggest immediate concern as well, but I suppose that this feature could be implemented as an optional flag that isn't supported in combination with streaming.

Implementation-wise, it's too bad it wouldn't be as trivial as changing one fixed offset, but it sounds like it could still be done easily enough by having the compiler save the offset somewhere like `MODULE.WASM_TOTAL_MEMORY_INDEX`.

>For wasm it makes much more sense just to enable memory growth, because it doesn't come with the performance penalty that it does in asm.js. Then you could grow the memory up to the desired size at runtime if needed. For ideal best results you can also set a maximum limit on the amount of memory growth.

Hmm, that's *very* interesting, and sounds like it potentially makes this whole issue moot. Is there any performance penalty or other kind of tradeoff at all? If not, what is the purpose of `TOTAL_MEMORY` with wasm? Is it just a small optimization like the difference between `[]` and `new Array(134217728)`?

**Comment by brion** [comment]
I've seen no apparent performance penalty enabling memory growth on wasm builds for ogv.js's video codecs, where in JS builds I had a similar need to manually bump up the memory limit at high resolutions. I've just rigged my code to drop the memory limit override in wasm mode, while keeping it for asm.js (where growth is still disabled).

Can't speak to the reasons for the max/total/whatever memory options on wasm, it confuses me a bit too. ;)

**Comment by buu700** [comment]
Awesome, glad to hear that! Sounds like there's no reason to keep this open, and I'll just circle back and reopen it if memory growth turns out to be really bad for libsodium.

**Comment by buu700** [comment]
Heard back from @jedisct1 on the libsodium benchmarks:

>I got bad news. The overhead is massive.
>
>`ALLOW_MEMORY_GROWTH` makes Argon2 twice as slow. Many other tests become 3x or 4x slower.
>
>:(

**Comment by brion** [comment]
Hmm, this is with the wasm version? (asm.js will be slower using memory growth, wasm should not.) Same on all browser engines? Does the slowdown kick in only after growth occurs, or before as well?

**Comment by jedisct1** [comment]
Yes, this is with the wasm version. Using Node 9.3.0.

**Comment by dschuff** [comment]
I'd be very interested in getting more details and a reproducer for this, because based on what I know of how V8 implements memory growth, there really shouldn't be any difference in the generated code (unless it's actually the growth itself that is really slow?)
+cc @dtig
