### ISSUE TITLE
shm_open and mmap giving unexpected results

### ISSUE THREAD

**Issue by 7890** [emscripten-core/emscripten#5928]
mmap'ing the same file twice, the second instance doesn't see the file's contents.
I'm trying to figure out if this is a limitation of emscripten or the result of bogus code.

```
#include <stdio.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/shm.h>
#include <string.h>
#include <fcntl.h>

//gcc -o shm_open_test shm_open_test.c -lrt
//emcc -O1 -s ASM_JS=1 -o test/shmopen.html shm_open_test.c

int main()
{
	//shm handle / filename
	char handle[4]={'a','b','c','\0'};

	//create file in shared memory, size 100
	int fd=shm_open(handle, O_CREAT | O_RDWR, 0666);
	if(fd<0)
	{
		fprintf(stderr, "could not get shared memory file descriptor.\n");
		return 1;
	}

	int r=ftruncate(fd, 100);
	if(r!=0)
	{
		fprintf(stderr, "could not ftruncate shared memory file descriptor.\n");
		return 1;
	}

	//map file
	void *ptr_mmap = mmap(NULL, 100, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if(ptr_mmap==NULL || ptr_mmap==MAP_FAILED)
	{
		fprintf(stderr, "map failed.\n");
		return 1;
	}

	//write something
	memcpy(ptr_mmap,"hello",5);
	//sync back to file (?)
	msync(ptr_mmap,100,MS_SYNC);

	//open existing file in shared memory
	int fd2=shm_open(handle, O_RDWR, 0666);
	if(fd2<0)
	{
		fprintf(stderr, "could not get shared memory file descriptor.\n");
		return 1;
	}

	//map file
	void *ptr_mmap2 = mmap(NULL, 100, PROT_READ | PROT_WRITE, MAP_SHARED, fd2, 0);
	if(ptr_mmap2==NULL || ptr_mmap2==MAP_FAILED)
	{
		fprintf(stderr, "map failed.\n");
		return 1;
	}

	//read
	char buf[100];
	memcpy(buf,ptr_mmap2,100);
	fprintf(stderr,"found: %s\n",buf);

	//expected: found: hello
	//gcc:      found: hello
	//emcc:     found: 
}

```

**Comment by kripken** [comment]
If it works natively, it's possibly a JS limitation - we don't have access to proper mmap capabilities, and our mmap code just handles simple common cases like mapping a file once.

However, mapping a file twice (without special flags) seems like it should be possible to support. Look for `mmap` in `src/*` if you want to investigate that.

**Comment by 7890** [comment]
@kripken thanks for the suggestions.
I look at https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/system/lib/libc/musl/src/mman/shm_open.c#L29 and https://github.com/kripken/emscripten/blob/7f89560101843198787530731f40a65288f6f15f/system/lib/libc/musl/src/mman/mmap.c.
There is no error at either compile or runtime.. i don't understand which flags are special in this case.

**Comment by 7890** [comment]
Reading again.. it is currently not supported to mmap the same file multiple times.

**Comment by juj** [comment]
Hey, let me reopen this to keep track of the issue, in ASMFS we'll need mmap support as well, so this will be a good test case. Thanks!

**Comment by 7890** [comment]
ok :)
