### ISSUE TITLE
mouse jumping in chrome

### ISSUE THREAD

**Issue by lomateron** [emscripten-core/emscripten#5943]
using precompiled SDK 1.37.22
using emscripten_set_mousemove_callback
for games where you move the camera with mouse, it will jump around
tested this on chrome and in firefox, only happens in chrome
I can't figure out what makes it jump
it doesn't looks like holding any key or not affects the mouse jumping around

**Comment by saschanaz** [comment]
Possibly related with #5737?

**Comment by lomateron** [comment]
this is what triggers the jumping
after chrome captures the mouse
if the pointer was visible the jumping will happen when it touches the edge of the window
so the jumping will happen more if you reduce the width the window and move the mouse to the left or right
it is the same when the window's height is reduced

**Comment by saschanaz** [comment]
Not sure I understand, your source code and a repro video or GIF may help...

**Comment by juj** [comment]
Is there a specific Chrome or Emscripten version where this started occurring, or has this happened with all Chrome and Emscripten versions? (i.e. a recent regression perhaps, or was it always there?)

**Comment by lomateron** [comment]
you can see the bug here
https://kripken.github.io/BananaBread/cube2/bb.html
http://www.quakejs.com/
in BananaBread example put it in fullscreen then move the mouse only up and you will see how the camera will go from pointing to the sky to pointing to the floor in an instant

**Comment by saschanaz** [comment]
I tried the BananaBread demo in fullscreen mode and can confirm that Chrome only exhibits the strange behavior.

**Comment by lomateron** [comment]
just discovered that the bug even happens when not using emscripten just pure javascript only on chrome
like in this demo
https://mdn.github.io/dom-examples/pointer-lock/

**Comment by kripken** [comment]
Looks like this is a chrome bug then, @lomateron please file a bug on the chromium tracker and link to it here.
