### ISSUE TITLE
[Feature Request] API for Javascript to return custom object.

### ISSUE THREAD

**Issue by kkimdev** [emscripten-core/emscripten#5953]
We wanted to create a Javascript function that returns a custom object, that can be called from C++ but couldn't find an appropriate API.  Also there is an open issue for that https://github.com/kripken/emscripten/issues/1296

We tried working around by examining how `val::global(...)` is implemented, and here is our hacky working code:

test.cpp
```C++
#include <emscripten/val.h>
#include <emscripten.h>

using namespace emscripten;

extern "C" {
internal::EM_VAL getCustomObj();
}

int main()
{
    val object = val::take_ownership(getCustomObj());
    object.set("answer", val(42));
    emscripten_run_script("console.log(window.answer)");
}
```

test.js
```javascript
mergeInto(LibraryManager.library, {
  getCustomObj: function() {
      return __emval_register(window);
  }
});
```

to build:
`em++ test.cpp --js-library test.js -std=c++14 --bind -o index.html`

Would it make sense to have API support so that the above example can be done without messing `internal::EM_VAL` and `__emval_register`?

**Comment by kkimdev** [comment]
@Deepayan-Ghosh

**Comment by AlexPerrot** [comment]
The approach I would suggest would be to create a C++ class fitting your needs and exposing it through embind. Then use an instance of this class rather than a js object.

**Comment by kkimdev** [comment]
@AlexPerrot I'm not sure if that fits our situation though.

We're creating a 3D game, and all the logics are managed on C++ side, and Javascript side is a very thin render layer, using BabylonJS.

So for every object in the game, there is corresponding C++ class instance, for example, say

```c++
class Player {
...
};

Player  player= new Player(...);
```

and it has all the informations about Player, including rendering mesh, which is a Javascript instance http://doc.babylonjs.com/classes/3.0/mesh .  Currently we're storing and manipulating the Mesh JS instance directly from C++ side, e.g., `this.mesh["position"].set("x", 0.0);`, .  We are planning to wrap that in a C++ class so that it has nice C++ API boundary, but it doesn't change the that a C++ class owns a JS instance.  Alternatively, we can maintain a dictionary on JS side, that maps custom ID to JS object and let C++ class instances keep those IDs, but I feel like that's an unnecessary indirection that doesn't add any value.

**Comment by kkimdev** [comment]
Anyways, there is already val::global('...") to obtain a js object from C++ side, wouldn't it make sense to also support API to get val from non globals?

**Comment by brion** [comment]
I think the trick here is that JS library functions are called directly like C functions, so they don't get any embind magic to map the return value -- so you can't idiomatically return an object from the function...

Does the JS function need to be implemented directly as a library function, or can it be a function reference provided at runtime by calling code?

If the latter, you can receive the reference as a `val` and call it directly, which will return another `val` with the target object.

This can be obtained from a global like so:

```cpp
#include <emscripten/val.h>
#include <emscripten.h>

using namespace emscripten;

int main()
{
    val getCustomObj = val::global("getCustomObj");
    val object = getCustomObj();
    object.set("answer", val(42));
    emscripten_run_script("console.log(window.answer)");
}
```

```js
function getCustomObj() {
	return window;
}
```

```bash
em++ test.cpp --post-js test.js -std=c++14 --bind -o index.html
```

Or providing the callback as a constructor parameter:

```cpp
#include <emscripten/val.h>
#include <emscripten/bind.h>
#include <emscripten.h>

using namespace emscripten;

class Thingy {
	val objectGetter;
public:
	Thingy(val getter);
	void doThings();
};

Thingy::Thingy(val getter)
: objectGetter(getter)
{
}

void Thingy::doThings()
{
	val object = objectGetter();
	object.set("answer", val(42));
	emscripten_run_script("console.log(window.answer)");
}

int main()
{
	// no-op
}

EMSCRIPTEN_BINDINGS(test) {
	class_<Thingy>("Thingy")
		.constructor<val>()
		.function("doThings", &Thingy::doThings);
}
```

```js
Module.onRuntimeInitialized = function() {
	var thingy = new Module.Thingy(function() {
		return window;
	});
	thingy.doThings();
};
```

```bash
em++ test.cpp --post-js test.js -std=c++14 --bind -o index.html
```

Alternately we could think about easier ways to declare compile-time library functions that run through the embind wiring and can handle object parameters and return values...
