### ISSUE TITLE
USE_PTHREADS=1 fails with LLVM ERROR: Cannot select ...

### ISSUE THREAD

**Issue by chrisber** [emscripten-core/emscripten#5956]
After the latest merge of the pull request `Initial support for pthreads with wasm` #5710. 
I was curious about thread support in webassembly and  tried to compile the the following example [cppreference storage duration ](http://en.cppreference.com/w/cpp/language/storage_duration), but compiling and executing with thread support only succeeded with asm as target.
 Is thread support with the native webassembly backend currently limited or did I make a mistake?

emsdk `sdk-incoming-64bit` compiled from source (https://github.com/juj/emsdk/commit/d3a5609c5f1cf786de9e205a154e1ffacd80a173)
emscripten/incoming (https://github.com/kripken/emscripten/commit/1754e325023ee28aa36943a1ea18e5742181d4b6)
clang/fastcomp/src (https://github.com/kripken/emscripten-fastcomp/commit/7153769ed5cb94eb920b633bc0befdb71a30657b)
Firefox nightly Version 59.0a1

### Example.cc:
```c++
#include <iostream>
#include <string>
#include <thread>
#include <mutex>
 
thread_local unsigned int rage = 1; 
std::mutex cout_mutex;
 
void increase_rage(const std::string& thread_name)
{
    ++rage; // modifying outside a lock is okay; this is a thread-local variable
    std::lock_guard<std::mutex> lock(cout_mutex);
    std::cout << "Rage counter for " << thread_name << ": " << rage << '\n';
}
 
int main()
{
    std::thread a(increase_rage, "a"), b(increase_rage, "b");
 
    {
        std::lock_guard<std::mutex> lock(cout_mutex);
        std::cout << "Rage counter for main: " << rage << '\n';
    }
 
    a.join();
    b.join();
}
```

### Build from source for asm : 

```bash
 git clone https://github.com/juj/emsdk.git
 cd emsdk
./emsdk install sdk-incoming-64bit binaryen-master-64bit
./emsdk activate sdk-incoming-64bit binaryen-master-64bit
. ./emsdk_env.sh
emcc -v -std=c++11  -01 \
-s USE_PTHREADS=1 \
-s PROXY_TO_PTHREAD=1 \
-s VERBOSE=1 \
example.cc -o example.html
```
Compiles and runs successfull when optimization is set  to-01 or above (fails with -O0).

Program output:
```
Preallocating 1 workers for a pthread spawn pool.
Preallocating 1 workers for a pthread spawn pool.
Preallocating 1 workers for a pthread spawn pool.
Rage counter for main: 1
Rage counter for a: 2
Rage counter for b: 3
```

### Build from source with asm2wasm backend: 
```bash
 git clone https://github.com/juj/emsdk.git
 cd emsdk
 ./emsdk install sdk-incoming-64bit binaryen-master-64bit
 ./emsdk activate sdk-incoming-64bit binaryen-master-64bit
 . ./emsdk_env.sh
 DEBUG=1 emcc -v -std=c++11   \
-s USE_PTHREADS=1 \
-s PROXY_TO_PTHREAD=1 \
-s WASM=1 \
-s VERBOSE=1 \
example.cc -o example.html
```
Compiles but the program is not executable.

### Build from source with native wasm backend: 
```bash
 git clone https://github.com/juj/emsdk.git
 cd emsdk
./emsdk install --enable-wasm sdk-incoming-64bit binaryen-master-64bit
./emsdk activate --enable-wasm sdk-incoming-64bit binaryen-master-64bit
. ./emsdk_env.sh
DEBUG=1 EMCC_WASM_BACKEND=1 emcc -v -std=c++11   \
-s USE_PTHREADS=1 \
-s PROXY_TO_PTHREAD=1 \
-s WASM=1 \
-s VERBOSE=1 \
example.cc -o example.html

Compilation fails with error:
```
`LLVM ERROR: Cannot select: 0x55d8f3285d00: i32 = GlobalTLSAddress<i32* @rage> 0
In function: _ZTW4rage`

It seems like an issue with the statement `thread_local unsigned int rage = 1; `

**Comment by juj** [comment]
The missing piece here is the `thread_local` keyword, which is not yet supported in our multithreading work. This is on the TODO list though, since it's quite an important one. Thanks for the test case!

**Comment by trailcode** [comment]
I am having the same problem. If I compile with -s WASM=1 it does not work.

**Comment by tlively** [comment]
Actually, this should be fixed now that we support thread_locals.
