### ISSUE TITLE
LinkError: WebAssembly Instantiation: Import #1 module="env" function="setTempRet0" error: function import requires a callable

### ISSUE THREAD

**Issue by tuananh** [emscripten-core/emscripten#6024]
Can someone help me on how to debug this error?

I build my `test.wasm` with `SIDE_MODULE=1` and `-s "BINARYEN_METHOD='native-wasm,asmjs'"`

```js
const fs = require('fs')
const toUint8Array = require('base64-to-uint8array')
const buf = fs.readFileSync('./test.wasm')

const imp = {
    env: {
        memoryBase: 0,
        tableBase: 0,
        memory: new WebAssembly.Memory({ initial: 256 }),
        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
    }
}

WebAssembly.instantiate(toUint8Array(buf), imp).then(i => {
    console.log(i.instance.exports._fib(10))
})
```

**Comment by kripken** [comment]
`setTempRet0` is an import in that module, which you must provide. It's a temp value that is set for certain 64-bit operations when crossing from JS to wasm and back. For example, when wasm returns a 64-bit value to JS, it returns the low 32 bits and calls `setTempRet0` with the higher 32 bits.

You can view the wasm source to see in more detail what imports there are and how they are used.

**Comment by tuananh** [comment]
@kripken: Thanks. Do you have an example of `setTempRet0` function that i could check?

**Comment by kripken** [comment]
The simplest thing is to look in the JS that is emitted in a non-`SIDE_MODULE` file. So just build `emcc tests/hello_world.c` for example, and read the code mentioning `setTempRet0` there.
