### ISSUE TITLE
Got stuck at "GCC >=5 is required" error

### ISSUE THREAD

**Issue by raj4all** [emscripten-core/emscripten#6034]
Hi,
We are trying to compile a piece of cpp code using GCC.
it requires GCC version 5 or > as a prerequisite.
My machine got GCC 5 and 6 but still I couldnt pass on that check.

Is there a way to link the GCC version to get it going?

**Comment by curiousdannii** [comment]
Emscripten does not use GCC. Are you sure you're posting in the right place?

**Comment by prelution** [comment]
I am also working on this project and let me try to elaborate:

The code that we are trying to convert to javascript contains a header with the following line:

```
// GNU GCC/G++
#if defined(__GNUC__) && (__GNUC__ < 5)
#error "Requires __GNUC__ >= 5" 
#endif
```

However, apparently emcc defines the __GNUC__ value to 4.  This is seen from the following commands in the terminal (Ubuntu 14.04):

```
james@james-HP-Z820-Workstation:~/repos$ g++ -E -dM t.cpp | grep GNUC
#define __GNUC_PATCHLEVEL__ 0
#define __GNUC__ 6
#define __GNUC_STDC_INLINE__ 1
#define __GNUC_MINOR__ 3

james@james-HP-Z820-Workstation:~/repos$ ./emscripten/emcc -E -dM t.cpp | grep GNUC
#define __GNUC_GNU_INLINE__ 1
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC__ 4
```

I would like to note that we are building from source described here: [https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_linux.html#building-emscripten-on-linux](url).  We have even tried rebuilding the Fastcomp against gcc-6 instead for gcc-4.8 with no avail.

**Comment by kripken** [comment]
Oh, I see, the problem occurs when porting an application that expects a newer gcc?

Can you just edit that source code to skip the check? There's a good chance clang already supports the things it needs. Or does it actually depend on very new gcc features?

Emscripten itself doesn't declare a gcc version, I believe, that all comes from clang. It's possible a newer version of clang supports a newer gcc version. You can try upstream clang/llvm with the wasm backend, or you can try https://github.com/kripken/emscripten-fastcomp/pull/199 which is the next merge. Also, worth seeing if upstream native clang (just building natively) works, to see it isn't a gcc-specific codebase.

**Comment by saschanaz** [comment]
It seems clang 5 still has the value 4.

```
$ clang-5.0 -E -dM emscripten/tests/hello_world.c | grep GNUC
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_PREREQ(maj,min) ((__GNUC__ << 16) + __GNUC_MINOR__ >= ((maj) << 16) + (min))
#define __GNUC_STDC_INLINE__ 1
#define __GNUC_VA_LIST 1
#define __GNUC__ 4
```
