### ISSUE TITLE
External control of STATICTOP and global initializers

### ISSUE THREAD

**Issue by tbfleming** [emscripten-core/emscripten#6043]
I have an unusual case with cib: I load a separately-generated binary into emscripten's JS runtime. The STATICTOP and the global initializer set are different from what the JS runtime expects. Here's a patch that allows external code to take control of these.

Right now the patch's history is tangled up; I'll rebase it to a fresh branch and create a pull request if it's useful to others.

https://github.com/tbfleming/cib-emscripten/commit/23705baf9d37490d540e94cd2d9f3e8ba4179923

**Comment by kripken** [comment]
Needs more thought, but there is a downside to making this dynamic. Right now it's a statically known property, and I've been planning to use that to optimize more.

Why are you loading another binary into the runtime, instead of building it the regular way?

**Comment by tbfleming** [comment]
It didn't have all the exports I needed to hook in global variables from the RTL into user code (e.g. ```cout```). I solved it by creating a new linker which exports the appropriate globals.

**Comment by tbfleming** [comment]
This is probably an A-B problem. I asked for A when I really should be doing B. Even if it's not, I don't want to hinder future optimizations.

**Comment by kripken** [comment]
What exports were missing? Making more stuff exportable (if not by default) would be good in most cases.

**Comment by tbfleming** [comment]
It's missing all global exports; none are present. e.g. ```_ZNSt3__24coutE``` (```std::__2::cout```). It's also missing some function exports such as ```_ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_```.

I ended up having to export all non-local functions and globals, including the ones with hidden visibility.

**Comment by tbfleming** [comment]
Something that helped: my linker's input is the entire set of library ```.o``` files in wasm format. This stops llvm from optimizing away anything.

**Comment by kripken** [comment]
Does `EXPORT_ALL` do what you want?

**Comment by kripken** [comment]
Also `LINKABLE` may be relevant.

**Comment by tbfleming** [comment]
I just tried adding both. No change. Here's the set I tried:

```
    target_link_libraries(runtime PRIVATE
        "-s MODULARIZE=1"
        "-s ALLOW_MEMORY_GROWTH=1"
        "-s EXPORT_ALL=1"
        "-s LINKABLE=1"
        "-s MAIN_MODULE=1"
        "-s EXTRA_EXPORTED_RUNTIME_METHODS='[\"FS\"]'"
    )
```

**Comment by tbfleming** [comment]
I also had ```EMCC_FORCE_STDLIBS=1``` in the environment.

**Comment by kripken** [comment]
Hmm, EXPORT_ALL should export everything it is aware of. Are those compiled functions you are not seeing exported, or js runtime functions, or something else?

Might be worth building with and without that option and diffing the JS output, to see what's different. There should be a bunch of new exports, and then the question is why isn't what you want among them.

**Comment by tbfleming** [comment]
The .js and .wasm files are identical with and without ```-s EXPORT_ALL=1 -s LINKABLE=1```.

```_ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_``` lives in ```emscripten/system/lib/libcxx/string.cpp```:

```
_LIBCPP_BEGIN_NAMESPACE_STD
...
template class _LIBCPP_CLASS_TEMPLATE_INSTANTIATION_VIS basic_string<char>;
```

```_ZNSt3__24coutE``` lives in ```emscripten/system/lib/libcxx/iostream.cpp```:

```
_LIBCPP_BEGIN_NAMESPACE_STD
...
_ALIGNAS_TYPE (ostream) _LIBCPP_FUNC_VIS char cout[sizeof(ostream)]
```

These definitions in ```emscripten/system/lib/libcxx/__config``` are active, both when building the system libraries and when building runtime.cpp:
```
#define _LIBCPP_CLASS_TEMPLATE_INSTANTIATION_VIS
#define _LIBCPP_FUNC_VIS __attribute__ ((__visibility__("default")))
```

I have this code in ```runtime.cpp``` to try to force in ```cout```:

```
int main() { std::cout << ""; }
```

**Comment by kripken** [comment]
> The .js and .wasm files are identical with and without -s EXPORT_ALL=1 -s LINKABLE=1.

Maybe the params aren't being consumed? Building a small hello world C program, those options have a radical effect on the size of the output (much bigger). Do you see something different on such a program?

**Comment by tbfleming** [comment]
Yes. This is with the wasm backend.

```
#include <iostream>

int main() { std::cout << "Hello"; }
```

```
em++ hello.cpp -o a.js -s EXPORT_ALL=1 -s LINKABLE=1 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s MAIN_MODULE=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS']"
```

```
em++ hello.cpp -o b.js -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s MAIN_MODULE=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['FS']"
```

The only difference in the output is where it has the filenames:

```
<   var wasmTextFile = 'a.wast';
<   var wasmBinaryFile = 'a.wasm';
<   var asmjsCodeFile = 'a.asm.js';
---
>   var wasmTextFile = 'b.wast';
>   var wasmBinaryFile = 'b.wasm';
>   var asmjsCodeFile = 'b.asm.js';
```

**Comment by kripken** [comment]
Oh, the wasm backend. Yeah, I think it doesn't support those options.

**Comment by tbfleming** [comment]
I'm falling off my chair :). It's part of my "unusual case".

**Comment by kripken** [comment]
Sorry, yeah, sometimes things are confusing with the new wasm backend. It's not the default for a reason, it's not quite ready yet.

Is this for building your clang, or what is being built? I would build clang using fastcomp normally, but it does make sense to build a clang that uses the wasm backend (since it's more standalone and easier to get running on a web page).

**Comment by tbfleming** [comment]
It's for building the runtime library. Here's the various parts of the system:

* browser clang: normal app generated using emscripten's wasm backend flow. The only needed exports are the compiler entry point and the FS js functions.
* rtl 1: generated using emscripten's wasm backend flow. I load rtl 2's .wasm into rtl 1's js.
* rtl 2: I run the rtl sources through clang, which produces a large set of .wasm files. I feed them through cib-link, which produces a single .wasm with all non-local exports (function and global) present, including weak exports and hidden exports.
* browser clang's output: unlinked wasm
* Run button: links browser clang's output to the rtl.

**Comment by kripken** [comment]
So which of 1-5 are we discussing here? I am guessing it is 1 or 2 as they mention emscripen and the wasm backend? Could the relevant of those be done using fastcomp instead, so that those options work?

**Comment by tbfleming** [comment]
Loading rtl 2's .wasm into rtl 1's .js is why I patched in control of STATICTOP and the global initializers. I doubt if I compile the rtl with fastcomp that it'd be compatible with linking to browser clang's output (e.g. i64 difference).

**Comment by kripken** [comment]
I see now, thanks. Yeah, you need those to be from the same type of build.

It might be worth looking into EXPORT_ALL for the wasm backend, but we should find out if that fits with the plans for that backend first.
