### ISSUE TITLE
Cannot use setjmp with SIDE_MODULE=1

### ISSUE THREAD

**Issue by CGamesPlay** [emscripten-core/emscripten#6047]
Hello, I have a strange case that I believe is a bug, unless I'm misunderstanding something. Given a simple file that calls `setjmp`:

```
#include <setjmp.h>

int main() {
  jmp_buf b;
  setjmp(b);
  return 0;
}
```

If you compile this file with `SIDE_MODULE=1`, you get an assertion failure in `asm2wasm`:

```
$ emcc -s WASM=1 -O2 -s SIDE_MODULE=1 test.c
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
Assertion failed: (infos->count(curr->target) > 0), function visitCall, file /Users/rpatterson/.emscripten_ports/binaryen/binaryen-version_40/src/passes/Inlining.cpp, line 89.
Traceback (most recent call last):
  File "/usr/local/bin/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emcc.py", line 1886, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/usr/local/Cellar/emscripten/1.37.28/libexec/emcc.py", line 2358, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/rpatterson/.emscripten_ports/binaryen/binaryen-version_40/bin/asm2wasm', 'a.out.asm.js', '--total-memory=16777216', '--trap-mode=allow', '-O2', '--table-max=-1', '--mem-max=-1', '-o', 'a.out.wasm']' returned non-zero exit status -6

$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.37.28 ()
```

This is confusing to me because the following works just fine:
```
$ cat test.c
#include <setjmp.h>

int main() {
  jmp_buf b;
  _setjmp(b);
  return 0;
}

$ emcc -s WASM=1 -O2 -s SIDE_MODULE=1 test.c
WARNING:root:BINARYEN_ASYNC_COMPILATION disabled due to user options. This will reduce performance and compatibility (some browsers limit synchronous compilation), see https://github.com/kripken/emscripten/wiki/WebAssembly#codegen-effects
```

**Comment by kripken** [comment]
Looks like this is a bug in our setjmp code. First, the second example won't work - we must see `setjmp` calls statically, and I'm not sure what `_setjmp` is, but it just emits a call to it. What needs to happen is `setjmp` be seen by the compiler, and then we emit all the code for being able to jump back to where it is, and that includes allocating a buffer - which is where we use `malloc`. The bug is that we don't ensure that `malloc` is imported.

To fix this, the LowerEmSetjmp pass in fastcomp can see if we find a setjmp anywhere in the program, and if so, add a declaration for malloc.

**Comment by CGamesPlay** [comment]
This is interesting, so I can work around the bug in `-O1` and below by using `free(malloc(0))` in an uncalled function. However, the error message is actually different in `-O2` and above:

    Assertion failed: (infos->count(curr->target) > 0), function visitCall, file /Users/rpatterson/.emscripten_ports/binaryen/binaryen-version_40/src/passes/Inlining.cpp, line 89.

Any ideas why `-O2` would cause this different error?

**Comment by kripken** [comment]
Hmm, yes, adding a `malloc` should work around this. The problem is that in -O2 the optimizer removes your workaround ;) so you need to be crafty. This seems to work:
```
#include <setjmp.h>
#include <stdlib.h>

int main() {
  volatile int x;
  x = (int)malloc(0);
  free((void*)x);
  jmp_buf b;
  setjmp(b);
  return 0;
}
```

**Comment by froydnj** [comment]
I'm not seeing the same error as the original report with the latest release, I get:

```
invalid call target: $_malloc
Traceback (most recent call last):
  File "/home/froydnj/src/emsdk-portable/emscripten/1.37.33/emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "/home/froydnj/src/emsdk-portable/emscripten/1.37.33/tools/python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "/home/froydnj/src/emsdk-portable/emscripten/1.37.33/tools/python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "/home/froydnj/src/emsdk-portable/emscripten/1.37.33/emcc.py", line 1878, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/froydnj/src/emsdk-portable/emscripten/1.37.33/emcc.py", line 2346, in do_binaryen
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/froydnj/src/emsdk-portable/clang/e1.37.33_64bit/binaryen/bin/asm2wasm', 'a.out.asm.js', '--total-memory=16777216', '--trap-mode=allow', '-O2', '--table-max=-1', '--mem-max=-1', '-o', 'a.out.wasm']' returned non-zero exit status -6
```

I attempted to insert `malloc` into the compilation unit in `LowerEmSetjmp`, but that didn't seem to change anything.

**Comment by kripken** [comment]
Hmm, I think SIDE_MODULE and dynamic linking in general are too far off to be worth spending much time on now. That is, there's too much other stuff blocking them from being generally useful.

We should keep this open though and revisit once dynamic linking is considered stable. At that point the problem might be handled in a different way.
