### ISSUE TITLE
When building with just static libraries all symbols from system libraries are included

### ISSUE THREAD

**Issue by Stuk** [emscripten-core/emscripten#6055]
If you link just a static library you would expect that all symbols from the `.a`/library files would be included in the build, but because of the code linked below, all symbols from all system libraries are also included. This leads to a lot of unnecessary code/filesize in the built files.

https://github.com/kripken/emscripten/blob/incoming/emcc.py#L1512
https://github.com/kripken/emscripten/blob/incoming/tools/shared.py#L1805

I've tried making a reduced test case for this issue and although the debug output shows that something is wrong, I could not reproduce the filesize issue I'm seeing in my full build. I'm filing an issue just in case there is something is wrong.

test.cpp:
```cpp
#include <iostream>
#include <emscripten.h>

void EMSCRIPTEN_KEEPALIVE greet() {
    std::cout << "hello\n";
}
```

```bash
# more objects included
em++ test.cpp -o test.o
emar cr test.a test.o
env EMCC_DEBUG=1 em++ test.a -o test-a.js

# fewer
env EMCC_DEBUG=1 em++ test.cpp -o test-cpp.js
```

If you look for the `DEBUG:root:adding object` output, you can see that building from the static library adds a lot more objects from the system libraries.

**Comment by kripken** [comment]
I can't remember why this behaves that way, but I'm pretty sure it's tested. So disabling it and running the test suite could help find out why.
