### ISSUE TITLE
Unused argument errort for -march=native option flag

### ISSUE THREAD

**Issue by ajz01** [emscripten-core/emscripten#6071]
Hello, I'm running into "unused argument" error when using emcc to compile a project whose compiler flags include the -march=native. Is this flag supported by emcc? I was able to build the project on the same machine using the same cmake generated makefile using g++. Should I try applying all the flags -march=native generates explicitly instead? Thanks for any help.

**Comment by kripken** [comment]
`-march=native` means to emit native code for the current platform, so emcc doesn't know what to do with it - it can only emit asm.js or wasm.

Hopefully you can just make the project not emit that flag, but the bigger question is why it emits it, maybe you need more changes for cross-compiling.

**Comment by ajz01** [comment]
Thanks. I was able to suppress the error and produce the wasm, but I think you're correct that there's a more specific reason the developers of the project I'm trying to build included the flag since without it I run into some run-time errors that I can't figure out. I'm planning on trying this some more to see if I can figure it out. The project that I'm trying to build is called OGDF. It's a popular graph drawing framework and it looks like some others have been able to get earlier versions built to asm.js, so I'll see if those solutions might help me build the most recent release. Thanks again.
