### ISSUE TITLE
Google Chrome and tabs switching

### ISSUE THREAD

**Issue by Invi1337** [emscripten-core/emscripten#6076]
Good day. Is it possible to detect when browser tab with my application becomes active?
I have a following problem:
There are some timers on my page. When user switches tab to another - all activity on my page stops. And when user switches to my application again - he sees same timer values as before switching. I can send request to server and update these timer values, but I don't understand how to detect moment of tab switching.

**Comment by curiousdannii** [comment]
Throttling timers in inactive tabs is by design, and is usually a good thing. If you need timers to continue regardless you might be able to run them in a worker.

On detecting tab switches, see [this Stackoverflow question](https://stackoverflow.com/q/1060008/2854284).
