### ISSUE TITLE
Tutorial contains error

### ISSUE THREAD

**Issue by zwhitchcox** [emscripten-core/emscripten#6079]
So, the tutorial contains an error when I first run emscripten (1.37.28), it gives the error 

```
stdio streams had content in them that was not flushed. you should set NO_EXIT_RUNTIME to 0 (see the FAQ), or make sure to emit a newline when you printf etc.
```

It didn't say anything about the error in the tutorial, so it doesn't seem like that was intended, but if so, I can see where I can build with the `-s` flag, but that seems like a lot for "hello, world", so just wanted to be sure.

**Comment by zwhitchcox** [comment]
Note: it did work when I compiled with `-s NO_EXIT_RUNTIME=0`

**Comment by curiousdannii** [comment]
The default was recently changed: #5878.

The docs need an update, and maybe the tutorial code should be tested as is to prevent this kind of thing in the future?

**Comment by kripken** [comment]
@zwhitchcox Which part of the tutorial caused this? It seems like the printfs do have newlines in them, so I'm not sure how that could happen. Although the files example does use putchar, was it there?

@curiousdannii Good idea about testing, hopefully there's a way.

**Comment by zwhitchcox** [comment]
For me it happened with printf, even with the new lines

**Comment by kripken** [comment]
Very strange, printf with a newline should work, and we do  test that heavily. So maybe it is something on your local system. What node.js version was used? (or was it another shell?)

**Comment by zwhitchcox** [comment]
I didn't know you could use node.js for that. I was just using em++
