### ISSUE TITLE
emsdk installs wrong nodejs on ARM linux (easy workaround)

### ISSUE THREAD

**Issue by carangil** [emscripten-core/emscripten#6089]
The installer downloaded llvm and other sources, and built sucessfully.  However, the x86 version of nodejs was installed instead of ARM.  This was on Ubuntu ARM (inside crouton xenial chroot on arm chromeos).  I instead installed nodejs into the chroot from Ubuntu's ARM repo, and changed the emscripten environment variables to use the system's node instead of emsdk's.  Works great!  I can now write C code, and run it in the chromeos browser as a proper web app.

Just thought you'de want to know that ARM almost works perfectly out-of-the-box.

**Comment by curiousdannii** [comment]
@juj will almost certainly see this, but just for reference, the emsdk has its own repo here: https://github.com/juj/emsdk

**Comment by brion** [comment]
This was fixed a while ago over on emsdk repo, should pull the appropriate arm 32-bit or 64-bit version of node instead of the x86 or x64.
