### ISSUE TITLE
Define posix_spawn stub only when needed

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#6090]
```
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_addopen
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: posix_spawn_file_actions_init
```

Do Emscripten lack these functions, or do I need an option to enable them?

**Edit:** sigaltstack problem is now irrelevant, it was my environment that is problematic.

**Comment by saschanaz** [comment]
libc.symbols defines `posix_*` functions as `U` and lacks sigaltstack.

**Comment by saschanaz** [comment]
I added stubs on library.js as #3819 did but it didn't work for me :/

**Comment by kripken** [comment]
Those `spawn` operations are for spawning a new process, which we can't support. But you should not see clang doing that, or if it does we should work around it. I vaguely remember I had to do that back when I ported it - clang used to open a new process to call itself, and I hacked that out.

**Comment by saschanaz** [comment]
It won't be web compatible but probably can be node.js compatible with its [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) API. Hmm.

**Comment by saschanaz** [comment]
BTW I cannot just ignore the linker warnings as they become explicit errors with `EMMAKEN_JUST_CONFIGURE=1 EMCONFIGURE_JS=2`.

**Comment by kripken** [comment]
Oh right, we enforce errors in cmake/configure because they depend on error handling. Then we need to add stubs for those that abort if actually called.

**Comment by saschanaz** [comment]
After more investigation I think #3819 is causing this problem. [The CMake script](https://github.com/kripken/emscripten-fastcomp/blob/2075d1ab8f6edd681bbf5ecfffe51c70d78c121b/cmake/config-ix.cmake#L201) checks if `posix_spawn` exists and conditionally process related codes. The current Emscripten defines `posix_spawn` and then lacks other related functions, which causes this odd state.

**Comment by juj** [comment]
> The current Emscripten defines posix_spawn and then lacks other related functions, which causes this odd state. cc: @juj

> Wouldn't it make sense to define posix_spawn only when really crucially needed, as defining stubs breaks conditional processing?

This is a common theme we keep juggling around. Sometimes we go towards runtime aborting stubs to get existing projects to build, and only fail at the very end when/if code ends up actually running such code. This lets large projects build and run without issues as long as they dynamically make sure not to run into such code paths. Other times we'd like to abort as early on as possible - preferably we would not even declare such nonexisting functions in musl headers that we can't support. That way we'd get the earliest possible compilation error for all missing headers that aren't available.

The reason those symbols were added was to make `popen` gracefully fail by setting `errno` to signal at runtime that `popen` is not actually available.

For CMake, you should be able to force the Emscripten configure by passing `-DHAVE_POSIX_SPAWN=0` to your CMake invocation. That makes CMake behave as if that check had been already run and cached to that variable, and `check_symbol_exists()` line should then immediately return without doing anything. Would that work here?

Ideally we'd strip from musl headers all declarations of symbols that we don't have in Emscripten, to provide a "pure" platform of only existing symbols, but that will break many ported projects from being able to build. Those can of course be fixed but it needs code changes and man-hours. Not sure how to balance between these at the moment.

Or I wonder if we'd like to define stubs for `posix_spawn_file_actions_*` as well and that'd work here to mute those warnings?

**Comment by saschanaz** [comment]
`-DHAVE_POSIX_SPAWN=0` helped and also I had to add ` -DHAVE_PTHREAD_H=0 -HAVE_LIBPTHREAD=0 -DPTHREAD_IN_LIBC=0` to disable pthreads (because it doesn't support Node.js).
