### ISSUE TITLE
Need help!, I got a problem when trying to build a project

### ISSUE THREAD

**Issue by cristhian255** [emscripten-core/emscripten#6097]
Hi, I'm trying to build [ffmpeg](https://www.ffmpeg.org/download.html) library using emscripten. This project need to do a "configure" before "make", so using the emscripten [tutorial](http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#building-projects) to build projects, when I run "./emconfigure ./configure" command i got the following errors:

```
/Escritorio/workspace/emsdk-portable/emscripten/1.37.28$ ./emconfigure ./configure
ERROR:root:Exception thrown when invoking Popen in configure with args: "./configure"!
Traceback (most recent call last):
  File "./emconfigure", line 13, in <module>
    emconfigure.run()
  File "/home/prodigy/Escritorio/workspace/emsdk-portable/emscripten/1.37.28/emconfigure.py", line 47, in run
    shared.Building.configure(sys.argv[1:])
  File "/home/prodigy/Escritorio/workspace/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 1607, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or `directory`
```

I got those errors building in Linux, but the same errors appears in Windows.  Any suggest to solve them?

Thanks in advance.

**Comment by saschanaz** [comment]
The command runs `./configure` script, so it should exist on your current working directory.

**Comment by cristhian255** [comment]
It exist, I builded it normally with mingw, and ./configure worked fine.

**Comment by cristhian255** [comment]
Note: I'm using "emcmdprompt.bat" to run commands
Note: I'm also going to the directory where "Makefile" and "configure" files are (the same directory where I builded it using MinGW).

**Comment by saschanaz** [comment]
You are running the command in `/Escritorio/workspace/emsdk-portable/emscripten/1.37.28`, you should run it instead in the directory where the ffmpeg sources are.

**Comment by cristhian255** [comment]
`C:\Users\CrisT` L\Desktop\ffmpeg>emconfigure configure --help
ERROR:root:Exception thrown when invoking Popen in configure with args: "configure --help"!
Traceback (most recent call last):
  File "C:\Users\CrisT L\Desktop\ems\emscripten\1.37.26\\emconfigure", line 13, in <module>
    emconfigure.run()
  File "C:\Users\CrisT L\Desktop\ems\emscripten\1.37.26\emconfigure.py", line 47, in run
    shared.Building.configure(sys.argv[1:])
  File "C:\Users\CrisT L\Desktop\ems\emscripten\1.37.26\tools\shared.py", line 1607, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "C:\Users\CrisT L\Desktop\ems\python\2.7.5.3_64bit\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Users\CrisT L\Desktop\ems\python\2.7.5.3_64bit\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado

C:\Users\CrisT L\Desktop\ffmpeg>`

I moved to the ffmpeg directory but it **still dont work** (I did it before, just didnt copy the "correct" error lines), as you can see I do not have too much experience programming, thanks for trying to help me.

**Comment by juj** [comment]
You can try doing `set EMCC_DEBUG=1` and `set EM_BUILD_VERBOSE=3` in a Windows command prompt (on Linux/macOs, replace `set` with `export`) to dig out deeper levels of logs from the output. Also try triple checking the existence of the `configure` script. Tried doing an `emconfigure ./configure` in my linux box from FFmpeg, which does work, although the resulting `emmake make` does not produce proper Emscripten binaries at least when run on https://github.com/FFmpeg/FFmpeg repository, that one has not been ported to run on the web yet.

**Comment by saschanaz** [comment]
Windows does not support opening extension-less scripts, so that may be the cause. Have you tried the same thing on MinGW, on the ffmpeg directory?

**Comment by cristhian255** [comment]
Yeah @saschanaz, I ran "configure [+FLAGs]" and "make" commands (standing in the same directory) and I builded fmpeg project correctly using MinGW. 

My friend tried the same commands using emscripten on Ubuntu and got almost the same error lines, it isn't about windows support in my opinion, maybe I did something wrong somewhere, or some missing step.

**Comment by cristhian255** [comment]
@kripken Any suggest?

**Comment by juj** [comment]
> @juj Here is a screenshot showing the directory where I'm and where "configure" file is.

The issue here is like @saschanaz mentions: "Windows does not support opening extension-less scripts". In order to achieve this, this should be run in a MSYS/Cygwin shell (my earlier comment somehow thought this was already happening), or better, use a Linux or macOS host system that can run configure scripts.

> He did the same thing (convert ffmpeg lib into javascript using emscripten) 4 years ago, I tested his project but it's kinda slow, so I'm hoping that building a more recent ffmpeg library gives a better perfomance.

Do you know if he upstreamed his work to port to the web to FFmpeg source tree? If not, then the trunk FFmpeg will not have his work and it will not build directly with Emscripten without patching his fixes to it.

**Comment by saschanaz** [comment]
>Do you know if he upstreamed his work to port to the web to FFmpeg source tree

The repo has its own source files: https://github.com/bgrins/videoconverter.js/tree/master/build
