### ISSUE TITLE
Example with fetch API don't work

### ISSUE THREAD

**Issue by jcubic** [emscripten-core/emscripten#6102]
I've use latest emscripten with example on https://kripken.github.io/emscripten-site/docs/api_reference/fetch.html

and have errors like this:

![image](https://user-images.githubusercontent.com/280241/35068408-3f743262-fbd7-11e7-9b18-d388c9eea9bc.png)

**Comment by juj** [comment]
Missing that function suggests that at link time `-s FETCH=1` parameter might not have been present. Can you double check that?

**Comment by jcubic** [comment]
thanks it work, where can I find docs about this parameter, maybe it would be good idea to include it on fetch page.

**Comment by kripken** [comment]
Also, can we make the `emscripten_fetch` methods show an error message if used without `FETCH`? At least at runtime but maybe we can do it at compile time too.
