### ISSUE TITLE
wasm runtime error only in optimized build

### ISSUE THREAD

**Issue by Deins** [emscripten-core/emscripten#6106]
When compiling to wasm with optimizations i get `wasm trap: i32.truncUFloat overflow` (with -s BINARYEN_METHOD='interpret-binary') or `RuntimeError: integer result unrepresentable` (native chrome) error in weird place where there is only integer operations and floats aren't involved. In wasm debug build everything runs fine. It looks like the code is the same (there aren't ifdefs or asserts). I haven't learned how to debug wasm well jet, so i just added bunch of emscripten_logs trying to identify the problem. The code is something like this:

```C
// the code is from library https://github.com/vurtun/nuklear which i am trying to use
#define NK_INTERN static
struct nk_draw_vertex_layout_element {
    enum nk_draw_vertex_layout_attribute attribute; // this is regular C enum
    enum nk_draw_vertex_layout_format format; // this is regular C enum
    nk_size offset; // uint32_t 
};

NK_INTERN int
nk_draw_vertex_layout_element_is_end_of_layout(
    const struct nk_draw_vertex_layout_element *element)
{
    return (element->attribute == NK_VERTEX_ATTRIBUTE_COUNT ||
            element->format == NK_FORMAT_COUNT);
}

NK_INTERN void*
nk_draw_vertex(void *dst, const struct nk_convert_config *config,
    struct nk_vec2 pos, struct nk_vec2 uv, struct nk_colorf color)
{
        void *result = (void*)((char*)dst + config->vertex_size);
        const struct nk_draw_vertex_layout_element *elem_iter = config->vertex_layout;
	LOG("a");
	int val = nk_draw_vertex_layout_element_is_end_of_layout(elem_iter);
	LOG("b"); // THIS IS LAST LOG BEFORE IT CRASHES
    while (0 == val) {
		LOG("c");
                // ... some other stuff, here actually float operations can happen
                elem_iter++;
		LOG("d");
		val = nk_draw_vertex_layout_element_is_end_of_layout(elem_iter);
		LOG("e");
    }
    return result;
}
```
Could it be that it is compiler/optimizer bug, or that the log calls simply aren't in sync with execution? 
Also with `-s "BINARYEN_TRAP_MODE='js'"` and on asm.js the code runs fine, however i would like to fix the code instead of using these options.

P.S. emscripten version:
```Shell
λ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.28
clang version 4.0.0  (emscripten 1.37.28 : 1.37.28)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:\programs\emscripten\clang\e1.37.28_64bit
INFO:root:(Emscripten: Running sanity checks)
```
EDIT: you can view the error live here: http://www.deins.lv/voxwar/bug/web/

**Comment by kripken** [comment]
If you can create a small testcase we can debug, that would be worth looking at, especially since it's odd if that's a float error in code without floats.

But in general this type of thing is probably not a bug, and just that when trapping is allowed (trap mode is "allow", which is the default) the optimizer can move the trap around in ways that can be surprising. You can use the "clamp" trap mode which is almost as fast as "allow" and would avoid these problems.

**Comment by Deins** [comment]
Thanks for reply. 
The code actually does float operations nearby so probably the trap appears in wrong place. It still could be simply nuklear library or me thats at fault. But it is just suspicious how it crashes only in optimized build. Clamp mode runs as expected on both builds. 
So anyway I created small test case here: https://github.com/Deins/nuklear_wasm_bug_test
It is 150loc however the nuklear library itself unfortunately is quite big. For now I guess i will give up and just run with 'clamp' mode.
Thanks for help 👍

**Comment by Deins** [comment]
Question: is it possible compile only one file with  'clamp' mode? I tried it but it seems it has no effect.

**Comment by kripken** [comment]
No, sorry, it's a global option current, for the entire compilation to wasm.

**Comment by EvilPudding** [comment]
I'm having the exact same problem in the exact same nuklear line of code, using clamp is completely out of the options for me though...

**Comment by EvilPudding** [comment]
Is there an attribute that can be used to prevent optimizing a specific function?

**Comment by EvilPudding** [comment]
I've fixed it by adding an `fmin` check in:

```c
    case NK_FORMAT_R32G32B32: {
        nk_uint col[3];
        col[0] = (nk_uint)fmin(val[0]*(float)NK_UINT_MAX, NK_UINT_MAX);
        col[1] = (nk_uint)fmin(val[1]*(float)NK_UINT_MAX, NK_UINT_MAX);
        col[2] = (nk_uint)fmin(val[2]*(float)NK_UINT_MAX, NK_UINT_MAX);
        NK_MEMCPY(attr, col, sizeof(col));
    } break;
    case NK_FORMAT_R32G32B32A32: {
        nk_uint col[4] = {0};
        col[0] = (nk_uint)fmin(val[0]*(float)NK_UINT_MAX, NK_UINT_MAX);
        col[1] = (nk_uint)fmin(val[1]*(float)NK_UINT_MAX, NK_UINT_MAX);
        col[2] = (nk_uint)fmin(val[2]*(float)NK_UINT_MAX, NK_UINT_MAX);
        col[3] = (nk_uint)fmin(val[3]*(float)NK_UINT_MAX, NK_UINT_MAX);
        NK_MEMCPY(attr, col, sizeof(col));
    } break;
```

This is probably a nuklear problem, but it would be helpful to have a way of allowing unchecked overflows in my opinion.

@Deins if the problem persists, try to go around all the formats in that switch and clamping them before the integer cast.
