### ISSUE TITLE
Problem with arguments passed to function

### ISSUE THREAD

**Issue by laSinteZ** [emscripten-core/emscripten#6110]
I am building [https://github.com/warchant/ed25519.git](https://github.com/warchant/ed25519.git) with Emscripten
The project is built with cmake, so I do
```
emcmake cmake . -DTESTING=OFF
emmake make
emcc libed25519.so -s EXPORTED_FUNCTIONS='["_ed25519_create_keypair", "_ed25519_sign", "_ed25519_verify", "_ed25519_derive_public_key"]' -o ed25519.js
```
Since this is a library, I export 4 functions, described in [here](https://github.com/Warchant/ed25519/blob/master/include/ed25519/ed25519/ed25519.h)

But when I try to call those functions from javascript, turns out that `_ed25519_sign` and `_ed25519_verify` in JScode receive 1 more argument than it described in .h file.

In .h file `ed25519_sign` [receives 5 args](https://github.com/Warchant/ed25519/blob/master/include/ed25519/ed25519/ed25519.h#L47), but in js code [it receives 6](https://gist.github.com/laSinteZ/bf306b580add74b64751d640b74b282b#file-part-of-ed25519-js-L1).
in .h file `ed25519_verify` [receives 4 args](https://github.com/Warchant/ed25519/blob/master/include/ed25519/ed25519/ed25519.h#L59), but in js code [it receives 5](https://gist.github.com/laSinteZ/bf306b580add74b64751d640b74b282b#file-part-of-ed25519-js-L92).

Because of that, in my wrapper functions I need to pass 1 more argument like [this](https://github.com/laSinteZ/ed25519.js/blob/master-for-debug/index.js#L69)
(There I pass 0, so function works correctly)

Other option for me was to change variable assignments in generated code like i did [here](https://github.com/laSinteZ/ed25519.js/commit/56073fe563d24da90e172e09def46945c8c0b38a). After changing assignments function started to work correctly. But I don't like idea of changing generated code so I will stick to my "hack" in wrapper.

For other 2 functions, `_ed25519_create_keypair` and `_ed25519_derive_public_key` everything is OK.

**Comment by kripken** [comment]
I believe that is because of the `unsigned long long msglen` - that's a 64-bit integer, which can't be represented in JavaScript. So the compiler emits 2 params, for the lower and higher 32 bits each separately.

**Comment by laSinteZ** [comment]
Thank you for the answer! Seems like you are right. I've [written a small test](https://gist.github.com/laSinteZ/f1dce3a0fbd0b43c469086ec98c979d8#file-test-cpp-L5) to check it and seems that if you call such function for example from main, javascript [explicitly passes additional argument for higher 32 bits.](https://gist.github.com/laSinteZ/f1dce3a0fbd0b43c469086ec98c979d8#file-test-js-L28)
I guess this case should be noted in docs (if it is not done already, sorry, didn't check properly). @kripken I can write docs for this case, so no one will fall for it again :)

**Comment by kripken** [comment]
Yeah, I think this might not be documented - would be great to fix that, thanks! :)

Probably the "[interacting with code](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html)" page is a good location, but if you were looking for this somewhere else, that could be better.

**Comment by laSinteZ** [comment]
Tried to add some documentation. Not sure if I explained everything correctly, but please check it.
