### ISSUE TITLE
Problem with returning JS-Promises to C++

### ISSUE THREAD

**Issue by ismbabf** [emscripten-core/emscripten#6112]
Hi,

currently I'm trying to implement a function in C++, which should return the number of available audio devices.

This is my Code:
```
uint32_t getNumDevices() const {
#ifdef __EMSCRIPTEN__
  int num = EM_ASM_INT_V({
    var numDev;
    navigator.mediaDevices.enumerateDevices()
    .then(function(devices) {
      numDev = devices.length;
      console.log("numDev: " + numDev);    //prints out 3
      return numDev;
    })
        .catch(function(err) {
          console.log(err.name + ': ' + err.message);
        });
      });
      std::cout << "NUM: " << num << std::endl;    //prints out 0
      return num;
    #endif
    }
```

My question is: Since Promises are a common pattern in javascript, what's the recommended way to force C/C++ to wait for the evaluated Promise result?

I've also tried variations of emscripten_run_script_int and emscripten_sync_run_in_main_runtime_thread which had the same problems of returning before the return value is known.

Note: For some reason the javascript logout "numDev" is only printed once the C++ main function exits.

Thanks for any help.

**Comment by curiousdannii** [comment]
You'll need to use EMTERPRETIFY and EMTERPRETIFY_ASYNC, and then write library functions. 

Here's an example from my library: https://github.com/curiousdannii/emglken/blob/a98cc6c75d8214184afaeeb7f6ccbed0cd79e3af/emglken/library.js#L390-L414

**Comment by ismbabf** [comment]
Thanks for the quick response. The problem is that I need pthread support for my application and when I tried to compile with emterpretify an error occured: -s EMTERPRETIFY=1 is not supported with -s USE_PTHREADS>0!
I am using emscripten version "1.37.28".
