### ISSUE TITLE
wasm-validator error: "call param types must match"

### ISSUE THREAD

**Issue by emsdksaber** [emscripten-core/emscripten#6116]
We are using the "latest" emsdk toolchain (clang e1.37.28_64bit, banaryen e1.37.28_64bit, emscripten 1.37.28, emscripten native optimizer e1.37.28_64bit, )

The validation errors look like this

[wasm-validator error in function $__ZN16TCustomShapeList10ReadStreamEP11TReadStreamb] 2 != 4: call param types must match, on 
[i32] (call $invoke_iijj
 [i32] (i32.const 1)
 [i32] (get_local $1)
 [i64] (get_local $38)
 [i64] (get_local $21)
)
(on argument 2)
[wasm-validator error in function $__ZN16TCustomShapeList10ReadStreamEP11TReadStreamb] 2 != 4: call param types must match, on 
[i32] (call $invoke_iijj
 [i32] (i32.const 1)
 [i32] (get_local $1)
 [i64] (get_local $38)
 [i64] (get_local $21)
)
(on argument 3)

I have attached a file which contains the full list of the errors reported for __ZN16TCustomShapeList10ReadStreamEP11TReadStreamb. Also, I have added the wasm code  and the C++ source code for that function. We have tried to match some of the function calls in wasm to the C++ source. Please read the discussion at the end of the file to find which calls we have  matched.

Let me know if you need any further information.

[call-param-types-must match.txt](https://github.com/kripken/emscripten/files/1644285/call-param-types-must.match.txt)
.

**Comment by kripken** [comment]
Can you create a testcase for this that can be built? This is likely a bug in creating those `invoke_*` methods, and to investigate we need to be able to add some logging as the compiler executes.

**Comment by emsdksaber** [comment]
The smaller subset I generated unfortunately does not reproduce the
problem.

Can you post a build that has the logging statements? I can pull and
compile that build, and then generate the logs you need using that build.

Thanks

**Comment by kripken** [comment]
It's not practical, sorry - I need to add print statements based on what I see in previous print statements. It's a messy debugging process ;)

It's ok if you don't have a small testcase, as long as it's one that you can share and that deterministically shows the problem.
