### ISSUE TITLE
Shared memory disabled error with WASM=1 and USE_PTHREADS=1

### ISSUE THREAD

**Issue by melbow** [emscripten-core/emscripten#6119]
Hi, I'm having trouble compiling a basic hello world application with these two features enabled:

ENV (OSX 10.12, emscripten incoming built from src yesterday/today):
```
Adding directories to PATH:
PATH += /Users/mlbw/src/emsdk-portable
PATH += /Users/mlbw/src/emsdk-portable/clang/fastcomp/build_incoming_64/bin
PATH += /Users/mlbw/src/emsdk-portable/node/4.1.1_64bit/bin
PATH += /Users/mlbw/src/emsdk-portable/emscripten/incoming
PATH += /Users/mlbw/src/emsdk-portable/binaryen/master_64bit_binaryen/bin

Setting environment variables:
EMSDK = /Users/mlbw/src/emsdk-portable
EM_CONFIG = /Users/mlbw/.emscripten
EMSCRIPTEN = /Users/mlbw/src/emsdk-portable/emscripten/incoming
BINARYEN_ROOT = /Users/mlbw/src/emsdk-portable/binaryen/master_64bit_binaryen
```

main.cpp
```
#include <iostream>

int main(int argc, char **argv)
{
  std::cout << "Hello World!\n";
  return 0;
}
```

compile command (compiles without errors):
`
EMCC_WASM_BACKEND=1 emcc -std=c++11 -s WASM=1 -s USE_PTHREADS=1 main.cpp -o hello.html
`

output when opening in Firefox Nightly 59.0a1 (2018-01-18) (64-bit)
`
Exception thrown, see JavaScript console
`
`
Console:
LinkError: shared memory is disabled
`

According to this post https://github.com/kripken/emscripten/wiki/Pthreads-with-WebAssembly I think this should work OOTB, I must be missing something.

Many thanks

**Comment by kripken** [comment]
The browser is reporting that shared memory is disabled - I believe that's because of the recent Spectre vulnerabilities. You can flip a pref to restore it, but that does make you vulnerable to the attack, so except for a testing environment that's not recommended.

Perhaps we should mention this in the docs - it's not likely this will change in the near future.

**Comment by melbow** [comment]
Ahh yeah, had scoured the Preferences section but it's on the about:config page.

I agree, I think a note in the docs would be good, I feel a PS on the page that I linked would be enough.

Thanks for the help
