### ISSUE TITLE
Dangerous ~/.emscripten_cache conflicts when switching emscripten version

### ISSUE THREAD

**Issue by bitc** [emscripten-core/emscripten#6136]
When upgrading to a new version of emscripten, `emcc` doesn't seem to realize that the contents of the `~/.emscripten_cache` directory should be invalidated (deleted).

I install multiple versions of emscripten in different directories.

When switching from 1.37.22 → 1.37.28, then everything compiles normally with no warnings/errors (although through experimenting and manually regenerating the cached libraries and comparing them with the previous one reveals that they are greatly different; things might be therefore subtly broken).

But when switching from emscripten 1.36.4 → 1.37.22 things break. Below is the output I get:

```
warning: unresolved symbol: _ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEjjPKcj
warning: unresolved symbol: _ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv
warning: unresolved symbol: _ZNKSt3__221__basic_string_commonILb1EE20__throw_length_errorEv
warning: unresolved symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKc
warning: unresolved symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKcj
warning: unresolved symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignEPKc
warning: unresolved symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9push_backEc
warning: unresolved symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_
warning: unresolved symbol: _ZNSt3__26__sortIRNS_6__lessIjjEEPjEEvT0_S5_T_
```

(After running `emcc --clear-cache` and then rebuilding, everything works)

### Suggestion

All the cache files should be in a subdirectory named after the version of emscripten currently running (output of `emcc --version`).

So instead of the cache directory being in `~/.emscripten_cache/`, it would be: `~/.emscripten_cache/1.37.28/`

I can work on a pull request for this.

**Comment by kripken** [comment]
That's strange and worrying - we should be clearing the cache when the emscripten version updates.

If you get a version, run `emcc -v`, then get a newer version and run `emcc -v`, do you see it report a new version but not clear the cache?

**Comment by bitc** [comment]
I have multiple versions of emscripten installed:

```
$ /home/bitc/dev/emscripten-1.37.22/emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.37.22 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
$ /home/bitc/dev/emscripten-1.37.28/emcc --version
INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "/home/bitc/.emscripten_cache/is_vanilla.txt" for subsequent builds)
INFO:root: - ok
emcc (Emscripten gcc/clang-like replacement) 1.37.28 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ /home/bitc/dev/emscripten-1.37.28/emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.37.28 ()
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

So it's changing the `~/.emscripten_cache/is_vanilla.txt` file.

But it's not doing anything with the `~/.emscripten_cache/asmjs/*` files. They are left alone, and whichever files are there continue to be used with the current version of emcc (even if they were built with a different emcc version)

**Comment by kripken** [comment]
Yeah, that looks like a bug...

What does `~/.emscripten_cache/is_vanilla.txt` contain before and after the first two commands there (using 1.37.22 and 1.37.28)? Also, the contexts of `~/.emscripten_sanity` before and after?

The relevant code to clear after a version change is in `check_sanity()` in `tools/shared.py`. It compares the sanity data and should set `reason` to `system change` and the version number change.

Note that if it is on vanilla llvm, it will clear the cache for wasm and not asm.js, although either way you should see a message about something being cleared, which isn't appearing for you...

**Comment by bitc** [comment]
The file `~/.emscripten_cache/is_vanilla.txt` contains:
`0:/home/bitc/dev/emscripten-1.37.22/emscripten-fastcomp` (both before and after the first command).

After running the second command it contains:
`0:/home/bitc/dev/emscripten-1.37.28/emscripten-fastcomp` (and remains like this also after the third command).

I don't have a file `~/.emscripten_sanity` 😲
I've searched also the whole hard drive for `"*emscripten_sanity*"` and don't have it anywhere.

I am currently not using wasm.

I'm not sure if I'm using "vanilla" llvm. I compile emscripten according to ["Building Emscripten using your own fork"](https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_using_the_sdk.html#building-emscripten-using-your-own-fork). I use the original unchanged repos: https://github.com/kripken/emscripten-fastcomp.git and https://github.com/kripken/emscripten-fastcomp-clang.git (both checked out to the same tag that matches the tagged version that the main emscripten repo is currently checked out to)

Thank you

**Comment by kripken** [comment]
No sanity file? Are you using `EM_CONFIG` to change where the config file is (`~/.emscripten` by default)? The sanity file should be alongside it.

This might explain what you see, as EM_CONFIG skips sanity checks, I see from reading the code. Perhaps that's not quite right?

**Comment by bitc** [comment]
Yeah, I'm modifying EM_CONFIG, similar to what the nix emscripten build script does: <https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/emscripten/default.nix>

But I must be breaking something.... anyway, this is likely something wrong with my setup and not a bug in emscripten

**Comment by kripken** [comment]
I see, thanks. Then yeah, that's the issue - EM_CONFIG disables the sanity checks which disables clearing the cache when the version number changes. We should fix that, I don't see a reason for the current behavior.

Looking in the code, it seems like the issue is that the sanity file is kept alongside the settings file (by just adding `_sanity` to it), and when EM_CONFIG we don't have a file, so we just skip the sanity checks. But thinking on this, I think the sanity file should be tied to the cache dir instead. Should be a pretty simple fix, would you like to look into that?

**Comment by bitc** [comment]
Yeah, I will look into it during the next few days :+1:
