### ISSUE TITLE
-Ox flag to llc for wasm backend?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#6158]
We pass `-O1` or `-O2` etc. to llc with asm2wasm, but with the wasm backend no optimization level is specified. Is that intentional?

**Comment by dschuff** [comment]
By default `llc` runs at `-O2`. Which is weird but that's always been its behavior and it's what we want. We could also consider using `-O0` when building with emcc `-O0` though.

**Comment by kripken** [comment]
I see, thanks.

What about `-O3, -Os, -Oz`, do those not make much difference compared to `-O2`?

**Comment by dschuff** [comment]
last I checked, llc doesn't have those options, they only apply to the midlevel optimizers (LLVM IR passes). The backend just has O2 (use selectionDAG isel and extra backend opt passes) and O0 (use fast-isel or global isel and skip backend opt passes).

**Comment by dschuff** [comment]
(or I should say, maybe llc has those as CLI flags, but they are all just clamped to be O2 or O0).

**Comment by kripken** [comment]
Hmm, `-Os/-Oz` are indeed not present, but `-O1` and `-O3` at not clamped to `-O2`, they all do something different:
https://github.com/llvm-mirror/llvm/blob/master/tools/llc/llc.cpp#L428-L437

**Comment by kripken** [comment]
But that's just for llc I guess, the actual backends like the wasm backend might clamp?

**Comment by dschuff** [comment]
OK interesting;  last time I checked it wasn't even expressible. From a brief browse of TargetPassConfig.cpp and BackendUtil.cpp and the x86 backend, nothing uses the difference; everything I see just checks if the level is 0 or not. Still (once we test everything), no reason we couldn't just map the flags directly onto the backend; it would match clang's internal driver's behavior.

**Comment by dschuff** [comment]
Actually I take that back, some of the other backends and  MachineBlockPlacement use the aggressive setting.
