### ISSUE TITLE
str.charCodeAt is not a function error in allocateUTF8OnStack function of wasm glue-code

### ISSUE THREAD

**Issue by a-omsk** [emscripten-core/emscripten#6170]
Hello, my emscripten environment:

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.32
clang version 5.0.0  (emscripten 1.37.32 : 1.37.32)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin

emcc command: ```emcc jq.o -s WASM=1```

I'll try to load my wasm module via glue-code and it crashes with str.charCodeAt is not a function error in this place of code: 

```javascript
function lengthBytesUTF8(str) {
  var len = 0;
  for (var i = 0; i < str.length; ++i) {
    // Gotcha: charCodeAt returns a 16-bit word that is a UTF-16 encoded code unit, not a Unicode code point of the character! So decode UTF16->UTF32->UTF8.
    // See http://unicode.org/faq/utf_bom.html#utf16-3
    var u = str.charCodeAt(i); // < -- str.charCodeAt is not a function
```

In this case type of str param is Buffer not string!

My stacktrace:

```
TypeError: str.charCodeAt is not a function
    at lengthBytesUTF8 (popup.js:56162)
    at allocateUTF8OnStack (popup.js:56334)
    at Object.callMain (popup.js:62024)
    at doRun (popup.js:62089)
    at run (popup.js:62103)
    at runCaller (popup.js:62008)
    at removeRunDependency (popup.js:56738)
    at receiveInstance (popup.js:56892)
    at receiveInstantiatedSource (popup.js:56917)
    at <anonymous>
```

**Comment by kripken** [comment]
`callMain` uses `Module.arguments`, perhaps you assigned it something that isn't a string?

**Comment by a-omsk** [comment]
Oh, webpack wraps emscripten gluecode with some additional wrappers

```/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(1), __webpack_require__(37).Buffer))```

**Comment by kripken** [comment]
I'm not familiar enough with webpack to understand that. Does that call end up sending something as a parameter to `run()`?
