### ISSUE TITLE
SDL_Init sets up event handlers which SQL_Quit does not release, which prevents GC of the Module instance 

### ISSUE THREAD

**Issue by dmitrykuzmin** [emscripten-core/emscripten#6172]
In my application, I compile emscripten code via `"MODULARIZE"` option and thus I am able to create multiple `Module` instances one after another.

But when it's time for the `Module` instance to be garbage collected and release its memory, it doesn't do so. Instead, it keeps the memory occupied.

I've created [a small example](https://github.com/dmitrykuzmin/emscripten_memory_test) showcasing the problem.

From what I see, the problem is in the following line:

`SDL_Init(SDL_INIT_VIDEO);`

This line is situated in the class method exposed to the JavaScript and, although the method is never called, it somehow prevents `Module` instance from being destroyed and releasing its memory. When the line is commented out, everything is garbage collected properly and memory is released.

Is there any solution or workaround for this problem?

**Comment by kripken** [comment]
Thanks for the testcase (I had to lower the amount of memory to 128MB or my browser wouldn't load it, but otherwise it all works as described).

I believe what's going on is that `SDL_Init` sets up some event listeners, and they keep everything else alive.

In principle calling `SDL_Quit` should remove those. However, it looks like we don't do that, which is a bug. I'll rename this issue to focus on that.

**Comment by juj** [comment]
Try checking browser's DOM Inspector tool to see which event handlers are still active, and see where they are registered, to get a possible clue where they should get unregistered in turn.

**Comment by dmitrykuzmin** [comment]
Update: I've found some more SDL commands that prevent Module instance from being garbage collected in the same way as SDL_Init does.

They are as follows: SDL_CreateWindow, SDL_PollEvent and even SDL_Quit itself.
Maybe there are more, but those are the ones I use in my program.

I updated my test case with branches for each failing command:
[SDL_CreateWindow](https://github.com/dmitrykuzmin/emscripten_memory_test/tree/SDL_CreateWindow), [SDL_PollEvent](https://github.com/dmitrykuzmin/emscripten_memory_test/tree/SDL_PollEvent), [SDL_Quit](https://github.com/dmitrykuzmin/emscripten_memory_test/tree/SDL_Quit).

For me they all work in exactly the same way as with SDL_Init.

**Comment by ongamex** [comment]
Well this is not an error, how should I fix it?

Calling stub instead of sigaction() sge_game.html:1246:19
    printErr http://localhost:8080/sge_game.html:1246
    _sigaction http://localhost:8080/sge_game.js:12084
    _SDL_QuitInit http://localhost:8080/sge_game.js:308720
    _SDL_EventsInit http://localhost:8080/sge_game.js:305899
    _SDL_InitSubSystem http://localhost:8080/sge_game.js:300381
    _SDL_Init http://localhost:8080/sge_game.js:300575
    _main http://localhost:8080/sge_game.js:86826
    _main http://localhost:8080/sge_game.js:513764
    callMain http://localhost:8080/sge_game.js:514116
    doRun http://localhost:8080/sge_game.js:514175
    run http://localhost:8080/sge_game.js:514186

**Comment by sbc100** [comment]
Are you building with USE_SDL=2?  It looks like it because SDL_InitSubSystem does nothing in emscirpten normally.    Might be worth filing a bug at https://github.com/emscripten-ports/SDL2?  In any case this doesn't look related to this bug.
