### ISSUE TITLE
Raw pointer object documentation

### ISSUE THREAD

**Issue by ghost** [emscripten-core/emscripten#6173]
Hi,

I expose a function that returns a pointer with embind by using allow_raw_pointers().

On the Javascript side, when I call this function it returns an object, not directly the number corresponding to the address.

In this object I can see that by calling the property $$.ptr I'm able to retrieve this address, but I'm not sure if it's safe, I've searched through Emscrpiten documentation but didn't find anything about it?

Thanks

**Comment by AlexPerrot** [comment]
What do you want this address for ? If you use embind, you shouldn't need to manipulate addresses directly.

**Comment by th0mas** [comment]
Actually I manipulate vertices and triangles for a 3D application, these are in WebAssembly memory and I want direct access to send them to WebGL.

**Comment by th0mas** [comment]
Maybe we could have a function in the API to do that instead of directly accessing properties of this object?

**Comment by wxfred** [comment]
> What do you want this address for ? If you use embind, you shouldn't need to manipulate addresses directly.

Hello, I have the same question, I have a class A embinded, and i have a list of A to pass to a function like

```
void handleMaterials(const val obj)
{
      // get all materials from obj
}

EMSCRIPTEN_BINDINGS(my_module)
{
    class_<A>("A")
        ;
   
    function("handleMaterials", handleMaterials, allow_raw_pointers());
}
```

in js, i want to put each ptr of A into a BigUintArray, like
```
const materials = new BigUint64Array(1)
const material= new Module.A()
materials[0] = material["$$"].ptr
Module.handleMaterials({
    materials,
})
```

But some error comes out and says material["$$"] is undefined.

So, I need some help to get the ptr of a embinded obj in js.

**Comment by wxfred** [comment]
@kasperk81 console.log(material.ptr) prints **undefined**

**Comment by wxfred** [comment]
I figured out
