### ISSUE TITLE
How to prevent memory leak while calling exported c++ class in js

### ISSUE THREAD

**Issue by lokpoi888** [emscripten-core/emscripten#6179]
I use embind export a class A from c++ and this class is the return type of a function F(). When I call the function F() in JS code, I need to call delete() after I used it, otherwise the memory will leak, I think it is not conforming to JS programming habits. Is there any suggested method to solve this problem?
The code is shown below:

```
//c++ code
class A 
{
public:
    A(){}
    ~A(){}
    int method()
    {
        return 5;
    }
}

A F()
{
     A a;
     return a;
}
EMSCRIPTEN_BINDINGS(Export){
class_<A>("A")
        .constructor<>()
        .function("method", &A::method)
        ;
}
emscripten::function("F",&F);
```

```
//js code

var a = Module.F();
var b = a.method();
a.delete(); //if I don't call delete(),the memory will leak
```

**Comment by tbfleming** [comment]
C++'s preferred resource management (RAII) and JS's only resource management (GC with no finalizers) don't get along. embind compromizes by using ```new``` and ```delete```, which is workable, but not JS-like. Maybe create a helper function to ease the pain?

```
function withObj(x, f) {
    try {
        f(x);
    }
    finally {
        x.delete();
    }
}

withObj(Module.F(), a=>{
     let b = a.method();
});
```
