### ISSUE TITLE
scanf not working

### ISSUE THREAD

**Issue by didacusAbella** [emscripten-core/emscripten#6188]
i have the following C code:
```C
#include <stdio.h>
/***********Main*******************/
int main(void){
int value;
printf("Inserici Valore\n");
scanf("%d", &value);
printf("%d\n", value);
return 0;
}
````
but when i compile with emscripten and run with node I pass the input value but the shell not print he result and remain blocked. Here are an image of example:
![schermata del 2018-02-05 15-01-44](https://user-images.githubusercontent.com/11076147/35808254-843454ce-0a85-11e8-8934-2ca32ebb576d.png)

**Comment by eclecticdave** [comment]
Hi @didacusAbella,

Can you try pressing Ctrl-D to send EOF? This is one of the things I'm working on in my PR #6080.

**Comment by didacusAbella** [comment]
Hi @eclecticdave I have tried to send Ctrl-D but nothing change. I have tried either on Linux either on Windows.

**Comment by brion** [comment]
This is still going on, I think due to the way stdin.get_char buffers on its reads? scanf needs to be able to stop inputting data when it reaches a delimiter, so needs to actually read one char at a time (?)
