### ISSUE TITLE
browser.test_sdl_ttf_render_text_solid fails on Firefox on Linux

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#6197]
The test passes on Chromium (64.0.3282.119).

We should probably file a Firefox bug, but first, can someone please check if this also occurs on MacOS and Windows? We should figure out if it's a Linux-specific bug.

Also noticed on #5901.

**Comment by saschanaz** [comment]
Installing Arial fixed the failure last time I tried. I skipped it because the required package `ttf-mscorefonts-installer` was fairly big.

**Comment by kripken** [comment]
I see, thanks.

I don't know much about fonts on the web, but is there a way to make the test not depend on Arial? I see the test does
```
    TTF_Font *font = TTF_OpenFont("Arial", 32);
```
but I'm not sure if there's another font which we can assume exists in all browsers?
