### ISSUE TITLE
Way to preprocess `EM_ASM...` JS code?

### ISSUE THREAD

**Issue by martijnthe** [emscripten-core/emscripten#6217]
Is it possible to "preprocess" the JS code inside a `EM_ASM({ ... })` macro somehow?

Use cases:
- Write ES6/7 in `EM_ASM` blocks and while targeting older VMs, using i.e. Babel to transpile down to an older ES version.
- Write TypeScript in `EM_ASM` blocks.
- Lint code in `EM_ASM` blocks.

I'm imagining a compiler flag to pass a program to the compiler that would be invoked to preprocess any JS code blocks in the .c file, or something along those lines. The program would take input from `stdin` and output the transpiled code to `stdout`.

For the linting use case, it'd be nice to be able to just get the preprocessors (both C and JS ones) invoked without actually compiling the C code. Perhaps the existing `-E` flag (only preprocess, don't compile) could be used to accomplish that.

**Comment by kripken** [comment]
There isn't an option currently. It wouldn't be too hard to add one, and those use cases sound nice, but given the current uncertainty about API changes for EM_ASM (#6213), this should probably wait for now.

**Comment by AndrewAMD** [comment]
Now that we have EM_JS, suppose that we add EM_TS exclusively for Typescript and just upgrade EM_JS to support ES6/7 (unless this was done already)?
