### ISSUE TITLE
memoryprofiler.js is tracking reallocation in a wrong way

### ISSUE THREAD

**Issue by anton-kl** [emscripten-core/emscripten#6223]
Hello!

The problem is as follows: `memoryprofiler.js` would treat each `_emscripten_trace_record_reallocation` call as a new `onFree` and an `onMalloc` calls:

```Javascript
onRealloc: function onRealloc(oldAddress, newAddress, size) {
  this.onFree(oldAddress);
  this.onMalloc(newAddress, size);
},
```

However, there is a situation when `dlrealloc` fails to reallocate chunk, and calls `dlmalloc` and `dlfree` directly, which call Emscripten Tracing Api themselves.

So, for just one reallocation `memoryprofiler.js` may do following calls:

1. `onFree` (triggered by dlfree call in dlrealloc)
1. `onMalloc`  (triggered by dlmalloc call in dlrealloc)
1. `onRealloc` -> which will result in a second `onFree` call and another `onMalloc` call

Second `onFree` will fail, due to missing information about pointer size (removed in the first `onFree` call), and second `onMalloc` will succeed, increasing overall memory usage.

This problem could be fixed either in `dlmalloc.c` or `memoryprofiler.js`, depending on which behavior you find to be correct. Please refer to following commits:

- Option 1: fix in `dlcalloc.c`: https://github.com/kripken/emscripten/commit/58c4789aff00547e763787b5c1934c755c1b5344
- Option 2: fix in `memoryprofiler.js`: https://github.com/kripken/emscripten/commit/51b0be22b1c2608e55512e2c2756facf262754f5

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
Thank you @anton-kl for the thorough analysis on this. Came back to doing some more memoryprofiler improvements, and incorporated your fix option 1 and some other missing memoryprofiler tracking items into the bunch. The change set is in the above PR.
