### ISSUE TITLE
Issue generating source maps (1.37.9)

### ISSUE THREAD

**Issue by njligames** [emscripten-core/emscripten#6225]
Hello,
I am trying to generate source maps.

I use cmake to build with the following options:
`
LIST(APPEND EXTRA_PLATFORM_LIBS "--bind")
LIST(APPEND EXTRA_PLATFORM_LIBS "--profiling")
LIST(APPEND EXTRA_PLATFORM_LIBS "--profiling-funcs")
LIST(APPEND EXTRA_PLATFORM_LIBS "--tracing")
LIST(APPEND EXTRA_PLATFORM_LIBS "--emit-symbol-map")
ADD_DEFINITIONS(-DEMCC_DEBUG=1)
LIST(APPEND EXTRA_PLATFORM_LIBS "-O0")
LIST(APPEND EXTRA_PLATFORM_LIBS "--js-opts 0")
LIST(APPEND EXTRA_PLATFORM_LIBS "-g4")
LIST(APPEND EXTRA_PLATFORM_LIBS "-s ALLOW_MEMORY_GROWTH=1")
LIST(APPEND EXTRA_PLATFORM_LIBS "-s FULL_ES2=1")

SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --memory-init-file 1 --embed-file  ${NJLIGameEngine_COMMON_DIRECTORY}/assets@/" )
SET(CMAKE_EXECUTABLE_SUFFIX ".html")
`

This is my .emscripten file:
`import os
LLVM_ROOT='/Applications/Developer/emsdk_portable/clang/e1.37.9_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Applications/Developer/emsdk_portable/clang/e1.37.9_64bit/optimizer'
BINARYEN_ROOT='/Applications/Developer/emsdk_portable/clang/e1.37.9_64bit/binaryen'
NODE_JS='/Applications/Developer/emsdk_portable/node/4.1.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/Applications/Developer/emsdk_portable/emscripten/1.37.9'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/var/folders/vd/k6633p_j1t500kv83bjp_rhr0000gn/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
`

I receive this error:
`DEBUG:root:generating source maps
buffer.js:378
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:378:11)
    at Object.fs.readFileSync (fs.js:461:33)
    at Object.<anonymous> (/Applications/Developer/emsdk_portable/emscripten/1.37.9/tools/source-maps/sourcemapper.js:183:47)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
Traceback (most recent call last):
  File "/Applications/Developer/emsdk_portable/emscripten/1.37.9/em++", line 16, in <module>
    emcc.run()
  File "/Applications/Developer/emsdk_portable/emscripten/1.37.9/emcc.py", line 2075, in run
    '--offset', str(0)])
  File "/Applications/Developer/emsdk_portable/emscripten/1.37.9/tools/jsrun.py", line 122, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/Applications/Developer/emsdk_portable/node/4.1.1_64bit/bin/node', '/Applications/Developer/emsdk_portable/emscripten/1.37.9/tools/source-maps/sourcemapper.js', '/var/folders/vd/k6633p_j1t500kv83bjp_rhr0000gn/T/tmpCb4RQi/index.bc.o.js.pp.js.mem.js', '--sourceRoot', '/Users/jamesfolk/Documents/NJLI/Engine/projects/emscripten_Sublime', '--mapFileBaseName', 'build/index.html', '--offset', '0'] to finish with return code 0, but it returned with code 1 instead! Output: /var/folders/vd/k6633p_j1t500kv83bjp_rhr0000gn/T/tmpCb4RQi/index.bc.o.js.pp.js.mem.js
make[2]: *** [build/index.html] Error 1
make[1]: *** [CMakeFiles/NJLIGameEngine.dir/all] Error 2
make: *** [all] Error 2`

Any Help would be appreciated!

**Comment by kripken** [comment]
Nothing here seems obviously wrong. I'd try to narrow this down, compiling less code until something breaks, or start from a minimal testcase where source maps work and compare from there.

**Comment by njligames** [comment]
ok, thanks, will do
