### ISSUE TITLE
Is any way to hack emscripten_set_main_loop() and return back into main() after quiting of a loop?

### ISSUE THREAD

**Issue by Wohlstand** [emscripten-core/emscripten#6227]
As I see, using of emscripten_set_main_loop() I have no way to return back into main() function to change scene into another and start emscripten_set_main_loop() again, but on another function/class.

I thinking how to hack this as Emterpreter even looks good, but result works VERY slow and I have no idea how to correctly selectively interpret loop calls are in most of cases are members of scene classes (or I getting an error of linking, or result doesn't works properly).

I thinking about a way to hack emscripten_set_main_loop() and return back to main, as idea I have:
* By any ASM or other way completely save a current state of a stack
* Then begin emscripten_set_main_loop() which will kill the current state of a stack
* On calcelling of main loop, restore the saved stack state and jump into it. But, skip the emscripten_set_main_loop() call as it is not needed.
Then, in any next time, repeat same operation when beginning a process of a next scene.

Are you think it is possible to solve this?

P.S. As my game engine has sub-loops (as example, a message or other dialog box requested from a middle of code that does own control listening and a render of parent scene's state), I would think is to use Emterpreter or even disable support of child-boxes for Emscripten builds until I'll find a proper way to selectively interpret class-membered loop calls. I can't just use a regular function callbacks as there are must be friends and there are can't be "extern 'C'" without loss of private access.

**Comment by tbfleming** [comment]
> restore the saved stack state

This is impossible in asm.js and in wasm without a system like emterpreter or asyncify.

>  can't just use a regular function callbacks as there are must be friends and there are can't be "extern 'C'" without loss of private access.

C++ lambda functions can act as callbacks, and can safely access private data.

**Comment by Wohlstand** [comment]
> This is impossible in asm.js and in wasm without a system like emterpreter or asyncify.

To use Empterpreter or Asyncify I need to correctly refere functions are has sleeps and loops, but to make that easier I need use extern "C", or try to guess it from object files generated by the compiler, etc.

>> can't just use a regular function callbacks as there are must be friends and there are can't be "extern 'C'" without loss of private access.
>> 
> C++ lambda functions can act as callbacks, and can safely access private data.

I meant that I need to refer a function which a class member or friend independent C++ function in the EMPTERPRITY_WHITELIST to compile everything except of those functions to don't cause a lag of entire game.

**Comment by Wohlstand** [comment]
About "Asyncify", I have missed that up... I have checked it out more and looks that what I needed, I need to check this in action... I should be able to run this:
```c
int exec()
{
    struct State xxx;
    int running = 0, ret = 0;
    while(running)
    {
        doAnything1(xxx)
        doAnything2(xxx)
        ...
        renderEverything(xxx)
        waitSome(&ret);
        if(xxx.quit)
            running = 0;
    }
    return ret;
}
```
and I don't want to be forced use this:
```c
static struct State xxx;
void runStep()
{
    doAnything1(xxx)
    doAnything2(xxx)
    ...
    renderEverything(xxx)
}
```
As in my engine, there are many cases of sub-loops are will cause stuck of the entire engine, for example, spawned message boxes are will run own loop inside self and will render parent scene's content and self above.

**Comment by sbc100** [comment]
I think Asyncify is the way to go if you want to keep you stack while yielding to the event loop.

Can you verify and close this issue if that works for you?

**Comment by Wohlstand** [comment]
Yes, I'll close this issue once I'll solve the problem.

P.S. Thanks that bot who reminded me about this question, I forgot about this unsolved task, so, it's a time to finally solve it! :grin:

**Comment by Wohlstand** [comment]
Okay, right now I can't test the build because I have met this error https://github.com/emscripten-core/emscripten/issues/9317 , will re-try tomorrow...

**Comment by Wohlstand** [comment]
Have found just now that #9317 is looking like has been fixed! :fox_face: :smile: 
Gonna re-test the thing today in the evening in my time zone...

**Comment by Wohlstand** [comment]
Hello! Today I finally did a test, and I did some own side works to fix up my project to work with Emscripten https://github.com/WohlSoft/PGE-Project/commit/3c5acff8cbb8c9850f08e0a711bcdb37d54c1212
So, the problem has been finally solved! Thank you all for any given help and tips! :fox_face:
