### ISSUE TITLE
swprintf not printing pointer address with %p

### ISSUE THREAD

**Issue by yairlev** [emscripten-core/emscripten#6240]
`swprintf` is not formatting a pointer's address when using the `%p`directive.  Here's a code sample demonstrating the problem: 

Tested on latest emscripten: `1.37.33`.

```
#include <string>  

int main( void )  
{  
   wchar_t  buffer[200], s[] = L"computer";  
   
   //This line prints the address of s correctly
   printf("%p\n", s); 

   //store the address of 's' into buffer
   auto j = swprintf( buffer, 200, L"%p", s );

  //print the number of wide chars stored. This returns -1.
   printf("j: %d\n", j); 

   //print the address of s - returns an empty string
   printf("buffer: %ls\n", buffer); 
}  


```

When running the same code natively, the address is printed as expected. Here's a running example: https://onlinegdb.com/SJYLDrgvM

Any idea why this is happening?

**Comment by kripken** [comment]
This does look like a bug. Most likely it's in the musl implementation of the `*wprintf` calls. Can confirm using musl built natively.

**Comment by yairlev** [comment]
Thanks @kripken. I'm trying to see if this can be resolved in musl.

**Comment by brion** [comment]
This is still an issue, appears to be an upstream bug in musl. Looks fixable by tweaking `vfwprintf.c` to change `t` to `'x'` before it gets passed back to `fprintf`'s implementation. Should send a fix upstream and integrate here.

**Comment by sbc100** [comment]
Sounds like its not been fixed (at least not in emscripten).  It might be that musl has a fix already.
