### ISSUE TITLE
Runtime dependency on glibc/++ 3.4.20

### ISSUE THREAD

**Issue by qpn6ph9q** [emscripten-core/emscripten#6252]
I have no problem building Emscripten/LLVM from source on older linux distros, like Centos 7. The problem I'm encountering is a runtime dependency on glibc/++ 3.4.20. For example:

Minimal steps to reproduce (after installing all prerequisites):

    $ git clone https://github.com/juj/emsdk.git
    $ cd emsdk
    $ ./emsdk install latest
    $ ./emsdk activate latest
    $ ./clang/e1.37.33_64bit/clang++ -v

The following output is produced on Centos 7. 

```
/home/dev/emsdk/clang/e1.37.33_64bit/clang++: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/dev/emsdk/clang/e1.37.33_64bit/clang++)
/home/dev/emsdk/clang/e1.37.33_64bit/clang++: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/dev/emsdk/clang/e1.37.33_64bit/clang++)
```
This works fine on Fedora core 22 and above.
Also note that I can successfully build from source on this same platform, but the same error happens at runtime.

**Comment by dschuff** [comment]
@juj perhaps we should link LLVM with the `-static-libstdc++` flag.

**Comment by Nanonid** [comment]
Is the answer to use Centos 6.x?

**Comment by tiaanwessels** [comment]
Does it work on RH7 or is this a CentOS7 problem only ?

**Comment by thwee-alchemist** [comment]
emscripten used to work on CentOS 7, but I don't remember what version that was. Perhaps a compatibility table would be a quick and easy fix.

**Comment by kripken** [comment]
We've recently [replaced our build infrastructure](https://groups.google.com/d/msg/emscripten-discuss/WhDtqVyW_Ak/8DfDnfk0BgAJ), so it's possible something has changed here (the new build scripts were written from scratch). Would be good to know if things changed here, and whether for good or bad.

**Comment by sbc100** [comment]
The path to clang looks like this build comes from the old infrastructure no?

We could build out binaries against a sysroot in order to get better compatibility I guess, or we could try dereks suggestion.    It really depends how much users are effected by this.  If its only a few then it seems reasonable to ask them to build their own version of clang.

**Comment by tesch1** [comment]
I've got this problem too.  Either `-static-libstdc++`, sysroot, or clear instructions on how to re-build a known-good version would help.  I've tried a bunch of things suggested on the website to rebuild, but nonetheless always end up with a non-working installation (master does build via ./emsdk, but doesnt work).

**Comment by sbc100** [comment]
The fallback for building form source *should* always work.  Perhaps the documentation needs to be improved.    I believe `./emsdk install sdk-incoming-64bit` is the simplest way to be build the entire SDK from source.  If that doesn't work for you can you open a bug in the `emsdk` repo?

**Comment by tesch1** [comment]
Yes, that works, I was building `master` which does not.  Still would be nice if there was a `./emsdk install sdk-<version>-64bit` that could be forced to build rather than download binaries.

**Comment by tesch1** [comment]
Thanks for your help!
