### ISSUE TITLE
construct_env does not inherit environment variables on windows.

### ISSUE THREAD

**Issue by marius-luca-87** [emscripten-core/emscripten#6257]
I have noticed recently that on windows emsdk_env will revert certain environment variables to the global state instead of appending to the existing context.

```
@echo off
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
call emsdk_env.bat
nmake /?
```
In this example the nmake application is no longer available because of the PATH override.
def adjusted_path(tools_to_activate, log_additions=False, system_path_only=False):
The adjusted_path function seems to be reading the PATH from the global state instead of the current ENV.

If this behaviour is intended then maybe a new command line option could be introduced to allow people to incrementally setup the environment state.

**Comment by SSYGEN** [comment]
I had the same problem and I fixed it by running `emsdk_env.bat` before `vcvarsall.bat`

**Comment by marius-luca-87** [comment]
vcvarsall.bat is just an example used to describe the problem of losing the local environment variables. In more complex cases reordering is not possible as the environment is constructed incrementally.
