### ISSUE TITLE
Mismatched calling convention linking to function returning struct

### ISSUE THREAD

**Issue by morganbr** [emscripten-core/emscripten#6259]
In linking a C++ module to a module of [generated ](https://github.com/dotnet/corert)bitcode, I'm seeing a couple of the C++ functions that return pointer-sized structs get different generated calling conventions than their callers. The callers seem to be trying to add the stack pointer as a hidden first argument, expecting the callee to write the return value to it, but the callee is just returning the struct instead. This misaligns the arguments and drops the last one.

Changing the caller to expect an i32 return type instead of a struct works, but isn't ideal since it means modifying the source code (since I'm building a compiler, I don't always control that). I'm seeing similar results with both Asm.JS and Webassembly. My SDK info is below (I can't update due to #6251):
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.30
clang version 4.0.0  (emscripten 1.37.30 : 1.37.30)

For example:

Callee in C++:
```
struct TypeManagerHandle { void* _value; };
extern "C" TypeManagerHandle RhGetModuleFromEEType (EEType * pEEType)
{
    return *pEEType->GetTypeManagerPtr(); // Dereferences and returns a TypeManagerHandle
}
```

Callee in LLVM bitcode:
```
; Function Attrs: noinline sspstrong
define hidden i8* @RhGetModuleFromEEType(%class.EEType*) #0 !dbg !24172 {
  // snip
  %9 = load i8*, i8** %8, align 4, !dbg !24180
  ret i8* %9, !dbg !24180
}
```

Caller in LLVM bitcode:
```
// I've tried treating the return value as a 4-i8 array, a struct with an i32 member
// and a struct with 4 i8 members and got same result in all cases
declare [4 x i8] @RhGetModuleFromEEType(i8*)

%call = call [4 x i8] @RhGetModuleFromEEType(i8* %ldtemp)
```

Caller in wast:
```
// Prolog puts the stack pointer in $$call
  (set_local $$call
   (get_local $sp)
  )

//snip

// Set up the argument we meant to pass
(set_local $$ldtemp
   (i32.load
    (get_local $$8)
   )
  )
// Pass the stack pointer instead and drop the return value
  (drop
   (call $_RhGetModuleFromEEType
    (get_local $$call)
   )
  )
// Try to load the return value from the stack
(set_local $$call$sreg$field
   (i32.load8_s
    (get_local $$call)
   )
  )
```

Callee in wast:
```
 // Still just takes one i32 and returns an i32
 (func $_RhGetModuleFromEEType (; 15487 ;) (param $$0 i32) (result i32)
// snip
  (return
   (get_local $$5)
  )
)
```

This also triggers misleading linker warnings like:
```
warning : unexpected number of arguments 2 in call to 'RhGetModuleFromEEType', should be 1 
warning : unexpected return type void in call to 'RhGetModuleFromEEType', should be i8*
```

**Comment by tbfleming** [comment]
The future looks good. Here's what clang trunk produces when outputting wasm directly. emscripten will eventually use this (#5313) instead of fastcomp or s2wasm.

```c++
struct S {
    int i;
};

S f();

int g() {
    return f().i;
}
```

```
(module
  (type $t0 (func (result i32)))
  (import "env" "__linear_memory" (memory $env.__linear_memory 0))
  (import "env" "__indirect_function_table" (table $env.__indirect_function_table 0 anyfunc))
  (import "env" "_Z1fv" (func $_Z1fv (type $t0)))
  (func $_Z1gv (export "_Z1gv") (type $t0) (result i32)
    (call $_Z1fv)))
```

**Comment by kripken** [comment]
Interesting, if it's different in the LLVM wasm backend then it's likely ABI differences there. In that case the same should happen when @sunfishcode updates the asm.js ABI to match the LLVM wasm one, which is planned.

**Comment by morganbr** [comment]
I don't think the LLVM wasm backend is involved. I just used Emscripten's clang to compile the C++ module as a .bc file and used CoreRT to generate another .bc file and then ran ```emcc MyCppModule.bc MyGeneratedModule.bc -o MyPage.html```.

**Comment by tbfleming** [comment]
Right. It will be fixed when emscripten switches to lld.

**Comment by tbfleming** [comment]
I shouldn't say "fixed". It's just a different ABI.
