### ISSUE TITLE
Cannot register member functions of a value_struct type.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#628]
Currently, it is not possible to register member functions into a structure exposed using value_struct. I.e. the following does not work:

value_struct("float3")
.constructor<>()
.field("x", &StructVector::x)
.field("y", &StructVector::y)
.field("z", &StructVector::z)
.method("Add", (float3(float3::*)(float) const)&float3::Add)

For reference on the type float3, see 

https://github.com/juj/MathGeoLib/blob/master/src/Math/float3.h
http://clb.demon.fi/MathGeoLib/docs/float3_summary.php
https://dl.dropbox.com/u/40949268/emcc/embind_symbols.cpp

In the last link, I used class_ as a workaround (but that didn't allow me to expose .field()s.

This item was reported already in #603, but making it a separate item, in case if the implementation is different.

**Comment by NuclearCookie** [comment]
As this is still not supported, do you agree with what @chadaustin suggested?
>Adding support for methods to value_struct would be harder: value_structs are stored as copies in JavaScript, and it's unclear what data the method would modify.

>I could be convinced that adding support for const methods to value_struct would be a good idea, since they don't modify the underlying object.

I'm interested in looking in to this feature

**Comment by chadaustin** [comment]
@NuclearCookie If you want to play around and see if you can get something to work, I'd be happy to review the diff.
