### ISSUE TITLE
Running WebGL 1 and WebGL 2 using SDL2

### ISSUE THREAD

**Issue by mortennobel** [emscripten-core/emscripten#6280]
When I try to run the attached file compiled using '-s USE_WEBGL2=1' in a browser with only WebGL 1 support I get the following error:

exception thrown: ReferenceError: Can't find variable: WebGLVertexArrayObject,emscriptenWebGLGet — hello.js:1:190541
_glGetIntegerv — hello.js:1:226858

When compiling for only WebGL 1 or running on a WebGL 2 browser works.

A build with '-O3 -g4' can be found here:
http://www.itu.dk/~mnob/hello/hello.html

[main.cpp.zip](https://github.com/kripken/emscripten/files/1757972/main.cpp.zip)

**Comment by gogoprog** [comment]
Are you expecting a clearer error message?

**Comment by mortennobel** [comment]
I'm not expecting any error. WebGL defaults to version 1, and I'm only using valid WebGL 1 functions.

**Comment by gogoprog** [comment]
`USE_WEBGL2=1` will target for WebGL2 so it won't work on a WebGL1-only browser

**Comment by mortennobel** [comment]
It seems a little weird since OpenGL ES 3.0 is backward compatible with 2.0 (and WebGL 2 is backward compatible with WebGL) as long as you for the lower version are using GLSL ES 100 and only shared function calls and enums.

I suggest that this should be fixed. Or alternative the documentation should clarify that `USE_WEBGL2=1` breaks backward compatibility.

**Comment by mortennobel** [comment]
I have created a workaround. Emscripten will probably not call WebGL 2 function unless it needs to, but the error above is related to using undefined WebGL2 types. So one solution is to detect WebGL 1 context and then inject the needed types into the JavaScript context:

    auto glContext = SDL_GL_CreateContext(window);
    auto version = glGetString(GL_VERSION);
    #ifdef EMSCRIPTEN
    bool isWebGL1 = strcmp((const char*)version, "WebGL 1") != -1;
    if (isWebGL1){
        const char* embeddedCode =
            "window.WebGL2RenderingContext = window.WebGL2RenderingContext || window.WebGLRenderingContext;\n"
            "window.WebGLQuery = window.WebGLQuery || function(){};"
            "window.WebGLSampler = window.WebGLSampler || function(){};"
            "window.WebGLSync = window.WebGLSync || function(){};"
            "window.WebGLTransformFeedback = window.WebGLTransformFeedback || function(){};"
            "window.WebGLVertexArrayObject = window.WebGLVertexArrayObject || function(){};";
        emscripten_run_script(embeddedCode);
    }
    #endif

This approach seems to work, but I haven't tested it thoroughly.
[main.cpp.zip](https://github.com/kripken/emscripten/files/1759764/main.cpp.zip)

**Comment by prsolucoes** [comment]
It still necessary?
