### ISSUE TITLE
Tring to call functions of an unkown WebAssembly

### ISSUE THREAD

**Issue by nrllh** [emscripten-core/emscripten#6281]
I try to call functions of an unknown-WebAssembly «Or better said, i try to simulate them» and if the functions has a return value to get its return value.

I cant get with following code i cant get exports, but can't get any info which parameters are needed for it. 

    instance.exports();

That's why i wrote a parser to find out functions of WebAssembly-File and their parameter. After i got these infos, i tried to call an export function and got following error:

>import object field 'env' is not an Object.

And its header which comes from emscripten :

 

      (import "env" "DYNAMICTOP_PTR" (global $env.DYNAMICTOP_PTR i32))
      (import "env" "STACKTOP" (global $env.STACKTOP i32))
      (import "env" "STACK_MAX" (global $env.STACK_MAX i32))
      (import "env" "abort" (func $env.abort (type $t1)))
      (import "env" "enlargeMemory" (func $env.enlargeMemory (type $t2)))
      (import "env" "getTotalMemory" (func $env.getTotalMemory (type $t2)))
      (import "env" "abortOnCannotGrowMemory" (func $env.abortOnCannotGrowMemory (type $t2)))
      (import "env" "_gmtime" (func $env._gmtime (type $t3)))
      (import "env" "___setErrNo" (func $env.___setErrNo (type $t1)))
      (import "env" "_emscripten_memcpy_big" (func $env._emscripten_memcpy_big (type $t4)))
      (import "env" "___syscall20" (func $env.___syscall20 (type $t5)))
      (import "env" "_ftime" (func $env._ftime (type $t3)))
      (import "env" "memory" (memory $env.memory 256 256))
      (import "env" "table" (table $env.table 8 8 anyfunc))
      (import "env" "memoryBase" (global $env.memoryBase i32))
      (import "env" "tableBase" (global $env.tableBase i32))

The reason is clear: Because i didn't define any import object. i have following idea to solve this:

I define the importObject so that it meets minimum requirements. I found following code for some imports: 

        table: new WebAssembly.Table({ initial: 0, maximum: 0, element: 'anyfunc' }),
        tableBase: 0,
        memory: memory,
        memoryBase: 1024,
        STACKTOP: 0,
        STACK_MAX: memory.buffer.byteLength,

But there are too many different imports. I couldn't find a list, which gives me all import types and their definition. That's why w want to create my own table to solve this problem. Could you give me some informations or help me to make this table?

**Comment by kripken** [comment]
In general, those imports are an internal API, and there isn't a single place that documents all of those. In the long term, we may move things to something more modular. Meanwhile, first thing I recommend is to make sure you fully optimize the code, as metadce (in -O3 and -Os) will remove unnecessary imports, which may make things simpler. Aside from that, the best thing is to read the source code or ask here about specific imports.

**Comment by NurullahDe** [comment]
I do research on WebAssembly files, so i am not owner. I find a WebAssembly file and try to call its functions to retrieve return values:

- i convert wasm to wat
- then find exports and its parameters
- then call exports 

And then i analyse the return values. That's why an optimisation is not possible at this point.  I liste above the most used imports.. If i find a defination for them, it will be enough to complete this task.

**Comment by kripken** [comment]
In general the wasm might not be meaningful on itself, though, without the JS. But here are some quick notes on the ones you mentioned:
```
DYNAMICTOP_PTR - the value sbrk() returns, the top of the program break.
STACKTOP - the top of the stack
STACK_MAX - the maximum top of the stack
abort - will abort execution
enlargeMemory - will grow memory
getTotalMemory - get total memory size
abortOnCannotGrowMemory - aborts execution with an error message about running out of memory
_gmtime - implements libc gmtime()
___setErrNo - sets the errno value in C (error result from a libc call)
_emscripten_memcpy_big - memcpy a large amount of memory
___syscall20: linux syscall 20 (get process id)
_ftime - implements libc ftime()
```
