### ISSUE TITLE
After introducing MODULARIZE flag , the default Module fails to get exported in the compiled JS file

### ISSUE THREAD

**Issue by prtk418** [emscripten-core/emscripten#6282]
After introducing MODULARIZE flag , the content of post.js file is not getting rendered at proper place, i.e., at the end, causing syntactical error.

post.js :
```javascript
export default ModuleInitialized;
```

compiled.js :
```javascript
export default ModuleInitialized;

  return ModuleInitialized;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ModuleInitialized;
.
.
.
```
built using : 
```bash
em++ test.cpp -o compiled.js -s MODULARIZE=1 -s 'EXPORT_NAME="ModuleInitialized"' --post-js post.js
```
test.cpp
```cpp
#include<iostream>
#include <emscripten.h>

int EMSCRIPTEN_KEEPALIVE main() {
  std::cout << "initialized";
}
```

**Comment by prtk418** [comment]
@kkimdev

**Comment by kripken** [comment]
The post-js is inside the module, so that it can be optimized together with that code (to add things outside of the module, after everything, you can just append to the JS output file). Perhaps we should document this better, did you see a place in the docs we should improve?

**Comment by kkimdev** [comment]
One place is here https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html#emcc-post-js Im not sure if there are more places to fix

**Comment by kripken** [comment]
Thanks, I opened #6287.
