### ISSUE TITLE
emsdk download links?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#6288]
It looks like http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html points to https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable-64bit.zip for those downloads. I'm not sure how those are generated? Do they contain anything more than the emsdk itself, for which we could use https://github.com/juj/emsdk/archive/master.zip as the link instead?

cc @juj

**Comment by Cypher1** [comment]
I'd like to reopen this, there doesn't seem to be a good alternative download link for a portable, pre-built version of emsdk, instead we're expected to use the emsdk tools to install emsdk. I just need an emsdk binary for my project.

**Comment by sbc100** [comment]
emsdk is a tool that does the downloading for you.   We don't have a single binary that you can download.   I'm afraid this is just the way emsdk works.   You could do an install then zip the results perhaps?

**Comment by Cypher1** [comment]
Sorry I mispoke (miswrote?) 
```
I'd like to reopen this, there doesn't seem to be a good alternative download link for a portable, pre-built version of emscripten, instead we're expected to use the emsdk tools to install emscripten. I just need an emscripten binary for my project.
```

**Comment by curiousdannii** [comment]
Ubuntu has an emscripten package you could install, but it is very old. Still it's there. Otherwise use the sdk.

**Comment by sbc100** [comment]
> Sorry I mispoke (miswrote?)
> 
> Here's a more correct form:
> 
> I'd like to reopen this, there doesn't seem to be a good alternative download link for a portable, pre-built version of emscripten, instead we're expected to use the emsdk tools to install emscripten. I just need an emscripten binary for my project.

I don't really understand what you are asking for.  Emscripten itself doesn't require any building, its written in python.  However, it does depend on many tools such as llvm and binaryen which do require building.   If you want use pre-built binaryen the only option we provide is to use the emsdk.   emsdk download the components for you.     IIUC we have never supplied a single binary download of emscripten + all its dependencies.

**Comment by Cypher1** [comment]
Thanks Sam Clegg,

There used to be a portable emscripten zip that was provided by Mozilla.
This provided all dependencies (pre-built) and was a lovely, simple, way to
start using emscripten.

I'll work out running emsdk as this doesn't seem to be something that
emscripten is interested in.

**Comment by sbc100** [comment]
> Thanks Sam Clegg, There used to be a portable emscripten zip that was provided by Mozilla. This provided all dependencies (pre-built) and was a lovely, simple, way to start using emscripten. I'll work out running emsdk as this doesn't seem to be something that emscripten is interested in.

Oh, my apologies.  I didn't know we ever provided such a thing.   I'll see if I can dig up more details on it and try to resurrect.  @juj any pointers on how this used to work?

**Comment by juj** [comment]
For each tag, we would run a script (in juj/emslave) to run emsdk install, and produce a redist out of the results, zip it up to a portable download that people could pull down from Mozilla servers.

**Comment by sbc100** [comment]
Sounds like make a behaviour worth restoring?  What do you think @kripken @juj ?

**Comment by kripken** [comment]
In general that sounds good (but I don't know how much effort it would take to do, as it's on windows).

**Comment by juj** [comment]
If there is need for that from users, then that could be useful.

The scripts in juj/emslave did do similar packaging for macOS and Linux if my memory serves correctly (though Linux being at the mercy of different cross-distro behaviors)

**Comment by sbc100** [comment]
I guess that good news is that the emscripten bundles that we download with emsdk these days are already kind of pre-packaged fat archives.  It could be enough to simply link to them?
