### ISSUE TITLE
Not displaying array value Pt2

### ISSUE THREAD

**Issue by Mcilie** [emscripten-core/emscripten#6291]
##EDIT
The value isnt showing uo the first time, If i use the google inspect element console and call `_main()` it prints it, but waaayyyy before its supposed to. Is this something to do with async?
I write a simple matrix mult. Program.

And I want to access one of the buffer arrays that has the returned values. 
my code (below) Prints everything except the value. Is it emscripten or is it just my code:

`#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <emscripten/emscripten.h>

int genMatrix(long N, long ret[][N]){
	long i,j;
	for (i=0; i<N; i++){
		for (j=0; j<N; j++){
	        srand ( time(NULL) );
                ret[i][j] = rand() % N+ 1;
		
		} 	
	}
	return 0;
}

int EMSCRIPTEN_KEEPALIVE multMat(long N, long a[][N], long b[][N], long res[][N]) {
    long i, j, k;
    for (i = 0; i < N; i++)
    {
        for (j = 0; j < N; j++)
        {
            res[i][j] = 0;
            for (k = 0; k < N; k++)
                res[i][j] += b[i][k]*b[k][j];
        }
    }
    srand ( time(NULL) );
    return rand() % 6 + 1;
}

int main(int argc, char ** argv) {
    printf("WebAssembly module loaded\n");
    long n = 10;
printf("done\n");
    long ret[n][n];
printf("done2\n");
    long a[n][n],b[n][n];
printf("done3\n");
    genMatrix(n,a);
printf("done4\n");
    genMatrix(n,b);
printf("done5\n");
    multMat(n,a,b,ret);

    printf("done6\n");
    printf("%ld", ret[2][2]);
}
`

**Comment by tbfleming** [comment]
```
printf("%ld", ret[2][2]);
```

You're missing ```\n```. BTW, this isn't portable:

```
int genMatrix(long N, long ret[][N]){
```
