### ISSUE TITLE
Send mail automatically to emscripten-discuss when a new build has been tagged

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#6307]
Brion had a great idea in the emscripten-discuss mailing list:

```
"I would really love announcements of new tagged
build availability to the list though, or an RSS feed
or twitter bot I can subscribe to."
```

Not sure there's resources to do this right now, so thought to mark this down since this would help people to avoid polling for new tags.

This could be achieved by having the emslave python build script [here](https://github.com/juj/emslave/blob/master/bin/deploy_emscripten_llvm.py#L442) kick off a [sendmail](https://docs.python.org/2/library/email-examples.html) task. This would need setting up SMTP credentials from EC2 over to send to emscripten-discuss.

**Comment by curiousdannii** [comment]
There's an ATOM feed: https://github.com/kripken/emscripten/releases.atom

And various services that can email you when there's a new release: https://stackoverflow.com/questions/20839622/notifications-for-new-github-project-releases
