### ISSUE TITLE
[Feature Request] Unresolved symbol for functions, in case of wasm should get linked to a stub implementation instead of throwing link error

### ISSUE THREAD

**Issue by tarun550** [emscripten-core/emscripten#6326]
Hi,

Incase of asm.js, missing functions get "linked" to functions that call abort (please correct me if I am wrong). This strategy is great when you have just started porting a huge code base and want to see something working in the browser(if we make sure we do not hit the stub function in our workflow).

Incase of wasm output, the browser complains of a missing symbol and nothing works which makes it difficult to test wasm output.

I would like to request a flag or something similar by which this behaviour can be altered and wasm does not complain, just like asm.js output.

Thanks.

**Comment by kripken** [comment]
The same should happen in wasm, so you may be seeing a bug. What options are you building with? Do you have a testcase showing the problem?

**Comment by tarun550** [comment]
Yes. Sorry that was my bad, I did not test with a simpler case. 
 Basically I have a huge project that works with asm.js but when output is wasm chrome/firefox give this error: 

> LinkError: WebAssembly Instantiation: Import #6 module="env" function="__XXX" error: global import must be a number

I thought that it could be due to a missing symbol, as the function is indeed missing and a warning is also generated for the same. But since it works in asm.js, shouldn't it also work in wasm?

**Comment by kripken** [comment]
It should work, yes, so this may be a bug in asm2wasm (the conversion from asm.js to wasm).

If you can't provide a testcase for us to reproduce the problem, you might use EMCC_DEBUG=1 in the env and look at that symbol through the temp files in emits to the temp dir.
