### ISSUE TITLE
Misleading documentation about main() exit

### ISSUE THREAD

**Issue by shooshx** [emscripten-core/emscripten#6335]
I've followed the advice from [this FAQ](https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions) and implemented `main()` in order to get a notification about when my preloaded files are done loading. After doing that I started to get strange iostream exceptions for code that ran in some event handler and sure enough the console had this:

`segmentation fault`
`Assertion failed: the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)`

I then compiled with `-s NO_EXIT_RUNTIME=1` and that solved the problem.
Now the console had this comment:

`topo_js_main.js:360 exit(0) implicitly called by end of main(), but noExitRuntime, so not exiting the runtime (you can use emscripten_force_exit, if you want to force a true shutdown)`

So this behavior seem to directly contradict the text in [this FAQ](https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#what-does-exiting-the-runtime-mean-why-don-t-atexit-s-run)  that suggests my added fix is the default behavior.

my `main()` function looks like this:

```
int main() 
{
    EM_ASM(start());
}
```
command line:
     `%EMSCRIPTEN%\em++  -g3 -O0 --bind -s ASSERTIONS=2 -s SAFE_HEAP=1 -s DEMANGLE_SUPPORT=1 -s ALLOW_MEMORY_GROWTH=0 -s NO_EXIT_RUNTIME=1 -D_DEBUG -D_LIBCPP_DEBUG=0  --memory-init-file 0 -Wno-switch -Isrc src/main.cpp src/Mesh.cpp --preload-file models/bunny.obj -o out/topo_js_main.html `

using version 1.37.1

p.s. is there any way to remove the annoying `exit(0) implicitly called` warning?

**Comment by kripken** [comment]
The `exit(0) implicitly called` warning has been removed since 1.37.1, I don't see it on incoming. In general that code has been updated a lot recently, so it's possible your issues have been fixed (but I'm not sure, what you report doesn't sound familiar).
