### ISSUE TITLE
WASM with USE_PTHREAD=1 is producing invalid javascript

### ISSUE THREAD

**Issue by avery1701** [emscripten-core/emscripten#6337]
I am compiling an app using Emscription 1.37.35 and flags -s WASM=1 -s USE_PTHREADS=1.  I have enabled SharedArrayBuffer support in my browser for testing.  The resulting Javascript bombs on this line:

Atomics.store(HEAPU32, (PThread.mainThreadBlock + 116 ) >> 2, tlsMemory);

The underlying issue is that HEAPU32 is a Uint32Array backed by an ArrayBuffer instead of a SharedArrayBuffer, so it is throwing "TypeError: invalid array type for the operation".  I am fairly new to emscripten but I'm guessing this is just an error in the js template that is emitted for pthread support?  Any help would be appreciated!

**Comment by hlolli** [comment]
Duplicate of https://github.com/kripken/emscripten/issues/6332 I assume

**Comment by avery1701** [comment]
Agreed.  I found #6332 after I made the post.

**Comment by brion** [comment]
(closing as this is a duplicate)
