### ISSUE TITLE
TypeError: WebAssembly Instantiation: Imports argument must be present and must be an object

### ISSUE THREAD

**Issue by lakinmohapatra** [emscripten-core/emscripten#6351]
Hi 
I downloaded .wasm file . and tried to run following command . 
[fetch('test.wasm').then(res => res.arrayBuffer()).then(buf => WebAssembly.instantiate(buf))
Promise {<pending>}]

It has shown me this error on console. 
TypeError: WebAssembly Instantiation: Imports argument must be present and must be an object

**Comment by kripken** [comment]
How was that wasm generated? If emscripten created it, it will create a .js file too that can load it properly. Otherwise, you need to see what imports the wasm needs, and figure out how to provide them somehow.

**Comment by BrandonDyer64** [comment]
If you used Emscripten, make sure you use the flag `-03` on compiling to make sure the `.wasm` file has the functions exposed,

**Comment by CodeKittey** [comment]
Are there any updates?

llc -version
LLVM (http://llvm.org/):
  LLVM version 6.0.1
  Optimized build.
  Default target: x86_64-apple-darwin17.7.0
  Host CPU: skylake

  Registered Targets:
    js     - JavaScript (asm.js, emscripten) backend
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64

Node Version: v11.4.0

I still get exactly the same

`index_two.html:21 Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #0 module="env" function="__memory_base" error: global import must be a number or WebAssembly.Global object`

Generated wasm with:
`emcc hello.c -O3 -s WASM=1 -s SIDE_MODULE=1 -s EXPORTED_FUNCTIONS='["_fib"]'  -o hello_two.wasm`

Loaded it:

`<script>
(async () => {
  const config = {
    env: {
        memoryBase: 0,
        tableBase: 0,
        memory: new WebAssembly.Memory({
            initial: 256,
        }),
        table: new WebAssembly.Table({
            initial: 0,
            element: 'anyfunc',
        }),
    }
  }
  const fetchPromise = fetch('hello_two.wasm');
  const {instance} = await WebAssembly.instantiateStreaming(fetchPromise, config);
  const result = instance.exports._fib();
  console.log(result);
})();
</script>`
