### ISSUE TITLE
WebAssembly: wrong conversion from double to int64 when OUTLINING_LIMIT isn't 0

### ISSUE THREAD

**Issue by GraDKh** [emscripten-core/emscripten#6352]
The result of the conversion from double to signed/unsigned int64 is wrong when OUTLINING_LIMIT is non-zero.

Having the following code:
```
#include <iostream>
#include <cmath>

int64_t __attribute__ ((noinline)) toSInteger64(double x) {
  return (int64_t)x;
}

int main(int argc, char ** argv) {    
    double a = 1520968721803.0;
    int64_t b = toSInteger64(a);
    std::cout << "result: " << b << std::endl;
    return 0;
}
```
If compile it without setting `OUTLINING_LIMIT` (or setting it to zero) everything is ok:
```
emcc \
    -s WASM=1 \
    -s OUTLINING_LIMIT=0 \
    -g0 -g\
    -w --emrun \
    hello.cpp -o hello.html 
```
`emrun ./hello.html`
>result: 1520968721803

If set some `OUTLINING_LIMIT` and pass `"BINARYEN_TRAP_MODE='clamp'"` the result is wrong:
```
emcc \
    -s "BINARYEN_TRAP_MODE='clamp'" \
    -s WASM=1 \
    -s OUTLINING_LIMIT=100000 \
    -g0 -g\
    -w --emrun \
    hello.cpp -o hello.html
```
`emrun ./hello.html`
>result: 1522565906432

If set some `OUTLINING_LIMIT` and do not set `"BINARYEN_TRAP_MODE='clamp'"` the exception is raised:
```
emcc \
    -s WASM=1 \
    -s OUTLINING_LIMIT=100000 \
    -g0 -g\
    -w --emrun \
    hello.cpp -o hello.html
```
`emrun ./hello.html`
>exception thrown: Error: Out of bounds Trunc operation (evaluating 'Module["asm"]["_main"].apply(null, arguments)'),wasm function: __Z12toSInteger64d@[wasm code]
>wasm function: _main@[wasm code]
>wasm function@[wasm code]
>_main@[native code]

Although as far as I can see setting OUTLINING_LIMIT when compiling to wasm is rather useless (correct me if I'm wrong) it is still quite unexpected behavior.

**Comment by GraDKh** [comment]
Big thank for the answer. As for me - it was quite unexpected that the arithmetic works in a so unexpected way. When reading about trap mode I thought that it is about corner cases - overflows in the C++ sense. But now I see that asm.js type model matters, even if WebAsembly has single operands to do such conversion. It would be very nice to have this moment explained in documentation.
Also do I understand right that outlining doesn't improve the performance of WebAssembly build in general case? If yes it may be reasonable to produce a warning during compilation in this case.

**Comment by kripken** [comment]
Yeah, outlining isn't really needed in wasm, as VMs should be able to handle big functions well anyhow. I agree a warning makes sense there, I opened #6371 for that.

Maybe you can look into improving the docs for the trap mode issue? If you looked somewhere and didn't find an explanation there, that's probably the right place to mention this.

**Comment by GraDKh** [comment]
> Yeah, outlining isn't really needed in wasm, as VMs should be able to handle big functions well anyhow. I agree a warning makes sense there, I opened #6371 for that.

There is a more generic question: is there any sense to make any optimizations that disable wasm-only mode if targeting WebAssembly? Or we can say that in wasm-only code the resulting WebAssembly code will always be better?

> Maybe you can look into improving the docs for the trap mode issue? If you looked somewhere and didn't find an explanation there, that's probably the right place to mention this.

Yes for sure. But I'm not quite sure if my edits would be good enough and preserve the sense. Is there a possibility to make a somewhat like pull request to [https://github.com/kripken/emscripten/wiki/WebAssembly](url)?

**Comment by kripken** [comment]
>  is there any sense to make any optimizations that disable wasm-only mode if targeting WebAssembly

Hmm, good question. In theory that should only be done due to current limitations, like the emterpreter, outlining, etc. that are asm.js optimizer passes. Outlining happens to be not important for wasm, but the emterpreter is. But, eventually we should have something with emterpreter functionality for wasm-only.

> Is there a possibility to make a somewhat like pull request to https://github.com/kripken/emscripten/wiki/WebAssembly?

Is that not publicly editable? In any case, we should probably migrate that from the wiki into the main docs under `site/` since it's pretty stable and official now, and might as well use the normal PR methods on it etc.

**Comment by GraDKh** [comment]
> Is that not publicly editable? In any case, we should probably migrate that from the wiki into the main docs under site/ since it's pretty stable and official now, and might as well use the normal PR methods on it etc.

Yes, it's publicly editable. I've just wondered about the mechanism of reviewing my changes since I'm not sure if I'll describe everything right and the English will be of a good quality :)

**Comment by kripken** [comment]
Oh, ok, now I understand :)

I opened #6418 about moving that page from the wiki. Hopefully someone will want to do that soon.

In the short term for that wiki page, if you aren't sure of your edits, we can discuss them here first perhaps?

**Comment by andreyugolnik** [comment]
Documentation mentions
> WebAssembly can trap on rounding a very large float to an int

I have code that always traps:
```
    size_t getZoneIndex(const ageVector& pos) const
    {
        const auto x = (size_t)pos.x / ZoneSize;
        const auto y = (size_t)pos.y / ZoneSize;

        const auto idx = x + y * m_zoneCols;
        return idx;
    }
```

And no traps in debug mode or when I add logging:
```
    size_t getZoneIndex(const ageVector& pos) const
    {
        my_log_like_printf("%g x %g\n", pos.x, pos.y);
        const auto x = (size_t)pos.x / ZoneSize;
        const auto y = (size_t)pos.y / ZoneSize;

        const auto idx = x + y * m_zoneCols;
        return idx;
    }
```

Where:

```
const size_t ZoneSize = 250;

struct ageVector
{
   float x;
   float y;
};
```

and `ageVector& pos` range is 0.0f - 7500.0f.

I try compile with Emscripten 1.38.1 and 1.38.5.

**Comment by andreyugolnik** [comment]
My ugly workaround is:
```
        const auto x = pos.x / ZoneSize;
        const auto y = pos.y / ZoneSize;

        const auto idx = (size_t)x + (size_t)y * m_zoneCols;
```

**Comment by kripken** [comment]
@andreyugolnik I assume that is without setting the trap mode to clamp? That might be a good solution (if it doesn't work, please let us know).

**Comment by andreyugolnik** [comment]
@kripken thank you for reply.
I doesn't set any trap mode. As I know this means `allow` trap mode by default.
I will try `-s "BINARYEN_TRAP_MODE='clamp'"` option.
