### ISSUE TITLE
EXPORT_NAME and --separate_asm don't work together

### ISSUE THREAD

**Issue by Stuk** [emscripten-core/emscripten#6358]
[separate_asm.py](https://github.com/kripken/emscripten/blob/b64e1d394143ee3ed6a684275337ec46fb0c306d/tools/separate_asm.py) hard codes `Module["asm"] = `, so changing `EXPORT_NAME` has no effect.

**Comment by kripken** [comment]
Thanks for filing, this should be easy to fix and definitely worth doing.
