### ISSUE TITLE
Recursion in  _gmtime

### ISSUE THREAD

**Issue by TomerHeber** [emscripten-core/emscripten#6367]
Hi,

I'm getting a strange recursion when calling _gmtime:

  function _gmtime(time) {
      return _gmtime_r(time, ___tm_current);
    }

var real__gmtime_r = asm["_gmtime_r"]; asm["_gmtime_r"] = function() {
  assert(runtimeInitialized, 'you need to wait for the runtime to be ready (e.g. wait for main() to be called)');
  assert(!runtimeExited, 'the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)');
  return real__gmtime_r.apply(null, arguments);
};

printing:

> Module["asm"]["_gmtime_r"]
ƒ 198() { [native code] }

Any ideas?

**Comment by kripken** [comment]
I don't understand, where's the recursion? As far as I can tell,

 * gmtime calls gmtime_r
 * gmtime_r has a wrapper in assertions mode that checks if the runtime is ready

**Comment by TomerHeber** [comment]
Hi,

My apologies.

Here is some more info:
detect.js:39 RangeError: Maximum call stack size exceeded
    at Module._gmtime_r (magic.js:1)
    at _gmtime (magic.js:5473)
    at /wasm-function[198]:40
    at Module._gmtime_r (magic.js:5805)
    at _gmtime (magic.js:5473)
    at /wasm-function[198]:40
    at Module._gmtime_r (magic.js:5805)
    at _gmtime (magic.js:5473)
    at /wasm-function[198]:40
    at Module._gmtime_r (magic.js:5805)
reader.onload @ detect.js:39

It's straightforward to reproduce on my website with certain file types.
When trying to detect gzip file, it might be calling gtime, and is running into an endless loop.
I was thinking it might be a problem with the source code I used (maybe gtime was compiled incorrectly).

Attached a sample file, the url to to reproduce it is https://detect-file-type.com

Any pointers on how to investigate it further are 
[dummy.txt.gz](https://github.com/kripken/emscripten/files/1844369/dummy.txt.gz)
 appreciated.

Thank you,
Tomer.

**Comment by kripken** [comment]
Thanks for the extra info. I don't see an attached file that was mentioned, though?

It would be best if you can attach a cpp file that is a complete testcase I can compile and run in order to see this problem.

If that's not practical for you, do things change when you build with ASSERTIONS? Perhaps that can catch a problem.
