### ISSUE TITLE
API documentation on Asyncify vs Emterpretify-async

### ISSUE THREAD

**Issue by atrosinenko** [emscripten-core/emscripten#6375]
On [this documentation page](http://kripken.github.io/emscripten-site/docs/api_reference/emscripten.h.html) there is two separate headings:

* Emterpreter-Async functions
* Asyncify functions

This may be slightly misleading, since looks like now there is no such function that is supported in Asyncify, but not in Emterpretify-async. Is it right?

**Comment by kripken** [comment]
Good point, yeah, I think we can merge those sections now.

**Comment by atrosinenko** [comment]
Meanwhile, do we have functions that, conversely, exist in Emterpretify-Async but **not in** Asyncify?

**Comment by kripken** [comment]
I'm not sure offhand. Good point, yeah, we should read `library_async` carefully and make a list of which are implemented in each of those modes.
