### ISSUE TITLE
Clipboard API?

### ISSUE THREAD

**Issue by alexzielenski** [emscripten-core/emscripten#6377]
I wonder if it would be possible to add the new HTML Clipboard API to the html5 header? This functionality would be very useful to users of emscripten.

https://w3c.github.io/clipboard-apis/

**Comment by kripken** [comment]
Sounds good. Is browser support wide enough, though?

To add this, we should add to the HTML C API (under `system/include/emscripten/html5.h`).

**Comment by alexzielenski** [comment]
According to caniuse (https://www.caniuse.com/#feat=clipboard) support is at 86% of all browsers. However, there seem to be a lot of caveats across difference user agents.

**Comment by kripken** [comment]
Caveats sound worrying, but hopefully basic stuff will work (like github copying the clone command/url seems to work in all browsers I've tried).

**Comment by miguelsaldivar** [comment]
I'll work on this 😄

**Comment by kripken** [comment]
Great, thanks @miguelsaldivar !
