### ISSUE TITLE
Low Framerate for mobile browser

### ISSUE THREAD

**Issue by njligames** [emscripten-core/emscripten#6389]
Hello, I build the 'testdraw2' test from SDL2 with these flags: 
`-O3 -DNDEBUG --llvm-opts 3 --js-opts 1 --closure 1`

Here is the result:
https://www.njligames.com/njlic/NJLIC-exe.html

When I run it on the Safari Mobile (iphone 7+), it runs very slow.

I was wondering what I can do to make it not run slow?

Thanks.

**Comment by njligames** [comment]
Bump.
Does emscripten support mobile browsers?

**Comment by eclecticdave** [comment]
Hi,  I don't have any apple devices myself, but according to caniuse.com iOS Safari does not support asm.js (so it runs at normal javascript speeds).  However wasm is a little more promising - iphone 7 is no good, but iphone 8 should have Safari 11.2 which does support wasm.

**Comment by kripken** [comment]
There have been some bugs in mobile safari's wasm support, but hopefully they are all resolved now. If not, please let us know.

In general, emscripten output works on mobile browsers, but it really depends on which browser, and on iOS in particular we sometimes have to wait for mobile safari to ship fixes or speedups (as other browsers are not allowed).
