### ISSUE TITLE
llc hangs for a specific project

### ISSUE THREAD

**Issue by janjongboom** [emscripten-core/emscripten#6391]
I'm building a simulator for embedded systems, and for every application I see very short compilation times (2-5 seconds), except for one and I'm trying to figure out what's going on. I don't see the same issue when compiling the application with GCC ARM 6.

What I see is that it starts the `LLVM => JS` step, then runs `llc` which consumes a single core (so it's doing something). This step then just keeps hanging consuming 100% CPU.

Some info on my environment:

* MacOS 10.13.3 on a MBP 2017 model (3.5 GHz Core i7, 16GB RAM).
* emcc version:

    ```
    emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.36
    clang version 5.0.0  (emscripten 1.37.36 : 1.37.36)
    Target: x86_64-apple-darwin17.4.0
    Thread model: posix
    InstalledDir: /Users/janjon01/toolchains/emscripten/emsdk-portable/clang/e1.37.36_64bit
    INFO:root:(Emscripten: Running sanity checks)
    ```

* Build flags:

    ```
    -s ASYNCIFY=1 -s NO_EXIT_RUNTIME=1 -s ASSERTIONS=2 -std=c++11 -g4 -Wall
    ```

* Using a precompiled library with most of the code (`.bc` file).
* I'm preloading some files, but dropping that argument does not change things.

[Build log](https://gist.github.com/janjongboom/6df01202270bc6e3cdf88806b66bbccb)

I've also uploaded the complete project (has a `build.sh` script that has the full command): [Full project](http://janjongboom.com/downloads/utensor-helloworld-emscripten.zip). The `mbed-simulator` folder is the same for all projects, and always builds quite fast; but there's something in `utensor-helloworld` that triggers something in llc and I cannot find what it is.

If you have any flags (already building with `EM_BUILD_VERBOSE=3 EMCC_DEBUG=1`) that can provide with more info that would be great.

**Comment by kripken** [comment]
My first guess would be ASYNCIFY - that may grow the code by a huge amount in some cases, and it happens in the llc phase (and nothing like it happens in gcc etc., so it would explain that difference too). If you build without ASYNCIFY, does it still hang there? (of course it won't run properly, but just looking at compilation)

If ASYNCIFY is indeed the issue, then the [emterpreter-async](https://github.com/kripken/emscripten/wiki/Emterpreter#emterpreter-async-run-synchronous-code) option might work better. It can run the code slower in some cases, but it avoids the bad cases of huge code growth that ASYNCIFY has.

**Comment by janjongboom** [comment]
@kripken Yes, indeed. That solves the issue. Will see if I can retool around emterpreter-async. Thanks for the quick hint.

**Comment by janjongboom** [comment]
Note that I was using it in the past, but it was breaking source maps support (https://github.com/kripken/emscripten/issues/5862).

**Comment by kripken** [comment]
Hmm, do you actually need source maps when the emterpreter is on? It will not be able to show them anyhow as the code is interpreted from bytecode? Or do you want it for the non-interpreted code?

**Comment by janjongboom** [comment]
@kripken Source maps lets me show the C++ code in the browsers debugging window and then actually break on this code. Quite a nice feature, but could disable it for certain projects.

**Comment by kripken** [comment]
But just on C++ code that isn't run in the emterpreter, correct? Do you have enough code left out of the emterpreter that it's useful?

**Comment by janjongboom** [comment]
So the user application looks something like:

```
int main() {
    while (1) {
        // do useful stuff
        wait_ms(50);
    }
}
```

As far as I can see I have to emterpretify the main function, which is where all the interesting stuff lives? This is all code for microcontrollers, so single main loop and some state management done by the user himself (although we have constructs around it, but I don't want to force the user to use these).
