### ISSUE TITLE
WebGL2 Functions Not Found

### ISSUE THREAD

**Issue by blockulator** [emscripten-core/emscripten#6401]
When I run with emrun and view in the browser the program fails on every OGL call.

`exception thrown: TypeError: Cannot read property 'getParameter' of undefined,TypeError: Cannot read property 'getParameter' of undefined
    at _glGetString (http://localhost:8080/)
    at wasm-function[961]:234
    at wasm-function[729]:1796
    at wasm-function[726]:1041
    at Object.Module._main (http://localhost:8080/)
    at Object.callMain (http://localhost:8080/)
    at doRun (http://localhost:8080/)
    at http://localhost:8080/`

Here's how I'm linking in my cmake file. Is there anything I'm missing?

`set_target_properties(lumin PROPERTIES SUFFIX ".html" LINK_FLAGS "--bind  -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s USE_SDL=2 -s USE_WEBGL2=1 -s WASM=1 -s NO_EXIT_RUNTIME=1 -s ASSERTIONS=1 -s DEMANGLE_SUPPORT=1 -s \"BINARYEN_METHOD='native-wasm'\" --emrun -std=c++11 -O2")`

**Comment by kripken** [comment]
The error suggests `GLctx` does not contain a proper GL context. Did setting up GL work properly, any errors or warnings shown? `ASSERTIONS, GL_ASSERTIONS, GL_DEBUG` might help.

**Comment by tuket** [comment]
For anyone coming from google search. In my case, I was using SDL and I forget to specify the right GLES context params:

```c
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
```
