### ISSUE TITLE
library_glfw.js: glfwFocusWindow/glfwGetWindowAttrib(window,GLFW_FOCUSED) broken

### ISSUE THREAD

**Issue by podsvirov** [emscripten-core/emscripten#6409]
The only window that we can create perfectly handles all input events, but never is focused?

**Comment by podsvirov** [comment]
For example, in the `ImGui's` `opengl2_example` the `GLFW_FOCUSED` attribure checked beafore work with window, but window never is focused.
For more info see ocornut/imgui/pull/1713.

**Comment by kripken** [comment]
Do you mean that the user must click on the window manually first?

**Comment by kripken** [comment]
There is an open PR for adding multiwindow/multicanvas support for SDL (I don't remember if in the SDL2 ports repo or in this one).

I'm not familiar with glfw, but yeah, it sounds like that flag should be changed. In theory perhaps the right behavior is to say the window is focused if the tab is active, or something like that? Anyhow, PR for this would be very welcome.

**Comment by podsvirov** [comment]
Hey guys, can anyone help here or advise a possible implementor?

Cc: @satoshinm, @guillaumeblanc, @cgibson...

**Comment by greggman** [comment]
In your init code before creating a window call

    glfwWindowHint(GLFW_FOCUSED, 1);

Of course we could also add direct support for that feature but if you just want things to work that will do it.

You can also hack on [`library_glfw.js`](https://github.com/kripken/emscripten/blob/incoming/src/library_glfw.js) and just change [line 96](https://github.com/kripken/emscripten/blob/a977b34fd94f6e16008ac6c742269ab4d31302e1/src/library_glfw.js#L96) from

      0x00020001:0, // GLFW_FOCUSED

to

      0x00020001:1, // GLFW_FOCUSED

Maybe that should be the default?

I thought about looking into making focus work but it's not an easy as it sounds. Is it that the tab is focused or is it that particular canvas? In other words you can run multiple emscripten apps on a single page, clicking on one seems like it should focus that particular app. But I can also imagine that even if that particular canvas does not have the focus some apps want the focus constantly (meaning even if the user never clicks the canvas they want the mouse position to be transmitted to the app).

So, not really sure what to do there.
