### ISSUE TITLE
Passing args into js file from originally C++ linux command line binary file args

### ISSUE THREAD

**Issue by ericchenmelt** [emscripten-core/emscripten#6434]
We are trying to compile libraptorQ into JS.
In the C++ library, you can pass in args through terminal like this:
`RaptorQ encode -s 101 -w 1024 -r 10 testimage.jpg blocksje`
or
`RaptorQ decode -s 101 -w 1024 -r 103424 blocksje testimagedecoded.jpg`

I attached the library js file that I compiled as well as the lib I compiled from. Do you know how do we pass arguments into the JS file?
[Library JS File + Original C++ file.tar.gz](https://github.com/kripken/emscripten/files/1888188/Library.JS.File.Original.C.file.tar.gz)

Here is the link to LibRaptorQ repo
https://github.com/LucaFulchir/libRaptorQ

**Comment by kripken** [comment]
You can pass commandline arguments to a compiled program by setting `Module.arguments`, see https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.arguments

(That will be set automatically for you when running in node.js or a JS shell, from the actual arguments.)
