### ISSUE TITLE
Protecting image content

### ISSUE THREAD

**Issue by TZBH** [emscripten-core/emscripten#6439]
Say I’d like to display some confidential content (e.g. image) to the user of my page. How can webassembly help me protect it considering user may have access to Developer tools? I’d like to make sure the content cannot be saved (especially in original format).
From what I can see the emscripten API is basically a glue to the API provided by the browser. This means operations will go through glue code and if the glue can be modified all data can be intercepted.
Is there anything better than using watermarks? I understand even in this case all image loading/decoding and watermarking code will need to be embedded in my webassembly as otherwise it will still go through the glue code (e.g. if I try to use SDL to load the image or WEBGL to set it as texture) and then the original image can be intercepted.

**Comment by tbfleming** [comment]
There's a dedicated button on my keyboard that defeats any web page that attempts to do this. Most keyboards have it: PrtScn. It's an OS function that browsers can't disable.

**Comment by TZBH** [comment]
I'm aware of Print Screen, and Snipping Tool available on Windows. Protection of final image is not possible on most of current environment. My problem is protection of the original. I.e. if I e.g. want to use WebGL to blend original image with watermark, the original image will be passed to WebGL through JS layer and can be intercepted there. This means to me the only way is to do all processing within Webassembly and only ever pass final data to be displayed.

**Comment by tbfleming** [comment]
Any chance you can do the watermarking on the server? For your use case, the user's machine is a hostile environment since like you noted, the interface between wasm and the browser is easy to intercept by design.

**Comment by TZBH** [comment]
Doing it on the server is of course an option, but not one that I'd prefer. Historically we used to do it in ActiveX on the client, thus doing it still on the client would be the easiest choice, not mentioning avoiding potentially expensive image operations on the server, increase in image size, etc.
I guess one issue here is the expectations. I was expecting webassembly would have direct interface to the browser, without the glue in between where the standard API (like webgl) is involved. This would allow approach similar to ActiveX, where only the final image would be accessible to the outside world if any.
Actually if all API has to go through JavaScript, unless you are going to do heavy number crunching or want to obscure your logic further than JavaScript obfuscation, the advantages of using webassembly rather than only JavaScript look to be unclear to me.

**Comment by tbfleming** [comment]
> heavy number crunching

This and porting existing non-js code are wasm's strong points. e.g. Custom decompression for new file formats. Decrypting files when you trust the user with the keys. Video game engines. In-browser compilers for C++ or other languages.

**Comment by TZBH** [comment]
Porting existing code is fine (although I would think it's a bit late for that).
However isn't the intermediate glue layer actually an issue for game engines? Wouldn't the requirement to copy/translate data on each method call be a large hindrance? Wouldn't it result in cases where actually webassembly would slow down your game? E.g. if your logic wasn't too complex and most of your work involved canvas/webgl operations.

**Comment by tbfleming** [comment]
The logic in the existing AAA game engines (e.g. Unity) is complex. There's another advantage to using WebGL from wasm instead of JS: the WebGL API expects large data to be in an ArrayBuffer. Linear memory has an ArrayBuffer interface, making large contiguous blocks of data in C++'s heap perfect for WebGL.

**Comment by TZBH** [comment]
But nonetheless all interaction with WebGL is exposed and can be intercepted, isn't it?

**Comment by tbfleming** [comment]
Yes.

e.g. here's some JS glue in a demo I wrote:

```
glBufferData(target, size, data, usage) { 
    gl.bufferData(target, new Uint8Array(emModule.buffer, data, size), usage);
},
```

```new Uint8Array(``` doesn't copy data. Instead it constructs a view on the data for WebGL to consume.

The demo is at https://tbfleming.github.io/cib/#gist=3e3b86b9d70d87a38cc61bfba2f12a79 .  Firefox (fastest) and Chrome (slow to initialize the page)

**Comment by TZBH** [comment]
Thanks for your answers. I understand in my case the approach I've mentioned would probably be the best. I do not need dynamic image changes/painting, etc. like games do, but do need some at least basic image protection and some 2D image processing, thus it seems best is to do all processing as pure C++ within webassembly and only pass input and get ready output to be displayed using standard JS. I do not see that in my case using any emscripten API (other than console output for diagnostic purposes) would add much value.
