### ISSUE TITLE
emcc -- command not found

### ISSUE THREAD

**Issue by briefy** [emscripten-core/emscripten#6447]
i referenced the tutorial [http://webassembly.org/getting-started/developers-guide/](http://webassembly.org/getting-started/developers-guide/)
and found a similar issue #5696 

however i cannnot figure out how can this be done?
i really wanna use emcc to test wasm

**Comment by kripken** [comment]
More information could let us help you better: what OS are you on? How did you install the emsdk? Did you get any errors while doing so? What is the full error you get when trying to run emcc?

**Comment by briefy** [comment]
@kripken . 
i am using a `macOS x`, and i am sure other requirements are met
there are no errors, it only says `emcc: command not found` at last
i checked the emsdk directory, i didnt find any file name `emcc`

the steps are, exactly the same by the [tutorial](http://webassembly.org/getting-started/developers-guide/)
```
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
```

**Comment by bnjm** [comment]
I ran into this problem on MacOS too even after running through the thread: https://github.com/kripken/emscripten/issues/5696

In my case I hadn't run the activate step after installing:
`./emsdk activate --global --build=Release sdk-incoming-64bit binaryen-master-64bit`

**Comment by wortwart** [comment]
Same here, on Ubuntu in a VM. I followed the steps in the tutorial (including installing all prerequisites) and then:

```
git clone https://github.com/juj/emsdk.git
cd emsdk
./emsdk update /* which says I should use git pull instead */
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
```

And `ls` returns:

```
bin
binaryen-tags.txt
clang
Dockerfile
emcmdprompt.bat
emscripten
emscripten-tags.txt
emsdk
emsdk.bat
emsdk_env.bat
emsdk_env.ps1
emsdk_env.sh
emsdk_manifest.json
emsdk.ps1
emsdk_set_env.sh
LICENSE
llvm-tags-32bit.txt
llvm-tags-64bit.txt
node
README.md
zips
```

... but no emcc executable. Where did I go wrong?

**Comment by kmturley** [comment]
I solved by adding this line to my .bash_profile file:
```
# Web Assembly paths
source "/Users/${USER}/Sites/emsdk/emsdk_env.sh"
```

**Comment by sebastienmascha** [comment]
More accurate is:
`source path/to/emsdk/emsdk_env.sh`

If you do not want to run this command each time you reload your terminal, you should put it on .bash_profile (as suggest @kmturley) or .zprofile if you're using ZSH.
