### ISSUE TITLE
ioctl() terminal window syscalls not implemented

### ISSUE THREAD

**Issue by Aearnus** [emscripten-core/emscripten#6463]
Hey, I was trying to compile libreadline to JavaScript, but to no avail. Upon successful compilation and inclusion, the program using libreadline fails to load due to an unimplemented syscall -- syscall `0x00005414`, usually implemented in `/usr/include/asm-generic/termios.h`. Screenshot relevant and attached.

![syscall screenshot](https://user-images.githubusercontent.com/6219010/39037194-9dcd8282-4434-11e8-9785-5fff9dafc767.png)

If this is my fault compiling readline incorrectly, please point me in the right direction or close this ticket.

**Comment by kripken** [comment]
Doing a grep for that ioctl code in our system code (under `system/`), looks like it's `TIOCSWINSZ`, and reading some online docs for that, it seems to be setting the window size?

We don't have much terminal window support right now, but in principle we could add it. The first question is what does "window" mean here - our default html contains a textarea, which I suppose would be the natural thing to refer it to? Then the question is whether HTML textareas support is enough for this purpose (or would we need a canvas?). Once that's figured out, the main implementation for this would go in `src/library_syscall.js`, see for example #6466 for a recent PR implementing another syscall thing.

**Comment by Aearnus** [comment]
I'll try and get on this once I get a minute tonight. Is there anything special I have to be aware of when using `emsdk` with a custom version of emscripten?

**Comment by xloem** [comment]
I'm working on terminal support for things like this a little at https://github.com/xloem/emterm.git
