### ISSUE TITLE
Document C++ name mangling issues better

### ISSUE THREAD

**Issue by pikachuk** [emscripten-core/emscripten#6465]
Hello, i'm posting this because i've a weird problem, when i'm using emscripten to compile my C++ code to webassembly, things are working, but the names of the functions are not the same, and when i look at documentations about webassembly, function names are supposed either to have the same name, either to have the same name with an underscore before, but in my case the name follows this format

__Z[NumberOfLetters] + FunctionName + v

for instance the function int roll_dice()
would be renamed to "__Z9roll_dicev" in the generated js glue code
which is pretty weird, it means that it requires me to always check the glue code when i want to call a function to remember its name

ps : i tried to manually set the function names by adding them to the build command line instead of KEEPALIVE and it didn't find the function definition until i copy pasted the same kind of weird name
so it must probably search the function name in the linker instead of searching in the cpp files which produces this kind of weird name

**Comment by kripken** [comment]
Most of that is C++ name mangling: the name `_Z9roll_dicev` is how C++ mangles `roll_dice`. You can use the `c++filt` utility to demangle them to confirm,
```
$ c++filt _Z9roll_dicev
roll_dice()
```
In addition, emscripten prefixes compiled methods with a `_`.

**Comment by kripken** [comment]
To avoid C++ name mangling, you can write your code in `.c` files or use `extern "C"` in the source.

**Comment by kripken** [comment]
Ah interesting, I never heard of that `asm()` notation :)

I agree it would be nice to add more docs about this. Perhaps a FAQ entry? If you have a little time, a PR would be very welcome.

**Comment by pikachuk** [comment]
What's a PR ?

**Comment by kripken** [comment]
A [pull request](https://help.github.com/articles/about-pull-requests/).

**Comment by pikachuk** [comment]
I looked at pull requests but it seems to be more related to code changes, i don't really know how i could suggest this for the FAQ

**Comment by mischnic** [comment]
The website is in this repository just like the actual source code: https://github.com/kripken/emscripten/blob/incoming/site/source/docs/getting_started/FAQ.rst

**Comment by jtorresfabra** [comment]
Just wanted to comment that this issue is now handled with embind (https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html) so probably this issue can be closed
