### ISSUE TITLE
Only some images loading

### ISSUE THREAD

**Issue by arasouli91** [emscripten-core/emscripten#6470]
I have tried so many possible combinations of flags and any fixes from the other similar issues, but nothing is working. Some of the images load and one doesn't
I am trying to use this:  --preload-file assets
All my images are in the assets folder. And, when I use this flag: --use-preload-plugins 
The one missing image loads, but then some that previously loaded won't load anymore. Here is the compile command I am using:
em++ *.cpp -O2 -s TOTAL_MEMORY=134217728 -s WASM=1 -std=c++11 -s USE_SDL=2 -s USE_SDL_IMAGE=2  -s SDL2_IMAGE_FORMATS='["png"]' --use-preload-plugins --preload-file assets -o index.html

I tried ALLOW_MEMORY_GROWTH and changing the optimization levels, but nothing.
Without --use-preload-plugins, there is only one image missing. I tried embedding that one image instead, but then it is resized, which is undesirable.

I think this is unrelated, but for a few hours of testing different compilation configurations there were no errors produced in browser console, now there is this:
wasm streaming compile failed: TypeError: Response has unsupported MIME type       index.html:1249
falling back to ArrayBuffer instantiation       index.html:1249
Calling stub instead of sigaction()      index.html:1249
emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.       index.js:1

**Comment by kripken** [comment]
Those warnings in the log do look unrelated.

To debug this, I'd also look in the network devtool in the browser - just to make sure there isn't some kind of network error. Also I'd build with `SAFE_HEAP` and `ASSERTIONS` to add some checks, might find something.

**Comment by arasouli91** [comment]
This is very strange. This code is from my texture manager. I added this #ifdef block, and now all my images load. Except, I don't actually have any images stored at that URL, and the onFailed function gets called for each image load. So, they don't load from the URL. They must load from the preloaded assets. But, when I remove the #ifdef block, my images don't load.

```C++
#ifdef __EMSCRIPTEN__
        std::string s = "https://grafflife.000webhostapp.com/2/"; s+=texture;
	const char *URL = s.c_str();
	emscripten_async_wget(URL, texture, onLoaded, onFailed);
#endif
	SDL_Surface* tempSurface = IMG_Load(texture);
	if (!texture)
	{
		printf("IMG_Load: %s\n", IMG_GetError());
		return 0;
	}
```

texture holds the local file address like: assets/asphalt.png
So, the #ifdef block doesn't modify texture. I believe wget attempts to retrieve the file from the URL and emulate it at the location in texture like assets/asphalt.png.

Does this work because despite the file not existing at the URL, and wget failing, wget still emulated the file? The file that does exist in the virtual FS, because it was preloaded. Yet for some reason, the file was not retrievable before. 

BTW, there is never any IMG_Load errors, whether or not the images show up in the game.
