### ISSUE TITLE
Add registration functions for WebVR-specific events.

### ISSUE THREAD

**Issue by sebcrozet** [emscripten-core/emscripten#6472]
As mentioned by @Squareys in https://github.com/kripken/emscripten/pull/5508#discussion_r143470069, being able to register callbacks to, e.g., the `vrdisplayactivate`, `vrdisplaydeactivate` events (see the list and documentation [there](https://developer.mozilla.org/en-US/docs/Web/Events/vrdisplayactivate)) would allow to request the device to present when it becomes active.

**Comment by Squareys** [comment]
Hi @sebcrozet !

Yes, that would be nice to have, but as mentioned in https://github.com/kripken/emscripten/pull/5640#issuecomment-358419754 I don't know whether it would be worth doing anymore WebVR related stuff before WebXR device API\*.
Thanks for mentioning that comment, though. I had forgotten, that there was another reason why the dependency on the html5 API would make sense apart from having `EMSCRIPTEN_RESULT`, which can instead be moved to emscripten.h.

Cheers, Jonathan.

\* I believe nobody will keep you from create a pullrequest, though ;)
