### ISSUE TITLE
Missing glGetError

### ISSUE THREAD

**Issue by zajo** [emscripten-core/emscripten#6485]
I believe I found a bug. The following code:

```
#include <emscripten/html5.h>
#include <GLES3/gl32.h>

int main() {
	EmscriptenWebGLContextAttributes attr;
	attr.depth=true;
	attr.alpha=true;
	attr.stencil=true;
	attr.majorVersion=3;
	attr.minorVersion=3;
	emscripten_webgl_init_context_attributes(&attr);
	int ctx = emscripten_webgl_create_context(0, &attr);
	emscripten_webgl_make_context_current(ctx);
	(void) glGetError();
	return 0;
}
```

Built with:

```
-s USE_WEBGL2=1 -s HEADLESS=1
```

Running on `node`, fails with:

```
exception thrown: TypeError: GLctx.getError is not a function,TypeError: GLctx.getError is not a function
    at _glGetError <REDACTED>test.js:2839:22)
    at _main <REDACTED>test.js:3137:3)
    at Object.asm._main <REDACTED>test.js:6277:21)
    at Object.callMain <REDACTED>test.js:7483:30)
    at doRun <REDACTED>test.js:7541:60)
    at run <REDACTED>test.js:7555:5)
    at Object.<anonymous> <REDACTED>test.js:7670:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
<REDACTED>test.js:113
      throw ex;
```

**Comment by kripken** [comment]
Looks like a bug, indeed. It should be added to `src/headlessCanvas.js`.

If you or someone else want to try and need help, let me know.

**Comment by Gioyik** [comment]
Hey @kripken, I want to give this a try. Could you give me more context or input about where to start? Thanks

**Comment by kripken** [comment]
@Gioyik great, thanks!

Basically, that error shows that `getError` does not exist on that object, which is our "fake headless GL implementation". We implement things there just to let an app keep running, but without doing any actual rendering. The code is in `src/headlessCanvas.js`, so we need to add that method there, and implement it as best we can (an option might be to always return "not an error", but maybe we do want to handle some errors?).

**Comment by kripken** [comment]
Maybe the name is somewhat confusing. Our headless mode is basically a mode where no rendering happens. We do need to perform just enough work so that code *thinks* rendering occurs. This helps simulate and debug programs in the shell.

**Comment by zajo** [comment]
Is there a mode where I can boot up GL in emscripten/node, load up shaders, draw, capture the output in a PNG and write it to disk? My goal is to port my graphics engine to emscripten, and I need this to run the unit tests.

(As a side note, in my view "headless" doesn't mean or suggest "stubbed-out" at all. It should probably be renamed.)

**Comment by kripken** [comment]
Emscripten doesn't have a mode for that, but I think you can use chrome or firefox in headless mode to run emscripten code. However, I'm not sure they can do things like GL - we run firefox headless in our CI, and we had to disable GL tests.

I agree the name in emscripten might not be good, yeah. Open to suggestions for renaming, PR would be welcome if someone has an idea.

**Comment by zajo** [comment]
Thank you, this is helpful. Question: how do you guys run OpenGL unit tests for Emscripten?

**Comment by kripken** [comment]
We only run them locally, not on CI. Locally, `python tests/runner.py browser` will run the test suite, it opens a window in the default system browser. For GL, most tests render and then compare to a reference image.

**Comment by zajo** [comment]
I suppose the comparison is done in `runner.py`? I have a similar system of comparing to a reference image, but it's all C++, so I was trying to get that to work on node. I suppose there's no way to get this to work, right?

**Comment by zajo** [comment]
I suppose the comparison is done in `runner.py`? I have a similar system of comparing to a reference image, but it's all C++, so I was trying to get that to work on node. I suppose there's no way to get this to work, right?
