### ISSUE TITLE
Load .wasm file from a variable.

### ISSUE THREAD

**Issue by strepkov** [emscripten-core/emscripten#6486]
Hi,

Could you please help me. I can't use the local links to the files(.js and .wasm) due to I receive these files after a compilation from a webserver. Because of that they just stored in the memory. I able to inject the content of .js file into <script>content of .js</script>. But the problem is that it tries to find in the root directory the .wasm file, what is logically. The main question is: How to upload the variable with .wasm content that the .js script be able to find it? Thank you in advance for your responce!

PS.: Sorry if my explanaction is not detailed enough, just ask me please :)

**Comment by kripken** [comment]
I think [locateFile](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile) might help here.

**Comment by strepkov** [comment]
Thank you really much for your answer! 
Should I then instantiate the .wasm file with WebAssembly.instantiate() from the memory and then give this instance to the locate function?

**Comment by strepkov** [comment]
I have already check the data with WebAssembly.validate() and it's valid. I have written the overloading of locateFile function for Module.

var Module = {	
                       locateFile: function(file) {
			    return path + file;
		      }
};

but how I understand it should return the path, but I need to pass binary data.

**Comment by dschuff** [comment]
So if I understand you correctly, you don't have a file, you basically have the data in an arraybuffer or something? You can also override [Module.instantiateWasm](https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.instantiateWasm) to give you more complete control over wasm instantation.
