### ISSUE TITLE
Unresolved externals while building custom SDL_mixer

### ISSUE THREAD

**Issue by despair86** [emscripten-core/emscripten#6487]
I'm having a problem building a custom SDL_mixer 1.2 build. I've back-ported some patches from a custom SDL2_mixer to support OggOpus music output. These patches otherwise work properly on a native target. (https://gitgud.io/despair/sdl-mixer)

I'm getting unresolved external symbol errors in functions that should already be part of SDL 1.2 or 1.3, see attached screenshot. Only attempted to link the sample apps in-tree (`playmus`/`playwave`), but this may occur in other apps linked against the custom `SDL_mixer.a` bitcode archive.
![2018-04-29-184606_1280x800_scrot](https://user-images.githubusercontent.com/35446253/39412168-9f512586-4bdd-11e8-811c-64db81ccb62e.png)
![2018-04-30-130939_1280x800_scrot](https://user-images.githubusercontent.com/35446253/39442714-cf40022c-4c77-11e8-928e-4103c5e12ae1.png)

Thanks

EDIT: using bleeding-edge emscripten SDK, built from source for OpenBSD 6.3
EDIT 2: Chrome JS console output

**Comment by kripken** [comment]
Is that SDL_mixer 1.2 compiled from source?

In emscripten our SDL 1.x support is not compiled from source, it's handwritten JS, and so pretty focused on a subset of the API (so mixing it with compiled SDL_mixer might not find all it needs). But the SDL 2.x support is compiled, and should be complete, and there is either SDL_mixer support for it already or an open PR for it iirc.

**Comment by despair86** [comment]
@kripken Yes, it's compiled from source, my fork is in the link posted above. 

My new project is intended to be a single, unified multi-platform build, with the same C code being compiled to multiple targets, including asm.js and WebAssembly. In light of this, I shall provide my own implementation of the missing SDL APIs through a preprocessor macro.

I'd be willing to discuss a PR for including the low-level SDL APIs, perhaps selected as part of a optional link library (something like `emcc ... -lSDL1_lowio`?)
```c
#ifdef __EMSCRIPTEN__
/* copy missing SDL1.2 APIs from source tree */
#endif
```

Thanks
R

**Comment by kripken** [comment]
I see - and I guess you need SDL1.x instead of SDL2.0?

For implementing the missing SDL1.x APIs in emscripten, I'd suggest adding them to `src/library_sdl.js`. Unless there's a problem with doing that, but based on their names, I would guess it would be ok - unless I'm missing something?

**Comment by despair86** [comment]
>I'm missing something

Nah, sounds like a plan. I'll probably start out with a few prototypes transpiled from the C source before formatting a JS patch, as I've been MIA from the web-platform for a while....

Thanks!
