### ISSUE TITLE
USE_PTHREADS=2 generate Cannot read property '1' of null error 

### ISSUE THREAD

**Issue by noxytrux** [emscripten-core/emscripten#6508]
Hi I'm trying to force usage of pthreads by using `-s USE_PTHREADS=2` however it fails 

This is the project i'm working on https://github.com/inFullMobile/pixfight (simply follow build, is as simple as `emmake make` in PLATFORM/HTML5 directory)

I have disabled them for now and manage to compile and play it in single thread mode but i would like to use it with threads to have better experience.

I'm starting local server using `python -m SimpleHTTPServer 8000` and game runs until I press end turn. Then i get exception even if I compile with `USE_PTHREADS=2` followed by this output when starting game:  

```
This browser does not support SharedArrayBuffer/Atomics/pthreads! 
Patching out SharedArrayBuffer usage...
pixfight.html:1587 Failed to optimize out SharedArrayBuffer calls 
TypeError: Cannot read property '1' of null
```

Chrome: **Version 66.0.3359.139 (Official Build) (64-bit)**

Is there anything else i need to do, to make it work ?

**Comment by kripken** [comment]
Does it work with `USE_PTHREADS=1`? (the bug here might be in the special runtime fallback to non-threaded code)

Do our docs recommend using `USE_PTHREADS=2` over 1? If so, which page - we should probably change that.

**Comment by kripken** [comment]
Yes, sorry if I wasn't clear before.

Ok, thanks, this looks like a bug in the PTHREADS=2 fallback to non-threads mode.
