### ISSUE TITLE
I am a novice, encountered in the use of emcc compiled into js after the error, compiled through the use of g++ is no problem, there is no problem with me encountered the same trouble to solve, thank you very much!

### ISSUE THREAD

**Issue by whw155** [emscripten-core/emscripten#6525]
C++ source code: Environment is Ubuntu16.04
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <ifaddrs.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
char * myFunction ();
int main(int argc, char *argv[])
{
        char *str = myFunction();
        printf("%s\n", str);
        return 0;

}
char * myFunction () {

        //char *sub_str = malloc(1100 * sizeof(char));
        char* sub_str = new char[100];
        //char *split = ":";
        //char *end = ";";
        struct ifaddrs *ifaddr, *ifa;
        int family, s;
        int x=0;
        char host[NI_MAXHOST];

        if (getifaddrs(&ifaddr) == -1)
        {
                perror("getifaddrs");
                exit(EXIT_FAILURE);
        }

        for (ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next)
        {
                if (ifa->ifa_addr == NULL)
                        continue;

                s=getnameinfo(ifa->ifa_addr,sizeof(struct sockaddr_in),host, NI_MAXHOST, NULL, 0, NI_NUMERICHOST);

                if(ifa->ifa_addr->sa_family==AF_INET)
                {
                        if (s != 0)
                        {
                                printf("getnameinfo() failed: %s\n", gai_strerror(s));
                                exit(EXIT_FAILURE);
                        }
                        if(x==0){
                                strcpy(sub_str, ifa->ifa_name);
                                strcat(sub_str, ":");
                                strcat(sub_str, host);
                                strcat(sub_str, ";");
                        }else{
                                strcat(sub_str, ifa->ifa_name);
                                strcat(sub_str, ":");
                                strcat(sub_str, host);
                                strcat(sub_str, ";");

                        }
                        x++;
                }
        }

        int len = strlen(sub_str);
        sub_str[len - 1] = '\0';
        freeifaddrs(ifaddr);
        return sub_str;
}
After compiling with g++ -o a a.cc, the execution of a can obtain the IP address.

In the emcc syntax, modify the following:
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netdb.h>
#include <ifaddrs.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

extern "C" {
char * myFunction () {
        //char *sub_str = malloc(1100 * sizeof(char));
        char* sub_str = new char[100];
        //char *split = ":";
        //char *end = ";";
        struct ifaddrs *ifaddr, *ifa;
        int family, s;
        int x=0;
        char host[NI_MAXHOST];

        if (getifaddrs(&ifaddr) == -1)
        {
                perror("getifaddrs");
                exit(EXIT_FAILURE);
        }

        for (ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next)
        {
                if (ifa->ifa_addr == NULL)
                        continue;

                s=getnameinfo(ifa->ifa_addr,sizeof(struct sockaddr_in),host, NI_MAXHOST, NULL, 0, NI_NUMERICHOST);

                if(ifa->ifa_addr->sa_family==AF_INET)
                {
                        if (s != 0)
                        {
                                printf("getnameinfo() failed: %s\n", gai_strerror(s));
                                exit(EXIT_FAILURE);
                        }
                        if(x==0){
                                strcpy(sub_str, ifa->ifa_name);
                                strcat(sub_str, ":");
                                strcat(sub_str, host);
                                strcat(sub_str, ";");
                        }else{
                                strcat(sub_str, ifa->ifa_name);
                                strcat(sub_str, ":");
                                strcat(sub_str, host);
                                strcat(sub_str, ";");

                        }
                        x++;
                }
        }
        int len = strlen(sub_str);
        sub_str[len - 1] = '\0';
        freeifaddrs(ifaddr);
        return sub_str;
}
}
carried out    emcc -s EXPORTED_FUNCTIONS="['_myFunction ']" -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall","cwrap"]' example5.cc -o example5.js 

Use the generated file example5.js to use the html file, print the information obtained, and fail to get the information that you want to correspond to the IP

The wording in HTML is as follows：
<script>
    GetLocalIp = Module.cwrap('myFunction');
    document.write("result == " + GetLocalIp());
</script>

The error message is as follows：
pre-main prep time: 2 ms
12345.js:143 bad ioctl syscall 35090
12345.js:146 bad ioctl syscall 35090
12345.js:143 abort("bad ioctl syscall 35090") at Error
    at jsStackTrace (file:///D:/study/h5/asm/js/12345.js:1173:13)
    at stackTrace (file:///D:/study/h5/asm/js/12345.js:1190:22)
    at abort (file:///D:/study/h5/asm/js/12345.js:23412:44)
    at ___syscall54 (file:///D:/study/h5/asm/js/12345.js:5672:18)
    at _ioctl (file:///D:/study/h5/asm/js/12345.js:11071:8)
    at _if_nameindex (file:///D:/study/h5/asm/js/12345.js:11810:12)
    at _getifaddrs (file:///D:/study/h5/asm/js/12345.js:11379:8)
    at _myFunction (file:///D:/study/h5/asm/js/12345.js:7225:8)
    at asm._myFunction (file:///D:/study/h5/asm/js/12345.js:23172:25)
    at file:///D:/study/h5/asm/getLocalIp.html:15:35
12345.js:146 abort("bad ioctl syscall 35090") at Error
    at jsStackTrace (file:///D:/study/h5/asm/js/12345.js:1173:13)
    at stackTrace (file:///D:/study/h5/asm/js/12345.js:1190:22)
    at abort (file:///D:/study/h5/asm/js/12345.js:23412:44)
    at ___syscall54 (file:///D:/study/h5/asm/js/12345.js:5672:18)
    at _ioctl (file:///D:/study/h5/asm/js/12345.js:11071:8)
    at _if_nameindex (file:///D:/study/h5/asm/js/12345.js:11810:12)
    at _getifaddrs (file:///D:/study/h5/asm/js/12345.js:11379:8)
    at _myFunction (file:///D:/study/h5/asm/js/12345.js:7225:8)
    at asm._myFunction (file:///D:/study/h5/asm/js/12345.js:23172:25)
    at file:///D:/study/h5/asm/getLocalIp.html:15:35

Are there expert guidance points, see where the problem is, thank you very much！！！

**Comment by kripken** [comment]
In general our networking/sockets support is fairly limited, mainly because web APIs limit what we can do.

More specifically, grepping for that ioctl code under `system/`, it seems to be `SIOCGIFCONF`. We should check if that is something we can implement on the web. If so, the main impl would go in `src/library_syscall.js`.

**Comment by whw155** [comment]
According to you say so, we through emscripten is unable to get the address of the host by C or C + +?Also fail to C or C + + UDP broadcast or multicast communication?
