### ISSUE TITLE
Float to 64-bit integer conversions generating identical signed/unsigned code

### ISSUE THREAD

**Issue by alexcrichton** [emscripten-core/emscripten#6530]
I was over the weekend looking at enhancing wasm2asm's support for more instructions, and one of the ones I ran across was float<->integer conversions. Instead of reinventing the wheel I figured I'd copy whatever Emscripten is already doing so I generated a [C file](https://gist.github.com/alexcrichton/aefde6384dbafc3840b6f434cf783cc0) to see what emscripten was doing, namely:

```c
#include <emscripten.h>

EMSCRIPTEN_KEEPALIVE
unsigned long long f64_to_u64(double a) {
  return (unsigned long long) a;
}

EMSCRIPTEN_KEEPALIVE
long long f64_to_i64(double a) {
  return (long long) a;
}
```

I then installed Emscripten via:

```
$ git clone https://github.com/juj/emsdk.git
$ ./emsdk install latest
$ ./emsdk activate latest
```

and then I compiled the file as:

```
$ source emsdk_env.sh
$ emcc -O2 -g3 foo.c
cat a.out.js
```

and in the output I see:

```js
function _f64_to_u64($0) {
 $0 = +$0;
 tempRet0 = +Math_abs($0) >= 1.0 ? ($0 > 0.0 ? ~~+Math_min(+Math_floor($0 / 4294967296.0), 4294967295.0) >>> 0 : ~~+Math_ceil(($0 - +(~~$0 >>> 0)) / 4294967296.0) >>> 0) : 0;
 return ~~$0 >>> 0 | 0;
}

function _f64_to_i64($0) {
 $0 = +$0;
 tempRet0 = +Math_abs($0) >= 1.0 ? ($0 > 0.0 ? ~~+Math_min(+Math_floor($0 / 4294967296.0), 4294967295.0) >>> 0 : ~~+Math_ceil(($0 - +(~~$0 >>> 0)) / 4294967296.0) >>> 0) : 0;
 return ~~$0 >>> 0 | 0;
}
```

I was expecting the signed/unsigned versions to be slightly different but it looks like they're the same! @kripken recommended I file a bug to track this, so just wanted to make sure this wasn't lost!

**Comment by kripken** [comment]
This goes beyond my understanding of C type conversions, but consider this program:
```
#include <stdint.h>
#include <stdio.h>

uint64_t f64_to_u64(double a) {
  return uint64_t(a);
}

int64_t f64_to_i64(double a) {
  return int64_t(a);
}

int main() {
  union Union {
    struct {
      uint32_t low, high;
    };
    uint64_t unsign;
    int64_t sign;
  };
  volatile double x = -10;
  volatile Union y;
  y.unsign = f64_to_u64(x);
  printf("%x %x\n", y.low, y.high);
  y.sign = f64_to_i64(x);
  printf("%x %x\n", y.low, y.high);
}
```
emcc and gcc have the exact same output here, so it seems like emscripten does the right thing (unless the testcase is somehow not actually checking for the signed/unsigned conversion difference).

cc @sunfish

**Comment by kripken** [comment]
cc @sunfishcode

**Comment by alexcrichton** [comment]
Ah ok! And FWIW I have no reason to believe that this is incorrect, I just thought it was a little suspicious! If it's passed a whole bunch of test suites it's probably right :)

**Comment by sunfishcode** [comment]
I haven't looked at the code closely enough to say for sure, but it's plausible that f64_to_i64 and f64_to_u64 could use the same code, because:
 - for f64_to_i64, most f64 values in (INT64_MAX, UINT64_MAX], are out of range, and therefore UB
 - for f64_to_u64, most f64 values in [INT64_MIN, 0) are out of range, and therefore UB
