### ISSUE TITLE
SAFE_HEAP=1 breaks source map generation for WASM

### ISSUE THREAD

**Issue by newnon** [emscripten-core/emscripten#6534]
CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8)

project(cpp_with_emscripten_val)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_EXECUTABLE_SUFFIX ".html")

set(EMSCRIPTEN_FLAGS " -s WASM=1")
set(CMAKE_C_FLAGS             "${CMAKE_C_FLAGS} ${EMSCRIPTEN_FLAGS}")
set(CMAKE_CXX_FLAGS           "${CMAKE_CXX_FLAGS} ${EMSCRIPTEN_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS    "${CMAKE_EXE_LINKER_FLAGS} ${EMSCRIPTEN_FLAGS}")

set(EMSCRIPTEN_FLAGS_DEBUG "-g4")
#set(EMSCRIPTEN_FLAGS_DEBUG "-g4 SAFE_HEAP=1")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${EMSCRIPTEN_FLAGS_DEBUG}")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}  ${EMSCRIPTEN_FLAGS_DEBUG}")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} ${EMSCRIPTEN_FLAGS_DEBUG} --source-map-base http://localhost:6931/")

add_executable(cpp_with_emscripten_val main.cpp)
```

main.cpp
```
#include <stdio.h>

int main()
{
	int test_int = 5;
	printf("Hello! test int: %d, __cplusplus: %ld\n", test_int, __cplusplus);
}
```
finally emrun you code place main.cpp where browser will search it(or just edit 1 line in .map file)
and try to set break point with Firefox developer edition everything will work good
then uncomment string SAFE_HEAP=1 and recompile break point not work now

**Comment by kripken** [comment]
I think this is the same as #4224. Basically SAFE_HEAP uses the js optimizer, and optimizing the JS messes up source maps currently.

**Comment by newnon** [comment]
And where is no way to use SAFE_HEAP with source maps?

**Comment by kripken** [comment]
Yes, until that bug is fixed, I think it doesn't work. Although I'm not sure if it's broken entirely or just not as good.

**Comment by newnon** [comment]
May be emscripten compiler should write some warning about SAFE_HEAP & -g4 something like
"source maps can be corrupted if with safe heap enabled"? I spend whole day on this bug.

**Comment by newnon** [comment]
Yes thats the problem - you got same source map but different binary, because after source map generation where is extra step that post process wasm binary.

**Comment by dschuff** [comment]
The safe heap transformation is just a Binaryen pass, right? Does it run after the source map is already emitted? (e.g. emit a binary and source map, then re-parse and modify the binary?)

**Comment by yurydelendik** [comment]
Any wasm binary transformation invalidates source map generated with it. (The JS source maps no different, once JS is changed source map needs to be re-created) The optimizer must transform source map along with code optimization (again similar to JS), or remove source map.

**Comment by kripken** [comment]
I see, thanks @dschuff and @yurydelendik - yes, safe-heap is a binaryen pass now. So what happens with source maps + safe-heap is (in asm2wasm)

 * `asm2wasm` to a wast (which contains comments for code locations), including optimizations.
 * `wasm-as` to convert that to a wasm + a source map
 * `wasm-opt` to run safe-heap on the wasm, which breaks the source map :(

Since we run optimizations in that first phase, it seems like we could just run extra passes then too, by adding that capability to asm2wasm.

I'm not sure how this would work with the wasm backend path, though. We do currently run `wasm-opt` for safe-heap at the end there, like `asm2wasm`, so it seems like we'd need to run it during `s2wasm` or `wasm-emscripten-finalize`, but I'm not sure how source maps fit in with those?

**Comment by yurydelendik** [comment]
wasm-dis has ability to ingest locations from source maps (see https://github.com/WebAssembly/binaryen/blob/7a8273ae2c1854b9840fc56a952e572f673bb10f/src/tools/wasm-dis.cpp#L53). will it be useful for other passes?

**Comment by kripken** [comment]
Thanks, yeah, based on that + discussion on irc, I think we just need to use that in wasm-opt. I'll look into it.

**Comment by kripken** [comment]
wip code in https://github.com/WebAssembly/binaryen/pull/1557

**Comment by VirtualTim** [comment]
I'm pretty sure this issues is fixed. At least it seems to work for me.
I just needed to specify "--serve_root /" for the webserver to actually serve the source maps.

**Comment by kripken** [comment]
Looks like that PR was indeed merged, thanks, closing.
