### ISSUE TITLE
Better wasm source map generation

### ISSUE THREAD

**Issue by newnon** [emscripten-core/emscripten#6535]
it is not good idea to pick you sources by your self
source map support sourcesContent for this purposes
It is possible to process generated source maps
here is python script for this
```
 import sys, os, json

if __name__ == "__main__":

	if len(sys.argv) > 1:
		destPath = os.path.abspath(sys.argv[1])

		if len(sys.argv) > 2:
			sys_path = os.path.abspath(sys.argv[2])
		else:
			sys_path = os.getenv("EMSCRIPTEN")
			if sys_path is None:
				print "can't find emscripten path \n set EMSCRIPTEN environment variable or add EMSCRIPTEN path as second param" 
				sys.exit()

		if len(sys.argv) > 3:
			sources_path = os.path.abspath(sys.argv[3])
		else:
			sources_path = os.path.abspath(os.path.dirname(os.path.realpath(__file__)) + "/.")

		print "sources_path: " + sources_path
		print "sys_path: " + sys_path

		with open(destPath) as data_file:    
			data = json.load(data_file)

		sources = []

		paths = data["sources"]

		for i, path in enumerate(paths):
			with open(path, 'r') as source_file:
				source_data = source_file.read()
			sources.append(source_data)
			if path.startswith(sources_path):
				paths[i] = "sources" + path[len(sources_path):]
			if path.startswith(sys_path):
				paths[i] = "sources" + path[len(sys_path):]

		data["sourcesContent"] =  sources

		with open(destPath, 'w') as outfile:
			json.dump(data, outfile, ensure_ascii=False)
	else:
		print "usage: process_source_map.py {source_map_path}"
```

after this script all compiled files content will be inside source maps and all path will be truncated to more short version
before
```
{
    "mappings": "kqCAIA,IACA,uCACA",
    "names": [],
    "sources": [
        "/Users/user/Desktop/cmake_with_emval/main.cpp"
    ],
    "version": 3
}
```
after
```
{
    "mappings": "kqCAIA,IACA,uCACA",
    "names": [],
    "sources": [
        "sources/main.cpp"
    ],
    "sourcesContent": [
        "#include <stdio.h>\n\nint main()\n{\n\tint test_int = 5;\n\tprintf(\"Hello! test int: %d, __cplusplus: %ld\\n\", test_int, __cplusplus);\n}\n"
    ],
    "version": 3
}
````
you can add some param that add this step to build process i think it can be also useful also for asmjs version to

**Comment by kripken** [comment]
cc @yurydelendik

**Comment by newnon** [comment]
@kripken may be integrate my script somehow in build process?

**Comment by kripken** [comment]
@yurydelendik: I see you thumbed-up the post here - sounds like it looks good to you? How would you suggest we proceed here?

**Comment by yurydelendik** [comment]
First step will be develop a way we can configure such transform:
- [ ] how the "sources" entries are changed (prefix removed or replaced)
- [ ] how the "sourcesContent" items are read -- we need a way to resolve relative or foriegn "sources" entries paths into local file system paths. (Notice that libraries such as musl or libcxx can be build on different computer than end user's)

**Comment by newnon** [comment]
At first step it is possible to not change sources paths.
And it will work just out of box(yes you will see full path from build machine)
Then we can add some param like source_map_prefixes=["prefix1": "replace1", "prefix2": "replace2"]
and for example replace path to emscripten with "system"

**Comment by yurydelendik** [comment]
> At first step it is possible to not change sources paths.

I recommend to add something , at least "wasm-src://" by default (or remove leading `/`), to not confuse debuggers with absolute file path as the current origin: WebAssembly.instance() has no valid origin.

@newnon Can you submit a valid PR with your solution?

**Comment by newnon** [comment]
unfortunately i have no idea how to integrate this inside emscripten build script
