### ISSUE TITLE
CMake 3.12 and Emscripten 1.37.40 or lower do not like each other

### ISSUE THREAD

**Issue by CShankland** [emscripten-core/emscripten#6536]
The upcoming CMake 3.12 release includes a change[1] that defaults the `CMAKE_CXX17_STANDARD_COMPILE_OPTION` and it's related extension property from `c++1z` to `c++17`.  The emscripten compiler (tested against sdk-1.37.40) does not understand this flag[2].

Specifying property overrides such as:
```
set(CMAKE_CXX17_STANDARD_COMPILE_OPTION "-std=c++1z")
set(CMAKE_CXX17_EXTENSION_COMPILE_OPTION "-std=gnu++1z")
```
are sufficient for our use case.  Alternatively, reducing the advertised version of Clang to something between 3.5 and 5.0 will also produce the desired flags.

`em++` uses a prerelease version of clang 5.0.0 which does not support this flag but reports itself as release 5.0.0 which does support this flag[3].

[1] https://gitlab.kitware.com/cmake/cmake/commit/1b328e09a33e61293635c7ddb9bcff986ae8d1e7

[2] Compiler version
```
> em++ -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.40
clang version 5.0.0  (emscripten 1.37.40 : 1.37.40)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Emscripten\clang\e1.37.40_64bit
INFO:root:(Emscripten: Running sanity checks)

>em++ --std=c++17 hello.cc
error: invalid value 'c++17' in '--std=c++17'
note: use 'c++98' or 'c++03' for 'ISO C++ 1998 with amendments' standard
note: use 'gnu++98' or 'gnu++03' for 'ISO C++ 1998 with amendments and GNU extensions' standard
note: use 'c++11' for 'ISO C++ 2011 with amendments' standard
note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standard
note: use 'c++14' for 'ISO C++ 2014 with amendments' standard
note: use 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standard
note: use 'c++1z' for 'Working draft for ISO C++ 2017' standard
note: use 'gnu++1z' for 'Working draft for ISO C++ 2017 with GNU extensions' standard
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```
[3] Clang release notes for 5.0.0 http://releases.llvm.org/5.0.0/tools/clang/docs/ReleaseNotes.html#id1

**Comment by kripken** [comment]
Thanks for the detailed bug report!

It's possible the quickest way to resolve this is to merge in 6.0 (release). I just opened an issue for that here: https://github.com/kripken/emscripten/issues/6544
