### ISSUE TITLE
What to do to dispose finished `emscripten_coroutine`

### ISSUE THREAD

**Issue by paladin-t** [emscripten-core/emscripten#6540]
I'm trying to understand the coroutine functions, my question is do I need to do anything to dispose/free a coroutine created by `emscripten_coroutine_create`, after it's no longer in use? Or just leave it without worrying about leak?

**Comment by kripken** [comment]
The coroutine should be cleaned up when it finishes running. If you're interested, the implementation is in `src/library_async.js`, you can see the matching malloc/free calls there.

**Comment by paladin-t** [comment]
Thanks for the information. If I'm right, a coroutine **must** return normally to let the async library know that it's ready to be freed. Would it be possible to free an infinite coroutine which never returns? For instance:

```c
void func(void*) {
	while (1) {
		// Do something...
		emscripten_yield();
	}
}
```

**Comment by kripken** [comment]
It does seem like such an infinite coroutine would not currently be cleaned up, yeah.

And yeah, it seems like `free(co)` might be enough. We should check if that's the case, and if so we should document it.

**Comment by paladin-t** [comment]
Glad to know that.
