### ISSUE TITLE
Merge LLVM 6.0

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#6544]
Discussion started in https://github.com/juj/emsdk/issues/144#issuecomment-389682105

I opened `next-merge` branches in the 3 repos and got things to compile pretty easily. Running tests, so far I see a SIMD test started to fail but it could just be autovectorization heuristics, and most ofher stuff seems to be passing.

It might make sense to wait for 6.0.1 which is in a few months. However, given this would fix at least 2 bugs (also https://github.com/kripken/emscripten/issues/6536 ) it seems like doing this sooner might make sense.

**Comment by kripken** [comment]
Failures:
 * `other.test_linpack_autovectorize`: no longer seeing vectorization happen in LLVM IR on that code.
 * `default.test_floatvars`: unoptimized `fmin(NAN, 3.3)` returns `NaN` now.

**Comment by kripken** [comment]
The full line `s2wasm` fails on is
```
pow10 = exp10@FUNCTION
```
(from `wasm_libc_rt.a`). I guess this is an alias or something like that? Is it expected it would not work in LLVM6.0 but work in LLVM trunk, i.e. has that changed in s2wasm in recent months? cc @jgravelle-google

**Comment by kripken** [comment]
Other than that (and the autovectorization issue which I think we can safely ignore) all tests pass!

**Comment by jgravelle-google** [comment]
https://github.com/WebAssembly/binaryen/pull/1491 it would appear

**Comment by kripken** [comment]
Thanks @jgravelle-google ! Well, in that case, we can probably just disable the test. The point of it was to help avoid regressing the wasm backend while working on asm2wasm in a simple way, but if it's not practical to check that using fastcomp, we'll just need to be more diligent to test properly.

**Comment by kripken** [comment]
A serious problem has shown up in the benchmark suite. On the one hand, there are some tiny code size wins across the board, and some big ones, 5% on box2d (!), 3% on bullet. But there are also several big slowdowns that must be investigated

 * skinning, box2D: 2x slowdown! :(
 * primes, bullet: 10% slowdown

Given these are all floating-point benchmarks, it seems possible there is a single shared cause here. (Perhaps related to the fmin/fmax changes?)

**Comment by kripken** [comment]
Perf issue looks like a hard problem. The main change is that LLVM inlines a little less in the new version, and in e.g. skinning we no longer inline all the calls in `calculateVerticesAndNormals_x87`. The binaryen optimizer does inline them later, but that only removes the call overhead, we still have the stack usage (more loads and stores).

Options seem to be
 * Accept the regression - inlining is just heuristics and some stuff will get faster or slower. If it were just one benchmark, maybe that would make sense, but 2 with a big slowdown is worrying.
 * Investigate the LLVM inliner issue. But even if we can figure it out, it might mean we need to make local modifications, unless the new heuristics happen to make general sense upstream.
 * Improve the binaryen inliner to handle stack usage. Not easy.

**Comment by kripken** [comment]
In `box2d`, a suspicious issue is that in the new version we import sin/cos from JS and use them, which could cause slowness. I didn't confirm that, but it is wrong in itself. Looking in the IR, LLVM used to emit `cosf` and now emits `llvm.cos.f32`, which we apparently don't handle properly.

**Comment by kripken** [comment]
I added a pass to lower `llvm.cos.f32` etc. to libc calls after optimization, and then linking brings in libc properly etc. This practically fixes the box2d and primes regressions. That leaves skinning and bullet, and perhaps a tiny regression on box2d, all of which I suspect come down to the inlining issue.

**Comment by kripken** [comment]
The inlining issue was that something in TTI changes, and it wasn't using the asm.js TTI, and then it thought float operations were always expensive (the default in LLVM now?) which meant inlining didn't make as much sense.

Fixed now, so I think we can merge this soon.

**Comment by kripken** [comment]
Running the full benchmark suite, major speed regressions are gone. Some minor changes in both directions, and one big speedup on `copy`. On the other hand, all the size improvements are gone now that we inline properly again ;) and now we have tiny size regressions across the board, oh well.

**Comment by kripken** [comment]
I verified the entire test suite passes now properly. If there are no concerns I can merge this tomorrow.

**Comment by jgravelle-google** [comment]
Sounds good to me! +1

**Comment by VirtualTim** [comment]
Pretty sure this should be closed.

**Comment by kripken** [comment]
Yes, thanks @VirtualTim - we landed 6.0.1 separately (and newer LLVM updates will happen on the wasm backend path, which we have 9.0.0svn on).
