### ISSUE TITLE
embind: Make working without RTTI

### ISSUE THREAD

**Issue by Armoken** [emscripten-core/emscripten#6551]
Hi, I am trying to use Embind in work project. But it works only in Debug mode. The main difference between Debug and Release is a optimization level (-O0 vs -O3) and RTTI, which disabled in Release. 
In Release mode I see the following exceptions:

> Error: Cannot access LeaderboardPlayer.id due to unbound types:

I tried to enable RTTI in Release, and Embind worked correctly in this case. Is it possible to make embind working without enabling RTTI?

**Comment by brion** [comment]
Can you provide a minimal test case and the compiler flags you're building with? I believe embind should work with `-fno-rtti` as long as you build with `-DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0` as well (you'd get a compile time error without it).

There may be something wrong in the dependent type resolution...

**Comment by wingo** [comment]
I can confirm that I had a problem building with `-fno-rtti` and that `-DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0` fixed it for me.  Test case here: https://github.com/wingo/pictie

**Comment by wingo** [comment]
I can confirm that I have the same problem as the original poster.  Simple standalone test case here: https://github.com/wingo/pictie

Build as: `em++ -Oz -fno-exceptions -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 --bind -s ENVIRONMENT=web -s WASM=1 -Wall -std=c++17 -o pictie.js pictie.cc pictie.bindings.cc`

**Comment by wingo** [comment]
Here's the first of three errors:

```
In file included from pictie.bindings.cc:1:
In file included from /home/wingo/src/emscripten-core/emscripten/system/include/emscripten/bind.h:21:
In file included from /home/wingo/src/emscripten-core/emscripten/system/include/emscripten/val.h:15:
/home/wingo/src/emscripten-core/emscripten/system/include/emscripten/wire.h:75:21: error: static_assert failed due to requirement '!std::is_polymorphic<Painter>::value' "Canonicalized<T>::type being polymorphic is illegal with RTTI disabled"
                    static_assert(!std::is_polymorphic<C>::value,
                    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wingo/src/emscripten-core/emscripten/system/include/emscripten/wire.h:105:40: note: in instantiation of member function 'emscripten::internal::LightTypeID<Painter>::get' requested here
                return LightTypeID<T>::get();
                                       ^
/home/wingo/src/emscripten-core/emscripten/system/include/emscripten/bind.h:1136:36: note: in instantiation of member function 'emscripten::internal::TypeID<Painter>::get' requested here
                TypeID<ClassType>::get(),
                                   ^
pictie.bindings.cc:67:3: note: in instantiation of member function 'emscripten::class_<Painter, emscripten::internal::NoBaseClass>::class_' requested here
  class_<Painter>("Painter")
  ^
```

**Comment by dnfield** [comment]
Here's an even smaller repro:

https://github.com/dnfield/emscripten_rtti/

If you uncomment https://github.com/dnfield/emscripten_rtti/blob/dc5be14133e8d046000c25801e3480868a03baa0/Makefile#L4 it will fail to build.

I'm not sure if there's a good way to fix this.  I'm interested in doing this for a class that I don't expect people to ever really `new` or extend in JavaScript - I'd basically like embind to just work with the concrete type that I'm specifying in the `MakePoly` function, so that I can easily swap it out based on other configurations in a real project.
