### ISSUE TITLE
emcc.py respects -xc but not -x c

### ISSUE THREAD

**Issue by ecuzzillo** [emscripten-core/emscripten#6553]
detect_fixed_language_mode in emcc.py is not respected by use_cxx at https://github.com/kripken/emscripten/blob/c3a988649cfac7535987531242a5ebda0520e3d8/emcc.py#L655

so -std=c++03 ends up getting passed together with -x c, which is an error

**Comment by kripken** [comment]
Thanks for filing!

Do you have a small concrete testcase showing the problem? That would avoid possible confusion and save time for anyone that wants to work on fixing the issue.
