### ISSUE TITLE
conftest.c special case is false positive / unclear

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#6561]
When run with a 'conftest.c' argument, emcc does additional processing.
For the following simple testcase it incorrectly fails:
```
echo 'char dlopen(); int main(void) { dlopen(); }' > conftest.c
echo 'char dlopen(); int main(void) { dlopen(); }' > conftest2.c
```

```
$ emcc -o conftest   -m32 conftest2.c -ldl; echo $?
0

$ emcc -o conftest   -m32 conftest.c -ldl 
warning: unexpected number of arguments 0 in call to 'dlopen', should be 1
error: unresolved symbol: $FS
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
  File "/home/me/workdir/emsource/emscripten/emcc.py", line 2902, in <module>
    sys.exit(run())
  File "/home/me/workdir/emsource/emscripten/emcc.py", line 1669, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/me/workdir/emsource/emscripten/tools/shared.py", line 2030, in emscripten
    emscripten._main(cmdline)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 2353, in _main
    temp_files.run_and_clean(lambda: main(
  File "/home/me/workdir/emsource/emscripten/tools/tempfiles.py", line 93, in run_and_clean
    return func()
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 2358, in <lambda>
    DEBUG=DEBUG,
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 2266, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 95, in emscript
    glue, forwarded_data = compiler_glue(metadata, settings, libraries, compiler_engine, temp_files, DEBUG)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 227, in compiler_glue
    glue, forwarded_data = compile_settings(compiler_engine, settings, libraries, temp_files)
  File "/home/me/workdir/emsource/emscripten/emscripten.py", line 542, in compile_settings
    cwd=path_from_root('src'), error_limit=300)
  File "/home/me/workdir/emsource/emscripten/tools/jsrun.py", line 132, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['nodejs', '/home/me/workdir/emsource/emscripten/src/compiler.js', '/tmp/tmpoaYQGE.txt', '/home/me/workdir/emsource/emscripten/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..generated code.. }
// 3. pre-run appended it, var Module = {}; ..generated 
```
This is typically what can be found in a config.log.

The cause of the error is hard to understand since it output the start of a JS compiler result, rather than its stderr, plus the temporary .txt file is removed immediately.

Fiddling with jsrun.py, stderr appears to be `Aborting compilation due to previous errors | undefined` which is also unclear.

In this particular case, as far as I understand "dlopen" is explicitely blacklisted?
The same test works fine with "dlsym".

I'm not sure what the special case for "conftest.c" is supposed to do.
As I could use dlopen() manually with emscripten, I would expect the result to be positive though.

**Comment by kripken** [comment]
Something seems odd here, yeah. In general, when running `configure` we want to handle things a little differently, so `emconfigure` should set an env var, and then if set and we see a file called `conftest.c` then we special-case that. But it sounds like you're seeing special behavior without `emconfigure`?

**Comment by Beuc** [comment]
OMG using an environment variable is sneaky (I suppose it's EMMAKEN_JUST_CONFIGURE)! Perharps it would be worth mentionning it in the output, though I should have thought about trying to reproduce a failing conftest with emconfigure as well.

In any case, yes, I got the initial post's output _without_ emconfigure.
When using emconfigure, I get the error in both conftest.c and conftest2.c.
So I guess that behavior is triggered with the environment variable OR if the filename is conftest.c.

**Comment by kripken** [comment]
Thanks @Beuc , yeah, in that case it does sound like a bug here, that we should look into.
