### ISSUE TITLE
[Feature request] Make `locateFile` async

### ISSUE THREAD

**Issue by surma** [emscripten-core/emscripten#6564]
I have encountered some cases where it would be desirable to hook up `locateFile` to an async process. 

In an ideal world, `locateFile` would accept strings, [`ArrayBuffers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), [`Blobs`](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and [`Responses`](https://developer.mozilla.org/en-US/docs/Web/API/Response), both synchronously (for backwards-compatibility) and asynchronously.

This way it could be easily integrated with `fetch()`, `CacheAPI`, `IndexDB` and other means of storage while still working in the current way if a string is returned synchronously.

**Comment by kripken** [comment]
I think you're suggesting a wider use case than `locateFile` is intended for - it's basically just a simple way to say where to find file paths at runtime (mapping paths to corrected paths). Perhaps something like what you suggest is more of a new feature? (Or maybe I don't understand the proposal.)

**Comment by surma** [comment]
Yes, this is very much a feature request and my proposal is indeed to widen the use-case of `locateFile`. 

As you say, `locateFile` is currently a simple path remapping function. To make it much more versatile and ergonomic, a great first step would be to allow it to be asynchronous. This way it could return a _promise_ that resolves to the new URL. This would allow developers to consult the ServiceWorker, IndexDB and similar APIs to generate the new URL. In combination with Blob URLs, this would technically allow all use-cases I outlined above.

As a second step, we could consider talking about also allowing to resolve to ArrayBuffers or Blobs directly.

**Comment by curiousdannii** [comment]
Hmm, I don't see much of an advantage expanding it in that way. If the file can't be easily located then it probably can't be easily loaded either, so you'd have two async functions. Instead you could overwrite the loading code to locate the file in its nonstandard location as well.

**Comment by surma** [comment]
What do you mean by “overwrite the loading code”? If there is a hook to do that, than this can be closed. I just want to be able to load a wasm module from the IndexDB/Cache API.

**Comment by curiousdannii** [comment]
You can just set `Module['wasmBinary']` to the buffer.

http://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#wasm-files-and-compilation

**Comment by surma** [comment]
Hm, not what I was hoping for. Is this appropriate to add to https://kripken.github.io/emscripten-site/docs/api_reference/module.html ?
