### ISSUE TITLE
Minimal wasm with certain system library methods

### ISSUE THREAD

**Issue by chrjohnson** [emscripten-core/emscripten#6569]
I would like to have Emscripten build a wasm file with just my functions plus just the standard library methods that I ask for (malloc, free). It’s alright if it builds a JS file but I would like to be able to ignore that file and handle all the javascript myself like in the MDN articles like this: https://developer.mozilla.org/en-US/docs/WebAssembly/Loading_and_running

SIDE_MODULE almost meets my needs. it’s almost just my methods (other than things like__post_instantiate, runPostSets, some globals, etc) and there is no js file created. I can do the javascript myself but I can’t seem to find a way to get it to include things like malloc.

SIDE_MODULE is for use with MAIN_MODULE and the main module is the one expected to have the system libraries so this makes sense not being able to include them in the side_module build.

I’ve tried using ONLY_MY_CODE with -O1 and that gets me even closer than SIDE_MODULE does because it doesn’t have the methods like __post_instantiate and runPostSets but I still can’t seem to get it to include portions of the standard library like malloc.

Is there a flag that I’m missing or is it simply not possible to have just my methods in the wasm, no js file (or at least one that I can ignore), and just specific standard library methods like malloc and free?

**Comment by kripken** [comment]
You can include malloc in `SIDE_MODULE` by including it manually: add `dlmalloc.c` (under the `system/` dir) to the list of files you are compiling. Then malloc is just more code that you are compiling, no different from the code you wrote yourself.

Another option is to rely on metadce to remove the runtime, see https://github.com/kripken/emscripten/wiki/WebAssembly-Standalone#let-the-optimizer-remove-the-runtime . Whether that does what you want or not depends on the input files and whether the system libraries you link to require JS or not. But it would include malloc for you automatically (unless it can see malloc is never used anywhere, and it optimizes it out).

**Comment by chrjohnson** [comment]
Looking at the .wast file and including dlmalloc.c gives the exports for _free and _malloc (exactly what I'm looking for)

It expects imports for `___errno_location` and `_sbrk`. I'm not sure what to set for these. Am I missing a file perhaps?

**Comment by kripken** [comment]
Those arrive from JS library support, I belive, see library.js. They are not included in a side module though, since we don't link in system libraries there.
