### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by xtuc** [emscripten-core/emscripten#6571]
With the new wasm pipeline in Webpack (> 4.8.0), loader can now directly emit a wasm binary. 

I have a very simple demo here: https://github.com/xtuc/c-webpack-demo.

The idea would be to allow:

```js
  module: {
    rules: [
      {
        test: /\.c$/,
        loader: "emscripten/loader",
        type: "webassembly/experimental"
      }
    ]
  },
```

and the user would just:

```js
import("./foo.c").then(...)
```

**Comment by kripken** [comment]
Nice!

Is there anything in emscripten we need to do to support this? Or does it all work already?

**Comment by xtuc** [comment]
FYI I started experimenting here: https://github.com/xtuc/emscripten-loader-test/blob/master/loader.js.

Some thoughts:
- It's simpler to "finalize/link" the binary in a loader instead of adding more logic in emscripten.
- I'm trying to instantiate the wasm binary directly and using the loader for the dependencies

**Comment by Dwood15** [comment]
@xtuc Your PR was accepted for webpack. Is there anything remaining to be done on the emscripten side of things?

**Comment by xtuc** [comment]
@Dwood15 (when I have time) I'm still experimenting with the loader.

**Comment by Dwood15** [comment]
I found your loader repo, I'll follow along as it develops. :)

**Comment by xtuc** [comment]
The loader is extremely hacky but usable now. Please let me know if you have any though on it.

**Comment by xtuc** [comment]
I suppose @surma already knows. 

FYI the repo is now here https://github.com/wasm-tool/emscripten. It's experimental.
