### ISSUE TITLE
Suggestions for mouse capture issues?

### ISSUE THREAD

**Issue by greggman** [emscripten-core/emscripten#6585]
I'm doing some Dear ImGUI stuff and at the moment there's issues with sticky mouse button issues related to mouse capture.

Example: 

![screenflow](https://user-images.githubusercontent.com/234804/40540546-8576477e-6053-11e8-8358-5c8a3ee2c6bf.gif)

Has any thought been given on how to deal with this? Should emscripten deal with this in any way or should it be handled at some other level?

I can go try to add mouse capture support into library_glfw (if that's the appropriate place) but I thought I should ask first to see if anyone has given this any thought or if I'm going in the wrong direction

**Comment by greggman** [comment]
Sorry, not pointerlock. "Mouse capture" is getting mouse events even when the mouse goes outside the current element and or the app's window. It's needed when you mousedown inside your emscripten canvas/window and while dragging take the mouse outside the canvas/window (without releasing the button) and then release the button outside the window.  Without mouse capture the app never gets the mouseup event and so when the user moves the mouse back into the window stuff is stuck to the mouse pointer because the app never saw a mouseup event.

**Comment by kripken** [comment]
Thanks, I think I noticed that in the past but never knew what it was called ;)

Not sure what best practices are for it.

But in general, adding code to the more central library_browser.js (that is then used by the different APIs) might be better, if possible.
