### ISSUE TITLE
Cut/Copy/Paste Ctrl-V vs Cmd-V etc

### ISSUE THREAD

**Issue by greggman** [emscripten-core/emscripten#6594]
In porting some native apps they might target different keys for different platforms. Of course as native apps they expect to be compiled on that platform but then when running in emscripten that platform changes at runtime not compile time.

So, the app might say 

```
#if MAC
   if (key === KEY_C and mod &= MOD_COMMAND) {
#else 
   if (key === KEY_C and mod &= MOD_CTRL) {
#endif
       copyToClipboard();
    }
```

Unfortunately that of course doesn't work with emscripten. Should emscripten (or various libraries like library_glfw.js) try to handle this in some way or is this really something where the app needs to be modified? For example if apps end up assuming Ctrl-C is their platform then maybe an option to have emscripten (or one of the various libraries) do translation of Cmd-C to Ctrl-C or maybe some kind of use callback in the library that can be added at a javascript level?

As an example for Dear ImGUI I can maybe handle this in C++ by overriding the keyboard callback from glfw and doing my own conversions. I don't think there are any easy solutions really I just thought I'd ask if anyone has any ideas.

Paste has issues that AFAICT in the browser the only way to read the clipboard is during a "paste" event whereas native apps expect to just be able to read it at anytime. That generally means if we want emulation we probably have to filter out `Ctrl-V` and `Cmd-V`,  add a listener to the `paste` event, when the paste event arrives get the clipboard data, save it and then synthesize fake key events so the C++ code will then read our copy of the clipboard?

**Comment by bdenhollander** [comment]
@greggman I've come across a similar scenario where Windows Ctrl shortcuts would ideally use Cmd on Mac. Did you come up with an elegant solution to this?
