### ISSUE TITLE
emcmake find_package not working for own libraries

### ISSUE THREAD

**Issue by Pfeifenjoy** [emscripten-core/emscripten#6595]
I hope this is the correct place to ask this question.

I have a library Foo which I install and a program Bar which requires this library.

In my library foo I create a FooConfig:
`
include("${CMAKE_CURRENT_LIST_DIR}/FooTargets.cmake")
`

Which imports the targets I generated in my CMakeLists.txt.

```
install(TARGETS Foo EXPORT FooTargets
	ARCHIVE DESTINATION lib
	LIBRARY DESTINATION lib
	RUNTIME DESTINATION bin
	INCLUDES DESTINATION include
)
install(DIRECTORY include/foo DESTINATION include)

install(EXPORT FooTargets
	FILE FooTargets.cmake
	NAMESPACE Foo::
	DESTINATION lib/cmake/Foo
)

include(CMakePackageConfigHelpers)
write_basic_package_version_file("FooConfigVersion.cmake"
	VERSION ${Foo_VERSION}
	COMPATIBILITY SameMajorVersion
)

install(FILES
	"FooConfig.cmake"
	"${CMAKE_CURRENT_BINARY_DIR}/FooConfigVersion.cmake"
	DESTINATION lib/cmake/Foo
)
```

When I use simply cmake, I can run `find_package(Foo REQUIRED)` in the CMakeLists.txt of Bar,
and the library will be imported.

This however does not work if I run `emcmake cmake ..`. I get the following error message:

```
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindFoo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Foo", but
  CMake did not find one.

  Could not find a package configuration file provided by "Foo" with any of
  the following names:

    FooConfig.cmake
    foo-config.cmake

  Add the installation prefix of "Foo" to CMAKE_PREFIX_PATH or set
  "Foo_DIR" to a directory containing one of the above files.  If "Foo"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by Pfeifenjoy** [comment]
Maybe some information on where I got stuck.

It works to search for some libraries like OpenGL and tools like Bison.
This makes sense because obviously you cannot use all system libraries.
And honestly if I compile something with gcc and install it globally to my
system it is reasonable that the library should not be found.
Because everything is installed globally it is very hard to identify libraries which are compiled with emcc.
In my usecase however I install the libraries into a separate directory called dependencies
via setting the CMAKE_PREFIX_PATH variable.
This allows me to locally install the library without interference with any other system library.

Thus I tried to add support for local directories:
As far as I can tell emcmake uses the cross compilation feature of cmake.

The file specifying the compilation process is `/usr/local/Cellar/emscripten/1.38.0/libexec/cmake/Modules/Platform/Emscripten.cmake`
on my mac.

Sadly I don't have the expertise to modify this file.

**Comment by tw-git** [comment]
@Pfeifenjoy Did you find a solution?

**Comment by nowakowsk** [comment]
It's as if `CMAKE_PREFIX_PATH` is ignored entirely, at least on Windows. A workaround is to set paths to installation directories manually (`-D<library_name>_DIR=...`).

However, this is not how CMake should behave. It really should be fixed.

**Comment by sarkahn** [comment]
Just hit this issue - I use vcpkg to manage all my libraries in windows and vcpkg uses CMAKE_PREFIX_PATH for package discovery. Effectively this makes it impossible to use emscripten with cmake on windows (without the extremely annoying workaround mentioned above), unless I'm missing something.

**Comment by lwyj123** [comment]
So What's the solution?

**Comment by ali1234** [comment]
The reason why this does not work is explained here: https://github.com/emscripten-core/emscripten/issues/10078#issuecomment-580260069

So in order to work around this problem with `-D<library_name>_DIR=...` you MUST provide an absolute path.

**Comment by lwyj123** [comment]
@ali1234 I don't understand why the behavior between cmake and emcmake is different. And It makes development in different computer sucks if I need to provide an absolute path. Also bad for migration.

**Comment by ali1234** [comment]
I agree.

**Comment by sbc100** [comment]
@Pfeifenjoy, I've been working on cmake fixes and I think I might have fixed this issue, but I'm having trouble building a repro case (one that works on desktop and fails with current emscripten).   Any chance you could post a full example?   I'm assuming that you are doing doing any of `make install` step here?  Its just a project nested within another project?

**Comment by sbc100** [comment]
See https://github.com/emscripten-core/emscripten/pull/14291 for my WIP PR that I think will fix this.

**Comment by AHaliq** [comment]
I'm still having the same issue, i'm using emsdk `2.0.25` and I have to manually specify the `-DBoost_INCLUDE_DIR=...`.

However even after getting all boost dirs im getting
```
  Could NOT find Boost (missing: system) (found version "1.77.0")
```
I can't find a workaround for that either.

**Comment by roysc** [comment]
A workaround I'm using: pass `CMAKE_FIND_ROOT_PATH_BOTH` to `find_package` to override Emscripten's setting (i.e. use the normal search order, respecting `CMAKE_PREFIX_PATH`).
