### ISSUE TITLE
linking module flags 'wchar_size': IDs have conflicting values

### ISSUE THREAD

**Issue by GregSlazinski** [emscripten-core/emscripten#6599]
I have my game engine:
http://www.esenthel.com/
With a small WebGL Emscripten demo:
http://www.esenthel.com/?id=live_demo

Since I've updated to Emscripten 1.38.3
I am getting the error 
`linking module flags 'wchar_size': IDs have conflicting values`

I build the engine and the demo with `-fshort-wchar`
The entire engine assumes that wchar_t size is 2, for performance and memory usage.

This was working fine with Emscripten 1.37.21 (version number from my memory)
But now on 1.38.3 it doesn't work anymore.

I have seen this already:
https://github.com/kripken/emscripten/issues/6336
And even though it's a closed issue, it doesn't provide any clear explanation (step by step) how to solve this.
This involves manually performing some changes in the Emscripten repository files?
However the engine is not only for me, I have some users, that use the engine + Emscripten combined together.
It would be a big pain asking the users to perform some changes manually by themself in the Emscripten.
Since it was working fine with Emscripten 1.37.21 then can you revert any Emscripten changes that broke the -fshort-wchar support?

I don't see any point in having 32-bit chars, while 16-bit is perfectly enough to support most common used characters, such as Chinese Japanese Korean and others.
Perhaps you could change the default Emscripten setting to use 16-bit.
Or alternatively you could change Emscripten to cache/pre-build the system libraries based on the currently being compiled project. Example if compiled project uses -fshort-wchar then Emscripten should use system libraries with that flag too, if the last precompiled system library doesn't, then it could be recompiled on the fly? Or two system libraries could be always compiled (cached) and the requested one would be used depending on the application project.

**Comment by kripken** [comment]
I don't think we've done any changes to `wchar`, so the likely cause of the change is an upstream LLVM or clang update.

It would be useful to bisect this to find out which version (or better, which commit) causes the problem for you. (If that's not easy for you, if you can create a testcase that shows the issue i could bisect.)

**Comment by trippleflux** [comment]
@kripken 
Any news on these?
@GregSlazinski 
I am also esenthel source user :-(

**Comment by trippleflux** [comment]
@kripken
Just a heads up, this issue is exist with 1.37.40, so probably there are something changes between 1.37.21 and 1.37.40/1.38.3?

**Comment by kripken** [comment]
@trippleflux bisection makes it a lot faster: instead of checking each version from 21 to 40, you check 30, then if it works you look into the range 31-40, if not then the range 21-29. Basically, the same as binary search (so it's in logarithmic time).

Another option as I mentioned above is if you can make me a small testcase I can easily run myself, I could do the bisection for you

**Comment by GregSlazinski** [comment]
Hi,

Thanks for your replies.

I get this error by modifying the `Emscripten\emscripten\1.38.3\tests\hello_world.cpp`
into:
```
#include <stdio.h>

class Test {}; // This will fail in C mode

int main() {
  static_assert(sizeof(wchar_t)==2, "wchar size should be 2");
  printf("hello, world!\n");
  return 0;
}
```

and then compiling it as:
`emcc hello_world.cpp -o hello.html -fshort-wchar`
with the result:
`error: linking module flags 'wchar_size': IDs have conflicting values`

I'm guessing that it's not an Emscripten change, but rather Clang change? previously it ignored checking the status of wchar_t size when linking, but now it does the checks and returns an error when multiple wchar sizes are detected.
And as someone mentioned here:
https://github.com/kripken/emscripten/issues/6336#issuecomment-378352650

> This happens because the existing cached prebuilt library (in ~/.emscripten_cache) was not built with the same flag, so the cached library asserts the size of wchat_t to be 4. This is not gonna work unless you build your own library with the same flag.

So the solution would be to add -fshort-wchar support to the Emscripten toolchain.

-fshort-wchar works fine on:

- Linux Desktop GCC
- Linux Desktop Clang
- Apple Mac+iOS Clang

Only Emscripten fails.

Reasons why -fshort-wchar should be supported:
-it uses 2x less memory
-it is faster, doing string operations requires to process 2x less bytes
-it is binary compatible with Windows
-it is completely enough to support all the language characters, Chinese Japanese Korean, etc.
-it is natively supported on Linux GCC/Clang, Apple and so should be in Emscripten

Thank you

**Comment by trippleflux** [comment]
Could it be [this ](https://reviews.llvm.org/D32982)un-applied patch is related?

**Comment by trippleflux** [comment]
@kripken 
About the EMCC_FLAGS env var, does adding -Xclang -fwchar-type=short means passing -fwchar-type=short into clang cflags?. Because adding -Xclang -fwchar-type=short and rebuilding all esenthel dependencies & engine  resulting the same error as above.

So you seem to be correct it's from upstream, the list below is from the embuilder.py : 
```
        libc
        libc-mt
        struct_info
        emmalloc
        emmalloc_debug
        dlmalloc
        dlmalloc_debug
        dlmalloc_threadsafe
        dlmalloc_threadsafe_debug
        pthreads
        libcxx
        libcxx_noexcept
        libcxxabi
        native_optimizer
        binaryen
        wasm-libc
        wasm_compiler_rt
```
Above list seem needs to be recompiled with EMCC_FLAGS=-Xclang -fwchar-type=short ?, but i am stuck with recompiling libc.bc cache with this error below : 

```
INFO:root:generating system library: libc.bc... (this will be cached in "C:\Users\echelon\.emscripten_cache\asmjs\libc.bc" for subsequent builds)
C:\Users\echelon\Documents\Tools\emsdk\emscripten\1.38.4\system\lib\libc\musl\src\ctype\wcwidth.c:26:9: error: result of
      comparison of constant 917505 with expression of type 'wchar_t' (aka 'short') is always false
      [-Werror,-Wtautological-constant-out-of-range-compare]
        if (wc == 0xe0001 || wc-0xe0020U < 0x5f || wc-0xe0100 < 0xef)
            ~~ ^  ~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

**Comment by trippleflux** [comment]
@kripken 
Here is the possible test case for linking module flags 'wchar_size': IDs have conflicting values, project attached should be outputting 2 bytes as wchar_t size, instead it causing linking error.
[wchar_test.zip](https://github.com/kripken/emscripten/files/2066164/wchar_test.zip)

**Comment by trippleflux** [comment]
@kripken 
I have been waiting for your reply, expertise, and skills, hmm modifying the C_OPTS into 
```
  C_OPTS = ['-Xclang', '-fwchar-type=short', '-nostdinc', '-Xclang', '-nobuiltininc', '-Xclang', '-nostdsysteminc']
```
And : 
```
  C_OPTS = ['-fshort-wchar', '-nostdinc', '-Xclang', '-nobuiltininc', '-Xclang', '-nostdsysteminc']
```

Also facing musl errors like my reply above : 
```
INFO:root:generating system library: libc.bc... (this will be cached in "C:\Users\echelon\.emscripten_cache\asmjs\libc.bc" for subsequent builds)
C:\Users\echelon\Documents\Tools\emsdk\emscripten\tag-1.38.4\system\lib\libc\musl\src\ctype\wcwidth.c:26:9: error:
      result of comparison of constant 917505 with expression of type 'wchar_t' (aka 'short') is always false
      [-Werror,-Wtautological-constant-out-of-range-compare]
        if (wc == 0xe0001 || wc-0xe0020U < 0x5f || wc-0xe0100 < 0xef)
            ~~ ^  ~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```
As below i have had preparing the sample test case for linux/bash.
[wchar_test_linux.zip](https://github.com/kripken/emscripten/files/2069608/wchar_test_linux.zip)

**Comment by GregSlazinski** [comment]
Please also see my previous post:
https://github.com/kripken/emscripten/issues/6599#issuecomment-393702731

It includes a sample test case, I quote:

> I get this error by modifying the `Emscripten\emscripten\1.38.3\tests\hello_world.cpp`
> into:
> ```
> #include <stdio.h>
> 
> class Test {}; // This will fail in C mode
> 
> int main() {
>   static_assert(sizeof(wchar_t)==2, "wchar size should be 2");
>   printf("hello, world!\n");
>   return 0;
> }
> ```
> 
> and then compiling it as:
> `emcc hello_world.cpp -o hello.html -fshort-wchar`
> with the result:
> `error: linking module flags 'wchar_size': IDs have conflicting values`


Would be great if Emscripten could support that out-of-the-box.

**Comment by kripken** [comment]
Thanks for the info @trippleflux and @GregSlazinski.

That error message suggests to me that musl is not compatible with `-fshort-wchar`. That does seem to the be the case, for example see http://openwall.com/lists/musl/2015/02/18/4

It's interesting that this worked before - I suspect it was fragile and you were just lucky to not hit the problems?

Overall I am pessimistic that proper `-fshort-wchar` support is possible with musl, and porting another libc would be a lot of work. However, if it worked well enough for you before, it's possible some hacking could make it work similarly now too I suppose, if you're interested to explore that. Maybe just working around that compiler error on `system\lib\libc\musl\src\ctype\wcwidth.c:26:9` gets it to compile?
