### ISSUE TITLE
Still some color with -fno-diagnostics-color and -fdiagnostics-color=never

### ISSUE THREAD

**Issue by promi** [emscripten-core/emscripten#6650]
There seem to be no documented way to turn of color output of emcc, in clang or gcc you can just do:

-fno-diagnostics-color

or

-fdiagnostics-color=never

emcc accepts these options but still does some colorization with ANSI escape codes.

I'm using emacs as my editor and when compiling I get output like:

`ERROR:root:[31mcompiler frontend failed to generate LLVM bitcode, halting[0m`

**Comment by kripken** [comment]
To fix this, we need to process that flag in `emcc.py`, and it should affect how `tools/colored_logger.py` works.
