### ISSUE TITLE
Angular 6 doesn't inject fs anymore

### ISSUE THREAD

**Issue by Rlcolli4** [emscripten-core/emscripten#6653]
[Reference bug #10681](https://github.com/angular/angular-cli/issues/10681)

After converting from c++ to wasm, the code it is converted to (at least with angular) requires an `import * from 'fs'` which no longer works in Angular 6. I came across this when trying upgrade our application to angular 6 and one of the node modules we use ([this discussion](https://github.com/xaviergonz/js-angusj-clipper/issues/2)) uses your code to help compile some of his script. I don't know if angular plans to fix that issue in their CLI but I thought I would also bring up the problem here as this prevents us from upgrading the Angular 6.

**Comment by curiousdannii** [comment]
So is one of your build steps converting the CommonJS `require` statements into ES6 `import` statements? Emscripten really needs conditional importing if it is in the default cross-platform mode.

One thing you could try is to compile with `-s ENVIRONMENT="web"`. All `require` statements should then be removed from the output.

Documented at: http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#miscellaneous-code-size-tips

**Comment by xaviergonz** [comment]
Ah, I just found it
```
var ENVIRONMENT_IS_WEB = {{{ ENVIRONMENT === 'web' }}};
var ENVIRONMENT_IS_WORKER = {{{ ENVIRONMENT === 'worker' }}};
var ENVIRONMENT_IS_NODE = {{{ ENVIRONMENT === 'node' }}};
var ENVIRONMENT_IS_SHELL = {{{ ENVIRONMENT === 'shell' }}};
```

**Comment by Rlcolli4** [comment]
Any update on the status of this issue?

**Comment by Rlcolli4** [comment]
Should this be closed now that the label is “won’t fix”?
