### ISSUE TITLE
Switch to an event emitter interface

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#6659]
The Emscripten code currently handles events in several ways:

 - The `callRuntimeCallbacks` system for five sets of events
 - The `addRunDependency` system
 - The barely used `abortDecorators` system
 - The single `onX` properties

It should be possible to unify these under a single event emitter interface, either modelled on the DOM's EventTarget interface, or Node's EventEmitter. (It wouldn't need to be as full featured as either, depending on what exactly we need.) In addition to cleaning up what looks like quite a few redundancies here, it would also mean that all the single `onX` properties would be upgraded to proper event emitters allowing multiple handlers. (We already have to work around that for [`onRuntimeInitialized`](https://github.com/kripken/emscripten/blob/incoming/src/postamble.js#L137).)

An alternative would be to use promises for all of these, attaching handlers through `then`. Aside from it switching from synchronous calling to asynchronous, I'm not sure what the implications would be. Probably best to just do event emitters unless someone can think of really good reasons to use promises for these systems.

**Comment by kripken** [comment]
Agreed, we really should unify and modernize these. Should also make the code smaller, too.
