### ISSUE TITLE
OpenAL Support

### ISSUE THREAD

**Issue by fungos** [emscripten-core/emscripten#666]
Is there an OpenAL implementation?

What about wrapping WebAL ? https://github.com/benvanik/WebAL

Also, right now how do you play sounds/music with emscripten?

**Comment by macramole** [comment]
Hi, I'm searching the web for open source projects using emscripten and openal for sound, I'm not being very lucky though, can you point me in any direction ?

I'm interested in learning how to plug those two together for contributing with an open source game engine called Godot.

Thanks !

**Comment by juj** [comment]
Emscripten supports OpenAL out of the box without any special linking flags or similar. Not all features are available though (contributions to implement more are welcome) Try searching the `tests/` directory for example code that uses OpenAL, or some other OpenAL using samples on the net.

**Comment by macramole** [comment]
Nice. Thanks for your help !
