### ISSUE TITLE
Emconfigure pkg-config dependencies unresolved

### ISSUE THREAD

**Issue by Samsy** [emscripten-core/emscripten#6664]
I'm tying to compile a project with a CMakeList and pkg-config tool
Problem : dependencies using pkg-config are unresolved
'pkg-config --list-al' => all the dependencies listed
'emconfigure pkg-config --list-all' => All my dependencies are missing

Cannot find a documentation concerning pkg-config usage using emconfigure

Am I missing something ? Or is it an issue ?

**Comment by rjy7wb** [comment]
I am having this problem too, has someone that has experienced this issue or knows what to do point us in the right direction?

**Comment by tamusjroyce** [comment]
It is a sandbox... I can't find documentation how to import emscripten ports so pkg-config will find them. Or to compile libraries using emscripten and deploy them where emconfigure pkg-config can find them.

**Comment by brion** [comment]
The emscripten ports don't actually 'install' a library in a way that pkg-config will recognize (they create a `.bc` bitcode library in-place in the source checkout), so you may need to manually build the library and `make install` it into a local prefix to get the `.pc` files installed.

You'll then have to manually set `PKG_CONFIG_PATH` in the environment; with autoconf-like builds you can do that something like this (from a build script in my ogv.js project):

```
emconfigure ../../../libskeleton/configure \
	--prefix="$dir/build/js/root" \
	PKG_CONFIG_PATH="$dir/build/js/root/lib/pkgconfig" \
	--disable-shared
```

The main thing to remember is that `PKG_CONFIG_PATH` should point into the `lib/pkgconfig` subdir under the installation prefix you put the libraries in, not just the root of the prefix.

See [compileOggJs.sh](https://github.com/brion/ogv.js/blob/master/buildscripts/compileOggJs.sh) and [compileSkeletonJs.sh](https://github.com/brion/ogv.js/blob/master/buildscripts/compileSkeletonJs.sh) from the ogv.js build scripts for examples of installing a library and then of using it with the set path.

Hopefully that helps!

Probably the ports could be extended to create a suitable `.pc` file and set `PKG_CONFIG_PATH` in `emmake` and `emconfigure`... this could even specify the `-s USE_BLAH` special params that `emcc` uses in place of manual linking/include path setup.

If folks think that would be useful, I might look into a patch for that later.

**Comment by tamusjroyce** [comment]
Those examples are very helpful. Maybe it be added to https://emscripten.org/docs/getting_started/Tutorial.html? But as long as there is an example, that suffices for me! Thank you!
