### ISSUE TITLE
CMake calling itself recursivly and infinitly

### ISSUE THREAD

**Issue by etienne02** [emscripten-core/emscripten#6675]
Hi,
I'm i on the latest version of emscripten (incoming) and when I try to compile something, the process call ```python em++ ... -g -O2 CMakeCXXCompilerId.cpp``` which call ```cmake -DCMAKE_BUILD_TYPE=Release . ``` which call ```python em++ ... -g O2 CMakeCXXCompilerId.cpp``` which call ```cmake -DCMAKE_BUILD_TYPE``` and this infinitly until I kill the process or my pc frezze.

**Comment by kripken** [comment]
Doesn't sound like a known bug. Did this regress? If so it would be good to bisect to find out when the problem started.
