### ISSUE TITLE
Large strings corrupted after conversion via cwrap 

### ISSUE THREAD

**Issue by griffin2000** [emscripten-core/emscripten#6683]
If I pass a large (over 1mb) string into  a C function via Cwrap the resulting memory is corrupted ( possibly overflowing a temp buffer provided by the Cwrap wrapper code?). 

I have compiled the _bar_ function below (using emcc with the WASM flag enabled), that creates a std::string from the input char* parameter and then checks for invalid (non-ASCII) characters. 

```
extern "C" EMSCRIPTEN_KEEPALIVE int bar(const char* xml)
{
			
		int len = strlen(xml);
		printf("\nOriginal string\n");
		int originalStringInvalidChars = FindInvalidChars(xml, len);
		printf("Original string found %d invalid chars\n",originalStringInvalidChars);

		
		printf("\nConverted string\n");
		string *inputStr=new string(xml,len);	
		int convertedStringInvalidChars = FindInvalidChars(inputStr->c_str(), len);
		printf("Converted std::string found %d invalid chars\n",convertedStringInvalidChars);

		return (convertedStringInvalidChars || originalStringInvalidChars)

}

```

In Javascript I can allocate a 1.5Mb string of A's via Module._malloc and pass directly to Module._bar and it works fine, finding no invalid chars.  But if I create the same string as a Javascript string call via cwrap then I either get invalid characters found or a _RuntimeError: memory access out of bounds_ exception:
```

		const len =1500000;
		var str = new Array(len + 1).join( 'A' );

		const bar = Module.cwrap("bar", "number", ["string"]);
		const res0 = bar(str);
		console.log("All chars valid calling via cwrap:"+res0);

		var strPointer = Module._malloc(len+1);	
		const strArray = new Uint8Array(Module.HEAPU8.buffer, strPointer, len);
		
		for(let i=0;i<len;i++){
			strArray[i]=str[i];
		}
		
		const res1=Module._bar(strPointer);
		console.log("All chars valid calling direcly:"+res1);

```

I don't believe it is running out of memory (TOTAL_MEMORY is 60mb). Is there an internal buffer that is used by Cwrap to convert strings, that is overflowing? Is it possible to change the size of that buffer (or detect overflows?)

I've attached a testcase below (including full emcc command line).

emcc version information:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.37
clang version 5.0.0  (emscripten 1.37.37 : 1.37.37)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/gareth/OpenBabelWeb/emsdk/clang/e1.37.37_64bit
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```
I am testing the resulting code in Windows on Chrome Version 66.0.3359.181 

[foo.zip](https://github.com/kripken/emscripten/files/2096106/foo.zip)

**Comment by kripken** [comment]
I believe ccall/cwrap store copies on the stack, which might be related, see the first note here: https://kripken.github.io/emscripten-site/docs/api_reference/preamble.js.html#calling-compiled-c-functions-from-javascript

However, 1.5MB should fit on the default stack size (5MB). Also, when assertions are on, we should check for overflows. So unless you set a smaller stack + only checked when assertions are disabled, the fact it's on the stack might not matter, and something else might be the issue.
