### ISSUE TITLE
emscripten_GetProcAddress doesn't have webgl2 functions

### ISSUE THREAD

**Issue by arturoc** [emscripten-core/emscripten#6685]
It seems functions that are new to webgl 2 / opengl es 3 are not present in the index of functions in gl.c

**Comment by kripken** [comment]
Yes, functions need to be added there manually.

It's pretty easy to do it, the relevant file is `system/lib/gl.c
`, and you can look at recent commits adding stuff to there with `git log system/lib/gl.c`

**Comment by arturoc** [comment]
yeah i've seen that file but thought it was autogenerated. i tried to manually add glGenSamplers and glSamplerParameter* but when using them later glSamplerParameter* complains that the sampler passed as parameter is not an object as if it wasn't being inserted in the object index by glGenSamplers.

The weird thing is that glGenSamplers seems to work fine without including it in gl.c, any idea why that would happen?

**Comment by kripken** [comment]
`gl.c` only provides the support for using GetProcAddress type methods to get the function (so you can just call things directly and they work, if you don't try to use GetProcAddress). But the implementations are in `library_gl.js`, and it's possible there is a bug in those, from what you are saying. If you can make a testcase that would be helpful to debug it.

**Comment by arturoc** [comment]
yes the thing is if I import those symbols as extern "C" instead of loading them with GetProcAdress then it works. If i try to load them using GetProcAdress, after adding them to gl.c then i get the message above. It might be that the way i'm loading those functions is somehow calling glGenSamplers as an external symbol from library_gl.js and glSamplerParameter* as a function pointer loaded at run time from gl.c

I'll try to look into it and let you know

this is using rust gl-generator + emscripten btw, in case it gives you any clue
