### ISSUE TITLE
Unable to use system calls

### ISSUE THREAD

**Issue by nepx** [emscripten-core/emscripten#6708]
I am trying to leverage system calls in Emscripten. Here's `syscall.c`, a small test I wrote:

```c
#define _GNU_SOURCE
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <signal.h>

int main(int argc, char *argv[]) {
    syscall(SYS_close, -1);
    syscall(SYS_exit, 15);
}
```

And got the following when I compiled with Emscripten:

```
$ emcc syscall.c -o syscall.html
syscall.c:10:12: error: implicit declaration of function 'syscall' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
           syscall(SYS_close, -1);
           ^
```

However, the same program compiles on GCC and Clang. 

I know that Emscripten supports system calls ([library_syscall.js](https://github.com/kripken/emscripten/blob/incoming/src/library_syscall.js)), but they seem to be hidden from the user, or at least inaccessible. 

Are there any flags that enable this or any defines I need to use? I tried adding `#include <emscripten.h>` but that doesn't work either.

**Comment by kripken** [comment]
I think we don't have the generic `syscall` method, and instead implemented direct calls to the various ones, so that we can analyze them statically, which is useful for reducing code size. See details in `./system/lib/libc/musl/src/internal/syscall.h`.

**Comment by nepx** [comment]
How would one go around calling something like, say, `SYS_close`? Is there an API of some sort or some header files I have to include (because musl seems to use `syscall` directly? I'm not sure)? 

And I know that using system calls isn't the most portable of assumptions to make, but since I'm already doing a lot of Emscripten-specific stuff in my project I thought I might as well take advantage of the browser-based system calls.

**Comment by kripken** [comment]
Not sure there would be much benefit to calling them directly, as opposed to calling musl. Calling musl would also keep working if we change the syscall API, which might happen.

But if you want to, I'd look at how musl does it: something like `__syscall(SYS_close, fd);` appears in the code. iirc, `__syscall` is a macro that expands into a static call.

**Comment by nepx** [comment]
In my project, I decided to just go with the wrappers, (i.e. `close` rather than `syscall(SYS_close)`), but it would be nice to have a standardized system call interface (to call things like, say, `renameat2`, which [has no glibc wrapper](http://man7.org/linux/man-pages/man2/renameat2.2.html)). Exposing the `syscall` interface might make low-level code easier to port.
