### ISSUE TITLE
Embind unresolved symbol

### ISSUE THREAD

**Issue by chris70c** [emscripten-core/emscripten#6712]
if I compile the simple code attached I get this warning:

Warning: unresolved symbol: _ZN4test3cl1C1Ev

What am I doing wrong?

Thanks

[code.zip](https://github.com/kripken/emscripten/files/2109156/code.zip)

also tried this code from Embind page:

#include <emscripten/bind.h>

struct Point2f {
    float x;
    float y;
};

struct PersonRecord {
    std::string name;
    int age;
};

PersonRecord findPersonAtLocation(Point2f);

using namespace emscripten;

EMSCRIPTEN_BINDINGS(my_value_example) {
    value_array<Point2f>("Point2f")
        .element(&Point2f::x)
        .element(&Point2f::y)
        ;

    value_object<PersonRecord>("PersonRecord")
        .field("name", &PersonRecord::name)
        .field("age", &PersonRecord::age)
        ;

    function("findPersonAtLocation", &findPersonAtLocation);
}

and I get an unresolved symbol too...

I can only make it work with -s LINKABLE=1

**Comment by FalkorX** [comment]
Your classes' constructors have no definition. Try removing the line `cl1();` or use `cl1() = default;` for generating the default definitions for these constructors. Same goes for class cl2.
