### ISSUE TITLE
Wasm malloc fails

### ISSUE THREAD

**Issue by buu700** [emscripten-core/emscripten#6715]
Still trying to figure out how to get a reproducible test case to trigger this state, but under some weird conditions any call to malloc (e.g. `Module._malloc(1)`) starts to consistently fail with the following error:

```
Uncaught RuntimeError: memory access out of bounds
    at wasm-function[29]:143
    at Object.B._malloc (http://localhost:42002/...:55479:68439)
    at eval (eval at B._malloc (http://localhost:42002/...:55479:68530), <anonymous>:1:3)
    at Object.B._malloc (http://localhost:42002/...:55479:68530)
    at http://localhost:42002/...:55479:144273
```

The build flags used are: `-O3 -s WASM=1 -s SINGLE_FILE=1 -s TOTAL_MEMORY=16777216 -s TOTAL_STACK=8388608 -s ASSERTIONS=0 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ALIASING_FUNCTION_POINTERS=1 -s DISABLE_EXCEPTION_CATCHING=1 -s NO_FILESYSTEM=1`.

The module was built with the latest version published via emsdk on March 14. This may be a Chrome issue (version 67.0.3396.87); I'll investigate tomorrow and see if I can manage to reproduce this with Firefox.

**Comment by kripken** [comment]
Maybe a memory corruption? `SAFE_HEAP` may find something.

**Comment by buu700** [comment]
Thanks! Just went ahead and tried that, and also found some more information:

1. malloc fails with the same error while the input is 12 or below. At 13 it works as expected for some reason.

2. With `-s ALIASING_FUNCTION_POINTERS=0 -s SAFE_HEAP=1`, it behaves the same way except the error is `Uncaught abort("segmentation fault"). Build with -s ASSERTIONS=1 for more info.`.

3. With `-s ASSERTIONS=1`, I get the following error (relevant file attached, which is a bundle that includes [sphincs.js](https://github.com/cyph/sphincs.js)):

```
abort("segmentation fault") at Error
    at jsStackTrace (http://localhost:42002/assets/js/cyph/crypto/potassium/index.js:76091:31)
    at stackTrace (http://localhost:42002/assets/js/cyph/crypto/potassium/index.js:76105:30)
    at abort (http://localhost:42002/assets/js/cyph/crypto/potassium/index.js:77249:62)
    at segfault (http://localhost:42002/assets/js/cyph/crypto/potassium/index.js:75857:21)
    at wasm-function[11]:29
    at wasm-function[51]:165
    at malloc (http://localhost:42002/assets/js/cyph/crypto/potassium/index.js:78903:47)
    at http://localhost:42002/assets/js/cyph/crypto/potassium/index.js:78975:50
```

[index.js.txt](https://github.com/kripken/emscripten/files/2113220/index.js.txt)

**Comment by kripken** [comment]
Oh sorry, I see you did check with ASSERTIONS in (3). I guess that option doesn't add much info.

**Comment by buu700** [comment]
Not sure. It's very edge case — it somehow happened by accident while testing something last night, but to make it happen intentionally I have to spend ~10 minutes repeatedly clicking buttons that trigger various calls to `sphincs.sign` while some unrelated `sphincs.open`s are going off in the background.

I haven't yet been successful at trying to manually trigger the state by interacting with the library directly (kicking off thousands of calls in my console), so I have no idea what the application could be doing differently to cause this.

**Comment by kripken** [comment]
Might help to use the DETERMINISTIC option, and to create a script that generates input events deterministically, that's helped me in the past.

**Comment by buu700** [comment]
Hmm, is there more information about that flag? What does it do, and (unrelated to this issue) would it help ensure that constant-time algorithms work as designed?

In any case, I'll go ahead and add that to the debug build and see what happens.

**Comment by kripken** [comment]
There are a few docs in settings.js: https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L576 It just makes Math.random, Date.now, etc. deterministic, so running the build twice gives the same results. It doesn't do anything for user input, though.

It wouldn't actually cause operations to be constant time, but it would make them seem constant time, if they are measured using Date.now ;)

**Comment by buu700** [comment]
Ah, got it, thanks. (Seemed a bit too good to be true that it might do something crazy under the hood to prevent browsers from making unwanted data-dependent performance optimizations.)

**Comment by buu700** [comment]
Okay, I got a reproducible test case by rebuilding with `DETERMINISTIC` and just logging all the sphincs.js function calls that took place while clicking around in the Cyph test environment.

Just run this Plunker with your console open in Chrome or Firefox to reproduce the error (preferably Chrome, since Firefox hangs for a long time on the `debugger` statement for some reason): https://plnkr.co/edit/98ExMA3ByC1T4jZqcI2M?p=preview

The steps that trigger this issue are a sequence of 77 calls to [`sphincs.verifyDetached`](https://github.com/cyph/sphincs.js/blob/927b6dc/post.js#L153) and 13 calls to [`sphincs.signDetached`](https://github.com/cyph/sphincs.js/blob/927b6dc/post.js#L109).

**Comment by kripken** [comment]
Good, a deterministic testcase can help a lot. I would try that with previous emcc versions to see if it's a regression - if it is, bisection can quickly find the issue. However, if the bisection takes you into say an LLVM upgrade, then likely it won't help (LLVM may just be placing stuff in different valid locations, and some happen to hit your issue).

If that fails, I'd try to add some debug printouts in the code and rebuild with those, to narrow this down. Often it's easier to debug in the original source in my experience.

**Comment by buu700** [comment]
Sounds good, thanks. I'll let you know when I have a chance to dig into this and find out more.
