### ISSUE TITLE
LLVM unhappy about gsl::byte ?

### ISSUE THREAD

**Issue by aardappel** [emscripten-core/emscripten#6728]
The final link step with `emcc` spits out this interesting error from LLVM:

```
invalid enum type
!1390 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1391, producer: "clang version 6.0.1  (emscripten 1.38.6 : 1.38.6)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !1392, retainedTypes: !1511, globals: !64226, imports: !64277)
!1392 = !{!1393, !1400, !1406, !1414, !1431, !1452, !1457, !1463, !1470, !1473, !1476, !1483, !1490, !1501, !1508}
!1400 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "byte", scope: !1402, file: !1401, line: 1057, size: 8, elements: !1403, identifier: "_ZTSN3gsl4byteE")
warning: ignoring invalid debug info in C:\w\lobster\dev\src\meshgen.o
invalid enum type
!1390 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1391, producer: "clang version 6.0.1  (emscripten 1.38.6 : 1.38.6)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !1392, retainedTypes: !1868, globals: !47565, imports: !47577)
!1392 = !{!1393, !1399, !1764, !1779, !1796, !1817, !1822, !1828, !1835, !1838, !1841, !1852, !1859, !1865}
!1859 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "byte", scope: !1861, file: !1860, line: 1057, size: 8, elements: !1862, identifier: "_ZTSN3gsl4byteE")
```

That appears to refer to `gsl::byte`, and indeed I am including https://github.com/martinmoene/gsl-lite, though I am not using `gsl::byte` anywhere in my code specifically (though `gsl::span` I use does have unused methods that refer to it).

The error does not appear to stop a valid wasm module being built and executed.

This is with a fresh emsdk I just installed today.

build settings: https://github.com/aardappel/lobster/blob/master/dev/emscripten/Makefile

**Comment by aardappel** [comment]
@martinmoene who wrote gsl-lite.

**Comment by kripken** [comment]
I'm guessing the error comes from LLVM here: https://github.com/kripken/emscripten-fastcomp/blob/f95ea2d7c7f9d1260fe91ee14d4920a4cbc01621/lib/IR/Verifier.cpp#L989

It's possible it's an LLVM bug. Does it also happen with the LLVM wasm backend (which has a newer LLVM)?

**Comment by aardappel** [comment]
Using the wasm backend (on Linux, above was Windows) I get this:

```
Invalid user of intrinsic instruction!
void (i8*, i8, i32, i1)* bitcast (void (i8*, i8, i32, i32, i1)* @llvm.memset.p0i8.i32 to void (i8*, i8, i32, i1)*)
Invalid user of intrinsic instruction!
void (i8*, i8*, i32, i1)* bitcast (void (i8*, i8*, i32, i32, i1)* @llvm.memcpy.p0i8.p0i8.i32 to void (i8*, i8*, i32, i1)*)
Invalid user of intrinsic instruction!
void (i8*, i8, i64, i1)* bitcast (void (i8*, i8, i64, i32, i1)* @llvm.memset.p0i8.i64 to void (i8*, i8, i64, i1)*)
Invalid user of intrinsic instruction!
void (i8*, i8*, i32, i1)* bitcast (void (i8*, i8*, i32, i32, i1)* @llvm.memmove.p0i8.p0i8.i32 to void (i8*, i8*, i32, i1)*)
llvm-link: error: linked module is broken!
```

That is a toolchain from a few months ago though. I'll update it and see if it still happens.

**Comment by aardappel** [comment]
With latest of all tools from the waterfall (last green build from today) with or without `EMCC_WASM_BACKEND=1` I get no such error, only thousands of lines like `skipping debug location info for 1373168`.

**Comment by martinmoene** [comment]
It's unlikely I can enlighten you down there in LLVM's krochten.
