### ISSUE TITLE
"Type undefined" error occurred when trying "enum" with WebIDL.

### ISSUE THREAD

**Issue by Becavalier** [emscripten-core/emscripten#6731]
The screenshot of error message:
![image](https://user-images.githubusercontent.com/8282020/41692516-553050c4-7533-11e8-80a7-77a4d0120f40.png)

The content of "glue.cpp" generated by "webidl_binder.py":
![image](https://user-images.githubusercontent.com/8282020/41692358-6b413690-7532-11e8-99ad-6d1fbf9e2e2c.png)

I am trying to "glue" an enum data structure into JavaScript by WebIDL which was defined inside a namespace block like below:
```c++
namespace WebAssembly {
  enum yEnum {
    ns_enum_val1 = 10,
  	ns_enum_val2
  };
};
```
The corresponding WebIDL:
```
enum WebAssembly_yEnum {
  "WebAssembly::ns_enum_val1",
  "WebAssembly::ns_enum_val2"
};
```

It seems like the compiler did not find the definition of type "WebAssemby_yEnum". **Should we hardcode the type of return value into "int"?**

https://github.com/kripken/emscripten/blob/de0987a23fc1e5c65decb65b148f8b3755b890c4/tools/webidl_binder.py#L722-L726

@kripken @sbc100

**Comment by kripken** [comment]
I think you're right @Becavalier , we should assume the type of an enum is an int.

What's odd is that we have tests for enums in webidl - might be worth looking at them, to see what we are missing in the coverage.

**Comment by Becavalier** [comment]
@kripken Let me figure out this issue. : )

**Comment by Becavalier** [comment]
I found this file "emscripten/tests/webidl/test.cpp" has the following codes which will pre-define those symbols. If I remove these two lines, the same error will occur.

https://github.com/kripken/emscripten/blob/2195ec7e644a86f1352b6f1724edd76c05b3aba1/tests/webidl/test.cpp#L7-L8

**Comment by kripken** [comment]
Hmm, reading `tools/webidl_binder.py`, I see we have some explicit support for enums there. I'm not sure, but if we know what are enums, we could just turn them into ints, as you suggested.

But in the meanwhile documenting this might be good.

**Comment by koconnor** [comment]
@Becavalier, @kripken, is there a workaround for this in the short term?  I appear to be running into this with an enum in a namespace. Should I add those two typedefs to a file emcc'd to the final js?

**Comment by Becavalier** [comment]
@koconnor 
Yes, Currently you should add those typedefs into your c/c++ source file according to your enum types.
