### ISSUE TITLE
 I  need a  help!

### ISSUE THREAD

**Issue by OgreShader** [emscripten-core/emscripten#6735]
1>Context.obj : error LNK2019: unresolved external symbol emscripten_cancel_main_loop referenced in function "public: static void __cdecl Context::_mainLoop(void *)" (?_mainLoop@Context@@SAXPEAX@Z)

I build the a win32 project on windows by  the version of  emscripten is 1.35.0 SDK and  the version of MSVC is 12. 
I have  include  emscripten.h  ,but there  has e error like that. So ,Can you give me the file that is emscripten.c or emscripten.cc. I want to know the defination of emscripten_cancel_main_loop .
Can  you help me  or give me a solution about it ?

**Comment by curiousdannii** [comment]
emscripten_cancel_main_loop 
 is defined here: 
https://github.com/kripken/emscripten/blob/bee58ef2f4644f24273dfbda0642e2ad5ba33a15/src/library_browser.js#L1207

**Comment by Becavalier** [comment]
This is an external function which declared here:
https://github.com/kripken/emscripten/blob/a35a823311888ec2545c1bf7a4759980ad55c426/system/include/emscripten/emscripten.h#L77
 
And the definition is located here:
https://github.com/kripken/emscripten/blob/bee58ef2f4644f24273dfbda0642e2ad5ba33a15/src/library_browser.js#L1207-L1210

**Comment by OgreShader** [comment]
@Becavalier     How  to link this  file which is library_browser.js   by  vs2013 on windows.

**Comment by Becavalier** [comment]
Please make sure you have included this "emscripten.h" head file into you project correctly, so "emcc" will automatically finding the corresponding function body through the static compiling.

**Comment by curiousdannii** [comment]
You can't just include the emscripten.h header, you need to compile your project with emcc. The entire compiler toolchain is different.

Have a read of the tutorial if you haven't yet.
http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html

**Comment by Becavalier** [comment]
@OgreShader As @curiousdannii said, you need to use Emscripten's compiler toolchain to compile your project rather than your normal compiler.

**Comment by OgreShader** [comment]
@Becavalier @curiousdannii   ，
if  I use emcc, it can't  automatically finding  the  Ogre.h in my project.

**Comment by OgreShader** [comment]
@Becavalier  @curiousdannii ,
if I use emcc , it cannot find other library files except Emscripten's library.I use Emscripten's library on Ogre。I use emcc to complie main.cpp,it can find emscripten.h,but cannot find other library files contained in other library files。
Can you help me or give me a solution about it ?

**Comment by curiousdannii** [comment]
It depends on what libraries you need. Many are available in the Ports system. See http://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#emscripten-ports

**Comment by Becavalier** [comment]
You can regard "emcc" as a normal clang compiler, so please feel free to use "-I" to point out the location of your necessary "include" header files.
 
![image](https://user-images.githubusercontent.com/8282020/41952677-be41e38c-7a03-11e8-9186-5ecbc7677d49.png)

**Comment by OgreShader** [comment]
@Becavalier  @curiousdannii 
Thank you for using the -I solution to find the files that the library contains.
According to the tutorial set EMCC_DEBUG = 1, I want to see the compilation error message, but can not find where the log generated file. The tutorial says that the log output folder
TEMP_DIR/emscripten_temp does not exist.Can you tell me where is it?
