### ISSUE TITLE
how to bind a top-level function in webIDL?

### ISSUE THREAD

**Issue by timotheecour** [emscripten-core/emscripten#6742]
## how to bind a top-level function in webIDL?
Here `fun` is a top-level C++ function (ie, not in a class)
```
// funs.h
void fun();
```

What's the corresponding funs.idl file?
```
// funs.idl
void fun(); 
```
this didn't work, can't seem to find examples that don't involve `interface`

## related: how to call a static method without a class instance in webIDL?
```
/// funs.cpp
class A{
  static void fun();
};
/// funs.idl
interface A{
  static void fun();
}
/// test.js
Module.A.fun(); // doesn't work
new Module.A().fun(); // works but shouldn't be necessary to have an instance since it's a static method
```

**Comment by Becavalier** [comment]
@timotheecour 
Sorry, all the current functions defined in WebIDL must be wrapped in an "interface" structure. You can see these files for further information: https://github.com/kripken/emscripten/tree/incoming/tests/webidl.

For your second question, you can try calling the function through the prototype of the corresponding object in JavaScript:

FYI: https://github.com/kripken/emscripten/blob/bf0bdc540ad45b7178c6ea77a947c1b9f70a127d/tests/webidl/post.js#L65
