### ISSUE TITLE
source emsdk_env.sh errors with: `BASH_SOURCE: parameter not set` if set -u + zsh is used

### ISSUE THREAD

**Issue by timotheecour** [emscripten-core/emscripten#6743]
```
source emsdk_env.sh
emsdk_env.sh:18: BASH_SOURCE: parameter not set
```
cause:
I have set -u in my shell (to avoid common errors) and use zsh.

workaround until emsdk_env.sh is fixed:
instead of `source /path/to/emsdk_env.sh`, call: `BASH_SOURCE=/path/to/emsdk_env.sh source /path/to/emsdk_env.sh`

**Comment by kane-thornwyrd** [comment]
F the stale state, it's still an issue !

**Comment by kripken** [comment]
Ok, reopening.

**Comment by sbc100** [comment]
If you would like to fix it any patches would be very welcome.  I don't know of any emscripten developers who use zsh so we might not be the best placed to fix it.

It could be that you need to create a new emsdk_env.zsh file (like the `.csh` and `.fish` and `.ps1` scripts we have to other shells)?  I'm not sure.

**Comment by nhooyr** [comment]
I opened https://github.com/emscripten-core/emsdk/pull/605 to fix!
