### ISSUE TITLE
emcc returns error code 0 even with error

### ISSUE THREAD

**Issue by timotheecour** [emscripten-core/emscripten#6745]
`emcc test.cpp --preload-file /tmp/foo.txt && echo success` prints success even though it gives error:
Error: Embedding "/tmp/foo.txt" which is below the current directory "/Users/timothee/temp". This is invalid since the current directory becomes the root that the generated code will see

emcc should return error code non-zero in case of error

**Comment by kripken** [comment]
It's possible we should say that's a warning instead of an error. Alternatively, maybe since that file won't be accessible, maybe it should be an actual error. No strong feelings either way from me.
