### ISSUE TITLE
Embind + Closure Compiler - proper strategy

### ISSUE THREAD

**Issue by bsokol** [emscripten-core/emscripten#6758]
Is there any recommended strategy for using --closure 1 and binding C++ methods to JS via embind?

I have (for example) simple function in C++ :
```
EMSCRIPTEN_KEEPALIVE void App_Log(const string& txt)
{
	Log(txt.c_str());
}
```
binded to JS via:
```
EMSCRIPTEN_BINDINGS()
{
	emscripten::function("App_Log", &App_Log);
}
```
and I am using it from JS code without any issues:
`Module.App_Log("test");`

but after adding "--closure 1" to my makefile I've got silent freezes or exceptions like: "TypeError: e.hb is not a function".

I cannot find any tips in the docs how to make it work :/

**Comment by kripken** [comment]
We should try to document this better. But I'm not sure what the status is. In particular, I'm not sure how EMSCRIPTEN_KEEPALIVE (which should keep it alive + export it as a simple C function) works with EMSCRIPTEN_BINDINGS.

However, from the error message, I am guessing your JS that does that call is being optimized by emscripten and closure. In that case, does `Module['App_Log']("test");` work?

**Comment by bsokol** [comment]
> However, from the error message, I am guessing your JS that does that call is being optimized by emscripten and closure. In that case, does Module['App_Log']("test"); work?

Yes, it works.

I also found two workarounds:

1. I can fix references at the begining of main:

int main(int argc, char *argv[])
{	
	EM_ASM(
		Module._malloc = Module["_malloc"];
		Module._free = Module["_free"];
		Module.stringToUTF8 = Module["stringToUTF8"];
		Module.App_Log = Module['App_Log'];
        );
  ....
};

and it works even after closure compiler pass (because I see `e.N("test")` instead of `Module.App_Log("test")` in app.js )

2.  or I can use additional externs file with closure compiler:

set EMCC_CLOSURE_ARGS=--externs .../myexterns.js

with method declaration:
`var App_Log = function () { };`

so Module.App_Log is not minified and  `e.App_Log("test")` is generated in asm.js

Both 'hacks' works correct but I am still not sure that is is proper way to make embid and closure work together. And these solutions reqiure some additional work which can/should be automated.

**Comment by kripken** [comment]
I don't think it's possible to automate these - closure compiler is tricky, it depends on things that JS semantics strictly don't. In particular closure will minify `foo.bar` into `a.b` or such, but leave `foo['bar']` as `a.bar` (the `bar` remains). The developer needs to be aware of these rules when writing code that closure will see. closure has a bunch of [docs](https://developers.google.com/closure/compiler/docs/api-tutorial3#propnames) on this.
