### ISSUE TITLE
Can't disable 'antialias' via SDL

### ISSUE THREAD

**Issue by TrevorSundberg** [emscripten-core/emscripten#6764]
We're porting our engine to emscripten, fantastic work by the way! We've run into a problem where our engine attempts to blit a frame-buffer to the back-buffer but it can't because the back-buffer is multi-sampled.

We're setting `-s USE_WEBGL2=1` and using SDL. We've attempted to disable multi-sampling via:
```
SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 0);
SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 0);
```
As per the SDL documentation we put it before any window creation (but after `SDL_Init`). We also tried putting it after the window creation but before the `SDL_GL_CreateContext`, and finally tried it even after `SDL_GL_CreateContext`. We also called `glDisable(GL_MULTISAMPLE)` and `glDisable(GL_MULTISAMPLE_ARB)` just in case, but those come after the WebGL context is created so that wouldn't quite work, and they ended up emitting errors anyways.

I investigated and found that if I just insert the line:

```
createContext:function (canvas, webGLContextAttributes) {
  webGLContextAttributes.antialias = false;
```

Everything works. How can we disable antialias without having to insert that line every time? Even if it's somehow running JavaScript from C++ that patches over the `canvas.getContext`, that would be fine!

Thanks again for developing such awesome software.

**Comment by kripken** [comment]
There are some context-handling methods in the HTML5 API, https://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html?highlight=emscripten_webgl_create_context#c.emscripten_webgl_init_context_attributes

I'm not sure how those interact with SDL, and there doesn't seem to be a test combining them. I'd guess you not tell SDL to init GL, and instead create it using the HTML5 API, set the attributes you want like antialias, then set it as current, and rendering should work. If it doesn't please let us known.

**Comment by TrevorSundberg** [comment]
I ended up doing something a bit different and hooking the canvas.getContext function inside of our provided shell.html (using `--shell-file`). For anyone referencing this bug, here's the workaround:

```javascript
var canvasElement = document.getElementById('canvas');
var originalCanvasGetContext = canvasElement.getContext;
canvasElement.getContext = function(contextType, contextAttributes)
{
  if (contextAttributes)
    contextAttributes.antialias = false;
  
  return originalCanvasGetContext.call(this, contextType, contextAttributes);
};
```

**Comment by Jorhlok** [comment]
I ran into this and wasn't using a shell.html (yet) so I did as @kripken suggested. Here's what that looks like in C++ (SDL2 and GLESv2) for future reference.


```c++
	SDL_Window *window;
	SDL_GLContext context;
	SDL_Init(SDL_INIT_VIDEO);

	SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
	SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);

	window = SDL_CreateWindow("Demo", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 800, 480, SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN);
#ifndef __EMSCRIPTEN__
	context = SDL_GL_CreateContext(window);
#else
	EmscriptenWebGLContextAttributes conattr;
	emscripten_webgl_init_context_attributes(&conattr); //load default webgl1 attributes
	conattr.antialias = false;
	EMSCRIPTEN_WEBGL_CONTEXT_HANDLE con = emscripten_webgl_create_context(0,&conattr);
	emscripten_webgl_make_context_current(con);
	context = SDL_GL_GetCurrentContext();
#endif
```
