### ISSUE TITLE
Firefox Profiler only references my *.js file and not my source (C++)

### ISSUE THREAD

**Issue by athei** [emscripten-core/emscripten#6775]
I am trying to profile a C++ project that I ported to wasm using emscripten. [This site](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html) states that the Firefox Profiler should be able to pin its entries to the actual source file.

But what I am experiencing is that all the entries are referencing my *.js file:
![screen shot 2018-06-28 at 23 57 58](https://user-images.githubusercontent.com/2580396/42062890-8cc604e6-7b2f-11e8-952a-aebf62103470.png)

This is how I build the project:
```
# compiled all o files this way
em++ file1.cpp -o file.o -g --std=c++14 -O3 -DNDEBUG
em++ file2.cpp -o file.o -g --std=c++14 -O3 -DNDEBUG
em++ file2.cpp -o file.o -g --std=c++14 -O3 -DNDEBUG

# create html output
em++ file1.o file2.o file3.o -o simc.html -O3 -DNDEBUG\
    -s TOTAL_MEMORY=256MB -s DISABLE_EXCEPTION_CATCHING=1\
    --preload-file moerrer.simc --no-heap-copy -s WASM_MEM_MAX=1024MB\
    -s ALLOW_MEMORY_GROWTH=1 --profiling -g4
```

Am I getting the parameters wrong? This is with Firefox 61 but Safari shows the same effect. I guess its something off with my compilation flags.

**Comment by kripken** [comment]
Not sure offhand what could be wrong. I'd try two things first:
 * does it matter if the 3 files are combined into one cpp file, then compiled? (I doubt this is it, but just to be sure)
 * does it matter if you disable wasm (`-s WASM=0`)? (wasm source maps are less tested)
