### ISSUE TITLE
Request: Adopt Reentrant Implementation of getenv for Better Compatibility with Other Code Bases

### ISSUE THREAD

**Issue by ilyaigpetrov** [emscripten-core/emscripten#6778]
#4226 (getenv: Calling getenv deallocate string previously returned)
> After your comment, I did some more searching and ... it seems common for existing implementation to assume multiple call to getenv do not modify the underlying environment.
By @jcfr [here](https://github.com/kripken/emscripten/issues/4226#issuecomment-205654770)

#5053 (getenv returns temporary strings?)
#6766 (Building NCurses. Emscripten getenv Bug?): ncurses fails to function because it assumes getenv to be reentrant.

Maybe some flag/switch/config settable for projects that require reentrant behavior?

**Comment by ThomasDickey** [comment]
That's mentioned in POSIX (most of the rationale is moot since applications aren't allowed to modify the environment directly):

http://pubs.opengroup.org/onlinepubs/9699919799/functions/getenv.html

saying that as an *extension*,

>The returned string pointer might be invalidated or the string content might be overwritten by a subsequent call to getenv(),  setenv(), unsetenv(),  or (if supported) putenv()  but they shall not be affected by a call to any other function in this volume of POSIX.1-2017.

**Comment by ilyaigpetrov** [comment]
@ThomasDickey Is that you the current maintainer of [ncurses](https://invisible-island.net/ncurses/)? Will there be a patch to ncurses to resolve this issue?

**Comment by ThomasDickey** [comment]
Actually, I'd forgotten (too many to-do's).  Most of the calls to `getenv` are checked and discarded immediately, but I suppose some might be passed into a function which directly (or indirectly) calls `getenv`. In [#6766](https://github.com/emscripten-core/emscripten/issues/6766) I don't see that offhand, but I might be able to construct a test which I could use to fix that.

Adding a to-do item :-)

**Comment by jamesbiv** [comment]
@ThomasDickey @ilyaigpetrov Hi Guys!

@ThomasDickey It would be great if you have plans to port ncurses to emscripten. If that's the case could you please see my <a href=http://www.jamesbiv.com/ircii-emscripten/irc.html>test site</a> for ircII. If you inspect the page the following error is shown. 

![Screenshot](https://user-images.githubusercontent.com/16272529/62787566-5927f980-ba9b-11e9-97ba-e00d4bdf897d.png)

The implementation works with -s ASSERTIONS=1 enabled. But id thought id raise it any case.

**Comment by ThomasDickey** [comment]
sorry - just not enough time.

The stack trace (in the middle) uses names that might have come from some attempt to port ncurses in to this environment, but the context would be a filename (which wouldn't have non-ASCII text).

**Comment by jamesbiv** [comment]
Yeah I see it now, interesting :) thanks!

**Comment by drpowell** [comment]
Override the standard library for getenv() works for my use-case.  Include this with `--js-library`

    mergeInto(LibraryManager.library, {
    // Override the getenv call to make it return a stable location per entry.
    getenv: function(name) {
        if (name === 0) return 0;
        name = UTF8ToString(name);
        if (!ENV.hasOwnProperty(name)) return 0;

        // Use 1 location for each name.  Use an ES6 map
        if (!_getenv.ret) _getenv.ret = new Map()
        if (_getenv.ret.has(name)) _free(_getenv.ret.get(name));
        _getenv.ret.set(name, allocateUTF8(ENV[name]));
        return _getenv.ret.get(name);
    },
  });

**Comment by sbc100** [comment]
I wonder if we should just switch to using musl's getenv and drop the JS version?

**Comment by drpowell** [comment]
That would work too - just need to be sure to handle all the *env() functions (setenv(), putenv()).  Not sure how musl would interact with the javascript `ENV` object.

**Comment by sbc100** [comment]
I think the JS ENV object is just for seeing the environment.  No need to keep them in sync after startup.

**Comment by drpowell** [comment]
As getenv() and friends is implemented at the moment, it is possible to interact and modify the ENV object at runtime from JS code and see that reflected in calls from the compiled code

**Comment by sbc100** [comment]
I'm not sure we want to support that.   Calling putenv seems reasonable, but I'm happy to declare that direct ENV manipulation after startup is not supported.   In general C programs don't expect to call getenv() and second time and get a different result.

**Comment by sbc100** [comment]
These days we rely on musl's getenv/setenv code.

**Comment by Potherca** [comment]
> These days we rely on musl's getenv/setenv code.

@sbc100 Could you post an example of _how_? I'm trying to compile lynx to WASM but I'm running into issues with ncurses.
And I'm still to much a n00b at compiling things to understand what is going on without pointers...

**Comment by sbc100** [comment]
> > These days we rely on musl's getenv/setenv code.
> 
> @sbc100 Could you post an example of _how_? I'm trying to compile lynx to WASM but I'm running into issues with ncurses.
> And I'm still to much a n00b at compiling things to understand what is going on without pointers...

I'm not sure what your question is.   Are you having trouble using getenv/setenv?     The environment exposed to emscripten programs is a synthetic one defined here: https://github.com/emscripten-core/emscripten/blob/a560a678aca86f05dd7888dd5d71cc00c4cabe41/src/library_wasi.js#L25-L33.   Is that the issue?

I imagine there could be several issue with curses-based programs that expect to read TERMINFO.  Terminal-based programs don't have a lot of testing emscripten today.

**Comment by sbc100** [comment]
If you are interested in running on node (as opposed to the web) then you might be interested in direct access to the environment: https://github.com/emscripten-core/emscripten/issues/3915

**Comment by Potherca** [comment]
Thanks! Both pointers help me in the puzzle I'm trying to unravel.
