### ISSUE TITLE
emscripten_log + sourcemaps + wasm fails

### ISSUE THREAD

**Issue by pierreglibert** [emscripten-core/emscripten#6784]
Hi community :)
I try to write the line errors of cpp files in console with the sourcemap.
I tested it with a sample "hello world" but I have this : 
![capture d ecran 2018-06-30 a 14 09 26](https://user-images.githubusercontent.com/21291915/42125045-3f214be2-7c6f-11e8-86fe-fb625cf24961.png)

I tried with `--pre-js $EMSCRIPTEN/src/emscripten-source-map.min.js` but I have this : 
![capture d ecran 2018-06-30 a 14 20 47](https://user-images.githubusercontent.com/21291915/42125124-e62387ba-7c70-11e8-9a0b-326200285135.png)

My code : 
```
int main() {
     emscripten_log(EM_LOG_C_STACK, "hello world \n");
     return 0;
};
```

The command line : 
`./emcc main.cpp -std=c++11 -s USE_WEBGL2=1 -Werror -v -g4 -o /build/main.html`

Can you help me please ?

**Comment by kripken** [comment]
I think this may be a wasm source maps bug. When I do this (when a.cpp is the C code you provided, plus `#include <emscripten.h>` at the top),
```
./emcc a.cpp -std=c++11 -g4 -o a.html  --pre-js /home/alon/Dev/emscripten/src/emscripten-source-map.min.js -s WASM=0
```
then it works as expected. When not disabling wasm, though, it fails.

I suspect the source map parsing library there assumes a JS source map, and we'd need code to parse wasm source maps.

In the shorter term, it might be nice to improve that warning message to mention this only works without wasm for now.

**Comment by pierreglibert** [comment]
Thanks @kripken for your answer :)
