### ISSUE TITLE
Question: How to access FS in EXPORT_ES6=1 mode

### ISSUE THREAD

**Issue by ThorstenBux** [emscripten-core/emscripten#6787]
Hi,

I'm compiling my project with `-s MODULARIZE_INSTANCE=1 -s EXPORT_NAME='project' -s EXPORT_ES6=1 `

Then I access the exported instance like this:
```import project from './project.js';```

That is working well. Now I would like to access `FS` from the javascript that also imports the project.js file. However, I can't find a way to get access to the FS object.

Any suggestions?

At the moment I append a js script using ```--post-js``` that exports a function which accesses FS which seems to work but doesn't seem to be very elegant.

**Comment by kripken** [comment]
You can export the FS using `-s 'EXTRA_EXPORTED_RUNTIME_METHODS=["FS"]'`, and then it is accessible on the `Module` object (which should be the main exported object in `EXPORT_ES6` mode).
