### ISSUE TITLE
Using Emscripten Fetch causes problems with --closure 1

### ISSUE THREAD

**Issue by quartata** [emscripten-core/emscripten#6811]
Bare-bones example to reproduce it without the code getting optimized out:

```
#include <emscripten/fetch.h>

int main(void)
{
    emscripten_fetch(NULL, "");
}
```

Compile with: `$EMSDK/emcc -O2 -s WASM=0 -s FETCH=1 --closure 1 file.c`

The result:

```
/tmp/tmpfurai9h0.cl.js:1405: ERROR - variable ENVIRONMENT_IS_FETCH_WORKER is undeclared
      var isMainThread = (typeof ENVIRONMENT_IS_FETCH_WORKER === 'undefined');
```

I'm on `incoming` commit 8f9d510 currently.

**Comment by kripken** [comment]
Confirmed on latest incoming.

Looks like the var is defined in `src/fetch-worker.js` and used in `src/Fetch.js` (and the error is in there). I think we may need to define that var in `Fetch.js` which is used in both `src/fetch-worker.js` and `src/library_fetch.js`, but I'm not sure.

**Comment by quartata** [comment]
I just threw this in at the top of `staticInit`

```
    /** @suppress {duplicate} **/
    var ENVIRONMENT_IS_FETCH_WORKER;
```

and it works fine now, but there must be a better solution. (I don't know anything about how this is structured.)
