### ISSUE TITLE
Loading DLL lead to an Error in loading dynamic library: "Assertion failed: need to see wasm magic number"

### ISSUE THREAD

**Issue by Milerius** [emscripten-core/emscripten#6817]
Hello i followed the tutorial for dynamic library i'm here so far:

<img width="1673" alt="capture d ecran 2018-07-06 a 20 20 36" src="https://user-images.githubusercontent.com/21139416/42394366-2fe91502-815a-11e8-9c3d-e03f3864dadd.png">

so i compiled ecs-test as a main module and the dynamic library as a side module

i get this error when i run the program:
<img width="1679" alt="capture d ecran 2018-07-06 a 20 22 35" src="https://user-images.githubusercontent.com/21139416/42394433-6029edc2-815a-11e8-84d2-93de930ccfcb.png">

there is my cmake:
```cmake
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
macro(generate_local_plugin SOURCES EXECUTABLE)
    add_library(${EXECUTABLE} SHARED "${SOURCES}")
    target_link_libraries(${EXECUTABLE} shiva::world)
    set_property(TARGET ${EXECUTABLE} PROPERTY POSITION_INDEPENDENT_CODE ON)
    set_target_properties(${EXECUTABLE}
            PROPERTIES
            ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/systems_test"
            LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/systems_test"
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/systems_test"
            LIBRARY_OUTPUT_DIRECTORY_DEBUG "${CMAKE_SOURCE_DIR}/bin/systems_test"
            LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CMAKE_SOURCE_DIR}/bin/systems_test"
            RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_SOURCE_DIR}/bin/systems_test"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_SOURCE_DIR}/bin/systems_test")
endmacro()

set(SOURCES ecs-test.cpp)
CREATE_UNIT_TEST(ecs-test shiva: "${SOURCES}")

generate_local_plugin("plugins/system_plugged_bar.hpp;plugins/system_plugged_bar.cpp" system-plugin-bar)

if(EMSCRIPTEN)
    set_target_properties(system-plugin-bar PROPERTIES LINK_FLAGS "-s BUILD_AS_SHARED_LIB=1 -s SIDE_MODULE=1 -s EXPORT_ALL=1 -s DISABLE_EXCEPTION_CATCHING=0 -s FORCE_FILESYSTEM=1 -s SINGLE_FILE=1 -s BINARYEN_ASYNC_COMPILATION=0")
    set_target_properties(ecs-test PROPERTIES LINK_FLAGS "-s DEMANGLE_SUPPORT=1 -s MAIN_MODULE=1 -s EXPORT_ALL=1 -s DISABLE_EXCEPTION_CATCHING=0 -s FORCE_FILESYSTEM=1 -s SINGLE_FILE=1 -s BINARYEN_ASYNC_COMPILATION=0 --embed-file ${CMAKE_SOURCE_DIR}/bin/systems_test@/systems_test")
endif()

target_link_libraries(ecs-test shiva::world)
add_dependencies(ecs-test system-plugin-bar)

magic_source_group(ecs-test)
```

so i have exported all functions from the modules with `-s EXPORT_ALL=1`

It's seems that for dlopen, it's not a valid module

so the stacktrace is: boost::dll::load(libname.so) -> dlopen(libname.so) which failed with `[plugins_registry][08:30:18 PM][pid: 42][error]: error loading: libsystem-plugin-bar.so -> boost::dll::shared_library::load() failed (dlerror system message: Could not evaluate dynamic lib: /systems_test/libsystem-plugin-bar.so`

plugins_registry code:
```cpp
template <typename CreatorSignature>
    class plugins_registry
    {
    public:
        using symbols_container = std::vector<std::function<CreatorSignature>>;

    private:
        symbols_container symbols;
        shiva::fs::path plugins_directory_;
        shiva::logging::logger log_{shiva::log::stdout_color_mt("plugins_registry")};

    public:
        explicit plugins_registry(shiva::fs::path &&plugins_directory) noexcept :
            plugins_directory_{plugins_directory}
        {
            log_->info("plugins_registry directory: {}", plugins_directory.string());
            log_->info("plugins_registry successfully created.");
        }

        bool load_all_symbols() noexcept
        {
            bool res{true};
            if (!fs::exists(plugins_directory_))
                return false;
            fs::recursive_directory_iterator endit;
            for (fs::recursive_directory_iterator it(plugins_directory_); it != endit; ++it) {
                if (!fs::is_regular_file(*it)) {
                    continue;
                }
                if (!is_shared_library((*it).path())) {
                    continue;
                }
                try {
                    symbols.emplace_back(
                        boost::dll::import_alias<CreatorSignature>(
                            boost::filesystem::path(it->path().string()),
                            "create_plugin",
                            dll::load_mode::append_decorations
                        ));
                    log_->info("Successfully loaded: {}", it->path().filename().string());
                }
                catch (const boost::system::system_error &error) {
                    log_->error("error loading: {0} -> {1}", it->path().filename().string(), error.what());
                    res = false;
                }
            }
            return res;
        }

        size_t nb_plugins() const noexcept
        {
            return symbols.size();
        }

        template <typename Functor>
        void apply_on_each_symbols(Functor &&functor)
        {
            shiva::ranges::for_each(symbols, functor);
        }
    };
```

Any idea ?

**Comment by Milerius** [comment]
@kripken there is something that i miss ? I can not find what's wrong

**Comment by kripken** [comment]
It says it doesn't see the wasm magic number, so maybe that file is LLVM bitcode (first 2 bytes are `BC`)? If so, then you missed the step of compiling the bitcode to wasm (using something like `emcc -s SIDE_MODULE=1 input.bc -o output.wasm`).

Are we missing that in the docs somewhere?

**Comment by Milerius** [comment]
as you can see my first screenshot the command line use -s SIDE_MODULE=1 !

**Comment by kripken** [comment]
I don't know cmake well enough to know if that's the right place, though. That needs to be passed when compiling bitcode to wasm, not linking bitcode. We should probably raise an error if it's the wrong time, I'll look into that. But meanwhile, what I mean is
```
emcc a.bc b.bc -o c.bc -s SIDE_MODULE=1
```
that command will still emit bitcode, not wasm. Even with the output set to `c.so` it will emit bitcode. You need to set the suffix to `.wasm` for it to compile to wasm (or to `.js` if instead you wanted `.js`).

**Comment by kripken** [comment]
I added an error message + test for that in #6835

**Comment by Milerius** [comment]
@kripken Oh thank's kripken, i will probably try to make add_executable instead of add_library so when using emscripten, sound's good ?

**Comment by Milerius** [comment]
can you give a little example ?

**Comment by kripken** [comment]
I don't know enough cmake to give an example using that, but look in `tests/test_other.py` for `SIDE_MODULE` or `MAIN_MODULE` to see working examples of those.

**Comment by Milerius** [comment]
@kripken baaaa, i generate a wasm now, but i dont know how to transform the wasm into library ... :/
