### ISSUE TITLE
SDL_DropEvent does not override default browser behavior

### ISSUE THREAD

**Issue by danecurbow** [emscripten-core/emscripten#6839]
Currently when using emscripten (1.38.5) SLD_DropEvents are not received.
It appears the default browser window event listeners are still connected for drag and drop events.
SDL_SendDropFile isn't called anywhere inside the emscripten sld port.
Is there any existing branches with this support or any planned support?

**Comment by kripken** [comment]
Yeah, looks like those events are not hooked up. Should be here:

https://github.com/emscripten-ports/SDL2/blob/master/src/video/emscripten/SDL_emscriptenevents.c#L616

I'm not aware of anyone planning to work on it, but might be worth filing an issue in the ports SDL2 repo there to ask (could be some people only read there).

**Comment by danecurbow** [comment]
Thanks for the reply. I will report the issue over on the emscripten-ports repo as suggested.
