### ISSUE TITLE
Memory access out of bounds (recursion limit?)

### ISSUE THREAD

**Issue by d07RiV** [emscripten-core/emscripten#6843]
Using this small code to test recursion and local value pointers:

    #define WASM_EXPORT __attribute__((visibility("default")))
    
    void getv(int idx, int* ptr);
    
    WASM_EXPORT
    int sum(int idx) {
      int v;
      getv(idx, &v);
      if (idx > 0) {
        v += sum(idx - 1);
      }
      return v;
    }

The generated code sets global `$g0` to 65560 and decrements it by 16 for every function call (incrementing again before returning). As expected, this fails when recursion depth is over ~4K.

For a real world scenario that could potentially require more values and/or deeper recursion, is there any way to adjust maximum stack size?

This example in action:
https://webassembly.studio/?f=62598e3q9ng

**Comment by kripken** [comment]
In emcc the TOTAL_STACK parameter lets you define the stack size (default 5MB). If you compile manually using llc, I believe it has an `-emscripten-stack-size` parameter, https://github.com/kripken/emscripten/blob/incoming/emscripten.py#L414
