### ISSUE TITLE
Register a TTY

### ISSUE THREAD

**Issue by lunu-bounir** [emscripten-core/emscripten#6861]
I am using the incoming version and it has a TTY object which seems to be responsible of reading from stdin and writing to stdout. Basically I need to redirect these two to a JS library to parse (termlib.js in my case). I cannot seem to be able to use the `FS.init` as I get `Input is not from a terminal` in the console of my application. So I was wondering if this `TTY.register` can be useful or not. Couldn't find any documentation about how to use it.

**Comment by kripken** [comment]
Those internal details might not be well-documented, yeah - only option may be to read the source code in `library_fs.js`.

If all you need is stdin/stdout, though, then I believe you can define `stdin` and `stdout` on `Module` (a quick read in the source seems to support that too). However, I don't see this documented on

https://kripken.github.io/emscripten-site/docs/api_reference/module.html

We should add docs for it there.
