### ISSUE TITLE
Tutorial hello_world.c hello.html file doesn't load in Safari or Chrome from file:// URL and has confusing error message

### ISSUE THREAD

**Issue by tangobravo** [emscripten-core/emscripten#6865]
This part of the tutorial failed for me:
http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html#generating-html

It's the first `printf("hello, world!");` example, compiled with HTML output with `./emcc tests/hello_world.c -o hello.html`.

The tutorial suggests just opening the generated file, which for me opened the file in Safari from a file:// URL, but it doesn't work in that case. Same result with Chrome. There is also a confusing error message:
`on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)`

The example worked when serving the folder via HTTPSimpleServer, as mentioned in the later example about filesystem access.

I'm on the latest OS X (10.13.5) and recently activated the latest emsdk tools:
```
LLVM_ROOT='/Users/xxxx/Development/Tools/emsdk/clang/e1.38.8_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/Users/xxxx/Development/Tools/emsdk/clang/e1.38.8_64bit/optimizer'
BINARYEN_ROOT='/Users/xxxx/Development/Tools/emsdk/clang/e1.38.8_64bit/binaryen'
NODE_JS='/Users/xxxx/Development/Tools/emsdk/node/8.9.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/Users/xxxx/Development/Tools/emsdk/emscripten/1.38.8'
```

If not outputting the `Module['wasmBinary']` was on purpose, then the tutorial should be updated to recommend serving the files right from the first example (and the error message updated to avoid confusion).

**Comment by kripken** [comment]
I think this was a problem in older versions, which we fixed. Is there a chance you have more than one version installed (like maybe from Brew, which maybe put it in your path) and you compiled with the older one?

**Comment by kripken** [comment]
I see, thanks. Ok, then I guess the issue is that Safari, like Chrome, won't load file:// urls, and so async loading fails, and we fall back to the sync code path, which then hits that error. And that error is quite confusing, sorry about that.

I opened #6873 with a better error message, and also moved around the webserver text, as you mentioned earlier.

**Comment by tangobravo** [comment]
Thanks, that doc change looks like it should clear it up.

> emcc.py will do that for you when generating HTML (but not JS)

That was the bit that was confusing for me - I ran with `-o hello.html` but couldn't see any `wasmBinary` being setup up in the generated files. Is that what the "(but not JS)" bit is referring too - is there a "html only" compile option that would do this?

**Comment by kripken** [comment]
It's a little complicated - it will set `wasmBinary` if emitting HTML *and* also async compilation is off. Async compilation is on by default, so you didn't see it, but the previous confusing warning suggested it should be there...
