### ISSUE TITLE
emcc optimization flag works for the latest version ?

### ISSUE THREAD

**Issue by lst60916** [emscripten-core/emscripten#6869]
Hi,

My MAC updates to the emsdk latest version 1.38.8.

When I command something like : 
`emcc hello.c -o hello.html -O2`

I thought hello. mem. file is going to be generated. 
(this file format is prefered for my usage)
However there is only the hello.wasm.

I try the rest verison like 1.38.x and it turns out the same!
Wondering if I could solve it with some adjustment, 
or do you guys have the same situation ?    

Thank you so much
Have a nice day!

**Comment by FalkorX** [comment]
In some 1.37.x version Emscripten switched to WebAssembly by default, before that you had to explicitly enable it with WASM=1. Now you can still generate asm.js code (the one using the .mem file) by explicitly disabling WebAssembly via the WASM=0 option, although -if you can- you should consider using WebAssembly instead for performance reasons.
