### ISSUE TITLE
What are these warnings missing?

### ISSUE THREAD

**Issue by OgreShader** [emscripten-core/emscripten#6881]
E:\Emscripten-1.350>emcc E:\OgreEmscriptenDemo1\OgreEmscriptenDemo\OgreEmscrtipe
nDemo\Main.cpp -I%OGRE%/include/OGRE -I%OGRE%/include/OGRE/Overlay -I%OGRE%/incl
ude/OIS   -o  a.html
warning: unresolved symbol: _ZN6Sample13startMainLoopEv
warning: unresolved symbol: _ZN6Sample11setupEngineEv
warning: unresolved symbol: _ZN6SampleC1Ev

**Comment by kripken** [comment]
The commandline tool `c++filt` is useful for demangling stuff like that, for example
```
$ c++filt _ZN6Sample13startMainLoopEv
Sample::startMainLoop()
```
Perhaps you need to include another cpp file that has the Sample class implementation, which is used by Main.cpp?

**Comment by kripken** [comment]
`--js-library %OGRE%/lib/libOgreMain.so.1.10.0` - a JS library is a file containing JS. Looks like it fails when it tries to parse it.

To link in that file, just provide it as an input to emcc - remove the `--js-library`. (It should have been built to LLVM bitcode, so that it is a valid input.)

**Comment by OgreShader** [comment]
@kripken ,After  remove the --js-library.

_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void
warning: unexpected number of arguments 6 in call to '_ZNSt3__116__pad_and_outpu
tIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_

 Why? How to deal with it?

**Comment by kripken** [comment]
I think that's just a warning? Perhaps you can ignore it.

If not, it's possible some of the code was compiled with one version of emscripten, and other code with another. Like if you have a build of a library to bitcode, then you need to rebuild it from source to bitcode, so it's compatible with other code compiled with that version.

**Comment by OgreShader** [comment]
I can't ignore it, the generated Html made the error code in the browser is 83,
How  to  rebuild library from source to bitcode?

**Comment by OgreShader** [comment]
@kripken    Some of the warnings are as follows.
warning: unexpected return type %"class.std::__1::basic_streambuf"* in call to '
_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void
warning: unexpected number of arguments 6 in call to '_ZNSt3__116__pad_and_outpu
tIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_
baseES4_', should be 7
warning: unexpected return type %"class.std::__1::basic_streambuf"* in call to '
_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void
warning: unexpected number of arguments 6 in call to '_ZNSt3__116__pad_and_outpu
tIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_
baseES4_', should be 7
warning: unexpected return type %"class.std::__1::basic_streambuf"* in call to '
_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void
warning: unexpected number of arguments 6 in call to '_ZNSt3__116__pad_and_outpu
tIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_
baseES4_', should be 7
warning: unexpected return type %"class.std::__1::basic_streambuf"* in call to '
_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void
warning: unexpected number of arguments 6 in call to '_ZNSt3__116__pad_and_outpu
tIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_
baseES4_', should be 7
warning: unexpected return type %"class.std::__1::basic_streambuf"* in call to '
_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void
warning: unexpected number of arguments 6 in call to '_ZNSt3__116__pad_and_outpu
tIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_
baseES4_', should be 7
warning: unexpected return type %"class.std::__1::basic_streambuf"* in call to '
_ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0
_EES6_PKS4_S8_S8_RNS_8ios_baseES4_', should be void

**Comment by kripken** [comment]
I'm not sure what could cause that. It might be helpful to try to create a reduced testcase that also hits this issue, that would be much easier to debug.
