### ISSUE TITLE
Debugging a uncaught abort() best practices / tools -> abort(trap!)

### ISSUE THREAD

**Issue by janschmutz** [emscripten-core/emscripten#6885]
Hi, I'm currently trying to compile a c++ library to WASM and I've added a lot of compiler flags to figure out why parts of the code work and others throw me a 

    output.js:1 Uncaught abort() at Error
    at jsStackTrace (http://localhost:8080/dist/output.js:1:8739)
    at stackTrace (http://localhost:8080/dist/output.js:1:8910)
    at Object.abort (http://localhost:8080/dist/output.js:1:383760)
    at _abort (http://localhost:8080/dist/output.js:1:116089)
    at wasm-function[3286]:116
    at wasm-function[3303]:274
    ...
    ...

(for all browsers)
I've tried -g4 it also throws me a very weird error `abort(trap!)`  , ASSERTIONS=2, SAFE_HEAP=1, but I haven't really been able to gather more Information about the Error. How can I find out where the error was created in the source code, (wasm-function[..]) Are there  any good Tools for this? What are the best Strategies / Workflows to Debug Webassembly? Any Input is appreciated. 

I've tried WABT specifically the wasm-interp, but that seems to not work very well for large libs. Thanks in advance

**Comment by kripken** [comment]
Building with `-g` (as an `emcc` param), for debug info, will replace those `wasm-function` with the original function name.

There is also `-g4` which enables source maps, which can also let you view the original source in browser debuggers. Still some work on that though, so it might not be fully stable yet.
