### ISSUE TITLE
Config and cache files should be stored in a special directory by default

### ISSUE THREAD

**Issue by qrals** [emscripten-core/emscripten#6886]
emscripten has already created these files in my home directory
`.emscripten`
`.emscripten_cache__last_clear`
`.emscripten_ports/`
`.emscripten_sanity`
`.emscripten_cache/`
`.emscripten_cache.lock`

To avoid cluttering `~`, I suggest that such files be stored in something like `~/.emscripten.d/`.

**Comment by kripken** [comment]
Sounds reasonable to me. Perhaps except for the `.emscripten` config file, though - moving that would be much more noticeable than the others, and could surprise people. But all the rest could be combined into one dir.

**Comment by vanzef** [comment]
Pardon my intrusion. Why don't use [XDG Base Directiry specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)? I mean `$XDG_CACHE_HOME`, `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` which are `~/.config`, `~/.cache` and `~/.local/share`, respectively, by default?

**Comment by sbc100** [comment]
Closing in favor of #3624
