### ISSUE TITLE
Wrapping emscripten output in a function similar to modularize causes document.currentScript to fail

### ISSUE THREAD

**Issue by Polevata** [emscripten-core/emscripten#6927]
I'm trying to use Emscripten with requirejs. I don't want it polluting the namespace, so I've wrapped it inside a function (initializeModule) very similar to MODULARIZE, but although it properly detects that it's being run on web, it then assumes that there has to be a document.currentScript, which in the case of requirejs there  is not. Simply setting MODULARIZE also doesn't work because then I get a bunch of exports at the end which aren't compatible with requirejs. If I'm missing some sort of build flags, feel free to let me know, but it seems to me like a check for that variable, or even better, exports which support requirejs could be added? Or perhaps a flag to turn of automatic exporting with MODULARIZE?

**Comment by kripken** [comment]
I think that's a bug we recently fixed, where we assumed document.currentScript - is this still an issue on current incoming?

Btw, if we can make MODULARIZE compatible with requirejs, that would be good - perhaps we can add a flag for that?
