### ISSUE TITLE
[announce] The bf library - way to interactive console

### ISSUE THREAD

**Issue by podsvirov** [emscripten-core/emscripten#6928]
# bf - buffered formatted input/output

This is a very small and lazy C library writen by Konstantin Podsvirov
to create interactive examples for his [book].

All the work with formatted input and output is performed by standard
[scanf] and [prinntf] functions, and behind the screen works [curses].

## Source code

Source available at [github].

## Code sample

```c
#include <bf.h>

int main() {
  bfhi(); // hello bf
  char name[32];
  int running = 1;
  do {
    bfcs(); // clear screen
    bfo(0, "Enter your name and press {Enter}: "); // buffered output
    if (bfi(1, "%s", name) == 1) { // like scanf
      bfo(2, "Hello, %s!", name); // like printf
      running = 0;
    }
    bffs(); // fill screen
  } while (running);
  bfbi(); // bye bf
  return 0;
}
```

## Living preview

Launch the above code in your browser [just now](https://podsvirov.github.io/bf/hello.html)!

## Documentation

Online documentation available [there](https://podsvirov.github.io/bf/).

[github]: https://github.com/podsvirov/bf
[book]: http://book.podsvirov.pro
[scanf]: https://en.cppreference.com/w/c/io/fscanf
[prinntf]: https://en.cppreference.com/w/c/io/fprintf
[curses]: https://en.wikipedia.org/wiki/Curses_(programming_library

**Comment by podsvirov** [comment]
Hello @kripken, what your think about this?

**Comment by kripken** [comment]
Interesting, so does this basically connect ncurses to printf/scanf? What's the main work done here to connect those two?

**Comment by podsvirov** [comment]
General problema in porting classic console applications to emscripten platform is the blocked input. The `scanf` method block current thread before user type the Enter key.
In the `bf` library all methods is non-bloking and return control immediate.
We can accumulate intermediate state in the character buffer and the use is his when this is needed.
Then we can render console application frame by frame as we do for graphical application.
The `bf` library compatible with classic `ncurses` implementation of the `curses` API, but for `emscripten` platform we can use `PDCurses` implementation based on the `SDL` API.

**Comment by podsvirov** [comment]
On the main page I deceived everyone. Here is the real code for the platform:
```c
#include <bf.h>

#include <emscripten.h>

static char name[32];
static int running = 2;

void frame()
{
    if (running) {
        bfcs();
        bfo(0, "Enter your name and press {Enter}: ");
        if (bfi(1, "%s", name) == 1) {
          bfo(2, "Hello, %s!", name);
          running--;
        }
        bffs();
    } else {
        bfbi();
        emscripten_cancel_main_loop();
    }
}

int main() {
  bfhi();
  bfas(1);
  emscripten_set_main_loop(frame, 0, 1);
  return 0;
}
```

**Comment by kripken** [comment]
I think I see, so this is a non-blocking API? But I see an "infinite loop" in the example here (`do .. while (running)`) - how does that work?

**Comment by podsvirov** [comment]
On main page I put sample code for desktop application.
The [hello.c](https://github.com/podsvirov/bf/blob/develop/examples/hello.c) for `emscripten` platform that I use for living preview.

**Comment by kripken** [comment]
I see now, thanks. Very cool!
