### ISSUE TITLE
WORKERFS: Blob usage slow on Chrome

### ISSUE THREAD

**Issue by sehugg** [emscripten-core/emscripten#6955]
On Chrome, reading from a WORKERFS node is very slow. Profiling reveals that Blob.slice() and readAsArrayBuffer() take several msec per call.

The following is a workaround, replacing stream_ops.read with a function that converts stream content Blobs to typed arrays and caches them:

    var WORKERFS = FS.filesystems['WORKERFS'];
    var reader = WORKERFS.reader;                                                                                                                                             
    var blobcache = {};                                                                                                                                                       
    WORKERFS.stream_ops.read = function (stream, buffer, offset, length, position) {                                                                                            
      if (position >= stream.node.size) return 0;                                                                                                                               
      var contents = blobcache[stream.path];                                                                                                                                    
      if (!contents) {                                                                                                                                                            
        var ab = reader.readAsArrayBuffer(stream.node.contents);                                                                                                                  
        contents = blobcache[stream.path] = new Uint8Array(ab);                                                                                                                 
      }                                                                                                                                                                         
      if (position + length > contents.length)                                                                                                                                    
        length = contents.length - position;                                                                                                                                    
      for (var i=0; i<length; i++) {                                                                                                                                               
        buffer[offset+i] = contents[position+i];                                                                                                                                
      }                                                                                                                                                                         
      return length;                                                                                                                                                          
    };

On Chrome it speeds my application by 50-100x. This seems a bit faster on Firefox too, maybe 2x.

Using typed arrays instead of Blobs for stream contents might be better overall, since the only way to select data from a Blob is slice() which requires an array creation for every read().

**Comment by kripken** [comment]
Interesting that this speeds things up so much! It would take more memory, though, wouldn't it?

A 50x speedup might be worth the extra memory, but I'm not sure a 2x one would. I'd suggest filing an issue on the Chromium bug tracker to see why Chrome is so slow on this - hopefully that can be fixed there.

**Comment by kripken** [comment]
Memory-wise, I believe a typed array will always take up memory, while a Blob might be on disk or otherwise not be completely resident. That's actually one main reason for WORKERFS using Blobs. But, we should re-measure that, it's been a few years since it's been written, and the Chrome speed difference you found is definitely something we need to look into.

**Comment by thewtex** [comment]
Just a note that I also independently encountered >10X slowdown with WORKERFS vs MEMFS.
