### ISSUE TITLE
Request: Make WASM toolchain warn on double->int conversions?

### ISSUE THREAD

**Issue by rspq** [emscripten-core/emscripten#6958]
I just lost a nontrivial amount of dev time to an implicit double->int conversion sometimes overflowing and causing a runtime exception ("Error: Out of bounds Trunc operation").

Would it be possible to add a compiler warning for this?

Also, having now discovered BINARYEN_TRAP_MODE I'd personally prefer the ability to address the issue case by case, perhaps via some new __builtin functions.

**Comment by kripken** [comment]
Sorry about that, yeah, this is a tricky subject.

In the long term, wasm is adding non-trapping variants of the conversions, which we'll use by default. Meanwhile, though, we should do what we can do make this less confusing.

Not sure we can add a compiler warning on this - it would show up all the time, so it would have to be off by default, limiting it's usefulness. We can improve the docs though, to mention the error messages people might see, so they find the answer more quickly. I added the one you mentioned now.

Adding builtins is an interesting option.
