### ISSUE TITLE
What about python C extension in js?  

### ISSUE THREAD

**Issue by fduxiao** [emscripten-core/emscripten#6980]
I'd like to try to build web frontend with languages other than javascript, and I think C++ is to difficult for the whole team to use. My desired solution is to write with [cython](http://cython.org/), python and C/C++. Then I have to consider how to build an extension for python in web. Since it requires dynamic loading a shared object, how should I do it?
Will you consider adding a loader for `dynamic link` across web with current file system support?

**Comment by kripken** [comment]
Emscripten supports dynamic linking of shared objects. There is even a project using it with Python, and also includes bindings between C, Python and JS: https://github.com/iodide-project/pyodide

For dynamic linking in general in emscripten, you can also look at the `dyfcn*` and `dylink*` tests in the test suite for examples.
