### ISSUE TITLE
"Calling stub instead of sigaction()" when running emscripten-compiled SDL2 code 

### ISSUE THREAD

**Issue by LaurentiuGabriel** [emscripten-core/emscripten#6987]
Hello,

I'd like to highlight the following behavior whenever I try to run c++ code, that uses SDL2, after I compile it using emscripten. The code can be found here: https://github.com/LaurentiuGabriel/sdl-app/tree/master/sdl-app/src. 
The command with which I compile the code is: 

./em++ ../../../sdl-app/src/main.cpp ../../../sdl-app/src/Particle.cpp ../../../sdl-app/src/Swarm.cpp ../../../sdl-app/src/Screen.cpp -s USE_SDL=2 -o sdl2_wasm.html --emrun

Everything is compiled successfully, but when I try to run this command:

./emrun.py sdl2_wasm.html --verbose

The browser opens, the status is changed from Preparing to Running, but nothing actually happens. The page also becomes unresponsive after a while. In console, the following is printed:

Executing /usr/bin/xdg-open http://localhost:6931/sdl2_wasm.html?--verbose
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Created new window in existing browser session.
Calling stub instead of sigaction()
Calling stub instead of sigaction()
Calling stub instead of sigaction()

I have also cleared cache and ports several times, I tried WASM=0 and WASM=1 arguments as well, but I still get the same results. 

Do you have any ideas of why this happens?

Thanks!

**Comment by kripken** [comment]
It might help to start with a smaller SDL2 program. For example look at `test_sdl2_image` in `tests/test_browser.py`, and there are a lot of other sdl2 tests there, that are all known to pass.

That `sigaction` warning may be important - signals are not actually supported on the web, so the question is whether your app uses them in an important way.

Regarding the app becoming unresponsive, have you converted the main loop to an event-based one? See https://kripken.github.io/emscripten-site/docs/porting/emscripten-runtime-environment.html#implementing-an-asynchronous-main-loop-in-c-c
