### ISSUE TITLE
No way to bind simple function with RTTI deactivated

### ISSUE THREAD

**Issue by hugoam** [emscripten-core/emscripten#7001]
I'm trying to bind a simple function that takes an `std::string` as an argument.

```
#include <emscripten/bind.h>
using namespace emscripten;

void paste(std::string text);

EMSCRIPTEN_BINDINGS(shell) {
	function("paste", &paste);
}
```

- It simply doesn't compile with RTTI deactivated.
- If I set `EMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0` in my compiler defines, it compiles, but I get an error at runtime: `UnboundTypeError: Cannot call paste due to unbound types: emsc, emsc`

Documentation about **what** is an unbound type in emscripten jargon, or about rtti needing to be activated to use embind, is as far as I can tell nonexistent.
I have no idea why calling that function would use an "unbound type" ? And neither what `emsc` type is.

It's good to note this page: https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html doesn't contain one single mention of RTTI

**Comment by chadaustin** [comment]
@hugoam Can you offer some more context? Were you using emcc with embind enabled and passing -fno-rtti anyway? What were the compile errors?

Glancing at the code, it looks like someone (me?) has tried to make embind work with rtti disabled, but it's possible that's rotted.

The nonsensical "emsc" type makes sense - if you disabled RTTI, the compiler would not have generated useful type names in the executable.

**Comment by smbape** [comment]
After one year, I hope my comment will still reach authors and contributors.
I came across runtime errors after compiling a library and I isolated some failing test cases hoping it will help to solve the issue.

With `-DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0`,

`em++.bat main.cpp  -Wall -Werror -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 --bind -o unbound_type.js && node unbound_type.js`

`em++.bat main.cpp  -Wall -Werror -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 --bind -DCLASS_BIND -o unbound_type.js && node unbound_type.js`

`em++.bat main.cpp  -Wall -Werror -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 --bind -o unbound_type.js && node unbound_type.js`

`em++.bat main.cpp  -Wall -Werror -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 --bind -DCLASS_BIND -o unbound_type.js && node unbound_type.js`
  - bound void functions will fail
  - bound class methods will fail
  - bound non-void functions involving structures/classes bound as `value_object` will pass

Without `-fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0`,

`em++.bat main.cpp  -Wall -Werror --bind -o unbound_type.js && node unbound_type.js`

`em++.bat main.cpp  -Wall -Werror --bind -DCLASS_BIND -o unbound_type.js && node unbound_type.js`
  - bound void functions will pass
  - bound class methods will pass
  - bound non-functions involving structures/classes bound as `value_object` will pass

**Comment by sbc100** [comment]
Is this the same issue as: https://github.com/emscripten-core/emscripten/pull/9122?

**Comment by jgravelle-google** [comment]
Yep. Verified it breaks before https://github.com/emscripten-core/emscripten/pull/9261, and is fixed with it.
Note this requires a rebuild of the emscripten cache, and the latest version (1.38.42) does not have the fix. The fix is in incoming, and should be in the next tagged release (presumably 1.38.43)
