### ISSUE TITLE
Execution breaks with an empty error message if a class method is called inside a loop

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [emscripten-core/emscripten#7009]
I've built a template C++ "stack" class with the following code:
```
#include <iostream>
#include <exception>
#include <emscripten/bind.h>
using namespace std;
using namespace emscripten;

template<class T>
class Stack {
    private:
    int size = 0;
    val *arr;

    public:
    Stack() {
        this->arr = new val(0);
    }
    
    void Push(val element) {
        val *temp = this->arr;
        this->arr = new val(this->size + 1);
        for (int i = 0; i < this->size; i++) {
            this->arr[i] = temp[i];
        }
        this->arr[this->size] = element;
        this->size++;
    }

    val Pop() {
        if (this->size == 0) {
            throw new underflow_error("Underflow eror.\nNothing to pop.");
        }
        else {
            val *temp = this->arr;
            val element = this->arr[this->size - 1];
            this->size--;
            this->arr = new val(this->size);
            for (int i = 0; i < this->size; i++) {
                this->arr[i] = temp[i];
            }
            return element;
        }
    }

    val Top() {
        if (this->size == 0) {
            throw new underflow_error("Underflow eror.\nThe stack is empty.");
        }
        else {
            return this->arr[this->size - 1];
        }
    }

    void Flush() {
        while (this->size != 0) {
            this->Pop();
        }
    }

    int Size() {
        return this->size;
    }
};

EMSCRIPTEN_BINDINGS(Stack) {
    class_<Stack<val>>("Stack")
    .constructor<>()
    .function("Push", &Stack<val>::Push)
    .function("Pop", &Stack<val>::Pop)
    .function("Top", &Stack<val>::Top)
    .function("Flush", &Stack<val>::Flush)
    .function("Size", &Stack<val>::Size);
}

int main() {
    cout << "Loaded" << endl; 
    return 0;
}
```

And then compiled it to WASM using:
```
emcc --bind -o stack.js stack.cpp
```

Now in my browser i'am loading it like this:
```
<script src="stack.js"></script>
<script>
    Module["onRuntimeInitialized"] = () => {
        let s = new Module.Stack();
        for (let i = 0; i < 20; i++) {
            s.Push(8);
        }
    };
</script>
```
And here's where the problem occurs:
When the `Push()` function is called outside a loop , everything works fine.
When the `Push()` function is called inside a loop , the script halts with the following warning messages:
![image](https://user-images.githubusercontent.com/9156333/44243526-38a2c780-a1d8-11e8-914d-3ccdc7f0c40e.png)
And this error message:
![image](https://user-images.githubusercontent.com/9156333/44243550-5a9c4a00-a1d8-11e8-8288-648abb9c3554.png)
Executing the script in the console generates the following error message:
![image](https://user-images.githubusercontent.com/9156333/44243631-d4343800-a1d8-11e8-86be-54726c08e4aa.png)

Are there anyway to fix this?
Thanks in advance

**Comment by kripken** [comment]
Not sure what went wrong here, but I'd try to build without optimizations, perhaps the assertions at `-O0` will find something. If not that, then I'd try to see if it's something to do with startup ("failed to asynchronously prepare wasm" - can try to disable async compilation, or add a setTimeout in onRuntimeInitialized just to make sure it runs in a later frame, to rule out issues there).

**Comment by Eyad-Mohammed-Osama** [comment]
@kripken thanks for your reply.
Here's what i've tried:
I've cleared the cache , then i re-compiled the C++ file using this command:
`emcc -O0 --bind -o stack.js stack.cpp -s EXPORTED_FUNCTIONS="['_main']"`
In the HTML file i've made the following modifications:
```
<script src="stack.js"></script>
<script>
    window.addEventListener("load", () => {
        Module["onRuntimeInitialized"] = () => {
            setTimeout(() => {
                let s = new Module.Stack();
                for (let i = 0; i < 20; i++) {
                    s.Push(8);
                }
            }, 4000);
        };
    });
</script>
```
All warning messages has disappeared , and i'm left with this one error message:
![image](https://user-images.githubusercontent.com/9156333/44435285-eb4b9f00-a5b7-11e8-8eff-950d74250c2e.png)
