### ISSUE TITLE
SharedArrayBuffer is supported, but HEAPU32 is backed by ArrayBuffer

### ISSUE THREAD

**Issue by prideout** [emscripten-core/emscripten#7018]
I know I'm using a version of Chrome that supports `SharedArrayBuffer` because I can create one in the console.  I'm compiling and linking my C++ code with `-s USE_PTHREADS=1`. However `initMainThreadBlock` throws this:

```
TypeError: [object Uint32Array] is not an integer shared typed array. at Atomics.store (<anonymous>) at Object.initMainThreadBlock (http://localhost:8000/web_hellotriangle.js:1874:17) at http://localhost:8000/web_hellotriangle.js:7433:38
```
I've verified that __EMSCRIPTEN_PTHREADS__ is defined because I added the following snippet to my application code and it compiles fine:

```
#if defined(__EMSCRIPTEN__) && !defined(__EMSCRIPTEN_PTHREADS__)
#error "WASM pthreads are not enabled"
#endif
```

**Comment by prideout** [comment]
I'm using **emsdk-1.38.11-64bit**

**Comment by kripken** [comment]
Do the pthreads tests in the test suite pass for you? Like `python tests/runner.py browser.test_pthread_atomics`. Also worth testing in firefox nightly (the tests are known to pass there, with the shared_memory flag set - they pass on our CI).

See also https://github.com/WebAssembly/binaryen/issues/1419

**Comment by prideout** [comment]
I did a search In the emscripten repo and I see `new SharedArrayBuffer` at [this line](https://github.com/kripken/emscripten/blob/d828e76752f95c65116158791694f557a3342cc5/src/preamble.js#L1133), which is only active when WASM is false.

The unit tests fail for me but probably for an unrelated reason:

```
test_pthread_atomics (test_browser.browser) ... error: failure to process js library "library_html5.js": TypeError: Cannot read property '0' of undefined,,TypeError: Cannot read property '0' of undefined
    at getFastValue (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:1156:10)
    at calcFastOffset (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:1196:10)
    at makeSetValue (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:983:16)
    at eval (eval at <anonymous> (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8)), <anonymous>:1:2)
    at eval (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:12:15)
    at String.replace (<anonymous>)
    at processMacros (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:10:15)
    at Object.load (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:178:21)
    at JSify (eval at globalEval (/Users/prideout/github/emscripten/src/compiler.js:105:8), <anonymous>:87:20)
    at library_html5.js (/Users/prideout/github/emscripten/src/compiler.js:221:3)
```

Yes, the WebAssembly ticket that you referenced seems similar or equivalent to what I'm seeing.

**Comment by kripken** [comment]
Running `./emcc --clear-cache` may fix that test error (something needs to be rebuit for a recent incoming change).

Also relevant here is that I believe chrome enables SAB, but not wasm threads - there is a separate flag. Does building with `-s WASM=0` make it work? (that is what is tested on the bots, although there is work happening right now to add wasm testing)

**Comment by prideout** [comment]
Thanks for your attention!  Yes, I was able to get WASM=0 to work with threads.

In the WASM=1 case, I have verified in the Chrome Debbuger that the backing array of HEAPU32 is indeed an ArrayBuffer rather than a SAB.  Where in the emscripten codebase does it create a SAB when WASM is enabled?

**Comment by kripken** [comment]
That code is in `src/preamble.js`, can search for `SharedArrayBuffer` there. But for wasm I think the relevant code is where we create a Memory with `'shared': true` (around line 1187).

Looks like after we do that, we do `buffer = Module['wasmMemory'].buffer;`. Perhaps the browser doesn't return a `SharedArrayBuffer` there? If so that sounds like a browser bug.

**Comment by kripken** [comment]
Oh ok, looking into this it seems like that happens in Chrome - with SAB enabled but not wasm-threads, creating a shared Memory leads to a non-shared memory, and I see the same error as you. I opened #7023 with a proper assertion for this.

If you change the chrome flag does it work?

**Comment by wffurr** [comment]
If I enable the Chrome flag for WebAssembly shared memory, everything works as expected, but in the default configuration the fallback path doesn't work.

Instead of asserting and failing, it would be extremely helpful to have a graceful fallback ala https://github.com/kripken/emscripten/pull/3705/commits/336b7a920cac2543e013d7be2aa45efe0b07ccd2.

Those fallbacks don't work through in the case that SharedArrayBuffer and Atomics are defined, but WebAssembly shared memory is disabled (the default behavior in Chrome 69).  Even if I disabled SharedArrayBuffer, loading still fails on Atomics.store because the single-threaded polyfills were never installed.
