### ISSUE TITLE
other.test_llvm_nativizer fails on Windows.

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#702]
Running the test other.test_llvm_nativizer on Windows gives the following error

http://clb.demon.fi/dump/emscripten_temp/other_test_llvm_nativizer/stderr.txt

The intermediate output files are at 

http://clb.demon.fi/dump/emscripten_temp/other_test_llvm_nativizer/

**Comment by juj** [comment]
Took a peek at this and #709 again, but I am not sure what is going wrong here. It looks like the disassembled code listing from `as` is not compatible with what clang wants to read. Added a bit more validation to `tools/nativize_llvm.py` and skipped these tests on the bots for now.

**Comment by kripken** [comment]
It's fine to skip these permanently, this tool is really just for extreme debugging by very few people.
