### ISSUE TITLE
Can't get keyboard input with SDL and a textbox with text entry working together on the same HTML page

### ISSUE THREAD

**Issue by smlehbleh** [emscripten-core/emscripten#7043]
Hello,
The default behaviour of an SDL window with emscripten causes any HTML elements with text entry to not work.

In my emscripten C++ I can totaly disable SDL input using:
 SDL_EventState(SDL_TEXTINPUT, SDL_DISABLE);
 SDL_EventState(SDL_KEYDOWN, SDL_DISABLE);
 SDL_EventState(SDL_KEYUP, SDL_DISABLE);
which gets the text entry working.

but surely theres a way to receive SDL input events but also keep text entry working on the page?

Cheers
Russell

**Comment by Apivan** [comment]
Hi, I faced the same problem.  My workaround was to modify the output js and html like this.

https://github.com/Apivan/webasm_focus_then_consume_keypress/commit/b13b40e2e5c8020e6a965995504af3909a47c382

**Comment by Apivan** [comment]
![peek 2019-01-28 16-46](https://user-images.githubusercontent.com/8325019/51827756-acff9c00-231c-11e9-8514-0b210d79e409.gif)

**Comment by qunying** [comment]
I face the same issue, is it still no elegant solution for this?

**Comment by gregoiregentil** [comment]
+1. I'm facing the same issue in LVGL ported to web. See https://github.com/lvgl/lv_web_emscripten/issues/32.
