### ISSUE TITLE
Failure loading large file into IDBFS

### ISSUE THREAD

**Issue by ndarilek** [emscripten-core/emscripten#7050]
Using Emscripten 1.38.11, I am unable to load a large (3.2G) file into idbfs. I get an "Out of memory" exception and an OOM dump, attached here. I'm not smart enough to know if this contains sensitive information, so please let me know if it does and I'll remove it immediately.

My code processes a file from a `<input/>` element, iterates over it using `FileReader`, slices it into 10M chunks, and writes them to a file stored in IDBFS. If I remove all Emscripten code (I.e. anything that touches a stream) the code works without hitting the OOM killer, so the issue doesn't seem to be with my slicing of the large file in JS.

I'll include sample code below that opens the stream in append mode, writes a 10M chunk to it, then closes it on each call to `FileReader.onload`. This is an iteration on my initial attempt which didn't do this, but which still exhibited the same error.

I'm pretty sure my code is writing to IDBFS, because when I reload the app, I still see the file present where the upload failed. So clearly I'm persisting data outside of RAM.

I'm wondering if Emscripten just isn't tuned for large files? Is an entire file read into RAM even though its physical bytes may get persisted? Or is something not being cleaned up? Maybe I'm misunderstanding how file access is meant to work.

Thanks! Here's my code. This is compiled using Rust/cargo-web, so you'll see a couple variable tags mapping Rust references to JS. Otherwise it's pure JS.

```
                    let filename = @{fh.to_str().unwrap()};
                    let element = document.querySelector("#import");
                    let file = element.files[0];
                    let size = file.size;
                    let chunk_size = 1024*10000;
                    let offset = 0;
                    let reader = new FileReader();
                    let counter = 0;
                    reader.onloadend = function() {
                        let stream = FS.open(filename, "a");
                        if(reader.error) {
                            FS.close(stream);
                            FS.unlink(filename);
                            return console.error(reader.error);
                        }
                        console.log("onload ", offset);
                        let result = new Uint8Array(reader.result);
                        FS.write(stream, result, 0, result.length);
                        offset += result.length;
                        FS.close(stream);
                        counter++;
                        FS.syncfs(function(err) {
                            if(err)
                                return console.error(err);
                            if(offset >= file.size)
                                return;
                            read();
                        });
                    };
                    function read() {
                        var blob = file.slice(offset, offset+chunk_size);
                        reader.readAsArrayBuffer(blob);
                    }
                    read();
```

[oom.json.gz](https://github.com/kripken/emscripten/files/2324638/oom.json.gz)

**Comment by ndarilek** [comment]
FWIW, I've reimplemented my file write logic almost entirely in Rust with almost the same results, though this time I get a JS stacktrace instead of just an "out of memory" error. Here is my stacktrace if it helps, though it looks like the `write` call is what's triggering the OOM:

```
out of memory waynav.js:10742:5
out of memory waynav.js:10743:5
uncaught exception: abort("out of memory") at jsStackTrace@http://localhost:8000/waynav.js:1811:13
stackTrace@http://localhost:8000/waynav.js:1828:12
abort@http://localhost:8000/waynav.js:10753:44
___syscall4@http://localhost:8000/waynav.js:6594:69
_write@http://localhost:8000/waynav.js:8599817:1
__ZN48__LT_std__fs__File_u20_as_u20_std__io__Write_GT_5write17hc0bbac925ac6cb29E [__LT_std__fs__File_u20_as_u20_std__io__Write_GT_::write::hc0bbac925ac6cb29]@http://localhost:8000/waynav.js:3119272:1
__ZN3std2io5Write9write_all17h9cba2244a6d2e473E [std::io::Write::write_all::h9cba2244a6d2e473]@http://localhost:8000/waynav.js:1813232:1
dynCall_viiii@http://localhost:8000/waynav.js:9098356:1
Module.dynCall_viiii@http://localhost:8000/waynav.js:10402:10
invoke_viiii@http://localhost:8000/waynav.js:9336:5
__ZN59__LT_waynav__web__Model_u20_as_u20_yew__html__Component_GT_6update28__u7b__u7b_closure_u7d__u7d_17h8f55488827b5daf9E [__LT_waynav__web__Model_u20_as_u20_yew__html__Component_GT_::update::__u7b__u7b_closure_u7d__u7d_::h8f55488827b5daf9]@http://localhost:8000/waynav.js:1682742:1
__ZN76__LT_F_u20_as_u20_stdweb__webcore__callfn__CallMut_LT__LP_A12_C__RP__GT__GT_8call_mut17hef3026f80bc71235E [__LT_F_u20_as_u20_stdweb__webcore__callfn__CallMut_LT__LP_A12_C__RP__GT__GT_::call_mut::hef3026f80bc71235]@http://localhost:8000/waynav.js:1680948:1
dynCall_vii@http://localhost:8000/waynav.js:9098179:1
Module.dynCall_vii@http://localhost:8000/waynav.js:10374:10
invoke_vii@http://localhost:8000/waynav.js:9259:5
__ZN199__LT_stdweb__webcore__newtype__Newtype_LT__LP_stdweb__webcore__serialization__FunctionTag_C__u20__LP_A12_C__RP__RP__C__u20_F_GT__u20_as_u20_stdweb__webcore__serialization__FuncallAdapter_LT_F_GT__GT_15funcall_adapter17h427bf57487c7eae1E [__LT_stdweb__webcore__newtype__Newtype_LT__LP_stdweb__webcore__serialization__FunctionTag_C__u20__LP_A12_C__RP__RP__C__u20_F_GT__u20_as_u20_stdweb__webcore__serialization__FuncallAdapter_LT_F_GT__GT_::funcall_adapter::h427bf57487c7eae1]@http://localhost:8000/waynav.js:1928814:1
dynCall_vii@http://localhost:8000/waynav.js:9098179:1
Module.dynCall_vii@http://localhost:8000/waynav.js:10374:10
dynCall@http://localhost:8000/waynav.js:1138:12
Module.STDWEB_PRIVATE.dyncall@http://localhost:8000/waynav.js:768:12
output@http://localhost:8000/waynav.js:494:13
```

**Comment by kripken** [comment]
I'm not sure. In practice, though, IDB memory limits are definitely browser-specific. See for example work here to split up files to work around Chrome limitations:

https://github.com/kripken/emscripten/pull/6934

However, the error you see isn't an IDB error directly - that might be an IDB error reported oddly, or it could be a browser bug. Btw, might be interesting to see what the browser devtools memory analysis tools say - if there isn't anything there justifying an OOM, then it sounds even more like a browser bug.

**Comment by kripken** [comment]
Sorry, I should have been more clear, I meant the memory devtool - in firefox control-shift-K, in chrome control-shift-J, each has a "memory" tab, that can scan the JS heap and give very useful info.

**Comment by jazarforcite** [comment]
Hello ndarilek, were you able to find a solution to your problem? I'm trying to do the same. Seems to be that idbfs is using uint arrays to store the files and the limitation are due to browsers limiting the size of the uint arrays.

**Comment by ndarilek** [comment]
I gave up, but am still interested in continuing that particular project 
someday. Please let me know if you make any progress.

**Comment by jazarforcite** [comment]
hehehe yeah i figured! it's a shame, i'm not giving up. yes will let you know if it works out.
