### ISSUE TITLE
both async and sync fetching failed 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [emscripten-core/emscripten#7063]
while running hello.html produced by emcc I get this error 

<img width="1391" alt="screen shot 2018-08-29 at 2 50 19 pm" src="https://user-images.githubusercontent.com/8083613/44779526-550e0f00-ab9d-11e8-8374-579c70c78f28.png">

**Comment by kripken** [comment]
The devtools may show more information. But I'd guess it's Chrome's limitation on loading `file://` urls - you need to run a webserver, see the note in this section: http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html#generating-html
