### ISSUE TITLE
val::operator() with pointer as argument

### ISSUE THREAD

**Issue by isc30** [emscripten-core/emscripten#7084]
I'm trying to avoid the need of JS users calling `.delete()` on the API by accepting lambdas as actions that work with the objects:

```cpp
EMSCRIPTEN_BINDINGS()
{
    function("using_x", optional_override([](val action)
    {
        X x; // C++ constructs `x`
        action(x); // JS uses `x`
        // C++ destroys `x`
    }));
}
```

The idea is to use it like this:

```js
Module.using_x(x => x.something()); // C++ destroys the object internally
```

I realized that embind is copying the object every time I pass it as a parameter, so I tried passing the ptr to `x`:

```cpp
action(&x);
```

The compiler complains: "Implicitly binding raw pointers is illegal. Specify allow_raw_pointer<arg<?>>"

I see no way of specifying policy in this case.

Is it possible to pass pointers into `val::operator()`?
How can I achieve managing memory from C++ and calling JS actions like this in an easy way?
Am I wrong in my assumption that this design would help defining the proper ownership of those objects?

Thanks a lot

**Comment by isc30** [comment]
Just discovered a workaround: explicitly crafting the `emscripten::val` from the pointer:
```cpp
emscripten::val ptr{&x};
action(ptr);
```

**Comment by isc30** [comment]
Okay, looks like I found a workaround:
> if the pointer is a lvalue, it works properly

```cpp
X x;
X* ptr = &x;
action(ptr);
```

**Comment by chadaustin** [comment]
That's... scary. I feel like that shouldn't work. :D What happens when JavaScript grabs a long-lived reference to the value and tries to run it later?

This sounds related to #7292 to me. cc @mejedi

**Comment by isc30** [comment]
I don't consider it a bug. Being able to do this opens many doors when talking about memory management from the C++ side when exposing objects to js.
I wrote a small article about this topic and how you can benefit from such constructions: https://blog.codeisc.com/2018/09/15/xlnt-wasm-bindings.html#avoiding-exposed-ownership
