### ISSUE TITLE
EMSCRIPTEN_FETCH_STREAM_DATA fails on chrome

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#7090]
The following line is used to set the `responseType`:

`xhr.responseType = fetchAttrStreamData ? 'moz-chunked-arraybuffer' : 'arraybuffer';`

Since `moz-chunked-arraybuffer` is not supported on chrome this line ends up setting responceType to `''` which then confuses the later code which expects it to be an arraybuffer.

The fix I have working is to only try to use `moz-chunked-arraybuffer` on firefox and on chrome fall back to arraybuffer.  This result is that the data is not actually streamed but all arrives in the final onprogess callback.

The alternative would simply be to fail with some kind of unsupported error on non-firefox browsers when the user tries to use `EMSCRIPTEN_FETCH_STREAM_DATA`. I think I prefer the former fix.

**Comment by VirtualTim** [comment]
Just ran into this and it's a bit annoying. I've created a PR to update the documentation.
Personally I think that whatever we decide to do with this we need to spit out a console warning to inform people that the data is not actually streaming, otherwise the behaviour will confuse people.
