### ISSUE TITLE
Question about pthreads and offscreen canvas support - getting errors about control transfer in Chrome 69

### ISSUE THREAD

**Issue by sortofsleepy** [emscripten-core/emscripten#7097]
👋 

Hello!

I'm trying to explore possibilities for using the OffscreenCanvas support in Emscripten now that Chrome supports OffscreenCanvas. I am however running into a few issues, looking on Google, it seems either no one else is running into this issue and I'm not quite awake yet or maybe something new might have been introduced. 

* The first error I'm getting is 
```failed to transfer control of canvas "canvas" to OffscreenCanvas! Error: InvalidStateError: Failed to execute 'transferControlToOffscreen' on 'HTMLCanvasElement': Cannot transfer control from a canvas that has a rendering context.```

From what I understand, the canvas element with the id "canvas" refers to the default canvas Emscripten creates. 

* If I add my own canvas I get a different error 
```failed to transfer control of canvas "#testcanvas" to OffscreenCanvas! Error: TypeError: document.getElementByID is not a function``` 

I've heard Firefox Nightly has support but unfortunately I cannnot try it out on the computer I'm using currently cause I don't have admin access(work computer)

Any ideas? I'm thinking I'm forgetting something dumb but at the moment I'm not sure what. According to the spec, from what I can see, not being able to transfer from a canvas element with a context attribute is defined as known behavior but I'm not sure why things still fail if I try to supply my own canvas. 

Any help is appreciated!

__Code__

```c++
#include <stdio.h>
#include <string.h>
#include <pthread.h>
#include <GLES2/gl2.h>
#include <math.h>
#include <assert.h>
#include <emscripten/emscripten.h>
#include <emscripten/html5.h>
#include <emscripten/threading.h>
#include <bits/errno.h>
#include <stdlib.h>
void* threadFunc(void* arg)
{

	const EmscriptenWebGLContextAttributes attr = {
		.alpha = 1,
		.depth = 1,
		.stencil = 1,
		.antialias = 1,
		.explicitSwapControl = 1,
		.majorVersion = 2,
		.minorVersion = 0,
	};

	EMSCRIPTEN_WEBGL_CONTEXT_HANDLE context = emscripten_webgl_create_context("#canvas", &attr);
	if (context == 0) {
		printf ("error can't create context\n");
	}
	if (emscripten_webgl_make_context_current(context) != EMSCRIPTEN_RESULT_SUCCESS) {
		printf("error can't make context current\n");

	}


  EMSCRIPTEN_RESULT r = emscripten_webgl_commit_frame();
   assert(r == EMSCRIPTEN_RESULT_SUCCESS);
}
int main(){
    pthread_t pth;
    pthread_attr_t attr;
   pthread_attr_init(&attr);
   emscripten_pthread_attr_settransferredcanvases(&attr, "#canvas");
   int rc = pthread_create(&pth, &attr, threadFunc, 0);

  return 0;
}
```

**Comment by sortofsleepy** [comment]
@kripken thanks for chiming in!

Updated to 1.38.12 and still running into the same errors 😢 . 

Unfortunately `runner.py` doesn't work in Windows from what I can gather and I can't install the Linux subsystem on this machine(apologies I should have mentioned that I was using Windows in my initial post) 

I took a look through the `tests` folder and tried running 
* `gl_only_in_pthread.cpp`
* `gl_in_pthread.cpp`
* `gl_in_mainthread_after_pthread` 

as they all seemed relevant. Is one of those the file that gets run by chance? 

I will try to find the time to run the test script on my own machine at some point.

**Comment by kripken** [comment]
Hmm, runner should work on windows as long as you have python installed, I think. But, you don't need it, can just search for that test name in `tests/test_browser.py` and you can find the source file it compiles + the exact arguments it uses, and then do that manually.

**Comment by sortofsleepy** [comment]
Ah yea, I figured that was the case so I just tried all the relevant looking files(I didn't know runner would point to `test_browser.py`);  looks like I did happen to run the file the test runs. Tried again to make sure with the same flags, still a no-go. 

I will keep digging

side note about `runner.py` - keep getting error `'module' object has no attribute 'geteuid'`, I've tried python 2.7 and 3.6
