### ISSUE TITLE
emmake can't be used in a path with spaces anymore

### ISSUE THREAD

**Issue by elvissteinjr** [emscripten-core/emscripten#7103]
$(CC) in a makefile expands to "python [full path]", with the path not being in quotes or escaped. 
For example: "python D:\Program Files\Emscripten\emscripten\1.38.12\emcc.py"

Paths with spaces are usually said to be not a good idea, but this used to work. Program Files even was the default location in the old Windows installers if I remember correctly.
Moving the SDK is an obvious fix on the user end. Using quotes for the path or just "emcc" instead in the resulting command seems to work in my environment.

**Comment by kripken** [comment]
Hmm, no ideas offhand of what could have regressed this. It would be good to bisect to the breaking commit (or at least version).
