### ISSUE TITLE
-wpedantic reports erroneous warning for parameters in EM_ASM_ blocks

### ISSUE THREAD

**Issue by aaron-michaux** [emscripten-core/emscripten#7113]
Compiling the following code should work without warning. Even in `pedantic` mode.

```
#include <emscripten.h>

int main(int, char * *)
{
    int x = EM_ASM_INT({
            console.log('I received: ' + $0);
            return $0 + 1;
        }, 100);
    printf("%d\n", x);
    return 0;
}
```

However, emcc reports the following warning:

```
~ > emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.38.8 (commit 1c100d9f8ad4e073b33d64aed2fdf91cbc355cb3)

~ > emcc -x c++ -std=c++17 -stdlib=libc++ -DTARGET="ariel.html" -Wall -Wextra -Wpedantic test.cpp 
test.cpp:7:42: warning: '$' in identifier [-Wdollar-in-identifier-extension]
            console.log('I received: ' + $0);
                                         ^
test.cpp:8:20: warning: '$' in identifier [-Wdollar-in-identifier-extension]
            return $0 + 1;
                   ^
2 warnings generated.
```

**Comment by aaron-michaux** [comment]
I'm not sure of the moving parts, but maybe the $0 variable can be mangled as it is written out? Regardless, using the `-Wno-dollar-in-identifier-extension` switch turns off the warning, so perhaps the entire issue is `-pedentic` =).

**Comment by kripken** [comment]
Yeah, but mangling the $0 would need to be done before clang sees it - which would be a big change, I'm afraid.

Another option is to not use `$N` for those arguments, it could be `_N` for example. That would be a breaking change, unless we supported both - so none of the options is very appealing, sadly.

**Comment by aaron-michaux** [comment]
Suppose it would cause other problems with emcc supported both `$N` and `_N`. I think a lot of people use `_` at the beginning of their variable names even though I believe it is reserved. Maybe `__arg_N` would be more obvious. I'm not sure I should be making a recommendation, but those are my thoughts.
