### ISSUE TITLE
emcc give us a .data file but this file can be only loaded by firefox nightly never works on google chrome

### ISSUE THREAD

**Issue by gogogous88** [emscripten-core/emscripten#7115]
i have 4 files after emcc -Os foo.c -s Wasm=1 -o foo.html:

they are : 
foo.data 
foo.wasm 
foo.js 
foo.html

the foo.html can only work under firefox nightly but cannot work on chrome condtion:

the console says in chrome:
[post-exception status] Downloading data... 

any idea how can i solve this problem to make it work in chrome? thank you

**Comment by kripken** [comment]
Check in the chrome devtools, the network tab may show why the file isn't being loaded.

One possibility is if you are using a `file:///` URL, then firefox will load the data file but chrome will not (so you need to use a local webserver).

**Comment by chris-ray** [comment]
For me, the .js file attempts to load the .data file from `/` instead of the url path where the .js file was loaded from.

**Comment by gogogous88** [comment]
thank you all
