### ISSUE TITLE
browser.test_aniso fails intermittently on chrome

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7117]
For example https://circleci.com/gh/kripken/emscripten/38543?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The test is deterministic, so that's odd.

Perhaps we should disable it for now?

cc @sbc100

**Comment by sbc100** [comment]
Yes, if its flaky lets disable it and include a link to this bug.
