### ISSUE TITLE
JS functions in wasm tables

### ISSUE THREAD

**Issue by jgravelle-google** [emscripten-core/emscripten#7120]
Looking at EMULATED_FUNCTION_POINTERS in settings.js, I saw a curious note:
> However, Tables have some limitations currently, like not being able to assign an arbitrary JS method to them, which we have yet to work around.

So I figured we could work around this by creating a wrapper wasm module that just exports an imported JS function, making it a wasm function, and thus suitable to put in a wasm table. Trying it out, this seems to work.
Prototype: https://gist.github.com/jgravelle-google/4e3015e23ebb68414461ba0b0f33f9aa

We need to generate the wasm module dynamically, because the type signature of the imported function needs to match. We also need users to specify a signature, which we conveniently already warn on / require in `addFunction` because of the wasm backend.
If this seems at-all sane, I can open a PR that integrates this.

**Comment by kripken** [comment]
Sounds great!

Side note, I wish we had an alternative to creating the wasm in binary form, like if browsers accepted the text form as input. For stuff like this, and JITs in general, that could have been useful, but oh well.

**Comment by jgravelle-google** [comment]
Incidentally, I had looked at https://github.com/WebAssembly/design/issues/1206 recently and was thinking of strawman-suggesting "what if we included wasm-as.js" (or wat2wasm.js), but that's probably substantially worse than just doing it inline like this. For now.

If we need more of this it would be useful to abstract away binary creation in some helper library, maybe one of those tools?

**Comment by kripken** [comment]
Yeah, a tiny JS library for wasm binary generation could be useful, compiled binaryen and wabt are overkill for that use case. On the other hand though as wasm gets more complicated (GC, SIMD, etc.) even a tiny JS library may not be so tiny...

**Comment by awtcode** [comment]
@jgravelle-google , may I know what's the benefit of doing this? Will we have a smaller Wasm binary or faster inter-module calls?

**Comment by jgravelle-google** [comment]
The benefit is that we can add JS functions to wasm tables at all.
Take a look at test_core's test_add_function: https://github.com/kripken/emscripten/blob/708668e268c58f42180fe03d25f0ea773d95c09c/tests/test_core.py#L6682
We would like the following code to work:
JS:
```js
var fp = addFunction(function(x, y) {
  console.log('in JS with ' + x + ', ' + y);
  return 2 * x + y;
}, 'iii');
Module.callJS(fp);
```
C:
```c
EMSCRIPTEN_KEEPALIVE
void callJS(int (*jsFunc)(int, int)) {
  jsFunc(2, 3);
}
```
Currently, with `-s EMULATED_FUNCTION_POINTERS=1` we handle function pointers by adding them to the wasm table. The problem here is that the wasm table doesn't allow JS functions at all so this simply doesn't work.
So, the benefit of this is that this code pattern will function at all :)
It won't make the wasm binary any smaller, and it won't make a wasm->JS call any faster (if anything it adds another layer of indirection?), but it will enable calling JS via a function pointer when using EMULATED_FUNCTION_POINTERS (as opposed to RESERVED_FUNCTION_POINTERS)

**Comment by awtcode** [comment]
Thanks for the explanation @jgravelle-google :)

**Comment by sbc100** [comment]
This was done a while back now
