### ISSUE TITLE
No glutReshapeFunc() callback on browser window resizing

### ISSUE THREAD

**Issue by erik-larsen** [emscripten-core/emscripten#7133]
In the test [hello_world_gles.c](https://github.com/kripken/emscripten/blob/incoming/tests/hello_world_gles.c),
the callback registered to glutReshapeFunc() is not being called when the browser window is resized, even when using html which stretches the canvas to cover the browser window ('soft fullscreen').

Here's a live example of the problem (try resizing the browser window):
https://erik-larsen.github.io/emscripten-glut-resizable/hello_world_gles.html

And here's a fix:
https://erik-larsen.github.io/emscripten-glut-resizable/hello_world_gles_resizable.html

The fix detects canvas size changes on redraws and explicitly calls glutReshapeWindow().  This doesn't seem ideal though, as the canvas size check has to be done on every frame, plus this seems like something the GLUT implementation should handle under the hood.  As well, the SDL2 implementation does send resize window callbacks under [similar circumstances](https://erik-larsen.github.io/emscripten-sdl2-ogles2/hello_triangle.html).

I put together a repository for this issue and the workaround fix here:
https://github.com/erik-larsen/emscripten-glut-resizable

-Erik

**Comment by erik-larsen** [comment]
The problem appears to be **updateResizeListeners** is never called on browser window resize.  For comparison, when resizing the window with an SDL sample, updateResizeListeners is called via this stack: 

updateResizeListeners (hello_triangle.js:5795)
setCanvasSize (hello_triangle.js:5802)
_emscripten_set_canvas_size (hello_triangle.js:9718)
_Emscripten_HandleResize (hello_triangle.js:134253)
dynCall_iiii (hello_triangle.js:168663)
handlerFunc (hello_triangle.js:7171)
jsEventHandler (hello_triangle.js:6973)

There's no **_Emscripten_HandleResize** nor **_emscripten_set_canvas_size** in the GLUT sample, so browser resize events never make it to updateResizeListeners.

**Comment by erik-larsen** [comment]
Would a reasonable fix here involve adding

`document.addEventListener('resize', GLUT.onResize, true);`
to `_glutInit()?`   

And then do the appropriate stuff in GLUT.onResize (which does not exist yet).

**Comment by erik-larsen** [comment]
[Here](https://github.com/erik-larsen/emscripten-glut-resizable/commit/994a360aee755abe2367e8c5eff39a14e9125734#diff-4b9becdae8ad5c98f03786590cfe738e) is a proposed fix which adds an onResize handler to GLUT.

It fixes the issue in my initial tests, but I'll do some more testing around it.

Wondering if anyone sees an issue with this general approach?

The core of the fix:
```
onResize:function (event) {
        var rect = Module['canvas'].getBoundingClientRect();
         _glutReshapeWindow(rect.width,rect.height);
      }
```

**Comment by erik-larsen** [comment]
Needs to handle fullscreen properly, working on that.

**Comment by erik-larsen** [comment]
[Fix](https://github.com/erik-larsen/emscripten-glut-resizable/commit/d12d0b63aff82d51d4f5d784ef1da019f8a2f409#diff-4b9becdae8ad5c98f03786590cfe738e) for fullscreen.

Can someone review this?

**Comment by kripken** [comment]
@erik-larsen Sound good to open a pull request, we can discuss details there.
