### ISSUE TITLE
Compile C++ Lib 

### ISSUE THREAD

**Issue by geghamjivanyan** [emscripten-core/emscripten#7136]
I have a C++ lib called cryptomagic, and need JS sdk for that functionality. So what I’m doing is
```
cd cryptomagic
mkdir build && cd build
emconfigure cmake .. -DCFLAGS_CXX_FLAGS=-std=c++11
emmake make -j4
```

this compile my lib and create shared library `libcryptomagic.a`

Also I have a header file `cryptomagic_c.h` which contains all functions definitions I need from my lib.
I write a `cryptomagic.cpp` file for wrapping all functions in `cryptomagic_c.h`, so I can compile it for JS, which looks like 

```  
#include <stdio.h>
#include "emscripten.h"
#include "cryptomagic_c.h"


EMSCRIPTEN_KEEPALIVE
void * cryptomagic_new_wrapper()
{
    return cryptomagic_new(); // function from cryptomagic_c.h
}
```

and now when I'm compiling it with 

```
em++ cryptomagic.cpp -o MyWrapper.js
```
or 
```
emcc cryptomagic.cpp -o MyWrapper.js

```
I'm getting a warning

```
warning: unresolved symbol: cryptomagic_new
```

and also 

```
function _cryptomagic_new() {
  err('missing function: cryptomagic_new'); abort(-1);
  }
```
in my MyWrapper.js file, and so when I try to call `_cryptomagic_new_wrapper` get this error.

**Comment by geghamjivanyan** [comment]
Hi Marcel,
Thanks for the reply. No cryptomagic.cpp is not implementation, but wrapper
forfunctions from cryptomagic_c.h, which should be called from JS.
Implementations are in lib, which I want to compile.

**Comment by pixelherodev** [comment]
`this compile my lib and create shared library libcryptomagic.a`

If your shared library ends in .a, that might be a sign of a problem already.
