### ISSUE TITLE
Use import.meta.url in EXPORT_ES6 mode

### ISSUE THREAD

**Issue by curiousdannii** [emscripten-core/emscripten#7137]
Follow on to #5368. When in EXPORT_ES6 mode `import.meta.url` should be used. In browsers `document.currentScript` will *probably* still work, but `__dirname` will not work in Node. `import.meta.url` is supported in both, and it's cleaner and safer.

**Comment by saschanaz** [comment]
https://aremodulesready.com/ The availability for `import.meta.url` seems fairly limited yet 😢

**Comment by curiousdannii** [comment]
It was just added in Firefox 62. Edge support is still lacking. Detecting its support could be tricky?

At the very least it's needed for Node, and supported in Node.

**Comment by saschanaz** [comment]
It's tricky because `import.meta` is a special syntactic form with a keyword so unsupported browsers will throw a SyntaxError. Waiting Stage 4 makes sense, though.
