### ISSUE TITLE
Better handling for process listeners

### ISSUE THREAD

**Issue by lal12** [emscripten-core/emscripten#7143]
I am calling a wasm compiled file in node very often, this leads to an Error about max event listeners on process. The wasm javascript wrapper do's set `process.on("uncaughtException")` every time. The same goes for the `unhandledRejection` event.

I think there needs to some kind of check whether this has been set already, also thoose event listeners are not removed. I am thinking of something like: 

```
if(!global.__emscripten_running__)
  global.__emscripten_running__ = 0;
if(global.__emscripten_running__ == 0){
  process.on("uncaughtException", ...)
}
global.__emscripten_running__++;
// run process 
// ....
if(global.__emscripten_running__ == 1){
  process.off("uncaughtException",...)
}
```

Maybe removing the listener is not even neccessary, but it would be much nicer though. 

As far as I seen the emscripten JS Interface for wasm (don't know how it differs for other compile targets) really needs a restructuring, this also would involve #6659.

**Comment by curiousdannii** [comment]
Are you calling the MODULARIZE wrapper multiple times? Because from what I can see an `uncaughtException` handler is only added once when the module is first set up.

You can turn NODEJS_CATCH_EXIT off to stop this specific error being caught. But if you're calling the wrapper so many times probably other error events will cause the same problem.

**Comment by lal12** [comment]
What I did currently is setting `process.setMaxListeners(x)` appropiately.

Hmm, I am unsure how I am supposed to call it exactly, what I am doing now is:
```
const wasm = require("./dist/wasm.js");
let env = {};
    let args = opts || [];
    args = // some args
    let prog;
    env.arguments = args;
    let datas = [];
    env.preRun = [
        function(){
            // setup files in FS
        }
    ];  
    await new Promise((res,rej)=>{
        let error = false;
        env.quit = (code,err)=>{
            error = true;
            rej(err);
        };
        env.postRun = [
            function(){
                if(!error){
// ...
                    res(filesOut);
                }   
            }
        ];
        prog = wasm(env);
});
```

**Comment by curiousdannii** [comment]
Ah. Yep when you run it like that (like a program you'd call from a CLI) there's going to be a lot of redundant events. Probably Emscripten should clean up for itself after it's finished running.

Are you able to change what you're doing to export a function to call instead? If you can initialise the module once and call the individual function multiple times it won't be rebinding error handlers.

**Comment by lal12** [comment]
This is `strip` from binutils, which is a cli tool, so I cannot call an exported function like I would do in a library. Probably I could call main, I already tried that, but I couldn't get that to work properly...
