### ISSUE TITLE
Unexpected result of combining -s EMULATED_FUNCTION_POINTERS=1 and -g4

### ISSUE THREAD

**Issue by kumpera** [emscripten-core/emscripten#7149]
When using the two at the same time all indirect functions get exported, which is sort of unexpected.

**Comment by kripken** [comment]
That's odd, do you have a testcase? When I try
```
./emcc tests/hello_libcxx.cpp -s EMULATED_FUNCTION_POINTERS=1
./emcc tests/hello_libcxx.cpp -s EMULATED_FUNCTION_POINTERS=1 -g4
```
I see no difference in the exports in the wasm file. (Also no difference when comparing to without `EMULATED_FUNCTION_POINTERS`, ignoring dynCall exports.)
