### ISSUE TITLE
emcc first-time fail on Windows when copying is_vanilla.txt to embedded .emscripten_cache

### ISSUE THREAD

**Issue by audioMirror** [emscripten-core/emscripten#7155]
OS: Windows 10
Emsdk version: 1.38.12

After activating a project with the --embedded option the first time, the EM_CACHE environment variable is set to a Unix-style path name with forward slashes.

On build, files are stored into the .emscripten_cache local directory.  One of these is is_vanilla.txt, but there can be others.  For each store, the python script assumes that the file might be written to a temporary location, tests if the final and start locations are different.  If different, it tries to do a copy.

On Windows, the locations DO test different, because one (from EM_CACHE) has mostly Unix-style path separators.

The python script tries to copy, but realizes that the files are actually the same, and fails.  This fails the build.  Future builds, when all files are in the .emscripten_cache, will succeed.

Either EM_CACHE should have OS-specific path separators (I tried this change, and it works), or the python code that determines whether the copy needs to be done needs to make sure both are normalized to an OS style.

call ..\target\dependency\emsdk-portable-64bit\emscripten\1.38.12\emcc.bat -o Emscripten/Release/adler32.o -DNO_GZIP -DNO_GZCOMPRESS -DNDEBUG -D_LIB -DEMSCRIPTEN -D__STDC__ -O2 -I../../library/kaffeemonster-zlib -Wno-warn-absolute-paths -x c ../../library/kaffeemonster-zlib/adler32.c

INFO:root:generating system asset: is_vanilla.txt... (this will be cached in "C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\.emscripten_cache\is_vanilla.txt" for subsequent builds)
Traceback (most recent call last):
  File "C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\emscripten\1.38.12\emcc.py", line 38, in <module>
    from tools import shared, jsrun, system_libs, client_mods, js_optimizer
  File "C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\emscripten\1.38.12\tools\shared.py", line 1012, in <module>
    check_vanilla()
  File "C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\emscripten\1.38.12\tools\shared.py", line 987, in check_vanilla
    is_vanilla_file = temp_cache.get('is_vanilla', get_vanilla_file, extension='.txt')
  File "C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\emscripten\1.38.12\tools\cache.py", line 105, in get
    shutil.copyfile(temp, cachename)
  File "C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `C:/sandbox/alchemyLookup/src/LookupWrapperEmscripten/target/dependency/emsdk-portable-64bit/.emscripten_cache\is_vanilla.txt` and `C:\sandbox\alchemyLookup\src\LookupWrapperEmscripten\target\dependency\emsdk-portable-64bit\.emscripten_cache\is_vanilla.txt` are the same file
INFO:root:(Emscripten: Running sanity checks)

echo %EM_CACHE%
C:/sandbox/alchemyLookup/src/LookupWrapperEmscripten/target/dependency/emsdk-portable-64bit/.emscripten_cache

EDIT: This works fine in 1.37.22.  The slash differences exist, but everything works.  I could narrow the version down more if necessary.

**Comment by sbc100** [comment]
I imagine this has not been fixed yet

**Comment by brion** [comment]
I can't reproduce it with `latest` (1.38.45) on Windows 10 (insider fast build 18985). The forward slashes are there in the `EM_CACHE` variable but I see no error during compilation or setup of `is_vanilla.txt`.

**Comment by brion** [comment]
164fb064805f10494c8d4fe520c895c89cdefb2b appears to have fixed this issue in December 2018.
