### ISSUE TITLE
Emscripten fails to generate proper code  for macro

### ISSUE THREAD

**Issue by d3x0r** [emscripten-core/emscripten#7174]
Made simple example here.
https://gist.github.com/d3x0r/4af276237bf925be16748e02b61b8563

basically these macros do exactly the same job as the routine `GetUtfChar_code`, but compile to a single expression (relying a little on explicit knowledge of the variable 'c').  Using the macro works (MSVC(windows),GCC(windows/linux/android))
https://gist.github.com/d3x0r/4af276237bf925be16748e02b61b8563#file-emscripten_bindings-cc-L18

```
- for input '[1,2,3]' 

Character (METHOD1):91 [
Character (METHOD1):91 [
Character (METHOD1):91 [
Character (METHOD1):91 [
Character (METHOD1):44 ,
Character (METHOD1):44 ,
Character (METHOD1):44 ,

Character (METHOD2):91 [
Character (METHOD2):49 1
Character (METHOD2):44 ,
Character (METHOD2):50 2
Character (METHOD2):44 ,
Character (METHOD2):51 3
Character (METHOD2):93 ]
```

using the macro(METHOD1), the first byte from the each 4 bytes is returned for each for bytes.
using METHOD2 works as expected.
(Because this operation is done many many many times, once for each character in stings, the cost of the function call overhead was signifcant enough to merit making a single-expression macro.

I broke the macro out into a few functional parts for clarity....

---

How do I deal with accepting arbitrary strings?

```
test.dumpString("\u{12345}" ); // this line just totally fails: 
//BindingError: String has UTF-16 code units that do not fit in 8 bits
//    at BindingError.<anonymous> (M:\javascript\emscripten\dumpString.js:1802:24)
```

**Comment by d3x0r** [comment]
Any confirmation?

**Comment by brion** [comment]
Try setting `-s EMBIND_STD_STRING_IS_UTF8=1` on the compile.

I don't think there's anything wrong with the macro; rather, you're hitting a limitation that the bindings for converting a JavaScript string to a std::string don't allow arbitrary non-ASCII strings if std::string is not specified as being UTF-8.

You could also work around this by converting to a std::wstring instead, but if that's a lot of API surface that might not be easy.

**Comment by d3x0r** [comment]
Yes the macro and replcement code far overshadows the testcase but...

I don't know that in either of these cases there's a string conversion.

while( ( ( n = (*msg_input) - msg ), ( n < msglen ) ) && ( ( c = GetUtfChar( msg_input ) ) ) ) {
 printf( "Character (METHOD1):%d %c\n", c, c );
}

The input string

"[1,2,3]"  is received from JS, and is converted to valid UTF-8, 

```
	std::string s = string.as<std::string>();
	const char *s_char = s.c_str();
	dump_string( &s_char, s.length() );
```

**Comment by brion** [comment]
Ahhhh I see... on further testing, I can confirm that METHOD1 gives me your unexpected results (repeating characters four times) on asm.js builds but not on Wasm builds, where it works fine.

This is probably due to using unaligned 32-bit memory accesses, which doesn't work in asm.js because of how the TypedArrays are accessed.

If you only need WebAssembly builds, you can probably keep using this macro as-is but would have to change it if you need asm.js builds.

**Comment by brion** [comment]
(Specifically, you'll need to fetch memory byte-by-byte, as in METHOD2.)
