### ISSUE TITLE
Using flake8 on diffs in code contributions

### ISSUE THREAD

**Issue by rth** [emscripten-core/emscripten#7181]
From what I saw, there is an effort lead by @sbc100 to improve code style of Python files and make then more PEP8 compliant.

The current situation is that flake8 is run with a few exceptions,
> ignore = E111,E114,E501,E261,E266,E121,E402,E241

on an explicitly given subset of files.

However, new code can be introduced even in the whitelisted list of files that is not fully flake8 compliant (since the above errors are ignored). Moreover, changes in all other python files are not linted at all.

One way around this, that is practical for large code-bases is to additionally lint the diff (without any flake8 exceptions), approximately,
```
git diff -u incoming..HEAD | flake8 --diff --show-source
```
(except that one needs to filter out non Python files in addition). A more complete example can be found [here](https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/flake8_diff.sh)).

This may help spreading the effort to improve the Python code base quality to all contributors, with small incremental changes.

If you think that this might be useful, I can make a PR.

**Comment by sbc100** [comment]
I like the idea.
 
We could also ecourage the use of yapf which actually makes all the formatting decisions for you: https://github.com/google/yapf.  Similar to clang-format.

The plan is to switch from a white list to a blacklist once we pass a certain point.

The problem we face around ignoring certain errors makes me a little sad.  We should probably audit each exception and see how hard it would be to remove.  Sadly flake8 doesn't seem to be configurable WRT to indentation width or max line width so I don't think we can remove those two. 

There is a also a check for ',' followed by multiple spaces which means you can't format tables of data
nicely in python.   I'm not sure if this is perhaps bug in flake8 but it seems like data layed out in tables
is often important to readability.
