### ISSUE TITLE
Query On Exporting Std C++ Functions

### ISSUE THREAD

**Issue by awtcode** [emscripten-core/emscripten#7188]
@kripken , I was trying to test out exporting some C++ std functions with MAIN_MODULE=2. I realized that when I try to export the following functions explicitly, these functions are not exported as part of the main Wasm export table but as named globals:

"__ZTISt13runtime_error",
"__ZTINSt3__213basic_ostreamIwNS_11char_traitsIwEEEE",
"__ZTINSt3__215basic_streambufIwNS_11char_traitsIwEEEE",
"__ZTISt12length_error",
"__ZTVSt12length_error",
"__ZNSt3__26localeC1Ev",
"__ZNSt3__26localeC1ERKS0_",
"__ZTIPKw",
"__ZNSt3__26localeD1Ev",
"__ZNSt3__25ctypeIwE2idE",
"__ZTIj",

Since these functions are Std functions, I would expect them to be exported as part of the Wasm export table as per the rest. Instead, I find them exported as :

var NAMED_GLOBALS = {
"_ZNSt3__25ctypeIwE2idE": 195872,
"_ZTINSt3__213basic_ostreamIwNS_11char_traitsIwEEEE": 163280,
"_ZTINSt3__215basic_streambufIwNS_11char_traitsIwEEEE": 163200,
"_ZTIPKw": 165640,
"_ZTISt12length_error": 165488,
"_ZTISt13runtime_error": 165456,
"_ZTIj": 165656,
"_ZTVN10__cxxabiv117__class_type_infoE": 176016,
"_ZTVN10__cxxabiv120__si_class_type_infoE": 176056,
"_ZTVN10__cxxabiv121__vmi_class_type_infoE": 176376,
"_ZTVSt12length_error": 176220,
"_ZZNKSt3__27num_putIwNS_19ostreambuf_iteratorIwNS_11char_traitsIwEEEEE6do_putES4_RNS_8ios_baseEwPKvE5__fmt": 179317,
"_ZZNKSt3__27num_putIwNS_19ostreambuf_iteratorIwNS_11char_traitsIwEEEEE6do_putES4_RNS_8ios_baseEwmE5__fmt": 179323,
"str": 176473
};

May I know why is this the case? Thanks for your help.

**Comment by kripken** [comment]
I believe those are globals, not functions. For example,
```
$ c++filt _ZTVN10__cxxabiv117__class_type_infoE
vtable for __cxxabiv1::__class_type_info
```
So that symbol is a vtable for the c++ class, and is the address of where pointers to the relevant functions are, but it isn't a function itself.

**Comment by awtcode** [comment]
Thanks for the clarification @kripken :) But the last 2 C++ symbols seems to be functions though?
`_ZZNKSt3__27num_putIwNS_19ostreambuf_iteratorIwNS_11char_traitsIwEEEEE6do_putES4_RNS_8ios_baseEwPKvE5__fmt` 
gives
`std::__2::num_put<wchar_t, std::__2::ostreambuf_iterator<wchar_t, std::__2::char_traits<wchar_t> > >::do_put(std::__2::ostreambuf_iterator<wchar_t, std::__2::char_traits<wchar_t> >, std::__2::ios_base&, wchar_t, void const*) const::__fmt`
which seems like a valid C++ function?
