### ISSUE TITLE
Incorrect results when calling functions with int64_t parameters.

### ISSUE THREAD

**Issue by thndrwrks** [emscripten-core/emscripten#7199]
Is it possible to pass int64_t and uint64_t values from js into wasm functions? The code below shows my issue. Basically, the C code adds two int64_t values and returns the int64_t result. It looks like x and y are being placed as if they are int32_t (4 byte) then read as int64_t (8 byte) values.

main.html
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
</body>
<script async src="bug.js"></script>
<script src="main.js"></script>
</html>
```

main.js
```
"use strict";

self.Module = {
	onRuntimeInitialized: () => {
		let data = self.Module._bug(12, 24);
		console.log(data);

		data = self.Module._bug(24, 12);
		console.log(data);
	}
}
```

bug.c
```
#include <emscripten.h>
#include <stdint.h>

EMSCRIPTEN_KEEPALIVE int64_t bug(int64_t x, int64_t y)
{
	printf("%llx + %llx = %llx\n", x, y, x + y);
	return x + y;
}

```
I build with: emcc bug.c -o bug.html -std=c99 -O1 -g4 -s WASM=1
I run with: emrun --no_browser --port 8080 .

My console reads:
180000000c + 0 = 180000000c
12
c00000018 + 0 = c00000018
24

Running emcc -v:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.12
clang version 6.0.1  (emscripten 1.38.12 : 1.38.12)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/kurthildebrand/emsdk/clang/e1.38.12_64bit
INFO:root:(Emscripten: Running sanity checks)
WARNING:root:java does not seem to exist, required for closure compiler, which is optional (define JAVA in /Users/kurthildebrand/.emscripten if you want it)
WARNING:root:closure compiler will not be available
```

Zip file of the code: [wasm-int64-bug.zip](https://github.com/kripken/emscripten/files/2425848/wasm-int64-bug.zip)

**Comment by kripken** [comment]
This probably isn't documented well currently - would be good if someone could improve that.

JS can't represent int64s, so what happens is that in exported functions (that you can call from JS) we "legalize" the types, by turning an i64 argument into two i32s (low and high bits), and an i64 return value becomes and i32, and you can access the high bits by calling a helper function called `getTempRet0`.

**Comment by WizardOfArc** [comment]
@kripken which documentation file needs to be updated?

**Comment by kripken** [comment]
Probably the "Interacting with Code" page. Possibly an FAQ entry too.

**Comment by WizardOfArc** [comment]
@kripken both of those pages are in the Wiki. Can one contribute to the Wiki just like the regular code? In other repos (opencv for instance) this is not possible.  And my fork of this repository does not have the wiki included.

**Comment by kripken** [comment]
Thanks for the PRs! Will take a look now.

Yeah, CI has some random failures now, it's very hard to get rid of them all...

**Comment by jymuk** [comment]
> This probably isn't documented well currently - would be good if someone could improve that.
> 
> JS can't represent int64s, so what happens is that in exported functions (that you can call from JS) we "legalize" the types, by turning an i64 argument into two i32s (low and high bits), and an i64 return value becomes an i32, and you can access the high bits by calling a helper function called `getTempRet0`.

How do I do that with embind? Do you have a small example?
