### ISSUE TITLE
Tutorial.html#using-files cannot open file

### ISSUE THREAD

**Issue by isral** [emscripten-core/emscripten#7206]
I try [Tutorial.html](http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html) and stuck on [#using-files](http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html#using-files) with message: cannot open file.
OS: Windows 10 v1803 build 17134.1
Emscripten: 1.35.0 (nsis) and 1.38.12
Both firefox and chrome dev tools indicate hello.data already downloaded.
The other error message is related to MIME but I already fixed that by modifying SimpleHTTPServer.
I don't think I have other useful information because I just do what the tutorial said and even hello_world_sdl.cpp which produce colorful square run nicely.

**Comment by isral** [comment]
@kripken 
After 2 weeks I finally able to make this running.
Apparently emcc remove first character of folder name if I build from root (eg: R:\\).
It's fine if build from something else (eg: R:\A).
So, this is a bug.
hello.js:116: Module['FS_createPath']('/', 'ests', true, true); -> BUG
hello.js:116: Module['FS_createPath']('/', 'tests', true, true); -> CORRECT

**Comment by kripken** [comment]
Sounds like this could be a windows bug with the root path, yes.
