### ISSUE TITLE
SINGLE_FILE could use hex instead of base64

### ISSUE THREAD

**Issue by jedisct1** [emscripten-core/emscripten#7213]
The `SINGLE_FILE` flag causes the generated wasm code to be embedded within the JS code as a base64 string so it doesn't have to be loaded as an external dependency.

And this is awesome.

However, encoding wasm code as a hexadecimal string consistently provides smaller file sizes, after gzip compression, than base64. Between 5% and 8% smaller in the experiments I ran (libsodium, libhydrogen, and implementations of individual primitives).

Which kinda makes sense. Wasm opcodes repeat, and we can make better use of the dictionary if the same sequence of bytes always gets encoded the same way, unlike what base64 does.

In that context, would it make sense to encode wasm code as hex instead of base64 when `SINGLE_FILE` is used?

/cc @buu700

**Comment by buu700** [comment]
lol, did you mean to submit the exact same issue immediately after me? (See #7211.)

Anyway, I'm totally onboard with this idea.

**Comment by jedisct1** [comment]
Hahah, no, hadn't seen this. I was experimenting with libhydrogen and wasm yesterday and came to the same conclusion while trying to make it as small as possible.

Great, then :)
