### ISSUE TITLE
Non-possible link with non-LLVM bitcode should be an error and not a Warning

### ISSUE THREAD

**Issue by FrancoisChastel** [emscripten-core/emscripten#7214]
In this case, I think it should be an error and not a warning ?
`WARNING:xxxx:object /tmp/emscripten_temp_6YyTNZ_archive_contents/xxxx.o is not LLVM bitcode, cannot link`

**Comment by kripken** [comment]
There is some complexity here, see #6961 - we need to ignore invalid elements in archives in some cases, to not break existing things. Once that PR is finished and landed it should resolve this one.
