### ISSUE TITLE
Unexpected output path of emcc

### ISSUE THREAD

**Issue by FrancoisChastel** [emscripten-core/emscripten#7228]
I am using bazel and emscripten to port a C++ project to asm.js (and soon wasm).

But I get a behavior that I can't understand from `emscripten`, it's actually outputting the files (the `.d` files at least) to a different location. 

It's considering the right path as input :
`/private/var/tmp/_bazel_root/1eb19cb352f82c30aefdf9e9e4c9d429/execroot/__main__/bazel-out/asmjs-fastbuild/bin/xxx/xxx/_objs/empty/xxx/xxx/empty.d`

But it's considering the wrong path as output :
`/private/var/tmp/_bazel_root/1eb19cb352f82c30aefdf9e9e4c9d429//execroot/__main__/bazel-out/darwin-opt-clang/bin/xxx/xxx/_objs/empty/xxx/xxx/empty.d`

**Comment by kripken** [comment]
What generates those `.d` files? They don't sound familiar to me, not sure what those are - not sure if emscripten is emitting them?

**Comment by FrancoisChastel** [comment]
Hello @kripken thank you for your answer, 
When trying to build the project using EmScripten I have dependencies on `.d` files. 
Are you sure there are not coming from EmScripten at all ? 

To achieve this I tried to implement this following [tutorial](https://github.com/bazelbuild/bazel/wiki/Yet-Another-CROSSTOOL-Writing-Tutorial). 

Maybe you have better ressources to integrate Bazel with EmScripten ? Or any further explanation of the building pipeline using EmScripten ?
