### ISSUE TITLE
Emterpreter: show a proper error if a function is in both WHITELIST and BLACKLIST

### ISSUE THREAD

**Issue by hostilefork** [emscripten-core/emscripten#7239]
*Using SDK version 1.38.12 on Linux*

I was concerned that a given top-level function in a project might not be emterpreted, because I saw it on the stack with a name instead of `emterpret`...even though I'd said EMTERPRETIFY=1 and it wasn't on the EMTERPRETIFY_BLACKLIST.

I'm pretty sure it was emterpreted, and that was just a property of top-level calls distinct from subsequent ones.  But for the sake of assurance, I thought I'd throw it in an EMTERPRETIFY_WHITELIST:

    -s EMTERPRETIFY_WHITELIST="['_repl']"

I hadn't thought through the question of what having both a blacklist and whitelist would mean.  But instead of getting an error like "hey, you can't have both" the code generation just terminated in a somewhat uninformative way:

> ["binary", "%", "$33", ["unary-prefix", "+", 2]]
> ERROR:root:'/home/hostilefork/emsdk/clang/e1.38.12_64bit/binaryen/bin/asm2wasm libr3.temp.asm.js --total-memory=16777216 --trap-mode=allow -Os --mem-init=libr3.js.mem --mem-base=1024 -g -o libr3.wast -S' failed

Let me know if this isn't enough information to reproduce.  The spew from EMCC_DEBUG didn't look too useful, here's some prelude to the above:

> DEBUG:root:separating asm
> DEBUG:root:PYTHON not defined in /home/hostilefork/.emscripten, using "/usr/bin/python"
> DEBUG:root:JAVA not defined in /home/hostilefork/.emscripten, using "java"
> DEBUG:root:Cache: PID 13667 acquiring multiprocess file lock to Emscripten cache at /home/hostilefork/.emscripten_cache
> DEBUG:root:Cache: done
> DEBUG:root:Cache: PID 13667 released multiprocess file lock to Emscripten cache at /home/hostilefork/.emscripten_cache
> DEBUG:root:check tells us to use asm.js backend
> DEBUG:root:Successfully executed /usr/bin/python /home/hostilefork/emsdk/emscripten/1.38.12/tools/separate_asm.py /tmp/tmpd5RFMf/libr3.bc.o.js.pp.js.mem.js.jsopted.js.jsopted.js.jsopted.js.em.js.jsopted.js libr3.temp.asm.js /tmp/tmpd5RFMf/libr3.bc.o.js.pp.js.mem.js.jsopted.js.jsopted.js.jsopted.js.em.js.jsopted.js
> DEBUG:root:using binaryen, with method: native-wasm
> DEBUG:root:binaryen root already set to /home/hostilefork/emsdk/clang/e1.38.12_64bit/binaryen
> DEBUG:root:binaryen root already set to /home/hostilefork/emsdk/clang/e1.38.12_64bit/binaryen
> DEBUG:root:asm2wasm (asm.js => WebAssembly): /home/hostilefork/emsdk/clang/e1.38.12_64bit/binaryen/bin/asm2wasm libr3.temp.asm.js --total-memory=16777216 --trap-mode=allow -Os --mem-init=libr3.js.mem --mem-base=1024 -g -o libr3.wast -S
> ["binary", "%", "$33", ["unary-prefix", "+", 2]]
> ERROR:root:'/home/hostilefork/emsdk/clang/e1.38.12_64bit/binaryen/bin/asm2wasm libr3.temp.asm.js --total-memory=16777216 --trap-mode=allow -Os --mem-init=libr3.js.mem --mem-base=1024 -g -o libr3.wast -S' failed

**Comment by kripken** [comment]
> I was concerned that a given top-level function in a project might not be emterpreted, because I saw it on the stack with a name instead of emterpret...even though I'd said EMTERPRETIFY=1 and it wasn't on the EMTERPRETER_BLACKLIST.

I think what can happen is that the outside calls into `main()` (or another toplevel function), so we have to have a function by that name. But it should contain only a call into the emterpreter with the proper address. So you will see `main()` on the stack, but it's just the "trampoline", the function is actually emterpreted. You can look in the asm.js or wasm of that function to confirm.

(Note that e.g. `--profiling` makes us emit even more such trampolines, as it makes the stack traces more useful, but also in that case the code is being interpreted.)

**Comment by hostilefork** [comment]
>  But it should contain only a call into the emterpreter with the proper address

Yup, it was a suspiciously short number of instructions to be the actual code for the function!

I figured out what that problem was, but still wanted to mention the abrupt and bizarre exit printout.

**Comment by kripken** [comment]
Yeah, good point, it would be better to show a proper error for a function in both lists.

**Comment by hostilefork** [comment]
* a blacklist is a way of saying *"this is the list of functions that are not emterpreted, everything else is."*
* a whitelist says *"this is a list of functions that are emterpreted, everything else is not."*

So if you're going to have both a blacklist and a whitelist, there has to be a rule for resolving it.  If you have: foo(), baz(), bar()

    BLACKLIST ="foo"
    WHITELIST = "baz"

So, is bar() emterpreted or not?

**Comment by curiousdannii** [comment]
https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tools/emterpretify.py#L783-L785

Everything that's not in the whitelist gets added to the blacklist.
