### ISSUE TITLE
pipe+select timeout doesn't work

### ISSUE THREAD

**Issue by evgeny-g** [emscripten-core/emscripten#7241]
I'm trying to use pipe's file descriptors with select(), the code below compiled by gcc works in ubuntu, but doesn't work if compiled by em++

#include <stdio.h>
#include <unistd.h>
#include <sys/time.h>
int main() {
       int fd[2];
        pipe(fd);
        fd_set fds;
        FD_ZERO(&fds);
        int max_fd = fd[0];

        timeval timeout;
        timeout.tv_sec = 1;
        timeout.tv_usec = 0;

        FD_SET(fd[0], &fds);
        timeval tv;
        gettimeofday(&tv, NULL);

        int start_time = (tv.tv_sec)*1000+(tv.tv_usec)/1000 ;
        if( 0 != ::select(max_fd+1, &fds, NULL, NULL, &timeout))
        {
                printf("Select ERROR\r\n");
        }
        gettimeofday(&tv, NULL);
        int end_time = (tv.tv_sec)*1000+(tv.tv_usec)/1000 ;
        if( end_time-start_time<500 )
                printf("ERROR!!!\r\n");//-printed into web browser console

}
compiled by following command:
em++ -s WASM=1 main.c -o select.html

**Comment by kripken** [comment]
Low-level IO like `select` is not well supported in emscripten currently, sorry.
