### ISSUE TITLE
invocation:/emsdk/emscripten/incoming/emcc.py

### ISSUE THREAD

**Issue by 1312543912** [emscripten-core/emscripten#7247]
I am using webassembly to compile opus-1.2.1.
command:
  git clone https://github.com/xiph/opus.git
  EMCC_DEBUG=1 emconfigure ./configure
error:
![6272582b4ecb7b8a3e3ed590b186ed05](https://user-images.githubusercontent.com/21102828/46655479-4ecc7300-cbde-11e8-936b-ec7ec2a288c4.png)
I have installed python and java.
$ java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
$ python
Python 2.7.15 (default, Sep 18 2018, 20:16:18)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
I do not know why?

**Comment by kripken** [comment]
Looks like we need to add support for the `-print-search-dirs` command to emcc.py. Should be pretty simple, similar to `--version`, `--help`, etc.

**Comment by 1312543912** [comment]
> Looks like we need to add support for the `-print-search-dirs` command to emcc.py. Should be pretty simple, similar to `--version`, `--help`, etc.

I am sorry to comment duplicate. So, How i can do to resolve this problem?

**Comment by kripken** [comment]
No problem, I already closed the duplicate, nothing to worry about.
