### ISSUE TITLE
GL_ALPHA_TEST not implemented

### ISSUE THREAD

**Issue by KungPhoo** [emscripten-core/emscripten#725]
Howdy.

It seems that glAlphaFunc and glEnable(GL_ALPHA_TEST) is not implemented, yet. No big deal as I could use alpha blending do far. But it would be good to draw "holes" in 3D textures.

**Comment by juj** [comment]
Unassigning myself from this bug - reading later I realize that this relates to desktop OpenGL emulation, which is quite difficult in general and at present it is not on the critical path to be worth spending time on. It is possible to work around this by using `discard;` in fragment shader: http://stackoverflow.com/questions/24302152/opengl-alpha-test-how-to-replace-alphafunc-deprecated . If someone is interested in improving desktop OpenGL emulation here (or perhaps adding Regal to emscripten-ports), that would be a helpful contribution.
