### ISSUE TITLE
Compile Error: 'SDL_mixer.h' file not found

### ISSUE THREAD

**Issue by UstymUkhman** [emscripten-core/emscripten#7283]
I can't figure out why, but I'm having the following error:

```
opl_sdl.c:26:10: fatal error: 'SDL_mixer.h' file not found
#include "SDL_mixer.h"
         ^~~~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

when running `emcc [my_project_files.c] -s USE_SDL=2 -s ALLOW_MEMORY_GROWTH=1 -o test.html --embed-file some_stuff.txt`

and having the following code in the opl_sdl.c file:

```
#include "SDL.h"
#include "SDL_mixer.h" // <-- line 26
```

I've also tried with `-s USE_OGG=1 -s USE_VORBIS=1 -s ASSERTIONS=1` flags but it changed nothing.
Is there some flag I'm missing to make sure emscripten includes `SDL_mixer.h` header file?

I've also tried to use system's header file and in that case it seems that the build finish correctly, but when opening the project in the browser, I get

```
exception thrown: Mix_QuerySpec: TODO
Uncaught Mix_QuerySpec: TODO
```

So it's like it has just skipped `SDL_mixer.h` include and than couldn't find it's `Mix_QuerySpec` function on runtime.

**Comment by kripken** [comment]
We don't have SDL2_mixer in ports yet. There is a PR, #5995, which is mostly done, but seems to have stalled. Help finishing it would be very welcome.
