### ISSUE TITLE
emscripten_run_script_string returns "null" instead of (char*)0 for null strings.

### ISSUE THREAD

**Issue by SteveBaker** [emscripten-core/emscripten#7291]
If emscripten_run_script_string runs a command that returns a "null" string (in my case, the JavaScript command was:  "localStorage.getItem('foobar');" where there is no such item as 'foobar') - it returns a valid string containing the letters 'n' 'u' 'l' 'l' rather than returning a C/C++ NULL.  Consequence being that you can't tell whether you have an actual missing item or an item that happens to contain the string 'null'.

**Comment by kripken** [comment]
This API always returns a string, by converting the JS output to a string first. So that is the currently expected behavior. However, perhaps it does make sense to return a NULL in C when the result is a JS falsey value..? Not sure.

**Comment by SteveBaker** [comment]
The problem being - if the string truly is "null" (four ASCII characters) and not a null string - there is no way to tell - and since a null string is typically some kind of an error condition (as in the case of reading a localStorage item) - and "null" is a perfectly valid string - we're going to be seriously screwed (and I was!) - the idea, surely is to return a C string that represents the result of the JavaScript code (after all, we do stick a '\0' on the end - so it's not literally what JavaScript returns) - and this behavior quite utterly fails to capture that.  If that's what the spec says - then we need to change the spec because (a) it's not useful and (b) it's not what any sane person would expect it to do!   The way it works now is just asking for trouble down the line when some malware idiot starts putting "null" into strings and watching the C code fail to handle it.

**Comment by kripken** [comment]
Maybe you're right, I'm not sure. Would be good to have more people's feedback here.

I'd summarize the current function as "evaluate the input as JS, convert the result to a string, and return that string", while you're suggesting it should be "evaluate the input as JS, return a string if it is a string, otherwise return NULL". I think each makes sense in its own way - perhaps a new API for the latter makes sense.

**Comment by SteveBaker** [comment]
The problem (and it is HUGE) is that far *FAR* too many things you might want to call in JS return a null on error.
What we're doing by converting a null into a "null" is preventing wasm programs from detecting error conditions on the JS side.  Preventing programs from detecting errors is really pretty terrible behavior. 
 This isn't a matter of opinion - the way it works now is undoubtedly WRONG.

Worse still - my only defense against the current behavior is to compare the string I get back against the string "null" with a string compare.   This is slow - and it's error-prone because the string inside JS might actually BE the four letters n, u, l, l and not a null string - and what this stupid code is doing is making it 100% IMPOSSIBLE for me to distinguish an error condition from a perfectly legitimate piece of text.

So - there really shouldn't be any discussion about this.   It's a bug.   It's a bad decision.   It NEEDS to be fixed ASAP before we have a bajillon   if ( strcmp ( JSresult, "null" ) )...  things appearing in wasm programs.

I'm frankly horrified that there is any debate about this.

**Comment by SteveBaker** [comment]
This also violates the "principle of least surprise" - so when I call a JS function that says it returns a null string - it damned well ought to return a null string - and not four ASCII characters.   I can imagine any C/C++ programmer EXPECTING it to do anything other than returning a NULL.

**Comment by SteveBaker** [comment]
Without this change - how would you propose I rewrite this super-simple bit of C++ code?

   char *result = emscripten_run_script_string (  "localStorage.getItem('foobar');"  ) ;

   if ( result )
     printf ( "foobar is '%s'\n", result ) ;
   else
      printf ( "**ERROR: Missing 'foobar'\n" ) ;

localStorage.getItem returns a null string if there is no field 'foobar' in local storage.   How can I tell whether 'foobar' is nonexistent or whether it contains the string "null"?

**Comment by SteveBaker** [comment]
What is the use-case for WANTING this function to return "null" for a null result?   I can't think of a single case when that's desirable.

I apologize if I sound angry...but it's mostly because I'm angry!

**Comment by mutedAjar** [comment]
I don't think there's any reason to keep the current behavior. It actively makes any code that calls a function that could return null more error prone, and there doesn't seem to be a use case that requires it to return "null" for null.

**Comment by kripken** [comment]
Those are fair points. And the old behavior is always possible if the user does `toString()` or such. So I would be ok with a PR making this change, if we properly document it as a breaking change (in the changelog), and add tests.

If you work on such a PR, let me know if you run into any problems I can help with.

**Comment by SteveBaker** [comment]
Many thanks!   I'm not sufficiently familiar with the innards of emscripten - or your test protocols - to attack this one myself - but for anyone familiar with the code, I expect it should be an easy fix.
