### ISSUE TITLE
Exporting enums in C

### ISSUE THREAD

**Issue by Grieverheart** [emscripten-core/emscripten#7299]
I'm unable to find how to export enums in plain C.

**Comment by Becavalier** [comment]
@Grieverheart What do you mean by "export enums in plain C"? Here you can use "Embind" to export a C-like enum structure to JavaScript context.  And it also works for enum class.

FYI:
https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#enums

**Comment by Grieverheart** [comment]
@Becavalier I have written a module in plain C, meaning **not in C++**. As far as I know, Embind is not compatible with C, thus it is not an option for binding enums.

**Comment by FalkorX** [comment]
@Grieverheart emcc supports C++ also, there is no need to write bindings in C, because you cannot export enums from plain C.

What you can do however: write a C++ file which exports your enum and calls your C code. You don't have to alter you C code for this and can still export the enum.

**Comment by Grieverheart** [comment]
> @Grieverheart emcc supports C++ also, there is no need to write bindings in C, because you cannot export enums from plain C.
> 
> What you can do however: write a C++ file which exports your enum and calls your C code. You don't have to alter you C code for this and can still export the enum.

@FalkorX That seems indeed to be the solution then, although I feel like it's a **workaround**.

**Comment by FalkorX** [comment]
> @FalkorX That seems indeed to be the solution then, although I feel like it's a **workaround**.

@Grieverheart I'm afraid it is not, embind/WebIDL are the only options to export enums, and both of them only run with C++. You can either use that, or pass the enum's integer values to the function, which is definitely more of a hack than using embind.

**Comment by Grieverheart** [comment]
@FalkorX With workaround I mean that an option could "probably" be implemented in emcc to allow exporting enums. Of course then you can argue that you should also be able to export other types of constants and even macros, and would probably end up getting into a long discussion...
