### ISSUE TITLE
Missing WireType for std::basic_string<unsigned char> in wire.h

### ISSUE THREAD

**Issue by e45lee** [emscripten-core/emscripten#7362]
From looking at https://github.com/kripken/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/embind/embind.js#L617-L724 and https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/system/lib/embind/bind.cpp#L120-L121 it looks like embind expects that `std::basic_string<unsigned char>` has the same WireType as `std::string`, namely: https://github.com/kripken/emscripten/blob/60d6732eae2503d567534f1f994e35c2f541a768/system/include/emscripten/wire.h#L289-L292

However, there's no BindingType for `basic_string<unsigned char>` defined in https://github.com/kripken/emscripten/blob/master/system/include/emscripten/wire.h, so garbage gets serialized/deserialized by embind in this case.

My guess as to why the existing tests pass is that for short strings the wire format coincidentally coincides with how `basic_string<unsigned char>` is laid out on the heap.  For long strings, the first four bytes of the `basic_string<unsigned char>` object correspond to the length of the string, which coincides with the first four bytes/characters of what embind returns to JavaScript.

**Comment by Becavalier** [comment]
Maybe need  @chadaustin 's help to have a look.

**Comment by kripken** [comment]
Fixed by #7574
