### ISSUE TITLE
browser.test_webgl_offscreen_canvas_in_mainthread_after_pthread browser.test_webgl_offscreen_canvas_in_pthread browser.test_webgl_offscreen_canvas_only_in_pthread fail on chrome

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7374]
These fail on
```
    EMSCRIPTEN_RESULT r = emscripten_webgl_commit_frame();
```

**Comment by zivsha** [comment]
Is there a w/a for this issue?

**Comment by zivsha** [comment]
@kripken so since no browser other than chrome supports SharedBufferArray and since chrome fails for some reason to commit WebGL frames, is is correct that currently it is impossible on any browser to render from a background thread to an off screen canvas?

**Comment by juj** [comment]
Looks like Chrome has migrated its implementation away from the synchronous `.commit()` function proposal that is going away from the OffscreenCanvas spec. Not sure if Chrome ever had `.commit()`, but looks like when I run OffscreenCanvas tests in latest Chrome, there's no `.commit()`.

**Comment by kripken** [comment]
Yes, looks like `.commit()` is gone. We should have workarounds for that in the current code, so I think this can be closed.

Note that there is other stuff being fixed now for OffscreenCanvas, https://github.com/emscripten-core/emscripten/pull/8578, https://github.com/emscripten-core/emscripten/pull/8579
