### ISSUE TITLE
std::promise::get() hangs the main thread

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#7388]
std::promise::get() often uses 100% cpu, starving the thread it is waiting for. This happens sporadically with std::thread's, but consistently with emscripten_async_wget2_data. The behaviour appears the same in WASM/ASM.js. This affects both 1.38.13 and 1.38.14 (Edit: still an issue in 1.38.26).

Example Code:
```
#include <iostream>
#include <future>
#include "emscripten.h"

std::promise<bool> isComplete;
std::string str;

void callback_onLoad(unsigned handle, void* arg, void* pBuffer, unsigned pBufferSize) {
	str = "test string\n";
	isComplete.set_value(true);
}

int main(int argc, char** argv) {
	std::future<bool> callback_finished = isComplete.get_future();
	
	emscripten_async_wget2_data(
		"https://emscripten.org/_static/Emscripten_logo_full.png",
		"GET", "",
		nullptr,
		1,
		&callback_onLoad,
		nullptr,
		nullptr
	);
	
	if (callback_finished.get())	//<-- Hang here, mutex never unlocks, 100% cpu
		std::cout << str << std::endl;
	
	return EXIT_SUCCESS;
}
```
Compile with:
`emcc promise.cpp -std=c++11 -o promise.html --emrun`

The png gets downloaded, but 'callback_onLoad' is never called.
___
EDIT: Better example
```
#include <iostream>
#include <future>
#include <thread>

std::promise<bool> isComplete;
std::string str;

void test_function() {
	str = "test string";
	isComplete.set_value(true);
}

int main(int argc, char** argv) {
	std::future<bool> callback_finished = isComplete.get_future();
	
	std::thread(test_function).detach();
	
	if (callback_finished.get())	//<-- Hang here, mutex never unlocks, 100% cpu
		std::cout << str << std::endl;
	
	return EXIT_SUCCESS;
}
```
Compile with:
`emcc promise.cpp -std=c++11 -o promise.html --emrun -s USE_PTHREADS=1`

**Comment by VirtualTim** [comment]
Possibly related to #7261?

**Comment by kripken** [comment]
I think you'd actually need to run the operation on another thread for this to work, but I'm not sure.

**Comment by VirtualTim** [comment]
So I should be calling 'emscripten_async_wget2_data(...)' like std::thread(emscripten_async_wget2_data, ...)? I kind of thought that this was all handled internally by that function. I'll give that a shot and see how that goes.

**Comment by Querijn** [comment]
The issue here is that javascript is singlethreaded and would run this stuff in the event loop. It needs to exit the function it is right now to get a chance to run any other (callback_onLoad). emscripten_async_wget2_data does not launch a thread.

**Comment by VirtualTim** [comment]
Looking back at this with more experience, I'm pretty sure that emscripten_async_wget2_data is trying to execute on the main thread, but since the main thread is waiting on a promise, it never gets executed.

I'd still consider this a bug, as waiting on a promise should still execute queued calls on the main thread. There's other cases in Emscripten where sleeping the main thread really sleeps for a bit, waked up to check the event queue, then goes back to sleeping. I can't recall where I've seen this code of the top of my head right now.
