### ISSUE TITLE
Building problems with emscripten

### ISSUE THREAD

**Issue by a2kas** [emscripten-core/emscripten#7396]
Hello, I need to build project with emscripten, but have issue and dont understand what am I doing wrong?

In the project documentation which I need to build is given only such note how to build project by emscripten:
> make PLATFORM=js EMSCRIPTEN=<path_to_emscripten>

1. So installed emscripten, 
2. ran emcmdprompt.exe 
3. cd path to building project
4. type make PLATFORM=js EMSCRIPTEN=C:/Users/Administrator/Desktop/emsdk/emscripten/1.38.14

and got a bellow error:

![1](https://user-images.githubusercontent.com/15969142/47571297-df29e800-d940-11e8-8ec6-9e168982b260.png)

All variables looks OK:

![2](https://user-images.githubusercontent.com/15969142/47571323-ef41c780-d940-11e8-834c-fd5125dc7235.png)

thanks for any assistance in advance

**Comment by kripken** [comment]
It says `make` is not in your path, so I think you need to install it first, before using emscripten. I'm not sure how that is done on windows, though.

Also a good idea to verify that emscripten is set up properly by itself, for example by running the steps in the tutorial, https://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html
