### ISSUE TITLE
EMULATED_FUNCTION_POINTERS=1 issue with EH and functions returning int64

### ISSUE THREAD

**Issue by vargaz** [emscripten-core/emscripten#7399]
Testcase:
```
#include <cstdio>
#include <cstdint>

int64_t foo (void)
{
	return 5;
}

typedef int64_t (Func) (void);

Func *bar;

int main (void)
{
	bar = foo;

	try {
		printf ("%d\n", bar ());
	} catch (int i) {
	}
}
```
Compile with:
```
emsdk_env.sh && emcc -g  -s DISABLE_EXCEPTION_CATCHING=0  -s EMULATED_FUNCTION_POINTERS=1 -s ALIASING_FUNCTION_POINTERS=0 -s EXIT_RUNTIME=1 -s WASM=1 -s BINARYEN=1 foo.cpp
```

Expected result:
```
5
```

Actual result:
```
exception thrown: TypeError: cannot pass i64 to or from JS
ftCall_j@a.out.js:2221:10
invoke_j@a.out.js:2211:12
legalfunc$invoke_j@a.out.js line 1656 > WebAssembly.instantiate:wasm-function[104]:0xbc16
_main@a.out.js line 1656 > WebAssembly.instantiate:wasm-function[29]:0x5a2
Module._main@a.out.js:2446:10
```

**Comment by kripken** [comment]
I can confirm this issue. What happens is we need to do a call to a function type that is not valid in JS, so we need to legalize it. We legalize imports and exports properly, but the invoke/dynCall logic is somewhat special and I guess we need to fix something there.

Also confirming that this should only affect code using exceptions or setjmp, where an invoke ends up necessary to a function type containing an i64.

**Comment by aardappel** [comment]
Can confirm this issue as well. In my own code I can work around it by marking functions like `foo` in the example above with `noexcept`, but it also happens when calling functions in SDL that use 64-bit arguments, like https://wiki.libsdl.org/SDL_RWseek

**Comment by vargaz** [comment]
Submitted two 2 PRs to fastcomp/emscripten with a possible fix.

**Comment by jaykrell** [comment]
The sample doesn't look legal, but that may be besides the point.
i.e. it is passing int64_t to %d (unless int==int64_t which is possible but unlikely).

**Comment by AlexAltea** [comment]
Could anyone please suggest a temporary workaround for this issue?

I'm in a scenario where both `-s EMULATED_FUNCTION_POINTERS=1` and `setjmp` are necessary, and it causes a direct call to be transformed into a `$legalimport$invoke_iij` call (see #8119).

**Comment by kripken** [comment]
I think this is almost fixed - we legalize invokes now, and #8065 should fix emulated function pointers as well - may be interesting to test your code with that PR.

**Comment by vargaz** [comment]
The testcase above seems to work now.

**Comment by vargaz** [comment]
This is now fixed. Thanks.
