### ISSUE TITLE
Runtime.generateStructInfo method

### ISSUE THREAD

**Issue by a2kas** [emscripten-core/emscripten#7408]
Hi, I am trying to build https://github.com/inolen/ioq3/tree/4f7d7bf2159aa0a18b79bb417aa760abac817b2a project and faced with problem related to Runtime.generateStructInfo method. I know that It was deleted but I have no idea how I should replace those methods in compiled project. 

![untitled](https://user-images.githubusercontent.com/15969142/47741387-d9a30980-dc82-11e8-911d-7e0096295f30.png)

**Comment by kripken** [comment]
There is actually no automatic tool for that currently - the old tool depended on metadata in LLVM IR, that isn't there in general (not in an optimized build).

To achieve something similar, you can write a small C program that uses the structure, to find those offsets. Emscripten actually has one in `tools/gen_struct_info.py` which it uses internally, but I don't think it's easily usable for user code - perhaps it could be though. If not, looking at how it works might be helpful,
