### ISSUE TITLE
How to retain a undefined symbol name and 'import' in wast?

### ISSUE THREAD

**Issue by yyh1102** [emscripten-core/emscripten#7413]
I have a header file `hello.h`:
```C
#include <stdio.h>

int db_print(const char* a);
```

and `hello.cpp`:
```C
#include "hello.h"

int main(int argc, char** argv){
	db_print("hi\n");    // use this self-defined but not implemented function
	printf("hello world\n");
}

```

Then i run the command to compile C++ file to wast: 
`emcc hello.cpp -s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 && wasm2wat a.out.wasm -o hello.wast`

In `hello.wast`, i found the `db_print` has been compiled as `__Z8db_printPKc`, what does that mean? 

And if I wanna implement the function `db_print` in the Virtual machine implemented by myself.  How can i retain the name `db_print` in wast? 
![image](https://user-images.githubusercontent.com/10328169/47766838-d142e100-dd0b-11e8-839d-44f127f02f88.png)

**Comment by kripken** [comment]
>  i found the db_print has been compiled as __Z8db_printPKc, what does that mean?

The change in name is due to C++ name mangling. To avoid it, you can compile the file as C and not C++, or use `extern "C"` in C++. You can also "demangle" them,
```
$ c++filt _Z8db_printPKc
db_print(char const*)
```

Btw, js-libraries are a simple way to implement stuff like this, see the `--js-library` option.

**Comment by yyh1102** [comment]
@kripken Thanks! I've tried this solution, but i got the symbol name `_db_print` in wast, not the pure `db_print`. 
![image](https://user-images.githubusercontent.com/10328169/47830456-d9138b80-ddc6-11e8-9b0d-33b3f8743b51.png)


And i have another question：If i delete `main` in `hello.cpp` and just declare and implement a function like below:
```C++
#include "hello.hpp"

void hi(){
	db_print("hello");
}
```

When i compile the file to wast, **`db_print` will not be 'import' in 'env'**. What can i do to make it happen?

**Comment by kripken** [comment]
Yes, as a convention there is a `_` prefix currently. x86 assembly also has a similar convention.

For the second question, you need to export functions you want kept around, see https://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-functions-in-my-c-c-source-code-vanish-when-i-compile-to-javascript-and-or-i-get-no-functions-to-process

**Comment by kripken** [comment]
Not sure why the specific name is that crucial? But using the LLVM wasm backend might not emit a "_" prefix, I think it has different conventions. Otherwise you can always edit the wasm file to rename it (e.g. convert to text using wasm-dis, edit, then wasm-as to binary).

**Comment by yyh1102** [comment]
I use the command `emcc hello.cpp -s "EXPORTED_FUNCTIONS=['_hi','_db_print']" -s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0` to compile the original `hello.cpp`, but `db_print` is still not import in `env`.

**Comment by kripken** [comment]
Why do you have `ERROR_ON_UNDEFINED_SYMBOLS`? I think that might be hiding an error that should be fixed.

One possibility is if that's a cpp file, it will mangle names as mentioned earlier, unless you use `extern "C"`. Or just rename it to a c file.

**Comment by yyh1102** [comment]
Oh, if without `ERROR_ON_UNDEFINED_SYMBOLS`, an error will be throw like below:
![image](https://user-images.githubusercontent.com/10328169/48040835-8a466700-e1b5-11e8-9bd9-3e772611dec9.png)

Maybe use `extern "C"` is the only way i can reach my goal~ Thank you!
