### ISSUE TITLE
Unresolved symbol for libc networking since 1.38.13 included

### ISSUE THREAD

**Issue by FrancoisChastel** [emscripten-core/emscripten#7416]
Hello,

Just wanted to mention that since the version 1.38.13 and above (compile fine in the version 1.38.12) some symbols are missing, just for example `htons` is not resolvable on these versions.

PS : It could be great to have test that verify that EmScripten support all the systems calls ?
If you think so I would be more than happy to work on it if you can point me a clean way to do it that will integrate smoothly inside the project.

**Comment by FrancoisChastel** [comment]
By the way, I am using `getaddrinfo` and `sockets` related functions is there any incompatibility regarding the network side of `WebAssembly` ?

**Comment by kripken** [comment]
As mentioned in the other issue, those may be fixed by #7420, however it would be good to have testcases of what you see.

We may not have tests to check all the syscalls, yeah. Not sure if there's a simple solution there, or to just audit the code to find what's not tested and add that.
