### ISSUE TITLE
Future and networking functions crash

### ISSUE THREAD

**Issue by FrancoisChastel** [emscripten-core/emscripten#7428]
Hello,

After lot of investigation I found out that running a `std::async` is working fine except when trying to use a networking function. I didn't wanted to bother the community once again but it's totally impossible to debug it regarding the fact all the Web Browser environment is crashing when executing this code.

For example the following code will crash :
```C++
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <future>
#include <iostream>

struct addrinfo hints, *infoptr;

int main() {
    hints.ai_family = AF_INET; 

    std::future<int> f1 = std::async(std::launch::async, []{
      int result = getaddrinfo("www.mozilla.org", "http", &hints, &infoptr);
      fprintf(stdout, "Ok !\r\n");
      freeaddrinfo(infoptr);
      return 0;
     });

    fprintf(stdout,"%d\r\n",f1.get());
}
```

This one using future as well is not crashing : 
```C++
int main() {

    std::future<int> f1 = std::async(std::launch::async, []{
      fprintf(stdout, "Ok !\r\n");
      return 0;
     });

    fprintf(stdout,"%d\r\n",f1.get());
}
```

**Comment by FrancoisChastel** [comment]
Any reason of this bug ? @kripken

**Comment by kripken** [comment]
I'm not familiar with that code, but if it hangs on a wait, then the question is what thread is it waiting on, and why isn't that threading sending it a notification.
