### ISSUE TITLE
Release lists are different

### ISSUE THREAD

**Issue by a2kas** [emscripten-core/emscripten#7429]
Hi, emsdk list --old gives different list on the linux and windows, I would like to install sdk-1.12.0-64bit on the linux, but there is no such version listed in the list (also clang-3.2-64bit there is no on linux, on win it is).

**Comment by FrancoisChastel** [comment]
Hello,

I can't reproduce your bug when running `emsdk list --old` I am able to see the version `sdk-1.12.0-64bit`, could you provide more insight ? 

By the way, this is not the actual repo of the sdk, this [one is](https://github.com/juj/emsdk).

**Comment by a2kas** [comment]
@FrancoisChastel are you able to see sdk-1.12.0-64bit on linux? 

here is list which i get on linux: https://justpaste.it/4gcus and yes, i use not his repo but https://github.com/juj/emsdk

**Comment by a2kas** [comment]
@FrancoisChastel what distribution? what do you mean?

**Comment by FrancoisChastel** [comment]
I was speaking about your Linux distribution, by using `Ubuntu v18.04` inside a docker container I am not able as well to retrieve `sdk-1.12.0-64bit`.

Why not using the last version ? The branch from the git does not mention it as well !

**Comment by a2kas** [comment]
I need that version because I want build https://github.com/ioquake/ioq3 project and with latest emscripten version I am getting errors.
