### ISSUE TITLE
Clang fails to compile a native executable for benchmark.test_dlmalloc

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#743]
Running the test 'python tests/runner.py benchmark.test_dlmalloc' fails on Windows like described in #729.

The first problem seems to be that Doug Lea's Malloc code uses Visual C++ compiler intrinsics _BitScanForward and _BitScanReverse when it detects it's building against a VC++ compiler (in the case defined(_MSC_VER) && _MSC_VER>=1300).

Clang masquerades as the VC++ compiler, so it defines _MSC_VER, but it does not seem to recognize/implement either of these intrinsic instructions, and fails at link time to unresolved symbols from these two functions.

To reproduce, download https://dl.dropbox.com/u/40949268/Bugs/clang/dlmalloc.cpp and try to compile it on clang 3.1 on Windows just by issuing:

clang++ dlmalloc.cpp 

The result prints

```
dlmalloc-907634.o : error LNK2019: unresolved external symbol __BitScanForward referenced in function _malloc
dlmalloc-907634.o : error LNK2019: unresolved external symbol __BitScanReverse referenced in function __ZL13tmalloc_largeP12malloc_statej
a.out : fatal error LNK1120: 2 unresolved externals
clang++: error: linker command failed with exit code 1120 (use -v to see invocation)
```

To work around this issue, I replaced 
# elif defined(_MSC_VER) && _MSC_VER>=1300

with
# elif defined(_MSC_VER) && _MSC_VER>=1300 && !defined(__clang__)

to have dlmalloc not try to use these undefined VC++ intrinsics when building using clang. In that case, it should default to a manual bittwiddling implementation for these two functions. The fixed version is available at https://dl.dropbox.com/u/40949268/Bugs/clang/dlmalloc_clang.cpp

This allows the application to build and link successfully. However, running the application crashes after executing the last line of main(). At this point I'm quite unsure how to continue debugging. dlmalloc is pure C code, and I tried to rename the file to .c and build it with clang, to confirm that there at least are no global C++ class dtors being unwound at application exit time that could cause the crash, which there wasn't, and the crash still occurs.

To reproduce, download the dlmalloc_clang.cpp and compile and run it with

clang++ dlmalloc_clang.cpp -o dlmalloc.exe
dlmalloc.exe

The application prints the line 

```
 *0,0*
```

right before crashing.

**Comment by bhupeshpant19jan** [comment]
I am seeing this issue now for 64 bit.

**Comment by bhupeshpant19jan** [comment]
Has any support engineer been assigned to this query?

**Comment by sbc100** [comment]
@bhupeshpant19jan is the issue you are seeing exactly the same?  i.e. are you trying to run the `benchmark.test_dlmalloc` test on windows?.  I only ask because that is a fairly unusual test to run.

**Comment by bhupeshpant19jan** [comment]
I havn't run the tests/

**Comment by sbc100** [comment]
Then can you explain that issue you are seeing?     this issue specifically relates  to a test called `benchmark.test_dlmalloc`.   

It probably best to open a new issue since this from from 2012 is almost certainly not the same issue you are seeing.

**Comment by bhupeshpant19jan** [comment]
agreed
