### ISSUE TITLE
HEAPU8 and _malloc

### ISSUE THREAD

**Issue by yjjnls** [emscripten-core/emscripten#7437]
According to some examples, I found that `Module._malloc()` return the address of the alloced memory, something like the pointer.

But in the example below:
```js
let data = new Uint8Array([0, 0, 0, 255, 0, 1, 2, 3]);
let dataPtr = cv._malloc(8);
let dataHeap = new Uint8Array(cv.HEAPU8.buffer, dataPtr, 8);
```
>new Uint8Array(buffer [, byteOffset [, length]]);

`byteOffset` should be the offset in the buffer, but here dataPtr is passed in. 

I don't know why? 

According to the [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array#Properties_2), `byteOffset` is the offset (in bytes) of the Uint8Array from the start of its ArrayBuffer. But what `cv._malloc(8)` returned is an address. The former is a relative address, the latter is an absolute address. I think they're different.

The example is from opencv.js, and it run correctly.

**Comment by kripken** [comment]
This stuff can be confusing, yeah. But `HEAPU8.buffer` is all of memory, so an offset on it is the same as an absolute offset.
