### ISSUE TITLE
MODULARIZE / scriptDirectory fails when loaded in an SVG

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7494]
Reported here: https://github.com/kripken/emscripten/issues/6903#issuecomment-437320418

**Comment by originalsouth** [comment]
In the case of an SVG we probably want:
`scriptDirectory = self.location.href;`
Instead of:
`scriptDirectory = document.currentScript.src;`
as the latter is `null`.

As a workaround one can compile with `-s ENVIRONMENT=worker` to enforce this behavior.

**Comment by adjenks** [comment]
This is still an issue. The workaround _works_, but is still a _workaround_.

**Comment by kripken** [comment]
Ok, let's reopen it, hopefully someone will want to look into fixing it.
