### ISSUE TITLE
[LTO] Emscripten compiled cv::solvePnPRansac broken on iOS Safari

### ISSUE THREAD

**Issue by ThorstenBux** [emscripten-core/emscripten#7495]
Hi,

I'm compiling this function from OpenCV to JS using Emscripten. https://github.com/artoolkitx/opencv/blob/master/modules/calib3d/src/solvepnp.cpp#L233

It works fine on all platforms except iOS. On iOS the returned matrix contains only 0/-0 or NAN. I've tried with various compilation options but without any success.

Emscripten version:
```
emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.6
clang version 6.0.1  (emscripten 1.38.6 : 1.38.6)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Users/thorstenbux/repos/emsdk/clang/e1.38.6_64bit
INFO:root:(Emscripten: Running sanity checks)
```
I was hoping that maybe you could spot why it fails on iOS by looking at the OpenCV function code.

Any hints highly appreciated.

**Comment by ThorstenBux** [comment]
Hi everyone, has anyone the slightest idea? I'm a bit puzzled why it doesn't work

**Comment by kripken** [comment]
Sounds like an LLVM LTO bug. If you can also make a native build of the code, it should also occur there, and filing a bug for LLVM with that would be a good idea.

**Comment by ThorstenBux** [comment]
Hi, @kripken thanks for your reply. I would need guidance to do so *blush* so far I have build with emcc and the cmake toolchain of OpenCV but not much knowledge of LLVM.

**Comment by kripken** [comment]
No problem @ThorstenBux - yeah, debugging and filing an LTO issue like that can be hard and take time. I would myself if I had the time, but not likely atm. Maybe best to reopen the issue for that investigation, perhaps someone else can.

**Comment by vasanthhr** [comment]
@ThorstenBux  @kripken 

Safari-12 has issue, and solvepnp opencv function getting break during runtime, but it works in safari-13

I seen your answer , as do we need to build opencvjs with not using ` --llvm-lto 1`  ?

Please guide me on the same.

**Comment by sbc100** [comment]
Do you need to reopen?
