### ISSUE TITLE
Bump C++ Test Requirements to C++11 or Newer.

### ISSUE THREAD

**Issue by EricWF** [emscripten-core/emscripten#7496]
If I'm not mistaken, the test suite builds `.cpp` files without specifying a C++ dialect. Meaning some compilers will default to C++03.

If I'm mistaken on this point, please close this bug.

Although C++03 test coverage is important when shipping a toolchain, I don't think it justifies forcing tests to be written using archaic C++. Additionally, ensuring C++03 conformance is Clang and libc++'s job, meaning we don't need to provide additional test coverage.

I suggest bumping the any `.cpp` tests to compiling with at lease C++11 if not newer. Since we own the toolchain version, we can go as high as we want. Ideally tests for this project could be allowed to compile in the newest dialect available.

What do you think?

**Comment by kripken** [comment]
Individual tests can specify `-std=c++11`, but yeah, probably the great majority do not, so they implicitly get the current clang default.

I don't object to updating older C++ files, however, I don't think I see the benefit? We mostly test non-frontend parts of the compiler in emscripten, that is, optimizations and wasm stuff etc.

**Comment by kripken** [comment]
Yeah, makes sense - if most new tests would be c++11 etc. anyhow, it could be easier to have that be the default instead of making them set it manually. Sounds good to me.
