### ISSUE TITLE
USE_PTHREADS and ASSERTIONS cause worker loading to fail

### ISSUE THREAD

**Issue by wffurr** [emscripten-core/emscripten#7515]
A debug build with threads enabled fails to load.

Module.instantiateWasm callback failed with error: LinkError: WebAssembly Instantiation: Import #5 module="env" function="tempDoublePtr" error: global import must be a number or WebAssembly.Global object

In jsifier.js:

if (USE_PTHREADS) {
          print('var tempDoublePtr;\n');
          print('if (!ENVIRONMENT_IS_PTHREAD) tempDoublePtr = alignMemory(allocate(12, "i8", ALLOC_STATIC), 8);\n');
        } else {
          print('var tempDoublePtr = ' + makeStaticAlloc(8) + '\n');
        }
        if (ASSERTIONS) print('assert(tempDoublePtr % 8 == 0);\n');   // tempDoublePtr is always undefined in the workers!

Since pthreads work fine without assertions enabled, the "copyTempFloat" function must be unused in the worker code.

**Comment by kripken** [comment]
I'm not sure how this could occur - tempDoublePtr should be defined for the worker, it's passed in in pthread-main.js on the line with `tempDoublePtr = e.data.tempDoublePtr`, and only after that do we importScripts to get the code you see the problem in.

Must be some corner case we don't see in our test suite. If you add an assert that `tempDoublePtr` is not falsey after that line I mentioned, is it hit?
