### ISSUE TITLE
emcc --clear-cache doesn't clear wasm_o

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7519]
STR:
```
./emcc --clear-cache
./emcc -s WASM_OBJECT_FILES=1 tests/hello_world.c
```
The second command should rebuild libc, etc., but does not - the wasm_o subdir in the cache directory was not cleared. I think we don't look at the -s options in clear-cache.

To fix this, we should probably just clear both wasm backend subdirs, and not try to figure out which one is intended.

cc @sbc100

**Comment by kripken** [comment]
PR: https://github.com/kripken/emscripten/pull/7522

**Comment by VirtualTim** [comment]
Hey since the linked PR is merged, this should be closed, right?

**Comment by kripken** [comment]
Yes, thanks!
