### ISSUE TITLE
error: undefined symbol: glCompressedTexImage1D

### ISSUE THREAD

**Issue by ValSergey** [emscripten-core/emscripten#7528]
Hello!
what's the hitch?
error: undefined symbol: glCompressedTexImage1D
error: undefined symbol: glCopyTexSubImage3D
error: undefined symbol: glGetCompressedTexImage
error: undefined symbol: glTexImage3D
I try all from http://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html#opengl-support-webgl-subset

**Comment by ValSergey** [comment]
I used -lSDL2_mixer

**Comment by kripken** [comment]
I think `getTexImage3D` requires WebGL2. You can use  `-s USE_WEBGL2=1` to enable that.

**Comment by ValSergey** [comment]
getTexImage3D Ok with -s USE_WEBGL2=1. but glCompressedTexImage1D no

**Comment by kripken** [comment]
I don't think that glCompressedTexImage1D is in WebGL2, I don't see it in the spec: https://www.khronos.org/registry/webgl/specs/latest/2.0/
