### ISSUE TITLE
How to use SDL2_mixer

### ISSUE THREAD

**Issue by ValSergey** [emscripten-core/emscripten#7530]
error: undefined symbol: Mix_LoadMUSType_RW
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: glCompressedTexImage1D
error: undefined symbol: glCopyTexSubImage3D
error: undefined symbol: glGetCompressedTexImage
error: undefined symbol: glTexImage3D

**Comment by kripken** [comment]
There is a PR for SDL2_mixer,, but it needs help to get landed, https://github.com/kripken/emscripten/pull/5995

**Comment by ValSergey** [comment]
Thankee you
1)./emconfigure ./configure
./emmake make   for SDL2_mixer
2)-L/usr/local/lib64 -lSDL2_mixer        for makefile
it is work

**Comment by ValSergey** [comment]
but,  then I compile SDL2 to get : error: SDL now requires a Linux 2.4+ kernel with /dev/input/event support. fatal error: 'linux/joystick.h' file not found . Why? else without emmake compiled ok
