### ISSUE TITLE
Security concerns regarding the SDK install instructions

### ISSUE THREAD

**Issue by mihaifm** [emscripten-core/emscripten#7531]
On Emscripten's documentation, the instructions for installing the SDK  point to the following repository:

https://github.com/juj/emsdk.git

I am not familiar with the development of Emscripten, so for me this repository belongs to a random user named **juj** who doesn't display his real name, and has a broken url listed as website in the description. He also belongs to the `Mozilla-Games` organization.

The license of the SDK also doesn't have any names associated with it, just mentions `Emscripten authors`.

Looking at the install script itself it seems like it's asking me to run some random executables on my machine, and messes with my registry keys.

As a user concerned about my security I simply cannot trust the installer instructions. The SDK should have some proper releases, with release hashes or GPG signatures that I can verify.

**Comment by kripken** [comment]
* What broken URL did you see?
 * We do have the option to move repos to the `emscripten-org`  group, which would be more official. Sadly the "emscripten" name is taken by someone, and github won't let us use it.
 * The "Emscripten authors" reference should perhaps have a link to the AUTHORS file in the emscripten repo.

**Comment by mihaifm** [comment]
Ok, I understand, thanks for the update. 
I was just referring to the url on his profile, that's not too important.
Moving to an org group would definitely help in terms of trust, indeed. I was just looking for the minimal stuff, like a release on github for the sdk signed with gpg, with the public key posted on the main repo. In the current state of affairs, if someone hijacks the main repo they can replace juj's link with with a custom repo and have malware automatically installed on my computer. Signing the release and posting the key in a public place would prevent this.
