### ISSUE TITLE
avoid checking in `node_modules` directories.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#7538]
This is somewhat related to #5774, but can be done as an intermediate cleanup step.

We currently have two separate `node_modules` directories checked-in under emscripten:
```
./tools/node_modules
./tools/eliminator/node_modules
```
We also use the top level node_modules directory for installing `ws` which is only used to the socket tests.
 
After discussing this with @jgravelle-google and @mathiasbynens I'd like to propose that we switch to using npm to install all this stuff at the top level and remove the checked in versions.

As an initial cleanup I already uploaded: #7536 

In order to avoid requiring developers to manually run `npm install` after cloning (at least initially) I'm proposing to run this transparently from emcc's `check_sanity` if needs be.  A bit like how we build libc on demand behind the scenes.

emsdk users should never have to run `npm install` since the SDK should alwasy include the correct versions.

**Comment by kripken** [comment]
Sounds like a noticeable change could be that non-emsdk users would need to install npm (and not just node, although the official downloads contain both)?

**Comment by sbc100** [comment]
I'm pretty you node always comes with npm... but that it something I will verify and mention on them mailing list.
