### ISSUE TITLE
Difference in building project

### ISSUE THREAD

**Issue by yjjnls** [emscripten-core/emscripten#7542]
According to the [specification](https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#building-projects) in the doc, when I build a large project, I can just use `emconfigure` and `emmake`: 
```
# Run emconfigure with the normal configure command as an argument.
./emconfigure ./configure

# Run emmake with the normal make to generate linked LLVM bitcode.
./emmake make

# Compile the linked bitcode generated by make (project.bc) to JavaScript.
#  'project.bc' should be replaced with the make output for your project (e.g. 'yourproject.so')
#  [-Ox] represents build optimisations (discussed in the next section).
./emcc [-Ox] project.bc -o project.js
```

But there's another introduction about [embind](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html#embind), I'm confused about why use embind? 
If I want to build a large c++ project(already owns makefile) into js, should I  just use the `emconfigure` and `emmake`? or add contents `EMSCRIPTEN_BINDINGS()` and how?

**Comment by kripken** [comment]
The two are separate topics. emconfigure/emmake help build a project that uses configure/cmake/make. It basically integrates with those build systems. embind, on the other hand, has nothing to do with build systems, it's a way to connect C++ and JS. You can use it regardless of whatever build system you have in place.

**Comment by kripken** [comment]
@yjjnls What kind of error does it show? Is it a compile-time error, or run-time, and if run-time, is it from the emscripten system support code, or from user code in those libraries?

If the issue is something is not being linked in, you can use llvm-nm on the input .so files to see which symbols are provided there.

**Comment by yjjnls** [comment]
@kripken It's a runtime error in my application. I used `llvm-nm input.so` and found the symbols, but in the `tesseract.js` (emscripten generated), the symbols can't be found and raise the error.

`em++ -s WASM=1 -o tesseract.js /usr/local/lib/libtesseract.so /usr/local/lib/liblept.so`

Is there anything wrong?

**Comment by kripken** [comment]
@yjjnls 

> It's a runtime error in my application

Please be more specific - what kind of runtime error? How is the app determining that may be important. Is it using dlopen, for example, or some other mechanism?

In general linking two `.so` files together should work, however, emscripten will dce away code it does not see is used. So there must be a `main()` in one of those libraries, unless you export something. And also anything accessed dynamically later may also need to be exported as well, depending how it is accessed. To test if that is relevant, you can build with `-s LINKABLE=1` which will disable dce (as it assumes the code can be linked again later).

**Comment by yjjnls** [comment]
> 1. use `emconfigure cmake + emmake make` to build leptonica into bitcode. The building result is liblept.so (why this format instead of .bc?) and I checked it's LLVM IR bitcode.
> 2. use `LIBLEPT_HEADERSDIR=$HOME/local/include emconfigure ./configure --prefix=$HOME/local/ --with-extra-libraries=$HOME/local/lib` + `emmake make` to build tesseract into bitcode and it will link liblept.so.
> 3. use `em++ -s WASM=1 -o tesseract.js /usr/local/lib/libtesseract.so /usr/local/lib/liblept.so` to build tesseract.js and tesseract.wasm.
> 
> But when I use tesseract.js for application, it show error about cann't find TessBaseAPI and I found the no interfaces of tesseract in tesseract.js.

@kripken I do the steps as memtioned above. 

In short, I build lept and tesseract to bitcode firstly, but they're `.so` format and I check the symbols using `llvm-nm`, the symbols are all exported. 

Then I want to build these two bitcode files together into wasm. **I don't want to use dynamic linking.**

At last, I write a test nodejs application, which require the `tesseract.js` build above as `Module`: 
`let api = new Moudle.TessBaseAPI();`

It shows error: Moudle.TessBaseAPI is not a constructor. I think the js code can't find TessBaseAPI.

Are the steps I did right? or should I do something more?

**Comment by kripken** [comment]
It sounds like you're expecting C++ classes to be used as JS classes?

We do have ways to do that, see [the WebIDL binder](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html). The tests in the test suite for the WebIDL binder may also be useful examples of working code. (also [embind](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html) is another option.)

**Comment by yjjnls** [comment]
@kripken yes, I want to use the c++ classes of tesseract in js code. I want to use embind. So I create this issue: If I just use `emconfigure` and `emmake`, why couldn't I use the c++ classes in js? And I'm still confused now, could you explain it please?

According [your answers](https://github.com/kripken/emscripten/issues/7542#issuecomment-440739703) above, 
>embind, on the other hand, has nothing to do with build systems

But if I want to use embind and the build systems of c++ project, how should I do? I did the steps memtioned above, but it raise error memtioned above.
