### ISSUE TITLE
Linking third-party libraries 

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#7547]
When trying to compile my code with this command:
```
em++ -std=c++17 -Wall -pedantic -pedantic -D variant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -fexceptions -I C:/boost_1_68_0/ -I C:/Jinja2Cpp/install/include/ -I C:/json/single_include/ -L C:/boost_1_68_0/lib64-msvc-14.1/ -lboost_system-vc141-mt-x64-1_68 -L C:/Jinja2Cpp/install_x64/lib/static/ -ljinja2cpp -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::send_lambda'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::operator()'] -s EXPORTED_FUNCTIONS=['_server_session::server_session'] -s EXPORTED_FUNCTIONS=['_server_session::run'] -s EXPORTED_FUNCTIONS=['_server_session::do_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_write'] -s EXPORTED_FUNCTIONS=['_server_session::do_close'] -s EXPORTED_FUNCTIONS=['_listener::listener'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_listener::do_accept'] -s EXPORTED_FUNCTIONS=['_listener::on_accept'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_cache'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_duration'] -s EXPORTED_FUNCTIONS=['_cache_storage::query'] -s EXPORTED_FUNCTIONS=['_client_session::client_session'] -s EXPORTED_FUNCTIONS=['_client_session::run'] -s EXPORTED_FUNCTIONS=['_client_session::on_resolve'] -s EXPORTED_FUNCTIONS=['_client_session::on_connect'] -s EXPORTED_FUNCTIONS=['_client_session::on_write'] -s EXPORTED_FUNCTIONS=['_client_session::on_read'] -s EXPORTED_FUNCTIONS=['_mime_type'] -s EXPORTED_FUNCTIONS=['_path_cat'] -s EXPORTED_FUNCTIONS=['_parse'] -s EXPORTED_FUNCTIONS=['_fail'] -s EXPORTED_FUNCTIONS=['_handle_request'] currency_converter.cpp -o currency_converter.js
```
I had these warnings:
```
WARNING:root:emcc: cannot find library "boost_system-vc141-mt-x64-1_68"
WARNING:root:emcc: cannot find library "jinja2cpp"
```
The code is here: https://github.com/DragonOsman/currency_converter/blob/master/currency_converter.cpp .  Why is it giving that warning even though I provided the search path?  It also said 
```
WARNING:root:emcc: cannot find library "libboost_system-vc141-mt-x64-1_68.lib"
WARNING:root:emcc: cannot find library "jinja2cpp.lib"
```
When I did this:
```
-L C:/boost_1_68_0/lib64-msvc-14.1/ -l libboost_system-vc141-mt-x64-1_68.lib -L C:/Jinja2Cpp/install_x64/lib/static/ -l jinja2cpp.lib
```
And when I provided the library name with the full path, like `L C:/boost_1_68_0/lib64-msvc-14.1/libboost_system-vc141-mt-x64-1_68.lib` and `-L C:/Jinja2Cpp/install_x64/lib/static/jinja2cpp.lib`, it complained about undefined symbols.  

About EXPORTED_FUNCTIONS, it seems you need to define them separately like I did here.  It thinks that subsequent functions in the list are input files if you define multiple functions in the same `-s EXPORTED_FUNCTIONS=[]` list.  

I also want to know: how do I use EMSCRIPTEN_BINDINGS with `std::shared_ptr` the way I've used them in this app?  

Anyway, yeah, please help.  Thanks in advance for any replies and/or help.

**Comment by kripken** [comment]
`boost_system-vc141-mt-x64-1_68` sounds like an x64-specific build of the library. I think emcc might not find code it can use, so it ignores it. Running with EMCC_DEBUG=1 in the env should show more info about that.

To use `boost_system` you'd need to port it using emcc, instead of using a native build for your system's architecture, see https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries

**Comment by DragonOsman** [comment]
And if I want to bring in environment variables with Module.ENV, do I do that on the command line or my Node.js code?  If in the Node.js code, would it be after the `require` function?  [I'm planning to use the WASM module on the backend through Node rather than as an ES6 module since it's a webserver).  

So I have to compile the `jinja2cpp` and `boost_system` libraries to bitcode first?  What commands should I use for that in this case?  And how can I make sure that emcc compiles for x64 architecture and is able to find the code it needs in the libraries?  

Is EMCC_DEBUG=1 a "-s X=Y" type flag?  

And since my code uses `std::shared_ptr`, I'll have to use the `EMSCRIPTEN_BINDINGS` function macro.  Am I correct in assuming it'd be something like the following?
```cpp
EMSCRIPTEN_BINDINGS(better_smart_pointers)
{
    const auto doc_root class_<std::string>("std::string")
        .smart_ptr_constructor("std::string", &std::make_shared<std::string>(argv[3]))
        ;

}
```
In my `main` function, I have this code:
```cpp
const auto address = boost::asio::ip::make_address(argv[1]);
const auto port = static_cast<unsigned short>(std::atoi(argv[2]));
const auto doc_root = std::make_shared<std::string>(argv[3]);
const auto threads = std::max<int>(1, std::atoi(argv[4]));
```
I'm also using `std::shared_ptr` in a similar way at others places in the code, too.  So do I put an `EMSCRIPTEN_BINDINGS` block below the line where I initialize `doc_root`, or do I have to initialize it as a binding from the get-go?  If it's the former, then like this?
```cpp
const auto address = boost::asio::ip::make_address(argv[1]);
const auto port = static_cast<unsigned short>(std::atoi(argv[2]));
const auto doc_root = std::make_shared<std::string>(argv[3]);
const auto threads = std::max<int>(1, std::atoi(argv[4]));

EMSCRIPTEN_BINDINGS(better_smart_pointers)
{
    class_<std::string>("std::string")
        .smart_ptr_constructor("std::string", &std::make_shared<std::string>)
        ;
}
```
Do I have to do this to both classes and `std_shared_ptr`s in my code even when I'm going to use the module with Node.js rather than client-side JavaScript?  Or is there a way for me to not have to do it?  

Also, if I want to `#include` `emscripten.h`, do I not `#include` `iostream` and other standard library headers?  I also want to know if it's possible to use LLVM/Clang version 7 with Emscripten.  Please also let me know about anything I have to do be able to compile my webserver app to WebAssembly, as well as the Node.js code I have to write in order to actually use the app as a Node module.  Thanks in advance (and sorry if I'm asking too many questions at once).

**Comment by DragonOsman** [comment]
Just now I tried again with this command:
```
em++ -std=c++17 -Wall -pedantic -m64 -D variant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -I C:/Jinja2Cpp/install_x64/include -I C:/json/single_include -I C:/boost_1_68_0/ -I C:/Users/Osman/emsdk/emscripten/1.38.18/system/include/ currency_converter.cpp -L C:/Jinja2Cpp/install_x64/lib/static/jinja2cpp.lib -L C:/boost_1_68_0/lib64-msvc-14.1/libboost_system-vc141-mt-x64-1_68.lib -lpthread -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_cache_storage::query'] -s EXPORTED_FUNCTIONS=['_mime_type'] -s EXPORTED_FUNCTIONS=['_path_cat'] -s EXPORTED_FUNCTIONS=['_parse'] -s EXPORTED_FUNCTIONS=['_listener::listener'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_cache'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_duration'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::send_lambda'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::operator()'] -s EXPORTED_FUNCTIONS=['_server_session::server_session'] -s EXPORTED_FUNCTIONS=['_server_session::run'] -s EXPORTED_FUNCTIONS=['_server_session::do_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_write'] -s EXPORTED_FUNCTIONS=['_server_session::do_close'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_listener::on_accept'] -s EXPORTED_FUNCTIONS=['_listener::do_accept'] -s EXPORTED_FUNCTIONS=['_client_session::client_session'] -s EXPORTED_FUNCTIONS=['_client_session::convert'] -s EXPORTED_FUNCTIONS=[_client_session::run'] -s EXPORTED_FUNCTIONS=['_client_session::on_resolve'] -s EXPORTED_FUNCTIONS=['_client_session::on_connect'] -s EXPORTED_FUNCTIONS=['_client_session::on_write'] -s EXPORTED_FUNCTIONS=['_client_session::on_read'] -s EXPORTED_FUNCTIONS=['_fail'] -s EXPORTED_FUNCTIONS=['_handle_request'] -s DISABLE_EXCEPTION_CATCHING=0 -s USE_PTHREADS=1 -o currency_converter.js
```
And it gave me undefined symbol errors:
```
error: undefined symbol: _ZN5boost6system6detail24system_category_instanceE
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: _ZN5boost6system6detail25generic_category_instanceE
Error: Aborting compilation due to previous errors
ERROR:root:'C:/Users/Osman/emsdk/node/8.9.1_64bit/bin/node.exe C:\Users\Osman\emsdk\emscripten\1.38.18\src\compiler.js C:\Users\Osman\AppData\Local\Temp\tmpuasb1u.txt C:\Users\Osman\emsdk\emscripten\1.38.18\src\library_pthread.js' failed (1)
```

**Comment by yjjnls** [comment]
@DragonOsman 
If you use `EMSCRIPTEN_BINDINGS`, you have to use `--bind` in the command line.  You can ref the issue: https://github.com/kripken/emscripten/issues/2564.

I have similar question as you have, and I'm also confused about how to build a large c++ project to webassembly.  Weather to use emcc port [the doc](https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries) @kripken recommanded or use embind? Which is more porprely?

**Comment by DragonOsman** [comment]
I included the `emscripten/emscripten.h` and `emscripten/bind.h` header files, but in VS2017, when I try to use EMSCRIPTEN_BINDINGS, I see an error about it being undefined in the tooltip when I hover over it.  

Also, why did `main` suddenly become a function macro and how do I get the normal `main` function back?

**Comment by DragonOsman** [comment]
I have these classes:
```cpp
// Handles an HTTP server connection
class server_session : public std::enable_shared_from_this<server_session>
{
	// This is the C++11 equivalent of a generic lambda.
	// The function object is used to send an HTTP message.
	struct send_lambda
	{
		server_session& self_;
		explicit send_lambda(server_session &self)
			: self_(self)
		{
		}

		template<bool isRequest, class Body, class Fields>
		void operator()(http::message<isRequest, Body, Fields>&& msg) const;
	};

	tcp::socket socket_;
	boost::asio::strand<boost::asio::io_context::executor_type> strand_;
	boost::beast::flat_buffer buffer_;
	std::shared_ptr<const std::string> doc_root_;
	http::request<http::string_body> req_;
	std::shared_ptr<void> res_;
	send_lambda lambda_;

public:
	// Take ownership of the socket
	explicit server_session(tcp::socket socket, const std::shared_ptr<const std::string>& doc_root)
		: socket_(std::move(socket)), strand_(socket_.get_executor()), doc_root_(doc_root), lambda_(*this)
	{
	}

	// Start the asynchronous operation
	void run()
	{
		do_read();
	}

	void do_read();
	void on_read(boost::system::error_code ec, std::size_t bytes_transferred);
	void on_write(boost::system::error_code ec, std::size_t bytes_transferred, bool close);
	void do_close();
};

// Accepts incoming connections and launches the sessions
class listener : public std::enable_shared_from_this<listener>
{
	tcp::acceptor acceptor_;
	tcp::socket socket_;
	std::shared_ptr<const std::string> doc_root_;

public:
	listener(boost::asio::io_context& ioc, tcp::endpoint endpoint, const std::shared_ptr<const std::string>& doc_root);

	// Start accepting incoming connections
	void run();

	void do_accept()
	{
		acceptor_.async_accept(socket_, std::bind(&listener::on_accept, shared_from_this(), std::placeholders::_1));
	}

	void on_accept(boost::system::error_code ec);
};

// This class represents a cache for storing results from the
// currency exchange API used by currencylayer.com
class cache_storage
{
public:
	cache_storage(const std::chrono::seconds &duration)
		: m_cache{}, m_duration{ duration }
	{
	}

	// This function queries the currency API after making sure
	// that the stored result(s) is/are old enough
	// It also makes a new query to the API if needed
	const json &query(const std::map<std::string, std::string> &query_data, const char *accesskey);

	std::map<std::map<std::string, std::string>, std::pair<std::chrono::time_point<std::chrono::steady_clock>, json>> &get_cache()
	{
		return m_cache;
	}

	const std::chrono::seconds &get_duration() const { return m_duration; }

private:
	std::map<std::map<std::string, std::string>, std::pair<std::chrono::time_point<std::chrono::steady_clock>, json>> m_cache;
	std::chrono::seconds m_duration;
};

// Performs an HTTP GET and stores response in cache_storage object
class client_session : public std::enable_shared_from_this<client_session>
{
	tcp::resolver resolver_;
	tcp::socket socket_;
	boost::beast::flat_buffer buffer_; // (Must persist between reads)
	http::request<http::empty_body> req_;
	http::response<http::string_body> res_;

public:
	// Resolver and socket require an io_context
	explicit client_session(boost::asio::io_context& ioc)
		: resolver_(ioc), socket_(ioc)
	{
	}

	// Perform currency conversion
	double convert(const std::string &from_currency, const std::string &to_currency, double money_amount, const char *accesskey);

	// Start the asynchronous operation
	void run(const char *host, const char *port, const char *target, int version);
	void on_resolve(boost::system::error_code ec, tcp::resolver::results_type results);
	void on_connect(boost::system::error_code ec);
	void on_write(boost::system::error_code ec, std::size_t bytes_transferred);
	void on_read(boost::system::error_code ec, std::size_t bytes_transferred);
};
```
And I want to create bindings for them.  I also have some `std::shared_ptr`s, some from `std::string` and some from those other classes (except `cache_storage`).  I'd like some help in defining the bindings.  For now I have this just below `main`:
```cpp
EMSCRIPTEN_BINDINGS(module_bindings)
{
	class_<std::string>("std::string")
		.smart_ptr_constructor("std::string", &std::make_shared<std::string>);

	class_<listener>("listener")
		.constructor(boost::asio::io_context&, tcp::endpoint, const std::shared_ptr<std::string>&)
		.function("run", &listener::run).function("")

	class_<listener>("listner")
		.smart_ptr_constructor("listener", &std::make_shared<listener>);

	class_<server_session>("server_session")
		.smart_ptr_constructor("server_session", &std::make_shared<server_session>);

	class_<client_session>("client_session")
		.smart_ptr_constructor("client_session", &std::make_shared<client_session>);
}
```
Specifically, I need help on binding the classes.

**Comment by DragonOsman** [comment]
@kripken I have this right now:
```cpp
EMSCRIPTEN_BINDINGS(module_bindings)
{
	class_<listener>("listener")
		.constructor<boost::asio::io_context&, tcp::endpoint, const std::shared_ptr<const std::string>&>()
		.smart_ptr_constructor("listener", &std::make_shared<listener>);

	class_<server_session>("server_session")
		.constructor<tcp::socket, const std::shared_ptr<const std::string>&>()
		.smart_ptr_constructor("server_session", &std::make_shared<server_session>);

	class_<client_session>("client_session")
		.constructor<boost::asio::io_context&>()
		.class_function("convert", &client_session::convert)
		.smart_ptr_constructor("client_session", &std::make_shared<client_session>);
	class_<cache_storage>("cache_storage")
		.constructor<const std::chrono::seconds&>()
		.property("m_cache", &cache_storage::m_cache, &cache_storage::get_cache)
		.property("m_duration", &cache_storage::m_duration, &cache_storage::get_duration)
		.class_function("query", &cache_storage::query);
}
``` 
for the bindings.  I'm not sure how I should write the Node.js user code for the WASM module, so I'll still need help here.  Is what I have here enough for that though?  Look at the full code here to see what's going on in the code and how the classes are being used, please ([link](https://github.com/DragonOsman/currency_converter/blob/master/currency_converter.cpp)).

Thanks in advance.

**Comment by DragonOsman** [comment]
Should I open a new issue about the bindings?  I'll do that if that'd be better.

**Comment by DragonOsman** [comment]
@kripken I tried to build my code just now with the following command, after having made the bindings code like what I've specified in earlier posts here:
```
em++ -std=c++17 -Wall -pedantic -m64 --bind -D variant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -I C:/Jinja2Cpp/install_x64/include -I C:/json/single_include -I C:/boost_1_68_0/ -I C:/Users/Osman/emsdk/emscripten/1.38.18/system/include/ currency_converter.cpp -L C:/Jinja2Cpp/install_x64/lib/static/jinja2cpp.lib -L C:/boost_1_68_0/lib64-msvc-14.1/libboost_system-vc141-mt-x64-1_68.lib -lpthread -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_cache_storage::query'] -s EXPORTED_FUNCTIONS=['_mime_type'] -s EXPORTED_FUNCTIONS=['_path_cat'] -s EXPORTED_FUNCTIONS=['_parse'] -s EXPORTED_FUNCTIONS=['_listener::listener'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_cache'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_duration'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::send_lambda'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::operator()'] -s EXPORTED_FUNCTIONS=['_server_session::server_session'] -s EXPORTED_FUNCTIONS=['_server_session::run'] -s EXPORTED_FUNCTIONS=['_server_session::do_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_write'] -s EXPORTED_FUNCTIONS=['_server_session::do_close'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_listener::on_accept'] -s EXPORTED_FUNCTIONS=['_listener::do_accept'] -s EXPORTED_FUNCTIONS=['_client_session::client_session'] -s EXPORTED_FUNCTIONS=['_client_session::convert'] -s EXPORTED_FUNCTIONS=[_client_session::run'] -s EXPORTED_FUNCTIONS=['_client_session::on_resolve'] -s EXPORTED_FUNCTIONS=['_client_session::on_connect'] -s EXPORTED_FUNCTIONS=['_client_session::on_write'] -s EXPORTED_FUNCTIONS=['_client_session::on_read'] -s EXPORTED_FUNCTIONS=['_fail'] -s EXPORTED_FUNCTIONS=['_handle_request'] -s DISABLE_EXCEPTION_CATCHING=0 -s USE_PTHREADS=1 -o currency_converter.js
```
And I had the errors documented in this Gist: https://gist.github.com/DragonOsman/07005c910bff427b05fbe6370e787255 .  Please help.

I also want to know how to use the LLVM version 7 I downloaded, that doesn't have any of the Emscripten-specific modifications, to build to WebAssembly.

**Comment by kripken** [comment]
> Is EMCC_DEBUG=1 a "-s X=Y" type flag?

That is an env var for emcc. So something like `EMCC_DEBUG=1 emcc [emcc commandline flags]` in linux.

**Comment by DragonOsman** [comment]
@kripken When I tried to use the `EMCC_WASM_BACKEND=1` flag like that, I got an error about it not recognized.  I set up the emcc environment in the shell and then ran it, but it gave me that error.  So what do I do to make those flags work?

Also, I still need an answer on this:
I tried to build my code just now with the following command, after having made the bindings code like what I've specified in earlier posts here:
```
em++ -std=c++17 -Wall -pedantic -m64 --bind -D variant_CONFIG_SELECT_VARIANT=variant_VARIANT_NONSTD -I C:/Jinja2Cpp/install_x64/include -I C:/json/single_include -I C:/boost_1_68_0/ -I C:/Users/Osman/emsdk/emscripten/1.38.18/system/include/ currency_converter.cpp -L C:/Jinja2Cpp/install_x64/lib/static/jinja2cpp.lib -L C:/boost_1_68_0/lib64-msvc-14.1/libboost_system-vc141-mt-x64-1_68.lib -lpthread -s EXPORTED_FUNCTIONS=['_main'] -s EXPORTED_FUNCTIONS=['_cache_storage::query'] -s EXPORTED_FUNCTIONS=['_mime_type'] -s EXPORTED_FUNCTIONS=['_path_cat'] -s EXPORTED_FUNCTIONS=['_parse'] -s EXPORTED_FUNCTIONS=['_listener::listener'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_cache'] -s EXPORTED_FUNCTIONS=['_cache_storage::get_duration'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::send_lambda'] -s EXPORTED_FUNCTIONS=['_server_session::send_lambda::operator()'] -s EXPORTED_FUNCTIONS=['_server_session::server_session'] -s EXPORTED_FUNCTIONS=['_server_session::run'] -s EXPORTED_FUNCTIONS=['_server_session::do_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_read'] -s EXPORTED_FUNCTIONS=['_server_session::on_write'] -s EXPORTED_FUNCTIONS=['_server_session::do_close'] -s EXPORTED_FUNCTIONS=['_listener::run'] -s EXPORTED_FUNCTIONS=['_listener::on_accept'] -s EXPORTED_FUNCTIONS=['_listener::do_accept'] -s EXPORTED_FUNCTIONS=['_client_session::client_session'] -s EXPORTED_FUNCTIONS=['_client_session::convert'] -s EXPORTED_FUNCTIONS=[_client_session::run'] -s EXPORTED_FUNCTIONS=['_client_session::on_resolve'] -s EXPORTED_FUNCTIONS=['_client_session::on_connect'] -s EXPORTED_FUNCTIONS=['_client_session::on_write'] -s EXPORTED_FUNCTIONS=['_client_session::on_read'] -s EXPORTED_FUNCTIONS=['_fail'] -s EXPORTED_FUNCTIONS=['_handle_request'] -s DISABLE_EXCEPTION_CATCHING=0 -s USE_PTHREADS=1 -o currency_converter.js
```
And I had the errors documented in this Gist: https://gist.github.com/DragonOsman/07005c910bff427b05fbe6370e787255 .  Please help.

I also want to know how to use the LLVM version 7 I downloaded, that doesn't have any of the Emscripten-specific modifications, to build to WebAssembly.

**Comment by DragonOsman** [comment]
@kripken I set the Nodejs and LLVM paths in the .emscripten configuration file to use the ones I've installed from their own websites.  I'm not sure if it'll work now, but before changing the path to the Nodejs installation, I tried running the `em++` command with `EMCC_DEBUG=1` before it and I got this error: 
```
'EMCC_DEBUG' is not recognized as an internal or external command,
operable program or batch file.
```

Please help.

**Comment by kripken** [comment]
@DragonOsman 

> is not recognized as an internal or external command, operable program or batch file

That did not look familiar to me, so I googled it and found a bunch of links to Windows-related things. As I wrote above, the syntax I mentioned works on Linux. Sorry, I don't know enough about Windows to help there, but perhaps if you search for how to set an environment variable there you can find out how.

**Comment by DragonOsman** [comment]
Oh, so I just need to set system-wide environment variables?  

I'd also like to know how to install the upstream version of the EMSDK and use LLVM version 7.0 instead of 6.0.

**Comment by DragonOsman** [comment]
@kripken I set the environment variables and then ran the same compilation command as before.  Result:
```
shared:DEBUG: EMCC_WASM_BACKEND tells us to use wasm backend
shared:ERROR: WASM_BACKEND selected but could not find lld (wasm-ld): C:/Users/Osman/emsdk/clang/e1.38.20_64bit\wasm-ld.exe
```
Where's `lld` in the emsdk distribution?  Did something go wrong in the installation, by chance?  I may have to try again in that case.  

Would you by any chance know how to build LLVM with the option to have it target WASM as well?  What setting do I add in CMake for that?

**Comment by yjjnls** [comment]
@DragonOsman have you fixed the problem, how to build boost with the embind code? I have similar problems.

**Comment by DragonOsman** [comment]
@yjjnls (and @kripken ) No.  I haven't yet.  I tried to run it after setting the environment variable, but I haven't gotten any useful debug info yet.  I set the environment variables for the WASM backend and the debugging and installed the upstream version of the SDK, but now I have that problem with the distribution I have not having wasm-ld.exe.

**Comment by DragonOsman** [comment]
I have other errors too when I try to bind my classes with EMSCRIPTEN_BINDINGS.  It can't construct the objects, and it complains about private data members and being unable to find `class_function`.  And other such stuff.  But after getting that, I now have this problem where when I try to install the SDK, I don't get wasm-ld.exe.  And because I don't have that, I can't build anything with emcc.

**Comment by DragonOsman** [comment]
@kripken Never mind, I got the flag.  

I can only find a link to download version 7.0.0 from the LLVM website.  There's no version 8.  So how do I get the Emscripten SDK to accept version 7 instead of saying it expected version 8?  Is there a way?
