### ISSUE TITLE
Mixing libraries together

### ISSUE THREAD

**Issue by VictorQueiroz** [emscripten-core/emscripten#7560]
I need to encode audio using libogg and libopus, how could I do that and export just the functions I'd need to use? Also while building libopus I notice that it does not generate .bc files but normal .a and .so files. How can I overcome that and build the whole opus library to a .bc file?

I obviously tried to build js files out of .so and .a like they were .bc files, although I get this error:
```
error: undefined symbol: CELT_INNER_PROD_IMPL
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: COMB_FILTER_CONST_IMPL
error: undefined symbol: DUAL_INNER_PROD_IMPL
error: undefined symbol: OP_PVQ_SEARCH_IMPL
error: undefined symbol: XCORR_KERNEL_IMPL
Error: Aborting compilation due to previous errors
ERROR:root:'/Storage/emsdk/node/8.9.1_64bit/bin/node /Storage/emsdk/emscripten/1.38.19/src/compiler.js /tmp/tmp90y0kg2m.txt /Storage/emsdk/emscripten/1.38.19/src/library_pthread_stub.js' failed (1)
```

I also tried `-s ERROR_ON_UNDEFINED_SYMBOLS=0` and it works but I'm not sure that's the right way. 

Thank you in advance!

**Comment by yjjnls** [comment]
@brion how to link against in the final compilation?

**Comment by VictorQueiroz** [comment]
> @brion how to link against in the final compilation?

Currently I'm building common .so, .a files and then linking against in the following way:
```
emcc -O3 \
.libs/libopus.so -lopus -L .libs \
-s "EXPORTED_FUNCTIONS=['_opus_encoder_create']" \
-o opus.html
```
