### ISSUE TITLE
`sys/acl.h` file not found

### ISSUE THREAD

**Issue by ireneGP** [emscripten-core/emscripten#7565]
Hello,

We have a bunch of medium size `C` programs that would like to migrate to the `WebAssembly` ecosystem.  So basically I tried to use `emcc` and compile some single-file C code, it works fine. 

However, when I tried to substitute our compiler in the tool chain with `emcc` (by editing the makefile), I got multiple errors, something like:

````
In file included from lib/acl-internal.c:24:
./lib/acl-internal.h:27:11: fatal error: 'sys/acl.h' file not found
# include <sys/acl.h>
          ^~~~~~~~~~~
1 error generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
````

So I am writing to ask:

1. How should I solve the above issue? 

2. In general, it would be great if someone can shed some lights on the application scope of `emcc` tool chain. For instance I tried to compile a C code with `fopen` and `fwrite`, and it seems mal-functional. That seems reasonable to me because browser shouldn't have any privilege to manipulate the file system; whatever happens within the browser, it should stay in the browser. 

Thanks.

**Comment by kripken** [comment]
1) I'm not sure what ACL is, but sounds like it's a library? In general you'd need to compile it with emscripten and link it in. See https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries

2) Code with fopen/fwrite can work, but not directly on the underlying filesystem, as you said. Instead, to help port code emscripten provides an emulated filesystem. See https://kripken.github.io/emscripten-site/docs/porting/files/file_systems_overview.html#file-system-runtime-environment (There is also a way to directly access the filesystem from node, unlike in the browser, see [NODERAWFS](https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L586))

**Comment by sassman** [comment]
when running `emconfigure` it explicitly says that this dependency is not available.

```bash
$ emconfigure ./configure
[..]
checking sys/acl.h usability... no
checking sys/acl.h presence... no
```
the header belongs to [libacl1-dev](https://packages.debian.org/buster/libacl1-dev) and I suspect there is no emulation provided by the emscripten toolchain?

Or shall I recompile the lib with emscripten as well?

**Comment by sbc100** [comment]
I would try to compile the library in question without the need libacl.  libacl is linux-specific and is unlikely that emulating it would make sense.   Hopefully your library can be modified to avoid the the libacl dependency.
