### ISSUE TITLE
Multithreaded WebGL rendering

### ISSUE THREAD

**Issue by zivsha** [emscripten-core/emscripten#7581]
My goal is to be able to use OpenGL to render from multiple threads to dedicated HTML canvases per thread. This is in order to be able to have multiple view ports that allow the user to interact with, and upon interaction, update all other views accordingly (so I need to be able to share memory somehow between the threads as well).

I cannot seem to get this to work and I would appreciate any advice on what is the best practice for implementing such an application.

Below is a summary of what I managed to pull off and where I fail (I've put the question first since my trials might have been just baby steps in the process of learning and applying the capabilities of both WebAssembly and Emscripten).

**First steps:**
I tried rendering from a single thread to multiple canvases (Thanks @juj for helping with this). This was done by creating multiple canvases from the code using `EM_JS` and create a WebGL context per canvas using `emscripten_webgl_create_context`. Then, from the main thread simply iterate and switch to each context with `emscripten_webgl_make_context_current` and calling `glClearColor` with some color. 
This works nicely but will jitter when the rendering is heavier.

**Next** I wrapped some of the code into a class, which holds a `pthread` (since I failed to to this with `std::thread`), a string representing the canvas id, and and `EMSCRIPTEN_WEBGL_CONTEXT_HANDLE`.

I've looked through the `gl_*thread*` tests and tried to create something similar to `gl_only_in_pthread`. Since nothing worked for me so far I just tried compiling the test itself and try to run it:
- Compiled with: 
```
emcc main.cpp -g4 -std=c++11 -O2 -s USE_PTHREADS=1 -Wc++11-extensions -s PTHREAD_POOL_SIZE=2 -s OFFSCREENCANVAS_SUPPORT=1 -lGL -o index.html
```

- Running `python -m SimpleHTTPServer 8080` for local server.
- Tested on chrome (with `WebAssembly threads support.` enabled)
- **Result**: A black canvas that doesn't change. 😢 

Then I saw Issue #7374. So I tried with Firefox (with SharedArrayBuffer enabled) but I get:

```
Assertion failed: requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag
```

Not really sure what to try next...

**Comment by VirtualTim** [comment]
WASM threads don't currently work on Firefox.
You can track progress using: https://bugzilla.mozilla.org/show_bug.cgi?id=1389458
Or use this website: http://kangax.github.io/compat-table/es2016plus/#test-shared_memory_and_atomics
At a minimum Firefox will need 'shared memory and atomics'.

No idea why it's not working on Chrome though.
