### ISSUE TITLE
gc-sections not fully effective in wasm-ld (--export-dynamic)

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7586]
The box2D wasm is 15% bigger with the wasm backend (using the default, no wasm object files). A large part of that is the data section, which is more than twice as large as asm2wasm's, and is 12% of the total binary size.

Inspecting the contents via wasm-dis, the reason appears to be that parts of libcxxabi were not dce'd out (it is linked in in both cases). For example:

 * the string `pthread_once failure in __cxa_get_globals_fast` appears, which is from `system/lib/libcxxabi/src/cxa_exception_storage.cpp` 

In asm2wasm we run something like `-internalize -globaldce` which cleans those out.

Invoking `wasm-ld` with `--lto-O1` or 2 does not help, it actually makes it a few percent larger (maybe inlining?).

Would a wasm-ld option to run globaldce make sense perhaps? Or maybe there's more to this?

cc @sbc100

**Comment by kripken** [comment]
Talking with @dschuff there is also the question of what to do with wasm object files, which is more important for the future. Sounds like `--gc-sections` should do this? Making emcc send it to wasm-ld now, I don't see a difference in the output, but maybe I'm doing something wrong.

**Comment by sbc100** [comment]
`--gc-sections` is the default for wasm lld.

I'll take a look at the data GC issue.

**Comment by sbc100** [comment]
It looks like LTO does do globaldce be default: https://github.com/llvm-mirror/llvm/blob/master/lib/LTO/LTOCodeGenerator.cpp#L119.

Which box2d build are you looking at?  the one the emscripten tests?

**Comment by kripken** [comment]
Yes, box2d in the emscripten benchmark suite. So `./tests/runner.py benchmark.test_zzz_box2d` (have to edit the list of benchmarkers first, so the wasm backend runs, and remove the native benchmarker etc.). I suspect though that this is not special to box2d, but any codebase linking in libc++abi will hit it.

**Comment by kripken** [comment]
@sbc100 For a simpler testcase, a hello world iostream program is enough. For example
```
./emcc tests/hello_libcxx.cpp -O1
```
yields a 170K wasm in asm2wasm and 253K in the the wasm backend. And the strings mentioned in the bullet points above appear in the wasm backend's but not asm2wasm.

**Comment by kripken** [comment]
This is a large factor in why the fasta benchmark is larger too.

**Comment by kripken** [comment]
I think this is now the biggest code size issue with the wasm backend that does not have a PR open for it. @sbc100, if you don't have time to look into it I could try, maybe with some pointers (I've never looked at the lld codebase before)?

**Comment by kripken** [comment]
Investigating this, I narrowed things down to the wasm-ld flag `--export-dynamic'. Without that I no longer see the unnecessary `pthread_once failure` mentioned earlier - that is, `emcc -Os tests/hello_libcxx.cpp` no longer has that text in the wasm binary's data section, and the binary is 2% smaller overall.

The flag is necessary, though, as 4 tests fail without it: `wasmobj2.test_em_js wasmobj2.test_embind_3 wasmobj2.test_embind_unsigned wasmobj2.test_llvm_used`.

@sbc100 What does that flag do? It seems like it helps those tests pass by making EMSCRIPTEN_KEEPALIVE work, so I am guessing it preserves `@llvm.used`, but it seems to be doing more (for the testcase here with `pthread_once`, `@llvm.used` is not present).

**Comment by sbc100** [comment]
`--export-dynamic` is the current workaround for https://github.com/WebAssembly/tool-conventions/issues/64.   Without it EMSCRIPTEN_KEEPALIVE won't work.  The effect it to mark any symbols with default visibility as exports.

**Comment by kripken** [comment]
I see, ok. So the current status seems to be we have a workaround that makes EMSCRIPTEN_KEEPALIVE work for most things, but also

 * EMSCRIPTEN_KEEPALIVE does not fully work (#6233)
 * More code is kept alive than is needed, as noticed in this issue

And hopefully we can fix both by removing the workaround with the work in progress in #6233?
