### ISSUE TITLE
emscripten_async_wget2* status code successful should check 200-299 range, not only == 200

### ISSUE THREAD

**Issue by ziocleto** [emscripten-core/emscripten#7587]
Hi, 

I think this has been fixed already for Fetch API, but functions in the emscripten_async_wget2 family also suffer this bug, in particular at lines that do these kind of check:

`if (http.status == 200)`

It should really be 

`if (http.status >=200 && http.status < 300 )`

Or just have a isSuccessful(status) function that returns true if within that range.

Cheers,
Dado.

**Comment by CodeKittey** [comment]
Hey, im new here and want to start helping, so I think this one is a good starting point.
Can I just take it?

**Comment by kripken** [comment]
@CodeKittey yes, thanks! We don't have a special process here, if an issue isn't assigned, it's free for anyone to work on. Reading your PR now.
