### ISSUE TITLE
flatmax broken with wasm + embind

### ISSUE THREAD

**Issue by flatmax** [emscripten-core/emscripten#7589]
I am trying to bind a .so to a .js for use in nodejs but I can't construct my class - this works in earlier versions (see the reply below).

Version : Emscripten versoin 1.38.19
Linux system nodejs version : v8.11.4

My makefile sets up compiler flags like so (https://github.com/flatmax/WASM/blob/master/configure.ac#L65) :
`-s DEMANGLE_SUPPORT=1 -std=c++11 -O3 -fno-exceptions -s NO_EXIT_RUNTIME=1
`
The binding is like so (https://github.com/flatmax/WASM/blob/master/src/Makefile.am#L37) :
```
	@emcc --bind -s TOTAL_MEMORY=32MB --llvm-lto 1 --memory-init-file 0 $(AM_CXXFLAGS) .libs/libwasm.so -o .libs/libwasm.js
        mv .libs/libwasm.js .libs/libwasmNode.js

```
The nodejs is like so (https://github.com/flatmax/WASM/blob/master/test/RunTest.js#L33) :
```
var libwasm = require('../src/.libs/libwasmNode');
var test = new libwasm.Test;
test.sayHello();
return;
```

I get this error :
```
var test = new libwasm.Test;
           ^

TypeError: libwasm.Test is not a constructor
    at Object.<anonymous> 
```

Any pointers ?

**Comment by flatmax** [comment]
I have tested it to not work with the most recent emscripten release.
It does work with the following release versions :
emscripten : 1.37.36
nodejs : v8.10.0

**Comment by flatmax** [comment]
Are there instructions for reverting to different emscripten versions ?

thanks

Matt

**Comment by kripken** [comment]
I believe the emsdk lets you pick the version number (instead of writing `latest`). Alternatively, you can get the repos from source, and there are tags in them (or you can just bisect directly on the git repos).

**Comment by flatmax** [comment]
Which tool do you recommend me changing ?
I still am not really sure what to change here.

**Comment by kripken** [comment]
In more detail, you can do
```
./emsdk update-tags
```
and then
```
./emsdk install emscripten-1.38.18
```
to get 1.38.18. Then you can quickly bisect to find which revision broke things.

Alternatively, if you reduce your issue to a small testcase that's very easy to run and see the problem with, I can bisect that.

**Comment by flatmax** [comment]
The test case is executed like so :

git clone git@github.com:flatmax/WASM.git

cd WASM

./tools/autotools.sh

emconfigure ./configure

emmake make -j

./test/RunTest.js

**Comment by flatmax** [comment]
I tried downgrading to begin bifurcation, however it is possible that the clang version is mismatched from the emscripten verions - is that possible ?
How do you work out which clang version install for which emscripen version ?

**Comment by kripken** [comment]
Each emscripten version (1.38.21, etc.) is tagged in the clang, llvm, and emscripten repos, so they all match for a specific version. Bisecting within a version can be trickier, though.

**Comment by kripken** [comment]
I bisected this now. It broke when we switched wasm on by default. Disabling wasm (`-s WASM=0` fixes things).

It's not obvious to me why wasm breaks it. One issue is that there is a separate wasm file, but that's easily fixed (copy it to the dir, or use SINGLE_FILE), but it's still broken after that. Looks like that's an embind-specific issue.

**Comment by kripken** [comment]
Steps:
 * See https://github.com/kripken/emscripten/issues/7589#issuecomment-443914229
 * edit `src/Makefile` to add `-s WASM=0`, then `make clean` and rebuild.

I used
```
make clean
emmake make -j
cp src/.libs/*.wasm .
node  test/RunTest.js
```

**Comment by kripken** [comment]
The error `libwasm.Test is not a constructor` suggests that embind creates that dynamically somehow, and it isn't found, perhaps?

cc @chadaustin @brion
