### ISSUE TITLE
Assigning a non-existent settings attribute "DLOPEN_SUPPORT"

### ISSUE THREAD

**Issue by a2kas** [emscripten-core/emscripten#7596]
Hello, maybe do you have any idea what can be wrong here?

Error:
![1](https://user-images.githubusercontent.com/15969142/49332863-70821f00-f5bd-11e8-9513-da81abc58933.png)

Makefile
![makefile](https://user-images.githubusercontent.com/15969142/49332876-c951b780-f5bd-11e8-969e-a0ef188a20e6.png)

**Comment by kripken** [comment]
I think we removed that option at some point, and dlopen should just work automatically.
