### ISSUE TITLE
Specifying module imports

### ISSUE THREAD

**Issue by d07RiV** [emscripten-core/emscripten#7598]
I have several functions declared in C++ code that need to be defined in JS. However, I can't find where to put these functions.

I build my code with `-s WASM=1 -s MODULARIZE=1`, and import it with

    const Module = import('./module.js');
    Module().then(code => code._run());

Which then fails with `missing function`, as expected. Where am I supposed to define the missing functions in my JS code?

**Comment by kripken** [comment]
See the `--js-library` option ([emcc docs](https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html)).

**Comment by d07RiV** [comment]
Is it not possible to leave the imports unresolved, and plug them in when instantiating the module? Similar to how imports work in regular webassembly.

**Comment by kripken** [comment]
It might be nice to add an option for that if someone's interested, but there isn't one currently AFAIK.

Perhaps such an option might read them from the Module object, although I'm not sure how exactly it would know which ones to look for.

**Comment by d07RiV** [comment]
If it looked for them in the module object, then we'd be able to put the imports inside parentheses in `Module()` statement? That's what I was trying to find in the current implementation, but seems that is not the case.

Wouldn't it be relatively easy for Module object to support some sort of `imports` fields where we can put anything we want?

I've been using [cpp-wasm-loader](https://github.com/ClickSimply/cpp-wasm-loader) to use cpp files "directly" as webpack modules. Under the hood it takes the .js generated my emcc and replaces the module instantiation function, providing a hook to add imports. Unfortunately the loader is not well suited for building larger modules with many source files.

**Comment by kripken** [comment]
Yeah, it might be easy actually. The user would need to disable compile time errors on unresolved symbols (`-s ERROR_ON_UNDEFINED_SYMBOLS=0`). Then where we have `err('missing function` (in `src/jsifier.js` we could emit something that at call time checks if `Module` has that method. (With some more effort we could do it once at startup.)

If you or someone else is interested to try to implement this, I can help with any questions you have.

**Comment by JakeTherston** [comment]
Could modularized emscripten modules also be made to accept a list of functions (or even `WebAssembly.instantiate`'s full `importObject`) to make available to the instantiated web assembly module? That is, something like `module_name(importObject)`? I imagine this can *greatly* simplify this feature's implementation since you get it for free via the webassembly vm.
