### ISSUE TITLE
std::stringstream pulls FS code

### ISSUE THREAD

**Issue by d07RiV** [emscripten-core/emscripten#7606]
This simple code pulls the entire FS implementation (MEMFS, NODEFS etc):

    #include <emscripten.h>
    #include <sstream>

    EMSCRIPTEN_KEEPALIVE void test() {
      std::stringstream str;
      str << "hi";
    }

What does stringstream have to do with the file system?

**Comment by kripken** [comment]
Running this with `EMCC_DEBUG=1` and `-s VERBOSE=1`, it looks like this brings in locale support, which requires munmap, which brings in filesystem support.

You can build with `-s FILESYSTEM=0` to force it off.
