### ISSUE TITLE
std::vector of std::unique_ptr<>

### ISSUE THREAD

**Issue by Chiv76** [emscripten-core/emscripten#7646]
I can not figure out how can I push instance of std::unique_ptr<> into approptiate vector. The minimal code is:
```c++
 #include <vector>
 #include <memory>
 #include <iostream>
 int main()
 {
   std::vector<std::unique_ptr<int> > int_v;
   // catch compile error next line:
   int_v.push_back(std::unique_ptr<int>(new int(123)));
   std::cout << *(int_v.back()) << std::endl;
 }
```
Same code works fine in different c++ compilers (msvs'17)
The issue was already discussed (but rejected) here: https://github.com/juj/emsdk/issues/191
Reproduced in 1.38.20 with *no* c++11 support

**Comment by juj** [comment]
Oh hmm, adding `-std=c++11` flag does get this to pass for me without compiler errors. (Emscripten defaults to C++03 if no `-std=` is passed)

**Comment by Chiv76** [comment]
Yes, using c++11 soves the problem, but, as I've wrote in https://github.com/juj/emsdk/issues/191 I'm forced not to use c++11 due to some reasons. In c++11 environment it is possible to use emplace_back instead of push_back. Just thinking, if this code compiled fine with other pre-11 compilers, may be the real promlem is deeper than it seems at first glance.
