### ISSUE TITLE
Only call exitFullscreen when needed

### ISSUE THREAD

**Issue by schmidtk** [emscripten-core/emscripten#7676]
The `exitFullscreen` call should test that the [fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) is supported by the browser, and that an element is in fullscreen mode prior to exiting fullscreen. On most browsers this would be a no-op, but as of Chrome 71 the returned promise will be rejected and result in an error.

Related code here:
https://github.com/kripken/emscripten/blob/df84567d01fb9243b8a79f77601cda6f8f0783fc/src/library_glut.js#L318-L325

For easy reference, the Closure library has code to [test support](https://github.com/google/closure-library/blob/master/closure/goog/dom/fullscreen.js#L50-L64), [check fullscreen status](https://github.com/google/closure-library/blob/master/closure/goog/dom/fullscreen.js#L118-L130), and [exit fullscreen](https://github.com/google/closure-library/blob/master/closure/goog/dom/fullscreen.js#L99-L115) across all browsers.

**Comment by kripken** [comment]
+1

Another thing we should do here is refactor the code to have a single exitFullscreen location, in `library_browser.js` probably (right now that quoted glut logic also appears in glfw, for example).

**Comment by Rishabh0712** [comment]
Hii. I am a beginner and would like to give it a try. Please provide some more info.

**Comment by kripken** [comment]
I think this may have been done already. To check, I'd search for exitFullscreen in `src/*.js`, and see whether a single central function is used, or whether there is code duplication.

Can also look at the git log of the relevant files, like `src/library_browser.js` that was mentioned earlier, as I think we changed things in the last few months.

**Comment by schmidtk** [comment]
Confirmed, this is now fixed. Thank you!
