### ISSUE TITLE
`getTempRet0` and similar missing/obfuscated when compiling to asm.js

### ISSUE THREAD

**Issue by dfellis** [emscripten-core/emscripten#7692]
Hi,

When I [upgraded a library that uses emscripten](https://github.com/uber/h3-js/pull/28/files#diff-b0ba2aae6a5133534a8b2a038375402eR42) from 1.37.40 to 1.38.21 recently, I noticed that `getTempRet0`, which is vital to the library being able to process 64-bit integer responses correctly, had disappeared.

I found it still in the compiled code and then poked around and saw it in an `asmLibraryArg` object under an obfuscated name, so I was able to de-obfuscate the functions and re-attach them to interact with the C code, but I wanted to bring this problem to your attention since I don't think it was intentional? (The comment on [this diff](https://github.com/kripken/emscripten/commit/c5a455873a5ee84ac07961e06a3a58204e5813b2) implies that these functions are still supposed to be accessible, and perhaps they are for WASM-based libraries?)

There are very few references to `getTempRet0` in the documentation, and none of them state where this function is supposed to be attached, so if there is another place it is accessible from without needing to deobfuscate it back out, that would be very helpful (for both this library and to state explicitly in the docs).

Regards,

David Ellis

**Comment by kripken** [comment]
Given the version jump here (1.37.40 to 1.38.21), I am guessing the issue might be that we used to export it by default, and we either stopped doing so or we made the optimizer powerful enough to remove it (both happened, I'm not not sure which caused your case to break - could be both). Are you calling `Module.getTempRet0` from your JS code? If so, that would be consistent with that theory.

If you call getTempRet0 from a place the optimizer can see it, it will not remove it. However, if you call it on `Module`, you need to export it, and it's possible we don't support that currently - we should add it to `exportRuntime` in `src/modules.js`.

**Comment by dfellis** [comment]
Yep, we call it from our code so we can take a 64-bit integer result and transform it into hex string JS-side (and then back from hex string to a pair of 32-bit integers before passing back into other C functions).

And yes, when I tried to manually include it in the cli arg `EXTRA_EXPORTED_RUNTIME_METHODS` it didn't show up.

**Comment by kripken** [comment]
Good, sounds like that's it then. This PR should fix the exporting bug: #7694
