### ISSUE TITLE
Too many variables declared (only 32767 allowed)

### ISSUE THREAD

**Issue by davidagraf** [emscripten-core/emscripten#770]
Hi
I am trying to compile imagemagick with emscripten. Unfortunately, it is not working properly. I am trying to do it as explained at http://mozakai.blogspot.ch/2012/03/howto-port-cc-library-to-javascript.html.

But it ends with the assertion:

Traceback (most recent call last):
  File "/home/vagrant/emscripten/emscripten/emscripten.py", line 402, in <module>
    temp_files.run_and_clean(lambda: main(keywords))
  File "/home/vagrant/emscripten/emscripten/tools/shared.py", line 433, in run_and_clean
    func()
  File "/home/vagrant/emscripten/emscripten/emscripten.py", line 402, in <lambda>
    temp_files.run_and_clean(lambda: main(keywords))
  File "/home/vagrant/emscripten/emscripten/emscripten.py", line 358, in main
    emscript(args.infile, settings, args.outfile, libraries)
  File "/home/vagrant/emscripten/emscripten/emscripten.py", line 228, in emscript
    for func_js, curr_forwarded_data in outputs:
ValueError: need more than 1 value to unpack
Traceback (most recent call last):
  File "/home/vagrant/emscripten/emscripten/emcc", line 1087, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/vagrant/emscripten/emscripten/tools/shared.py", line 908, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js: 

Here are the commands I am executing:
1) wget http://www.imagemagick.org/download/ImageMagick.tar.gz
2) tar xfz ImageMagick.tar.gz
3) cd ImageMagick-*
4) doing the following patches (no clue if they make sense):

```
--- a/magick/blob.c
+++ b/magick/blob.c
@@ -2183,8 +2183,9 @@ MagickExport unsigned char *MapBlob(int file,const MapMode mode,
       map=(unsigned char *) mmap((char *) NULL,length,protection,flags,file,
         (off_t) offset);
 #if defined(MAGICKCORE_HAVE_POSIX_MADVISE)
-      (void) posix_madvise(map,length,POSIX_MADV_SEQUENTIAL |
-        POSIX_MADV_WILLNEED);
+      (void) posix_madvise(map,length,0);
+//      (void) posix_madvise(map,length,POSIX_MADV_SEQUENTIAL |
+//        POSIX_MADV_WILLNEED);
 #endif
       break;
     }
--- a/magick/magick.h
+++ b/magick/magick.h
@@ -18,6 +18,8 @@
 #ifndef _MAGICKCORE_MAGICK_H
 #define _MAGICKCORE_MAGICK_H

+#define SSIZE_MAX  0x7fffffffL
+
 #if defined(__cplusplus) || defined(c_plusplus)
 extern "C" {
 #endif
```

5) emconfigure ./configure
6) emmake make
7) emcc utilities/convert.o ./wand/.libs/libMagickWand-Q16.a ./magick/.libs/libMagickCore-Q16.a -o convert.js

Since I am hitting an assertion, it seems to be a bug. But I guess I am also doing something wrong here ...

**Comment by KnicKnic** [comment]
FYI I did this for webassembly https://github.com/KnicKnic/WASM-ImageMagick
