### ISSUE TITLE
parseTools.js bug with inline CSS

### ISSUE THREAD

**Issue by rspq** [emscripten-core/emscripten#7700]
A regression between 1.38.6 and 1.38.21 :

My --shell-file contains CSS with identity selectors like so:

    #screenContainer {
      position:fixed;
      top:0px;
      bottom:0px;
      left:0px; right:0px;
    }

If the line with the selector (#screenContainer) has any leading whitespace then parseTools processes it without issue. If however the line has no whitespace then you get this:

````
parseTools.js preprocessor error in undefined:32: "#screenContainer {"!

undefined:106
      throw e;
      ^
Unclear preprocessor command: #screenContainer {
Traceback (most recent call last):
  File "/Users/reuben/Downloads/emsdk-portable/emscripten/1.38.21/emcc.py", line 3090, in <module>
    sys.exit(run())
  File "/Users/reuben/Downloads/emsdk-portable/emscripten/1.38.21/emcc.py", line 2092, in run
    memfile, optimizer)
  File "/Users/reuben/Downloads/emsdk-portable/emscripten/1.38.21/emcc.py", line 2734, in generate_html
    shell = read_and_preprocess(options.shell_path)
````

**Comment by kripken** [comment]
Hmm, yes, we enabled the preprocessor on HTML in #6755. It does indeed look at lines starting with `#`, without preceding whitespace.

We could make it ignore lines it doesn't recognize, which would fix this. That seems reasonable to me, but I'm not 100% sure.

**Comment by rspq** [comment]
If I had a vote I'd say ignoring unrecognised preprocessor directives would be an acceptable fix.

(But I'm now really curious as to why C preprocessing is being done on HTML at all... seems an odd thing to want to do.)

**Comment by kripken** [comment]
The motivation is that the HTML can contain JS, and it can be useful to preprocess it like our other JS, see https://github.com/kripken/emscripten/pull/6510#issuecomment-387243820

Which makes me think, another option here might be to limit the preprocessor on HTML to `<script>..</script>` sections.

**Comment by eclecticdave** [comment]
Since I contributed the html preprocessor code, I'll take a look at this.

Both approaches above have pros and cons.  On the one hand I'm slightly reluctant to only check between <script> and </script> as someone might find it useful to preprocess outside those.  In particular #include-ing one html file inside another seems potentially useful.

On the other hand, even if we parse more carefully, at least some of the syntax is ambiguous with valid CSS (for example #else and #endif could be valid css, especially if the open brace is on the next line)

What if instead we turn off preprocessing between <style> and </style>? Would that work for you @rspq?

**Comment by rspq** [comment]
Works for me, I think (it's not my area of expertise, TBH). Given how insignificant carriage returns are in HTML, might there be a profoundly unlikely edge case with anchors? E.g.:

    <a href="
    #C4">Jump to Chapter 4</a>

**Comment by eclecticdave** [comment]
Hmm, yes it's not impossible.  Although TBH something similar could in principle happen with a JS file as well and, although there's always scope for tightening the code up, I don't think it's possible to eliminate all edge cases without writing an out-and-out HTML/JS parser.  For example there's nothing stopping you from doing:

```<a href="
#else
">Jump to alternative place</a>```

which would baffle anything but a full-blown parser.

**Comment by rspq** [comment]
Ok, well no need to go so far as that! I think just warning on unknown preproc directives and not doing any preproc at all inside <style> blocks will be more than sufficient to address this.
