### ISSUE TITLE
Linking wasm object files to another wasm object file?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7702]
E.g. `emcc a.o b.o -o c.o` should link two object files into another, which happens in some build systems, and is tested in the `other` test suite. Trying that with wasm object files, we use llvm-link in that code path, which won't work. I tried to replace it with `wasm-ld --relocatable` (so the output will be a wasm object file with relocations), which seems to work in some cases, but crashes on e.g.
```
python embuilder.py build sdl2-mixer
```
The specific command from there that fails:
```
wasm-ld --export-dynamic -z stack-size=5242880 --global-base=1024 --initial-memory=16777216 -o output.o --no-entry --allow-undefined --import-memory --import-table --export __wasm_call_ctors --export __data_end --lto-O0 playwave.o libSDL2_mixer.a --max-memory=16777216 -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export main --export malloc --export free --export setThrew --export __errno_location --export fflush --relocatable
```
Without `--relocatable` it does not crash.

I'm not sure if this is expected to work, though? cc @sbc100 

[libSDL2_mixer.a.zip](https://github.com/kripken/emscripten/files/2692737/libSDL2_mixer.a.zip)
[playwave.o.zip](https://github.com/kripken/emscripten/files/2692738/playwave.o.zip)

**Comment by sbc100** [comment]
Yes, `ld -r` should work.

Any crash bug in lld should be filed in the llvm bug tracker (which i can do when I'm back at work in Jan if you like).

**Comment by sbc100** [comment]
By the way "gcc a.o b.o -o c.o" produces an executable output, not an object file.    The fact that its called `c.o` is not relevant to gcc or clang and probably should be for emcc either.

**Comment by kripken** [comment]
Ok, opened this bug with simplified STR: https://bugs.llvm.org/show_bug.cgi?id=40204

(Yeah, it's weird that emcc cares about the output suffix - it has since the beginning, which was probably a bad decision, I agree.)

**Comment by sbc100** [comment]
Does emscripten actually depend on being able to do "emcc a.o b.o -o c.o"?    Since its non-standard it would be nice to remove this ability.  We could replace it with `emcc -Wl,-r` or add a new `emld` tool?

**Comment by kripken** [comment]
Hmm, I guess the question is how you consider "depend". If we remove it, some tests will break, but perhaps those are not very important ones, as I don't think poppler or other real-world ones would? But probably some user out there would be surprised by removing it.

In any case, this is not urgent for me, my wip branch with wasm-object-files-by-default does not require it (which was the reason for me opening this issue).
