### ISSUE TITLE
Question about extension for library files when compiling with LLVM

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#7705]
If I'm compiling a library with LLVM that I want to use when building code with Emscripten, should I use the .bc extension?  Or would the .lib extension be fine?

Note: I built "vanilla" LLVM from sources after getting it from the upstream Git monorepo and am using it with the Emcc WASM Backend, instead of using the Fastcomp one.  And I built Emscripten and Binaryen manually form source.

I read in the /src/settings.js file that even with the setting where it should warn about unaligned memory, it only does so with asm.js as of Sep. 2 2014.  I hope this has been fixed by now.

**Comment by dschuff** [comment]
Hi Osman,
If you mean you want to use bare clang (without the emcc wrapper or
emscripten sysroot) to compile code compatible with emscripten, then that
currently won't work. Eventually it might be nice to get to the point where
you wouldn't need the emscripten-specific flags that emcc provides, but it
would be a challenge to build compatible modules without any of
emscripten's headers, and it's not clear what the benefit might be. What is
the use case you have in mind?
