### ISSUE TITLE
Newer releases of emscripten are slower than older ones

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#7712]
We're still stuck on 1.37.20. We'd love to upgrade to the latest version but 1.38.21 is 15% slower than 1.37.20 in my testing (7 minutes vs. 6 minutes for a full build). Here are our compiler flags relevant to optimizations in case that matters:

```
--js-library
--pre-js
--llvm-lto 0
--llvm-opts 2
--memory-init-file 1
-fno-exceptions
-O3
-s ABORTING_MALLOC=0
-s ALLOW_MEMORY_GROWTH=1
-s DISABLE_EXCEPTION_CATCHING=1
-s ERROR_ON_UNDEFINED_SYMBOLS=1
-s NO_EXIT_RUNTIME=1
-s NO_FILESYSTEM=1
```

Is it expected that emscripten's compiler is getting slower over time? I'd like to upgrade to a newer version of emscripten to keep up with releases, but our team is not likely to upgrade if it makes the developer experience worse.

Edit: perhaps effort to reduce emscripten's output size are making the compiler take longer? Our compiled output is 2.8% smaller in 1.38.21 than in 1.37.20. 2.8% smaller output isn't worth a whole extra minute of build time for us. Perhaps there's a way to improve our build times by disabling some optional compiler features that have been added since 1.37.20?

**Comment by juj** [comment]
There exists the tool toolchain_profiler.py you can use to record performance profiles of the two compiler versions to help find out what causes the regression in build times.

**Comment by kripken** [comment]
In general, yes, as more compiler optimizations are added compilers do tend to get slower. Specifically in emscripten, `-O3`is "optimize at all costs" mode, so compile time is not something we focus on there, and we've added useful things like metadce at that level. 

On the other hand, other optimization modes should be the same speed, in particular `-O0` ("don't optimize") and `-O1` ("optimize a little"). I'm not sure about `-O2` (I don't think emscripten added stuff there, but LLVM might have).

**Comment by evanw** [comment]
Thanks for your help! That profiler is really helpful. I didn't know it existed. It looks like the problem is a combination of LLVM getting slower and linking taking 30 seconds longer than it used to. I'll try messing with optimization levels and other compiler flags and see what I can do.
