### ISSUE TITLE
Emscripten reproducible builds?

### ISSUE THREAD

**Issue by paulshapiro** [emscripten-core/emscripten#7714]
Hi there,

We're having trouble isolating the reason for variance between emscripten builds of the same source.

I'm able to produce repeatable builds, but different systems are unable to do so, despite having the same boost build product.

Is there anything at the user or system level, or anything related to the emscripten toolchain that could be causing this?

Here's a bunch of background where we try to figure it out. The discussion about reproducible builds starts about halfway down.

https://github.com/mymonero/mymonero-core-js/pull/71#issuecomment-449217836

Thanks

Paul

**Comment by kripken** [comment]
This may be an LLVM issue. LLVM guarantees deterministic builds on the same machine, but I've seen differences e.g. in the same LLVM build on MacOS and Linux emit something different, even when cross-compiling.

Emscripten also guarantees deterministic builds on the same machine, so if LLVM gave us the same input we should produce the same output - if not, that's a bug.

To investigate this, you can build with `EMCC_DEBUG=1` in the env, then you'll find `/tmp/emscripten_temp` containing the temp files during compilation. Comparing those between machines can help see where the difference originates.

**Comment by gutenye** [comment]
@kripken Thanks for the help, here're my checksum across two machines (macOS and Ubuntu):

Comparision of build output checksum
```
build/MyMoneroCoreCpp_ASMJS.asm.js: FAILED
build/MyMoneroCoreCpp_ASMJS.js: FAILED
build/MyMoneroCoreCpp_WASM.js: OK
build/MyMoneroCoreCpp_WASM.wasm: FAILED
sha256sum: WARNING: 3 computed checksums did NOT match
```

Comparision of temp files checksum
```
emscripten_temp/emcc-0-basebc.bc: FAILED
emscripten_temp/emcc-0-lto.bc: FAILED
emscripten_temp/emcc-1-linktime.bc: FAILED
emscripten_temp/emcc-1-original.js: FAILED
emscripten_temp/emcc-2-meminit.js: FAILED
emscripten_temp/emcc-2-original.js: OK
emscripten_temp/emcc-2-pre-post.js: FAILED
emscripten_temp/emcc-3-js_opts_0.json: FAILED
emscripten_temp/emcc-3-meminit.js: FAILED
emscripten_temp/emcc-4-js_opts_1.json: FAILED
emscripten_temp/emcc-4-module_export_name_substitution.js: OK
emscripten_temp/emcc-4-pre-eval-ctors.js: OK
emscripten_temp/emcc-5-js_opts_2.js: FAILED
emscripten_temp/emcc-5-preclean.js: OK
emscripten_temp/emcc-5-preclean.wasm: FAILED
emscripten_temp/emcc-6-modularized.js: FAILED
emscripten_temp/emcc-6-postclean.js: OK
emscripten_temp/emcc-6-postclean.wasm: FAILED
emscripten_temp/emcc-7-modularized.js: OK
emscripten_temp/emcc-7-module_export_name_substitution.js: FAILED
emscripten_temp/emcc-8-module_export_name_substitution.js: OK
emscripten_temp/MyMoneroCoreCpp_ASMJS.js.mem: FAILED
emscripten_temp/MyMoneroCoreCpp_WASM.js.mem: FAILED
emscripten_temp/MyMoneroCoreCpp_WASM.temp.asm.js: FAILED
emscripten_temp/pre-eval-ctors.wasm: FAILED
sha256sum: emscripten_temp/tmpx70dNf.js.mem: No such file or directory
emscripten_temp/tmpx70dNf.js.mem: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
sha256sum: WARNING: 18 computed checksums did NOT match
```

I have no idea what each temp file does, can you help me where should I look and how to compare them to find out the issue? If you need anything, please let me know.

**Comment by kripken** [comment]
> emscripten_temp/emcc-0-basebc.bc

That's the LLVM bitcode, at the very start of what emcc does. So if it's different even there, that means the problem is in LLVM - it's before we do anything to the bitcode. In other words, the issue is either in LLVM compiling source code to bitcode, or in LLVM linking that bitcode together.
