### ISSUE TITLE
How to port header-only C++ libraries to WebAssembly?

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#7716]
The current port of standalone Asio is using an older version, and I want to try porting the latest one.  I found a tutorial on porting a library that has code that needs to be linked against, but I want to port Asio which is a header-only library.  Some help and advice pointing me to the right direction would be appreciated.  Thanks in advance.

**Comment by gabrielcuvillier** [comment]
Normally, you have nothing to do. Just to include the headers in your project, and compile your project with emscripten. I use header-only Boost and GLM without any issues.

Note that you must take care that the paths to the headers are correctly set-up. There is many ways to do this (depending if you use CMake, configure, etc...). As a first start to check everything is OK, just copy the library header files to the "<emsdk>/emscripten/<version>/system/include" folder. They should be taken into account automatically.

**Comment by podsvirov** [comment]
Hello @DragonOsman, I trying to upstream port patches to asio there chriskohlhoff/asio#419.
