### ISSUE TITLE
EXPORT_ALL=1 not working when WASM=0

### ISSUE THREAD

**Issue by marwin1991** [emscripten-core/emscripten#7721]
To reproduce this you can use docker image

https://github.com/libamtrack/DockerFiles/tree/master/libamtrackForJs

And change in docker-compose WASM to 0
then when you want to use it 
"Assertion failed: Cannot call unknown function AT_beta_from_E_single, make sure it is exported"

when you compile with WASM to 1 everything works nice.
 
this calls function from Module
https://github.com/libamtrack/web/blob/master/src/functionsFromC/AT_beta_from_E_single.js
argument can be f.e. 10.0

**Comment by marwin1991** [comment]
when you explicite export functions 
https://github.com/libamtrack/library/blob/forjs-funs-explicite/distributions/JavaScript/compile_to_js.sh
it works.
I've checked twice but still i can be my fault

**Comment by kripken** [comment]
It would be easier to debug this with a small reduced testcase, if that's possible (and without docker, which is preventing me from taking a look at this now).

**Comment by kripken** [comment]
One guess though is that metadce runs in wasm -O3 and above, and perhaps it is not aware of EXPORT_ALL.

**Comment by marwin1991** [comment]
i will prepare a simple test case repo for you
