### ISSUE TITLE
wrf-chem with kpp error

### ISSUE THREAD

**Issue by fipoucat** [emscripten-core/emscripten#7794]
I am trying to compile kpp but getting many warnings creating an error related to compiling a c function 
compile kpp
  /Users/sarr/work/Build_WRF/LIBS/ycc/bin/yacc -d scan.y
  gcc -O -c y.tab.c
scan.y:96:4: warning: implicit declaration of function 'CmdJacobian' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdJacobian( yystack.l_mark[0].str );
          ^
scan.y:99:4: warning: implicit declaration of function 'CmdHessian' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdHessian( yystack.l_mark[0].str );
          ^
scan.y:102:4: warning: implicit declaration of function 'CmdStoicmat' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdStoicmat( yystack.l_mark[0].str );
          ^
scan.y:105:4: warning: implicit declaration of function 'CmdDouble' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdDouble( yystack.l_mark[0].str );
          ^
scan.y:108:4: warning: implicit declaration of function 'CmdReorder' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdReorder( yystack.l_mark[0].str );
          ^
scan.y:111:4: warning: implicit declaration of function 'CmdMex' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdMex( yystack.l_mark[0].str );
          ^
scan.y:114:4: warning: implicit declaration of function 'CmdDummyindex' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdDummyindex( yystack.l_mark[0].str );
          ^
scan.y:117:4: warning: implicit declaration of function 'CmdEqntags' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdEqntags( yystack.l_mark[0].str );
          ^
scan.y:120:4: warning: implicit declaration of function 'CmdFunction' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdFunction( yystack.l_mark[0].str );
          ^
scan.y:123:4: warning: implicit declaration of function 'CmdStochastic' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdStochastic( yystack.l_mark[0].str );
          ^
scan.y:154:4: warning: implicit declaration of function 'CheckAll' is invalid in C99
      [-Wimplicit-function-declaration]
        { CheckAll(); }
          ^
scan.y:156:4: warning: implicit declaration of function 'LookAtAll' is invalid in C99
      [-Wimplicit-function-declaration]
        { LookAtAll(); }
          ^
scan.y:158:4: warning: implicit declaration of function 'TransportAll' is invalid in C99
      [-Wimplicit-function-declaration]
        { TransportAll(); }
          ^
scan.y:168:4: warning: implicit declaration of function 'CmdUse' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdUse( yystack.l_mark[0].str ); }
          ^
scan.y:170:4: warning: implicit declaration of function 'CmdLanguage' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdLanguage( yystack.l_mark[0].str ); }
          ^
scan.y:172:4: warning: implicit declaration of function 'DefineInitializeNbr' is invalid in C99
      [-Wimplicit-function-declaration]
        { DefineInitializeNbr( yystack.l_mark[0].str ); }
          ^
scan.y:174:4: warning: implicit declaration of function 'DefineXGrid' is invalid in C99
      [-Wimplicit-function-declaration]
        { DefineXGrid( yystack.l_mark[0].str ); }
          ^
scan.y:176:4: warning: implicit declaration of function 'DefineYGrid' is invalid in C99
      [-Wimplicit-function-declaration]
        { DefineYGrid( yystack.l_mark[0].str ); }
          ^
scan.y:178:4: warning: implicit declaration of function 'DefineZGrid' is invalid in C99
      [-Wimplicit-function-declaration]
        { DefineZGrid( yystack.l_mark[0].str ); }
          ^
scan.y:187:4: warning: implicit declaration of function 'CmdIntegrator' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdIntegrator( yystack.l_mark[0].str ); }
          ^
scan.y:189:4: warning: implicit declaration of function 'CmdDriver' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdDriver( yystack.l_mark[0].str ); }
          ^
scan.y:191:4: warning: implicit declaration of function 'CmdRun' is invalid in C99
      [-Wimplicit-function-declaration]
        { CmdRun( yystack.l_mark[0].str ); }
          ^
scan.y:195:4: warning: implicit declaration of function 'SparseData' is invalid in C99
      [-Wimplicit-function-declaration]
        { SparseData( yystack.l_mark[0].str );
          ^
scan.y:198:4: warning: implicit declaration of function 'WRFConform' is invalid in C99
      [-Wimplicit-function-declaration]
        { WRFConform(); 
          ^
scan.y:251:4: warning: implicit declaration of function 'AddUseFile' is invalid in C99
      [-Wimplicit-function-declaration]
        { AddUseFile( yystack.l_mark[0].str );
          ^
25 warnings generated.
  flex scan.l
make[1]: *** [lex.yy.c] Error 1
Could someone help soving this problem?

**Comment by lacstorm** [comment]
Hi, have you solved the problem?
I met the same one as yours.
Hope for your reply.
Thanks.

**Comment by fipoucat** [comment]
I was using mac and was recommended to use a linux system, I don't have now.
