### ISSUE TITLE
Simplify memory setup / remove special JS allocation modes?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7795]
I'd like to simplify our memory setup code by removing the ability to do "special" allocations in JS. That is, right now you can do these allocations from JS:

 * Stack allocation (calls `stackAlloc` in compiled code)
 * Heap/normal allocation (calls `malloc` in compiled code)
 * Static allocation (done in JS during startup, before static memory is "sealed")
 * Dynamic allocation (done in JS during startup, after static memory is "sealed", from the area sbrk uses)

I propose keeping the first two (which we can't remove, they are the absolute minimum) and removing the latter two.

The benefits of removing them:

 * Remove a bunch of JS setup/startup code.
 * Simplify the overall model of how memory is set up, less to think about.
 * Allow moving **all** the memory setup and management logic into compiled code.
 * Allow further optimizations like the ctor evaller doing mallocs at compile time.
 * Simplify our JS/wasm ABI, that is, make our wasm more standalone and easier to run without special JS.

The downsides:

 * No more JS allocation of memory in a synchronous way during startup - since compiled code will manage memory, and we must call into it for `malloc/stackAlloc`, we must wait for compiled code to be ready first.
 * Existing JS features that depend on the existing APIs need some work, and in particular some may need to become async. This may actually increase code size somewhat for users of those features.
 * Existing external (not in-tree) users of those internal allocation APIs will break. We've never really recommended these APIs, and they are marked as internal, e.g. http://kripken.github.io/emscripten-site/docs/api_reference/advanced-apis.html?highlight=allocate#allocate , so hopefully there are not many such users. Opening this issue to discuss that.

**Comment by dschuff** [comment]
I regret that I have but one +1 to give for this proposal....

**Comment by kripken** [comment]
@juj, any thoughts/concerns here before I start to look into this?

**Comment by juj** [comment]
How do you see the extent of this to go:
 - Does this mean that the `STATICTOP` variable would be removed?
 - How about the `staticSealed` model? Would that go away?
 - Will the bottom address of the dynamic memory area (`DYNAMIC_BASE`) then be dictated by compiled code up front? 

The `sbrk()` model of growing dynamic memory area is still intended to stay, I suppose? (I do like that model, wish we'd have that paired with page unloading in the future, and/or `sbrk()` shrinking aware malloc that we could experiment with freeing committed physical memory at runtime)

The `allocate()` function is great to be removed, we do want to have a code flow that statically/at compile time knows what kind of allocations are being performed.

Although I think there may still be a need to have a `staticAlloc()` function that is able to allocate bytes from .js code by bumping `STATICTOP` before startup? If that can be removed with a better model that does not grow code size and is not constraining, especially with multithreading in mind, then I don't mind if `staticAlloc()` is removed. (If a replacement for `staticAlloc()` would end up to be some kind of asynchronous(?) post-globals-init model that takes up more code size than current form, then that may be troublesome)

**Comment by kripken** [comment]
> Does this mean that the STATICTOP variable would be removed?

Yes, JS would no longer manage any memory allocation. It would just call into wasm/asm.js for stackAlloc or malloc. (should be a nice shrinking of our JS glue)

> How about the staticSealed model? Would that go away?

Yes.

> Will the bottom address of the dynamic memory area (DYNAMIC_BASE) then be dictated by compiled code up front?

Yes.

>  The sbrk() model of growing dynamic memory area is still  intended to stay, I suppose?

Yes. Still sbrk() as normal, but done all in compiled code (it already mostly is, just the initial location came from JS).

> The allocate() function is great to be removed, we do  want to have a code flow that statically/at compile time knows what kind  of allocations are being performed.

Note that `allocate` may be orthogonal to this issue: it may stay around, but just support stack and malloc allocation, removing 2/4 of the modes. So it would be simplified. But yes, I agree we should look at removing it separately.

But yes, as you said in the second part of your comment, statically handling JS static allocations may be useful here, and may end up replacing some allocate()s (the static and perhaps dynamic ones).

>  Although I think there may still be a need to have a staticAlloc() function that is able to allocate bytes from .js code by bumping STATICTOP  before startup? If that can be removed with a better model that does  not grow code size and is not constraining, especially with  multithreading in mind, then I don't mind if staticAlloc() is removed. (If a replacement for staticAlloc()  would end up to be some kind of asynchronous(?) post-globals-init model  that takes up more code size than current form, then that may be  troublesome)

Yes, this may end up the hard part here - it may need to be asynchronous if it is to be in JS. Other options are to statically compute JS static allocations, as just mentioned. Another option is for me to move some things into compiled code. I hope to avoid any async messiness with both of those, but I can't be sure til I try.

**Comment by rianhunter** [comment]
Will it still be possible to call malloc / free from the JS / host code? Sometimes host functions need to return dynamically allocated memory to the hosted code.

**Comment by juj** [comment]
I am in favor of removing `STATICTOP`, `staticSealed` and `staticAlloc`, and `allocate`. It feels like there is a great flexibility that is provided if JS code can decide where the dynamic memory area starts, when it is compiling a WebAssembly module, i.e. JS code would define `DYNAMIC_BASE/DYNAMICTOP_PTR`, and pass it off as an import to the WebAssembly module? That way JS code will have the power of bumping up `DYNAMIC_BASE/DYNAMICTOP_PTR` synchronously before it starts to compile, in case there will be a need to add blocks of memory to the heap at startup.

If instead `DYNAMIC_BASE/DYNAMICTOP_PTR` is burned in to the WebAssembly module at compilation time, it may make JS side too inflexible to manage startup process on the heap, and it may need to awkwardly split up its initialization in multiple parts. Two examples that come to mind are multithreaded startup logic, where main thread allocates pointers to the heap to share info to pthreads, and MEMFS&ASMFS files preloading on the heap before application start. Does it gain anything to have Wasm module side establish the starting value of the dynamic memory area at compilation time?

**Comment by kripken** [comment]
> Does it gain anything to have Wasm module side establish the starting value of the dynamic memory area at compilation time?

Yes, it allows the optimizer to pre-execute code at compile time. Say if the program starts with a few mallocs, those can be done at compile time, improving startup and download times.

> Two examples that come to mind are multithreaded startup logic, where main thread allocates pointers to the heap to share info to pthreads,

How many does it allocate? If it's just a few, then statically allocating them at compile time seems ok?

> MEMFS&ASMFS files preloading on the heap before application start. 

That is async anyhow, and so it seems like it could use malloc - so it just waits for the wasm to be ready to run?

**Comment by kripken** [comment]
ping @juj - see comments above.

**Comment by juj** [comment]
sgtm

**Comment by kripken** [comment]
I still think this is worth doing.

**Comment by kripken** [comment]
I believe this has been done.
