### ISSUE TITLE
[Feature request] Provide opt-out from certain generated code

### ISSUE THREAD

**Issue by surma** [emscripten-core/emscripten#7802]
The glue code can contain a lot of sections that turn out to be unnecessary. For example: 

- There is an implementation of a String-to-UTF8 converter. AFAICT, it uses `TextDecoder` when available, but will use the DIY version as a fallback. I can save a good amount of bytes if I know that `TextDecoder` will be available.
- The entire list of stringifications of error messages is something that is useful in debug but could be stripped for production.

I’d be great if I can opt-out from some of these sections to be generated.

**Comment by kripken** [comment]
For the first, we have an option `TEXTDECODER`, and could perhaps add another level there (`TEXTDECODER=2`) which means "assume it has to exist".

For the second, what do you mean exactly, which error messages?

**Comment by kripken** [comment]
Ah, for other context I see the issue is the errno error message texts. We do have a bunch we can improve there to avoid including them, I opened #7808

**Comment by kripken** [comment]
Another issue with TextDecoder is that it isn't present in nodejs (at least not in 8.12).

**Comment by kripken** [comment]
Might still be worth doing despite those issues. Here's a PR with a `FORCE_TEXTDECODER` option: #7813.
