### ISSUE TITLE
Missing dso_handle

### ISSUE THREAD

**Issue by Mintyboi** [emscripten-core/emscripten#7811]
@kripken I hit into this error when running my build.

> external function '___dso_handle' is missing. perhaps a side module was not linked in? if this symbol was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment

This is because after setting EXPORT_ALL to false in #7371 , this function gets excluded in https://github.com/emscripten-core/emscripten/blob/52479350e642453bf74ceca108fca8e1f43b30d5/src/jsifier.js#L372

I'm not sure how to reproduce this issue in a smaller test case. However, this function appears to be a standard library function that I am not explicit using.
Do you think it make sense to add it into the shared.Settings.EXPORTED_FUNCTIONS in emcc.py? And if so under which conditions do you think it falls best under

**Comment by kripken** [comment]
I think we need to understand that better first. What uses it in your codebase? If you can't share the code, can investigate that in llvm IR using llvm-dis.

**Comment by Mintyboi** [comment]
Sorry for the late update.
I managed to reproduce this issue in a small testapp (using a fastcomp build, 1.39.6-fastcomp) by using a `thread_local static` variable and setting the `profiling` flag in my build.

However, because I'm not seeing this in LLVM backend (1.39.6), I'll be closing this thread.

Thanks to all who tried helping!
