### ISSUE TITLE
Grouping all global initializers in one function call?

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#7818]
Consider the following code:

`a.cpp`

```c++
#include <emscripten.h>
double a = emscripten_get_now();
```

`b.cpp`

```c++
#include <emscripten.h>
double b = emscripten_get_now();
```

`c.cpp`

```c++
#include <emscripten.h>
double c = emscripten_get_now();
int main(){}
```

Building with
```
em++ a.cpp b.cpp c.cpp -o a.html -O3 -g2 -s WASM=0
```

generates the following code:

```javascript
__ATINIT__.push({
 func: (function() {
  __GLOBAL__sub_I_a_c();
 })
}, {
 func: (function() {
  __GLOBAL__sub_I_b_c();
 })
}, {
 func: (function() {
  __GLOBAL__sub_I_c_c();
 })
});

...
// in asm.js module
function da() { ... emscripten_get_now(); ... }
function ga() { ... emscripten_get_now(); ... }
function ea() { ... emscripten_get_now(); ... }

...
// EMSCRIPTEN_END_FUNCS


  return { __GLOBAL__sub_I_a_c: da, __GLOBAL__sub_I_b_c: ea, __GLOBAL__sub_I_c_c: ga, ...

...

var __GLOBAL__sub_I_a_c = Module["__GLOBAL__sub_I_a_c"] = asm["__GLOBAL__sub_I_a_c"];
var __GLOBAL__sub_I_b_c = Module["__GLOBAL__sub_I_b_c"] = asm["__GLOBAL__sub_I_b_c"];
var __GLOBAL__sub_I_c_c = Module["__GLOBAL__sub_I_c_c"] = asm["__GLOBAL__sub_I_c_c"];

```

In `-s WASM=1` build, output is quite similar:

```javascript
__ATINIT__.push({
 func: (function() {
  __GLOBAL__sub_I_a_c();
 })
}, {
 func: (function() {
  __GLOBAL__sub_I_b_c();
 })
}, {
 func: (function() {
  __GLOBAL__sub_I_c_c();
 })
});

...

var __GLOBAL__sub_I_a_c = Module["__GLOBAL__sub_I_a_c"] = (function() {
 return Module["asm"]["c"].apply(null, arguments);
});
var __GLOBAL__sub_I_b_c = Module["__GLOBAL__sub_I_b_c"] = (function() {
 return Module["asm"]["d"].apply(null, arguments);
});
var __GLOBAL__sub_I_c_c = Module["__GLOBAL__sub_I_c_c"] = (function() {
 return Module["asm"]["e"].apply(null, arguments);
});
```

In a large C++ codebase these global cpp file initializers take up a considerable amount of space (second largest chunk after #7505), the project having 552 such generated and exported `__GLOBAL_xxx()` initializers.

Ideally we would generate one function `init()` in LLVM build time that would get exported out from the asm.js/wasm module, which would call each of the individual cpp file global initializer functions from within asm.js/wasm module code. The individual cpp file global initializers would then not need to be exported at all out from the module. This would be very worthwhile in terms of code size, that would drop ~100KB of generated code size in release builds, and ~500KB of generated code size in ASSERTIONS-enabled debug builds. (mostly due to hundreds of `assert(runtimeInitialized, "you need to wait for the runtime to be ready (e.g. wait for main() to be called)");` lines generated in debug builds)

I was wondering if LLVM already would have something to be able to do this, or if this has been considered before?

It would be cool if such an `init()` function could be programmatically generated in LLVM builds in such a way that LLVM optimizer could even inline the individual global initializers into the super-initializer for smaller code size inside the asm.js/wasm module.

**Comment by kripken** [comment]
The LLVM wasm backend actually does this already,

We could do it in asm.js/asm2wasm as well. The main downside is that "flattening" out the ctors loses some info about the ordering and priority. If LTO is not done then it probably doesn't matter, except for the eval-ctors optimization, which can optimize out individual ctors, but not part of one, so it would be "all or nothing" with this. However, we could improve it to support this.

**Comment by juj** [comment]
Oh, that's great. Is the code something that we would be able to reuse in fastcomp just as a LLVM pass, or does it have some wasm-specifics?

It sounds like such a pass that creates one super-initializer would be possible to adhere to desired ordering and priority, to follow whatever LLVM attributes on global initializers there are?

**Comment by kripken** [comment]
I'm not sure, but I'd actually guess that the LLVM wasm backend path does this in lld. So it might not be practical to copy over. But making an LLVM pass for it should be practical. (It would have to follow the order, yeah, and whatever other LLVM rules, as you said - probably pretty simple.) Alternatively, we know the final ctors and their order in emscripten so we can emit them, so for asm.js emscripten.py might emit a function calling them inside the asm.js, and emit that as the single ctor, that sounds simpler to me.
