### ISSUE TITLE
How to create a context without premultipled alpha when using SDL/EGL

### ISSUE THREAD

**Issue by gabrielcuvillier** [emscripten-core/emscripten#7821]
I would like to create a WebGL context without premultiplied alpha, but the issue I am facing is that my program uses SDL to initialize the GL context - which in turn uses EGL implementation of emscripten - but I can't see a way to specify that option neither in SDL nor in EGL.

Any ideas ?

**Comment by kripken** [comment]
[emscripten_webgl_create_context](https://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#c.emscripten_webgl_create_context) supports creating a context with that attribute. I'm not sure offhand how to get SDL/EGL to use it, though - if it doesn't just work, perhaps we need to somehow get them to accept an existing context that was already created.

**Comment by gabrielcuvillier** [comment]
As the option looks like to be set to 'true' by default, maybe a compiler option would suffice (ie. -s EGL_WEBGL_PREMULTIPLIED_ALPHA=1)

**Comment by juj** [comment]
EGL API does not support specifying a premultiplied alpha enabled context, if my google search was accurate. The closest there does exist EGL_VG_ALPHA_FORMAT_PRE_BIT flag (https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglChooseConfig.xhtml) which relates to OpenVG, so not quite the same.

Perhaps SDL implementation should be updated to not utilize EGL, but directly depend on Emscripten's WebGL context creation functions. Then the generated code size will be smaller, as the whole EGL lib can be dropped from in between.

Another option would be to craft a custom Emscripten EGL extension to allow specifying premultipliedAlpha, but that can get hairy, it'll require some diligent design work for good API hygiene.

Although now that I search for it, I cannot find what the SDL (are you using 1.4? 2.0?) API option for expressing premultiplied alpha context would be. If SDL does not allow initializing a premultiplied alpha context, then a SDL-specific global option such as `-s SDL_PREMULTIPLIED_ALPHA_CONTEXT=1` could work.

**Comment by gabrielcuvillier** [comment]
Neither EGL nor SDL are supporting expressing premultiplied alpha contexts. That's something very web specific.
I think it might be interesting, because some legacy apps does not clear the color/alpha buffer between each frames, which makes things look silly the first time we have a legacy app running: weird colors/LSD effects (honestly, the first time I had this, I thought it was coming from bugs in Regal and lost a couple of hours investigating)

SDL implementation could be updated indeed, but that's not the simple path :)
Regarding global options, SDL will not be able to do anything with it because it uses EGL directly
However a global EGL_PREMULTIPLIED_ALPHA_CONTEXT option could do the job at compilation time

If you agree with that option, I could take a look
(For now, I just modify library_gl.js in my own branch :)

**Comment by kripken** [comment]
I think @juj's comment here is the best direction:

> Perhaps SDL implementation should be updated to not utilize EGL, but directly depend on Emscripten's WebGL context creation functions. Then the generated code size will be smaller, as the whole EGL lib can be dropped from in between.

But maybe optionally, that is - if emscripten's C API was used to create the context, it should be stored on the canvas I think, and then SDL etc. can check if the context already exists, and use that if so?

**Comment by gabrielcuvillier** [comment]
I 100% agree that it would be indeed the right direction. 
But in my case the benefits actually outweigh the costs. Having to rewrite the SDL emscripten video backend - already working nice even if using EGL - just for one canvas option is a little bit overkill ;)
I'll stick with my "alpha-channel-cleaning-after-each-frame approach" for now. Thanks !

**Comment by gabrielcuvillier** [comment]
Closing this one, as related to SDL port and not emscripten port.
