### ISSUE TITLE
Set up emscripten.org to work with HTTPS

### ISSUE THREAD

**Issue by surma** [emscripten-core/emscripten#7824]
Currently, [https://emscripten.org/](https://emscripten.org/) does not work.

At least the redirect from http://emscripten.org to http://kripken.github.io/emscripten-site/ should be changed to redirect to [http**s**://kripken.github.io/emscripten-site/](https://kripken.github.io/emscripten-site/).

**Comment by kripken** [comment]
I think I updated that correctly now, but it may take a few hours to update. We should check tomorrow probably.

**Comment by kripken** [comment]
I don't actually know how to set up `https://emscripten.org` itself to work. Is that something I need to ask the registrar for?

**Comment by chicoxyzzy** [comment]
> I think I updated redirects to https://kripken.github.io/.. now, but it may take a few hours to update. We should check tomorrow probably.

This works already 👍

> I don't actually know how to set up https://emscripten.org itself to work. Is that something I need to ask the registrar for?

You need certificate. Let's Encrypt provides free certificates and it's probably the easiest way to configure HTTPS https://letsencrypt.org/getting-started/.

**Comment by chicoxyzzy** [comment]
You can use custom domain with GitHub Pages https://help.github.com/articles/using-a-custom-domain-with-github-pages/.

**Comment by surma** [comment]
+1 to @chicoxyzzy’s suggestion.

@kripken I am happy to help with web-related stuff if desired :)

**Comment by kripken** [comment]
Help would be great - starting to read that page, it talks about 'apex' and other domains, and a bunch of other things and steps that I don't understand at all :)

Is there maybe some doc somewhere that just says what to do for the simple case? (I assume we don't need anything special here?)

**Comment by kripken** [comment]
The github docs say I should make an ALIAS or ANAME record. My domain registrar is gandi, and I don't see an option in their UI for either of those, or in their [docs](https://docs.gandi.net/en/).

**Comment by kripken** [comment]
Ok, this seems to now be working. emscripten.org, with and without https, looks ok.

Oddly www.emscripten.org does not work, still looking into that.

**Comment by kripken** [comment]
Ok, looks like that's fixed too, so I think we can close this.

Thanks for all the help!
