### ISSUE TITLE
Uncaught surprising proxied syscall: 202

### ISSUE THREAD

**Issue by Hao-Yan** [emscripten-core/emscripten#7833]
I am porting some cross platform code to WebAssembly, now it build successfully, when run, I met below issue. Did anyone have some insight on this?

![image](https://user-images.githubusercontent.com/6327453/50903941-03826480-145a-11e9-9296-7b54cadfcc26.png)

I checked the code where the exception throw, seems 202 syscall is not implemented in _emscripten_syscall. My emscripten version is 1.38.21. BTW, I use -s WASM=0 when compile. I also use embind when call from js to c++.

![image](https://user-images.githubusercontent.com/6327453/50904140-82779d00-145a-11e9-939d-ddfac53a516f.png)

**Comment by kripken** [comment]
Hmm, that function is autogenerated based on the syscalls seen at compile time. Is it possible you're calling the syscall in a nonstandard/dynamic way? Do you have a testcase showing the issue.

Testing locally, if I statically call `getgid()/getegid()` manually I do see it get proper proxying code.

**Comment by Hao-Yan** [comment]
@kripken , you are right. There is some code related to SQLite which used some dynamic way to do syscall.
![image](https://user-images.githubusercontent.com/6327453/50958537-e900c780-14fb-11e9-9724-2989d4c26bb1.png)
To let the __emscripten_syscall generate the 202 syscall, I just manually call getgid()/getegid() in another source file. Thanks for the help.
