### ISSUE TITLE
Gamepads broken in 1.38.22

### ISSUE THREAD

**Issue by dos1** [emscripten-core/emscripten#7840]
```
exception thrown: TypeError: Cannot read property 'length' of undefined
    at _emscripten_get_num_gamepads (http://localhost:8000/odglos.js:1:318521)
 ```

**Comment by dos1** [comment]
I should have said that I got that with SDL2 from emscripten-ports ;)

**Comment by Daft-Freak** [comment]
I just hit this myself. Looks like we need to call that in [here](https://github.com/emscripten-ports/SDL2/blob/master/src/joystick/emscripten/SDL_sysjoystick.c#L163) and [here](https://github.com/emscripten-ports/SDL2/blob/master/src/joystick/emscripten/SDL_sysjoystick.c#L310).

**Comment by dos1** [comment]
emscripten-ports/SDL2@2092befbcee6731c39c50a6ad4c78f3f2b1c9c17 does help :)

**Comment by Beuc** [comment]
With or without the patch, I now get:
```
TypeError: JSEvents.lastGamepadState is undefined
```

I don't have time to track down right now, but I guess I'll have to.

(This is a quite ugly breakage, please consider a deprecation phase to avoid busting everybody's intermediate libs/frameworks, I see Godot seems also impacted https://github.com/godotengine/godot/issues/25100 :/)

**Comment by Beuc** [comment]
> Did you test it with a gamepad? (That's on a branch because I couldn't find one).

I reproduced the first error in my FreeDink port. I could test the patch with a gamepad: things work as before, that is, the joystick gets initialized only once in a while (not sure where that comes from, SDL2 just returns 0 joystick found). But when it gets detected, it works.

I was about to check this other "JSEvents.lastGamepadState is undefined" error but now the OpenGL context doesn't start anymore... Wish me luck :/

**Comment by weiyuemin** [comment]
I encountered the same with Beuc

With or without the patch (https://github.com/emscripten-ports/SDL2/blob/master/src/joystick/emscripten/SDL_sysjoystick.c ), get:
TypeError: Cannot read property 'length' of undefined,TypeError: Cannot read property 'length' of undefined
at _emscripten_get_num_gamepads 
...

and in the generated js i see:

function _emscripten_get_num_gamepads() {
    return JSEvents.lastGamepadState.length
}

seems JSEvents.lastGamepadState is undefined.

I don't have gamepad connected, and I'm using Chrome 71.0.3573.0

**Comment by weiyuemin** [comment]
well, the error is gone after rebuilding the project.
