### ISSUE TITLE
extern variables aren't exported

### ISSUE THREAD

**Issue by dos1** [emscripten-core/emscripten#7849]
Instead of using `-s EXPORTED_FUNCTIONS` to define exported symbols, one can use `EMSCRIPTEN_KEEPALIVE` macro to mark functions as exported already in code.

However, `extern` variables which should also be exported (for instance in a side module) can't be marked with `EMSCRIPTEN_KEEPALIVE`.

```
warning: 'used' attribute ignored [-Wignored-attributes]
```

The only way to get them exported is to use `-s EXPORTED_FUNCTIONS`.

I'd suggest exporting defined variables that are declared with `extern` keyword by default, as that's basically what that keyword means.

**Comment by kripken** [comment]
If it's extern then it isn't defined, though?
```
extern int c;
```
Or do you mean in the dynamic linking case?

**Comment by kripken** [comment]
Oh, I see you mentioned side modules as an example, so I guess dynamic linking is indeed the intention here.

Doing something special for `extern` seems odd to me. I wonder though if we can define a macro that does work for globals?

**Comment by dos1** [comment]
I'm afraid it's still a valid issue ;)

Just to make it clear: yes, it was filled with dynamic linking in mind.

**Comment by juj** [comment]
> However, `extern` variables which should also be exported

> I'd suggest exporting defined variables that are declared with `extern` keyword by default, as that's basically what that keyword means.

That is not what `extern` means. `extern` on a definition means that a variable is scoped to other compilation units. It does not make any qualifications about the behavior in linkage in a .dll or a .so. In C and C++ all global variable definitions are already extern by default unless explicitly marked `static`.

Not sure about the bug here with respect to side modules (got a small repro to illustrate?), but *default-exporting extern variables* would be the same as *export all variables that were not marked static*, which is not the right thing to do.

**Comment by dos1** [comment]
Don't focus too much on that suggestion, the essence of the issue is that `EMSCRIPTEN_KEEPALIVE` can't be used on globals, so you need to resort to providing a list of symbols to the compiler via some external means if you want to keep them around.

**Comment by sbc100** [comment]
It seems to work just find for me:

```
#include <emscripten.h>                                                          
                                                                                 
int foo = 7;                                                                                                                   
int bar EMSCRIPTEN_KEEPALIVE = 99;    
```

When I compile this with `SIDE_MODULE=1` I get both `_foo and `_bar` exported.

When I compile with `SIDE_MODULE=2` I gut only `_bar`. 

At least using the llvm backend I see this (are you using fastcomp?)

Can you post minimal example of the problem in action?

**Comment by sbc100** [comment]
As @juj says, I don't think exporting at the point of `extern` declaration doesn't make sense.  The export should be declared where the variable is *defined*, not where it is declared as `extern`.
