### ISSUE TITLE
Inline webassembly

### ISSUE THREAD

**Issue by singpolyma-shopify** [emscripten-core/emscripten#7859]
Is there any way to have `emcc` emit some inline WASM?  I want to use an alternate `malloc` implementation (until at least #7795 is done), but cannot usefully do so unless I can emit the `grow_memory` instruction.

**Comment by dschuff** [comment]
There's always [EM_JS](https://github.com/kripken/emscripten/issues/6147) where you could do something like `Module.memory.grow()` (this uses the JS API rather than emitting the instruction inline but the effect would be the same).

The upstream wasm backend also supports inline asm in C, but that support is still fairly rudimentary.

**Comment by dschuff** [comment]
Actually come to think of it, in emscripten you should use `EM_JS` and call [`Module.enlargeMemory`](https://github.com/kripken/emscripten/blob/incoming/src/preamble.js#L983) becaus that will also update the ArrayBuffer views (`HEAP32` etc) as well.

**Comment by sunfishcode** [comment]
The upstream wasm backend supports `__builtin_wasm_memory_grow(index, delta)`.

**Comment by singpolyma-shopify** [comment]
@sunfishcode Using that I get:

```
t.c:30:2: error: use of unknown builtin '__builtin_wasm_memory_grow' [-Wimplicit-function-declaration]
        __builtin_wasm_memory_grow(0, 8);
```

Do I need to do something to up the right backend?

**Comment by sunfishcode** [comment]
Ah, it appears the emscripten-fastcomp-clang directory doesn't include the patch which adds that yet. It might support the previous name `__builtin_wasm_grow_memory` though, which is the same, except doesn't have an index argument.

**Comment by singpolyma-shopify** [comment]
@sunfishcode hmm... no joy with the old name either. Can I do something to update the clang version my emsdk is using or something like that?

**Comment by GreatIndieDeveloper** [comment]
any new news this issue ? ....

**Comment by sbc100** [comment]
__builtin_wasm_memory_grow works now with the llvm upstream backend, which is not the default in emsdk.

**Comment by GreatIndieDeveloper** [comment]
unluckily it doesn't here i have did a 

> ./emsdk install latest-upstream

> ./emsdk activate latest-upstream


and still anytime i use __builtin_wasm_memory_grow i get :

> error: use of undeclared identifier '__builtin_wasm_grow_memory'
         return __builtin_wasm_grow_memory(pages);
