### ISSUE TITLE
GL_QUAD_STRIP broken (with -s USE_REGAL=1)

### ISSUE THREAD

**Issue by claudeha** [emscripten-core/emscripten#7867]
With incoming regal port (version 4) I get this printout in the Firefox console and my shape isn't drawn:

    Error: WebGL warning: drawElements: Index buffer too small.

Reproducing test case:

    // emcc -s USE_SDL=2 -s USE_REGAL=1 -o quadstrip.html quadstrip.c -lGL
    // gcc -o quadstrip quadstrip.c -lGL -lSDL2
    
    #ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #include <GL/Regal.h>
    #else
    #include <GL/gl.h>
    #endif
    #include <SDL2/SDL.h>
    
    SDL_Window *window = 0;
    SDL_GLContext context;
    
    void main1(void)
    {
      glClear(GL_COLOR_BUFFER_BIT);
    
      glBegin(GL_QUAD_STRIP);
      glVertex2f(-0.5, -0.5);
      glVertex2f( 0.5, -0.5);
      glVertex2f( 0.5,  0.5);
      glVertex2f(-0.5,  0.5);
      glVertex2f(-0.5,  1.5);
      glVertex2f( 0.5,  1.5);
      glEnd();
    
      SDL_GL_SwapWindow(window);
    }
    
    int main(int argc, char **argv)
    {
      SDL_Init(SDL_INIT_VIDEO);
      window = SDL_CreateWindow("GL_QUAD_STRIP", 0, 0, 640, 480, SDL_WINDOW_OPENGL);
      context = SDL_GL_CreateContext(window);
      SDL_GL_MakeCurrent(window, context);
    #ifdef __EMSCRIPTEN__
      RegalMakeCurrent((void *) 1);
    #endif
    
      glDisable(GL_DEPTH_TEST);
      glClearColor(0, 0, 1, 1);
      glColor4f(1, 0, 0, 1);
    
    #ifdef __EMSCRIPTEN__
      emscripten_set_main_loop(main1, 0, 1);
    #else
      while(1) main1();
    #endif
      return 0;
    }

**Comment by kripken** [comment]
cc @gabrielcuvillier 

It may make sense to file bugs on the port, I enabled issues there now, https://github.com/emscripten-ports/regal/issues Or perhaps on regal upstream, but I'm not sure it's still active?

**Comment by gabrielcuvillier** [comment]
Regal upstream is no more active since a few years. I guess I'm the only one tweaking that beast now ;)
Yes, better to have those bugs on the port directly

**Comment by kripken** [comment]
Thanks, closing.
