### ISSUE TITLE
Worker API docs improvements

### ISSUE THREAD

**Issue by svenemtell** [emscripten-core/emscripten#7868]
I think the Worker API docs are not clear and therefore I want to propose a couple of  improvements. Bear with me if I have misunderstood things...

### In the paragraph 'void emscripten_call_worker ...'

REPLACE
The data block defined by the pointer and size exists only during the **callback**: it cannot be relied upon afterwards. If you need to keep some of that information outside the **callback**, then it needs to be copied to a safe location.
WITH
The data block defined by the pointer and size exists only during the **function call**: it cannot be relied upon afterwards. If you need to keep some of that information outside the **function call**, then it needs to be copied to a safe location.

##### Regarding callback parameters:

REPLACE
(char)* : The data pointer provided in emscripten_call_worker().
WITH
(char)* : The address of a block of memory to copy to the callback function.

REPLACE
(int) : The size of the block of data.
WITH
(int) : The size of the block of memory.

### In the paragraph 'void emscripten_worker_respond_provisionally ...'

Is the following Note right? When callback is null you don't have to call the non-provisional version?

Note
Calling the provisional version is optional, but you must call the non-provisional version to avoid leaks.

### General
As I understand, the following is true and should be emphasized:
• the memory block defined by the data pointer and size in emscripten_call_worker is copied from the main program to the worker
• the memory block defined by the data pointer and size in emscripten_worker_respond and emscripten_worker_respond_provisionally is copied from the worker to the main program
• calling emscripten_worker_respond deallocates the copied memory block defined by the data pointer and size in the call to the worker function
• when using emscripten_call_worker without a callback the copied memory block defined by the data pointer and size has to be manually deallocated in the worker
• when using emscripten_worker_respond_provisionally the copied memory block defined by the data pointer and size has to be manually deallocated in the main program

URL: ../../docs/api_reference/emscripten.h

**Comment by kripken** [comment]
Thanks! It would probably be easiest to discuss this on a PR making the proposed changes (the source files are under `site/` in this repo.

cc @floooh who knows about those worker APIs.
