### ISSUE TITLE
Initialization/post-instantiate ordering in dynamic linking

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#7869]
Testcase from the mailing list (slightly simplified): https://gist.github.com/kripken/23c0e8749971d727cc402e2b513aa429

The issue here is that the loader does this:
```js
      // initialize the module
      var init = exports['__post_instantiate'];
      if (init) {
        if (runtimeInitialized) {
          init();
        } else {
          // we aren't ready to run compiled code yet
          __ATINIT__.push(init);
        }
      }
```
This is pretty naive as regards to ordering. In the case here, the runtime is not yet initialized, and we push it to the end of that array. But then it gets run too late, previous functions in the list call into that shared module, and it isn't ready yet. As a hack, replacing `push` with `unshift` fixes this case, but breaks other stuff in the test suite.

We do have some info on which dynamic library needs what, which affects how we order them for loading, and that info should be taken into account here, I believe (in this testcase, it's the main module depending on the side module). cc @navytux

**Comment by navytux** [comment]
@kripken, thanks for heads-up. I'm currently deep in other things, so won't be able to look into this in the near time. Maybe in one month I should be able to look into, but I cannot promise that, sorry.

**Comment by kripken** [comment]
Thanks for the info @navytux, any time in the future if you can can get to it would be great.

**Comment by navytux** [comment]
> Thanks for the info @navytux, any time in the future if you can can get to it would be great.

( I could not get to it and I'm sure I won't be able in the near future; appologize for the inconvenience )
