### ISSUE TITLE
LEGACY_GL_EMULATION does not work with emscripten_webgl_create_context

### ISSUE THREAD

**Issue by Daft-Freak** [emscripten-core/emscripten#7871]
[port of sdl2glshader.c](https://gist.github.com/Daft-Freak/a99f163bf7f3b2189e648fc1cf1c678a)

Noticed this looking at #5580. Looks like the init function never gets called. Calling it may get messy though as it doesn't look like the emulation would deal with multiple contexts. (I'm not sure these should work together, but then `LEGACY_GL_EMULATION` would stop working with EGL and SDL2)

**Comment by Daft-Freak** [comment]
I haven't looked at multiple GL contexts in SDL for a while, but this is still an issue. I can get the example to work by adding a `EM_ASM("Module.useWebGL = true; GLImmediate.init();");` after `emscripten_webgl_make_context_current`, so it seems it's just immedate mode emulation that isn't getting inited.

**Comment by Daft-Freak** [comment]
I'm hitting this again trying to port SDL2 away from EGL... and I'm still not sure what to do here. It's a bit of a mixing legacy/non-legacy API problem, but using EGL in SDL2 is blocking some work (no support for specifying canvas)... and we also have a bunch of tests here that rely on legacy GL working.

**Comment by ColleagueRiley** [comment]
This still seems to be an issue, running `EM_ASM("Module.useWebGL = true; GLImmediate.init();");` works but then it breaks support for newer versions of OpenGL
