### ISSUE TITLE
glEnable(GL_MULTISAMPLE) creates wrong WebGL command

### ISSUE THREAD

**Issue by frguthmann** [emscripten-core/emscripten#7898]
I tried compiling a project that uses GLFW3 to WebGL 2.0 and noticed the command "glEnable(GL_MULTISAMPLE)" makes the generated js call the function _glEnable(x0) with argument 32925. This is not a supported value and the following warning appears in the console: INVALID_ENUM: enable: invalid capability

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
None of WebGL 2.0, WebGL 1.0, OpenGL ES 3.0 or OpenGL ES 2.0 specifications support the `glEnable(GL_MULTISAMPLE);` function. It is functionality that was introduced on top of Desktop OpenGL 1.3 by [GL_ARB_multisample extension](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_multisample.txt). It is present as a compatibility extension [EXT_multisample_compatibility](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_multisample_compatibility.txt) on top of OpenGL ES 3.1, but that does not apply to WebGL.

In WebGL to perform multisampling, create the WebGL context with multisampling bits enabled, or create an offscreen rendertarget with multisampling enabled.
