### ISSUE TITLE
asm.js and runPostSets problem

### ISSUE THREAD

**Issue by bsokol** [emscripten-core/emscripten#7903]
I still use asm.js export (for wider compatibility on mobile browsers) and from this version of Emscripten:

v1.38.21: 11/30/2018
 - fastcomp: Remove `runPostSets` function and replace with normal static
   constructor function. See #7579 

I see "Invalid asm.js: Expected function" error in browser log caused by "runPostSets:runPostSets" code fragment inside generated app.js file.
Every time I make a build I have to manually remove this fragment.

It looks like some old and unnecessary function export during build process which should be removed.

**Comment by kripken** [comment]
cc @sbc100 

@bsokol, do you have a testcase showing the issue? I'm not sure what could refer to runPostSets - all references in our compiler should be gone after that PR.

**Comment by sbc100** [comment]
Could you be running a old version of fastcomp perhaps?  As @kripken says there are no more references to this function in fastcomp or emscripten.

**Comment by bsokol** [comment]
Hmm, it was very strange. I had this problem with this setup:

```
import os
MINGW_ROOT='w:/Emsdk/mingw/7.1.0_64bit'
LLVM_ROOT='w:/Emsdk/clang/e1.38.24_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='w:/Emsdk/clang/e1.38.24_64bit/optimizer.exe'
BINARYEN_ROOT='w:/Emsdk/clang/e1.38.24_64bit/binaryen'
NODE_JS='w:/Emsdk/node/8.9.1_64bit/bin/node.exe'
PYTHON='w:/Emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
JAVA='w:/Emsdk/java/8.152_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='w:/Emsdk/emscripten/1.38.24'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'c:/users/bartek/appdata/local/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

Setting environment variables:
EMSDK = w:/Emsdk
EM_CONFIG = C:\Users\Bartek\.emscripten

Set the following tools as active:
   mingw-7.1.0-64bit
   clang-e1.38.24-64bit
   node-8.9.1-64bit
   python-2.7.13.1-64bit
   java-8.152-64bit
   emscripten-1.38.24

```
Even with full project rebuild (and deleting all bc files) I had this runPostSets problem.

So today I decided to remove Emscripten SDK from disk and do a fresh install . And with exactly the same setup like before with the same versions of middlewares runPostSets has gone away!
Very very strange, it looks like during incremental updating emsdk something went wrong.
