### ISSUE TITLE
Crash when calling glClear on closed GL context

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#7908]
Currently SDL2 first calls SDL_GL_MakeCurrent(NULL, NULL) (in SDL_GL_DeleteContext) which then call Emscripten's callback which does a glClear (in Emscripten_GLES_DeleteContext).

This used to actually work (screen cleared), but now (1.38.25) this crashes with:
```
Exception thrown: TypeError: GLctx is null,_glClear@http://localhost:8000/index.js:11273:27
_Emscripten_GLES_DeleteContext@http://localhost:8000/index.js line 1711 > WebAssembly.instantiate:wasm-function[2505]:0xe297a
_SDL_GL_DeleteContext@http://localhost:8000/index.js line 1711 > WebAssembly.instantiate:wasm-function[2159]:0x895df
```

I would expect this to possibly silently no-op (don't clear screen), but not crash.

**Comment by juj** [comment]
Someone has written `Emscripten_GLES_DeleteContext` like this:

https://github.com/emscripten-ports/SDL2/blob/54eb141735151c0a42d6093fe44fe1bc0f18107a/src/video/emscripten/SDL_emscriptenopengles.c#L84-L95

The intent of the clear there is apparently to make it visually look as if GL was deinitialized on the page. Perhaps that code will need a fix to first check if there is an active GL context, and only try to issue a clear command if so. (or first try to activate the context if not active, and only then clear). There does not seem to be a bug in Emscripten code, but if it used to work with Emscripten, may be worth bisecting which commit regressed.

This issue may be more precise to be filed against https://github.com/emscripten-ports/SDL2 (although I don't mind discussing it here)

If this used to work in earlier Emscripten version, it is possible that the earlier Emscripten version did not yet implement activating/deactivating multiple contexts with MakeCurrent (although that support is kinda ancient), or perhaps newer Emscripten just upgraded the tag version of SDL2 it pulls from emscripten-ports, which triggered update to newer SDL2 version that e.g. started to do SDL_GL_MakeCurrent(NULL) calls in Esmcripten, or something similar.

CC @Daft-Freak

**Comment by Daft-Freak** [comment]
Yep, [that was me](https://github.com/Daft-Freak/SDL-emscripten/commit/aa89125a80e37dbaa5b4511384f878a7a824b651). It was to fix SDL's test runner (it would create/delete a context/renderer for each test and fail with leftover content from the last test). It did work back when I wrote it, but that was ~4 years ago. eglMakeCurrent wasn't implemented until recently, so it looks like I [broke it](https://github.com/emscripten-core/emscripten/blame/incoming/src/library_egl.js#L597) as well.

**Comment by Beuc** [comment]
> There does not seem to be a bug in Emscripten code

I believe that crashing the application with a JS TypeError, instead of e.g. defining an OpenGL error and continuing execution, can be considered a bug (hence why the title doesn't reference SDL2).

**Comment by juj** [comment]
> I believe that crashing the application with a JS TypeError, instead of e.g. defining an OpenGL error and continuing execution, can be considered a bug (hence why the title doesn't reference SDL2).

In native C/C++ on Windows/Linux/macOS etc. you can also get a segfault when attempting to do a GL call when there is no active context. The GL specification does not require an OpenGL error to be raised in this kind of scenario.

(Having to check in each GL call if there is an active context would considerably add to the build size of the program, so not something all people would like to ship with. Though if you'd like to add such a feature as an optional flag, that'd be an ok contribution)

**Comment by Beuc** [comment]
I understand the need for performances, but I hope we'll consider error handling as important as well, especially given the recent history of breakages in Emscripten+SDL2 official releases and the hours users wasted debugging :/

**Comment by kripken** [comment]
We have `GL_DEBUG`, and could add more checks if that mode is enabled perhaps.

**Comment by Daft-Freak** [comment]
I've removed the bad glClear from SDL (we don't need it any more anyway). Also, in the case of having no context, it isn't possible to set a GL error as the error is a property of the context.
