### ISSUE TITLE
disable -O3 minification

### ISSUE THREAD

**Issue by danm-netlify** [emscripten-core/emscripten#7916]
I would like to turn `-O3` specially `DCE` but specifically disable minification. Is it possible?

**Comment by kripken** [comment]
`-O3 -g1` for example will disable whitespace minification. Higher debug levels may disable more optimizations and minification.

**Comment by danm-netlify** [comment]
`em++ -fno-builtin -O3 --profiling-funcs -s ERROR_ON_UNDEFINED_SYMBOLS=0 -std=c++17 -o em-wasm-matcher.js wasm-matcher.cc;` (also `--profiling`) eliminates the function which does contain `KEEPALIVE`

**Comment by VirtualTim** [comment]
`-s DEMANGLE_SUPPORT=1` May also help.
See https://github.com/emscripten-core/emscripten/blob/incoming/src/settings.js#L333
Name demangling for WASM only seems to work in Firefox. Chrome still shows the c++ mangled names.

You probably also want `-g2` (preserve function names) or `-g3` (preserve variable names).

Personally I've set up a "Profiling" target that uses the following (additional) compile options:
```
add_compile_options(-fno-inline)
add_compile_options(-fno-inline-functions)
add_compile_options(--profiling)
```
And the following linker flags (for WASM):
```
LINK_FLAGS "-O3 --llvm-opts 3 --llvm-lto 3 -s ALIASING_FUNCTION_POINTERS=1 \
            -s ASSERTIONS=0 -s STACK_OVERFLOW_CHECK=0 -s SAFE_HEAP=0 \
            -s NO_DYNAMIC_EXECUTION=1 -s DEMANGLE_SUPPORT=1 \
            -s OUTLINING_LIMIT=0 -s ELIMINATE_DUPLICATE_FUNCTIONS_PASSES=1 \
            ${wasmflags}")
```
I realise some of these may be redundant, but I like being explicit.
