### ISSUE TITLE
Closure compiler error starting 1.38.25

### ISSUE THREAD

**Issue by kkimdev** [emscripten-core/emscripten#7933]
We're hitting this error starting 1.38.25, which compiled successfully before.
```
/tmp/emscripten_temp_tMzdcc/game_core.bc.o.js.mem.js.jso.js.jso.js.jso.js.jso.js:1: ERROR - variable Buffer is undeclared
...
1 error(s), 2 warning(s)
shared:ERROR: closure compiler failed (rc: 1)
```

The project is quite complex and I didn't have time to narrow down the cause yet.  I apologize for an under-specified report but there was another issue about closure compiler failure recently #7914 , so I wanted to provide another datapoint.

**Comment by kkimdev** [comment]
Verified that with `emsdk install sdk-1.38.24-64bit && emsdk activate sdk-1.38.24-64bit` it compiles successfully

**Comment by kripken** [comment]
@juj I think this may be from the closure compiler update you did recently.

**Comment by juj** [comment]
If you can produce a minimal test case that I can reproduce, I can take a peek.

**Comment by kkimdev** [comment]
Minimal test case:

`em++ main.cpp  -s STRICT=1 -s NO_EXIT_RUNTIME=1 -s SINGLE_FILE=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web -s NO_FILESYSTEM=1 --bind -Wall -Os -DNDEBUG --closure 1`

where main.cpp is an empty file

**Comment by juj** [comment]
Above PR was merged, so closing as fixed.
