### ISSUE TITLE
Static Library .a use and link and .c .h .o files to Emscripten

### ISSUE THREAD

**Issue by exonent** [emscripten-core/emscripten#7972]
Hi everybody!

I'm trying to use `Emscripten `in my Cordova project (hybrid mobile App). I read a lot of articles, pages ,etc.. But I don't know how to use this tool in my project.

That's the problem (my problem :-) ):
- I want to use my own `(.a)` library if is possible
(How I create that` (.a)` library? Got a lot of `(.o)` (C files compiled) and I use the command: "`ar rcs nameLib.a aFile.o bFile.o cFile.o etc...`" when finish, I compile it again for each architecture (`iOS armv7`, `PC i386`, `PC x86_64`) to use it in different environments).
- How can I "convert" that using `Emscripten `into my project? What commands I need to use?
- If I can't use `(.a)` library. How can I use/convert all my `(.o)`, `(.c)`, `(.h)` files? What I need to do? (Commands, steps.. )

Thank you very much!! Apologizes for the question but this make me crazy!

**Comment by brion** [comment]
You must start with `.c` or `.cpp` and `.h` source files. Native executables or libraries for any other platform will not work. You cannot take an existing `.a` library and convert it.

You compile those source files to LLVM bitcode in `.o` files with `emcc` or `em++`.

Optionally you may wish to built multiple `.o` files into an `.a` or `.bc` library with `emcc` or `em++`. These will contain LLVM bitcode, which must be built targetting emscripten.

You may then compile the `.o`, `.a`, `.bc`, etc files to `.js` or `.js`+`.wasm` with `emcc` or `em++`.

`emcc` is a compiler tool, wrapping the `clang` compiler and accepts most `clang` options as well as emscripten-specific options. See the tutorial https://emscripten.org/docs/getting_started/Tutorial.html for basic setup and links to further documentation.

**Comment by brion** [comment]
Oh, and use `emar` in place of `ar`.

**Comment by exonent** [comment]
First of all. Thanks for the comments!

>  You must start with `.c` or `.cpp` and `.h` source files. Native executables or libraries for any other platform will not work. You cannot take an existing .a library and convert it.

> You compile those source files to LLVM bitcode in `.o` files with `emcc` or `em++`.

- So.. I have to use: `./emcc fileA.c fileB.c fileC.c fileD.h fileE.h ` ? Or need more attributes? 

> Optionally you may wish to built multiple `.o` files into an `.a` or `.bc` library with `emcc` or `em++`. These will contain LLVM bitcode, which must be built targetting emscripten.

- What command I have to use to build my `.o` files into an `.a` library?

> You may then compile the `.o`, `.a`,` .bc`, etc files to `.js` or `.js`+`.wasm` with `emcc `or `em++`.

- What's the different between compile into`.js` or `.js+.wasm`?
- What commant I have to use to compile my `.o`, `.a`,` .h` files to `.js` or `.js`+`.wasm`?
- I need to modfy my own `.o`, `.a`,` .h` files?
- How can I call my `.o`, `.a`,` .h` funtions using `JS`?

The question is: How can I build my lot of `.o`, `.c`, `.h` files in `JS` and call/use their functions?
Thx again!

**Comment by brion** [comment]
If you are not familiar with compiling C/C++ programs on the command line, you may wish to start with the emscripten documentation and tutorial:
* https://emscripten.org/docs/getting_started/Tutorial.html
* https://emscripten.org/docs/compiling/Building-Projects.html

**Comment by exonent** [comment]
hi @brion,

Ok have been working and reading a lot of documentation (Included your links). 
I'm doing a script to do all the work. Can you say me if I'm wrong with the process?:

>  //Generate a.out.js from two C sources.
> `./emcc fileA.c fileB.h fileC.c fileD.c fileE.c fileF.c `
> 
> //Generate fileA.o and fileB.o... containing LLVM bitcode
> `./emcc fileA.c fileB.h fileC.c fileD.c fileE.c fileF.c -c`
> 
> //Combine two LLVM bitcode files into a.out.js
> `./emcc fileA.o fileB.o fileC.o fileD.o fileE.o fileF.o`
> 
> //Combine two LLVM bitcode files into another LLVM bitcode file
> `./emcc fileA.o fileB.o fileC.o fileD.o fileE.o fileF.o -o result.o`

If everything is ok. Whats the next steps? What I have to do to make an `.a` file and call the functions?

Thx! have a good day!

**Comment by mariorodriguespt** [comment]
`What I have to do to make a .a file and call the functions?`
Please reopen this ticket, I'm facing the same issue.

**Comment by sbc100** [comment]
To build a static library you use `emar` (it works just like the normal `ar` tools that is part of traditional unix toolchains).

Just like the native toolchain object files from a library are only included if a symbol within that object is required by the linker.  You can force the export of a given symbol by adding it to `-s EXPORTED_FUNCTIONS` list.. or you can force the inclusion (but not the export) of all object files in a library using `-Wl,-whole-archive` and `-Wl,-no-whole-archive` on the command line before and after your library.

**Comment by sbc100** [comment]
I think the question here has been answered.  Feel free to re-open/comment if not.
