### ISSUE TITLE
Warn if SIDE_MODULE=1 without either EXPORT_ALL or EXPORTED_FUNCTIONS

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#7974]
AFAIU, in dynamic linking a side module would be useless without either EXPORT_ALL=1 or EXPORTED_FUNCTIONS set.
Hence emcc could warn the user when neither option are present.
(I just spent forever updating a dynamic linking experiment I had done last year...)

**Comment by pmp-p** [comment]
maybe could prevent https://github.com/emscripten-core/emscripten/issues/7811

**Comment by kripken** [comment]
Good idea @Beuc!

The place to add this is in `emcc.py`, can search for `SIDE_MODULE` there to find the right code area.

**Comment by rpopensource7** [comment]
Hi @Beuc  @kripken I want to push fix to that issue and noticed that EXPORTED_FUNCTIONS by default  contains Main function.
When you mean set you mean that it wont be empty or you mean it should be changed by the user to something that it isn't Main?

**Comment by Beuc** [comment]
A side module (e.g. a library .so file) isn't supposed to export `_main` in the first place, so SIDE_MODULE + EXPORTED_FUNCTIONS=['_main'] sounds suspicious too.
The real warning could be emitted when witnessing that the resulting .wasm file has no symbols (that would include e.g. when the user mistypes the wrong function names).

**Comment by Beuc** [comment]
AFAICS the issue is still relevant.
