### ISSUE TITLE
Opcode "Loop" is not permitted in intializer expressions

### ISSUE THREAD

**Issue by NicolasDorier** [emscripten-core/emscripten#7976]
So my ultimate goal is to compile a C project into WASM, then convert the [WASM to IL](https://github.com/RyanLamansky/dotnet-webassembly). (.NET Core)

I was able to compile my C program fine with this [dockerfile](https://github.com/bitjson/bitcoin-ts/blob/master/wasm/docker/secp256k1.Dockerfile) which use `emscripten` under the hood.

But when I tried to use the WASM to IL compiler, I ended up having the error [Opcode "Loop" is not permitted in intializer expressions](https://github.com/RyanLamansky/dotnet-webassembly/issues/9) .

I asked to the WASM to IL repository maintainer about it, and he pointed me out that [this seem not permitted by the spec](https://webassembly.org/docs/modules/#initializer-expression). Might it be a bug in `emscripten` or is there an improvement to webassembly spec somewhere allowing this?

**Comment by NicolasDorier** [comment]
Same issue with `trzeci/emscripten-slim:sdk-tag-1.38.25-64bit`

**Comment by kripken** [comment]
That does sound like an invalid wasm file, as loops are not allowed in initializer expressions. Was it emitted by emscripten? If you can provide the wasm output file (and preferably the input files + emcc command), I can take a look at it.

**Comment by NicolasDorier** [comment]
@kripken thanks for your help

Here is the [input file (.o)](https://aois.blob.core.windows.net/public/libsecp256k1_la-secp256k1.o) 

Here is the [output file (.wasm)](https://aois.blob.core.windows.net/public/secp256k1.wasm).

Here is how I generated the wasm file:
```bash
emcc src/libsecp256k1_la-secp256k1.o \
  # uncomment next line for debug build:
  # -O0 -g4 -s ASSERTIONS=2 --source-map-base ../../../wasm/secp256k1 \
  # uncomment next line for production build:
  -O3 \
  -s WASM=1 \
  -s NO_EXIT_RUNTIME=1 \
  -s DETERMINISTIC=1 \
  -s EXPORTED_FUNCTIONS='[ \
  "_malloc", \
  "_free", \
  "_secp256k1_context_create", \
  "_secp256k1_context_randomize", \
  "_secp256k1_ec_seckey_verify", \
  "_secp256k1_ec_privkey_tweak_add", \
  "_secp256k1_ec_privkey_tweak_mul", \
  "_secp256k1_ec_pubkey_create", \
  "_secp256k1_ec_pubkey_parse", \
  "_secp256k1_ec_pubkey_serialize", \
  "_secp256k1_ec_pubkey_tweak_add", \
  "_secp256k1_ec_pubkey_tweak_mul", \
  "_secp256k1_ecdsa_sign", \
  "_secp256k1_ecdsa_signature_malleate", \
  "_secp256k1_ecdsa_signature_normalize", \
  "_secp256k1_ecdsa_signature_parse_der", \
  "_secp256k1_ecdsa_signature_parse_compact", \
  "_secp256k1_ecdsa_signature_serialize_der", \
  "_secp256k1_ecdsa_signature_serialize_compact", \
  "_secp256k1_ecdsa_verify", \
  "_secp256k1_ecdsa_sign_recoverable", \
  "_secp256k1_ecdsa_recover", \
  "_secp256k1_ecdsa_recoverable_signature_serialize_compact", \
  "_secp256k1_ecdsa_recoverable_signature_parse_compact"\
  ]' \
  -o out/secp256k1/secp256k1.js
```

**Comment by kripken** [comment]
That wasm file looks valid. I don't see a Loop in an initializer. Also binaryen, wabt, and VMs can load it properly. So this looks like a bug in the tool that gave you that error.

**Comment by RyanLamansky** [comment]
The tool hasn't been checked with a lot of real WASMs yet, so this outcome doesn't surprise me.  It's being tracked over there with https://github.com/RyanLamansky/dotnet-webassembly/issues/9 .

**Comment by NicolasDorier** [comment]
Thanks a lot for the help, moving to the next blocking parts ;)
