### ISSUE TITLE
asm.js codegen code size: literals encoded with excess precision

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#7980]
Noticed this one looking at asm.js code size: given C/C++ code

```c++
clear_screen(0.1f, 0.2f, 0.3f, 1.f);
```

fastcomp generates

```js
_clear_screen(.10000000149011612, .20000000298023224, .30000001192092896, 1.0);
```

This seems to be due to a single vs double precision mismatch. A literal 0.1f is encoded as hex 0x3dcccccd inside fastcomp, but we convert it to a double, and then that double back to a string. This is not wrong, but it would be equally correct to generate the shortest text representation of a floating point number that encodes back to 0x3dcccccd as single precision (as opposed to needing to match binary as double precision). Since LLVM knows at each literal whether it's a float32 or a float64, it would be able to avoid generating extra precision.

In my MathGeoLib library I use Florian Loitsch's Grisu algorithm (https://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf) - that would be able to cut string encoding to the shortest needed form. Might try putting that in if I find time.

(Not super exciting since this issue will not apply to wasm, but still marking this down as it caught my eye)

**Comment by juj** [comment]
Let me reopen this: looking today, this same issue affects Wasm2JS builds in wasm backend.

```
emcc tests/minimal_webgl/main.cpp tests/minimal_webgl/webgl.c --js-library tests/minimal_webgl/library_js.js -lwebgl.js -s MINIMAL_RUNTIME=1 -s WASM=0 -O3 --closure 1 -g1 -o a.html
```
contains output like
```
 wa(v(0), v(0), v(1024), v(20), v(.800000011920929), v(.800000011920929), v(.800000011920929));
  qa = v(+s[Ta >> 2] - Ua * +v(v(v(Pa * v(.05000000074505806)) / v(100)) + v(.05000000074505806)));
  Pa = v(Ua * +v(xa(v(Pa * v(345362)), v(.019999999552965164)) + v(-.009999999776482582)) + +s[Qa >> 2]);
```
which is excessive. The same example with `clear_screen` from above occurs, with
```
 ba(v(v(.10000000149011612)), v(v(.20000000298023224)), v(v(.30000001192092896)), v(v(1)));
```

**Comment by juj** [comment]
Unminified with

```
emcc tests/minimal_webgl/main.cpp tests/minimal_webgl/webgl.c --js-library tests/minimal_webgl/library_js.js -lwebgl.js -s MINIMAL_RUNTIME=1 -s WASM=0 -O0 -g2 -o a.html
```
there's
```js
  clear_screen(Math_fround(Math_fround(.10000000149011612)), Math_fround(Math_fround(.20000000298023224)), Math_fround(Math_fround(.30000001192092896)), Math_fround($165));
```
Perhaps we could run an optimization pass that detects literals flowing into Math_fround(), and optimizes thoses to new double literals without the fround (as not needed), i.e. compute Math_fround()s at compile time?

**Comment by kripken** [comment]
This should be possible. The relevant place is `src/tools/wasm2js.cpp` in binaryen. There are already a few things with fround, see `isFround`. The tricky part here might be to figure how how small the text can be without losing precision.

**Comment by juj** [comment]
> figure how how small the text can be without losing precision.

There exists a nice compact research paper that prints single precision floating point numbers with minimal length strings. (https://github.com/juj/MathGeoLib/blob/master/src/Math/grisu3.c). I suppose `removePlusAndFround()` would be the place to hook that in to?

**Comment by kripken** [comment]
Oh cool!

About where to put the code, actually I realize now that around that code we have the AST in which a number is a number - we can't minify it there yet. In `src/emscripten-optimizer/simple_ast.h` is the AST writer, and `numToString` is where we emit the actual string for a number. We'd need to pipeline in the information that it's in an fround context - probably in `printCall` we can check if it's `MATH_FROUND` and if so we know it's a float and not a double.
