### ISSUE TITLE
asm.js codegen code size: redundant returns

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#7982]
In minimal WebGL demo (https://github.com/emscripten-core/emscripten/issues/7981), there also exists redundant `return` statements at the end of void functions, e.g.

```js
function _fill_solid_rectangle(d1, d2, d3, d4, d5, d6, d7, d8) {
  ...
 return;
}
```

The `return;` there does not seem necessary, even for asm.js validation, but could be dropped.

Not sure what this does in asm2wasm, might not be that exciting if the `return;` does not generate any extra code in wasm.

**Comment by kripken** [comment]
Hmm, I guess we never got around to optimizing that for asm.js. For wasm, `remove-unused-brs` would eliminate it.
