### ISSUE TITLE
asm.js codegen code size: u8/i8/u16/i16 arithmetic excess type annotation

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#7984]
Looking at

```c++
uint8_t __attribute__((noinline)) d(uint8_t a, uint8_t b)
{
	return a+b;
}

int main()
{
	uint8_t a = (uint8_t)emscripten_get_now();
	uint8_t b = (uint8_t)emscripten_get_now();
	printf("%d\n", (int)d(a,b));
}
```

generates

```js
function _d(i1, i2) {
 i1 = i1 | 0;
 i2 = i2 | 0;
 return (i2 & 255) + (i1 & 255) & 255 | 0;
}

function _main() {
 var i1 = 0, i2 = 0, i3 = 0;
 i1 = STACKTOP;
 STACKTOP = STACKTOP + 16 | 0;
 i2 = i1;
 i3 = ~~+_emscripten_get_now() & 255;
 HEAP32[i2 >> 2] = (_d(i3, ~~+_emscripten_get_now() & 255) | 0) & 255;
 _printf(2772, i2) | 0;
 STACKTOP = i1;
 return 0;
}
```

There
```js
(i2 & 255) + (i1 & 255) & 255 | 0
```
looks excessive. Iiuc this could be transformed to
```js
(i2 & 255) + (i1 & 255) & 255
```
and still be equivalent? I.e. `& 255` fulfills the same purpose of `& 255 | 0`? At least this kind of transformation does still validate properly in Firefox.

Another transformation that would be valid (although will revert the computation to run as `i32+i32->i8` rather than `i8+i8=i8`?) would be to do
```js
i2 + i1 & 255
```
which looks like it still validates ok.

This may be a bit of historic in interest, though asm.js fallback is still a huge deal for low-end mobile, so there is still value at looking at asm.js codegen size. (I assume this extra type annotation will not leak through to wasm with asm2wasm?)

**Comment by kripken** [comment]
That looks generally valid, however, there are some places where I think you do need a `|0`, like in function call arguments. But the asm.js optimizer should be aware of that. So this might be practical to add to `simplifyExpressions()` there.

> (I assume this extra type annotation will not leak through to wasm with asm2wasm?)

It should not, and asm2wasm's optimize-instructions should optimize it anyhow, I believe.
