### ISSUE TITLE
Native Node Module to WASM, CPU Architecture Problem?

### ISSUE THREAD

**Issue by semireg** [emscripten-core/emscripten#7987]
My goal is to migrate a native node module to WASM, but I'm running into issues with CPU architecture. I'm building on a MacBook Pro (2.9 GHz Intel Core i9) in MacOS and also inside a Windows 10 VM. My runtime target is an electron app (Chromium instance).

I can successfully build and use the WASM if I run it on the same architecture that it is built on. For my Windows build  of the electron app I'm using the Windows-built WASM. On the Mac build of the electron app I'm using the Mac-built WASM.

If I try using the Mac WASM on Windows, or Windows on Mac I get some variation of these errors:
```
wasm streaming compile failed: CompileError: AsyncCompile: Wasm decoding failed: Invalid function length (0) @+37886
CompileError: AsyncCompile: Wasm decoding failed: unknown section code #0x83 @+74623
Uncaught (in promise) abort({}). Build with -s ASSERTIONS=1 for more info.
```

I thought I "solved" the problem by just shipping both versions and deciding at runtime which one to load. However, I'm seeing suspicious crash reports (unclear stack traces) from Windows Store on Celeron and Core i3 device types. I suspect these are related to the WASM not running on these devices.

As you'll see below, I'm linking to a project named "image-worsener." Could it be that it's compiling this project in an architecture-specific way that creates later incompatibilities? What is the recommended method for making this work correctly?

Here's my build script on Mac:
```
#!/bin/bash

IWSRC=../imageworsener/src
OPTIMIZE="-O3" # 01 for test, O3 for release
MODULARIZE=1 # 1 for web, 0 for node (testing)

emcc -Wall \
  --bind \
  $OPTIMIZE \
  -o dither.js \
  -s MODULARIZE=$MODULARIZE \
  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
  -s ALLOW_MEMORY_GROWTH=1 \
  -I $IWSRC/ \
  $IWSRC/imagew-api.c \
  $IWSRC/imagew-util.c \
  $IWSRC/imagew-main.c \
  $IWSRC/imagew-opt.c \
  $IWSRC/imagew-resize.c \
  dither.cc

if [ $? -ne 0 ]; then
  echo "Error building"
  exit $?
fi
```

Windows 10:
```
$IWSRC="..\imageworsener\src"
$OPTIMIZE="-O3" # 01 for test, 03 for release
$MODULARIZE=1 # 1 for web, 0 for node

emcc -Wall `
  --bind `
  $OPTIMIZE `
  -o dither.js `
  -s MODULARIZE=$MODULARIZE `
  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' `
  -s ALLOW_MEMORY_GROWTH=1 `
  -I $IWSRC/ `
  $IWSRC/imagew-api.c `
  $IWSRC/imagew-util.c `
  $IWSRC/imagew-main.c `
  $IWSRC/imagew-opt.c `
  $IWSRC/imagew-resize.c `
  dither.cc
```

Thanks for any help!

Here's a link to my working repo: https://github.com/semireg/iw-dither

**Comment by kripken** [comment]
Something else is going on here - a wasm should compile regardless of which OS it was built on. So it's possible you're running into a bug in either the compilers, or the VMs. I'd suggest filing a bug - or continuing the discussion here, if relevant - specifying how you emitting the wasm, attaching that wasm, and specifying which VM(s) the wasm fails on `Wasm decoding failed: Invalid function length`.

**Comment by kripken** [comment]
`dither-win.wasm` is an invalid wasm file. it's possible you're running into a windows-specific bug in the tools used to create it.

Was this using the standard emsdk (so not using the upstream LLVM backend)? If so, then it's likely a binaryen windows bug. If you can provide the bitcode (or otherwise make the zip file a complete testcase) that would be good.

**Comment by semireg** [comment]
@kripken, thank you for your attention on this.

I had a longer reply written, but then I found the root cause... my windows git client was converting CRLF to LF and back! That explains why my workflow was symmetrically broken. GAH! 

Adding `*.wasm binary` to my .gitattributes seems to have "fixed" the problem. 🤣
