### ISSUE TITLE
Emterpreter and changing function names

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#7988]
(Note: I tried sending this twice to the emscripten-discuss mailing list, and it was silently dropped each time... Not sure what it didn't like)

When compiling my RenPyWeb project, which use Emterpreter, I often get
errors about new, non-whitelisted functions such as:

  ___Pyx_PyObject_CallNoArg_387
  ___Pyx_PyObject_CallNoArg_6345

This may happen when I make some changes in the code or in the
compilation flags.

AFAIU these are generated by Emscripten ('grep' only sees references in
Emscripten-generated files) and the numbers are some kind of offset.

This is annoying because I usually have to compile (5-10mn depending on
target), run in a browser and wait for complete startup (couple
minutes), get the new stack strace, edit my Makefile and
EMTERPRETIFY_WHITELIST, and repeat.
And I need to tell my users/contributors to do the same 

Is there anything I can do to avoid these dynamic function names?

**Comment by Beuc** [comment]
Those are static conflicts indeed:
```
gen/pygame_sdl2.transform.c:static CYTHON_INLINE PyObject* __Pyx_PyObject_CallNoArg(PyObject *func);
```
```
$ for i in *.o; do echo -n $i:; llvm-nm $i|grep CallNoArg || echo; done
pygame_sdl2.color.o:-------- t __Pyx_PyObject_CallNoArg
pygame_sdl2.controller.o:-------- t __Pyx_PyObject_CallNoArg
...
pygame_sdl2.surface.o:-------- t __Pyx_PyObject_CallNoArg
pygame_sdl2.transform.o:-------- t __Pyx_PyObject_CallNoArg
```

I don't know how the number is computed. It's moderately stable (doesn't change everytime), it's not the line number, and it changes depending on other files linked and possibly the linker options used.

With a 2-steps compilation (*.bc -> monolith.bc -> .html), I can see some matching symbols (modulo "." -> "_"):
```
-------- t __Pyx_PyObject_CallNoArg
-------- t __Pyx_PyObject_CallNoArg.10863
-------- t __Pyx_PyObject_CallNoArg.1301
-------- t __Pyx_PyObject_CallNoArg.1847
-------- t __Pyx_PyObject_CallNoArg.2057
-------- t __Pyx_PyObject_CallNoArg.216
```
which I can crudely flag:
```
-s EMTERPRETIFY_WHITELIST='["_main", ... $(shell llvm-nm build/t/index.bc | grep -Po '__Pyx_PyObject_CallNoArg\.\d+' | sed -e 's/\./_/' -e 's/.*/"&"/' | tr '\n' ',') ...]'
```
(I had to LOL though ;))

One issue is I cannot distinguish which ones to whitelist (though in this particular case these functions are reasonably quick).
If we need to live with this imprecision, a wildcard makes more sense.

**Comment by kripken** [comment]
Heh, nice shell command :)

Yeah, +1 for a whitelist wildcard then.

**Comment by Beuc** [comment]
For reference my work-around is flawed - and I don't understand how it worked until I upgraded today...
Missing a leading '_', and not executed by 'make' at the right time.
```
-s EMTERPRETIFY_WHITELIST='["...", '`llvm-nm build/t/index.bc | grep -Po '__Pyx_PyObject_CallNoArg\.\d+' | sed -e 's/\./_/' -e 's/.*/"_&"/' | tr '\n' ','`' "..."]'
```
