### ISSUE TITLE
Emscripten does not Identfy NODE_JS

### ISSUE THREAD

**Issue by vineethkartha** [emscripten-core/emscripten#800]
Dear Friends
I tried to install emscripten, but I couldn't get it working, this is the error I get when running  ./emcc tests/hello_world.c

(Emscripten: unknown, clearing cache)
warning: LLVM version appears incorrect (seeing "clang version 3.3 (trunk 173618)", expected "clang version 3.2")
warning: cannot check node version: [Errno 13] Permission denied
(Emscripten: Running sanity checks)
Checking JS engine /usr/bin/ failed. Check ~/.emscripten. Details: [Errno 13] Permission denied
FATAL: The JavaScript shell used for compiling (/usr/bin/) does not seem to work, check the paths in ~/.emscripten

I have made all settings in ~/.emscripten file

**Comment by ExpandingDev** [comment]
I had a similar problem, but then I changed 
```NODE_JS = 'node' ``` to ```NODE_JS = 'nodejs' ``` in my ~/.emscripten

I think this is an issue because of how the old and new versions of NodeJS name their executables.
http://askubuntu.com/questions/227271/checking-version-of-nodejs-returns-nothing
