### ISSUE TITLE
USE_PTHREADS=1 with NO_FILESYSTEM=1 breaks at -O1 and higher

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8001]
I've noticed that when setting USE_PTHREADS=1 something breaks when using NO_FILESYSTEM=1 to disable unused filesystem stuff. Tested on 1.39.25 and on juj's modularization+pthreads branch, seems the same on both.

Test file:

```c
#ifdef __EMSCRIPTEN_PTHREADS__
#include <emscripten/emscripten.h>
#include <emscripten/threading.h>
#include <pthread.h>
#endif

int main() {
	pthread_exit(NULL);
    return 0;
}
```

compile with:

```bash
emcc -O1 -o barfo.html -s USE_PTHREADS=1 -s NO_FILESYSTEM=1 barfo.c
```

Running the code in Firefox Developer Edition with SharedArrayBuffer enabled results in this error in console:

```
ReferenceError: FS is not defined[Learn More]
```

The JS contains some stray declarations trying to use this `FS` variable that does not exist:

```js
Module["FS_createFolder"] = FS.createFolder;
Module["FS_createPath"] = FS.createPath;
Module["FS_createDataFile"] = FS.createDataFile;
Module["FS_createPreloadedFile"] = FS.createPreloadedFile;
Module["FS_createLazyFile"] = FS.createLazyFile;
Module["FS_createLink"] = FS.createLink;
Module["FS_createDevice"] = FS.createDevice;
Module["FS_unlink"] = FS.unlink;
```

If I crank it down to `-O0` this line appears above those:

```js
if (!Module["FS"]) Module["FS"] = function() { abort("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)") };
```

and it seems to work without erroring out, since `FS.createFolder` etc will return `undefined` instead of throwing an exception when dereferenced.

(I've never seen this problem on non-pthreads builds, where I've used NO_FILESYSTEM=1 for years.)

**Comment by juj** [comment]
In `emcc.py` around line 1215 or so, if you delete

```py
        shared.Settings.EXPORTED_RUNTIME_METHODS += [
          'FS_createFolder',
          'FS_createPath',
          'FS_createDataFile',
          'FS_createPreloadedFile',
          'FS_createLazyFile',
          'FS_createLink',
          'FS_createDevice',
          'FS_unlink'
        ]
```

does that avoid the exports?

**Comment by brion** [comment]
@juj yeah that seems to remove the exports and gets both the minimal test case and my video decoder modules for ogv.js running.

Ah this is suspicious, when `USE_PTHREADS` is on it's also forcing `FORCE_FILESYSTEM=1` in emcc.py:

```python
      shared.Settings.FORCE_FILESYSTEM = 1 # proxying of utime requires the filesystem
```

Perhaps the combination of FORCE_FILESYSTEM=1 and NO_FILESYSTEM=1 is troublesome?

(As far as I know `utime` is a filesystem-specific function, so I'm not sure why it's called out specifically there unlike other filesystem-specific functions.)

**Comment by juj** [comment]
For some reason we enable `FORCE_FILESYSTEM=1` when building with `-s USE_PTHREADS=1`. Added a PR to remove that, `USE_PTHREADS` should definitely not imply `FORCE_FILESYSTEM`, but may be that some technicality currently requires that case.

Let's see what CI says on https://github.com/emscripten-core/emscripten/pull/8002, have not been able to try it locally.

**Comment by juj** [comment]
git blame goes way back in time for that line, https://github.com/emscripten-core/emscripten/commit/a9dceb6a1089dae8e718a9f59a9223d153b004ff , that can't be the breakage though, since it is so old.

**Comment by brion** [comment]
Closing out since fix was merged.
