### ISSUE TITLE
unable to build zmq for emscripten c 

### ISSUE THREAD

**Issue by kavikumarN** [emscripten-core/emscripten#8005]
i am trying to build zeromq  c library into emscripten. but i am not clear about the steps to be followed. [https://emscripten.org/docs/compiling/Building-Projects.html#building-projects]()

**Comment by jkbbwr** [comment]
You are going to have a hard time with zmq as real sockets arn't exposed in emscripten.

**Comment by kavikumarN** [comment]
is there any alternatives?

**Comment by jkbbwr** [comment]
sockets in emscripten are wrappers around websockets if I understand correctly.

https://blog.squareys.de/emscripten-sockets/
