### ISSUE TITLE
fatal error: 'GL/glx.h' file not found

### ISSUE THREAD

**Issue by ohmahgawditbob** [emscripten-core/emscripten#8020]
I have been trying to compile this GL program for a while that uses javidx9's pixelGameEngine, which uses the GLX library. I am guessing it might be because GLX works off of the X11 library, but I could have sworn I saw others using the X11 library on em++. I am unsure as to whether or not the GLX library can be supported in the future, but if you have any ideas, that would be great!

Edit: I have imported -lGL, and the first import of <GL/gl.h> includes just fine. I have also tried setting a flag of `-s USE_SDL=2`, and it did not help

Link to the pixelGameEngine: https://github.com/OneLoneCoder/olcPixelGameEngine/blob/master/olcPixelGameEngine.h

**Comment by ohmahgawditbob** [comment]
I notice now that it also uses libpng, so I might have to scrub the idea of compiling this project into webassembly

**Comment by kripken** [comment]
libpng is in emscripten ports, so you can use it with just `-s USE_LIBPNG=1`.

But glx would need to be ported, I don't think that has been yet.

**Comment by ohmahgawditbob** [comment]
alright, thanks! I will see if I can port the GLX to GL, but I might just wait until GLX is ported. Thanks for the help!

**Comment by PaulKania** [comment]
Curious: has GLX been ported?

**Comment by sbc100** [comment]
No, GLX is kind of specific to the X windows system.   Most codebases tend to support something more portable such as EGL or SDL (both of which are supported by emscripten).

**Comment by aisnote** [comment]
I meet this kind of same issue with EMSDK, how to solve it?  @sbc100   thanks

**Comment by sbc100** [comment]
We don't support GLX in emscripten.  Does your codebase perhaps have an alternative?
