### ISSUE TITLE
Modularized Javascript Output Uses Deprecated 'arguments' Function Property

### ISSUE THREAD

**Issue by zicklag** [emscripten-core/emscripten#8042]
I just found that I couldn't create an instance of an Emscripten library inside of a [Kha](https://github/Kode/Kha) app because the Javascript code generated by Haxe uses strict mode. I get the following error:

```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
```

My JS code is in strict mode and I am loading the library using `eval()` so the error is thrown whenever the generated module tries to access `Module["attributes"]` which is apparently a [deprecated function property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments#Browser_compatibility) that is disabled in strict mode. It would probably be good to eliminate the use of the deprecated `arguments` property in Emscripten's modularized modules.

**Comment by kripken** [comment]
I agree we should remove it. Searching in the source, looks like this happens in `_emscripten_traverse_stack` in library.js.

**Comment by woosle1234** [comment]
Hey new to GitHub I would like to tackle this issue

**Comment by kripken** [comment]
Hi @woosle1234! That would be great. Let me know if you have any questions.

**Comment by woosle1234** [comment]
I'm reviewing the deprecated function property:
- can someone explain the purpose of the _emscripten_traverse_stack? 
- what I can change the parameters to and what it should return?
- How should I handle args.callee.caller?

**Comment by kripken** [comment]
I think that method lets emscripten log out nice stack traces, including arguments. I don't think we can still do that without  the deprecated stuff, so we may need to just remove that - I'm not sure how much value it brings, but I'd guess not much.

**Comment by woosle1234** [comment]
> I think that method lets emscripten log out nice stack traces, including arguments. I don't think we can still do that without  the deprecated stuff, so we may need to just remove that - I'm not sure how much value it brings, but I'd guess not much.

So should I just remove _emscripten_traverse_stack entirely?
Also forgot to ask how I can test the code?

**Comment by zicklag** [comment]
Not sure if it will help in this instance, but there is a non-deprecated [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) variable, but I think it only lets you get the arguments of the function that you are currently in.

**Comment by woosle1234** [comment]
> Not sure if it will help in this instance, but there is a non-deprecated arguments variable, but I think it only lets you get the arguments of the function that you are currently in.

ya unfortunately, I also found out you can only get the function name and string only if the function is passed with no arguments. As far as I know caller is not possible to get.

**Comment by kripken** [comment]
> Also forgot to ask how I can test the code?

We have automatic tests in this repo, when you open a PR they will run. You can also run tests locally manually, but there are quite a lot, so it may make sense to run just the ones relevant for you before submitting the PR,

https://emscripten.org/docs/getting_started/test-suite.html

(to find relevant ones, you can search in `tests/` for things related to the feature)
