### ISSUE TITLE
Provide binaries for incoming

### ISSUE THREAD

**Issue by abitrolly** [emscripten-core/emscripten#8045]
It is impossible to use incoming Emscripten SDK on Travis with Rust. Installing incoming fails with timeout after 40 minutes - https://travis-ci.org/ethereumjs/rustbn.js/jobs/490901840 while installing latest takes only 40 seconds thanks to available binaries.

Docker is unlikely to help, because Rust calls `emcc` directly.

**Comment by kripken** [comment]
`latest` should be very close to `incoming` - is it not close enough for you?

**Comment by abitrolly** [comment]
`latest` fails.
```
          Unsupported:   %12 = tail call i128 @llvm.bswap.i128(i128 %11) #5
          LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
```
https://travis-ci.org/ethereumjs/rustbn.js/jobs/490897289#L632

**Comment by kripken** [comment]
That looks like a fastcomp bug - try `latest-upstream`, which we hope to make the default soon anyhow.

**Comment by abitrolly** [comment]
@kripken although the build fails https://travis-ci.org/ethereumjs/rustbn.js/jobs/650773025 the installation of `latest-upstream` is not longer takes 40+ minutes.
