### ISSUE TITLE
Any known issues with python SimpleHTTPServer and Web Workers?

### ISSUE THREAD

**Issue by chrjohnson** [emscripten-core/emscripten#8051]
Have you seen any issues with the python SimpleHTTPServer and the importScripts of Web Workers?

I was trying to test pthreads but kept getting errors so I tried building the solution found here and it still failed: https://developers.google.com/web/updates/2018/10/wasm-threads

The pre-built example works: https://alex-wasm.appspot.com/threads/index.html

I tested using IIS as the web server and the Alex Danilo solution works. Thought maybe it was an https thing but it works over http using IIS.

I put together a quick test without any Emscripten. The HTML file:
```
<!DOCTYPE html><html><body><script src="mytest.js"></script></body></html>
```
The JS in mytest.js:
```
let a = new Worker("myworker.js");
a.onmessage = function(e){ alert(e.data); }
```
The JS in myworker.js: `importScripts("MyWorkerHelper.js");`

The JS in MyWorkerHelper.js: `self.postMessage("Hello from the worker");`

It looks like new Worker and importScripts use the wrong content-type. Returns 'text/plain' instead of 'application/javascript'

The main JS (mytest.js) uses the right content-type.

**Comment by kripken** [comment]
@juj was seeing this as well, but I could not reproduce it, and we couldn't figure out what a safe way forward was. See discussion in https://github.com/emscripten-core/emscripten/pull/8007

**Comment by juj** [comment]
Oh, thought that was something odd in my setup. Brought back https://github.com/emscripten-core/emscripten/pull/8052 in a form that only affects the test suite.
