### ISSUE TITLE
Output warning message if pthread_create() won't start before yield

### ISSUE THREAD

**Issue by hostilefork** [emscripten-core/emscripten#8078]
There's a note in the special considerations section of the [pthread support in emscripten document](https://emscripten.org/docs/porting/pthreads.html), which says:

> When the linker flag `-s PTHREAD_POOL_SIZE=<integer>` is not specified and pthread_create() is called, the new thread will not actually start to run immediately, but the main JS thread must yield execution back to browser first.

I can see why in the web environment one might want to make the user conscious of how many web workers they were making, given that the situation is different than from OS threads.

But...my first try with pthreads had a signaling condition and mutex.  The idea was that the main thread would call `create_thread()` and then block until it received the signal.  So it hung, and I was perplexed because the messages seemed to suggest it was working (it said it was creating a thread, etc.)  Searching for "emscripten pthread_create won't start" turned up nothing--which seems surprising.

In any case: so long as it was printing out a message, I would have been greatly helped if it had said:

> Delaying thread creation until main thread yields, see link flag PTHREAD_POOL_SIZE to pre-allocate workers instead.

If not that, then a linker message when you have USE_PTHREADS but no PTHREAD_POOL_SIZE would probably do the trick as well.

(I'd send a PR for it, but I don't really know the right wording or place to put it, to warn only if needed.)

**Comment by kripken** [comment]
Good idea to add a warning about this. Can add it in `src/library_pthread.js`, in `pthread_create`, something like, `if ASSERTIONS and !PTHREAD_POOL_SIZE, then err("..text..")`
