### ISSUE TITLE
Explicitly import function from JS

### ISSUE THREAD

**Issue by nic-hartley** [emscripten-core/emscripten#8088]
I'm using `emcc` to generate plain WASM to import later. This is my code:

```cpp
#include "emscripten.h"
extern "C" {
  extern void print(int val);
  EMSCRIPTEN_KEEPALIVE
  void print_val(int num) {
    print(num * 2);
  }
}
```

I can compile this successfully:

```
emcc src/*.cpp -O3 -o html/hello.wasm -s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0
```

And then I can successfully link in the function:

```js
WebAssembly.instantiateStreaming(fetch("/hello.wasm"), { imports: { env: { _print: console.log } } }).then(...)
```

With this setup, though, I get an unnecessary warning about `print` not being defined, and my import has to be prefixed by a `_`.

I suspect the latter is unfixable (because that's how `extern "C"` works) but the former should be pretty trivial to fix. Is there a flag I can pass with functions that need to be linked in by the JS?

**Comment by kripken** [comment]
I believe you can set `-s WARN_ON_UNDEFINED_SYMBOLS=0` to avoid the warning.

**Comment by nic-hartley** [comment]
I mean, that still feels like a workaround, and if I accidentally `extern` something I didn't mean to (or `extern` something I meant to link but forgot to) it won't warn me. Is there any way to specify a list of function names to specifically ignore the warning for?

Actually, this doesn't sound like too difficult a feature to add -- something like `-s IMPORTED_FUINCTIONS="['print']"`, which just omits the line `print: extern function not defined` (or whatever it is; I don't have `emcc` in front of me to check). I'd be happy to look into actually doing that sometime next week.

**Comment by kripken** [comment]
Hmm, you could create a js library with those functions,
```
mergeInto(LibraryManager.library, {
  print: function(){},
  otherFunc: function(){},
});
```
If you then do `--js-library FILENAME` then it will include those into your JS. In your case I think you're not going to use that JS, but this approach would get you proper errors/warnings if a function is missing there.

An IMPORTED_FUNCTIONS could be even simpler, but I'm not sure how generally useful it would be. Perhaps it is important though if many people are not using the standard JS.

**Comment by nic-hartley** [comment]
I can't speak for everyone, obviously, but there really aren't any good options to just compile C++ to WASM, with no glue code. I've been using emcc because it's really easy to set up, it works well, and it allows me to generate _just_ WASM, no glue code, no extra fluff, nothing (as long as I use `-O3` at least). For me, personally, an `IMPORTED_FUNCTIONS` option would be really helpful. Doubly so if I could pick and choose which modules each function was imported through (e.g. importing `print` through the `std` module versus memory through `env`)

The JS library approach works fine for now, though, even if it's a little more bloated than I'd prefer. Thanks!

**Comment by kripken** [comment]
Makes sense. I think an option like that would be ok to add.

**Comment by allsey87** [comment]
Did a `IMPORTED_FUNCTIONS` ever get implemented?

**Comment by sbc100** [comment]
I think the `import_module` and `import_name` attributes are probably good solution to this problem.  They were added the last year or so and I think are better than adding command line options.    You can even use the `EM_IMPORT` as a shorthand for these: https://github.com/emscripten-core/emscripten/blob/acbf9e6749780f1e5d41ab941ed2f40263b62f99/system/include/emscripten/em_macros.h#L13
