### ISSUE TITLE
SDL2 Mixer 

### ISSUE THREAD

**Issue by Unwarped** [emscripten-core/emscripten#8097]
On the latest version of Emscripten. SDL2 Mixer always fails to build.

`emcc main.c -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS=["png"] -s USE_SDL_TTF=2 -s USE_SDL_NET=2 -s FULL_ES3=1 -s USE_WEBGL2=1 --preload-file resources -Os --closure 1 -s ALLOW_MEMORY_GROWTH=1 -o SDL_game.html`

> emscripten:INFO: generating port: sdl2-mixer.bc... (this will be cached in "C:\Users\username\.emscripten_cache\asmjs\sdl2-mixer.bc" for subsequent builds)
> Traceback (most recent call last):
>   File "C:\emsdk\emsdk\emscripten\1.38.27\emcc.py", line 3153, in <module>
>     sys.exit(run())
>   File "C:\emsdk\emsdk\emscripten\1.38.27\emcc.py", line 1608, in run
>     compile_source_file(i, input_file)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\emcc.py", line 1593, in compile_source_file
>     args = get_clang_args([input_file]) + ['-c', '-o', output_file]
>   File "C:\emsdk\emsdk\emscripten\1.38.27\emcc.py", line 1574, in get_clang_args
>     args = system_libs.process_args(args, shared.Settings)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\system_libs.py", line 1004, in process_args
>     args = port.process_args(Ports, args, settings, shared)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\ports\sdl2_mixer.py", line 42, in process_args
>     get(ports, settings, shared)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\ports\sdl2_mixer.py", line 31, in get
>     return [shared.Cache.get('sdl2-mixer', create, what='port')]
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\cache.py", line 111, in get
>     temp = creator()
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\ports\sdl2_mixer.py", line 25, in create
>     ports.run_commands([[shared.EMCONFIGURE, configure, '--prefix=' + dist_dir] + formatflags + commonflags + ['CFLAGS=-s USE_VORBIS=1']])
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\system_libs.py", line 791, in run_commands
>     run_commands(commands)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\system_libs.py", line 33, in run_commands
>     call_process(command)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\system_libs.py", line 26, in call_process
>     shared.run_process(cmd, stdout=stdout, stderr=stderr)
>   File "C:\emsdk\emsdk\emscripten\1.38.27\tools\shared.py", line 166, in run_process
>     proc = Popen(cmd, *args, **kw)
>   File "C:\emsdk\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "C:\emsdk\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
>     startupinfo)
> WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by kripken** [comment]
That might be a windows issue - this works on our linux both. The sdl2-mixer setup runs configure, so to fix this the best thing might be to skip that step and bundle the output from it, and replace the makefile with our own python, like we did for sdl (compare sdl_mixer.py and sdl.py in tools/ports).

**Comment by Unwarped** [comment]
Yes you're right it worked fine on a linux sub-system I installed. That will be a good workaround for now. Thanks Alon.
