### ISSUE TITLE
USE_PTHREADS=1 requires ENVIRONMENT='web,worker'

### ISSUE THREAD

**Issue by hostilefork** [emscripten-core/emscripten#8102]
When building with `USE_PTHREADS=1` and `ENVIRONMENT=web`, the loading worker does not have ENVIRONMENT_IS_WORKER set.  This makes it error on not being able to find `document`:

    if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
         if (ENVIRONMENT_IS_WORKER) {
              scriptDirectory = self.location.href;
         } else if (document.currentScript) {  // <-- problem here loading *.worker.js
              scriptDirectory = document.currentScript.src;
      }

I found [#7801: "ENVIRONMENT=web disables worker detection"](https://github.com/emscripten-core/emscripten/issues/7801).  The resolution of that was to add `ENVIRONMENT=web,worker`.

Indeed, changing this to `ENVIRONMENT=web,worker` made the error go away.  But it was difficult to find the option, and I'm still a bit puzzled about it.  If it's not a holistic setting that understands USE_PTHREAD+web, then how would it know which is which?

It seems to me that `ENVIRONMENT=web` and `USE_PTHREADS=1` should be sufficient to "just work".

**Comment by kripken** [comment]
We recently made the compiler error, and require that you allow both web and worker at compile time, so this should be less confusing. But yes, we should probably make it do that automatically.
