### ISSUE TITLE
Integer size issue with WebVR

### ISSUE THREAD

**Issue by jaadelgren** [emscripten-core/emscripten#8109]
While using the WebVR API, I ran into an issue where the header vr.h uses `unsigned long`s in a few places (specifically the `maxLayers` member of the `VRDisplayCapabilities` struct and the `renderWidth` and `renderHeight` members of `VREyeParameters`), which on several of the platforms I've tested on are 32-bits, while library_vr.js writes to these `unsigned long`s as if they were 64-bit integers. Ultimately it was leading to other memory on the stack being overwritten, which was somewhat difficult to track down. Hopefully I'm not missing something obvious, and thanks for this awesome project!

**Comment by jaadelgren** [comment]
Just to clarify, the specific functions that were causing issues were `emscripten_vr_get_display_capabilities` and `emscripten_vr_get_eye_parameters`, which were writing outside the bounds of `VRDisplayCapabilities` and `VREyeParameters`, respectively.

**Comment by kripken** [comment]
Yeah, those should probably be `uint32_t` (or `uint64_t`, as needed). And the JS code should refer to them as such, I see they are marked as `i64` now which is wrong (since even the current `unsigned long` is an `i32` in practice).

**Comment by jaadelgren** [comment]
Cool, thanks for confirming that. I made the change to `uint64_t`s locally just to get by for the time being, but I would be surprised if 32-bits wasn't enough for the usages here.

**Comment by kripken** [comment]
Good to hear that fixes things. Please open a PR to fix it upstream too, if you have the time.

**Comment by quantum5** [comment]
Seems like this is fixed in #8145. Please reopen if it's not.
