### ISSUE TITLE
Exports object in MODULARIZE mode is alive/mutable with ALLOW_MEMORY_GROWTH

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#8118]
Just realized that there is a fundamental incompatibility with MODULARIZE and ALLOW_MEMORY_GROWTH as far as external JS code is considered.

In MODULARIZE mode we wrap the JS code into a function, and return an exports object from that function when instantiated. That is, we have

```js
function MyModule(Module) {
  ...
  Module['buffer'] = buffer = new WebAssembly.Memory(...);
  Module['HEAPU8'] = HEAPU8 = new Uint8Array(buffer);
  ...

  function updateGlobalBuffer(buf) {
    Module['buffer'] = buffer = buf;
  }

  function updateGlobalBufferViews() {
    Module['HEAPU8'] = HEAPU8 = new Uint8Array(buffer);
    ...
  }

  return Module;
}
```

Then user code does
```js
var imports = { ... };
var exports = MyModule(imports);
```
to instantiate. Here `exports` received `Module` from inside the compiled code runtime scope.

What becomes brittle/incompatible here is that `Module['buffer']` and `Module['HEAPU8']` can change at runtime. So for external code, the following will work:

```js
// at startup/init time
var imports = { ... };
var exports = MyModule(imports);
...
// some time much later at runtime
exports['HEAPU8'][16] = 0x42;
```
but the following will not
```js
// at startup/init time
var imports = { ... };
var exports = MyModule(imports);
var heap = exports['HEAPU8'];
...
// some time much later at runtime
heap[16] = 0x42;
```
because the returned export object is "alive" and heaps+views are updated to it at runtime when memory grows, rather than being an immutable/constant one off returned value.

I don't know if it is common/expected that this kind of alive connection exists for exports objects for modules in general in node.js/es6/requirejs/amd world, but to me this strikes as something that is really particular to how our MODULARIZE=1 exports object works. I kind of always assumed exports would behave as if they returned an immutable set of fields.

Is it enough to solve this with documentation only? Or can this create trouble? Is this a big difference to how exports objects usually work, or is this kind of "mutating exports" aspect a common occurrence? I do not really see any other way we could support memory growth than to let the exports object mutate, and document that developers cannot retain their own references to `buffer` and `HEAP*` objects returned from the exports.

**Comment by curiousdannii** [comment]
I think it's fine. You shouldn't think of MODULARIZE as exporting multiple objects, but one, the Module itself. There's no guarantee that an object's properties won't be overwritten, and I'd expect that most JS devs who would be directly accessing the heaps are prepared for this.

**Comment by kripken** [comment]
I also think it's fine as is. Even if we see the individual Module properties as separate exports, ES6 modules allow exports of [constant and non-constant values](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export), so there is no assumption that exported values are constant.
