### ISSUE TITLE
sse/intrinsics missing since 1.38.26

### ISSUE THREAD

**Issue by jkgrytten** [emscripten-core/emscripten#8120]
When compiling a codebase at work I get errors (from clang?) that -msse option is not recognized.
Also the folder system/include/SSE is missing (installed on windows using emsdk install).
It's OK in 1.38.25. Couldn't find anything reported on this.

**Comment by VirtualTim** [comment]
See #7924 
In my own experience SSE was about 6 times slower than no SSE. I think we need to wait for proper WASM SIMD to actually get better performance.
I think that's still a decent way away though. See https://www.chromestatus.com/feature/6533147810332672 and https://github.com/WebAssembly/proposals/issues/1

**Comment by jkgrytten** [comment]
Ah, many thanks for pointing this out & working towards improving the situation. I didn't dig deeper than the changelog before upgrading since I usually find indications of breaking changes there.  It was convenient to have x86 intrinsics for the (illusion of) portability but it seems like the benefits stops right there.
