### ISSUE TITLE
out of executable memory in function at index xxxx  on iOS safari

### ISSUE THREAD

**Issue by PeterWangNavisens** [emscripten-core/emscripten#8121]
version: 1.38.22 (commit c486741551124af6e40fbdfd03e1505a35deecc1)
platform: iOS safari

On desktop & android, it does not show the error when refreshing the page, it only happens on iOS safari.
A 7.5 mb webasm file compiled with ALLOW_MEMORY_GROWTH=1 -s WASM_MEM_MAX=128M
it does not show on first loading, only happens when refreshing the page.

**Comment by kripken** [comment]
This kind of thing may mean that the browser has not fully collected the page's memory before starting to reload the page. There's not much we can do here, but you may be able to work around this by reducing the memory or binary sizes.

It may also be worth filing a bug on the WebKit bug tracker, perhaps they can improve that behavior.

**Comment by evanw** [comment]
We get this from time to time too at Figma. For people that also end up here, I found these links relevant:

* https://bugs.webkit.org/show_bug.cgi?id=181723
* https://github.com/emscripten-core/emscripten/issues/6042
