### ISSUE TITLE
accessing Emscripten in Windows Subsystem for Linux with Visual C++ 

### ISSUE THREAD

**Issue by stephassoria** [emscripten-core/emscripten#8125]
Hello,

this is not really an issue, but more a try to start a discussion.
We were using emscripten in visual studio with vs-tool, but as it's now deprecated I recently tried another way by : 
- installing Windows Subsystem for Linux (https://docs.microsoft.com/fr-fr/windows/wsl/install-win10) with Ubuntu
- installing emscripten sdk in this Ubuntu => works fine
- targeting linux in WSL from visual c++ 2017 community (https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/)
- changing compiler to  ~/emsdk/emscripten/tag-1.38.26/emcc in visual c++ project settings 

but I'm getting this error : 
F:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(348,5): error : ~/emsdk/emscripten/tag-1.38.26/emcc exited with code 1, please see the Output Window - Build output for more details (NOTE: the build output verbosity might need to be changed in Tools Options to see more information in the Output Window).

Anyone having done some more tests here ?

    thanks,

            Stéphane

**Comment by VirtualTim** [comment]
I actually just set up something similar recently. I'm running WSL with Ubuntu, and Docker inside that, using the trzeci/emscripten image. That's all been working great for me, better than the VM I was using before. It seems like WSL has had some changes for 1809 (October update), are you running that one?
The only major issue I had was that perforce messed up some of the line endings. Shell scripts and the makefile needed linux line endings, but all the source code compiled fine with windows line endings.

I haven't tried connecting to Visual Studio, but that seems like an interesting idea. Let me know if you get it working.

**Comment by stephassoria** [comment]
Hi Tim,

Emscripten works fine for me in WSL as far as I can see. And yes, this is the 1809 version of Windows 10.
We maintain a cross platform framework in C++, and the easy way for us is to use Visual C++ for all targets. It's OK for mainly all platforms (Android, iOS, Win32, Hololens, Linux, even Nintendo Switch or 3DS...) but for Emscripten. 
     Stéphane
