### ISSUE TITLE
embuilder: Building bitcode and object libraries

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8128]
Right now with the LLVM wasm backend, embuilder will build object file libraries for libc, libc++ etc. It came up in https://github.com/emscripten-core/emscripten/pull/7929 that we should probably build the bitcode versions too, for people that want to do bitcode LTO.

Automatically building them would basically double the time it takes to run embuilder. May be worth it, as it's the simplest thing.

Another option is to add an "lto" option for embuilder, that builds the LTO versions. That would give embuilder users more control (maybe some don't need LTO libraries built).

**Comment by sbc100** [comment]
I think we can have an embuilder option for this:

Perhaps `./embuilder build ALL --lto`?  Or `./embuilder build ALL -s WASM_OBJECT_FILES=0`?  Or `./embuilder build_lto ALL`.
