### ISSUE TITLE
Loop fails to unroll at -O3

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8139]
While doing performance tuning on the [dav1d](https://code.videolan.org/videolan/dav1d) AV1 video decoder library for emscripten, I found that a constant-size inner loop in the `cdef_filter_block_c` function was not being unrolled despite building at -O3.

The loop body is relatively large, but it benefits from unrolling (either hand-done or using a clang-specific pragma) because it allows folding some constants at compile time, improving total throughput by a consistent 2%.

I've collected the offending function in a smallish test case here: https://github.com/brion/emscripten-loop-test

Native building using Apple's clang seems to unroll the loop if I'm reading the disassembly correctly, while the bitcode emitted from emscripten/fastcomp doesn't show any sign of that loop being unrolled unless I add a pragma (add `#pragma clang unroll(enabled)` on line 89 ahead of the 2-item for loop)

**Comment by kripken** [comment]
Is that with asm2wasm or the LLVM wasm backend? (If asm2wasm, perhaps we don't have some IR option set right, but not sure it's worth fixing as we hope to replace it soon; if wasm backend, we definitely want to look at it.)

**Comment by brion** [comment]
That's with asm2wasm; will check with llvm backend after llvm finishes building on this machine. ;)

**Comment by brion** [comment]
Ok, confirmed that it unrolls as expected with native backend. Yay!

Since I can patch in a `#pragma` to force it to unroll on fastcomp, I think that's good enough for me.

**Comment by kripken** [comment]
Great, thanks for confirming!

Closing as that's going to be the default soon anyhow.

Btw, this is the kind of benefit we hope to get from that backend, as it's just better written and integrated with LLVM in general.
