### ISSUE TITLE
How to match types of thrown objects?

### ISSUE THREAD

**Issue by kbumsik** [emscripten-core/emscripten#8141]
Hi, I'm trying to add exception handling in my code.
Emscripten throws a pointer value to JS side, which make sense to me. But while I had a quick look at the source code of generated JS file, I noticed that there is [a piece of code that tries to find a matching type and dereference it](https://github.com/emscripten-core/emscripten/blob/609fb83548ddf70696a863b2624a8b5bdee45e86/src/library.js#L1654) (maybe I'm wrong). However, I couldn't find any relevant documentations or emcc option.

How can I make use of `__cxa_find_matching_catch` part? My current code does nothing but prints `can_catch on {pointer]` when an exception is thrown .

Thanks,
Bumsik Kim

**Comment by aheejin** [comment]
Not sure what you are trying to do with the library code, but you can use emscripten exception support by using `-s DISABLE_EXCEPTION_CATCHING=0` option. So that should be something like
`emcc -s DISABLE_EXCEPTION_CATCHING=0 yourfile.cpp`
