### ISSUE TITLE
USE_LIBPNG=1 WASM_OBJECT_FILES=1 build error

### ISSUE THREAD

**Issue by msorvig** [emscripten-core/emscripten#8143]
Looks like the USE_LIBPNG=1 WASM_OBJECT_FILES=1 combination is broken:

```
em++ -s USE_LIBPNG=1 -s WASM_OBJECT_FILES=1 main.cpp 
emscripten:INFO: generating port: libpng.bc... (this will be cached in "/Users/msorvig/dev/emsdks/.emscripten-vanillallvm-cache-1.38.27/wasm_o/libpng.bc" for subsequent builds)
root:INFO: building port: libpng
llvm-link: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: /Users/msorvig/dev/emsdks/llvm-master-build/bin/llvm-link -help
```

emcc (Emscripten gcc/clang-like replacement) 1.38.27 (commit b81acebe6921f07b15b575cb9d49398da123622e)

**Comment by kripken** [comment]
I can't reproduce this with current incoming. It is also tested on our bots, as we run `embuilder build ALL` which includes that. So my guess is that this is a problem that has been fixed.
