### ISSUE TITLE
memory leak related to emscripten_fetch

### ISSUE THREAD

**Issue by paulli2017** [emscripten-core/emscripten#8152]
Hi,

I am debugging a memory leaking issue in Firefox nightly build, which ran our test application. In our test application we used emscripten_fetch API to get chunk from HLS streaming server(test running at LAN server 10.73.82.177). After several hours running, I noticed that Firefox NightlyCP web content used double size memory as those of the chunks downloaded from server, which seems that the memory used to store the chunk content is never released. 

Actually I read this issue:   
https://github.com/emscripten-core/emscripten/issues/6359 
and from the discussion the memory leaking issue should be solved.  Unfortunately I still can reproduce the issue with the almost same test application written by me:  (My test is based on latest emscripten code release: 1.38.27. Compiling command is: emcc -s fetch.c -s  WASM=1 -s FETCH=1 -o fetch.html)

Is there still anything missing here when I used emscripten_fetch API to fetch HLS chunks?
Thanks for your help! 

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <emscripten/fetch.h>

void downloadSucceeded(emscripten_fetch_t *fetch) { 
  printf("Finished downloading %llu bytes from URL %s time=%u\n", fetch->numBytes, fetch->url);  
  emscripten_fetch_close(fetch); 
}

void downloadFailed(emscripten_fetch_t *fetch) {
  printf("Downloading %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
  emscripten_fetch_close(fetch);
}

int main(int argc, char* argv[])
 {
  printf("Test started\n");
  int time = 20000;
  while(time >= 0) {    
    emscripten_fetch_attr_t attr;
    emscripten_fetch_attr_init(&attr);
    strcpy(attr.requestMethod, "GET");    
    attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY;
    attr.onsuccess = downloadSucceeded;
    attr.onerror = downloadFailed;    
    emscripten_fetch(&attr, "http://10.73.82.177/test1M.ts");    
    time--;
  }
  printf("End of test\n");
  return 0;
}

**Comment by kripken** [comment]
cc @juj

**Comment by paulli2017** [comment]
Further investigating this issue, I used memory profiling tool provided by Firefox browser when I ran the test application on MacOS. I noticed that the most memory used were from ArrayBuffer type data, which were the memory allocated by the javascript to store the HLS chunk(video file) downloaded from server. 
You can get this from the screen shot I got while the test application was running.
![memory_usage](https://user-images.githubusercontent.com/24902466/53659234-e2dfbb00-3c0f-11e9-90a2-78cdbe03aab9.jpg)

As I searched from internet, it seems the release of ArrayBuffer type data memory should be taken cared by GC of javascript( I am from c/c++ background). From this test, however, it seems that the GC never kicks in to collect those memory after the video chunk was decoded and displayed on browser, which leads to the total memory usage keep growing up.  Later I found this memory leaking discussion in Nodejs used by Emscripten,  https://github.com/nodejs/node/issues/21021
From the discussion,  there is memory leaking issue in Node.js V8.*, but it is already fixed in Node.js V9. * , however, current emscripten still used V8.9.1. 
Does it really mean the current memory leaking issue in my test come from Node.js?  Do I need to run my test with latest version of Node.js?  If so, how should I update the current Node.js in emscripten? 
Really appreciate your help with this!
