### ISSUE TITLE
wasm-ld warnings "unexpected existing value" on sdk-upstream-3346

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8158]
When trying to build the dav1d decoder library with the LLVM Wasm backend, I get a large number of errors from `wasm-ld` at link time:

```
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=176224 expected=0
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=177248 expected=0
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=178272 expected=1024
wasm-ld: warning: unexpected existing value for R_WASM_MEMORY_ADDR_I32: existing=179296 expected=2048
```
etc; there are several hundred of various address types.

I'm not quite sure what it indicates or how I can fix it... The resulting module doesn't run properly, but I don't know if that's related to this or not.

Testing on Fedora 29 with a fresh emsdk checkout, installed via `./emsdk install latest-upstream`.

**Comment by brion** [comment]
The warnings go away if I set `-s WASM_OBJECT_FILES=0` and use bitcode objects in the .a library.

Still not working at runtime, which could be some other problem. I can provide build details as necessary.

**Comment by kripken** [comment]
I think that's https://bugs.llvm.org/show_bug.cgi?id=40503
