### ISSUE TITLE
js created (by Webassembly and emscripten) works only once

### ISSUE THREAD

**Issue by rod2712** [emscripten-core/emscripten#8169]
I'm using Webassembly and emscripten for a project and the webpage is working very well. In it I send a textarea with information to the .js created (by Webassembly and emscripten), for processing, but, oh, there is the problem !!, only works only once, when I modify the which is in the textarea and resubmit to js, ​​it does nothing. When I reload the page it works again (only once).

**Comment by VirtualTim** [comment]
I think you may have to submit a minimal example for people to be able to understand what you're talking about.
