### ISSUE TITLE
Declare imports/exports in C++

### ISSUE THREAD

**Issue by IngwiePhoenix** [emscripten-core/emscripten#8171]
Hey!

I am just getting started and my head wrapped around WASM (and WAT) and one thing I noticed is that the generated WebAssembly has imports and exports - most of which being pre-defined by Emscripten.

The reason I am most interested in this has to do with dynamic linking. I may be wrong here, but I believe that utilizing the imports object would allow for dynamic linkage to be possible, by offering the exports of one WASM file to the imports of another.

So how can I precisely define imports and exports from my C/C++ code? I know that I could use EmBind or NBind to achieve exporting... but I only really want to generate the `(import "a" "b" ...` and corresponding exporting statements as per my definition.

How do I do that? Thank you! :)

**Comment by sbc100** [comment]
Emscripten does already support a form of dynamic linking in the form of
SIDE_MODULE and MAIN_MODULE.  Its flat namespace that all symbols (from the
main and the side module) live in, rather then a two-level namespace.  So
all symbols are imported from "env" and any exported symbols effectively
get added to "env".     Normally when build with either SIDE_MODULE or
MAIN_MODULE you would also add "-s EXPORT_ALL", but you the normal method
of `-s EXPORT_FUNCTIONS` on the command line or EMSCRIPTEN_KEEPALIVE in the
source code can also be used.

**Comment by sbc100** [comment]
I think you can now do this with the "import_name", "import_module" and "export_name" clang attributes:  https://lld.llvm.org/WebAssembly.html#exports
