### ISSUE TITLE
missing function 

### ISSUE THREAD

**Issue by ValSergey** [emscripten-core/emscripten#8174]
Hello,
have idea why  missing function: emscripten_glMapBufferRange?
---------------------------------------------------------------------------------------
I use -s USE_WEBGL2=1 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["bmp","png","xpm"]'  -s USE_SDL_MIXER=2

**Comment by ValSergey** [comment]
It is project on OpenGL ES 3.0 work well

**Comment by ValSergey** [comment]
Emscripten compile a project without error, but Google Chrome give error: missing function: emscripten_glMapBufferRange

**Comment by kripken** [comment]
Please provide a testcase if you can, as this does sound like a bug somewhere.

**Comment by ValSergey** [comment]
#ifdef glMapBufferRange
#undef glMapBufferRange
#endif
#define glMapBufferRange(a, b, c, d) (void *)0

it is to work

**Comment by hugoam** [comment]
You need to build with `-s FULL_ES3=1` for those functions to be even defined, as per the implementation: https://github.com/emscripten-core/emscripten/blob/1.38.30/src/library_webgl.js#L3320
In my opinion, it would not cost much to add a dedicated/more helpful error message in a stub implementation of those functions when `FULL_ES3` evaluates to 0, after that #if block.
