### ISSUE TITLE
Possible LLVM backend SIMD autovectorization bug in dav1d library

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8175]
Ok now that I've got working upstream LLVM builds, I'm taking a peek at SIMD autovectorization.

With latest-upstream-3454 I get a 'memory access out of bounds' error during the dav1d decoder library's initialization, seemingly in the `init_chroma` inline function of `fill2d_16x2` in `wedge.c`.

```
RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at fill2d_16x2 (wasm-function[9]:1895)
    at dav1d_init_wedge_masks (wasm-function[8]:971)
    at main (wasm-function[10]:7)
    at Object.Module._main (https://brionv.com/misc/kersplat/test-simd.js:1823:74)
    at Object.callMain (https://brionv.com/misc/kersplat/test-simd.js:1949:30)
    at doRun
```

I'm not sure whether the problem is the compilation, or Chrome's implementation of the SIMD instructions. I'm testing in Chrome Canary 74.0.3714.0 on macOS, started with `--js-flags="--experimental-wasm-simd"` to enable the SIMD support.

Broke out just the offending setup code to a test repo: https://github.com/brion/emscripten-simd-bug

Test repo includes a standalone source file, Makefile with commands to build SIMD and non-SIMD versions which either fail or work in Chrome, and my build artifacts.

I'm not sure exactly which bit is going wrong as touching the loops in almost any way ends up changing how it's optimized and often makes the error go away (but then a similar error elsewhere in the library happens).

**Comment by kripken** [comment]
cc @tlively

**Comment by brion** [comment]
Thomas has narrowed down the issue on the V8 side and filed as https://bugs.chromium.org/p/v8/issues/detail?id=8927

Thanks!

**Comment by VirtualTim** [comment]
Linked bug is closed. Presumably this should be closed too.

**Comment by brion** [comment]
Yep, closing.
