### ISSUE TITLE
How to convert c++  to  js clean code 

### ISSUE THREAD

**Issue by liang94huai** [emscripten-core/emscripten#8178]
I just want to convert c++ code to js,a source to source operation

I don't need to run on the web platform.

how to do that?

**Comment by VirtualTim** [comment]
[https://emscripten.org/docs/porting/index.html](https://emscripten.org/docs/porting/index.html)

Assuming you aren't doing anything fancy like using threads, try compiling like
`emcc test.cpp -o test.js`
Additional compiler options are the llvm compiler options, plus additional stuff you can see by running emcc --help. Additional linker options are found here [https://github.com/emscripten-core/emscripten/blob/incoming/src/settings.js](https://github.com/emscripten-core/emscripten/blob/incoming/src/settings.js).
