### ISSUE TITLE
emrun Default Browser

### ISSUE THREAD

**Issue by Coder-256** [emscripten-core/emscripten#8179]
By default on macOS, `emrun` always opens Safari. However, simply [removing `-a Safari` here](https://github.com/emscripten-core/emscripten/blob/3e0c3e129d4534f099412c810bbcad6208a95031/emrun.py#L1562) would open the URL with the user's default browser! For example, if you have Chrome set as your default browser, it would just open up a new tab as expected, rather than using Safari by default. AFAIK, there isn't currently any way to change the **default** browser except for passing `--browser` every time.

I would open a PR to fix this, but the `emrun` script is a bit convoluted IMHO, and I don't want to break anything/anybody's workflow. If using the browser set in `System Preferences` would not be a good idea, maybe the best way would be setting an environment variable to override the default browser? Or maybe both; an environment variable, if set, overrides System Preferences. IMHO either way is better than having [a hardcoded default of Safari](https://github.com/emscripten-core/emscripten/blob/3e0c3e129d4534f099412c810bbcad6208a95031/emrun.py#L1458). Thoughts?

**Comment by sbc100** [comment]
Seems reasonable to default to the system default to me.

**Comment by VirtualTim** [comment]
At a glance it looks like the proposed change would break if the default browser is Safari, right?

**Comment by sbc100** [comment]
Is there actually a proposed change here (PR)?   Can you explain how the change as described would be break if the default browser was Safari (also do you mean the default on the user's machine or the default in emrun?).

**Comment by VirtualTim** [comment]
I was just referring to this:
> [removing `-a Safari` here](https://github.com/emscripten-core/emscripten/blob/3e0c3e129d4534f099412c810bbcad6208a95031/emrun.py#L1562) would open the URL with the user's default browser

**Comment by Coder-256** [comment]
@VirtualTim If the default browser is Safari, nothing would change at all. `-a` simply overrides the default. My concern is that it may cause unexpected behavior if the default browser is *not* Safari (ex. command line flags, incompatible browsers, etc) but IMHO it's still worth it, especially for people like me who just use Chrome and don't want Safari popping up each time. I  really doubt that anything would break but it's important to test for sure and I don't know how to handle all the complex cases in the `emrun` script which is why I didn't just open a PR.

**Comment by sbc100** [comment]
@Coder-256 did you see the comment in the code the @VirtualTim linked to though.  Might be a little subtlety there.  I think your best bet is to create a patch and we can see how it looks.

**Comment by Coder-256** [comment]
Sorry for the delay, I opened a PR.
