### ISSUE TITLE
Typo in library_syscall.js

### ISSUE THREAD

**Issue by vedadkajtaz** [emscripten-core/emscripten#8190]
Hello,

This seems to be a typo in `library_syscall.js` regarding the syscall 265:
```
    SYS_clock_gettime: 265,
```

vs

```
  __syscall265: function(which, varargs) { // clock_nanosleep
#if SYSCALL_DEBUG
    err('warning: ignoring SYS_clock_nanosleep');
#endif
    return 0;
  },

```

That being said, I wonder what is the purpose of this syscall - `SYS_clock_gettime` is only being referenced from `int __clock_gettime(clockid_t clk, struct timespec *ts)` in musl's `clock_gettime.c`, yet the linker retains the implementation in `library.js`.

**Comment by kripken** [comment]
I don't think it's used, yeah. Would still be nice to fix the typo - maybe you want to write a PR?

**Comment by kripken** [comment]
Looks like this syscall was removed meanwhile.
