### ISSUE TITLE
EMSCRIPTEN_KEEPALIVE doesn't work with WebAssembly backend + metadce

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8194]
Followup to #6233

`wasm3.test_llvm_used` fails due to this.

I think the issue is that in metadce we remove everything but what the user explicitly exported (if we see it is not used). What fastcomp does is append `llvm.used` to `ORIGINAL_EXPORTED_FUNCTIONS`. Do we have a way to do that with the LLVM wasm backend?

cc @sbc100

**Comment by sbc100** [comment]
I don't see ORIGINAL_EXPORTED_FUNCTIONS ever getting appended to in the source code.  Am I missing something?  I'll keep digging.

**Comment by sbc100** [comment]
> I don't see ORIGINAL_EXPORTED_FUNCTIONS ever getting appended to in the source code. Am I missing something? I'll keep digging.

Looks like its `shared.Building.user_requested_exports` that is failing to include this.

**Comment by kripken** [comment]
Oh sorry, yeah, we may have renamed that at some point.
