### ISSUE TITLE
variables in functions in side modules overwrites global variables

### ISSUE THREAD

**Issue by jb-pol** [emscripten-core/emscripten#8204]
I have a structure like this:

struct parse_info
{
	object_local_gl3Dobj_parse_xaml *obj;
	wchar_t *t;
	unsigned long line;
	std::wstring error;
};

and uses this in a function like this;

void somefunction()
{
	parse_info pinf;
        //other code following
}

Since this struct contains an object variable (std::wstring error) is it given a default constructor that is called automatically for me when the code reaches the variable declaration point. So far so good... except that this call overwrites some global memory variables and thereby trashes their content...

I don't know if this is a general problem with object variables in a struct or if it is specific to std::wstring

I do however know that changing it to:
void somefunction()
{
	parse_info *pinf = new parse_info();
        //other code following
        delete pinf;
}
works, I do however have an unkown number of places in my code looking similar and just finding them is a pain, changing all of them (and covering all posible exits from the function) is an even greater pain.

emscripten version: 1.38.28

I am using a main module compiled with MAIN_MODULE=2, the code above is located in a side module. The trashed global variables are in my case located in the main module.

I am using asm.js, not wasm

**Comment by jb-pol** [comment]
After more testing does this seem to be a more general problem, this sometimes fails with more general variables too. For some reason is the variables at the stack allocated over the global variables.

**Comment by kripken** [comment]
I'm not aware of any open bugs that sound like that. If you can make a full standalone testcase, that would help investigate this.

**Comment by jb-pol** [comment]
Ok, I think I have it now:

Main module, compiled with -s ENVIRONMENT=web -s WASM=0 -s LEGACY_VM_SUPPORT=1 -s MAIN_MODULE=2 -s EXPORTED_FUNCTIONS="['_main','_printf']" 

// emscripten_test.cpp 
//

#include <stdio.h>
#include <emscripten.h>
#include <dlfcn.h> 


void *module;

static char msg[]="Hello World!";

void sideLoadFail(const char *filename)
{
	printf("sideLoadFail\n");
}

void sideLoad(const char *filename)
{
  module=dlopen(filename,RTLD_NOW);
	if (!module) { printf("unable to dlopen\n"); return; }

	int(*fp)(int a)=(int(*)(int a))dlsym(module,"fn");
	if (!fp) { printf("unable to dlsym\n"); return; }

	for (int i=0;i<=12;i++) //12 is the length of msg
		printf("msg[%d]=%d\n",i,msg[i]);

	int res=fp(63);

	printf("res=%d &msg=%p\n",res,&msg);
	for (int i=0;i<=12;i++) //12 is the length of msg
		printf("msg[%d]=%d\n",i,msg[i]);
}


int main()
{
	printf("%p:%s\n",&msg,msg);

	emscripten_async_wget("sidemod.js","sidemod.js",sideLoad,sideLoadFail);
	return 0;
}
// end of emscripten_test.cpp 

Side module, compiled with -s ENVIRONMENT=web -s WASM=0 -s LEGACY_VM_SUPPORT=1 -s SIDE_MODULE=1 

// sidemod.cpp
//

#include <stdio.h>
#include <emscripten.h>

extern "C" EMSCRIPTEN_KEEPALIVE int fn(int a)
{
	int v1=a-1;
	int v2=a+1;
	char buffer[0x274];
	printf("fn() a=%d &a=%p v1=%d &v1=%p v2=%d &v2=%p buffer=%p\n",a,&a,v1,&v1,v2,&v2,buffer);
	return v1*v2;
}
// end of sidemod.cpp

When I run this I get:
0x3a8:Hello World!
msg[0]=72
msg[1]=101
msg[2]=108
msg[3]=108
msg[4]=111
msg[5]=32
msg[6]=87
msg[7]=111
msg[8]=114
msg[9]=108
msg[10]=100
msg[11]=33
msg[12]=0
fn() a=63 &a=0x3cc v1=62 &v1=0x3c8 v2=64 &v2=0x3c4 buffer=0x130
msg[0]=63
msg[1]=0
msg[2]=0
msg[3]=0
msg[4]=-52
msg[5]=3
msg[6]=0
msg[7]=0
msg[8]=62
msg[9]=0
msg[10]=0
msg[11]=0
msg[12]=-56


Changing the size of buffer in the side module function moves the adress for a,v1 and v2 and it is possible to move them to any point inside the main module variable msg. Some adresses does however cause something else to crash making the final print of msg just dissapear, anyway stack allocations in the side module function overwrites things it shouldn't.

**Comment by jb-pol** [comment]
Uploading my example files and the compiled version.
This needs to be run from a web server since the side module is dowloaded using emscripten_async_wget

[em_test.zip](https://github.com/emscripten-core/emscripten/files/2914767/em_test.zip)

**Comment by jb-pol** [comment]
After reverting to an older version (1.38.11), (seems to work) and looking at the output it makes me confused, does each side module have it's own memory area for allocating local variables, and does that mean it just sits around there unused if there isn't any function call into that side module? If that is true it sounds to me like wasted memory.

**Comment by sbc100** [comment]
The side module shares the memory with the main module, including the stack.   In this case the v1, v2, and buffer locals in the side module should all be allocated on the stack on demand.   Its not obvious to me how the corruption is occurring.  I would try reducing this tests case even more if you can.

**Comment by jb-pol** [comment]
I know the memory is shared, otherwise would it not be possible to pass pointers, but the adress of variables allocated on the stack varies in a way not expected (at least not by me) between variables in the main module and in the side module. I don't think the example can be much smaller: you need a side module and it needs to export a function where local variables are declared. The buffer variable is there to adjust the adress so the collision actually occurs with something I can monitor.

It might need to be expanded a bit: declare a local variable in the function sideLoad and examine it's adress (or examine the adress of filename. It is far from the adress of the variables in the side module function, and if they are using the same allocated stack they should be close. Calls within the same module allocates variables close to each other in a more expected manner.
