### ISSUE TITLE
Runtime.dynCall undefined

### ISSUE THREAD

**Issue by aimemilos** [emscripten-core/emscripten#8205]
Hi,

I switched from using version sdk-1.38.24-64 bit to sdk-1.38.28-64bit.
**The error below is present since `sdk-1.38.26-64bit`**
In my application the following run-time error during downloading of data occurs: 

`Uncaught Type Error: Runtime.dynCall is not a function at XMLHttpRequest.xhr_onload`

the error happens in this piece of code:

    xhr.onload=function xhr_onload(){
      if(xhr.status==200&&xhr.response){
        var byteArray=new Uint8Array(xhr.response);
        var buffer=_malloc(byteArray.length);
        HEAPU8.set(byteArray,buffer);
        Runtime.dynCall("viii",onload,[arg,buffer,byteArray.length]);   <-----------
        _free(buffer)
      }else{
        Runtime.dynCall("vii",onerror,[arg,xhr.status])
      }
    };

I checked that in version 1.38.24, the generated code (js) contains: `var Runtime={dynCall:dynCall};`
In version 1.38.28 the same source code gets generated into `var Runtime={};` which leads to `dynCall` being undefined.

The `dynCall` function is being defined in both versions.

Is the `Runtime` variable being generated by emscripten? If so, how can I influence the resulted `Runtime` variable assignment?
Were there some changes that made the previous version incompatible?

Thank you very much, for any suggestions.

**Comment by kripken** [comment]
The Runtime object has been deprecated and removed. Calling `dynCall` instead of `Runtime.dynCall` should work.

**Comment by aimemilos** [comment]
thank you very much, that helped
