### ISSUE TITLE
Free Ways to Deploy WebAssembly Application?

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#8209]
I'm sorry if this is a noob question.  

I have a WebAssembly application and I want to know how I can deploy it for free.  [Here](https://github.com/DragonOsman/makechange-wasm) is a link to the source code.  So yeah, how do I do it?

Note: I tried to deploy it to [Heroku](https://heroku.com), but I got this error:
```
E:\programming\Emscripten_WASM\cppbydissection_makechange_wasm\makechange-wasm>git push heroku master
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (6/6), 1.48 KiB | 380.00 KiB/s, done.
Total 6 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote:  !     No default language could be detected for this app.
remote:                         HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote:                         See https://devcenter.heroku.com/articles/buildpacks
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to makechange-wasm.
remote:
To https://git.heroku.com/makechange-wasm.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/makechange-wasm.git'
```
For Heroku we need a buildpack that would tell it how to build the app.  I'm new to this stuff, though.

**Comment by jakogut** [comment]
Assuming it's already built, [GitHub Pages](https://pages.github.com/) might work for you.

**Comment by DragonOsman** [comment]
Yes, it's built. Do I put the .wasm file into the repository?

This one's a frontend app, but would GitHub Pages work for one that uses a backend WebAssembly module?  Just wondering.

**Comment by jakogut** [comment]
It would only work for a static page using WASM.

**Comment by DragonOsman** [comment]
I already have a GitHub Pages site I'm working on for this account, by the way.  It's my portfolio website.  I wanted to port some C++ exercises I've done to WebAssembly and display them on the portfolio page.  I don't think it'd be a good idea if I made a separate GitHub account for every single WebAssembly app I want to show on the page.  So aren't there any other options?

I also want to ask another question: is there no way to take the prompt for input from the original C++ code and send it to the JavaScript glue code generated by Emscripten so that I can use it as the string input to the `window.prompt` method?  I tried to cut a part of the text displayed in the textarea on the HTML page, but it didn't work like I wanted so I had to give up and just manually edit the string passed to the `window.prompt` method.  And there's also the issue of it generating the message to ask for input multiple times, even after it's been given the input needed.  I have to click the checkbox to get it to not produce any more messages.  Is there no way to fix that?  

And I'd prefer to be able to use an HTML form instead of `window.prompt`, so I was wondering if there was a way to do that that actually worked.

**Comment by DragonOsman** [comment]
I put the files for the Wasm program in the same folder that my portfolio site's HTML files are in and provided a link to the app directly in the portfolio page itself.  So this issue is solved.  I still have the question about `window.prompt` and how the popup dialogue keeps coming up even after giving the input the app needs.  I'll open another issue for that.  

My portfolio website is available [here](https://dragonosman.github.io).  The Wasm app is [here](https://dragonosman.github.io/makechange.html).
