### ISSUE TITLE
Passing data from pthread-worker to main thread

### ISSUE THREAD

**Issue by electricric** [emscripten-core/emscripten#8212]
Hi,

i'm trying to use an external C++ SDK in my javascript app. I wrote some C++ glue code and in general calling functions from my C++ code to JS and vice versa works flawlessly. However, i'm stuck with the following problem:

I'm calling an embinded SDK-function from my js-app. The SDK then does some work involving spawning a pthread. Finally, the thread invokes a callback function within my C++ glue code. 

That works, but now i need to notify my js-app that the SDK-function finished, eventually passing it some data. However, my C++-callback still runs in the pthread-context, so i can't access emscripten::val::global or run functions via EM_JS to access an object on my js-app. 

I stumbled over [this post](https://github.com/emscripten-core/emscripten/issues/4998#issuecomment-284486358) by @kripken , suggesting to call `emscripten_run_script("postMessage('myMessage')");` from the thread and then implementing the onmessage-callback in the --pre-js file. But i could not figure out how to implement this. Simply adding `self.onmessage = function(){...}` disturbes the normal Module/Worker communication. 

I guess i would need some kind of onmessage-proxy, filtering my own messages and passing the others to the Module? Or is there another way to communicate from a worker to the main thread?

Any help would be appreciated!

**Comment by electricric** [comment]
I think i found a solution. Does not seem to be super elegant, but hey, it works!

I found the following worker-callback in the Module:
`````
worker.onmessage = function(e) {
[...]
	else if (d.cmd === 'objectTransfer') {
		PThread.receiveObjectTransfer(e.data);
      }
`````

Later PThread.receiveObjectTransfer is defined with an empty method body:

`````
receiveObjectTransfer:function (data) {
}
`````

I'm not sure what this method was originally designed for? 
Can somebody shed some light on this?
 
I decided to overwrite the method in my `--post-js` file, hoping there will be no side effects in future versions of the emscripten-sdk:

`````
//post-js.js
if(!ENVIRONMENT_IS_PTHREAD) {
    PThread.receiveObjectTransfer = function (data) {
        let event = new CustomEvent('worker_message', {detail : data.msg});
        window.dispatchEvent(event);
    };
}
`````

Invoking it from the C++ side (running in a pthread) looks like the following:
`````
//bridge.cpp
emscripten_run_script("postMessage({cmd: \"objectTransfer\", msg: \"foobar\"})");
`````

As `emscripten_run_script` is using eval(), you can put arbitary additional data into the object, as long as  cmd : "objectTransfer" is present. 

Now i can use a regular EventListener somewhere in my main js-app to react to the event created: 

`````
//app.js
addEventListener('worker_message', function(e) {
   console.log(e.detail);
});
`````

**Comment by sbc100** [comment]
I would hope there was a simpler way to do this kind of thing.  What about the functions in `include/emscripten/threading.h` such as `emscripten_sync_run_in_main_thread`?

**Comment by sbc100** [comment]
Or `emscripten_async_run_in_main_runtime_thread`

**Comment by VirtualTim** [comment]
Oh that's genius hijacking the `receiveObjectTransfer` function.
The method is empty because it's body is in an `OFFSCREENCANVAS_SUPPORT` block:
https://github.com/emscripten-core/emscripten/blob/30eb07a16404e6075c8672f63e1d35e190a6f476/src/library_pthread.js#L224-L236

Of course that means that someone could ifdef out more `OFFSCREENCANVAS_SUPPORT` stuff, like the entire `objectTransfer` message handling... But lets hope that doesn't happen any time soon...

Personally I'm trying to run a JS function that triggers a C++ callback at intervals, that triggers DOM changes (changes being specified in a user defined lambda). I can run the callback in a thread, but I'm trying to figure out how to call a JS lambda (specified at run time) on the main thread from a C++ callback, and this might do the trick.

**Comment by colin-guyon** [comment]
@sbc100 indeed you guessed correctly, `emscripten_sync_run_in_main_thread` and `emscripten_async_run_in_main_runtime_thread` allow me to run JS code in the main UI thread from a pthread in the C/C++ side, and this allows me to interact with the DOM if needed...
But is it safe/future-proof to use these functions? (as they don't seem to be documented in the Emscripten's API doc)

**Comment by sbc100** [comment]
I think they are as stable as any of our other APIs.  We try to avoid changing them if we possibly can.   My understanding is that these are not internal-only functions so you are free to use them.  @juj might provide more certainty?

**Comment by VirtualTim** [comment]
We should at least document these (and others in [threading.h]( https://github.com/emscripten-core/emscripten/blob/master/system/include/emscripten/threading.h))

Documentation for similar things like MAIN_THREAD_EM_ASM [can be found here](https://emscripten.org/docs/api_reference/emscripten.h.html#c.MAIN_THREAD_EM_ASM), but I don't know if this is the right place for those other functions.

**Comment by colin-guyon** [comment]
Great I didn't notice `MAIN_THREAD_EM_ASM` and `MAIN_THREAD_ASYNC_EM_ASM` but it is exactly what I need :)

**Comment by gerald-dotcom** [comment]
Any example on `emscripten_sync_run_in_main_thread ` ?

**Comment by colin-guyon** [comment]
For e.g. (can also be used without arg, and in ASYNC version) :
```
MAIN_THREAD_SYNC_EM_ASM(
    console.log(some_arg);
, some_arg);
```

**Comment by mmarczell-graphisoft** [comment]
Is there something like MAIN_THREAD_EM_ASM except taking a C++ code block instead of a JS one?

**Comment by sbc100** [comment]
@mmarczell-graphisoft I believe you can use `emscripten_sync_run_in_main_runtime_thread:  https://github.com/emscripten-core/emscripten/blob/aab919ddfe92e88c8f1d67159d41e2291af7a1dd/system/include/emscripten/threading.h#L248-L249
It take a function pointer and sequence of args.. is that what you are looking for?

**Comment by mmarczell-graphisoft** [comment]
Thanks, exactly what I was looking for. It's really unfortunate that there is no documentation for it. An example for posterity:

```
extern "C" EMSCRIPTEN_KEEPALIVE void invokeCallback (void (*callback) (char*)) {
	std::thread ([callback] {
                // Some expensive computation
	        char* pBuf = computation_result ();		
		emscripten_sync_run_in_main_runtime_thread(EM_FUNC_SIG_VI, callback, pBuf);
	}).detach ();
}
```

(TypeScript)
```
let pCallback: number;
const callback = (pData: number) => {
	observer.next(UTF8ToString(pData));
	removeFunction(pCallback);
}
pCallback = addFunction(callback, 'vii');
Module.ccall('invokeCallback', null, ['number', 'number'], [url, pCallback]);
```

**Comment by monoto** [comment]
Looks like this issue is not yet fixed when passing std::string to MAIN_THREAD_EM_ASM from a pThread.

MAIN_THREAD_EM_ASM({
	var uuid = UTF8ToString($0);
	console.log(uuid);
}, aTicket->uuid.c_str());

I'm getting garbage in uuid.

**Comment by sbc100** [comment]
`MAIN_THREAD_ASYNC_EM_ASM` runs your code at a later time and returns right away.   You need to ensure your `uuid` string (more precisely, the result of `c_str()`) stay alive long enough so they are available once the code runs.   So without extra checks this code could be buggy/racey.

**Comment by monoto** [comment]
Yes, you are absolutely right.  Keep it a bit longer, and the problem went away.
