### ISSUE TITLE
IDBFS is not defined

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#8213]
This issue occurs with emscripten 1.38.25 (also 1.38.28 - just tested), worked fine in 1.38.21

We use emscripten in a worker and use the file packaging to load fonts during run time.

After the web assembly has been parsed we run the following code

```
        Module['onRuntimeInitialized'] = function(){ 
            Module.PdfViewerModelInitialize();
            FS.mkdir('/Caches');
            FS.mount(IDBFS, {}, '/Caches');
            FS.syncfs(true, function (err) {
                if (!err) {
                    resolve();
                } else {
                    reject("Failed to load IDBFS: " + err);
                }
            });
        };
```

The problem is when I compile with 1.38.25 IDBFS is not defined in the .js file created by emscripten. 

I use following command to build the web assembly:

```
emcc -s FORCE_FILESYSTEM=1 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=0 -s WARN_ON_UNDEFINED_SYMBOLS=1 -s DISABLE_EXCEPTION_CATCHING=0 -s NO_EXIT_RUNTIME=1 -s EXTRA_EXPORTED_RUNTIME_METHODS="['stringToUTF8']" -s \"BINARYEN_TRAP_MODE='clamp'\"  -s ENVIRONMENT=worker --bind -s LZ4=1 --pre-js pre.js --post-js ${CMAKE_SOURCE_DIR}/gwt/libPdfViewerAPI_post.js -O2 libpdfwebviewerapi.bc -o ${CMAKE_BINARY_DIR}/libPdfViewerAPI_WASM.js
```
Is there a change that I missed that removes IDBFS from the .js?

**Comment by kripken** [comment]
Thanks, I think this can be fixed by https://github.com/emscripten-core/emscripten/pull/8221 (more details there). Sorry about the regression!

**Comment by fibbo** [comment]
Thank you, it works now!
