### ISSUE TITLE
LinkError: WebAssembly Instantiation: Import #1 module="env" function="enlargeMemory" error: function import requires a callable

### ISSUE THREAD

**Issue by domoritz** [emscripten-core/emscripten#8230]
I compiled a C++ application to WASM but with the latest version of emscripten, I get the error above (it worked before). The code I use to initialize the app is at https://github.com/domoritz/wasm-clingo/blob/master/index.html. The build script is at https://github.com/domoritz/webclingo-example/blob/dom/rebuild/compile_web.sh#L43. I noticed that the module file (`clingo.js`) does not have a method `enlargeMemory` anymore. Is that intended? How should I provide this function now?

**Comment by sbc100** [comment]
Looks like this functions was renamed to `emscripten_resize_heap` in 1655d72383eaeb79c5bdd764c5502833bb9c457a

**Comment by domoritz** [comment]
Hmm, shouldn't emscripten automatically change the call then or did I miss something?

**Comment by sbc100** [comment]
That depends if the call site is from your code from the emscripten code.  Presumably the call is coming from your code since there are no more references to this function in the emscripten itself.  If you are calling this function from your code you will need to update it.

**Comment by domoritz** [comment]
It must be coming from the c++ code that is being compiled into wasm rather than my js code since i only make a single call in the example linked above. How is this a problem now but not with previous versions of emscripten?
