### ISSUE TITLE
dlopen: RuntimeError: indirect call signature mismatch

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#8235]
I'm exploring dynamic linking and WebAssembly and stumbled over following weird issue.

I have a main module and one side module. The side module contains one function which just returns a float.

```
extern "C" {

  float ReturnFloat()
  {
    return 10.4;
  }
}
```

The main module can load this function via a function exposed through embind and the linked function can then be called with another function.

The loading of the side module works, the linking of the function also works. But calling fails with the error message from the title.

Compiling this with C++ and then running the executable works without any issue. Changing the return types to double fixes the issue.

MWE here: https://github.com/fibbo/WebAssemblyTests/tree/master/return_float_dlopen

html to test it here: https://github.com/fibbo/WebAssemblyTests/blob/master/returnfloat.html

This happens with 1.38.28

**Comment by kripken** [comment]
This is probably a legalization issue - f32 is not a valid type for JS, so we fix things up for it. But we have a mismatch somewhere in how we do that and how we use it.

You can try to build with `-s LEGALIZE_JS_FFI=0` to avoid legalization (that means JS won't be able to call illegal functions though; but wasm will).
