### ISSUE TITLE
--llvm-lto 3 -s USE_PTHREADS -s FETCH=1 broken in 1.38.28

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8242]
Compiling something simple like:
```
#include <iostream>
int main(int argc, char** argv) {
	std::cout << "test" << std::endl;
}
```
Using: `emcc test.cpp --llvm-lto 3 -s USE_PTHREADS -s FETCH=1 -o test.html` Will result in the error 
`shared:ERROR: failed to find function _pthread_mutexattr_init!`

This worked in 1.38.27. Compiling with `-s WASM=0` doesn't change the error.
`--llvm-lto 2` works for the above example, but the actual code I'm working on requires `--llvm-lto 0` to compile.

**Comment by kripken** [comment]
Possibly a bug where we assume that function exists without adding an explicit export for it, and LTO manages to optimize it out in this case.

**Comment by VirtualTim** [comment]
`_pthread_mutex_init` also needs to be exported.

I thought I could add something like this `shared.Settings.EXPORTED_RUNTIME_METHODS += ['_pthread_mutexattr_init', '_pthread_mutex_init']`
around here: https://github.com/emscripten-core/emscripten/blob/incoming/emcc.py#L2067, but that didn't seem to change anything.
Adding `'_pthread_mutexattr_init', '_pthread_mutex_init'` to `-s EXPORTED_FUNCTIONS` fixes this.

**Comment by kripken** [comment]
What code calls those pthread mutex functions? If it was in the JS, then exporting would be the natural solution. I don't see that though. So we should find out where it's called, and understand why normal linking didn't bring those in.

**Comment by VirtualTim** [comment]
Not really sure how this all works, but these functions are called in the generated fetch.js, and looks like they [should be imported here](https://github.com/emscripten-core/emscripten/blob/7cae0636bbe44092b20b3a7679ed4562e31a0b89/tools/shared.py#L3145)?
So I'm sure really sure how those get removed.

**Comment by kripken** [comment]
Ah, this might be related to the special fetch-worker stuff then. I think only @juj understands that code well. It would be good to rewrite that as a simple/normal pthread at some point.

**Comment by VirtualTim** [comment]
I think the fix is to add these to library_fetch.js, in a similar manner to #9202.
I don't have time right now to work on a PR, but I'll look at this in the future.
