### ISSUE TITLE
"random_device" Error

### ISSUE THREAD

**Issue by robertaboukhalil** [emscripten-core/emscripten#8247]
I'm porting a C++ codebase and getting this error when I launch the `.html` file:

![image](https://user-images.githubusercontent.com/2009870/53887374-fb1c5500-3fd6-11e9-876d-4c2b7d4487f5.png)

Looking at the `.js` glue code generated ([link to corresponding file in repo](https://github.com/emscripten-core/emscripten/blob/4f1bcf1c7b1de20ecff13ae8ddfd1a727516d495/src/library_fs.js#L1310)):

```javascript
// setup /dev/[u]random
var random_device;
if (typeof crypto === 'object' && typeof crypto['getRandomValues'] === 'function') {
  // for modern web browsers
...
```

It's checking whether `crypto` is an object, but `crypto` isn't defined anywhere. So if I modify the `.js` to define `var crypto = window.crypto;`, it works great and I no longer get the `random_device` error.

Is this a bug or is there another way to make sure `crypto` is properly defined in `library_fs.js`?

[I'm using Emscripten 1.38.26 (commit c486741551124af6e40fbdfd03e1505a35deecc1)]

**Comment by sbc100** [comment]
This looks like it could be related to ES6 modules.  What `-s` flags are you passing when building your project, and how are you loading the JS?

**Comment by kripken** [comment]
https://github.com/emscripten-core/emscripten/pull/8223/files may be relevant here, but this seems like it might be a different issue.

**Comment by robertaboukhalil** [comment]
@sbc100: I'm passing it the `-s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2` flags and I'm compiling to `.html` so using the Emscripten glue code to load the JS

@kripken: ah I see, I could use `--pre-js` to define it

**Comment by mabrownptc** [comment]
This does look like a scoping issue where the use of crypto should have the 'window.' prefix on it.
When I debug the call to FS.createDefaultDevices() (FF & Chrome) it fails to use the browsers crypto implementation and instead assigns the 'random_device' to the else conditions implementation.

1.38.11 Emscripten used to have a simple Math.Rand implementation so people were probably not aware it's not using the browsers crypto.
1.38.26 assigns an abort function which causes our program to stop working.
Looking at the latest submitted code for library_fs.js it still looks like it will fail.

To debug this put a breakpoint in the library_fs.js assigning the random_device and execute this code in the console
FS.rename('/dev', '/dev_old')
FS.createDefaultDevices();

**Comment by robertaboukhalil** [comment]
Seems like this is no longer an issue in the latest emscripten so I'll close the ticket :D
