### ISSUE TITLE
Load SIDE_MODULEs on the fly

### ISSUE THREAD

**Issue by mmontag** [emscripten-core/emscripten#8256]
How do we load SIDE_MODULEs on the fly?

I know we have 
```es6
import MainModule from './mainmodule.js';

const mainModule = new MainModule({
    dynamicLibraries: ['sidemodule1.wasm', 'sidemodule2.wasm'],
    onRuntimeInitialized: () => {...},
    ...
}
```
but this loads heavy side modules immediately - I want to load modules only when they are needed (for example, after the user clicks a button). 

What is the equivalent way to do this on the fly in Javascript? I have tried with 
```es6
        fetch('sidemodule1.wasm')
          .then(response => response.arrayBuffer())
          .then(buffer => new Uint8Array(buffer))
          .then(binary => mainModule.loadWebAssemblyModule(binary, {
            loadAsync: true,
            global: true,
            nodelete: true,
          }))
          .then(sidemodule => 
             // invoke code in sidemodule that depends on mainmodule
          );
```
 but **it doesn't seem to set up the linking between modules**.

**Comment by sbc100** [comment]
You can call `dlopen`, or perhaps `loadDynamicLibrary` the function on which it is based.

**Comment by mmontag** [comment]
Thank you @sbc100 ! `loadDynamicLibrary` is exactly what I need. Here are a few things I was missing that might improve the documentation: 

1. Major problem: I was building with `-O2` and all the helpful comments were removed from the Emscripten runtime, plus Chrome couldn't effectively step through the minified bundle. I had no idea what argument to pass to `loadDynamicLibrary`.
2. `loadDynamicLibrary` fails, at least in Chrome, without the `loadAsync: true` option in the flags. 
3. Once the side module is loaded with this method, the new symbols are available on the original main module.
