### ISSUE TITLE
Emcc command error

### ISSUE THREAD

**Issue by WafflePersonThing** [emscripten-core/emscripten#8269]
I installed Emscripten using the instructions from the emscripten website and tried to run emcc  -v not sure what this error means. How do I fix it?
``` [emsdk]# emcc -v
Traceback (most recent call last):
File "/root/emsdk/emscripten/1.38.28/emcc.py", line 41, in <module>
from tools import shared, system_libs, client_mods, js_optimizer, jsrun
File "/root/emsdk/emscripten/1.38.28/tools/system_libs.py", line 676
system_libs_map = {l.shortname: l for l in system_libs}
^
SyntaxError: invalid syntax```

**Comment by sbc100** [comment]
This is python map comprehension.   What version of python are you using?

**Comment by WafflePersonThing** [comment]
> This is python map comprehension. What version of python are you using?
`[~]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.`

**Comment by sbc100** [comment]
yeah, you need at least python2.7 to run emscripten.   

Looks like you are running a very old version of red hat there (4.4?  From 2006?, or am I misreading).

Anyway I will add a check to make this more obvious for anyone else.
