### ISSUE TITLE
Way to use precompiled wasm object?

### ISSUE THREAD

**Issue by saschanaz** [emscripten-core/emscripten#8279]
It seems Node.js doesn't cache the compiled wasm binary by default (https://github.com/saschanaz/flif-wasm/issues/8, https://github.com/nodejs/node/issues/18265).

So I want to use `v8.serialize` and `v8.deserialize` to cache it myself and pass it to emscripten JavaScript wrapper. Is it possible now?

Short deserialization example: https://runkit.com/saschanaz/5c84667c6e2ea0001222a59f

**Comment by sbc100** [comment]
I'm don't know a lot about node but wouldn't it be nicer to have this caching happen transparently?  i.e. have it happen inside of node or v8?  Perhaps by intercepting calls to `new WebAssembly.Module` in some way?

**Comment by saschanaz** [comment]
@sbc100 Agree, but not an option in current versions.

**Comment by sbc100** [comment]
I guess what I'm saying is that this bug should probably be files against node.js so that it can benefit all wasm users, not just emscripten users.

**Comment by sbc100** [comment]
Oh I see you already referenced the upstream bug.  Sorry for not reading that correctly.

**Comment by saschanaz** [comment]
That bug is about deserializing the manually cached binary.

It seems the browser devs want to do it [in HTTP cache level](https://github.com/WebAssembly/host-bindings/issues/16#issuecomment-425946581) rather than to do some magic in the `Module` constructor.

**Comment by kripken** [comment]
This was implemented as an option in #9948

**Comment by saschanaz** [comment]
Specifically it's `NODE_CODE_CACHING=1` 👍
