### ISSUE TITLE
test_webgl_context_attributes flakyness

### ISSUE THREAD

**Issue by hujiajie** [emscripten-core/emscripten#8280]
For example: https://circleci.com/gh/emscripten-core/emscripten/104567?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I suspect the failure is due to [test_webgl_array_of_structs_uniform](https://github.com/emscripten-core/emscripten/blob/883905425c5cc988374f728eeccc11d5c1688c49/tests/test_browser.py#L4077). In particular, is it safe to use `REPORT_RESULT()` along with `reference=`?

**Comment by sbc100** [comment]
In that test run `test_webgl_array_of_structs_uniform` passes so I'm a little confused why you think that test is to blame.

I think are you correct that any test that uses `reference=` should not be calling `REPORT_RESULT()`.  On the other hand it seems like the only effect this might have would be to generate false positive test passes.

**Comment by hujiajie** [comment]
Maybe `test_webgl_array_of_structs_uniform` sends two results to the server: the first result `0` from `REPORT_RESULT` causes `test_webgl_array_of_structs_uniform` to pass, and `test_webgl_context_attributes` is affected by the second result `77` from `reference=`?

**Comment by kripken** [comment]
Yeah, I think you may be right, this sounds like a possible bug. I pushed [a branch](https://github.com/emscripten-core/emscripten/tree/err) now with an error thrown on excessive responses to the server, let's see what happens.

**Comment by hujiajie** [comment]
I think this specific issue has been fixed with #8405, though there might be some other flaky cases.
