### ISSUE TITLE
need electron support

### ISSUE THREAD

**Issue by mccoysc** [emscripten-core/emscripten#8285]
if run in electron,it's "BOTH"  web env and node env.
maybe add this support?

**Comment by mccoysc** [comment]
@kripken

**Comment by curiousdannii** [comment]
Can you give more detail about what is not working?

**Comment by ericmandel** [comment]
Please have a look at this new PR https://github.com/emscripten-core/emscripten/pull/8594 and feel free to join the discussion.

The aim of the PR is to make it possible to mount the local file system in a Node-enabled web page within Electron. Do you have other Emscripten issues within Electron?
