### ISSUE TITLE
WebAssembly + pthreads + memory growth

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8287]
There are some challenges with implementing that combination of features. The spec has added some significant capabilities that help, in particular, when growth happens the wasm memory remains valid, while it's `.buffer` property changes, and the views on the previous buffer remain alive but on the previous size. This is almost enough for Emscripten's JavaScript glue to work, except for the case where another thread grows memory, allocates something past the previous size of memory, and you need to read that,
```
function someJSGlueFunction(ptr1) {
  var memorySize = HEAP8.length;
  var ptr2 = HEAP32[ptr1 >> 2] | 0;
  // ptr2 may be larger than memorySize if another thread grew memory meanwhile!
  return HEAP32[ptr2 >> 2] | 0; // may return 0 instead of the valid value, if past memorySize!
}
```
There is no simple solution here. Some options:

1. Do our best to work around this. In particular, we can check around every load and store whether the size of memory changed, and if so, update all our views. That would significantly increase code size, and make things much slower, since we'd need to do a (sequentially consistent) atomic operation. (We could try to only checks at "reasonable" places - say, where new pointers arrive - but it would mean carefully auditing all our JS glue, and there would be risks for user-written code.) Alternatively we could call into wasm to do every load and store, which would also add significant overhead.
2. Say that pthreads + memory growth is not supported for now, and wait for a future time when we don't need JS glue like that - when wasm can access DOM APIs directly, we can make threads contain only wasm. This would be a very different model than we have now, but it would be a cleaner and simpler one. 
3. Propose new things in the spec. If we had `wasmMemory.loadInt32` etc., for example, then VMs might efficiently implement wasm-style loads and stores from JS. Equivalently, if we could have a `SharedArrayView`, which unlike a normal typed array view could change size, that would also work.

**Comment by sbc100** [comment]
Is this problem limited to WebAssembly or should the title be just "pthreads + memory growth"?

**Comment by brion** [comment]
For library type cases where memory usage depends on input data, I think memory growth is essential. With ogv.js memory usage in the codec depends on input resolution and number of buffered frames, and it's hard to predict an appropriate fixed memory limit that's not either too small for high resolution or wastes memory for low resolution.

From the perspective of interoperating with JS, I like the idea of SharedArrayViews that can change length, since that should be a simple change to how I copy buffers in and out of the heap. But I don't know how tricky that is in terms of other spec updates to accept the new view types as buffer providers. (Maybe none, if they Just Work as buffer providers?)

**Comment by kripken** [comment]
> Is this problem limited to WebAssembly or should the title be just "pthreads + memory growth"?

A lot is shared, but the details are wasm-specific, like with asm.js you'd also need to postMessage the new SharedArrayBuffer to the workers, which is even harder. I'd guess we wouldn't want to even try to get the non-wasm case working here.

**Comment by sbc100** [comment]
OK, I was thinking the title implied that non-WebAssembly was working with pthreads+growth, which is doesn't. No problem.

**Comment by VirtualTim** [comment]
@kripken is this still an issue?
I was going to take a quick look at #9190, but it might be pointless if this hasn't changed.

**Comment by kripken** [comment]
@VirtualTim this can be closed, thanks. We do support wasm + pthreads + growth (with some downsides in JS speed due to wasm spec limitations, but hopefully most codebases wouldn't notice).
