### ISSUE TITLE
return int64 value

### ISSUE THREAD

**Issue by mccoysc** [emscripten-core/emscripten#8297]
uint64_t xxx(){
    uint64_t x=1;
    return x;
}

after comiled,the return value would only the low-32bits data,how can i get the whole 64 bits data?

**Comment by mccoysc** [comment]
i found in the compiled js file that the high-32bits data is set to be a global variable.
but how can i export the function "getTempRet0"?

**Comment by kripken** [comment]
Adding it to `EXPORTED_FUNCTIONS` should work.
