### ISSUE TITLE
question about source map Sources

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#8304]
The start of my source map says:

```
{"version":3,"sources":["D","F"]
```
Where does it get D and F from?  The browser (firefox) tries to find those files:
```
Error while fetching an original source: request failed with status 404
Source URL: http://localhost:8000/F
```
Which dont exist.  Command line for building the wasm is:
```
D:\GitHub\corert>"D:\GitHub\emsdk\emscripten\1.38.13\emcc.bat" "D:\GitHub\corert\tests\src\Simple\HelloWasm\obj\Debug\wasm\native\HelloWasm.bc" -o "D:\GitHub\corert\tests\src\Simple\HelloWasm\bin\Debug\wasm\native\HelloWasm.html" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s DISABLE_EXCEPTION_CATCHING=0 --emrun  "D:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libPortableRuntime.bc" "D:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libbootstrappercpp.bc" "D:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libSystem.Private.CoreLib.Native.bc"  -g4 --source-map-base http://localhost:8000/
```

Thanks

**Comment by yowl** [comment]
I wonder, could they be the drive letters and the rest of the path is lost?

**Comment by kripken** [comment]
That does look wrong. Here's what hello world looks like for me, from running `./emcc tests/hello_world.c -g4`:
```
{"version":3,"sources":["tests/hello_world.c"],"names":[],"mappings":"m+BAUA,YACA"}
```
Yeah, could be some windows-specific issue with paths perhaps.

**Comment by yowl** [comment]
`-s WASM=0` looks fine.  Maybe I'm just confused about what should or shouldn't work regards source maps and wasm, it does seem a bit confusing where debugging support is at.  To be fair emscripten docs say `WebAssembly doesn’t have source maps support yet` so maybe I'm just chasing a rainbow. Will try a later version.

**Comment by yowl** [comment]
`1.38.29` is the same, I guess as `-s WASM=1` is the default that must be what you are getting in your example so could be a windows issue as you suggest.
