### ISSUE TITLE
wasm-ld: machine type must be wasm32

### ISSUE THREAD

**Issue by alshamma** [emscripten-core/emscripten#8321]
I'm trying to use the LLVM WebAssembly backend with LLVM 9.0 on Mac per https://emscripten.org/docs/compiling/WebAssembly.html#llvm-webassembly-backend.

During the link stage I get the error `machine type must be wasm32` from wasm-ld. 

By adding output to https://github.com/llvm-mirror/lld/blob/master/wasm/InputFiles.cpp, in `BitcodeFile::parse()`, it appears `T.getArch()` is 0. The check fails because it should be 46, the enum for wasm32.

**Comment by sbc100** [comment]
It looks like you are trying to pass bitcode files to the linker that were not produced with wasm32 target.  Which object file is the problem?  How did you create this file?

**Comment by alshamma** [comment]
A problem is that `ccache --clear-cache` was not sufficient. I needed to use `ccache --clear`. Thus, I believe wasm-ld was failing because it was trying to use the old .obj files.
