### ISSUE TITLE
Error while updating Emscripten SDK on windows 10

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [emscripten-core/emscripten#8323]
Good greetings to everyone.
Previously i've installed  version 1.38.11 of the Emscripten SDK on my device which runs Windows 10 , `emcc -v` outputs the following on my console:

> emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.11
> clang version 6.0.1  (emscripten 1.38.11 : 1.38.11)
> Target: x86_64-pc-windows-msvc
> Thread model: posix
> InstalledDir: e:\emsdk\clang\e1.38.11_64bit
> INFO:root:(Emscripten: Running sanity checks)

However, i'm seeking to update the SDK to the latest version, so i followed the instructions on https://emscripten.org/docs/getting_started/downloads.html#updating-the-sdk

But when i run `emsdk update`  i get the following output:

> Traceback (most recent call last):
>   File "E:\emsdk\\emsdk", line 2438, in <module>
>     sys.exit(main())
>   File "E:\emsdk\\emsdk", line 2208, in main
>     load_sdk_manifest()
>   File "E:\emsdk\\emsdk", line 1841, in load_sdk_manifest
>     if '%tag%' in sdk.version: expand_category_param('%tag%', emscripten_tags, sdk, is_sdk=True)
>   File "E:\emsdk\\emsdk", line 1802, in expand_category_param
>     passes = passes_filters(param, ver, t2.version_filter)
>   File "E:\emsdk\\emsdk", line 1778, in passes_filters
>     if v[0] == param and not cmp_version(ver, v[1], v[2]):
>   File "E:\emsdk\\emsdk", line 1768, in cmp_version
>     if cmp_operand == '<=': return version_key(ver) <= version_key(reference)
>   File "E:\emsdk\\emsdk", line 1570, in version_key
>     return list(map(int, re.split('[._-]', ver)))
> ValueError: invalid literal for int() with base 10: '<<<<<<< HEAD'

I tried using `git pull` then `emsdk update` , but still no change.
From what the output says , it seems like a python error , but at this point i'm really afraid to touch anything.
How does the solution looks like ?
Thanks in advance

**Comment by VirtualTim** [comment]
Try `./emsdk update-tags` then `./emsdk install ` then `source ./emsdk_env.sh`.
Personally I've switched over to using Docker though.

**Comment by Eyad-Mohammed-Osama** [comment]
@VirtualTim Thanks for your reply
All of the commands you mentioned didn't work for me.
I'm still getting the exact same error message as above.

**Comment by cggallant** [comment]
Which version of python do you have installed? `python -V`

You'll need 2.7.12 or higher

**Comment by Eyad-Mohammed-Osama** [comment]
@cggallant i'm running python 3.7.0

**Comment by sbc100** [comment]
Looks like you have some kind of git merge conflict in a manifest file.

What does `git status` say?

**Comment by Eyad-Mohammed-Osama** [comment]
@sbc100 

> On branch master
> Your branch is ahead of 'origin/master' by 4 commits.
>  (use "git push" to publish your local commits)
> 
> Untracked files:
>   (use "git add &lt;file&gt;..." to include in what will be committed)
> 
>         emscripten-tags.txt
> 
> nothing added to commit but untracked files present (use "git add" to track)

**Comment by sbc100** [comment]
Try removing that file and running the command again?

**Comment by Eyad-Mohammed-Osama** [comment]
@sbc100 

> On branch master
> Your branch is ahead of 'origin/master' by 4 commits.
>   (use "git push" to publish your local commits)
> 
> nothing to commit, working tree clean

**Comment by sbc100** [comment]
I'm curious how are you ahead of origin/master by 4 commits?  Are you working emsdk stuff?

Why is emscripten-tags.txt untracked?  Its been part of the repo since 2015.

**Comment by sbc100** [comment]
Try `emsdk update` again.   Amd `./emsdk update-tags`
