### ISSUE TITLE
emscripten-site repo is still under kripken org.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#8332]
We should move it to the emscripten org.

**Comment by kripken** [comment]
Hmm, links like `http://kripken.github.io/emscripten-site/` will break, I worry - unless github forwards github pages like it does repos? The [docs](https://help.github.com/en/articles/transferring-a-repository) suggest it does not,

> However, we don't redirect GitHub Pages associated with the repository.

Given that, I'm unsure if this is worth it, as it's it almost entirely invisible which github repo is being used (since we properly set up emscripten.org).

**Comment by sbc100** [comment]
Its invisible to the reader of the docs, but as someone who might want to update them its quite confusing to have to do a pull request against kripken in order to update those pages.

Actually I tried and failed to figure out how that process works.  Is it manual?

How about if we continue to mirror the content to the kripken repo to prevent old links from breaking?  (Or even better include redirects in the mirroring process?)

(Just out of interest modern links should be to "https://emscripten.org/" right?)

**Comment by kripken** [comment]
Ah, no, there should never be PRs to that repo. It's literally just for hosting the site. PRs go to `site/` under the main emscripten repo here, that's where the sources are.

The process for updating that is basically, I run make html, copy the files to my checkout of the site repo, and push it to gh-pages.

Yes, links can now start with `emscripten.org/`

**Comment by sbc100** [comment]
Do what do you think of this idea:

1) Create a script to push that docs live (the process you currently go though manually)
2) Have it push both to `emscripten/emscripten-site` and also to `kripken/emscripten-site`.
3) Have emscripten.org start pointing to the gh-pages for `emscripten/emscripten-site`.

In the fullness of time we might eventually stop mirroring to `http://kripken.github.io/emscripten-site/` but for now its just to keep the old links working.

That way the live site lives alongside the site sources.

Out of interest why not just use the gh-pages branch of the main repo?  (Why have a separate -site repo?)

**Comment by kripken** [comment]
Much of a script to push the docs live would be messing around with local directories, though? The literal commands I run are
```
cd site/
make html
cp -R build/html/* [the repo for the site]
cd [the repo for the site]
git commit -a -m "update" ; git push
```

I'm not opposed to mirroring like that, but I don't think I see the benefit of this extra effort?

I agree we should document this stuff better, I opened https://github.com/emscripten-core/emscripten/pull/8358 for that now.

I think I split out the site repo from the main one for convenience - e.g. if the site repo is just a branch under the current repo, it must be in literally the same location, or else it can be awkward to move stuff around (if you are in the main branch, and you copy the output files to path/to/site, where path/to/site exists in the gh-pages branch, you can't switch branches to it without git erroring on you).

**Comment by sbc100** [comment]
I'd still like to see this move if we can

**Comment by kripken** [comment]
I actually don't know what would happen if we transferred it. Looking in the domain provider, I see nothing specific to being under `kripken/`. So I am guessing github sites does all the magic? And I don't know how that would handle a site transfer. It seems kind of risky and for little benefit IMO.

**Comment by curiousdannii** [comment]
It should probably just work. Github never had any way to know that your username related to the person who owned the domain name. It just relies on the CNAME file being there.

**Comment by kripken** [comment]
Ok, thanks @curiousdannii Let's just try this then. If it breaks we can try to revert it (I worry in the worst case we'll need to set it all up from scratch, but hopefully it won't come to that...).

**Comment by sbc100** [comment]
I would actually quite like to pursue the option of having the site checked in under this repo.  I think I had a bug open for this somewhere but I can't find it now. 

@kripken had argued that it would take up a lot of space in the checkout, but given that we are movign towards shipping just the parts of emscripten that our end users need I don't think its a huge deal.  The advantage of this appouch would that we could automatically check the generated docs match the input docs on each commit.

Move emscripten-site to the WebAssembly org would be a welcome intermediate step of cource, and worth doing even if this large plan never happens.

**Comment by kripken** [comment]
Reading the github docs meanwhile, they do *not* redirect URLs. That means that old URLs will fail. We have quite a lot of those on our wiki here, and there are a few in the emscripten repo. There are likely many others in the wild. That makes me think this isn't worth doing given the benefit is just cleanliness.
