### ISSUE TITLE
slash before binaries

### ISSUE THREAD

**Issue by DanielRuf** [emscripten-core/emscripten#8333]
I am currently running emscripten on Ubuntu Xenial (Travis CI) and `./emmake make` does not work but `emmake make`.

Is this wrong in the docs?
If so I can provide a PR.

**Comment by sbc100** [comment]
Which docs are your referring too?

The slash (or some path component) is needed if emmake is not in your PATH.

I support  `/path/to/emmake` would make more sense if the Makefile is not in the same directory as emmake itself.

**Comment by DanielRuf** [comment]
I mean https://emscripten.org/docs/compiling/Building-Projects.html for example.

**Comment by sbc100** [comment]
Sure, the "./" in that case doesn't make much sense..

**Comment by sbc100** [comment]
PR welcome.
