### ISSUE TITLE
Compiler Crash with mappedGlobals.find(name) != mappedGlobals.end()

### ISSUE THREAD

**Issue by theparitt** [emscripten-core/emscripten#8352]
I have a similar problem with this issue https://github.com/emscripten-core/emscripten/issues/5383

When I compiled the code link with an external library and -s ASYNCIFY=1. The compiler crashes. However when I remove ASYNCIFY everything is alright. ( by the way, I really need ASYNCIFY ).   I read the comment from atrosinenko about adding line

When I manually added the lines

  var _setjmpTable = 0;
  var _setjmpTableSize = 0;

But I do not understand how to fix the problem. Could anyone help me pkease

**Comment by danilw** [comment]
same here

**Comment by kripken** [comment]
Is there a testcase that shows this issue currently? I think it only happened on fastcomp, which is being removed soon anyhow, and things should all work in upstream which replaced it.

If that's not the case please reopen or comment.
