### ISSUE TITLE
webgl api needed

### ISSUE THREAD

**Issue by mccoysc** [emscripten-core/emscripten#8370]
can add any webgl api that can be used in c/c++?
and also need some general GPU compute APIs,like gpu.js,CUDA,OpenCL and so on.
for CUDA/OpenCL are all need install some GPU-related plugins(drivers,librarys and so on ,but webgl not).

**Comment by mccoysc** [comment]
@kripken

**Comment by kripken** [comment]
If it can be implemented in WebGL or another Web API, then yes.

See https://emscripten.org/docs/porting/multimedia_and_graphics/OpenGL-support.html - quite a lot is already supported. WebGPU will eventually allow more things than WebGL can.

**Comment by mccoysc** [comment]
@kripken
maybe a cuda-like general computing frame needed,not only the webgl api

**Comment by mccoysc** [comment]
just like gpu.js
