### ISSUE TITLE
 onRuntimeInitialized called before the module's main function

### ISSUE THREAD

**Issue by cggallant** [emscripten-core/emscripten#8371]
I've set up a WebAssembly module where the `main` function sets up some variables at startup.

I then implemented the Emscripten Module object's `onRuntimeInitialized` function and call into the WebAssembly module for the initial values but they're not set.

I've placed a `printf` statement in the `main` function and a `console.log` call in the `onRuntimeInitialized` function. The onRuntimeInitialized function outputs to the console first.

If I put a `setTimeout` in the onRuntimeInitialized function of even 1 millisecond then the main method executes first and I get the expected values when I call into the WebAssembly module.

I've tested this in both Firefox and Chrome on Windows 10 and I get the same results.

Looking at the code in the Emscripten generated JS, the `doRun` function calls onRuntimeInitialized before it calls the main method. I would expect the main method to be called first.

I could always implement postRun but, from the documentation, onRuntimeInitialized appears to be the function to implement.

**Comment by sbc100** [comment]
I believe this is WAI.   `onRuntimeInitialized` is called after static constructors. 

It sounds like `postRun` is what you want, or you might want to move your startup code into a separate function that you can either call yourself (from `onRuntimeInitialized`) or perhaps even put your code in a static initializer `__attribute__((constructor))`.

Perhaps the documentation needs to be clearer.  Which documentation led you believe the main would be called before `onRuntimeInitialized`?

**Comment by fugelen** [comment]
So if we cwrap and expose our methods to javascript in main(), what is the recommended way of telling the web page that the methods are ready to be called after that?

**Comment by embeddedt** [comment]
> what is the recommended way of telling the web page that the methods are ready to be called after that?

In the case where I use `cwrap`, I usually avoid having a `main` function, and run `cwrap` from JavaScript before I call my `main` equivalent.

That being said, in your case, I would suggest calling a JavaScript function from C, and then whenever that function is called you know that your methods can be used.

**Comment by sbc100** [comment]
You can use `addOnPostRun`  (or `Module['postRun']`) to get a callback after main has run.
