### ISSUE TITLE
Error parsing lkgr.json! [Errno 2] No such file or directory: '/mnt/c/Users/xxx/Desktop/tmpCode/emsdk/upstream/lkgr.json

### ISSUE THREAD

**Issue by mccoysc** [emscripten-core/emscripten#8384]
./emsdk install latest
Error parsing lkgr.json! [Errno 2] No such file or directory: '/mnt/c/Users/xxx/Desktop/tmpCode/emsdk/upstream/lkgr.json

why?
@kripken

**Comment by kripken** [comment]
Perhaps `./emsdk update-tags` or `update`? I think those update the lkgr file.
