### ISSUE TITLE
Global Functions and WebIDL binding

### ISSUE THREAD

**Issue by prestomation** [emscripten-core/emscripten#8390]
I'm trying to build a JS->C++ bridge for a large, existing C++ code base.
The code base already builds with emscripten and is already used by others in WASM. What I am doing that is new is exposing the library to javascript(the others use it from C++ that is also compiled to WASM).

This library uses C++ classes and a large set of global functions. 

It seems I cannot model the global functions using the webidl-binder. **Is it possible to model global functions using webidl-binder and I've just missed it?**

That aside, I've modeled some of the classes using Webidl-binding and modeled the global functions using embind. But when I call a global function(modeled using embind) that uses a class instance(modeled by webidl) I get an `UnboundTypeError`.

Should I expect mixing webidl and embind to work?

Thanks!

**Comment by kripken** [comment]
I think global functions are not yet supported in the webidl binder. Main focus has been on mirroring classes to JS. But you can create a class for the global stuff, and a singleton of it, etc.

Webidl binder and embind don't have any integration code, they are not aware of each other.

**Comment by prestomation** [comment]
Thanks Kripken. I'm still evaluating our options for our usecase, but I think embind is preferred(as we can 'graft' our own functions onto existing classes to address some of the limitations)

Thank you for the incredible toolset!
