### ISSUE TITLE
dynamic_cast fails across modules for dynamic linking

### ISSUE THREAD

**Issue by awtcode** [emscripten-core/emscripten#8392]
@kripken and @sbc100 , I have created a new issue for this problem as I believe the root cause is not about pointer inequality. The issue here is that the pointer to the type info is duplicated and since dynamic_cast relies on pointer comparison, the dynamic_cast fails. 

https://github.com/emscripten-core/emscripten/blob/fc8874437ce7cbeb56bc8536a817273c3ff868f1/system/lib/libcxxabi/src/private_typeinfo.cpp#L78

The problem can be reproduced when we pass a derived pointer to a function in another module. The dynamic_cast fails in the other module.

main.cpp
`EMSCRIPTEN_KEEPALIVE extern "C"
void mainy(base * arg) {
derived * temp = dynamic_cast < derived * > (arg);
printf("temp:%p\n", temp);
}

extern "C" void sidey(base* arg);

int main() {
derived* temp = new derived();
printf("main: temp:%p\n", temp);
sidey(temp);
return 0;
}`

side.cpp
`EMSCRIPTEN_KEEPALIVE extern "C"
void sidey(base* arg) {
derived * temp1 = dynamic_cast < derived * > (arg);
printf("sidey: arg:%p temp1:%p\n", arg, temp1);

base* temp = new derived();
mainy(temp);
}`

**Comment by sbc100** [comment]
Thanks.  You are correct in your diagnosis I believe.  However I already opened an issue and added a test for this.  See #8376 and #8377.

**Comment by sbc100** [comment]
The function pointer equality issue is a separate one that also has an issue and a tested too: #8330 and #8268

**Comment by awtcode** [comment]
Thanks for the update @sbc100 :)
