### ISSUE TITLE
RangeError: bad Table initial size

### ISSUE THREAD

**Issue by yowl** [emscripten-core/emscripten#8393]
I'm trying a large llvm (the text respresentation is about 1GB) and after a long time, I don't know exactly, the wasm was produced (I think the process went up to around 9GB of memory in task manager) but when running it produces the message above: `RangeError: bad Table initial size`.  What does that mean?

**Comment by kripken** [comment]
Running it in another browser, or in the binaryen and wabt tools, might give a clearer error.

One possibility is the table is too large for the VM (there might be a hardcoded limit).

**Comment by yowl** [comment]
Yes, Chrome gives a bit more:
```
Uncaught RangeError: WebAssembly.Module(): Property 'initial': value 13944832 is above the upper bound 10000000
    at Object.Module.asm (HelloWasm.js:1699)
    at HelloWasm.js:8566
```

**Comment by sbc100** [comment]
You might want to try the llvm backend as opposed to fastcomp.

IIRC fastcomp can end up using a lot more table space than it needs to depending on the various options such EMULATED_FUNCTION_POINTERS, etc.

What flags are you passing the `emcc` at link time?

Alon I'm I rememebering correctly that asm2wasm can use a lot of table space in some configurations.

13944832 certainly seems rather high.   In theory there should be at most one table entry for each function in your program (less if you don't call those functions indirectly).

**Comment by yowl** [comment]
That does seem high considering:
```
$ grep "^define" UnoStandardRefTest.Wasm.txt | wc -l
140154
```

**Comment by yowl** [comment]
I believe this was the command I used 
```
"D:\GitHub\emsdk\emscripten\1.38.29\emcc.bat" "D:\GitHub\UnoStandardRefTest\UnoStandardRefTest\UnoStandardRefTest.Wasm\bin\Debug\netstandard2.0\UnoStandardRefTest.Wasm.bc" -o "D:\GitHub\UnoStandardRefTest\UnoStandardRefTest\UnoStandardRefTest.Wasm\bin\Debug\netstandard2.0\HelloWasm.html" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 --emrun  "D:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libPortableRuntime.bc" "D:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libbootstrappercpp.bc" "D:\GitHub\corert\tests\\..\bin\WebAssembly.wasm.Debug/sdk/libSystem.Private.CoreLib.Native.bc"  -g3
```

**Comment by sbc100** [comment]
On Thu, Apr 4, 2019 at 12:22 PM yowl <notifications@github.com> wrote:

> That does seem high considering:
>
> $ grep "^define" UnoStandardRefTest.Wasm.txt | wc -l
> 140154
>
>
What is that text file?   I'm not sure why define would be the number of
table elements.

You should be able to use wasm-objdump or wasm2wat to see the table
elements in the wasm file.   You can also try `wasm-opt --metrics` from the
binaryen project.

**Comment by yowl** [comment]
Thats the llvm textual dump from
```
LLVM.PrintModuleToFile(Module, Path.ChangeExtension(_objectFilePath, ".txt"), out string unused2)
``` 
I believe thats pulling out all the functions e.g.
```
define void @"S_P_CoreLib_System_Array_1<UInt64>__set_Item"(i8*, i32, i64) {
define i64 @"S_P_CoreLib_System_Array_1<UInt64>__get_Item"(i8*, i32) {
define i1 @"S_P_CoreLib_System_Array_1<UInt64>__Remove"(i8*, i64) {
```
I'll try the other tools and the llvm backend.

**Comment by yowl** [comment]
wasm-opt:
```
ARYEN_ROOT/bin/wasm-opt HelloWasm.wasm --metrics
total
 [funcs]        : 141831
 [imports]      : 432
 [memory-data]  : 12309511
 [table-data]   : 13944832
 [total]        : 31746171
 [vars]         : 6413597
 binary         : 4178908
 block          : 385594
 break          : 46337
 call           : 744216
 call_indirect  : 66321
 const          : 4806094
 drop           : 5656
 global.get     : 371022
 global.set     : 197695
 host           : 1
 if             : 231577
 load           : 1931436
 local.get      : 10489625
 local.set      : 6473161
 loop           : 10190
 return         : 208492
 store          : 1526163
 switch         : 3109
 unary          : 70574
```

**Comment by sbc100** [comment]
Certainly seems strange.   With only 141k functions its not clear why the
compiler would generate 14M table entries.  Alon, any ideas?

**Comment by yowl** [comment]
I tried llvm 8.0.0 , but seems a bit tricky.  My llvm is built with LLVMSharp 5, so I have 2 problems, the first is easy, I have one instance of `thread_local` which I can `sed` out.  The second I'm not sure, `llc` fails with 
```
/tmp/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/llvm-as: UNoTls.txt:12900797:165: error: invalid field 'variables'
!5960 = distinct !DISubprogram(name: "Flt2LngOvf", scope: null, file: !1, line: 209, isLocal: true, isDefinition: true, scopeLine: 1, isOptimized: false, unit: !0, variables: !5956)
```
Not empscripten problems, but just in case there's an easy sed'able fix.

**Comment by sbc100** [comment]
thread_local should be find as long as you don't build with +matomic
or -thread-model=posix or anything like that.    It will just get
lowered away by the backend to regular global.

Is the program you are trying to build using multi-threading?

What is generating the UNoTls.txt file?  Is that LLVMSharp (I don't
know that that is)?  Whatever it is it will need to be able to spit
out LLVM 8.0 compatible bitcode if you want this to work.

**Comment by yowl** [comment]
I'm not using multithreading (this is the corert dotnet -> wasm project https://github.com/dotnet/corert/blob/master/Documentation/how-to-build-WebAssembly.md) , but the compiler encounters this one instance of a c++ thread static which it emits as `thread_local`, its not important for now as there's no threads created.  LLVMSharp (https://github.com/Microsoft/LLVMSharp) are some dotnet bindings over LLVM, but version 5.   So the corert compiler builds the LLVM byte code and at the same time dumps the LLVM text, which I passed through `sed s/thread_local// < UnoStandardRefTest.Wasm.txt > UNoTls.txt` as I was hitting 
```
/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/llc UnoStandardRefTest.Wasm.bc -mtriple wasm32-unknown-unknown
LLVM ERROR: Cannot select: 0x8cc19900: i32 = GlobalTLSAddress<i8** @t_pShadowStackTop> 0
In function: Flt2LngOvf
```
Which now I paste it I realise is the same function so maybe I'm maybe my `sed` has screwed something up.  The fastcomp table size remains a question, but I'll see if I can build for LLVM 8 by creating a local build of LLVMSharp.  Thanks for the help.

**Comment by kripken** [comment]
Yeah, fastcomp may blow up the table in some cases, because asm.js has one table per type, and they need to be a power of 2 size, etc. This could be that. If so, using `-s EMULATED_FUNCTION_POINTERS=1` may help (avoid strict asm.js function tables), but yeah, the real solution is the LLVM wasm backend.

**Comment by yowl** [comment]
Ok, thanks.  I'll work to get upgraded to llvm 8.0.0 and use the LLVM wasm backend.
