### ISSUE TITLE
wasmBinary is not synchronous

### ISSUE THREAD

**Issue by acthp** [emscripten-core/emscripten#8395]
https://emscripten.org/docs/compiling/WebAssembly.html?highlight=wasmbinary

> If you can fetch the binary yourself, you can set Module['wasmBinary'], and that will be used synchronously.

It won't. It will instead be instantiated as a Promise, which will be queued for later async resolution.

There doesn't appear to be a way to initialize emscripten synchronously, which complicates use with bundlers.

**Comment by kripken** [comment]
Yeah, if async compilation is on, it will be async even if `Module['wasmBinary']` is provided. You can disable async compilation though (` -s BINARYEN_ASYNC_COMPILATION=0`), does that help?
