### ISSUE TITLE
Namespace support is required to build ICU. 

### ISSUE THREAD

**Issue by seuliang** [emscripten-core/emscripten#8401]
1 warning generated.
configure: error: Namespace support is required to build ICU.
make[5]: *** [icu-build/Makefile] Error 1
make[5]: Target 'rebuild' not remade because of errors.
make[4]: *** [../../libs/icu/include/unicode/uversion.h] Error 2

anyono has ideal about solving this?

**Comment by vadimkantorov** [comment]
Also stumbled on this while building TexLive/icu in Github Actions environment. Locally everything works. Trying to figure it out

**Comment by vadimkantorov** [comment]
```
busytex_emcc_wrapper.py calling ['em++', '-Oz', '-s', 'ERROR_ON_UNDEFINED_SYMBOLS=0', '-o', 'conftest', '-O2', '-std=c++11', '-ffunction-sections', '-fdata-sections', '-Wl,--gc-sections', 'conftest.cpp', '-lpthread', '-lm']
busytex_emcc_wrapper.py return_code 0
configure:6823: $? = 0
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "ICU"
| #define PACKAGE_TARNAME "International Components for Unicode"
| #define PACKAGE_VERSION "65.1"
| #define PACKAGE_STRING "ICU 65.1"
| #define PACKAGE_BUGREPORT "http://icu-project.org/bugs"
| #define PACKAGE_URL "http://icu-project.org"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define SIZEOF_VOID_P 4
| #define HAVE_LIBM 1
| #define HAVE_ELF_H 1
| #define HAVE_GETTIMEOFDAY 1
| #define HAVE_LIBPTHREAD 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_DIRENT_H 1
| /* end confdefs.h.  */
| namespace x_version {void f(){}}
|     namespace x = x_version;
|     using namespace x_version;
|
| int
| main ()
| {
| f();
|   ;
|   return 0;
| }
configure:6832: result: no
configure:6836: error: Namespace support is required to build ICU.
```

**Comment by vadimkantorov** [comment]
My wrapper returns code 0, so not sure why the namespace check fails

**Comment by vadimkantorov** [comment]
Maybe it's that Github Actions ubuntu-20.04 uses a different host compiler (?)

I can see the following in my configure log:
```
InstalledDir: /home/runner/work/_temp/995214ea-5c6e-42e4-99f3-f3b007dae6f4/emsdk-master/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
```

**Comment by sbc100** [comment]
Emscripten/emsdk should no depend in any way on the system compiler.. the clang binaries are embedded in emsdk itself.

**Comment by vadimkantorov** [comment]
Hmm, makes sense. I should be able to prepare a "Github repo+actions" repro, but it looks extremely fishy (and still performs the namespace check even if I override it in CONFIG_SITE).

**Comment by F1lou** [comment]
Although this thread is already older than a year, I'd like to report, that linking libiconv helped me in compiling the sources.
-> I added libiconv-dev to my build dependencies (or just install it)
-> then I added "export LDFLAGS="$LDFLAGS -liconv"

-> then icu compiled fine.

**Comment by iliakan** [comment]
@F1lou Did you compile libiconv into WASM separately?

I also need to add libiconv to the build, but it's not ported.

**Comment by sbc100** [comment]
Emscripten does comes with its own port of ICU in case that is useful.  To use it build wit `-sUSE_ICU`

**Comment by bugparty** [comment]
remove clang will fix that error, must be clang related
