### ISSUE TITLE
Make the output JS file smaller

### ISSUE THREAD

**Issue by photopea** [emscripten-core/emscripten#8409]
We are using Emscripten to convert a C library into a 700 kB WASM and 138 kB JS file. As our website is accessed about 100 000 times a day, and each visitor needs to load the JS and WASM into his browser, it would be great to save every byte we can (even when the content is zipped during the transfer).

I have looked into [our current JS](https://pastebin.com/eQJSbBJ6). At line 4598, you start to define variable names, that are never used afer defining them:

    var _hb_aat_layout_feature_type_get_name_id = 
    Module["_hb_aat_layout_feature_type_get_name_id"] = function() {
        return Module["asm"]["D"].apply(null, arguments)
    };

Could you remove the variable definition and keep only the assignment? 

    Module["_hb_aat_layout_feature_type_get_name_id"] = function() {
        return Module["asm"]["D"].apply(null, arguments)
    };

It looks like you are trying to map JS function names to WASM funciton names. You could crete a simple String-to-String map:

    {  "_hb_aat_layout_feature_type_get_name_id":"D", ....  }

and then, create all functions with a short for-loop. Is it possible?

**Comment by kripken** [comment]
Some of those optimizations are possible, yes - the emscripten optimizer, and closure compiler, should do them for you. You should also get whitespace minified which saves a lot. Which flags are you building the JS with? I'd recommend something like `-O3 --closure 1`

**Comment by ebraminio** [comment]
Yes, Google Closure made it much better, thanks for reminding this @kripken, feel free to close this. Thanks!
