### ISSUE TITLE
How to use compiled js file in node?

### ISSUE THREAD

**Issue by marlinilram** [emscripten-core/emscripten#8415]
I have built the example "lerp" function to lerp.js file, I want to use it in a client file. I use cmake to generate project and has added "-s --bind" flags through set_target_properties

lerp.cpp
```cpp
#include <emscripten/bind.h>

using namespace emscripten;

float lerp(float a, float b, float t) { return (1 - t) * a + t * b; }

EMSCRIPTEN_BINDINGS(my_module) { function("lerp", &lerp); }
```

client.js
```javascript
const Module = require("./lerp.js");
console.log(Module.lerp(1, 2, 3));
```

but it gives error "Module.lerp is not a function"

How do I initialize the compiled module properly in such case?

**Comment by marlinilram** [comment]
code generated by -s WASM=1 --bind can be used as in client.js

**Comment by iceydee** [comment]
@marlinilram I had the same problem, until I realised that the wasm is being loaded asynchronously so if you try to use it directly like that it's not yet available.

change client.js to this instead:
```js
const Module = require("./lerp.js");
Module.onRuntimeInitialized = () => {
  console.log(Module.lerp(1, 2, 3));
};
```
