### ISSUE TITLE
Confusion about compiling Hello-World example to WASM

### ISSUE THREAD

**Issue by TedaLIEz** [emscripten-core/emscripten#8416]
From the `hello-world` example:
```
#include <iostream>

int main(int, char**) {
    std::cout << "Hello, world!\n";
    return 0;
}
```
I tried to compile it with `emcc main.cpp -s WASM=1 -o output.js`, `emcc` will give me two outputs: output.js and output.wasm

I looked through the `WebAssembly` documentation, but I didn't find much information about this generated javascript file. And I found that the `output.js` has some implementation with the standard library in C++. But I am confused, I think wasm can call the standard library function directly in browser. Is it necessary to generate extra javascript files when I compile a C++ library to wasm?

**Comment by VirtualTim** [comment]
For getting started it may be a good idea to change the output to "output.html". You can then run a simple server doing something like: `emrun --no_browser --hostname $(hostname -I) --port 80 output.html`. This will generate a sample html page and should give you a good idea of how to integrate Emscripten code.

**Comment by TedaLIEz** [comment]
@sbc100 Thanks for your comment. Besides I have another question. If I have a wasm module which imports a function(e.g, foo). To provide the `foo` implementation, it seems that I may provide the implementation in the javascript side. (Like what emscripten does I think) Can I have an alternative way to solve this? Will dynamic link help?

**Comment by sbc100** [comment]
I think the documentation here should answer your questions:
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

Specifically check out "Implement a C API in JavaScript" for how to provide JS functions to wasm .

**Comment by TedaLIEz** [comment]
Thanks. I will take a look.
