### ISSUE TITLE
relooper gives incorrect results

### ISSUE THREAD

**Issue by bkw** [emscripten-core/emscripten#842]
While trying to emscripten https://github.com/mbebenita/Broadway with the current master, I ran into issues with both google closure compiler and relooper. Disabling both makes the code work, alas slow. Without closure compiler I managed to trace the error introduced by the new relooper to one function (_DetermineNC). From there I did not get any further.

I created a gist showing the delta between a version with all functions except _DetermineNC relooped, and one with all functions relooped [here](https://gist.github.com/bkw/4749526/revisions).

Since this is a function from deep inside a video decoder and it's accessing the global HEAP objects, I find it very hard to construct a test case.

Any suggestions?

**Comment by juj** [comment]
Hey, this bug report is quite old, but looking at the Broadway repository, there have been commits to Emscripten side about 4 months ago. @bkw: I presume this issue has since been resolved?
