### ISSUE TITLE
Incorrect STACKTOP in asm side modules

### ISSUE THREAD

**Issue by rianhunter** [emscripten-core/emscripten#8433]
When emitting an ASM side module, emscripten sets `STACKTOP` in the shell:

https://github.com/emscripten-core/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/shell_sharedlib.js#L15

But this STACKTOP variable is overridden when emitting the asm variables in emscripten.py:

https://github.com/emscripten-core/emscripten/blob/4ce1300f41c9d29de08c7f65a34faaff275322d6/emscripten.py#L489

This causes the side module to corrupt memory because its `STACKTOP` is not the dynamically allocated `STACKTOP` obtained from the side module shell, and is a lower `STACKTOP` taken from considering only the globals in the side module.

My fix would be to change the condition in emscripten.py:

https://github.com/emscripten-core/emscripten/blob/4ce1300f41c9d29de08c7f65a34faaff275322d6/emscripten.py#L487

But I'm not sure if that is the correct change.

**Comment by kripken** [comment]
I think for side modules in general, not just asm.js ones, we can't know their stack location at compile time. So yes, I think the fix is to change that condition to not happen for any side module.

**Comment by rianhunter** [comment]
I came up with a set of changes that seem to be consistent with the surrounding code. The distinction wasn't side modules but "relocatable" modules. Unfortunately two tests are failing, so I'm still investigating that but if you can, let me know if I'm on the right track.
