### ISSUE TITLE
[Emterpreter] different behavior in browsers

### ISSUE THREAD

**Issue by Svichkaryov** [emscripten-core/emscripten#8439]
Hi. When compiling with Emterpreter, I noticed that with exceptions enabled (-s DISABLE_EXCEPTION_CATCHING=0) an error: 

> This error happened during an emterpreter-async operation. Was there non-emterpreted code on the stack during save (which is unallowed)? If so, you may want to adjust EMTERPRETIFY_BLACKLIST, EMTERPRETIFY_WHITELIST. 

 may appear periodically in the Firefox 65.0.1 (64-bit), but in Chrome (Version 72.0.3626.119 (Official Build) (64-bit)) always everything works fine.
Compile script:
```bash
 emcc -I../../CryptoLib/src -I../../CWrapper/hdr \
        $PATH_TO_C_WRAPPER/WrapObj.cpp \
        $PATH_TO_C_WRAPPER/Utils.cpp \
        $PATH_TO_C_WRAPPER/CryptoLibEmulator.cpp \
        $PATH_TO_C_WRAPPER/CertificateExtend.cpp \
        -o wasmModule.js --pre-js ../pre.js -s NO_EXIT_RUNTIME=1 \
        -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=0 -s SOCKET_DEBUG=1 \
        -s ASSERTIONS=1 -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 \
        -s "EMTERPRETIFY_WHITELIST=$emwhitelist" \
        -s "EXTRA_EXPORTED_RUNTIME_METHODS=['cwrap', 'ccall', 'UTF8ToString']" \
        -D __EMSCRIPTEN_DEBUG__ --emit-symbol-map --profiling-funcs \
        -L ../libCL3Client/ -llibCL3Client \
        -Wno-extra-tokens --std=c++14`
```
If at compilation remove option: -s DISABLE_EXCEPTION_CATCHING=0, Firefox starts to work normally and no longer gives the above error. Is this normal behavior?

**Comment by kripken** [comment]
It's possible the codebase is sensitive to timing somehow, that could explain both a difference between browsers and the test randomly failing on one browser.

I can't think of `DISABLE_EXCEPTION_CATCHING` affecting timing variability, except in that exceptions can make things slower.
