### ISSUE TITLE
Allow access of memory location 0

### ISSUE THREAD

**Issue by s-macke** [emscripten-core/emscripten#8440]
Usually user space programs don't have access to the first memory page. Hence writing to the memory location 0 leads to an segmentation fault. However, WebAssembly does provide linear memory starting from offset 0. Hence it is legal to write to the first byte. I use my own memory layout in a very computational critical task. When I try to compile the following code

```C
int *x = (int*)0;
void EMSCRIPTEN_KEEPALIVE foo()
{
    x[0] = 0;
}
```
the compiler exchanges the store with an call to '_llvm_trap'. I understand the behavior, but I wish a setting so that LLVM doesn't exchange the code with a trap. I know, that I can use side modules, but for speed considerations, I don't want to use this option.

**Comment by VirtualTim** [comment]
Out of curiosity, do you still see this when compiling with `-s BINARYEN_IGNORE_IMPLICIT_TRAPS=1`?

**Comment by s-macke** [comment]
Yes, I tried the compile option already.
```sh
emcc -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 -s TOTAL_MEMORY=32MB -s BINARYEN_IGNORE_IMPLICIT_TRAPS=1 -Os test.c -o test.o
```
The compiled code is
```wat
(module
  (type (;0;) (func))
  (type (;1;) (func (param i32 i32) (result i32)))
  (import "env" "_llvm_trap" (func (;0;) (type 0)))
  (func (;1;) (type 1) (param i32 i32) (result i32)
    call 0
    i32.const 0)
  (export "_foo" (func 1)))
```

**Comment by kripken** [comment]
I believe the fastcomp backend will do that, yeah. We're going to migrate to the LLVM wasm backend soon anyhow though, so worth checking if this happens there as well (there's a good chance it doesn't).

**Comment by jgravelle-google** [comment]
It shouldn't: https://github.com/emscripten-core/emscripten/blob/007d839136b78a4beb5d5b8721a4a3af9d36b555/tests/test_core.py#L2092-L2097

The test in question: https://github.com/emscripten-core/emscripten/blob/007d839136b78a4beb5d5b8721a4a3af9d36b555/tests/core/test_intentional_fault.c

This is explicitly done by the JSBackend in fastcomp, but not done in upstream LLVM.

**Comment by s-macke** [comment]
Thanks, so I will close this issue and wait for the future enhancement.
