### ISSUE TITLE
Issues on the Windows 10 paltform ... filename too long.

### ISSUE THREAD

**Issue by woobagooba** [emscripten-core/emscripten#8442]
Greetings.

I am having no success to install an application which invokes Emscriptem to perform a compilation.  We are getting a WIndowsError 206 file name too long error.  Long filenames are enabled on the problem Win 10 machine. 

Best we can determine, the only way around this is to use python 3.6 or later.

What say the Emscriptem experts?

![image](https://user-images.githubusercontent.com/3648022/56158616-81419900-5f90-11e9-89d5-3aec0872a361.png)

**Comment by sbc100** [comment]
Interesting, it looks like the executable in question is the clang binary you are using.  Have you modified your LLVM path?   Can you add EMCC_DEBUG=1 to your environment so we see more tracing here?

Another reason to switch to python3 only perhaps?  #7198.

Regardless of if/when we make the switch is there any reason you can't use python to solve your immediate issue?

**Comment by woobagooba** [comment]
> Interesting, it looks like the executable in question is the clang binary you are using. Have you modified your LLVM path? Can you add EMCC_DEBUG=1 to your environment so we see more tracing here?
> 

We strictly followed the Encriptem install instructions for Windows here ... https://emscripten.org/docs/getting_started/downloads.html

> Another reason to switch to python3 only perhaps? #7198.

It seems so.  I think Python 3.6 or later is required to fix this issue.

> 
> Regardless of if/when we make the switch is there any reason you can't use python to solve your immediate issue?

I am not sure what you are asking.  We adhered to published Emscriptem installation instructions for Windows.  As one component of the ARM Mbed OS simulator ... https://github.com/janjongboom/mbed-simulator

If you are suggesting we tackle introduction of Python 3, appreciated if you could provide some guidance.

**Comment by sbc100** [comment]
Emscripten already supports (and is tested with) python3.  However, emsdk for windows by default installs python2.    Switching to python3 should be relatively simple but I don't have a windows machine handy to figure out exact instructions for you.  It probably involves installing python3 by hand and injecting into the PATH before the one that emsdk installs. 

I'm curious why you are having this issue and other windows users are not.  Any ideas why which would  not effect everyone?

**Comment by woobagooba** [comment]
> Emscripten already supports (and is tested with) python3. However, emsdk for windows by default installs python2. Switching to python3 should be relatively simple but I don't have a windows machine handy to figure out exact instructions for you. It probably involves installing python3 by hand and injecting into the PATH before the one that emsdk installs.
 
I will try that.  Maybe it is just a matter of installing Python 3 and changing the emdsk_env.bat file.

> I'm curious why you are having this issue and other windows users are not. Any ideas why which would not effect everyone?

Because I am in a hurry to get the dependent project working, and under a deadline!  Of course there is a showstopper!  ;)
