### ISSUE TITLE
Function pointers appear not to be shared across threads.

### ISSUE THREAD

**Issue by coopersimon** [emscripten-core/emscripten#8444]
The `functionPointers` variable is global, and is being instantiated on each thread. This means that when a different thread tries to call a function stored in the array (C calling a function pointer passed in through `addFunction`), added by another thread, it can't find it:

`TypeError: functionPointers[index] is not a function`

Not sure how best to deal with this. I tried sending the array when the worker was set up, but it didn't seem to like copying the javascript functions. I also couldn't find a good way of adding the function pointers list to each worker.

**Comment by VirtualTim** [comment]
From my very amateur understanding `functionPointers` should be defined like `Module['functionPointers']`, and initialised in each thread in `src/worker.js`. I think you might also have to change the datatype to a `SharedArrayBuffer` (from an `Array`).

Hope that helps?

**Comment by coopersimon** [comment]
Yeah I agree it should be stored in each module. I'll investigate using a `SharedArrayBuffer` and see if that works. That seems like it would be the best solution - then function pointers could be added and called from any worker.

There is this `addFunctionWasm` function that exists in the generated .js file, however it isn't connected to anything and the corresponding remove function doesn't do anything. I suppose there is a plan for something there.

**Comment by coopersimon** [comment]
So JavaScript functions can't be stored in a typed array, so they can't use a shared array buffer. I managed to get something working in which I check inside `jsCall_...` if the current thread is not the main one, and if so then I post a message back to the main thread with the function index to call.

**Comment by kripken** [comment]
I think this only a problem with fastcomp, as we implement things differently in the LLVM wasm backend, which we hope to switch the default to soon anyhow. So might not be worth spending much time on this - would be good to know if the same code works with the wasm backend.

**Comment by sbc100** [comment]
yes it looks like if we want this to work you'd need to proxy all the jsCall functions to the main thread.   

I'm looks like this would also not work if you tried EMULATED_FUNCTION_POINTERS=1 or EMULATED_FUNCTION_POINTERS=2 either.  I think we'd need to do work in each of these cases :(
