### ISSUE TITLE
how to export global variable and static member variables in side_module or main_module

### ISSUE THREAD

**Issue by ck7colin** [emscripten-core/emscripten#8448]
how to export global variable and static member variables in side_module or main_module.

**Comment by ck7colin** [comment]
is there something like EMSCRIPTEN_KEEPALIVE?

**Comment by kripken** [comment]
I don't think this works yet. An extern global should be exported automatically, but there is an LLVM wasm backend bug on that, https://bugs.llvm.org/show_bug.cgi?id=40364

**Comment by ck7colin** [comment]
that means I can't use global variable of main_module in side_module or use  or use static members in main_module?!!!

**Comment by sbc100** [comment]
No, it should work.  We have tests for it. e.g. `test_dylink_global_var`

When building a SIDE_MODULE *all* global symbols should be preserved by the linker and exported.  

When building the MAIN_MODULE the symbols that get exported depends on if you set MAIN_MODULE to 1 or to 2 and weather you enable `EXPORT_ALL=1`.  I would suggest building with `-s MAIN_MODULE=1` and `-s EXPORT_ALL` when you build you main module, at least just to get things running.  

At least this is my understanding based on the recent work I've been doing trying to get this stuff working with the wasm backend.

**Comment by ck7colin** [comment]
> No, it should work. We have tests for it. e.g. `test_dylink_global_var`
> 
> When building a SIDE_MODULE _all_ global symbols should be preserved by the linker and exported.
> 
> When building the MAIN_MODULE the symbols that get exported depends on if you set MAIN_MODULE to 1 or to 2 and weather you enable `EXPORT_ALL=1`. I would suggest building with `-s MAIN_MODULE=1` and `-s EXPORT_ALL` when you build you main module, at least just to get things running.
> 
> At least this is my understanding based on the recent work I've been doing trying to get this stuff working with the wasm backend.

good job!I am building the side_module and main_module both in mode 2.export side_module symbols with EMSCRIPTEN_KEEPALIVE and main_module with EXPORT_ALL=1. As a result, the side_module can't find the global variable symbol which is an extern variable in side_module and defined in main module.

**Comment by sbc100** [comment]
Does it work with SIDE_MODULE=1 and MAIN_MODULE=1?

**Comment by sbc100** [comment]
Despite the documentation it looks like 1 is the only meaningful value for SIDE_MODULE so setting it to 2 won't be any different to 1.

It sounds like you've tried attaching EMSCRIPTEN_KEEPALIVE to the global declared in the main module?  Does that not work?  If not, have you tried adding to EXPORTED_FUNCTIONS?

**Comment by ck7colin** [comment]
no, it's different from mode 2 to mode 1 just as the documemtation .  And it doesn't work to attach EMSCRIPTEN_KEEPALIVE to the global or add to EXPORTED_FUNCTIONS.

**Comment by ck7colin** [comment]
it seems that the global of main_module would be convert into the the exact  address of memory table such as `i32.add (get_global $gb) (i32.const 261736)`  , while it is a name in side_module.

**Comment by ck7colin** [comment]
finally, I don't use global variable in main module to avoid this. I had moved the global to side_module.I know that is not a good way!

**Comment by RixInGithub** [comment]
I've stumbled upon such an issue too. I'm thinking of making a function that returns your variable, if, of course, it isn't an array. If it is an array, I'd recommend moving to `malocc`ing.

**Comment by RixInGithub** [comment]
Oh nevermind, the special functions return an integer for me; you probably have to get the array from the memory buffer too then...
