### ISSUE TITLE
Make abort() throw an actual javascript Error object instead of just a string.

### ISSUE THREAD

**Issue by hugoam** [emscripten-core/emscripten#8449]
Could we consider making abort() throw an actual javascript Error object instead of just a string ?
Is there any good reason that abort() only throws a string ?

In the context of generalized error handling/logging it's really not ideal. Even though the stack/line/column standardization is currently non-existent, it's still easier for the user to handle proper Errors than a mix of sometimes Errors, sometimes simple strings.

**Comment by kripken** [comment]
Sounds good to me, a PR would be welcome.
