### ISSUE TITLE
make_fetch_worker() looks for missing functions

### ISSUE THREAD

**Issue by rianhunter** [emscripten-core/emscripten#8452]
In `emcc.py`, `make_fetch_worker()` is called when the `FETCH` and `USE_PTHREADS` settings are true. It imports some functions that may be removed due to dead code elimination when `opt` is run on the source bitcode. Is there a better way to ensure that the fetch worker functions required aren't optimized out during `opt`?

**Comment by rianhunter** [comment]
I think updating `get_safe_internalize()` with the functions in `make_fetch_worker()` may be the best approach here

**Comment by kripken** [comment]
In general, I think the fetch code needs some improvements like replacing the fetch worker with a simple thread instead. That should avoid this problem entirely, I think.

**Comment by rianhunter** [comment]
Okay, and someone else brought up that this is related to #7490. I'll close this issue and use that one to coordinate that larger change.
