### ISSUE TITLE
Embind low-level documentation contains visible comments

### ISSUE THREAD

**Issue by wingo** [emscripten-core/emscripten#8455]
The low-level documentation for embind has a lot of in-progress comments by a user HamishW (perhaps @hamishwillee ?).  They make it difficult to read the documentation; see e.g. https://emscripten.org/docs/api_reference/bind.h.html#enums.

Probably they were are not meant to render and should either be marked as comments or taken out.  FWIW to my mind none of them added any information to the document; AFAIU the documentation is correct without them.

**Comment by kripken** [comment]
Agreed, those comments are quite old and can be cleaned up and removed now.

**Comment by kripken** [comment]
Fixed by #8463
