### ISSUE TITLE
export symbols of static lib

### ISSUE THREAD

**Issue by ck7colin** [emscripten-core/emscripten#8465]
I do the the follows cmds:

1. `emcc Main.o  libxxx.a libApplicationMain.a -o ApplicationMain.o`
2. `emcc ApplicationMain.o -s WASM=1 -s NO_EXIT_RUNTIME=1 -s USE_SDL=2 -s MAIN_MODULE=1 -s EXPORT_ALL=1 -s FORCE_FILESYSTEM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=['loadWebAssemblyModule'] -lpthread -lopenal -s DISABLE_EXCEPTION_CATCHING=0 -O2 -g -s USE_WEBGL2=1 -s TOTAL_MEMORY=32*16777216 -s ALLOW_MEMORY_GROWTH=1 --preload-file assets -o ../bin/BunnyMark.js`

In the result, I can't find the symbol of the static libs  libxxx.a libApplicationMain.a .Is there any way to export them?

**Comment by ck7colin** [comment]
one way I can see is that expand the static lib

**Comment by sbc100** [comment]
I'm not sure what you are trying to do in the first line?  Are you trying to linking multiple input object into a bigger object file?  Normally you would use `-r` to do this.   Perhaps emscripten magically supports doing this without `-r`?   Is there a reason you need to do that rather than just creating an archive?

Normally if you want to force object from an archive to be includes by the linker you would want to wrape the archive in `-Wl,--whole-archive` and `-Wl,--no-whole-archive`.

**Comment by ck7colin** [comment]
> I'm not sure what you are trying to do in the first line? Are you trying to linking multiple input object into a bigger object file? Normally you would use `-r` to do this. Perhaps emscripten magically supports doing this without `-r`? Is there a reason you need to do that rather than just creating an archive?
> 
> Normally if you want to force object from an archive to be includes by the linker you would want to wrape the archive in `-Wl,--whole-archive` and `-Wl,--no-whole-archive`.

ok,thanks.is there some macro for this [https://github.com/emscripten-core/emscripten/issues/8448#issuecomment-483956629](url)? just as this.

**Comment by sbc100** [comment]
No, AFAIK, there is no way to force a symbol to be exported from .a archive without a linker flag.  This means you can't do this in the source code, only from the command line.   

By default the linker will completely ignore entire object files in archives unless it is looking for a symbol that is defined in that object.   (--whole-archive overrides this behaviour, as well as other linker flags such as -u)

**Comment by EddyTheCo** [comment]
> Normally if you want to force object from an archive to be includes by the linker you would want to wrape the archive in `-Wl,--whole-archive` and `-Wl,--no-whole-archive`.

How can I  neglect an object from an static library to be included by the linker.  
I am getting 
>wasm-ld: error: duplicate symbol:

when linking with 3rd party static libs. But one of the objects with the duplicated symbol I don need it.

**Comment by sbc100** [comment]
There is no way to that i know of to tell the linker to ignore an object within a library.  However you can remove the object from the library using `emar d libfoo.a filename.o`

**Comment by EddyTheCo** [comment]
Many Thanks, that was what I did but using  "ar dv libfoo.a filename.o". Gave me some warnings but works ok.

**Comment by sbc100** [comment]
The system version of `ar` doesn't support wasm object files so your are better of using `emar` or `llvm-ar`.
