### ISSUE TITLE
Error: x is readonly

### ISSUE THREAD

**Issue by gardspirito** [emscripten-core/emscripten#8469]
Hello. I am compiling my C++ file with following command:
`em++ src/Main.cpp -o dest/Main.js -s MODULARIZE=1 -s EXPORTED_FUNCTIONS="['_loop']" --bind -std=c++17 -s BINARYEN_ASYNC_COMPILATION=0 -s ENVIRONMENT=shell -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall','cwrap']`
When I run `Module(opts)`, there is an error:
`"__GLOBAL__sub_I_bind_cpp" is read-only`
I have fixed it by commenting the following section of `Module` code:
`
var real___GLOBAL__sub_I_bind_cpp = asm["__GLOBAL__sub_I_bind_cpp"]; asm["__GLOBAL__sub_I_bind_cpp"] = function() {
  assert(runtimeInitialized, 'you need to wait for the runtime to be ready (e.g. wait for main() to be called)');
  assert(!runtimeExited, 'the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)');
  return real___GLOBAL__sub_I_bind_cpp.apply(null, arguments);
};
...
`
It works fine now, but I am not sure that this is how it is supposed to work.

**P.S.:** I am working in an unusual environment (not simply `web` or `node`), maybe this is the source of the problem?

**Comment by kripken** [comment]
Interesting, what environment is that? Is it a different JS VM, or does it enable something like strict mode?

@VirtualTim saw something perhaps related [here](https://github.com/emscripten-core/emscripten/pull/8306#discussion_r272006611) with read-only properties, that we are still trying to understand.

**Comment by mystery-coder** [comment]
This environment does enforce strict mode.

**Comment by VirtualTim** [comment]
Yep, that sounds like the same thing I was experiencing. I'm guessing it's a strict mode thing, in my case caused by running that code in an ES6 Module.

**Comment by kripken** [comment]
Good, then the next step is to get a testcase. I tried to run that em++ command here on a hello world program, then add "use strict", but I couldn't reproduce it, so there's something more going on here.

**Comment by VirtualTim** [comment]
@mystery-coder If you still haven't got this working, compiling with `ASSERTIONS=0` should "fix" this. Obviously you won't get assertions, but better than not running at all, right?

**Comment by mystery-coder** [comment]
@VirtualTim, thanks. I'll try that.

**Comment by kripken** [comment]
I think https://github.com/emscripten-core/emscripten/pull/11048 may fix this
