### ISSUE TITLE
the diff of compile stout between module building and normal building ?

### ISSUE THREAD

**Issue by ck7colin** [emscripten-core/emscripten#8475]
compile `setbuf(stdout, 0);`  in cmd SIDE_MODULE=1, we got the wast code 
 `
(set_local $1
   (call $g$_stdout)
  )
(call $_setbuf
   (i32.load
    (get_local $1)
   )
   (i32.const 0)
  )
`
and when I call this code in MAIN_MODULE, the application would be blocked。Why？
I compile `setbuf(stdout, 0);`  normally without *_MODULE, we get the wast code`
 (call $_setbuf
   (i32.load
    (i32.const 883660)
   )
  )
`. the differents is we got the name in side_module while got the address in the normal building.
We can't use this in module buiding?

**Comment by sbc100** [comment]
I'm not sure I understand that questions, but your observation seems correct.  In the SIDE_MODULE case the address of the `stdout` global is not known at compile time and so is retrieved at runtime by calling the `g$stdout`.

The functions that start with `g$` are functoins for looking up the address of global variables at runtime.
