### ISSUE TITLE
wasm-dis: std::bad_alloc

### ISSUE THREAD

**Issue by nomeata** [emscripten-core/emscripten#8484]
Running `wasm-dis` on the attached `.wasm` file results in
```
$ wasm-dis foo.wasm 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
As for the version: This seems to be `binaryen-45`, installed through `nixpkgs`.

**Comment by kripken** [comment]
I don't see an attached file?

**Comment by nomeata** [comment]
Ouch, darn. And I don't have the file any more… I vaguely remember that `wasm2wat` complained about a section with number 12 (although WebAssembly only specifies 11 sections), maybe related to that. 

Well, sorry for the noise, I’ll reopen this if I remember how precisely I created that file.
