### ISSUE TITLE
Uncaught reference error to establishStackSpace for llvm_backend/no pthreads

### ISSUE THREAD

**Issue by StevePerry182** [emscripten-core/emscripten#8485]
This occurs when I use the llvm_backend and no pthreads.

The wasm binary js contains a call to the establishStackSpace function, but does not define the function.

The support.js file at around line 924 has this to define the function (neither variable has a non-zero value in my case):

#if WASM_BACKEND && USE_PTHREADS
// The wasm backend path does not have a way to set the stack max, so we can
// just implement this function in a trivial way
function establishStackSpace(base, max) {
  stackRestore(base);
}

**Comment by sbc100** [comment]
Do you know where the call to `establishStackSpace` is coming from?  If you compile with -O0 or -O1 you should be able to easly see where it is in the JS.

**Comment by sbc100** [comment]
we should have enough tests to cover this once thread+wasm_backend is working.
