### ISSUE TITLE
Problem trying to compile C++ code to WASM (line 405 in gen_struct_info.py)

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#8505]
I'm opening another issue for this because the other was mainly for libc.a not being generated.  

I can't compile any code with Emscripten.  I always get this message:
```
Traceback (most recent call last):
  File "C:\emscripten\emcc.py", line 3316, in <module>
    sys.exit(run(sys.argv))
  File "C:\emscripten\emcc.py", line 1947, in run
    final = shared.Building.emscripten(final, target + '.mem', js_libraries)
  File "C:\emscripten\tools\shared.py", line 2209, in emscripten
    emscripten.run(infile, outfile, memfile, js_libraries)
  File "C:\emscripten\emscripten.py", line 2556, in run
    shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, ensure_struct_info)
  File "C:\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\emscripten\emscripten.py", line 2553, in ensure_struct_info
    gen_struct_info.main(['-qo', out, path_from_root('src', 'struct_info.json')])
  File "C:\emscripten\tools\gen_struct_info.py", line 527, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "C:\emscripten\tools\gen_struct_info.py", line 405, in inspect_code
    info = shared.run_js(js_file[1]).splitlines()
  File "C:\emscripten\tools\shared.py", line 1090, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "C:\emscripten\tools\jsrun.py", line 155, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['C:\\Program Files\\nodejs\\node.exe', 'c:\\users\\osman\\appdata\\local\\temp\\tmpjvne59.js'] to finish with return code 0, but it returned with code -1073741819 instead! Output:

```
And my C:/Users/<name>/.emscrpten_cache/wasm_obj/ directory doesn't have libc++.a for some reason.  How do I generate that?  It has libc++_noexcept.a, though.  

I built LLVM 9.0.0 using Visual Studio 2019's MSVC compiler (latest version of MSVC compiler) and I have Node version 11.14.0.  I updated Emscripten to the latest version via the `git pull` command, too.  I wasn't having this problem with the LLVM version 8, built using MSVC 14.2 which came with VS2017.  Could it be that VS2019 builds of LLVM haven't been tested with Emscripten yet?  Maybe there's an incompatibility problem here.

**Comment by sbc100** [comment]
All the standard libraries should be generated on-demand as they are required.

You could forcibly compiler them using "./embuilder build <name>", or "./emsbuild build ALL" to build them all. 

We test emscripten with tip of tree llvm built from source only.  Its hard to imagine why VS2019 LLVM would be different to upstream.   Are you saying that VS2019 provided your LLVM binaries, or that you build your own LLVM binaries using VS2019?

In terms of the exception above there seems to be an issue running tools/gen_struct_info.py which builds a small C program to output struct offsets.  This program is returning non-zero but doesn't seem to be showing any output which seems very strange.

**Comment by DragonOsman** [comment]
@kripken Do I need to read the code in all of the Python files mentioned in the error message?  If so, I'll do that.  Unless there's documentation on them that I could read instead (I hope there is--if there isn't, please create it.  Thanks).

**Comment by DragonOsman** [comment]
@sbc100 @kripken Something else I noticed.  I didn't have the Build Tools for VS2019 installed, so I installed them using Chocolatey.  But the VCTargetsPath.vcxproj project file still can't find the Build Tools, so I made a thread about the issue on the MSDN forums.  I'm also asking here since it's something related to Emscripten.  I can't generate project files for VS2019 for Emscripten because of this.  Should I also ask at the CMake mailing list, or is just here and MSDN enough?  

This is the error message I got:
```
cmake ../tools/optimizer -G"Visual Studio 16 2019" -A Win64 -DCMAKE_BUILD_TYPE=Release
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 4/27/2019 3:11:32 AM.
    Project "C:\emscripten\build\CMakeFiles\3.14.3\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\emscripten\build\CMakeFiles\3.14.3\VCTargetsPath.vcxproj]
    Done Building Project "C:\emscripten\build\CMakeFiles\3.14.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\emscripten\build\CMakeFiles\3.14.3\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\emscripten\build\CMakeFiles\3.14.3\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:02.46


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/emscripten/build/CMakeFiles/CMakeOutput.log".
```
Any help is appreciated.  Thanks.

**Comment by sbc100** [comment]
That looks like a general cmake issue.  The native optimizer is just a normal host binary .. it should build just like any other cmake project.   Can you build a trivial cmake hello world project with your current setup?

**Comment by DragonOsman** [comment]
Looks like the problem is with the VS2019 generator in CMake.  Generating solution and project files for VS2017 still works like a charm.

**Comment by DragonOsman** [comment]
I'll keep using the VS2017 generator in CMake for now, until the problem with the VS2019 generator is fixed.  I'm thinking that it could be a problem with the location of the Build Tools since it looks like CMake can't find them (maybe Microsoft changed the location of the Build Tools in VS2019? (It's VCTargetsPath.vcxproj that can't find the Build Tools, but isn't that project file generated by CMake? That's what I'm thinking at least)).

**Comment by DragonOsman** [comment]
Actually, never mind; it turns out that the platform flag, `-A`, is `x64`.  It could be that the reason it wasn't working is because I was using `Win64` as the value for it.  I'll try it with that and get back to you.

**Comment by DragonOsman** [comment]
@sbc100 I finally managed to build the Emscripten native optimizer and Binaryen.  The value for the platform was the problem.  I still need help with handling a situation where I have a C++ program that takes user input that I want to compile to WASM as a Node module, though.  When I tried it with an ES6 module, I got a `text` string object that was printed to the HTML document itself, and it included the prompt for input and the result of processing it as one whole piece.  I don't want that.  I want the prompt to be separate and for the user to be given the chance to give input through stdin after the prompt is printed to stdout.  Is this possible?

**Comment by sbc100** [comment]
You should be able to write your input loop as a node js file that can then call into your wasm module as you like.

See https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

Seems like the original issue here is fixes?
