### ISSUE TITLE
'emcc' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by MatteoGioioso** [emscripten-core/emscripten#8509]
I have installed emscripten according to the instructions: https://emscripten.org/docs/getting_started/downloads.html
Everything seems to work fine

`emsdk_env.bat`
```
PATH += C:\Users\plasm\Google Drive\Development\Tools\emsdk
PATH += C:\Users\plasm\Google Drive\Development\Tools\emsdk\clang\e1.38.30_64bit
PATH += C:\Users\plasm\Google Drive\Development\Tools\emsdk\node\8.9.1_64bit\bin
PATH += C:\Users\plasm\Google Drive\Development\Tools\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64
PATH += C:\Users\plasm\Google Drive\Development\Tools\emsdk\java\8.152_64bit\bin
PATH += C:\Users\plasm\Google Drive\Development\Tools\emsdk\emscripten\1.38.30

Setting environment variables:
EMSDK = C:/Users/plasm/Google Drive/Development/Tools/emsdk
EM_CONFIG = C:\Users\plasm\.emscripten
LLVM_ROOT = C:\Users\plasm\Google Drive\Development\Tools\emsdk\clang\e1.38.30_64bit
EMSCRIPTEN_NATIVE_OPTIMIZER = C:\Users\plasm\Google Drive\Development\Tools\emsdk\clang\e1.38.30_64bit\optimizer.exe
BINARYEN_ROOT = C:\Users\plasm\Google Drive\Development\Tools\emsdk\clang\e1.38.30_64bit\binaryen
EMSDK_NODE = C:\Users\plasm\Google Drive\Development\Tools\emsdk\node\8.9.1_64bit\bin\node.exe
EMSDK_PYTHON = C:\Users\plasm\Google Drive\Development\Tools\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe
JAVA_HOME = C:\Users\plasm\Google Drive\Development\Tools\emsdk\java\8.152_64bit
EMSCRIPTEN = C:\Users\plasm\Google Drive\Development\Tools\emsdk\emscripten\1.38.30
```

`emcc -v` output
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.30
clang version 6.0.1  (emscripten 1.38.30 : 1.38.30)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\plasm\Google Drive\Development\Tools\emsdk\clang\e1.38.30_64bit
shared:INFO: (Emscripten: Running sanity checks)
```

However when I try to open a terminal on my target folder and run `emcc -v` it gives me this error `'emcc' is not recognized as an internal or external command, operable program or batch file`

My system:
Windows 10 Pro
node: 10.14.1

**Comment by kripken** [comment]
I think when you open a new terminal, you need to run `emsdk_env.bat` again, so emcc is in the path.

**Comment by MatteoGioioso** [comment]
I have tried already, but of course I have the same error
```
'emsdk_env.bat' is not recognized as an internal or external command,
operable program or batch file.
```

The current work around is to open a terminal on the `emsdk` folder run `emsdk_env.bat` and navigate to my target folder. But it is a bit cumbersome and should not be like that.

**Comment by sbc100** [comment]
All you need to do is find some way to running emsdk_env.bat in your terminal.  There are any number of ways to do that.  Probably the simplest would be to add the emsdk folder to your PATH and then run emsdk_env.bat from anywhere.  

This seems to be working as intended and as documented in https://emscripten.org/docs/getting_started/downloads.html

**Comment by MatteoGioioso** [comment]
@sbc100 So, every time I open a new terminal session to use emscripten I have to run that script? Is this how it suppose to work?

**Comment by sbc100** [comment]
Yes, I think so.  I believe visual studio works the same way.  There is batch file that sets up the environment.   I'm sure there are several ways you can add that batch file to you startup script if you wish to have it done automatically.

Its similar on UNIX, we have an `emsdk_env.sh` shell script that needs to be sourced in order to use the SDK.

**Comment by MatteoGioioso** [comment]
Ok then, I think I can close this issue, thanks!
