### ISSUE TITLE
wasm1.test_wasm_builtin_simd fails

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8516]
We only test `-O0` and `-O2` on the bots, so `-O1` was missed. Error is

```
-Success!
+Failed :(
+line 954: expected 1, got 0
+line 1041: expected 1, got 0
+line 1125: expected 1, got 0
```

**Comment by tlively** [comment]
Looks like these are all boolean reductions failing to run. I believe V8 used to have this bug but it was fixed a while ago. What engine are the tests being run with? It's certainly surprising that they pass at -O0 and -O2 but not at -O1.

**Comment by kripken** [comment]
Ah, it's probably that my local v8 build is too old then!
