### ISSUE TITLE
Using -O1 or higher breaks this program (index out of bounds)

### ISSUE THREAD

**Issue by singpolyma-shopify** [emscripten-core/emscripten#8523]
https://0x0.st/zcuM.tar

compile with:

    emcc -std=c99 -Wall --memory-init-file 0 -DEMSCRIPTEN -s EXPORTED_FUNCTIONS='["_run", "_shopify_runtime_allocate"]' -s SUPPORT_LONGJMP=0 -O0 duktape.c

run in firefox from console with:

    Module._run(1)

Get expected result: 3.  Compile with:

    emcc -std=c99 -Wall --memory-init-file 0 -DEMSCRIPTEN -s EXPORTED_FUNCTIONS='["_run", "_shopify_runtime_allocate"]' -s SUPPORT_LONGJMP=0 -O1 duktape.c

(or `-O2`, `-O3`, `-Os`, `-Oz`) and run the same way in firefox console... get:

    RuntimeError: index out of bounds

**Comment by kripken** [comment]
The stack trace in a debug build might help figure this out.

One possibility is that the program has undefined behavior, and clang takes advantage of that in -O1 and above to do more things. Testing with ubsan in a native build might help (it could detect it even if the undefined behavior doesn't break the native build in a similar way).

More unlikely causes, but worth ruling out, are a specific browser bug - does it crash in non-firefox as well? Also possible its a non-LLVM optimizer bug. Can try to compare to a JS build (`-s WASM=0`), and also to a wasm backend build.
