### ISSUE TITLE
__builtin_unreachable() accepted but does not generate (unreachable)

### ISSUE THREAD

**Issue by singpolyma-shopify** [emscripten-core/emscripten#8525]
Calling `__builtin_unreachable()` is accepted by emcc, but the resulting wasm seems to contain nothing, rather than the expected `unreachable` instruction.

**Comment by kripken** [comment]
It looks like that is lowered to an LLVM `unreachable`. The meaning of that is that the code can't be reached, not that it will trap - arguably the wasm `unreachable` should have been named `trap` to avoid confusion.

I would expect `__builtin_trap` to emit a wasm `unreachable`, but that doesn't happen either, which surprises me. It's lowered to an `llvm.trap`, so this might be a bug in the LLVM wasm backend? (In asm2wasm, it emits a fall to an external `llvm_trap` function which does trap.)

**Comment by dschuff** [comment]
The wasm backend does lower @llvm.trap to `unreachable`: see e.g. https://github.com/llvm/llvm-project/blob/master/llvm/test/CodeGen/WebAssembly/unreachable.ll

**Comment by kripken** [comment]
Ah yes, thanks, I see it does. I forgot that there is both main and __original_main and I was looking at the wrong one.

Looks like there isn't a bug here then, closing.
