### ISSUE TITLE
Error: "ReferenceError: read is not defined" when running on Node using ES6 module support with --experimental-modules

### ISSUE THREAD

**Issue by rapodaca** [emscripten-core/emscripten#8542]
I'm getting an error whenever I try to run compiled C on Node 12.1.0 behind the `--experimental-modules` flag. The code is compiled using Emscripten's `-s MODULARIZE=1` and `-s EXPORT_ES6=1` flags. I think the problem has to do with how the generated JavaScript detects the environment.

I compiled the following C file:

```c
#include <stdio.h>
#include <emscripten.h>

EMSCRIPTEN_KEEPALIVE
int test() {
  printf("Ready\n");

  return 0;
}
```

using the following script:

```bash
mkdir -p build
emcc \
  src/test.c \
  -o build/test.js -s WASM=1 -s MODULARIZE=1 -s EXPORT_ES6=1
```

I'm using the following JavaScript file to test the result:

```javascript
import Module from '../build/test.js';

const instance = Module();

instance.then(() => {
  console.log('OK');
});
```

Running the JavaScript test gives an error:

```bash
$ node --experimental-modules lib/inchi.js 
(node:95155) ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: read is not defined
[... more output]
```

Environment detection appears to take place around this block in the generated JavaScript:

```javascript
var ENVIRONMENT_IS_WEB = false;
var ENVIRONMENT_IS_WORKER = false;
var ENVIRONMENT_IS_NODE = false;
var ENVIRONMENT_IS_SHELL = false;
ENVIRONMENT_IS_WEB = typeof window === 'object';
ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function' && !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_WORKER;
ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
```

`require` isn't defined when running the `--experimental-modules` flag. So this approach won't work right when native ES6 modules are turned on.

As a workaround I am able to run the code without issue with reify.js (using the `--require reify` flag).

**Comment by VirtualTim** [comment]
Just FYI, if you're planning on using ES6 + threads it's currently not supported. I've got a PR (#8306) open, and it's in the review stage, so hopefully will go through soon.

**Comment by dasa** [comment]
> `require` isn't defined when running the `--experimental-modules` flag. So this approach won't work right when native ES6 modules are turned on.

@kripken I'm not sure, but I think there may need to be a new environment for when the script is running as an ESM module in Node. The `--experimental-modules` flag is not needed anymore starting with Node [13.2](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.2.0). The other option could be to feature detect the [differences](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html) within the ENVIRONMENT_IS_NODE code.

**Comment by ternaam** [comment]
With the emscripten version I use I get
```js
ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof process.versions === 'object' && typeof process.versions.node === 'string';
```
As check for NODE environment, but even then it tries to `require('path')` and `ws` later (maybe more, haven't checked fully). 

So it really seems that emscripten ESM running in nodejs is just not supported at the moment.

**Comment by VirtualTim** [comment]
FYI I've been running an ES6+NodeJS build since 1.39.6.
So I'm pretty sure this is actually fixed.
