### ISSUE TITLE
pthread sigmask/atfork no-op when using NNG

### ISSUE THREAD

**Issue by aliasdevelopment** [emscripten-core/emscripten#8545]
I am trying to port an existing application which is using [nng](https://github.com/nanomsg/nng). 

At runtime I get no-op errors relating to [sigmask](https://github.com/emscripten-core/emscripten/blob/edb38262494a8ac9c84c93b511eceffcfc1f1a7a/src/library_pthread.js#L994) and [atfork](https://github.com/emscripten-core/emscripten/blob/edb38262494a8ac9c84c93b511eceffcfc1f1a7a/src/library_pthread.js#L998)

Is it technically possible to support pthread_sigmask and pthread_atfork in emscripten?

**Comment by aliasdevelopment** [comment]
I found "The Emscripten implementation does also not support multiprocessing via fork() and join()." on https://emscripten.org/docs/porting/pthreads.html.

Is this statement valid as a 'not support yet' statement or 'is not possible' statement?

**Comment by aliasdevelopment** [comment]
Both #7670 and #7672 are hinting changes allowing full posix sockets and multithreading aware websockets

**Comment by aliasdevelopment** [comment]
The initial issue has been seen on emscripten branch master and incoming.

Tried juj:full_posix_sockets branch described in #7672 and is still getting the no-op

Using: `-lwebsocket.js -s PROXY_POSIX_SOCKETS=1 -s USE_PTHREADS=1 -s PROXY_TO_PTHREAD=1`

> Preallocating 1 workers for a pthread spawn pool. app_one.html:1237:13
Network - Starting app_one.html:1237:13
Network - Call resolve app_one.html:1237:13
Network - Resolve start: ws://127.0.0.1:9999 app_one.html:1237:13
Preallocating 1 workers for a pthread spawn pool. app_one.html:1237:13
fork() is not supported: pthread_atfork is a no-op. app_one.js:9328:7
Preallocating 1 workers for a pthread spawn pool. app_one.html:1237:13
pthread_sigmask() is not supported: this is a no-op. app_one.js:9611:7
Preallocating 1 workers for a pthread spawn pool. app_one.html:1237:13
pthread_sigmask() is not supported: this is a no-op. app_one.js:9611:7
Preallocating 1 workers for a pthread spawn pool. app_one.html:1237:13
pthread_sigmask() is not supported: this is a no-op.

**Comment by femski** [comment]
I have installed and activated latest 1.39.8 build (also tried "master" build) and I still see:

fork() is not supported: pthread_atfork is a no-op

Also, pthread_sigmask throws exception.

I am trying to use libuv (posix only) to work under emscripten

Issue #7672 and Issue #7670 are both supposed to merged to "incoming" which I thought was now "master".  Any idea when we can use pthread_sigmast/pthread_atfork in emscriten ?
