### ISSUE TITLE
Do not minify HTML entry point

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#8547]
Since a few versions emcc also minifies the HTML entry point (built from shell.html).

This file is pretty small and does not benefit a lot from minification. However minification is a significant hassle when testing changes in a customized shell.html, or when shipping an HTML entry point that is possibly further customized by the end user (like I do with RenPyWeb, where I provide a generic runtime for Ren'Py games).

I couldn't find an option to selectively remove minification of the HTML entry point either.

**Comment by kripken** [comment]
cc @juj who added that, I believe.
