### ISSUE TITLE
Missing out folder causes the build to fail with unhelpful error message

### ISSUE THREAD

**Issue by innerop** [emscripten-core/emscripten#8549]
When specifying a non-existent folder e.g. -o bin/abc.js we see this really confusing error message:

IOError: [Errno 2] No such file or directory: 'bin/abc.js.mem'

I assumed it was as the error message says failing to find bin/abc.js.mem which it is responsible for generating in the first place. It maybe a standard Python file creation API behavior to report that file to be created does not exist (doh, really? unless time travel) when parent folder doesn't but it is very confusing in terms of the temporal logic.  See below: 

https://groups.google.com/forum/#!topic/emscripten-discuss/OQO9hphO5nY

**Comment by kripken** [comment]
Thanks @innerop! Fix in #8551 - yeah, that error message is really confusing...

**Comment by innerop** [comment]
Sweet!
