### ISSUE TITLE
Possible bugs in branch wasm-simd-intrinsics

### ISSUE THREAD

**Issue by jing-bao** [emscripten-core/emscripten#8553]
In the WASM SIMD intrinsics test and header files in commit 902b2a0ef384b6f21ece46a3e9c3ac67386f3230, there seem to be some typos and bugs which block the compilation.
For example,
1. Type mismatches will cause compilation errors when `-fno-lax-vector-conversions` is on.
    One possible fix may be changing `typedef int8_t i8x16 __attribute__((__vector_size__(16)));` to `typedef char i8x16 __attribute__((__vector_size(16)));`
2. Missing intrinsic functions in simd128.h. e.g. `wasm_f32x4_div`
3. `_Generic` controlling-expression types should be modified to handle all possible types.
4. Improper usage of `__wasm_unimplemented_simd128__`. e.g. `wasm_f32x4_eq` doesn’t need this macro.
5. `__wasm_undefined_simd128__` seems to be typo of `__wasm_unimplemented_simd128__`

We are working on fixing these.

**Comment by tlively** [comment]
I just met with @rrwinterton about these issues and the decision in that meeting was that I would fix these issues up and create a PR for further discussion. I expect to have a working PR up tonight. Sorry for the duplicate effort, but I think that is the fastest path to getting these done.

**Comment by tlively** [comment]
The intrinsics have been fixed up and moved upstream into clang.
