### ISSUE TITLE
Would like help with this again: gen_struct_info.py

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#8557]
@sbc100 @kripken 

Hi again.

This time I've built LLVM 9.0.0 with the -A x64 and -Thost=x64 flags and also built Binaryen and Emscripten's asm.js optimizer again, then tried to compile some C code to WebAssembly.  But I get the same error as before: 
```
Traceback (most recent call last):
  File "C:\emscripten\emcc.py", line 3316, in <module>
    sys.exit(run(sys.argv))
  File "C:\emscripten\emcc.py", line 1947, in run
    final = shared.Building.emscripten(final, target + '.mem', js_libraries)
  File "C:\emscripten\tools\shared.py", line 2197, in emscripten
    emscripten.run(infile, outfile, memfile, js_libraries)
  File "C:\emscripten\emscripten.py", line 2560, in run
    shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, ensure_struct_info)
  File "C:\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\emscripten\emscripten.py", line 2557, in ensure_struct_info
    gen_struct_info.main(['-qo', out, path_from_root('src', 'struct_info.json')])
  File "C:\emscripten\tools\gen_struct_info.py", line 529, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "C:\emscripten\tools\gen_struct_info.py", line 407, in inspect_code
    info = shared.run_js(js_file[1]).splitlines()
  File "C:\emscripten\tools\shared.py", line 1090, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "C:\emscripten\tools\jsrun.py", line 155, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['C:\\Program Files\\nodejs\\node.exe', 'c:\\users\\osman\\appdata\\local\\temp\\tmpadbhvx.js'] to finish with return code 0, but it returned with code -1073741819 instead! Output:
```
The command I ran was:
```
emcc -std=c11 -Wall -pedantic main.c -Os -s WASM=1 -s SIDE_MODULE=1 -s BINARYEN_ASYNC_COMPILATION=0 -o main.wasm
```
And it gave me a .wasm file -- but the file is corrupted.  When I tried to click "Show WebAssembly" in the context menu that comes up when right-clicking on a .wasm file in Visual Studio Code's left pane, I had these two errors:
```
Unable to open 'main.wasm': resource is not available.
```
and 
```
readWasm failed: 000007b: error: invalid linking metadata version: 2
```
Any help or advice is greatly appreciated.  Thanks in advance.

**Comment by DragonOsman** [comment]
I found this just now: https://github.com/emscripten-core/emscripten/pull/6520 .  What's the situation about this now?  Also, is it possible to get generated_struct_info.json downloaded from somewhere, assuming it's the same for any case (Emscripten caches it after generating it once, which is why I'm assuming that).

**Comment by sbc100** [comment]
We really need to see what went wrong with the running of the gen_struct_info output under node, but its not very easy to debug this without hacking on the code I fear.   We should make it easier for people to run gen_struct_info.py standalone.  Right now the simplest way to run it is "./embuilder BUILD struct_info`.. can you verify this also fails in the same way.

**Comment by DragonOsman** [comment]
Do you mean hacking on the implementation of gen_struct_info?  

I'm using standalone Emscripten and Binaryen with a Wasm Backend, with no EMSDK or Fastcomp.  

When I try to do ` .\embuilder BUILD struct_info ` (I'm using Windows 10, not Linux or Mac), I get this:
```
'embuilder' is not recognized as an internal or external command,
operable program or batch file.
```
I had to do `embuilder.py build struct_info`; the result was:
```
embuilder:INFO: building and verifying struct_info
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\generated_struct_info.json" for subsequent builds)
Traceback (most recent call last):
  File "C:\emscripten\emcc.py", line 3316, in <module>
    sys.exit(run(sys.argv))
  File "C:\emscripten\emcc.py", line 1947, in run
    final = shared.Building.emscripten(final, target + '.mem', js_libraries)
  File "C:\emscripten\tools\shared.py", line 2197, in emscripten
    emscripten.run(infile, outfile, memfile, js_libraries)
  File "C:\emscripten\emscripten.py", line 2560, in run
    shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, ensure_struct_info)
  File "C:\emscripten\tools\cache.py", line 133, in get
    temp = creator()
  File "C:\emscripten\emscripten.py", line 2557, in ensure_struct_info
    gen_struct_info.main(['-qo', out, path_from_root('src', 'struct_info.json')])
  File "C:\emscripten\tools\gen_struct_info.py", line 529, in main
    struct_info = inspect_code(header_files, cpp_opts, structs, defines)
  File "C:\emscripten\tools\gen_struct_info.py", line 407, in inspect_code
    info = shared.run_js(js_file[1]).splitlines()
  File "C:\emscripten\tools\shared.py", line 1090, in run_js
    return jsrun.run_js(filename, engine, *args, **kw)
  File "C:\emscripten\tools\jsrun.py", line 155, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['C:\\Program Files\\nodejs\\node.exe', 'c:\\users\\osman\\appdata\\local\\temp\\tmpfpnshe.js'] to finish with return code 0, but it returned with code -1073741819 instead! Output:
shared:ERROR: embuilder: emcc command failed with 1: 'C:\Python27\python.exe C:\emscripten\emcc.py C:\Users\Osman\AppData\Local\Temp\tmppijujc\src.cpp -o C:\Users\Osman\AppData\Local\Temp\tmppijujc\out.js'
```
Is it possible to save the .cpp and .js files that are generated so that I can look at them later if needed (I could show them to you then)?

**Comment by sbc100** [comment]
> Do you mean hacking on the implementation of gen_struct_info?
> 
> I'm using standalone Emscripten and Binaryen with a Wasm Backend, with no EMSDK or Fastcomp.
> 
> When I try to do `.\embuilder BUILD struct_info` (I'm using Windows 10, not Linux or Mac), I get this:
> 
> ```
> 'embuilder' is not recognized as an internal or external command,
> operable program or batch file.
> ```
> 
> I had to do `embuilder.py build struct_info`; the result was:
> 
> ```
> embuilder:INFO: building and verifying struct_info
> cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "C:\Users\Osman\.emscripten_cache\wasm-obj\generated_struct_info.json" for subsequent builds)
> Traceback (most recent call last):
>   File "C:\emscripten\emcc.py", line 3316, in <module>
>     sys.exit(run(sys.argv))
>   File "C:\emscripten\emcc.py", line 1947, in run
>     final = shared.Building.emscripten(final, target + '.mem', js_libraries)
>   File "C:\emscripten\tools\shared.py", line 2197, in emscripten
>     emscripten.run(infile, outfile, memfile, js_libraries)
>   File "C:\emscripten\emscripten.py", line 2560, in run
>     shared.Settings.STRUCT_INFO = shared.Cache.get(generated_struct_info_name, ensure_struct_info)
>   File "C:\emscripten\tools\cache.py", line 133, in get
>     temp = creator()
>   File "C:\emscripten\emscripten.py", line 2557, in ensure_struct_info
>     gen_struct_info.main(['-qo', out, path_from_root('src', 'struct_info.json')])
>   File "C:\emscripten\tools\gen_struct_info.py", line 529, in main
>     struct_info = inspect_code(header_files, cpp_opts, structs, defines)
>   File "C:\emscripten\tools\gen_struct_info.py", line 407, in inspect_code
>     info = shared.run_js(js_file[1]).splitlines()
>   File "C:\emscripten\tools\shared.py", line 1090, in run_js
>     return jsrun.run_js(filename, engine, *args, **kw)
>   File "C:\emscripten\tools\jsrun.py", line 155, in run_js
>     raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
> Exception: Expected the command ['C:\\Program Files\\nodejs\\node.exe', 'c:\\users\\osman\\appdata\\local\\temp\\tmpfpnshe.js'] to finish with return code 0, but it returned with code -1073741819 instead! Output:
> shared:ERROR: embuilder: emcc command failed with 1: 'C:\Python27\python.exe C:\emscripten\emcc.py C:\Users\Osman\AppData\Local\Temp\tmppijujc\src.cpp -o C:\Users\Osman\AppData\Local\Temp\tmppijujc\out.js'
> ```
> 
> Is it possible to save the .cpp and .js files that are generated so that I can look at them later if needed (I could show them to you then)?

Its possible, but you'd need to hack on the script a bit I think.  Thats kind of what I mean by improving debug-ability here.

**Comment by sbc100** [comment]
node should be producing some kind of output or error message.. if you can find that it might give you a clue.

**Comment by DragonOsman** [comment]
Node's output in Emscripten's message seems to be empty.  

So I have to do something to the gen_struct_info.py script so that it saves the .cpp and .js files somewhere?  What do I need to do exactly?

**Comment by DragonOsman** [comment]
Are you sure there's an error message from Node, even though there seems to be an empty output in the message returned from `embuilder`?

**Comment by sbc100** [comment]
No.  From what I can see all we know right now is that node is not returning zero after running the test program.  If you can figure out why its not returning zero that would be useful.

**Comment by DragonOsman** [comment]
Yes, but do you have any suggestions on how I can do that?  Right now I'm still learning C++ and client-side JavaScript (though I already know quite a bit, there's still stuff I want to learn and some things I'm still not good at), so I don't know much about Node yet at this point.

**Comment by sbc100** [comment]
I recently updated `tools/gen_struct_info.py` in #8716 so you should be able to simply run it directly with no args.

Should make debugging easier.
