### ISSUE TITLE
Release 1.38.31 not available for OSX

### ISSUE THREAD

**Issue by kjpou1** [emscripten-core/emscripten#8560]
The latest release is 1.38.30 for OSX as per the file: https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/index.txt

```
emscripten-llvm-e1.38.9.tar.gz
emscripten-llvm-e1.38.8.tar.gz
emscripten-llvm-e1.38.7.tar.gz
emscripten-llvm-e1.38.6.tar.gz
emscripten-llvm-e1.38.5.tar.gz
emscripten-llvm-e1.38.4.tar.gz
emscripten-llvm-e1.38.30.tar.gz
emscripten-llvm-e1.38.3.tar.gz
```

Issuing the command:

```
./emsdk update-tags
Fetching all tags from Emscripten Github repository...
Done. 159 tagged releases available, latest is 1.38.31.
Fetching all tags from Binaryen Github repository...
Done. 86 tagged Binaryen releases available, latest is 1.38.31.
```

```
https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/osx_64bit/emscripten-llvm-e1.38.31.tar.gz
```

Can OSX be updated please?

**Comment by kripken** [comment]
I landed a change on emscripten now, so it should kick off the builder.

Btw, we are working on replacing all those bots - the new solution should be more reliable. But there might be some issues during the transition.

**Comment by kripken** [comment]
Tags seem to have been built ok - sorry for the delay.

**Comment by kjpou1** [comment]
Thanks @kripken
