### ISSUE TITLE
[feature request] Please add the LLVM_SUFFIX config variable

### ISSUE THREAD

**Issue by yurivict** [emscripten-core/emscripten#8564]
LLVM executables on FreeBSD are named with suffix corresponding to the version, ex. ```llvm-dis80``` or ```llvm-dis-devel```.

**Comment by sbc100** [comment]
It looks like we have support for this already in the form of `LLVM_ADD_VERSION` and `CLANG_ADD_VERSION`.

Not very well named, but they seem to do what you want.   I don't know why we would need two different settings either.

**Comment by yurivict** [comment]
Thanks!
