### ISSUE TITLE
 error: "No thread API" (on FreeBSD)

### ISSUE THREAD

**Issue by yurivict** [emscripten-core/emscripten#8566]
On FreeBSD ```emcc``` always fails:
```
$ emcc x.cc 
In file included from x.cc:1:
In file included from /usr/local/lib/emscripten/system/include/libcxx/math.h:295:
/usr/local/lib/emscripten/system/include/libcxx/__config:1042:4: error: "No thread API"
#  error "No thread API"
   ^
1 error generated.
```

Looking at this place in ```libcxx/__config``` it shouldn't happen because ```__FreeBSD__``` is normally defined on FreeBSD, but it happens somehow.

**Comment by kripken** [comment]
Hmm, emcc should not depend on local system defines, as it behaves like a cross-compiler. I think we need to look at that header and see which part ends up used on other OSes, as that might be wrong.

**Comment by yurivict** [comment]
Just adding ```#define __FreeBSD__``` there alowed it to proceed past this point.

**Comment by sbc100** [comment]
I think the problem is that __EMSCRIPTEN__ is not being defined by your compiler.

`__FreeBSD__` should certainly *not* be defined.  We are cross compiling here.

**Comment by yurivict** [comment]
What should I patch to define ```__EMSCRIPTEN__```? The compiler in use is llvm-devel which is at version 9 now.

**Comment by sbc100** [comment]
See my comments on #8569,  I think this is basically a duplicate of that issue.   It looks like you need to rev  llvm-devel to a more recent revision.

**Comment by yurivict** [comment]
Thanks, I am trying to update ```llvm-devel```.
