### ISSUE TITLE
[security problem] Downloads code archives without checking fingerprints

### ISSUE THREAD

**Issue by yurivict** [emscripten-core/emscripten#8568]
In many places the function ```ports.fetch_project``` downloads code archives without checking fingerprints. This makes such downloads susceptible to MITM attacks.

Examples:
* https://github.com/emscripten-core/emscripten/blob/incoming/tools/ports/binaryen.py#L27
* https://github.com/emscripten-core/emscripten/blob/incoming/tools/ports/sdl2.py#L18

**Comment by sbc100** [comment]
Surely the use of https mitigates this risk?    I agree is better to include hashes, but mostly for integrity checking and to detect unexpected content changes.

If you are worried about man in the middle of github.com over https then aren't you exposed to this same risk every time you `git pull` from any github repo?

**Comment by yurivict** [comment]
> Surely the use of https mitigates this risk?

Are you kidding?

**Comment by sbc100** [comment]
Of course, mitigate was perhaps too strong a word there :)  

I was thinking that most users get emscripten via `git fetch` so those people are already exposed in this way.   I believe emsdk also doesn't use hashes so those users are too.  Might be worth fixing emsdk at least to use hashes.

**Comment by quantum5** [comment]
I think the more realistic threat is a malicious user deliberately uploading a bad tarball to github/sourceforge.

**Comment by yurivict** [comment]
I am used to the FreeBSD packaging framework, and it strictly requires fingerprints for all files.

Most users should be installing emscripten from the packages on their corresponding OSes. I know, some of them are slow, or eben non-existent (like on windows). But they all have mailing lists, you should request packages to be created through these lists.

Currently available ports: https://repology.org/project/emscripten/versions

**Comment by yurivict** [comment]
> I think the more realistic threat is a malicious user deliberately uploading a bad tarball to github/sourceforge.

This too, but in Kazakhstan, for example, the government mandates that all users have government certificate installed, so that they can look at every request's content and can seamlessly substitute every downloaded file.

Fingerprints still stand up to that, and https doesn't.

**Comment by yurivict** [comment]
I also believe that there are some compromised certificate authorities among the hundreds of them that browsers use to validate https. One needs to trust hundreds of entities that one has never personally encountered, with some of which have been revoked before. This is quite a questionable proposition to trust everybody in such list.
