### ISSUE TITLE
Chrome leaks memory on page refresh with PTHREADS

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8571]
Compile an empty file like:
`emcc empty.cpp -s TOTAL_MEMORY=536870912 -s USE_PTHREADS=1 -s THREAD_POOL_SIZE=10 -o test.html`
Open in Chrome, open the Chrome task manager (shift esc), and refresh the page a few times.
"Memory footprint" will increase by ~500MB on each refresh, until the tab crashes.
![image](https://user-images.githubusercontent.com/5424257/57440672-0449cc80-727b-11e9-8608-23dff1706a11.png)
Tested in Chrome 76.0.3789.0.

No idea if the issue is on Chrome or Emscripten, but figured that I'd open here to see if anyone had any ideas. I couldn't reproduce on Firefox.

**Comment by kripken** [comment]
I'm afraid this is a known issue on Chrome currently. Should be https://bugs.chromium.org/p/chromium/issues/detail?id=935169 / https://bugs.chromium.org/p/chromium/issues/detail?id=877055 They're assigned, and I believe they are being looked at.

**Comment by VirtualTim** [comment]
Alright. I had a look on the Chrome bug tracker, but didn't see that. I'll close this.
