### ISSUE TITLE
Serious z-fighting?

### ISSUE THREAD

**Issue by fei2020** [emscripten-core/emscripten#8573]
I running an emscripten opengl application in browsers. 
z-fighting is much more serious in mobile browsers than in PC browsers. Please see the figures below.
I have checked the GL_DEPTH_BITS in my mobile browsers and my PC browser. They are both 24.

In mobile browsers:
[1.png](http://ec2-54-95-2-219.ap-northeast-1.compute.amazonaws.com/1.png)

In PC browsers:
[2.png](http://ec2-54-95-2-219.ap-northeast-1.compute.amazonaws.com/2.png)

This is another live demo(thank fogleman and satoshinm) to show this problem.
[Another live demo](https://satoshinm.github.io/NetCraft/)
You can compare it in mobile(Can't rotate view in Android devices. You'd better use IOS devices.) and pc.

And I found emscripten version of cube2 has the same problem too.
[Cube2](https://kripken.github.io/BananaBread/cube2/bb.html)

**Comment by kripken** [comment]
This sounds like a browser bug. Probably best to file it directly there so the right people can see it.

**Comment by fei2020** [comment]
> This sounds like a browser bug. Probably best to file it directly there so the right people can see it.

thank you for your attention

**Comment by fei2020** [comment]
This problem has been solved with highp precision in shaders.
