### ISSUE TITLE
emcc fails to find "emmintrin.h" even with -msse2

### ISSUE THREAD

**Issue by GeorgeLyon** [emscripten-core/emscripten#8576]
I'm currently running emcc in a docker container:
```
emcc (Emscripten gcc/clang-like replacement) 1.38.30 (commit 9538381d56272818cba77a808ba46fdac6c961c8)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The actual command which is run: 
```
emcc -O3 -msse2 -s WASM=1 -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap"]' -I Dependencies/argon2/include -I Dependencies/libecc/src -I Dependencies/tweetnacl -I Sources/CLibOpaque/include <source files>
```

It produces the following output, despite the documentation [here](https://emscripten.org/docs/porting/simd.html#enabling-simd-code-generation)
```
~/D/O/WebAssembly> ./build --use-docker
clang-6.0: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
clang-6.0: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
In file included from Dependencies/argon2/src/opt.c:26:
Dependencies/argon2/src/blake2/blamka-round-opt.h:23:10: fatal error: 'emmintrin.h' file not found
#include <emmintrin.h>
         ^~~~~~~~~~~~~
1 error generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
```

The full source of my project can be found here: https://github.com/GeorgeLyon/Opaque
The issue can be reproduced by running `WebAssembly/build`

**Comment by sbc100** [comment]
These were removed in #7924.  Looks like we forgot to update the docs.  @tlively

**Comment by sbc100** [comment]
Actually `git grep emmintrin` reveals some other places that we should probably clean up too.

**Comment by GeorgeLyon** [comment]
Does this mean there isn’t any way to compile existing libraries that use SSE using emscripten? Given that autovectorization has some pretty mixed results it seems better to take a performance hit and keep a single codepath rather requiring two codepaths or having to rely on autovectorization.

**Comment by sbc100** [comment]
Perhaps the discussion on #7924 will help answer you question, and you could follow up there?
