### ISSUE TITLE
Generated source-map (.wasm.map) contains mixture of '/' and '\' in sources

### ISSUE THREAD

**Issue by hkleynhans** [emscripten-core/emscripten#8577]
When generating a source-map (using `-g4`) the list of `sources` contain paths with a mixture of `/` and `\` in a single file name, e..: `../src/something/other\than\bla.cpp`

The '\` characters are not escaped which also seems to create issues when loading the source-map file.  It would be great if the paths could be normalized to _always_ use '/'

Environment:
Windows 10
MSYS
emscripten 1.38.30 installed via emsdk, `activate` called from `MSYS`.
ninja 1.9  (Windows Native, not MSYS built)
cmake 3.14.3 (Windows Native, not MSYS built)

**Comment by hkleynhans** [comment]
Nobody is looking at this as far as I can tell.

**Comment by dschuff** [comment]
This is going to be challenging because IIRC some of these come from LLVM itself, while some come from emscripten. But I would be willing to take patches that fix this if it didn't cause too much complexity in emscripten.
