### ISSUE TITLE
source maps not properly generated?

### ISSUE THREAD

**Issue by nedres** [emscripten-core/emscripten#8584]
Hi,

I'm using `emscripten-1.38-31` and `clang-e1.38.31-64bit`.

I'm compiling with `-g4 -s WASM=0` to get source maps, expecting to set breakpoints in C++ code using the Chrome developer tools, and linking with ` -g4 --source-map-base http://localhost:8000/`

I end up with an output directory with like { `PROJECT.asm.js`, `PROJECT.data`, `PROJECT.html`, `PROJECT.html.map`, `PROJECT.js` }.

`PROJECT.html.map` has a single line: `{"version":3,"sources":[],"names":[],"mappings":"","file":"D:/dev/Build/Output/PROJECT.html"}`.

Does it seems wrong that there are no sources listed?  After adding my source directory to Chrome's dev tools, the console output lines have links to the .html file, not the original source, and my breakpoint doesn't get hit.

Is there a step I'm missing?

**Comment by nedres** [comment]
Part of the problem is that I was both compiling and linking with `-g4`.  Compiling with `-g` and linking with `-g4` results in proper `*.html.map` files. But, console links are still into the html file, and breakpoints in C++ code aren't hit.

**Comment by nedres** [comment]
A simple hello-world program works correctly, stopping at breakpoints as expected.

With our larger project, behavior is inconsistent from run to run.  In both Firefox and Chrome, sometimes a breakpoint gets hit-- the one in `main()' most often.  Often no breakpoints are hit.  In some files, Chrome adds breakpoints on different lines than requested. In Firefox, loading source files sometimes works but sometimes hangs.

The project uses dynamic linking and has output files in subdirectories away from the source files, which may be a factor.  Also many functions are inlined, although I don't see a definite difference between inlined code and regular .cpp files.

**Comment by kripken** [comment]
It sounds like these are browser bugs that we should file in their trackers, with testcases.

**Comment by derofim** [comment]
Try to set

**Comment by derofim** [comment]
also check other settings breaking source maps, like emterpreter https://github.com/emscripten-core/emscripten/issues/5862

**Comment by nedres** [comment]
Still looking into this, but I have noticed a problem with the `--profiling` flag.

This works:
`emcc -g4 hello.cpp -o hello.html -s WASM=0`

This does not (source file isn't loaded):
`emcc -g4 hello.cpp -o hello.html -s WASM=0 --profiling`

**Comment by kripken** [comment]
Thanks @nedres, that looks like a bug with `--profiling`. Fix in #8663

**Comment by nedres** [comment]
Great, thanks for the quick turnaround!

**Comment by nedres** [comment]
Our project uses 2-stage compilation: `.cpp` -> `.o`, then `.o`->`.html`.  On the way the source maps break-- if I build in one step `.cpp`->`.html`, source map debugging works.

I'm using the same clang flags and emcc `-s` symbols at both stages.  I remember reading that mattered, though I can't find the reference now.

Is 2-stage build + source maps expected to work?  It did for us at one time but perhaps that was just luck?

**Comment by nedres** [comment]
Actually `SAFE_HEAP` seems to be the problem, even with single-stage build.  This causes broken debugging in Chrome and Firefox:

`emcc -g4 hello.cpp -o hello.html -s WASM=0 -s SAFE_HEAP=1`

Removing `SAFE_HEAP` from our more complex build also fixes source map debugging.

**Comment by kripken** [comment]
That's a known issue - SAFE_HEAP is implemented by running some JS  transformations on the JS. That breaks source maps. We should probably issue a warning or document this. (Did it not warn?)

**Comment by nedres** [comment]
Aha, good to know.  It did not warn.  (also a google search on `site:emscripten.org "SAFE_HEAP"` doesn't mention it).

**Comment by kripken** [comment]
Actually that might work with the upstream LLVM backend, which we plan to switch to soon. Would be good to test there (can currently use `emsdk install latest-releases-upstream`, see https://groups.google.com/forum/#!topic/emscripten-discuss/WhDtqVyW_Ak).
