### ISSUE TITLE
Closure tests fail with EMCC_DEBUG=2

### ISSUE THREAD

**Issue by rianhunter** [emscripten-core/emscripten#8610]
Tests like `other.test_emcc_5` fail if `EMCC_DEBUG=2` because running optimization passes one by one breaks an invariant.

https://github.com/emscripten-core/emscripten/blob/ac0af50dc77eafa6239ccacea4d3e30e94510b23/emcc.py#L276

`js_optimizer.run_on_js()` expects `EMSCRIPTEN_GENERATED_FUNCTIONS` to be present in the input js, but that isn't the case after running the closure compiler in a previous run.

The failure is:

    shared:ERROR: Invalid input file. Did not contain appropriate markers. (start_funcs: 8532, end_funcs: 56031, suffix_start: -1

I'm not sure what the best way to fix this. I think Ideally the test for `EMSCRIPTEN_GENERATED_FUNCTIONS` would be skipped if the optimization pass does not require it, but I'm not totally sure when that is.

**Comment by kripken** [comment]
Yeah, this isn't easy to fix. Probably not that important - EMCC_DEBUG=2 is useful for debugging only in rare casees I think.
