### ISSUE TITLE
fatal error: 'emscripten/fetch.h' file not found #include <emscripten/fetch.h>

### ISSUE THREAD

**Issue by khmmarket** [emscripten-core/emscripten#8611]
I try compile https://github.com/dreamlayers/em-dosbox and see this error. (Emscripten Version 1.38.31) Earlier i  used Emscripten Version 1.38.21 and all was ok.

/usr/share/emscripten/em++ -DHAVE_CONFIG_H -I. -I../..  -I../../include   -O3  -s USE_SDL=2 -MT dos_programs.o -MD -MP -MF .deps/dos_programs.Tpo -c -o dos_programs.o dos_programs.cpp
WARNING  root: Assigning a non-existent settings attribute "USE_SDL"
WARNING  root:  - did you mean one of USE_BSS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
dos_programs.cpp:28:10: fatal error: 'emscripten/fetch.h' file not found
#include <emscripten/fetch.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
Makefile:383: recipe for target 'dos_programs.o' failed
make[4]: *** [dos_programs.o] Error 1

**Comment by sbc100** [comment]
Can you run with EMCC_DEBUG=1?

The USE_SDL warning is very strange.  Can you verify that USE_SDL is listed in your `src/settings.js` file?  Can you verify that `system/include/emscripten/fetch.h` exists in your emscripten directory?

**Comment by khmmarket** [comment]
I checked src/settings.js and system/include/emscripten/fetch.h. Both files are exist.

running with EMCC_DEBUG=1:

/usr/share/emscripten/em++ -DHAVE_CONFIG_H -I. -I../..  -I../../include   -O3  -s USE_SDL=2 -MT dos_programs.o -MD -MP -MF .deps/dos_programs.Tpo -c -o dos_programs.o dos_programs.cpp
DEBUG    root: PYTHON not defined in ~/.emscripten, using "/usr/bin/python"
DEBUG    root: JAVA not defined in ~/.emscripten, using "java"
DEBUG    root: PYTHON not defined in ~/.emscripten, using "/usr/bin/python"
DEBUG    root: JAVA not defined in ~/.emscripten, using "java"
WARNING  root: invocation: /usr/share/emscripten/emcc -DHAVE_CONFIG_H -I. -I../.. -I../../include -O3 -s USE_SDL=2 -MT dos_programs.o -MD -MP -MF .deps/dos_programs.Tpo -c -o dos_programs.o dos_programs.cpp  (in /home/alex/emsdk/emscripten/1.38.31/tests/em-dosbox-em-dosbox-svn-sdl2/src/dos)
WARNING  root: LLVM version appears incorrect (seeing "", expected "3.4")
INFO     root: (Emscripten: Running sanity checks)
WARNING  root: Assigning a non-existent settings attribute "USE_SDL"
WARNING  root:  - did you mean one of USE_BSS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
DEBUG    root: compiling to bitcode
DEBUG    root: emcc step "parse arguments and setup" took 0.02 seconds
DEBUG    root: compiling source file: dos_programs.cpp
DEBUG    root: running: /home/alex/emsdk/clang/e1.38.31_64bit/clang++ -target le32-unknown-nacl -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=22 -D__EMSCRIPTEN_tiny__=1 -fno-math-errno -DEMSCRIPTEN -D__EMSCRIPTEN__ -fno-math-errno -U__native_client__ -U__pnacl__ -U__ELF__ -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/usr/share/emscripten/system/local/include -Xclang -isystem/usr/share/emscripten/system/include/compat -Xclang -isystem/usr/share/emscripten/system/include -Xclang -isystem/usr/share/emscripten/system/include/emscripten -Xclang -isystem/usr/share/emscripten/system/include/libc -Xclang -isystem/usr/share/emscripten/system/lib/libc/musl/arch/js -Xclang -isystem/usr/share/emscripten/system/include/gfx -Xclang -isystem/usr/share/emscripten/system/include/SDL -Xclang -isystem/usr/share/emscripten/system/include/libcxx -D__IEEE_LITTLE_ENDIAN -DHAVE_CONFIG_H -I. -I../.. -I../../include -O3 -MT dos_programs.o -MD -MP -MF .deps/dos_programs.Tpo -c -mllvm -disable-llvm-optzns -std=c++03 -emit-llvm -c dos_programs.cpp -o dos_programs.o -nostdinc++
dos_programs.cpp:28:10: fatal error: 'emscripten/fetch.h' file not found
#include <emscripten/fetch.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
Makefile:383: recipe for target 'dos_programs.o' failed
make[4]: *** [dos_programs.o] Error 1

**Comment by sbc100** [comment]
Somehow it looks like you are using an ancient version of emscripten.  It looks like maybe 1.22.1 based on the valued of __EMSCRIPTEN_major__ being passed on the command line.    That version is from 2014.   

What does /usr/share/emscripten/emscripten-version.txt say?  I think perhaps you PATH is pointing the wrong emscripten location?

**Comment by khmmarket** [comment]
Yes its realy true 1.22.1 version, thank you! But then why old version left? I did
git reset --hard
git pull
./emsdk update-tags
./emsdk install latest
./emsdk activate latest

**Comment by khmmarket** [comment]
Ok I'll deal with this. Thanks again
