### ISSUE TITLE
OSError: [Errno 8] Exec format error while excuting command: emcc -v

### ISSUE THREAD

**Issue by Y0QIN** [emscripten-core/emscripten#8612]
emsdk version:1.38.31-64bit.  python 3.7.3
Error output:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.31
Traceback (most recent call last):
  File "/root/emsdk/emscripten/1.38.31/emcc.py", line 3308, in <module>
    sys.exit(run(sys.argv))
  File "/root/emsdk/emscripten/1.38.31/emcc.py", line 477, in run
    code = run_process([shared.CLANG_CC, '-v'], check=False).returncode
  File "/root/emsdk/emscripten/1.38.31/tools/shared.py", line 163, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/emsdk/clang/e1.38.31_64bit/clang'

**Comment by sbc100** [comment]
What happens when run `/root/emsdk/clang/e1.38.31_64bit/clang` directly?

What does `file /root/emsdk/clang/e1.38.31_64bit/clang` say?

**Comment by Y0QIN** [comment]
@sbc100 
emcc /root/emsdk/clang/e1.38.31_64bit/clang
shared:ERROR: '/root/emsdk/clang/e1.38.31_64bit/clang++ --version' failed: [Errno 8] Exec format error: '/root/emsdk/clang/e1.38.31_64bit/clang++'

**Comment by sbc100** [comment]
And what does  `file /root/emsdk/clang/e1.38.31_64bit/clang` output?

What environment are you working in?  I imagine its some kind of container based on the fact that you installed in "/root"?   Are you maybe trying to use 64-bit binaries on a 32-bit distro?   That seems like likely.  You will either need a 64-bit container or install the 32-bit version of the SDK (if there is one).

**Comment by Y0QIN** [comment]
emm,I seem to be mistaken for the Linux operating system type.I‘ll intstall the 32-bit version and reply later

**Comment by Y0QIN** [comment]
@sbc100 I installed and excuted command emcc -v successfully~

**Comment by LucienXian** [comment]
@Y0QIN How do you solved the problem? I met the same problem.

**Comment by LucienXian** [comment]
@sbc100 Hi, I met the same problem.But my docker image is 64-bit version.
Type:
`file /bin/bash`
Output:
`/bin/bash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32`

**Comment by sbc100** [comment]
@LucienXian, are you sure its the same issue?  Does running `file` on you clang say its also 64-bit?  And is you seeing "OSError: [Errno 8] Exec format error: '?

Perhaps open another issue, and include the full command you typed, along with the full output, and also the contents of your `.emscripten` file?

**Comment by Y0QIN** [comment]
@LucienXian I  intstalled the 32-bit  emsdk version,then this problem solved.
I have encountered this problem because I mistakenly think that I am a 64-bit Linux system, it is actually 32-bit.
Since you are a 64-bit system, the problem you are experiencing should be different from mine.

**Comment by Y0QIN** [comment]
@LucienXian Maybe you can have a try to install the 32-bit emsdk version.
And since the BINARYEN_ROOT defaults to the 64-bit binaryen library,maybe you should excute:
grep BINARYEN_ROOT ~/.emscripten BINARYEN_ROOT = '/root/emsdk/binaryen/tag-xxxx_32bit_binaryen'
