### ISSUE TITLE
EMTERPRETIFY stack corruption

### ISSUE THREAD

**Issue by evgeny-g** [emscripten-core/emscripten#8614]
Hi,
I have C++ application compiled with emscripten and adopted for it. It works well when compiled with ASYNCIFY=1 option, but I got other problem with ASYNCIFY so I decided to switch to EMTERPRETIFY(ASYNC)=1 mode. But when my code was compiled with EMTERPRETIFY=1 and EMTERPRETIFY_ASYNC=1 options as well as with and without EMTERPRETIFY_LIST and WASM=0 or WASM=1 I got strange errors. Sometimes "this" pointer inside class equal zero, sometimes some other pointers inside equal zero or some wrong value. I tried to research and found that behaviour depends from a lot of different options. In some cases OUTLINING_LIMIT can help, but in other cases changing Os to O0 or set alignment for class help. And I didn't find right way how to fix it and avoid such troubles in all parts of code. 
Also prepared Unit test(based on gtest) and tried to pass allocated buffer to two different coroutines, it failed(one coroutine was not able to read data that was written by another coroutine). But after compilation it with -O0 it works! But when I created simple app based on that UT it works with -O0 and -Os too.
It looks like complex problem with emterpreter and|or our code, but may be you can advise right way for fixing it.
thank you.

**Comment by kripken** [comment]
The best thing is to provide us with a small testcase, then we can debug and fix it hopefully.
