### ISSUE TITLE
When I link with -s ALLOW_MEMORY_GROWTH=1 -s USE_PTHREADS=1 Chrome brower will hang.

### ISSUE THREAD

**Issue by briangavin** [emscripten-core/emscripten#8616]
When I link with the following setting -s USE_PTHREADS=1 and -s ALLOW_MEMORY_GROWTH=1 the Chrome brower to hang with version 1.38.31 of Emscripten.   I run the same wasm generated file on Firefox Nightly with shared memory turn on it works.   

I tried Chrome version 74.0.3729.131 and Chrome Canary(5/15/2019) and both browser hung and eventually had an unresponsive web page error.   No additional errors were printed in the browser console.   My application uses threading and if I turn off shared memory it will run.

**Comment by kripken** [comment]
This might be a browser bug - we need a testcase to investigate it, though. There are no open issues that sound related.

**Comment by VirtualTim** [comment]
Possibly due to:
https://bugs.chromium.org/p/chromium/issues/detail?id=877055
or
https://bugs.chromium.org/p/chromium/issues/detail?id=935169

**Comment by dschuff** [comment]
Pthreads + growable memory doesn't work in Chrome right now.
https://bugs.chromium.org/p/v8/issues/detail?id=8564 is probably the bug you should follow for that.

**Comment by kripken** [comment]
I believe all known issues with pthreads+growth have been fixed in chrome, closing.
