### ISSUE TITLE
IDBFS operations not working inside pthreads

### ISSUE THREAD

**Issue by TuckWa** [emscripten-core/emscripten#8624]
Is there a known issue with trying to sync and use directories/files with the IDBFS while in a pthread?
I've been fighting to get persistence working and it works until I change to run everything in a pthread. I decided to just make a small testcase following the example:

- FS.mkdir a couple directories and FS.mount them to IDBFS
- FS.syncfs from the browser storage and call a test function
- test function checks for files and creates them if they don't exist, then FS.syncfs back to the browser and call a success function

This works fine when compiled and ran normally, but when compiled with -s PROXY_TO_PTHREAD it blows up; creating the files fails with "No such file or directory"
I have tried a few different combinations, like running the mkdir/initial sync in the main thread, then spawning a pthread to do the rest of the work, and this runs, but the IDB never actually gets any data pushed to it. 
Am I expected to run all FS.* calls in the main thread, and if so how is that done if the entire program is running within various pthreads?

**Comment by kripken** [comment]
I believe this is a current limitation. The FS.* API is in JS, and that means it can't be shared among threads. So a pthread can't access the same FS.* as the main thread can. We create the filesystem in the main thread, so pthreads can't access it, basically.

We should probably add assertions against FS access in pthreads, as this can be confusing.

Note that C access to the filesystem will work, using normal pthreads operations - we proxy operations transparently to the main thread.

**Comment by TuckWa** [comment]
Thanks for the response. 
Right, I've noticed that I can create/mount directories to the IDBFS on the main thread, and can create/access(creat, open, write etc)  files in those directories from a different thread. 

Would the current way to work in this scenario be to, instead of having main exit with live runtime after creating threads, have my main() just lie dormant and periodically do the FS.syncfs itself? I haven't tested this exact case but I'm assuming that the FS would have knowledge of those files that were created/modified on other threads.
Going off of that, if I register a beforeunload callback, does that run on the main browser thread, allowing me to sync before the page is closed?

**Comment by kripken** [comment]
Keeping the main thread around to handle FS operations is the safest thing, yeah, and to proxy all requests to it.
