### ISSUE TITLE
Some assertions are not in an #if ASSERTIONS block

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8629]
This means that compiling with `-s ASSERTIONS=0` will still generate some assertions.
Eg: https://github.com/emscripten-core/emscripten/blob/e33390fb48bea846022875efa15cef5cf06e4ba1/src/preamble.js#L654

Is this something that's intentional? Is it worth changing?

**Comment by kripken** [comment]
In general, I think we try to put assertions behind an ifdef with that flag when (1) they are of minor importance (super-important ones on the other hand might be useful even in release builds), and (2) where it matters more for code size (like in code that is included in all builds). So this isn't a clear-cut distinction.

Perhaps we should instead do something like make the optimizer strip out `assert()` calls automatically (and asserts we want to keep we'd rename to `releaseAssert` or something like that). Then we can get rid of the ugly ifdefing.
