### ISSUE TITLE
dynamicAlloc() doesn't work with memory growth

### ISSUE THREAD

**Issue by kichikuou** [emscripten-core/emscripten#8637]
Emscripten 1.38.31

main.c:
```C
int main() {
}
```
post.js:
```JavaScript
for (var i = 0; i < 3; i++) {
    var buf = getMemory(10000000);
    console.log(buf);
}
```

```shell
$ emcc -s ALLOW_MEMORY_GROWTH=1 main.c --post-js post.js -o out.js
$ node out.js
5246848
15246848
15246848
```
Note that second and third `getMemory()` calls return the same pointer.

This is because `dynamicAlloc()` doesn't update `HEAP32[DYNAMICTOP_PTR>>2]` when the heap is resized.

https://github.com/emscripten-core/emscripten/blob/46a5d4672344d5d0704cfff9c968e6e49d47130d/src/support.js#L31-L42

It seems like a bug introduced by https://github.com/emscripten-core/emscripten/pull/7897.

**Comment by kripken** [comment]
Thanks, I opened #8643 to throw a clear error on this. More details there.
