### ISSUE TITLE
A suggestion about generated_struct_info.json

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#8646]
Hi again, everyone.

I was wondering if there could be just one generated_struct_info.json for the Wasm backend and one for the Fastcomp backend that would be cached for each subsequent build for either corresponding backend.  And it should also be possible to use the Linux version of the file on Windows.  I want to try this on mine and see if it works, for my current problem with the temporary JS file and gen_struct_info.py.  I can try it with the one I have on my WSL Linux distro.  I don't want to try it until I know it's supported because I'm worried that if I try it right now, the .json file from the WSL will be overwritten by the one it'll try to generate when I try to build C/C++ code on Windows using the Wasm backend.

I'd also like some help on the issue I talked about in the new thread I recently opened on the emscripten-discuss Google Group ([this one](https://groups.google.com/forum/#!topic/emscripten-discuss/crK6qwaVe_Q)).

**Comment by DragonOsman** [comment]
I just want to see what that does for the temporary JS file.

**Comment by sbc100** [comment]
I'm not sure I understand exactly.   IIUC your failure is during the generation of the struct_info file.   The js file is question is supposed to generate the file but is returning non-zero instead.  if you copy over an existing struct_info file, that part of the build won't even run because the system will think the struct_info is up-to-date.    

So it will (hopefully) simply skip over your problem..

**Comment by DragonOsman** [comment]
The JS file seem to be a temporary file it uses to test the Wasm module.  The extension of the file that's left behind in the Temp folder is even .wasm.o.js, and the code in there is Wasm loading code.  I'm not sure if that's also the case for the original temporary file that isn't there anymore but had the same name as the .wasm.o.js one, but yeah.

**Comment by DragonOsman** [comment]
Something I noticed that I don't like: whenever I try to set a C++ flag, even if I set C++14 or C++17 Emscripten still passes the `-std=c++11`  flag when invoking Clang.  Is there no way to get around this?

**Comment by DragonOsman** [comment]
It didn't work.  It still tries to generate it again and runs into the same error.  There's a need to make it not generate it again if it's already there.  Though be sure to keep the ones for the Fastcomp and Wasm backends, respectively, separate (maybe in separate locations?).

**Comment by DragonOsman** [comment]
By the way, after passing the `-s DEMANGLE_SUPPORT=1` setting to Emscripten, where am I supposed to use the JS function `demangle`?  In my C++ code itself?
