### ISSUE TITLE
Problems with abs(1.0) as exponent in pow function with O2 enabled under iOS Safari 12.2 and 12.3 Beta 6

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#8647]
This seems very specific and very odd to me:

But somewhere between Emscripten 1.38.6 and 1.38.30 something changed with the code generation for web assembly which breaks the power function.

```
void pow_test(double exp) {
  printf("pow(10, %f): %f\n", exp, pow(10.0, exp));
}
```

When exp is either 1.0 or -1.0 the pow function returns 0. I was only able to reproduce this on iOS devices and with O2 optimisations. I will investigate further but maybe someone knows already more about this than me.

**Comment by kripken** [comment]
We have had some reports of odd behavior on Safari, like https://github.com/WebAssembly/binaryen/issues/2096 , but it's been hard to a good small testcase to file for WebKit. If you can get such a testcase that would be great!

**Comment by juj** [comment]
Which Safari version do the issues occur on? There is one option in src/settings.js to work around a Safari 9 issue - though perhaps this issue is also with latest Safari, or?

**Comment by fibbo** [comment]
@kripken What do you exactly need for a test case? Is a wasm file with exported function enough?

@juj I tried latest i.e. iOS 12.3

**Comment by kripken** [comment]
@fibbo the best testcase is a small program that can be run with jsc (the WebKit shell program) that shows the bug in a clear way. A program that runs as an html page is also reasonable.

**Comment by fibbo** [comment]
@kripken I uploaded a small test program on github. I'm not familiar with jsc so I set up an html page example. Let me know if this helps: https://github.com/fibbo/safari_wasm_bug

**Comment by kripken** [comment]
Thanks @fibbo, looks like a good bug report to me! I cc'd myself on the webkit tracker. Hopefully they can get to this soon.

**Comment by fibbo** [comment]
This has been resolved with https://bugs.webkit.org/show_bug.cgi?id=198106
