### ISSUE TITLE
dict_values' object does not support indexing

### ISSUE THREAD

**Issue by ajit3259** [emscripten-core/emscripten#8656]
./emsdk install latest
Traceback (most recent call last):
  File "./emsdk", line 2605, in <module>
    sys.exit(main())
  File "./emsdk", line 2369, in main
    load_sdk_manifest()
  File "./emsdk", line 1977, in load_sdk_manifest
    elif '%releases-tag%' in t.version: expand_category_param('%releases-tag%', releases_tags, t, is_sdk=False)
  File "./emsdk", line 1933, in expand_category_param
    ver = category_list[i]
TypeError: 'dict_values' object does not support indexing

**Comment by sbc100** [comment]
Looks like category_list is supposed to be list here.  

Would you mind re-opening this issue against https://github.com/emscripten-core/emsdk?

**Comment by ajit3259** [comment]
Added it to https://github.com/emscripten-core/emsdk
