### ISSUE TITLE
Build is broken after emscripten update with 'symbol multiply defined'

### ISSUE THREAD

**Issue by ebraminio** [emscripten-core/emscripten#8658]
Hey there, I am using Manjaro (Arch based) emscripten build nowadays but after an update I am unable to build this repo https://github.com/harfbuzz/harfbuzzjs (easy to use, clone it, install Google Closure or remove `--closure 1`, issue `./build.sh`) with this result,

```
[57/57] Linking CXX executable harfbuzzjs.js
FAILED: harfbuzzjs.js 
: && /usr/lib/emscripten/em++  -std=c++11 -s MODULARIZE=1   -s NO_FILESYSTEM=1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s STRICT=1   -Oz --closure 1 -s "EXPORTED_FUNCTIONS=['_hb_version_string',   '_malloc', '_hb_blob_create', '_hb_face_create', '_hb_font_create',   '_hb_buffer_create', '_hb_buffer_add_utf8', '_hb_buffer_guess_segment_properties',   '_hb_buffer_set_direction', '_hb_shape', '_hb_buffer_serialize_glyphs',   '_hb_buffer_get_length', '_hb_buffer_serialize_glyphs', '_hb_buffer_destroy',   '_hb_font_destroy', '_hb_face_destroy', '_hb_blob_destroy', '_hb_blob_get_length',   '_hb_direction_from_string', '_hb_font_set_scale', '_free']"     -o harfbuzzjs.js  harfbuzz/libharfbuzz.a && :
error: Linking globals named '_Z34hb_aat_layout_find_feature_mappingj': symbol multiply defined!
shared:ERROR: Failed to run llvm optimizations: 
ninja: build stopped: subcommand failed.
```

Why is that? We don't have the mentioned issue, we are running the same cmake in our CI for many different build environments and it feels this is emscripten specific and a recently introduced regression also.

**Comment by sbc100** [comment]
That error is coming from llvm-link or opt.  Looks like its trying to combine all the bitcode objects and it s seeing two different strong definition of `hb_aat_layout_find_feature_mapping(unsigned int)`.

You say you noticed this after and update?   And update of what exactly?   When did this use to work?  It could be that https://github.com/harfbuzz/harfbuzzjs needs patching..

**Comment by ebraminio** [comment]
After emscripten update (`pacman -Suy` on Manjaro) I am seeing the issue, pretty sure no other change has happened, we have different cmake CI builders, one asmjs even, on harfbuzz project and harfbuzzjs is using very similar scripts on harfbuzz so I think it is some change from emscripten or its packaging that caused this.

**Comment by ebraminio** [comment]
Pretty sure it used to work on 1.38.30-2 but broke 1.38.31-1, I issued `emcc --clear-cache` also right with no luck
```
[2019-05-17 15:46] [ALPM] upgraded emscripten (1.38.30-2 -> 1.38.31-1)
[2019-05-17 15:46] [ALPM-SCRIPTLET] => You may need to manually clear your emscripten cache as clang may not link
[2019-05-17 15:46] [ALPM-SCRIPTLET] => the new library versions with cached data properly. Use this command:
[2019-05-17 15:46] [ALPM-SCRIPTLET]    $ emcc --clear-cache
```

**Comment by sbc100** [comment]
I assume you are using the fastcomp backend?   I can't think of any changes that might cause this between .30 and .31.    Can you take a look at why `_Z34hb_aat_layout_find_feature_mappingj` might be reported as multiply defined?   perhaps search you input bitcode files for definitions of this symbol?    Otherwise you could try using emscripten from git and bisecting between .30 and .31 I guess?

**Comment by ebraminio** [comment]
Just downgraded the package using `sudo pacman -U /var/cache/pacman/pkg/emscripten-1.38.30-2-x86_64.pkg.tar.xz` command (from 1.38.31, and did it multiple times) and was able to compile the package. Not saying it is necessarily emscripten bug as it can be packaging issue also

**Comment by sbc100** [comment]
Can you take a look at "_Z34hb_aat_layout_find_feature_mappingj"  perhaps there is some reason why it might be reported as multiply defined?  Might give us a clue.

**Comment by ebraminio** [comment]
I think that is not the issue even, I should do the thing you said of course and bisecting but can't do it right now as I am seeing not some Google Closure issues

**Comment by sbc100** [comment]
It might not be your fault or the fault of harfbuzzjs but somehow llvm is seeing two different definitions for that symbols.   So it as at least the why the is manifesting.   It would be interesting, for example, to know which input object files contain the two different definitions.    You could use llvm-nm to determine this.  It might provide some clue.

**Comment by ebraminio** [comment]
Ok, the issue is if I remove `-s NO_FILESYSTEM=1` Google Closure work correctly again but I will have harfbuzzjs.js growing from 10kb to 25kb, only on 1.38.31

**Comment by ebraminio** [comment]
Lets close this, it should be easy to fix I guess

**Comment by ebraminio** [comment]
https://github.com/emscripten-core/emscripten/issues/8677 and sorry for the confusing file bug, I hope the newer would be better.
