### ISSUE TITLE
Version tagging with the new emscripten-releases build infrastructure

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8660]
Until now, to tag a new version we tagged the emscripten, emscripten-fastcomp, emscripten-fastcomp-clang, and binaryen repos. Then the builder would see that tag and create a build. And each repo knew which version it was using either the git tag, or the checked-in `emscripten-version.txt` file (which exists in the first three repos, but we never added one to binaryen).

With the new emscripten-releases infrastructure, we can actually see that a build passes tests on all platforms before saying it is a new tagged version. The emscripten-releases repo rolls in git hashes as the various repos get updated, and when we see a line of all green builds, we can decide that is a new version. And the emsdk repo has a metadata file that maps hashes in emscripten-releases to version numbers, so that when a user requests a version, we know what to download. But that doesn't answer what to do (if anything) for tagging repos. In particular, we can't update `emscripten-version.txt` before we see the green builds, and we can't update it later as that would be too late. So what `emcc -v` reports is unclear.

## Proposal

 * We remove the `emscripten-version.txt` file from all repos.
 * `emcc -v` reports "dev version" (or "no version"?) if it sees no file there, which will be the default in git clones.
 * When the emsdk unpacks a build, it emits an `emscripten-version.txt` file with the tag, which could be a version number, in which case `emcc -v` will report the expected thing. If the emsdk was used to get an arbitrary build from emscripten-releases, identified only by the hash from that repo, then the tag would be that hash, and `emcc -v` would report it since it just reads that `.txt` file. The hash would be useful like a version number in that it has an unambiguous mapping to versions of all other repos, using the deps info in emscripten-releases.

And the process for making a new release tag would be something like: see that all emscripten-releases builds are green for a hash, also see there is no known breakage on github CI (which also has browser tests and some more coverage). Open a PR to the emsdk repo to update `emscripten-releases-tags.txt` with an entry for the new release and its hash. We can optionally git tag repos, but since we can't tag some anyhow (like LLVM) this seems unimportant.

**Comment by sbc100** [comment]
I kind of like that tagging of the repos.  So I think the release process should include tagging of any repos where it makes sense. 

That way emcc.py can in a clean git checkout can still use this to report something somewhat useful like "1.30.38+git".

Other than that this seems reasonable.  I'm happy to get rid of the emscripten-version.txt text file from git, especially if it duplicates information already in the tags.

**Comment by kripken** [comment]
I agree tagging the repos can be useful - for bisection for example. But I'm a little worried about inferring the last version number from a tag. It seems like we'd do this by seeing if the tag is in the git history? Merges etc. might make that complicated. Or is there some git utility that makes that straightforward and unambiguous?

Another worry I have is that we would add the tags some time after the commit -  hours (or days) can pass until the builds turn green and we decide to tag that version. As a result a user doing `emcc -v && git fetch && emcc -v` may get different results the second time, just because of fetching the tag metadata.

**Comment by sbc100** [comment]
OK, we can skip reported the latest version in `emcc -v` for git users.
