### ISSUE TITLE
Feature Request: Improve warning 'unexpected number of arguments'

### ISSUE THREAD

**Issue by d3x0r** [emscripten-core/emscripten#8661]
```
warning: unexpected number of arguments 1 in call to 'GetInterfaceDbg', should be 3
warning: unexpected number of arguments 4 in call to 'AddTimerExx', should be 6
warning: unexpected number of arguments 2 in call to 'AddLinkEx', should be 4
warning: unexpected number of arguments 1 in call to 'GetInterfaceDbg', should be 3
... +200
```

It would be nice to know which module being linked had the issue.  These arise because of a mis-definition between debug and non-debug modes.  (debug routines take extra `__FILE__,__LINE__`) arguments. Maybe what the name of the function with the call is?

```
emcc -s WASM=1 -g -D_DEBUG -D__NO_OPTIONS__ -D__NO_ODBC__ -D__WASM__ -D__LINUX__ -DMAKE_RCOORD_SINGLE -D__STATIC_GLOBALS__ -DSUPPORT_LOG_ALLOCATE -DDEFAULT_OUTPUT_STDERR  loader.c  
    jpeg9.lo png.lo zlib.lo freetype.lo imglib_puregl2.lo  vidlib_puregl2.lo  genx.lo expat.lo psi.lo   sack_ucb_full.c -o x.js 
```

**Comment by kripken** [comment]
I think those warnings are arriving from asm2wasm - we are replacing it by default soon with the LLVM wasm backend, which will have different warnings. So probably not worth fixing asm2wasm, but we should see what the wasm backend warns on that and make sure that's clear.

**Comment by d3x0r** [comment]
Okay, sounds good.  
If you like I can make a small example ... maybe something like...
``` c
int f( int a, int b, int c ) {
   return 0;
}
int main() { 
    return ((int(*)(int)f)(1);
}
```

**Comment by sbc100** [comment]
Closes since as alon says we probably are not going to fix this in asm2wasm at this point.  This is also undefined behaviour in C so you its probably worth warning about and/or fixing (although lots of existing code does this its hard to make such code work with wasm where function signatures are first class in the format).

**Comment by d3x0r** [comment]
Yes, I don't exact it to work, I expect it to fail with useful errors like module/file/function even line might be available... 
It's come up purely because I forgot in the first pass to define _DEBUG, and I don't know which one I missed.... if i take out any one of them, then they fail earlier with missing functions, so a binary search isn't possible.... (Just sayin...)

**Comment by sbc100** [comment]
Sorry, I didn't mean to suggest that the request for better error messages here is not valid.  Just that we are currently focused on the llvm backend now and not fastcomp so this is unlikely to get fixed.  I you want to look into fixing it yourself feel free to do so and re-open this issue.
