### ISSUE TITLE
emar adds object files twice

### ISSUE THREAD

**Issue by digimatic** [emscripten-core/emscripten#8670]
The latest commit of emar.py (d8d121ee63dc7bc9dff38c3ffb5a3e319456560a) causes entries to be duplicated instead of replaced.

Example:
$ rm -f lib/libCore.a
$ emar rc lib/libCore.a Mobile/Core/CMakeFiles/Core.dir/src/Runtime.cpp.o
$ emar tv lib/libCore.a
rw-r--r-- 0/0 2905028 1970-01-01 01:00:00.000000000 Runtime.cpp.o
$ emar rc lib/libCore.a Mobile/Core/CMakeFiles/Core.dir/src/Runtime.cpp.o
$ emar tv lib/libCore.a
rw-r--r-- 0/0 2905028 1970-01-01 01:00:00.000000000 Runtime.cpp.o
rw-r--r-- 0/0 2905028 1970-01-01 01:00:00.000000000 Runtime_3bf7fd6a.cpp.o
$ emar rc lib/libCore.a Mobile/Core/CMakeFiles/Core.dir/src/Runtime.cpp.o
$ emar tv lib/libCore.a
rw-r--r-- 0/0 2905028 1970-01-01 01:00:00.000000000 Runtime.cpp.o
rw-r--r-- 0/0 2905028 1970-01-01 01:00:00.000000000 Runtime_3bf7fd6a.cpp.o

I tested emar.py 965bdd922713d513f1db4146f3d99a3f5077c6fc, and that makes the lib contain  only Runtime_3bf7fd6a.cpp.o.

This causes problem in a normal build cycle. When a .cpp is changed it is recompiled and added into the archive again. But the second time with a new name (mangled). The linker may still resolve using the first object file it finds, that is the old object file. So the final binary is having the old behavior before the cpp was modified..

**Comment by kripken** [comment]
cc @sbc100

**Comment by sbc100** [comment]
Yup, looks like an oversight on my part here.
