### ISSUE TITLE
Can't use STRICT=1 with USE_WEBGL2=1

### ISSUE THREAD

**Issue by jasonsanjose** [emscripten-core/emscripten#8673]
I get the following error for a simple hello world example when combining `USE_WEBGL2=1` with `STRICT=1`. It appears `library_webgl.js` is not included.

```
emcc helloworld.c -s USE_WEBGL2=1 -s STRICT=1
error: failure to execute js library "library_webgl2.js": ReferenceError: createGLPassthroughFunctions is not defined,
error: use -s VERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "ReferenceError: createGLPassthroughFunctions is not defined" | ReferenceError: createGLPassthroughFunctions is not defined
    at eval (eval at load (eval at globalEval (/<path to>emscripten/1.38.31/src/compiler.js:110:8)), <anonymous>:880:1)
    at Object.load (eval at globalEval (/<path to>emscripten/1.38.31/src/compiler.js:110:8), <anonymous>:169:9)
    at JSify (eval at globalEval (/<path to>emscripten/1.38.31/src/compiler.js:110:8), <anonymous>:59:20)
    at Object.<anonymous> (/<path to>emscripten/1.38.31/src/compiler.js:219:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
shared:ERROR: 'node /<path to>emscripten/1.38.31/src/compiler.js /tmp/tmpd0GksE.txt /<path to>emscripten/1.38.31/src/library_pthread_stub.js' failed (1)

```

**Comment by jasonsanjose** [comment]
I believe this problem points back to this PR https://github.com/emscripten-core/emscripten/pull/8059 and perhaps a missing `__deps` declaration for functions like `createGLPassthroughFunctions`.

**Comment by kripken** [comment]
cc @juj who wrote the PR that may have regressed this.

**Comment by juj** [comment]
The error here is a bit peculiar one, although root cause is that instead of `-s STRICT=1 -s USE_WEBGL2=1` one should use `-s STRICT=1 -s USE_WEBGL2=1 -lGL` to link in the WebGL library. Adjusted in PR #8727 that `-s USE_WEBGL2=1` is ignored if `-lGL` is not specified.

**Comment by jasonsanjose** [comment]
Thanks @juj. I tried this but now I'm seeing `emscripten_webgl_create_context` return `0`. Is there something else I can try?

**Comment by juj** [comment]
Try double checking that the DOM target is appropriate for the `emscripten_webgl_create_context` target. Also you can try building with `-s GL_DEBUG=1` linker flag to get more detailed debug prints in web console. If after both of those the issue is still cloudy, try debugging the generated .js file directly, searching for the function `_emscripten_webgl_create_context` there, and trace through that function why it is returning zero. Most likely the canvas target cannot be found, I'd guess.
