### ISSUE TITLE
Release 1.38.32 not available for OSX

### ISSUE THREAD

**Issue by kjpou1** [emscripten-core/emscripten#8684]
Can OSX be updated please?

Reference: https://github.com/emscripten-core/emscripten/issues/8560

**Comment by kripken** [comment]
We are testing new builders, which will hopefully replace the old ones very soon. See details here:

https://groups.google.com/d/msg/emscripten-discuss/WhDtqVyW_Ak/8DfDnfk0BgAJ

The instructions there will download 1.38.33 (first release in the new infra). Please let us know if that doesn't work!
