### ISSUE TITLE
library_glfw.js: The previously set callback not returned

### ISSUE THREAD

**Issue by podsvirov** [emscripten-core/emscripten#8689]
Since 3.0 version the callback registration functions return the previosly set callback. You can look there in `GLFW/glfw3.h` header or in documentation. Current implementation in `library_glfw.js` return nothing.

**Comment by kripken** [comment]
We have some tests on glfw, but maybe not on those callbacks?

**Comment by podsvirov** [comment]
> We have some tests on glfw, but maybe not on those callbacks?

Hi @kripken, I fix `library_glfw.js` and add missing checks to `glfw3.c` for `test_glfw3`. Please review #8782.
