### ISSUE TITLE
Minifying Imports/Exports Across Modules

### ISSUE THREAD

**Issue by awtcode** [emscripten-core/emscripten#8694]
This is a follow-up discussion to #8686. Can we extend the minification of imports and exports to dynamic linking by doing the following:

1. Export the mapping in https://github.com/emscripten-core/emscripten/blob/a3567830e7f489fd4139f3b196c4b31ebed8c293/tools/shared.py#L2612
2. Add an option in Binaryen that takes in the mapping and replaces the names in the side module correspondingly.

@kripken and @sbc100 . WDYT?

**Comment by kripken** [comment]
I think it's possible, and it might be interesting to experiment here, but I do think this is a very specific use case (where you use dynamic linking + you know exactly what will be linked with it at runtime). I don't think I'll have time myself.

**Comment by awtcode** [comment]
No worries @kripken , I'll try it out and keep you updated.

**Comment by sbc100** [comment]
Still worth looking into..
