### ISSUE TITLE
Don't expose data_target/PACKAGE_NAME when loading WASM

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#8698]
We use the `file_packager.py` script to create a small data file. The thing we don't like is that when the Emscripten generated js file loads the .data file it logs it to the `PACKAGE_NAME` to the console. And `PACKAGE_NAME` is `data_target` which is the argument passed to the script.

We call the script from CMake with `${CMAKE_BINARY_DIR}/files.data` as this argument. And this resolves to the full path which we would like to hide (or disable the logging altogether).

Would it be possible to use only the base name of the `data_target`?

**Comment by kripken** [comment]
I think removing any unnecessary logging is probably a good idea. PR would be welcome.

**Comment by gabrielcuvillier** [comment]
Huh, I think a "-v"-like option (ie. "verbose") to keep the logging would have been better, as I find very useful to know what is happening exactly in the JS console (at least with the --use-preload-cache options: is the package is loaded from cache or remote?).  I noticed this changes recently when suddenly nothing was printed anymore :(

Anyway, that is not so much important

**Comment by kripken** [comment]
@gabrielcuvillier If you want this back, i think it would be ok, if we put it behind the `RUNTIME_LOGGING` or `ASSERTIONS` flags (not sure offhand which is better).

**Comment by gabrielcuvillier** [comment]
Yes, RUNTIME_LOGGING could be the way to go.
Actually, I think a lot of devs would love to know what's going on in Emscripten, for debugging purposes: Wasm fetched, compiled, various stuff/subsystems initialized, packages downloaded, and so on
