### ISSUE TITLE
Global Javascript Variables

### ISSUE THREAD

**Issue by ktb92677** [emscripten-core/emscripten#8704]
Hi all! Does anyone know how to handle javascript variables across multiple EM_JS calls?

For example I am using websockets and I want to be able to call websocket.send throughout my code base so I have the following:

```
EM_JS(void, initialize, (), {
	window.WebSocket = window.WebSocket || window.MozWebSocket;
    var websocket = new WebSocket('ws://127.0.0.1:9000',
  								'protocol');
	websocket.binaryType = "arraybuffer";

    websocket.onopen = function () {
    };
    websocket.onerror = function () {
    };

     websocket.onmessage = function (event) {
     };
});


EM_JS(void, send, (int* data), {
	websocket.send(new Uint8Array(HEAPU8.buffer, data, 4));
});
```

But a call to send(int*) says that websocket is undefined... any help would be greatly appreciated!

**Comment by ktb92677** [comment]
Can anyone shed any light on this?

**Comment by sbc100** [comment]
I think each EM_JS function will define its own JS function, which means anything declared as `var` would certainly not be accessible outside.

You could try hanging globals of the Module.  e.g. `Module.mysocket = ` ?    Or use the new globalThis:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis
