### ISSUE TITLE
Change to globalThis from window or global

### ISSUE THREAD

**Issue by adam-cyclones** [emscripten-core/emscripten#8708]
In the compiled output of emscripten JavaScript gluecode, an ENVIRONMENT can be specified to node or browser. 

Despite that setting val.global(""); still refers to window even if called in node and ENVIRONMENT was set to node explicitly.

Now that `globalThis` is a thing, emscripten could use it to refer to `window` or node `global` depending on its environment automatically, maybe `globalThis` could be quickly implemented and potentially reduce guarding logic too.

PS. Happy to raise a PR if I knew what file to edit, to control JavaScript gluecode output.

**Comment by sbc100** [comment]
We should probably do this..

**Comment by kripken** [comment]
@adam-cyclones a PR would be great! the relevant file for this is `src/shell.js` I believe. Otherwise searching in `src/*.js` for `global` should find other places if there are any.

**Comment by adam-cyclones** [comment]
Im so sorry I missed this, I will take a look after work.
