### ISSUE TITLE
EMSCRIPTEN_EVENT_TARGET_* throws with --proxy-to-worker

### ISSUE THREAD

**Issue by Daft-Freak** [emscripten-core/emscripten#8733]
The old `#document`/`#window` still work fine. Can be reproduced by running `test_sdl2_canvas_proxy` with SDL2 master. Looks like `_specialEventTargets` is set before the proxied window/document objects exist.

**Comment by kripken** [comment]
cc @juj

**Comment by juj** [comment]
This should be fixed by PR #8771, although I was not quite able to reproduce the same conditions.  @Daft-Freak , if you are able to confirm that #8771 does the trick, that'd be great!
