### ISSUE TITLE
pthread_key_create does not initialize thread local variable with null

### ISSUE THREAD

**Issue by AndreasReich** [emscripten-core/emscripten#8740]
The following code fails with emscripten right now:

```
pthread_key_t k;
pthread_key_create(&k, NULL);
assert(pthread_getspecific(k) == 0); // fine

pthread_setspecific(k, (void*)1);
pthread_key_delete(k);

pthread_key_create(&k, NULL);
assert(pthread_getspecific(k) == 0); // fails
```

According to POSIX specification, after creation of a thread local key, the value should be zero on key creation on all threads.
See: http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_key_create.html

**Comment by VirtualTim** [comment]
@abujalski is working on similar bugs.

**Comment by abujalski** [comment]
It looks like bug in musl library. 

Function `int pthread_setspecific(pthread_key_t k, const void *x)` (emscripten/system/lib/libc/musl/src/thread/pthread_setspecific.c) sets struct `pthread.tsd[k]` array element.

Function `int __pthread_key_create(pthread_key_t *k, void (*dtor)(void *))` (emscripten/system/lib/libc/musl/src/thread/pthread_key_create.c) sets only dtor associated with given `pthread_key_t` and **doesn't** set `pthread.tsd[k]` to `NULL`.

**Comment by AndreasReich** [comment]
Yes, musl's implementation is wrong. Probably should have filed a bug there?
I don't think it is enough to set the value on create to null: Any other thread that might read its value for the same key will still not see null.
I checked the libc implemention, there they use a generation counter which is compared on every access. If a thread's local generation for a given key is lower than a globally known location for the key, then the local value is set to null on access.

**Comment by AndreasReich** [comment]
I believe this is still unchanged. Need to re-test against newest version though to be fair

**Comment by sbc100** [comment]
ping

**Comment by sbc100** [comment]
This bug looks like its fixed in the latest musl code: https://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_key_create.c#n57

So it should be resolved once we land: #13006 (hopefully some time in the next decade!)

**Comment by kleisauke** [comment]
FWIW, this should probably be re-opened due to this TODO-item:
https://github.com/emscripten-core/emscripten/blob/f065db68f698469ff5db8415d872b4e2d223c396/system/lib/libc/musl/src/thread/pthread_key_create.c#L60-L66

As a workaround, we could do `self->tsd[k] = 0;` there, but that only sets the value to zero for the current thread, not for all threads (which is required by the POSIX standard).

**Comment by sbc100** [comment]
Ah yes, thanks for pointing that out.  Do you fancy opening a PR to do that?

**Comment by kleisauke** [comment]
I can look at implementing this next week, feel free to fix it earlier. Unit tests for this are also missing, it's a bit curious that this isn't covered by the POSIX test suite.

**Comment by mannk123** [comment]
Hello! I took the liberty of attempting a fix for this issue. It's my first time contributing to emscripten, please let me know of anything I've missed.
