### ISSUE TITLE
Create emscripten-core/dockerfile

### ISSUE THREAD

**Issue by trzecieu** [emscripten-core/emscripten#8742]
Hi,
I would like to offer my image and my support as a maintainer for this image which is placed under: 
* https://github.com/trzecieu/emscripten-docker
* https://hub.docker.com/r/trzeci/emscripten
* https://hub.docker.com/r/trzeci/emscripten-slim

I spent pretty decent amount of spare time maintaining it and optimizing the image size (which at the moment is ~160MB for Emscripten + base tools) and I think that it will be much more trustworthy if we could offer it from an official source.

**Comment by sbc100** [comment]
Nice!  Thanks for working on that.  What are proposing exactly?  Do you want to move the docker image creation under emscripten-core perhaps?

From looking over the scripts they do mostly look good.   Some parts (such as trimming emscripten) should probably pushed upstream to emsdk if possible.    Do you images currently have llvm upstream or just fastcomp?

**Comment by trzecieu** [comment]
I think that the image `emscripten-slim` might be taken as a base for the official Emscripten image with required adaptation.
It has some good findings:
* Dynamically linked llvm to internal shared objects
* Stripped debugging symbols form some tools
* Maintains compatibility for a long time, so that it started to be wide used. 

Well, it's MIT license so basically you can do it at any moment, but I think I can provide some valuable support with bootstrapping this. 

At the moment it's fastcomp, switching to upstream is on my backlog.

**Comment by kripken** [comment]
@trzecieu - just adding my own thanks as well! This has been very useful, and we use it on binaryen CI :)

**Comment by VirtualTim** [comment]
Just wanted to say that I've been using the trzeci/emscripten image for a few months, and I've been very happy with it. Development has been much smoother using WSL + Docker + trzeci/emscripten than my old Linux VM.

**Comment by sbc100** [comment]
What about adding this to the emsdk repo?  Since the work done to create the docker image is more like the work done to create emsdk and to two project will almost certainly want to do the same thing.

In we would probably want the emsdk contents should be (mostly) identical to the emsdk.   Any improvements that have been made in the dockerfile could/should be backported to the emsdk.  Shoudl we move this issue to the emsdk repo?

**Comment by trzecieu** [comment]
Sounds good @sbc100

**Comment by trzecieu** [comment]
Hi! 
I think I have managed to establish my Dockerfile to use new distribution from you. 
Also build size isn't affected much. As I've seen `emscripten-ci` repo being created that might be a good place to have it?

**Comment by kripken** [comment]
@trzecieu 

Good question about where to put it. Your image is useful for more than just CI, so maybe a more general place? `emscripten-ci` is initially for #9549 which is CI specific.

Or maybe the main use case for your image is still CI, so it's fine. I'm ok either way. Another option is to rename `emscripten-ci` to `emscripten-infra` maybe?

**Comment by sbc100** [comment]
emscripten-ci seems like a different use case since its used to *build* emscripten, where as this docker file *contains* emscripten.   I think they both have value.

I still think emsdk might be the best place for this?   What do you think about this idea?

**Comment by trzecieu** [comment]
Make sense, let's move there https://github.com/emscripten-core/emsdk/pull/368 then. 
Cheers,
