### ISSUE TITLE
-g4 and wasm2js should generate JS source map or be an error

### ISSUE THREAD

**Issue by quantum5** [emscripten-core/emscripten#8743]
`-g4` generates source maps, but `wasm2js` does not convert the WASM source map to a JavaScript source map, so you end up with a source map that you can't actually use.

We could generate translate the source maps in `wasm2js`, but it doesn't seem that important, as you can debug your program with wasm most of the time. So instead, we should probably make it an error to use the two together instead.

**Comment by blockspacer** [comment]
May be related to https://github.com/emscripten-core/emscripten/issues/8584

Provide full build flags / small example, please.

Check other settings breaking source maps, like emterpreter https://github.com/emscripten-core/emscripten/issues/5862

**Comment by sbc100** [comment]
Hmm, it is a requirement that `-g4` generate a source map?    `-g4` is a general purpose compiler flag so I think its ok to accept it without generated a source map.

How about this:

1. make a `--source-map` argument to guarantees the generation a source map and will error out under `wasm2js`.
2. Have --source-map default to true under `-g4`

**Comment by kripken** [comment]
I can confirm the problem, `-s WASM=0 -g4` will emit a source map file, but wasm2js has no integration with debug info.

@sbc100 we do [document](https://emscripten.org/docs/tools_reference/emcc.html) `-g4` as emitting a source map, so I think this is a bug. I added a comment in the wasm2js PR that disables the test, I really should have added an error in there earlier, #8756
