### ISSUE TITLE
Synchronous Fetch API Bug with Fix

### ISSUE THREAD

**Issue by elliott-wen** [emscripten-core/emscripten#8749]
Hi All

I somehow found that the synchronous API is not working properly. 

I used the following example source code from the API document.  

#include <stdio.h>
#include <string.h>
#include <emscripten/fetch.h>
int main() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);
  strcpy(attr.requestMethod, "GET");
  attr.attributes = EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | EMSCRIPTEN_FETCH_SYNCHRONOUS;
  emscripten_fetch_t *fetch = emscripten_fetch(&attr, "test.txt"); // Blocks here until the operation is complete.
  if (fetch->status == 200) {
    printf("Finished downloading %llu bytes from URL %s.\n", fetch->numBytes, fetch->url);
    // The data is now available at fetch->data[0] through fetch->data[fetch->numBytes-1];
  } else {
    printf("Downloading %s failed, HTTP failure status code: %d.\n", fetch->url, fetch->status);
  }
  emscripten_fetch_close(fetch);
}

I then compiled the source code using 
emcc example.cc -s FETCH=1 --proxy-to-worker -o example.html 

Then I started the emrun http server, which allowed me to load the example.html in my firefox browser (Ubuntu 19.04) through http://localhost:6931/example.html

Somehow the console outputted

running code in a webworker
Downloading test.txt failed, HTTP failure status code: 0.

I double checked that http://localhost:6901/test.txt exists and the link flag contains --proxy-to-worker. 

My emcc version is 1.38.31. (Also tried the upstream one 1.38.34)

Anyone could enlighten me?

Cheers
Elliott

**Comment by elliott-wen** [comment]
Ok, after a bit digging around, i now confirmed it is a bug from the Fetch library. 

When we started the synchronous download with the EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | EMSCRIPTEN_FETCH_SYNCHRONOUS  flag, the call stack will be as follows. 

emscripten_fetch.cpp (line 66): emscripten_fetch 

Fetch.js (line 456): emscripten_start_fetch

Fetch.js(line 549): __emscripten_fetch_load_cached_data

note that __emscripten_fetch_load_cached_data triggers a asynchronous call, which will not be executed right away. This makes emscripten_fetch return an empty struct. 

Solution:

put EMSCRIPTEN_FETCH_REPLACE in the flag as well....

**Comment by VirtualTim** [comment]
Sounds like #8183.

**Comment by sarbabi** [comment]
Hi seems like this is yet an issue with emscripten synchronous fetch.
I just copied the exact [code](https://emscripten.org/docs/api_reference/fetch.html#synchronous-fetches) and ran it, getting error: "Downloading (null) failed, HTTP failure status code: 0."
this error persists even when I'm adding the flag "EMSCRIPTEN_FETCH_REPLACE".

Any solutions?

**Comment by hsdk123** [comment]
Same here, it looks like firefox just stops responding when using the fetch api

**Comment by heshuimu** [comment]
This issue is still present in the current latest version. 

So it seems that there are several steps needed to make synchronous fetch work: 

1. Add `EMSCRIPTEN_FETCH_REPLACE` besides `EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | EMSCRIPTEN_FETCH_SYNCHRONOUS`
2. (This is already in the documentation) Be sure build with with `--proxy-to-worker`

**Comment by banimania** [comment]
> This issue is still present in the current latest version.
> 
> So it seems that there are several steps needed to make synchronous fetch work:
> 
> 1. Add `EMSCRIPTEN_FETCH_REPLACE` besides `EMSCRIPTEN_FETCH_LOAD_TO_MEMORY | EMSCRIPTEN_FETCH_SYNCHRONOUS`
> 2. (This is already in the documentation) Be sure build with with `--proxy-to-worker`

This workaround is not working for me. I'm still getting fetch status 0 no matter what. Does anyone have any ideas?
