### ISSUE TITLE
Delay Loading of Side Wasm Module

### ISSUE THREAD

**Issue by awtcode** [emscripten-core/emscripten#8752]
@sbc100 and @kripken ,

Do you think it is feasible to implement [delay-loading](https://stackoverflow.com/q/23403848/1329652) for a Wasm side module? This has the following benefits:
1. Replace JS import stubs with a stub function.
2. No runtime overhead of having to go thru a JS thunk.

One current limitation that I can think of is that the prototype of the imported function needs to be declared at instantiation time and I'm not sure if we can declare a stub function that takes in an arbitrary number of parameters. FYI @szilvaa.

**Comment by awtcode** [comment]
Btw, by JS import stubs, I'm referring to the following stubs that are generated by Emscripten:
<function _sidey(){ Module["_sidey"].apply(null,arguments) }>

**Comment by kripken** [comment]
Not sure what you mean by "Replace JS import stubs with a stub function" - what is replaced with what? (I guess the first is what you wrote in the later comment, but what is the second?)

In general I think this is practical, yes. Changes to wasm imports would need to be done in emscripten.py, and in the dynamic loader. Then if another module is loaded later the code can be run from there.

**Comment by awtcode** [comment]
@kripken , the stub function would be something like the following:

function delayloader() {
  // get indexes of imported functions in main module
  // get exported functions in side module
 // replace imported functions in main module with the relevant exported function
}

When the main module is first instantiated, all imported functions to the main module should be populated with the above function. Do you think this is still practical?

**Comment by sbc100** [comment]
Sadly no, I don't think this is possible.  Specifically its not possible to replace and imported function once instantiation has happened.    The only way to achieve this is with some kind of per-function wrapper (either in JS on in wasm, but either way it would need to be per function).

**Comment by sbc100** [comment]
Another way to achieve this is to use indirect calls for all inter-module calls, since the table entries are mutable after instantiation, but even then you would probably need a per-function wrapper to stuff into the table initially.

**Comment by awtcode** [comment]
@sbc100 , thanks for your reply. Are you available for a short chat now?

**Comment by awtcode** [comment]
@sbc100 , btw, I presume that the dynamic loader uses indirect calls for all inter-module calls? Is this already in Emscripten?

**Comment by sbc100** [comment]
No, the dynamic linking in emscripten today can use direct calls.. but they are direct calls to imports that themselves can have a level of indirection.   in the ideal case they can/should be direct wasm to wasm calls, but in the worst case they go via JS thunks.
