### ISSUE TITLE
[Question] Memory growth

### ISSUE THREAD

**Issue by MarcelKlammer** [emscripten-core/emscripten#8760]
Is it possible to set the memory grow steps to a specific value, eg. 64MB or 128MB, instead of doubling it?

**Comment by kripken** [comment]
There isn't an option for that currently, but it sounds like a reasonable idea to add one.

PR welcome, if you or anyone else is interested to implement this and have questions about how, let me know!

**Comment by MarcelKlammer** [comment]
Added a first pull request for this change. Any comments welcome.

https://github.com/emscripten-core/emscripten/pull/8775

**Comment by quantum5** [comment]
The pull request containing the change has been merged.
