### ISSUE TITLE
em++ unable to build

### ISSUE THREAD

**Issue by martmists** [emscripten-core/emscripten#8772]
While getting my project set up, I got the following error while running `cmake .`

```cmake
$ cmake .
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/mart/git/emsdk/fastcomp/bin/em++
-- Check for working CXX compiler: /home/mart/git/emsdk/fastcomp/bin/em++ -- broken
CMake Error at /usr/share/cmake-3.14/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/home/mart/git/emsdk/fastcomp/bin/em++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/mart/git/PokemonStats/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_ee44b/fast 
    /usr/bin/make -f CMakeFiles/cmTC_ee44b.dir/build.make CMakeFiles/cmTC_ee44b.dir/build
    make[1]: Entering directory '/home/mart/git/PokemonStats/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_ee44b.dir/testCXXCompiler.cxx.o
    /home/mart/git/emsdk/fastcomp/bin/em++     -o CMakeFiles/cmTC_ee44b.dir/testCXXCompiler.cxx.o -c /home/mart/git/PokemonStats/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    shared:ERROR: llc exectuable not found at `/b/s/w/ir/k/install/fastcomp/bin/llc`
    make[1]: *** [CMakeFiles/cmTC_ee44b.dir/build.make:66: CMakeFiles/cmTC_ee44b.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/home/mart/git/PokemonStats/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_ee44b/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)


-- Configuring incomplete, errors occurred!
See also "/home/mart/git/PokemonStats/CMakeFiles/CMakeOutput.log".
See also "/home/mart/git/PokemonStats/CMakeFiles/CMakeError.log".

```

what concerns me is that `/b/s/w/ir/k/install/fastcomp/bin/llc` is an invalid path on any system, yet it somehow generates that path rather than using the current working directory.

**Comment by kripken** [comment]
This looks similar to https://github.com/emscripten-core/emsdk/issues/260 , which in that case ended up being related to the system being 32-bit while our builds are 64-bit. We should now issue a proper error for that in the emsdk as of a few days ago.

So this might be related - which OS are you on, and is it 32-bit or 64-bit? Are you using the latest emsdk, and if so, did it show a warning or error?

But I'm not entirely sure that 32/64 bit issue explains the weird path that both of you are seeing. That looks like our build system is leaking a path somehow, but no idea how. What does your `~/.emscripten` file look like? The path to llc should be constructed from LLVM_ROOT from there.

**Comment by kripken** [comment]
Depending on how you set up the emsdk, it may also create the `.emscripten` file in the emsdk directory, so worth looking there too if it exists.

**Comment by martmists** [comment]
Arch Linux x64
```
$ cat .emscripten
import os
LLVM_ROOT = '/home/mart/git/emsdk/fastcomp/fastcomp/bin'
BINARYEN_ROOT = '/home/mart/git/emsdk/fastcomp'
NODE_JS = '/home/mart/git/emsdk/node/8.9.1_64bit/bin/node'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

**Comment by kripken** [comment]
Thanks @martmists - and just to confirm, there is no `.emscripten` file at another location? (possible locations are home dir and the emsdk dir - which location was that one in?)

If the `.emscripten` file doesn't mention such a weird `/b/s/w/ir/k` directory then it's hard for me to imagine what could make that path show up. Perhaps add some debug printouts in `tools/shared.py`, say at the end of `parse_config_file` (which loads the data from that file), and near where it prints the `llc exectuable not found at` error you see, which is in `get_llc_targets` - those might help explain what we need to fix?

**Comment by blockspacer** [comment]
> While getting my project set up, I got the following error while running `cmake .`
> 
> ```cmake
> $ cmake .
> -- The C compiler identification is GNU 8.3.0
> -- The CXX compiler identification is unknown
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/mart/git/emsdk/fastcomp/bin/em++
> -- Check for working CXX compiler: /home/mart/git/emsdk/fastcomp/bin/em++ -- broken
> CMake Error at /usr/share/cmake-3.14/Modules/CMakeTestCXXCompiler.cmake:53 (message):
>   The C++ compiler
> 
>     "/home/mart/git/emsdk/fastcomp/bin/em++"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: /home/mart/git/PokemonStats/CMakeFiles/CMakeTmp
>     
>     Run Build Command(s):/usr/bin/make cmTC_ee44b/fast 
>     /usr/bin/make -f CMakeFiles/cmTC_ee44b.dir/build.make CMakeFiles/cmTC_ee44b.dir/build
>     make[1]: Entering directory '/home/mart/git/PokemonStats/CMakeFiles/CMakeTmp'
>     Building CXX object CMakeFiles/cmTC_ee44b.dir/testCXXCompiler.cxx.o
>     /home/mart/git/emsdk/fastcomp/bin/em++     -o CMakeFiles/cmTC_ee44b.dir/testCXXCompiler.cxx.o -c /home/mart/git/PokemonStats/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
>     shared:ERROR: llc exectuable not found at `/b/s/w/ir/k/install/fastcomp/bin/llc`
>     make[1]: *** [CMakeFiles/cmTC_ee44b.dir/build.make:66: CMakeFiles/cmTC_ee44b.dir/testCXXCompiler.cxx.o] Error 1
>     make[1]: Leaving directory '/home/mart/git/PokemonStats/CMakeFiles/CMakeTmp'
>     make: *** [Makefile:121: cmTC_ee44b/fast] Error 2
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:11 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/mart/git/PokemonStats/CMakeFiles/CMakeOutput.log".
> See also "/home/mart/git/PokemonStats/CMakeFiles/CMakeError.log".
> ```
> 
> what concerns me is that `/b/s/w/ir/k/install/fastcomp/bin/llc` is an invalid path on any system, yet it somehow generates that path rather than using the current working directory.

Are you using emcmake & emmake?
Try to build similar to https://github.com/GoogleChromeLabs/webm-wasm/blob/master/build.sh#L23

**Comment by kripken** [comment]
I think we finally figured this out, see https://github.com/WebAssembly/waterfall/issues/557

It should be fixed now, but will only be in the next tagged version (1.38.40, probably next week).
