### ISSUE TITLE
Minify additional js files

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8773]
Additional js files generated by the compiler do not get minified. They probably should be.
For example `Module.worker.js` is generated when compiling with PTHREADS, `Module.fetch.js` when compiling with FETCH. These files are only ~11KB and ~115KB, but I can't see any harm on running the minifier on them.

**Comment by blockspacer** [comment]
1 Minify step can make debugging harder.
2 App developers can minify resulting files as they want.

If you want to add minify step - please make it optional (even better - using flag with ability to switch minify method)

**Comment by VirtualTim** [comment]
Well, yeah, I figured that this would obey the existing minification flags. Currently if you compile with something like `-O3` then `Module.js` is minified, but those other files are not.

**Comment by kripken** [comment]
I agree, it makes sense to do this with the current flags (`-g1` to preserve whitespace, etc.).

To minify those files, running `Building.js_optimizer_no_asmjs` with no passes should be enough, I think.

**Comment by VirtualTim** [comment]
`worker.js` is now minified, but I don't' believe that `fetch.js` is.
Not a big deal, but would still be nice.
