### ISSUE TITLE
addFunction is missing in .js companion when building with cmake -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by cryptable** [emscripten-core/emscripten#8776]
Hi,

When I build my C-code using cmake it creates the .wasm-file and the companion .js-file. The .js-file is very practical for using addFunction() to create javascript callback functions to be used in my C-code.
But when I use "cmake -DCMAKE_BUILD_TYPE=Release" to build an optimized release version of my project, the addFunction() is missing in the minified companion .js-file.

PS:
I'm a newbie in emscripten, but I won't mind to help if you can point me where to look.

**Comment by sbc100** [comment]
I think you need to export it using the EXTRA_EXPORTED_RUNTIME_METHODS command line flag
