### ISSUE TITLE
Breaking float-to-int conversion behavior change from fastcomp to LLVM (do we need BINARYEN_TRAP_MODE?)

### ISSUE THREAD

**Issue by rajsite** [emscripten-core/emscripten#8789]
I tried out the LLVM backend based on the [emsdk "latest" now uses the new build infrastructure thread](https://groups.google.com/d/msg/emscripten-discuss/fo0W09OYYfk/Z9goesA-BgAJ) by [switching to 1.38.34-upstream](https://github.com/rajsite/VireoSDK/commit/d7de5fa7e1624dbdfd9a24f4e6feae42cff95587) and ran into some interesting float-to-int problems.

After the initial switch to wasm we enabled [BINARYEN_TRAP_MODE="js"](https://github.com/emscripten-core/emscripten/blob/db6120dabd0de2defb99dedf78a07f8997a97f70/src/settings.js#L993) to make sure that code that does [double to int conversion in C++](https://github.com/ni/VireoSDK/blob/6c17b903c3dc459a893426cdd6bc96a9da95d579/source/core/TypeAndDataManager.cpp#L2848) and code that does double to int conversion in JS by assigning to the TypedArray view of the memory result in the same behavior.

We have a [few tests](https://github.com/ni/VireoSDK/blob/master/test-it/karma/publicapi/Double.Test.js#L142) that verify the float-to-int behavior through the C++ code path and then through TypedArrays [which failed for Int32, UInt32, and UInt16](https://travis-ci.org/rajsite/VireoSDK/builds/545023037#L1079).

The following are the C++ conversion and associated JS conversions where the C++ behavior has changed and is now failing:
![image](https://user-images.githubusercontent.com/1588923/59400342-c00b8980-8d5c-11e9-8d35-135945e4e974.png)

As an example for the following:
```
testWriteDoubleCoerced('int32MinValue', -2147483648, 8123456789, expectedCoercedValue(Int32Array, 8123456789));
```
The value `-2147483648`  is the initial value in memory from a fixture, the value `8123456789` is what we are trying to write using the C++ code path linked above, and `expectedCoercedValue(Int32Array, 8123456789)` calculates the behavior of that conversion using a JS TypedArray and assigning to memory of the same type (you can see further down that this example is asserting to the value `-466477803`).

The interesting bit is that it looks like the value is not getting written to memory. The test fails saying that after performing the update the value was still the initial value for those failing tests. 

My guess is that in the llvm backend the `BINARYEN_TRAP_MODE="js"` for these cases is potentially trapping and skipping the float-to-int writes that overflow and is not doing the JS algorithm based conversion or something like that.

**Comment by jgravelle-google** [comment]
Near as I can tell we don't do anything with the BINARYEN_TRAP_MODE setting in the new backend path. In emcc that gets converted to the `--trap-mode` binaryen flag, but only for asm2wasm path: https://github.com/emscripten-core/emscripten/blob/6b2cccd92892bbaf05eeab84627cc7c674e2655e/emcc.py#L2714-L2715

We have test code for this, but it's disabled in the case of the wasm backend:
https://github.com/emscripten-core/emscripten/blob/db6120dabd0de2defb99dedf78a07f8997a97f70/tests/test_core.py#L7491-L7494
https://github.com/emscripten-core/emscripten/blob/db6120dabd0de2defb99dedf78a07f8997a97f70/tests/test_core.py#L7499-L7501

So it sounds like we should show an error message when using BINARYEN_TRAP_MODE in the upstream backend at all.

**Comment by rajsite** [comment]
I think I may have buried the lead by hypothesizing about BINARYEN_TRAP_MODE.

I reran the tests with BINARYEN_TRAP_MODE removed and I get the same failure which I'll emphasize as follows:

> The interesting bit is that it looks like the value is not getting written to memory. The test fails saying that after performing the update the value was still the initial value for those failing tests.

It seems that with the llvm backend that in the cases provided assigning a large float to an Int32 is not resulting in truncating or saturating but is instead skipping the operation. The result of the test shows that after the assignment the value has not changed at all.

I think this is a distinct issue from what is discussed in #8790 and does not fix this issue.

**Comment by kripken** [comment]
@rajsite if it's separate from #8790 then we should try to get a testcase here, so we can debug it. It doesn't sound like a known bug from what you describe (unless this is with pthreads? if so, maybe #8718). Can you extract a testcase from your test suite?

**Comment by sbc100** [comment]
#8790 didn't really fix this, it just turned it into a compile error.  Re-opening in case we want to look into actual support for different modes.
