### ISSUE TITLE
emsdk install leaving a zip behind on windows

### ISSUE THREAD

**Issue by jpharvey** [emscripten-core/emscripten#8791]
The zips directory has the wasm-binaries.zip file left in it because the download code uses a different method to determine the name from the code that deletes it :-

download_and_unzip(zipfile=https://storage.googleapis.com/webassembly/emscripten-

releases-builds/win/048cf9424790cc525a7ea6da340820aae226f3b9/wasm

-binaries.zip, dest_dir=D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/fastcomp)
download_file(url=https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/048cf9424790cc525a7ea6da340820aae226f3b9/wasm-binaries.zip, dstpath=zips/)
mkdir_p(D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/zips)
Downloading: D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/zips/048cf9424790cc525a7ea6da340820aae226f3b9-wasm-binaries.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/048cf9424790cc525a7ea6da340820aae226f3b9/wasm-binaries.zip, 715598889 Bytes
unzip(source_filename=D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/zips/048cf9424790cc525a7ea6da340820aae226f3b9-wasm-binaries.zip, dest_dir=D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/fastcomp)
Unpacking 'D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/zips/048cf9424790cc525a7ea6da340820aae226f3b9-wasm-binaries.zip' to 'D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/fastcomp'
mkdir_p(D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk/fastcomp)
remove_tree(D:/Work/gitclones/gitlab/vis_tools/vistool_emscripten/windows_x86_64/emsdk\unzip_temp)
Done installing tool 'releases-fastcomp-048cf9424790cc525a7ea6da340820aae226f3b9-64bit'.
Deleting temporary zip file zips/wasm-binaries.zip

This patch fixes it for me and i think it is correct.

[emsdk.zip](https://github.com/emscripten-core/emscripten/files/3287066/emsdk.zip)

**Comment by kripken** [comment]
Thanks @jpharvey, yes, there seem to be some bugs in the code there. It also fails to identify the `.tbz2` and `.xz` suffixes. I'm not sure that mechanism is meant to delete all download - only "temp" ones, as other code in the emsdk does try hard to not download or unpack the same thing twice.

So I'm not sure how we should fix this. If we delete all downloads immediately after install then running `install` twice in a row will download twice.

On the other hand, if we don't delete it, then there are two options: if each version has a different filename, as is the case now, then we can avoid download and unpacking if we already have a version. But then we end up with extra files over time. Or, if all versions have the same filename, then we need to add some extra tracking to know whether we need to download, which seems bug-prone.

Another option is to keep things as they are now (different name per version, keep downloads around to avoid re-downloading), and have the emsdk warn if the zip dir becomes large, and have an `emsdk clean` option which erases the zip dir. Thoughts?

**Comment by jpharvey** [comment]
@kripken That probably makes sense (though isn't what i want) but it is inconsistent.
I ran 
emsdk install sdk-1.38.34-64bit

twice in a row. It did detect that the zip was there and then that the contents already existed so didn't download or unzip the file which is good.
But then it went on to download the zip for nodejs and then tried and failed to expand it and the install said it failed. 
So should probably try to keep all zips not just some ? And then adding a clean would make sense i think.
For my use case which is creating a compiler that is complete as a package that our developers can just use without doing anything i can just delete the zips.

**Comment by kripken** [comment]
Yeah, there is some inconsistency there atm, I opened #274 to try to fix that.

Aside from the zips, I realize there are other files that can linger, like every old tagged version gets a dir (1.37.3, 1.37.4, etc.). Not sure if a possible "clean" option should remove those too. It may be easier to just warn, and let people clean it themselves (or as you said, to let people always remove zips etc. manually if their use case prefers that).
