### ISSUE TITLE
python and latest version

### ISSUE THREAD

**Issue by wblakey** [emscripten-core/emscripten#8792]
hi there, is there a change with how you are dealing with pyenv, when i pull the latest version i get errors whenever i run a command with ./emsdk before it, such as:
./emsdk update-tags
or ./ emsdk install
my build script for my project pulls and then uses these commands to install emcripten before i run it.

I always get pyenv: python3: command not found,

i run this on circle with an image of ubuntu that doesn't change

**Comment by kripken** [comment]
#273 did change some things, cc @trzecieu 

I'm not sure how `pyenv` is involved - we don't call it ourselves. Is `python`, `python2`, or `python3` on your system something that runs `pyenv`? Check if `python3` works on that system (we now default to it).

**Comment by kripken** [comment]
As a workaround, if `python3` doesn't work on that environment, doing `python ./emsdk` or `python2 ./emsdk` should work, as if you pick python yourself it will use that.

However, we should try to find a way to make this work automatically. Like maybe checking not just checking if `python3` exists, but also that it works?

**Comment by trzecieu** [comment]
Hi! Can you create a simplified example how to trigger threat bad behaviour?

**Comment by trzecieu** [comment]
I've tested running `./emsdk` under `pyenv` with `3.7.0`, `2.7.15`and `system` and I couldn't find any problem.
@wblakey: Can you paste output form:
```bash
pyenv versions
which python
```

And from inside `emsdk` folder:
```bash
./python_selector --version
```

**Comment by wblakey** [comment]
I understand, python3 is used by default now. Sorry I should have mentioned this earlier, the next line of the error says this command is found in the following: python 3.5.2 3.6.4 3.7..... does the fact if finds multiple things that could use it have an effect? I’ll give you the exact output tomorrow, and I’ll try the work around too, thanks for your help

**Comment by trzecieu** [comment]
It's not used by default but favoured. In systems where no `python3` command is found in the system `$PATH` it falls back to either `python` or whatever has been used by system.

**Comment by kripken** [comment]
Hmm, the `this command is found in the following: python 3.5.2 3.6.4 3.7.....` error sounds like what ubuntu prints if python3 is called when it is not installed. So perhaps our new python selector thought it existed when it didn't, although I'm not sure how that could happen...

**Comment by trzecieu** [comment]
Hi @kripken @wblakey: I've found the cause reason and possible solution, please follow https://github.com/emscripten-core/emsdk/pull/275

**Comment by kripken** [comment]
This should be fixed by that PR, which was just merged. @wblakey, please confirm it now works on your setup, or whether there is something left to fix.

**Comment by wblakey** [comment]
yes this works great now think this was the same issue as described, thanks for your help
