### ISSUE TITLE
Emscripten .py files errors

### ISSUE THREAD

**Issue by sarthaksarm** [emscripten-core/emscripten#8799]
While compiling an emulator named "Simavr" through emscripten with the intention of porting it to web, came across with certain types of errors which got rectified even but have stuck with an issue, whose desription is as follows:
The generation of .bc(Bit Code) file for whole project has been done successfully but the corresponding .js file is not being generated, throwing an error.

Command Used(for final compilation of .js):
sudo emcc output.bc -o output.js

Error log:
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1548, in <module>
    extra_files_to_link = system_libs.calculate([f for _, f in sorted(temp_files)], in_temp, stdout, stderr, forced=forced_stdlibs)
  File "/usr/share/emscripten/tools/system_libs.py", line 545, in calculate
    libfile = shared.Cache.get(name, create)
  File "/usr/share/emscripten/tools/cache.py", line 36, in get
    shutil.copyfile(creator(), cachename)
  File "/usr/share/emscripten/tools/system_libs.py", line 379, in create_libcextra
    return build_libc('libcextra.bc', libcextra_files, ['-O2'])
  File "/usr/share/emscripten/tools/system_libs.py", line 60, in build_libc
    run_commands(commands)
  File "/usr/share/emscripten/tools/system_libs.py", line 45, in run_commands
    call_process(command)
  File "/usr/share/emscripten/tools/system_libs.py", line 14, in call_process
    raise CalledProcessError(proc.returncode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/usr/share/emscripten/emcc', '/usr/share/emscripten/system/lib/libc/musl/src/stdio/vfscanf.c', '-o', '/tmp/tmpOhkFI5/vfscanf.c.o', '-I', '/usr/share/emscripten/system/lib/libc/musl/src/internal', '-I', '/usr/share/emscripten/system/lib/libc/musl/arch/js', '-O2']' returned non-zero exit status 1

System Specification: Ubuntu 18.04
Emcc version: emcc (Emscripten GCC-like replacement) 1.22.1

**Comment by kripken** [comment]
Try to build with `EMCC_DEBUG=1` in the environment, which will print out a lot more info, hopefully including the error that causes it to halt.

However, 1.22.1 is 5 years old, and has many bugs which have been fixed since then. I'd recommend installing the latest version using the emsdk and trying that.

**Comment by sarthaksarm** [comment]
Command Used: 
sudo EMCC_DEBUG=1  emcc output.bc -o output.js

Error log:
(After few warnings and notes, the error is listed as follows)

/usr/share/emscripten/system/lib/libc/musl/src/stdio/vfscanf.c:333:1: error: alias must point to a defined variable or function
weak_alias(vfscanf,__isoc99_vfscanf);
^
/usr/share/emscripten/system/lib/libc/musl/src/internal/libc.h:66:48: note: expanded from macro 'weak_alias'
        extern __typeof(old) new __attribute__((weak, alias(#old)))
                                                      ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1548, in <module>
    extra_files_to_link = system_libs.calculate([f for _, f in sorted(temp_files)], in_temp, stdout, stderr, forced=forced_stdlibs)
  File "/usr/share/emscripten/tools/system_libs.py", line 545, in calculate
    libfile = shared.Cache.get(name, create)
  File "/usr/share/emscripten/tools/cache.py", line 36, in get
    shutil.copyfile(creator(), cachename)
  File "/usr/share/emscripten/tools/system_libs.py", line 379, in create_libcextra
    return build_libc('libcextra.bc', libcextra_files, ['-O2'])
  File "/usr/share/emscripten/tools/system_libs.py", line 60, in build_libc
    run_commands(commands)
  File "/usr/share/emscripten/tools/system_libs.py", line 45, in run_commands
    call_process(command)
  File "/usr/share/emscripten/tools/system_libs.py", line 14, in call_process
    raise CalledProcessError(proc.returncode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/usr/share/emscripten/emcc', '/usr/share/emscripten/system/lib/libc/musl/src/stdio/vfscanf.c', '-o', '/tmp/tmpauH_EZ/vfscanf.c.o', '-I', '/usr/share/emscripten/system/lib/libc/musl/src/internal', '-I', '/usr/share/emscripten/system/lib/libc/musl/arch/js', '-O2']' returned non-zero exit status 1


Version used: emscripten 1.38.31 : 1.38.31

**Comment by kripken** [comment]
There might be some confusion between emscripten versions here - like one version is trying to compile system libraries from another. If you got emscripten from your OS (the 1.22.1 version I guess) that one might be confusing things.

Probably best to uninstall all versions, then install latest from the emsdk.

**Comment by sarthaksarm** [comment]
Uninstalled whole Virtual Machine which i was working upon. Now the only version of emscripten being used is 1.38.36 .

While trying to compile a project using gcc compiler is working fine(i.e by using "make" command) but doing same with "emmake make" command, the following errors made the compilation stuck :

Command Used: emmake make

Error log:
make -C simavr RELEASE=0
make[1]: Entering directory '/home/sarm/project/simavr_emscripten/simavr'
make obj config
make[2]: Entering directory '/home/sarm/project/simavr_emscripten/simavr'
make[2]: Nothing to be done for 'obj'.
CONF sim_core_config.h
CONF sim_core_decl.h
make[2]: Leaving directory '/home/sarm/project/simavr_emscripten/simavr'
make libsimavr run_avr
make[2]: Entering directory '/home/sarm/project/simavr_emscripten/simavr'
CC sim/sim_avr.c
AR obj-asmjs-unknown-emscripten/libsimavr.a
SHARED obj-asmjs-unknown-emscripten/libsimavr.so.1
shared:ERROR: emcc: cannot find library "elf" (-s ERROR_ON_MISSING_LIBRARIES=0 to disable this error)
Makefile:68: recipe for target 'obj-asmjs-unknown-emscripten/libsimavr.so.1' failed
make[2]: *** [obj-asmjs-unknown-emscripten/libsimavr.so.1] Error 1
make[2]: Leaving directory '/home/sarm/project/simavr_emscripten/simavr'
Makefile:34: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sarm/project/simavr_emscripten/simavr'
Makefile:15: recipe for target 'build-simavr' failed
make: *** [build-simavr] Error 2

Emscripten version used: 1.38.36
OS Config.: Ubuntu 18.04

**Comment by kripken** [comment]
`shared:ERROR: emcc: cannot find library "elf"` suggests it is doing `-lelf` or otherwise trying to link in a library by that name. Emscripten doesn't have a system library like that. If this is a user library, you need to port it first, then link it in here.

**Comment by sarthaksarm** [comment]
True that but emscripten(emcc) itself is claiming on asking for help as NO support for elf by giving the
Command:
emcc --help

Result:
emcc: supported targets: llvm bitcode, javascript, NOT elf
(autoconf likes to see elf above to enable shared object support)


Then, does it mean compiling of some project with "elf" is not possible ? And if it is like so, how to proceed further then, for Porting of such project(specifically Simavr)?

**Comment by sbc100** [comment]
No, the problem is not related to the target type.   The project seems to depend on a library called libelf which it not found.   Most like you need to compile libelf first.

**Comment by sarthaksarm** [comment]
Yes, true that. We have successfully addressed this issue. Thanks a lot for the kind cooperation and support.
