### ISSUE TITLE
Memory leak and threading issues with Fetch

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#8803]
Marking down items of the current Fetch API that I observed while reviewing #8486:

1. `Fetch.xhrs` is thread local to each thread, and the size of this array is used to assign IDs to fetches. The intent was that these IDs would uniquely identify Fetch objects, but as it currently stands, each thread gets their own running numbers for IDs, so there can exist a fetch with ID 1 in two different threads. To fix, should use a global variable that is atomically incremented to allocate fetches, so that all threads source IDs from a coherent/consistent running number.

2. It looks like `emscripten_fetch_close()` does not currently clear out the `Fetch.xhrs[fetch->id-1]` field, so the actual XHR object for each fetch is kept alive and won't be garbage collected! Closing a fetch should null out the appropriate xhr object from the `Fetch.xhrs` array so GC can reclaim it.

3. For the above reason, `emscripten_fetch_close()` needs to be called on the same thread where the `emscripten_fetch()` was initiated - or otherwise the calling thread won't be able to free the xhr object from another Worker.

4. the intent was that Fetch ID field could be used to index to this array to locate the xhr, i.e. with `Fetch.xhrs[fetch->id];`. However, a small awkwardness, turns out this is off by one, and currently `Fetch.xhrs[fetch->id-1];` currently needs to be used. ID/index 0 should be reserved for an invalid/no fetch - we can push a 0/null/undefined to first index of the table to denote an empty fetch, then `Fetch.xhrs[fetch->id];` could be used.

**Comment by VirtualTim** [comment]
For `2.`, I wonder if that's why the last request is always shown as "pending" in the browser? I had assumed that was some sort of optimisation regarding request reuse.

**Comment by juj** [comment]
Hmm no, I don't think that should cause downloads to show up as pending (if it did, that would be a browser devtools(?) bug)

**Comment by VirtualTim** [comment]
OK. I haven't really investigated the issue, because there doesn't seem to be any negative impact.

**Comment by VirtualTim** [comment]
I've got a fix for the leek (linked above).

Unfortunately this does not fix the the issue I was having where the last xhr request would always be stuck on "pending". Although strangely if the logging (here: https://github.com/VirtualTim/emscripten/blob/c2168fc24565887c295363b1256230d1b4eaeb50/src/Fetch.js#L593) is enabled this doesn't occur. I'll write this of as a browser bug.

**Comment by kripken** [comment]
Looks like the leak has been fixed by @VirtualTim 's #8968, but leaving open for the other issues.
