### ISSUE TITLE
bad magic word

### ISSUE THREAD

**Issue by log4b0at** [emscripten-core/emscripten#8804]
i get a file with a bad magic word when i use 
`   emcc src.c -s WASM=1 -o src.wasm`
, why?

**Comment by sbc100** [comment]
Whats probably happening is that you are getting an object file (either a bitcode object or a wasm object). 

To get the final wasm output file you need to calls the output ".js", this will then also generate a ".wasm" file alongside.

I'm a little confused about this myself and I think I might try to change this behaviour.  We shouldn't be generating object files unless `-c` is specified.
