### ISSUE TITLE
Different encoding between std::string and char* in embind

### ISSUE THREAD

**Issue by TomiBelan** [emscripten-core/emscripten#8806]
When using embind / emval, std::string values are encoded as UTF-8 but char* values are encoded as Latin-1. So you must be very careful about which val() constructor you use, or what argument type you give to operator[], set(), etc.

```cpp
#include <emscripten/bind.h>
#include <emscripten/val.h>

emscripten::val tryCharPtr() {
    const char* str = "☺";
    return emscripten::val(str);
}

emscripten::val tryStdString() {
    std::string str = "☺";
    return emscripten::val(str);
}

EMSCRIPTEN_BINDINGS(demo) {
  emscripten::function("tryCharPtr", &tryCharPtr);
  emscripten::function("tryStdString", &tryStdString);
}
```
```bash
$ emcc -o encodingdemo.js encodingdemo.cpp --bind
```
```js
> require('./encodingdemo').tryStdString()
'☺'
> require('./encodingdemo').tryCharPtr()
'âº'
```

Maybe one solution could be: In emval.js, getStringOrSymbol currently calls readLatin1String. This could be also configurable by EMBIND_STD_STRING_IS_UTF8, or a separate new option which also defaults to 1. Although, I don't know where everywhere is getStringOrSymbol used and if any call sites rely on Latin-1.

**Comment by TomiBelan** [comment]
For now I'm using this workaround:
```bash
$ emcc -o encodingdemo.js encodingdemo.cpp --bind --js-library workaround8806.js
```
```js
// workaround8806.js

// --js-library must go after --bind
if (!LibraryManager.library['$getStringOrSymbol']) {
  throw Error("emval.js didn't run yet");
}

mergeInto(LibraryManager.library, {
  $getStringOrSymbol__deps: ['$emval_symbols'],
  $getStringOrSymbol: function(address) {
    var symbol = emval_symbols[address];
    if (symbol === undefined) {
      return UTF8ToString(address);
    } else {
      return symbol;
    }
  },
});
```

**Comment by TomiBelan** [comment]
Ah, is this what they call the CADT development model?

Issue still happens on `emcc (Emscripten gcc/clang-like replacement) 1.39.18 (a3beeb0d6c9825bd1757d03677e817d819949a77)`.

**Comment by sbc100** [comment]
Certainly seems odd to use latin1 here.. UTF8 seems like the appropriate way to interpret C strings by default.
