### ISSUE TITLE
template class deduction guides for optional 

### ISSUE THREAD

**Issue by rilerez** [emscripten-core/emscripten#8807]
I installed latest-upstream using emsdk. I'm running on linux. I wrote the following minimum working example:

    #include<optional>
    int main(){
      auto x = std::optional{24};
      return 0;
    }

calling em++ -std=c++2a test.cpp results in an error message where no candidate for optional's constructor could match. This, however, compiles fine on the vanilla clang I built from source.

**Comment by juj** [comment]
Which clang version are you on when you build from source? Perhaps it is only available in a newer version of clang? (try `clang --version`)

For reference on the Emscripten side:
```bash
zclb:incoming clb$ which emcc
/Users/clb/emsdk/emscripten/incoming/emcc
zclb:incoming clb$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.38.34 (commit 1d220c57d4bd98ebb4eeeb1e5e9cf0b9561b9781)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
zclb:incoming clb$ which clang
/Users/clb/emsdk/clang/upstream/build_master_64/bin/clang
zclb:incoming clb$ clang --version
clang version 9.0.0 (https://github.com/llvm-mirror/clang.git 83b6db970ca7d26ee646a0d7a2087941280b936f) (https://github.com/llvm-mirror/llvm.git 7a3adb340cb803b091c445433ac4dc4e24000250)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/clb/emsdk/clang/upstream/build_master_64/bin
zclb:incoming clb$ 
```
where indeed the test case does not build.

**Comment by kripken** [comment]
I think the error message about no candidate is because of code in the system library. So the upstream backend's compiler is new enough, but we need to update libc++ in emscripten for the system library to be new enough.

**Comment by kripken** [comment]
Looks like our last update is here, which was about a year ago: https://github.com/emscripten-core/emscripten/pull/6619 if someone is interested to do a similar update now, a PR would be welcome!

**Comment by rilerez** [comment]
Copying the deduction guide over from clang's libc++ doesn't fix the problem, with or without the `#ifndef _LBICCP_HAS_NO_DEDUCTION_GUIDES`. My own code has a deduction guide which seems to work without a problem. Any ideas what could be causing this?

**Comment by sbc100** [comment]
From my initial testing I found that this worked with libstdcxx headers but not with libc++ headers:

Works:  `../llvm-build/bin/clang -c test.cc -std=c++2a`
Fails: `../llvm-build/bin/clang -c test.cc -std=c++2a -stdlib=libc++`

Are you able to get this to work at all with libc++?

**Comment by rilerez** [comment]
As of now my libc++ paths are not configured correctly so it can't find optional in the first place. I'll see if I can get that working tomorrow.

**Comment by sbc100** [comment]
I got this to work with more recent libc++ headers so it looks like it is simply the fact the emscripten's headers are somewhat out of date.
