### ISSUE TITLE
emsdk construct_env doesn't set PYTHON_PATH

### ISSUE THREAD

**Issue by d3x0r** [emscripten-core/emscripten#8809]
When updating to latest with git, emsdk_prompt.bat stopped working... (between that, and my updating python, though I'm pretty sure that was working after python update and until git update)

I have Python 2.7.16 installed 'system wide' that is, the environment variable python_path points to

```
PYTHONPATH=c:\tools\python27;c:\tools\python27\DLLS;c:\tools\python27\LIB;c:\tools\python27\LIB\LIB-TK
```

Which, when emsdk detects python and finds...

```
@IF EXIST "%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe" (
  @SET EMSDK_PY="%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe"
  @GOTO end
)
```

Python path then doesn't point at the correct library...

```
  @SET PYTHONPATH=%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\;c%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\DLLS;%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\\LIB;%~dp0python\2.7.13.1_64bit\python-2.7.13.amd64\LIB\LIB-TK
```

(Should probably be implemented similarly for other python versions).

**Comment by kripken** [comment]
I'm not sure, but I don't think this is a regression, as I can't see any mention of PYTHONPATH at all in emsdk?

I'm not sure how PYTHONPATH works on windows though, so maybe I'm missing something.

@d3x0r perhaps by checking older revisions of the emsdk you can check if this is a regression or not?

cc @juj

**Comment by d3x0r** [comment]
Maybe a better solution is to unset PYTHONPATH... 

 I found I also did had patched my emsdk.bat previously.

```
set PATH=H:\dev2\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\;C:\Users\Panther\AppData\Roaming\npm\;%PATH%
set PYTHONPATH=H:\dev2\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\;H:\dev2\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\DLLS;H:\dev2\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\LIB;H:\dev2\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\LIB\LIB-TK
```

I'm not sure why I have it set.. doing some digging it shouldn't be.... probably was an earlier version or mixing python3 with 2.7 or ... *shrug*

**Comment by sbc100** [comment]
Sounds like that you want to find and edit or remove your global PYTHONPATH.   For one thing system librarys should not be in the PYTHONPATH since python finds them on its own.

**Comment by d3x0r** [comment]
*shrug* I don't know.  There's a reason I add it to the environment; I don't use python except where required, so I don't know the specifics.  I know if someone has a PYTHONPATH set, emscripten's scripts to use its own version fail.
It does appear that `@set PYTHONPATH=`  is a more generic patch, and seems to work.

I don't version control my tool system so I don't know when it was added, nor have any remarks as to why it is required.

**Comment by sbc100** [comment]
I would advice removing all your PTYHONPATH settings.  

It should not be needed, python itself knows where to find things by default.
