### ISSUE TITLE
Easily include external .js file

### ISSUE THREAD

**Issue by ktb92677** [emscripten-core/emscripten#8826]
Hi all, for a while now I have been adding the following to the top of index.html that is generated by emcc:

```
<script type="text/javascript" src="Decoder.js"></script>
		<script type="text/javascript" src="YUVCanvas.js"></script>
		<script type="text/javascript" src="Player.js"></script>
```

How can I have these lines added automatically?

**Comment by brion** [comment]
I'm not sure if there's a handy way to insert individual `<script>` tags to the default shell, but you can replace the default shell HTML with the [`--shell-file` option](https://emscripten.org/docs/tools_reference/emcc.html#emcc-shell-file) which lets you do any customization you like on the HTML, such as pulling in additional scripts or customizing the styling.

**Comment by kripken** [comment]
Other options here are `--pre-js` and `--extern-pre-js`.

Closing, but please let us know if there is something more to fix here.
