### ISSUE TITLE
Debugging runtime behaves differently with optimization flag 

### ISSUE THREAD

**Issue by kwonoj** [emscripten-core/emscripten#8835]
Coming from https://github.com/kwonoj/hunspell-asm/issues/187#issuecomment-504087065

Original reporter @bluthen did nice sleuthing around this behavior:

```
int is_swap = 0;
  int re = 0;
  double fact = 1.0;
  printf("!!!1 fact=%f\n", fact);
  if (pAMgr) { 
    printf("!!!2 fact=%f\n", fact);
    int maxd = pAMgr->get_maxdiff();
    printf("!!!3 fact=%f, %d\n", fact, maxd);
    if (maxd >= 0) 
      fact = (10.0 - maxd) / 5.0;
    printf("!!!4 fact=%f, %d\n", fact, maxd);
  }
```

in above, ` fact = (10.0 - maxd) / 5.0;` sets to `0.0` only on certain runtime env (mobile safari in here) with -O optimization turned on. I don't have greate knowledge around optimization flag behavior, bit stuck where to start to debug / understand why this is happening & how to fix. Is there some recommended way I can try myself?

buildable docker config is located here (https://github.com/kwonoj/docker-hunspell-wasm) and wrapping libarary is here (https://github.com/kwonoj/hunspell-asm).

**Comment by bluthen** [comment]
Just a note for clearity. I'm not confident that it is even `fact = (10.0 - maxd) / 5.0;` that sets it to zero.  maxd is -1 so it shouldn't even go in that if condition.

**Comment by kripken** [comment]
There have been a few safari bugs in this area, like https://bugs.webkit.org/show_bug.cgi?id=198106 . If it's possible to file a small testcase with what you see then we should file that for them. If it is a safari bug, until they fix it a possible workaround may be to not optimize certain functions (but yeah, that's not great).

**Comment by jasonsanjose** [comment]
I think we're in the same boat with a similar safari-only, release-build-only behavior that for us results in a crash.

@kripken we think we've isolated our issue to one or two libraries we're using. Is there a way to tell the emscripten tool chain to skip optimizing those libraries?

**Comment by kripken** [comment]
@jasonsanjose it would depend on the library. but typically you can edit their makefiles or CMakeLists.txt etc. and remove the optimizations (or replace them with different ones).

**Comment by CoreyDotCom** [comment]
Thanks @kripken, in our case I think we're getting bitten by a link time optimization. I really wish they has fixed the safari mobile macro compiler issues in 12.4. :) 

Long story short the only way to avoid safari mobile issues is to crank back to O0 which is not viable.  We were just wondering if there is any to wholesale exclude a library (static) from lto in the wasm toolchain.  Other things we've tried are clang @pragma's and/or attributes to exclude specific code but didn't seem to help.  Unfortunate.

**Comment by kripken** [comment]
Emscripten won't do LLVM LTO by default, but it does do Binaryen optimizations, which are kind of like LTO - is that maybe what is affecting things?

We don't have a way to not run Binaryen on specific functions or libraries, but if you link with `-O0` then it won't run Binaryen opts at all. When using the LLVM wasm backend, the code will still be pretty optimized. If you're using fastcomp, however, then this might be more of a problem. So I'd recommend [upgrading to the wasm backend](https://v8.dev/blog/emscripten-llvm-wasm#testing) as a first step here if you haven't already.

**Comment by bluthen** [comment]
The original issue seems to be gone on mobile safari on iOS/iPadOS 13.1
