### ISSUE TITLE
Failing to build cpp file containing openCV [question]

### ISSUE THREAD

**Issue by mbijelic** [emscripten-core/emscripten#8840]
I am trying to create utility (a cpp file with few exported functions containing OpenCV image manipulation) with emscripten and opencv, by compiling statically.
After following the suggestions here
https://github.com/emscripten-core/emscripten/issues/1776
and here
https://stackoverflow.com/questions/55233539/emscripten-link-static-library-error-wasm-steaming-compile-fail-import-env-ge
I am still failing to successfully compile this utility file.
my steps:
1. build OpenCV
2. build OpenCV wasm
3. compile cpp file using em++ (using -I to include every header file that is needed for compilation) and including .a files from wasm build

Regarding this: https://emscripten.org/docs/compiling/Building-Projects.html#using-libraries
I am not sure how to generate bit codes for OpenCV

Is there more documentation on how to use existing libraries with projects and compiling it to wasm.
P.S. I am using windows subsystem for linux as environment
![image](https://user-images.githubusercontent.com/52065444/59907504-8ba66600-940b-11e9-8111-18562fe38335.png)

**Comment by juj** [comment]
> I am not sure how to generate bit codes for OpenCV

To compile to bitcode, specify output suffix as `.bc` for the build. For example, to build `tests/hello_world.c` to a bitcode file instead of a js/html file, specify
```
emcc tests/hello_world.c -o this_is_a_bitcode_output.bc
```
(whereas to build a js file, you would have issued
```
emcc tests/hello_world.c -o this_is_a_javascript_output.js
```
)

**Comment by mbijelic** [comment]
Thank you.
I will close this now.
