### ISSUE TITLE
Emscripten Fetch API: Unable to get total file size when doing range requests

### ISSUE THREAD

**Issue by fibbo** [emscripten-core/emscripten#8841]
I want to implement range requests with the fetch API. For this to work I need to know the total size of the file I want to fetch.

Is there a way to do this? When just doing a range request, `fetch->totalBytes` contains only the partially fetched size and not the total file size. I also tried to use `HEAD` instead of `GET`  and see if this shows me the file size but this just returns `0`.

If this is not possible yet I think this should be something that needs to be implemented in order to properly work with range requests.

In a very simple hack I added following lines to `Fetch.js`:

```
else {
      Fetch.setu64(fetch + {{{ C_STRUCTS.emscripten_fetch_t.totalBytes }}}, e.total); 
}
```

after line [379](https://github.com/emscripten-core/emscripten/blob/incoming/src/Fetch.js#L379) This would allow me to obtain the total file size if the body is 0.

**Comment by juj** [comment]
The PR #8486 will resolve this, it gives a general way to obtain the response headers, so those can be used to query the returned header attributes.

**Comment by fibbo** [comment]
Thanks - works like a charm
