### ISSUE TITLE
Rename stack and other memory location variables

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8843]
Background: discussion in #8842 

 * It may be nicer to rename "STACKTOP" to "SP" or "STACK_POINTER".
 * It may also be a good idea to rename `STACK_BASE` and `STACK_MAX` to something less ambiguous, as "max" is really the farthest we can increment it to, and for the wasm backend we increment it down... so "max" is the lowest value. `min/max` and `low/high` may be less ambiguous if we make them mean the lowest and highest value respectively.
 * This should be done in coordination with the pthreads code, which has things like `stackMax` which should have the same meaning as `STACK_MAX`.
 * This should probably also affect `DYNAMIC*` and `STATIC*` as those have the same convention as `STACK*` currently.

Notes:

 * This may become much easier after fastcomp is removed, as then the stack will only go one way.
 * This may become easier if we remove `DYNAMIC*` and `STATIC*`. (We've already removed much of the latter since we stopped doing static allocations at JS startup  time; see #7795)

**Comment by quantum5** [comment]
It seems like in threads on WASM backend, `STACK_MAX` is the same as `STACK_BASE`, but on the main thread, `STACK_BASE` is the starting point of the stack. So, on a thread, `STACK_BASE` is the lowest address on the stack, but on the main thread, it's the highest.

This is highly inconsistent and makes it very difficult to obtain the bounds of the stack in sanitizers.

**Comment by sbc100** [comment]
@quantum5 that clearly needs addressing independently of the rename

@kripken I suggest we go ahead with the STACKTOP -> STACK_POINTER/SP rename right away and look into the others later/independently as its less obvious what the right answer is.

**Comment by kripken** [comment]
I'm not opposed to doing this now (especially if it's blocking something) but I think it would be easier after we remove fastcomp since there will just be less code.

**Comment by quantum5** [comment]
It's not actually blocking anything now. We should wait for fastcomp removal.

**Comment by kg** [comment]
As far as I can tell STACKTOP is gone. Is it behind a pref now? Was it renamed without closing this issue? I can still see DYNAMICTOP in .js outputs from emscripten along with STACK_MAX and TOTAL_STACK but not STACKTOP.

**Comment by kripken** [comment]
@kg STACKTOP is still there for initial setup (if the optimizer didn't remove it), but it shouldn't be used, as the stack is now managed by the compiled code.

The safe way to access the current stack location is to call the `stackSave/stackRestore/stackAlloc` functions, to get/set/allocate. (They will also be eliminated if not used, but you can either use them in JS code the optimizer sees, or export them on `EXPORTED_RUNTIME_METHODS`.)

**Comment by kg** [comment]
By "shouldn't be used" do you mean that stackSave() - STACKTOP won't provide a meaningful value?

**Comment by kg** [comment]
I'm attempting to export stackSave and not getting it, is this not supported in the new llvm flow?
```
EXTRA_EXPORTED_RUNTIME_METHODS=['stackSave', 'ccall', 'FS_createPath', 'FS_createDataFile', 'cwrap', 'setValue', 'getValue', 'UTF8ToString', 'addFunction']
```

**Comment by kripken** [comment]
@kg

Yeah, STACKTOP is assigned once during startup (as an internal detail) but it will be out of date later. I guess it would be a valid measurement of the initial location of the stack, but not the current location.

That command looks right (with a `-s` before it). E.g. `./emcc tests/hello_world.c -s EXTRA_EXPORTED_RUNTIME_METHODS=['stackSave']` will emit `Module["stackSave"] = stackSave` in the JS, showing it's exported.
