### ISSUE TITLE
'createQueryEXT' of null

### ISSUE THREAD

**Issue by ValSergey** [emscripten-core/emscripten#8844]
Hi,
New version (1.38.36) exhibit :
 exception thrown: TypeError: Cannot read property 'createQueryEXT' of null,TypeError: Cannot read property 'createQueryEXT' of null
    at _emscripten_glGenQueriesEXT 
What’s the hitch?

**Comment by ValSergey** [comment]
I used SDL_GL_GetProcAddress. (SDL2)
_________________________________________________
....
PFNGLGETQUERYIVPROC    glGetQueryiv_  = NULL;
...
glGenQueries_ =  (PFNGLGENQUERIESPROC)   SDL_GL_GetProcAddress("glGenQueries");

**Comment by kripken** [comment]
We did do some recent changes here, #8541 and #8430. Please check if those make a difference in your codebase, and if there's a regression from one of them, then we need to look into that.

**Comment by ValSergey** [comment]
Thankee you. Your variant work all good.
