### ISSUE TITLE
LLVM backend: Improve usability for .a files without symbol table

### ISSUE THREAD

**Issue by Keno** [emscripten-core/emscripten#8847]
Opening this issue to track the issue I mentioned at the end of https://github.com/emscripten-core/emscripten/pull/8808. In particular, on my machine, the system `ar` and `ranlib` don't have any support for wasm object files (but I believe they may have support for bitcode), causing the library to be skipped in linking without any notice to the user. This seems like something users are quite likely to hit once the backend is switched to LLVM by default, so I think it would be good to do something about. Suggestions:

- In `wasm-ld --verbose` mode print an explicit warning for any archive without a symbol table

and one of

- Add a general warning to lld if there are undefined symbols and there were archives without symbol tables. I think the biggest problem here is that `-allow-undefined` is generally passed by emscripten, so the warning would never actually show up.

- Just make it work by iterating the symbol tables of the members if the archive has no symbol table. This would probably be the user friendliest option, but of course comes with performance implications of having to parse through every member file.

- Detect this situation separately in emscripten at the very end of the linking process if there are undefined symbols left. This is similar to the first suggestion, but at the point where emscripten has resolved all the imports and knows whether any undefined symbols are left. Of course, similar issues with allowing undefined imports remain.

For a bit of history, the lld ELF backend has gone through a bit of history here. There used to be a warning about archives without symbol table if any undefined symbols remained. This got changed in https://reviews.llvm.org/D32721, to just iterate the symbol tables of the members, and then changed again in https://reviews.llvm.org/D59373 to only iterate over members if all the members are bitcode.

I think my preference here would be to just make this work (by iterating over symbol tables of members). We could potentially add a flag to `wasm-ld` for emscripten to set to choose this behavior (such that users who have more tightly controlled build systems and don't use emscripten don't have to pay the overhead), but I think for emscripten the right default is to be as tolerant as possible of not-quite-correct build systems, esp since it appears to work with the fastcomp backend at the moment (at least on my system).

**Comment by kripken** [comment]
Thanks @Keno!

cc @sbc100

**Comment by sbc100** [comment]
This makes sense to me.  Thanks for pointing it out.  I think we can extend the logic used in ELF lld to be "if archive is missing symbol table, and contains either all bitcode or all wasm then parse objects individually".

I'll open an upstream bug in lld: https://bugs.llvm.org/show_bug.cgi?id=42376

**Comment by sbc100** [comment]
The initial fix is just to error out: https://reviews.llvm.org/D63739

We can extend this to reading object individually later perhaps.

**Comment by dschuff** [comment]
IIUC we have a nice error message now (and we match the behavior of GNU ld), which should avoid silently skipping libraries and confusion. It sounds like at least Rui and @keno want to match the lld/ELF behavior so we can leave this open. But I think this shouldn't be a blocker to switching the default anymore.

**Comment by sbc100** [comment]
I'm inclined to close this.  I think the current behaviour is fine.  Error'ing out and asking the developer to use the right `ar` tool seems perfect acceptable.  @Keno are you OK with this outcome?

**Comment by dschuff** [comment]
FWIW that was the behavior I actually expected because it's what GNU ld does; but I don't have a strong opinion.
