### ISSUE TITLE
CMake Platform file doesn't work with LLVM Backend

### ISSUE THREAD

**Issue by Keno** [emscripten-core/emscripten#8848]
Continuing my adventure of trying to use the LLVM wasm backend with Emscripten, I encountered the next issue. The Emscripten CMake platform file specifies `-s WASM=0` as a forced override at:

https://github.com/emscripten-core/emscripten/blob/16edbe51e141f443a27a9a8919786089facdcfbb/cmake/Modules/Platform/Emscripten.cmake#L53

This caused various cmake configure checks to fail in `wasm2js`, e.g. because of lacking sourcemap support:
```
shared:ERROR: wasm2js does not support source maps yet (debug in wasm for now)
```
(though there were other `wasm2js` errors also). I suspect that override should not be applicable to the wasm backend.

**Comment by kripken** [comment]
Thanks @Keno - I'm removing that hack in #8851. Do things work for you with that?

**Comment by Keno** [comment]
Yes, that's one of the changes I made on my way to getting things to build with the LLVM backend and that worked fine.
