### ISSUE TITLE
Sent int in EM_ASM will always be unsigned value

### ISSUE THREAD

**Issue by Mavhod** [emscripten-core/emscripten#8850]
Example code
`
EM_ASM( {
	console.log( $0 );
}, -1 );
`

Console output show
`
4294967295
`

**Comment by kripken** [comment]
Yeah, we've never really specified an "ABI" here, but yeah, this can be confusing. In LLVM there is no signed or unsigned value, just operations that are signed or unsigned. This difference may become more noticeable as we switch to the wasm backend, as it may happen to do things differently than fastcomp.

Fixing this might require adding casts on the entire wasm/JS API, though, which I'm not sure is worth it.

For users, the simple thing to do is to not assume the value is signed or unsigned, and cast it as necessary: `x | 0` for signed, `x >>> 0` for unsigned.

**Comment by jgravelle-google** [comment]
Should also be able to use EM_JS here, to do something like:
```c++
EM_JS(void, console_log_signed, (int x), {
  console.log(x);
});
int main() {
  console_log_signed(-1);
  return 0;
}
```
which shows `-1`

What's interesting to me is the wasm->JS conversion is explicitly signed: https://webassembly.github.io/spec/js-api/index.html#tojsvalue so it's something EM_ASM-specific
