### ISSUE TITLE
PROXY_TO_PTHREAD and OFFSCREENCANVAS_SUPPORT issues

### ISSUE THREAD

**Issue by samsinsane** [emscripten-core/emscripten#8852]
When using `-s PROXY_TO_PTHREAD=1` with `-s OFFSCREENCANVAS_SUPPORT=1`, `eglCreateContext` and `eglMakeCurrent` synchronize with the main thread and generate an error/exception because the canvas has been transferred. I wrapped the `eglCreateContext__proxy: 'sync',` and `eglMakeCurrent__proxy: 'sync',` lines in `#if !OFFSCREENCANVAS_SUPPORT` and everything started working, this might not be the correct way to do this and they might not be the only functions with this problem.

I had a look at the test `test_webgl_offscreen_canvas_in_proxied_pthread` which seems to cover this case, but it doesn't run on Chrome due to memory leaks, and the Firefox build seems to be spamming `[client logging: /?exception=ExitStatus: Program terminated with exit(0) / undefined ]` a number of times before continuing. The test has a number of calls to `printf`, so I would assume we would see these in the test output?

**Comment by kripken** [comment]
Thanks @samsinsane! yeah, the current testing situation is not good, we had to disable it on chrome as you said, and on firefox I think there is no offscreen canvas support yet so the test ends up skipped as well.

Yes, it does sound like we should proxy those two methods (and likely others). Do you want to open a PR with that fix perhaps?

**Comment by samsinsane** [comment]
> and on firefox I think there is no offscreen canvas support yet so the test ends up skipped as well.

Looked into this a bit more, according to MDN Firefox does support offscreen canvas but it's behind a flag which the tests already enable. I'm not sure what I was looking at originally but that test has been skipped for about a year, I must have been looking at the wrong test, sorry about that. However, the CircleCI config states that it's skipped specifically due to https://bugzil.la/1281796 which was closed 9 months ago as won't fix, it seems like it's fixed? Should I re-enable the tests in my PR?

**Comment by samsinsane** [comment]
Figured out why I'm so confused, there's two tests with very similar names:
- `test_webgl_offscreen_canvas_in_pthread` This is the one that has been skipped for over a year due to the linked issue above.
- `test_webgl_offscreen_canvas_in_proxied_pthread` This is the one that I originally referenced that matches my use case. It runs [this file](https://github.com/emscripten-core/emscripten/blob/b3f068e23b5cc09055e9651c6de56070f9fdfff1/tests/gl_in_proxy_pthread.cpp) should the `printf` calls be appearing in the CI logs, and should the test be checking that the functions are successful?

**Comment by kripken** [comment]
`printf` calls don't get into the server logs by default. we only log errors and other critical events currently.

And yeah, those tests just check the final return code atm - would be good to improve that. Options include checking the visual output with a reference test image, or checking each return code of those functions, as you said.

**Comment by samsinsane** [comment]
I don't believe this is fixed.
