### ISSUE TITLE
USE_PTHREADS + BUILD_AS_WORKER doesn't work

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8854]
I assume that this doesn't work the the same reason that USE_PTHREADS + PROXY_TO_WORKER doesn't. However it appears that at some point it was working (#4372)?

I didn't really expect this to work, but if it's known to be broken the compiler should emit an error.

The issue for me is that this: 
https://github.com/emscripten-core/emscripten/blob/7eb910a3c5324ecf8ce3c0d96a635a920fbdcde2/src/postamble.js#L496
catches the pthread initialisation 'run' command, so it ends up throwing here:
https://github.com/emscripten-core/emscripten/blob/7eb910a3c5324ecf8ce3c0d96a635a920fbdcde2/src/postamble.js#L509

**Comment by kripken** [comment]
Yes, these are separate modes that don't work together. Probably once pthreads is common enough the old `BUILD_AS_WORKER` can be removed. Meanwhile I agree it would be good to show an error.
