### ISSUE TITLE
EM_ASM is broken without extra parameters

### ISSUE THREAD

**Issue by Akaricchi** [emscripten-core/emscripten#8860]
The following code used to work:
```c
	EM_ASM({
		var sdl2 = Module['SDL2'];
		if(sdl2 !== undefined) {
			var audioctx = sdl2.audioContext;
			if(audioctx !== undefined) {
				audioctx.resume();
			}
		}
	});
```

After updating to latest emscripten I get the following: https://gist.githubusercontent.com/Akaricchi/e970633fdfd8816338574c7e096f5428/raw/28b0ec9104ab9c56f6309ee6a1de5255a121c5cb/gistfile1.txt

Appending a dummy unused argument appears to work, although it still generates a -Wgnu-zero-variadic-macro-arguments warning, annoyingly enough — maybe you should consider suppressing it with `__extension__` so that users wouldn't have to disable the warning or do that in their own code. `#define EM_ASM(...) (__extension__ (.. the rest ..))` should do the trick.

**Comment by kripken** [comment]
Do you have a full testcase showing the problem? When I try to compile that like this I don't get an error:
```
#include <emscripten.h>

int main() {
	EM_ASM({
		var sdl2 = Module['SDL2'];
		if(sdl2 !== undefined) {
			var audioctx = sdl2.audioContext;
			if(audioctx !== undefined) {
				audioctx.resume();
			}
		}
	});
}
```

**Comment by Akaricchi** [comment]
Seems like it only occurs in strict ANSI compliance mode, e.g. `-std=c11` which my project builds with by default. `-std=gnu11` works fine. The warnings are still there with `-Wpedantic` though.

It's probably fine to require GNU extensions, but this should at least be documented, and/or perhaps `emcc` should remap strict ANSI standard modes into GNU equivalents automatically, with a warning.

**Comment by sbc100** [comment]
Or perhaps we should just pass `-Wno-gnu-zero-variadic-macro-arguments` under the hood?

**Comment by Akaricchi** [comment]
That would remove the warning, but not the error; they are not related.

**Comment by sbc100** [comment]
@jgravelle-google where you aware that EM_ASM required GNU extensions?   

Perhaps that best thing to do is simply `#error` if GNU extensions are missing.

Its kind of shame we can't just do this for EM_ASM users.  It will effect all emscripten.h users I think.

**Comment by sbc100** [comment]
I think its better to error out and have developers stop passing the non-gnu flag, rather than coercing the flag they pass into the gnu flag.

**Comment by jgravelle-google** [comment]
I'm curious if `__extension__` would work in general. Failing that:

>Perhaps that best thing to do is simply #error if GNU extensions are missing.
Its kind of shame we can't just do this for EM_ASM users. It will effect all emscripten.h users I think.

I mean, we could. Do something gross (hah) like:
```
#if [not gnu]
  #define EM_ASM(...) #error don't do that
#else
 ...
```
or if `#error` doesn't work that way (and I expect it doesn't), `#define EM_ASM(x) EM_ASM_doesnt_work_without_GNU_extensions(__LINE__, x)`

**Comment by Akaricchi** [comment]
```c
#ifdef __STRICT_ANSI__
  #define EM_ASM(...) _Pragma("GCC error \"EM_ASM does not work in strict ANSI mode\"")
#else 
  ...
```

Yes, this GCC pragma works in clang.

**Comment by sbc100** [comment]
Sounds like the right solution.   Wouldn't it be better to test for what we need with something like "#ifndef __GNU__"?

**Comment by Akaricchi** [comment]
`__GNUC__` is still defined in strict ANSI mode, it just means the compiler is GCC (or, in our case, clang pretending to be GCC). `__STRICT_ANSI__` is only defined if `-std` is not `gnu`-something, which is exactly what you want to detect.

**Comment by Akaricchi** [comment]
It should be noted that I've only tested this with C, not C++. I'm not actually sure whether it's broken in strict C++ modes too or not.

**Comment by tlively** [comment]
In the SIMD intrinsics I just sprinkled __extension__ everywhere and called it a day. That worked pretty well so it might be worth investigating that further.
