### ISSUE TITLE
error in dlopen while statically linking

### ISSUE THREAD

**Issue by arturoc** [emscripten-core/emscripten#8861]
I'm linking everything statically, or at least i think so, but still getting this error:

To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking

This are the linker flags:

```
/home/arturo/Code/emsdk-portable/emscripten/1.38.28/em++ -o bin/3DPrimitivesExample.html 
-O3 -s TOTAL_MEMORY=134217728 --memory-init-file 1 obj/emscripten/Release/src/ofApp.o
 obj/emscripten/Release/src/main.o /home/arturo/Code/openFrameworks/addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenVideoPlayer.o /home/arturo/Code/openFrameworks/addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenURLFileLoader.o /home/arturo/Code/openFrameworks/addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenVideoGrabber.o /home/arturo/Code/openFrameworks/addons/obj/emscripten/Release/ofxEmscripten/src/ofxAppEmscriptenWindow.o /home/arturo/Code/openFrameworks/addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenSoundStream.o /home/arturo/Code/openFrameworks/addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenSoundPlayer.o  
/home/arturo/Code/openFrameworks/libs/openFrameworksCompiled/lib/emscripten/libopenFrameworks.bc   
-Wl,--as-needed -Wl,--gc-sections --preload-file bin/data@data --emrun 
--js-library /home/arturo/Code/openFrameworks/addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js 
--js-library /home/arturo/Code/openFrameworks/addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js 
--shell-file /home/arturo/Code/openFrameworks/libs/openFrameworksCompiled/project/emscripten/template.html 
/home/arturo/Code/openFrameworks/libs/FreeImage/lib/emscripten/libfreeimage.a 
/home/arturo/Code/openFrameworks/libs/boost/lib/emscripten/libboost_system.a 
/home/arturo/Code/openFrameworks/libs/boost/lib/emscripten/libboost_filesystem.a 
/home/arturo/Code/openFrameworks/libs/freetype/lib/emscripten/libfreetype.bc 
/home/arturo/Code/openFrameworks/libs/pugixml/lib/emscripten/libpugixml.bc 
/home/arturo/Code/openFrameworks/libs/tess2/lib/emscripten/libtess2.a 
/home/arturo/Code/openFrameworks/libs/uriparser/lib/emscripten/liburiparser.a   
```

I do include some js libraries but that wasn't a problem before and from what I read they should be compiling as static.

I'm also using opengl through EGL in case that makes any difference

**Comment by arturoc** [comment]
looking into it a bit more it seems `emscripten_set_main_loop` is doing the dlopen call and throwing the exception

**Comment by arturoc** [comment]
actually no, sorry, what seems to be triggering the error is any opengl call

**Comment by arturoc** [comment]
and specifically draw calls, something like `glEnable(GL_DEPTH_TEST)` seems to be ok but draw calls trigger the dlopen error

**Comment by kripken** [comment]
It seems odd that a gl call would end up calling dlopen, unless maybe your application code has replaced the GL calls with wrappers that do that?

A stack trace in a debug build (`-g`) might help understand what's going on there.

**Comment by arturoc** [comment]
you are right, it was something that should only run on other platforms trying to dynamically load some gl calls on my code. turning on debug build showed the exact function where the problem was happening

thanks and sorry for the noise
