### ISSUE TITLE
minification error breaks wasm2js initialization with -O2 --memory-init-file 0

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8886]
I'm trying to update ogv.js's upstream-llvm compatible builds to work with the latest goodies, including JS builds using wasm2js, but I seem to be having some trouble with minification at `-O2` or above breaking the memory init functions when using `--memory-init-file 0`.

Using a `latest-upstream` build on macOS:
```
emcc (Emscripten gcc/clang-like replacement) 1.38.37 (commit d33f7a29002a2463a7956cd53a559b97a52f9560)
```

This code fragment from wasm2js.h:

```js
    function(mem) {
      var _mem = new Uint8Array(mem);
      return function(offset, s) {
        if (typeof Buffer === 'undefined') {
          var bytes = atob(s);
          for (var i = 0; i < bytes.length; i++)
            _mem[offset + i] = bytes.charCodeAt(i);
        } else {
          var bytes = Buffer.from(s, 'base64');
          for (var i = 0; i < bytes.length; i++)
            _mem[offset + i] = bytes[i];
        }
      }
    }
```

ends up becoming this in output (exact var names vary depending on code built):

```js
                    function(mem) {
                        var N = new Uint8Array(mem);
                        return (function(offset, s) {
                            if (typeof Buffer === "undefined") {
                                var O = atob(s);
                                for (var P = 0; R < Q.length; R++)
                                    N[offset + R] = Q.charCodeAt(R)
                            } else {
                                var Q = Buffer.from(s, "base64");
                                for (var R = 0; R < Q.length; R++)
                                    N[offset + R] = Q[R]
                            }
                        }
                        )
                    }
```

Note that the `var bytes` definitions becomes both a `var O` and a `var Q` in the separate if/else branches, but the uses in both branches are for `Q`. This causes an exception during initialization:

```
Uncaught (in promise) abort("TypeError: Cannot read property 'length' of undefined"). Build with -s ASSERTIONS=1 for more info.
```

because `Q` is hoisted and left at `undefined` rather than being set to the expected value.

Example test case:

```c
#include <stdio.h>

int main(int argc, const char **argv) {
    printf("Hello, world\n");
    return 0;
}
```

```
emcc --memory-init-file 0 -O2 -s WASM=0 -o hi.html hi.c
```

**Comment by sbc100** [comment]
Presumably this is a bug in the upstream minifier.. :(

**Comment by brion** [comment]
Looks like my patch didn't quite fix it right. :(

I find this is still failing for me now, but in a silent way where it corrupts memory and later dies with an OOM. The `for` loops use the same variable name and it has the same problem, getting minified into the wrong variable for the non-Node case.

(Workaround is to disable minification, such as using `--profiling`, or use a memory init file which is probably more efficient anyway.)

I'll see if I can chase down the actual minifier bug at some point rather than chasing more symptoms...

**Comment by brion** [comment]
I'm also looking a little at the minifier; I think it's js-optimizer.js not acorn-optimizer.js that's being used here, but I'm not sure if anything from upstream uglify-js is doing that or if it's all the local optimization passes.

**Comment by sbc100** [comment]
Presumably we should address that bug in the optimizer rather than trying to tip toe around it, no?  (Sorry I don't know this area of the code well so it not obvious to me who is to blame).

**Comment by brion** [comment]
Yes, I'm not sure yet either where the fault lies, but I _think_ it's some of the operations in `js-optimizer.js` where it's renaming variables.

**Comment by kripken** [comment]
We've fixed a bunch of minification issues over the last year in wasm2js, perhaps this has been resolved?
