### ISSUE TITLE
libvpx data corruption with USE_PTHREADS, MODULARIZE on upstream backend

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#8887]
With recent updates I'm now able to build and run the ogv.js video decoder modules in multithreaded mode with the upstream LLVM backend, yay! However libvpx's VP9 decoder  gives me badly visible data corruption when run in a pthread (see https://github.com/brion/ogv.js/issues/526).

Note the VP8 decoder in the same library, as well as the dav1d AV1 decoder, run fine so this may be a fun "tricky" issue that only sometimes corrupts data that makes it to the screen...

To be sure it's not something in the use of atomics within the codec, I tried building the library single-threaded and linking it into my wrapper code with `USE_PTHREADS=1` -- when running the codec on a pthread I get the corruption, but when switching it to run on the main thread it looks fine, even when built with pthreads on.

I haven't yet narrowed down exactly what's going on but I suspect that something in the thread's memory setup is still not quite right and some bit of data is getting overwritten (maybe one of the lookup tables used in decoding).

Building with:

```
emcc (Emscripten gcc/clang-like replacement) 1.38.37 (commit d33f7a29002a2463a7956cd53a559b97a52f9560)
```

I don't have a simple repro test case yet, but the code I'm building is:
* https://github.com/brion/ogv.js "upstream-llvm" branch

Will be happy to keep trying to narrow this down, and/or can provide a full build tree with all the artifacts.

**Comment by sbc100** [comment]
There was a recent fix to stack layout in pthreads: #8811, are you using ToT?

**Comment by brion** [comment]
It's latest-upstream from a day or two ago but when I get back to my laptop I'll double check that it actually includes that fix, then test with incoming.

**Comment by brion** [comment]
Yep it appears to already include that fix, as does `emscripten-incoming-64bit`. I tried wiping out my entire emsdk and reinstalling everything from scratch, and I see no difference.

**Comment by brion** [comment]
@sbc100 I think I've identified the problem -- the stack allocated for the threads is sometimes 8-byte aligned, which seems to break some assumptions somewhere (either in libvpx or in some emscripten/musl support code, I do not know).

If I force alignment of the thread stacks to 16 bytes in `library_pthread.js` by `_malloc`'ing 16 extra bytes and bumping them up, my data corruption goes away.

```js
    if (allocatedOwnStack) {
      //stackBase = _malloc(stackSize); // Allocate a stack if the user doesn't want to place the stack in a custom memory area.
      stackBase = _malloc(stackSize + 16); // Allocate a stack if the user doesn't want to place the stack in a custom memory area.
      if (stackBase % 16 != 0) {
        console.log('unaligned stackBase ' + stackBase);
        stackBase += (16 - (stackBase % 16));
        console.log('corrected to ' + stackBase);
      }
    } else {
```

**Comment by sbc100** [comment]
Awesome news!  Thanks for tracking that down.  Must have been a real pain to find.   Do you want to send a patch?  

I wonder if we can use _memalign there to void the extra code?

**Comment by brion** [comment]
Heh yeah, lots of head-desk-thunking involved. ;)

Looks like #5996 covers the more general issue that `malloc` uses 8-byte alignment. Should we go ahead and change allocations to be 16-byte aligned in general or just manually align the stack for now?

`_memalign` should do the job, I'll whip up a provisional patch.

**Comment by sbc100** [comment]
Oh, I didn't see that issue.   I think to fair to special case the stack pointer as is has special alignment requirements.

**Comment by sbc100** [comment]
What makes you think this is an llvm-upstream-only issue?  Which malloc are you using?

Looking at the dlmalloc source code it looks like it defaults to:
```
#define MALLOC_ALIGNMENT ((size_t)(2 * sizeof(void *))) 
```

Which should be 8 for both fastcomp and the llvm-backend.

**Comment by brion** [comment]
I'm using the default malloc, which I think should be dlmalloc. I'll double-check the alignment under fastcomp, but I had no corruption problems under fastcomp either...

**Comment by brion** [comment]
Ok, fastcomp also gives me 8-byte-aligned stacks, but no corruption; while upstream gives me 8-byte aligned stacks with consistent corruption or, with the patch, 16-byte stacks with no corruption.

So the actual data corruption may be something else but it seems to be avoided by the fix to the stack alignment. Now I have no idea what's going on. :D
