### ISSUE TITLE
activate script hangs in Windows 10

### ISSUE THREAD

**Issue by bastet77** [emscripten-core/emscripten#8889]
Running .\emsdk activate --global latest 

The following messages appear and then the scrip hangs. Running as Admin.

Adding directories to PATH:
PATH += C:\users\ed\tooling\emsdk
PATH += C:\users\ed\tooling\emsdk\fastcomp\emscripten
PATH += C:\users\ed\tooling\emsdk\node\8.9.1_64bit\bin
PATH += C:\users\ed\tooling\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64
PATH += C:\users\ed\tooling\emsdk\java\8.152_64bit\bin

Setting environment variables:
EMSDK = C:/users/ed/tooling/emsdk
EM_CONFIG = C:\Users\Ed\.emscripten

ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.

**Comment by regimantas** [comment]
same problem

**Comment by Forux** [comment]
The same

**Comment by kripken** [comment]
Not sure what could be going on here. cc @juj @sbc100 who might have a guess, or an idea for how to help the reporters investigate further?

**Comment by sbc100** [comment]
Seems like it must be related to the `--global` flag or perhaps running as admin.   @Forux and @regimantas are you both running as admin too?

Does removing `--global` and / or not running as admin make the issue go away?

**Comment by dbonattoj** [comment]
Removing the `--global` flag works for me,

This issue was difficult to find as I had the french message:
`Erreur : Erreur : le système n’a pas trouvé la clé ou la valeur de Registre spécifiée.`
