### ISSUE TITLE
How to get key codes

### ISSUE THREAD

**Issue by ktb92677** [emscripten-core/emscripten#8892]
Does anyone know how to get key codes like this from Javascript?

https://www.google.com/search?q=key+codes&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi5qYeWvo3jAhVMGs0KHfEQA8IQ_AUIECgB&biw=1276&bih=979#imgrc=eeRpiMY5jf5aqM:

**Comment by VirtualTim** [comment]
This is not really the place for questions like this, but maybe this will help you?
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
