### ISSUE TITLE
template class deduction for std::array

### ISSUE THREAD

**Issue by matt1795** [emscripten-core/emscripten#8893]
Compiling something like:
```
int main() {
    std::array arr = { 1, 2, 3, 4 };
}
```
with `em++ main.cpp -std=c++17` gives me a:

 `error: no viable constructor or deduction guide for deduction of template arguments of 'array'`

I noticed that there is #8807, so I thought we might want to bring this to light as well. -- I'm also using v1.38.29

**Comment by sbc100** [comment]
This should also be fixed by #8867
