### ISSUE TITLE
wasm backend: EM_ASM incompatible with setjmp

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8894]
Testcase:

```
#include <emscripten.h>
#include <setjmp.h>

int main() {
  jmp_buf buf;
  setjmp(buf);
  EM_ASM({
    console.log("hello world");
  });
}
```

Build with `emcc  -O2`. Then when running it it fails on
```
failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): Import #8 module="env" function="emscripten_asm_const_iii" error: function import requires a callable
LinkError: WebAssembly.instantiate(): Import #8 module="env" function="emscripten_asm_const_iii" error: function import requires a callable
```
Removing the `setjmp` call fixes things.

**Comment by quantum5** [comment]
The bug appears to be in `wasm-emscripten-finalize`, where the call site to `emscripten_asm_*` gets consumed and the `EM_ASM` call is not reported as part of the metadata, but the import still remains.

**Comment by quantum5** [comment]
Taking another look, and the bug appears to have originated from LLVM.

**Comment by quantum5** [comment]
Proposed fix: https://reviews.llvm.org/D65358
