### ISSUE TITLE
-mbulk-memory generates a 500 byte zero segment embedded into .wasm

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#8899]
When using new upstream backend with the following command-line:

```
emcc src/vertexcodec.cpp src/indexcodec.cpp -O3 -DNDEBUG -s EXPORTED_FUNCTIONS='["_meshopt_decodeVertexBuffer", "_meshopt_decodeIndexBuffer"]' -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=32768 -s TOTAL_MEMORY=65536 -o build/meshopt_decoder.wasm
```

I get a 4759 byte .wasm file with the following layout:

```
meshopt_decoder.wasm:   file format wasm 0x1

Section Details:

Type[4]:
 - type[0] (i32, i32, i32) -> i32
 - type[1] () -> nil
 - type[2] (i32, i32, i32, i32, i32) -> i32
 - type[3] (i32) -> nil
Import[2]:
 - func[0] sig=0 <env.emscripten_memcpy_big> <- env.emscripten_memcpy_big
 - memory[0] pages: initial=1 <- env.memory
Function[5]:
 - func[1] sig=0
 - func[2] sig=3
 - func[3] sig=2 <meshopt_decodeIndexBuffer>
 - func[4] sig=2 <meshopt_decodeVertexBuffer>
 - func[5] sig=1 <__wasm_call_ctors>
Global[1]:
 - global[0] i32 mutable=1 - init i32=33792
Export[3]:
 - func[5] <__wasm_call_ctors> -> "__wasm_call_ctors"
 - func[4] <meshopt_decodeVertexBuffer> -> "meshopt_decodeVertexBuffer"
 - func[3] <meshopt_decodeIndexBuffer> -> "meshopt_decodeIndexBuffer"
Code[5]:
 - func[1] size=515
 - func[2] size=326
 - func[3] size=2114 <meshopt_decodeIndexBuffer>
 - func[4] size=1611 <meshopt_decodeVertexBuffer>
 - func[5] size=3 <__wasm_call_ctors>
```

A large portion of this file is the memcpy implementation; hoping to use new bulk memory instructions, I recompile with `-mbulk-memory` and get the file to be 4341 bytes (-400 bytes) with the following layout:

```
meshopt_decoder.wasm:   file format wasm 0x1

Section Details:

Type[2]:
 - type[0] () -> nil
 - type[1] (i32, i32, i32, i32, i32) -> i32
Import[1]:
 - memory[0] pages: initial=1 <- env.memory
Function[3]:
 - func[0] sig=1 <meshopt_decodeIndexBuffer>
 - func[1] sig=1 <meshopt_decodeVertexBuffer>
 - func[2] sig=0 <__wasm_call_ctors>
Global[1]:
 - global[0] i32 mutable=1 - init i32=33792
Export[3]:
 - func[2] <__wasm_call_ctors> -> "__wasm_call_ctors"
 - func[1] <meshopt_decodeVertexBuffer> -> "meshopt_decodeVertexBuffer"
 - func[0] <meshopt_decodeIndexBuffer> -> "meshopt_decodeIndexBuffer"
Code[3]:
 - func[0] size=2076 <meshopt_decodeIndexBuffer>
 - func[1] size=1598 <meshopt_decodeVertexBuffer>
 - func[2] size=3 <__wasm_call_ctors>
Data[1]:
 - segment[0] size=508 - init i32=1024
  - 0000400: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000410: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000420: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000430: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000440: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000450: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000460: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000470: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000480: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000490: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00004a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00004b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00004c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00004d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00004e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00004f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000500: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000510: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000520: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000530: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000540: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000550: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000560: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000570: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000580: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 0000590: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00005a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00005b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00005c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00005d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00005e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
  - 00005f0: 0000 0000 0000 0000 0000 0000            ............
```

While I'm happy to see 400 bytes go, I now have a 500 byte blob of zeroes at the end of my .wasm file. Is this expected with bulk memory instructions or am I doing something incorrectly?

**Comment by sbc100** [comment]
I believe you are generating an object file here.  If you want to generate a final output you need to output to .html or to .js.   Using .wasm for final output only works with SIDE_MODULE=1. 

I hope to fix this as I find the current behavior confusing.   My planned fix is to try to turn this into an error: "Unexpected linker output name, please use .js. or html when linking".

**Comment by sbc100** [comment]
In short:  try building with SIDE_MODULE=1 to see to get an optimized wasm file.

**Comment by jgravelle-google** [comment]
This is because BSS memory segments need to be actually zeroed in the presence of bulk memory. Otherwise there's no guarantee on a re-initialization of the memory that the bytes we expect to be 0 are actually 0.

Without bulk memory we are guaranteed that wasm memory is 0-initialized. Similarly with it we can be sure that the first time we instantiate we get 0ed memory, but later on that's not necessarily true. So the BSS is modeled explicitly as N 0s.

**Comment by sbc100** [comment]
To be fair, in emscripten, we always assume memory is zero'd on startup.     Therefore I think at the very least binaryen should be able to strip out these zeros.    @tlively what do you think?

**Comment by zeux** [comment]
I'll look closer into this but I'm slightly puzzled by the presence of 500-byte block in BSS segment here - none of the functions should require this. I'll try to build with SIDE_MODULE - in the past I've seen this leave extra symbols in the resulting .wasm file that I didn't need but maybe the status has improved.

**Comment by sbc100** [comment]
Hmm.. I would expect `SIDE_MODULE=1` to have the exact opposite effect, i.e. build a very minimal module with no libc or anything and import all dependencies from the main module.

**Comment by sbc100** [comment]
If you compile each of your source files to object files you should be able to see eactly where the bss data is coming from.  `wasm-objdump -x` should show this.

**Comment by tlively** [comment]
This issue arises because Binaryen's MemoryPacking pass conservatively does not run when bulk memory is enabled because it assumes the presence of passive segments and `memory.init` instructions, which it does not know how to reason about. This is clearly too conservative, since bulk memory might be enabled for a single-threaded app that would still have active segments.

In the presence of threads, this problem should be solved in the linker by not emitting segments for BSS sections at all. @sbc100 do you think it would be better to assume that memory is already zeroed when `__wasm_init_memory` is called or do you think it would be better to emit a `memory.fill` instruction to explicitly zero the memory?

**Comment by sbc100** [comment]
So can we relax the check to "if there are passive segments don't do MemoryPacking"?

I think in emscripten we have thus far assumed that memory is zero'd on init, so bss segments don't need to be explicitly initialized.

**Comment by tlively** [comment]
> So can we relax the check to "if there are passive segments don't do MemoryPacking"?

Correct.

> I think in emscripten we have thus far assumed that memory is zero'd on init, so bss segments don't need to be explicitly initialized.

Sounds good. The only edge case I can think of would be for thread local storage, where segments will be initialized after code has been running for some arbitrary time. Are there even thread-local BSS sections? This also isn't an immediate concern since we don't have any TLS at all.

**Comment by zeux** [comment]
@sbc100 Building with SIDE_MODULE=1 produces this error:

> [wasm-validator error in function $5] unexpected false: Bulk memory operation (bulk memory is disabled), on

If I disable bulk memory extension, I get the following sizes:

- SIDE_MODULE=0: 4759 bytes
- SIDE_MODULE=1: 8136 bytes

The SIDE_MODULE build includes all functions from the translation units I'm building, not just the ones mentioned in the EXPORTED_FUNCTIONS list, which looks like the reason for the increase. In addition to my own functions it also contains references to `env.stackSave` and `env.stackRestore`, `env.memset`, `env.memcpy`, all of which are absent in the build without SIDE_MODULE=0.

(as a side note, please don't remove the ability to build .wasm output with SIDE_MODULE=0 - everything else I've tried before with emscripten generated larger output; I am using a custom runtime but relying on Emscripten to create the .wasm file, so .js/.html output is not practical for me)

**Comment by zeux** [comment]
As for the 500 bytes of BSS, it's not my code that generates it - it appears that this is just added for any use of bulk memory? Here's a minimal repro:

```
#include <string.h>

extern "C"
void zero(void* ptr, size_t size)
{
}
```

```
 emcc src/foo.cpp -O3 -DNDEBUG -s EXPORTED_FUNCTIONS='["_zero"]' -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=24576 -s TOTAL_MEMORY=65536 -o build/foo.wasm -mbulk-memory
```

objdump -x shows a 508 byte zero segment in the resulting .wasm file

**Comment by tlively** [comment]
@zeux, thanks for the repro. I'll investigate to figure out where that BSS is coming from.

**Comment by tlively** [comment]
It turns out the BSS is coming from the unconditional export of `malloc` and `free`. Once the MemoryPacking pass is made to run with bulk memory enabled, that BSS should be eliminated from the output again, just like it is normally.

We should probably be smarter in the linker about emitting BSS in general, whether or not bulk memory is enabled.

**Comment by zeux** [comment]
Is there any way to suppress malloc/free export in the meantime? (I'd love to be able to do this in general to make sure malloc/free aren't pulled in accidentally...)

**Comment by tlively** [comment]
I'm not sure, maybe @kripken or @sbc100 knows.

**Comment by kripken** [comment]
We do link in malloc and free automatically since much of the runtime needs it, but metadce will remove them if they are not used. However, that can't handle the BSS - binaryen doesn't work on symbol relocations, yet. This is another reason for us to prioritize that, I think.

**Comment by zeux** [comment]
I'm not sure if anything was specifically done to improve it but with emscripten 1.38.42 I don't seem to have this problem anymore:

- compiling without bulk memory produces 4759 byte .wasm file
- compiling with -mbulk-memory produces 3822 byte .wasm file with no extraneous Data sections

**Comment by zeux** [comment]
Oh, I see, there's a linked PR merged in July that solves this. I'll close this then, thanks!
