### ISSUE TITLE
ASYNCIFY main_loop ruined because of emscripten_sleep, non-static to emscripten_wget

### ISSUE THREAD

**Issue by danilw** [emscripten-core/emscripten#8911]
maybe im missing something, sorry, maybe this is not bugs, idk (I have read emscripten.org/docs/api_reference/emscripten.h.html )

using Emscripten 1.38.31, Browsers latest Firefox/Chrome (result same)

**1. emscripten_sleep bug** minimal code:
```cpp
#include <stdio.h>
#include <emscripten.h>

//emcc -O1 test_no_sleep.c -s ASYNCIFY=1 -s WASM=1 -o build/test.html

static void main_loop(){
   printf("loop \n" );
   emscripten_sleep(5000);
   emscripten_pause_main_loop();
   emscripten_cancel_main_loop();
   printf("after emscripten_cancel_main_loop \n" );
}

int main() {
   printf("launch \n" );
   emscripten_set_main_loop(main_loop, 0, 1);
   printf("end \n" );
}
```
[compiled-link](https://danilw.github.io/OpenRCT2-wasm/test_sleep/test.html) main_loop continue after sleep and pause and cancel, removing emscripten_sleep make it work as I expect.

*emscripten_sleep_with_yield* give error(in browser, compiled with no errors): missing function: emscripten_sleep_with_yield

**2. passing non-static to emscripten_wget** ruin everything

[link to code](https://github.com/danilw/OpenRCT2-wasm/blob/master/test_async/test_wget_min.c) 53 lines, links compiled(link name equal define flag in code(1==true)) [ASYNC=1, static_buff=1](https://danilw.github.io/OpenRCT2-wasm/asynk_wget/async_static/test.html) [ASYNC=1, static_buff=0](https://danilw.github.io/OpenRCT2-wasm/asynk_wget/asynk_no_static/test.html) [ASYNC=0, static_buff=0](https://danilw.github.io/OpenRCT2-wasm/wget_no_static/async_static/test.html) [ASYNC=0, static_buff=1](https://danilw.github.io/OpenRCT2-wasm/asynk_wget/wget_static/test.html)

ASYNC mean using *emscripten_async_call* to call *emscripten_wget*, result images  [ASYNC=1, static_buff=1](https://user-images.githubusercontent.com/24825887/60604597-afc95600-9dc0-11e9-9a6c-33ab5f63d771.png) [ASYNC=1, static_buff=0](https://user-images.githubusercontent.com/24825887/60604594-af30bf80-9dc0-11e9-8dfa-beff7a11f454.png) [ASYNC=0, static_buff=0](https://user-images.githubusercontent.com/24825887/60604599-afc95600-9dc0-11e9-84aa-4ce2bba2a591.png) [ASYNC=0, static_buff=1](https://user-images.githubusercontent.com/24825887/60604600-afc95600-9dc0-11e9-95e6-ad265c19d63f.png) (only ASYNC=1, static_buff=1 work as expected I think)

**3. using emscripten_wget with emscripten_sleep** ruin everything

[code link](https://github.com/danilw/OpenRCT2-wasm/blob/master/test_async/test_wget_big.c), compiled link [TEST=4](https://danilw.github.io/OpenRCT2-wasm/test_s/test4//test.html)

In "big project" enabling ASYNCIFY ruin everything, generated WASM file is 10x times bigger(from 8mb to 90mb), adding *emscripten_cancel_main_loop* before main_loop call make it "launch"...

P.S. bug with "passing only static variables" exist also with "callbacks"(lambda/anonymous functions)
non-static variables outside of "function from which call_back called" does not exist, (call_back function does not have it)
(this bug I found only in very large and complicated code, still not sure if it emscripten bug, or its in code...can not make simple example for this)

sorry if it all my mistake somewhere, maybe im wrong in everything

**Comment by kripken** [comment]
Note that Asyncify is no longer supported, see the note at the top here: https://github.com/emscripten-core/emscripten/wiki/Asyncify

I'd recommend using the [LLVM wasm backend](https://v8.dev/blog/emscripten-llvm-wasm) + Bysyncify. It should be much better than Asyncify on code size, in particular. Please let me know if those bugs exist there too, and if code size does not improve dramatically from the 10x bigger you saw with Asyncify.

**Comment by danilw** [comment]
didn't knew that
thanks

**Comment by sbc100** [comment]
Can/should we completely remove Asyncify today?   if only to reduce complexity?

**Comment by kripken** [comment]
Yeah, maybe after we switch to the wasm backend by default we can announce we are removing Asyncify, and then do that later, and then it won't all happen at once when we remove fastcomp.

**Comment by VirtualTim** [comment]
@danilw Personally I'm using `std::this_thread::sleep_for` with surprising success. Maybe that would help you, depending on what exactly you're trying to achieve.
