### ISSUE TITLE
"static EMSCRIPTEN_KEEPALIVE" diverges on fastcomp/upstream

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8916]
On fastcomp, it still exports the function on Module, even though it is `static`. On upstream, it stays alive but is not exported.

I'm not sure which is "better", as "static" and "export" seem contradictory. But worth discussing perhaps since this is a difference between the backends.

This explains part of https://github.com/emscripten-core/emscripten/issues/8718

**Comment by sbc100** [comment]
I think "EMSCRIPTEN_KEEPALIVE" really means EMSCRIPTEN_EXPORT, right?  So I think fastcomp is correct here.

However, as you say I kind of think its user error to have this on a static... so I don't care too much about fixing it.

**Comment by sbc100** [comment]
I think the llvm backend behaviour is defensible and we are soon gonna remove fastcomp.  So closing this as wontfix.  Please re-open if you disagree.
