### ISSUE TITLE
Constructor attribute in libc does not work on wasm backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#8917]
See `__emscripten_pthread_data_constructor` which is defined here, with the constructor attribute on it:

https://github.com/emscripten-core/emscripten/blob/6e4b98636618989bcd99308391e51aa1b81f4c61/system/lib/libc/musl/src/misc/emscripten_pthread.c#L13

In fastcomp that works as expected. In upstream, the first issue is it isn't linked in. I assume that's since we use a `.a`. Adding it to the exported functions, it's included, but not run automatically.

Should this work?

**Comment by sbc100** [comment]
I'm pretty sure it does work.. but you need to make sure that particular .o file gets pulled in.   My guess is that you not referencing the .o file at all so it discarding that object.   Does that sounds right?

**Comment by kripken** [comment]
Yes, I believe you are right - I was testing this incorrectly back then.
