### ISSUE TITLE
sscanf does not handle UTF-8 characters beyond ASCII-7 (code point > 0x7F)

### ISSUE THREAD

**Issue by sbalko** [emscripten-core/emscripten#892]
sscanf does not currently handle characters beyond the 128 ASCII-7 characters. This is because it simply accesses a string a one-character-per-byte lookup on HEAP8.

**Comment by Tyrben** [comment]
So far, C `sscanf` manages at least 2 bytes unicode characters in condition to store it in 2 bytes (aka UTF-16 without multi-word, aka UCS-2)

```
wchar_t warr[1];
char input[] = "水";
int ret = sscanf(input, "%2lc", warr);
printf("Converted into warr[0] = U+%x", warr[0]);
```
