### ISSUE TITLE
llvm upstream EMSCRIPTEN is not defined

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#8921]
Hi. I know that llvm-upstream should became default soon and now I want to test it over all projects that I have. I am started with very simple one, and I can't compile it.
I am using emsdk with installed latest-upstream, latest-fastcomp. 
I found that in upstream `#define EMSCRIPTEN` is missed (looks like it ships somewhere internally in fastcomp).  If it's true, then it's breaking change but I have not success with googling it.

**My testcase:**
CMakeLists.txt
```
add_executable(main "main.cpp")
```

main.cpp
```
#ifdef EMSCRIPTEN
    emscripten defined
#else
    emscripten NOT defined
#endif
```

To build I used this commands:
```
./emsdk activate --embded latest-upstream/latest
source ./emsdk_env.sh
emcmake cmake -GNinja ..
ninja -v
```

Output for fastcomp:
```
[1/2] /home/caiiiycuk/emscripten/sdk/emsdk/fastcomp/emscripten/em++     -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
FAILED: CMakeFiles/main.dir/main.cpp.o 
/home/caiiiycuk/emscripten/sdk/emsdk/fastcomp/emscripten/em++     -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
../main.cpp:2:5: error: unknown type name 'emscripten'
    emscripten defined
    ^
../main.cpp:2:23: error: expected ';' after top level declarator
    emscripten defined
                      ^
                      ;
2 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
ninja: build stopped: subcommand failed.
```

output for upstream:
```
[1/2] /usr/bin/c++    -g -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
FAILED: CMakeFiles/main.dir/main.cpp.o 
/usr/bin/c++    -g -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
../main.cpp:4:5: error: ‘emscripten’ does not name a type
     emscripten NOT defined
     ^~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by kripken** [comment]
Thanks @caiiiycuk, I think we forgot about this. I opened https://github.com/emscripten-core/emscripten/pull/8924 now. I'm not sure what we'll decide though, maybe we just want `__EMSCRIPTEN__`. I'd suggest changing ifdefs to use that, which looks more "standard" anyhow.

**Comment by VirtualTim** [comment]
Apparently `EMSCRIPTEN` is deprecated.
https://github.com/emscripten-core/emscripten/blob/9aff7f29885ed34ea42f129ec718f3c0f0fdd018/emcc.py#L672-L673

**Comment by sbc100** [comment]
You seems to have different problem.   The build you call "upstream" is building with /usr/bin/c++.   This will certainly not define any emscripten stuff.   You still need to use emcc/em++ when building with the upstream backend.

**Comment by caiiiycuk** [comment]
This output compiler is taken from emsdk, I didn't configure compiler by myself.

**Comment by caiiiycuk** [comment]
@sbc100 Yes you right, I just rechecked everything and new correct log is:
```
[1/2] /home/caiiiycuk/emscripten/sdk/emsdk/upstream/emscripten/em++     -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
FAILED: CMakeFiles/main.dir/main.cpp.o 
/home/caiiiycuk/emscripten/sdk/emsdk/upstream/emscripten/em++     -MD -MT CMakeFiles/main.dir/main.cpp.o -MF CMakeFiles/main.dir/main.cpp.o.d -o CMakeFiles/main.dir/main.cpp.o -c ../main.cpp
../main.cpp:4:5: error: unknown type name 'emscripten'
    emscripten NOT defined
    ^
../main.cpp:4:19: error: expected ';' after top level declarator
    emscripten NOT defined
                  ^
                  ;
2 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
ninja: build stopped: subcommand failed.
```
--
Anyway I think this problem is confirmed. It's not a big problem to switch on __EMCSCRIPTEN__, just need to add message about this in migration guide.
