### ISSUE TITLE
Support HEAP64/HEAPU64

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8925]
All the other typed arrays are supported (ie HEAP8, HEAPF32), except for HEAP64/HEAPU64.
Chrome 67, Firefox 68 support this via [BigInt64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) and [BigUint64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array). Edge/IE/Safari doesn't yet support them.

I guess this should be behind a build flag?

Safari bug is here: https://bugs.webkit.org/show_bug.cgi?id=179001

**Comment by VirtualTim** [comment]
I'm happy to take a crack at implementing this, if people support the addition.

**Comment by kripken** [comment]
Good idea, yeah - makes sense to add this, and I agree it should be behind a flag for now.

**Comment by kripken** [comment]
We have full support for BigInt now, but we didn't need to add BigInt64Array support for that. But adding `HEAP64` might be useful in that case, so leaving open if someone wants to add that - could be a simple addition, just ifdefed on whether `WASM_BIGINT` is set.
