### ISSUE TITLE
Emsdk on Windows uses SDK root directory different from tutorial

### ISSUE THREAD

**Issue by yeputons** [emscripten-core/emscripten#8927]
See [Emscripten Tutorial](https://emscripten.org/docs/getting_started/Tutorial.html):

> Navigate with the command prompt to the SDK root directory for your target SDK. This is an SDK-version-specific folder below the emsdk root directory, for example <emsdk root directory>/emscripten/1.20.0/.

However, in my installation there is no `emscripten` directory under emsdk root directory and there is no versioned directory, but there is `fastcomp/emscripten` instead. I suspect the documentation should be updated (unless there are still version-specific folders):

> Navigate with the command prompt to the SDK root directory for your target SDK: `<emsdk root directory>/fastcomp/emscripten`.

I've cloned `emsdk` from [35cd9268f0e490f9039baed97ae2b99a7bfeed48](https://github.com/emscripten-core/emsdk/commit/35cd9268f0e490f9039baed97ae2b99a7bfeed48), ran `emsdk install latest` followed by `emsdk activate latest` followed by `emsdk activate latest --global` as Administrator.

Here are all directories in my emsdk directory not deeper than three levels:

```
.
./.git
./.git/hooks
./.git/info
./.git/logs
./.git/logs/refs
./.git/objects
./.git/objects/info
./.git/objects/pack
./.git/refs
./.git/refs/heads
./.git/refs/remotes
./.git/refs/tags
./bin
./fastcomp
./fastcomp/bin
./fastcomp/emscripten
./fastcomp/emscripten/.circleci
./fastcomp/emscripten/cmake
./fastcomp/emscripten/docs
./fastcomp/emscripten/media
./fastcomp/emscripten/site
./fastcomp/emscripten/src
./fastcomp/emscripten/system
./fastcomp/emscripten/tests
./fastcomp/emscripten/third_party
./fastcomp/emscripten/tools
./fastcomp/fastcomp
./fastcomp/fastcomp/bin
./fastcomp/fastcomp/include
./fastcomp/fastcomp/lib
./fastcomp/fastcomp/libexec
./fastcomp/fastcomp/msbuild-bin
./fastcomp/fastcomp/share
./fastcomp/fastcomp/tools
./fastcomp/include
./fastcomp/include/clang-c
./fastcomp/include/llvm-c
./fastcomp/lib
./fastcomp/lib/asmjs
./fastcomp/lib/clang
./fastcomp/lib/wasm-obj
./fastcomp/libexec
./fastcomp/share
./fastcomp/share/clang
./fastcomp/share/man
./fastcomp/share/opt-viewer
./fastcomp/share/scan-build
./fastcomp/share/scan-view
./java
./java/8.152_64bit
./java/8.152_64bit/App
./java/8.152_64bit/bin
./java/8.152_64bit/Data
./java/8.152_64bit/lib
./java/8.152_64bit/Other
./node
./node/8.9.1_64bit
./node/8.9.1_64bit/bin
./python
./python/2.7.13.1_64bit
./python/2.7.13.1_64bit/notebooks
./python/2.7.13.1_64bit/python-2.7.13.amd64
./python/2.7.13.1_64bit/scripts
./python/2.7.13.1_64bit/settings
./python/2.7.13.1_64bit/tools
./releases
./releases/.git
./releases/.git/hooks
./releases/.git/info
./releases/.git/logs
./releases/.git/objects
./releases/.git/refs
./releases/tools
./zips
```

UPD: if I install `emsdk install sdk-1.38.6-64bit`, then I get `./emscripten/1.38.6` directory as expected.

**Comment by kripken** [comment]
Thanks @yeputons! Yes, this changed recently, and we forgot to update the tutorial. Fix in #8956
