### ISSUE TITLE
embind: Cannot pass vector of strings from JS to C++

### ISSUE THREAD

**Issue by kornerr** [emscripten-core/emscripten#8933]
I'm using Emscripten 1.38.37 on Linux.

C++:
```
std::vector<std::string> cpparray(const std::vector<std::string> &values)
{
    printf("cpparray values:\n");
    for (auto value : values)
    {
        printf("- '%s'\n", value.c_str());
    }
    return values;
}

EMSCRIPTEN_BINDINGS(mycpparray) {
    emscripten::register_vector<std::string>("StringList");
    emscripten::function("cpparray", &cpparray);
}
```

JavaScript:
```
Module.cpparray(["One", "Two", "1.234", "Four"]);
```

Error:
```
uncaught exception: BindingError: Cannot pass "One,Two,1.234,Four" as a StringList
```

Any idea what I'm doing wrong?

**Comment by yeputons** [comment]
As far as I understand, there is no conversion from JS' `Array` to `std::vector` (unlike `String` and `std::string`).

You can populate vector manually, though:

```
const vec = new Module.StringList();
vec.push_back("One");
vec.push_back("Two");
vec.push_back("1.234");
vec.push_back("Four");
Module.cpparray(vec);
```

Would be happy if someone more proficient in embind confirms, denies and/or provides a link to corresponding tracking issue (if any).

**Comment by kornerr** [comment]
Thanks, @yeputons, that works!

PS Hi from St. Pete ;)

**Comment by sandeep-dorsavi** [comment]
For some reason it didnt work for me while setting a decimal vector. 
I then tried the above peace of code but still gettig the same error.. 

 Uncaught (in promise) TypeError: root.StringList is not a constructor

Could this be due to the newer vesion of emscripten? Not finding a way to pass a vector string as function parameter from JS to C++

**Comment by yeputons** [comment]
@sandeep-dorsavi Looks like you have not registered `vector<string>` as `StringList` via `EMSCRIPTEN_BINDINGS`.

**Comment by sandeep-dorsavi** [comment]
@yeputons I have already registered them as below, no idea whats been missed? As you can see getting same error if i try to set a vector string or a vector double.

C++ Binding cpp:

```
 
EMSCRIPTEN_BINDINGS(AttitudeEstimatorBinding)
{

    register_vector<double>("DoubleList");
    register_vector<std::string>("StringList");

    class_<AttitudeEstimatorBase>("AttitudeEstimatorBase")
        .constructor<>()
        .function("StringTest", &AttitudeEstimatorBase::StringTest)
        .function("DoubleTest", &AttitudeEstimatorBase::DoubleTest) 
}
```
 

CPP:

`emscripten::val AttitudeEstimatorBase::StringTest(std::vector<std::string> input)`
{

    int length = input.size();
    std::string inputArray[length];

    std::copy(input.begin(), input.end(), inputArray);

    val entry = val::object();
    entry.set(std::string("FirstItem"), inputArray[0]);

    return entry;
}
```
 
emscripten::val AttitudeEstimatorBase::DoubleTest(std::vector<double> input)
{

    int length = input.size();
    double inputArray[length];

    std::copy(input.begin(), input.end(), inputArray);

    val entry = val::object();
    entry.set(std::string("FirstItem"), inputArray[0]);

    return entry;
}

```

JSX:

```

   function RunCcode() {

     AEAlgo.then((core) => {
     
        const Module = new core.AttitudeEstimatorBase();      
        var strList = new Module.StringList(); 
        strList.push_back("One");
        strList.push_back("Two");       
        console.log('strList',strList);
        var objStr = Module.StringTest(strList); 

        var dbleList = new Module.DoubleList(); 
        dbleList.push_back(0.123);
        dbleList.push_back(1.345);      
        console.log('dbleList',strList);  
        var objDble = Module.DoubleTest(dbleList);
        console.log('ResultObjs',objStr,objDble);
        
     });
```

Error:

![image](https://user-images.githubusercontent.com/74334980/112747957-7ad54c00-9004-11eb-8f2a-851461dd5f76.png)

**Comment by yeputons** [comment]
@sandeep-dorsavi I suspect you did not wait until emscripten's runtime is initialized before accessing embind's stuff.

Here is a working example: https://gist.github.com/yeputons/8591cc26cc1b61d3503b0cb3b4623001

**Comment by sandeep-dorsavi** [comment]
Hi @yeputons, Thanks for suggestion, it was initilized as below

```
import AttitudeEstimator from '../../cpp/AttitudeEstimatorA/Wasm/AttitudeEstimator.js';
import AttitudeEstimatorWASM from '../../cpp/AttitudeEstimatorA/Wasm/AttitudeEstimator.wasm';

const AEAlgo = AttitudeEstimator({
    locateFile: () => {
        return AttitudeEstimatorWASM;
    },
});
```


I found the issue though - in the emscript binding file = as the vectors were not defined at the class level (but were at the root level) so I had to change 2 lines to make it working.

 ```
    AEAlgo.then((core) => {
        console.log('came');
     
        const Module = new core.AttitudeEstimatorBase();
        console.log('came1',Module);

        var strList = new core.StringList(); // <--Changed from Module.StringList()
        strList.push_back("One");
        strList.push_back("Two");       
        console.log('strList',strList);
        var objStr = Module.StringTest(strList); 

        var dbleList = new core.DoubleList();   // <--Changed from Module.DoubleList()
        dbleList.push_back(0.123);
        dbleList.push_back(1.345);      
        console.log('dbleList',strList);  
        var objDble = Module.DoubleTest(dbleList);

        console.log('ResultObjs',objStr,objDble);

     });

   }
```

In the bindings, the vectors were not defined under the class

```
EMSCRIPTEN_BINDINGS(AttitudeEstimatorBinding)
{

    register_vector<double>("DoubleList"); //<-- defined here but not under class
    register_vector<std::string>("StringList");

    class_<AttitudeEstimatorBase>("AttitudeEstimatorBase")
        .constructor<>()
        .function("StringTest", &AttitudeEstimatorBase::StringTest)
        .function("DoubleTest", &AttitudeEstimatorBase::DoubleTest) 
}
```

**Comment by MaheshVelankar** [comment]
I am new to webassembly / emscripten /embind world.
I do not intend to write off-topic comment here; however I did not find any other suitable place to start with. Kindly move the commment to any other appropriate place.

-----------------------------------

I am trying to write a web application that will do sort of word processing (say spell check, grammar check, word analysis) using back-end C/C++ code. (I have got c/C++ code working in another desktop app... I want to bring it to web). I want an example minimal code doing this (pass **array of strings** from JavaScript to c/c++ code...c/c++ code will do the word operations... I have this code ......and the resulting **array of strings** will be sent back to JavaScript where they will be processed further. (passing **arrays** to and from is important) Please point me to any such code/tutorial, from where I can make a start.

I searched GitHub. I found several projects using emscripten but could not get this anywhere. (Only place I could get some clue was Hunspell built with emscripten ... however I could not build it successfully)

Please let me know . Thanks in advance.
