### ISSUE TITLE
setjmp breaks with WASM_OBJECT_FILES=0

### ISSUE THREAD

**Issue by Keno** [emscripten-core/emscripten#8935]
Consider:
```
#include <setjmp.h>

int main() {
    jmp_buf jmp;
    setjmp(jmp);
    return 0;
}
```
With:
```
emcc -s WASM_OBJECT_FILES=0 -s WASM=1 -s SAFE_HEAP=1 test.c -o test.html
```
opening test.html will print "segmentation fault" (and corresponding errors will appear in the log). However,
```
emcc -s WASM_OBJECT_FILES=1 -s WASM=1 -s SAFE_HEAP=1 test.c -o website/test.html
```
exits fine and does not cause a segmentation fault error.

**Comment by kripken** [comment]
No idea what's going on here, but this does look like a hole in our testing - `wasm0.test_longjmp` passes (and we test constantly), while `wasmlto0.test_longjmp` fails, possibly for the same reason as this issue, and we don't run the `wasmlto*` tests on CI normally.

Once fixed perhaps we should test all of them, or at least part?

**Comment by aheejin** [comment]
Uploaded a fix: https://reviews.llvm.org/D67129
