### ISSUE TITLE
access() crashes when given path is empty

### ISSUE THREAD

**Issue by rhysd** [emscripten-core/emscripten#8937]
- emscripten: 1.38.32
- macOS 10.12

Project: https://github.com/rhysd/vim.wasm

<img width="528" alt="スクリーンショット 2019-07-08 1 52 55" src="https://user-images.githubusercontent.com/823277/60771760-2e0e5b00-a127-11e9-8905-e051d0183fb2.png">

I could only reproduce this issue with unit test on release build. So there is no sourcemap. Unfortunately, Chrome crashes after a while so I also could not investigate further. But it seems that `access()` crashes when empty string is given.

**Comment by kripken** [comment]
Do you mean the access API called from C or from JS?

Would be good to get a small testcase for this if possible.

**Comment by kripken** [comment]
I don't see a problem with this testcase:
```
#include <unistd.h>
int main() {
  return access("", F_OK);
}
```

**Comment by rhysd** [comment]
Actually it was caused in vim.wasm. Let me try to make a small size reproduction.

**Comment by rhysd** [comment]
I'm sorry that I mistook the pre-condition. First argument was actually `NULL`. However, simpler reproduction as follows does not reproduce above crash.

```c
#include <stdio.h>
#include <unistd.h>
#include <errno.h>

int main()
{
    printf("%d\n", access(NULL, 0755));
    printf("%d\n", errno);
    return 0;
}
```

Let me close this for now. And when I face this issue and pre-condition is made clearer, let me reopen this again.
