### ISSUE TITLE
Race condition in test_runtime_misuse tests

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#8939]
In the test_runtime_misuse tests test reporting is done in a setTimeout. This makes the test pretty fragile, because if the timings change things will break.
I tried to fix it as part of #8926, but I think the test need a more serious rewrite, and it's better to make it it's own PR instead of sticking it to another.

Also it looks like `free` should be removed from runtime_misuse_2.cpp, since it was removed from runtime_misuse.cpp 4 years ago https://github.com/emscripten-core/emscripten/commit/3ddc9f28726bcb209829aa83792e8ebbcb99b80c.

@kripken, you wrote the test originally (https://github.com/emscripten-core/emscripten/commit/0f8e6d992cfc5b363bfa4aa07c3d8de96b301ac5), what are your thoughts?

https://github.com/emscripten-core/emscripten/blob/57387d023f8410e7bf22cd6f3501764a1e90b81d/tests/test_browser.py#L2328-L2334

**Comment by kripken** [comment]
Yeah, would be good to remove any possible async timing issues. I think there isn't anything async in that test but that one setTimeout? So seems like we can just put the code in that callback in the right place, which I think is after `myJSCallback`, maybe in a finally or the next browser event loop iteration.

**Comment by VirtualTim** [comment]
I tried adding the body of that function to `myJSCallback`, but that's not called in all configurations, and it's not even guaranteed to be the last thing called.

I'm not really sure how to tackle this without basically rewriting the whole test.
