### ISSUE TITLE
wasm-ld bug

### ISSUE THREAD

**Issue by truedim** [emscripten-core/emscripten#8981]
`em++ file1.cpp file2.cpp`

where file1.cpp and file2.cpp are the same:
```cpp
template <typename T> struct foo {
	foo() :v(s) {}
	T& v;
	static T s;
};
template <typename T> T foo<T>::s = T();
struct bar{ ~bar() { foo<bar>(); }};
```

**Assertion failed: FunctionIndex != INVALID_INDEX, file C:\b\s\w\ir\cache\builder\emscripten-releases\llvm-project\lld\wasm\Symbols.cpp, line 152**

The bug also can be reproduced with
`boost/math/special_functions/binomial.hpp` 
`boost/spirit/home/support/utree.hpp`

It only happens with upstream WASM backend.

**Comment by kripken** [comment]
Thanks @truedim!

 @sbc100 Looks like this might be an unknown wasm-ld bug?

**Comment by sbc100** [comment]
Fix is at https://reviews.llvm.org/D64872
