### ISSUE TITLE
Make lzma available via emscripten-ports?

### ISSUE THREAD

**Issue by kml27** [emscripten-core/emscripten#8984]
Would it be simple enough to provide the lzma lib (e.g. already noticed lzma.js) via emscripten-ports? 

Is there some non-obvious reason preventing it?

**Comment by kripken** [comment]
It should be pretty easy to add, especially if lzma has a github repo already, see for example

https://github.com/emscripten-core/emscripten/blob/incoming/tools/ports/icu.py

(and the commits on that file, especially #7167 where it was initially added).

**Comment by kripken** [comment]
This should be even easier now after @sbc100 's recent changes to ports additions. Are there docs for that?

**Comment by sbc100** [comment]
Yes, I'm actually using lzma as a prototype for the new "contrib" ports system.   Thanks for reminding me about this issue.
