### ISSUE TITLE
eglDestroyContext duplicated

### ISSUE THREAD

**Issue by samsinsane** [emscripten-core/emscripten#8987]
It looks like `eglDestroyContext` was duplicated at some point, is this intentional/correct?
https://github.com/emscripten-core/emscripten/blob/c28a629cd5ddc9a4ec5f89ef7a55e8f78a808b31/src/library_egl.js#L388-L391
https://github.com/emscripten-core/emscripten/blob/c28a629cd5ddc9a4ec5f89ef7a55e8f78a808b31/src/library_egl.js#L409-L410

The second implementation doesn't actually destroy the context, and it appears to be the implementation that ends up being used.

**Comment by VirtualTim** [comment]
Looking at the blame it looks like two people implemented it independently at the same time; @juj here: https://github.com/emscripten-core/emscripten/commit/40ca8f65b04a7b8128a82e90c2f3cef0c60a0656 and @michaeljbishop  here: https://github.com/emscripten-core/emscripten/commit/5ccadef8807c2c1bc597b6c439cfe1dff967a48a a day later.

This was done almost 7 years ago, so I'm surprised no one else picked it up.

**Comment by juj** [comment]
Good find. Most web page uses are "init only" without deinitialization, and EGL was never updated with multithreading in mind (I had a stab at #5580, but never had time to finish that up, and at some point dropped using EGL in favor of the more straightforward HTML5 context init API)
