### ISSUE TITLE
'978' inserted between 'support.js' and 'preamble.js'

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#9020]
Really weird issue, the compiled js looks like this:

```
[...]
// The address globals begin at. Very low in memory, for code size and optimization opportunities.
// Above 0 is static memory, starting with globals.
// Then the stack.
// Then 'dynamic' memory for sbrk.
var GLOBAL_BASE = 1024;


978// === Preamble library stuff ===
[...]
```
Somehow '978' ended up there between the first block (from `support.js`), and the second block (from `preamble.js`).
978 is the number of lines in `support.js`. I imagine the fix is something obvious/simple, but I can't see where these two files are stitched together.

**Comment by kripken** [comment]
`src/jsifier.js` emits most of the core JS. Here is where it prints preamble:

https://github.com/emscripten-core/emscripten/blob/incoming/src/jsifier.js#L450

So some debug printouts right before that might help.

This is definitely weird, I don't think I've ever seen this happen... curious what it is!

**Comment by sbc100** [comment]
Its obviously a very important magic number.    Change it at your own risk!

**Comment by VirtualTim** [comment]
This was just an issue with my local setup. Lets just blame this one on me not getting enough sleep.
