### ISSUE TITLE
switched to upstream: getting an Optional.h hasValue assert

### ISSUE THREAD

**Issue by tjenssen** [emscripten-core/emscripten#9023]
after setting set EMCC_DEBUG=2
the linker step

```
emcc:DEBUG: emcc step "calculate system libraries" took 1.13 seconds
emcc:DEBUG: linking: ['C:/dev/emsdk/qt5/qtbase/lib/libqtfreetype.a', 'C:/dev/emsdk/qt5/qtbase/lib/libqtlibpng.a', 'main.obj', 'qmlprojectrunner.js_plugin_import.obj', 'C:/dev/emsdk/qt5/qtbase/plugins/platforms/libqwasm.a', 'C:/dev/emsdk/qt5/qtbase/lib/libQt5EventDispatcherSupport.a', 'C:/dev/emsdk/qt5/qtbase/lib/libQt5FontDatabaseSupport.a', 'C:/dev/emsdk/qt5/qtbase/lib/libqtfreetype.a', 'C:/dev/emsdk/qt5/qtbase/lib/libQt5EglSupport.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqgif.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqicns.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqico.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqjpeg.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqtga.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqtiff.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqwbmp.a', 'C:/dev/emsdk/qt5/qtbase/plugins/imageformats/libqwebp.a', 'C:/dev/emsdk/qt5/qtbase/lib/libQt5Gui.a', 'C:/dev/emsdk/qt5/qtbase/lib/libqtlibpng.a', 'C:/dev/emsdk/qt5/qtbase/lib/libqtharfbuzz.a', 'C:/dev/emsdk/qt5/qtbase/lib/libQt5Core.a', 'C:/dev/emsdk/qt5/qtbase/lib/libqtpcre2.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libc.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libcompiler_rt.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libc-wasm.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libc++-noexcept.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libc++abi.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libc-extras.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libgl.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libdlmalloc.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libpthreads_stub.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libcompiler_rt_wasm.a', 'C:\\Users\\tijensse\\.emscripten_cache\\wasm-obj\\libc_rt_wasm.a']

```
 fails with
`
Assertion failed: hasVal, file C:\b\s\w\ir\cache\builder\emscripten-releases\llvm-project\llvm\include\llvm/ADT/Optional.h, line 177
`
a very simple c++ application just works

with fastbuild everything was working as expected, not sure what kind of information I can also bring up, just ask me if you need anything!

**Comment by sbc100** [comment]
Can you post the full error message output from LLVM?

**Comment by tjenssen** [comment]
not sure what you mean, but here is the complete output: https://pastebin.com/diJHsuPK

**Comment by tjenssen** [comment]
If I do:
em++ -s ERROR_ON_UNDEFINED_SYMBOLS=0 --source-map-base http://localhost:8000/ -o ./qmlprojectrunner.js main.obj qmlprojectrunner.js_plugin_import.obj   C:/dev/emsdk/qt5/qtbase/plugins/platforms/libqwasm.a C:/dev/emsdk/qt5/qtbase/lib/libQt5FontDatabaseSupport.a C:/dev/emsdk/qt5/qtbase/lib/libQt5Gui.a C:/dev/emsdk/qt5/qtbase/lib/libQt5Core.a

I am getting the same error, if I remove one of these libs, the error is gone

**Comment by tjenssen** [comment]
LD_DEBUG seems to be ignored, how can I debug the linker?

**Comment by sbc100** [comment]
You can pass "-verbose" and/or "-mllvm -debug" to wasm-ld.   (Or -Wl,-verbose -Wl,-mllvm,-debug to clang or emcc).

You might find that --no-threads is useful too since it avoid interleaved output from the threaded parts.

I didn't know about LD_DEBUG!  I will look into adding support for that in lld.

**Comment by sbc100** [comment]
Normally I would expect a more useful error output from llvm. @dschuff would we expect no backtrace in the llvm assert failure?  Should we be building with more debug information in there?

**Comment by tjenssen** [comment]
ok just added your proposed flags to emcc, this is the output:

`applying relocations: .data.__stdout_used count=1
apply reloc: type=getVirtualAddress: R_WASM_SECTION_OFFSET_I32f
apply reloc: type=R_WASM_MEMORY_ADDR_I32 addend=0 index=0 value=3586336 offset=167
 addend=applying relocations: .data.__cxa_terminate_handler count=13439 index=167
 value=apply reloc: type=R_WASM_TABLE_INDEX_I32 addend=03791925 index= offset=0 value=5300 offset=123978
6
apply reloc: type=R_WASM_SECTION_OFFSET_I32 addend=175490applying relocations:  index=.data._ZL5cause167 value=3963976 count= offset=1124001

getVirtualAddress: .L.str.4
apply reloc: type=R_WASM_MEMORY_ADDR_I32 addend=apply reloc: type=R_WASM_SECTION_OFFSET_I32 addend=0 index=352317 value= index=3476268 offset=74167 value=3792009
 offset=124005
apply reloc: type=R_WASM_SECTION_OFFSET_I32 addend=175510 index=167 value=3963996 offset=124028
apply reloc: type=R_WASM_SECTION_OFFSET_I32 addend=3439 index=167 value=3791925 offset=124032
`
and then many similar lines from 1434273 to 3178780 and then

`apply reloc: type=R_WASM_SECTION_OFFSET_I32 addend=405147 index=124 value=34657526 offset=284792
Assertion failed: hasVal, file C:\b\s\w\ir\cache\builder\emscripten-releases\llvm-project\llvm\include\llvm/ADT/Optional.h, line 177
 #0 0x00007ff61554da25 (C:\dev\emsdk\upstream\bin\wasm-ld.exe+0xada25)
 #1 0x00007fff7515d167 (C:\Windows\System32\ucrtbase.dll+0x6d167)
 #2 0x00007fff7515dff1 (C:\Windows\System32\ucrtbase.dll+0x6dff1)
...
`

**Comment by akien-mga** [comment]
I get a similar issue compiling [Godot Engine](https://github.com/godotengine/godot): godotengine/godot#30756.

On Linux I seem to have some more debug symbols and a more verbose stacktrace:
```
wasm-ld: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/include/llvm/ADT/Optional.h:177: const T &llvm::optional_detail::OptionalStorage<unsigned int, true>::getValue() const & [T = unsigned int]: Assertion `hasVal' failed.
 #0 0x00007fb376481af4 PrintStackTraceSignalHandler(void*) (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/../lib/libLLVM-9svn.so+0x6c6af4)
 #1 0x00007fb37647f7ae llvm::sys::RunSignalHandlers() (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/../lib/libLLVM-9svn.so+0x6c47ae)
 #2 0x00007fb376481da8 SignalHandler(int) (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/../lib/libLLVM-9svn.so+0x6c6da8)
 #3 0x00007fb379294560 __restore_rt (/lib64/libpthread.so.0+0x13560)
 #4 0x00007fb37594ba7a raise (/lib64/libc.so.6+0x3ca7a)
 #5 0x00007fb375934524 abort (/lib64/libc.so.6+0x25524)
 #6 0x00007fb37593440f _nl_load_domain.cold.0 (/lib64/libc.so.6+0x2540f)
 #7 0x00007fb3759409a2 (/lib64/libc.so.6+0x319a2)
 #8 0x00000000006a7ad2 (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/wasm-ld+0x6a7ad2)
 #9 0x0000000000690267 lld::wasm::InputChunk::writeTo(unsigned char*) const (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/wasm-ld+0x690267)
#10 0x00000000006befad lld::wasm::CustomSection::writeTo(unsigned char*) (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/wasm-ld+0x6befad)
#11 0x00000000006bac7d std::_Function_handler<void (), void llvm::parallel::detail::parallel_for_each<__gnu_cxx::__normal_iterator<lld::wasm::OutputSection**, std::vector<lld::wasm::OutputSection*, std::allocator<lld::wasm::OutputSection*> > >, (anonymous namespace)::Writer::writeSections()::$_0>(__gnu_cxx::__normal_iterator<lld::wasm::OutputSection**, std::vector<lld::wasm::OutputSection*, std::allocator<lld::wasm::OutputSection*> > >, __gnu_cxx::__normal_iterator<lld::wasm::OutputSection**, std::vector<lld::wasm::OutputSection*, std::allocator<lld::wasm::OutputSection*> > >, (anonymous namespace)::Writer::writeSections()::$_0)::'lambda'()>::_M_invoke(std::_Any_data const&) (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/wasm-ld+0x6bac7d)
#12 0x00007fb376417625 std::_Function_handler<void (), llvm::parallel::detail::TaskGroup::spawn(std::function<void ()>)::$_0>::_M_invoke(std::_Any_data const&) (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/../lib/libLLVM-9svn.so+0x65c625)
#13 0x00007fb376417207 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work() (/home/akien/Projects/godot/emscripten/emsdk/upstream/bin/../lib/libLLVM-9svn.so+0x65c207)
#14 0x00007fb375cf23d0 (/lib64/libstdc++.so.6+0xbd3d0)
#15 0x00007fb37928a04c start_thread (/lib64/libpthread.so.0+0x904c)
#16 0x00007fb375a13bcf clone (/lib64/libc.so.6+0x104bcf)
```

**Comment by supernow** [comment]
I got the same error.
How can I fix it?

**Comment by kripken** [comment]
@supernow this bug is still open, and there isn't a known workaround. For now, I'd suggest not using upstream if you hit this bug. But we hope to fix it soon!

**Comment by sbc100** [comment]
Looks like this is related to debug info.  Adding `-Wl,--strip-debug` fixes the issue.  I'm investigating a real fix now.

**Comment by sbc100** [comment]
Fix should be here: https://reviews.llvm.org/D66435

**Comment by sbc100** [comment]
Should be fixed now.

**Comment by supernow** [comment]
The latest version is 1.38.42-upstream, however that can not build well without -Wl,--strip-debug flags. 
Should I do something else?

**Comment by sbc100** [comment]
@supernow can you post the output of your build failure?  and the output of `emcc -v`?

**Comment by supernow** [comment]
@sbc100 
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.42
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project edfaee08115376467d1c95573de991aebfdaeb42)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

`without -Wl,--strip-debug flags`

wasm-ld: /b/s/w/ir/cache/builder/emscripten-releases/llvm-project/llvm/include/llvm/ADT/Optional.h:177: const T &llvm::optional_detail::OptionalStorage<unsigned int, true>::getValue() const & [T = unsigned int]: Assertion `hasVal' failed.
 #0 0x00007f876fa309f4 PrintStackTraceSignalHandler(void*) (/root/emsdk/upstream/bin/../lib/libLLVM-10svn.so+0x6d79f4)
 #1 0x00007f876fa2e73e llvm::sys::RunSignalHandlers() (/root/emsdk/upstream/bin/../lib/libLLVM-10svn.so+0x6d573e)
 #2 0x00007f876fa30ca8 SignalHandler(int) (/root/emsdk/upstream/bin/../lib/libLLVM-10svn.so+0x6d7ca8)
 #3 0x00007f87729005d0 __restore_rt (/lib64/libpthread.so.0+0xf5d0)
 #4 0x00007f876e7292c7 raise (/lib64/libc.so.6+0x362c7)
 #5 0x00007f876e72a9b8 abort (/lib64/libc.so.6+0x379b8)
 #6 0x00007f876e7220e6 __assert_fail_base (/lib64/libc.so.6+0x2f0e6)
 #7 0x00007f876e722192 (/lib64/libc.so.6+0x2f192)
 #8 0x00000000006ac962 (/root/emsdk/upstream/bin/wasm-ld+0x6ac962)
 #9 0x0000000000695287 lld::wasm::InputChunk::writeTo(unsigned char*) const (/root/emsdk/upstream/bin/wasm-ld+0x695287)
#10 0x00000000006c461d lld::wasm::CustomSection::writeTo(unsigned char*) (/root/emsdk/upstream/bin/wasm-ld+0x6c461d)
#11 0x00000000006c02ed std::_Function_handler<void (), void llvm::parallel::detail::parallel_for_each<__gnu_cxx::__normal_iterator<lld::wasm::OutputSection**, std::vector<lld::wasm::OutputSection*, std::allocator<lld::wasm::OutputSection*> > >, (anonymous namespace)::Writer::writeSections()::$_0>(__gnu_cxx::__normal_iterator<lld::wasm::OutputSection**, std::vector<lld::wasm::OutputSection*, std::allocator<lld::wasm::OutputSection*> > >, __gnu_cxx::__normal_iterator<lld::wasm::OutputSection**, std::vector<lld::wasm::OutputSection*, std::allocator<lld::wasm::OutputSection*> > >, (anonymous namespace)::Writer::writeSections()::$_0)::'lambda'()>::_M_invoke(std::_Any_data const&) (/root/emsdk/upstream/bin/wasm-ld+0x6c02ed)
#12 0x00007f876f9c71a5 std::_Function_handler<void (), llvm::parallel::detail::TaskGroup::spawn(std::function<void ()>)::$_0>::_M_invoke(std::_Any_data const&) (/root/emsdk/upstream/bin/../lib/libLLVM-10svn.so+0x66e1a5)
#13 0x00007f876f9c6d87 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work() (/root/emsdk/upstream/bin/../lib/libLLVM-10svn.so+0x66dd87)
#14 0x00007f876f9c6c17 std::thread::_Impl<std::_Bind_simple<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(unsigned int)::'lambda'() ()> >::_M_run() (/root/emsdk/upstream/bin/../lib/libLLVM-10svn.so+0x66dc17)
#15 0x00007f876f090ad3 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /root/gcc-6.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/shared_ptr_base.h:661:0
#16 0x00007f876f090ad3 std::__shared_ptr<std::thread::_Impl_base, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /root/gcc-6.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/shared_ptr_base.h:928:0
#17 0x00007f876f090ad3 std::shared_ptr<std::thread::_Impl_base>::~shared_ptr() /root/gcc-6.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/shared_ptr.h:93:0
#18 0x00007f876f090ad3 execute_native_thread_routine_compat /root/gcc-6.1.0/build/x86_64-pc-linux-gnu/libstdc++-v3/src/c++11/../../../../../libstdc++-v3/src/c++11/thread.cc:102:0
#19 0x00007f87728f8dd5 start_thread (/lib64/libpthread.so.0+0x7dd5)
#20 0x00007f876e7f102d clone (/lib64/libc.so.6+0xfe02d)


**whether 1.38.42-upstream version fix the bug?**

**Comment by sbc100** [comment]
The version of llvm used in 1.38.42-upstream (edfaee08115376467d1c95573de991aebfdaeb42) looks like it doesn't include my fix from https://reviews.llvm.org/D66435 which landed at cf2b8722d4e3bc4f0c106a5724778d56074e1ec7.

The respective llvm revisions are:
edfaee08115376467d1c95573de991aebfdaeb42 -> 369268
cf2b8722d4e3bc4f0c106a5724778d56074e1ec7 -> 369423

**Comment by dschuff** [comment]
If 1.38.42 doesn't have the revision you need, you could try manually replacing your clang with [this one](https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/aab4183c0e90e8f333b0f8f51e6ab17d5d2ae75c/wasm-binaries.tbz2) or wait for the next release.

**Comment by supernow** [comment]
Thanks a lot
