### ISSUE TITLE
Remove unhandledRejection event listener

### ISSUE THREAD

**Issue by roccomuso** [emscripten-core/emscripten#9028]
Is there a way to remove:

```
  process["on"]("unhandledRejection", (function(reason, p) {
    process["exit"](1)
  }));
```
from the js bundle?

I tried `NODEJS_CATCH_EXIT=0` flag. But it does only remove `process.on('uncaughtException')`.

**Comment by sbc100** [comment]
I don't think there is a way to remove it right now.. isn't this a dup of https://github.com/emscripten-core/emscripten/issues/7855?

**Comment by roccomuso** [comment]
Can't this be added? I don't see the point of keeping it
