### ISSUE TITLE
[Bug] [Fix and code suggested] EM_ASM does not allow modifying operations as arguments

### ISSUE THREAD

**Issue by yeputons** [emscripten-core/emscripten#9030]
# The issue
Consider the following snippet compiled with `em++ a.cpp` (`
emcc (Emscripten gcc/clang-like replacement) 1.38.38 (commit 49652605051d9faca2dcb781918a028bdfbc2703)`):

```c++
#include <emscripten/emscripten.h>

int main() {
    int x = 0, y = 0;
    EM_ASM({ console.log($0, $1); }, x++, y++);
}
```

**Expected output**: `0 0`
**Real output**: `1 1`

## The reason
The following warning is produced:

```
a.cpp:5:39: warning: multiple unsequenced modifications to 'x' [-Wunsequenced]
    EM_ASM({ console.log($0, $1); }, x++, y++);
                                      ^~
c:\emsdk\upstream\emscripten\system\include\emscripten/em_asm.h:176:83: note: expanded from macro 'EM_ASM'
#define EM_ASM(code, ...) ((void)emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__)))
                                                                                  ^~~~~~~~~~~
c:\emsdk\upstream\emscripten\system\include\emscripten/em_asm.h:122:42: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
                                         ^                      ~~~~~~~~~~~
a.cpp:5:44: warning: multiple unsequenced modifications to 'y' [-Wunsequenced]
    EM_ASM({ console.log($0, $1); }, x++, y++);
                                           ^~
c:\emsdk\upstream\emscripten\system\include\emscripten/em_asm.h:176:83: note: expanded from macro 'EM_ASM'
#define EM_ASM(code, ...) ((void)emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__)))
                                                                                  ^~~~~~~~~~~
c:\emsdk\upstream\emscripten\system\include\emscripten/em_asm.h:122:42: note: expanded from macro '_EM_ASM_PREP_ARGS'
    , __em_asm_sig_builder::__em_asm_sig(__VA_ARGS__).buffer, ##__VA_ARGS__
                                         ^                      ~~~~~~~~~~~
2 warnings generated.
```

Specifically, when `EM_ASM` is expanded in C++ mode with non-asmjs backend, it's expanded to:

```c++
((void)emscripten_asm_const_int("{ console.log($0, $1); }" , __em_asm_sig_builder::__em_asm_sig(x++, y++).buffer,x++, y++));
```

Here we clearly see the unsequenced modification which is undefined behaviour in C++: each argument is evaluted twice: once to pass to `__em_asm_sig` to examine the type of the argument and build corresponding type signature, and once to `emscripten_asm_const_int` to pass the actual value.

## Severity

On the one hand, it's a warning enabled by default, so users may investigate further and avoid undesired consequences. Fortunately, it looks like more complex types (like vectors) are not supported by `EM_ASM` at all, so the warning _probably_ catches all cases.

On the other hand, this bug occured in [`asm-dom`](https://github.com/mbasso/asm-dom/blob/ea3dba7b0e031051eb2b8aa2eba53d99912305ab/src/cpp/Patch/patch.cpp#L91-L93) at the very least, even though it's compiled with `-Wall -Werror`. So it looks like this warning evaded the developer in that specific case.

# Suggestion: quick fix
Document that `EM_ASM`'s arguments are not to have any side effects at all.

# Suggestion: full fix

Values passed to [`__em_asm_sig`](https://github.com/emscripten-core/emscripten/blob/941bbc6b9b35d3124f17d2503d7a32cc81032dac/system/include/emscripten/em_asm.h#L112-L119) are not really needed: we only want to know their types. We can do that by passing arguments to `decltype`, which prevents evaluation of these arguments, thus removing unsequenced modifications. As we have to pass several arguments, we can wrap them into `std::make_tuple` (not exactly sure how that will play with constness and stuff, but probably in a reasonable way because only trivial types are passed, essentially).

Some rewriting of `__em_asm_sig_builder` should happen as well to work strictly on type-level so it can be reused in the future for values which cannot be instantiated simply (note that `std::declval()`'s result cannot be used in any evaluated expression even if it's discarded).

Here is my attempt which monkey-patches emscripten, you can compile it with `em++ a.cpp -std=c+=11` and see the expected `0 0`:

```c++
#include <emscripten.h>
#include <tuple> // std::tuple, std::make_tuple
#include <type_traits> // std:integral_constant

// Function overload requires passing a value of a type, but we
// may have no easy way to instantiate a value of a generic type.
template<typename> struct __em_asm_sig {};
template<> struct __em_asm_sig<float> : std::integral_constant<char, 'd'> {};
template<> struct __em_asm_sig<double> : std::integral_constant<char, 'd'> {};
template<> struct __em_asm_sig<int> : std::integral_constant<char, 'i'> {};
template<> struct __em_asm_sig<unsigned> : std::integral_constant<char, 'i'> {};
template<> struct __em_asm_sig<long> : std::integral_constant<char, 'i'> {};
template<> struct __em_asm_sig<unsigned long> : std::integral_constant<char, 'i'> {};
template<typename T> struct __em_asm_sig<T*> : std::integral_constant<char, 'i'> {};

template<typename>
struct __em_asm_sig_builder2 {};

template<typename... Args>
struct __em_asm_sig_builder2<std::tuple<Args...>> {
  // No need for internal buffer or copying, just initialize directly.
  char buffer[sizeof...(Args)+1] = { __em_asm_sig<Args>::value..., 0 };
};

// Redefine old macro to use the new builder instead
#undef _EM_ASM_PREP_ARGS
#define _EM_ASM_PREP_ARGS(...) \
    , __em_asm_sig_builder2<decltype(std::make_tuple(__VA_ARGS__))>().buffer, ##__VA_ARGS__

int main() {
    int x = 0, y = 0;
    EM_ASM({ console.log($0, $1); }, x++, y++);
}
```

I hope that most of the example above can be a drop-in replacement of [`__em_asm_sig_builder`](https://github.com/emscripten-core/emscripten/blob/941bbc6b9b35d3124f17d2503d7a32cc81032dac/system/include/emscripten/em_asm.h#L81-L123).

Here, `EM_ASM` unwraps to

```
((void)emscripten_asm_const_int("{ console.log($0, $1); }" , __em_asm_sig_builder2<decltype(std::make_tuple(x++, y++))>().buffer,x++, y++));
```

and no unordered modifications occur, as the first `x++` happens inside `decltype` which prevents the subexpression from evaluating.

**Comment by sbc100** [comment]
Seems like we should document this, and let the warning scare people.

I would no be against the proposed solution, but it would need to be C++11 only and EM_ASM needs to also work with plain C.

In general my understanding is that we are trying to move people towards EM_JS and away from EM_ASM so I don't think we want to be investing too much time making it better.  @jgravelle-google, thoughts?

**Comment by yeputons** [comment]
To the best of my understanding regarding the proposed solution:

* It is already C++11 (at least in compiles with `-std=c++11` successfully).
* This problem is not happening in current C implementation: `EM_ASM` expands to [`_Generic`](https://en.cppreference.com/w/c/language/generic) there which does not evaluate the controlling expression and does not yield undefined behaviour. Consequently, it also prints `0 0` as expected. So, nothing to fix there.
* The third implementation of `_EM_ASM_PREP_ARGS` (the one for asmjs) does not do any type annotations at all, so it should be safe as well.

Would you consider a PR which fixes the C++ version and adds corresponding tests for C and C++?

**Comment by sbc100** [comment]
For sure, patches welcome!
