### ISSUE TITLE
Link broken on getting started page

### ISSUE THREAD

**Issue by limitlessloop** [emscripten-core/emscripten#9035]
Hi,

I noticed the link to "Allow installation of unsigned packages" on the getting started page is broken/missing.

https://emscripten.org/docs/getting_started/downloads.html

Regards,
Gavin

**Comment by kripken** [comment]
Thanks @limitlessloop!

Can we just remove that line, or should we find a better link? I don't know enough about MacOS...

**Comment by limitlessloop** [comment]
I'm not sure exactly what the link is supposed to be pointing to but maybe something on this page would be correct and unlikely to change/disappear https://support.apple.com/en-gb/HT202491

**Comment by kripken** [comment]
Thanks @limitlessloop, I opened #9118 with that now.
