### ISSUE TITLE
other.test_minimal_dynamic fails on wasm backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9038]
Noticed this will going through all the currently disabled tests. This disabled test seems to fail because too much DCEing is being done - perhaps we are not passing the right flags / lists of exports to wasm-ld in MAIN_MODULE 2 or something like that.

**Comment by sbc100** [comment]
Looks like this is due to the wasm backend optimizing the `printf` call to `iprintf`.  Working on a fix now.

**Comment by kripken** [comment]
@sbc100 is this still in progress? (I see a PR landed that refers to this, but the test still fails.)

**Comment by sbc100** [comment]
Taking another look now.
