### ISSUE TITLE
Invalid pointer/value from variadic function argument with aggregate variable type

### ISSUE THREAD

**Issue by msabwat** [emscripten-core/emscripten#9042]
Hi, 

Declaring an aggregate variable, and passing it to a variadic function is not possible. The pointer we get is invalid (thus, the value too). I isolated the bug, but I discovered it on a large codebase where I was getting segfaults with strdup and printf calls that use variables returned by va_arg(). On a side note I noticed these addresses were abnormally big compared to the valid pointers I could see.

Here is an example of the behavior I observed using this command:
```
emcc main.c -o test.js
```
here is the source code for main.c:
```
#include <stdio.h>
#include <stdarg.h>

typedef struct { int x; int y; } coords;

void fun(int a, ...)
{
  (void)a;
  va_list ap;
  va_start(ap, a);
  
  coords var = va_arg(ap, coords);
  printf("va_arg struct: %d and %d\n", var.x, var.y);
  va_end(ap);
}

main()
{
  coords val = { .x=42,.y=21, };
  
  printf("value passed struct: %d and %d\n", val.x, val.y);
  fun (0, val);

  return 0;
}
```
Result:
```
$ node test.js 
value passed struct: 42 and 21
va_arg struct: 5243832 and 0
```
I was wondering if there will be a fix for this, and if there was something I could do to workaround (apart from dynamically allocating coords *val) and/or help resolve the issue?  

Thanks, 
Regards

**Update**:
Forgot to mention I am on latest-upstream emsdk with a51302ba20697f5251a8185cfdc72e72b14351e4 being the latest commit.
```$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.38
clang version 9.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 922759a63d7d8edbc47578b4718a38765093d24e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/b1ue/b1ue/workdir_vlc/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.1.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.1.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by kripken** [comment]
Thanks for filing! This does look like a bug in the upstream backend, as it works ok on fastcomp.

I'm not sure if the issue is in the backend, or in frontend lowering, though. cc @tlively @aheejin @jgravelle-google who might know. Adding to list of upstream blockers.

**Comment by tlively** [comment]
Doesn’t ring a bell, but I’ll take a look if no one else gets to it first.

**Comment by quantum5** [comment]
`WebAssemblyTargetLowering::LowerCall` passes the struct by pointer inside the varargs struct:

```cpp
  if (IsVarArg) {
    // Outgoing non-fixed arguments are placed in a buffer. First
    // compute their offsets and the total amount of buffer space needed.
    for (unsigned I = NumFixedArgs; I < Outs.size(); ++I) {
      const ISD::OutputArg &Out = Outs[I];
      SDValue &Arg = OutVals[I];
      EVT VT = Arg.getValueType();
      assert(VT != MVT::iPTR && "Legalized args should be concrete");
      Type *Ty = VT.getTypeForEVT(*DAG.getContext());
      unsigned Align = std::max(Out.Flags.getOrigAlign(),
                                Layout.getABITypeAlignment(Ty));
      unsigned Offset = CCInfo.AllocateStack(Layout.getTypeAllocSize(Ty),
                                             Align);
      CCInfo.addLoc(CCValAssign::getMem(ArgLocs.size(), VT.getSimpleVT(),
                                        Offset, VT.getSimpleVT(),
                                        CCValAssign::Full));
    }
  }
```

In this code, the `assert` makes it clear that by this point, arguments are all "legalized" into pointers. We can see evidence of this in the generated code:

```wast
  (i64.store offset=8
   (local.get $0)
   (i64.load align=4
    (i32.const 1052)
   )
  )
  (i32.store
   (local.get $0)
   (i32.add
    (local.get $0)
    (i32.const 8)
   )
  )
  (call $fun
   (local.get $0)
  )
```

`(i32.add (local.get $0) (i32.const 8))` is the location of the actual `coords` structure, and `(local.get $0)` is the varargs struct which contains a pointer to the `coords` structure.

On the other hand, the function expects to receive the structure by value, as seen in this snippet of `fun`:

```wast
  (i64.store
   (local.get $1)
   (i64.load align=4
    (local.get $0)
   )
  )
  (call $iprintf
   (i32.const 1024)
   (local.get $1)
  )
```

`(local.get $1)` is the location of the varargs struct to `printf`, and `(local.get $0)` is the varargs struct for `fun`. It is clear that the structure was expected to be read directly with a `i64.load`, instead of going through a pointer.

Due to the lack of a formal ABI specification, it is impossible to know if structures are expected to be passed by value in the varargs structure, or by pointer.

**Comment by tlively** [comment]
@dschuff for the ABI question. Until we have documentation on this, I'd say it makes sense to use whichever approach would be simpler to code. I would expect that to be the pass-by-pointer approach, since I believe that more closely matches what happens to structs in the non-varargs case.

**Comment by quantum5** [comment]
The bug appears to be in clang. A proposed fix is https://reviews.llvm.org/D66168.

**Comment by dschuff** [comment]
That fix looks like the right one. We should probably update the ABI doc in tool-conventions too; I think I just didn't get around to the calling conventions that last time I was working on it.
