### ISSUE TITLE
Add metadata field to indicate wasm backend

### ISSUE THREAD

**Issue by quantum5** [emscripten-core/emscripten#9055]
In `add_emscripten_metadata`, the metadata does not distinguish between fastcomp and wasm backend, even though the ABI is different.

This is suggested in https://github.com/emscripten-core/emscripten/pull/9026#issuecomment-513406079.

**Comment by mykmartin** [comment]
Hi - for future updates to the metadata fields, is it possible to require that new values are always appended? As a consumer of the metadata fields, it is much easier to maintain compatibility with different metadata versions if new values aren't inserted into the existing list.

**Comment by mykmartin** [comment]
Thanks @kripken. At this time it's fine either way - I don't need to maintain compatibility between released versions yet, so for the time being I can easily update our code to match the metadata.
