### ISSUE TITLE
`run_process` from `tools/shared.py` ignores `universal_newlines`

### ISSUE THREAD

**Issue by yeputons** [emscripten-core/emscripten#9069]
See [here](https://github.com/emscripten-core/emscripten/blob/466b40bafd4134bbf58bf273b8aadca851ea6621/tools/shared.py#L164-L165):

```javascript
def run_process(cmd, check=True, input=None, universal_newlines=True, *args, **kw):
  kw.setdefault('universal_newlines', True)
```

This snippet catches value of the `universal_newlines` parameter into a variable which is later unused. The second line suggests that the idea was to capture `universal_newlines` in `kw` and provide default by `setdefault`. However, the combination fixes `universal_newlines=True`.

That makes fix of #9057 slightly more cumbersome.

**Comment by kripken** [comment]
Interesting, thanks @yeputons!

That code is indeed odd. I am a little worried about changing it without understanding the background.@sbc100 , @jgravelle-google ?
