### ISSUE TITLE
upstream, multithreading, Firefox: wasm validation error

### ISSUE THREAD

**Issue by truedim** [emscripten-core/emscripten#9077]
Command line:
`em++ test.cpp -s USE_PTHREADS=1 -o test.html`

test.cpp:
```cpp
 int main(int argc, char **argv){}
```

Latest Firefox with shared memory enabled:
`about:config?filter=shared_memory`

Error: 
`failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 2343: expected code section`

It only happens with upstream backend.

**Comment by kripken** [comment]
I think upstream recently updated to the new bulk memory spec, which firefox supports in beta, but not stable. @tlively can verify.

**Comment by tlively** [comment]
That is correct. We figured that since threads is already behind a flag in FF, it would be ok to require developers experimenting with it to also use a beta.

**Comment by truedim** [comment]
Thanks for the clarification, it works with v69 beta, so I can close the issue.
