### ISSUE TITLE
emsdk support for JNI code compilation.

### ISSUE THREAD

**Issue by Srinirajini** [emscripten-core/emscripten#9078]
Dear emscripten Team,
   I am fairly new with emscripten, so I am not very clear whether my requirement to build JNI code with emsdk has already supported or not but as far as I googled for the solution I haven't get any solution. My requirement is to port my existing C/C++ USB tool to ChromeOS using Chrome USB APIs which are exposed in Java, so I have a layer abstracted in my existing stack where I thought to make a JNI calls to ChromeOS USB API. but end up in below error while building, does it means that emsdk does not have JNI support?

test# emcc -O2 -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=10 -s WASM=1 -I/usr/local/java/jdk-10.0.2/include/ -I/usr/local/java/jdk-10.0.2/include/linux/ test.c ../debug.c ../ftd2xx-private.c ../config.c ../baud.c ../bulk_in.c ../usb_control.c ../device-list.c ../idtable.c ../ftd2xx.c ../Event.c ../chrome_portingStubs.c  -o test.js
../ftd2xx.c:777:51: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
        snprintf(ftdi_dev->Info.SerialNumber, 17, info.SerialNumber);
                                                  ^~~~~~~~~~~~~~~~~
../ftd2xx.c:777:51: note: treat the string as an argument to avoid this
        snprintf(ftdi_dev->Info.SerialNumber, 17, info.SerialNumber);
                                                  ^
                                                  "%s", 
../ftd2xx.c:778:50: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
        snprintf(ftdi_dev->Info.Description, 65, info.Description);
                                                 ^~~~~~~~~~~~~~~~
../ftd2xx.c:778:50: note: treat the string as an argument to avoid this
        snprintf(ftdi_dev->Info.Description, 65, info.Description);
                                                 ^
                                                 "%s", 
2 warnings generated.
error: undefined symbol: JNI_CreateJavaVM
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
Error: Aborting compilation due to previous errors
shared:ERROR: '/root/D2XX/emsdk/node/8.9.1_64bit/bin/node /root/D2XX/emsdk/fastcomp/emscripten/src/compiler.js /tmp/tmprdLH2f.txt /root/D2XX/emsdk/fastcomp/emscripten/src/library_pthread.js' failed (1)

Regards,
Srini.

**Comment by kripken** [comment]
Correct, emscripten emits JS+wasm that is intended to run on the web or on node.js etc., and those platforms don't have JNI support, so emscripten doesn't.

However, if you are running in a custom environment that does have JNI support somehow, then you can implement `JNI_CreateJavaVM` and the other methods. You can call out from emscripten-compiled code to run arbitrary JS, so if the JNI is exposed to you there you can call it.

**Comment by Srinirajini** [comment]
OKay, Thanks for clarification.
