### ISSUE TITLE
Can I use MinGW to compile Clang/LLVM from source?

### ISSUE THREAD

**Issue by Katmai6** [emscripten-core/emscripten#9093]
I am trying to install Emscipten for 32bit Windows.I need a version of Emscripten which supports Fetch Api.

It seerms like I have to compile Emscripten/LLVM/Clang from source.Can I use MinGW to compile Clang/LLVM from source instead of installing Visual Studio?If yes, which version of MinGW should I install in order to do it?

I installed MinGW gcc version 8.2.0 from mingw.org, while trying to build clang/llvm(using emsdk install sdk-tag-1.38.31 command) it gives many warning,notes and also errors ,then it says an exception is thrown and installation failed.

**Comment by kripken** [comment]
This is easiest with the llvm wasm backend. Basically you just need to build LLVM normally, just make sure it has clang and wasm-ld included.

The official LLVM docs mention mingw in a few places, hopefully they answer any questions? https://llvm.org/docs/CMake.html if not then asking there might be best.

**Comment by Katmai6** [comment]
Thanks for your answer.
