### ISSUE TITLE
Various portability issues in shared.py preventing Termux compatibility

### ISSUE THREAD

**Issue by easyaspi314** [emscripten-core/emscripten#9098]
I was trying to configure and build emscripten from source on Termux and there are some major portability issues in the shared.py script.

First of all, it only chooses `/tmp` on Linux and macOS. There are numerous environment variables, such as `TMPDIR` which properly points to Termux's temp folder (`/tmp` is *not accessible* on Android even though it exists). Sometimes we also see `TEMP_DIR`.

Second of all, it uses `multiprocessing.Pool`. This throws an `ImportError` when called on Android. We should fall back to the `FakeMultiprocessingPool` class in this case.

**Comment by bipgen** [comment]
Hi I would like to work on this problem. I am a noob. So I looked at the source code and I indeed saw that it chooses '/tmp' directly as you have mentioned. I believe I can fix it by checking some env variables and choosing the appropriate directory.

However for the second issue I am not able to understand the meaning of it. I see that it calls FakeMultiProcessingPool when there is only 1 core. Could you shed some more light on this issue?

Can someone please assign me this issue. Thanks.

**Comment by kripken** [comment]
Thanks for working on this @bipgen!

Yes, on we should use the Fake pool for a single core. Not sure what the issue is either. Does even importing the module fail for you, @easyaspi314 ?

**Comment by easyaspi314** [comment]
Importing the module doesn't seem to cause an error, but using the Pool functions throws an ImportError.
```python
multiprocessing.Pool(processes=cores, initializer=g_multiprocessing_initializer, initargs=child_env)
```
The thing is that even though Pool is useless, `multiprocessing.cpu_count()` still returns the number of CPUs.

**Comment by juj** [comment]
The Pool issue sounds like a Python issue on termux, perhaps useful to raise it against Python. In the meanwhile, if there is a good way to check support (without spawning a costly temp thread to do it), then that could be used to decide whether to force FakeMultiprocessingPool to take place instead.

Changing to use an environment variable for the temp directory sounds good, if there are multiple, may be best to search through them all.

**Comment by bipgen** [comment]
@easyaspi314 I see the following code in Building class:
  ```
@staticmethod
  def get_num_cores():
    return int(os.environ.get('EMCC_CORES', multiprocessing.cpu_count()))

```
Are you saying that we checking for cpu_count() is causing a problem in termux. Are you saying this function isn't supported. So we need to somewhat figure that out (maybe try except blocks) and directly use Fake Pool ??

**Comment by quantum5** [comment]
Have you tried putting `EMCC_CORES=1` in `.bashrc` or something? I think that should fix the pool issue.

**Comment by quantum5** [comment]
As for `/tmp`, the temporary file directory is configurable in `.emscripten`, although the custom `find_temp_directory` function in `shared.py` should probably be replaced with [`tempfile.gettempdir`](https://docs.python.org/2/library/tempfile.html#tempfile.gettempdir).

**Comment by quantum5** [comment]
I believe the `/tmp` problem has been fixed. Putting `EMCC_CORES=1` should fix the remaining `multiprocessing` issue.

**Comment by bipgen** [comment]
@kripken sorry could not work on this. Someone resolved this issue in a better manner.
