### ISSUE TITLE
Embind without RTTI broken in 1.38.40

### ISSUE THREAD

**Issue by cwoffenden** [emscripten-core/emscripten#9122]
Tested with both _latest_ and _latest-upstream_ (and _incoming_).  A simple C++ file (`test.cpp`) and corresponding HTML (`test.html`):
```C
#include <emscripten/bind.h>
int test() {
	return 42;
}
EMSCRIPTEN_BINDINGS(test) {
    emscripten::function("test", test);
}
```
```HTML
<html>
<script>
var Module = {
    onRuntimeInitialized: function () {
        console.log("inited");
        console.log(Module.test());
    }
};
</script>
<script src="test.js"></script>
</html>
```
Compile using `emcc --bind -o test.js test.cpp` and load the resulting page. Observe in the console the return value from `Module.test()`.

Now compile without RTTI using `emcc --bind -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 -o test.js test.cpp`. Observe that we see `onRuntimeInitialized` entered but no return value from `Module.test()` (in Firefox; Chrome shows the `UnboundTypeError` directly, as does `-s WASM=0`). If we try to call the function manually we get:
```
UnboundTypeError: Cannot call test due to unbound types: emsc test.js:2564:13
    throwUnboundTypeError http://localhost/test.js:2564
    __embind_register_function http://localhost/test.js:2572
    <anonymous> debugger eval code:1
```
Test files attached: [test.zip](https://github.com/emscripten-core/emscripten/files/3446707/test.zip). This was working with 1.38.39.

**Comment by kripken** [comment]
Thanks @cwoffenden!

Bisecting this, the regression happened in #8817. Will ping there.
