### ISSUE TITLE
Embind unreachable code warning in 1.38.40 upstream/wasm2js

### ISSUE THREAD

**Issue by cwoffenden** [emscripten-core/emscripten#9129]
Using the same test as in #9122 (which also affects _upstream_) and compiling with `emcc --bind -s WASM=0 -o test.js test.cpp` I'm seeing `unreachable code after return statement` in Firefox on Windows (but not in Chrome).

Compiling with `emcc --bind -fno-rtti -DEMSCRIPTEN_HAS_UNBOUND_TYPE_NAMES=0 -s WASM=0 -o test.js test.cpp` I see the same bug as #9122 with the addition of the `unreachable code` warning.

Looking at the reported line it does indeed have unreachable code:
```
function convertJsFunctionToWasm(func, sig) {
  return func;

  // The module is static, with the exception of the type section, which is
  // generated based on the signature passed in.
  var typeSection =
  etc., etc.
```

**Comment by jgravelle-google** [comment]
(removing the embind tag; it's not really related to embind, just happens to be built with `--bind`)

A fix is in #9133 

I'd expect `--closure 1` to similarly strip the dead code, which is also why we don't strip the comments from the library code in general either.
