### ISSUE TITLE
Asyncify is not working with wasm

### ISSUE THREAD

**Issue by Srinirajini** [emscripten-core/emscripten#9134]
Hi,
  I am reading a tutorial about Asyncify at the link "https://emscripten.org/docs/porting/asyncify.html" and trying out the sample program "Returning values" I have not changed anything and just followed the instruction in the tutorial for building too ("emcc example.c -s ASYNCIFY=1 -s 'ASYNCIFY_IMPORTS=["get_digest_size"]' -o a.html -O2"). 
My emcc version is as below.
"_emcc (Emscripten gcc/clang-like replacement) 1.38.39 (commit e2110d88167bc0bd74affe35054d799f90dfa759)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE._"

when looking at the browser while running the server, I am getting below error.
"
_**_a.html:1 exception thrown: ReferenceError: Asyncify is not defined,ReferenceError: Asyncify is not defined
    at _get_digest_size (http://localhost:8080/a.js:1:16111)
    at wasm-function[17]:17
    at Object.Module._main (http://localhost:8080/a.js:1:21028)
    at Object.callMain (http://localhost:8080/a.js:1:23102)
    at doRun (http://localhost:8080/a.js:1:23772)
    at http://localhost:8080/a.js:1:23919

a.js:1 Uncaught ReferenceError: Asyncify is not defined
    at _get_digest_size (a.js:1)
    at wasm-function[17]:17
    at Object.Module._main (a.js:1)
    at Object.callMain (a.js:1)
    at doRun (a.js:1)
    at a.js:1_**_
"
Please let me understand whether the document is outdated, or I am missing something.
Note I am running the cod in chrome browser.

Regards,
Srini.

**Comment by kripken** [comment]
Make sure you are using the wasm backend, as mentioned in the note there - using fastcomp will not work.

emcc -v should show clang's version is 9 or 10 for the wasm backend (fastcomp would be 6.0.1).

**Comment by Srinirajini** [comment]
Wow, Thanks for quick clarification.
my emcc -v shows clang version 6.0.1.
Could you please give me any reference Howe to upgrade to WASM CLANG 9 or 10.
Is there any separate branch maintained for emdk.
Please clarify.

Thanks.

**Comment by kripken** [comment]
You just need to get `latest-upstream` instead of `latest`. See https://v8.dev/blog/emscripten-llvm-wasm#testing

**Comment by Srinirajini** [comment]
Okay, Just got upgraded to WASM backend and now my emcc -v output is 
"
**_emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.39
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 10dad95a75592717d2f7c0ebc181fb8a970a8df7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/D2XX/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
shared:WARNING: LLVM version appears incorrect (seeing "10.0", expected "9.0")
shared:INFO: (Emscripten: Running sanity checks)_**
"

But with this version I could not able to build any of the previously built files. I am ending up with an error .
"
_**shared:WARNING: LLVM version appears incorrect (seeing "10.0", expected "9.0")
cache:INFO:  - ok
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/root/.emscripten_cache/wasm-obj/generated_struct_info.json" for subsequent builds)
shared:WARNING: LLVM version appears incorrect (seeing "10.0", expected "9.0")
shared:ERROR: unexpected metadata key received from wasm-emscripten-finalize: mainReadsParams**_
"

Please help me to resolve this problem.

Thanks.

**Comment by Srinirajini** [comment]
Got a hint here, I tried installing the emsdk in a user instead of root and the problem disappears.
Is there a fix available to have WASM Backend work in root.

Thanks.

**Comment by kripken** [comment]
The latest version should be 1.38.40, may need to [update the emsdk](https://emscripten.org/docs/getting_started/downloads.html#updating-the-sdk). That might explain that error.

**Comment by Srinirajini** [comment]
Uninstalling the emsdk completely and installed freshly has solved the problem.

Thanks.

**Comment by Ujjwal21** [comment]
Hi @kripken, I am getting similar issue on clang 14.0

**Comment by kripken** [comment]
@Ujjwal21 Make sure you have the latest emsdk installed and updated. It uses clang 16.0.
