### ISSUE TITLE
Weird paths in building libcxxabi

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9144]
Building it with EMCC_DEBUG=1 in the env, I see stuff like this:
```
/home/azakai/Dev/emscripten/emcc.py /home/azakai/Dev/emscripten/system/lib/libcxxabi/src/cxa_exception_storage.cpp -o /tmp/emscripten_temp/cxa_exception_storage.cpp.o -Werror -std=c++11 -Oz -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -I/home/azakai/Dev/emscripten/s/y/s/t/e/m -I/home/azakai/Dev/emscripten/l/i/b -I/home/azakai/Dev/emscripten/l/i/b/c/x/x/a/b/i -I/home/azakai/Dev/emscripten/i/n/c/l/u/d/e -DNDEBUG -D_LIBCXXABI_HAS_NO_THREADS --emscripten-cxx
```
Note the `-I/home/azakai/Dev/emscripten/i/n/c/l/u/d/e` etc. - it seems like "include" is added as a string that is split up.

Somehow this causes no bugs, so maybe we can just remove those paths?

cc @quantum5 @sbc100 who recently worked on those files, maybe this rings a bell?

**Comment by quantum5** [comment]
Ah yes, this is because it says `includes = ['system', 'lib', 'libcxxabi', 'include']` in `libcxxabi`. The correct code is `includes = [['system', 'lib', 'libcxxabi', 'include']]`.

The idea is to declare paths as a list of components instead of requiring `os.path.join` every time a path is used.
