### ISSUE TITLE
Exporting asyncified function makes program hang

### ISSUE THREAD

**Issue by rhysd** [emscripten-core/emscripten#9152]
## Environment

- emscripten: latest-upstream
- OS: macOS 10.12
- Browser: Chrome 76

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.40
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 10dad95a75592717d2f7c0ebc181fb8a970a8df7)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
```

## Repro

Save following file as `foo.c`

```c
#include <emscripten.h>
#include <stdio.h>

void my_sleep(int d) {
  emscripten_sleep(d);
}

int main() {
  printf("Start\n");
  my_sleep(3000);
  printf("End\n");
}
```

Compile it with:

```
emcc -O3 -g2 foo.c -s ASYNCIFY -o foo.html -s 'ASYNCIFY_IMPORTS=["emscripten_sleep"]' -s 'EXPORTED_FUNCTIONS=["_my_sleep"]'
```

The command completes successfully.
Finally host `foo.html` and access to it on browser.

## Expected behavior

In DevTools console, 'Start' is shown at first then 'End' is shown after 3000ms

## Actual behavior

No output in DevTools console

**Comment by kripken** [comment]
I think this may be a confusion about `EXPORTED_FUNCTIONS`. That command will *only* export `my_sleep`, that is, it prevents exporting `main`. If I add `,"_main"` to the export list it works as expected for me locally (without exporting `main` it is removed as dead code).

The API is potentially confusing this way, but it is the simplest way to give 100% control to the user. Perhaps we should at least warn if `main` exists but is not exported?

**Comment by rhysd** [comment]
Oh, you're correct. Since I'm usually using emscripten without `main()` function, I wrongly thought that `_main` is automatically exported even if `EXPORTED_FUNCTIONS` does not include it. As you said, it worked fine when I added `_main` to the list. Closing this issue.

> Perhaps we should at least warn if main exists but is not exported?

I feel it would be useful :+1: though it may be intentional.

**Comment by kripken** [comment]
I opened #9159 with a possible warning for this.

**Comment by rhysd** [comment]
Thank you @kripken for taking care :smile:
