### ISSUE TITLE
Asyncify: Nested pause function calls does not work

### ISSUE THREAD

**Issue by rhysd** [emscripten-core/emscripten#9153]
## Environment

- emscripten: latest-upstream
- OS: macOS
- Browser: Chrome 76

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.40
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 10dad95a75592717d2f7c0ebc181fb8a970a8df7)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
```

## Repro

Please save following code as `foo.c`

```c
#include <emscripten.h>
#include <stdio.h>

EM_JS(void, f, (int duration), {
  return Asyncify.handleSleep(function(wake) {
    console.log('f: start:', duration);

    setTimeout(() => {
      console.log('f: end:', duration);
      wake();
    }, duration);

    Module.ccall('do_something_async', null, [], []);
  });
});

EM_JS(void, g, (int duration), {
  return Asyncify.handleSleep(function(wake) {
    console.log('g: start:', duration);

    setTimeout(() => {
      console.log('g: end:', duration);
      wake();
    }, duration);
  });
});

void do_something_async() {
  g(1000);
}

int main() {
  printf("Start\n");
  f(3000);
  printf("End\n");
}
```

And compile it with following command:

```
emcc -O3 -g2 foo.c -s ASYNCIFY -o foo.html \
    -s 'ASYNCIFY_IMPORTS=["f","g"]' \
    -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" \
    -s 'EXPORTED_FUNCTIONS=["_do_something_async","_main"]'
```

Host the directory with web server and browse `foo.html` from browser

## Expected behavior

In DevTools console, expected log output is:

```
Start
foo.js:611 f: start: 3000
foo.js:601 g: start: 1000
foo.js:603 g: end: 1000
foo.js:613 f: end: 3000
foo.html:1237 End
```

it means that both inner call `g` and outer call `f` are rewinded correctly.

## Actual Behavior

In DevTools console, actual log output is:

```
Start
f: start: 3000
g: start: 1000
g: end: 1000
End
f: end: 3000
Uncaught TypeError: Cannot read property 'bottomOfCallStack' of undefined
    at foo.js:1640
    at foo.js:614
```

it seems that inner call `g` is rewinded correctly but outer call `f` seems also rewinded at the timing when `g` is rewinded. So 'End' is output before 'f: end: 3000' ending up with causing an exception.

**Comment by kripken** [comment]
I think this is not currently supported - just one sleep is allowed at a time. Does building with `-s ASSERTIONS` (or with `-O0` where assertions are on by default) show a proper error? If not we should fix that.

**Comment by kripken** [comment]
Also, it would be nice to support multiple nested sleeps too, if it's useful for people. @rhysd I'm curious to hear the use case you have for this?

**Comment by rhysd** [comment]
> Does building with -s ASSERTIONS (or with -O0 where assertions are on by default) show a proper error?

I tried `-O0` instead of `-O3` with latest-upstream (2b568055af67b4fb04c13ef81dc2b3ca3035ac8f) and still got following exception:

```
Uncaught abort(RuntimeError: unreachable) at Error
    at jsStackTrace (http://localhost:1111/foo.js:1170:13)
    at stackTrace (http://localhost:1111/foo.js:1187:12)
    at abort (http://localhost:1111/foo.js:3769:44)
    at runAndAbortIfError (http://localhost:1111/foo.js:3064:9)
    at http://localhost:1111/foo.js:3134:13
    at http://localhost:1111/foo.js:1746:157
```

It seems that it is not an assertion failure, but just a runtime error.

> Also, it would be nice to support multiple nested sleeps too, if it's useful for people. @rhysd I'm curious to hear the use case you have for this?

Sure, let me explain (I'm not a native English speaker so my English would not be good. Please let me know if something is not clear or seems wrong).

My use case is [vim.wasm](https://github.com/rhysd/vim.wasm), which is a project to port Vim editor to the Web.
Vim has event loop internally to handle user's key input and apply the input to the editor's state (update internal text buffer, render to screen, ...). In the event loop, Vim requires blocking wait to wait for user's key input.

For now, Vim sleeps until user input using `SharedArrayBuffer` and `Atomics.wait` (on `KeyboardEvent`, main thread awakes worker thread using `Atomics.notify`). I'm now considering to replace this blocking wait with asynchronous wait using Asyncify.

https://github.com/rhysd/vim.wasm/compare/asyncify?expand=1

Inputs are sent from main thread asynchronously so Vim may accept multiple inputs at the same time. Let's say there are two interactions at the same time:

1. Vim wants to access to clipboard so it requests clipboard contents to main thread
2. User's key input is sent from main thread to worker thread

Let's say while sending 1. request to main thread and awaiting for response from main thread, key input 2. is sent from main thread. Vim accepts the key input 2. before receiving the clipboard response 1. In the case, the clipboard request is paused and handling key input for 2. happens. Handling key input may cause another async operation.

However, I think this problem can be solved by queueing the inputs and process them in order. In above example, I can enqueue 1. and 2. then process them serially. By processing inputs serially, response time of inputs may be slightly worse, but I think it does not have any impact for users in real usage. So nested pausing is actually not mandatory for my use case.

**Comment by rhysd** [comment]
In favor of https://github.com/emscripten-core/emscripten/issues/9153#issuecomment-518631804, I'm closing this issue. I'm sorry for remaining this issue for a long time.
