### ISSUE TITLE
emcc not working with msvc compiler options

### ISSUE THREAD

**Issue by suhaschintala** [emscripten-core/emscripten#9160]
I am working on porting a windows C++ library to webassembly. I am using ninja build system and I have provided the absolute path to emcc in the command to build object files in my ninja files. I noticed emscripten does not have an emcc.exe rather, a emcc.bat file which we run when we build. Ninja throws an error saying CreateProcess failed. I later found out  it was because .bat is not an exe and i ran it as 
`cmd.exe /C <path to emscripten>/emcc.bat <compiler options>`

This throws error 
`shared:ERROR: /nologo: No such file or directory ("/nologo" was expected to be an input file, based on the commandline arguments provided)`

there are many such /<option>'s  which are windows cl.exe's compiler options.

Looks like emcc.bat does not recognize the msvc options to me, can someone help me here?

PS: I have built my library successfully with the same ninja file except changing the command to
`<path to fastcomp/bin/clang-cl>/clang-cl.exe a.cc -o a.obj <compiler options>`

Can someone tell me what are the best practices/ways to build a [C++ project of windows] in windows using emcc, preferably using ninja build system if that matters?

Edit: I noticed that this is because the emcc.py file parses input options and that is what's raising the error because emcc.py does not understand the msvc options.

**Comment by kripken** [comment]
`emcc` is compatible with gcc and clang commandline flags (most of them are handled by clang itself). There is no support for the msvc flags.

The best thing is usually to port the application to build using clang natively first, then port that to emscripten.
