### ISSUE TITLE
Header-only system libraries and CMake

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9184]
We tell CMake not to look at system libraries,

https://github.com/emscripten-core/emscripten/blob/incoming/cmake/Modules/Platform/Emscripten.cmake#L181-L185

which makes sense as they are compiled for the local system, and not for our cross-compiling. For header-only libraries, though, this could be safe, and maybe useful? Not sure how practical that would be though.

cc @juj

**Comment by sbc100** [comment]
On Thu, Aug 8, 2019 at 9:10 AM Alon Zakai <notifications@github.com> wrote:

> We tell CMake not to look at system libraries,
>
>
> https://github.com/emscripten-core/emscripten/blob/incoming/cmake/Modules/Platform/Emscripten.cmake#L181-L185
>
> which makes sense as they are compiled for the local system, and not for
> our cross-compiling. For header-only libraries, though, this could be safe,
> and maybe useful? Not sure how practical that would be though.
>
> cc @juj <https://github.com/juj>
>

I don't think its ever a good idea to use host include directories with a
cross compiler.  If a user wants headers to be available they can install
them in emscripten/system/local/include or and a `-I` flag to the command
line.

**Comment by juj** [comment]
Even if header only libraries would work, the trouble is that all those get stuffed in with the rest of the header files, so would not be able to distinguish between those that would work and those that don't.

I think the use cases where people are able to utilize header only libraries are so few, that if/when there are users that know they are able to pull that off, they can probably hardcode the system header directory themselves, and venture down such a path manually?

**Comment by kripken** [comment]
Makes sense. It's sad that it means some things don't just work, but I guess there just isn't a good solution for that.
