### ISSUE TITLE
Overhead from noexcept, in particular in libc++

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9185]
Consider this testcase:
```cpp
#include <emscripten.h>

void i_would_never_throw() noexcept {
  emscripten_get_now();
}

int main() {
  i_would_never_throw();
}
```
We have helpfully annotated the function `i_would_never_throw` as `noexcept`. Building with something like `emcc -c -emit-llvm -S -s DISABLE_EXCEPTION_CATCHING=0 -std=c++11` the output contains
```llvm
; Function Attrs: noinline nounwind optnone
define hidden void @_Z19i_would_never_throwv() #0 personality i8* bitcast (i32 (...)* @__gxx_personality_v0 to i8*) {
entry:
  %call = invoke double @emscripten_get_now()
          to label %invoke.cont unwind label %terminate.lpad

invoke.cont:                                      ; preds = %entry
  ret void

terminate.lpad:                                   ; preds = %entry
  %0 = landingpad { i8*, i32 }
          catch i8* null
  %1 = extractvalue { i8*, i32 } %0, 0
  call void @__clang_call_terminate(i8* %1) #4
  unreachable
}
```
This appears to be the correct behavior in clang, [as docs say](https://en.cppreference.com/w/cpp/language/noexcept_spec)

> Non-throwing functions are permitted to call potentially-throwing functions. Whenever an exception is thrown and the search for a handler encounters the outermost block of a non-throwing function, the function std::terminate is called

In libc++, this adds significant overhead in stuff like
```cpp
void mutex::unlock() _NOEXCEPT
{
    __libcpp_mutex_unlock(&__m_);
}
```
where `__libcpp_mutex_unlock` just directly calls `pthread_mutex_unlock`. The extra invokes end up calling into JS etc. We are seeing this overhead show up in profiles of real-world codebases so it would be good to do something here.

Note that this appears to happen because clang doesn't know that `pthread_mutex_unlock` and `emscripten_get_now` don't throw. Somehow it does know that e.g. `puts` won't. Do we need to annotate all our C API, including all of libc somehow?

cc @aheejin @dschuff

**Comment by juj** [comment]
> Note that this appears to happen because clang doesn't know that `pthread_mutex_unlock` and `emscripten_get_now` don't throw.

Hmm, if there is a difference, I think we should probably annotate every external JS function as `nothrow`? They will never throw C++ exceptions, and JS exceptions that they may throw do not really qualify? (unless we developed a wrap-a-JS-exception-into-a-C++-exception machinery which we don't have?)

**Comment by jgravelle-google** [comment]
IIRC this type of codegen-affecting out-of-band knowledge is modeled in clang in Builtins.def: https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/Builtins.def

Though that doesn't have puts so now I'm remembering that libcalls are different from builtins, maybe.

**Comment by dschuff** [comment]
https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/IR/RuntimeLibcalls.def has libcalls but it doesn't have puts, so I'm not sure how that in particular gets modeled.

But yeah it probably does make sense to try to model emscripten syscalls as nothrow.

**Comment by kripken** [comment]
Ok, sounds like we should add to the emscripten headers `noexcept` (or `throw()` if not c++11) for all functions?

And what about `pthread_mutex_unlock` - should we modify all the relevant musl headers as well? That seems like a nontrivial amount of work, and divergence from upstream - would that still be better than listing them in clang/llvm?

**Comment by aheejin** [comment]
> > Note that this appears to happen because clang doesn't know that `pthread_mutex_unlock` and `emscripten_get_now` don't throw.
> 
> Hmm, if there is a difference, I think we should probably annotate every external JS function as `nothrow`? They will never throw C++ exceptions, and JS exceptions that they may throw do not really qualify? (unless we developed a wrap-a-JS-exception-into-a-C++-exception machinery which we don't have?)

I'm not sure if we should do this. C++'s `catch` clause actually [_can_ catch foreign exceptions](https://github.com/llvm-mirror/libcxxabi/blob/a03db0b008026ef06aabb24abef806d962b31949/src/cxa_exception.cpp#L403-L406) (with `catch (...)`). And also the [new wasm exception proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/Exceptions.md) assumes the ability to catch foreign exceptions. Of course C++ can't directly examine the data within exceptions, but it can rethrow them.

**Comment by aheejin** [comment]
I'm not sure if there's a better way of handling this than annotating headers. Modifying clang frontend to not generate these for functions with certain names would be too hacky. We can try not to convert `invoke` into `invoke_sig` wrappers in [LowerEmscriptenEHSjLj](https://github.com/llvm/llvm-project/blob/master/llvm/lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp) pass in LLVM and run DCE after that to remove all code related to calling `std::terminate`, but this would only affect the emscripten EH, while this would be also useful for the new wasm exception scheme.

**Comment by kripken** [comment]
https://github.com/WebAssembly/binaryen/pull/2442 should optimize almost all that overhead away in binaryen.

**Comment by aheejin** [comment]
So can we close this?

**Comment by kripken** [comment]
I suspect there are still cases not covered by that PR. It assumes any JS import can throw, for example, as it doesn't know anything about what they do. So it would still be good to find a more general solution if there is one (which might be improving the optimization to identify specific imports, maybe).
