### ISSUE TITLE
can't install in Mac OS

### ISSUE THREAD

**Issue by wangfpp** [emscripten-core/emscripten#9199]
./emsdk install latest error:
$./emsdk install latest
Fetching emscripten-releases repository...
Cloning into '/Users/mac/study/emsdk/releases'...
fatal: unable to access 'https://chromium.googlesource.com/emscripten-releases/': Failed to connect to chromium.googlesource.com port 443: Operation timed out
['/usr/bin/git', 'clone', 'https://chromium.googlesource.com/emscripten-releases', '/Users/mac/study/emsdk/releases'] failed with error code 128!
Traceback (most recent call last):
  File "./emsdk", line 2756, in <module>
    sys.exit(main())
  File "./emsdk", line 2470, in main
    fetch_emscripten_tags()
  File "./emsdk", line 1805, in fetch_emscripten_tags
    emscripten_releases_tot = get_emscripten_releases_tot()
  File "./emsdk", line 1756, in get_emscripten_releases_tot
    recent_releases = git_recent_commits(sdk_path('releases'))
  File "./emsdk", line 679, in git_recent_commits
    returncode, stdout, stderr = run_get_output([GIT(), 'log', '-n', str(n), '--pretty="%H"'], cwd=repo_path)
  File "./emsdk", line 639, in run_get_output
    process = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE, env=os.environ.copy(), universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mac/study/emsdk/releases': '/Users/mac/study/emsdk/releases

what's wrong  how fix this error?

**Comment by wangfpp** [comment]
mybe i can't connect Google?

**Comment by kripken** [comment]
Sounds like a network error. Has it gone away or is it a constant problem?

**Comment by maoliangwu** [comment]
> mybe i can't connect Google?

is it resolved? I've met the same problem, do you have any way to connect google?

**Comment by sbc100** [comment]
I'm pretty sure this is not a emsdk bug a connectivity issue with google cloud storage.  Happy to re-open if anyone disagrees.
