### ISSUE TITLE
Continuous Integration tests never pass

### ISSUE THREAD

**Issue by cclauss** [emscripten-core/emscripten#9204]
It is not very helpful if the CI tests _never_ pass when submitting pull requests.

In seven pages of open PRs, there is not a single instance of the CI tests passing.  There are numerous instances where they never even run to completion.  Perhaps some thought should be given to how CI can give a clearer signal to both contributors and reviewers of the validity of proposed changes.

**Comment by kripken** [comment]
I agree this should be better.

We have random failures on some browser tests. We're not sure why that happens, and could use help in figuring it out. Until then, the people with commit access generally know which browser failures are ok to ignore, and we do run each test multiple times - in chrome and firefox, and fastcomp and upstream - so unless on fails in more than one, it's likely a random error.

CI not running to completion is not a known problem. Maybe that's related to the recent removal/replacement of `wasm1`? Older PRs will see it as "pending" in some cases. If you saw something other than that, where was it?

**Comment by kripken** [comment]
I think this has gotten a lot better, it's very rare to see a random failure now.
