### ISSUE TITLE
ASYNCIFY_WHITELIST fails on Windows

### ISSUE THREAD

**Issue by gabrielcuvillier** [emscripten-core/emscripten#9206]
Following #9128, I've spotted this one on Windows:

test.cpp:
```
void f(bool,bool) {
  return;
}

int main() {
  f(true,true);
}
```

command:
```
emcc test.cpp --profiling -s ASYNCIFY=1 -s 'ASYNCIFY_WHITELIST=["f(bool, bool)"]' -o test.html
```
will fail with
```
shared:ERROR: unclosed opened string list. expected final character to be "]" in "[f(bool, bool)]'"
```
(notice the trailing ' at the end...)

**Comment by quantum5** [comment]
This is just a windows command line quoting issue. The proper windows way to quote that argument in JSON format is

    "ASYNCIFY_WHITELIST=[\"f(bool, bool)\"]"

**Comment by gabrielcuvillier** [comment]
@quantum5 @kripken I've found a secondary issue:
While quantum5 is right about the way to quote the arguments on Windows, that nevertheless did not worked for me on the D3 port. The problem is with the C++ reference "&" syntax , try with this:

```
emcc test.cpp --profiling -s ASYNCIFY=1 -s 'ASYNCIFY_WHITELIST=["f(bool&, bool)"]' -o test.html
```
... this will fail on windows. I did not found a way to escape the & character

**Comment by quantum5** [comment]
You escape the `&` operator in `cmd.exe` with `^`.

**Comment by dschuff** [comment]
I wonder if we should add an option to read the whitelist from a file....

**Comment by quantum5** [comment]
Yes, I think that has been suggested before. I think that's a good idea.

**Comment by dschuff** [comment]
Actually, does our existing response file support work for this?

**Comment by gabrielcuvillier** [comment]
`^&` did not worked, as cmd.exe will not escape it (probably because the ^ is in a " " pair ? I don't know). But after random tweaking attempts, I finally found the following tricky workaround for windows: `"&"`

For windows:
`emcc test.cpp --profiling -s ASYNCIFY=1 -s "ASYNCIFY_WHITELIST=[\"f(bool"&", bool)\"]" -o test.html`

For linux:
`emcc test.cpp --profiling -s ASYNCIFY=1 -s 'ASYNCIFY_WHITELIST=["f(bool&, bool)"]' -o test.html`


This is a bit mad. I definitiely think response files should be used instead...

**Comment by gabrielcuvillier** [comment]
I'd take a look at the new response file feature to see if it works. Btw, the solution I explained solves my problem, so I close the issue.
