### ISSUE TITLE
shared:ERROR: The JavaScript shell used for compiling (['E:/emsdk/node/8.9.1_64bit/bin/node.exe']) does not seem to work

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [emscripten-core/emscripten#9211]
Hello everyone.
I've previously installed `emscripten-1.38.25` on Kali Linux 20182, i copied the whole `emsdk` folder on a flash storage device then copied it into windows 10.
I followed the instructions at the [Download and install](https://emscripten.org/docs/getting_started/downloads.html#installation-instructions) page and re-ran `emsdk activate latest` and `emsdk_env` commands.

The output of `emsdk activate latest` is as follow:

> Writing .emscripten configuration file to user home directory C:\Users\USER/
> The Emscripten configuration file C:\Users\USER\.emscripten has been rewritten with the following contents:
> 
> import os
> LLVM_ROOT = 'E:/emsdk/clang/e1.38.32_64bit'
> EMSCRIPTEN_NATIVE_OPTIMIZER = 'E:/emsdk/clang/e1.38.32_64bit/optimizer.exe'
> BINARYEN_ROOT = 'E:/emsdk/clang/e1.38.32_64bit/binaryen'
> NODE_JS = 'E:/emsdk/node/8.9.1_64bit/bin/node.exe'
> PYTHON = 'E:/emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
> JAVA = 'E:/emsdk/java/8.152_64bit/bin/java.exe'
> EMSCRIPTEN_ROOT = 'E:/emsdk/emscripten/1.38.32'
> SPIDERMONKEY_ENGINE = ''
> V8_ENGINE = ''
> TEMP_DIR = 'c:/users/user/appdata/local/temp'
> COMPILER_ENGINE = NODE_JS
> JS_ENGINES = [NODE_JS]
> 
> Adding directories to PATH:
> PATH += E:\emsdk
> PATH += E:\emsdk\clang\e1.38.32_64bit
> PATH += E:\emsdk\node\8.9.1_64bit\bin
> PATH += E:\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64
> PATH += E:\emsdk\java\8.152_64bit\bin
> PATH += E:\emsdk\emscripten\1.38.32
> 
> Setting environment variables:
> EMSDK = E:/emsdk
> 
> Set the following tools as active:
>    clang-e1.38.32-64bit
>    node-8.9.1-64bit
>    python-2.7.13.1-64bit
>    java-8.152-64bit
>    emscripten-1.38.32
> 
> The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to permanently register this environment globally to all users in Windows Registry, rerun this command with the option --global.

The output of `emsdk_env` is as follow:

> Adding directories to PATH:
> PATH += E:\emsdk
> PATH += E:\emsdk\clang\e1.38.32_64bit
> PATH += E:\emsdk\node\8.9.1_64bit\bin
> PATH += E:\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64
> PATH += E:\emsdk\java\8.152_64bit\bin
> PATH += E:\emsdk\emscripten\1.38.32
> 
> Setting environment variables:
> EMSDK = E:/emsdk

However, when i run `emcc` in the command line interface i got the following output:

> root:INFO: Checking JS engine ['E:/emsdk/node/8.9.1_64bit/bin/node.exe'] failed. Check your config file. Details: [Error 2] The system cannot find the file specified
> shared:WARNING: cannot check node version: [Error 2] The system cannot find the file specified
> shared:INFO: (Emscripten: Running sanity checks)
> shared:ERROR: The JavaScript shell used for compiling (['E:/emsdk/node/8.9.1_64bit/bin/node.exe']) does not seem to work, check the paths in C:\Users\USER\.emscripten

How can i resolve this issue ?, show i download re-download the SDK again on windows ?
Thanks in advance.

**Comment by sbc100** [comment]
Yeah you need to start again and install on windows, the SDK is not portable across OSes like that.
