### ISSUE TITLE
Asyncify: pause function called by extern function does not work correctly

### ISSUE THREAD

**Issue by qingyuealone** [emscripten-core/emscripten#9216]
<h2>Environment</h2>
<ul>
<li>emscripten: latest-upstream</li>
<li>OS: win7</li>
<li>Browser: Chrome 76</li>
</ul>
<pre><code>
clang version 10.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project ea134f221f2a5c075b7539876a444b4a07362912)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: F:/emsdk/upstream/bin
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.41</code></pre>
<h2>Repro</h2>
<p><code>main.cpp</code></p>
<div class="highlight highlight-source-c"><pre>
#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>emscripten.h<span class="pl-pds">&gt;</span></span>
#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>emscripten/bind.h<span class="pl-pds">&gt;</span></span>
#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>stdio.h<span class="pl-pds">&gt;</span></span>
 
<span class="pl-en">extern "C" </span>{
<span class="pl-k">    extern </span><span class="pl-c1">void initProj</span>(void);
}
    
<span class="pl-en">using namespace emscripten;</span>
    
<span class="pl-k">void</span> <span class="pl-en">do_asyncify</span>() {
<span class="pl-c1">    printf</span>(<span class="pl-s"><span class="pl-pds">"\t</span>do_asyncify<span class="pl-cce">\n</span><span class="pl-pds">"</span></span>);
<span class="pl-c1">    emscripten_sleep</span>(<span class="pl-c1">10</span>);
}

<span class="pl-en">EMSCRIPTEN_BINDINGS</span>(my_module) {
<span class="pl-c1">    function</span>(<span class="pl-c1">"do_asyncify", &do_asyncify</span>);
}

<span class="pl-k">void</span> <span class="pl-en">main_loop</span>() {
<span class="pl-c1">    //nothing</span>
}

<span class="pl-k">void</span> <span class="pl-en">main</span>() {
<span class="pl-c1">    printf</span>(<span class="pl-s"><span class="pl-pds">"</span>start<span class="pl-cce">\n</span><span class="pl-pds">"</span></span>);
<span class="pl-c1">    initProj</span>();
<span class="pl-c1">    emscripten_set_main_loop</span>(<span class="pl-c1">main_loop, 0, 0</span>);
<span class="pl-c1">    printf</span>(<span class="pl-s"><span class="pl-pds">"</span>end<span class="pl-cce">\n</span><span class="pl-pds">"</span></span>);
 }
</pre></div>
<p><code>pre.js</code></p>
                            <div class="highlight highlight-source-c"><pre>
<span class="pl-en">mergeInto</span>(LibraryManager.library, {
      initProj:<span class="pl-c1">function</span>() {
<span class="pl-c1">        console.log</span>(<span class="pl-s"><span class="pl-pds">"\n</span>initProj begin{<span class="pl-cce">\n</span><span class="pl-pds">"</span></span>);
<span class="pl-c1">        Module.do_asyncify</span>();
<span class="pl-c1">        console.log</span>('<span class="pl-s">}initProj end<span class="pl-cce">\n</span><span class="pl-pds">"</span></span>);
      },
});
</pre></div>

<p>And compile it with following command:</p>
<pre><code>emcc --bind -o main.html main.cpp -s WASM=1 --shell-file shell.html -s ASYNCIFY -s -g3 --js-library pre.js \
        -s 'ASYNCIFY_IMPORTS=["initProj", "emscripten_sleep"]'
</code></pre>
<p>Host the directory with web server and browse <code>main.html</code> from browser</p>
<h2>Expected behavior</h2>
<p>In DevTools console, expected log output is:</p>
<pre><code>
    Start
    initProj begin{
    	do_asyncify complete
    }initProj end
    End
    </code></pre>
                            <h2>Actual Behavior</h2>
                            <p>In DevTools console, actual log output is:</p>
                            <pre><code>
    Start
    initProj begin{
    }initProj end    

    initProj begin{
    	do_asyncify complete
    }initProj end
    end
</code></pre>
<p>is that means the unwinding and rewinding is wrong, but why</p>

**Comment by kripken** [comment]
The testcase here looks incomplete or incorrect:

 * I had to add `void` as the return type for `initProj`, otherwise it hits `main.cpp:6:12: error: C++ requires a type specifier for all declarations`
 * `do_asyncify` is defined twice in `main.cpp`. Should the last one be `main()`? (If so the return type also must change.)
 * The pre.js file is missing a `"`.
 * The pre.js uses `Module.print` without exporting it first (can just use `console.log(..)` for debugging, or use the internal emscripten JS helper `out(..)`.

**Comment by qingyuealone** [comment]
I'm so sorry, you are right, there are several clerical errors:
1. extern void initProj(void);
2. void main(replace second do_asyncify)
3. in pre.js file: Module.print('}initProj end\n'); and you can use console.log(...)
(I'm not a  web programmer when I use the Html, I copy the wrong code. I'm sorry for that!)
