### ISSUE TITLE
GLctx is undefined error in render function in a single-threaded OpenGL 2.0 app

### ISSUE THREAD

**Issue by shaovoon** [emscripten-core/emscripten#9217]
The [OpenGL 2.0 project](https://github.com/shaovoon/simple_opengl) showing a rotating quad is made to reproduce the problem. It works perfectly on VC++ and Windows.

There is a problem with the latest Emscripten calling the render function. Any 1st OpenGL call in the render function has this "GLctx is undefined" error in javascript on Chrome and Firefox. I am not multi-threading.

```Cpp
#ifdef __EMSCRIPTEN__
    emscripten_set_main_loop(render, 0, 0);
#else
...

void render()
{
    // Clear the color buffer
    glClear(GL_COLOR_BUFFER_BIT); <--- exception on this function.
...
}
```

**Comment by kripken** [comment]
It may be helpful to look at examples in the test suite for working code (under `tests/`, can search for `glClear` for example).

In general I'd guess maybe the GL context was not set up? There are various ways to do that, depending on if you use SDL or glut or something else.

**Comment by shaovoon** [comment]
After looking at tests folder, I copied the code below. It works now. The SDL2 implementation is definitely broken. The emscripten_set_canvas_element_size below specifies the canvas id which SDL2 does not. The SDL2 code is originally working in Emscripten without modification.

```
emscripten_set_canvas_element_size("#canvas", SCREEN_WIDTH, SCREEN_HEIGHT);
EmscriptenWebGLContextAttributes attr;
emscripten_webgl_init_context_attributes(&attr);
attr.alpha = attr.depth = attr.stencil = attr.antialias = attr.preserveDrawingBuffer = 
  attr.failIfMajorPerformanceCaveat = 0;

attr.enableExtensionsByDefault = 1;
attr.premultipliedAlpha = 0;
attr.majorVersion = 1;
attr.minorVersion = 0;
EMSCRIPTEN_WEBGL_CONTEXT_HANDLE ctx = emscripten_webgl_create_context("#canvas", &attr);
emscripten_webgl_make_context_current(ctx);
```

**Comment by shaovoon** [comment]
The workaround is written in my 2nd post (that specifies the canvas id). Case closed.

**Comment by nowakowsk** [comment]
I may be doing something wrong, but it doesn't seem like `SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);` has any effect.

A workaround that worked for me was building with `-s MIN_WEBGL_VERSION=2`. It made my regular SDL2 code work, without need for Emscripten-specific initialization.
