### ISSUE TITLE
Emscripten error undefined symbols

### ISSUE THREAD

**Issue by senthilsivanath** [emscripten-core/emscripten#9231]
**Note : librdkafka uses tinycthread**

Unable to generate HTML from c file. 

Note : dependent librdkafka.a is already generated by emmake make

emcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I../src rdkafka_simple_producer.c  -o kafka_producer.html ../src/librdkafka.a -lm -ldl -lpthread -lrt -lpthread -lrt -v
shared:INFO: (Emscripten: Running sanity checks)
 "/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/bin/clang" -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=38 -D__EMSCRIPTEN_tiny__=41 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/libcxx -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/lib/libcxxabi/include -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/compat -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/libc -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/local/include -v -DEMSCRIPTEN -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I../src -mllvm -disable-llvm-optzns -g rdkafka_simple_producer.c -Xclang -disable-O0-optnone -Xclang -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/SDL -c -o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/rdkafka_simple_producer_0.o -emit-llvm
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 1b4148f39a69c7fc62edadd85e4122b68694dfb7) (emscripten 1.38.31 : 1.38.31)
Target: asmjs-unknown-emscripten
Thread model: posix
InstalledDir: /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/bin
 "/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/bin/clang-6.0" -cc1 -triple asmjs-unknown-emscripten -emit-llvm-bc -emit-llvm-uselists -disable-free -main-file-name rdkafka_simple_producer.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -no-integrated-as -mconstructor-aliases -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -target-linker-version 409.12 -v -coverage-notes-file /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/rdkafka_simple_producer_0.gcno -resource-dir /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/lib/clang/6.0.1 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=38 -D __EMSCRIPTEN_tiny__=41 -D _LIBCPP_ABI_VERSION=2 -D EMSCRIPTEN -I ../src -O2 -Werror=implicit-function-declaration -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -fno-dwarf-directory-asm -fdebug-compilation-dir /Users/senthil.sivanath/Documents/SourceCode/librdkafka/examples -ferror-limit 19 -fmessage-length 141 -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -nostdsysteminc -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/libcxx -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/lib/libcxxabi/include -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/compat -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/libc -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/lib/libc/musl/arch/emscripten -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/local/include -disable-O0-optnone -isystem/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/SDL -disable-llvm-optzns -o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/rdkafka_simple_producer_0.o -x c rdkafka_simple_producer.c
clang -cc1 version 6.0.1 based upon LLVM 6.0.1 default target x86_64-apple-darwin18.7.0
#include "..." search starts here:
#include <...> search starts here:
 ../src
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/libcxx
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/lib/libcxxabi/include
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/compat
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/libc
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/lib/libc/musl/arch/emscripten
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/local/include
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/system/include/SDL
 /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include
End of search list.
 "/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/bin/opt" /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/rdkafka_simple_producer_0.o -O3 -lower-non-em-intrinsics -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/rdkafka_simple_producer_0_1.o
 "/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/bin/opt" /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/rdkafka_simple_producer_0_1.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_broker.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_msg.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_topic.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_conf.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_timer.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_offset.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_transport.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_buf.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_queue.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_op.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_request.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_cgrp.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_pattern.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_partition.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_subscription.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_assignor.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_range_assignor.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_roundrobin_assignor.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_feature.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdcrc32.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/crc32c.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdmurmur2.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdaddr.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdrand.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdlist.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/tinycthread_extra.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdstring.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_event.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_metadata.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdregex.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdports.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_metadata_cache.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdavl.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_sasl.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_sasl_plain.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_interceptor.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_msgset_writer.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_msgset_reader.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_header.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_background.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_idempotence.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdvarint.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdbuf.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdunittest.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/snappy.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdhdrhistogram.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_lz4.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/xxhash.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/lz4frame.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/lz4hc.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdkafka_plugin.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rdlog.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/lz4.o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_H1jPNs_archive_contents/rddl.o /Users/senthil.sivanath/.emscripten_cache/asmjs/libc.bc /Users/senthil.sivanath/.emscripten_cache/asmjs/libcompiler_rt.bc /Users/senthil.sivanath/.emscripten_cache/asmjs/libc-wasm.bc /Users/senthil.sivanath/.emscripten_cache/asmjs/libc-extras.bc /Users/senthil.sivanath/.emscripten_cache/asmjs/libdlmalloc-debug.bc /Users/senthil.sivanath/.emscripten_cache/asmjs/libpthreads_stub.bc -disable-verify -internalize -internalize-public-api-list=main,malloc,free,__errno_location,htonl,htons,ntohs,_get_environ -globaldce -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/kafka_producer.bc
 "/Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/fastcomp/bin/llc" /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/emscripten_temp_kUfEnp/kafka_producer.bc -march=js -filetype=asm -o /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/tmpbzfUhB.4.js -emscripten-stack-size=5242880 -O2 -emscripten-precise-f32 -emscripten-global-base=1024 -emscripten-no-exit-runtime -emscripten-wasm -emscripten-only-wasm
error: undefined symbol: call_once
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: cnd_broadcast
error: undefined symbol: cnd_destroy
error: undefined symbol: cnd_init
error: undefined symbol: cnd_signal
error: undefined symbol: cnd_timedwait
error: undefined symbol: cnd_wait
error: undefined symbol: mtx_destroy
error: undefined symbol: mtx_init
error: undefined symbol: mtx_lock
error: undefined symbol: mtx_unlock
error: undefined symbol: pthread_kill
error: undefined symbol: thrd_create
error: undefined symbol: thrd_join
Error: Aborting compilation due to previous errors
shared:ERROR: '/Users/senthil.sivanath/Documents/SourceCode/emsdk/node/8.9.1_64bit/bin/node /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/src/compiler.js /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/tmpdjh89o.txt /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/src/library_pthread_stub.js' failed (1)

**Comment by VirtualTim** [comment]
So at a quick glance it looks like you're using threads, so should be compiling with the `-s USE_PTHREADS=1` flag, and not passing in -lpthread.

**Comment by senthilsivanath** [comment]
@VirtualTim  Have tried with the flag, but the undefined symbol is not resolving

emcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I../src test.c -o test.js ../src/librdkafka.a -lm -ldl -lrt -lrt -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2 -s ASSERTIONS=1 -s WASM=0
test.c:37:21: warning: unused variable 'rkt' [-Wunused-variable]
  rd_kafka_topic_t *rkt;  /* Topic object */
                    ^
test.c:15:13: warning: unused function 'stop' [-Wunused-function]
static void stop (int sig) {
            ^
2 warnings generated.
error: undefined symbol: call_once
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: cnd_broadcast
error: undefined symbol: cnd_destroy
error: undefined symbol: cnd_init
error: undefined symbol: cnd_signal
error: undefined symbol: cnd_timedwait
error: undefined symbol: cnd_wait
error: undefined symbol: mtx_destroy
error: undefined symbol: mtx_init
error: undefined symbol: mtx_lock
error: undefined symbol: mtx_unlock
error: undefined symbol: thrd_create
error: undefined symbol: thrd_join
Error: Aborting compilation due to previous errors
shared:ERROR: '/Users/senthil.sivanath/Documents/SourceCode/emsdk/node/8.9.1_64bit/bin/node /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/src/compiler.js /var/folders/b2/xnz96rgj3wv8k89r283lh1q9cbpqx4/T/tmpvHSFuA.txt /Users/senthil.sivanath/Documents/SourceCode/emsdk/fastcomp/emscripten/src/library_pthread.js' failed (1)

**Comment by sbc100** [comment]
I believe that we don't currently build the C11 thread support.   Currently we only have pthread support functions.   I looks like we could possible get these support from musl but we don't currently build those functions. 

Can you open a bug to add the missing C11 thread functions?

**Comment by senthilsivanath** [comment]
@sbc100 Thanks for clarifying.

I was able to build by disabling c11 mode to c pthreads mode. Although app was failing for a different TCP security reasons. 

Opening a different bug for missing c11 thread functions as requested.
