### ISSUE TITLE
rintf/lrintf slowness in wasm backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9236]
Consider this testcase:
```
#include <math.h>
#include <stdio.h>

int main(int argc, char** argv) {
  volatile float f;
  volatile double d;
  printf("%f\n", rintf(f));
  printf("%f\n", rint(d));
  printf("%ld\n", lrintf(f));
  printf("%ld\n", lrint(d));
}
```
The first and second calls are lowered into `f32.nearest` and `f64.nearest`, but something bad happens with the last two. They are libc functions, and inside libc there are calls to `rintf` and `rint`, which should also be turned into `nearest`... but we build libc with `-fno-builtin`...! So we end up calling the existing system lib support for those, which means `rint` in libc (large and likely slower than `nearest`) and `rintf` in JS (very slow to call out) :(

I'm not sure what is best here. One option is to add wasm instrinsics for `nearest` and to use them in libc?

cc @tlively @aheejin @dschuff

**Comment by tlively** [comment]
It would be relatively straightforward to ensure we have [clang builtins ](https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/BuiltinsWebAssembly.def) for every [wasm instruction](https://webassembly.github.io/spec/core/exec/numerics.html) that corresponds to a libc call, then make sure musl uses those builtins to implement the corresponding libc functions. The inliner would take care of the rest.

Alternatively, we could selectively compile musl files without `-fno-builtin`, but the builtins seem more generally useful and robust. Perhaps we could upstream the changes to musl as well.

**Comment by sbc100** [comment]
Why is that we need to build with `-fno-builtin`?  Does musl normally build with this flag?

**Comment by quantum5** [comment]
It appears that LLVM had intrinsics for `rint` and `rintf` since 9 years ago. We can just use `__builtin_rint*`.

> Why is that we need to build with `-fno-builtin`? Does musl normally build with this flag?

Clang likes to do clever things, for example, seeing a loop that does `memset` and replace it with a call to `memset`. Even if it's in your `memset` implementation.

**Comment by sbc100** [comment]
I guess I'd prefer not to modify musl.  But if this is general problem with musl (i.e. if people generally build it with `-fno-builtin`) then perhaps this is change that upstream would want too?

**Comment by sbc100** [comment]
Would LTO would eliminate all of this anyway?

**Comment by tlively** [comment]
> I guess I'd prefer not to modify musl. But if this is general problem with musl (i.e. if people generally build it with `-fno-builtin`) then perhaps this is change that upstream would want too?

I think it would, except that it would introduce a dependency on the compiler builtin. I'm not sure what musl's stance on that is.
