### ISSUE TITLE
`emrun` fails if HTML file name contains spaces

### ISSUE THREAD

**Issue by GregSlazinski** [emscripten-core/emscripten#9253]
I'm using `emrun` to test running HTML files on my computer without uploading them to a server.
However it fails if the HTML file name contains spaces.

**Comment by quantum5** [comment]
What platform and browser is this? It seems to work for me.

**Comment by GregSlazinski** [comment]
Windows chrome

**Comment by GregSlazinski** [comment]
Reopen

**Comment by sbc100** [comment]
Can you give an example of how to make it fail.

For example, this workflow seems to work fine:

```
$ emcc ~/test/hello.c -o "my test.html"
$ emrun "my test.html"
```

It ends up navigating to `http://localhost:6931/my%20test.html` which seems to work just fine.

What do we need to do reproduce this issue?

**Comment by GregSlazinski** [comment]
Hello,

I use this command to run emrun:
`ShellExecute(null, L"open", L"emrun", L"\"C:\\Esenthel\\_Projects\\_Build_\\Esenthel Fantasy Demo\\Emscripten\\Esenthel Fantasy Demo.html\"", null, SW_SHOWNORMAL);`

After that, 2 console windows get opened, and nothing happens:
![Capture-1](https://user-images.githubusercontent.com/7143443/91939319-cf8b3f80-ed1f-11ea-977c-f1703546687a.png)
![Capture-2](https://user-images.githubusercontent.com/7143443/91939328-d2863000-ed1f-11ea-989b-7936e682f721.png)

If I use path without spaces, then everything works fine
like "EsenthelFantasyDemo" instead of "Esenthel Fantasy Demo"

**Comment by quantum5** [comment]
This sounds like you are using the `start` command in `cmd.exe` incorrectly. The first quoted argument to `start` is treated as the window title of the newly opened command prompt window. You want to write: `ShellExecute(null, L"open", L"emrun", L"\"\"", L"\"C:\\Esenthel\\_Projects\\_Build_\\Esenthel Fantasy Demo\\Emscripten\\Esenthel Fantasy Demo.html\"", null, SW_SHOWNORMAL);`

**Comment by GregSlazinski** [comment]
I'm not using "start" command, I'm using "emrun"
My parameters are correct.
So the "emrun" must be at fault.
