### ISSUE TITLE
Missing C11 Thread functions

### ISSUE THREAD

**Issue by senthilsivanath** [emscripten-core/emscripten#9254]
error: undefined symbol: call_once
error: undefined symbol: cnd_broadcast
error: undefined symbol: cnd_destroy
error: undefined symbol: cnd_init
error: undefined symbol: cnd_signal
error: undefined symbol: cnd_timedwait
error: undefined symbol: cnd_wait
error: undefined symbol: mtx_destroy
error: undefined symbol: mtx_init
error: undefined symbol: mtx_lock
error: undefined symbol: mtx_unlock
error: undefined symbol: thrd_create
error: undefined symbol: thrd_join

**Comment by sbc100** [comment]
Ooops, sorry I already opened the issue: #9242
