### ISSUE TITLE
shared:WARNING: object /tmp/emscripten_temp_UjJqD0_archive_contents/*.c.o/*.cc.o is not a valid object file for emscripten, cannot link

### ISSUE THREAD

**Issue by wenjunyeah** [emscripten-core/emscripten#9255]
shared:WARNING: object /tmp/emscripten_temp_UjJqD0_archive_contents/options.c.o is not a valid object file for emscripten, cannot link

**Comment by sbc100** [comment]
Can you run with EMCC_DEBUG=1 and then maybe take a look at the options.c.o file to whats up with it?  If possible you can also attach the object to this ticket.
