### ISSUE TITLE
SDL2/SDL.h not found

### ISSUE THREAD

**Issue by remoe** [emscripten-core/emscripten#9259]
I cannot get it to work SDL2 with latest emscripten. I use a CMake environment without emsdk. From where get the cmake the SDL2 include and library path. I've used USE_SDL=2. But I only found files in ~/.emscripten_ports/sdl2. But this is not a install of SDL2. Do I need to call FindPackage(SDL2) and add includes and libraries in CMake ?

**Comment by remoe** [comment]
Thanks, but this doesn't help:

```
set ( USE_FLAGS "-s USE_SDL=2")
set ( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${USE_FLAGS}" CACHE STRING "" )
set ( CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${USE_FLAGS}" CACHE STRING "" )
set ( CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${USE_FLAGS} " CACHE STRING "" )
```

**Comment by sbc100** [comment]
What is the error you are seeing?

**Comment by remoe** [comment]
```c++
main.cpp:25:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.
```

**Comment by sbc100** [comment]
Somehow it looks like the `-s USE_SDL=2` is not getting through.   Can you show the `emcc` command that cmake is running in order to generate this error.

If you run something like `./emcc -s USE_SDL=2 -c tests/sdl2glshader.c` directly then presumably it works?

**Comment by remoe** [comment]
```emcc -s USE_SDL=2 -c tests/sdl2glshader.c``` works. 
But something doesn't work in my cmake environment. I don't see a emcc call.

update: I cleaned all with ```emcc --clear-ports``` and now it works. Didn't know what it was :)

**Comment by ford442** [comment]
I have just realized that this is a result of me using emconfigure ./configure when just ./configure is needed to build the initial package..
