### ISSUE TITLE
[upstream] Symbol naming inconsistency wrt leading underscores

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#9264]
In fastcomp, it used to be the case that symbols always had leading underscores:

- When specifying the exports via `-s EXPORTED_FUNCTIONS`, you had to add a leading underscore
- When working with the imports/exports from JS, all symbols had leading underscores

In upstream, it looks like the intention has been to remove leading underscores and indeed, in imports/exports they are not present anymore.

However, in `EXPORTED_FUNCTIONS` they are still required, e.g.

```
emcc src/vertexcodec.cpp src/indexcodec.cpp -O3 -DNDEBUG -s EXPORTED_FUNCTIONS='["meshopt_decodeVertexBuffer", "meshopt_decodeIndexBuffer"]' -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_STACK=24576 -s TOTAL_MEMORY=65536 -o build/meshopt_decoder.wasm
shared:ERROR: undefined exported function: "meshopt_decodeVertexBuffer"
```

(even though `meshopt_decodeVertexBuffer` is available by that name in the export table of the resulting .wasm binary; adding an underscore in EXPORTED_FUNCTIONS works).

Is this intentional? It's simple enough to work around but it seems like a bug.

**Comment by sbc100** [comment]
We want the command line flags to be compatible, so even though under the hood there are no underscores in the wasm imports/exports.. the user-facing symbols *do* have underscores.  So your functions on the module will have a leaving underscore and you still need to specify EXPORTED_FUNCTIONS with underscores.

One day it would be nice to fix this but we don't want to break users when they upgrade from fastcomp and we don't want to have to support two naming conventions at the same time in the JS code.

**Comment by sbc100** [comment]
So I this is WAI yes, or maybe you could call it a known issue?
