### ISSUE TITLE
Dead code elimination despite EMSCRIPTEN_KEEPALIVE

### ISSUE THREAD

**Issue by intrigus** [emscripten-core/emscripten#9271]
Hey, I'm trying to compile the freetype library.
This works fine, but the c file ([freetype.c](https://github.com/intrigus/gdx-freetype-gwt-gen/blob/master/freetype.c)) I wrote to interface with the library ends up being completely remvoed.
I've specified all functions in freetype. with EMSCRIPTEN_KEEPALIVE but this doesn't prevent them from being dce'd.

Is this intended behavior?
I can fix it with this change:
https://github.com/intrigus/gdx-freetype-gwt-gen/compare/d3ca456f91c7065fe9f4dd707b1c1839e7b0fe25...19ab1b5

I would have expected EMSCRIPTEN_KEEPALIVE to also prevent dce.
If this behavior is intended it might make sense to be more explicit about this in the docs. I could create a PR for this if wanted.

`emcc -v`:
````emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.24
clang version 6.0.1  (emscripten 1.38.24 : 1.38.24)
Target: x86_64-unknown-linux-gnu
````

[broken.zip](https://github.com/emscripten-core/emscripten/files/3520918/broken.zip)
[working.zip](https://github.com/emscripten-core/emscripten/files/3520919/working.zip)

**Comment by sbc100** [comment]
Can you try with a more recent version of emscripten.   There are no known issues with EMSCRIPTEN_KEEPALIVE today that I know of.

**Comment by intrigus** [comment]
I unfortunately can't try a more recent version.
Could you try this with a more recent version:
````bash
git clone https://github.com/intrigus/gdx-freetype-gwt-gen.git
git checkout d3ca456f91c7065fe9f4dd707b1c1839e7b0fe25
chmod +x doBuild.sh
./doBuild.sh````

When the resulting freetype.js is not around 1 mega byte size it failed.
