### ISSUE TITLE
[SIMD] support integer to integer widening

### ISSUE THREAD

**Issue by huningxin** [emscripten-core/emscripten#9283]
[WASM SIMD integer to integer widening](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#integer-to-integer-widening)
* `i16x8.widen_low_i8x16_s(a: v128) -> v128`
* `i16x8.widen_high_i8x16_s(a: v128) -> v128`
* `i16x8.widen_low_i8x16_u(a: v128) -> v128`
* `i16x8.widen_high_i8x16_u(a: v128) -> v128`
* `i32x4.widen_low_i16x8_s(a: v128) -> v128`
* `i32x4.widen_high_i16x8_s(a: v128) -> v128`
* `i32x4.widen_low_i16x8_u(a: v128) -> v128`
* `i32x4.widen_high_i16x8_u(a: v128) -> v128`

The integer to integer widening instructions are essential to implement some heavily used OpenCV.js universal intrinsics, e.g. [`v_dotprod`](https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html#gac6b7cdd3073adba3d9f3e0a2bc986809), [`v_reduce_sum`](https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html#ga38ffc32658e008a149f259b1637cb0be) and [`v_mul_expand`](https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html#ga8bb510213a964865860cccf6b1ee42bb).

**Comment by zhlwang** [comment]
i8x16.narrow_i16x8_s(a: v128, b: v128) -> v128
i8x16.narrow_i16x8_u(a: v128, b: v128) -> v128
i16x8.narrow_i32x4_s(a: v128, b: v128) -> v128
i16x8.narrow_i32x4_u(a: v128, b: v128) -> v128
Also the integer to integer narrowing instructions are essential in wasm SIMD code develop.

**Comment by tlively** [comment]
These instructions are available in 1.38.48 (the current latest), so I'll close this as fixed.
