### ISSUE TITLE
emscripten::val::gloal() can't access ES6 classes

### ISSUE THREAD

**Issue by shooshx** [emscripten-core/emscripten#9285]
JS:
class Foo {
}
C++;
emscripte::val foo_cls = emscripten::val::global("Foo")
assert !foo_cls.isUndefined()

It actually returns "undefined"
This is because in ES6 classes are not defined in the "window" which is what global() actually does.

see this answer:
https://stackoverflow.com/questions/30321636/es6-classes-what-about-instrospection/30322216#30322216

**Comment by kripken** [comment]
Perhaps `global` needs to do something different in workers too, where there also isn't `window`?
