### ISSUE TITLE
calling javascript from c++ without emcc

### ISSUE THREAD

**Issue by dcooley** [emscripten-core/emscripten#9294]
I would like to call javascript functions from C++, but I'm constrained whereby I can't use the `emcc` compiler in production.

My understanding is, the only way I can call javascript from c++ is to include `emscripten/val.h` in the .cpp file (as per the [examples / tutorial](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#using-val-to-transliterate-javascript-to-c) ). And for this to work it has to be compiled with `emcc`. 

Is it possible to do a two-stage build process, one where I use `emcc` to compile the required files, then include those files in my actual project and compile using `clang` (or equivalent)? If this is possible, do you have any documentation or templates showing how it's done?

**Comment by sbc100** [comment]
So you are trying to use upstream clang as you compiler?

How about the linker?  If you also can't use emscripten as that linker then it sounds like you will have basically roll you own.   You might want to look at the wasi sdk.  Or at least at more simple ways to call between JS and C++. The tutorial you are looking at is based on `embind` which is fairly emscripten specific and relied on the lot of glue code on both sides which is generated by emcc at link time. 

There are other, simpler ways to call back and forth such as ccall: 
 trying to use emscripten headers without emscripten/emcc is probably going to https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-ccall-cwrap

But honestly trying to use anythiing from emscripten without calling emcc is going be extremely difficult.

**Comment by dcooley** [comment]
Yes, the tutorial I link to is an `embind` example. I think I can make my question even more specific:

The examples which show calling javascript **from** c++ rely on including [`val.h`](https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/val.h), which in turn includes [`wire.h`](https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/wire.h)

When compiling with `emcc` everything works as expected.

So I tried compiling with `clang` to see what would happen, whether I could just include these headers into my project. However, it fails at [this assertion](https://github.com/emscripten-core/emscripten/blob/incoming/system/include/emscripten/val.h#L191)

```c++
static_assert(sizeof(GenericWireType) == 8, "GenericWireType must be 8 bytes");
static_assert(alignof(GenericWireType) == 8, "GenericWireType must be 8-byte-aligned");
```

Now I have a very limited understanding of how compilers work, so my questions are

1. Do you think it's at all possible to have a project which includes these headers and compiles with `clang` or `gcc`?

2. What is `emcc` doing that makes these assertions work? (I don't quite see how the `GenericWireType` can be 8 bytes)

(If the answer to 2 is more than a sentence don't worry about answering it)

**Comment by dcooley** [comment]
Thanks for the response @sbc100

**Comment by adaviding** [comment]
I was also stuck on this.  It is news to me that pointers are only 32-bits wide when compiled with enscriptem.

A similar issue is [here](https://github.com/emscripten-core/emscripten/issues/3674).
