### ISSUE TITLE
[SIMD] header needs an include guard

### ISSUE THREAD

**Issue by penzn** [emscripten-core/emscripten#9298]
[SIMD intrinsics header][h] needs an include guard to prevent it from getting included multiple times. See [emmintrin.h][e] for an example.

[h]: https://github.com/emscripten-core/emscripten/blob/incoming/system/include/wasm_simd128.h
[e]: https://github.com/llvm-mirror/clang/blob/master/lib/Headers/emmintrin.h#L10

**Comment by sbc100** [comment]
Hmm.. it also needs a copyright statement.

**Comment by penzn** [comment]
Hmm.. Good catch, copied one from one of the other header file.

**Comment by VirtualTim** [comment]
Fixed in #9299.
