### ISSUE TITLE
PThread.runningWorkers contents incorrect once a worker is returned to pool

### ISSUE THREAD

**Issue by erestor** [emscripten-core/emscripten#9307]
src/library_pthread.js:

in **_spawn_thread()**:
PThread.runningWorkers.push(worker);
here a **worker** object is pushed to the array.

in **returnWorkerToPool()**:
PThread.runningWorkers.splice(PThread.runningWorkers.indexOf(worker.pthread), 1);
here we're looking for a **pthread** instead of worker in the array

in **_kill_thread()**:
PThread.runningWorkers.splice(PThread.runningWorkers.indexOf(pthread.worker.pthread), 1);
same problem

**Comment by erestor** [comment]
Moreover, imo the line is long enough to justify creating a dedicated function, e.g. 
`removeRunningWorker(worker) {`
`var i = PThread.runningWorkers.indexOf(worker);`
`//could even provide a warning if the worker isn't there`
`PThread.runningWorkers.splice(i, 1);`
`}`

**Comment by VirtualTim** [comment]
Yeah, looks like you're right, there is a bug there.
You're fix looks right, do you want to create a PR?

Personally I think the function could be named something like `removeWorkerFromRunningWorkers`, and it might be good to add something like:
```
#if ASSERTIONS
  assert(i > 0);
#endif
```

So all up something like this:
```
removeWorkerFromRunningWorkers(worker) {
  var index = PThread.runningWorkers.indexOf(worker);
#if ASSERTIONS
  assert(index > 0);
#endif
  PThread.runningWorkers.splice(index , 1);
}
```

**Comment by VirtualTim** [comment]
Also this makes me think that the `terminateAllThreads` function may be wrong:
https://github.com/emscripten-core/emscripten/blob/baa28482c5f4b12062e7c11ed6b979bf961ae33d/src/library_pthread.js#L200-L206

I think that should maybe be something like:
```
for (var worker in PThread.runningWorkers) {
  if (worker.pthread) {
    PThread.freeThreadData(worker.pthread);
  }
  worker.terminate();
}
```

But I haven't actually tested this.

**Comment by erestor** [comment]
`terminateAllThreads` also uses the unused worker pool in the same manner, so someone should make the original intent behind those arrays clear before attempting to fix this. The names suggest they should contain workers but the usage suggests they should contain pthreads.

**Comment by VirtualTim** [comment]
Perhaps `runningWorkers` should be renamed to `runningWorkerPool` to mirror `unusedWorkerPool`, as I assume that's the intent.

**Comment by erestor** [comment]
Grand, so as long as we're clear that it really should be workers in those arrays I'll put together a PR.

**Comment by VirtualTim** [comment]
You'll probably have to run your PR by @juj, but this looks like the right approach to me.

**Comment by juj** [comment]
Good catch - indeed a bug here, something that functional tests would not be able to cover, since the bug causes workers to just silently accumulate up in the pool.

**Comment by juj** [comment]
Something like following should work: https://github.com/emscripten-core/emscripten/commit/05cfa71ffa1f637101dcdbf95a8b68908ea15302 . Unable to test at the moment though, feel free to work though a PR @erestor.

**Comment by erestor** [comment]
#9341 is the new pull request.
