### ISSUE TITLE
EM 1.38.42 Internal compiler error in src/compiler.js!

### ISSUE THREAD

**Issue by scotbenn** [emscripten-core/emscripten#9312]
We recently upgraded from 1.38.30 to 1.38.42 for glTexImage2d and pthread issues. We've also tried 1.38.41 and get hit the same results. While building our wasm components, we hit the following:
Error: ENOENT: no such file or directory, open '/src/library_websocket.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read (/local/emsdk/fastcomp/emscripten/src/compiler.js:62:34)
    at Object.load (eval at globalEval (/local/emsdk/fastcomp/emscripten/src/compiler.js:110:8), <anonymous>:172:17)
    at JSify (eval at globalEval (/local/emsdk/fastcomp/emscripten/src/compiler.js:110:8), <anonymous>:69:20)
    at Object.<anonymous> (/local/emsdk/fastcomp/emscripten/src/compiler.js:220:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
shared:ERROR: '/local/emsdk/node/8.9.1_64bit/bin/node /local/emsdk/fastcomp/emscripten/src/compiler.js /tmp/tmpni7zuw.txt /src/library_websocket.js /local/emsdk/fastcomp/emscripten/src/library_pthread.js' failed (1)

Here is our build environment:
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.42
clang version 6.0.1 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp--clang 98df4be387dde3e3918fa5bbb5fc43e1a0e1daac) (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-emscripten--core-emscripten--fastcomp 1b4148f39a69c7fc62edadd85e4122b68694dfb7) (emscripten 1.38.31 : 1.38.31)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/emsdk/fastcomp/fastcomp/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
shared:WARNING: java does not seem to exist, required for closure compiler, which is optional (define JAVA in /home/scotbenn/.emscripten if you want it)
shared:WARNING: closure compiler will not be available

I'm not sure what else you need from me, so please let me know. This issue didn't occur on 1.38.30 or 32. Thank you.

**Comment by sbc100** [comment]
Can you post the output with EMCC_DEBUG=1 set?

**Comment by scotbenn** [comment]
Thank you for the prompt reply. I've enabled debug and attached a txt file with the output.
[emscripten_debug.txt](https://github.com/emscripten-core/emscripten/files/3536510/emscripten_debug.txt)

**Comment by sbc100** [comment]
This looks like the output of two different emcc calls, is that right?

The first call is to compile wasmnotes.c.  This seems to succeed, although I will not that you probably don't  want command line to include `-I/system/include/libc/nptl -I/system/include/libc`.   They are your local linux headers.  This doesn't look like the cause of your problem though.

The next emcc invocation is to link the binary: 
```
/local/emsdk/fastcomp/emscripten/emcc.py -s USE_PTHREADS=1 -DEMSDK -DMOBILE -DOPENGL -DNO_DYNAMIC_LOADING -DNO_EM --emrun -s WASM -g2 -s FULL_ES2=1 -m32 -march=pentium3 -DGCC3 -DGCC4 -fno-strict-aliasing -DGCC_LBLB_NOT_SUPPORTED -felide-constructors -Wl,--whole-archive -rdynamic -s USE_PTHREADS -s TOTAL_MEMORY=1GB -s PTHREAD_POOL_SIZE=3 --preload-file /home/scotbenn/git/notes/kitfiles/wasm/tmpnotes@/tmpnotes -s FORCE_FILESYSTEM=1 -O0 --memory-init-file 1 -s NO_EXIT_RUNTIME -s --js-library /system/bin/../../src/library_websocket.js -s DEMANGLE_SUPPORT=1 /home/scotbenn/git/notes/kit/openssl/wasm/libcrypto.so.1.1 -o /home/scotbenn/git/notes/bin/wasm/bin/ -o /home/scotbenn/git/notes/bin/wasm/bin/wasmnotes.html wasmnotes.wasm.o /home/scotbenn/git/notes/bin/wasm/lib/notes0.o /home/scotbenn/git/notes/bin/wasm/bin/libndgts.so -Wl -L/home/scotbenn/git/notes/bin/wasm/bin -lnotes /home/scotbenn/git/notes/bin/wasm/bin/liblsxbe.so -Wl,--no-whole-archive -lm -L/usr/local/lib -L/usr/lib -lpthread -ldl --emscripten-cxx 
```

Did you run this command line?  It looks a little strange.   Firstly it contains the problematic --js-library `--js-library /system/bin/../../src/library_websocket.js`.    Secondly, right before that there seems to be a stray `-s`.   Finally, it contains ` -L/usr/local/lib -L/usr/lib -lpthread -ldl` all of which you probably don't want.

**Comment by scotbenn** [comment]
We only make the following call:

em++ -s USE_PTHREADS=1 -DEMSDK -DMOBILE -DOPENGL -DNO_DYNAMIC_LOADING -DNO_EM --emrun -s WASM -g2 -s FULL_ES2=1  -m32 -march=pentium3 -DGCC3 -DGCC4 -fno-strict-aliasing -DGCC_LBLB_NOT_SUPPORTED  -felide-constructors -Wl,--whole-archive -rdynamic -s USE_PTHREADS -s TOTAL_MEMORY=1GB -s PTHREAD_POOL_SIZE=3 --preload-file /home/scotbenn/git/notes/kitfiles/wasm/tmpnotes@/tmpnotes -s FORCE_FILESYSTEM=1 -O0 --memory-init-file 1 -s NO_EXIT_RUNTIME -s --js-library /system/bin/../../src/library_websocket.js -s DEMANGLE_SUPPORT=1 /home/scotbenn/git/notes/kit/openssl/wasm/libcrypto.so.1.1 -o $NOTESBIN/ -o /home/scotbenn/git/notes/bin/wasm/bin/wasmnotes.html `build %1 @obj.wasmnotes.wasm.tmp -d -s /home/scotbenn/git/notes/bin/wasm/lib/notes0.o /home/scotbenn/git/notes/bin/wasm/bin/libndgts.so -Wl -L/home/scotbenn/git/notes/bin/wasm/bin -lnotes /home/scotbenn/git/notes/bin/wasm/bin/liblsxbe.so -Wl,--no-whole-archive -lm -L/usr/local/lib -L/usr/lib -lpthread -ldl

I am not calling the /local/emsdk/fastcomp/emscripten/emcc.py........

**Comment by scotbenn** [comment]
Oh geez.... I see the problem..... duh..... thank you! I'll fixit, build again and let you know.

**Comment by scotbenn** [comment]
Working again! Thank you for your prompt support!
