### ISSUE TITLE
Is it possible to compile v8 to webassembly with emscripten?

### ISSUE THREAD

**Issue by bgnx** [emscripten-core/emscripten#9314]
Is it even possible? It would be awesome! At first glance V8 it's not different from a simple c++ applications except some business related to jit but I think I can be feasible by transpiling it to js calls which will generate and load new wasm modules at runtime, so if some function is running without deoptimizations in v8 it should be (in ideal case) no performance penalty running it inside wasm-compiled v8. Hoverer there is one challenge - v8 emits optimized code for real processors directly (without llvm bytecode which powers emscripten) - and it's interesting question how compile x64_86 asm code to wasm and how it affects performance (I suspect there is not so much penalty because v8 will be optimize generated code back and eliminate some overhead)

**Comment by blockspacer** [comment]
Yes, see
(old webkit engine, only js) https://github.com/mbbill/JSC.js
(semi-broken, old webkit engine, full browser port to WASM/ASMJS) https://github.com/trevorlinton/webkit.js
(new blink engine, without js, cobalt based) https://github.com/blockspacer/skia-opengl-emscripten

**Comment by blockspacer** [comment]
'which will generate and load new wasm modules at runtime' - you can embed clang/cling and execute C++ as usual / JIT / bytecode also. May be similar app size overhead (+5 to 30Mb).
See 
https://github.com/QuantStack/xeus-cling
https://github.com/tbfleming/cib

**Comment by PaperPrototype** [comment]
For anyone discovering this issue in the future there is already projects with full JS vm's using quickjs (lightweight alternative to V8 with a focus on embedding):
https://github.com/sebastianwessel/quickjs
https://github.com/justjake/quickjs-emscripten
https://github.com/reearth/quickjs-emscripten-sync

There is also Javy (https://github.com/bytecodealliance/javy):
> Run your JavaScript on WebAssembly. Javy takes your JavaScript code, and executes it in a WebAssembly embedded JavaScript runtime. Javy can create very small Wasm modules in the 1 to 16 KB range with use of dynamic linking. The default static linking produces modules that are at least 869 KB in size.

Javy is a CLI tool that compiles you javascript ahead of time into a wasm binary, and idk if it can be used as a library in the browser or not just FYI
