### ISSUE TITLE
add tests demonstrating use of co_await, co_yield, etc., which is now available via clang/llvm

### ISSUE THREAD

**Issue by unicomp21** [emscripten-core/emscripten#9316]

**Comment by unicomp21** [comment]
Hopefully we can deprecate Asyncify.

**Comment by unicomp21** [comment]
https://blog.panicsoftware.com/your-first-coroutine/

**Comment by Akaricchi** [comment]
I'm very much interested in getting any kind of coroutine support working with emscripten; unfortunately I don't have nearly sufficient understanding of the internals to implement it myself. It doesn't help that the fastcomp asyncify and empterpreter implementations are both broken in different ways. I figured these are not maintained anymore, so I'm not sure if its worth reporting the bugs.

**Comment by unicomp21** [comment]
I'll see if I can test a simple test going ...

**Comment by unicomp21** [comment]
My humble apologies for being so arrogant, didn't fully understand Asyncify.  Wow, this rocks!

Is there a future within webassembly where we can track cache-line faults and schedule coroutines accordingly?
