### ISSUE TITLE
SDL_NumJoysticks always returns 0

### ISSUE THREAD

**Issue by yylittlefish** [emscripten-core/emscripten#9318]
Hi, I'm tring to run a gamepad code in ubuntu.
I compiled the sample code testjoystick.c with emcc like this:
emcc testjoystick.cpp  -s USE_SDL=2 -o index.html
when I open the index.html in browser(I tried chrome and firefox), SDL_NumJoysticks() always returns 0.
to make sure the gamepad works fine, I tested with the w3c gamepad test suit(https://w3c-test.org/gamepad/), it works fine.
Is anybody know the reason?

**Comment by Daft-Freak** [comment]
Gamepads aren't visible immediately and the `SDL_NumJoysticks` call happens too early. When I was testing gamepads I used [this](https://github.com/emscripten-ports/SDL2/blob/master/test/emscripten/joystick-pre.js) as a `--pre-js`. (That was a while ago though.)

**Comment by yylittlefish** [comment]
> Gamepads aren't visible immediately and the `SDL_NumJoysticks` call happens too early. When I was testing gamepads I used [this](https://github.com/emscripten-ports/SDL2/blob/master/test/emscripten/joystick-pre.js) as a `--pre-js`. (That was a while ago though.)

yes! that wroks!
besides --pre-js, also need to add flag "-s FORCE_FILESYSTEM=1":
emcc testjoystick.cpp -s USE_SDL=2 -o index.html --pre-js joystick-pre.js -s FORCE_FILESYSTEM=1

btw, are you farmiliar with audio capture? could you help to also check this issue ,please?
https://github.com/emscripten-ports/SDL2/issues/91
thank you very much!
