### ISSUE TITLE
Emscripten 42: TypeError: GLctx is undefined

### ISSUE THREAD

**Issue by scotbenn** [emscripten-core/emscripten#9320]
Hello, I had been using 1.38.30 and 1.38.32 for some time and recently moved up to 1.38.42 because something changed that fixed glTexImage2D and pThread issue and frame buffers. After moving to 42, I am not getting a GLctx is undefined error at launch time that I wasn't getting before. The way I setup the EGL context has not changed. It follows the guidelines of the Emscripten tests and document here: https://emscripten.org/docs/porting/multimedia_and_graphics/EGL-Support-in-Emscripten.html?highlight=egl

I'm not sure what you need from me to help figure this out. Any help is greatly appreciated. Thank you.

**Comment by scotbenn** [comment]
Here is screen shot of the FF browser console:
![image](https://user-images.githubusercontent.com/41883241/63688878-23d71780-c7ce-11e9-877b-a20d144e655d.png)

**Comment by major-mayer** [comment]
Thank you very much for the hint with `OFFSCREEN_FRAMEBUFFER`.
I wouldn't have found the documentation without you pointing me to it, but if anyone has the same problem, here it is: 
https://emscripten.org/docs/api_reference/html5.h.html?#c.EmscriptenWebGLContextAttributes.renderViaOffscreenBackBuffer
