### ISSUE TITLE
Memory not freed on page reload

### ISSUE THREAD

**Issue by askuri** [emscripten-core/emscripten#9321]
I'm coding a library that uses embind so I can access its functions through JS. It might consume a lot of memory and eventually run OOM. I've set the flag `-s TOTAL_MEMORY=500MB`.

Now, if it has run OOM or not doesn't matter. If I reload the page, it allocates memory beyond the 500MB that I set without having freed the old one. The old memory is only freed if I close the tab or browser.
This is also the case if I let my library free all the memory and remove all references to it.

I've tested this under Firefox and Chromium. Newest Emsdk pulled today.

### Steps to reproduce
* open the site under which the script runs. I've bundled my built here: [oomtest.zip](https://github.com/emscripten-core/emscripten/files/3542110/oomtest.zip)
* watch your ram/cpu until it has stabilized. It should take some 500mb of RAM.
* refresh the website. The RAM usage should now continue to climb, exceeding the limit while not freeing up old RAM.

### Code (simplified)
lib.cpp
```#include <vector>
#include <emscripten/bind.h>
using namespace emscripten;
using namespace std;

class Test {
public:
	vector<int> vec;
	void add() {
		for (int i = 0; i < 30000000; i++) {
			vec.push_back(10000000);
		}
		vec.clear();
	}
};
// Binding code
EMSCRIPTEN_BINDINGS(Test) {
  class_<Test>("Test")
    .constructor()
    .function("add", &Test::add)
    ;
}
```
Script on the website
```var test;
var i = 0;
Module['onRuntimeInitialized'] = function() {
	test = new Module.Test();
	
	test.add();
};
```
CMakeLists.txt
```cmake_minimum_required(VERSION 3.10)
project(memtest)
set(CMAKE_CXX_STANDARD 17)
add_executable(memtest lib.cpp)
set_target_properties(memtest PROPERTIES LINK_FLAGS "--bind --emrun -s TOTAL_MEMORY=500MB")
```

**Comment by VirtualTim** [comment]
Sounds like a browser bug. See:
[https://bugs.chromium.org/p/chromium/issues/detail?id=935169](https://bugs.chromium.org/p/chromium/issues/detail?id=935169)
[https://bugs.chromium.org/p/chromium/issues/detail?id=877055](https://bugs.chromium.org/p/chromium/issues/detail?id=877055)

If you keep refreshing the page does the tab eventually crash?

**Comment by askuri** [comment]
> If memory is being retained after a page refresh, it would be a browser issue likely.
> 
> What is more likely is that the browser isn't freeing the 500MB because it didn't need to / just hasn't gotten around to it yet. If you put more pressure on it (i.e. start allocating enough memory that your system begins to run out RAM), it will likely start freeing some of the 500MB memory allocations from previous runs that are no longer needed.
> 
> Linux does something similar on an operating system level instead of at the application level to some degree. It'll "use up" all of your RAM until it specifically needs to free up space for something else. See: https://www.linuxatemyram.com/

Good Idea, I've also thought about that. But my System only has 4GB of RAM and 2GB swap, so it is fairly easy to actually run out of memory. I tried what @VirtualTim suggested and kept refreshing the page.
What happens can be seen here in this here: 
![screenshot](https://user-images.githubusercontent.com/2938495/63749850-9b7b7400-c8ac-11e9-910b-73ece5f3f8ac.png).
When the memory gets free in the end, that is probably me closing the browser so I don't risk a crash. I used Firefox this time.
Anyhow, I have **tried it again with chromium** this time, also with the dev console closed. Problem **did not occur**. So it was a coincidence of having this bug in Firefox generally and in Chromium when dev console open.
I'll report this to Mozilla now and close here. Thank you for your help.

**Comment by askuri** [comment]
@AjayP13 Then that is likely related to the chrome bug that VirtualTim has linked: https://bugs.chromium.org/p/chromium/issues/detail?id=935169

I have reported the bug I described above to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1576829
