### ISSUE TITLE
Require a recent node version and allow more recent JS features.

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#9332]
It seems reasonable to require a minimum of Node LTS (currently v10.x) for both building with emscripten and running the output.

This should enable us to use more moden JS features as well.

**Comment by curiousdannii** [comment]
If someone can't transpile for some reason, they have the option of using an older version of emscripten.

**Comment by curiousdannii** [comment]
At a minimum it would need options for both input features and output target, but you can be sure that people will ask for more options.
