### ISSUE TITLE
Concurrency issue with EMCC_LOCAL_PORTS

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#9342]
Hi,

When specifying EMCC_LOCAL_PORTS to point to e.g. a patched SDL2, parallel builds break:

```
cat <<EOF > main.c
void a(); void b(); void c(); void d();
int main(void) {
  a(); b(); c(); d();
}
EOF

for i in a b c d; do (echo "#include <stdio.h>"; echo "void $i() { printf(\"$i\n\"); }") > $i.c; done

cat <<EOF > Makefile
EMCC_LOCAL_PORTS = sdl2=../../build/SDL2
export EMCC_LOCAL_PORTS
CFLAGS=-s USE_SDL=2

all: main
main: main.o a.o b.o c.o d.o
clean:
	rm -f main *.o
EOF
```

```
$ emmake make clean; emmake make -j4
rm -f main *.o
/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc -s USE_SDL=2   -c -o main.o main.c
/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc -s USE_SDL=2   -c -o a.o a.c
/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc -s USE_SDL=2   -c -o b.o b.c
/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc -s USE_SDL=2   -c -o c.o c.c
system_libs:WARNING: using local ports: sdl2=../../build/SDL2
system_libs:WARNING: grabbing local port: sdl2 from ../../build/SDL2 to /home/me/.emscripten_ports/sdl2 (subdir: SDL2-version_18)
system_libs:WARNING: using local ports: sdl2=../../build/SDL2
system_libs:WARNING: grabbing local port: sdl2 from ../../build/SDL2 to /home/me/.emscripten_ports/sdl2 (subdir: SDL2-version_18)
Traceback (most recent call last):
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc.py", line 3557, in <module>
system_libs:WARNING: using local ports: sdl2=../../build/SDL2
system_libs:WARNING: grabbing local port: sdl2 from ../../build/SDL2 to /home/me/.emscripten_ports/sdl2 (subdir: SDL2-version_18)
    sys.exit(run(sys.argv))
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc.py", line 1851, in run
    compile_source_file(i, input_file)
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc.py", line 1833, in compile_source_file
    cmd = get_clang_command([input_file]) + ['-c', '-o', output_file]
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/emcc.py", line 1814, in get_clang_command
    args = system_libs.process_args(args, shared.Settings)
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/tools/system_libs.py", line 1597, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/tools/ports/sdl2.py", line 70, in process_args
    get(ports, settings, shared)
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/tools/ports/sdl2.py", line 19, in get
    ports.fetch_project('sdl2', 'https://github.com/emscripten-ports/SDL2/archive/' + TAG + '.zip', SUBDIR, sha512hash=HASH)
  File "/home/me/workdir/emtests/renpyweb/emsdk/fastcomp/emscripten/tools/system_libs.py", line 1429, in fetch_project
    shutil.copytree(path, os.path.join(fullname, subdir))
  File "/usr/lib/python2.7/shutil.py", line 200, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/me/.emscripten_ports/sdl2/SDL2-version_18'
...
```

This does not happen when using a builtin port.

Pre-generating the local port wouldn't help since, besides being an inconvenient work-around, local ports are always regenerated.

**Comment by kripken** [comment]
Ah, I think that makes sense. That was initially intended for local debugging, so we didn't test stuff like that. Probably we need to use the cache lock when using building a local port.

Perhaps there's a better approach for local ports, though (again, this was not a carefully designed feature, but rather done quickly to fill the need for debugging stuff with a port).

**Comment by Beuc** [comment]
I'm hitting another case of port directory removed during build.
Same reproducer, with `CFLAGS=-s USE_SDL=2 -s SDL_MIXER=2` even with `-j4`.
This is happening while testing a PR for SDL2.

**Comment by Beuc** [comment]
AFAIU:
- multiple emcc processes are run
- due to EMCC_LOCAL_PORTS each and every one wants to rebuild SDL2
- process#1 wants to rebuild SDL2, grabs the lock, and the proceed to build SDL2
- process#1 releases the lock and proceeds to build SDL2_Mixer
- process#2 grabs the lock and rebuild SDL2 *again* which removes SDL2_Mixer (as part of the build recipe, due to repopulating a shared headers directory), removing process#1's build dir as well.

There are multiple issues: unnecessary SDL2 rebuilds, and removing everything everytime SDL2 is rebuilt.
This is blocking when working on the SDL2 port, or when needing a local patch to SDL2.
I'm not sure how to proceed.

**Comment by kripken** [comment]
I guess process#2 rebuilds SDL2 because it's here? https://github.com/emscripten-core/emscripten/blob/incoming/tools/system_libs.py#L1543 Looks like there is no logic to know if another process build the local port already.

For now it seems like `EMCC_CORES=1` would be a workaround, but that's slow obviously. A proper solution would be to add support to know when the port is already built. For example we could write a file to there that contains the "version", and rebuilds only if the version is out of date. Unlike a normal port there isn't an obvious way to get the version, but one option would be to get the last update time of the port files (the files that the copytree there would copy).

**Comment by Beuc** [comment]
I think so yes, wrt L1543.

`EMCC_CORES=1`: thank you, I was looking for that option.
It doesn't help though, the ports builds are non-parallel but I still see several `using local ports: sdl2=xxx` in a row, and SDL2_Mixer fails the same.

(By the way, the build didn't fail with 1.39.0. I believe previously emcc didn't rebuild SDL2 when not using EMCC_LOCAL_PORT, even if the previous build was a port. I see a `check_tag()` whichnow detects this mismatch, so the bug triggers more consistently.)

**Comment by kripken** [comment]
I wonder if just copying the files only when they are newer is enough. That is, around line 1543 we copy all the source files into the port, and then when we build the port later it rebuilds it all because the files are all changed. But if we only copied if the sources are actually newer, that wouldn't happen - we only copy once, then stop.

I don't have a setup to test this (I'd need to have local copies of SDL2 and mixer etc., I guess), but I think this patch should do that, maybe you can test it @Beuc ?
```diff
diff --git a/tools/shared.py b/tools/shared.py
index b7fcd5f50..c69a28bad 100644
--- a/tools/shared.py
+++ b/tools/shared.py
@@ -199,6 +199,20 @@ def check_call(cmd, *args, **kw):
     exit_with_error("'%s' failed: %s", ' '.join(cmd), str(e))
 
 
+def get_all_files_under(dirname):
+  ret = []
+  for path, subdirs, files in os.walk(dirname):
+    for name in files:
+      ret.append(os.path.join(path, name))
+  return ret
+
+
+def dir_is_newer(dir_a, dir_b):
+  newest_a = max(list_of_files, key=os.path.getmtime)
+  newest_b = max(list_of_files, key=os.path.getmtime)
+  return os.path.getmtime(newest_a) < os.path.getmtime(newest_b)
+
+
 def generate_config(path, first_time=False):
   # Note: repr is used to ensure the paths are escaped correctly on Windows.
   # The full string is replaced so that the template stays valid Python.
diff --git a/tools/system_libs.py b/tools/system_libs.py
index adb1245a7..96751bed9 100755
--- a/tools/system_libs.py
+++ b/tools/system_libs.py
@@ -1554,10 +1554,14 @@ class Ports(object):
               logger.error('port %s lacks .SUBDIR attribute, which we need in order to override it locally, please update it' % name)
               sys.exit(1)
             subdir = port.SUBDIR
-            logger.warning('grabbing local port: ' + name + ' from ' + path + ' to ' + fullname + ' (subdir: ' + subdir + ')')
-            shared.try_delete(fullname)
-            shutil.copytree(path, os.path.join(fullname, subdir))
-            Ports.clear_project_build(name)
+            target = os.path.join(fullname, subdir)
+            if not shared.dir_is_newer(path, target):
+              logger.warning('not grabbing local port: ' + name + ' from ' + path + ' to ' + fullname + ' (subdir: ' + subdir + ') as the destination', target, ' is newer (run emcc --clear-ports if that is incorrect)')
+            else:
+              logger.warning('grabbing local port: ' + name + ' from ' + path + ' to ' + fullname + ' (subdir: ' + subdir + ')')
+              shared.try_delete(fullname)
+              shutil.copytree(path, target)
+              Ports.clear_project_build(name)
       finally:
         shared.Cache.release_cache_lock()
       return
```

**Comment by Beuc** [comment]
I seem to be missing "list_of_files" (at first glance it's not in git):
```
system_libs:WARNING: using local ports: sdl2=xxx/build/SDL2
system_libs:ERROR: a problem occurred when using an emscripten-ports library.  try to run `emcc --clear-ports` and then run this command again
Traceback (most recent call last):
  File "xxx/emsdk/upstream/emscripten-git/emcc.py", line 3665, in <module>
    sys.exit(run(sys.argv))
  File "xxx/emsdk/upstream/emscripten-git/emcc.py", line 2057, in run
    extra_files_to_link = system_libs.get_ports(shared.Settings)
  File "xxx/emsdk/upstream/emscripten-git/tools/system_libs.py", line 1715, in get_ports
    ret += [f for f in port.get(Ports, settings, shared) if not f.endswith('.txt')]
  File "xxx/emsdk/upstream/emscripten-git/tools/ports/sdl2.py", line 19, in get
    ports.fetch_project('sdl2', 'https://github.com/emscripten-ports/SDL2/archive/' + TAG + '.zip', SUBDIR, sha512hash=HASH)
  File "xxx/emsdk/upstream/emscripten-git/tools/system_libs.py", line 1558, in fetch_project
    if not shared.dir_is_newer(path, target):
  File "xxx/emsdk/upstream/emscripten-git/tools/shared.py", line 211, in dir_is_newer
    newest_a = max(list_of_files, key=os.path.getmtime)
NameError: global name 'list_of_files' is not defined
```

Testing is fortunately easy:
```
git clone https://github.com/emscripten-ports/SDL2 mySDL2
EMCC_LOCAL_PORTS=sdl2=mySDL2 emcc *.o -o test.html -s USE_SDL=2 -lSDL2_image -s USE_SDL_MIXER=2 -s USE_SDL_TTF=2
```

**Comment by kripken** [comment]
Oh sorry, `list_of_files` should be `get_all_files_under`. I guess I renamed it midway through the patch ;)

**Comment by kripken** [comment]
(Will try that test later if I find time, thanks!)

**Comment by Beuc** [comment]
(Sorry for re-reopening, there seem to be multiple issues as tested in 1.39.3.)

It seems there's a logic error:
```
def dir_is_newer(dir_a, dir_b):
  ...
  return newest_a < newest_b
```
"a is newer than b" means "newest_a > newest_b"

My local port wouldn't replace the current port even if I manually touch-ed files.

Moreover 'fetch_project' doesn't respect the Git tarball's timestamps (due to https://stackoverflow.com/questions/9813243/extract-files-from-zip-file-and-retain-mod-date) which means the default compilation is newer than it looks (zip extraction time vs. zip files timestamps). I can work-around by touch-ing one of my local port's files before each emcc call (in addition to fixing the comparison above) but we may need the stackoverflow fix.

Last, there seem to be a new issue as the check "SDL >= 2.0.0" by SDL_Mixer now fails (whatever the comparison used), I'll investigate as time permits.

**Comment by Beuc** [comment]
Hmmm actually I can't reopen the bug, let me know if I should open a new one.

**Comment by kripken** [comment]
Odd you can't reopen it since you originally created it, but I've never understood github rules on that... Reopened.

Hmm yes, that comparison does look wrong. But the testcase we had back then did work, I remember seeing it update the port when necessary. Maybe the testing was wrong...

**Comment by kripken** [comment]
(If you the flip the condition, does it work?)

**Comment by Beuc** [comment]
Maybe our testing was mostly focused on case newest_a == newest_b.

To recap, when flipping the condition to `newest_a > newest_b`:
- detecting a touch-ed local port now works
- local port needs to be always touch-ed in case the previous emcc call used the standard port
- SDL_Mixer fails to build with a SDL2 local port, whatever dir_is_newer's condition

**Comment by Beuc** [comment]
Some more investigation:

- the logic error in `dir_is_newer` is still present, so I would suggest flipping the condition before this is used in other contexts, independently of this issue

- cache lock safety is defeated by EM_EXCLUSIVE_CACHE_ACCESS=1 being set by emcc for child processes (in cache.acquire_cache_lock AFAICS), causing concurrent issues such as directory removals while other processes are still compiling

- using local paths in EMCC_LOCAL_PORTS also causes assertion issues in some cases where child emcc processes get started in the Emscripten dir (not the build directory)

All of this seems pretty fragile and seldom used, I'm not sure if it's better to spend time fixing it or moving away from it :/

**Comment by kripken** [comment]
@Beuc Interesting, good finds, and yeah, I think you're right - we should probably move away from it.

Maybe we can find a nicer way to make the local port look like a real port, so that we just change the URL (in sdl2, from `https://github.com/emscripten-ports/SDL2/archive/' + TAG + '.zip'`). For example if we run a local http server, we can literally change the URL and that would be it..?
