### ISSUE TITLE
Emscripten requires Node.js 8.10 but Emsdk provides only Node.js 8.9

### ISSUE THREAD

**Issue by juj** [emscripten-core/emscripten#9354]
Recently there has been an added requirement to have Node.js >= 8.10, but Emsdk only ships with Node.js 8.9.

If I manually adjust the check to only require Node.js 8.9, things seem to work fine. Why 8.10? Emsdk should probably be updated to bundle Node.js 8.10 instead of earlier 8.9 when upping the requirement from 8.9 to 8.10?

**Comment by trzecieu** [comment]
Hi @juj , do you know in which version this requirement has been added?

**Comment by kripken** [comment]
See #9333 #9345, we tried to update further, but had to temporarily revert that. After the reversion there should be no error?

**Comment by sbc100** [comment]
Trying against to land the emsdk upsdate: https://github.com/emscripten-core/emsdk/pull/341

These time we now have mac, linux and windows testing so it should be good.

**Comment by sbc100** [comment]
Should be fixed now.  emscripten requirements were reverted.
