### ISSUE TITLE
Major slowdown with function pointers

### ISSUE THREAD

**Issue by nepx** [emscripten-core/emscripten#9362]
Function pointers are 8-10x slower in asm.js/WebAssembly than in native, as illustrated by the following test case: 

```c
#include <stdio.h>
#include <sys/time.h>

#define START_TIME \
    struct timeval tval_before, tval_after, tval_result;\
    gettimeofday(&tval_before, NULL);
#define END_TIME gettimeofday(&tval_after, NULL);\
    timersub(&tval_after, &tval_before, &tval_result);\
    printf("Time elapsed: %ld.%06ld\n", (long int)tval_result.tv_sec, (long int)tval_result.tv_usec);

// 0: Regular loop
// 1: Regular loop modified to avoid nested while loop
// 2: Completely refactored to avoid double while
// 3: Returns the new value of "i." 
#define TEST_TYPE 2
#if TEST_TYPE==3
typedef struct insn insn_t;
#define RETTYPE struct insn*
#define RETTYPE2 insn_t* 
#else
#define RETTYPE void
#define RETTYPE2 void
#endif


struct insn{
    int lin;
    RETTYPE2 (*handler)(void*);
};
static struct insn ptr[5];

volatile int d = 0, // A dummy variable to give the functions something to do. 
             iterations = 100000000; // This variable is used elsewhere, prevent it from being optimized
static int exit, refill; // Some other helper variables

static RETTYPE test(void* e){
    d += 7;
#if TEST_TYPE==3
    return ((struct insn*)e) + 1; // Return the next instruction in the stream/ 
#endif
}

static RETTYPE test2(void* e){
    d -= 7;
#if TEST_TYPE==3
    return ((struct insn*)e) + 1;
#endif
}

static RETTYPE test3(void* e){
    d += 5;
#if TEST_TYPE==3
    return ((struct insn*)e) + 1;
#endif
}

static RETTYPE test4(void* e){ // This function forces the interpreter loop to go back to the top
#if TEST_TYPE == 0 || TEST_TYPE == 1
    //console.log("%d\n", iterations);
    refill = iterations; // Load the refill counter with the number of iterations left
    iterations = 1; // Set it to one so that it catches the (!--iterations) case below
#else
#endif
#if TEST_TYPE==3
    return &ptr[0]; // Go back to the top
#endif
}

int main(){
    struct insn* i;
    // These can be shuffled around to confuse the branch predictor. 
    ptr[0].handler = test;
    ptr[1].handler = test2;
    ptr[2].handler = test3;
    ptr[3].handler = test;
    ptr[4].handler = test4; // Last test case must be the end-of-trace function
    
    int e = 0;
    START_TIME;
#if TEST_TYPE == 0
    while(1){
#endif
        // In a real-world situation, there would be more sophisticated logic here. 
        i = &ptr[0]; // Start with opcode in position 0
        while(1) {
#if TEST_TYPE == 3
            i = 
#endif
            i->handler(i);
#if TEST_TYPE == 0
            if(!--iterations){
                if(!refill){ // If the iteration count was already zero before test4 was called, then quit
                    goto done;
                }
                iterations = refill; // Reset iteration count
                refill = 0; // Reset refill value
                break; // Go back to top
            }
            ++i; // Go to the next instruction
#elif TEST_TYPE == 1
            if(!--iterations){
                if(!refill){
                    goto done;
                }
                iterations = refill;
                refill = 0;
                i = &ptr[0]; // Sophisticated logic is inside the if statement instead of out in a separate loop
            }
            ++i;
#elif TEST_TYPE == 3
            if(!--iterations) // Every test case has been run, exit
                goto done;
#else // TEST_TYPE == 2
            if(!--iterations) goto done;
            if(e++ == 4) { // If four instructions have been executed, then go back to the top of the loop
                i = &ptr[0];
                e = 0;
            } else ++i;
#endif
        }
#if TEST_TYPE == 0
    }
#endif
    done:
    END_TIME;
    return 0;
}
```

I got the following results:

| Test    | System  | Elapsed time (s) |
|---------|---------|------------------|
| 0, 1, 2 | Native  | 0.2              |
| 0, 1, 2 | Firefox | 1.7              |
| 0, 1, 2 | Chrome  | 2.1              |
| 3       | Native  | 0.15             |
| 3       | Firefox | 1.15             |
| 3       | Chrome  | 1.5              |

Using WebAssembly actually *increased* each test case's run time by around 0.4 seconds. 

Is there any way to speed up indirect function calls?

**Comment by kripken** [comment]
Not currently - this is a definite downside of the current wasm spec.

Wasm does require such calls to be safe, which adds some overhead, but that they are slower than asm.js is indeed unfortunate.

**Comment by VirtualTim** [comment]
Just out of curiosity, would you be able to re-run those tests with `EMULATED_FUNCTION_POINTERS`? I'm just curious what the performance difference is there.

**Comment by nepx** [comment]
@VirtualTim I re-ran the tests, and the results were slow. It took 37 seconds for asm.js and 18 seconds for WebAssembly. I haven't run them for tests one or two, but I'd imagine the timing profile  looks similar. 

I took a look at the generated asm.js code, and it appears that the dispatch is well-optimized. The main loop of the test case I provided looks like this:

```javascript
 do {
  $$0 = FUNCTION_TABLE_ii[HEAP32[$$0 + 4 >> 2] & 7]($$0) | 0;
  $6 = (HEAP32[2] | 0) + -1 | 0;
  HEAP32[2] = $6;
 } while (($6 | 0) != 0);
```

At this point, I'm not sure if this is a bug in Emscripten, Binaryen (I'm not familiar enough with WebAssembly to understand the generated `wat` file), or the WebAssembly engine in Chrome/Firefox itself. Perhaps it's a combination of all three. 

Is there any way to work around this limitation via some combination of compilation flags, or will I have to create an issue elsewhere? Thank you very much for you help.

**Comment by VirtualTim** [comment]
Oh wow, that's shockingly slow. I'm sorry, I'm not really sure I can help. I was just curious about the performance impact for personal reasons. Sounds like `EMULATED_FUNCTION_POINTERS` is best avoided.

**Comment by kripken** [comment]
> At this point, I'm not sure if this is a bug in Emscripten, Binaryen (I'm not familiar enough with WebAssembly to understand the generated wat file), or the WebAssembly engine in Chrome/Firefox itself. Perhaps it's a combination of all three.

Sorry if I wasn't clear before @nepx - this is a combination of sandboxing (such calls must be safe) + that the wasm spec adds more overhead than asm.js did for such calls. See for example [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1340235).

(There may also be some variation between browsers on this too, if you see that please let us know!)

Overall there isn't much you can do - that's just how wasm was designed. In the future this may improve, as wasm may add more specific types for Tables, which could avoid of the current overhead. I'm not sure how much that would be.

**Comment by embeddedt** [comment]
@kripken What you are saying is that WebAssembly is actually slower than asm.js for function pointers?

If so, for an application that makes heavy use of function pointers for callbacks/event handlers/etc., would asm.js be a better choice or do the benefits of WebAssembly outweigh it?

**Comment by kripken** [comment]
> What you are saying is that WebAssembly is actually slower than asm.js for function pointers?

Yes.

> If so, for an application that makes heavy use of function pointers for callbacks/event handlers/etc., would asm.js be a better choice or do the benefits of WebAssembly outweigh it?

Well, wasm will be faster in general (maybe 10% or so) and also much much faster on specific things (like i64s). Also smaller to download. So unless you really hammer on indirect calls, likely wasm is better.

**Comment by VirtualTim** [comment]
That's interesting. [In the linked Firefox bug juj reported](https://bugzilla.mozilla.org/show_bug.cgi?id=1340235#c4) that `EMULATED_FUNCTION_POINTERS=1` caused a speed _increase_ of a couple percent, where nepx says it's about 10x slower.

I wonder if something changed, or if this is just different scenarios.

**Comment by kripken** [comment]
Maybe one of the two was `EMULATED_FUNCTION_POINTER_CASTS`? That's expected to be very slow (10x) or so.

`EMULATED_FUNCTION_POINTERS` on the other hand is not supported on upstream (because it's not needed), while on fastcomp it replaces the wasm function pointer calls with calls to JS and a table lookup there, and yeah, that may have been faster than the wasm calls at some point, but maybe not anymore.

**Comment by nepx** [comment]
@kripken This issue has significant performance implications for emulators, which typically dispatch each machine opcode using a `switch` statement or function pointers.
