### ISSUE TITLE
malloc(0): inconsistent behavior between emmalloc and dlmalloc

### ISSUE THREAD

**Issue by gabrielcuvillier** [emscripten-core/emscripten#9364]
I have a very large program which occasionally does `malloc(0)`

While this is working fine with dlmalloc, I noticed this was failing with emmalloc.

After some research, I found the following comment in dlmalloc.c: 

> Even a request for zero bytes (i.e., malloc(0)) returns a
>  pointer to something of the minimum allocatable size.

... and this in emmalloc.c:

> // malloc() spec defines malloc(0) => nullptr.
>   if (size == 0)
>     return nullptr;

So this is not consistent, and it can lead to unexpected crashes when changing the allocator in settings.js (for testing purposes for example).

In the end, the C standard just says malloc(0) is implementation defined. So I guess Emscripten should choose one way, but not both ;) My stance is on allowing it, as it is what typical stdlibs do nowadays.

**Comment by kripken** [comment]
Thanks! Yes, I agree.

This should be easy to change (just fix the code itself, and maybe a test needs to be updated). Happy to help with any codebase questions if someone's interested to take it on.

**Comment by gabrielcuvillier** [comment]
As a fix, would it be OK in emmalloc.c to simply "tweak" the input size argument to something like 1, 4 or 8 (in case it is 0) ?There's a slight memory consumption, but it looks like ok to me, as malloc(0) is not something very common. 

Actually, that's what I am doing upfront  in the program I am working on, and so far, this have been working well.

**Comment by kripken** [comment]
Yes, forcing it to allocate some space is probably fine. I assume that's what dlmalloc does too.
