### ISSUE TITLE
Optimizing WebGL advice, matching resolution, revisited?

### ISSUE THREAD

**Issue by greggman** [emscripten-core/emscripten#9365]
[The document on Optimizing WebGL](https://emscripten.org/docs/optimizing/Optimizing-WebGL.html) has this advice

> Pay close attention to the visible size of the canvas (the CSS pixels size of the DOM element) versus the physical render target size of the initialized WebGL context on the canvas, and make sure these two match in order to render 1:1 pixel perfect content.

That is not advice on "Optimizing WebGL". It might be advice on getting 1x1 pixels on the canvas. It's just as valid to make the canvas twice the resolution for pretty rendering or half the resolution for speed (which would actually be relevant to "Optimizing" WebGL)

Should that paragraph be changed or removed given it's not actually advice about optimizing?

**Comment by juj** [comment]
This advice was given to me by both Firefox and Chrome browser teams, rationale being that it gives browsers an opportunity to elicit an extra framebuffer blitting copy that would otherwise be needed to resize the contents, especially in fullscreen situations.

**Comment by greggman** [comment]
First off that makes zero sense in 2019 given that 

(a) most devices are HD-DPI

rendering 2880 x 1800 is up to 4x slower than rendering say 1440x900

(b) there is no API that will give you 1x1 pixels

see this thread https://github.com/KhronosGroup/WebGL/issues/587

(c) AFAIK there's no such thing as removing a blitting copy as the browser has to composite the canvas with any html. The only thing here is setting preserveDrawingBuffer false which is the default. If there is some short path (there wasn't when I helped implement WebGL on Chrome), then that paragraph is lacking all the details needed to make sure that short path happens.

It's possible maybe if there is only the canvas element, no other elements, it's fullscreen, it's alpha is set to false, it's set premultipliedAlpha: false, and it's 1x1 with the screen size then maybe there could be fast path but then you'd need to document all of that, not just say make things 1x1. You'd also probably want to say that you should draw to a smaller framebuffer and expand since drawing at a full HD-DPI resolution will be incredibly slow but then of course you're just repeating what the browser would do for you so I can't see how that's a win.

In any case, that paragraph by itself is anti-optimization

**Comment by juj** [comment]
Your reply reads like something has offended you here. I don't feel as strongly about this, feel free to post a PR to correct the guide to your liking.

If the part about devicePixelRatio is removed, it should probably be preserved somewhere else in the WebGL docs to highlight the fact that rendering will not be at actual resolution unless devicePixelRatio is taken into account.

**Comment by greggman** [comment]
Sorry, I'm not offended. I didn't mean to come across that way. Apologies.

devicePixelRatio won't help get 1x1 pixels. Just asking for its size of a canvas in CSS pixels and multiplying by devicePixelRatio is not enough sadly. That's what that linked thread was about.

My point is only that the advice is not correct AFAICT. The lazy solution is to delete the paragraph. The non-lazy solution is to ask the browser teams to be more clear exactly what they meant. If there is some special fast path it has a lot more requirements than just canvas = 1 to 1 pixels.

**Comment by greggman** [comment]
So FYI I asked here

https://github.com/KhronosGroup/WebGL/issues/2922

Ken Russel from the Chrome team and Jeff Gilbert from the Firefox team seem to verify my belief that that paragraph mentioned about above 1 to 1 rendering is not really an optimization. 

Should I submit a PR to delete it? Should I put more info about making smaller than 1 to 1 canvases for a speed up (like many console games do?) 

Thoughts?

**Comment by kripken** [comment]
Sounds like we should update the docs to match what the WebGL implementors
recommend in that link, yeah. Thanks!

- Alon

**Comment by ericoporto** [comment]
This was closed but it should possibly be reopened
