### ISSUE TITLE
Browser "Resist Fingerprinting" features might severly impact time.h functions

### ISSUE THREAD

**Issue by gabrielcuvillier** [emscripten-core/emscripten#9367]
When a browser such as Firefox have the new "Resist Fingerprinting" feature enabled, all calls to Date.now() and performance.now() are throttled to 100ms (ie. 10FPS for a real time application). I don't know if requestAnimationFrame is concerned too, but that's a possibility. 

Obviously this can have huge performance impact...

I don't think anything can be done about this, but this is something to be aware of.

**Comment by embeddedt** [comment]
> Obviously this can have huge performance impact...

I'm not sure if describing it as a "performance impact" is the right way to consider it.

From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now#Reduced_time_precision):

> To offer protection against timing attacks and fingerprinting, the precision of `Date.now()` might get rounded depending on browser settings.

This says nothing about how fast the function executes; only how the value returned by it will be rounded. 

What I think this means is that if you called it many times in rapid succession, you would get the same value for that 100 millisecond period. That would only be a real issue in an application that needs to wait until a specified period has elapsed.

>  I don't know if requestAnimationFrame is concerned too, but that's a possibility.

It's unlikely, in my opinion. If `requestAnimationFrame` were to be throttled, it would be very obvious to the user, as that method is supposed to be used for displaying animations (which cannot afford to be delayed 100ms).

**Comment by gabrielcuvillier** [comment]
Yes, you are right. In fact, the game on which I observed the problem is using the "gettimeofday" C function to "sync" the time progress in the whole game (physics, FPS, etc...). As it is implemented with Date.now(), this do have a big performance impact in the end ;)

**Comment by embeddedt** [comment]
@gabrielcuvillier I see. That would make sense given the information I've read.


One solution might be to hack the game to use `requestAnimationFrame` instead (since you can [find out how much time has passed since the last call](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#Parameters)).

**Comment by gabrielcuvillier** [comment]
Ok thanks, I'd take a look at that solution
