### ISSUE TITLE
Possible bug: glBufferSubData with size of 0 produces out-of-bounds error in WebGL 2.0

### ISSUE THREAD

**Issue by JacksonAllan** [emscripten-core/emscripten#9370]
The following code, which attempts to copy zero bytes from an array called CPUBuffer to the GPU-side buffer currently bound, produces no errors when compiling for WebGL 1.0:

glBufferSubData( GL_ARRAY_BUFFER, 0, 0, CPUBuffer );

However, once the USE_WEBGL2=1 flag is added, the code produces this error in Firefox (I have not tested in Chrome):
Error: WebGL warning: bufferSubData: Offset+size passes the end of the buffer.

This might be occurring because the WebGL 2.0 specs, unlike the WebGL 1.0 specs, allow a length (i.e. the amount of data to copy) to be passed into bufferSubData, and if that length is 0, then the length is deduced from the size of the source data array. If Emscripten is simply passing the value of 0 into the WebGL 2.0 version of bufferSubData, then rather than 0 bytes being copied, the entire source data array is copied.

The application-level solution is to check to make sure there is actually data that needs copying before using the function. However, it would be nice if Emscripten worked in accordance with the OpenGL ES 2.0/3.0 specs here (https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glBufferSubData.xhtml) and were consistent across both the WebGL 1.0 and WebGL 2.0 implementations.

**Comment by kainino0x** [comment]
@JacksonAllan Thanks for the report! Is there any chance you could look into this a little more - e.g. test on Chromium just to make sure it's probably an Emscripten bug?

The likely location of the bug is right here:
https://github.com/emscripten-core/emscripten/blob/7e21c7e/src/library_gl.js#L1785
which is very simple code. Would you be able to experiment with it and propose a fix?

**Comment by JacksonAllan** [comment]
Hi kainino0x,

I tested in Chrome and it produces the same error albeit phrased slightly differently.

As for the solution, bear in mind that I’m no expert in OpenGL, JavaScript, or the internal workings of Emscripten. But to reiterate, the issue here is that passing a value of 0 for size into glSubBuffer causes overflow warnings, and this isn’t in accordance with OpenGL ES 2.0/3.0 specs, which are silent about what happens if size is 0 (intuitively, we would expect the function to do nothing). The issue occurs because in the WebGL 2.0 specs, size being 0 means that WebGL deduces the size of the data to copy from the size of the source buffer, which is possible in JavaScript but not C. The issue also only occurs in WebGL 2.0 because in WebGL 1.0 the programmer cannot manually specify the size of the data to copy, so the conversion of the ES function to the WebGL function is handled differently.

Hence, the simple solution would be to check and abort if size is 0, either for both WebGL 1.0 and 2.0 or just the latter, e.g.:

`  glBufferSubData: function(target, offset, size, data) {
#if USE_WEBGL2
    if (GL.currentContext.supportsWebGL2EntryPoints) { // WebGL 2 provides new garbage-free entry points to call to WebGL. Use those always when possible.
      **if( !size ) // Prevent WebGL from trying to copy all of HEAPU8 if size is 0 
          return;**      

      GLctx.bufferSubData(target, offset, HEAPU8, data, size);
      return;
    }
#endif
    GLctx.bufferSubData(target, offset, HEAPU8.subarray(data, data+size));
  },`

Of course, this would mean that the GLctx.bufferSubData never gets called, and I’m not sure what side effects, if any, that could have (presumably none).

Note that this issue isn't critical at the moment as the error does not interrupt program. The function call simply fails, assuming that HEAPU8 is smaller than the target buffer.

**Comment by kainino0x** [comment]
I think it would still be ideal if we could fix this. It would make Emscripten's OpenGL implementation closer to conformant.

Unfortunately it still won't be quite conformant - skipping the bufferSubData call skips other validation that occurs in the browser's implementation of bufferSubData. But that's less of a problem.
