### ISSUE TITLE
Memory spike on startup (PHP in browser)

### ISSUE THREAD

**Issue by nikolayemrikh** [emscripten-core/emscripten#9376]
Hello, we're using https://github.com/oraoto/pib to bring PHP into the browser and it works fine, except a huge memory spike on startup (up to 3GB of memory, then lowers to 300MB). We're compiling it with emcc with following parameters: https://github.com/oraoto/pib/blob/master/build.sh#L40-L52

I've tried to play with `INITIAL_MEMORY` and `TOTAL_STACK` but it has no effect. Maybe you have any thoughts, let me know

**Comment by kripken** [comment]
An initial memory spike like that might be due to the VM compiling the code. Is the wasm file here quite large?

The compilation flags there seem reasonable, so I don't think there is anything obvious you can do to fix this, you may just be hitting a browser limitation or bug.

Which browser/version is that on?

**Comment by nikolayemrikh** [comment]
.wasm is 4.8 MB

Literally every browser — latest versions of FF, Chromium-based and Safari only Technical Preview (because in current Safari it doesn't work at all, promise returned by WebAssembly.instantiate never fulfilled nor errored — https://github.com/oraoto/pib/issues/30)

**Comment by nikolayemrikh** [comment]
You can try to open https://oraoto.github.io/pib/ page and see memory spike

**Comment by kripken** [comment]
Thanks for the link! Yeah, I also see a spike in chrome on startup there.

Inspecting the wasm, it has 2 massive functions, 381K and 231K. Those are probably the cause of this. Are those perhaps interpreter loops, or machine-generated code? If there's a way to build PHP with those being smaller, that might help, like disabling inlining on those functions.

**Comment by nikolayemrikh** [comment]
Do setting [`INLINING_LIMIT`](https://github.com/emscripten-core/emscripten/blob/master/src/settings.js#L230) to 50 can help with it?

**Comment by nikolayemrikh** [comment]
I don't see any helpful options to configure btw https://www.php.net/manual/en/configure.about.php

**Comment by nikolayemrikh** [comment]
> 2 massive functions, 381K and 231K
Which functions are you talking about? (names)

**Comment by kripken** [comment]
I couldn't tell their names as the binary doesn't have names in it - if you rebuild with `--profiling` then we can find them (either send me the binary, or use the `bloaty` tool which now has wasm support).

**Comment by nikolayemrikh** [comment]
If we will find those functions, could we do something to resolve the problem?

**Comment by nikolayemrikh** [comment]
compiled with next options:
```
emcc -O3 \
  --profiling \
  --llvm-lto 2 \
  -g4 \
  -s ENVIRONMENT=worker \
  -s EXPORTED_FUNCTIONS='["_pib_eval", "_php_embed_init", "_zend_eval_string", "_php_embed_shutdown"]' \
  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall"]' \
  -s MODULARIZE=1 \
  -s EXPORT_NAME="'PHP'" \
  -s TOTAL_MEMORY=134217728 \
  -s ASSERTIONS=0 \
  -s INVOKE_RUN=0 \
  -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
  libs/libphp7.a pib_eval.o -o out/php.html
```

bloaty gave next result:

```
# /bloaty/bloaty -d symbols ./php.wasm
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  55.9%  3.82Mi   NAN%       0    [4964 Others]
  25.8%  1.76Mi   NAN%       0    [section Data]
   6.1%   428Ki   NAN%       0    _scan
   3.9%   269Ki   NAN%       0    _match
   1.2%  83.9Ki   NAN%       0    _lex_scan
   1.1%  76.4Ki   NAN%       0    _zendparse
   0.7%  48.8Ki   NAN%       0    _zend_ast_export_ex
   0.7%  45.9Ki   NAN%       0    _ini_lex
   0.6%  44.0Ki   NAN%       0    _compare_opcodes
   0.6%  40.5Ki   NAN%       0    _php_request_shutdown
   0.5%  32.5Ki   NAN%       0    _parse_regex
   0.4%  30.7Ki   NAN%       0    _compile_regex
   0.3%  23.8Ki   NAN%       0    _mbfl_filt_conv_wchar_sjis_mac
   0.3%  22.8Ki   NAN%       0    _php_stream_url_wrap_http_ex
   0.3%  21.9Ki   NAN%       0    _zif_extract
   0.3%  21.6Ki   NAN%       0    _php_json_scan
   0.3%  19.5Ki   NAN%       0    _BF_crypt
   0.3%  18.8Ki   NAN%       0    _php_module_startup
   0.2%  17.4Ki   NAN%       0    _zm_startup_date
   0.2%  17.1Ki   NAN%       0    _timelib_parse_from_format_with_map
   0.2%  16.9Ki   NAN%       0    _zif_metaphone
 100.0%  6.84Mi 100.0%       0    TOTAL
```

**Comment by nikolayemrikh** [comment]
https://github.com/oraoto/pib/issues/31

With this flag (`chromium --js-flags="--no-wasm-tier-up"`) there're no memory spike...

**Comment by nikolayemrikh** [comment]
Memory spike decreased down to 2GB when i compiled .wasm with `1.38.31` version

**Comment by kripken** [comment]
Now that you know which functions those are (scan and match), perhaps you can work around this in the source. Perhaps using `__attribute__((noinline))` to prevent functions being inlined into those two, for example. Or perhaps the functions are machine-generated, and can be generated as a set of smaller functions?

Doing some more testing, this doesn't seem to be a browser bug, I see around 3GB spikes in Chrome and Firefox.

**Comment by nikolayemrikh** [comment]
Compiling with option `OUTLINING_LIMIT=400` with sdk version `1.38.31` gave next result:
```
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  71.5%  6.11Mi   NAN%       0    [8168 Others]
  20.6%  1.76Mi   NAN%       0    [section Data]
   0.9%  75.4Ki   NAN%       0    func[8178]
   0.8%  72.4Ki   NAN%       0    func[8177]
   0.7%  58.6Ki   NAN%       0    func[7095]
   0.6%  56.1Ki   NAN%       0    func[6044]
   0.5%  43.8Ki   NAN%       0    func[5124]
   0.4%  38.0Ki   NAN%       0    func[3385]
   0.4%  37.8Ki   NAN%       0    func[6748]
   0.4%  36.8Ki   NAN%       0    func[4259]
   0.3%  28.1Ki   NAN%       0    func[1384]
   0.3%  27.8Ki   NAN%       0    func[7852]
   0.3%  26.3Ki   NAN%       0    func[6653]
   0.3%  26.1Ki   NAN%       0    func[5991]
   0.3%  26.0Ki   NAN%       0    func[5815]
   0.3%  25.1Ki   NAN%       0    func[7637]
   0.3%  25.0Ki   NAN%       0    func[2507]
   0.3%  24.3Ki   NAN%       0    func[8071]
   0.3%  23.3Ki   NAN%       0    func[7417]
   0.3%  23.0Ki   NAN%       0    func[1611]
   0.2%  21.0Ki   NAN%       0    func[7963]
 100.0%  8.55Mi 100.0%       0    TOTAL
```

Memory spike lowered a bit, but not that much to stop research
