### ISSUE TITLE
WASM=0 + SINGLE_FILE=1 not a stand-alone file

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#9380]
Hi,

I'm trying to make zee.js https://github.com/kripken/zee.js work with the "upstream" branch.

This project is compiled so it can be loaded synchronously on start-up, possibly to load other compressed files such as index.wasm.gz with a custom loader.

```
EMCC=emcc -O2 -s WASM=0 -s SINGLE_FILE=1 -s EXPORTED_FUNCTIONS="['_gzopen', '_gzread', '_gzwrite', '_gzclose']" --pre-js pre.js --post-js post.js
```

zee.js now raises:
```
uncaught exception: could not load memory initializer http://localhost:8000/libz.raw.js.mem
```
```
Error: ENOENT: no such file or directory, open '.../zee.js/libz.raw.js.mem'
```

Is SINGLE_FILE support incomplete in "upstream"?

**Comment by sbc100** [comment]
No its more likely due to the fact that upstream + WASM=0 (i.e. wasm2js) is fairly new still and probably hasn't been tested with SINGLE_FILE.

What is you reason for needed WASM=0 here?

**Comment by sbc100** [comment]
Oh I see you are using WASM=0 to allow for the synchronous startup.   Is the wasm file to large for WASM_ASYNC_COMPILATION=0?

**Comment by Beuc** [comment]
Yes, I get 188kB so far above Chromium's 4kB limit :/

**Comment by sbc100** [comment]
I think we can fix this bug.. however I don't think wasm2js is intended as way to work around wasm synchronous compilation limits (I could be wrong).   Ideally you probably want to re-factor your code to allow for asynchronous compilation.   I understand this can sometimes be tricky.. but it is probably work that is worth doing.

**Comment by Beuc** [comment]
I'm not even sure such a re-factoring is possible TBH, short of patching Emscripten / Emscripten's boilerplate - the context is loading a compressed main.wasm.gz (on a CDN where HTTP compression can't be configured). I currently have to work within Module.instantiateWasm, it's tricky enough as it is.
(now if Emscripten provides fallback JS compression natively, I'm all ears ;))

**Comment by sbc100** [comment]
Can't you do it like this?:

1. Async fetch the decompressor
2. Async fetch main.wasm.gz
3. Run decompress on main.wasm.gz to create blobURL (or just arraybuffer)
4. Async instantiate main.wasm from the blob url / arraybuffer?

Where does the requirement for synchronous instantiate come from?   Is it hard to override the emscripten URL with the blob URL from (3)?

**Comment by Beuc** [comment]
Well I already have this much rewrite:
https://github.com/renpy/renpyweb/blob/2094ec0866401bbe6bdbf0e0a52b6216692354cc/renpy-pre.js#L26
(note that I also handle properly-configured web servers with compression and proper content-type)
I find the init process particularly tricky.

Maybe I overlooked a trivial fix, but if I can save some sanity by being able to generate a synchronous zee.js, that would be nice.

That's only one example, I'm pretty sure other users of zee.js would appreciate running it like they currently do.

**Comment by sbc100** [comment]
I'm not aware of zee.js or its users.  I'll try to find time to take look at this use case.  Hopefully we can find a way to avoid needing to use wasm2js on platforms that have wasm, but obviously people are free to do as they please.

**Comment by Beuc** [comment]
You can ask @kripken as zee.js is his project :)

**Comment by kripken** [comment]
Ah, looks like the relevant test was disabled, so this was missed, sorry...

Fix in #9407!

**Comment by buu700** [comment]
Awesome, thanks @kripken! I was just about to submit a report for this issue as well.

**Comment by Beuc** [comment]
On a related note, it seems that:
`-s WASM=1 -s SINGLE_FILE=1`
works in Chrome, even with code > 4kB.

Was I just repeatedly lucky, or is this really synchronous?

**Comment by kripken** [comment]
No, see other issue - SINGLE file doesn't mean synchronous. The extra `WASM_ASYNC_COMPILATION=0` flag must be used for that (and it won't work in chrome for large files, sadly, yeah...).

**Comment by Beuc** [comment]
Thanks for clarifying.

(Maybe there's some ordering constraint that made my custom (async) wasm.gz loader always run after zee's.)
