### ISSUE TITLE
Use openssl get dlopen abort

### ISSUE THREAD

**Issue by jishuo1213** [emscripten-core/emscripten#9386]
Hi,
I complie openssl1.1.1c to do some encrypt and decrypt in browser.Here is my build script.
`emconfigure ./Configure linux-x32 -no-asm -no-threads`
`sed -i 's|^CROSS_COMPILE.*$|CROSS_COMPILE=|g' Makefile`
`emmake make -j 12 build_generated libssl.a libcrypto.a apps/openssl`
And i got two bitcode file  `libcrypto.so` and `libssl.so`,then i use it in my own code.
Here is my CMkaeLists.txt:

`include_directories("${OPENSSL_ROOT}/build/include")`
`link_directories("${OPENSSL_ROOT}/lib")`
`set(CMAKE_C_FLAGS "--pre-js pre.js -s WASM=1  -s EXTRA_EXPORTED_RUNTIME_METHODS='[\"cwrap\",\"getValue\",\"setValue\"]'")`
`SET(CMAKE_EXECUTABLE_SUFFIX ".html")`
`add_executable(SM2FinalNew main.c ${DIR_SRCS})`
`target_link_libraries(SM2FinalNew crypto)`
 

When i use sha256 base64 ,everything is ok,but when i use some method to achieve sm2 encrypt and decrypt,i got error on the web page.
`SM2FinalNew.html:98 To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking`
I found when i call `EC_POINT_mul` method, the error apper,when i comment the call，the error disapper,but the encrypt result is incorrect.
I don't know why.

**Comment by jishuo1213** [comment]
I found that when i build openssl with option no-engine and no-dso ,the error disapper,I don't konw why.I think in openssl somewhere ,it call dlopen function.

**Comment by wuchu** [comment]
@jishuo1213 so how to deal with it?

**Comment by jishuo1213** [comment]
> @jishuo1213 so how to deal with it?

you mean deal with what,I changed the build option,add --no-engine and --no-dso
