### ISSUE TITLE
-s ALLOW_MEMORY_GROWTH=1 gets ignored

### ISSUE THREAD

**Issue by DerRM** [emscripten-core/emscripten#9388]
Hi,

I'm using
`emcc (Emscripten gcc/clang-like replacement) 1.38.42 (commit ef0699a936acdc3722625468c7b4cd8b09232dab)
` 
and I can't seem to get `-s ALLOW_MEMORY_GROWTH=1` to work properly. I always get the error `failure to dynamicAlloc - memory growth etc. is not supported there, call malloc/sbrk directly`
I tried to repro this issue with the code and command line in #8637 and it doesn't seem to work with this simple case either. Any help is appreciated.

Best regards
DerRM

**Comment by kripken** [comment]
I think that error can show up when allocation happens before the program starts (like for preloading files). The stack trace for the error would confirm it.

If that's it, then increasing initial memory would be necessary (we can't grow memory until the program fully starts).

**Comment by DerRM** [comment]
My problem is that we have an engine which uses different assets and it's also possible to switch between assets. I also used 1.38.18 before where this didn't seem to be a problem and `-s ALLOW_MEMORY_GROWTH=1` did work for arbitrary sized assets.
What would be your suggestion? How would I call malloc/sbrk? In JS?

**Comment by kripken** [comment]
A safer option is to load the file package after the main program is running. You can use an EM_ASM to loda the script tag, for example.
