### ISSUE TITLE
asyncify: identify functions missing from whitelist

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#9389]
Hi,

As discussed at https://github.com/emscripten-core/emscripten/issues/9257#issuecomment-525043658 and confirmed at [emscripten-discuss](https://groups.google.com/d/msg/emscripten-discuss/YWdLNgCqIjk/eJNJ5TFcAAAJ) it would be useful to identify what function is missing from ASYNCIFY_WHITELIST, in a manner similar to what Emterpreter does (full stack trace when sleeping or resuming inappropriately).
Opening an issue as requested.

This is particularly useful in complex code with indirect calls :)

**Comment by Beuc** [comment]
In addition, formatting the function names appears to be error-prone ([discussion](https://groups.google.com/d/msg/emscripten-discuss/YWdLNgCqIjk/A-Ad47tZAAAJ) recommends grepping the wasm disassembly) so it would save time to provide function names in a format recognized by ASYNCIFY_WHITELIST, if possible :)

**Comment by gabrielcuvillier** [comment]
I agree with this. The current approach I am using is to use Emterpreter first to find out the functions to whitelist at runtime, demangle them, then switch back to ASYNCIFY...
