### ISSUE TITLE
how build glog in windows?

### ISSUE THREAD

**Issue by 2qif49lt** [emscripten-core/emscripten#9390]
Hello all!
I have reading
 [https://developer.mozilla.org/en-US/docs/WebAssembly/existing_C_to_wasm](existing_C_to_wasm)
[https://emscripten.org/docs/compiling/Building-Projects.html](Building-Project)
[https://emscripten.org/docs/tools_reference/emcc.html#command-line-syntax](emcc.html#command-line-syntax)

but when i want build glog to .o , meet lots problems. 
is there any example demonstrate how to do with  a little bit more complicated open source project?

my command:
```
F:\GitHub\glog>emcc -D_WIN32 -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" -I src/windows -I src/windows/glog src/logging.cc src/demangle.cc src/raw_logging.cc src/signalhandler.cc src/symbolize.cc src/utilities.cc src/vlog_is_on.cc -c
```
caution,thousands error:
```
src/base/mutex.h:129:11: warning: non-portable path to file '<Windows.h>'; 
minwinbase.h:47:5: error: unknown type name 'DWORD';
vadefs.h:133:18: error:
      expected identifier or '{'
            enum : bool { __the_value = false };
                      ^
vcruntime.h:83:1: error:
      C++ requires a type specifier for all declarations
_CRT_BEGIN_C_HEADER
^
vcruntime.h:215:22: error:
      'short wchar_t' is invalid
    typedef unsigned short wchar_t;

```

 Thanks in advance.

**Comment by sbc100** [comment]
I should not be defining _WIN32 or including windows headers when using emcc.

emcc is cross compiler that targets the web, it can't compile OS-specific code such as code designed for windows.
