### ISSUE TITLE
Error: "toString()" failed

### ISSUE THREAD

**Issue by scotbenn** [emscripten-core/emscripten#9392]
Hello,

I'm using Emscripten 1.38.42 and trying to build for debugging in Firefox.

While compiling with -g4 -s WASM-0 --source-map-base <my url and port> I get the following error:

buffer.js:565
      if (encoding === 'utf-8') return buf.utf8Slice(start, end);
                                           ^

Error: "toString()" failed
    at stringSlice (buffer.js:565:44)
    at Buffer.toString (buffer.js:631:10)
    at Object.fs.readFileSync (fs.js:601:41)
    at Object.<anonymous> (/local/emsdk/fastcomp/emscripten/tools/source-maps/sourcemapper.js:186:47)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
shared:ERROR: '/local/emsdk/node/8.9.1_64bit/bin/node /local/emsdk/fastcomp/emscripten/tools/source-maps/sourcemapper.js /tmp/emscripten_temp_d20Jds/wasmnotes.bc.o.js.pp.js.mem.js --sourceRoot /home/scotbenn/git/notes/main/wasm --mapFileBaseName /home/scotbenn/git/notes/bin/wasm/bin/wasmnotes.html --offset 0' failed (1)

I enabled EMCC_DEBUG=1 and attached the output from the build, which includes the error above.

I'm not sure what else you need from us, so please let me know. We are so close to running in WASM! We just need to debug a few things, thank you :-)

[buffer.js.error.txt](https://github.com/emscripten-core/emscripten/files/3579160/buffer.js.error.txt)

**Comment by kripken** [comment]
This might be a bug in the asm.js source maps support, which I don't think anyone is actively working on, so no one might know how to easily fix this.

The more recent source maps support in the the new upstream backend might work for you though, so trying that might help, https://v8.dev/blog/emscripten-llvm-wasm#testing
