### ISSUE TITLE
Info about Asyncify on Emterpreter Wiki Needs Update

### ISSUE THREAD

**Issue by hostilefork** [emscripten-core/emscripten#9405]
There is a section on the emterpreter wiki page called [**"Comparison to Asyncify**](https://github.com/emscripten-core/emscripten/wiki/Emterpreter#comparison-to-asyncify) *(which seems to be the source material for the [emterpreter documentation page](https://emscripten.org/docs/porting/emterpreter.html))*.  Among the things it says is:

> *"As the emterpreter is useful for other things than synchronous code, it will likely continue to be worked on, while the ASYNCIFY option currently does not have activity."*

This contradicts current statements in the ["Future of Emterpreter/Asyncify"](https://github.com/emscripten-core/emscripten/issues/8561) ticket...or what I [read on the mailing list](https://groups.google.com/d/msg/emscripten-discuss/TmQuXXSJEnw/qgY8KVZBAwAJ):  *"Asyncify is meant to do everything that Emterpreter (and old Asyncify) used to do. But more efficiently."*

*(Note: In the code I'm working with, Asyncify seems to be 7x-8x faster than the Emterpreter--which is great!  Though the download is about twice the size, so about 100% bigger.  Though when the files are compressed, the difference becomes less significant.)*

The [corresponding page on Asyncify](https://emscripten.org/docs/porting/asyncify.html) talks about the "new asyncify".  It seems perhaps the "Comparison to Asyncify" section on the emterpreter page could be taken out entirely, with a note at the very top bringing people up to date on the pending reversal and pointing them to the new asyncify information.

**Comment by kripken** [comment]
Thanks @hostilefork! Yeah, that was badly out of date, I removed the section now. (And we can remove the entire emterpreter docs eventually once fastcomp is deprecated and removed, but that's far off.)

Good to hear Asyncify is fast on your codebase! And yeah, the code size difference makes sense - emterpreter bytecode is very compact, that was the one big benefit that is impossible to match (not without also being very slow...).

**Comment by hostilefork** [comment]
> (And we can remove the entire emterpreter docs eventually once fastcomp is deprecated and removed, but that's far off.)

It was nontrivial to understand the various aspects involved in the Emterpreter.  I was a bit glum in a way to delete the code for processing and downloading the bytecode--it was a bit of a Herculean effort to do browser detection etc. and handle the process (not done by me, but [by Giulio](https://github.com/giuliolunati))

So once you invest in something, you can be torn on whether to keep it as a separate build option or not.  But doing a 3-way build: Pthreads, Asyncify, Emterpreter... ?

Emterpreter was a valiant effort and concept, and it may still fit some scenarios.  But I think perhaps, killing it off entirely is the right answer.  e.g. drop the whole thing and turn it into a different project and see who cares, and let them be the ones to maintain it.  There's enough going on here.  Do not have any Emterpreter in the next release, period: spin it off.  Look ahead, not backward.

**Comment by kripken** [comment]
The main problem is that the Emterpreter feature is specific to fastcomp, and we we deprecated fastcomp.

If someone were interested to do something similar in the new backend, that would be welcome of course!
