### ISSUE TITLE
Remove Binaryen from ports?

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9409]
Binaryen uses ports to fetch itself when it isn't already set up. In practice, the emsdk sets it up, and developers also tend to set it up as well. And we have not been keeping the port up to date - it's broken (far too old) atm, and has been for a while. So perhaps we should just remove it?

Overall I think we agreed that using ports to build something like binaryen was a hack. It was useful in early days, but now we treat binaryen just like LLVM in the emsdk and elsewhere.

**Comment by jgravelle-google** [comment]
+1 to just remove it and require BINARYEN_ROOT to be set in .emscripten. We treat it like LLVM (and use it similarly too) so it makes sense. The only people this should affect are people who fetch emscripten+LLVM from source, but not binaryen. I can't imagine that's popular.

**Comment by brion** [comment]
I think this would make it clearer how to use a custom binaryen install as well, such as when testing changes to it. :)
