### ISSUE TITLE
MAIN_THREAD_EM_ASM in wasm backend

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9410]
See https://groups.google.com/d/msg/emscripten-discuss/5jcPS41at9M/9vA2abaCCQAJ

Perhaps we can use some macro magic to do this? Alternatively, perhaps we can design something more like EM_JS that is better?

**Comment by jgravelle-google** [comment]
Looking briefly at how this is done in fastcomp, it shouldn't be too impossible to just implement. What we'd need to do is just recognize the "_sync/_async_on_main_thread" suffix, and add the relevant sync/async/none (https://github.com/emscripten-core/emscripten-fastcomp/blob/7338ca5770a6118cefd98cce3e733dfff894c1da/lib/Target/JSBackend/JSBackend.cpp#L4134) to the metadata we emit from emscripten-finalize and IIRC it'll just work? Unless there's more plumbing after that fact that we don't have. I'll give it a shot I think.

**Comment by jgravelle-google** [comment]
Okay, looking at this some more it is indeed, pretty trivial to support this in binaryen: https://github.com/WebAssembly/binaryen/commit/5a8f0deb568fd145c796f53849723257868d94e1#diff-8cf6999a742cd6a8d9594c858eddc917R775

However, the emscripten side of it: https://github.com/emscripten-core/emscripten/commit/127fc123e535cc997f257e51956cf300c4f86292
We need to merge/unify/reimplement the two fastcomp em_asm glue generators ([`include_asm_consts`](https://github.com/emscripten-core/emscripten/blob/127fc123e535cc997f257e51956cf300c4f86292/emscripten.py#L938) and [`all_asm_consts`](https://github.com/emscripten-core/emscripten/blob/127fc123e535cc997f257e51956cf300c4f86292/emscripten.py#L1017)) with the wasm backend's version ([`create_asm_consts_wasm`](https://github.com/emscripten-core/emscripten/blob/127fc123e535cc997f257e51956cf300c4f86292/emscripten.py#L2329)). That looks much more nontrivial.

So, those are my initial findings.
