### ISSUE TITLE
Using Buildroot for building JS/WASM sysroots?

### ISSUE THREAD

**Issue by jakogut** [emscripten-core/emscripten#9414]
JavaScript and WebAssembly are new compilation targets that require recompiling not only an application, but also all of its dependencies. Applications and libraries can require several third party libraries such as OpenCV, which can be configured to use SDL2, FFmpeg, GTK, Gstreamer, libjpeg, libwebp, libpng, zlib, pthreads, etc. Many of these libraries compile and install without modification, and some have ports available for use with a flag. Additionally, there's been some discussion here around changing the way that libraries are built and used to a more traditional sysroot type arrangement. https://github.com/emscripten-core/emscripten/issues/9353

Managing and building all of these dependencies can be a laborious process, and is arguably out of the scope of what Emscripten should be expected to do.

However, there are projects such as Buildroot that are developed and intended to build a complete system from source, starting with the cross-compilation toolchain, ending with a sysroot complete with the user's selected applications and their dependencies.

As a Buildroot contributor myself, I'm curious about the possibilities and benefits of adding JS/WASM as a compilation target to Buildroot. This could allow developers to simply run `make menuconfig`, pick `JS ` or `WASM` as a compilation target, choose toolchain options such as upstream LLVM with the WASM backend or fastcomp, choose target packages to build, such as FFmpeg, OpenCV, Python, SQlite, etc., and build a sysroot with headers and WASM blobs they could use to link their final application.

Additionally, users could clone Buildroot and use a known working defconfig to get a reproducible WASM blob of a library or application they're interested in, just by running `make`. I think this has interesting implications for ease of use, as well as testing.

I've had this idea for a while, but it's very much a non-trivial task. Fortunately, LLVM and Clang were added as packages late last year, and patches were submitted a couple of days ago to use Clang as the system's cross-compiler. http://patchwork.ozlabs.org/project/buildroot/list/?series=129565

At this point, adding support for Emscripten should be a matter of adding Emscripten as a package, making it a dependency of the toolchain build process, and configuring the build to use the right tools.

Thoughts?

**Comment by sbc100** [comment]
This is an exciting idea and I think it is possible.    One road block you may have is that emscripten today is kind of a hybrid toolchain so it requires not just llvm/clang but also python and node and java and bunch of other stuff.

It also doesn't honor --sysroot in the normal way yet.  I'm hoping #9353 will at least partially address that.

As a first step have you considered targeting wasi first.  https://github.com/CraneStation/wasi-sdk.  This is a much smaller (and much less useful today) SDK that is based purely on llvm/clang.  If you target wasi then by the time you are done with that we might have fixed #9353 which would make your work easier.

**Comment by jakogut** [comment]
> This is an exciting idea and I think it is possible. One road block you may have is that emscripten today is kind of a hybrid toolchain so it requires not just llvm/clang but also python and node and java and bunch of other stuff.

Other host tools aren't really a problem, as Buildroot builds the entire toolchain from source, and those packages can be added as host dependencies for Emscripten.

> It also doesn't honor --sysroot in the normal way yet. I'm hoping #9353 will at least partially address that.

Sysroots are definitely an area that needs figured out, but I see it as somewhat of a chicken and egg problem right now. We don't have a way of using sysroots, but we also don't have a way of making them, so what good would heeding a sysroot option do at this point? Buildroot could help solve the problem of making sysroots.

> As a first step have you considered targeting wasi first. https://github.com/CraneStation/wasi-sdk. This is a much smaller (and much less useful today) SDK that is based purely on llvm/clang. If you target wasi then by the time you are done with that we might have fixed #9353 which would make your work easier.

What are the limitations of WASI compared to Emscripten? I assume it could compile most anything that links only to a libc, such as zlib?

**Comment by sbc100** [comment]
Regarding emscripten support for sysroot I was really talking about supporting `emcc --sysroot=xxx`.   Right now I don't think that works as expected, and moving to default sysroot internally will mean building fully featured external sysroots will be a simple case of running with `emcc --sysroot=some_other_sysroot`.

wasi is more about non-web embeddings and has a different syscall internface.  So it should only really be code that makes syscalls (such as libc) and is fundamentally different between wasi and emscripten.

**Comment by flatmax** [comment]
@jakogut you had any progress with buildroot ?

I started working with this concept, however it isn't working yet.
My concept was to have a buildroot external dir and setup buildroot from there, then build as per usual.

You can see some of the approach here :

https://github.com/flatmax/buildroot.WASM

My setup was to use an external toolchain, check the BR config :

https://github.com/flatmax/buildroot.WASM/blob/master/configs/wasm_defconfig
