### ISSUE TITLE
WebIDL unsupported operators

### ISSUE THREAD

**Issue by ricksterhd123** [emscripten-core/emscripten#9415]
I notice that it says in the WebIDL Binder docs that support is missing for some operators such as `Operator="*"`, `Operator="+"`, `Operator="-"`, etc.
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html

Is there a good reason behind this?
Could support be added?
Where do I start?

**Comment by kripken** [comment]
Help improving that would be great!

The code is in `tools/webidl_binder.py`. I'm not that familiar with it, so I'm not sure if the docs are out of date or not. (if they are, helping update them would be great!) Maybe a good starting point is to check if the functionality works or not, by writing a little testcase, or adding to the existing tests in the test suite (I think it's `test_webidl`, search under `tests/*`. If it does work, we can just add the tests then.
