### ISSUE TITLE
N-API interopability

### ISSUE THREAD

**Issue by maierfelix** [emscripten-core/emscripten#9418]
I need to pass C structs around, created in the N-API and also the Wasm space. Unfortunately the memory of the structs doesn't match at all, it's shifted:

Here is a screenshot comparing both structs:
http://prntscr.com/p4f46q
 - Top is Wasm
 - Bottom is N-API

It's important, that the struct created in Wasm matches the layout of the N-API struct.

Is this because Wasm is limited to 32-bit? How could this be fixed?

**Comment by kripken** [comment]
Wasm is 32-bit currently, yes, so structs are aligned according to that.

There is a future wasm64 planned, but even when it arrives it may not match other ABIs (e.g. it may work on linux64 but not windows64).

In general, you need to convert when crossing such an ABI boundary, I don't think that's avoidable.

**Comment by maierfelix** [comment]
Thanks for the reply! Closing this
