### ISSUE TITLE
SIMD shift instructions compile but fail to run in d8 with "invalid shift amount"

### ISSUE THREAD

**Issue by tangobravo** [emscripten-core/emscripten#9439]
The code below is sufficient to reproduce this bug with the `latest-upstream` toolchain, which now is pulling in `sdk-releases-upstream-737d4a07be76c15124adf3c6ef2c218123f7a67f-64bit`

```
#include <wasm_simd128.h>

int main()
{
    v128_t initial = wasm_i16x8_splat(0x4321);
    v128_t shifted = wasm_i16x8_shr(initial, 8);

    if(wasm_i16x8_extract_lane(shifted, 0) != 0x43) return 1;
    return 0;
}
```

Compile with `-O0` to ensure the instructions actually get emitted. 

```
$ emcc -O0 -msimd128 main.c -o main.js
```

Testing with a build of d8 from the 7.7 branch on my MacBook Pro:
```
$ path/to/v8/out/x64.release/d8 --experimental-wasm-simd main.js
failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #4 failed: invalid shift amount @+477
CompileError: WebAssembly.instantiate(): Compiling function #4 failed: invalid shift amount @+477
CompileError: WebAssembly.instantiate(): Compiling function #4 failed: invalid shift amount @+477
```

The same issue also occurs with optimization enabled for practical uses - see https://github.com/tangobravo/webassembly-halfsample-benchmark for a more complex example that has the same issue with `-O3`.

**Comment by brion** [comment]
Is this d8 current or an older version? Non-immediate shift amounts used to be unimplemented by the chromium SIMD implementation, so there used to be a temporary workaround in LLVM to avoid emitting them. This workaround was removed in LLVM some weeks ago after chromium's implementation was fixed. I'm not sure exactly which commit in chromium updated it offhand, but it should be findable in source control.

**Comment by tangobravo** [comment]
I cloned the latest stable 7.7 release branch of v8; looks like the release was mid-August. I'll try with a newer build too.

However saying that it seems the shift here should be an immediate anyway? I'm just shifting 16-bit elements right by 8 bits (the 8 is a literal in the example code above).

**Comment by tangobravo** [comment]
The latest d8 master is able to run the compiled code (both this toy example and the real-world half sampling one).

I've looked at the [latest wasm SIMD](https://github.com/WebAssembly/simd/blob/master/proposals/simd/BinarySIMD.md) spec and it seems the shift instructions don't have immediate operands. Adding -S on the command line for compiling the half sample code shows the shifts like this, which I suppose is as expected if there are no immediate encodings.
```
local.get	7
i32.const	8
i32.shr_u
```

I'll close this issue as it seems emscripten is doing the right thing here. Thanks for the help!

**Comment by brion** [comment]
Sorry I meant 'constant' rather than 'immediate'. But in that case it ought to have worked I think... Anyway glad it's working now! Beware in general that the SIMD stuff remains in flux, with new instructions still going in, so staying in sync between compiler and runtime is tough. :(

**Comment by tangobravo** [comment]
Thanks for the pointer and the warning!

I was benchmarking an idea I had to do some uint8_t operations in parallel by packing elements into an uint64_t and adding appropriate masking / clamping / fixup operations. Was just keen to get a wasm simd128 implementation too for comparison. It's in the half-sample-benchmark repo linked above if you're interested.

With x86-64 d8 on my MacBook Pro, I get about a 2x speedup from my packed uint64 implementation, and a 5x speedup from simd128, vs the plain C implementation. On mobile the packed one gets an even bigger speedup (...and the SIMD one crashes Chrome Canary :( - v8 bug incoming about that).

So it looks like SIMD will be a big help, but there are certainly a few hotspots in my code that look like they'd also benefit from some packed uint64 implementations until the SIMD stuff is stable and available by default.
