### ISSUE TITLE
Improve syntax for -s list arguments on the command line

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#9460]
Right now we have an overly general and overly fiddly syntax for specifying lists on the command line:

```
emcc hello.c -s EXPORTED_FUNCTIONS="['foo', 'bar']"
```

I have been toying with a new, stricter, faster, simpler syntax: https://github.com/emscripten-core/emscripten/compare/s_parsing_strict

**Comment by kripken** [comment]
I think this almost works now? We support e.g.
```bash
./emcc tests/hello_world.c -s EXPORTED_FUNCTIONS=[_main,_malloc]
```
