### ISSUE TITLE
Support for BigInt

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#9462]
We don't currently have easy support for the [JS BigInt ](https://github.com/WebAssembly/JS-BigInt-integration) proposal.

Currently the legalize-js-ffi Binaryen pass converts all i64 imports/exports to use a pair of i32s. In principle we could have a way to disable that behavior, which might be enough for testing out. We'd also want to consider how it would affect embind and dynamic libraries.

**Comment by VirtualTim** [comment]
I think this would depend on HEAP64/HEAPU64 support, right? I opened a bug for that a few months ago (#8925).

**Comment by littledan** [comment]
I guess this is closed by https://github.com/emscripten-core/emscripten/pull/10860 , right?

**Comment by kripken** [comment]
Yes, thanks @littledan !
