### ISSUE TITLE
Using emcc for general purpose pre-processing

### ISSUE THREAD

**Issue by andrewleech** [emscripten-core/emscripten#9466]
We're using emscripten to create a javascript port of [micropython] (https://github.com/micropython/micropython/tree/master/ports/javascript) which is working really well. 

As part of the micropython build process, the entire source tree (*.c and *config.h) is pre-processed (currently with gcc / clang) into one file which is then parsed to find and consolidate all strings; these are then stored efficiently and referenced differently during runtime.

For the emscripten builds, it would be better if we could use `emcc -E` instead of `clang -E` to deal with include/paths automatically, however it currently fails with the error
```
Traceback (most recent call last):
  File "/emsdk_portable/emscripten/tag-1.38.43/emcc.py", line 3556, in <module>
    sys.exit(run(sys.argv))
  File "/emsdk_portable/emscripten/tag-1.38.43/emcc.py", line 1774, in run
    assert header.endswith(HEADER_ENDINGS), 'if you have one header input, we assume you want to precompile headers, and cannot have source files or other inputs as well: ' + str(headers) + ' : ' + header
AssertionError: if you have one header input, we assume you want to precompile headers, and cannot have source files or other inputs as well
```

For reference this is the command `make` is trying to run:
```
GEN build/genhdr/qstr.i.last
emcc -E -DNO_QSTR -Ibuild/tmp -m32 -Wall -Werror -I. -I../.. -Ibuild -std=c99  \
-O0 -DNDEBUG -fdata-sections -ffunction-sections ../../py/mpstate.c ../../py/malloc.c \
../../py/gc.c ../../py/pystack.c ../../py/qstr.c ../../py/vstr.c ../../py/mpprint.c ../../py/unicode.c ../../py/mpz.c ../../py/reader.c ../../py/lexer.c ../../py/parse.c ../../py/scope.c ../../py/compile.c ../../py/emitcommon.c ../../py/emitbc.c ../../py/asmbase.c ../../py/asmx64.c ../../py/emitnx64.c ../../py/asmx86.c ../../py/emitnx86.c ../../py/asmthumb.c ../../py/emitnthumb.c ../../py/emitinlinethumb.c ../../py/asmarm.c ../../py/emitnarm.c ../../py/asmxtensa.c ../../py/emitnxtensa.c ../../py/emitinlinextensa.c ../../py/formatfloat.c ../../py/parsenumbase.c ../../py/parsenum.c ../../py/emitglue.c ../../py/persistentcode.c ../../py/runtime.c ../../py/runtime_utils.c ../../py/scheduler.c ../../py/nativeglue.c ../../py/stackctrl.c ../../py/argcheck.c ../../py/warning.c ../../py/map.c ../../py/obj.c ../../py/objarray.c ../../py/objattrtuple.c ../../py/objbool.c ../../py/objboundmeth.c ../../py/objcell.c ../../py/objclosure.c ../../py/objcomplex.c ../../py/objdeque.c ../../py/objdict.c ../../py/objenumerate.c ../../py/objexcept.c ../../py/objfilter.c ../../py/objfloat.c ../../py/objfun.c ../../py/objgenerator.c ../../py/objgetitemiter.c ../../py/objint.c ../../py/objint_longlong.c ../../py/objint_mpz.c ../../py/objlist.c ../../py/objmap.c ../../py/objmodule.c ../../py/objobject.c ../../py/objpolyiter.c ../../py/objproperty.c ../../py/objnone.c ../../py/objnamedtuple.c ../../py/objrange.c ../../py/objreversed.c ../../py/objset.c ../../py/objsingleton.c ../../py/objslice.c ../../py/objstr.c ../../py/objstrunicode.c ../../py/objstringio.c ../../py/objtuple.c ../../py/objtype.c ../../py/objzip.c ../../py/opmethods.c ../../py/sequence.c ../../py/stream.c ../../py/binary.c ../../py/builtinimport.c ../../py/builtinevex.c ../../py/builtinhelp.c ../../py/modarray.c ../../py/modbuiltins.c ../../py/modcollections.c ../../py/modgc.c ../../py/modio.c ../../py/modmath.c ../../py/modcmath.c ../../py/modmicropython.c ../../py/modstruct.c ../../py/modsys.c ../../py/moduerrno.c ../../py/modthread.c ../../py/vm.c ../../py/bc.c ../../py/showbc.c ../../py/repl.c ../../py/smallint.c ../../py/frozenmod.c ../../extmod/moductypes.c ../../extmod/modujson.c ../../extmod/modure.c ../../extmod/moduzlib.c ../../extmod/moduheapq.c ../../extmod/modutimeq.c ../../extmod/moduhashlib.c ../../extmod/moducryptolib.c ../../extmod/modubinascii.c ../../extmod/virtpin.c ../../extmod/machine_mem.c ../../extmod/machine_pinbase.c ../../extmod/machine_signal.c ../../extmod/machine_pulse.c ../../extmod/machine_i2c.c ../../extmod/machine_spi.c ../../extmod/modussl_axtls.c ../../extmod/modussl_mbedtls.c ../../extmod/modurandom.c ../../extmod/moduselect.c ../../extmod/moduwebsocket.c ../../extmod/modwebrepl.c ../../extmod/modframebuf.c ../../extmod/vfs.c ../../extmod/vfs_reader.c ../../extmod/vfs_posix.c ../../extmod/vfs_posix_file.c ../../extmod/vfs_fat.c ../../extmod/vfs_fat_diskio.c ../../extmod/vfs_fat_file.c ../../extmod/utime_mphal.c ../../extmod/uos_dupterm.c ../../lib/embed/abort_.c ../../lib/utils/printf.c build/genhdr/moduledefs.h main.c mphalport.c modutime.c \
../../py/mpconfig.h mpconfigport.h >build/genhdr/qstr.i.last
```

ps. For an unofficial live demo see https://alelec.gitlab.io/micropython_ci/javascript.html

**Comment by embeddedt** [comment]
Any updates here? The `clang` binary seems to be missing in newer versions of Emscripten so I've had to stick with 1.38.31 for now (seems to be the latest version that `emsdk` lets me download easily).

It would be great if we could move over to using `emcc` instead of having to deal with Emscripten internals directly.

**Comment by sbc100** [comment]
clang still exists in the SDK.   Look in `upstream/bin`

We should fix this issue though.

BTW, you could also work around this by pre-compiling each file one at time and then concatenating them.

**Comment by embeddedt** [comment]
Hmm. I had tried that binary but it was giving me issues about `stdio.h` and other normal C includes not being found. I'll give it another try.

**Comment by sbc100** [comment]
BTW, I'm not sure how get useful output from preprocessing all those files together.   

For example if you have `foo.h` and `bar.h` that both contain simply `#include <stdio.h>` and you do `gcc -E foo.h bar.h > out.c` then the resulting out.c will not be build-able (with `gcc -c foo.c`)  since it will contain all kind of duplicate definitions from stdio.   So the result is not really useful.

I would suggest a more common why of doing what what here would be to create one single source file e.g. big.c that includes all the sources you want.   That way the result is at least likely to be copilable and wont contain all any duplication.

If you don't want to create `big.g` you can instead do `gcc -include foo.c -include bar.c .. etc` to get the same effect.

**Comment by pmp-p** [comment]
@sbc100 
the result is not to be built but to be parsed, for making a pointer array of strings and replacing strings by their index later at build stage 
Thank you a lot for taking the time to solve this.
