### ISSUE TITLE
Add support for noexcept methods and functions to embinds _class.function()

### ISSUE THREAD

**Issue by Veetaha** [emscripten-core/emscripten#9485]
Since `_class<T>::function(...)` depends on `RegisterClassMethod` that doesn't provide template specialization or general implementation that would encompass class methods and free functions with `noexcept` modifier you get the anoying error for the following well-formed code:
```cpp
class Cls { };

void foo(Cls&) noexcept {}

EMSCRIPTEN_BINDINGS(emproj) {
    emscripten::class_<Cls>("Cls").function("fn", &foo);
}
```

```
In file included from ../../src/index.cpp:1:
In file included from ../../src/pch/pch.h:23:
/home/veetaha/apps/emsdk/upstream/emscripten/system/include/emscripten/bind.h:1470:13: error: implicit instantiation of undefined template 'emscripten::internal::RegisterClassMethod<void (*)(Cls &) noexcept>'
            invoker::template invoke<ClassType, Policies...>(methodName, callable);
            ^
../../src/index.cpp:55:10: note: in instantiation of function template specialization 'emscripten::class_<Cls, emscripten::internal::NoBaseClass>::function<emscripten::internal::DeduceArgumentsTag, void (*)(Cls &) noexcept>' requested here
        .function("fn", &foo);
         ^
/home/veetaha/apps/emsdk/upstream/emscripten/system/include/emscripten/bind.h:1202:16: note: template is declared here
        struct RegisterClassMethod;
               ^
1 error generated.
```
As a workaround I implemented a templated function that casts `noexcept` functions pointers and pointers to methods to counterparts without `noexcept`, otherwise you could explicitly write:

```cpp
    emscripten::class_<Cls>("Cls").function("fn", emscripten::select_overload<void(Cls&)>(&foo))
```

But this seems ugly to me, adding `noexcept` support seems legitimate, since a lot of STL classes (`std::vector<>` in particular) uses `noexcept` functions that need such workarounds when ported.

**Comment by s0l0ist** [comment]
I have this issue as well. 

I have this issue as well. If I remove this keyword, the binding compiles successfully.

I've found an alternative solution that may apply to you. If you change the `.function` binding method to use `optional_override` the problem goes away:

```
        ...
        .function("fn", optional_override([](Cls& self) {
               return self. fn();
          }))
```
