### ISSUE TITLE
Use Docker image for CircleCI

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9496]
Currently each of our jobs does some `apt-get` stuff, and according to the CircleCI docs the best way to cache that is to use a Docker image.

Sounds like we want a custom docker image for exactly the stuff we need on CI here. We may need to recreate it as CI requirements change, so it would be good to have an easy way to generate it (I don't know enough about Docker to know what people do for that).

**Comment by sbc100** [comment]
You mean replace:

```   
docker:                                                                      
      - image: buildpack-deps:bionic 
```

with something like:

```
docker:                                                                      
      - image: emscripten-ci-image
```

That makes sense I guess.   What I want to avoid is having to include docker commands in our recipe but it doesn't sounds like that is what you are suggesting?

**Comment by kripken** [comment]
Yes, I think just having a custom image that already includes our apt-get installations would be useful. Should save a bunch of resources, and also avoid timeouts when the ubuntu apt-get servers are down.

**Comment by sbc100** [comment]
I'm seeing some JVM crashes on the CI which could be releated this change maybe?:

https://circleci.com/gh/emscripten-core/emscripten/192728?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
test_fs_nodefs_home (test_core.wasm2) ... ok
/root/project/tests/fuzz/5.c
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f43766bd1f8, pid=23326, tid=0x00007f42f3543700
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x2d21f8]
#
# Core dump written. Default location: /tmp/tmp3a9em01p/emscripten_test_wasm2_utufniaj/core or core.23326
#
# An error report file with more information is saved as:
# /tmp/tmp3a9em01p/emscripten_test_wasm2_utufniaj/hs_err_pid23326.log
#
# Compiler replay data is saved as:
# /tmp/tmp3a9em01p/emscripten_test_wasm2_utufniaj/replay_pid23326.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
shared:ERROR: closure compiler failed (rc: -6. the error message may be clearer with -g1)
test_fs_nodefs_rw (test_core.wasm2) ... ERROR
```

**Comment by kripken** [comment]
I've seen those in the past, rarely. But perhaps this image increases the probability somehow? How many have you seen?

**Comment by haraldreingruber** [comment]
This issue can probably be closed, or do you want to keep it open until potential regressions (e.g. JVM crash mentioned above) can be ruled out?

**Comment by kripken** [comment]
I think we can close it, thanks. If the JVM crash issue recurs we can open a specific issue for that.
