### ISSUE TITLE
embind serialization of string to std::wstring fails if memory growth happens

### ISSUE THREAD

**Issue by evanw** [emscripten-core/emscripten#9497]
I'm getting a weird bug where sending a string from JS to C++ using embind fails if the string is really big. The string is the right size but the contents are random, as if it had never been initialized. The bug is in `embind_register_std_wstring`:

https://github.com/emscripten-core/emscripten/blob/b42d1b3c5c136e94071d9ca10c660a410426ffcc/src/embind/embind.js#L755-L769

This code incorrectly calls `getHeap()` before calling `_malloc()`. If `_malloc()` causes the heap to grow, then the heap reference obtained earlier is stale. This then causes the code below to write past the end of the old array, which goes nowhere. The memory for the string remains uninitialized.

This is basically the same issue as #3299. I'm filing it as a new issue because that one's really old. It appears that this bug has been around for quite a long time since this buggy code is from #3318 (so since 2015).

Sorry, I don't have time to put together a patch. It should be an easy fix though.

**Comment by kripken** [comment]
Thanks @evanw! I opened #9500.
