### ISSUE TITLE
React-Native-mode: trying to access "fs" and "path"

### ISSUE THREAD

**Issue by martinheidegger** [emscripten-core/emscripten#9498]
When trying to use `libsodium-js` (compiled using emscripten) in react-native, I am running into the issue that it is compiled in a way that it uses `path` and `fs` as require statements:

https://github.com/emscripten-core/emscripten/blob/941bbc6b9b35d3124f17d2503d7a32cc81032dac/src/shell.js#L121-L122

The problem is that node.js modules _(also affects ["crypto"](https://github.com/emscripten-core/emscripten/blob/master/src/library_uuid.js#L41))_ are not supported by react-native and by consequence I need to recompile libsodium to be web-only.

It would be good if emscripten could add a logic to automatically detect if its running in a react-native context and avoid using those dependencies.

Here is the error thrown in expo:

> The package at "./node_modules/libsodium-sumo/dist/modules-sumo/libsodium-sumo.js" attempted to import the Node standard library module "path". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo

**Comment by martinheidegger** [comment]
Amending to this: Not having a path is the easier of the two problems. crypto is harder as react-native doesn't come with a sync randomBytes function.

**Comment by nth-chile** [comment]
My build depends on "path", "fs", and "document", and my app is React Native
