### ISSUE TITLE
Extending an Embind C++ class with a JS class

### ISSUE THREAD

**Issue by matpen** [emscripten-core/emscripten#9501]
I just stumbled upon the same problem described in #7200: it appears that it is not possible to extend a C++ class with a JS class. In other words:

```
// in C++

#include <emscripten/bind.h>

class MyCppClass {
public:
    MyCppClass() {}
};

EMSCRIPTEN_BINDINGS(mymodule) {
    using namespace emscripten;
    class_<MyCppClass>("MyCppClass");
}

// then in JS

class MyJsClass extends MyCppClass {
    constructor() {
        super();
    }

    jsfun() {
        console.log('This is jsfun');
    }
}
```

the above leads to two problems:
* as explained [here](https://github.com/emscripten-core/emscripten/issues/7200#issue-364712700), [this code](https://github.com/emscripten-core/emscripten/blob/2ba90d02f63fd8993cae1fdb88c6dfecd02d8b4d/src/embind/embind.js#L1924) will throw an exception (`Use 'new' to construct MyCppClass`) when calling `super()`;
* even if the check is disabled (as suggested [here](https://github.com/emscripten-core/emscripten/issues/7200#issue-364712700)), instances of `MyJsClass` will have no access to `jsfun()` because the prototype is overridden [here](https://github.com/emscripten-core/emscripten/blob/2ba90d02f63fd8993cae1fdb88c6dfecd02d8b4d/src/embind/embind.js#L1936) (as explained [here](https://github.com/emscripten-core/emscripten/issues/7200#issuecomment-437279825)).

It looks like #7200 was closed by the OP and consequently abandoned. However, I fee like this would be a nice feature to have, so I allowed myself to bring the idea back up.

Any chance that this will be eligible for future iterations?

**Comment by matpen** [comment]
Friendly ping.

**Comment by jgravelle-google** [comment]
I don't have too strong of an opinion here either way. In general my intuition says I wouldn't expect any ES6 features to work nicely with Emscripten features. As we become increasingly wasm-only it might make sense to revisit that, but at the moment I'm not aware of any plans to ES6-ify Emscripten's JS output.

This is also betraying my ignorance of modern JS, however. Looking at documentation for ES6 classes, it seems like they're implemented in terms of the prototype chain, so in principle we should be able to do something. In practice I can't really guess what that would involve. If some brave volunteer were to submit a patch I wouldn't object to it though.
