### ISSUE TITLE
How do you get emcc to fail checks for dlopen?

### ISSUE THREAD

**Issue by bplevin36** [emscripten-core/emscripten#9523]
I'm trying to port JamVM (as several have unsuccessfully tried before), which requires both pthreads and dlopen to dynamically load the native portions of the Java class library.  Attempting to run `emcc` with both pthreads and dynamic linking enabled causes huge problems, unsurprisingly.  I think I can get around it, though, because the shared objects needed are known at compile time.

I've been trying to use libltdl to "preopen" the objects, making them [dlopen-able at runtime](https://www.gnu.org/software/libtool/manual/libtool.html#Dlpreopening).  Looking at libltdl's source, I don't see any reason this shouldn't work as long as I don't use high optimization levels.  The problem is that libltdl's configure script ignores cross-compilation directives and does a bunch of checks to see what dynamic loading properties already exist on the system.  `emcc` does a very good job of faking dlopen functionality, so libltdl concludes that native dlopen is supported and refuses to build with dlpreopen enabled because it thinks it can use native dlopen at runtime.  Does anyone know how to get emcc to fail these checks?  I've already tried reading through libltdl's configure and configure.ac, and they're both completely impenetrable to anybody who hasn't been using autotools since they were in diapers.

**Comment by kripken** [comment]
One hackish way to do this, that happens to work because of emscripten internals, is to add `--js-library lib.js` to the emcc flags, and implement that JS file with
```javascript
delete LibraryManager.library.dlopen;
```
This works since emscripten JS libraries have full control about what to add and remove from the JS libraries, and dlopen is a JS library function.

However, this is obviously a bad hack. If this is a common issue then perhaps we can add an option for "JS library functions to blacklist"?

**Comment by bplevin36** [comment]
This is my third project with Emscripten where I've run into problems like this (emcc makes checks pass that should fail in order for configure to generate the right build).  But based on how few other comments I've seen like mine, it doesn't sound like that common of a need.

In any case, I'll try this and see if I can get a working build out of it.  Thanks!

**Comment by sbc100** [comment]
IIRC your can pre-seed the autoconf cache for force the setting you want.  See https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Site-Defaults.html.  Looks like settings CONFIG_SITE to a file with the correct contents should do the trick.

You might have an easier time updating the upstream project and adding static linking option there.

**Comment by bplevin36** [comment]
My thoughts about libltdl turned out to be wrong, but your hack did make configure work correctly so I'll close this.  Thanks!
