### ISSUE TITLE
Adding thread support

### ISSUE THREAD

**Issue by watfuk** [emscripten-core/emscripten#953]
(correct me if this already exists; I didn't see it in the documentation at least) Could emscripten be given support for message based threading with a special C++ library that permits similar behavior to JavaScript?  That way, a threaded application can compile both to machine code and to JS with web workers.

**Comment by SlightlyCyborg** [comment]
I'll be excited for pthread support to be a thing of the future as it sure makes game loops with interrupts from the outside difficult. Perhaps I'm just not thinking about this in the right way though.
