### ISSUE TITLE
js-optimizer.js exception on simple program

### ISSUE THREAD

**Issue by alkhimey** [emscripten-core/emscripten#9535]
```emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.38.46 (commit 41adfea99dd4af48c9d068f572d42bb6606384f1)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
The following code does not compile:
```
#include <stdint.h>
#include <emscripten.h>

EMSCRIPTEN_KEEPALIVE
uint64_t  square(uint64_t x)
{
    return x * x;
}
```
Compilation with:
```
emcc \
-s WASM=1 -s ONLY_MY_CODE=1 -g3 -O3 \
-s RESERVED_FUNCTION_POINTERS=20 -o output.js test.c \
-s ERROR_ON_UNDEFINED_SYMBOLS=0
```

Produces the following error:
```
$
/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:2040
    default: throw 'wha? ' + JSON.stringify(type) + new Error().stack;
             ^
wha? 12Error
    at makeAsmCoercedZero (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:2040:53)
    at makeAsmVarDef (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:2045:14)
    at denormalizeAsm (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:2240:18)
    at /home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:7182:11
    at traverse (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:247:18)
    at traverseChildren (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:224:25)
    at traverse (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:252:9)
    at traverseChildren (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:224:25)
    at traverse (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:252:9)
    at traverseChildren (/home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js:224:25)
shared:ERROR: '/home/artium/emsdk/node/12.9.1_64bit/bin/node /home/artium/emsdk/fastcomp/emscripten/tools/js-optimizer.js output.temp.asm.js eliminateDeadGlobals last asm' failed (1)
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

Yet, replacing `uint64_t` with `uint32_t` compiles just fine.

**Comment by alkhimey** [comment]
Additionally, using `long` compiles fine but produces a binary that use `i32`. I was expecting `i64` to be used:

```
(module
 (export "_square" (func $_square))
 (func $_square (; 0 ;) (; has Stack IR ;) (param $0 i32) (result i32)
  (i32.mul
   (local.get $0)
   (local.get $0)
  )
 )
)
```

**Comment by sbc100** [comment]
On the second point: `long` is defined to be 32-bit on wasm32.   Wasm32 is what they call ILP32 (ints, long and pointers are all 32-bit).  If you want 64-bit use `long long` or better still using `int64_t`.

More info: https://github.com/WebAssembly/tool-conventions/blob/master/BasicCABI.md

**Comment by alkhimey** [comment]
@sbc100 Thanks for the info. Tried `long long` and got the same exception from above.

**Comment by kripken** [comment]
The issue here is probably `ONLY_MY_CODE`. That's an experimental mode that isn't well supported, and we should probably remove, as there are better ways to do such things now, see

https://github.com/emscripten-core/emscripten/wiki/WebAssembly-Standalone

If those don't cover what you're trying to do, can you explain a little more why you're using that flag?

**Comment by alkhimey** [comment]
@kripken I tried the suggested `-s STANDALONE_WASM` in the link you provided. Indeed there is no exception and the code compiles, but as an output I get a file a little bit bigger than 10KBytes. In fact, I see no effect of the flag on the output wast file. 

My reason for using `ONLY_MY_CODE` is that I am learning wasm and want to compile simple programs into simple binaries and study those. Boilerplate code makes the learning process very difficult.

**Comment by kripken** [comment]
@alkhimey I see, thanks. For learning, perhaps use `-s SIDE_MODULE`, as that will only emit your own code, without system libraries or runtime support, see the "Create a dynamic library" section in that link.

**Comment by kripken** [comment]
Some more options for learning:

* Build to an object file, not an executable, `emcc file.cpp -c -o file.o`, then inspect that using wabt. That will only include your own code (but is not executable since it lacks system libraries and runtime support).
* Optimize as much as possible. For example `-Os --profiling-funcs` will emit a 2K wasm file (smaller than your 10K).

Overall, an object file lets you read your own compiled code, but to also run it, you do need system libraries etc.
