### ISSUE TITLE
WebAssembly.Table() call appears in .js output with WASM=0 since 1.38.45

### ISSUE THREAD

**Issue by WesThorburn** [emscripten-core/emscripten#9536]
As of version 1.38.45, when compiling with `WASM=0` the following snippet appears in the output.
```
var wasmTable = new WebAssembly.Table({
    "initial": 0,
    "maximum": 0,
    "element": "anyfunc"
});
```
This is causing `'WebAssembly' is undefined` errors on older browsers. 

`WebAssembly.Table()` doesn't appear in the output after recompiling with version 1.38.44.

**Comment by kripken** [comment]
Thanks @WesThorburn! Looks like this is indeed a regression on fastcomp. Fix in #9539 plus testing so this never happens again.
