### ISSUE TITLE
wast and wasm files does not contain exactly the same program

### ISSUE THREAD

**Issue by alkhimey** [emscripten-core/emscripten#9538]
The following C code was compiled with `emcc 
-s WASM=1 -s ONLY_MY_CODE=1 -g3 -O3 
-s RESERVED_FUNCTION_POINTERS=20 -o output.js test.c 
`

```
#include <stdint.h>
#include <emscripten.h>

EMSCRIPTEN_KEEPALIVE
 int square(  int x)
{
    return x * x;
}
```
And produced this `wast` file:
```
(module
 (export "_square" (func $_square))
 (func $_square (; 0 ;) (; has Stack IR ;) (param $0 i32) (result i32)
  (i32.mul
   (local.get $0)
   (local.get $0)
  )
 )
)
```
And the following `wasm` file:
```
00000000: 0061 736d 0100 0000 0106 0160 017f 017f  .asm.......`....
00000010: 0302 0100 070b 0107 5f73 7175 6172 6500  ........_square.
00000020: 000a 0901 0700 2000 2000 6c0b 0011 046e  ...... . .l....n
00000030: 616d 6501 0a01 0007 5f73 7175 6172 65    ame....._square
```

You can see that starting at address `00000008`, there is a type section `0106 0160 017f 017f` which does not appear in the `wast` file.
Indeed `wasm2wat` tool produced:
```
(module
  (type (;0;) (func (param i32) (result i32)))
  (func $_square (type 0) (param i32) (result i32)
    local.get 0
    local.get 0
    i32.mul)
  (export "_square" (func $_square)))
```

I guess that semantically these two programs are the same, yet I think it is important that the listings represent the binary faithfully. Assembly listings are usually used to debug complex issues, and potentially compiler bugs.

**Comment by kripken** [comment]
The wasm text format has a few "simplifications" that make it easier to write by hand, which lead to differences like that one. In this case, that a function type can be implicit in the function's declaration. However, the wasm binary format doesn't allow such implicitness.

So this is working as intended, but I agree with you that the wasm text format has some annoyances, and I wish we'd done a better job on it.

**Comment by sbc100** [comment]
We don't generate wast files at all in emscripten anymore.
