### ISSUE TITLE
failed to asynchronously prepare wasm: Error: import function env:a must be callable (Apple products)

### ISSUE THREAD

**Issue by v-stein** [emscripten-core/emscripten#9540]
Hi,

I get this error on Safari for MacOS and iOS 13 browsers (tested with Safari, Chrome and Firefox).
I tried to change the way it was compiled, but nothing I tried did work.

emcc version: **1.38.46** 
clang version: **6.0.1**
Operating system: **Debian 4.19.67**

Here is the error I get:
`[Warning] failed to asynchronously prepare wasm: Error: import function env:a must be callable (my_app.js, line 1)`

Which seems to be thrown by this function:
```javascript
function instantiateArrayBuffer(receiver) {
        return getBinaryPromise().then(function(binary) {
            return WebAssembly.instantiate(binary, info)
        }).then(receiver, function(reason) {
            err("failed to asynchronously prepare wasm: " + reason);
            abort(reason)
        })
    }
```

And here is the command running the compilation:
```bash
# Actually one-lined, but added line-breaks for better readability
em++
  -std=c++14
  -O3
  -s WASM=1
  -s ALLOW_MEMORY_GROWTH=1
  -s EXTRA_EXPORTED_RUNTIME_METHODS=['cwrap']
  -s BINARYEN_TRAP_MODE='clamp'
  -I /path/to/my_app/lib/**/*.c /path/to/my_app/main.cpp
  -o /path/to/compiled/my_app.js
```

I really can't figure out where this does come from, so if anyone has an idea, feel free to share your thoughts.

---------
*Edit: Added system versions*

**Comment by alkhimey** [comment]
Did you use the loader script generated by emscripten or did you load the wasm file with custom code?

**Comment by v-stein** [comment]
I did use the generated loader script, I don't want to try to load it myself yet.

**Comment by kripken** [comment]
Building with `-g` will add debug info, which can make the error more understandable in many cases, worth trying.

**Comment by v-stein** [comment]
Ok, building with `-g` throws a different error.

`TypeError: this.cmod.cwrap is not a function.`

It seems to be related to Webpack, so I'll be closing this issue.

**Comment by v-stein** [comment]
For anyone having the issue, it seems that iOS has a global "Module" variable in some particular context.

The solution I ended up with is to put in the configuration these options:
`-s MODULARIZE=1 -s EXPORT_NAME="'MyModule'"`
Then using it with:
```javascript
function onWasmScriptLoaded () {
  let wasmModule = MyModule();
  // ...
}
```
