### ISSUE TITLE
"failed to find function _sbrk" when compiling with --llvm-lto 3 -s USE_PTHREADS -s FETCH=1

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#9561]
Probably the same issue as #8242, however the _sbrk requirement is new.
This worked in 1.38.45, but broke in 1.38.46. I have only tested with the fastcomp backend.

I figured I'd log this as a separate issue, in case this is fresh in someone's mind (maybe caused by #9438?), but feel free to close as a dupe if you don't think this is right.

**Comment by kripken** [comment]
Looks like this is specific to fastcomp, I don't see an error using upstream.
