### ISSUE TITLE
wasm-ld doesn't support required flags

### ISSUE THREAD

**Issue by Beuc** [emscripten-core/emscripten#9565]
Hi,

When compiling ffmpeg with 1.38.46, I used to get warnings like:
```
emcc:WARNING: ignoring unsupported linker flag: `-soname`
emcc:WARNING: ignoring unsupported linker flag: `libavutil.so.55`
emcc:WARNING: ignoring unsupported linker flag: `-Bsymbolic`
emcc:WARNING: ignoring unsupported linker flag: `--version-script`
emcc:WARNING: ignoring unsupported linker flag: `libavutil/libavutil.ver`
emcc:WARNING: ignoring unsupported linker flag: `--as-needed`
emcc:WARNING: ignoring unsupported linker flag: `-z`
emcc:WARNING: ignoring unsupported linker flag: `noexecstack`
emcc:WARNING: ignoring unsupported linker flag: `--warn-common`
emcc:WARNING: ignoring unsupported linker flag: `-rpath-link=libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample`
```

I now get:
```
wasm-ld: error: unknown argument: -soname
wasm-ld: error: cannot open libavutil.so.55: No such file or directory

shared:ERROR: '/home/me/workdir/emtests/renpyweb-asyncify/emsdk/upstream/bin/wasm-ld -o libavutil/libavutil.so.55 --allow-undefined --lto-O0 -soname libavutil.so.55 -Llibavcodec -Llibavdevice -Llibavfilter -Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample -z noexecstack libavutil/adler32.o libavutil/aes.o libavutil/aes_ctr.o libavutil/audio_fifo.o libavutil/avstring.o libavutil/base64.o libavutil/blowfish.o libavutil/bprint.o libavutil/buffer.o libavutil/camellia.o libavutil/cast5.o libavutil/channel_layout.o libavutil/color_utils.o libavutil/cpu.o libavutil/crc.o libavutil/des.o libavutil/dict.o libavutil/display.o libavutil/downmix_info.o libavutil/error.o libavutil/eval.o libavutil/fifo.o libavutil/file.o libavutil/file_open.o libavutil/fixed_dsp.o libavutil/float_dsp.o libavutil/frame.o libavutil/hash.o libavutil/hmac.o libavutil/imgutils.o libavutil/integer.o libavutil/intmath.o libavutil/lfg.o libavutil/lls.o libavutil/log.o libavutil/log2_tab.o libavutil/mastering_display_metadata.o libavutil/mathematics.o libavutil/md5.o libavutil/mem.o libavutil/murmur3.o libavutil/opt.o libavutil/parseutils.o libavutil/pixdesc.o libavutil/pixelutils.o libavutil/random_seed.o libavutil/rational.o libavutil/rc4.o libavutil/reverse.o libavutil/ripemd.o libavutil/samplefmt.o libavutil/sha.o libavutil/sha512.o libavutil/stereo3d.o libavutil/tea.o libavutil/threadmessage.o libavutil/time.o libavutil/timecode.o libavutil/tree.o libavutil/twofish.o libavutil/utils.o libavutil/xga_font_data.o libavutil/xtea.o -L/home/me/workdir/emtests/renpyweb-asyncify/emsdk/upstream/emscripten-git/system/local/lib -L/home/me/workdir/emtests/renpyweb-asyncify/emsdk/upstream/emscripten-git/system/lib -L/home/me/workdir/emtests/renpyweb-asyncify/emsdk/.emscripten_cache/wasm-obj --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024 --relocatable' failed (1)
```
which breaks the build.

Note: I don't need these .so right now, but the ffmpeg build system is not entirely following my `--disable-shared` configuration.

It looks like wasm-ld would benefit from supporting these flags for people compiling dynamic libraries.

(In my particular case I'll try to patch-up the build system though I'd appreciate release notes for stricter compiler changes.)

**Comment by kripken** [comment]
Looks like fallout from the wasm-ld flag refactoring... adding to list of wasm backend blockers.

**Comment by dschuff** [comment]
I don't think this is a blocker because it's not a regression from fastcomp, is it? AFAIK fastcomp only ever supported `-s SIDE_MODULE`?

**Comment by dschuff** [comment]
Also, it's possible that the new dynamic linking model might not even have the concept of soname in the same sense that ELF does.

**Comment by kripken** [comment]
I think this does build with fastcomp? In general ffmpeg has been known to compile there for a very long time. It just recently regressed. So I think this is both a regression compared to upstream and compared to fastcomp.

**Comment by sbc100** [comment]
Looks like this was fixed between 1.38.46 and 1.38.47.   It should not longer appear with a more recent version.

**Comment by nhooyr** [comment]
Hi Guys!

I'm seeing this compiling `libpng` on version `1.39.16`.

**Comment by nhooyr** [comment]
```
wasm-ld: error: unknown argument: -version-script
wasm-ld: error: unknown file type: .libs/libpng16.ver
emcc: error: '/tmp/x11wasm/build/home/emsdk/upstream/bin/wasm-ld -o .libs/libpng16.so.16.38.0 .libs/png.o .libs/pngerror.o .libs/pngget.o -L/tmp/x11wasm/build/home/emsdk/upstream/emscripten/system/local/lib .libs/pngmem.o -L/tmp/x11wasm/build/home/emsdk/upstream/emscripten/system/lib .libs/pngpread.o -L/tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm .libs/pngread.o .libs/pngrio.o .libs/pngrtran.o .libs/pngrutil.o .libs/pngset.o .libs/pngtrans.o .libs/pngwio.o .libs/pngwrite.o .libs/pngwtran.o .libs/pngwutil.o mips/.libs/mips_init.o mips/.libs/filter_msa_intrinsics.o intel/.libs/intel_init.o intel/.libs/filter_sse2_intrinsics.o powerpc/.libs/powerpc_init.o powerpc/.libs/filter_vsx_intrinsics.o /tmp/x11wasm/build/home/emsdk/upstream/emscripten/system/lib/libz.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libc.a -version-script .libs/libpng16.ver --relocatable -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
```

**Comment by sbc100** [comment]
Technically we don't support that flag.  Do you know where its coming from,  can it be suppressed the case of wasm?

We can add to the list of flags we ignore, but you will still see a warning because this flag doesn't do anything in emscripten.

Also, we don't really supported shared libraries.  Does adding `--disable-shared` fix this?

**Comment by nhooyr** [comment]
Unfortunately I can't easily suppress it without patching. I'm not 100% exactly how it works but it seems like it's from here:

https://github.com/glennrp/libpng/blob/dbe3e0c43e549a1602286144d94b0666549b18e6/scripts/libtool.m4#L5230

Patching to remove it seems to fix.

**Comment by sbc100** [comment]
I've uploaded a fix.   But I would recommend avoiding building the shared libraries if you can.  Can you try passing `--disable-shared` to configure?

**Comment by nhooyr** [comment]
> I've uploaded a fix. But I would recommend avoiding building the shared libraries if you can. Can you try passing --disable-shared to configure?

So the reason I'm building shared libs is just to install the appropriate `pkgconfig` files so that other pieces of software I build see it as existing in the emscripten system and I can easily link my final piece against them as they're all in a standard spot.

**Comment by sbc100** [comment]
As far as I know that pkgconfig infrastructure works fine with static libraries, doesn't it?   Its sounds like you use case is that you actually want static libraries anyway (you final binary will include the libraries, they won't be separate modules).

Admittedly some build systems really like to use shared libraries and so emscripten can try to fake them, but its better to be clear and just use static libraries if possibls (.a files as opposed to .so files).

**Comment by nhooyr** [comment]
True, I guess there would be no harm in passing that flag then. I was under the assumption that disabling shared libraries meant disabling pkgconfig but that doesn't really make sense. I'll give it a shot and let you know how it goes.

**Comment by nhooyr** [comment]
Yea it broke pixman's tests unfortunately somehow.

```
make[3]: Entering directory '/tmp/x11wasm/deps/pixman/test'
  CC       oob-test.o
  CC       utils.lo
  CC       utils-prng.lo
  CCLD     libutils.la
  CCLD     oob-test
wasm-ld: error: --shared-memory is disallowed by pixman-implementation.o because it was not compiled with 'atomics' or 'bulk-memory' features.
emcc: error: '/tmp/x11wasm/build/home/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_vn_cvfsp/oob-test.wasm oob-test.o ./.libs/libutils.a -L/tmp/x11wasm/build/home/emsdk/upstream/emscripten/system/local/lib ../pixman/.libs/libpixman-1.a -L/tmp/x11wasm/build/home/emsdk/upstream/emscripten/system/lib -L/tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libc-mt.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libcompiler_rt.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libc-wasm.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libc++-mt-noexcept.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libc++abi-mt-noexcept.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libdlmalloc-mt.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libpthread-mt.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libc_rt_wasm.a /tmp/x11wasm/build/home/emsdk/upstream/emscripten/cache/wasm/libsockets-mt.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --allow-undefined --import-memory --import-table --shared-memory --export main --export malloc --export free --export __data_end --export __wasm_call_ctors --export __errno_location --export emscripten_get_global_libc --export __pthread_tsd_run_dtors --export pthread_self --export __emscripten_pthread_data_constructor --export emscripten_futex_wake --export memalign --export memset -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (1)
```

And some other libraries I'm building.

For now I switched to `--disable-shared` for `libpng` which seems to work and then `--enable-shared` for everything else.

**Comment by sbc100** [comment]
I would advise using `--disable-shared` across the board if you can. 

I imagine the the `--shared-memory` flag is being added because you passing `-pthread` a link flag?

BTW: If you run with your `make` command with `VERBOSE=1` it should show the full link command that is failing (the wasm-ld command is the internal command that is run from `emcc`).   You can also run cmake with `-G ninja` and then build with ninja which always prints the full failing command in the case of an error.

**Comment by nhooyr** [comment]
You got it! Will give it a shot soon.

> I imagine the the --shared-memory flag is being added because you passing -pthread a link flag?

All I did was `emconfigure --prefix=<my-prefix> ./configure && emmake make` with `PKG_CONFIG_LIBDIR=<mylibdir>`.

**Comment by nhooyr** [comment]
Worked!!!

```
  emconfigure ./autogen.sh --disable-shared
  export EMMAKEN_CFLAGS="-s USE_PTHREADS=1"
  emmake make
  emmake make install
```
