### ISSUE TITLE
ffmpeg or avconv on client side?

### ISSUE THREAD

**Issue by binarykitchen** [emscripten-core/emscripten#957]
Hello guys

Has anyone of you ever tried to port ffmpeg or avconv to client side with emscripten?

Cheers
Michael

**Comment by MadLittleMods** [comment]
See

 - https://www.npmjs.com/package/videoconverter -> https://github.com/bgrins/videoconverter.js
 - https://github.com/muaz-khan/Ffmpeg.js/
