### ISSUE TITLE
Emterprer and Maximum call stack size exceeded on Safari/iOS 13

### ISSUE THREAD

**Issue by Kukunin** [emscripten-core/emscripten#9584]
Hello. I have a project using own fork of `ffmpeg.js`. In Safari 13/iOS 13 it raises an exception:

```
RangeError: Maximum call stack size exceeded
```

It works fine in Safari/iOS 12 with no issues. I happen only with WebAssembly, asm.js works flawlessly. I run ffmpeg.js in WebWorker, didn't try in the Main thread.

Overall, Safari 13 broke WebAssembly (https://github.com/mono/mono/issues/15981, https://bugs.webkit.org/show_bug.cgi?id=200918), but I hope at least we can find a workaround.

I managed to make Safari 13 working by splitting a huge function in FFmpeg's source code. Before it said and crashed.

```
warning: Output contains some very large functions (9747 lines in _ff_epzs_motion_search), consider building source files with -Os or -Oz)
```

Now it says

```
warning: Output contains some very large functions (4946 lines in _ff_epzs_motion_search), consider building source files with -Os or -Oz)
```

and it turned small enough to work in Safari 13 desktop.

iOS 13 Safari (mobile) crashes earlier in runtime.  I did a little research:

I used a simple function to measure stack trace size that left in a point of call.
```js
self.leftStackSize = function() {
  console.log('measure left stack');
  let i = 0;
  (function inc() {
    if(i % 100 == 0) { console.log(i); }
    i++;
    inc();
  })();
};
```

So, the idea is simple: we call a function recursively. We measure how many calls we can have before the exception is thrown. Here is numbers:

| Case | iOS 12 | iOS 13 | iOS 13 asm.js | Safari 13 | Chrome |
|------|--------|--------|---------------|-----------|-------|
| Before ffmpeg.js, in webworker | 3100 | 3100 | - | 3000 | 5700 |
| Before `fill_buffer` in `aviobuf.c` (middle of execution) | 2900 | 300 | - |1300 | 5700 |
| After `fill_buffer` in `aviobuf.c` (buffers are set) | 2900 | 0 | 3000 | 1100 | 5700 |

I haven't localized code that causes stack eating, but it's visible that stack memory reduces in both Safari 13 desktop/mobile and doesn't change significantly in iOS12 or Chrome.

The whole failing code is inside `EMTERPRETIFY_WHITELIST` because I need to asynchronously feed FFmpeg with input. The code fails before the actual asynchronous place, so I tried without emterpreter.

So, in a place, when with `-s EMTERPRETIFY=1` I had **0** and **1100** for iOS13 and Safari 13 respectively, without emterpreter It had **2200** for both iOS/Safari 13.

That's why I drew a conclusion that emterpreter is related to eating stack memory in the newest Safari. I'm not a big expert to dig more, but I guess that stack can be exceeded while passing bytecode to `emterpret` function via arguments. 

Sorry, if something is not clear. It's a definitely complicated bug and caused by the latest Safari, but I hope that provided information is helpful to find a workaround and/or help Apple fix it on their side.

**Comment by davlhd** [comment]
Any news on this? I am hitting this bug without emterpreter.
