### ISSUE TITLE
Need to Redirect Build Output to a File

### ISSUE THREAD

**Issue by DragonOsman** [emscripten-core/emscripten#9585]
I tried to use Emscripten to build a Qt GUI project to Wasm, but it failed.  I wanted to generate a log file so I appended the build command I ran with 
```
> build-log.txt
```
but `build-log.txt` is an empty file so nothing was sent to it.  Is there a way to get Emscripten build logs or to at least create my own by redirecting the build output to a file?  I'm trying to use Qt version 5.13.1 which has Wasm support (though it needs to be compiled to Wasm on the command line since Qt Creator itself doesn't have a built-in toolchain for Emscripten yet (they plan to add it in soon apparently)).  

This is the full command I used:
```
em++ -Wall -std=c++17 -pedantic -I C:\Qt\5.13.1\wasm_32\include -I C:\Qt\5.13.1\wasm_32\include\QtWidgets -I E:\programming\Qt\build-notepad-project-Desktop_Qt_5_13_1_MSVC2017_64bit-Debug main.cpp notepad.cpp -s WASM=1 -s EXPORT_ALL=1 -o notepad.html > ./build-log.txt
```
Thanks in advance for any help.

**Comment by Kukunin** [comment]
build logs might be written to `stderr` instead of `stdout`. Can you try redirect them by `2> build-log.txt` ?

**Comment by DragonOsman** [comment]
Okay, that worked.  Thanks.
