### ISSUE TITLE
Error: undefined symbol: __cxa_find_matching_catch_24

### ISSUE THREAD

**Issue by Luthaf** [emscripten-core/emscripten#9605]
I am getting the above error when compiling my code with the latest emscripten version.

I traced it to the following parameter, and confirm that I can fix the error by setting `maxExceptionArgs` to 30.

https://github.com/emscripten-core/emscripten/blob/8f2ee09690fe29122bcc7368b873e4b78cdd4ea5/src/library_exceptions.js#L328

----

Is there anything I can do on my side to prevent LLVM from emitting call to this function?

----

The above code was changed in #8040/#8046, ping @juj

**Comment by kripken** [comment]
Thanks @Luthaf , this does look like a regression from that PR. A possible fix is in #9607, applying that locally should work around it for you.
