### ISSUE TITLE
casting doubles to int64_t fails for dynamic modules

### ISSUE THREAD

**Issue by gl84** [emscripten-core/emscripten#9613]
During porting of an existing piece of code that dynamically loads plugins I get an unexpected runtime error
`RuntimeError: float unrepresentable in integer range` in the fastcomp backend.

`emcc --version`
`1.38.47 (commit cf01b11c4e5c081372c75af0e5c92a9de071ad7c)`

A minimal reproducing test case is:
```C++
#include <cstdint>
#include <cstdio> 
#include <cinttypes>

int main() {
    // bounds for int64_t: 
    // std::numeric_limits<int64_t>::lowest()= -9223372036854775808
    // std::numeric_limits<int64_t>::max()   =  9223372036854775807
    // std::numeric_limits<int32_t>::lowest()= -2147483648
    // std::numeric_limits<int32_t>::max()   =  2147483647
    double d1 = -22009855.6956453174; // outside int32_t range but inside int64_t
    int64_t id = static_cast<int64_t>(d1); // RuntimeError: integer overflow
    printf("value=%" PRId64 "\n",id);
    return 0;
}
``` 
Compiling with
`emcc -std=c++11 main.cpp -o main.js -s MAIN_MODULE=1 -O0 --profiling-funcs` throws the runtime error.

Compiling with optimizations turned on
`emcc -std=c++11 main.cpp -o main.js -s MAIN_MODULE=1 -Os --profiling-funcs`.
works as expected. It seems that in this case the cast is optimized away...

**Comment by kripken** [comment]
Thanks @gl84, oddly it looks like without main module it emits `i64.trunc_f64_s` but with main module it's `_u`. That does look like a bug.

However, we are very close to switching the default from fastcomp to the wasm backend, and this problem won't happen there. So I'd recommend switching to it now (but patches for fixing fastcomp bugs are still welcome if someone is interested to work on that).
