### ISSUE TITLE
How include path to ZLIB and OPENSSL_CRYPTO_LIBRARY

### ISSUE THREAD

**Issue by zababurinsv** [emscripten-core/emscripten#9614]
Hi
I compile code, and i get this error.

-- Performing Test HAVE_CXX_FLAG_WREDUNDANT_MOVE - Success
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  terminal/CMakeLists.txt:4 (find_package)

How i can include this librarys ?
i am use this string.

 emcmake cmake  ../node_modules/client

-- Performing Test HAVE_CXX_FLAG_WREDUNDANT_MOVE - Success
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  terminal/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sergey/Desktop/wasm/build-ton-client/CMakeFiles/CMakeOutput.log".
See also "/home/sergey/Desktop/wasm/build-ton-client/CMakeFiles/CMakeError.log".
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/sergey/emsdk/node/8.9.1_64bit/bin/node" ../node_modules/lite-client -DCMAKE_TOOLCHAIN_FILE=/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake at /home/sergey/Desktop/wasm/build-ton-client

bush script
  emcmake cmake  ../node_modules/client
  emmake make

cmake found this file 

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found ZLIB: /usr/include /usr/lib/x86_64-linux-gnu/libz.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")

**Comment by zababurinsv** [comment]
i am found this library.

  emcmake cmake  ../node_modules/lite-client \
       -PNG_BUILD_ZLIB="ON"
       -ZLIB_LIBRARY="/usr/lib/x86_64-linux-gnu/"
       -ZLIB_INCLUDE_DIR="/usr/include/usr/lib/x86_64-linux-gnu/"
       -OPENSSL_ROOT_DIR="/etc/ssl/"
       -OPENSSL_SSL_LIBRARY="/usr/lib/x86_64-linux-gnu/"
       -OPENSSL_CRYPTO_LIBRARY="/usr/lib/x86_64-linux-gnu/"
       -OPENSSL_INCLUDE_DIR= "/usr/include/usr/lib/x86_64-linux-gnu/"
       -DCMAKE_TOOLCHAIN_FILE="/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake"

but i get final error 
CMake Error: Error processing file: -DCMAKE_TOOLCHAIN_FILE=/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/sergey/emsdk/node/8.9.1_64bit/bin/node" ../node_modules/lite-client -PNG_BUILD_ZLIB=ON -DCMAKE_TOOLCHAIN_FILE=/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake at /home/sergey/Desktop/wasm/build-ton-client

How can it is cjange ?

**Comment by zababurinsv** [comment]
p,s
I am add this FLAG
  emcmake cmake  ../node_modules/lite-client
       -PNG_BUILD_ZLIB="ON"
       -ZLIB_LIBRARY="/usr/lib/x86_64-linux-gnu/"
       -ZLIB_INCLUDE_DIR="/usr/include/usr/lib/x86_64-linux-gnu/"
       -OPENSSL_ROOT_DIR="/etc/ssl/"
       -OPENSSL_SSL_LIBRARY="/usr/lib/x86_64-linux-gnu/"
       -OPENSSL_CRYPTO_LIBRARY="/usr/lib/x86_64-linux-gnu/"
       -OPENSSL_INCLUDE_DIR= "/usr/include/usr/lib/x86_64-linux-gnu/"
 -DCMAKE_TOOLCHAIN_FILE="/home/sergey/emsdk/emscripten/master/cmake/Modules/Platform/Emscripten.cmake"

But it is not work

**Comment by sbc100** [comment]
Is this a regression?  (i.e. did it used to work in a previous release?)

**Comment by zababurinsv** [comment]
No Work when i use cmake
When i use cmake emscripten  i see this error

**Comment by VirtualTim** [comment]
For ZLIB you should probably use the Emscripten port. This can be done by adding the linker flag '-s USE_ZLIB=1'.

I'm pretty sure you can't mix so's like that. If you want OPENSSL_CRYPTO_LIBRARY you probably have to compile it yourself.

**Comment by zababurinsv** [comment]
Thanks, I understood the sequence of actions.
Can you give a link to an article that describes how to make a library openssl for wasm ?

**Comment by zababurinsv** [comment]
Now i create zlib
libz.a
zlib.pc
example.wasm

and openssl 
libcrypto.a
libcrypto.so
libssl.a
libssl.so
openssl

I pointed  -DCMAKE_TOOLCHAIN_FILE="/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake"
But in error i have this path
 /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake
it is true path ?

If I entered the path correctly, should the errors disappear?
Is it possible to connect libraries in another way?

  emcmake cmake   ../node_modules/lite-client
  -DCMAKE_TOOLCHAIN_FILE="/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake" \
  -ZLIB_INCLUDE_DIR="/home/sergey/Desktop/wasm/build-zlib" \
  -ZLIB_LIBRARY="/home/sergey/Desktop/wasm/build-zlib/libz.a"
  -OPENSSL_ROOT_DIR="/home/sergey/Desktop/wasm/include/openssl"
  -OPENSSL_SSL_LIBRARY="/home/sergey/Desktop/wasm/include/openssl/apps/lib"
  -OPENSSL_CRYPTO_LIBRARY="include/openssl/apps/openssl"
  -OPENSSL_INCLUDE_DIR= "/home/sergey/Desktop/wasm/include"

**Comment by zababurinsv** [comment]
-- Found ZLIB: /home/sergey/Desktop/wasm/build-zlib/libz.a  
-- Found ZLIB: /home/sergey/Desktop/wasm/build-zlib /home/sergey/Desktop/wasm/build-zlib/libz.a
-- Found OpenSSL: /home/sergey/Desktop/wasm/build-openssl/openssl/lib (found version "1.1.0h")  
-- Found OpenSSL: /home/sergey/Desktop/wasm/build-openssl/openssl/lib   
-- Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY) 
-- Could NOT find Readline (this is NOT an error)

Is there a readline library for emscripten ?

**Comment by zababurinsv** [comment]
thanks, I started to understand how it works. I create cmake process.
