### ISSUE TITLE
Pthread assert on exit

### ISSUE THREAD

**Issue by englercj** [emscripten-core/emscripten#9627]
I'm hitting an assertion in `terminateAllThreads` when my app exits.

Specifically this one:

https://github.com/emscripten-core/emscripten/blob/9f883dc1f197541ac5c49a8653e7a5a1af63a099/src/library_pthread.js#L228

When entering this function `PThread.pthreads` has a single entry which is destroyed and the worker has `.pthread` marked as null. That worker happens to be in the `PThread.runningWorkers` list and so it later asserts when `pthread` is null.

It may be my misunderstanding, but it seems strange to assert that the pthread will exist when there is code above this that goes through every pthread and sets them all to null.

Is this a bug in the JS, or am I doing something wrong?

My configuration looks like:

```
-s USE_PTHREADS
-s PTHREAD_POOL_SIZE=2
-s EXIT_RUNTIME
-s DISABLE_EXCEPTION_CATCHING=0
```

**Comment by kripken** [comment]
I think this is the same as https://github.com/emscripten-core/emscripten/issues/9486 - yeah, it's quite annoying, I'll look into it right now!

**Comment by englercj** [comment]
Pretty sure that is the same issue, and your fix looks like it will work for me. Thanks for hitting that so fast! I'll leave this open and let the PR merge close it out.
