### ISSUE TITLE
How can I load the ‘*.data’ file？

### ISSUE THREAD

**Issue by lokpoi888** [emscripten-core/emscripten#9637]
I have a project with the following directory structure：
pages
 |--index.html
js
 |----webcore.js
 |----webcore.data
When I start the index.htlm，the webcore.js will load the webcore.data file from the ‘pages’ directory。How can I redefine the directory to the ‘js’ directory？

**Comment by kripken** [comment]
I think [locateFile](https://emscripten.org/docs/api_reference/module.html#Module.locateFile) can help with this.

**Comment by lokpoi888** [comment]
where shall I white the locateFile？ In the webcore.js file？

**Comment by kripken** [comment]
It depends on your project. If the HTML defines the Module object, then there. Otherwise, a pre-js in the js file probably. (The test suite has various examples, can search to find concrete working code samples there.)

**Comment by askuri** [comment]
> I have a project with the following directory structure：
> pages
> |--index.html
> js
> |----webcore.js
> |----webcore.data
> When I start the index.htlm，the webcore.js will load the webcore.data file from the ‘**pages**’ directory. How can I redefine the directory to the ‘js’ directory？

I can confirm that emscripten tries to look for the .data file in the same directory as the html file. However, that is against what is written in the [documentation](https://emscripten.org/docs/porting/files/packaging_files.html#changing-the-data-file-location): *By default, the .data file containing all the preloaded files is loaded from the same URL as your **.js** file*

Additionally, using locateFile as suggested by @kripken doesn't seem to work for .data files. I have created a sample to reproduce the behaviour: [emscripten-preload-file.zip](https://github.com/emscripten-core/emscripten/files/4668783/emscripten-preload-file.zip).

# Steps to reproduce
* Run `emcmake cmake .`
* Run `emmake make test`
* emrun, open a browser, open /test/index.html

In the JS console, you will first find the output `test.wasm` which comes from pre-js.js. That includes the locateFile code, outputting the path for every call of locateFile. Seeing at least test.wasm in the console shows that the code works. However, I would expect to also see test.data in the console as an indicator, that locateFile is also called for test.data. That is not the case.

# Conclusion
I see two problems here: first, the default location of .data is expected to be next to the html file, which doesn't match what the documentation is saying. Secondly, locateFile is not called for .data files.

Environment
Kubuntu 19.20, Firefox 76.0.1
emcc -v:
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.16
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 3774bcf9f84520a8c35bf765d9a528040d68a14b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/martin/Apps/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
```

**Comment by kripken** [comment]
Thanks @askuri , those do sound like bugs we should fix.

Would you like to open a PR perhaps? If you're not sure where to fix things, even a PR that adds tests for this would greatly help speed things up (I would run the test, see where it breaks, and fix it).

A possible place to add testing is in `tests/test_browser.py` in `test_locate_file`. Or perhaps a new test right after it if there isn't a natural place inside.
