### ISSUE TITLE
error on undefined `main` symbol by default

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#9640]
Currently emscripten tries to make the `main` symbol optional, so that some programs (in particular library that export functions but have no entry point) can be built with no `main` all.

While this feature is convenient if make the code in emscripten more complicated since there is no way to know ahead of time (before linking) if a program has an entry point or not.   In particualar there are two places in the codebase were we try to detect if `main` is present.  The first is `HAS_MAIN` in jsifier, and the second is `Building.link_lld`.   In both cases we get false positives because `main` is often in EXPORTED_FUNCTIONS even when there is no main.

My proposed solution is to force such users to pass a certain link flag (e.g. `-mno-entry` or `-fno-entry`) which will allow emscripten to know what type of program is being built.

**Comment by sbc100** [comment]
The cost here is that some users will see `undefined symbol: main` in their builds and be forces to add `-fno-entry`.

**Comment by sbc100** [comment]
See #9635

**Comment by parksj10** [comment]
@sbc100 I'm getting a main export error:

`error: undefined symbol: main`

with the following code:
```
#undef __APPLE__ // https://github.com/microsoft/vscode-cpptools/issues/1083#issuecomment-338499236
#include <emscripten/bind.h>
#include "lttb.hpp"

using namespace emscripten;

struct DataPoint
{
  float x;
  float y;
};

void readData(DataPoint in[], int data_length, float *x, float *y)
{
  for (int i = 0; i < data_length; i++)
  {
    in[i].x = x[i];
    in[i].y = y[i];
  }
}

void lttb(float *x, float *y, int data_length, int max_points, float *downsampled_x, float *downsampled_y)
{
  using PointLttb = LargestTriangleThreeBuckets<DataPoint, float, &DataPoint::x, &DataPoint::y>;

  DataPoint in[data_length];
  readData(in, data_length, x, y);
  DataPoint out[max_points];
  PointLttb::Downsample(in, data_length, out, max_points);
  *downsampled_x = out[0].x;
  *downsampled_y = out[0].y;
  return;
}

int main()
{
  return 0;
}

EMSCRIPTEN_BINDINGS(lttb_module)
{
  function("lttb", &lttb, allow_raw_pointers());
}
```

and the following compiling options:

```
rm lttb.wasm
emcc ./lttb.cpp \
  --bind \
  --optimize=3 \
  -Wl,--export-all \
  -Wl,--no-entry \
  -Wl,--allow-undefined \
  -s ALLOW_MEMORY_GROWTH=1 \
  -o lttb.wasm
```

Is this related or another silly error on my part?
