### ISSUE TITLE
glVertexAttribIPointer cause javascript function undefined error

### ISSUE THREAD

**Issue by eminor1988** [emscripten-core/emscripten#9650]
Sorry about bad English.

I ported my game engine to web (WebAssembly and WebGL 2.0).
I got a thrown Javascript exception from function - "_glVertexAttribIPointer" (calling glVertexAttribIPointer in my program).

**The exception message from Chrome is:**
exception thrown: TypeError: Cannot read property '10' of undefined,TypeError: Cannot read property '10' of undefined.

**And screenshot:**
![image](https://user-images.githubusercontent.com/3272005/66887764-9e722580-f00e-11e9-8f40-c2e8f51ee11b.png)

And I noticed those code in area of red rectangle of above image.
The variable "cb" is unused, so I deleted the code of whole part of red rectangle area and run my game engine on browser again, then everything is just fine.

I believe the code in red rectangle area is legacy code, but I'm not sure how to fix it in right way.
So I just report it

Thanks.

**Comment by kripken** [comment]
Thanks @eminor1988!

Reading that code, it looks like the failing line is included if you build with `FULL_ES3`, and it depends on `clientBuffers` which are set up if `FULL_ES2` is defined. So building with just 3 but not 2 can cause that crash. Maybe that's it?

If that's so, then perhaps `FULL_ES3` should automatically turn on `FULL_ES2`? Or maybe that line should only be included if both 2 and 3 are enabled? I don't know enough about ES2/ES3, cc @juj @kainino0x

**Comment by kainino0x** [comment]
It definitely makes sense to me to turn on FULL_ES2 if using FULL_ES3. It may be technically possible to separate them but I don't think there is any benefit to maintaining the extra configuration.

**Comment by Green-Sky** [comment]
I just had the same problem. Enabling `FULL_ES2` fixed it for me, but stating this nowhere else is kind of a problem...

**Comment by Green-Sky** [comment]
thanks :smile:
