### ISSUE TITLE
Embind fail when `MAIN_MODULE=1`

### ISSUE THREAD

**Issue by Keillion** [emscripten-core/emscripten#9658]
Hi, 
I have trouble using `EMSCRIPTEN_BINDINGS` with `MAIN_MODULE=1`.
A simple code modified from embind tutorial:
```
// mainModule.cpp
#include <emscripten/emscripten.h>
#include <emscripten/bind.h>
using namespace std;
using namespace emscripten;

EMSCRIPTEN_KEEPALIVE
float lerp(float a, float b, float t) {
    return (1 - t) * a + t * b;
}

EMSCRIPTEN_BINDINGS(my_module) {
    emscripten::function("lerp", &lerp);
}
```
```
// compile command
./em++ -O0 -s MAIN_MODULE=1 -s EXPORT_ALL=1 -s WASM=1 -s ABORTING_MALLOC=0 -s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=1 -s --bind -std=c++11 -o ~/mainModule.js ~/mainModule.cpp
```
Compile pass, but it reports `BindingError: No dynCall invoker for signature: fifff` in browser. It might be the same problem as #6362. I use 1.38.45 upstream (llvm backend). What is the correct way to not `dce` embind?

The latest version is 1.38.48, I'm downloading it and going to try it tomorrow.

Thanks very much.

====eidt 20191017====

I have tested 1.38.48 upstream. Still BindingError.

**Comment by kripken** [comment]
Thanks @Keillion , I can reproduce this locally. It happens on both fastcomp and upstream, so it may be a long-standing bug with embind not being compatible with MAIN_MODULE.

Not sure if the issue is more embind-related or dynamic linking related, but I guess the first question is what that `BindingError` means. @jgravelle-google do you know?

**Comment by Keillion** [comment]
There is a walkaround. Use webidl instand. 
I'm not sure how to export a static function of a class, not exist in [webidl tutorial](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html). 
I try to add `static`, but `webidl_binder.py` just ignore it and treat it as a member function.

Now I modify the automatically generated glue-cpp. Use member function as static function to let it work. It could be a temporary solution.
```
int EMSCRIPTEN_KEEPALIVE emscripten_bind_Test2_test_1(Test2* self, float val) {
  //return self->test(val); // comment out the automatically generated code

  return Test2::test(val); // use the static one
}
```

Hope it will help guys having the same problem.
