### ISSUE TITLE
How to pass -s arguments to emmake

### ISSUE THREAD

**Issue by GeometricAlgorithm** [emscripten-core/emscripten#9668]
I have done exhaustive online searching, but I still cannot figure out how to pass the `ALLOW_MEMORY_GROWTH=1` option to `emmake make`

Here is a list of commands I have tried:

`emmake make VERBOSE=1 -s ALLOW_MEMORY_GROWTH=1`
`emmake -s ALLOW_MEMORY_GROWTH=1 make VERBOSE=1`

I have also tried to use `emconfigure` to pass the argument in:

`emconfigure cmake . -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=0 -s ALLOW_MEMORY_GROWTH=1`
`emconfigure cmake . -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=0 -DALLOW_MEMORY_GROWTH=1`

Any help would be greatly appreciated.

**Comment by kripken** [comment]
`emmake` is just a wrapper around the command it runs, so `emmake make` calls `make` but also sets some env vars. So the question is how to get `make` to notice those flags. That may involve adding the Makefile (or earlier, changing how you call `configure` to pass it some cflags).

There is also the env var `EMCC_CFLAGS` which can be used in cases where you can't figure out the Makefile ;) `EMCC_CFLAGS="-s ALLOW_MEMORY_GROWTH" emmake make` will add that flag to each emcc invocation that happens.

**Comment by sbc100** [comment]
Yes, one fairly standard way do this would be `emake CFLAGS=<..> LDFLAGS=<..>`

Please avoid using `EMCC_CFLAGS` if you possible can, that a non-standard, and has non-local effects on the build.  Hopefully it can go away one day.

**Comment by GeometricAlgorithm** [comment]
Y'all rock! Thank you!

My issue has been resolved.
