### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

### ISSUE THREAD

**Issue by vasanthhr** [emscripten-core/emscripten#9669]
Hello Team,

I installed Cmake version 3.10.2 and Emscrippten(1.38.48).

I am trying to build cpp file and set the CmakeList.txt file as below:

```
set(project "Alignment")
set( CMAKE_TOOLCHAIN_FILE /home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake)
project(${project})
# Use C++ 11 by default
set( CMAKE_CXX_STANDARD 11 )
cmake_minimum_required(VERSION 3.12)
```

But getting the below error and same screenshot is attched when i run Cmake.

```
CMake Error at /home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake:105 (message):
  Failed to fetch compiler version information with command
  "'/home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/emcc' -v"!
  Process returned with error code 126.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:4 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

```
![post1](https://user-images.githubusercontent.com/20619142/67067511-99af8d80-f144-11e9-9917-d78ab046e7e2.png)

**Comment by sbc100** [comment]
Looks like you need to install a build tools such as "make" or "ninja"
on your system.   If are you on a debian or ubuntu derived system you
can just do `apt-get install make`.   Or better still `apt-get install
build-essential` as there are probably other things you are missing
too.

**Comment by sbc100** [comment]
It also looks like `emcc -v` didn't succeed.   What does running
`'/home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/emcc -v
` produce on your system?

**Comment by vasanthhr** [comment]
Hello ,

Issue got fixed, i set python path properly. 

Later emcc  -v worked well.

**Comment by Grimvale96** [comment]
I hate people that just say "it works now bye" like, tell us wtf you did?

**Comment by SwatiModi** [comment]
https://stackoverflow.com/a/56029320/8463170

**Comment by SwatiModi** [comment]
https://stackoverflow.com/a/58984024/8463170

**Comment by midzer** [comment]
```
CMake Error at /usr/share/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'/usr/share/emscripten/emcc' -v"! Process returned with error code No such
  file or directory.
```
I've installed emscripten via debian packages.

Running `/usr/share/emscripten/emcc -v` does not compute. But `/usr/share/emscripten/emcc.py -v` does!

Although `which emcc` gives me: `/usr/bin/emcc` <- I wonder why this path is not used?!

So, I've fixed this by setting

https://github.com/emscripten-core/emscripten/blob/81106e2f283595da4d0741c51487ec6d0970d8d0/cmake/Modules/Platform/Emscripten.cmake#L86

to `set(EMCC_SUFFIX ".py")`

**Comment by sbc100** [comment]
Sounds like an issue with the downstream debian package.   Can you open a bug there?

As a user of the toolchain you should always be running `emcc` and not `emcc.py` (which is kind of an implementation detail).

**Comment by aisnote** [comment]
I am in Ubuntu and also meet this same issue on emcc 2.0.10. 

`
CMake Error at /home/%user%/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:131 (message):
  Failed to fetch compiler version information with command
  "'/home/%user%/emsdk/upstream/emscripten/emcc' -v"! Process returned with
  error code 1.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:3 (project)
`

But run:  **'/home/%user%/emsdk/upstream/emscripten/emcc' -v** got right version.

![image](https://user-images.githubusercontent.com/1201634/208822759-5c8c7919-c6d5-4f72-ab61-a1d254e3253c.png)

**Comment by timmeh87** [comment]
Guys, I am here because google takes me here for the general error "CMAKE_MAKE_PROGRAM not set" even though its not related to emscripten.

Anyways, It was not working for me even though I swear it worked *yesterday*, other fixes didnt work, yadda yadda. I was able to solve the issue by running as root. I guess I rooted some folders in the build or something because root does not have CMAKE_MAKE_PROGRAM explicitly defined either . No time to worry about it, as usual I just gotta sudo my way past confusing linux permissions scenarios, thanks linus.

**Comment by jamierpond** [comment]
> Looks like you need to install a build tools such as "make" or "ninja" on your system. If are you on a debian or ubuntu derived system you can just do `apt-get install make`. Or better still `apt-get install build-essential` as there are probably other things you are missing too.
> […](#)
> On Thu, Oct 17, 2019 at 10:16 PM Vasantha HR ***@***.***> wrote: Hello Team, I installed Cmake version 3.10.2 and Emscrippten(1.38.48). I am trying to build cpp file and set the CmakeList.txt file as below: set(project "Alignment") set( CMAKE_TOOLCHAIN_FILE /home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake) project(${project}) # Use C++ 11 by default set( CMAKE_CXX_STANDARD 11 ) cmake_minimum_required(VERSION 3.12) But getting the below error and same screenshot is attched when i run Cmake. CMake Error at /home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake:105 (message): Failed to fetch compiler version information with command "'/home/vasanthahr/code/C_Cplus_code/emsdk/fastcomp/emscripten/emcc' -v"! Process returned with error code 126. Call Stack (most recent call first): /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include) CMakeLists.txt:4 (project) CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool. -- Configuring incomplete, errors occurred! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You may well be looking for `sudo apt install make`

**Comment by naih222** [comment]
cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_GPU=CUDA -DGMX_MPI=ON -DGMX_USE_PLUMED=ON
I am trying to compile plumed to gromacs with this command; CMake Error in /data1/naih222/gromacs-2023.3/build/CMakeFiles/CMakeTmp/CMakeLists.txt:

But I got this error below, please can anyone help with a guide?

  Target "cmTC_c06ab" requires the language dialect "CXX17" .  But the
  current compiler "GNU" does not support this, or CMake does not know the
  flags to enable it.


CMake Error at /usr/local/share/cmake-3.23/Modules/FindOpenMP.cmake:217 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.23/Modules/FindOpenMP.cmake:462 (_OPENMP_GET_FLAGS)
  cmake/gmxManageOpenMP.cmake:41 (find_package)
  CMakeLists.txt:381 (include)

**Comment by sbc100** [comment]
@naih222 that looks like a completely different issue to me, unless I'm missing something?

**Comment by naih222** [comment]
> @naih222 that looks like a completely different issue to me, unless I'm missing something?

May be a completely different issue though. this is about the closest thread to the error I am facing, any idea on going forward?

**Comment by sbc100** [comment]
Please open another issue.  I've never seen the `requires the language dialect "CXX17"` error message before but it seem odd since we support CXX all the way up to CXX20.    Are running via `emcmake`?  If not how are you including the emscripten toolchain?
