### ISSUE TITLE
How to generate typescript typings from WebIDL

### ISSUE THREAD

**Issue by giniedp** [emscripten-core/emscripten#9674]
I am new to emscripten and curious about how people generate d.ts files for 3rd party C++ libraries where nbind or mbind is not an option.

A couple of weeks ago i have written an `WebIDL` -> `d.ts` converter specifically for ammo.js

- https://github.com/giniedp/ammojs-typed
- https://github.com/kripken/ammo.js/issues/233

Before doing that i was looking for an existing `WebIDL` -> `d.ts` conversion tool but could not find any complete solution. The closest i could find was

- https://github.com/Microsoft/dts-gen which generates `d.ts` from any `js` library, so this has incomplete type definitions with lots of `any`
- https://github.com/microsoft/TSJS-lib-generator which is a project dedicated to DOM apis and not really a tool in my sense

so i am left with these questions

1. is there a `WebIDL` -> `d.ts` converter outside of emscripten that i have overseen?
2. is such tool desired for emscripten (or maybe already exists)?
3. should such a tool be part of emscripten or should it be a standalone project

**Comment by kripken** [comment]
I don't think there is one. I think it could be useful! And yes, would be good to have it in emscripten itself.

**Comment by tchakabam** [comment]
@giniedp I have understood you built it yourself? :)  https://github.com/giniedp/webidl2ts

**Comment by giniedp** [comment]
> @giniedp I have understood you built it yourself? :) https://github.com/giniedp/webidl2ts

yes, i did. But haven't worked on that topic for a while now.

**Comment by diegosogari** [comment]
I'm fidgeting with the idea of developing a Clang plugin for generating interface files from C++ headers. The choice of files would be:

- `.idl` (Web IDL)
- `.wit` (Wasm Interface Type)
- `.d.ts` (TypeScript declaration)

Of course, only the C++ features that have a direct mapping to the concepts in each of these formats would be supported.

Any thoughts?

**Comment by isaac-mason** [comment]
JoltPhysics.js and recast-navigation-js are using a fork of @giniedp's webidl2ts: https://github.com/pmndrs/webidl-dts-gen

We've stumbled through adding fixes aligning generated types with the output of the webidl binder, most recently generating types with inheritance for JSImplementation. @giniedp if you're still involved in webidl2ts we can upstream the improvements.


Like webidl2ts, webidl-dts-gen still has an emscripten an non-emscripten mode, but I'm really only supporting it for usage with emscripten.

I'm also keen to help improve the typescript story for webidl itself, but I'm lacking in direction 😅
