### ISSUE TITLE
[SIMD] error result of Integer to integer narrowing

### ISSUE THREAD

**Issue by zhlwang** [emscripten-core/emscripten#9679]
When testing the SIMD code of integer to integer narrowing as following

        
	i16x8 h = {61, 38, -18, 23, 6, 30, 37, 33};

     i16x8 g = {5, -5, -5, -5, -8, -5, 5, -5};

	u8x16 dst = __builtin_wasm_narrow_u_i8x16_i16x8(g, g);

	printf("%d, %d, %d, %d, %d, %d, %d, %d\n", dst[0],dst[1],dst[2],dst[3],dst[4],dst[5],dst[6],dst[7]);

	dst = __builtin_wasm_narrow_s_i8x16_i16x8(h, h);

	printf("%d, %d, %d, %d, %d, %d, %d, %d\n", dst[0],dst[1],dst[2],dst[3],dst[4],dst[5],dst[6],dst[7]);

The result is as following, it seems different with expected. 
5, 0, 0, 0, 0, 0, 5, 255
61, 38, 238, 23, 6, 30, 37, 33

**Comment by tlively** [comment]
@zhlwang can you post the typedefs your are using to get `i16x8` and the other vector types? In general I also recommend using the intrinsics defined in the `wasm_simd128.h` header rather than using clang builtin functions: https://github.com/emscripten-core/emscripten/blob/incoming/system/include/wasm_simd128.h.

**Comment by zhlwang** [comment]
Here is the tyepdefs
```
typedef uint8_t u8x16 __attribute__((__vector_size__(16)));
typedef int16_t i16x8 __attribute__((__vector_size__(16)));
```

**Comment by tlively** [comment]
When I compile and run this code I get the following output:
```
5, 255, 255, 255, 255, 255, 5, 255
61, 38, 238, 23, 6, 30, 37, 33
```
Perhaps the version of V8 you're running on is out of date?

**Comment by zhlwang** [comment]
according the definition:  The signed narrowing operation will use signed saturation to handle overflow, 0x7f or 0x80 for i8x16, the unsigned narrowing operation will use unsigned saturation to handle overflow, 0x00 or 0xff for i8x16. Regardless of the whether the operation is signed or unsigned, the input lanes are interpreted as signed integers.
The expected result is 
```
5, 0, 0, 0, 0, 0, 5, 0
61, 38, -18, 23, 6, 30, 37, 33
```
I am working on master branch of v8 on Ubuntu, and the version is _V8 version 8.0.0 (candidate)_
The output is as following, the same result in chrome canary 80.0.3951.0(64 bit) 
```
5, 0, 0, 0, 0, 0, 5, 255
61, 38, 238, 23, 6, 30, 37, 33
```

**Comment by tlively** [comment]
Ah, you're right. Here is the V8 bug tracking this issue: https://bugs.chromium.org/p/v8/issues/detail?id=9729.

**Comment by tlively** [comment]
I'm going to close this because Emscripten and the rest of the tools are behaving correctly here.

**Comment by zhlwang** [comment]
OK, thanks to your quick reply. I'll track the issue on V8 bug system.
