### ISSUE TITLE
emscripten_set_pointerlockchange_callback not working

### ISSUE THREAD

**Issue by caiiiycuk** [emscripten-core/emscripten#9681]
Hi. I am trying to use pointer lock api from html5.h to implement mouse locking in js-dos. I can lock/unlock mouse with this API but I never get notified about status updates. Simple testcase:

```
#include <emscripten/html5.h>
#include <emscripten/emscripten.h>
#include <cstdio>
#include <stdlib.h>

void loop() {
    EmscriptenPointerlockChangeEvent lastChangeEvent;
    auto haveLockInfo = emscripten_get_pointerlock_status(&lastChangeEvent) == EMSCRIPTEN_RESULT_SUCCESS;
    if (!haveLockInfo) {
        printf("Can't get pointer lock info\n");
        abort();
    }

    printf("Is locked? %s\n", lastChangeEvent.isActive ? "true" : "false");
}

int main(int argc, char** argv) {
    emscripten_set_mousedown_callback("#canvas", NULL, false, [](int eventType, const EmscriptenMouseEvent *mouseEvent, void *userData) {
	printf("noop callback\n");
        return 0;
    });

    auto pointerLockChangeSet = emscripten_set_pointerlockchange_callback("#canvas", NULL, true, 
    [](int eventType, const EmscriptenPointerlockChangeEvent *pointerlockChangeEvent, void *userData) -> EM_BOOL {
        printf("Received pointer lock change event\n");
        return true;
    }) == EMSCRIPTEN_RESULT_SUCCESS;
    printf("pointerlock callback set? %s\n", pointerLockChangeSet ? "true" : "false");

    auto lockRequested = emscripten_request_pointerlock("#canvas", true) == EMSCRIPTEN_RESULT_DEFERRED;
    printf("lockrequested? %s\n", lockRequested ? "true" : "false");

    emscripten_set_main_loop(loop, 1, false);
    return 0;
}
```

Compile it with: `emcc -std=c++11 pointerbug.cpp -o pointerbug.html`

I expect to see:
```
pointerlock callback set? true
lockrequested? true
Is locked? false
/* CLICK  IN CANVAS */
noop callback
Is locked? true
Received pointer lock change event
Is locked? true
...
```

What I see:
```
pointerlock callback set? true
lockrequested? true
Is locked? false
/* CLICK  IN CANVAS */
noop callback
Is locked? true
Is locked? true
```

Callback is never called for me. Don't understand why, everything looks correct.

--
emcc (Emscripten gcc/clang-like replacement) 1.39.0 (commit
e047fe4c1ecfae6ba471ca43f2f630b79516706b)
Related to: https://groups.google.com/forum/#!topic/emscripten-discuss/CNxCC0ZiUzc

**Comment by ZaDarkSide** [comment]
Yes, please can we get to the bottom of this? I'm experiencing the same issue.

**Comment by caiiiycuk** [comment]
If I am not wrong pointer change event/pointer error event is dispatched only to **document**.
So, `emscripten_set_pointerlockchange_callback` should not take target element as first argument. 
And if I am not wrong null element is defaulted to '#canvas' that incorrect for this event type.

Fixing this line will fix test code:
```
auto pointerLockChangeSet = emscripten_set_pointerlockchange_callback("#document", NULL, true,
```

I think there is 3 ways to fix this issue:

1. Remove first argument for register callback functions in pointer lock api, but it's breaking change. 2. Change documentation and add warning if target is not document.
3. use document to register listener (no matter what you pass), but filter events based on target element in handler function (not sure that this will work).

Want to preapare PR, which way you prefer @kripken ?

--
from MDN
![image](https://user-images.githubusercontent.com/1727152/67412628-d3234580-f5e9-11e9-9ee3-74f4dcfe9c51.png)

**Comment by kripken** [comment]
Sorry for the delay in responding! Thanks for looking into this @caiiiycuk, yeah, that makes sense. I think option 2 is best, but maybe it could even be an error instead of a warning there.

The reason I'd rather not add a new API without the target parameter is that I think we may need multiple targets eventually (for multiple windows). Not sure about that, but I'd rather not change the API for now.

**Comment by simonmeusel** [comment]
Hi

I'm getting an error with the following code:

```
printf("%i\n", emscripten_set_pointerlockchange_callback(
                           "#document", NULL, true,
                           [](int eventType,
                              const EmscriptenPointerlockChangeEvent
                                  *pointerlockChangeEvent,
                              void *userData) -> EM_BOOL {
                               printf("Received pointer lock change event\n");
                               return true;
                           }));
```

It prints: `-4` which is `EMSCRIPTEN_RESULT_UNKNOWN_TARGET`. When the pointer lock gets activated I never get ´Received pointer lock change event´. I'm requesting the pointer lock through external JS when the user clicks.

I have tried executing the code in the main and after one second (after a few rendered frames).

For context: I have a WebGL project involving a canvas with a pointer lock.

I'm compiling with `emcc -std=c++17 -Wall -s ALLOW_MEMORY_GROWTH=1 -s ASYNCIFY -s FULL_ES2=1 -I"/usr/local/Cellar/glm/0.9.9.5/include/" src/*.cpp -O2 -o dist/engine.js`

Firefox even shows the attached event, but the callback never gets called:

![Screenshot 2020-01-31 at 01 20 43](https://user-images.githubusercontent.com/16321843/73502047-a25c6480-43bf-11ea-9542-a15e5d841f84.png)

Also tested in Chrome. Attaching a event handler with JS works.

Any idea what could cause it?

**Comment by falkTX** [comment]
issue is still present on latest emscripten

**Comment by woxels** [comment]
> To add some details here, I am using
> 
> ```
> emscripten_set_pointerlockchange_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, ...);
> ```
> 
> and this works on firefox, the callback is triggered as expected. does not work on chrome based browsers, didnt try webkit/safari as it does not support simd yet so it is not very useful.
> 
> what I did for now as workaround (same as mentioned on this ticket before) is to query the pointerlock status on every mouse event, ugly but does indeed work.
> 
> ```
>   EmscriptenPointerlockChangeEvent e;
>   if (emscripten_get_pointerlock_status(&e) == EMSCRIPTEN_RESULT_SUCCESS)
>       isPointerLocked = e.isActive;
> ```

that worked for me, thanks!

**Comment by donthomasitos** [comment]
> and this works on firefox, the callback is triggered as expected. does not work on chrome based browsers, didnt try webkit/safari as it does not support simd yet so it is not very useful.

It works for me on Chrome too (Linux), so maybe the issue can be closed.

**Comment by sbc100** [comment]
Sounds good.  Please re-open if `emscripten_set_pointerlockchange_callback` is still not working on chrome.
