### ISSUE TITLE
C++ exceptions thrown in SIDE_MODULES not caught (by other modules?)

### ISSUE THREAD

**Issue by johnwason** [emscripten-core/emscripten#9691]
I am using the Pyodide project with Emscripten to compile a C++ Python library for use in the browser. I have found that exceptions are working sometimes, but other times they are not caught correctly and filter back to Python instead. If the `throw` and `catch` are in the same function, it seems to work correctly. If they are in different functions, it is not caught. Because of the use of Boost and CMake the module has to be built separately, so it is possible. I haven't found the magic combination of compiler flags to make it work. Pyodide is using side modules with dynamic loading. I looked through the generated wasm text code and the exception checks were being generated.

The original issue with more details can be found here:

https://github.com/iodide-project/pyodide/issues/545

Test case: 

https://gist.github.com/johnwason/422b0bd9787088db3d12b422a6a835ff

**Comment by kripken** [comment]
`-s EXCEPTION_DEBUG` may help debug this, it will print some logging on each throw and catch etc. Specifically, I'd look at a full stack trace (in a build with `--profiling`) when it throws an exception you want to be caught (that option may already print the stack trace, if not, I'd just add `console.log(new Error().stack)` there). Then you can look up the stack to see if the expected catch is there, and if there's anything in the middle.

If you get stuck, I can take a look at such a build that's instrumented to show the stack trace etc.

**Comment by johnwason** [comment]
I have `-s EXCEPTION_DEBUG=1` set but it didn't seem to do anything. See my build.sh file in the gist like above.

**Comment by kripken** [comment]
I see it on `SIDE_C_FLAGS`, is that just for the side module? Side modules don't have any JS for that to effect, the option would need to be on main program.

(Btw, exceptions would need to be enabled on both the side module and the main program, if one wants to catch an exception from the other, but I think that's not the issue here from the description.)

**Comment by johnwason** [comment]
The main compilation is done by the Pyodide build scripts which download and build everything at once. This module is compiling against the environment Pyodide sets up.

The exceptions are all caught within the module so I don't think them leaking into the main module is the issue. Do I need to compile the main module with exceptions as well?

**Comment by johnwason** [comment]
That makes sense. I will go through the (rather convoluted) build system in Pyodide and see if I can build with exceptions enabled. Thanks!

**Comment by kripken** [comment]
Cool, let me know what you find!

Btw, it looks like we should already print a clear error, "Exception catching is disabled, this exception cannot be caught" if the main module is built without exceptions. So I'm surprised you didn't see that. Perhaps it is already built with exceptions?

**Comment by johnwason** [comment]
Would that message be shown during compilation or runtime?

**Comment by johnwason** [comment]
Ok, I rebuilt the main module with the following output:

```
em++ -s EXPORT_NAME="'pyodide'" -o build/pyodide.asm.html src/main.bc src/jsimport.bc src/jsproxy.bc src/js2python.bc src/pyimport.bc src/pyproxy.bc src/python2js.bc src/python2js_buffer.bc src/runpython.bc src/hiwire.bc \
  -O3 -s MODULARIZE=1 cpython/installs/python-3.7.0/lib/libpython3.7.a lz4/lz4-1.8.3/lib/liblz4.a -s "BINARYEN_METHOD='native-wasm'" -s TOTAL_MEMORY=1073741824 -s ALLOW_MEMORY_GROWTH=1 -s MAIN_MODULE=1 -s EMULATED_FUNCTION_POINTERS=1 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s EXPORTED_FUNCTIONS='["___cxa_guard_acquire", "__ZNSt3__28ios_base4initEPv"]' -s WASM=1 -s SWAPPABLE_ASM_MODULE=1 -s USE_FREETYPE=1 -s USE_LIBPNG=1 -std=c++14 -Lcpython/build/sqlite-autoconf-3270200/.libs -lsqlite3 cpython/build/bzip2-1.0.2/libbz2.a -lstdc++ --memory-init-file 0 -s "BINARYEN_TRAP_MODE='clamp'" -s TEXTDECODER=0 -s LZ4=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXCEPTION_DEBUG=1 -s FORCE_FILESYSTEM=1
emcc: warning: cannot represent a NaN literal '0x555a9590bca0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
  in   %spec.select = select i1 %2, double 0x7FF8000000000000, double 0xFFF8000000000000 in _Py_dg_stdnan() 
rm build/pyodide.asm.html
```
This is the web console output I see when I run the module:

```
Python initialization complete
pyodide.asm.js:8:57200
Loading pyodide_exception_test_module from default channel
pyodide_dev.js:129:9
Loading numpy from default channel
pyodide_dev.js:129:9
Running test 0!
pyodide.asm.js:8:57200
Throw Exception!
pyodide.asm.js:8:57200
Compiled code throwing an exception, 11149552,2533368,16392
pyodide.asm.js:8:51362

```
Here is the wast file: https://gist.github.com/johnwason/bb0a530f41671a25e8d7760e0e9e63e3

**Comment by kripken** [comment]
The error should be shown at runtime. Strange you don't see it. What emscripten version was it built with?

Is that pasted output what you'd expect? Or is it still showing a problem? If it is, then I'd recommend as earlier to get a stack trace and investigate that.

**Comment by johnwason** [comment]
Emscripten version for Piodide is 1.38.30. There appears to be work to update the version but currently it is fixed to that version.

The out put should say: "Running test 0", "Throw Exception!", "Caught std::exception!", and then pass the exception back to Python. Currently I am not seeing "Caught Exception" or receiving an error in Python. If I throw an exception directly within the `try` block, it works. If I throw an exception in a function it is not caught by the enclosing `catch` block.

I will try enabling profiling and reply with the output.

**Comment by johnwason** [comment]
I wasn't able to get a stack trace or see anything useful in profiling. I am only seeing the small main module in the debugger in Firefox and none of the side modules. The exception seems to fall out of web assembly as soon as it is thrown.

**Comment by kripken** [comment]
Adding stack trace logging in `__cxa_throw` may be the simplest thing, as that is what it calls to throw.

**Comment by johnwason** [comment]
How would I add stack trace to `__cxa_throw` in firefox?

**Comment by kripken** [comment]
Something like `console.log(new Error().stack)`, pasted in the JS function.

**Comment by johnwason** [comment]
I got this adding `console.log(new Error().stack) to `__cxa_throw` in `library.js`

```
Python initialization complete
pyodide.asm.js:2731:13
Loading pyodide_exception_test_module from default channel
pyodide_dev.js:129:9
Loading numpy from default channel
pyodide_dev.js:129:9
Running test 0!
pyodide.asm.js:2731:13
Throw Exception!
pyodide.asm.js:2731:13
Compiled code throwing an exception, 8831944,2533368,16392
pyodide.asm.js:2410:7
___cxa_throw@http://localhost:8000/pyodide.asm.js:2412:19
__ZL16test_exceptions2v@http://localhost:8000/pyodide.asm.js:2603:1
byn$fpcast-emu$__ZL16test_exceptions2v@http://localhost:8000/pyodide.asm.js:3831:1
dynCall_X@http://localhost:8000/pyodide_dev.js:10006308:1
@http://localhost:8000/pyodide.asm.js:49757:60
invoke_v@http://localhost:8000/pyodide.asm.js:31519:5
__ZL15test_exceptionsP7_objectS0_@http://localhost:8000/pyodide.asm.js:2104:1
byn$fpcast-emu$__ZL15test_exceptionsP7_objectS0_@http://localhost:8000/pyodide.asm.js:3807:1
__PyMethodDef_RawFastCallKeywords@http://localhost:8000/pyodide_dev.js:1280610:1
__PyCFunction_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1280966:1
_call_function@http://localhost:8000/pyodide_dev.js:3330415:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3300137:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10097715:1
__PyEval_EvalCodeWithName@http://localhost:8000/pyodide_dev.js:3252635:1
_PyEval_EvalCode@http://localhost:8000/pyodide_dev.js:3248339:1
_builtin_eval@http://localhost:8000/pyodide_dev.js:3228481:1
byn$fpcast-emu$_builtin_eval@http://localhost:8000/pyodide_dev.js:10032166:1
__PyMethodDef_RawFastCallKeywords@http://localhost:8000/pyodide_dev.js:1279425:1
__PyCFunction_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1280966:1
_call_function@http://localhost:8000/pyodide_dev.js:3330415:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3300231:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10097715:1
_function_code_fastcall@http://localhost:8000/pyodide_dev.js:1276137:1
__PyFunction_FastCallDict@http://localhost:8000/pyodide_dev.js:1272759:1
__PyObject_FastCallDict@http://localhost:8000/pyodide_dev.js:1271603:1
_object_vacall@http://localhost:8000/pyodide_dev.js:1286996:1
_PyObject_CallFunctionObjArgs@http://localhost:8000/pyodide_dev.js:1287477:1
__runPython@http://localhost:8000/pyodide_dev.js:1059281:1
@http://localhost:8000/pyodide.asm.js:40296:64
_runpython_init_js/Module._runPythonInternal@http://localhost:8000/pyodide.asm.js:2074:94
internal@http://localhost:8000/pyodide.asm.js:2074:704
runInternal@http://localhost:8000/pyodide.asm.js:2074:1121
pyodide.asm.js:2412:7
```
After that no other exception related functions were called. It seems like the exception vanishes.

**Comment by kripken** [comment]
Ok, with that stack trace you can find out what happens, as it can only be caught in JS (not in wasm), and you can inspect each of those JS locations and see what happens in them. The likely candidates is the `invoke_v` there. Then you can add some debug logging there to see it's called, and what it does.

If the place you expect the exception to be caught is not there, that is, you find the proper function but it doesn't call an invoke and so nothing will be caught, then the question is why an invoke wasn't created. It should be created if the file is built with exceptions support, and if LLVM doesn't believe there is no way an exception can be thrown there.

**Comment by johnwason** [comment]
I am not sure how to put in the logging you suggest.

I have the .wast file. Here is the invoke call:

https://gist.github.com/johnwason/6be581c412ed72906983e77df029e2ee#file-pyodide_test_exceptions_module-wast-L344

Here is the throw:

https://gist.github.com/johnwason/6be581c412ed72906983e77df029e2ee#file-pyodide_test_exceptions_module-wast-L806

and here is where it should set the Python error and return:

https://gist.github.com/johnwason/6be581c412ed72906983e77df029e2ee#file-pyodide_test_exceptions_module-wast-L986

I don't know enough about the details of webassembly to trace the execution.

**Comment by johnwason** [comment]
Would it help if I set up a travis.ci build that you can see the entire process?

**Comment by johnwason** [comment]
I got it to work!

I built the module statically into main, and used `PyImport_AppendInittab` to load the module definition into the Python runtime. This avoids the side module and call to dlopen. The console output is now:

```
Python initialization complete
pyodide.asm.js:2738:13
Running test 0!
pyodide.asm.js:2738:13
Throw Exception!
pyodide.asm.js:2738:13
Compiled code throwing an exception, 9094848,2533400,5223
pyodide.asm.js:2417:7
___cxa_throw@http://localhost:8000/pyodide.asm.js:2419:19
__ZL16test_exceptions2v@http://localhost:8000/pyodide_dev.js:1061489:1
byn$fpcast-emu$__ZL16test_exceptions2v@http://localhost:8000/pyodide_dev.js:10085540:1
dynCall_X@http://localhost:8000/pyodide_dev.js:10007455:1
@http://localhost:8000/pyodide.asm.js:49763:60
invoke_v@http://localhost:8000/pyodide.asm.js:31521:5
__ZL15test_exceptionsP7_objectS0_@http://localhost:8000/pyodide_dev.js:1061115:1
byn$fpcast-emu$__ZL15test_exceptionsP7_objectS0_@http://localhost:8000/pyodide_dev.js:10019531:1
__PyMethodDef_RawFastCallKeywords@http://localhost:8000/pyodide_dev.js:1281602:1
__PyCFunction_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1281958:1
_call_function@http://localhost:8000/pyodide_dev.js:3331407:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3301129:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10098929:1
__PyEval_EvalCodeWithName@http://localhost:8000/pyodide_dev.js:3253627:1
_PyEval_EvalCode@http://localhost:8000/pyodide_dev.js:3249331:1
_builtin_eval@http://localhost:8000/pyodide_dev.js:3229473:1
byn$fpcast-emu$_builtin_eval@http://localhost:8000/pyodide_dev.js:10033326:1
__PyMethodDef_RawFastCallKeywords@http://localhost:8000/pyodide_dev.js:1280417:1
__PyCFunction_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1281958:1
_call_function@http://localhost:8000/pyodide_dev.js:3331407:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3301223:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10098929:1
_function_code_fastcall@http://localhost:8000/pyodide_dev.js:1277129:1
__PyFunction_FastCallDict@http://localhost:8000/pyodide_dev.js:1273751:1
__PyObject_FastCallDict@http://localhost:8000/pyodide_dev.js:1272595:1
_object_vacall@http://localhost:8000/pyodide_dev.js:1287988:1
_PyObject_CallFunctionObjArgs@http://localhost:8000/pyodide_dev.js:1288469:1
__runPython@http://localhost:8000/pyodide_dev.js:1059678:1
@http://localhost:8000/pyodide.asm.js:40302:64
_runpython_init_js/Module._runPythonInternal@http://localhost:8000/pyodide.asm.js:2074:94
internal@http://localhost:8000/pyodide.asm.js:2074:704
_runpython_init_js/Module.runPythonAsync@http://localhost:8000/pyodide.asm.js:2074:1244
term.runPython@http://localhost:8000/console.html:59:11
_hiwire_call_member@http://localhost:8000/pyodide.asm.js:2016:210
_JsBoundMethod_Call@http://localhost:8000/pyodide_dev.js:1047706:1
byn$fpcast-emu$_JsBoundMethod_Call@http://localhost:8000/pyodide_dev.js:10019518:1
__PyObject_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1278931:1
_call_function@http://localhost:8000/pyodide_dev.js:3331729:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3301129:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10098929:1
_function_code_fastcall@http://localhost:8000/pyodide_dev.js:1277129:1
__PyFunction_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1279454:1
_call_function@http://localhost:8000/pyodide_dev.js:3331717:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3301112:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10098929:1
__PyEval_EvalCodeWithName@http://localhost:8000/pyodide_dev.js:3253627:1
__PyFunction_FastCallKeywords@http://localhost:8000/pyodide_dev.js:1279593:1
_call_function@http://localhost:8000/pyodide_dev.js:3331717:1
__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:3301112:1
byn$fpcast-emu$__PyEval_EvalFrameDefault@http://localhost:8000/pyodide_dev.js:10098929:1
_function_code_fastcall@http://localhost:8000/pyodide_dev.js:1277129:1
__PyFunction_FastCallDict@http://localhost:8000/pyodide_dev.js:1273751:1
__PyObject_FastCallDict@http://localhost:8000/pyodide_dev.js:1272595:1
__PyObject_Call_Prepend@http://localhost:8000/pyodide_dev.js:1284900:1
_method_call@http://localhost:8000/pyodide_dev.js:1291390:1
byn$fpcast-emu$_method_call@http://localhost:8000/pyodide_dev.js:10021519:1
_PyObject_Call@http://localhost:8000/pyodide_dev.js:1282589:1
__pyproxy_apply@http://localhost:8000/pyodide_dev.js:1050610:1
@http://localhost:8000/pyodide.asm.js:40261:72
apply@http://localhost:8000/pyodide.asm.js:2071:2868
pushCode@http://localhost:8000/console.html:15:24
o@https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js:44:94800
T@https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js:44:95634
ENTER@https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js:44:31594
We@https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js:44:48580
dispatch@https://code.jquery.com/jquery-latest.js:4640:15
add/elemData.handle@https://code.jquery.com/jquery-latest.js:4309:6
pyodide.asm.js:2419:7
can_catch on 9094848
pyodide.asm.js:2394:7
  can_catch found 9094848,2533256
pyodide.asm.js:2405:11
cxa_get_exception_ptr 9094848
pyodide.asm.js:2328:7
cxa_begin_catch 9094848,stack,9094848
pyodide.asm.js:2281:5
addref 9094848
pyodide.asm.js:2246:9
cxa_end_catch popped 9094848,9094848,stack,
pyodide.asm.js:2307:7
decref 9094848
pyodide.asm.js:2251:9
decref freeing exception 9094848,9094848,stack,
pyodide.asm.js:2265:11
Caught std::exception!Python exception:
pyodide.asm.js:2738:13
Traceback (most recent call last):
pyodide.asm.js:2738:13
  File "/lib/python3.7/site-packages/pyodide.py", line 44, in eval_code
pyodide.asm.js:2738:13
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
pyodide.asm.js:2738:13
  File "<eval>", line 1, in <module>
pyodide.asm.js:2738:13
RuntimeError: Caught std::exception!
```

This suggests that there is a problem with exceptions thrown in side modules. For my purposes statically liking in the module is fine, so feel free to close the issue.

**Comment by kripken** [comment]
It would still be good to fix this issue, even if you have a workaround. But we should try to get a small as possible testcase for that I guess, if no one is going to debug the pyodide one. I'll rename this issue.

(For adding logging, I meant in the JS file.)

**Comment by waterlike86** [comment]
@kripken  I think i have a test app. cause we seem to be facing this on 1.39.7-fastcomp as well.
[side_exception.zip](https://github.com/emscripten-core/emscripten/files/4243850/side_exception.zip)

**Comment by kripken** [comment]
@waterlike86 that sounds odd - not sure how a C++ exception could end up as a wasm RuntimeError. Perhaps a stack trace shows something for you?

**Comment by johnwason** [comment]
Has there been any progress on this issue?

**Comment by ravisumit33** [comment]
@kripken I used to add `(new Error).stack` in cxa_throw and it was working fine as was getting function indexes in the stack trace. But some recent versions of chrome have stopped displaying function indexes and only display the wasm file. However, it is still working in firefox and safari.

**Comment by johnwason** [comment]
This appears to be working now with Emscripten version 3.10.2 and `-fexceptions`.
