### ISSUE TITLE
 fatal error: 'unwind.h' file not found #include "unwind.h"

### ISSUE THREAD

**Issue by zababurinsv** [emscripten-core/emscripten#9693]
Hi 
i am compile this project  https://github.com/GoogleChromeLabs/wasm-av1.git

And i geting this error:

In file included from /home/sergey/emsdk/emscripten/incoming/system/lib/libcxxabi/src/cxa_exception_storage.cpp:14:
/home/sergey/emsdk/emscripten/incoming/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"
         ^~~~~~~~~~
In file included from /home/sergey/emsdk/emscripten/incoming/system/lib/libcxxabi/src/cxa_handlers.cpp:19:
/home/sergey/emsdk/emscripten/incoming/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"
         ^~~~~~~~~~
In file included from /home/sergey/emsdk/emscripten/incoming/system/lib/libcxxabi/src/cxa_default_handlers.cpp:19:
/home/sergey/emsdk/emscripten/incoming/system/lib/libcxxabi/src/cxa_exception.hpp:19:10: fatal error: 'unwind.h' file not found
#include "unwind.h"

SRCS=decode-av1.c

AOMDIR=third_party/aom

LIBDIR=third_party/embuild

INC=-I $(AOMDIR) -I $(LIBDIR)

X86LIBDIR=third_party/build

LIB=aom

LIBNAME=lib$(LIB).a

EMLIBAV1=$(LIBDIR)/$(LIBNAME)

X86LIBAV1=$(X86LIBDIR)/$(LIBNAME)

TARGET=decode-av1.js

TESTTARGET=testavx

DEPS=$(SRCS) Makefile

all: $(TARGET)

$(TARGET): $(DEPS) blob-api.c yuv-to-rgb.c $(EMLIBAV1)
		emcc -o $@ -O3 -s WASM=1 \
				-s ALLOW_MEMORY_GROWTH=1 \
				-s EXPORTED_FUNCTIONS="['_AVX_Decoder_new', \
										'_AVX_Decoder_destroy', \
										'_AVX_Decoder_set_source', \
										'_AVX_Decoder_run', \
										'_AVX_Decoder_get_width', \
										'_AVX_Decoder_get_height', \
										'_AVX_Decoder_video_finished', \
										'_AVX_Decoder_get_frame', \
										'_AVX_Video_Frame_get_buffer', \
										'_AVX_YUV_to_RGB', \
										'_DS_open', \
										'_DS_close', \
										'_DS_set_blob', \
										'_malloc', '_free' \
									   ]" \
				blob-api.c yuv-to-rgb.c $(SRCS) $(INC) -L $(LIBDIR) -l$(LIB)

$(TESTTARGET): test.c $(DEPS) $(X86LIBAV1)
		cc -o $@ -O3 test.c $(SRCS) $(INC) -L $(X86LIBDIR) -l$(LIB)

$(TESTTARGET)g: test.c $(DEPS) $(X86LIBAV1)
		cc -o $@ -g test.c $(SRCS) $(INC) -L $(X86LIBDIR) -l$(LIB)

clean:
		-rm $(TARGET) $(TESTTARGET) $(TESTTARGET)g

$(EMLIBAV1): $(LIBDIR)
		(cd $(LIBDIR); \
			cmake  `pwd | sed 's?$(LIBDIR)?$(AOMDIR)?'` \
		        -DENABLE_CCACHE=1 \
		        -DAOM_TARGET_CPU=generic \
		        -DENABLE_DOCS=0 \
		        -DCONFIG_ACCOUNTING=1 \
		        -DCONFIG_INSPECTION=1 \
		        -DCONFIG_MULTITHREAD=0 \
		        -DCONFIG_RUNTIME_CPU_DETECT=0 \
		        -DCONFIG_UNIT_TESTS=0 \
		        -DCONFIG_WEBM_IO=0 \
		        -DCMAKE_TOOLCHAIN_FILE="/home/sergey/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake"; \
			make \
		)

$(X86LIBAV1): $(X86LIBDIR)
		(cd $(X86LIBDIR); cmake  `pwd | sed 's?$(X86LIBDIR)?$(AOMDIR)?'`; make)

$(LIBDIR):
		mkdir $(LIBDIR)

$(X86LIBDIR):
		mkdir $(X86LIBDIR)

 emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.31
clang version 6.0.1  (emscripten 1.38.31 : 1.38.31)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/sergey/emsdk/clang/e1.38.31_64bit
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:WARNING: (Emscripten: system change: 1.38.31|/home/sergey/emsdk/clang/e1.38.31_64bit|6.0 vs 1.38.47|/home/sergey/emsdk/clang/e1.38.31_64bit|6.0, clearing cache)
shared:INFO: (Emscripten: Running sanity checks)

The following precompiled tool packages are available for download:
           clang-e1.37.1-64bit      
           clang-e1.38.30-64bit     
     *     clang-e1.38.31-64bit         INSTALLED
           node-4.1.1-32bit             INSTALLED
           node-4.1.1-64bit             INSTALLED
           node-8.9.1-32bit         
     *     node-8.9.1-64bit             INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        
           emscripten-1.37.1        
           emscripten-1.38.30       
     *     emscripten-1.38.31           INSTALLED

The following tools can be compiled from source:
           clang-tag-e1.38.48-32bit 
           clang-tag-e1.39.0-32bit  
           clang-tag-e1.38.48-64bit 
           clang-tag-e1.39.0-64bit  
           clang-incoming-32bit     
           clang-incoming-64bit         INSTALLED
           clang-master-32bit           INSTALLED
           clang-master-64bit           INSTALLED
           emscripten-tag-1.38.48-32bit
           emscripten-tag-1.39.0-32bit
           emscripten-tag-1.38.48-64bit
           emscripten-tag-1.39.0-64bit
           binaryen-tag-1.38.47-32bit
           binaryen-tag-1.38.48-32bit
           binaryen-tag-1.38.47-64bit
           binaryen-tag-1.38.48-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit      INSTALLED
           emscripten-incoming-64bit    INSTALLED
           emscripten-master-64bit      INSTALLED
           binaryen-master-32bit    
           binaryen-master-64bit    

The following precompiled SDKs are available for download: (Run "./emsdk update" to pull in the latest list)
         sdk-1.38.30-64bit        
    *    sdk-1.38.31-64bit              INSTALLED

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit             INSTALLED
         sdk-master-32bit               INSTALLED
         sdk-master-64bit               INSTALLED
         sdk-tag-1.38.48-32bit    
         sdk-tag-1.39.0-32bit     
         sdk-tag-1.38.48-64bit    
         sdk-tag-1.39.0-64bit     

Items marked with * are activated for the current user.

**Comment by sbc100** [comment]
Somehow you seem to be mixing `1.38.31` with `incoming`.. at least the error messages seem to include `/home/sergey/emsdk/emscripten/incoming` but `emcc -v` says its in ` /home/sergey/emsdk/clang/e1.38.31`.

I would try `emsdk install latest` to get the latest SDK.

**Comment by zababurinsv** [comment]
> Somehow you seem to be mixing `1.38.31` with `incoming`.. at least the error messages seem to include `/home/sergey/emsdk/emscripten/incoming` but `emcc -v` says its in ` /home/sergey/emsdk/clang/e1.38.31`.
> 
> I would try `emsdk install latest` to get the latest SDK.

I am install emsdk install latest

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.0
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project e44524736c4a97ae4fb37193e58647f838f6d36a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/sergey/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)
sergey@node:~/Desktop/project/wasm/wasm-av1$ 

Makefile
 $(EMLIBAV1): $(LIBDIR)
		(cd $(LIBDIR); \
			cmake  `pwd | sed 's?$(LIBDIR)?$(AOMDIR)?'` \
		        -DENABLE_CCACHE=1 \
		        -DAOM_TARGET_CPU=generic \
		        -DENABLE_DOCS=0 \
		        -DCONFIG_ACCOUNTING=1 \
		        -DCONFIG_INSPECTION=1 \
		        -DCONFIG_MULTITHREAD=0 \
		        -DCONFIG_RUNTIME_CPU_DETECT=0 \
		        -DCONFIG_UNIT_TESTS=0 \
		        -DCONFIG_WEBM_IO=0 \
		        -DCMAKE_TOOLCHAIN_FILE=`/home/sergey/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake`; \
			make \
		)


"..at least the error messages seem to include /home/sergey/emsdk/emscripten/incoming.."
What is the path ?
 
Now i getting this error:


/home/sergey/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake: 8: /home/sergey/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake: Syntax error: word unexpected (expecting ")")
CMake Error at /home/sergey/Desktop/project/wasm/wasm-av1/third_party/embuild/CMakeFiles/3.15.3/CMakeSystem.cmake:6 (include):
  include could not find load file:

    /home/sergey/emsdk/emscripten/incoming/cmake/Modules/Platform/Emscripten.cmake
Call Stack (most recent call first):
  CMakeLists.txt:57 (project)

**Comment by zababurinsv** [comment]
> Somehow you seem to be mixing `1.38.31` with `incoming`.. at least the error messages seem to include `/home/sergey/emsdk/emscripten/incoming` but `emcc -v` says its in ` /home/sergey/emsdk/clang/e1.38.31`.
> 
> I would try `emsdk install latest` to get the latest SDK.

thanks it is working
