### ISSUE TITLE
undefined symbol: fd_read and undefined symbol: fd_seek

### ISSUE THREAD

**Issue by stephassoria** [emscripten-core/emscripten#9694]
Hello,

    after updating emscripten (git pull, emsdk update-tags, emsdk install latest ... ) and trying to rebuild a test project, I get two undefined symbols I didn't get before (fd_read, fd_seek). I force -s ERROR_ON_UNDEFINED_SYMBOLS=0 to link, but execution failed at first fseek call.

     I use --preload-file to preload some assets and classic fopen, fread... to access it.

     All help is welcome.

             regards,

               Stéphane

**Comment by kripken** [comment]
This might happen from mixing together emscripten versions, as we have changed the ABI there. Please make sure to rebuild source files to object using the new compiler.

If that's not it, please try to create a reduced testcase and we can debug that.

**Comment by stephassoria** [comment]
Thanks kripten, 
    a full rebuild and everything is fine. Sorry for the inconvenience.

     Stéphane
