### ISSUE TITLE
Typo in wiki (tappy chicken)

### ISSUE THREAD

**Issue by SamyBencherif** [emscripten-core/emscripten#9695]
I'm not sure if I'm confused or if this is a typo 😅 

<img width="879" alt="Screen Shot 2019-10-23 at 10 46 50 AM" src="https://user-images.githubusercontent.com/10871454/67405334-9c661480-f582-11e9-913e-8d2b027ff489.png">

It says _Tappy Chicken_, but the description is _The Full Unreal Engine 3_. 

This is on page [Porting-Examples-and-Demos](https://github.com/emscripten-core/emscripten/wiki/Porting-Examples-and-Demos#games-and-game-engines) under header #games-and-game-engines.

BTW, the link _Tappy Chicken_ hilariously links to the UE homepage. I think this is probably a harmless typo, but porting of UE3 to JS is a significant achievement. It should be displayed prominently and correctly! 

Cheers,
-S

**Comment by kripken** [comment]
Thanks @SamyBencherif , looks like that link is dead. I don't see another good UE online demo right now, which is a shame... I removed the line from the list.
