### ISSUE TITLE
Invalid asm.js: Expected shift of word size

### ISSUE THREAD

**Issue by frantic0** [emscripten-core/emscripten#9696]
Hello, 

I'm getting an "Invalid asm.js: Expected shift of word size" and an unexpected behaviour in library that I'm transpiling.

Here's a [snapshot](https://i.imgur.com/g30splo.png) of the console. This seems to happen every time I load the library from an empty cache. 

Here's my setup 

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.31
clang version 6.0.1  (emscripten 1.38.31 : 1.38.31)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/francisco/emsdk_portable/clang/e1.38.31_64bit
```

And emcc compilation flags

```CFLAGS=--bind -O1 \
				-s WASM=0 \
				-s DISABLE_EXCEPTION_CATCHING=0 \
				-s ASSERTIONS=1 \
				-s SINGLE_FILE=1 \
				-s --memory-init-file 0 --profiling -std=c++11 -DSPN -DVORBIS \
				-s MODULARIZE=1 \
				-s EXPORT_NAME="'maximilian'"
```
This might be related to the previous issue https://github.com/emscripten-core/emscripten/issues/7370.

Would this be a bug in Chrome? Any ideas?

Many thanks,
FØ

**Comment by kripken** [comment]
It could be a bug in v8. However that emscripten runtime code is not new, so it would surprise me a bug was missed there.

Which chrome version is that? And do you see this with newer emscripten as well (that version looks like it's 6 months old or so, although I don't remember any asm.js fixes in that time - all new development is on wasm).

**Comment by frantic0** [comment]
Thanks @kripken, 

I updated to emsdk 1.39.0, the warning seemed to go away. FYI, It was happening on chrome version 78.0.3904.70 (Official Build) (64-bit) and version 80.0.3949.0 (Official Build) canary (64-bit).

However, now I get two unexpected errors...

```1. Uncaught TypeError: X is not a constructor```

```2. UnboundTypeError {name: "UnboundTypeError", message: "Cannot call Y due to unbound types: N7maxiFFT8fftModesE", stack: "UnboundTypeError: Cannot call maxiFFT.process due …ipt-processor-node/build/maximilian.js:119416:22)"}```

Were there any changes to the compilation process? Any flags that I should update?
