### ISSUE TITLE
Add EM_ASYNC_JS for native async function support

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#9709]
While `Asyncify.handleSleep` is relatively easy to use, async functions and Promises are pretty ubiquitous in Web APIs, it seems useful to have something more direct.

## Why

Adding a built-in macro for async functions would have several benefits:
1) Being able to integrate more easily with native async APIs.
1) Consistent synchronous-looking code on both sides of Asyncify.
1) Easier error handling - right now any async errors will be just reported to browser console, while code remains sleeping, but async functions catch any asynchronously thrown errors and report as promise rejections, which makes it easier to propagate them back to C++ and handle as any other FFI errors.

### Before

```js
EM_JS(void, do_fetch, (), {
  Asyncify.handleSleep(function(wakeUp) {
    out("waiting for a fetch");
    fetch("a.html").then(response => {
      out("got the fetch response");
      // (normally you would do something with the fetch here)
      wakeUp();
    });
  });
});
```

### After

```js
EM_ASYNC_JS(void, do_fetch, (), {
  out("waiting for a fetch");
  let response = await fetch("a.html");
  out("got the fetch response");
  // (normally you would do something with the fetch here)
});
```

**Comment by kripken** [comment]
Nice idea!

cc @jgravelle-google

**Comment by jgravelle-google** [comment]
To clarify, the expectation here would be that this C++
```c++
EM_JS(void, foo, (), {
  out("hello");
});
EM_ASYNC_JS(void, bar, (), {
  let response = await fetch("a.html");
  out(response);
});
```
would produce JS functions:
```js
function foo() {
  out("hello");
}
async function bar () {
  let response = await fetch("a.html");
  out(response);
}
```

Sgtm! Might even be simple, I'll give it a shot.

Nit: how about EM_JS_ASYNC instead? Keeps all the related functionality greppable with "EM_JS\*"

**Comment by RReverser** [comment]
@jgravelle-google This is correct, assuming that you left sleep handling out of scope of generated example.

I don't have a strong preference about the name, although `EM_ASYNC_JS` feels a bit more readable / consistent with output.

**Comment by jgravelle-google** [comment]
Right, those weren't meant to be equivalent to each other, but rather to show that the generated JS is just literally what the user wrote, and that adding ASYNC in EM_JS is the same as adding async to a JS function.

Which is to say we don't reason about the JS function body at all. In general I don't think we do anything with ES6 features, but this would be entirely user-driven and so totally opt-in, and not need global changes to our JS glue to support it.

**Comment by RReverser** [comment]
@jgravelle-google Sounds right to me!

**Comment by gerald-dotcom** [comment]
Sorry for jumping into this old topic. Is there are any way to use Await keyword in EM_JS at this stage?

I was able to make Async function but it seems mystery why the code not wait for Await keyword

**Comment by RReverser** [comment]
I don't think it's that old 😅 But yeah, it hasn't had much attention since.

> > I was able to make Async function but it seems mystery why the code not wait for Await keyword

It doesn't wait precisely because `EM_JS` generates regular JS functions (essentially `function foo() { ... }`), but `await` requires async JS functions (`async function foo() { ... }`).

This issue is precisely about that - ability to generate async functions and use their resulting Promise. I don't know if @jgravelle-google has any time on his plate to implement this though.

**Comment by RReverser** [comment]
Bump.
