### ISSUE TITLE
embind problems with upstream

### ISSUE THREAD

**Issue by greglandrum** [emscripten-core/emscripten#9718]
Hi,

I have an embind-based wrapper around a large-ish C++ project that I've been working on that breaks when I try building it using upstream. The error is:
`BindingError: No dynCall invoker for signature: ` (there's nothing after the colon).
If I switch to using fastcomp everything works fine.

In the discussion of #6362 there's a comment from @kripken that embind is no longer maintained. Is that still true? Should I switch to webIDL or something else to do these wrappers?

Here's the dockerfile that I use to do my builds:
https://github.com/rdkit/rdkit/blob/fix/js_tests/Code/MinimalLib/docker/Dockerfile

Version: I cloned the emsdk repo and ran `emsdk install latest` or `emsdk install latest-fastcomp` this morning.

FWIW, here's the full output:
```
root@d5f71fba3399:/src/rdkit/Code/MinimalLib/tests# node tests.js
BindingError: No dynCall invoker for signature: 
BindingError: No dynCall invoker for signature: 

/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(Module["ENVIRONMENT"]){throw new Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for ex
abort(BindingError: No dynCall invoker for signature: ) at Error
    at jsStackTrace (/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1:25027)
    at stackTrace (/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1:25198)
    at process.abort (/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1:22152)
    at process.emit (events.js:209:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

**Comment by kripken** [comment]
Thanks @greglandrum! Embind is maintained (that old link is obsolete), so this is definitely a bug we should fix.

Can you provide a testcase perhaps? We aren't aware of any fastcomp/upstream differences in embind atm, so this isn't a known issue.

**Comment by greglandrum** [comment]
@kripken : unfortunately I'm not sure how to prune things back far enough that it's self-contained but still shows the problem. 
The best I can currently do is this Dockerfile, which creates an emscripten build environment, pulls the codebase I'm wrapping, and does a build:
https://github.com/rdkit/rdkit/blob/fix/js_tests/Code/MinimalLib/docker/Dockerfile

If I change lines 30 and 31 to:
```
  ./emsdk install latest && \
  ./emsdk activate latest
```
I get the error I show above.

**Comment by kripken** [comment]
Thanks @greglandrum! @jgravelle-google maybe that's enough to take a look at?

**Comment by jgravelle-google** [comment]
That should be enough to look at. I need to get set up with either Docker or install the Boost headers, which I'll get to sometime next week.

In the meantime, taking another look at that error message, "No dynCall invoker for signature: (there's nothing after the colon)", that looks like the pointer for the signature is reading out of uninitialized memory, which is odd. That's still a problem in the embind runtime, mostly just noting the results of my initial pass at looking into this.

Also it looks like the only Emscripten arguments that are passed is `-s DISABLE_EXCEPTION_CATCHING=0`, which in theory could have an effect, but adding that to our `test_embind.cpp` didn't reproduce the issue, so something else must be happening.

**Comment by greglandrum** [comment]
FWIW: I just did a fresh emscripten install from github and am able to run my build and tests using upstream.
I'll go ahead and close this.
