### ISSUE TITLE
Cannot call myResize due to unbound types

### ISSUE THREAD

**Issue by 810250082** [emscripten-core/emscripten#9722]
I compiled opencv into js and then wrote the code to call。
.cpp
`
#include <emscripten/bind.h>
#include <emscripten/val.h>
#include <opencv2/core/mat.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/opencv.hpp>
#include <stdio.h>
using namespace cv;
using namespace emscripten;

Mat myResize(const Mat& img){
  Mat dst;
  resize(img, dst, Size(512, 512));
  return dst;
}

EMSCRIPTEN_BINDINGS(my_moudle) {
  function("myResize", &myResize);
}
`

.html
`<script>
imgElement.onload = function() {
var mat = Module.imread(imgElement);
mat = Module.myResize(mat);
Module.imshow('canvasOutput', mat);
mat.delete();
};
</script>
`

Compile through, but js runs to `mat = Module.myResize(mat);` ，
Report an error：

Uncaught 
UnboundTypeError {name: "UnboundTypeError", message: "Cannot call myResize due to unbound types: ", stack: "UnboundTypeError: Cannot call myResize due to unbo…t.onload (http://localhost:5000/index.html:37:11)"}
message: "Cannot call myResize due to unbound types: "
name: "UnboundTypeError"
stack: "UnboundTypeError: Cannot call myResize due to unbound types: ↵    at UnboundTypeError.<anonymous> (http://localhost:5000/build/func.js:1:89809)↵    at new UnboundTypeError (eval at createNamedFunction (http://localhost:5000/build/func.js:1:1), <anonymous>:4:34)↵    at throwUnboundTypeError (http://localhost:5000/build/func.js:1:100919)↵    at Object.myResize (http://localhost:5000/build/func.js:1:101267)↵    at face2 (http://localhost:5000/index.html:48:30)↵    at HTMLImageElement.imgElement.onload (http://localhost:5000/index.html:37:11)"
__proto__: Error

how should I do？

**Comment by waywardmonkeys** [comment]
You need a binding for `Mat`, no?
