### ISSUE TITLE
STANDALONE_WASM should probably support SIMD?

### ISSUE THREAD

**Issue by zeux** [emscripten-core/emscripten#9724]
I'm starting to experiment with -msimd128 and getting this error from emcc.py:

```
if shared.Settings.SIMD:
    exit_with_error('STANDALONE_WASM does not support simd yet')
```

However, commenting this out doesn't result in any further errors. My understanding is that SIMD doesn't require any runtime support - should this error be emitted?

**Comment by kripken** [comment]
Thanks @zeux! Yeah, seems like it should just work, I opened #9727 now.
