### ISSUE TITLE
Re-add v8 to CI somehow

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9729]
In #9711 we disabled it because it broke. We should re-add it, so we don't lose test coverage (for SIMD etc.) for too long.

We've considered

 * Upgrading v8, which may fix the issue, but I think I remember @dschuff couldn't upgrade DEPS all the way for some reason?
 * Using newest v8 from jsvu.
 * Pinning a version from jsvu, if that's possible.

**Comment by dschuff** [comment]
There was an issue with Goma on Windows (basically the toolchain it wanted to use wasn't on the server). Hopefully that will just take care of itself.
Even if we use jsvu for the actual V8 binary, we are using all the toolchain-management code in V8's build scripts (i.e. MSVC SDK, clang binaries, etc) to build our binaries, so we do still want to keep it up-to-date.
