### ISSUE TITLE
Expose WEBGL_multi_draw extension to Emscripten

### ISSUE THREAD

**Issue by kenrussell** [emscripten-core/emscripten#9732]
The [WEBGL_multi_draw extension](https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw/) can significantly reduce the overhead of issuing many small draw calls of varying length.

Support should be added to Emscripten to allow C/C++ applications to call these APIs.

**Comment by kenrussell** [comment]
CC'ing @austinEng and @ShrekShao who have been working on the multi-draw and BaseVertex/BaseInstance extensions. Once multi-draw is exposed, the BaseVertex/BaseInstance extensions would be a natural follow-on.

**Comment by shrekshao** [comment]
Addressed in #11650 (Don't have permission to close this)

**Comment by kenrussell** [comment]
Looks like as the issue author I can close this. Great work @shrekshao!
