### ISSUE TITLE
a problem with the relocatable flag 

### ISSUE THREAD

**Issue by SetLinux** [emscripten-core/emscripten#9739]
i am trying to produce a relocatable wasm file from a .bc file but it allways ends this way

> parse exception: unexpected end of input (at 0:433594)]
Fatal: error in parsing input

the command i am using 

> emcc libLinearMath.bc -s RELOCATABLE=1  --o testlib.wasm -v

**Comment by kripken** [comment]
What version of emscripten is that with? And can you provide the input file as a testcase?

**Comment by kripken** [comment]
Also, what are you trying to achieve with that flag? In general it is used internally in the main module / side module modes. I'm not sure how function it is by itself.

**Comment by GreatIndieDeveloper** [comment]
i am doing with the (tot) (tip of tree) and i got the same result when doing it with the latest release and i tried to use the "-s SIDE_MODULE=1" and got the same result exactly

**Comment by GreatIndieDeveloper** [comment]
i will be able to upload the file in a couple of hours

**Comment by sbc100** [comment]
The output of your build command with "EMCC_DEBUG=1" might also be helpful.

**Comment by GreatIndieDeveloper** [comment]
> <pre>shared:DEBUG: <font color="#AA00AA">EM_CONFIG is located in /home/mohamedmedhat/.emscripten</font>
shared:DEBUG: <font color="#AA00AA">JAVA not defined in /home/mohamedmedhat/.emscripten, using &quot;java&quot;</font>
cache:DEBUG: <font color="#AA00AA">PID 26915 acquiring multiprocess file lock to Emscripten cache at /home/mohamedmedhat/.emscripten_cache</font>
cache:DEBUG: <font color="#AA00AA">done</font>
cache:DEBUG: <font color="#AA00AA">PID 26915 released multiprocess file lock to Emscripten cache at /home/mohamedmedhat/.emscripten_cache</font>
shared:DEBUG: <font color="#AA00AA">check tells us to use wasm backend</font>
emcc:WARNING: <font color="#AA5500">invocation: /home/mohamedmedhat/emsdk/upstream/emscripten/emcc.py libLinearMath.bc -s RELOCATABLE=1 -o final.wasm  (in /home/mohamedmedhat/Downloads/bullet3-2.88/anthtest/src/LinearMath)</font>
shared:DEBUG: <font color="#AA00AA">successfully executed /home/mohamedmedhat/emsdk/upstream/bin/clang++ --version</font>
root:DEBUG: <font color="#AA00AA">Checking JS engine [&apos;/home/mohamedmedhat/emsdk/node/12.9.1_64bit/bin/node&apos;]</font>
shared:DEBUG: <font color="#AA00AA">successfully executed /home/mohamedmedhat/emsdk/node/12.9.1_64bit/bin/node --version</font>
shared:DEBUG: <font color="#AA00AA">successfully executed /home/mohamedmedhat/emsdk/upstream/bin/llc --version</font>
shared:INFO: <font color="#00AA00">(Emscripten: Running sanity checks)</font>
shared:DEBUG: <font color="#AA00AA">successfully executed java -version</font>
emcc:DEBUG: <font color="#AA00AA">compiling to bitcode</font>
emcc:DEBUG: <font color="#AA00AA">emcc step &quot;parse arguments and setup&quot; took 2.75 seconds</font>
cache:DEBUG: <font color="#AA00AA">PID 26915 acquiring multiprocess file lock to Emscripten cache at /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic</font>
cache:DEBUG: <font color="#AA00AA">done</font>
emcc:DEBUG: <font color="#AA00AA">using object file: libLinearMath.bc</font>
emcc:DEBUG: <font color="#AA00AA">emcc step &quot;compile inputs&quot; took 0.00 seconds</font>
emcc:DEBUG: <font color="#AA00AA">emcc step &quot;process inputs&quot; took 0.00 seconds</font>
shared:DEBUG: <font color="#AA00AA">executed /home/mohamedmedhat/emsdk/upstream/bin/llvm-nm /home/mohamedmedhat/Downloads/bullet3-2.88/anthtest/src/LinearMath/libLinearMath.bc</font>
system_libs:DEBUG: <font color="#AA00AA">including crt1 (crt1.o)</font>
system_libs:DEBUG: <font color="#AA00AA">including libc (libc.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libcompiler_rt (libcompiler_rt.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libc-wasm (libc-wasm.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libc++ (libc++-noexcept.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libc++abi (libc++abi-noexcept.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libmalloc (libdlmalloc.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libpthread (libpthread_stub.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libc_rt_wasm (libc_rt_wasm.a)</font>
system_libs:DEBUG: <font color="#AA00AA">including libstandalonewasm (libstandalonewasm.a)</font>
emcc:DEBUG: <font color="#AA00AA">emcc step &quot;calculate system libraries&quot; took 0.08 seconds</font>
emcc:DEBUG: <font color="#AA00AA">linking: [&apos;libLinearMath.bc&apos;, &apos;-L/home/mohamedmedhat/emsdk/upstream/emscripten/system/local/lib&apos;, &apos;-L/home/mohamedmedhat/emsdk/upstream/emscripten/system/lib&apos;, &apos;-L/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/crt1.o&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libcompiler_rt.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc-wasm.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc++-noexcept.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc++abi-noexcept.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libdlmalloc.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libpthread_stub.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc_rt_wasm.a&apos;, &apos;/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libstandalonewasm.a&apos;]</font>
wasm-ld: <font color="#AA00AA">warning: </font>unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=0 expected=1
wasm-ld: <font color="#AA00AA">warning: </font>unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=1 expected=2
wasm-ld: <font color="#AA00AA">warning: </font>unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=2 expected=3
wasm-ld: <font color="#AA00AA">warning: </font>unexpected existing value for R_WASM_TABLE_INDEX_REL_SLEB: existing=3 expected=4
shared:DEBUG: <font color="#AA00AA">successfully executed /home/mohamedmedhat/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp/final.wasm --allow-undefined --lto-O0 libLinearMath.bc -L/home/mohamedmedhat/emsdk/upstream/emscripten/system/local/lib -L/home/mohamedmedhat/emsdk/upstream/emscripten/system/lib -L/home/mohamedmedhat/.emscripten_cache/wasm-obj-pic /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/crt1.o /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libcompiler_rt.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc-wasm.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc++-noexcept.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc++abi-noexcept.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libdlmalloc.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libpthread_stub.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libc_rt_wasm.a /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic/libstandalonewasm.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --no-gc-sections --export-dynamic --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush --export _ZSt18uncaught_exceptionv -pie -z stack-size=5242880 --initial-memory=16777216 --max-memory=16777216</font>
emcc:DEBUG: <font color="#AA00AA">emcc step &quot;link&quot; took 0.02 seconds</font>
emcc:DEBUG: <font color="#AA00AA">LLVM =&gt; JS</font>
[parse exception: unexpected end of input (at 0:426746)]
Fatal: error in parsing wasm binary
shared:ERROR: <font color="#AA0000">&apos;/home/mohamedmedhat/emsdk/upstream/bin/wasm-dis /tmp/emscripten_temp/final.wasm -o /tmp/emscripten_temp/base.wasm.wast&apos; failed (1)</font>
cache:DEBUG: <font color="#AA00AA">PID 26915 released multiprocess file lock to Emscripten cache at /home/mohamedmedhat/.emscripten_cache/wasm-obj-pic</font></pre>

>

**Comment by GreatIndieDeveloper** [comment]
any news/ideas on this ?

**Comment by kripken** [comment]
It would be good to get the file you said you could upload, then we can reproduce it locally.

Also, as I asked earlier, I'm curious what are you trying to achieve with that flag? In general it is used internally in the main module / side module modes, and I'm not sure how functional it is by itself.

**Comment by GreatIndieDeveloper** [comment]
https://gofile.io/?c=6R64NX

**Comment by GreatIndieDeveloper** [comment]
any news on the issue ?

**Comment by kripken** [comment]
Thanks for the testcase @GreatIndieDeveloper !

On latest emscripten I see this:
```
$ ./emcc libLinearMath.o -s SIDE_MODULE
wasm-ld: error: libLinearMath.o: relocation R_WASM_TABLE_INDEX_SLEB cannot be used against symbol btAlignedFreeDefault(void*); recompile with -fPIC
```
Does it work if you recompile source files with `-fPIC`?

**Comment by kripken** [comment]
(btw, why is it named `.bc` when it's a wasm object file? those normally have suffix `.o`. confused me for a minute...)

**Comment by GreatIndieDeveloper** [comment]
sorry for not answering earlier been a bit busy with a couple of things here and there

**Comment by GreatIndieDeveloper** [comment]
i will recheck ASAP
