### ISSUE TITLE
Function signature mismatch: wrong number of arguments passed

### ISSUE THREAD

**Issue by manumartin** [emscripten-core/emscripten#9746]
Hi, I'm having a strange issue when running cpython built with:
- emscripten 1.38.47
- LLVM master
- -fPIC flag (I don't know if the problem is related to this flag but it has been giving some problems)

I have a function call that in c looks like:
```
return descr->d_getset->get(obj, descr->d_getset->closure);
```
In webassembly it's translated to:
```
        local.get 25
        local.get 28
        local.get 24
        call_indirect (type 1)
```
where type 1 is defined as:
```
  (type (;1;) (func (param i32 i32) (result i32)))
```
The type matches the c signature but three parameters are being passed to the stack instead of two.

A screenshot for a little more context:
![invalid_indirect_call](https://user-images.githubusercontent.com/1679143/67909133-704c2400-fb7e-11e9-9f00-5037495068f4.png)

**Comment by manumartin** [comment]
This seems more of an LLVM issue, perhaps I should put this on the LLVM bugtracker instead of here

**Comment by sbc100** [comment]
If you remove the PIC flag does it work?  We are still resolving some issue with PIC code and static linking.  If you can, remove the PIC flag from your build and see if that fixes the issue for now?

**Comment by manumartin** [comment]
Hi, I'm using the PIC flag because we are trying use dynamic linking, I'm going to try to reproduce the problem in isolation to test it with and without the flag.

**Comment by manumartin** [comment]
Tried this example:

```
#include <stdio.h>
#include <stdlib.h>

typedef char *(*getter)(char *, void *);

typedef struct {
  getter get;
} PyGetSetDef;

typedef struct {
  PyGetSetDef *d_getset;
} PyGetSetDescrObject;

char *fun(char *param1, void *param2) {
  printf("testing\n");
  return 0;
}

/**
 * Test double indirect dereference into an indirect function call, should generate
 * this WASM:
 *    local.get 28
 *    local.get 24
 *    call_indirect (type 1)
 */
void test_function(PyGetSetDescrObject *descr) {
  char * test = descr->d_getset->get(0, 0);
}

int main() {
  PyGetSetDescrObject *descr = (PyGetSetDescrObject *)malloc(sizeof(PyGetSetDescrObject));
  descr->d_getset = (PyGetSetDef *)malloc(sizeof(PyGetSetDef));
  descr->d_getset->get = &fun;

  test_function(descr);
}
```
It doesn't throw the error although it is loading three values on the stack.. I guess the error is being thrown for other reason

**Comment by manumartin** [comment]
I'm closing this issue, it seems the problem isn't about the generated WASM, the function pointer has a bad value for some reason.
