### ISSUE TITLE
Access to AWS repository resources fails with HTTP Error 403

### ISSUE THREAD

**Issue by TidbitSoftware** [emscripten-core/emscripten#9748]
On a machine running Ubuntu Linux 16.04, I am currently getting,
```
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/emsdk_unix_update.tar.gz': HTTP Error 403: Forbidden
Fetching all tags from Emscripten Github repository...
```
and
```
Done installing tool 'clang-master-64bit'.
Installing tool 'node-4.1.1-64bit'..
HTTP error with URL 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/node-v4.1.1-linux-x64.tar.gz': HTTP Error 403: Forbidden
Installation failed!
```
The following configuration was working as of a couple days ago (after downloading and un'tar'ing emsdk source),
```
# Download and install the latest SDK tools
./emsdk update

# Make the "latest" SDK "active" for the current user. (writes ~/.emscripten file)
# NOTE: See revision history for version that we used to hard code in.
./emsdk install latest
./emsdk activate latest

# Activate PATH and other environment variables in the current terminal
source emsdk_env.sh
```
Navigating to the resource in a Web browser gives,
 ```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>52CFAF7C08B4AB08</RequestId>
<HostId>
3MfYe1Y0CuiMW/PjGuOjGFn/n3o3HucQg4O6wELP07ZHjgzsxBm231OKfUKfBsjWLMRyLyC5DIw=
</HostId>
</Error>
```

**Comment by kripken** [comment]
Mozilla has removed the AWS S3 storage for mozilla-games, so all those old links are now dead, sorry about that.

Where did the old link come from? Those links have been removed from the emsdk a while ago. Is it possible that's an old emsdk version? Or perhaps your `./emsdk update` command failed? One possible issue there is if the emsdk is a git checkout, then you need to use git to update it (`git pull`).

**Comment by TidbitSoftware** [comment]
Thanks for the quick response. You are exactly right: I am pulling the tarball from a private repo where we keep external package source code. It must be then than the `./emsdk update` failed in this instance because the same configuration worked on another machine just days ago. As a result, and because of the HTTP errors, I figured it was a new outage. Thanks again!
