### ISSUE TITLE
error: conflicting types for 'SDL_SetError' extern DECLSPEC void SDLCALL SDL_SetError(const char *fmt, ...)

### ISSUE THREAD

**Issue by zababurinsv** [emscripten-core/emscripten#9749]
Hi.
I saw this error in two projects.

In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:117:5: error: redefinition of enumerator 'SDL_FALSE'
    SDL_FALSE = 0,
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:163:5: note: previous definition is here
    SDL_FALSE = 0,
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:118:5: error: redefinition of enumerator 'SDL_TRUE'
    SDL_TRUE = 1
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:164:5: note: previous definition is here
    SDL_TRUE = 1
    ^
In file included from main.c:9:

My make file 
```
CC=gcc

CFLAGS=-g -Wall -O3 -D_GNU_SOURCE=1 -D_REENTRANT -pedantic -lm -I/usr/include/SDL2 
IMAGE_FLAGS=-lSDL2_image
MIXER_FLAGS=-lSDL2_mixer
FONTS_FLAGS=-lSDL2_ttf
SFLAGS=-lSDL2
SOURCES=main.c
OBJECTS=main.o
BINARIES=zombie-breakout

all: $(BINARIES)

zombie-breakout: main.o
	$(CC) -o zombie-breakout main.o $(CFLAGS) $(SFLAGS) $(IMAGE_FLAGS) $(MIXER_FLAGS) $(FONTS_FLAGS)

main.o: main.c
	$(CC) -c main.c $(CFLAGS) $(SFLAGS) $(IMAGE_FLAGS) $(MIXER_FLAGS) $(FONTS_FLAGS)

emcc: main.c
	emcc main.c -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s WASM=1 --shell-file html_template/resize-with-aspect-ratio.html -s USE_OGG=1 -s USE_VORBIS=1 -o docs/index.html -O2 --preload-file assets

clean:
	rm -rf *.o *.exe *.bak *.c~ $(BINARIES) core a.out

```
How add sdl ?

**Comment by kripken** [comment]
From the error it looks like maybe this was caused by a mixup of SDL1 and SDL2, was that the issue?
