### ISSUE TITLE
Can we use Emscripten to get back candidates from Web Langauge like WASM to C?

### ISSUE THREAD

**Issue by shrin18** [emscripten-core/emscripten#9752]

**Comment by sbc100** [comment]
I'm not sure what you mean by "get back candidates".  can you explain?

**Comment by shrin18** [comment]
I mean can you generate a candidate from .wasm to .c language in reverse way. We have a couple of wasm files which are yet to be validated. We were thinking of incorporating emscripten in our pipeline for doing so. Currently the optimised candidates that we generate are in .wasm form generated via souper

**Comment by sbc100** [comment]
Are you talking about decompilation from wasm back into C?  

I don't know of any wasm->C decompiler that exist to day no. There is wasm->llvm (https://github.com/WAVM/WAVM) and there may be tools for lifting llvm up into C code?   Aside from the there is `wasm-dis` (part of binaryen) and `wasm-objdump -d` but those just do disassembly.

**Comment by kripken** [comment]
Wabt has a [wasm2c](https://github.com/WebAssembly/wabt/tree/master/wasm2c) translation tool. But it doesn't try to decompile to the actual original C source.

**Comment by shrin18** [comment]
Yes exactly @kripken . The output from `[wabt](https://github.com/WebAssembly/wabt)` gives a code with separate source and header files and it seems that both of them use several additional functions with mangled names. We are not able to parse the C output from wabt. We were trying to compare C input with C output with transformations in between llvm bit code. I think @sbc100 suggest a good way to go wasm to llvm and then trying to get C. In anyway I guess it will be more worth it to compare the .c files than .wasm files for proving optimizations since can then extend the results to include assembly level c language as well.
