### ISSUE TITLE
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:

### ISSUE THREAD

**Issue by zababurinsv** [emscripten-core/emscripten#9759]
Hi
How can i understood what the problem ?

cmake "/home/sergey/Desktop/project/wasm/build-aom/wasm-av1/third_party/aom" \
    -DENABLE_CCACHE=1 \
        -DAOM_TARGET_CPU=generic \
        -DENABLE_DOCS=0 \
        -DENABLE_TESTS=0 \
        -DCONFIG_ACCOUNTING=1 \
        -DCONFIG_INSPECTION=1 \
        -DCONFIG_MULTITHREAD=0 \
        -DCONFIG_RUNTIME_CPU_DETECT=0 \
        -DCONFIG_WEBM_IO=0 \
  -DCMAKE_TOOLCHAIN_FILE="/home/sergey/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"

[CMakeError.log](https://github.com/emscripten-core/emscripten/files/3799169/CMakeError.log)
[CMakeOutput.log](https://github.com/emscripten-core/emscripten/files/3799170/CMakeOutput.log)

i given this error.

Checking C compiler flag support for: -D_FILE_OFFSET_BITS=64
-- Performing Test C_FLAG_SUPPORTED
-- Performing Test C_FLAG_SUPPORTED - Success
Checking C++ compiler flag support for: -D_FILE_OFFSET_BITS=64
-- Performing Test CXX_FLAG_SUPPORTED
-- Performing Test CXX_FLAG_SUPPORTED - Success
-- Found PythonInterp: /usr/bin/python (found version "3.7.5") 
-- Configuring incomplete, errors occurred!

**Comment by sbc100** [comment]
Looks like the problem is `error: undefined symbol: pthread_atfork`. 

It looks like we are missing that symbol in `library_pthread_stub.js`.

**Comment by zababurinsv** [comment]
Thank.
Now 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at build/cmake/compiler_tests.cmake:43 (string):
  string no output variable specified

But now  Performing C SOURCE FILE Test C_TEST_COMPILED failed with the following output:

[CMakeError.log](https://github.com/emscripten-core/emscripten/files/3800351/CMakeError.log)
[CMakeOutput.log](https://github.com/emscripten-core/emscripten/files/3800352/CMakeOutput.log)
