### ISSUE TITLE
fatal error: too many errors emitted, stopping now [-ferror-limit=]

### ISSUE THREAD

**Issue by zababurinsv** [emscripten-core/emscripten#9769]
Hi
I want build code.

My build.sh
EMCC_DEBUG=1 emcc main.c \
  -s USE_SDL=2 \
  -s USE_SDL_TTF=2 \
  -s USE_SDL_IMAGE=2 \
  -s SDL2_IMAGE_FORMATS='["png"]' \
  -s WASM=1 \
  -s USE_OGG=1 \
  -s  USE_VORBIS=1 \
  -o docs/index.html \
  -O2 --preload-file assets

The make file which is in the source file. 

CC=gcc

CFLAGS=-g -Wall -O3 -D_GNU_SOURCE=1 -D_REENTRANT -pedantic -lm -I/usr/include/SDL2
IMAGE_FLAGS=-lSDL2_image
MIXER_FLAGS=-lSDL2_mixer
FONTS_FLAGS=-lSDL2_ttf
SFLAGS=-lSDL2
SOURCES=main.c
OBJECTS=main.o
BINARIES=zombie-breakout

all: $(BINARIES)

zombie-breakout: main.o
	$(CC) -o zombie-breakout main.o $(CFLAGS) $(SFLAGS) $(IMAGE_FLAGS) $(MIXER_FLAGS) $(FONTS_FLAGS)

main.o: main.c
	$(CC) -c main.c $(CFLAGS) $(SFLAGS) $(IMAGE_FLAGS) $(MIXER_FLAGS) $(FONTS_FLAGS)

emcc: main.c
	emcc main.c -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s WASM=1 --shell-file html_template/resize-with-aspect-ratio.html -s USE_OGG=1 -s  USE_VORBIS=1 -o docs/index.html -O2 --preload-file assets

clean:
	rm -rf *.o *.exe *.bak *.c~ $(BINARIES) core a.out

I getting this error:

I understand correctly sdl is connected through the port.
Are these libraries shipped with emscripten?

shared:DEBUG: EM_CONFIG is located in /home/sergey/.emscripten
shared:DEBUG: JAVA not defined in /home/sergey/.emscripten, using "java"
cache:DEBUG: PID 18019 acquiring multiprocess file lock to Emscripten cache at /home/sergey/.emscripten_cache
cache:DEBUG: done
cache:DEBUG: PID 18019 released multiprocess file lock to Emscripten cache at /home/sergey/.emscripten_cache
shared:DEBUG: check tells us to use wasm backend
emcc:WARNING: invocation: /home/sergey/emsdk/upstream/emscripten/emcc.py main.c -s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS=["png"] -s WASM=1 -s USE_OGG=1 -s USE_VORBIS=1 -o docs/index.html -O2 --preload-file assets  (in /home/sergey/Desktop/project/wasm/game/zombie-breakout)
shared:DEBUG: successfully executed /home/sergey/emsdk/upstream/bin/clang++ --version
root:DEBUG: Checking JS engine ['/home/sergey/emsdk/node/12.9.1_64bit/bin/node']
shared:DEBUG: successfully executed /home/sergey/emsdk/node/12.9.1_64bit/bin/node --version
shared:DEBUG: successfully executed /home/sergey/emsdk/upstream/bin/llc --version
shared:INFO: (Emscripten: Running sanity checks)
shared:DEBUG: successfully executed java -version
emcc:DEBUG: asm.js opts not forced by user or an option that depends them, and we do not intend to run the asm.js, so disabling and leaving opts to the binaryen optimizer
emcc:DEBUG: compiling to bitcode
emcc:DEBUG: emcc step "parse arguments and setup" took 0.16 seconds
cache:DEBUG: PID 18019 acquiring multiprocess file lock to Emscripten cache at /home/sergey/.emscripten_cache/wasm-obj
cache:DEBUG: done
emcc:DEBUG: compiling source file: main.c
system_libs:DEBUG: including port: zlib
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/zlib)
system_libs:DEBUG: including port: libpng
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/libpng)
system_libs:DEBUG: including port: sdl2
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/sdl2)
system_libs:DEBUG: including port: sdl2_image
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/sdl2_image)
system_libs:DEBUG: including port: ogg
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/ogg)
system_libs:DEBUG: including port: vorbis
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/vorbis)
system_libs:DEBUG: including port: freetype
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/freetype)
system_libs:DEBUG: including port: sdl2_ttf
system_libs:DEBUG:     (at /home/sergey/.emscripten_ports/sdl2_ttf)
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:117:5: error: redefinition of enumerator 'SDL_FALSE'
    SDL_FALSE = 0,
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:163:5: note: previous definition is here
    SDL_FALSE = 0,
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:118:5: error: redefinition of enumerator 'SDL_TRUE'
    SDL_TRUE = 1
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:164:5: note: previous definition is here
    SDL_TRUE = 1
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:119:3: error: typedef redefinition with different types ('enum SDL_bool' vs 'enum SDL_bool')
} SDL_bool;
  ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:165:3: note: previous definition is here
} SDL_bool;
  ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:189:5: error: redefinition of enumerator 'DUMMY_ENUM_VALUE'
    DUMMY_ENUM_VALUE
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:339:5: note: previous definition is here
    DUMMY_ENUM_VALUE
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:190:3: error: typedef redefinition with different types ('enum SDL_DUMMY_ENUM' vs 'enum SDL_DUMMY_ENUM')
} SDL_DUMMY_ENUM;
  ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:340:3: note: previous definition is here
} SDL_DUMMY_ENUM;
  ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:739:32: error: conflicting types for 'SDL_iconv'
extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf,
                               ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:551:32: note: previous declaration is here
extern DECLSPEC size_t SDLCALL SDL_iconv(SDL_iconv_t cd, const char **inbuf,
                               ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:98:5: error: redefinition of enumerator 'SDL_ASSERTION_RETRY'
    SDL_ASSERTION_RETRY,  /**< Retry the assert immediately. */
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:104:5: note: previous definition is here
    SDL_ASSERTION_RETRY,  /**< Retry the assert immediately. */
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:99:5: error: redefinition of enumerator 'SDL_ASSERTION_BREAK'
    SDL_ASSERTION_BREAK,  /**< Make the debugger trigger a breakpoint. */
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:105:5: note: previous definition is here
    SDL_ASSERTION_BREAK,  /**< Make the debugger trigger a breakpoint. */
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:100:5: error: redefinition of enumerator 'SDL_ASSERTION_ABORT'
    SDL_ASSERTION_ABORT,  /**< Terminate the program. */
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:106:5: note: previous definition is here
    SDL_ASSERTION_ABORT,  /**< Terminate the program. */
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:101:5: error: redefinition of enumerator 'SDL_ASSERTION_IGNORE'
    SDL_ASSERTION_IGNORE,  /**< Ignore the assert. */
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:107:5: note: previous definition is here
    SDL_ASSERTION_IGNORE,  /**< Ignore the assert. */
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:102:5: error: redefinition of enumerator 'SDL_ASSERTION_ALWAYS_IGNORE'
    SDL_ASSERTION_ALWAYS_IGNORE,  /**< Ignore the assert from now on. */
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:108:5: note: previous definition is here
    SDL_ASSERTION_ALWAYS_IGNORE  /**< Ignore the assert from now on. */
    ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:103:3: error: typedef redefinition with different types ('enum SDL_AssertState' vs 'enum SDL_AssertState')
} SDL_assert_state;
  ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:279:26: note: expanded from macro 'SDL_assert_state'
#define SDL_assert_state SDL_AssertState
                         ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:109:3: note: previous definition is here
} SDL_AssertState;
  ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:105:16: error: redefinition of 'SDL_AssertData'
typedef struct SDL_assert_data
               ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:280:25: note: expanded from macro 'SDL_assert_data'
#define SDL_assert_data SDL_AssertData
                        ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:111:16: note: previous definition is here
typedef struct SDL_AssertData
               ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:74:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:114:3: error: typedef redefinition with different types ('struct (anonymous struct at /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_assert.h:105:16)' vs 'struct SDL_AssertData')
} SDL_assert_data;
  ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:280:25: note: expanded from macro 'SDL_assert_data'
#define SDL_assert_data SDL_AssertData
                        ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_assert.h:120:3: note: previous definition is here
} SDL_AssertData;
  ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:188:31: error: typedef redefinition with different types ('struct SDL_atomic_t' vs 'struct SDL_atomic_t')
typedef struct { int value; } SDL_atomic_t;
                              ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_atomic.h:198:31: note: previous definition is here
typedef struct { int value; } SDL_atomic_t;
                              ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:223:23: error: static declaration of 'SDL_AtomicGet' follows non-static declaration
static __inline__ int SDL_AtomicGet(SDL_atomic_t *a)
                      ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_atomic.h:219:29: note: previous declaration is here
extern DECLSPEC int SDLCALL SDL_AtomicGet(SDL_atomic_t *a);
                            ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:75:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_atomic.h:298:25: error: static declaration of 'SDL_AtomicGetPtr' follows non-static declaration
static __inline__ void* SDL_AtomicGetPtr(void* *a)
                        ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_atomic.h:266:31: note: previous declaration is here
extern DECLSPEC void* SDLCALL SDL_AtomicGetPtr(void **a);
                              ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:76:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_audio.h:32:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_error.h:42:30: error: conflicting types for 'SDL_SetError'
extern DECLSPEC void SDLCALL SDL_SetError(const char *fmt, ...);
                             ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_error.h:41:29: note: previous declaration is here
extern DECLSPEC int SDLCALL SDL_SetError(SDL_PRINTF_FORMAT_STRING const char *fmt, ...) SDL_PRINTF_VARARG_FUNC(1);
                            ^
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:76:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_audio.h:32:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_error.h:57:5: error: redefinition of enumerator 'SDL_ENOMEM'
    SDL_ENOMEM,
    ^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_error.h:57:5: note: previous definition is here
    SDL_ENOMEM,
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
shared:ERROR: '/home/sergey/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=1 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/sergey/emsdk/upstream/emscripten/system/local/include -O2 -DEMSCRIPTEN main.c -Xclang -isystem/home/sergey/.emscripten_cache/wasm-obj/ports-builds/zlib -Xclang -isystem/home/sergey/.emscripten_cache/wasm-obj/ports-builds/libpng -Xclang -isystem/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include -Xclang -isystem/home/sergey/.emscripten_cache/wasm-obj/ports-builds/ogg/include -Xclang -isystem/home/sergey/.emscripten_cache/wasm-obj/ports-builds/vorbis/include -Xclang -isystem/home/sergey/.emscripten_cache/wasm-obj/ports-builds/freetype/include -c -o /tmp/emscripten_temp/main_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
cache:DEBUG: PID 18019 released multiprocess file lock to Emscripten cache at /home/sergey/.emscripten_cache/wasm-obj

**Comment by Gh0stBlade** [comment]
Possibly related to #9676 SDL2 is apparently bugged in latest SDK version it seems?

**Comment by zababurinsv** [comment]
This code also worked.
The whole code stopped working for various reasons.

My emcc -v

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.1
clang version 10.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project f919be336583349d883ba0dfdb3b2479a190b67c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/sergey/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

**Comment by kripken** [comment]
Thanks for filing this issue @zababurinsv !

> I understand correctly sdl is connected through the port.

SDL2 is, however, SDL1 is built into emscripten (it doesn't use a port).

The errors make me think that both SDL1 and SDL2 are being used here, and they confuse each other. Specifically,
```
In file included from main.c:9:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_ttf.h:30:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL.h:72:
In file included from /home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_main.h:25:
/home/sergey/emsdk/upstream/emscripten/system/include/SDL/SDL_stdinc.h:117:5: error: redefinition of enumerator 'SDL_FALSE'
SDL_FALSE = 0,
^
/home/sergey/.emscripten_cache/wasm-obj/ports-builds/sdl2/include/SDL2/SDL_stdinc.h:163:5: note: previous definition is here
SDL_FALSE = 0,
^
```
The first path there is SDL1 (under system/include) while the second is SDL2 (under ports-builds).

What specifically is on line 9 of main.c? That might help debug this.

Also, please paste the output of compiling `main.c` with `-v` in the commandline arguments (verbose clang printing will show the include paths).

Last question for now, what OS are you on?

**Comment by kripken** [comment]
Btw, looking in our test suite, I think the issue may be if you have 
```
#include <SDL/SDL.h>`
```
but you link with SDL2. In that case it will mix the two versions. Instead, you should have
```
#include <SDL2/SDL.h>
```
If that is the case then I think it's just a change that needs to be done in the source code of your project.
