### ISSUE TITLE
Disable memory import.

### ISSUE THREAD

**Issue by zie1ony** [emscripten-core/emscripten#9773]
I would like to ask how to remove unwanted memory import?

My module:
```c
extern void read_bytes(char *ptr, int len);

int call()
{
    char *str = "Hello, World!";
    read_bytes(str, 13);
    return 0;
}
```

Command I use to compile:
```bash
emcc filet.c -Os -s SIDE_MODULE=1 -s EXPORTED_FUNCTIONS="['call']" -o file.wasm
```

Part of generated `wasm` file converted to `wat` I don't want to be there.
```wat
(import "env" "__memory_base" (global (;0;) i32))
(import "env" "memory" (memory (;0;) 0))
```

**Comment by sbc100** [comment]
I believe the new `STANDALONE_WASM` mode is probably what you want.  Try adding that and removing the `SIDE_MODULE` setting.

**Comment by zie1ony** [comment]
It doesn't give me what I want. Now the whole module is:
```wat
(module
  (memory (;0;) 256 256)
  (export "memory" (memory 0))
  (data (;0;) (i32.const 1536) "\a0\06P"))
```

**Comment by sbc100** [comment]
What command line did you use?   Did you specify EXPORTED_FUNCTIONS="['call']" ?  That should preserver the call function in the final output.  (By the way the named of the C functions in EXPORTED_FUNCTIONS require an _ prefix so I would expect the command line to contain `-s EXPORTED_FUNCTIONS="['_call']"`).

**Comment by zie1ony** [comment]
`_` prefix was exactly what I needed. Thank you!
I also had to add `-s ERROR_ON_UNDEFINED_SYMBOLS=0`.
