### ISSUE TITLE
EmSDK script does not work under MSYS2

### ISSUE THREAD

**Issue by MayaPosch** [emscripten-core/emscripten#9774]
Doing a clean install of emscripten on a Windows 7 x64 system, using the current MSYS2 Bash shell and tools. Python version is 3.7.5, installed in /mingw64/bin/.

```
$ ./emsdk install latest
** NOTICE **: The default SDK changed from `fastcomp` to `upstream`.
If you have problems, or wish to revert back to fastcomp for some other reason
you can add `-fastcomp` to explicitly install that fastcomp-based
SDK, .e.g ./emsdk install latest-fastcomp.

Installing SDK 'sdk-releases-upstream-40f3caabcef7b52bdde63d3883462414d7a25bec-64bit'..
Installing tool 'releases-upstream-40f3caabcef7b52bdde63d3883462414d7a25bec-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/40f3caabcef7b52bdde63d3883462414d7a25bec/wasm-binaries.zip': <urlopen error unknown url type: https>
Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
Installation failed!
```

Using the (ancient) Python 2.7 installed on Windows gets the following result:

```
$ python2 emsdk.py install latest
Installing SDK 'sdk-releases-upstream-40f3caabcef7b52bdde63d3883462414d7a25bec-64bit'..
Installing tool 'releases-upstream-40f3caabcef7b52bdde63d3883462414d7a25bec-64bit'..
Downloading: D:/Dev/emscripten/emsdk/zips/40f3caabcef7b52bdde63d3883462414d7a25bec-wasm-binaries.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/40f3caabcef7b52bdde63d3883462414d7a25bec/wasm-binaries.zip, 502634308 Bytes
Unpacking 'D:/Dev/emscripten/emsdk/zips/40f3caabcef7b52bdde63d3883462414d7a25bec-wasm-binaries.zip' to 'D:/Dev/emscripten/emsdk/upstream'
Unzipping file 'D:/Dev/emscripten/emsdk/zips/40f3caabcef7b52bdde63d3883462414d7a25bec-wasm-binaries.zip' failed due to reason: [Error 2] The system cannot find the file specified: '\\\\?\\D:/'
Installation failed!
** NOTICE **: The default SDK changed from `fastcomp` to `upstream`.
If you have problems, or wish to revert back to fastcomp for some other reason
you can add `-fastcomp` to explicitly install that fastcomp-based
SDK, .e.g ./emsdk install latest-fastcomp.
```

Finally I used the listed binaries URL to obtain the emscripten ZIP file using wget, which worked flawlessly.

Perhaps it's an idea to provide the URL to the latest ZIP file directly, or use a shell script that uses wget and unzip instead of a Python script?

**Comment by kripken** [comment]
Thanks for filing, what an odd bug... does that Python 3.7.5 not have https support? Is it a python that comes with MSYS2?

The second issue with python 2.7 looks unrelated (but also very bad). Maybe we don't recognize the MSYS2 environment properly? I don't think we test it on our CI. @sbc100 is bash.exe there WSL?

**Comment by sbc100** [comment]
Yeah I don't think we have the resources to test in all the various configurations like mingw64 and cygwin.    Happy to accept patches though.

**Comment by kripken** [comment]
Should we perhaps error, or warn on untested ones? (Is WSL the only one we test in practice?)

**Comment by sbc100** [comment]
I believe we only test with an actual windows python.  We don't test with any kind of linux-on-windows type of python.

**Comment by kripken** [comment]
Ah, what is bash.exe then (the one we test on emsdk CI)? (Sorry, I'm not very familiar with windows.)

**Comment by EssenWorkbench** [comment]
emconfigure can't run ./configure shell script on MING64 environment.

$ emconfigure ./configure
configure: ./configure
emconfigure: error: './configure' failed: [WinError 193] %1 is not a valid Win32 application

**Comment by sbc100** [comment]
I think maybe you need to do `$ emconfigure sh ./configure` on MINGW.. since you end up using windows python which doesn't know how to launch subprcocess via the `#!` line at the top.
