### ISSUE TITLE
--memory-init-file has no effect in upstream backed

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#9781]
Emscripten 1.39.0.
No file is created. I don't know if this is a valid workflow in the llvm backend.

**Comment by kripken** [comment]
I think it was supported initially, as we needed it for pthreads (the memory must be outside the wasm so we load it only once on the main thread), but for wasm we don't need it any more. For wasm2js however it should function exactly like with fastcomp.

Perhaps we should update the docs and/or issue a warning if it's used without wasm2js?

**Comment by VirtualTim** [comment]
> Perhaps we should update the docs and/or issue a warning if it's used without wasm2js?

I think that's a good idea. The doco made it sound like a performance improvement for wasm, so I guess I was building with that flag needlessly.
