### ISSUE TITLE
WebIDL Gluecode issue with strings in callbacks

### ISSUE THREAD

**Issue by FelixNotTheCat** [emscripten-core/emscripten#9782]
Using emscripten-1.38.6 I am defining a interface with a pure virtual function in c++ and making it derivable in javascript, by exporting it using the webIDL binder.
When using a const char* as argument of this callback function, the gluecode generated by the binder does not call UTF8ArrayToString() before passing said argument to the derived class/function. Thus that function receives a pointer instead of a string.

cpp file:
```
class TestIDLCallbackHandler {
public:
    virtual void testIDLCallback(const char* num) = 0;
};


class TestIDLMainClass {
public:
    TestIDLMainClass(TestIDLCallbackHandler* callbackHandler)
    {
        this->callbackHandler = callbackHandler;
    }

    void test()
    {
        callbackHandler->testIDLCallback("String from WebIDL callback");
    }

private:
    TestIDLCallbackHandler* callbackHandler;
};

```

idl file:
```
interface TestIDLCallbackHandler {
    void testIDLCallback([Const]DOMString val);
};

[JSImplementation = "TestIDLCallbackHandler"]
interface TestIDLCallbackHandlerJS {
    void TestIDLCallbackHandlerJS();
    void testIDLCallback([Const]DOMString val);
};

interface TestIDLMainClass {
    void TestIDLMainClass(TestIDLCallbackHandlerJS handler);
    void test();
};
```

As a workaround i am currently accessing the emscripten HEAPU8 directly from javascript and converting the pointer to a string in the callback.
However I would have expected that this is handled in the generated gluecode. Specifically the definition of TestIDLCallbackHandler.prototype.testIDLCallback inside the generated glue.js should call UTF8ToString() before passing the argument to the derived TestIDLCallbackHandlerJS. But the generated gluecode does not do that:

```
TestIDLCallbackHandler.prototype['testIDLCallback'] = TestIDLCallbackHandler.prototype.testIDLCallback = /** @suppress {undefinedVars, duplicate} */function(val) {
  var self = this.ptr;
  ensureCache.prepare();
  if (val && typeof val === 'object') val = val.ptr;
  else val = ensureString(val);
  _emscripten_bind_TestIDLCallbackHandler_testIDLCallback_1(self, val);
};;
```

I am currently unsure exactly where this conversion should take place and digging into the gluecode generation has proven to be somewhat challenging.
Any suggestions on how this issue should be addressed?

**Comment by kripken** [comment]
It does look like the test in `tests/webidl/` doesn't check string conversions for `JSImplementation` interfaces, so yes, this looks like a missing feature.

The relevant code is in `tools/webidl_binder.py`. It can be a little hard to read at first since it generates code. When I've debugged stuff there I've done things like find the right area in the generated output, then search for the pattern in the python file. And then add extra output in python and see if it shows up in the right place in the output.
