### ISSUE TITLE
Analysis of Pull Request actions in emscripten project.

### ISSUE THREAD

**Issue by trzecieu** [emscripten-core/emscripten#9784]
Hi, 
I'm doing some analysis of big project on GitHub and how Pull Requests are handled, as I'm familiar with Emscripten project and it's a petty popular repo I run some analysis of this project. Please take following post just as an information, you're doing a great project and with effort of all people involved the entire Open Source community is getting this shining gem. 

Findings: 

1. Cumulative distribution of closed PRs looks pretty typical for Open Source projects, and looks that ~50% of all PRs are handled (merged / closed) in 1 day. 
![image](https://user-images.githubusercontent.com/4076929/68214352-8ffba600-ffdd-11e9-923e-d8c8bbaa0153.png)

Distribution of currently open PRs looks slightly different, 50% of all open PRs is half year old. 
![image](https://user-images.githubusercontent.com/4076929/68215448-8e32e200-ffdf-11e9-8ada-82e55e828215.png)

2. Plot of age of crated PR over history has no visible trend, and also it supports last observation that ~50% of created PRs are being closed in 1day
![image](https://user-images.githubusercontent.com/4076929/68214503-de10a980-ffdd-11e9-89f4-db1e76151033.png)

3. Plot of closed PR shows couple of spikes of closing issues 1 year old or more - which correlates with clean up sessions / Git Stale bot being activated 
![image](https://user-images.githubusercontent.com/4076929/68214641-1e702780-ffde-11e9-9c62-46366e2889c7.png)

4. Actions of Pull Requests are pretty balanced, there is no visual shift between amount of created and closed pull requests. Thin red bottom line shows PRs closed without merging. Pink colour shows PRs being merged. 
![image](https://user-images.githubusercontent.com/4076929/68214756-511a2000-ffde-11e9-9442-57274af4ed5f.png)

5. Here you can see amount of open Pull Requests over time, also some clean up sessions / git stale work is visible. 
![image](https://user-images.githubusercontent.com/4076929/68214872-832b8200-ffde-11e9-8514-76e88ff97ff8.png)

6. If we break down open pull request over time and categorize them by age (up to the moment of the timeline) you can observe how contribution of `1 month - 1 year` and `1 year +` increases, which means that with age of PR is getting more unlikely to merge such PR (obsolete / merge conflicts) 
![image](https://user-images.githubusercontent.com/4076929/68214988-b9690180-ffde-11e9-903b-7337526dba9d.png)

The same graph, just normalized, here it's visible how old PRs slowly overtake all PRs until something ~25th of September where a significant cleanup happened. 
![image](https://user-images.githubusercontent.com/4076929/68243134-28ac1900-0012-11ea-9c7f-5fa28601e105.png)

**Comment by kripken** [comment]
Wow, nice data, thanks @trzecieu!

Key thing for me is that around 50% of all PRs are merged or closed in 1 day, which does seem pretty good. And looks like 90% are merged/closed in around a month.

Still, that a small amount of other PRs linger and eventually stay around forever until they are closed as stale after 1 year is less good. I'd be curious if those PRs are mostly waiting on review (I hope not...) or waiting on the PR submitter, but that's probably not easy to find data on.

**Comment by trzecieu** [comment]
Still I'm trying to learn how to correctly interpret these data, last plot showing structure of active pull requests I found most informative.
If we keep focus on issues in at least 1month old you can see trends and actions: 
![image](https://user-images.githubusercontent.com/4076929/68280222-61c9a500-0075-11ea-9eff-0dce5621c4bf.png)
blue arrows are either clean up sessions or git-stale automation, at the moment my assumption is that this pattern will repeat, and amount of open PRs is reduced by automation. 

Here is another graph showing difference between open and closed PRs (quarterly aggregated):
![image](https://user-images.githubusercontent.com/4076929/68281489-08af4080-0078-11ea-9e78-6f69ce9ea936.png)
On average after 2017 there is an increment of 10-28 open pull request each quarter unless automation kicks in. 

We've started to evaluate how automation like stale bot affects our effectiveness in handling pull requests, and situation like this: https://github.com/emscripten-core/emscripten/pull/2440 proves that it can actually help. 
Here is the moment where first time automation kicked in (it was set for closing 2yo issues):
![image](https://user-images.githubusercontent.com/4076929/68283734-647bc880-007c-11ea-8d34-337520381754.png)
You can see 2 spikes, the second spike the execution done on 25th of October 2018. Important is that there is one spike before this - that's the moment where stale bot wrote a comment, which stimulated either author to re-validate if this is still an issue - which could trigger conversation around PR and effectively PR being merged.
