### ISSUE TITLE
Large codebases that use MAIN_MODULE/SIDE_MODULE incur large startup overhead

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#9791]
When using MAIN_MODULE and SIDE_MODULE with a lot code sharing.  The post instantiate time and be very high.  This is largely due to the way dynamic addresses are asssigned using the `fp$` and `g$` helper functions. 

Whenever either to main or side module needs the address is a non-internal symbol it has to call out the JS to fine the address.

We should fine a way to optimize the use case, perhaps by allowing the main module to be statically linked (or more statically linked) or perhaps by allowing fixed load addressed to be assigned to side modules at compile time.

In any case the first step is probably to produce a benchmark that demonstrates this issue, some kind of example code that shared many thousands and symbols between the main and side modules.

**Comment by sbc100** [comment]
@awtcode

**Comment by awtcode** [comment]
Thanks for looking into this @sbc100 :) I've created a simple python script that generates a cpp program with 40k imports here: https://github.com/awtcode/largeimports

It currently takes a very long time for node to complete the execution. The program can be tested by running `node index.js` in the build directory. 

I tested this on the new LLVM backend and I believe a large portion of the time is spent on `___assign_got_enties`.  The post instantiation time is currently too slow for production usage.
fyi @kripken , @dschuff .

**Comment by awtcode** [comment]
@sbc100 , since the current implementation assigns the address of an imported function by adding it to the end of the table during post-instantiation, I believe there should not be much difference if we move this to the build phase? One possible way is to assign the address in `EmscriptenGlueGenerator::generateAssignGOTEntriesFunction` and store it in an immutable global which we then export to the side module. I tried to prototype this idea by making some changes here:

https://github.com/awtcode/binaryen/commit/f88136d7026d506967a05e168066eb08c98e7cda

This is not testable yet but I thought it will be helpful to get the conversation going. Please feel free to let me know your thoughts on this. Thanks.

**Comment by sbc100** [comment]
That seems like a workable approach yes.  Do you mean one immuatable global per function?   One problem is that you don't know which functions the side module might need the address of so you need to do this for every exported function.

Also, this trick only works for the main module.  Any function in the side module still need their table slots assigned at runtime right?

**Comment by sbc100** [comment]
This is kind of like the "static main module" approach I was suggesting, were we fix the addresses of things in the main module at build time.

**Comment by awtcode** [comment]
> That seems like a workable approach yes. Do you mean one immuatable global per function? One problem is that you don't know which functions the side module might need the address of so you need to do this for every exported function.

Yes, we will use one immutable global per function. Do we need to do this for every exported function from the side module? I was under the impression that we only need one global per imported function in the main module.
 
> Also, this trick only works for the main module. Any function in the side module still need their table slots assigned at runtime right?
Yes, I think for now, we will still use the fp$ accessors to assign the slots to functions in the side module. But moving forward, I hope to statically assign their addresses to table_base + offset as well. This would also speed up the loading time.

**Comment by awtcode** [comment]
I did some more exploration today and I believe the only missing part is how to change the initial table size of the main module in the JS after we run wasm-emscripten-finalize.

These are the changes in Emscripten:
https://github.com/awtcode/emscripten/commit/aa01bb7738ee7fb43948ae744a45c511d5fd9199

These are the changes in Binaryen:
https://github.com/awtcode/binaryen/commit/d8cff16d8aa7aa62bbaf45544815aa84bd60a7a0

Please feel free to give your comments. Thanks :)
