### ISSUE TITLE
MAIN_MODULE without EXPORT_ALL does not export js library functions

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9793]
See for example the testcase added in https://github.com/emscripten-core/emscripten/pull/9698 - we need EXPORT_ALL there so that the side module can call `cxa_throw`, which is a JS library function.

It shouldn't be an observable difference if a function is from the JS library or not, so it should be exported like the compiled library code is, probably. I'm not sure of the ramifications of flipping EXPORT_ALL to 1 when MAIN_MODULE, though, so maybe we need something more specific?

**Comment by kripken** [comment]
Oh, this *does* look like a difference between the backends. Fastcomp doesn't export them, but it does add them to `asmLibraryArg` which is then imported into all wasm modules as `env`. So this is a regression on upstream. I'll open a PR.

**Comment by sbc100** [comment]
Does `EXPORT_ALL` effect JS functions?  I thought it was for native functions.  The docs for EXPORT_ALL are not clear to me.

It looks like you explicitly changes the behaviour in 1.38.16 such the EXPORT_ALL was not long enabled for MAIN_MODULES.
