### ISSUE TITLE
Is there any way to reload File IO actions into a JavaScript or other method?

### ISSUE THREAD

**Issue by quank123wip** [emscripten-core/emscripten#9801]
I want to "simulate" a Linux Filesystem in browser, and run something(such as gcc, ccls) in browser with Webassembly.So is there any way run a program which design for local machine in browser without virtualization, just use a custom method instead of File/Network IO in local system?

**Comment by quank123wip** [comment]
As far as I know, there is a solution "browserfs" that provides a "simulated" filesystem in browser.It looks like a Node.js environment in browser.It's for JavaScript or other languages but not webassembly.

**Comment by sbc100** [comment]
Emscripten provides various virtual filesystems yes: https://emscripten.org/docs/api_reference/Filesystem-API.html

See also: 
- https://github.com/tbfleming/cib
- https://browsix.org/

And if you really want to get into the some of the nuts and bolts of this stuff you can build it yourself:
- https://www.youtube.com/watch?v=5N4b-rU-OAA

**Comment by quank123wip** [comment]
thanks
