### ISSUE TITLE
Closure compiler breaks web worker JS by optimizing (Dedicated)WorkerGlobalScope symbols

### ISSUE THREAD

**Issue by tklajnscek** [emscripten-core/emscripten#9805]
I coded up a custom messaging implementation for web workers. When the worker receives a quit message it uses DedicatedWorkerGlobalScope.close() to shut itself down (this is preferred to the main thread terminating the worker as it doesn't get a chance to process the outstanding messages).

When run through the closure compiler it chokes on close() since it doesn't see it as a declared symbol. Similarly 'onmessageerror' also fails (I don't use it, but still). After some digging I realized the other things work because they're declared in closure-externs.js or map 1:1 with symbols on 'Window' which the closure compiler preserves automatically.

Adding close and onmessageerror to closure-externs.js seems to work.

Please let me know if that's the preferred way to address this and I can go ahead and submit a PR.

Sample worker JS that breaks:
```
onmessage = function(e) {
	console.log("Message", e.data);
	close();
}
```

**Comment by kripken** [comment]
@tklajnscek yes, adding to the externs is what we normally do. PR would be great!

More generally, it would be good to upgrade our version of closure compiler as possibly upstream has added those and other ones. However that would take more work.

**Comment by tklajnscek** [comment]
The PR for this has now been merged into incoming!
