### ISSUE TITLE
Build regression in 1.39.1, llvm-ranlib failure: file too small to be an archive

### ISSUE THREAD

**Issue by akien-mga** [emscripten-core/emscripten#9806]
Emscripten builds of [Godot Engine](https://github.com/godotengine/godot) are now failing with Emscripten 1.39.1 and 1.39.2 using `latest-upstream`.

Emscripten 1.39.0 works fine with `latest-upstream`, so it seems to be a regression in 1.39.1.

See godotengine/godot#33374.

The build fails with:
```
[  5%] Linking Static Library ==> main/libmain.javascript.opt.bc
shared:WARNING: Assuming object file output in the absence of `-c`, based on output filename. Please add with `-c` or `-r` to avoid this warning
Ranlib Library         ==> main/libmain.javascript.opt.bc
/opt/emsdk/upstream/bin/llvm-ranlib: error: unable to load 'main/libmain.javascript.opt.bc': file too small to be an archive

OVERVIEW: LLVM Ranlib (llvm-ranlib)

  This program generates an index to speed access to archives

USAGE: llvm-ranlib <archive-file>

OPTIONS:
  -help                             - Display available options
  -version                          - Display the version of this program
scons: *** [main/libmain.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```

The relevant file after the build failure:
```
$ file main/libmain.javascript.opt.debug.bc 
main/libmain.javascript.opt.debug.bc: WebAssembly (wasm) binary module version 0x1 (MVP)
$ ls -l main/libmain.javascript.opt.debug.bc 
-rwxr-xr-x 1 akien akien 311938 Nov  8 10:58 main/libmain.javascript.opt.debug.bc*
```

See https://github.com/godotengine/godot/issues/33374#issuecomment-551495206 for build logs using both 1.39.0 (success) and 1.39.1 (failure).

This was seen on Linux and WSL so far, but might be reproducible on other platforms.

I haven't investigated yet *why* it fails in Godot's build and whether that's something that we should fix ourselves downstream, but since it's a regression in a patch release I figured that it would be worth reporting here in any case.

**Steps to reproduce:**
- Install Emscripten 1.39.1
- Build https://github.com/godotengine/godot/ (`master` branch) with `p=javascript tools=no target=release_debug verbose=yes` and see above `llvm-ranlib` failure.
- Install Emscripten 1.39.0
- Attempt the build again (possibly after cleaning build objects with `scons p=javascript tools=no target=release_debug -c`) and it should work fine.

**Comment by sbc100** [comment]
It looks like the build script need some updating here.   It seems like "Linking Static Library" should be creating a library (with `emar`) not an object file.

**Comment by akien-mga** [comment]
Thanks, it looks indeed like we are using `emcc` instead of `emar`:
https://github.com/godotengine/godot/blob/d1f8fd6384ae8d2caae368d79d1db23654868b98/platform/javascript/detect.py#L85-L87

The contributor who set this up years ago is no longer active, so I'm not sure what problem they were having exactly, but replacing it by `emar` seems to allow building properly (and without warnings) with emscripten 1.39.3.

Downstream PR: godotengine/godot#33635.

There was still some change between 1.39.0 and 1.39.1 which caused this regression (as in, it used to raise warnings but compilation worked nevertheless), so I'll let you see if you want to investigate further or close this as an expected change/bugfix.

**Comment by sbc100** [comment]
The change was that `emranlib` used to do nothing at all.. running on on anything at all would silently work.   As of #9714 `emranlib` actually runs `llvm-ranlib`.    I'm pretty happy with that change.
