### ISSUE TITLE
Malloc behavior on full heap

### ISSUE THREAD

**Issue by dschuff** [emscripten-core/emscripten#9808]
We had a report from a user switching from fastcomp to upstream, that the behavior of malloc when there was no available space, was different. Namely that with fastcomp it would fail with a useful error message, but with upstream there would be an OOB access error instead.
I'm not aware of any interesting differences between fastcomp and upstream on that but it seems worth investigating.

**Comment by kripken** [comment]
Interesting, I can reproduce this with upstream + optimizations + memory growth. It OOBs inside dlmalloc somewhere. Investigating now.
