### ISSUE TITLE
Emscripten produces invalid file paths in source maps on Windows

### ISSUE THREAD

**Issue by RReverser** [emscripten-core/emscripten#9811]
When using `-g4`, Emscripten produces double-escaped paths in `sources` array of source maps on Windows, making them invalid and not possible to load in browser.

For example, if I have a file at location `C:\Users\rreverser\Projects\temp-wasm\temp.c`, the source map contains:

```js
{"version":3,"sources":["C:\\\\Users\\\\rreverser\\\\Projects\\\\temp-wasm/temp.c"]/*,...*/}
```

And devtools show corresponding error trying to load it:

```
Could not load content for http://localhost:5000/C:\\Users\\rreverser\\Projects\\temp-wasm/temp.c : HTTP status code: 404
```

**Comment by kripken** [comment]
Thanks! Probably something wrong in https://github.com/emscripten-core/emscripten/blob/incoming/tools/wasm-sourcemap.py (skimming it now, nothing obvious pops out).

If you have a windows machine, might be quick to just put some debug prints in there and see what's going on...

**Comment by RReverser** [comment]
Looks like the issue is that llvm-dwarfdump already outputs escaped paths (as it outputs quoted strings), but they're never unescaped by Python script, and so end up escaped again by JSON encoder.

**Comment by kripken** [comment]
Interesting. I guess we need to unescape things somewhere. Maybe at the output of llvm-dwarfdump?

**Comment by RReverser** [comment]
Probably, yeah. In every places that extracts a quoted string (comp_dir, include_directories, filename).

**Comment by kripken** [comment]
If you have some time and a windows machine, would be great if you can look into it. I just don't have one myself so it's hard to work on stuff like this.
