### ISSUE TITLE
'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)

### ISSUE THREAD

**Issue by 73UJ34** [emscripten-core/emscripten#9821]
Hello, I'm trying to upgrade our cmake/html5 project from emscripten 1.35.0 to 1.39.2 and I am getting this error when I run it in a browser.

'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)

I created a simple test app that reproduces the problem. I have tried many different ways to set EXTRA_EXPORTED_RUNTIME_METHODS with no luck. Here are the files for the test app:

[main.cpp.txt](https://github.com/emscripten-core/emscripten/files/3833169/main.cpp.txt)
[emscripten_template.html.txt](https://github.com/emscripten-core/emscripten/files/3833173/emscripten_template.html.txt)
[CMakeLists.txt](https://github.com/emscripten-core/emscripten/files/3833175/CMakeLists.txt)
[build.sh.txt](https://github.com/emscripten-core/emscripten/files/3833176/build.sh.txt)

Am I doing something wrong or is this a bug with cmake projects?

Thanks in advance for any advise.
Dave

**Comment by sbc100** [comment]
Can you not add `-s EXTRA_EXPORTED_RUNTIME_METHODS=["ccall"]` to your existing setting for LINK_FLAGS in your `CMakeLists.txt`?

**Comment by 73UJ34** [comment]
Adding this to my CMakeLists.txt file did not change anything:

	set_property(TARGET ${PROJECT_NAME} PROPERTY -s EXTRA_EXPORTED_RUNTIME_METHODS=["ccall", "cwrap"])

I still get the same error.

**Comment by 73UJ34** [comment]
My bad I read it wrong. I have tried not setting EXTRA_EXPORTED_RUNTIME_METHODS and I get the same error.

**Comment by sbc100** [comment]
Most like `set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "-s EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']")`
`

**Comment by 73UJ34** [comment]
That appears to have fixed it. Now I'm getting an error about get_int being unknown. I'll do some more testing.

Thanks for the quick replies.

**Comment by 73UJ34** [comment]
My test app works now. Thanks for your help.
