### ISSUE TITLE
LLVM crash installing "latest" after 1.39.2 release

### ISSUE THREAD

**Issue by TidbitSoftware** [emscripten-core/emscripten#9822]
Using `cd <PATH_TO_EMSDK>; ./emsdk install latest; ./emsdk activate latest` allowed me to successfully build my project as of release 1.39.1, but started failing with 1.39.2. This appears to be an LLVM issue and I will be submitting a bug report to them, but I figured I point this out to you as being an issue.

**Comment by kripken** [comment]
Thanks, and please link to the LLVM bug report here after you file it.
