### ISSUE TITLE
ReferenceError: Can't find variable: IDBFS

### ISSUE THREAD

**Issue by andreyugolnik** [emscripten-core/emscripten#9824]
Hello,

After upgrading to emscripten to the version `1.39.2-fastcomp` I got error:
`ReferenceError: Can't find variable: IDBFS`:

```js
var profilePath = 'my_path';
FS.mkdir(profilePath);
FS.mount(IDBFS, {}, profilePath);
```

Mainstream version doesn't compile my code at all:
```
Fatal: local.get of unknown in arg0 of call to $emscripten_asm_const_int (used by EM_ASM* macros) in function $685.
This might be caused by aggressive compiler transformations. Consider using EM_JS instead.
```

OS: latest macOS.
Tested in browsers: latest Google Chrome and latest Safari.

**Comment by andreyugolnik** [comment]
Compilation flags:
```
-s WASM=0 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall','callMain']"
```

**Comment by kripken** [comment]
Sorry for the inconvenience, this changed in 1.39.1, see the changelog:

https://github.com/emscripten-core/emscripten/blob/incoming/ChangeLog.md#v1391-10302019

(In a build with ASSERTIONS, or at `-O0`, it should have shown you a useful error message. If you built in one of those modes and didn't see one, please let me know as it means something is broken in that helper code.)

**Comment by sbc100** [comment]
For the upstream build failure we do want to look into that.    If you can somehow produce a repro case for that that would be useful.   Doing a debug build might give you a more useful error message than `in function $685` so you can find out which EM_ASM macro is causing this issue.

**Comment by andreyugolnik** [comment]
@kripken thanks a lot, it helps.

@sbc100 thank you, I will try to rebuild game in debug mode a little bit later.

**Comment by andreyugolnik** [comment]
@kripken I have another problem.
After adding `-lidbfs.js`, my application crashes in Safari with the message`longjmp` in the console. But it works fine in Google Chrome.
Removing `-lidbfs.js` solves the problem. But, as expected, removes IDBFS support.
