### ISSUE TITLE
is it possible to compile nodejs to wasm using emscripten

### ISSUE THREAD

**Issue by blizzardzheng** [emscripten-core/emscripten#9825]
i had try to compoile nodeJS with emscripten, but it shows an error of version too low

**Comment by sbc100** [comment]
You most likely won't be able to compile nodejs to emscripten since it is built on v8 and v8 is a JIT compiler that only runs on certain architectures (of which WebAssembly is not one).

**Comment by blizzardzheng** [comment]
so there is no way run?

**Comment by kripken** [comment]
This should be possible, as v8 has a [jitless mode](https://v8.dev/blog/jitless) now. In that mode it uses an interpreter and should be portable to wasm.

When you say

> it shows an error of version too low

What version did it report was too low? Please paste the complete error.
