### ISSUE TITLE
console.log is changed to print

### ISSUE THREAD

**Issue by aeschli** [emscripten-core/emscripten#9829]
Original issue https://github.com/NeekSandhu/onigasm/issues/19

Emscripten 1.39.1

Onigasm uses emscripten with `-s ENVIRONMENT=shell`

The generated `onigasm.js` contains the following snippet:

![image](https://user-images.githubusercontent.com/1378130/68732735-71b22d80-060f-11ea-9449-a8539db0a8b2.png)
```
if (typeof print !== "undefined") { 
        if (typeof console === "undefined") 
            console = {}; 
        console.log = print; 
        console.warn = console.error = typeof printErr !== "undefined" ? printErr : print 
}
```

if 'print' is defined, `console.log` is changed to `print`, causing problems when other code attempts to log something.

I guess there are brackets missing:
```
if (typeof print !== "undefined") { 
    if (typeof console === "undefined") {
        console = {}; 
        console.log = print; 
        console.warn = console.error = typeof printErr !== "undefined" ? printErr : print 
    }
}
```

**Comment by sbc100** [comment]
I believe this in order to handle some JS shells which didn't have `console.log`.  I thought maybe `d8` but it looks like `d8` does include `console.log`.

@kripken do you remember why this was added?  Can we remove it now?

**Comment by kripken** [comment]
Yes, it's for shells that don't have `console.log`. Interesting, which shell now includes it @aeschli ?

**Comment by sbc100** [comment]
I think we can fix it so that it only polyfills when needed.. right now it will polyfill whenever print is available.

**Comment by aeschli** [comment]
Onigasm is a library designed to be used in both Web and NodeJS and maybe also in other environments. To express that and to avoid any dependencies we compile with `-s ENVIRONMENT=shell`.

The bug was discovered when using onigasm in the browser. There both print and console are defined.

**Comment by kripken** [comment]
@aeschli hmm, the "shell" environment is specifically intended for js shells like js (spidermonkey), d8 (v8), jsc (javascriptcore). The "node" environment should be used for node, and "web" for web etc. Are you only using "shell" to save some code size?

**Comment by aeschli** [comment]
We want to avoid any dependencies so onigasm runs in all environments. Please advise if there's a better way.

**Comment by kripken** [comment]
@aeschli What do you mean by "dependencies"? JS support code?

In general, if you want to support all environments, then `ENVIRONMENT=shell` does the opposite, it intentionally does not include support for anything but JS shells like d8. However, it might work if you don't use certain features.

If the goal is to reduce JS support code, we should look into what extra code you want to remove. Is it stuff like the node.js FS support code in shell.js?

**Comment by aeschli** [comment]
I meant dependencies on any platform/runtime feature such as file system, networkd, workers. By avoiding all these advanced features in the c code of onigasm itself (which is easy as it's basically just a computational function), the hope is also that the emscripten runtime gets as minimal as possible. Especially we want to avoid any reference to `require(..)`, even behind flags, as this will cause webpack to complain or start bundling unnecessary code.
It looks like the 'shell' environment is the closest to that, and worked fine so far. No specifying any environment unfortunately results in `require` calls in the compiled code.

**Comment by kripken** [comment]
I see.

If you need almost no runtime support, do you also need almost no JS? In that case, emitting a standalone build, and writing your own custom JS (with only exactly what you need) might work, see https://v8.dev/blog/emscripten-standalone-wasm

**Comment by bolinfest** [comment]
I am using Emscripten to compile Oniguruma as part of vscode-oniguruma. Presumably because the resulting JS could be used on either Node or the web, it is compiled with `-s ENVIRONMENT=shell`. It currently has this unfortunate workaround to rewrite the code generated by Emscripten:

https://github.com/microsoft/vscode-oniguruma/blob/bb4b078835b548e14c783bfe922700eda21b1ea3/scripts/remove-print.js#L11.

On the web, we have the problem where a global `print()` function is defined, which triggers the "print this page" behavior in a web browser! As you can imagine, this a pretty terrible side-effect when trying to log a message. It would be nice if we could remove that workaround.

/cc @alexdima

**Comment by kripken** [comment]
`ENVIRONMENT=shell` is not for node, it's for other JS shells (like d8 and sm). I think if you change that to `ENVIRONMENT=node` it may work. But if the code is meant to work on node and the web, that should be `ENVIRONMENT=node,web`.

(Another option is to just remove that `print()` method, you can do `print = undefined` in an `--extern-pre-js` for example.0
