### ISSUE TITLE
In Chrome: TypeError: Module._malloc is not a function

### ISSUE THREAD

**Issue by QQilin** [emscripten-core/emscripten#9853]
I am compiling my program with such keys (also tried with O2) with emsdk latest
```
em++ -o my.js my.cpp -O3 -s EXPORTED_FUNCTIONS="['_malloc']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['cwrap']" -s ALLOW_MEMORY_GROWTH=1 -std=c++2a -s NO_EXIT_RUNTIME=1 -s NO_FILESYSTEM=1 -fno-exceptions
```
Chrome78: Uncaught (in promise) TypeError: Module._malloc is not a function.
Firefox: all is well, no problem.

```
buffer16 = Module._malloc(16);
```

**Comment by sbc100** [comment]
Seems very strange.  Can you attach some more info?  Is that line of code from my.js?  At what point does it run? 

If you could attach a full simple repro case that would be great.

**Comment by QQilin** [comment]
(index):65 Uncaught (in promise) TypeError: Module._malloc is not a function
    at Object.onRuntimeInitialized ((index):65)
    at doRun (check.js:1)
    at run (check.js:1)
    at runCaller (check.js:1)
    at removeRunDependency (check.js:1)
    at receiveInstance (check.js:1)
    at receiveInstantiatedSource (check.js:1)
onRuntimeInitialized @ (index):65
doRun @ check.js:1
run @ check.js:1
runCaller @ check.js:1
removeRunDependency @ check.js:1
receiveInstance @ check.js:1
receiveInstantiatedSource @ check.js:1
Promise.then (async)
instantiateArrayBuffer @ check.js:1
(anonymous) @ check.js:1
Promise.then (async)
(anonymous) @ check.js:1
Promise.then (async)
instantiateAsync @ check.js:1
createWasm @ check.js:1
(anonymous) @ check.js:1

[check.js.txt](https://github.com/emscripten-core/emscripten/files/3862894/check.js.txt)

A previously compiled version works fine.  Everything works well in Chrome Dev.

**Comment by QQilin** [comment]
I realized that it was my mistake. Chrome cached the very first version of the page that didn't work. Thanks Chrome
