### ISSUE TITLE
Is there any way to modify WebAssembly.Memory after compilation?

### ISSUE THREAD

**Issue by VirtualTim** [emscripten-core/emscripten#9860]
I thought that I could be able to do something like:
```
const INITIAL_TOTAL_MEMORY = 209715200;   //200MB
const WASM_PAGE_SIZE = 64*1024;
module_overrides = {
    TOTAL_MEMORY: INITIAL_TOTAL_MEMORY,
    wasmMemory: new WebAssembly.Memory({
        'initial': INITIAL_TOTAL_MEMORY / WASM_PAGE_SIZE,
        'maximum': INITIAL_TOTAL_MEMORY / WASM_PAGE_SIZE,
        'shared': true
    })
};
Module(module_overrides).then(() => {...}
```

However that throws:
`Module.js:1637 wasm streaming compile failed: LinkError: WebAssembly.instantiate(): memory import 144 is smaller than initial 10240, got 3200`

Basically what I'm trying to do is compile with `-s TOTAL_MEMORY=640MB`, which works well on desktop, but fails to run on mobile (I'm assuming since I can't alloc that much continuous memory). So my plan was to detect mobile then start the module with less memory.

**Comment by VirtualTim** [comment]
Relates to #5069.

**Comment by sbc100** [comment]
I imagine it will easier to do it the other way around.  Build with TOTAL_MEMORY set to a small amount, and then on desktop provide a larger memory, which should be fine.  I think the wasm modules built by emscripten will accept *larger* memories than those they were built to expect, but not a smaller one.

**Comment by kripken** [comment]
You do need to allow memory growth for larger memories to be supported, though.

**Comment by VirtualTim** [comment]
OK. I'm blocked on compiling with `ALLOW_MEMORY_GROWTH` by #9190.
It sounds like when that is fixed I should be able to compile with a smaller memory limit, and if not mobile do what I mentioned in my initial comment.

**Comment by sbc100** [comment]
@kripken are you sure you can't just pass an "too-big" memory to a memory import?  i.e. does "max" mean anything in the memory limits when importing a memory?

**Comment by kripken** [comment]
@sbc100 

`max` means the maximum size for the memory. If it's identical to the initial size, growth is off.

If a wasm has been built **without** memory growth, the imported memory must be identical in size to it. If the size is too big, you'll get `LinkError: imported Memory with incompatible size`. If the size is ok but the incoming memory has growth enable, i.e., has a max larger than the initial, you get `LinkError: imported Memory with incompatible maximum size`.

If a was has been built **with** memory growth, the imported memory's size can be anywhere in the range of allowed sizes that the wasm expects. The imported memory can also have a different maximum, as long as that is in the right range as well.

**Comment by sbc100** [comment]
What about a config where we build without growth, but we don't set a maximum on the imported memory of the wasm module?  

And by "without groth" I mean we don't include any code for handling growth and the actual memory we create at runtime is not growable (i.e. its init an max are the same).

**Comment by kripken** [comment]
Not setting a maximum means growth is enabled. There is no way to say "this wasm module can accept multiple imported memory sizes, but they cannot grow afterwards."

IOW wasm memories have 2 flags, initial and max size, and if they are not identical, the memory can grow up to the max (and if imported, the memory size at import time can be within the allowed range as well).

**Comment by sbc100** [comment]
Right but as well as the import, the memory object itself can also be growable vs non-growable.   What if we create a non-growable memory of the size we want, and pass it to a the webassembly module that doesnt' set a a maximum on its import?

In that case we know the memory can't grow, as does the wasm module (since the memory we gave it at instantiation time was not growable), so don't we have a setup were we can create a memory of whatever size we want, but without much runtime overhead.  Specifically without any JS code for handling growth.

**Comment by VirtualTim** [comment]
@sbc100 Yep, that's pretty much what I was attempting. Memory growth is nice, but it would also be good to have a way to set initial memory after compilation but before the module is initialised. That way I can load the module with different amounts of memory on mobile and desktop.

**Comment by kripken** [comment]
> What if we create a non-growable memory of the size we want, and pass it to a the webassembly module that doesnt' set a a maximum on its import?

Yes, that's possible according to those rules. But the wasm module would support memory growth, so it's the same as compiling with `ALLOW_MEMORY_GROWTH` today. The only difference is that we'd disallow calls to actually grow the memory, but the wasm VM would have compiled in the support.

**Comment by sbc100** [comment]
The other differences is that any attempts to grow the memory would trap right?

In theory a VM could re-compile/re-optimize when it sees that the final memory it was given is not growable.

It does sounds like this is the config that OP wants.

**Comment by VirtualTim** [comment]
I've managed to mostly fix this issue due to the growable memory changes that @brion made.
I'm compiling with a smaller memory limit and if there's enough browser memory doing something like:
```
module_overrides.TOTAL_MEMORY = 640*1024*1024;
Module(module_overrides).then(() => {...}
```
Personally I'd prefer to do this the opposite way around, but if `module_overrides.TOTAL_MEMORY` is less than `-s TOTAL_MEMORY` the wasm initialisation will throw.

I'm happy to consider this fixed, but I do still see value in being able to pass in your own `WebAssembly.Memory` object.
