### ISSUE TITLE
'Promise' is undefined

### ISSUE THREAD

**Issue by 73UJ34** [emscripten-core/emscripten#9867]
I just upgraded from 1.35.0 to 1.39.2 with CMake on MACOs and found out that the web assembly formate is not supported by IE so I linked with -s WASM=0. I then got the error about polyfills which I fixed with -s LEGACY_VM_SUPPORT=1. Now I get the following output in the console:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
SoftAdmin.htm
HTML1300: Navigation occurred.
goglobal
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
SoftAdmin.htm
init http://dave16.graphon.com/goglobal/?useapp=false
SCRIPT5009: 'Promise' is undefined
webappcore.js (477939,3)
still waiting on run dependencies:
dependency: wasm-instantiate
(end of list)
still waiting on run dependencies:
dependency: wasm-instantiate
(end of list)

The last part just keeps repeating. I tried adding Promise with -s EXTRA_EXPORTED_RUNTIME_METHODS=\"['ccall', 'UTF8ToString', 'Promise']\" but that just caused the linker to complain with:

invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: Promise

Google was no help. What am I doing wrong?

**Comment by sbc100** [comment]
Promise is an ES6 feature which is looks like emscripten depends on.     If we want to continue to support IE and ES5 we should probably work around our use of Promises here and/or have a better transpile story.

 What line is the Promise reference coming from?  Most of our use of promises seems to be around wasm loading so I would hope that non-wasm use of emscripten might still be able to avoid using them.

**Comment by 73UJ34** [comment]
I did add -s WASM=0, but the console output implies that wasm is attempting to be loaded. Here's the code chunk with the error being the new Promise at the bottom.

`function getBinaryPromise() {
  // if we don't have the binary yet, and have the Fetch api, use that
  // in some environments, like Electron's render process, Fetch api may be present, but have a different context than expected, let's only use it on the Web
  if (!wasmBinary && (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) && typeof fetch === 'function') {
    return fetch(wasmBinaryFile, { credentials: 'same-origin' }).then(function(response) {
      if (!response['ok']) {
        throw "failed to load wasm binary file at '" + wasmBinaryFile + "'";
      }
      return response['arrayBuffer']();
    }).catch(function () {
      return getBinary();
    });
  }
  // Otherwise, getBinary should be able to get it synchronously
  return new Promise(function(resolve, reject) {
    resolve(getBinary());
  });
}`

This works fine in Chrome and FF.

**Comment by 73UJ34** [comment]
Here is a simple test app that reproduces the problem (the DEBUG files are included):
[Promise.zip](https://github.com/emscripten-core/emscripten/files/3866034/Promise.zip)

**Comment by kripken** [comment]
I think we should add a little Promise polyfill when `LEGACY_VM_SUPPORT` is enabled.

This is a regression in upstream, as in upstream we use wasm2js and implement the non-wasm output in as wasm a manner as possible, using the same APIs. That's a simpler model than the old asm.js support. But it does mean we end up using a Promise in one place.

**Comment by 73UJ34** [comment]
How long will it take for this fix to get into a stable release? Our next release is scheduled for Q1.

**Comment by kripken** [comment]
Once there is a PR, we can probably merge that in in a matter of days, and we tag a release every week or so. So it should be well before Q1, assuming someone has time to open a PR for it.

Maybe you're interested to do that? If so let me know if there's any questions about the process that I can help with!

**Comment by embeddedt** [comment]
Should the polyfill be part of Emscripten itself? Wouldn't it make more sense to have people include a Promise polyfill themselves if necessary? Lots of other projects take the second approach.

The problem I see with providing a built-in polyfill is that when everyone polyfills the features they need, the resulting bundle of code contains a lot of duplicate implementations of the same thing. Using one global, standards-compliant polyfill is better for code size (in my experience) than including many different polyfills in different locations.

It also eases the burden on migration: shrinking bundle size by removing/reducing polyfills can become as simple as removing one global `import`, instead of turning off polyfilling for many different components.

I'm not trying to change the plan here: just trying to get a sense of which way would be preferable.

**Comment by sbc100** [comment]
How about this:

1. Drop all support for ES5 and LEGACY_VM_SUPPORT from emscripten
2. Add support for running bable as post-link phase for those who really needs ES5
3. Find some way to do some minimal amount of testing for IE

TBH I would have imagined that those targeting IE/ES5 would already have a transpiler like that in their build process so (2) might not be necessary, but it would be nice to integrate it if only for our testing purposes.

**Comment by brion** [comment]
My main concern with not including the Promise polyfill in the direct output from emscripten is that if you do `emcc -s WASM=0 -s LEGACY_VM_SUPPORT=1 -o foo.html foo.c` you won't get something that works in IE 11.

Perhaps it belongs in the shell, as equivalent of the top-level application?

**Comment by sbc100** [comment]
What if LEGACY_VM_SUPPORT=1 means we run babel on the output (as a post-link step within emscripten itself) to convert to ES5?

**Comment by 73UJ34** [comment]
I'm guessing that a PR is a Pull Request, but I'm not sure what that entails. Are you suggesting that I try to fix this myself? Seeing as how I don't even know what a Promise is I doubt I will be much help.

**Comment by kripken** [comment]
@sbc100 I think it's useful to keep our output working by default without post-processing tools. Yes, if we run babel ourselves (like we do closure) that would be a way to do that. But that's a large change that we should consider separately. One specific issue to consider is I'm not sure `LEGACY_VM_SUPPORT` is implementable as a post-processing pass that just adds code, as it may modify our codegen. 

I think adding a short Promise polyfill when LEGACY_VM_SUPPORT is on is a good solution for now. Our Promise usage is very minimal, so the polyfill might be just a few lines.

@73UJ34 I see, no worries. Hopefully someone else has time for this soon. If not I can probably get to it by the end of the year, so it should be before your deadline.

**Comment by sbc100** [comment]
I agree with the fact at that we should keep out code working.   However I think it seems reasonable that if you are in the tiny minority who need `LEGACY_VM_SUPPORT` that you should have to install babel in order for the build to succeed.    Does requiring babel to be installed if you want to use `LEGACY_VM_SUPPORT` seem like too much to ask?

I agree its a larger change and won't block a more minimal fix, but I'd still like to know if you think this is a reasonable longer term fix?

**Comment by 73UJ34** [comment]
Thank you all for your attention to this problem. If it does not get fixed in time we have the option to go back to using emscripten 1.35.0. Thanks again.

**Comment by kripken** [comment]
@sbc100 I guess I'm not sure. It depends on how easy it would be for people to install babel and get emcc to use it properly.

**Comment by embeddedt** [comment]
>  It depends on how easy it would be for people to install babel and get emcc to use it properly.

I suppose you could either get `emcc` to run something along the lines of `npx babel`, or even just `require()` Babel (like a bundler would). Either way, Babel is pretty straightforward to install so I don't think it would be that much extra work for users.

Is Babel necessary for this, though? We're not trying to transpile new syntax; we are just polyfilling a new feature. Babel itself doesn't provide polyfills; it can just optionally add import statements for them at the top of a file.

**Comment by sbc100** [comment]
I'd like to be able to use ES6 features (such as Promises) freely in emscripten, and have a tool transpile it down to ES5.  I thought babel did that?    If its not babel we can just the choose whatever the best tool is to doing this.  Trying to ah-hoc monkey patch our own ES6 feature implementation seems like the wrong approach in the long run.

**Comment by embeddedt** [comment]
> I'd like to be able to use ES6 features (such as Promises) freely in emscripten, and have a tool transpile it down to ES5. I thought babel did that? If its not babel we can just the choose whatever the best tool is to doing this.

If you want full ES6 support on ES5 platforms, you need two things:

* A transpiler (i.e. Babel) for converting ES6 syntax (`i => i +1`) to ES5 syntax (`function(i) { return i + 1; }`).
* Polyfills for ES6 features (like `Object.assign`, `Promise`, etc.).

**Comment by sbc100** [comment]
I see.  My point is really the IIUC these are will understood problems in the JS space that have good existing solutions, right?

**Comment by embeddedt** [comment]
> these are [sic] will understood problems in the JS space that have good existing solutions, right?

Yes. Generally speaking, the program that outputs the final JS/HTML file is the one responsible for downlevelling everything. In this case I suppose that would be `emcc`, so I guess `emcc` needs to add the ability to run Babel and/or include `core-js` (the polyfill).
