### ISSUE TITLE
wasm2js import/export minification currently disabled

### ISSUE THREAD

**Issue by kripken** [emscripten-core/emscripten#9879]
We run `minify_wasm_imports_and_exports` before wasm2js, which means the legalization imports like `getTempRet0` are now minified. When wasm2js runs, it may need those, and then it legalizes again.

For now this minification is disabled. Some options:

 * Always pass the non-minified `getTempRet0` etc. in. This would be a hack, but allow minification.
 * Pass wasm2js the minified import names somehow.

**Comment by tklajnscek** [comment]
I think this should be closed - I accidentally stumbled upon this a few times already and it's been fixed/addressed and it's out of date? Minification of imports/exports is enabled by default for WASM and WASM2JS builds in master.

**Comment by kripken** [comment]
Thanks, @tklajnscek , yes, I forgot to close this when I fixed it...
