### ISSUE TITLE
Compile error on Rpi3

### ISSUE THREAD

**Issue by kermitdafrog8** [emscripten-core/emscripten#9887]
Trying to compile in Slackware ARM --current and have the following error.  Any suggestions or help would be appreciated.  If it's possible to compile.

[  7%] Built target AttributeCompatFuncTableGen
[  7%] Built target intrinsics_gen
[  9%] Built target LLVMCore
[  9%] Built target LLVMFuzzMutate
[  9%] Built target LLVMIRReader
[ 16%] Built target LLVMCodeGen
[ 17%] Built target LLVMSelectionDAG
[ 18%] Built target LLVMAsmPrinter
[ 18%] Built target LLVMMIRParser
[ 18%] Built target LLVMGlobalISel
[ 18%] Built target LLVMBinaryFormat
[ 18%] Built target LLVMBitReader
[ 18%] Built target LLVMBitWriter
[ 20%] Built target LLVMTransformUtils
[ 21%] Built target LLVMInstrumentation
[ 21%] Built target LLVMInstCombine
[ 23%] Built target LLVMScalarOpts
[ 24%] Built target LLVMipo
[ 24%] Built target LLVMVectorize
[ 24%] Built target LLVMHello_exports
[ 25%] Built target LLVMHello
[ 26%] Built target LLVMObjCARCOpts
[ 26%] Built target LLVMCoroutines
[ 26%] Built target LLVMLinker
[ 30%] Built target LLVMAnalysis
[ 30%] Built target llvm_vcsrevision_h
[ 30%] Built target LLVMLTO
[ 32%] Built target LLVMMC
[ 32%] Built target LLVMMCParser
[ 33%] Built target LLVMMCDisassembler
[ 34%] Built target LLVMObject
[ 34%] Built target LLVMObjectYAML
[ 34%] Built target LLVMOption
[ 35%] Built target LLVMDebugInfoDWARF
[ 35%] Built target LLVMDebugInfoMSF
[ 37%] Built target LLVMDebugInfoCodeView
[ 40%] Built target LLVMDebugInfoPDB
[ 40%] Built target LLVMSymbolize
[ 41%] Built target LLVMExecutionEngine
[ 41%] Built target LLVMInterpreter
[ 41%] Built target LLVMMCJIT
[ 42%] Built target LLVMOrcJIT
[ 43%] Built target LLVMRuntimeDyld
[ 44%] Built target LLVMTarget
[ 44%] Built target LLVMJSBackendCodeGen
[ 45%] Built target LLVMJSBackendInfo
[ 45%] Built target LLVMJSBackendDesc
[ 47%] Built target LLVMPNaClTransforms
[ 48%] Built target ARMCommonTableGen
[ 49%] Built target LLVMARMCodeGen
[ 49%] Built target LLVMARMInfo
[ 49%] Built target LLVMARMAsmParser
[ 49%] Built target LLVMARMDisassembler
[ 49%] Built target LLVMARMAsmPrinter
[ 50%] Built target LLVMARMDesc
[ 50%] Built target LLVMARMUtils
[ 50%] Built target LLVMAsmParser
[ 50%] Built target LLVMLineEditor
[ 50%] Built target LLVMProfileData
[ 50%] Built target LLVMCoverage
[ 50%] Built target LLVMPasses
[ 50%] Built target DllOptionsTableGen
[ 50%] Built target LLVMDlltoolDriver
[ 50%] Built target LibOptionsTableGen
[ 50%] Built target LLVMLibDriver
[ 51%] Built target LLVMXRay
[ 51%] Built target LLVMTestingSupport
[ 51%] Built target LLVMWindowsManifest
[ 52%] Built target FileCheck
[ 52%] Built target llvm-PerfectShuffle
[ 52%] Built target count
[ 52%] Built target not
[ 52%] Built target yaml-bench
[ 52%] Built target LTO_exports
[ 52%] Built target LTO
[ 52%] Built target llvm-ar
[ 52%] Built target llvm-ranlib
[ 52%] Built target llvm-lib
[ 52%] Built target llvm-dlltool
[ 52%] Built target llvm-config
[ 52%] Built target llvm-lto
[ 52%] Built target llvm-profdata
[ 53%] Built target obj.clang-tblgen
[ 53%] Built target clang-tblgen
[ 57%] Built target clang-headers
[ 57%] Built target ClangSACheckers
[ 57%] Built target StmtDataCollectors
[ 57%] Built target ClangCommentCommandList
[ 57%] Built target ClangAttrVisitor
[ 57%] Built target ClangCommentNodes
[ 57%] Built target ClangStmtNodes
[ 57%] Built target ClangAttrClasses
[ 57%] Built target ClangDeclNodes
[ 57%] Built target ClangAttrImpl
[ 57%] Built target ClangCommentHTMLTags
[ 57%] Built target ClangCommentHTMLTagsProperties
[ 58%] Built target ClangCommentHTMLNamedCharacterReferences
[ 58%] Built target ClangAttrDump
[ 58%] Built target ClangCommentCommandInfo
[ 58%] Built target ClangDiagnosticSema
[ 58%] Built target ClangDiagnosticRefactoring
[ 58%] Built target ClangDiagnosticCrossTU
[ 58%] Built target ClangDiagnosticParse
[ 58%] Built target ClangDiagnosticDriver
[ 58%] Built target ClangDiagnosticAST
[ 58%] Built target ClangDiagnosticFrontend
[ 58%] Built target ClangDiagnosticAnalysis
[ 58%] Built target ClangDiagnosticLex
[ 58%] Built target ClangDiagnosticComment
[ 58%] Built target ClangDiagnosticCommon
[ 59%] Built target ClangDiagnosticGroups
[ 59%] Built target ClangAttrHasAttributeImpl
[ 59%] Built target ClangARMNeon
[ 59%] Built target ClangDiagnosticSerialization
[ 59%] Built target ClangDiagnosticIndexName
[ 59%] Built target ClangAttrList
[ 59%] Built target ClangAttrSubjectMatchRuleList
[ 59%] Built target ClangAttrParserStringSwitches
[ 59%] Built target ClangAttrSubMatchRulesParserStringSwitches
[ 59%] Built target ClangAttrSpellingListIndex
[ 59%] Built target ClangAttrParsedAttrKinds
[ 59%] Built target ClangAttrParsedAttrImpl
[ 59%] Built target ClangAttrTemplateInstantiate
[ 59%] Built target ClangAttrParsedAttrList
[ 59%] Built target ClangAttrPCHWrite
[ 60%] Built target ClangAttrPCHRead
[ 60%] Built target clang-tablegen-targets
[ 62%] Built target clangBasic
[ 63%] Built target clangLex
[ 64%] Built target clangParse
[ 67%] Built target clangAST
[ 67%] Built target clangASTMatchers
[ 68%] Built target clangDynamicASTMatchers
[ 68%] Built target clangCrossTU
[ 70%] Built target clangSema
[ 72%] Built target clangCodeGen
[ 73%] Built target clangAnalysis
[ 73%] Built target clangEdit
[ 73%] Built target clangRewrite
[ 74%] Built target clangARCMigrate
[ 74%] Built target ClangDriverOptions
[ 76%] Built target clangDriver
[ 76%] Built target clangSerialization
[ 78%] Built target clangFrontend
[ 79%] Built target clangRewriteFrontend
[ 79%] Built target clangFrontendTool
[ 79%] Built target clangTooling
[ 80%] Built target clangToolingCore
[ 80%] Built target clangToolingRefactor
[ 80%] Built target clangToolingASTDiff
[ 80%] Built target clangIndex
[ 82%] Built target clangStaticAnalyzerCore
[ 86%] Built target clangStaticAnalyzerCheckers
[ 86%] Built target clangStaticAnalyzerFrontend
[ 86%] Built target clangFormat
[ 87%] Built target diagtool
[ 87%] Built target clang-offload-bundler
[ 88%] Linking CXX executable ../../../../bin/clang
/usr/bin/ld: ../../../../lib/libclangStaticAnalyzerFrontend.a(AnalysisConsumer.cpp.o): in function `clang::ento::createPlistHTMLDiagnosticConsumer(clang::AnalyzerOptions&, std::vector<clang::ento::PathDiagnosticConsumer*, std::allocator<clang::ento::PathDiagnosticConsumer*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clang::Preprocessor const&)':
AnalysisConsumer.cpp:(.text._ZN5clang4ento33createPlistHTMLDiagnosticConsumerERNS_15AnalyzerOptionsERSt6vectorIPNS0_22PathDiagnosticConsumerESaIS5_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_12PreprocessorE+0xa8): undefined reference to `clang::ento::createHTMLDiagnosticConsumer(clang::AnalyzerOptions&, std::vector<clang::ento::PathDiagnosticConsumer*, std::allocator<clang::ento::PathDiagnosticConsumer*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clang::Preprocessor const&)'
/usr/bin/ld: ../../../../lib/libclangStaticAnalyzerFrontend.a(AnalysisConsumer.cpp.o): in function `clang::ento::CreateAnalysisConsumer(clang::CompilerInstance&)':
AnalysisConsumer.cpp:(.text._ZN5clang4ento22CreateAnalysisConsumerERNS_16CompilerInstanceE+0x600): undefined reference to `clang::ento::createHTMLSingleFileDiagnosticConsumer(clang::AnalyzerOptions&, std::vector<clang::ento::PathDiagnosticConsumer*, std::allocator<clang::ento::PathDiagnosticConsumer*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clang::Preprocessor const&)'
/usr/bin/ld: AnalysisConsumer.cpp:(.text._ZN5clang4ento22CreateAnalysisConsumerERNS_16CompilerInstanceE+0x620): undefined reference to `clang::ento::createHTMLDiagnosticConsumer(clang::AnalyzerOptions&, std::vector<clang::ento::PathDiagnosticConsumer*, std::allocator<clang::ento::PathDiagnosticConsumer*> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clang::Preprocessor const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/build.make:200: bin/clang-6.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:12390: tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by sbc100** [comment]
We have no official support for running emscripten except on x86_64 mac/linux/windows.    If you want to try to make it run on arm/linux then you may have some work to do.

It looks like you are trying to build upstream llvm here?  Are you building it yourself using cmake or driving the process with `emsdk`.    If you are building it yourself, can I suggest you trying using `-G Ninja` and using ninja to build it.  It (a) provides more useful diagnostics when a command fails (such as pring the failing command line) and (b) automatically parallelized your build.

Having said that this looks like it might be a general "llvm-on-arm" or "llvm-on-slackware" issue.   You might be better of asking upstream about this, or perhaps look into that slackwhere llvm package?  Does that build for arm?  Presumably yes?

**Comment by kermitdafrog8** [comment]
I will report back if ninja actually builds without errors.
