### ISSUE TITLE
-g flag doesn't output a .wast file, functions included without underscore

### ISSUE THREAD

**Issue by cggallant** [emscripten-core/emscripten#9890]
I've noticed two differences as of Emscripten 1.39.0 compared to the way things worked with 1.38.48 and earlier...

1) Including the `-g` flag when compiling no longer outputs a `.wast` file. Do I need to include another flag to have the .wast file output too? 

The file is very helpful in debugging why something isn't working.

I tried running the `set EMCC_DEBUG=1` command first and was able to track down a generated .wast file in a temp folder.

2) Also, when including a function in the EXPORTED_FUNCTIONS command line array, it appears that you still need to include the underscore character (e.g. `-s EXPORTED_FUNCTIONS=['_main']`) but when you get the .wasm file, the function is in there without the underscore character.

**Comment by sbc100** [comment]
1. I'm not sure that outputting a wast file with `-g` was every an intended feature.  I would advice running `wasm2wat` on the wasm out if you want the a textual version of your final binary.    Perhaps is this is a desirable feature we could put in behind the `-save-temps` flag which gcc and clang normally use to save intermediate files.

2. Yes, for backwards comparability we still continue to require and support the leading underscore on symbol names.   Once we remove fastcomp we are considering removing this.

**Comment by CGerardGallant** [comment]
Thank you.

**Comment by cggallant** [comment]
Thank you
