### ISSUE TITLE
__heapObjectForWebGLType: GL_UNSIGNED_SHORT_5_6_5_REV is missing

### ISSUE THREAD

**Issue by ddovod** [emscripten-core/emscripten#9892]
Hello guys. Big thanks for such an amazing project! You're making the world better = )
I've recently tried to port my application to wasm + webgl using emscripten, it took not more than 3-4 hours, but I faced an issue. I use bgfx library, it tries to call some opengl functions (specifically `glTexImage2D`) with different parameters and checks for errors using `glGetError()`. This way it checks for available features. In short it calls `glTexImage2D` with `GL_UNSIGNED_SHORT_5_6_5_REV` as a texture format. After some investigation I found that this constant maps to the `0x8364` value and it is missing in a `__heapObjectForWebGLType` function so the application just craches with exception
```
TypeError: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': parameter 9 is not of type 'ArrayBufferView'.
```
The solution is to add `case 0x8364:` to the `__heapObjectForWebGLType` body. I didn't find the place in emscripten sources where this function is defined, it only exist in the app.js file.
Could you please help me with this?
Thanks a lot!

**Comment by kripken** [comment]
Looks like the source code for that is here: https://github.com/emscripten-core/emscripten/blob/095b841dd7d75466d06d70eff61c2ad55745c49d/src/library_webgl2.js#L113

Would be great if you can open a PR with that @ddovod :smiley:

**Comment by ddovod** [comment]
Sure, thank you very much! Closing this for now
#9902
