### ISSUE TITLE
Demangling code enabled even if DEMANGLE_SUPPORT=0

### ISSUE THREAD

**Issue by aaronsgiles** [emscripten-core/emscripten#9905]
In libcxxapi/src/cxa_default_handlers.cpp, the default termination handler is set to demangling_terminate_handler, which invokes the demangler if exceptions are enabled, and thus implicitly causes it to be included, regardless of the DEMANGLE_SUPPORT option.

I discovered this when porting from a 1.5-year-old toolchain to the latest, and my binary size increased by over 60k (truly a ridiculous amount of code for demangling). This was all due to the whole itanium_demangle namespace getting referenced.

There is a LIBCXXABI_SILENT_TERMINATE option for the lib that just points demangling_terminate_handler at std::abort, which is fine for my needs, but required me to manually investigate and rebuild. After that, my binary size was back down to expected levels.

An alternative would be to introduce a mechanism to still provide the nice abort_message but with a mangled name so as not to create so much overhead.

Regardless, this was surprising undocumented changed behavior across a toolchain upgrade, and should at least be noted somewhere.

**Comment by sbc100** [comment]
It sounds like we need a libcxxabi variant that is built with `LIBCXXABI_SILENT_TERMINATE`.

I'm curious what changed in the last 1.5 year that make this start happening.

**Comment by aaronsgiles** [comment]
Looks like @kripken hand-removed it in a previous version on 7/25/2014, but then the lib was updated to 8.0.0 on 7/19/2019 and that blew away the change.

**Comment by aaronsgiles** [comment]
Obviously need a more sustainable solution. :)

**Comment by sbc100** [comment]
Ah.. that would be my fault then... <facepalm>.   In wonder why we didn't see major regressions because of this in the test suite?   Maybe we don't do size bench-marking with DEMANGLE_SUPPORT=0?

**Comment by aaronsgiles** [comment]
It's also #ifdef'ed out if exception handling is disabled, so maybe the test suite mostly does no-exception builds?

**Comment by kripken** [comment]
Thanks @aaronsgiles ! Great find, sorry this happened, we should have caught it earlier.

Fix in #9914 + testing so it doesn't happen again (yeah, we didn't have size tests for exceptions...).
