### ISSUE TITLE
Add support for `WebAssembly.Function`

### ISSUE THREAD

**Issue by sbc100** [emscripten-core/emscripten#9909]
Currently when we add JS functions to the WebAssembly table we use a horrible (and slow) hack  which involves creating a new wasm module for each JS function.

The new `WebAssembly.Function` which is being standardized will allow us to add these functions far more easily and directly.  We should start feature detecting and using this API ASAP.

**Comment by backes** [comment]
Note that I already uploaded a PR for this: https://github.com/emscripten-core/emscripten/pull/9908

**Comment by backes** [comment]
This can be closed, now that #9908 has landed.
