### ISSUE TITLE
pass NULL pointer

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [emscripten-core/emscripten#9911]
I wanna to use the FFmpeg decoder in WebAssembly but I cannot use the method:
```c
avcodec_open2 (AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options)
```
I wanna to pass `options = NULL` but I cannot be able to generate in Javascript something relevant to pass to the method.
Do you have any idea who to do that ?

Thanks for your help
Marc-Antoine

**Comment by brion** [comment]
A null pointer has an integer value of 0, which you can pass from JS. If that's not working for you, can you show the calling code you've got so far and what's happening (error messages etc)?

**Comment by MarcAntoine-Arnaud** [comment]
Thanks for your replie, it's what I have understood to pass a 0 but it not works.

For the javascript part I try to do that:
```javascript
var prores_codec = avcodec.find_decoder_by_name("prores")
const codec_context = avcodec.alloc_context3(prores_codec);
console.log("Codec Context " + codec_context);
console.log("Prores codec pointer " + prores_codec);
var options = 0;
const openning_status = avcodec.open2(codec_context, prores_codec, options);
```

I got in the console:
```
Codec Context 14427120
Prores codec pointer 1930584
TypeError: SYSCALLS.getStreamFromFD is not a function
```

I don't found lot of relevant information about the `getStreamFromFD` ...
Thanks for yourr feedback

**Comment by MarcAntoine-Arnaud** [comment]
I close it because it's linked to the configuration of FFmpeg compilation.
I have not found the answer now but it can be linked to threading activation ...
