### ISSUE TITLE
Strange default umask value

### ISSUE THREAD

**Issue by drpowell** [emscripten-core/emscripten#9916]
https://github.com/emscripten-core/emscripten/blob/dc5407e52f49bcd40a85f32cdcf4a07842078ed9/src/library_syscall.js#L22

The default umask (0777) is unusual and causes files to be created as unreadable by anyone.  A more typical umask would by 022

**Comment by sbc100** [comment]
Sure we can change that to 022.  Why do you care?  I guess for nodefs where maybe permissions are real?

**Comment by drpowell** [comment]
Exactly, with nodefs files are created with no permission bits - and cannot be chmoded without changing umask first

**Comment by sbc100** [comment]
Feel free to upload a patch + test.  Otherwise, I've marked this as "good first bug" and "help wanted" since it seems pretty straight forward.
