### ISSUE TITLE
Many calls to Math.fround with wasm2js despite not setting PRECISE_F32

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#9923]
While working on switching ogv.js decoders from fastcomp to upstream for JS builds, I found that in the opus audio codec which uses a lot of float32 math, I was seeing a *lot* of calls to Math.fround, on almost every floating-point operation.

IIRC with fastcomp, those only got emitted if PRECISE_F32 was set to 1; by default 64-bit math was used and things only got rounded when written to memory.

I'm able to double the audio decoding speed in IE 11 (my legacy JS target, whee) by manually stripping out the calls in a post-processing step. Impact is probably a lot smaller on newer browsers that don't need to polyfill Math.fround though.

Would it be possible to have wasm2js emit or not emit the rounding calls based on the emscripten PRECISE_F32 setting? Or alternately, should the setting be documented as applying to fastcomp backend only?

**Comment by sbc100** [comment]
My guess is that PRECISE_F32 is currently a fastcomp-only option, but that making it work with wasm2js should be possible.  

Am I right in assuming this is a JS-only option though?  We should probably warn if people try to set this option when building for wasm?

**Comment by brion** [comment]
Yeah I don't think it has any meaning for Wasm output, as Wasm does f32 directly.

**Comment by kripken** [comment]
That's all correct, yeah - `PRECISE_F32` only makes sense for fastcomp (historically, it was there before JS added `Math.fround`, I believe, and when the speed issue was much bigger). With the wasm backend's wasm2js, we try to do a correct lowering of wasm to JS, so we include `Math.fround` calls as needed.

I didn't realize this makes such a difference on IE11, interesting! Adding an option to remove those calls, as a JS optimizer pass, might be reasonable to do (I'd rather not modify wasm2js itself in binaryen). However, if you already have a post-processing approach that works for you @brion then that might not be worth it, and we should just document the issue (that `PRECISE_F32` is fastcomp-only) as you said?

**Comment by brion** [comment]
Yeah, IE 11 is diminishing returns so I don't mind having to make the hack on my end. ;) Added a pull req with a doc change to the settings.
