### ISSUE TITLE
Memory leak in embind when returning a reference to a C++ object

### ISSUE THREAD

**Issue by luisfonsivevo** [emscripten-core/emscripten#9930]
I have this C++ vector class from PhysX:

```
class PxVec3
{
  public:
	float x, y, z;

	PX_CUDA_CALLABLE PX_FORCE_INLINE PxVec3& operator*=(float f)
	{
		x *= f;
		y *= f;
		z *= f;
		return *this;
	}
};

EMSCRIPTEN_BINDINGS(physxjs)
{
	class_<PxVec3>("Vec3")
			.constructor<float, float, float>()
			.property("x", &PxVec3::x)
			.property("y", &PxVec3::y)
			.property("z", &PxVec3::z)
			.function("op_mul", &PxVec3::operator*=);
}
```

The vector multiplier method supposedly returns a reference to itself. But when I call it from JSland:

```
var vec1 = new Px.Vec3(1, 2, 3);
var vec2 = vec1.op_mul(5);

console.log(vec1.x, vec1.y, vec1.z, vec1.$$.ptr);
//5 10 15 5450800
console.log(vec2.x, vec2.y, vec2.z, vec2.$$.ptr);
//5 10 15 5453456
```

We see that vec1 was multiplied properly by 5, but the op_mul function returns a duplicate of vec1 instead of vec1 itself (notice the internal pointers are different). This becomes a huge problem over millions of operations. I have `-s ALLOW_MEMORY_GROWTH=1` so this causes the heap size to balloon to hundreds of megabytes.

```
console.log("before: " + Px.HEAP8.length / 1024 / 1024 + " mb");
//before: 16 mb

for(var i = 0; i < 10000000; i++) //10 million iterations
	vec1.op_mul(1);

console.log("after: " + Px.HEAP8.length / 1024 / 1024 + " mb");
//after: 256 mb!!!! should still be 16!
```

Surely embind should return a wrapper of the same C++ object when a class method returns a reference to itself (or a reference to anything) so that I don't have to call delete() on all the needless duplicates.

**Comment by juj** [comment]
> Surely embind should return a wrapper of the same C++ object when a class method returns a reference to itself

That would require embind to do an AST traversal to analyze all bound code to make such a deduction on its own. Perhaps this could be fixed by adding a bind attribute, or a different form, e.g.
```c++
.function_returns_ref_to_self("op_mul", &PxVec3::operator*=);
```
to let embind know to do a different treatment of the return value.

**Comment by luisfonsivevo** [comment]
I modified `GenericBindingType` at wire.h:344 to prevent embind from copying any return values, ever:

```
template<typename T>
struct GenericBindingType {
	typedef typename std::remove_reference<T>::type ActualT;
	typedef ActualT* WireType;

	//function returning a reference
	static WireType toWireType(T& v) {
		return &v;
	}

        //function returning an object (use the value immediately and drop all references to it)
	static WireType toWireType(T&& v) {
		return &v;
	}

	//pass an object into a function as an arg (works as is; no change)
	static ActualT& fromWireType(WireType p) {
		return *p;
	}
};
```

Also remove `const` at bind.h:557:
```ClassType& ptr```

This makes embind behave like the WebIDL binder, where all JS objects are only a wrapper around a raw pointer and you have to be extra careful with memory management. This would fix the bug, but I imagine that embind was written this way on purpose and I probably just broke a dozen other projects that rely on the original (broken?) behavior.

**Comment by kripken** [comment]
cc @chadaustin

**Comment by luisfonsivevo** [comment]
Here's another even worse side effect of embind's copying references: I can't even modify submembers. For example, another PhysX class, `PxSceneDesc`, owns a gravity vector:

```
class PxSceneDesc
{
  public:
	PxVec3 gravity;
};

EMSCRIPTEN_BINDINGS(physxjs)
{
	class_<PxSceneDesc>("SceneDesc")
			.property("gravity", &PxSceneDesc::gravity);
}
```

And then when I try to modify the gravity in javascript:

```
sceneDesc.gravity = new Px.Vec3(0, -10, 0);
console.log(sceneDesc.gravity.y); //-10
sceneDesc.gravity.y = -9.81;
console.log(sceneDesc.gravity.y); //still -10
```

And it leaks memory too! Whenever I access `sceneDesc.gravity`, embind returns a copy of gravity and not a reference to the original as it should. The hotfix I mentioned in my previous comment again fixes the problem.

**Comment by RazerTang** [comment]
same proble, how you fix it?
