### ISSUE TITLE
gzseek and gztell function signature mismatch

### ISSUE THREAD

**Issue by niekvlessert** [emscripten-core/emscripten#9952]
I installed the latest Emscripten yesterday on Debian 10, but my old project wouldn't work anymore. When linking I get this;
```
wasm-ld: warning: function signature mismatch: gztell
>>> defined as (i32) -> i32 in libvgmplay.a(VGMPlay_8cb594a0.c.o)
>>> defined as (i32) -> i64 in /root/.emscripten_cache/wasm-obj/libz.a(gzlib_667366dc.c.o)

wasm-ld: warning: function signature mismatch: gzseek
>>> defined as (i32, i32, i32) -> i32 in libvgmplay.a(VGMPlay_8cb594a0.c.o)
>>> defined as (i32, i64, i32) -> i64 in /root/.emscripten_cache/wasm-obj/libz.a(gzlib_667366dc.c.o)
```

When running the code and using one of those functions I get
```
Uncaught RuntimeError: unreachable
    at wasm-function[478]:0x61ad5
```

**Comment by sbc100** [comment]
Did you rebuild everything in `libvgmplay.a` with the new toolchain?

Those warning mean that `libvgmplay.a` saw a different signature for those function at compile time compared to `libz.a`.  

The return value of `gztell` is `z_off_t` which is defined in your zconf.h file.    The zconf.h that `libz.a` is compiled with is in `$HOME/.emscripten_cache/wasm-obj/ports-builds/zlib/zconf`.   Can you verify that `libvgmplay.a` is being compiled with that same header file?

`z_off_t` should be defined in your zconf.h to `off_t` which itself is defined in `./system/lib/libc/musl/arch/emscripten/bits/alltypes.h` to be `_Int64`.    So `
libvgmplay.a` is building with the wrong type for `z_off_t` somehow...

**Comment by niekvlessert** [comment]
Thx, the zlib header files included with the software were outdated.
