### ISSUE TITLE
Why i just get .exe file instead of .js or .wasm file when using CMakeLists.txt to compile?

### ISSUE THREAD

**Issue by For-thewin** [emscripten-core/emscripten#9954]
I just follow the tutorial in Emscripten.cmake

# To use this toolchain file with CMake, invoke CMake with the following command line parameters
# cmake -DCMAKE_TOOLCHAIN_FILE=<EmscriptenRoot>/cmake/Modules/Platform/Emscripten.cmake
#       -DCMAKE_BUILD_TYPE=<Debug|RelWithDebInfo|Release|MinSizeRel>
#       -G "Unix Makefiles" (Linux and OSX)
#       -G "MinGW Makefiles" (Windows)
#       <path/to/CMakeLists.txt> # Note, pass in here ONLY the path to the file, not the filename 'CMakeLists.txt' itself.

# After that, build the generated Makefile with the command 'make'. On Windows, you may download and use 'mingw32-make' instead.

But i just get a .exe file. i Have tried some solutions.
1、I try add "SET(CMAKE_EXECUTABLE_SUFFIX ".html")" in CMakeLists.txt but i get a wrong .html file. 
2、I try add SET_TARGET_PROPERTIES(HelloWorld PROPERTIES LINK_FLAGS "-s WASM=1"), but there is a error which is "gcc.exe: error WASM=1: NO such file or directory"

So who can tell me where is the problem. I don't think the CmakeList file is wrong because i use the CMakefiles from "@\emsdk-master\upstream\emscripten\tests\cmake\cmake_with_emval".

**Comment by juj** [comment]
Hmm, that looks like old help. Try using `emcmake` wrapper:

```
emcmake cmake /path/to/CMakeLists.txt
```

e.g. https://github.com/emscripten-core/emscripten/blob/incoming/tests/test_other.py#L745

**Comment by For-thewin** [comment]
That works. Thank you very much.------------------ 原始邮件 ------------------
发件人: "juj"<notifications@github.com>
发送时间: 2019年12月4日(星期三) 晚上8:46
收件人: "emscripten-core/emscripten"<emscripten@noreply.github.com>;
抄送: "For-thewin"<1227355175@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [emscripten-core/emscripten] Why i just get .exe file instead of.js or .wasm file when using CMakeLists.txt to compile? (#9954)



Hmm, that looks like old help. Try using emcmake wrapper:
 emcmake cmake /path/to/CMakeLists.txt  
e.g. https://github.com/emscripten-core/emscripten/blob/incoming/tests/test_other.py#L745
 
&mdash;

**Comment by ngzhian** [comment]
This issue is resolved and can be closed @sbc100
