### ISSUE TITLE
What is this cryptic html code inside my Wasm file?

### ISSUE THREAD

**Issue by 5ut** [emscripten-core/emscripten#9960]
If you open the .wasm file generated by emscripten in a text editor, about 3/4 down the page you get some very scrambled html code. 

`</giftssteve-linkbody.});
	mount (199FAQ</rogerfrankClass28px;feeds<h1><scotttests22px;drink) || lewisshall#039; for lovedwaste00px;ja:ã‚simon<fontreplymeetsuntercheaptightBrand) != dressclipsroomsonkeymobilmain.Name platefunnytreescom/"1.jpgwmodeparamSTARTleft idden, 201);
}
form.viruschairtransworstPagesitionpatch`

For example. 

Looks like some form of obfuscation but curious as to what this is. Thanks

**Comment by kleisauke** [comment]
Looks like this is from Brotli, see:
https://github.com/google/brotli/blob/master/c/common/dictionary.bin

Try to compile Brotli with `-DBROTLI_EXTERNAL_DICTIONARY_DATA` to exclude the dictionary.

**Comment by juj** [comment]
Emscripten itself does not compress with Brotli, so I suppose your project contained Brotli library as part of the build?

(btw that dictionary contents looks just brain dead.. They scraped the web for common words to pre-create a high frequency dictionary? so now we get bits used by default for optimized entropy for viruses, joints, drugs and rated asian girls. Wow. Just wow.)

If we do have this part of Emscripten (and I missed this somewhere?), we should add that flag to exclude dictionary contents.

**Comment by 5ut** [comment]
Yeah, it does use Brotli. That makes more sense. Very weird. 

Thanks for the info.
