### ISSUE TITLE
emscripten_futex_wake fails with pthreads & memory growth

### ISSUE THREAD

**Issue by brion** [emscripten-core/emscripten#9963]
A number of pthreads library functions access `HEAP8` or `HEAP32` without guards for memory growth. I found that `emscripten_futex_wake` caused hangs using the dav1d AV1 decoder with pthreads & memory growth enabled together, as it would fail out when called with a futex address above the current `HEAP8` view's size.

Adding a guard like this:

```js
    if (addr > HEAP8.length) {
      updateGlobalBufferAndViews(wasmMemory.buffer);
    }
```

at the top of the function seems to resolve it for me, but there are other functions similarly affected.

**Comment by brion** [comment]
(Note that while assignments and reads in the form `HEAP8[x]` etc are transformed into wrapper functions that are safe, the Atomics accesses and other uses such as checking length are not so transformed.)

**Comment by kripken** [comment]
Good point, yes - we should also guard against heap accesses that are not loads and stores. It could be done in a similar way, I think. But it would need to be careful not to affect the startup code (perhaps just ignoring the global scope would be enough).

**Comment by kripken** [comment]
The relevant code for this is `growableHeap` in `tools/js-optimizer.js`, which does the transformation. The extra helper functions should go alongside the current ones, in `src/growableHeap.js`.

**Comment by brion** [comment]
@kripken ah great, I think I can rig something up from there. :)

If I have it take any HEAP* references that aren't caught by the assignment traversals and stick in a function that does the `wasmMemory.buffer != buffer` dance, it should work for remaining code with a little bit of overhead. Would turn something like

```js
if (ptr > HEAP8.length) { ... }
Atomics.wait(HEAP32, ptr);
```

into something like

```js
if (ptr > (GROWABLE_HEAP_CHECK_VIEWS(),HEAP8).length) { ... }
Atomics.wait((GROWABLE_HEAP_CHECK_VIEWS(),HEAP32), ptr);
```

The downside is that it could introduce more calls into the update check function than are necessary if the view is used multiple times with the same pointer range validity, but it's best to err on the side of caution. :)

I'll whip up a patch and see if it works.

**Comment by brion** [comment]
Aesthetically that comma expression pains me, I'll probably just make functions that return each view. Functionally the same, but looks nicer and could compress better, and makes the AST traversal easier.

**Comment by VirtualTim** [comment]
@brion While you're doing that would you be able to take a look at moving the whole growableHeap function from js-optimizer.js to acorn-optimizer.js? This would also fix #9190.
I took a bit of a look myself, but I didn't get much further than replacing 'assign' and 'sub' with 'AssignmentExpression' and 'ArrayExpression'.

**Comment by brion** [comment]
@VirtualTim I'll take a peek.

**Comment by kripken** [comment]
Great, thanks @brion! :smiley:

I agree that functions that return the view are better, maybe `GROWABLE_HEAPU16()` etc.?
