### ISSUE TITLE
USE_PTHREADS + FULL_ES3 + OFFSCREEN_FRAMEBUFFER = link error

### ISSUE THREAD

**Issue by xprogram** [emscripten-core/emscripten#9965]
If I try and compile `tests/webgl_draw_triangle.c` with the following command:
```
emcc -s USE_PTHREADS=1 -s FULL_ES3=1 -s OFFSCREEN_FRAMEBUFFER=1 -lGL tests/webgl_draw_triangle.c -o test.html
```

I get the following error log:
```
error: undefined symbol: emscripten_webgl_create_context
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: emscripten_webgl_make_context_current
Error: Aborting compilation due to previous errors
```

I was able to reproduce it with Emscripten 1.39.3 and 1.39.2; fastcomp and upstream backends both produce the same result. This only happens with the above combination of `-s` flags; if any one of them is removed, compilation succeeds.

**Comment by VirtualTim** [comment]
You can probably compile with `-s EXPORTED_FUNCTIONS=['emscripten_webgl_create_context']` to get things working. This still sounds like a bug in Emscripten, but you might be able to use that until it's fixed.

**Comment by xprogram** [comment]
Unfortunately, adding to `EXPORTED_FUNCTIONS` doesn't work:
```
emcc -s USE_PTHREADS=1 -s FULL_ES3=1 -s OFFSCREEN_FRAMEBUFFER=1 -lGL -s EXPORTED_FUNCTIONS="['_main','_emscripten_webgl_create_context','_emscripten_webgl_make_context_current']" tests/webgl_draw_triangle.c -o test.html
```
This results in the same output as before.

I also tried setting `EXPORT_ALL` and adding the missing functions to `DEFAULT_LIBRARY_FUNCS_TO_INCLUDE` without success.

**Comment by sbc100** [comment]
Looks like the symbols files were out of date.  Fix on the way.
