### ISSUE TITLE
Zlib version trouble

### ISSUE THREAD

**Issue by niekvlessert** [emscripten-core/emscripten#9978]
I've been reading in another issue that zlib header files are not included by default and that is it recommended the project should provide their own. The project I'm transpiling does that, it provides the header files from the latest version from 2017, 1.2.11. However this causes trouble with for example zseek. I ended up copying header files out of .emscripten_cache/wasm-bc/ports-builds/zlib. I learned those are version 1.2.8 from 2013. Now compiling works fine. Why not upgrade zlib to 1.2.11?

**Comment by sbc100** [comment]
No reason in particular.  Do you need the newer version?   Feel free to send a PR to update the port in `tools/ports/zlib.py` is you like.

**Comment by niekvlessert** [comment]
Well, most projects will probably have the 2017 version by now, it will save people some time I guess. LCM is a good thing. :) I'm busy with my transpiling stuff for now but I might give it a shot later.

**Comment by VirtualTim** [comment]
The zlib port is located here: https://github.com/emscripten-ports/zlib
If you want to do the work to update the port that would be great 👍.
