### ISSUE TITLE
wast file not generated when compiling with -g

### ISSUE THREAD

**Issue by boyanio** [emscripten-core/emscripten#9984]
It seems the wast file is not generated anymore when compiling with `-g`.

```
emcc (Emscripten gcc/clang-like replacement) 1.39.4 (commit cf90c72aba3e09ffd96d90a6fdf87095ed5351b8)
```

## Example

I have the following `.c` program:

```
int add(int a, int b) {
  return a + b;
}
```

I am compiling it using this command:

```
emcc -g -s EXPORTED_FUNCTIONS="['_add']" add.c -o add.wasm
```

Before, I used to get a `.wasm` file and a `.wast` one, but now the latter is not generated anymore.

**Comment by sbc100** [comment]
It was never indented that `-g` produce a wast file in addition to the wasm file.    I think perhaps some version of emscripten used to do this because this is the second report I've seen like this.

If you want to see the wat version of your code you can run `wasm2wat` (from wabt) or `wasm-dis` (from binaryen) on the resulting wasm file.

**Comment by kripken** [comment]
Also note that both those tools are included with the emsdk, so you don't even need to build them yourself - they are in `emsdk/upstream/bin/`.

**Comment by boyanio** [comment]
Thanks for clarifying this. Yes, in the previous version I had (I think it was 1.38.something), it used to do so. I also think the documentation used to state so, but I don't seem to find it now. I already use `wasm2wat`, so it is not an issue for me.

@kripken Thanks, I didn't know this - I used to build it myself :)

**Comment by jamesknightgd** [comment]
As an entire emscripten newbie, I ran into this issue today in the documentation https://emscripten.org/docs/compiling/WebAssembly.html#debugging-webassembly which states _"...but building with -g will emit both a text and a binary wasm"_, but emcc does not seem to output the .wast file. Perhaps docs need updating to reflect that this is no longer supported?

**Comment by sbc100** [comment]
Yes.. looks like that docs are out of date.   Feel free to open a bug or PR.
