### ISSUE TITLE
error: undefined symbol: gzclose

### ISSUE THREAD

**Issue by chhaunkar96** [emscripten-core/emscripten#9985]
When I'm trying to compile OpenCV code with following the command, An error is coming.
**Command**
`sudo /home/xyz/emsdk/upstream/emscripten/em++ ./test_wasm.cpp  -s WASM=1 -I/usr/local/include/opencv4/ -L/home/xyz/opencv/build_wasm/lib  -llibopencv_core -llibopencv_calib3d  -llibopencv_imgproc -llibopencv_photo -llibopencv_flann -llibopencv_features2d  -o test_wasm/test_wasm.html  -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_FUNCTIONS='["_image_input"]' -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']" -std=c++11  -s DISABLE_EXCEPTION_CATCHING=0 `

**Error**:
```
error: undefined symbol: gzclose
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: gzeof
error: undefined symbol: gzgets
error: undefined symbol: gzopen
error: undefined symbol: gzputs
error: undefined symbol: gzrewind
Error: Aborting compilation due to previous errors
shared:ERROR: '/home/xyz/emsdk/node/12.9.1_64bit/bin/node /home/xyz/emsdk/upstream/emscripten/src/compiler.js /tmp/tmptCnzix.txt' failed (1)

```

**Other info**
Ubuntu 18.4, Opencv 4.1

**Comment by sbc100** [comment]
You are missing the zlib library.   One way to link against that is it to build with `-s USE_ZLIB=1`.

**Comment by chhaunkar96** [comment]
Thank you much @sbc100 . It was very helpful to me. Thanks, again.. :)
