### ISSUE TITLE
Wasm-ld error: unknown file type

### ISSUE THREAD

**Issue by miaaaahmed97** [emscripten-core/emscripten#9988]
Hi. I'm sorry if this question sounds amateurish but i'm new to emscripten.
I am trying to build a .cpp file to .wasm using emscripten. My command is 

`em++ -std=c++17 hello.cpp -s WASM=1 -o hello.html -ISEAL/native/src/ -ferror-limit=40 --target=x86_64-unknown-linux-gnu`

But i get this error:

`wasm-ld: error: unknown file type: /tmp/emscripten_temp_WjXsN4/hello_0.o
shared:ERROR: '/home/maria/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_WjXsN4/hello.wasm --allow-undefined --lto-O0 /tmp/emscripten_temp_WjXsN4/hello_0.o -L/home/maria/emsdk/upstream/emscripten/system/local/lib -L/home/maria/emsdk/upstream/emscripten/system/lib -L/home/maria/.emscripten_cache/wasm-obj /home/maria/.emscripten_cache/wasm-obj/libc.a /home/maria/.emscripten_cache/wasm-obj/libcompiler_rt.a /home/maria/.emscripten_cache/wasm-obj/libc-wasm.a /home/maria/.emscripten_cache/wasm-obj/libc++-noexcept.a /home/maria/.emscripten_cache/wasm-obj/libc++abi-noexcept.a /home/maria/.emscripten_cache/wasm-obj/libdlmalloc.a /home/maria/.emscripten_cache/wasm-obj/libpthread_stub.a /home/maria/.emscripten_cache/wasm-obj/libc_rt_wasm.a --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --strip-debug --export __wasm_call_ctors --export __data_end --export main --export malloc --export free --export setThrew --export __errno_location --export fflush --export _ZSt18uncaught_exceptionv --export __cxa_find_matching_catch --export __cxa_is_pointer_type --export __cxa_can_catch -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=16777216 --global-base=1024' failed (1)

Can someone please help me
`

**Comment by sbc100** [comment]
emscrpten/wasm is its own architecture so don't want to pass `--target=x86_64-unknown-linux-gnu`.. by doing this you are asking clang to produce an x86 object file which wasm-ld can't process.

**Comment by miaaaahmed97** [comment]
If i remove `--target=x86_64-unknown-linux-gnu`, i get this error instead

`In file included from hello.cpp:3:
In file included from SEAL/native/src/seal/seal.h:6:
In file included from SEAL/native/src/seal/biguint.h:9:
In file included from SEAL/native/src/seal/memorymanager.h:10:
In file included from SEAL/native/src/seal/util/defines.h:62:
In file included from SEAL/native/src/seal/util/clang.h:20:
In file included from /home/maria/emsdk/upstream/lib/clang/10.0.0/include/x86intrin.h:13

/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:188:10: error: use of undeclared identifier '__builtin_ia32_readeflags_u32'
  return __builtin_ia32_readeflags_u32();
         ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:194:3: error: use of undeclared identifier '__builtin_ia32_writeeflags_u32'
  __builtin_ia32_writeeflags_u32(__f);
  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:284:10: error: use of undeclared identifier '__builtin_ia32_crc32qi'
  return __builtin_ia32_crc32qi(__C, __D);
         ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:305:10: error: use of undeclared identifier '__builtin_ia32_crc32hi'
  return __builtin_ia32_crc32hi(__C, __D);
         ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:326:10: error: use of undeclared identifier '__builtin_ia32_crc32si'
  return __builtin_ia32_crc32si(__C, __D);
         ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:354:10: error: use of undeclared identifier '__builtin_ia32_rdpmc'
  return __builtin_ia32_rdpmc(__A);
         ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:360:10: error: use of undeclared identifier '__builtin_ia32_rdtscp'
  return __builtin_ia32_rdtscp(__A);
         ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/ia32intrin.h:369:3: error: use of undeclared identifier '__builtin_ia32_wbinvd'
  __builtin_ia32_wbinvd();
  ^
In file included from hello.cpp:3:
In file included from SEAL/native/src/seal/seal.h:6:
In file included from SEAL/native/src/seal/biguint.h:9:
In file included from SEAL/native/src/seal/memorymanager.h:10:
In file included from SEAL/native/src/seal/util/defines.h:62:
In file included from SEAL/native/src/seal/util/clang.h:20:
In file included from /home/maria/emsdk/upstream/lib/clang/10.0.0/include/x86intrin.h:15:
In file included from /home/maria/emsdk/upstream/lib/clang/10.0.0/include/immintrin.h:14:
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:33:5: note: '__builtin_isless' declared here
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:50:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:67:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:129:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:159:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:189:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:216:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:239:19: error: use of undeclared identifier '__builtin_ia32_punpckhwd'
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:260:19: error: use of undeclared identifier '__builtin_ia32_punpckhdq'
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:287:19: error: use of undeclared identifier '__builtin_ia32_punpcklbw'
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:310:19: error: use of undeclared identifier '__builtin_ia32_punpcklwd'
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:331:19: error: use of undeclared identifier '__builtin_ia32_punpckldq'
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:352:19: error: use of undeclared identifier '__builtin_ia32_paddb'
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:373:19: error: use of undeclared identifier '__builtin_ia32_paddw'
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:394:19: error: use of undeclared identifier '__builtin_ia32_paddd'
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:416:19: error: use of undeclared identifier '__builtin_ia32_paddsb'
    return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:439:19: error: use of undeclared identifier '__builtin_ia32_paddsw'
    return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:461:19: error: use of undeclared identifier '__builtin_ia32_paddusb'
    return (__m64)__builtin_ia32_paddusb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:483:19: error: use of undeclared identifier '__builtin_ia32_paddusw'
    return (__m64)__builtin_ia32_paddusw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:504:19: error: use of undeclared identifier '__builtin_ia32_psubb'
    return (__m64)__builtin_ia32_psubb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:525:19: error: use of undeclared identifier '__builtin_ia32_psubw'
    return (__m64)__builtin_ia32_psubw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:546:19: error: use of undeclared identifier '__builtin_ia32_psubd'
    return (__m64)__builtin_ia32_psubd((__v2si)__m1, (__v2si)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:569:19: error: use of undeclared identifier '__builtin_ia32_psubsb'
    return (__m64)__builtin_ia32_psubsb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:592:19: error: use of undeclared identifier '__builtin_ia32_psubsw'
    return (__m64)__builtin_ia32_psubsw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:616:19: error: use of undeclared identifier '__builtin_ia32_psubusb'
    return (__m64)__builtin_ia32_psubusb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:640:19: error: use of undeclared identifier '__builtin_ia32_psubusw'
    return (__m64)__builtin_ia32_psubusw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:667:19: error: use of undeclared identifier '__builtin_ia32_pmaddwd'
    return (__m64)__builtin_ia32_pmaddwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:688:19: error: use of undeclared identifier '__builtin_ia32_pmulhw'
    return (__m64)__builtin_ia32_pmulhw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:709:19: error: use of undeclared identifier '__builtin_ia32_pmullw'
    return (__m64)__builtin_ia32_pmullw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:732:19: error: use of undeclared identifier '__builtin_ia32_psllw'
    return (__m64)__builtin_ia32_psllw((__v4hi)__m, __count);
                  ^
/home/maria/emsdk/upstream/lib/clang/10.0.0/include/mmintrin.h:754:19: error: use of undeclared identifier '__builtin_ia32_psllwi'
    return (__m64)__builtin_ia32_psllwi((__v4hi)__m, __count);
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
41 errors generated.
shared:ERROR: '/home/maria/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=4 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/include -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/local/include -std=c++17 -ISEAL/native/src/ -ferror-limit=40 -DEMSCRIPTEN hello.cpp -Xclang -isystem/home/maria/emsdk/upstream/emscripten/system/include/SDL -c -o /tmp/emscripten_temp_5_ONRq/hello_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)
`

**Comment by sbc100** [comment]
Your code is importing an x86-only header.   It probably needs a little porting to run on non-x86 platforms like emscripten.   Take a look at SEAL/native/src/seal/util/clang.h line 20, if its not already that include should be guarded with some kind of "ifdef" for the x86 architecture.

**Comment by miaaaahmed97** [comment]
@sbc100 Thankyou! That helped.

**Comment by s0l0ist** [comment]
@miaaaahmed97 this is also in my fork of SEAL inside clang.h where I’ve included the emscripten recommended intrinsics header in place of the x86 one. Feel free to pull my fork and do a diff on the master branch.

**Comment by sbc100** [comment]
I guess this can be closed now?
