### ISSUE TITLE
[possible bug] why is emconfigure adding the -m64 option?

### ISSUE THREAD

**Issue by binarykitchen** [emscripten-core/emscripten#999]
... there shouldn't be anything about 64 bit architectures in javascript.

in this gist you can see that emconfigure was adding the `-m64` option:
https://gist.github.com/binarykitchen/5230096

how to reproduce? do exactly like on that gist, the steps 0, 1, 2 then 5 and 6.

when you have run `./../emscripten/emconfigure ./configure --enable-static --disable-thread` you'll can open the `config.mak` file and see the `-m64` option there.

isn't this a bug? shouldn't emconfigure remove this option?

**Comment by juj** [comment]
I believe it's not feasible for emconfigure to inject into the execution of the configure script in a way to detect this kind of thing for all projects, although I'm not at all an expert on how ./configure scripts work. Should this be closed as something that Emscripten can't do?
